### ISSUE TITLE
ValidationProblemDetails creation from ModelStateDictionary with Exceptions added return  the errors property with "The input was not valid." and not the Exception Message

### ISSUE THREAD

**Issue by luizfbicalho** [dotnet/aspnetcore#31395]
### Describe the bug
If I add some exceptions to a controller API ModelState property, and pass this to the ValidationProblemDetails to return on the Bad Request, I get only the "The input was not valid." on the return result.

### To Reproduce
In my API controller I Have a post Method Like this
```
        public virtual async Task<IActionResult> Post([FromBody] T value, CancellationToken ct)
        {
            try
            {
                await ExecuteCreateServiceAsync(value, ct);
                return Ok(value);
            }
            catch (ServiceException sx)
            {
                Modelstate.TryAddModelException("", sx);
            }

         var problemDetails = new ValidationProblemDetails(c.ModelState)
        {
            Type = "error/modelvalidation",
            Title = "An Error Occurred here",
            Status = StatusCodes.Status400BadRequest,
            Detail = "More details on errors.",
            Instance = HttpContext.Request.Path
        };
        return new BadRequestObjectResult(problemDetails)
        {
            ContentTypes = { "application/problem+json" }
        };
      }
```
and the return json is this

```
{
  "errors": [
    "The input was not valid.",
    "The input was not valid."
  ],
  "type": "error/modelvalidation",
  "title": "An Error Occurred here",
  "status": 400,
  "detail": "More details on errors.",
  "instance": "/api/Profile"
}
```

### Further technical details
- ASP.NET Core version 5.0.4
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.21077.7
 Commit:    c36b2408a7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.21077.7\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version 
Visual Studio 2019 Version 16.10.0 Preview 1.0

**Comment by pranavkm** [comment]
In general, MVC does not return arbitrary exceptions messages to the client (since it doesn't know if it contains any sensitive information). You could consider using the TryAddModelError overload that accepts a string value which should serialize as expected:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.tryaddmodelerror?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_ModelBinding_ModelStateDictionary_TryAddModelError_System_String_System_String_

**Comment by luizfbicalho** [comment]
> In general, MVC does not return arbitrary exceptions messages to the client (since it doesn't know if it contains any sensitive information). You could consider using the TryAddModelError overload that accepts a string value which should serialize as expected:
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.tryaddmodelerror?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_ModelBinding_ModelStateDictionary_TryAddModelError_System_String_System_String_

The problem is not return exception sensitive infomation, is the message "The input was not valid.", it makes no sense, I mean you add the exeption to the response, and only returns this message.
