### ISSUE TITLE
Compression versions of scoped css appear in an additional directory on publish

### ISSUE THREAD

**Issue by fuzl-llc** [dotnet/aspnetcore#31398]
This is a follow up to issue #29179 that I created a while back. It has been marked as closed.  While most of it was fixed, there was a part of the solution that was not completed and was supposedly split off to be tracked elsewhere.  I asked the following near the end of that issue but have heard no response in a few weeks, most likely due to its closed status:

@pranavkm said, "You're right, compression versions of scoped css appear in an additional directory. We'll track fixing this but this shouldn't affect your published blazor-wasm apps" ... Was this css issue meant to be addressed in 5.0.3 and if not, where exactly is this css issue being tracked?

I've searched and I can't find any other issue tracking this...  does it exist?  If not, can this issue be used to track it?

**Comment by SteveSandersonMS** [comment]
We believe this is resolved in newer previews. Please try .NET 6 preview 7 or later and let us know if this still affects your app. Thanks!
