### ISSUE TITLE
Please add mapping for .msg in FileExtensionContentTypeProvider

### ISSUE THREAD

**Issue by meghma** [dotnet/aspnetcore#31407]
### Describe the bug
Missing { ".msg", "application/vnd.ms-outlook" }

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by blowdart** [comment]
From https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L15

>// - This table was initially copied from IIS and has many legacy entries we will maintain for backwards compatibility.
>// - We only plan to add new entries where we expect them to be applicable to a majority of developers such as being
>// used in the project templates.

It doesn't meet our criteria for adding. You can [add it yourself](https://weblog.west-wind.com/posts/2020/Jun/12/Adding-Additional-Mime-Mappings-to-the-Static-File-Provider) when using the static file middleware.

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#fileextensioncontenttypeprovider
