### ISSUE TITLE
VS is slow to start making requests of Language Servers

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#31416]
In VS we are currently providing both TextMate and SemanticTokens colorization. The idea is that TextMate colorization will finish first (giving people a general idea of the document shape) and then when project load finishes Semantic Tokens will come behind it with a more accurate view. We've run into two problems with this approach:
1. TextMate is sometimes wrong in edge-cases, and a VS issue means that those "wrong" classifications can override the SemanticTokens results, which obviates our "iterative pass" model.
2. TextMate isn't THAT much faster than SemanticToken. While TM is definitely faster than ST the difference may not be worth it. When I launch a default Blazor project I wait a solid couple of seconds while it tries to get either colorization pass. TM always comes in first, with ST following ~1 second later. Considering that the total time passed was ~4 seconds and only ~1 second had TM but not ST, AND TM makes the colors wrong in some edge cases, is it even worth it?

Some things to consider:
- What does removing TM do to "Time to first color" on first startup?
- Do we value the fact that TM provides SOME colors even in the case that the LSP has crashed, or maybe the project is broken?
- Does this mean anything for VSCode, where we don't have the "override" problem?

**Comment by ryanbrandenburg** [comment]
[I used this commit ](https://github.com/dotnet/aspnetcore-tooling/commit/c59fa42306c735cf1d4783b6f5389099e30959a2) to remove the TextMate grammar. 

The following were my first impression findings
1. Having and not having TextMate seem to have about the same TTFC (Time to first color). Considering that TextMate is supposed to be the faster one that feels like a strike against keeping it.
2. If the LSP crashes (I crashed mine on accident while testing, couldn't repro :( ) without TextMate you get NO color updates, which sucks, but I don't know if we'd keep TextMate just for that considering we want to avoid LSP crashes at all costs, and the rest of the experience is broken in that state too.
3. Editing an already open file seems to colorize just a HAIR slower without TextMate but
    1. It also won't flash when semantic colors correct it.
    2. It was such a close call that I'm going more off feeling cause I can't time it by hand reliably.
    3. Both are too slow for my preference anyway, I assume it's because we have to update the project system first.
4. The worst part about the startup experience was (and continues to be with this change) waiting for things to get to a "Project Ready" state. I think getting us to a faster state there will do a lot toward making the whole system feel better (because I assume it'll make every project update/request faster as well).

My reaction given those thoughts is we should get rid of the TextMate Grammar (at least for VS), but I'm curious to hear what other people think.

Also @NTaylorMullen I think you mentioned something which would complicate removing TextMate the other day but I didn't quite catch it, could you go into that a little bit here?

**Comment by NTaylorMullen** [comment]
Awesome synopsis @ryanbrandenburg! One thing that I'd be really really curious about is if you do the same experiment in VSCode what's your experience there? 

@gundermanc given Ryan's evaluation of removing TextMate colorization for perf reasons what's your take on all the above?

@dbaeumer do you have any opinions here based on experiences you've seen in VSCode about relying too heavily or too little on semantic colorization? Aka, with VSCode's mature semantic colorization approach have you found that it could potentially replace the colorization aspects of TextMate in the long run?

> Also @NTaylorMullen I think you mentioned something which would complicate removing TextMate the other day but I didn't quite catch it, could you go into that a little bit here?

Sure can totally go into detail. SOoooo we can't truly remove TextMate for 1 reason: It defines where certain languages start and others end. That's important because the language boundaries are adopted by language-configuration.json and influence what commenting type is used at various portions of the document (`@*` vs. `//` vs. `<!--`), what brace matching pattern is used, what indenting pattern is used, word pattern for completion etc. Now that being said we absolutely could optimize our TextMate grammar towards defining language boundaries and not colorization, that alone would probably be a huge net win from the language-configuration.json perspective but would require colorization to be sufficient with semantic colorization only.

**Comment by dbaeumer** [comment]
@NTaylorMullen we had a discussion about this in VS Code and decided to always keep the two pass approach for the following reasons:

- in a remote case the syntax pass (TextMate) always happens on the client (even in a browser) whereas the semantic pass always happens in the remote and therefore might have greater delays.
- in a pure browser setup there is not remote so without TextMate there would be no coloring at all.

But I don't know if these are things you need to consider for VS.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen we had a discussion about this in VS Code and decided to always keep the two pass approach for the following reasons:
> 
> * in a remote case the syntax pass (TextMate) always happens on the client (even in a browser) whereas the semantic pass always happens in the remote and therefore might have greater delays.
> * in a pure browser setup there is not remote so without TextMate there would be no coloring at all.
> 
> But I don't know if these are things you need to consider for VS.

Thanks for the clarification! Ya I'd be curious how we operate when there are greater delays, that's a great point. I think if anything though we could probably benefit from significantly simplifying our TextMate grammar based on this info

**Comment by gundermanc** [comment]
>in a remote case the syntax pass (TextMate) always happens on the client (even in a browser) whereas the semantic pass always happens in the remote and therefore might have greater delays.

To this point, in LiveShare, we currently have a hack in place that rejects any responses during the round trip of which, the user made an edit, to ensure the LSP requests stay in sync.

The net impact is that in LiveShare, your colors will consistently have potentially seconds of delay.

Unless LiveShare finishes up my synchronization spike, this will continue to be an issue.

**Comment by gundermanc** [comment]
>A VS issue means that those "wrong" classifications can override the SemanticTokens results

Note that this behavior isn't set in stone. You can absolutely customize your classifications to supersede one another, including setting all of your semantic tokens classifications to supersede the TextMate classifications.

We could also look at generalizing this behavior if it's enough of a problem.

>I wait a solid couple of seconds while it tries to get either colorization pass

This seems like a candidate for an Editor bug. With the various extensibility efforts underway, low latency, high throughput in-proc colorization via TextMate or some alternative is going to become more of a priority.

**Comment by ryanbrandenburg** [comment]
Hmm, so it sounds to me like the expectation from the editor is that the TextMate should be faster than it is in the first place, and anyway we can't COMPLETELY remove TextMate. There's an existing issue which [tracks improving that speed](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1250184).

Given all of the above my recommendation would be: Talk with the people in charge of TextMate and communicate our priority on their existing issue. If they make that fix we can re-evaluate and likely won't have to do anything further. If the timeline is gonna be too long for us we can look into simplifying the TM grammar and see if that makes it noticeably faster.

**Comment by NTaylorMullen** [comment]
> Hmm, so it sounds to me like the expectation from the editor is that the TextMate should be faster than it is in the first place, and anyway we can't COMPLETELY remove TextMate. There's an existing issue which [tracks improving that speed](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1250184).
> 
> Given all of the above my recommendation would be: Talk with the people in charge of TextMate and communicate our priority on their existing issue. If they make that fix we can re-evaluate and likely won't have to do anything further. If the timeline is gonna be too long for us we can look into simplifying the TM grammar and see if that makes it noticeably faster.

@gundermanc would be that person 😉. My bet is that it's a long while out but i'll let him respond

**Comment by gundermanc** [comment]
>My bet is that it's a long while out but i'll let him respond

My understanding is that it's not committed yet but it's something Neeraja is aware of being important as part of the overall shift to OOP via LSP. 

@olegtk FYI.

**Comment by olegtk** [comment]
We do have a backlog item (listed above) tracking VS TextMate implementation perf improvements, but it's too general (lacks specific bugs or explicit partner asks) so it's not yet committed. This case sounds like a perfect case, can somebody please file a bug for the Editor documenting these issues?

**Comment by ryanbrandenburg** [comment]
Tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1312678.

**Comment by ryanbrandenburg** [comment]
Let's figure out the exact customer scenarios this is affecting, and what other non-Razor scenarios might be affected by this slowness.

**Comment by ryanbrandenburg** [comment]
Updated the title to reflect what we've learned.

**Comment by ryanbrandenburg** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388999 tracks this work on the VS side.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg this good to close out?
