### ISSUE TITLE
ssh dotnet certificate

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#31415]
### Describe the bug

Originally posted on Developer Community:

https://developercommunity.visualstudio.com/t/ssh-dotnet-certificate/1383442

When running dotnet project.dll —URLS https://0.0.0.0:5001/ 
via bash/shellscript (Mac Big Sur) and you open de webpage 

A certificate issue occurs, this only happens when you run the script via ssh. When you launch local dotnet project.dll —URLS https://0.0.0.0:5001/ it all works fine

Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[3]
The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run the following commands 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate.

A certificate issue occurs, this only happens when you run the script via ssh. When you launch local dotnet project.dll —URLS https://0.0.0.0:5001/ it all works fine

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn are those two invocations expected to behave the same or not?

**Comment by adityamandaleeka** [comment]
Triage: This is a macOS security feature. The SSH process likely doesn't have access to the certificate.
