### ISSUE TITLE
AzureAD.WebSite.csproj and CreateDefaultBuilderApp.csproj don't exist in AspNetCore.sln

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#31436]
The project exists and is referenced in Azure.slnf:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Azure/Azure.slnf#L11

But isn't included in AspNetCore.sln causing the following error when running `dotnet restore src/Azure/Azure.slnf` 

```
D:\dotnet\aspnetcore\src\Azure\AzureAD\test\testassets\AzureAD.WebSite\AzureAD.WebSite.csproj : Solution file error MSB5028: Solution filter file at "D:\dotnet\aspnetcore\src\Azure\Azure.slnf" includes project "src\Azure\AzureAD\test\testassets\AzureAD.WebSite\AzureAD.WebSite.csproj" that is not in the solution file at "D:\dotnet\aspnetcore\AspNetCore.sln".
```

**Comment by Youssef1313** [comment]
Also CreateDefaultBuilderApp.csproj doesn't exist in AspNetCore.sln:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DefaultBuilder/DefaultBuilder.slnf#L8

**Comment by dougbu** [comment]
1. Should fix this but need to confirm these test assets aren't amoung those that must be restored after everything else (or just about) has been packed
2. Should extend existing CodeCheck.ps1 rule that ensures every project in AspNetCore.sln exists. Additional check should make sure every project mentioned in a *.slnf file is also in AspNetCore.sln

**Comment by Youssef1313** [comment]
I think everything is okay after #37114
