### ISSUE TITLE
querystring different from client

### ISSUE THREAD

**Issue by xp44mm** [dotnet/aspnetcore#31434]
i send a request from client
```
http://localhost:53603/sample/test1?foo=bar&abc=('xyz'*'123')
```
the query string is:
```
?foo=bar&abc=('xyz'*'123')
```
but in controller i get:
```
UrljsonExample.Controllers.SampleController: Information: ?foo=bar&abc=(%27xyz%27*%27123%27)
UrljsonExample.Controllers.SampleController: Information: ?foo=bar&abc=(%27xyz%27*%27123%27)
UrljsonExample.Controllers.SampleController: Information: ?foo=bar&abc=(%27xyz%27*%27123%27)
```
by followig code:
```f#
[<ApiController>]
[<Route("[controller]/[action]")>]
type SampleController(_logger:ILogger<SampleController>) =
    inherit ControllerBase()

    [<HttpGet>]
    member this.Test1() = 
        _logger.LogInformation(this.Request.QueryString.Value)
        _logger.LogInformation(this.Request.QueryString.ToString())
        _logger.LogInformation(this.Request.QueryString.ToUriComponent())
```
Strings on the server side have more escape chars, though not causing any trouble, How do I get a string that exactly matchs the data sent by the client?

**Comment by Tratcher** [comment]
`Request.QueryString.Value` is the original query string as received from the client. The encoding would have been added by the client before sending the request. You can verify that using a network trace, a browsers networking tools, or Kestrel's [connection logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#connection-logging).

You can access `Request.Query["abc"]` to get the decoded version of query parameters.
