### ISSUE TITLE
ArPow stage 2: implementing source-build CI

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#31445]
To make sure ArPow (arcade-powered source-build) keeps working in this repo, we need to add it to PR validation. We also need it to run in the official build to publish source-built artifacts that can be tested downstream.

Let us know when an official build runs with ArPow enabled, and the source-build team will look at it to greenlight the artifacts or make fixes.

See <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md> for ArPow CI onboarding info.

For <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md>

**Comment by MichaelSimons** [comment]
cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Ah, I opened the same tracking issue in https://github.com/dotnet/aspnetcore/issues/31423. I'll close that one since this one has a bit more detail.

**Comment by MichaelSimons** [comment]
@JunTaoLuo, do you have an ETA on when this will be complete?  This will be blocking the ArPow effort soon.

**Comment by JunTaoLuo** [comment]
It's been on my list since last week but I haven't made much progress due to other priorities. I do plan to get a PR out in the preview 5 timeline and address additional followup issues in preview 6, if any is identified.
