### ISSUE TITLE
ASP .NET Identity Core does not validate emails comply with RFC 3696

### ISSUE THREAD

**Issue by xantari** [dotnet/aspnetcore#31443]
### Describe the bug
ASP .NET Identity core is not validating email's follow RFC 3696.

There are several issues with this:

1. The Default allowed username / email character list doesn't allow for apostrophes, even through apostrophes are valid in email's as long as they occur before the @ sign. Often times ASP .NET Identity is setup to make the email and username the same thing, and this fails for emails with apostrophes out of the box.

See here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.useroptions.allowedusernamecharacters?view=aspnetcore-5.0

2. When fixing it to include an apostrophe in the AllowedUsernameCharacters (link above) to include an apostrophe for example it does not validate the email (and subsequently the username as well) has the apostrophe BEFORE the @ sign according to RFC 3696.

### To Reproduce

Simply create a user account with ASP .NET Identity Core where the username and email contain an apostrophe in the username and email.

Once you see the default failure, add an apostrophe to the AllowedUserNameCharacters list, and you will see that it now succeeds with say this example:

opts.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+'";

Example emal and username to use:

foo'bar@gmail.com

But it also succeeds then with this example:

foobar@g'mail.com

The "g'mail.com" should be considered invalid in an email address as that doesn't follow RFC 3696.

### Exceptions (if any)

None when allowing apostrophe in the email, but should fail when it doesn't follow RFC 3696.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

ASP .NET Identity Core 5.0 / .NET Core 5.0

**Comment by blowdart** [comment]
Let's be honest, the only way to confirm an email address is valid is to send an email to it. ASP.NET Identity has the ability to do this. The validation on input is only there to help catch typos, it's not meant for full validation at all.

Also, as you say, usernames and emails can be different (although we keep them the same by default), so username validation itself is an entirely different beast.

Given that there's email confirmation built in, a much more useful way to validate emails, the effort in trying to write an RFC conforming checker has a low cost/benefit ratio. It's not something I'd consider that useful.
