### ISSUE TITLE
Blazor Component with a parameter type of EventCallback incorrectly fills in a selected completion item for the value e.g. OnClick=""

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/aspnetcore#31447]
I have reported this issue via Visual Studio 2019 Version 16.10.0 Preview 1.0 so that should have any logs you need to investigate.

https://developercommunity.visualstudio.com/t/Blazor-Component-with-a-parameter-type-o/1388296

**Details from Developer Community Issue:**
I have a razor component which is using a Third Party Telerik `TelerikButton` component. 

**N.B.** 
I don't think this issue is related to Telerik components specifically, but think it would be any component that has a `[Parameter]` property with a type of `Microsoft.AspNetCore.Components.EventCallback` or `Microsoft.AspNetCore.Components.EventCallback<T>` 

For example in my razor component if I type out a new `TelerikButton` component .e.g. 
`<TelerikButton>Button Text</TelerikButton>` 

Then I start adding the `OnClick` attribute to the `TelerikButton` component by typing `OnClick`, like so:
`<TelerikButton OnClick>Button Text</TelerikButton>` 

when I add the `=` sign the tooling automatically adds the double quotes `""` in for me, like so:
`<TelerikButton OnClick="">Button Text</TelerikButton>` 

at the same time as adding the double quotes `""` it also offers up a list of possible values to put into those quotes and generate the event method for me. 

An example for this: 
![image](https://user-images.githubusercontent.com/47532258/113322002-12d87b80-930c-11eb-9ab2-827447440063.png)

If I choose "**Create method** Callback()" or "**Create method** Callback(MouseEventArgs)" I end up with an extra closing bracket in between the double quotes `""` like so:
![image](https://user-images.githubusercontent.com/47532258/113322047-1e2ba700-930c-11eb-8dd8-30dd1207c67d.png)

**Comment by NTaylorMullen** [comment]
@adrianwright109 Do you happen to be using any third party extensions that could be modifying your Razor experience? Seeing the completion items in your screenshot are not something we typically provide.

**Comment by adrianwright109** [comment]
Hi @NTaylorMullen,

Yes I forgot to say that I have ReSharper installed in Visual Studio. I wasn't aware that it was adding a number of different completions over and above the standard set.

So perhaps I need to report this issue to JetBrains?

**Comment by NTaylorMullen** [comment]
> So perhaps I need to report this issue to JetBrains?

Yes unfortunately!
