### ISSUE TITLE
Update IdenitityModel dependencies to 6.10.0

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#31454]
https://github.com/dotnet/aspnetcore/blob/2afcac2d152c0faca2f0f43407e71820408dc614/eng/Versions.props#L196-L198

https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/

6.10.0 is out with some useful bug and perf fixes. Update the depdendency version and run some of our security samples for manual testing.

**Comment by blowdart** [comment]
Also check that Identity.Web doesn't have an updated dependency

**Comment by Tratcher** [comment]
> Also check that Identity.Web doesn't have an updated dependency

It does, but I'll let @jmprieur address that after their next update.

**Comment by jmprieur** [comment]
@Tratcher @blowdart : why don't we want Microsoft.Identity.Web to have the updated dependency?

**Comment by Tratcher** [comment]
@jmprieur you're pushing a new version of Microsoft.Identity.Web after you update your IdentityModel dependencies, right? We can update ASP.NET's Microsoft.Identity.Web dependency after that. No point in changing it twice.

**Comment by jmprieur** [comment]
@Tratcher : yes we are going to release today or on Monday, Microsoft.Identity.Web 1.9.0 which leverages Wilson 6.10.0
cc: @jennyf19
