### ISSUE TITLE
Hot reload no longer working for simple markup change in Blazor Server app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31459]
Repro steps:

- Install 6.0.100-preview.3.21201.11
- `dotnet new blazorserver`
- `dotnet watch`
- Modify markup in Pages/Index.razor

Expected result: hot reload
Actual result: app restart and refresh

@pranavkm @mkArtakMSFT

**Comment by danroth27** [comment]
Looks like https://github.com/dotnet/sdk/pull/16648 broke hot reload in Razor unfortunately. Reverting the change makes hot reload work again.

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/sdk/pull/16702
