### ISSUE TITLE
Special character `/` selects completion item `@...` and commit character `>` commits the `@...` completion item

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#31469]
![SpecialCharCommit](https://user-images.githubusercontent.com/14852843/113373298-643e3600-931f-11eb-933a-2273ded77dcf.gif)

Also note how the `/` is wiped out.

**Comment by TanayParikh** [comment]
I think this'll be external on platform. `/` should not select the `@...` completion item. Leaving it here to discuss during triage.

**Comment by NTaylorMullen** [comment]
Same thing as: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1305289

Should ensure both are closed out once we get confirmation this is client refactor related.
