### ISSUE TITLE
Non-allocating Use middleware extension method

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#31463]
## Background and Motivation

While profiling an app I noticed the two largest allocations were coming from the [Use](https://github.com/dotnet/aspnetcore/blob/b12b64e829feda5dc5854566ae548e4145f0e851/src/Http/Http.Abstractions/src/Extensions/UseExtensions.cs#L21) extension method. A `Func<Task>` and a lambda capture, equivalent to ~94 bytes per request.

The proposed API will remove both per-request allocations.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder
{
    public static class UseExtensions
    {
        public static IApplicationBuilder Use(this IApplicationBuilder app, Func<HttpContext, Func<Task>, Task> middleware)
+       public static IApplicationBuilder Use(this IApplicationBuilder app, Func<HttpContext, RequestDelegate, Task> middleware)
    }
```

## Usage Examples

Before:
``` C#
app.Use(async (context, next) =>
{
    await next();
});
```

New:
```C#
app.Use(async (context, next) =>
{
    await next(context);
});
```

## Alternative Designs

No.

## Risks

More overloads isn't always great as it can be detrimental to the developer experience. Fortunately the beginning of both the new and old overloads is the same and the only difference will be when invoking the `next` method.

It would be nice if we could somehow promote using the new overload over the old one to let developers know they can avoid the implicit allocations.

## Additional Information

Possible implementation:
```C#
public static IApplicationBuilder Use(this IApplicationBuilder app, Func<HttpContext, RequestDelegate, Task> middleware)
{
    return app.Use(next =>
    {
        Func<HttpContext, Task> n = (c) => next(c);
        return context =>
        {
            return middleware(context, n);
        };
    });
}
```

**Comment by davidfowl** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
> Before:
> 
> ```cs
> app.Use(async (context, next) =>
> {
>     await next();
> });
> ```
> 
> New:
> 
> ```cs
> app.Use(async (context, next) =>
> {
>     await next(context);
> });
> ```

Aren't those signatures ambiguous? How can the compiler tell if next is `Func<Task>` or `Func<HttpContext, Task>`?

**Comment by BrennanConroy** [comment]
Looks like the compiler can disambiguate based on return value. I.e. when you type `await next()` vs. `await next(context)` it can figure out which one to use.

**Comment by Tratcher** [comment]
Which return value does intellisence recommend first?

**Comment by BrennanConroy** [comment]
The first one, and unfortunately it doesn't show multiple options when typing `next`. It does show the new one before the old one when typing `app.Use`.

**Comment by davidfowl** [comment]
That can be fixed. Lets not gate APIs on intellisense features that we can influence 😄

**Comment by Tratcher** [comment]
Do we want an analyzer to recommend the right overload? We don't want to obsolete the old one, that's used everywhere.

**Comment by BrennanConroy** [comment]
Is there a `[Recommend("use other")]` sort of thing that will just give a message and green squiggly in VS?

**Comment by BrennanConroy** [comment]
We would like an analyzer to suggest the new method, but might just make an issue and backlog it as it isn't super high priority.

Add a `<para>` to the old methods doc comments to suggest using the new method.

**Comment by BrennanConroy** [comment]
Unfortunately, the current approach doesn't work because there is an ambiguous overload when short-circuiting:
```
app.Use((context, next) =>
{
    return Task.CompletedTask;
});
```

**Comment by pranavkm** [comment]
This seems like a poor use of `app.Use`. We should be recommending `app.Run` in this case. If we super cared about it, we can create an analyzer for this.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/31784
