### ISSUE TITLE
Changing assembly name breaks Blazor Server app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31479]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Changing-assembly-name-breaks-Blazor-Ser/1383436)._

---
[severity:I'm unable to use this version]
Changing the assembly name for a Blazor Server for .NET 5 project causes the sample pages to not render properly. This doesn't happen with Blazor Server for .NET 3.1 projects.

To replicate, just use the Visual Studio Blazor Server project creation template to create a project, with no authentication or with "Individual Authentication". Run the app to see that the sample pages work correctly. Then right-click on the project in Solution Explorer and open the Properties window. Change the "Application" > "Assembly name" by just adding a single character. Then try running the project again. The page doesn't render properly if your project target was set to .NET 5 when you created the project. The left nav doesn't appear on the page. However, if you set your target to .NET 3.1 when you create the project, then changing the assembly name doesn't cause a problem.

Changing the assembly name seems like too basic of a change to have a problem with it go unnoticed. Am I doing something wrong?

---
#### James Watkin on 3/27/2021, 09:38 AM: 

(private comment, text removed)
#### James Watkin on 3/27/2021, 07:24 PM: 

(private comment, text removed)
#### Feedback Bot on 3/28/2021, 11:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by danroth27** [comment]
The functionality of the app is still there when you change the assembly name, but the link to the component specific styles needs to be updated in *_Host.cshtml* to reflect the new assembly name.

I did find though that I had to do a full rebuild to get the component specific IDs to match up again though. @javiercn is this a bug?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
