### ISSUE TITLE
dotnet watch rebuilds the project on static file change

### ISSUE THREAD

**Issue by kanadaj** [dotnet/aspnetcore#31470]
It seems that https://github.com/dotnet/sdk/pull/15405 has added support to `dotnet watch` to watch static files. I believe the intent was to use browsersync to reload static files automatically, but it instead causes a rebuild to the whole app, even though that's likely not the intention.

**Comment by pranavkm** [comment]
Thanks @kanadaj for reporting this. We'll use the linked issue to track resolving this.
