### ISSUE TITLE
What is the lifetime of IServiceScopeFactory and IServiceProvider ?

### ISSUE THREAD

**Issue by EnricoMassone** [dotnet/aspnetcore#31478]
I'm looking for some informations related to the lifetime of `IServiceScopeFactory` and `IServiceProvider` when they are injected inside of a custom service, an MVC controller or an hosted service.

Based on my understanding, `IServiceScopeFactory` is automatically registered with the dependency injection system as a singleton service. Is my understanding correct ?

My doubt are related to the injection of `IServiceProvider`, because there is a root service provider and several children service providers (one per each scope defined when an HTTP request is handled by the ASP.NET core application). 

When I request an instance of `IServiceProvider` from the constructor of an MVC controller do I get the root container or a child container for the scope of the current HTTP request ? 

What about the injection of `IServiceProvider` in the constructor of an hosted service ? In that case the root container is inject, right ?

Thanks for helping.

Enrico.

**Comment by davidfowl** [comment]
IServiceScopeFactory is always a Singleton but the IServiceProvider can vary based on the lifetime of the containing class. So if you create a scope and resolve services from this scope, and any of those services take an IServiceProvider, it'll be the scoped one.

cc @IEvangelist some docs to add

**Comment by davidfowl** [comment]
To answer your concrete questions

> When I request an instance of IServiceProvider from the constructor of an MVC controller do I get the root container or a child container for the scope of the current HTTP request ?

The request scoped container.

> What about the injection of IServiceProvider in the constructor of an hosted service ? In that case the root container is inject, right ?


The root container.

**Comment by EnricoMassone** [comment]
@davidfowl thanks for the clarifications. So basically `IServiceScopeFactory` is always singleton and `IServiceProvider `depends on the context. 

One last questions. In order to use scoped services from an hosted service, a dependency injection scope needs to be created. The official docs suggests to inject `IServiceProvider` and create a scope from that. Some other sources suggest to inject `IServiceScopeFactory` and create a scope from that. Is there any difference ? Are the two methods to create a dependency injection scope equivalent ?

**Comment by davidfowl** [comment]
>  Is there any difference ? Are the two methods to create a dependency injection scope equivalent ?

Yea either works. There's even a CreateScope extension method on IServiceProvider that resolves the IServiceScopeFactory on your behalf. Injecting the scope factory once might be more efficient than using the extension method though.

**Comment by EnricoMassone** [comment]
> > Is there any difference ? Are the two methods to create a dependency injection scope equivalent ?
> 
> Yea either works. There's even a CreateScope extension method on IServiceProvider that resolves the IServiceScopeFactory on your behalf. Injecting the scope factory once might be more efficient than using the extension method though.

@davidfowl thanks for these clarifications.
