### ISSUE TITLE
The renderer needs to implement DisposeAsync

### ISSUE THREAD

**Issue by jaisondthomas** [dotnet/aspnetcore#31471]
The renderer needs to implement DisposeAsync
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/RenderTree/Renderer.cs#L759

_Originally posted by @javiercn in https://github.com/dotnet/aspnetcore/issues/26737#issuecomment-706187882_

I came across a similar issue. Not sure it is the same.

Steps to reproduce(The below code is from the demo page( Basic detailslist code and pivot large link example code))
Step 1 - press the "click me first " tab
Step 2 - then press the "click me second" tab
I have a Detailslist control inside the first tab

Error message - BlazorFluentUI.Lists.DetailsList`1.DisposeAsync()
I am using the new version( BlazorFluentUI V5.1.0.0 ) and doing Blazor server-side

<div>
    <Pivot AriaLabel="Large Link Size Pivot Example" LinkSize=PivotLinkSize.Large>
        <PivotItem HeaderText="My Files">
            <Label>Pivot #1</Label>
        </PivotItem>
        <PivotItem HeaderText="Recent">
            <Label>Pivot #2</Label>
        </PivotItem>
        <PivotItem HeaderText="Click me first">
            @*DetailsList demo page code*@
            <div data-is-scrollable="true" style="height:400px;overflow-y:auto;">
                <DetailsList ItemsSource="InputList"
                             Columns="Columns"
                             GetKey=@(item=>item.Key)
                             LayoutMode="DetailsListLayoutMode.Justified"
                             TItem="DataItem"
                             OnItemInvoked="OnClick"
                             Selection="selection"
                             SelectionMode="SelectionMode.Single">
                </DetailsList>
            </div>
        </PivotItem>

        <PivotItem HeaderText="Click me second">
            <Label>Pivot #3</Label>
        </PivotItem>
    </Pivot>
</div>

**Comment by pranavkm** [comment]
> The renderer needs to implement DisposeAsync

This was resolved as part of https://github.com/dotnet/aspnetcore/pull/26848. If you think there's an issue with the framework, please provide a minimal app that exhibits the issue.

**Comment by jaisondthomas** [comment]
Sorry, I think I put this in the wrong spot. 
It is resolved here - https://github.com/BlazorFluentUI/BlazorFluentUI/issues/285#issuecomment-812642751
