### ISSUE TITLE
IIS Deployment for Blazor WASM 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31480]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IIS-Deployment-for-Blazor-WASM/1383010)._

---
[severity:I'm unable to use this version]
Good day Team,

I'm currently deploying the My Blazor WASM application to IIS (windows 10), I have already published it and applied the necessary folder permission. However I can't make it work due to an error to web config. 

! [image.png] (https://aka.ms/dc/image?name=B6e8b591edd1949bd8b7878590d8fe8b7637523624311312386_20210326-213349-image.png&tid=6e8b591edd1949bd8b7878590d8fe8b7637523624311312386)

Here are the Prerequisite I have installed:

dotnet-hosting-5.0.4-win.exe - for iis deployment of .Net core projnect

Attached also is my test application
[Portal.zip] (https://aka.ms/dc/file?name=B71fc27d61fce426491790c581b137982637523625120643713_Portal.zip&tid=71fc27d61fce426491790c581b137982637523625120643713)

---
#### Feedback Bot on 3/28/2021, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what you're referring to as an issue with the framework. 
Unfortunately we don't have enough resources to try to help every customer. Hence we focus only on the issues which have very high chance being bugs with the framework. For these type of issues we recommend posting questions to [StackOverflow](https://stackoverflow.com).
