### ISSUE TITLE
Helix add built AspnetCore.App as a correlation payload

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#31494]
With the shift to moving to correlation payloads for sdk/runtime bites, we no longer are able to update our built aspnet runtime bits (for project templates tests) the same way.

This is only an issue on docker queues which are read only correlation payloads.  Currently no tests seem to be affected by this difference, but its possible if template tests are every updated to rely on new functionality this will become a temporary issue.

**Comment by dougbu** [comment]
Hmm, won't the full matrix tests fail with things as #31448 will leave them❔

**Comment by HaoK** [comment]
No they are passing as is, they were only failing due to the ref pack trying to be copied there, I changed the destination to the work item so they are green

**Comment by HaoK** [comment]
The only thing that was failing was the 3 docker queues

**Comment by HaoK** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=1070132&view=results
