### ISSUE TITLE
Missing `class` colorization in `@code` block

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#31496]
![image](https://user-images.githubusercontent.com/14852843/113464970-87331d80-93e5-11eb-8e9f-bafb241bbb2a.png)

**Comment by NTaylorMullen** [comment]
@gundermanc I assume this is most likely the semantic colorization issue you fixed? It was spotted on Friday

**Comment by gundermanc** [comment]
This one? https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/313631

Simplest way to check is to attach or look at telemetry monitor and look for 'BadEditException' being raised on every keystroke.

With the synchronization refactor, that should never happen locally.

**Comment by NTaylorMullen** [comment]
@TanayParikh could you confirm?

**Comment by TanayParikh** [comment]
I don't have the prior version of VS installed any longer, but can confirm this issue no longer repros in current VS Main:
![image](https://user-images.githubusercontent.com/14852843/113641113-c9e93580-9631-11eb-9774-5dd38e65e82f.png)
