### ISSUE TITLE
ChunkingCookieManager could be optimized for perf and fewer allocations

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31508]
* DeleteCookie calls AppendCookie which is designed for larger chunked cookies. However, when deleting each of the values is an empty string. It could do something much more targeted.
* `DeleteCookie` also could the delegate allocation using `Enumerable.Where` and use a bespoke iterator similar to `ResponseCookies.Delete`:
     * https://github.com/dotnet/aspnetcore/blob/main/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L282
     * https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Internal/ResponseCookies.cs#L128-L142
* `AppendResponseCookie` invokes `ResponseCookies.Append` which allocates a `ResponseCookieValues` instance and an intermediary `StringValues` for the header. Since we know we're running inside a loop, it could be better optimized for fewer allocations

**Comment by JuanShares** [comment]
Sounds interesting, I would like to take this one, some questions:

- Any common place where I can put some perf tests to see if my refactors do have real gains?
- I am thinking a few strategies to follow in this refactor, but I do not loose nothing asking, do you have any docs when it comes to refactor something with perf as a goal?

**Comment by JuanShares** [comment]
@davidfowl @pranavkm I have send a new PR adding some performance refactoring's that follows the guidance of the original comment, there are pretty cool wins with it although it adds a new public api which will need to be reviewed.


### Proposal

```csharp
void Append(IDictionary<string, string> keyValuePairs, CookieOptions options);
```

As seen on `ChunkingCookieManager` the need to add several cookies at once using the same CookieOptions seems to be common, the new overload will cover this need by receiving a `IDictionary<string, string>`  whose values will be added to the `Set-Cookier` response header in an efficient manner:

- Allowing us to instante only one CookieOptions per all cookies added
- Allowing us to instante only one SetCookieHeaderValue and be reused for all Cookies to be added 
- Prevent multiple StringValues.Concat

**Comment by Tratcher** [comment]
Notes for the API review:
Could this IEnumerable or ICollection instead of IDictionary? I think the implementations would be more efficient with a List than a Dictionary. Random access isn't needed.
`void Append(ICollection<KeyValuePair<<string, string>> keyValuePairs, CookieOptions options);`

**Comment by davidfowl** [comment]
I think we should add overloads as appropriate to avoid transforming source data. If the caller has a dictionary then we need to make that work as is.

**Comment by JuanShares** [comment]
I have tested it with `IEnumerable<KeyValuePair<<string, string>>` and it actually improved the performance numbers and saved us 1k of allocation on DeleteCookies, I liked the idea as users can still pass `IDictionary<string,string>` without problems.

**Comment by davidfowl** [comment]
Excellent work @barahonajm! I hope to see more contributions like this from you

**Comment by barahonajm** [comment]
Thanks for all your help team, I have learned a lot!

@davidfowl definitely! more contributions coming 😃
