### ISSUE TITLE
.NET 6 - ApplicationState - Steps are executed twice

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#31509]
Hello,

I took a look at the [.NET 6 Preview 2](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/) post.
I tried the '_Preserve prerendered state_' function with the proposed code.
When run on the '_/fetchdata_' page, the steps are executed once.
But if I place the same code on the main '_/_' page, it is called twice.

```C#
protected override async Task OnInitializedAsync()
{
    ApplicationState.OnPersisting += PersistForecasts;
    if (!ApplicationState.TryRedeemPersistedState("fetchdata", out var data))
    {
        Console.WriteLine("Load");
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
    else
    {
        Console.WriteLine("Retrieve");
        var options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true,
        };
        forecasts = JsonSerializer.Deserialize<WeatherForecast[]>(data, options);
    }
}

private Task PersistForecasts()
{
    Console.WriteLine("Persist");
    ApplicationState.PersistAsJson("fetchdata", forecasts);
    return Task.CompletedTask;
}
```

The output is the following:

```
Load
Persist
Retrieve
Load
Persist
Retrieve
```
I didn't expect to have a call twice for the different steps. Could we avoid this and get the same behaviour as the '_/fetchdata_' page ? 
Or maybe I didn't understand correctly the concept explained on the Microsoft Blog ?
Thanks for any answer/clarification @danroth27 😄 

_Visual Studio Version 16.10.0 Preview 1.0
dotnet-sdk-6.0.100-preview.2.21155.3-win-x64_

**Comment by javiercn** [comment]
@boukenka thanks for contacting us.

That sounds strange, could you provide a minimal repro project (gh repo) to ensure we are not missing anything in your description?

We have automation covering this scenario and whether you put something on the main page or a different page should not matter at all.

**Comment by boukenka** [comment]
@javiercn Thanks for the feedback. 😄 
Please find attached the project.
For information, I am using EDGE DEV Version 91.0.838.3 (Official build) dev (64-bit)
I think this is related to the browser version. 
I did some additional tests.
It was Ok with the most recent version of Vivaldi, Firefox and Google Chrome.

![Problem](https://user-images.githubusercontent.com/16502423/113614599-00837800-9653-11eb-8975-aa7fbf1991fa.png)
[BlazorApp.zip](https://github.com/dotnet/aspnetcore/files/6260150/BlazorApp.zip)

**Comment by boukenka** [comment]
@javiercn Good evening,

I have tried with _.NET 6 Preview 3_ and _Visual Studio Version_ _16.10.0 Preview 2.1_ on the latest _DEV EDGE 91.0.864.1_.
I have modified the code using the new methods :

```C#
protected override async Task OnInitializedAsync()
{
    ApplicationState.OnPersisting += PersistForecasts;
    if (!ApplicationState.TryTakeAsJson<WeatherForecast[]>("fetchdata", out var data))
    {
        Console.WriteLine("Load");
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
    else
    {
        Console.WriteLine("Retrieve");
        forecasts = data;
    }
}

private Task PersistForecasts()
{
    Console.WriteLine("Persist");
    ApplicationState.PersistAsJson("fetchdata", forecasts);
    return Task.CompletedTask;
}
```

The problem I have encountered was no longer present. I have closed the issue.
