### ISSUE TITLE
RSG fails to resolve EditorConfigFile task in VS

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#31514]
The new `EditorConfigFile` task we are using to inject the `RazorSourceGenerator.razorencconfig` file is not being resolved correctly.

![image](https://user-images.githubusercontent.com/1857993/113490691-92875700-9480-11eb-93c7-284c090c5ef6.png)

**Comment by pranavkm** [comment]
Fixed by https://github.com/dotnet/sdk/pull/16726
