### ISSUE TITLE
Support validation of multiple hosted domains

### ISSUE THREAD

**Issue by vyarymovych** [dotnet/aspnetcore#31529]
### Is your feature request related to a problem? Please describe.
I am trying to build a google add-on which will be used by specific google workspace domains. I'm not guru in this area, but I'm thinking how to secure backend API which will be accepting google id token.
The point is we would like to publish google add-on globally, but only specific domains can call those APIs. 
Is it the case that I would need to validate **hd** claim against a list of allowed domains? Currently only one allowed value is supported.

### Describe the solution you'd like
I would like **UseGoogle** method to accept a list of allowed hosted domains.

**Comment by blowdart** [comment]
The backend apis, what authentication are they using? UseGoogle is for interactive logins, and it seems unlikely that's the type of token you're going to get. Would it not be a JWT? is there any public documentation on what type of add-in you're writing and how security works for that model?
