### ISSUE TITLE
Trim insignificant spaces from text attributes

### ISSUE THREAD

**Issue by titan83** [dotnet/aspnetcore#31520]
Net5.0 supports the trimming of insignificant space into components by default (https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/blazor-components-trim-insignificant-whitespace).
This is a very useful feature.
But we can do a one step more in this direction.
And apply a normalization to attribute's values. It's described here: https://www.w3.org/TR/xhtml1/diffs.html#h-4.7
Small example:
```html
<td style="min-width: @(SomeProp == "1" ? "100px;" : "")
                                     @(SomeProp == "2" ? "200px;" : "")">tdValue</td>
```
If the first condition is true (SomeProp == "1") then Blazor produces next html:
```html
<td style="min-width: 100px;                                      ">tdValue</td>
```
As you seen 'style' attribute contains all spaces from source code.
But in sources we use these spaces for a indent and we would not want to see these spaces into result html.

I assume these behavior can be controlled by some additional property like "@preserveattributeswhitespace".

Thanks.

**Comment by javiercn** [comment]
@titan83 thanks for contacting us.

The main goal of trimming insignificant spaces in Blazor is for performance reasons. Insignificant space in elements is far more common than in attributes, while we could do work to implement something like this, I don't think in general it will pay off.

**Comment by danroth27** [comment]
Thanks for contacting us. This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md) writeup.
