### ISSUE TITLE
dotnet-watch install size increased by 477%

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#31527]
### Describe the bug

Sometime between versions 6.0.100-preview.3.21168.1 and 6.0.100-preview.3.21201.6, the dotnet-watch install size increased from 6,183 KB to 35,725 KB.  Is this size increase intentional?  Increasing the size on disk for the SDK should be limited whenever possible, particularly for container scenarios.

### To Reproduce

1. Download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.3.21168.1/dotnet-sdk-6.0.100-preview.3.21168.1-win-x64.zip
2. Download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.3.21201.6/dotnet-sdk-6.0.100-preview.3.21201.6-win-x64.zip
3. Compare the contents of the `sdk\<version>\DotnetTools\dotnet-watch\<version>\tools\net6.0\any` folders.

**Comment by pranavkm** [comment]
The size increase is somewhat intentional since dotnet-watch now ships additional compiler binaries to support hot reload. We're using https://github.com/dotnet/aspnetcore/issues/31212 to track reducing the size impact, but some increase is to be expected.
