### ISSUE TITLE
Duplicated event names in KestrelTrace logger

### ISSUE THREAD

**Issue by fvoronin** [dotnet/aspnetcore#31523]
In KestrelTrace logger declared two events with same name `"RequestBodyDrainTimedOut"`

https://github.com/dotnet/aspnetcore/blob/4f3e8e0efffc1a6fed471d1376db5afcefed21a6/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs#L85-L89

**Comment by BrennanConroy** [comment]
@fvoronin are you interested in fixing this?
