### ISSUE TITLE
Blazor: One-time binding mode is needed

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnetcore#31534]
### Is your feature request related to a problem? Please describe.
If we set a constant value for a component parameter property, and let the property change inside the component, this property will be set to the constant value again when the parent component which host the component rerenders if: 
1. the component has other reference type(not include string) parameter properties set(these paramters may not change)
or
2. any of the component paramter properties changed

Otherwise, the property will not be set to the constant value again.

This behavior causes:
1. inconsistent behavior between components
2. it's hard to set initial value for parameters and let them change inside the component and not be set by the parent component again. That is, the initial value should just be used once.

### Describe the solution you'd like
Add support for one-time binding mode

### Additional context
Sample code for better understand:
We use ant design blazor component library for this sample.
```C#
<input value="@("Orgin")" />

<AntDesign.Input Value="@("Orgin")" />

<input value="@("Orgin")" disabled="@_disabled" />

<AntDesign.Input Value="@("Orgin")" Disabled="_disabled" />

<AntDesign.Input Value="@("Orgin")">123</AntDesign.Input>

<AntDesign.Button OnClick="()=>{ _disabled = !_disabled; }">Click</AntDesign.Button>

@code {
    bool _disabled = false;
}
```

**Comment by javiercn** [comment]
@anranruye thanks for contacting us.

It's not clear what you are asking/implying with your sample. Could you post the full details?

**Comment by anranruye** [comment]
@javiercn 
Ok.
Route attribute added:
```C#
@page "/sample" 

<input value="@("Orgin")" />

<input value="@("Orgin")" disabled="@_disabled" />

<AntDesign.Input Value="@("Orgin")" />

<AntDesign.Input Value="@("Orgin")" Disabled="_disabled" />

<AntDesign.Input Value="@("Orgin")">ChildContentWasSet</AntDesign.Input>

<AntDesign.Button OnClick="()=>{ _disabled = !_disabled; }">Click</AntDesign.Button>

@code {
    bool _disabled = false;
}
```

Follow these steps:
1. Run the app(either blazor server app or blazor wasm app)
2. Navigate to "/sample"
3. Change input values by keyboard input
4. Click the button

Then you can see the difference: values for the first three inputs are not changed but the last two inputs are set to "Orgin" again.

ScreenShots:
![image](https://user-images.githubusercontent.com/54608128/113650008-1419f780-96c2-11eb-92c1-9975c0982567.png)
![image](https://user-images.githubusercontent.com/54608128/113650054-2b58e500-96c2-11eb-8761-85baf2105df7.png)
![image](https://user-images.githubusercontent.com/54608128/113650053-2b58e500-96c2-11eb-8bb7-3f73d6a0d93e.png)

**Comment by pranavkm** [comment]
@anranruye could you take this up with the AntDesign component project? This isn't an issue specific to Blazor, more about AntDesign's usage and their behavior.

**Comment by anranruye** [comment]
@pranavkm 
I don't think so. I can reproduce similar behavior by a custom component without AntDesign. The reason to use AntDesign in my sample code is just to make the code concise and clear.

Also, I have communicated with the author of AntDesign. He told me that this is a common issue among various component libraries, not only for AntDesign. We both agree that this is an issue of Blazor itself.

You can say that we are using blazor in a wrong way. But the point is, how to use it to achieve our goal? Both library developers and common users of blazor are confusing about this issue. As I said, we need more suggestions. Or you should explicitly tell us this is not a supported feature.

With all due respect, I don't think you have read my issue carefully. Otherwise, you may not make comments that contradict the facts. I will not be satisfied until I get a proper answer.
