### ISSUE TITLE
[Discussions] Obsoleting AddDataAnnotationsValidation and replacing with EnableDataAnnotationsValidation

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#31536]
The extension method `EditContextDataAnnotationsExtensions.AddDataAnnotationsValidation` is being marked as obsolete. Developers should use the new extension method `EditContextDataAnnotationsExtensions.EnableDataAnnotationsValidation` instead.

The only difference between these two APIs is in their return values:

```cs
EditContext AddDataAnnotationsValidation(this EditContext editContext) { ... }

IDisposable EnableDataAnnotationsValidation(this EditContext editContext) { ... }
```

**Comment by mrpmorris** [comment]
What will happen when Dispose is called on the result?

**Comment by SteveSandersonMS** [comment]
Disposal removes the data annotations validator from the EditContext.

**Comment by mrpmorris** [comment]
What is the use case for wanting to do that?

**Comment by SteveSandersonMS** [comment]
https://github.com/dotnet/aspnetcore/issues/31027
