### ISSUE TITLE
Error while compiling HubConnectionSample (VS 2019) - ASP.NET Core SignalR C++ Client

### ISSUE THREAD

**Issue by SanjDesa** [dotnet/aspnetcore#31548]
### Describe the bug
I have downloaded ASP.NET Core SignalR C++ Client (1.0-alpha2-9073dc8645) using vcpkg and built it. I trying to compile the sample example HubConnectionSample.cpp in VS 2019 but getting following errors and warnings

Severity Code Description Project File Line Suppression State Error (active) E0312 no suitable user-defined conversion from "std::shared_ptr" to "std::shared_ptrsignalr::log_writer" exists SignalRApp ...\SignalRApp\SignalRApp\SignalRApp.cpp 54
Severity Code Description Project File Line Suppression State Error C2011 'signalr::log_writer': 'class' type redefinition SignalRApp ..\SignalRApp\packages\Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta2\build\native\include\signalrclient\log_writer.h 11
### To Reproduce

```
#include <iostream>
#include <sstream>
#include <signalrclient\hub_connection_builder.h>
#include <signalrclient\log_writer.h>
#include <future>
#include <signalrclient\signalr_value.h>

class logger : public signalr::log_writer
{
    // Inherited via log_writer
    virtual void __cdecl write(const std::string& entry) override
    {
        std::cout << entry;
    }
};

void send_message(signalr::hub_connection& connection, const std::string& message)
{
    std::vector<signalr::value> arr{ std::string("c++"), message };
    signalr::value args(arr);

    // if you get an internal compiler error uncomment the lambda below or install VS Update 4
    connection.invoke("Send", args, [](const signalr::value& value, std::exception_ptr exception)
        {
            try
            {
                if (exception)
                {
                    std::rethrow_exception(exception);
                }

                if (value.is_string())
                {
                    std::cout << "Received: " << value.as_string() << std::endl;
                }
                else
                {
                    std::cout << "hub method invocation has completed" << std::endl;
                }
            }
            catch (const std::exception& e)
            {
                std::cout << "Error while sending data: " << e.what() << std::endl;
            }
        });
}

void chat()
{
    signalr::hub_connection connection = signalr::hub_connection_builder::create("http://localhost:5000/default")
        .with_logging(std::make_shared <logger>(), signalr::trace_level::verbose)
        .build();

    connection.on("Send", [](const signalr::value& m)
        {
            std::cout << std::endl << m.as_array()[0].as_string() << std::endl << "Enter your message: ";
        });

    std::promise<void> task;
    connection.start([&connection, &task](std::exception_ptr exception)
        {
            if (exception)
            {
                try
                {
                    std::rethrow_exception(exception);
                }
                catch (const std::exception& ex)
                {
                    std::cout << "exception when starting connection: " << ex.what() << std::endl;
                }
                task.set_value();
                return;
            }

            std::cout << "Enter your message:";
            while (connection.get_connection_state() == signalr::connection_state::connected)
            {
                std::string message;
                std::getline(std::cin, message);

                if (message == ":q" || connection.get_connection_state() != signalr::connection_state::connected)
                {
                    break;
                }

                send_message(connection, message);
            }

            connection.stop([&task](std::exception_ptr exception)
                {
                    try
                    {
                        if (exception)
                        {
                            std::rethrow_exception(exception);
                        }

                        std::cout << "connection stopped successfully" << std::endl;
                    }
                    catch (const std::exception& e)
                    {
                        std::cout << "exception when stopping connection: " << e.what() << std::endl;
                    }

                    task.set_value();
                });
        });

    task.get_future().get();
}

int main()
{
    chat();

    return 0;
}
```

### Further technical details

- Include the output of `dotnet --info`
- 
- .NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

-ASP.NET Core SignalR C++ Client (1.0-alpha2-9073dc8645),  Visual Studio 2019, Version 16.9.2

**Comment by BrennanConroy** [comment]
>type redefinition SignalRApp ..\SignalRApp\packages\Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta2\build\native\include\signalrclient\log_writer.h 11

Are you referencing two different SignalR C++ clients? Looks like you're referencing the new C++ client and the old one, which both have a log_writer class. Remove your reference to the old client.

**Comment by SanjDesa** [comment]
Thank you!!
