### ISSUE TITLE
Improve Razor Formatting Perf

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#31542]
Due to the prevalence of formatting across the Razor editor experience, investing in improving it's perf may be very effective in helping improve overall performance.

💡 [Formatting](https://github.com/dotnet/aspnetcore-tooling/blob/436191f0c5aeb836e87547aa8b5bf73909687254/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs#L126-L133) absolutely dominates the perf of Code Action Resolve. Looking at the CPU Usage details below we see formatting is responsible for 7.39% of compute time within the sequence under examination. In contrast to the request we dispatch to Roslyn to compute the resolved code action which only takes about 1-2%. I believe this is a result of us doing full document formatting everytime, which would be especially costly in large documents. **Range formatting** comes to mind as the most direct solution, however I don't believe we have that directly implemented yet.

![image](https://user-images.githubusercontent.com/14852843/113617852-b7f49c00-960b-11eb-95c5-32473a31ef3c.png)

**Comment by davidwengier** [comment]
I was hoping there would be some low-hanging fruit around FormattingContext, but nothing obvious jumped out at me. Looks like the biggest wins are in Roslyn, though range formatting like Tanay says could change that.
![image](https://user-images.githubusercontent.com/754264/118119478-c4052200-b431-11eb-9e92-122a447159d1.png)

**Comment by allisonchou** [comment]
Closing via https://github.com/dotnet/aspnetcore-tooling/pull/4242.
