### ISSUE TITLE
Investigate Components.E2ETest hang after selenium update

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#31545]
When I updated Selenium in https://github.com/dotnet/aspnetcore/pull/31497/commits/7795dc9376e0811b3a847aa0928ad176970d7691, the Components.E2ETEsts started to hang: https://dev.azure.com/dnceng/public/_build/results?buildId=1072106&view=logs&jobId=c18bc5be-c9c3-5147-7bbf-cfe43d8b0016&j=c18bc5be-c9c3-5147-7bbf-cfe43d8b0016&t=005b7324-c327-56d8-0a3d-2ba9507954e0
https://dev.azure.com/dnceng/public/_build/results?buildId=1072107&view=ms.vss-test-web.build-test-results-tab&runId=32934718&resultId=100352&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Someone familiar with the tests should investigate. This might be mitigated if migration to Playwright completes soon. FYI @pranavkm

**Comment by BrennanConroy** [comment]
```
System.InvalidOperationException : Couldn't create a Selenium remote driver client. The server is irresponsive
      ---- System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 90
```

**Comment by pranavkm** [comment]
We need to wait for Chrome 90 to be released. This just needs patience.

**Comment by BrennanConroy** [comment]
Should some text be including in the "blops" docs so people don't hit this unexpectedly every time chrome updates?

**Comment by JunTaoLuo** [comment]
Ah so that's what it is. This process is really unfortunate since the version updates must be matched with chrome update on the agents. You can't preempt this at all and we'll always have a few days of downtime when chrome updates.

**Comment by mkArtakMSFT** [comment]
Closing as this was a point-in-time issue. We should try to document / give a heads-up about similar changes going forward, as @BrennanConroy suggested above.
