### ISSUE TITLE
'Razor component' versus 'Blazor component' in project templates

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#31559]
### Is your feature request related to a problem? Please describe.

Feature description question

### Describe the solution you'd like

The RCL project template and the WebView sample component have a components with the following markup:

```razor
<div class="my-component">
    This Blazor component is defined in the <strong>WebviewAppShared</strong> package.
</div>
```

```razor
<div class="my-component">
    This Blazor component is defined in the <strong>Company.RazorClassLibrary1</strong> library.
</div>
```

We don't currently use the naming 'Blazor component' in docs. We use 'Razor component' everywhere. I wonder if these framework components should use 'Razor component'? If not, what doc contexts should use 'Blazor component'?

### Additional context

* https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/Samples/WebviewAppShared/SharedComponent.razor
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/RazorClassLibrary-CSharp/Component1.razor

Also note that a few other spots use 'Blazor component' lingo. For example, I saw 'Blazor component model' go by in search results.

**Comment by javiercn** [comment]
@guardrex thanks for bringing this up.

These should be renamed to `razor component`

**Comment by pranavkm** [comment]
Could we rename this to "This component" (so we don't use either Blazor or Razor) here?

**Comment by adrianwright109** [comment]
I would like to take this on and create a PR - is that OK ?
