### ISSUE TITLE
[release3.1] Package Microsoft.AspNetCore.Identity.EntityFrameworkCore should support netstandard2.0

### ISSUE THREAD

**Issue by jonnybee** [dotnet/aspnetcore#31555]
Package Microsoft.AspNetCore.Identity.EntityFrameworkCore v3.1 now only supports netcoreapp3.1 and nestandard2.1. 

EntityFrameworkCore 3.1 brings back support for netstandard2.0 and so should this package.

**Comment by blowdart** [comment]
Given that Identity is aimed at use within asp.net, flows with asp.net and asp.net is now over and above netstandard2.1, why would we want to target anything lower than whatever the version of asp.net targets at the time of release?

**Comment by jonnybee** [comment]
I was referring to the recently updated package version 3.1.13, of March 9th, 2021. 

This  Microsoft.AspNetCore.Identity.EntityFrameworkCore package references 

- Microsoft.EntityFrameworkCore.Relational v 3.1.13 that contains assemblies for netstandard2.0 only
- Microsoft.Extensions.Identity.Stores v3.1.13 that contains assemblies for netstandard2.0 and netcoreapp3.1

So why is Microsoft.AspNetCore.Identity.EntityFrameworkCore v.3.1.13 targeting netstandard2.1 and netcoreapp3.1? 

We have a several "legacy" applications on netcoreapp2.1 and I was looking into upgrading the packages and EF Core to v3.1 but this package is (so far) the only one that does not target netstandard2.0.

**Comment by pranavkm** [comment]
We generally don't add new features to older versions of packages. In addition, mixing runtime and package versions across major releases (3.1 and netcoreapp2.1) in your case is not a scenario we support. We really wouldn't recommend doing this.
