### ISSUE TITLE
Shadow copy on Azure App Services doesn't work with relative 

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31570]
Calling canonical on the shadowCopyBaseDirectory [here](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp#L307) doesn't work on Azure App Services, and returns a path that looks like a volume mount:
```
[aspnetcorev2.dll] shadowCopyPath D:\home\site\wwwroot\ShadowCopyDirectory\
[aspnetcorev2.dll] shadowCopyBaseDirectory D:\home\site\wwwroot\ShadowCopyDirectory\
[aspnetcorev2.dll] Canonical \\<IP>\volume-1-default\fe4f951b8d68fa3b8283\2db0a0180dd144328b9ee1bc49d73b1f\site\wwwroot\ShadowCopyDirectory
```

This canonical value is used to verify we don't recursively copy the folder content of the shadow copy app, so this breaks relative paths inside of the app directory.

**Comment by BrennanConroy** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/31864
