### ISSUE TITLE
No hot reload error UI on compilation failure with Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31584]
Repro steps:

- Create a new Blazor WebAssembly app
- Update launchSettings.json to enable hot reload: `"hotReloadProfile": "blazorwasm"`
- `dotnet watch`
- Remove a semi-colon to cause a compilation failure

Expected: Error UI shows up with details about the compilation failure
Actual: Compilation failure printed to the console, but no error UI.

.NET SDK: 6.0.100-preview.3.21202.5

**Comment by pranavkm** [comment]
This was resolved as part of https://github.com/dotnet/sdk/pull/16701. You get the compilaton error window and the ability to continue from the error once the error is resolved.
