### ISSUE TITLE
Removal of component attribute isn't honored after hot reload

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31582]
Repro steps:

- Create a new Blazor WebAssembly app
- Update launchSettings.json to enable hot reload: `"hotReloadProfile": "blazorwasm"`
- `dotnet watch`
- Update the Counter component to add an `IncrementAmount` parameter
- Add a `Counter` to the home page: `<Counter IncrementAmount="10" />`
- Remove the `IncrementAmount` attribute
- Try the counter

Expected: Counter increments by 1
Actual: Hot reload succeeded, but the Counter still increments by 10.

.NET SDK: 6.0.100-preview.3.21202.5

**Comment by pranavkm** [comment]
Likely a dupe of https://github.com/dotnet/aspnetcore/issues/31272.
