### ISSUE TITLE
Add an option to dev-certs to add certs to the machine store on Windows

### ISSUE THREAD

**Issue by ben-zen** [dotnet/aspnetcore#31595]
### Motivating issue

While trying out http.sys using the [sample app](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp) I ran into an issue testing it with TLS; the server would simply reset the connection and no attempts would succeed. When I tried following [the directions to set up http.sys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-windows-server),  I found that the certificate I had installed with `dotnet dev-certs https --trust` was ignored by `netsh http add sslcert ...` -- because it's in the current user's personal store, not the local machine. I had to go and find the cert in its then-current store, and copy it manually into the local machine store.

### Describe the solution you'd like
I'd appreciate a `--machine` option on `dotnet dev-certs https` to go along with `--trust` and `--clean`, that would simplify testing with `http.sys` by elevating and adding the cert to the Local Machine\Personal store, instead of just always adding the certificate to the Current User\Personal store. This would probably also involve clearly stating where the certificate actually has been placed, because currently that is left completely unstated.

**Comment by javiercn** [comment]
@ben-zen thanks for contacting us.

The dev cert we generate is for use with Kestrel only. We don't plan to expand the scope of the tool to cover other hosts like IIS Express or http.sys. It should be trivial to install the certificate into the machine store with a powershell command if you need to.

**Comment by ben-zen** [comment]
@javiercn that makes a lot more sense. Once I understood where it was located, it wasn't that difficult to get it into the correct store, but it definitely took some digging.
