### ISSUE TITLE
Can no longer run standalone Blazor WebAssembly apps from source in this repo

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#31611]
Repro:

* `cd src\Components\WebAssembly\testassets\StandaloneApp`
* `dotnet run`

Expected: App runs, as it used to
Actual:

```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\path\artifacts\bin\Microsoft.AspNetCore.Components.WebAssembly.DevServer\Debug\net6.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\path\artifacts\bin\Microsoft.AspNetCore.Components.WebAssembly.DevServer\Debug\net6.0\blazor-devserver.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\path\artifacts\bin\Microsoft.AspNetCore.Components.WebAssembly.DevServer\Debug\net6.0\blazor-devserver.runtimeconfig.json' file and specify the appropriate framework.
```

In combination with #31023 which TBH is much more impactful, I'm finding the productivity of working within our repo to be a real challenge at the moment. Am I the only one? If anyone has capacity to look into this before the end of preview 4 that would be great, or if not I think we need to reserve some time at the start of preview 5 to prioritise this ahead of feature/bug work.

**Comment by pranavkm** [comment]
@captainsafia if you're able to look at this as part of build ops, that would be great.

**Comment by captainsafia** [comment]
Should be fixed on the latest main.
