### ISSUE TITLE
WASM application Memory leak(Memory foot print) in Browser 

### ISSUE THREAD

**Issue by Venkat4655** [dotnet/aspnetcore#31615]
### Describe the bug
Brower memory footprint size was increasing while navigation between the razor pages. Due to this Memory leak was occurred in WASM application. 

### To Reproduce
We had created the WASM app for the Default HTML table by using that Razor component. Here, we have defined the BLAZOR components for the table, Row, Cell, Header, and Content. 

you can find the simple project in the following GitHub link,[WASMMemory](https://github.com/Venkat4655/WASMMemoryIssue)
 
Replication procedure
1) Run the sample
2) Open the Task Manager of Chrome (short cut key Shift+ESC )
3) Navigate the razor pages between HTML Grid, HTML GRID1 and HTML Grid2 multiple times
4) Now you can see the Memory footprint increases
 
[WASM Memory leak Video](https://drive.google.com/file/d/1cZ4sUfrgvXmrJMDavnLNItyrT9PT-f_D/view)

### Exceptions (if any)
No Exceptions

### Further technical details
- ASP .NET core version 5.1
-.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]

- VS2019

**Comment by pranavkm** [comment]
Thanks for your issue report. Do you have a more minimal app that demonstrates that there's an issue with the framework? There's quite a bit going on in the sample that you've attached.

**Comment by Venkat4655** [comment]
Hi Pranav,

Thanks for looking into this issue

As per your request, we have modified the samples and removed some unnecessary components as well as commented code blocks. 
Updated Sample: [Sample](https://github.com/Venkat4655/WASMMemoryIssue)
Sample App Explanation:
This WASM app contains a Components folder that has multiple components. Actually, we have been facing the issue while using multiple components. 
For example,
```
<div>
<table>
<tr>
<td>
</td>
</tr>
</table>
</div>
```

above code represents the structure we want to display the table and we have rendered the above HTML table using multiple components like as follows,

```

<HTMLGridComponent>
<HTMLHeader></HTMLHeader>
<ValueComponent>
<HTMLRow>
<HTMLCell>
</HTMLCell>
</HTMLRow>
</ValueComponent>
</HTMLGridComponent>
```

In this scenario, we have faced the reported issue. Here system/JSArrayBufferData size was maintained if we moved to the home page(which doesn't contain the HTML table). We have shown this issue in this [Video](https://drive.google.com/file/d/1cZ4sUfrgvXmrJMDavnLNItyrT9PT-f_D/view). Could you please explain why it was maintained and we suspect that this was the root cause of that Memory footprint increasing while navigating between the razor pages?

Also, I can understand that when having many components, WASM memory has to be increased but when I leave the Table page, I expect the WASM memory should be released or reduced but I can see that assigned WASM memory(buffer size) is maintained.

**Comment by Madhust** [comment]
@mkArtakMSFT @pranavkm I could see that WASM memory buffer size which is increased when I navigate to a page with a large number of components is not released after navigating to another page. 

I found this [comment](https://github.com/dotnet/aspnetcore/issues/30210#issuecomment-779849309) where @javiercn gave a clear explanation about how memory is released when Blazor server circuits are closed. Does Blazor WASM flavor have a similar thing?

**Comment by TanayParikh** [comment]
Thanks for contacting us. This doesn't seem to be an issue with the framework as there aren't any strong guarantees on when exactly memory is reclaimed after navigating away from a page. 

I'd recommend reviewing [component disposal in the component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-disposal-with-idisposable) for more information on when memory is expected to be reclaimed.

Note specifically:
> Disposal can occur at any time, including during component initialization.
