### ISSUE TITLE
Autocompletion deletes code

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#31616]
Please see attached video. There is no better way of reporting :) 

https://user-images.githubusercontent.com/40038634/114042237-e344e880-98a2-11eb-936f-e39a83358691.mp4

### Further technical details
- ASP.NET Core version 5.x
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version : VS Community Edition 19.6.3

**Comment by NTaylorMullen** [comment]
@mayur-ekbote do you happen to have this flag checked? Or not?

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

**Comment by mayur-ekbote** [comment]
I don't use the experimental editor. Quite a few reasons, but the biggest is that there is no support for CSS IntelliSense. It makes developing Blazor UI very difficult. Another is that it is slow and crashes most of the time. 
This bug appears randomly so I don't know how to reproduce it. 
I will wait till the editor is production-ready.

**Comment by allisonchou** [comment]
Hi @mayur-ekbote, would you mind filing additional issues for the problems you're seeing?
It seems like the original problem in this issue has been solved in the new editor, so for tracking purposes I'm going to close it out. But we'd love to gather more feedback on how to make the new editor better. Thank you!
