### ISSUE TITLE
AddControllersWithViews with a global ActionFilter prevents setting CurrentCulture in Controller action method

### ISSUE THREAD

**Issue by msneijders** [dotnet/aspnetcore#31617]
### Describe the bug
After adding a global ActionFilter (even a dummy one, not doing anything) using services.AddControllersWithViews, setting `CurrentThread.CurrentCulture` in the Controller action method does not work anymore.
[CurrentCulture.zip](https://github.com/dotnet/aspnetcore/files/6279477/CurrentCulture.zip)

This kind of pattern of setting the CurrentCulture in the action method and rendering the view using this culture comes from an asp.net net471 solution that I am migrating to asp.net core -- this is my last hurdle.

### To Reproduce

See attached solution.

In short:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews((options) => {
        options.Filters.Add<DummyFilter>(); // comment this, and setting current culture in Controller action works
    });
}

class DummyFilter : ActionFilterAttribute
{
    
}

public class HomeController : Controller
{
    public IActionResult Privacy()
    {
        System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("nl-nl");
        System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("nl-nl");
        return View(new PrivacyVM());
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}
```

Razor view:

```cshtml
<p>@System.Threading.Thread.CurrentThread.ManagedThreadId has culture @System.Threading.Thread.CurrentThread.CurrentCulture.Name</p>
<p>@System.Threading.Thread.CurrentThread.ManagedThreadId has uiculture @System.Threading.Thread.CurrentThread.CurrentUICulture.Name</p>
<p>@System.Threading.Thread.CurrentThread.ManagedThreadId has uiculture @System.Globalization.CultureInfo.CurrentCulture.Name</p>
```

The action method and razor view are executed by the same thread (same ManagedThreadId) -- but with the global actionfilter the culture in the view is always my systems default, and not the "nl-nl" -- without the global action filter the culture in the view is "nl-nl".

### Exceptions (if any)
No exceptions, the CurrentCulture in the View is not what I set it to be.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.200-preview.21079.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pranavkm** [comment]
This is part of how async-local/call-context work. The mechanism used to propagate culture in .NET Core uses an `AsyncLocal` which only applies to the current call chain. In your case, executing the action is a sibling (and not a parent) of the view rendering call chain. 

Setting the culture in a middleware or a resource filter would do the right thing. Also, consider using the request localization middleware rather than rolling your own solution: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#localization-middleware-2

**Comment by msneijders** [comment]
So if I get this right, for each action method I find that sets the CurrentCulture (and needs to render its view using this culture) I should wrap this action method using an actionfilter/resourcefilter and the logic to determine the culture should move to this filter?

**Comment by pranavkm** [comment]
Specifically a Resource Filter or a middleware. An action filter would run in to the same issue. The diagram on here https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0 might help illustrate this. 

Essentially you want to run as a parent in the async call-chain. Action filter, action execution and result execution are all siblings so configuring in either would not influence the async state in one another.

**Comment by msneijders** [comment]
These async-call-chains al feel a bit opaque to me -- but I can figure this out now, thank you!

**Comment by davidfowl** [comment]
Using the middleware likely makes the most sense.
