### ISSUE TITLE
Making HTTP requests from Blazor apps with custom headers alters the HTTP generates CORS error

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/aspnetcore#31635]
### Describe the bug
Adding custom headers fails ass they are not added nor does the HTTP method stay the same. 
I would like to be able to disable cors error

### To Reproduce
I am adding custom headers to my HTTP request
I get the client from DI using 
```c#
private readonly HttpClient _client;
public AuthenticationService(HttpClient client)
{
    _client = client;
}
```

in my method I use the client like so
````C#
var request = new HttpRequestMessage(HttpMethod.Get, new Uri(url, UriKind.Absolute));
request.Headers.Add("x-a1","Value 1"));
request.Headers.Add("x-a2", "Value 2");
request.Headers.Add("x-a3","Value 3");
using var httpResponse = await _client.SendAsync(request);
````

what it generates is 
```
OPTIONS https://localhost:5003/api/token?userName=admin&password=password HTTP/1.1
Host: localhost:5003
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: x-a1,x-a2,x-a3
Origin: https://localhost:44330
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: https://localhost:44330/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

### Further technical details
- ASP.NET 5.0

**Comment by pranavkm** [comment]
`HttpClient` in Blazor uses `window.fetch` as the transport. Is the behavior different if you do the something similar using `fetch`? If so, then it would warrant further investigation from us. If not, it's pretty much what browsers do with cross-origin requests. Here's what the request would look like:

eg.

```js
fetch('...', { method: 'get', headers: { 'x-a1': 'Value 1' });
```



> OPTIONS https://localhost:5003/api/token?userName=admin&password=password HTTP/1.1

Super unrelated, but are you sure you want to be sending username and passwords as plain text in the query string?

**Comment by PeterPann23** [comment]
I have a blazer app without a fixed backend, CORS is not helping me nor does it add any security as it's a browser thing therefore does not help.

the URL is a sample and not the point, any packet inspector can read data and SSL is not really secure.

As to the issue, I can do a get and get an answer in HTTP using any rest tool, however in blazor I get a CORS error that is no issued by my  API configuration. I would expect an "HTTP get" to become an "HTTP get".

I can write my own wrapper in javascript and do my own implementation of HttpClient and call it and ignore the framework implementation but that's not the point, the point is that I send a valid HttpGet and it gets messed up.

If I send:
```C#
using var request = new HttpRequestMessage(HttpMethod.Get, new Uri(url, UriKind.Absolute));
request.SetBrowserRequestMode(BrowserRequestMode.NoCors);
using var httpResponse = await _client.SendAsync(request);
```
My endpoint answers with data and a 200, blazer will lose the data (I can see it in F12) and state that  
the `httpResponse.IsSuccessStatusCode` is false, and 
 
` var authContent = await httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);`

[sample url](https://www.asp-waf.com/api/token?userName=guest&password=Guest)

**Comment by javiercn** [comment]
@PeterPann23 What @pranavkm is trying to point out is that Blazor Webassembly can't bypass the browser sandbox and that if you are building a Blazor webassembly app you need to deal with CORS in the same way as if you were building a single page application using vanilla JavaScript.

The headers that you see in the requests are not generated by the runtime but by the browser and can't be controlled by the user. It's also the browser that is preventing access to the response, the server will happily return 200 and the response data, but if the browser doesn't see the right headers it will prevent the application from accessing the response.

**Comment by PeterPann23** [comment]
so what is needed to be done to make it work, at the moment I see no way to disable the "browser protection"

**Comment by javiercn** [comment]
> so what is needed to be done to make it work, at the moment I see no way to disable the "browser protection"

There is no way, it's how browsers work. CORS is present to prevent `evil.com` from accessing data in `good.com` unless `good.com` gives it explicit access (through CORS).

Otherwise someone could "bait" a victim into clicking a link to evil.com and retrieve personal data from good.com without the victim knowing anything about it. The way to "disable" it, is for the server (good.com) to give access to the information to (evil.com) via the CORS headers in the response.
