### ISSUE TITLE
SignalR C++ set_client_config not working

### ISSUE THREAD

**Issue by DragonGER** [dotnet/aspnetcore#31639]
### Describe the bug
Hello there,

i was trying to add http headers to my hub connection. In my case for authentication reasons.
However i was unable to set a new client config for unknown reasons.
As soon as i try to set the http headers it will result in a access violation.
I can apply the client config without setting the http headers.

I tried multiple differend things:
* first assign it to the connection and then setting the header
* getting the http headers, then trying to add my header (this fails)

### To Reproduce
```
auto newConnection = signalr::hub_connection_builder::create("https://blub.com/hub").build();
auto clientConfig = signalr::signalr_client_config();
clientConfig.set_http_headers({ { "ApiKey", "fancyApiKey" } });
newConnection.set_client_config(clientConfig);
```

### Exceptions (if any)
Will result in access violation.

### Further technical details
- Got the package from vcpkg
- Using CMAKE with Ninja to build
- Running the latest version of Visual Studio 2019

**Comment by BrennanConroy** [comment]
Where does this AV? Are you using a different compiler to build the library and to build your app?
