### ISSUE TITLE
.Net Hot Reload did not work with blazor wasm 

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/aspnetcore#31632]
Hello
i am use .net 6 preview 3 and vs 2019 16.10.0
but the hot reload did not work with blazor wasm 
here is the picture about every thing.
![ScreenShot_20210409105730](https://user-images.githubusercontent.com/40013555/114149572-bb499980-9923-11eb-9c39-6269fc056fc3.png)

**Comment by javiercn** [comment]
@Ali1Jamal thanks for contacting us.

You put the setting on the iisSettings profile however you are starting Kestrel via dotnet watch. I suspect you need to put `"hotreloadProfile": "blazorwasm"` within the `"Webapplication1"` section for it to work.

**Comment by Ali1Jamal** [comment]
> @Ali1Jamal thanks for contacting us.
> 
> You put the setting on the iisSettings profile however you are starting Kestrel via dotnet watch. I suspect you need to put `"hotreloadProfile": "blazorwasm"` within the `"Webapplication1"` section for it to work.

i put "hotreloadProfile": "blazorwasm" within the "Webapplication1" section and its work now .Thank you very much.

**Comment by javiercn** [comment]
@Ali1Jamal Yep, it's an ASP.NET Core feature, it also works for your pages and views.

**Comment by Ali1Jamal** [comment]
> @Ali1Jamal Yep, it's an ASP.NET Core feature, it also works for your pages and views.

nice, thank you for your time. 👍👍
