### ISSUE TITLE
RZ2005	The 'code` directive must appear at the start of the line.	

### ISSUE THREAD

**Issue by dajma00** [dotnet/aspnetcore#31647]
### Describe the bug
While migrating a .NET5 project to .NET6 preview, in one of the razor files, I am getting this error:
`Error	RZ2005	The 'code` directive must appear at the start of the line.`
	
Code is running  fine on .NET5. Is this some sort of migration issue?

### Further technical details
- ASP.NET Core version 6 preview 3
VS Latest Preview Windows

**Comment by pranavkm** [comment]
Are you able to share the project or preferably a minimal app that demonstrates the problem? Thanks!
