### ISSUE TITLE
ASP.NET Core tag helpers don't allow me to escape attributes annotated with @

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#31640]
Why is the following issue closed?

https://github.com/dotnet/aspnetcore/issues/5075

This has not been resolved and means you have to resort to hacks to get around it. Unfortunately I cannot comment on that issue so I had to create a new one.

**Comment by javiercn** [comment]
@nfplee thanks for contacting us.

it's not a priority for the team since we have not received significant feedback from people that is running into issues because of it.

**Comment by nfplee** [comment]
I'm sure there's quite a lot of developers using Vue with ASP.NET Core.
