### ISSUE TITLE
IClaimsTransformation Implementation in Blazor WebAssembly

### ISSUE THREAD

**Issue by eltinghana** [dotnet/aspnetcore#31657]
I have been trying to add claims to identity after authentication. I have used IClaimsTransformation in asp.net core and tried doing same in Blazor webAssembly. No errors but implementation doesn get called

    public class PermissionToClaimsExtender : IClaimsTransformation {

        private readonly IPermissionService _permissionService;

        public PermissionToClaimsExtender(IPermissionService permissionService)
        {
            _permissionService = permissionService;
        }

        public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            if (principal.Identity is {IsAuthenticated: false}) return await Task.FromResult(principal);

            var userPermClaims = principal.GetClaim(ArchBit.Shared.Common.Enums.ClaimTypes.Permissions);

            if (userPermClaims.HasValue) return principal;
            
            var userId = principal.FindFirst(ClaimTypes.NameIdentifier);

            var (_, isFailure, value) = await _permissionService.GetUserPermissions(userId?.Value,CancellationToken.None);

            if (isFailure) return principal;

            if (principal.HasClaim(x => x.Type == ArchBit.Shared.Common.Enums.ClaimTypes.Permissions.GetAttributeStringValue())) return await Task.FromResult(principal);

            var claims = new List<Claim> { new Claim(ArchBit.Shared.Common.Enums.ClaimTypes.Permissions.GetAttributeStringValue(), value.Permissions) };

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            principal.AddIdentity(identity);

            return principal;
        }
    }

**Comment by javiercn** [comment]
@eltinghana thanks for contacting us.

You are looking for https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#customize-the-user
