### ISSUE TITLE
Rename the Blazor WebAssembly AOT workload

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31659]
We should rename the Blazor WebAssembly AOT workload to reflect its more generic nature. It doesn't just to WebAssembly AoT. It also handles linking and dealing with native dependencies.

Proposal: ".NET WebAssembly Build Tools"

@lewing @pranavkm

**Comment by pranavkm** [comment]
As part of doing this, we should rejigger / rename the workload to follow the SDK's naming guidelines. From https://github.com/dotnet/designs/pull/188/files#diff-8fcaa29d8e6f00b34b3cb1830d93f33e75f04424780a66a3c658c7021048e74fR125,

> Manifests are packaged and distributed as NuGet packages. The ID of the NuGet package is `{manifest-id}.Manifest-{sdk-band}` (for example, `Microsoft.NET.Sdk.Android.Manifest-6.0.200`) and the version of the NuGet package is the manifest version. They will use the existing package type called `DotnetPlatform` so they cannot be accidentally used as a `PackageReference`. The manifest’s `workloadmanifest.json`, `WorkloadManifest.targets`, and any other files are in the `data/` folder of the NuGet package. This ensures that there's not confusion about whether a file in the root is part of the workload manifest or a file owned by NuGet.

**Comment by lewing** [comment]
I think we landed on:


name          | value
------------ | -------------
Text in VS | .NET WebAssembly Build Tools
Description | Build tools for WebAssembly ahead-of-time (AoT) compilation and native linking.

recording it here to make it easier to refer back to

**Comment by SteveSandersonMS** [comment]
Done
