### ISSUE TITLE
Expose EnableBuffering for MultipartSection

### ISSUE THREAD

**Issue by tobias-tengler** [dotnet/aspnetcore#31666]
## Background and Motivation

I'm currently trying to implement a specification that requires me to validate a Multipart form. 
Previously I was using [`FormFeature`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Features/FormFeature.cs) to do the parsing, but since I need to validate the order of boundaries, this is not optimal, since I first have to read the entire form, before I can validate the order.

So I attempted to replicate the behavior of [`FormFeature.InnerReadForm`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Features/FormFeature.cs#L146) in a way that suits my use case. 
I was able to recreate everything I needed except for the [`EnableRewind`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Features/FormFeature.cs#L209) call on the [`MultipartSection`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/WebUtilities/src/MultipartSection.cs).
In order to replicate this in my code, I would have to copy over some internal code, which is really none of my business.

For the [`HttpRequest`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http.Abstractions/src/HttpRequest.cs#L16) the needed internal [`BufferingHelper`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Internal/BufferingHelper.cs) is exposed via [`HttpRequestRewindExtension`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Extensions/HttpRequestRewindExtensions.cs), but it isn't exposed for the [`MultipartSection`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/WebUtilities/src/MultipartSection.cs).

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http
{
+     public static class MultipartSectionRewindExtensions
+     {
+         public static IDisposable EnableBuffering(this MultipartSection section);
+ 
+         public static IDisposable EnableBuffering(this MultipartSection section, int bufferThreshold, long bufferLimit);
+     }
}
```

## Usage Examples

```csharp
// ...

var reader = new MultipartReader(boundary, httpRequest.Body);
var options = new FormOptions();

var section = await reader.ReadNextSectionAsync(cancellationToken);

// if it is a file section we could now enable buffering for it:
section.EnableBuffering(httpRequest.HttpContext.Response.RegisterForDispose, 
    options.MemoryBufferThreshold, options.MultipartBodyLengthLimit);

// ...
```

## Alternative Designs

I wanted to keep it as similar as possible to the [`HttpRequestRewindExtensions`](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Extensions/HttpRequestRewindExtensions.cs), so I haven't thought about alternative designs.

## Risks

None to my knowledge.

**Comment by BrennanConroy** [comment]
>EnableBuffering(httpRequest.HttpContext.Response.RegisterForDispose,

Did you forget this in your API proposal?
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http/src/Internal/BufferingHelper.cs#L31

**Comment by tobias-tengler** [comment]
Dammit I must've forgot about that... I updated my initial proposal!

**Comment by halter73** [comment]
@tobias-tengler Do you really need `registerForDispose` though? Or was it left there because that's how the internal method is? I figured you could dispose whatever you want the usual way when you're done with the MultipartReader.

**Comment by tobias-tengler** [comment]
@halter73 I'm not sure if this would simplify usage of this API. 
In the `BufferingHelper` the `FileBufferingReadStream` is only created and registered for dispose, if the original `Body` of the `MultipartSection` is not seekable. Therefor I would have to explicitly check this condition in my code and keep track of the relevant `MultipartSection` bodies to dispose. Having the API internally register the streams for dispose moves this "complexity" inside the API. In my opinion this would be better from a consumer perspective.

**Comment by BrennanConroy** [comment]
You still should remove the middle two methods as they are ambiguous and you can use the multiple argument method.

**Comment by BrennanConroy** [comment]
```diff
namespace Microsoft.AspNetCore.Http
{
+     public static class MultipartSectionRewindExtensions
+     {
+         public static IDisposable EnableBuffering(this MultipartSection section);
+ 
+         public static IDisposable EnableBuffering(this MultipartSection section, int bufferThreshold, long bufferLimit);
+     }
}
```

This is what we think the API should look like.

Or we might not want this API at all. If we choose not to, we should add documentation for manually adding file buffering.

**Comment by tobias-tengler** [comment]
@BrennanConroy how would my usage example change with the changes you've proposed? Would it be like this:
```csharp
// ...

var reader = new MultipartReader(boundary, httpRequest.Body);
var options = new FormOptions();

var section = await reader.ReadNextSectionAsync(cancellationToken);

var bufferedSection = section.EnableBuffering(options.MemoryBufferThreshold, options.MultipartBodyLengthLimit);
httpRequest.HttpContext.Response.RegisterForDispose(bufferedSection);

// ...
```

**Comment by davidfowl** [comment]
Yes. It's also unclear if there's any value in adding an API here since the same can be done by wrapping the multipart section body manually

**Comment by pranavkm** [comment]
We discussed this in the api-review and think documenting this is sufficient without introducing a new API. We can document this as part of here: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#file-upload-scenarios

```C#
var section = await reader.ReadNextSectionAsync(cancellationToken);
await using var bufferedStream = new FileBufferingReadStream(section.Body, memoryThreshold: 1024 * 30);
...
```

**Comment by tobias-tengler** [comment]
This works for me. Thanks for taking your time looking into this. I look forward to the final documentation! :)

**Comment by SpiritBob** [comment]
> We discussed this in the api-review and think documenting this is sufficient without introducing a new API. We can document this as part of here: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#file-upload-scenarios
> 
> ```cs
> var section = await reader.ReadNextSectionAsync(cancellationToken);
> await using var bufferedStream = new FileBufferingReadStream(section.Body, memoryThreshold: 1024 * 30);
> ...
> ```

Seems the above sometimes throws an exception of the likes "The content has not been fully buffered yet."
with a stack trace

```
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipArchive..ctor(Stream stream)
    .....
    .....
```
