### ISSUE TITLE
Use cache and specify serialization for performance

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/aspnetcore#31676]
### Is your feature request related to a problem? Please describe.
Is it possible to configure the cache to change the serialization ??
Because it is very important in distributed caches that the data volume is small
For example, use messagepack or protubuf

### Describe the solution you'd like
For example, use messagepack or protubuf. like this
```csharp
services.AddStackExchangeRedisCache(options => { }).WithMessagePack();
```

### Additional context
In the use of cache in ordinary and large projects, this issue has become a challenge for programmers.
The EasyCache package supports this, but using AspCore's internal cache is far better than relying on external packages.

**Comment by davidfowl** [comment]
Serialization is up to you. There's nothing built in here. Using EasyCache might be better if it already does what you need

**Comment by EngRajabi** [comment]
Yes, easycache can be used, but it would be better if this feature was here
Because it's complicated for programmers to use

**Comment by BrennanConroy** [comment]
> Serialization is up to you.

The cache implementation(s) accept a `byte[]`, so you do your own formatting/serialization when storing items. You could write a wrapper around the cache that does serialization to a `byte[]` on any types you pass in, but we wont be doing anything with that data.

If you want a whole new caching type, you'll need to propose one in https://github.com/dotnet/runtime/
