### ISSUE TITLE
Merge multiple Hubs into one Endpoint

### ISSUE THREAD

**Issue by SebastianKunz** [dotnet/aspnetcore#31689]
Hello I'm working on a mini game Server using SignalR. I have a bunch of Hubs (one for each minigame) and a LobbyHub, which handles creating lobbies, joining, leaving, ... The Hubs themself need to talk to each other (at least some of them, e.g. lobbyHub tells the specific gameHub that the game is ready to start). I decided for this design, because it lets me seperate the different logics of the hubs.
When thinking about how the hubs can communicate with each other I came up with 2 ideas.
1. Have a seperate SignalR .NET Client that serves as a service bus and relays messages from hub A to hub B (see [this stackoverflow post](https://stackoverflow.com/questions/63451745/communication-between-two-signalr-core-hubs) for more information)
2. Use a MasterHub which inherits all the minigame hubs functionalities. Thus the client only has one active connection to the masterhub and the masterHub provides all Endpoints that are needed to play the games. The masterhub would work as if you put all the hub methods from all the hubs into one Hub. However this doesnt work because C# doesnt support multiple inheritance and therefore you cannot merge multiple hubs into one Endpoint :(

### Describe the solution you'd like
It would be nice to have a way to merge multiple Hub logic into one Endpoint, so you can design Hubs independently from each other and then opt in the functionality you need.

**Comment by BrennanConroy** [comment]
This is not something we are planning on adding, see a previous issue https://github.com/dotnet/aspnetcore/issues/26537

> LobbyHub, which handles creating lobbies, joining, leaving

I would recommend writing a service that interested hubs can accept through DI, then you could have an interface for hubs that use the lobby for common functions like "signin", "joingame", etc.

**Comment by SebastianKunz** [comment]
Thank you for pointing me to the issue I was looking for.
Regarding the lobbyHub: I do have a service which my hub accepts through DI, however I still have to setup the endpoints. I want to write a generic Hub that can be reused in a lot of projects. I would be amazing if people could build hub libraries that work like extensions that you can just add to your application. Need a realtime gps tracker, here you go. Need a chat messanger, here you go.

I guess this will be resolved with the mentioned Issue. Thank you very much!
