### ISSUE TITLE
Exception when trying to run Razor Pages Web App in .NET 6 Preview 3

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#31690]
After updating to .NET 6 Preview 3 the Razor Pages web app doesn't work - I get the following exception when I try to enter the web site:

![image](https://user-images.githubusercontent.com/7391680/114298477-4ca14300-9abf-11eb-80ed-fe69d7ef7f86.png)

### To Reproduce
1. Create brand new "ASP.NET Core Web App" ("Enable Razor runtime compilation" is checked).
2. Run app.
3. Go to the web site

### Further technical details
- ASP.NET Core 6.0.100-preview.3.21202.5
- Windows 10 Pro x64 20H2 build 19042.906
- Visual Studio Community 16.9.3

**Comment by pranavkm** [comment]
Thank you for your issue report. I tried this using the preview3 SDK and do not see an issue with the default app. Are you able to share a minimal app that reproduces the problem? Thanks!

**Comment by JohnyL** [comment]
@pranavkm Here's the [link](https://github.com/JohnyL/RazorPagesDefault) to default Razor Pages template.

**Comment by pranavkm** [comment]
I haven’t built the app, but a quick guess is that you have a preview2 build of the runtime compilation package. Could you try updating it to see if that’s the issue?

**Comment by JohnyL** [comment]
This is interesting. I have installed VS 16.10.0 Preview 1.0. The package is, as you noted, is Preview 2, but... the app is successfully run! Should have tested it with 16.9, but I have already installed 16.10. 😐

**Comment by JohnyL** [comment]
@pranavkm I have installed VS 16.9.3 back and updated runtime package to preview 3 - the error came back. 😐
