### ISSUE TITLE
Creating an aspnet core app on mapped drive results in a empty solution in Visual Studio

### ISSUE THREAD

**Issue by martinjh99** [dotnet/aspnetcore#31695]
### Describe the bug
When creating a aspnet net core webapp on a mapped linux server share it results in an totally empty project in the Visual Studio Community (latest version)

### To Reproduce
1. File/New Project
2. Select ASP.NET Core Web App and click next
3. Change the location of the project to a mapped drive (In my case to s:\aspnet which is mapped to \\sienna\homedir sienna being the hostname of my server)
4.  I enabled Docker and deselected https 
5. Clicked Creeate
 
### Further technical details
- ASP.NET Core version 
   Checked with both 5.0 and 3.1
 
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2019 Windows 16.9.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please verify if creating a project using dotnet cli behaves the same or not for the same path?

**Comment by martinjh99** [comment]
martin@sienna ~/aspnet % mkdir test
martin@sienna ~/aspnet % cd test
martin@sienna ~/aspnet/test % dotnet new webapp
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.1-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on /home/martin/aspnet/test/test.csproj...
  Determining projects to restore...
  Restored /home/martin/aspnet/test/test.csproj (in 130 ms).

Restore succeeded.

Works fine by the looks of it - Loads and runs fine in Visual Studio

**Comment by javiercn** [comment]
@martinjh99 thanks for the additional details.

@vijayrkn can you route this to the right place?

**Comment by martinjh99** [comment]
No problems - I can load up the csproj in Visual Studio and it works fine - Can add Docker support etc...

**Comment by vijayrkn** [comment]
For the VS issue, @martinjh99 - Can you please create an issue through the VS -> Help -> Report an issue. This will provide us with the relevant logs to troubleshoot and fix the issue. Thanks for letting us know about this issue.

**Comment by martinjh99** [comment]
Done.  No worries :)

**Comment by mkArtakMSFT** [comment]
Closing as this will now be tracked on the VS side through the submitted VS Feedback ticket.
