### ISSUE TITLE
Blazor WASM: Detailed Error on Production Environment

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#31699]
Hi, 

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-5.0&pivots=webassembly
_Detailed errors during development_
_When a Blazor app isn't functioning properly during development, receiving detailed error information from the app assists in troubleshooting and fixing the issue. When an error occurs, Blazor apps display a light yellow bar at the bottom of the screen:_
_During development, the bar directs you to the browser console, where you can see the exception.
In production, the bar notifies the user that an error has occurred and recommends refreshing the browser._

The information on this page is pretty clear. However, I still need to capture detailed error messages on my prod system using pdb files. In previous classical applications, I could provide this via web.config.

```
  <system.web>
    <compilation debug="true" targetFramework="4.8" />
  </system.web>
```
When I debugging in the development environment, I can get the stack trace (file name and line number) information of the error. I'm publishing my Blazor WASM project with the "DEBUG" configuration profile. However, I still am not getting the detailed error messages. 

Setting "ASPNETCORE_ENVIRONMENT = Development" also did not work.

I can understand the basic safety concerns. However, I still think that there should be an opportunity to express a preference in this matter. Is there a point I'm missing? Or is Blazor WASM blocking this by default in prod environment?

Thanks in advance.

**Comment by javiercn** [comment]
@creacity thanks for contacting us.

I just scanned the MSBuild targets. You can try setting `<DebuggerSupport>true</DebuggerSupport>` and see if that works. In addition to that (I don't think it applies, but just in case) you can set "detailedErrors":"true" within you appsettings.json file

**Comment by creacity** [comment]
@javiercn thank you for comment. Unfortunately both solutions didn't work.

When debugging, the exception message comes up as below.

```
System.NullReferenceException: Object reference not set to an instance of an object.
at XXX.OnInitializedAsync() in xxx.razor:line 21
at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

However, after publishing the error message just looks like the following.

```
System.NullReferenceException: Arg_NullReferenceException
at XXX.OnInitializedAsync()
at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

This is a good thing for prod environments. However, we have no chance to catch error detailed messages in the published intermediate test versions. The situation is the same for "Release" and "Debug" configuration profiles.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
