### ISSUE TITLE
Blazor - Linking issue with dotnet publish? Too much tree shaking with dotnet illinker? Net6.0 Preview-3

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#31698]
### Describe the bug
Hosted client app is erroring due to dll missing required.

### To Reproduce
I have a hosted blazor app, using pre-rendering in Net6.0 Preview 2. (Server and Client project)

I upgraded to Net6.0 Preview 3 and updated all Nuget packages to latest Preview. Everything works great locally.

When I publish the application 
```
dotnet publish -c Release
```

I get the following error in console when running:
![image](https://user-images.githubusercontent.com/12847647/114319145-1936d680-9b08-11eb-8749-eb5b8efb212f.png)

My client csproj:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-Analytics" Version="3.3.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="6.0.0-preview.3.21201.13" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-preview.3.21201.13" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="6.0.0-preview.3.21201.13" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-preview.3.21201.4" />
    <PackageReference Include="P4.Commerce.PublicApi.Contract" Version="0.1.73" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-preview.3.21201.4" />
    <PackageReference Include="Toolbelt.Blazor.HeadElement" Version="5.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\P4.ITOps.AspNetCore.Blazor.Core\P4.ITOps.AspNetCore.Blazor.Core.csproj" />
    <ProjectReference Include="..\P4.Web.Shared.Components\P4.Web.Shared.Components.csproj" />
  </ItemGroup>

</Project>
```

Through [a LOT of]experimentation and comparison between local dev and the published version, I realise that it looks like we are serving smaller dlls. Trial and error I found that `Microsoft.AspNetCore.Components.WebAssembly` is the problem.

In browser tools you see the dll downloaded is 20.2KB:
![image](https://user-images.githubusercontent.com/12847647/114319234-8c404d00-9b08-11eb-9797-0a99e53bee3c.png)

Reviewing the publish log when running `dotnet publish -c Release` you see:

```
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
```
Using this as a hint, I add the following to my client csproj:
```
  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>
```
Browser tools show download is now 26.0 KB and the application does not error.
![image](https://user-images.githubusercontent.com/12847647/114319240-96fae200-9b08-11eb-8dd3-23c6a213b3e3.png)

It seems that we are stripping out something that is required by the app.

Note: I am not doing any reflection in the app (I suppose it's possible 1 of the libraries is - I have not checked implementations)

### Further technical details
Have the 2 dlls for comparison.
Using ILSpy or DotPeek you can see a number of differences between the 2 dlls. I haven't yet got to the bottom of the exact problem.
[Dlls.zip](https://github.com/dotnet/aspnetcore/files/6292717/Dlls.zip)

cc: @Bigtalljosh

**Comment by javiercn** [comment]
@srpeirce thanks for contacting us.

This seems like an issue on our side.

**Comment by srpeirce** [comment]
Thank you @javiercn 👍

**Comment by SteveSandersonMS** [comment]
We think this will be fixed in more recent previews. Could you please try the latest .NET 6 preview and let us know if the issue still affects your application? Thanks!

**Comment by srpeirce** [comment]
Yep it's now resolved. Thanks 👍
