### ISSUE TITLE
Microsoft.AspNetCore.DataProtection PersistKeysToDbContext : unable to retrieve decryption key

### ISSUE THREAD

**Issue by ahmedkamal-TeraByte** [dotnet/aspnetcore#31706]
I am working with encryption some data using ceritificate.
i have been using following method to encrypt and decrypt data with a certificate that was already added in windows Certificate store.

```
services.AddDataProtection()
                    .ProtectKeysWithCertificate(thumbprint)
                    .PersistKeysToDbContext<CloudDbContext>();
```

it was working completely fine.. but then we decide to move our server from windows to linux. Hence, i exported that certificate from windows cert manager and put it in linux machine and used the following code.

```
services.AddDataProtection()
                    .ProtectKeysWithCertificate(new X509Certificate2(certificateDetails.GetValue<string>("filePath"), certificateDetails.GetValue<string>("password")))
                    .PersistKeysToDbContext<CloudDbContext>();
```

as it is the same certificate so it is supposed to be working fine. because keys are stored in the database. and i've verified that keys are present in database. but everytime i try to decrypt my data, i get the following exception..

```
An exception occurred while processing the key element '<key id="07dabe64-845f-4f2f-8e1d-e63ae1ee4b08" version="1" />'.
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
  at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
  at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
  at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
  at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
  at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
```

Now this key " id="07dabe64-845f-4f2f-8e1d-e63ae1ee4b08" is present in my db.. but somehow it is unable to retrieve..

The new data is being encrypted and decrypted properly using this certificate and a new key is also being generated and stored in the database. but the older data can't be decrypted.. How can i decrypt the older data???

**Comment by blowdart** [comment]
What version of .NET Core are you using? Can we see your startup.cs (with any secrets removed)?

**Comment by ahmedkamal-TeraByte** [comment]
@blowdart  i am working with .net core 3.1.  and i here's the startup.cs file. 

```
using Alachisoft.NCache.Cloud.API.Configurations;
using Alachisoft.NCache.Cloud.API.Error;
using Alachisoft.NCache.Cloud.API.Filters;
using Alachisoft.NCache.Cloud.API.Models;
using Alachisoft.NCache.Cloud.API.Services;
using Alachisoft.NCache.Cloud.Common.Interfaces;
using Alachisoft.NCache.Cloud.Common.Services;
using Alachisoft.NCache.Cloud.Common.Util;
using Alachisoft.NCache.Cloud.Data;
using Amazon.AWSMarketplaceMetering;
using AutoMapper;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Tokens;
using Serilog;
using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;

namespace Alachisoft.NCache.Cloud.API
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public Startup() { }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(Configuration)
            .CreateLogger();

            Log.Information("Starting up");


            //FluentValidater Registration
            services.AddMvc(setup =>
            {
            }).AddFluentValidation(options =>
            {
                options.RunDefaultMvcValidationAfterFluentValidationExecutes = false;
                options.RegisterValidatorsFromAssemblyContaining<Startup>();
            });

            // inject HttpClient
            services.AddHttpClient();
            //use in-memory cache for temporary storage
            services.AddMemoryCache();
            services.AddCors();
            services.AddControllers().AddNewtonsoftJson();
            services.AddAutoMapper(typeof(Startup));
            //configure auditlog filter
            services.AddScoped<AuditLogFilter>();
            //ConfigureValidations(services);
            // configure strongly typed settings objects
            
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
#if DEBUG
            IConfigurationSection certificateDetails = Configuration.GetSection("CertificateDetails");
            services.AddDataProtection()
                    .ProtectKeysWithCertificate(new X509Certificate2(certificateDetails.GetValue<string>("filePath"), certificateDetails.GetValue<string>("password")))
                    .PersistKeysToDbContext<CloudDbContext>();
#elif RELEASE
            services.AddDataProtection()
                .ProtectKeysWithCertificate(Configuration.GetSection("CertificateDetails").GetValue<string>("Thumbprint"))
                .PersistKeysToDbContext<CloudDbContext>();

#endif
            services.AddSingleton<IDataProtector>(x => x.GetDataProtector("NCProtectorKey"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseHttpsRedirection();
            app.UseRouting();

            //global cors policy
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader());

            app.UseAuthentication();
            app.UseAuthorization();
            app.UseMiddleware<ErrorHandlerMiddleware>();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}

```

**Comment by blowdart** [comment]
Can you move your AddDataProtection section to the very beginning of ConfigureServices, just to rule out ordering?

**Comment by ahmedkamal-TeraByte** [comment]
sure.. but does this has anything to do with the problem???

**Comment by ahmedkamal-TeraByte** [comment]
as far as my understanding, there are two things involved in this process. 
i- a certificate
ii- an encryption key. 

Certificate can be provided using different overloads, either using a thumbprint, or pfx file .

Keys are to be stored in file system or any other preffered place. 

if these two things are accessible, then data should be encrypted and decrypted from any machine. 

please correct me if i am wrong ...

**Comment by blowdart** [comment]
Yes. When you add MVC it adds data protection and configures it because it relies on it. Putting data protection last and configuring it means that configuration won't get applied, because it's already configured.

**Comment by ahmedkamal-TeraByte** [comment]
I have moved these to the top just to make things in order. 

But with current order,the configurations were being applied.. i have verified that... Keys are being created and store in the database . 
I have also verified by removing specified certificate and keys.. It works fine on my current server. 

But now when i want to move my server, i can't decrypt the data that was encrypted on old server.

**Comment by blowdart** [comment]
Ok that rules out order. The other thing to look at is the application name. Data Protection isolates applications based on an auto-generated [ApplicationDiscriminator](https://github.com/dotnet/aspnetcore/blob/main/src/DataProtection/DataProtection/src/DataProtectionOptions.cs), to allow for safe sharing of a keyring between applications. It's likely that on linux and windows the autogenerated name is different. This is generated by the IApplicationDiscriminator service.

At the end your ConfigureServices try outputting the result from `services.GetService<IApplicationDiscriminator>()?.Discriminator;`. Are those the same? If not, then when configuring DataProtection [set the discriminator](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0#per-application-isolation) as shown in the docs,

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection()
        .SetApplicationName("shared app name");
}
```

And set the name to match the auto generated one on Windows.

**Comment by ahmedkamal-TeraByte** [comment]
I did set the application name in my startup and deployed on both windows and linux servers with same application name. 
But unfortunately, i still have some problem. 
```
IConfigurationSection certificateDetails = Configuration.GetSection("CertificateDetails");
            services.AddDataProtection()
                    .SetApplicationName("NCCloud")
                    .ProtectKeysWithCertificate(new X509Certificate2(certificateDetails.GetValue<string>("filePath"), certificateDetails.GetValue<string>("password")))
                    .PersistKeysToDbContext<CloudDbContext>();
```

I get same exception i.e. Unable to retrieve decryption keys.

**Comment by blowdart** [comment]
Strange. And you're sure the X509Certificate instance has the private key, and it's the certificate used to encrypt that key? That DPAPI doesn't get involved on windows in any way? You'd see a comment in the <encryptedKey> element for the key

**Comment by ahmedkamal-TeraByte** [comment]
Using "ApplicationName", i deployed my application on two different Linux servers. 
it worked fine.. it was able to decrypt each other's data. 

but with one linux and one windows server, windows application was unable to decrypt data encrypted by linux server. 

I was running windows application in debug mode? can this somehow effect this????

**Comment by blowdart** [comment]
It shouldn't. Hey @GrabYourPitchforks this should work with mixed platforms right?

**Comment by GrabYourPitchforks** [comment]
```txt
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
  at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
  at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
```

This error is coming from `EncryptedXml`, specifically [this line](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs#L374). I'm guessing what's happening is that `EncryptedXml` is reading the X.509 cert data from the encrypted XML blob, it's looking on the local box for the private key that corresponds to that cert, it can't find that private key, and it's failing the operation.

Note: "decryption key" (or "private key") in the above contexts means __the private key of the X.509 cert__, not the symmetric key used by DataProtection.

As a first step in debugging, can you use the normal `X509Certificate2` class to open the target certificate and perform a signing operation? (Or check the `X509Certificate2.HasPrivateKey` property.) If this step fails, it means your app can't find the X.509 cert's private key. Double-check that the cert has been properly deployed to your host environment.

**Comment by blowdart** [comment]
@bartonjs for x509. Jeremy any ideas?

**Comment by bartonjs** [comment]
I'm not sure there's really an X.509 thing here, it's mostly EncryptedXml-isms.

I... think... that method only uses certs from the CurrentUser\My or LocalMachine\My store.  The exception means one of:

* There were no KeyInfo values that were of known types
* There were X509KeyInfo values but no certificate was found in the appropriate persisted store that matched it.
  * Also, to match it has to be a cert with an RSA key.
  * Also, to match the candidate cert has to know about a private key.

At least, I'm not seeing any way that EncryptedXml.DecryptDocument works with call-provided certs, it seems to be a "yay, ambient state" API

**Comment by blowdart** [comment]
Oh no. How can we shim that in on linux?

**Comment by bartonjs** [comment]
Looks like DataProtector uses an EncryptedXml derived type which adds that support on top:

https://source.dot.net/#Microsoft.AspNetCore.DataProtection/XmlEncryption/EncryptedXmlDecryptor.cs,4640450d42ebf503

I'm not quite sure how all it ends up interplaying.

**Comment by blowdart** [comment]
OK assigning @HaoK to investigate further

**Comment by HaoK** [comment]
@ahmedkamal-TeraByte can you try levi's suggestion to help scope the issue a bit more?

> As a first step in debugging, can you use the normal X509Certificate2 class to open the target certificate and perform a signing operation? (Or check the X509Certificate2.HasPrivateKey property.) If this step fails, it means your app can't find the X.509 cert's private key. Double-check that the cert has been properly deployed to your host environment.

**Comment by ahmedkamal-TeraByte** [comment]
sure @HaoK  i'll try it and update here ...
