### ISSUE TITLE
Update Polly dependency to latest release?

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#31705]
### Is your feature request related to a problem? Please describe.

ASP.NET Core currently depends on Polly 7.1.0, which was [released in March 2019](https://www.nuget.org/packages/Polly/7.1.0).

https://github.com/dotnet/aspnetcore/blob/1870441efdc00a6c253c2a5c54c20a313fb56ee2/eng/Versions.props#L249

Since then there have been a number of minor releases, the most recent being yesterday to 7.2.2, to fix a number of bugs and minor improvements ([CHANGELOG](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md)).

### Describe the solution you'd like

Update the Polly dependency to the latest release, [7.2.2](https://www.nuget.org/packages/Polly/7.2.2).

Updating to at least 7.2.0 would also make the new `IConcurrentPolicyRegistry` interface available, which could then be registered by default in the Polly extensions for HttpClientFactory: https://github.com/dotnet/aspnetcore/pull/28283#discussion_r598061746.

Assuming there isn't a specific reason to pin the dependency at 7.1.0, I'd be happy to raise a PR to update the minimum version for ASP.NET Core 6.0.

**Comment by javiercn** [comment]
@martincostello thanks for contacting us.

Are there known breaking changes between 7.2.2 and 7.1.0? I think we would be open to a PR if there are no breaking changes, otherwise we would need to evaluate the impact.

**Comment by martincostello** [comment]
@javiercn No, there shouldn't be any breaking changes. There's no changes to the public API other than the addition of the new `IConcurrentPolicyRegistry` interface and `PolicyRegistry` implementing it. All the other changes are just bug fixes.

If you'd be happy to accept a PR to update the dependency then I'll open one later on today 👍

**Comment by javiercn** [comment]
@martincostello go for it.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/31708
