### ISSUE TITLE
Blazor server-side - <AuthorizeView /> not working after "Attempting to reconnect to the server: 1 of 8"

### ISSUE THREAD

**Issue by monica-vrancean** [dotnet/aspnetcore#31712]
We have a Blazor server-side application and we use for authorization the <AuthorizeView /> component with Roles and Policies. 
After the message "Attempting to reconnect to the server: 1 of 8" is displayed the <AuthorizeView/> loses track of the existing roles and it returns "not authorized".

We set the claims for the roles on the ClaimsPrincipal user from AuthenticationState. Permissions are resolved correctly before the above message is displayed. The application needs to be restarted to gain back the permissions. AuthenticationState persists the claims but <AuthorizeView/> does not resolve them.
If we use our custom authorization component and check the roles everything works as it should even after the "Attempting to reconnect" message. 
This can be reproduced by adding a breakpoint and waiting for the application to show the "Attempting to reconnect" message and only after that releasing the breakpoint. All the authorized parts that were visible before are now restricted.

Is there a way to fix this without replacing the <AuthorizeView/> component?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
