### ISSUE TITLE
Blazor Desktop Not Supporting Routing

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#31714]
Currently I found that for now, there is no support for routing.  Which means if you have a blazor component that sends a route to another location, does not work.  I also tried adding an App component and do the routing so it routes to the "/"

If there are no plans to support routing, then would be important to make it clear that when you use blazor from outside of web assembly and server side, there is no routing support.  Good news is most pages can be done without routing.  Unfortunately, there are a few complex scenarios that works best with routing.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

Can you clarify exactly what is not working? Routing should work in the same way as in other flavors.

**Comment by musictopia2** [comment]
When I created a component called App, and copied the stuff that would have worked in webassembly and server side, i first got some errors.  Once the errors was fixed, I was still unable to make it go to the index route.  If you need a repository, I can create a simple repository to show that routing is currently not working with blazor desktop at all.  Even the sample for getting started showed no routing (just going directly to the counter component).

**Comment by javiercn** [comment]
@musictopia2 that would be helpful
