### ISSUE TITLE
System.Private.CoreLib: Exception while executing function: Function1. System.Data.SqlClient: Keyword not supported: 'authentication'

### ISSUE THREAD

**Issue by Pranay8070** [dotnet/aspnetcore#31716]
Hi, I am getting the following error when I'm trying to connect function apps to azure sql database(Azure active directory login)

![image](https://user-images.githubusercontent.com/82394820/114415663-86606f80-9bcd-11eb-8d62-03eb5e8e29a2.png)

**Comment by javiercn** [comment]
@Pranay8070 thanks for contacting us.

In order for you to get a better and faster answer we suggest you file this issue directly within the azure functions reo [here](https://github.com/Azure/Azure-Functions)
