### ISSUE TITLE
Microsoft.AspNetCore.App v2.1.27 pins new references that breaks the latest OData Nuget References

### ISSUE THREAD

**Issue by tsharp** [dotnet/aspnetcore#31725]
v2.1.27 nuget package pins a number of libraries to 4.6.0 not inclusive. This breaks downstream dependencies when combined with the OData libraries.

v2.1.26:
![image](https://user-images.githubusercontent.com/2798069/114454220-36fb4e80-9b8f-11eb-86bd-349f5970cfe2.png)

v2.1.27:
![image](https://user-images.githubusercontent.com/2798069/114454276-4bd7e200-9b8f-11eb-970c-8c348c63003f.png)

### To Reproduce
1. Create a new .net core web app v2.1, upgrade to latest version of library - v2.1.27
2. Install the latest v4.5.x line of `Microsoft.AspNetCore.OData`
3. Observe the errors:
![image](https://user-images.githubusercontent.com/2798069/114454654-b25d0000-9b8f-11eb-8773-bf68fe91b6e0.png)

### Further technical details
- ASP.NET Core version: v2.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@tsharp thanks for contacting us.

Can you give us details on the OData library ids and versions that are running into this issue?

**Comment by tsharp** [comment]
Microsoft.AspNetCore.OData 7.5.7 and 7.5.6

https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.5.7
https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.5.6

**Comment by Pilchie** [comment]
Tagging @dotnet/aspnet-build to take a look here.

**Comment by dougbu** [comment]
@tsharp the OData team has resolve this problem w/ https://github.com/OData/odata.net/commit/7e08912aaa8a6d2fe2bdcbe9b5923f06fff20947. When a new version of Microsoft.OData.Edm is available, please try it out. I believe https://www.myget.org/feed/odlnightly/package/nuget/Microsoft.OData.Edm should be updated in the next day or two to contain that fix.

**Comment by tsharp** [comment]
@dougbu Thank-you so much for the follow up. We'll go ahead and start testing this in our build pipelines asap.

**Comment by xuzhg** [comment]
Here's the latest odata.edm link: https://www.nuget.org/packages/Microsoft.OData.Edm/7.9.0

Here's the depdendencies:

![image](https://user-images.githubusercontent.com/9426627/118047260-5ffa3500-b32f-11eb-9500-9a2141b915e3.png)
