### ISSUE TITLE
no Startup.cs created upon creating a new Blazor WebAssembly project

### ISSUE THREAD

**Issue by bolat** [dotnet/aspnetcore#31731]
no Startup.cs created upon creating a new Blazor WebAssembly project. Why is that and what to do?

**Comment by ar0311** [comment]
Blazor WASM doesn't use a Startup.cs anymore for quite some time.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is by-design. ALl the DI service registration code is in `Program.cs`.
