### ISSUE TITLE
Blazor apps built using default template now seeing console warnings in F12 developer tools

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#31737]
Example message :
Site cannot be installed: Page does not work offline. The page will not be regarded as installable after Edge 93, stable release August 2021.

![image](https://user-images.githubusercontent.com/35312807/114334545-9f9aea80-9aff-11eb-9388-6eef98a9390e.png)

**Comment by ChristianWeyer** [comment]
This is the same as https://github.com/dotnet/aspnetcore/issues/30925

**Comment by mkArtakMSFT** [comment]
Looks like Google has resolved the issue causing this.
