### ISSUE TITLE
Unable to receive authorization header in asp.net core API application

### ISSUE THREAD

**Issue by kawanami-nsd** [dotnet/aspnetcore#31732]
I am creating the following program.

client
```
var factory = _provider.GetRequiredService<IHttpClientFactory>();
var client = factory.CreateClient();

var request = new HttpRequestMessage(HttpMethod.Get, Uri_Xxx)
request.Headers.TryAddWithoutValidation("Authorization", $"Bearer {AccessToken}");

client.SendAsync(request, ... more parameters ...);
```

api server
```
public class UsersController : ControllerBase
{
        [HttpGet("me")]
        public async Task<IActionResult> Me([FromHeader] string authorization)
        {
            // authorization is empty
        }
}
```

I updated the version of dotnet core used in the application from 2.2.6 to 3.1.10.

It works fine in an environment where dotnet-hosting 2.2.6 is installed.

If you install dotnet-hosting 3.1.10 in an environment where the program is working without problems, the program will not work.

Has the method of specifying the authorization header changed in dot net core 3.x?

**Comment by kawanami-nsd** [comment]
By the way, it is additional information. When I communicated with WebAPI using REST Client, I was able to get the authorization header without any problem, so I was able to confirm that it was working.

So I think that there is a problem in the part passing the Authorization header on the client side.
Has there been a change in the way you specify the Authorization header in 2.2.6 and 3.1.10. Or is it sometimes not possible to change the authorization header after installing 3.1.10 of dotnet-hosting-runtime that I have installed?

**Comment by davidfowl** [comment]
Can you make a runnable project that we can use to reproduce the problem?

**Comment by kawanami-nsd** [comment]
Please wait for a while as we will prepare the project.

**Comment by kawanami-nsd** [comment]
I'm sorry it took a long time to reply.

Since it is not possible to pass the project in which the error occurs as it is, I cut out the part where the error occurred and created a new project.
I placed the module created from the new project in the verification environment and checked the operation, but I don't know why, but the error no longer occurs.
In addition, the module created from the project that originally had the error no longer causes the error.

Therefore, we cannot send the project in the state where the error occurs.
If it seems difficult to continue the investigation, I will close this issue.

**Comment by rafikiassumani-msft** [comment]
Closing per user request.
