### ISSUE TITLE
Signalr: Uncaught (in promise): Error: Invocation canceled due to the underlying connection being closed.

### ISSUE THREAD

**Issue by avialonn** [dotnet/aspnetcore#31751]
Hi, 
Ive implemented signalr with angular 11 and .net 5.
When user logout I call the  this.hubConnectionValue.stop(); and sometime I get the following message:
![image](https://user-images.githubusercontent.com/72415692/114563925-89fd0080-9c78-11eb-84a7-4da33f20aea3.png)

Any idea on what might be the issue?
Thanks

**Comment by BrennanConroy** [comment]
Looks like you aren't properly awaiting a `hubConnection.invoke` so you have an unhandled exception from an active invoke call when the connection is closed.

**Comment by avialonn** [comment]
Thanks for the quick reply.
Can you direct me to the relevant docs? my implementation is quite straight forward

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#call-hub-methods-from-the-client

"Uncaught (in promise)" is a fairly common issue you can find out about
https://stackoverflow.com/questions/37624322/uncaught-in-promise-undefined-error-when-using-with-location-in-facebook-gra

I assume you have something like `hubConnection.invoke("blah");` and you are ignoring the result. Should have `await hubConnection.invoke("blah");` or `hubConnection.invoke("blah").catch(e => {});`

**Comment by avialonn** [comment]
Ok I've added the catch but that's just mask the 'Invocation canceled due to the underlying connection being closed' error.
How can I understand why its happening?
Thanks again!

**Comment by BrennanConroy** [comment]
> an active invoke call when the connection is closed.

If the connection is closed, we need to make sure anyone awaiting an invoke doesn't hang. Do you have any suggestions to make the error clearer?

**Comment by avialonn** [comment]
No i see that when I close the connection I send a last request of remove user from a group. Could that be the issue where the callback is not going through?
