### ISSUE TITLE
Css Isolation issue still remains at Dotnet 6 Preview 3 for traditional AspNet Core Web Application 

### ISSUE THREAD

**Issue by tanekim77** [dotnet/aspnetcore#31750]
I created a fresh Asp.Net Web Application and added a _Layout.cshtml.css file to test if css isolation feature is working, as in the following screen shot
![image](https://user-images.githubusercontent.com/20119808/111632174-9a7da080-87ca-11eb-90e9-466e45227fda.png)

But when I run the application, I am seeing a weird letters on top of the file (i.e. "b-g6ltozs93r"), and the css content is not working either. It is supposed to have green background.

![image](https://user-images.githubusercontent.com/20119808/111631805-39ee6380-87ca-11eb-8106-edf0cb40e971.png)

**Comment by javiercn** [comment]
@tanekim77 thanks for contacting us.

@captainsafia do you know when we fixed this?

**Comment by captainsafia** [comment]
It was fixed, however, it will ship with 6.0-preview4.

@tanekim77 You can grab a nightly installer of preview4 from https://github.com/dotnet/installer if you'd like to try it out.

**Comment by tanekim77** [comment]
@captainsafia  Thanks, I will give a try
