### ISSUE TITLE
Update the documentation for FileBufferingReadStream.Length

### ISSUE THREAD

**Issue by Skleni** [dotnet/aspnetcore#31753]
### Describe the bug
The `Length` property of the `FileBufferingReadStream` returns 0 before any data is read. Looking at the [tests](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/WebUtilities/test/FileBufferingReadStreamTests.cs#L31), this seems to be the expected behavior, but I'm not sure if it is right. It might prevent users of the stream from ever calling `Read`. For example, when trying to upload such a stream using the `Azure.Storage.Blobs` nuget package, you end up with an empty blob (see [this related issue](https://github.com/Azure/azure-sdk-for-net/issues/17110)).

### To Reproduce

The following code prints `0`.

```csharp
using (var stream = new MemoryStream(new byte[1024]))
using (var buffer = new FileBufferingReadStream(stream, 1024, default, Path.GetTempPath()))
{
    Console.WriteLine(buffer.Length);
}
```

A slightly larger example is available in the issue mentioned above.

### Further technical details
- Microsoft.AspNetCore.WebUtilities 2.2.0
- .NET Core 3.1 Windows 10
- Visual Studio 16.9.3

**Comment by Skleni** [comment]
I also found [this article](https://titanwolf.org/Network/Articles/Article?AID=d4d4fc71-ee59-48c8-b5da-0528d1248954) which seems to describe a related problem, although I didn't understand all of it to be honest.

**Comment by Tratcher** [comment]
This is known behavior, but we should update the API docs to cover it.

FileBufferingReadStream is a read-through stream, it buffers the data from the inner stream as it's read. It only knowns the length of the data already read/buffered. The inner stream is normally a request body stream that doesn't support the Length property.

**Comment by pranavkm** [comment]
FYI @Skleni, the version of Microsoft.AspNetCore.WebUtilities package that you're targeting has been out of support for about 2 years now.

**Comment by Skleni** [comment]
You're right @pranavkm, I wasn't actually using the package in my real app, it just slipped in in my reproduction sample.

What I'm actually doing is using the `HttpRequestRewindExtensions.EnableBuffering` extension method which internally replaces the request's body with a `FileBufferingReadStream`.

When I then want to upload this stream to the blob storage, it doesn't work, because the stream's length appears to be 0.

I think it's a good idea to update the documentation, but it won't help with my problem. The `BlobClient` has no idea that I'm handing it a `FileBufferingReadStream` and that checking the length is not reliable here. They say that they don't upload anything because I hand them an empty stream:

> Obviously if you go and hand Upload an empty buffer, there won't be anything to upload.

Are they supposed to call `Read` even though the stream says it has a 0 length?

**Comment by Tratcher** [comment]
Why are you enabling buffering before sending the data to blob storage? Do you also want a copy locally? If so, consume the stream before sending it on.

**Comment by Skleni** [comment]
Yes, I also need to do some local processing of the same stream. What do you mean by consuming the stream before sending it on?

**Comment by Tratcher** [comment]
Today you enable buffering, send to blob, and then do extra processing on the buffered content. Since blob storage wants to know the length I recommend reordering it to enable buffering, do your local processing, and then send the buffered content to blob storage.

**Comment by pranavkm** [comment]
@Skleni you could drain the request and reset it. That should give you an accurate Length:

```
FileBufferingReadStream stream = ...;
await stream.DrainAsync();

var contentLength = stream.Length; // this should be accurate now.
stream.Position = 0;
```

**Comment by Skleni** [comment]
I guess that will work for my problem, thanks!

Still, it feels a bit like treating the symptom and not the underlying problem, namely the `FileBufferingReadStream` and the `BlobClient` disagreeing on the contract defined by the `Stream` class.

Is it a valid usage of a `Stream` to do something like this:

```csharp
void Consume(Stream stream)
{
    var buffer = new byte[1024];
    int read = 0;
    while (read < stream.Length)
    {
        read += stream.Read(buffer, read, buffer.Length);
    }
}
```

If yes, the the `FileBufferingReadStream` does not implement this contract correctly. If no, then the `BlobClient` seems to do something wrong (that's just my personal point of view).

**Comment by pranavkm** [comment]
> Is it a valid usage of a Stream to do something like this:

Usually this would only work if a stream is seekable. In the absence of this, the API is allowed to throw: https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-5.0#remarks.

In the case of the `FileBufferingReadStream`, I think we need to have `CanSeek` return `false` until the underlying stream has been fully buffered. Essentially this check: https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/FileBufferingReadStream.cs#L222-L226 would be replicated in `CanSeek` which currently always returns `true`

@Skleni are you able to do a quick check if changing the behavior of `CanSeek` addresses the issue you're seeing? You could wrap `FileBufferingReadStream` in a [delegating stream](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/NonDisposableStream.cs) where the delegating stream's `CanSeek` always returns false?

**Comment by Skleni** [comment]
Yes, I'll try it tomorrow.

**Comment by Tratcher** [comment]
That implementation of Consume is not recommended since Length is an optional property (it can throw). The standard is to read until Read returns 0.

> In the case of the `FileBufferingReadStream`, I think we need to have `CanSeek` return `false` until the underlying stream has been fully buffered.

Changing CanSeek is going to cause the same kinds of confusion, breaking logic that checks `CanSeek` to see if it needs to add its own buffering. I think FileBufferingReadStream is doing the best it can within the limited Stream contract.

**Comment by Skleni** [comment]
@pranavkm Wrapping the `FileBufferingReadStream` in a delegating stream that always returns false from `CanSeek` works indeed.

**Comment by Henery309** [comment]
Hi I am having similar issues. My application has a multipart file upload feature (which I am in process of upgrading to .net 5). 
When uploading file the client sends metadata in the multipart request along with the file section. Before the file is uploaded to azure blob I have to extract the metadata save to database and then upload the file to azure storage. 

Extracting the metadata sections works fine. But when I try to read the stream second time the stream is empty which results in a blank file being uploaded. This worked fine when used with old SDK. 

Here is my code, I am trying to figure out where I should drain the stream as pointed out by @pranavkm. 

```
// Enable buffering so that we can read the stream twice.
context.Request.EnableBuffering();

var boundary = GetBoundary(MediaTypeHeaderValue.Parse(context.Request.ContentType), DefaultFormOptions.MultipartBoundaryLengthLimit);
var reader = new MultipartReader(boundary, context.Request.Body, 80 * 1024);

MultipartSection section;
var fileName = string.Empty;
var contentType = string.Empty;
var tenantId = string.Empty;
var userName = string.Empty;

while ((section = await reader.ReadNextSectionAsync()) != null)
{
    // Get file content disposition header. We need this to check whether multipart section is a file or text field.
    var contentDisposition = section.GetContentDispositionHeader();

    // Check if contentDisposition is a file if so we need to extract file name and contentType
    if (contentDisposition != null && contentDisposition.IsFileDisposition())
    {
        // Parse section into file section and extract information about the file.
        var fileSection = section.AsFileSection();

        // Extract file name first
        fileName = fileSection.FileName;
        contentType = fileSection.Section.ContentType;
    }

    // Here we are going to read metadata that is sent along with the multipart request.
    if (contentDisposition != null && contentDisposition.IsFormDisposition())
    {
        var dataSection = section.AsFormDataSection();

        var fieldName = dataSection.Name.ToLower();

        if (fieldName.Equals("UserName"))
        {
            userName = await dataSection.GetValueAsync();
        }

        if (fieldName.Equals("TenantId"))
        {
            tenantId = await dataSection.GetValueAsync();
        }
    }
}

// Upload file to azure store
// NOTE - this is a simplified example. The actual uploading of the file happens in another class.
var containerClient = service.GetBlobContainerClient("containerName");
var blobClient = containerClient.GetBlobClient(Guid.NewGuid().ToString());
var httpHeaders = new BlobHttpHeaders { ContentType = contentType};

// Here we are going to get a reference to the file stream and pipe that to azure blob storage. 
// Note the idea here is to not buffer the file locally. but not sure if this is correct.
var sBoundary = GetBoundary(MediaTypeHeaderValue.Parse(context.Request.ContentType), 128);
var sReader = new MultipartReader(sBoundary, context.Request.Body);

// read the first section from multi-part request the file will be sent in the first section.
var sSection = await sReader.ReadNextSectionAsync();
var sFileSection = sSection.AsFileSection();
var stream = sFileSection.FileStream;

// Now upload to azure.
// ###-- this is where the problem. Empty file is uploaded to azure.
var res = await blobClient.UploadAsync(stream, httpHeaders);`

**Comment by BrennanConroy** [comment]
Triage: Let's update the documentation to say that the length is only usable when fully buffered.
```
FileBufferingReadStream stream = ...;
await stream.DrainAsync();

var contentLength = stream.Length; // this should be accurate now.
stream.Position = 0;
```

**Comment by jteer** [comment]
Hello, I would like to make this change for my first issue.

How does this update sound?

```csharp
/// <summary>
/// The length of bytes read into the buffer from the inner stream so far.
/// </summary>
public override long Length ...
```

**Comment by BrennanConroy** [comment]
I don't think we should describe the internals like this, probably just want to say that the length isn't accurate until the stream is fully buffered. e.g. using `stream.DrainAsync()`

**Comment by Tratcher** [comment]
That's not internals, though it could be rephrased to be clearer:
The total bytes read from and buffered by the stream so far, it will not represent the full data length until the stream is fully buffered. e.g. using stream.DrainAsync().
