### ISSUE TITLE
Avoid the use of the word "Component" in built-in component names (types)

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#31754]
## Summary

Avoid the use of the word "Component" in built-in components (types) names.

## Motivation and goals

When composing content in the docs for components (built-in and examples made up for doc examples), the structure of the text must include the code-fenced component (type) name and the word "component" in text for localization. This results in redundant naming, thus poor phrasing.

## In scope

All built-in components, and I think `DynamicComponent` is the only case thus far.

It's not normal to use "Component" ... i.e. ...

- App
- Authentication
- AuthorizeView
- CascadingValue
- InputCheckbox
- InputDate
- InputFile
- InputNumber
- InputRadio
- InputRadioGroup
- InputSelect
- InputText
- InputTextArea
- LayoutView
- MainLayout
- NavLink
- NavMenu
- Router
- Virtualize

## Out of scope

None

## Risks / unknowns

None AFAICT

## Examples

Currently in docs, the new `DynamicComponent` composes in text as ...

> The \`DynamicComponent\` component allows you to render a component specified by type.

The `DynamicComponent` component allows you to render a component specified by type.

I hope for ...

> The \`Dynamic\` component allows you to render a component specified by type.

The `Dynamic` component allows you to render a component specified by type.

# Detailed design

`DynamicComponent` is here :point_right: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/DynamicComponent.cs

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS , @danroth27 what do you guys think?

**Comment by SteveSandersonMS** [comment]
I’m not really seeing the problem. DynamicComponent is for introducing some other component dynamically, so its name seems very reasonable to me.

The phrasing “DynamicComponent component” sounds absolutely fine too since it’s a component that introduces another component. If you had a bag of bags, you’d be well justified in calling it a “bag bag”. The repetition of word reflects the way the concepts are composed in usage.

**Comment by SteveSandersonMS** [comment]
Also the word “dynamic” on its own has a pre-existing and unrelated meaning as a C# keyword.
