### ISSUE TITLE
EventCallback closures lead to increased diff size and decreased Blazor performance.

### ISSUE THREAD

**Issue by jspuij** [dotnet/aspnetcore#31755]
### Describe the bug

When using lambdas that capture variables as event callbacks in Blazor components, the diffs will contain new event handler ids whenever the component is rerendered. Especially in components containing loops this will lead to increasing diff sizes and decreased performance. A detailed explanation and discussion of a fix can be found on my blog.

https://spuij.nl/closures-as-callbacks-improving-blazor-performance-part-1/
https://spuij.nl/closures-as-callbacks-improving-blazor-performance-part-2/
https://spuij.nl/closures-as-callbacks-improving-blazor-performance-part-3/

This bug was previously reported as https://github.com/dotnet/aspnetcore/issues/17886, but was closed as a workaround is possible for the event callback situation. However the issue extends to Two-way-binding as well, and the closure is created by the Razor compiler here and is harder to be avoided. Since I've already devised a fix, I'll attach a PR to this issue.

### To Reproduce

Clone https://github.com/jspuij/DelegateBindingTest. Run the project. Open the developer tools of Edge. Inspect the web socket connection and the messages. Notice the increasing diff size whenever you add a row to the table. This is true for the event callback page, and the binding page.

### Exceptions (if any)

No exceptions.

### Further technical details

- ASP.NET Core version

6.0.0-preview.4.21211.7

- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21168.19
 Commit:    82e763ce49

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\source\external\AspNetCore\.dotnet\sdk\6.0.100-preview.3.21168.19\

Host (useful for support):
  Version: 6.0.0-preview.4.21211.7
  Commit:  355eff52be

.NET SDKs installed:
  5.0.100-rc.1.20379.10 [C:\source\external\AspNetCore\.dotnet\sdk]
  6.0.100-alpha.1.20523.3 [C:\source\external\AspNetCore\.dotnet\sdk]
  6.0.100-preview.3.21168.19 [C:\source\external\AspNetCore\.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-dev [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20379.2 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-alpha.1.20513.8 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-dev [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21168.5 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20371.13 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.20428.2 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.20513.9 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.20560.10 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21167.1 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21201.1 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21211.1 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21211.7 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20374.2 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20417.4 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21167.3 [C:\source\external\AspNetCore\.dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

Microsoft Visual Studio Enterprise 2019
Version 16.9.3

###

**Comment by mkArtakMSFT** [comment]
We did spend quite a bit of time discussing how this could be achieved but we couldn't come up with a reasonable solution (a good balance of simplicity and benefit) here. Hence, closing this for now. We may revisit this in the future, when we come up with some good way to support this.
