### ISSUE TITLE
Why there are two SignInResult in ASP.NET Core?

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#31762]
Why there are two `SignInResult` classes in ASP.NET Core as follows:

1. `Microsoft.AspNetCore.Identity.SignInResult` 
2. `Microsoft.AspNetCore.Mvc.SignInResult`

`Microsoft.AspNetCore.Identity.SignInResult`  is the return type of `await _signInManager.PasswordSignInAsync()` but what is the use of  `Microsoft.AspNetCore.Mvc.SignInResult`?

Thank you.

**Comment by javiercn** [comment]
@TanvirArjel thanks for contacting us.

Microsoft.AspNetCore.Mvc.SignInResult is for signing a user with a given authentication scheme (whatever that means is up to the authentication scheme in question, for example, for cookies it will emit the cookie in the response).
