### ISSUE TITLE
[Identity] Could not properly use Two Factor Authentication flow

### ISSUE THREAD

**Issue by vuthainam** [dotnet/aspnetcore#31765]
### Describe the bug
Hi everyone!
I've been using AspNetCore.Identity in my project and lately I've tried to apply **Two Factor Authentication** flow.
To be able to use **Two Factor Authentication**, I manually set **true** for **TwoFactorEnabled** property of each user.
But every time I use **SignInManager.PasswordSignInAsync** to login the user, **SignInResult.RequiresTwoFactor** is always **false**.
Not sure that I've missed any config for AspNetCore.Identity or not.

So here is the code for AspNetCore.Identity config:
`services.AddIdentity<ApplicationUser, IdentityRole>()
.AddEntityFrameworkStores<IdentityContext>()
.AddDefaultTokenProviders()
.AddTokenProvider<PhoneNumberTokenProvider<ApplicationUser>>(IdentityTokenProvider.Mobile)
.AddTokenProvider<PhoneNumberTokenProvider<ApplicationUser>>(IdentityTokenProvider.Email);`

For more information, I also use IdentityServer4 and here is the config for it:
`services.AddIdentityServer()
.AddDeveloperSigningCredential()
.AddInMemoryIdentityResources(Config.GetIdentityResources())
.AddInMemoryApiResources(Config.GetApiResources())
.AddInMemoryApiScopes(Config.GetApiScopes())
.AddAspNetIdentity<ApplicationUser>()
.AddConfigurationStore(options =>
                    {
                        options.ConfigureDbContext = builder =>
                            builder.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
                    })
                    .AddOperationalStore(options =>
                    {
                        options.ConfigureDbContext = builder => 
builder.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
                        options.EnableTokenCleanup = true;
                        options.TokenCleanupInterval = 30;
                    })
.AddProfileService<ProfileService>();`

P/S: there is a workaround that using UserManager to generate and verify 2FA Token (Code) but generated  2FA Token can be verified correctly many times until it expires. So I think this is not a safe solution to do.

### Further technical details
- ASP.NET Core version 3.1

**Comment by javiercn** [comment]
@vuthainam thanks for contacting us.

Using identity server here shouldn't matter.

**Comment by blowdart** [comment]
Exactly *what* type of mfa are you trying to use here? We're aware of email tokens being multiple user, that's not going to change. It's exactly the same with TOTP codes, they're all time limited, not one shot.

**Comment by abryzgin** [comment]
Hallo! After upgrading the project from core 3.1 to core 5, SignInManager.PasswordSignInAsync after successful authentication always returns false to the RequiresTwoFactor property, although the TwoFactorEnabled field in the database is true, EmailConfirmed - true. The only exception is the first authentication after registering a new user. During the first authentication after registering a new user, RequiresTwoFactor is still true and the system sends the code, but the second and subsequent times are always false.
