### ISSUE TITLE
Invalid RZ Diagnostic Location

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#31783]
Not sure if this falls under tooling or runtime so tagged both for now.

![image](https://user-images.githubusercontent.com/14852843/114629904-456c6780-9c6e-11eb-89dd-c7eb597b5da2.png)

The columns (ex. column 1131 for the first diagnostic) are non-existent..

Repro:
1. Build the [E2E tests](https://github.com/dotnet/aspnetcore/blob/686da2e6c5b62570a7750bc3d85179ee5e9e75fd/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj) project
2. Get RZ9991 errors with invalid `Column` numbers (note you'll have to right click on the header to see the column numbers)
3. Clicking on the diagnostic takes you to the *far* right of the page beyond any characters.

**Comment by TanayParikh** [comment]
Note; errors are due to: https://github.com/dotnet/aspnetcore/issues/31023

**Comment by captainsafia** [comment]
The diagnostics are coming from the generated source files, not the user's source files, which is likely why the column numbers are off.

This brings up a general inquiry I've had about how build errors get displayed to the users. Now that generated files are not emitted by default, it is difficult for the user to be able to open a file and see where the exception is coming from.

It might be helpful to figure out how to map the diagnostics in the generated source to the appropriate lines in the original source files.

**Comment by benaadams** [comment]
Might be resolved by https://github.com/dotnet/sdk/pull/17204
