### ISSUE TITLE
Bring back Random.Shared API once new SDK is picked up

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#31782]
Noticed this while looking at why the blazor template tests are 100% failing now in the quarantined runs:

Related to this PR: https://github.com/dotnet/aspnetcore/pull/31453/files

https://dev.azure.com/dnceng/public/_test/analytics?definitionId=869&contextType=build

```
C:\h\w\BABC09DD\w\A5850946\e\Templates\BaseFolder\AspNet.klo4c0qemnm\Server\Controllers\WeatherForecastController.cs(35,39): error CS0117: 'Random' does not contain a definition for 'Shared' [C:\h\w\BABC09DD\w\A5850946\e\Templates\BaseFolder\AspNet.klo4c0qemnm\Server\AspNet.klo4c0qemnm.Server.csproj]
C:\h\w\BABC09DD\w\A5850946\e\Templates\BaseFolder\AspNet.klo4c0qemnm\Server\Controllers\WeatherForecastController.cs(36,44): error CS0117: 'Random' does not contain a definition for 'Shared' [C:\h\w\BABC09DD\w\A5850946\e\Templates\BaseFolder\AspNet.klo4c0qemnm\Server\AspNet.klo4c0qemnm.Server.csproj]
```

**Comment by javiercn** [comment]
@HaoK good catch.

I ran into this last week too, I thought it was because we were missing an updated SDK on the repo. I expect these to go away once we update the SDK in our repo

**Comment by davidfowl** [comment]
When will that happen?

**Comment by javiercn** [comment]
@davidfowl My understanding is before we ship preview4, otherwise we need to back this change out on Friday.

**Comment by davidfowl** [comment]
Are the tests being skipped? Do we know when the update is coming? In general we shouldn't merge these until the dependency PR flows in.

**Comment by javiercn** [comment]
@davidfowl agree.

This was originally a community contribution. We rely on CTI tests for the SPA templates and the Blazor tests are quarantined at the moment while we work on improving their reliability

**Comment by javiercn** [comment]
@davidfowl here is a PR to revert the commit https://github.com/dotnet/aspnetcore/pull/31795
