### ISSUE TITLE
net 6 preview 3 web app 404 can not find routes

### ISSUE THREAD

**Issue by ByronAP** [dotnet/aspnetcore#31788]
### Describe the bug
Asp .net web application in 6 preview 3 can not find routes returns 404. It looks like this may be related to #31578 

### To Reproduce
Create a new web application in visual studio, select framework 6.
Run the app and you will be greeted with a 404.

### Exceptions (if any)
No exceptions are logged

### Further technical details
- ASP.NET Core version 6 preview 3
- 
> .NET SDK (reflecting any global.json):
>  Version:   6.0.100-preview.3.21202.5
>  Commit:    aee38a6dd4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\
> 
> Host (useful for support):
>   Version: 6.0.0-preview.3.21201.4
>   Commit:  236cb21e3c
> 
> .NET SDKs installed:
>   5.0.202 [C:\Program Files\dotnet\sdk]
>   6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- VS 16.9.4

**Comment by javiercn** [comment]
@ByronAP thanks for contacting us.

I'm not able to reproduce this issue with the latest nightly build. I did `dotnet new webapp -o sampleapp` and everything seems to be in working order. This either doesn't repro or was fixed between preview3 or preview4.

We suggest you try the nightly builds or wait until preview4 to check if you still have this issue. Alternatively it would help if you can provide us with exact details on how you created and ran the application for us to try and reproduce it again.

**Comment by ByronAP** [comment]
Created a repo here https://github.com/ByronAP/aspnetcore-31788 

Load with VS 2019 run as debug WebApplication1

**Comment by pranavkm** [comment]
@ByronAP I tried your app in VS, and it appears to work just fine. Is it possible that the issue you're seeing is specific to your machine?

**Comment by ByronAP** [comment]
Closing since it seems to not be reproduceable, Will come back on it when/if I find out the cause.

**Comment by ByronAP** [comment]
found something 

> An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\Program Files\dotnet\sdk\6.0.100-preview.4.21214.14\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by pranavkm** [comment]
FYI @captainsafia
