### ISSUE TITLE
[Kestrel] Dispose certificate or certificate private key after TLS Handshake

### ISSUE THREAD

**Issue by paulorego** [dotnet/aspnetcore#31785]
Hi,

Is there way to dispose certificate or certificate private key after TLS Handshake ?

I tried in HttpsConnectionAdapterOptions.OnAuthenticate, but not success.

Help me please!

Thanks !!!

**Comment by Tratcher** [comment]
Can you clarify why? 

In most configurations the same certificate will be used for every new connection, if it were disposed nobody else would be able to connect.

**Comment by paulorego** [comment]
In the world of cryptography it is common to remove the private key from memory after use.
So it would be for security reasons.
The idea is to instantiate the certificate dynamically, using ServerCertificateSelector,  and after the handshake process removes it.

**Comment by Tratcher** [comment]
Cc @blowdart 

In theory you could dig the SslStream out of the feature collection and dispose it's LocalCertificate. Deciding when to do that would be one problem. I also don't know that disposing it would be enough, it would remain a rooted object.

Since connection turnover is continuous in most applications, you would end up with the cert in memory most of the time regardless.

Have you considered using HttpSys instead? It does Tls in kernel mode and never loads the keys into the app.

**Comment by blowdart** [comment]
Loading it on every request would bottleneck absolutely everything. The certificate is needed as long as a connection is open, or something is listening. So yes, while you remove private keys after use, if you're using _HTTPS_ on a server, it's always in use.

**Comment by paulorego** [comment]
> Cc @blowdart
> 
> In theory you could dig the SslStream out of the feature collection and dispose it's LocalCertificate. Deciding when to do that would be one problem. I also don't know that disposing it would be enough, it would remain a rooted object.
> 
> Since connection turnover is continuous in most applications, you would end up with the cert in memory most of the time regardless.
> 
> Have you considered using HttpSys instead? It does Tls in kernel mode and never loads the keys into the app.

HttpSys is not an option because it is not cross-platform.

**Comment by blowdart** [comment]
If your concern is about it being in process, and the potential of it leaking through some weird confluence of errors, then a forwarding proxy which terminates HTTPS is the standard way to go here.

**Comment by LucasMonari** [comment]
@Tratcher, the idea is to limit the private key exposure.
[OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html#key-compromise-and-recovery) recommends "Limiting the amount of time a symmetric or private key is in plaintext form."

@blowdart, the certificate and respective private key should be used just on TLS handshake, so, it will delay just the first request of each connection. Isn't it?
> Loading it on every request would bottleneck absolutely everything.

@blowdart, how to protect the webserver from unauthenticated requests using a forwarding proxy? We are using mutual tls in Kestrel. Using an in-process solution we ensure that just the app has access to the private key and the certificate. 
> If your concern is about it being in process, and the potential of it leaking through some weird confluence of errors, then a forwarding proxy which terminates HTTPS is the standard way to go here.

**Comment by blowdart** [comment]
I'm honestly unaware of any web server that dynamically loads and unloads the certificate in memory. Unfortunately Linux doesn't provide for isolation of certificates, this is something Windows does better by keeping private keys in the kernel. The private key would also have to be loaded when the symmetric key gets renegotiated too. It's unrealistic for us to do, kestrel just isn't architected that way.

**Comment by davidfowl** [comment]
+1 to what @blowdart said. This isn't realistic for us to do.

**Comment by paulorego** [comment]
Thanks!
