### ISSUE TITLE
Update AspNetCore to use MetadataUpdateHandlerAttribute to clear caches

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31806]
* [ ] Blazor re-rendering
* [ ] Blazor Routing
* [ ] ASP.NET Core's routing

The last two bits are currently blocked since they're treated as rude edits

**Comment by davidfowl** [comment]
I assume for routing we can trigger a change token and be done

**Comment by pranavkm** [comment]
Yup that's the plan. Routing is still a bit busted because changing custom attributes is currently treated as rude edit, but that is expected to be allowed soon-ish.

**Comment by pranavkm** [comment]
This is done. There's some additional cache clearing we need to do  as part of the reloadable type effort, but that is being tracked separately.
