### ISSUE TITLE
Health checks: Authorization

### ISSUE THREAD

**Issue by dasMulli** [dotnet/aspnetcore#31803]
Health checks are currently unauthorized by default (possibly leaking internal system details) and configuration for running only health checks on a specific port is complicated (https://github.com/dotnet/aspnetcore/issues/6677).

It should be possible to use `endpoints.MapHealthChecks(...)` along with an authorization specification, e.g. requiring an authorization policy name.

This would enable scenarios (/ make them easier to configure) where a central health check service can query the health checks of multiple services by using its service identity (e.g. OIDC client credentials flow)

**Comment by javiercn** [comment]
@dasMulli thanks for contacting us.

You should already be able to add authorization to your healthchecks by calling `endpoints.MapHealthChecks(...).RequireAuthorization("Policy")`

Also, healthcheck info is not considered a secret, however if you want to treat them as such, you can use the code above to secure them.

**Comment by dasMulli** [comment]
Ah, i missed that. Thanks!
