### ISSUE TITLE
Blazor webassembly IIS 10 Net Core hosted routing working not correctly

### ISSUE THREAD

**Issue by aarrtturas** [dotnet/aspnetcore#31802]
Blazor webassembly IIS 10 Net Core hosted routing working not correctly endpoints.MapFallbackToFile("index.html") should have the lowest routing priority, but this is not the case of IIS 10 hosting. 
Running from VS in 'IIS Express' it works correctly as should. 

### To Reproduce
1. Create in VS Blazor webassebly Net core hosted App (see image in VS for details). Create any controller with any method. Create link in your app linking to controller like "a href='api/home/index'". Try to run from VS in 'IIS Express'. It will work correctly - controller method will be reached. This is ok.
2. Host app in IIS 10. 
3. Load your app. Hit you link in app pointing to controller method. Blazor UI will tell - "no page found". Routing works not correctly on IIS. In different way it works in IIS Express mode. 
**It worked well in older Blazor webassembly  versions on IIS 10 hosting. No problems was. See the last one image for tech details**

Startup.cs Configure suggestions from stackoverflow.com I have tried and not working:

This not helping, it just ignores this on IIS 10 hosting, but on IIS Express from VS it works fine:

        endpoints.MapFallbackToFile("{*path:regex(^(?!api).*$)}", "index.html");

This not helping as well on IIS 10:
        
        endpoints.MapGet("api/{**slug}", HandleApiFallback);

        private Task HandleApiFallback(HttpContext context)
        {
            context.Response.StatusCode = StatusCodes.Status404NotFound;
            return Task.CompletedTask;
        }

Any way you host MapFallbackToFile  must have the lowest routing priority, but this is not the case on IIS 10.

- ASP.NET 5 the last one
- Blazor webassembly 
- IIS 10

Link to minimal repro:
https://github.com/aarrtturas/BlazorWebAssemblyIIS10RoutingIssue.git

**Comment by aarrtturas** [comment]
![2021-04-14 17_31_27-Microsoft Visual Studio](https://user-images.githubusercontent.com/41419745/114727971-54731880-9d47-11eb-9ef9-430dcfe575b1.png)
![2021-04-14 17_20_25-Chalange - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/41419745/114726165-cd717080-9d45-11eb-96bd-a94cc86017ee.png)
![2021-04-14 17_19_32-About Internet Information Services (IIS) Manager](https://user-images.githubusercontent.com/41419745/114726152-c8acbc80-9d45-11eb-88f5-1833f8b3a2c7.png)

**Comment by captainsafia** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by aarrtturas** [comment]
Adding minimal repro from Visual studio Blazor Webassembly template

https://github.com/aarrtturas/BlazorWebAssemblyIIS10RoutingIssue.git

**Comment by mkArtakMSFT** [comment]
@aarrtturas when you refer to `older blazor version` what specific version was that?

**Comment by aarrtturas** [comment]
It was refered to:
        <AspNetCoreVersion>3.1.6</AspNetCoreVersion>
        <RazorLangVersion>3.0</RazorLangVersion>
        <BlazorVersion>3.1.0-preview4.19579.2</BlazorVersion>

**Comment by aarrtturas** [comment]
Solution to this issue:

Edit wwwroot\service-worker.published.js file.
Add exclusions. In my case '/api/', '/signin-google', '/signin-facebook'.
Very unexpected place to add exlusions. Javascript is not a prefered way to do things with Blazor.

        // For all navigation requests, try to serve index.html from cache
        // If you need some URLs to be server-rendered, edit the following check to exclude those URLs
        const shouldServeIndexHtml = event.request.mode === 'navigate' &&
                                     !event.request.url.includes('/api/') &&
                                     !event.request.url.includes('/signin-google');
                                     !event.request.url.includes('/signin-facebook');

Tested and working finaly!
