### ISSUE TITLE
Inconsistent Razor (cshtml) coloring

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#31805]
A tracking issue for https://github.com/OmniSharp/omnisharp-vscode/issues/4282.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg does this repro in VS? I would have figured our semantic colorization would have solved this.

**Comment by ryanbrandenburg** [comment]
This does not repro in VS, C# semantic colorization paper's over the TextMate mistakes.

**Comment by ryanbrandenburg** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/26479.
