### ISSUE TITLE
HubConnection failed to start successfully because of error 'SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by neobgd** [dotnet/aspnetcore#31819]
### Describe the bug
Unable to connect from Angular 11 application and NET5 Web Api.
We use "@microsoft/signalr": "^5.0.5" library

### Exceptions (if any)

[2021-04-14T23:40:14.466Z] Debug: Starting HubConnection.
[2021-04-14T23:40:14.474Z] Debug: Starting connection with transfer format 'Text'. 
[2021-04-14T23:40:14.475Z] Debug: Sending negotiation request: https://localhost:44346/apphub/negotiate?access_token=Nv8Bhi…xzq35y2W9VlLVq7RrQCK7LATMC3xLj4It_Q4ftPsg&negotiateVersion=1
[2021-04-14T23:40:14.628Z] Error: Failed to complete negotiation with the server: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 
[2021-04-14T23:40:14.630Z] Error: Failed to start the connection: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 
[2021-04-14T23:40:14.632Z] Debug: HubConnection failed to start successfully because of error 'SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data'. 
Error while starting connection: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS Code 1.55

**Comment by BrennanConroy** [comment]
Can you capture a network trace?

Also, verify that https://localhost:44346/apphub is your hubs endpoint.

**Comment by neobgd** [comment]
Hello,
we use that endpoint.
endpoints.MapHub<AppHub>("/apphub");

Do you want har file?

**Comment by neobgd** [comment]
We found solution, it was custom Auth attribute, in one case did not return proper response.
Sorry for inconvenience.
