### ISSUE TITLE
How to hot reload when use Blazor WebAssembly

### ISSUE THREAD

**Issue by BruceQiu1996** [dotnet/aspnetcore#31829]
Hi,i use blazor webassembly last week to develop a web project for my company.
but When i modify some text on razor page,i remember i can Ctrl+S and reload page to display new page on asp.net mvc or asp.net core mvc.
So How can I achieve such an effect on blazor webassembly.

**Comment by javiercn** [comment]
@BruceQiu1996 thanks for contacting us.

Hot reload for webassembly is currently a 6.0 preview3 feature. Check https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/#initial-net-hot-reload-support for details
