### ISSUE TITLE
Remove unsafe string mutation code from repo

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/aspnetcore#31821]
Strings in .NET are immutable, and we want to experiment with runtime features (deduplication, codegen optimizations, etc.) which rely on this fact. To accomplish this we'll need to start moving away from existing code which mutates string instances in-place. Here's a first-pass at all the places in this repo which mutate strings and recommended workarounds for them.

https://github.com/dotnet/aspnetcore/blob/8f564897f68944d5f9bf9bded45160fcf3fb0329/src/Shared/ServerInfrastructure/StringUtilities.cs#L73-L94

(Similar code [here](https://github.com/dotnet/aspnetcore/blob/28a0a5348d3dc3ba49db8955d4c60a5ad3d58da0/src/Shared/Http2cat/Http2Utilities.cs#L158) and [here](https://github.com/dotnet/aspnetcore/blob/28a0a5348d3dc3ba49db8955d4c60a5ad3d58da0/src/Shared/Http2cat/Http2Utilities.cs#L180).)

Suggested workaround (pseudocode):

```cs
fixed (byte* pBytes = bytes)
{
    return string.Create(bytes.Length, (IntPtr)pBytes, (span, ptr) =>
    {
        fixed (char* pChars = span)
        {
            WidenAndCopy((byte*)ptr, pChars, span.Length);
        }
    });
}
```

https://github.com/dotnet/aspnetcore/blob/28a0a5348d3dc3ba49db8955d4c60a5ad3d58da0/src/DataProtection/Cryptography.Internal/src/SafeHandles/BCryptAlgorithmHandle.cs#L78-L84

Suggested workaround: Write to a stackalloced buffer, or rent a char array and write to that, then turn it into a string. Or use `string.Create` and avoid the intermediate rentals.

**Comment by gfoidl** [comment]
I'd like to have look into this.

**Comment by BrennanConroy** [comment]
While we're looking into fixing these we should keep https://github.com/dotnet/aspnetcore/issues/4720 in mind. I.e. Try to remove `unsafe`.

**Comment by gfoidl** [comment]
It's on my radar. Thanks.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/31850
