### ISSUE TITLE
Latest version of Microsoft.AspNetCore.Http should update dependency System.Text.Encodings.Web to 4.5.1

### ISSUE THREAD

**Issue by SLdragon** [dotnet/aspnetcore#31826]
According to component detection in Azure pipeline, there is a security alert of the library Microsoft.AspNetCore.Http 2.2.2 which refer System.Text.Encodings.Web 4.5.0 should be updated to 4.5.1.

**Comment by BrennanConroy** [comment]
2.2 has been out of support since Dec 23, 2019
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by SLdragon** [comment]
Any new version can we use for this library: Microsoft.AspNetCore.Http?
I found the latest version is 2.2.2, there is no new version for it?

**Comment by BrennanConroy** [comment]
It's part of the ASP.NET Core Runtime now, so there isn't any standalone package for it. You get it for free when using ASP.NET Core.

**Comment by SLdragon** [comment]
How can I get and use this library? Is it using a new namespace?
I am using net core 3.1, if I remove this "Microsoft.AspNetCore.Http" nuget dependency, it will show errors:
![image](https://user-images.githubusercontent.com/5545529/114838669-8350c380-9e07-11eb-849d-8d05b3f805b8.png)
![image](https://user-images.githubusercontent.com/5545529/114838706-8d72c200-9e07-11eb-9be8-16de191b2715.png)

**Comment by blowdart** [comment]
Can you post your csproj file so we can ensure you're not mixing versions of anything? The namespace has not changed

**Comment by BrennanConroy** [comment]
Are you making a class library?
If so, you need to add a reference to the shared framework
https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

**Comment by SLdragon** [comment]
Hi, @blowdart , this is our csproj file, and it is a class library:

```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Microsoft.Azure.WebJobs.Extensions.TeamsFx</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.TeamsFx</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.1.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JWT" Version="7.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.22" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.22.0" />
  </ItemGroup>

</Project>


```

**Comment by blowdart** [comment]
It's a false positive. 

3.1 includes it in the runtime so if the runtime is updated you're good, you don't need to do anything.

We're seeing a lot of scanning getting this wrong because they don't realise it went "inbox" in 3x

**Comment by blowdart** [comment]
Wait I take this back. 

You're targeting .netcoreapp3.1 but you're including Microsoft.AspNetCore.Http 2,x? That's wrong.

The migration guide for .net core 3.0 explained [you must use a framework reference and remove the old packages](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference).

**Comment by SLdragon** [comment]
OK, thank you very much for the guidance, I will take a look!

**Comment by blowdart** [comment]
Please let us know how it goes
