### ISSUE TITLE
Intellisense breaking in Razor pages with hyphen in folder name

### ISSUE THREAD

**Issue by maxscan** [dotnet/aspnetcore#31839]
When using Visual Studio 16.9.4 (and for at least a couple months before this release) VS Intellisense breaks if a Razor page is in a folder with a hyphen in the name. For example:

I have a page in a folder as follows: /Pages/Admin/Client-Accounts/Edit.cshtml

In this page the @Model is not recognised - VS says: Cannot resolve symbol 'Model'

If I rename the folder to change the path to: /Pages/Admin/ClientAccounts/Edit.cshtml (ie remove hyphen in Client-Accounts) then Intellisense works fine.

There are no issues with Tag Helpers, it's only when using @Model directly.

The project builds ok and the page does work fine when served via IIS but shows errors when editing and Intellisense for properties etc. is broken.

This is very similar to an old, fixed, bug here: https://github.com/aspnet/Mvc/issues/6296 - although this applied to filenames only I think - but thought I'd mention in case the solution used there helps...

**Comment by NTaylorMullen** [comment]
If this is broken in the old editor as well then no-op and put back to triage

**Comment by ryanbrandenburg** [comment]
@maxscan I'm not seeing any `Cannot resolve symbol` errors when trying to use VS the way you describe. It's possible we fixed this in 16.10, could you see if it still repro's for you in [16.10-preview2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview)? If it still repros in the preview I've probably misunderstood what you're describing, could you include a snippet of the text on your page and maybe a screenshot of the page while it's errored?
