### ISSUE TITLE
Is that any like IControllerModelConvention in Signalr core?

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/aspnetcore#31836]
I want to change the hub's AuthorizeAttribute.AuthenticationSchemes in runtime,because it only can get scheme from the configuration,  is that any way to use something like IControllerModelConvention ?

**Comment by davidfowl** [comment]
No and that's on purpose 😄. Mvc has lots of overhead for extensibility like this. That overhead isn't carried into signalr.

**Comment by BrennanConroy** [comment]
There is a ForwardedScheme feature that you might be able to use here. You could also write a custom auth scheme that you then configure the middleware at runtime/config time.
