### ISSUE TITLE
JS event capture

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#31830]
Blazor WASM .Net 5 SDK 5.0.201

I have this js method to get keyboard events globally:

```js
window.addEventListener('keyup', function (e) {
    if (DataGridDotNetReference !== null) {
        DataGridDotNetReference.invokeMethodAsync('HandleKeyUp', e);
    }
});
```
and this one in my Blazor component
```csharp
[JSInvokable]
public void HandleKeyUp(KeyboardEventArgs e)
{
    Console.WriteLine($"HandleKeyUp {e} / {e.Key} / {e.Code} / {e.Type}");
}
```
console output is:
```
HandleKeyUp Microsoft.AspNetCore.Components.Web.KeyboardEventArgs /  /  / 
```

Why the event is "empty " ?

**Comment by JulienM28** [comment]
I found a workaround:

```js
window.addEventListener('keyup', function (e) {
    if (DataGridDotNetReference !== null) {
        DataGridDotNetReference.invokeMethodAsync('HandleKeyUp', serializeKeyboardEvent(e));
    }
});

var serializeKeyboardEvent = function (e) {
    if (e) {
        let o = {
            AltKey: e.altKey,
            Code: e.code,
            CtrlKey: e.ctrlKey,
            Key: e.key,
            Location: e.location,
            MetaKey: e.metaKey,
            Repeat: e.repeat,
            ShiftKey: e.shiftKey,
            Type: e.type
        };
        return o;
    }
};
```

but it could be nice to get javascript events sent to blazor without this kind of trick.

Thanks.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

What you are seeing is by design. We have specialized code for handling and dispatching events to the server. Since you are using JS interop none of our mappings apply. In 6.0 you might be able to leverage custom event arguments. See [here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/#support-for-custom-event-arguments-in-blazor) for details

**Comment by JulienM28** [comment]
I already use EventHandler decorator for weeks for mouse events not supported by Blazor with .Net 5.

I'll try this. Thanks.

Also, is thera a way to do equivalent of window.addEventListener() in Blazor ?

**Comment by javiercn** [comment]
@JulienM28 we don't offer anything out of the box
