### ISSUE TITLE
Use TaskToApm everywhere

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31842]
We should be using TaskToApm on all streams for the BeginWrite, EndWrite, BeginRead, and EndRead apis. A few places where we don't:
- https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs
- https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/HttpSys/src/ResponseStream.cs#L77
- https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Middleware/ResponseCaching/src/Streams/ResponseCachingStream.cs#L184
- https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Middleware/ResponseCaching/src/Streams/SegmentWriteStream.cs#L194

As an example: https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs#L525

**Comment by davidfowl** [comment]
cc @gfoidl this feels like a change you would make 😊

**Comment by gfoidl** [comment]
You have a good feeling 😃 
(will do later today / tomorrow)
