### ISSUE TITLE
Add W3C logging to HttpLogging middleware

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31843]
We want to extend the HttpLogging Middleware to include W3C logs. 

Hazy details:

- Logging Provider
- Logging inside of the middleware to a different logger
- Making sure format is consistent (no extra fields per request/response)

@shirhatti can you help with specific details here?

**Comment by blowdart** [comment]
The spec - https://www.w3.org/TR/WD-logfile.html

The fields IIS could log are at https://www.loganalyzer.net/log-analyzer/w3c-extended.html. You don't have to include all of them (win32status for example)
