### ISSUE TITLE
ASP.NET Core SignalR Java client

### ISSUE THREAD

**Issue by 296370493** [dotnet/aspnetcore#31860]
### Describe the bug
After calling start() and stop() multiple times using HubConnection, through "cat proc/{pid}/status | grep Threads" on the client (Android phone), we can see that the number of threads will continue to increase. 

Why are start() and stop() called multiple times? Because you need to reconnect after disconnecting.

### To Reproduce
`HubConnection hubConnection = HubConnectionBuilder.create("YOUR HUB URL HERE")
                        .shouldSkipNegotiate(true)
                        .withTransport(TransportEnum.WEBSOCKETS)
                        .build();
                // Simulate multiple disconnection and reconnection
                for (int i = 0; i < 30; i++){
                    hubConnection.start().blockingAwait();
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    hubConnection.stop().blockingAwait();

                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }`

### Exceptions (if any)
Through "cat proc/{pid}/status | grep Threads" on the client (Android phone), we can see that the number of threads will continue to increase. 

### Further technical details
Server(CentOS 7.9 64bit): ASP.NET Core-3.1.13
Client(Android application): ASP.NET Core SignalR Client for Java applications-3.1.13
Android phone：Android 7.1.1

- Include the output of `dotnet --info`
Host (useful for support):
  Version: 3.1.13
  Commit:  64df28ec4a

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Android Studio 4.1.13

**Comment by BrennanConroy** [comment]
You should try with the 5.0.x java client.

**Comment by 296370493** [comment]
> You should try with the 5.0.x java client.

It is no problem to use the 5.0.x version test
