### ISSUE TITLE
EditForm Causing Layout Corruptions

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#31876]
I have some code here that works if there is no editform.
```
<div style="height: 100%; display: grid; grid-row-gap: 5px; grid-template-rows: auto 1fr auto">
        <div>
            Top
        </div>
        <div>
            Middle
        </div>
        <div>
            Bottom
        </div>
    </div>
```

However, if I use editform, then the bottom div does not show up on the bottom.  Here is the code to show it happening.
```
<SubmitForm Model="_model" OnValidSubmit="SaveAsync">
    <div style="height: 100%; display: grid; grid-row-gap: 5px; grid-template-rows: auto 1fr auto">
        <div>
            Top
        </div>
        <div>
            Middle
        </div>
        <div>
            Bottom
        </div>
    </div>
</SubmitForm>
```

I do know if I set height at 100vh, then its okay.  the problem is this could be a sub page.
An example is a person may have a top bar that shows up on all pages.  Then you have content.  However, within the content, its very common to need something that fills available area.  Does not seem to work with submitform though.   Would like to know what the workaround is in this case.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

`SubmitForm` is not a component that we ship. Can you reproduce this issue with a standard `EditForm` component?

**Comment by musictopia2** [comment]
I meant the problem happens with editform.  I was able to reproduce with editform.  Just change to EditForm and same issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
