### ISSUE TITLE
<InputFile> upload progress

### ISSUE THREAD

**Issue by DouglasRiddle** [dotnet/aspnetcore#31875]
### Describe the solution you'd like
I am working on migrating from [Steve Sanderson's BlazorInputFile](https://github.com/SteveSandersonMS/BlazorInputFile) but am having difficulty getting upload progress working with .NET 5.0 ```<InputFile>```. Can you all add a working example to the [File Uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0) documentation page?

**Comment by pranavkm** [comment]
There's a sample available here: https://github.com/pranavkm/FileUpload/blob/master/Pages/Index.razor. You could consider contributing to the documentation using that.

**Comment by DouglasRiddle** [comment]
I had found that code in a [previous version of the file upload documentation page](https://github.com/dotnet/AspNetCore.Docs/pull/20046/commits/0eb3f5b2c3d7f95a37ebd30137477b47ce451b9f) but have not been able to get it to work similarly to @SteveSandersonMS's prototype code.
