### ISSUE TITLE
C# error squiggles are so small they are invisible 

### ISSUE THREAD

**Issue by bemokraig** [dotnet/aspnetcore#31885]
On a busy page, forgetting a semicolon or other error results in a very tiny squiggle on one line.  May as well be invisible if your vision is not 2020.  I would consider this a bug for the visually impaired.  Looks like dirt on the screen.

At least have an option for errors to be larger, a symbol that stands out more, highlight the line in red something, anything.

**Comment by javiercn** [comment]
@bemokraig thanks for contacting us.

Is this related to errors within razor pages or about errors in c# files in general.

**Comment by NTaylorMullen** [comment]
@bemokraig Really appreciate your feedback! Has using the `Error List` when filtered to the current document helped you at all?

Also, to gain more traction here it'd be best to use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
