### ISSUE TITLE
Problem when using Microsoft.AspNetCore.Identity.UI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31889]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-when-using-MicrosoftAspNetCore/1396314)._

---
[severity:Other]
I created two versions of Blazor Server 5.0 one with authentication , one without.  I then proceeded to manually update the one without to the configuration of the one with.  In Startup.cs I could not get rid of red squigley under  services. AddDefaultIdentity<IdentityUser>   of the following:

services. AddDefaultIdentity<IdentityUser>(options => options. SignIn.RequireConfirmedAccount = true)
                . AddEntityFrameworkStores<ApplicationDbContext>();
  
I traced the problem to the 6.0.0 version of Microsoft.AspNetCore.Identity.UI   once I replaced it with 5. 0.4 the problem disappeared.

---
#### Feedback Bot on 4/12/2021, 07:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
Yes, you're mixing up versions. 6.x will work alongside .NET 6.0. 5.x needs 5.x packages. This is to be expected.
