### ISSUE TITLE
There are cases where &nbsp; cannot be used with Brazor Server Application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31891]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/There-are-cases-where-nbsp;-cannot-be-u/1389730)._

---
[severity:It's more difficult to complete my work]
In the .razor file of Brazor Server Application, if & nbsp; is described in @if, a build error will occur.
Brazor Server Application の .razor file で、@if 内に &nbsp; を記述するとビルドエラーになる。

---
#### Feedback Bot on 4/6/2021, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Because inside the `@if` block you're within a C# context, `&nbsp` isn't recognized there hence the error. To switch context to markup, you'll have to wrap the content in a `<text>` bock or some other tag.
