### ISSUE TITLE
Angular 11.0.4 & .Net 5.0 Giving TimeoutException Exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31890]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Angular-1104--Net-50-Giving-Timeout/1393855)._

---
[severity:It's more difficult to complete my work]
Steps

1. Created angular Project in Visual Studio 2019. 
2. Picked up .Net 5.0 while creating the project. 
3. Upgraded Angular version to 11.0.4 from default 8.2.12.  

Getting Error

TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.

Exception stack trace

System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0. <<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

What all things I tried

1.  Increased timeout in Startup.cs
2. Set progress flag to true in agular.json
3. Tried echo in ng serve command
4. Tried --aot and --prod flags in ng build
5. Upgraded global version of Angular to 11.0.4
6. Removed externally installed node.js
7. Setup environment variable to point node.js and ng path from the visual studio environment.

I am using the latest Visual Studio 

**Microsoft Visual Studio Professional 2019
Version 16.9.3**

---
#### Feedback Bot on 4/8/2021, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Amit Shinde on 4/9/2021, 11:57 AM: 

<p>Whenever I run the project it creates a few node.js processes. Visual studio does not kill these processes automatically when the project is stopped. These processes eat up a lot of memory.</p>
<p><img src="https://aka.ms/dc/image?name=B0e4c30264a0e4c1e91eaf7c21d7ccc33637535914254595180_20210410-002704-image.png&amp;tid=0e4c30264a0e4c1e91eaf7c21d7ccc33637535914254595180" alt="image.png"></p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Does the angular development proxy start if you navigate to the `ClientApp` folder and run `npm run start`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've recently updated the template to use Angular 12. Please try the new templates and file a new issue, if you still face any issues.
