### ISSUE TITLE
Hot reload is flaky: after 3-5 saves it falls back to rebuild and refresh of the browser, also the performance of when hot reload does work is inconsistent even when making only 1 character change at a time.

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#31901]
### Describe the bug
Hot reload is flaky after 3-5 saves it falls back to rebuild and refresh of the browser, also the performance of when hot reload does work is inconsistent even when making only 1 character change at a time.

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new blazorwasm app
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Hit CTRL+S multiple times in a row or even just keep pressing CTRL+S
- The first few times hot reload works and then falls back to rebuilding and refreshing the browser

![image](https://user-images.githubusercontent.com/18366446/115100213-72cc4600-9ef8-11eb-8b52-052e7181e7c8.png)

### Further technical details
- ASP.NET Core version: 6.0.100-preview.3.21202.5
- Include the output of `dotnet --info`
    .NET SDK (reflecting any global.json):
     Version:   6.0.100-preview.3.21202.5
     Commit:    aee38a6dd4
    
    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  20.04
     OS Platform: Linux
     RID:         ubuntu.20.04-x64
     Base Path:   /home/user/dotnet/sdk/6.0.100-preview.3.21202.5/
    
    Host (useful for support):
      Version: 6.0.0-preview.3.21201.4
      Commit:  236cb21e3c
    
    .NET SDKs installed:
      6.0.100-preview.3.21202.5 [/home/user/dotnet/sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/home/user/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/home/user/dotnet/shared/Microsoft.NETCore.App]
    
    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download

- The IDE: VS Code
![image](https://user-images.githubusercontent.com/18366446/115100067-68f61300-9ef7-11eb-883a-d7041772cab4.png)

**Comment by ahmedalejo** [comment]
It´s natural to see improvements over time. one thing that bothers me is that when tooling is starting to become very reliable, the technology tends to be considered obsolete by then.

Just take a look at what we have with [Live Preview](https://devblogs.microsoft.com/aspnet/introducing-web-live-preview/) JUNE 2021 for Razor pages and Web Forms after years of existence.
![image](https://user-images.githubusercontent.com/7012074/115971406-ade4ff80-a51e-11eb-9f10-2d91822c2aec.png)

Hopefully NET 6 breaks the cycle.

**Comment by pranavkm** [comment]
Thanks for the issue report @MacdonaldRobinson. We made improvements to dotnet-watch and the compiler since preview3 and using the latest (preview6) builds, I no longer see issues with my WSL2 image. If you continue to see issues once updated, please feel free to file a new issue and I'd be happy to investigate further. Note that you might run in to this issue https://github.com/dotnet/aspnetcore/issues/33209 using a preview4 build.

![Watch](https://user-images.githubusercontent.com/174281/120523485-ca305380-c38a-11eb-9082-1d0b2bee1742.gif)

**Comment by MacdonaldRobinson** [comment]
Thanks allot @pranavkm !
