### ISSUE TITLE
Remove unwanted info from signalr client

### ISSUE THREAD

**Issue by avialonn** [dotnet/aspnetcore#31907]
Hi there,
Anyone know how can I remove the following info messages?
![image](https://user-images.githubusercontent.com/72415692/115118058-2ccfba80-9faa-11eb-8480-ea420b308bb8.png)
Thanks!
aa

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#error-handling-and-logging

You can use configureLogging to set the level to None.

**Comment by avialonn** [comment]
Excellent. Work like a charm! Thanks
