### ISSUE TITLE
TestServer support for WebSockets in SignalR .NET client

### ISSUE THREAD

**Issue by sergey-litvinov** [dotnet/aspnetcore#31911]
## Summary

This is a design proposal for #11888. It doesn't have `helpwanted` label but if it's not internal ticket, i would love to help with it.

## Motivation and goals

The reasoning is that WebSockets is a popular transport for SignalR and teams that are heavily depending on tests might have problems since at the moment we can't mock it. 
In our case we are trying to have custom implementation of SignalR with handshake\messages parsing that works based on the Pipelines so we can mock it with TestServer but it might be painful to support such thing in the future.

## In scope

The main use case is to add a way to override WebSocket that is used in SignalR's `WebSocketsTransport` so it can be mocked by TestServer

## Out of scope

Nothing

## Risks / unknowns

The biggest risk is that interface that is described below would be a public contract that might be not so good.
And unknown what is a better way to apply `ClientWebSocketOptions` since it can't be instantiated manually as constructor\ `WebSocketHandle` are internal

## Detailed design

From my understanding one way of fixing it might be adding factory for websockets to `HttpConnectionOptions` in the same way we have `HttpMessageHandlerFactory` for `HttpClient`
https://github.com/dotnet/aspnetcore/blob/62e157b94276bf6e607546b0a46b283f7a6a9b92/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs#L48-L52

so then we can inject there and add `TestServer.CreateWebSocketClient()`.

The main complication would be that `WebSocketsTransport` uses `ClientWebSocket` since it overrides `_webSocket.Options` by adding headers\proxy\etc, and it can't be replaced to base `WebSocket` class since it doesn't have needed property. 

Maybe as one way of fixing it, a proxy interface can be made like

```
public interface IWebSocketFactory
{
	ClientWebSocketOptions Options { get; }
	async Task<WebSocket> CreateAndConnect(Uri uri, CancellationToken cancellationToken);
}

public class DefaultWebSocketFactory: IWebSocketFactory
{
    private ClientWebSocket _clientSocket;

    public DefaultWebSocketFactory(ClientWebSocket clientSocket)
    {
        _clientSocket = clientSocket;
    }

    public ClientWebSocketOptions Options => _clientSocket.Options;

    public Task ConnectAsync(Uri uri, CancellationToken cancellationToken)
    {
        await _clientSocket.ConnectAsync(uri, cancellationToken);
        return _clientSocket;
    }
}
```

then `HttpConnectionOptions` can be updated to have 
```
        public Func<IWebSocketFactory, IWebSocketFactory>? WebSocketFactory { get; set; }
```

And then `WebSocketsTransport` would create `DefaultWebSocketFactory`, pass it to `Options.WebSocketFactory` and use result. So if developers would want to mock WebSockets for SignalR and TestServer, then something like below can be made

```
public class TestWebSocketFactory: IWebSocketFactory
{
    private WebSocketClient _testSocket;

    public TestWebSocketFactory(WebSocketClient testSocket)
    {
        _testSocket = testSocket;
    }

    public ClientWebSocketOptions Options ....

    public Task ConnectAsync(Uri uri, CancellationToken cancellationToken)
    {
         return await _testSocket.ConnectAsync(uri, cancellationToken);
    }
}
```

The thing that i'm not sure is `Options` since options doesn't have public constructor and `WebSocketHandle.CreateDefaultOptions()` is also internal. If it would have it as public, then it can be instantiated and then when `TestWebSocketFactory` creates a connection, it can use `Action<HttpRequest>? ConfigureRequest` in `WebSocketClient` to override request and add cookies\proxy\certificates\etc based on the Options object. 

i'm not sure that it's a good approach since that interface would be public contract and maybe you have another better idea, but if it's doable by external contributors and you are fine with it, i would love to help with PR.

**Comment by davidfowl** [comment]
Thanks for taking the initiative here @sergey-litvinov !

What about:

```diff
public class HttpConnectionOptions
{
+    public IWebSocketFactory? WebSocketFactory { get; set; }
}
```

```C#
public interface IWebSocketFactory
{
    ValueTask<WebSocket> ConnectAsync(Uri uri, HttpConnectionOptions options, CancellationToken cancellationToken);
}
```

The default `IWebSocketFactory` would look like this:

```C#
public class DefaultWebSocketFactory : IWebSocketFactory
{
    public async ValueTask<WebSocket> ConnectAsync(Uri uri, HttpConnectionOptions options, CancellationToken cancellationToken)
    {
        var ws = new ClientWebSocket();

       // Translate other HttpConnectionOptions 

        options.WebSocketConfiguration?.Invoke(ws.Options);

        await ws.ConnectAsync(uri, cancellationToken);

        return ws;
    }
}
```

cc @BrennanConroy @halter73

**Comment by sergey-litvinov-work** [comment]
yeah, that's a great idea! and in that way `DefaultWebSocketFactory` would do mapping based from `HttpConnectionOptions` and would set `ws.Options` directly from it. And `TestWebSocketFactory` can do the same for TestServer's `WebSocketClient` but without the need to create `ClientWebSocketOptions` instance

**Comment by sergey-litvinov** [comment]
yeah, that's a great idea! and in that way `DefaultWebSocketFactory` would do mapping based from `HttpConnectionOptions` and would set `ws.Options` directly from it. And `TestWebSocketFactory` can do the same for TestServer's `WebSocketClient` but without the need to create `ClientWebSocketOptions` instance

**Comment by BrennanConroy** [comment]
I'm going to play devil's advocate a little here: Is testing websockets with SignalR important or is testing SignalR with TestHost important?

If we added TestHost integration, via an extension method, then we wouldn't have to add any public API to the client. The extension method could set the HttpClient and LongPolling transport on the SignalR connection so websockets wont be used.
WebSockets is partially a hidden implementation detail and normally not a concern for unit tests.

----

The suggested API looks simple and easy to integrate :+1:
We can probably bring it to API review on Monday.

**Comment by davidfowl** [comment]
Good question @BrennanConroy! We'd need to make another package SignalR + TestHost since I assume we'd need an extension method that took the TestServer?

If we didn't want to expose a new abstraction we could do something like this:

```diff
public class HttpConnectionOptions
{
+    public Func<Uri, HttpConnectionOptions, CancellationToken, ValueTask<WebSocket>>? WebSocketFactory { get; set; }
}
```

**Comment by sergey-litvinov** [comment]
>If we added TestHost integration, via an extension method, then we wouldn't have to add any public API to the client. The extension method could set the HttpClient and LongPolling transport on the SignalR connection so websockets wont be used.
WebSockets is partially a hidden implementation detail and normally not a concern for unit tests.

if it would support bi-directional communication between client and TestHost even if it uses HttpClient and LongPolling internally, then it would be great as well. In our case we use bi-directional calls client <-> server and that's why we can't just mock regular HttpClient and LongPooling\ServerSideEvents

**Comment by BrennanConroy** [comment]
> if it would support bi-directional communication between client and TestHost even if it uses HttpClient and LongPolling internally, then it would be great as well.

SignalR is bi-directional, so you're covered.

I can see scenarios where people only want WebSockets with SignalR so I do think adding the websocket abstraction is valuable.

So the two proposals so far are:

```diff
public class HttpConnectionOptions
{
+    public IWebSocketFactory? WebSocketFactory { get; set; }
}

+public interface IWebSocketFactory
+{
+    ValueTask<WebSocket> ConnectAsync(Uri uri, HttpConnectionOptions options, CancellationToken cancellationToken);
+}
```

or

```diff
public class HttpConnectionOptions
{
+    public Func<Uri, HttpConnectionOptions, CancellationToken, ValueTask<WebSocket>>? WebSocketFactory { get; set; }
}
```

**Comment by BrennanConroy** [comment]
@sergey-litvinov Good news! The API at https://github.com/dotnet/aspnetcore/issues/31911#issuecomment-822611705 has been approved. Are you interested in contributing a PR for this?

**Comment by sergey-litvinov** [comment]
@BrennanConroy yay, thanks! yep, I'm still want to help with that. I see updated API design and that it has `WebSocketConnectionContext` that holds both `Uri` and `HttpConnectionOptions`, so it's a mix of two original approaches. 

it looks clear to me, so i'll work on it and create a PR with a change

**Comment by sergey-litvinov** [comment]
@BrennanConroy made a PR with the change

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/32348
