### ISSUE TITLE
How to get the remote IP address of the end user in Blazor Server App running on IIS

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#31920]
It is a standard IIS installation on a standard Windows 2016 Server running in a VM. We have access to this remote machine... When we access the web app from our local machine the IP address is not our local client IP (end user), but the standard gateway of the remote machine. But we want to retrieve our local client IP (end user), and not that of the remote machine.

Though we make no use of Kestrel, we tried to use the ForwardedHeaders middleware but to no avail . The returned IP Address is always that of the machine on which IIS has been installed.

Here's a complete repro of the code involved.

On Startup.cs, in the ConfigureServices method we added: 

      // Forwarded Headers: 
     services.Configure<ForwardedHeadersOptions>(options =>
     {
          options.ForwardedHeaders =
             ForwardedHeaders.XForwardedFor | 
            ForwardedHeaders.XForwardedProto;
    });

And in the  Configure method we added:
     `app.UseForwardedHeaders();`

The following code snippets describe how we retrieve the IP Address:

UserInfo.cs
------------

     public class UserInfo
    {
         public string UserAgent { get; set; }
         public string IPAddress { get; set; }
    }

_Host.cshtml (partial code...)
------------------------------

     @using System.Net

    @{
          string ip = HttpContext.Connection?.RemoteIpAddress.ToString();

          //127.0.0.1    localhost
         //::1          localhost
        if (ip == "::1")
       {
           ip = 
           Dns.GetHostEntry(Dns.GetHostName()).AddressList[2].ToString();
       }

       var _userInfo = new UserInfo
      {
           UserAgent = HttpContext.Request.Headers["User-Agent"],
           IPAddress = ip
   
      };
    }

   <component type="typeof(App)" render-mode="Server" param- 
                                                                                     UserInfo="@_userInfo" />

App.razor
-----------
     <p>UserAgent: @UserInfo.UserAgent</p>
     <p>IPAddress: @UserInfo.IPAddress</p>

     @* Code removed for brevity's sake*@

     @code
    {
         [Parameter]
         public UserInfo UserInfo { get; set; }
     }

Note: The issue has nothing to do with Blazor. We know its related to IIS, but our configuration is robust, and we tend to believe this is a bug...

Many thanks in advance...

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

The best way to do this is to capture the IP in `_Host.cshtml` and pass it to the Blazor server application as a parameter to the root component.

**Comment by enetstudio** [comment]
@javiercn, thanks for your response...

> The best way to do this is to capture the IP in _Host.cshtml and pass it to the Blazor server application as a parameter to the root component.

That's exactly what I'm doing. See my code above...

Once again, the issue is not how to retrieve the end user's IP Address from Blazor. This is done perfectly well. My code is identical to yours.

The issue is that I get the IP Address of the machine on which the IIS is installed, and not that of the end user...  And even adding the UseForwardedHeaders middle ware did not help (see settings above).

Once again, this is not a Blazor problem...


Code Definition
> **RemoteIpAddress** The IP Address of the client making the request. Note this may be for a proxy rather than the end user.

We want to get the IP Address of the end user. As we do not use a proxy reverse server in our installation of IIS, the  retrieved IP Address should be that of the end user, and not of the machine on which IIS installed. 

Hope I've made our issue clearer now...

Many thanks and good day...

**Comment by javiercn** [comment]
@enetstudio thanks for the additional details.

Let me route this to the right place where folks can help you.

**Comment by BrennanConroy** [comment]
Can you provide a simple repro app so we can try this out?

Also, do you know this is IIS specific? Have you tried using Kestrel and does it repro there too?

**Comment by cryo75** [comment]
Here is a simple repo:
[BlazorRemoteIPTest](https://github.com/cryo75/BlazorRemoteIPTest)

The app was published to a standard IIS running on Windows 2016 Server as a VM. It's a default installation. 

The app is accessed from my home PC, and these are the results:

The app shows the following IP Address:
![image](https://user-images.githubusercontent.com/3060986/115328626-28b1c180-a191-11eb-88e8-6000772f621b.png)

Using Ipify I can see my public IP Address:
![image](https://user-images.githubusercontent.com/3060986/115328739-6878a900-a191-11eb-9d94-64072adda766.png)

This is the IPConfig of my home PC:
![image](https://user-images.githubusercontent.com/3060986/115328904-a8d82700-a191-11eb-9012-997154c583f1.png)

This is the IPConfig of the remote VM (where the app is installed):
![image](https://user-images.githubusercontent.com/3060986/115328999-de7d1000-a191-11eb-9f27-fd8e5ba6fc28.png)

**Comment by enetstudio** [comment]
@BrennanConroy, please see the comment posted by the user @cryo75. He's a co-worker, and can provide you with all the necessary details related to the issue in hand...   

Many thanks...

**Comment by BrennanConroy** [comment]
>Also, do you know this is IIS specific? Have you tried using Kestrel and does it repro there too?

Can you please answer the above

**Comment by BrennanConroy** [comment]
I am unable to reproduce the issue. I published the app to Azure App Service and can see my public IP displayed when connecting to the site.

Can you either log the headers from requests or capture a network trace on the server side to see if the IP information is actually getting to the server?

**Comment by cryo75** [comment]
> > Also, do you know this is IIS specific? Have you tried using Kestrel and does it repro there too?
> 
> Can you please answer the above

I don't know if this is IIS specific. Kestrel was not used.

I will try to log the request headers.

**Comment by cryo75** [comment]
I added the XFF header to the IIS logs. IIS logs the remote machine's gateway ip in the 'c-ip' column and the correct client ip in the 'x-forwarded-for' header. This column contains just 1 IP address, so the client is not passing through proxies.

So question is: Why does remote address still return the gateway ip?

**Comment by BrennanConroy** [comment]
> the correct client ip in the 'x-forwarded-for' header. This column contains just 1 IP address, so the client is not passing through proxies.

Ok, so we know the IP gets to IIS, can you log the headers on the app side to see if that header gets to your app?

**Comment by cryo75** [comment]
Here are the headers (I placed the code in `_Host.cshml.cs`). The IP mentioned above (standard gateway) is that of the firewall (and IS sits obviously behind it). But as we can now ascertain my client IP is reaching IIS and also the app.

Accept = text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding = gzip, deflate, br
Accept-Language = en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7
Connection = Keep-Alive
Cookie = [Here the cookie]
Host = [Here the host, which is correct]
Referer = [Here the referer, which is correct]
User-Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 Edg/90.0.818.42
sec-ch-ua = " Not A;Brand";v="99", "Chromium";v="90", "Microsoft Edge";v="90"
sec-ch-ua-mobile = ?0
Upgrade-Insecure-Requests = 1
Sec-Fetch-Site = same-origin
Sec-Fetch-Mode = navigate
Sec-Fetch-Dest = document
X-Forwarded-Proto = https
X-Forwarded-For = 62.216.200.xx
X-Forwarded-Host = [Here the host, which is correct]
X-Forwarded-Server = [Here the server, which is correct]

Could it be a misconfiguration in `Startup.cs`? Anything else I can check?

**Comment by davidfowl** [comment]
> Could it be a misconfiguration in Startup.cs? Anything else I can check?

Yes, what does your middleware order look like?

**Comment by cryo75** [comment]
```cshtml
        public void ConfigureServices(IServiceCollection services)
        {
            //Forwarded headers
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });

            //Cookie consent options
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            //Authentication ticket store
            services.AddSingleton<ITicketStore, CookieMemoryTicketStore>();
            services.AddOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme)
                 .Configure<ITicketStore>((options, store) => {
                     options.ExpireTimeSpan = TimeSpan.FromDays(14);
                     options.SlidingExpiration = true;
                     options.SessionStore = store;
                 });

            //Cookie authentication
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options => { })
            .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                options.AccessDeniedPath = "./AccessDenied";
                options.Authority = "Authority";
                options.ClientId = "ClientId";
                options.ClientSecret = "ClientSecret";
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.ResponseMode = OpenIdConnectResponseMode.FormPost;
                options.GetClaimsFromUserInfoEndpoint = true;
                options.SaveTokens = true;
                options.UseTokenLifetime = false; 
                options.Scope.Add(OpenIdConnectScope.OpenIdProfile);
                options.Scope.Add(OpenIdConnectScope.Email);
                options.Scope.Add(OpenIdConnectScope.OfflineAccess);
                options.Scope.Add("aboserver_apicore");
                options.SecurityTokenValidator = new JwtSecurityTokenHandler
                {
                    InboundClaimTypeMap = new Dictionary<string, string>()
                };
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name"
                };

                options.Events = new OpenIdConnectEvents
                {
                    OnAccessDenied = context =>
                    {
                        context.HandleResponse();
                        context.Response.Redirect("/");
                        return Task.CompletedTask;
                    }
                };
            });

            services.AddAuthorizationCore();

            services.AddHttpContextAccessor();
            services.AddHttpClient();

            services.AddAutoMapper(typeof(AutoMapperProfile));

            services.AddMvc(options => options.EnableEndpointRouting = false).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

            services.AddRazorPages();
            services.AddServerSideBlazor().AddCircuitOptions(options => { options.DetailedErrors = true; });
            services.AddBlazoredToast();
            services.AddDevExpressBlazor(options =>
            {
                options.SizeMode = SizeMode.Medium;
            });
            services.AddDevExpressBlazorReporting();
            services.AddSingleton<IWebDocumentViewerReportResolver, DocumentViewerReportResolver>();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseMvcWithDefaultRoute();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });

            app.UseDevExpressBlazorReporting();
        }
`
