### ISSUE TITLE
'Correlation failed.' on Google Authorization when using Docker - Cookie not found.

### ISSUE THREAD

**Issue by jpbream** [dotnet/aspnetcore#31921]
### Describe the bug
I am getting a `Correlation failed.` exception when using the external Google authentication service in ASP.NET Core. I head to my Index page, and the Google account select box comes up. Then I select my account, and the exception happens. The The message also says something about a missing cookie (that is posted further down):
![image](https://user-images.githubusercontent.com/36459994/115150342-e9bb2900-a035-11eb-97c8-efe3652abda3.png)
However, this exception ONLY happens when running the application with Docker:
![image](https://user-images.githubusercontent.com/36459994/115150367-00618000-a036-11eb-96db-76ffe7c134de.png)
The authentication works totally fine when using Kestrel.

Also, I have only seen the bug when using Firefox. It works totally fine in Chrome, even when using a Docker container. Even stranger, it will work in Firefox when I run the container on an external host (ie: my production scenario). The bug only happens for me when using a Docker container on `localhost` in Firefox.

I have tried disabling all my extensions, clearing all cookies and cache for `localhost`, and using all the default security settings, but the crash will still happen in Firefox.

### To Reproduce
The bug can be reproduced with a trivial application: [Github](https://github.com/jpbream/DockerBug)
It contains only an `/Index` page, and an `AccountController` with the two authorization endpoints. On my machine, when I run this application with Docker, go to the homepage, and select my account, the exception will happen. However, if I don't use Docker (or I use Chrome), it proceeds to the `/Index` page with no issues.

You will need to register an app in the `Google Developers Cloud` to test this however. I'm not going to share my Client ID and Secret. Doing so is very simple:
1. Head to the [Google Developers Console](https://console.developers.google.com/)
2. Create a new project
3. On the `OAuth Consent Screen` tab, configure the consent screen. Just use your email with all the default values.
4. On the `Credentials` tab, click `Create Credentials` -> `OAuth Client Id`. Choose `Web Application`. Be sure to leave `https://localhost:44380/signin-google` as an authorized redirect URI. This is the port I configured the Docker container to use.
5. The `Client ID` and `Client Secret` should pop up. Copy/paste these into the spots I left in the `appsettings.json` file in the test project.
6. Run the test project using Docker and see if you can reproduce the bug.

You can delete the Google project when you are done with it.

### Exceptions (if any)
```
System.Exception: Correlation failed.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
The container output also gives me this just before the exception happens:
```
warn: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[15]
      '.AspNetCore.Correlation.gdbGbhLvCj-862NaogXrcQGhVS_mR1xlpIpbRtJ1pWA' cookie not found.
Microsoft.AspNetCore.Authentication.Google.GoogleHandler: Warning: '.AspNetCore.Correlation.gdbGbhLvCj-862NaogXrcQGhVS_mR1xlpIpbRtJ1pWA' cookie not found.
```
The string of junk characters is random.
Here is the console output from Firefox just as the exception happens:
![image](https://user-images.githubusercontent.com/36459994/115150722-a2ce3300-a037-11eb-8665-71096f772312.png)

### Further technical details
- ASP.NET Core version: 5.0.5
- Output from `dotnet --info`
![image](https://user-images.githubusercontent.com/36459994/115150751-c98c6980-a037-11eb-9c8e-67f86a64a761.png)

- Visual Studio v16.8.4
- My `WSL 2` Docker version: `20.10.5, build 55c4c88`
- Firefox version: 87.0

**Comment by Tratcher** [comment]
Please share a decrypted fiddler trace file showing both the initial request and then the request that failed.

**Comment by jpbream** [comment]
Well this is embarrassing. I seem to have accidentally fixed the issue. Since I am on Windows, my Docker engine runs out of the 'WSL 2' Integration. Every once in a while, my WSL 2 setup somehow breaks and won't send any network traffic, and can be fixed by running `wsl --shutdown`. I don't know why this happens - but it's happened a few times ever since I updated to WSL 2. This morning, after I posted this issue, I was working on another project when I noticed it happening again, so I ran `wsl --shutdown` in Powershell to fix it. That also appears to have fixed the bug I mention in this issue, because I can't replicate the bug anymore. So really it seems like there is a bug in WSL 2 that affects network traffic, but I haven't got a clue why or when that happens. You can probably close this issue.
