### ISSUE TITLE
[Blazor] Dispose guidelines

### ISSUE THREAD

**Issue by andrewittorio** [dotnet/aspnetcore#31934]
Good morning,

I am developing a Blazor Server side application, using third part libraries of components. 

Let's now assume that the third part component1.razor component implements IDisposable. 

Now, my question is: if I use the <component1> in my own wrapperComponent.razor, is it mandatory that my wrapperComponent.razor implements IDisposable too? 
I ask because it seems that the Dispose method of component1 is already automatically called and I do not want add useless additional code, if this is true. In the other hand, I am a bit confused because I know that to use a IDisposable object I should dispose it and reading the documentation I cannot find a precise answer about this scenario. Furthermore, in the developer guideline examples of the third part library I see that component are used in not IDisposable .razor pages.
I am wondering if there are precise cases when, using an IDisposable object, I have to implement IDisposabel me too and when this in not necessary. Please could you help me clarifying this doubt? 

Thank you for your time and work. Best regards,

**Comment by javiercn** [comment]
@andrewittorio thanks for contacting us.
* The framework (Blazor) is in charge of creating the components, so it also takes care of Disposing them.
* This also applies to services created from DI.
  * The DI container disposes them when the DI scope is disposed.
* In general you only need to implement IDisposable if you have a field that you are assigning a disposable object to as a result of calling `new` for the disposable object or if you are receiving an `IDisposable object` as a result of calling a method on  some other object.
* If it's a local you like just do `using var local` to make sure Dispose gets called at the end of the syntactical scope.

**Comment by andrewittorio** [comment]
@javiercn ,

thank you for your explanation. Now everything is very clear.
Thank you very much!
