### ISSUE TITLE
[QUESTION] ASP.NET MVC With React.js And Next.js

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#31932]
This really isn't a bug but I don't where else to put this. I asked a [stackoverflow question](https://stackoverflow.com/questions/67112683/how-to-use-next-js-react-js-with-visual-studio-19-asp-net-mvc)...

No reply. 

Please help me or point me in the right direction.

Thanks!

**Comment by ErrorAtNight** [comment]
@javiercn @mkArtakMSFT 

Any idea?

Thanks!
