### ISSUE TITLE
Blazor conditional events

### ISSUE THREAD

**Issue by marsPure** [dotnet/aspnetcore#31953]
I have a span which should have an onclick attribute if the IsActive bool is true. Otherwise the span should have no onclick attribute.

```csharp
@if (IsActive == true)
{
    <span @onclick="@(e => Go.DoSomething("please"))">
        @s.DisplayText
    </span>
}
else
{
    <span>
        @s.DisplayText
     </span>
}
```

Is there not a way to avoid the repeated code using a ternary operator? e.g.

```csharp
@(IsActive == true ? "add onclick method somehow?" : "")
```

I am using Blazor server and if I have an event registered and put the IsActive condition in the event handler method, every time a user click on it and there would be a performance penalty. 

I have thousands of users and have to put that IsActive on every ingle component but only couple of users will have access to it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Here is an example of how you can improve this: https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/CounterComponent.razor#L3
