### ISSUE TITLE
Unintentional change to Blazor WebAssembly startup promise semantics

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#31971]
Follow-up from https://github.com/dotnet/aspnetcore/pull/31769#pullrequestreview-638712400

It looks like an unintended consequence of #31769 was changing the behavior of the promise we return from `Blazor.start`:

* On Blazor Server, `Blazor.start` returns a promise that resolves when the .NET code starts up and the app becomes interactive
* On WebAssembly:
  * Prior to this PR, `Blazor.start` behaves the same as server (the promise resolves when the app becomes interactive)
  * Since this PR, `Blazor.start` returns a promise that doesn’t resolve until the .NET app exits, which typically means never, and hence prevents its usage for triggering post-.NET startup logic

The fault here is not in the PR, but is with us not previously having added any E2E coverage for this behavior on WebAssembly (though we do have coverage for it on Server).

Ideally we should fix this before preview 4 ships.

### Possible fix

The absolute simplest thing to do would be just removing the `await` keyword from the line where we call `platform.callEntryPoint`. Going further, it would be great to also add an E2E test for this behavior on WebAssembly.

**Comment by SteveSandersonMS** [comment]
cc @TanayParikh @mkArtakMSFT

**Comment by javiercn** [comment]
@SteveSandersonMS that sounds good to me

**Comment by captainsafia** [comment]
Thanks for this write-up. Can you point me to the test scenario we use to validate this in server? 

> Since this PR, Blazor.start returns a promise that doesn’t resolve until the .NET app exits, which typically means never, and hence prevents its usage for triggering post-.NET startup logic

So something like this would no longer work in WASM?

```js
Blazor.start().then(() => {
  // some initialization logic
});
```

**Comment by SteveSandersonMS** [comment]
> Thanks for this write-up. Can you point me to the test scenario we use to validate this in server?

Sure. This [line of code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml#L28) is where we tell the Blazor Server tests they are OK to start executing, so if it never ran, the tests would wait forever. There isn't any equivalent to that in our WebAssembly tests AFAIK.

> So something like this would no longer work in WASM?

Yes, exactly.

**Comment by TanayParikh** [comment]
Thanks @SteveSandersonMS  for pointing this out! Put up a PR here: https://github.com/dotnet/aspnetcore/pull/31978
