### ISSUE TITLE
Changing the default value of a property sometimes results in a rude edit, sometimes successfully hot reloads

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31999]
Repro steps:
- Install 6.0.100-preview.4.21219.6
- `dotnet new blazorserver`
- `dotnet watch`
- Add an `IncrementAmount` component parameter in Counter razor

```
    [Parameter]
    public int IncrementAmount { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount+=IncrementAmount;
    }
```

- In VS Code with Autosave enabled repeatedly change the default value of IncrementAmount to different values

Expected result: The change is always successfully hot reloaded
Actual result: Sometimes the change results in rude edit and app restart

![u11QtTewgw](https://user-images.githubusercontent.com/1874516/115475483-8fb49200-a1f4-11eb-9efa-cae6f4fb268e.gif)

@pranavkm

**Comment by pranavkm** [comment]
Very likely a bug in RSG. If you run watch with `--verbose` you'll notice errors like so:

```
atch : Unable to apply hot reload because of a rude edit. Rebuilding the app...
watch : Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Counter_razor.cs(82,5): error ENC0004: Updating the modifiers of 'class' will prevent the debug session from continuing.
watch : Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Counter_razor.cs(82,5): error ENC0033: Deleting attribute will prevent the debug session from continuing. 
watch : Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Counter_razor.cs(82,5): error ENC0033: Deleting field 'currentCount' will prevent the debug session from continuing.
watch : Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Counter_razor.cs(82,5): error ENC0033: Deleting method 'IncrementCount()' will prevent the debug session from continuing.
watch : Unable to handle changes to D:\temp\watchapps\b4\Pages\Counter.razor. Rebuilding the app.
```

**Comment by pranavkm** [comment]
We added a workaround to mitigate this in 6.0-p4. While this is resolved in the ordinary case, some of these things are ultimately left to the whims of file systems and IDE behavior and it's possible that we end up producing unnecessary rude edits. Regardless, resolving this since this particular issue has been addressed.
