### ISSUE TITLE
dotnet-watch: Hot reload causes blazorwasm apps to rebuild

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31994]
We recently added a feature to restart the app if applying a delta to a blazor wasm app crashes after a hot reload applies. This happens fairly frequently with the current implementation of the runtime since the hot reload capabilities in wasm are less capable than the .net core case. 

When testing this scenario, we found out that there's an issue with the implementation and while hot reload applies, watch kicks off a rebuild.

**Comment by DrewScoggins** [comment]
Heads up for @stephentoub @brianrob @Pilchie, this is blocking performance runs for WASM Hot Reload

**Comment by pranavkm** [comment]
This should be resolved as part of https://github.com/dotnet/sdk/pull/17053. @captainsafia could you do a sanity check once the change becomes available as part of the installer?

**Comment by captainsafia** [comment]
Sure! I'll keep an eye out for the flow and respond back once it's landed.

**Comment by captainsafia** [comment]
Resolved in 6.0.100-preview.4.21222.3
