### ISSUE TITLE
Blazor WASM template missing ko-KR translations

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspnetcore#31995]
While testing out localization we discovered that there were no translations for the Blazor WASM template in ko-KR. I looked at the template and the WASM template is missing the ko-KR folder.
The Blazor Server template does have this folder, and translation file.

Due to this issue, Visual Studio users are not getting translations when running with ko-KR locale.

cc @phenning @vijayrkn

**Comment by pranavkm** [comment]
Fixed as part of #32016 32016
