### ISSUE TITLE
HTTP/3: CONNECT method

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#32004]
https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.2

What level of support is required for CONNECT method requests?

**Comment by Tratcher** [comment]
Kestrel has not supported connect in any protocol version to date. No reason we'd start now.

**Comment by JamesNK** [comment]
There is some logic that checks for CONNECT when validating headers and tests for it

https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs#L235-L258

**Comment by Tratcher** [comment]
Hmm, there is some protocol validation here:
https://github.com/dotnet/aspnetcore/blob/741d210c73f3b159520d1993998f38729fcca051/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L225-L237
But tunneling is still not supported. Not sure what else you would use CONNECT for.

**Comment by JamesNK** [comment]
I don't think there is anything else to do here. Re-open if that changes.
