### ISSUE TITLE
[Identity] SignInManager.PasswordSignInAsync returns false to the RequiresTwoFactor property

### ISSUE THREAD

**Issue by abryzgin** [dotnet/aspnetcore#32012]
Hello!

For Login I use SignInManager.PasswordSignInAsync with 2FA

if the isPersistent flag = false during registration, then everything works well. Result of _signInManager.PasswordSignInAsync = result.RequiresTwoFactor. 2FA works.

But

if the isPersistent flag = true. First, 2FA will work, and after logging out and trying to log in again, the system will not ask for the 2FA code 

most likely the problem is in this method:
[IsTwoFactorClientRememberedAsync ](https://github.com/dotnet/aspnetcore/blob/7af95b42681e6808a3944168dcf54a7c4adbf0f8/src/Identity/Core/src/SignInManager.cs#L785-L791)

Code for Login:

```
public async Task<IActionResult> Login(UserLoginModel userModel, string returnUrl = null)
{
	if (!ModelState.IsValid)
	{
		return View(userModel);
	}

	var result = await _signInManager.PasswordSignInAsync(userModel.UserName, userModel.Password, userModel.RememberMe, lockoutOnFailure: true);

	if (result.Succeeded)
	{
		return RedirectToLocal(returnUrl);
	}
	if (result.RequiresTwoFactor)
	{
		var user = await _userManager.FindByNameAsync(userModel.UserName);
		return RedirectToAction(nameof(LoginTwoStep), new { user.Email, userModel, userModel.RememberMe, returnUrl });
	}

	if (result.IsLockedOut)
	{
		/*		
		*	some code
		*/

		return View();
	}
	else
	{
		ModelState.AddModelError("", "Unsuccessful login attempt");

		return View();
	}
}
```

**Further technical details**
- ASP.NET Core 5

**Comment by blowdart** [comment]
This is by design, remember me also remembers the device, and won't mfa prompt again.

**Comment by abryzgin** [comment]
How then to request the code 2FA?

**Comment by blowdart** [comment]
You could delete the cookie on logout by calling ForgetTwoFactorClientAsync() on the SignInManager, or remove the ability to have remember me. Facebook, github et al work in exactly the same way.
