### ISSUE TITLE
[SPA] Setup new repo for the templates

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#32027]
The new repo name is: https://github.com/dotnet/spa-templates

* We need to setup dependency flows from the asp.net core and into the SDK
* We need to move the code from src/ProjectTemplates/Spa.ProjectTemplates into this new repo.
* We need to produce packages and flow them into the SDK

- [x] Populate the dotnet/spa-templates repo
- [x] Use the new repo as a submodule in dotnet/aspnetcore (#34366 w/ fix in #34499)
- [x] Get dotnet/spa-templates to support `dotnet build` when built outside the dotnet/aspnetcore submodule
- [x] Revert changes to src/submodules/Directory.Build.* files

**Comment by mkArtakMSFT** [comment]
@dougbu I've asked @terrajobst to setup the new repo. Will you then help us with getting it wired up in Arcade so that the dependencies flow properly. @javiercn will fill in the details in this issue shortly, so that it's clear what exactly is needed.

**Comment by dougbu** [comment]
- What versions need to flow and from where❔
- Will the new repo build using the Arcade SDK❔
- Are you asking me to also create the AzDO repo necessary for official builds❔

**Comment by mkArtakMSFT** [comment]
Talked some more regarding this and the decision is to have the new repo configured as a module for doptnet/aspnetcore.

**Comment by dougbu** [comment]
@mkArtakMSFT @javiercn it's been a bad week for progress on almost anything. Just got the questions&hellip;

1. @javiercn am I correct you meant "src/ProjectTemplates/**Web.**Spa.ProjectTemplates" instead of "src/ProjectTemplates/Spa.ProjectTemplates"❔
2. Does the new repo need to build when referenced outside the submodule in dotnet/aspnetcore❔
   1. If yes, do we need an AzDO mirror for official builds❔
   2. If yes, should the new repo build using the Arcade SDK❔
3. Should the new repo have the commit history for the ported files❔
   1. If yes, do we need the commit history for the older src/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/ and src/templating/test/Templates.Test/SpaTemplateTest folders❔
      1. If yes to that as well, do we need the commit history for the even older src/templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates and src/Templating/test/Templates.Test/SpaTemplateTest folders❔
 4. I can't find tests that do anything w/ these templates outside src/ProjectTemplates/Shared/TemplatePackageInstaller.cs. Am I missing something that may need to change aside from the project reference in ProjectTemplates.Tests.csproj❔

**Comment by dougbu** [comment]
Thoughts @javiercn❔ I'm hesitant to start on this work w/o answers here.

**Comment by dougbu** [comment]
Please have a look at https://github.com/dougbu/spa-templates

Let me know if the commit syntax, file layout, et cetera matches what you want. I migrated all src/ files and moved them up to the src/ level in the repo. Made no attempt to get isolated builds working.

After tweaking things, it shouldn't take long to run my script (see https://github.com/dougbu/consolidation/blob/main/build.sh) one more time and fill in dotnet/spa-templates.

**Comment by dougbu** [comment]
/ping @mkArtakMSFT and @javiercn. I just slightly updated the commit message tweaks and reran the scripts to populate https://github.com/dougbu/spa-templates. I don't expect much more will need to change but need your feedback before populating https://github.com/dotnet/spa-templates.

**Comment by javiercn** [comment]
@dougbu took a quick look, changes look reasonable

**Comment by dougbu** [comment]
@mkArtakMSFT I don't have rights to push to dotnet/spa-templates. Please let me know when I can try again.

**Comment by mkArtakMSFT** [comment]
@dougbu you should be good now. Give it a try!

**Comment by dougbu** [comment]
Phase one is now done. dotnet/spa-templates contains the right files and commits. Moving on to phase two: Create and use submodule for that repo in dotnet/aspnetcore.

**Comment by dougbu** [comment]
See #34366 for phase 2. I'd like to get this in tomorrow. (Fortunately, it's mostly deletion of the src/ProjectTemplates/Web.Spa.ProjectTemplates/ folder.)

**Comment by SteveSandersonMS** [comment]
@dougbu In #34366, it adds the submodule as a reference to https://github.com/dougbu/spa-templates.git rather than https://github.com/dotnet/spa-templates.git. Is that intentional? Is it just temporary?

**Comment by dougbu** [comment]
> Is that intentional? Is it just temporary?

Neither. That was a **mistake**

**Comment by dougbu** [comment]
> > Is that intentional? Is it just temporary?

> Neither. That was a **mistake**

Fix is in #34499

**Comment by dougbu** [comment]
Not `blocked` anymore 😺 

I'm moving on to phase 3 (of 4). See new checklist in the description&hellip;

**Comment by dougbu** [comment]
Actually, I think this is done -- thanks for the nudge😺  If you need me to do Arcade-like stuff, add a CI setup, or an internal mirror repo, let's handle that separately.
