### ISSUE TITLE
Blazor WASM: Missing Scoped CSS after .NET 5.0 upgrade

### ISSUE THREAD

**Issue by DenmarkG** [dotnet/aspnetcore#32024]
### Describe the bug
After upgrading to a project to .NET 5.0 my project stopped working on Github pages. Inspecting the console it appears that the /{ProjectName}/_framework/scoped.styles.css/ request returns a 404 Not Found error. I checked the published folder and the file does not exist in the folder. 

I've already followed all the steps outlined [here](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)

I tried again, using just the startup project with no changes, and the file is still missing after publishing. 

### To Reproduce

Create a new Blazor Web Assembly project with VS2019. 
Create a folder profile for publishing (Target runtime = Portable)
Publish.

### Exceptions (if any)

None

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS2019 16.8.6

**Comment by javiercn** [comment]
@DenmarkG thanks for contacting us.

The bundle we generate is not in that location, it is at the root of the project. I would suggest you create an empty project and check out the differences in index.html as well as on the output folder. You can run `dotnet publish` to see where the file is located within the wwwroot folder.

**Comment by DenmarkG** [comment]
@javiercn I should clarify, the scoped.styles.css file does not exist in any directory at all after publishing, even with a fresh project. I've tried this using the dotnet publish in the command line, as well as through the publish window in Visual Studio.

**Comment by javiercn** [comment]
@DenmarkG can you share your version of the dotnet sdk produced by `dotnet --info` as well as the command line you used to create and publish the process?

**Comment by DenmarkG** [comment]
Sure thing, I've attached the files with the console output as well as an image of the contents of the wwwroot folder. 

[DotNetInfo.txt](https://github.com/dotnet/aspnetcore/files/6359660/DotNetInfo.txt)
[DotNetPublishInfo.txt](https://github.com/dotnet/aspnetcore/files/6359661/DotNetPublishInfo.txt)
![wwwRoot](https://user-images.githubusercontent.com/6344169/115746955-a9b3b900-a349-11eb-8041-abd68e3f1f36.PNG)

**Comment by DenmarkG** [comment]
@javiercn As a bit of a side question, how can I figure out where this file is referenced in the final published build?

**Comment by javiercn** [comment]
@DenmarkG The file is there `Pennies.styles.css` if you are looking for `/{ProjectName}/_framework/scoped.styles.css` that was only on a preview version.

**Comment by DenmarkG** [comment]
@javiercn the final release build is looking for that preview file. Something in the build is still referencing that `scoped.styles.css` file and causing the 404 error

**Comment by javiercn** [comment]
@DenmarkG I would suggest you start with `index.html`.

As an alternative I would just search all files for `scoped.styles.css` in VS Code?

**Comment by DenmarkG** [comment]
@javiercn thanks for your help. I think I see what's going  on now. 

Is it possible that on [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#github-pages) or in the update docs I mentioned before, that the line  `<link href="_framework/scoped.styles.css/" rel="stylesheet" />`  should be removed before publishing a build?

**Comment by javiercn** [comment]
@DenmarkG I'm not sure that shipped in an RTM version and I'm not sure we document migrations from previews. That said, @guardrex is this something we can cover in the docs assuming we cover preview to preview migrations? Feel free to add it to the docs and get it merged right away.

**Comment by guardrex** [comment]
I don't think we can document this without more info. That file is a Blazor Server scenario or **_Server_** project in hosted WASM scenario. Idk how that `<link>` ended up there. I'll close the docs issue for now, just perhaps until I hear back what scenario leads to that link appearing in a WASM app.
