### ISSUE TITLE
Resource limit API review

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#32030]
Part of Epic https://github.com/dotnet/aspnetcore/issues/27464, 

Currently, ongoing design doc at https://github.com/aspnet/specs/tree/main/design-notes/ratelimit

- [x] dotnet/runtime proposal: https://github.com/dotnet/runtime/issues/52079
- [ ] dotnet/aspnetcore proposal

**Comment by JunTaoLuo** [comment]
We've done the API review with dotnet/runtime as part of https://github.com/dotnet/runtime/issues/52079. We have additional APIs to review but that will happen in the future. (e.g. AggregatedRateLimiter)

**Comment by adityamandaleeka** [comment]
@wtgodbe I'm closing this since I don't think this is tracking anything meaningful at this point.
