### ISSUE TITLE
Annotate generated razor C# file with pragmas to hide unnecessary diagnostics

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#32042]
[Here's](https://github.com/dotnet/aspnetcore-tooling/blob/0d46aaf1e3d77399a03eeea0f6b464a01c3f672f/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs#L248) where we do the Razor C# diagnostic filtering/postprocessing currently.

Main things are `CS1525` (missing attribute value) and using directive not necessary (`IDE005_gen` & `RemoveUnnecessaryImportsFixable`). We also hide all non-error severity (ie. information, warning, etc.) diagnostics which don't have a 1:1 mapping to the .razor document.

Hiding missing attribute value diagnostic is done [here](https://github.com/dotnet/aspnetcore-tooling/blob/0d46aaf1e3d77399a03eeea0f6b464a01c3f672f/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs#L264-L275). We could update:

```csharp
__o = Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.ProgressEventArgs>(this, );
```

to

```csharp
__o = Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.ProgressEventArgs>(this, default);
```

to get rid of:
![image](https://user-images.githubusercontent.com/14852843/115629527-64df4200-a2b7-11eb-9bf7-b6490d0f85d1.png)

cc/ @captainsafia

**Comment by mkArtakMSFT** [comment]
Closing as this is going to be obsolete work after the combined build (not having design time and runtime builds).
