### ISSUE TITLE
http can not redirect to https

### ISSUE THREAD

**Issue by zsjbsn** [dotnet/aspnetcore#32047]
Hi,
    I want to enforce all HTTP to HTTPS, but it responses failed when I use HTTP to access website. In browser, if I first use HTTPS to access website and then use HTTP to access, it responses ok. otherwise, I use "curl http://xxx.com" in cmd, it returns "(52) Empty reply from server".
Code in ConfigureServices of Startup.cs
```
services.AddHsts(options =>
{
    options.Preload = true;
    options.IncludeSubDomains = true;
    options.MaxAge = TimeSpan.FromDays(60);
});
```
Code in Configure of Startup.cs
```
var options = new RewriteOptions();
options.AddRedirectToWww();
options.AddRedirectToHttps();
app.UseHsts();
app.UseRewriter(options);
```

**Comment by Tratcher** [comment]
See for https docs:
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#require-https
And here for logging:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

Enable the server debug logs to see what's happening.
