### ISSUE TITLE
Ensure resource limit APIs can be used by existing implementations

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#32041]
This is part of epic: https://github.com/dotnet/aspnetcore/issues/27464.

This issue tracks the work to ensure existing rate limits implemented can adopt the new abstractions.

Candidates to consider:
- ACR
- ATS
- OneAccess
- R9

**Comment by adityamandaleeka** [comment]
I'm not sure this is actionable anymore. @BrennanConroy I'm closing this, but reopen if you think it's needed.
