### ISSUE TITLE
asp .net 5 can't return json with 404 status code

### ISSUE THREAD

**Issue by VladislavMorozov** [dotnet/aspnetcore#32046]
I use .net 5.0.202 with system.text,json.
I have exception handler
![image](https://user-images.githubusercontent.com/31768904/115525544-dd360b00-a297-11eb-9bed-4b44dc9b2c94.png)
With processing errors.
![image](https://user-images.githubusercontent.com/31768904/115525067-6e58b200-a297-11eb-919e-04d6b3cfc1a2.png)

(failed)net::ERR_INCOMPLETE_CHUNKED_ENCODING

![image](https://user-images.githubusercontent.com/31768904/115525376-b4ae1100-a297-11eb-8893-bc13c559b7c8.png)

**Comment by fvoronin** [comment]
I did a little investigation and found that the problem occurs when we set the StatusCode = 404 in the response. In this case, the web server transmitting the response in "Transfer-Encoding: chunked" mode does not transmit a zero-length chunk at the end of the response body.

Compare. As now:
```
HTTP/1.1 404 Not Found
Date: Thu, 22 Apr 2021 06:40:36 GMT
Content-Type: application/problem+json
Server: Kestrel
Cache-Control: no-cache,no-store
Pragma: no-cache
Transfer-Encoding: chunked
Expires: -1

75
{"title":"title","status":404,"detail":"details","traceId":"00-93249638518c924dafd48997d28c8303-ccd2508c5de5a34d-00"}

```
As it should be:
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 22 Apr 2021 06:40:03 GMT
Content-Type: application/problem+json
Server: Kestrel
Cache-Control: no-cache,no-store
Pragma: no-cache
Transfer-Encoding: chunked
Expires: -1

75
{"title":"title","status":404,"detail":"details","traceId":"00-0bad9468621ebd4981854389e389ba9d-29a0cf6cc2c0e44d-00"}
0


```

@Tratcher, I'd like to take a deeper look at it.

**Comment by davidfowl** [comment]
It's by design, you can disable this behavior with https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.exceptionhandleroptions.allowstatuscode404response?view=aspnetcore-5.0.

**Comment by davidfowl** [comment]
@VladislavMorozov there are also built in helpers for writing JSON responses as well:

- https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponsejsonextensions.writeasjsonasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Http_HttpResponseJsonExtensions_WriteAsJsonAsync_Microsoft_AspNetCore_Http_HttpResponse_System_Object_System_Type_System_Text_Json_JsonSerializerOptions_System_Threading_CancellationToken_
- https://docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-5.0#create-json-web-apis

**Comment by VladislavMorozov** [comment]
But before it works on .net 5 :) Thanks for help

**Comment by VladislavMorozov** [comment]
@davidfowl It works with https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.exceptionhandleroptions.allowstatuscode404response?view=aspnetcore-5.0
Thanks. But I don't understand how this works on previous versions of .net 5 :)

**Comment by davidfowl** [comment]
> But I don't understand how this works on previous versions of .net 5 :)

Because we changed the behavior. https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/middleware-exception-handler-throws-original-exception

We added this API later but never updated the original change it seems:

https://github.com/dotnet/aspnetcore/pull/26567

cc @JunTaoLuo @Tratcher

**Comment by VladislavMorozov** [comment]
@davidfowl It's okay that server return (failed)net::ERR_INCOMPLETE_CHUNKED_ENCODING ?

**Comment by Tratcher** [comment]
> @davidfowl It's okay that server return (failed)net::ERR_INCOMPLETE_CHUNKED_ENCODING ?

That means the rethrown exception caused the connection to be closed and the response aborted. There's another issue where we disabled the 404 rethrow if there was a body to prevent this kind of abort.

**Comment by Tratcher** [comment]
Correction, @JunTaoLuo and I talked about adding a HasStarted check here, but it doesn't look like it's happened yet.
https://github.com/dotnet/aspnetcore/blob/9817a811c1fe6034b112e4fde84d2f4271492dc5/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L135
@JunTaoLuo do you remember if there's another issue for that, or did we change our minds?

**Comment by BrennanConroy** [comment]
Triage: we think there is another issue for this. TLDR; we should add the HasStarted check on the body at the end of the error handler.

**Comment by davidfowl** [comment]
Mark as up for grabs?

**Comment by JunTaoLuo** [comment]
Ah, the HasStarted check was proposed in https://github.com/dotnet/aspnetcore/issues/31024#issuecomment-802268610 but I neglected to do that since during triage we decided to add more useful exception message. I can add the check since it should be a one line change.
