### ISSUE TITLE
Creating a System.IO.Compression.ZipArchive from FileMultipartSection.FileStream yields in errors.

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#32055]
### Describe the bug
When you have a `FileMultipartSection` taken from a `HttpContext.Request` object that contains `multipart/form-data` content and contains valid file disposition, when you decide to create a ZipArchive out of the "FileStream" object, you get the following exception:

```
The Position must be positive. (Parameter 'value')
Actual value was -10.
```

In reality, I'm aware that the `FileStream` property to `FileMultipartSection` is not really a `FileStream`, but a `MultipartReaderStream`, still - it seems really confusing for this not to work.

If this is not a bug, could someone expand on exactly what's going on here which leads to the above error?

### Further technical details
- ASP.NET Core version - .NET 5
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.114 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
Please provide a code sample and the full exception with stack trace.

**Comment by SpiritBob** [comment]
@Tratcher Okay! When I'm free from everything else, I'll be sure to notify you here. I'll also provide a fully working Github repository you can experiment with.

**Comment by SpiritBob** [comment]
@Tratcher After doing a deep-dive, it seems that the issue might be coming from a call to `HttpContext.Request.EnableBuffering()`, which is used with the idea that at later stages you might need to re-read the underlying stream.


Removing the above call fixes the issue, otherwise an exception is thrown.

Repository with code to test: https://github.com/SpiritBob/RequestBufferingIssue

Actual code to reproduce:
```
[HttpPost("bugged")]
[DisableFormValueModelBinding]
public async Task<IActionResult> UploadMultipartUsingReader()
{
    Request.EnableBuffering(); // This causes issues for some reason
    var boundary = GetBoundary(MediaTypeHeaderValue.Parse(Request.ContentType));
    var reader = new MultipartReader(boundary, Request.Body, 80 * 1024);

    MultipartSection section;

    while ((section = await reader.ReadNextSectionAsync()) != null)
    {
        var contentDispo = section.GetContentDispositionHeader();

        if (contentDispo.IsFileDisposition())
        {
            var fileSection = section.AsFileSection();

            try
            {

                // exception incoming here
                var archive = new ZipArchive(fileSection.FileStream);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }
    }

    return Ok();
}
```

**Comment by Tratcher** [comment]
It's likely related to https://github.com/dotnet/aspnetcore/issues/31753. When buffering is enabled the stream is seekable, but it's not fully buffered yet and the length isn't accurate. 

Mitigations:
- Fully buffer the stream first `fileSection.FileStream.DrainAsync(); fileSection.FileStream.Position = 0;`
- Disable buffering.
- Use Request.ReadFormAsync(), it pre-buffers the form parts separately. If you're buffering anyways then this API seems easier to use.

**Comment by SpiritBob** [comment]
@Tratcher I have a question in regards to that. If you opt into reading the underlying stream with hopes of saving hard disk space, but you go the route of re-reading the request's stream directly like I did above, like it or not - the file must be saved on the hard drive (granted it's above the default size of 32kb)

If I'm correct in this, wouldn't it then be much better to simply fallback to the `IFormFile` approach? As in both situations, you'd be taking a hit of say a 500 mb temporary file, in order to support re-reading the stream.

Are there benefits to sticking to the above, or is it correct to simply let ASP.NET Core do the model binding with `IFormFile`?
I'm not sure how that would pan out with multiple files - say 5 files in a multipart/form-data request.

Is there a way to enable re-reading and read one file specifically, then to dispose of it (and it's temporary file) before reading the next one etc? If there is such a case, then I already see the benefits, as `IFormCollection` will blast you with all the file's contents as temporary files.

Thank you for helping me out Tratcher.

**Comment by Tratcher** [comment]
If you're buffering regardless, IFromCollection/IFormFile is the simplest approach.

The main reason to use the MultipartReader directly is if there are parts that you do not want to buffer, it would let you choose per section how to handle it.

> Is there a way to enable re-reading and read one file specifically, then to dispose of it (and it's temporary file) before reading the next one etc? If there is such a case, then I already see the benefits, as IFormCollection will blast you with all the file's contents as temporary files.

I still don't quite understand your re-reading requirement, especially when you talk about reading one file at a time and disposing it like this. Do you need to seek around within one file at a time, but not across files? If that's the case you don't enable buffering on the whole stream, you do it per file. There's an example for that here:
https://github.com/dotnet/aspnetcore/issues/31666#issuecomment-822653168

**Comment by SpiritBob** [comment]
Yes, I was asking if there was a possible per-file approach, and after testing it was exactly what I was searching for - thank you once again!

My actual requirements get filled by a simple `IFormFile`, but I just wanted to make sure if there was any other reason to stick to manually reading the stream, rather than it being binded by ASP Net Core, and it seems there is - for multiple files that is.

For my case, it's just a single file, so I'll just use `IFormFile` for that.

Closing this as I think everything is now resolved? It would be nice to document this nice feature in the docs, as suggested in the other thread.

**Comment by davidfowl** [comment]
Why do you need to buffer at all here?

**Comment by SpiritBob** [comment]
To re-read the stream at a later stage.

**Comment by davidfowl** [comment]
2 questions:
- What later stage after the controller action?
- What would you want to re-read a file upload during the same request?

**Comment by SpiritBob** [comment]
Imagine someone uploads a file, that you wish to validate. In order to validate the file - you need to read it.
After reading, you'd like to re-upload it to another service on the web, and for that - you need to re-read the stream, am I wrong?

The stage would be after the file has been verified.

**Comment by davidfowl** [comment]
> Imagine someone uploads a file, that you wish to validate. In order to validate the file - you need to read it.
After reading, you'd like to re-upload it to another service on the web, and for that - you need to re-read the stream, am I wrong?

Yes, if you care about efficiency you would try your best to validate it on the fly. The only reasonable case for buffering is if you want to retry and I would be opportunistic about that (maybe only retry in chunks). This is what we typically refer to as a read through Stream. A Stream that wraps another stream and performs transformations or validations on the fly to avoid buffering the entire thing into memory causing problems for the GC.

**Comment by SpiritBob** [comment]
Sometimes reading binary files, like Excel for example, require use of things like `ZipArchive` that won't work unless the content is fully buffered.

I'm actually getting an exception if I do
```
var section = await reader.ReadNextSectionAsync(cancellationToken);
await using var bufferedStream = new FileBufferingReadStream(section.Body, memoryThreshold: 1024 * 30);
```

which I've outlined with a stack-trace in the original thread: https://github.com/dotnet/aspnetcore/issues/31666#issuecomment-826640691

Are you referring to the above as a read through Stream?

**Comment by davidfowl** [comment]
> Sometimes reading binary files, like Excel for example, require use of things like ZipArchive that won't work unless the content is fully buffered.

Yes it seems ZipArchive [*really* wants to see the content buffered](https://github.com/dotnet/runtime/blob/e5dd7150e6ced783159a8ae3adb77b899b1204db/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L141-L146) so I guess there's nothing you can do here since it needs the stream to be seekable in order to read from the back.

How big are these zip files that are being uploaded? Any size? You'll need to figure out a performance tradeoff here, maybe buffering to local disk temporarily is better and using `IFormFile` makes more sense in this scenario.

**Comment by SpiritBob** [comment]
Exactly! I think `IFormFile` for this specific use-case is the option to go, unless I'd like to support multiple file uploads, in which case I'd still need to buffer them to the disk, but I'd be doing it in a one by one fashion, rather than bulk.

For our specific use-case, we agreed the files to be small - about 5 to 10 mb's, but the original intentions and goal was to have it programmed in a way that it would handle big files - as large as 300-500 mb's.

I now realize that if it were to come to this, we'd surely face problems as all of those would have no option but to be stored on the disk. In such an event - we'd either have to introduce some form of monitoring/locking, or use a dedicated file storage scenario.

**Comment by davidfowl** [comment]
> I'd be curious to see how one would be able to monitor these kinds of things. On a side-note: Is there an option of changing the default memory buffer of an IFormFile? The default is 32 kb.

You can configure [FormOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.formoptions?view=aspnetcore-5.0) in ConfigureServices.

```
services.Configure<FormOptions>(o =>
{
     // Configure some defaults here                
});
```

@Tratcher this type is poorly documented 😞
