### ISSUE TITLE
dotnet dev-certs on linux

### ISSUE THREAD

**Issue by vitalii-pokrivchak** [dotnet/aspnetcore#32051]
dotnet dev-certs command not work correctly on linux

**Comment by javiercn** [comment]
@vitalii-pokrivchak thanks for contacting us.

Can you give us more details about what doesn't work?

**Comment by vitalii-pokrivchak** [comment]
> @vitalii-pokrivchak thanks for contacting us.
> 
> Can you give us more details about what doesn't work?

 this tool cannot create a valid certificate for the ASP.NET Core website in Linux. When you run the command, it displays that a valid certificate is already present but in fact https does not work

**Comment by mkArtakMSFT** [comment]
Thanks @vitalii-pokrivchak.
Are you seeing any issues when you're trying to access the website?

**Comment by danroth27** [comment]
@vitalii-pokrivchak If you're seeing that the app successfully listens on an HTTPS address, but the certificate is not trusted, that is expected on Linux as there isn't a standard way across Linux distros to establish certificate trust. You'll need to setup trust for the certificate yourself.

If you're hitting some other issue with getting HTTPS to work, please give us more details on exactly what isn't working and we'll do our best to help you out.

**Comment by vitalii-pokrivchak** [comment]
@mkArtakMSFT Thanks for reply.
Problem with when opening the page from the browser the certificate is invalid and if to make request through cURL or wget

**Comment by javiercn** [comment]
@vitalii-pokrivchak thanks for the additional details. The problem you have is with the certificate not being trusted by your machine. We don't support trusting the cert automatically on Linux, however we provide instructions for you to do so. Check https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-on-linux for how to do that.

**Comment by vitalii-pokrivchak** [comment]
@javiercn Thank you very much
