### ISSUE TITLE
SourceLink links broken for some files because of space in name

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#32065]
This file appears to have a space in the filename, causing source links to be generated incorrectly. It may be that the link is generated incorrectly, or that the validation is a bit wonky, but the space is probably not intended.

https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Intermediate/LazyIntermediateToken%20.cs

**Comment by dougbu** [comment]
Fixed in #32066
