### ISSUE TITLE
OkObjectResult should be changed to support better type safety

### ISSUE THREAD

**Issue by AgentEnder** [dotnet/aspnetcore#32080]
## Summary

[OkObjectResult](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/OkObjectResult.cs) has an inner type of object?. This proposal is to make it generic, allowing better type safety when used in conjunction with ActionResult<T>

## Motivation and goals

Currently it is possible to break type safety in a method that returns an ActionResult<T>. See the code sample below, found in a controller.

```csharp
[HttpGet()]
public ActionResult<T1> MyControllerMethod {
    T2 myResult = repository.get();
    return Ok(myResult);
}
```

This code not only compiles, but creates API endpoints whose swagger documentation represents T1, when the returned type is actually T2. This is clearly unintended.

The goal here is to not change the signature of the helper functions like Ok(), but to use generics and type inference to ensure that types flow through the system properly.

## Risks / unknowns

Some API's could theoretically build only because of this issue. While this would not be a hard thing for developers to fix, this would be a breaking change due to some projects not building after the types are locked down.

**Comment by pranavkm** [comment]
Thanks @AgentEnder for your issue. We're considering tackling this issue as part of https://github.com/dotnet/aspnetcore/issues/8535 for 6.0. Feel free to upvote the other issue so we can prioritize it correctly.
