### ISSUE TITLE
windows event log recording: An ISAPI reported an unhealthy condition to its worker process.

### ISSUE THREAD

**Issue by dighexode** [dotnet/aspnetcore#32098]
### Describe the bug
Every time I put a app_offline.htm file into our code folder for doing code move, or I changed web.config in code folder, windows event log will record such a log: An ISAPI reported an unhealthy condition to its worker process. Therefore, the worker process with process id of '21676' serving application pool 'abc.com' has requested a recycle.
This event log's Id is 5078.

Can you tell me why recording such a log? Especially when uploading a app_offline.htm file, this file is just for getting the site offline to move code files, so it should not record such a log. Web.config is same, changing web.config will cause the site restarting, why record this log?

This should not be a bug, but I really don't know where to ask, I don't think this is a question for IIS. Even I need to set IIS app pool Advanced Settings - Generate Recycle Event Log Entry - set 'Isapi Reported Unhealthy' to be True.

### Further technical details
- ASP.NET Core version: 3.1

**Comment by BrennanConroy** [comment]
What are the ISAPI filters that you have registered in your IIS pipeline? We don't add any by default.

**Comment by dighexode** [comment]
@BrennanConroy Do you mean this?
![image](https://user-images.githubusercontent.com/8807880/116088366-61432500-a6d4-11eb-8c05-36e243862074.png)
![image](https://user-images.githubusercontent.com/8807880/116088421-6f914100-a6d4-11eb-804a-e4d9df31acb3.png)

**Comment by BrennanConroy** [comment]
Can you switch your app pool to managed instead of classic? Does that not produce the same issue?

Can you share your event log of the error?

> Can you tell me why recording such a log?

This is the expected behavior when using ANCM.

**Comment by dighexode** [comment]
@BrennanConroy We are using No Managed Code and Integrated for our .net core 3.1 webapi application. Do you mean change to Managed Code and Classic?
![image](https://user-images.githubusercontent.com/8807880/116191574-21754f80-a75f-11eb-900a-77f71937e7de.png)

There is no more log, just: An ISAPI reported an unhealthy condition to its worker process. Therefore, the worker process with process id of '8288' serving application pool 'abc.com' has requested a recycle.

You said this is an expected behavior, then can you tell me why the log has no detailed information? Such as: ISAPI name, detailed unhealthy information etc.

**Comment by jkotalik** [comment]
Hm, that's odd then. If you are using Integrated pipeline mode, I don't believe the ISAPI module should be running at all. Maybe the module is always enabled though.

Either way, our hypothesis is that because we are calling [`IHttpServer::RecycleProcess`](https://docs.microsoft.com/en-us/previous-versions/iis/smooth-streaming-client/ihttpserver-recycleprocess-method), the ISAPI module sees that as "Unhealthy", even though the it's a graceful shutdown. We believe that this is just a bad log from the ISAPI module.

**Comment by dighexode** [comment]
@BrennanConroy I see, thank you! I saw your add this into 'Discussions', so I can expect a reply later here? Or some articles will be linked into here with your final decision about this log?
