### ISSUE TITLE
MarkupString? doesn't render raw content 

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/aspnetcore#32099]
### Describe the bug
Using server side Blazor.
When rendering a nullable MarkupString, the raw string isn't output but rather a sanitized one.
If MarkupString is not nullable (remove the question mark bellow), it works as expected.

### To Reproduce
```
@Text

@code
{
    public MarkupString? Text { get; } = new MarkupString("Yolo<br />Bolo");
}
```

### Further technical details
dotnet: 5.0.202

**Comment by javiercn** [comment]
@MihaMarkic thanks for contacting us.

This is likely an issue in the compiler not treating Nullable<MarkupString> correctly. I'm not sure why you think you need to type it that way. I would suggest you check against `default` if you need to do any comparison instead of making it Nullable.

**Comment by MihaMarkic** [comment]
@javiercn If I use default then I loose nullable reference help from compiler. But yes, there are plenty of workarounds, I was merely pointing to a bug which might confuse the developer.

**Comment by SteveSandersonMS** [comment]
Should be just a matter of adding an extra overload for this content type in RenderTreeBuilder. If anyone is interested in doing a PR it might be relatively easy.

**Comment by bhupinderr8** [comment]
I can take this issue. Look like we just need to add the nullable overload of this method
`public void AddContent(int sequence, MarkupString markupContent)`
