### ISSUE TITLE
Invalid nullability annotation on HttpRequest.ContentType

### ISSUE THREAD

**Issue by bart-degreed** [dotnet/aspnetcore#32097]
After updating my Web API project from .NET Core 3.1 to .NET 5, I'm getting a warning along the lines of "variable is never null".

```c#
var contentType = httpContext.Request.ContentType;

if (contentType != null && contentType != allowedContentType)
{
// ^^^^^^^^^^^^^
}
```

The warning is incorrect, because when I remove the null check, lots of my integration tests start to fail. Specifically, the ones where no Content-Type header is sent in the request.

This makes me believe the [HttpRequest.ContentType](https://github.com/dotnet/aspnetcore/blob/f37fa30683a92d83297434103a43b3d46aaa93a9/src/Http/Http.Abstractions/src/HttpRequest.cs#L99) property type should be `string?` instead of `string`.

**Comment by BrennanConroy** [comment]
Good catch thanks! Interested in contributing a change for this?

**Comment by bart-degreed** [comment]
Thanks for the offer, but I'd be happy to give someone else the opportunity to take this.

**Comment by KellenCarl** [comment]
I'm interested in contributing.  This would be my first non-doc contribution.  If you and/or other reviewers don't mind helping me through the process, I'd be more than happy to do the "leg-work."  Just let me know what needs to be done, and I can give it my best.  I've read the contribution guidelines code of conduct.

Are you looking to just have the "?" added to the HttpRequest.ContentType to make the type nullable, and run a unit test for both type string and null?

**Comment by BrennanConroy** [comment]
> Are you looking to just have the "?" added to the HttpRequest.ContentType to make the type nullable

Yep! The trick with changing APIs is that we need to update the baseline files. You can read about that at https://github.com/dotnet/aspnetcore/blob/main/docs/APIBaselines.md#updated-apis. Essentially a `*REMOVED*some.api` and `some.api?` will be added to the unshipped.txt file.

Another thing with updating nullability on an API is that it can affect other code that might be using the changed API and didn't expect the property to ever be null. Fortunately the PR builds will find any of those, but building a couple projects locally can help find some of those quicker so there is less PR churn 😃 

> run a unit test for both type string and null?

Don't think that's needed for this change, we're not changing any behavior or adding new code, but good thought 👍

**Comment by KellenCarl** [comment]
Ok.  Sounds good.  I'll start taking a look into this.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/444#issuecomment-828841450

**Comment by bart-degreed** [comment]
Thanks for the fix! Which release will include it?

**Comment by Tratcher** [comment]
6.0-preview5. since this is an api change it's not something we can backport.
