### ISSUE TITLE
IdentityServer future and alternatives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32109]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IdentityServer-future-and-alternatives/1402270)._

---
[severity:It's more difficult to complete my work]
Hello,
these solutions seem to efemeral. What is the recomended approach to use if I need to implement OpenID Connect server with Blazor administration UI now and need an open source components in ASP.NET Core with .NET >= 5?

- IdentityServer4 fades away in 2022
- IdentityServer5 is not free
- There are other open source options
  - OpenIddict
  - SimpleIdServer
  - ...?

Is there any Blazor UI administration available for any OpenID Connect open source server usable beyond 2022?

I think that Microsoft should come with and maintain such solution as part of ASP.NET Core or Blazor.
Is it planned or at least somethink similar?

Thank You

Marek Ištvánek

---
#### Feedback Bot on 4/19/2021, 11:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
A slight correction - IdentityServer 5 is open source and [still free](https://leastprivilege.com/2020/10/01/the-future-of-identityserver/) if you are open source.

.NET Core and .NET 5 have never provided administration UIs, and there are no plans to do so.
