### ISSUE TITLE
Blazor Custom EventHandler

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#32100]
.Net 5.0 / Blazor WSAM / SDK 5.0.202 x64

I made a tooltip component with Blazor WASM.
it requires event not supported with Blazor.

So I declared custom event handlers:
```csharp
[EventHandler("onmouseenter", typeof(EventArgs), true, true)]
[EventHandler("onmouseleave", typeof(EventArgs), true, true)]
public static class EventHandlers
{
}
```
It works fine but things getting harder when making an RCL.

if custom events aren't in the RCL the RCL doesn't work properly.
but if event are declared in RCL and in the main project it doesn't work too, there is an error for duplicate declaration.
Is it possible to bypass the double event declaration, or isolate it to their respective project or making RCL using event declaration from the project?

Thanks.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

I believe we explicitly don't support overriding custom events. You can "override" this event by creating your alternative custom event that targets the same original DOM event.

**Comment by JulienM28** [comment]
This solution is only possible with .Net 6 with the new custom event register function ?

**Comment by javiercn** [comment]
Yep, this requires 6.0
