### ISSUE TITLE
[Blazor] SIMD easy.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#32101]
Webassembly already implements SIMD API and blazor runs on webassembly can benefits for this and should.
Let's make blazor applications able to use SIMD and easily.
Unless we already have this feature.

**Comment by gfoidl** [comment]
https://github.com/dotnet/runtime/issues/51709 for the runtime-counterpart.

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is a runtime feature, tracked by the issue referenced by @gfoidl. I recommend upvoting the issue there to show interest. We will be closing this issue since it should naturally be exposed to Blazor once the runtime offers support for it.
