### ISSUE TITLE
Blazor (Razor component ) throw errors of non existence while it really exist, this happened after 30 minutes of work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32108]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Razor-component--throw-errors-o/1405790)._

---
[severity:It's more difficult to complete my work]
Blazor (Razor component ) throw errors of not found while it really exist, this happened after 30 minutes of work

---
#### Feedback Bot on 4/22/2021, 07:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear how you're experiencing this issue and when. Can you please share more details about your scenario as well as a repro project?
