### ISSUE TITLE
ASP.NET Core Identity {Failed : DuplicateRoleName} when saving role with Georgian (ka_GE) utf8 characters

### ISSUE THREAD

**Issue by alexejibishvili** [dotnet/aspnetcore#32102]
I'm trying to create roles using `RoleManager<ApplicationRole> _roleManager.`
`ApplicationRole` is a class which derives from `IdentityRole` of course.

When I create first role, everything is OK.
Provided role name of the first one consists of Georgian (ka_GE) alphabetical symbols.
No errors at this step.

**PROBLEM**: When I try to create second role even with different name, but again with Georgian alphabetical symbols, 
`{Failed : DuplicateRoleName}` error is returned after running await `_roleManager.CreateAsync(input)`.

Seems like a bug to me.
It happens only for Georgian symbols, not Russian or English.

Environment:

Microsoft Visual Studio Enterprise 2019
Version 16.9.1
VisualStudio.16.Release/16.9.1+31105.61
Microsoft .NET Framework
Version 4.8.04084

OS Name	Microsoft Windows 10 Home Single Language
Version	10.0.19042 Build 19042

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

**Comment by blowdart** [comment]
Role (and usernames) get normalized, to stop impersonation based on unicode characters looking like ascii characters, so you may be hitting that.

What are the two role names you're trying to create?

**Comment by alexejibishvili** [comment]
I'm trying to create 2 roles for example:
Administrator - ადმინისტრატორი
Manager - მენეჯერი

These Georgian names are completely different from each other. Their normalized names are different too.
Inserting the first one goes without any problems. Name = ადმინისტრატორი (Administrator)
In database table I can see the record with ordinary "Name" and "NormalizedName".
As soon as I try to create second role Name = მენეჯერი (Manager) there goes the duplicate error.

**Comment by blowdart** [comment]
Thanks, I'll try to replicate. 

You're targeting .NET 5? Can I also get your startup.cs with any secrets removed?

**Comment by alexejibishvili** [comment]
Sure, would you like me to post the code here directly or any other way?

**Comment by alexejibishvili** [comment]
Targeting .NET 5
Here is the code of Startup.cs file: https://dotnetfiddle.net/GjSMFo

**Comment by blowdart** [comment]
@HaoK can you take a look please?

**Comment by HaoK** [comment]
Things appear to be working with the default implementations, perhaps there's something specific in your derived role, see https://github.com/dotnet/aspnetcore/blob/b65922e4105c67837de37ec3fd6705ae165af97e/src/Identity/EntityFrameworkCore/test/EF.InMemory.Test/RoleStoreTest.cs#L55 which passes in our tests.

If you are able to upload a working repro app that demonstrates the problem, I can take a look to see if I can pinpoint the issue for you, but otherwise we won't be able to help
