### ISSUE TITLE
DotNet 6 preview Blazor PWa error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32119]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DotNet-6-preview-Blazor-PWa-error/1403224)._

---
I have created the blazor Webssembly PWA asp.net hosted project in visual studio 2019 16.9.4  .net 6.0.0-preview.3.21201.13  and run the application.

It throws the build error as

The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

---
#### Feedback Bot on 4/20/2021, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/21/2021, 05:06 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please update your VS to the latest preview release and give it a try. Let us know if that doesn't solve your problem.
