### ISSUE TITLE
.razor Development: Basic Development Pegs CPU at 25% For Nearly 10 Seconds After Last Keypress

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32118]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587)._

---
[severity:It's more difficult to complete my work]
This is similar to this issue:
https://developercommunity.visualstudio.com/t/ServiceHubRoslynCodeAnalysisServiceex/1359690

But `ServiceHub.RoslynCodeAnalysisService.exe` is not involved (as much) and takes place specifically in a `.razor` file. 

Please see the attached recording.  Simple addition of attribute to `.razor` component will peg the CPU to 25% usage for 8-10 seconds, where the CPU usage will dip after some time but then spike back to over 25% before idling down to ~10% and then [finally to 1-3%](https://developercommunity.visualstudio.com/t/Constant-Oscillation-of-CPU/1352436).

---
#### DragonSpark on 3/12/2021, 06:49 AM: 

<p>Additional recording here.  It takes 3-4 seconds – sometimes more – for a tag completion to occur on a simple <code>&lt;div&gt;</code> tag.</p>

#### DragonSpark on 3/13/2021, 05:07 AM: 

<p>Another recording here where a simple <code>public</code> qualification of a <code>[Parameter]</code> property will oscillate for ~15 seconds, with the CPU sometimes hitting 35% utilization.  I have seen this go for over 20 seconds but it seems shy when actually trying to record it.</p>

#### Feedback Bot on 3/14/2021, 11:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/15/2021, 06:51 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### DragonSpark on 4/9/2021, 08:34 AM: 

<p>It is not uncommon for my machine to be perpetually pegging between 30-50% while typing during .razor development.  Please send halp. 😛</p>

#### DragonSpark on 4/15/2021, 00:40 AM: 

<p>Here’s another capture with <code>16.10-preview2</code>. Note that the CPU is consistently pegged in the 25-30% range sometimes reaching as high as 40%. For reference/comparison, typing in Notepad++ never goes above .5% in its process. 😛</p>

#### Mike-E on 4/15/2021, 04:59 AM: 

<p>Looks like the issue is a ton of GC calls from executing <code>Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument)</code></p>
<p><img src="https://aka.ms/dc/image?name=Bb0d60ae9be9e4d918a85b8e247ebac78637540846864817637_2c6InX2%5B1%5D.png&amp;tid=b0d60ae9be9e4d918a85b8e247ebac78637540846864817637" alt="2c6InX2[1].png"></p>

#### DragonSpark on 4/16/2021, 00:53 AM: 

<p>Greetings… <a target='_blank' href="https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-preview-2/#comment-24419">according to this comment</a> it would seem an ETL has not been provided for this issue, when I have provided several and in fact provided one with the original issue.  Did you not receive them?  Is this thing working?  Is it on?  Hello?  Hello? 😃</p>

#### DragonSpark on 4/19/2021, 10:03 PM: 

<p>Any chance we can get an update on this ticket, please?</p>

#### DragonSpark on 4/20/2021, 11:26 PM: 

<p>Any update on this issue would be greatly appreciated.  Thank you for any consideration. 🙏</p>

#### Taylor Mullen [MSFT] on 4/21/2021, 11:27 AM: 

<p>Hey <a target='_blank' href="https://developercommunity.visualstudio.com/user/e6b7815f-d503-4e57-ab73-1545c65bf301/profile">DragonSpark</a>, we really appreciate your passion in this area! I’ve dug through your traces and found some problem areas. Stay tuned!</p>

#### DragonSpark on 4/21/2021, 00:47 PM: 

<p>Great!  Thank you so much <a target='_blank' href="https://developercommunity2.visualstudio.com/user/8722b87d-8809-40a4-9bfe-234b2c0d3556/profile">Taylor Mullen [MSFT]</a> for the update.  It really means a lot.  Best of luck with your endeavors out there. 👍</p>

---
### Original Solutions
(no solutions)

**Comment by Mike-E-angelo** [comment]
Doh, that's is disappointing, for sure.  Can someone expound a bit upon the not obvious part?  The dotTrace snapshot I provided showed a lot of GC from `Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument)` which seems to be very much in your framework. :)

Any further insight/explanation would be very much appreciated.  As you might understand, having my IDE constantly churning 20-35% at a bare minimum is not exactly a pleasant experience, especially once ReSharper is added on top of that. 😭

**Comment by Mike-E-angelo** [comment]
Also, shouldn't this be in the https://github.com/dotnet/aspnetcore-tooling repo? The other VisualStudio/razor editor-based issues that I have reported (that were, incidentally, fixed 😁) landed in that repo.  So that would make sense from a 'framework' perspective.

The other issue here is that I am encountering this in 5.0, not 6.0.  The usual apologies if I am misunderstanding how things are run around here. 😇

**Comment by NTaylorMullen** [comment]
> Also, shouldn't this be in the https://github.com/dotnet/aspnetcore-tooling repo? The other VisualStudio/razor editor-based issues that I have reported (that were, incidentally, fixed 😁) landed in that repo. So that would make sense from a 'framework' perspective.
> 
> The other issue here is that I am encountering this in 5.0, not 6.0. The usual apologies if I am misunderstanding how things are run around here. 😇

After looking at your perf results we found that the Razor compiler was where the pain point was occurring. Going to have the Razor compiler team work on a fix 😄

**Comment by Mike-E-angelo** [comment]
Awesome, thank you for the additional context, @NTaylorMullen!  Things are going to be pretty sweet once these last major issues are addressed.  JetBrains are also making improvements on their side so we are trending in the right direction here. 👍

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen do you know where exactly this issue is coming from? Looks like you did look into this a bit. Thanks!

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you know where exactly this issue is coming from? Looks like you did look into this a bit. Thanks!

IIRC it was a combination of a few things. Brief look led me to:

- How the [TagHelperMatchingConventions](https://github.com/dotnet/aspnetcore/blob/974206547cdcb2fc252b537711d790d42c7997e8/src/Razor/Microsoft.AspNetCore.Razor.Language/src/TagHelperMatchingConventions.cs) are used when determining various aspects of Blazor/TagHelper components.
- How [TagHelperBindings](https://github.com/dotnet/aspnetcore/blob/974206547cdcb2fc252b537711d790d42c7997e8/src/Razor/Microsoft.AspNetCore.Razor.Language/src/TagHelperBinder.cs) get created (this drives which TagHelpers power a given component).
- How [component scoping is understood](https://github.com/dotnet/aspnetcore/blob/974206547cdcb2fc252b537711d790d42c7997e8/src/Razor/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorTagHelperBinderPhase.cs#L222). Aka how the compiler determines which Blazor components are applicable depending on the using directives in play for a given Razor file.

One interesting note I recall is that all the above scaled poorly so the bigger the Blazor app the worse the problem.

**Comment by Mike-E-angelo** [comment]
> One interesting note I recall is that all the above scaled poorly so the bigger the Blazor app the worse the problem.

This is my world right now.  I have over 150 .razor files in my solution (also at a high count with 108 projects) and development is nothing but grief on the daily.  I also find that if I add any new `.razor` files I basically have to restart the IDE to get it to a somewhat decent state.  Although I am not entirely sure that does much.  It's to the point that I am about to break open Notepad++ for razor development now.  I am not sure why I haven't already, actually. :P

One more note: my `_Imports.razor` files have a lot of `using` statements in them.  This is throwing R# for a loop (literally 😅😭) in a couple of issues, but not sure if that's also the case here, too, so thought I would mention it.

**Comment by Mike-E-angelo** [comment]
If you all are interested, I have an older version of my solution that I shared with JetBrains that I could also share with you.  I would have to find a good scenario to help highlight this issue, but shouldn't take long. :P

Basically adding new files to the project or doing any sort of refactoring seems/feels to trigger the grief.

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details, @Mike-E-angelo. We'll let you know if there is any additional information we need here.

**Comment by mkArtakMSFT** [comment]
@Mike-E-angelo, did you try to disable ReSharper and see whether that helps?

**Comment by Mike-E-angelo** [comment]
I do that first thing before reporting anything to MSFT, @mkArtakMSFT.  It's how I know if what I am dealing with is a JetBrains or MSFT issue. :)  There are several in both camps around `.razor` development, unfortunately.

**Comment by pranavkm** [comment]
> If you all are interested, I have an older version of my solution that I shared with JetBrains that I could also share with you

@Mike-E-angelo could you share the solution? It would help narrow this down quickly. If you'd like send it as an email attachment, my address is `prkrishn at microsoft dot com`

**Comment by Mike-E-angelo** [comment]
Great!  Thank you all for looking into this.  I sent you the link to the OneDrive file, @pranavkm.  Please check your Spam folder as it seems that's where those always land.  Also please kindly let me know when you have successfully downloaded the file so that I can then invalidate the share.

For some additional reference and context here, from a new instance of the solution and R# suspended, I added a new razor component to `starbeam.one\Pages\Profile\Marketplace\Assets\Component.razor`, and this is what I see:

![](https://i.imgur.com/vSaC7K2.gif)

You can also see #32558 in effect here as well.

Now as mentioned the solution was just opened, so the "burn" only lasts so long.  This issue seems to progress worse and worse the longer the solution is opened and/or the more activity is performed within the IDE.

One recommended activity is to edit `Starbeam.Presentation.Components.ComponentBase.Initialize` so that it has the following signature:

`protected virtual ValueTask Initialize(object parameter)`

This will of course break a lot of files dependent on it, which will require you to subsequently open a lot of files to fix them.  It should be readily apparent during this process the issue here as degradation should be equally as obvious.

Please do let me know if you require any additional information and I will do my best to assist you. 🙏

**Comment by Mike-E-angelo** [comment]
Wow, so I installed `16.11-preview1` and it not only appears that #32558 was addressed (I will need to further verify this), but the churn has been reduced considerably with this issue:

![](https://i.imgur.com/gyeSliU.gif)

It appears the duration is about 8 seconds now, with a max CPU utilization of ~15-16%.  What's interesting is that it will shoot up to 8-10%, down to 1.5%, and then back up to ~16% during this time.  Looks like this is due to the `ServiceHub.RoslynCodeAnalysisService.exe` kicking in after some time.

**Comment by pranavkm** [comment]
That's interesting. I know @NTaylorMullen has been working on some perf improvements in the tooling space, so perhaps one of those changes helps here. I have been investigating the hot parser code paths and there's some easy optimizations we can make here. Perhaps that would help this further. In the meanwhile, I've grabbed a copy of your solution, so feel free to purge it.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you have an estimate for what VS release @Mike-E-angelo might see some of the changes (e.g. #33013)?

17.0-Preview2

**Comment by Mike-E-angelo** [comment]
OK great, thank you all once again for your efforts out there!  I will patiently wait for `17.0-preview2` and update you here with any further comments.  Hopefully positive ones. 😁🤞
