### ISSUE TITLE
Add better certificate configuration support to WebApplication

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#32124]
### Is your feature request related to a problem? Please describe.

Today if you want to configure a TLS certificate for the host in code, you have to configure Kestrel directly using `WebApplicationBuilder.WebHost.ConfigureKestrel(...)`. Kestrel is the only server we ship that supports runtime configuration of certificates currently, but it would be nice to have a way to configure the certifcate(s) to be used by any `IServer` capable of using them.

It would also be nice if you could configure TLS certificates with just the `WebApplication` like you can for `Urls`. Certificates can be configured per-endpoint in Kestrel (and even per-server-name using SNI), but associating certificates with endpoints and server names could prove complicated. This is especially true with the multiple places in both code and config you can define Kestrel endpoints. However, maybe we could support this for all endpoints with a known URL.

To support this in a way that is testable and could at least theoretically work with other `IServers` we should add a server feature interface. `IServerAddressesFeature` is the only other server feature that I know of in wide use.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like

I'm still not sure I like this, but here's one possibility:

```diff
namespace Microsoft.AspNetCore.Builder
{
    public class WebApplication
    {
+        public X509Certificate2? Certificate { get; set; }
+        public void LoadPfxCertificate(string pfxPath, string? password = null);
+        public void LoadPemCertificate(string pemPath, string keyPath, string? password = null);

           // Review: Do we need special helpers for store? Or is setting the X509Certificate2 easy enough?
           // Borrows signatures from existing UseHttps overloads.
+        public void LoadStoreCertificate(StoreName storeName, string subject);
+        public void LoadStoreCertificate(StoreName storeName, string subject, bool allowInvalid);
+        public void LoadStoreCertificate(StoreName storeName, string subject, bool allowInvalid, StoreLocation location);
```

```diff
namespace Microsoft.AspNetCore.Hosting.Server.Features
{
+    public interface IDefaultServerCertificateFeature
+    {
+        X509Certificate2? DefaultCertificate { get; set; }
+    }
```

The idea is this would basically override the default/dev cert, but certificates configured for a specific Kestrel endpoint would be preferred.

## Usage Examples

```c#
using var app = WebApplication.Create(args);

// Load cert from file in content root using password from user secrets.
app.LoadPemCertificate("cert.pem", "cert.key", app.Configuration["Cert:Password"]);

app.Run("https://example.org");
```

### Additional context

What I don't like about this proposal is that it's yet another possible source for default certificates. We will have to make sure the prioritization of these sources is clear as possible, but adding more sources can only make clarifying this harder.

@Tratcher @davidfowl

**Comment by davidfowl** [comment]
> I also think that loading a cert from a .pfx file in the content root directory will be unnecessarily difficult if we only have a X509Certificate2 property. Maybe we need to also add methods that take strings for the relative path and password.

These should be factory methods on WebApplication and the feature should be as you have it. That solves the problem where the `WebApplication` knows the content root so the user doesn't need to resolve it.

```diff
public class WebApplication
{
+    void UseCertificate(string pfx);
+    void UseCertificate(string pemFile, string keyFile);
+    void UseCertificate(X509Certificate2 certificate);
}
```

```C#
var app = WebApplication.Create();

app.UseCertificate("cert.pfx"); // Relative to content root

app.MapGet("/", (Func<HttpContext, string>)(context => $"Current scheme is {context.Request.Scheme}"));

app.Run(); 
```

With pem

```C#
var app = WebApplication.Create();

app.UseCertificate("cert.pem", "key.pem"); // Relative to content root

app.MapGet("/", (Func<HttpContext, string>)(context => $"Current scheme is {context.Request.Scheme}"));

app.Run(); 
```

With pfx file

```C#
var app = WebApplication.Create();

var cert = new X509Certificate2(Convert.FromBase64String(app.Configuration["Cert"]));

app.UseCertificate(cert);

app.MapGet("/", (Func<HttpContext, string>)(context => $"Current scheme is {context.Request.Scheme}"));

app.Run(); 
```

**Comment by Tratcher** [comment]
If IDefaultServerCertificateFeature is the source of truth, do these need to be first class methods on WebApplication? Or can they be extension methods on IApplicationBuilder? It would make them accessible to a broader audience.

IDefaultServerCertificateFeature must be supplied by the server, correct? What do these APIs do if the feature is absent (e.g. HttpSys or IIS)? Throw NotSupportedException?

`Certificate` should be a method rather than a property for two reasons:
A) It's disassociated from the useful methods for loading the certificate, from the property it's hard to discover the Load methods.
B) retrieving the value isn't necessary, they only need to provide one.

A more consistent approach would be:
```
+        public void UseCertificate(X509Certificate2 cert);
+        public void UseCertificatePfx(string pfxPath, string? password = null);
...
```

> // Review: Do we need special helpers for store?

Can you show a one line way to retrieve the cert from the store without these?

**Comment by davidfowl** [comment]
In case I can't make it to API review tomorrow:
- I don't like Use because this type already conflates middleware configuration and routing configuration (on purpose).
- We should avoid new top level Use/Run/Map that don't relate to middleware. If we like the term use, we might want to hang it off something else (similar to how we have WebHost and Host hanging off the builder)
- We might want to make this work for existing ASP.NET Core applications. Should this hang off the IWebHostBuilder as well?

**Comment by pranavkm** [comment]
```diff
namespace Microsoft.AspNetCore.Builder
{
    public class WebApplication
    {
+        public X509Certificate2? Certificate { get; set; }
    }
```

```diff
namespace Microsoft.AspNetCore.Hosting.Server.Features
{
+    public interface IDefaultServerCertificateFeature
+    {
+        X509Certificate2? DefaultCertificate { get; set; }
+    }
```

Currently approved API. @halter73 is going to speak to @javiercn about certificate loading APIs.
