### ISSUE TITLE
Razor compliance work

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#32138]
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317738
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317737
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317741
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317740
- [x] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317739

**Comment by ryanbrandenburg** [comment]
I'll take the first one.

**Comment by NTaylorMullen** [comment]
Checking all the issues they all seem to be closed out now (in addition to offline shared queries). Holy hell @davidwengier ❤️ ❤️ ❤️, really appreciate all the assistance here, boss status!
