### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource with computed SHA-256 integrity. The resource has been blocked.

### ISSUE THREAD

**Issue by Tailslide** [dotnet/aspnetcore#32130]
### Describe the bug
Blazor Webassembly never updates through serviceworker .. reports integrity errors on updated file because it is trying to use an old version of the file from disk cache.  I verified the file on the server is the updated version, and when I look at the response to the loads in the network view they say 'disk cache' and they contain the old version of the file. I followed all the instructions in the Microsoft documentation step by step. Is this by design?  Do I need to prevent caching in order to use serviceworker? 

### To Reproduce
Publish PWA webassembly with default service worker code.. load site. Exit browser entirely and publish update to some css file on azure windows appservice. Load up site in browser and it will report integrity errors trying to update.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/5757188/115953344-1f359b80-a4a8-11eb-94ef-2c973d2d3c71.png)

![image](https://user-images.githubusercontent.com/5757188/115953331-0d53f880-a4a8-11eb-8feb-7f248f6bddb3.png)

### Further technical details
- ASP.NET Core version Razor (ASP.NET Core)   16.1.0.2120507+b9076c2c2098fb1f4bac21342cff9a07bcbbc277
- Include the output of `dotnet --info`
- .NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21180.15
 Commit:    19ce2535ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS 16.10.0 Preview 2.1

**Comment by javiercn** [comment]
@Tailslide thanks for contacting us.

Try https://github.com/dotnet/aspnetcore/pull/32015/files#diff-d34587ee763cd9cccf1c08b5e21c1f2e857225d106c70088453e1c6365b99411R21

**Comment by Tailslide** [comment]
@javiercn Thank you so much this solved my issues.   On iOS Safari I actually had to delete the bookmark from the home screen and re-bookmark it before it would start taking updates.   I don't think PWA is very functional without this change.

For reference there is more discussion here:
https://github.com/dotnet/aspnetcore/issues/31467
