### ISSUE TITLE
Passing an object(cyclic) as parameter to a Razor component via the component tag helper throws JsonException 

### ISSUE THREAD

**Issue by amal-stack** [dotnet/aspnetcore#32150]
### To Reproduce
I have created a new project to reproduce the problem: [JsonExceptionRepro](https://github.com/amal-stack/JsonExceptionRepro). 

The project has been created using the ASP.NET Core MVC template. 
To add support for Razor components, I have:
- Added `services.AddServerSideBlazor()` in `ConfigureServices()`
- Added `endpoints.MapBlazorHub()` in `Configure()`.
- Added `<base href="~/">` in the head section of `_Layout.cshtml` and also added a script reference to `blazor.server.js`.

In the `Models` folder, I have created two classes with cyclic dependencies. This is a common practice to add navigation properties in EF Core. :
```
class Question { ... List<Answer> Answers { get; set; } }
```
```
class Answer { ... Question Question { get; set; } }
```

In `Controllers/HomeController`, I have added two actions `ThisWillWork()` and `ThisWillNotWork()` to demonstrate how having the inner property set causes the exception. 

#### What I have tried
I tried adding the following to `Startup.cs`:
```
services.AddControllersWithViews()
                .AddJsonOptions(options => options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve); 
```
This probably is not affecting the component.

The only solution I could think of is to pass only the object's ID as parameter to the component and use the DB Context in the component's code section to look up the object. I have asked a related question on StackOverflow but I didn't get any help yet: [Is it safe to inject the DbContext service into a Razor component of an ASP.NET Core project?](https://stackoverflow.com/questions/67232177/is-it-safe-to-inject-the-dbcontext-service-into-a-razor-component-of-an-asp-net?noredirect=1#comment118849095_67232177)

### Exceptions (if any)
> JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.

### Further technical details
- ASP.NET Core version
5.0.5
- Include the output of `dotnet --info`
```
PS %USERPROFILE%\OneDrive\Documents\las\KSD.ModelCollege.LearningAssessmentSystem> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Community 2019
Version 16.9.3

**Comment by javiercn** [comment]
@amal-stack thanks for contacting us.

We only support serializing acyclical graphs of objects. That is by design.
