### ISSUE TITLE
Localization and third party libraries in Razor Class Library

### ISSUE THREAD

**Issue by TO-sullah** [dotnet/aspnetcore#32151]
### Can we use MudBlazor/UI libraries or Localization in Razor Class library?

I'm trying to create a Razor class library to hold all the common components. But the problem I'm facing is that I use MudBlazor and localization in my components, and apparently there's no way to add/configure them in my RCL. 

Is there any other way to make use of the localization and 3rd party libraries in a Razor class library? If not, maybe there should be a way to add 3rd party libraries into the RCL.

Please forgive me if this a straightforward issue with a simple answer.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please clarify what do you mean by "add 3rd party libraries into the RCL" ?

**Comment by danroth27** [comment]
Hi @TO-sullah. To add third party components to your Razor class library you should be able to just add a package reference to MudBlazor. Are you having issues with that? If yes, what sort of problems are you hitting?

For localization, are you trying to use localized resource from MudBlazor in your own library? Assuming yes, can you share with us how you're trying to do that and what sort of issues you're hitting?

**Comment by danroth27** [comment]
Note that you can find docs on how localization works in Blaozr here: https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization
