### ISSUE TITLE
MinmalActionEndpointRouteBuilderExtensions typo

### ISSUE THREAD

**Issue by dodyg** [dotnet/aspnetcore#32169]
https://github.com/dotnet/aspnetcore/blob/76d5c625ec702ee7a4a642b52b7ecfd8fc435338/src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs#L17

**Comment by mkArtakMSFT** [comment]
Thanks for filing this issue. Looks like @careless6666 has fixed this already.

Thank you, @careless6666!
