### ISSUE TITLE
[Blazor] Detecting which parameters have changed

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#32163]
Hi,

I am looking at an efficient way to optimize redundant rendering of complex reusable components (e.g. grid).

Here's a rough draft of the approach that I'm considering:

```csharp
        protected bool m_shouldRender = false;

        protected override void OnParametersSet()
        {
            if (PrimitiveDataTypeParametersChanged() || ReferenceParametersChanged())
            {
                m_shouldRender = true;
            }
        }

        protected override bool ShouldRender()
        {
            if (m_shouldRender == true)
            {
                m_shouldRender = false;
                return true;
            }

            return false;
        }
```

The idea is that the component will be rendered only if any of the parameter values have changed. According to https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#avoid-unnecessary-rendering-of-component-subtrees guidance, the framework is already detecting ``PrimitiveDataTypeParametersChanged`` condition - if a component consists only of primitive data type parameters that have not changed, ``OnParametersSet`` is not called to begin with.

I want to avoid declaring a member field for each parameter to track if it has changed - this is an error prone approach and makes the code look rather cumbersome. Another approach is to use reflection to list all parameter properties and store their values in a dictionary - but it does require some additional CPU cycles that I'd like to avoid - clearly Blazor must be doing something similar internally that I'd like to take advantage of. Is this possible? If not, can you show me the lines in source code that perform this check?

With respect to complex data types (references), I'm OK with storing their previous values internally. Consumers of my components will understand that if any of the properties of reference parameters change, they will need to call a public ``Render`` method that will then call ``StateHasChanged``. Practically speaking, this will only be needed in scenarios such as adding a new row to a grid that is not bound to ``ObservableCollection`` - it's an inconvenience that I'm willing to accept.

I would really prefer not to even bother with this approach, but as various tickets indicate, unnecessary rendering of components is a problem.

Thank you for your help.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

The problem with your approach is that you can't tell when a reference parameter has not changed based solely on reference equality, since it's values might have mutated.

**Comment by daniel-p-tech** [comment]
@javiercn sorry if I did not clearly phrase what I'm after.

I'm OK with not automatically rendering the component if its reference parameter values' have mutated. Users will understand that in such a rare circumstance they will be required to explicitly call ``Render`` method to request update.

What I'm really asking is simple:
How can I easily detect which primitive data type parameters have changed without writing my own mechanism? Blazor must be doing this already somewhere. At the very least, can you show me the code where this is done?

Thanks.
