### ISSUE TITLE
Blazor Server App not loading on IIS Properly

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/aspnetcore#32176]
Greetings all!

I've been struggling with this blazor issue for a couple of days. This is .net core 6, preview 3.

All of my API only code works fine (.net core 6, preview 3, no blazor code)

But when I would try and load my published blazor server app, the UI (static non blazor css, html, etc) all load fine, but nothing within the <app> tags is rendering.

So, I tried the basic "counter" out of the box app, and ran into the same issue.

The strange thing is, if I run it via the dotnet command line, it loads fine on localhost:5000, but the published version does not.

You can see a live example here: http://testblazorapp.bscapps.ca/counter

The "click me" button does nothing - and, if you view source, you'll see that the "blazor" tag is missing:

`<div class="page" b-423lnt6p6c><div class="sidebar" b-423lnt6p6c><div class="top-row pl-4 navbar navbar-dark" b-pugcpcs91u><a class="navbar-brand" href b-pugcpcs91u>TestBlazorApp</a>
-->`

That renders on my localhost in the *same code base* as the URL I provided above - so - what could it be with IIS that is different than dotnet run, and, keeping in mind all of my other .net core stuff works fine - no app loading issues, etc, just that tag is missing across any blazor server app I try and load on IIS.

It's IIS8 on windows server 2012 with the SDK and hosting bundle installed for asp.net core 6 preview 3.

thank you.

**Comment by javiercn** [comment]
@caliberdigitalllc thanks for contacting us.

Are you using a CDN like cloudflare or similar to process/minify the HTML? If so, add something like the following to the response

```
if (!context.Response.HasStarted)
{
    context.Response.Headers[HeaderNames.CacheControl] = "no-cache, no-store, no-transform, max-age=0";
}
```

**Comment by caliberdigitalllc** [comment]
@javiercn that was 100% the problem. I just googled "blazor through cloudflare" and instantly came to this article: https://zimmergren.net/solved-asp-net-core-blazor-web-sites-does-not-work-with-cloudflare-html-minification/

There's like 8 hours wasted - I never once suspected CF.

thanks!!
