### ISSUE TITLE
Dynamic Disabled HTML Element Using HTMLHelpers

### ISSUE THREAD

**Issue by kculpepperhpc** [dotnet/aspnetcore#32183]
Something that has plagued me since the inception of Razor views has been HTML Helpers and Tag Helpers.  The concept is fantastic, but the implementation has bin a bit lackluster.  One of the issues I have with them is that in our enterprise application, we need the ability to be able to dynamically make a field _(not an entire form)_ disabled.  There are a couple of scenarios that we have where this is necessary and one of them is authorization.  If the user is authorized to modify another user's submission of some sort, the field will not be disabled.  If the user does have authority to modify someone else's submission, the disabled attribute should not be present.  

Can anyone explain or send a link to a description on how to make this happen?  In previous versions of Core, one could dynamically set the attributes using an extension, but I cannot find any documentation of that nor can I make it work from fiddling around with it.  I would like to create some sort of extension method that you pass in a bool that would mark the HTML editor as disabled if true or false.  For instance:

`<input asp-for="AssetName" class="form-control required" data-lpignore="true" asp-disabled="@User.HasOverride()" />`

or

`@Html.EditorFor(model => model.AssetName, new { @class = "form-control", data_lpignore = "true" }).Disabled(User.HasOverride())`

Can someone point me in the right direction?

**Comment by javiercn** [comment]
@kculpepperhpc thanks for contacting us.

With tag helpers you don't need to use anything like `asp-disabled (unless you want to build a custom tag helper). You can just say `disabled="@(User.HasOverride())"` and that should work

**Comment by kculpepperhpc** [comment]
Unfortunately, disabled is a default-present attribute and if it's present, it disables the control, no matter the value (true,false,yes,no,please,etc.)

**Comment by kculpepperhpc** [comment]
Apologies.  You were correct.  Not sure what voodoo .NET magic runs behind the scenes, but it took my boolean return value and enables or disables the input.  Thank you for the answer.
