### ISSUE TITLE
Support Hot-Reload for Referenced Projects

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/aspnetcore#32181]
### Is your feature request related to a problem? Please describe.
In our setup we develop blazor pages and components in one project and have a separate project to host a local dev server. When using hot-reload the whole project is being rebuilt when we make changes to components in the referenced project.

### Describe the solution you'd like
Hot reload works the same for referenced projects as it does for the main project. Source is available since it sits right next to it.

### Additional Context
All projects are part of the same solution

**Comment by pranavkm** [comment]
@Blackclaws could you share a minimal app that reproduces the issue? dotnet-watch should already support this unless you have watching explicitly disabled. For instance, the blazor-hosted template includes 3 projects and we support editing and hot reloading all of the projects during a hot reload session.

**Comment by Blackclaws** [comment]
Ok, trying to make a minimal example has tought me quite a few things about the hot-reloading feature as it stands right now. 

You are correct that it indeed _does_ work for referenced projects. I've found a couple of other bugs however that explain the behavior I have seen and will open those separately.
