### ISSUE TITLE
Blazor chat sample, loading issues,  some files  404 and some 404 + Failed to find a valid digest in the 'integrity'

### ISSUE THREAD

**Issue by sajrashid** [dotnet/aspnetcore#32192]
### **Blazor chat sample, loading issues,  some files 404 Failed to find a valid digest in the 'integrity' , files exist on disk**

- **Loads** `/_framework/blazor.webassembly.js (HTTP 200)`
- **upto** `/_framework/dotnet.5.0.4.js (HTTP 200)`

**all subsequent  files  starting from...**

- `/_framework/Microsoft.AspNetCore.Authorization.dll`
- **fail with` HTTP 404`** 

![image](https://user-images.githubusercontent.com/6164594/116147064-28587f80-a6d7-11eb-96a7-933f7332cd05.png)

debug mode 
![image](https://user-images.githubusercontent.com/6164594/116148126-6a35f580-a6d8-11eb-8179-0cec6ec24447.png)

```
:44300/_framework/Microsoft.AspNetCore.Authorization.dll:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to find a valid digest in the 'integrity' attribute for resource '<URL>' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.
```

**Folder**

`\BlazorSignalR.Client\bin\Debug\net5.0\wwwroot\_framework `

**Contains correct files including** Microsoft.AspNetCore.Authorization.dll

![image](https://user-images.githubusercontent.com/6164594/116142687-1f18e400-a6d2-11eb-9d22-209b4e506f39.png)

```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21180.15
 Commit:    19ce2535ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.114 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

_Same issue from VS or VS code_

**Some of the console output**
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Client.Core.dll - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Client.Core.dll - - - 404 0 - 0.2855ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Common.dll 
- -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Common.dll 
- - - 404 0 - 0.2078ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Protocols.Json.dll - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.AspNetCore.SignalR.Protocols.Json.dll - - - 404 0 - 0.2279ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.Extensions.Configuration.dll - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:44300/_framework/Microsoft.Extensions.Configuration.dll - - - 404 0 - 0.2159ms
ework/Microsoft.Extensions.FileSystemGlobbing.dll - -
```

**Output from fiddler**

![image](https://user-images.githubusercontent.com/6164594/116141571-c1d06300-a6d0-11eb-855a-8a4551cef86e.png)

Headers from the first 404
![image](https://user-images.githubusercontent.com/6164594/116145077-baab5400-a6d4-11eb-94af-4ca10770af57.png)
![image](https://user-images.githubusercontent.com/6164594/116145123-cb5bca00-a6d4-11eb-97d0-1c787feeaa3d.png)

**looked at** [https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures](url)

above article if i've followed it correctly points to a server side issue and mentions to look at the logs, apart from the 404 there doesn't seem to be anything to indicate why,  here's output from the server side app 

IIS Express log
`#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2021-04-26 21:17:51
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2021-04-26 21:17:51 ::1 GET / - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 - 304 0 0 3011
2021-04-26 21:17:51 ::1 GET /BlazorSignalR.Client.styles.css - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 http://localhost:44300/ 200 0 0 36
2021-04-26 21:17:51 ::1 GET /_framework/blazor.boot.json - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 http://localhost:44300/ 200 0 0 26
2021-04-26 21:17:51 ::1 GET /_framework/Microsoft.AspNetCore.Components.Web.dll - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 http://localhost:44300/ 404 0 0 55
2021-04-26 21:17:51 ::1 GET /_framework/Microsoft.AspNetCore.Components.Forms.dll - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 http://localhost:44300/ 404 0 0 58
2021-04-26 21:17:51 ::1 GET /_framework/Microsoft.AspNetCore.Authorization.dll - 44300 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/90.0.4430.85+Safari/537.36 http://localhost:44300/ 404 0 0 70`

_Hmmm any ideas on what can I try next ?_

Thanks for looking

**Comment by sajrashid** [comment]
I have tried 
   
  <BlazorCacheBootResources>false</BlazorCacheBootResources>

seems to be the same

**Comment by javiercn** [comment]
@sajrashid thanks for contacting us.

We recommend you use the following script [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#troubleshoot-integrity-powershell-script) (requires a recent version of powershell core) as a starting point to troubleshoot what can be going badly.

In your specific case, I would try first removing the bin and obj folders from the solution and performing a clean build/publish to see if that fixes the issue.

**Comment by sajrashid** [comment]
Hi, thanks for getting back to me, i rebuilt the project and everything works.

Closure Code:Gremlins.

Thanks you & have a lovely day

**Comment by sajrashid** [comment]
Closure Code:Gremlins
