### ISSUE TITLE
'System.IO.InvalidDataException' in Microsoft.AspNetCore.SignalR.Protocols.Json.dll

### ISSUE THREAD

**Issue by drfbwilliams** [dotnet/aspnetcore#32195]
### Describe the bug
The title is the exact error message

After working through the absolute nightmare of documentation (or lack thereof) - finally getting a function to run locally that negotiates correctly, then invoking a simple function to push through a test message and all I get are the exceptions below.

The negotiation returns URL and Token for local correctly.

The functions I am invoking is:

```
[FunctionName("negotiate")]
        public static SignalRConnectionInfo Negotiate(
            [HttpTrigger(AuthorizationLevel.Anonymous)] HttpRequest req,
            [SignalRConnectionInfo(HubName = "test")] SignalRConnectionInfo connectionInfo)
        {
            return connectionInfo;
        }


        [FunctionName("SendMessage")]
        public static Task SendMessage(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "test")] IAsyncCollector<SignalRMessage> signalRMessages)
        {
            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    Target = "newMessage",
                    Arguments = new[] { message }
                });
        }
```

My .net core 3.1 solution is creating and starting the hubconnectionbuilder without issue.

I have the following simple 'on' handler:

```
var testMessage = string.Empty;
            hubConnection.On<string>("newMessage", (res) => {
                testMessage = res;
            });
```

Can someone please help me resolve this.

versions of pkgs:

In the function project:

`    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.3.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Text.Encodings.Web" Version="5.0.1" />`

In the web project:

` <PackageReference Include="Microsoft.AspNetCore.Http.Connections.Client" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Text.Encodings.Web" Version="5.0.1" />`

### Exceptions (if any)

Exception thrown: 'System.InvalidOperationException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.IO.InvalidDataException' in Microsoft.AspNetCore.SignalR.Protocols.Json.dll

### Further technical details
- ASP.NET Core version - 3.1
-VS 2019

**Comment by BrennanConroy** [comment]
Where are you getting the exception? On the server side or the functions side?

Can you share the exception message and full stack trace of the exception?

Also, we noticed the `.On` accepts a string, but you're passing around an `object` which can cause issues.

**Comment by drfbwilliams** [comment]
@BrennanConroy  Thanks for the response - most appreciated.

After counting sheep for a few hours, and reading your response - I noticed your last comment.

Indeed - this is the source of the issue. 

I assume this is a bug listed somewhere? My assumption (clearly incorrectly) was that a serialised string would push back over the wire regardless - it appears System.Text.Json is unable to deal with that, and as you correctly point out, changing the 'on' to <object> results in a small win.

Beer for you.
