### ISSUE TITLE
Blazor Form API should expose a caller id on Submit

### ISSUE THREAD

**Issue by gcerik** [dotnet/aspnetcore#32202]
## Background and Motivation

The Submit events in EditForm do get triggered for multiple events, e.g. on blur, submit or cancel but in the the Submit callbacks, there is no way to know why the Submit event was triggered.

The suggested change below just adds a property to the EditContext to indicate the trigger for the form.

## Proposed API

public sealed class EditContext

### Properties

**SubmitEvent** Gets the id of the button used to submit the form (e.g. submit) or the id of the event that triggered the submission.  Even can be 'submit', 'onblur', 'button'

## Usage Examples

```cs
    private async Task HandleSubmit(EditContext editContext)
    {
        var isSubmitButton = editContext.SubmitEvent == 'submit';

        if (!isSubmitButton )
        {
            ... //roll back changes
        }
        else
        {
            ... // save changes
        }
    }
```
## Alternative Designs

Any way to get the trigger for the submit would enable to rollback changes when the form has not been submitted using the submit button.

**Comment by SteveSandersonMS** [comment]
> The Submit events in EditForm do get triggered for multiple events, e.g. on blur, submit or cancel

Could you clarify this? Can you give a small code sample showing how a `blur` event could lead to a "submit" callback? Then we can be sure we have the same understanding of what's being requested here.

**Comment by gcerik** [comment]
@SteveSandersonMS Here is a an example to demonstrate the need for the SubmitEvent. There are two buttons on the form and there is no way from the second button (that doesn't have the submit type) to prevent a submit. 

Within the submit method, there doesn't seem to be a way to know which button did trigger the event. https://github.com/nabeelbader/FormSubmissionEvents

**Comment by mrpmorris** [comment]
Did you try 
type="button"

**Comment by nabeelbader** [comment]
> Did you try
> type="button"

This does indeed work, but it seems restrictive to not be able to use the Button component

**Comment by mrpmorris** [comment]
It's standard HTML. Buttons are considered Submit when inside a <form> unless explicitly specified otherwise.

**Comment by mkArtakMSFT** [comment]
Thanks @mrpmorris.

Looks like there are no more remaining work here for us to do - not pressing one, at least.
I wonder if some of this is also addressed by the new `formname` attribute that was introduced in .NET 8? @gcerik what do you think?

**Comment by mkArtakMSFT** [comment]
Turns out `formname` doesn't help here.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
