### ISSUE TITLE
Blazorwasm hot-reload silently breaks if packages are not up to date

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/aspnetcore#32209]
### Describe the bug
dotnet watch will accept hot-reloading of blazorwasm projects even if the packages

- Microsoft.AspNetCore.Components.WebAssembly

are not at a version where they support hot-reloading. 

This is probably expected behaviour, however dotnet watch should probably display a warning/error when the packages do not support hot-reloading. This is especially relevant when upgrading existing projects to use hot-reloading.

### To Reproduce
1. dotnet new blazorwasm
2. Downgrade package Microsoft.AspNetCore.Components.WebAssembly to 5.0.5
3. Add "hotReloadingProfile": "blazorwasm" to launchSettings
4. dotnet watch
5. Wait for reload socket to connect
6. Make changes
7. See no changes

### Exceptions (if any)
```
Uncaught TypeError: window.Blazor._internal.applyHotReload is not a function
    applyBlazorDeltas https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101
    applyBlazorDeltas https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101
    BlazorHotReloadDeltav1 https://localhost:5001/_framework/aspnetcore-browser-refresh.js:31
    onmessage https://localhost:5001/_framework/aspnetcore-browser-refresh.js:37
```

**Comment by captainsafia** [comment]
Thanks for filling this issue.

We generally expect that the package dependencies and TFM align when doing upgrades. Moving forward, we'll be documenting the appropriate upgrade instructions from .NET 5 to .NET 6 to account for this and we have a fix for unexpected exceptions like this in .NET 6 Preview 4.
