### ISSUE TITLE
Update extensions release/3.1 to use ubuntu18.04 agents

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#32200]
The blocker here is that Microsoft.Extensions.Hosting.Systemd is broken when built on ubuntu18.04. This is likely a product issue so investigation is needed.

See initial attempt at: https://github.com/dotnet/extensions/pull/3860

**Comment by dougbu** [comment]
Have you checked the agent configurations in the AzDO documentation❔ It seems likely `systemd` isn't configured as we expect in the newer images. May also need to check w/ the people who originally got the project working. IIRC it was an external contributor and @BrennanConroy who were most involved.

**Comment by JunTaoLuo** [comment]
Done in https://github.com/dotnet/extensions/pull/3868.
