### ISSUE TITLE
Add doc comments for FormOptions defaults

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#32216]
See https://github.com/dotnet/aspnetcore/issues/32055#issuecomment-827335599. We should document these in the xml comments.

https://github.com/dotnet/aspnetcore/blob/1453c5bd2cf886f6846d2cc00b8106dbd0fdbd53/src/Http/Http/src/Features/FormOptions.cs#L16-L34

cc @JamesNK

**Comment by pranavkm** [comment]
Could we document the defaults in the actual options e.g. here: https://github.com/dotnet/aspnetcore/blob/1453c5bd2cf886f6846d2cc00b8106dbd0fdbd53/src/Http/Http/src/Features/FormOptions.cs#L42-L47? Nobody really needs to use these constants.

**Comment by davidfowl** [comment]
Should we hire them from the docs then? It looks bad that they are basically empty in the docs.

**Comment by pranavkm** [comment]
*hide them? If that's an option, I'd prefer it.

**Comment by JamesNK** [comment]
Should add defaults to both places - the const values and the properties that are set to them.

For anyone who picks this up, here is an example of configuring defaults in XML docs:

https://github.com/dotnet/aspnetcore/blob/1453c5bd2cf886f6846d2cc00b8106dbd0fdbd53/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L89-L108
