### ISSUE TITLE
On StackExchangeRedis, allow to get without refresh

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [dotnet/aspnetcore#32210]
Looking at "src/Caching/StackExchangeRedis/src/RedisCache.cs" i noticed that there is no possibility to do a "get" of a valued cached in Redis without doing also a "refresh".

If it is already possible to do a "get" without a "refresh", please tell me how.

Thanks in advance.

**Comment by alecrodden** [comment]
Are you referring to this TODO comment?
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Caching/StackExchangeRedis/src/RedisCache.cs#L302
If so, implementing the change would be useful to us as well. Seems like `EVAL` command could be used to do `GET`+`EXPIRE` together the same way as is done for setting?
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Caching/StackExchangeRedis/src/RedisCache.cs#L19-L30

**Comment by JunTaoLuo** [comment]
I'm curious why you want to be able to "Get" without "Refresh"? Specifically, the refresh is only applicable when `SlidingExpiration` is used. In that case, `Get` is considered as an activity and will therefore need to refresh the expiration value. 

If you wish to set an expiration that doesn't get refreshed by `Get`, `AbsoluteExpiration` and `AbsoluteExpirationRelativeToNow` can be used instead. Does that work for you?

**Comment by LeonSebastianCoimbra** [comment]
Hi Jun,

Yes, AbsoluteExpiration and AbsoluteExpirationRelativeToNow seems to do the work that i need!!

I returned to use StackExchangeRedis one year after i wrote the code, so my memory was, in the meanwhile, overwritten by a lot of other stuffs... I totally forget of the existance of the two flags and doing so i jumped directly to the code.... wrong thing to do....

Thanks for the advice!!
