### ISSUE TITLE
No sign-out authentication handlers are registered. Did you forget to call AddAuthentication().AddCookie("Identity.Application",...)?

### ISSUE THREAD

**Issue by pantonis** [dotnet/aspnetcore#32215]
When I call ```signInManager.SignOutAsync``` I get ```No sign-out authentication handlers are registered. Did you forget to call AddAuthentication().AddCookie("Identity.Application",...)?``` 
I have googled the issue and found that you need to add ```.AddCookie(o =>....)``` in Startup.cs

Why would someone need to add cookie when it is working only with JWT and localstorage???

### Further technical details
- ASP.NET Core version 5.0.5
- Include the output of `dotnet --info` 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS2019

**Comment by blowdart** [comment]
There's no signout mechanism for JWT, the identity is not persisted between calls, you send it every time. So why would you need to signout?

I don't know what "local storage" is referring to here.

**Comment by pantonis** [comment]
@blowdart regarding the signout you are correct. 
@blowdart local storage refers to document in a browser. 
However I was getting the same error when I was calling ```signInManager.PasswordSignInAsync``` until I understood that this method is used only with cookies. In the official documentation there is no such clarification except for the explanation of the ```isPersistent``` param which after 3 hours of searching I found that you need to use the ```signInManager.CheckPasswordSignInAsync``` when working with IdentityCore.

**Comment by blowdart** [comment]
But we don't supply local storage logins, unless this is a blazor issue?

**Comment by pantonis** [comment]
From all this conversation you only understood that the issue is with local
storage?

**Comment by blowdart** [comment]
From this conversation it's not clear how local storage plays into any of this. SignInManager is for ASP.NET Identity. ASP.NET identity does not use client-side local storage. ASP.NET Identity does not use JWT. So where are you using SignInManager, what type of project?
