### ISSUE TITLE
Update Blazor workshop to .NET 6

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#32226]
We should setup a net6 branch of the Blazor workshop: https://aka.ms/blazor-workshop. We need to figure out which .NET 6 functionality we want to add to the labs. This will help validate the work we've done in .NET 6.

**Comment by javiercn** [comment]
@danroth27 thanks for volunteering :)

**Comment by danroth27** [comment]
https://github.com/dotnet-presentations/blazor-workshop/pull/330
