### ISSUE TITLE
Blazor inline `RenderFragment` syntax does not handle `EventCallback`s Properly

### ISSUE THREAD

**Issue by davidmilligan** [dotnet/aspnetcore#32227]
### Describe the bug
Trying to use `EventCallback` in an "inline" razor RenderFragment results in a compilation failure. I think this is due to the generated razor cs code calling the wrong `AddAttribute` override on the builder.

### To Reproduce

```cs
public class C : ComponentBase
{
    [Parameter] public EventCallback E { get; set; }
}
```

```
@code{
    private RenderFragment M() {
       return @<C E=@(() => { }) />;
    }
}
```

### Expected Behavior

Compiles successfully

### Actual Behavior

> error CS1503: Argument 2: cannot convert from 'bool' to 'Microsoft.AspNetCore.Components.EventCallback'

### Further technical details
- ASP.NET Core version: 5.0.104

### Use Case:
Using bUnit to write test cases in .razor files. See: https://bunit.dev/docs/getting-started/writing-tests.html?tabs=xunit#secret-sauce-of-razor-files-tests

This issue was reported in down in the middle of an unrelated thread, but I think it was overlooked, as it wasn't really the main issue: https://github.com/dotnet/aspnetcore/issues/19640#issuecomment-658487401

**Comment by mkArtakMSFT** [comment]
@javiercn should this be transferred to the razor repo or do we have work to do here on our end?

**Comment by vgallegob** [comment]
I really need this, the only way left is using the builder manually which I do not want to maintain.

**Comment by jjonescz** [comment]
This doesn't seem to be reproducible in newer versions of .NET. Can repro in .NET 5, but not in 6, 7, 8.
