### ISSUE TITLE
[Blazor] Using @ref on dynamically generated children

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/aspnetcore#32244]
Blazor related.
### Is your feature request related to a problem? Please describe.
Normally I'd use @ref attribute to reference a child component. But I can't when items are generated dynamically. The question is whether there is a way to reference dynamically generated children.

### Describe the solution you'd like
One way would be that @ref attribute is bound to a IList property, it'd add the child to the list instead of assigning itself to the property. Perhaps there are better ways.

### Additional context
Need to access dynamically generated children. I know that I could pass reference of parent to children and then children can register themselves, but it doesn't look like perfect solution.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This has already been asked https://github.com/dotnet/aspnetcore/issues/17361.
Also there is slightly different solution provided https://stackoverflow.com/questions/60064510/add-ref-to-a-blazor-component-in-a-loop

**Comment by MihaMarkic** [comment]
@mkArtakMSFT Awesome, thanks. I searched before but didn't find it.

**Comment by MihaMarkic** [comment]
@mkArtakMSFT There is one drawback though. Component can't be easily removed. Perhaps @unref could help :)
