### ISSUE TITLE
Populate AuthenticationProperties.ExpiresUtc in JwtHandler

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#32248]
When a JWT token contains the "exp" claim it should set the `ExpiresUtc` property.

We're considering using that property in SignalR to check for expired authentication and closing connections.

cc @Tratcher @blowdart @davidfowl

**Comment by blowdart** [comment]
Yes you should :)

**Comment by davidfowl** [comment]
Isn't this blocking for preview5 @BrennanConroy ?

**Comment by BrennanConroy** [comment]
I'm trying to do this issue right now, asked Chris if I could 😛
