### ISSUE TITLE
System.Security.Claims.PrincipalExtensions.FindFirstValue should return nullable value

### ISSUE THREAD

**Issue by leotsarev** [dotnet/aspnetcore#32264]
### Is your feature request related to a problem? Please describe.
```
        //
        // Summary:
        //     Returns the value for the first claim of the specified type, otherwise null if
        //     the claim is not present.
        //
        // Parameters:
        //   principal:
        //     The System.Security.Claims.ClaimsPrincipal instance this method extends.
        //
        //   claimType:
        //     The claim type whose first value should be returned.
        //
        // Returns:
        //     The value of the first instance of the specified claim type, or null if the claim
        //     is not present.
        public static string FindFirstValue(this ClaimsPrincipal principal, string claimType);
```

### Describe the solution you'd like
It should be `public static string? FindFirstValue(this ClaimsPrincipal principal, string claimType);`

**Comment by blowdart** [comment]
Why do you believe it should be nullable? What claim are you using that has a null value? As claims are serialised as strings it's generally just string.empty

**Comment by leotsarev** [comment]
@blowdart  because it literally says so in XML doc: `or null if the claim is not present`. FindFirstValue source code also consistent with this.

**Comment by blowdart** [comment]
Ah got it. OK that makes sense @HaoK a quick one for you

**Comment by HaoK** [comment]
nullable isn't enabled for identity yet, so this is true in more than just this method

**Comment by leotsarev** [comment]
@HaoK I didn't found tracking issue for "enable nullability for Identity"

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/issues/27389 is one of the meta work items, we have some nullable support but its not fully implemented everywhere yet

**Comment by HaoK** [comment]
Closing as this is tracked by https://github.com/dotnet/aspnetcore/issues/27389
