### ISSUE TITLE
Consider perfering `127.0.0.1` over `localhost` for tests

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#32276]
Localhost can be slow to resolve (1sec) to 127.0.0.1 when the client/server has both ipv4 and ipv6 enabled

e.g. https://github.com/dotnet/runtime/issues/51942

Currently are 1524 references to `localhost`

**Comment by Tratcher** [comment]
Do you see specific tests where the client uses localhost but the server only listens on IPv4?

**Comment by benaadams** [comment]
Not really :)
