### ISSUE TITLE
UserManager.GenerateTwoFactorTokenAsync. How to forget old tokens when creating new ones 

### ISSUE THREAD

**Issue by abryzgin** [dotnet/aspnetcore#32291]
Hello!

using the command userManager.GenerateTwoFactorTokenAsync () I create a new TwoFactorToken. How to delete an old token? so that when you try to enter the old token, the system gives an error

SignInManager.ForgetTwoFactorClientAsync () is not suitable for this.

Also, if I log in, enter the TwoFactorCode. Then I log out and try to log in again, then within 10 minutes I can use the old TwoFactorCode 

**Further technical details**
- ASP.NET Core 5

**Comment by HaoK** [comment]
By default our two factor token providers are not stored in the database, they are either authenticator style TOTP tokens or self signed data protector tokens.  You would have to implement your own token provider and store them somewhere and verify that they are only used once.  But identity does do something similar for the recovery tokens if you want to leverage how we chose to implement it
