### ISSUE TITLE
Update source generator analyzer assemblies used in Dev17

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#32296]
Assemblies in the SDK are cross-genned to improve performance. However, these
cross-genned assemblies cannot be loaded into 32-bit VS. To work around these, we load
the binaries that are not cross-genned (those in the source-generators directory) when
building in VS. However, we want to continue to leverage the cross-genned assemblies in
environments where it makes sense so we load them in the CLI and elsewhere.

There is a chance that cross-genned assemblies can be used in Dev17 so leaving this as a note to verify that.

**Comment by mkArtakMSFT** [comment]
The ROI will be very low from this effort, so closing.
