### ISSUE TITLE
dotnet watch reports hot reload succeeded when there are code errors

### ISSUE THREAD

**Issue by jchannon** [dotnet/aspnetcore#32292]
### Describe the bug
When you have a code error dotnet watch reports it succeeded

### To Reproduce
Write some code, run dotnet watch, make a code change that you know will break compilation, see dotnet watch report the error but also report all is well. I would expect it to say it failed and maybe some colour eg red to indicate a problem

![Screenshot 2021-04-30 at 10 27 16](https://user-images.githubusercontent.com/105126/116676679-2c1e2780-a99f-11eb-8518-30741ac61349.png)

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21229.26
 Commit:    d096cb92f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /Users/jonathan/.dotnet/sdk/6.0.100-preview.5.21229.26/

Host (useful for support):
  Version: 6.0.0-preview.5.21229.1
  Commit:  6a5bc5315a

.NET SDKs installed:

  6.0.100-preview.5.21229.26 [/Users/jonathan/.dotnet/sdk]

.NET runtimes installed:

  Microsoft.NETCore.App 6.0.0-preview.5.21229.1 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by pranavkm** [comment]
This was fixed as part of https://github.com/dotnet/sdk/pull/17391 (which should be a newer build of 6.0-preview5). Errors are reported in red, and it no longer says that hot reload succeeded. Thanks for the report!
