### ISSUE TITLE
Authentication in ASP.NET Core API without using third party solutions

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [dotnet/aspnetcore#32293]
I am building a monolithic API using ASP.NET Core and I want authentication to use JWT.
The official docs suggest following three options for authenticating users accessing web API:

>  - Azure Active Directory
>  - Azure Active Directory B2C
>  - IdentityServer4

But I don't want to use third party providers. And I sure as hell don't want to use IdentityServer4 ($1500/year)

Basically I want the authentication to behave the same way it does with Razor Pages app where Identity takes care of hashing, salting passwords, registration and saves it to the local database. Except in this case I want to use JWT Tokens instead of Cookies for authentication and authorization.

Why isn't there such and option on official docs / VS 2019 template.

How can I achieve this?

I am doing something [similar to this guy](https://stackoverflow.com/questions/65983243/use-net-core-identity-with-an-api) but I wish there was much easier, "official" way of doing this so that I don't introduce security bugs while writing custom implementation.

Frankly, it is amazing to me that I can do this in Razor Pages and not in Web API.

**Comment by javiercn** [comment]
@Prajwal-Jadhav thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/27053, please upvote that issue instead.
