### ISSUE TITLE
Blazor Visual App Builder

### ISSUE THREAD

**Issue by zawhtut** [dotnet/aspnetcore#32304]
Hi,

I would like to request that we can have visual website builder for Blazor, mainly frontend stuffs.
I found we have this in the past. https://www.mono-project.com/archived/aspnet_visual_designer/

It would be great if we have a UI design tool with drag & drop feature for Blazor app. 
There are other website builders like Wix, Webflow and Wordpress. I don't see similar one to that in ASP.net world.

And there are styling libraries like https://blazorstrap.io/ and https://blazorstyled.io/. Especially BlazorStyled.io/
It makes CSS usable in Blazor pages. This tool may also be able to use 3rd party component libraries such as Telerik,
Syncfusion, MudBlazor, Radzen, MatBlazor and DevExpress. 

So I come up with an idea. If we can have a visual design tool that generate codes like BlazorStyled behind, 
it would be so awesome. Thanks for your attention.

**Comment by javiercn** [comment]
@zawhtut thanks for contacting us.

This is not a feature our team would likely work on in the future, our focus is on building the framework bits. You might choose to file this issue in Visual Studio via the [suggest a feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) for tooling teams in Visual Studio to consider this in the future.
