### ISSUE TITLE
Running Azure Function net core 3.1 and v3 with AspNetCore.SignalR.Client pacakge rasing error Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0,

### ISSUE THREAD

**Issue by bhasker412** [dotnet/aspnetcore#32313]
Created a net core 3.1  v3 queue trigger azure function to read the queue message, process it and then send message with signalr hub to notify user.

When i run the function without signalr core client everything works fine. After adding signalr client package and try to run it, ended up in **System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')**. I have added **Microsoft.Extensions.Logging.Abstractions 5.0.0** also but it didn't work out.

### Sample project and error screenshot

[QueueSignalR.zip](https://github.com/dotnet/aspnetcore/files/6408909/QueueSignalR.zip)

![Screenshot (4)](https://user-images.githubusercontent.com/4247402/116771439-12491700-aa69-11eb-8ac1-df7b9c65a863.png)

**Comment by blowdart** [comment]
You are trying to use SignalR for .NET 5. Please change the SignalR client version to [3.1.14](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/3.1.14), the latest 3.1.x version and try again.

**Comment by davidfowl** [comment]
This is an azure functions issue. If @blowdart's advice doesn't work file an issue here https://github.com/Azure/azure-functions-host

cc @fabiocav

**Comment by bhasker412** [comment]
Thanks @blowdart this worked.
