### ISSUE TITLE
[FEATURE REQ] Azure.Extensions.AspNetCore.DataProtection.Blobs should create container if not exists 

### ISSUE THREAD

**Issue by jsquire** [dotnet/aspnetcore#32316]
# Issue Transfer

This issue was transferred from the Azure SDK repository, [#20798](https://github.com/Azure/azure-sdk-for-net/issues/20798).   

## Please be aware that @leotsarev is the author of the original issue and include them for any inquiries or replies.

**Library or service name.**
Azure.Extensions.AspNetCore.DataProtection.Blobs
 
**Is your feature request related to a problem? Please describe.**
I call PersistKeysToAzureBlobStorage in Startup and expect everything should work out of box, but I have to create container manually.

**Comment by blowdart** [comment]
@jsquire I commented on the original issue, this code is part of the Azure Sdk, as indicated by its namespace and that it lives in your repo.

Closing as external.

**Comment by jsquire** [comment]
@blowdart.  Apologies for the confusion and thanks for the redirect.   This was a mistake on my part.

**Comment by blowdart** [comment]
No worries, it's all quite confusing now you own the bits for the azure services 😀
