### ISSUE TITLE
using browser local storage an asp.net core app MVC and razor

### ISSUE THREAD

**Issue by saeednoruzi** [dotnet/aspnetcore#32311]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

### Additional context
it would be nice if we had access to web browser local storage in MVC and Razor Pages like cookie and session

**Comment by blowdart** [comment]
Do you have a question or an issue here? You need to explain what you're looking for.

**Comment by javiercn** [comment]
@saeednoruzi thanks for contacting us.

You can't use local storage unless your app runs javascript in the browser to access it.

**Comment by saeednoruzi** [comment]
well we can access to cookie and session in controller why not local storage
