### ISSUE TITLE
ASP.net core app cannot handle requests with double slash (e.g. https://host//api)

### ISSUE THREAD

**Issue by Yaming-Hub** [dotnet/aspnetcore#32326]
### Describe the bug
ASP.net core app cannot handle requests with double slash (e.g. https://host//api)

### To Reproduce
Start a basic Asp.net core server (.net 5.0), send request https://host//api (note, there is a double slash at root).

### Exceptions (if any)
System.ArgumentException
  HResult=0x80070057
  Message=The path in 'value' must start with '/'. (Parameter 'value')
  Source=Microsoft.AspNetCore.Http.Abstractions
  StackTrace:
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)

### Further technical details
- ASP.NET Core version 5.0
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
What's the full stack trace for that exception?

**Comment by halter73** [comment]
I think it would be nice to at least have the option to support this. https://github.com/////dotnet/aspnetcore/issues/32326 works just fine for example.

**Comment by Tratcher** [comment]
No repro on .NET 5.0 IIS Express or Kestrel with a simple app:
```
            app.Run(context =>
            {
                return context.Response.WriteAsync(context.Request.Path);
            });
```
