### ISSUE TITLE
asp.net core Cluster

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/aspnetcore#32328]
Is there documentation for the cluster?
Please share your experience.

**Comment by Tratcher** [comment]
Like a web farm?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-5.0

**Comment by EvgenyPrikhodko** [comment]
If I understood correctly this is an example for Azure, but is there an example for servers?

**Comment by davidfowl** [comment]
It's not azure specific no.

**Comment by EvgenyPrikhodko** [comment]
for example, I do not really understand how the token of server A will understand server B

**Comment by EvgenyPrikhodko** [comment]
> It's not azure specific no.

ok

**Comment by Tratcher** [comment]
Please explain what resource you're trying to share across machines.

**Comment by EvgenyPrikhodko** [comment]
> Please explain what resource you're trying to share across machines.

nginx upstream

**Comment by Tratcher** [comment]
Sorry, this isn't enough of an explanation for us to be able to help you.

Usage questions like this are better directed to forums like [Stackoveflow.com](Stackoveflow.com).

**Comment by davidfowl** [comment]
Sounds like maybe you're trying to configure nginx in front of asp.net core which isn't directly related.
