### ISSUE TITLE
Checkbox to disable HTTPS after project creation.

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#32330]
1st of all it is not just about HTTPS it applies to enabling PWA for Blazor WASM after creation.
Scenario: I have build a Blazor server project 3 months ago and left the HTTPS checkbox checked in the option. Now that they made public handling of the HTTPS I needed to run it as HTTP.
searched the Microsoft docs and it says I can only configure it from the creation page.
So I had to recreate the same project again and copy paste my code with the checkbox un-Checked.

I had this complain with PWA when I forgot to check it and then I had to manfully apply the PWA files later to my WASM project because I could not find a checkbox to make my project PWA.

**Comment by blowdart** [comment]
The dialog you see on project creation is only for project creation. It's not for adjusting the project after it's been created. It's always been this way, as VS can't tell what changes you may have made once the initial project was laid down on disk.

You can adjust the HTTPS settings via the project properties dialog in solution explorer, and then removing the HSTS and HTTPS redirect in startup.cs

**Comment by Sharaf-Mansour** [comment]
@blowdart 
I removed the HSTS and HTTPS and still got HTTPS and I could not find any option for it in the project  properties.
Also this is not only about HTTPS. Docs does not show how to remove it.
And for Blazor WASM I can not set it up for PWA after the creation which I must do manually.
All I am saying is that if it is possible to add a checkbox for it in the Project properties would make it easier, and if not then it would be nice to find a solution for it from the Docs.
Adding a feature is not easy but I am pointing out an idea.

**Comment by blowdart** [comment]
To be honest if you're using authentication then you need https to be safe. Or any PII or company secrets. Even on an internal network https is pretty much necessary these days.

Adding a feature to make something unsafe is a big request.

**Comment by Sharaf-Mansour** [comment]
@blowdart I completely agree with you, but sometimes this becomes the final decision and you as a developer will have to do. As for me I personally did not ever consider removing HTTPS.
But it is what it is.
But let's say maybe adding it as an option later in the project properties. Along with PWA and Docker ?

**Comment by blowdart** [comment]
Well in VS, if you right click on the project and choose properties then click debug you can see, under web server settrings, enable SSL

![Screenshot 2021-05-02 105023](https://user-images.githubusercontent.com/796298/116822536-37568c00-ab34-11eb-9189-0c6f16d25643.jpg)

That gets you there in VS 

In launchsettings.json in the properties folder you can see appplication URL, removing the https one in there removes it if you're running kestrel directly

```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:27577",
      "sslPort": 44340
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "WebApplication1": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

And then finally, as you've discovered you need to remove `app.UseHttpsRedirection()` and `app.UseHsts()`. That removes all vestiages of https.

But as I said, the new project dialog is for new projects. There's no way to switch project types, or those settings from it once a project is created. Same with switching Blazor to a PWA. It's just a limitation of VS, not .NET
```

**Comment by Sharaf-Mansour** [comment]
@blowdart thank you very much for the information, is it possible to add those steps to the docs ? 
Also Thanks for ￼clarifying that it's VS ￼limitation. I hope it gets improved in VS 2022.

**Comment by blowdart** [comment]
It won't change in VS, it cannot. Because it involves both code and settings, and that dialog is for _new_ projects, it's not going to be a design goal.

@Rick-Anderson do you think a docs update for removing HTTPS in web and API projects would be useful?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson do you think a docs update for removing HTTPS in web and API projects would be useful?

I don't want to encourage removing HTTPS. It's pretty straightforward if you look at [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio)

If you want to remove HTTPS, then you better read the docs and understand what you're doing. By the time you do that, you'll know how to remove it. In the words of @Eilon, anyone who needs this is smart enough to figure it out. I've added a few corollary's:

* Anyone who wants this better figure out how to do it, just to make sure they understand what they're asking.

Feel free to transfer this to https://github.com/dotnet/AspNetCore.Docs
If we get enough requests, I might change my mind.

**Comment by Sharaf-Mansour** [comment]
@blowdart Alright thanks for your time and efforts sir.
@Rick-Anderson 
I get it now. when it comes to unrecommended scenarios it is better to follow the standards and as for doing something risky then Docs should never encourage doing so. and yes if someone is smart enough to want HTTPS removed then they should be smart enough to figure it out. 

And I will take this:

> Well in VS, if you right click on the project and choose properties then click debug you can see, under web server settrings, enable SSL
> 
> ![Screenshot 2021-05-02 105023](https://user-images.githubusercontent.com/796298/116822536-37568c00-ab34-11eb-9189-0c6f16d25643.jpg)
> 
> That gets you there in VS
> 
> In launchsettings.json in the properties folder you can see appplication URL, removing the https one in there removes it if you're running kestrel directly
> 
> ```json
> {
>   "iisSettings": {
>     "windowsAuthentication": false,
>     "anonymousAuthentication": true,
>     "iisExpress": {
>       "applicationUrl": "http://localhost:27577",
>       "sslPort": 44340
>     }
>   },
>   "profiles": {
>     "IIS Express": {
>       "commandName": "IISExpress",
>       "launchBrowser": true,
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     },
>     "WebApplication1": {
>       "commandName": "Project",
>       "dotnetRunMessages": "true",
>       "launchBrowser": true,
>       "applicationUrl": "https://localhost:5001;http://localhost:5000",
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     }
>   }
> }
> ```
> 
> And then finally, as you've discovered you need to remove `app.UseHttpsRedirection()` and `app.UseHsts()`. That removes all vestiages of https.
> 
> But as I said, the new project dialog is for new projects. There's no way to switch project types, or those settings from it once a project is created. Same with switching Blazor to a PWA. It's just a limitation of VS, not .NET

As the answer to my question. I will close the issue
