### ISSUE TITLE
After RequestAborted, Response.BodyWriter does not signal IsCompleted/IsCanceled

### ISSUE THREAD

**Issue by sandersaares** [dotnet/aspnetcore#32331]
### Describe the bug
When RequestAborted occurs, code using Response.BodyWriter will not realize that the pipe is closed because **the pipe will silently discard writes** instead of signaling completion/cancellation.

Explicitly doing `BodyWriter.CancelPendingFlush()` is something of a workaround but if done after `RequestAborted` it only works under IIS Express, not when running standalone via Kestrel.

|                                              | IIS Express               | WebApp1.exe               |
|----------------------------------------------|---------------------------|---------------------------|
| RequestAborted -> FlushResult.IsCompleted    | No                        | No                        |
| CancelPendingFlush -> FlushResult.IsCanceled | Yes                       | No                        |
| WriteAsync() after request handler returns   | ObjectDisposedException   | InvalidOperationException |

My expectation is that at minimum `.IsCompleted` is true after request is aborted. I would strongly prefer `.CancelPendingFlush()` to still also signal `.IsCanceled` in such a case.

If the request handler method ends, PipeWriter will throw `ObjectDisposedException` or `InvalidOperationException` in any case, preventing this from being a resource leak but the lack of working IsCanceled or IsCompleted signaling in this situation does complicate writing clean code because of the extra wiring needed to "manually" detect end of response in the write loop before the request handler method ends - I would much prefer to wait for the write loop to tell my request handler when it is done and use that as my signal to end the request handler.

Tested with HTTP1, though I see similar code paths also in HTTP2 and HTTP3 implementations (`if (_streamCompleted) return default;` in `FlushAsync()`).

### To Reproduce
```csharp
[HttpGet]
public async Task Get()
{
    var writeLoop = Task.Run(() => WriteLoopAsync(Response.BodyWriter));

    // CancelPendingFlush() here has no effect except when started via IIS Express.
    using var registration = HttpContext.RequestAborted.Register(() => Response.BodyWriter.CancelPendingFlush());

    await writeLoop;
}

private async Task WriteLoopAsync(PipeWriter writer)
{
    var payload = Encoding.UTF8.GetBytes("hello, web browser" + new string(' ', 512) + "\n");

    while (true)
    {
        var result = await writer.WriteAsync(payload);

        if (result.IsCompleted || result.IsCanceled)
        {
            // The idea is to reach this point if the body writer pipe ends (either because of RequestAborted or other reason).
            // This is not reached on RequestAborted, though. The write loop keeps "successfully" writing.
            return;
        }

        await Task.Delay(TimeSpan.FromSeconds(1));
    }
}
```

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by davidfowl** [comment]
The one comment I have is that running any code after the request handler requests is invalid. It's your job to make sure that doesn't happy.

**Comment by senbar** [comment]
I have started working on this issue.

**Comment by senbar** [comment]
So I have fixed this issue for http1,2,3 on kestrel but am struggling with IIS. I can't seem to find the part of the code responsible for creating FlushResult, if anyone has any directions I could use some help. I will open PR draft for now with Kestrel fixes.
