### ISSUE TITLE
Unknown ASP.NET pages since .NET 6 Preview updates

### ISSUE THREAD

**Issue by MichaRotstein** [dotnet/aspnetcore#32344]
Since updating from an earlier .NET 6 preview to the latest one (6.0.100-preview.3.21202.5)

I noticed new classes appearing when I reflect on the assembly:
```
Assembly.GetExecutingAssembly().GetTypes()
...
    [86]: {Name = "Pages_Error" FullName = "DashboardServer.Pages.Pages_Error"}
    [87]: {Name = "Pages_Index" FullName = "DashboardServer.Pages.Pages_Index"}
    [88]: {Name = "Pages_Privacy" FullName = "DashboardServer.Pages.Pages_Privacy"}
    [89]: {Name = "Pages__ViewImports" FullName = "DashboardServer.Pages.Pages__ViewImports"}
    [90]: {Name = "Pages__ViewStart" FullName = "DashboardServer.Pages.Pages__ViewStart"}
    [91]: {Name = "Pages_Shared__Layout" FullName = "DashboardServer.Pages.Shared.Pages_Shared__Layout"}
    [92]: {Name = "Pages_Shared__LoginPartial" FullName = "DashboardServer.Pages.Shared.Pages_Shared__LoginPartial"}
    [93]: {Name = "Pages_Shared__ValidationScriptsPartial" FullName = "DashboardServer.Pages.Shared.Pages_Shared__ValidationScriptsPartial"}
```

`Pages_Error` for example is not in my project. This is causing issues with a verification process I do using reflection on all type which fails on `Pages_Error`

I think this is a bug as before all types from `Assembly.GetExecutingAssembly().GetTypes()` where included in the project. Is there at least a way to identify such types ?

Thanks

**Comment by javiercn** [comment]
@MichaRotstein thanks for contacting us.

This might be due to the fact that we are moving the Razor compiler to use source generators and producing the builds in the same assembly as the original application.

@captainsafia or @pranavkm can confirm, however this is expected.

**Comment by MichaRotstein** [comment]
Thanks @javiercn .. is it planned to have a way for reflection to recognized such classes that are not actually in the project (and therefore cannot be decorated with attributes that can be inspected by reflection) ?

**Comment by captainsafia** [comment]
Yes, the change you are running into is a result of https://github.com/aspnet/Announcements/issues/459.

> is it planned to have a way for reflection to recognized such classes that are not actually in the project

The types are all placed under the same namespace `AspNetCoreGeneratedDocument` so you might be able to filter by that for your use case.

**Comment by MichaRotstein** [comment]
@captainsafia 

>The types are all placed under the same namespace AspNetCoreGeneratedDocument

I'm confused if you look at the output of `Assembly.GetExecutingAssembly().GetTypes()` in my post the namespace is `Pages` and not AspNetCoreGeneratedDocument

**Comment by pranavkm** [comment]
@MichaRotstein we're looking at annotating these types using CompilerGenerated attributes. See #32356. Would that resolve your ask?

**Comment by MichaRotstein** [comment]
@pranavkm yes definitely

Is there any workaround in the meantime ? this is breaking existing code and I am wondering if there is any other way for reflection to recognize such classes that are in `GetExecutingAssembly().GetTypes()` but who's code is not available ?

**Comment by captainsafia** [comment]
The namespace trick was a poor misdirect on my part. I hadn't noticed that your views were defined under a separate namespace and would not be under the default one we generated.

Alternatively, we do add a `RazorCompiledItem` metadata attribute to the compiled assembly with the generated views. You might be able to leverage that in the meanwhile.

![Screen Shot 2021-05-03 at 5 29 11 PM](https://user-images.githubusercontent.com/1857993/116948715-1590fe00-ac35-11eb-8925-e257b123be11.png)

**Comment by MichaRotstein** [comment]
@captainsafia 

here is the type from the debugger:

```
{Name = "Pages_Error" FullName = "DashboardServer.Pages.Pages_Error"}
    Assembly: {DashboardServer, Version=1.141.0.0, Culture=neutral, PublicKeyToken=null}
    AssemblyQualifiedName: "DashboardServer.Pages.Pages_Error, DashboardServer, Version=1.141.0.0, Culture=neutral, PublicKeyToken=null"
    Attributes: Sealed | BeforeFieldInit
    BaseType: {Name = "Page" FullName = "Microsoft.AspNetCore.Mvc.RazorPages.Page"}
    ContainsGenericParameters: false
    CustomAttributes: Count = 0
    DeclaredConstructors: {System.Reflection.ConstructorInfo[1]}
    DeclaredEvents: {System.Reflection.EventInfo[0]}
    DeclaredFields: {System.Reflection.FieldInfo[5]}
    DeclaredMembers: {System.Reflection.MemberInfo[27]}
    DeclaredMethods: {System.Reflection.MethodInfo[13]}
    DeclaredNestedTypes: {System.Reflection.TypeInfo.<get_DeclaredNestedTypes>d__22}
    DeclaredProperties: {System.Reflection.PropertyInfo[7]}
    DeclaringMethod: '((System.RuntimeType)t).DeclaringMethod' threw an exception of type 'System.InvalidOperationException'
    DeclaringType: null
    FullName: "DashboardServer.Pages.Pages_Error"
    GUID: {935a60a4-0f04-3848-963f-7e25c76e6598}
    GenericParameterAttributes: '((System.RuntimeType)t).GenericParameterAttributes' threw an exception of type 'System.InvalidOperationException'
    GenericParameterPosition: '((System.RuntimeType)t).GenericParameterPosition' threw an exception of type 'System.InvalidOperationException'
    GenericTypeArguments: {System.Type[0]}
    GenericTypeParameters: {System.Type[0]}
    HasElementType: false
    ImplementedInterfaces: {System.Type[1]}
    IsAbstract: false
    IsAnsiClass: true
    IsArray: false
    IsAutoClass: false
    IsAutoLayout: true
    IsByRef: false
    IsByRefLike: false
    IsCOMObject: false
    IsClass: true
    IsCollectible: false
    IsConstructedGenericType: false
    IsContextful: false
    IsEnum: false
    IsExplicitLayout: false
    IsGenericMethodParameter: false
    IsGenericParameter: false
    IsGenericType: false
    IsGenericTypeDefinition: false
    IsGenericTypeParameter: false
    IsImport: false
    IsInterface: false
    IsLayoutSequential: false
    IsMarshalByRef: false
    IsNested: false
    IsNestedAssembly: false
    IsNestedFamANDAssem: false
    IsNestedFamORAssem: false
    IsNestedFamily: false
    IsNestedPrivate: false
    IsNestedPublic: false
    IsNotPublic: true
    IsPointer: false
    IsPrimitive: false
    IsPublic: false
    IsSZArray: false
    IsSealed: true
    IsSecurityCritical: true
    IsSecuritySafeCritical: false
    IsSecurityTransparent: false
    IsSerializable: false
    IsSignatureType: false
    IsSpecialName: false
    IsTypeDefinition: true
    IsUnicodeClass: false
    IsValueType: false
    IsVariableBoundArray: false
    IsVisible: false
    MemberType: TypeInfo
    MetadataToken: 33554520
    Module (System.Reflection.MemberInfo): {DashboardServer.dll}
    Module: {DashboardServer.dll}
    Name: "Pages_Error"
    Namespace: "DashboardServer.Pages"
    ReflectedType: null
    StructLayoutAttribute: {System.Runtime.InteropServices.StructLayoutAttribute}
    TypeHandle: {System.RuntimeTypeHandle}
    TypeInitializer: null
    UnderlyingSystemType: {Name = "Pages_Error" FullName = "DashboardServer.Pages.Pages_Error"}
```

where do I find `RazorCompiledItem` ?

**Comment by benaadams** [comment]
> where do I find `RazorCompiledItem` ?

Its on the `Assembly` rather than the `Type`?

**Comment by MichaRotstein** [comment]
@benaadams 

OK I see this:

```
Assembly.GetExecutingAssembly().CustomAttributes.ToArray()[24]

{[Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(DashboardServer.Pages.Pages_Error), "mvc.1.0.razor-page", "/Pages/Error.cshtml")]}
    AttributeType: {Name = "RazorCompiledItemAttribute" FullName = "Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute"}
    Constructor: {Void .ctor(System.Type, System.String, System.String)}
    ConstructorArguments: Count = 3
    NamedArguments: Count = 0
```

I guess I can use this but given a Type instance `t` to then find out if it has assembly custom attribute `RazorCompiledItemAttribute` on it is quite convoluted :(

**Comment by MichaRotstein** [comment]
I ended up with this that seem convoluted but works 

```
Func<Type, bool> ok = (type => 
    Assembly.GetExecutingAssembly().CustomAttributes
      .Select(customAttributeData => customAttributeData.ConstructorArguments)
      .Where(constructorArguments => (constructorArguments.Any() && (constructorArguments[0].Value as Type) == type))
      .Any()
);
```

Would appreciate comments

**Comment by davidfowl** [comment]
Is performs a concern? You could do more caching if it was...

**Comment by MichaRotstein** [comment]
@davidfowl yes I will I just wanted to get approval this is the right way (checking ConstructorArguments etc)
