### ISSUE TITLE
Windows authorization fails when specifying both Roles and AuthenticationSchemes

### ISSUE THREAD

**Issue by robertcoltheart** [dotnet/aspnetcore#32340]
### Describe the bug
When using Windows authentication (using the Negotiate package), specifying both `Roles` and `AuthenticationSchemes` in the `[Authorize]` attribute fails when it should succeed.

It's likely to be caused by the `PolicyEvaluator`, which merges identities into a single principal, see [here](https://github.com/dotnet/aspnetcore/blob/v5.0.5/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L46). However this means the `WindowsPrincipal` is lost which is crucial to decoding the `groupsid` groups from AD when the authorization calls `IsInRole`.

Is this expected behavior? Am I doing something wrong?

### To Reproduce

Controller endpoint:
```c#
[ApiController]
public class WeatherForecastController : ControllerBase
{
    [Authorize(Roles = "Everyone", AuthenticationSchemes = NegotiateDefaults.AuthenticationScheme)]
    [HttpGet("weatherforecast")]
    public IActionResult Get()
    {
        // This endpoint call fails

        // Type of user is `ClaimsPrincipal`
        // If I remove `AuthenticaitonSchemes`, it is `WindowsPrincipal`
        var user = User;

        return Ok();
    }
}
```

Vanilla startup using Kestrel:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services
        .AddAuthentication(NegotiateDefaults.AuthenticationScheme)
        .AddNegotiate();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app
        .UseRouting()
        .UseAuthentication()
        .UseAuthorization()
        .UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
}
```

### Further technical details
- ASP.NET Core version `5.0`
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
Is there a reason you need to specify the auth scheme on Authorize? You've already set it as the default scheme in startup.

**Comment by robertcoltheart** [comment]
This was simply to illustrate the problem.  

In reality, we are using both Negotiate and JWT, neither of which are set as defaults. Then we set the default policy in 'UseAuthorization' to accept both schemes. This approach works flawlessly, except for the scenario I described above, where an AD role will fail to authorize since the WindowsPrincipal is stripped away from the resulting 'User' principal object.

**Comment by Tratcher** [comment]
Just checking. I agree this is problematic behavior. It's not clear why MergeUserPrincipal is even creating a new principal when there's only one scheme. If it no-op'd the first time then this would work in the general case.  We could also have it sniff for WindowsPrincipals coming in and re-create that.

As for mitigations, it looks like you can replace the IPolicyEvaluator service with your own copy that does as you like.

**Comment by robertcoltheart** [comment]
Yeah that's what we've done, but I'm sure this issue will bite someone down the line, so would be good to either have the behaviour described in docs or have a bug fix for it. I'm happy to take a stab at a PR if you'd like.

**Comment by Tratcher** [comment]
@HaoK thoughts on fixing this via no-oping or type sniffing?

**Comment by HaoK** [comment]
I think its reasonable to skip doing anything when only a single scheme to the principal if only a single scheme is specified if that will fix this problem
