### ISSUE TITLE
Use ProtectedLocalStorage Across Subdomains

### ISSUE THREAD

**Issue by LazZiya** [dotnet/aspnetcore#32347]
I am building an e-commerce website, the users can add items to their cart that is persisted in the DB or local storage. If the user is logged-in the cart items will be saved into the DB, but if the user is not logged-in (anonym) so the cart items are saved into local storage. I already implemented `ProtectedLocalStorage` in a shared class library and all cart operations are working perfectly.

### The project arch.
My project has multiple subdomains;
 - Main shopping site: (e.g. https://www.my-shopping-site.com) where all the products are listed and where users can add items to their shopping carts.
 - Checkout Site: (e.g.: https://checkout.my-shopping-site.com) a subdomain of the shopping site, where the users can view their cart details, and increase/decrease or remove items from their carts.

When an anonym user adds item to the cart, the items is being saved into the local storage relevant to the main shopping site. When the user want to review the cart and do checkout, he is being redirected to the checkout subdomain where the cart items are listed, and there additional increase/decrease of items should be possible.

### The problem
When we are in the subdomain we can't access the local storage of the main website, and that makes it impossible to view the cart items from the subdomain. 

### The desired solution
Add a `BaseDomian` configuration param to the `ProtectedLocalStorage` to define the main site of local storage, so we van access it from subdomains as well. e.g.:

````cs
private readonly ProtectedLocalStorage LocaStorage;

public Foo(ProtectedLocalStorage localStorage)
{
    LocalStorage = localStorage;

    // Define a param for base domain, so even when we do a request from subdomain
    // it will fetch the local storage of the base domain.
    LocalStorage.BaseDomain = "https://my-shopping-site.com";
}
````

### Additional context
A [similar discussion](https://stackoverflow.com/questions/4026479/use-localstorage-across-subdomains) was around since many years, but it would be great if we can just do it with a simple setup using `ProtectedLocalStorage`.

**Comment by javiercn** [comment]
@LazZiya thanks for contacting us.

What you are experiencing is a fundamental limitation that the browsers impose for security reasons. This scenario is outside of the scope of use cases for protected local storage and is not something we plan to add.

If you need cross-domain communication you'll have to implement your own solution using standard web technologies.

**Comment by LazZiya** [comment]
@javiercn thank you for your response, I ended up using cookies to store cart items for anonym users, so it is easier to share across subdomain. _But I still willing to see an official (browser based or blazor based) solution for sharing the local storage across subdomains_ :)
