### ISSUE TITLE
Generic Claim for SignalR to check for expired authentication and closing connections

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#32350]
### Is your feature request related to a problem? Please describe.

With the [AuthenticationProperties.ExpiresUtc in JwtHandler](https://github.com/dotnet/aspnetcore/issues/32248) by @BrennanConroy, the '_exp_' claim is used in SignalR for expired authentication and closing connections. It will be available in .NET 6 preview 5.

The following has been implemeted for a Blazor Server project (Individual Accounts Authentication Type) to determine if the user is no longer authorized based on the idea of @javiercn : https://github.com/dotnet/aspnetcore/issues/21726#issuecomment-627434195

The Identity User has a ExpirationUtcDateTime property. It is used to define an ExpirationUtcDateTime claim in an additional User Claim principal factory.

```C#
public class AdditionalUserClaimsPrincipalFactory : UserClaimsPrincipalFactory<...>
{
   ...
   public override async Task<ClaimsPrincipal> CreateAsync(WebBiobankUser user)
  {
	// The supplementary claim is added during the clain definition
	var principal = await base.CreateAsync(user);
	var identity = (ClaimsIdentity)principal.Identity;
	var claim = new Claim(nameof(ExpirationUtcDateTime), user.ExpirationUtcDateTime...);
	identity?.AddClaim(claim);
	return principal;
  }
}
```
The expiration is set when logging.

```C#
// When logging
...
user.ExpirationUtcDateTime = DateTime.UtcNow.AddSeconds(...);
...
await _signInManager.SignInAsync(user, new AuthenticationProperties
{
    AllowRefresh = false,
    IsPersistent = false,
    ExpiresUtc = DateTime.UtcNow.AddSeconds(...)
});
```

There is a claim comparison in the authentication state provider with the date with the current time to determine if the user is no longer authorized.

```C#
public class RevalidatingIdentityAuthenticationStateProvider<TUser> : ...
{
   ...
   protected override async Task<bool> ValidateAuthenticationStateAsync(AuthenticationState authenticationState, 
   CancellationToken cancellationToken)
  {
     ...
     // Check is made with the ExpirationUtcDateTime claim information
     ...
  }
}
```

### Describe the solution you'd like
What about a claim with a specific name in the authenticated principal in SignalR to check for expired authentication and closing connections ? Does it make sense ?

**Comment by davidfowl** [comment]
Why would we make a signalr specific claim?

**Comment by boukenka** [comment]
What I have understood with the [AuthenticationProperties.ExpiresUtc in JwtHandler](https://github.com/dotnet/aspnetcore/issues/32248), the "_exp_" claim is used in SignalR for expired authentication and closing connections. What if you want to notify SignalR of authentication expiration in the same way and you are not using JWT ? Can this be done by using a claim like 'exp' or another claim name?

**Comment by davidfowl** [comment]
Then I think the authentication scheme should set the `AuthenticationProperties.ExpiresUtc` field, like cookies did and now JWT is doing.

**Comment by boukenka** [comment]
Now, with cookie authentication and with the ExpiresUtc property set, when the cookie expires and the user clicks a button on a blazor component, the authentication state provider still says that the user is authenticated. 
That's why I had to define a specific implementation to support this scenario.
I thought it would not be necessary to do this implementation if SignalR drops the connection because the authentication has expired. SignalR will know when to close the connection with a dedicated claim. For JWT, this would be 'exp'.

**Comment by BrennanConroy** [comment]
The idea is that SignalR will check the `AuthenticationProperties.ExpiresUtc` property for when the token expires, SignalR should not care about what claim the expiration comes from, that is an auth concern not a SignalR concern. Today this will work for at least Cookie and JWT auth out of the box. We'll be taking a look at other auth schemes to see if the work and see what kind of hooks might be needed or already exist for users to customize this.

**Comment by boukenka** [comment]
@BrennanConroy @davidfowl Thank you both for your answers and clarifications.
