### ISSUE TITLE
No HTML end tag completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-HTML-end-tag-completion/1381509)._

---
I created a minimalistic ASP.NET Core app using FeatherHttp and wired up Razor Pages, but I'm not getting HTML end tag completions in my .cshtml file.

---
#### Feedback Bot on 3/25/2021, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/25/2021, 11:21 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Fixed in latest VS.
