### ISSUE TITLE
Experimental Razor editor colouring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32369]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Experimental-Razor-editor-colouring/1408956)._

---
The editor does not apply colouring of components. Everything is colour coded as HTML elements is seems and editing the source code does not affect this.

---
#### Feedback Bot on 4/27/2021, 07:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg assigning over to you. Could you investigate the logs attached and see what part of the system is falling over. We should ensure that this isn't still an issue in 16.10

**Comment by ryanbrandenburg** [comment]
I'm like 90% sure this is caused by a space in the path that causes the C# call to fail. If that's correct I should be able add an extra conversion/guard and have this solved.
