### ISSUE TITLE
Infer collection interfaces like IList come from the body in minimal actions

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#32376]
Currently, all interface parameters without an attribute are inferred to be services. I like this simplicity, but it might be more convenient for developers if we inferred collection interface types like `IList` and `IEnumerable` are from the body instead. This complicates the mental model a bit and it's not *that* uncommon to consume multiple services using `IEnumerable`, but it's worth considering. See https://github.com/dotnet/aspnetcore/pull/31658#issuecomment-817132361

**Comment by halter73** [comment]
Given discussion in #32516, we might want to avoid doing this for collections of simple types. Or maybe we exclude arrays? That would feel a bit weird though.

**Comment by davidfowl** [comment]
I think we should close this and wait for feedback.

**Comment by halter73** [comment]
Agreed!
