### ISSUE TITLE
TouchActions do not appear to work in Selenium

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#32373]
We might be able to use this event when using PlaywrightSharp. Using this to track unskipping a test.

**Comment by TanayParikh** [comment]
https://playwright.dev/python/docs/api/class-touchscreen

**Comment by mkArtakMSFT** [comment]
Given that we're not switching to the Playwright yet, and Selenium doesn't support touch actions, let's delete the (one test which relies on this, but is skipped) for now and close this issue.

**Comment by MackinnonBuck** [comment]
> let's delete the (one test which relies on this, but is skipped) for now and close this issue.

I investigated this more and concluded that we could still make this test work in Selenium. Therefore, this issue is now closed because the test has been re-enabled, not because it has been deleted.
