### ISSUE TITLE
Advantage of single file deployment

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/aspnetcore#32379]
Single file deployment was available in .netcore3.0 and improves this mode in .net5. But, what's the advantage of Single file deployment? Do we really need it?

In ASP.NET MVC5, I can replace the static files directly, after I deploy the app. In single file deployment mode, if I need temporarily replace the static file, I must deploy the app again.

**Comment by javiercn** [comment]
@CwjXFH thanks for contacting us.

Single file deployments make deploying apps much easier, and enable smaller payloads via IL linking. It's an optional platform feature that you can use if it fits your use case, if not, you are not forced to use it.

While we've tried to answer your question, this issue tracker is limited to issues and feature improvements, we don't have the capacity to deal with open ended questions like the one you are posing, so we suggest you use a different channel like visual studio feedback or user voice.
