### ISSUE TITLE
Use nullibility to infer optionality of service and body parameters

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#32375]
```C#
app.MapPost("/todos", (Todo? todo) => { 
// ...
app.MapGet("/something", (IService? service) => { 
// ...
```

In cases like the above, we could use the nullability of the `Todo` and `IService` parameters to determine weather to request body and service are optional.

See https://github.com/dotnet/aspnetcore/pull/31658#discussion_r610968242

**Comment by davidfowl** [comment]
Also detect default values

**Comment by JamesNK** [comment]
Required reflection metadata about whether parameters have default values and are nullable is no available on private and compiler-generated methods.

**Comment by davidfowl** [comment]
We want to determine if these parameters should fail to bind if there's no value provided for them from the determined source (inferred or explicit). The question is, how does the developer indicate that a parameter is optional (should allow default value) or not. For example

```C#
string Hello(string name = "John") => $"Hello {name}";
app.MapGet("/hi", Hello);
```

In the above, if no name is provided (via the query string), the value will be "John".

```C#
string Hello(string name = null) => $"Hello {name}";
app.MapGet("/hi", Hello);
```

In the above, if no name is provided, the value will be null.

```C#
string Hello(string name) => $"Hello {name}";
app.MapGet("/hi", Hello);
```

What does the above mean? Should it mean non-null? Today if no name is provided the value will be null.

We need a way to opt-into "required-ness":
- Nullable annotations:
- Attributes
- Absence of default values could mean required
- Type system (e.g. F# option)

```C#
// Required name
string Hello(string name) => $"Hello {name}";

// Required name
string Hello([Required]string name) => $"Hello {name}";

// Optional name
string Hello(string name = null) => $"Hello {name}";

// Optional name
string Hello(string? name) => $"Hello {name}";
```

The same would apply for body parameters:

```C#
// Required TodoItem
async Task<IResult> PostTodo(TodoItem todo)
{
    await db.Todos.AddAsync(todo);
    await db.SaveChangesAsync();

    return Created($"/todo/{todo.Id}", todo);
}

// Required TodoItem
async Task<IResult> PostTodo([Required]TodoItem todo)
{
    await db.Todos.AddAsync(todo);
    await db.SaveChangesAsync();

    return Created($"/todo/{todo.Id}", todo);
}

// Optional TodoItem (can be null)
async Task<IResult> PostTodo(TodoItem todo = null)
{
    if (todo is null)
    {
       return UnprocessableEntity();
    }

    await db.Todos.AddAsync(todo);
    await db.SaveChangesAsync();

    return Created($"/todo/{todo.Id}", todo);
}

// Optional TodoItem (can be null)
async Task<IResult> PostTodo(TodoItem? todo)
{
    if (todo is null)
    {
       return UnprocessableEntity();
    }
    await db.Todos.AddAsync(todo);
    await db.SaveChangesAsync();

    return Created($"/todo/{todo.Id}", todo);
}
```

**Comment by davidfowl** [comment]
We've decided to avoid `[Required]` and just support default parameter values and nullability.
