### ISSUE TITLE
Looking for a fixed console output string for spa applications fails...

### ISSUE THREAD

**Issue by rwrife** [dotnet/aspnetcore#32371]
This line of code is looking for a fixed value to determine if the spa application is running behind the scenes is kind of broken in the case of where your node js app does not output that value, in my case we upgrade create-react-app to WebPack 5):

https://github.com/dotnet/aspnetcore/blob/6bc4b79f4ee7af00edcbb435e5ee4c1de349a110/src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L99

Ideally this, at a minimum, should be a configurable value.

**Comment by rwrife** [comment]
Opened a PR https://github.com/dotnet/aspnetcore/pull/32372 but couldn't build since .net core 6.0.100-preview.4.21222.6 is not available.

**Comment by javiercn** [comment]
@rwrife thanks for contacting us.

We are changing the way our SPA templates work to leverage the specific SPA development proxy in favor of our own and we are providing a similar utility to launch the CLI proxy when the app starts or you can choose to run the SPA proxy manually yourself and keep it running.

Our new logic is not based on the console output but on a configurable endpoint we will probe to determine that the proxy is running. You can check out more details [here](https://youtu.be/Nb5lV2i8bCI?t=777)

We recommend folks move to the new approach we are implementing in 6.0 (can be "easily" backported to 5.0) and as a result we don't plan to make updates to the existing logic unless they are blocking mainline scenarios.
