### ISSUE TITLE
.NET 6 Blazor WASM Hot Reload re-launch when a component has a RenderFragment property

### ISSUE THREAD

**Issue by dannykay1710** [dotnet/aspnetcore#32385]
### Describe the bug
Hot Reload doesn't work when your page has a component embedded which populates a RenderFragment parameter of the child component. 

If a component is on the page which has child content, the entire page cannot be updated with hot reload. It fails silently although errors are outputted to the console and no full browser reload is initiated either. {UPDATE: as of preview 4 it no longer fails silently but relaunches)

If the RenderFragment property is not set, the component can be used and hot reload will still work, however as soon as you attempt to set a RenderFragment property the entire page stops working with Child Content.

### To Reproduce

- File New Project - Blazor WebAssembly
- In launchsettings.json add `"hotReloadProfile" : "blazorwasm"` to your launch profile
- Add `[Parameter] public RenderFragment ChildContent { get; set; }` to the Counter.razor page and add the appropriate `@ChildContent` to the markup
- In Index.razor, add the Counter component initially and add some child content
- Run dotnet watch and attempt to make a change to anything within Index.razor. Despite console saying Hot Reload succeeded nothing on the page will change, and the browser window will not refresh.
- You can use Ctrl+R to force a reload which will then show your change.

### Exceptions (if any)

`* Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, condition ``<disabled>' not met`
`Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, condition ``<disabled>' not met`

### Further technical details
- ASP.NET Core version: 6.0.0-preview.3.21201.13
- The IDE: VS Code 1.55.2 & VS 16.10.0 Preview 2.1

dotnet --info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by dannykay1710** [comment]
In preview 4, carrying out the same steps the app now does a full reload of the page, losing user state but at least the page auto-refreshes now.

Is hot reload expected to preserve state in this instance?

**Comment by chucker** [comment]
@dannykay1710 in preview 5, the console output of `dotnet --watch` is a little clearer. If you see messages like:

```
watch : Unable to apply hot reload because of a rude edit. Rebuilding the app...
watch : Unable to handle changes to /Users/chucker/blazor33662/Pages/Form.razor.
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

then I don't think it can preserve any state; it's relaunching. But if it's _not_ a "rude" edit, it can apply the changes to the page without relaunching.

**Comment by dannykay1710** [comment]
@chucker  Yes, I understand that. Though I guess my main issue was that hot releod, as in preserving state, wasn't working when the change could be as simple as a text change

In practice the changing of text in a RenderFragment is a parameter change for the child component, which I would imagine would add'significant complexity even though the change looks simple. I presume this additional complexity is why hot reload today re-launches the app in this scenario.

Interestingly though I do not get a message which says it is a rude edit like your first line, just that it is unable to handle changes.

Changing parameters of components, which is essentially what modifying child content is, seems like a fairly common scenario and that not supporting it could mean that in all but the simplest of applications most changes would cause a full re-launch.

**Comment by dannykay1710** [comment]
So on further looking it appears as long as there is no child content set, you can change parameter values and the change will hot reload and preserve state. 

The point I made originally about it affecting changes to the entire page and not just the component with child content still stands even on preview 5

_If the RenderFragment property is not set, the component can be used and hot reload will still work, however as soon as you attempt to set a RenderFragment property the entire page stops working with Child Content._

```
@page "/"
<h1>Hello, world!!!</h1>

Welcome to your new app. This my new app!!!
<br />

<SurveyPrompt Title="How is Blazor working for you?" />

<Counter IncrementAmount="10">
    Testing 123
</Counter>
```

Hot reload will cause a full relaunch for any change on this entire page - even if the edit is not to the Counter component. As soon as the Counter component doesn't have child content, hot reload with preserved state works again.

`<Counter IncrementAmount="20"></Counter>`

**Comment by pranavkm** [comment]
Thanks for the issue report. For 6.0, this scenario is addressed to some extent. While adding the `RenderFragment` parameter or changing the contents for the render fragment will be rude edits, updating any content outside of the ChildContent will no longer fail and should hot reload correctly. If you grab the latest rc1 builds from https://github.com/dotnet/installer#installers-and-binaries, you should be able to verify this.

For 7.0, we hope to improve the experience further and allow more edits to be made, bringing .NET Core WASM's hot reload closer in parity with .NET Core's.
