### ISSUE TITLE
Missing content for <option> value-attribute reported as error by Visual Studio

### ISSUE THREAD

**Issue by adschm** [dotnet/aspnetcore#32384]
When using `<option value>` without a value assigned to the value attribute, Visual Studio reports "Error: Attribute 'value' on tag helper element 'option' requires a value. Tag helper bound attributes of type 'System.String' cannot be empty or contain only whitespace."

However, this is perfectly valid HTML5, and actually happens to be exactly what Html.DropDownList does when `null` is provided. I'm just not allowed to do it manually.

Note that this is treated as "error", so actually prevents building.

I propose to either remove this restriction completely, or at least reduce it to a warning (since probably only few people actually intend to have a value without value).

If this is reported in the wrong place, please tell me where to report this instead.

Code:

```
    <div class="form-group">
        <label asp-for="LastWorkStationStateId" class="control-label col-md-2"></label>
        <div class="col-md-10">
            <select asp-for="LastWorkStationStateId" class="form-control selectpicker"
                    asp-items="ViewBag.WorkstationStateId">
                <option value>@CNames.NoHighlight</option>
            </select>
            <span asp-validation-for="LastWorkStationStateId" class="text-danger"></span>
        </div>
    </div>
```

**Comment by javiercn** [comment]
@adschm thanks for contacting us.

This is a Visual Studio issue, in order for you to get a better and faster answer we suggest you file the issue from the report an issue dialog in Visual Studio as described [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
