### ISSUE TITLE
Blazor WASM apps should display an error that the current browser isn't supported

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#32410]
### Describe the bug
When trying to run a Blazor WASM app on a freshly installed VM, it fails to load and appears to hang. It is stuck on the "Loading...." screen.

This is because I was using the Legacy Edge (which is installed by default on Azure VMs).

### To Reproduce
1. Create a new Azure VM in DevTest Labs
2. Install VS
3. Create a new Blazor WebAssembly app
4. F5

### Exceptions (if any)
The web page appears to hang and says "Loading...".

In the developer console log, I see `SCRIPT1002: SCRIPT1002: Syntax error`.

### Further technical details
- ASP.NET Core version: 6.0.0-preview.4.21227.6
- Include the output of `dotnet --info`
```
C:\Users\eerhardt>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.4.21227.10
 Commit:    0c7bfd6e76

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21227.10\

Host (useful for support):
  Version: 6.0.0-preview.4.21222.10
  Commit:  bd2d701e75

.NET SDKs installed:
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21227.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21227.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21222.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21223.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 2.1

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
