### ISSUE TITLE
What is the role Nodejs in .NET 5 Blazor WebAssembly

### ISSUE THREAD

**Issue by urza** [dotnet/aspnetcore#32426]
When you create new .NET 5 Blazor WebAssembly project from Visual Studio 2019 and then run it, Windows Firewall asks for permission for Nodejs.

Why do I need Nodejs? What is its role in .net 5 blazor webassembly project and why does it want to connect to internet?? What happens if I don't allow Nodejs in my firewall?

**Comment by javiercn** [comment]
@urza thanks for contacting us.

That's very likely for the debugger. Does it happen if you run without debugging?
