### ISSUE TITLE
Focus Component

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#32424]
HEllo,

Documentation tell us how focus an Html Element:
https://docs.microsoft.com/fr-fr/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#focus-an-element

But what about InputTextComponent ?

Thanks

**Comment by guardrex** [comment]
`ElementReference` is coming for InputX components in 6.0: https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/#input-elementreference-exposed-on-relevant-components

* https://github.com/dotnet/aspnetcore/issues/24446
* https://github.com/dotnet/aspnetcore/pull/24899

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

@guardrex is correct.

**Comment by JulienM28** [comment]
Thanks.
