### ISSUE TITLE
Trusted Root Certificates Store

### ISSUE THREAD

**Issue by tssanikop** [dotnet/aspnetcore#32430]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

OS: Windows 10
Trying to get a basic PWA working using Blazor and I get Adding the certificate to the trusted root certificates store failed with the following error: Failed trusting the certificate.

Checked online for help, found some solutions but none of them worked.
 I get this error if I select BlazorPWA.server and run the project.

If I select IIS Express I just get a blank webpage and an exception exception of type 'microsoft.visualstudio.shared.vscode debug protocol.protocolexception' was thrown.

**Comment by javiercn** [comment]
@tssanikop thanks for contacting us.

This looks like there might be some group policy in your org that is preventing you to add the certificate to the trusted root store. Just to check, is this with Kestrel or with IIS Express?

**Comment by tssanikop** [comment]
This happens when, I select BlazorServer instead of iisexpress. If I select iisexpress then it does not connect validate the certificate. And I do not the + to install option in the browse.

I will check in office, that might be the case as I was working on work laptop.

Thanks,
Teju

**Comment by javiercn** [comment]
@tssanikop You can try and run `dotnet dev-certs https --trust` from the command-line and see if it also fails (it will likely do) and if that's the case, you can try and trust the certificate manually.

`dotnet dev-certs https -ep https.crt` will export the certificate ASP.NET Core uses. With that, you can open the certificate manager (Manage user certificates). Select `Trusted Root Certification Authorities -> Certificates`. right click on it, select `import` and pick the certificate file. If that also fails, it means there is a policy in your system preventing you from doing so, and you'll have to work with your IT admins to add an exception for it
