### ISSUE TITLE
ITicketStore async methods should support cancellation. 

### ISSUE THREAD

**Issue by damianh** [dotnet/aspnetcore#32443]
https://github.com/dotnet/aspnetcore/blob/4d3191176696d69a289ec465c38f2374553ed324/src/Security/Authentication/Cookies/src/ITicketStore.cs#L14-L41

### Describe the bug

These methods should accept a cancellation token. Other async interefaces support cancellation, for example: https://github.com/dotnet/aspnetcore/blob/4d3191176696d69a289ec465c38f2374553ed324/src/Identity/Extensions.Core/src/IUserStore.cs#L14-L22

**Comment by brockallen** [comment]
Woah woah woah, next thing you'll be asking for is that it needs to be in the [DI system](https://github.com/aspnet/AspNetCore/issues/6946)! ;)

**Comment by Tratcher** [comment]
With Default Interface Methods we can do that now and not even break people 😁.

The only relevant CancellationToken to pass into ITicketStore would be the RequestAborted token. Would that be useful in this context? E.g. Abort the retrieve or store operation if the client disconnects?

**Comment by davidfowl** [comment]
Why is that the only relevant token ?

**Comment by Tratcher** [comment]
This is invoked from within the cookie auth handler, it doesn't have any other tokens and isn't directly callable from app code.
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs

**Comment by davidfowl** [comment]
Oh so is there an observable issue?

**Comment by damianh** [comment]
We're implementing it here https://github.com/DuendeSoftware/BFF/blob/adef0c72797d3f92d0e38051df38d0cd2d14eda1/src/Duende.Bff/SessionManagement/ServerSideTicketStore.cs .

When adding cancellation token parameters to various interface methods (https://github.com/DuendeSoftware/BFF/pull/15 ) the chain broke at ITicketStore.

**Comment by davidfowl** [comment]
Makes sense. We should take a look and see where else it's missing.

**Comment by Tratcher** [comment]
@damianh while flowing tokens is fine, I suspect in this case it might be more meaningful for your ITicketStore implementation to provide it's own tokens with timeouts for each operation. Cancelling for a client disconnect will be a relatively small optimization.
