### ISSUE TITLE
Performance delay in Blazor WebAssembly with System.Text.Json.JsonSerializer

### ISSUE THREAD

**Issue by sabari3** [dotnet/aspnetcore#32441]
Hi,

When I perform deserialization for a nested array of double values with System.Text.Json library, the time taken to complete this process is different in Blazor server side application and in Blazor Web Assembly application. When the deserialization is done multiple times, the time delay is huge in web assembly application.

In the server application, the deserialization takes around 0.3 - 0.5 milliseconds. The same code used in the server application takes 5 - 8 seconds in the web assembly application.

Please find the server side application and web assembly application below.

[Server-side application](https://github.com/dotnet/aspnetcore/files/6430155/JsonParseServerApp.zip)
[Web assembly](https://github.com/dotnet/aspnetcore/files/6430159/JsonParseWASM.zip)

Please check this performance issue.

Thanks,
Sabari Anand

**Comment by pranavkm** [comment]
Thank you for your feedback. We generally don't accept zip files for our issue report and would prefer a GitHub repository or set of instructions that detail the issue.

That said, Blazor WebAssembly runs under an interpreter in the browser's sandbox which is less performant compared to .NET Core on the desktop. Depending on the size and complexity of your JSON payload, it's entirely possible to see the sort of drastic differences you're seeing here. 

That said, there are some fairly dramatic (~20%) improvements in the runtime perf, specifically around scenarios such as JSON (de)serialization in .NET 6.0. In addition, as part of 6.0, we're working on adding support for AOT for Blazor WASM which should result in much better performance particularly for compute heavy workloads such as JSON serialization.
