### ISSUE TITLE
IFormFile length in object is not real .NET 5

### ISSUE THREAD

**Issue by gdetra** [dotnet/aspnetcore#32445]
### Describe the bug
Hi guys, 
i'm porting an old Asp Net web api project into a new net 5 web api project.
I have a very strange problem in .net 5 solution with IFormFile. When i try upload a jpg, png or pdf file i get a length bigger than the length of the file in filesystem. It seems that length is about x2 of real length. 
Consequently when a try to download the uploaded file it is corrupted.
Below two screen of the file (the same file) uploaded on asp net project and .net 5 project.

.NET 5 upload file
![bugfilesize (2)](https://user-images.githubusercontent.com/25401025/117216023-648a8f00-adff-11eb-90c5-1ab707fb70bc.jpg)

.NET Framework upload file
![fileaspnet](https://user-images.githubusercontent.com/25401025/117216193-aca9b180-adff-11eb-9220-3fd91a1289c9.png)

### To Reproduce
Simply upload a file with form data.

### Exceptions (if any)
There is no exception

### Further technical details
- ASP.NET Core 5.0
- .NET SDK (che rispecchia un qualsiasi file global.json):
 Version:   5.0.202
 Commit:    db7cc87d51
Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\
Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14
.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Microsoft Visual Studio Professional 2019 Version16.9.4

Thank you for your support

**Comment by davidfowl** [comment]
Can you provide some sample code that reproduces the problem?

**Comment by benaadams** [comment]
Going by screenshot are 4 files in first example and 3 files in second?

**Comment by Tratcher** [comment]
And a Fiddle trace of the request with an example payload.

What client are you using?

**Comment by gdetra** [comment]
I'll share with you a salmple and a link to download the images and files that i used to do the requests.
As client i have used postman with default headers. I only uploaded a file with a name that i use to get it.
For security reason i cannot share with you the real solution but i have repro the problem in this one.

**THIS IS THE SOLUTION**
[WebApplication.zip](https://github.com/dotnet/aspnetcore/files/6432499/WebApplication.zip)

**THIS IS ZIP WITH FILE INSIDE (extract it)**
Try to upload this 3 files the images is bigger then real but the json file is correct.
[request.zip](https://github.com/dotnet/aspnetcore/files/6432594/request.zip)

**Comment by gdetra** [comment]
> Going by screenshot are 4 files in first example and 3 files in second?

sorry by mistake I added one more, but the problem still existed.

**Comment by gdetra** [comment]
> And a Fiddle trace of the request with an example payload.
> 
> What client are you using?

I'm using postman. With Fiddle trace do you mean the software Fiddler? I can download it and share with you the result if it can be useful to investigate on the problem.

**Comment by gdetra** [comment]
> Can you provide some sample code that reproduces the problem?

I shared with you the solution with files to be uploaded too.

**Comment by Tratcher** [comment]
Your RequestResponseLoggerMiddleware is corrupting the files.
```
            using (var bodyReader = new StreamReader(context.Request.Body))
            {
                string body = await bodyReader.ReadToEndAsync();
                var builder = new StringBuilder(Environment.NewLine);

                builder.AppendLine($"========================REQUEST======================== {guid}");
                builder.AppendLine(string.Empty);
                builder.AppendLine("-- REQUEST-HEADERS");
                foreach (var header in context.Request.Headers)
                {
                    builder.AppendLine($"{header.Key}:{header.Value}");
                }
                builder.AppendLine(string.Empty);
                builder.AppendLine("-- REQUEST-BODY");
                builder.AppendLine(body);
                builder.AppendLine(string.Empty);
                builder.AppendLine("=======================================================");

                _logger.LogInformation(builder.ToString());
                context.Request.Body = new MemoryStream(Encoding.UTF8.GetBytes(body));
            }
```

The logs look like this:
```
?5 ?,►??a?ME?I?v??p{?♥??cB??i   ?↔?w??A??U?T(?♣?x#?z?8?v?a♂E¶UQE¶QE¶QE¶QE¶☺¶?lE???L???M?Y♫N??y??0???↨L$i????X??j??.n=?????I♦+♥?¶??ye??  ♥⌂??q?4?F
??J♥??UL?????1m?♥?P?‼??↨?Q~?▲?J?▲?????♥?¶\?8'??I??VLrT?T☼?1????♠#?∟SB9?GP??2A∟?↨??♥▼x?????H??._???M??I?♣?f?_????t??y???d¶c|?h?J??sM???;Yf????J♫☼RRGw{??4?T???z▲??????N?mU♂?@?▼◄k‼?
ZX?}???♫▬?h?M?↑G?↨T'♫#>?¶?‼?Q??y7<?♀♠N?*?I??k?Q?a?M??u'?j??o>?X???F?L?jT?d?a=?LN??J?J?c4?/♂????t?????rO⌂?I?Rj?"yεye<?X?0?v?§J??R→e????¶M?◄?Q?]&???g?]↕C??♫e?E`6?x,b???C∟e?"◄?‼??z?m?>?T?↨v?m(?8???$?O?'R??????▬??6?§O?◄?.? -'????>??▲ºU?♀w?7
?→H??$t?¶jQ??y????'U`??◄↨↓♥??,W??3?!]?3sS?{I??◄????/?d???;;?↔?F▬D?K?G???y????o¶?Mu?s?↕☺??Z????K?????X‼?☼?kA?[X??I??ZS"n?{b??Z`???¶?▬nF↨
,♀?l?Er??f??♫??#?♠??????↕5?0?♠?B?=?♥??rxQ?-,?/??hb↑?c?U?<▼aq§??gP?I???I?'b??Σ>?i<e"y%1☼??\U?|H?n?.?⌂v?$Q?b↨?#?????◄?????U?` ?}j#?[►??]~??????☻???L???♫????(???H↔???Y??  ↕?►y?n?▬▬??DVQ!?♥??;?R??I???If&?s♀7r?#>$S????O¶{?☻>?????‼♣??s?v?s♂?8e?p???ph???/?↕??c\☻y??ypM#♫[?lm?0   ^??%??
‼?\?<VM?e?S????w??S??Y?☻hL?r?mU#cs?qW-⌂{f#????(k+???\?∟o♥☻♫8?j_☼?c?'???????∟W2$kmA$N~O?z?39?cc??????=??[?♂▲?<?4?x?TW?@CwG`?{?F??r*"?♫L_?9C??Jlv↔?????i<?=?'????¶?qv?????????bTE
```

This doesn't round trip when re-encoded. If you really want to buffer the request body like this then use the `HttpRequest.EnableBuffering()` extension to preserve the original bytes rather than re-encoding the text.

**Comment by gdetra** [comment]
> Your RequestResponseLoggerMiddleware is corrupting the files.
> 
> ```
>             using (var bodyReader = new StreamReader(context.Request.Body))
>             {
>                 string body = await bodyReader.ReadToEndAsync();
>                 var builder = new StringBuilder(Environment.NewLine);
> 
>                 builder.AppendLine($"========================REQUEST======================== {guid}");
>                 builder.AppendLine(string.Empty);
>                 builder.AppendLine("-- REQUEST-HEADERS");
>                 foreach (var header in context.Request.Headers)
>                 {
>                     builder.AppendLine($"{header.Key}:{header.Value}");
>                 }
>                 builder.AppendLine(string.Empty);
>                 builder.AppendLine("-- REQUEST-BODY");
>                 builder.AppendLine(body);
>                 builder.AppendLine(string.Empty);
>                 builder.AppendLine("=======================================================");
> 
>                 _logger.LogInformation(builder.ToString());
>                 context.Request.Body = new MemoryStream(Encoding.UTF8.GetBytes(body));
>             }
> ```
> 
> The logs look like this:
> 
> ```
> ?5 ?,►??a?ME?I?v??p{?♥??cB??i   ?↔?w??A??U?T(?♣?x#?z?8?v?a♂E¶UQE¶QE¶QE¶QE¶☺¶?lE???L???M?Y♫N??y??0???↨L$i????X??j??.n=?????I♦+♥?¶??ye??  ♥⌂??q?4?F
> ??J♥??UL?????1m?♥?P?‼??↨?Q~?▲?J?▲?????♥?¶\?8'??I??VLrT?T☼?1????♠#?∟SB9?GP??2A∟?↨??♥▼x?????H??._???M??I?♣?f?_????t??y???d¶c|?h?J??sM???;Yf????J♫☼RRGw{??4?T???z▲??????N?mU♂?@?▼◄k‼?
> ZX?}???♫▬?h?M?↑G?↨T'♫#>?¶?‼?Q??y7<?♀♠N?*?I??k?Q?a?M??u'?j??o>?X???F?L?jT?d?a=?LN??J?J?c4?/♂????t?????rO⌂?I?Rj?"yεye<?X?0?v?§J??R→e????¶M?◄?Q?]&???g?]↕C??♫e?E`6?x,b???C∟e?"◄?‼??z?m?>?T?↨v?m(?8???$?O?'R??????▬??6?§O?◄?.? -'????>??▲ºU?♀w?7
> ?→H??$t?¶jQ??y????'U`??◄↨↓♥??,W??3?!]?3sS?{I??◄????/?d???;;?↔?F▬D?K?G???y????o¶?Mu?s?↕☺??Z????K?????X‼?☼?kA?[X??I??ZS"n?{b??Z`???¶?▬nF↨
> ,♀?l?Er??f??♫??#?♠??????↕5?0?♠?B?=?♥??rxQ?-,?/??hb↑?c?U?<▼aq§??gP?I???I?'b??Σ>?i<e"y%1☼??\U?|H?n?.?⌂v?$Q?b↨?#?????◄?????U?` ?}j#?[►??]~??????☻???L???♫????(???H↔???Y??  ↕?►y?n?▬▬??DVQ!?♥??;?R??I???If&?s♀7r?#>$S????O¶{?☻>?????‼♣??s?v?s♂?8e?p???ph???/?↕??c\☻y??ypM#♫[?lm?0   ^??%??
> ‼?\?<VM?e?S????w??S??Y?☻hL?r?mU#cs?qW-⌂{f#????(k+???\?∟o♥☻♫8?j_☼?c?'???????∟W2$kmA$N~O?z?39?cc??????=??[?♂▲?<?4?x?TW?@CwG`?{?F??r*"?♫L_?9C??Jlv↔?????i<?=?'????¶?qv?????????bTE
> ```
> 
> This doesn't round trip when re-encoded. If you really want to buffer the request body like this then use the `HttpRequest.EnableBuffering()` extension to preserve the original bytes rather than re-encoding the text.

I've tried this code both on mac and windows. The result is that on mac it works, but on windows no.
On windows the request body length is 0 every time.
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace WebApplication2.Middlewares
{
    public class RequestResponseLoggerMiddleware
    {
        private readonly RequestDelegate _next;

        private readonly ILogger<RequestResponseLoggerMiddleware> _logger;

        public RequestResponseLoggerMiddleware(RequestDelegate next, ILogger<RequestResponseLoggerMiddleware> logger)
        {
            _next = next;
            _logger = logger;
        }

        public async Task Invoke(HttpContext context)
        {
            context.Request.EnableBuffering();

            var guid = Guid.NewGuid();
            await LogRequest(context, guid);
            await LogResponseAndInvokeNext(context, guid);
            
        }

        private async Task LogRequest(HttpContext context, Guid guid)
        {
            var stream = context.Request.Body;
            using (var bodyReader = new StreamReader(context.Request.Body,leaveOpen:true))
            {
                string body = await bodyReader.ReadToEndAsync();
                var builder = new StringBuilder(Environment.NewLine);

                builder.AppendLine($"========================REQUEST======================== {guid}");
                builder.AppendLine(string.Empty);
                builder.AppendLine("-- REQUEST-HEADERS");
                foreach (var header in context.Request.Headers)
                {
                    builder.AppendLine($"{header.Key}:{header.Value}");
                }
                builder.AppendLine(string.Empty);
                builder.AppendLine("-- REQUEST-BODY");
                builder.AppendLine(body);
                builder.AppendLine(string.Empty);
                builder.AppendLine("=======================================================");

                _logger.LogInformation(builder.ToString());

                
            }
            stream.Position = 0;
            await _next.Invoke(context);
        }

        private async Task LogResponseAndInvokeNext(HttpContext context, Guid guid)
        {
            using (var buffer = new MemoryStream())
            {
                var stream = context.Response.Body;
                context.Response.Body = buffer;

                

                buffer.Seek(0, SeekOrigin.Begin);
                var reader = new StreamReader(buffer);
                using (var bufferReader = new StreamReader(buffer))
                {
                    string body = await bufferReader.ReadToEndAsync();
                    buffer.Seek(0, SeekOrigin.Begin);
                    await buffer.CopyToAsync(stream);
                    context.Response.Body = stream;

                    var builder = new StringBuilder(Environment.NewLine);
                    builder.AppendLine($"========================RESPONSE======================== {guid}");
                    builder.AppendLine(string.Empty);
                    builder.AppendLine("-- RESPONSE-HEADERS");
                    foreach (var header in context.Request.Headers)
                    {
                        builder.AppendLine($"{header.Key}:{header.Value}");
                    }
                    builder.AppendLine(string.Empty);
                    builder.AppendLine("-- RESPONSE-BODY");
                    builder.AppendLine(body);
                    builder.AppendLine(string.Empty);
                    builder.AppendLine("=======================================================");

                    _logger.LogInformation(builder.ToString());
                }
            }
        }
    }

    public static class RequestResponseLoggingMiddlewareExtensions
    {
        public static IApplicationBuilder UseRequestResponseLogging(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<RequestResponseLoggerMiddleware>();
        }
    }
}
```

**Comment by davidfowl** [comment]
That response buffering code is broken. You have to set up the response buffer before you call next.

**Comment by davidfowl** [comment]
It functions but is extremely inefficient. We're writing a new logging middleware that does similar things but in a more efficient way for .net 6

**Comment by gdetra** [comment]
I'll wait for it. Thank you guys.🙏
