### ISSUE TITLE
Blazor does not target scoped css when html is rendered as a MarkupString

### ISSUE THREAD

**Issue by royberris** [dotnet/aspnetcore#32462]
### Describe the bug
When you render HTML elements with the `MarkupString` the scoped CSS is not applied to the elements. I don't know if this is intended.

### To Reproduce

https://github.com/royberris/BlazorCssScopedBug/commit/2dedea0d5136b4377d98a616537322168d9e3057

I created a Blazor project from the template using `net5.0`. In the linked commit I added the files where the problem is. 

Screenshot:

![image](https://user-images.githubusercontent.com/25608596/117302687-326b4280-ae7c-11eb-8f62-c33ec2afd4f8.png)

### Further technical details
- ASP.NET Core version `net5.0`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `VS `

**Comment by javiercn** [comment]
@royberris thanks for contacting us.

That's by design. Scoped css is a build time step and only applies to markup in the razor file, not to string literals in your code.

**Comment by meziantou** [comment]
A workaround is to fix the scope name ([Customize scope identifier format](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003978#customize-scope-identifier-format)) and use this attribute when creating the MarkupString. You can find an example here: [Using raw html with isolated CSS in Blazor](https://www.meziantou.net/using-raw-html-with-isolated-css-in-blazor.htm)
