### ISSUE TITLE
 Blazor Server Net Core 5 -  Users are autheticated with wrong user account Because of Memory Cache or Identity ?

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/aspnetcore#32474]
We have a Blazor Server App .NET 5.0 , Latest Version with a strange situation and we can't figure it out : After Login in some strange situations some Users are logged in with wrong user account and they see the Info Account from another users .
We couldn't find this situation in normal testing , but we received a lot of complains .

In our situation, this can be because of  :

1. **Memory Cache** Doesn't Work Well in .razor Files. (We are using this to avoid database access wheb double rendering  )
2. **Identity** returns wrong user for a a given .AspNetCore.Identity.Application Cookie ? 

**1. Memory Cache :** (For the moment we choose to disable Memory Cache to see if this is the problem)

It is there any chance to get Wrong Memory Cache Values or same Values for Different Users with different PC and different keys ? if we are using Memory Cache in a .razor files  ?

```
// MainLayout.razor
 async Task RefreshUser()
    {
        Authentication = await _AuthenticationStateTask;
        if (Authentication.User.Identity.IsAuthenticated)
        {          
            if (!_MainApp.PageState.IsBlazorConnected && !IsRendered)
            {
               var key = $"{_MainApp.PageState.CacheKeyGuid}{nameof(_ApplicationUserService.GetApplicationUserByUserName)}{Authentication.User.Identity.Name}";
                // CacheKeyGuid is an unique guid
                ApplicationUser = await _MemoryCache.GetOrCreateAsync(key , async entry =>
                {
                    entry.SetOptions(new MemoryCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(4) });
                    return await _ApplicationUserService.GetApplicationUserByUserName(Authentication.User.Identity.Name);
                });               
            }
            else
            {
                ApplicationUser = await _ApplicationUserService.GetApplicationUserByUserName(Authentication.User.Identity.Name);
            }
           
        }
        else
        {
            ApplicationUser = null;
     }
}
```

2. **Identity**  Is there any chance to return a  different user for a given .AspNetCore.Identity.Application cookie ?

We are using Default Identity and because we didn't like the Login through redirect we implemented a custom ApiAuthenticationStateProvider who is calling a controller through post to Login User and get  Current User.

**Configuration** 

```
services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
            {
                options.Lockout.AllowedForNewUsers = true;
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireDigit = false;              
            })
              .AddEntityFrameworkStores<ApplicationDbContext>()
              .AddDefaultTokenProviders();

services.AddAuthentication();
services.AddScoped<AuthenticationStateProvider, ApiAuthenticationStateProvider>();
....
app.UseAuthentication();
app.UseAuthorization();
```

**ApiAuthenticationStateProvider** :

```
  public class ApiAuthenticationStateProvider : AuthenticationStateProvider
    {
        string SecurityTimeStamp;
        string AuthenticationCookie;
        public ApiAuthenticationStateProvider(ApplicationUserService applicationUserService, IHttpClientFactory clientFactory)
        {
            _ClientFactory = clientFactory;            
        }

        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            return await Task.FromResult(new AuthenticationState(new ClaimsPrincipal(await GetCurrentUserIdentity())));
        }
        
        public async Task<ClaimsIdentity> GetCurrentUserIdentity()
        {
            ClaimsIdentity identity = new ClaimsIdentity();
            var InitialStateFromBowserForLoginSecurityTimeStamp = IsInitialStateFromBrowser;
            if (string.IsNullOrEmpty(AuthToken) && IsInitialStateFromBrowser && string.IsNullOrEmpty(TimeStamp))
            {
                AuthToken = AuthenticationCookie ;
               IsInitialStateFromBrowser = false;
            }

            if (!string.IsNullOrEmpty(AuthToken) && (InitialStateFromBowserForLoginSecurityTimeStamp || !string.IsNullOrEmpty(TimeStamp)))
            {
                var client = _ClientFactory.CreateClient();
                if (IsStateFromLogin)
                {
                    client.DefaultRequestHeaders.Add("Cookie", AuthToken);
                }
                else
                {
                    client.DefaultRequestHeaders.Add("Cookie", _ApplicationUserService._Settings.AuthenticationCookie + "=" + AuthToken);
                }

                var url = NavigationManager.ToAbsoluteUri($"/api/LogInOut/GetCurrentUserPost");
                var CurrentUserResult =  await client.PostJsonAsync<CurrentUserResult>(url.ToString(), new CurrentUserResult() { ID=ID, TimeStamp = TimeStamp, IsInitialStateFromBrowser = InitialStateFromBowserForLoginSecurityTimeStamp, ManageMessageId = ManageMessageId.GetCurrentIdentity.ToString() });
                
                if (CurrentUserResult != null && CurrentUserResult.ID !=default)
                {
                    var userFinded = await _ApplicationUserService.GetApplicationUserByUserNameFromCache(CurrentUserResult.ID);
                    if (userFinded != null   && userFinded.UserName == CurrentUserResult.ID && userFinded.LoginSecurityTimeStamp == CurrentUserResult.TimeStamp)
                    {
                        TimeStamp = userFinded.LoginSecurityTimeStamp;
                        ID = userFinded.UserName;

                        var claims = new List<Claim>();
                        claims.Add(new Claim(ClaimTypes.Name, userFinded.UserName));

                        var roles = await _ApplicationUserService.GetUserRoles(userFinded.Id);

                        foreach (var item in roles ?? new List<ApplicationRole>())
                        {
                            claims.Add(new Claim(ClaimTypes.Role, item.Name));
                        }

                        identity = new ClaimsIdentity(claims, "ApiAuthenticationStateProvider");
                    }
                }
            }

            return identity;
        }

        public async Task MarkUserAsAuthenticated(string id, string token, string timestamp)
        {
            _ApplicationUserService.ClearEvictionGroupCache();
            ID = id;
            AuthToken = token;
            TimeStamp = timestamp;
            IsStateFromLogin = true;
            var user = new ClaimsPrincipal(await GetCurrentUserIdentity());
            NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(user)));
        }

        public void MarkUserAsLoggedOut()
        {
            _ApplicationUserService.ClearEvictionGroupCache();
            AuthToken = null;
            TimeStamp = null;
            ID = null;
            var identity = new ClaimsIdentity();
            var user = new ClaimsPrincipal(identity);
            NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(user)));
        }

// Set by Main App
      public void SetSecurityTimeStampAndAuthenticationCookie(string timestamp, string cookie)
        {
           SecurityTimeStamp = timestamp;
           AuthenticationCookie = cookie;
        }  
    }
```
**Controller**

    [Route("api/[controller]")]
    public class LogInOutController : Controller
    {  
        private readonly SignInManager<ApplicationUser> _SignInManager;
        private readonly ApplicationUserService _ApplicationUserService;
        public readonly WebSiteSettings _Settings;
        public readonly IServiceProvider _ServiceProvider;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        public LogInOutController(IServiceProvider serviceProvider, SignInManager<ApplicationUser> signInManager, ApplicationUserService applicationUserService, IOptions<WebSiteSettings> Settings, IHttpContextAccessor httpContextAccessor)
        {
            
            _SignInManager = signInManager;
            _ApplicationUserService = applicationUserService;
            _Settings = Settings.Value;
            _ServiceProvider = serviceProvider;
            _HttpContextAccessor = httpContextAccessor;
        }
 
        [HttpPost]
        [Route("LoginUser")]
        public async Task<JsonResult> LoginUser([FromBody] LoginModel model)
        {
            if (ModelState.IsValid && model.ManageMessageId == ManageMessageId.LoginIdentity.ToString() && !string.IsNullOrEmpty(model.Username))
            {
                var result = await _SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    var timeStamp = Guid.NewGuid().ToString();
                    if (await _ApplicationUserService.UpdateApplicationUserLoginSecurityTimeStamp(model.Username, timeStamp))
                    {
                        return Json(new LoginResult() { ID = model.Username, AuthenticationCookie = _HttpContextAccessor.HttpContext.Response.Headers["Set-Cookie"].ToString(), TimeStamp = timeStamp, ManageMessageId = ManageMessageId.LoginSuccess.ToString() });
                    }
                }
            }
            await _HttpContextAccessor.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            await _HttpContextAccessor.HttpContext.SignOutAsync();
            await _SignInManager.SignOutAsync();
            return Json(new LoginResult());
        }   
        
        [HttpPost]      
        [Route("GetCurrentUserPost")]
        public async Task<JsonResult> GetCurrentUserPost([FromBody] CurrentUserResult result)
        {
            if (result != null && result.ManageMessageId == ManageMessageId.GetCurrentIdentity.ToString())
            {
                if (_HttpContextAccessor.HttpContext.User != null && !string.IsNullOrEmpty(_HttpContextAccessor.HttpContext.User.Identity.Name) && _HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                {               
                    ApplicationUser userFinded = null;
                    using (var scope = _ServiceProvider.CreateScope())
                    {
                        var context = scope.ServiceProvider.GetService<ApplicationDbContext>();
                        userFinded = await context.Users.Where(p => p.UserName == _HttpContextAccessor.HttpContext.User.Identity.Name)
                                                        .Select(p=> new ApplicationUser 
                                                        { 
                                                            UserName=p.UserName, 
                                                            LoginSecurityTimeStamp=p.LoginSecurityTimeStamp 
                                                        }
                                                        ).AsNoTracking().FirstOrDefaultAsync();
                    }
                       
                    if (userFinded != null && (result.IsInitialStateFromBrowser || (result.TimeStamp == userFinded.LoginSecurityTimeStamp && result.ID == userFinded.UserName)))
                    {
                        result.ID = userFinded.UserName;
                        result.TimeStamp = userFinded.LoginSecurityTimeStamp;
                        return Json(result);
                    }
                }
            }
            await _HttpContextAccessor.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            await _HttpContextAccessor.HttpContext.SignOutAsync();
            await _SignInManager.SignOutAsync();
            return Json(new CurrentUserResult());
        }
}

**Comment by javiercn** [comment]
@lucianparvu thanks for contacting us.

Could you please instead host a minimal repro project on a public github repository? Looking at chunks of code so large on an issue makes it really hard for us to understand what's going on and makes it really easy for us to miss something important.

**Comment by lucianparvu** [comment]
Thank's 

I'll try , but it will take some time .

Meanwhile I have simplified my question and code  and maybe you can answer to that .

1. **Memory Cache**: It is safe to inject Memory cache into .razor Files ? and use it ? Can this give wrong Values or same values for different users ?

//.razor 
@inject IMemoryCache _MemoryCache

```
await _MemoryCache.GetOrCreateAsync($"{PageState.CacheKeyGuid}{nameof(_ApplicationUserService.GetApplicationUserByUserName)}{Authentication.User.Identity.Name}", async entry =>
                    {
                        entry.SetOptions(new MemoryCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(4) });
                        return await _ApplicationUserService.GetApplicationUserByUserName(Authentication.User.Identity.Name);

                    });
```

2. If we use **Identity** to get  .AspNetCore.Identity.Application Cookie after User Sign In ( through javascript) calling an api controller ( HttpContextAccessor.HttpContext.Response.Headers["Set-Cookie"].ToString()) and use it later to check if user is Authenticated, can this cookie be the same for different users  or return different user ?

**Example for calling GetCurrentUser from Api  Controller with Cookie AuthenticationCookie in Header**

```
var client = _ClientFactory.CreateClient();
client.DefaultRequestHeaders.Add("Cookie", AuthenticationCookie );                        
var CurrentUserResult = await client.PostJsonAsync<CurrentUserResult>($"/api/LogInOut/GetCurrentUserPost", new CurrentUserResult() { });

```

**Api Controller Code Example For Login and GetCurrentUser** :

```
[Route("api/[controller]")]
public class LogInOutController : Controller
{  
    private readonly SignInManager<ApplicationUser> _SignInManager;
    private readonly ApplicationUserService _ApplicationUserService; 
    public readonly IServiceProvider _ServiceProvider;
    private readonly IHttpContextAccessor _HttpContextAccessor;
    public LogInOutController(IServiceProvider serviceProvider, SignInManager<ApplicationUser> signInManager,  IOptions<WebSiteSettings> Settings, IHttpContextAccessor httpContextAccessor)
    {
        
        _SignInManager = signInManager;       
        _Settings = Settings.Value;
        _ServiceProvider = serviceProvider;
        _HttpContextAccessor = httpContextAccessor;
    }

    [HttpPost]
    [Route("LoginUser")]
    public async Task<JsonResult> LoginUser([FromBody] LoginModel model)
    {
            var result = await _SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, lockoutOnFailure: false);
            if (result.Succeeded)
            {
              // Get Identity Cookie From HttpContextAccessor.HttpContext.Response.Headers and pass it back
               var AuthenticationCookie =  _HttpContextAccessor.HttpContext.Response.Headers["Set-Cookie"].ToString()
                return Json(new LoginResult() {  AuthenticationCookie =  AuthenticationCookie });
            }
        await _HttpContextAccessor.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
        await _HttpContextAccessor.HttpContext.SignOutAsync();
        await _SignInManager.SignOutAsync();
        return Json(new LoginResult());
    }   
    
    [HttpPost]      
    [Route("GetCurrentUserPost")]
    public async Task<JsonResult> GetCurrentUserPost([FromBody] CurrentUserResult result)
    {
              if (_HttpContextAccessor.HttpContext.User != null && !string.IsNullOrEmpty(_HttpContextAccessor.HttpContext.User.Identity.Name) && _HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                {
                        result.ID = _HttpContextAccessor.HttpContext.User.Identity.Name;
                        return Json(result);                 
                }           
        await _HttpContextAccessor.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
        await _HttpContextAccessor.HttpContext.SignOutAsync();
        await _SignInManager.SignOutAsync();
        return Json(new CurrentUserResult());
    }
```
