### ISSUE TITLE
Arpow: GenerateFileFromTemplate task causes BuildTools prebuilt

### ISSUE THREAD

**Issue by dseefeld** [dotnet/aspnetcore#32492]
### Describe the bug
The `GenerateFileFromTemplate` task is defined in BuildTools, which isn't built with source-build.  This will be reported as a prebuilt in Arpow when building offline and when prebuilt reporting is turned on.  This task should either be moved to Arcade or moved into RepoTasks to ensure it can build and be used with source-build.

### To Reproduce
When Arpow source-build CI is included (see https://github.com/dotnet/aspnetcore/issues/31445), in the generated results (`Microsoft.SourceBuild.Intermediate.aspnetcore.*.nupkg`), the file `prebuilt-report/annotated-usage.xml` will contain a reference to BuildTools, indicating that this is a prebuilt.

**Comment by dougbu** [comment]
Resolution requires dotnet/arcade#7403 and adoption of the new package in this repo. Assigning to @JunTaoLuo since he owns at least the first (larger) part of this.
