### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/InvalidOperationException/1410014)._

---
From time to time, lots of features report an InvalidOperationException.

! [image.png] (https://aka.ms/dc/image?name=B909a1b72fb26460c8e65958ac2fc3c5d637552143407519713_20210428-154540-image.png&tid=909a1b72fb26460c8e65958ac2fc3c5d637552143407519713)

---
#### Feedback Bot on 4/28/2021, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
