### ISSUE TITLE
Validation (CSS 4.0) warnings appear when using ::deep with Blazor CSS Isolation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32500]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Validation-CSS-40-warnings-appear-whe/1415231)._

---
[severity:It's more difficult to complete my work]
As the title says, Validation (CSS 4.0) warnings appear when using ::deep with Blazor CSS Isolation files.

::deep itself is a violation of the validation, but it's removed when the scoped css is created. In CSS files that end in .razor.cs, this warning should be suppressed.

Otherwise, this creates a lot of white noise in the Error List for Blazor css files, which heavily reduces the visibility of genuine warnings.

---
#### Feedback Bot on 5/6/2021, 08:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@mkArtakMSFT this is not for our team to handle.

This happens in Visual Studio because they don't know about the `::deep` semantics. So they should provide a way for disabling the warning if we think it's important enough.
