### ISSUE TITLE
Debugger Blazer Client side

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32505]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Debugger-Blazer-Client-side/1413485)._

---
The problem I am having is when I run this Blazer application it executes the code that is highlighted for the break point but it's not stopping there, like it ignores that there is a break point completely.
How can I solve that?

! [image.png] (https://aka.ms/dc/image?name=B0d3a4ae91a134726a9d2ac0c10f6db28637557531549797705_20210504-152553-image.png&tid=0d3a4ae91a134726a9d2ac0c10f6db28637557531549797705)

---
#### Feedback Bot on 5/6/2021, 02:32 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by captainsafia** [comment]
It looks like the referenced ticket attached to this is missing all the logs so it's hard to reason about where this should be directed to and the screenshot doesn't provide much help.

Can you share a repro?
