### ISSUE TITLE
Add a parameterless overload to AddHttpLogging() with some reasonable defaults

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#32507]
Currently you have to configure options to call AddHttpLogging(). Calling `builder.Services.AddHttpLogging(_ => { });` works, but it's ugly. We should add a parameterless overload to AddHttpLogging() that does something reasonable.

@jkotalik

**Comment by jkotalik** [comment]
You don't need to call AddHttpLogging() at all if you just want the defaults, hence we didn't add a parameterless overload.

**Comment by danroth27** [comment]
Ah, that makes sense. I tried just adding the middleware originally, but it didn't work. I think now that was because the default logging levels in app settings weren't set to Information.

**Comment by BrennanConroy** [comment]
Triage: We think this is fine as is, closing.
