### ISSUE TITLE
An AuthorizationHandler gets executed twice if a global AuthorizeFilter is also present

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/aspnetcore#32518]
Hi everyone,
in a ASP.NET Core for .NET 5 application, suppose we have a very basic `AuthorizationHandler` like this one.
```csharp
public class CustomRequirementAuthorizationHandler : AuthorizationHandler<CustomRequirement>
{
  protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, CustomRequirement requirement)
  {
    // This gets called twice
    // First time with a context.Resource of type Microsoft.AspNetCore.Http.DefaultHttpContext
    // Second time with a context.Resource of type Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.AuthorizationFilterContextSealed
    context.Succeed(requirement);
    return Task.CompletedTask;
  }
}
```

Its `HandleRequirementAsync` method gets executed twice if I also add a global `AuthorizeFilter` like so:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers(config =>
    {
        var policy = new AuthorizationPolicyBuilder().RequireAssertion(context => true).Build();
        config.Filters.Add(new AuthorizeFilter(policy));
    });

    services.AddAuthorization(options =>
    {
        options.AddPolicy("MyPolicy", builder =>
        {
            builder.AddRequirements(new CustomRequirement());
        });
    });
    services.AddSingleton<IAuthorizationHandler, CustomRequirementAuthorizationHandler>();
}
```
The policy is applied to an MVC action like so:
```csharp
public class HomeController : Controller
{
  [Authorize(Policy = "MyPolicy")]
  public IActionResult Index()
  {
    return Content("Ok");
  }
}
```

A repro is here
https://github.com/BrightSoul/AuthorizationHandlerMultipleInvocations

I'm not sure if this is intended behavior or not but it seems somewhat strange that the same logic gets executed twice within the scope of the same HTTP request. This could lead to reduced performance when executing time expensive operations in the `HandleRequirementAsync` method (e.g. database access).

**Comment by pranavkm** [comment]
Yup, this is by design. Starting in 3.1, authorization attributes are handled by the [authorization middleware](https://github.com/BrightSoul/AuthorizationHandlerMultipleInvocations/blob/master/Startup.cs#L63) instead of being evaluated by MVC's authorization filter. However if you explicitly add an `AuthorizationFilter`, it would get separately executed.

Instead of adding a AuthorizationFilter, consider using using `RequireAuthorization` on an endpoint: e.g.

```C#
endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}").
   RequireAuthorization("some_policy");
```

This would a substitute to adding a global auth filter.

**Comment by BrightSoul** [comment]
Thanks @pranavkm for your detailed answer. 

> Instead of adding a AuthorizationFilter, consider using using RequireAuthorization on an endpoint: e.g.
Yes, that's perfect! My authorization handler is being invoked just once now.

I could close the issue now but I wonder if this can be an occasion for improving the documentation. I got a bit off-track by [this page in the docs](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#require-authenticated-users) which is not mentioning your solution. I wonder if your code sample could be added to it.

Again, thanks!
