### ISSUE TITLE
a question about an unexpected behavior of web job singleton lock

### ISSUE THREAD

**Issue by Liphi** [dotnet/aspnetcore#32513]
Hi, we have deployed 3 regions of web apps, and each region has 1 instance of the same timer-triggered web job running. The distributed lock to guarantee singleton is backed by the AzureWebJobsStorage storage account. I find when this storage account is available, singleton works. But when this storage account is unavailable (for example, incorrect connection string causes auth error, storage account service down causes service unavailable error, etc), all 3 regional instances of web job run. But our requirement is at any time only up to 1 instance runs.
Is there any configuration knob to tune this behavior, so that when AzureWebJobsStorage is not available, no instance runs, instead of all instances running?

**Comment by davidfowl** [comment]
You can file that issue here https://github.com/Azure/azure-webjobs-sdk
