### ISSUE TITLE
Minimal Actions - array support in method signatures from querystring binding

### ISSUE THREAD

**Issue by jchannon** [dotnet/aspnetcore#32516]
### Describe the bug
When using the ASPP.NET 6 minimal hosting, querystring binding does not work with arrays/lists

### To Reproduce
```csharp

app.MapGet("/qs/{id:int}", HttpHandlers.GetByQueryString);

public static string GetByQueryString(int id, string name, int[] values)
{
    return id + " " + name + string.Join(",", values);
}
```

Adding `[FromQuery(Name = "values")]` to the method signature does not help either.

### Exceptions (if any)
An exception is thrown when sending in a request:

`curl http://localhost:5000/qs/123\?name\=dave\&values\=1\&values\=2`

`Unhandled exception. System.InvalidOperationException: No public static bool Int32[].TryParse(string, out Int32[]) method found for values.`

### Further technical details
- ASP.NET Core version 6
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21252.2
 Commit:    921395c33e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /Users/jonathan/.dotnet/sdk/6.0.100-preview.5.21252.2/

Host (useful for support):
  Version: 6.0.0-preview.5.21251.4
  Commit:  d2fba8fdc4

.NET SDKs installed:
  2.1.809 [/Users/jonathan/.dotnet/sdk]
  3.1.401 [/Users/jonathan/.dotnet/sdk]
  3.1.403 [/Users/jonathan/.dotnet/sdk]
  5.0.103 [/Users/jonathan/.dotnet/sdk]
  6.0.100-preview.5.21229.26 [/Users/jonathan/.dotnet/sdk]
  6.0.100-preview.5.21252.2 [/Users/jonathan/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21229.9 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21230.5 [/Users/jonathan/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21229.1 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21251.4 [/Users/jonathan/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by davidfowl** [comment]
Would this only be for simple types? Today we don't support any complex types for model binding and it conflicts with [this idea](https://github.com/dotnet/aspnetcore/issues/32376)

**Comment by jchannon** [comment]
Yup simple types only imo, it's a query string, you shouldn't be doing crazy stuff like json binding. I mean there's nothing stopping someone adding json in a querystring I just don't think the framework should support that

**Comment by halter73** [comment]
What collection types should we support?

What should we do if we know the param comes from the route? Fail at startup? Provide a single-element array?

**Comment by DamianEdwards** [comment]
With the newly added support for `BindAsync(HttpContext)` on the target parameter type it would be easy to support this in the app or a library via a custom type, e.g. `MultiValueQuery values`, where `MultiValueQuery` has a `BindAsync` method on it.

**Comment by davidfowl** [comment]
@halter73 

> What collection types should we support?

This is where this typically falls of the rails. There are *A LOT* of collection types including custom types that implement collection interfaces. It's possible we can do something like pattern match a `.Add` method similar to what the [ConfigurationBinder](https://github.com/dotnet/runtime/blob/09ff1acdad2e7789908b5db9bb89896144c13042/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L500) does.

This currently also conflicts with JSON bodies sent as arrays so it would need to be explicitly declared as `[FromQuery]` in order to make this work.

@JamesNK I'd like your feedback here.

> What should we do if we know the param comes from the route? Fail at startup? Provide a single-element array?

I think fail. This should work for headers and query but not route.

**Comment by davidfowl** [comment]
@jchannon This is supported in .NET 7 preview1

**Comment by davidfowl** [comment]
I mean preview2

**Comment by legistek** [comment]
Previously (in Framework) you could serialize an array of primitives to a JSON object in the query string like this:

`?values=[1,2,3,4,5]`

(escaped obviously)

and the method:

`DoSomething(int[] values)`

would bind correctly. That doesn't appear to be the case in .NET6 (or possibly earlier). I assume that was a known breaking change but I thought it worth asking? If it was not an intentional change then it's a different bug I guess.

**Comment by davidfowl** [comment]
This issue isn't about MVC's binding semantics and minimal API supports a subset of what MVC supports. If you want to see what is supported for MVC today look at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections

**Comment by legistek** [comment]
Thanks. Sorry this seemed like the closest issue to what I'm experiencing that wasn't locked by the bots.

**Comment by davidfowl** [comment]
> Thanks. Sorry this seemed like the closest issue to what I'm experiencing that wasn't locked by the bots.

😄. FWIW, it's not supported in MVC either.
