### ISSUE TITLE
Bootstrap Intellisense in razor files

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/aspnetcore#32519]
hey. why does the intellisense in razor files (blazor project) does not works?
I checked this issue https://github.com/dotnet/aspnetcore/issues/5568 but that does not works too.

any solution I could use bootstrap intellisense in razor files?

**Edit**
I created a index.html file inside and the intellisense worked. so it has to be the .razor file that dont support intellisense.

**Comment by javiercn** [comment]
@HeroinGyrl thanks for contacting us.

This is a Visual Studio issue. In order for you to get a better and faster answer we suggest you report it through the report a problem dialog as described [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#:~:text=In%20Visual%20Studio%2C%20select%20the,Send%20Feedback%20%3E%20Report%20a%20Problem.)
