### ISSUE TITLE
Infinite Parameters for Unmarshalled JS Invokes

### ISSUE THREAD

**Issue by mruch2** [dotnet/aspnetcore#32521]
My request is simple to explain, I would like the ability to have an unlimited amount of arguments passed to JS functions through the invoke unmarshalled call found under the IJSUnmarshalledRuntime.  Working with Blazor and Three.js we have large amounts of calculated data and the only way we get around lag is by using the unmarshalled method. The problem is we are required to make multiple calls to JS as currently only 3 parameters are allowed.

**Comment by manigandham** [comment]
Can't you send an array containing all of your data as a single parameter?

**Comment by mruch2** [comment]
I could but the other interops already function as I am describing. It
would be nice if they all worked the same as we use the different tiers
throughout. Kind of why I listed it as an enhancement.

Plus putting an array of objects together to break them apart on the
otherside and then feed the parameters on, kind of a waste of time as you
can run the functions async. More cost affective.

**Comment by javiercn** [comment]
@mruch2 thanks for contacting us.

Unfortunately, unmarshalled JS interop is a contract between the .NET runtime in Webassembly and Blazor, which requires much more work for us to change.

I'm not sure if there are low-level alternatives that you could leverage to pack args into a struct and receive them that way on the .NET side.

@SteveSandersonMS might have more ideas.

Keep in mind that all this is going through "unsupported" interop paths.

**Comment by SteveSandersonMS** [comment]
The request certainly makes sense, but we have to make careful tradeoffs here. Unmarshalled interop is first and foremost about gaining perf by willing to reduce developer convenience. We're unlikely to make design changes that hurt perf in favour of convenience, as that's the opposite of what these APIs are for.

The current status quo for unmarshalled interop is that if you want to send a more complex object structure, it's on you to pack it into some `struct` or array that you can read from on the JS side.

**Comment by mruch2** [comment]
Hi Steve, the intent of the unmarshalled call certainly does its job. We are using it in our blazor app and have noticed significant performance gains. I am not asking for how it works to be changed just requesting an enhancement to it for additional parameters. 

We are using vlazor with ThreeJS so the amount of data we have to pass into it is quite large, if it is a bit of work to allow infinite parameters, maybe the functionality could be extended to have 6 as this would cover almost all of the need we have for it?

**Comment by SteveSandersonMS** [comment]
> maybe the functionality could be extended to have 6 as this would cover almost all of the need we have for it?

Technically we probably could do. There is genuinely still an element of perf tradeoff since if we're populating, passing, and parsing larger buffers then there is more overhead. Most likely it wouldn't make much of a difference but it is something to think about for an API that is all oriented around perf.

I can't promise this is likely to get to the top of our backlog queue any time soon as we're mainly focused on areas that have more widespread community demand. In the meantime I'd recommend using the techniques we've mentioned (putting your params in a custom struct or array). Hope that seems reasonable!

**Comment by mruch2** [comment]
I will do as you suggested until maybe one day there is the extended
functionality for this method.
