### ISSUE TITLE
setting LowercaseQueryStrings = false not working as expected. 

### ISSUE THREAD

**Issue by rajshukla09** [dotnet/aspnetcore#32533]
services.AddRouting(options =>
            {
                options.LowercaseUrls = true;
                options.LowercaseQueryStrings = false;
            });
Here the entire URL is being set as lowercase, and so is the querystring value.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
