### ISSUE TITLE
AddRazorRuntimeCompilation not work

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#32535]
VS2019 16.9.4
asp.net core 5.0 project

I want `.cshtml` files appear in output and publish directory, and no `views.dll`, so I follow this [doc](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio):
>1. Install the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation NuGet package.
>2. Update the project's Startup.ConfigureServices method to include a call to AddRazorRuntimeCompilation. For example:

But not work, no see any `.cshtml` file, and the damn `views.dll` file still here.

**Comment by pranavkm** [comment]
@ahdung thanks for the feedback. Runtime compilation complements build time complement, it does not substitute it. Consequently you should continue seeing views compiled (.views.dll). The SDK has a few options to disable build time compilation and include cshtml files as part of the published output, perhaps that would help: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-5.0

**Comment by ahdung** [comment]
@pranavkm Thank you. 
I think they should not be a complementary relationship, but a mutually exclusive relationship. If it has been compiled at build time, why do I need runtime compilation? The introduction of runtime compilation components is to not compile at build time, This should be an obvious intention. It is a pity that you behaved a bit logically on this issue.
Please remove your `Answered` tag thanks.

**Comment by pranavkm** [comment]
>  think they should not be a complementary relationship, but a mutually exclusive relationship. 

Thanks for your feedback @ahdung , but we think of runtime compilation as a primarily dev-focused feature. It's primarily meant to improve speed of development locally without the cost of a full rebuild on changes. Making the two features mutually exclusive would defeat this goal.
