### ISSUE TITLE
Invalid nullability annotation on ParameterDescriptor.BindingInfo

### ISSUE THREAD

**Issue by maurei** [dotnet/aspnetcore#32538]
I'm getting a warning about `BindingInfo` never being null, but the error that results from removing the null conditional operator demonstrates otherwise. 

```c#
// Repro parameter
public sealed class DebugController : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> Debug(int test)
    {
        return Ok();
    }
}

// Calling code:
var parameterDescriptor = descriptor.Parameters.FirstOrDefault();
var bindingSource = parameterDescriptor.BindingInfo?.BindingSource;
```

I suspect property `BindingInfo` should be of type `BindingInfo?` instead of `BindingInfo`.

If this indeed is the case I'm opening to contributing a fix.

**Comment by pranavkm** [comment]
Thanks for the issue report @maurei. The API has been corrected as part of .NET 6: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Abstractions/src/Abstractions/ParameterDescriptor.cs#L27.
