### ISSUE TITLE
[Blazor] Guids should be treated as an inmutable type

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#32539]
https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ChangeDetection.cs doesn't account for Guid which will result in unnecessary renders.

**Comment by javiercn** [comment]
The fix here is to update the ChangeDetection logic to include Guids.

/cc: @SteveSandersonMS

**Comment by daniel-p-tech** [comment]
@SteveSandersonMS have you considered taking this a step further and giving developers complete control over the detection mechanism?

I have recently filed two issues that relate to detecting changed parameters in an effort to optimize more complex reusable components. I would like to expand the list of parameter types to reference types - users will understand that if for example an underlying item in a collection is changed, they will have to call custom ``Render`` method which will guarantee to refresh the component.

Ideally, I would like to acquire collection of all old/new parameter values and decide myself if a render is necessary. Implementing such logic would currently require redundant CPU cycles - first by the framework and then by my solution.

Thank you.

https://github.com/dotnet/aspnetcore/issues/32163
https://github.com/dotnet/aspnetcore/issues/32287

**Comment by SteveSandersonMS** [comment]
@daniel-p-tech If you have a specific design in mind please let us know. Some of the tricky things that would have to be solved include:

 * Composability across component libraries. It's not valid for one library to start influencing the treatment of (say) `System.Object` in a way that would affect library that's within the same application.
 * The costs of even locating any customizations. Currently we don't (say) compute a hash of the parameter type to find a dictionary entry while diffing every single parameter.

These kinds of constraints are why we've kept the "shall I render or not" decision to be something that happens inside each component, and each component chooses what (if any) snapshots of preceding data to retain. This gives the component control over whether it wants to compare by reference, by some kind of hash of values being supplied, or any other rule.

**Comment by javiercn** [comment]
We should do Guid because we have a Guid constraint in routing and that makes it akward since it's a value type, besides that, anything else should be on a case by case basis, IMO.
