### ISSUE TITLE
There is no `Retry` button in the page after reconnection to the server for blazor server project

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#32545]
**Repro Steps**
1. Open VS > Create a new project > Blazor Server App > 6.0 > Create
2. F5 to run the application
3. After it pop up a browser to show the page, please open another browser that the website link same as previous one, then stop debugging
4. Wait for about 3 mins, verify the page info

Note: This issue does not repro on 5.0/3.1 project

**Actual Result**
After stop debugging, connect server message show up and then the page show "reload" message. Wait for about 3 mins, the page still show "Reload"
![image](https://user-images.githubusercontent.com/22535374/115699987-d04d1080-a398-11eb-8e57-fa4c769c4fac.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/22535374/115700016-d80cb500-a398-11eb-8b8e-49924177f0e3.png)

**Comment by SteveSandersonMS** [comment]
We're not 100% clear on whether this is a problem specific to debugging or also affects real users when deployed. We also don't know why the behavior changed.

Putting in RC2 to verify that the behavior is intentional.

**Comment by EmilyFeng97** [comment]
@TanayParikh @wtgodbe Verify this issue on the latest 6.0 RC2 build[6.0.100-rc.2.21465.13], and it still repro. Could you please tell me where I can get the new build to verify this issue?

**Comment by TanayParikh** [comment]
> @TanayParikh @wtgodbe Verify this issue on the latest 6.0 RC2 build[6.0.100-rc.2.21465.13], and it still repro. Could you please tell me where I can get the new build to verify this issue?

I believe this will take a few days to propagate as it only merged on Tuesday. Could you try again Monday?

**Comment by EmilyFeng97** [comment]
thank you for your reply. I will continue to track this issue for a while, and once it is fixed, I will verify it.
