### ISSUE TITLE
Razor editor messing up ending brackets when using override in code block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32555]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-editor-messing-up-ending-brackets-/1414079)._

---
[severity:It's more difficult to complete my work]
When I do an override, the completion ‘steals’ the ending bracket and I have to re-enter it
Microsoft Visual Studio Enterprise 2019 main
Version 16.10.0 Preview 3.0 [31303.267.main]

Project: https://github.com/timheuer/blazorauthplayground

I see it in weird places… almost like when it is near end of bracket.  Updated video attached

---
#### Feedback Bot on 5/5/2021, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
@NTaylorMullen If it's OK with you, I'm going to self-assign this one since I can repro it now that you figured out that using tabs is the cause.

**Comment by allisonchou** [comment]
Fixed by https://github.com/dotnet/aspnetcore-tooling/pull/3768.

**Comment by NTaylorMullen** [comment]
Reopening for now to track the work in 17.0-P3
