### ISSUE TITLE
Razor Editor boostrap intelliSense does not works

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32559]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-Editor-boostrap-intelliSense-does-/1416723)._

---
[severity:It bothers me. A fix would be nice]
the bootstrap intellisense inside a .razor file does not works. I have the same issue than [this topic](https://developercommunity2.visualstudio.com/t/Razor-Editor-boostrap-class-intelliSense/1367793?space=61&entry=problem) 

I checked if the intellisense is generally borken. I made a index.html and the intellisense works perfectly. so the issue must be in a .razor or .cshtml file which dont supports the intelliense of bootstrap.

I enabled the experimental razor editor. but this still dont makes the intellisense working.

I'm using the latest preview of visual studio **16.10.0 Preview 2.1** 

regarding.

---
#### Feedback Bot on 5/9/2021, 07:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Hello, when using the new Razor editor do you not see bootstrap like so?
![image](https://user-images.githubusercontent.com/2008729/118562810-44719e80-b722-11eb-800f-f71e53be2c34.png)

**Comment by cydolo** [comment]
I have created a test project (Blazor Server). Intellisense works in an .html file. but it doesn't work in the .razor file. 

**Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 2.1**

![swrrereqqw3221](https://user-images.githubusercontent.com/25271332/118697065-364d7c00-b80f-11eb-85f5-0be487a5053f.gif)

**Comment by cydolo** [comment]
Intellisense worked after updating visual studio. from **Version 16.10.0 Preview 2.1** to **Version 16.10.0 Preview 4.0**

**Comment by NTaylorMullen** [comment]
> Intellisense worked after updating visual studio. from **Version 16.10.0 Preview 2.1** to **Version 16.10.0 Preview 4.0**

Thanks for confirming!
