### ISSUE TITLE
Blazor Server HTML boolean attribute doesn't work normally

### ISSUE THREAD

**Issue by ZiadMadkour** [dotnet/aspnetcore#32551]
Hi All,

let's say I have code that generates:

```html
<details open b-cssIs0lat1on>
  ...
</details>
<details open b-cssIs0lat1on>
  ...
</details>
<details b-cssIs0lat1on>
  ...
</details>
```

```html
<details>
<summary>This is the summary</summary>
These are the details
</details>
```

On adding new elements, I remove the `open` attribute from all but the new one:
it works only when the user doesn't collapse the details block.
when the user collapses and expands a tag, the order of the attributes change, and I think that's the problem:
`<details open b-cssIs0lat1on>` ==> `<details b-cssIs0lat1on open>`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what is the exact issue that you're concerned about here as well whether it's an issue in our framework.
If you believe it is an issue in our framework, please share a more detailed example and also a small repro project which will help us better understand the issue.

Note, that Blazor doesn't guarantee the order of attributes it renders.
