### ISSUE TITLE
NullReferenceException thrown from Microsoft.AspNetCore.TestHost.ClientHandler

### ISSUE THREAD

**Issue by ohadschn** [dotnet/aspnetcore#32561]
### Describe the bug
We've encountered a seemingly rare intermittent `System.NullReferenceException` with the following stack trace:
```at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass11_0.<SendAsync>b__2(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<.ctor>b__15_0()
   at Microsoft.AspNetCore.TestHost.ResponseBodyReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Our..Test.Code
```

Looking at what I think is the relevant code section, I can't say I see any potentially null object, but combined with the rare reproduction rate I'd guess this is a threading bug (some sort of race condition): https://github.com/dotnet/aspnetcore/blob/9445d00a65e5d3ead768a6de114ae8713c12dfd3/src/Hosting/TestHost/src/ClientHandler.cs#L187

### To Reproduce
I can't reproduce it reliably, but when I run the following code in a loop I manage to get it maybe once in every 100-200 iterations (only in release, not in debug):

```cs
//_client is generated from a TestServer (specifically via its CreateHandler)
_client.DefaultRequestHeaders.Add(HeaderNames.Origin, "https://example.com");

using (var preflightRequest = new HttpRequestMessage(HttpMethod.Options, RequestUri))
{
    preflightRequest.Headers.Add(HeaderNames.AccessControlRequestMethod, method.Method);
    var preflightResponse = await _client.SendAsync(preflightRequest).ConfigureAwait(false);
    AssertAllowMethods(preflightResponse.Headers, method);
}

using (var request = new HttpRequestMessage(method, RequestUri))
{
    var response = await _client.SendAsync(request).ConfigureAwait(false);
    AssertAllowOrigin(response.Headers);
}
```

Where the assert methods basically access the headers:
```cs
private static void AssertAllowOrigin(HttpResponseHeaders headers)
{
    Assert.True(headers.Contains(HeaderNames.AccessControlAllowOrigin));
    var headervalues = headers.GetValues(HeaderNames.AccessControlAllowOrigin).ToArray();
    Assert.Single(headervalues);
}

private static void AssertAllowMethods(HttpResponseHeaders headers, HttpMethod method)
{
    Assert.True(headers.Contains(HeaderNames.AccessControlAllowMethods));
    var headerValues = headers.GetValues(HeaderNames.AccessControlAllowMethods).ToArray();
    Assert.Single(headerValues);
}
```

### Exceptions (if any)
`System.NullReferenceException : Object reference not set to an instance of an object`

### Further technical details
- ASP.NET Core version 5.0.5

``` dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.523 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Visual Studio 2019 16.9.4 (Windows), but I saw this reproduced in our linux build server as well

**Comment by Tratcher** [comment]
That callback implies an issue with the anonymous callback method passed in here:
https://github.com/dotnet/aspnetcore/blob/b124d508b898f7c9e52897600c6fea9a6037ebf4/src/Hosting/TestHost/src/HttpContextBuilder.cs#L50
I agree though, it should be able to handle any nulls in that statement.

**Comment by ohadschn** [comment]
@Tratcher yes, and according to ILSpy the only place that callback is passed is here: https://github.com/dotnet/aspnetcore/blob/9445d00a65e5d3ead768a6de114ae8713c12dfd3/src/Hosting/TestHost/src/ClientHandler.cs#L185

The callback code looks like this:
```cs
var responseTrailersFeature = context.Features.Get<IHttpResponseTrailersFeature>()!;
foreach (var trailer in responseTrailersFeature.Trailers)
{
	bool success = response.TrailingHeaders.TryAddWithoutValidation(trailer.Key, (IEnumerable<string>)trailer.Value);
	Contract.Assert(success, "Bad trailer");
}
```
At first I thought `context.Features.Get<IHttpResponseTrailersFeature>()` might be null, but that doesn't make sense, as it's always set here: https://github.com/dotnet/aspnetcore/blob/b124d508b898f7c9e52897600c6fea9a6037ebf4/src/Hosting/TestHost/src/HttpContextBuilder.cs#L59

`trailer` is a struct (`KeyValuePair`) and `Trailers` is set in a private member that's never touched as far as I can tell: https://github.com/dotnet/aspnetcore/blob/b124d508b898f7c9e52897600c6fea9a6037ebf4/src/Hosting/TestHost/src/HttpContextBuilder.cs#L25

So I don't see any other possible null reference there, which brings me back to the multi-threading / race condition theory. Initially I suspected my access to the headers in the test code was the cause, but as far as I can tell `Headers` and `TrailingHeaders` are completely separate.

BTW, I'm a Microsoft employee, can send failing Azure DevOps build and exact code (my alias is _ohads_).

**Comment by JamesNK** [comment]
I'm having trouble seeing a race condition. All of these are set before SendAsync is called:
* Setting delegate into RegisterResponseReadCompleteCallback
* Creating and setting `_httpContext` (a null ref could also be caused by this being null)
* Creating and setting ResponseTrailersFeature
* Creating and setting ResponseTrailersFeature.Trailers collection

None of these are changed during the call in our app code. The only things that could be changed would have to be done by the app. Either the app being tested removing the feature from the feature collection or setting the `Trailers` collection to null.

Also, the error can't be coming from your assert methods. It must be SendAsync. That's shown in the stack trace.

[I have a PR](https://github.com/dotnet/aspnetcore/pull/32633) to check for the trailers feature being messed with in the app, but I don't know if that is the problem or not.

**Comment by ohadschn** [comment]
I was having trouble too, but that's still my best theory :)

Our code doesn't touch [IHttpResponseTrailersFeature](https://dev.azure.com/msazure/ADP/_search?text=IHttpResponseTrailersFeature*&type=code&lp=code-Project&filters=ProjectFilters%7BADP%7DRepositoryFilters%7BADP%7D&pageSize=25), in fact we don't touch [features](https://dev.azure.com/msazure/ADP/_search?action=contents&text=Features*&type=code&lp=code-Project&filters=ProjectFilters%7BADP%7DRepositoryFilters%7BADP%7D&pageSize=25&result=DefaultCollection%2FADP%2FADP%2FGBmaster%2F%2FDirectory.Build.props) at all. Nothing about [Trailers](https://dev.azure.com/msazure/ADP/_search?action=contents&text=Trailers*&type=code&lp=code-Project&filters=ProjectFilters%7BADP%7DRepositoryFilters%7BADP%7D&pageSize=25&result=DefaultCollection%2FADP%2FADP%2FGBmaster%2F%2FDirectory.Build.props) either...

By the error coming from our test code / assert methods I meant our test code somehow triggering the race condition in the stack trace. I was thinking along the lines of concurrent access to a `HttpHeaders` collection (which is [not thread safe](https://github.com/dotnet/runtime/blob/db3784c30ce2ff3a71b0d5b83ddda59a2a9bfd63/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L41)), but as mentioned we only touch `Headers` (and [never touch TrailingHeaders](https://dev.azure.com/msazure/ADP/_search?action=contents&text=TrailingHeaders*&type=code&lp=code-Project&filters=ProjectFilters%7BADP%7DRepositoryFilters%7BADP%7D&pageSize=25&result=DefaultCollection%2FADP%2FADP%2FGBmaster%2F%2FDirectory.Build.props)) which appears completely separate from `TrailingHeaders`...

**Comment by JamesNK** [comment]
The way you are using `HttpClient` means that the request will be complete before exiting `HttpClient.SendAsync`. The entire response will be downloaded and the logic to access trailers will have run.

**Comment by ohadschn** [comment]
Then I suppose that leaves the case of our app code doing something asynchronously while we're calling `SendAsync`, because it seems like it has to be some sort of a race condition, considering nothing should be null there and especially considering the fact it only happens once per 100-200 runs.

Looking at our code though I can't say that I see something like this, but I'll send you more details offline.

**Comment by JamesNK** [comment]
We have investigated our code and taken a look at your app. We don't know why this is happening.

You said that you only see this problem in certain build configurations of your app (which has no impact on our bits which are always RELEASE). That might indicate that it is a problem in your app or tests, rather than in TestServer itself. However, we didn't see anything in your code that might cause this problem.

At this point, we'd need you to provide an isolated repro to investigate. E.g. copying the relevant test to an independent project you can share and removing as much code as possible while still hitting the repro.

**Comment by ohadschn** [comment]
Thank you, I'll try to repro and report back

**Comment by dmitrykarnitski** [comment]
Hi,
We have faced the same issue as described here. Our tests are failing randomly on a build machine and locally, however, our usage of a TestServer is quite simple - adding an Authorization header, setting string content as a body, and sending a Post request.
The only issue "bad thing" we do is that we use ".GetAwaiter().GetResult()" while awaiting a response.

Could you please take a look at this a bit deeper? Because my investigation results are the same as @ohadschn did...

**Comment by Tratcher** [comment]
@dmitrykarnitski can you share a minimal test that reproduces this? We haven't been able to reproduce the issue and can't investigate further with that.
