### ISSUE TITLE
Add IResult implementations for more IActionResults

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#32565]
Currently, only [JsonResult](https://github.com/dotnet/aspnetcore/blob/0551cef40f5f169e6d610ba71b0c26c51b2502ad/src/Mvc/Mvc.Core/src/JsonResult.cs) and [StatusCodeResult](https://github.com/dotnet/aspnetcore/blob/0551cef40f5f169e6d610ba71b0c26c51b2502ad/src/Mvc/Mvc.Core/src/StatusCodeResult.cs) implement both an [IActionResult](https://github.com/dotnet/aspnetcore/blob/63ece745cfbf6967743abb1e173aeb2eb7144453/src/Mvc/Mvc.Abstractions/src/IActionResult.cs) and [IResult](https://github.com/dotnet/aspnetcore/blob/0551cef40f5f169e6d610ba71b0c26c51b2502ad/src/Http/Http.Abstractions/src/IResult.cs). This means there are a bunch of remaining built-in `IActionResult`s implementations that have no IResult equivalent.

- [x] ContentResult
- [x] VirtualFileResult
- [x] PhysicalFileResult
- [x] FileStreamResult
- [x] FileContentResult
- [ ] RedirectResult
- [ ] LocalRedirectResult
- [x] ChallengeResult
- [x] ForbidResult
- [x] SignIn/OutResult
- [ ] RedirectToAction/PageResult?
- [ ] ObjectResult?

`ObjectResult` is the big  `IActionResult` that probably doesn't have an easy `IResult` implementation. I feel this requires some support for content-negotiation, but maybe we can just assume JSON.

**Comment by davidfowl** [comment]
@pranavkm should we bother with ActionResult\<T\>?

**Comment by davidfowl** [comment]
We'll strike out the action results that don't make sense once we investigate their feasibility

**Comment by halter73** [comment]
For anyone looking at this because of the `help-wanted` label, feel free to take a subset of these types. I have a feeling something like RedirectResult will be easier to chew off than ObjectResult.

**Comment by barahonajm** [comment]
Sounds interesting, I will take the easiest ones 😄

**Comment by deepumi** [comment]
I would like to try ContentResult or something simple.

**Comment by barahonajm** [comment]
@halter73 @davidfowl I would like to confirm the approach I am taking is how you were envisioning the implementation of these new `IActionResults`, could you take a look at #32647?

If the approach its fine I will continue with the rest but there is a question, similar to MVC we will need to register singleton of each ActionResult like this

https://github.com/dotnet/aspnetcore/blob/d8906c8523f071371ce95d4e2d2fdfa89858047e/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L245-L259

Where do you think is the best place to add these new addings in this particular case?

**Comment by wcontayon** [comment]
@halter73 @davidfowl  can I try the `IResult` implementation for `ObjectResult` ?

**Comment by davidfowl** [comment]
That's the hard one. Maybe the file results?

**Comment by wcontayon** [comment]
> That's the hard one. Maybe the file results?

Why not 🙂. I'll submit PR on that.
Thanks @davidfowl

**Comment by davidfowl** [comment]
@pranavkm suggested that we should support `ObjectResult` by doing JSON and if another content type is specified then fail.

**Comment by ilkayilknur** [comment]
I'm implementing the `IResult` on the `RedirectToActionResult`. I think it's best to wait for https://github.com/dotnet/aspnetcore/pull/33843 to be merged to avoid conflicts, right?

**Comment by halter73** [comment]
I think that's a good idea @ilkayilknur

**Comment by pranavkm** [comment]
@ilkayilknur I think the plan is to not add any more `IResult` to MVC's action result types.

**Comment by ilkayilknur** [comment]
Thanks for the update @pranavkm

**Comment by halter73** [comment]
The remaining work was addressed by #33843
