### ISSUE TITLE
x-www-form-urlencoded not binding on an ApiController

### ISSUE THREAD

**Issue by MarkMcDonald** [dotnet/aspnetcore#32579]
`        [HttpGet]
        [HttpPost]
        public async Task<dynamic> Get(string postcode,
            string displayPo = "0")`

Porting an API and have a method signature as above. The idea is it needs to handle both GET and POST requests.

GET requests with data on the query string work.
POST requests with data on the query string work.
POST requests with data sent as x-www-form-urlencoded leave the parameters empty.

Looking through the documentation it suggests without using model binding attributes it should look at all sources as per:
[https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#manual-model-binding]

1. Form fields
2. The request body (For controllers that have the [ApiController] attribute.)
3. Route data
4. Query string parameters
5. Uploaded files

Tried to update to use a complex type in case that helped as below:

```C#
        public class InputParams
        {
            public string Postcode { get; set; }
            public string DisplayPO { get; set; } = "0";
        }

        [HttpGet]
        [HttpPost]
        public async Task<dynamic> Get(InputParams inputParams)
        {
            var postcode = inputParams.Postcode;
            var displayPo = inputParams.DisplayPO;
```

When trying that I get the following error:

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-d731e412904dcb468b4c65247871e02e-43110d65dadd414a-00"
}
```

Pretty sure in .NET Framework this sort of thing just worked, and from early documentation on .NET Core sounds like it used to work in early versions of Core too.

But targeting .NET 5 it seems problematic. Is this a bug or am I missing something?

**Comment by pranavkm** [comment]
In an API controller, complex types are inferred to be `FromBody` parameters:

* https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#frombody-inference-notes
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.frombodyattribute?view=aspnetcore-5.0

This indicates that the parameter is deserialized (think JSON or XML) rather than model bound. 

* For an APIController, if you want a complex type to be model bound, you can [annotate it with the `ModelBinder` attribute](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#modelbinder-attribute):
* If your action is actually working with browser posted forms and views, I'd recommend not using an `ApiController`. The behavior produced by `ApiController` is meant for a REST-ful client, and might not be best suited for a browser-based client.

**Comment by MarkMcDonald** [comment]
It's a port of an existing API onto a new tech stack, and is mainly accessed through a variety or browser based and ajax requests, or server side HttpClient calls - so in this particular case the key consideration was to preserve existing behaviour.

The solution I eventually went for is to use the ConfigureApiBehaviorOptions - this looks to allow the original signature to work in all scenarios without having to jump through any additional hoops or worrying about specifying individual consume behaviours or inference between simple and complex types. So seems to be exactly what I need in this case. Thanks for your help.

`            services.AddControllers().ConfigureApiBehaviorOptions(options =>
                {
                    options.SuppressConsumesConstraintForFormFileParameters = true;
                    options.SuppressInferBindingSourcesForParameters = true;
                });`

**Comment by MarkMcDonald** [comment]
Out of curiosity, can this be supressed on a per controller or per method basis? The fact this is suppressed global to be able support legacy behaviours when porting APIs could cause future security issues - particularly if having to combine old APIs into other projects.

In my case I think when we come to iterate and version on the ported API will create a new project, as this new way of doing things potentially makes things tricky to have a predictable and granular way of controlling behaviours.

**Comment by pranavkm** [comment]
Is there a reason you're choosing to annotate your app with `ApiController`? Using a controller without this attribute should give you behavior most compatible with an MVC 5 application and you wouldn't have to change global settings.

**Comment by MarkMcDonald** [comment]
The main reason I suppose is because it's an API I'm porting. Admittedly it's an old API that's been online for over 10 years and is being converted to a new tech stack, it has a CORS policy (admittedly allow all origins), and it takes in input parameters returning JSON. 

Maybe it's just a naming thing but when I thought of porting an API to .NET 5 and looked for information - as after 20 years as a developer most of my experience is on .NET Framework (and still likely will be for the next 10 years) - ApiController is what came up.

**Comment by davidfowl** [comment]
But its clear that the semantics you want aren't in the new ApiController so the question remains, why not use the normal controller that was suggested earlier?

**Comment by MarkMcDonald** [comment]
Mainly because it's working now, and that the most important thing. 

I'm sure I'll look into it more in the future, and look to see if I can find adequate documentation as to the whys and wherefores of the various approaches. But at the minute there isn't a compelling reason to use .NET 5 in most web projects so this was a first dip in the water.

**Comment by davidfowl** [comment]
Great
