### ISSUE TITLE
user-secrets does not function on ubuntu 18.04

### ISSUE THREAD

**Issue by m1stermanager** [dotnet/aspnetcore#32576]
### Describe the bug
dotnet user-secrets either sets no values, or creates C:\ directory in project when running on wsl2 ubuntu 18.04

### To Reproduce

https://github.com/m1stermanager/user-secrets-issue

### Exceptions (if any)

None, except a build error when the errant directory exists

`/usr/share/dotnet/sdk/5.0.202/Microsoft.Common.CurrentVersion.targets(3136,5): error MSB3552: Resource file "**/*.resx" cannot be found. [/home/<my linux username>/<my repo path>/user-secrets-issue.csproj]`

### Further technical details
- ASP.NET Core version Microsoft.AspNetCore.App 5.0.5
- Include the output of `dotnet --info`
▶ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.408 [/usr/share/dotnet/sdk]
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
vscode 1.55.2, though issue seems tied to WSL

**Comment by adityamandaleeka** [comment]
Assigning to myself to investigate.

**Comment by adityamandaleeka** [comment]
@m1stermanager Any luck with the repro?

**Comment by m1stermanager** [comment]
so sorry! let me try this right now actually

**Comment by m1stermanager** [comment]
@adityamandaleeka I was unable to reproduce this issue. as far as I am concerned this can be closed. I must've had some wires crossed in my original wsl2 setup.
