### ISSUE TITLE
How is status code set between controller and middleware?

### ISSUE THREAD

**Issue by normj** [dotnet/aspnetcore#32596]
I'm maintain the [Amazon.Lambda.AspNetCoreServer](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer) package which allows developers to run ASP.NET Core applications as a Lambda (Serverless) Function in AWS. In this environment Kestrel is not used nor is any real web server. I implement my own version of `Microsoft.AspNetCore.Hosting.Server.IServer` and take care of converting the Lambda event sources into ASP.NET Core requests and convert responses from ASP.NET Core back into how the Lambda expected response formatted.

We have users that have noticed a slight discrepancy between running in Kestrel versus in Lambda and I'm having trouble understanding why this is happening and wondered if somebody could give me a clue that could help me.

### The scenario ###

Basically if you have a simple controller like this classic example where the http status code is not set on the response.
```csharp
[HttpGet]
public IEnumerable<string> Get()
{
    return new string[] { "value1", "value2" };
}
```
I assume somewhere up the ASP.NET Core HTTP request pipeline the status code is given a default value whether there was an exception or not. That default status code comes across correctly through my library as well as Kestrel so a 200 status code is returned.

### Where it goes wrong ###

If there is a middleware added to the request pipeline like this:

```csharp

// Snippet from Startup.cs
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{

    app.UseMiddleware<RequestLoggingMiddleware>();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
    });
}

// Snippet from middleware
public async Task Invoke(HttpContext context)
{
    _logger.LogInformation(
            "START: Request {method} {url} => {statusCode}",
            context.Request?.Method,
            context.Request?.Path.Value,
            context.Response?.StatusCode);
    try
    {
        await _next(context);
    }
    finally
    {
        _logger.LogInformation(
            "END: Request {method} {url} => {statusCode}",
            context.Request?.Method,
            context.Request?.Path.Value,
            context.Response?.StatusCode);
    }
}
```
In the normal usage of Kestrel I can see in the status code set to 200 in the finally block of the middleware even through the controller didn't explicit set it. In my case where Kestrel is not used status code in the finally blocked is 0. Again somewhere else the pipeline in ASP.NET Core the status code is set.

So my question is could somebody explain to me how in the Kestrel scenario the status code is set by the time the `next` method returns in the middleware even though the controller didn't actually set the status code? I'm wondering if there was something in my implementation of the `Microsoft.AspNetCore.Http.Features.IFeatureCollection` class that I should have implemented to trigger the status code resolution?

**Comment by Tratcher** [comment]
context.Response?.StatusCode is set to the 200 default by the server before even calling into the middleware pipeline. You have two logs in your middleware, you should see that StatusCode starts as 200 when you're first called. Middleware or the app can override the value at any time before sending the response.
Here's one example:
https://github.com/dotnet/aspnetcore/blob/5f720bd10acd5a51e59819b59097cfd4b9e1323c/src/Http/Http/src/Features/HttpResponseFeature.cs#L18-L21

**Comment by normj** [comment]
Thanks @Tratcher. I can see were to put that same logic in my implementation. I had gotten myself confused and thought if I threw an exception from the controller the middleware would see a 500. I see now that is not true and it still gets a 200 in the middleware.

**Comment by Tratcher** [comment]
Indeed. Any exceptions in the pipeline are converted to 500s by middleware or the server if it reaches that far.
