### ISSUE TITLE
After replacing the response body content in the middleware, the full replacement body content cannot be obtained

### ISSUE THREAD

**Issue by ygr757326** [dotnet/aspnetcore#32611]
### Describe the bug
我在中间件中替换响应体内容后，无法得到完整的替换后的响应体内容

_Translated: After replacing the response body content in the middleware, the full replacement body content cannot be obtained._ 

### Exceptions (if any)

```C#
  Stream originalResponse = context.Response.Body;

                    using (var newResponse = _streamManager.GetStream())
                    {
                        context.Response.Body = newResponse;

                        await _next.Invoke(context);

            newResponse.Seek(0, SeekOrigin.Begin);
// str=123
            string str = await new StreamReader(newResponse).ReadToEndAsync();
     
            var writer = new StreamWriter(originalResponse);
            await writer.WriteAsync("abcdefg");
            await writer.FlushAsync();
//abc
          context.Response.Body = originalResponse;
                     
                    }
```                

### Further technical details
- ASP.NET Core version ： net5.0
- The IDE (VS / VS Code/ VS4Mac)：VS2019 16.9.5

**Comment by ygr757326** [comment]
@Tratcher 确实，我设置了响应的    Content-Length 后，就可以完全输出了：context.Response.ContentLength ="abcdefg".Length ;但是在未设置 Content-Length之前，同样的代码在 netcore3.0 中是可以正常运行的，难道net5.0需要同时修改 Content-Length ？

**Comment by Tratcher** [comment]
In your 3.0 example, did the Content-Length have a value before you set it? If the Content-Length is null then the server will use `Transefer-Encoding: chunked` instead. It's only a problem if you have a Content-Length that does not match your body.

**Comment by ygr757326** [comment]
@Tratcher Oh, I see, thank you
