### ISSUE TITLE
[WebToolsE2E] After creating ASP.NET Core 5.0 MVC web app with identity platform auth, the versions of the Microsoft.Identity.Web and Microsoft.Identity.Web.UI packages in the template are old

### ISSUE THREAD

**Issue by balachir** [dotnet/aspnetcore#32617]
### To Reproduce

**INSTALL STEPS**

Clean machine: Win10 x64 ENU
Install 16.10 Preview 3
Install VS Enterprise
- Select Web workload, default options (includes .NET 5 SDK + 5.0 / 3.1 runtimes) + 2.1 runtime

**REPRO STEPS**
New ASP.NET Core 5.0 > Web Application (MVC) > Microsoft identity platform auth
Build solution
Open Manage NuGet Packages dialog

**ACTUAL**
Versions of the Microsoft.Identity.Web and Microsoft.Identity.Web.UI packages in the template are old. The version in the templates is 1.1.0 but the latest version available from nuget.org is 1.9.2.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/8246794/118009941-27c51780-b36c-11eb-9f09-bc580ae99f38.png">

**EXPECTED**
Templates should install the latest versions of the Microsoft.Identity.Web and Microsoft.Identity.Web.UI packages

**Comment by blowdart** [comment]
We don't update template dependencies immediately unless there are security issues, because those dependencies may have functional changes we can't anticipate.

Is this actually causing you problems, or is it just they're not latest?

**Comment by balachir** [comment]
We're not aware of any functional issues at this point. I'm just calling out that they're not latest. The current 1.1.0 versions are about 7 months old now, so I was wondering if that might be getting a little out-dated.

**Comment by mkArtakMSFT** [comment]
Thanks @balachir.
We'll stick to our process here to update the dependencies only when we need to.
