### ISSUE TITLE
Few questions about .NET 6 hot reload

### ISSUE THREAD

**Issue by ionoy** [dotnet/aspnetcore#32616]
Not sure if this is the right place to ask, but I have a few questions about the upcoming hot reload functionality.

I'm the author of LiveSharp, which provides hot reload for .NET projects. It seems that with .NET 6, there will be much fewer cases where people would choose LiveSharp over the built-in stuff. Still, with LiveSharp there is a lot of infrastructure that allows a high degree of configurability that might be useful for some projects. Plus, there will be existing customers that I don't want to abandon. 

I would like to integrate .NET 6 hot reload into LiveSharp to use with the newer projects that allow it. Is it even possible with the current API? 

Can I create an assembly diff from the LiveSharp server side? 

LiveSharp Server is a .NET Core application running on the developer's machine. I already do my own assembly diffing and only send changes. But I'm not sure how to prepare specific diff buffers required by the Assembly update API.

What triggers .NET 6 hot reload? Is it a filesystem event or something integrated into the IDE?

**Comment by danroth27** [comment]
Hi @ionoy. .NET Hot Reload is still a work in progress with many parts still moving around, so we're not quite ready to engage on this yet. We'll get back to you once things have settled down into a more stable form.
