### ISSUE TITLE
Non-generic interface on WebApplicationFactory

### ISSUE THREAD

**Issue by arnevandenberghe** [dotnet/aspnetcore#32612]
### Is your feature request related to a problem? Please describe.
I am trying to set up an integration test using `WebApplicationFactory<T>`, involving multiple apps. I would like to be able to store the factories in a generic collection. I can't however, since the factories do not have the same generic Type parameter.

### Describe the solution you'd like
A non-generic interface `IWebApplicationFactory` could provide the important public properties and methods you would need to interact with it during the actual test. e.g. `Server`, `Services`, `CreateClient()`, ...

I have a workaround by creating a wrapper class around the factory that does provide a non-generic interface. It works perfectly, it just seems like the interface could have been baked in.

### Additional context
My integration test is focused on two (or more) applications communicating over a bus. I need to coordinate the bus's test harness with the apps' testserver. Starting needs to be performed in a certain order for it to work. Storing the factories in a collection helps with that.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do given that we haven't received enough evidence that this impacts major number of customers. We will reevaluate this ask if we hear similar feedback in the future.
