### ISSUE TITLE
azurewebsites.net fails to find a view

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32619]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/azurewebsitesnet-fails-to-find-a-view/1374420)._

---
[severity:It's more difficult to complete my work]
I have deployed my ASP .NET project in an azure app service. The problem arise when I try to access to a part of the deployed  application and the server return a HTTP 404. However, it has no sense because if I run the local application there is no problem with the route and the deployed aplication and local application is equal.

¿Can anyone helps me?

! [image.png] (https://aka.ms/dc/image?name=Bc7d00e7487a24fbdb05435d46721e836637516527840552129_20210318-092624-image.png&tid=c7d00e7487a24fbdb05435d46721e836637516527840552129)

! [image.png] (https://aka.ms/dc/image?name=B319f43dcdb6d43b3a13e25fbb94aab70637516528027270295_20210318-092643-image.png&tid=319f43dcdb6d43b3a13e25fbb94aab70637516528027270295)

! [image.png] (https://aka.ms/dc/image?name=Bfe9f0f8748e641629d52fae3f6b1d03f637516528195213892_20210318-092700-image.png&tid=fe9f0f8748e641629d52fae3f6b1d03f637516528195213892)

! [image.png] (https://aka.ms/dc/image?name=B99b692fc0c974d3bb12c5d02862c6d66637516528486088813_20210318-092729-image.png&tid=99b692fc0c974d3bb12c5d02862c6d66637516528486088813)

---
#### Feedback Bot on 3/18/2021, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/18/2021, 10:47 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
