### ISSUE TITLE
Javascript Isolation and CSS Isolation not loading when using a razor class library

### ISSUE THREAD

**Issue by chrisevich** [dotnet/aspnetcore#32622]
### Describe the bug
I converted a working horizontal slider menu to a razor class library component. The component renders but no CSS is being loaded. The javascript should load on demand only when a left or right button is pressed, I'm getting a 404 not found error when a button is pressed. Checked all spelling, CSS is Component1.razor.css under Component1.razor. JavaScript1.js is under wwwroot folder in SliderComponent. This is a Blazor WebAssembly app. Thanks!

### To Reproduce
1. Create a new project, select Razor Class Library
2. Under wwwroot folder add file called Javascript1.js and paste the following code:

```
    export function getSliderWidth(element) {
        return element.clientWidth;
    }

    export function getScrollWidth(element) {
        return element.scrollWidth;
    }

```
3. Open Component1.razor and replace the code with the following:

```
@inject IJSRuntime JS
@using Microsoft.JSInterop;

@page "/"
<div @ref="sliderElement" class="slider">
    <ul @ref="scrollElement" style="transform:translate(@(x.ToString()+"px")); transition-timing-function: ease-out; transition:2s">
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
        <li>10</li>
        <li>11</li>
        <li>12</li>
        <li>13</li>
        <li>14</li>
        <li>15</li>
        <li>16</li>
        <li>17</li>
        <li>18</li>
        <li>19</li>
        <li>20</li>
    </ul>
</div>

<button @onclick="scrollRight">right</button>
<button @onclick="scrollLeft">left</button>

@code {

    [Parameter] public int Duration { get; set; } = 3000;
    ElementReference sliderElement;
    ElementReference scrollElement;
    double x;
    int sliderWidth;
    int scrollWidth;
    ExampleJsInterop module;


    private async Task scrollLeft()
    {
        sliderWidth = await module.GetSliderWidth(sliderElement);
        x += Math.Clamp(Math.Abs(x), 0, sliderWidth);
    }

    private async Task scrollRight()
    {
        scrollWidth = await module.GetScrollWidth(scrollElement);
        sliderWidth = await module.GetSliderWidth(sliderElement);

        x -= Math.Clamp(scrollWidth - (Math.Abs(x) + sliderWidth), 0, sliderWidth);
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            module = new ExampleJsInterop(JS);
        }
    }
}
```
4. Add the following code to ExampleInterop.cs:
      
  ```
public async ValueTask<int> GetScrollWidth(ElementReference element)
        {
            var module = await moduleTask.Value;
            return await module.InvokeAsync<int>("getScrollWidth", element);
        }

        public async ValueTask<int> GetSliderWidth(ElementReference element)
        {
            var module = await moduleTask.Value;
            return await module.InvokeAsync<int>("getSliderWidth", element);
        }
```

5. Add the following css to Component1.razor.css:

```
.slider {
    color: white;
    background-color: blue;
    overflow-x: hidden;
}

    .slider ul {
        display: flex;
        overflow-x: visible;
        user-select: none;
        padding: 0;
    }

        .slider ul li {
            background: skyblue;
            min-height: 250px;
            min-width: 400px;
        }
```

6. Create a new solution/project Blazor Web Assembly project called trash23
7. Add a reference to SliderComponent.Component1

8. Add the following code to Index.razor

`<SliderComponent.Component1></SliderComponent.Component1>`

9. Build and run

No CSS is being loaded for component
Clicking on either scrollRight or scrollLeft button should cause javascript to be fetched, but instead get a 404 not found error

REPOS:
https://github.com/chrisevich/Slider

https://github.com/chrisevich/SliderComponent

### Exceptions (if any)
404 error for javascript, no errors for CSS

### Further technical details

Microsoft Visual Studio Community 2019
Version 16.9.5

.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.617 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.114 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@chrisevich thanks for contacting us.

Your example code seems to be incomplete, please provide a sample that clearly illustrates the issue as well as detailed instructions on how to repro and where are the things you have added or modified from a blank template project.

**Comment by mkArtakMSFT** [comment]
Thanks for the detailed report, @chrisevich.
This is working correctly in our default project template which makes us believe that this is an issue in your app. We're not funded to handle such investigations and we recommend customers to post similar questions to [StackOverflow](https://stackoverflow.com) forum to get help from the community on finding issues in their apps.
