### ISSUE TITLE
Readme links to Extensions libraries go nowhere

### ISSUE THREAD

**Issue by allyn-psyonix** [dotnet/aspnetcore#32625]
### Describe the bug
On the main project readme page, as well as on the "How to contribute" readme, the links to `Extensions` projects go to an empty project that just links back to this project. Those links need to be updated to point to the correct location.

### To Reproduce
Affected readmes that I identified:
- https://github.com/dotnet/aspnetcore
- https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md

In either readme, click the `Extensions` link and note that the project direct to is empty and just links back to this project and the runtime project (which does not appear to have the extensions).

**Comment by dougbu** [comment]
@allyn-psyonix thank you for reporting this issue. We agree it is a bug but this cleanup after moving the extensions projects to dotnet/runtime and dotnet/aspnetcore is not urgent. I am therefore placing it in our backlog.

That said, this is a good first issue. We would appreciate a pull request from you or any member of the community.

**Comment by BohdanBuhrii** [comment]
@dougbu so, if I understand you correctly, the fix will be to replace all the links to the `dotnet/extentions` repo with links to the `dotnet/runtime` and `dotnet/aspnetcore`. Could I grab this issue?

**Comment by dougbu** [comment]
> the fix will be to replace all the links to the dotnet/extentions repo with link to the dotnet/runtime.

Yes, that's it.

> Could I grab this issue?

Absolutely❕

**Comment by garfbradaz** [comment]
Has https://github.com/dotnet/aspnetcore/pull/33322 fixed this issue?

**Comment by dougbu** [comment]
Yes❕ 7da26508e02c21f3ccf79e1e9503c5548aaae87f did the trick
