### ISSUE TITLE
Test ANCM shadow copying with NtfsDisableLastAccessUpdate 

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#32629]
The Windows Server performance tuning guide recommends enabling the `NtfsDisableLastAccessUpdate` flag to reduce disk I/O load and latencies. It also notes that this flag is enabled for most Windows Server OS SKUs enable this by default.

https://docs.microsoft.com/windows-server/administration/performance-tuning/role/web-server/#ntfs-file-system-settings

**Comment by BrennanConroy** [comment]
We don't think last access affects shadow copy, we should be using last modified.
