### ISSUE TITLE
Appdomain unload stuck on System.Web.Hosting.PipelineRuntime.WaitForRequestsToDrain

### ISSUE THREAD

**Issue by pipi1007** [dotnet/aspnetcore#32626]
### Describe the bug
We are seeing sometimes our application has two appdomains, one is in existing state, for a long time if not forever... From dump, domain unload got stuck on System.Web.Hosting.PipelineRuntime.WaitForRequestsToDrain, stack is:

00 000000bd`1fe7ee88 00007ffd`fa9f9c21     ntdll!ZwDelayExecution+0x14
01 000000bd`1fe7ee90 00007ffd`f38454e3     KERNELBASE!SleepEx+0xa1
02 000000bd`1fe7ef30 00007ffd`f38916d9     clr!EESleepEx+0x33
03 000000bd`1fe7ef60 00007ffd`f38917ed     clr!Thread::UserSleep+0xa5
04 000000bd`1fe7efc0 00007ffd`e4a37507     clr!ThreadNative::Sleep+0xad
05 000000bd`1fe7f120 00007ffd`e476a4ab     System_Web_ni!System.Web.Hosting.PipelineRuntime.WaitForRequestsToDrain()+0x37
06 000000bd`1fe7f150 00007ffd`e476b11b     System_Web_ni!System.Web.HttpRuntime.Dispose()+0xcb
07 000000bd`1fe7f1b0 00007ffd`e476b0dc     System_Web_ni!System.Web.HttpRuntime.RecoverFromUnexceptedAppDomainUnload()+0xbb
08 000000bd`1fe7f1f0 00007ffd`e47876ef     System_Web_ni!System.Web.HttpRuntime.RecoverFromUnexceptedAppDomainUnload()+0x7c
09 000000bd`1fe7f230 00007ffd`f3846913     System_Web_ni!System.Web.Hosting.HostingEnvironment.OnAppDomainUnload(System.Object, System.EventArgs)+0x3f
0a 000000bd`1fe7f280 00007ffd`f3846824     clr!CallDescrWorkerInternal+0x83
0b 000000bd`1fe7f2c0 00007ffd`f386a5d3     clr!CallDescrWorkerWithHandler+0x4e
0c 000000bd`1fe7f300 00007ffd`f3a37332     clr!DispatchCallSimple+0x67
0d 000000bd`1fe7f3a0 00007ffd`f3a3728c     clr!InvokeNotifyInner+0x5d
0e 000000bd`1fe7f430 00007ffd`f3a371fe     clr!InvokeNotify+0x62
0f 000000bd`1fe7f4d0 00007ffd`f3c5db33     clr!DistributeEventReliably+0x174
10 000000bd`1fe7f5d0 00007ffd`f3936065     clr!AppDomain::RaiseUnloadDomainEvent+0xf156f
11 000000bd`1fe7f6c0 00007ffd`f3b6c62d     clr!Thread::DoADCallBack+0x211
12 000000bd`1fe7f870 00007ffd`f3b6c533     clr!AppDomain::RaiseUnloadDomainEvent+0x66
13 000000bd`1fe7f960 00007ffd`f3b626c7     clr!AppDomain::ProcessUnloadDomainEventOnFinalizeThread+0x43
14 000000bd`1fe7f990 00007ffd`f38a5e20     clr!Thread::DoExtraWorkForFinalizer+0x1e8
15 000000bd`1fe7fa00 00007ffd`f3847cd0     clr!FinalizerThread::FinalizerThreadWorker+0x90
16 000000bd`1fe7fa50 00007ffd`f3847c43     clr!ManagedThreadBase_DispatchInner+0x40
17 000000bd`1fe7fa90 00007ffd`f3847b82     clr!ManagedThreadBase_DispatchMiddle+0x6c
18 000000bd`1fe7fb90 00007ffd`f39455a6     clr!ManagedThreadBase_DispatchOuter+0x4c
19 (Inline Function) --------`--------     clr!ManagedThreadBase_NoADTransition+0x3b
1a (Inline Function) --------`--------     clr!ManagedThreadBase::FinalizerBase+0x3b
1b 000000bd`1fe7fc00 00007ffd`f384b5b5     clr!FinalizerThread::FinalizerThreadStart+0x116
1c 000000bd`1fe7fca0 00007ffd`fc187974     clr!Thread::intermediateThreadProc+0x8b
1d 000000bd`1fe7fd60 00007ffd`fe6ea2f1     kernel32!BaseThreadInitThunk+0x14
1e 000000bd`1fe7fd90 00000000`00000000     ntdll!RtlUserThreadStart+0x21

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by davidfowl** [comment]
This looks like a .NET Framework issue. This repository is for .NET Core only. 

@richlander do you know where the @pipi1007 can file this issue?

**Comment by pipi1007** [comment]
Thanks @davidfowl , we did more investigation and found it might because there is a SignalR request hanging. Can someone from SignalR team take a look and confirm?

**Existing domain**

Domain 3:           000001e7fc827520
LowFrequencyHeap:   000001e7fc827d18
HighFrequencyHeap:  000001e7fc827da8
StubHeap:           000001e7fc827e38
Stage:              EXITING
SecurityDescriptor: 000001e7ed53c9e0
Name:               /LM/W3SVC/2/ROOT/owa-2-132651877997755443

**TransportHeartBeat in that domain**

0:047> !findappdomain 000001e7dbb23d40
AppDomain: 000001e7fc827520
Name:      /LM/W3SVC/2/ROOT/owa-2-132651877997755443
ID:        3

0:047> !mdt 000001e7dbb23d40
000001e7dbb23d40 (Microsoft.AspNet.SignalR.Transports.TransportHeartbeat)
    _connections:000001e7dbb23d90 (System.Collections.Concurrent.ConcurrentDictionary`2[[System.String, mscorlib],[Microsoft.AspNet.SignalR.Transports.TransportHeartbeat+ConnectionMetadata, Microsoft.AspNet.SignalR.Core]])
    _timer:000001e7dbb330b8 (System.Threading.Timer)
    _configurationManager:000001e7d7d59080 (Microsoft.AspNet.SignalR.Configuration.DefaultConfigurationManager)
    _trace:000001e7dbb31f28 (System.Diagnostics.TraceSource)
    _counters:000001e7d7d5ac50 (Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager)
    _counterLock:000001e7dbb31f10 (System.Object)
    _running:0x0 (System.Int32)
    _heartbeatCount:0x1096 (System.UInt64)

**There is one active connection**

[195] 000001e79638d1e8 (System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.String, mscorlib],[Microsoft.AspNet.SignalR.Transports.TransportHeartbeat+ConnectionMetadata, Microsoft.AspNet.SignalR.Core]])
    m_key:000001e79638c610 (System.String) Length=36, String="0c58876d-efaf-461c-bdd8-1aae73688ce5"
    m_value:000001e79638d1c0 (Microsoft.AspNet.SignalR.Transports.TransportHeartbeat+ConnectionMetadata)
        <Connection>k__BackingField:000001e79638c3d0 (Microsoft.AspNet.SignalR.Transports.ServerSentEventsTransport)
            _context:000001e79638bfc0 (Microsoft.AspNet.SignalR.Hosting.HostContext)
            _heartbeat:000001e7dbb23d40 (Microsoft.AspNet.SignalR.Transports.TransportHeartbeat)
            _trace:000001e7dbb33d60 (System.Diagnostics.TraceSource)
            _timedOut:0x0 (System.Int32)
            _counters:000001e7d7d5ac50 (Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager)
            _ended:0x0 (System.Int32)
            _state:0x1 (Added) (Microsoft.AspNet.SignalR.Transports.TransportConnectionStates)
            _lastMessageId:NULL (System.String)
            _connectTcs:000001e79638cdf0 (Microsoft.AspNet.SignalR.Infrastructure.DispatchingTaskCompletionSource`1[[System.Object, mscorlib]])
            _connectionEndToken:(System.Threading.CancellationToken) VALTYPE (MT=00007ffaf4bba818, ADDR=000001e79638c460)
            _connectionEndTokenSource:000001e79638ce70 (Microsoft.AspNet.SignalR.Infrastructure.SafeCancellationTokenSource)
            _lastWriteTask:000001e7dbb33bc0 (System.Threading.Tasks.Task`1[[System.Object, mscorlib]])
            _hostShutdownToken:(System.Threading.CancellationToken) VALTYPE (MT=00007ffaf4bba818, ADDR=000001e79638c468)
            _hostRegistration:000001e79638cf70 (Microsoft.AspNet.SignalR.Infrastructure.DisposableAction)
            _connectionEndRegistration:000001e79638d180 (Microsoft.AspNet.SignalR.Infrastructure.DisposableAction)
            _requestLifeTime:000001e79638cd38 (Microsoft.AspNet.SignalR.Transports.HttpRequestLifeTime)
            <ConnectionId>k__BackingField:000001e79638c610 (System.String) Length=36, String="0c58876d-efaf-461c-bdd8-1aae73688ce5"
            <WriteQueue>k__BackingField:000001e79638c5b8 (Microsoft.AspNet.SignalR.Infrastructure.TaskQueue)
            <Disconnected>k__BackingField:000001e79638ccf8 (System.Func`2[[System.Boolean, mscorlib],[System.Threading.Tasks.Task, mscorlib]])
            <Connection>k__BackingField:000001e79638c8b8 (Microsoft.AspNet.SignalR.Infrastructure.Connection)
            _counters:000001e7d7d5ac50 (Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager)
            _jsonSerializer:000001e79638c4e0 (Newtonsoft.Json.JsonSerializer)
            _busRegistration:000001e79638d440 (Microsoft.AspNet.SignalR.Infrastructure.DisposableAction)
            _transportLifetime:000001e79638d1a0 (Microsoft.AspNet.SignalR.Transports.ForeverTransport+RequestLifetime)
            <Pool>k__BackingField:000001e7d7d59678 (Microsoft.AspNet.SignalR.Infrastructure.MemoryPool)
            <Received>k__BackingField:000001e79638ccb8 (System.Func`2[[System.String, mscorlib],[System.Threading.Tasks.Task, mscorlib]])
            <Connected>k__BackingField:000001e79638cc38 (System.Func`1[[System.Threading.Tasks.Task, mscorlib]])
            <Reconnected>k__BackingField:000001e79638cc78 (System.Func`1[[System.Threading.Tasks.Task, mscorlib]])
            AfterReceive:NULL (System.Action)
            BeforeCancellationTokenCallbackRegistered:NULL (System.Action)
            BeforeReceive:NULL (System.Action)
            AfterRequestEnd:NULL (System.Action`1[[System.Exception, mscorlib]])
            _counters:000001e7d7d5ac50 (Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager)
        <LastMarked>k__BackingField:(System.DateTime) 2021/05/11 19:04:12.142 VALTYPE (MT=00007ffaf4bb1648, ADDR=000001e79638d1d0)
        <Initial>k__BackingField:(System.DateTime) 2021/05/11 07:18:41.843 VALTYPE (MT=00007ffaf4bb1648, ADDR=000001e79638d1d8)
    m_next:NULL (System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.__Canon, mscorlib],[System.__Canon, mscorlib]])
    m_hashcode:0x6a84d18a (System.Int32)

**Comment by davidfowl** [comment]
Can you move this issue to here http://github.com/SignalR/SignalR
