### ISSUE TITLE
Add support for "prompt="select_user" with WASM / MSAL

### ISSUE THREAD

**Issue by gusmanb** [dotnet/aspnetcore#32640]
When a user has more than one account for a service it is desirable to ask which account the user wants to use. Usually using MSAL on Javascript you can add "prompt=select_user" but this is not possible (as far as I know) to specify when using MSAL from Blazor.

The proposed feature would be to add to MsalProviderOptions a field to enable this.

**Comment by mkArtakMSFT** [comment]
This is related to https://github.com/dotnet/aspnetcore/issues/25391

**Comment by TestLearningUser** [comment]
I would like to know if Multitenant applications / accounts will be shown a propmpt for selecting a user,

For example i've got miguelmorales@test.com
that is invited into the tenant secondtest (miguelmorales_test#ext#@secondtest.com

Could I do login with miguelmorales@test.com and a promp "Which domain do you want to login" could be shown?

**Comment by javiercn** [comment]
Covered by https://github.com/dotnet/aspnetcore/issues/42580
