### ISSUE TITLE
[dotnet-watch] Investigate hot restarting the host

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#32648]
With dotnet-watch's current implementation of hot reload, changes to Program.Main and Startup don't have any effect. In particular changes to the DI container or middleware pipeline do not produce any changes. This issue tracks figuring out if we could instead restart the host.

**Comment by davhdavh** [comment]
In order to support this, it would need to log every single method ever called during init phase (which in itself would need to be well defined) and then compare if any of these methods were updated during the hot reload. Seems overkill to me.
