### ISSUE TITLE
How I can build packages that not included in AspNetCore.App?

### ISSUE THREAD

**Issue by deflarten** [dotnet/aspnetcore#32671]
I need build aspnetcore from source via build.sh and get packages (.nupkg) like Microsoft.AspNetCore.Mvc.NewtonsoftJson, Microsoft.AspNetCore.Authentication.JwtBearer and other packages that your team publish to nuget
How I can do it correctly? Maybe I need some different script... I dont know...

**Comment by javiercn** [comment]
@deflarten thanks for contacting us.

@dotnet/aspnet-build do you have any thoughts here?

**Comment by wtgodbe** [comment]
`build.sh -pack` should do the trick

**Comment by wtgodbe** [comment]
The packages will wind up in `artifacts\packages`

**Comment by dougbu** [comment]
If you are aiming not to change the code but to pick up fixes before our releases, unsigned packages containing what will eventually end up on NuGet.org are also available in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

**Comment by dougbu** [comment]
@deflarten thank you for your feedback. We're closing this issue as the questions asked here have been answered.
