### ISSUE TITLE
[Razor] Bring back RazorLangversion 6.0

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#32672]
We undid the change for adding a new RazorLangVersion because we thought it would resolve some build/stability issues that we were observing on the build. Undoing the change didn't seem to fix the issue, so we should try and bring back the change and solve the underlying root cause.

This issue tracks the work for "re-reverting the commits" on the SDK and the razor compiler as well as updating the codebase in all places where its necessary to key off functionality of RazorLangVersion 6.0:
* Generic type constraints
* Generic parameters type inference
* JS Modules

**Comment by captainsafia** [comment]
@javiercn We can do this once https://github.com/dotnet/aspnetcore/pull/32581 is in which attempts to resolve the generic params issue by disabling the RSG for projects where it is throwing errors.

**Comment by javiercn** [comment]
@captainsafia If you want to do it, go ahead.

I don't think we have any rush to bump the version, just filed an issue to make sure we keep track of it and have a place to put all the things we need to key of of this.

**Comment by captainsafia** [comment]
Now that we're on the new SDK, let's give it a couple of days to see how things fare with the build issues.

**Comment by mkArtakMSFT** [comment]
Thank you @captainsafia for agreeing to help with this issue. This will help @javier with his backlog in current milestone.
