### ISSUE TITLE
[dotnet-watch] Document how source generators can support hot reload

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#32673]
It is obviously possible for a source generator to support hot reload, since changes to razor files are detected and updated via hot reload.

It should therefore be documented how other source generators might take advantage of this.

**Example:** 
A source generator parses files of type *.rrr and generates corresponding cs classes.
a. Document how to make watch detect changes to a rrr file.
b. Document how the change results in a hot reload (assuming the change is supported by hot reload) instead of a full reload.
Notice the current solution documented for a:`<ItemGroup><Watch Include="**/*.rrr"/></ItemGroup>` always causes a non-hot reload.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Hot reloading files generated by other source generators is not a supported scenario at this time.
