### ISSUE TITLE
[Feature request] `UnifyUrlMiddleWare`

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#32670]
### Is your feature request related to a problem? Please describe.
for most website, we normally only use 1 domain  for our site to improve SEO experience.  
asp.net core now have  `HttpsRedirection`  and `UrlRewriter` ，  but it's hard  to  redirect all the "temporary url" to official url.
for example:

temporary url |  redirect to
|--------------|-----------------|
http://A.com |  https://www.A.com
http://www.A.com |  https://www.A.com
https://A.com |  https://www.A.com
https://www.A.com  |  `no action`
http://B.com |  https://www.A.com
http://www.B.com |  https://www.A.com
https://B.com |  https://www.A.com
https://www.B.com  |  https://www.A.com

### Describe the solution you'd like

we can use an the `UnifyUrlMiddleWare`  to achieve this simply.

usage 

```C#
//startup.cs
app.UseUnifyUrl();

```

```json
// appseting.Production.json
"UnifyUrl":{
    "Enable": true,
    "Url":"https://www.A.com",
    "IgnoreUrl":[ 
         "http://B.com",
         "https://B.com" 
    ]
}
...
```

### Additional context
none

**Comment by javiercn** [comment]
@John0King thanks for contacting us.

HttpsRedirection is meant to support simple scenarios, if you have an scenario that leverages UrlRewriter the recommendation is that you integrate the https redirection within your rewrite rules directly.

**Comment by John0King** [comment]
@javiercn   @BrennanConroy   the asp.net core's URLRewriter is not like the IIS,   if you use that middleare,  that would normally  breack your development,  it's rules can not be reconfigured via  `appseting.<Environment>.json` ,   that's Why I ask for this  much simpler solution !

the benefit:
- much simple and available for nearly every website !
- configure via `appsetting.<Environment>.json`, so deploy and develop can not different configuration.
- solve htts redirection and www redirection at once, and the logic is way simple.


and the pain spot of  URLReWriter:

-  there no easy way your can get the `IFileProvider` in `ConfigureServices` method  (by using `services.Configure<RewriteOptions>()`  via DI,  and you can not get a `IServiceProvider` , there no `services.Confiugre<TOptions>(Action<TOptions,IServiceProvider>)` override). 
-  if your hard code the read for `URLRewriter.xml`  in `Startup.Configure()` method, then it would break your develop if you pre write your rules, and commit the code in Source Control.

**Comment by John0King** [comment]
it's a very simple requirements,  every microsoft's site have this configured  eg:
```
[ http://xbox.com https://www.xbox.com , https://xbox.com ]=> https://www.xbox.com
[ http://dot.net ,  https://dot.net , http://dotnet.microsfot.com ]  => https://dotnet.microsoft.com/

and many many more.

```
and @javiercn @BrennanConroy   I'd like to make PR to implement the `UnifyUrlMiddleWare`  , but the size of this repository is too huge for me to clone it  (I'm in China, and github  can break access  in any seconds, it can not (or hard) clone big repo before, and now it worth,  we could not even access the github.com steadily)

**Comment by John0King** [comment]
@davidfowl   I find out there many things need to be set before I create a project inside this repo/folder  (`~/src/Middleware/UnifyUrl`),   such as sdk and some extra `.props` file.

Can I just create a normal  .net class library and copy the code into it, and wait you guys change and merge it ?

**Comment by John0King** [comment]
@davidfowl   I find out there many things need to be set before I create a project inside this repo/folder  (`~/src/Middleware/UnifyUrl`),   such as sdk and some extra `.props` file.

Can I just create a normal  .net class library and copy the code into it, and wait you guys change and merge it ?

**Comment by javiercn** [comment]
> * configure via `appsetting.<Environment>.json`, so deploy and develop can not different configuration.

I'm missing something here. It should be trivial to get these values from config and apply them to the URL rewrite middleware in ConfigureServices.

> * solve htts redirection and www redirection at once, and the logic is way simple

We already provide a general way of doing this via the URL rewrite, we normally don't add "one shot" features like this one since it increases the framework API surface and makes it harder to evolve without breaking people.

We haven't heard significant feedback about this being a problem for customers and based on that we should avoid adding something like this for now until we find enough demand for it. In addition to that, adding a new middleware is a big deal, since its a new concept users need to grok. It might be better to support config in the URL rewrite middleware directly.

**Comment by John0King** [comment]
> It might be better to support config in the URL rewrite middleware directly

I agree.


and  I want to point out is  that  it's very very common SEO technics to just use one  official domain. and with `https` turned on, now we have to dealing with 4 possible url  for 1 domain.  the UrlRewiter middlware can be hard code to dealing with inside url, but for domain it must not using hard code.   and the purpose is little bit different from URL Rewriter

**Comment by davidfowl** [comment]
> @davidfowl I find out there many things need to be set before I create a project inside this repo/folder (~/src/Middleware/UnifyUrl), such as sdk and some extra .props file.

> Can I just create a normal .net class library and copy the code into it, and wait you guys change and merge it ?

No. The only reason I reopened the bug is because bot closed it in the middle of a discussion. I don't think we should add a new middle here. I think you should ship a middleware from your own GitHub repository to nuget.

**Comment by John0King** [comment]
@davidfowl   I see.

and what about  the UrlRewiter using configuration  file  to configure the rule ?  Is there any issue track for that ?

**Comment by javiercn** [comment]
Using config to create the rules should be possible today by injecting IConfiguration in the `Startup` class constructor (like the templates do) and reading the rules from a section in config. 

I don't think we need to come up with a config schema, etc for it, unless we can determine it drastically simplifies things.

**Comment by John0King** [comment]
@javiercn

> Using config to create the rules should be possible today by injecting IConfiguration in the Startup class constructor (like the templates do) and reading the rules from a section in config.

Is it possible  to reading the rule from `IConfiguration` today ? 

I think , at least , we should add an extension method of `UrlRewriterOption` like this :

```C#
    public static RewriteOptions AddIISUrlRewriteFileFromConfiguration(this RewriteOptions , IConfiguration configuraion)
{
    // well,  current AddAddIISUrlRewrite  need an non-nullable  IFileProvider, this should be an bug.  
   // because  if the IFileProvider is null , then it well use  the default  IFileProvider from  IWebHostEnvironment.

  //  and  !!!!!!
  //  we can not get the IServiceProvider here, and neither ConfigurateService ,
  //  but the IFileProvider normally regiested into DI, instead create an static instance,
  //  so how we get the `IFileProvider`  we want ? 

}
``` 

usage :

```json
{
    "UrlRewriter":{
         "IISUrlRewriterFilePath":"path to rewriter.xml"
    }
}
```

```C#
// ConfigureService()
service.Configure<RewriteOptions>(op=> op.AddIISUrlRewriteFileFromConfiguration(Configuration.GetSection("UrlRewriter")))

```

**Comment by davidfowl** [comment]
That would make sense for non IIS and non Apache rewrite rules

**Comment by John0King** [comment]
do we have any decision on improve the simple SEO experience？
leave it alone, and I create a middleware on nuget,  
or ,  we  improve the `UrlRewriterMiddleware`  to support  easily register for IIS/Apache rewriter configuration file ?

**Comment by javiercn** [comment]
@John0King We think these things are better handled in nuget packages created by the community. If we see more demand for it, we might consider changes, however at least for now we prefer not building these things in box.

**Comment by John0King** [comment]
@javiercn  @davidfowl 
I think to improve the `UrlRewriter` ,  and  add configuration for the IIS/Apache  rewrite configuration file  may be a better idea,
don't you think ?
