### ISSUE TITLE
Fix JSInterop layering mistake around JSON serialization of results

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#32678]
The intent for JSInterop is that it encapsulates the rules and semantics of JSON serialization for parameters and result values. Each hosting platform (Server, WebAssembly, WebView) only needs to know how to transmit JSON strings, and can't control how that JSON is generated, hence there's never any risk that different platforms have different behavior or bugs because they are using different converters, for example.

This has all been working well for us, but I've realised there's a mistake. JSInterop deals with:
 * serializing .NET-to-JS params, and deserializing the result values
 * deserializing JS-to-.NET params, but **not** serializing the result values

This "not" part is the mistake. It should cover this too. The fact that it doesn't now leads to two problems:

1. For the binary-and-streaming interop work, it would leak internal concerns about this into each of the hosting platforms
2. For the S.T.J. source generator support, it creates an issue because the current call-result payload combines the user-supplied result into a single JSON blob with system-controlled data about the call ID etc., which means there isn't a single "context" class that could deserialize it all in a nice way.

To fix this I propose we have a breaking change to the JSInterop abstraction contract where we: (1) have it pre-serialize the JS-to-.NET result values in the same way it does everything else, and (2) split up the call result JSON blob into two parts - one managed by the system, and one that purely represents the user result type. This will allow us to support passing a serialization context or even entirely custom serialization options without risking breaking the call info data managed by the system.

Although this is a breaking change, the only people it would affect are people who have built their own JSRuntime implementation, which is very few people. It's possible that bUnit would need to react, but I wouldn't expect any applications to be able to observe this change.

If we are doing this, it should be really soon (like, first day or two of next week) to avoid blocking @TanayParikh's work on binary/streaming interop. I'm happy to do it.

**Comment by SteveSandersonMS** [comment]
cc @dotnet/aspnet-blazor-eng for any feedback, otherwise I plan to do this soon.

**Comment by javiercn** [comment]
Can you point to a PR?

**Comment by SteveSandersonMS** [comment]
It's not implemented yet, so not yet. I'm filing this issue to check nobody has any definite cause for concern before I spend the time doing that.
