### ISSUE TITLE
Improve WebSocket failure on HTTP/1.0

### ISSUE THREAD

**Issue by agerchev** [dotnet/aspnetcore#32674]
Hello, 

In our environment, we cannot make websocket connection in aspnetcore signalR application hosted in IIS (InProcess) and behind reverse proxy (NGINX). 
The TCP connection is reset from IIS (or something else) and the protocol cannot be upgraded to proxy and client receives 502
Bad Gateway, then signalR fallbacks to eventStream. 
Here is the TCP dump.

![TCPDump](https://user-images.githubusercontent.com/4629857/118268867-a0d88200-b4c6-11eb-8728-dd5f1d32cc55.png)

Here is detailed info for our environment: 
AspnetCore SignalR application is hosted in IIS(in process)
dotnet --info: 
  Version: 5.0.4
  Commit:  f27d337295
IP: 192.168.8.100

The reverse proxy is NGINX hosted in Red Hat Enterprise Linux 8.3 - IP: 192.168.8.101
here is the NGINX configuration 

```
http {
    map $http_connection $connection_upgrade {
        "~*Upgrade" $http_connection;
        default keep-alive;
    }
}

server {
    listen       443 ssl http2;

    root         /usr/share/nginx/html;
    
    error_log /var/log/nginx/error.log warn;
    
    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    location /DashboardHub {
        
        proxy_cache off;
        proxy_buffering off;
        proxy_read_timeout 100s;
	proxy_set_header Host $host;
	proxy_pass http://upstream80;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
    	proxy_set_header X-ClientCert $ssl_client_escaped_cert;
        proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Connection "";
    	proxy_pass http://upstream80;
    	proxy_redirect off;
	client_max_body_size 12M;
	proxy_http_version 1.1;
    }
    
}
```

What I have tried so far: 

1. If we connect to the application directly to IIS from browser everything is working as expected. The app is opening web socket connection and everything is ok. 
2. If we direct the browser through NGINX the app is working, but the browser cannot open websocket connection and the HTTP  status is 502. It then fallbacks to SSE. 
3. If we forward the traffic from NGINX directly to kestrel (start the application as console app) skipping IIS it is also working. 

I have turned FRT in IIS and there is something strange: 
68. GENERAL_RESPONSE_HEADERS Headers="Upgrade: websocket
Server: Microsoft-IIS/10.0
Sec-WebSocket-Accept: rdM3H8k1KPmD/f8HhyLCIw4vpng=
Connection: Upgrade
" 11:49:07.650 

69. GENERAL_FLUSH_RESPONSE_END BytesSent="0", ErrorCode="The parameter is incorrect.
 (0x80070057)" 11:49:07.650 
 
70. ANCM_INPROC_REQUEST_DISCONNECT  11:49:07.650 

71. GENERAL_READ_ENTITY_START  11:49:07.650 

72. GENERAL_READ_ENTITY_END BytesReceived="0", ErrorCode="The specified network name is no longer available.
 (0x80070040)" 

here is complete tcpdump file with two dumps from Failed Request Tracing. One with the failing request from the proxy, and one from a working one.
[Data.zip](https://github.com/dotnet/aspnetcore/files/6478780/Data.zip)

Thank you !

**Comment by shirhatti** [comment]
Failing headers

```
Cache-Control: no-cache
Connection: keep-alive, Upgrade
Pragma: no-cache
Upgrade: websocket
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cookie: <redacted>
Host: portal.dev.mz-is150.dev.local
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
X-Forwarded-For: 192.168.70.139
X-Forwarded-Proto: https
Sec-WebSocket-Version: 13
Origin: https://portal.dev.mz-is150.dev.local
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: FXtt4U/fBF0e6GkDAkNFTg==
```

**Comment by shirhatti** [comment]
Headers for the successful request
```
Cache-Control: no-cache
Connection: keep-alive, Upgrade
Pragma: no-cache
Upgrade: websocket
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cookie: <redacted>
Host: portal.dev.mz-is150.dev.local
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Sec-WebSocket-Version: 13
Origin: https://portal.dev.mz-is150.dev.local
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: f1qPvQkRuq48kN/FeuxJZA==
```

**Comment by BrennanConroy** [comment]
Is it possible for you to share an application that hits this issue?

The only difference we can see is that the failing case sends the X-Forwarded-* headers on the request.

**Comment by halter73** [comment]
If it's not a difference in the request headers, I still think IIS response headers could be the proximate cause of the failed WebSocket requests between NGINX and IIS. Is Kestrel responding with different response headers to NGINX? It's possible that NGINX doesn't like the response headers for some reason and it RSTs the connection causing the flush error.

**Comment by agerchev** [comment]
I do not think the NGINX i resetting the connection, because it can be seen from the tcp dump, that the RST packet is send from 192.168.8.100 (windows machine ) and the request comes from *.101 (the linux machine).

I downloaded sample application (https://github.com/dcomartin/Practical.AspNetCore.SignalR), then upgraded to 5.0  and it works, exactly the same way: 
1.If i run it without IIS, just kestrel it works. 
2. If i redirect traffic from NGINX to the console app from (1)  - it works 
3. if i deploy the app behind IIS and access it - it works. 
4. if i redirect the traffic from NGINX to the APP hosted in IIS, IIS resets the connection. 
4.1 if the application is hosted outOfprocess it does not work again, this way, the connection is reset from ACNM and here is the access log from IIS to NGINX `2021-05-12 07:44:08 192.168.8.100 GET /DashboardHub id=yjgtuAyCl0nVR-Rv6MRU3Q 80 - 192.168.8.101 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:88.0)+Gecko/20100101+Firefox/88.0 - 502 3 64 8`

I thought that maybe the configuration of NGINX is not ok, but it is working in case (2), so it must be something else. 

I have included new data from the sample application. It has different hub location and some changes in the headers.
[DataWithApp.zip](https://github.com/dotnet/aspnetcore/files/6494059/DataWithApp.zip)

**Comment by BrennanConroy** [comment]
Ok, we figured it out. Http.sys only supports Http/1.1 (or higher) and nginx defaults to 1.0, so when it sends the websocket response it checks the http protocol version and throws since it is invalid.

Our docs do use http/1.1 by default https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx, and it looks like you have that for the `/` location, but not the signalr specific location.

**Comment by Tratcher** [comment]
Upgrade mechanics were not defined until HTTP/1.1. We could mitigate this by requiring HTTP/1.1 in server upgrade checks to at least produce a better error message. However, that might break people currently deploying kestrel with NGinx. Maybe we should at least add that check for IIS & Http.Sys.

**Comment by halter73** [comment]
I definitely don't think we should break this scenario with Kestrel, but making it a clearer error for IIS & Http.Sys makes a lot of sense.

**Comment by agerchev** [comment]
It work, thank you!
We made the configuration according to this doc: https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-5.0#linux-with-nginx, maybe it is a good idea to include it there too. We saw the NGINX docs too https://www.nginx.com/blog/websocket-nginx/, but apparently missed the http 
version in the configuration 
```
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

**Comment by BrennanConroy** [comment]
> maybe it is a good idea to include it there too

Could have swore it was, thanks for pointing that out 😃

**Comment by Tratcher** [comment]
Offline design discussion: How to best make this failure visible in SignalR? If the servers say IsUpgradableRequest = false for HTTP/1.0 then what error does SignalR present?

Alternative: Instead of changing IsUpgradableRequest, instead put the check in UpgradeAsync and throw an explicit error about the version. It would be more targeted, but it would make providing a graceful fallback more difficult.
