### ISSUE TITLE
Adopt OSPlatformAttributes logic in aspnetcore

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#32685]
This is a follow up to https://github.com/dotnet/aspnetcore/pull/32023. Essentially, we need to port the logic https://github.com/dotnet/runtime/blob/c7e02f3773da25946328eba150a70caa3b0e4c74/eng/versioning.targets#L53-L85 to aspnetcore.

**Comment by dougbu** [comment]
We have just two projects (Microsoft.AspNetCore.Hosting.WindowsServices and Microsoft.AspNetCore.Server.Kestrel.Transport.Quic) where _any_ `[assembly: SupportedOSPlatform(...)]` instances were deemed necessary. It's not clear where what we have is insufficient.

Why do we need anything different from the current infrastructure❔ In particular, why do we need either additional `[assembly: SupportedOSPlatform(...)]` attributes or the complicated logic from the dotnet/runtime repo❔

**Comment by dougbu** [comment]
/btw https://github.com/dotnet/runtime/blob/main/eng/versioning.targets#L73 looks like a significant bug @jeffhandley

**Comment by jeffhandley** [comment]
> /btw https://github.com/dotnet/runtime/blob/main/eng/versioning.targets#L73 looks like a significant bug @jeffhandley

That code is right, but it highlights just how badly named the `<SupportedPlatform>` property is. 😟 `<SupportedPlatform>`  is actually used to specify which platforms the analyzer is expected to check for compatibility--not which platforms are _actually supported_. There is no MSBuild property for which platforms are actually supported--that's done through the `OSPlatform` attributes. In the `runtime` repo though, we populate the `OSPlatform` attributes using MSBuild properties of `<SupportedOSPlatform>` and `<UnsupportedOSPlatform>`. Sooooo similar in name.

The code you linked to is ensuring that for every `<SupportedOSPlatform>` _and every_ `<UnsupportedOSPlatform>` that the assembly is configured for, we include the platform in the `<SupportedPlatform>` MSBuild property to make sure the analyzer checks compatibility for the platform. The [`CA1418` analyzer](https://github.com/dotnet/runtime/issues/45851) will produce warnings for any platforms used in attributes that aren't included in the `<SupportedPlatform>` list.

Thanks for the tag on this regardless. It really emphasizes the poor naming.
/cc @terrajobst

**Comment by dougbu** [comment]
Discussed offline and @JunTaoLuo has decided not to be passionate. Closing since duplicating what dotnet/runtime has wouldn't simplify _our_ infrastructure.
