### ISSUE TITLE
Exception in VS running a Blazor WebAssemby project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32687]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Exception-in-VS-running-a-Blazor-WebAsse/1379426)._

---
[severity:It's more difficult to complete my work]
When I debg in VS a Blazor WebAssemby project, sometimes I get this error from the image.
Then I have to either restart VS or even the machine (maybe because a service is malfunctioning) to make it work again.

! [image.png] (https://aka.ms/dc/image?name=B1d89985ead8d418a87caede0ef2537ed637521388082219611_20210324-102641-image.png&tid=1d89985ead8d418a87caede0ef2537ed637521388082219611)

---
#### Feedback Bot on 3/23/2021, 08:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/7/2021, 09:55 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by uniqueiniquity** [comment]
Moving to GitHub since the VS JS debugger is unable to connect to the Blazor Debug Proxy.

**Comment by captainsafia** [comment]
@uniqueiniquity Thanks, Ben. It looks like there might have been an issue launching the debug proxy.

We document some common issues that might cause the debug proxy not to launch in [our docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio). Do you think it would be possible to reference this in the exception message?

**Comment by uniqueiniquity** [comment]
@captainsafia I assume you mean the troubleshooting section. Sounds reasonable to me, but I'll work with @EricCornelson to see that's doable.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please try out the suggestions from the docs provided above and let us know if you're still facing this issue.

> We document some common issues that might cause the debug proxy not to launch in our docs. Do you think it would be possible to reference this in the exception message?
