### ISSUE TITLE
web api with microsoft identity error 401

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/web-api-with-microsoft-identity-error-40/1422358)._

---
web api with microsoft identity error 401

Curl

curl -X GET "https://localhost:44395/WeatherForecast" -H  "accept: text/plain"
Request URL
https://localhost:44395/WeatherForecast
Server response
Code	Details
401
Undocumented
Error:
Response headers
 date: Wed12 May 2021 21:49:15 GMT 
 server: Microsoft-IIS/10.0 
 www-authenticate: Bearer 
 x-powered-by: ASP.NET

---
#### Feedback Bot on 5/12/2021, 07:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/13/2021, 00:24 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
There is not enough information to help fix this.

Please provide a sample repo illustrating the problem
