### ISSUE TITLE
Missing x86 vs x64 qualifier in add/remove programs for ASP.NET Core shared framework

### ISSUE THREAD

**Issue by nguerrera** [dotnet/aspnetcore#32708]
### Describe the bug
ASP.NET Core Shared Framework add/remove programs entry doesn't differentiate x86 and x64 and appears like a duplicate.

![image](https://user-images.githubusercontent.com/75470/118337483-c49cc780-b4c8-11eb-92ec-161321ff27ae.png)

### To Reproduce

I saw this after Microsoft Update pushed new versions to my machine. The prior versions were from Visual Studio and hidden from add/remove programs. I have not verified, but I suspect you can repro this on any machine by installing both x64 and x86 ASP.NET Core shared frameworks

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21258.4
 Commit:    e659912dfb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21258.4\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Pilchie** [comment]
Tagging @wtgodbe

**Comment by wtgodbe** [comment]
Thanks for the report - looks like it should be as simple as updating https://github.com/dotnet/aspnetcore/blob/fdabaf00a6720d852ec3120b7bbe4b14de2f3ccf/src/Installers/Windows/SharedFrameworkBundle/SharedFrameworkBundle.wixproj#L67-L68 to include `Platform`. I'll spin up PRs & validate

**Comment by wtgodbe** [comment]
Actually, maybe this is intentional? `BundleNameFull` is just `BundleName` + `Platform`, which implies leaving `Platform` out of `BundleName` was on purpose: https://github.com/dotnet/aspnetcore/blob/fdabaf00a6720d852ec3120b7bbe4b14de2f3ccf/src/Installers/Windows/SharedFrameworkBundle/SharedFrameworkBundle.wixproj#L67-L70

@joeloff any harm in including `Platform` in `BundleName` and having it be identical to `BundleNameFull`?

**Comment by wtgodbe** [comment]
For what it's worth, dotnet/runtime _does_ include `Platform` in the bundle name that gets displayed in add/remove programs

**Comment by joeloff** [comment]
Yeah, this dates back to 2.0. The hosting bundle didn't have platform information in the name and I suspect we maybe copied/reused some properties for the shared framework bundle. Would be good to fix in the standalone fx bundles

**Comment by wtgodbe** [comment]
PR: https://github.com/dotnet/aspnetcore/pull/32778. I'll put up backport PRs once I've validated it does what I expect

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/32968
https://github.com/dotnet/aspnetcore/pull/32969
