### ISSUE TITLE
.razor components produce an unfixable warning when using @implements or @inherits with a generic type

### ISSUE THREAD

**Issue by gulbanana** [dotnet/aspnetcore#32733]
### Describe the bug
When Nullable Reference Types are enabled (`<Nullable>enable</Nullable>` in the .csproj), referring to a supertype with nullable parts results in a generated .razor.g.cs which disables nullable reference types then uses one. This line:
`@implements SomeGeneric<T?>`
results in warning CS8669, "The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.". However, there is no way to enable the nullable annotations context for the generated code or to disable it for the .razor file, leaving you in a catch-22 situation.

### To Reproduce
Here is a simple repro: https://github.com/gulbanana-bugs/repro-blazor-nullable-generic-parameters

### Further technical details
- ASP.NET Core version
5.0.6

- Include the output of `dotnet --info`
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS Code 1.56.2

**Comment by mkArtakMSFT** [comment]
@captainsafia do you remember what was the fix in the compiler which should have fixed this? We would like to confirm that it's fixed.

**Comment by captainsafia** [comment]
@mkArtakMSFT The external issue is https://github.com/dotnet/roslyn/issues/45960.

**Comment by mkArtakMSFT** [comment]
Closing as the underlying roslyn issue has been fixed.
