### ISSUE TITLE
DynamicComponent not initializing properly

### ISSUE THREAD

**Issue by tmandekic** [dotnet/aspnetcore#32745]
### Describe the bug
When using DynamicComponent, if the component of the same type is instantiated through a mechanism such as select list, or a dynamic menu list (a list of buttons), unexpected behaviour occurs when components of the same type are selected by user one after the other. 
For example, I have 2 Razor components: CheckboxComponent and RadioComponent. 
I have created a select list that dynamically invokes those 2 components, by using DynamicComponent.
What I want to do is to select RadioComponent 1, then RadioComponent 2 options. (that should instantiate RadioComponent two times). When I click/select RadioComponent 1 option, code correctly goes into RadioComponent's OnInitialized method. I then selects second RadioComponent 2, the code goes only into OnParametersSet method of the RadioComponent (not in OnInitialized). It seems that the first instance of the RadioComponent is re-used when I was expecting to have new instance created.
But if I click on RadioComponent 1, then on CheckboxComponent, then on second RadioComponent 2, the code correctly goes into OnInitialized method every time. 

Also, if there are 2 DynamicComponents hardcoded in the Razor page, both referencing the same type (RadioComponent), each one is correctly instantiated (the code goes into OnInitialized for both components)

### Questions
Is it possible to have "forceReload" property (similar to NavigationManager.NavigateTo() method parameter)?
Otherwise, how can I force reload when new instance is required? I cannot use links, as these are just components inside a page, not pages (these components do not have @page directives)

### To Reproduce
Github: 
https://github.com/tmandekic/DynamicControlsTest/blob/master/DynamicControlsTest/Pages/Index.razor

```
@page "/"

<select @onchange="onChange">
    <option value="@nameof(CheckboxComponent)">@nameof(CheckboxComponent)</option>
    <option value="@nameof(RadioComponent)">@nameof(RadioComponent)</option>
    <option value="@nameof(RadioComponent)">@nameof(RadioComponent)</option>
    <option value="@nameof(TextComponent)">@nameof(TextComponent)</option>
</select>

<br>
<DynamicComponent Type="selectedType" Parameters="dynParams" />
<br><br><br><br>
<DynamicComponent Type="typeof(DynamicControlsTest.Shared.RadioComponent)" Parameters="dynParams" />
<br />
<DynamicComponent Type="typeof(DynamicControlsTest.Shared.RadioComponent)" Parameters="dynParams2" />

@code{
    Type selectedType = typeof(CheckboxComponent);

    private Dictionary<string, object> dynParams { get; set; }
    private Dictionary<string, object> dynParams2 { get; set; }

    protected override void OnInitialized()
    {
        dynParams = new Dictionary<string, object>();
        dynParams.Add("Counter", 1);
        dynParams2 = new Dictionary<string, object>();
        dynParams2.Add("Counter", 2);
    }
    private int clickedCount;

    public void onChange(ChangeEventArgs arg)
    {
        if (dynParams == null)
        {
            dynParams = new Dictionary<string, object>();            
        }
        dynParams.Clear();
        dynParams.Add("Counter", clickedCount);

        selectedType = Type.GetType($"DynamicControlsTest.Shared.{arg.Value}");
        clickedCount++;
    }
}
```

https://github.com/tmandekic/DynamicControlsTest/blob/master/DynamicControlsTest/Shared/RadioComponent.razor

```
<input type="radio"/>

@code {
    [Parameter]
    public int Counter{ get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();
    }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();
    }
}
```

### Further technical details
- ASP.NET Core version: .NET 6 Preview 3
- IDE: Microsoft Visual Studio Community 2019 Preview, Version 16.10.0 Preview 3.0
 
- The output of `dotnet --info`:
```
- .NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
The scenario doesn't totally make sense to me because your two `<select>` options for RadioComponent are completely identical to each other:

```razor
    <option value="@nameof(RadioComponent)">@nameof(RadioComponent)</option>
    <option value="@nameof(RadioComponent)">@nameof(RadioComponent)</option>
```

As such, changing from one to another of these won't change the `selectedType`, and hence doesn't have any effect as far as the `<DynamicComponent>` is concerned.

> Is it possible to have "forceReload" property (similar to NavigationManager.NavigateTo() method parameter)? Otherwise, how can I force reload when new instance is required?

You can control the preservation or non-preservation of child instances using `@key`. For example, by changing the `@key` value on your `<DynamicComponent>`, you can force it to be replaced with a new subtree. See https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#use-key-to-control-the-preservation-of-elements-and-components
