### ISSUE TITLE
Identity User Name is null in Publish Mode ?

### ISSUE THREAD

**Issue by avadaneid** [dotnet/aspnetcore#32762]
I'm working on the Blazor Server-side and I want to access the windows user name. I tried doing this, as per the documentation, using the `AuthenticationStateProvider `object. The issue is that the `User.Identity.Name` property is null when I run the solution in Release mode. In Express mode it's working fine, I can get the `User.Identity.Name` property, in release mode the value is null.

This is the `AuthenticationStateProvider `object:

       public class Authenticator
    {
        public readonly AuthenticationStateProvider _auth;

        public Authenticator(AuthenticationStateProvider authenticationStateProvider)
        {
            _auth = authenticationStateProvider;
        }
    }
I inject it in Startup.cs :

`services.AddScoped<Authenticator>();`

I enabled windows authentication:

     "iisSettings": {
        "windowsAuthentication": true,
        "anonymousAuthentication": false,
        "iisExpress": {
          "applicationUrl": "http://localhost:49349",
          "sslPort": 0
        }
      }
This is how I use the object:

`return _auth.GetAuthenticationStateAsync().Result.User.Identity.Name.Substring(3);`

I also enabled WebSocketProtocol:

![image](https://user-images.githubusercontent.com/51731664/118462093-01ee9880-b707-11eb-96ea-435c2df71546.png)

The `Name` property of the `Identity` object is null, only in release mode, in normal Debug mode on IIS Express, it works as expected.

I use ASP.NET CORE 3.1 with VisualStudio 16.9.4. I also have this issue on Windows Server 2012 after I publish the app on ISS.

I use ASP.NET CORE 3.1 with VisualStudio 16.9.4. I also have this issue on Windows Server 2012 after I publish the app on ISS.

EDIT 1: I also have the same issue when using IHttpContextAccessor with Blazor-Server. It gets the user name in IIS Express but in Release mode the Name is null.

EDIT 2: The issue appears when I run the app with the application name instead of IIS Express. From what I read on the internet, this is using Kestrel server behind.

**Comment by javiercn** [comment]
@avadaneid thanks for contacting us.

Check out the instructions for configuring windows auth on Kestrel [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#kestrel)

This issue is not specific to Blazor. Make sure you can get correctly authenticated in your deployed application and once you have that, authentication in Blazor should work.

Moving this issue to `security` so that those folks can help you further if needed.

**Comment by avadaneid** [comment]
Ok, thank you for your help @javiercn.

I added  the package  _Microsoft.AspNetCore.Authentication.Negotiate_ and configured the services and pipeline in Startup.cs:

1. Added the service: `services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate()` in `ConfigureServices.cs`
2. Added authorization in `Configure `method:

```
   app.UseAuthentication();
   app.UseAuthorization();
```

I still have the same issue when using either `IHttpContextAccessor `or `AuthenticationStateProvider`. 

This is my IIS Server configuration:
![image](https://user-images.githubusercontent.com/51731664/118479509-c610fe80-b719-11eb-93f0-54c1b311c0d2.png)

**Comment by javiercn** [comment]
@avadaneid Using IHttpContextAccessor in Blazor server is discouraged. See details [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state)

Blazor server apps don't run in the context of an HTTP request and don't have access to the HTTP context. If you need any information from the HTTP context you need to capture it ahead of time.

**Comment by avadaneid** [comment]
@javiercn I read the docs, I know that IHttpContextAccessor is discouraged, but because I could not make it work with AuthenticationStateProvider I also tried IHttpContextAccessor. Both of them seems to work fine on IIS Express. In case I manage to find the issue I will use  AuthenticationStateProvider. This issue seems weird because I used windows authentication on other projects using Razor pages on ASP.NET Core and I did not had this issue, I don't know if it's related to Blazor or not.

**Comment by javiercn** [comment]
@avadaneid Make it work in a razor page in the project first, and then it should just work with Blazor Server.

**Comment by avadaneid** [comment]
If anyone else will face this issue, I  managed to make it work by installing ASP.NET Core 5.0 Runtime (v5.0.6) - Windows Hosting Bundle and URL Rewrite Module. I also added full rights on publish folder to NETWORK and IIS_IUSRS users. I will now close this issue.
