### ISSUE TITLE
Add Quality parameter to BrowserFileExtensions.RequestImageFileAsync

### ISSUE THREAD

**Issue by chrfin** [dotnet/aspnetcore#32769]
### Is your feature request related to a problem? Please describe.
Yes, I'm uploading smartphone camera images to my Blazor Server app to process them with Azure OCR. To reduce the upload size I use `BrowserFileExtensions.RequestImageFileAsync` to shrink them to a usable size and improve upload speed. But I also detected that JPEGs with ~50-60% quality are giving me still VERY good results in OCR, but are MUCH smaller (=> I could use a higher resolution and detect more text at once).

### Describe the solution you'd like
After investigating the possibilities in JavaScript and analyzing how Blazor Server implements the `BrowserFileExtensions.RequestImageFileAsync`-method I detected that it would just need the additional parameter forwareded to the JS sides call to `canvas.toBlob(resolve, format);`.  
My suggestion would be to add the third parameter available there to the chain of methods to be usable from C#.

### Additional context
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@SteveSandersonMS what do you think we should do here? Do you think we should extend this area?

**Comment by chrfin** [comment]
Thanks for the quick reply and looking into this.    
I created a small pull-request showing the required changes, but no other work done yet. If this would be something acceptable as a community contribution, I'm happy to add unit tests and documentation.

**Comment by chrfin** [comment]
Hmm, should have read the documentation to the end. The quality parameter is not supported on Chrome on Android and Safari on iOS, so for the project I'm working on now it's not an option :-(. I'll look into WebP, but there I would need to convert to JPEG on the server, as Azure OCR does not work with it...

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
