### ISSUE TITLE
ERROR  self is not defined

### ISSUE THREAD

**Issue by milladka** [dotnet/aspnetcore#32776]
after build project in nuxt js 

**ERROR  self is not defined**

`at new FetchHttpClient (node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:81:0)

2021-05-17 21:21:23 |   at new DefaultHttpClient (node_modules/@microsoft/signalr/dist/cjs/DefaultHttpClient.js:27:0)

2021-05-17 21:21:23 |   at new HttpConnection (node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js:99:0)

2021-05-17 21:21:23 |   at HubConnectionBuilder.exports.modules.574.HubConnectionBuilder.build 

(node_modules/@microsoft/signalr/dist/cjs/HubConnectionBuilder.js:117:0)`

**version :  @microsoft/signalr": "^5.0.6**

**Comment by BrennanConroy** [comment]
Please provide more info and a repro project.

**Comment by milladka** [comment]
The project works in developer mode without error, but after deploying in one of the package files, it gives this error.
`ERROR self is not defined`
self exists in one of the files and is not defined.
`this file line 81 - node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:81`

my code 
```
import {HubConnectionBuilder} from '@microsoft/signalr';
const connection = new HubConnectionBuilder().withUrl('').build();

    let SELF = this;
    if(!connection.connectionStarted){
      await connection.start().then(async function(){
        await SELF.open('','');
      })
      .catch(err => {
        console.log(err)
      })

    async open(source,final){
      let SELF = this;
      connection.invoke("Open",source,final);
        connection.on("Opened", function () {
          connection.stream("Stream").subscribe({
            close:false,
            next: function(data){ }
          })
        })
        connection.on("Closed", function() {
        });
    },
```

**Comment by BrennanConroy** [comment]
Please provide a repro app that we can run to see the issue.
