### ISSUE TITLE
GetHttpProtocol support for 0.9

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#32775]
```
Exception:
System.ArgumentOutOfRangeException: Version doesn't map to a known HTTP protocol. (Parameter 'version')
at Microsoft.AspNetCore.Http.HttpProtocol.GetHttpProtocol(Version version)
at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpRequestFeature.get_Protocol()
at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.IsEmptyHostAllowed(HttpContext context)
at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

The default builder adds the HostFitleringMiddleware:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/DefaultBuilder/src/WebHost.cs#L245

HTTP 0.9 doesn't set a Host, so it ends up here:
https://github.com/dotnet/aspnetcore/blob/dc5e11abdb05b322f4b74b3afbcfb352fe984b2e/src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs#L191-L202

IIS uses GetHttpProtocol to get the string value:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs#L108-L110

Http.Sys would also be affected:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs#L191

GetHttpProtocol doesn't support 0.9:
https://github.com/dotnet/aspnetcore/blob/fdabaf00a6720d852ec3120b7bbe4b14de2f3ccf/src/Http/Http.Abstractions/src/HttpProtocol.cs#L99-L106

Reported by a large internal partner.

**Comment by blowdart** [comment]
If you do consider supporting it (oh lord, why?) you're going to have a bunch of validation work to do which may end up cross cutting between places;

- Request nature: single-line (method + path for requested document)
- Methods supported: GET only
- Response type: hypertext only
- Connection nature: terminated immediately after the response
- No HTTP headers (cannot transfer other content type files), No status/error codes, No URLs, No versioning

**Comment by Tratcher** [comment]
I don't know that we'd explicitly support it, but we'd like the failure to happen somewhere else 😁.

**Comment by blowdart** [comment]
Oh well that's easier :)

**Comment by Tratcher** [comment]
Note this was a regression between 3.1 and 5.0.

**Comment by BrennanConroy** [comment]
Triage: Add 0.9 to protocol list and make sure it's rejected by host filtering middleware.

**Comment by BrennanConroy** [comment]
> I don't know that we'd explicitly support it, but we'd like the failure to happen somewhere else

To be clear, we're not saying we support 0.9, but we would prefer a 400 failure from another middleware (like host filtering) or something else instead of a 500 like it gets now.

**Comment by FireAlkazar** [comment]
Hi, I would like to take this one

**Comment by Tratcher** [comment]
@FireAlkazar Go ahead.

**Comment by FireAlkazar** [comment]
> Triage: Add 0.9 to HttpProtocol list and verify that it's rejected by the host filtering middleware.

I couldn't find an easy way to verify HTTP\0.9 is rejected in host filtering middleware.
In `HostFilteringMiddlewareTests` `TestServer` is used and it is not calling `HttpProtocol.GetHttpProtocol(...)`

It looks like some options are:
- Call `HttpProtocol.IsHttp09` in `HostFilteringMiddleware` class and if `true` return 400 the same way as for host validation
- Create functional tests for `HttpSys` and `IIS` servers (HttpClient used in functional tests throws if HTTP\0.9 is used, so I will look for some other ways to test it)
- Change `RequestFeature` in `TestServer` so it uses `HttpProtocol.GetHttpProtocol(...)` when property `Protocol` is used
- Some other option

Could you please guide me here?

**Comment by Tratcher** [comment]
HostFilteringMiddleware would refuse the 0.9 request because it doesn't have a Host header. You can either verify that manually with an application, it doesn't need to be automated.
