### ISSUE TITLE
Big integer unwanted rounding

### ISSUE THREAD

**Issue by mexmer** [dotnet/aspnetcore#32773]
### Describe the bug
i'm not sure if problem is inside NewtonSoftJson extension or somewhere else, but for some reason big numbers are getting rounded or rather, if they exceed certain number of places (15), they rounded and replaced by zero

### To Reproduce
I have following code in controller
```csharp
    [ApiController]
    [Route("test")]
    public class Test : Controller
    {
        public async Task<ActionResult> Number()
        {
            var reslt = JObject.FromObject(new { result = "OK", id = 614170000063097008 });
            return Ok(reslt);
        }
   }
```

controller is initialized in startup as
```csharp
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers().AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });
        }
```

expected result is
```json
{
  "result": "OK",
  "id": 614170000063097008
}
```

what i get is
```json
{
  "result": "OK",
  "id": 614170000063097000
}
```

if i use JsonSerialer and output string, it's converted correctly, so i believe issue is not inside newtsonoft json but rather in mvc serialization

### Further technical details
dotnet 5.0.202
visual studio 2019 (16.9.4)

in attachment is sample visual studio webapi
[BigNumberTest.zip](https://github.com/dotnet/aspnetcore/files/6495302/BigNumberTest.zip)

**Comment by pranavkm** [comment]
@mexmer I tried reproducing your issue, but it looks fine to me:

```
> curl "https://localhost:5001/test" -k
{"result":"OK","id":614170000063097008}
```

**Comment by mexmer** [comment]
@pranavkm did you try use it in solution i posted? also with same .NET version?

**Comment by pranavkm** [comment]
Yup. This was using the app that you provided.

**Comment by mexmer** [comment]
ok, did some tests and found following when calling https://localhost:44376/test url (eg. controller endpoint)
using commandline (curl, wget) result is correct
using development client (like postman or insomnia) result is correct
internet explorer 11 doesn't display result but does invoke download, downloaded json is correct
edge (old one, from windows 1610 build) display is correct
Firefox 88.0.1, chrome 90.0.4430.212, edge 89 - all display correct value in raw data, but rounded value when using json.

thanks for directing me to do more though research, i'm closing it, because it's not bug in .NET, it's bug in browser json parser
