### ISSUE TITLE
Support passing more options to WASM AAD auth

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#32782]
Throughout the repo, users have requested having the ability to pass "X" option supported by the MSAL implementation via our Blazor wrapper.

* https://github.com/dotnet/aspnetcore/issues/19925
* https://github.com/dotnet/aspnetcore/issues/25391
* https://github.com/dotnet/aspnetcore/issues/32640

We should consider adding support for all of these items and/or making it easier for users to provide config options to the Blazor wrapper that are supported by the underlying MSAL implementation.

**Comment by javiercn** [comment]
@captainsafia check out https://github.com/dotnet/aspnetcore/issues/27549 which contain more details I think.

**Comment by captainsafia** [comment]
@javiercn Yep. I think we can use this to track the work of supporting `loginHint,` extraQueryParams`, and `prompt`.

**Comment by mkArtakMSFT** [comment]
Related to: https://github.com/dotnet/aspnetcore/issues/25391

**Comment by javiercn** [comment]
Covered by https://github.com/dotnet/aspnetcore/issues/42580 which was added to RC1
