### ISSUE TITLE
Re-enable build of Wasm.Performance.TestApp

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#32788]
This project is currently disabled because it doesn't build consistently with the current SDK (`6.0.100-preview.5.21230.2`). Re-enable it once we update the SDK.

**Comment by wtgodbe** [comment]
Requires undoing changes in `Microsoft.AspNetCore.Components.E2ETests.csproj` and `eng\build.props`

**Comment by wtgodbe** [comment]
Also need to unquarantine 2 tests in https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/PerformanceTest.cs

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/33018
