### ISSUE TITLE
Hot reload skips changes to files that are modified between detect/reload events

### ISSUE THREAD

**Issue by Xeevis** [dotnet/aspnetcore#32792]
### Describe the bug
I have a Snowpack watcher for TailwindCSS JIT that regenerates CSS file in `wwwroot` whenever `.razor` file is changed. However most of the time, change to this CSS file is simply ignored by hot reload, because it happens too fast 😖. More precisely between detect and reload events of the `.razor` file. 

>watch : File changed: E:\BlazorWasm\Pages\Index.razor
_(💀 dead zone, all further file changes are ignored)_
watch : Hot reload of changes succeeded.
_(⏳ waits for next changes ...)_

### Expected behavior
Changes in all watched files should be hot reloaded no matter when they happened.

### To Reproduce
Have two or more files save at roughly the same time while `dotnet watch` with hot reload is running. 

1. With `SDK 6.0.100-preview.4.21255.9` call command `dotnet new blazorwasm -o BlazorPreview4 && cd BlazorPreview4 && dotnet watch`
2. Run several times this Powershell script inside the newly created folder. 

```powershell
$file1 = Get-Item ".\Pages\Index.razor"
$file2 = Get-Item ".\wwwroot\css\app.css"
$file1.LastWriteTime = (Get-Date)
#Start-Sleep -ms 200 #Uncomment to have app.css hot reloaded
$file2.LastWriteTime = (Get-Date)
```

In terminal with `dotnet watch` for the most part you will see only `Index.razor` being reloaded (unless `Start-Sleep` line is uncommented)

### Further technical details
- SDK 6.0.100-preview.4.21255.9
- Vanilla blazorwasm template

**Comment by Xeevis** [comment]
Indeed it seems that changes slip undetected if they happen between the detect and reload events. I've rewrote the original post with much simpler description and repro steps.

I've worked around this issue by artificially delaying file changing script call by couple hundred milliseconds.

**Comment by MisterGoodcat** [comment]
I see a similar or related behavior. I'm running Tailwind CLI as watcher and regenerate the `.css` file in `wwwroot` on `.razor` file changes. In my case hot reload seems to pick up the changes reliably (at least the console says so), but the content delivered to the browser is not current, there seems to be a race condition. I'm using .NET 6.0.100-preview.5.21302.13

One workaround is to explicitly add the file in `wwwroot` in another watch item in the `.csproj` file. This seems to trigger hot reload _twice_ (also confirmed by its output) and then updates the browser correctly.
