### ISSUE TITLE
Configure the Accept Socket

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#32794]
This issue is inspired by @deanward81's post at https://bakedbean.org.uk/posts/2021-05-airdrop-anywhere-part-3/

### Is your feature request related to a problem? Please describe.

We recently exposed the Listen socket via a connection feature. In similar vein, we should probably also expose the Listen Socket via a server feature.

The workaround today is to replace the TransportFactory (code snippet copied from the blog post)

```csharp
// Actual implementation: https://github.com/deanward81/AirDropAnywhere/blob/2021-05-17-receiving-files/src/AirDropAnywhere.Core/HttpTransport/AwdlSocketTransportFactory.cs
internal class AwdlSocketTransportFactory : IConnectionListenerFactory
{
    private readonly IConnectionListenerFactory _connectionListenerFactory;
    private readonly FieldInfo _listenSocketField;
    
    public AwdlSocketTransportFactory(IOptions<SocketTransportOptions> options, ILoggerFactory loggerFactory)
    {
        _connectionListenerFactory = new SocketTransportFactory(options, loggerFactory);
        // HACK: this merry little reflective dance is because of sealed internal classes
        // and no extensibility points, yay :/
        _listenSocketField = typeof(SocketTransportFactory).Assembly
            .GetType("Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener")
            .GetField("_listenSocket", BindingFlags.Instance | BindingFlags.NonPublic);
    }

    public async ValueTask<IConnectionListener> BindAsync(EndPoint endpoint, CancellationToken cancellationToken = default)
    {
        var transport = await _connectionListenerFactory.BindAsync(endpoint, cancellationToken);
        // HACK: fix up the listen socket to support listening on AWDL
        var listenSocket = (Socket?) _listenSocketField.GetValue(transport);
        if (listenSocket != null)
        {
            listenSocket.SetAwdlSocketOption();
        }
        return transport;
    }
}
```

### Describe the solution you'd like

I haven't thought this through yet. 😅 I know an `IStartupFilter` is too early since the server hasn't started yet 

### Additional context

Here's a fun read: https://bakedbean.org.uk/posts/2021-05-airdrop-anywhere-part-3/

**Comment by Tratcher** [comment]
It would need to be some kind of callback on the SocketTransportOptions. Features only come into play after accepting a connection.

**Comment by halter73** [comment]
Why not just use [ListenHandle](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.listenhandle?view=aspnetcore-5.0)?

**Comment by shirhatti** [comment]
Something like this? 

```csharp
webBuilder.ConfigureKestrel(options =>
{
    
    if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        var ipAddress = new IPEndPoint(IPAddress.Loopback, 5000);
        var socket = new Socket(ipAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
        // modify socket options
        options.ListenHandle((ulong)socket.SafeHandle.DangerousGetHandle().ToInt32());
    }

});
```

**Comment by shirhatti** [comment]
Alternatively, how about a `KestrelServerOptions.Listen()` overload that accepts a listen socket?

**Comment by halter73** [comment]
Yeah. A Socket overload to Listen might also be interesting.

One advantage to doing this as a server feature is that it would work with our normal address binding logic, but then we'd probably want to introduce a way to interact with the socket between binding and listening. I'm not sure how we'd do that.

**Comment by davidfowl** [comment]
> It would need to be some kind of callback on the SocketTransportOptions. Features only come into play after accepting a connection.

👍🏾 

```diff
public class SocketTransportOptions
{
+    public Action<EndPoint, Socket> ConfigureAcceptSocket { get; set; }
}
```

**Comment by halter73** [comment]
That is a pretty good way to do that. Nice suggestion @Tratcher 😄

**Comment by deanward81** [comment]
I wanted to play with .NET 6 in my side project (from the blog post) so added both `ConfigureListenSocket` and `ConfigureAcceptSocket` to test my AirDrop shennanigans with. Seems to be working well on my end so I just added a PR for it.
