### ISSUE TITLE
Nullable annotations metadata on non-public members

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#32804]
### Description

In ASP.NET Core we want to use nullable annotations metadata to make decisions about how to call user-defined methods and local-methods/delegates. For more information, see https://github.com/dotnet/aspnetcore/issues/32375

Today that metadata is removed from private members and compiler-generated methods: https://github.com/dotnet/runtime/issues/29723#issuecomment-825911394

> Also we set the flag for the compiler to not emit nullable metadata for non visible outside the assembly APIs; I don't know how interesting it would be for apps to figure out nullability for internal/private APIs of the framework, I guess that is a non-goal for this API but something to add on the docs?

I'm guessing this was done to reduce metadata in assemblies.

Unfortunately, it means that today we can't use that information when calling compiler-generated methods and private methods.

```cs
// Nullable IService means if IService is not resolved from DI
// then the method will be called will a null value instead of throwing an error
app.MapPost("/todos", (IService? service) => {
    // stuff
});
```

**Comment by JamesNK** [comment]
The private and compiler-generated methods in this situation aren't written by us. They're from user's applications and we're reflecting on them.

Would that mean the `nullablePublicOnly` setting must be not set in the ASP.NET Core SDK?

**Comment by jkotas** [comment]
I do not see anyting setting `nullablePublicOnly` in any SDK. Do you have a repro for the problem that you are trying to solve? Maybe you are getting confused by `nullablePublicOnly` being set for ASP.NET Core repo here https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/eng/targets/CSharp.Common.props#L7 ?

**Comment by JamesNK** [comment]
Ahh, I get what is going on now. This is something that we've opted into for assemblies produced by runtime and aspnetcore.

In user app assemblies this flag isn't on so the nullable metadata will always be available.

My confusion was because I was testing this in an aspnetcore test assembly, which has the `nullablePublicOnly` flag applied to it.

I think the only change here will be to turn `nullablePublicOnly` on in just the assemblies that are deployed in the SDK, and leave it off in test assemblies.

**Comment by halter73** [comment]
Closing but the context might be relevant for #32375
