### ISSUE TITLE
Throwing empty NavigationException 

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#32805]
### Describe the bug

In server-side pre-rendering mode, calling `Navigation.NavigateTo` in `OnInitialized` on the home page will throw an empty `NavigationException`. Since there is no useful information in the exception, it is easy to confuse the users.

However, when I switch to server mode, everything is fine.

I think the exception is located here:
https://github.com/dotnet/aspnetcore/blob/50b2470d75b0ff09994a190c68b45e68506e8f1b/src/Components/Server/src/Circuits/RemoteNavigationManager.cs#L75

### To Reproduce

I copy the `RedirectToLogin.razor` file from Blazor documentation.
```
@inject NavigationManager Navigation

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateTo($"/Identity/Account/Login?returnUrl={(new Uri(Navigation.Uri)).LocalPath}");
    }
}

```

And copy the [app-component](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio&WT.mc_id=DT-MVP-5003987#app-component) part of the documentation.
```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" 
                DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (!context.User.Identity.IsAuthenticated)
                    {
                        <RedirectToLogin />
                    }
                    else
                    {
                        <p>
                            You are not authorized to access 
                            this resource.
                        </p>
                    }
                </NotAuthorized>
            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

Finally, I add a `@attribute [Authorize]` in the Index.razor page.

### Exceptions (if any)

`NavigationException` with empty message. 

### Further technical details
- ASP.NET Core version 5.0
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@ElderJames thanks for contacting us.

That's a first chance exception that gets captured by the framework to trigger a redirect when a navigation request occurs while prerendering. You don't need to catch it and you should not observe it unless you wrap your code in a try..catch and capture a very general type like `Exception`

**Comment by ElderJames** [comment]
I know I don't need to care about it because it's all fine. But when using VS for debugging, it gets caught by VS.

**Comment by javiercn** [comment]
@ElderJames You can disable breakpoints on first chance exceptions.
