### ISSUE TITLE
Debug Break Point not hit for .NET 5 Blazor wasm.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#32811]
I am running into problem where Debug Break point is not hit.

Attached is the sample project and screen shots.

![Debug Point is not hit](https://user-images.githubusercontent.com/3267605/118677723-1479d800-b7c2-11eb-97b5-cd88dc68a97c.jpg)

![NET 5 Info](https://user-images.githubusercontent.com/3267605/118677744-19d72280-b7c2-11eb-9b9d-397c7d811cc5.jpg)

**Comment by captainsafia** [comment]
@nssidhu I'm unable to see your project but it looks like you might be trying to hit a breakpoint in the `OnInitialized` method of a component. This isn't supported at the moment but you can find workarounds for it in [the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#breakpoints-in-oninitializedasync-not-hit).

If this isn't the case, please let us know.

**Comment by nssidhu** [comment]
#if DEBUG
        await Task.Delay(10000);
#endif

Worked!!
