### ISSUE TITLE
Unable to make Http client call along with Authorization enabled in Blazor application

### ISSUE THREAD

**Issue by Indhumathy-Loganathan** [dotnet/aspnetcore#32810]
### Description
We are making a WebAPI call through HTTP client and this call is prevented when authorization is enabled in the Blazor application with the following code.

`services.AddAuthorization(options =>
{
      options.FallbackPolicy = options.DefaultPolicy;
});`

**Note:** Http client call(GET or POST) triggers when removing the above code or removing the app.UseAuthorization() from Startup.cs file.

### To Reproduce

Please find the code through which the HTTP client call is made.

`@inject HttpClient Http` 
`@inject NavigationManager uriHelper`
`<button @onclick="clickEvent">Web API call</button>`
`@code{`
    `public static System.Text.Encoding UTF8 { get; }`
    `string text= "Testing";`
    `public async Task clickEvent()`
    `{
        HttpContent httpContent = new StringContent(text, UTF8, "application/json");`
        `var id = await Http.PostAsync(https://localhost:5001/api/Manage/PostCount, httpContent);`
    `}
}`

Post method

`[HttpPost]
        [Route("PostCount")]
        public IActionResult PostCount(string item)
        {
            // perform some operations            
        }`

### Further technical details
- Blazor server side sample .NET 5.0
- Http post method is not triggered with Authorization.
- Is there any way to make an HTTP call along with Authorization enabled in the Blazor server application?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Indhumathy-Loganathan** [comment]
Sorry for the delay. Please find the issue replicated sample from below link.

[AuthorizationSample.zip](https://github.com/dotnet/aspnetcore/files/6554173/AuthorizationSample.zip)

In the sample, the controller post method is not triggered while using the authorization code in Startup.cs file. After commenting, we can able to access the method.
