### ISSUE TITLE
TS client: Custom JSON serializer to support 64bit integers through BigInt

### ISSUE THREAD

**Issue by Niproblema** [dotnet/aspnetcore#32828]
## Summary

I require support for 64bit integers on the TS client side. Would anyone know how to achieve this? I suspect custom json serializer is required in order to parse BigInt from string value with `n` suffix.

## Motivation and goals

64bit integers are useful

## In scope

Setup custom serializer or support BigInt by default.

## Risks / unknowns

No clue

## Help

Please let me know if there is any existing way to achieve this.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by Niproblema** [comment]
@mkArtakMSFT Would you know if this is already possible then? If not, then it has to be implemented, either by the signalr developers or by me.

**Comment by Niproblema** [comment]
@mkArtakMSFT The functionality does not exist in the current implementation, so it has to be added. Please re-open the ticket.

**Comment by BrennanConroy** [comment]
Looks like this issue was misrouted.

> I suspect custom json serializer is required in order to parse BigInt from string value with `n` suffix.

That is very likely true.
Issue https://github.com/dotnet/aspnetcore/issues/5321 is tracking adding support for customizing the javascript json serializer.
Today you can workaround the issue by accepting a string on the client and parsing it in the client callback.
