### ISSUE TITLE
PersonalDataAttribute does not specify AttributeUsage.

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#32833]
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/PersonalDataAttribute.cs. It's currently valid on all targets (including assemblies), but it appears that Properties are the only place that they are actually allowed on.

**Comment by adityamandaleeka** [comment]
Moved to 7 since this is a breaking change.
