### ISSUE TITLE
Empty Blazor project template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#32832]
The default Blazor template has a bunch of stuff in it to help you get started. This means you have a bunch of stuff to delete once you want to build your own app. We should have a way to build an empty Blazor project that has only minimum of what you need. This could potentially be an option on the existing templates.

**Comment by lbugnion** [comment]
As mentioned on Twitter that's what I did on https://github.com/lbugnion/timekeeper which allowed me to progress much faster without getting confused by CSS and JS that I didn't know. An empty template is also important to teach Blazor without letting another framework get in the way, or simply because a designer prefers another CSS framework.

**Comment by sayedihashimi** [comment]
Should it be an option on the existing template or an entirely new template?

**Comment by danroth27** [comment]
> Should it be an option on the existing template or an entirely new template?

Still to be decided. An option would simplify the number of templates we have. We don't just have one Blazor template: there's Blazor Server, Blazor WebAssembly, and .NET MAUI Blazor. How do you feel about the user experience of this being an option in VS? It would be different than what we do for ASP.NET Core, which has a separate empty template...

**Comment by sayedihashimi** [comment]
I was thinking for each hosting option Empty would be a checkbox in VS. Seems like it would be confusing to have 
 - Blazor Server
 - Blazor Server (Empty)
 - Blazor WASM
 - Blazor WASM (Empty)
 - .NET MAUI Blazor
 - .NET MAUI Blazor (Empty)

**Comment by danroth27** [comment]
> I was thinking for each hosting option Empty would be a checkbox in VS. 

Yeah, that's what I was thinking too. Otherwise, the number of templates gets out of hand.

**Comment by sayedihashimi** [comment]
Ok great, thanks.

**Comment by MarvinKlein1508** [comment]
I would do it the other way around. 
- Blazor Server
- Blazor WASM
- .NET MAUI Blazor

When you have created a few demo projects, you will most likely don't need any of the template data anymore.

So keep the three templates and add an option to create a full demo. Doing it this way keeps the templates clean and makes it more convienient for everyone to create a new project.

BTW. I really think the razor class library should be in the blazor category as well. I always need to search for it when I'll need it to create library for blazor components.

**Comment by TanayParikh** [comment]
> > I was thinking for each hosting option Empty would be a checkbox in VS.
> 
> Yeah, that's what I was thinking too. Otherwise, the number of templates gets out of hand.

@danroth27 just confirming this is still the decision we'd like to pursue. Ie.

Adding an option to the `Blazor Server`, `Blazor WASM` & `MAUI Blazor` templates, to make the template content empty. 

I imagine, this would also involve somehow disabling the other template options like authentication (?) Or is that not the case?

**Comment by danroth27** [comment]
> I imagine, this may also involve disabling the other template options like authentication (?) Or is that not the case?

Yup, I'm ok if empty doesn't compose with the other options.

**Comment by Eagle3386** [comment]
Since this is all about open-source & community voices, I'm strongly against disabling authentication.

Why do you want to combine "getting rid of outdated Bootstrap bloatware, etc." with "remove APIs, deps, etc. for authentication or things like that"?

**Comment by mkArtakMSFT** [comment]
Discussed this further in the team and have decided to go with a separate template options:
- Empty Blazor WebAssembly
- Empty Blazor Hosted

We won't have an Empty Blazor MAUI project template for now.
//cc @TanayParikh @danroth27 @MackinnonBuck @cerasamson

**Comment by cerasamson** [comment]
@danroth27 Do you feel strongly about keeping the survey component in the empty app template?

**Comment by danroth27** [comment]
We should remove the survey component from the empty Blazor templates. This template is more for users that are already experienced with Blazor.

**Comment by cerasamson** [comment]
For the empty Blazor WebAssembly template, just confirming that it is standalone and not hosted?

@mkArtakMSFT

**Comment by danroth27** [comment]
> For the empty Blazor WebAssembly template, just confirming that it is standalone and not hosted?

I think we'd want it to support the ASP.NET Core hosted option.
