### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource '<URL>' with computed SHA-256 integrity '1fDu8mg18ucrJQQ8BIWmXj+H0mYOGdVQ/AbAKt9KvLM='. The resource has been blocked

### ISSUE THREAD

**Issue by khalidjavaid** [dotnet/aspnetcore#32840]
after publish blazor webassembly app working fine on local IIS server but throw error when deploy on live server below is picture of errors any one can help me  
[
<img width="960" alt="IntergrityError" src="https://user-images.githubusercontent.com/33339700/118799065-c21ae300-b8b7-11eb-876d-7b501dd0cfec.PNG">
](url)

**Comment by blowdart** [comment]
This is odd, when I use fiddler to grab /_framework/wasm/dotnet3.2.2.0.js from your published site, it's actually an HTML page.

Can you tell us how you deployed the app to your live server?

**Comment by khalidjavaid** [comment]
thanks @blowdart i am using vs 2019 simply i have publish the app and put on server directory .
when i deploy on save publish file with local IIS server on window its was working fine but on live windows hosting it is blocking dll files

**Comment by blowdart** [comment]
Did you ensure the web.config was published? Did you go through the troubleshooting steps? https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0

**Comment by khalidjavaid** [comment]
Yes web.config is published i tried to used different work around but could not get success. get error _bin/System.Data.dll 403 error
Below is link of deploy Site
https://tm.ilaan.com/
you can check error by open in developer mode

**Comment by javiercn** [comment]
@khalidjavaid thanks for contacting us.

We recommend you start by updating to Blazor webassembly 5.0 since its the supported version as a first step
