### ISSUE TITLE
Visual Studio is very slow when editing .razor files in a blazor project

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#32841]
### Describe the bug

Visual Studio becomes very slow and consumes >60-70% CPU and ~2-4GB RAM when running blazor projects (on IIS Express) and editing `.razor` files.

Similar to https://github.com/dotnet/aspnetcore/issues/22276 but happens in more recent versions - tested with 16.10-Preview3 and 16.8.0-Preview4. The original issue mentioned 16.7-Preview4, but the problems are still present.

> **Note;** A workaround (e.g. disabling some options in Visual Studio) will be highly appreciated. I've tried various things, e.g. "Auto build and refresh option" to false, but none of them make any difference.

### To Reproduce
Steps:
1. Run a .NET 5.0 template project for server-side blazor
2. Make changes to `.razor` files and press `Ctrl + F5` again.
3. Repeat step 2 several times.

### Further technical details
- ASP.NET Core version - 5.1
- Include the output of `dotnet --info`
<details>
<summary>dotnet --info</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
```
</details>

- Visual Studio 2019 - tested with 16.10-Preview3 and 16.8.0-Preview4

**Comment by Stamo-Gochev** [comment]
As a follow-up - the same behavior is observed with the latest Visual Studio 16.10.0 Preview 1.0.

**Comment by NTaylorMullen** [comment]
We've done a lottttt of work here in 17.0-Preview2. If you could re-validate the "slowness" in that release (once released) and report back that'd be appreciated. Closing this for now because there's nothing known

**Comment by Stamo-Gochev** [comment]
@NTaylorMullen OK, I will test the improvements once I am able to update to the new version and share the outcome.
