### ISSUE TITLE
Errors property is empty when deserializing ValidationProblemDetails using STJ 

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/aspnetcore#32843]
### Description

I've an ASP.NET Core API which returns a `ValidationProblemDetails` _(Status 400)_ when receiving models with validation errors (Default ASP.NET behavior).

When I try to deserialize the server response on the client using this code:
```c#
var rawJson = await response.Content.ReadAsStringAsync();
var validationProblemDetails = JsonSerializer.Deserialize<ValidationProblemDetails>( rawJson );
```
The `Errors` proeprty of the deseralized `ValidationProblemDetails` is always empty, but the server response contains errors. 

Response from the Server:
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-84075aa65ec81f409bc74a3af930ea5c-f846f3a15024794e-00",
    "errors": {
        "Name": ["The Name field is required."]
    }
}
```

![Capture](https://user-images.githubusercontent.com/7510324/118802907-018b0480-b8a3-11eb-8ff3-524cc48608a0.PNG)

My client is a standard .NET core console app using the `Microsoft.NET.Sdk` SDK.
To use the `ValidationProblemDetails` class in my client I've added a reference to `Microsoft.AspNetCore.Mvc.Core`:
```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
```

If I remove the reference to `Microsoft.AspNetCore.Mvc.Core` and instead change the SDK to `Microsoft.NET.Sdk.Web`, the deserialization works as expected (`Errors` property contains 1 validation error message). 

### Configuration

* Which version of .NET is the code running on: **.NET 5**
* What OS and version, and what distro if applicable? **Win10 20H2 Pro**
* What is the architecture (x64, x86, ARM, ARM64)? **x64**
* Do you know whether it is specific to that configuration? **I don't know... but I guess it is not**

### Regression?

I only tested this on .NET 5.

### Other information

You can find a repro of this issue here: https://github.com/DaveSenn/Repor_ValidationDetails
Just run the server and the client project.

### Expected Result
I would expect the deserialization to work properly when using the class from the latest version of `Microsoft.AspNetCore.Mvc.Core`.

**Comment by pranavkm** [comment]
The 2.2 version of ValidationProblemDetails (which is what you're referencing in your client) is attributed for deserialization using Newtonsoft.Json, not System.Text.Json. You would have to copy the type in - https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ValidationProblemDetails.cs (and possibly the converter) for it to be correctly deserialized in your app.

Note that 2.2 packages have been out of support for about 2 years now, so I wouldn't recommend using it in your projects.

**Comment by DaveSenn** [comment]
@pranavkm Thanks for your answer. That makes sens.

2.2 is the latest version of this package on NuGet https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core/.
Is there another NuGet package which I can refrence to gain access to this type or do I need to "create/copy" my own class?

**Comment by pranavkm** [comment]
@DaveSenn your options would be to either copy the code or reference the ASP.NET Core framework in your class library - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#use-the-aspnet-core-shared-framework
