### ISSUE TITLE
dev-certs accepts only localhost

### ISSUE THREAD

**Issue by latala43** [dotnet/aspnetcore#32873]
Could you please check my question in StackOverflow [here](https://stackoverflow.com/questions/67607187/httpclient-https-call-to-docker-container). I have created a very simple repository in GitHub [here](https://github.com/latala43/TestYarpMaster/blob/master/TestYarpMaster/Controllers/WMController.cs). I want to register the San I have created using Microsoft Documentation [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide#with-powershell) but I always get **PartialChain** Issue when calling a container action from another container hosted in Docker Compose.

The error is:
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
...
```

I tried several ways to register crt, pem, cer, ... and other staff and modify the hosts here and there with no luck. It looks like dev-certs accepts only ```localhost``` and not multiple hostnames. **How can I make this call without bypassing the certificate validation or handling them by code in Startup?** How to create and register the certificate in wsl? I want to continue my development in Windows in Linux!!!

**Comment by blowdart** [comment]
This is by design. The dev tools are deliberately limited to locally run applications. Once you start wanting to trust between machines you need to look at the documentation for your hosting environment and make your security decisions from that knowledge.

A quick summary would be you either choose to trust the self-signed certificate by importing it into your local user trusted certificate store, or if you need specific host names, you should look at using openssl, generating a root CA, and trusting that root CA, then issuing individual certificates. https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/ is a good starting point.

**Comment by javiercn** [comment]
For trusting the certificate on Linux (WSL) there are instructions [here](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-on-linux). If you need to do dotnet-to-dotnet communications you need to have an openssl version equal or higher than 1.1.1h

**Comment by latala43** [comment]
> For trusting the certificate on Linux (WSL) there are instructions [here](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-on-linux). If you need to do dotnet-to-dotnet communications you need to have an openssl version equal or higher than 1.1.1h

But this [instructions ](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-on-linux) here are talking about localhost and not with DnsNames tag. Actually the first MicroService is working fine with the pfx one. It looks like that ```ASPNETCORE_Kestrel__Certificates__Default__Path``` is working with the first hosted service only (something like ApiGateways only). Any additional services in docker-compose does not use ```ASPNETCORE_Kestrel__Certificates__Default__Path```!!!

**Comment by javiercn** [comment]
@latala43 I only pointed out the docs for trust on Linux just in case.

As @blowdart mentioned `dotnet dev-certs` is for localhost only.
