### ISSUE TITLE
Missing Dispose in AuthenticatorTokenProvider

### ISSUE THREAD

**Issue by dIeGoLi** [dotnet/aspnetcore#32871]
### Describe the bug
The [AuthenticatorTokenProvider](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs) should dispose the HMACSHA1 instance created on line 57.

**Comment by blowdart** [comment]
Sure, for correctness, but that class doesn't hang onto any unmanaged resources, so it's not that urgent. If you would like to submit a PR for it, we'd accept it :)

**Comment by dIeGoLi** [comment]
hehe :) i will do that!

**Comment by HaoK** [comment]
Thanks for fixing this @dIeGoLi
