### ISSUE TITLE
Add link to identity documentation in the Blazor WASM template 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/aspnetcore#32883]
Current error page in the Blazor Identity WASM template when the user clicks on login leaves the user uniformed.  Could we provide them with a link to some helpful docs?
![image](https://user-images.githubusercontent.com/2546640/119046068-42117d80-b98a-11eb-9b4c-6a970a4880f2.png)

**Comment by mkArtakMSFT** [comment]
@danroth27  please let us know if you want to have something like this.

**Comment by danroth27** [comment]
@javiercn Do we know why the login fails in this case? Shouldn't it "just work"?

**Comment by javiercn** [comment]
@danroth27 not sure what you mean.

That looks like a configuration issue on the server project (it's serving HTML instead of JSON)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
