### ISSUE TITLE
[5.0.2] SystemOutOfMemoryException in packages after upgrade to .NET 5

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#32884]
### Describe the bug
Few days ago I upgraded my custom e-commerce solution based on blazor to .NET 5.0.2 (server has 5.0.3). In few hours memory usage was about 500MB-600MB RAM. If I try to export some data and save to excel (custom package - NPOI) I get SystemOutOfMemoryException. However site is not crashing and keep running, basic request like search/visiting product works just fine.

In following hours I noticed there is another issue - sending emails.. same exception. Thrown by custom package.

I wonder if I missed some setting in upgrade process? Last stable version 3.1.8 had no issues running at 600MB or more. 

Server has about 10 GB free memory

### Upgrade ###
App.razor
```
        <Router AppAssembly="@typeof(Program).Assembly">
to
        <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
```

```
    <TargetFramework>netcoreapp3.1</TargetFramework>
to
    <TargetFramework>net5.0</TargetFramework>

+ package upgrades to 5.0.2 / target Portable AnyCpu
```

### Exceptions (if any)
```
[ERR] An unhandled exception has occurred while executing the request.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.ReplaceHelper(Int32 oldValueLength, String newValue, ReadOnlySpan`1 indices)
   at System.String.Replace(String oldValue, String newValue)
   at NPOI.OpenXml4Net.Util.XmlHelper.EncodeXml(String xml)
   at NPOI.OpenXmlFormats.Spreadsheet.CT_Rst.get_XmlText()
   at NPOI.XSSF.Model.SharedStringsTable.GetKey(CT_Rst st)
   at NPOI.XSSF.Model.SharedStringsTable.AddEntry(CT_Rst st)
   at NPOI.XSSF.UserModel.XSSFCell.SetCellValue(IRichTextString str)
   at NPOI.XSSF.UserModel.XSSFCell.SetCellValue(String str)
   at Ecom.Controllers.Api.ExportApiController.ExportProducts(ExportViewModel model, ISheet excelSheet) in F:\ASP.NET Core\Ecom\src\Controllers\Api\ExportApiController.cs:line 301
   at Ecom.Controllers.Api.ExportApiController.ProcessExport(String fileName, String sheetName, ExportViewModel model, ExportDelegate exportDelegate) in F:\ASP.NET Core\Ecom\src\Controllers\Api\ExportApiController.cs:line 90
   at Ecom.Controllers.Api.ExportApiController.GetExportAsync(ExportViewModel model) in F:\ASP.NET Core\Ecom\src\Controllers\Api\ExportApiController.cs:line 53

```

### Further technical details
- ASP.NET Core version; 5.0.2
- Include the output of `dotnet --info`; 5.0.3 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version; VS 2019.8

Running on IIS 10 Windows Server 2016 x64. AppPool settings: LoadUserProfile: true (no poll memory limit)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
At least from the exception stack trace this doesn't seem to be coming from the framework, rather than your code.
If you believe this is indeed an issue in the framework, we would need to have a minimal repro project (hosted in GitHub) to be able to investigate further.

**Comment by glararan** [comment]
@mkArtakMSFT Yea stack trace dont call it back to framework. I'll try to gather more info. Maybe there will be leads back to .NET 5. However what is strange is app is not crashing. Why is that? Is there build-in anti-crash protection? Cause I've looked into package source code and I cant find anything about throwing SystemOutOfMemoryException.

At the moment I dont have min repro as I am investigating whats going on exactly. I can only tell I changed following lines vs .NET 3.1.8.

**Comment by glararan** [comment]
Hi,

So I finally managed to deploy debug version and today I am right now encountering with same exception.

I have to admit some days there are none problems. Memory consumption is right now 309 MB. App is still not crashing. I can browse pages.

Last few days it used average 500 MB so I am really desperated where to look for.

This is my memory object diff (decrease by 944)
![image](https://user-images.githubusercontent.com/281441/121406350-54b21d80-c95e-11eb-9dc5-dce370a75a29.png)


Heap is increased by 2 MB
![image](https://user-images.githubusercontent.com/281441/121406409-6693c080-c95e-11eb-8c70-e03dbadef536.png)

Snapshots were taken right before OOM exception and right after. However this is snapshot from production, that means about 5+- active users.

Since this above I was able to reproduce during email sending its not really like I told in post above exactly dotnet issue as it may seem.

I was able to track earlier this day another OOM exceptions. I am still finding which action I should do to make it throw.

> 2021-06-09 08:40:34.948 +02:00 [ERR] An exception occurred while iterating over the results of a query for context type '...Data.DatabaseContext'.
> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.Threading.Thread.StartInternal()
>    at System.Threading.Thread.Start()
>    at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
>    at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
> --- End of stack trace from previous location ---
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.Threading.Thread.StartInternal()
>    at System.Threading.Thread.Start()
>    at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
>    at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
> --- End of stack trace from previous location ---
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

As you can see its still not asp.net core issue, I wonder if I should move this issue to dotnet repo? This issue went on like I told after upgrading to .NET 5 with none hard code change (except blazor migration needs).
