### ISSUE TITLE
Calling javascript from blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32905]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Calling-javascript-from-blazor/1424194)._

---
First off, I have to apologize for creating this issue here. I was trying to reopen issue 16218 in GitHub (closed by Steve Sanderson), while trying to implement a suggestion by BrainSlugs83. But for some reason the "new" button was not showing after I clicked on "Issue". I did this under my git Id PSCRIMS.

I need to call a google GTM script from my BlazorServer site. I understand that by architecture I can't have a script call in the HTML portion of Index.Razor.  I had already called in the same project a Javascript tracking function in the override of OnInitialized in my index.razor and that worked OK, but when I tried the same solution on the Google GTM it was not been fired by the website. 

The solution proposed on the closed issue was to create a shared component which was temporarily suppressing error BL999. In the solution he mentions that then we could add the script in the HTML. What I need to know if how to call the component from my OnInitialized, I am already navigating to Base

JS. InvokeVoidAsync("pixel");  // this worked
        //JS. InvokeVoidAsync("GTM");  // this did not work
        ////////////////////////////////////// ?? NavManager.NavigateTo(GTM);
        var uri = NavManager.ToAbsoluteUri(NavManager.Uri);
        //     userData.ParseUri(uri);
        base. OnInitialized();

Thanks in advance.

---
#### admin on 5/14/2021, 00:10 PM: 

(private comment, text removed)
#### Feedback Bot on 5/17/2021, 01:22 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
Thanks for contacting us.

Our recommendation is that you leverage JS modules instead of adding script tags within Blazor components. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-isolation-in-javascript-modules) for details
