### ISSUE TITLE
SignalR Client not recover the connection in Full Framework

### ISSUE THREAD

**Issue by LuisM000** [dotnet/aspnetcore#32900]
### Describe the bug
Microsoft.AspNetCore.SignalR.Client stops working after a few moments without connection in WPF Full Framework.

### To Reproduce
We have a WPF Full Framework 4.7.2 application with Microsoft.AspNetCore.SignalR.Client package (5.0.6). When we disconnect the internet (for example, by deactivating the wifi of the pc), we wait a few moments and reconnect the internet, at no time SignalR tries to reconnect and, after recovering the internet, it stops working "forever", if for example at that moment we do a StopAsync, the call never ends.
On the other hand, if we do the same with WPF net core 3.1, this does not happen and everything works correctly (it reconnects).

Repro:
Video link: https://drive.google.com/file/d/1y3XGfThFMuz8n0EXApYBlLjtEGNb9b6f/view?usp=sharing
Example Full Framework: https://drive.google.com/file/d/1E6qx4tW0mw4jDO8M5H3xog71fJ_j98Oa/view?usp=sharing
Example net core: https://drive.google.com/file/d/1KWqa3xYY9oBZ8r3f1398g4y90WYs9cln/view?usp=sharing

### Exceptions (if any)
In WPF Full Framework 4.7.2, after a few moments without an internet connection, a trace appears that may have some clue:
`Exception thrown: 'System.Net.Http.HttpRequestException' in Microsoft.AspNetCore.Http.Connections.Client.dll`

### Further technical details
- WPF Full Framework 4.7.2 
- Microsoft.AspNetCore.SignalR.Client 5.0.6
- Microsoft Visual Studio Professional 2019 16.9.5

**Comment by BrennanConroy** [comment]
I assume the code is same between the two apps?

Can you share Trace logs from the failing app? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0#net-client-logging

**Comment by LuisM000** [comment]
> I assume the code is same between the two apps?

Yes, the same code.

Trace logs:
[Trace.txt](https://github.com/dotnet/aspnetcore/files/6526107/Trace.txt)

The last error occurs when I have disabled the internet from the pc. After that if I make the call to `connection.StopAsync()` it doesn't leave any traces.

Thanks!

**Comment by BrennanConroy** [comment]
Does the .NET Core 3.1 client use WebSockets as the transport? I'm wondering if there is an issue specific to SSE.

Also, for the Full Framework app, could you try using LongPolling as the transport and see if the issue still exists? (you might need to wait a little longer for it to disconnect with LongPolling)

**Comment by LuisM000** [comment]
> Does the .NET Core 3.1 client use WebSockets as the transport? I'm wondering if there is an issue specific to SSE.

No, .NET Core 3.1 uses ServerSentEvents.


> Also, for the Full Framework app, could you try using LongPolling as the transport and see if the issue still exists? (you might need to wait a little longer for it to disconnect with LongPolling)

It seems that forcing LongPolling on the Full Framework application (I was using ServerSentEvents) does not occur the error, that is, it has the same behavior as in the .NET Core 3.1 app.

Thanks!

**Comment by BrennanConroy** [comment]
That's interesting, and good data points, thanks!

So SSE only, only on Full Framework. We'll take a look and see if we can repro the issue.

**Comment by BrennanConroy** [comment]
I believe this is a case of the issue described at https://github.com/dotnet/runtime/issues/38782
The fix is to include a binding redirect for System.Buffers so it loads 4.0.3.0 of the dll.

**Comment by BrennanConroy** [comment]
I don't think there is anything for SignalR to do here. The underlying issue is linked above
