### ISSUE TITLE
[Blazor] [WASM] Unable to obtain access token once refresh token expires (11-24 hrs)

### ISSUE THREAD

**Issue by tonyruco** [dotnet/aspnetcore#32923]
### Describe the bug
[Blazor] [WASM] Unable to obtain access token once refresh token expires which has been ~ 11-12 hrs in Edge and 24 consistently in Chrome browser.

### To Reproduce

Repro steps
1) Configure B2C tenant & Create new app, per MS document guidance: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0
dotnet new blazorwasm -au IndividualB2C --aad-b2c-instance "{AAD B2C INSTANCE}" --client-id "{CLIENT ID}" --domain "{TENANT DOMAIN}" -o {APP NAME} -ssp "{SIGN UP OR SIGN IN POLICY}"

	Make sure to add an Api scope

2) Login

3) Wait for Refresh token to expire (24 hrs in Chrome)

4) Click on tab, DO NOT REFRESH

### Exceptions (if any)
AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1621001950, Grant issued time: 1620915137, Grant expiration time: 1620959635

### Further technical details
- .NET 5
- output of `dotnet --info
              .NET SDK (reflecting any global.json):
               Version:   5.0.202
               Commit:    db7cc87d51
              
              Runtime Environment:
               OS Name:     Windows
               OS Version:  10.0.18363
               OS Platform: Windows
               RID:         win10-x64
               Base Path:   C:\Program Files\dotnet\sdk\5.0.202\
              
              Host (useful for support):
                Version: 5.0.5
                Commit:  2f740adc14
              
              .NET SDKs installed:
                5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
                5.0.102 [C:\Program Files\dotnet\sdk]
                5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]
                5.0.202 [C:\Program Files\dotnet\sdk]
              
              .NET runtimes installed:
                Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
                Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
                Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
                Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
                Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
                Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
                Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
                Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
                Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Enterprise 2019 - Version 16.9.4

**Comment by javiercn** [comment]
@tonyruco thanks for contacting us.

It is expected that if your refresh token has expired you are not able to provision new tokens. I'm not sure if we are missing something here in terms of your explanation, is the user not able to log in afterwards and provision a new access_token + refresh_token pair?

**Comment by tonyruco** [comment]
Hello Javier, thank for the quick response. As I understand, MSAL should be redirecting to the login page so the new refresh token and access token pair obtained, but it's not. Just producing this exception.

**Comment by javiercn** [comment]
@tonyruco I don't think MSAL must be doing that.

In the case of Blazor, if there's an issue with the credentials you'll get an exception and you are responsible for re-authenticating the user by redirecting to /authentication/login in the same way as if the user is not authenticated.

> Microsoft.Authentication.WebAssembly.Msal

There's no relationship between the version in Microsoft.Authentication.WebAssembly.Msal and the version in msal-browser. We bundle msal-browser within our library and we are currently using 2.8.0

It looks like the behavior you are expecting is not inline with the behavior we are implementing. I wouldn't expect msal-browser to automatically redirect upon an expired refresh token. That would be very jarring for the app which would not get a chance to save any state before the redirect.

**Comment by tonyruco** [comment]
Sorry when I mentioned MSAL i was referring to 'Microsoft.Authentication.WebAssembly.Msal', specifically /Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js, not MSAL browser. I already do redirect to login on a failure to obtain a accessToken but need to see why this isnt being handled by that.
My initial assumption was that 'Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js' is responsible to handling cases where the refresh token was expired. Can you provide or point me to a resource, with information on what  'Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js' is responsible for vs our Blazor SPA application? 

Thank you very much.

**Comment by javiercn** [comment]
> Can you provide or point me to a resource, with information on what 'Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js' is responsible for vs our Blazor SPA application?

We don't have specific docs about internal implementation details like that. However, to bring a bit more clarity, C# controls the general auth-flow in the app and `AuthenticationService.js` only implements specific details for sign-in, sign-out, get a token. The refresh token is handled by msal-browser (used within AuthenticationService.js). 

When C# requests an access token and the credentials have expired. That should manifest in an exception that bubbles up to the C# layer and that can be caught by the application, which in turn can initiate the process to re-authenticate the user.
