### ISSUE TITLE
Consider changing the log level of JwtBearer TokenValidationSucceeded to Debug

### ISSUE THREAD

**Issue by aelij** [dotnet/aspnetcore#32947]
### Is your feature request related to a problem? Please describe.
`JwtBearer`'s `TokenValidationSucceeded` log is currently defined with `Information` log level:

https://github.com/dotnet/aspnetcore/blob/b1412cfc0de98ca7bbdf636c683a62621fc70569/src/Security/Authentication/JwtBearer/src/LoggingExtensions.cs#L20-L23

We would like to turn on this logger but it produces a huge amount of logs.

### Describe the solution you'd like
Change the log level to `Debug`, same as the `AuthenticationSchemeAuthenticated` log.

**Comment by blowdart** [comment]
@aelij  Would you like to submit a PR for this, or shall we do it?

**Comment by aelij** [comment]
@blowdart Sure, I can do it. Thanks
