### ISSUE TITLE
.NET 6 Blazor WebAssembly IIS hosting project template fails to run at first start

### ISSUE THREAD

**Issue by donhuvy** [dotnet/aspnetcore#32942]
.NET 6 Blazor WebAssembly IIS hosting project template fails to run at first start

```
dotnet --version
6.0.100-preview.3.21202.5
```

Visual Studio version
```
Microsoft Visual Studio Community 2019 Preview - Version 16.10.0 Preview 4.0
```
Steps to reproduce

![image](https://user-images.githubusercontent.com/1328316/119248007-563ac200-bbb8-11eb-98ab-2323a690ac40.png)

![image](https://user-images.githubusercontent.com/1328316/119248020-6e124600-bbb8-11eb-8307-bc8a1acdb54d.png)

![image](https://user-images.githubusercontent.com/1328316/119248033-85513380-bbb8-11eb-8eb5-9878ad0c9fc4.png)

![image](https://user-images.githubusercontent.com/1328316/119248050-a6b21f80-bbb8-11eb-97df-0112b77b1a41.png)

![image](https://user-images.githubusercontent.com/1328316/119248066-c77a7500-bbb8-11eb-97cd-01f2714e9db7.png)

![image](https://user-images.githubusercontent.com/1328316/119248073-df51f900-bbb8-11eb-835d-788a63cfd3b4.png)

![image](https://user-images.githubusercontent.com/1328316/119248084-f0026f00-bbb8-11eb-8509-46e13defd2a0.png)

![image](https://user-images.githubusercontent.com/1328316/119248093-07415c80-bbb9-11eb-83b9-c49f8ea16e8a.png)

![image](https://user-images.githubusercontent.com/1328316/119248102-20e2a400-bbb9-11eb-9736-2060a8c27794.png)

![image](https://user-images.githubusercontent.com/1328316/119248113-35bf3780-bbb9-11eb-9695-97236d347d65.png)

![image](https://user-images.githubusercontent.com/1328316/119248123-4a033480-bbb9-11eb-939a-aa1380fc9e22.png)

Error

```
HTTP Error 500.33 - ANCM Request Handler Load Failure
Common solutions to this issue:
Make sure Microsoft.AspNetCore.App is referenced by your application.
Specific error detected by ANCM:
Could not find the assembly 'aspnetcorev2_inprocess.dll' referenced for the in-process application. Please confirm the Microsoft.AspNetCore.Server.IIS or Microsoft.AspNetCore.App is referenced in your application.
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526
```

Source code: 
[blazor01.zip](https://github.com/dotnet/aspnetcore/files/6527527/blazor01.zip)

Then, I add NuGet package `Microsoft.AspNetCore.Server.IIS` and `Microsoft.AspNetCore.App`, but the problem is the same.

https://user-images.githubusercontent.com/1328316/119248389-0ad5e300-bbbb-11eb-9238-8a33e738e6ee.mp4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're aware of this issue and are tracking it as part of https://github.com/dotnet/aspnetcore/issues/32851.
To work-around it for now you can follow the instructions provided [here](https://github.com/dotnet/aspnetcore/issues/32851#issuecomment-844393696)
