### ISSUE TITLE
Produce zip version of IIS support (ANCM)

### ISSUE THREAD

**Issue by richlander** [dotnet/aspnetcore#32955]
A customer asked us for the following:

- Windows Server Core container images
- Include ASP.NET Core
- With IIS enabled

https://github.com/dotnet/dotnet-docker/issues/2814

The customer tried to install the hosting bundle MSI, but failed. I tried it too, and got farther, but it likely doesn't produce what we want.

We want to include ANCM within this Dockerfile, and to rely on the .NET runtime that is in the layer below.

https://github.com/dotnet/dotnet-docker/blob/nightly/src/aspnet/6.0/windowsservercore-ltsc2019/amd64/Dockerfile

If there is an asset already available that you can share with us, that'd be great. If not, can you provide one? The customer wants to enable this scenario for .NET Core 3.1.

In hindsight, it is a missed opportunity that the ASP.NET Core image for Windows Server Core doesn't have IIS hosting pre-enabled.

**Comment by BrennanConroy** [comment]
Do you have the MSI failure?

> I tried it too, and got farther, but it likely doesn't produce what we want.

What issues are you seeing?

And can you share the command used to attempt to install the MSI?

**Comment by richlander** [comment]
I did not have the MSI failure. I used `-q` and that made it work.

The primary issue is that we need an asset (installer or zip) that plays well with our layering.

The only real requirement is "do not update/touch .NET Core runtime assets, which are not installed via MSI".

**Comment by BrennanConroy** [comment]
Looks like you need a few more options when installing
https://github.com/microsoft/iis-docker/blob/master/samples/aspnetcoremodule/Dockerfile#L9-L17

**Comment by richlander** [comment]
Oh? That looks great.

My take away is that set of args will only install and register ANCM. Yes?

**Comment by BrennanConroy** [comment]
Correct, opts out of touching the runtime and shared fx.

**Comment by BrennanConroy** [comment]
Closing as I believe this work can progress now, feel free to reopen if there are more questions.
