### ISSUE TITLE
building aspnetcore

### ISSUE THREAD

**Issue by tschmit** [dotnet/aspnetcore#32954]
### Describe the bug
Error when building because correct version of dotnet sdk can't be found.

Said version is read from [global.json](https://github.com/dotnet/aspnetcore/blob/main/global.json) and is 6.0.100-preview.5.21230.2

But the greater version [downloadable](https://dotnet.microsoft.com/download/dotnet/6.0) is 6.0.100-preview.3.21202.5

### To Reproduce

Just follow the steps in [Build ASP.NET Core from Source](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md)

**Comment by ylabade** [comment]
The procedure for compiling from source is described in the main readme in the section _How to Engage, Contribute, and Give Feedback_.
You have to download and install the [latest daily build](https://github.com/dotnet/aspnetcore/blob/main/docs/DailyBuilds.md) of the .NET Core SDK.

**Comment by tschmit** [comment]
seen
