### ISSUE TITLE
When scaffolding new project with dotnet new, generated source files have different encoding

### ISSUE THREAD

**Issue by Vake93** [dotnet/aspnetcore#32960]
When generating a new empty web project using `dotnet new web` command the `Program.cs` and `Startup.cs` encording is UTF-8.
But if I do `dotnet new console` or `dotnet new classlib` the resulting cs files are with encoding  UTF-8 with BOM. The project files are always generated as UTF-8.

Can the encoding  be unified across the files generated when using the dotnet new command?

I found this because of the analyzers we use always show `Warning SA1412 Store files as UTF-8 with byte order mark` when creating a new empty web project.

**Comment by javiercn** [comment]
We do have some tests for ensuring a specific encoding of JS, JSON, .cshtml, and .razor files [here](https://github.com/dotnet/aspnetcore/blame/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/ProjectTemplates/test/ByteOrderMarkTest.cs)

Not sure what the choices were here nor why. I think its ok if we change them as long as we understand why the current options were selected and what the impact on the change is. One common issue in this space are editors automatically modifying the file on save and generating additional git changes.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The current choice that we've made is intentional. You can get more context about it from #11225
If we hear concerns from the community that this is causing trouble, we may consider doing something in this space. For now closing this issue.
