### ISSUE TITLE
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy

### ISSUE THREAD

**Issue by saithis** [dotnet/aspnetcore#32964]
# Describe the bug
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy.
There is no exception if we deploy the code with Visual Studio (no zip deploy).

### To Reproduce
1. Using version '3.0.0' of package 'Microsoft.Extensions.Logging.AzureAppServices'
2. Run this code:
```
        private static readonly LoggerProviderCollection LoggerProvider = new LoggerProviderCollection();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    .UseSerilog(providers: LoggerProvider)
                    .ConfigureLogging(config =>
                    {
                        config.ClearProviders();
                        config.SetMinimumLevel(LogLevel.Trace);
                        config.AddAzureWebAppDiagnostics();
                    })
                    .UseStartup<Startup>();
                });
```
3. Deploy to Azure with Zip Deployment/WEBSITE_RUN_FROM_PACKAGE: 1
4. See error:

> System.IO.FileNotFoundException: Error reading the D:\home\site\diagnostics\ directory.
>    at System.IO.FileSystemWatcher.StartRaisingEvents()
>    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
>    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
>    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
>    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Microsoft.Extensions.Logging.AzureAppServices.SiteConfigurationProvider.GetAzureLoggingConfiguration(IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder, IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder)
>    at Prosoft.Tenant.Api.Program.<>c.<CreateHostBuilder>b__1_2(ILoggingBuilder config) in C:\j\ws\Recruiting\prosoft-recruiting-qa\Prosoft.Tenant.Api\Program.cs:line 66
>    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureServices>b__0(WebHostBuilderContext context, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()

### Expected behavior
It should find and be able to read the D:\home\site\diagnostics\settings.json, as it is definitelly there.

### Additional context
We use AspNetCoreModuleV2 with InProcess hosting and .NET Core 3.0

**Comment by BrennanConroy** [comment]
I've tried to repro the issue and been unsuccessful so far. New Azure App Service, turn on diagnostics, zip deploy app that uses AzureWebAppDiagnostics, see that app is running and logs are streaming through portal.

Is there some specific steps to hit the issue or is it random?

**Comment by asilverstein** [comment]
Probably was already stated, but it only occurred for me with net5 projects

**Comment by adityamandaleeka** [comment]
Can anyone confirm whether this issue is still occurring? There was a recent App Service update that fixed a file system issue that this sounds very similar to.

**Comment by adityamandaleeka** [comment]
No response on this issue, so I'll close it. If anyone hits it we can reopen.
