### ISSUE TITLE
Web components API to dynamic elements

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#32967]
Look into:

 * API for registering a custom element that will render a Blazor component dynamically
 * Making sure nothing weird happens with shadow roots
 * Make sure that web component APIs interact well with it (slotted elements - should they map to `RenderFragment`, or does it somehow magically get rendered as a child because of the web component intrinsics?)
 * What do you do when the custom element already has some content? Will you pass it as `ChildContent`?
 * Checking it works well when embedded in a React/Angular/Vue app

Main thing is to check we don't have to ship anything in-box to make this work sensibly.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT I don't see this happening in preview 6 so bumping forwards to 7.

**Comment by SteveSandersonMS** [comment]
This is now done.

 * The core framework APIs for adding, removing, and updating root elements from JavaScript are implemented in this repo
 * The custom elements APIs are available at https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements as a package called `Microsoft.AspNetCore.Components.CustomElements`. See the README there for details.

During the 6.0 period (Nov 2021-Nov 2022) we will encourage developers to use the `Microsoft.AspNetCore.Components.CustomElements` package and provide feedback. This may or may not become a built-in part of Blazor in 7.0. However, the main thing to note is that the total amount of code in the CustomElements package is extremely small - only about 100 lines of code total, since it's just a small wrapper on top of the built-in core APIs mentioned above. Developers who are keen on custom elements may wish to implement their own variant of those 100 lines since there are various arbitrary design choices and each team may prefer different approaches.

**Comment by RChrisCoble** [comment]
Hello @SteveSandersonMS, this implementation doesn't appear to require .Net 6 or the the ASP.Net bits delivering with .Net 6 in November.  Is that correct?  In other words, this appears to be usable with the current/released version of Blazor?

**Comment by SteveSandersonMS** [comment]
No, sorry, this is a .NET 6 feature involving runtime changes in .NET 6. It's not usable with .NET 5 applications.

**Comment by RChrisCoble** [comment]
Ok, no worries.  I couldn't find that information specified in the linked BlazorCustomElements Readme.md file.

**Comment by RChrisCoble** [comment]
@SteveSandersonMS, one final question here, with this feature tagged as RC1, I assume we can't leverage/try BlazorCustomElements until the .Net 6 RC1 build?  Thanks.

**Comment by SteveSandersonMS** [comment]
The official release of RC1 hasn't happened yet, but if you wish, you can download a non-final build of .NET Core 6.0 RC1 from https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries and try out the features in it. We don't yet have docs about using the RC1 features so you'd need to infer it from the PR history or E2E test sources.
