### ISSUE TITLE
What is magic number 4

### ISSUE THREAD

**Issue by MSIH** [dotnet/aspnetcore#32966]
https://github.com/dotnet/aspnetcore/blob/596970a89b418c175e3356bf1247c9bbe5b76211/src/Components/Web/src/Virtualization/Virtualize.cs#L215

This line of code passes the number 4 to a function. Please document what different number do.

**Comment by chrissainty** [comment]
@MSIH This is documented [here](https://docs.microsoft.com/en-gb/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-5.0#sequence-numbers-relate-to-code-line-numbers-and-not-execution-order). They are sequence numbers and the number itself doesn’t hold any particular value but relates to the order of lines of code.
