### ISSUE TITLE
ASP.NET template disables EF Core SQL logging by default

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#32977]
### Include your code

Create an ASP.NET Core app with individual user accounts so EF Core is used

```
dotnet new webapp -au Individual -uld -o RPauth
cd RPauth
dotnet ef database update
dotnet run

```

Browse to https://localhost:5001/ and create a new account. Click on the link to confirm the account. Note that no SQL is logged.

Add the following to *appsettings.json*:
```,"Microsoft.EntityFrameworkCore.Database.Command": "Information"```

No need to stop/restart as *appsettings.json* is reloaded. Navigate to https://localhost:5001/Identity/Account/Manage can select some of the tabs on the left. SQL output is displayed.

Comment out the following and  SQL output stops:

```// ,"Microsoft.EntityFrameworkCore.Database.Command": "Information"```

### Include provider and version information

Using all defaults with .NET 5 or .NET 6

Related: dotnet/efcore#3240

**Comment by javiercn** [comment]
Thanks for the additional info.

I've tagged this as MVC, although its for the team to handle.

@ajcvickers what namespace are the queries logged in from. I imagine we need to add an additional entry to the appsettings.json to mark those logs as info and have the queries show up.

**Comment by Rick-Anderson** [comment]
> I imagine we need to add an additional entry to the appsettings.json to mark those logs as info and have the queries show up.

See [SQL Logging of Entity Framework Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio#sql-logging-of-entity-framework-core)
`   ,"Microsoft.EntityFrameworkCore.Database.Command": "Information"`

**Comment by mkArtakMSFT** [comment]
@davidfowl , @DamianEdwards looks like you had changed this area in the past so what do you want to do regarding this?

**Comment by davidfowl** [comment]
Pretty sure this is by design. We don't want logs showing up as information by default. It's too much noise.

**Comment by ajcvickers** [comment]
It's by-design that EF Core shows SQL by default. Not doing so leads to thinks like the stackoverflow question that triggered this. We agreed with ASP.NET that SQL would be shown by default if we logged at Info level.

**Comment by Rick-Anderson** [comment]
> Pretty sure this is by design. We don't want logs showing up as information by default. It's too much noise.

So add  ` //  ,"Microsoft.EntityFrameworkCore.Database.Command": "Information"`
to *appSettings.development.json*

See [this SO thread](https://stackoverflow.com/questions/45893732/how-do-you-show-underlying-sql-query-in-ef-core), 50K + views, all the ridiculous answers to get SQL logging. Luckily I was able to contact the owner and have him change my answer to the correct answer.

See [SQL Logging of Entity Framework Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio#sql-logging-of-entity-framework-core) - Probably documenting it is enough. That just went live today and it's an include file so it's all over the ASP.NET Core EF tutorials.

**Comment by Rick-Anderson** [comment]
I have extensive anecdotes that customers want to see SQL logging in development, that's fundamentally different than seeing framework logging. The best fix might be enabling it in *appSettings.Development.json* and then documenting how to turn it off.

What would be really cool and beneficial is adding several useful logging flags `// commented out` in *appSettings.Development.json* with a link to a troubleshooting document describing them. I've seen lots of issues opened where the response is, "Enable this flag to debug".

**Comment by davidfowl** [comment]
We don't show anything info level by default, it doesn't have anything to do with EF, we literally don't show per request logs. Maybe this is something we can change in development but not in production? Logging per request is extremely inefficient and we opt for showing the user's logs by default  but not the framework logs.

**Comment by Rick-Anderson** [comment]
>Maybe this is something we can change in development but not in production? 

My original suggestion, add  `  ,"Microsoft.EntityFrameworkCore.Database.Command": "Information"`
to `appSettings.`***Development***`.json`

**Comment by ajcvickers** [comment]
My preference would be to put all of EF Core at Info, at least for development. That is, "Microsoft.EntityFrameworkCore"

**Comment by davidfowl** [comment]
I'm not sure we want that much noise. This is something that we should discuss 😄

**Comment by DamianEdwards** [comment]
In 2.x, the templates are set so the logging level for Microsoft prefixed categories is **Information** in _appsettings.Development.json_:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

In 3.x, this was changed to reduce the amount of logging emitted by default, to be **Warning**, with a specific setting added to ensure _Microsoft.Hosting.Lifetime_ messages would still be emitted (so it was easy to see that the app had started successfully in the console during development):
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

This would have resulted in EF logs that were previously emitted by 2.x apps to not be emitted in new 3.x apps (and beyond).

Personally, I agree it's very useful to have some EF logs present in development by default and support adding a specific setting to the templates to emit EF **Information** logs. My initial thought is I'd only expect a single log per query executed, which would include the SQL command text. Thus we'd need to look at what EF emits at the **Information** level today ensure the settings file entry is specific enough to result in the desired amount of logging (and potentially update EF if that's not possible right now).

**Comment by ajcvickers** [comment]
EF Core logs the following at `Information` level:

* All providers:
  * `Entity Framework Core {version} initialized '{contextType}' using provider '{provider}' with options: {options}`
  * `A transient exception occurred during execution. The operation will be retried after {delay}ms.{newline}{error}`
* Cosmos:
  * `Reading resource '{resourceId}' item from container '{containerId}' in partition '{partitionKey}'.`
  * `Executing SQL query for container '{containerId}' in partition '{partitionKey}' [Parameters=[{parameters}]]{newLine}{commandText}`
* Relational:
  * `Executed DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}`
  * `Applying migration '{migration}'.` (Migrations only)
  * `No migrations were applied. The database is already up to date.` (Migrations only)
  * `Reverting migration '{migration}'.` (Migrations only)
  * `The index named '{indexName}' on the entity type '{entityType}' specifies properties {indexProperties}, but none of these properties are mapped to a column in any table. This index will not be created in the database.` (Will follow up on why this is at Info level. /cc @AndriySvyryd)
  * `The unnamed index on the entity type '{entityType}' specifies properties {indexProperties}, but none of these properties are mapped to a column in any table. This index will not be created in the database.` (Likewise)

**Comment by DamianEdwards** [comment]
Thanks @ajcvickers. From that list it seems that for a typical web app then (e.g. the Identity pages) there'd be 2 log messages emitted per request, one for the `DbContext` initialization and another for the query execution. Are they logged form different categories? If so, how do folks feel about just adding the setting to enable the relational query execution log?

**Comment by ajcvickers** [comment]
@DamianEdwards Yes, I think that is correct, and they are in different categories. The generated SQL for both Cosmos and relational is in the category, `Microsoft.EntityFrameworkCore.Database.Command`, so enabling this will get just the SQL back. I'm fine with this (it is was what @Rick-Anderson suggested above), although I slightly prefer turning all Info events.

**Comment by DamianEdwards** [comment]
Cool so this is a fairly simple template change then. Does anybody have any concerns with a logging setting for EF Core being present in the templates even when EF Core itself isn't referenced? I don't in particular but wanted to ask anyway.

**Comment by javiercn** [comment]
Not really, it's also not hard either to just enable it when EF is involved in the template. Its just a switch for `IndividualAuth`

**Comment by Rick-Anderson** [comment]
> Not really, it's also not hard either to just enable it when EF is involved in the template. Its just a switch for `IndividualAuth`

We don't always know when EF is being used. [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio) doesn't use auth. Customers following that tutorial want EF logging enabled so I can remove [SQL Logging of Entity Framework Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio#sql-logging-of-entity-framework-core) from the tutorial.

**Comment by ajcvickers** [comment]
Agree with @Rick-Anderson here. Numbers show that most people using EF Core with ASP.NET Core are doing so without using Identity. We should not limit this to only when Identity is included in the template.

**Comment by davidfowl** [comment]
I think we need to see what typical per request logs look like for a simple crud application. That'll help determine if we should reduce the noise or not.

**Comment by ajcvickers** [comment]
@davidfowl It will look that same as it does now with one extra log message for any SQL query.

**Comment by DamianEdwards** [comment]
@ajcvickers that's what I'm expecting to see too. I guess @davidfowl would like to see an example though.

**Comment by DamianEdwards** [comment]
It literally changes from no logs per request, to a single log message per EF database command per request:
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\dedward\source\repos\WebApplication45\WebApplication45
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (25ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [w].[Id], [w].[Name]
      FROM [Widget] AS [w]
```

**Comment by davidfowl** [comment]
That seems reasonable but I'd like to actually see it before we turn it on.

**Comment by DamianEdwards** [comment]
@davidfowl see above, I took  that from an app I just enabled it in.

**Comment by Rick-Anderson** [comment]
What's the harm of SQL noise in development? I can splatter the docs with instructions on how to comment out EF logging.

**Comment by DamianEdwards** [comment]
@Rick-Anderson not sure anyone is suggesting there's harm, just trying to ensure all folks find the defaults reasonable from their, admittedly subjective, view point.

**Comment by davidfowl** [comment]
There may harm. People do things like run performance tests in development. Also if there's too much noise then logs trend towards being not as useful

**Comment by DamianEdwards** [comment]
@davidfowl indeed, but let's scope the conversation to what we know the delta is that's being discussed here. Are you pushing back or are you OK with it?

**Comment by davidfowl** [comment]
Yes, those logs look fine.

**Comment by Rick-Anderson** [comment]
Now that we have https://github.com/dotnet/aspnetcore/issues/32977 :)

**Comment by g-u-r-k-a-n** [comment]
Hey @Rick-Anderson, I found your [answer ](https://stackoverflow.com/a/66662556/13664939) on SO while researching about `ToTraceString()`. I was going to write there but you know, the comments are limited within text there. Although I can monitor the query from Server Profiler as below, I cannot see it from the output window.

![sql-trace](https://user-images.githubusercontent.com/55924924/121590243-c82c5b80-ca40-11eb-90b1-0358ccc35333.png)

I added the `"Microsoft.EntityFrameworkCore.Database.Command": "Information"` line to the configuration file, but I still cannot see the generated query. By the way, you have shown that you have selected the project in the output window. 

![debug](https://i.stack.imgur.com/x1XNO.png)

I'm probably missing the point because of I am debugging with test project in debug mode and there is no project names. 

![debug](https://user-images.githubusercontent.com/55924924/121592209-12aed780-ca43-11eb-83f5-631a150f5271.png)

Since I used Server Profiler all the time before, I never needed it, but I wanted to use it after I saw your answer. So, what do you think I'm missing?

**Comment by DamianEdwards** [comment]
@g-u-r-k-a-n the capturing of app logs and showing in the Output window only works when launched **without** debugging.

**Comment by g-u-r-k-a-n** [comment]
Thanks @DamianEdwards . I knew them. Even the exceptions are selected. All of them are like that. I'm in the Debug mod. You describe exactly what i'm doing right now :relaxed: In fact, there are no any message except the modules. I followed your advice and turned others off but situatiuon of output window is the same.
![ss](https://user-images.githubusercontent.com/55924924/121596424-14c76500-ca48-11eb-8921-8cf0b77945f5.png)

**Comment by DamianEdwards** [comment]
@g-u-r-k-a-n can you share the contents of your `appsettings.Development.json` file please?

**Comment by g-u-r-k-a-n** [comment]
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.EntityFrameworkCore.Database.Command": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "DefaultConnection": "Server=.;Database=BlogDB;User Id=sa;Password=123;"
    //"DefaultConnection": "server=.;Database=BlogDB;Trusted_Connection=true;MultipleActiveResultSets=True;"
    //,"DefaultConnection": "server=(localdb)\\mssqllocaldb;Database=BlogDB;Trusted_Connection=true;MultipleActiveResultSets=True;"
  }
}
```
@DamianEdwards I was using different settings from config file but I turned to default config after your advise. So, I've just added others to try different ConnectionStrings but I closed them with comments as is seen. By the way, I have another base `DbContext` in the other .NET 5 project. I'm talking about a project that provides my basic needs. I'm building `appsetting.json` in `OnConfigure()` from that project. I debugging it and the connections settings is fetching succesfully.

![constr](https://user-images.githubusercontent.com/55924924/121684464-62cf7d80-cac7-11eb-8dc5-7201521b841e.png)


```cs
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
    var configuration = new ConfigurationBuilder()
                            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                            .AddJsonFile("appsettings.json")
                            .Build();

    optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"));
}
```

**Comment by DamianEdwards** [comment]
Is there a particular reason you're overriding `OnConfiguring` to do the `DbContext` configuration rather than using the built-in methods on `IServiceCollection` to configure this from your `Startup` class? Do you see any log messages at all for the ASP.NET Core application in the output window (either for Debug or the project itself)?

**Comment by g-u-r-k-a-n** [comment]
> Is there a particular reason you're overriding `OnConfiguring` to do the `DbContext` configuration rather than using the built-in methods on `IServiceCollection` to configure this from your `Startup` class? Do you see any log messages at all for the ASP.NET Core application in the output window (either for Debug or the project itself)?

This was what I tried to explanation it with the 'Base' idiom in the previous comment. in fact, you can think actual name of that project is Company.Core. Because I have a my own Core Project. I don't mentioned .NET Core, I've been using the 'Core' name for a long time already. I prefer this way to solve my similar requirements or concerns from single point.  I'm updating it when I need a new similar requirement. I have some settings or infrastructure concernes in that project and I don't want to break this struct . In this way, I can concentrate to the essential creating the algorithms independently from the technologies.

**Comment by g-u-r-k-a-n** [comment]
@DamianEdwards This was what I tried to explanation it with the 'Base' idiom in the previous comment. in fact, you can think actual name of that project is Company.Core. Because I have a my own Core Project. I don't mentioned .NET Core, I've been using the 'Core' name for a long time already. I prefer this way to solve my similar requirements or concerns from single point. I'm updating it when I need a new similar requirement. I have some settings or infrastructure concernes in that project and I don't want to break this struct . In this way, I can concentrate to the essential creating the algorithms independently from the technologies.

**Comment by DamianEdwards** [comment]
@g-u-r-k-a-n sorry, I'm a bit confused now. Are you still having an issue getting the EF Core logs to show up? If so, can you share the details of the project that is executing including it's `appsettings.json` and `appsettings.Developer.json` logging sections, and the code in your `Program.cs` and `Startup.cs` that configures the host/logging and the services collection?

**Comment by chengyanbing** [comment]
When I use a real database such as "sql server", it works very well, but when I use MemoryDatabase like this:
services.AddDbContext<CustomerDbContext>(options => options.UseInMemoryDatabase("Customers")),
it doesn't work. Is that how it was designed? Or What did I miss?

**Comment by ajcvickers** [comment]
@chengyanbing The in-memory database is not a relational database and does not use SQL, so there is no SQL to log.
