### ISSUE TITLE
[SignalR] [JS Client] Stopping & Starting connection periodically results in " Error: Cannot start a HubConnection that is not in the 'Disconnected' state"

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/aspnetcore#32987]
### Describe the bug
When stopping and then starting a connection (to restart it, say after an auth token change), the connection sometimes fails to start because it's not in a disconnected state. Even though the stop call is awaited.

This is inconsistent, sometimes it fails, sometimes it doesn't.

It seems as though `stop()` hasn't actually completed before it resolves the promise?

### To Reproduce
```js
    private async restartConnection() {
        if (this._connection) {
            await this.connection.stop();
            await this.connection.start();
        }
    }
```

### Exceptions (if any)
> Error: Cannot start a HubConnection that is not in the 'Disconnected' state.

### Further technical details
- ASP.NET Core version: `5.0.0`
- @microsoft/signalr version: `^5.0.5`
- Include the output of `dotnet --info: `N/A`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `N/A`

**Comment by BrennanConroy** [comment]
Is the exception coming from that call to start, or do you have other code that's also calling start? I find it hard to believe that this is broken from a quick glance at the code. Can you provide a minimal repro? If it's as simple as just a loop over start stop that would be nice.

**Comment by douglasg14b** [comment]
The exception is coming from `await this.connection.start();`. However, there where some intersections going on that I'm going to try and clean up for a clear repo.

How would I provide a running repro with the SignalR client since that needs a server to connect to? Honestly wondering. Unless you mean just a block of code you can take and run?

**Comment by BrennanConroy** [comment]
Client code is fine, as long as we don't need to do anything complex on the server we can just spin up a server.

**Comment by douglasg14b** [comment]
So, this was essentially a race condition on my end. I ended up trying to restart the connection 2x at the same time from different callers, after resolving that this is no longer an issue.

Closing. 

Thanks for your reply!
