### ISSUE TITLE
Published Blazor app errors on fresh visit after some amount of time

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#32983]
### Describe the bug
I have a Blazor app published to a test and production environments that exhibits an error after not visiting the app for a while.

The error states "Did not parse stylesheet at '{path to stylesheet}' because non CSS MIME types are not allowed in strict mode."

However, the CSS files on the Network tab of the developer tools can be opened without any issues.

Refreshing the page allows the app to load normally.

### To Reproduce
Run a Blazor app on a Windows server with Apache.
After not visiting the app for some amount of time, an error is presented.
Using different browsers doesn't change the behavior.

### Exceptions (if any)
Here is a screenshot of the console when presented with the error:
![Screen Shot 2021-05-24 at 6 45 19 PM](https://user-images.githubusercontent.com/213164/119416047-caf92380-bcc0-11eb-9e3b-9f70699d3001.png)

### Further technical details
- ASP.NET Core version: 5.0.6

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

We don't think that has anything specific to do with Blazor. It looks like an issue in your deployment where under some circumstance the CSS is not served correctly and instead something else is being sent. 

I would suggest capturing the network traffic with something like fiddler to confirm.
