### ISSUE TITLE
Running new SPA templates from VS results in "unable to connect to web server" error dialog

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#32986]
Repro steps:

- Install .NET 6 Preview 4 and VS 16.11 P1
- Create a new Angular or React app in VS
- Hit Ctrl+F5 to run the app

Expected result: App runs fine in launched browser

Actual result:

- App runs, but the VS shows the following error dialog without launching the browser:

![image](https://user-images.githubusercontent.com/1874516/119420978-78186f80-bcb2-11eb-8141-7916eafd2ce6.png)

@javiercn @LadyNaggaga

**Comment by javiercn** [comment]
@danroth27 thanks.

That's likely VS trying to connect to the site before the proxy is up. We have a fix coming in preview6 that will address that.

Using https://github.com/dotnet/aspnetcore/issues/32851 to track it.

**Comment by javiercn** [comment]
For completeness this is addressed [here](https://github.com/dotnet/aspnetcore/pull/32997)
