### ISSUE TITLE
IAntiforgery has no method to get the "current" antiforgery REQUEST token 

### ISSUE THREAD

**Issue by schmitch** [dotnet/aspnetcore#32999]
currently we are building a product which has some api methods, but still uses a classical razor pages environment which gets enhanced with react.

at the moment, we use the default antiforgery middleware, but it's basically really really hard to use, when using our construct, since we would need to set a hidden form element, which javascript tries to read into our ajax service. unfortunatly that is not as easy as just using two cookies, where one is the request cookie and the other is not.

unfortunatly the current api is completly internal and makes it possible to extend, that only a new request token cookie is set, when a new one is needed. (a new one is needed whenever the user changes, but that only makes the request token invalid, not the antiforgery token.)

the example given here: https://docs.microsoft.com/aspnet/core/security/anti-request-forgery?view=aspnetcore-5.0#javascript-ajax-and-spas

also only injects a new one, whenever the index page is visited, which clearly works on spa's, but not so on mixed sites, where you mix react widgets, which call ajax methods.

Edit:

the problem is that `GetAndStoreTokens` basically **always** returns a **new** `RequestToken`, so it's basically impossible to set it as a cookie.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we've heard many requests for so we won't be making changes here in the near future.
