### ISSUE TITLE
Hot reload 6.0.0-preview.3.21201.4 Blazor WASM + ASP.Net Core Hosted partially works

### ISSUE THREAD

**Issue by sajrashid** [dotnet/aspnetcore#32993]
### Describe the bug
Version: 6.0.0-preview.3.21201.4
Hot Reload most fails to work in WebAssemby (ASP.NET Core Hosted).
Detects Hot Reload 👍 

`watch : File changed: C:\Users\Me\source\repos\WebAsseblyhotreloadtest\WebAsseblyhotreloadtest\Pages\Counter.razor.
watch : Hot reload of changes succeeded.`

### To Reproduce

- Create Blazor WebAssembty App
- Tick ASP.NET Core Hosted  

> add  "hotReloadProfile": "aspnetcore", to launchSetting.json in the **Server** Project 
> `dotnet watch run `

update HTML :  Fails (have to stop & restart "dotnet run")
Update c# :Fails (Works if I manually refresh on some code)

> Add  "hotReloadProfile": "blazorwasm", to launchSetting.json in the **Client** Project  
> `dotnet watch run `

update HTML :  Fails (have to stop & restart "dotnet run"
Update c# :Fails  (have to stop & restart "dotnet run")

Remove "hotReloadProfile": "blazorwasm" from launchSetting.json in the **Client** Project 
update HTML :  Fails (have to stop & restart "`dotnet run`")
Update c# :Fails (Works if I manually refresh on some code)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- `.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.115 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`
- The IDE VS Community Version 16.10.0 Preview 4.0

**Comment by pranavkm** [comment]
Thanks @sajrashid. The profile name for Blazor Hosted apps is `blazorhosted` that you add to the `launchSettings.json` in the Server project. You shouldn't need to change to the Client project's launchSettings. For preview5, we've also looking at removing the hotReloadProfile property in launchSettings.json which should hopefully make this a lot less confusing.

Could you try the new profile name and let me know if it helps?

**Comment by sajrashid** [comment]
Hi @pranavkm 

In my existing project, the setting had no effect :(

Created a new project WASM Hosted added 

` "hotReloadProfile": "blazorhosted",`

build loops continuously,
no errors & no change except the ` "hotReloadProfile": "blazorhosted",`

Removing the hotReloadProfile, builds & runs fine.

see output below.

Thanks.
S

![image](https://user-images.githubusercontent.com/6164594/119599349-bb6efd00-bddc-11eb-845a-058ba0a691bb.png)

**Comment by sajrashid** [comment]
Hi @pranavkm, 
see minimun repo [here  ](https://github.com/sajrashid/preview6Issues)
repo also contains fileupload example linked in this issue

dotnet/aspnetcore#33101

**Comment by sajrashid** [comment]
Hi @pranavkm, any luck with this?

**Comment by srpeirce** [comment]
@sajrashid 

I am finding certain behaviours are breaking hot reload in hosted app. For example, it seems using lambdas inside nested components causes problems.

## Hot reload works inside a page

I start with this:

Counter.razor
```html
@page "/counter"
<button class="btn btn-success btn-lg" @onclick="@(() => { })">Increment</button>
```

Edit the contents, hot reload works as expected. e.g. changing to this:
Counter.razor
```html
@page "/counter"
<button class="btn btn-success btn-lg" @onclick="@(() => { })">Updated Text</button>
```

## It does not work if I extract a button component

So I extract P4Button into it's own component - hot reload no longer works when making any change to this component.
I can make changes to other components before, but as soon as I change this (for example the button text) hot reload breaks for everything.

P4Button.razor
```
<button class="btn btn-success btn-lg" @onclick="@(() => { })">Updated 2</button>
```

Counter.razor
```html
@page "/counter"
<P4Button />
```

## However, it works without lambda

If I change the code to not use a lambda, and reload the app, hot reload works:
P4Button.razor
```html
<button class="btn btn-success btn-lg" @onclick="@DoNothing">Updated 3</button>

@code {
    void DoNothing() {}
}
```
