### ISSUE TITLE
Fully ngen all of our Razor binaries for VS x64

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#33000]
Backing VSTS issue for the compiler: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1331878/
We should also fully ngen the rest of our language server assemblies.

**Comment by captainsafia** [comment]
@NTaylorMullen Does Razor tooling use the same binaries that are included in the Razor SDK?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Does Razor tooling use the same binaries that are included in the Razor SDK?

No sadly. We have to re-ship them for a few reasons:
- Decouple ourselves from SDK ship schedule
- Can't guarantee the SDK's compiler binaries will actually be compatible with what we're shipping in VS (somewhat related to the first bullet point)

Do you all do this already?

**Comment by captainsafia** [comment]
Yep -- the SDK assemblies are cross-genned when they are packaged into the installer so I figured you could reuse the work there but ah well.

**Comment by NTaylorMullen** [comment]
> Yep -- the SDK assemblies are cross-genned when they are packaged into the installer so I figured you could reuse the work there but ah well.

Appreciate the thought. It definitely would have been nice!

**Comment by ryanbrandenburg** [comment]
So after some investigation and conversation the current thinking is that our VSIX authoring is correctly requesting that these assemblies be fully NGEN'd, but when NGEN tries to run on these assemblies it fails. We're still learning more, but I thought I'd update with the current understanding.

**Comment by ryanbrandenburg** [comment]
This ended up being a point-in-time problem with the build system, nothing for us to do.
