### ISSUE TITLE
Use structured log properties in HTTP logging middleware

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/aspnetcore#33038]
The new [HTTP logging middleware](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#http-logging-middleware) is a neat idea. IMO it's not really usable for anything else than simple console or file logging, though. This is because all of the information from the request and response is simply concatenated to a big string:

```
Request: Protocol: HTTP/2 Method: GET Scheme: https PathBase: Path: /serviceworker.js QueryString: Cache-Control: [Redacted] :authority: [Redacted] :method: [Redacted] :path: [Redacted] :scheme: [Redacted] Accept: */* Accept-Encoding: gzip, deflate, br Accept-Language: en-US,en;q=0.9,da;q=0.8,da-DK;q=0.7 Cookie: [Redacted] Host: localhost:5001 Referer: [Redacted] User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 service-worker: [Redacted] sec-fetch-site: [Redacted] sec-fetch-mode: [Redacted] sec-fetch-dest: [Redacted]
```

The string is fine, but including structured properties would make it possible to do lots of interesting things if working with a log storage implementation that supports structured properties. The above string could look like this structured:

```
Request: {Protocol} {Method} {Scheme} {PathBase} {Path} {QueryString} ...
```

**Comment by davidfowl** [comment]
The log is actually structured. The console logger uses strings since that's all it can do with the structure but the actual log content is a big list of key value pairs that end up as structured logging entries assuming the LoggerProvider implementation is written to correctly recognize the pattern.

**Comment by ThomasArdal** [comment]
Thanks. It must be the logger I'm using then. I will look into what happens there ASAP.

**Comment by ThomasArdal** [comment]
Oh. That's because my logger only looks for properties with this:

```csharp
if (state is IEnumerable<KeyValuePair<string, object>> stateProperties)
```

And the `HttpRequestLog` and `HttpResponseLog` classes implement `IReadOnlyList<KeyValuePair<string, string?>>`. I can change the logger. But you might want to consider that implement since I see a lot of loggers looking for properties using `KeyValuePaid<string, object>`. Or what do you think?

**Comment by davidfowl** [comment]
We use `IReadOnlyList<KeyValuePair<string, object>>` everywhere 😄. I think you need to support both.

**Comment by ThomasArdal** [comment]
But my point is that `HttpRequestLog` uses `KeyValuePair<string, string>`: 
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpRequestLog.cs#L11

Totally fine of course. Maybe just check for that type too.

**Comment by davidfowl** [comment]
Ohhhhh, my bad, we should fix that!
