### ISSUE TITLE
SignInManager. CheckPasswordSignInAsync does not check for two factor authentication

### ISSUE THREAD

**Issue by Sabbi** [dotnet/aspnetcore#33030]
### Describe the bug

Checking a login with SignInManager. CheckPasswordSignInAsync  does not check if two factor authentication is required.

If the password is correct, it will return SignInResult.Success, even if 2FA is enabled.

See relevant lines 388 - 398 on 
 https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs)

 ```
 if (await UserManager.CheckPasswordAsync(user, password))
		{
			var alwaysLockout = AppContext.TryGetSwitch("Microsoft.AspNetCore.Identity.CheckPasswordSignInAlwaysResetLockoutOnSuccess", out var enabled) && enabled;
			// Only reset the lockout when not in quirks mode if either TFA is not enabled or the client is remembered for TFA.
			if (alwaysLockout || !await IsTfaEnabled(user) || await IsTwoFactorClientRememberedAsync(user))
			{
				await ResetLockout(user);
			}

			return SignInResult.Success;
		}
```

### To Reproduce

Do a SignInManager.CheckPasswordSignInAsync on a user with 2FA enabled. If the password check is correct, it will return SignInResult.Success

### Expected Behaviour

SignInManager.CheckPasswordSignInAsync should return SignInResult.TwoFactorRequired if 2FA is enabled for the user.

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

**Comment by brockallen** [comment]
There are other APIs for that.

**Comment by Sabbi** [comment]
> There are other APIs for that.

Nevertheless, the two methods

SignInManager.CheckPasswordSignInAsync
and
SignInManager.PasswordSignInAsync

should IMHO return the identical result if called with identical parameters.

**Comment by blowdart** [comment]
Why? One is named CheckPassword, which, well, checks the password.

Changing that API would be a major breaking change and would be very unlikely to happen without good justification

**Comment by Sabbi** [comment]
> Why? One is named CheckPassword, which, well, checks the password.

CheckPassword is another method of the SignInManager, which is not the issue. But you're right, CheckPassword should only check the password.

My issue is with [CheckPasswordSignInAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.checkpasswordsigninasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Identity_SignInManager_1_CheckPasswordSignInAsync__0_System_String_System_Boolean_) which does behave differently than [PasswordSignInAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.passwordsigninasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Identity_SignInManager_1_PasswordSignInAsync__0_System_String_System_Boolean_System_Boolean_). Both should either check if 2FA is required or ignore 2FA completly, but not that one does check (PasswordSignInAsync), and one does not (CheckPasswordSignInAsync). Naming and documentation also imply identical behaviour (except for performing actual login of course).
