### ISSUE TITLE
After upgrading to preview 4 - InvalidOperationException: The view '' was not found. on any view

### ISSUE THREAD

**Issue by lofcz** [dotnet/aspnetcore#33039]
After upgrading from preview 1 to preview 4 I'm getting `The view 'XXX' was not found. The following locations were searched. /Views/XXX/YYY.cshtml /Views/Shared/XXX.cshtml` on all actions. This is happening only after publishing on staging / production server. The issue is not present on localhost. Path on staging server contains only ASCII characters (same as on localhost), all views are set to build action - content. I have Hosting Bundle installed on staging server.

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
