### ISSUE TITLE
SqlServer Distributed Caching - Id column length

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/aspnetcore#33031]
I see that 'sql-cache' tool, used to create the distributed cache table, creates Id column as nvarchar(900).
900 seems a arbitrary number to me chosen for Id length. Is there any logic behind why 900 was chosen for Id length?

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/blob/af96abad0112a90110c0f2d46104fb2e06ed2de2/src/Tools/dotnet-sql-cache/src/SqlQueries.cs#L11-L20

Does this answer your question?

**Comment by shvmgpt116** [comment]
@BrennanConroy Thanks for the explanation. But still it does not explain why 900 bytes are chosen. Is there any logic behind it or is it chosen as any sensible length?

**Comment by BrennanConroy** [comment]
We don't know. Is it causing an issue for you?
