### ISSUE TITLE
Adding dependency to Microsoft.AspnetCore.Identity requires installed Microsoft.AspNetCore.App shared framework

### ISSUE THREAD

**Issue by vladop** [dotnet/aspnetcore#33047]
I have My.App dll which is shared between web and wpf desktop app. Since web apps already depend on Microsoft.AspNetCore.App shared framework by default it is not problem. Problem is that on desktop app users get crashes that Microsoft.AspNetCore.App should be installed. I tought that identity nuget package has everything it needs for itself. Project is built and published fine, but it is not easy to find that dependency and also even harder to receive errors from users

**Comment by blowdart** [comment]
Microsoft.AspnetCore.Identity requires Aspnet. That's why it's in that namespace.

What are you trying to do with it within wpf?
