### ISSUE TITLE
Blazor WASM AOT Compilation error

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#33053]
After upgrading to .Net 6 preview 4 I wanted to give a try to AOT Compilation, 
but I get this error message:

Error	NETSDK1147	The following workload packs were not installed: Microsoft.NET.Runtime.MonoAOTCompiler.Task Microsoft.NET.Runtime.WebAssembly.Sdk Microsoft.Netcore.App.Runtime.Aot.Cross.browser-wasm Microsoft.NET.Runtime.Emscripten.Python Microsoft.NET.Runtime.Emscripten.Node Microsoft.NET.Runtime.Emscripten.Sdk	Client	C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	24	

after removing AOT Compilation switch in CSProj, it's ok.
```
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RunAOTCompilation>true</RunAOTCompilation>
</PropertyGroup>

```

**Comment by pranavkm** [comment]
Have you installed the build tools? From the blog post

> .NET WebAssembly AOT compilation requires an additional build tools that must be installed as an optional .NET SDK workload in order to use. To install the .NET WebAssembly build tools, run the following command from an elevated command prompt:

```
dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
```
