### ISSUE TITLE
Dedupe Razor helper classes across relevant repos

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#33058]
We've currently got Razor-related code in three different repos: aspnetcore-tooling, aspnetcore, and sdk.

Each of these repos contains it's own copy of shared utility classes like `TagHelperJsonConverter`.

* https://github.com/dotnet/aspnetcore/blob/1a2b3260c6161ae9b7f639de228a6eb0488a1075/src/Shared/RazorShared/TagHelperDescriptorJsonConverter.cs
* https://github.com/dotnet/sdk/blob/c26c3eec745d5350cf3d0bd6657553c0c7f1ec80/src/RazorSdk/Tool/TagHelperDescriptorJsonConverter.cs
* https://github.com/dotnet/razor-tooling/blob/1d644183c1e0be04b02483ad8a5cc2d4ef6db433/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/TagHelperDescriptorJsonConverter.cs

We should consolidate all these into a single source of truth to avoid inconsistent implementations.

**Comment by TanayParikh** [comment]
Bringing into Docs & Infra if there's time

**Comment by mkArtakMSFT** [comment]
Talked about this a bit more and we think there is no much value in doing this at this time. Also, one of the items in the list is something we don't use any more.
