### ISSUE TITLE
Allow exception propagation during view render

### ISSUE THREAD

**Issue by gyankov** [dotnet/aspnetcore#33065]
Currently the  [view.RenderAsync](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/ViewExecutor.cs#L243) method is executed within a try block. Thus, if an exception is thrown during rendering, no error message is displayed which makes it hard to track.

### Is your feature request related to a problem? Please describe.
In a custom html helper which internally uses HtmlHelper.Editor, if the editor view is misconfigured and throws an exception, instead of showing a meaningful exception message, the html helper simply has no output which is confusing and a nightmare to track down.

### Describe the solution you'd like
```
try
{
    viewContext.Writer = writer;

    DiagnosticListener.BeforeView(view, viewContext);

    await view.RenderAsync(viewContext);

    DiagnosticListener.AfterView(view, viewContext);
}
catch
{
    if (viewContext.PropagateExceptions)
    {
         throw;
    }
}
finally
{
    viewContext.Writer = oldWriter;
}
```

**Comment by pranavkm** [comment]
@gyankov it's likely that the HTTP headers were already sent by the time the exception were thrown which is why you don't see a developer exception page. Do you see these exceptions logged or see the exception with a debugger attached?

**Comment by gyankov** [comment]
@pranavkm Yes, I see the exception, but only if my Exception Settings are configured to show that exact exception. If you use the default exception settings, this will still fail silently even while debugging.

If that is by design, is there any way around it? Showing some exception message would save a ton of time to many developers.
