### ISSUE TITLE
Blazor loading destroys my page

### ISSUE THREAD

**Issue by ottaCronos** [dotnet/aspnetcore#33078]
In my Blazor project, I have a js file that styles the page (script-dashboard.js). 
Everything works fine outside blazor (wamp/asp.net mvc) and when blazor is not loaded :
`<script src="_framework/blazor.server.js" autostart="false" defer></script>`
But when I load blazor, the page breaks.

[When blazor is not loaded](https://ibb.co/2PpF52t)
[When blazor is loaded](https://ibb.co/BgT1wFj)

I've already looked at theses issues : 
[#22643](https://github.com/dotnet/aspnetcore/issues/22643)
[#16628](https://github.com/dotnet/aspnetcore/issues/16628)
But none of the solutions work for me...

`script-dashboard.js` is currently loaded like this : 
```
jQuery(window).on("load", loadApp);

function loadApp() {
	'use strict';

	jQuery('...')...({
		...: false,
	});
}
```

I would like to understand why loading Blazor causes "all scripts to reload" (or something like that)
and how I could fix the problem. (I think the problem is with my script, but why, I already had the same problem with another one and running the script manually in `OnAfterRender()` was enough to fix the problem)

Thanks in advance for your help, I discover Github Issues so sorry if I don't do everything correctly 😅

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
