### ISSUE TITLE
Localize standard DataAnnotations in ASP.NET Core MVC

### ISSUE THREAD

**Issue by sdudnic** [dotnet/aspnetcore#33073]
### The problem

As far as I see from the docs, [DataAnnotation localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0) asks additional resx files, or hardcoded translation strings in [Attributes], or specific code customization, that seem not really fair versus non-English projects.

In order to make `"The XX field is required"` string to appear as `"Le champ XX est obligatoire"` we need to write it hardcoded on all decorated with `[Required]` properties, or write custom code to implement it on all the `[Required]` properties, and also for all other `DataAnnotation` attributes, that seem strange... 

`DataAnnotation` should be translated in a similar way another localized strings are, depend on the current culture, be available in localized `.json` or `res` files or similar, without the need for each developer to translate by itself the same "Is required" string with same text in their projects. 

### Further technical details
- ASP.NET Core version:  5.0.202
- VS 2019

### Linked to
- https://github.com/dotnet/aspnetcore/issues/4848
- https://github.com/dotnet/aspnetcore/issues/2631
- https://github.com/aspnet/Localization/issues/286
- [SO question](https://stackoverflow.com/questions/67683394/localize-dataannotations-in-asp-net-core)

**Comment by progmars** [comment]
Also, the entire model validation message pipeline should be improved. 

If we want to return translated error messages also for the automatic model binding validations (e.g. non-null properties, data types etc.), the workaround becomes very ugly. Just look at this convoluted piece of code I had to use as a workaround to have fully translated binding errors:

```
public static IMvcBuilder AddModelBindingMessagesLocalizer(this IMvcBuilder mvc,
            IServiceProvider serviceProvider, 
            IValidationErrorLocalizer localizer, Type modelBaseType)
        {
            var VL = localizer.ValidationStringLocalizer;
            var DL = localizer.FieldNameStringLocalizer;

            return mvc.AddMvcOptions(o =>
            {
                // for validation error messages
                o.ModelMetadataDetailsProviders.Add(new LocalizableValidationMetadataProvider(VL, modelBaseType));

                // for field names
                o.ModelMetadataDetailsProviders.Add(new LocalizableInjectingDisplayNameProvider(DL, modelBaseType));

                // does not work for JSON models - Json.Net throws its own error messages into ModelState :(
                // ModelBindingMessageProvider is only for FromForm
                // Json works for FromBody and needs a separate format interceptor
                var provider = o.ModelBindingMessageProvider;

                provider.SetValueIsInvalidAccessor((v) => VL["FormatHtmlGeneration_ValueIsInvalid", v]);
                provider.SetAttemptedValueIsInvalidAccessor((v, x) => VL["FormatModelState_AttemptedValueIsInvalid", v, x]);
                provider.SetMissingBindRequiredValueAccessor((v) => VL["FormatModelBinding_MissingBindRequiredMember", v]);
                provider.SetMissingKeyOrValueAccessor(() => VL["FormatKeyValuePair_BothKeyAndValueMustBePresent" ]);
                provider.SetMissingRequestBodyRequiredValueAccessor(() => VL["FormatModelBinding_MissingRequestBodyRequiredMember"]);
                provider.SetNonPropertyAttemptedValueIsInvalidAccessor((v) => VL["FormatModelState_NonPropertyAttemptedValueIsInvalid", v]);
                provider.SetNonPropertyUnknownValueIsInvalidAccessor(() => VL["FormatModelState_UnknownValueIsInvalid"]);
                provider.SetUnknownValueIsInvalidAccessor((v) => VL["FormatModelState_NonPropertyUnknownValueIsInvalid", v]);
                provider.SetValueMustNotBeNullAccessor((v) => VL["FormatModelBinding_NullValueNotValid", v]);
                provider.SetValueMustBeANumberAccessor((v) => VL["FormatHtmlGeneration_ValueMustBeNumber", v]);
                provider.SetNonPropertyValueMustBeANumberAccessor(() => VL["FormatHtmlGeneration_NonPropertyValueMustBeNumber"]);


                // the code below is to prevent JSON.NET from polluting modelstate with unlocalizable messages, such as:
                /*
                    "errors": {
                    "countryId": [
                      "Input string '111a' is not a valid number. Path 'countryId', line 3, position 23."
                    ]
                  },
                  */

                var customJsonInputFormatter = new LocalizableJsonInputFormatter(localizer,
                     serviceProvider.GetRequiredService<ILoggerFactory>().CreateLogger<LocalizableJsonInputFormatter>(),
                     serviceProvider.GetRequiredService<IOptions<MvcJsonOptions>>().Value.SerializerSettings,
                     serviceProvider.GetRequiredService<ArrayPool<char>>(),
                     serviceProvider.GetRequiredService<ObjectPoolProvider>(),
                     o,
                     serviceProvider.GetRequiredService<IOptions<MvcJsonOptions>>().Value
                );

                o.InputFormatters.Insert(0, customJsonInputFormatter);

            });
        }
```

**Comment by sdudnic** [comment]
please do a "like" on the issue, if not, they will not treat it in the backlog...

**Comment by LazZiya** [comment]
Many developers prefers official solutions, but sometimes when the wait is too long, you will start developing it yourself or find a community solution.

I've developed a nuget ([XLocalizer](https://github.com/LazZiya/XLocalizer)) for simplifing localization in all aspects including auto adding missing keys and online translation support. 

In terms of validation there are three main categories:
- DataAnnotations erros
- Model binding errors
- Identity describer errors

Basically there is no need to provide any error message manually, XLocalizer will take care of localizing all automatically. But if you want to customize any error message you can do it simply in startup or json.

- ### Option A : In startup
````cs
services.AddRazorPages()
        .AddXLocalizer<...>(ops =>
        {
            // Data annotation error messages
            ops.ValidationErrors = new ValidationErrors 
            {
                RequiredAttribute_ValidationError = "The {0} field is required.",
                CompareAttribute_MustMatch = "'{0}' and '{1}' do not match.",
                StringLengthAttribute_ValidationError = "The field {0} must be a string with a maximum length of {1}.",
                // ...
            };

            // Model binding error messages
            ops.ModelBindingErrors = new ModelBindingErrors
            {
                AttemptedValueIsInvalidAccessor = "The value '{0}' is not valid for {1}.",
                MissingBindRequiredValueAccessor = "A value for the '{0}' parameter or property was not provided.",
               // ...
            };

            // Identity Errors
            ops.IdentityErrors = new IdentityErrors
            {
                DuplicateEmail = "Email '{0}' is already taken.",
                DuplicateUserName = "User name '{0}' is already taken.",
                // ...
            }
        });
````

- ### Option B - Json:
````js
{
  "XLocalizerOptions": {

    ....

    "ValidationErrors": {
      "CompareAttribute_MustMatch": "'{0}' and '{1}' do not match. They should not be different!",
      "CreditCardAttribute_Invalid": "The {0} field is not a valid credit card number.",
      "CustomValidationAttribute_ValidationError": "{0} is not valid.",
      ...
    },
    "IdentityErrors": {
      "DuplicateEmail": "Email '{0}' is already taken.",
      "DuplicateUserName": "User name '{0}' is already taken. Please try another one.",
      "InvalidEmail": "Email '{0}' is invalid.",
      ...
    },
    "ModelBindingErrors": {
      "AttemptedValueIsInvalidAccessor": "The value '{0}' is not valid for {1}.",
      "MissingBindRequiredValueAccessor": "A value for the '{0}' parameter or property was not provided.",
      ...
    }
  }
}
````

- [XLocalizer Repo](https://github.com/LazZiya/XLocalizer)
- [Docs](https://docs.ziyad.info/)
- [Samples](https://github.com/LazZiya/XLocalizer.Samples)

**Comment by sdudnic** [comment]
great work, @LazZiya ! However when it comes to _human translated messages_, the actual solution is always to _hardcode_, and not use a community translated set of messages by language. You take the translation of "_field_" and in many languages it is translated like "_meadow_" or "_pasture_"... this is why I asked MS & Co to move to a stable solution for non-English users, not imposing them to hardcode the seem texts for each of them.

**Comment by ianbrian** [comment]
Localization should be baked in. I've been spending ages replacing hard-coded strings in Identity razor pages. Millions of developers must have done that. What a waste of time.

**Comment by einsteinpp** [comment]
Nice, in the backlog again  😒.

**Comment by hishamco** [comment]
@sdudnic could please let me know what's the exact issue in the DataAnnotations localization? I remembered there was an issue with `DisplayAttribute` then we did a custom fix in Orchard Core
