### ISSUE TITLE
[Blazor Server] Memory that grows during a Drag'n'Drop

### ISSUE THREAD

**Issue by tossnet** [dotnet/aspnetcore#33077]
### Describe the bug
In a little example I show a memory problem. I can't explain this growth.
I have a Blazor Server project in production and I see an incredible memory increase when using Drag and Drop. I made a small program to show the problem:
![mem](https://user-images.githubusercontent.com/3845786/119842401-ee151480-bf06-11eb-86a9-f7d2a24555d4.jpg)

[https://user-images.githubusercontent.com/3845786/119837872-3e8a7300-bf03-11eb-9561-aa6a3dad1f35.mp4](https://user-images.githubusercontent.com/3845786/119837872-3e8a7300-bf03-11eb-9561-aa6a3dad1f35.mp4)

### To Reproduce
Instead of explaining I made a minimalist code on github to reproduce this like the video above
[https://github.com/tossnet/Blazor-memory-keeps-growing](url)

With each movement or shift of a DIV, the memory increases for no visible reason

the code is very simple and I can summarize it here:

`<div class="d-flex flex-wrap myContener"  ondragover="event.preventDefault();">
	@for (int i = 0; i < Cells; i++)
	{
		var id = i;
		<div class="cellBoard" @ondrop="() => HandleOnDrop(id)" >
			
			@foreach(Piece p in Pieces)
			{
				if (p.IDCell == i)
				{
					<div class="dot" draggable="true" 
						@ondrag="() => HandleDragStart(p.ID)">
					</div>
					break;
				}
			}
		</div>
	}
</div>`

### Further technical details
- Blazor Server
- .net5.0
- The IDE (VS2019 16.11.0 Preview 1.0 and VS2019 16.10)

**Comment by javiercn** [comment]
@tossnet thanks for contacting us.

We don't think this is an issue in Blazor. We don't think the way you are using to measure the memory is accurate. When running inside Visual Studio, debugging and likely using a debug build, the GC behaves differently.

If you want to capture an accurate trace of your program we suggest you follow some of the guidance provided [here](https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-5.0) to accurately measure the memory usage in your app.
