### ISSUE TITLE
Kestrel loads wrong SSL certificate when configured in appsettings

### ISSUE THREAD

**Issue by piotrekh** [dotnet/aspnetcore#33070]
At my work there is a server with two SSL certificates installed in the store - let's say the first one's subject is **my-app** whereas the second one's is **client-my-app**. We're hosting an application which is supposed to use the first one as the server certificate and has the following appsettings configuration (we use xml instead of json but it doesn't matter in this case):

```
<Kestrel>
  <EndPoints>
    <HttpsInlineCertStore>
      <Url>https://*:1029</Url>
      <Certificate>
        <Subject>my-app</Subject>
        <Store>My</Store>
        <Location>LocalMachine</Location>
        <AllowInvalid>false</AllowInvalid>
      </Certificate>
    </HttpsInlineCertStore>
  </EndPoints>
</Kestrel>
```

The problem is that in the runtime we can see that the other certificate - '**client**-my-app' - is used instead, which is wrong. I found out that the code responsible for loading certificate uses a 'less precise' search type [X509FindType.FindBySubjectName](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509findtype?view=netframework-4.7.2#fields) to find a certificate by subject name:

https://github.com/dotnet/aspnetcore/blob/028470e31304cde30aebacd44be2abc34ee99f62/src/Servers/Kestrel/Core/src/CertificateLoader.cs#L39

It sees that 'client-my-app' contains 'my-app' string entered in the configuration and returns wrong certificate :(

### What can be done?
I see two possible solutions to this problem:
- fix the code to use X509FindType.FindBySubjectDistinguishedName - is there any valid reason why someone would actually want the less precise FindBySubjectName? I think it can only lead to unpredicted and difficult to trace issues (like in my example)
- add possibility to define the find type in configuration:
```
<Certificate>
  <Subject>my-app</Subject>
  <SubjectFindType>FindBySubjectDistinguishedName</SubjectFindType>
  <Store>My</Store>
  <Location>LocalMachine</Location>
  <AllowInvalid>false</AllowInvalid>
</Certificate>
```

### Current workaround
I know the 'easiest' way to deal with this issue would be to generate and use a certificate with different, unique subject, but unfortunately it's not that simple in a corporate environment. We found a silly workaround and enter a blank space before subject name, which surprisingly results in loading the correct certificate: ```<Subject> my-app</Subject>```

**Comment by BrennanConroy** [comment]
Triage: we probably still want the substring to work, but we should attempt to match the exact value first then fallback to substring.

**Comment by piotrekh** [comment]
@BrennanConroy 'probably' - so you too don't see a clear reason when FindSubjectName might be useful, do you? Regardless, I think such a solution would be a fair enough compromise and I could live with that ;)

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/34582, will be in rc1
