### ISSUE TITLE
Use edge for blazorwasm config by default

### ISSUE THREAD

**Issue by connor4312** [dotnet/aspnetcore#33088]
We now have integration with the Edge Tools team that adds an "inspect" icon and functionality to Edge sessions. We should default to Edge so that blazor debugging gets this functionality too.

![](https://memes.peet.io/img/21-05-4d5c4471-0571-4df2-9350-563856d06d00.png)

Currently users manually need to opt-in by specifying `browser: edge`:

```
{
  "type": "blazorwasm",
  "name": "Launch and Debug Blazor WebAssembly Application",
  "request": "launch",
  "browser": "edge",
  "url": "http://localhost:5000"
}
```

@captainsafia / @codepo8

**Comment by javiercn** [comment]
@connor4312 thanks for contacting us.

@captainsafia @danroth27 do you have any thoughts on this? Moving to next sprint planning for consideration. Marking as good first issue, help wanted **in case we decide to go this route**

**Comment by codepo8** [comment]
Hey @javiercn, I'm the PM for the integration on the Edge DevTools side, if you need any help or more information, feel free to reach out.

**Comment by javiercn** [comment]
@codepo8 thanks for letting us know.

I'm not very involved in this feature, hence why I passed the ball to @captainsafia (main dev on the area) and @danroth27 (the PM for Blazor)

**Comment by captainsafia** [comment]
Yep -- this is something we discussed doing via email.

The change itself is pretty trivial. We'll need to update the default value here:

https://github.com/dotnet/aspnetcore-tooling/blob/abb2775cd1185b50f0cfc404e7316e8826f2e116/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json#L84

and here:

https://github.com/OmniSharp/omnisharp-vscode/blob/19b027b91ae99b1010af249a1a9131b8cdf45ae0/package.json#L3179

@codepo8 Would you be interested in updating the values as needed here?

**Comment by danroth27** [comment]
Have we tried out the debugging experience with Edge on macOS? Any known issues there?

**Comment by connor4312** [comment]
Edge on macOS work well, though I haven't tried Blazor + macOS + Edge.

**Comment by captainsafia** [comment]
@danroth27 Yeah, I tried it recently. No major issues with Edgeium.

**Comment by codepo8** [comment]
I'm a Mac user, all good.

**Comment by taha-ghadirian** [comment]
Hello! @mkArtakMSFT can I work on this issue? 
I hope you could assign it to me ;)

**Comment by prnam** [comment]
In my opinion it should open up default browser set by user in their machine (to avoid monopoly concerns in future / considering .NET Foundation working in favour of MSFT corp as deviation from objective or bylaws etc.)  and then also have an option of using Safari, Firefox accepted as valid values.

**Comment by connor4312** [comment]
js-debug uses the [`default-browser`](https://github.com/sindresorhus/default-browser) module to check the browser on any platform, to which I PR'd in support for Windows a few months ago 🙂

**Comment by TanayParikh** [comment]
Thanks @DarCampbell. @captainsafia is this change done already given https://github.com/dotnet/razor-tooling/pull/5666 & https://github.com/OmniSharp/omnisharp-vscode/pull/4847?

Do we need to update:
https://github.com/dotnet/razor-tooling/blob/e43ce65bda7c105463e3775e8beb89cc48444ea1/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts#L94

to something like:

```
type: configuration.browser === 'chrome' ? 'pwa-chrome' : 'pwa-msedge',
```

**Comment by captainsafia** [comment]
> Thanks @DarCampbell. @captainsafia is this change done already given dotnet/razor-tooling#5666 & OmniSharp/omnisharp-vscode#4847?

Yep. This is done now via https://github.com/OmniSharp/omnisharp-vscode/commit/1300a755cd67bd19a85355991f29ffaf14d127b9.

**Comment by TanayParikh** [comment]
Thanks for confirming, closing out the issue.
