### ISSUE TITLE
ASP.NET Core analysis rule CA5395 false positive for [Route] w.r.t. HTTP HEAD requests (and spelling mistake)

### ISSUE THREAD

**Issue by Jehoel** [dotnet/aspnetcore#33102]
### Describe the bug

ASP.NET Core's code-analysis rule CA5395 complains if a Controller has an Action that is not annotated with a `[HttpGet]`, `[HttpPost]`, `[HttpHead]`, `[HttpDelete]`, etc.

The straightforward way to comply with the rule is to add a `[HttpGet]` attribute - or to replace `[Route("etc")]` with `[HttpGet("etc")]`, however doing so means you lose ASP.NET Core's built-in `HEAD` request handling feature.

...but using both `[HttpGet]` and `[HttpHead]` attributes on the same controller action is not a perfect solution and causes web-applications to violate the HTTP spec regarding `HEAD` vs `GET` requests - and also means repeating the route template twice: once in each attribute - or still using the `[Route]` attribute which just means more lines-of-code for no real gain.

----

Also, the analyzer's error message has a spelling mistake and it's missing a terminal period: `"request kind explictly"` should be "`request kind explicitly.`".

### To Reproduce

1. Create a new ASP.NET Core project with these MSBuild properties:

    ```
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    ```

1. Define a controller with a `[HttpRoute("etc")]`:

    ```
    namespace Foobar
    {
        public class MyController : Controller
	{
            [Route("/etc")]
            public async Task<IActionResult> DoSomething()
            {
                return this.View( "Something", new SomethingViewModel() );
            }
        }
    }
    ```

1. Add the `Something.cshtml` view and `SomethingViewModel` class. Ensure there's some HTML content.
1. Build the project.
1. You'll get this output:

    ```
    warning CA5395: Action method DoSomething needs to specify the Http request kind explictly
    ```

1. Change the action to use `[HttpGet][HttpHead]` and run the project.
1. Make a `HEAD` request for `/etc`.
1. Observe that the response to the `HEAD /etc` request now has a content body, in violation of the HTTP spec.

### Exceptions (if any)

None

### Further technical details
- ASP.NET Core version: 5
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2019 19.9.6

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.9.6
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>
```

**Comment by javiercn** [comment]
Agreed.

Not sure who created these analyzers, I don't think anyone on the MVC team was consulted for best practices.

**Comment by javiercn** [comment]
@pranavkm I'm closing this issue since we don't own these analyzers. 

We should follow up with the appropriate teams to fix the guidance.

**Comment by Jehoel** [comment]
@javiercn With respect, please keep this issue open **until** we hear back from the aspnet people and a plan is in action.

My issue is not resolved. Please don't close issues until they're _actually resolved_.
