### ISSUE TITLE
[Blazor] Add html attribute to component

### ISSUE THREAD

**Issue by netleader** [dotnet/aspnetcore#33118]
Hi Folks,
I want to add a data attribute automatically to every component based on the component name:

`<div data-template="Components/Counter" />`

I tried to create my own `ComponentBase` class but no success. Any hints?

**Comment by En3Tho** [comment]
Have you tried looking at BlazorUniversity? Got lots of material there. Also, it would be good if you could describe the expected result better, like what kind of template and what should it change when applied

**Comment by javiercn** [comment]
@netleader thanks for contacting us.

It's not 100% clear what you are trying to accomplish. However, if you expect the markup to be added "automagically" that's not a feature that we currently have.
