### ISSUE TITLE
Remove RazorSemanticTokensLegendEndpoint

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#33119]
For Semantic tokens we currently have a "hack" Endpoint which provides the SemanticTokenLegend. This is off-spec, it should be provided on the server capability. [See the specification here](https://microsoft.github.io/language-server-protocol/specification#textDocument_semanticTokens). This may mean advancing some of our dependencies to newer versions to more easily provide this, or it might just work already if we delete it.

**Comment by NTaylorMullen** [comment]
Did this!
