### ISSUE TITLE
Razor partial Views dont refresh even after using Razor Runtime Compilation?

### ISSUE THREAD

**Issue by aloksharma1** [dotnet/aspnetcore#33122]
### Describe the bug
hello when i use AddRazorRuntimeCompilation method with custom view providers or otherwise, the views are refreshed when file changes. but same is not true for partial view, partials once called using view component/partial/render partial or tag helpers gets cached in view engine ViewLookupCache and doesnt refresh so only option i get is restarting the app. which is non intuitive, i found a SO solution talking about implementing CustomViewEngine but its an example of net core 2.1 while i am using net 5. And i am not sure if that solution still applies after the introduction of Runtime Compilation.

### To Reproduce

simply call this in startup service : 
service.AddMvc().AddRazorRuntimeCompilation();

and try to pull any test partial view with aforementioned methods and change it while running the app, view changes will take effect but partial wont.
            
### Exceptions (if any)

none
### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS Code

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by aloksharma1** [comment]
i dont thin kthis requires any repo to check it, as the issue is related to view engine caching but if you certainely need it i will make one by weekend.

**Comment by mkArtakMSFT** [comment]
@aloksharma1 we do need a repro, as we have a test validating this scenario and it does pass. Will wait for you to provide one.
