### ISSUE TITLE
Tool to validate the performance : Blazor Web assembly application

### ISSUE THREAD

**Issue by KameshRajandran** [dotnet/aspnetcore#33138]
Could you please some one suggest a tool to validate the performance (profiling) of Blazor **web assembly application**. We have used resharper tool for validating the performance for server application. But we could not able to validate the performance. 

We need to validate the following cases.

1. Initial performance 
2. Performance factors while state has changed
3. in which code causes performance issues.

**Comment by Rkeerthivasan** [comment]
Hi team,

 we have to validate the performance in Blazor web assembly. Could you please suggest a tool to validate the performance (profiling) of Blazor web assembly application?

Thanks in advance.

Regards,
Keerthivasan R.

**Comment by RanjithaAmirthalingam** [comment]
Hi Team,

I too need to validate the performance in Blazor web assembly. Could you please suggest a tool to validate the performance (profiling) of Blazor web assembly application?

Thanks and Regards,
Ranjitha A.

**Comment by RajeswariPounraj** [comment]
Hi Team,

I also need to validate the performance in Blazor web assembly. Can anyone please suggest a tool to validate the performance of Blazor web assembly application?

Regards,
Rajeswari P.

**Comment by sivakumarsync** [comment]
I too have a same requirement to validate the performance in Blazor web assembly. Could you please suggest a performance validation tool for Blazor web assembly application?

Regards,
Sivakumar S

**Comment by sekarsivakumar** [comment]
Can anyone suggest a tool to validate the performance of Webassembly application. I too have the same requirement as he mentioned.

**Comment by Arunkumar-syncfusion** [comment]
Hi,

we also facing the same issue on our end. can anyone suggest an idea to work on it

**Comment by javiercn** [comment]
@KameshRajandran thanks for contacting us.

You can use the same tools you use with .NET Core to measure the performance of a Blazor application. We recommend you start by testing the performance using common tools like Benchmarkdotnet or Perfview in a console, class library or using Blazor Server.

For Blazor Webassembly specifically the best way is to use the performance tools built in directly in the browser.

/cc: @SteveSandersonMS and @pranavkm in case they have more ideas.

Note that this is not a feature our team would build, you might get better luck asking the `dotnet/runtime` folks.
