### ISSUE TITLE
New Razor Editor randomly hangs and freezes

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/aspnetcore#33149]
Visual Studio version: 16.11.0 Preview 1.0
Enable experimental Razor Editor: on
Project type: Blazor WebAssembly
Windows version: 21H1 (OS Build 19043.1023)
.NET SDKs:
5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
CPU: 12 HT cores, 3.7 Ghz
Memory: 16 GB

It happens randomly, usually when copying or cutting text:
![image](https://user-images.githubusercontent.com/9047283/120118130-524b0900-c191-11eb-8e78-b4619de78b57.png)

This operation never ends and cannot even be cancelled. The only way is to kill the whole VS process and re-open everything.

Some other symptoms:
 - colors appear long seconds after opening a single Razor file, sometimes only parts of the file get colorized and not the whole document
 - other operations like automatic tag close takes usually more than 5 seconds
 - completions even in simple C# segments of a Razor file are so slow that they are late, basically non-existent

I give this new editor a try every now and then when a new preview becomes available, because the old one definitely need to be redesigned, but this new one is still so far from being usable that I get to the conclusion that the old one is still better, and I have to switch back every time.

**Comment by aloksharma1** [comment]
i had to disable a bunch of extensions to make mine working after latest update, otherwise my project was crashing.

**Comment by NTaylorMullen** [comment]
@Peter-Juhasz would you mind providing the following:
1. A repro project
2. A process dump when VS hangs like that? We'd love to investigate further. You can also provide this info by  by doing "Report a Problem" in VIsual Studio:
![image](https://user-images.githubusercontent.com/2008729/121093767-59ca6d80-c7a2-11eb-8c07-7e6ecb33da63.png)

**Comment by Peter-Juhasz** [comment]
Same thing happens with new VS2022 17.0.0 Preview 1. No extensions are installed.

I was trying to delete text too fast, `Shift`+`Delete` two lines:

![image](https://user-images.githubusercontent.com/9047283/122666176-11507e00-d1ac-11eb-81d3-ad4ace11ab89.png)

@NTaylorMullen I can't even open the Report a problem menu since the whole Visual Studio is frozen and this modal dialog never vanishes. Cancel does literally nothing, I have to restart the whole process all over again.

The project I work on is not publicly shareable, it is somewhat large (around 200 Blazor files), but there is nothing special or customized in it, not even a 3rd party NuGet package.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I can't even open the Report a problem menu since the whole Visual Studio is frozen and this modal dialog never vanishes. Cancel does literally nothing, I have to restart the whole process all over again.

When VS' hanging if you could capture a process dump and then after-the-fact do Report a Problem in a separate VS & upload the process dump that'd help immensely!

**Comment by Peter-Juhasz** [comment]
The occurrences are definitely less with the new 2022 preview, which is good news, but still occurs. Is there any way to send some kind of sanitized dump? And what process (I have "out-of-process" preview flag enabled with 2022)? Thanks.

**Comment by NTaylorMullen** [comment]
> The occurrences are definitely less with the new 2022 preview, which is good news, but still occurs. Is there any way to send some kind of sanitized dump? And what process (I have "out-of-process" preview flag enabled with 2022)? Thanks

Here's a good [doc](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem-minidumps?view=vs-2019#create-the-minidump-file). As for which process `devenv.exe` is sufficient in this scenario.

**Comment by Peter-Juhasz** [comment]
This is how it looks like, the last action is cut text:
![razoreditor](https://user-images.githubusercontent.com/9047283/123158663-615d6800-d46c-11eb-9f2e-e96f7214098b.gif)

Visual Studio completely freezes, there is no way to cancel, and there is no return. We have to restart the whole IDE every time this happens.

And although the new experience would be super cool and starting to get useful, all the issues still persist which pretty much ruins the experience:
 - the whole IDE becomes unresponsive
 - significant lag in typing
 - closing of tags
   - takes long seconds (gif render might even shortened the recording by a few frames)
   - sometimes even misses completion
   - sometimes completes later and the text ends up gibberish
 - parts of the text is wrongly classified

Classification bug example:
![image](https://user-images.githubusercontent.com/9047283/123159811-bc438f00-d46d-11eb-8e54-2c8aa595d954.png)

Version: 17.0.0 Preview 1
Project: .NET 5

Installed extensions (none added to default installations):
![image](https://user-images.githubusercontent.com/9047283/123159012-c913b300-d46c-11eb-9f55-1b09166dae8a.png)

**Comment by Peter-Juhasz** [comment]
Even a simple copy can crash the whole VS from the new Razor editor:
![image](https://user-images.githubusercontent.com/9047283/123165334-645c5680-d474-11eb-8272-6d29fc9e89f8.png)

**Comment by Peter-Juhasz** [comment]
This is the reproduction with formatting: paste text, select text, copy
![razoreditor2](https://user-images.githubusercontent.com/9047283/123166087-4e02ca80-d475-11eb-82ca-8e24dbe7bda5.gif)

Note:
 - the classification error in line 115. The interpolated expression in the interpolated string seems like it is classified as an HTML attribute value, instead of proper C# classification.
 - also, classification of the pasted text lags way behind

**Comment by NTaylorMullen** [comment]
@Peter-Juhasz we're pretty sure these issues are fixed with 17.0-Preview3 (currently released). Would you mind trying that build out and seeing if your issue persists?

**Comment by Peter-Juhasz** [comment]
I follow the preview releases closely and usually I'm always on the latest one. I can confirm that I have never experienced any hangs or freezes in the new Razor editor since I use the latest preview. 👍

Although I have "Use accurate classification" (under "Copy rich text on copy/cut") turned off since some time which might have been related to the issue.

While the issues mentioned in the issue title seems to be addressed, I can still experience the slowness, like tag completion still takes long seconds, or a lot of times my normal pace of typing is faster than code completion could follow, and it arrives late.

**Comment by NTaylorMullen** [comment]
> While the issues mentioned in the issue title seems to be addressed, I can still experience the slowness, like tag completion still takes long seconds, or a lot of times my normal pace of typing is faster than code completion could follow, and it arrives late.

17.0-Preview4 should fix that completely! 😄

**Comment by Peter-Juhasz** [comment]
@NTaylorMullen I can confirm that the editor in general and specifically tag completion feel much faster! Good job! 🎉

There are still a few issues I/we encounter every day, I know the language service is still in preview, but they may worth a look on your side, if some of them would not be known yet or regression related:
 - Syntax highlighting: C# identifiers are not classified correctly `AsOrganization`, parts of code segments remain classified as plain markup attribute value
 - Semantics: `RequireMembership` property (component parameter) is not recognized, although it exists, compiles successfully and works
![image](https://user-images.githubusercontent.com/9047283/133478778-b225380d-7b3d-43b0-bae0-28fc84e0f163.png)

Reference:
![image](https://user-images.githubusercontent.com/9047283/133479349-13353e57-fbd6-4716-8401-76d935673d6e.png)

 - Completion: is missing for `RenderFragment` typed parameters:
![image](https://user-images.githubusercontent.com/9047283/133479609-1eebc4ec-ca55-4ae6-8012-7098ca3a99f2.png)

Reference:
![image](https://user-images.githubusercontent.com/9047283/133479759-2c6d1052-de72-4717-8d06-94369972932c.png)

 - Syntax highlighting: can get out of sync and misaligned sometimes
![image](https://user-images.githubusercontent.com/9047283/133478891-883db24d-35c3-45e8-8482-a1a70fee4066.png)

 - Attribute value enclosing quotes are not inserted automatically (it worked before)
![image](https://user-images.githubusercontent.com/9047283/133480205-08c17412-42b6-4087-8b0f-3616125749d6.png)

 - Navigation: go to definition doesn't work on component parameters

**Comment by NTaylorMullen** [comment]
> * Syntax highlighting: C# identifiers are not classified correctly `AsOrganization`, parts of code segments remain classified as plain markup attribute value

Ya that definitely seems odd. Does this happen every time for you? If so, would it be possible to share a repro for us to investigate further? /cc @ryanbrandenburg 

> Completion: is missing for RenderFragment typed parameters:

Ya this is something I'd like to add to completion. A missing feature that would be so nice to have!

> Syntax highlighting: can get out of sync and misaligned sometimes

Hmmm, I could have swore we fixed this in Preview4. @ryanbrandenburg / @allisonchou the one-off fix was in Preview4 right?

> Attribute value enclosing quotes are not inserted automatically (it worked before)

This is probably one of the most sad take backs we have in VS2022 (/cc @mikadumont). We're trying our best to bring this back in subsequent VS2022 releases!!

> Navigation: go to definition doesn't work on component parameters

On our radar and are really looking forward to adding something for this in the future 😄.

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/133533283-084a74ad-d41a-4c29-9635-a26ec40238b0.png)

https://user-images.githubusercontent.com/1549611/133533730-918555a9-2e5a-4cf9-a3c2-ca1519d2677c.mp4


I found razor editor html code format is not working yet in preview4.
use legacy razor editor it's OK.

**Comment by NTaylorMullen** [comment]
Forgot to close out this since it seems the original issue reported is resolved in 17.0-Preview4.

@neozhu it looks like JavaScript formatting isn't working as expected in your scenario. Mind filing another issue for us to track the work there?
