### ISSUE TITLE
Call JavaScript functions from .NET methods in ASP.NET Core Blazor---function is not a function

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [dotnet/aspnetcore#33146]
### Describe the bug
Calling a js method when prompted that the method being called is not a function.
调用js方法时被提示被调用的方法不是一个方法

### To Reproduce
XX.razor
```
<div @ref="overlay" class="p-autocomplete-panel p-component" >
    <ul>
        <li class="p-highlight"></li>
    </ul>
</div>
```
`await moduleTask.InvokeVoidAsync("findSingle", overlay, "li.p-highlight");`

xxxx.js
```
export function findSingle(element, selector) {
    return element.querySelector(selector);
}
```

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/26154837/120100075-60892d00-c171-11eb-9d31-1236e919b37a.png)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/26154837/120100169-d7262a80-c171-11eb-85ee-3e7443d3e22c.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- IDE:
![image](https://user-images.githubusercontent.com/26154837/120100211-08065f80-c172-11eb-95f2-e09373d3f787.png)

Browser：
![image](https://user-images.githubusercontent.com/26154837/120100270-806d2080-c172-11eb-8897-cdf576a80b5c.png)

**Comment by sps014** [comment]
Can you send bit more code like how are you initializing moduleTask?

**Comment by javiercn** [comment]
@Dean-ZhenYao-Wang thanks for contacting us.

In order for us to make progress on this issue we need a minimal repro project in a github repo and detailed instructions on how to reproduce the issue.

**Comment by Dean-ZhenYao-Wang** [comment]
> @Dean-ZhenYao-Wang thanks for contacting us.
> 
> In order for us to make progress on this issue we need a minimal repro project in a github repo and detailed instructions on how to reproduce the issue.

The problem has been solved.
I added a reference to JQuery in the Index.html file of the VUE project under the solution. The problem no longer occurs.
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+ IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script
