### ISSUE TITLE
Azure AD B2C - Blazor Server Side

### ISSUE THREAD

**Issue by raedg2000** [dotnet/aspnetcore#33157]
Dears,

I am developing a Blazor server side app and using Azure AD B2C. I am having an issue with the signout method. I need to navigate to the home page. Is there a way to modify the  RedirectURl in the signout method of the AccountController?

regards,
Raed

**Comment by javiercn** [comment]
@raedg2000 thanks for contacting us.

We don't handle AAD and AAD B2C authentication in GH in this repo. In order for you to get a faster and better answer we suggest you file an issue on the Microsoft.Identity.Web repo [here](https://github.com/AzureAD/microsoft-identity-web)
