### ISSUE TITLE
Running dotnet watch with a EditForm component with @bind-Value breaks with error "condition `<disabled>' not met"

### ISSUE THREAD

**Issue by ShoarW** [dotnet/aspnetcore#33152]
Running my project I've noticed that the hot reload will exit/crash if it finds a <EditForm> with a @bind-Value inside of it.

Files looks like 
```
<EditForm Model="@Login" OnValidSubmit="HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText @bind-Value="Login.Email" />
    <InputText @bind-Value="Login.Password" />
    <button class="btn btn btn-lg btn-primary" type="submit">Sign in One</button>
</EditForm>

@code {
    private LoginResult Login = new LoginResult();
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount += 30;
    }

    private void HandleValidSubmit()
    {
        Navigation.NavigateTo("/");
    }
}
```

Crashes with when navigating to the page

```
* Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1373, condition `<disabled>' not met
dotnet.6.0.0-preview.4.21253.7.js:1:18291
```

Downgrading the preview packages to Preview 3 (not the SDK) will not crash the application.

I have created a reproduction of the issue here - You will need Preview4 and latest Visual Studio Preview

https://github.com/ShoarW/BlazorHotReloadPreview4

**Comment by mkArtakMSFT** [comment]
@lambdageek do you have a separate issue tracking this already?

**Comment by lambdageek** [comment]
Very strange: the assert is hit when you start the app via `dotnet watch` and navigate to the Counter page - you don't need to edit any code.
That assertion is hit if a managed `AppDomain.CurrentDomain.AssemblyLoad` event throws an unhandled exception.
Does the hot reload agent hook up to that event? /cc @pranavkm

**Comment by pranavkm** [comment]
It does. That sounds like a bug in Blazor's hot reload agent. I'll look at this further.

**Comment by pranavkm** [comment]
I should have a fix out for this soon. The exception is triggered because a "Anonymously Hosted DynamicMethods Assembly" is loaded and accessing it's Module property throws:

```
System.NullReferenceException: Object reference not set to an instance of an object.
blazor.webassembly.js:1    at System.Reflection.Emit.AssemblyBuilder.GetModules(Boolean getResourceModules) in System.Private.CoreLib.dll:token 0x6004ca7+0x0
blazor.webassembly.js:1    at System.Reflection.Emit.AssemblyBuilder.GetLoadedModules(Boolean getResourceModules) in System.Private.CoreLib.dll:token 0x6004caa+0x0
blazor.webassembly.js:1    at System.Reflection.Assembly.get_Modules() in System.Private.CoreLib.dll:token 0x6004778+0x0
```

We can do a better job handling this case, but I'm curious if you happen to know what could be loading that particular assembly? @lambdageek?

**Comment by pranavkm** [comment]
I have a targeted fix that prevents the exception from AssemblyLoad event. Once that is resolved you run in to https://github.com/dotnet/runtime/issues/51855.

**Comment by lambdageek** [comment]
> I should have a fix out for this soon. The exception is triggered because a "Anonymously Hosted DynamicMethods Assembly" is loaded and accessing it's Module property throws:
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
> blazor.webassembly.js:1    at System.Reflection.Emit.AssemblyBuilder.GetModules(Boolean getResourceModules) in System.Private.CoreLib.dll:token 0x6004ca7+0x0
> blazor.webassembly.js:1    at System.Reflection.Emit.AssemblyBuilder.GetLoadedModules(Boolean getResourceModules) in System.Private.CoreLib.dll:token 0x6004caa+0x0
> blazor.webassembly.js:1    at System.Reflection.Assembly.get_Modules() in System.Private.CoreLib.dll:token 0x6004778+0x0
> ```
> 
> We can do a better job handling this case, but I'm curious if you happen to know what could be loading that particular assembly? @lambdageek?


@pranavkm  Those modules are created by [`new DynamicModule (string, Type, Type[])`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.dynamicmethod.-ctor?view=net-5.0#System_Reflection_Emit_DynamicMethod__ctor_System_String_System_Type_System_Type___)   (and probably a few other overloads).

I just tried this in a console app:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

namespace q
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
	    var d = new DynamicMethod ("ababa", typeof(void), new Type[]{ });


	    foreach (var a in AppDomain.CurrentDomain.GetAssemblies()) {
		foreach (var m in a.Modules) {
                    Console.WriteLine ($"{a.FullName}: module {m}, {m.ModuleVersionId}");
		}
	    }
        }
    }
}
```

And on both CoreCLR and Mono it prints out:
```
...
Anonymously Hosted DynamicMethods Assembly: module RefEmit_InMemoryManifestModule, 96267b54-2435-47eb-917a-680e98cf5815
```

So it doesn't seem like there's an obvious bug in `System.Reflection.Emit.AssemblyBuilder.GetModules`.

Is the IL trimmer running for this project? Maybe it is removing some reflection enumeration code that the hot reload agent depends on?

**Comment by pranavkm** [comment]
No trimmer's running during development. More specifically, nothing in the code explicitly creates and loads a dynamically loaded assembly. Perhaps the presence of the anonymous lambda causes one to load and that has different semantics?
