### ISSUE TITLE
How to check a deployed app is using AOT?

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#33163]
This is a question not a bug report. I followed the steps here https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/comment-page-2/#blazor-webassembly-ahead-of-time-aot-compilation to deploy a Blazor WASM app. I see effectively it reports in the output window of visual studio it is AOT'ing, but when I browse the app I see in Chrome developer tools it is downloading the dll's, so my question is whether I'm seeing the interpreted runtime application or AOT? How can I make sure?

**Comment by javiercn** [comment]
@arivoir thanks for contacting us.

The size of the downloaded dlls will be greatly reduced (they essentially only contain the metadata) and all the code is in the wasm file (which will be bigger than the non-aot version)

**Comment by arivoir** [comment]
The only wasm file is downloaded is "dotnet.wasm" is that normal?

**Comment by htdag** [comment]
@javiercn From my test, `dotnet.wasm` bigger ~30MB,
DLLs still contain the original IL (not only the metadata),
![image](https://user-images.githubusercontent.com/40710867/120219685-d2db3980-c265-11eb-9c8a-c76c7fce9382.png)
and if I replace all to opcode `ret` (with dnlib),
I got error, It's not fully AOT?
![image](https://user-images.githubusercontent.com/40710867/120220028-5006ae80-c266-11eb-800f-ca6bd8148457.png)

Note: method called have no reflection.

**Comment by arivoir** [comment]
I'm experiencing very similar results to @htdag The dll's are the full dll, not only metadata, and the dotnet.wasm file is 47.6 MB

**Comment by javiercn** [comment]
@arivoir do you have linking disabled? (looks like that, based on bundle size). Same goes for @htdag

**Comment by htdag** [comment]
@javiercn Same result with `<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>`.

**Comment by arivoir** [comment]
I have no linking setting, only `<RunAOTCompilation>true</RunAOTCompilation>`

**Comment by pranavkm** [comment]
Adding @lewing for visibility.

a) The IL trimming of managed assemblies isn't currently enabled (the runtime team is working thru issues there).
b) Looking at the dotnet.wasm file (larger file size) or the dotnet.$version$.js file (includes funny named functions at the end) should provide hints if the app is AOT compiled.
