### ISSUE TITLE
Blazor: two variables without whitespace in the middle not compiled

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnetcore#33169]
### Describe the bug
In a razor page, we can use:
```
@{ bool useClass1 = true; bool useClass2 = true; }
<div class="class0@(useClass1 ? " class1" : "")@(useClass2 ? " class2" : "")"></div>
```
But in a blazor component, this can't be compiled unless we add an addtional whitespace:
```
@{ bool useClass1 = true; bool useClass2 = true; }
<div class="class0@(useClass1 ? " class1" : "")      @(useClass2 ? " class2" : "")"></div>
```

However, it's strange that this works:
```
<div class="class@(2 > 1)@(? 1 : 0)"></div>
```
just like
```
<div class="class@(2 > 1 ? 1 : 0)"></div>
```

### To Reproduce

```
@{ bool useClass1 = true; bool useClass2 = true; }
<div class="class0@(useClass1 ? " class1" : "")@(useClass2 ? " class2" : "")"></div>
```
### Further technical details
- ASP.NET Core version: 5.x
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@anranruye thanks for contacting us. 

You can't mix markup and literals in Blazor that way. You need to wrap the entire expression wihin `@()`.
