### ISSUE TITLE
DOTNET_URLS on for Kestrel

### ISSUE THREAD

**Issue by X-7r3em** [dotnet/aspnetcore#33175]
I have a plain dotnet new application started with Kestrel on windows (the Project command from VS). I have the Environment Variable DOTNET_URLS, but it does not change the Urls. When I change it to ASPNETCORE_URLS, it changes the urls. When I also say AddEnvironmentVariables("DOTNET_") on ConfigureAppConfiguration it again works. When I try to ConfigureHostConfiguration, 

ASP NET CORE 3.1

### Is your feature request related to a problem? Please describe.
Well, i dont know if this is expected or a problem, some articles in the docs say its expected, some don't. So could you, please, clarify the IHost vs IWebHost configuration constants, which is taken when, with more details, so that I can see why this does not work or works hacky.

### Describe the solution you'd like
I would like to have containers, some of them console apps, some of them web apps. I would like to configure all of the containers with the same DOTNET_ , and not some with DOTNET_ and other with ASPNETCORE_

**Comment by BrennanConroy** [comment]
Can you share your program main?

**Comment by X-7r3em** [comment]
Yes, sorry. Yesterday I was all furry and ughhh :D. This is the repo. I have added Case 1, Case 2 and etc. Each of the cases is intended to run separately. 
https://github.com/X-7r3em/DotnetUrls

**Comment by davidfowl** [comment]
I'm pretty sure this is by design. URLS is an ASP.NET Core specific setting.

**Comment by X-7r3em** [comment]
The thing that bugs me the most is that the AddEnvironmentVariables("DOTNET_") works, but just plain DOTNET_URLS does not. And it would be sooo nice if you could have all the DOTNET and ASPNETCORE prefixes overlap. Situation -> a container. One is a generic host and the other is for a webapp. And then you can configure the env variables with DOTNET_ all the way. Right now, you have to have DOTNET_ and ASPNETCORE_ on separate scripts. This is why I opened it in the features section.

And for my self, we just went with the Use... methods for the Env variables, because we just got pissed due to the complexity of the precedence of the convention. Soo Im leaving this as food for thought.

**Comment by BrennanConroy** [comment]
When you're trying `DOTNET_URLS` do you have an `ASPNETCORE_URLS` set via launchsettings or something else? That would override any `DOTNET_URLS` settings you have.

We can't merge different config values for string values, that would be too big of a breaking change. In your app code you can reference `DOTNET_URLS` and `ASPNETCORE_URLS` manually from config and get the correct values, then you could merge them yourself if you wanted.

**Comment by X-7r3em** [comment]
When you're trying DOTNET_URLS do you have an ASPNETCORE_URLS set via launchsettings or something else? That would override any DOTNET_URLS settings you have. -> no. If you check the repo, they are separate cases. Just DOTNET_URLS, so no overriding from ASPNETCORE_URLS

We can't merge different config values for string values, that would be too big of a breaking change. In your app code you can reference DOTNET_URLS and ASPNETCORE_URLS manually from config and get the correct values, then you could merge them yourself if you wanted. -> we already did that :). The idea is that we have console workers, containers that have a console app (generic host) inside them and docker containers with webapps (web host). They share the same Environment variables, And we wanted to configure the net core stuff with only DOTNET_ instead of a combo between DOTNET_ and ASPNETCORE_ (the same scrips - less errors). I think it would be very convenient if this was possible.

You can close this. But please correct the Generic host and Webhost HC articles so that they do not mislead other people. Also, a really good article on precedence of these conventions would be highly appreciated.

**Comment by BrennanConroy** [comment]
If you enumerate all environment variables is there an ASPNETCORE_URLS value? Visual Studio may be setting it which is overriding the DOTNET_URLS value.

Can you point at which docs specifically are confusing?
