### ISSUE TITLE
It is recommended to add readme to all samples

### ISSUE THREAD

**Issue by sgalcheung** [dotnet/aspnetcore#33171]
When I was running the SignalR sample, I didn't know where to start. After that, I browsed some concepts about SignalR. I learned about Hub. I ran samples/SignalRSample and entered http://localhost:5000/hubs. html, but some errors were reported, and some js files were missing. I found that the file defined by SignalRSamples.csproj was copied from [SignalR/clinets/ts](https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/clients/ts). In the end I solved the problem, but it bothered me for a while and gave me experience Not very good，There are other examples I did not understand, such as samples/ClientSample connection hub error
![image](https://user-images.githubusercontent.com/42566429/120279002-871da400-c2e8-11eb-9710-2f1b2053fffa.png)

**Comment by davidfowl** [comment]
The samples in this repository are really more like test applications for when product changes are made, not samples you would use to learn the product. Those are elsewhere (e.g. https://github.com/aspnet/SignalR-samples for SignalR). That said, I don't have anything against adding readmes for these samples here.

**Comment by sgalcheung** [comment]
I think https://github.com/aspnet/SignalR-samples just a simple example, compared with https://github.com/dotnet/aspnetcore/tree/main/src/SignalR, the latter comprehensive，understand the core of SignalR, what are the functions

**Comment by davidfowl** [comment]
While that's true, its not something that's even runnable without building some piece of the entire repository. The sample exists solely so we can test features that we add to the product (it's more of a test than something to understand).

**Comment by sgalcheung** [comment]
Yes, maybe from https://github.com/aspnet/SignalR-samples first, and then come back to https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/samples, here is a sample that is closer to the source code , I can learn more about SignalR

**Comment by javiercn** [comment]
@sgalcheung thanks for contacting us.

As @davidfowl mentions the samples in these repos are for helping developers on the team test new features quickly. I'm closing this issue since we don't plan to add README files to these projects.

**Comment by davidfowl** [comment]
@captainsafia Any opinions here? I'm not against the readme as it might be helpful to contributors.

**Comment by captainsafia** [comment]
This is the kind of stuff we want to document as part of the top-level READMEs for each project. So for SignalR, here: https://github.com/dotnet/aspnetcore/blob/df47cc793afb6bbc28d4f555bbf8d486cff5ad73/src/SignalR/README.md

Those READMEs are intended to document things that are useful during the local dev loop.
