### ISSUE TITLE
Make BundleMinifier functionality a native MS package

### ISSUE THREAD

**Issue by eat-sleep-code** [dotnet/aspnetcore#33182]
### Is your feature request related to a problem? Please describe.
The [BundlerMinifier project ](https://github.com/madskristensen/BundlerMinifier) was started by a MS employee, but now seems to be abandoned / unmaintained.  

### Describe the solution you'd like
As this lightweight bundler is used extensively in VS Code to Visual Studio, and is very handy, I would love to see it pulled in and be an officially maintained project.

### Additional context
There are a multitude of issues opened on the current repo, and some pull requests to fix issues, but none are addressed.

**Comment by javiercn** [comment]
@eat-sleep-code thanks for contacting us.

Unfortunately this repo only deals with runtime/framework issues and not Visual Studio tooling. For you to get a better and faster answer we suggest you file this issue via Visual Studio [suggest a feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019).

**Comment by eat-sleep-code** [comment]
Thanks for directing me to the correct place!  Wasn't sure where it would fall.
