### ISSUE TITLE
Test failure: ThrowsWhenBindingLocalhostToIPv4AddressInUse

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#33185]
## Error Message

> Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   (No exception was thrown)

## Stacktrace

>    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ThrowsWhenBindingLocalhostToAddressInUse(AddressFamily addressFamily) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 944
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ThrowsWhenBindingLocalhostToIPv4AddressInUse() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 747

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1164357&view=results

**Comment by HaoK** [comment]
Closing stale issue, this test has already been unquarantined https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs#L738
