### ISSUE TITLE
Support for UserInfo Message Level Encryption (Microsoft.AspNetCore.Authentication.OpenIdConnect)

### ISSUE THREAD

**Issue by DumboJet** [dotnet/aspnetcore#33215]
I am trying to authenticate my app against this authority and method that uses MLE (Message Level Encryption):
https://developer.signicat.com/enterprise/docs/authentication/about-oidc.html#finnish-trust-network-ftn-specifics

Quote:
> You should send your requests as a normal OIDC request (see exception below). The difference between a normal OIDC flow and MLE flow are:
> 
> The ID token **and the response from user info** is a nested JWT which is encrypted and signed.
> Decrypt it with your private key from the RSA pair given to Signicat.
> Deserialize the resulting signed JWT and verify the signature.

Extra emphasis on the "**and the response from user info**".

I have managed to make the ID token handling to work by using a custom ISecurityTokenValidator like so:
```
options.SecurityTokenValidator = new SecurityTokenValidator();
```
However, your code fails when parsing the user token here, because the Payload is null (I guess because you need to decrypt the token to get the real payload):

https://github.com/dotnet/aspnetcore/blob/6427d9cc718f8093c506b62b6fd12544411b477f/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L902

(Note: I am getting this error with version 3.1.0 of your `Microsoft.AspNetCore.Authentication.OpenIdConnect` library, but the code seems the same in newer versions)

### Describe the solution you'd like
I guess you should provide a way to decrypt the user info token as well.
```
options.UserInfoTokenValidator = new SecurityTokenValidator();
```

### Additional context
Any ideas for a workaround are welcome.
I am trying to replace the `OpenIdConnectHandler` with my own version now, but I am not sure this is possible... :(
Also, the event callback for `OnUserInformationReceived` is called too late to help me do something with the encrypted token, it seems.

**Comment by blowdart** [comment]
This appears to be a [requirement only for the Finnish Trust Network](https://developer.signicat.com/documentation/finnish-trust-network/full-message-level-encryption-for-ftn/). As such it's not generic enough to be considered for inclusion in the framework. Signicat has a [.NET Core example](https://github.com/signicat/Quick-start-guide-Authentication-.NET-Core), I'd suggest aiming questions that way.

**Comment by DumboJet** [comment]
This is my personal opinion, but I think that your framework should be flexible enough to (at least) allow developers to support this, if not have it supported to begin with.

**What I tried was these:**
At first I was thinking about swapping the `OpenIdConnectHandler` implementation, but I couldn't find a way to do that (I haven't spent much time on that though).
Then I tried providing a custom `HttpClient` (for the `Backchannel` option) that decrypts the tokens internally and returns a decrypted response. Turns out, you use a method of `HttpClient` that is not virtual and I could not affect anything. I could only override the method from the base class (`HttpMessageInvoker`) but that was not used everywhere.
Then I tried using a custom `HttpMessageHandler` and that failed too.

**What seemed to work was this:**
I tried making the call to the useinfo endpoint manually from inside the `OnTokenResponseReceived` event.
Then I decrypted the userinfo, called the `context.HandleResponse();`, and altered the response according to my needs. This will require some custom plumbing it seems, but at least it seems doable.

But this part of the framework is not performance-critical, so providing some hooks for various events to allow changing the behavior should be possible. E.g., in this case, an event for `OnUserInfoResponseReceived` that allows changing the response data would be handy. The current `OnUserInformationReceived` is called too late. It feels to me that the framework is working against you now.

But it is up to you to decide. You can close this issue if you think this adds no extra value.
I have not contacted Signicat for this yet, but I might do if I feel desperate.

**Comment by DumboJet** [comment]
Also, just FYI:
I was told that, despite the fact that only the Finnish Trust Network requires MLE, all Signicat authentication methods support MLE, so we plan on using it on all of them, if all things go well.

**Comment by blowdart** [comment]
@Tratcher do you have any thoughts on what events might support this?

**Comment by Tratcher** [comment]
The UserInformationReceived event is too late, it's just after the code that's failing here. They'd probably need to turn off the built in user-info retrieval and do it themselves in the TokenValidated callback.

**Comment by DumboJet** [comment]
In case I am not bothering you too much, any suggestions on how to make this call succeed:
```
var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
```
...after I get the user claims manually, would be welcome. This is called during the normal flow without MLE.
I guess, during the MLE flow I could also sign the user in directly, from inside the `OnTokenValidated` callback with :
```
await AuthenticationHttpContextExtensions.SignInAsync(context.HttpContext, ...);
```
...but I am trying to keep the flow the same compared to when not using MLE, to avoid making some terrible mistake...
And also to be able to switch between MLE and non-MLE without code changes.

Although, this might be a question that can answered by the IdentityServer4 people, because I see that in the non-MLE flow some temporary cookies with names like "idsrv.externalC1" are added in the response, which seem to be coming from IS4, making the `AuthenticateAsync()` method succeed.
But if you happen to be able to shed some light, it would be great.

**Comment by Tratcher** [comment]
@DumboJet I recommend not calling HandleResponse in this case. You shouldn't need Success either, just let the event complete and the normal logic continue.

**Comment by DumboJet** [comment]
Thank you @Tratcher !
Indeed this works!
I had the impression it didn't, but apparently I was wrong.
