### ISSUE TITLE
CSC : error CS8034: Unable to load Analyzer assembly

### ISSUE THREAD

**Issue by iammelvin** [dotnet/aspnetcore#33222]
I am trying to run my .NET Core 3.1 API project for the first time in visual studio code after restoring nuget packages and when trying to run with the below commands I get error as mentioned and the build fails. 

> dotnet restore
> dotnet run

> C:\Users\X1\.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.2.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll : Assembly with same name is already loaded [C:\Users\X1\IBO\SOS.Notification\Source\Api\Service\Service.Api.csproj]
> 
> The build failed. Fix the build errors and run again.

Need help in resolving this issue with same assembly loading twice.

**Comment by pranavkm** [comment]
That error message usually indicates your app is referencing a 2.2 package. Have you followed the migration instructions at https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio to update all your package references?
