### ISSUE TITLE
Issue when upgrading from .Net 5 to .Net 6

### ISSUE THREAD

**Issue by josebimbo1208** [dotnet/aspnetcore#33229]
### Describe the bug
I upgraded my current blazor web Assembly project to .net 6 and keep getting an error on some razor files saying:  The 'code` directive must appear at the start of the line

### Further technical details
- ASP.NET Core version : 6.0.100-preview.4.21255.9

**Comment by javiercn** [comment]
@josebimbo1208 thanks for contacting us.

Can you provide more details like the visual studio version you are using and so on?

**Comment by josebimbo1208** [comment]
Hi @javiercn , 

My visual studio version is : 16.10.0 (Community) and Im using .net 6 preview 

Yes I get the same error...

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
