### ISSUE TITLE
Support passing list of changed files to msbuild while using dotnet watch run

### ISSUE THREAD

**Issue by belav** [dotnet/aspnetcore#33221]
I'm working on a package that allows [CSharpier](https://github.com/belav/csharpier) to format files in a project on build.
While using `dotnet watch run` it would be ideal to pass just the list of changed files to CSharpier to speed up the formatting. Otherwise it will reformat all files in the project when a single one is saved.

This gives me the list all files in the project.
```xml
<PropertyGroup Condition="'$(DotNetWatchBuild)'=='true'">
    <!-- From the item list Compile, use the FullPath and separate them by a ' ' instead of the default ;-->
    <FilesToFormat>@(Compile->'%(FullPath)', ' ')</FilesToFormat>
</PropertyGroup>
```
Ideally I'd be able to do something like
```xml
<FilesToFormat>@(DotNetWatchChangedFiles->'%(FullPath)', ' ')</FilesToFormat>
```

I found where the file watching occurs, but it doesn't appear that the list of changed files gets passed to msbuild.
https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs

**Comment by shocklateboy92** [comment]
Thanks for your reply @pranavkm. If that's the case, what would be your recommendation for figuring out which files to act on?
Is there some other way of hooking into dotnet watch to get the list of files out of it?

**Comment by pranavkm** [comment]
There's some discussion about a similar problem in https://github.com/dotnet/aspnetcore/issues/27555.  In their case, they're hosting a separate file watcher (e.g. WebPack HMR) to solve their problem. 

Our thought was to possibly enhance dotnet-watch with the ability to invoke custom msbuild targets or executables as a reaction to changed fil, but it's not something we've put serious thought to as yet.

**Comment by belav** [comment]
Thanks for the information @pranavkm, I have some ideas for how to move forward.
