### ISSUE TITLE
Running multiple projects under `dotnet watch run` causing the 3rd to go into a loop build

### ISSUE THREAD

**Issue by zoinkydoink** [dotnet/aspnetcore#33234]
3 projects
1. blazor - .NET 6.0 Preview 4
2. aspnet core api  - .NET 6.0 Preview 4
3. aspnet core api - .NET 6.0 Preview 4

opened 3 terminals in visual studio 2019 16.11 Preview 1
launched the first 2 with `dotnet watch run`
when running the 3rd one with same command it goes into a infinite build.

if it makes a difference, i have another c# project that all 3 of the above project reference.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
