### ISSUE TITLE
BuildRequstDelegate() is a typo

### ISSUE THREAD

**Issue by dodyg** [dotnet/aspnetcore#33243]
https://github.com/dotnet/aspnetcore/blob/836b622bf9bb98bfd59d95838470bb1351d32368/src/DefaultBuilder/src/WebApplication.cs#L169

**Comment by javiercn** [comment]
@dodyg thanks for contacting us.

Feel free to send a PR if you are interested in fixing it.

**Comment by rbrishabh** [comment]
I can submit a PR :)
