### ISSUE TITLE
[Blazor Server] API Endpoint Not Accessible on All Servers

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#33261]
### Describe the bug
I have an API endpoint in a Blazor server app that is accessible locally and on one server but not a second server. On the second server, instead of accessing the API controller at the specified URL, I get Blazor instead.

### To Reproduce
The code is the same locally, on server A, and on server B. The servers are Windows with Apache. I'm not sure whether anything with the server setup could make the API controller route "invisible", but the website .conf files are the same on both servers.

From Startup.cs, Configure():
```
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();

app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub();
    endpoints.MapHub<MyHub>("/myhub");
    endpoints.MapControllers();
    endpoints.MapFallbackToPage("/_Host");
});
```

From the API controller at external/MyApiController.cs:
```
[ApiController]
[Route("external/[controller]")]
public class MyApiController : ControllerBase { ... }
```

The api controller is access at `/external/MyApi`.

### Exceptions (if any)
No exceptions or error messages

### Further technical details
- ASP.NET Core version: 5.0.6
- VS Mac: 8.10 Preview 5

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

We suggest you start by cranking up the logs to the Debug level to see the routing resolution in both servers or anything else that might cue you to why this is happening.

**Comment by mrlife** [comment]
@javiercn thanks for the suggestion. I checked the Windows Event Viewer and saw a null reference exception (uses different database than local and other server) occurring in the API Controller, so I fixed that, and it's working now. It does make me wonder why Blazor would come into play instead of just erroring out. Any ideas?

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @mrlife.
There doesn't seem to be any issues here related to Blazor. If you have any specific issue related to the framework, please file a new issue.
