### ISSUE TITLE
Passing an object(cyclic) as parameter to a Razor component via the component tag helper throws JsonException

### ISSUE THREAD

**Issue by zmp2000** [dotnet/aspnetcore#33287]
This issue was well reported here #32150 

But the answer from @javiercn clearly doesn't satisfy-me and probably no one.

If it's "by design" it's a shit design, the problem remains when THERE IS NO OPTION to end the Cycles.
By explicit adding Newtonsoft as Json option should solve this, but nothing changes by adding any of the 3 following codes:

`services.AddControllers().AddNewtonsoftJson();
         services.AddControllersWithViews().AddNewtonsoftJson();         
         services.AddRazorPages().AddNewtonsoftJson();`

The Cycle excpetion still point out to System.Text.Json.JsonException

This simple make impossible to solve the problem as an object with cycle reference is a NORMAL situation using the very best ORM frameworks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't support serialization for cyclic references.
You can use other methods to serialize this yourself - like strings.

**Comment by zmp2000** [comment]
Ok, How can I serialize it by my self? How can I change or intercept the default serialization mechanism when passing an object as a parameter? I mean, globally.
