### ISSUE TITLE
Blazor scoped CSS vs Dynamic loaded razor class library 

### ISSUE THREAD

**Issue by dirething** [dotnet/aspnetcore#33284]
I have blazor server app that uses pages from runtime loaded libraries.  The pages work fine, and if I look at a decompile of the page classes I see the scoping attributes that the scoped css in my [pageName].razor.css are meant to be linked to.  What I do not see is the ~/_content/[className]/[className].bundle.scp.css being returned from the server or any evidence that it is embedded in the dlls in the first place.  the documentation says that the css is bundled at compile time, so I assumed it meant when the library was compiled.  After spending about a week looking for what I might be doing wrong I came across the following comment:

We don't embed anything into the assembly, the outputs are just static web assets that get bundled into nuget packages.
...
The only thing that we do across packages is bundle css in the host project/wasm app project.

_Originally posted by @javiercn in https://github.com/dotnet/aspnetcore/issues/10170#issuecomment-668104650_

assuming that is still accurate it would seem I have been wasting my time because this use case was not covered when the css isolation was designed.

is this accurate? and if so is the best I can do here is stick large <style> blocks into the pages themselves or am I missing something here?

**Comment by javiercn** [comment]
@dirething thanks for contacting us.

> What I do not see is the ~/_content/[className]/[className].bundle.scp.css being returned from the server or any evidence that it is embedded in the dlls in the first place. the documentation says that the css is bundled at compile time, so I assumed it meant when the library was compiled. After spending about a week looking for what I might be doing wrong I came across the following comment:

If your app doesn't have a project or package reference to the `RCL` and you are loading the dll via `Assembly.LoadFromFile` or similar, we don't have any way of knowing that there is a CSS file at all.

This is not a scenario we support, so you would have to figure out a process to bring the bundle into your final app in the same way you are doing with the assembly.

**Comment by dirething** [comment]
Thanks for the reply & glad I can end that wild goose chase.

You mention creating a "process to bring the bundle into the final app" - I am ok with writing more plumbing for this, but it seems like I am missing something.  The \obj\[build]\net5.0\scopedcss folders seem to be the only place that has the library's scoped matched css but something also reference them when rebuilding the host application's css doesn't it?  

Is that part doing anything important besides getting the all of the css in scope? or is collecting all of the various scoped files and adding them individually as links in the _Host.cshtml achieve the same effect?

**Comment by dirething** [comment]
I had not seen that this auto-closed over the weekend, but I have since collected the css from the obj folders and added it programatically to the _host.  It appears to work, but i am still not sure if I am missing something about how it is intended to work or not and I am not certain if they are intended to always be included or only conditionally be included depending on your route or something.  Perhaps @javiercn can comment further.
