### ISSUE TITLE
InputNumber: support for binding to all integral numeric types (byte, ushort, uint, etc.)

### ISSUE THREAD

**Issue by dmoncada** [dotnet/aspnetcore#33293]
### Describe the solution you'd like
To be able to bind an `InputNumber` component to a property of type, for ex. `uint`, or `ushort`, etc:

```
<InputNumber @bind-Value="MyProp" />

@code
{
    private uint MyProp { get; set; }
}
```

### Additional context
Currently `InputNumber` implements a `static` constructor with a big `if` that checks the type of the bound property. However, several integral numeric types are left out of the check (perhaps arbitrarily?), which prevents the component from being bound to, for ex. `uint` like in the snippet above. Also, the fact that this check is done in a `static` constructor makes it difficult to override this behavior by deriving from `InputNumber`.

All integral types; those supported by `InputNumber` are checked ([link][ints]):
- [ ] `sbyte`
- [ ] `byte`
- [x] `short`
- [ ] `ushort`
- [x] `int`
- [ ] `uint`
- [x] `long`
- [ ] `ulong`

[ints]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#integral-types

**Comment by mkArtakMSFT** [comment]
We've seen multiple similar issues in the past and have addressed those which had engagement from the community. At this point we think we've tackled the set of scenarios that customers were really interested in.
We'll keep an eye on similar feedback in the future and if there is something specific that customers would like us to add support for, we'll consider it then.
