### ISSUE TITLE
.netcore5  request.Host.value bug or leak?

### ISSUE THREAD

**Issue by byerror** [dotnet/aspnetcore#33308]
version: .netcore5.1 
I found a user can visit my site, event though my project only bind to port 9000  from local to  router WAN(see img below).
It shows that hacker can vist my site use port 80 and in the console make the request.Host.value shows it's IP or HOST?

### here is the .netcore source code I found in HostingRequestStartingLog.
`private const string LogPreamble = "Request starting ";` 
 ` _cachedToString = $"{LogPreamble}{request.Protocol} {request.Method} {request.Scheme}://{request.Host.Value}{request.PathBase.Value}{request.Path.Value}{request.QueryString.Value}`

😢  5.188.210.227 is not my Server's IP, and my project have nothing releate to php。

![1](https://user-images.githubusercontent.com/3293632/120883910-8cddf700-c612-11eb-902d-7a218ccface8.png)

**Comment by blowdart** [comment]
Is 5.188.210.227 your router IP by any chance?

I wouldn't worry about php being present, people scan the internet for all sorts of things and don't target specific web servers, but rather try everything they can on every IP they find, and that's what you're seeing here. The port, the ip address, they're all outside of the connection itself, they're part of the HTTP protocol, so a tool will see a web server listening on port 9000 at your router, open a socket to it, and start sending commands which a browser normally wouldn't. You can, for example, open a socket to 10.0.0.1 and then use the host header in a request to request another IP address, different to the connection. Badly configured proxies will sometimes forward those on.

@Tratcher maybe the log should log the port, even if it is the default for the protocol, for clarity?

**Comment by byerror** [comment]
> Is 5.188.210.227 your router IP by any chance?
> 
> I wouldn't worry about php being present, people scan the internet for all sorts of things and don't target specific web servers, but rather try everything they can on every IP they find, and that's what you're seeing here. The port, the ip address, they're all outside of the connection itself, they're part of the HTTP protocol, so a tool will see a web server listening on port 9000 at your router, open a socket to it, and start sending commands which a browser normally wouldn't. You can, for example, open a socket to 10.0.0.1 and then use the host header in a request to request another IP address, different to the connection. Badly configured proxies will sometimes forward those on.
> 
> @Tratcher maybe the log should log the port, even if it is the default for the protocol, for clarity?

5.188.210.227 is hacker's IP,not Router。 So use proxy or socket could make it happend  and then passthrough the  limit of TCP?  
Eg:  my site local address--->>  http://localhost:9000  WAN(public) address: http://1.1.1.1:9000 
       the request.Host.Value show in the Console  will may be http://222.222.222.222:80 ?  that's horrible! Anyway,thanks for your reply.

**Comment by Tratcher** [comment]
The Host header is a field the client can set to anything they want, you need to check the  connection remote and local IP fields if you want to find out where it came from and where it was sent to.

The Host validation middleware can be used to filter out spammy requests like this. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/host-filtering?view=aspnetcore-5.0

**Comment by byerror** [comment]
> The Host header is a field the client can set to anything they want, you need to check the connection remote and local IP fields if you want to find out where it came from and where it was sent to.
> 
> The Host validation middleware can be used to filter out spammy requests like this. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/host-filtering?view=aspnetcore-5.0

You are right,but I'm confused yet. If someone change the request host in the header, then the packet should  never arrive to the real host. Am I miss something?
Eg: `  request header>>
GET /login HTTP/1.1
Host: www.gggg.com
Connection: Keep-Alive
`
If Host www.gggg.com change to www.aaaa.com ，then how TCP packets can  arrive to gggg.com? 
thank you for your help.

**Comment by Tratcher** [comment]
HTTP header fields are not use for TCP level routing, though they may be used if your server is behind a level 7 reverse proxy. In many cases the client is making a direct TCP connection to your server, or to your firewall which forwards all traffic on specific ports without reading it. The main purpose of the Host header is to disambiguate in the application if your server is hosting multiple sites on one port. It should match the DNS Host value used to find your IP address, but it doesn't have to.

**Comment by blowdart** [comment]
Think of it like this. Your IP address is like your street address, the attacker walks up to your house, then takes out a letter addressed to someone else and puts it in your mailbox to see what happens. The first part is opening a connection, the address on the letter is the HTTP header fields. They're separate making the connection, or walking to the house, that has already happened before you open your mailbox and see a mis-addressed envelope.

**Comment by byerror** [comment]
@Tratcher thank you very much.
