### ISSUE TITLE
how to register callback on tls clientHello

### ISSUE THREAD

**Issue by yuzd** [dotnet/aspnetcore#33309]
i want to get clientHello Frame to generator SSL Fingerprinting

**Comment by davidfowl** [comment]
Take a look at this sample https://github.com/microsoft/reverse-proxy/tree/2fd46596c7cc370660f024e442ac3c8c00b88acf/testassets/ReverseProxy.Direct

**Comment by yuzd** [comment]
@davidfowl nice ! thanks

**Comment by yuzd** [comment]
@davidfowl  how to get parase all extensionData  to list ?

**Comment by davidfowl** [comment]
https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Utilities/TlsFrameHelper.cs#L98
