### ISSUE TITLE
Blazor WebAssembly error when running using `dotnet watch`: condition `<disabled>' not met

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#33319]
Repro steps:

- Install .NET 6 Preview 4 SDK
- `dotnet dev-certs https --trust`
- `dotnet workload install microsoft-net-sdk-blazorwebassembly-aot`
- Clone https://github.com/SteveSandersonMS/PictureFixer
- From the Server directory run `dotnet watch`
- When the app loads, click on the Tennis player image 

Expected result:

Tennis player edit page loads fine.

Actual result:

```
dotnet.6.0.0-preview.4.21253.7.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1373, condition `<disabled>' not met
543344 @ dotnet.6.0.0-preview.4.21253.7.js:1
```

Workaround:

Run the app using `dotnet run` instead of `dotnet watch`

**Comment by danroth27** [comment]
This also repros for me with the latest .NET 6 Preview 5 candidate build.

@lewing @lambdageek

**Comment by lambdageek** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/33152, I think. @pranavkm do you know if your fix made it into Preview 5 builds yet?

**Comment by pranavkm** [comment]
I unfortunately hadn't considered porting it to p5 when I made the fix to the other issue. The change is in main and it's a bit late now to for a p5 fix. I'll verify the fix with the latest SDK and close as appropriate.

**Comment by danroth27** [comment]
This still repros for me with .NET 6 Preview 6 (6.0.100-preview.6.21315.23)

https://github.com/danroth27/PictureFixer/tree/net6p6

**Comment by danroth27** [comment]
Actually, I'm not 100% sure I reproduced this correctly. Closing until I can repro for sure.
