### ISSUE TITLE
Select asp-for incorrect behavior / Bug

### ISSUE THREAD

**Issue by ollie10** [dotnet/aspnetcore#33323]
Good Morning,

I think I have found a bug in the **select asp-for** tag helper.

I'm generating a List of **ListItem** in the controller and I'm passing the selected value via the a property of my **Model**.
Here is an image of the QuickWatch, I preselect willingly the first item

![image](https://user-images.githubusercontent.com/10867372/120919401-b0a84800-c6b9-11eb-9ee0-2805408a9947.png)

The **ListItem**s arrive correctly to the view as shown here

![image](https://user-images.githubusercontent.com/10867372/120919491-34facb00-c6ba-11eb-9d46-c908c4a4fff3.png)

But once is rendered is rendered with another value preselected

```
<select class="form-control bg-transparent pl-0 selectpicker d-flex align-items-center sortby" data-style="bg-transparent px-1 py-0 lh-1 font-weight-600 text-body" data-val="true" data-val-required="The Status field is required." id="Status" name="Status">
<option value="0">View All</option>
<option selected="selected" value="1">Active</option>
<option value="2">Expired</option>
<option value="3">Sold</option>
<option value="4">Hidden</option>
</select>
```

### Further technical details
- ASP.NET Core version 5
- Visual Studio 2019 16.10.0
- Dotnet Info
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ollie10** [comment]
After a further investigation I realized what was the problem.
The model has two properties one with the value and one with the SelectItems, even if I preselect the SelectItem the renderer selects always the value used in the model, so changing this it worked.
What I don't know it is if in a
`<select asp-for="Status" asp-items="Model.StatusList">`

 should prevail the value of the model instead the **SelectedValue** in **asp-items**

**Comment by mkArtakMSFT** [comment]
Glad that you've been able to resolve the issue yourself. At this point it seems there are no any pending actions here so we'll close this issue.
As for your question, we'd prefer not to change the behavior at this time.
