### ISSUE TITLE
.net 6 Preview 4: Published WEB API not working when deploy to single file self contained

### ISSUE THREAD

**Issue by urza** [dotnet/aspnetcore#33326]
.net 6 Preview 4
Visual Studio 16.11.0 Preview 1.0

Create new asp.net core WEB API project with:
- swagger enabled
- not setup for https

Publish it with these options:

- produce single file
- Enable ReadyToRun
- Trim unused assemblies

![image](https://user-images.githubusercontent.com/189804/120936599-e9bbd900-c708-11eb-84a8-286ff5ed111e.png)

Run compiled .exe, it starts listening on localhost:5000
visit localhost:5000 in browser,
**Expected**: API working on localhost
**Actual behaviour**: 404 reposponse, the same for swagger docs index

**Comment by urza** [comment]
So it seems that localhost:5000/wheatherforecast works, probably my mistake, but localhost:5000/swagger/index.html returns 404

**Comment by Pilchie** [comment]
@urza - can you share your project file?  @vijayrkn - do you know what trimming is actually enabled by that checkbox? I believe the default changed in .NET 6 SDKs.

**Comment by Pilchie** [comment]
@urza if you look in the output window, are there any trim warnings?

**Comment by urza** [comment]
> @urza - can you share your project file? @vijayrkn - do you know what trimming is actually enabled by that checkbox? I believe the default changed in .NET 6 SDKs.

It's really just the default WEB API core project.. csproj file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

</Project>
```

**Comment by Pilchie** [comment]
Hmm, I would have expected checking those to add properties to the `PropertyGroup` there, but maybe VS only specifies the properties on the command line when you publish.

**Comment by urza** [comment]
> @urza if you look in the output window, are there any trim warnings?

Nothing obvious, but there is a lot of output during publish, so not sure. This is at the beginning when publishing:

```
--singlewarn- "API6"
-out "obj\Release\net6.0\win-x64\linked"
--nowarn "1701;1702;IL2026;1701;1702;2008;IL2041;IL2042;IL2043;IL2056;IL2045;IL2046;IL2050;IL2032;IL2055;IL2057;IL2058;IL2059;IL2060;IL2061;IL2096;IL2062;IL2063;IL2064;IL2065;IL2066;IL2067;IL2068;IL2069;IL2070;IL2071;IL2072;IL2073;IL2074;IL2075;IL2076;IL2077;IL2078;IL2079;IL2080;IL2081;IL2082;IL2083;IL2084;IL2085;IL2086;IL2087;IL2088;IL2089;IL2090;IL2091;IL2092;IL2093;IL2094;IL2095;IL2097;IL2098;IL2099"
--warn "5"
--warnaserror- --warnaserror ";NU1605"
--feature System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization false
--feature System.Resources.ResourceManager.AllowCustomResourceTypes false
--feature System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization false
--feature System.StartupHookProvider.IsSupported false
-b
--trim-mode link
--action copy
--skip-unresolved true 

Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\xxx\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.0-preview.4.21253.7\tools\crossgen2.exe --targetos:windows
--targetarch:x64
-O
```

**Comment by Pilchie** [comment]
Okay, the `--trim-mode link` is the important one.  From the [docs](https://docs.microsoft.com/dotnet/core/deploying/trimming-options#trim-additional-assemblies), this is doing member level trimming. We haven't done the work to make this work correctly yet (and it's not clear if it will be finished in .NET 6).

You may be able to get this working by switching to assembly trimming, or by specifying different behavior for particular assemblies as described in that documentation.

(Tagging @davidfowl too)

**Comment by urza** [comment]
Ok I understand, thanks. It would be really great to have member level trims for .net 6

**Comment by davidfowl** [comment]
I thought we were only trimming the framework itself not dependencies. I'm not sure why the swagger page isn't working but the scenario is untested

**Comment by Pilchie** [comment]
Based on the docs I pointed to above, only assemblies marked with `[AssemblyMetadata("IsTrimmable", "True")]` should be being trimmed, and I don't think any of ours are, so it's not clear to me why swagger wouldn't work either.

**Comment by vijayrkn** [comment]
> Hmm, I would have expected checking those to add properties to the `PropertyGroup` there, but maybe VS only specifies the properties on the command line when you publish.


These publish properties are persisted to the publish profile under Properties\PublishProfiles\<profilename>.pubxml. The equivalent of checking the checkbox is setting the msbuild property `PublishTrimmed` to true. This issue has some additional details on trim specific changes for .NET 6.0+ - https://github.com/mono/linker/issues/2011

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The swagger endpoint is added only in the Development environment and that's intentional. The fact that the weatherforecast endpoint works proves that things work as expected. Here is the code in template showing the check: https://github.com/dotnet/aspnetcore/blob/3d9b8f40fc220a2568447059e129df88150257b8/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Startup.cs#L80
