### ISSUE TITLE
Blazor: Hot reload and WASM pre-render do not work together

### ISSUE THREAD

**Issue by jburman** [dotnet/aspnetcore#33320]
App. is asp.net core hosted WASM app. with WebAssemblyPrerendered enabled.

Steps to repro. the issue...
1) Updated from .net 5 to use .net 6 preview 4. 
2) At this point, running dotnet watch run works as expected (browser refreshes and shows updates as files change)
3) Added hotReloadProfile aspnetcore to the Server app's run profile
4) Running dotnet watch run indicates that hot reload is now enabled.
5) Making a change triggers hot reload, however the update does not display in the web browser.
6) Manually refreshing the page in the browser will briefly show the changed version and then it reverts back to the old version.
7) Ctrl-R in the terminal will reload the app and show the changes.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
