### ISSUE TITLE
SpaServices Middleware has a slight incompatibility with yarn passthrough syntax

### ISSUE THREAD

**Issue by MeikTranel** [dotnet/aspnetcore#33337]
### Describe the bug
When using yarn as a package manager during development yarn prints out a warning thats automatically escalated to an error with the following message:
```log
fail: Microsoft.AspNetCore.SpaServices[0]
      warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

### To Reproduce
Start with the `angular` aspnetcore template and switch out the packagemanagercommand like this:
```csharp
app.UseSpa(spa =>
{
    if (env.IsDevelopment())
    {
        spa.Options.PackageManagerCommand = "yarn";
        spa.UseAngularCliServer(npmScript: "start");
    }
});
```
Yarn seems to have moved on with the passthrough syntax, warns about it and the SpaServices Middleware escalates the issue to a fail log entry.

The actual passthrough syntax is triggered here:
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Spa/SpaServices.Extensions/src/Npm/NodeScriptRunner.cs#L45
called by this:
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Spa/SpaServices.Extensions/src/AngularCli/AngularCliBuilder.cs#L60-L67

### Further technical details
`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We've moved away to a model where we rely on SPA framework provided proxy logic. You can read more about it at https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#improved-single-page-app-spa-templates

That said, we don't plan to address this issue in earlier versions of the framework so closing this issue.
