### ISSUE TITLE
Blazor: #32901 breaks a JS invocation from the IAsyncDisposable.DisposeAsync method

### ISSUE THREAD

**Issue by pos777** [dotnet/aspnetcore#33336]
Hello,

It looks like the https://github.com/dotnet/aspnetcore/pull/32901 fix breaks an existing blazor component.
The issue is related to https://github.com/dotnet/aspnetcore/pull/32901#issuecomment-850500538.
In .NET 5 I have to handle the TaskCanceledException exception when invoke any JS inside the `IAsyncDisposable.DisposeAsync` to process component's disposing when a browser page is closed (https://github.com/pos777/Blazor_DisposeAsync_Sample/blob/632378bc60e8e1930b73a273c417f61458018b62/NET5/NET5/Shared/TestComponent.razor#L13):
```
async ValueTask IAsyncDisposable.DisposeAsync()
{
    try
    {
        await JS.InvokeVoidAsync("console.log", "TestComponent.DisposeAsync");
    }
    catch (TaskCanceledException) { }
}
```
This code does not work under .NET 6. The JSDisconnectedException exception occurs in .NET 6.
Since the JSDisconnectedException is a new class and it is not available in .NET 5, I cannot handle it in .NET 5. 
I need to keep using the net5.0 target in my component library project. But it should also work in .NET 6.  Please advise, how it is supposed to process the scenario?

### To Reproduce

.NET 5: 
- Run the [Blazor_DisposeAsync_Sample\NET5.sln](https://github.com/pos777/Blazor_DisposeAsync_Sample/blob/master/NET5/NET5.sln) project;
- Refresh a browser page;
- Wait for a while;
- There is no error in log.

.NET 6:
- Run the [Blazor_DisposeAsync_Sample\NET6.sln](https://github.com/pos777/Blazor_DisposeAsync_Sample/blob/master/NET6/NET6.sln) project;
- Refresh a browser page;
- The unhandled JSDisconnectedException exception is logged.
![image](https://user-images.githubusercontent.com/5260725/120996932-7315ee80-c78f-11eb-8034-8b895e0969c1.png)

### Exceptions
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'DTYIfmJRu2-bAa8jKA_vxbF6NESzfXcAYlgt5ZPDRgY'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId) in Microsoft.AspNetCore.Components.Server.dll:token 0x6000245+0x1a
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args) inMicrosoft.JSInterop.dll:token 0x600003a+0xda
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) in Microsoft.JSInterop.dll:token 0x6000039+0x48
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) in Microsoft.JSInterop.dll:token 0x6000046+0x82
         at NET6.Shared.TestComponent.System.IAsyncDisposable.DisposeAsync() ind:\NET6\NET6\Shared\TestComponent.razor:line 11
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|62_0(List`1 tasks) in Microsoft.AspNetCore.Components.dll:token 0x6000248+0x91
```

### Further technical details
```
C:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21306.2
 Commit:    c83bef2f34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21306.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21306.1
  Commit:  5b8e1780ad

.NET SDKs installed:
  2.1.524 [C:\Program Files\dotnet\sdk]
  2.1.815 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21306.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21306.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21306.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21305.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Thanks,
Ilya

**Comment by SteveSandersonMS** [comment]
One option is that you can make your class library multitarget both `net5.0` and `net6.0`. Then, you can use `#if` [like this](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) to have a conditional block of code that references `JSDisconnectedException` and applies only in .NET 6.

Alternatively if you don't want to multitarget, you could do something like this:

```cs
            try
            {
                // ...
            }
            catch (Exception ex) when (ex.GetType().Name == "JSDisconnectedException")
            {
                // ...
            }
```

**Comment by pos777** [comment]
Hello @SteveSandersonMS,

Thank you for your answer.
As I see in the https://github.com/dotnet/aspnetcore/pull/32901#issuecomment-847247434, people with existing code were taken into account. I want to point that this change affects these people too. And it may be difficult to find places in existing code that should be updated. Moreover, such "broken" code may be in third-party libraries, where you cannot update the code.
I understand that the `JSDisconnectedException` exception exactly determines the scenario with disconnected browser. But may be there is another solution for the original issue (https://github.com/dotnet/aspnetcore/issues/32808) that will not require existing code update?

**Comment by SteveSandersonMS** [comment]
@pos777 Unfortunately I don't have a suggestion for a different solution. Delaying disposal by 1 minute is not a good situation to be in, so something will have to change to make the call end sooner, and that can only be an exception since there is no successful result we can supply.

If we do hear a lot of customer feedback that this is problematic, we could consider having some kind of back-compat switch that just disables the change (and brings back the original problem from before). However if this only affects a small number of people it would be much better to fix those particular applications.

> Moreover, such "broken" code may be in third-party libraries, where you cannot update the code.

Are there specific libraries that are concerning? I'd be happy to get in touch with the library owners to help them produce an updated version that behaves correctly.

**Comment by pos777** [comment]
@SteveSandersonMS 

> Delaying disposal by 1 minute is not a good situation to be in

Totally agree. But you can throw the `TaskCanceledException` instead of the `JSDisconnectedException` =) Although it looks like a hack.

> Are there specific libraries that are concerning?

I have notified all I know =) May be some entry in the [Breaking changes in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0) article will cover more interested people. May be there is appropriate place in documentation that should be updated.

Ok, I'll use the https://github.com/dotnet/aspnetcore/issues/33336#issuecomment-862425579 solution. Thank you for your help.
