### ISSUE TITLE
Microsoft.SourceBuild.Intermediate NuGet package is not getting published in official CI

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#33343]
This is related to the recent changes to add a ArPow SourceBuild leg to CI in https://github.com/dotnet/aspnetcore/pull/32790.

In the official CI builds, the Microsoft.SourceBuild.Intermediate NuGet package that gets created is not getting published.  This is necessary for the source-build legs of downstream repos that depend on ASP.NET Core.

I speculate this is a simple issue of not passing the `_PublishArgs` into the source-build job.  In order to implement this, https://github.com/dotnet/source-build/issues/2151 must be fixed first.

cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
@MichaelSimons is there any action items we need to do here? Or is this a tracking issue for dotnet/source-build only?

**Comment by MichaelSimons** [comment]
@JunTaoLuo, this is something we are going to need your help with.  I took a look and the issue wasn't what I thought it was.
