### ISSUE TITLE
The default ASP.NET Core 5 react template doesn't work in a LAN on iOS or MacOS Safari

### ISSUE THREAD

**Issue by Ziriax** [dotnet/aspnetcore#33349]
### Describe the bug

When creating an ASP.NET Core 5 React web application with the default template, trying to connect to the Kestrel server running on a Windows machine from an iOS or MacOS device in the LAN with Safari doesn't work. It works fine on Android and Windows machines. The environment is `Development`.

Enabling ASP.NET Core debug log levels doesn't print any errors or warnings.

Creating a React app with `npx create-react-app` and enabling SSL with `HTTPS=1` and installing a dev certificate with [mkcert.exe](https://github.com/FiloSottile/mkcert) works fine on all devices, so it doesn't seem to be a network configuration related issue. 

We also tried in 3 different offices with different routers, all the same.

### To Reproduce

- On Windows, start a command prompt
- install `dotnet 5.0.300`
- create a new React web project, e.g. `dotnet new react -o WebSpaTest && cd WebSpaTest`
- run the project with `dotnet run --urls https://*:5001`
- open a web browser and ensure that `https://localhost:5001` works
- use `ipconfig` to figure out the server's IP address in your LAN, e.g. `192.168.1.23`
- open a web browser and ensure that `https://192.168.1.23:5001` works
- now open Safari on iOS, and navigate to `https://192.168.1.23:5001`

Observe the error:
```
Safari cannot open the page.
The error was: "cannot parse response"
```

Enabling debug logging doesn't print any errors or warnings.

### Workaround

It seems the SPA proxy in `Startup.cs` is the culprit.

The workaround is basically:
- disable the proxy in `Startup.cs`
- run the SPA separately, by setting up CORS to the API in a `ClientApp/src/setupProxy.js` 
- enable CORS to the SPA in `Startup.cs`
- use `mkcert.exe` to generate a certificate that is used by both the Kestrel API and the React SPA. This is the crucial part, iOS doesn't like it otherwise.

This workaround has the following advantages:
- loads much faster since no proxy is involved
- allows separate development of the C# and JS code (especially faster when doing typescript, `npm start` can be slow)

If needed I can provide the source code for the workaround on github.

### Further technical details
```
iOS version 14.5.1

.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.2.206 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This scenario is not supported because of security reasons.
Non-published sites won't be accessible. If you want them to be accessible you should publish the app (which will not use the proxy logic).
