### ISSUE TITLE
Incorrect code generated when using component with generic type constraints

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#33357]
### Describe the bug

The new generic type constraints feature generates invalid code when a component with constrained type parameters is invoked.

Suppose you have a component with constraints on the generic type param like:

```razor
@typeparam TItem where TItem : PictureFixer.Shared.Image

@if (Items == null)
{
    <div class="loading">
        <img src="spinner.gif" alt="Loading indicator" /> Loading
    </div>
}
else
{
    <div class="m-4 my-5 grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        @foreach (var image in Items)
        {
            @ChildContent(image)
        }
    </div>
}

@code {
    [Parameter]
    public RenderFragment<TItem> ChildContent { get; set; }

    [Parameter]
    public IEnumerable<TItem> Items { get; set; }
}
```

And the component is used like so:

```razor
<ImageList Items="@images">
    <ImageListItem Image="@context"/>
</ImageList>

@code {
    private EditableImage[] images;
}
```

The generated class associated with ImageList.razor will have the type constraints correctly generated.

```csharp
    public partial class ImageList<TItem> : Microsoft.AspNetCore.Components.ComponentBase
    where TItem : PictureFixer.Shared.Image
    {
```

But when the image list component is instantiated, the following code is generated:

```csharp
__Blazor.PictureFixer.Client.Pages.Home.Index.TypeInference.CreateImageList_0
```

And the referenced `CreateImageList_0` method does _not_ have the constraints defined:

```csharp
    internal static class TypeInference
    {
        public static void CreateImageList_0<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Collections.Generic.IEnumerable<TItem> __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment<TItem> __arg1)
        {
        __builder.OpenComponent<global::PictureFixer.Client.Pages.Home.ImageList<TItem>>(seq);
        __builder.AddAttribute(__seq0, "Items", __arg0);
        __builder.AddAttribute(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }
    }
```

So the mapping fails when passing the unconstrained generic TItem in the method to the constrained `ImageList` element.

Adding the type constraint to the method appears to fix the issue locally:

```csharp
public static void CreateImageList_0<TItem>(
  global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0,
  global::System.Collections.Generic.IEnumerable<TItem> __arg0, int __seq1,
  global::Microsoft.AspNetCore.Components.RenderFragment<TItem> __arg1) 
  where TItem : global::PictureFixer.Shared.Image // this is the key bit
```

So it looks like we might need to generate the constraint at the method site as well.

### To Reproduce

https://github.com/captainsafia/PictureFixer/tree/safia/foo

### Exceptions (if any)

```
/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/_Pages_Home_Index_razor.cs(180,82): error CS0314: The type 'TItem' cannot be used as type parameter 'TItem' in the generic type or method 'ImageList<TItem>'. There is no boxing conversion or type parameter conversion from 'TItem' to 'PictureFixer.Shared.Image'.
```

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21269.6
 Commit:    222644b6db

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.4
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /Users/captainsafia/.dotnet/sdk/6.0.100-preview.6.21269.6/

Host (useful for support):
  Version: 6.0.0-preview.6.21269.1
  Commit:  c0a1734094

cc: @javiercn

**Comment by javiercn** [comment]
@captainsafia quick question.

Does this happen only with the new syntax or does it also reproduce if you specify the constraints in a code-behind class?

**Comment by captainsafia** [comment]
Only with the new syntax. It works with a code behind class.

Are we expecting people to still be passing the item type with the new syntax?

```
<ImageList Items="@images" TItem="EditableImage">
    <ImageListItem Image="@context"/>
</ImageList>
```

**Comment by mkArtakMSFT** [comment]
@captainsafia moving this over to you to help @javier with his backlog in current milestone.
