### ISSUE TITLE
HtmlHelper.Editor method doesn't correctly render properties of an object inside a collection #16689

### ISSUE THREAD

**Issue by singh733** [dotnet/aspnetcore#33358]
### Goals

To make HtmlHelper.Editor relevant for  string expression like "Items[0].FirstName"

### Proposed Solution:

Add `modelAccessor` function in `FromStringExpression`  in `ExpressionMetadataProvider` class.   **ModelAccessor** code is missing.

### Sample

```
object modelAccessor(object container)
                {
                    // Get Outer Property Value
                    var outerPropertyInfo = container.GetType().GetProperty(outerProperty);
                    var outerPropertyValue = outerPropertyInfo.GetValue(container, null);
                    var outerPropertyValueList = outerPropertyValue as IList;
                    var outerPropertyIndexValue = outerPropertyValueList[indexer];

                    // Get Inner Property Value
                    var innerPropertyInfo = outerPropertyIndexValue.GetType().GetProperty(innerProperty);
                    var innerPropertyValue = innerPropertyInfo.GetValue(outerPropertyIndexValue, null);

                    
                    return innerPropertyValue;
                    
                }
                var metadata = metadataProvider.GetMetadataForType(viewData.Model.GetType().GetProperty(outerProperty).PropertyType.GetGenericArguments()[0]).Properties[innerProperty];

                if (metadata != null)
                 return viewData.ModelExplorer.GetExplorerForExpression(metadata, modelAccessor);
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear what your ask is. Can you please share more details about what you're trying to do (as a small repro hosted in GitHub) and point out what specifically doesn't work.

**Comment by singh733** [comment]
Thank you for replying !!!
The problem is this (https://github.com/dotnet/aspnetcore/issues/16689).  In this link it is written that HtmlHelper.Editor does not work for object inside a collection. So i resolved that issue in my local branch. 
When i try to push that branch on github i got 403 unauthorized error.

**Comment by mkArtakMSFT** [comment]
Thanks for additional details. We prefer customers to discuss issues with the team first, get an approval for the design on how to resolve the issue and then send a PR.
Also, community members can't send PRs to this repo directly, instead they should fork the repo first. Please read our Contributors Guide for more details on this process.

As for the linked issue, we don't have a good feel of how any change in that area with impact other areas so we'd like to not touch it for now.
