### ISSUE TITLE
Microsoft.AspNet.WebApi.Core returns error in Solution Explorer under Packages for a project that references it

### ISSUE THREAD

**Issue by matthewacme** [dotnet/aspnetcore#33380]
![image](https://user-images.githubusercontent.com/11168104/121240624-89dc4400-c868-11eb-8afe-2eef997c4366.png)

### Describe the bug
Start a new fresh aspnet core webapi project, and upgrade the WebApi Core library to version 5.2.7 Visual Studio 2019 shows an error in the package definition's references in the Solution Explorer

### To Reproduce
Start a new fresh aspnet core webapi project, and upgrade the WebApi Core library to version 5.2.7 Visual Studio 2019 shows an error in the package definition's references in the Solution Explorer

### Exceptions (if any)
so far nothing

### Further technical details
Microsoft Visual Studio Professional 2019
Version 16.10.1
VisualStudio.16.Release/16.10.1+31402.337
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA931
Microsoft Visual C++ 2019

.ignore   1.2.77
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.10.526.50910
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CommandJSON2CSharp Extension   1.0
CommandJSON2CSharp Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.10.21111.19
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Farticus   2.0.3
The original Visual Studio fart app

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Material icons generator   2.0.0
This extension helps you to add material design icons to your Android, iOS or UWP project

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NuGetReferenceSwitcher   1.0
Information about my package

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.10.21111.19
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   16.10.21111.19
Provides templates and integration for the Django web framework.

Python - Profiling support   16.10.21111.19
Profiling support for Python projects.

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SendMeThatPackage Extension   1.0
SendMeThatPackage Visual Studio Extension Detailed Info

Snippet Designer   1.8.1
Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.31306.167
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Windows Template Studio   3.10.21120.3
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

**Comment by pranavkm** [comment]
@mattferderer the error message makes sense. You're trying to reference a package targeting .NET Framework in a .NET Core project. Can you elaborate on why it is you're referencing that particular package?

**Comment by matthewacme** [comment]
Uh not exactly.

I created a .net core 5.0 app, there is no .net framework part in it. I’ve referenced a Microsoft .Net Core component Microsoft.AspNet.WebApi.Core and that package (your stuff) is giving me a warning that it was created with a reference to a non core framework.

That’s all on Microsoft and who ever packaged up the 5.7.2 Microsoft.AspNet.WebApi.Core package that is currently sitting on Nuget.


***@***.***D75C80.FA804AC0]
Matthew C. Hintzen | Windows Washer
•
w – ***@***.***
p – 321.234.8839
•
Flightwise.com MyRadar.com

**Comment by pranavkm** [comment]
> I’ve referenced a Microsoft .Net Core component Microsoft.AspNet.WebApi.Core

That's the .NET framework package. You usually wouldn't be referencing that in a .NET Core project.

**Comment by matthewacme** [comment]
Wow, I’m an idiot.

Sorry for bothering you Pranav, closing my idiotic report… :doh:


***@***.***D75C82.CF795C20]
Matthew C. Hintzen | Windows Washer
•
w – ***@***.***
p – 321.234.8839
•
Flightwise.com MyRadar.com

**Comment by Xyncgas** [comment]
Even I wouldn't normally do this
