### ISSUE TITLE
Not continuing with MVU? 

### ISSUE THREAD

**Issue by VishwasDeokar** [dotnet/aspnetcore#33392]
Not continuing with MVU?

I am not reading anything about MVU in release notes

**Comment by javiercn** [comment]
@VishwasDeokar thanks for contacting us.

Did you mean MVC? If so we have done several features in this release, including CSS Isolation as well as Streaming support.

**Comment by campersau** [comment]
MVU is a concept which more related to [MAUI](https://github.com/dotnet/maui) see https://youtu.be/9kwrgm_-FCk?t=1345

**Comment by javiercn** [comment]
@campersau I'm familiar, however this is not the repo to ask for it. So I answered for MVC just in case. For MVU questions specifically I recommend going to the MAUI repo
