### ISSUE TITLE
Blazor Virtualize<T>: Make interface IVirtualizeJsCallbacks public

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#33396]
In some cases Virtualize component is not enough, for example if we want to focus some item to edit.
It would be greate if we could implement IVirtualizeJsCallbacks in custom component class

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear to us what specifically you're trying to do here and what prevents you from doing so. Can you please share more details about your scenario?
