### ISSUE TITLE
Blazor with razor pages not working in preview 4

### ISSUE THREAD

**Issue by rakeshkgsg** [dotnet/aspnetcore#33405]
Hi there,

I am excited about the latest .net 6 preview 4 and would like to share somw issues i encountered with the github project attached.

I have a blazor web app (.razor) with razor pages (.cshtml) that is modularised using the abp.io framework. The razor portion uses areas to route and currently does my login thru identity server 4. Everything works fine on .net 5 but under .net6 preview 4 the following behaviour occurs. 
- when i redirect to the login page (/account/login) which is a cshtml page and setup breakpoints, no break points are hit and the login page loads but with some broken css. The css are all embedded resources as it resides in a separate module library.
- when i click on the login, doing a post, the page fails to load. Just get a failed message in chrome. 
- when i reload the page or type the full url, chrome tells me it fails to load. The only way i can access it is thru the link on a blazor page. Ie. using Navigationmanager.Navigate (url, true);
- if i have f12 running and i go thru the blazor page link, it also fails to load, hence cant really figure out what is breaking when it does load without f12.
- in fact any cshtml page doesnt load in my project if accessed directly. 

**Please see the detailed steps below**
Git hub repo : https://github.com/rakeshkgsg/TestNet6

**Steps to reproduce**

**Phase 1 - Test to ensure thet .net5 works.**
1. Open TestNet5\TestApp.sln in Visual Studio 16.11 Preview
2. Modify the file TestApp.DbMigrator\appsettings.json and put in your database connection string. Also do the same for TestApp.Web\appsettings.json
3. Set TestApp.DbMigrator as the primary project and run it to create the database
4. Set TestApp.Web as the primary project and run it
5. Click on Login and use the credentials username - "admin" & password - "1q2w3E*" without the quotes
6. Also visit the page \counter to see the blazor page in action
7. Everything is working well

Now TestNet6 is the same as TestNet5 except that all the references is set to .Net6 and we have added in  the
"hotReloadProfile": "aspnetcore" in launchsettings.json 

**Phase 2 - replicate issue in .net6.**
1. Open TestNet6\TestApp.sln in Visual Studio 16.11 preview
2. Modify the file TestApp.DbMigrator\appsettings.json and put in your database connection string
Also do the same for TestApp.Web\appsettings.json. These can be the same as the one in TestAppNet5.
3. You can skip the creation of the database if the db is the same as the one in TestNet5.
Otherwise, set TestApp.DbMigrator as the primary project and run it to create the database 
4. Set TestApp.Web as the primary project and run it
5. Congrats the first page loads. Click to login and the login page loads.
6. Use the credentials username - "admin" & password - "1q2w3E*" without the quotes and login. You will see you cannot login. Exception - NullReferenceException: Object reference not set to an instance of an object.
7. Click the url to reload the page (not a post) - the page loads a blank page
8. Click on the url and change it back to the homepage - still shows blank page
9. Goto /counter and it is working - blazor works
10. Goto command and change dir to the TestNet6/src/TestApp.Web folder.
11. Do a dotnet watch run -> and we can edit the blazor page and see the hotreload working
12. If you click on login whcih goes to the cshtml page - it will be blank

Cheers and kudos to the .net team. Really exicited to hopefully be able to gain access to these updates. 

Cheers,
Rakesh gupta

**Comment by rakeshkgsg** [comment]
Have included the github project whcih shows the issues above

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The projects that you've shared look very large. Please share a minimal repro project, which has no dependencies and is based on a new project with only the minimal code necessary to repro the issue. We will then investigate this. Thanks!
