### ISSUE TITLE
Consider enhancements to MVC for a grow up story from minimal actions

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#33403]
* [x] #40639
* [x] #39692
* [x] #39667
* [x] #39754
* [x] #39757
* [x] #39682
* ~Consider adding a `EnableMinimalAPICompatibilityMode` to `ApiBehaviorOptions` so that controller actions behave like a minimal action.~

We'd likely have an option specifically for `FromServices` behavior rather than a global `EnableMinimalAPICompatibilityMode`

**Comment by pranavkm** [comment]
FYI @davidfowl / @halter73

**Comment by mkArtakMSFT** [comment]
@rafikiassumani-msft do you want to handle this in 6.0 or backlog? Up to you :)

**Comment by brunolins16** [comment]
@pranavkm for this item "Inferring optionality from nullability information" there is recent PR that updated the DataAnnotationsProvider to use the NullabilityContext https://github.com/dotnet/aspnetcore/pull/39219. 

Is that enough? If not, can you just give me a briefly explanation about this item?

**Comment by pranavkm** [comment]
@brunolins16 it's about supporting https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#optional-parameters. Essentially make `

```C#
#nullable enable
public IActionResult Post(string? value);
```

the same as

```C#
#nullable disable
public IActionResult Post(string value = null);
```

**Comment by brunolins16** [comment]
@pranavkm I thought it was already supported. Let me test it. Thanks.
