### ISSUE TITLE
Typeparam whitespace issue in .net6 preview 4.

### ISSUE THREAD

**Issue by rakeshkgsg** [dotnet/aspnetcore#33404]
Not sure if this is a design issue. Came across this when migrating files to the new .net6 preview.

In .net 5, we can do this in a blazor page
- code starts here -
@typeparam T;
@inherits ComponentBase
@implements IDisposable;
- code ends here -

But in .net6 preview 4 the above throws an error stating that it expects a whitespace after the typeparam which is a bit misleading as we simply need to remove the semicolon. It also.complains that dispose is not implemented. I had to change the code as such by removing the semicolons.

- code starts here -
@inherits ComponentBase
@implements IDisposable
@typeparam T
- code ends here -

**Comment by TanayParikh** [comment]
Hello @rakeshkgsg.

This has now been fixed via https://github.com/dotnet/aspnetcore/pull/37167 for .NET 6.0 GA release. 

Closing as dup of: https://github.com/dotnet/aspnetcore/issues/33602

Note; this only accounts for `;` after `@typeparam`.

I do not get an error with `@implements IDisposable;`
