### ISSUE TITLE
Read in System.Text.Json converter not hit

### ISSUE THREAD

**Issue by KarlssonBernoulli** [dotnet/aspnetcore#33406]
### Describe the bug
On [FromQuery] parameters the DateTimeConverter added to  ```JsonSerializerOptions.Converters.Add()``` is not used for ```Read```. The ```Write``` method is used on serialization to JSON.

### To Reproduce
```C#
services.AddControllers()
.AddJsonOptions(x => {
     x.JsonSerializerOptions.Converters.Add(new DateTimeJsonConverter());
})

public class DateTimeConverter: JsonConverter<DateTime>
{
     // Not invoked
     public override DateTime Read(ref Utf8JsonReader, Type typeToConvert, JsonSerializerOptions options)
     {
           var jsonString = reader.GetString();

           ...
           return date;
     }

     // Write is invoked - Ok

}


public async Task<ActionResult<DontCareClass>> GetBla([FromQuery]DateTime myDate)
{
}

```

### Further technical details
- ASP.NET Core version 3.1

**Comment by davidfowl** [comment]
[FromQuery] wouldn't call into your JSON converter, in fact, it doesn't use JSON at all. Seems like you need to write a [model binder](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0) instead.
