### ISSUE TITLE
Support for wfresh in Microsoft.AspNetCore.Authentication.WsFederation

### ISSUE THREAD

**Issue by nickjmcclure** [dotnet/aspnetcore#33407]
### Problem
I am trying to build an application that uses ws-fed with our ADFS environment but I want to force the user to authenticate even if they have previously authenticated for another app. This app will allow the user to perform potentially destructive actions, so requiring a new authentication is important to prevent issue like a person leaving their desktop unlocked and somebody else coming along and gaining access.

### Proposed Solution
ADFS supports this using the wfresh parameter Adding support for wfresh in WsFederationOptions and passing that value to the ADFS server would be an effective way to handle this.

If this is supported via a different method, I've not been able to find it documented anywhere.

**Comment by blowdart** [comment]
_Note - this is [prompt=login](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-prompt-login) in AzureAD terms_

@Tratcher can this be done inside [OnRedirectToIdentityProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.wsfederation.wsfederationevents.onredirecttoidentityprovider?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_WsFederation_WsFederationEvents_OnRedirectToIdentityProvider)?

You should be able to use the redirectContext.Request and append parameters there

**Comment by Tratcher** [comment]
Yes, something like this:
```
context =>
{
  context.ProtocolMessage.Wfresh = "0"
  return Task.CompletedTask;
};
```
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/101da4bd2ecb0a3128017de47bf5123a700f4a6e/src/Microsoft.IdentityModel.Protocols.WsFederation/WsFederationMessage.cs#L423

**Comment by brockallen** [comment]
> Note - this is prompt=login in AzureAD terms

Ackshully, it's *max_age* in OIDC.

**Comment by nickjmcclure** [comment]
Thanks @Tratcher & @blowdart

That did exactly what I needed.

in case anybody else stumbles across this, here is the redacted version of the options from startpup.cs:

```csharp
.AddWsFederation(options =>
{
    options.MetadataAddress = "";
    options.Wtrealm = "";
    options.Events = new WsFederationEvents
    {
        OnRedirectToIdentityProvider = context =>
        {
            context.ProtocolMessage.Wfresh = "0";
            return Task.CompletedTask;
        }
    };
})
```
