### ISSUE TITLE
Typing @ in an attribute value in a .razor file replaces the quotes with two @ characters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33417]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Typing--in-an-attribute-value-in-a-raz/1442223)._

---
Start with `<img src=`

Type " to add the quotes for the src attribute value.

Type an @ character.

Expected result: `<img src="@"`

Actual result: `<img src=@@`

---
#### Feedback Bot on 6/6/2021, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Fixed in 17.0-p2
