### ISSUE TITLE
[SignalR] Javascript clients keep reconnecting - KeepAlive

### ISSUE THREAD

**Issue by weirdyang** [dotnet/aspnetcore#33424]
I'm using a javascript client in an angular application that is hosted on the same application that hosts the hub.

For this scenario, the javascript  client keeps reconnecting every 30s, I suspect this is because it is not responding to the server's keep alive pings. When I add a breakpoint on the Hub's `OnDisconnectedAsync`,  the exception is null.

This is happening in both development and production environments.

```
Utils.js:218 [2021-06-10T08:04:14.608Z] Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.
```

I've tried increasing the serverTimeOutInMilliseconds, however this error message is still thrown every 30s:

```javascript
    this.hubConnection = new signalR.HubConnectionBuilder()
      .configureLogging(signalR.LogLevel.Debug)
      .withUrl(environment.signalHubUrl)
      .withAutomaticReconnect()
      .build();
    this.hubConnection.serverTimeoutInMilliseconds = 60 * 60 * 20;
```
![image](https://user-images.githubusercontent.com/25576022/121491835-e5ddce80-ca08-11eb-97b7-bf1c2942f781.png)

```csharp
public override async Task OnDisconnectedAsync(Exception exception)
        {
           //exception will be null
            await Groups.RemoveFromGroupAsync(Context.ConnectionId, "SignalR Users");
            await base.OnDisconnectedAsync(exception);
        }
```

```csharp
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddSignalR(opts =>
            {
                opts.EnableDetailedErrors = true;
               // have tried increasing to 1 minute but still reconnects every 30s
              // opts.ClientTimeoutInterval = TimeSpan.FromMinutes(1);
            });
```

```csharp
            app.UseSpa(spa =>
            {
                // To learn more about options for serving an Angular SPA from ASP.NET Core,
                // see https://go.microsoft.com/fwlink/?linkid=864501

                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });
```

However, when I host the client and application separately, I do not experience this issue. What could be the issue?

**Comment by weirdyang** [comment]
Ok, I realised it might be due to my initialization code in `program.cs`

If I call `.start()` on the `IHost`, I will get the timeouts, if I call `run`, it works as expected

Why is this so?

The below code ensure it works during development, but I'm not sure how to handle it for production:

```csharp
        public static void Main(string[] args)
        {
            var configuration = ConfigurationFactory.CreateConfiguration();

            

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            var databaseConfig = new DatabaseConfiguration();
            configuration.GetSection(nameof(DatabaseConfiguration)).Bind(databaseConfig);

            var url = configuration.GetValue<string>("Url", "http://localhost:8181");
            var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
            if(environmentName == Environments.Development)
            {
                CreateHostBuilder("http://localhost:5000", args).Build().Run();
            }
            else
            {
                try
                {
                    using (var _db = new MySqlDatabase(databaseConfig.ConnectionString()))
                    {
                        _db.Connection.Open();
                        _db.Connection.Close();
                    };

                    var host = CreateHostBuilder(url, args).Build();

                    RunServer(host);
                }
                catch (MySqlException ex)
                {
                    Log.Error(ex, "There's a problem with the MySQL connection, ensure it is running");
                }
                catch (Exception ex)
                {

                    Log.Error(ex, "Unable to start the server");
                };
            }

        }
```

**Comment by davidfowl** [comment]
Run blocks and waits until the application shuts down (via Control+C or SIGTERM). Start boots up the applications and hands you back control so it's likely the application is exiting completely based on the code you have above.

**Comment by weirdyang** [comment]
> Run blocks and waits until the application shuts down (via Control+C or SIGTERM). Start boots up the applications and hands you back control so it's likely the application is exiting completely based on the code you have above.

But when I use that code, I can still post and send to the api, and as you can see from the chrome console, able to connect back to the hub.

**Comment by davidfowl** [comment]
Probably for a very short amount of time, then the app ends. Though, I don't know what your RunServer does, maybe you're waiting on something in there that's making it work temoporarily.

Anyhow, what I described was the difference between the 2 methods.

**Comment by weirdyang** [comment]
> Probably for a very short amount of time, then the app ends. Though, I don't know what your RunServer does, maybe you're waiting on something in there that's making it work temoporarily.
> 
> Anyhow, what I described was the difference between the 2 methods.

I see, thanks for the clarification!
