### ISSUE TITLE
SignalR User-Agent is not correctly set on iOS and Android with React Native

### ISSUE THREAD

**Issue by TheTimeWalker** [dotnet/aspnetcore#33428]
### Describe the bug
Currently when using the SignalR Javascript Client library in React Native, on connecting with the Hub via e.g. WebSockets, the User-Agent headers aren't overriden by the library at all. This means that when the server gets the request, it either sees okhttp/3.12.12 when conecting with an Android device, while on iOS there is no User-Agent at all.

This is the request from iOS:
![SignalR-iOS](https://user-images.githubusercontent.com/8660693/121503455-5ffa5d00-c9e1-11eb-9cf3-ad03141b71d3.png)

This is the request on Android:
![SignalR-Android](https://user-images.githubusercontent.com/8660693/121503607-80c2b280-c9e1-11eb-93ed-d2672d0e71f7.png)

### To Reproduce

1. Create barebones React Native app
2. Install SignalR library and implement a simple connection
3. Start the app and connect

A super simple ready repo is here: https://github.com/TheTimeWalker/SignalRMissingUserAgent

### Further technical details
- iOS 14.5
- Android 11
- React Native 0.64
- @microsoft/signalr 5.0.6

**Comment by BrennanConroy** [comment]
This seems like a common problem and requires adding an interceptor to the OkHttp pipeline. https://stackoverflow.com/questions/35119761/react-native-okhttp-on-android-set-user-agent/66163168#66163168

This is not something we will do from the Javascript client. If you want to change the user-agent you'll have to manage it yourself.
