### ISSUE TITLE
Blazor Web Assembly Work or School Authentication type Failure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33439]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Web-Assembly-Work-or-School-Authe/1437975)._

---
I have faced below issues while login in the Blazor Web Assembly projects with work or school authentication type. Could please let me know how to resolve this issue?

Issue 1: **Can't access your account**

! [image.png] (https://aka.ms/dc/image?name=Bfce8d63780a548c39b15585ae88ec4f1637581427718793917_20210601-164249-image.png&tid=fce8d63780a548c39b15585ae88ec4f1637581427718793917)

issue 2 : After login with my account it shows **there was an error trying to login**.

! [image.png] (https://aka.ms/dc/image?name=B0fc168f9a9b143928672f8f1b9d1cf76637581429114771268_20210601-164507-image.png&tid=0fc168f9a9b143928672f8f1b9d1cf76637581429114771268)

**Visual Studio Version: Microsoft Visual Studio Professional 2019 - Version 16.8.4**

---
#### Feedback Bot on 6/1/2021, 07:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Kalirajan Ganesan on 6/3/2021, 03:10 AM: 

<p>Could you please update on this issue?</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
To configure work or school authentication, you have to make some other configuration changes. The doc here will help: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-5.0

Hope that helps.
