### ISSUE TITLE
Azure App service sticky session

### ISSUE THREAD

**Issue by Zquiz** [dotnet/aspnetcore#33440]
Hello,
I hope someone can help or just tell me that's how it works. But we have moved our Blazor Serverside project from an on-premise hosted environment to using Azure App service.

If we try and use these settings

Autoscale when the memory hit x % usage (works)

Always on to true

ARR affinity off

Web sockets ON

Followed this documentation for this

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0

We're always using an Azure SignalR Service as recommended by Mircosoft itself for this. Added Microsoft.Azure.SignalR.ServerStickyMode.Required; in our code, so it should be a sticky session.

The issue we're seeing is after 10-15 mins a browser fan will disconnect if the user is not on that fan but working on another
![image](https://user-images.githubusercontent.com/25593927/121580032-93aea480-ca2c-11eb-844c-4567716e5c43.png)

But if we enable ARR affinity cookies. Then it seems like it can negotiate just fine with SignalR. But we lose the effect of making people get onto a new instance if autoscale creates a new instance. So the load won't evenly be distributed.

Is it something we're doing wrong on our end or is it just some missed information for some failsafe built into SignalR?

Bonus info is that on-premise was we using Session sticky session LB and that worked fine for the most time.

Currently, auto-scaling to 9 instances in the morning to even out the load since the ARR cookie will let them stay on the instance for the whole workday.

Documentation I have been following
https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-5.0

**Comment by BrennanConroy** [comment]
What is a browser fan? What version of Blazor are you using?
Are you saying that if you enable ARR affinity cookies the issue doesn't happen after 10-15 minutes?

**Comment by BrennanConroy** [comment]
Can you gather client side logs to see why the client disconnected

**Comment by Zquiz** [comment]
Yeah sure.
Just the from SignalR or everything happen up to when the user disconnect?

**Comment by BrennanConroy** [comment]
Ideally SignalR only, but we can probably parse out the other logs if it's not too bad. Also, debug or trace logs please.

**Comment by Zquiz** [comment]
Sorry for the late delay.
not that easy to collect a live log while in the middle of moving from on premise to Azure and learn how to dump logs and so on.
Had to use the Live trace tool in Azure SignalR Service
![SignalRTrace002](https://user-images.githubusercontent.com/25593927/121911729-4e41ee00-cd30-11eb-98fb-16f46bd898c6.PNG)
![SignalRTrace001](https://user-images.githubusercontent.com/25593927/121911739-4eda8480-cd30-11eb-97c3-005f2a9a13f9.PNG)
If there is a better way to get the trace out in App Service please show us :)

**Comment by BrennanConroy** [comment]
This issue was moved to Azure/azure-signalr#1302
