### ISSUE TITLE
Re-opening issue: SAST Scanning of .razor files

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#33448]
I had earlier opened this [issue ](https://github.com/dotnet/aspnetcore/issues/30399) which, I think, was pre-maturely closed.

While I completely understand that it is not the responsibility of asp.net core team to work on SAST scanning tools, however, the inability of tools to scan .razor files is a very big issue and is still impeding our ability to roll out Blazor framework widely within the enterprise.

Is there any help the team can provide to the tool makers e.g. Sonarqube, or to nudge them a bit? Or would it be possible to go back to a .cshtml extension for razor components?

@danroth27  kindly intervene.

**Comment by danroth27** [comment]
Looks like Sonarqube has .razor support on their radar. I would suggest folks vote for https://community.sonarsource.com/t/support-for-scanning-of-razor-files-ie-blazor-components/43911 to let them know about the level of interest in this feature.

**Comment by javiercn** [comment]
@bancroftway what @danroth27 mentions is correct.
