### ISSUE TITLE
GetAsync of ProtectedSessionStorage locks unintentionally 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33445]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/GetAsync-of-ProtectedSessionStorage-lock/1442147)._

---
[severity:Other]
ProtectedSessionStorage GetAsync unintentionally locks
GetAsync of ProtectedSessionStorage locks unintentionally

Blazor server uses ProtectedSessionStorage to pass values between razor pages while displaying two razor pages at the same time.
After SetAsync, getAsync on another razor page does not return a response.
SetAsync is another razor page, and if the razor page is different, the thread is different, why lock it?　Asp.Net Core bug?
I'm using ProtectedSessionStorage to pass values between razor pages while displaying two razor pages at the same time on the Blazor server.
After settingAsync, when I do GetAsync on another razor page, no response is returned.
SetAsync is on another razor page, and different razor pages have different threads, why lock? A bug in Asp.Net Core?

---
#### Feedback Bot on 6/6/2021, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/7/2021, 03:04 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
