### ISSUE TITLE
FocusAsync does not focus on input on initial load on Chrome / Edge but does on Firefox

### ISSUE THREAD

**Issue by blazorbill** [dotnet/aspnetcore#33447]
I have an input element that I want to receive the focus on initial load of the form. I have added a reference to the input element and have added the FocusAsync (along with the await Task.Yield() mentioned in https://github.com/dotnet/aspnetcore/issues/30070) to the OnAfterRenderAsync method. When I run on Edge and Chrome it does not receive the focus. If I refresh the form, it does receive the focus. If I run on Firefox, the input element receives the focus on initial load. I initially had the problem with a DevExpress component and after confirmation from them that it does not appear to be a component issue but rather a Blazor issue, I created a small application to reproduce the issue. 

To reproduce the issue, please run the code in this repository on Edge, Chrome, and Firefox. On Edge and Chrome you will see that the input does not get the focus. A refresh of the browser will give the input the focus. Running this in Firefox will show that the input receives the focus on initial load and no refresh is required. 

Repository to test issue: [https://github.com/blazorbill/WebApplication1](https://github.com/blazorbill/WebApplication1)

I am using Visual Studio 2019 version 16.9.6 but have also tried on 16.10.1.
I am using .net 5.0.301 sdk.
I am running on Windows 10 version 21H1 but have also run on Windows 10 20H2.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
