### ISSUE TITLE
[Blazor] [WASM] Getting 'Interaction is currently in progress' when coming back to site.

### ISSUE THREAD

**Issue by tonyruco** [dotnet/aspnetcore#33458]
My team is getting this error when coming back to our site, which uses Azure B2C: 'Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API'.
I found this Msal-browser fix that addresses clearing of cache to avoid this error. https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3129
However, I noticed Authentication.Msal uses:     "@azure/msal-browser": "2.8.0".

Are there plans to update the msal-browser version used in Authentication.Msal sometime soon? is there an estimated timeframe?

Environment set-up
----------------------------
Further technical details
.NET 5

output of `dotnet --info
.NET SDK (reflecting any global.json):
Version: 5.0.202
Commit: db7cc87d51

        Runtime Environment:
         OS Name:     Windows
         OS Version:  10.0.18363
         OS Platform: Windows
         RID:         win10-x64
         Base Path:   C:\Program Files\dotnet\sdk\5.0.202\
        
        Host (useful for support):
          Version: 5.0.5
          Commit:  2f740adc14
        
        .NET SDKs installed:
          5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
          5.0.102 [C:\Program Files\dotnet\sdk]
          5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]
          5.0.202 [C:\Program Files\dotnet\sdk]
        
        .NET runtimes installed:
          Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
          Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
          Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Enterprise 2019 - Version 16.9.4

**Comment by javiercn** [comment]
@tonyruco thanks for contacting us.

We normally update the library when we are close to a new release. If you want to pick an updated version of the library we recommend using your own `AuthenticationService.js` file instead of the one we provide with the library.

All the interop code we have to build the library is [here](https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebAssembly/Authentication.Msal/src/Interop) and should be straightforward to update the version and build your own bundle with it.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
