### ISSUE TITLE
[Spec] Dropdown with Image abilities to be able to show flags without third party libs

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#33468]
In asp.net core and .net 6 we should be able to have a dropdown that displays an image. 

For example if I want to display an image in a dropdown we should be able to do the following

Use Case
Say for example we want to show lanauges in a ecomerce store we should be able to set images based on the models flags properties so for example here it would work as.

    <div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage"
          asp-controller="Warehouse"
          asp-action="SetCulture"
          asp-route-returnUrl="@returnUrl"
          method="post"
          class="form-horizontal nav-link text-dark"
          role="form">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items-images=@currentItem.Flag + ".png"
                asp-items="cultureItems">
        </select>
    </form>
    </div>

Flag For example would be the two letter abbreviation that would be defined in the model and the flag would be stored on the users file system or else css could be applied using icons-css. In the age of modern design this is very common place and while I no can be achieved with bootstrap extra we should not need expensive addons just to create a dropdown with image.

Spec
For example in bootstrap we can perform this like this.

 <select class="selectpicker" data-width="fit">
    <option data-content='<span class="flag-icon flag-icon-us"></span> English'>English</option>
   <option  data-content='<span class="flag-icon flag-icon-mx"></span> Español'>Español</option>
 </select>

Working Example
https://codepen.io/samar/pen/EvMgPq

It wouldn't be just flags we could show font awesome icons the reason I do not understand How I could change my select code above  to allow the working example.

   <select class="selectpicker" data-width="fit">
      <option data-content='<span class="fa-fa-car"></span> English'>English</option>
      <option  data-content='<span class="fa-fa-ball"></span> Español'>Español</option>
   </select>

We could also apply padding between the images and the text or a default padding of 10 - 15 px should be set when the dropdown is in the drop mode as shown in the below screen shot.

![image](https://user-images.githubusercontent.com/5619229/121663727-9f3ab380-ca9e-11eb-9991-eb9e9407fc97.png)

**Comment by javiercn** [comment]
@davidbuckleyni thanks for contacting us.

We work on the framework and we are not generally responsible for providing specialized components such as the one you are asking. We recommend you build your own or find one from the many of community and comercial controls libraries available.
