### ISSUE TITLE
HttpContext.Request.Headers out of original order. Allow access to raw HTTP pre body content

### ISSUE THREAD

**Issue by wayneschwebel** [dotnet/aspnetcore#33478]
The current implementation of header parsing results in headers being in a different order than the original request's order. In specialised circumstances, eg. dealing with legacy systems, this is an issue.

Adding the raw HTTP pre body content to the HTTP context would provide the flexibility for developers to determine how they would like to interpret the full message, independently of the way the standard features work.

**Comment by Tratcher** [comment]
Can you give a specific example request where this is a problem? 

Is this on Kestrel? A connection log would be a good way to verify the original input.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#connection-logging

This is HTTP/1.x, not HTTP/2, right?
