### ISSUE TITLE
[HOT REALOD] How to disable hot reload?

### ISSUE THREAD

**Issue by taha-ghadirian** [dotnet/aspnetcore#33484]
Hello guys! 
As you know, hot reload have some problems for now and doesn't let you to test .Net6 with `dotnet watch` correctly. 

For disabling hot reload in your projects, Just go to `{ProjectFolder}\Properties\LaunchSettings.Json` and Comment (disable/Delete) `HotReloadProfile` Section. 

By disabling hot reload, you can test other `.Net6 preview` features with `dotnet watch` command. 😉

**Comment by taha-ghadirian** [comment]
Hi @javiercn Please pin this issue on the top, for new users seeing this github repo.

**Comment by javiercn** [comment]
@taha-ghadirian thanks for contacting us.

What features are you having issues with?

**Comment by taha-ghadirian** [comment]
> @taha-ghadirian thanks for contacting us.
> 
> What features are you having issues with?

There are a lot of issues with `Hot reload` and they are reported in another issues.
This is a guidance for users how have problem with `Hot reload` and they cant test new features in `.Net6` because for `Hot reload problems`.

**Comment by javiercn** [comment]
@taha-ghadirian This is not the repo for such guidance, and we are interested in people trying out hot reload.

I'm closing this issue since there are no specific problems being reported here and there are issues for other problems.

**Comment by kerams** [comment]
@javiercn, so the fact that you cannot disable it is not a problem? Let alone the fact watch is now broken for F# projects, which don't supported hot reload, since you cannot opt out.

**Comment by kerams** [comment]
@javiercn, there is no hot reload section in my launch settings, yet it still seems to be enabled by default. It's an F# project that now cannot be watched because it fails with `Unhandled exception. System.InvalidOperationException: Cannot open project 'snip\Server.fsproj' because the file extension '.fsproj' is not associated with a language.`.

**Comment by javiercn** [comment]
@kerams You seem to have a different issue.

Please file a specific issue with details on your concrete scenario so that we can investigate. This issue doesn't reflect your problem and we'll loose track of it.
