### ISSUE TITLE
Blazor WebAssembly prerendering application with Globalization and Localization

### ISSUE THREAD

**Issue by Keerthi-Mettu** [dotnet/aspnetcore#33485]
### Blazor WebAssembly prerendering application with Globalization and Localization 

I'm trying to implement the internationalization feature in an asp.net core hosted Blazor web assembly that is also prerendering, but whenever a foreign language is selected, the page displays the default culture first (English translation from Resource.resx file) followed by the selected foreign language. I'm aware that pre-rendering feature will let the page load will happen twice, but is there any way to handle the initial rendering from the server with the user-selected language? Because the UI transition of two languages on each page refresh or during new language selection seems confusing!

https://user-images.githubusercontent.com/79932039/121736512-85a06880-caac-11eb-9b6a-e7bb50fd884a.mp4

Note: in this video, I'm trying to select a language (from Francais to German and viceversa) from a dropdown list. For some reason, the Xbox utility controller in windows 10, did not capture that while screen recording, lol. kindly ignore that, and look what happens when I tried to refresh the page. 

All I want is to avoid that default culture loading.

**Comment by pranavkm** [comment]
Thanks for the issue report @Keerthi-Mettu. https://github.com/dotnet/aspnetcore/issues/26890 discusses a similar problem which suggestions about using the request localization middleware and storing the culture in a way that's accessible both the server and the browser. Could you have a look and see if it helps?

**Comment by Keerthi-Mettu** [comment]
Hi @pranavkm, I tried using the localization middleware in the startup.cs file and a cultureController on the server part, but this time, instead of seeing the English translation, I see the code word name is loading up instead of its value (from resource.resx) when the page is refreshed. Also, I'm not binding the CultureController.cs in the server-part to the CultureSelector.razor in client, not sure how to do this. 


https://user-images.githubusercontent.com/79932039/121938671-f2ac3c00-cd00-11eb-8d41-5e5edaf9fa2f.mp4


Please see the code I'm writing for this and correct me if I'm missing anything.

_Host.cshtml file in Server/Pages

` @page "/"
@namespace LocalizationPreRender.Server.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Globalization
@using Microsoft.AspNetCore.Localization

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Prerendering client-side Blazor</title>
    <base href="~/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="LocalizationPreRender.Client.styles.css" rel="stylesheet" />

</head>
<body>
    <component type="typeof(LocalizationPreRender.Client.App)" render-mode="WebAssemblyPrerendered" />

    @{
        this.HttpContext.Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(
                new RequestCulture(
                    CultureInfo.CurrentCulture,
                    CultureInfo.CurrentUICulture)));
    }

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>

    <script>
        window.blazorCulture = {
            get: () => localStorage['BlazorCulture'],
            set: (value) => localStorage['BlazorCulture'] = value
        };
    </script>

</body>
</html> `

code in Startup.cs

`



        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllersWithViews();
            services.AddRazorPages();
            services.AddLocalization(options => options.ResourcesPath =
                                                      "Resources");

            services.AddControllers();

            services.AddSingleton<HttpClient>(sp =>
            {
                // Get the address that the app is currently running at
                var server = sp.GetRequiredService<IServer>();
                var addressFeature = server.Features.Get<IServerAddressesFeature>();
                string baseAddress = addressFeature.Addresses.First();
                return new HttpClient { BaseAddress = new Uri(baseAddress) };
            });

            services.Configure<RequestLocalizationOptions>(options =>
            {
                // define the list of cultures your app will support
                var supportedCultures = new List<CultureInfo>()
                                    {
                                         new CultureInfo("en-US"),
                                         new CultureInfo("fr-FR"),
                                         new CultureInfo("de-DE")
                                    };

                // set the default culture
                options.DefaultRequestCulture = new RequestCulture("en-US");

                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }
            app.UseRequestLocalization(
            app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>
                                                                 ().Value);


            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToPage("/_Host");
                //endpoints.MapFallbackToFile("index.html");
            });
        }
    }
}
`
Program.cs 
![image](https://user-images.githubusercontent.com/79932039/121937714-d4920c00-ccff-11eb-8a2c-294bcd6a1130.png)

WebAssemblyHostExtension.cs in Client/Extensions
![image](https://user-images.githubusercontent.com/79932039/121937911-0acf8b80-cd00-11eb-9ce6-fdebdeb7d6bb.png)

CultureSelector.razor in Client/Pages
![image](https://user-images.githubusercontent.com/79932039/121937067-26866200-ccff-11eb-9cc7-272ac4e1fbe6.png)

![image](https://user-images.githubusercontent.com/79932039/121937119-330aba80-ccff-11eb-8d39-ed2ed81819e9.png)

CultureController.cs in Server/Controllers
![image](https://user-images.githubusercontent.com/79932039/121936846-e58e4d80-ccfe-11eb-8d74-2afa2f5fcd08.png)

PS: The Resource.resx, Resource.fr.resx, Resource.de.resx files are in a Resources folder under Shared project.

**Comment by Keerthi-Mettu** [comment]
Please find the replica of this problem from the following link:
[Github link](https://github.com/Keerthi-Mettu/InternationalizationPreRender)

Thanks
