### ISSUE TITLE
JSON Parsing issue in .NET core 3.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33490]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JSON-Parsing-issue-in-NET-core-31/1447548)._

---
[regression] [worked-in:2019]
I am Migrating the web API build in .NET framework to .NET core.
while migrating I am facing parsing issue which was handle in .NET framework while JSON parsing in API controller.
For E.g I am having a class Test with below properties 
1. Public bool IsValid{get; set;}
2. public int[] YearId { get; set; }
case 1
while calling API in JSON If IsValid value is passed as null then in .NET framework it is getting parsed however not in .NET core 3.1 it is giving error as "Error converting value {null} to type 'System.Boolean'.".
Also I tried with NullValueHandling to Ignore as globally in configure service but it removes property which are null while sending the response. 
case 2
while calling API in JSON If YearId  value is passed as 0 then in .NET framework it is getting parsed however not in .NET core 3.1.

Can some please help me for this.

---
#### Feedback Bot on 6/10/2021, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/11/2021, 01:15 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
It's likely that your app needs to be configured to use the Newtonsoft.Json based formatter. It's what WebAPI uses for it's formatting, so that would be a better formatter to migrate to than the 3.1 compared to the System.Text.Json default. Here are the instructions: https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-5.0#add-newtonsoftjson-based-json-format-support. 

Let me know if you continue running in to issues once you switch.
