### ISSUE TITLE
Is Microsoft.NET.Sdk.Razor.SourceGenerators going to be available as a NuGet package in .NET 6 release?

### ISSUE THREAD

**Issue by tobyash86** [dotnet/aspnetcore#33508]
Question: Is Microsoft.NET.Sdk.Razor.SourceGenerators going to be available via NuGet in .NET 6 release?

Or maybe it will be available as part of SDK?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't have such plans as it's going to be part of the .NET 6 SDK. But no separate package will ship in NuGet.
