### ISSUE TITLE
BlazorServer Authorization Should Redirect to Challenge

### ISSUE THREAD

**Issue by Raghu-kumar** [dotnet/aspnetcore#33517]
blazorServer app landing page allow Anonymous access. It works properly for anonymous users. 
When I click second page which is protected using @attribute [Authorize], Blazor should redirect to Azure sso page based on the config in appsettings.json.

Here is my appsettings.json
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "mydomain.onmicrosoft.com",
    "TenantId": "12345",
    "ClientId": "a84567780s228797",
    "CallbackPath": "/signin-oidc"
  },

made following changes in app.razor
 <AuthorizeRouteView RouteData="@routeData"
                                DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (!context.User.Identity.IsAuthenticated)
                    {
                        <RedirectToLogin />
                    }
                    else
                    {
                        <p>
                            You are not authorized to access
                            this resource.
                        </p>
                    }
                </NotAuthorized>
            </AuthorizeRouteView>

I created RedirectToLogin.razor
should I do redirect by forming the required Azure sso login url (Auth request) with all the required parameters? or is there default option in blazor which redirect to the Azure sso page

**Comment by javiercn** [comment]
@Raghu-kumar thanks for contacting us.

You should redirect a user to a a controller endpoint on the server and issue a `Challenge` from there to start the authentication process.

**Comment by Raghu-kumar** [comment]
@javiercn Thank you. it works
