### ISSUE TITLE
Blazor Wasm - DLL on subpath not found (404)

### ISSUE THREAD

**Issue by Molinware** [dotnet/aspnetcore#33515]
### Describe the bug
External DLL's of project not being loaded.

### To Reproduce
https://github.com/Molinware/BlazorWasmDllExample

I've created a Blazor (wasm) templated Asp Net Core hosted. In the Client I've Added a folder with an external dll:
**BlazorWasmDllExample.Client\ExternalDll\ExampleErrorDll.dll**

Steps:
- Publish the Server
- Run
- Access localhost
- It'll not load the project because blazor.boot is not able to load the dll.

### Further technical details
- .NET 5
- VS 2019 Professional

**Comment by javiercn** [comment]
@Molinware thanks for contacting us.

Loading dlls dynamically is not something we support out of the box, however its something you can do by yourself if you publish the dll to the wwwroot folder of your app, download it and load the assembly manually on the client.

**Comment by Molinware** [comment]
In my real project I have the **Blazor App**. It has a **Referenced Project** that contains the **external dll**. I don't really use it in the **Blazor App**, but the **Referenced Project** is referenced too in a **Desktop App** that uses the **external dll**.
So, is there a way I can ignore it on the **Blazor App**? Do you want me to update the repro to reflect this?

**Comment by javiercn** [comment]
@Molinware It's not clear to me what you are trying to achieve here.

**Comment by Molinware** [comment]
- I have a **Class Library Project** that contains an **External.dll**
- The **Class Library Project** is shared between the **Blazor App** and **Desktop App**
- In the **Desktop App** I call the **External.dll**
- In the **Blazor App** I do not call the **External.dll** but since it's part of the **Class Library Project** it's being shipped to the **Blazor App** anyway.
- Then when I access the **Blazor App**, it tries to download the **External.dll** and gives an error.

This image is from the repro, but follows the same logic as the real project:
![Example](https://user-images.githubusercontent.com/10515611/121920064-09a55b00-cd0e-11eb-84ad-43d46a95dc0b.png)

**Comment by javiercn** [comment]
@Molinware thanks for the additional details.

We would recommend that in that situation you would instead refactor your class library to avoid the unwanted (shared) dependency and to move that dependency to the Desktop project.

**Comment by Molinware** [comment]
There's no other way I can prevent this dll to be placed on the **blazor.boot.json** file?

**Comment by javiercn** [comment]
@Molinware no.

It's a dependency for the app and it will be placed in blazor.boot.json and loaded whether you use it or not. The only thing that you could use is to mark it as a "lazy loaded" assembly as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)
