### ISSUE TITLE
Account Login post action incorrectly calling PasswordSignInAsync with wrong parameter

### ISSUE THREAD

**Issue by Nfactor26** [dotnet/aspnetcore#33519]
### Describe the bug
I am working with Asp.Net Identity and using Default UI. I registered a new user by providing email and password. 
I updated my user name later by editing my profile. Initially, user name was same as email when account was registered.
After updating user name, I am not able to sign in using the account login page.

### Error message on trying to sign in with email and password
Invalid login attempt.

### Further technical details
- ASP.NET Core version : 5.0

Account Login Page (Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.Login.cshtml.cs) passes Email as the first parameter to PasswordSignInAsync method.

` var result = await _signInManager.PasswordSignInAsync(**Input.Email**, Input.Password, Input.RememberMe, lockoutOnFailure: false);`

However, if you look at the implementation of _signInManager.PasswordSignInAsync( ...... ), it expects userName as the first parameter.

`public virtual async Task<SignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent, bool 
        lockoutOnFailure)
 {
            var user = await UserManager.FindByNameAsync(userName);
            ..................................................
  }`

As a result of this , if  username and email are not same in the users table, login fails from the Account Login page.

**Comment by Nfactor26** [comment]
Does it make sense to retrieve the **user** using email in Login.cshtml.cs and then call the overload 
`Task<SignInResult> PasswordSignInAsync(TUser user, string password,  bool isPersistent, bool lockoutOnFailure)` ?
If someone can confirm, I would love to try and create a PR.

**Comment by HaoK** [comment]
The default UI/templates treat email and username as the same, you are free to customize the app/scaffold to treat email/username distinctly
