### ISSUE TITLE
playwright  Failed to download firefox

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#33527]
## Error Message

```
  Failed to install browsers
EXEC : error : Failed to download firefox, caused by [D:\workspace\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to download firefox, caused by
EXEC : error : connect ETIMEDOUT 13.107.246.70:443 [D:\workspace\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) connect ETIMEDOUT 13.107.246.70:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
D:\workspace\_work\1\s\.packages\playwrightsharp\0.192.0\build\netstandard2.0\PlaywrightSharp.targets(20,5): error MSB3073: The command "playwright.cmd install" exited with code 1. [D:\workspace\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error].packages\playwrightsharp\0.192.0\build\netstandard2.0\PlaywrightSharp.targets(20,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "playwright.cmd install" exited with code 1.
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1184309&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4a2ac175-72f0-54eb-c8b6-eb1e5d86c7d5&l=1911

**Comment by javiercn** [comment]
@HaoK do you think we can apply the recommendations [here](https://playwright.dev/docs/ci#caching-browsers) and [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) to avoid downloading the browsers from external sources when possible?

**Comment by HaoK** [comment]
Sure i'll give it a shot

**Comment by HaoK** [comment]
I ran into weird issues with azdo restore and seemingly unrelated mac os job issues trying out the azdo caching, https://github.com/dotnet/aspnetcore/pull/33557 was my PR to try out these suggestions that seemed to cache/restore the playwright binaries correctly, so it does seem promising

**Comment by TanayParikh** [comment]
Another failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1454787&view=logs&jobId=f43b187f-6c15-531c-a59b-e4fba4e9ed20&j=f43b187f-6c15-531c-a59b-e4fba4e9ed20&t=98a09275-a4dd-593e-c21a-1f8bea3be5b1

**Comment by TanayParikh** [comment]
Another one:
https://dev.azure.com/dnceng/public/_build/results?buildId=1464595&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4a2ac175-72f0-54eb-c8b6-eb1e5d86c7d5&s=6884a131-87da-5381-61f3-d7acc3b91d76

```
EXEC : error : Failed to download firefox, caused by [D:\a\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to download firefox, caused by
EXEC : error : end of central directory record signature not found [D:\a\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) end of central directory record signature not found
      at D:\a\_work\1\s\artifacts\bin\Microsoft.AspNetCore.BrowserTesting\Release\net6.0\.playwright\win-x64\native\package\node_modules\yauzl\index.js:187:14
      at D:\a\_work\1\s\artifacts\bin\Microsoft.AspNetCore.BrowserTesting\Release\net6.0\.playwright\win-x64\native\package\node_modules\yauzl\index.js:631:5
      at D:\a\_work\1\s\artifacts\bin\Microsoft.AspNetCore.BrowserTesting\Release\net6.0\.playwright\win-x64\native\package\node_modules\fd-slicer\index.js:32:7
      at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
D:\a\_work\1\s\.packages\playwrightsharp\0.192.0\build\netstandard2.0\PlaywrightSharp.targets(20,5): error MSB3073: The command "playwright.cmd install" exited with code 1. [D:\a\_work\1\s\src\Shared\BrowserTesting\src\Microsoft.AspNetCore.BrowserTesting.csproj]
##[error].packages\playwrightsharp\0.192.0\build\netstandard2.0\PlaywrightSharp.targets(20,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "playwright.cmd install" exited with code 1.
 ```

**Comment by javiercn** [comment]
@TanayParikh you are doing work in this area, so I'm going to hold-off on this one until you are done, since I'm not sure what impact it'll have.

My goal with this PR is to try and make sure we follow the guidance [here](https://playwright.dev/docs/ci/#caching-browsers). If that's something you also want to tackle as part of your changes that sounds good to me.

**Comment by TanayParikh** [comment]
Closing this out now, it was resolved via https://github.com/dotnet/aspnetcore/pull/38414's new Playwright installation mechanism.
