### ISSUE TITLE
Blazor tooling fails to work with nested Global.json

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33532]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-tooling-fails-to-work-with-nested/1446158)._

---
[severity:It bothers me. A fix would be nice]
Given a solution that is in a directory using a Global.json file and the directory has multiple Global.json files.

EX:
-- RootDirectory (global.json targeting .NET 5)
     -- ProjectDirectory (global.json targeting .NET 6)

Razor tooling in the project will fail to work properly, no intellisense will be applied, no tool tips are shown, RazorComponents are not recognized.

The project can be built and run using the CLI with no issue.

Moving the project to a new root folder without a global.json resolves the problem.

---
#### Feedback Bot on 6/9/2021, 11:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
This doesn't repro for me in the latest preview version (31726.67.main). Closing out for now, will re-open if reported again.
