### ISSUE TITLE
Razor.Language loaded by source generator can conflict with version loaded by Visual Studio

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#33536]
Razor source generator attempts to load Razor.Language and CodeAnalysis.Razor which are also part of VS tooling. Both of these are present in the same AppDomain so things are ripe for conflict. 

A possible easy fix is to produce assemblies with different identity (e.g. `Microsoft.AspNetCore.Razor.Language.Internal`) and load those in the RSG.

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/54100 (Do not run source generators in-proc)

**Comment by dibarbet** [comment]
I updated https://github.com/dotnet/roslyn/issues/54100#issuecomment-873285120 with details, but I am fairly frequently hitting an issue where the `Microsoft.AspNetCore.Razor.Language.dll` is loaded twice with different versions causing runtime exceptions in VS.

**Comment by pranavkm** [comment]
FYI @tmat  \ @NTaylorMullen - this is done.
