### ISSUE TITLE
Require an option to view the rendered html source of the BlazorWebView control in WinForms and WPF model during runtime

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/aspnetcore#33539]
### Is your feature request related to a problem? Please describe.
I am trying to do a prototype on the reuse of the razor component with the BlazorWebView, so that it can be integrated into the existing WinForms, WPF, .NET MAUI app. But the problem is, could not able to view the rendered html source to fine tune it. This will definitely affect the developer productivity as more time will be spent on the dev loop of build and debug.

### Describe the solution you'd like
During app execution, a context menu item / shortcut key to view the source of the rendered html in a separate window (those items depends on enabling a property, that can be turned on during development).

### Additional context
If possible, element highlight and other features like how the browser F12 developer tools does today.

**Comment by javiercn** [comment]
@egvijayanand thanks for contacting us.

I believe you can open the devtools on the webwindow to see the HTML or configure the webview2 control we expose to do so.

@Eilon might have more insights.

**Comment by egvijayanand** [comment]
Thanks for the immediate response.

@Eilon, if you could share the details on how to enable such option, it would be much helpful.

**Comment by Eilon** [comment]
@egvijayanand the "browser dev tools" are enabled automatically so you should be able to use that to inspect/edit/debug code and content in the BlazorWebView. For WPF/WinForms/WinUI: run the app, click somewhere in the BlazorWebView to make sure it's "in focus," and then press either <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>. Then you can use the browser dev tools just like anywhere else.

**Comment by Eilon** [comment]
Oh, and if you want to handle it in a totally custom way, you can run code like this from somewhere in your app (say, your own menu or button):

```c#
blazorWebView1.WebView.CoreWebView2.OpenDevToolsWindow();
```

(Note that some of this is enabled only in recent builds.)

**Comment by egvijayanand** [comment]
Ctrl+Shift+I nailed it, and this is what I want. Thanks @Eilon.
