### ISSUE TITLE
Blazor Server Net Core 5: System.Text.Json.JsonException: Invalid JSON When open multiple Tab

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/aspnetcore#33542]
Hello,

I have the the next exception in Blazor Server , .NET 5 Latest Version . What can be ? This happens when open multiple tabs , but only in some tabs . The browser doesn't matter .

[2021-06-15T10:49:32.726Z] Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.EndInvokeJSFromDotNet(Int64 asyncCall, Boolean succeeded, String arguments)
e.log @ blazor.server.js:21

There is no json in any call to JS.

Every call to js has try catch ...

Thank's

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by lucianparvu** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

Hello,

This is impossible because it is a big project and i don't know what part is causing this problem .

I suspect is from JS interaction .

I can see there was similar issue : https://github.com/dotnet/aspnetcore/issues/20581 but without result

Please find here  some examples :

```
 protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            try
            {
                 
                objRef = DotNetObjectReference.Create(this);
                await _JsRuntime.InvokeVoidAsync("LoadScriptWithPromise", TimeSpan.FromSeconds(3), FinalSrc, IsFooter, objRef, nameof(InformOnChildLoadedParent));

            }
            catch
            {
            }

        }
    }
```

```
     /// <summary>
    ///  Invoked from Javascript.
    /// </summary>
    [JSInvokable("InformOnChildLoadedParent")]
    public async Task InformOnChildLoadedParent(bool result)
    {
        try
        {
            if (result)
            {
                await OnChildLoaded.InvokeAsync(true);
            }
        }
        catch { }
    }

```

**Comment by javiercn** [comment]
@lucianparvu thanks for contacting us.

Try adding the following to your `_Host.cshtml` and see if that helps:

```csharp
if (!context.Response.HasStarted)
{
    context.Response.Headers.CacheControl = "no-cache, no-store, max-age=0, no-transform";
}
```
