### ISSUE TITLE
Results of async calls not being returned to correct caller

### ISSUE THREAD

**Issue by pridmorej** [dotnet/aspnetcore#33544]
### Describe the bug
You'll see in the git repo a solution that displays a list of Crypto Product Tickers.  There are a number of nested Razor components, and I'm utilising the [Parameter] attribute to pass down a ProductTickerVM from the ProductTickersPanel to the ProductTickerPanel, and then the ProductId as a string from the ProductTickerPanel to the ProductStatsPanel.  I'm then making an async call to get the latest ProductStat for the specified ProductId (adding a new ProductStat to a ConcurrentDictionary, keyed on ProductId, after an async call to get the stat from coinbase if needed).  There's some uses of "lock" in there too which is a remnant of when I was just using a Dictionary.

The issue I'm getting is that the ProductStats returned by that async call are often for a completely different ProductId.  

To trap this issue, I have a Debug.Assert just before the return of  ProductStatsUpdater.Last (which is not triggered) and a Debug.Assert statement in ProductStatsManager.LatestProductStatsFor (which is triggered). 

It therefore seems that the results for one async call are somehow confused with the results of another async call, or the ordering of the DOM elements is getting messed up.  Whatever it is, the results are crazy and I just can't figure out why.  I'm fairly new to Blazor, so very likely there is something I don't understand. However, I am mainly dealing with local variables when getting the ProductStats, so I can't see how or why threading is getting in the way.

Of course, this is probably somewhat hampered by this all occurring asynchronously whilst also loading a list of ProductTickerPanel components, and those being reordered on the page according to ProductId as they are being loaded, however, I fully expect Blazor to be able to handle reordering those dom elements as they are all neatly nested components.

I'm pretty sure I've got the right mix of events being raised from my Services, and being handled correctly in the consumers of those events.  All the services are IDisposable where necessary in order to detach events.

Most of the services are Singletons registered in ConfigureServices.

### To Reproduce
Please see my repo here: https://github.com/pridmorej/ProductStats

This is a BlazorServer application.  Please download, F5 in VS, and then note the failing Debug.Assert statements.

### Exceptions (if any)
no exceptions raised.

### Further technical details

- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: 
Microsoft Visual Studio Enterprise 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

- ASP.NET Core version: 
ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974

**Comment by pridmorej** [comment]
I had thought it might be related to use/lack of use of ConfigureAwait, so I have also experimented with adding ConfigureAwait(false) to all awaited calls in the Service methods; even though I am not experiencing any deadlocks.  I also tried various uses of ConfigureAwait in OnAfterRenderAsync, but found that made no difference either, other than the ExecutionContext switching and therefore having to use InvokeAsync to call StatehasChanged).  However, despite this, I do actually want the returning ExecutionContext to be synchronised, as I fail to see how I'd get the correct result after awaiting a call if I was to ConfigureAwait(false).

**Comment by javiercn** [comment]
@pridmorej thanks for contacting us.

The repro project you produced is too big for us to make sense of it without spending a significant amount of time on it. 

The app doesn't follow common Blazor patterns, for example registering the services as singletons make those services globally to all circuits in a given server.

Without an absolutely minimal repro and detailed steps on what the expected behavior is, and what the actual behavior you are observing is, we can't make progress on this issue efficiently.

We don't think we have issues on this area since its a very fundamental block of the framework and its well covered by automation, so we think there likely is a subtle bug in the application code.

If you are able to produce a smaller repro and clear detailed steps that demonstrates the bug we'll be happy to take another look.
