### ISSUE TITLE
Add ability to use razor page, rather than static page, for Angular aspnetcore projects

### ISSUE THREAD

**Issue by DarylSmith** [dotnet/aspnetcore#33552]
Currently, the behaviour of the Angular SPA extensions is to configure middleware to listen for UI requests and send them to a static page (for example index.html) https://github.com/aspnet/JavaScriptServices/blob/master/src/Microsoft.AspNetCore.SpaServices.Extensions/SpaDefaultPageMiddleware.cs#L23 . 
However in many cases, it would be much more useful to use a razor/cshtml page for this purpose. This is particularly true in applications with important configuration data - it's much simpler to return the data payload on the initial page request, then to have to wait for the page to load, submit an xhr request for the configuration data on the Angular bootstrap event, and then pause the application while that initial configuration returns, since that initial data is required for page rendering.  In addition to avoiding this type of bottleneck, the dynamic index page avoids race condition and complexity inherent in loading configuration data via an xhr request.

While there are workarounds available currently, as outlined in this SO question https://stackoverflow.com/questions/50815456/asp-net-core-2-1-angular-6-0-spa-template-razor-page-cshtml-for-index-instea. it would be much better to have this functionality added to the core Angular middleware service.  One possibility could be an overload to the .useSpa() method, that would allow providing razor or cshtml that could be called for UI requests.

**Comment by javiercn** [comment]
@DarylSmith thanks for contacting us.

I'm not sure this is possible given how angular and other frameworks use a build process for updating the index.html. If you come up with a specific pattern that aligns well with what angular and other frameworks recommend in this space, we might consider adding it to the docs.

However, we don't plan to add any functionality in this area that is specific to ASP.NET Core and we recommend following the guidance Angular or other SPA frameworks offer for this.
