### ISSUE TITLE
VS2019 - Razor Language Services - Shared Project - ".cshtml is not a descendent of the base path"

### ISSUE THREAD

**Issue by joe88ds** [dotnet/aspnetcore#33550]
### Visual Studio Windows

I'm trying to add my shared project (with razor views) into my web application development project (by Add Shared Project Reference), but this error pops up as many times as there are razor views. This is because my razor views are inside my shared project (which is a different directory tree than my development project). Is there anyway of referencing a shared project with razor views? Why is this a limitation?

Error encountered from project 'C:\@\Tests\Testing.WebApp\Testing.WebApp.csproj': System.InvalidOperationException: The file 'C:/@/Templates/Projects/WebApplication/Pages/_ViewStart.cshtml' is not a descendent of the base path 'C:/@/Tests/Testing.WebApp'.   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.GetItem(String path, String fileKind)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetImportsCore(DefaultProjectSnapshot project)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetImports()   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.&lt;GetImportsAsync&gt;d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.&lt;GetGeneratedOutputAndVersionCoreAsync&gt;d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.&lt;GetGeneratedOutputAsync&gt;d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.Razor.BackgroundDocumentGenerator.&lt;ProcessDocument&gt;d__44.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.Razor.BackgroundDocumentGenerator.&lt;TimerTick&gt;d__48.MoveNext()
--

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue is fixed in the latest Visual Studio 2022. If you'd like to try this tooling out you can download the latest VS 2022 and re-try your scenario.

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.
