### ISSUE TITLE
Adding a component specific CSS file doesn't trigger `dotnet watch`

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#33569]
Repro steps:

- Install .NET 6 Preview 6 (6.0.100-preview.6.21315.23)
- `dotnet new blazorserver`
- `dotnet watch`
- Add *Index.razor.css*

Expected:
- `dotnet watch` rebuilds the app

Actual:
- The app doesn't get rebuilt

Workaround:
- Hit <kbd>Ctrl+Shift+R</kbd> to restart the app

**Comment by danroth27** [comment]
@pranavkm

**Comment by v-nzicol** [comment]
@pranavkm , After installing 6.0 Preview 7, this issue also repro for Blazor WASM project. Should we open a new issue to track blazor wasm?

**Comment by danroth27** [comment]
@v-nzicol We can use this issue for both Blazor Server and Blazor WebAssembly.

**Comment by v-nzicol** [comment]
@danroth27 Got it, thanks for your reply.
