### ISSUE TITLE
RedirectToAction should support relative paths

### ISSUE THREAD

**Issue by joshudson** [dotnet/aspnetcore#33568]
### Is your feature request related to a problem? Please describe.

We have an application that we're trying to prepare for running behind customer-provided reverse proxy servers. What will eventually need to work is https://customer-site/subdir/Applciation -> https://internal:highport/ via reverse proxy server; however the url for https://internal:highport/ needs to actually work as well. This means that PathBase needs to be a computed relative URL rather than an absolute URL.

### Describe the solution you'd like

Knock out the check that reads "The path in 'value' must start with /"; allow `@Url` and `~/`to just be relative URLs and RedirectToAction to work.

### Additional context

I'm probably going to have to remove all reference to ~ and RedirectToAction because this feature has an unnatural limitation.

**Comment by Tratcher** [comment]
Can you give some example code, values, and the full exception with stack trace?

**Comment by joshudson** [comment]
So the object is to set `PathBase` to something appropriate for an application that doesn't know its actual path. Simple URL rewriting doesn't work anymore in the days of `require.js` and friends.

Code:
````
            app.Use((context, next) =>
            {
                context.Request.PathBase = context.Request.Path.GetBasePath();
                return next();
            });
````

GetBasePath is a function that determines the number of `../` components are needed. In this case it returned `.` as no `../` are needed within the IDE.

````
        public static string GetBasePath(this PathString @this)
        {
            var path = @this.ToString();
            int count = -1;
            foreach (var c in path)
                if (c == '/')
                    ++count;
            if (count < 0) throw new InvalidOperationException("URL passed to web server doesn't start with /");
            if (count == 0) return ".";
            return string.Concat(Enumerable.Repeat("../", count));
        }

````

Stack trace:

````
System.ArgumentException
  HResult=0x80070057
  Message=The path in 'value' must start with '/'. (Parameter 'value')
  Source=Microsoft.AspNetCore.Http.Abstractions
  StackTrace:
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Http.PathString.op_Implicit(String s)
   at Cedaron.FormBuilder.Presentation.Startup.<>c.<Configure>b__12_0(HttpContext context, Func`1 next) in C:\Users\jhudson\dev\cento_forms\src\Cedaron.FormBuilder.Presentation\Startup.cs:line 163
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.<ProcessRequestAsync>d__2.MoveNext()
````

**Comment by joshudson** [comment]
Clarification: The first request when running under the IDE will always be a request for / so "." is correct. If a request is made for "/Home/About" then "../" would be generated; "Home/About/" would generate "../../" and so forth. (Perchance the trailing / is a bug and if so I would remove it but I'm not getting far enough to try.)

**Comment by Tratcher** [comment]
Ok, though I still don't understand what you're hoping this will accomplish?

The request Uri is broken down like this:
{scheme}://{host:port}{PathBase}{Path}{QueryString}

A Uri like `https://host/../../Home/About` isn't meaningful since you can't navigate down past the root.

I think you're approaching this backwards. The recommendation when you have a proxy that removes parts of the path is for it to communicate that path via an extra header like `X-Forwarded-Prefix: /subdir/Applciation` and then you read (and validate) that header in order to assign PathBase.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#deal-with-path-base-and-proxies-that-change-the-request-path

**Comment by joshudson** [comment]
Well; if the extra header were reasonably well-specified I would definitely do that. I spent quite some time looking for one. I didn't find X-Forwarded-Prefix until you mentioned it; I did find X-Original-Url from IIS; and found some other proxies just don't set anything.

The idea is for the application to work when called either directly or through the reverse proxy, and the less I have to bug the customer to configure the better. If I have to bug the customer to set up the header I will, but I'd rather not do it. A Uri of https://host/../../Home/About is not meaningful but the user's browser actually sees  https://host/subdir/Area/Controller/Action/../../Home/About which is long-winded but perfectly reasonable.

Fun fact; if you make an `<A HREF="/../Home/About">` it will get passed to the server with a path of '/../Home/About"; .. components aren't removed if they would extend upwards from the root. Kestrel's default static file provider won't resolve these but a custom static file provider could. I wanted to make a bizarre easter egg that looked like I was vulnerable to that ancient security vulnerability but return fake data and gave up when I discovered that static file providers couldn't return error codes other than 500 or 404 easily.

**Comment by Tratcher** [comment]
I think I finally understand what you're trying to do. You're trying to make all link generation relative to the current request path rather than absolute, correct? PathBase is definitely not designed for that.

Let's shift to the consumption end. You're using RedirectToAction? Can you show how?

**Comment by joshudson** [comment]
`return RedirectToAction("Home", "About");`

Expected to generate: `Location: ../../Home/About`

I found out this is not quite the same as `return RedirectResult(context.Request.PathBase + "/Home/About");` because of some reflection magic; but in any case without PathBase being set relative, the RedirectResult won't work either.

Relative paths work in the Location header have always worked and the spec was finally updated to say they do. https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.2

**Comment by Tratcher** [comment]
Ok, that's a much clearer objective. I've updated the title and re-tagged this for MVC to investigate.

**Comment by javiercn** [comment]
@joshudson thanks for the additional details.

We currently generate host relative paths. Are you asking we support "document" relative paths instead?

**Comment by joshudson** [comment]
@javiercn : Host relative path doesn't seem to be a real term on attempting internet search. I've heard of host relative URL which is still an absolute path. A relative path doesn't start with / and is clearly relative to the document (or base href if there is one).
