### ISSUE TITLE
Check validity of a registered user's password

### ISSUE THREAD

**Issue by eliaskokkalis** [dotnet/aspnetcore#33577]
I am trying to check all registered users' passwords validity according to a new stricter password policy. 
For example, let's assume that the password policy was initially set to a password length of 6 characters (no other requirements). So, the registered users are created with passwords that conform to this policy. Then I change the password policy to a password length of 10 characters (still no other requirements). As a result, some user passwords may conform to the new policy but some others may not. I want to find all the users that have a password that does not conform to the new password policy so that I prompt them to change their passwords.

I haven' find a way to achieve this. Is there a way that this become possible?

**Comment by blowdart** [comment]
You cannot do it until a user enters the existing password, as the passwords aren't stored in plain text. 

You'd have to [scaffold out the login page](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio), and change the code there to validate on form submission. You'd also have to inject `IEnumerable<IPasswordValidator<TUser>> passwordValidators` to get the registered validators then run through them calling validate

**Comment by eliaskokkalis** [comment]
Yes, I thought so. Thank you.
