### ISSUE TITLE
Error: "Failed to find a valid digest in the 'integrity' attribute for resource" on .NET 6 

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#33584]
### Describe the bug
We are doing some tests with Blazor WebAssembly AOT on .NET 6.
We published a build to Azure, and when it is trying to load we get errors such as the following
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://fairplaytubeprodvnext.azurewebsites.net/_framework/Microsoft.AspNetCore.Components.Authorization.dll' with computed SHA-256 integrity 'iIeB+m196dll9MhI3qhlQ6zC+Nd1g0iHC4zsBowo79U='. The resource has been blocked.`

<img width="1425" alt="Screen Shot 2021-06-16 at 08 18 28" src="https://user-images.githubusercontent.com/3481899/122236926-28296480-ce7c-11eb-99dc-fedc5ef01424.png">

**NOTE: Issue happens even on self-contained deployments**

### To Reproduce

- Create a Blazor WebAssembly project
- Set it to use .NET 6 Preview 4 packages
- Enable AOT
- Publish to Azure
- Set Azure to use .NET 6 Early Access

### Further technical details
- ASP.NET Core version: 6 Preview 4
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This documentation should help: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures
