### ISSUE TITLE
Request for `--` configuration key delimiter support in KeyPerFile

### ISSUE THREAD

**Issue by craigktreasure** [dotnet/aspnetcore#33589]
### Is your feature request related to a problem? Please describe.

I'm using secrets stored in Azure Key Vault in a Kubernetes environment. Key Vault does not support the use of `_` characters in a secret name, so we're advised ([here](https://docs.microsoft.com/aspnet/core/security/key-vault-configuration) and [here](https://docs.microsoft.com/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#configuration-keys-and-values)) to use a `--` for a configuration key delimiter in Key Vault. Using the Secrets Store CSI driver and provider for Azure Key Vault (per the [documentation](https://docs.microsoft.com/azure/key-vault/general/key-vault-integrate-kubernetes)), secrets are downloaded to key files in a directory. Loading those secrets using the `KeyPerFile` configuration provider would be a great fit, but it only supports `__` as a configuration key delimiter.

### Describe the solution you'd like

Enabling the `KeyPerFile` configuration provider to support a `--` configuration key delimiter would be great. It would also allow me to maintain compatibility in my scenario with the [Azure Key Vault configuration provider](https://docs.microsoft.com/aspnet/core/security/key-vault-configuration).

### Additional context

None

**Comment by BrennanConroy** [comment]
Triage: That sounds like a good addition we'd be happy to accept a contribution for.

On the `KeyPerFileConfigurationSource` add an option for a delimiter. Then use that delimiter in the `KeyPerFileConfigurationProvider`.

**Comment by BrennanConroy** [comment]
cc @HaoK in case you have any extra input.

**Comment by craigktreasure** [comment]
Thanks @BrennanConroy!
