### ISSUE TITLE
Razor compilation errors started happening from VS2019 v16.10, potentially due to path lengths

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-compilation-errors-started-happeni/1452042)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9]
This issue only started happening when moving to v16.10.0 or v16.10.1.
It is also a problem in v16.11.0 Preview 1.0.
This was not an issue in version 16.9.x
I noticed it a few weeks before the RTM/GA release, but didn't have time to report it and it now seems to have got past the testing phase.
I worked around it previously by uninstalling the preview version of VS2019, but now I can't even do that anymore as I'm forced to use the current version, **so I basically can't work anymore :(**

I basically get lots of compilation errors similar to this (which aren't very useful as all the files exist):
Error	RSG002	TargetPath not specified for additional file: c:\Users\gordo\! ADO\my-software\A0501\A0501\src\A0501. UI. BlazorServer\_Imports.razor.	
Error	CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

If I move the project to a ridiculously short path (like C:\temp) then everything compiles and runs perfectly, as before the VS2019 upgrade.
I've got long paths enabled in Windows, to try work around this issue, but that doesn't help either.
I've also tried to shorten my project names and paths, but I can only go so far before it becomes really difficult to keep things organised.

I'm not sure if this is related or not, but I've also noticed that the files/folders are getting hard locked by PerfWatson2.exe (or something else), even after closing VS2019, requiring lots of rebooting (or eventually installing a tool just to unlock the folders again).

---
#### Gordon Rudman on 6/9/2021, 04:04 PM: 

<p>Ah, this situation gets much worse 😦</p>
<p>My build server is treating these Razor problems as warnings instead of errors, so has automatically just compiled and deployed my website to Azure.<br>
However, it’s completely broken now.</p>
<p>I’m getting the following error on Azure now:<br>
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.<br>
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)<br>
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)<br>
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.&lt;Invoke&gt;g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)<br>
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)</p>

#### Feedback Bot on 6/9/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/10/2021, 03:51 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
