### ISSUE TITLE
HTTP/3: Figure out ConnectionId, RequestId, TraceId

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#33593]
Various IDs are assigned to connections and requests. These are output in logging.

The current design on ConnectionContext wasn't designed with HTTP/3 in mind which has a multiplexed transport context plus per-stream contexts.

Want to give users informative IDs in log messages without allocating a string ID per-stream.

**Comment by BrennanConroy** [comment]
Triage: We're fine allocating, as long as it's lazy.

**Comment by JamesNK** [comment]
Today in HTTP/3:
* ConnectionId = Stream ConnectionId. Allocates a new string per request by combining QUIC connection ID with stream number. `$"{_connection.ConnectionId}:{StreamId}"`. e.g. "0HMAGF2FLQPAO:4"
* RequestId = Stream ConnectionId again.
* TraceId = Stream ConnectionId again.

When we log about events on a request stream the logs all contain an argument with the Stream ID number. e.g.
> Connection id "0HMAGF2FLQPAO:3" sending GO_AWAY frame for stream ID 3 with length 1.

Because the stream number is always logged, I think we should change ConnectionId to be the actual QUIC connection ID (so, no longer be concatenated with the StreamId). That makes it consistent with HTTP/2 and it will no longer be allocated per request.

In HTTP/3, RequestId and TraceId will continue to be a concat of both data, e.g. "0HMAGF2FLQPAO:4".

Question: should the value be updated to be consistent with HTTP/2? i.e. change `$"{_connection.ConnectionId}:{StreamId}"` to `StringUtilities.ConcatAsHexSuffix(ConnectionId, ':', (uint)StreamId)`?

**Comment by JamesNK** [comment]
Thoughts @Tratcher @halter73 @wtgodbe?

**Comment by JamesNK** [comment]
Discussed with HTTP/3 team. Will follow proposed changes. Will make consistent with HTTP/2.
