### ISSUE TITLE
Microsoft.AspNet.SignalR.Core, Version=2.4.1 referencing Microsoft.Owin, Version=2.1.0.0

### ISSUE THREAD

**Issue by borap90** [dotnet/aspnetcore#33599]
Facing an issue while generating type library for our .NET Component which uses Microsoft.AspNet.SignalR.Core NuGet package (version 2.4.1). 
----------------------------------------------------------------------------------------------------------
Our .NET component, uses the below NuGet packages. 
Nuget Package							     Version			.NET Framework

jQuery									       3.5.1				.Net4.8
Microsoft.AspNet.Cors						       5.2.7				.Net4.8
Microsoft.AspNet.SignalR					       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.Core				       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.JS					       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.SystemWeb			       2.4.1				.Net4.8
Microsoft.Owin							       4.1.0				.Net4.8
Microsoft.Owin.Cors						       4.1.0				.Net4.8
Microsoft.Owin.Host.HttpListener			               4.1.0				.Net4.8
Microsoft.Owin.Host.SystemWeb				       4.1.0				.Net4.8
Microsoft.Owin.Hosting						       4.1.0				.Net4.8
Microsoft.Owin.Security						       4.1.0				.Net4.8
Newtonsoft.Json							       12.0.3			.Net4.8
Owin									       1.0				.Net4.8

The .NET component is in turn used by an unmanaged C++ component. 
For this, it is required to generate the type library of the .NET Component which is then referred within the unmanaged C++ classes. The problem happens when we try to invoke tlbexp command for the .NET Component.  The Type library export fails with the following error.

Microsoft (R) .NET Framework Assembly to Type Library Converter 4.8.3928.0
Copyright (C) Microsoft Corporation.  All rights reserved.

TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.Hub`1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM.
TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.IHubContext`1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM.
TlbExp : error TX0000 : Type library exporter encountered an error while processing 'TMNETBrowserIndependenceService.SignalRHub, TMNETBrowserIndependenceService'. Error: Type library exporter encountered an error while processing 'Microsoft.AspNet.SignalR.Owin.Middleware.HubDispatcherMiddleware, Microsoft.AspNet.SignalR.Core'. Error: Type library exporter cannot load type 'Microsoft.AspNet.SignalR.Owin.Middleware.HubDispatcherMiddleware' (error: Could not load file or assembly 'Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)).

As per the error message “error: Could not load file or assembly 'Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'”. It seems like the Microsoft.AspNet.SignalR.Core is looking for 'Microsoft.Owin, Version=2.1.0.0 which is not referenced within project (As per the table).
As you can see above, we are using Microsoft.Owin (v 4.1.0)
Checking the Microsoft.AspNet.SignalR.Core.dll using DotPeek (by JetBrains)  shows that the library refers to version 2.1.0.0 of Microsoft.Owin instead of the latest one.

We believe -
There should be backwards compatibility with Microsoft.Owin (4.1.0) 
If there is a dependency on Microsoft.Owin (2.1.0) for Microsoft.AspNet.SignalR.Core (2.4.1), then it should be flagged as a dependency.
Using Microsoft.Owin (2.1.0) with Microsoft.AspNet.SignalR.Core (2.4.1), gives the same error

Could you please let us know if there is a way to resolve this issue?
Also, is there another way to raise this - so that this can be resolved?

**Comment by BrennanConroy** [comment]
This issue was moved to SignalR/SignalR#4562
