### ISSUE TITLE
blazor - session status variables for components

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#33604]
While working with blazor, I came across an issue.
I can't start while(true) loops from inside components or they will run forever

I suggest adding some component lifetime variables, or events, such as:

OnComponentClose();
OnComponentInactive();

or a set of variables:
bool ComponentActive
bool UserOnSession

these will widely improve ease of life when working with those components

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The Dispose method of components is what you're looking for. Hope this helps: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-disposal-with-idisposable
