### ISSUE TITLE
in blazor, .net 3.1, Timers seem to remain undestroyed after page navigated away.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#33606]
To reproduce,
```
 if (Timer == null)
        {
            Timer = new System.Timers.Timer(100);
            Timer.Elapsed += ((Object source, System.Timers.ElapsedEventArgs e) =>
            {
                *do something
            });
            Timer.AutoReset = false;
            Timer.Enabled = true;
        }
```
Click a button on the page to go to another page.
Then come back using `backward` in browser.
this code wont run, seems like Timer isn't null.

**Comment by Xyncgas** [comment]
the variable Timer is declared as `System.Timers.Timer Timer = null;`

**Comment by Xyncgas** [comment]
it's not static

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Timers are disposable types and it's the developer's responsibility to dispose of such instances in their code, when they're not needed any more and/or when the owning components are disposed.

**Comment by Xyncgas** [comment]
It just gives me an impression that this way of it works is unnatural!!! In c++ we have object life-cycle with scopes or reference counting. What you just said made Timer sounded like a dangling pointer, it's bizarre to me!!! Do you have any idea why it is this way
