### ISSUE TITLE
Integration test working, production code failing

### ISSUE THREAD

**Issue by Rubenisme** [dotnet/aspnetcore#33601]
I'm not totally sure this should be a bug report, but the issue here is that I initially (I quickly understood why it didn't) had expected the integration test to fail and does not, but I'm not sure how to change it so that it does.

So we have a piece of code that calls uses a client package to call an API.

### To Reproduce
The client method looks like this
```
public Task UpdateMethod(string id, UpdateRequest updateRequest, CancellationToken cancellationToken)
{
    var url = $"api/UpdateApiMethod/{Uri.EscapeDataString(id)}";
    using (var request = new HttpRequestMessage(HttpMethod.Post, url) { Content = GetContent(updateRequest) })
    {
        return Call(request, cancellationToken);
    }
}

private async Task Call(HttpRequestMessage request, CancellationToken cancellationToken)
{
    using (var httpClient = _httpClientFactory.CreateClient(nameof(TheClient)))
    {
        using (var response = await httpClient.SendAsync(request, cancellationToken))
        {
            var content = await response.Content.ReadAsStringAsync(cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                throw new CustomException(response.StatusCode, content);
            }
        }
    }
}
```
And the (integration) test looks like:
```
public class IntegrationTests
{
    private const string Id = "0123456789";

    private WebApplicationFactory<Startup> _factory;
    private HttpClient _httpClient;
    private TheClient _theClient;

    private readonly Mock<IHttpClientFactory> _httpClientFactoryMock = new();

    [SetUp]
    public void SetUp()
    {
        _factory = new WebApplicationFactory<Startup>().WithWebHostBuilder(
            builder => builder.UseEnvironment("Development")
                              .ConfigureAppConfiguration((_, conf) => conf.AddJsonFile("appsettings.json")));

        var serviceProvider = _factory.Services;
        var httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

        _httpClient = _factory.CreateClient();
        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        _httpClientFactoryMock
            .Setup(m => m.CreateClient(nameof(TheClient)))
            .Returns(_httpClient);

        _theClient = new TheClient(httpClientFactory);
    }

    [TearDown]
    public void TearDown()
    {
        _httpClient?.Dispose();
        _factory?.Dispose();
    }

    [Test]
    public async Task TestUpdateOfProperty()
    {
        // Arrange
        var updateRequestModel = new UpdateRequest { PropertyThatNeedsUpdating = "somevalue" ;

        // Act
        await _theClient.UpdateOfProperty(Id, updateRequestModel, CancellationToken.None);

        // Assert
    }
}
```
You might have seen the mistake immediately but unfortunately this test will just run properly, while production code with the equivalent will with fail the exception below.

### Exceptions (if any)
**ObjectDisposedException**: Cannot access a disposed object. Object name: 'System.Net.Http.StringContent'.

How can I test that properly? The purpose of this test is to pretty much test the whole thing (of course excluding some mocks (not shown) that we have set up and tested elsewhere).

Of course I just fixed the mistake, but I would have liked to see this fail before finding out somewhere else.

**Comment by javiercn** [comment]
@Rubenisme can you please include the full call stack?

That said, you are mocking the HttpClient instance, which is likely why the test passes. We don't think this is an issue on the framework but something going on with your code.

**Comment by Rubenisme** [comment]
@javiercn Thanks for your quick response. While the client factory is mocked, the client returned when IHttpClientFactory.CreateClient is called is: _factory.CreateClient();

Or am I missing something?

I will include the call stack where it was originally thrown, the full one was either way too long or too short depending on whether 'just my code' was turned on or off:

> This exception was originally thrown at this call stack:
    System.Net.Http.HttpContent.CheckDisposed()
    System.Net.Http.HttpContent.CopyToAsync(System.IO.Stream, System.Net.TransportContext, System.Threading.CancellationToken)
    System.Net.Http.HttpConnection.SendRequestContentAsync(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpConnection.HttpContentWriteStream, bool, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Net.Http.HttpConnection.SendAsyncCore(System.Net.Http.HttpRequestMessage, bool, System.Threading.CancellationToken)

**Comment by javiercn** [comment]
@Rubenisme as I understand it works in the integration test but fails on production?

There are definitely differences in the implementation between the two, since the one in WAF uses an in memory handler.

I don't think we have enough context to help you here. We would need a minimal repro project (as a GH project) to make progress on this.

**Comment by Rubenisme** [comment]
@javiercn thanks again. Yes, I created a repo [here](https://github.com/Rubenisme/reproduce-request-disposed).

Running the 'integration' test works and you get into the receiving controller method. Run both sender and receiver and then send a request via swagger from the sender and you will see that it fails with the ObjectDisposedException exception and never hits the receiving controller method.

**Comment by javiercn** [comment]
`Call(request, cancellationToken);` needs to be awaited in 

```csharp
    using (var request = new HttpRequestMessage(HttpMethod.Post, url) { Content = GetContent(updateRequest) })
    {
        return await Call(request, cancellationToken);
    }
```

**Comment by Rubenisme** [comment]
@javiercn thanks, but I did know this and had already fixed this in the real code before raising this issue. It’s why I wrote this in the first message:

> How can I test that properly? The purpose of this test is to pretty much test the whole thing (of course excluding some mocks (not shown) that we have set up and tested elsewhere).
> 
> Of course I just fixed the mistake, but I would have liked to see this fail before finding out somewhere else.

The problem I have is that the test succeeds and didn’t find this error.

**Comment by Rubenisme** [comment]
I tried to look into it more deeply by debugging the SendAsync method but I cannot see where’re exactly it throws the DisposedException and why the test doesn’t. 

@mkArtakMSFT @javiercn can you you remove the resolved tag? The answer that was given was one to which I already had the answer. I propose that the test should have failed and my question is if you agree? If so can we change the test WAF framework so that it will, or can I change something myself to make the test fail in this scenario?
