### ISSUE TITLE
Interface color does not match C#

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#33623]
`IJSDataReference` is an interface, the generic type is colored like a class instead of an interface.

![image](https://user-images.githubusercontent.com/14852843/122477348-66a64880-cf7c-11eb-85a0-b3747196fa26.png)

The tool-tip matches the C# color for interfaces.

Version 17.0.0 Preview 1.0

**Comment by NTaylorMullen** [comment]
@dibarbet are interfaces expressed as a modifier?

**Comment by dibarbet** [comment]
We should just be using the LSP defined interface -
https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs,92

Are all interfaces getting tagged like this, or just certain instances

**Comment by NTaylorMullen** [comment]
Ahhhh @dibarbet looks like the LSP platform doesn't differentiate: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FTagger%2FSemanticTokensTaggerBase.cs&version=GBdevelop&line=441&lineEnd=441&lineStartColumn=17&lineEndColumn=51&lineStyle=plain&_a=contents

There an issue on the C# side we can dupe with?

**Comment by dibarbet** [comment]
Not sure, didn't see one after a cursory search - @allisonchou may know of one

**Comment by allisonchou** [comment]
I don't think there's an issue on the C# side, but as a workaround, I think we can just add interfaces to the list of [Roslyn's hardcoded token types](https://devdiv.visualstudio.com/DevDiv/_search?text=RoslynSemanticTokenTypes&type=code&pageSize=25&filters=ProjectFilters%7BDevDiv%7DRepositoryFilters%7BVSLanguageServerClient%7D&action=contents&result=DefaultCollection%2FDevDiv%2FVSLanguageServerClient%2FGBdevelop%2F%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FExtensions%2FRoslynSemanticTokenTypes.cs). I can get out a PR to do this soon

**Comment by allisonchou** [comment]
This was addressed in https://github.com/dotnet/roslyn/pull/54412

**Comment by NTaylorMullen** [comment]
> This was addressed in [dotnet/roslyn#54412](https://github.com/dotnet/roslyn/pull/54412)

Woooo!
