### ISSUE TITLE
ASP.NET Core 6.0 SPA templates 支持VUE3.0

### ISSUE THREAD

**Issue by ghd258** [dotnet/aspnetcore#33626]
ASP.NET Core 6.0 SPA templates 支持 VUE3.0

**Comment by blowdart** [comment]
There are no plans to add another javascript framework to the spa templates. 

There is a [community template](https://github.com/NetCoreTemplates/vue-spa) you could try.

**Comment by javiercn** [comment]
@ghd258 thanks for contacting us.

@blowdart answer is correct.
