### ISSUE TITLE
RedisCache Broken in .net 6

### ISSUE THREAD

**Issue by los93sol** [dotnet/aspnetcore#33628]
I will update this in the morning when I’m back to my box, but wanted to put this out there now.

starting with .NET 6 Preview 1, Microsoft.Extensions.Caching.StackExchangeRedis is broken.  The SetScript was changed from HMSET to HSET and when calling Set or SetAsync results in an invalid number of args error for the lua script.  Rolling back to 5.0.6 resolves the issue.  From my testing I’m pretty sure https://github.com/dotnet/aspnetcore/commit/bf4d9b9bd0d11e4e46924e4e09014580ec1a1449#diff-864fe17644db62a3e03b1dc57457f6f6786151f3041977d984a8435095ae18b2 is the cause.

**Comment by JunTaoLuo** [comment]
Can you share the error you are seeing @los93sol? 

I suspect it has to do with the Redis version used. We changed to using HSET, which should work on Redis >4.0.0. We need to revisit the decision wrt backwards compatibility.

**Comment by JunTaoLuo** [comment]
FYI it looks like the current supported version of Redis are > 5.2: https://docs.redislabs.com/latest/rs/administering/product-lifecycle

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.

**Comment by los93sol** [comment]
My apologies for the delay, the error is
ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script

Tried both with the latest version of redis in docker and the old 2.4.5 windows binary
