### ISSUE TITLE
SignalR JS client fails to send out ping message

### ISSUE THREAD

**Issue by vicancy** [dotnet/aspnetcore#33629]
### Describe the bug
We have a customer here that the client failed to send out the ping messages on time sometimes when for example the server->client messages are frequent

![image](https://user-images.githubusercontent.com/668244/122498397-a2dfb480-d021-11eb-893e-00d4246be5c8.png)

### Version
- JS SignalR client: @microsoft/signalr 5.0.6

**Comment by jkmchinese** [comment]
May be related to this problem and relationship: [Chrome-terminates-WebSocket-conenction](https://github.com/SignalR/SignalR/issues/4536)

btw, What tools did you use to capture WS

**Comment by BrennanConroy** [comment]
Closing as I don't think there is an issue here. Talked to customer offline and they had some weird behavior that could be related to browser tabs sleeping.
