### ISSUE TITLE
Need a way to determine from a Razor tag helper syntax node if indentation will be affected

### ISSUE THREAD

**Issue by davidwengier** [dotnet/aspnetcore#33630]
I don't know if this is a request for a new API, or just a cry for help, but I'll take what I can get.

For Razor formatting to be correct it currently needs to understand the expected indentation level of C# code in the generated designer file. As it traverses the syntax tree for the Razor document it assumes that any `MarkupTagHelperElementSyntax` that is a component (determined by calling `Microsoft.AspNetCore.Razor.Language.TagHelperDescriptorExtensions.IsComponentOrChildContentTagHelper()`) will result in an increase of indentation. Unfortunately this isn't always true, but I can't see (from inspecting in the debugger) any way to find a better answer.

As an example, given this Razor source:
```
<CascadingAuthenticationState>
    <Router AppAssembly=""@typeof(Program).Assembly"">
        <Found Context=""routeData"">
            <RouteView RouteData=""@routeData"" DefaultLayout=""@typeof(MainLayout)"" />
        </Found>
        <NotFound>
            <LayoutView Layout=""@typeof(MainLayout)"">
                <p>Sorry, there's nothing at this address.</p>

                @if (true)
                {
                    <strong></strong>
                }
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

This results in the following heirarchy in the generated code for the `@if (true)`:
```
__builder.AddAttribute(-1, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((__builder2) =>
{
    __builder2.AddAttribute(-1, "NotFound", (Microsoft.AspNetCore.Components.RenderFragment)((__builder3) =>
    {
        __builder3.AddAttribute(-1, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((__builder4) =>
        {
            if (true)
            {
            }
        }
        ));
        __o = typeof(LayoutView);

    }
    ));
    __o = typeof(Router);
}
));
__o = typeof(CascadingAuthenticationState);
```

So in the Razor syntax tree the `@if (true)` is under 4 components, but in the generated code its only part of 3 nested lambdas. It looks like the `Router` component doesn't cause a RenderFragment lambda to be created, but I can't see any way to determine that.

Is there a way? If not, can there be an API added that would return that information? Perhaps a new extension method on Microsoft.AspNetCore.Razor.Language.TagHelperDescriptorExtensions`?

Thank you for any help you can give me!

**Comment by NTaylorMullen** [comment]
@pranavkm @captainsafia @SteveSandersonMS could you advise

**Comment by SteveSandersonMS** [comment]
> So in the Razor syntax tree the @if (true) is under 4 components, but in the generated code its only part of 3 nested lambdas. It looks like the Router component doesn't cause a RenderFragment lambda to be created, but I can't see any way to determine that.

There are two different kinds of things in the source that are syntactically identical, and can only be distinguished based on the generated tag helpers' parameter lists:

 * ChildContent blocks
 * Named RenderFragement parameters

Both of them are represented as tags in the markup. In this case:

```razor
<CascadingAuthenticationState>
    <Router AppAssembly=""@typeof(Program).Assembly"">
        <Found Context=""routeData"">
            <RouteView RouteData=""@routeData"" DefaultLayout=""@typeof(MainLayout)"" />
        </Found>
        <NotFound>
            <LayoutView Layout=""@typeof(MainLayout)"">
                <p>Sorry, there's nothing at this address.</p>

                @if (true)
                {
                    <strong></strong>
                }
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

`Found` and `NotFound` are both named parameters on `Router`. They aren't components in their own right. This can be identified by looking at the list of parameters to `Router` and observing that it has `[Parameter] RenderFragment Found { get; set; }` (and equivalent for `NotFound`).

Does that make sense of the difference?

**Comment by davidwengier** [comment]
That does make sense, yes, thank you. Are they mutually exclusive though? ie, if a tag helper has at least one named RenderFragment parameter does that mean it won't have ChildContent (and therefore it's safe to assume it won't get a nested lambda generated)?

**Comment by SteveSandersonMS** [comment]
@davidwengier No, the rule is:

If the immediate child element matches up with a named parameter, then *all* the immediate child elements have to match up with named parameters. One of those parameters might be called `ChildContent`, since it ceases to have a special meaning if you're passing multiple content values. Example:

```
<MyComponent>
    <NamedParameter1>Some content for NamedParameter1</NamedParameter1>
    <NamedParameter2>Some content for NamedParameter2</NamedParameter2>
    <ChildContent><UnrelatedComponent>Hey there</UnrelatedComponent><div>This is nice</div></ChildContent>
</MyComponent>
```

But the same `MyComponent` could also be used like this:

```
<MyComponent NamedParameter1="@someValue" NamedParameter2="@anotherValue">
    <UnrelatedComponent>Hey there</UnrelatedComponent>
    <div>This is nice</div>
</MyComponent>
```

Since `UnrelatedComponent` isn't a named parameter for `MyComponent`, the entirety of the markup inside `MyComponent` gets interpreted as a single parameter named `ChildContent`. In other words, it's exactly equivalent to this:

```
<MyComponent NamedParameter1="@someValue" NamedParameter2="@anotherValue">
    <ChildContent>
        <UnrelatedComponent>Hey there</UnrelatedComponent>
        <div>This is nice</div>
    </ChildContent>
</MyComponent>
```

This is intended to give flexibility. In cases where you're only using the element's contents to supply a single `RenderFragment` parameter and it is named `ChildContent`, then as a shorthand you can just dump its contents directly inside the component tag without surrounding it with the name of that parameter. In other cases you must specify the names of the parameters completely.

**Comment by davidwengier** [comment]
Thank you for the excellent explanation and examples, that has resolved the issue for me!
