### ISSUE TITLE
Dotnet Watch Net 6 Preview 5: The model item passed into the ViewDataDictionary is of type X but this ViewDataDictionary instance requires a model item of type X.

### ISSUE THREAD

**Issue by phillipmunn** [dotnet/aspnetcore#33636]
### Describe the bug

Unable to use 'dotnet watch' with Net 6.0 Preview 5.
Any attempt to launch the project using the 'dotnet watch' command results in the application failing to launch.

All our models in razor pages are flagged as invalid with an error that says the type X does not match the expected type of X - despite them being the same model.

E.g. 
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Opsyte.API.Portal.EnquiryDTO', but this ViewDataDictionary instance requires a model item of type 'Opsyte.API.Portal.EnquiryDTO'.

Running without 'watch' (hot reload) does not reproduce the error. This error is therefore related to dotnet watch / hot reload.

### To Reproduce

Unfortunately I cannot share the project due to confidentially issues.

ASP.NET MVC project.
Create some pages with Controllers/Views. In the .razor views we reference models which are generated automatically using NSwag. Run the project using 'dotnet watch'. Observe any page that contains a model does not work.

The error message confusingly says the type X does not match the expected type X.

### Exceptions (if any)

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Opsyte.API.Portal.EnquiryDTO', but this ViewDataDictionary instance requires a model item of type 'Opsyte.API.Portal.EnquiryDTO'.

Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Opsyte.API.Portal.DashboardDTO', but this ViewDataDictionary instance requires a model item of type 'Opsyte.API.Portal.DashboardDTO'.

Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)

### Further technical details
Visual Studio 16.11.0 Preview 2.0

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by phillipmunn** [comment]
Update @Pilchie. I found the cause of the problem:

<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.4" />

services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
                config.Filters.Add(new AuthorizeFilter(policy));
                config.Filters.Add(new ErrorHandlingFilter());
            }).AddRazorRuntimeCompilation();
            
          I had a reference to the Mvc.Razor.RuntimeCompilation in the project and therefore this must conflict with the new hot reload work in .NET 6. The error message is obviously confusing.
          
          Perhaps you can improve this by making the tools detect this package and ensure developers remove it?

**Comment by Pilchie** [comment]
Tagging @pranavkm for this.

**Comment by mkArtakMSFT** [comment]
Thanks  for contacting us, @phillipmunn.
We've changed a lot in this area. Can you please try out the latest RC1 release and let us know if you still face this issue? Thanks!

**Comment by phillipmunn** [comment]
I can no longer reproduce this issue in the latest RC1 release. So I believe this issue can be closed.
