### ISSUE TITLE
Hot reload is not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33654]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hot-reload-is-not-working/1449489)._

---
[severity:It's more difficult to complete my work]
I have a blazor-server project that I have "migrated" to .net6 preview 4 and followed these steps :
https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload/
However hot-reload is still not working for me.
*My VS version is 16.11.0 Preview 1.0

---
#### Feedback Bot on 6/14/2021, 11:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
