### ISSUE TITLE
TlsHandshakeFailure_EmitsStartAndStopEventsWithActivityIds

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#33656]
## Error Message

``` text
Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.EventSourceTests.TlsHandshakeFailure_EmitsStartAndStopEventsWithActivityIds()
[xUnit.net 00:00:04.72]         --- End of stack trace from previous location ---
  Passed ChunkFramingAndExtensionsCountTowardsRequestBodySize [261 ms]
  Passed CertificatePassedToHttpContext(httpProtocols: Http1) [249 ms]
  Passed HEADERS_Received_Path_DecodedAndNormalized(input: "/a/b/c/.%2E/d", expected: "/a/b/d") [336 ms]
  Failed TlsHandshakeFailure_EmitsStartAndStopEventsWithActivityIds [496 ms]
  Error Message:
   Assert.Equal() Failure
                       (pos 12)
Expected: TlsHandshakeFailed
Actual:   TlsHandshakeStop
                       (pos 12)
```

## Stacktrace

``` text
     at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.EventSourceTests.TlsHandshakeFailure_EmitsStartAndStopEventsWithActivityIds() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/EventSourceTests.cs:line 334
--- End of stack trace from previous location ---
```

## Build

aspnetcore-helix-matrix runs failed on Windows.7.Amd64.Open in
- https://dev.azure.com/dnceng/public/_build/results?buildId=1191726&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=1193923&view=results

**Comment by dougbu** [comment]
Both runs were for release/5.0. @halter73 should we backport fe6a3fc747096308ac3acdf7d72437f6955490d5 (or at least the src/Servers/Kestrel/test/InMemory.FunctionalTests/EventSourceTests.cs portion) to that branch to clean this up❔ And why does the test work sometimes on Win7❔

@mmitche @lukas-lansky will the release/5.0 branch be open for test fixes on Monday❔ I can quarantine the test today if we're not done the final build but want @halter73's opinion.

**Comment by lukas-lansky** [comment]
@dougbu We have a candidate for the servicing release being finished right now, but I that shouldn't stop us from accepting test fixes. Definitely open a PR; thanks!

**Comment by mmitche** [comment]
@dougbu Don't think so. I think wait for the next cycle.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/33714
