### ISSUE TITLE
Can I use the "blazor webAssembly" in ".cshtml" for "MVC or RazorPage"?

### ISSUE THREAD

**Issue by ShuiFan0** [dotnet/aspnetcore#33661]
I am trying to do use the "blazor webAssembly" in ".cshtml" for "MVC or RazorPage" but I not found the way.
So,I show the idea to you.

```
@page
@model SF0.Base.Razor.Areas.MyFoup.Pages.Config.IndexModel
@{
   var Title="Config"
   //other server run
}//run in web server
<p>
   @Title@TitleMore
   <!--"@Title" is set in web server-->
   <!--"@TitleMore" is set in user web client-->
   <!--other(as "@Model") is run in  web server, but if define in "@code" is setting in  user web client. -->
</p>

@code {
   //run in user web client
    public string TitleMore { get; set; }
}
```

**Comment by javiercn** [comment]
@ShuiFan0 thanks for contacting us.

You need to use the `Component` tag helper to render a root component.

**Comment by ShuiFan0** [comment]
> @ShuiFan0 thanks for contacting us.
> 
> You need to use the `Component` tag helper to render a root component.

I'm find the doc.Then, I will try to do.If it's runing as me wish, you are very good.

**Comment by ShuiFan0** [comment]
> @ShuiFan0感谢您与我们联系。
> 
> 您需要使用`Component`标签助手来呈现根组件。

I'm sorry.I read the document carefully and I found mistakes in my presentation.
My real hope is using Blazor WebAssembly in RazorClassLib(AddRazorSupportForMvc is true) ,without  BlazorClient，All in RazorClassLib.
