### ISSUE TITLE
Add easier way to name endpoints for easier link generation

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#33687]
Today it's possible to use the `LinkGenerator` to generate links to arbitrary endpoints but it's a little inconvenient to do this for endpoints that exists outside of MVC because they don't have intrinsic names or route values (like "controller" and "action").

Here's an example of what this looks like this today:

```C#
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/", (LinkGenerator linkGenerator) =>
{
    return linkGenerator.GetPathByName("todos", values: new { id = 13 });
});

app.MapGet("/todos/{id}", (int id) => { }).WithMetadata(new EndpointNameMetadata("todos"));

app.Run();
```

Some ideas:
- We add an extension method WithName to hide the explict metadata addition.
-  Automatically infer some defaults based on route template.
- Automatically infer some defaults based on method name (if not compiler generated).

**Comment by javiercn** [comment]
I might be saying the same things as you, but here are some  thoughts:
* If using a local function, automatically use that name.
* If using a lambda, consider having an attribute `[EndpointName]` `[RouteName]` that you can apply to it.
* You can also have a separate overload `template, name, action` to do this.
* You could default to `/todos/{id}` as the default name, although it can get ambiguous.

**Comment by pranavkm** [comment]
@davidfowl please speak to @javiercn if you need something specific for 6.0.

**Comment by davidfowl** [comment]
Yes I'd like this for .NET 6, it's part of the minimal APIs end to end.

**Comment by DamianEdwards** [comment]
@davidfowl this can be closed now yes?

**Comment by davidfowl** [comment]
Yep. Closing.
