### ISSUE TITLE
ModelMetadataType & MetadataType not working in webapi

### ISSUE THREAD

**Issue by chin-udara** [dotnet/aspnetcore#33681]
### Describe the bug
The following code using `ModelMetadataType` or `MetadataType` does not work as it should.

### To Reproduce

model class
```
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;

namespace webapi.models
{
  public partial class MyClass
  {
    public int id { get; set; }
  }

  [ModelMetadataType(typeof(MyClassMeta))]
  public partial class MyClass {}

  public class MyClassMeta
  {
    [JsonPropertyName("myid")]
    public int id { get; set; }
  }
}
```

controller class
```
[HttpPost]
public ActionResult<MyClass> save([FromBody]MyClass myobj) {
    return myobj;
}
```

### Current output in Swagger
`{ "id": 0 }`

### Expected output in Swagger
`{ "myid": 0 }`

### Exceptions (if any)
No Exceptions

### Further technical details
- ASP.NET Core version = dotnet 5
- The IDE - VS Code using dotnet CLI on Ubuntu 20.04.2 LTS

**Comment by chin-udara** [comment]
Any update on this please? Or have I missed anything in the code?

**Comment by pranavkm** [comment]
Thanks for the issue report @chin-udara. ModelMetadataType is a MVC specific type that only affects model binding and validation. It does not formatting performed by System.Text.Json, Json.NET etc.
