### ISSUE TITLE
Hot Reload doesn't work when you make any change in Shared/NavMenu.razor

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#33695]
### Describe the bug
Hot Reload doesn't work when you make any change in Shared/NavMenu.razor

![image](https://user-images.githubusercontent.com/18366446/122685781-baa66c80-d1ca-11eb-8804-81067dc2226b.png)

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new blazorserver app ( I tested using blazorwasm and it doesnt work there as well )
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Open Shared/NavMenu.razor
- Add a new nav item or change the text of an existing nav item and hit save
- You will see the app crash with the error: Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### Further technical details
- Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.5.21302.13/

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE: VS Code
![image](https://user-images.githubusercontent.com/18366446/122685761-a1052500-d1ca-11eb-96b0-be7d054b4a2e.png)

**Comment by pranavkm** [comment]
Could you try running `dotnet watch` with the `--no-hot-restart` switch? It's fixed in preview6, but this should fix it in preview5

**Comment by MacdonaldRobinson** [comment]
Thanks @pranavkm running the app using "dotnet watch --no-hot-restart" fixes the issue!

![image](https://user-images.githubusercontent.com/18366446/122687176-60a9a500-d1d2-11eb-8147-aa026af2d8d9.png)

**Comment by pranavkm** [comment]
Thanks for confirming. It was an experiment, that as you saw with the exception, didn't pan out too well.
