### ISSUE TITLE
[Blazor] JS Interop - Call JS from C# - Promise Handling Problem

### ISSUE THREAD

**Issue by SSgumS** [dotnet/aspnetcore#33698]
### Describe the bug
If the promise is rejected, `InvokeVoidAsync`/`InvokeAsync` does not throw any exceptions and doesn't get completed.

### To Reproduce
C#:
```
var task = JSRef.InvokeVoidAsync("ThrowError");
await task;
Console.WriteLine(task.IsCompletedSuccessfully);
```
JS:
```
async function ThrowError() {
    await asynctask();
    throw new Error("My Error");
}
```
Console:
```
# no output. It awaits indefinitely.
```

### Further technical details
- ASP.NET Core version: 5.0.7

**Comment by javiercn** [comment]
@SSgumS thanks for contacting us.

Can you give us more details on your environment? Is this Blazor Server or Webassembly? 

What Blazor version are you using (3.1, 5.0, 6.0 preview5).

Could you provide a publicly accessible github repo with a minimal repro project and detailed steps on how to trigger the issue?
