### ISSUE TITLE
RequestDelegateFactory should take an optional set of route pattern names or route parameter names

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#33700]
## Background and Motivation

This would allow unattributed methods to disambiguate between route and query string when the method parameters are unattributed. Today we generate code that prefers route over query string and we could avoid that in certain cases. It would also allow us to better fail if the user used `[FromRoute]` and there was no route parameter with that name defined.

## Proposed API

Since our overloads are getting a bit crazy with this change, I suggest we add an options object to handle the overflow.

```diff
public static class RequestDelegateFactory
{
-    public static RequestDelegate Create(Delegate action, IServiceProvider? serviceProvider)
+    public static RequestDelegate Create(Delegate action, Func<HttpContext, object>? targetFactory = null, RequestDelegateFactoryOptions? options = null)
-    public static RequestDelegate Create(MethodInfo methodInfo, Func<HttpContext, object>? targetFactory = null, IServiceProvider? serviceProvider)
+    public static RequestDelegate Create(MethodInfo methodInfo, Func<HttpContext, object>? targetFactory = null, RequestDelegateFactoryOptions? options = null)
}

+ public class RequestDelegateFactoryOptions
+ {
+     public IServiceProvider? ServiceProvider { get; init; }
+     public IReadOnlyList<string>? RouteParameterNames { get; init; }
+ }
```

## Usage Examples

``` C#
var options = new RequestDelegateFactoryOptions 
{ 
    ServiceProvider  = serviceProvider, 
    RouteParameterNames  = new[] { "id" }
};

var rd = RequestDelegateFactory.Create((int id) => id, options: options);
```

## Alternative Designs

A single static method with optional parameters.

```diff
public static class RequestDelegateFactory
{
+    public static RequestDelegate Create(MethodInfo methodInfo, Func<HttpContext, object>? targetFactory = null, IServiceProvider? serviceProvider = null, IReadOnlyList<string>? routeParameterNames = null);
}
```

## Risks

None

**Comment by davidfowl** [comment]
MVC skips binding sources that aren't from the request and that solves this problem, see https://github.com/dotnet/aspnetcore/blob/a9a6831a1a0aa2fc21c276e1f28b86a2b1cdbb28/src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs#L212

https://github.com/dotnet/aspnetcore/blob/a9a6831a1a0aa2fc21c276e1f28b86a2b1cdbb28/src/Mvc/Mvc.Abstractions/src/ModelBinding/BindingSource.cs#L84


cc @pranavkm

**Comment by halter73** [comment]
I almost used IsFromRequest instead of specifically checking for BindingSource.Services in https://github.com/dotnet/aspnetcore/pull/33727, but I didn't want to depend too much on BindingSource logic/conventions. The only other default non-IsFromRequest is BindingSource.Special.

I guess we could use BindingSource.Special to represent CancellationToken, HttpContext and things like that. Now those are just "services" as far as the EndpointMetadataApiDescriptionProvider is concerned but I don't think this matters much since it's all internal anyway.

**Comment by davidfowl** [comment]
I put this text on the wrong issue..

**Comment by pranavkm** [comment]
```diff
+ public class RequestDelegateFactoryOptions
+ {
+     public IServiceProvider? ServiceProvider { get; init; }
-     public IReadOnlyList<string>? RouteParameterNames { get; init; }
+    public IEnumerable<string>? RouteParameterNames { get; init; }
+ }
