### ISSUE TITLE
Remove Utf8EncodingSealed from Kestrel

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/aspnetcore#33713]
Context:

https://github.com/dotnet/aspnetcore/blob/574a3ff36ab54421dd4f82b4168ad6bf61750e2d/src/Servers/Kestrel/Core/src/Internal/Infrastructure/HttpUtilities.cs#L528-L534

All consumers of this API pass the parameter around (via _DefaultRequestHeaderEncoding_) as an `Encoding` parameter to non-inlineable method. As a result, accesses to this instance will not be devirtualized. End result is that this class introduces a new type and doesn't realize any perf benefit.

Suggest using `new UTF8Encoding(false, true)` instead.

**Comment by halter73** [comment]
@GrabYourPitchforks. I assume you're referring to GetAsciiOrUTF8StringNonNullCharacters as the "non-inlineable method". Out of curiosity, what makes it non-inlinable for sure? That it's unsafe, throws, and/or is too large?

I suppose we could have a separate branch and method that always uses UTF8EncodingSealed, but I doubt it's worth it.

**Comment by GrabYourPitchforks** [comment]
> Out of curiosity, what makes it non-inlinable for sure? That it's unsafe, throws, and/or is too large?

Some combination of all three, plus the fact that the code isn't actually calling any virtual methods on the incoming parameter. It's calling a non-virtual method, which calls a helper, which calls a helper, which eventually dispatches to the virtual method. But by this time the call stack is significantly deep enough that any relevant context behind what the original parameter was has been lost.

**Comment by PublicFedorenko** [comment]
@GrabYourPitchforks. To clarify what should be done:
1. Remove `UTF8EncodingSealed` class.
2. Change `DefaultRequestHeaderEncoding` type to `UTF8Encoding`.

> Suggest using `new UTF8Encoding(false, true)` instead.

Should the parameters to `UTF8Encoding()` be named for better transparency?
`= new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);`

**Comment by halter73** [comment]
> Should the parameters to UTF8Encoding() be named for better transparency?

I think so, since `: base(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true)` will no longer be there.

**Comment by PublicFedorenko** [comment]
Yes, exactly!
At this point, I would be happy to create a PR, if there are no important details missed

**Comment by halter73** [comment]
Go for it!
