### ISSUE TITLE
Add default implementation for HttpContext.WebSockets.IsWebSocketRequest

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#3372]
We should provide a default implementation for this property, even when there is no feature installed. There's nothing in the logic for detecting a WebSocket request that inherently requires the middleware. This property should just check for:

* `Connection: Upgrade` header
* `Upgrade: WebSocket` header

It's still up to the middleware to validate the `Sec-WebSocket-*` headers during `Accept`. Any request with the above two headers should be considered a WebSocket request though, even if the other headers are invalid (then it's an *invalid* WebSocket request).

**Comment by Tratcher** [comment]
IsWebSocketRequest in the middleware considers Method, Upgrade, Connection, SecWebSocketKey, and SecWebSocketVersion. It would be weird for IsWebSocketRequest to return true before the middleware and false afterwards. If this check is reduced it should be done consistently in both implementations.

https://github.com/aspnet/WebSockets/blob/cff748cad3c8087649e82aa2420ad2347d40404e/src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs#L64-L82
https://github.com/aspnet/WebSockets/blob/cff748cad3c8087649e82aa2420ad2347d40404e/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs#L16-L22

**Comment by anurse** [comment]
Sure, we can just do it all if that makes sense.

**Comment by Eilon** [comment]
What repo would the fix go in? WebSockets?

**Comment by Tratcher** [comment]
HttpAbstractions

**Comment by anurse** [comment]
Oops, yeah I meant to put the repo tag on :).

**Comment by anurse** [comment]
Maybe I'll take a stab at this. It should just mean sharing some code between WebSockets and here.

**Comment by anurse** [comment]
As a reminder, we **can't** provide a default implementation of the feature since SignalR depends upon the feature being `null` when running on IIS in Win 7 to detect that WebSockets isn't present.

**Comment by davidfowl** [comment]
@BrennanConroy do you think this is important still?

**Comment by BrennanConroy** [comment]
Low priority, haven't heard any customer complaints about this.

**Comment by davidfowl** [comment]
Closing it then.
