### ISSUE TITLE
Create IResult-returning static methods 

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#33729]
`IResult`-returning static methods would allow something like `using static Microsoft.AspNetCore.Http.Results` and makes for better return type inference for IResult-returning lambdas, so you don't have to do casting like the following you have to do using constructors today.

```c#
app.MapGet("/todos/{id}", async (int id) =>
{
    using var db = new TodoDbContext(options);
 
    if (await db.Todos.FindAsync(id) is not Todo todo)
    {
        return (IResult)new NotFoundResult();
    }
 
    return new JsonResult(todo);
})
```

With, `IResult` returning `NotFound` and `Ok` methods the `(IResult)` casting can be removed.

```c#
app.MapGet("/todos/{id}", async (int id) =>
{
    using var db = new TodoDbContext(options);
 
    if (await db.Todos.FindAsync(id) is not Todo todo)
    {
        return NotFound();
    }
 
    return Json(todo);
})
```

**Comment by davidfowl** [comment]
We should start with these methods and remove a bunch:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase?view=aspnetcore-5.0

cc @pranavkm

**Comment by davidfowl** [comment]
@pranavkm [StatusCodeResult](https://github.com/dotnet/aspnetcore/blob/640b77f0823f9de872359aa174669efbbd742e72/src/Mvc/Mvc.Core/src/StatusCodeResult.cs#L17) still implements IResult. Is that intentional?
