### ISSUE TITLE
Blazor Server template open-iconic issues

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#33738]
Repro steps:

- Install .NET 6 Preview 7 (6.0.100-preview.7.21321.6)
- `dotnet new blazorserver -o BlazorApp`
- `cd BlazorApp`
- `dotnet watch`

Expected result: App runs cleanly

Actual result:

![image](https://user-images.githubusercontent.com/1874516/122865099-a2be0e00-d2da-11eb-912d-25daee688141.png)

```
Failed to decode downloaded font: https://localhost:5001/css/open-iconic/font/fonts/open-iconic.woff
localhost/:1 OTS parsing error: incorrect file size in WOFF header
localhost/:1 Failed to decode downloaded font: https://localhost:5001/css/open-iconic/font/fonts/open-iconic.ttf
localhost/:1 OTS parsing error: cvt : invalid table offset
localhost/:1 Failed to decode downloaded font: https://localhost:5001/css/open-iconic/font/fonts/open-iconic.otf
localhost/:1 OTS parsing error: CFF : table overruns end of file
```

**Comment by danroth27** [comment]
Also repros with .NET 6 Preview 6 (6.0.100-preview.6.21321.10).

**Comment by captainsafia** [comment]
I haven't been able to repro this on `6.0.100-preview.6.21276.12` and `Google Chrome | 91.0.4472.114 (Official Build) (arm64)`

**Comment by captainsafia** [comment]
OK I was able to repro this on 6.0.100-preview.7.21322.1 though. And I'll trust that it also repros on 6.0.100-preview.6.21321.10, so the regression happened between then.

**Comment by danroth27** [comment]
@captainsafia Can you look into this for Preview 6? I don't think we want to ship the templates this way 😝
