### ISSUE TITLE
Should Blazor AOT still be downloading dlls?

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#33730]
### Describe the bug

When running AOT build I am seeing the blazor.wasm file increase size from 398KB to 3.6MB which matches my expectations.

However, I am also still seeing the dlls being downloaded, these look exactly the same files and sizes as per the non-AOT application. My assumption was that these would no longer be required, or would be `.wasm` instead?

### To Reproduce
Load dev tools, clear application data. Navigate to AOT compiled site.

Dlls are still downloaded as well as wasm file.

![image](https://user-images.githubusercontent.com/12847647/122836978-35ff3f80-d2eb-11eb-97c0-01e2b8fed713.png)
![image](https://user-images.githubusercontent.com/12847647/122837002-40b9d480-d2eb-11eb-80a4-041550945308.png)

### Further technical details
Following notes from here: https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#blazor-webassembly-ahead-of-time-aot-compilation

Prerendering the wasm app in server project.

From the Client csproj:
```
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RunAOTCompilation>true</RunAOTCompilation>
  </PropertyGroup>
  ```
I appreciate that I might not of fully understood how AOT is working, in which case I apologise for wasting time. I would appreciate a link to some more information as to how it all works :)

**Comment by javiercn** [comment]
@srpeirce thanks for contacting us.

I believe this is a known (temporary) behavior. @pranavkm can you confirm?
