### ISSUE TITLE
 Copy task in Microsoft.AspNetCore.Mvc.Testing.targets has missing UseHardlinksIfPossible and UseSymlinksIfPossible

### ISSUE THREAD

**Issue by dashkodo** [dotnet/aspnetcore#33757]
When enabling multiple msbuild nodes it could fail due to locking "xxx.deps.json" files
We have faced with this issue using latest version of microsoft.aspnetcore.mvc.testing nuget package
C:\ZZZZ\nuget\microsoft.aspnetcore.mvc.testing\5.0.7\build\net5.0\Microsoft.AspNetCore.Mvc.Testing.targets(56, 5): error MSB3027: Unable to copy file "D:\XXXX\bin\Release\YYYY.deps.json" to "bin\Release\YYYY.deps.json". The process cannot access the file 'bin\Release\YYYY.deps.json' because it is being used by another process.

**Comment by javiercn** [comment]
@dashkodo thanks for contacting us.

We see that you've sent us a PR for this issue. We've left some comments on it.

**Comment by dashkodo** [comment]
@javiercn 
>I've made a suggestion since we normally use _ for things we don't want people to depend on or configure individually (like this).

The default value should also come from the standard CreateHardLinksIfPossible (or however is named in copy files) since that's the single switch users turn on or off

**Comment by BurakTaner** [comment]
Looks like PR related to this issue is merged. should we close or any plan for future ? @captainsafia

**Comment by captainsafia** [comment]
Yes, this is resolved as of .NET 8. TY for the nudge, @BurakTaner!
