### ISSUE TITLE
SignalR: when streaming from client to server, if client completes channel with an exception, channelreader.WaitToReadAsync execution is blocked on the server.

### ISSUE THREAD

**Issue by arnab-1995** [dotnet/aspnetcore#33753]
### Describe the bug
Hi, we are streaming some messages from a .NET console app to a SignalR server. On the client, we have the below code
```
var channel = Channel.CreateUnbounded<object>();
await hubConnection.SendAsync("TestUpstream", channel.Reader);
await channel.Writer.WriteAsync("some data");
await channel.Writer.WriteAsync("some more data");
channel.Writer.Complete(new Exception("an error occurred"));
```

On the server, we have the "TestUpstream" hub method as below 
```
        public async Task TestUpstream(ChannelReader<object> stream)
        {
            try
            {
                while (await stream.WaitToReadAsync())
                {
                    while (stream.TryRead(out object item))
                    {
                        Console.WriteLine(item);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error occurred while reading from stream, Exception: " + ex.Message);
            }
        }
```
When the channel is completed with an exception on the client, then on the server, the stream.WaitToReadAsync() task is not completed with the exception as per docs. Instead the execution is blocked on this line.

### To Reproduce
I have created sample repos for both SignalR client & server to reproduce the above behavior. Please find the links below
SignalR Client : https://github.com/arnab-1995/TestSignalRClient
SignalR Server : https://github.com/arnab-1995/TestSignalRServer

### Further technical details
- .NET Core version 3.1
- SignalR Client version 3.1.0

**Comment by BrennanConroy** [comment]
Surprised this hasn't been hit before!

As a workaround either Complete without an exception or pass a cancellation token to `SendAsync` and cancel that instead of Completing the channel.

**Comment by arnab-1995** [comment]
Is there any chance this fix can be made available in .NET Core 3.1, it being an LTS version?

**Comment by BrennanConroy** [comment]
Unlikely, there is a simple workaround (don't complete with an exception), and 6.0 will be an LTS with the fix.
