### ISSUE TITLE
Urls with space in query string cause Kestrel to return a 505 HTTP Version Not Supported

### ISSUE THREAD

**Issue by brianfeucht** [dotnet/aspnetcore#33769]
### Describe the bug
HTTP requests with a unencoded space character causes Kestrel to return with a `505 HTTP Version Not Supported` error.  I need to be able to handle this condition in my app, but the way this error is getting handled doesn't allow me to intercept it in any middleware.  

### To Reproduce
Any Kestrel console app will do.  I am reproducing with just an empty host setup.  You need to run the app from the console as IIS express and IIS will cause different behavior.  

```
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
            await host.RunAsync();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                // .UseDependencyModuleServiceProvider<FrontendDependencyInjectionModule>()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }
    }
    
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
        }
    }
 ```
 
 Make an HTTP call with a URL with space characters not encoded `curl -D - "http://localhost:5000/?d=Bad Url To Accept"`
 
 Returns the following response
 ```
HTTP/1.1 505 HTTP Version Not Supported
Connection: close
Date: Tue, 22 Jun 2021 20:56:42 GMT
Server: Kestrel
Content-Length: 0
```

### Further technical details
- ASP.NET Core .NET 5.0

**Comment by Tratcher** [comment]
You can use connection logging or a network trace to capture the raw request on the wire and confirm the format.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#connection-logging

From the curl command, I'd expect the request to look something like this:
```
GET /?d=Bad Url To Accept HTTP/1.1
Host: localhost:5000
```

The start line is white space delineated, so putting spaces in the url is a significant spec violation that makes the parser think the HTTP version is "Url". `400 Bad Request` might be a more appropriate response. We don't usually accommodate blatant spec violations like this since it can introduce vulnerabilities in the parser or further up the stack.

What client actually sends invalid requests like this (besides curl)? Do you know of any other servers that will accept it and pass the fully query to the app?

>  IIS express and IIS will cause different behavior.

What do they do?

Incidentally this would work on HTTP/2 because the message format is no longer white space delineated.

**Comment by brianfeucht** [comment]
More details on the request via the verbose command from curl:
`curl -v "http://localhost:5000/?d=Bad UrlToAccept"`
```
GET /?d=Bad UrlToAccept HTTP/1.1
Host: localhost:5000
User-Agent: curl/7.58.0
Accept: */*

HTTP/1.1 505 HTTP Version Not Supported
Connection: close
Date: Wed, 23 Jun 2021 14:23:17 GMT
Server: Kestrel
Content-Length: 0
```

> What client actually sends invalid requests like this (besides curl)?

A couple user agents we are seeing do this
- `lua-resty-http/0.07 (Lua) ngx_lua/10012`
- `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

The URLs themselves are getting generated by processes that are outside of our control.  Generally speaking they are very few in number as a percentage of all our requests.  I would have probably not have even noticed if it wasn't for the 505 response code.

> IIS express and IIS will cause different behavior.
> What do they do?

IIS encodes the space as a `%20` before forwarding the request to Kestrel
IIS express returns a `400 Bad Request`

We are coming from IIS so the encoding the space as `%20` is the legacy behavior I would like to maintain if possible.

I have tested proxying requests through nginx and it returns `400 Bad Request` as expected.

**Comment by Tratcher** [comment]
> IIS encodes the space as a `%20` before forwarding the request to Kestrel
> IIS express returns a `400 Bad Request`

You're using the legacy iis-out-of-process model? Kestrel isn't used with the default iis-in-process model.

IIS and Express should have consistent behavior for something like this, they use the same underlying Http.Sys stack. We'll need to verify this across our servers.

**Comment by brianfeucht** [comment]
@Tratcher I was mistaken about IIS.  We are running InProcess and I am seeing a `400 Bad Request` there too.  The encoding I was seeing must have been done by the client.  

All the servers (besides Kestrel) I have tested return `400 Bad Request` for this case

**Comment by Tratcher** [comment]
Changing kestrel to return a 400 if the request line has the wrong number of tokens/spaces makes sense.

**Comment by BrennanConroy** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/33814
