### ISSUE TITLE
Disable non-websocket transports for Blazor Server

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#33775]
Customers often have a bad time if they use Blazor Server with transports other than websockets. We should consider disabling non-websocket based transports for Blazor Server apps and provide a good error experience when websockets are not available.

**Comment by pranavkm** [comment]
FYI @BrennanConroy / @davidfowl

**Comment by BrennanConroy** [comment]
> We should consider disabling non-websocket based transports

If you do this you need to make sure that there is a way to opt back into other transports. You don't want to exclude those customers that can't run WebSockets for whatever reason.

Do you have ideas of how to surface clean errors for this or is there asks for SignalR to help here?

**Comment by danroth27** [comment]
Some evidence of Blazor Server usage over non-websockets: https://twitter.com/HeyWellsy/status/1408275567489601540

**Comment by TanayParikh** [comment]
> provide a good error experience when websockets are not available.

@danroth27 Did you have anything in mind  to ensure a 'good error experience'? Would a banner with a message like the following be appropriate?

![image](https://user-images.githubusercontent.com/14852843/126704486-99cc5dcc-6520-4f3a-b520-a6761e5a161e.png)


@javiercn

**Comment by javiercn** [comment]
@TanayParikh can you detect that the websocket failed to connect?

**Comment by TanayParikh** [comment]
> @TanayParikh can you detect that the websocket failed to connect?

Yep, I'm able to catch the following exception:

```
Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: 'WebSockets' is not supported in your environment.
```

Hence we can give a pretty specific error message about WebSockets being unavailable.

**Comment by BrennanConroy** [comment]
I don't think that is the right error for this scenario. How did you get that?

**Comment by TanayParikh** [comment]
> I don't think that is the right error for this scenario. How did you get that?

Running a basic script in my browser (before page load) that does:

```js
WebSocket2 = null;
WebSocket = null;
```

Is it possible to use:

https://github.com/dotnet/aspnetcore/blob/fd85422b45f6c080b440648656807945e418cde6/src/SignalR/clients/ts/signalr/tests/HttpConnection.test.ts#L252 

for browser testing as well?

**Comment by BrennanConroy** [comment]
>Running a basic script in my browser (before page load) that does:

Ok, so that tests old un-supported browsers that don't support WebSockets at all. You also need to test connecting to a server that doesn't support WebSockets, which will be a slightly different error

> for browser testing as well?

Yes

**Comment by TanayParikh** [comment]
> You also need to test connecting to a server that doesn't support WebSockets, which will be a slightly different error

Ah gotcha. Emulated that now via:

```c#
options.Transports = HttpTransportType.LongPolling
```

and got:

```
 Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. LongPolling failed: Error: 'LongPolling' is disabled by the client.
```

I believe the underlying "ability" to detect WS not being an available isn't hindered. Will ensure the final solution reflects both these use cases.

**Comment by TanayParikh** [comment]
> You also need to test connecting to a server that doesn't support WebSockets, which will be a slightly different error

I'm assuming this is with client side enforcing WebSockets transports layer, in which case I emulated that now via:

```c#
options.Transports = HttpTransportType.LongPolling
```

and got:

```
 Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. LongPolling failed: Error: 'LongPolling' is disabled by the client.
```

I believe the underlying "ability" to detect WS not being an available isn't hindered. Will ensure the final solution reflects both these use cases.
