### ISSUE TITLE
Target Specific Language Server when Re-Invoking

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#33772]
Looking into a reported issue it seems like sometimes the wrong LanguageServer is sent requests. This is possible because we give a ContentType, and then the first server that matches is selected (even though there may be more than one server, and we have no guarantees about their order). If we used the ServerName instead we wouldn't have this problem.

**Comment by ryanbrandenburg** [comment]
I sent https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/329933 to deal with this, but it will likely need another design pass.

**Comment by NTaylorMullen** [comment]
Should this be closed out in favor of https://github.com/dotnet/aspnetcore/issues/33772?

**Comment by ryanbrandenburg** [comment]
That's a link to this issue?

**Comment by NTaylorMullen** [comment]
Recursion!!! This issue is what I was referring to sorry! https://github.com/dotnet/aspnetcore/issues/33857

**Comment by ryanbrandenburg** [comment]
Ah, yes apparently. Closing this one as dupe.
