### ISSUE TITLE
Breakdown of the time taken by IActionResultExecutor 

### ISSUE THREAD

**Issue by REASY** [dotnet/aspnetcore#33778]
It would be helpful when do some performance troubleshooting if infrastructure can provide a breakdown of the execution time of all the `IActionResultExecutor` implementations, such [SystemTextJsonResultExecutor](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/SystemTextJsonResultExecutor.cs#L39) and others.

**Comment by javiercn** [comment]
@REASY thanks for contacting us.

What do you want us to specifically provide, can you be more specific?

**Comment by REASY** [comment]
@javiercn in my concrete example I have pretty big model which is serialized to JSON (> 14 MBytes of JSON) and would be great to know how much time it takes to serialize data model to JSON

**Comment by TanayParikh** [comment]
Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
