### ISSUE TITLE
In Blazor WebAssembly, allow dynamic query string parameters when redirecting to IDP

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#33784]
### Is your feature request related to a problem? Please describe.
When using [Auth0's organisation feature](https://auth0.com/docs/organizations), in order to invite users to an organisation a URL is created and sent to the invitee via email. When clicked, this URL sends the invitee to the application where the application must strip out two query string parameters and then forward the invitee to Auth0's `authorize` endpoint along with these two query string parameters. Currently (as far as I can see) there is no way to append query string values dynamically when redirecting to an IDP. 

I see the extraQueryParams option has been added for .NET 6 but this doesn't seem to help in this situation. 

### Describe the solution you'd like
I think we may need an event which is triggered before the redirect which allows us to add, dynamically, any additional query string values to the URL the user is being forwarded to. However, I'm far from being an expert on this and I could be completely wrong.

**Comment by javiercn** [comment]
Done in https://github.com/dotnet/aspnetcore/issues/42580
