### ISSUE TITLE
F7 to get to code from razor file (blazor)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33794]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F7-to-get-to-code-from-razor-file-blazo/1453748)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.10.2]
Pressing F7 in the new experimental editor or VS 2022 preview does not go to the code. It does still work to get to the razor file from the razor.cs though.

---
#### Feedback Bot on 6/17/2021, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/18/2021, 03:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Xiaolin Zhang [MSFT] on 6/20/2021, 07:05 PM: 

<p>Thank you for taking the time to log this issue!<br>
Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ? If so, in order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool. For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed</a>.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a> , you can get tips on how to provide clear and simple reproducible steps.<br>
We look forward to hearing from you!</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Another instance of this type of missing feature: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1345954

**Comment by NTaylorMullen** [comment]
- WebTools pre-existing logic:
  - https://devdiv.visualstudio.com/DevDiv/_git/WebTools?path=%2Fsrc%2FLanguages%2Fhtml%2FVS%2FCommands%2FHtml%2FGoToPageCommand.cs
  - https://devdiv.visualstudio.com/DevDiv/_git/WebTools?path=%2Fsrc%2FLanguages%2Fhtml%2FVS%2FCommands%2FHtml%2FGoToPageModelCommandHandler.cs
