### ISSUE TITLE
Custom Framework/Template Create with Asp.Net Core ?

### ISSUE THREAD

**Issue by younussenn** [dotnet/aspnetcore#33805]
Hi,

I am working on a web application with Asp.Net Core. I use the same approaches and designs in almost every project. I have to do all the settings and configurations at every project start. I wonder if I create and save the general structure of the project, can I bring this structure in the new project ? So I don't know if this makes sense but I need this for rapid development.

For example, I use IdentityScheme for user management in each of my projects. I have to build up IdentityScheme every time. Instead, if I call the structure I prepared before, I don't have to do the same thing over and over.

**Comment by davidfowl** [comment]
Are you asking for an example of building a custom template or something else?

**Comment by Pilchie** [comment]
If it is that, check out https://devblogs.microsoft.com/dotnet/how-to-create-your-own-templates-for-dotnet-new/ and the dotnet/templating repository.
