### ISSUE TITLE
Blazor wasm endpoints.MapFallbackToFile("index.html") should not apply to URLs with API

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#33810]
With the Default Blazor wasm hosted template in .NET6.
there is a endpoints.MapFallbackToFile("index.html"); in Server Project configure method of startup class.

is there a way to not apply MapFallbackToFile when the URL has '/api' in it ?

**Comment by pranavkm** [comment]
There are overloads to MapFallback that you could consider: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.fallbackendpointroutebuilderextensions.mapfallback?view=aspnetcore-5.0. You could also consider matching for a specific pattern as a fallback:

```C#
endpoints.MapFallbackToFile("/FirstApp/{*path:nonfile}", "FirstApp/index.html");
```

**Comment by nssidhu** [comment]
I tried that code is not working, if i type invalid uri with api, it still falls back to index.html
example https://mywebsite.com/api/fakecontroller/realmethod
