### ISSUE TITLE
JWT Authentications always fail after upgrading from .NET to .NET 6

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#33811]
www-authenticate: Bearer error="invalid_token"  401

Every Api method protected by [Auhtorize] is failing after i upgraded to .NET 6 from .NET 5.
I am using Blazor wasm hosted App.

Is there anything that i need to do additional when migrating ?

**Comment by Tratcher** [comment]
Possible duplicate of https://github.com/dotnet/aspnetcore/issues/33634.

Enable application logging for details.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by nssidhu** [comment]
I just verified that if I remove [Authorize] attribute it works fine.
So this is something related to Upgrade.

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

We haven't changed anything significant in that area.
