### ISSUE TITLE
Remove <LangVersion>preview from empty web template

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#33813]
This shouldn't be necessary to get C# 10 features any more.

**Comment by DamianEdwards** [comment]
Change to enable this was just merged to Roslyn so once it flows to the SDK we should be OK to make this change in main.

**Comment by DamianEdwards** [comment]
Latest SDK (_6.0.100-preview.7.21356.3_ at time of writing) has this change now. Not sure if this has flowed to ASP.NET repo though.

**Comment by DamianEdwards** [comment]
OK just verified this works now with _6.0.100-preview.7.21329.3_ which is what the repo is (at least in my branch) so I'll go ahead and update this as part of #34016
