### ISSUE TITLE
Running multiple "dotnet watch run" with dependency overlap periodically fails

### ISSUE THREAD

**Issue by jonstelly** [dotnet/aspnetcore#33827]
I've got a dotnet core solution with several class libraries, an asp.net core web app project and a background worker project that share dependencies on the class libraries.  During development I fire up a `dotnet watch run` for both projects.  All of my development is currently on Windows.

When I modify a file in a dependency project both watches start builds at almost the same time and fairly often (more than 1/3 of the time) one of the builds will fail from a file being in use by the other build.

`CSC : error CS2012: Cannot open 'C:\code\thing\src\Thing.Data\obj\Debug\netcoreapp3.1\Thing.Data.dll' for writing -- 'The process cannot access the file 'C:\code\thing\src\Thing.Data\obj\Debug\netcoreapp3.1\Thing.Data.dll' because it is being used by another process.' [C:\code\thing\src\Thing.Data\Thing.Data.csproj]
`

Is there already a way to accomplish what I'm trying to do and keep these two watches from stepping on each other?

If not, the simplest idea I could come up with was to add a flag to `dotnet run`, something like `--with-lock` so that dotnet takes a system-wide mutex for each project directory?  That would ensure that even with multiple overlapping watches they wouldn't try to build the same project at the same time.

Any thoughts?  I've never dug into the SDK source code but I'm starting to track my way through, starting with RunCommand.  I think this would end up being a command-line argument/property added to msbuild that gets passed down to roslyn?  I have a very basic idea of how the dotnet build server processes work.  In the end this may not be as simple a thing as I would hope.  Does this seem like something that a pull request might be accepted for?

**Comment by pranavkm** [comment]
@jonstelly thanks for the issue report. It's unlikely the `run command` would support this. However, `dotnet watch` isn't limited to the run command - it can run any global dotnet CLI command. You could consider building a wrapper command that run `dotnetr run` and supports the kinds of locking your app needs. Separately, as part of the hot reload work in 6.0, `watch` by default performs compilation in memory (does not shell out to `dotnet build`) , so the experience might have improved.
