### ISSUE TITLE
`dotnet watch run` applies project-type-specific defaults for its behavior when source changes are detected

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#33825]
### User Story
As a user, I want `dotnet watch run` to default to performing reasonable behaviors, appropriate for the project type I'm working on, so that my development experience is productive and enjoyable.

### Considerations
- Will leverage the mechanism covered by https://github.com/dotnet/sdk/issues/15851
- *Rest TBD*

**Comment by pranavkm** [comment]
@DamianEdwards watch currently bakes in some understanding about ASP.NET Core and Blazor WASM projects. When we discussed further support for Xamarin et al, the plan was to consider some sort of plug in model. But we dropped this for 6.0 as part of scoping work. 

Do you think there's further work that we want to track as part of this issue?

**Comment by DamianEdwards** [comment]
For .NET 6, no I think broadly speaking this item is done now. We can log any further workload-specific issues as they come up in the rest of .NET 6.
