### ISSUE TITLE
Dotnet watch run cause my Mac to restart

### ISSUE THREAD

**Issue by n1developer-ubt** [dotnet/aspnetcore#33824]
Panicked task 0xfffffe166e9137f8: 23573 pages, 1 threads: pid 2172: dotnet
Panicked thread: 0xfffffe16739f6c68, backtrace: 0xfffffe309539b160, tid: 36995
		  lr: 0xfffffe001abadf7c  fp: 0xfffffe309539b1d0
		  lr: 0xfffffe001abadd48  fp: 0xfffffe309539b240
		  lr: 0xfffffe001accf7d0  fp: 0xfffffe309539b260
		  lr: 0xfffffe001acc12fc  fp: 0xfffffe309539b310
		  lr: 0xfffffe001ab677e8  fp: 0xfffffe309539b320
		  lr: 0xfffffe001abad9d8  fp: 0xfffffe309539b6b0
		  lr: 0xfffffe001abad9d8  fp: 0xfffffe309539b720
		  lr: 0xfffffe001b345dec  fp: 0xfffffe309539b740
		  lr: 0xfffffe001b3467dc  fp: 0xfffffe309539b8b0
		  lr: 0xfffffe001acc31ac  fp: 0xfffffe309539b920
		  lr: 0xfffffe001acc1228  fp: 0xfffffe309539b9d0
		  lr: 0xfffffe001ab677e8  fp: 0xfffffe309539b9e0
		  lr: 0xfffffe001b35d788  fp: 0xfffffe00205fffe0
		  lr: 0xfffffe001ab67ff4  fp: 0xfffffe309539ba00
		  lr: 0xfffffe001ac3d558  fp: 0xfffffe309539bae0
		  lr: 0xfffffe001ac47fdc  fp: 0xfffffe309539bc90
		  lr: 0xfffffe001ac4b980  fp: 0xfffffe309539bcd0
		  lr: 0xfffffe001abdebf4  fp: 0xfffffe309539bd10
		  lr: 0xfffffe001b095db0  fp: 0xfffffe309539bda0
		  lr: 0xfffffe001b095b94  fp: 0xfffffe309539bdb0
		  lr: 0xfffffe001b1a9308  fp: 0xfffffe309539be40
		  lr: 0xfffffe001acc0fe0  fp: 0xfffffe309539bef0
		  lr: 0xfffffe001ab677e8  fp: 0xfffffe309539bf00

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
