### ISSUE TITLE
BlazorServer TokenProvider returns null in MessageHandler

### ISSUE THREAD

**Issue by Dresel** [dotnet/aspnetcore#33837]
This might be by design but I found no clear answer if this is supported or not. I found some related but unanswered issues like [this](https://github.com/dotnet/aspnetcore/issues/12601#issuecomment-555566415). Related SO questions didn't provide any answers either.

I followed the docs for access token retrieval within a blazor server app ([TokenProvider](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0)).

I would like to use this token (provider) for a nswag generated client. For this we are defining a named HttpClient in combination with an HttpMessageHandler:

```csharp
services.AddHttpClient("MyApi", (client) =>
{
    // TODO: Load from Configuration
    client.BaseAddress = new Uri("https://my.api/");
})
.AddHttpMessageHandler<AuthorizationMessageHandler>();
```

```csharp
public class AuthorizationMessageHandler : DelegatingHandler
{
	private readonly IHttpContextAccessor httpContextAccessor;

	public AuthorizationMessageHandler(IHttpContextAccessor httpContextAccessor)
	{
		this.httpContextAccessor = httpContextAccessor;
	}

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		// AccessToken is always null
		string? accessToken = this.httpContextAccessor.HttpContext.RequestServices.GetRequiredService<ITokenProvider>().AccessToken;

		if (!string.IsNullOrWhiteSpace(accessToken))
		{
			request.Headers.Authorization = new AuthenticationHeaderValue("bearer", accessToken);
		}

		return await base.SendAsync(request, cancellationToken);
	}
}
```

This does not work and might be explained by the docs when they say

> Additionally, again for security reasons, you must not use IHttpContextAccessor within Blazor apps. Blazor apps run outside of the context of the ASP.NET Core pipeline. The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app.

Is there any "trick" how we could use the TokenProvider with an HttpMessageHandler? This is what we are currently using as a workaround (MyApiClient is the generated nswag client that accepts an HttpClient instance):

```csharp
services.AddScoped<IMyApiClient, MyApiClient>(provider =>
{
	HttpClient httpClient = provider.GetRequiredService<IHttpClientFactory>().CreateClient("ProfileApi");

	ITokenProvider tokenProvider = provider.GetRequiredService<ITokenProvider>();

	if (!string.IsNullOrWhiteSpace(tokenProvider.AccessToken))
	{
		httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {tokenProvider.AccessToken}");
	}

	return ActivatorUtilities.CreateInstance<MyApiClient>(provider, httpClient);
});
```

What is also missing from the docs is where to put the "refresh token" workflow part. I guess this is something that could be added to the TokenProvider (or MessageHandler)?

**Comment by javiercn** [comment]
@Dresel thanks for contacting us.

Since you are using HttpFactory, which creates its own scope, the only way I can think you can achieve this is by retrieving the token and setting it up before any call inside an AsyncLocal<T> variable so that your handler can acess it.

As an aside, we discourage the usage of IHttpContextAccessor within blazor server. Checkout https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state-1 for more details.
