### ISSUE TITLE
React to System.Net.Quic being made internal

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#33834]
React to https://github.com/dotnet/runtime/issues/54534

Changes were merged in https://github.com/dotnet/runtime/pull/54610

Will likely block this repo from merging the latest runtime update until fixed.

**Comment by wtgodbe** [comment]
This is the PR: https://github.com/dotnet/aspnetcore/pull/33847

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/33847
