### ISSUE TITLE
Remove reliance on preview LanguageVersion for incremental RSG

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#33848]
The incremental RSG currently requires a preview language version. We'll need to remove this once the compiler supports it.

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/sdk/pull/18817

**Comment by captainsafia** [comment]
@pranavkm Actually no. I had to revert because the incremental API still depends on the preview version. Confirmed the behavior with Chris last week.

**Comment by pranavkm** [comment]
Clearing the milestone so we can bring this up for triage. We want to fix this for rc1.

**Comment by mkArtakMSFT** [comment]
@pranavkm what is left here given that your PRs were already merged in the SDK repo?
