### ISSUE TITLE
Minimal APIs - return string isn't setting content type header 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/aspnetcore#33860]
### To Reproduce

- Create a new empty web application 
-  Add swagger UI 
- Run the application  go to  `https://localhost:5001/swagger/index.html`

![image](https://user-images.githubusercontent.com/2546640/123486901-f2525180-d5da-11eb-844b-edba0e015884.png)

**Comment by BrennanConroy** [comment]
Triage: We might consider setting the response type to "text/plain" by default if it isn't set already.

**Comment by halter73** [comment]
Only do this if the `Content-Type` response header is not already set.
