### ISSUE TITLE
Blazor areas

### ISSUE THREAD

**Issue by dartemage** [dotnet/aspnetcore#33862]
The current implementation of **Blazor routing** does not support "**areas**".

I would like to be able to manage "**areas**" in the Blazor application to be able to manage multiple sites from one application asp.net

**Comment by javiercn** [comment]
@dartemage thanks for contacting us.

Can you clarify what do you mean by "areas"? Do you want to have multiple Blazor Server apps hosted inside the ASP.NET Core app, where each of them is completely separate from the other app? (Meaning no two apps will render on the same document) or are you looking for something else?

**Comment by dartemage** [comment]
I need to specify which area my application will work with depending on the entry point. And so that routing occurs within the boundaries of the region, and not across all specific pages that are in assembly

`endpoints.MapFallbackToAreaPage("/Sites/Example/_Host", "Example").RequireHost("example.org");
 endpoints.MapFallbackToAreaPage("/Sites/Example1/_Host", "Example1").RequireHost("example1.org");
`

![image](https://user-images.githubusercontent.com/6968097/123531045-c41f5f80-d709-11eb-8246-f0cdd2c4b281.png)


> Microsoft.AspNetCore.Components.Routing.Router doesn't handle area handling in any way

**Comment by javiercn** [comment]
@dartemage thanks for the additional details.

There is no Area concept in Blazor. Areas are an MVC/Razor pages concept that we don't have plans to include in Blazor. That said, there is nothing specific to MVC in areas, and there's no real benefit for having them in Blazor. Areas are valuable for carving a subset of the URL space under a known prefix (the area). This has an impact in two areas:
* Route matching for which Blazor routes need to specify routes explicitly, so you can specify the area in the route template explicitly.
  * The only place where this matter (a little bit) is on the fallback route, and in that case you can be explicit about it by using 
    ```csharp
     public static IEndpointConventionBuilder MapFallbackToAreaPage(
        this IEndpointRouteBuilder endpoints,
        string pattern,
        string page,
        string area)
    ```
    For example: `endpoints.MapFallbackToArea("/Sites/Example/{**slug:nonfile}", "/Sites/Example/_Host", "Example")` to map the different areas.
* Link generation (which doesn't exist on Blazor).

**Comment by dartemage** [comment]
In the current version, for each page, you must explicitly specify the path, which is not good. I would like to be able to manage at the directory / namespace / attribute level
