### ISSUE TITLE
PageX and PageY in MouseEventArgs

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/aspnetcore#33873]
We already have `ScreenX`/`ScreenY` and `ClientX`/`ClientY` and  `OffsetX`/`OffsetY`. I think these will cover typical use cases.

If there are needs for even more types of coordinate, we'd handle that through #17552, so I'll close this as a duplicate of that.

_Originally posted by @SteveSandersonMS in https://github.com/dotnet/aspnetcore/issues/7182#issuecomment-708437442_

**Comment by TonyLugg** [comment]
It was incorrect to close this issue.  pageX and pageY are present in the standard DOM MouseEvent: 
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

The issue still stands that it is impossible to determine the page coordinate without these properties.  If they are in the standard DOM event, why do they not appear from Blazor?

**Comment by MackinnonBuck** [comment]
Done in #34605.
