### ISSUE TITLE
Measure text width and height in server side Blazor without JsInterop

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/aspnetcore#33875]
We are developing a complex editor using blazor for building graphs, however during the layout we need to measure the width (and sometimes height) of text.  In a complex DAG this can require 1000s of calls.  All the suggestions we have found use JSInterop to measure text width, but for 1000s of calls from the server is this the recommended approach, or is there a server side approach?

I would imagine anyone wanting to build a complex application (we use svg) will need this functionality on the server, so it would be good if this was built in to blazor, but happy to learn of any alternatives.

Please advise, many thanks John

**Comment by javiercn** [comment]
@johngsandiford thanks for contacting us.

In general, the browser controls the elements layout and sizing, so the server would need to replicate the Browser rendering process, which is not something we plan to do.

Unfortunately, it's likely that JS interop is your only choice here.

**Comment by johngsandiford** [comment]
Thanks for the reply @mkArtakMSFT , much appreciated.
If anyone knows a way of measuring just the width (given a font and size on the server), please let me know :)
