### ISSUE TITLE
dotnet watch (net 6.0 preview 5) - attach to process... not working and no breakpoints hit

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/aspnetcore#33871]
I'm trying .net 6 preview 5, I created a **blazor webassembly** project using the default template.  Next I go to the **Server** project open a command prompt and run `dotnet watch`.

I go to the `counter.razor` page and put a breakpoint on `currentCount++; ` (line 15)
In Microsoft Visual Studio Enterprise 2019 Preview (Version 16.11.0 Preview 2.0) I Go to Debug -> Attach to Process...

**Issues**

1. In previous versions of Visual Studio 2019 I could find the processor name belonging to my application. I can't seem to find the processor exe file here.
2. So I decided to run `dotnet watch --no-hot-reload` this time the processor name is displayed in the list and I am able to choose it. But my breakpoint never gets hit
3. I next decide to abandon using the `dotnet cli` and instead just press `F5` from within Visual Studio it brings up the cli and opens the site and breakpoints work correctly.
4. Using debugging through Visual Studio I noticed that if I tried to change the `counter.razor` by updating the `<h1>` tag nothing changed. Are edits not supported while debugging?

**Questions**

1. Differences between trying to use the `dotnet cli` directly and trying to attach the process?
2. Is hot module reloading disabled when debugging within visual studio? i.e. can I edit the the razor page and expect to see pages?

This issue also happens with other app types such asp asp.net core mvc

**Comment by pranavkm** [comment]
Thanks for the issue report @dotnetshadow. 

Preview6 removes the hot-restart option, and you should be able to see the process in the debugger as normal. That said, attaching a debugger is not supported for an application that was launched with hot reload (dotnet-watch / Control-F5 with the right setting in upcoming VS 2022 previews). Launching with F5 should work with hot reload once that feature lands in one of the upcoming VS preview releases.
