### ISSUE TITLE
Consider adding an item template + gesture to add component with code behind

### ISSUE THREAD

**Issue by feiyun0112** [dotnet/aspnetcore#33885]
Split razor file into two files, one is only html, one is cs code.

like this：
**Counter.razor**
```
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```
**Counter.razor.cs**
```
public partial class Counter : Microsoft.AspNetCore.Components.ComponentBase
  {
      private int currentCount = 0;

      private void IncrementCount()
      {
          currentCount++;
      }
  }
```

I think the codes can be easy to read and maintain

**Comment by chrissainty** [comment]
This is possible now and it's down it the individual to choose if they want to do this or not. Razor files generate partial classes so you just need to create a class with the same name as the razor file and mark it as partial.

**Comment by porkopek** [comment]
You also have this nice refactor "move to code behind" in VS after placing the caret in any code line within the razor page’s code section

**Comment by feiyun0112** [comment]
> This is possible now and it's down it the individual to choose if they want to do this or not. Razor files generate partial classes so you just need to create a class with the same name as the razor file and mark it as partial.

yes, i know.

but i mean maybe vs template use this way as default.

**Comment by chrissainty** [comment]
> > This is possible now and it's down it the individual to choose if they want to do this or not. Razor files generate partial classes so you just need to create a class with the same name as the razor file and mark it as partial.
> 
> 
> 
> yes, i know.
> 
> 
> 
> but i mean maybe vs template use this way as default. 

I'd disagree. I really dislike this separation. 

In my opinion it's less efficient (I have to move between two files). It can hide bloated components. As the files are split it's easier to add more code and look like there isn't as much there as it's split across two files. Finally, it implies that the markup and logic isn't tightly linked--which it is and should be. The logic in the code block should be for manipulation the markup anything else should be somewhere else. 

Having a single file is the lowest barrier to entry for a new developer learning Blazor, they can see everything and how it interacts. This should be the default for the template. But the great thing about Blazor is that if you don't like that approach you can refactor it to separate files. And as was pointed out in the previous comment, there are even tools which help you do it.

**Comment by pranavkm** [comment]
We can consider adding an item template and a VS gesture that lets you create a Razor component with a code behind file.

**Comment by danroth27** [comment]
We're tracking this with https://github.com/dotnet/aspnetcore/issues/47030
