### ISSUE TITLE
Having C# block comments can cause C# colorization to Debug.Fail

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#33895]
Looks like having a C# block comment in this situation can cause us to fall over:
![image](https://user-images.githubusercontent.com/2008729/123560368-872d8a00-d756-11eb-8afc-306bc6debbb3.png)

![image](https://user-images.githubusercontent.com/2008729/123560389-a9270c80-d756-11eb-9f64-dd823cbcac9b.png)

Whole Razor file:
```Razor
@page "/counter"

<h2>Counter</h2>

<strong>
    
</strong>
<p>Current count: @currentCount</p>

<input />

<strong>
    @{
        <div></div>
    }
</strong>

<style>
    h1 {
        
    }
</style>

<input />

<button class="btn btn-primary" @onclick="IncrementCount2">Click me</button>

<strong>
</strong>

@if (true)
{

}

@{
}

@code {
    private int currentCount = 1000;


    /*
     * 
     */
    private void IncrementCount2()
    {
        currentCount++;

        if (true)
        {

        }
    }

    public void Foo()
    {
    }
}

```

If you have a hard time reproing I also have a dump saved to my box.

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen I'm not getting this to replicate in latest experimental, did you have this happen when you opened the document like that or added the comment via edit? If via edit this may have been fixed by https://github.com/dotnet/aspnetcore-tooling/pull/4092.

**Comment by ryanbrandenburg** [comment]
@allisonchou am I remembering correctly that you made a fix for 0-length classifications on the C# side?

**Comment by ryanbrandenburg** [comment]
I wasn't able to repro.

**Comment by ryanbrandenburg** [comment]
Not able to repro after a couple more attempts and variations. If this IS still happening we'll need a different repro, and even if it is I know of no reason it would cause problems.
