### ISSUE TITLE
Razor colorization incorrectly colors as you type then corrects

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#33928]
Notice the trailing blue:
![N2OI7YwzVu](https://user-images.githubusercontent.com/2008729/123736742-8d0a9480-d856-11eb-8c94-fa3166963a51.gif)

Given the "lagginess" of the coloring it makes me think this is coming from our semantic colorization?

**Comment by ryanbrandenburg** [comment]
@gundermanc, do I remember correctly that you were looking at something like this from the Platform end?

**Comment by ryanbrandenburg** [comment]
This does still happen barely, but now that the Semantic Tokens are much faster it looks better:
![ColorOver](https://user-images.githubusercontent.com/14987221/128432111-17385992-7c20-490c-b3ac-4bf2d958d7e6.gif)

If we wanted to pursue that I would assume the problem lay somewhere in either the TextMate Grammar or the VS Tagger, but I think the view now is roughly on par with the existing C# experience.

**Comment by NTaylorMullen** [comment]
> If we wanted to pursue that I would assume the problem lay somewhere in either the TextMate Grammar or the VS Tagger, but I think the view now is roughly on par with the existing C# experience.

Good to know! I agree, possible improvements here are definitely from the platform side. For completeness do we happen to have an issue opened on them for that? I know that when I personally format documents I see our directive yellow semantic colorization stretch across the screen in VS but not in VSCode

**Comment by ryanbrandenburg** [comment]
Good call, I was so sure I'd already filed that one that I didn't check until you asked, and apparently I hadn't. Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1367097 to track this on their end.

I wasn't QUITE right about the existing C# (non-LSP) experience, but the same thing does happen in C# LSP, so we can be pretty sure it's an LSP platform issue.
