### ISSUE TITLE
Is "UseExceptionHandler" middleware used in Blazor apps?

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#33921]
In the Blazor Server project template, there are a few middleware in `Configure()`. I've read that Blazor doesn't use middleware, so I'm wondering, does this line do anything in Blazor Server or WebAssembly apps?

https://github.com/dotnet/aspnetcore/blob/86ea8e019eb315dd6b68bd7fcc796a0fcb6a67c9/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Startup.cs#L145

**Comment by pranavkm** [comment]
In Blazor WebAssembly and unhandled exception happens on the client, not on the server, so the middleware won't do anything. Exceptions in a Blazor server app won't appear in the exception handler, however if there are errors that happen as part of the HTTP middleware pipeline including pre-rendering, the exception middleware would see and process these.

**Comment by mrlife** [comment]
@pranavkm Thank you. If pre-rendering is not used, the exception middleware only applies to errors in _Host.cshtml and API endpoints (any `.cshtml` file) in Blazor Server apps?

**Comment by pranavkm** [comment]
Yup. Nearly all of Blazor's rendering happens outside the context of an ASP.NET Core request, which is why the middleware does not come in to play.
