### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#33923]
`I put markup in try block for fun and page hangs, I am not willing to provide full detail, I am expecting generic answers like if this is a known thing`
![image](https://user-images.githubusercontent.com/35312807/123708340-194d9500-d820-11eb-9503-4b9f41675468.png)

`This code is throwing exception, mean while I looked at my code and I want you to look at it too, nothing seems wrong`
![image](https://user-images.githubusercontent.com/35312807/123708743-c6c0a880-d820-11eb-842e-2dfed6b87ac1.png)
![image](https://user-images.githubusercontent.com/35312807/123708779-d63ff180-d820-11eb-86f5-82b0ed8300fc.png)

**Comment by Xyncgas** [comment]
this was the only exception I was getting, weird that it says line56 has error while line56 worked and printed what I wanted it to print. I am using RenderFragment<T> and from the outside I have two elements one nested in another that's why you can see two `output :`

**Comment by Xyncgas** [comment]
Maybe when .net 6 get out at the end of this year, things will be better for blazor?

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

> `I put markup in try block for fun and page hangs, I am not willing to provide full detail, I am expecting generic answers like if this is a known thing`.

Throwing during render should be fine, It's not clear why your app hangs, but its likely app specific.

If you are receiving a null reference exception there's definitely something wrong with that code. Without context we can't tell you what. The line number might not be exactly correct, and that might be a compiler bug, but that's it.
