### ISSUE TITLE
WebApplicationBuilder adds default services twice

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#33934]
After my [change](https://github.com/dotnet/aspnetcore/pull/33800) got merged Swashbuckle broke when using the `WebApplicationBuilder` and it's because we call  ConfigureWebHostDefaults twice: 
1. https://github.com/dotnet/aspnetcore/blob/348b810d286fd2258aa763d6eda667a83ff972dc/src/DefaultBuilder/src/WebApplicationBuilder.cs#L52
2. https://github.com/dotnet/aspnetcore/blob/348b810d286fd2258aa763d6eda667a83ff972dc/src/DefaultBuilder/src/WebApplicationBuilder.cs#L111

Assuming it was fine to do so but it isn't when using API explorer because we end up adding the same provider twice which makes swashbuckle (and I assume other code) unhappy. Swagger/OpenAPI is currently broken because of this.

cc @halter73 @LadyNaggaga @bradygaster

**Comment by halter73** [comment]
Yeah. I knew this might be bad. That's why I left this comment. 😆 

https://github.com/dotnet/aspnetcore/blob/348b810d286fd2258aa763d6eda667a83ff972dc/src/DefaultBuilder/src/WebApplicationBuilder.cs#L108-L111

We'll have to consider how we deal with the "ForwardedHeaders_Enabled" scenario.
