### ISSUE TITLE
UseExceptionHandler in SPA templates not working

### ISSUE THREAD

**Issue by fuzzykiller** [dotnet/aspnetcore#33937]
### Describe the bug

When creating a new SPA project (eg. `dotnet new react`), `Startup.cs` contains the following:

```cs
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
```

However, there is nothing at `/Error`, so the exception middleware fails somehow and control passes to the SPA middleware (the SPA is served).

The template needs controller at `/Error` or something like that.

### To Reproduce
1. `dotnet new react`
2. Add some exception (eg. `endpoints.Map("/boom", context => throw new Exception("boom"));` in `UseEndpoints`)
3. `dotnet publish -c Release`
4. Run published build
5. Go to `http://localhost:5000/boom`

### Exceptions (if any)
No exception (except the one explicitly thrown).

### Further technical details
- ASP.NET Core version: 5.0 (5.0.7 maybe?)
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Not applicable / Notepad

**Comment by javiercn** [comment]
@fuzzykiller thanks for contacting us.

This is likely because the template doesn't have a razor page on it. 

That said, I believe we should not have an error page experience here at all, since the reality is that the page is not going to be displayed to the end user in any case, as the likely source of an exception comes from an HTTP request to the backend from the SPA frontend.

/cc: @LadyNaggaga

**Comment by javiercn** [comment]
The suggestion here is to remove the error page middleware alltogether since it doesn't add anything in this scenario.

**Comment by fuzzykiller** [comment]
Thanks for the quick feedback! I agree that an error is very unlikely. However, depending on the middleware used (authentication etc), exceptions are still possible, for example due to errors in the deployment configuration. The user would get an empty page or network error in that case, if no exception handler is present.

**Comment by javiercn** [comment]
@fuzzykiller that's true, for some reason I thought this was only used in development.

**Comment by pranavkm** [comment]
The suggestion is to remove the exception handler (as long as we can validate it does not leak any sensitive details such as stack traces or exception messages).
