### ISSUE TITLE
When is ObjectGraphDataAnnotationsValidator available for production ?

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#33932]
The ObjectGraphDataAnnotationsValidator  has been in rc for a long time... ?
```

<EditForm Model="@model" OnValidSubmit="@HandleValidSubmit">
    <ObjectGraphDataAnnotationsValidator />
    ...
</EditForm>
```

The latest [nuget ](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation)package is 3.2.-rc1 and its still in rc1 for more that a year now, last updated on 4/29/2020  !

When can we expect a released version for  production blazor apps ?

**Comment by pranavkm** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/33247. We're looking to productionize it for 6.0.
