### ISSUE TITLE
SignalR - CORS - Windows Authentication it fails to get past negotiate

### ISSUE THREAD

**Issue by pthorsley** [dotnet/aspnetcore#33939]
### Describe the bug
When trying to set up connection to Hub it always fails, HOWEVER all of the standard API controller calls work and negotiate just fine, it only fails when trying to connect to the Hub using this library that MS provides:

const newConnection = new HubConnectionBuilder()
            .withUrl(url, options => {
              options.UseDefaultCredentials = true
              options.Headers['Content-Type'] = 'text/plain'
             // options.SkipNegotiation = true;
            })    
            .withAutomaticReconnect()
            .build();

I have tried many different configurations of this call and still nothing. 

Have added to web.config this did help a little, it at least lets me in,  but still fails with exception below:
```
 <httpProtocol>
        <customHeaders>
          <add name="Access-Control-Allow-Origin" value="https://localhost:3000" />       
          <add name="Access-Control-Allow-Credentials" value="true" />
          <add name="Access-Control-Request-Headers" value="User-Agent,Content-Type,Authorization,X-RequestDigest,X-ClientService-ClientTag,XMLHttpRequest,x-requested-with" />
          <add name="Access-Control-Allow-Headers" value="User-Agent,Content-Type,Authorization,X-RequestDigest,X-ClientService-ClientTag,XMLHttpRequest,x-requested-with" />
          <add name="Access-Control-Request-Method" value="GET,POST,HEAD,OPTIONS" />
        </customHeaders>
      </httpProtocol>
```

Also tried custom middleware for CORS but still failing with or without it. 
Of course it is blocking the request before it gets to actual hub.
Have tried skipping Negotiation, but that has not worked either. 
Get the same error on DEV box also, so it seems consistent with of course a different Access-Control-Allow-Origin.

### Exceptions (if any)
Access to fetch at 'https://localhost:44319/ticketsummary/negotiate?negotiateVersion=1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: 
**It does not have HTTP ok status.**

![image](https://user-images.githubusercontent.com/6778972/123834799-0b9e1b00-d8c5-11eb-8c4e-26f0ac529f4c.png)

### Further technical details
dotnet core 3.1 
   -   SSL enabled
   -   Win Auth enabled

SignalR 
reactJS

**Comment by pthorsley** [comment]
Just tried this as well, but did not work.....same error
Funny it knows my domain is correct because if I put in another domain it gives a wrong domain error...... yet it does not pass....mmmmm

```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                //endpoints.MapHub<TicketSummaryHub>("/hubs/ticketsummary");

                app.UseSignalR(routes =>
                {
                    routes.MapHub<TicketSummaryHub>("/hubs/ticketsummary");
                });
            });
```

**Comment by BrennanConroy** [comment]
I don't think setting custom headers in your web config will help with CORS. You need to either use the CORS IIS module, or configure CORS on the server with the CORS middleware.
IIS CORS: https://docs.microsoft.com/en-us/iis/extensions/cors-module/cors-module-configuration-reference
CORS on the server: https://docs.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-5.0#cross-origin-resource-sharing

**Comment by pthorsley** [comment]
mmmmmmm.....
Removed the web.config xml and get a different error:
Access to fetch at 'https://localhost:44319/hubs/ticketsummaryhub/negotiate?negotiateVersion=1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Put it back in and back to this error:
Access to fetch at 'https://localhost:44319/hubs/ticketsummaryhub/negotiate?negotiateVersion=1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by pthorsley** [comment]
well one thing is for sure the XML version with the startup.cs going at the same time crashed things in the normal API controller calls......so back to square one with the HUB for signalR, here is the error, seems the CORS policy is NOT being applied to the HUBS:

Access to fetch at 'https://localhost:44319/hubs/ticketsummaryhub/negotiate?negotiateVersion=1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by pthorsley** [comment]
Here is my middle ware execution order:
`
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();


            app.UseAuthentication();


            app.UseRouting();


            app.UseAuthorization();

            if (System.Diagnostics.Debugger.IsAttached)
            {
                app.UseCors(localSpecificOrigins);

                //app.UseCorsMiddleware();
            }
            else
            {
                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                    app.UseCors(serverSpecificOrigins);
                }
                else
                {
                    app.UseHsts();
                    app.UseCors(serverSpecificOrigins); // TODO: Will go to PRD Origins
                }
            }

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

                endpoints.MapHub<TicketSummaryHub>("/hubs/ticketsummary");

            });

        }
`

**Comment by BrennanConroy** [comment]
What do your CORS options look like? Also, CORS should be before auth
https://docs.microsoft.com/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order

**Comment by BrennanConroy** [comment]
Oh wait, I just realized you're doing CORS and Windows Auth, those aren't great together, you need to use the CORS IIS module if you're doing that (I assume you're using IIS here)
https://docs.microsoft.com/aspnet/core/security/cors?view=aspnetcore-5.0#cors-in-iis

**Comment by pthorsley** [comment]
CORS and WIN auth are working great for the API controllers and have been for years...so no issue there.
It is just CORS and the HUB plus WIN auth that might be the issue. The origin fails as shown above , but just for SignalR calls using HubConnectionBuilder provided by MS for react.

**Comment by pthorsley** [comment]
Forgot to mention , get the same error in DEV boxes running win server 2012 as I do on my local.....so it seems pretty consistent with the .net core middleware code failure not being able to handle the hub requests properly.

**Comment by pthorsley** [comment]
Also: had the auth before the CORS, just flipped it back to after CORS, here is error:

`ticketsummary:1 Access to fetch at https://localhost:44319/hubs/ticketsummaryhub/negotiate?negotiateVersion=1 from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No Access-Control-Allow-Origin header is present on the requested resource. If an opaque response serves your needs, set the request's mode to no-cors to fetch the resource with CORS disabled.
`

Seems CORS and signalR HUB mixed with Win auth do not play together in .net core 3.1

**Comment by pthorsley** [comment]
here is current configure:
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();




            app.UseRouting();



            if (System.Diagnostics.Debugger.IsAttached)
            {
                app.UseCors(localSpecificOrigins);

                //app.UseCorsMiddleware();
            }
            else
            {
                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                    app.UseCors(serverSpecificOrigins);
                }
                else
                {
                    app.UseHsts();
                    app.UseCors(serverSpecificOrigins); // TODO: Will go to PRD Origins
                }
            }

            app.UseAuthentication();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

                endpoints.MapHub<TicketSummaryHub>("/hubs/ticketsummary");

            });

        }

**Comment by BrennanConroy** [comment]
Can you please collect a network trace and share it:
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0#network-traces

Also, what is `serverSpecificOrigins` or `localSpecificOrigins` whichever one you're using, the actual options are important.

Lastly, can you turn on server logs to Debug and see if there are any logs from the CORS middleware.

**Comment by pthorsley** [comment]
The localSpecificOrigins is what is run when debugging, have removed serverSpecificOrigins just for this testing fix.

Might try out Socket.io , maybe it does not have this CORS, SignalR, Win Auth issue. 

Here is the basic add CORS options:

 ```
 public void ConfigureServices(IServiceCollection services)
        {
          
            services.AddSignalR();

            services.AddControllers();

            services.Configure<AppSettings>(Configuration);

            services.AddMemoryCache();

            services.Configure<IISOptions>(options => options.AutomaticAuthentication = true);

            services.AddScoped<SmtpClient>((serviceProvider) =>
            {
                var config = serviceProvider.GetRequiredService<IConfiguration>();
                return new SmtpClient()
                {
                    Host = config.GetValue<String>("EmailSettings:SMTP:Host"),
                    Port = config.GetValue<int>("EmailSettings:SMTP:Port"),
                    UseDefaultCredentials = false,
                };
            });
 services.AddCors(options =>
            {
                options.AddPolicy(localSpecificOrigins,
                builder =>
                {
                    builder.WithOrigins("http://localhost:3000", "http://localhost:3001", "https://localhost:3000", "https://localhost:3001")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                    .SetIsOriginAllowed((host) => true) ;
                });

                options.AddPolicy(serverSpecificOrigins,
                builder =>              
                {
                    builder.WithOrigins("<server list removed for github>")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                    .SetIsOriginAllowed((host) => true);
                });
            });

        services.AddAuthentication(IISDefaults.Ntlm);
}
```

**Comment by pthorsley** [comment]
Seems signalR and CORS in IIExpress/IIS have some sort failure....ugh

Access to fetch at 'https://localhost:44319/hubs/ticketsummary/negotiate?negotiateVersion=1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to **preflight** request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by pthorsley** [comment]
I guess there is no support for Win Auth using CORS and SignalR?

Anyone have a actual working example of Win Auth being used?

**Comment by BrennanConroy** [comment]
Yes it works, but we can't help you if you don't provide the information asked for
>Can you please collect a network trace and share it:
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0#network-traces

>can you turn on server logs to Debug and see if there are any logs from the CORS middleware.

**Comment by pthorsley** [comment]
Very sorry, not allowed to capture traffic from the source due to government limitations. 
They will never allow capture let alone sharing it. :) 

However if you have an actual working example of Win Auth using CORS and SignalR then please send it my way. 
Sorry , they won't even let me install fiddler let alone capture traffic and share it is out of the question. 
Thanks

**Comment by pthorsley** [comment]
wow, after I rebuilt the startup.cs I have proved that Win Auth for sure is causing the issue with CORS mixed with SignalR.
I removed Win Auth from the project and put this in startup.cs

Turned OFF Windows Auth and went with Anonymous and now it will connect without any CORS errors ....... soooooooo, it seems that Win Auth is the culprit as expected.

Sadly I cannot run in Kestrel since it does NOT support win auth either....ugh....... would not matter anyway we have to have it run in win auth and IIS in our environment no matter what.

This will have to go up the food chain that SignalR does NOT WORK with Win Auth when using CORS unless someone can provide PROOF otherwise. Real proof with a REAL working example of Win Auth working with SignalR and CORS

SADLY this is a huge contract and will be very impactful, they were leaning towards Azure, but this will solidify AWS for sure, bummer

Here is working startup.cs that works with Anonymous Auth and IISExpress 
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddSignalR();
            services.AddCors(options =>
            {
                options.AddPolicy("ClientPermission", policy =>
                {
                    policy.AllowAnyHeader()
                        .AllowAnyMethod()
                        .WithOrigins("http://localhost:3001")
                        .AllowCredentials();
                });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseCors("ClientPermission");

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<TicketSummaryHub>("/hubs/ticketsummary");

            });
        }
    }

```

**Comment by BrennanConroy** [comment]
This is outside the scope of what we can support through GitHub. You can reach out to paid support at http://support.microsoft.com/supportforbusiness/productselection?sapId=ef53b119-5f8c-7343-2a0f-f5008a1399b9

**Comment by pthorsley** [comment]
nobody from MS even responded....since there not ONE example I would for sure not pay for the complete lack of support so far.

**Comment by pthorsley** [comment]
So everyone is aware...........   Not addressed and NOT solved!!!!!!!!!!!
Adding to that , since I have completely wasted my time, except to find that SignalR/CORS/Win Auth do NOT WORK together!! THIS IS A BUG!!!!!!!!!!! 
But cheers. :)
