### ISSUE TITLE
Update ASP.NET Core C# project templates to use new minimal hosting APIs in .NET 6

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#33944]
The ASP.NET Core project templates included in the SDK should be updated to use the new minimal hosting APIs introduced in .NET 6 as they represent the new idiomatic way to bootstrap (configure and start) the relevant host for the majority of scenarios.

- The `CreateHostBuilder` method would be removed as the patterns that were previously reliant on this are no longer necessary
- The `Startup` class would be removed and its contents applied as applicable to the calls to `WebApplicationBuilder` in _Program.cs_
- Change to Blazor WebAssembly hosted templates tracked in #32471

**Comment by Tratcher** [comment]
FYI @jmprieur @jennyf19

**Comment by jmprieur** [comment]
@DamianEdwards : are there examples of the new projects (or already converted templates?)?
cc: @Tratcher @jennyf19

**Comment by Tratcher** [comment]
@jmprieur see https://github.com/dotnet/aspnetcore/blob/b9efadc59ddbf6743775244622fb95301dd1846c/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs

**Comment by jmprieur** [comment]
Thanks @Tratcher. I didn't even know that this could build.
Where would you do the services.AddAuthentication() ? and the app.UseAuthentication() ?

**Comment by Tratcher** [comment]
Services are on builder.Services, app.UseAuthentication() goes between the exception handlers and the routes.

We'll update the StarterWeb templates and then you can copy or iterate on those as needed.

**Comment by DamianEdwards** [comment]
@jmprieur you can see these changes WIP in #34016

**Comment by jmprieur** [comment]
@DamianEdwards : so you've done the work?
Should we then just update the templates to use the latest version of MIcrosoft.Identity.Web and its latest features?
cc: @jennyf19

**Comment by DamianEdwards** [comment]
@jmprieur sorry didn't realize the arrangement here that you typically update the parts of the files relevant to org auth. Would be great if you could update the templates to use latest version of `Microsoft.Identity.Web` and its latest features once my PR is in.

**Comment by jmprieur** [comment]
@DamianEdwards, there isn't really an arrangement.
but yes, I'll do that. Please tell me when it is

To test the updated templates, I installed VS2022 and .NET 6. Will that be enough? or should I install internal bits for the runtime and SDK? (and in that case where to get them from)?

**Comment by DamianEdwards** [comment]
It depends on how soon you want to test them. If you want to do it as soon as they're committed to the aspnetcore repo you'll need to set things up locally for development in the repo itself. Or you can wait until the changes flow to the SDK installer and then you can simply install a CI build from dotnet/installer

**Comment by DamianEdwards** [comment]
Fixed in #7699bab0fc5b1451272c7873af45990932d3d148
