### ISSUE TITLE
Minimal APIs ModelBinderProvider

### ISSUE THREAD

**Issue by doddgu** [dotnet/aspnetcore#33955]
### Is your feature request related to a problem? Please describe.
I am trying to do let dapr-dotnet sdk support FromStateAttribute for Minimal APIs, but MvcOptions is not working. Because I use app.MapGet(?), it does not use MvcOptions.

### Describe the solution you'd like
Let me know how add ModelBinderProvider to Minimal APIs, I can not find any document about this.
Or how custom model binder to Minimal APIs.

**Comment by doddgu** [comment]
BTW, how to add HealthCheck to Minimal APIs

**Comment by BrennanConroy** [comment]
Triage: We currently don't support any model binding interception in Minimal APIs, if you want to do that you need to use MVC.
