### ISSUE TITLE
Now listening on:[port] not showing up in 5.0 after 2.2 upgrade

### ISSUE THREAD

**Issue by rafaribe** [dotnet/aspnetcore#33968]
### Describe the bug
I have upgraded from .NET Core 2.2 and replaced quite a lot of code on my `Program.cs` and `Startup.cs` to accommodate the changes in the upgrade guides.

I am missing a Log statement from Kestrel indicating in which port the server is listening to.

I want this log statement in order for VSCode to detect the host/port for the `serverReadyAction` to launch a browser when I start the server. [Info](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#starting-a-web-browser) 

Is there any flag that can be enabled to accomplish this, or am I missing some configuration pption?

### To Reproduce

```
IHost host = HostBuilder()
      .UseContentRoot(Directory.GetCurrentDirectory())
      .ConfigureAppConfiguration( ( hostingContext, config ) =>
      {
          IHostEnvironment env = hostingContext.HostingEnvironment;

          config.AddJsonFile( "appsettings.json", optional: false, reloadOnChange: true )
              .AddJsonFile( $"appsettings.{ env.EnvironmentName }.json", optional: true )
              .AddEnvironmentVariables( "WILSEN_" );
      } )
      .ConfigureWebHostDefaults(webBuilder =>
      {
          webBuilder.UseStartup<Startup>();
          webBuilder.UseUrls("http://*:8088", "http://*:8089");
      })
      .UseSerilog()
      .Build();
host.Run();
```

### Further technical details
- ASP.NET Core version 5
```
NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/
```
IDE: Irrelevant

**Comment by Tratcher** [comment]
What does your appsettings.json and appsettings.developement.json look like? These logs moved to a different provider at some point. Update to these settings:
https://github.com/dotnet/aspnetcore/blob/b9efadc59ddbf6743775244622fb95301dd1846c/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/appsettings.json#L2-L8
https://github.com/dotnet/aspnetcore/blob/b9efadc59ddbf6743775244622fb95301dd1846c/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/appsettings.Development.json#L2-L8

On a different note, is there a reason you're not using `Host.CreateDefaultBuilder()`? It includes loading appsettings.json.
https://github.com/dotnet/aspnetcore/blob/d2eab532a6a251135715fbedc88184037539d0f0/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs#L20

**Comment by rafaribe** [comment]
Thanks for the hint on the `Host.CreateDefaultBuilder(args)`. Helps avoid some boilerplate initialization.
After changing it and also the logging settings in  `appsettings.json` for each respective environment, I still don't see the respective log.

Its showing the same output as before.

![image](https://user-images.githubusercontent.com/11667740/124144661-1357ee00-da84-11eb-84c0-f5a93a7a6eca.png)

**Comment by Tratcher** [comment]
None of those look like .NET logs, they look like deployment logs. These are the logs you should be getting:

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\github\AspNetCore\src\Servers\Kestrel\samples\Http2SampleApp
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/ - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/ - - - 200 - - 86.6800ms
```

I see you've added Serilog. Serilog uses its own config settings: https://procodeguide.com/programming/aspnet-core-logging-with-serilog/#h-implement-asp-net-core-logging-with-serilog

**Comment by rafaribe** [comment]
> None of those look like .NET logs, they look like deployment logs. These are the logs you should be getting:
> 
> ```
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://[::]:5000
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Production
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: D:\github\AspNetCore\src\Servers\Kestrel\samples\Http2SampleApp
> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/2 GET https://localhost:5001/ - -
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished HTTP/2 GET https://localhost:5001/ - - - 200 - - 86.6800ms
> ```
> 
> I see you've added Serilog. Serilog uses its own config settings: https://procodeguide.com/programming/aspnet-core-logging-with-serilog/#h-implement-asp-net-core-logging-with-serilog

Thanks for the hint, I've looked at my code and I had a Serilog override to only log `Fatal` events from the `Microsoft` `SourceContext`.

I'll provide the code that i'm using  for my `ILogger` initialization in case someone has the same problem.

```  public static int Main(string[] args)
        {
            Log.Logger = BuildLogger();

            ILogger logger = Log.ForContext<Program>();
            try
            {
                IHost host = BuildWebHost(args);

                host.Run();
                return 0;
            }
            catch (Exception ex)
            {
                logger.Fatal(ex, "Unhandled exception");

                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
 ```
 Then my `BuildLogger` function has a condition if I want JSON or Human Readable logging based on a `boolean` variable.
 
 ```
 private static ILogger BuildLogger()
        {
            if (App.HumanReadableLogging)
            {
                return new LoggerConfiguration()
                    .MinimumLevel.Debug()
                    .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Information)
                    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                    .Enrich.WithExceptionDetails(
                        new DestructuringOptionsBuilder()
                            .WithDefaultDestructurers()
                            .WithDestructurers(new[] {new SqlExceptionDestructurer()}))
                    .WriteTo.Console(formatProvider: new NormalFormatProvider())
                    .CreateLogger();
            }
            return new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Warning)
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .Enrich.WithExceptionDetails(
                    new DestructuringOptionsBuilder()
                        .WithDefaultDestructurers()
                        .WithDestructurers(new[] {new SqlExceptionDestructurer()}))
                .WriteTo.Console(new RenderedCompactJsonFormatter())
                .CreateLogger();
        }
```
So in this case, If I have `HumanReadableLogging` enabled (only on developer machines), I can see the `Now listening on: http://[::]:8088` statements provided by `Microsoft.Hosting.Lifetime` `SourceContext`. 
I could have used the ` hostingContext.HostingEnvironment` variable for this, but in some situations I want `json` logging on the `Development` `HostingEnvironment`. 

Hopefully someone with the same problem can find this information useful.
