### ISSUE TITLE
Kestrel's MinimumDataRateNotSatisfied logs should be in the same category

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#33985]
https://github.com/dotnet/aspnetcore/pull/31596 which created more Kestrel categories put `RequestBodyMinimumDataRateNotSatisfied` in the `Microsoft.AspNetCore.Server.Kestrel.BadRequests` log category and kept `ResponseMinimumDataRateNotSatisfied` in the general `Microsoft.AspNetCore.Server.Kestrel` log category.

I think they should both be in `Microsoft.AspNetCore.Server.Kestrel.BadRequests`. Even though `ResponseMinimumDataRateNotSatisfied` is *technically* about the client's handling of the response and not the request, this is still an issue with the client's request/response handling as a whole. I could be convinced they should both stay in the general category, but I don't think they should be split.

**Comment by wcontayon** [comment]
Hi @halter73 can I try a PR on this issue 🙂.

**Comment by halter73** [comment]
Sure. I say go with both in the `Microsoft.AspNetCore.Server.Kestrel.BadRequests` category for now.
