### ISSUE TITLE
Missing completions in .razor in .NET MAUI Blazor app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33982]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-completions-in-razor-in-NET-MA/1440190)._

---
[severity:I'm unable to use this version]
Repro steps:

- Install .NET 6 Preview 4 and VS 16.11 P1
- Create .NET MAUI Blazor app
- Open MauiApp1 > Pages > Index.razor
- Add a code block with a string field:

```
@code {
    string text = "hi";
}
```

- Try to add a `p` tag that renders the `text` field

```html
<p>@text</p>
```

Expected result: Completions for `@text`
Actual result: No completions for `@text`

---
#### Feedback Bot on 6/2/2021, 11:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/3/2021, 10:42 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/maui/issues/1623
