### ISSUE TITLE
[Feature Request] Composable modular startup

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#33996]
### Problem
App start is messy and is getting worse. Dumping registration and configuration in `ConfigureServices()` and `Configure()` works, but with dozens of moving parts it gets hard to maintain.

Since we're stuck with all that startup code, let's at least clean it up a bit.

### Solution
Please add a composable / modular startup mechanism.

Instead of dumping code in those methods above, let us compose config in separate classes, e.g.:
````cs
EfStartupModule.cs
MvcStartupModule.cs
AutofacStartupModule.cs
SerilogStartupModule.cs
AuthStartupModule.cs
ValidationStartupModule.cs
AzureStartupModule.cs
SwaggerStartupModule.cs
````

Each one contains registrations and configurations for a single area of interest. These are discovered by assembly scan.

Each one implements `IStartupModule`:
````cs
void ConfigureServices(IServiceCollection services, IConfiguration configuration, IHostEnvironment hostEnvironment);
void Configure(IApplicationBuilder app, IConfiguration configuration, IHostEnvironment hostEnvironment, IServiceProvider serviceProvider)
````

As you can imagine from those signatures, you place the appropriate code from `Startup.cs` in those two methods instead.

Note the middleware pipeline must still be configured in `Startup.Configure()`, so as to order the middlewares (whereas StartupModules have no order). But anything unrelated to the actual pipeline can be moved to a StartupModule's `Configure()` instead.

This approach ensures configs are decoupled, simpler, easier to understand, and **more maintainable**.

### Examples
I've been doing the above for a while and it works well. It would be nice to have it in the framework itself.

Here are two example implementations which are excellent, and can be used as references:
- https://github.com/henkmollema/StartupModules (very simple and effective - this should be rolled into the framework)
- https://docs.servicestack.net/modular-startup

**Comment by ShreyasJejurkar** [comment]
That implementation (first project you reference) is quite threatening to startup performance.

Better I would suggest extension method on `IServiceCollection` and on `IApplicationBuilder` for segregation of those things and making them maintainable!

Extension method per module in application.

**Comment by lonix1** [comment]
@ShreyasJejurkar Why do you believe it's bad for perf?

I have no perf problems. It does an assembly scan for classes that implement `IStartupModule`, similar to how the framework does it for other things.

Of course, if there's indeed a better way, let's do that instead.

There's another way to look at it, and that is this: let's say you're right and it's bad for perf (though it's not). Many devs myself included would accept a startup perf reduction (what are we talking about, 1 second maybe?), in order to dramatically improve maintainability.

**Comment by davidfowl** [comment]
We have no plans to ever add scanning here, generally the team is fundamentally against things that scan by default but we're very happy to enable users to do their own scanning. FWIW it affects:
- Startup time (scanning assemblies and types)
- Trimming friendliness (when you scan, there's really no sane way to make trimming work with assembly scanning involved)

> https://github.com/henkmollema/StartupModules (very simple and effective - this should be rolled into the framework)

I'd urge you to use these frameworks as they look pretty good for this scenario.

**Comment by lonix1** [comment]
Thanks for taking the time to explain your reasoning.

Assuming assembly scanning is a "hard no" for design reasons, would the team at least consider a modular startup concept, **without assembly scanning**.?

A middle ground. Perhaps "startup modules" can be manually invoked within `ConfigureServices` and `Configure`, no scanning involved.

I realize the obvious response would be "use that library"! :-) But a structured, modular, official way to compose startup config would be great.

Right now getting an app to work (not a trivial demo, but one with all the typical libraries: IoC container, fluentvalidation, EF, mediatr, automapper, options, spa services, remote resources, swagger, etc, etc) is not easy, and is hard to maintain because it quickly becomes messy.

Something to think about? Feel free to close, and thanks again.

**Comment by davidfowl** [comment]
Our current composition model is static/extension methods which is a simple way to modularize the code. The idea of scanning or having a first class "module" concept leans more towards plugin over code organization. Startup is where coupling is supposed to happen, in a sense it's supposed to be messy, it's all of the bootstrapping logic that wires up concrete implementation, reads configuration, wires up settings etc. 

Some options you can use today:
- [IHostingStartup](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.ihostingstartup?view=aspnetcore-5.0) - These are discovered via the [HostingStartupAssemblyAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingstartupattribute?view=aspnetcore-5.0) in the application itself. You can add a services here.
- [IStartupFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.istartupfilter?view=aspnetcore-5.0) - Can be added via ConfigureServices to add middleware that wraps the pipeline. This is better for middleware that doesn't *really* care about the order.


> I realize the obvious response would be "use that library"! :-) But a structured, modular, official way to compose startup config would be great.

I actually love that this library exists https://github.com/henkmollema/StartupModules. I haven't looked deeply, but I don't see why this wouldn't be your first option. The way we make a vibrant ecosystem is by not building everything into the framework, this is one of those cases where there's a simple and effective library that does the job and is a valid alternative.

PS: We're currently updating the templates to move away from Startup classes by default. They will be used as the more advanced option going forward.

**Comment by lonix1** [comment]
Thanks again, I concede your points. I think `IHostingStartup` and `IStartup` filter is the "middle ground" I was talking about.

And I actually am using that https://github.com/henkmollema/StartupModules library, it's really great.

I understand your point about the ecosystem, and that there's a limited budget for aspnet as with all things. The only concern I always have is with libraries that become abandonware - like one finds in the Node world, which is why it's so terrible.

> PS: We're currently updating the templates to move away from Startup classes by default. They will be used as the more advanced option going forward.

I'm looking forward to see what you guys come up with!
