### ISSUE TITLE
Query parameters in Microsoft.AspNetCore.Grpc.Swagger

### ISSUE THREAD

**Issue by pavixonpl** [dotnet/aspnetcore#33993]
Hello,
I'm currently trying to implement mentioned library in our project. Everything is fine, except query parameters  combined with single route parameter in GET request. In Microsoft.AspNetCore.Grpc.HttpApi query parameters works properly, but just swagger don't show them as excpected.

**Comment by JamesNK** [comment]
I’m not sure what you mean.

Can you include you proto file, what swagger result you get, and what you expect?
