### ISSUE TITLE
Issues with file name completions in Blazor app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issues-with-file-name-completions-in-Bla/1465055)._

---
If I create an `img` tag with a `src` attribute, I get offered file name completions for files in my wwwroot folder even if I haven't typed any quotes yet. If I complete the file name, I end up with something like this with missing quotes: `<img src=~/dotnet_bot.svg>`

Even if I type the quotes first and then try to complete the file name, the quotes get removed and I end up with the same thing.

Note also that the `~/` doesn't work in Blazor apps, so the even if I add back the quotes manually, I'll get a 404 for the image file because the path is wrong.

---
#### Feedback Bot on 7/1/2021, 00:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
This issue encompasses ensuring that completion after the equal sign works as expected (aka it doesn't replace quotes if you type them and we don't provide attribute completions

**Comment by NTaylorMullen** [comment]
The file path completion items removing double quotes is being tracked internally here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338934

As for the ~/ being added to the completion output in Blazor scenarios is consistent with the older Razor editor; however, totally understand that's incorrect Blazor behavior. @ToddGrun / @jimmylewis Do you all have a work item for not providing `~/` for .razor files? I know technically we should own the file path completion item provider tech but not sure how much of a work item it'd be on your side to remove .razor from the applicable list here.

**Comment by NTaylorMullen** [comment]
Fixed in latest 17.0-P5 builds 👏 @AmadeusW
