### ISSUE TITLE
Blazor wasm 6.0.0-preview.5.21301.5, Random error occurring frequently

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#34005]
I ma using Blazor wasm .NET 6 preview (6.0.0-preview.5.21301.5)
I am running into a problem where i see this error random(but occurs too many time).
This is occurring when Starting the app.

![image](https://user-images.githubusercontent.com/3267605/124173544-ce768c00-da70-11eb-92e6-62cd25c47799.png)

Any ideas why am i getting this error and identify from where is it coming ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Are you facing this issue with a specific app, or does it happen for a newly created apps?

**Comment by nssidhu** [comment]
Looks like i was able to narrow it down to syncfusion Blazor control, remove that control from home page also removes the error.
I will post the problem on their forum.

**Comment by mkArtakMSFT** [comment]
Thanks @nssidhu. I'll close this issue then.

**Comment by nssidhu** [comment]
I would like to re-open as this seems to tough to isolate to sync fusion control.
How do i ascertain what is the root cause of the problem ?
