### ISSUE TITLE
blazor project doesn't work on server 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34017]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/blazor-project-doesnt-work-on-server/1464595)._

---
! [image.png] (https://aka.ms/dc/image?name=B50b3c603b50640ef8c7d2ab23390584e637606437490264757_20210630-175548-image.png&tid=50b3c603b50640ef8c7d2ab23390584e637606437490264757)

a empty blazor webassembly project,
it works on my PC,
but doesn't work on my server iis
(windows server 2019 datacenter, .net 5.0 installed).
what should i do?

---
#### Feedback Bot on 6/30/2021, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
