### ISSUE TITLE
minimal API - Package template 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/aspnetcore#34010]
**Available**: August 17th (this is a tentative date and may change)
**Reason**: The first iteration of minimal APIs template will be a template package on NuGet until we have all the user scenarios fully working.

**User experience**

- Install package Microsoft.AspNetCore.Minimal-api.Templates
`dotnet new install  Microsoft.AspNetCore.MinimalApi.Templates:: 0.1.0-pre`
- Create a new minimal api 
`dotnet new api -o myapi`

Related issue

- [ ] #34011

**Comment by davidfowl** [comment]
Why a package? Why don't we put this in the box?

**Comment by LadyNaggaga** [comment]
> Why a package? Why don't we put this in the box?

Fair question.  If you look at the [end to end](https://github.com/dotnet/aspnetcore/issues/34011) getting started experience I am documenting the pillars we should hit to provide developers with smooth experience that we should ship OOB.

A package also allows us to make changes and updates **fast** to the new experience without having to go through the SDK.

**Comment by davidfowl** [comment]
How do we make sure that people find it?

**Comment by DamianEdwards** [comment]
This is now setup in the [aspnet/AspLabs repo](https://github.com/aspnet/AspLabs/commit/ca86530965b7dc0585a07873938d6c722de4cb90). Versioned packages are available from the internal feed right now as there's an issue with the publishing to the public .NET feed from the AspLabs-Ci pipeline (@JunTaoLuo is looking into that). Once we decide to publish the first version to NuGet we can do so manually.

**Comment by JunTaoLuo** [comment]
FYI the package is available at https://dnceng.visualstudio.com/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.AspNetCore.MinimalApi.Templates&protocolType=NuGet&version=0.1.0-alpha.21370.3.

I'll leave the decision of manually pushing to NuGet publicly up to you folks.

**Comment by DamianEdwards** [comment]
Closing this as we've added the option to the webapi project template now.
