### ISSUE TITLE
Failing HttpClientHttp2InteropTests on Windows 8.1

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#34014]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1214891&view=results

I noticed that a couple of the Http2 client interop tests started failing on Windows 8.1 with the following message:
`System.NotSupportedException : HTTP/2 over TLS is not supported on Windows versions earlier than Windows 10 and Windows Server 2016 due to incompatible ciphers or missing ALPN support.`

This seems pretty consistent. I'm not sure what changed but maybe the machines were updated and something messed up? Needs investigation but I'll disable the tests for now. Revert https://github.com/dotnet/aspnetcore/pull/34015 when we figure out why.

**Comment by Tratcher** [comment]
FYI these tests are new. I didn't notice on the PR because we only run Win8.1 nightly. Your fix is correct (skip on < Win10), no additional follow-up is needed.
