### ISSUE TITLE
Blazor Webassembly with PostgreSQL

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34019]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Webassembly-with-PostgreSQL/1455086)._

---
[severity:It's more difficult to complete my work]
Hi, I did a program with blazor server using PostgreSQL and its works find and i able to connect the database but when I using the same method using Blazor WebAssembly i not able to connect the database. My question is does the Blazor WebAssembly support PostgreSQL? Please reply me.

---
#### Feedback Bot on 6/20/2021, 11:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Blazor WebAssembly runs within the constraints of the browser sandbox, and is consequently limited by things the browser supports. However, even if the browser were to support the protocols required by PostgreSQL, have you thought through what it means to share your credentials with arbitrary browsers and having them connect to your database server? Typically you would want to hide that behind an API endpoint.
