### ISSUE TITLE
Blazor Plublish azure site not running but all fine before, **Is this a version issue with whats on azure App even though the project is uploaded as SELF CONTAINED.**

### ISSUE THREAD

**Issue by tridexanders** [dotnet/aspnetcore#34031]
1. **Blazor Plublish azure site not running but all fine before, **Is this a version issue with whats on azure App even though the project is uploaded as SELF CONTAINED.****

2. This is a recent issue , as this all worked before, used the standard template created for Blazor app as a test, but still the same issue on plublish?

<Event>
<System>
<Provider Name=".NET Runtime"/>
<EventID>1000</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-07-02T09:18:09Z"/>
<EventRecordID>70209890</EventRecordID>
<Channel>Application</Channel>
<Computer>dw0sdwk0000TE</Computer>
<Security/>
</System>
<EventData>
<Data>Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware EventId: 1 SpanId: b0805cd15b75eae4 TraceId: c558904c7c6bff94fb64fb14f655bef0 ParentId: 0000000000000000 RequestId: 80000015-0000-d700-b63f-84710c7967bb RequestPath: / ActionId: 93125439-77ca-4fd4-a061-47ff886e0d60 ActionName: /_Host An unhandled exception has occurred while executing **the request. Exception: System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewAttributeFrame(DiffContext& diffContext, RenderTreeFrame& newFrame) in Microsoft.AspNetCore.Components.dll:token 0x600025e+0x0 at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600025c+0x52 at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x6000258+0x74 at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in Microsoft.AspNetCore.Components.d**ll:token 0x600024e+0x269 at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree) in Microsoft.AspNetCore.Components.dll:token 0x600024c+0x25 at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException) in Microsoft.AspNetCore.Components.dll:token 0x60002c4+0x5b at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in Microsoft.AspNetCore.Components.dll:token 0x600023e+0x13 at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() in Microsoft.AspNetCore.Components.dll:token 0x600023a+0x53 --- End of stack trace from previous location --- at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000060+0x0 at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() in Microsoft.AspNetCore.Components.dll:token 0x600023a+0x94 at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender() in Microsoft.AspNetCore.Components.dll:token 0x6000239+0x18 at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in Microsoft.AspNetCore.Components.dll:token 0x6000233+0x36 at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in Microsoft.AspNetCore.Components.dll:token 0x6000098+0x2d at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync() in Microsoft.AspNetCore.Components.dll:token 0x60000a1+0x24 at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() in Microsoft.AspNetCore.Components.dll:token 0x60000a0+0xc0 at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000060+0x0 at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull) in Microsoft.AspNetCore.Components.dll:token 0x6000242+0x67 at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task, ComponentState owningComponentState) in Microsoft.AspNetCore.Components.dll:token 0x6000231+0x23 at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters) in Microsoft.AspNetCore.Components.dll:token 0x60002ca+0x17 at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters) in Microsoft.AspNetCore.Components.dll:token 0x60002c8+0x42 at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters) in Microsoft.AspNetCore.Components.dll:token 0x6000229+0x72 at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000067+0x8b at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x600005e+0x74 at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext() in Microsoft.AspNetCore.Components.dll:token 0x60003f9+0x7d --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004c0+0x13c at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004b3+0xd7 at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004ae+0x16c at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in Microsoft.AspNetCore.Mvc.TagHelpers.dll:token 0x6000055+0xe4 at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count) in Microsoft.AspNetCore.Razor.Runtime.dll:token 0x600004a+0x65 at BlazorApp1.Pages.Pages__Host.<ExecuteAsync>b__14_1() in c:\Users\TridexXeon\Desktop\BlazorApp1\BlazorApp1\Pages\_Host.cshtml:line 20 at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync() in Microsoft.AspNetCore.Razor.Runtime.dll:token 0x6000046+0x84 at BlazorApp1.Pages.Pages__Host.ExecuteAsync() in c:\Users\TridexXeon\Desktop\BlazorApp1\BlazorApp1\Pages\_Host.cshtml:line 5 at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000c0+0xc7 at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000bf+0x1db at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000be+0xa7 at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000573+0x16d at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000573+0x29d at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a8c+0x6a at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a7f+0x15 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a7a+0x3dc at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a79+0xb --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a88+0x6a at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a7d+0x15 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a74+0x835 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a71+0xa --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a80+0x77 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a80+0xfb at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) in Microsoft.AspNetCore.Routing.dll:token 0x60000aa+0x5e at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) in Microsoft.AspNetCore.Diagnostics.dll:token 0x60000bf+0x70 </Data>
</EventData>
</Event>

**Comment by pranavkm** [comment]
Hi, looks like there's an issue with the preview5 build that's causing this issue. I verified this does not reproduce using the preview6 builds which should be released shortly.
