### ISSUE TITLE
.NET 5 Microsoft.AspNetCore.SpaServices.Extensions:  How to pass contextual information from the Razor view to the server-side JavaScript ?

### ISSUE THREAD

**Issue by rdalfonso** [dotnet/aspnetcore#34036]
Apologies if this is the wrong channel 

I'm required to upgrade to .NET 5 which has deprecated Microsoft.AspNetCore.SpaServices and Microsoft.AspNetCore.NodeServices in favor of Microsoft.AspNetCore.SpaServices.Extensions

.NET / react app: I cannot find any examples or documentation on how to pass contextual information from the Razor view to the server-side JavaScript like the previous solution ( asp-prerender-module /  asp-prerender-data tag helpers). Example below

```
<app asp-prerender-module="ClientApp/dist/main-server"
        asp-prerender-data='new {
            UserName = "John Doe"
        }'>Loading...</app>
```

I know these NPM packages have been deprecated in .NET 5 

Is there any examples on how to pass contextual information from the Razor view to the server-side JavaScript using Microsoft.AspNetCore.SpaServices.Extensions

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The support for server-side rendering has been deprecated. You can learn more about the change from https://github.com/aspnet/Announcements/issues/379.
