### ISSUE TITLE
Getting error while loading blazor webassembly. Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by vinayiscool** [dotnet/aspnetcore#34037]
![image](https://user-images.githubusercontent.com/78460365/124303277-dffa8980-db7f-11eb-903d-5318f4b96090.png)

Getting **Uncaught SyntaxError: Unexpected token '<'** while loading blazor webassembly. steps are below

1) Hitting URL from chrome browser
2) Loading blazor in iFrame (using .NET 5 MVC page)
3) Getting error on console.

Please let me know if more details required.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by pranavkm** [comment]
The error message usually indicates that your app is returning HTML (markup) instead of the JS file. Have you inspected your browser and server logs to see what is being returned and if your routing is configured correctly?

**Comment by vinayiscool** [comment]
@pranavkm, @mkArtakMSFT Thanks for your quick reply.

So flow of application is below
1) Login into application
2) Select menu
3) On selecting menu, it navigates to controller(i.e. ABCController) -> Action (i.e. XYZAction)
4) 3rd step is MVC route so, it renders associated cshtml, i.e. XYZ.cshtml
5) XYZ.cshtml having iFrame and iFrame source sets on XYZAction, i.e. URL of blazor client(i.e. listing page)
6) on rendering 5th step, its giving Uncaught SyntaxError: Unexpected token '<' error on console. 

Note : No server logs and not related information found on IISLogs.

Please let me know if any specific information is needed.. Thanks a lot in advance.

**Comment by vinayiscool** [comment]
@pranavkm, you are correct, its returning HTML instead of JS while clicking on error, can you help me how to get rid of that ?

![image](https://user-images.githubusercontent.com/78460365/124482668-268df500-ddc7-11eb-94fa-51816dfe48e3.png)

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core-mvc tag to reach a wider audience.
