### ISSUE TITLE
Update StartupAnalyzer to account for top level statements

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#34042]
The StartupAnalyzer specifically looks for types named Startup and will not apply to the minimal hosting pattern.

**Comment by pranavkm** [comment]
FYI @DamianEdwards

**Comment by singh733** [comment]
@pranavkm  would you please provide more details for this.

**Comment by singh733** [comment]
@pranavkm I have started working on this .When there is only top level statement no breakpoint hits .I have put breakpoint in these projects (in kestrel, TransportSockets, Hosting) . Would you please give more detail like : which file or project i need to look.

![Top Level Startup](https://user-images.githubusercontent.com/83835739/127486973-ceb04d8e-338f-4489-8df5-d484bddc3446.PNG)

**Comment by mkArtakMSFT** [comment]
This is a dupe of #34404
