### ISSUE TITLE
AKS + Ingress (nginx) + Linux + .NET Core Web Api  + Kestrel + HTTPS fails to handle low concurrency

### ISSUE THREAD

**Issue by avnerms** [dotnet/aspnetcore#34041]
Hi,
We are facing bottleneck issues with AKS + nginx-ingress + dotnet core (Kestrel) + HTTPS.
When we run our load tests (hundreds of requests in parallel) we are getting timeouts.
When calling the same API via HTTP (not HTTPS) everything works well.
When replacing the .Net core web api with NodeJS, everything works well via HTTPS.
 
Our configuration went like this : 
-> AKS cluster with few node pools , nginx ingress controller configured to work on HTTPS only ( helm chart :nginx-ingress)
-> a service that is written in .Net Core 3.1 loads the PFX certificate and allows traffic to a very simple "\healthz" endpoint
-> benchmark test : 
      creating a Bastion with "AB" (apache benchmark) on the Service  using dotnet core provides very poor results 
-> replacing the .net core with NodeJs 10 on the same VM /vNet/ CPU / memory and ingress configurations:
     -> same benchamrk tests provides amazing results , almost few hundreds requests per second on a single pod.
-> There is no CPU / memory footprints  and scaling is not required here. we also onboard to larger machines with better IOPS .
since the NodeJS code works very good on this VM (Standard_D4_v3) we want to compare apples to apples.
 
We suspect it to be a Kestrel problem as already reported here: https://github.com/dotnet/aspnetcore/issues/7081
We have changed the keep_alive_requests to 1024 , and modiftied all the timeouts of nginx to large numbers -> no effect
	
Please advise.

Thanks,

Avner

**Comment by Tratcher** [comment]
Some improvements were made here for .NET 5, are you able to test that version?

Is nginx configured to use keep-alive connections between it and kestrel?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx

**Comment by davidfowl** [comment]
> creating a Bastion with "AB" (apache benchmark) on the Service using dotnet core provides very poor results

Can you show your ab command? ab isn't a great benchmarking tool (the defaults are pretty terrible).
