### ISSUE TITLE
Not able to Debug Blazor wasm code after upgrade to .NET 6

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#34054]
I upgraded my app from .NET5 to .NET 6 running into many issue, it is totally broken.
My app is Blazor wasm PWA hosted app.
I am using VS 2022 Preview as IDE.

1) Issue one, no longer able to debug the Blazor wasm code. I can debug the server side code though.

![image](https://user-images.githubusercontent.com/3267605/124342097-f48e5000-db86-11eb-9f44-79465e44cc27.png)

Tried both IIS & webdev server

i see this fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1020 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1021 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1022 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1023 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1024 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1025 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1026 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1027 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1028 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1029 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1030 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1031 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1032 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-99B0A64254889D9908D9D8941474C0CC:::1033 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32000,   "message": "Debugger agent is not enabled" } ]

Server side 
launchSettings.json
```

{
    "iisSettings": {
      "windowsAuthentication": false,
      "anonymousAuthentication": true,
      "iisExpress": {
        "applicationUrl": "http://localhost:58042",
        "sslPort": 44378
      }
    },
    "profiles": {
      "IIS Express": {
        "commandName": "IISExpress",
        "launchBrowser": true,
        "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",

        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      },
      "BlazorBaseApp.Server": {
        "commandName": "Project",
        "dotnetRunMessages": "true",
        "launchBrowser": true,
        "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
        "applicationUrl": "https://localhost:5001;http://localhost:5000",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      }
    }
  }

```

**Comment by captainsafia** [comment]
Thanks for opening this issue, @nssidhu. Can you try the following:

- Is script debugging still enabled in VS?
- Have you tried clearing the hidden `.vs` directory that is adjacent to your solution file?
- Did you ensure that the local dev certs were configured correctly on your machine after the upgrade?

**Comment by nssidhu** [comment]
I tried 1st and 2nd option and non of them helped fix the problem.
Are there step to verify the dev certs are correct or create new one ?

**Comment by captainsafia** [comment]
Try running `dotnet dev-certs https --check`.

**Comment by nssidhu** [comment]
This is what i get
```
C:\Windows\system32>dotnet dev-certs https --check
A valid certificate was found: DA4CE700CEFD9257D6C9919CE4D568C68785D2DD - CN=localhost - Valid from 2021-03-29 20:48:04Z to 2022-03-29 20:48:04Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
Run the command with both --check and --trust options to ensure that the certificate is not only valid but also trusted.
```

```
C:\Windows\system32>dotnet dev-certs https --check --trust
A trusted certificate was found: DA4CE700CEFD9257D6C9919CE4D568C68785D2DD - CN=localhost - Valid from 2021-03-29 20:48:04Z to 2022-03-29 20:48:04Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
```

**Comment by captainsafia** [comment]
@nssidhu Got it. You mention that these issues started happening after the upgrade. Were any code changes made in your app or is the same app still debuggable under .NET 5?

**Comment by taylorchasewhite** [comment]
I also cannot debug in my .NET 6 apps.
