### ISSUE TITLE
Add IgnoreApi() extension method for IEndpointConventionBuilder

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#34068]
## Background and Motivation

Related to #34061, if using minimal hosting with minimal actions and Swashbuckle and it is possible to hide actions from API Explorer using the `[ApiExplorerSettings]` attribute (which doesn't work right now, see also #34065), it would be a quality-of-life improvement to the API surface to add an extension method for `IEndpointConventionBuilder` to make it require less verbose code to hide it.

## Proposed API

Add a new extension method to the `Microsoft.AspNetCore.Mvc.ApiExplorer` assembly with a name something along the lines of `IgnoreApi()`:

```diff
namespace Microsoft.AspNetCore.Builder
{
+    public static class ApiExplorerEndpointConventionBuilderExtensions
+    {
+       public static TBuilder IgnoreApi<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder;
+    }
}
```

The implementation would be something like this:

```csharp
using Microsoft.AspNetCore.Mvc;

namespace Microsoft.AspNetCore.Builder
{
    /// <summary>
    /// API Explorer extension methods for <see cref="IEndpointConventionBuilder"/>.
    /// </summary>
    public static class ApiExplorerEndpointConventionBuilderExtensions
    {
        private static readonly ApiExplorerSettingsAttribute _ignoreApiMetadata = new()
        {
            IgnoreApi = true
        };

        /// <summary>
        /// Ignores the endpoint(s) from the API Explorer.
        /// </summary>
        /// <param name="builder">The endpoint convention builder.</param>
        /// <returns>The original convention builder parameter.</returns>
        public static TBuilder IgnoreApi<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
        {
            builder.Add(endpointBuilder =>
            {
                endpointBuilder.Metadata.Add(_ignoreApiMetadata);
            });
            return builder;
        }
    }
}
```

## Usage Examples

``` C#
var builder = WebApplication.CreateBuilder(args);

// Configure application...

var app = builder.Build();

// Redirect to Swagger documentation
app.MapGet("/api", () => Results.Redirect("/swagger-ui/index.html"))
   .IgnoreApi();

// Configure other endpoints...

app.Run();

```

## Alternative Designs

No alternative designs considered, this is just API sugar to remove the need to use verbose way of doing this using the existing APIs, similar to the existing `AllowAnonymous()`, `RequireAuthorization()`, `RequireCors()`, `RequireHost()` and `WithDisplayName()` extension methods:

```csharp
builder.MapGet("/api", () => Results.Redirect("/swagger-ui/index.html"))
       .WithMetadata(new ApiExplorerSettingsAttribute { IgnoreApi = true });
```

## Risks

None that I'm aware of, other than potential conflicts with user-defined application extension methods of the same name.

**Comment by DamianEdwards** [comment]
Swashbuckle's [default logic for whether to include an API in a given OpenAPI document](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs#L57) is based on `ApiDescription.GroupName` today. To get the desired experience discussed here it should be updated to also look at whatever new metadata we add to indicate that an endpoint should be excluded when observing API explorer data.

**Comment by martincostello** [comment]
Happy to help out with implementing this one once a decided-upon API spec is ready.

**Comment by DamianEdwards** [comment]
@martincostello FYI I got a prototype of this [working in my playground repo].(https://github.com/DamianEdwards/MinimalApiPlayground/commit/b5f19ea8b3832508a7282d65e032bd8e633cab7c)

**Comment by martincostello** [comment]
Thanks @DamianEdwards - I had a play around with some of the suggested API additions in the epic earlier today to try and match the API surface (but not the implementation) for hiding and also the response metadata in the repo where I've been trying stuff out: https://github.com/martincostello/dotnet-minimal-api-integration-testing/commit/266fec2286862675fe9cf4014ee7c2e09f5f34c4
