### ISSUE TITLE
Blazor Virtualize scrollbar broken

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#34060]
### Describe the bug
I use blazor virtualize inside css grid (display: grid) and the scrolling when dragging scrollbar is being interrupted:
![scrolling](https://user-images.githubusercontent.com/3494407/124346917-d43faf00-dbe1-11eb-9ba1-8dae0161ed83.gif)

### To Reproduce
1. here is a working demo:  https://blazorrepl.com/repl/mvkBuHuB22FVBxY258
2. open in Edge Chromium 
3. Drag the scrollbar

```razor
<div class="sg-container" style="height:200px">
    <div class="simple-grid" style="grid-template-columns: 3em minmax(5em, auto); ">
        <Virtualize Items="_products" 
                    ItemSize="32">
            <ItemContent>
                <div class="sg-row sg-row ">
                    <div class="sg-cell ">@context.Id</div>
                    <div class="sg-cell ">@context.Name</div>
                </div>
            </ItemContent>
        </Virtualize>

    </div>
</div>
@code {
    record Product(int Id, string Name);

    Product[] _products = Enumerable.Range(1, 200)
        .Select(i => new Product(i, "Name" + i))
        .ToArray();
}
```

### Further technical details
- ASP.NET Core version: 5.0.6
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by SteveSandersonMS** [comment]
Unfortunately this is not a Blazor issue - it's an issue in Chromium which we have reported but haven't heard about any ETA for a fix. Also unfortunately, it's on the internal Edge issue tracker so I can't post a link to that.

To show it's not Blazor-specific, please note that the same problem happens with apps built in Angular, React, and Vue. There is more info about this at https://github.com/dotnet/aspnetcore/issues/26870#issuecomment-708659039. In other words, this affects all web developers, regardless of your technology choices. If this is a concern to you, please consider making your own separate reports to the Chromium or Edge projects.

**Comment by SteveSandersonMS** [comment]
Sorry, my mistake. It's not the same issue. Reopening.

**Comment by Liero** [comment]
This bug is reproducable in both Blazor Server Side and WebAssembly.
Let me know if you need further assistance.

**Comment by SteveSandersonMS** [comment]
Could you post the full source of the repro as a GitHub repo rather than the repl link? 

I notice it involves some 3rd party library and don’t know whether that is the actual problem so need to see what it does, or try reproducing the issue without the 3rd party dependency.

**Comment by SteveSandersonMS** [comment]
OK, I looked more closely, and this is an issue in the CSS being used in the application. Fortunately there is an easy solution here.

You need the element that has `overflow: auto` to be the same one that has a restricted height. Otherwise there's no way for `Virtualize` to know how much of the restricted height is meant to be taken up by the scrollable region. In the sample code provided, `.sg-container` has the fixed height of 200px, whereas a different element `.simple-grid` is the one that has the scrollbar.

To fix this, move the `height: 200px` from `.sg-container` to `.simple-grid` and then it works fine: https://blazorrepl.com/repl/GbEBOhbk297FAqW803

Note that in general, you shouldn't expect `Virtualize` to work with all possible element hierarchies and CSS rules, because it could only do that if it replicated all the CSS layout rules implemented in the browser. It depends on being able to infer the scroll position based on there being a single scrollable ancestor with a height restriction.

**Comment by SteveSandersonMS** [comment]
Also you should consider adding a `@key` to the items in `Virtualize` to make the rendering more efficient: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0

**Comment by Liero** [comment]
> To fix this, move the `height: 200px` from `.sg-container` to `.simple-grid` and then it works fine: https://blazorrepl.com/repl/GbEBOhbk297FAqW803

So the scrolling in the Virtualize component won't work with adaptive height, like 100%? I think it should be possible without any magic, as the value can be measured quite easily.
