### ISSUE TITLE
[.NET 6] Hot reload doesn't work for Blazor WASM

### ISSUE THREAD

**Issue by BearsPunch** [dotnet/aspnetcore#34085]
### Describe the bug
Hot reload doesn't work for Blazor WASM
![image](https://user-images.githubusercontent.com/66436099/124395141-b4ec7300-dd02-11eb-8408-d3c214280bdb.png)
after changing the file, I see a message "watch : File changed: ...." and nothing happens after. If manually reload the browser page also no changes. 
Also I can't close the app by Ctrl + C. I see a message " Application is shutting down..." and that's all. The app freezes until close terminal.

Hosted Blazor app, ASP.NET app  - they don't have this issue. Only WASM Blazor has this problem.

### To Reproduce
.NET 6 preview 3+ ( with "hotReloadProfile": "blazorwasm", for preview 5 - without)
Create new blazor wasm project and run with:
dotnet watch

**Comment by tesar-tech** [comment]
I have exactly the same issue. It is same for hosted app when I `dotnet watch` in server project folder. 

Windows 11 dev, VS 17 preview, dotnet 6.0.100-preview.5.21302.13

**Comment by pranavkm** [comment]
Could you run `dotnet watch` with verbose logs `dotnet watch --verbose`? I tried this using preview5 bits and it works fine locally.

**Comment by tesar-tech** [comment]
This is it:
```
PS C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server> dotnet watch --verbose
watch : Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Evaluating dotnet-watch file set.
watch : Running MSBuild target 'GenerateWatchList' on 'C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server\WebApplication7.Server.csproj'
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 26100
watch : Process id 26100 ran for 1225ms
watch : Watching 36 file(s) for changes
watch : Building...
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 14876
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  WebApplication7.Shared -> C:\Users\toted\source\repos\WebApplication7\WebApplication7\Shared\bin\Debug\net6.0\WebApplication7.Shared.dll
  WebApplication7.Client -> C:\Users\toted\source\repos\WebApplication7\WebApplication7\Client\bin\Debug\net6.0\WebApplication7.Client.dll
  WebApplication7.Client (Blazor output) -> C:\Users\toted\source\repos\WebApplication7\WebApplication7\Client\bin\Debug\net6.0\wwwroot
  WebApplication7.Server -> C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server\bin\Debug\net6.0\WebApplication7.Server.dll
watch : Process id 14876 ran for 3498ms
watch : dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
watch : Refresh server running at wss://localhost:50917.
watch : HotReloadProfile: BlazorHosted. C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server\WebApplication7.Server.csproj references BlazorWebAssembly project C:\Users\toted\source\repos\WebApplication7\WebApplication7\Client\WebApplication7.Client.csproj.
watch : Started 'C:\Program Files\dotnet\dotnet.exe' 'exec --runtimeconfig "C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server\bin\Debug\net6.0\WebApplication7.Server.runtimeconfig.json" --depsfile "C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server\bin\Debug\net6.0\WebApplication7.Server.deps.json" "C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\DotnetTools\dotnet-watch\6.0.100-preview.5.21302.8\tools\net6.0\any\hotreload\Microsoft.Extensions.HotRestart.dll"' with process id 22400
watch : Running dotnet with the following arguments: run
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
watch : Launching browser.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\toted\source\repos\WebApplication7\WebApplication7\Server
watch : File changed: C:\Users\toted\source\repos\WebApplication7\WebApplication7\Client\Pages\Index.razor.
```

Only the last line appears after the saved file change (and nothing more..).

**Comment by BearsPunch** [comment]
Won't duplicate because I have exactly the same what @tesar-tech has.

**Comment by pranavkm** [comment]
Thanks. Could I have you look at the browser Developer console to see if it includes anything interesting? This looks like a hang that I thought I'd fixed, but apparently not.

**Comment by tesar-tech** [comment]
Actually yes, there is an error:

> Firefox can’t establish a connection to the server at wss://localhost:64355/.
dotnet-watch reload socket error.

Hmm. I also tried different browsers (Brave, Edge-chromium) and it **works**. It seems this error is specific to Firefox (??).

**Comment by BearsPunch** [comment]
> Actually yes, there is an error:
> 
> > Firefox can’t establish a connection to the server at wss://localhost:64355/.
> dotnet-watch reload socket error.
> 
> Hmm. I also tried different browsers (Brave, Edge-chromium) and it **works**. It seems this error is specific to Firefox (??).

I can't test it right now, but I don't use Firefox, but Edge and Chrome. It can be the problem with cache

**Comment by pranavkm** [comment]
@tesar-tech, it's likely the developer certificate, In preview5, we started using the ASP,NET Core dev cert to host the WebSocket server that relays hot reload deltas. In p7, we fall back to a non-TLS connection if connecting via TLS fails. If you'd like you could try out the latest nightlies of our SDK and let me know if using a newer build addresses the issue: https://github.com/dotnet/installer#installers-and-binaries

**Comment by pranavkm** [comment]
@BearsPunch any chance you've been able to inspect the browser console logs? Also could you try out the nightlies to see if that helps with your issue? Thanks!

**Comment by BearsPunch** [comment]
> @BearsPunch any chance you've been able to inspect the browser console logs? Also could you try out the nightlies to see if that helps with your issue? Thanks!

 Hey @pranavkm . I've tested with preview 7 and looks like it works. But I still have error in console browser
![image](https://user-images.githubusercontent.com/66436099/125042856-9c7daf00-e09a-11eb-8258-62e6c107060d.png)

**Comment by pranavkm** [comment]
Thanks @BearsPunch for the feedback. I guess your dev environment doesn't have the ASP.NET Core developer certificate trusted. which would explain the error. We might want to address that in dotnet-watch, but that seems like a low hanging bug that we can independently fix. I'm closing this as the initial issue has been resolved.
