### ISSUE TITLE
Blazor Wasm Hosted Default Authentication not working in razor page

### ISSUE THREAD

**Issue by fayewong6198** [dotnet/aspnetcore#34080]
I try to create a Blazor wasm app with Authentication by the command and it seems to work well

> dotnet new blazorwasm --auth Individual --hosted

![image](https://user-images.githubusercontent.com/55927484/124380500-0b4bb880-dce7-11eb-8cb9-112f5bb89d47.png)

Then I can edit my password, .... It seems to work well with razor pages

![image](https://user-images.githubusercontent.com/55927484/124380538-4f3ebd80-dce7-11eb-8799-9aca27b4e7a1.png)

However when I tried to add razor page to my project, the _LoginPartial seems doesn't work. (I tried to login many times)

![image](https://user-images.githubusercontent.com/55927484/124380621-d5f39a80-dce7-11eb-8d49-665d10659dfc.png)

The _LoginPartial still work in balzor wasm and razor pages in Identity Areas

_LoginPartial file
![image](https://user-images.githubusercontent.com/55927484/124380661-16ebaf00-dce8-11eb-82d6-5b74eb4b4665.png)

Startup.cs
![image](https://user-images.githubusercontent.com/55927484/124380700-51554c00-dce8-11eb-9b4b-b205aba9de45.png)

**Comment by javiercn** [comment]
@fayewong6198 thanks for contacting us.

In order for us to make progress on this issue we would need a minimal repro project as a publicly available github repo.

**Comment by fayewong6198** [comment]
> @fayewong6198 thanks for contacting us.
> 
> In order for us to make progress on this issue we would need a minimal repro project as a publicly available github repo.

Here is the [repo](https://github.com/fayewong6198/ProcessClone)

**Comment by mkArtakMSFT** [comment]
@HaoK  can you please look into this? Thanks!

**Comment by HaoK** [comment]
Hi @fayewong6198 can you slim down the repro to the smallest set of files that demonstrates the issue?  Can you create a new blazorwasm, and only add the login page, there's currently a lot of other changes which seems to be causing restore issues for me.

Ideally if its something like dotnet new blazorwasm, then add a _LoginPartial.cshtml, etc., and then try to login (doesn't work), as an example
