### ISSUE TITLE
dotnet publish does not publish entry dll in case of Blazor WebAssembly app

### ISSUE THREAD

**Issue by mihben** [dotnet/aspnetcore#34088]
### Describe the bug
I have a Blazor WebAssembly application. After running `dotnet publish -c Release -o Publish` command the `Project.dll` file is not generated into the `Publish` directory. Without this binary the docker image cannot start, because the entrypoint is missing. (In dockerfile: `ENTRYPOINT ["dotnet", "DiabloII-Cookbook.Client.dll"]`). Only the following items will be generated to the `Publish` folder:
- `wwwroot`
- `web.config`

The problem occurs in case of fully new Blazor WebAssembly project as well.

### To Reproduce
1. Create a Blazor WebAssembly application
2. Run `dotnet publish -c Release -o Publish` in the project directory (same level as .csproj)

### Further technical details
- Target framework: net5.0
- Build engine version: 17.0.0-preview-21302-02+018bed83d

**Comment by javiercn** [comment]
@mihben thanks for contacting us.

It seems that you have created a standalone Blazor application? If that's the case, you need to use an image with an Http server to serve te files. Seem more details [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#standalone-deployment) about deployment.

**Comment by mihben** [comment]
> @mihben thanks for contacting us.
> 
> It seems that you have created a standalone Blazor application? If that's the case, you need to use an image with an Http server to serve te files. Seem more details [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#standalone-deployment) about deployment.

Yes, I use standalone Blazor application. 
Thank you for your quick answer.
