### ISSUE TITLE
Allow configuring CORS to allow wildcard origin without auth AND whitelisted domains with auth

### ISSUE THREAD

**Issue by cmeeren** [dotnet/aspnetcore#34084]
I have an API that serves a list of documents that are mostly publicly available. They are surfaced through a 1st party SPA, and they are also embeddable in other websites. Therefore, I need to allow all origins in CORS.

However, some of the documents are restricted, and requires authentication (for which I use a bearer token in the `Authorization` header). Therefore, I also have to allow credentials in CORS. (Note that only public documents are embeddable, so no auth is needed when embedding.)

[As far as I know](https://stackoverflow.com/questions/67803262/set-up-cors-in-asp-net-core-to-allow-wildcard-origin-without-auth-and-whiteliste), this is currently not possible to configure in ASP.NET Core:

* If I allow credentials, I can't allow wildcard domains.
* If I disallow credentials, then AFAIK the 1st party SPA won't send the necessary authorization for signed-in users.
* If I dynamically allow any domain (using `SetIsOriginAllowed` and always returning `true`), then AFAIK I open up for vulnerabilities if the 3rd party websites that embed data from the API are vulnerable to XSS. (But I don't really know much about the security aspect of CORS, so please correct me if I'm wrong.)

It seems to me that what I need is to allow wildcard origins without authentication, AND allow specific (1st party) origins with authentication.

**I propose that ASP.NET Core be extended to allow configuring CORS like this.**

If there are good workarounds, please let me know. For reference, here are some possible workarounds I can think of, which I'd rather not have to do:
* Deploy the API twice with different base URLs and CORS config (more complex devops)
* Dynamically allow any origin with credentials (security issue, see note earlier)
* Dynamically allow any origin with credentials, but manually block authenticated requests from non-whitelisted origins (non-standard, hacky, I'm not sure what kind of response to return)
* Disallow credentials in CORS and use a non-standard auth header for the bearer token (from the SPA). Would this cause security issues?

In case it's relevant, I'm using F# and Giraffe.

**Comment by javiercn** [comment]
@cmeeren thanks for contacting us.

I believe this is not possible and consider insecure by the spec. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials) for details.

I believe your best bet is to either duplicate the endpoints with multiple cors policies or to implement your own ICorsPolicyProvider to dynamically evaluate the request and make a decision based on the request data.

**Comment by cmeeren** [comment]
> I believe this is not possible and consider insecure by the spec. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials) for details.

That page is about using credentials with `Access-Control-Allow-Origin: *`. That's not what I'm suggesting.

In concrete terms, what I am suggesting is a way to accomplish the following, using a whitelist of hosts for which credentials are allowed:
* If the origin is "credentials-whitelisted", reflect the `Host` back at the caller and allow credentials.
* If the origin is not "credentials-whitelisted", return `Access-Control-Allow-Origin: *` and don't allow credentials

Note that each of the points above are currently possible on its own. Respectively:
* `.WithOrigins(origins).AllowCredentials()`
* `.AllowAnyOrigin()`

Furthermore, each of these options are secure and according to spec/recommendations.

What is _not_ currently possible is mixing them as I have described, where you allow all origins, credentials are only allowed for some origins. As I understand it, this is completely transparent to the client and therefore does not in any way break the spec. Nor does it introduce any security risks, since 1) the `*` value does not allow credentials, and 2) we are just switching between two completely standard CORS configs.

In other words, I want the request's host to govern whether the CORS policy is similar to `.AllowAnyOrigin()` or `.WithOrigins(origins).AllowCredentials()`. That would solve the problem where an API endpoint has public data that needs to be publicly available through browsers regardless of origin, as well as protected data that should only be available through known origins.

Please let me know if I should clarify further, and if so, where the confusion might lie.

---

Side-note regarding Giraffe: AFAIK it works as is an ASP.NET middleware, so CORS is irrelevant to it; CORS is handled before Giraffe enters the picture. Here is an excerpt from my `Configure` method:

```f#
app
  .UseCors(Configure.cors config)
  .UseGiraffe(giraffeEntryPoint)
```

Since Giraffe when used this way does not use the ASP.NET Core built-in routing, I'm not sure if it's possible for me to use ASP.NET Core's built-in functionality to configure separate CORS configs for separate endpoints.

**Comment by cmeeren** [comment]
Thanks to your mention of `ICorsPolicyProvider`, some searching and a bit of experimentation, this seems to do the trick. Let me know if I'm shooting myself in the foot. Also, I still think the requested functionality would be good to have built-in.

```f#
type CorsPolicyProvider(config: IConfiguration) =
  let origins = config.GetSection("CORS:Origins").Get<string []>()

  let configureCommonAndBuild (builder: CorsPolicyBuilder) =
    builder
      .AllowAnyMethod()
      .AllowAnyHeader()
      .SetPreflightMaxAge(TimeSpan.FromMinutes 60.)
      .WithExposedHeaders((*...*))
      .Build()

  let allowCredentialsPolicy =
    CorsPolicyBuilder().WithOrigins(origins).AllowCredentials()
    |> configureCommonAndBuild

  let publicPolicy =
    CorsPolicyBuilder().AllowAnyOrigin()
    |> configureCommonAndBuild

  interface ICorsPolicyProvider with
    member _.GetPolicyAsync(ctx: Microsoft.AspNetCore.Http.HttpContext, _policyName: string) =
      let policy =
        match ctx.TryGetRequestHeader "Origin" with
        | Some origin when origins |> Array.contains (origin.ToLowerInvariant()) -> allowCredentialsPolicy
        | _ -> publicPolicy
      Threading.Tasks.Task.FromResult policy


type Startup(config: IConfiguration) =

  member _.ConfigureServices(services: IServiceCollection) : unit =
    services
      // ...
      .AddCors()
      .AddSingleton<ICorsPolicyProvider>(CorsPolicyProvider(config))
      // ...

  member _.Configure(app: IApplicationBuilder) : unit =
    app
      // ...
      .UseCors()
      // ...
```

**Comment by javiercn** [comment]
@cmeeren your approach seems appropriate.

One thing that I would change is that I would inherit from `DefaultCorsPolicyProvider` call `base` to get the policy applied to the endpoint and then use a `CorsPolicyBuilder` to generate a new "derived" policy based on your needs. 

That way, individual endpoints still get to decide what is allowed and what not and you can still apply your behavior on top for the things you care about.

As to whether this should be built-in, It's quite a specific scenario I think and we haven't received significant feedback about this in the many years we've been shipping CORS, so I suspect its not common enough to guarantee first class support.

Using the custom CORS policy provider already feels like an adequate solution, I think.

**Comment by cmeeren** [comment]
Thanks for the tip and opinion. Closing this, then!
