### ISSUE TITLE
More detail on Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#34081]
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorBaseApp.Client.Shared.UserTokenStatusPage.<BuildRenderTree>b__33_2(RenderTreeBuilder __builder2) in BlazorBaseApp.Client.dll:token 0x600009b+0xc5

Can we add some more information to such an error like, Which Object and What Line Number the error Occurred at ?

Error message like this is not useful at all.

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

This is not something we can determine within ASP.NET Core, its a feature the runtime needs to provide.
