### ISSUE TITLE
Problem on Linux server in Authorization part for ASP.NET Core 2.2 

### ISSUE THREAD

**Issue by Qorxi** [dotnet/aspnetcore#34098]
### Description
We have problem at Default scheme authorization class on the HandleAuthenticateAsync method for custom authorization checking API end points. We checks in this method JWT coding on the like this :

I leave the codes here so that this is the problem 

if (!Request.Headers.ContainsKey("Authorization"))
                    return AuthenticateResult.Fail("Unauthorized");

                string authorizationHeader = Request.Headers["Authorization"];
                if (string.IsNullOrEmpty(authorizationHeader))
                    return AuthenticateResult.NoResult();

                if (!authorizationHeader.StartsWith("bearer", StringComparison.OrdinalIgnoreCase))
                    return AuthenticateResult.Fail("Unauthorized");

                string token = authorizationHeader.Substring("bearer".Length).Trim();
                Log.Information($"User Toke: {token}");

                if (string.IsNullOrEmpty(token))
                    return AuthenticateResult.Fail("Unauthorized");

                try
                {
                    string Key =
                        await _cacheHelper.GetAsync<string>("token_key",
                            AuthHelper.GetUserIdFromToken(token).ToString());
                    Log.Information($"Key : {Key}");

                    return AuthHelper.ValidateToken(token, publicKey, Scheme.Name);
                }
                catch (Exception ex)
                {
                    Log.Information($"Error:{ex.Message}: {ex.StackTrace} ");
                    return AuthenticateResult.Fail(ex.Message);
                }

AuthHelper.ValidateToken(token, publicKey, Scheme.Name) in this code, there is a problem for .NET Core 2.2 version on Linux server, we do not have this problem on a server with windows operating system.

**Comment by blowdart** [comment]
You'd have to ask whoever wrote the AuthHelper class. That's not a .NET provided class as far as I can tell, that's certainly not our JWT auth service.

**Comment by Qorxi** [comment]
> You'd have to ask whoever wrote the AuthHelper class. That's not a .NET provided class as far as I can tell, that's certainly not our JWT auth service.


 public static AuthenticateResult ValidateToken(string token, string publicKey, string schemaName)
        {
            RSA rsa = RSA.Create();
            rsa.FromXmlString(publicKey);
            JwtSecurityTokenHandler jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
            TokenValidationParameters tokenValidationParameters = new TokenValidationParameters
            {
                ValidateAudience = false,
                ValidateIssuer = false,
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new RsaSecurityKey(rsa),
                ValidateLifetime = true,
                LifetimeValidator = LifetimeValidator
            };
            ClaimsPrincipal principal =
                jwtSecurityTokenHandler.ValidateToken(token, tokenValidationParameters,
                    out _);
            AuthenticationTicket ticket = new AuthenticationTicket(principal, schemaName);
            return AuthenticateResult.Success(ticket);
        }


We just wrote the ValidateToken method as a wrapper operation, there are classes that Micorosft provides, I left them in the comments.

The RSA part works with .NET Core 5.0, but we are using the .NET Core 2.2 version and it does not work in a microservice there.

RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
             RSACryptoServiceProviderExtensions.FromXmlString(rsa, publicKey);
  We changed that part in this way, at this time it works on the server with windows installed, but this method does not work on the server with Linux installed.

**Comment by blowdart** [comment]
Is there a reason you don't want to use the provided Jwt middleware?

If, as I suspect it's just that FromXmlString that's erroring, then what I'd suggest is reducing it down to a console app to demonstrate the problem, and then posting a bug in the runtime repo, as it doesn't seem like an asp.net problem, rather one in the crypto code.
