### ISSUE TITLE
Complex Model Binding to File Element Not working with repeater

### ISSUE THREAD

**Issue by aloksharma1** [dotnet/aspnetcore#34094]
### Describe the bug
When using complex models form post (with repeater plugin to add more elements), the data binding working but the IFormFile Element binding doesnt work if the dot (.) is missing from html model element names. To make it clear suppose this html code:

`<input type="text" name="ComplexModel[0][Id]"/>
<input type="text" name="ComplexModel[0][File]"/>`

on **POST** we will get data in ID field but File is always null, post file is working as i can receive files in _Request.Form.Files_ Collection. If i change the **ComplexModel[0][File]** to **ComplexModel[0].File** model binding works. but the issue is most of the form repeaters follow the above mentioned pattern.

So how do i make the model binding work for **ComplexModel[0][File]**,
Thanks for the help.

### To Reproduce

Use Complex Model of List type with IFormFile element & use any form repeater i.e. jquery-repeater to add more elements and submit data & check in debugger IFormFile is Null.
### Exceptions (if any)

null
### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version "any"

**Comment by pranavkm** [comment]
> If i change the ComplexModel[0][File] to ComplexModel[0].File model binding works

This format is specifically meant as compat for jQuery's serialization which does not support files. I would recommend using the property format (using `dots) if you're manually constructing these names.

**Comment by aloksharma1** [comment]
I am not manually constructing them, I am using client side libraries to create repeater controls. if the serialization format is not supported, how come the binding works for text data say :ComplexModel[0][ID] ComplexModel[0][Name] etc. Also is their a way to introduce the format in using extension code or otherwise? i cant go around and edit js libs everywhere. its fine as long as its jquery, but when i switch to other codes like react or angular; changing core client libraries becomes a challenge.
