### ISSUE TITLE
Extract the ApplicationPart library/mechanism to it's own library/package

### ISSUE THREAD

**Issue by Alxandr** [dotnet/aspnetcore#34092]
## Background and Motivation

The `ApplicationPartManager` can be very usefull in situations outside of MVC. I've already whole-sale copy-pasted the whole solution into 2 different projects, and was about to do so again. Every time I want to add this kind of feature-set to any application I'm stuck between either creating a slimed-down version, copying the one in MVC again, or including the entirety of MVC core (and registering it's services in DI as the extension methods are on `IMvcBuilder`).

## Proposed API

```diff
-namespace Microsoft.AspNetCore.Mvc.ApplicationParts
+namespace Microsoft.Extensions.ApplicationParts
```

```diff
+namespace Microsoft.Extensions.DependencyInjection
+{
+    public static class ApplicationPartsServiceCollectionExtensions
+    {
+        public static ApplicationPartManager GetOrAddApplicationPartManager(this IServiceCollection services);
+    }
+}
```

## Usage Examples

The usage would be the same as it is today, except not married to MVC.

## Alternative Designs

As described in the background and motivation section, an alternative is simply that applications that requires it copies the source code, which I think is a sub-par solution.

## Risks

There is a namespace change here and types moving from one assembly to another which probably constitutes a breaking change. I'm not sure if this can be solved with type-forwarding. There is also the standard risk in maintaining more projects. Though there shouldn't be more code here, at least not more than a couple of extension methods.

**Comment by davidfowl** [comment]
Ship your package to NuGet. We don't have any plans to ship this thing as a feature outside of MVC.
