### ISSUE TITLE
Source build job broken for internal PRs

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#34127]
The source build job for aspnetcore is broken for internal PRs. https://dev.azure.com/dnceng/internal/_build/results?buildId=1218246&view=results

The arcade source build template has been updated to include a download of the internal runtime (https://github.com/dotnet/arcade/pull/7587), but aspnetcore also calls the `build.sh` script from within msbuild here: https://github.com/dotnet/aspnetcore/blob/main/eng/SourceBuild.props#L50, which isn't getting the correct internal runtime download args. This means that the internal PR will fail.

**Comment by dougbu** [comment]
@pranavkm is this the same issue as #34048❔

@ericstj please let us know how best to handle this and #34048. See also the continuing build breaks in #34033.

**Comment by pranavkm** [comment]
@dougbu I'm not seeing the analyzers warnings in the linked build. It looks like it's failing to download the runtime:

```
  Failed to install dotnet SDK from public location (exit code '1').
    Failed to install dotnet SDK from public location (exit code '1').
  /__w/1/s/artifacts/source-build/self/package-cache/microsoft.dotnet.arcade.sdk/6.0.0-beta.21311.3/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/__w/1/s/artifacts/source-build/self/package-cache/microsoft.dotnet.arcade.sdk/6.0.0-beta.21311.3/tools/Tools.proj] [/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/6.0.0-beta.21311.3/tools/Build.proj]
##[error]artifacts/source-build/self/package-cache/microsoft.dotnet.arcade.sdk/6.0.0-beta.21311.3/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/__w/1/s/artifacts/source-build/self/package-cache/microsoft.dotnet.arcade.sdk/6.0.0-beta.21311.3/tools/Tools.proj]
    dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
```

**Comment by dougbu** [comment]
@pranavkm for some reason I misread "source build" as "source generators". Oops 🤦 

We don't have a way to completely disable the runtime installations in our build.sh script. Therefore the fix would be to extend the command at https://github.com/dotnet/aspnetcore/blob/main/eng/SourceBuild.props#L50 to include the download arguments if the properties are set. Looking&hellip;

**Comment by dougbu** [comment]
Testing a fix in @mmitche's https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore/pullrequest/16328, https://dev.azure.com/dnceng/internal/_build/results?buildId=1224971&view=results in particular. Will open a GitHub PR containing just my added commit if that works.

**Comment by mmitche** [comment]
> Testing a fix in @mmitche's https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore/pullrequest/16328, https://dev.azure.com/dnceng/internal/_build/results?buildId=1224971&view=results in particular. Will open a GitHub PR containing just my added commit if that works.

@dougbu Did you end up opening a PR for this?

**Comment by dougbu** [comment]
> > Testing a fix in @mmitche's https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore/pullrequest/16328, https://dev.azure.com/dnceng/internal/_build/results?buildId=1224971&view=results in particular. Will open a GitHub PR containing just my added commit if that works.

> @dougbu Did you end up opening a PR for this?

No because my change didn't fix your internal PR. Can't test now because your branch no longer exists. What do you recommend❔

**Comment by mmitche** [comment]
I'll open another one for p7

**Comment by dougbu** [comment]
> I'll open another one for p7

I don't see this PR. Did you create something❔

**Comment by mmitche** [comment]
Not yet. Still finalizing public p7.

**Comment by dougbu** [comment]
@mmitche this must have been fixed (by you❔) ages ago and source-builds are working fine now. Any remaining work here❔ If not, plz close zee issue.
