### ISSUE TITLE
Update Blazor icon

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#34138]
The existing Blazor icon uses wrong color purple from the old .NET branding. We should update the Blazor icon to use new .NET purple.

![BrandBlazor_nohalo_128x](https://user-images.githubusercontent.com/1874516/124667624-81c1f500-de64-11eb-85e8-2a3739549135.png)

![180px- NET_Logo svg](https://user-images.githubusercontent.com/1874516/124667743-aa49ef00-de64-11eb-9024-2ade6f641a43.png)

**Comment by danroth27** [comment]
@sayedihashimi @vijayrkn

**Comment by sayedihashimi** [comment]
We would like for the blazor icon to use the new color from the .net icon `#512BD4`
