### ISSUE TITLE
Partial class for Razor Component does not work in .NET MAUI Blazor

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#34133]
I have already submitted this in Maui (https://github.com/dotnet/maui/issues/1516) repository but nobody responded in 5 days. So I am submitting it here as it is also related to Blazor.

In Blazor Web Assembly and Blazor Server, we use partial class for Razor component to separate the C# Code from Razor Code. In .NET MAUI Blazor, the partial class for Razor Component is not working. It shows the following error:

>'LoginComponent.OnInitialized()': no suitable method found to override

![124151532-76617900-dab4-11eb-94af-93859ff3b8ff](https://user-images.githubusercontent.com/14342773/124656554-2d019700-dec3-11eb-9fb8-02cc87b54763.png)

Thank you.

**Comment by Eilon** [comment]
Closing as dup of the MAUI one. I was on vacation last week so that why there was no response 😄
