### ISSUE TITLE
Publish errors with multiple files with same relative paths

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#34142]
### Describe the bug
I am trying to publish an application that is composed of multiple projects. Two of those projects have a 'project.json' and a 'project-lock.json' as they use npm for some build functionality. On attempting the publish I get
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Found multiple publish output files with the same relative path: C:\Solutions\OHI\Optimiser\Optimiser.2021\package-lock.json, C:\Solutions\OHI\Optimiser\GeneralComponents\package-lock.json, obj\Release_Server\net6.0\compress\5DHazuFb.br, obj\Release_Server\net6.0\compress\umeHzM7o.br, obj\Release_Server\net6.0\compress\5DHazuFb.gz, obj\Release_Server\net6.0\compress\umeHzM7o.gz.	Optimiser.2021.Web		0	
```
The two projects are listed in the error message. All projects in the solution are .Net 6

### Further technical details
```
Microsoft Windows [Version 10.0.19043.1052]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ms>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\ms>
```

Visual Studio 17.0.0 P1.1

**Comment by MarkStega** [comment]
I found the underlying cause of this issue. When you run NPM as part of the build process it generates project-lock.json; As a default VS treats this with properties of 'Build action -> content' and 'Copy -> Copy if newer'. Simply changing the 'Build action -> None' resolves the issue in my case.

But what if two projects really had content with identical names that were to be included? This does not affect me but could be an issue for others.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The support for server-side rendering has been deprecated. You can learn more about the change from https://github.com/aspnet/Announcements/issues/379.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Glad that you've been able to resolve the issue. In .NET 6 we've introduced this behavior to error when conflicting files are discovered. So developers should resolve those issues as these are error scenarios. Here is the announcement for the change: https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output
