### ISSUE TITLE
Is there any LostFocusAsync() method in Blazor

### ISSUE THREAD

**Issue by mckaragoz** [dotnet/aspnetcore#34156]
In net 5, we have FocusAsync() method.

Is there a similar way to lost focus programmatically?

**Comment by javiercn** [comment]
@mckaragoz thanks for contacting us.

No, we don't have/offer that capability. I'm not sure if this is a standard DOM feature or not. If its not a standard DOM feature we are very unlikely to offer something out of the box unless we see an overwhelming demand for it. If its a standard DOM feature, we suggest you implement it via JS interop. Again, unless we see a lot of demand for it, we likely won't do something in the box.

**Comment by mckaragoz** [comment]
I ask this issue for making arrangements on input even if it has focus. Inputs don't accept the programmatically changes to render while it has focus.

So as a long-term-service planned framework, if .Net 6 has complete power on focus and lostfocus, it would be great and users can implements lots of things based on this.
