### ISSUE TITLE
Run .NET FX 4.8 + ASP.NET Core 2.1.x application and .NET Core 5 + ASP.NET Core 5 application on same server?

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#34158]
Is it possible to run two such applications in the same IIS?

Is the ASP.NET Core 5 Hosting Bundle able to run ASP.NET Core 2.1.x/.NETFX4.8 applications as well?

Best regards,
D.R.

**Comment by blowdart** [comment]
The hosting bundle doesn't affect 4.x applications at all, the ability to run those is bundled into Windows and IIS, you need to install the 4.x runtime through the OS. The hosting bundle isn't limited to a specific runtime, but, if, for example, you installed the .NET 5 hosting bundle it won't install the 2.1 or 3.1 runtimes, you have to do that separately, but it will work, you don't need an extra hosting bundle for those. So, to summarise

- .NET 4.x is supported by the OS
- The .NET Core/.NET hosting bundle will support any previous versions of the runtime that are installed, but you need to install those runtimes after you install the latest hosting bundle

**Comment by fschmied** [comment]
I think the question is whether the ASP.NET Core 5.0 IIS module version also supports forwarding to an ASP.NET Core 2.1 application.

ASP.NET Core 2.1 only had the out-of-process hosting model, so the answer probably depends on the protocol between the IIS module and the ASP.NET Core application. The protocol is HTTP, so no big deal, but have details (headers etc. that the IIS integration at the application side interprets) changed?

Is this a supported scenario?

**Comment by fschmied** [comment]
@blowdart Do you happen to know this offhand?

**Comment by blowdart** [comment]
It should @shirhatti for the final word though.

**Comment by drauch** [comment]
Can you please give us an answer, we really need to release this to production and are stuck because we don't know yet whether this is supported.

Best regards,
D.R.

**Comment by shirhatti** [comment]
Yes. ANCM is always backwards compatible.

I meant to link to this issue- https://github.com/dotnet/AspNetCore.Docs/issues/22565#issue-924470739
