### ISSUE TITLE
Getting Uncaught (in promise) RuntimeError: abort(undefined) error on .NET 6 Preview 4 on blazor webassembly with AOT enabled

### ISSUE THREAD

**Issue by vinayiscool** [dotnet/aspnetcore#34161]
![image](https://user-images.githubusercontent.com/78460365/124752923-13edfa00-df46-11eb-8938-2dedbaf54f53.png)

Steps : 
As per .NET 6 Preview 4 blog (https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/)
Installed .NET 6 Preview 4
And set <RunAOTCompilation>true</RunAOTCompilation>
then publish blazor client using dotnet publish -c Release
then set pointing of this published content to IIS.

While accessing through application getting above attached error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We've have many fixes in this area in preview5. Can you please try it out and if that fails too, please share a minimalistic repro project (hosted as a GitHub repo) so that we can investigate.

**Comment by abhimantiwari** [comment]
We have one more customer facing exactly same error...suggested to try preview5
