### ISSUE TITLE
Blazor & MAUI import css/js with wildcard

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#34165]
### Problem

I am start playing with blazor & MAUI. And I want to ask if there is way to include css/js file in same way as with aspcore `asp-href-include="~/test.*.css`. Because currently we have setup workflow for web with NPM with `[name].[chunkhash].js`

### Describe the solution you'd like

Would be nice to have option to somehow (easyly use this feature with MAUI). I do not know how it is implemented but it would be nice to host blazor app from standart `.cshtml` layout/razorpage with all it feature (i don't know if that is possible).

**Comment by Eilon** [comment]
Hi @jirisykora83 for now the `index.html` file needs to be a static file in the project so this is not directly possible. If your _build process_ can update the `index.html` file then you could have it do the globbing/wildcard logic and update the file with the dynamic content.

**Comment by jirisykora83** [comment]
Thanks you for response. It is something what I really don't want messing js/webpack. Will be nice to consider this as feature because at least for me is agility easily reuse blazor component in mobil app big point.

Not sure how others but in my case we already rewrite some views to blazor component (in our web project) and now plays with migration some components to RCL (i will be really happy if default MVC template have this setup because that could make adding mobile app much easiest).

For anybody who have same issue / setup.

This could build your `index.html`
```
plugins: [
new HtmlWebpackPlugin({
		template: path.join(__dirname, '../ProjectName.Ui.Maui/ProjectName.Maui/wwwroot/index_template.html'),
		filename: path.join(__dirname, '../ProjectName.Maui/ProjectName.Ui.Maui/wwwroot/index.html'),
		inject: "body",
		minify: false,
		publicPath: '/_content/ProjectName.Ui.Components/dist'
	}),
]
```

@Eilon Thanks for point me to right direction :)

Is current implementation blazor with MAUI basically starting asp core process which then communicate with WebView or there is some other technologie involved? I would like to use `IWebHostEnvironment` but it is not registred in DI (at least with default setup)
