### ISSUE TITLE
Add a paramter to StartAsync

### ISSUE THREAD

**Issue by ponyspeed888** [dotnet/aspnetcore#34192]
Almost all use cases require some kind of description for a connection.  so it make sense to add an overload method to HubConnection class

 Task StartAsync(string ConnectionDescription,  CancellationToken cancellationToken = default);

And on the server side

        public virtual Task OnConnectedAsync(string ConnectionDescription)

With these changes user can use a Dictionary to associate connectionId with a name

**Comment by davidfowl** [comment]
Unfortunately this isn't as simple as adding APIs, the protocol would need to change. Can you show how this would be used? This feels like a generic "header collection" feature feels better to be than a connection description feature. Nevertheless we're too late in the cycle to design something like this now so I'd recommend using a query string as a workaround

**Comment by ponyspeed888** [comment]
thank you for the fast response.  I just finished a sample project at https://github.com/ponyspeed888/SignalRUtil.  Using header as you suggested ( and another way using a custom RegisterMe method).  If Microsoft can implement the same functionality for java and javascript client that will make signalR much more useful

**Comment by BrennanConroy** [comment]
There are two ways to do this, you can add the name to the query string which will work on all clients. Or you can have a hub method that you call when first starting the connection that sets a name for the connection.

We don't plan on adding a new pattern for `OnConnectedAsync`.
