### ISSUE TITLE
Chrome onclick select>option not firing (blazor serverside)

### ISSUE THREAD

**Issue by courosh12** [dotnet/aspnetcore#34194]
Just as the title says it.  
Chrome version: 91.0.4472.124

Following code in a new serverside blazor app:

```
@page "/"
@inject IJSRuntime JsRuntime

    <p>
        <label>
            Select:
            <select>
                <option value="test" @onclick="Click">test</option>
            </select>
        </label>
    </p>


@code {


    private void Click()
    {

        JsRuntime.InvokeVoidAsync("alert");
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is HTML behavior and it's discussed at https://stackoverflow.com/a/1402268

**Comment by courosh12** [comment]
Thank you. The werid thing is when u have the multiple tag on the select element it does fire the event. Just for future googlers.
