### ISSUE TITLE
Unable to start a debugging session for a Blazor WASM app with Google Chrome

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34190]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-start-a-debugging-session-for-/1469887)._

---
[severity:It's more difficult to complete my work]
! [blazor_debugging. PNG](https://aka.ms/dc/image?name=B913baf6d51474bec97986d58be5c7bd0637612698159646624_blazor_debugging.PNG&tid=913baf6d51474bec97986d58be5c7bd0637612698159646624)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
It looks like you are trying to debug on a production deployment and not on localhost. Debugging Blazor WASM is currently only supported on development, Debug builds.

You can check out all the requirements in our docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio
