### ISSUE TITLE
🐛   ReferenceError: self is not defined --> I am using version "next": "^11.0.0", and I am getting this error in my link.

### ISSUE THREAD

**Issue by onurykaya** [dotnet/aspnetcore#34202]
### Describe the bug
!This situation occurs only in projects using next.js
 I am using version "next": "^11.0.0", and I am getting this error in my link.
----> When I update the signalR version, I get the following error.

My new signalR version   ->	    "@microsoft/signalr": "^5.0.7",
Old signalR version          ->       "@microsoft/signalr": "^3.1.9",

![image](https://user-images.githubusercontent.com/40173569/124934148-267f3680-e00d-11eb-839c-6b68165fe956.png)

### To Reproduce
To reproduce this issue, check to have the following code:

const mainHubConnection = new signalR.HubConnectionBuilder()
		.withUrl(sportProgram, {
			skipNegotiation: true,
			transport: signalR.HttpTransportType.WebSockets,
		})
		.configureLogging(signalR.LogLevel.Information)
		.build();

	let startSocket;

	const handleSocketConnection = () => {
		if (eventData) {
			startSocket = () => {
				try {
					mainHubConnection.start()
						.then(() =>
							mainHubConnection.invoke("listen", programType, sportId)
								.catch((err) => {
									Sentry.captureException(err);
								}));
				} catch (err) {
					Sentry.captureException(err);
					setTimeout(startSocket, 5000);
				}
			};

			mainHubConnection.on("ReceivedSportProgramBySportId", (event) => {
				if (Object.keys(event).length > 0) {
					handleEventChange(event);
				}
			});

			if (sliderEvent) {
				startSocket();
			}
		}

### Further technical details
- ASP.NET Core version 5.0
- Webstorm 2021.1.3

**Comment by muratdogan17** [comment]
+1

**Comment by BrennanConroy** [comment]
Please provide a small self-contained repro app as a GitHub repository.

**Comment by BrennanConroy** [comment]
It looks like next.js does server-side rendering by default. It doesn't make sense to run the SignalR client on the server-side, so you need to make sure that the client connection only runs on the client-side.
