### ISSUE TITLE
Publishing a .Net 6 application to a file directory can result in extraneous content

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#34204]
### Describe the bug
I am publish my app to a destination of 'publish\' with the option of 'Delete existing files -> true'

If I do a second publish I get an extra directory in the output directory named 'publish'

### To Reproduce

Create a publish profile as in:
![devenv_2021-07-08_11-21-21](https://user-images.githubusercontent.com/634561/124948525-c07bba80-dfde-11eb-9f6b-6c9906ad5a57.png)

![devenv_2021-07-08_11-17-32](https://user-images.githubusercontent.com/634561/124947844-316ea280-dfde-11eb-9f78-aacdd1f80ab7.png)

Perform a publish an observe the output directory contents:
![explorer_2021-07-08_11-12-39](https://user-images.githubusercontent.com/634561/124947938-451a0900-dfde-11eb-9ff5-b29dc8b27191.png)

Perform a second publish and note that a directory 'publish' is in the output with content:
![explorer_2021-07-08_11-13-57](https://user-images.githubusercontent.com/634561/124948097-65e25e80-dfde-11eb-9e4e-77e94173f565.png)
![explorer_2021-07-08_11-14-09](https://user-images.githubusercontent.com/634561/124948115-6975e580-dfde-11eb-98bb-f2c51c63bf41.png)

If you then delete the top level publish directory and publish for a third time the results are the same as the first publish above.

### Further technical details
C:\Users\ms>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS 17.0.0 P1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you observe the same behavior when publishing using dotnet cli?

**Comment by danroth27** [comment]
@vijayrkn @sayedihashimi 

What version of VS is this?

**Comment by sayedihashimi** [comment]
@MarkStega What version of VS is this?

**Comment by vijayrkn** [comment]
It looks like you are publishing to the project folder instead of a temp folder. This means the 'publish' folder is getting added as additional content.  You can remove `publish` from your content glob in the csproj & you should be good.

**Comment by MarkStega** [comment]
@sayedihashimi VS 17.0.0 P1.1

**Comment by MarkStega** [comment]
@vijayrkn I am publishing to 'publish/' but I have the 'Delete all existing files prior to publish' turned on.

**Comment by vijayrkn** [comment]
Based on this image, you are publishing to the root of your project. 
![image](https://user-images.githubusercontent.com/3981619/125129912-f7bc9b00-e0b4-11eb-8799-57d7234e365e.png)

Once the publish is complete, the folder will contain assets that the project will consider as project artifacts. That is the reason you are seeing the publish folder appearing again. 

 To fix this, you can add the following to the csproj under the propertygroup: 

`
 <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/publish/**</DefaultItemExcludes>
 </PropertyGroup>
`

**Comment by MarkStega** [comment]
@vijayrkn So what good does having the 'Delete all existing files prior to publish' option turned on? Your solution works but if feels like the delete prior to publishing should also work.

**Comment by vijayrkn** [comment]
Delete existing files does delete the folder before publishing but the 'step that computes the files to publish' happens before the folder is deleted. That is the reason an additional publish folder is getting created. 

If you were publishing to a folder under 'bin' or 'obj' then you won't see this behavior since these folders are already excluded by default & delete existing files will also work. Hope that explains.
