### ISSUE TITLE
Blazor WASM has a curious dependency on the case of the URL used to initiate the application

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#34212]
### Describe the bug
Create a Blazor WASM app and deploy it upon IIS in an application under the default web site. When accessing the application you can get a failure of "System.ArgumentException: The URI 'https://t570/optimiser.2021/' is not contained by the base URI 'https://t570/Optimiser.2021/'."

### To Reproduce
1) Create the application (setting the '[Base href="/Optimiser.2021/" /]' in the index file
2) Deploy to an IIS application under the 'Default Web Site' called 'Optimiser.2021'
3) Browse to 'https://t570/optimiser.2021/' and receive the aforementioned error
4) Browse to 'https://t570/Optimiser.2021/' and see success (Note the case of the worrd 'Optimiser')

Since I believe that URL's are deemed case insensitive, this seems like a very poor choice has been made in the determination of whether a resource is contained in a base URI with a case dependent comparison.

### Further technical details
```
C:\Users\ms>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS 17.0.0 P1.1

**Comment by javiercn** [comment]
@MarkStega thanks for contacting us.

It's not a "curious" dependency, it is a requirement for navigation, links and resources to work correctly.

URLs are case-sensitive even though  ASP.NET Core routing decides to treat them as case-insensitive, IIS and other servers will not, hence the error you are seeing.

**Comment by MarkStega** [comment]
I don't see this as am IIS issue. All of the resources (css/js) were loaded correctly with the 'wrong' url. It was the startup of Blazor itself where the error was thrown. Suspicion is that is was in the Blazor NavigationManager where an ordinal comparison is done to determine if the request is 'within' the base.
