### ISSUE TITLE
Move IHubClients and IHubCallerClients from SignalR to separate library

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#34228]
Example solution structure:
# ApiLibrary (NetCore Lib)
- ref SignalR.Client

Here i want to declare some logic for server side and some api (proxy methods calling server and some logic to subscribe callbacks) for client side. 
To do this, i need IHubClients and IHubClients<T> interfaces, to call client from server like context.All.SomeClientMethod(),
and now i have to reference SignalR library to use jus this interface

# Server (AspNetCore App)
- ref ApiLibrary
- ref .SignalR

here i make some class of Hub<T> and inject logic from ApiLibrary, passing this.Clients as argument 

# Client (Blazor App)
- ref ApiLibrary

here i call api methods and subscribe callbacks from ApiLibrary

Finally, it would be grate, if this (and maybe some others) interfaces will be moved to separate library like .SignalR.CommonInterfaces

**Comment by davidfowl** [comment]
It would be great if you could provide more details about why this would be helpful.
