### ISSUE TITLE
Feature request: Blazor Template Counter-component - Update the visuals for .NET6 

### ISSUE THREAD

**Issue by pownas** [dotnet/aspnetcore#34223]
In the Blazor template Application, you can maybe consider to update something visual in the counter clicker code? That so we in all YouTube videos I’ve watched on Blazor lately, easily can see if the counter-component (that are shown in ALL Blazor videos), have something more visual so we can see directly if it’s the Blazor .NET6 template or not. 

![image](https://user-images.githubusercontent.com/47676607/125033363-84ecf900-e08f-11eb-881f-50df255ee5f3.png)

A nice visual and short minimal code to add, could maybe bee in the visuals to add a small update that multiply the output of the clicker.

### Describe the solution you'd like
something like I found in this minimal framework: 

![image](https://user-images.githubusercontent.com/47676607/125033203-4fe0a680-e08f-11eb-9ab7-2c49e74c3764.png) 
    
      
        
## Example 
Example of Blazor output on screen could be something like a nice visual clue:

“Current count: 3, that multiplied to: 6”
Or
“Clicked 3 times, and that multiple to: 6”

### Also…
If I’m in the wrong repository for this issue, please guide me to the Blazor template repository.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.

**Comment by pownas** [comment]
Ok, thanks for a quick response, but sad to hear.
