### ISSUE TITLE
Blazor WASM always shows integrity error once after every new deployment

### ISSUE THREAD

**Issue by shadarath** [dotnet/aspnetcore#34230]
### Describe the bug

I have an error that occures after every deploy to server. Refreshing page makes bug go away until deployment of new version. Error shown is integrity error and hash shown always contains hash from previous build.

### To Reproduce

I am able to reproduce error with following steps:
 - I make simple change to client blazor project
 - I publish app into azure webapp (for test I am using VS's built in publish function)
 - I have an error and application fails to load
 - I refresh webpage, which makes error go away and app works correctly
 
I then repeat all steps and I have exacly the same situation every time:
 - error shown is integrity error on all the files I have changed (in case of this test, it's Project.Client.dll file contining blazor wasm app)
 - hash value in the integrity error always shows correct hash of previous deployment (so incorrect for current deployment)
 - files on server always have correct, newest hash in files blazor.boot.json, service-worker-assets.js, also if I download published dll itself it also has correct hash.
 
### Additional information

I have been struggling with this problem for weeks, and I have been able to reproduce it in few configurations:
- app deployed statically to apache ftp server as well as served directly by .net core server
- app deployed using VS Publish function as well as deployed by Azure Pipelines

### Exceptions (if any)
Error appears for every assembly that was changed:
`Failed to find a valid digest in the 'integrity' attribute for resource '[Host]/_framework/Project.Client.dll' with computed SHA-256 integrity 'AV4BnHp9H2ZbVjXoUXDs3rY9QuOQtcb0pbMf4SVjm00='. The resource has been blocked.`

Edit - There is actually more errors shown, some are most likely not related but just in case I will include it all:
```
Uncaught (in promise) TypeError: Failed to fetch
(index):29 GET https://js.monitor.azure.com/scripts/b/ai.2.min.js net::ERR_FAILED
(anonymous) @ (index):29
(anonymous) @ (index):29
(anonymous) @ (index):29
bienergy-dev.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://bienergy-dev.azurewebsites.net/_framework/PVShop.Client.dll' with computed SHA-256 integrity 'AV4BnHp9H2ZbVjXoUXDs3rY9QuOQtcb0pbMf4SVjm00='. The resource has been blocked.
bienergy-dev.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.
blazor.webassembly.js?s=8:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at blazor.webassembly.js?s=8:1
    at blazor.webassembly.js?s=8:1
    at Object.throw (blazor.webassembly.js?s=8:1)
    at s (blazor.webassembly.js?s=8:1)
d.printErr @ blazor.webassembly.js?s=8:1
(anonymous) @ blazor.webassembly.js?s=8:1
Promise.catch (async)
(anonymous) @ blazor.webassembly.js?s=8:1
n @ blazor.webassembly.js?s=8:1
(anonymous) @ blazor.webassembly.js?s=8:1
(anonymous) @ blazor.webassembly.js?s=8:1
VM6:1 POST https://northeurope-0.in.applicationinsights.azure.com//v2/track 400
```

### Further technical details

 - Visual Studio Community 2019 version 16.10.1
 - ASP.NET Core version 5.0.301
 - Microsoft.AspNetCore.Components.WebAssembly lib version 5.0.7
 
### Output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.116 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please try to follow the following guidance and see whether that helps: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures

**Comment by shadarath** [comment]
Thank you for your response.

I have already tried to follow it, and it looks like everything is correct.
However, I was not able to get integrity.ps1 to work, best result I was able to get is error 404.
It took the script over 15 minutes to produce this result, and I was not able to get any meaningful result out of it.

```
Invoke-WebRequest : Response status code does not indicate success: 404 (Not Found).
At C:\Users\Bartek\Desktop\integrityscript\integrity.ps1:126 char:3
+   Invoke-WebRequest $url -Headers @{'Accept-Encoding' = 'identity' }  ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.7
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

Unfortunately I am not very proficient with powershell
Still, all other points of checklist seem to be satisfied.

**Comment by shadarath** [comment]
Hello, 

For past few days I have been doing a lot of simple tests to try and pinpoint what exacly is causing problems.
I now think it has something to do with CSS isolation functionality. About my tests:

Between every iteration I did following:
 - I make a big change in code
 - I make app to be forgotten by browser by going to 'dev console -> Cache storage' and removing all of cached storages
 - I deploy app - this always it works correctly (expected)
 - I increment counter in Index.razor to make sure assembly hash is different
 - I deploy app - now, depending on big change from first step, app can work correctly, or fail with my usual integrity error

My goal was to cut as much as possible while still being able to observe an error. I tried to produce a minimal sample with nothing except thing that causes error. I have however reliably and reproducibly observed something very, very strange:

My base version of app produces error.
If I change my base version in any of .razor or .cs it doesn't really have any impact on the test
If I however make ANY change in any of .razor.css files, it suddenly begins to work correctly.

This is very inconvenient because removing any of the many .razor files causes app to suddenly work, so I do not know how to make a small reproducible sample..

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by shadarath** [comment]
I have managed to find solution to my problem.

During lifetime of my project I added PWA capability to it, using this guide:
https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#convert-an-existing-blazor-webassembly-app-into-a-pwa

It suggested there are two equivalent methods to get file service-worker.published.js
I chose to use file from github to match my version of blazor (5.0.7)

Today I have created a new PWA-enabled blazor template, and noticed that despite also using 5.0.7 version, the content of service-worker.published.js is slightly different than in repository.

Using service-worker.published.js from generated template solved my issue
