### ISSUE TITLE
JwtBearerHandler logs the provided token when SecurityTokenValidators are not able to read the token

### ISSUE THREAD

**Issue by vh-vahan** [dotnet/aspnetcore#34233]
I can see the following being logged -
_Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token: **"the provided access token"**_

JwtBearerHandler returns this error here when none of the SecurityTokenValidators can handle the provided token  https://github.com/dotnet/aspnetcore/blob/0f37ede529d5b16aec856039ce18568d15d223e2/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L184

and the AuthenticationHandler logs the error - https://github.com/dotnet/aspnetcore/blob/0f37ede529d5b16aec856039ce18568d15d223e2/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L219
https://github.com/dotnet/aspnetcore/blob/cb9ed02a31b7ea5c8ce8b0f54c5230d9a904739c/src/Security/Authentication/Core/src/LoggingExtensions.cs#L39
`_authenticationSchemeNotAuthenticatedWithFailure = LoggerMessage.Define<string, string>(
                eventId: new EventId(7, "AuthenticationSchemeNotAuthenticatedWithFailure"),
                logLevel: LogLevel.Information,
                formatString: "{AuthenticationScheme} was not authenticated. Failure message: {FailureMessage}");`

Seeing that it contains PII wondering if the token should be removed from the  logged message.

**Comment by blowdart** [comment]
Addressed in https://github.com/dotnet/aspnetcore/issues/35246
