### ISSUE TITLE
.Net Core 5 Web Api doesn't work on IIS and always returns 404 error

### ISSUE THREAD

**Issue by NeginGit** [dotnet/aspnetcore#34231]
![Screen Shot 2021-07-09 at 8 29 53 AM](https://user-images.githubusercontent.com/17353710/125078081-e614cc80-e08f-11eb-97dc-867af31f3c0a.png)
![Screen Shot 2021-07-09 at 8 30 58 AM](https://user-images.githubusercontent.com/17353710/125078159-02186e00-e090-11eb-8545-c8065a4cd616.png)
.Net Core 5 Web **API** (not Web Application), doesn't work on IIS. It always returns 404 error.
I also tried to  run it through command prompt by "dotnet {my_web_api_dll_name}.dll", and it didn't work either.
I have not problem with .Net Core 5 Web **Application**, though.

I saw that it's been reported for .Net Core 3, before (https://github.com/dotnet/aspnetcore/issues/12648). Would that be a similar issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You're using wrong url for the endpoint. Try to use `https://localhost:5001/weatherforecast` instead.
