### ISSUE TITLE
Blazor Azure Deploy Now not worling Log event, Could some please help as out Project cannot continue? not workd before no issues!!!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34244]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Azure-Deploy-Now-not-worling-Log-/1467203)._

---
HelperMethodFrame_1OBJ
System.Runtime.CompilerServices.CastHelpers.ChkCastAny
Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[[System.__Canon System.Private.CoreLib][System.__Canon System.Private.CoreLib]]
Microsoft.AspNetCore.Components.Reflection.ComponentProperties. <SetProperties>g__SetProperty|3_0
Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties
Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties
Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync
Radzen.RadzenComponent.<>n__0
Radzen.RadzenComponent+<SetParametersAsync>d__51.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Radzen.RadzenComponent+<SetParametersAsync>d__51 Radzen.Blazor]]
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Radzen.RadzenComponent+<SetParametersAsync>d__51 Radzen.Blazor]]
Radzen.RadzenComponent.SetParametersAsync
Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff
Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue
Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged
Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync
Microsoft.AspNetCore.Components.ComponentBase+<RunInitAndSetParametersAsync>d__20.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Components.ComponentBase+<RunInitAndSetParametersAsync>d__20 Microsoft.AspNetCore.Components]]
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Components.ComponentBase+<RunInitAndSetParametersAsync>d__20 Microsoft.AspNetCore.Components]]
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync
Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync
Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters
Microsoft.AspNetCore.Components.RenderTree.Renderer+<RenderRootComponentAsync>d__36.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Components.RenderTree.Renderer+<RenderRootComponentAsync>d__36 Microsoft.AspNetCore.Components]]
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Components.RenderTree.Renderer+<RenderRootComponentAsync>d__36 Microsoft.AspNetCore.Components]]
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.AddComponentAsync
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost+<>c__DisplayClass35_0+<<InitializeAsync>b__0>d.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost+<>c__DisplayClass35_0+<<InitializeAsync>b__0>d Microsoft.AspNetCore.Components.Server]]
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost+<>c__DisplayClass35_0+<<InitializeAsync>b__0>d Microsoft.AspNetCore.Components.Server]]
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost+<>c__DisplayClass35_0. <InitializeAsync>b__0
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__9_0>d.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__9_0>d Microsoft.AspNetCore.Components]]
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__9_0>d Microsoft.AspNetCore.Components]]
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c.<InvokeAsync>b__9_0
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronouslyIfPossible
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.InvokeAsync
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.InitializeAsync
Microsoft.AspNetCore.Components.Server.ComponentHub+<StartCircuit>d__12.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Components.Server.ComponentHub+<StartCircuit>d__12 Microsoft.AspNetCore.Components.Server]]
System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon System.Private.CoreLib]]. Start[[Microsoft.AspNetCore.Components.Server.ComponentHub+<StartCircuit>d__12 Microsoft.AspNetCore.Components.Server]]
Microsoft.AspNetCore.Components.Server.ComponentHub.StartCircuit
DynamicClass.lambda_method7
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1+<ExecuteMethod>d__21[[System.__Canon System.Private.CoreLib]]. MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1+<ExecuteMethod>d__21[[System.__Canon System.Private.CoreLib]] Microsoft.AspNetCore.SignalR.Core]]
System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon System.Private.CoreLib]]. Start[[Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1+<ExecuteMethod>d__21[[System.__Canon System.Private.CoreLib]] Microsoft.AspNetCore.SignalR.Core]]

---
#### Feedback Bot on 7/5/2021, 02:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what is the issue that you're facing. Please share more details about what you're trying to do, what was working and hat has changed recently that it's not working any more.
