### ISSUE TITLE
Added services in DI after startup aren't visible by Controllers constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34240]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Added-services-in-DI-after-startup-aren/1468754)._

---
Any services added in the IServiceCollection after the startup phase (through the dynamic load of the Application Part or Collectible Assembly System) are visible by the correctly updated IServiceProvider (through the IServiceCollection.BuildServiceProvider) and are correctly found by the system through DI, but the infrastructure it instantiates the Controllers can only see the services added up to the startup (IHostBuilder.Build).
This limitation is not understandable also we cannot find a way to update these services, even if we set the instance in the application (through IApplicationBuilder.ApplicationServices before the Build) it is not used for the Controllers.
;(

---
#### Feedback Bot on 7/7/2021, 00:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidfowl** [comment]
The DI container is immutable, it doesn't do anything to assign it to `IApplicationBuilder.ApplicationServices`
