### ISSUE TITLE
Asp net 5, unable to reset ComponentFactory cache with wrong/old DI instance

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34246]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Asp-net-5-unable-to-reset-ComponentFact/1464807)._

---
More days lost in solving absurd problems.
This time it is not clear why the cache of the razor components has been so armored so as not to find any solution to be able to reset it!
Specifically, we have big problems with the AuthorizationView component that uses the IAthorizationPolicyProvider inject which can no longer be updated with the new added providers (ApplicationPart) correctly present in the DI.
In practice, if you start rendering any page and then add other AddPolicy they will no longer be visible from the AuthorizationView component, while they are correctly visible in the DI (through GetService).
The joke of all this is that it was enough to reset the cache using an elusive HotReloadManager, or extend the component to replace the property in AuthorizationView.AthorizationPolicyProvider which, however, was cleverly made private!
In short, a lot of wasted time, in the end we had to opt to recreate our AuthorizationView component identical to the original one (github) by replacing the injected property with another one obtained from the DI (GetService).
My humble advice is to never set private variables when the class / component is inheritable. Better still, it would be to make the HotReloadManager class already managed in the framework usable.
Thanks ;(

---
#### Feedback Bot on 7/1/2021, 01:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/1/2021, 02:59 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by HaoK** [comment]
Updating policies dynamically generally can be supported via a custom IAuthorizationPolicyProvider, did you try that as well?
