### ISSUE TITLE
Core 3.1 Scaffolded Identity says email when actually using username on generated Login code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34245]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Core-31-Scaffolded-Identity-says-email-/1469913)._

---
[severity:It bothers me. A fix would be nice]
This is generated by creating a new project with no authentication and then doing the scaffolding to add identity. Visual Studio V16.10.3

In the new Login.cshtml.cs, the generated code uses Input.Email as a parameter to _signInManager.PasswordSignInAsync when that parameter is supposed to be the username. This code works only because the generated Register.cshtml.cs puts the email as both the username and the email. Any modification that has actual username will fail. Anyone trying to log in with an email and a different user name will fail. 

I submit this to document the issue and provide a workaround.

Generated code:
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ScaffoldingError.Areas.Identity.Data;

namespace ScaffoldingError.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly UserManager<ScaffoldingErrorUser> _userManager;
        private readonly SignInManager<ScaffoldingErrorUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

public LoginModel(SignInManager<ScaffoldingErrorUser> signInManager, 
            ILogger<LoginModel> logger,
            UserManager<ScaffoldingErrorUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

[BindProperty]
        public InputModel Input { get; set; }

public IList<AuthenticationScheme> ExternalLogins { get; set; }

public string ReturnUrl { get; set; }

[TempData]
        public string ErrorMessage { get; set; }

public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

[Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

[Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string. IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string. Empty, ErrorMessage);
            }

returnUrl ?? = Url.Content("~/");

// Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()). ToList();

ReturnUrl = returnUrl;
        }

public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ?? = Url.Content("~/");

ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()). ToList();
        
if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result. Succeeded)
                {
                    _logger. LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result. RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result. IsLockedOut)
                {
                    _logger. LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string. Empty, "Invalid login attempt.");
                    return Page();
                }
            }

// If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

Once I realized what the problem was, I modified the code adding try catch and email lookup as:

public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ?? = Url.Content("~/");

if (ModelState.IsValid)
            {
                try {
                    OnboardingUser tUser = null;
                    tUser = await _userManager.FindByEmailAsync(Input.Email);  // <<<< this can throw an exception

if (tUser != null)
                    {

// This doesn't count login failures towards account lockout
                        // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                        // the scaffolded version has PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                        // however, the first parameter is not the email address, but the user name. This works only because the default registration puts email in both fields

var result = await _signInManager.PasswordSignInAsync(tUser, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                        if (result. Succeeded)
                        {
                            _logger. LogInformation("User logged in.");
                            return LocalRedirect(returnUrl);
                        }
                        if (result. RequiresTwoFactor)
                        {
                            return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                        }
                        if (result. IsLockedOut)
                        {
                            _logger. LogWarning("User account locked out.");
                            return RedirectToPage("./Lockout");
                        }
                        else
                        {
                            ModelState.AddModelError(string. Empty, "Invalid login attempt.");
                            return Page();
                        }
                    }
                }
                catch (Exception Ex)
                {
                    ModelState.AddModelError(string. Empty, "Invalid login attempt.");
                }
            }

// If we got this far, something failed, redisplay form
            return Page();

}

---
#### Feedback Bot on 7/8/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/8/2021, 03:05 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
This is by design. Templates treat the email address as the username, and keep things in sync. If you've edited the scaffolded code in the templates to change this behaviour you need to make sure you edit the code everywhere.
