### ISSUE TITLE
failed: HTTP Authentication failed; no valid credentials available when Authenticating and authorizing in ASP.NET Core SignalR

### ISSUE THREAD

**Issue by logcorner** [dotnet/aspnetcore#34258]
Hi , I'm facing the following error when authenticating asp.net 5 signalr hub using angular following the document here https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1#bearer-token-authentication
![token](https://user-images.githubusercontent.com/5066547/125170688-59adfb00-e1b0-11eb-902d-b04c6e15503a.png)

![token2](https://user-images.githubusercontent.com/5066547/125170909-a0502500-e1b1-11eb-9e6b-57807d7b2ea7.png)

**Hub Server**
```
       services.AddAuthentication(options =>
       {
            // Identity made Cookie authentication the default.
            // However, we want JWT Bearer Auth to be the default.
            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        })
       .AddJwtBearer(o =>
       {
           // Configure the Authority to the expected value for your authentication provider
           // This ensures the token is appropriately validated
           o.Authority = $"https://login.microsoftonline.com/[tenantID]/v2.0";
           o.Audience = "a7d63b4a-57b0-433d-a6db-27c6bd058af0";
           o.TokenValidationParameters.ValidateIssuer = true;
           o.TokenValidationParameters.ValidIssuer = $"https://login.microsoftonline.com/[tenantID]/v2.0";
           o.RequireHttpsMetadata = true;
           o.IncludeErrorDetails = true;
           o.ClaimsIssuer = $"https://login.microsoftonline.com/[tenantID]/v2.0";
           o.MetadataAddress = $"https://login.microsoftonline.com/[tenantID]/v2.0/.well-known/openid-configuration";

           o.TokenValidationParameters.ValidateIssuerSigningKey = true;

           o.Events = new JwtBearerEvents
           {
               OnMessageReceived = context =>
               {
                   var accessToken = context.Request.Query["access_token"];

                   // If the request is for our hub...
                   var path = context.HttpContext.Request.Path;
                   if (!string.IsNullOrEmpty(accessToken) &&
                       (path.StartsWithSegments("/logcornerhub")))
                   {
                       // Read the token out of the query string
                       context.Token = accessToken;
                   }
                   return Task.CompletedTask;
               }
           };
       });
```

**Angular side** 
```
let scopes =['https://datasynchrob2c.onmicrosoft.com/signalr/hub/event-notifier'];
     this.authService.getAccessToken(scopes).
      then((res: AuthResponse) => {
        console.log('**SignalRService::createConnection2 :accessToken',res.accessToken);
        this._hubConnection = new HubConnectionBuilder()
        .withUrl(this._hubUrl,{ 
          accessTokenFactory: () => {
             console.log('**SignalRService::createConnection2 :accessTokenFactory',res.accessToken);
             return res.accessToken;
          },
          skipNegotiation : true,
          transport: HttpTransportType.WebSockets
          
         },
        )
        .configureLogging(LogLevel.Information).build();
        console.log('**SignalRService::createConnection2 :this._hubUrl',this._hubUrl);
        this._hubConnection.start();
      })
      .catch(error => {
        console.log('**SignalRService::createConnection2 :error',error);
      });
```

I'm using an azuread b2c tenant and i registered a web application with the following scope : https://datasynchrob2c.onmicrosoft.com/signalr/hub/event-notifier

The front is also registered and granted the scope  on api permissions

**Comment by BrennanConroy** [comment]
Can you turn on Debug logging on the server and share them?

**Comment by logcorner** [comment]
Hi @BrennanConroy , you can find the logs in attached file
The following error is throwen by the server : Microsoft.IdentityModel.Tokens.SecurityTokenUnableToValidateException: IDX10516: Signature validation failed. Unable to match key:
[logs.txt](https://github.com/dotnet/aspnetcore/files/6796383/logs.txt)

**Comment by logcorner** [comment]
The token is valid in debug mode 
![TOKEN DEBUG](https://user-images.githubusercontent.com/5066547/125208724-96ebb900-e294-11eb-9f40-6d4e1a056eea.png)

![TOKEN DEBUG_2](https://user-images.githubusercontent.com/5066547/125208815-095c9900-e295-11eb-8052-1f3adcd4fa9d.png)

But I think that the token is troncated when it is passed as query paramater : 
wss://localhost:5001/logcornerhub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJpc3MiOiJodHRwczovL2RhdGFzeW5jaHJvYjJjLmIyY2xvZ2luLmNvbS81Nzc1ZDNmYy00MjZhLTRiM2ItYTg5My05M2IxOWU5ZTZjMWMvdjIuMC8iLCJleHAiOjE2MjYwMzc1ODMsIm5iZiI6MTYyNjAzMzk4MywiYXVkIjoiYTdkNjNiNGEtNTdiMC00MzNkLWE2ZGItMjdjNmJkMDU4YWYwIiwib2lkIjoiYjYxN2NiMzEtYmE4NC00MGRmLTk5NzgtMTkyMmI3MDM3ZGE0Iiwic3ViIjoiYjYxN2NiMzEtYmE4NC00MGRmLTk5NzgtMTkyMmI3MDM3ZGE0IiwiZ2l2ZW5fbmFtZ...lMWUtNGVhNi04NmMxLWM3YjAzOTE3NzRhZiIsInNjcCI6ImV2ZW50LW5vdGlmaWVyIiwiYXpwIjoiYjJlYjExZDItZWUwNS00ODZiLTlmMmMtZTZkYWY1OTVhZWE3IiwidmVyIjoiMS4wIiwiaWF0IjoxNjI2MDMzOTgzfQ.XjkKXnoCVnO913o4iY95dmiblkExTXwi94GdbMRxdGyBC2aGYtyWwU8YDaNAVMO_FqousUjec0jWx1xGpN5_nAd6XDzW-zsUtY51gT-8ZvoQNR7ARS_BULhJx6zzfDH8gqx-quwiVB0Bod-BGpQEVlKhVnMVuX3AVNAmjR4Q_Ur3p_q4_MOLqSh4lH1jBeCB6lDMjUTTuzJ5hj6dhDpN7LszYcSvvzgjVqwPG6M9_mW3hRBjIi0Z7XQWKMJ_qIXeY1N94haJq6mc2qBHoGHgrzwx5XUdvG1p0H44o9db0-a-K8vaGfJpE7cGI6c-w9zgCbFeD8RH8ZAkhmCHiUyKSA'

![token params](https://user-images.githubusercontent.com/5066547/125208861-5f314100-e295-11eb-8670-70ab4b1326b5.png)

Why it is not possible to authenticate to signalr hub using authorization header in the same way as we did in asp.net webapi ?
core

**Comment by BrennanConroy** [comment]
> Why it is not possible to authenticate to signalr hub using authorization header in the same way as we did in asp.net webapi ?

Are you saying that the same access token works with other endpoints?

From your logs it looks like "Signature validation failed" which would imply you have an invalid token. Are you getting your token from a different resource than the server expects? Or did you mis-configure the server side to not look at the correct resource for validating?

> But I think that the token is troncated when it is passed as query paramater :

That is very unlikely, you wouldn't get signature validation errors in that case, you would more likely see failures to parse the token. I'm guessing whatever you used to look at the query string was trying to be helpful and shortened the output for viewing purposes.

**Comment by logcorner** [comment]
Hi @BrennanConroy 
**you can see here that the token send to the hub is valid**
![125208815-095c9900-e295-11eb-8052-1f3adcd4fa9d](https://user-images.githubusercontent.com/5066547/125329463-ceff0480-e345-11eb-9a9b-335f9dd0f193.png)

**Comment by BrennanConroy** [comment]
That doesn't mean it's valid, the error is "Signature validation failed" which means the validation of the **Signature** failed.

The token is well formed, but the error has nothing to do with that.

**Comment by logcorner** [comment]
> That doesn't mean it's valid, the error is "Signature validation failed" which means the validation of the **Signature** failed.
> 
> The token is well formed, but the error has nothing to do with that.

I can call a secured web api controller in the same project with the same token, so it should be issue

**Comment by BrennanConroy** [comment]
> I can call a secured web api controller in the same project with the same token, so it should be issue

Ok, that's what I was asking about.

SignalR doesn't do anything special here so I'm not sure how your controller works but the hub doesn't. Are you hitting a different auth code path with the controller? What do the Debug server logs look like for the controller endpoint with auth?

**Comment by logcorner** [comment]
Hi @BrennanConroy 
It should be related to the token I got from the angular client , I will fix it and check again
Thank you
