### ISSUE TITLE
Blazor server sub application, can not login

### ISSUE THREAD

**Issue by juchunwei** [dotnet/aspnetcore#34252]
- ASP.NET Core version: 5.0.7

1. create a new Blazor server App.  change the code `app.UsePathBase("/app");`
2. change the _Host.cshtml. `<base href="~/" />` to `<base href="~/app/" />` , and also tried '<base href="/app/" />', but seems the `<base href="~/app/" />` changed to /app/app/ in the page source code.
3. add a new application on exists IIS website
4. go to the login page, enter username and password, no errors but still shows "Login" link instead of showing the user name.

is this a bug?
Please help. 
Thanks!

**Comment by javiercn** [comment]
@juchunwei thanks for contacting us.

If you use `app.UsePathBase`, `<base href=~/` is already enough, since `~` in aspnetcore means the pathbase/virtual directory.

**Comment by juchunwei** [comment]
@mkArtakMSFT
Why this is answered? what's the answer?

**Comment by juchunwei** [comment]
@javiercn 

I've tried with `<base href="~/" />`, doesn't work.
