### ISSUE TITLE
rewrite GroupByShaperExpression to support ef core group by sql evaluation

### ISSUE THREAD

**Issue by MalwareX95** [dotnet/aspnetcore#34256]
Hi. I've noticed for a long time that this issue hasn't been solved  since release of ef core 2. Maybe now its finally a time to fix it ?  If you don't know what I'm talking about just run the ODataRoutingSample in this repo, set the ef core provider to sql server and send this request http://localhost:64771/Products?$apply=groupby((Color),aggregate($count as Count)) and you will be greet with following exception:

InvalidOperationException: Processing of the LINQ expression 'GroupByShaperExpression:
KeySelector: new GroupByWrapper{ GroupByContainer = new LastInChain{
Name = N'Color',
Value = (object)p.Color
}
}

**Comment by davidfowl** [comment]
Where's the ODataRoutingSample in this repo?

**Comment by MalwareX95** [comment]
Ah, sorry. I've reported the issue late in night and I haven't noticed that I is the wrong repo. I wanted to report the issue here https://github.com/OData/AspNetCoreOData. Thanks David for pointing this out.
