### ISSUE TITLE
Unable to use WebAssembly.Authorization with AWS cognito 

### ISSUE THREAD

**Issue by nagtilaklaxman** [dotnet/aspnetcore#34263]
Blazor webassembly authentication with AWS cognito fails with 400 status.

In network i can see the   **x-frame-options: DENY**
Any way to solve this issue and implement the cognito in blazor.

![localhost_5001_authentication_login-callback_code=1d699b13-8a03-4e07-8923-2f6769431b25 state=d4d0a83b824d453784de912141d355c0](https://user-images.githubusercontent.com/16507190/125189202-3c456380-e27a-11eb-9ed8-0e20c2fc3737.png)

**Comment by blowdart** [comment]
What do the logs say when you try to login? Are you using Blazor Client or Server to perform the login?

**Comment by nagtilaklaxman** [comment]
I am using Blazor Client  to perform login.
I am unable to see the logs on cognito.
options.ProviderOptions.ResponseType = "code";
it is not working.

I have tried changing Authorzation flow to implicit flow but still it is not working.
options.ProviderOptions.ResponseType = "token";

in implicit flow everything works but application don't go further after authentication.
![localhost_5001_authentication_login-callback](https://user-images.githubusercontent.com/16507190/125233541-1ffd0180-e322-11eb-9522-3c2352bf4d00.png)

**Comment by nagtilaklaxman** [comment]
Found the problem.
It was the setting at cognito pool.
By mistake client was generated using client secret.
Created new client without secret it is working fine.
