### ISSUE TITLE
 Redirect to custom URL after sign-in with Microsoft Identity Platform

### ISSUE THREAD

**Issue by satishrabari** [dotnet/aspnetcore#34274]
Hi, Would you please help me with the following things?
I am using Microsoft Identity Platform.
I want to redirect to account/logincallback URL after successful login.
Where I put the redirect URL for this?

I want to configure using startup.cs because I want to save user info in DB and add custom claims in the claim principle.
Is it possible?
I don't have a login URL on my web.

following is my Startup.cs
` 

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
            services.AddRazorPages()
                 .AddMicrosoftIdentityUI();
       

`

_Originally posted by @satishrabari in https://github.com/dotnet/aspnetcore/issues/24167#issuecomment-877991903_

**Comment by satishrabari** [comment]
Thanks @blowdart 
I used **IClaimsTransformation** but I called the database on every Authorize request and it's not properly to call the database on every authorized request.
Would you please help in Microsoft Identity Platform redirect URL using Startup.cs?

**Comment by blowdart** [comment]
That shouldn't happen with claims transformation. @HaoK it should only run when a new principal is created right?

**Comment by satishrabari** [comment]
Please check the following code for IClaimsTransformation.
I tested its calling on every authorized request.
```
//IClaimsTransformation custom implement
public class CustomClaimsTransformer : IClaimsTransformation
    {
        public ILogger<CustomClaimsTransformer> _logger { get; set; }
        private readonly IUserRepository _userRepository;
        private IWebHostEnvironment _env;
        public CustomClaimsTransformer(ILogger<CustomClaimsTransformer> logger, IWebHostEnvironment env, IUserRepository userRepository)
        {
            _logger = logger;
            _env = env;
            _userRepository = userRepository;
        }
        public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            //This sample will automatically apply the Admin role to the user
            //In the real app, I will check the user against my DB and apply all roles (as claims) here
            // Remove Win AD role claims
            var claimsIdentity = (ClaimsIdentity)principal.Identity;
            var user = await _userRepository.GetByEmailAsync(claimsIdentity.Name);
            
            if (user != null && user.Enabled)
            {
                var roles = await _userRepository.GetUserRolesAsync(user.Id);
                var locations = await _userRepository.GetLocationByUserIdAsync(user.Id);
                claimsIdentity.AddClaim(new Claim("user_id", user.Id));
                claimsIdentity.AddClaim(new Claim("user_name", user.UserName));
                if (!string.IsNullOrWhiteSpace(user.ProviderDisplayName))
                {
                    claimsIdentity.AddClaim(new Claim("display_name", user.ProviderDisplayName));
                }
                else
                {
                    var displayName = claimsIdentity.Claims.FirstOrDefault(s => s.Type == "name");
                    if (displayName!=null)
                    {
                        claimsIdentity.AddClaim(new Claim("display_name", claimsIdentity.Claims.FirstOrDefault(s => s.Type == "name").Value));
                    }
                }
                claimsIdentity.AddClaim(new Claim("email", user.Email));
                foreach (var location in locations)
                {
                    claimsIdentity.AddClaim(new Claim("location", location.Name));
                }
                _logger.LogDebug($"Added location claim.");
                foreach (var role in roles)
                {
                    claimsIdentity.AddClaim(new Claim(claimsIdentity.RoleClaimType, role.Name));
                }
                _logger.LogDebug($"Added role claim.");
            }
            return principal;
        }
    }
```

**Comment by HaoK** [comment]
Yes but when that cookie is created is depending on settings like the cookie expiration settings and other things, can we see the startup/configuration of the service collection/options?

**Comment by satishrabari** [comment]
Yes sure ,
Following is my Startup.cs

        
```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));

        services.AddControllersWithViews(options =>
        {
            var policy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .Build();
            options.Filters.Add(new AuthorizeFilter(policy));
        });
        services.AddRazorPages()
             .AddMicrosoftIdentityUI();

```

**Comment by HaoK** [comment]
Where are you adding your custom claims transformer then?

**Comment by satishrabari** [comment]
I update comment @HaoK

**Comment by HaoK** [comment]
Okay I was mistaken, claimstransformation is run every time authenticate is called, so this behavior is correct:

See:

https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/Authentication.Core/src/AuthenticationService.cs#L95

I this makes sense as its going to run on any identity that comes out of authenticate, but it doesn't affect the persisted data for the auth scheme.  cc @blowdart

**Comment by blowdart** [comment]
Ah of course, I'm an idiot.

Ok, with the bare `OpenIDConnect` service you would do it inside the `OnTokenValidated` event in options. You can do much the same with IdentityWeb

```
services.Configure<MicrosoftIdentityOptions>(options =>
{
   options.Events = new OpenIdConnectEvents
   {
      OnTokenValidated = async ctx =>
      { 
        // Add your supplemental claims here 

        // You can get a DB context like this
        var db = ctx.HttpContext.RequestServices.GetRequiredService<Roles DbContext>();

        var claims = new List<Claim>
        {
            /// Create your extra claims
            new Claim(...)
        };
        var appIdentity = new ClaimsIdentity(claims);

        ctx.Principal.AddIdentity(identity);
      }
   };
});
services.AddMicrosoftIdentityWebAppAuthentication(Configuration);

```

**Comment by blowdart** [comment]
I should tag @jennyf19 to make sure I'm telling the truth

**Comment by jennyf19** [comment]
@blowdart That looks right. We have this [example](https://github.com/AzureAD/microsoft-identity-web/wiki/customization#how-to-query-microsoft-graph-on-token-validated), @satishrabari would replace the processing of the overage from Graph with something else. It needs to be chained correctly with `previousOnTokenValidatedHandler(context)`

**Comment by satishrabari** [comment]
Thank you so much.
@blowdart, @jennyf19, and @HaoK
