### ISSUE TITLE
Problems redirecting to both HTTPS and WWW

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#34287]
### Problem Description

I have a Razor Pages website that uses .NET 5.0, and I'm having trouble implementing redirection to both HTTPS and WWW.

### To Reproduce
Out of the box, the startup code looks something like this:

```cs
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseStatusCodePagesWithReExecute("/ErrorCode", "?code={0}");
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseStaticFiles();

    app.UseRouting();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapRazorPages();
    });
}
```

If I enter *www.insiderarticles.com* or *http://www.insiderarticles.com* in my browser, it correctly redirects to an HTTPS URL.

However, if I enter *insiderarticles.com* or *http://insiderarticles.com*, it fails to load the page.

So I replaced the call to `app.UseHttpsRedirection()` with the following:

```cs
// Redirect to HTTPS and www prefix
RewriteOptions options = new RewriteOptions()
    .AddRedirectToHttpsPermanent()
    .AddRedirectToWwwPermanent();
app.UseRewriter(options);
```

This seems better in some cases. It's a little hard to test since, once the browser has found the correct site, it seems to find it okay. But a fresh browser install still has the issue.

But if I enter *http://insiderarticles.com* into [Redirect Checker](https://www.redirect-checker.org/index.php), it still shows a 404 response.

I can't tell if I'm doing something wrong or these options aren't working right.

### Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 16.10.3

Additional details can be found in this [Stackoverflow question](https://stackoverflow.com/questions/68338435/website-not-redirecting-to-www-version-of-my-url).

**Comment by Tratcher** [comment]
Check your site bindings, it doesn't look like you have `insiderarticles.com` registered in IIS so the request doesn't even reach your app. That's implied by the server header `Microsoft-HTTPAPI/2.0`, which would normally say IIS.

**Comment by SoftCircuits** [comment]
> Check your site bindings, it doesn't look like you have `insiderarticles.com` registered in IIS so the request doesn't even reach your app. That's implied by the server header `Microsoft-HTTPAPI/2.0`, which would normally say IIS.

I'm not an expert at this part, but it looks right to me.

![ovxIV](https://user-images.githubusercontent.com/3191331/125352400-70726000-e31e-11eb-8f25-75efdf8d2d08.png)

**Comment by Tratcher** [comment]
those are "https" bindings, you also need some for "http" on port 80.

**Comment by SoftCircuits** [comment]
> those are "https" bindings, you also need some for "http" on port 80.

Yes! Thank you.

Can I just ask if `RewriteOptions` like I'm using it is the preferred way to redirect in my case?

**Comment by Tratcher** [comment]
> Can I just ask if `RewriteOptions` like I'm using it is the preferred way to redirect in my case?

It's the most viable option if you want to combine the www and the https redirects.
