### ISSUE TITLE
Request for .NET Standard 2.0 (or 2.1) version of Microsoft.AspNetCore.Components.WebView

### ISSUE THREAD

**Issue by visose** [dotnet/aspnetcore#34289]
### Is your feature request related to a problem? Please describe.

We are currently testing an embed Chromium webview inside a Unity 3D application to develop the UI of a 3D desktop application. SPAs like React work well, but requires interop between the Javascript UI code and Unity's C# API. We would like to use Blazor so that we can write the UI code in C# and run it using Unity's .NET runtime. This way we can call Unity's C# API directly from the UI code without the need of interop.

The main problem is that Unity is currently only compatible with .NET Standard 2.0 (soon with .NET Standard 2.1), but compatibility with NET 6.0 might be a long way away.

### Describe the solution you'd like
A .NET Standard 2.0 or 2.1 compatible version of the Microsoft.AspNetCore.Components.WebView or alternative solution to this.

### Additional context
To clarify, this is a webview embed inside Unity (Unity is the host application), as opposed to Unity embed inside a browser or similar. Specifically we are trying out this webview (has support for C#/JavaScript interop): https://store.vuplex.com/webview/windows-mac

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we can do due to dependencies we've taken in .NET 6.

**Comment by visose** [comment]
Ok, thank you for the reply. The preferred solution is really for Unity to try to keep up with the latest .NET, but there's an even less chance there.
