### ISSUE TITLE
FileLoggerProcessorTests.RollsTextFiles

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#34284]
## Failing Test(s)

Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.RollsTextFiles

## Error Message
```text
   Assert.Equal() Failure
          â†“ (pos 0)
Expected: Message two\n
Actual:   
          â†‘ (pos 0)
  Stack Trace:
     at Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.RollsTextFiles() in /_/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs:line 117
```
https://github.com/dotnet/aspnetcore/blob/69eb4b38bca90bb830f290a6eaa5a61650dc87ac/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs#L117
## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1231336&view=ms.vss-test-web.build-test-results-tab&runId=36670362&resultId=110218&paneView=debug
(Alpine.312.Amd64.Open)Ubuntu.1804.Amd64.Open

**Comment by wtgodbe** [comment]
Interesting, the file exists but was empty. Not one I ever saw during development - I can take a look after feature work is done

**Comment by HaoK** [comment]
Doesn't look like this has happened recently, 30 day clean run, should we just reenable this so we can see if/when it fails again?

**Comment by HaoK** [comment]
![image](https://user-images.githubusercontent.com/6537861/144652971-2262a84f-f335-490b-a660-514d9ddc7891.png)

**Comment by wtgodbe** [comment]
Yeah, should be fine to unquarantine - we had a community PR to improve these tests a while back
