### ISSUE TITLE
Cannot use same razor page for two adress

### ISSUE THREAD

**Issue by enricoe73** [dotnet/aspnetcore#34305]
I what to use the same razor page in more than one Url :  I have the page **/one** and I want to reach also with **/two** and **/three**

I can do it with the **AddPageRoute**  : 

```
options.Conventions.AddPageRoute("/one", "two");
options.Conventions.AddPageRoute("/one", "three"); 
```

But the taghelpers in the page (asp-page-handler) always render  **formaction="/Three?handler=Update"** pointing to the last route. 

This make impossible use the same razor page in different position in my web application.

Git sample : https://github.com/enricoe73/OnePage2Routes.git

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
