### ISSUE TITLE
Multiple root components should start in parallel

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34306]
Currently, if you have multiple root components, the host builders wait for each one to become quiescent before they add the next one. This doesn't seem at all like what anyone would want.

Since virtually everyone has only one root component in 5.0, and are likely to have multiple in 6.0 with the head component work, we should try to fix this ASAP.

This applies to all three hosting models.

**Comment by MackinnonBuck** [comment]
Done in #34634
