### ISSUE TITLE
Support binding to IFormFile in minimal routing APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#34303]
### Is your feature request related to a problem? Please describe.
Today we don't have any native support for binding to IFormFiles as part of the incoming request. This is convenient for applications that want to do file uploads.

### Describe the solution you'd like

```C#
app.MapGet("/upload", async (IFormFile file) =>
{
    var uploads = Path.Combine(uploadsPath, file.FileName);
    using var fileStream = File.OpenWrite(uploads);
    using var uploadStream = file.OpenReadStream();
    await uploadStream.CopyToAsync(fileStream);
});
```

### Additional context
- Should we support IFormFileCollection?
- Would we do matching by name? (yes)

Without this, it will look like this:

```C#
app.MapGet("/upload", async (HttpRequest req) =>
{
    if (!req.HasFormContentType)
    {
        return Results.BadRequest();
    }

    var form = await req.ReadFormAsync();
    var file = form.Files["file"];

    if (file is null)
    {
        return Results.BadRequest();
    }

    var uploads = Path.Combine(uploadsPath, file.FileName);
    using var fileStream = File.OpenWrite(uploads);
    using var uploadStream = file.OpenReadStream();
    await uploadStream.CopyToAsync(fileStream);

    return Results.NoContent();
});
```

**Comment by jchannon** [comment]
The below API would be good too, to handle more than one file at a time.
```
app.MapGet("/upload", async (IEnumerable<IFormFile> files) =>
{
    //process the files 
});
```

**Comment by bradygaster** [comment]
I worked this up today in my side-by-side comparison solution and was sad to come across this feature parity gap. 

Whilst this works fine with Web API:

```csharp
[HttpPost]
[Route("/upload")]
public async Task UploadFile(IFormFile file, CancellationToken token)
{
    using (var stream = System.IO.File.OpenWrite("upload.txt"))
    {
        await file.CopyToAsync(stream);
    }
}
```

A similar approach fails to work in minimal API: 

```csharp
app.MapPost("/upload", async(IFormFile file, CancellationToken token) =>
{
    using (var stream = System.IO.File.OpenWrite("upload.txt"))
    {
        await file.CopyToAsync(stream);
    }
});
```

I'd like to see how we get to party. Or maybe add an analyzer when folks do this to provide guidance to the alternative approach in this issue.

**Comment by davidfowl** [comment]
> The below API would be good too, to handle more than one file at a time.

@jchannon We would support `IFormFileCollection`. 

The other thing missing here is `[FromFile("name")]` for completeness we'd want to add metadata to let you specify the name of the file entry.

The other piece of work is updating the API explorer to set the right request content type if we support file upload.

**Comment by martincostello** [comment]
Would it also make sense to support `IFormCollection` here too (via `ReadFormAsync()` on the request), with `IFormFile` and `IFormFileCollection` being "specialisms" of that support?

**Comment by martincostello** [comment]
I've put up a draft to try and get this working in #35158.

**Comment by davidfowl** [comment]
We didn't do forks because we haven't thought the CSRF/Antiforgery features

**Comment by davidfowl** [comment]
@halter73 This is done right?

**Comment by martincostello** [comment]
@davidfowl Yep PR was merged a few weeks ago. I was going to do some E2E validation on it with Swagger to check it over, but the installer repo's been a bit sad over the last few weeks ingesting the SDK for 7.
