### ISSUE TITLE
Is the EndpointDataSource a good fit for routing in a CMS

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#34316]
Given that I have all urls stored in the database, including the controller type and action. My current implementation is using `DynamicRouteValueTransformer` but I am curious about the EndpointDataSource and if the purpose of it could be to store all my urls, controller types and action as a map for all incoming requests and send them directly to the correct controller and action based on the information stored in my database. Is the `EndpointDataSource` a good fit for that purpose?

**Comment by javiercn** [comment]
@marcuslindblom thanks for contacting us.

What you are describing is exactly how non-dynamic routes work, we build a "giant" table of all the possible paths and map them to the individual endpoint handling it.

You can do something similar provided you know all the paths and are able to map them to the correct endpoint when the app starts. If you need to reload the routes (because something changed on your DB) there is an IChangeToken you can invoke to trigger recomputing the route table.

Keep in mind however, that that is an expensive process and not something to be done frequently.

**Comment by marcuslindblom** [comment]
@javiercn Ok, do you have an example on how to add one endpoint to a datasource, with a know url, controller and action?

I tried this code but it does not run the controller, it ends up doing nothing?

```

var endpoints = new List<RouteEndpoint>();

endpoints.Add(new RouteEndpoint(
    requestDelegate: context => Task.CompletedTask,
    routePattern: RoutePatternFactory.Parse($"/blog"),
    order: 0,
    metadata: new EndpointMetadataCollection(new HttpMethodMetadata(new[] { "GET" }),
        new ControllerActionDescriptor() {
            RouteValues = new Dictionary<string, string>() {
                { "controller", "Home" },
                { "action", "Index" }}
    ),
    displayName: "id"));

```

**Comment by marcuslindblom** [comment]
@javiercn It would be real helpful if you could give me a working example 👆🏻

**Comment by davidfowl** [comment]
There's no API to do this other than using `DynamicRouteValueTransformer`. Only MVC knows how to create MVC endpoints. That's not exposed to you as a developer.

**Comment by marcuslindblom** [comment]
@davidfowl Hm ok, I thought it was suggested to create my own [`EndpointDataSource`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#guidance-for-library-authors)? Any plans on making this possible for developers?

**Comment by javiercn** [comment]
@marcuslindblom you would not do that though an endpoint data source.

You would do it through an `IApplicationModelProvider` or similar where you can define the things that will ultimately become endpoints.

**Comment by marcuslindblom** [comment]
@javiercn is that to recommend over `DynamicRouteValueTransformer`? If so, can you provide me with some sample code for that purpose?

**Comment by javiercn** [comment]
@marcuslindblom depends on what you are trying to achieve,

If you want to compute a static list of endpoints based on the DB, that's the way to go, if you want to decide the endpoint that matches at runtime, DynamicRouteValueTransformer is the approach.

In essence:
* ApplicationModelProvider -> You define each endpoint ahead of time when the app starts and create a static routing table (and optionally reload them periodically).
* DynamicRouteValueTransformer -> You map a single endpoint and decide on a per request basis what controller/action handles the request.

For samples/docs look at: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-5.0#custom-routing-convention

**Comment by marcuslindblom** [comment]
@javiercn Ok, I see.

So if I stick with `DynamicRouteValueTransformer`, where and how can I implement the link generation? The goal is to make the built in tag helpers to work when I provide the necessary route data. Before endpoint routing I used `IRouter.GetVirtualPath` but I can see that a lot of people seeks and answer to what we can use instead?

**Comment by javiercn** [comment]
@marcuslindblom we don't have a story around that at the moment.

This is something we are trying to add in this release, but it might at this point not make it.

If you need link generation to work with tag helpers, then your only path forward is the ApplicationModelProvider

**Comment by marcuslindblom** [comment]
@javiercn Ok, I understand.

Looking at the documentation for `ApplicationModelProvider`, all I see I see is an iteration over what I believe is controllers. Where can I say "for this url /blog/article-1, use the PostController with action Index". Given that I have 500 URLs in my database, I wish to iterate through those and create "endpoints".

**Comment by davidfowl** [comment]
@javiercn isn't that gonna blow up the route table and potentially cause memory issues?

**Comment by javiercn** [comment]
When the routes  are literals that's not a problem, specially with the optimization that I implemented recently.

**Comment by marcuslindblom** [comment]
@javiercn a good example would be awesome 👍🏻
