### ISSUE TITLE
Using Antiforgery in ASP.NET Core 3.1 with docker got error - the antiforgery token could not be decrypted

### ISSUE THREAD

**Issue by cuongvu0203** [dotnet/aspnetcore#34325]
### Describe the bug
My ASP.Net Core MVC application have added Antiforgery middleware like below:

### Startup.cs

> services.AddHttpContextAccessor();
services.Configure<Connections>(Configuration.GetSection("Connections"));
services.Configure<SettingStatics>(Configuration.GetSection("SettingStatics"));
services.Configure<RabbitOptions>(Configuration.GetSection("Rabbit"));
services.Configure<ApiSettings>(Configuration.GetSection("ApiSettings"));
var redisKey = ConnectionMultiplexer.Connect(Configuration["PersistKey"]);
services.AddDataProtection().AddKeyManagementOptions(options =>
{
    options.AutoGenerateKeys = true;
}).SetApplicationName("Fler").PersistKeysToStackExchangeRedis(redisKey, "Fler.DataProtectionKeys");        services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
{
    options.Cookie.Name = "qiflersui";
    options.Cookie.HttpOnly = true;
    options.SlidingExpiration = true;
    options.AccessDeniedPath = "/accessdenied.html";
    options.Cookie.SecurePolicy = CookieSecurePolicy.None;
    options.ExpireTimeSpan = TimeSpan.FromHours(24);
});
services.AddDistributeLogService(option =>
{
    var loggingSettings = Configuration.GetSection("LoggingSettings").Get<LoggingSettings>();
    option.ApplicationId = loggingSettings.ApplicationId;
    option.BaseUrl = loggingSettings.BaseUrl;
    option.FilterLogLevels.AddRange(new List<LogLevel>() { LogLevel.Trace, LogLevel.None, LogLevel.Warning, LogLevel.Error });
});
services.AddRedisCacheService(option =>
{
    var redisSettings = Configuration.GetSection("RedisSettings").Get<RedisSettings>();
    option.InstanceName = redisSettings.InstanceName;
    option.Configuration = redisSettings.Configuration;
});
services.AddSingleton<IZipHelper, GZipHelper>();
services.AddSingleton<RedisCacheService>();
services.AddSingleton<MemoryCacheService>();
services.AddSingleton<IBackgroundTaskQueue, BackgroundTaskQueue>();
services.AddSingleton<ITS_DOT_TUYEN_SINHData, TS_DOT_TUYEN_SINHData>();
services.AddResponseCompression(options => options.Providers.Add<GzipCompressionProvider>());
services.Configure<WebEncoderOptions>(webEncoderOptions => webEncoderOptions.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All));
services.AddSingleton<IMessageQueueService, RabbitmqService>();
services.AddControllersWithViews();
services.AddControllers();
services.AddWkhtmltopdf();

I've added below in the view 
`<form method="post" asp-route-returnurl="@ViewData["ReturnUrl"]" asp-antiforgery="false" id="login-form" autocomplete='off'>
@Html.AntiForgeryToken()`

### Exceptions Log
14/07/2021 09:42:12 - Error - Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery [ 7 - TokenDeserializeException ] Error: An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {b7efb999-49b8-4bff-933f-16d746d879a0} was not found in the key ring. at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData) at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken) --- End of inner exception stack trace --- at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken) at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

So what i wrong in my config or how to fix it? thank you

**Comment by blowdart** [comment]
- When does this happen? Immediately? After some time?
- What is your hosting environment? IIS? Kestrel? Azure? A container of some sort?
- Do you have multiple instances running?
- How is your redis instance configured? Is it persistent? 
- Is there any logs from data protection in the console logs?

**Comment by cuongvu0203** [comment]
> * When does this happen? Immediately? After some time?
> * What is your hosting environment? IIS? Kestrel? Azure? A container of some sort?
> * Do you have multiple instances running?
> * How is your redis instance configured? Is it persistent?
> * Is there any logs from data protection in the console logs?

Thank for asking!
* When does this happen? i think immediately, because after docker  build success i got this error
* What is your hosting environment? i using docker 
* Do you have multiple instances running? yes
* How is your redis instance configured? i don't know what u mean??
* Is there any logs from data protection in the console logs? this is my log
* And one more thing, if i deploy in IIS i don't get this error
![image](https://user-images.githubusercontent.com/70251952/125714081-d7f5c98f-bc87-43d9-b753-bd50d1e26183.png)
![image](https://user-images.githubusercontent.com/70251952/125714124-5718e6d3-a3b8-4c0d-8e2f-728fb739b987.png)

**Comment by blowdart** [comment]
What happens if you just start one docker instance and try?
