### ISSUE TITLE
Formatting @code block C# with extra block syntax can break formatting

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#34320]
![wscfCyk7vp](https://user-images.githubusercontent.com/2008729/125536216-3f6c39b3-b183-46d0-b396-552c5da56fd7.gif)

/cc @davidwengier

**Comment by davidwengier** [comment]
This is interesting... so in general the C# formatter just bails on collection and object initializers and does nothing, which means I'm not sure this is possible to fix.. but also this is actively _breaking_ formatting which means the formatter is doing something, which is surprising.

eg. putting that same code in a C# file and formatting the document:
![FormatCollectionInitializer](https://user-images.githubusercontent.com/754264/126101260-041e3db0-e886-4d05-bed5-a6aeaa07cbeb.gif)

**Comment by davidwengier** [comment]
Also reported here: https://developercommunity.visualstudio.com/t/Editors-automatic-formatting-does-not-p/1481367

**Comment by libu1129** [comment]
i have the same problem..   ;(
