### ISSUE TITLE
Tooling sees a random subset of Razor components as types

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34333]
I have three components in my `Pages` folder: `Index`, `Counter`, and `FetchData` (no surprise)

Yet autocomplete in `Program.cs` only offers `FetchData` for some reason:

![image](https://user-images.githubusercontent.com/1101362/125601667-3238630c-56b1-4bee-aaea-2a229613cec8.png)

If I do choose `FetchData` then tooling is happy:

![image](https://user-images.githubusercontent.com/1101362/125601728-ba281d59-a135-4cd6-a326-3263c9f84d29.png)

... but if I manually type `Counter` then VS doesn't believe me:

![image](https://user-images.githubusercontent.com/1101362/125601785-a1cf36d7-7ac6-4457-aac5-78496730d257.png)

... even though the compiler is totally cool with it:

![image](https://user-images.githubusercontent.com/1101362/125601830-4a585a10-f99b-4bef-bdf7-1796dc621f26.png)

This is based on working within the `aspnetcore` repo using VS 17.0.0 Preview 3.0 [31513.29.main].

I know the `aspnetcore` repo might be a special case, but is there any risk that similar issues could occur in customer projects?

**Comment by pranavkm** [comment]
Do you happen to have only the FetchData.razor open in VS?

**Comment by SteveSandersonMS** [comment]
Unfortunately I don't know the answer to that any more. I've opened and closed lots of files since then, and the tooling is now showing all three component types there. If I see this again I'll try to post an answer to that. Of course it's still a bug either way.

**Comment by pranavkm** [comment]
AspNetCore turns off the source generators in VS, This was a stop-gap to continue building 6.0 apps in VS 16.11 with a 6.0 SDK ( it's an unsupported combination). It might have spooky results like this that we wouldn't normally expect in a regular user's projects.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen do you know why this would be happening?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you know why this would be happening?

No, I can't reproduce in official apps either (outside of aspnetcore).

@pranavkm is it possible that in the aspnetcore repo RSG's aren't disabled in the IDE? I could imagine them running potentially resulting in something like this

**Comment by mkArtakMSFT** [comment]
This seems to be resolved now as neither @NTaylorMullen  nor @SteveSandersonMS can't reproduce this any more. There is another issue here, which we're going to fix in RC1: https://github.com/dotnet/aspnetcore/issues/33536
