### ISSUE TITLE
Allow separation of dependencies and request parameters in "minimalistic" request handlers

### ISSUE THREAD

**Issue by amoerie** [dotnet/aspnetcore#34331]
## Background and Motivation

Context: @DamianEdwards tweeted about the upcoming minimalistic API in .NET 6, and one of his code samples struck me as a little odd:

```csharp
app.MapGet("/todos/{id}", async (int id, SqliteConnection db) => 
  await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
    ? Results.Ok(todo)
    : Results.NotFound());
```

More specifically, what I found a bit odd is that SqliteConnection is sitting right next to "int id", while one is a request parameter coming in via the URL / Query String / Request Body, the other is a registered dependency in the service collection.

I realize that we already have this exact pattern in MVC today, it would probably look a bit like this:

```csharp

[HttpGet("/todos/{id}"]
public async Task<IActionResult> GetTodoByIdAsync([FromRoute] int id, [FromServices] SqliteConnection db) {
  ... // Rest of the owl
}
```

But what I like about the above is that it is very explicit where these values are coming from, while that information is not conveyed in the minimalistic API. 

My suggestion was to make use of a curried lambda to separate these two types of parameters, so it would look like this:

```csharp
app.MapGet("/todos/{id}", (SqliteConnection db) => async (int id) => 
  await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
    ? Results.Ok(todo)
    : Results.NotFound());
```

Now, the dependencies and request parameters are once again visually separated, and it is immediately clear that the outer lambda requires things from the dependency container, while the inner lambda "model binds" from the request. 

As for invocation, it is clear that the "inner lambda" will definitely be invoked per request. Unfortunately, it is more vague when the outer lambda will be invoked. A naive implementation would invoke it for every HTTP request, which is definitely the safest option.
It might allow for optimizations though, given certain guarantees. If the outer lambda only requires singleton dependencies, and always returns the same inner lambda, then the outer lambda could effectively be called only once and then reused. But I'm probably thinking too far ahead now. 

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder
{
    public static class MinimalActionEndpointRouteBuilderExtensions
    {
+       public static MinimalActionEndpointConventionBuilder MapGet(this IEndpointRouteBuilder endpoints, string pattern, Func<Delegate, Delegate> action)
+       // Other methods ( POST, PUT, ..) omitted for brevity
    }
}
```

## Usage Examples

I suppose I'll just copy paste the earlier example here again:

```csharp
app.MapGet("/todos/{id}", (SqliteConnection db) => async (int id) => 
  await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
    ? Results.Ok(todo)
    : Results.NotFound());
```

## Alternative Designs

Alternative API shapes
-------------------------

In the non-minimalistic APIs, this problem is typically solved using either constructors or the [FromServices] attribute.
However, constructors have historically had issues, because if a controller has many endpoints, its constructor ends up consuming tens if not hundreds of dependencies, only some of which are necessary for the current endpoint.
I personally prefer the [FromServices] approach, although I'm unaware of the performance impact of this approach. 

The best alternative API is probably what already exists, i.e. just mixing dependencies and request parameters in the same list of arguments. 

Analogous APIs in other ecosystems and libraries
------------------------------------------------------

Curried lambdas definitely stem from the functional world, and while I'm not a F# aficionado, it would surprise me if they haven't been doing it this way for years already. 

## Risks

The main risk that I see is that will people will find it **more** complex instead of less, because curried lambdas are not exactly typical in C#. I fear that this complexity might be linearly opposed to the spirit of the "minimalistic" API.

Furthermore, the invocation of the outer lambda might be a bit weird. What if people start doing weird stuff when returning the inner lambda? 

```csharp
app.MapGet("/todos/{id}", (SqliteConnection db) => { 
    var random = new Random();

    if(random.Next(0, 100) > 70)
        return async (int id) => 
                    await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
                        ? Results.Ok(todo)
                        : Results.NotFound());
    }   

    return () => "Sorry, this endpoint only works 70% of the time";
});
```

**Comment by amoerie** [comment]
I wanted to post this as a separate comment, but I would also already consider it a nice improvement if the minimalistic API allowed attributes to convey the explicitness that I'm looking for.

Something like this:

```csharp
  app.MapGet("/todos/{id}", async ([FromRoute] int id, [FromServices] SqliteConnection db) => 
    await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
      ? Results.Ok(todo)
      : Results.NotFound());
```

Since C# has been leaning harder into its functional side in recent years, the curried lambda suggestion seemed more natural though.

**Comment by DamianEdwards** [comment]
Your example using attributes to be explicit is already supported in the minimal APIs I believe.

**Comment by davidfowl** [comment]
I have some good news and bad news. The good news is we can support this without API changes so it can be done at a later date. It turns out the signature isn't `Func<Delegate, Delegate>`, it's just a Delegate that happens to return a Delegate. The bad news is, 2 fold:
1. You need to be explicit about the return type of the inner function:
```C#
app.MapGet("/todos/{id}", Delegate (SqliteConnection db) => { 
    var random = new Random();

    if(random.Next(0, 100) > 70)
        return async (int id) => 
                    await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
                        ? Results.Ok(todo)
                        : Results.NotFound());
    }   

    return () => "Sorry, this endpoint only works 70% of the time";
});
```

Notice the Delegate return type. That's important.

2. I think this is more complex to grok and understand (probably if you're not a haskell or F# developer 😄). I'm not convinced it makes sense to implement it. 

That said, we'll keep it in mind as and treat it as feedback for the future. I'll also play around with an implementation to see if there are any other technical challenges.

**Comment by amoerie** [comment]
Sounds like the benefits (clear separation and conceptual correctness) are very light compared to the heavy downsides.

In that case, I think this proposal should be rejected.

P.S. for the optimizable case where the dependencies are singletons, I suppose this is already supported today like this:

```csharp
// Grab things from the dependency container in the root scope. Not sure where IServiceProvider is exactly
var db = app.ServiceProvider.GetRequiredService<SqlLiteConnection>();

// Then simply use them in the request lambdas
app.MapGet("/todos/{id}", async (int id) => 
  await db.QuerySingleOrDefaultAsync<TODO>("SELECT * FROM Todos WHERE ID = @id", new { id}) is Todo todo
      ? Results.Ok(todo)
      : Results.NotFound());
); 
```

So, to summarize:

- You can already improve explicitness by sprinkling [FromRoute] and [FromServices] on your lambda parameters, sacrificing brevity in exchange for clarity
- When your dependencies are singletons, you can already move them out of the request lambda
- Using curried lambda's, while nice on paper and appeasing the legion of functional programmers, seems to introduce a lot of complexity for little gain.
