### ISSUE TITLE
Add support for Latin1 header encoding in HttpSysServer.

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#34330]
On IIS (ANCM) : when a request contains a header such as foo:Québec, IIS decodes it as Qu�bec. (The "é" is replaced with codepoint U+FFFD). It is possible to enable Latin1 decoding using `AppContext.SetSwitch("Microsoft.AspNetCore.Server.IIS.Latin1RequestHeaders", isEnabled: true);` Please see: https://github.com/dotnet/aspnetcore/issues/22675

On Kestrel : when a request contains a header such as foo:Québec, Kestrel rejects it outright as 400.0 (Bad Request). It is possible to enable Latin1 decoding using `KestrelServerOptions.RequestHeaderEncodingSelector` property : https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.requestheaderencodingselector?view=aspnetcore-5.0

However, on HttpSysServer, the option to enable Latin1 decoding is not present.

### Describe the solution you'd like
An option to enable Latin1 request header decoding on HttpSysServer similar to Kestrel and IIS (ANCM)

**Comment by Tratcher** [comment]
Note #22675 was never merged, we did #22798 instead.

Because IIS and HttpSys share their header encoding code, we should mainly need to turn on the existing option and add tests.

**Comment by davidfowl** [comment]
Can we add an API in rc1? The app context switch is a crutch we should remove in a future release.

**Comment by Tratcher** [comment]
We opted not to add the API for IIS for just latin1 support, we wanted to wait until we implemented the full `Func<string, Encoding>` like Kestrel. Given time and resources, and that @avparuch only needs this as a stopgap before moving to Kestrel, I also recommend the AppContext approach here.

**Comment by davidfowl** [comment]
I disagree. We should not lean on the AppContext for options like this. It's only to be used for patches, not when we have time to add public properties in a major release.

**Comment by Tratcher** [comment]
So what's the API proposal, `Func<string, Encoding> RequestHeaderEncodingSelector` or `bool UseLatin1RequestHeaders`? The former is more work and functionality than currently required.

**Comment by davidfowl** [comment]
I would assume the func

**Comment by Tratcher** [comment]
Offline notes:
Add an option `bool UseLatin1RequestHeaders` instead of the AppContext switch. Consider also replacing the IIS AppContext switch with a similar option.

We'll deal with custom encodings in the future if there's demand.
