### ISSUE TITLE
WebAssembly app startup promise unintentional change of behavior on .NET 6

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34332]
Given this code:

```html
    <script src="_framework/blazor.webassembly.js" autostart=false></script>
    <script>
        Blazor.start().then(() => {
            doSomethingImportant();
        });
    </script>
```

... do you think `doSomethingImportant` runs before the initial UI render, or after it? The answer is unfortunately rather complicated.

 * In 3.2.0, it would always run *after* the initial synchronous UI render, which certainly seems like the most useful behavior (because that's what you think that "start" would mean)
 * In 5.0, it nearly always does the same as 3.2.0
   * There is one special case where it runs before the initial UI render: if `LoadCurrentCultureResourcesAsync` decides it needs to do something async. Few applications will be in that situation.
 * In 6.0, it's really messed up:
   * If you're in development (and have hot reload enabled by default), it always runs before the initial UI render
   * If you have an `IComponentApplicationStateStore` that does something async to fetch the state, then `doSomethingImportant` runs before the initial UI render
   * Otherwise it runs after the initial UI render, like 5.0 and 3.2.0

Given that this code is specifically trying to wait until the application is "started", people probably do care about whether the initial UI has rendered or not. Having a change of behavior between development and production (based on whether hot reload is on) could be a pretty unwelcome surprise.

I think we should define the behavior clearly and ensure we honour it. In particular, I think we should be retaining the 3.2.0 and (mainstream) 5.0 behavior of completing the `Blazor.start` promise only after the initial UI render.

**Comment by SteveSandersonMS** [comment]
The underlying reason, by the way, is that `Blazor.start()` is a promise that completes when the application entrypoint first yields execution. It does *not* wait for the `async Task Main` task to complete (because it never completes!).

Previously there was nothing in `WebAssemblyHost.RunAsyncCore` that would yield execution, so you would see the initial render before the promise completes. However we've added several things to `WebAssemblyHost.RunAsyncCore` that now do yield execution (e.g., `ComponentApplicationLifetime.RestoreStateAsync` and `WebAssemblyHotReload.InitializeAsync`), so when we hit any of those, the `Blazor.start()` promise completes at that point.

**Possible solutions**

 * We could redefine `Blazor.start()` as being a promise that completes at some point when .NET code is running, but with no guarantees about what stage in the app startup process we've got to.
     * This would be pretty sucky and undermine the usefulness of that API.
 * We could rejuggle the code a bit to ensure the framework never yields execution before run the first render, recreating the conditions of 3.2.0 and 5.0
     * This would be adequate to be not a breaking change. However if someone manually adds some async logic to their `Main`, then they'd be in for a surprise.
 * We could change `RunAsyncCore` so that the returned task *does* complete, and then redefine `Blazor.start()` so that it completes only after the entrypoint task completes.
     * There would be an element of change-of-behavior here too if someone on 5.0 had manually added custom async logic to `Main` and cared about when the `Blazor.start()` promise completed. However, it would at least set us up with a consistent behavioral rule for all time in the future.
 * We could define a more explicit API like `Blazor.start({ awaitFirstRender: true })`, and clarify that if you're not awaiting the first render, we don't make any promises about when the promise will complete. I don't really like this because it's just messy and nonobvious.

**If we're feeling limited on time, my preference is that at the very least, we should not have a default difference in behavior between dev and prod based on hot reload.** As long as the behavior is consistent within any given app based on its own code, people are unlikely to get burned by it and can adapt their startup logic to whatever they need.

**Comment by javiercn** [comment]
We can return a promise and trigger the completion from the .NET side of things when we want to, without relying on the original `start` promise.

Does that sound appropriate?

**Comment by pranavkm** [comment]
> Do you know of any reason why we shouldn't move the await WebAssemblyHotReload.InitializeAsync() call to later in RunAsyncCore, immediately before await initializationTcs.Task

I had hoped for it to apply before components began to render. But it (inexplicably) doesn't do that now, so I'm ok moving it around if it's complicating things.

**Comment by SteveSandersonMS** [comment]
We've discussed and realised that the intended behavior for the `Blazor.start` promise only means ".NET has started" and not "Blazor has done something specific", so there isn't a breaking change here.
