### ISSUE TITLE
Allow customizing Socket.AcceptAsync() call

### ISSUE THREAD

**Issue by kevin-montrose** [dotnet/aspnetcore#34344]
We have an application where it would useful to be able to inspect a `Socket` after it is accepted, but before any other operations happen on it, in order to determine whether we want to marshal it over to another process to handle.

Currently this is not possible because once accepted in `SocketConnectionListener`, a `Socket` is almost immediately wrapped up in a `ConnectionContext` and read from.

It is important for us to inspect a `Socket` immediately, as (on Windows) once asynchronous I/O beings moving a `Socket` to another process will fail (see [DuplicateAndClose](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.duplicateandclose?view=net-5.0)).

### Describe the solution you'd like
Ideally a new option is added to `SocketTransportOptions` which, similar to `CreateBoundListenSocket`, allows customizing this `Socket`-y operation.  <strike>I'll have a PR sketching this out up shortly.</strike> #34345

**Comment by shirhatti** [comment]
Do you mind elaborating on your use case? I'm curious on what you plan to use this for?

**Comment by kevin-montrose** [comment]
@shirhatti Currently we've got a single process which is accepting requests for multiple domains.  Because of some other constraints beyond our control, we have to keep that one process accepting everything but would like to move the connections to separate processes based on the domain the connection is for.  We may also chose to serve some portion of the requests in the existing process.

We basically want to be able to swap the `_listenSocket.AcceptAsync(...)` out for two different implementations:

 - In our existing process, we'll peek at the SNI extension in TLS ClientHello (and maybe roll some dice) and either return the socket (if we want to serve it in the existing in the process) or marshal it across to a new process
 - In the new processes, we'll be reading these marshalled sockets off of some IPC mechanism

In essence we'd be changing where the `Sockets` are coming from out from under the rest of the socket transport layer, but once they arrive everything else proceeds as normal.  There's just no way to do that currently.

**Comment by davidfowl** [comment]
We reverted this delay change. The new strategy is to make the SocketConnectionFactory available and that is what would be used along with a custom transport on both the incoming side and receiving side.
