### ISSUE TITLE
When using statically rendered Razor components, allow for async initializer to complete before rendering

### ISSUE THREAD

**Issue by mqudsi** [dotnet/aspnetcore#34352]
Currently, the Razor Component execution model assumes dynamic (server- or client-side) rendering in its handling of async initializers, e.g. given the following:

```cshtml
@inject DbContext _db;
@code {
	private IList<Categories> Categories { get; set; }

	protected override async Task OnInitializedAsync()
	{
		Categories = await _db.Categories.ToListAsync();
	}
}

<ul>
foreach (var c in Categories) {
	<li>@c.Name</li>
}
</ul>
```

The rendering of the Razor syntax, including the realization of the still-null `Categories`, takes place immediately after the call to to `OnInitializedAsync()` yields execution for the first time (e.g. after `_db.Categories.ToList()` has begun executing but before it has completed and before the result has been assigned to `Categories`).

The rationale for a dynamically Razor component makes perfect sense - the UI shouldn't be blocking and so the HTML should alternate between some sort of loading state and the actual results predicated on whether or not the async initializer has completed running.

But for a *static* razor component (`<component type="@typeof(Shared.CategoryList)" render-mode="Static" />`) this doesn't work - the component is only rendered the very first time and not revisited thereafter; if the CSHTML alternated between a loading spinner and the actual results based off of whether or not the results were ready, the loading spinner would be shown indefinitely.

In fact, for a statically-rendered component `OnInitializedAsync()` is entirely useless, as nothing it actually does will ever be seen anywhere. The compiler/runtime could, as an optimization, skip execution of any side-effect free code (like in the sample above) and it would be within its rights because it changes absolutely nothing!

Would you be open to delaying the first (and only) render call to after `OnInitializedAsync()` has completed if and only if the Razor component is being statically rendered? That would be functionally no different than a Razor view/page with the asynchronous loading code placed in `OnGetAsync()` - rendering doesn't begin until after the "initializer" has completed, no matter how long it takes.

**Comment by javiercn** [comment]
@mqudsi Thanks for contacting us.

We don't support `async void` you need to change your method to return a Task.

**Comment by mqudsi** [comment]
@javiercn sorry, that was a typo when I was copying the code to the sample. It wouldn't have even compiled (since there was no matching method to override). I have corrected the typo, the issue still stands. If you don't mind removing the answered/resolved status?

**Comment by javiercn** [comment]
@mqudsi thanks for the additional details.

Rendering a static component is no different than rendering a non-static component (code wise) and I have in good authority that we wait for the components to have finished initializing.

I'm not sure how this can be happening, so for us to move forward, I would suggest you create a minimal repro project on GH that we can access to get a precise picture of your scenario.

**Comment by mqudsi** [comment]
I think I figured it out. 

> Rendering a static component is no different than rendering a non-static component (code wise) and I have in good authority that we wait for the components to have finished initializing.

Rendering, at least the first time, does *not* wait for `OnInitializedAsync()`, but I was wrong with what I said here:

> the component is only rendered the very first time and not revisited thereafter

In truth, the component is rendered multiple times *even in static rendering mode*, but only the result of the rendering after `OnInitializedAsync()` has completed and all variables have settled to their final values is captured in the final HTML served to the client.

So this, like the code sample I posted above, is broken:

```cshtml
@code {
	private IList<Categories> Categories { get; set; }

	protected override async Task OnInitializedAsync()
	{
                await Task.Delay(1000);
		Categories = new List<string>() { "hello" };
	}
}

<ul>
foreach (var c in Categories) {
	<li>@c</li>
}
</ul>
```

Because `OnInitializedAsync()` isn't awaited before the Razor CSHTML is executed, and when it does get executed for the first (and here I wrongly believed to be the only) time, it fails because `Categories` is null and the null reference exception brings a halt to the whole thing. But this works:

```cshtml
@code {
	private IList<Categories> Categories { get; set; }

	protected override async Task OnInitializedAsync()
	{
                await Task.Delay(1000);
		Categories = new List<string>() { "hello" };
	}
}

@if (Categories is null)
{
    return;
}

<ul>
foreach (var c in Categories) {
	<li>@c</li>
}
</ul>
```

precisely because the rendering actually happens multiple times.

I would argue that for statically rendered components it is wasteful to render at all before `OnInitializedAsync()` has completed, but that's a different discussion.

**Comment by javiercn** [comment]
@mqudsi thanks for the additional details.

Triggering a render is cheap. We don't plan to change this, doing so would create different semantics in a component between when its rendered statically vs when its rendered dynamically, which is something we don't want to encourage. Right now a component renders the same way independent of the context in which they are being rendered, and that's a trait we want to keep.

**Comment by mqudsi** [comment]
Awesome, thanks for the explanation.
