### ISSUE TITLE
Regression: `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory` no longer allows the content root to be set programatically in some cases

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet/aspnetcore#34354]
### Describe the bug
Hi, In .NET 5 it was possible to override the `ConfigureWebHost` method of `WebApplicationFactory` and call `builder.UseContentRoot(".")` when the content root can't be inferred (eg if the startup class isn't defined inside a web project).

In .NET 6, this is no longer possible as the `SetContentRoot` method now always calls `GetContentRootFromFile`. `GetContentRootFromFile`  throws an exception rather than returning null if no content root is present in `MvcTestingAppManifest.json`.

This affects the integration tests of the FluentValidation project, which need to be able to set the content root programatically (the controller end points, startup class, and integration tests themselves are all in the same project). 

I haven't looked into how the `MvcTestingAppManifest.json` file is generated, but it seems that it isn't populated with the test assembly itself, which is a problem if the Startup/entrypoint class is defined inside the test project, rather than a web project. 

### To Reproduce

- Create an integration test project
- Add the startup file to the integration test project (not to a separate web project)
- Create the test host using WebApplicationFactory to point to the Startup class that's inside the test project 
- *edit* I've made a small sample project to reproduce: https://github.com/JeremySkinner/IntegrationTestingRegression

Here is the web application factory that I was using in .net 5:

```csharp
public class WebAppFixture : WebApplicationFactory<Startup> {

		protected override void ConfigureWebHost(IWebHostBuilder builder) {
			builder.UseContentRoot(".");
		}
 //...
}
```

In .NET 5 this worked fine, but in .NET 6 `ConfigureWebHost` is never called as `GetContentRootFromFile` will always throw an exception before it gets to this point. 

My hacky workaround is to delete the manfiest file in the ctor:

```csharp
public WebAppFixture() {
	if (File.Exists("MvcTestingAppManifest.json")) {
		File.Delete("MvcTestingAppManifest.json");
	}
}
```  

...and then GetContentRootFromFile will never execute, and the exception won't be thrown.

### Recommendation

If `GetContentRootFromFile` could be modified to return null rather than throw an exception, then the previous behaviour would continue to work. 

https://github.com/dotnet/aspnetcore/blob/1395fa8574a574ca969463952d4c5e89e9febe89/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L228-L239

If the above method returned null, then the "old" (net5) codepath would continue to run, as it already handles the case when the content root is null:

https://github.com/dotnet/aspnetcore/blob/1395fa8574a574ca969463952d4c5e89e9febe89/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L208-L226

...and I believe adding an override in `ConfigureWebHost` would then continue to work. 

### Exceptions (if any)

```
Error Message:
   System.Collections.Generic.KeyNotFoundException : Could not find content root for project 'FluentValidation.Tests.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in test manifest file 'MvcTestingAppManifest.json'

```

### Further technical details
- ASP.NET Core version: 6 preview 6
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/jskinner/.dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  2.1.505 [/home/jskinner/.dotnet/sdk]
  3.1.408 [/home/jskinner/.dotnet/sdk]
  5.0.202 [/home/jskinner/.dotnet/sdk]
  6.0.100-preview.6.21355.2 [/home/jskinner/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download


```

**Comment by JeremySkinner** [comment]
Here's minimal sample project to reproduce: https://github.com/JeremySkinner/IntegrationTestingRegression

```
git clone https://github.com/JeremySkinner/IntegrationTestingRegression.git
cd IntegrationTestingRegression
dotnet test
```

**Comment by mkArtakMSFT** [comment]
@davidfowl have you been working on this area recently? Is this intentional?

**Comment by davidfowl** [comment]
Looks like it was caused by [this change](https://github.com/dotnet/aspnetcore/pull/28575), @captainsafia might have more information.

**Comment by JeremySkinner** [comment]
Thanks @captainsafia!

**Comment by JeremySkinner** [comment]
Hi @captainsafia I'm still seeing this behaviour with preview 7 so I'm guessing this didn't make it in time for this release. Do you know which release the fix is targetted for? Thanks!

**Comment by martincostello** [comment]
Yeah the fix for this missed out on preview 7 ([tag](https://github.com/dotnet/aspnetcore/commits/v6.0.0-preview.7.21378.6/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs)). It's in the RC1 daily builds.

https://github.com/dotnet/aspnetcore/commits/v6.0.0-preview.7.21378.6/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs
