### ISSUE TITLE
Hot Reload does not work in upgraded Project net5 -> net6

### ISSUE THREAD

**Issue by oiBio** [dotnet/aspnetcore#34355]
### Describe the bug
i upgraded my net5 blazor server-side app to net6 preview 6. unfortunatly hot reload does not work. when started with "dotnet watch" i get 

> watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + Shift + R" to restart.

so it seems to work, but it does not trigger when i change a file - not for *.cs nor for *.razor nor *.css. i just dont see the "file changed" line and i also dont see any changes nor a rebuild. 
There seems to be a problem with my projects, because it works with a clean new blazor project.

Also i got it working with preview3 back in april - it was quite slow in my project so i reverted all code changes and did not tried again till now. i was hoping for some progress for this issue #32867

### To Reproduce
Unfortunatly in a minimal repo it works... so i cant realy reproduce it for you

### Further technical details
- ASP.NET Core version: 
> net6-preview6
- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   6.0.100-preview.6.21355.2
>  Commit:    7f8e0d76c0
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\
> 
> Host (useful for support):
>   Version: 6.0.0-preview.6.21352.12
>   Commit:  770d630b28
> 
> .NET SDKs installed:
>   2.2.207 [C:\Program Files\dotnet\sdk]
>   3.1.200-preview-014977 [C:\Program Files\dotnet\sdk]
>   3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
>   3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
>   3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]
>   3.1.302 [C:\Program Files\dotnet\sdk]
>   3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
>   5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
>   5.0.201 [C:\Program Files\dotnet\sdk]
>   5.0.301 [C:\Program Files\dotnet\sdk]
>   5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
>   6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
>   6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
> Microsoft Visual Studio Professional 2022 Preview (64-bit)
Version 17.0.0 Preview 2.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It seems that you may have not updated your project completely / properly. As for the slowness, we are aware of it and it's being addressed already - in preview7.

**Comment by oiBio** [comment]
mmh any suggestions where the error might be? Hot Reload stoped working for us aufter preview 3
We did the exact same changes and it does not work :-/

All projects target net6 and all microsoft nugets target preview-6, exactly like descriped...

**Comment by oiBio** [comment]
Maybe another hint: When i make a simple change in a razor-file (linke change inline css from backgrund-color:red to blue) and press the new apply code changes button i get 

![image](https://user-images.githubusercontent.com/33127462/125900678-6307da33-f5ad-41b5-991b-3e5930aece9c.png)
