### ISSUE TITLE
How to determine if the code is running in Release Mode for Blazor WASM and JavaScript

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#34379]
Are there any option to determine if the code is running as release mode in Blazor wasm hosted Application 
as well as in JavaScript ?
I want to disable certain type of logging when running under Release.
Also want to determine that in JavaScript as well.

**Comment by nssidhu** [comment]
This seems to be working but want to make sure this is the right way to determine
#if DEBUG
        Console.WriteLine("Debugging");
#else
       Console.WriteLine("Release");
#endif

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Yes, that should work and is a reasonable way to do it.
