### ISSUE TITLE
Docker runtime from 2.0 suddenly not working

### ISSUE THREAD

**Issue by yuribsl** [dotnet/aspnetcore#34384]
Hi, i have a project .NET Core 2.0 running, about 2 days ago, when i try to create a docker image for my project, using the  microsoft/aspnetcore:2.0 image on my docker file, it says the Microsoft image is not found. I can't find any news about this image not being available anymore anywhere, but i also can't find another one i can use lol.

I am getting the following error:

```
[1/4] FROM mcr.microsoft.com/dotnet/aspnet:2.0
resolve mcr.microsoft.com/dotnet/aspnet:2.0 0.1s done
ERROR: mcr.microsoft.com/dotnet/aspnet:2.0 not found
[internal] load metadata for mcr.microsoft.com/dotnet/aspnet:2.0:
 [1/4] FROM mcr.microsoft.com/dotnet/aspnet:2.0:
 failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: mcr.microsoft.com/dotnet/aspnet:2.0 not found
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is probably a result of https://github.com/dotnet/dotnet-docker/issues/2848 work.

**Comment by yuribsl** [comment]
So.. just to check if i understood it correctly. The 2.0 image was removed from Dockerhub and MCR on the migration proccess. And the 2.1 version will go Out of support next month, meaning the image will be removed from the registry as well? So i need to upgrade my apps to 3.1 as soon as possible?
Or is there a new url on MCR with the 2.0 image? Because i can't find it. Also, do you know if the 2.1 image is compatible with my 2.0 app? Because i tried that but it didn't work. I'm not 100% sure if because it is not compatible or i am missing some configuration.

**Comment by martincostello** [comment]
.NET Core 2.0 has been out of support since [October 2018](https://devblogs.microsoft.com/dotnet/net-core-2-0-will-reach-end-of-life-on-september-1-2018/), and 2.1 will go out of support next month [on the 21st of August](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/). You'd be best investing your time in moving to 3.1 as soon as possible.

**Comment by yuribsl** [comment]
@martincostello Thanks for the advice. When i upgrade .NET versions, is there too much risk of runtime errors? Or every error on version upgrades happens at runtime?

**Comment by martincostello** [comment]
From what I recall, 2.0 -> 2.1 and then 2.1 -> 3.0 had a number of breaking changes.

You'll have to go back through the release notes for them to see what they might be, and they'll vary based on what your application does, but I would have thought it highly likely that you'll have to make source changes to fix compilation errors/warnings and then test to flush out and changes in runtime behaviour.

**Comment by mkArtakMSFT** [comment]
@martincostello is right, you'll have to go through all these breaking changes to get your project to a desired supported framework.

Thanks for helping out, @martincostello !

**Comment by spacecheeserocks** [comment]
I fully understand the "out of support anyway" argument, but it's hugely annoying to have these just ripped away. This sort of thing impacts our ability to run old builds to troubleshoot issues and such.

I can understand not wanting to push old images to mcr.microsoft.com, but did it really hurt to leave the old ones behind? Or at least provide some reasonable way for someone to fetch older versions as required?
