### ISSUE TITLE
Components.TestsServer can no longer be started from VS due to hot reload

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34380]
It used to be possible to start `Components.TestsServer` via ctrl+f5 from VS. This was the normal way I ran the E2E test components when working on them. However when running from VS, it now fails because the request for `blazor-hotreload.js` gives a 404.

This might be only a problem with our repo (but still work fixing even if so), but it **might also be a real product issue** that happens if you're running from a non-root path. If I strip out the `/subdir` part of the URL, then `blazor-hotreload.js` does actually get returned correctly, which is very suspicious.

Steps:

 * In VS, set `Components.TestsServer` as startup project and ctrl+f5
 * In the browser, choose *Dev server client-side blazor*

Expected: component picker appears and it works
Actual: *An unhandled error has occurred*

```
Failed to load resource: the server responded with a status of 404 (Not Found)
MonoPlatform.ts:63 System.AggregateException: One or more errors occurred. (Failed to fetch dynamically imported module: http://localhost:50135/subdir/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: http://localhost:50135/subdir/_framework/blazor-hotreload.js)
 ---> Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:50135/subdir/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: http://localhost:50135/subdir/_framework/blazor-hotreload.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext() in C:\git\dotnet\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\JSRuntime.cs:line 97
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.InitializeAsync() in C:\git\dotnet\aspnetcore\src\Components\WebAssembly\WebAssembly\src\HotReload\WebAssemblyHotReload.cs:line 40
```

**Comment by Mercurial** [comment]
I'm getting this issue as-well in preview-6 just straight out `dotnet watch` then I get this

```
GET http://localhost:5000/_framework/blazor-hotreload.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by SteveSandersonMS** [comment]
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/34975 which contains more info.
