### ISSUE TITLE
[Blazor] EditForm validation problem

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#34397]
Consider the following simplified model:

```csharp
        [Required(ErrorMessage = "Missing Party Type.")]
        public Guid? PartyTypeGuid { get; set; }

        [Required(ErrorMessage = "Missing First Name.")]
        [StringLength(50, ErrorMessage = "Invalid First Name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Missing Last Name.")]
        [StringLength(50, ErrorMessage = "Invalid Last Name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Missing Organization Name.")]
        [StringLength(100, ErrorMessage = "Invalid Organization Name.")]
        public string OrganizationName { get; set; }
```

I have a data entry form with a dropdown ``PartyType``. If the dropdown value is set to **Individual**, the form displays **First Name** and **Last Name** input fields that the user is required to enter and **Organization** field is removed from the form. If the value is set to **Organization** the user is required to fill out **Organization Name** input field and  **First Name** and **Last Name** fields are removed from the form.

The problem is that when the user submits the form, although there are no validation error messages, ``OnValidSubmit`` event callback of the ``EditForm`` component is not called! How can I resolve this issue? This is a perfectly valid scenario - depending on user's selection, only a subset of required fields need to be validated.

Thank you!

**Comment by pranavkm** [comment]
Seems like a question about using DataAnnotations. You can consider authoring an `IValidatableObject` or `CustomValidationAttribute` to build rules about what needs to be validated. Validation does not know what items are visible in the UI, so you cannot rely on that to require what fields get validated.

**Comment by daniel-p-tech** [comment]
Thanks for the pointer, I ended up creating a custom ``RequiredIf`` attribute.
