### ISSUE TITLE
error when publish blazor wasm asp.net core hosted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34392]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-when-publish-blazor-wasm-aspnet-c/1460763)._

---
[severity:It's more difficult to complete my work] [regression]
Error when publish blazor wasm asp.net core hosted self contained and target to folder. Severity	Code	Description	Project	File	Line	Suppression State
Error		The referenced project '.. \Client\Jasamedika.Pendidikan.Client.csproj' is a non self-contained executable.  A non self-contained executable cannot be referenced by a self-contained executable.	Jasamedika.Pendidikan.Server.

---
#### Feedback Bot on 6/25/2021, 01:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/25/2021, 03:36 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It seems you're trying to do this on a 3.1 project. Blazor WebAssembly is not supported on 3.1. So you should try doing this with 5.0, which should work.
