### ISSUE TITLE
Make StartupAnalysisBuilder-based analyzers work with WebApplicationBuilder

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#34404]
Today we have analyzers that warn for various misconfigurations of middleware, options and service registration all based on [StartupAnalysisBuilder](https://github.com/dotnet/aspnetcore/blob/main/src/Analyzers/Analyzers/src/StartupAnalysisBuilder.cs#L15). We should make this work for applications using WebApplicationBuilder without a `Startup` class.

This is related to #34146. We want to address that with a new analyzer to verify middleware ordering for WebApplicationBuilder now that UseRouting()/UseEndpoints() is often implicit.

**Comment by JunTaoLuo** [comment]
This should probably be re-assigned.
