### ISSUE TITLE
Memory Leaks starting with DotNet 6 Preview 5 in Blazor Server Statically-Rendered Components

### ISSUE THREAD

**Issue by fitdev** [dotnet/aspnetcore#34414]
### Describe the bug

After upgrading from DotNet 6 Preview 4 to Preview 5, and then, now to Preview 6, I noticed my website memory usage going up with time, whereas on Preview 4 it pretty much stayed the same for days, now it was adding like 100MB every half-hour, even though _no changes_ have been made (other than recompile for Preview 6) and the website load (users) remained the same.

I suspected a memory leak, and so collected GC Heap dumps every few hours. What I saw was this:

![2021-07-16 09_03_01-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/125900388-2975c47e-6b97-4ed9-9964-bfdad934783f.jpg)

Then, after running for 1 more hour:

![2021-07-16 09_03_26-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/125900403-7d63f453-ec74-432f-b253-7c552e82621b.jpg)

Clearly there was some change introduced with Preview _5_, which is also in Preview _6_, as both of those exhibit the same behavior. Preview _4_, however works fine.

What is interesting is that _all_ of my Razor components are exposed via a single `cshtml` view with basically one line of code:

```razor
<component type="Model.RazorComponentType" render-mode="Static" param-Model="Model" />
```
That is _all_ Razor components are rendered _statically_ on the Server.

What I tried:

- x86 vs x64 made no difference.
- `UseRazorSourceGenerator` in MSBuild Project file to either generate `mywebsite.Views.dll` or not made no difference.

My Code does use quite elaborate component inheritance, as well as manually constructed components (entirely in code using `RenderTreeBuilder`). But the point is I have not done any changes to code, and what previously worked in DotNet 5 and DotNet 6 Prview 4, no longer does and lead to this memory leak.

### Further technical details
- ASP.NET Core version: 6.0.0-preview.6.21352.12
- Include the output of `dotnet --info`:

```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  2.1.520 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 Preview 2 (though project was built and deployed using DotNet CLI)

**Comment by javiercn** [comment]
@fitdev thanks for contacting us.

Have you tried forcing a Gen 2 GC and checking if the objects are rooted after that?

**Comment by fitdev** [comment]
@javiercn Thank you for looking into this.

Prior to both of the snapshots above there have been on the order of 100 Gen0 and Gen1 collections. And maybe around 10-20 Gen2 collections. So, to answer your 2nd question, Yes the memory definitely grows and is not being freed by the GC.

I should also mention that I tried Server vs Workstation GC flavors with mo difference.

I am not sure what good forcing a GC will do, considering during the lifetime there are many GCs happening that have no effect on the matter (i.e. memory usage grows).

Also, perhaps I should mention that under Paths to Root cycles have been detected:

![2021-07-16 15_16_34-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/125946195-5be70e60-b506-4c19-8bc7-cbbc423df116.jpg)

**Comment by javiercn** [comment]
@fitdev triggering a Gen 2 GC collection helps with establishing whether something is holding on to the objects, most GC collections don't clear all the objects.

Can you check what things are rooting those objects? The fact that you see a bunch of Blazor types on the memory profile doesn't necessarily imply that its an issue in the framework, it can be something on your app causing those objects to stay in memory.

We would need a bit more info to make progress here since this can be something caused by your app and we don't have a good way to know:
* If you can create a minimal repro project that has this behavior that would work.
* Alternatively, check the GC roots for your app and trace the path starting from the framework code that is holding on to that memory.

**Comment by fitdev** [comment]
I will try forcing a Gen2 collection and see what I get, as you suggest.

But what could have changed between Preview 4 and Preview 5 that caused this behavior to start happening?

**Comment by javiercn** [comment]
Also, its fundamental that you run the app in Release and the publish output, not from Visual Studio

**Comment by fitdev** [comment]
I don't use VS to publish. I use CLI by running: `dotnet build src\Website.csproj /p:DeployOnBuild=true /p:PublishProfile=MyProfile`

With these options:
```
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SelfContained>true</SelfContained>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>True</EnableMSDeployBackup>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <EnvironmentName>Production</EnvironmentName>
```

**Comment by javiercn** [comment]
@fitdev that's fine, I just want to make sure that you are not running a debug build nor from in `development` mode. (dotnet run and similar).

Just `dotnet your.dll` against the Release build of what you generate to make sure there are no dev features that can potentially interfere like hot reload.

**Comment by fitdev** [comment]
What do you suggest I use to:

> Alternatively, check the GC roots for your app and trace the path starting from the framework code that is holding on to that memory.

I cannot seem to find this functionality in the Managed Heap view.

**Comment by javiercn** [comment]
You can take a memory dump and use you can use dotnet dump or windbg to do that as described [here](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak)

**Comment by fitdev** [comment]
Here's the output of `gcroot -all` ran on a random instance of `Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder` within the context of `dotnet-dump` tool.

```
Statistics:
              MT    Count    TotalSize Class Name
00007ffa1c3c2348     3572       200032 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
Total 3572 objects
> gcroot -all 00000168123cc250
HandleTable:
    000001680D201358 (strong handle)
    -> 0000016828319C10 System.Object[]
    -> 000001681223DF30 System.Action
    -> 0000016811CBBEF8 System.Object[]
    -> 000001681223DEF0 System.Action
    -> 000001681223D878 Microsoft.AspNetCore.Components.Rendering.HtmlRenderer
    -> 000001681223E7F0 System.Collections.Generic.List`1[[System.ValueTuple`2[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components],[Microsoft.AspNetCore.Components.ParameterView, Microsoft.AspNetCor
Components]], System.Private.CoreLib]]
    -> 000001681223E8C8 System.ValueTuple`2[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components],[Microsoft.AspNetCore.Components.ParameterView, Microsoft.AspNetCore.Components]][]
    -> 000001681223E5C8 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 000001681223E730 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 000001681223E768 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812240960 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168122410D8 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122411B0 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122411E8 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812242708 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812242CC0 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812242D98 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812242DD0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812242E48 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812243400 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122434D8 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812243510 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812243588 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812243D80 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812243EC0 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812243EF8 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812243F70 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812244510 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122445E8 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812244620 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122446B0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812244C50 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812244D28 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812244D60 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812244DF0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812245548 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812245688 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122456C0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122459D0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812245F70 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812246048 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812246080 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812246110 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168122466B0 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812246788 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122467C0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812246E60 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812247C60 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812247D38 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812247D70 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812253368 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812257040 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812257118 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812257150 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122737C8 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812275010 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122750E8 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812275120 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812241340 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812279020 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812279160 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812279198 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122758B0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168122A18E0 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122A1B00 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122A1B38 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122BEA18 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168122BF070 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122BF1B0 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122BF1E8 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168122DDB78 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168122DECD0 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168122DEE10 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168122DEE48 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812315D20 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 0000016812317F48 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 0000016812318088 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 00000168123180C0 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 0000016812363D70 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168123644A0 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168123645E0 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder
    -> 0000016812364618 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder
    -> 00000168123CB780 Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame[]
    -> 00000168123CC110 Microsoft.AspNetCore.Components.Rendering.ComponentState
    -> 00000168123CC250 Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder

Found 1 roots.
```

Not sure what to make of it.

**Comment by fitdev** [comment]
I also noticed that the number of rooted `Microsoft.AspNetCore.Components.Rendering.HtmlRenderer`s keeps going up, despite the fact that they should have been disposed of and collected. In my case the number of `Microsoft.AspNetCore.Components.Rendering.HtmlRenderer`s that are kept alive very closely corresponds to the number of page views there have been during app's lifetime. So it is as if, every page view leaves behind an uncollected renderer.

For instance:

```
> dumpheap -mt 00007ffa1b2535c0
         Address               MT     Size
0000016810c03528 00007ffa1b2535c0      144
0000016810e86ec8 00007ffa1b2535c0      144
00000168112441b0 00007ffa1b2535c0      144
0000016811cbb6e8 00007ffa1b2535c0      144
0000016811d6e6c8 00007ffa1b2535c0      144
00000168121c4660 00007ffa1b2535c0      144
000001681223d878 00007ffa1b2535c0      144

Statistics:
              MT    Count    TotalSize Class Name
00007ffa1b2535c0        7         1008 Microsoft.AspNetCore.Components.Rendering.HtmlRenderer
Total 7 objects
> gcroot -all 0000016811d6e6c8
HandleTable:
    000001680D201358 (strong handle)
    -> 0000016828319C10 System.Object[]
    -> 000001681223DF30 System.Action
    -> 0000016811CBBEF8 System.Object[]
    -> 0000016811D6ED40 System.Action
    -> 0000016811D6E6C8 Microsoft.AspNetCore.Components.Rendering.HtmlRenderer

Found 1 roots.
```

**Comment by javiercn** [comment]
I too a quick look just for sanity and I don't see anything wrong. These objects get created via DI and are registered in the container, which manages their lifecycle. 

https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L236-L238

When the scope for the request goes away the objects should go away too, unless there is something holding on to them. From what I can tell, we don't hold on to them anywhere outside of that chain, so it likely points to something in your app. Either that or DI is completely broken, which I doubt.

Essentially you need to check two things:
* Are those objects being collected (by a forced gen 2 GC triggered with `GC.Collect(2, force: true)`)
  * If they are, its not a memory leak
* If they are not, can you send requests up until you get an Out of memory exception?
  * If not, its not a memory leak
  * If you do then, we need to find out what is holding on to those objects:
    *  Does the behavior repro on an app with just framework code?
      * Memory leak
    * Potential memory leak, but unlikely to be on the framework.

In the end, we need a chain of objects that starts from a static field or object on the stack that keeps accumulating references to these objects to conclude that there is a memory leak.

**Comment by fitdev** [comment]
Thank you for your suggestions. I will investigate more. But as for 

> Are those objects being collected (by a forced gen 2 GC triggered with GC.Collect(2, force: true)) 

my understanding is that they are not collected, since I used `dotnet-gcdump` to get heaps, and it forces full collection in order to produce the heap dump.

**Comment by fitdev** [comment]
I did some more tests and found out that the issue is not present at all in Preview 4, but is Present in 5 and 6.

In particular, I ran memory diagnostic sessions for both Preview 4 and Preview 6 versions, which have _identical code_ (apart referencing different versions of extensions packages and the framework in csproj files):

- Opened the same webpages in the same order.
- Took heap snapshot.
- Forced Gen2 GC.
- Took heap snapshot.

Here are the results after forced GC:

Preview 4:

![2021-07-17 15_00_58-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/126036419-12c88bff-9022-440a-bd1f-0b84ab6bbfd3.jpg)

Preview 5/6:

![2021-07-17 15_02_41-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/126036448-94e87757-a944-4531-851e-0fcfda3d0ffb.jpg)


Preview 4 results make complete sense: the pages have been rendered, response sent to the client, everything was disposed of and gc-ed.

Preview 5/6 results indicate a clear leak: what are all those `Microsoft.AspNetCore.Components.Rendering.*` and `RAZOR.*` (our component-derived types) doing there? They should not have persisted, because the pages have been rendered and sent out, no one is making additional requests (it was just me doing the tests), and there _was_ a forced full GC.

So, clearly Preview 5 introduced a regression of sorts, if not a bug.

**Comment by fitdev** [comment]
@javiercn 

I think I have discovered the culprit. It's Hot Reload functionality! (Why it's made its way into release build done through dotnet CLI publish I have no idea).

As far as I could gather, basically it goes like this:
 - `component` tag helper instantiates `HtmlRenderer` instances to actually render all Razor components statically
 - The `HtmlRenderer` instances create a bunch of objects to actually render, i.e. instantiate components, types in `Microsoft.AspNetCore.Components.Rendering.*`, etc. Of course this increases memory usage.

And now comes the difference:
 - Normally, once the response has ended, the `HtmlRenderer` would be disposed, and all its child types would be gone too.
 - However because of Hot Reload functionality, it is kept alive, because it is rooted by: `Action [Static variable Microsoft.AspNetCore.Components.HotReload.HotReloadManager.OnDeltaApplied]`:

![2021-07-19 17_40_27-DotNet (Debugging) - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/126180752-ab245e9f-a0c1-44c7-b9c8-702d9a30475d.jpg)

Hence it is never collected by the GC. Hence, basically every page view results in linear RAM increase (since in my case it roughly corresponds to one more instance of `HtmlRenderer` and all the references taht are rooted to it).

Hope this can be addressed soon. And would appreciate if in the meantime you can suggest how to disable Hot Reload functionality completely. I do not use it anyway.

**Comment by javiercn** [comment]
@fitdev thanks for the additional details!

This is indeed a great finding! I suspected if there  was something on the framework it would be around that area.

@pranavkm can you take a look at this since you are the expert for this area?

**Comment by fitdev** [comment]
I suspect this may have to do with the fact that `Renderer` removes the handler `RenderRootComponentsOnHotReload` of `HotReloadManager.OnDeltaApplied` event only in the _async_ version of Dispose code, i.e. only in `DisposeAsync()`. `Dispose()`, on the other hand has no code to remove that event handler, yet the handler is always added so long as `TestableMetadataUpdate.IsSupported` is true. So, if the code path is synchronous, like in my case, it often is, then presumably `Renderer.DisposeAsync()` never gets called, and so the `RenderRootComponentsOnHotReload` handler of `HotReloadManager.OnDeltaApplied` event stays.

https://github.com/dotnet/aspnetcore/blob/30f08577419507061f911630b49f0121e8389679/src/Components/Components/src/RenderTree/Renderer.cs#L1061

**Comment by fitdev** [comment]
Though regardless of what the specific details of this particular bug are, there should be an option to completely turn off / disable hot reload functionality! And it certainly should not make its way into production / release version.

**Comment by fitdev** [comment]
After even more tests I am confident that the cause for all this is the fact that the handler is not removed in the Sync version of Dispose() code as I described above.

My app relies on `Renderer` in 2 ways: directly (via `component` tag helper), and indirectly (via custom implementation of `HtmlRenderer` that inherits from `Renderer`). So, when I added a hack to my `HtmlRenderer` by making it directly implement `IDisposable` and added the following code to it:

```cs
void IDisposable.Dispose(){
    base.DisposeAsync().GetAwaiter().GetResult();
}
```

Then it was properly disposed and collected once request ended.

However this is not all, because the `Microsoft.AspNetCore.Components.Rendering.HtmlRenderer` that is created via `component` tag helper is _not_ being properly disposed _if I use 3rd-party IOC_. This is also kind of weird. Because if I use Microsoft default IOC like so:

```cs
      hostBuilder.UseDefaultServiceProvider((context, options) => {
        var isDevelopment = context.HostingEnvironment.IsDevelopment();
        options.ValidateScopes = isDevelopment;
        options.ValidateOnBuild = isDevelopment;
      });
```

then, all `Microsoft.AspNetCore.Components.Rendering.HtmlRenderer` instances that come from `component` tag helper _are_ disposed. But, if I use my prefferred IOC - DryIOC:

```cs
      var ioc = new Container(ConfigureDryIOCRules);
      hostBuilder.UseServiceProviderFactory(new DryIocServiceProviderFactory(ioc))
```

then `Microsoft.AspNetCore.Components.Rendering.HtmlRenderer` instances that come from `component` tag helper _are NOT_ disposed. Presumably that's because this 3rd party IOC does not call `DisposeAsync`, whereas built-in IOC does.

This is just FYI. In any case though:

1. The code to clean up (i.e. remove handler) for the Hot Reload stuff should be included in the _sync_ version of Dispose code.
2. There should be a mechanism to turn off hot reload completely, at the very least for production / release builds.

**Comment by davidfowl** [comment]
cc @dadhi

**Comment by dadhi** [comment]
@fitdev @davidfowl DryIoc does no support the `DisposeAsync` yet. But I was thinking that it is kind of convention to have the same dispose logic in the `Dispose` as well?

**Comment by davidfowl** [comment]
I agree, this is a blazor bug. I just wanted to let you know since DryIoC was involved
