### ISSUE TITLE
[Loc]With net6 preview 7 installed on locale OS, some template names are unlocalized after runing "dotnet new --list" in CLI 

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#34412]
Install net 6 preview 7 SDK[6.0.100-preview.7.21364.30(runtime:6.0.0-preview.7.21360.10)] from https://github.com/dotnet/installer
Install it on locale OS
Run “dotnet new --list” in CLI
Check if output contents are localized well.
Actual Result:
Some template names are not localized.

e.g
SC
![image](https://user-images.githubusercontent.com/65637796/125883913-6ae751ea-4e2e-424e-9846-49ce2a866176.png)

DE
![image](https://user-images.githubusercontent.com/65637796/125884007-105d0ba1-2bb8-4c44-9b13-bf28eab786d8.png)

**Comment by phenning** [comment]
No, we don’t do anything in WebTools for Cli localization. That is a totally separate process and localization method.

@David ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vdanche** [comment]
we found some strings mentioned in bug still are unlocalized in net 7 rc1, is it expected?
![image](https://user-images.githubusercontent.com/65637796/190111945-b20a43d8-1f7d-4932-baeb-e6c26114d74a.png)

**Comment by vdanche** [comment]
Protocol Buffer File has been localized on NET 7 RC. MVC ViewImports/MVC ViewStart which are unlocalized should be expected. and for ASP.NET Core with React.js and Redux, we filed another bug to track:[#44104(https://github.com/dotnet/aspnetcore/issues/44104):[
