### ISSUE TITLE
[Feature Request] Inject depdencies into JsonConverters

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#34417]
## Is your feature request related to a problem? Please describe.
Currently we cannot inject dependencies into a `JsonConverter`.

My use case: binding to valueobjects (basically custom types) that require dependencies.

e.g.
- my `PasswordJsonConverter` converts json to/from a `Password` valueobject
- a controller action binds a string to a `Password`
- `Password` validates the string given by the user, but must check for lowercase, uppercase, digits, unique characters, etc., which are stored in `appSettings.json` or elsewhere
- *so the `Password` type needs a dependency, thus the `PasswordJsonConverter` needs a dependency*

## Describe the solution you'd like
Allow us to inject depedencies into `JsonConverter` subclasses.

## Additional context
There are [workarounds](https://thomaslevesque.com/2020/08/31/inject-service-into-system-text-json-converter/), but they're complicated or messy.

**Comment by davidfowl** [comment]
The blog posts shows how you can do it. That's the way to inject dependencies with options.

**Comment by lonix1** [comment]
Okay if that's the official way... thanks for confirming.

Out of interest why is it not possible to have JsonConverters with dependencies (without extra / supporting classes)?

**Comment by lonix1** [comment]
Alright I just realized the answer, I think.

It's because they're added to the `Converters` array of some config property - not to the container. So they don't actually take part in the DI system. To "put them into" the DI system requires those supporting classes.
