### ISSUE TITLE
E2E test retry logic incorrectly tries to keep using same page

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34424]
Just noticed while developing locally - if an E2E test fails, then the test runner tries to retry. However, it doesn't instantiate a new browser or even reload the page. It continues trying to use the existing page, which continues to have whatever half-complete state was left behind by the previous test run.

This means the retries are very unlikely to succeed, and even if they did, it might be a false pass in that case since they are working from an invalid starting point.

cc @HaoK

**Comment by HaoK** [comment]
Yep, the retry functionality is done at a xunit extensibility level, we noticed it wasn't working properly for selenium e2e as well in https://github.com/dotnet/aspnetcore/issues/27156#issuecomment-874991215
