### ISSUE TITLE
Include Microsoft.AspNetCore.Server.Kestrel.Transport.Quic in the shared runtime

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#34439]
As of dotnet-sdk-6.0.100-preview.1.21366.55-win-x64 and  Microsoft.AspNetCore.App 6.0.0-preview.7.21363.16, Microsoft.AspNetCore.Server.Kestrel.Transport.Quic is not shipping in the shared runtime. 

msquic.dll is included in Microsoft.NETCore.App 6.0.0-preview.7.21365.21.

Moving it into the shared runtime will allow us to clean up the user experience (e.g. kestrel can include the quic transport by default).

**Comment by wtgodbe** [comment]
TODO - release note the removal of the package/addition to the SharedFx

**Comment by wtgodbe** [comment]
Leaving open to track release-noting this. @rbhanda where can I write/draft a release note for preview7 about us removing a package?

**Comment by rbhanda** [comment]
Hi @wtgodbe you can create an issue with the description you would like to add on https://github.com/dotnet/core

**Comment by dougbu** [comment]
@wtgodbe should this be closed now or after you've added the release note❔

**Comment by wtgodbe** [comment]
After I've added the release note

**Comment by wtgodbe** [comment]
Release note added
