### ISSUE TITLE
.NET Hot Reload not working with .NET 6 Preview 7 and dotnet watch

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#34440]
Repro steps:

- Install .NET 6 Preview 7 (6.0.100-preview.7.21366.53)
- `dotnet new blazorserver -o BlazorApp`
- `cd BlazorApp`
- `dotnet watch`
- Edit Pages\Index.razor

Expected result: UI updates with changes

Actual result:

- `dotnet watch` says the change was applied, and the browser flashes with the hot reload overlay, but the UI isn't updated.

@pranavkm

**Comment by pranavkm** [comment]
@mikem8361 it looks like `MetadataUpdater.IsSupported` returns false when running under dotnet-watch. Does not seem to be the case for Mono / WebAssembly. Here's a simple repro:

* `dotnet new console`
* Edit `Program.cs` to print `Console.WriteLine(System.Reflection.Metadata.MetadataUpdater.IsSupported);`
* `dotnet watch`

This prints `False` and causes some of our wire-up to fail. Could you look?

**Comment by mikem8361** [comment]
Fixed in PR https://github.com/dotnet/runtime/pull/55874

**Comment by pranavkm** [comment]
Can we port the fix to preview7?

**Comment by campersau** [comment]
Backport: https://github.com/dotnet/runtime/pull/55876
