### ISSUE TITLE
Add support for setting ApiDescriptor.GroupName for minimal APIs

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#34443]
Minimal APIs currently don't populate any value for the `ApiDescriptor.GroupName` property. We should add support for setting the group name via endpoint metadata and flowing that through to the `ApiDescriptor`, e.g.:

``` c#
app.MapGet("/myapi/do-the-thing", () => "done!")
   .WithGroupName("v1");

// Psuedo-spec
public static IEndpointConventionBuilder WithGroupName(this IEndpointConventionBuilder builder, string groupName)
{
    builder.WithMetadata(new EndpointGroupNameMetadata(groupName));
}

// Attribute for declarative scenario
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Delegate, Inherited = false, AllowMultiple = false)]
public sealed class EndpointGroupNameAttribute: Attribute, IEndpointGroupNameMetadata;
```

**Setting it by default**
Swashbuckle currently uses `ApiDescriptor.GroupName` in its [default API inclusion predicate](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs#L57) in such a way that if we were to set a default value that doesn't match the configured Swagger document name, the APIs would not be included by default. For that reason it seems like we **shouldn't** set a default value for `ApiDescriptor.GroupName` unless we also update the Swashbuckle logic.

@bradygaster

**Comment by Kahbazi** [comment]
@DamianEdwards I'm interested in doing this issue. Is it up for grab?

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/34541.
