### ISSUE TITLE
SignalR Client not Acking type 6 Ping?

### ISSUE THREAD

**Issue by SonoranBrian** [dotnet/aspnetcore#34451]
### Describe the bug
While using CloudFlare to proxy the WSS connection with SignalR, some users experience frequent disconnects. This is only reproducible while using a proxied connection with CF, and *seems* to be more frequent for users with multiple connections open at a time?

I've been trying to track down this issue for months: https://github.com/dotnet/aspnetcore/issues/29563 as it seems only certain users experience this. When the clients use a different version of the app without a CF proxy it works. This appears to be because CF closes (hence the 1006 WSS error) idle websocket connections.

However, it appears SignalR is automatically sending ping/keepalive messages (type: 6). Here's two client's screenshots of these type 6/ping messages not being acked for some reason?

**Example 1**
Here, it appears the server is sending two keep-alive messages that the client never acks back for some reason. Then the server tells the client to reconnect?
![image](https://user-images.githubusercontent.com/56844125/125991782-a198cd08-fdc3-4bc6-8e60-6523f8ee28aa.png)

**Example 2**
Here, it appears the client is sending two pings up to the server that are never acked back.
![image](https://user-images.githubusercontent.com/56844125/126027972-b50f0106-5897-4fa6-9da5-31704915312b.png)

To keep the WSS connection "Active", do all of these keepalives need to be acked back? It appears when this type 6 is not acked, from either end it then disconnects and reconnects. This could also just be a CF thing, requiring communication going both ways?

Should I manually code in a server -> client heartbeat/keepalive? Is there any reason you can think of that would cause these messages not to be responded to?

### To Reproduce
Use Cloudflare proxying for WSS connections

### Exceptions (if any)
> Websocket closed with status code: 1006

### Further technical details
- ASP.NET Core SignalR version 5.0.7
- @microsoft/signalr@5.0.7

**Comment by BrennanConroy** [comment]
The Ping messages are not "acked", they are separately sent from both sides and both sides also have a timeout if any message isn't received within the timeout period. The send interval and the timeouts are [configurable](https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=dotnet#configure-server-options) for both sides.

If you are using Chrome, make sure that you are using the 3.1.16+ or 5.0.7+ versions of the client. Chrome introduced timer throttling for background tabs which would cause pings to not be sent and close connections.

Also, Chrome now has tab freezing which will break SignalR connections. I recommend turning that feature off while investigating potential issues (chrome://flags/#tab-groups-collapse-freezing).
