### ISSUE TITLE
Hot Reload Issue in Blazor - Uncaught ReferenceError

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/aspnetcore#34456]
I just upgraded my Blazor WASM project to .Net 6 Preview 6 (from .Net 5) and I'm now using Visual Studio 2019 Version 16.11.0 Preview 3.0.  I'm seeing an error show up often in my console saying:

Uncaught ReferenceError: notiifyHotReloadApplied is not defined
    at aspnetCoreHotReloadApplied (aspnetcore-browser-refresh.js:165)
    at Object.AspNetCoreHotReloadApplied (aspnetcore-browser-refresh.js:40)
    at WebSocket.connection.onmessage (aspnetcore-browser-refresh.js:44)

I glanced through the repo, but didn't know where to look to find this file. I'm guessing it's a typo (it has two i's in notify)?

I'm using 'dotnet watch'.  It's also not always repainting the screen, even though it says "Hot reload of changes succeeded", but I'm guessing it's related to the above error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which is already fixed in the upcoming preview7 release.
