### ISSUE TITLE
Add overloads to MapFallback that takes a Delegate

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#34450]
## Background and Motivation

Like the other Map* verbs we should add overloads to MapFallback that take a delegate. This is useful for implementing fallback routes that want to take advantage of the new binding and result APIs.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder
{
    public static class FallbackEndpointRouteBuilderExtensions
    {
+        public static MinimalActionEndpointConventionBuilder MapFallback(this IEndpointRouteBuilder endpoints, Delegate action);
+        public static MinimalActionEndpointConventionBuilder MapFallback(this IEndpointRouteBuilder endpoints, string pattern, Delegate action);

    }
}
```

## Usage Examples

``` C#
app.MapFallback((string name) => $"Hello {name}");
```

## Risks

None.

**Comment by halter73** [comment]
How do you expect the `string pattern` argument will be used? Will this still run the delegate if the pattern doesn't match?

**Comment by davidfowl** [comment]
There's an existing [MapFallback API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.fallbackendpointroutebuilderextensions.mapfallback?view=aspnetcore-5.0) that takes RequestDelegate with a pattern

**Comment by pranavkm** [comment]
This would have the same sort of problems (with overload resolution) as the other Map* overloads. `MapFallback` aligns with the existing RequestDelegate naming. Approved.
