### ISSUE TITLE
blazor + PWA = cache not updatable

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#34466]
when the blazor project is using PWA, the cache of all files is kept, even after a new version. is there any prediction of when this will be fixed (I read that there would be a solution somewhere) or is there already a workaround that I can use?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should help you to understand how PWA work, as this is not a bug: https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#caveats-for-offline-pwas

**Comment by drma-dev** [comment]
yes, I gave it a read. but it doesn't help at all.

I've already done tests. I can only update in two situations: clicking F5 or closing the browser.

I can't even do that on my cell phone. so my hands are tied.
