### ISSUE TITLE
HTTP/3: Future proof EnableAltSvc (alt-svc)

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34467]
`KestrelServerOptions.EnableAltSvc` is a boolean flag for enabling an alt-svc flag - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc

It is currently used to indicate to clients that the protocol can be upgraded to HTTP/3. Right now it is hardcoded to h3-28 (?). It will be changed to h3.

Should the property be changed to be more flexible? e.g. age, enable persist, customize protocol. What happens if alt-svc has new uses in the future? A boolean flag might not be flexible enough.

Should at least think about this in .NET 6.

**Comment by JamesNK** [comment]
`EnableAltSvc` proposal:
* Obsolete `KestrelServerOptions.EnableAltSvc`. HTTP protocols are customized per-ListenOptions. Enabling/disabling upgrade should also be on ListenOptions.
* Add `ListenOptions.EnableAltSvc`.
  * When `true`, the setting adds a header if all conditions are met...
    * Current endpoint's protocol includes HTTP/3.
    * Current request is HTTP/1.1 or HTTP/2.
  * Defaults to true. Almost everyone will want the header if they have an endpoint that supports Http1AndHttp2AndHttp3. Endpoints without HTTP/3 will automatically not use it.
  * `EnableAltSvc` only prompts to upgrade the current endpoint. This is different from the current behavior which will include the first HTTP/3 endpoint in the header. Upgrading to a different endpoint is not desirable in some situations.

@Tratcher @halter73 @davidfowl

**Comment by Tratcher** [comment]
> * Current request is HTTP/1.1 or HTTP/2.

I've noticed other implementations setting the alt-svc header even when already using HTTP/3. We'd need to understand why.


> * Existing `alt-svc` header value is overwritten.

Why would we overwrite an explicit app value? We don't do that for other headers like Server.

> ma=3600

We're not setting this parameter, right? Should we? And should it be configurable? Are there any other significant parameters?

**Comment by JamesNK** [comment]
> I've noticed other implementations setting the alt-svc header even when already using HTTP/3. We'd need to understand why.

I'll ask on the QUIC slack.

> Why would we overwrite an explicit app value? We don't do that for other headers like Server.

Ah, I thought we did overwrite other headers. Yes, for consistent we won't overwrite `alt-svc`.

> We're not setting this parameter, right? Should we? And should it be configurable? Are there any other significant parameters?

That controls how long the alt-svc is remembered for. I think we configure a best for most people value. If someone wants to customize it then they can set an alt-svc value themselves.

**Comment by JamesNK** [comment]
> I've noticed other implementations setting the alt-svc header even when already using HTTP/3. We'd need to understand why.

I asked and the reason is what we thought: keeps the browser cache updated with alt-svc details.
