### ISSUE TITLE
The asp.net core application loads the CPU even after a user requests are terminated.

### ISSUE THREAD

**Issue by neyromant** [dotnet/aspnetcore#3446]
Hi,
My asp.net core application is builded on .net core 2.1 and launched under CentOS 7.4 (Outside the Docker container). 
During the working day, this application has a high load. At night, when requests from clients stop, the application continues to use a lot of CPU. This stops only if I restart the application.

I searched for the blocking code manually and using [Ben.BlockingDetector](https://github.com/benaadams/Ben.BlockingDetector). (Question about this here: benaadams/Ben.BlockingDetector#9) But I did not find anything.

I collected and tried to analyze metrics using [perfcollect](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md)

These metrics are taken at night, when there are no requests from clients, but the application uses 206% of the CPU (The machine has 4 cores):

![image](https://user-images.githubusercontent.com/7146293/44485992-0d4a2d80-a65b-11e8-92ed-f356b7de6508.png)

![image](https://user-images.githubusercontent.com/7146293/44485870-b5132b80-a65a-11e8-9179-2c8a1fd236db.png)

My metrics are available here: (my application's name is current_app.anm)
https://drive.google.com/open?id=1SHTJqfWUMMOECcDUKnz37st1r4u_P4-j

Can anyone tell me what could be causing this problem? 
Thank you in advance for any response.

**Comment by Eilon** [comment]
@sebastienros - thoughts?

**Comment by neyromant** [comment]
I thought that it depends on [bug in System.IO.Pipelines package](https://github.com/dotnet/Announcements/issues/83) like [issue in Kestrel](https://github.com/aspnet/KestrelHttpServer/issues/2694)
But after connecting the package `<PackageReference Include="System.IO.Pipelines" Version="4.5.0" />` to my project nothing has changed.

dotnet/Announcements#83
aspnet/KestrelHttpServer#2694

**Comment by davidfowl** [comment]
@neyromant Did you update to .net core 2.1.4?

**Comment by neyromant** [comment]
@davidfowl Not yet, I just updated System.IO.Pipelines package.
My application is Self Contained Application and I do not use Microsoft.AspNetCore.App. 
Maybe the problem is this?

**Comment by Eilon** [comment]
@sebastienros any ideas on how to diagnose this?

**Comment by gzpbx** [comment]
@neyromant The same problem with yours - even no any request the asp.net core application still load high CPU, aspnet/KestrelHttpServer#2937

**Comment by sebastienros** [comment]
It could be the finalizer thread that is getting blocked. It would run even without any requests.

- Are you using EntityFramework, and changing how it's tracing SQL?
- Are you using HttpClient to request external services?

**Comment by davidfowl** [comment]
Can you take a memory dump? That might help as you can look at the finalizer queue that way.

**Comment by neyromant** [comment]
> It could be the finalizer thread that is getting blocked. It would run even without any requests.
> 
> * Are you using EntityFramework, and changing how it's tracing SQL?
Yes, I am
> * Are you using HttpClient to request external services?
Yes, I am

**Comment by neyromant** [comment]
> Can you take a memory dump? That might help as you can look at the finalizer queue that way.

Yes, of cource. My dump is here:
https://drive.google.com/file/d/1GPDSDktxOL_Cma61ZKSw3NH4gyhYnkr5/view?usp=sharing

**Comment by davidfowl** [comment]
Is this gcore dump or did you use https://github.com/dotnet/coreclr/blob/21f94f2be12e16bb36187d40c2fa82af9ebfd469/Documentation/botr/xplat-minidump-generation.md?

**Comment by neyromant** [comment]
This is gcore dump:
```
# ulimit -c unlimited 
# sudo gcore -o dump1 <pid of my self contained app>
```

**Comment by davidfowl** [comment]
Yep, I figured from the size 😄. This was collected on  CentOS 7.4 yeah?

**Comment by neyromant** [comment]
> This was collected on CentOS 7.4 yeah?

Yep, it is CentOS 7.4

**Comment by davidfowl** [comment]
I can't get this dump to load properly:

Try “readelf -a dump1.17928” and you will get some error messages:
 
```
readelf: Error: Reading 0x18c00 bytes extends past end of file for section headers
readelf: Error: Section headers are not available
```

**Comment by neyromant** [comment]
I'm sorry. I will check or I will soon make a new dump.

**Comment by neyromant** [comment]
@davidfowl, I am sorry for long answer.
I have uploaded corrected and checked dump here: https://drive.google.com/file/d/1ErM5in4N7ED620QWNHtW2abKFua1PtnN/view?usp=sharing

**Comment by mmikirtumov** [comment]
We have the same issue and we use HttpClient. 
This problem occured when we update to .Net Core 2.1.4.
For HttpClient we created wrapper class, which is scoped and constructor have only one line of code
 `_httpClient = new HttpClient();`
Do you have any idea what is the problem?

**Comment by poke** [comment]
@mmikirtumov Please consider using the [HttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1) for that. It will automatically follow the best practices when working with a `HttpClient`.

**Comment by mmikirtumov** [comment]
Thank you Patrick. I know that this is good practice. I am trying to figure it out what is the problem currently in my production server. And can HttpClient cause this issue?

**Comment by neyromant** [comment]
We are use the HttpClientFactory.

**Comment by vlad294** [comment]
![image](https://user-images.githubusercontent.com/9516149/49071952-2c4ef180-f240-11e8-80e1-ba84f1a36200.png)
> We are use the HttpClientFactory. 
@neyromant 
Have you resolved your issue? We have the same problem and now we are using HttpClientFactory.

We took a trace, but it didn't help us.

**Comment by neyromant** [comment]
@vlad294 Unfortunately no
