### ISSUE TITLE
Hot Reload: Adding a code block at runtime does not get hot reloaded, even refreshing the browser doesn't show the change.

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#34465]
### Describe the bug
Hot Reload: Adding a code block at runtime does not get hot reloaded, even refreshing the browser doesn't show the change. 

![image](https://user-images.githubusercontent.com/18366446/126052890-c94b7197-4f2b-4ba5-8d44-6e5d8e75d0da.png)

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new web app using "dotnet new blazorwasm"
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Open Pages/Index.razor
- Add a new code block and create a new property like "color"
- Now create a new line outside the code block to display this property value
- Now save the file
- You will notice in the console that the change IS detected however you get the message: "No hot reload changes to apply"
- Force refresh the browser and you will still not see your change
- CTRL + SHIFT + R does not work for some reason so you will need to stop and restart the app
- You will now see your changes

### Expectation
Code block changes are applied via hot reload

### Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by MacdonaldRobinson** [comment]
This is also related I think;

I noticed that you can now add a <style> tag and the style rules are  now scoped to the component which is great!

**Comment by pranavkm** [comment]
Thanks for the issue report @MacdonaldRobinson. For 6.0, adding a field is a rude edit with the WebAssembly runtime and requires a full rebuild. We were previously handling this incorrectly and suppressing the error the runtime would throw which explained some of the weird behavior you were seeing here. With a more recent SDK, dotnet-watch produces a rude edit when you make this change. 

We are using https://github.com/dotnet/runtime/issues/57365 to support more kinds of edits in the Mono runtime for 7.0.
