### ISSUE TITLE
WSL2: running the app using dotnet watch and then pressing "Ctrl + Shift + R" doesn't do anything when in windows terminal or in the VS Code terminal

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#34478]
### Describe the bug
WSL2: running the app using dotnet watch and then pressing "Ctrl + Shift + R" doesn't do anything when in WSL2 terminal or in the VS Code terminal

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new web app using "dotnet new blazorwasm"
- Enter "dotnet watch" to start the app
- You will see the message "Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + Shift + R" to restart."
- The app starts successfully
- Now press the key combo "Ctrl + Shift + R" as mentioned to rebuild the app
- You will notice that nothing happens

### Expectation
- The app should rebuild / restart and Refresh the browser when running a web app

### Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment]
Sorry this took us a while to get back to. I was able to confirm that VS Code will eat the Control+Shift+R gesture and it never reaches apps running in the terminal (couldn't reproduce it in with WSL terminal). But we'd like to make sure the VS Code experience isn't broken out of the box, so the plan is to change the restart gesture to `Ctrl + R`. We also said that if we later add support for hot restart (re-run main without a full rebuild), we'll use `R` as the gesture to kick this off.
