### ISSUE TITLE
Adding the ContentLength header to blazor webassembly provided Framework files

### ISSUE THREAD

**Issue by JPVenson** [dotnet/aspnetcore#34479]
## Summary

To allow an tracking on client side, especially for low bandwidth devices it would been helpful to have the `content-length` header set when loading the Webassembly framework files.

## Motivation and goals

- The existence of the content-length header would help implementing a progress display at the start of the application
- It could be used to display more advanced progress if necessary 

## In scope

- If used in conjunction with an overwritten `loadBootResource` it allows the display of an progressbar
- It allows an more interactive progress display at the very first start of the app
- It allows an more interactive progress display in a low bandwidth scenario 

## Out of scope

This does not include and changes to the client-side `Blazor.Start({ loadBootResource: ... })` code. An content-length header would only be added, its up to the dev to handle it.

## Risks / unknowns

I am not aware of any risks involving this feature.

## Examples

If the server provides proper `Content-Length` headers for Framework files, the dev could implement a custom `loadBootResource` that keeps track of the current download state for all assemblies like this:

```javascript
var progressbar = document.getElementById('progressbar');
Blazor.start({ 
	loadBootResource: function (type, name, defaultUri, integrity) {
		if (type == "dotnetjs")
			return defaultUri;

		var val = {
			url: defaultUri,
			progress: 0
		};
		allResourcesBeingLoaded.push(val);

		return fetch(defaultUri, {
			cache: 'no-cache',
			integrity: integrity,
		}).then((response) => {
			const contentLength = response.headers.get("content-length");
			progressbar.max += parseInt(contentLength);

			return new Response(
				new ReadableStream({
					start(controller) {
						const reader = response.body.getReader();

						read();

						function read() {
							reader.read().then(({ done, value }) => {
								if (done) {
									controller.close();
									return;
								}
								val.progress = value.byteLength;
								progressbar.value = allResourcesBeingLoaded.map(e => e.progress).reduce((e, f) => e + f);
								controller.enqueue(value);
								read();
							}).catch(error => {
								console.error(error);
								controller.error(error);
							});
						}
					}
				})
			);
		});
	}
});
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This will be possible after the https://github.com/dotnet/aspnetcore/issues/32353 is done.
