### ISSUE TITLE
HTTP/3: EnableAltSvc for all HTTP/3 endpoints?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34472]
The current `EnableAltSvc` behavior is it will add the header and specify the first HTTP/3 enabled endpoint. Question is, is that correct?

Options:
* Just the first HTTP/3 enabled endpoint
* All HTTP/3 enabled endpoints (`alt-svc` isn't limited to one entry)
* Just the current endpoint (if it supports HTTP/3)

**Comment by adityamandaleeka** [comment]
Triage: `alt-svc` should only advertise the current endpoint.
