### ISSUE TITLE
Blazor WebAssembly Standalone on ASP.NET Website

### ISSUE THREAD

**Issue by eguardiola** [dotnet/aspnetcore#34474]
Hi,

I have a solution on VS 2019 with a website project (yes, this is old) and another project with an Blazor WebAssembly Standalone app.

I'm able to publish the Blazor app inside a folder on the website and see it running on the browser. No problem here.

What i don't know is how to get a development workflow on this scenario. I don't know how to make changes and see the result without publishing or get the debugging features working on the blazor project, etc.

The Website also have some .ashx files serving some json-rpc services im willing to use from the Blazor client on the browser.

I have read Blazor WebAssembly Standalone is server side technology agnostic but i don't know how to get a development workflow on this scenario with an old ASP NET Website.

Can u help on this with some ideas ? Thanks in advance!

**Comment by javiercn** [comment]
@eguardiola thanks for contacting us.

That's not a scenario we support. Blazor WebAssembly is completely server side agnostic (it's just a bunch of files on disk) however the development workflow is not optimized for old ASP.NET projects. A standalone Blazor Webassembly app uses a development server to run during development and that's not something you can easily implement in an old ASP.NET project.

If you are willing to spend time on making something like this work, I would recommend the following approach:
* Create the blazor app as a hosted blazor webassembly app.
* On the host server app, use an existing proxy middleware to route unknown requests from the app to your old website project).
* Run both, the app host and the old ASP.NET project.
* Navigate through the site via the Url for the hosted ASP.NET Core host.

This is just a suggestion about how I would go about doing this, however there's no guarantee that this works properly nor that it is trivial to implement. This suggestion is based on how our SPA proxy support works, which should also work in this case.

**Comment by eguardiola** [comment]
Thanks for the quick reply. I was intuiting something like the proxy you propose, but I needed a confirmation. Very inspiring answer, thank you very much!

**Comment by eguardiola** [comment]
Sorry, i assume the proxy idea is the same if you have on the server PHP or Java or another other stuff, right?
