### ISSUE TITLE
Hot Reload: Adding and Removing components at runtime should not rebuild the app but should be hot reloaded

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#34476]
### Describe the bug
Hot Reload: Adding and Removing components at runtime should not rebuild the app but should be hot reloaded

![image](https://user-images.githubusercontent.com/18366446/126068298-3cb54ae8-8e8a-44c5-9aad-4307c3f823e5.png)

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new web app using "dotnet new blazorwasm"
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Create a new component: "Component1.razor"
- In the console you will notice that the change was detected, however it says: "Unable to handle changes to /home/mac/src/blazorwasm/Pages/Component1.razor." the app is then rebuilt / restarted and the browser is refreshed
- Now delete the newly added component "Component1.razor"
- Once again the change was detected, but the app rebuilds and restarts

### Expectation
- Adding a component should automatically load it and apply the code changes
- Deleting a component should remove it at runtime and then replace all locations where the component was called with a ErrorBoundry message saying the component "Compopnent1" does not exist

### Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
I just tried this with .NET 7 RC1 and the latest VS preview and it seems to be fixed already.
Specifically, I could add a component for a running app, then hot reload and see the new component show up (without app restarting). I then could remove the component and see it being removed from the UI.
