### ISSUE TITLE
HTTP/3: Document Kestrel requirements

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34488]
Discuss:

* Operating system requirements
  * Windows version number
  * Linux version number
* How to reference the package on Linux
* AppContext switch (if added)

Update quick link https://aka.ms/aspnet/kestrel/http3reqs to point to docs.

**Comment by adityamandaleeka** [comment]
See https://github.com/dotnet/runtime/blob/594901aa0ae58d9df1cf5daaee15b5f055a9deda/src/libraries/System.Net.Quic/readme.md

**Comment by wtgodbe** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http2?view=aspnetcore-5.0

**Comment by wtgodbe** [comment]
Done for preview7 by https://github.com/dotnet/AspNetCore.Docs/pull/22966, but needs to be updated for RC1 when we ship that.
