### ISSUE TITLE
append cookie json 

### ISSUE THREAD

**Issue by MohsenEs** [dotnet/aspnetcore#34484]
why append cookie problem?
          Response.Cookies.Append("setting", JsonConvert.SerializeObject(model.SettingMenuViewModel));
![2021-07-19_9-44-56](https://user-images.githubusercontent.com/46873097/126106512-315083c5-91d8-49ae-b061-d0deeac3d87a.png)

Why is it not Jason format?

**Comment by Tratcher** [comment]
Json uses characters that aren't allowed in cookie headers so they get url encoded.

**Comment by MohsenEs** [comment]
How can I solve this problem?
I want it to look like this
![2021-07-19_10-10-07](https://user-images.githubusercontent.com/46873097/126108491-72b082d1-2c99-4771-a9d5-bb6e5679cb27.png)

**Comment by Tratcher** [comment]
Then you'll need to write directly to the cookie header like this: 
HttpContext.Response.Headers.Append(HeaderNames.SetCookie, mycookieValueAndProperties):
