### ISSUE TITLE
Hot Reload: Adding a new [Parameter] property to a components code block triggers a restart instead of applying the change at runtime 

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#34480]
### Describe the bug
Hot Reload: Adding a new [Parameter] property to a components code block triggers a restart instead of applying the change at runtime 

![image](https://user-images.githubusercontent.com/18366446/126071173-cefe5d26-2496-4b1a-954f-125650247ced.png)

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new web app using "dotnet new blazorwasm"
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Open Shared/SurveyPrompt.razor
- Add a new parameter property to the code block called "Title2"
- Save the file
- In the console you will see the error "Unable to handle changes to /home/mac/src/blazorwasm/Shared/SurveyPrompt.razor. Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?"

### Expectation
Adding new parameters to a component is a very common task that should be hot reloaded

### Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@MacdonaldRobinson thanks for contacting us.

That might be by design (although I'll let @pranavkm confirm. The reason is the same I mentioned on the previous issue, if you add or remove state from a class (fields) that causes a change on the class layout, which requires a restart.

**Comment by pranavkm** [comment]
@MacdonaldRobinson unfortunately Mono / WASM currently does not support adding custom attributes (the `Parameter`). This is being tracked via https://github.com/dotnet/runtime/issues/52993.

The feature works in .NET Core so this should work with Blazor Server.
