### ISSUE TITLE
Blazor validation: Component's clas attribute [HasSelfValidation] and method attribute [ValidateSelf] missing.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-validation:-Components-clas-attr/1478786)._

---
Many validation problems currently could be settled by allowing the developers to include a custom validation on the form itself.
The (nowadays half-forgotten) EnterpriseLibrary, which was once the driver for attributed validation, had these attributes, which then allowed for a general custom validation. I suggest the implementation of these attributes following the guidance and implementation of EntLib's Validation block.

(I do not see any, why to take refuge to yet another validation component like the fluent validation.)

---
### Original Comments
(no comments)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do in the near future.
