### ISSUE TITLE
Memory leak with repetitive rendering of component

### ISSUE THREAD

**Issue by jivanova** [dotnet/aspnetcore#34528]
### Describe the bug

The example shows a bit extreme scenario with re-rendering component lots of time. However, the impact of the issue increases with adding more complex nested components.

### To Reproduce

https://github.com/jivanova/memory-leak-render

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

**Comment by SteveSandersonMS** [comment]
Hi, thanks for getting in touch.

To check this is definitely a memory leak, could you please first confirm that the memory use grows in an unlimited way? Specifically, if you run it long enough, will the process crash with an "out of memory" error?

The reason I'm asking is that often we get reports about memory leaks which are not really leaks, but rather are just the GC behaving as designed. The GC doesn't collect memory eagerly until sufficient memory pressure builds up. To be sure it's a leak we need to know it will actually crash, or at the very least that you can observe the server process growing from small memory usage to large usage (e.g., 100MB to > 4GB), and that calling `GC.Collect` intermittently does not free up that accumulated memory.

Apologies if this is all familiar info to you and you've already confirmed that it will grow in an unbounded way and eventually crash.
