### ISSUE TITLE
Expose SNI hostname via a feature

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#34525]
We currently do not expose the SNI hostname via a feature interface

https://github.com/dotnet/aspnetcore/blob/640b77f0823f9de872359aa174669efbbd742e72/src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs#L52-L53

```diff
namespace Microsoft.AspNetCore.Http.Features
{
    public interface ITlsHandshakeFeature
    {
+        string? HostName { get; }
    }
}
```

Given that it's already a property on the `TlsConnectionFeature` we can trivially expose it.

**Comment by Tratcher** [comment]
Is it available on http.sys or IIS?

**Comment by shirhatti** [comment]
@alanwest @cijothomas Y'all might be interested in this for https://github.com/open-telemetry/opentelemetry-dotnet/pull/2159 if you wish to add the [`http.server_name` attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attributes).

**Comment by shirhatti** [comment]
@Tratcher Is there somewhere else I should be looking?

https://github.com/dotnet/aspnetcore/blob/640b77f0823f9de872359aa174669efbbd742e72/src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs#L261-L272

**Comment by shirhatti** [comment]
Microsoft.Extensions.Features targets `netstandard2.0` and `net461` which means I can't use a DIM 😢 

https://github.com/dotnet/aspnetcore/blob/23b704915cdb9a73df7a61ff1aaa894712098615/src/Extensions/Features/src/Microsoft.Extensions.Features.csproj#L10

**Comment by Tratcher** [comment]
What are you trying to modify in Microsoft.Extensions.Features? I thought the features you needed to change were in Microsoft.AspNetCore.Http.Features?

**Comment by shirhatti** [comment]
Oops. I meant

https://github.com/dotnet/aspnetcore/blob/23b704915cdb9a73df7a61ff1aaa894712098615/src/Servers/Connections.Abstractions/src/Microsoft.AspNetCore.Connections.Abstractions.csproj#L5

**Comment by Tratcher** [comment]
Ah. I guess we'll have to put it on ITlsConnectionFeature instead.
https://github.com/dotnet/aspnetcore/blob/23b704915cdb9a73df7a61ff1aaa894712098615/src/Http/Http.Features/src/ITlsConnectionFeature.cs#L13

**Comment by shirhatti** [comment]
https://github.com/dotnet/aspnetcore/blob/d1c349f29752ac0718bda7b809ab7fd4f82ca414/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L305-L318

Turns out we never capture the hostname (or set `SslStream` as a feature) if you don't specify a `ServerCertificateSelector`

**Comment by pranavkm** [comment]
```diff
namespace Microsoft.AspNetCore.Connection.Abstractions
{
+    public interface ITlsServerNameFeature
+    {
+        string? ServerName { get; }
+    }
}
```

**Comment by shirhatti** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/35123

**Comment by shirhatti** [comment]
Blocked on https://github.com/dotnet/runtime/issues/57105

**Comment by shirhatti** [comment]
Un-backlogging since we're no longer blocked on runtime

**Comment by avparuch** [comment]
This is a great feature to have. Our service has 20k+ has SNI bindings and having telemetry on which SNI the client chose (as opposed to non-SNI TLS handshake) is valuable for debugging scenarios during customer escalations.

**Comment by Tratcher** [comment]
I found the HttpSys APIs:

```
typedef enum _HTTP_REQUEST_PROPERTY
{
    HttpRequestPropertyIsb,
    HttpRequestPropertyTcpInfoV0,
    HttpRequestPropertyQuicStats,
    HttpRequestPropertyTcpInfoV1,
    HttpRequestPropertySni,
    HttpRequestPropertyStreamError,
    HttpRequestPropertyWskApiTimings,
    HttpRequestPropertyQuicApiTimings,
    HttpRequestPropertyQuicStatsV2,
    HttpRequestPropertyQuicStreamStats
} HTTP_REQUEST_PROPERTY, *PHTTP_REQUEST_PROPERTY;

#if _WIN32_WINNT >= 0x0600

HTTPAPI_LINKAGE
ULONG
WINAPI
HttpQueryRequestProperty(
    _In_ HANDLE RequestQueueHandle,
    _In_ HTTP_OPAQUE_ID Id,
    _In_ HTTP_REQUEST_PROPERTY PropertyId,
    _In_reads_bytes_opt_(QualifierSize) PVOID Qualifier,
    _In_ ULONG QualifierSize,
    _Out_writes_bytes_to_opt_(OutputBufferSize, *BytesReturned) PVOID Output,
    _In_ ULONG OutputBufferSize,
    _Out_opt_ PULONG BytesReturned,
    _In_ LPOVERLAPPED Overlapped
    );

#define HTTP_REQUEST_PROPERTY_SNI_HOST_MAX_LENGTH 255

//
// Flags inside HTTP_REQUEST_PROPERTY_SNI can have following values:
// - HTTP_REQUEST_PROPERTY_SNI_FLAG_SNI_USED: Indicates that SNI was used for succesful
//   endpoint lookup during handshake. If client sent the SNI but Http.sys still decided to
//   use IP endpoint binding then this flag will not be set.
// - HTTP_REQUEST_PROPERTY_SNI_FLAG_NO_SNI: Indicates that client did not send the SNI.
//   If this flag is set, HTTP_REQUEST_PROPERTY_SNI_FLAG_SNI_USED can not be set.
//

#define HTTP_REQUEST_PROPERTY_SNI_FLAG_SNI_USED 0x00000001
#define HTTP_REQUEST_PROPERTY_SNI_FLAG_NO_SNI   0x00000002

typedef struct _HTTP_REQUEST_PROPERTY_SNI
{
    WCHAR Hostname[HTTP_REQUEST_PROPERTY_SNI_HOST_MAX_LENGTH + 1];
    ULONG Flags;
} HTTP_REQUEST_PROPERTY_SNI, *PHTTP_REQUEST_PROPERTY_SNI;
```

**Comment by BrennanConroy** [comment]
Triage:
We can `#if` the new property on an existing interface to workaround netstandard not supporting default interface methods.

**Comment by halter73** [comment]
```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+ #if NETCOREAPP
+     /// <summary>
+     /// Gets the host name from the "sever_name" extension of the client hello if present.
+     /// See <see href="https://www.rfc-editor.org/rfc/rfc6066#section-3">RFC 6066</see>.
+     /// </summary>
+     string? HostName => null;
+ #endif
}
```

Note: We already do a similar `#if` in `ITlsHandshakeFeature` for `NegotiatedCipherSuite`.

https://github.com/dotnet/aspnetcore/blob/6470682c03590c2b8f28aa3e897ce5a604e9e2ab/src/Servers/Connections.Abstractions/src/Features/ITlsHandshakeFeature.cs#L22-L27

**Comment by halter73** [comment]
API Review Notes:

- This was already approved as separate `ITlsServerNameFeature`. Considering we already have `NegotiatedCipherSuite` on the same interface in an `#if NETCOREAPP` without issue, it makes sense to do it again for `HostName`.

API Approved!

```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+ #if NETCOREAPP
+     /// <summary>
+     /// Gets the host name from the "sever_name" extension of the client hello if present.
+     /// See <see href="https://www.rfc-editor.org/rfc/rfc6066#section-3">RFC 6066</see>.
+     /// </summary>
+     string? HostName => null;
+ #endif
}
```

**Comment by halter73** [comment]
We decided that there was no reason to distinguish between the client sending an empty host name using SNI, the client not using SNI, and a server that doesn't support this feature in the PR. The reason the SNI host name is unavailable should not change how it's handled. This means it should be simpler to make `HostName` non-nullable and have the default implementation return the empty string to avoid unnecessary null checks.

Here's the updated API proposal:

```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+ #if NETCOREAPP
+     /// <summary>
+     /// Gets the host name from the "sever_name" extension of the client hello if present.
+     /// See <see href="https://www.rfc-editor.org/rfc/rfc6066#section-3">RFC 6066</see>.
+     /// </summary>
+     string HostName => string.Empty;
+ #endif
}
```

**Comment by halter73** [comment]
API Review Notes:

- Do we need a null value to indicate the server doesn't support this?
  - Maybe, but using a `null` HostName is too subtle for this
  - If it's important we can add a bool. 

API Approved as merged!

```diff
namespace Microsoft.AspNetCore.Connections.Features;

public interface ITlsHandshakeFeature
{
+ #if NETCOREAPP
+     /// <summary>
+     /// Gets the host name from the "sever_name" extension of the client hello if present.
+     /// See <see href="https://www.rfc-editor.org/rfc/rfc6066#section-3">RFC 6066</see>.
+     /// </summary>
+     string HostName => string.Empty;
+ #endif
}
```
