### ISSUE TITLE
GrpcHttpApi Exceptions Not getting Logged

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#34523]
---
**Issue moved from aspnet/AspLabs#363**
- Please respond to @BaleCR7.

---

_From @BaleCR7 on Wednesday, May 12, 2021 7:06:25 PM_

Hi,

I may have missed something, but I don't seem to see exceptions that are being thrown by our Controller being logged on the Server when making HTTP/Rest calls. I do see the exceptions being logged when making grpc calls.

**Comment by BrennanConroy** [comment]
---
**Issue moved from aspnet/AspLabs#363**
- Please respond to @JamesNK.

---

_From @JamesNK on Tuesday, July 20, 2021 2:18:21 AM_

If that is happening then it is a bug that should be fixed.

Error conditions are a place where there hasn't been much testing in GrpcHttpApi.

**Comment by JamesNK** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/43745
