### ISSUE TITLE
JSInterop invocation breaks circuit if canceled during running client script.

### ISSUE THREAD

**Issue by akorenchikov** [dotnet/aspnetcore#34534]
### Describe the bug
JSInterop invocation breaks circuit if it was canceled during javascript execution and a complex object is returned.

### To Reproduce
Interop cancelation will lead to uncatched global exception 
Full project - https://github.com/akorenchikov/CancelInteropProblem 

```
@inject IJSRuntime JSRuntime
<h3 @ref=@headerRef>heading</h3>
@code {
    public class BoundingBox {
        public int Top { get; set; }
        public int Left { get; set; }
        public int Right { get; set; }
        public int Bottom { get; set; }
    }

    ElementReference headerRef;
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        using (var cts = new CancellationTokenSource())
        {
            cts.CancelAfter(100);
           _ = await JSRuntime.InvokeAsync<BoundingBox>("delayedOp", cts.Token, headerRef);
        }
    }
}

```

```
function delayedOp(el) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(el.getBoundingClientRect());
                }, 1000);
            });
        }
```

I have found that manual serializing/deserializing allow to avoid global exception but it's significantly reduces interop capabilities

```
            return JsonSerializer.Deserialize<BoundingBox>(await JSRuntime.InvokeAsync<string>("delayedOpWA", cts.Token, headerRef));
```

```
function delayedOpWA(el) {
            return new Promise((resolve) => {
                setTimeout(() => {
                    resolve(JSON.stringify(el.getBoundingClientRect()));
                }, 1000);
            });
        }
```

### Exceptions (if any)

Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments) in Microsoft.JSInterop.dll:token 0x600004f+0x90

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.5.21302.13 [/usr/local/share/dotnet/sdk]

**Comment by g-spot** [comment]
April 2022 - this is still an issue causing errors in productive applications. Could you please start fixing it?

**Comment by crui3er** [comment]
This issue seems to be fixed. Not reproducible.
