### ISSUE TITLE
Blazor: Calling EventCallback from @onclick eventhandler, vs from JSInvokable method causes different rerendering of parent

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#34532]
this is probably not a bug, but I couldn't find an explanation in the docs or a workaround.

### Describe the issue
I have a CustomInput component, where I want to invoke ValueChanged callback from JSInterop method:

```csharp
[JSInvokable]
public void IncrementJsInterop() => Increment();

public void Increment()
{
    Value++;
    // This is how InputBase.cs implements callback and EditContext:
    _ = ValueChanged.InvokeAsync(Value);
    EditContext.NotifyFieldChanged(FieldIdentifier.Create(ValueExpression));
}
```

The problem is, that the parent component (listening to ValueChanged) will rerender immediatelly after ValueChanged is invoked and won't reflect changes to EditContext made by next statement: ` EditContext.NotifyFieldChanged(...)`;

However, if I call the same method from native blazor eventhandler, e.g. `@onclick="Clicked"`, the parent is rerendered correctly:

```csharp
void Clicked() => Increment();
```

### To Reproduce

1. Go to https://blazorrepl.com/repl/GlkBFqbH07Y1YMo029
2. Click the "Increment using JS Interop" button => IsModified stays false (it should be true). Click again and will become true;
3. Refresh the page and try the same with "Increment using C# Event handler" button. IsModified will become true immediately after first click.

![LDlHB](https://user-images.githubusercontent.com/3494407/126287473-780d00c2-cda5-4f5d-9b38-9faeaf16a23d.gif)

### The question:

How do I correctly invoke the ValueChanged callback from a JSInterop method, so that the consumer will rerender after EditContext.NotifyFieldChanged() is called?

### Further technical details
- ASP.NET Core version: 5.0.6
- Include the output of `dotnet --info`

      .NET SDK (reflecting any global.json):
       Version:   5.0.300
       Commit:    2e0c8c940e
      
      Runtime Environment:
       OS Name:     Windows
       OS Version:  10.0.19042
       OS Platform: Windows
       RID:         win10-x64
       Base Path:   C:\Program Files\dotnet\sdk\5.0.300\
      
      Host (useful for support):
        Version: 5.0.6
        Commit:  478b2f8c0e

**Comment by javiercn** [comment]
@Liero thanks for contacting us.

That's by design, EventCallback does additional work to trigger a re-render of the component defining the callback, while JS interop can't do that.

**Comment by Liero** [comment]
So what is your advice when updating value from a JS interop? That is a pretty normal requirement, isn't it?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. When calling methods through JSInterop, the `StateHasChange` isn't called automatically (which is the case when called through some action UI action in the page). Consider calling StateHasChanged manually.

**Comment by Liero** [comment]
Wait a moment. I still see no solution to the problem. 

I can call the StateHasChanged in the CustomInput component, but it does not solve the problem with the consumer (parent) component rendered prematurely. The parent component has no knowlegde about whether the callback is invoked from JSInterop or a EventCallback.
