### ISSUE TITLE
WebApplicationBuilder should register the developer exception page in the pipeline by default for Development environment

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#34548]
The `WebApplicationBuilder` should automatically register the `DeveloperExceptionPageMiddleware` in the pipeline by default. The middleware should be added before any other middleware in the pipeline and only when the current environment is development, i.e. when `IWebHostEnvironment.IsDevlopment() == true`.

The empty web template should be updated as part of this to remove the existing lines of code that explicitly add the middleware to the pipeline from the application, e.g.:

``` diff
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

-if (app.Environment.IsDevelopment())
-{
-    app.UseDeveloperExceptionPage();
-}

app.MapGet("/", "Hello World");

app.Run();
```

**Comment by Tratcher** [comment]
Hardcoding environment checks in the runtime has been an ongoing complaint for people that define their own environments. https://github.com/dotnet/aspnetcore/issues/28937.

The standing recommendation is for there to be an intermediate option people can set to control runtime behaviors, but it could default to IsDevelopment.

In this specific example the workaround isn't bad, they can call UseDeveloperExceptionPage themselves, but they'll also have to call UseRouting to fix the ordering which is a discoverability issue. Is this change intended to work around https://github.com/dotnet/aspnetcore/issues/34146?

**Comment by DamianEdwards** [comment]
This isn't related to the `UseRouting` issue as that pertains to `UseExceptionHandler` not `UseDeveloperExceptionPage`
