### ISSUE TITLE
Update the version of Swashbuckle.AspNetCore in the webapi template

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#34558]
The version of [Swashbuckle.AspNetCore](https://www.nuget.org/packages/Swashbuckle.AspNetCore) referenced in the [webapi template](https://github.com/dotnet/aspnetcore/blob/c754959e7133c4cf9e1fbaa610a2db2a7cb1399d/eng/Versions.props#L258) is quite [out of date](https://www.nuget.org/packages/Swashbuckle.AspNetCore/6.1.4) (5.6.3 vs. 6.1.4) and should be updated for the .NET 6 release to the latest version.

Note that we have some in-progress work (see #34514) that will likely impact Swashbuckle itself so we shouldn't update the version we reference in the template until we know the outcome of that and what impact it has on the version.

**Comment by captainsafia** [comment]
Note: We probably want to update it to 6.1.5 now since that release contains the fixes we need.
