### ISSUE TITLE
[Blazor] Immutable parameters

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#34552]
Hi,

I'd like to propose a concept of an "immutable" parameter that could be annotated with an attribute. Once the component is initialized, the parameter cannot be set and an exception is thrown. At the design time, user should be able to see an indication that the specified parameter is immutable.

There are several use cases where this is helpful. Certain complex components that I have developed use parameters to configure the initial behavior of a component and after that point it does not make sense to alter that behavior.

Thank you for your consideration.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

This is not something we plan to implement, we offer a `ComponentBase` with a set of defined behaviors that you can use. If you are missing some functionality or don't like any of the conventions we use, we recommend you create your own base class for use in your components and implement your own semantics there.

For example, for the case you are dealing with, you can implement this by overriding `SetParametersAsync` to make the check for parameters there.
