### ISSUE TITLE
Blazor Hot Reload not working

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#34566]
I'm using the latest preview of VS 2022 and I have a Blazor app -asp.net core hosted-. When I run the app -F5- say I change something in CSS, it doesn't do anything. No matter if you save, or click the Apply Code Changes button.

**Comment by pranavkm** [comment]
Could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report this issue? It would help route the issue to the right team in VS.

**Comment by ylr-research** [comment]
Sure thing
