### ISSUE TITLE
OutOfProcess hangs in app.Run with 6.0 templates

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#34565]
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1358358 for the original issue

IISExpress in OutOfProcess mode seems to hang in app.Run, possibly related to https://github.com/dotnet/aspnetcore/issues/34403

**Comment by davidfowl** [comment]
I debugged this and have found the issue. It's unrelated to #34403. The issue here is that we're not preserving calls to `UseUrls` during calls to `ConfigureWebHostDefaults` in the implementation of the `WebApplicationBuilder`.
