### ISSUE TITLE
Double-check of FileInfo in SendFileFallback causes issues in templating

### ISSUE THREAD

**Issue by nibblesnbits** [dotnet/aspnetcore#34575]
I've written a custom `IFileProvider` that does in-line replacements of file contents based on the incoming request.  This worked back in .NET Core 2.2, but has since broken due to https://github.com/dotnet/aspnetcore/pull/12328.

The offending lines are below.

https://github.com/dotnet/aspnetcore/blob/62e157b94276bf6e607546b0a46b283f7a6a9b92/src/Http/Http/src/SendFileFallback.cs#L30-L39

Is there a new suggested approach if I need to send a modified or different file from a custom `IFileProvider`?  Also, is it stricly necessary to have this check at all?

**Comment by Tratcher** [comment]
Are you using your custom IFileProvider with the StaticFile middleware? If the file length has been modified then your response has a mismatched Content-Length which can lead to protocol violations and failed responses.

Note the above code path is only hit if your IFileInfo preserves the original PhysicalPath property. If you're modifying the contents in the Stream then you'll want to remove the PhysicalPath property and update the length.
https://github.com/dotnet/aspnetcore/blob/62e157b94276bf6e607546b0a46b283f7a6a9b92/src/Http/Http.Extensions/src/SendFileResponseExtensions.cs#L115-L138

Have you considered doing this kind of inline processing in an MVC controller or custom middleware instead?

**Comment by nibblesnbits** [comment]
Yes, I am feeding that custom `IFileProvider` to the StaticFile middleware.  I had no idea I could just not return a `PhysicalPath`!  I'll update that and get back to you.

**Comment by nibblesnbits** [comment]
That totally works!

Would it make sense to put together something for the docs on a task like this?  I can throw up a small example repo of my current code to ensure it's not a totally off-the-rails approach if need be.

**Comment by Tratcher** [comment]
Feel free, I doubt we have much coverage for custom file providers.

**Comment by nibblesnbits** [comment]
Will do!  I'll link my repo here tonight and work on the docs soon.

**Comment by nibblesnbits** [comment]
Here's a quick-and-dirty demo: https://github.com/nibblesnbits/TemplateFileProviderDemo

**Comment by Tratcher** [comment]
404? Is it private?

**Comment by nibblesnbits** [comment]
I've updated the visibility.  It is public now; my mistake.

**Comment by Tratcher** [comment]
That's an interesting setup, I'm glad it works for you. I don't know that I'd recommend to the general public integrating dynamic content into the static file provider like that, it breaks some of the assumptions about immutability, cachability, range support, etc.. I hope your files aren't very big or else this would be really expensive to do on demand. You still might want to consider some caching logic like:
A) caching the original file in memory so you don't have to read it off the disk every time.
B) caching some of the templated results by host name so you don't have to keep regenerating them.

One alternative to consider is razor views. If everything is HTML anyways then it might be simpler to turn them into cshtml files and dynamically insert the content that way. That engine should be more efficient for templating than what you're using here.

**Comment by nibblesnbits** [comment]
That makes sense.  The impetus behind this originally was some really strange requirements due to a WordPress setup that's calling a .net core API that also serves up some JavaScript files that I need to update dynamically.  It's kind of a mess all the way around, but I learned a lot in the process.
So if I tweak this to just be static replacements and maybe throw some minimal caching in front of it with the relevant parts be acceptable for a documentation page?
________________________________
