### ISSUE TITLE
Blazor WebAssembly: Error parsing 'integrity' attribute ('undefined')

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#34571]
Repro steps:

- Install .NET 6 RC1 (6.0.100-rc.1.21370.2)
- `dotnet new blazorwasm`
- `dotnet run`

Expected result: App runs fine

Actual result:

Errors in the browser dev console:

Error parsing 'integrity' attribute ('undefined'). The hash algorithm must be one of 'sha256', 'sha384', or 'sha512', followed by a '-' character.
GET https://localhost:5001/_framework/undefined net::ERR_ABORTED 404

![image](https://user-images.githubusercontent.com/1874516/126409638-b0bdca09-14ed-4ca0-a18b-68e23271565d.png)

**Comment by danroth27** [comment]
@javiercn Is this possibly related to the static web asset changes?

**Comment by mkArtakMSFT** [comment]
Thanks @danroth27. This has been reported earlier by our CTI testing. https://github.com/aspnet/AspNetCore-ManualTests/issues/765

**Comment by javiercn** [comment]
https://github.com/dotnet/sdk/pull/19080
