### ISSUE TITLE
Swashbuckle CLI

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/aspnetcore#34593]
Execution of the Swashbuckle CLI to create an OpenAPI document on build/publish fails. This issue in the Swashbuckle repo represents the description and repro outline. 

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2168

**Comment by mkArtakMSFT** [comment]
@rafikiassumaniMSFT FYI

**Comment by davidfowl** [comment]
@rafikiassumaniMSFT @bradygaster  Marked as P0 because it breaks an existing scenario with new Web API projects (outside of minimal actions).

**Comment by davidfowl** [comment]
@bradygaster assigning this to you.

**Comment by bradygaster** [comment]
I have verified this works with the preview bits I obtained from Swashbuckle. I am chatting with @phil-allen-msft and he's looking at this on the publishing flow. From my side I can verify I can use the preview CLI bits to generate an OpenAPI description file from an assembly containing a minimal API project

**Comment by phil-allen-msft** [comment]
Correct; Visual Studio publishing of API using Swashbuckle will need to make some updates in order to handle the minimal API project.
