### ISSUE TITLE
Add DateOnly and TimeOnly support to model binding & routing

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#34591]
- Required for Blazor/MVC
  - [ ] Model Binding
  - [ ] Blazor Routing
  - [ ] Regular Routing

**Comment by davidfowl** [comment]
I want to mention that the TryParse heuristic that we added in minimal API means we support these out of the box 😄

**Comment by pranavkm** [comment]
Hmm, your comment reminded me that we want to special case DateTime. The default `DateTime.Parse` (and I imagine `DateTime.TryParse`), formats the date to a server local time. We had to author a model binder in MVC to parse it as UTC. @DamianEdwards did some research on this: https://github.com/dotnet/aspnetcore/issues/11584#issuecomment-506007647

**Comment by srpeirce** [comment]
Is this the reason I get the following error when returning `DateOnly` when returning via controller? Or should I raise a separate issue.

```
System.NotSupportedException: Serialization and deserialization of 'System.DateOnly' instances are not supported and should be avoided since they can lead to security issues. Path: $.Date.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.DateOnly' instances are not supported and should be avoided since they can lead to security issues.
 ```
 
🤔
![image](https://user-images.githubusercontent.com/12847647/133770991-196b99fa-44df-48a0-a172-4c9c65352909.png)

**Comment by DamianEdwards** [comment]
Seems that's from the underlying serializer in `System.Text.Json`, see this issue dotnet/runtime#53539

**Comment by maxkoshevoi** [comment]
@srajkovic Here's a workaround if you're interested: https://kevsoft.net/2021/05/22/formatting-dateonly-types-as-iso-8601-in-asp-net-core-responses.html ([NuGet](https://github.com/maxkoshevoi/DateOnlyTimeOnly.AspNet))

@DamianEdwards `DateOnly/TimeOnly` promise to be popular types, and currently (as of RC1) Asp.Net doesn't support them as both body (dotnet/runtime#53539) and query (https://github.com/dotnet/runtime/issues/59253) parameters. Both can be worked around with something like [this](https://github.com/maxkoshevoi/DateOnlyTimeOnly.AspNet), but shouldn't Asp.Net support it out of the box until runtime catches up in .Net 7? I feel like this will be a common issue after the release of .Net 6.

**Comment by srajkovic** [comment]
@maxkoshevoi, I think you meant to tag @srpeirce. DateOnly and TimeOnly look great though!

**Comment by mkArtakMSFT** [comment]
@rafikiassumani-msft some of this work will be an ask from your team for .NET 7.

**Comment by danroth27** [comment]
At this point we don't believe this will make it into .NET 7. Moving to .NET 8.

**Comment by maxkoshevoi** [comment]
Seems like everything except using TimeOnly as a dictionary key (fix is already merged for .NET 8) is working out of the box in .NET 7

**Comment by Nick-Stanton** [comment]
Closing this issue since it's been a month and it appears that DateOnly and TimeOnly already work in .NET 7 with the addition of the TryParseModelBinder
