### ISSUE TITLE
.SCSS files should support `@use` directive since `@import` is obsolete

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#34610]
I'm working on same Blazor components and now need some common CSS styles across multiple components. It is perfect fit for SCSS styles which is supported by Visual Studio. However I cannot reference .scss files in the recommended way with `@use` . Since VS 2019 shows error.  **Only the old and now obsolete `@import` works.**

![image](https://user-images.githubusercontent.com/7632824/126595639-d06f3e49-f259-4125-821c-f1f4b3309b2b.png)

See [@use docs](https://sass-lang.com/documentation/at-rules/use) which is replacing the [obsolete @import](https://sass-lang.com/documentation/at-rules/import).

![image](https://user-images.githubusercontent.com/7632824/126595442-bcadc1fd-a3f6-42c7-af3c-b76c0b49e003.png)

_**Please make `@use` supported before lots of projects might break when `@import` removed!**_

**Comment by javiercn** [comment]
@majorimi thanks for contacting us.

This is not something that this team works on. In order for you to get a better and faster response we suggest you create an issue via the report a problem dialog in visual studio. See details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
