### ISSUE TITLE
`The Line Number Specified is Missing or Invalid` Error `CS1576`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#34623]
![image](https://user-images.githubusercontent.com/14852843/126683287-f63a14ca-04a4-4051-b3c0-9b12877e2a06.png)

Getting this in VS 16.11 P3 & 17.0 P2, even after cleaning/rebuilding. Also tried manually purging the build artifacts.

It's building successfully on the cmd line so I believe this may be tooling specific.

```c#
#line (8,21)-(8,28) 24 "C:\aspnetcore\src\Components\Samples\BlazorServerApp\Pages\Counter.razor"
__builder.AddContent(6, Message);
```

**Comment by mkArtakMSFT** [comment]
Looks like you will need to use VS 17 Preview3.

**Comment by TheCakeMonster** [comment]
I didn't have this problem with the preview versions, but I do now with the 16.11 GA. It looks like there is something a bit unusual about how 16.11 interacts with .NET 6 previews. 16.11 + .NET 6 preview 7 triggers this error message.

I've got it going again by pinning the solution by disabling the use of pre-release SDKs using global.json, but I wonder if others will still be struggling with the problem.

**Comment by bairog** [comment]
@TheCakeMonster In my situation (ASP Razor Pages project, Visual Studio 2019 16.11.1 + .NET 6.0 preview 7) I get on build:
> error : System.IO.DirectoryNotFoundException: Could not find a part of the path 
 D:\Tabit.NET\Tabit.Web\obj\Debug\net6.0\StaticWebAssets.build.json'.
