### ISSUE TITLE
VS4Mac seems to be unreliable with dotnet-watch

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#34621]
VS4Mac 8.10.5.16

.NET info:

<details><pre>
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.4
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.410 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.5.21302.13 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</pre></details>

Given a simple Blazor page:

```Index.razor
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.
```

…and `dotnet watch --verbose`, making changes to this page from within VS4Mac seems to work very unreliably.

If I:

1. make a change from within VS
2. hit cmd-S

, nothing happens _most of the time_. `dotnet watch` doesn't seem to know anything has happened.

If I then:

1. make the same change from within VS
2. hit cmd-S
3. open that file in a different text editor (either `nano` or TextMate will do), which notices the change
4. hit cmd-S _there_

, `dotnet watch` picks up the change.

I'm guessing VS doesn't set some file attribute (modification date?) that dotnet-watch looks for, but I'm not sure.

I've also tried enforcing different line endings or encodings to no avail.

**Comment by mkArtakMSFT** [comment]
We've made a lot of improvements in this area in .NET 6. Please update to the latest .NET 6 RTM release. If you still face similar issues, please file new issues with more details.
