### ISSUE TITLE
Handle RedisConnectionException and SocketException by reconnecting in Microsoft.Extensions.Caching.StackExchangeRedis

### ISSUE THREAD

**Issue by rpanand24** [dotnet/aspnetcore#34642]
### Is your feature request related to a problem? Please describe.
Handle RedisConnectionException and SocketException by reconnecting in Microsoft.Extensions.Caching.StackExchangeRedis

Currently the _cache object get recreated only when it is being disposed or null. Is it possible to do a force reconnect when there are exceptions like RedisConnectionException and SocketException ?

### Describe the solution you'd like
Already there is a doc available for the reconnect logic here https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-dotnet-how-to-use-azure-redis-cache#connect-to-the-cache

**Comment by BrennanConroy** [comment]
StackExchange should be reconnecting automatically, are you seeing issues where this is not the case?

**Comment by rpanand24** [comment]
Hi,

Ours is a high transactional environment and we are using our own cache wrapper (almost identical to Microsoft.Extensions.Caching.StackExchangeRedis). But noticed that these connection exceptions are logged and no data is returned.  

Sorry if it a stupid question … if StackExchange does a reconnection automatically for these exceptions, why this below doc explaining about the force reconnection logic. 
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-dotnet-how-to-use-azure-redis-cache#connect-to-the-cache

**Comment by shirhatti** [comment]
We use the default retry policies used by StackExchange.Redis as outlined in their docs- https://stackexchange.github.io/StackExchange.Redis/Configuration.html#configuration-options

If you want to customize the retry logic, you can always do so. For example,
```csharp
builder.Services.Configure<RedisCacheOptions>(options =>
{
    options.ConfigurationOptions = new StackExchange.Redis.ConfigurationOptions()
    {
        ReconnectRetryPolicy = new ExponentialRetry(5000),
        ConnectRetry = 3
    };
});
```

The linked Azure Cache for Redis doc makes recommendation when their service. The best configuration will be workload dependent and we can't make any blanket recommendations on what you should do.
