### ISSUE TITLE
ViewModel data bound is empty in View when using Form Ajax for inserting record

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34650]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ViewModel-data-bound-is-empty-in-View-wh/1471917)._

---
Hello,

I am trying to get the key field from a view model in the View page after performed a database insert transaction via Ajax Form. When I use VS debugger in my view page, I can see it has a value in it but the hidden field for storing it always shows empty. I am not sure what is going on. 

Below is my code in brevity:

**Controller**:

public IActionResult SubmitProcFormAdd(ProcFormModi getEP)
        {
// perform database insert transaction and save the indentity key
getEP.Tracking = Convert.ToInt32(cmd.ExecuteScalar());  // using VS debugger, I can see the identity key value created here no problem.

return PartialView("_ProcFormAdd", getEP);
        }

----------0-----------------------

**Partial View**:

@model myNetCore.Areas.Statistics.Models.ProTrackingVM.ProcFormModi

<input type=hidden id=savedTracking value="@Model.Tracking"> // this hidden field is used to store the key id of the record after inserting it to the database.

<form id=epModiFormAdd data-ajax-begin=onBeginMo data-ajax-complete=onCompleteMo data-ajax-failure=onFailed data-ajax-success=onSuccess data-ajax=true data-ajax-method=POST>

<input type=hidden> // I use this option to ensure this model field is always updated for controller.

........

</form>

**View Model**:

public class ProcFormModi 
        {
            public string Option { get; set; }
            public string Tracking { get; set; }
          .......
         }

Can someone please help me out. I don't understand why the Model.Tracking is empty in View when I did see the value in it using VS debugger in Controller during the insert transaction. The database table does show the newly inserted record as well.

I use VS 2019 and .Net 5.

Thanks in advance.

---
#### Feedback Bot on 7/12/2021, 01:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/12/2021, 02:29 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
