### ISSUE TITLE
Asp net 5 razor pages:  the combined management of asynchronous tasks as synchronous is an incomprehensible hell

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34654]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Asp-net-5-razor-pages:--the-combined-man/1457427)._

---
I spent weeks if not months trying to combine asynchronous methods with synchronous code.
For example, the properties of the razor pages cannot call asynchronous methods (await) as also from the razor code of the pages, this problem forces the use of the waiting methods (blocking) of the Task (eg. the application blocking (Task deadlock).
I tried to combine Action / s together with Task Factory (ex. StartNew) which some cases manage to complete the Task synchronously but I found 2 hellish problems:
- Using repeated actions causes memory problems. it is sufficient to do a waiting cycle that creates Actions reaching several Gb of ram in a few seconds!
- The use of other Task Factory queues to complete the Task synchronously can cause the death of the same task or the failure of the creation of a new task (ex. StartNew) without reporting errors or other signals, it simply continues execution of the code ignoring the start of the Task to be completed !! .. simply scary!

After giving up generalized intelligent procedures to fall back on ad hoc calibrated procedures to solve the various problems mentioned above, I point out another scary problem by combining correctly called asynchronous procedures (through await) that when the HttpClient.PostAsync method is invoked (always with await ) causes the chain separation (await) by generating a secondary task for PostAsync while the main task jumps and continues without a result or even errors !! .. this behavior is very dangerous !!!

In my humble opinion this problem should be handled automatically within the framework because it is not possible for the developer to continually worry about the possibility that the Task executed in synchronous mode (Wait, RunSynchronously, Result, .etc.) May cause the deadlock resulting in failure of the application with unpredictable results !!

I sincerely hope that a solution to this problem will be found through the automatic creation of queues (TaskFactory) or Thread, or any other mechanism that solves the problem even at the expense of performance or resources.

Thank you.

---
#### Feedback Bot on 6/22/2021, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/23/2021, 01:11 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This feedback doesn't seem actionable in its current form.
If you can rephrase this in more detailed and targeted ask, we can take a look.
