### ISSUE TITLE
To change views namespace during compilation

### ISSUE THREAD

**Issue by wtujvk** [dotnet/aspnetcore#34666]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to change views namespace during compilation but many class is internal, cannot to be use in other library.

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

At 'Microsoft.AspNetCore.Razor.Language.DefaultRazorIntermediateNodeLoweringPhase',  to get view namespace like this:
`var importedUsings = ImportDirectives(document, builder, syntaxTree.Options, imports);`
![image](https://user-images.githubusercontent.com/17868266/126855370-812fa411-05a3-45a8-9a5d-011787b99384.png)

I want to copy and  override the method 'ExecuteCore' by use parameter 'importedUsings'.
To remove part  namespace in view  by condition.

### Additional context
netcoreapp3.1, 3.1.15

**Comment by javiercn** [comment]
@wtujvk thanks for contacting us.

We don't support extending the razor compiler and we don't plan to make changes to support extensibility for the time being.
