### ISSUE TITLE
Allow Command flag in redis caching

### ISSUE THREAD

**Issue by khanhna** [dotnet/aspnetcore#34669]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I'm in a scenario that using heavy read on redis (just occassionnaly write compare to read). So for the sake of simplycity, i choose redis replication implement method, and suddenly realize that redis caching extension is not support for command-flag passing along.

### Describe the solution you'd like
An optional command flag that allow passing along, default to none for Get method. So that those want to use them can benefit from the sake of load-balancing by using [CommandFlags.PreferSlave], or whatever the case it is. Otherwise the current default behavior is the same.

### Additional context
![image](https://user-images.githubusercontent.com/47200526/126857632-e8381d23-9360-4359-9eb0-71ff98ae2b5a.png)
netcoreapp 3.1, net5.0

**Comment by Tratcher** [comment]
That HashMemberGet API is internal. Where would you want this command flag exposed for you to pass it in?

**Comment by khanhna** [comment]
This is the full flow that i'm trying to achieve.

First, I want another interface such as [IRedisDistributedCache] that inherit from [IDistributedCache] interface to expose 2 additional Get API with optional [CommandFlags]. The current set API it's still ok cause if i'm not wrong, the default flag for set command is DemandMaster, which is right for all kind of cluster.
I think we shouldn't put them directly on [IDistributedCache] interface cause it make the root interface specific for redis but not others implementation.
![image](https://user-images.githubusercontent.com/47200526/127076926-ac166f1a-51e3-4746-850f-ddb88b9bb29a.png)

Then, re-implement the new interface with [RedisCache] implement instance:
![image](https://user-images.githubusercontent.com/47200526/127077009-affd41a4-0fbf-4ed5-9c09-22a02d6e043f.png)

Apply the 2 new contract:
![image](https://user-images.githubusercontent.com/47200526/127077047-79f1361a-73ce-43ae-b59d-97f3ab021aa6.png)

Then allow the command flag to passing-in for 2 helper helper in private
![image](https://user-images.githubusercontent.com/47200526/127077164-41f1f4af-6735-489e-9f99-b6247f963d03.png)

Then it got passed to the [HashMemberGet] API. which you already mentioned.

And final step, little modify on the collection extension (serve for native DI)
![image](https://user-images.githubusercontent.com/47200526/127077277-da523e79-6791-4776-b907-6491dbe48e8c.png)

That's all.
I'm not hesitate to submit a PR if you guys kind of busy these days.

Happy coding 🍨

**Comment by Tratcher** [comment]
When you start needing redis specific commands like this you should be using StackExchangeRedisCache directly. We don't intend to extend the IDistributedCache abstraction to support redis specific commands.

**Comment by khanhna** [comment]
I just though that would be nice, and reasonable too, for the extension with specific naming end with [Caching.StackExchangeRedis].
Cause i'm not extend the IDistributedCache abstraction, but to inherit to another specific interface.
Or maybe i'm just confuse assuming the [Caching.StackExchangeRedis] extension is specific target to implement Distributed cache by Redis but turns out it's not as close to the redis as i though.

But thank you for a fast response.
Have a nice day.
