### ISSUE TITLE
Signalr .Net client HubConnection is not starting on Xamarin Forms Android and Local Network

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#34673]
I have this code in a library
```csharp
var clientHandler = new HttpClientHandler
            {
                ClientCertificateOptions = ClientCertificateOption.Manual,
                ServerCertificateCustomValidationCallback = (msg, cert, certChain, policyErrors) => true
            };
 _connection = new HubConnectionBuilder()
                        .WithUrl(url, o =>
                        {
                            o.HttpMessageHandlerFactory = _ => clientHandler;
                            o.Transports = HttpTransportType.WebSockets;
                        })
                        .WithAutomaticReconnect()
                        .Build();
```

Here are some facts

- The service is running as a console app, No IIS
- I am using https and local network IP: https://192.168.1.2:6000
- Port 6000 is open for inbound connection and TCP protocol on the firewall
- The code works find from a console app
- I am running Android Pixel emulator on windows in a Xamarin Forms app
- The service has controllers beside the hubs, and Android succeeds to do http calls against the controllers

### The problem:

- If we remove `HttpMessageHandlerFactory` configuration, we will get SSL validation error when calling `HubConnection.StartAsync`

**Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/boringssl/ssl/handshake_client.c:1132**

- If we keep `HttpMessageHandlerFactory` configuration as above, we get this error when calling `HubConnection.StartAsync`

**Unable to connect to the server with any of the available transports. (WebSockets failed: Unable to connect to the remote server) (ServerSentEvents failed: The transport is disabled by the client.) (LongPolling failed: The transport is disabled by the client.)**

### Workaround
Replace the local network ip in the uri with android localhost `$"https://10.0.2.2:{baseUri.Port}"` and run the emulator on same machine with the service then it will work

**Comment by BrennanConroy** [comment]
>Android succeeds to do http calls against the controllers

What does your code look like for that? SignalR isn't do anything special here, we just create an HttpClient and send requests over it.

**Comment by MhAllan** [comment]
"Android succeeds to do http calls against the controllers" .. I give that info to know that HttpClient can reach the server, but SignalR client can't.

**Comment by BrennanConroy** [comment]
> I give that info to know that HttpClient can reach the server, but SignalR client can't

Right, that's why I am asking what your HttpClient code looks like. Because SignalR is using HttpClient internally and doesn't do anything crazy with it so it should work the same.

> * If we keep `HttpMessageHandlerFactory` configuration as above, we get this error when calling `HubConnection.StartAsync`

Missed this part, you will need to also configure the WebSocket to allow all certs via `o.WebSocketConfiguration` (https://docs.microsoft.com/dotnet/api/system.net.websockets.clientwebsocketoptions?view=net-5.0)
