### ISSUE TITLE
Add RequireEntropy in PasswordOptions 

### ISSUE THREAD

**Issue by mikhail-khalizev** [dotnet/aspnetcore#34697]
Currently, `Microsoft.AspNetCore.Identity` in `PasswordOptions` provides different options for checking password complexity.

I propose to add a new, more modern one - the requirement for the complexity of the password in bits.

How it works. See which classes are contained in the original password. Next, the entropy of the class is taken and multiplied by the number of characters of this class in the original string.

For example, for arabic numerals (0-9) the entropy per character is 3.322 bits.
Accordingly, a password of, say, 20 random numbers has an entropy of 66.44. Which can be considered a rather complex password, despite the fact that it does not contain the alphabetic characters 'a' - 'z'.

**Comment by blowdart** [comment]
What benefit do you believe this would give users? You can already create custom password validators and check entropy yourself by registering an instance of IPasswordValidator. In fact we run through all validators, so you can have multiple ones.

**Comment by mikhail-khalizev** [comment]
The main thing is to protect against using a simple password. And at the same time, allow users to use the symbols at their discretion.

That is, at the moment, the requirement is set strictly - there must be a certain length of the password and certain symbols.

And this change will allow the use of a soft restriction - characters can be any, and the minimum password length depends on the class of characters used.

**Comment by mikhail-khalizev** [comment]
That is, the user may not like using capital letters or special characters, for example. But now, if the programmer has laid down such a restriction, then the user simply has no choice but to obey.

And this change will allow you to meet the user halfway and take into account his wishes.

**Comment by marwalsch** [comment]
@mikhail-khalizev Have you considered forcing your users to simply use passphrases? A high minimum password length of at least a dozen characters (perhaps with an additional high amount of variant characters) should offer a considerably high entropy without enforcing upper case, numeric or special characters.

**Comment by mikhail-khalizev** [comment]
This is a good idea. I didn't think about that.
