### ISSUE TITLE
Blazor component with generics incorrectly invokes Func<T[]> that is a parameter

### ISSUE THREAD

**Issue by julian-altech** [dotnet/aspnetcore#34711]
If a generic component has a parameter property:
```csharp 
@typeparam T

@code {
    [Parameter]
    public Func<T[]> GetItems { get; set; }
}
```

When you use the component the GetItems will cause a build fail with the error "The type or namespace name T could not be found" since it generates this code for the page:
```csharp 
__builder.OpenComponent<BlazorTest.Client.Shared.GenericComponent<string>>(0);
__builder.AddAttribute(1, "GetItems", new System.Func<T[]>(GetItems)
````

But there is no definition of T there as T is defined on the comonent, it should generate as string[] not T[]

### To Reproduce
With the component above create the following page
```csharp
@page "/"

<GenericComponent T="string" GetItems="GetItems" />

@code {
    string[] GetItems() => new[]
    {
        "Foo", "Bar"
    };
}
```

As soon as you try to compile it will fail

I have tested this on 6.0.0-preview.6.21355.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in the upcoming 6.0-preview7 release.
That was fixed as part of #33357

**Comment by campersau** [comment]
@mkArtakMSFT I am not sure if they are really the same. This issue is about generic type parameters in combination with arrays which currently aren't supported. See PR #34734

**Comment by julian-altech** [comment]
> As a workaround use a `Func<IList<T>>` / `Func<List<T>>` / ... instead

I hadn't thought about trying that, switching to IList<T> has worked 100% and I don't have to change much other than some declarations through my layers. Thanks!
