### ISSUE TITLE
Cant scroll down in form of Counterpart 

### ISSUE THREAD

**Issue by VimalRaj09** [dotnet/aspnetcore#34720]
Cannot able to scroll up or down in counterpart form 

### To Reproduce
Login
Go to PDCA Module 
Go to Counterpart 
edit form
![counterpart bug](https://user-images.githubusercontent.com/84838341/127020189-76484761-3f64-4658-b195-8a89a3e7e7ef.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Did you file this issue in this repo intentionally, or was it a mistake?
If so, we will need more details about your scenario, what you're trying to do and what is not working in the framework.
Also, we'll need a minimalistic repro app to be able to reproduce the issue. Note, that app will have to be based off of new project template.
