### ISSUE TITLE
[Perf] SoD Regression in Microsoft.AspNetCore.Components.Web.dll

### ISSUE THREAD

**Issue by Tohron** [dotnet/aspnetcore#34736]
### Description

I have observed further regressions in the SoD for Microsoft.AspNetCore.Components.Web.dll in New Blazor Template - Publish.  There was also a minor regression in blazor.webassembly.js in New Blazor Template - Publish.

### Regression?

Microsoft.AspNetCore.Components.Web.dll regressed by 3kB(15%),  blazor.webassembly.js regressed by 1.18 kB (2%)

### Data

<html>
<body>
<span style="color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">### Run Information</span>

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | 1a84b29e367493c50dc979d7897a386734b8fd7f
Compare | bd3fb963e701743eb6847b898eda8571ead97155
Diff | Diff

</body>
</html>

<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Regressions in SOD - New Blazor Template - Publish</h3>

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/blazor.boot.json.gz | 1.88 KB | 1.86 KB | 0.99 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Logging.dll.br | 6.98 KB | 6.89 KB | 0.99 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Configuration.Abstractions.dll.br | 2.01 KB | 1.96 KB | 0.98 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.JSInterop.dll.gz | 14.87 KB | 15.12 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/blazor.webassembly.js | 53.81 KB | 54.99 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.gz | 8.31 KB | 9.56 KB | 1.15 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.WebAssembly.dll | 56.50 KB | 57.50 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/blazor.webassembly.js.gz | 17.01 KB | 17.38 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.timezones.blat.gz | 72.05 KB | 73.73 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.br | 7.03 KB | 8.14 KB | 1.16 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.JSInterop.dll | 33.00 KB | 33.50 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll | 19.50 KB | 22.50 KB | 1.15 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/blazor.webassembly.js.br | 15.08 KB | 15.40 KB | 1.02 | 0.00 | True |   |   |   |   |  

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/799ce815891cb525520758b44b2981d3be38685c21182ac8268e5e58fb405fe7/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/799ce815891cb525520758b44b2981d3be38685c21182ac8268e5e58fb405fe7/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_1.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/f90fcdae7d62b1ead5c49c744914d6426a81f173a071db87c785f9f4299f5124/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/f90fcdae7d62b1ead5c49c744914d6426a81f173a071db87c785f9f4299f5124/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_2.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/f0eb7a62f6fbabe6e3f889c51ae84846d07e06d192e12807497fcc6c8bd99abc/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/f0eb7a62f6fbabe6e3f889c51ae84846d07e06d192e12807497fcc6c8bd99abc/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_3.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/68f666d32f84d00301dd647f5f1cdab08e9ed1279b59ab53ed5abb51cb4089a1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/68f666d32f84d00301dd647f5f1cdab08e9ed1279b59ab53ed5abb51cb4089a1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_4.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/c045df4fd203e25fe9b3e926ce13363ba5beb27acdc903dcdc9003bb6968a8b1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/c045df4fd203e25fe9b3e926ce13363ba5beb27acdc903dcdc9003bb6968a8b1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_5.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/2895a65107a555b75748740fb0c1c19b2e06bce6695890277f29a0a2ae7f5804/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/2895a65107a555b75748740fb0c1c19b2e06bce6695890277f29a0a2ae7f5804/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_6.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/372b2a253eab8652a3b27c40d796b197a415d3e87c2f988eb2b792b23aa43be6/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/372b2a253eab8652a3b27c40d796b197a415d3e87c2f988eb2b792b23aa43be6/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_7.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/dd0b9f9951d0e6cb7a39f966e62005fb7d07cb8969bcb13e4f0717c145952cd8/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/dd0b9f9951d0e6cb7a39f966e62005fb7d07cb8969bcb13e4f0717c145952cd8/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_8.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/2854b05744cdba42a3ffe33d5539c5450db77eb4892a1792bed2d04484341d5f/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/2854b05744cdba42a3ffe33d5539c5450db77eb4892a1792bed2d04484341d5f/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_9.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/2f9a805354196de4e16905cffeacfd42df9fc02d4897c1d1f42cb283379929a9/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/2f9a805354196de4e16905cffeacfd42df9fc02d4897c1d1f42cb283379929a9/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_10.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/bee376e1862f91d8aa4660df23625281fe27555ba193d6e123c3f22f27f1829b/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/bee376e1862f91d8aa4660df23625281fe27555ba193d6e123c3f22f27f1829b/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31312e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_11.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/dd9e8f1969c9f53763e7f280e7725c4ab7e077e65dc74afa53d613e8ec80b0d6/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31322e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/dd9e8f1969c9f53763e7f280e7725c4ab7e077e65dc74afa53d613e8ec80b0d6/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31322e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_12.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/0cfad7b69c66cb672ff951796e68ff1097c370c0ef9fef1254a4b0a3ae709d77/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31332e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: underline; outline-width: 0px;"><img src="https://camo.githubusercontent.com/0cfad7b69c66cb672ff951796e68ff1097c370c0ef9fef1254a4b0a3ae709d77/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32335f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31332e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_13.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a href="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_23_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"></a></p>
</body>
</html>

**Comment by pranavkm** [comment]
This regression is the result of adding support for additional data types to InputDate. Unfortunately not much we can do here since the feature relies on runtime checks, and consequently preserves a bunch of unused code even if it does not appear in user code.
