### ISSUE TITLE
[Perf] SoD Regressions in emptyblazorwasmtemplate.dll, Microsoft.AspNetCore.Components.dll and Microsoft.AspNetCore.Components.Web.dll

### ISSUE THREAD

**Issue by Tohron** [dotnet/aspnetcore#34735]
### Description

There have been SoD regressions in emptyblazorwasmtemplate.dll, Microsoft.AspNetCore.Components.dll and Microsoft.AspNetCore.Components.Web.dll over the past few days that merit investigation.

### Regression?

emptyblazorwasmtemplate.dll has increased by 1kB(6%), Microsoft.AspNetCore.Components.Web.dll has increased by 2kB (11%),  and Microsoft.AspNetCore.Components.dll has increased by 6kB over the past few days (6%).

### Data
<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; font-size: 1em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Run Information</h3>

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | 1d144234376edb7206058d7d9229f84ce24a70aa
Compare | a2f2a629328a136c2cd18f2cd729e3854de2aeb4
Diff | Diff

</body>
</html>
<html>
<body>
<br class="Apple-interchange-newline">

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Configuration.dll.br | 2.75 KB | 2.72 KB | 0.99 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.JSInterop.dll.br | 13.20 KB | 13.42 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.dll.br | 43.49 KB | 44.78 KB | 1.03 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.dll | 17.50 KB | 18.50 KB | 1.06 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.br | 6.30 KB | 7.03 KB | 1.12 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Logging.dll.br | 6.87 KB | 6.98 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll | 17.50 KB | 19.50 KB | 1.11 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.pdb.gz | 16.32 KB | 16.63 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.dll.br | 6.63 KB | 6.87 KB | 1.04 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.gz | 7.45 KB | 8.31 KB | 1.11 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Configuration.Abstractions.dll.br | 1.97 KB | 2.01 KB | 1.02 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.dll.gz | 49.73 KB | 51.11 KB | 1.03 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.dll | 114.50 KB | 118.00 KB | 1.03 | 0.00 | True |   |   |   |   |  
SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.dll.gz | 7.40 KB | 7.70 KB | 1.04 | 0.00

</body>
</html>

<html>
<body>

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/b3ad84b4a180e962b1b1bbbbffe4135d8f1cca023681891ca760f6d927c77c43/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/b3ad84b4a180e962b1b1bbbbffe4135d8f1cca023681891ca760f6d927c77c43/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_1.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/48e707b5fd59c9d6976f9882c1d2af6fc2416afa862c150eef241aa6f72dfaaa/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/48e707b5fd59c9d6976f9882c1d2af6fc2416afa862c150eef241aa6f72dfaaa/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_2.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/34aa2a597587c35e2d1541c61e68beb66040a6ba4d6cacf7da5c3be842569631/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/34aa2a597587c35e2d1541c61e68beb66040a6ba4d6cacf7da5c3be842569631/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_3.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/f0a30e79208d3d2d165694ddf9ea5b88b5c48feeefc528a2e8171fb55476af87/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/f0a30e79208d3d2d165694ddf9ea5b88b5c48feeefc528a2e8171fb55476af87/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_4.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/102f4c4d1bfcf12fb0b71f69b96463439c30113385001db060747f25038bf5ca/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/102f4c4d1bfcf12fb0b71f69b96463439c30113385001db060747f25038bf5ca/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_5.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/657bf777d19d548d5f6a52af40dca3626f9b529c3f4e69d8d2d93a4d930e62e8/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/657bf777d19d548d5f6a52af40dca3626f9b529c3f4e69d8d2d93a4d930e62e8/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_6.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/265057b952de913a63802c37a5d3c3eb4563a2aba058cec735fd1c90cd3b6748/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/265057b952de913a63802c37a5d3c3eb4563a2aba058cec735fd1c90cd3b6748/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_7.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/4567a8ec429588f2af5c44e375c7578bb581178e6b934a7fda22bd291e511e3c/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/4567a8ec429588f2af5c44e375c7578bb581178e6b934a7fda22bd291e511e3c/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_8.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/3365a9862b0a8a0035823afadc08f370440763debce75fd68c29ac7f99c42231/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/3365a9862b0a8a0035823afadc08f370440763debce75fd68c29ac7f99c42231/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_9.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/d08fcad98426fbfd10ee418ccf421753402fc16e30d42b99e92bf081907499b1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/d08fcad98426fbfd10ee418ccf421753402fc16e30d42b99e92bf081907499b1/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_10.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/e1cc5b705904658ebdc9f60252891cad6bd45140fcd162b595ff1428a299ee74/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/e1cc5b705904658ebdc9f60252891cad6bd45140fcd162b595ff1428a299ee74/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31312e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_11.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/5e4620eaa79122ae414ebf1584a08f6b349ff6483ddb754b981dc1e237d79e95/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31322e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/5e4620eaa79122ae414ebf1584a08f6b349ff6483ddb754b981dc1e237d79e95/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31322e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_12.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/9431094752b34f469c1fbc4d09cccfad4456beb5c7163dc5a3ad552b9bfa8937/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31332e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/9431094752b34f469c1fbc4d09cccfad4456beb5c7163dc5a3ad552b9bfa8937/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31332e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_13.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/5a6bdf2558957f3c8b5092d08af32cb3a656dc8e7b0e29f03a24edd832ca496d/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31342e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/5a6bdf2558957f3c8b5092d08af32cb3a656dc8e7b0e29f03a24edd832ca496d/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f32315f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304e6577253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31342e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_14.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a href="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"></a></p>
</body>
</html>
Source:
https://github.com/DrewScoggins/performance-2/issues/7744

### Analysis

It would seem these regressions merit investigation.  If any were too small to merit this, let us know and we'll update our significance thresholds.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. We'll track this as part of https://github.com/dotnet/aspnetcore/issues/34736
