### ISSUE TITLE
IgnoreSection Should have an overload parameter "required" like RenderSection

### ISSUE THREAD

**Issue by keggster101020** [dotnet/aspnetcore#34742]
## Background and Motivation

I'm using `IgnoreSection` in a layout page to conditionally ignore a section. As it is today, if a page using that layout doesn't have the section defined the framework will throw an exception:

>The layout page '/Pages/Shared/_Layout.cshtml' cannot find the section '\<section name\>' in the content page '/Pages/\<pagename\>.cshtml'.

There should be an overload to deal with situations where the layout isn't defined much like it is for `RenderSection`

## Proposed API

```charp
public void IgnoreSection(string sectionName, bool required)
{
    if(!required && !IsSectionDefined(sectionName))
    {
           return;
    }
    IgnoreSection(sectionName);
}
```

## Usage Examples

``` C#
IgnoreSection("Section", required: false);
```

## Risks

N/A

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is very easy to do in application code by wrapping your section definition in a `if` block. Given that, we don't plan to add new APIs to help with this.
