### ISSUE TITLE
HTTP/3: Get QUIC tests running on CI

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34741]

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/35050 gets tests running on Linux, but we still need win/mac coverage

**Comment by wtgodbe** [comment]
Sounds like we should have a Win11 queue soon: https://github.com/dotnet/core-eng/issues/13582

**Comment by adityamandaleeka** [comment]
This is done... these are running in a quarantined job for now.
