### ISSUE TITLE
Blazor [Wasm + Hosted] the new razor Component CSS file is not working

### ISSUE THREAD

**Issue by zxbe** [dotnet/aspnetcore#34751]
Hi AspNetCore Team!

### Describe the bug
the new razor Component CSS(.razor.css) is not working

### To Reproduce
- project name: BlazorTestApp (Client、Server)

When i add the Counter.razor.css under the Counter.razor and run project, the css is working.
But when i rename the files to (Counter1.razor、Counter1.razor.css) and run project, the css is not working!!!.
And the file(BlazorTestApp.Client.styles.css) has no any content about (Counter1.razor.css).

When i write the css in  Counter1.razor's <style> ,it's working well.

### Further technical details
- ASP.NET Core 6.0 pre6
- VS2022 pre2.1
- win10 21h2
- microsoft edge

**Comment by StefanOssendorf** [comment]
In my experience Visual Studio does not like the renaming of razor components at the moment.
Try the following _after_ the renaming.

1. Close Visual Studio
2. Delete the bin and obj folder in the project folder
3. Open the project/solution againd and do a full rebuild

After that it should work again.

**Comment by zxbe** [comment]
@StefanOssendorf  
it's working well!! thx so much!
