### ISSUE TITLE
HTTP/3: Support getting client certificate

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34756]
Support getting client certificate via [HttpContext.Connection.GetClientCertificateAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connectioninfo.getclientcertificateasync?view=aspnetcore-5.0).

**Comment by JamesNK** [comment]
Related: Client certificate support in runtime - https://github.com/dotnet/runtime/issues/56362

**Comment by JamesNK** [comment]
There is also `ITlsHandshakeFeature` and `ITlsApplicationProtocolFeature`.

**Comment by JamesNK** [comment]
Requires either a fix or new API in System.Net.Quic.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/blob/fce1e3833512ec1dde263df2b8a05fd6303461ca/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.FeatureCollection.cs#L24-L27

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/issues/35039, https://github.com/dotnet/aspnetcore/issues/35040
