### ISSUE TITLE
Discussion about [aspnet/Announcements] Disable Long Polling Fallback Transport for Blazor Server

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#34754]
Hi,

I've just seen the announcement https://github.com/aspnet/Announcements/issues/470

If I understand this correctly, this will result in an error message in browsers which do not support websocket, by default, rather than falling back on a backup protocol to continue serving interactive content. 

I am concerned that this change harms SEO. My understanding of the Google crawler is that while they use a browser that supports websockets in general, it is disabled in that context. 

Am I getting this wrong? Isn't this quite a massive breaking change? I understand that the old behavior can still be implemented through the snippets provided. Still, the default experience after upgrading to net6.0 would be degraded significantly.

Best regards
Stefan

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
If you care about SEO we suggest using pre-rendering which does not rely on an established SignalR connection.
That said, we'll look for future signals around this and see whether we should do something else in this area.

**Comment by danroth27** [comment]
@stefanloerwald We're finding that some users are deploying Blazor Server without websockets by accident and then ending up with a subpar or even broken experience. So yes, this is a breaking change, but we think it will be a net good. We're making this change in preview specifically to test this assumption. Please also note that it is still possible to reenable support for long polling if you want it.
