### ISSUE TITLE
Provide easy access to Razor page runtime metadata

### ISSUE THREAD

**Issue by abdusco** [dotnet/aspnetcore#34759]
I'm trying to get a list of razor pages and type info for their handler classes (`/home` -> `HomeModel`)

I can access the runtime type for a controller from `ControllerActionDescriptor`s using `EndpointDataSource`s. It has `ControllerTypeInfo` property to check which route is mapped to which controller. It's quite handy. It even gives me some info for Razor pages, but it's quite limited.

```c#
var endpoints = _endpointSources
      .SelectMany(es => es.Endpoints)
      .OfType<RouteEndpoint>();
var output = endpoints.Select(
    e =>
    {
        var controller = e.Metadata
            .OfType<ControllerActionDescriptor>()
            .FirstOrDefault();
        var action = controller != null
            ? $"{controller.ControllerName}.{controller.ActionName}"
            : null;
        var controllerMethod = controller != null
            ? $"{controller.ControllerTypeInfo.FullName}:{controller.MethodInfo.Name}"
            : null;
        // ...
    }
);
```

The same is not valid for Razor pages. If I inject a `IActionDescriptorCollectionProvider`, it gives me a list of `PageActionDescriptor`s but that descriptor has only superficial, reduced properties. 

![image](https://user-images.githubusercontent.com/3243482/127136444-a8185d5d-2c31-41e8-9a86-cbbd6f18946c.png)

The actual type info for Razor model class is stored in `CompiledPageActionDescriptor` or `PageApplicationModel`s, which I can't easily access or have no way of accessing without resorting to reflection.

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Mvc/Mvc.RazorPages/src/ApplicationModels/CompiledPageActionDescriptorBuilder.cs#L47-L61

Is there a way to access runtime type info for Razor pages? Any provider that I can inject and get a list of `PageApplicationModel`s?

### Additional context
I'm using ASP.NET Core 5.0.200.

```powershell
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21318
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
Thanks for the feedback @abdusco. When it was first introduced, Razor Pages attempted to optimize start up cost by performing page discovery in 2 phases - in the first page it would discover the pages and it's routes, and compile them on the first request to. This was imperative because views relied on runtime compilation when MVC first started.

Now that build time compilation is the standard, we removed this 2-phase approach as part of https://github.com/dotnet/aspnetcore/pull/28444. For a 6.0 app without runtime compilation enabled, querying the collection provider  should return a list of `CompiledPageActionDescriptors`. Runtime compilation continues to use the 2-phase approach since we didn't find a compelling reason to change it.

**Comment by abdusco** [comment]
Hey @pranavkm, thanks for the insightful response. 

> querying the collection provider should return a list of CompiledPageActionDescriptors

That's great news!

Testing this on `6.0.100-preview.4`, I was able to access `CompiledPageActionDescriptor` as you describe:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/3243482/127232422-0724109a-2778-4940-ba42-2f28764efd07.png">


Thanks a lot!
