### ISSUE TITLE
AOT publishing to an Azure appservice

### ISSUE THREAD

**Issue by dkboon01** [dotnet/aspnetcore#34767]
I'm using .net 6.0.100 - preview 6.21355.2
When publishing receiving this error C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.6.21352.12\Sdk\WasmApp.Native.targets(49,3): Error MSB4019: The imported project "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" was not found. Confirm that the expression in the Import declaration "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" is correct, and that the file exists on disk.
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.6.21352.12\Sdk\WasmApp.Native.targets(49,3): Error MSB4019: The imported project "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" was not found. Confirm that the expression in the Import declaration "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" is correct, and that the file exists on disk.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which is now fixed in the upcoming 6.0-preview7 release.
Please note, that this issue happens only when the Blazor WebAssembly workload is installed. If you uninstall it, publishing should be unblocked.
