### ISSUE TITLE
Razor colorization issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34770]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-colorization-issues/1479049)._

---
There are a number of small issues with the Razor colorization that diverge from the new color updates:

Dark mode:
- Razor syntax in dark mode (`@`, `{`, `}`, etc) should use the purple color of Razor directives without any background color. The old yellow background highlighting should not be used at all in dark mode.
- Razor directive attributes (`@onclick`, `@bind`, etc.) should use the same purple color of Razor directives and should not bold
- Component parameter attributes (ex "Title" on the SurveyPrompt component) should be colored the same as component tags and tag helpers. Currently they show up as bold purple. They should be the bold teal green.

Light mode:
- Razor syntax in light mode (`@`, `{`, `}`, etc) should have the same pale yellow background as razor directives: and razor directive attributes: rgb(255, 255, 179). Right now it's the old full yellow color.

---
#### Feedback Bot on 7/19/2021, 11:00 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryanbrandenburg** [comment]
Waiting on https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/344632 to verify these changes.

**Comment by ryanbrandenburg** [comment]
Ought to also fix https://devdiv.visualstudio.com/DevDiv/_queries/query/72fd76f6-15ab-44d6-b0b2-4cf36f06f08d.

**Comment by ryanbrandenburg** [comment]
OK, I was able to Frankenstien a build that represents the way things will be once all my PR's go into VS:
Dark mode:
![image](https://user-images.githubusercontent.com/14987221/129809820-e21e4007-4b9f-4c02-9df3-c0a9e4383326.png)
Light mode:
![image](https://user-images.githubusercontent.com/14987221/129809952-ac95678b-6690-401a-a2ab-445c124e8c3b.png)
CC @danroth27 and @mikadumont to make sure I didn't miss any scenarios (or break anything anew).

PS: I also found https://github.com/dotnet/aspnetcore-tooling/pull/4105 while doing this, and fixing that should make user customization easier.

**Comment by ryanbrandenburg** [comment]
Spoke with @danroth27 offline and after some last-minute tweaks this seems to be approved, closing.
