### ISSUE TITLE
jquery-validation-unobstrusive in samples is licensed under a non-open source license

### ISSUE THREAD

**Issue by omajid** [dotnet/aspnetcore#34785]
### Describe the bug

ASP.NET Core is licensed under an Open Source License (Apache or MIT). However, some samples in this repository are under a proprietary license. Anyone looking to build and distribute ASP.NET Core from source (for example, Linux distributions as part of the source-build work) is at risk of accidentally violating the license.

Specifically, anumber of `.bower.json` files contain this license entry:

```json
"license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
```

And the license that it points to is not an Open Source License.

Since these are just samples, anyone looking to build and distribute ASP.NET Core can, as a workaround, delete the files and avoid packaging them, but it would be much easier and safer for everyone if the licenses were fixed (or the files were re-licensed or, failing that, any non-open source files were removed).

### To Reproduce

```
$ git remote -v
origin  https://github.com/dotnet/aspnetcore (fetch)
origin  https://github.com/dotnet/aspnetcore (push)

$ git rev-parse HEAD
7739f93951d4e71f61825b5f1380c421bd8c1499

$ grep -ir 'eula.*.htm'
src/Security/samples/PathSchemeSelection/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/DynamicSchemes/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/ClaimsTransformation/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Identity.ExternalClaims/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Cookies/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/StaticFilesAuth/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
```

**Comment by omajid** [comment]
cc @dseefeld @dleeapho @leecow

**Comment by richlander** [comment]
Ping ... Can we make this happen for .NET 7?

**Comment by mkArtakMSFT** [comment]
Discussed this with @ChrisSfanos offline. Here are the next steps to be taken:
- [ ] Update the aspnet/jquery-validation-unobtrusive repo license to MIT
- [ ] Release updated jquery-validation-unobtrusive version (with the new license)
- [ ] Update the dotnet/aspnetcore repo dependency to the latest jquery-validation-unobtrusive version

**Comment by richlander** [comment]
Can this be done in a way that also benefits .NET 6 source-build?

Thanks! This sounds great.

**Comment by omajid** [comment]
Would it make sense to update https://github.com/aspnet/jquery-validation-unobtrusive/blob/main/Microsoft.jQuery.Unobtrusive.Validation.nuspec as well?

It says the license is at https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm, which isn't an MIT license.

**Comment by dougbu** [comment]
@mkArtakMSFT I wasn't aware of this issue but suggest we do the release in jquery-validation-unobtrusive and version update in aspnetcore soon. Who or what is required to make this happen❔

**Comment by richlander** [comment]
@ChrisSfanos is going to resolve this for us.

**Comment by mkArtakMSFT** [comment]
> @mkArtakMSFT I wasn't aware of this issue but suggest we do the release in jquery-validation-unobtrusive and version update in aspnetcore soon. Who or what is required to make this happen❔

I'm working on this: https://github.com/aspnet/jquery-validation-unobtrusive/pull/153

**Comment by mkArtakMSFT** [comment]
Update: the license in the repo has been updated, but there are few nuances that I'm working around before I can publish a release.

**Comment by mkArtakMSFT** [comment]
I've filed a follow-up issue to track updating the references to the latest version: https://github.com/dotnet/aspnetcore/issues/42904

@richlander, there is no more action pending from our side here but the above referenced issue. Should this be closed now?

**Comment by omajid** [comment]
If it's okay with everyone, I would like to keep this issue open until the reproducer steps confirm the fix.

Right now, I still see the references to licenses.

```
$ git rev-parse HEAD
41128c7899ebf31053f3580c9cc0c325315a7aa6
$  grep -ir 'eula.*.htm'
src/Security/samples/ClaimsTransformation/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Cookies/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/DynamicSchemes/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Identity.ExternalClaims/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/PathSchemeSelection/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/StaticFilesAuth/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
```

**Comment by richlander** [comment]
That's a good test, @omajid. Can you address those as well @mkArtakMSFT?

**Comment by mkArtakMSFT** [comment]
This has been addressed by https://github.com/dotnet/aspnetcore/pull/42999

**Comment by omajid** [comment]
Thanks! It looks like my original concern remains unaddressed, though: 

```
$ git rev-parse HEAD
bf02bf2325f4752dd8a28c17d420e01961219f91
$ grep -ir 'eula.*.htm'
src/Security/samples/ClaimsTransformation/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Cookies/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/DynamicSchemes/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/Identity.ExternalClaims/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/PathSchemeSelection/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
src/Security/samples/StaticFilesAuth/wwwroot/lib/jquery-validation-unobtrusive/.bower.json:  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
```

**Comment by Pilchie** [comment]
I thought I had fixed these in https://github.com/dotnet/aspnetcore/pull/34573, but it looks like I missed the bower files.  We should be able to just change these (by effectively re-licensing the copy that is in the aspnetcore repo).

**Comment by mkArtakMSFT** [comment]
Thanks @omajid!
Just sent a PR to address this - the final touch 👍

**Comment by omajid** [comment]
Thanks for fixing this, @mkArtakMSFT
