### ISSUE TITLE
Add ASP.NET Core Visual Basic project template

### ISSUE THREAD

**Issue by skurth** [dotnet/aspnetcore#34788]
Add ASP.NET Core VB project template:
![image](https://user-images.githubusercontent.com/11660701/127277453-0be568fb-9ce2-44af-be54-13372eaafa29.png)

Even if VB is not fully supported for all ASP.NET Core web application types, at least "ASP.NET Core Web API" should be available:
![image](https://user-images.githubusercontent.com/11660701/127277711-4777bccd-a2dd-4232-96c8-d03666b80dbe.png)

Right now you have to create a C# project and convert it to VB.
I've found other similar issues (all closed), but this one is specific about ASP.NET Core Web API.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by skurth** [comment]
@mkArtakMSFT Thank you for your answer. I don't really understand it. According to [Microsoft statement](https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/) ASP.NET Core Web API for Visual Basic will be supported. And it's supported now and so to say part of the framework already. Like I wrote you can create a C# Web API and convert it to VB and it works.

So back to why I don't understand it: You have fully support (it _is_ part of the framework) for this application type in Visual Basic, why you don't provide a template for it?

**Comment by danroth27** [comment]
@LadyNaggaga
