### ISSUE TITLE
Unable to get Root folder location of the ASPNET CORE Web Application from a referenced DLL

### ISSUE THREAD

**Issue by sonupmandal** [dotnet/aspnetcore#34797]
I have a ASPNET Core Web Application which references a library that is generated from another .NET Core project.
 Is there a way to programmatically get the root folder location from within the referenced library?
 I am not able to use the ContentRootPath API in the project that generates the library because it is NOT a Web Application.

ASPNET Core web application details :
 Target Framework = .NET Core 3.1

Referenced Library details.
Target Framework = .NET Standard 2.1

**Comment by javiercn** [comment]
Thanks for contacting us @sonupmandal 

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.
