### ISSUE TITLE
ASPNETCORE_ENVIRONMENT value is ignored and HostingEnvironment is always set to production

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNETCORE_ENVIRONMENT-value-is-ignored-/1485890)._

---
[severity:It's more difficult to complete my work]
ASPNETCORE_ENVIRONMENT value is ignored and HostingEnvironment is always set to production.

**Program.cs**

```csharp
Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "Development");

Console.WriteLine(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"));

var host = new HostBuilder()
    . ConfigureAppConfiguration((hostContext, builder) =>
    {
        Console.WriteLine(hostContext.HostingEnvironment.EnvironmentName); // Production
    })
    . Build();
```

**launchSettings.json**

```json
{
  "profiles": {
    "LichessChallenger": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true
    }
  }
}
```

**Versions**

Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 2.0

<Project Sdk="Microsoft.NET.Sdk.Worker"/>

$ dotnet --version
6.0.100-preview.6.21355.2

---
#### Feedback Bot on 7/25/2021, 08:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
This is expected. ASPNETCORE_ENVIRONMENT applies to web applications (`.ConfigureWebHost`). You're using the HostBuilder without any web application components. The HostBuilder uses `DOTNET_ENVIRONMENT` by default. Was that one working for you?

**Comment by davidfowl** [comment]
This is worth documenting.

**Comment by maxisam** [comment]
@Tratcher 

But if I use 

```csharp
                      Host.CreateDefaultBuilder()
                      .ConfigureAppConfiguration((hostingContext, config) =>
                      {
                         config.AddEnvironmentVariables("ASPNETCORE_");
                      })
```

It still doesn't read ASPNETCORE_ENVIRONMENT. It still reads DOTNET_ENVIRONMENT.

**Comment by maxisam** [comment]
Just found the answer

https://github.com/dotnet/AspNetCore.Docs/issues/9278
https://thecodeblogger.com/2021/05/02/net-generic-host-host-configuration-vs-app-configuration/

And I forgot to set appsettings.json as Copy in property (Dont need to for Web project.)

The doc can be better here

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0

Or just provide a better template.

**Comment by sebastienros** [comment]
I believe the documentation is now updated to reflect all the layering and the reason why the issue was created in the first place: Use a `CreateDefaultBuilder` to setup the sources, or use `ConfigureHostConfiguration` to load the environment from custom sources.

c.f. https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-7.0
