### ISSUE TITLE
Error publishing .Net 6 P6 app from Visual Studio

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#34805]
### Describe the bug
I was able to publish my app on July 15th directly in VS (choosing the publish command against the appropriate project). Today July 28th I get two error messages:

The imported project "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" was not found. Confirm that the expression in the Import declaration "C:\WINDOWS\system32\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.6.21352.12\runtimes\browser-wasm\native\src\Emcc.props" is correct, and that the file exists on disk.	Optimiser.2021.Web

Assets file 'C:\Solutions\OHI\Optimiser\Optimiser.2021.Web\obj\publish\win-x64\project.assets.json' not found. Run a NuGet package restore to generate this file.	Optimiser.2021.Web

The only environment change that I am aware of is moving from VS2022 P2.0 to VS2022 P2.1; Certainly the paths look odd in the error messages. I can do a CLI 'dotnet publish optimiser.2021.sln -C DEMO' and not get an error message. The emcc.props file is actually in 'C:\Solutions\OHI\Optimiser\Optimiser.2021.Blazor\bin\DEMO\net6.0\wwwroot\_framework' and there is a 'project.assets.json' file in every project in the obj directory

### To Reproduce

See the description
### Exceptions (if any)

None
### Further technical details

VS2022 P2.1

C:\Solutions\OHI\Optimiser>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\OHI\Optimiser>

**Comment by mkArtakMSFT** [comment]
Thank for contacting us. This is a known issue which was already fixed in the upcoming 6.0-preview7 release.
