### ISSUE TITLE
Unable to import a PFX file using `dotnet dev-certs https` under macOS

### ISSUE THREAD

**Issue by msbit** [dotnet/aspnetcore#34808]
### Describe the bug
On macOS, I'm unable to import a PFX file using `dev-certs`.

### To Reproduce

* `dotnet new webapp --output test`
* `pushd test`
* `dotnet dev-certs https`
* Export `localhost` from Keychain Access to `~/Desktop/Certificate.p12` with `password` password
* `dotnet dev-certs https --clean --import ~/Desktop/Certificates.p12 --password password`

I get the following output:

```
Cleaning HTTPS development certificates from the machine. This operation might require elevated privileges. If that is the case, a prompt for credentials will be displayed.
HTTPS development certificates successfully removed from the machine.
The provided certificate file '/Users/tom/Desktop/Certificates.p12' is not a valid PFX file or the password is incorrect.
```

Looks to be output here:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Tools/dotnet-dev-certs/src/Program.cs#L217

based on an exception here:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Shared/CertificateGeneration/CertificateManager.cs#L371

I'm not sure how to get access to the `EventSource` instance under macOS (would be interested to see how), so I put together a simple console app:

```
using System;
using System.Security.Cryptography.X509Certificates;

namespace console {
  class Program {
    static void Main(string[] args) {
      Console.WriteLine(new X509Certificate2(
        "/Users/tom/Desktop/Certificates.p12",
        "password",
        X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet
      ));
    }
  }
}
```

which throws the following exception:

```
Unhandled exception. System.PlatformNotSupportedException: This platform does not support loading with EphemeralKeySet. Remove the flag to allow keys to be temporarily created on disk.
   at Internal.Cryptography.Pal.AppleCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at Internal.Cryptography.Pal.AppleCertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at console.Program.Main(String[] args) in /Users/tom/Development/msbit/68078355/console/Program.cs:line 7
```

Removing `X509KeyStorageFlags.EphemeralKeySet` does in fact work, with the following output:

```
[Subject]
  CN=localhost

[Issuer]
  CN=localhost

[Serial Number]
  00ABFF51599B55D5AD

[Not Before]
  29/7/2021 2:13:39 am

[Not After]
  29/7/2022 2:13:39 am

[Thumbprint]
  AD28BDE4084E1C8CC54D0001C85D87F06A869823
```

### Exceptions (if any)

```
System.PlatformNotSupportedException: This platform does not support loading with EphemeralKeySet. Remove the flag to allow keys to be temporarily created on disk.
```

### Further technical details
`dotnet-sdk-5.0.302-osx-x64`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /Users/tom/opt/dotnet/dotnet-sdk-5.0.302-osx-x64/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [/Users/tom/opt/dotnet/dotnet-sdk-5.0.302-osx-x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/Users/tom/opt/dotnet/dotnet-sdk-5.0.302-osx-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/Users/tom/opt/dotnet/dotnet-sdk-5.0.302-osx-x64/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@msbit thanks for contacting us.

The import functionality is only meant to be used in WSL scenarios where you want to share the cert from the host machine with the cert on the WSL distro. It is not meant as a general certificate import feature. For that we recommend you use the native OS toolchain.

**Comment by msbit** [comment]
Hey @javiercn, thanks for the response.

> The import functionality is only meant to be used in WSL scenarios where you want to share the cert from the host machine with the cert on the WSL distro

I was only going on the output of `dotnet dev-certs https --help` and error messages with incorrect invocations, would it be worth documenting this somewhere (if not already done).

> It is not meant as a general certificate import feature. For that we recommend you use the native OS toolchain.

Interesting! If I were to import a key/certificate with common name and SAN set to `localhost` using Keychain Access, would `dotnet run` pick it up without having to specify anything in the app settings?

**Comment by javiercn** [comment]
> If I were to import a key/certificate with common name and SAN set to `localhost` using Keychain Access, would `dotnet run` pick it up without having to specify anything in the app settings?

No. Our certificate is special and its optimized for local development. Creating your own custom certificate and having asp.net core pick it up, its not something we plan to support.
