### ISSUE TITLE
Failed to launch debug adapter when debugging Blazor in VS 2019.10.2 Enterprise

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34802]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Failed-to-launch-debug-adapter-when-debu/1459849)._

---
[severity:It's more difficult to complete my work]
After a fresh restart of my machine, I was unable to debug the default Blazor Web App using VS 2019 Enterprise version 16.10.2. I've tried the latest versions of both Edge (91.0.864.54) and Chrome (91.0.4472.114). The error message I got was: Failed to launch debug adapter.
I then tried FireFox. It could not connect to the webpage either, but showed a suggestion to enable TLS 1.0 and TLS 1.1. I accepted that, also allowed it to trust the certificate, and then the application did show. So this is my workaround: use FireFox and enable TLS 1.0 and TLS 1.1.

---
#### Arno Tolmeijer on 6/24/2021, 06:34 AM: 

<p>When I created a new solution and dit not check the ‘Configure for https’ checkbox, I could also use Edge and Chrome.</p>

#### Feedback Bot on 6/24/2021, 10:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
The original report from the user mentioned that disabling HTTPS resolved the issue for them. I suspect that the certificates were borked on their local machine.

We document this in our docs already: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio
