### ISSUE TITLE
Check if publish in progress: DeployOnBuild does not work for asp.net core client app

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#34811]
I have a Blazor wasm app hosted in asp.net core, client and server project in the same solution.
App publish start from server project.

From build task i would like to compile sass with "npm run sass ..." before the Compile target and **only during publish** (not for every build of the client project).

i tryed `Condition="'$(DeployOnBuild)' == 'true'" BeforeTargets="Compile"` to check if publish is running but `$(DeployOnBuild)` is always empty.

It's a bug?

How to check  if publish is running?

Thanks

**Comment by javiercn** [comment]
@Gambero81 thanks for contacting us.

If you want to do something only during publish, I would suggest you hook on to one of the publish targets on the build, like `PrepareForPublish` and so on. Is there any reason why you need to run before `Compile`?
