### ISSUE TITLE
Why is Identity coupled to .net5(core)

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/aspnetcore#34821]
Why are there two version of Identity, surely it make sense to just decouple this from 
dependency which require core (.net5) and further EF and then there would just be 1 version.

https://github.com/aspnet/AspNetIdentity 
Microsoft.AspNet.Identity.Core 2.2.3

and 

https://github.com/dotnet/aspnetcore/tree/main/src/Identity -
Microsoft.AspNetCore.Identity 2.2

see https://stackoverflow.com/questions/41140952/what-is-the-difference-between-microsoft-aspnet-identity-core-and-microsoft-aspn/41141049

This make very little sense to me, and in fact really annoys me when you try hard to keep things clean, only to have nothing compatible.

Could someone tell me why there isn't a version that has a abstraction over it so that it shouldn't matter and therefore only have 1 version.

This basically forces you to rewrite all Auth, stuff as they simple not compatible, which i have basically already done, but im trying to understand why they chose to do this.

I mean surely its a set of interfaces which then you set the implementation, so why, what would of forced them to say no we creating another one....
 
Microsoft.AspNetCore.Identity.IdentityUser

and  

 Microsoft.AspNet.Identity.EntityFramework.IdentityUser

begs the question why make the interface in the first place if its not something you are going to extend on and basically start from scratch.

Thanks, regards Calvin

**Comment by blowdart** [comment]
The two repos you have are very different - one is for older versions of the .NET framework, and one is the more modern one. We aren't writing new code for the .NET framework, so why would we abstract over them?

If you're wanting to share a single auth database between multiple web sites you can fudge it yourself, but you're into unsupported territory at that point.  It's better to abstract auth to a dedicated service such as an instance of [IdentityServer](https://www.identityserver.com/) or [OpenIddict](https://github.com/openiddict/openiddict-core).

**Comment by Seabizkit** [comment]
@blowdart , sorry maybe I didn't explain myself in a way which is understood.
What is in the newer one which is not backwards compatible if the idea is that its an abstract over how to manage Identities.
Let me try from another angle, why make something... which is designed to be independent of data store used.
Then go mmm wait you know what will force people to update, lets make the next update incompatible for no other reason. 

aka - 
**a good answer would be:**
 we wanted to use datatables in Identity management classes and these are not available in std 2.0 so we had to force consumers to a higher api level, we did this by making a new Identity nuget which can only be used on core. **Except this isn't the case!**

**a bad answer would be:**
The two repos you have are very different - one is for older versions of the .NET framework, and one is the more modern one.
With the justification being no body asks the question but why? What is in Core (.net5) which is not available in Framework, which forced all development to stop on "v1" I guess and start "v2" when its an abstract on  "data store" and "User classes".

Everything is available in standard 2.0, aka Claims classes and  interfaces, no .net core specific api level features.

Ok let me try another way

if v1 (framework) one was designed to be a user and data store abstraction, 
https://docs.microsoft.com/en-us/previous-versions/aspnet/dn468178(v=vs.108)

What was the goal with v2(core), wrong answer would be force everyone to move to core.

its like why do we even bother making std2, if you just going to write code for .net core but which could of worked in std2.
AKA do you see  Nuget packages only compiling to the highest level API, no they  compile for all which are possible, and try quite hard to keep a backward compile available.

Maybe my question is what feature/api was not available in std2.0 which force them to .net core **considering!** Identity is an abstraction, aka it doesn't know much about much, its like making an interface and then going lets just make a new one.... with 0 reason to.

Seems not heathy to do such things. AKa **when possible keep min level** to be able to be complied to std2.
in this case they started fresh but no indication as to what was the limit. Well hard for me to see what or why they couldn't make a nuget version which was compatible from 5.0 to std2.0. 

hope that clears up what im wanting to know.

**Comment by blowdart** [comment]
Honestly you're asking me to list 5 years of changes and feature enhancements. I'm not sure I can. Authenticator support is the big one that stands out, but also, the migration to EF Core, which isn't available on framework is also a reason. 

Keeping two versions in sync is expensive compared to any perceived benefit. .NET Standard doesn't include any of the asp.net features, and identity is solely targeted for the version of asp.net it's shipped with. Limiting ourselves like that wouldn't make sense. It's not about making you move to core, if you don't want the enhancements that came with the move to core, then just don't move. You're talking about code that's over 5 years old, expecting it to stand still is unrealistic in my opinion.

**Comment by Seabizkit** [comment]
@blowdart  no your not following what im asking.

**defo not asking to list 5 years....**

I have already moved... but im trying to understand why in my opinion a really "subjective" (bad) was made with regards to making Identity a requirement on core when technically nothing is stopping it from being .net standard 2.0 and thus compatible
which means it would available on framework which mean there would be 1 version and not two.

if they converted all the classes and interface to a standard lib, which api feature would not be available, i don't know which mean well they didn't do it for any good reason.

great site for showing Api supported.
https://dotnet.microsoft.com/platform/dotnet-standard
it would be cool if they gave the reasoning for the move with respect to this, rather than we just made it .core even though we could of made it standard 2.0
remember its an abstraction over a user and data pool **which is exactly what the Identity (framework) is**, so they could of made a standard version and everyone! would be happy! instead no they moved it to core.... which from and out side its not clear what feature was lacking to make this decision, and basically say we stopping support even though everything would of worked. 

there are lost of packages which target standard to maintain the existing the ego system, and only change when the framework simply does not have the required api's.

**Comment by blowdart** [comment]
_if they converted all the classes and interface to a standard lib, which api feature would not be available, i don't know which mean well they didn't do it for any good reason._

It's not so much which feature, but more that Identity is an ASP.NET feature. It keeps up with the platform itself, especially the UI portion. Separating it has never made much sense, and there's never been much demand for that. It's simply not something we're interested in doing, especially [as .NET Standard isn't a thing going forward](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md).
