### ISSUE TITLE
Add ISupportsConfigureWebHost interface to hosting.

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#34824]
## API Proposal

```diff
namespace Microsoft.AspNetCore.Hosting.Infrastructure
{
+    public interface ISupportsStartup
+    {
+        IWebHostBuilder Configure(Action<WebHostBuilderContext, IApplicationBuilder> configure);
+        IWebHostBuilder UseStartup([DynamicallyAccessedMembers(StartupLinkerOptions.Accessibility)] Type startupType);
+        IWebHostBuilder UseStartup<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)]TStartup>(Func<WebHostBuilderContext, TStartup> startupFactory);
+    }
+
+    public interface ISupportsConfigureWebHost
+    {
+        IHostBuilder ConfigureWebHost(Action<IWebHostBuilder> configure, Action<WebHostBuilderOptions> configureOptions);
+    }
```
We would implement `ISupportsStartup` in [ConfigureWebHostBuilder](https://github.com/dotnet/aspnetcore/blob/a7ca111caeb3f1a66a65ca802a3b7d18617b2e80/src/DefaultBuilder/src/ConfigureWebHostBuilder.cs) (i.e. `WebApplicationBuilder.WebHost`) and `ISupportsConfigureWebHost` in [ConfigureHostBuilder](https://github.com/dotnet/aspnetcore/blob/a7ca111caeb3f1a66a65ca802a3b7d18617b2e80/src/DefaultBuilder/src/ConfigureHostBuilder.cs) (i.e. `WebApplicationBuilder.Host`) .

## Justifcation

In order to make `builder.WebHost.UseStartup` and `builder.WebHost.Configure` throw instead of no-op in the following:

```c#
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseStartup<Startup>();
var app = builder.Build();
```

```c#
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.Configure(app =>
{
    app.Run(async context =>
    {
        await context.Response.WriteAsync("Hello world from configure!");
    });
});
var app = builder.Build();
```

This is because both [UseStartup](https://github.com/dotnet/aspnetcore/blob/a7ca111caeb3f1a66a65ca802a3b7d18617b2e80/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs#L57) and [Configure](https://github.com/dotnet/aspnetcore/blob/a7ca111caeb3f1a66a65ca802a3b7d18617b2e80/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs#L90) will try to pass through their calls to any IWebHostBuilder implementing ISupportsStartup giving us the opportunity to throw.

Currently only GenericWebHostBuilder implements ISupportsStartup and it lives in the same assembly so it can be internal. ConfigureWebHostBuilder is in another assembly that depends on Hosting, so it needs the interface to be public to implement it.

## Alternative considered
1.
    ```diff
    namespace Microsoft.AspNetCore.Hosting
    {
    +    public interface IRejectStartup
    +    {
    +        void ThrowException();
    +    }
    ```

    With this design, IRejectStartup is not just a marker interface, but it also throws an Exception via ThrowException() which would be called by the unsupported extension methods allowing any implementers of the interface to provide more detailed error messages. I'm not sure this is necessary, and if we wanted to support throwing different exceptions from Configure and UseStartup, the interface becomes more complicated.

2.
    ```diff
    namespace Microsoft.AspNetCore.Hosting
    {
    +    public interface ISupportsStartup
    +    {
    +        IWebHostBuilder Configure(Action<WebHostBuilderContext, IApplicationBuilder> configure);
    +        IWebHostBuilder UseStartup([DynamicallyAccessedMembers(StartupLinkerOptions.Accessibility)] Type startupType);
    +        IWebHostBuilder UseStartup<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)]TStartup>(Func<WebHostBuilderContext, TStartup> startupFactory);
    +    }
    ```

     This feels like it exposes more than we have to and doesn't allow us to throw from ConfigureWebHost().

3. If ConfigureWebHostBuilder continued not to implement ISupportsStartup, we could look for additions of IStartup services to the [WebApplicationServiceCollection](https://github.com/dotnet/aspnetcore/blob/a7ca111caeb3f1a66a65ca802a3b7d18617b2e80/src/DefaultBuilder/src/WebApplicationServiceCollection.cs) instead and throw if that ever happens. This feels a lot less straightforward than implementing ISupportsStartup however.

4.
    ```diff
    namespace Microsoft.AspNetCore.Hosting
    {
    +    /// <summary>
    +    /// A marker interface used to indicate the <see cref="IHostBuilder"/> or <see cref="IWebHostBuilder"/>
    +    /// does not support any of the following extension methods:
    +    /// * <see cref="WebHostBuilderExtensions.Configure(IWebHostBuilder,         Action{AspNetCore.Builder.IApplicationBuilder})"/>
    +    /// * <see cref="WebHostBuilderExtensions.UseStartup(IWebHostBuilder, Type)"/>
    +    /// * <see cref="GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder, Action{IWebHostBuilder})"/>
    +    /// </summary>
    +    public interface IRejectStartup
    +    {
    +    }
```

This allows us to check inside these extension methods whether they should throw to indicate they're not supported by the given IHostBuilder or IWebHostBuilder (namely WebApplicationBuilder.Host/WebHost) rather than effectively doing nothing.

**Comment by davidfowl** [comment]
- IDisallowWebHostConfiguration
- IBlockWebHostConfiguration

**Comment by pranavkm** [comment]
API review feedback - we think the names are fine. Let's put this in a non-root namespace `Microsoft.AspNetCore.Hosting.Infrastructure` since we don't want casual users seeing this type.
