### ISSUE TITLE
Minimal host does not work with NativeAOT

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#34838]
### Describe the bug
While this isn't yet a fully supported scenario it was possible to build simple ASP.NET Core applications before with NativeAOT. This should in theory still be possible since the WebApplicationBuilder is a thin layer over the existing APIs. That's broken now because we're using Assembly.GetCallingAssembly to get the default application name.

### To Reproduce

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-*" />
</ItemGroup>

</Project>
```

Program.cs

```C#
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/", context => context.Response.WriteAsync("Hello World!"));

app.Run();
```

1. Run `dotnet publish -r win-x64` (I was on windows)
2. Run the resulting published exe.

### Exceptions (if any)

```
WebApplication1\bin\Debug\net6.0\win-x64\publish\WebApplication1.exe
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Reflection.Assembly.GetCallingAssembly() + 0x7a
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[]) + 0x1d
   at <Program>$.<Main>$(String[]) + 0x3e
   at WebApplication1!<BaseAddress>+0x1080f37
   at WebApplication1!<BaseAddress>+0x1080fc5
```

cc @MichalStrehovsky @jkotas @agocke

**Comment by hez2010** [comment]
NativeAOT doesn't support `GetCallingAssembly`, because all assemblies are linked and "inlined" so there's no so called "calling assembly". 

To workaround, use
```xml
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Switch.System.Reflection.Assembly.SimulatedCallingAssembly" Value="true" />
  </ItemGroup>
```
which simulates `Assembly.GetCallingAssembly` using `Assembly.GetEntryAssembly`.

Or you can replace `Assembly.GetCallingAssembly` with `Assembly.GetEntryAssembly` directly if it's okay.

https://github.com/dotnet/aspnetcore/blob/0c5456afe95096db6ac5400cecd3440299b42714/src/DefaultBuilder/src/WebApplication.cs#L89
https://github.com/dotnet/aspnetcore/blob/0c5456afe95096db6ac5400cecd3440299b42714/src/DefaultBuilder/src/WebApplication.cs#L97

**Comment by davidfowl** [comment]
Yea I know why it's broken, I'm just filing an issue so we can resolve it

**Comment by jkotas** [comment]
`GetCallingAssembly` is slow and unreliable API that does not work well with NativeAOT. It does not work in Mono AOT either - https://github.com/dotnet/runtime/issues/53825. I do not see us fixing that.

I think we need a small language feature to get fast, reliable and AOT-friendly replacement for the scenarios where it is used: https://github.com/dotnet/runtime/issues/41690#issuecomment-685092071

**Comment by davidfowl** [comment]
I don't think we need to fix it in NativeAOT, I really want to use the entry assembly when running on native AOT but there's no way that I'm aware of (other than catching an exception to do that). If we could expose anything like an app context switch we can key off, that would work well. 

> I think we need a small language feature to get fast, reliable and AOT-friendly replacement for the scenarios where it is used: dotnet/runtime#41690 (comment)

Can we formalize this as a language feature for .NET 7? We probably need a proposal (like [CallerAssemblyName])

**Comment by jkotas** [comment]
We do want `GetCallingAssembly` to throw by default in NativeAOT . There are number of cases where the fallback behavior of `GetCallingAssembly` does not work well. We do not want to spend days trying to debug and diagnose those cases (we have been there with .NET Native).

> Can we formalize this as a language feature for .NET 7?

I have started https://github.com/dotnet/runtime/issues/56601

**Comment by jkotas** [comment]
> I really want to use the entry assembly when running on native AOT

If entry assembly was good enough for NativeAOT, why is it not good enough for everybody? I do not think we want to be creating NativeAOT behavior differences like this either.

**Comment by davidfowl** [comment]
> If entry assembly was good enough for NativeAOT, why is it not good enough for everybody? 

The situation is this, we need to get a best guess default application name. Historically this worked by using either:
- The assembly where the Startup class way (you called `UseStartup<T>` and we did `typeof(T).Assembly.GetName().FullName`)
- The assembly where your configure callback was defined(you called `Configure(app => {  })`, and we did `Action.Method.DeclaringType.Assembly.GetName().FullName`).
 
This name is used in 2 keys ways in ASP.NET Core, as a way to look for controllers and pages. It uses this assembly name to look for attributes to discover these things.

With this new imperative host, we don't have a startup type or a delegate so the best approximation is the entry assembly, EXCEPT in situations where you want to discover controllers inside of a library. We use the calling assembly as a close approximation (which I think is a pretty good default) then we fallback to the entry assembly.

The entry assembly is also broken by default whenever you are "hosted" in another process (think powershell, visual studio etc). The best approximation for those scenarios is the calling assembly. Bare in mind, we'll allow changing this manually but we're talking about defaults and I think this should work in both CoreCLR and NativeAOT, and other places.

It's generally bad when we can't avoid a throwing API IMO.

> I do not think we want to be creating NativeAOT behavior differences like this either.

The only thing I can think of is to catch the exception which I don't want to do.

**Comment by jkotas** [comment]
> The only thing I can think of is to catch the exception which I don't want to do.

Agree. I think it is bad idea to try to make AOT-incompatible patterns "work" at all costs. It produces bad results in the long run (learning from .NET Native for UWP).

If you wanted to do something now, I think it may be a good idea to add default Assembly argument to the `WebApplication.Create/CreateBuilder` methods that people can use to override the defaults:
- It would allow people to make the code compatible with NativeAOT by changing code instead of enabling compatibility quirk.
- It would prepare the public surface for passing the assembly implicitly using the proposed attribute.
- It would allow overriding the default if this API is wrapped by other libraries.

**Comment by davidfowl** [comment]
We're already doing this here https://github.com/dotnet/aspnetcore/issues/34837, I just wanted a good way to default it in the AOT case without throwing. When this change is in, it'll avoid calling `GetCallingAssembly` if the name is explicitly specified. I still don't like that we can't default it properly.

> It would prepare the public surface for passing the assembly implicitly using the proposed attribute.

Passing in the assembly might also be interesting given this.

**Comment by davidfowl** [comment]
Another option for .NET 6 might be to offer another `WebApplication.CreateBuilder<TEntryPoint>` but I don't love that either...

**Comment by jkotas** [comment]
> in situations where you want to discover controllers inside of a library. We use the calling assembly as a close approximation (which I think is a pretty good default) then we fallback to the entry assembly.

I would question whether `Assembly.GetCallingAssembly` is a good default: 
- `GetCallingAssembly` is unreliable API as its documentation states. You can end up behavior changes when you do "harmless" code refactoring.
- When people are calling APIs like this from libraries, they often have layers of wrappers and so the immediate caller is often wrong answer anyway. `ContextualReflectionScope` was introduced as imperfect duct tape around this problem for assembly load contexts.

I think `Assembly.GetEntryAssembly` would be about as good default as `Assembly.GetCallingAssembly`. And it would be fast, deterministic and AOT friendly.

**Comment by davidfowl** [comment]
It's not a good default because it's broken for the library scenarios I describe.

**Comment by davidfowl** [comment]
Unit testing being one of the main things as break as a result of removing this.

**Comment by jkotas** [comment]
My point is that the libraries or unit tests can can pass in the right assembly explicitly. I do not think it is a good idea to resort to slow unreliable API to make these cases "work", especially given that the default will not work for them like half the time.

Consider: The only place where `Assembly.GetCallingAssembly` is used in dotnet/runtime libraries is `Microsoft.VisualBasic.FileSystem`. Everything else is using `Assembly.GetEntryAssembly` with optional explicit override.

**Comment by davidfowl** [comment]
> My point is that the libraries or unit tests can can pass in the right assembly explicitly. I do not think it is a good idea to resort to slow unreliable API to make these cases "work", especially given that the default will not work for them like half the time.

I feel like this default works most of the time, but I'll see if I can come up with something that works well for both scenarios.

**Comment by davidfowl** [comment]
We might have made the wrong tradeoff removing this and making everything pass in the name from the outside. It's lead to a slow trickle of edge casey bugs that break tools and other things that load the application as a library...
