### ISSUE TITLE
does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by vvladro** [dotnet/aspnetcore#34835]
### Describe the bug
Dear developers, the following problem has arisen, 

ASP.NET Core SignalR C++ Client
Build on Linux
cmake .. -DCMAKE_TOOLCHAIN_FILE=../submodules/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CPPRESTSDK=true
...
Cmake Error The source directory "/home/user/SignalR-Client-Cpp/submodules/vcpkg/scripts" does not appear to contain CMakeLists.txt.

the library is not going
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by BrennanConroy** [comment]
Did you follow the instructions and initialize the submodules?
https://github.com/aspnet/SignalR-Client-Cpp#build-on-linux
> git submodule update --init

**Comment by vvladro** [comment]
> Did you follow the instructions and initialize the submodules?
> https://github.com/aspnet/SignalR-Client-Cpp#build-on-linux
> 
> > git submodule update --init

thanks, but unfortunately errors occurred again.
[CMakeError.log](https://github.com/dotnet/aspnetcore/files/6905993/CMakeError.log)

**Comment by BrennanConroy** [comment]
Try following the instructions for finding the issue at https://stackoverflow.com/a/57371779
