### ISSUE TITLE
[BUG] adding aspnetcore logging site extension when nuget is already installed breaks app

### ISSUE THREAD

**Issue by jsquire** [dotnet/aspnetcore#34840]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#22947](https://github.com/Azure/azure-sdk-for-net/issues/22947).

## Details

**Describe the bug**
If you add the aspnetcore logging site extension through the azure portal when it is already installed in your app, it stomps your existing package and replaces it with a different version, causing startup errors.

There is a dangerously easy button to click on the logging page which will add the site extension without taking you to where site extensions are managed. The button disappears after clicking it so you don't even know what you just clicked.

![image](https://user-images.githubusercontent.com/24449147/127456717-a583a1b3-65b2-420f-b93e-0c12874139c3.png)

**Expected behavior**
1. Dont overwrite packages if they are already in your app. 
2. Don't have buttons that are almost the same colour as the background, are clickable across the width of the screen, that require no confirmation, that disappear after clicking, that can break your app.

**Actual behavior (include Exception or Stack Trace)**
I found this error on startup which didnt appear until after swapping from our deployment slot.
```<Data>Application '/LM/W3SVC/1457250691/ROOT' with physical root 'D:\home\site\wwwroot\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.AzureAppServices, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 
```
I'm checking packages and wondering where 5.0.8 comes from when we have 5.0.6 targeted in our app.

**To Reproduce**
1. have logging already installed in your app (5.0.6)
2. click button on logging page to install 5.0.8 (ensure site extension installs different version that whatever your app expects)
3. restart app, watch it crash

**Environment:**
 - Name and version of the Library package used: Microsoft.Extensions.Logging.AzureAppServices 5.0.6
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure AppService
 - IDE and version : Visual Studio 2019

**Comment by adityamandaleeka** [comment]
@LukeBolly Can you please confirm whether your deployment is self-contained? The immediate workaround for this would be to change your package reference for `Microsoft.Extensions.Logging.AzureAppServices` to 5.0.8.

**Comment by adityamandaleeka** [comment]
This will be resolved by https://github.com/dotnet/aspnetcore/issues/34864.
