### ISSUE TITLE
[Question] What java client should I use in my Android app?

### ISSUE THREAD

**Issue by ntoskrnl** [dotnet/aspnetcore#34844]
Sorry, didn't know where else to ask. 
I am totally confused with the java client libraries that are available for SignalR. But the ones I checked out, don't support automatic reconnect and event replay (even if manual reconnect is implemented). Maybe I am looking in wrong places?

1. What is the official library version to use in Android apps?
2. Is there support for reconnect with event redelivery? 
3. Will it ever be supported in the future or we have to come up with custom solutions for that?

**Comment by adityamandaleeka** [comment]
@ntoskrnl Please take a look at this doc: https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-5.0#android-development-notes

Great username btw! :)

**Comment by ntoskrnl** [comment]
One last question:
We have a legacy project that was using one of the older implementations of the client library without RX java. I am thinking to migrate to the lates one, but I cannot find HubProxy functionality.
Then now I realize that what we are using is ASP.NET SignalR and this is Core SignalR and they are not compatible.

Is ASP.NET SignalR completely deprecated and ASP.NET Core SignalR the current technology?

**Comment by adityamandaleeka** [comment]
> Is ASP.NET SignalR completely deprecated and ASP.NET Core SignalR the current technology?

ASP.NET SignalR is still supported, but we are not investing in new features for it. For more info, see this post https://devblogs.microsoft.com/aspnet/the-future-of-asp-net-signalr/.
