### ISSUE TITLE
HTTP/3: UseHttps configuration

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34858]
Ensure that we set any options configured with UseHttps with HTTP/3. Some values might not be supported by QUIC.

**Comment by Tratcher** [comment]
Note the UseHttps overloads that take async callbacks probably won't work at all. Make sure they fail with reasonable errors.

The synchronous SNI callback is supposed to work.

**Comment by Tratcher** [comment]
HttpsConnectionAdapterOptions based UseHttps:
- [x] X509Certificate2? ServerCertificate
- [ ] Func<ConnectionContext, string?, X509Certificate2?>? ServerCertificateSelector
- [ ] ClientCertificateMode ClientCertificateMode
- [ ] Func<X509Certificate2, X509Chain?, SslPolicyErrors, bool>? ClientCertificateValidation
- [x] SslProtocols SslProtocols (N/A, TLS 1.3 is required)
- [ ] bool CheckCertificateRevocation
- [ ] AllowAnyClientCertificate()
- [ ] Action<ConnectionContext, SslServerAuthenticationOptions>? OnAuthenticate
- [ ] TimeSpan HandshakeTimeout

ServerOptionsSelectionCallback based UseHttps:
- [ ] UseHttps(this ListenOptions listenOptions, ServerOptionsSelectionCallback serverOptionsSelectionCallback, object state, TimeSpan handshakeTimeout)

TlsHandshakeCallbackOptions's based UseHttps
- [ ] Func<TlsHandshakeCallbackContext, ValueTask<SslServerAuthenticationOptions>> OnConnection
- [ ] object? OnConnectionState
- [ ] TimeSpan HandshakeTimeout

**Comment by Tratcher** [comment]
All of the unblocked items have been addressed for .NET 6. Moving to .NET 7.

**Comment by adityamandaleeka** [comment]
We need to ask for runtime APIs for the rest of these.

**Comment by JamesNK** [comment]
@Tratcher How many of the remaining options does runtime implementing [HTTP/3: QuicConnectionListener supports ServerOptionsSelectionCallback](https://github.com/dotnet/runtime/issues/49587) unblock? Are there other changes required from their side or is this it?

**Comment by JamesNK** [comment]
There is also https://github.com/dotnet/runtime/issues/55378 but it seems pretty minor.

**Comment by Tratcher** [comment]
Waiting on https://github.com/dotnet/runtime/issues/67560
