### ISSUE TITLE
HelixConstants Windows queue value

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#34866]
I saw a helix test failure which puzzled me: https://dev.azure.com/dnceng/public/_build/results?buildId=1263207&view=results. 

This test is marked to be skipped on Helix: https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/test/RazorPagesTemplateTest.cs#L38. I'm wondering if the issue here is that the short queue name for `HelixConstants.Windows10Arm64` isn't working properly: https://github.com/dotnet/aspnetcore/blob/main/src/Testing/src/xunit/HelixConstants.cs#L8. On the failing build, the queue that was used was: `Windows.10.Amd64.Server20H2.Open`.

FYI @dotnet/aspnet-build

**Comment by dougbu** [comment]
Looks like a transient test failure rather than a problem w/ the constants. Note `HelixConstants.Windows10Arm64` is about **ARM**64 and not **AMD**64.

**Comment by HaoK** [comment]
Yeah doesn't look like anything needs to be done here?  I'll close if so

**Comment by dougbu** [comment]
Sounds good @HaoK
