### ISSUE TITLE
Unity2018 impossible https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/5.0.8 Are you?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#34871]
Unity2018 impossible https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/5.0.8 Are you?

**Comment by BrennanConroy** [comment]
We are tracking unity work in https://github.com/dotnet/aspnetcore/issues/12102
