### ISSUE TITLE
ASP.NET Core - static web assets from nuget package (Radzen.Blazor, Microsoft Identity) load only when environment is Development, not when Staging or Production.

### ISSUE THREAD

**Issue by Dillion132** [dotnet/aspnetcore#34874]
### Describe the bug
I have a ASP.NET Core Blazor Server with Identity.
When I run in the Development environment ("ASPNETCORE_ENVIRONMENT": "Development") (in the launchSettings.json), everything works as expected. Specifically, the static web asset such as css and js files are loaded. Example: "~/Identity/css/site.css", "~/Identity/lib/jquery-validation/dist/jquery.validate.min.js".
But when I change the environment to Staging, all the files in "~/Identity/..." path are not found, returning 404 error. And it is not just my project. I created a brand new scaffolded Blazor app with Identity, and it behaves exactly the same. It appears Staging somehow affects sdk to not include embeded resources from .nuget.

This issue happens both in Asp.net Core 3.1 and Asp.net 5 application.

Besides, there have another error, in the Asp.net 5 Blazor application (the application name is "WebApplication1"), the _Host.cshtml page contains the `<link href="WebApplication1.styles.css" rel="stylesheet" />` tag, in the Development environment, everything is ok, but if using Staging or Production environment, this file will show the 404 error and the layout is broken. But this issue doesn't happen in Asp.net core 3.1 application

### To Reproduce

Create a New Asp.net core Blazor Server application and choose the Individual Accounts

![image](https://user-images.githubusercontent.com/16394302/127595326-26e4fe5a-b7e9-48ab-8a3e-d8013cb96b2a.png)

Then, in the launchSettings.json file, change the "ASPNETCORE_ENVIRONMENT" to "Staging" or "Production"

![image](https://user-images.githubusercontent.com/16394302/127595460-914cc8bc-5f7a-4698-8f0a-481dbb809636.png)

### Exceptions (if any)

Running the application, and click the Register or Login menu, use F12 developer Console tools to check it. You can see the error:

![image](https://user-images.githubusercontent.com/16394302/127595842-f5d73920-06ee-436c-bc6a-dbce78519399.png)

After deep research, find the following error:
  
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /Identity/css/site.css does not match an existing file
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/Identity/css/site.css'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' was rejected by constraint 'path':'Microsoft.AspNetCore.Routing.Constraints.NonFileNameRouteConstraint' with value 'Identity/css/site.css' for the request path '/Identity/css/site.css'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is not valid for the request path '/Identity/css/site.css'
>  
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' was rejected by constraint 'path':'Microsoft.AspNetCore.Routing.Constraints.NonFileNameRouteConstraint' with value 'blazorServerApp1.styles.css' for the request path '/blazorServerApp1.styles.css'
> Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Debug: Connection ID "18014398519682531329" disconnecting.
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 GET https://localhost:44350/css/open-iconic/font/css/open-iconic-bootstrap.min.css - - - 304 - text/css 58.7102ms
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is not valid for the request path '/blazorServerApp1.styles.css'
> 
> 'Microsoft.AspNetCore.Routing.Constraints.NonFileNameRouteConstraint

### Further technical details
- ASP.NET Core version: Asp.net core 3.1, Asp.net 5.0
- Include the output of `dotnet --info`
    ![image](https://user-images.githubusercontent.com/16394302/127596399-7ca0f105-dd16-48b8-8f0a-ca1a2d516f82.png)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version : Microsoft Visual Studio Community 2019 Version 16.10.2

**Comment by tn-5** [comment]
See: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class

Static web assets are only loaded automatically in the development environment. You need to manually add a call to webBuilder.UseStaticWebAssets() in startup to enable this for other environments.

**Comment by Dillion132** [comment]
Hi @tn-5,

Thanks a lot, after calling the `webBuilder.UseStaticWebAssets()`, everything works well.
