### ISSUE TITLE
Blazor is an absolute nightmare...

### ISSUE THREAD

**Issue by kevinbourassahoule** [dotnet/aspnetcore#34917]
... for all my front end code which will soon find itself sulking in the wake of my glorious Blazor app, its wings broadening the eclipse as it soars ever higher into .NET heavens.  

The mere fact that I can write C# in the browser and share code with my back end makes me tear up with holy pearls of disbelief that might just mend the still open wounds left by JS coercion.  I can't wait to send my  `JsFrameworks.OfType<JustKiddingNotTyped>().Where(x => x.YearsSinceRelease < 1).SelectManyAsF***(x => x.FlavourOfTheDay).ToOblivion()` and bore my children with tales of yore when the Great WebAssembly released us from bowing down to JavaScript The Tyrant.

Sure, there is still important work to be done, but it gives me hope for a better, more productive tomorrow, and I am 10000% cheering this project on.

Signed,

One stoked dev, to the wonderful Blazor team doing God's work and to the .NET team in general for developing a solid framework that left me longing to See Sharply in the browser ❤️

**Comment by En3Tho** [comment]
I'm not a frontend dev and I guess I will never be but working with Blazor, poking things, mixing F# and C# together was pure joy.

**Comment by realivanjx** [comment]
i dont think this is the place for rants

**Comment by kevinbourassahoule** [comment]
@realivanjx I mean I know that and expected this to close quickly, this is just the first place I thought I could show some love and support for these fine people!
