### ISSUE TITLE
signal/r client functional parity issue - httpConnectionOptions headers & connection upgrade to web sockets 

### ISSUE THREAD

**Issue by Simonl9l** [dotnet/aspnetcore#34911]
### Describe the bug
With the .Net Signal/R client, `httpConnectionOptions.headers` are propagated to the WebSockets upgrade request post the negotiate request.

However with the JavaScript client these headers are not propagated!

This creates a functional/behavioral inconsistency between Javascript and DotNet client libraries. We've not looked to see if other language libraries have the same issue.

The underlying use case is related to configuring sticky sessions in a multi host environment, and need for a user controlled distinguisher between requests to ensure the upgrade request is routed to the correct host given intermediate load balancing technologies.       

### To Reproduce

With multiple hosts running behind a load balancer....

.Net Client - [Microsoft.AspNetCore.SignalR.Client](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client) - 5.0.8

```C#

    var builder = new HubConnectionBuilder()
                .WithAutomaticReconnect()
                .WithUrl("<url>", opts => {
                    opts.Headers.Add("my-header", Guid.NewGuid().ToString());
                    opts.Transports = HttpTransportType.WebSockets;
                })
                .Build();

    hubConnection.Start(); // works!
```
Javascript - [@microsoft/signalr](https://www.npmjs.com/package/@microsoft/signalr) - 5.0.8

```Javascript
    let builder = new signalR.HubConnectionBuilder()
            .withAutomaticReconnect()
            .withUrl("<url>"));
          builder.configureLogging("debug");
          builder.httpConnectionOptions.headers = { "my-header": uuid.v4() };
          builder.httpConnectionOptions.transport = 1;
          
    let connection = builder.build();

    connection.start().then(async () => {
         // fail to establish connection as different host gets the upgrade request as we can't route due to the missing header.
      }
```

### Exceptions (if any)
No exception per see as the error is expected due to the inconsistent behavior per the log below:
```log
WebSocketTransport.js?eb1a:99 WebSocket connection to '<endpoint>' failed: Error during WebSocket handshake: Unexpected response code: 403
eval @ WebSocketTransport.js?eb1a:99
eval @ WebSocketTransport.js?eb1a:80
step @ WebSocketTransport.js?eb1a:41
eval @ WebSocketTransport.js?eb1a:22
eval @ WebSocketTransport.js?eb1a:16
__awaiter @ WebSocketTransport.js?eb1a:12
WebSocketTransport.connect @ WebSocketTransport.js?eb1a:62
HttpConnection.startTransport @ HttpConnection.js?da58:482
eval @ HttpConnection.js?da58:432
step @ HttpConnection.js?da58:41
eval @ HttpConnection.js?da58:22
eval @ HttpConnection.js?da58:16
__awaiter @ HttpConnection.js?da58:12
HttpConnection.createTransport @ HttpConnection.js?da58:385
eval @ HttpConnection.js?da58:301
step @ HttpConnection.js?da58:41
eval @ HttpConnection.js?da58:22
fulfilled @ HttpConnection.js?da58:13
Utils.js?7ed1:218 [2021-07-31T22:35:31.427Z] Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.
```

### Further technical details
- ASP.NET Core version - 5.0.302 
- Include the output of `dotnet --info`
```log
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by davidfowl** [comment]
You can't set headers in the web sockets upgrade request in the browser.

**Comment by BrennanConroy** [comment]
Yep, sorry we can't do anything here.

You can either move to a non-websocket transport, accept the difference and code defensively for it, or somehow convince all major browsers to finally allow setting headers for websocket requests https://github.com/whatwg/html/issues/3062

**Comment by Simonl9l** [comment]
@davidfowl & @BrennanConroy thanks for the speedy followup!

A tad disappointing that we find ourselves struggling to work around this gap, whilst heartened to know that the dotnet team are actively engaged in related conversations!

Thanks all!
