### ISSUE TITLE
Blazor: `BindConverter.TryConvertTo<bool>` throws an exception

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnetcore#34921]
### Describe the bug
very similar to #33587 but this time it's for bool type

### To Reproduce

```
<button @onclick="Click">Click</button>

@code{
    void Click()
    {
        string boolString = "True";
        Console.WriteLine(BindConverter.TryConvertTo<bool>(boolString, System.Globalization.CultureInfo.CurrentCulture, out var boolValue)); 
    }
}
```

### Exceptions (if any)

      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.BindConverter.ConvertToBoolCore(Object obj, CultureInfo culture, Boolean& value)
   at Microsoft.AspNetCore.Components.BindConverter.TryConvertTo[Boolean](Object obj, CultureInfo culture, Boolean& value)
### Further technical details
- ASP.NET Core version 5.x
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@anranruye thanks for contacting us.

We should probably give it the same treatment as we did for Guid

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The underlying issue here is already being worked on as part of #34816
