### ISSUE TITLE
Several issues with MessagePack when building asp net core 5

### ISSUE THREAD

**Issue by DaniilMonin** [dotnet/aspnetcore#34926]
I'm stuck with building asp dot net core 5.0 on Windows 10

I followed the instruction but have no luck with it. The output of build.cmd reporting me several errors that some files are missed in MessagePack

> CCS2001: File not found "..mvc\source\aspnetcore\src\submodules\MessagePack-CSharp\src\MessagePack.UnityClient\Assets\Scripts\MessagePack\T4\MessagePackReader.Integers.cs".

> CCS2001: File not found "..mvc\source\aspnetcore\src\submodules\MessagePack-CSharp\src\MessagePack.UnityClient\Assets\Scripts\MessagePack\MessagePackSerializationException.cs".

fix_symlinks.bat in MessagaPack.UnityClient doesn't fix this.

Could anybody help me with it what I missed?

My steps are (commit 3f873035c9ee96c4e4e93a9d3966baf3ef02581a)
1. restore.cmd
2. build.cmd

Thank you!

**Comment by Pilchie** [comment]
I suspect that when you made your local clone, you didn't get the submodules set up correctly.  See https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#cloning-your-repo-locally for the instructions.

**Comment by DaniilMonin** [comment]
> I suspect that when you made your local clone, you didn't get the submodules set up correctly. See https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#cloning-your-repo-locally for the instructions.

Thanks! I missed step about submodules. Now build process is ok with MessagePack but I get another errors.

> ..\mvc\source\aspnetcore\eng\targets\Npm.Common.targets(79,5): error : in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. [..\mvc\source\aspnetcore\src\Components\Web.JS\Microsoft.AspNetCore.Components.Web.JS.npmproj]                                                                                                                                                                                                                 

> ..\mvc\source\aspnetcore\.dotnet\sdk\5.0.205\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(326,5): error MSB4018: task failed unexpectedly "ResolveTargetingPackAssets". [..\mvc\source\aspnetcore\src\Components\WebAssembly\DevServer\src\Microsoft.AspNetCore.Components.WebAssembly.DevServer.csproj]              

> ..\mvc\source\aspnetcore\.dotnet\sdk\5.0.205\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(326,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path '..\mvc\source\aspnetcore\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0\data\FrameworkList.xml'.

**Comment by Pilchie** [comment]
I haven't seen those.  @dotnet/aspnet-build, any ideas?

**Comment by wtgodbe** [comment]
> ..\mvc\source\aspnetcore.dotnet\sdk\5.0.205\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(326,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path '..\mvc\source\aspnetcore\\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0\data\FrameworkList.xml'.

That is surprising, the FrameworkList.xml should exist at that location after running `restore.cmd`. Could you confirm whether or not there is a `.dotnet` folder present in the repo root after running restore, and whether or not it contains the file specified in the error message?

**Comment by wtgodbe** [comment]
As for the first error, you could try setting the following property to `true`:

https://github.com/dotnet/aspnetcore/blob/3f873035c9ee96c4e4e93a9d3966baf3ef02581a/eng/targets/Npm.Common.props#L11

**Comment by DaniilMonin** [comment]
> > ..\mvc\source\aspnetcore.dotnet\sdk\5.0.205\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(326,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path '..\mvc\source\aspnetcore\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0\data\FrameworkList.xml'.
> 
> That is surprising, the FrameworkList.xml should exist at that location after running `restore.cmd`. Could you confirm whether or not there is a `.dotnet` folder present in the repo root after running restore, and whether or not it contains the file specified in the error message?

@wtgodbe I see the folder but no any files or folders in it. Simply empty. Restore command finished successfully no any errors detected.

> PS ..\mvc\source\aspnetcore> ls .dotnet\packs\Microsoft.AspNetCore.App.Ref\
>     Directory: E:\LevelUp\mvc\source\aspnetcore\.dotnet\packs\Microsoft.AspNetCore.App.Ref
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d-----        31.07.2021     18:34                3.1.10
> d-----        31.07.2021     15:37                5.0.0
> 
> PS ..\mvc\source\aspnetcore> ls .\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0\
> PS ..\mvc\source\aspnetcore>

Thanks!

**Comment by wtgodbe** [comment]
Interesting - for now, could you try deleting the `.dotnet` folder and re-running `restore.cmd`?

@bekir-ozturk do you know of a reason dotnet-install would create but not populate the `aspnetcore.app.ref` folders under `packs`?

**Comment by DaniilMonin** [comment]
Fantastic! Thank you! Now everything is ok. No any errors after running `build.cmd`.

Do I need to provide more information or I just can close this issue?

**Comment by wtgodbe** [comment]
If everything is working we can close this, it was likely a machine state issue.
