### ISSUE TITLE
FindFirstValue(ClaimTypes.Email) returns null

### ISSUE THREAD

**Issue by stephenwilson1984** [dotnet/aspnetcore#34937]
Hi guys,

I'm trying to use this in .NET 6 using VS 2022 Preview and it still seems to be broken as per the original bug.

`principal.FindFirstValue(ClaimTypes.NameIdentifier);` - Works fine.
`principal.FindFirstValue(ClaimTypes.Email);` - Returns null.

I can see from the list of claims that only `NameIdentifier` seems to be added.

![Claims List](https://user-images.githubusercontent.com/20183602/127858330-e815b2cb-ce60-400a-88d1-501734eb7a87.png)

I saw from one of the original bugs that email was now added by default to the list of claims.  Is there a way to add multiple claims in the `Startup.cs` class as `ClaimTypes.Name` doesn't work either.

_Originally posted by @stephenwilson1984 in https://github.com/dotnet/aspnetcore/issues/18580#issuecomment-890966169_

**Comment by blowdart** [comment]
@HaoK as you did the original PR

@stephenwilson1984 To confirm this using asp.net identity? Not AAD or anything else? I see an audience claim there of API, so is identity server in the mix here, (this would mean it's not the linked bug but an IS configuration issue)?

**Comment by stephenwilson1984** [comment]
Hi,

This is using the Angular Project Template with Build In User Accounts (EF Core).  

`services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
     .AddEntityFrameworkStores<ApplicationDbContext>();`

`services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

`services.AddAuthentication()
    .AddIdentityServerJwt();`

I'm happy to be told this is a configuration issue and what the configuration should be or where to find it.

**Comment by HaoK** [comment]
Right, the PR that was merged was only for identity/cookies, that PR has no effect on principals created from AddIdentityServerJwt()

**Comment by blowdart** [comment]
Yup, this is a configuration issue.  I don't know how to ask for more in angular, @javiercn do you have an idea?
