### ISSUE TITLE
Default ASP.NET 6 SPA Angular template can't find the ssl certificate files. 

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/aspnetcore#34946]
I use VS 2022 2.1 and i create default Angular SPA template. Unfortunately it can't find the ssl cerificate files. This is how default is configured. 

`"start:windows": "ng serve --port 5002 --ssl --ssl-cert %APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem --ssl-key %APPDATA%\\ASP.NET\\https\\%npm_package_name%.key",`

And i get below exception when i run `npm start` command in `ClientApp` folder

```
An unhandled exception occurred: ENOENT: no such file or directory, open 'C:\Users\ffres\source\repos\Project15\Project15\ClientApp\%APPDATA%\ASP.NET\https\%npm_package_name%.key'
See "C:\Users\ffres\AppData\Local\Temp\ng-9BYxeG\angular-errors.log" for further details.
```

I can reproduce issue again and again by creating new angular spa project template.

**Comment by YakupIpek** [comment]
I will be happy if somone can show me how to handle this issue.

**Comment by YakupIpek** [comment]
@javiercn any update on this ?

**Comment by javiercn** [comment]
@YakupIpek can you give us more details about your environment?

Are you on a windows machine? I'm not able to repro the issue on my machine.

Can you give us more details about your environment? (Is this windows, linux, mac os)

Is `%APPDATA%` not defined as an environment variable in your case? does the folder `%APPDATA%/ASP.NET/https` not exist in your machine? (You can create it manually and see if that fixes the issue)

**Comment by YakupIpek** [comment]
@javiercn Yes i am on windows 10 os and it is able to find the files if i set fullpath of the files. Directory and files are exist. 

Do i have to define %AppData% as environment variable explicitly ?

**Comment by javiercn** [comment]
No, it should be defined. I just deleted my own folder and it just recreates it (as expected) without issue. 

I'm trying to find what's different on you machine. Can you tell us your node and npm versions?

**Comment by javiercn** [comment]
For reference, here are the ones I'm using:
```
> node -v
v15.12.0
> npm -v
6.14.13
```

**Comment by YakupIpek** [comment]
I run them in package manager console and results are 

```
PM> node -v
v15.11.0
PM> npm -v
7.6.0
```

**Comment by javiercn** [comment]
Can you go to `ClientApp\aspnetcore-https.js` and add a `console.log(baseFolder)` to see what is being used?

```
// This script sets up HTTPS for the application using the ASP.NET Core HTTPS certificate
const fs = require('fs');
const spawn = require('child_process').spawn;
const path = require('path');

const baseFolder =
  process.env.APPDATA !== undefined && process.env.APPDATA !== ''
    ? `${process.env.APPDATA}/ASP.NET/https`
    : `${process.env.HOME}/.aspnet/https`;

console.log(baseFolder);

const certificateArg = process.argv.map(arg => arg.match(/--name=(?<value>.+)/i)).filter(Boolean)[0];
const certificateName = certificateArg ? certificateArg.groups.value : process.env.npm_package_name;

if (!certificateName) {
  console.error('Invalid certificate name. Run this script in the context of an npm/yarn script or pass --name=<<app>> explicitly.')
  process.exit(-1);
}

const certFilePath = path.join(baseFolder, `${certificateName}.pem`);
const keyFilePath = path.join(baseFolder, `${certificateName}.key`);

console.log(certFilePath);
console.log(keyFilePath);

if (!fs.existsSync(certFilePath) || !fs.existsSync(keyFilePath)) {
  spawn('dotnet', [
    'dev-certs',
    'https',
    '--export-path',
    certFilePath,
    '--format',
    'Pem',
    '--no-password',
  ], { stdio: 'inherit', })
  .on('exit', (code) => process.exit(code));
}

```

**Comment by javiercn** [comment]
I suspect it might be the npm version? I believe we had troubles with npm 7 when updating the templates.

**Comment by YakupIpek** [comment]
@javiercn 
This is what i see and path has mixed /\ characters. 

```
> project18@0.0.0 prestart
> node aspnetcore-https

C:\Users\ffres\AppData\Roaming/ASP.NET/https

> project18@0.0.0 start
> run-script-os


> project18@0.0.0 start:windows
> ng serve --port 5002 --ssl --ssl-cert %APPDATA%\ASP.NET\https\%npm_package_name%.pem --ssl-key %APPDATA%\ASP.NET\https\%npm_package_name%.key

Node.js version v15.11.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.

```

**Comment by javiercn** [comment]
I updated to the latest NPM version and I'm still not able to repro.

I think this must be something specific to your machine setup (not exactly sure what). I suggest checking the two things I mentioned and see if that way we can make progress here.
* log the paths to the console when the app runs.
* follow the instructions on the npm update guide

```
> npm -v
7.20.6
```

**Comment by javiercn** [comment]
The mixed characters should not matter.

If you go to powershell and do `test-path <<your-path>>` it will return true, both separators are acceptable on windows.

One quick you can try is to replace `/` with `\` or vice-versa, but I suspect it won't matter (I'm happy to be proven wrong though!).

**Comment by YakupIpek** [comment]
File browser is able to go to correct location despite those different seperator characters.

**Comment by YakupIpek** [comment]
Yes `test-path`  returns true

**Comment by javiercn** [comment]
what happens if you go to the clientapp folder and run `node aspnetcore-https --name=<<your-app-name>>`

**Comment by YakupIpek** [comment]
This is result
```
PS C:\Users\ffres\source\repos\Project18\Project18\ClientApp> node aspnetcore-https --name=project18
C:\Users\ffres\AppData\Roaming/ASP.NET/https
```

**Comment by YakupIpek** [comment]
This is my file and it is actually default 

```
// This script sets up HTTPS for the application using the ASP.NET Core HTTPS certificate
const fs = require('fs');
const spawn = require('child_process').spawn;
const path = require('path');

const baseFolder =
  process.env.APPDATA !== undefined && process.env.APPDATA !== ''
    ? `${process.env.APPDATA}/ASP.NET/https`
    : `${process.env.HOME}/.aspnet/https`;

console.log(baseFolder);

const certificateArg = process.argv.map(arg => arg.match(/--name=(?<value>.+)/i)).filter(Boolean)[0];
const certificateName = certificateArg ? certificateArg.groups.value : process.env.npm_package_name;

if (!certificateName) {
  console.error('Invalid certificate name. Run this script in the context of an npm/yarn script or pass --name=<<app>> explicitly.')
  process.exit(-1);
}

const certFilePath = path.join(baseFolder, `${certificateName}.pem`);
const keyFilePath = path.join(baseFolder, `${certificateName}.key`);

if (!fs.existsSync(certFilePath) || !fs.existsSync(keyFilePath)) {
  spawn('dotnet', [
    'dev-certs',
    'https',
    '--export-path',
    certFilePath,
    '--format',
    'Pem',
    '--no-password',
  ], { stdio: 'inherit', })
  .on('exit', (code) => process.exit(code));
}


```

**Comment by javiercn** [comment]
Can you log the values for `certFilePath` and `keyFilePath`?

**Comment by YakupIpek** [comment]
console.log(certFilePath);
console.log(keyFilePath);

this is results. 
C:\Users\ffres\AppData\Roaming\ASP.NET\https\project18.pem
C:\Users\ffres\AppData\Roaming\ASP.NET\https\project18.key

test-path returns true for both of these paths

@javiercn

**Comment by javiercn** [comment]
Are you trying to run on WSL or a Docker container? (trying to think of what's going on here).

Let's try and run manually
`dotnet dev-certs https --export-path C:\Users\ffres\AppData\Roaming\ASP.NET\https\project18.pem --format Pem --no-password` and check that it succeeds

**Comment by YakupIpek** [comment]
```
dotnet dev-certs https --export-path C:\Users\ffres\AppData\Roaming\ASP.NET\https\project18.pem --format Pem --no-password

A valid HTTPS certificate is already present.
```

**Comment by javiercn** [comment]
@YakupIpek do you get a call stack when you look at `C:\Users\ffres\AppData\Local\Temp\ng-9BYxeG\angular-errors.log`?

**Comment by YakupIpek** [comment]
```
[error] Error: ENOENT: no such file or directory, open 'C:\Users\ffres\AppData\Roaming\ASP.NET\https\%npm_package_name%.key'
    at Object.openSync (node:fs:506:3)
    at Object.readFileSync (node:fs:402:35)
    at getSslConfig (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\webpack\configs\dev-server.js:140:23)
    at Object.getDevServerConfig (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\webpack\configs\dev-server.js:84:20)
    at C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:129:23
    at generateWebpackConfig (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:40:49)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async generateBrowserWebpackConfigFromContext (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:20)
    at async Object.generateI18nBrowserWebpackConfigFromContext (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:47:20)
    at async setup (C:\Users\ffres\source\repos\Project18\Project18\ClientApp\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:128:47)
```

**Comment by javiercn** [comment]
Can you also try going to the ClientApp project and running `npm start` from there? If that doesn't work or doesn't give more info. Try running `ng serve --port 5002 --ssl --ssl-cert <<path-to-cert>> --ssl-key <<path-to-cert-key>>`

**Comment by javiercn** [comment]
let's try this, replace the environment variables with the literal values and lets see if that gets it to work, I think we are getting closer, thanks for the patience here.

**Comment by YakupIpek** [comment]
```
PS C:\Users\ffres\source\repos\Project18\Project18\ClientApp>  npm start

> project18@0.0.0 prestart
> node aspnetcore-https

> project18@0.0.0 start
> run-script-os


> project18@0.0.0 start:windows
> ng serve --port 5002 --ssl --ssl-cert C:\Users\ffres\AppData\Roaming\ASP.NET\https\%npm_package_name%.pem --ssl-key C:\Users\ffres\AppData\Roaming\ASP.NET\https\%npm_package_name%.key

Node.js version v15.11.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
An unhandled exception occurred: ENOENT: no such file or directory, open 'C:\Users\ffres\AppData\Roaming\ASP.NET\https\%npm_package_name%.key'
See "C:\Users\ffres\AppData\Local\Temp\ng-3jBZmR\angular-errors.log" for further details.
```

**Comment by javiercn** [comment]
@YakupIpek replace %npm_package_name% with the value of the "name" field in your package.json within the start:windows value.

I believe for some reason that environment variable is not being replaced in your projects (it looks like a weird npm issue, since those variables are available to use in the package and on scripts)

**Comment by YakupIpek** [comment]
It still goes to wrong location 

`C:\Users\ffres\source\repos\Project18\Project18\ClientApp\%APPDATA%\ASP.NET\https\project18.key`
```
An unhandled exception occurred: ENOENT: no such file or directory, open 'C:\Users\ffres\source\repos\Project18\Project18\ClientApp\%APPDATA%\ASP.NET\https\project18.key'
See "C:\Users\ffres\AppData\Local\Temp\ng-yyyXuH\angular-errors.log" for further details.
```

**Comment by javiercn** [comment]
@YakupIpek what if you replace %APPDATA% with the literal value

**Comment by YakupIpek** [comment]
It works when it is replaced

**Comment by javiercn** [comment]
@YakupIpek can you check the steps described in https://docs.npmjs.com/try-the-latest-stable-version-of-npm#upgrading-on-windows to see if you are running into this issue? It seems potentially related to your problem

**Comment by YakupIpek** [comment]
Yes i tried those and now it works finally :) Thank you very much for your effort.
