### ISSUE TITLE
Angular project template doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34954]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Angular-project-template-doesnt-work/1491601)._

---
1. dotnet new angular
2. npm i

error ERESOLVE unable to resolve dependency tree ....

I have the latest versions installed: Nodejs 14, npm, .NET 6.0.100-preview

---
#### Feedback Bot on 8/2/2021, 01:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Can't repro this with RC1
![image](https://user-images.githubusercontent.com/6995051/129718023-ef722b29-f40f-4080-af74-838c7e29726b.png)

```
> npm -v
6.14.13
> node -v
v15.12.0
```
