### ISSUE TITLE
Semi-colon on-type-formatting can easily break @{} scenarios

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#34965]
![PXeDnI0qX9](https://user-images.githubusercontent.com/2008729/127948567-e7c9204d-95f3-4417-8a80-f31f52b1d83a.gif)

/cc @davidwengier is this a regression?

**Comment by davidwengier** [comment]
I did make a change in this area to allow these to remain on a single line when formatting, so it could be a bug due to that I guess. Not sure.

Also reported in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1354641

**Comment by davidwengier** [comment]
Doesn't look like this is because of my changes. Seems the C# formatter is removing the newline after the `@{` for some reason ¯\\\_(ツ)_/¯
