### ISSUE TITLE
blazorserver.styles.css sometimes will 404

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#34967]
I don't have a consistent repro for this but @danroth27 experienced forms of this while looking at bootstrap 5 templates with me and also witnessed it via screen share.

Repro steps: (happened using sdk main builds from dotnet/installer as well as local project templates in my branch)
dotnet new blazorserver
dotnet run

Look at browser (css styles will be busted due to the styles bundle returning a 404)

cc @javiercn

**Comment by javiercn** [comment]
I haven't experienced this myself, so given that we don't have a repro, I'm going to close it. If you or @danroth27 can come up with repro steps, I'll be happy to take a look.
