### ISSUE TITLE
MapWhen finds controllers despite not being mapped

### ISSUE THREAD

**Issue by msft-mw** [dotnet/aspnetcore#34964]
### Describe the bug
`MapWhen` that calls `UseEndpoints` and only maps health checks still routes to controllers that are mapped outside of the `MapWhen`.

Using the below repro code, `curl -v http://localhost:8080/time` returns `200 OK` and the current time, where I would expect it to 404 due to the `MapWhen` condition being met by the port, and the branch not mapping controllers.

### To Reproduce
```csharp
namespace Ports
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;

    [Route("time")]
    public class TimeController : Controller
    {
        public Task<IActionResult> Get()
        {
            return Task.FromResult<IActionResult>(Ok($"{DateTimeOffset.UtcNow.LocalDateTime}"));
        }
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.MapWhen(
                ctx => ctx.Connection.LocalPort == 8080,
                iab =>
                {
                    iab.UseRouting();
                    // don't map controllers
                    iab.UseEndpoints(builder => builder.MapHealthChecks("health/check").RequireHost("*:8080"));
                });

            app.UseEndpoints(builder => builder.MapControllers());
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddHealthChecks();
        }
    }

    public class Program
    {
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(
                    webBuilder =>
                    {
                        webBuilder.UseStartup<Startup>();
                        webBuilder.UseUrls("http://*:5000", "https://*:5001", "http://*:8080");
                    });

        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }
    }
}

```

### Exceptions (if any)
N/A

### Further technical details
- ASP.NET Core version: net5.0
- Include the output of `dotnet --info`
```text
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2019 - 16.10.4

**Comment by Vake93** [comment]
Since you have added `app.UseEndpoints(builder => builder.MapControllers());` at the end of Configure method all the controllers are still being mapped for all pipelines. 

You would need to map the controllers in a different pipeline to achieve the expected behaviour. One approach is,

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.MapWhen(
        ctx => ctx.Connection.LocalPort == 8080,
        iab =>
        {
            iab.UseRouting();
            iab.UseEndpoints(builder => builder.MapHealthChecks("health/check").RequireHost("*:8080"));
        });

    app.MapWhen(
        ctx => ctx.Connection.LocalPort != 8080,
        iab =>
        {
            iab.UseRouting();
            iab.UseEndpoints(builder => builder.MapControllers());
        });
}
```

**Comment by msft-mw** [comment]
> Since you have added `app.UseEndpoints(builder => builder.MapControllers());` at the end of Configure method all the controllers are still being mapped for all pipelines.
> 
> You would need to map the controllers in a different pipeline to achieve the expected behaviour. One approach is,
> 
> ```cs
> public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
> {
>     if (env.IsDevelopment())
>     {
>         app.UseDeveloperExceptionPage();
>     }
> 
>     app.MapWhen(
>         ctx => ctx.Connection.LocalPort == 8080,
>         iab =>
>         {
>             iab.UseRouting();
>             iab.UseEndpoints(builder => builder.MapHealthChecks("health/check").RequireHost("*:8080"));
>         });
> 
>     app.MapWhen(
>         ctx => ctx.Connection.LocalPort != 8080,
>         iab =>
>         {
>             iab.UseRouting();
>             iab.UseEndpoints(builder => builder.MapControllers());
>         });
> }
> ```

Hi Vake93, thank you for the reply. I'm not sure why this: 

> all the controllers are still being mapped for all pipelines.

happens, would you be able to elaborate? The documentation for `MapWhen` says that it branches the pipeline, so I don't understand why calling `MapControllers` at the end would affect all the branches, and not just the "primary" branch. I thought that since I had to call `AddRouting` again in my `MapWhen`, that the branch was distinct and changes made afterwards wouldn't affect it?

**Comment by Vake93** [comment]
If you see how the MapWhen Extension method works I think you would understand why this happens:
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/Extensions/MapWhenExtensions.cs
and here is the MapWhenMiddleware:
https://github.com/dotnet/aspnetcore/blob/53d052eb2636c8ffe1a752c54371cc745400d5ab/src/Http/Http.Abstractions/src/Extensions/MapWhenMiddleware.cs

The Request Processing pipeline the code created for your example is:

.... -> RoutingMiddleware -> MapWhenMiddleware  -> if the predicate evals to true  GOTO 1 ELSE 2
1 -> EndpointMiddleware (with Health Checks) -> 2
2 -> EndpointMiddleware  (with controllers)

**Comment by Vake93** [comment]
You interpreted it correctly I think my initial example made things worse. The issue is the branching happens after the routing middleware is added. So for both cases, the controllers respond with the results.

I think the best way for you to approach this is to add the routing after the branching has happened. 

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app
        .MapWhen(
            ctx => ctx.Connection.LocalPort == 8080,
            iab =>
            {
                iab.UseRouting();
                iab.UseEndpoints(builder => builder.MapHealthChecks("health/check").RequireHost("*:8080"));
            });

    app
        .UseRouting()
        .UseEndpoints(builder => builder.MapControllers());
}
```

**Comment by msft-mw** [comment]
Thank you, I'll give that a shot. I did see in my condition that `ctx.GetEndpoint()` returned a not-null `Endpoint`, but I didn't understand that it would match even if I hadn't mapped any controllers yet. I think I need to better understand the interaction between `UseRouting` and `UseEndpoints`.

I'll update as soon as I can try out your proposed solution.

**Comment by msft-mw** [comment]
That did seem to work, thank you for the help! I'm curious if you would use `RequireHost` in combination with the `MapWhen` condition that can also restrict ports, or if having the extra limitation is recommended.
