### ISSUE TITLE
Hot reload script 'aspnetcore-browser-refresh.js' connection issues

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#34975]
When running `StandaloneApp` directly using VS from the `aspnetcore` repo, it tries to open a websocket connection to `ws://localhost:63433/StandaloneApp/` (which seems a bit strange to me - I don't know why the `StandaloneApp` sub-path is there, since the app is running from the root). It fails with:

```
aspnetcore-browser-refresh.js:227 WebSocket connection to 'ws://localhost:63433/StandaloneApp/' failed: Error during WebSocket handshake: 'Sec-WebSocket-Protocol' header value '' in response does not match any of sent values
```

The headers look like:

![image](https://user-images.githubusercontent.com/1101362/128006187-627d781a-6df3-4f28-827c-a4bfdf3f5c5d.png)

Secondly, and I'm not certain whether this is an issue or not, but I've noticed that when we inject the script element for `aspnetcore-browser-refresh.js` itself, it looks like this:

```html
<script src="/_framework/aspnetcore-browser-refresh.js"></script>
```

I find the leading slash on that very suspicious. I would have expected the URL to be `_framework/aspnetcore-browser-refresh.js` *without* a leading slash, in case the `<base href>` specifies a nonroot location for the application. Do we know for sure this works correctly with apps that are not running at the origin root?

**Comment by SteveSandersonMS** [comment]
Update: This also entirely breaks launching the E2E test app from VS.

Steps:

 * Set `Components.TestServer` as startup project
 * Ctrl+F5
 * In the browser window, click the link for *Dev server client-side blazor*
 * See exception and no other UI

**Comment by SteveSandersonMS** [comment]
@pranavkm Do you think this is something we need to prioritize for RC1 if we are going to have hot reload working again?

**Comment by Wendelldh** [comment]
Hi. Just in case it might help with diagnosis.. 
I am seeing the same error after updating to the latest preview bits yesterday.....

aspnetcore-browser-refresh.js:227 WebSocket connection to 'ws://localhost:53804/Whays.Api.Rest/' failed: Error during WebSocket handshake: 'Sec-WebSocket-Protocol' header value '' in response does not match any of sent values ..

**Comment by captainsafia** [comment]
CTI is also running into this in https://github.com/aspnet/AspNetCore-ManualTests/issues/818.

**Comment by pranavkm** [comment]
Thanks @SteveSandersonMS. I've sent the CTI issue over to @BillHiebert since it looks like the app name is a VS specific thing. I have a PR that removes the leading slash since that also affects dotnet-watch if the page is being served from a non-root base path.
