### ISSUE TITLE
SignalR force close client connection

### ISSUE THREAD

**Issue by maxima120** [dotnet/aspnetcore#34979]
In a scenario when server needs to have 100% control over SignalR clients (which in my view - must be always :)) for security and business logic sake (eg a subscription expired or user tries to hack connection by manipulating client side etc) - having something like the below would really help (in fact - I think this is the only way to do it properly):

`hub.Clients.Client(connectionId).Close();`

### Additional context
*it appears that implementing authorization on SignalR using Angular with IdentityServer is unfeasible without re-writing client side completely and taking all the security responsibility for the whole app, while you only need to authorize signalr*, 

see here: https://github.com/dotnet/aspnetcore/issues/34948#issuecomment-891324176

**Comment by davidfowl** [comment]
I'm not sure how the additional context is related to the request here. This is a duplicate of https://github.com/dotnet/aspnetcore/issues/34481

**Comment by maxima120** [comment]
the use of HubCallerContext.Abort works. Thank you.
The other issue related to this one in a sense - as authorization is a workaround rather than a "native" solution - Abort is needed to strengthen my personal insecurity feeling about it :)

**Comment by davidfowl** [comment]
In .NET 6  we will automatically abort the connection if the auth token is expired

**Comment by maxima120** [comment]
sorry - I wasnt clear - the linked ticket was about not able to make use of asp.net core authorization (when Identity Server is involved), so I made a surrogate "authorization" which is a hack rather, so I need to be able to Abort manually.

**Comment by davidfowl** [comment]
Well you can use auth, but its per connection instead of per call.

**Comment by maxima120** [comment]
I cant - see the linked ticket. Also I actually want it to be per connection..

**Comment by davidfowl** [comment]
Not sure why you can't, I've read the issue. Why cant' you get the access token and pass it to signalr?

**Comment by maxima120** [comment]
the "angular with identity" template uses identity server 4 and it has separate root from angular app (for security and thats the main point why i dont want to change that). however to get access token i need to (according to multiple blogs and Brennan advice and considering zero answers on stackoverflow) write different auth flow where angular has a "auth service" and actively hacking into auth http headers and it also has few pages code.. comparing to no hacking, no code and everything is secure right now.. so i gave up on that idea...

i do believe there is some other way to do it without hacking but i simply cant find it.. the "workaround" i invented seems secure enough for signalr (for my needs) and it **doesnt affect the rest of the app security at all**.. which is the main point for me.

**Comment by maxima120** [comment]
P.S. if you are so keen on it - I can quickly implement the token factory and extraction of the token on server side and you just add code into the token factory getting the actual token, if you think it is that simple ;) [you probably spent more time already trying to understand whats happening] :)

**Comment by maxima120** [comment]
yeah you were both (you and Brennan) right. I was blinded by the frustration reading blogs which only shows how to implement access token client-side writing it in Authorization header pushing it back to server.

There is already authorization.service.ts generated by the template:

so the use is trivial:
```
import { AuthorizeService } from '../../api-authorization/authorize.service';

constructor( . . . , authsrv: AuthorizeService) {

      this.hub = new HubConnectionBuilder()
        .withUrl("/newshub", { accessTokenFactory: () => authsrv.getAccessToken().toPromise() })
```
