### ISSUE TITLE
Bad handling of complete logout in RemoteAuthenticatorViewCore.ProcessLogOutCallback

### ISSUE THREAD

**Issue by RemiBou** [dotnet/aspnetcore#34990]
### Describe the bug
In Blazor WASM when CompleteSignOutAsync returns  RemoteAuthenticationStatus.OperationCompleted:, nothing is done, so the message "Processing logout callback..." is still displayed
### To Reproduce
Implement https://auth0.com/blog/securing-blazor-webassembly-apps/

### Suggested fix
Merge Success and OperationCompleted switch branch
```

 case RemoteAuthenticationStatus.OperationCompleted:
case RemoteAuthenticationStatus.Success:
                    await OnLogOutSucceeded.InvokeAsync(result.State);
                    await NavigateToReturnUrl(GetReturnUrl(result.State, Navigation.ToAbsoluteUri(ApplicationPaths.LogOutSucceededPath).ToString()));
                    break;

```

### Further technical details
- ASP.NET Core version : 5.0.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
