### ISSUE TITLE
Allow disabling the browser refresh middleware

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#34994]
### Is your feature request related to a problem? Please describe.
Related to https://github.com/dotnet/aspnetcore/issues/34951 currently we inject this middleware into the pipeline in Visual Studio and when using dotnet watch. 

### Describe the solution you'd like
There should be a way to disable it via a launch setting or environment variable.

**Comment by mkArtakMSFT** [comment]
Closing as such functionality already exists: https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/dotnet-watch/DotNetWatchOptions.cs#L20
