### ISSUE TITLE
DataProtection support for symmetric encryption/decryption & containerization.

### ISSUE THREAD

**Issue by Cephei** [dotnet/aspnetcore#35004]
I'm personally not interested in DPAPI or DPAPI-NG based solutions as we're looking to eventually deploy our solution using containers - everything must be built cross-platform ready. With that in mind, I've been exploring the DataProtection APIs and I believe that I can use Kubernetes TLS Secrets to mount a volume for the crt/key.

### Is your feature request related to a problem? Please describe.
I'm mainly just curious whether there was a reason (perhaps security related) why the DP library doesn't provide out-of-the-box support for symmetric encryption/decryption of the persisted keyrings? It would be very easy for us to just use Opaque Kubernetes secrets as environment variables.

Is there any added advantage that I'm just not thinking through properly, why asymmetric crypto is needed here? Perhaps certificate expiration/rotation?

I've seen the articles related to XML Symmetric Encryption: https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-encrypt-xml-elements-with-symmetric-keys

**Comment by blowdart** [comment]
Because kubernetes wasn't a thing when it was written :)

Rotation is part of it, also there were easy ways to deploy certs in hosted environments rather than have a symmetric key, and certs are easily protected in a Windows OS (linux not so much). Also, the encryption and decryption code for asymmetric was part of the XML classes already, so we didn't need to roll our own.

**Comment by Cephei** [comment]
@blowdart Thanks for that information; it's much appreciated! I'm currently testing just with docker-swarm with a volume mount for a pem file and all seems to be working well. Looking forward to more features for DataProtection in .net 6.

Please feel free to close this issue or keep it open if it helps the team discussions in any way.
