### ISSUE TITLE
Override completions on-type-format incorrectly when they're the only member in an @code

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#35001]
![PSlHKxzt6P](https://user-images.githubusercontent.com/2008729/128067517-1f5024e2-7be6-4486-b1cd-4d9ab2052c83.gif)

**Comment by davidwengier** [comment]
This looks so much like what I'm working on now, it _must_ be something I broke recently... but when I commented out that bit of code the issues still occurred. So weird!
