### ISSUE TITLE
[Authorize] attribute is being ignored in MAUI Blazor, .NET 6 Preview 6

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#35034]
### Describe the bug
We have a project running on .NET 6 Preview 6 where we need to do Role Based authorization, 
but currently the [Authorize] attribute is being totally ignored.

This is the page
https://github.com/efonsecab/FairPlayTube/blob/maui-blazor-version/src/FairPlayTubeSln/FairPlayTube.MauiBlazor/FairPlayTube.MauiBlazor/Pages/Users/Pages/MyVideos.razor.cs

Startup.cs
https://github.com/efonsecab/FairPlayTube/blob/maui-blazor-version/src/FairPlayTubeSln/FairPlayTube.MauiBlazor/FairPlayTube.MauiBlazor/Startup.cs

### To Reproduce
* Create a MAUI Blazor application
* Create a page and restrict access using the [Authorize] attribute

The page executes despite a user not having the role configured

### Further technical details
- ASP.NET Core version: .NET 6 Preview 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Version 16.11.0 Preview 3.0

**Comment by pranavkm** [comment]
There's additional work you would need to do to configure your authorization including using `AuthorizedRouteView`. Have a look at the docs for authorization in Blazor - https://docs.microsoft.com/en-us/aspnet/core/blazor/security

**Comment by efonsecab** [comment]
> There's additional work you would need to do to configure your authorization including using `AuthorizedRouteView`. Have a look at the docs for authorization in Blazor - https://docs.microsoft.com/en-us/aspnet/core/blazor/security

Thanks, it worked.
These were the required changes: https://github.com/efonsecab/FairPlayTube/commit/49b25409060433f02bbacfd087605394ba3312ba
