### ISSUE TITLE
Inline declaration in Blazor @ref attribute

### ISSUE THREAD

**Issue by MarcoTheFirst** [dotnet/aspnetcore#35036]
## Background and Motivation
Blazor components often require references using the @ref attribute, be it for self-referencing purposes or to establish dependencies between components. Most of the time these references are only needed within the markup section of a component. So it is quite cumbersome to scroll down to the code block and add a new declaration for each single @ref. Also, the current approach bloats the code block with numerous "one-off" declarations. 

## Proposed API
The @ref attribute could be extended to allow direct inline declaration like so:

``` C#
<Component @ref="private component" />
```

or with optional attribute(s):

``` C#
<Component @ref="[Attribute] private component" />
```

This syntax would simply replace the identical declaration in the code section. The field's type could be omitted as suggested above, since it can be inferred from the component's declaration.

## Usage Examples

Consider the following scenario where  a component ref is only needed in the declaration itself. This would save one line of "unnecessary" variable declaration in the code block:

``` C#
<DateFilterOption @ref="private startDateFilter" TModel="Course" EqualsExpression="i => i.StartDate == startDateFilter.SelectedDate"></DateFilterOption>
```

## Alternative Designs
The inline declaration could also be accomplished by a second attribute:

``` C#
<Component @ref=component" @declare="private" />
```

This would eliminate some of the risks mentioned below, but it would also be less intuitive.

## Risks
The suggested approach is limited to declaring fields or auto-implemented properties at best. Complex property declarations with getters/setters are not advisable in this scenario. This limitation may confuse developers.

Another risk is the confusion between referencing existing fields and declaring a new one, since C# allows omission of the "private" keyword in regular declarations:

``` C#
Component comp;
//... is equal to ...
private Component comp;

//... so the suggested approach with inline declarations would contradict today's declaration pattern:

<Component @ref="component" />
//... is NOT equal to ...
<Component @ref="private component" />
```

**Comment by campersau** [comment]
Looks similar to https://github.com/dotnet/aspnetcore/issues/34826 

References:
- https://github.com/aspnet/Announcements/issues/381
- https://github.com/dotnet/aspnetcore/issues/13099

**Comment by MarcoTheFirst** [comment]
@campersau thanks, you're right. The difference being that my approach tries to prevent "background magic". It's just a declaration abbreviation and nothing's hidden from the developer. So I think it would be viable solution.

**Comment by MarcoTheFirst** [comment]
I just had another idea to remove any confusion and eliminate all risks: Two separate markup attributes could be used for the two purposes:

**@ref** -> stays as is
new: **@declare** -> allows inline declaration as suggested in my initial post. So the two scenarios would look like this:

**Referencing an existing field declaration from the code section:**
```C#
<Component @ref="component" />
```

**Declaring a new field inline and referencing in one step:**
```C#
<Component @declare="private component" /> 
```

This would remove the risk of confusing a declaration with a pure reference. In other words, the following syntax would also create a new private declaration according to the "global" C# rules:

```C#
<Component @declare="component" /> 
```

**Comment by javiercn** [comment]
@MarcoTheFirst thanks for contacting us.

@campersau already explained why this is not possible.

Adding declarations in component attributes is a big change for the language and not something we are planning to do at the moment.

**Comment by MarcoTheFirst** [comment]
I see it neither as a change nor as a complex addition. The blazor toolset already crreates hidden partial class files on-the-fly. Adding another attribute like @declare and writing that into the automated partial class file seems quite straightforward to me; and it would be in accordance with the paradigms that MS already applies to WinForms, WebForms, etc.

But fortunately 3rd party refactoring tools offer great help for auto-declaring such fields, so I suppose that'll have to make do.
