### ISSUE TITLE
HTTP/3: Remove non-final h3 ALPNs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#35032]
Should probably only have `h3` when .NET 7 RTM ships.

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/pull/34968/files#r682486016

It's only kept right now because of curl.

**Comment by wtgodbe** [comment]
So this is just about removing `h3-29` here once curl http3 tool recognizes `h3`? Do we know when that'll happen?

**Comment by Tratcher** [comment]
We should remove it before RTM regardless, but we'll wait until the last minute while we're testing with tools like curl.

**Comment by adityamandaleeka** [comment]
Still waiting for clients, but we should do this before end of 7.
