### ISSUE TITLE
Blazor components need a new lifecycle event, something like OnLostScope or OnUnrender?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35043]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-components-need-a-new-lifecycle-e/1494349)._

---
I'm loving Blazor over the last year and a half I've been working with it.
But I'm @inject'ing services that provide events - such as when a 'widget' changes.
My components want to hear about that event, and react to it.  Which means registering an event listener, ie, giving the publisher access to a method on an instance of my component.  
The issue being, there's no notification to the component when it is no longer being rendered.  Given the dependency injection nature of the service, the list of subscribers it holds prevents garbage collection on the component - and worse, the component still reacts to the event, because it was never disposed, and that's because its still in scope from the perspective of the publisher. 

Other than adding an IDisposable to each component, and then every container having responsibility of calling Dispose() on all instances of all components it has created - would be a nightmare.

We either need some loosely coupled event system (doesn't sound good for performance) or we need components to know when they're no longer being rendered, and using this opportunity to unregister themselves from all events, thus making it possible for the component to be garbage collected.

At the moment, we have to accept components are 'stored' and react to the OnParametersSet to reset them.  I'm calling this 'recycling'. This is ok for the moment, but not ideal.  Of course, if I didn't need to listen to events, it would be easy!  But having components respond to each other on screen, when there's no direct parent / child relationship is exactly what events are great for.  The common ground being the @inject'ed service that provides access to the event(s) to either publish or subscribe to.

So getting setup is great, and it all works.  But navigating from one "page" to another won't destroy (garbage collect) the components of the previous page, as described.

---
#### Feedback Bot on 8/4/2021, 02:32 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
> We either need some loosely coupled event system (doesn't sound good for performance) or we need components to know when they're no longer being rendered, and using this opportunity to unregister themselves from all events, thus making it possible for the component to be garbage collected.

Components do this by implementing `IDisposable` and unregistering. You can implement your own base class extending ComponentBase, implement IDisposable and expose an `OnDispose` method to register register callbacks from derived components to unregister from services.

**Comment by Simon-Miller** [comment]
@javiercn I appreciate components can implement the IDisposable interface (mine do), but in practice this doesn't seem to get called in my main project.  I've created an example project, with one service, with one event.  In this scenario, the Dispose is indeed being called, as you suggest.
But there's still an odd scenario where for example we use a pop-up window which as a component in and of itself, should have its own lifecycle. When it is no longer visible, the instance still remains, because of the parent / child relationship with the page component.  But its still listening to events, as described.  Not being rendered, but not disposed.

I have a boolean parameter to control visibility, and can hook into events when 'visible' and unhook from events when not. 
But ultimately, it would be nice for a component to know when it is being rendered or not.

**Comment by javiercn** [comment]
> But there's still an odd scenario where for example we use a pop-up window which as a component in and of itself, should have its own lifecycle. When it is no longer visible, the instance still remains, because of the parent / child relationship with the page component. But its still listening to events, as described. Not being rendered, but not disposed.
> 
> I have a boolean parameter to control visibility, and can hook into events when 'visible' and unhook from events when not.
> But ultimately, it would be nice for a component to know when it is being rendered or not.

That scenario seems specific to your app and what we encourage folks in those cases is to extend componentbase to fit add the pattern that works for them.

Every lifecycle event we add is a concept folks need to learn and take into account when creating their components and a complexity and perf hit that every component must pay, so we are unlikely to add something new unless there isn't a way to achieve it today and the majority of components would benefit from it.

In this case, it seems that you have some behavior tied to the visibility of your component, which is not required for the majority of components. For that reason we recommend adding that to your base class, however its not something we are interesting in adding.

While this not might match your expectations, I hope you can understand that every feature we add presents a trade-off and in this case we think the drawbacks outweigh the benefits.
