### ISSUE TITLE
[Routing] API review for pull/33712

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35042]
## Background and Motivation

We have issues with large route tables. And we've added a feature to avoid creating unnecessary nodes in our tree by evaluating constraint ahead of time and filtering nodes that would never produce a match.

## Proposed API

The interface we added allows you to filter nodes based on your parameter name or literal value. Our constraints implement this interface to proactively filter nodes that would never match.

```csharp
namespace Microsoft.AspNetCore.Routing
{
	public interface IParameterLiteralNodeMatchingPolicy : IParameterPolicy
	{
		bool MatchLiteral(string parameterName, string literal);
	}
}

namespace Microsoft.AspNetCore.Routing
{
	public interface IParameterLiteralNodeBuilderPolicy : IParameterPolicy
	{
		bool AppliesToLiteral(string parameterName, string literal);
	}
}
```

-->

## Usage Examples

This is typically associated with an IRouteConstraint

This is the excerpt from the route constraint:
``` C#
        private static bool CheckConstraintCore(string? valueString)
        {
            return Guid.TryParse(valueString, out _);
        }

        bool ILiteralConstraint.MatchLiteral(string parameterName, string literal)
        {
            return CheckConstraintCore(literal);
        }
```
-->

## Alternative Designs

None

## Risks

Low

**Comment by pranavkm** [comment]
API review:

Let's put this in a subnamespace:  `Microsoft.AspNetCore.Routing.Matching`

```C#
namespace Microsoft.AspNetCore.Routing.Matching;
public interface IParameterLiteralNodeMatchingPolicy : IParameterPolicy
{
    bool MatchesLiteral(string parameterName, string literal);
}
```
