### ISSUE TITLE
Tag SignalR-Client-Cpp project and update vcpkg port

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#35053]
The SignalR-Client-Cpp project has seen seen a few updates in the past 3-4 months, with msgpack functionality being the largest feature add in while.  

Can the project team tag the project and update the vcpkg port info? This will make it easy for vcpkg users to pick up the latest.

**Comment by BrennanConroy** [comment]
Wanted to wait for https://github.com/aspnet/SignalR-Client-Cpp/pull/66 before doing that.

**Comment by mprather** [comment]
Good to hear. Any chance there's a roadmap/plan posted?

**Comment by BrennanConroy** [comment]
Vcpkg port update is in PR.

> Any chance there's a roadmap/plan posted?

We aren't ready to commit to a roadmap or plan at this time.

**Comment by BrennanConroy** [comment]
Port updated
