### ISSUE TITLE
Apply layout from `_Imports.razor` to a folder and its subfolders is not working

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#35068]
[ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-5.0#apply-a-layout-to-a-folder-of-components) documentation said that:

>Every folder of an app can optionally contain a template file named _Imports.razor. The compiler includes the directives specified in the imports file in all of the Razor templates in the same folder and recursively in all of its subfolders. Therefore, an _Imports.razor file containing `@layout DoctorWhoLayout` ensures that all of the components in a folder use the `DoctorWhoLayout` component. There's no need to repeatedly add `@layout DoctorWhoLayout` to all of the Razor components (.razor) within the folder and subfolders.

But is not working for the following admin folder and its subfolder. If I move the `_Imports.razor` file inside `Admin/Pages` folder then it works for the Components inside `Admin/Pages` folder.

![Untitled](https://user-images.githubusercontent.com/14342773/128376722-6d687263-a499-46f4-a9a8-307171fffaea.jpg)

Even not working for the following folder structure:

![tempsnip](https://user-images.githubusercontent.com/14342773/128378211-c4344ad9-42ff-4764-95be-65eebd11a23c.png)

If I go to the route of the components inside `Admin` folder and its subfolder, the application freezes, and no error is thrown in the console.

**Comment by pranavkm** [comment]
> If I go to the route of the components inside Admin folder and its subfolder, the application freezes

The `_Imports` also applies to Layout, so you have a recursion issue here - the Layout adds itself as it's Layout.

**Comment by TanvirArjel** [comment]
@pranavkm Documentation also clearly said that:

> The @layout Razor directive only applies a layout to routable Razor components with an @page directive.

But there is no `@page` directive in the `AdminLayoutComponent` then why AdminLayoutComponent also be applied to itself?

**Comment by pranavkm** [comment]
Layouts apply to all components, not just routeable ones.

**Comment by TanvirArjel** [comment]
@pranavkm Then what about the documentation?

**Comment by pranavkm** [comment]
Doesn't the documentation state this:

> s. Therefore, an _Imports.razor file containing @layout DoctorWhoLayout ensures that all of the components in a folder use the DoctorWhoLayout component

If the `_Imports.razor` applies to the `DoctorWhoLayout` (which appears to be what's happening in your case), you essentially end up with a recursion.

**Comment by TanvirArjel** [comment]
However, if applying layout from `_Imports.razor` to a folder and its subfolders does not work for the above two folder structures then the design is surely flawed. You can't expect to keep the `AdminLayoutComponent` out of the `Admin` folder. 

Thank you for your responses.

**Comment by TanvirArjel** [comment]
@pranavkm You said that:

> Layouts apply to all components, not just routable ones.

I have checked that Layout from `_Imports.razor` file is only applying to the routable components, not all components, This is fine because this is the expected behavior.

**So the only issue is the LayoutComponent self-reference. This is surely an issue and this is quite easily addressable.  A LayoutComponent should not reference itself irrespective of the position of the LayoutComponent in the folder and subfolders.**

Please accept. this as an issue.
