### ISSUE TITLE
Add ability to add page content-based metatags on Blazor WebAssembly

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#35066]
### Is your feature request related to a problem? Please describe.
I am trying to add dynamically generated metatags in a Blazor WebAssembly application, specifically, those in the Open Graph protocol for social networks sharing.
I can generate them, however, they keep been unrecognized by online checkers or "sharers".

### Describe the solution you'd like
Using metatags is a vital step on great systems, currently, to the best of my knowledge, with Blazor WebAssembly,
you are only able to have static metatags manually set on the index.html, or if using the Blazor WebAssembly approach with a _Host. file, semi-dynamic generated.

We would like to have the posibility to add metatags as those in the Open Graph protocol, 
where the "og:image" for example will be generated from data in the component, like a thumbnail url.

**Comment by pranavkm** [comment]
We added support for Head and PageTitle as part of 6.0-preview7 that should be released soon. Look out for the ASP.NET Core blog post which will describe this feature in more detail.

**Comment by efonsecab** [comment]
> We added support for Head and PageTitle as part of 6.0-preview7 that should be released soon. Look out for the ASP.NET Core blog post which will describe this feature in more detail.

Nice, did not know that. Thanks a lot.
