### ISSUE TITLE
Set required parameter attribute in OpenAPI metadata

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#35081]
By default, OpenAPI assumes that all parameters are optional parameters.

https://swagger.io/docs/specification/describing-parameters/

We don't currently propagate any information that says `required: true` for parameters that are required in an endpoint

This builds on top of the work done in #32375

**Comment by davidfowl** [comment]
Turns out this requires changes in 2 places:
- We need to set the IsRequired flag on API explorer metadata
- We need to make sure consumers use this flag. Today Swashbuckle ignores this flag and determines "requiredness" using custom logic.
