### ISSUE TITLE
Add logging scope for session

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#35096]
### Is your feature request related to a problem? Please describe.
I would like to filter different requests based on the session id.

### Describe the solution you'd like
Create a logging scope in session middleware with the session id.

### Additional context
Here's the alternative that could be done.
```csharp
app.UseSession();
app.Use(async (context, next) =>
{
    var logger = context.RequestServices.GetService<ILogger<SessionMiddleware>>();
    var sessionFeature = context.Features.Get<ISessionFeature>();
    using var scope = logger.BeginScope(new SessionLogScope(sessionFeature.Session.Id))
    await next();    
});
```

_closed before here https://github.com/dotnet/aspnetcore/issues/2400_

**Comment by davidfowl** [comment]
This is a good thing to add.

**Comment by adityamandaleeka** [comment]
Closing this per discussion in https://github.com/dotnet/aspnetcore/pull/35104

The workaround for this is to use the log for SessionLoaded to correlate events (see https://github.com/dotnet/aspnetcore/blob/83927d9c988b88a8d1c29c324a4a62231a7f8c05/src/Middleware/Session/src/DistributedSession.cs#L394)
