### ISSUE TITLE
Provide a sample for generating JavaScript components that wrap Razor components

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#35112]
With the recent work around #32967, it could be valuable to developers if we provided a sample that auto-generates components for JavaScript SPA frameworks (e.g. Angular) from existing Razor components.

This sample could integrate into the existing build process - all it would take is editing the Razor component and rebuilding, and the corresponding Angular component would be automatically updated.

Developers could then take the sample and tweak it to their own needs, integrating it with whichever JavaScript framework they're using.

**Comment by mymatrixpixel** [comment]
Thank you @MackinnonBuck . I'm looking for the sample. it'll be very useful(integrating Angular app/lib with blazor components).

**Comment by MackinnonBuck** [comment]
Done in https://github.com/aspnet/samples/pull/76
