### ISSUE TITLE
Empty web project generates static assets

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35143]
### Describe the bug
A web project with no static assets static assets files in the output. We shouldn't be generating extra files if there's nothing in the source:

### To Reproduce

- Make a new project using the .NET 6.0 rc1 builds
- Look at the bin folder
- Observe both WebApplication519.StaticWebAssets.xml, WebApplication519.staticwebassets.runtime.json, WebApplication519.staticwebassets.json files.

![image](https://user-images.githubusercontent.com/95136/128588858-ca6be97f-ff57-4109-9f48-b86deb109b74.png)

```JSON
{
  "ContentRoots": [],
  "Root": {
    "Children": null,
    "Asset": null,
    "Patterns": null
  }
}
```

```XML
<StaticWebAssets Version="1.0" />
```

### Further technical details
- Microsoft.AspNetCore.App 6.0.0-rc.1.21406.15

**Comment by javiercn** [comment]
@davidfowl Not sure what's going on there, I would have swore that we had a test for that. 

I'll double check since we are doing cleanup now
