### ISSUE TITLE
Ability to set the rendering order of elements in the BuildRenderTree method

### ISSUE THREAD

**Issue by BananaRush** [dotnet/aspnetcore#35157]
### The problem
Hi I have a dynamic set of items and I render them in the BuildRenderTree method keeping an index for each item. In this implementation, adding and removing elements works well because the elements are displayed in ascending order of the element's index. I want to add the display order of the items and keeping the index, when I do the sorting of the items by the zIndex property, the tree rebuilding problems occur. I would like to have a function of lazy matching of the element tree. Since, in fact, the indices of the elements have not changed, but each time the OnAfterRender function is called in the components with the flag "firstRender = true"

```c#
private readonly HashSet<ElementNode> _elements;
private readonly Dictionary<Guid, int> _elementsSequence;
private int _lastSequence = 0;

public RenderNode()
{
	_elements = new HashSet<ElementNode>();
	_elementsSequence = new Dictionary<Guid, int>();
}

public static void RandomIndex(IEnumerable<ElementNode> arr)
{
	var rand = new Random();
	foreach(var item in arr)
		item.ZIndex = rand.Next(1, 5000);
}

protected override void BuildRenderTree(RenderTreeBuilder builder)
{
	RandomIndex(_elements);
	// foreach (var elm in _elements.OrderBy(r => r.ZIndex)) // Problem
	foreach (var elm in _elements)
	{
		int sequence = 0;
		if (_elementsSequence.ContainsKey(elm.Id))
		{
			sequence = _elementsSequence[elm.Id] - elm.Parameters.Count;
		}
		else
		{
			if (_elementsSequence.Any())
			{
				var key = _elementsSequence.OrderByDescending(r => r.Value).FirstOrDefault();
				sequence = key.Value;
				if (sequence > _lastSequence)
					_lastSequence = sequence;
				else
					sequence = _lastSequence;
			}
			_elementsSequence.Add(elm.Id, sequence + elm.Parameters.Count);
		}

		builder.OpenComponent(sequence, elm.GetComponentNodeType());
		foreach (var parm in elm.Parameters)
			builder.AddAttribute(++sequence, parm.Key, parm.Value);

		builder.CloseComponent();
	}
}


internal bool Add(ElementNode elementNode)
{
	if (_elements.Add(elementNode) == false)
		return false;
	StateHasChanged();
	return true;
}

internal bool Remove(ElementNode elementNode)
{
	if(_elements.Remove(elementNode) == false);
	   return false;
	StateHasChanged();
	return true;
}
```

### Describe the solution you'd like
Ability to set the rendering order of tree elements with maintaining the element index, without re-creating the element.

### Additional context

Target Frameworknet NET 5.0

**Comment by javiercn** [comment]
@BananaRush thanks for contacting us.

You might be looking to use the `@key` directive.

We don't recommend using a sequence variable to generate the indexes for the render tree frame.

We would recommend that you look at `DynamicComponent` and follow the same set of patterns the generated blazor code uses (with literal indexes and so on). 

While using an incrementing index might work, it is likely that it is degrading the performance of the diff algorithm (for reasons beyond the scope of this issue to explain).

Our recommendation is that you produce the render output you desire using razor syntax and closely match that in your code if you are not able to do so directly within razor syntax.
