### ISSUE TITLE
Blazor InputFile RequestImageFileAsync not revoking ObjectURL

### ISSUE THREAD

**Issue by MichelJansson** [dotnet/aspnetcore#35156]
### Describe the bug
When invoking `IBrowserFile.RequestImageFileAsync`, a file/blob object URL is created for the resize operation: https://github.com/dotnet/aspnetcore/blob/1795d691005181241617007399abd3c8d10ef32a/src/Components/Web.JS/src/InputFile.ts#L62

But this objectURL is never revoked (with `URL.revokeObjectURL()`) after the resize has completed, leading to the objectURL and consequently the blob (original image file reference in this case) not being released from memory until the tab is reloaded or closed.

[createObjectURL Usage Notes (Mozilla)](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#usage_notes)

### To Reproduce
1. Run the sample to resize images.
``` razor
<InputFile OnChange="OnInputFileChange" multiple/>

<div class="image-list">
    @foreach (var imageDataUrl in imageDataUrls)
    {
        <img src="@imageDataUrl" />
    }
</div>

@code {
    IList<string> imageDataUrls = new List<string>();

    async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        var imageFiles = e.GetMultipleFiles().Where(file => file.ContentType.StartsWith("image/"));

        var format = "image/png";
        foreach (var imageFile in imageFiles)
        {
            var resizedImageFile = await imageFile.RequestImageFileAsync(format, 100, 100);
            var buffer = new byte[resizedImageFile.Size];
            await resizedImageFile.OpenReadStream().ReadAsync(buffer);
            var imageDataUrl = $"data:{format};base64,{Convert.ToBase64String(buffer)}";
            imageDataUrls.Add(imageDataUrl);
        }
    }
}
```

2. Inspect the page, and find the ever growing list of blob URLs in the sources tab.

### Further technical details
- ASP.NET 5.0

**Comment by MichelJansson** [comment]
I'm willing to submit a PR for this issue as my first-time contribution, as it's a 1 line fix.

**Comment by TanayParikh** [comment]
> I'm willing to submit a PR for this issue as my first-time contribution, as it's a 1 line fix.

Thanks @MichelJansson!
