### ISSUE TITLE
[Blazor] `[Authorize]` attribute not checking authentication state before component initialization.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#35169]
I have the following menu:

![image](https://user-images.githubusercontent.com/14342773/128662512-b141afe2-9d4c-4f4a-bf66-86e590a3658e.png)

The three components are as follows:

HomeComponent:
```C#
@page "/"
<div>Home</div>
```

StoreComponent:
```C#
@page "/store"
@attribute [Authorize]
<div>Store</div>
```

ProductComponent:
```C#
@page "/products"
@attribute [Authorize]
<div>Products</div>
```

Store and Products menus are only visible when the user is authenticated. After 60 seconds JWT is being expired hence the user has been unauthenticated but if I click on `Store` and `Products` menus still showing the content of those pages **instead of redirecting to login page** as `@attribute [Authorize]` is not checking the latest AuthenticationState during the component initialization. This seems weird that during the initialization of the component with the `[Authorize]` attribute not checking the latest AuthenticationState and not doing the redirection based on the latest AuthenticationState result.

`@attribute [Authorize]` do check the latest AutheticationState only if the page is reloaded from the URL.

**Is there any way to force `@attribute [Authorize]` will check AuthenticationState by calling `GetAuthenticationStateAsync` of the `AuthenticationStateProvider` and do the navigation based on the AuthenticationState result?**

Here is my `AuthenticationStateProvider`:
```C#
public class HostAuthStateProvider : AuthenticationStateProvider
{
    private readonly ILocalStorageService _localStorage;
    private readonly NavigationManager _navigationManager;
    private readonly ExceptionLogger _exceptionLogger;
    private readonly JwtTokenParser _jwtTokenParser;

    public HostAuthStateProvider(
        ILocalStorageService localStorage,
        ExceptionLogger exceptionLogger,
        NavigationManager navigationManager,
        JwtTokenParser jwtTokenParser)
    {
        _localStorage = localStorage;
        _exceptionLogger = exceptionLogger;
        _navigationManager = navigationManager;
        _jwtTokenParser = jwtTokenParser;
    }

    public ClaimsPrincipal User { get; private set; }

    public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        try
        {
            string jwt = await _localStorage.GetItemAsync<string>("UserJwtKey");

            if (string.IsNullOrWhiteSpace(jwt))
            {
                User = new ClaimsPrincipal(new ClaimsIdentity());
                return new AuthenticationState(User);
            }

            User = _jwtTokenParser.Parse(jwt);
            return new AuthenticationState(User);
        }
        catch (Exception exception)
        {
            await _exceptionLogger.LogAsync(exception);
            User = new ClaimsPrincipal(new ClaimsIdentity());
            return new AuthenticationState(User);
        }
    }

    public async Task LoginAsync(string jsonWebToken, string redirectTo = null)
    {
        if (string.IsNullOrWhiteSpace(jsonWebToken))
        {
            throw new ArgumentNullException(nameof(jsonWebToken));
        }

        await _localStorage.SetItemAsync("UserJwtKey", jsonWebToken);

        NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());

        if (redirectTo != null)
        {
            _navigationManager.NavigateTo(redirectTo);
        }
    }

    public async Task LogOutAsync(string redirectTo = null)
    {
        await _localStorage.RemoveItemAsync("UserJwtKey");
        NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());

        if (redirectTo != null)
        {
            _navigationManager.NavigateTo(redirectTo);
        }
    }
}
```

Here is my `App.razor` file:

```C#
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayoutComponent)">
                <NotAuthorized>
                    <RedirectToLoginComponent/>
                </NotAuthorized>
                <Authorizing>
                    <h1>Authentication in progress</h1>
                    <p>Only visible while authentication is in progress.</p>
                </Authorizing>
            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayoutComponent)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

Expected Behaviour: `@attribute [Authorize]` should check the lastest AutheticationState on every route change and do navigation based on the lastest AuthenticationState result. **This is the behavior of the Angular Authentication Guard.**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like your authentication state provide is missing a notification for when the authentication state changes. You will have to call the `NotifyAuthenticationStateChanged` as soon as the token is expired.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT I am very much aware of what you said. It seems you did not read my issue thoroughly to understand what I mean and what I am expecting.

However, I have the following queries:

1. How and where from shall I know that token has been expired in real-time to trigger the Authentication State Changed? Is it not the responsibility of the `[Authorize]` attribute to determine the latest authentication state?

2. What about the Authentication Guard Concept in Blazor?
