### ISSUE TITLE
Visual Studio for mac - bootstrap classes not showing

### ISSUE THREAD

**Issue by Kremed** [dotnet/aspnetcore#35160]
I'm trying to develop a web application using Visual Studio on Mac, but I can't get the bootstrap class list when I type the first letters of the class, as for displaying interfaces, the classes are working normally, which means that the library already exists
All updates are already there Follow the latest versions in Visual Studio

**Comment by javiercn** [comment]
@Kremed thanks for contacting us.

This is not something that our team controls. In order for you to get a better and faster answer we suggest you file the issue directly through the report a problem feature in Visual Studio for Mac. You can see instructions for that [here](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019)
