### ISSUE TITLE
Blazor WebAssembly MSAL authentication error

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspnetcore#35162]
### Describe the bug

I have a [Blazor WebAssembly application](https://github.com/IEvangelist/learning-blazor) that relies on:

`<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="6.0.0-preview.6.21355.2" />`

For authentication, with an AAD B2C instance. It works perfectly, when running locally. But now that the app is deployed to Azure as a static web app, I get the following error:

> "There was an error trying to log you in: 'Cannot read property 'toLowerCase' of undefined'"

The website is [deployed here](https://purple-stone-0b2589410.azurestaticapps.net).

### To Reproduce

Deploy a Blazor WebAssembly app (with PWA bits) to Azure static web apps, with AAD B2C auth. Try logging in.

### Exceptions (if any)

None

### Further technical details

Using .NET Core SDK Version: 6.0.100-preview.6.21355.2

**Comment by javiercn** [comment]
@IEvangelist thanks for filing the issue.

Can you include the callstack?

**Comment by IEvangelist** [comment]
Hi @javiercn - there is no call stack. The error is trapped and a message passed to the `RenderFragment`. See [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L388-L398). On the client side, in the browser there are no errors logged - which is rather unfortunate.

**Comment by campersau** [comment]
I was able to get a stack trace, the error is in https://purple-stone-0b2589410.azurestaticapps.net/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js

See:
![image](https://user-images.githubusercontent.com/4009570/128714167-05ced237-7f40-4dab-b505-6628a29872ca.png)

**Comment by IEvangelist** [comment]
After a bit more digging, and thanks to @campersau - I have been able to determine that the `this._settings.loginMode` is in fact `undefined`. I had a break point on the in the `AuthenitcationService.init` which is called from here:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L230

Through the JS interop. I have this value set though in my app, [here](https://github.com/IEvangelist/learning-blazor/blob/ab34d1b1a8e66d3cfa87da082e6b4012fec66a8a/src/Web/Extensions/WebAssemblyHostBuilderExtensions.cs#L47). Is it possible that the config is somehow getting stomped out, if so where would one look for that?

**Comment by IEvangelist** [comment]
I'm thinking that somehow the `.ProviderOptions` are not passing the `.LoginMode`. The correct scopes are coming through, but not the login mode.

**Comment by aherrick** [comment]
Related https://github.com/dotnet/aspnetcore/issues/33312

**Comment by SireMartin** [comment]
the workaround in #33312 also worked for my slightly different error
![afbeelding](https://user-images.githubusercontent.com/5307283/134349118-c2e40f3d-2771-45bc-bac7-29026b47387d.png)
