### ISSUE TITLE
Add metadata for IFormFile usage with minimal actions

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#35175]
## Background and Motivation

As suggested in https://github.com/dotnet/aspnetcore/issues/34303#issuecomment-894149429, to support binding parameters of type `IFormFile` with minimal actions, some metadata to allow the form field name for the file would be needed to support names that can't be expressed with C# syntax within the parameter name.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http.Metadata
{
+    public interface IFromFileMetadata
+    {
+        string? Name { get; }
+    }
}

namespace Microsoft.AspNetCore.Mvc
{
+    [AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
+    public class FromFileAttribute : Attribute, IBindingSourceMetadata, IModelNameProvider, IFromFileMetadata
+    {
+        public FromFileAttribute();
+        public FromFileAttribute(string name);
+
+        public BindingSource BindingSource => BindingSource.FormFile;
+        public string? Name { get; set; }
+    }
}
```

## Usage Examples

```csharp
app.MapPost("/upload", async ([FromFile("file-name")] IFormFile file) =>
{
    using var stream = System.IO.File.OpenWrite("upload.txt");
    await file.CopyToAsync(stream);
});
```

## Alternative Designs

A more explicit name, but having _from_ and _form_ next to each other looks a bit yuck.

```diff
namespace Microsoft.AspNetCore.Http.Metadata
{
+   public interface IFromFormFileMetadata
+   {
+       string? Name { get; }
+   }
}
```

Putting `FromFileAttribute` in a different namespace so it's not coupled to MVC.

```diff
namespace Microsoft.AspNetCore.Http.Metadata
{
+    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
+    public class FromFileAttribute : Attribute, IFromFileMetadata
+    {
+        public FromFileAttribute();
+        public FromFileAttribute(string name);
+
+        public string? Name { get; set; }
+    }
}
```

## Risks

The other `[From...]` attributes live in the `Microsoft.AspNetCore.Mvc` namespace so adding another in the same place would make sense, but adding the concrete implementation for `[FromFile(...)]` to MVC wouldn't be right without also implementing it within model binding there too as a new feature to supplement the existing `IFormFile` support. Otherwise users of controllers might try and use it and it then not work as expected.

**Comment by pranavkm** [comment]
API review: We think we might be able to get away re-using the existing `FromFormAttribute` and specialize the swagger based on if it's a `IFormFile` / `IFormFileCollection` instance.

```diff
+ public interface IFromFormMetadata
+ {
+     string? Name { get; }
+ }

- public class FromFormAttribute : Attribute, IBindingSourceMetadata, IModelNameProvider
+ public class FromFormAttribute : Attribute, BindingSourceMetadata, IModelNameProvider, IFromFormMetadata
```

Usage:

```C#
app.MapPost("/upload", async ([FromForm("file-name")] IFormFile file) => { ... });

app.MapPost("/upload", async ([FromForm] IFormFileCollection file) => { ... }); 

app.MapPost("/upload", async (IFormFile myFile) => { ... });

app.MapPost("/upload", async (IFormFileCollection myFiles) => { ... });

// Unsupported. Analyzer error. This can be done in a follow up
app.MapPost("/upload", async ([FromForm("myFiles")] IFormFileCollection file) => { ... }); 
```

For `IFormFileCollection`, we do not wanted based on the parameter name or `IFromFormAttribute.Name` (at least to start with). We can make the latter an error via an analyzer + a runtime check.

**Comment by rafikiassumani-msft** [comment]
Closing this issue as it was fixed in the following PR: https://github.com/dotnet/aspnetcore/pull/35158. The feature will be released in .NET7 preview-1
