### ISSUE TITLE
Nuget package outdated (?)

### ISSUE THREAD

**Issue by MeikelLP** [dotnet/aspnetcore#35176]
### Describe the bug
This is more of a confusion than a classic bug report. I try to reference `IRouteValuesFeature` (example) and as stated in [the docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.iroutevaluesfeature?view=aspnetcore-5.0) it should exist in the `Microsoft.AspNetCore.Http.Abstractions.dll`.

 As a developer I expect nuget.org to provide a package like this and nuget.org does: https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics/
Sadly this package is outdated. I assume it's from ASP.NET Core 2.2

I need the version 5+ package. It's bundled in the https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/ but I am creating a library and not an asp app. What dependency do I need in a libary project to get the latest `Microsoft.AspNetCore.Diagnostics` ?

### To Reproduce
* Add this package reference to your project
```xml
<PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.2.0" />
```
* use `IRouteValuesFeature` anywhere
* try to compile

### Further technical details
- ASP.NET Core version 5

**Comment by martincostello** [comment]
Since .NET Core 3.0 the packages are part of the shared framework that come with the SDK. You need to use `<FrameworkReference Include="Microsoft.AspNetCore.App" />` instead ([docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#use-the-aspnet-core-shared-framework)).

**Comment by MeikelLP** [comment]
Isn't that a lot for a small library?

**Comment by martincostello** [comment]
I guess that's a different topic/discussion, but it's the only way to reference it in 3.0+, which is why the packages aren't in NuGet.org.

**Comment by javiercn** [comment]
@MeikelLP thanks for contacting us.

@martincostello is correct, we moved away from individual packages in favor of framework references since 3.0, so his answer applies here.
