### ISSUE TITLE
Blazor InputFile - Access IBrowserFile Stream after file list has changed

### ISSUE THREAD

**Issue by MichelJansson** [dotnet/aspnetcore#35178]
### Is your feature request related to a problem? Please describe.
I am trying to store a stack of IBrowserFiles (images) using one InputFile component (so the user can add one file after the other), where a preview is generated immediately `onchange`, and later when the user clicks submit/save we upload the entire stack to the server.
BUT there seem to be no way to access the IBrowserFile stream (`OpenReadStream()` throws) after the file list of the InputFile it originated from has changed.

This _could_ be solved by also reading all the files into memory `onchange`, but would be very wasteful as I'm expecting up to 200 files.

### Describe the solution you'd like
As long as I have a reference to the IBrowserFile in .NET I would like to be able to get it's stream just as I can in JS when keeping a reference to a File.

The changes implemented by @TanayParikh in #33986, looks like it MAY have opened up for an alternative solution to hold a reference to the stream by calling [`IBrowserFile.OpenReadStream`](https://github.com/dotnet/aspnetcore/blob/9b6afb49f6981de4e242e4781a88caf3804e83e9/src/Components/Web/src/Forms/InputFile/BrowserFile.cs#L40) (which returns a [`BrowserFileStream`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs), which opens a stream via [`IJSStreamReference`](https://github.com/dotnet/aspnetcore/blob/9b6afb49f6981de4e242e4781a88caf3804e83e9/src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs#L97)) before the file list changes. But I have no way of verifying this as that code has yet to be released, and I have a little hard time following all the interop stream code.

### Additional context
This issue stems from that the original JS objects is stored in a list on the input element, which is cleared each time the file list is changed, and after that the blob I am hoping to stream is gone.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us. This will require custom logic to load the file into memory as soon as it's selected. We don't plan to bake this functionality into the framework at this time.
