### ISSUE TITLE
CascadingParameter is too lazily refreshed

### ISSUE THREAD

**Issue by astrowalker** [dotnet/aspnetcore#35170]
In a way this is follow-up of the report: https://github.com/dotnet/aspnetcore/issues/5675 What OP didn't realized (I guess) the CascadingParameter is indeed refreshed as it should be, but in lazy manner -- and it shouldn't be.

My code looks like this:

Main page:
```html
<CascadingValue Value="commands">
    <States @ref="states"></States>
</CascadingValue>

<Commands @ref="commands"></Commands>

@code
{
    private Commands commands;
    private States states;
    ...

```

States components:

```html
@code {
    [CascadingParameter]
    public Commands Commands { get; set; }
}
```

So in short I have two custom components, and one of them (States) depends of the other (Commands). With such code States gets null value for Commands which is not good.

But! If I add on the main page some usage of Commands, like `Console.WriteLine(commands==null);` it is like Blazor realizes the "commands" reference was changed (because Blazor created instance of it) and propagates this fact down to "States".

What I am saying the workflow works as expected and the logic is there, the missing piece is eager approach instead of lazy one -- "the value changed? don't wait, refresh dependent components cascading values".

After all it is just dependency graph, I see no point in forcing user for each page with component-component dependency to manually resolve the refreshing order.

*Tested on ASP.Net 5.0.*

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're observing is expected. As mentioned in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0):

> A component reference is only populated after the component is rendered

So you'll have to re-render the second time to get the value set.
On a side note, we don't recommend passing references to components for these situations. Instead, we encourage passing domain objects around.

**Comment by astrowalker** [comment]
Hmm, I don't see a contradiction here. True, component reference is populated after component is rendered (so far so good) but my point is once it is set (or more actually changed) such change should trigger CascadingParameter for a refresh.

In other words I am not saying a reference acts strangely, I am saying CascadingParameter is not triggered properly by reference change.
