### ISSUE TITLE
Document the razor/cshtml compiler

### ISSUE THREAD

**Issue by oakad** [dotnet/aspnetcore#35180]
MSBuild is a decent build system, but many projects these days are multi-language in nature and may require custom code generation steps. In the modern day of microservices and shared IDL schemes there's a major synergy in compiling multiple system components together and using the same build system (which, in most cases, is not MSBuild, due to its Windows-only history).

It is possible to use the verbose debugging features of MSBuild to recreate the command line arguments needed to invoke the `rzc` compiler and process the cshtml and razor files, but this is tedious and not future-proof.

It would be so much better, if `rzc` was properly documented and some guarantees defined on its invocation interface. From the look of it, there's not much to it: only a handful of subcommands with rather well defined inputs and outputs.

Can we have it documented, please?

**Comment by javiercn** [comment]
@oakad thanks for contacting us.

> It would be so much better, if `rzc` was properly documented and some guarantees defined on its invocation interface. From the look of it, there's not much to it: only a handful of subcommands with rather well defined inputs and outputs.

We don't consider the interface for the razor compiler public API and it is susceptible to change at any moment, so we don't have plans to document it, since we don't plan to offer any guarantees about its stability. We don't recommend you take a dependency on it.

**Comment by oakad** [comment]
Your answer indicates, that to build anything ASP related MSBuild is a must. But is this really such a good idea? Why pin a whole bunch of really advanced tech on a rather limited build system?

**Comment by javiercn** [comment]
@oakad because it is the system that all our customers use and the ecosystem has built on.

> Why pin a whole bunch of really advanced tech on a rather limited build system?

We don't pin anything, we consider it an implementation detail because we don't think there is enough demand for us to support this as part of the public interface of the system and doing so greatly limits our ability to implement improvements and new features since in many cases they require breaking changes.

**Comment by oakad** [comment]
Of course it's a system everybody must use, there's no supported alternative. :-)

However, CMake is clearly an option right now for building dotnet apps, and Bazel Build is sort of ok (can be made to work quite well). But alas, those are dotnet apps without the Razor bliss.
