### ISSUE TITLE
blazor + PWA + static web app = cache not updatable

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#35184]
well, I've been struggling for a while trying to update my app versions and no solution has ever worked. and I never know who is to blame for these variables or if it's a mixture of everything.

until I found this one that worked:

```
  <Target Name="PublishServiceWorker" AfterTargets="CopyFilesToPublishDirectory">
    <WriteLinesToFile File="$(PublishDir)wwwroot\service-worker.js" Lines="/* $([System.Guid]::NewGuid()) */" />
  </Target>
```
I don't know why this change worked, because I've tried this strategy to update this file, but it never worked.

my questions are:
what does this do exactly and why only does this change take effect?
why is this code not part of the project template or the deploy process?

**Comment by javiercn** [comment]
@drma-dev thanks for contacting us.

You are forcing the service worker file to change on every build, which means your service worker always gets updated every time you deploy after the user has visited the page and refreshes the browser.

We already have code on the framework to automatically update the service worker when it needs to get updated. We compute a hash of all the assets in the service-worker-assets manifest and we compute another hash based on those hashes that we use to update the service-worker file in the same way you are doing there.

The difference is that you are forcing the service worker to update and re-download everything on every request.

**Comment by drma-dev** [comment]
is it a version yet to be released or do you refer to the current service work js? because it doesn't work properly.

on the desktop still works if the user closes the browser.
but that doesn't happen on the cell phone, the cache continues, even closing the browser. I can only get the new version by clearing the cache (something the user will never do)

**Comment by javiercn** [comment]
@drma-dev by default the service worker updates in the background and you ever only see a new version the next time the user visits the page, that's how service workers work.

You can setup an event on the service worker to notify the user when a new version is available and installed to refresh the page.

**Comment by drma-dev** [comment]
that's what I'm talking about. on my cell phone, if I close the browser and access the site again, it will get the old version. the only way to get the new version is to clear the browser cache.

**Comment by javiercn** [comment]
@drma-dev does it happen on your phone only or also on your desktop?

What phone/browser are you using?

**Comment by drma-dev** [comment]
on the desktop it works normal if you close the browser.

I use chrome on android. in fact, I've tested it on several of my friends' cell phones and the behavior is the same.

**Comment by javiercn** [comment]
@drma-dev thanks for the details.

It might be an android mobile specific issue, however all browsers always download the service worker file and check it byte by byte against the existing implementation to decide whether they need to update it or not.

We already stamp a version at the beginning of the file based on the contents (and if it works fine on desktop, it is unlikely we have a bug there (we also have through msbuild tests around it)).

If you want to be truly sure, you can donwload the service-worker file before you make an update and after you make an update and compare the two (byte by byte) to determine if they are different.

If you change a file listed in service-worker-assets.js (to the point where it produces a different hash), deploy and the new service-worker.js is not different, then its a bug in our logic.

**Comment by drma-dev** [comment]
I'm going to test again with this information and get back to you this week.

**Comment by drma-dev** [comment]
ok, I found out which circumstance works: you have to close the tab and the browser (it has to be both) in order to get the new version. but this only works when you open it through the browser, not through the pwa app you installed (apparently there is a dependency on the browser. If I do this process in the browser, then pwa can identify the new version). so i ask: is there any downside if i use this setting in csproject to force the update, because surely there will be many users using the old version for a long time?

**Comment by javiercn** [comment]
@drma-dev you are forcing users to download and install a new version of the service-worker (and their contents) every time you deploy your app independent of whether you have changed something or not that affects the installed bits.

In both cases it should work in the same way when a change on the app affects the service worker (meaning you end up with a service worker with different contents after you've deployed).
