### ISSUE TITLE
Significant Memory Usage, CPU/GC Time, and Potential Memory Leak with Opening/Closing Razor Documents

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#35199]
### Describe the bug

Razor analysis and project system for Visual Studio 2019 results in a considerable amount of memory usage to the point that suggests a bug.  This bug can be seen by opening and closing a number of .razor files in a larger product.  Each open and close of a razor document adds 25-50MB of retained objects, eventually leading to an IDE crash as a result of no remaining memory.

Additionally, even after closing a solution, the graph components continue to persist in memory, further suggesting a memory leak/retainer of some kind.

### To Reproduce

1. You can use [the project provided here](https://github.com/dotnet/aspnetcore/issues/32118#issuecomment-847577935).
2. Note the memory usage of the `devenv.exe` under test.
1. Open and close several `.razor` documents.  For best results, open 10 or more at a time.  Observe long CPU usage and GC wait time if using a diagnostic tool such as dotMemory or dotTrace.  10 or so documents take nearly 2 minutes on my Ryzen 3700x.
2. Close the documents opened in the previous step.  Observe again the long CPU/GC time.
3. Force a GC and observe memory usage of `devenv.exe` under test.  Each document opened should produce 25-50MB of extra memory than observed in the 2nd step.
2. Close the solution (not Visual Studio).  Note the persistence of Razor project/analysis components retained in memory.

As an example, this is what I see when capturing `devenv.exe` after closing the solution and forcing a GC:

![](https://i.imgur.com/oDxkzNv.png)

You can see the Razor components in red.

In addition to the potential memory leak, the other issue is the sheer amount of memory used by Razor Project and analysis during runtime.  Another interesting screenshot here:

![](https://i.imgur.com/IL69nK1.png)

It appears that the pain is being generated mostly by the `DataboundAttributeDescriptor`.  Subsequently, there appear to be many strings that are also created and retained by this (shown below), suggesting that some improvement could be made via `string.Intern` (or other -- spitballing here).

Finally, to demonstrate the scale of memory usage, another shot showing ReSharper components.  Razor Project/analysis components are measuring 3x the amount of R#, which seems suspect to me:

![](https://i.imgur.com/52STGxh.png)

Finally, if interested in a recorded example of this issue in action, you may find that here on Visual Studio Developer Community:
https://developercommunity.visualstudio.com/t/Constant-Memory-Pressure-from-Razor-Anal/1497080#T-N1498094-N1499494

### Exceptions (if any)
My IDE is crashing regularly these days, and it appears it's memory-related.

~~Note that this issue was first attempted to be addressed in #32118.~~ (EDIT: this appears to be a new, separate issue not involving keypresses but document open/closing)  

I appreciate any other suggestions towards addressing this issue, or if there is something on my side that I can do to help alleviate the pain.

Thank you for any assistance you can provide, as well as all your outstanding work over there. 🙏

### Further technical details
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `Microsoft Visual Studio Community 2019 Preview Version 16.11.0 Preview 4.0`

**Comment by javiercn** [comment]
@Mike-E-angelo thanks for contacting us and for the detailed report.

@NTaylorMullen can you take a look at this?

**Comment by Mike-E-angelo** [comment]
Awesome, thank you @javiercn, you read my mind. 😁

Greetings, @NTaylorMullen, we cross paths again!  I promise I am trying not to be a nuisance here, but simply clawing for a scenario where I am not fighting the IDE more than my code. 😅

I really do appreciate your patience here as I continually improve my ability to articulate the issue I am facing, as well as diagnosing it.

The one issue I am also seeing is that there is perpetual GC Time while Razor Analysis fires:

![](https://i.imgur.com/uPcxLpP.gif)

From dotTrace, that appears to be from the following:
![](https://i.imgur.com/VKuqQn0.png)

Now, if this was addressed in 2022, as discussed, that's awesome.  In fact, I did take a peek at 2022 and things seem so much better.  Unfortunately no extensions, however. 😭

Unfortunately and regretfully, it is still a looming problem in 2019.  It was one I was going to patiently wait out, but unfortunately, the more razor files added to the solution, the worse it seems to get and I am currently at a point where the most basic of key presses faces a half-second to several seconds delay time due to GC Time.  It just seems that a humongous amount of allocations are being generated during analysis, leading to a constant GC sweep.

Additionally, a single keypress in a razor file will lead to several minutes (!) of churning.

Anyways, I am starting to better understand the tooling to help diagnose and I will add more findings as I go along.

Thank you for any time and/or consideration you can lend to assist. 🙏

**Comment by Mike-E-angelo** [comment]
So another tidbit of information here.  

In my IDE:

1. I opened a razor document and waited for CPU to idle down (this is about ~45 seconds)
2. Closed the document and waited for idle CPU (another ~45 seconds)
3. Forced GC via dotMemory
3. Took a snapshot in dotMemory
3. Opened the same document from step 1 again, wait for idle CPU
4. Closed document and wait for idle CPU
5. Forced GC via dotMemory
6. Take a comparison snapshot with dotMemory

If I understand correctly, the result of the comparison is 47MB of newly retained objects in memory, suggesting a memory leak.

![](https://i.imgur.com/KJql8ae.png)

My concern is that there is a progressive memory leak here that ultimately results in the IDE crashing after a period of usage.  This has been my experience, at least.

**Comment by Mike-E-angelo** [comment]
I appreciate your patience with my chatter here.  This should be the last of it I SWEAR. 😅  I have been further exploring this throughout the day and I am wanting to make sure you have the most accurate information to work with as far as I understand it.

Please note the title and reproduction steps as I have updated them to better reflect the issue.  Note that the cause of memory usage can be tied to document opening and closing.  Each open/close of a razor document generates a considerable amount of GC Wait time and subsequent CPU usage (note that GC Time does interfere with keypresses in the text editor, which led me to initially believe it was keypress related).  It appears this issue is compounded by the number of documents opened.  For instance, opening 10 razor documents at a time will grind the CPU/wait time for nearly 2 minutes on my machine.

More of note, each open/close of a document appears to add 1-2MB of retained memory usage in Razor Project objects (specifically `ProjectState` and `DefaultTagHelperDescriptor`), even after forced GC.  This suggests a memory leak and is most likely the root cause of all my IDE crashes/struggles as of late.

**Comment by NTaylorMullen** [comment]
@Mike-E-angelo never apologize for filing issues this verbose. They're a rarity and we absolutely love the passion and energy you bring when filing them 😄. Thank you!

So as for the issue you're encountering 

> More of note, each open/close of a document appears to add 1-2MB of retained memory usage in Razor Project objects

Ya this is definitely an unfortunate bug in VS2019 that we addressed in VS2022. There's probably still a chance some other related memory leak is there but nothing is on our radar currently.

> Now, if this was addressed in 2022, as discussed, that's awesome. In fact, I did take a peek at 2022 and things seem so much better. Unfortunately no extensions, however. 😭

To be totalllly transparent the fixes for all of this will only be applicable in VS2022 and sadly wont make their way back to VS2019 😢. It's a huge bummer the extension ecosystem doesn't exist there yet which I can absolutely view as a blocker. That being said I'm curious, what extensions do you find yourself missing?


Oh and I don't have access to your project (at least not that I can remember, it's been a while), by chance does it happen to target net6.0?

**Comment by Mike-E-angelo** [comment]
Cool, yeah it's been a freaking crazy week here @NTaylorMullen.  Thank you for getting back to me on this.

Funny enough, I was able to dive into investigating VS2022 in earnest as yesterday [R# for VS2022 was announced](https://blog.jetbrains.com/dotnet/2021/08/11/support-for-visual-studio-2022-preview/).  It turns out I was able to get most of my other important extensions installed one way or another.  The only extensions that I am missing are Power Commands and a few from Productivity Power Tools.  I went and made a [feature request on DeveloperCommunity](https://developercommunity.visualstudio.com/t/Upgrade-Popular-MSFT-Extensions-to-VS202/1500844) to make sure those are accounted for at some point.  I'mma just have to grin and bear it until then, especially PowerCommand's collapse all projects (not to be confused with collapse all :)).

If you have some way of nudging DevLabs to start getting those extensions moved over, I would greatly appreciate it. 🙏

Otherwise, since these are all known issues and cannot be fixed in VS2019, and I have enough here to use VS2022, then I am going to close this.

BTW, VS2022 is SO MUCH NICER as promised.  I did [post a bit of a nit here](https://developercommunity.visualstudio.com/t/Intermittent-Delay-on-Tag-Autoclose-for/1500930) (no, I can't help myself 😁), but outside of that everything looks and feels so much better.  

Great work out there to you and the team. 👍

**Comment by NTaylorMullen** [comment]
Love that VS2022 is feeling good! As for your nit issue (definitely not a nit 😉) that's a known bit that wont make the cut for the final release of VS2022 but it's great to gauge interest in the feature. Hopefully not too much of a blocker!

**Comment by Mike-E-angelo** [comment]
Thank you for the added information @NTaylorMullen.  I appreciate you taking the time to let me know.

FWIW/FYI, it still does appear there is an inordinate amount of memory still being used by the Razor system in VS2022.  Closing the solution and performing a GC does nothing and the objects are retained in memory.  Nearly 2GB worth in my case:

![](https://i.imgur.com/1LSr91m.png)

You can see it's not just Razor but a whole lot of components in `Microsoft.CodeAnalysis`.

I have reported this here:
https://developercommunity.visualstudio.com/t/10gb-of-retained-memory-after-closing-solution-and/1503239

**Comment by NTaylorMullen** [comment]
Ahhh @pranavkm this looks like the Razor Source Generator's callstacks. This known?

@Mike-E-angelo thank you for your ongoing help in this area ❤️ !

**Comment by Mike-E-angelo** [comment]
My pain is your gain, @NTaylorMullen ... and yeah well eventually my gain, too. 😁

**Comment by Mike-E-angelo** [comment]
> Ahhh @pranavkm this looks like the Razor Source Generator's callstacks. This known?

FWIW @NTaylorMullen / @pranavkm I have opened #35380 to track, with a link to developercommunity that has the DMP file of the issue.
