### ISSUE TITLE
dotnet watch error -  'waiting for a file to change before restarting dotnet...'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35196]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/dotnet-watch-error----waiting-for-a-fil/1494705)._

---
[severity:Other]
I am using VS2022 Community Version 17.0.0 Preview 2.1

I have created a Blazer server app and added a razor component library. If I debug the project in the VS2022 IDE it builds and runs fine with no errors and the web page is displayed correctly.

If I open a terminal window on the main project, and the enter the command: dotnet watch
I get the subject error which keeps repeating the process over and over again.

! [dotnet-watch-error.png] (https://aka.ms/dc/image?name=Beabc28024f59407da9aa057c504271b8637636956707409783_dotnet-watch-error.png&tid=eabc28024f59407da9aa057c504271b8637636956707409783)

Note: I am trying to follow the example of doing this as shown in this Blazor video (re: 36:25):
https://www.youtube.com/watch?v=Q4D5NffKTIk&list=PLdo4fOcmZ0oV2fcY7wsQHx4RNWXEDKgm4&index=32

---
#### Feedback Bot on 8/4/2021, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@pranavkm FYI

**Comment by pranavkm** [comment]
Thanks for your issue report. This appears to be a VS's console which is being tracked by feedback items such as: https://developercommunity.visualstudio.com/t/running-a-net-6-preview-7-aspnet-core-app-in-the-v/1502210
