### ISSUE TITLE
Authorization header is ignored in WebSocket request

### ISSUE THREAD

**Issue by Marusyk** [dotnet/aspnetcore#35193]
### Describe the bug
The `Authorization` header is removed in WebSocket request.

### To Reproduce
I try to set `Authorization` header in .NET 5 console app for WebSocket connection:

```csharp
var client = new ClientWebSocket();
client.Options.SetRequestHeader("Authorization", "token");
client.Options.SetRequestHeader("CustomAuthorization", "custom-token");
await client.ConnectAsync(new Uri(_url, CancellationToken.None);
```

On the other side, there is ASP.NET WebAPI with the code in a middleware:

```csharp
public async Task Invoke(HttpContext context)
{
	if (!context.WebSockets.IsWebSocketRequest)
	{
		await context.Response.WriteAsync("Only WebSocket requests are allowed at this endpoint.");
		await context.Response.CompleteAsync();
		return;
	}

	Console.WriteLine($"Authorization = {context.Request.Headers["Authorization"]}");
	Console.WriteLine($"CustomAuthorization = {context.Request.Headers["CustomAuthorization"]}");	
	...
}
```
result:

> Authorization =
> CustomAuthorization = custom-token

Can anyone explain why the `Authorization` header was removed? Is it by design? If yes, then where I can find [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.setrequestheader?view=net-5.0) for that?
Are there other headers that will be removed? Please suggest

Perhaps the issue should be created in [dotnet/runtime](https://github.com/dotnet/runtime). Please correct me if I am wrong
### Further technical details
- ASP.NET Core 5.0.301

**Comment by BrennanConroy** [comment]
Please provide a minimal repro application as a GitHub repository.

**Comment by Marusyk** [comment]
@BrennanConroy that's all code I have, should I create a repo for this?

**Comment by adityamandaleeka** [comment]
Yes, please.

**Comment by Marusyk** [comment]
Done. Please see https://github.com/Marusyk/WebSocketDemo

**Comment by BrennanConroy** [comment]
Ok, so in your shared app you misspelled the header name `Console.WriteLine($"Authorization = {context.Request.Headers["Authorizationn"]}");`
And if you fix the spelling the output looks correct.

**Comment by Marusyk** [comment]
@BrennanConroy unfortunately no
It was a type. I've fixed it

**Comment by BrennanConroy** [comment]
Can you explain how you're running the app, is it hosted behind a proxy? Just running your app (after fixing the typo) shows the token, so there must be something specific to your environment.

**Comment by Marusyk** [comment]
I run it from VS 2019 on my Windows 10 machine in debug mode

**Comment by BrennanConroy** [comment]
Silly question, but did you make sure to rebuild after fixing the typo.

**Comment by Marusyk** [comment]
of course

**Comment by BrennanConroy** [comment]
Alright, could you capture a network trace that shows the websocket request, and also add code to write out every header:
```
foreach (var header in context.Request.Headers)
{
    Console.WriteLine($"{header.Key}: {header.Value}");
}
```

**Comment by Marusyk** [comment]
```
Connection: Upgrade
Upgrade: websocket
Host: localhost:5001
CustomAuthorization: custom-token
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: wpm9e+HpPUaQX8WgZ7EsAQ==
```

**Comment by BrennanConroy** [comment]
Oh, you're getting a redirect. If you either remove the https redirection middleware or change your client url to wss does it work?

**Comment by Marusyk** [comment]
yep, it works now 
```
Connection: Upgrade
Upgrade: websocket
Authorization: token
Host: localhost:5000
CustomAuthorization: custom-token
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: KMWZ1zWHi0W0sU5NJW01tw==
```
So it issue was in redirect. To fix that:
 - remove `app.UseHttpsRedirection();` from Startup.cs
 or
- use `wss://localhost:5001/heartbeats` instead of `ws://localhost:5000/heartbeats` in ConsoleClient
@BrennanConroy thank you very much for your time

**Comment by BrennanConroy** [comment]
Lets keep this open and see if that behavior makes sense

**Comment by BrennanConroy** [comment]
Ok, now I remember, for security reasons we don't preserve the authentication header on redirects. This is by design behavior.

https://github.com/dotnet/runtime/blob/3db6ec5ab895e57073dc657f1462f86d8e0d3d79/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs#L53-L54
