### ISSUE TITLE
Blazor Css Isolation Is Not Recognized in Maui-Blazor WinUI Application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35195]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Css-Isolation-Is-Not-Recognized-i/1495827)._

---
[severity:I'm unable to use this version]
I am using VS Community 2022 Preview.
I have updated my dev environment to all the latest versions, templates, ran maui-check, etc.

Steps To Reproduce:
1. Create new Maui-Blazor app in VS using the '.NET Maui Blazor App (Preview)' template.
2. In the main app/pages folder add a 'Counter.razor.css' file.
3. Check the WinUI pages folder - the *.css file is not added (see screen shot).

! [Css File Missing.png] (https://aka.ms/dc/image?name=Be5e6a9ba913042219d677dc788a58d69637637873362773675_Css_File_Missing.png&tid=e5e6a9ba913042219d677dc788a58d69637637873362773675)

---
#### Feedback Bot on 8/6/2021, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@Eilon can you please take a look at this? Thanks!

**Comment by Eilon** [comment]
Hi, this is a known issue and is fixed in the upcoming preview 7 update.
