### ISSUE TITLE
Creating a ASP.NET Core Web App with "dotnet" at the end of its name results in error 500.0 when debugging with IIS Express.

### ISSUE THREAD

**Issue by JayTennant** [dotnet/aspnetcore#35209]
### Describe the bug
After creating a file with "**dotnet**" at the end of its name, ie. "mayapp**dotnet**", then launching the debugger with IIS Express always results in:
`HTTP Error 500.0 - ANCM In-Process Handler Load Failure`

This does not happen if the project's name does not have "**dotnet**" at the end of its name.

### To Reproduce
1. Create a new project of type "ASP.NET Core Web App" ("Core Empty" works too, as I'm sure others), and end the name with "dotnet", ie. "testdotnet".
2. Try running the app in debug mode with IIS Express.
3. See the error in the browser.

### Further technical details
- ASP.NET Core 5
- VS 2019 16.10.0

**Comment by javiercn** [comment]
@JayTennant thanks for contacting us.

This is not something our team works on. In order for you to get a better and faster answer we suggest you report this through the report a problem dialog in visual studio. See details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
