### ISSUE TITLE
IdentityEntityFrameworkBuilderExtensions does not support IDbContextFactory

### ISSUE THREAD

**Issue by sommmen** [dotnet/aspnetcore#35215]
Hello,

I've moved away from calling `services.AddDbContext<MyDbContext>(opt)` and am now using `services.AddDbContextFactory<MyDbContext>(opt)`. This works fine, but an issue arises when the services are being resolved:

![image](https://user-images.githubusercontent.com/8641495/128832198-7938c6e9-8356-4055-ab38-283547877be4.png)

I think this issue comes from `IdentityEntityFrameworkBuilderExtensions`.
At some point i'm calling:

``` csharp
            services.AddIdentity<User, UserRole>()
                .AddEntityFrameworkStores<MyDbContext>()
                .AddDefaultTokenProviders();
```

`AddEntityFrameworkStores` needs the dbContext because its calling:
`services.TryAddScoped(typeof(IUserStore<>).MakeGenericType(userType), userStoreType);` where userStoreType takes a generic DbContext which will be injected at runtime. This causes my project to fail, because i do not have a DbContext in DI only a DbContextFactory.

I.e. IdentityEntityFrameworkBuilderExtensions should support building from IDbContextFactory<TContext>.

I'm using .net core 5. Hope to get some info on whether i'm just mistaken or this was overlooked.

**Comment by ajcvickers** [comment]
Mitigated by https://github.com/dotnet/efcore/pull/25440 if it gets merged.

**Comment by sommmen** [comment]
> Mitigated by [dotnet/efcore#25440](https://github.com/dotnet/efcore/pull/25440) if it gets merged.

My googling did not take me there unfortunately - thanks for the info!
