### ISSUE TITLE
Add SignalR WebSocket compression support

### ISSUE THREAD

**Issue by dorthl** [dotnet/aspnetcore#35212]
Hello I am not a native English speaker The following content is from machine translation. Sorry

I noticed that in 6.0-preview5 WebSocket has added compression support  #32600 (https://github.com/dotnet/aspnetcore/pull/32600)

But in SignalR, because WebSocketOptions did not add related options, I couldn’t use it.

What is the reason?

**Comment by davidfowl** [comment]
Other priorities. We'll look into it for .NET 7 though.

**Comment by dorthl** [comment]
Okay, thank you, but this one is really too late, right?
