### ISSUE TITLE
Database Distributed Cache

### ISSUE THREAD

**Issue by ddrdoubled** [dotnet/aspnetcore#35220]
### Is your feature request related to a problem? Please describe.
I am trying to write a Distributed Cache for a different database than SqlServer. While i looked at `SqlServerCache` i was thinking most of it could be moved into a `DatabaseCache` abstraction and injecting the `IDatabaseOperations` implementation for `SqlServer` depending whether it is Mono or not. I think it would also be cleaner than the current implementation.
What do you think?

### Describe the solution you'd like
Create `DatabaseCache` and let `SqlServerCache` inherit from `DatabaseCache` and move `IDatabaseOperations` from internal to public. Then anybody could implement a different database cache by implementing `IDatabaseOperations`
I have tried already and i can create a PR for this, if you like.

### Additional context
`public SqlServerCache(IOptions<SqlServerCacheOptions> options)`
vs.
`public SqlServerCache(IDatabaseOperations databaseOperations, IOptions<SqlServerCacheOptions> options)`

**Comment by Tratcher** [comment]
Can you share a full list of the proposed apis here?

**Comment by ddrdoubled** [comment]
Hi, do you like to have the PublicApi.Unshipped.txt ? Or how do you like to have it?

**Comment by Tratcher** [comment]
Something like:
```
public class SqlServerCache : IDistributedCache
{
   public SqlServerCache(IOptions<SqlServerCacheOptions> options);
   public byte[] Get(string key);
   ...
}
```

**Comment by ddrdoubled** [comment]
ok, so first thing, the `SqlServerCache` would look like this:
```
/// <summary>
    /// Distributed cache implementation using Microsoft SQL Server database.
    /// </summary>
    public class SqlServerCache : DatabaseCache
    {
        /// <summary>
        /// Initializes a new instance of <see cref="SqlServerCache"/>.
        /// </summary>
        /// <param name="databaseOperations">The database operations for SQL Server</param>
        /// <param name="options">The configuration options.</param>
        public SqlServerCache(IDatabaseCacheOperations databaseOperations, IOptions<SqlServerCacheOptions> options) : base(databaseOperations, options)
        {

        }
    }
```
then the `DatabaseCache` would implement the `IDistributedCache` interface. Maybe `DatabaseCache` should be abstract.
```
namespace Microsoft.Extensions.Caching.Database
{
    /// <summary>
    /// Distributed cache implementation using a database.
    /// </summary>
    public class DatabaseCache : IDistributedCache
    {
...
```
and the `IDatabaseCacheOperations` interface is the same as previously internal `IDatabaseOperations` interface:
```
/// <summary>
    /// Interface for operations in the <see cref="DatabaseCache"/>.
    /// </summary>
    public interface IDatabaseCacheOperations
    {
        /// <summary>
        /// Retrieve the Cache Item from the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        byte[] GetCacheItem(string key);

        /// <summary>
        /// Retrieve the Cache Item async from the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        /// <param name="token">The cancellation token for the retrieval</param>
        Task<byte[]> GetCacheItemAsync(string key, CancellationToken token = default(CancellationToken));

        /// <summary>
        /// Update the cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        void RefreshCacheItem(string key);

        /// <summary>
        /// Update the cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        /// <param name="token">The cancellation token for the update</param>
        Task RefreshCacheItemAsync(string key, CancellationToken token = default(CancellationToken));

        /// <summary>
        /// Delete the cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        void DeleteCacheItem(string key);

        /// <summary>
        /// Delete the cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        /// <param name="token">The cancellation token for the deletion</param>
        Task DeleteCacheItemAsync(string key, CancellationToken token = default(CancellationToken));

        /// <summary>
        /// Insert cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        /// <param name="value">The cache value</param>
        /// <param name="options">The cache item entry options</param>
        void SetCacheItem(string key, byte[] value, DistributedCacheEntryOptions options);

        /// <summary>
        /// Insert cache item in the database
        /// </summary>
        /// <param name="key">The key of the cache item.</param>
        /// <param name="value">The cache value</param>
        /// <param name="options">The cache item entry options</param>
        /// <param name="token">The cancellation token for the insertion</param>
        Task SetCacheItemAsync(string key, byte[] value, DistributedCacheEntryOptions options, CancellationToken token = default(CancellationToken));

        /// <summary>
        /// Remove expired cache items from the database
        /// </summary>
        void DeleteExpiredCacheItems();
    }
```
I have set it up and adjusted the tests and the solution files here: [https://github.com/ddrdoubled/aspnetcore/tree/CachingDatabase](url)
let me know what you think

**Comment by Tratcher** [comment]
We've very hesitant to add these kinds of abstractions without multiple implementations to verify it is generic enough to be useful. DatabaseCache itself doesn't seem to have a meaningful amount of functionality to warrant existing on its own, especially when it doesn't provide any virtual methods to override.

Can you share your other derivation of DatabaseCache? What does it gain by deriving?

**Comment by ddrdoubled** [comment]
Sorry for the delay, would it be enough to provide an example for Oracle? Another possibility is an EF Core implementation which would avoid the need to specify explicitly the SQL statements. Although performance would be worse.

**Comment by Tratcher** [comment]
Any viable alternative implementation would do. We just need to see if the abstraction makes sense when implemented elsewhere.

> Another possibility is an EF Core implementation which would avoid the need to specify explicitly the SQL statements.

In your current example the DatabaseCache base class requires IDatabaseCacheOperations. Does that make sense for an EF based derived instance? Would you re-implement IDatabaseCacheOperations over EF? If that's the case then IDatabaseCacheOperations should probably be replaced by abstract methods on DatabaseCache that are overridden by the SQL, Mono, EF, etc. derived implementations.
