### ISSUE TITLE
Incorporate template analyzer into the build

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#35238]
We recently had a PR build failure due to a template update containing a JSON syntax error in the `host.json` file that wasn't reported by the .NET templating engine or CLI itself. It might be useful to configure the template build to run the template analyzer tool from @sayedihashimi so that the build fails if any issues are found.

Details of the tool can be found at https://github.com/sayedihashimi/template-sample#template-analyzer

**Comment by ShreyasJejurkar** [comment]
My trying to implement this for the repo. I have installed the tool successfully. But when I ran the tool from the command line, am getting the following error. 

![image](https://user-images.githubusercontent.com/17148381/140469114-4ae47b93-f5d9-41ef-92fd-147d368ec1c3.png)

Based on the wiki of the tool, we should pass the folder which contains `.template.config` folder. As you can see I am passing the same here, but still, tool was not able to find the given folder. I even checked the tool code but didn't find much there. 

https://github.com/sayedihashimi/dotnet-new-web/blob/master/src/Templates/AnalyzeTemplateCommand.cs#L90

@sayedihashimi Any help would be appreciated.

**Comment by sayedihashimi** [comment]
@ShreyasJejurkar what OS is the build running on? I may need to make some changes to ensure that the tool works correctly cross platform.
I ran the tool on Windows and it was working for the aspnet code. I do need to make a couple of updates to the analyzer to adjust for changes that we made in VS2022/.net 6. I will make those over the weekend and hopefully publish a new version by Monday.

**Comment by DamianEdwards** [comment]
I can't even get it to install on macOS, it just always says it can't find it 😢

**Comment by DamianEdwards** [comment]
OK so I got the tool to install (for some reason I had to explicitly pass in the nuget.org feed URL as a source) but now it just crashes immediately when I try to run it: `zsh: killed templates`

**Comment by sayedihashimi** [comment]
I will have investigate. Only tried on Windows thus far.

**Comment by ShreyasJejurkar** [comment]
> OK so I got the tool to install (for some reason I had to explicitly pass in the nuget.org feed URL as a source) but now it just crashes immediately when I try to run it: `zsh: killed templates`

Yup. Need to pass that. Default nuget.org feed is not in Nuget.config. So need to pass source explicitly or need to add entry of nuget.org in Nuget.config in root of repository.

**Comment by ShreyasJejurkar** [comment]
> @ShreyasJejurkar what OS is the build running on? I may need to make some changes to ensure that the tool works correctly cross platform. I ran the tool on Windows and it was working for the aspnet code. I do need to make a couple of updates to the analyzer to adjust for changes that we made in VS2022/.net 6. I will make those over the weekend and hopefully publish a new version by Monday.

Am developing under Linux codespaces. I got the tool install correctly, and can invoke it as well. But I tried running analyze command on folder, but getting above error.

**Comment by sayedihashimi** [comment]
I have made some changes and I think it's working in version `1.1.10` but I will do some additional testing. If you have time to try it with that version, let me know. I will spend some more time this weekend to test it more and get back to you all here.

**Comment by sayedihashimi** [comment]
Sorry I forgot to reply back earlier. I tested version `1.0.10` more and it seems good. When running on Ubuntu (WSL), I'm getting the following warnings for the aspnet templates, but no errors.

```
Validating '/home/sayedha/mycode/oss/aspnetcore/src/ProjectTemplates/Web.ItemTemplates/content/RazorComponent\.template.config\template.json'
    WARNING: 'shortname' should be 'shortName', incorrect casing

Validating '/home/sayedha/mycode/oss/aspnetcore/src/ProjectTemplates/Web.ItemTemplates/content/Protobuf\.template.config\template.json'
    WARNING: 'shortname' should be 'shortName', incorrect casing

Validating '/home/sayedha/mycode/oss/aspnetcore/src/ProjectTemplates/Web.ProjectTemplates/content/RazorComponentsWeb-CSharp\.template.config\template.json'
    WARNING: template.json not found at '/home/sayedha/mycode/oss/aspnetcore/src/ProjectTemplates/Web.ProjectTemplates/content/RazorComponentsWeb-CSharp/.template.config/template.json'
```

When there is an error it should return a non-zero exit code. If it would be helpful for me to convert the errors and warnings output to MSBuild formatted errors/warnings please let me know.

If you update to `1.0.10`, I believe it should work. Please let me know if you run into any issues. Later I'll be adding some more checks to ensure that any files listed in `template.json` are on disk.

**Comment by wtgodbe** [comment]
@DamianEdwards looks like we have a version of the analyzer that works cross-plat now, is this something you'd want to take on?

**Comment by DamianEdwards** [comment]
@wtgodbe if I end up doing any template updates this release perhaps, but it's probably unlikely honestly.

**Comment by wtgodbe** [comment]
Ok, I can add it to the build team backlog, though I'm not sure when we'll be able to get to it.

**Comment by wtgodbe** [comment]
Closing as stale
