### ISSUE TITLE
webassembly vs .net

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#35252]
webassembly is an enviornment allowing multiple language to be compiled to something intermediate for execution, just like .net, so why are we mixing the two together with blazor? just pick one and use it, the only way, would be making .net available to the web without running in the browser

**Comment by Xyncgas** [comment]
I guess we are already seeing detach of blazor from webassembly with the example of blazor desktop

**Comment by davidfowl** [comment]
So .NET can run inside of the browser sandbox

**Comment by Xyncgas** [comment]
If my .net application can have a web-like front end, maybe a new microsoft project that has browser engine combined with .net platform, we will never have to run our web in the browser as it is just for 'browsing' an url, we can still let people enter urls in windows OS to open up app without installing, they are basically hybrid app without webassembly that can run like a app, otherwise behaves like a website.
Imagine a future, I give you the url xx.xx.com
you put it in the start menu or whatever in windows
now you are running a web app without installing, but that web app isn't opened by the browser, it's still contained because internally it uses a browser but it's microsoft's edge browser, and the browser shares its stack without other components like.net
this solution is very cross platform compatible, the 'opening an app with url" experience might be exclusive to windows that's fine, windows has a large user base, other people can still fall back to webassembly if they open this url on chrome or mannually in edge.
This way, we give people a url to run our app, instead of them installling it, it just be running in sandbox, more permission can be requested, and app can directly access sysytem later with no friction, because the application isn't running completely in browser, the browser is only part of the stack, and webassebmly wasn't used at all app just runs on .net
make this all part of the operating system please.
people can continue to write their blazor wasm apps and publish versions that runs in the browser and that runs natively on windows, if targetting exclusively to windows without any fall back, you take full advantage of this approach, it's clean

**Comment by Xyncgas** [comment]
maybe I am wrong about where the app is contained.
but what I want is simple.
Web UI in native applications
