### ISSUE TITLE
AddAuthentication DefaultScheme is always exectued even though another scheme is defined

### ISSUE THREAD

**Issue by stefan-thaler-compLex** [dotnet/aspnetcore#35264]
Why is a default authentication scheme always executed even though you explicitly define another scheme in a controller within Authorize.
Scheme one is called AuthCode and the second scheme is called AuthAdmin. Default should be AuthCode.
AuthCodeExampleController (with explicit definition of the scheme name) and DefaultAuthCodeExampleController (only Authorize) are working correctly with the AuthCodeSchemeHandler (protected override Task<AuthenticateResult> HandleAuthenticateAsync is being called).
But if you call the AuthAdminExampleController (with explicit definition of the scheme name AuthAdmin) then first of all the AuthCodeSchemeHandler of the scheme named AuthCode is executed and only afterwards the correct AuthAdminSchemeHandler (protected override Task<AuthenticateResult> HandleAuthenticateAsync) is exectued. Strange thing: if you would return a AuthenticateResult.Success within the AuthCodeSchemeHandler you are not directly passed to the requested controller, because then you are passed to the second and the correct Handler (AuthAdminSchemeHandler) and only if there is a AuthenticateResult.Success given back you will be forwarded to the requested controller. At the end the result is the same, but the way to the goal is a bit strange and it's not clear why there are calls exectued which are not necessary due to defining explicit scheme name.
If you do not set options.DefaultScheme = AuthCodeSchemeOptions.SchemeName in the Startup.cs then there is always only one and the correct service called (except the DefaultAuthCodeExampleController).

.NET 5.0.301

Startup.cs -> within ConfigureServices:
services.AddAuthentication(options =>
            {
                options.DefaultScheme = AuthCodeSchemeOptions.SchemeName;
            })
            .AddAuthCode<AuthCodeService>(options =>
                {
                })
            .AddAuthAdmin<AuthAdminService>(options =>
                {
                });

AuthCodeExampleController.cs:
[Route("api/[controller]")]
[ApiController]
[Authorize(AuthenticationSchemes = AuthCodeSchemeOptions.SchemeName)]
public class AuthCodeExampleController : ControllerBase
{
}

DefaultAuthCodeExampleController.cs
[Route("api/[controller]")]
[ApiController]
[Authorize()]
public class DefaultAuthCodeExampleController : ControllerBase
{
}

AuthAdminExampleController.cs:
[Route("api/[controller]")]
[ApiController]
[Authorize(AuthenticationSchemes = AuthAdminSchemeOptions.SchemeName)]
public class AuthAdminExampleController : ControllerBase
{
}

**Comment by blowdart** [comment]
You're mixing up authn and authz here.

If you set the default authz policy to use the scheme you want this would work as you expect. 

```c#
public void ConfigureServices(IServiceCollection services)
{
    // ...other config as before
    services.AddAuthorization(options =>
    {
        options.DefaultPolicy = new AuthorizationPolicyBuilder()
            .AddAuthenticationSchemes("schemeName")
            .RequireAuthenticatedUser()
            .Build();
    });
}
```

**Comment by stefan-thaler-compLex** [comment]
Sorry, but this isn't clear for me - I think I have found the same problem [https://github.com/dotnet/aspnetcore/issues/27025](url) from @luoxlgh and the explanation there is, that the default scheme runs always (on top of every other scheme). In my opinion it doesn't make sense, that the default scheme runs always, when you explicitly set that another scheme should be run. Default means to me, that if no scheme is defined then run scheme number one but if you explicitly define scheme number two, then only scheme number two should be run. I am confused.
