### ISSUE TITLE
Re-enable Components E2E tests in release/6.0 branch after GA

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#35263]
We're going to [disable the Components E2E tests in the main build pipeline](https://github.com/dotnet/aspnetcore/pull/35189) as a temporary mitigation for reliability issues, and instead run them in a separate pipeline that doesn't block PR merges. The Blazor team will take responsibility for watching the status of this separate pipeline and taking action if things start failing.

This is only a temporary phase, and we don't want it to last throughout the 6.0 servicing lifetime. **As soon as 6.0 goes to GA and there's a `release/6.0` branch (or similar), we should re-enable the Components E2E tests there, regardless of whether the CI infrastructure issues are improved or not.** This is because it will no longer block developers from routine work, and it's very important that we get alerted by the system if patch changes cause regressions.

**Comment by mkArtakMSFT** [comment]
Closing as we have another issue tracking this.
