### ISSUE TITLE
Blazor wasm .net 6.0 preview 7 - reference to .net standard assembly - file not found

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/aspnetcore#35278]
Hi,

I have an odd issue. I have a hosted Blazor application where the client (webassembly) project has a reference to a .net standard 2.0 dll. The dll is in a folder outside of the solution. I've had no problems with this arrangement in .net 5.0 or in .net 6.0 preview 6.

However once I upgraded to preview 7 I started getting a "file not found" error on build for the standard library dll. It looks like it might be looking for the file in the wrong place.

To try and debug the issue I created a brand new project using VS2022 preview 3 (I also tried 2) and added a reference to my library dll but it also fails to compile with the same issue. It compiles happily as soon as I remove the file.

The reference in the project file looks like this (company name changed):

```
  <ItemGroup>
    <Reference Include="MyCompany.Core.Types">
      <HintPath>..\..\..\..\src\Dependencies\Net Standard 2.0\MyCompany\MyCompany.Core.Types.dll</HintPath>
    </Reference>
  </ItemGroup>
```

And the error is this:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find file 'C:\Source\testsrc\BlazorApp1\BlazorApp1\Client\MyCompany.Core.Types'.	BlazorApp1.Client	C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets	253	

```

"C:\Source\testsrc\BlazorApp1\BlazorApp1\Client" is the root of the client project, and not where the file is referenced from.

Any help appreciated, thanks!
LJ

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@pranavkm any recommendation on where this should go? dotnet/sdk ?
Thanks!

**Comment by pranavkm** [comment]
Sounds like a SWA thing. @javiercn

**Comment by tn-5** [comment]
@LaughingJohn Check the path name in the files & on disk. In P7 it seems there was some update where the check for the assets from the referenced project / dll is done case sensitive (regardless of file system case sensitivity).

**Comment by javiercn** [comment]
We've significantly changed the static web assets implementation in Preview7, as a temporary limitation, net6 projects don't mix and match with anything from before (net5, netstandard) you can upgrade the libraries temporarily to net6 if you need to get unblocked.

We've already removed this limitation in RC1

**Comment by LaughingJohn** [comment]
Aha, thanks for replying @javiercn, that explains it, I'll wait for RC1!
