### ISSUE TITLE
how can I assign the hover css to RadzenMenu? this way doesn't work

### ISSUE THREAD

**Issue by MMonteiro-21801093** [dotnet/aspnetcore#35275]
how can I assign the hover ou change text color css to RadzenMenu? this way doesn't work
.RadzenMenu:hover {
    background-color: #ff0000;
    color: red;
}
.RadzenMenu {
    background-color: #ffffff;
    color: rgb(0,0,255);
}

**Comment by blowdart** [comment]
Radzen isn't a Microsoft product. You'd be better off following t[heir support channels](https://forum.radzen.com/).
