### ISSUE TITLE
An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created

### ISSUE THREAD

**Issue by kofifus** [dotnet/aspnetcore#35283]
I updated my ASP.NET 6 to the latest preview 7 and updated all packages

When building I now get:

> warning CS8032: An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

MY CSproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
    <Nullable>enable</Nullable>
    <FileVersion>1.345.0.0</FileVersion>
    <Version>1.345.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.7.21378.4" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.1-dev-00229" />
    <PackageReference Include="Serilog.Sinks.File.Archive" Version="1.0.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
    <PackageReference Include="System.Management" Version="6.0.0-preview.7.21377.19" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>
</Project>
```

**Comment by pranavkm** [comment]
Is this when building your app using VS 2019?

**Comment by Mike-E-angelo** [comment]
I am getting this as well in 2022 Preview 3.0

**Comment by pranavkm** [comment]
> I am getting this as well in 2022 Preview 3.0.

@chsienki any suggestions on how we could go about diagnosing this? Preview 3 should include `Microsoft.CodeAnalysis, Version=4.0.0.0` no?

**Comment by Mike-E-angelo** [comment]
OK I think I found the problem on my end.  Switching to detailed build output I see the following:

```
1>  Using "Csc" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll".
1>  Task "Csc"
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csc.exe 
```

Visual Studio 2022 is using 2019's build folder?  Seems very wrong. :)  I looked in the settings and I don't see where this is configured.  I will continue to poke around further but would appreciate any pointers on where one might look for this toggle.

**Comment by Mike-E-angelo** [comment]
ARRG... the reason why VS2022 is using 2019 is that VS2022 is actually 2019!

🤦‍♂️

So I was working on a more complex solution and was running into problems with NuGet.  My thought was to close that solution and open another simpler solution and get that working first.  So I closed that solution and double-clicked reopened the simpler SLN in Windows Explorer, which is still tied to VS2019.  Doh.

I can confirm that running this in VS2022 works and everything is happy again.

I'll now show myself out. :P

**Comment by kofifus** [comment]
I can confirm this is only a VS189 preview issue. Note that because the source generator doesn't run properly the server pages are not generated and basically the server is broken. Also the blank ASP.NET core template doesn't compile .. even though this is a preview I am surprised there is no stronger testing at least of templates

**Comment by pranavkm** [comment]
Starting in preview 7, .NET 6 requires using VS 2022 so the error seen with VS 2019 isn't surprising. I think at some point VS 2019 is expected to start notifying you that you're building an unsupported .NET version when you open a .NET 6 app.

**Comment by kofifus** [comment]
It would be helpful if VS19 will warn when compiled with .NET 6 > preview 7
