### ISSUE TITLE
Blazor: browser refresh not working when running in virtual path

### ISSUE THREAD

**Issue by robi26** [dotnet/aspnetcore#35291]
Hi
The _framework/aspnetcore-browser-refresh.js file is not found when a blazor server is running in a virtual path.

Repo:
1. Create Blazor server app in Visual Studio (using VS 2019 16.11.0)
2. Change the applicationUrl in iisSettings->iisExpress to "http://localhost:38327/test"
3. Start web app without debugging
4. Change any file
Bug: Browser does not automatically refresh

Expected behavior: browser refreshes automatically.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/34975
