### ISSUE TITLE
`Microsoft.CodeAnalysis.Razor` has Apparent Invalid Dependency

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#35300]
### Describe the bug
`Microsoft.CodeAnalysis.Razor` [on NuGet](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Razor/6.0.0-preview.7.21378.6) lists the following as dependencies:

```
Microsoft.CodeAnalysis.Common (>= 4.0.0-2.21354.7)
Microsoft.CodeAnalysis.CSharp (>= 4.0.0-2.21354.7)
```

However, the posted versions on NuGet are:
`Microsoft.CodeAnalysis.CSharp`: [4.0.0-2.final](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/4.0.0-2.final)
`Microsoft.CodeAnalysis.Common`: [4.0.0-2.final](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/4.0.0-2.final)

### To Reproduce

Attempt to install a NuGet package that depends on `Microsoft.CodeAnalysis.Razor`.

### Exceptions (if any)
The following message displays in the error list:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Microsoft.CodeAnalysis.CSharp with version (>= 4.0.0-3.21370.20)
  - Found 116 version(s) in nuget.org [ Nearest version: 4.0.0-2.final ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

Additional outputs:

```
33> ... : warning NU1603: Microsoft.CodeAnalysis.Razor 6.0.0-preview.7.21378.6 depends on Microsoft.CodeAnalysis.Common (>= 4.0.0-2.21354.7) but Microsoft.CodeAnalysis.Common 4.0.0-2.21354.7 was not found. An approximate best match of Microsoft.CodeAnalysis.Common 4.0.0-2.final was resolved.
33> ... : warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration 6.0.0-preview.7.21406.1 depends on System.Collections.Immutable (>= 6.0.0-preview.7.21377.12) but System.Collections.Immutable 6.0.0-preview.7.21377.12 was not found. An approximate best match of System.Collections.Immutable 6.0.0-preview.7.21377.19 was resolved.

33> error NU1102: Unable to find package Microsoft.CodeAnalysis.CSharp.Workspaces with version (>= 4.0.0-3.21370.20)
33> error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 4.0.0-2.final ]
33> error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
33> error NU1102: Unable to find package Microsoft.CodeAnalysis.CSharp with version (>= 4.0.0-3.21370.20)
33> error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 4.0.0-2.final ]
33> error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

```

### Further technical details
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
`Visual Studio 2022 Preview 3.0`

**Comment by Pilchie** [comment]
@jaredpar - any idea when the Roslyn packages will be published?

**Comment by jaredpar** [comment]
@JoeRobich

**Comment by JoeRobich** [comment]
@Pilchie Sorry for the delay we hit a snag during validation. Packages are now published.

**Comment by bfren** [comment]
This is still an issue, but with different analysis packages (`.Common` and `.CSharp`):

```
Warning	NU1603	Microsoft.CodeAnalysis.Razor 6.0.0-preview.7.21378.6 depends on Microsoft.CodeAnalysis.Common (>= 4.0.0-2.21354.7) but Microsoft.CodeAnalysis.Common 4.0.0-2.21354.7 was not found. An approximate best match of Microsoft.CodeAnalysis.Common 4.0.0-2.final was resolved.
Warning	NU1603	Microsoft.CodeAnalysis.Razor 6.0.0-preview.7.21378.6 depends on Microsoft.CodeAnalysis.CSharp (>= 4.0.0-2.21354.7) but Microsoft.CodeAnalysis.CSharp 4.0.0-2.21354.7 was not found. An approximate best match of Microsoft.CodeAnalysis.CSharp 4.0.0-2.final was resolved.
```

Latest posted versions of those are both `4.0.0-3.final`.

**Comment by Mike-E-angelo** [comment]
Thank you all for your efforts here!  It is very much appreciated.  I have been spending my morning attempting to get the latest and returned back here to report what @bfren has already stated.  I can now build but warnings still persist.

**Comment by Pilchie** [comment]
@pranavkm - any ideas here?

**Comment by pranavkm** [comment]
@JoeRobich any chance we could have those specific versions uploaded for p7 to function? For rc1 and later, we can pin the Roslyn package references to a specific version

**Comment by JoeRobich** [comment]
I can publish this pre-release package version as unlisted. Version `4.0.0-2.final` should satisfy the `>= 4.0.0-2.21354.7` version constraint, but I guess generates a warning because it isn't an exact match.

**Comment by JoeRobich** [comment]
4.0.0-2.21354.7 packages have been published to NuGet.org

**Comment by Mike-E-angelo** [comment]
Ok awesome.  That took care of one of my warnings.  I do have another remaining:

```
warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration 6.0.0-preview.7.21412.2 depends on System.Collections.Immutable (>= 6.0.0-preview.7.21377.12) but System.Collections.Immutable 6.0.0-preview.7.21377.12 was not found. An approximate best match of System.Collections.Immutable 6.0.0-preview.7.21377.19 was resolved.
```

I have reported this here: https://github.com/dotnet/Scaffolding/issues/1619

Thanks again for all your assistance here!
