### ISSUE TITLE
No overload for method RegisterBlazorMauiWebView takes 1 argument

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#35303]
Upgraded my VS2022 to the latest preview today and created MAUI Blazor App.
Getting Error "No overload for method RegisterBlazorMauiWebView takes 1 argument"
in the startup.cs of MAUI App
![image](https://user-images.githubusercontent.com/3267605/129266563-915522e5-a1f8-41ca-99f8-a22d642592d5.png)

**Comment by Eilon** [comment]
Hi @nssidhu to fix this, you can remove the `typeof(Startup).Assembly` from that line because it is no longer needed.

**Comment by nssidhu** [comment]
FYI: VS2022 Create new Project Template for MAUI Blazor itself is broken. I have to manually update the each Package.
[Link to Video](https://1drv.ms/v/s!AtHk7h6Srnk_h9cghtv6YiKmhrQ99g?e=VGWtFj)
Above is the video of the File/Create New Project / MAU Blazor Template
Also can we expect Blazor WASM Hosted(with server side for API) Template as well ?
Would there be any guidance on how to use existing Blazor WASM Hosted(with backend API & shared Project) project with this new MAUI Project, so that we don't have to rewrite the entire months of project work again ?

**Comment by Eilon** [comment]
@nssidhu this looks like a separate issue. Did you install the official .NET 6 Preview 7 installers, or are you using a "nightly build" of RC1? Can you log a new issue with all the details of what you installed?
