### ISSUE TITLE
Unexpected behaviour with css attribute selectors and css isolation.

### ISSUE THREAD

**Issue by TimDaborn** [dotnet/aspnetcore#35311]
# Blazor: Unexpected behaviour with css attribute selectors and css isolation.

### Describe the bug

I get different results with CSS attributes, depending on whether the CSS is in the project’s app.css or a control’s CSS (which is subject to css isolation). 
The issue arises when the CSS already has an attribute selector.

### To Reproduce

I have created a project at: https://github.com/TimDaborn/CSSIsolationTest/

![CSSIsolationTest](https://user-images.githubusercontent.com/16775016/129278353-edf30457-b4d9-47f7-911a-b280de08dec9.png)

In the project I am attempting to hide the button/default text in 2 Blazor InputFile components. 

Both components are decorated with identical CSS, except the CSS for one resides in app.css, and the other in Index.css.

 
The failing CSS has an attribute selector:

	.indexcss-drop-area input[type="file"]
	
There appears to be a conflict with this selector and the one created as part of the css isolation.

### Possible Solution

The css generated by css isolation is:

    .indexcss-drop-area input[type="file"][b-ka1wqpevsr], {
        position: absolute;
        background-color: lightgray;
        width: 100%;
        height: 100%;
        opacity: 0;
        cursor: pointer;
    }

I believe if there was a comma between the 2 selectors, then it would work? E.G.

    .indexcss-drop-area input[type="file"],[b-ka1wqpevsr]

### Further technical details
- ASP.NET Core version 5

**Comment by javiercn** [comment]
@TimDaborn thanks for contacting us.

You need to apply the `::deep` selector as explained [here](https://docs.microsoft.com/es-es/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support-1)

Scoped CSS works at the file level. You can't style another component within your file directly, otherwise you would break their isolation.

**Comment by TimDaborn** [comment]
Thanks Javier, 

I had tried `::deep`, but having revisited code following your comment, I now realise that `::deep` combinator appears only to effect the selector it immediately precedes and not any subsequent selector in the element.

Thus, the following does not work

> **_::deep_** .indexcss-drop-area input[type="file"] 

But the line below does work

>  .indexcss-drop-area **_::deep_** input[type="file"] 

I don't think the documentation makes this clear.  I wrongly assumed the `::deep` combinator at the beginning of the line effected both the class and the attribute selector.

I might do a blog post on this!

Again, thank you for help, I will mark this as closed.

**Comment by javiercn** [comment]
@TimDaborn Feel free to contribute to the docs page for this. We are always happy to take improvements.
