### ISSUE TITLE
Allow more failure details for AuthZ handlers

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#35319]
Today there's no way to signal anything other than which requirements have failed or an explicit Fail https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Core/src/AuthorizationHandlerContext.cs#L82

This makes it hard for a handler to flow more specific error information/details to the `IAuthorizationMiddlewareResultHandler`

**Comment by Tratcher** [comment]
API suggestions and data flow:

Overload Fail to pass state. Should it also pass some key for which requirement failed, or is the state itself they key?
https://github.com/dotnet/aspnetcore/blob/302ed3c6cffed260fc2f13641dd2f39f9cde7fc7/src/Security/Authorization/Core/src/AuthorizationHandlerContext.cs#L82

```diff
public class AuthorizationHandlerContext
{
+ // Calls Fail() and stores the failure state for future reference. Can be called multiple times.
+ public virtual void Fail(object state);
+ public IEnumerable<object> FailureStates { get; }
```

The IAuthorizationEvaluator checks for failure and bundles it into an AuthorizationFailure
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authorization/Core/src/DefaultAuthorizationEvaluator.cs#L19-L20
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authorization/Core/src/AuthorizationFailure.cs#L31

```diff
public class AuthorizationFailure
{
+ // Calls Fail and stores the failure state for future reference. Can be called multiple times.
+ public static void ExplicitFail(IEnumerable<object> state);
+ public IEnumerable<object> FailureStates { get; }
```

Which ends up on the AuthorizationResult:
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authorization/Core/src/AuthorizationResult.cs#L24
Which is then passed to the IAuthorizationMiddlewareResultHandler
https://github.com/dotnet/aspnetcore/blob/302ed3c6cffed260fc2f13641dd2f39f9cde7fc7/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L105-L107
https://github.com/dotnet/aspnetcore/blob/302ed3c6cffed260fc2f13641dd2f39f9cde7fc7/src/Security/Authorization/Policy/src/IAuthorizationMiddlewareResultHandler.cs#L24

**Comment by HaoK** [comment]
@Tratcher @blowdart how do you feel about ExplicitFail/States => FailureReason(s)?

**Comment by HaoK** [comment]
I don't think it necessarily makes sense to force correlation of requirements/reasons, but we could do Handler -> reasons, since that is really the split, but the failure state should be the mechanism to communicate information, if the handler wants to enumerate the requirements that failed, they are free to put that in the failure reason explicitly, but that mapping is completely up to the app/handlers

**Comment by blowdart** [comment]
State has multiple meanings, I'd prefer reasons. But object feels, odd to me. I'd suggest an interface here with, at least, a message property, so folks don't have to cast around if they don't want to?

As an aside aren't there old issues about this? We should link them.

**Comment by HaoK** [comment]
Isn't the argument against interfaces for something like future breaking change concerns?  We could do a base FailureReason class which has a message property?

**Comment by davidfowl** [comment]
Did this get API reviewed?

**Comment by HaoK** [comment]
Oops, no I'll add the labels

**Comment by pranavkm** [comment]
* Remove setters from properties.

```diff
public class AuthorizationFailureReason
{
+   public AuthorizationFailureReason(IAuthorizationHandler handler, string message)
+   public string Message { get; }
+   public IAuthorizationHandler Handler { get; }
}

API consideration: Can this type be sealed and use a `IDictionary` to pass additional data instead e.g.

```diff
+public sealed class AuthorizationFailureReason
{
+   public AuthorizationFailureReason(IAuthorizationHandler handler, string message)
+   public string Message { get; }
+   public IAuthorizationHandler Handler { get; }
+   public IDictionary<object, object> Properties { get; } 
}
```

AuthorizationFailure

* Update property name to `FailureReasons` for consistency:

```diff
public class AuthorizationFailure
{
+ // Calls Fail and stores the failure reasons for future reference. Can be called multiple times.
+ public static void ExplicitFail(IEnumerable<AuthorizationFailureReason> reasons);
+ public IEnumerable<AuthorizationFailureReason> FailureReasons { get; }
```

**Comment by pranavkm** [comment]
@blowdart / @adityamandaleeka  is someone on point to update the PR based on the API feedback?

**Comment by blowdart** [comment]
If hao isn't here @Tratcher i'd guess

**Comment by Kahbazi** [comment]
@pranavkm I'm interested in doing this. May I send the PR?

**Comment by pranavkm** [comment]
We'd appreciate that @Kahbazi. Thanks!

**Comment by Tratcher** [comment]
A) There's an RC1 PR here that needs updating: https://github.com/dotnet/aspnetcore/pull/35529. @Kahbazi you'll need to send a PR to that branch.
B) Main also needs updating.
C) There's an outstanding point to resolve first:

> ```diff
> API consideration: Can this type be sealed and use a `IDictionary` to pass additional data instead e.g.
> ```

@blowdart? When designing this we specifically discussed an unsealed type that could be derived from to add strongly typed data. Using a loosely typed dictionary didn't come up. Either way requires downcasting, though with the derived type it would only be a single downcast instead of per property.

**Comment by blowdart** [comment]
A single cast seems the better approach, less error prone and faster.

**Comment by Tratcher** [comment]
> ```diff
> + public static void ExplicitFail(IEnumerable<AuthorizationFailureReason> reasons);
> ```

This is outdated, the name used in the PR is:
> ```diff
> + public static void Fail(IEnumerable<AuthorizationFailureReason> reasons);
> ```

**Comment by davidfowl** [comment]
Are we sure we want `IEnumerable<T>` , allocations...
