### ISSUE TITLE
Virtualize show Placeholder after call RefreshDataAsync

### ISSUE THREAD

**Issue by farazp** [dotnet/aspnetcore#35315]
### Describe the bug
I using RefreshDataAsync method to refresh item, but after call this method the Placeholder show and not hiden after that

```
<Virtualize Context="Item" ItemsProvider="@LoadItems" OverscanCount="50" @ref="VirtualizeContainer">
                        <ItemContent>
                            <tr>
                                <td>@Item.X</td>
 <td><button type="button" @onclick="@(()=>DeleteItem(Item.Id))">Delete</button></td>
                            </tr>
                        </ItemContent>
                        <Placeholder>
                            <div class="d-flex justify-content-center">
                                <div class="spinner-border" role="status">
                                    <span class="visually-hidden">Loading...</span>
                                </div>
                                <span>Loading...</span>
                            </div>
                        </Placeholder>
                    </Virtualize>
```
and in code section

```
private int totalItems { get; set; }
private List<Items> ItemsList { get; set; } = new();
private Virtualize<Slug> VirtualizeContainer { get; set; }


private async ValueTask<ItemsProviderResult<Items>> LoadItems(ItemsProviderRequest request)
    {
        SlugsList = await pageService.GetVirtualizeSlugs(request);
        return new ItemsProviderResult<Slug>(SlugsList, totalSlugs);
    }

    private async Task DeleteItem(Guid itemId)
    {
        await itemService.DeleteItem(itemId);
        await VirtualizeContainer.RefreshDataAsync();
        StateHasChanged();
    }
```

I think this is bug or how can control the Placeholder for Show/Hide?

**Comment by SteveSandersonMS** [comment]
Thanks for the report. Are you able to supply a minimal repro project, ideally as a GitHub issue? We will then investigate.

**Comment by farazp** [comment]
> Thanks for the report. Are you able to supply a minimal repro project, ideally as a GitHub issue? We will then investigate.

Hi, Steve https://github.com/farazp/BlazorVirtualizer.git

I created a test project to determine exactly what was going on.
In the display list, when you delete one of the items, you see that the bottom of the list is constantly previewed.

**Comment by SteveSandersonMS** [comment]
@farazp I investigated, and there's a bug in your code here:

```cs
    private async ValueTask<ItemsProviderResult<Slug>> LoadSlugs(ItemsProviderRequest request)
    {
        var numContent = Math.Min(request.Count, totalSlugs - request.StartIndex);

        SlugsList = await contentServie.GetContent(request.StartIndex,
            numContent, request.CancellationToken);

        return new ItemsProviderResult<Slug>(SlugsList, totalSlugs);
    }
```

Notice that it uses `totalSlugs` as the item count, which is a fixed value set up front and not updated when you deleted items. So after you've deleted one, it continues to think there are more items to fetch, hence there's a placeholder.

By changing the last line there to the following, it is fixed:

```cs
return new ItemsProviderResult<Slug>(SlugsList, contentServie.ContentCount());
```

As a sidenote, I notice that your `ItemContent` is a `<tr>`, whereas your `Placeholder` is a `<div>`. I don't recommend having this mismatch, as you're then relying on a `div` inside a `tbody` rendering in the same style as a `tr`. I would recommend changing your `Placeholder` to be a `<tr>` like the `ItemContent`.
