### ISSUE TITLE
Https Endpoint doesn't use keep-alive connections

### ISSUE THREAD

**Issue by tkaepp** [dotnet/aspnetcore#35329]
### Describe the bug
Connections made to the https endpoint won't use keep-alive connections while the http endpoint does this be default.

We are in the process of analyzing production issues where we run around 20 kestrel webservers behind a NGINX loadbalancer. While debugging the connection handling between applications and trying to simplify the setup I found this behaviour. 

My Question: Is this intended or expected behaviour? I assumed that it doesn't matter if the connection is tcp or tcp+tls.

Also to note: I develop directly on a linux machine and used the [ss](https://man7.org/linux/man-pages/man8/ss.8.html) tool. Our production workload runs in containers and I wanted to debug locally as close to our setup.

### To Reproduce
1. Create a new project and start the server. [I also pushed my repo to github for reference](https://github.com/tkaepp/keepalive-repro)
```
dotnet new web -o keepalive
cd keepalive
dotnet run
# the server should start on the ports 5000 (http) and 5001 (https)
```
2. open a new shell and start the socket statistics tool to show connection events for the ports 5000 and 5001.
```
ss -tEn sport :5000 or sport :5001
```
3. run a load testing tool. I used [bombardier](https://github.com/codesenberg/bombardier)
```
bombardier http://localhost:5000 -c 1
bombardier https://localhost:5001 -c 1
```
4. Check the result on the ss tool. But the result should be visible in any network tracing tool like tcpdump or wireshark. The test for port 5000 closes the connections after the testrun is complete. Because we use the parameter `-c 1` only one connection is used. The expected result here is that only one or maybe a handful connections are used. The result for the port 5001 is that new connection get opened and closed in real-time while the test is running. Also a lot of connections end up in a TIME_WAIT status when using netstat -tn

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
>  tkae@dev-zh-204 ~/dev/keepalive$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

> Runtime Environment:
 OS Name:     gentoo
 OS Version:  
 OS Platform: Linux
 RID:         gentoo-x64
 Base Path:   /opt/dotnet_core/sdk/5.0.302/

> Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

> .NET SDKs installed:
  3.0.100 [/opt/dotnet_core/sdk]
  3.1.106 [/opt/dotnet_core/sdk]
  3.1.300 [/opt/dotnet_core/sdk]
  3.1.401 [/opt/dotnet_core/sdk]
  5.0.100 [/opt/dotnet_core/sdk]
  5.0.203 [/opt/dotnet_core/sdk]
  5.0.302 [/opt/dotnet_core/sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/opt/dotnet_core/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/opt/dotnet_core/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/opt/dotnet_core/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/opt/dotnet_core/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/opt/dotnet_core/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/opt/dotnet_core/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/opt/dotnet_core/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/opt/dotnet_core/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
-- for this reproduction I just used the dotnet cli.

**Comment by davidfowl** [comment]
The connections both http and https are definitely keep alive. You can try using the dotnet counters global tool (https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters) to see how many connections are being created. The  well known counters can be listed using:

dotnet-counters list --runtime-version 5.0

**Comment by tkaepp** [comment]
Thanks a lot for pointing out the dotnet-counters. I didn't know that there are so many new metrics. Those will help a lot in the future.

For my reported issue... The problem are failed SSL Handshakes because of the self-signed certificates. Ignoring certificate errors with `-k` helps. Cool that those metrics are reported!
```
bombardier https://localhost:5001 -c 1 -k
```

**Comment by davidfowl** [comment]
Glad it helped!
