### ISSUE TITLE
InvariantGlobalization 6.0 bug when component have  EditForm

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#35324]
The following project config throws when using a form. Happens in 6.0 when hotreload is enabled
```
<PropertyGroup>
  <InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>
```

In latest preview 7 this is the error shown in console
![image](https://user-images.githubusercontent.com/3386797/129303922-ba954e07-d8d3-49aa-a130-5c5680af9037.png)

**Comment by SteveSandersonMS** [comment]
Thanks for the report. Are you able to supply a minimal repro project, ideally as a GitHub issue? We will then investigate.
