### ISSUE TITLE
Enumerable dependencies resolving issue when open generic is used

### ISSUE THREAD

**Issue by skclusive** [dotnet/aspnetcore#35326]
### Describe the bug
Enumerable dependencies are not resolved as expected compared to console app when open generic services are registered later.

Ex:

#### Setup
```csharp
interface IProcessor<T> {}

record AnyProcessor<T> : IProcessor<T>;

record IntProcessor : IProcessor<int>;
```

#### Registration
```csharp
builder.Services.TryAddEnumerable(ServiceDescriptor.Scoped(typeof(IProcessor<int>), typeof(IntProcessor)));
// Fix: ordering open generic above concretes
builder.Services.TryAddEnumerable(ServiceDescriptor.Scoped(typeof(IProcessor<>), typeof(AnyProcessor<>)));
```

#### Resolving
```csharp
//  returns "IntProcessor -- IntProcessor" instead of IntProcessor -- AnyProcessor (as in console app)
app.MapGet("/", (IEnumerable<IProcessor<int>> processors) => string.Join(" -- ", processors.Select(p => p.GetType().Name)));
```

### To Reproduce

sample repo to reproduce the bug https://github.com/skclusive/EnumerableCallSiteBugWebApp

### Further technical details
- ASP.NET Core dotnet 6 preview 7
- `dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Microsoft Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 3.0

**Comment by davidfowl** [comment]
How is this different from https://github.com/dotnet/runtime/issues/57333?

**Comment by skclusive** [comment]
In #57333 the behavior is caused after a particular usage. otherwise it works as expected. 

ex: var processor = scope.ServiceProvider.GetService<IProcessor<int>>(); if code not used, it works fine in console app.

but in aspnetcore, without that usage itself the bug occurs. i guess the callsitecache in CallSiteFactory are loaded on startup itself.

raised here for the default behavior difference between console and aspnet app and for tracking purpose. 

please close this ticket if both could be handled in #57333 itself.
