### ISSUE TITLE
Possibility to remove Controller at runtime

### ISSUE THREAD

**Issue by angelaki** [dotnet/aspnetcore#35327]
I'd like to remove a controller of a separate assembly in runtime - but not all the assembly's controllers! I've seen this issue https://github.com/dotnet/aspnetcore/issues/7118 that showed how to remove complete `ApplicationParts`. But I'd rather remove a ApplicationPart's feature.

**Comment by davidfowl** [comment]
Here's an example of a dynamic application part that lets you add assemblies https://gist.github.com/davidfowl/d16c352c19b89acc2a20fe4c1061cad9. Maybe you could tweak it to handle individual controller types being removed.

**Comment by angelaki** [comment]
Thank you! Building my own `ApplicationPart` would be a possible workaround, yes. I've just checked that with 6.0 the `AssemblyPart` got a property `Types`. How about making it mutable? Or is this just my, too specific, scenario?

**Comment by davidfowl** [comment]
No, it's not thread safe and complicating this scenario for a rare scenario isn't worth it. Making it mutable is enough either. For complex scenarios, you can implement you own application part, that's why it's extensible

**Comment by angelaki** [comment]
Ok ... Too bad ... But understandable 👍
