### ISSUE TITLE
Add version to css of nuget package when load page

### ISSUE THREAD

**Issue by doanhquang2005** [dotnet/aspnetcore#35333]
When updating the new nuget package, the css files are cached. I suggest needing to add version to css files. Eg:
_content/HT.Components/HT.Components.bundle.scp.css?v=5.0.9
It is mandatory to use v={vesion package} because to allow me to be able to preload the css file of this package.
![image](https://user-images.githubusercontent.com/30622119/129371711-dae29ecc-2613-49ec-a1f6-befa3cba3228.png)

**Comment by pranavkm** [comment]
We discussed this and think we want to explore sending the right set of headers (e.g. `Must-Revalidate`) for static files by default. For the time being, we recommend adding a middleware that configures the right cache headers for static files. We don't think modifying the file name to perform cache busting is a good solution.
