### ISSUE TITLE
How turn off auto render "//" to href attribute

### ISSUE THREAD

**Issue by doanhquang2005** [dotnet/aspnetcore#35335]
Eg: navigationManager.BaseUri = "https://xyz.fun/";
`<link rel="canonical" href="@navigationManager.BaseUri" />` => render: `<link rel="canonical" href="//xyz.fun/" />`
`<a href="http://abc.com">Page ABC</a>` => render: `<a href="//abc.com">Page ABC</a>` => when click redirect to https://abc.com (Error page because abc.com doesn't have https)
How turn off auto render "//" to href attribute?
![image](https://user-images.githubusercontent.com/30622119/129390845-e1ed2c3e-1c03-419c-9ccd-2e210c3db48e.png)

**Comment by SteveSandersonMS** [comment]
Thanks for the report. We haven't seen this happen before. Would you please be able to supply a minimal repro project, ideally as a GitHub repo? We will then be able to investigate.

**Comment by doanhquang2005** [comment]
I created a new project for demo. I found this error due to package WebMarkupMin. I apologize for not checking this out!

**Comment by SteveSandersonMS** [comment]
Thanks for confirming!
