### ISSUE TITLE
ASP.NET Core *. StaticWebAssets.xml get unexpectedly deleted in the dependent project's output directory on build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35345]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNET-Core-StaticWebAssetsxml-get-u/1461438)._

---
**Environment showing the problem**
- Most recent VS Enterprise 2019 16.10.2 with ASP.NET Core 5.0.7
- Most recent VS Enterprise 2019  16.11.0 Preview 2.0 with ASP.NET Core 6.0 Preview

**Set-up overview**
- MyRCL is a razor class library project with static assets (an image file in wwwroot\).
- MyWebsite is an ASP.NET Core Web App dependent on MyRCL.
- MyTests is a test project dependent on MyWebsite and MyRCL.

**Brief description of the issue**
- Rebuild on MyTests causes all three projects to be rebuilt, with MyRCL.StaticWebAssets.xml and MyWebsite.StaticWebAssets.xml placed in MyTests\bin\Debug\net5.0\ - WHICH IS CORRECT
- Build on MyTests, when only MyTests is built, causes *. StaticWebAssets.xml being deleted from MyTests\bin\Debug\net5.0\ - WHICH IS INCORRECT

**How this impacts me**
MyTests is supposed to run MyWebsite for functional testing. Without *. StaticWebAssets.xml, MyWebsite misbehaves. 

**Detailed repro steps**

*Prepare projects*

1. In Visual Studio, create a new "ASP.NET Core Web App" C# project named "MyWebsite" with default settings (Target Framework: .NET 5.0, Authentication Type: None, Configure for HTTPS: No, Enable Docker: No, Enable Razor compilation: No).
2. Add a new project "Razor Class Library" C# project named "MyRCL" with default settings (Target Framework: .NET 5.0, Support pages and views: No).
3. Add a new "xUnit Test Project" C# project named MyTests with default settings (Target Framework: .NET 5.0).
4. Right-click MyWebsite > Add > Project Reference, select MyRCL.
5. Right-click MyTests > Add > Project Reference, select MyRCL and MyWebsite. 
6. Set MyTests as the startup project.
7. Select Debug is the current configuration.

*Full rebuild - CORRECT*

8. Right-click MyTests > Rebuild. All three projects get rebuilt:

1>------ Rebuild All started: Project: MyRCL, Configuration: Debug Any CPU ------
    2>------ Rebuild All started: Project: MyWebsite, Configuration: Debug Any CPU ------
    3>------ Rebuild All started: Project: MyTests, Configuration: Debug Any CPU ------
    ========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

9. Navigate to MyTests\bin\Debug\net5.0\ to see that the folder contains both _MyRCL.StaticWebAssets.xml_ and _MyWebsite.StaticWebAssets.xml_, which is correct.

*Build - KIND OF CORRECT*

10. Right-click MyTests > Build. Even though all projects has just been rebuild, 2 or 3 of them get built again. They shouldn't have, and it appears to be a separate bug, but it's unrelated to the problem at hand:

1>------ Build started: Project: MyRCL, Configuration: Debug Any CPU ------
	2>------ Build started: Project: MyWebsite, Configuration: Debug Any CPU ------
	3>------ Build started: Project: MyTests, Configuration: Debug Any CPU ------
	========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

11. Navigate to MyTests\bin\Debug\net5.0\ to see that the folder contains both _MyRCL.StaticWebAssets.xml_ and _MyWebsite.StaticWebAssets.xml_, which is correct.

*Build - CORRECT*

12. Right-click MyTests > Build. As expected, nothing is built because all three projects are up to date:

========== Build: 0 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========

13. Navigate to MyTests\bin\Debug\net5.0\ to see that the folder contains both _MyRCL.StaticWebAssets.xml_ and _MyWebsite.StaticWebAssets.xml_, which is correct.

*Modify and Build - INCORRECT*

14. Modify MyTests > UnitTests1.cs (for example, type a space at the end of any line of code).
15. Right-click MyTests > Build. As expected, only MyTest is built:

1>------ Build started: Project: MyTests, Configuration: Debug Any CPU ------
	========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

16. Navigate to MyTests\bin\Debug\net5.0\ to see that both _MyRCL.StaticWebAssets.xml_ and _MyWebsite.StaticWebAssets.xml_ are GONE, WHICH IS INCORRECT. Based on Process Monitor logs, those XML files where deleted by MSBuild.exe.

17. If we do Rebuild now (see step 8), then  _*. StaticWebAssets.xml_ will be reinstated.

**Conclusion**

Overall, this behavior is very confusing and it was quite hard to track down. The build process should produce consistent results regardless of whether its Build or Rebuild.

I also tried "dotnet build", but this tool seems to behave differently, so the issue seems to apply specifically to Visual Studio.

Attached are the projects created as described in steps 1-5 above. I deleted MyWebsite\wwwroot\lib to reduce the size of the ZIP file.

Thanks!

---
#### Feedback Bot on 6/27/2021, 06:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### m.juhas on 7/28/2021, 09:35 PM: 

<p>Hi everybody,</p>
<p>we are using different framework (.NET Core 3.1) and different WEB project (Blazor) but we have observed similar behavior. (VS Professional 16.10.3).</p>
<p>Looks like the VS deletes *.StaticWebAssets.xml files in shared output directory on partial solution build. If particular web project is not part of this partial build the file remains missing. This leads for example to debugging problems (missing web resources) and the solution needs to be rebuild whole to regenerate the files which is time consuming (we have 70+ projects in solution)</p>
<p>I highly vote for investigation of the problem described by Nikolay Repine!</p>
<p>Thank you and best regards.</p>

#### Anders Havn on 7/28/2021, 10:57 PM: 

<p>Hi,</p>
<p>We are also having the exact same problem. Could be nice with an update from “the appropriate engineering team”.</p>
<p>Thank you.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by 2932** [comment]
Madarcod toke cudbo

**Comment by DerekSMorin** [comment]
We have had intermittent compile failures with this in Azure Devops.

Bundler: Done processing bundleconfig.json 

e:\vsts\a\_tool\dotnet\sdk\6.0.100-preview.7.21379.14\Microsoft.Common.CurrentVersion.targets(4973,5): error MSB3030: Could not copy the file "e:\vsts\a\18349\s\Bentley.Interoperability.RazorCommon\obj\Release\netcoreapp3.1\staticwebassets\Bentley.Interoperability.RazorCommon.StaticWebAssets.xml" because it was not found. [e:\vsts\a\18349\s\Bentley.Interoperability.Web\Bentley.Interoperability.Web.csproj]

**Comment by CocoDico78** [comment]
Here is a minimal repo to reproduce the error. `dotnet publish` fails after a partial build. https://github.com/CocoDico78/StaticWebAssetsBug

**Comment by javiercn** [comment]
I'm not able to repro this behavior with the latest 6.0 RC2 builds.

**Comment by DerekSMorin** [comment]
> I'm not able to repro this behavior with the latest 6.0 RC2 builds.

Were you able to try the repro that CocoDico78 posted?

We are hitting this pretty regularly in our repo.

We tried adding Polly with a retry on the dotnet publish step in our build.cake script but now we are getting:

error NETSDK1152: Found multiple publish output files with the same relative path:

Probably related to trying to run dotnet publish more than once.

**Comment by javiercn** [comment]
@DerekSMorin that's what I tried it with.

**Comment by DerekSMorin** [comment]
@CocoDico78 

> Here is a minimal repo to reproduce the error. `dotnet publish` fails after a partial build. https://github.com/CocoDico78/StaticWebAssetsBug

I also was unable to reproduce locally.  But I guess it might depend on what versions of things are installed.

**Comment by CocoDico78** [comment]
Note that my workaround at the moment is to pre-run a `dotnet publish` command by customising the prebuild/build script. The second one (the real one) then succeeds.

**Comment by StingyJack** [comment]
@javiercn - what author feedback is it that you need?   Does the author even know that the issue has been moved to here?   

I still get this error with RC2, but not as frequently. Try using the visual studio extension I mentioned in the above post for a few days with RC1 and a solution with at least an assembly project, a web api project, a console app,  and a unit test project all using netcoreapp31. Most of the time it will work, but when it gets stuck the only thing that I have found to fix it most of the time is to start debugging that extension's project to load my solution up and run the coverage in the experimental instance of VS.  I dont know if that makes .net use some safemode or something but I remember the console windows had slightly different output in the experimental instance.

**Comment by ejsealms** [comment]
@javiercn It looks like someone above added a minimal repo - please take a look! This is still an issue!

**Comment by ejsealms** [comment]
Here's what worked for me: 
1. Delete the 'out' folder
2. Clean solution
3. Build solution

Hopefully that works for others too.

**Comment by jsheetzati** [comment]
We are running into this same issue when using the NET6 SDK to build our NET5 application

**Comment by BobbyTable** [comment]
Arrived here from getting this error when trying to publish a core3.1 application after having installed net6. **Clean solution, build solution** solved it. Hope it helps others googling
