### ISSUE TITLE
visual studio publish aspnet core writes in output window it is release but built instead debug !?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35346]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/visual-studio-publish-aspnet-core-writes/1502100)._

---
[severity:It's more difficult to complete my work]
Visual Studio 16.11.0
aspnet core - dotnet 5
Windows 10

I have a dependency for debug only in csproj:

<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.6" Condition="'$(Configuration)' == 'Debug'" />

Now sometimes it actually publishes in debug mode although already configured publish for release mode (especially in the first publish after starting visual studio, subsequents publishes has no issue)

```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DeleteExistingFiles>False</DeleteExistingFiles>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>x64</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>bin\Release\net5.0\publish\</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <SiteUrlToLaunchAfterPublish />
    <TargetFramework>net5.0</TargetFramework>
    <ProjectGuid>05947f62-3bf0-4f4c-b151-b548f6f1d25c</ProjectGuid>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
</Project>
```

after publishing to iis, logs got like

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at MyProj.Web.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0. <Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0. <Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0. <UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at QudraMgmnt.Web.Program.Main(String[] args)
```

My Startup file line which has the issue:

```
public void ConfigureServices(IServiceCollection services)
        {
#if DEBUG
            if (Env.IsDevelopment())
            {
                mvcBuilder.AddRazorRuntimeCompilation(); // <--- issue here, altought DEBUG code should not be enabled & development env besides
            }
#endif
        }
```

---
#### Feedback Bot on 8/13/2021, 02:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SteveSandersonMS** [comment]
Thanks for the report. We're unsure how to reproduce a problem here because we don't know exactly what steps you're using to publish.

Can you please provide exact repro steps?

**Comment by ibraheemalkilanny** [comment]
The steps to reproduce is to 
1. add a debug-only dependency 
  
       <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.6" Condition="'$(Configuration)' == 'Debug'" />

2. add publish profile like above
3. configure app in Startup.cs to use the debug dependency only if DEBUG directive is enabled, like above
4. go publish to iis, and try to browse the app. Make sure to enable std log to true in web.config to check log files
5. if the issue was not found, try to close VS2019 and restart it, make some code changes, and publish immediately then copy the changed app DLLs to iis publish directory (after stopping IIS, then after copying start it again)

**Comment by ibraheemalkilanny** [comment]
Same again (log file iis)

Error:
  An assembly specified in the application dependencies manifest (MyProj.Web.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Razor.Extensions', version: '5.0.6'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.Extensions.dll'

**Comment by pranavkm** [comment]
NuGet package references cannot reliably be made conditional on Configuration (there's only one project.assets.json that sits outside of Configuration specific directories). I would remove the conditionality there and see if it works. Here's some details on our recommended pattern for configuring runtime compilation in your apps for dev-only scenarios: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio#enable-runtime-compilation-in-an-existing-project-1
