### ISSUE TITLE
Blazor WebAssembly App does not build when referencing .NET Standard 2.0 assembly.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35349]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-App-does-not-build-wh/1500692)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Preview 2.1]
When referencing a .NET Standard 2.0 (this is the only option I have tried) assembly (versus Project Reference), I am not able to build the Project/Solution.
I have included the basic project, cleaned in order to keep the download small. Build the ClassLibrary first, then the BlazorApp.

---
#### Feedback Bot on 8/12/2021, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SteveSandersonMS** [comment]
Unfortunately we haven't received the repro project that is mentioned above. If you're able to repost it, preferably as a GitHub issue, we'd be happy to investigate.

**Comment by johnhmuller** [comment]
Hi, I have recreated the repro steps and attached the solution:

Create a new Blazor Web Application, do not build.  Add a .NET Standard 2.0 Class Library, building the latter (class library) only. Add a reference to the built output in the Blazor project and build - build fails.  Seems that the extension gets lost somewhere in the MSBuild machinery. I have also included a workaround in the project file - moving the HintPath directly into the Reference include section.

[BlazorApp.zip](https://github.com/dotnet/aspnetcore/files/6997845/BlazorApp.zip)

**Comment by pranavkm** [comment]
@johnhmuller could you share the repro app as a GitHub repo? Thanks!

**Comment by johnhmuller** [comment]
https://github.com/johnhmuller/blazorApp

**Comment by javiercn** [comment]
I've confirmed it's a bug.

It's an issue with how we choose the path to the file we are about to compress, we look at the original item spec expecting that its the path to an existing file.

**Comment by javiercn** [comment]
https://github.com/dotnet/sdk/pull/19873
