### ISSUE TITLE
Blazor Web Assembly hot reload is very unstable 

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#35352]
Hot reload is hit or miss for me, many times file watcher identifies changes but these changes aren't reflected in the browser.
I am currently using Dotnet preview 7 but have been facing this issue since dotnet 6 preview 5.

CSS or tailwind classes changes are also not reflected, I have to restart the application to see changes, it is a bit frustrating when you are working on the front-end of the app, I tried `hotReloadProfile`:`blazorwasm` but still, changes are not reflected in the browser.

Looks like there is some problem with the web socket connection.
Please prioritize this before RC1.
Thank You

```
Dotnet version: .net 6 p7
Tested on OS: Windows and Arch Linux
```

**Comment by Alikhll** [comment]
same here for wasm
.NET6 preview 7

watch : Hot reload enabled
however it's been working quite unexpected, highly likely I have to restart the process, I'd appreciate it if you could prioritize this particular issue

**Comment by pranavkm** [comment]
Thanks for the issue report. Unfortunately we had a last minute regression in the WASM runtime that crept in to our preview7 build that makes the experience unstable. We've resolved along with a couple other fixes that should make this a lot better in the rc1 release. Feel free to grab our nightly builds from https://github.com/dotnet/installer#installers-and-binaries and let us know if you continue seeing issues after you upgrade.
