### ISSUE TITLE
Wrong startup project in Blazor WASM ASP.NET Core Hosted template

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#35356]
In VS 2022 Preview 3 create Blazor WebAssembly ASP.NET Core Hosted application. Notice that **Client** is selected as startup project. Run the application. It will load, but you will see the problem described in this closed but unresolved issue https://github.com/dotnet/aspnetcore/issues/35290. Change startup project to **Server** and everything will work correctly.

**Comment by pranavkm** [comment]
@phenning do you know what version of VS this is fixed in?

**Comment by phenning** [comment]
Fixed for preview 4.
