### ISSUE TITLE
DynamicComponent does not implement IRefreshable

### ISSUE THREAD

**Issue by ngelotte** [dotnet/aspnetcore#35355]
### Describe the bug
The example and docs for DynamicComponent describe getting a reference that is cast to IRefreshable but IRefreshable does not seem to exist as an Interface and DynamicComponent does not implement it from what I can tell. 

### To Reproduce
In a .net 6 Preview 7 project past this code from the docs
<DynamicComponent Type="typeof(MyComponent)" @ref="dc" />

<button @onclick="Refresh">Refresh</button>

@code {
    DynamicComponent dc;
    Task Refresh()
    {
        return (dc.Instance as IRefreshable)?.Refresh();
    }
}

You will get a warning that IRefreshable cannot be found. 

Also, I searched in the entire dotnet organization on github and the one and only reference to IRefreshable is on the doc page for DynamicComponent. 

### Further technical details
- ASP.NET Core version: .net 6 Preview 7
- Include the output of `dotnet --info`
- .NET SDKs installed:
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Windows Visual Studio 2020 Preview 3

**Comment by pranavkm** [comment]
Can you point to doc that you're referring to?

**Comment by ngelotte** [comment]
Sure. It is here https://github.com/dotnet/AspNetCore.Docs/blob/5ca084268ece02f650e8ac1e6f415ccfcc6a5ad0/aspnetcore/blazor/components/dynamiccomponent.md
And was posted here as well. https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#new-dynamiccomponent-instance-property

**Comment by pranavkm** [comment]
That's an example of what one could do by accessing the instance created by `DynamicComponent`. It's not a type provided by the framework.

**Comment by ngelotte** [comment]
Ok That makes sense. I was able to implement my own interface and then cause an action on the currently loaded DynamicComponent. Thanks for your help.
