### ISSUE TITLE
Transparent backgrounds for Blazor Webview in WPF

### ISSUE THREAD

**Issue by kevinneitola** [dotnet/aspnetcore#35360]
I am creating an application that needs to live inside a transparent WPF window since the application provides additional information for the user as an overlay on top of other applications. Right now it is not possible to use BlazorWebView with a transparent background. 
Current behaviour is: WPF window is transparent/allows transparency, background set to transparent => background in BlazorWebView is white

The current workaround is to use electron to host the Blazor app inside a transparent window which I would like to avoid.

### Describe the solution you'd like
Please make it possible to display Blazor apps with a transparent background in BlazorWebView inside a WPF application.

### Additional context
This is a transparent WPF application hosting the Blazor app using BlazorWebView. The Blazor app also has a transparent background but gets displayed with a white background instead.

![image](https://user-images.githubusercontent.com/25182361/129489440-f9a5e4ee-b615-49d3-8257-1af67c41583e.png)

**Comment by Eilon** [comment]
Hi @kevinneitola this is a limitation of the WebView2 control in WPF apps, which you can upvote here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/356
