### ISSUE TITLE
Hotreload only triggers on css files in the css directory?

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#35377]
I have `wwwroot/styles` and `wwwroot/scripts`, css and js files in these directories does not trigger a reload/change. How can I include these directories?

**Comment by marcuslindblom** [comment]
I forgot to say that I'm using MVC in this project

**Comment by SteveSandersonMS** [comment]
Could you clarify if you're using VS or `dotnet watch` to get the hot reload feature? (They are implemented differently)

Also if you could share a minimal repro project that would help us to investigate. Thanks!

**Comment by marcuslindblom** [comment]
@SteveSandersonMS I'm using vs code and `dotnet watch`. I'll upload a minimal repo as soon as possible.

**Comment by marcuslindblom** [comment]
@SteveSandersonMS When I create a new MVC project I can not reproduce this. In my old project based on older project template it only works for files in the css folder or in the root. Do I need to change somehing in my old project when I upgrade to the preview version?

**Comment by marcuslindblom** [comment]
@SteveSandersonMS Ok, I figured it out. In my `csproj` I have this line
```xml
<ItemGroup>
    <Content Remove="wwwroot\styles\**" />
</ItemGroup>
```
I used this to remove the source css files when I create the deployment package. Is there another way to to this?

**Comment by SteveSandersonMS** [comment]
This sort of thing might be what you're looking for: https://github.com/dotnet/sdk/issues/7861#issuecomment-284512192
