### ISSUE TITLE
Feature request: strongly-typed route values in `a` tag-helpers

### ISSUE THREAD

**Issue by dharmatech** [dotnet/aspnetcore#35376]
# The Issue

The example project from the [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio) includes the following code:

```html
<a asp-page="./Index"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Students.PageIndex + 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @nextDisabled">
    Next
</a>
```

[Link](https://github.com/dotnet/AspNetCore.Docs/blob/0b70dd128fd79e92238dbede0092be22687f4e13/aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Index.cshtml#L81-L87) to those lines in the project.

The route parameter names:

```
asp-route-sortOrder="@Model.CurrentSort"
asp-route-pageIndex="@(Model.Students.PageIndex + 1)"
asp-route-currentFilter="@Model.CurrentFilter"
```

are not strongly-typed. I.e. there could be a typo in any of the names (`sortOrder`, `pageIndex`, `currentFilter`) and the project will compile and run however the program will not function as expected.

# Workaround - use `LinkGenerator.GetPathByAction`

This [stackoverflow post](https://stackoverflow.com/questions/63015808/type-safe-a-tag-helper) discusses one workaround for the issue. The example there has the following `a` tag-helper:

```html
    <a class="btn btn-block
       @(category == ViewBag.SelectedCategory 
           ? "btn-primary": "btn-outline-secondary")"
       asp-action="Index" asp-controller="Home"
       asp-route-category="@category"
       asp-route-productPage="1">
        @category
    </a>
```

It is rewritten in a more strongly-typed manner using `LinkGenerator.GetPathByAction` as follows:

```html
<a class="btn btn-block @(category == ViewBag.SelectedCategory ? "btn-primary" : "btn-outline-secondary")"
   href="@(
    _linkGenerator.GetPathByAction(
        nameof(HomeController.Index), 
        Regex.Replace(nameof(HomeController), "Controller$", String.Empty),
        new IndexParameters() 
        { 
            Category = category, 
            ProductPage = 1 
        }))">
    @category
</a>
```

This is more of a demonstration of what is theoretically possible in the form of a quick solution; it's not ideal for end users.

# Workaround - R4MVC

Another approach is to use [R4MVC](https://github.com/T4MVC/R4MVC).

Here's a [video demonstrating R4MVC](https://youtu.be/cFD9QOjEIxc).

Downsides to R4MVC:

- Still in pre-release
- Not built-in to ASP.NET Core

# Workaround - object for parameters

If we use a class to represent the parameters to `OnGetAsync`:

```csharp
public class OnGetAsyncParameters
{
    public SortOrder? SortOrder { get; set; }
    public string CurrentFilter { get; set; }
    public string SearchString { get; set; }
    public int? PageIndex { get; set; }
}
```

then instead of:

```html
<a asp-page="./Index"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Students.PageIndex + 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @nextDisabled">
    Next
</a>
```

we can use `asp-all-route-data` and generate a dictionary from an instance of `OnGetAsyncParameters`:

```html
<a asp-page="./Index"
   asp-all-route-data="to_dict(new OnGetAsyncParameters()
    {
        SortOrder = Model.CurrentSort,
        PageIndex = Model.Students.PageIndex + 1,
        CurrentFilter = Model.CurrentFilter
    })"
   class="btn btn-primary @nextDisabled">
    Next
</a>
```

[Link](https://github.com/dharmatech/ContosoUniversityRazorPages/blob/4254f4f57f0e980a7ca856457762ae7f99119137/Pages/Students/Index.cshtml#L100-L109)

where `to_dict` is the following utility function:

```csharp
Dictionary<string, string> to_dict(object obj)
{
    return obj
        .GetType()
        .GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public)
        .ToDictionary(
            prop => prop.Name,
            prop =>
            {
                var val = prop.GetValue(obj, null);

                return val == null ? "" : val.ToString();
            });
}
```

In this case, `OnGetAsync` is updated to accept `OnGetAsyncParameters`:

```csharp
public async Task OnGetAsync(OnGetAsyncParameters onGetAsyncParameters)
```

[Link](https://github.com/dharmatech/ContosoUniversityRazorPages/blob/4254f4f57f0e980a7ca856457762ae7f99119137/Pages/Students/Index.cshtml.cs#L49)

# Request

The request is for ASP.NET Core to have route parameters be more strongly-typed in `a` tag-helpers.

I understand that the priority may be low. I'd just like to request that it at least be on the roadmap. :-)

**Comment by michalsznajder** [comment]
Tag helpers are great but refactoring them is always a pain. Maybe source generators could be used here?

**Comment by dharmatech** [comment]
@michalsznajder 

Interestingly, this post from the .NET Blog:

[Introducing C# Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/)

suggests exactly that:

> Another capability Source Generators can offer is obviating the use of some “stringly-typed” APIs, such as how ASP.NET Core routing between controllers and razor pages work. With a Source Generator, routing can be strongly typed with the necessary strings being generated as a compile-time detail. This would reduce the amount of times a mistyped string literal leads to a request not hitting the correct controller.

**Comment by dharmatech** [comment]
@michalsznajder,

> Tag helpers are great but refactoring them is always a pain.

(I'll get off topic here a bit.)

Yup, this is true. As opposed to Razor syntax, I prefer systems like JSX which look like markup but actually expand into regular JavaScript code. I wish we had something like this in ASP.NET Core. Something like JSX (csx?) which simply expands into C#. This way the page description code is fully in C# and thus you have the full power of the language to perform whatever refactoring you'd like.

For this reason, I like:

https://github.com/giraffe-fsharp/Giraffe

You write your page code in straight F#. So very powerful refactoring. However, it's not as mature as ASP.NET Core. E.g. nothing like tag-helpers there.

**Comment by dharmatech** [comment]
As an aside, I've been exploring an approach to getting views that are fully type-safe by having everything expressed in C# instead of Razor syntax. Video I recorded demonstrating this approach:

https://youtu.be/PIfX-u27TLY

**Comment by michalsznajder** [comment]
I think this approach goes a little bit too far for me. I am into type-safe tag helpers not complete overhaul of whole Razor.

Maybe first step would be some extension of IHtmlHelper? Tag helpers use internally IHtmlHelper.

**Comment by dharmatech** [comment]
@michalsznajder,

> I think this approach goes a little bit too far for me. I am into type-safe tag helpers not complete overhaul of whole Razor.

Oh, I completely understand that such a radical approach may not be feasible for some folks. :-) Was just showing an approach I've been exploring to work around the lack of type-safety.
