### ISSUE TITLE
[Help] How to disable Hot Reload for ASP.NET Core projects.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#35387]
I would like to disable Hot Reload for ASP.NET Core and Blazor projects in **Visual Studio 2022 preview 3** as it is not working as expected.

Whenever I am making any changes in ASP.NET Core and Blazor projects, it showing the following irritating pop up although there is no error.

![HotReload](https://user-images.githubusercontent.com/14342773/129587313-5a6467ed-5599-4dd3-a2fd-93b26b389b7f.PNG)

I have tried opting out the Hot Reload from the following settings but it's not helping anyway.

![HotReload2](https://user-images.githubusercontent.com/14342773/129587510-7c0b3959-ad38-475e-a3b6-85081a2cfeb4.PNG)

Any help will be highly appreciated.

Thanks in advance.

**Comment by davidfowl** [comment]
cc @pranavkm @vijayrkn @BillHiebert

**Comment by SteveSandersonMS** [comment]
@TanvirArjel Since this is about VS, would you please be able to file a VS feedback issue describing this? I know that's a bit inconvenient but it means all the info will be in the right place.

**Comment by TanvirArjel** [comment]
@SteveSandersonMS I have done this. Here it is: https://developercommunity.visualstudio.com/t/How-to-disable-Hot-Reload-for-ASPNET-Co/1506697
