### ISSUE TITLE
Feature request: Commenting out parameters in Razor

### ISSUE THREAD

**Issue by Luk164** [dotnet/aspnetcore#35383]
### Is your feature request related to a problem? Please describe.
Sometimes I want to comment out a single parameter out of an element, but that is not currently possible.

### Describe the solution you'd like
An ability to comment out parameters in razor templates like this:

```
<Slider
        TValue="short" 
        Value="10" 
        Max="100" 
        @* ReadOnly *@
/>
```
This would also allow to put any other comment inside an element, something I am sure others may find useful as well.

### Additional context
I think this would be useful to have, nothing more.

**Comment by TanayParikh** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/15439
