### ISSUE TITLE
Basic Keypresses in Regular (non-Razor) Files Invokes `RazorSourceGenerator` Which Consume 10% of CPU for Nearly 1 Minute

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#35389]
### Visual Studio Windows

This issue was originally reported here:
https://developercommunity.visualstudio.com/t/Basic-Keypresses-in-Regular-non-Razor/1502318

But then closed as a duplicate for this issue:
https://developercommunity.visualstudio.com/t/RazorSourceGenerator-interferes-with-com/1501976

However, after reading the issue that it was closed for, I am not sure they are the same.  There is not a problem with interface/texteditor interference, but that the CPU is being consumed for an unexpected, extended amount of time.

The root issue appears to be that `RazorSourceGenerator` (and any source generator -- [JsonSourceGenerator being another](https://developercommunity.visualstudio.com/t/JsonSourceGenerator-Takes-Considerable-C/1502374)) will go through each and every file in the solution, even if it's not a Razor file.  For larger solutions, this takes an extended amount of time.

In any case, I wanted to make sure this was accurately captured here.  They are indeed found to be the same issue, please close this issue.

Thank you again for all your great work over there. 👍

**Comment by pranavkm** [comment]
@Mike-E-angelo any chance I could have you try the rc1 build of the SDK: https://github.com/dotnet/installer#installers-and-binaries? We made a smallish tweak last week that should cause the source generator to do less work.

**Comment by Mike-E-angelo** [comment]
Woohoo!  Thank you so much @pranavkm !  It does indeed act exactly as I expect now.  It takes about 15 seconds to idle down now but that's about normal for Visual Studio.  I'd like to see that get even better over time, but I'm OK with this for now.  **FAR** much better than a full 60 seconds as it was.

Thank you again for all your efforts over there. 👍
