### ISSUE TITLE
`Microsoft.AspNetCore.Razor.Language.DefaultBoundAttributeDescriptor` Consumes Large Amounts of Memory

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#35380]
### Visual Studio Windows

This issue was first reported with #35199 but it appears to continue with Visual Studio 2022 Preview 3.0.

I have filed a DMP/issue on developercommunity here:
https://developercommunity.visualstudio.com/t/razor-development-microsoftaspnetcorerazorlanguage/1504791

Expected:  When all Razor documents are closed and a `ForceGC` is performed on Visual Studio, memory used for Razor development is released.

Currently, I have to assign my Hyper-V instance to 32GB allocated RAM to avoid constant GC sweeps.  Even then, I am still encountering intermittent IDE freezes due to GC time.

For a little context, here is what my task manager looks like after an hour or so of development:

![](https://i.imgur.com/wic8Pgx.png)

As I mention in my developercommunity ticket, the RAM utilization actually appears to drop after time, from ~23GB to ~15GB.  However, `Microsoft.AspNetCore.Razor.Language.DefaultBoundAttributeDescriptor` utilization actually _increases_ from 1.35GB to 1.4GB during this same amount of time.

This is with no Razor files opened during this time, and after several ForceGC's applied to the IDE.

**Comment by pranavkm** [comment]
@Mike-E-angelo could I have you try out the rc1 build of the SDK - https://github.com/dotnet/installer#installers-and-binaries? It should be an in-place replacement. We made a some tweaks to the source generator that we think might help.

**Comment by Mike-E-angelo** [comment]
@pranavkm thank you for that.  I have been noticing the memory does seem better.  Thank you so much again for fixing this.

However, unfortunately, I am now running into a problem with rc1 where the all the `csproj` in my solution are building no matter what, leading to full builds with each attempt.  


```
========== Build: 128 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Do you know if this is a known issue and/or where would be the best place to report this?

**Comment by Mike-E-angelo** [comment]
Nevermind @pranavkm I got it:
https://github.com/dotnet/sdk/issues/19758

My SLN opened to 2-3GB instead of the typical 8-10GB.  That is a great start.  I am going to close this issue and mark it as resolved and will revisit/reopen if there is still and issue here.

I cannot convey how appreciative I am to see this addressed.  It feels like a 10-month weight lifted from my psyche. :)  Thanks again for your time/attention towards this.

**Comment by pranavkm** [comment]
You can have VS log the results of up-to-date check by changing this -
![image](https://user-images.githubusercontent.com/174281/129617902-24161ddf-b504-4748-b6a0-21dd216091c9.png). It should tell you why it decided to invalidate previous build results in the Output window. 

If you're using a hot off the press build of the installer, there's a chance that you're using a _sdk from the future_. The installer stamps the CI's local build times (without timezones) which might be newer than your dev machine's time. This breaks MSBuild / uptodate check incrementalism until your local dev time catches up or if you manually tweak the SDK files on disk. e..g

![image](https://user-images.githubusercontent.com/174281/129618624-6c6aae60-8d52-4ced-9481-04e7e414bd0b.png)

**Comment by Mike-E-angelo** [comment]
Thank you for providing that, @pranavkm!  That is valuable information.  I was not aware of that setting and was using the `Detailed` build output under `Solutions and Projects Run and Build` and did not see anything apparent.

I also then tried closing the SLN and running it direct from CLI.  The problem persisted there, too.  It was not until I ran `dotnet clean` from the CLI was I able to get incremental builds again.

So, there appears to have been some errant state from the previous SDK and/or vice versa that was keeping this from working as expected.

Usually what I do when things get funky in my IDE is `dotnet restore --force`.  Now I know about `dotnet clean` and will be using that, too.

Thanks again for your assistance. 👍

**Comment by Mike-E-angelo** [comment]
Doh, wrong button.  So many problems today. 😆😭

**Comment by Mike-E-angelo** [comment]
This does indeed appear to be addressed in rc1:

![](https://i.imgur.com/HJw9tcJ.png)

It feels so much better now, too.  I am not having to close/restart my IDE every hour or so due to constant GC sweeps.  Feels like a whole new application now.  NICE WORK OUT THERE @pranavkm. 

You even provided some spectacular tech support when you didn't have to.  

https://youtu.be/t2cQWCPDBC0

😁

Totally above and beyond there.  Much appreciation. 👍
