### ISSUE TITLE
AspNetCore.Mvc.NewtonsoftJson affects AspNetCore.SignalR.Core

### ISSUE THREAD

**Issue by DenisBabarykin** [dotnet/aspnetcore#35386]
### Problem
Microsoft.AspNetCore.Mvc.NewtonsoftJson package affects Microsoft.AspNetCore.SignalR.Core in an unobvious way. Apparantley, it enhances SignalR version from 1.1.0 (03.12.2018) to 5.0.0 (10.08.2021). For example, there is no support of nullable reference types feature in latest Microsoft.AspNetCore.SignalR package version (1.1.0). But after installing Microsoft.AspNetCore.Mvc.NewtonsoftJson (5.0.9) this feature becomes available.

### To Reproduce
Let's decompile class Hub from Microsoft.AspNetCore.SignalR with Resharper and JetBrains decompiler.

1. After installing latest Microsoft.AspNetCore.SignalR.Core nuget package of version 1.1.0
![изображение](https://user-images.githubusercontent.com/10895923/129582474-7ab5e170-8825-419a-aef4-ca07d0baf2ab.png)
![изображение](https://user-images.githubusercontent.com/10895923/129582763-a88738db-ba1d-4551-822e-327ec82c6c9c.png)

2. After removing package Microsoft.AspNetCore.SignalR.Core of version 1.1.0 and installing Microsoft.AspNetCore.Mvc.NewtonsoftJson of version 5.0.9
![изображение](https://user-images.githubusercontent.com/10895923/129582526-112b636a-f778-40a0-855c-d661c5899831.png)
![изображение](https://user-images.githubusercontent.com/10895923/129583848-595aab9b-e8f7-4b77-aa9d-be02cbb8de73.png)

**Comment by davidfowl** [comment]
Maybe because **Microsoft.AspNetCore.Mvc.NewtonsoftJson** depends on the ASP.NET Core 5.0 shared framework:

![image](https://user-images.githubusercontent.com/95136/129585516-a17f83f1-ed14-4c3e-862b-188ec2af5f49.png)

It doesn't just affect SignalR, it upgrades your entire app to use .NET 5.0's ASP.NET Core shared framework.
