### ISSUE TITLE
dotnet watch stomps over existing hosting startup assemblies

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35410]
This is a regression on 6.0 that affects the ability for apps to provide their own hosting startup assemblies:
```csharp
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=$Microsoft.AspNetCore.Watch.BrowserRefresh
```

When hosting startup assemblies are defined in launchSettings.json (as the SPA templates do) they get stomped over.

**Comment by javiercn** [comment]
@pranavkm can you help out here?

I discovered this issue as part of investigating https://github.com/dotnet/aspnetcore/issues/34925 and it's breaking dotnet-watch + SPA

**Comment by davidfowl** [comment]
Seems like a VS problem right?

**Comment by javiercn** [comment]
Why do you think it's VS, this happens on the command-line when you run dotnet-watch, VS is not involved in the picture

**Comment by davidfowl** [comment]
Ok so it's just the dotnet watch but VS works?

**Comment by javiercn** [comment]
Yep
