### ISSUE TITLE
BrotliCompress failing on some builds

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35411]
Not sure what's going on here, however it seems brotlicompress is failing on some builds
##[error].dotnet\sdk\6.0.100-rc.1.21415.3\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(642,5): error MSB6006: (NETCORE_ENGINEERING_TELEMETRY=Build) "D:\workspace\_work\1\s\.dotnet" exited with code 1.
https://github.com/dotnet/aspnetcore/pull/35408/checks?check_run_id=3349401233

We should at least add more logging to try and determine what's going on here.

**Comment by pranavkm** [comment]
The suggestion is to add additional logging to the executable to help with figuring out what's happening here.

**Comment by javiercn** [comment]
This was done in https://github.com/dotnet/sdk/pull/19873

**Comment by javiercn** [comment]
Will re-open the issue if we see more failures moving forward, these failures are usually a symptom of issues elsewhere and not a bug in this code-path itself.
