### ISSUE TITLE
[SignalR] IUserIdProvider's GetUserId has no async option

### ISSUE THREAD

**Issue by MichaelTontchev** [dotnet/aspnetcore#35417]
Related to https://stackoverflow.com/questions/68332358/how-to-implement-async-iuseridprovider-for-signalr

I'd like to implement an async IUserIdProvider since my method of getting a user id based on the incoming hub request is async. I take the request cookies and look up session data in my Cosmos DB. Unfortunately, there is no async version of GetUserId.

I have a PR ready to add the async version to the interface, with a default implementation that just calls the existing GetUserId. If approved, in the next major API version we can remove the non-async method in favor of just the async one.

Is this fine?

**Comment by BrennanConroy** [comment]
> my method of getting a user id based on the incoming hub request is async. I take the request cookies and look up session data in my Cosmos DB

This sounds like something that should be done once at the start of the connection. Using a custom auth handler or middleware that runs before SignalR are perfect for this.

It doesn't seem like something we should be adding to `IUserIdProvider`.

**Comment by 2932** [comment]
Madarcod toke cudbo

**Comment by MichaelTontchev** [comment]
> This sounds like something that should be done once at the start of the connection. Using a custom auth handler or middleware that runs before SignalR are perfect for this.

The problem is that I tried the middleware approach and got stuck.

I have a user session provider middleware that calls a scoped class that gets/verifies the user session and stores it internally for later retrieval within the session. The problem is that IUserIdProvider is defined as a singleton, so it doesn't have access to the scoped class that got and stored the session.
