### ISSUE TITLE
[Feature] Allow multiple file uploads with their own submit buttons

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#35413]
On allot of projects it becomes frustrating that one must have multiple file uploads on different form handlers in asp.net page or razor page.

Provide some in built way of allowing multiple file uploads within one submit button / razor page.

At present 

We declare a file input tag as such in the likes of php we could have many forms with a fileupload in the same page but .net still only allows one form.

     <form action="/action_page.php">
       <input type="file" id="myFile" name="filename">
       <input type="submit">
      </form> 
Expected
Allow multiple forms in the one asp.net core page / razor view that can be sent to  IFORMSCollection or something simlar to upload multiple files for different areas of a main form.

Api Changes

     <input type="file" name="ImageFile" required  SubmitEvent="submitEventUpload" 
        SubmitText='Upload Documents'/>

**Comment by DamianEdwards** [comment]
I'm not quite understanding what it is you're asking for here.  The file upload features in ASP.NET Core are based on what HTTP and browsers themselves support, i.e. multiple form fields, any number of which can be file uploads, that are POSTed to a single form handler (in ASP.NET Core that's usually a `PageModel` handler method or a `Controller` action method).

The `<input type="file" />` element doesn't support direct submission as far as I know. It is contained in a `<form>` element and gets submitted along with the other fields in the form when the form is submitted.

**Comment by davidbuckleyni** [comment]
Then maybe the file element needs a re think.

**Comment by pranavkm** [comment]
Thanks for your feedback. We're not sure there's anything actionable for us since we're following browser standards here.
