### ISSUE TITLE
Kestrel Support for Kerberos

### ISSUE THREAD

**Issue by mcarbonneaux** [dotnet/aspnetcore#35415]
Whould be very interesting to support kerberos authentification on linux and macos support for kerberos on kestrel self hosted http service in dotnet.

**Comment by blowdart** [comment]
It's [already there](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#kestrel)

**Comment by mcarbonneaux** [comment]
thank's ! i've not found it !

**Comment by blowdart** [comment]
Oh dear, we can hopefully improve any search results. How were you looking for it?

**Comment by mcarbonneaux** [comment]
i found the old repository with issue that explaint that you not whan to implement it....
