### ISSUE TITLE
Using Filters in SignalR to validate resources 

### ISSUE THREAD

**Issue by oriches** [dotnet/aspnetcore#35420]
Is this the only way to terminate a request from within a hub filter - throwing an exception?

```
public sealed class ValidateResourceFilter : IHubFilter
{
    public ValueTask<object> InvokeMethodAsync(HubInvocationContext invocationContext,
        Func<HubInvocationContext, ValueTask<object>> next)
    {
        // do some validation of invocationContext.HubMethodArguments
        throw new BadHttpRequestException("Foo resource is invalid!", (int)HttpStatusCode.UnprocessableEntity);
    }
}
```

The client does not recieve the status code in the propergated exception, I am not seeing it in the logs.

Or should I change my thinking and not concern myself with status codes, and just throw an exception - typeof(Exception)....

SignalR (ASp.Net Core) is running in a console app (.Net 5) hosted using Kestrel.

**Sever**
ASP.Net Core version 5.0,
Hosted in Kestrel in a .Net 5.0 console app.

**Client**
.Net framework 4.6.1,
WPF application,

VS 2019 (16.10.3)

**Comment by BrennanConroy** [comment]
> Is this the only way to terminate a request from within a hub filter

No, you can also call `invocationContext.Context.Abort();`

> The client does not recieve the status code in the propergated exception, I am not seeing it in the logs.

Exception messages are not returned to the client by default, you either need to throw a HubException, or set `EnabledDetailedErrors` on the server. https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=dotnet#configure-server-options-1

**Comment by oriches** [comment]
Thanks
