### ISSUE TITLE
Create 6.0 SiteExtensions package

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#35430]
We have 3.1 and 5.0 SiteExtensions packages which we reference from the 6.0 branch:

https://github.com/dotnet/aspnetcore/blob/cddec67ccb41c795740f17e3394bcc7b7e48d59e/src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L33-L36

We probably need a 6.0 package as well, which we'd reference from the 7.0 branch. We should figure this out & produce it by the time 6.0 RTMs.

**Comment by dougbu** [comment]
Given the layout of the bundle, this can't be fixed until we target the `net7.0` TFM.

Fix here is pretty simple. Just add a few new lines in Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj and eng/Versions.props. We'll eventually also need to bump the package versions from 6.0 in the same (regular) way we do for 3.1 and 5.0 SiteExtension packages.

----

This may also be a good place to talk about _removing_ the 2.1 SiteExtension package from the bundle. `netcoreapp2.1` is at EOL tomorrow. On the other hand, I see `netcoreapp2.2` bits in the recent 5.0.9 bundle. The second bit may be a bug in
- https://github.com/dotnet/aspnetcore/blob/release/3.1/src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L28
- https://github.com/dotnet/aspnetcore/blob/release/5.0/src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L33

@BrennanConroy @Pilchie @glennc, thoughts on 2.1 and 2.2 removals from our bundles❔

**Comment by dougbu** [comment]
This should be complete. Please reopen if we're forgetting something.
