### ISSUE TITLE
Fix minimal APIs behavior with duplicate endpoint and route names

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#35436]
By default, endpoint names must be global within an application.

MVC currently checks for duplicate endpoint names in the `EndpointNameAddressScheme` which maintains a cache that when hit, will run through all the declared endpoint names and throw if any errors are encountered.

https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/EndpointNameAddressScheme.cs#L38-L41

So, if a user has an application with duplicate endpoint names invoked, the application will through when one of the endpoints is hit (not at startup because the check only happens when the cache is initialized).

The same validations don't happen in minimal APIs because we don't execute any endpoints that invoke the cache initialization path.

**Comment by captainsafia** [comment]
> The same validations don't happen in minimal APIs because we don't execute any endpoints that invoke the cache initialization path.

@DamianEdwards forced this codepath to happen by calling the `GetUriByName` method

```
app.MapGet("/bar", () => "foo").WithName("Foo");
app.MapGet("/foo", (HttpContext context, LinkGenerator links) => links.GetUriByName(context, "foo", null)).WithName("Foo");
```

**Comment by DamianEdwards** [comment]
@captainsafia from my testing yesterday I think we discovered that MVC doesn't actually force that specific check at startup, but it has another check as part of building the action descriptors at startup that catches a slightly difference (but related) case when there are duplicate route names with different patterns. So as far as endpoint naming goes, MVC and Minimal are the same right now.

**Comment by captainsafia** [comment]
> So as far as endpoint naming goes, MVC and Minimal are the same right now.

Yep, both minimal and MVC do not do any checks for duplicate endpoint names in the startup path. As you mentioned though, the behavior is worse for minimal because we don't do the same duplicate route name check MVC does (which masks the underlying duplicate endpoint name issue since route names are mapped to endpoint names in MVC). The behavior currently looks like this:

| scenario | duplicate route name | duplicate endpoint name |
|--|--|--|
| minimal | exception when visiting a route | no exception |
| mvc | exception at startup | no exception because exception at startup masks it |

the semantics of minimal are a little different but I think the right approach here is to thrown an exception at startup for both scenarios -- eg. warn early and often.

**Comment by davidfowl** [comment]
I think it would be fine to do it [here](https://github.com/dotnet/aspnetcore/blob/39b54a3785bc69acb521cb0e96421074b19ea9e5/src/Http/Routing/src/ModelEndpointDataSource.cs#L22). It would only affect endpoints directly added to the builder which is fine. Custom data sources can do their own checks.
