### ISSUE TITLE
Styling issues in identity UI

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#35446]
As part of the migration to Bootstrap 5, we should expect there to be a few minor styling issues left over. Here are ones I've noticed while looking into the reported accessibility issues.

## Repro steps

Using SDK 6.0.0-rc.1.21409.9 and VS 17.0.0 Preview 4.0 [31609.369.main], I created an ASP.NET Core C# MVC project with Individual Accounts auth. After registering a user and confirming email, logging back in, and going to the user profile pages, the following apply.

---

### 1. Unstyled "close" button in "thankyou for confirming your email"

I don't know what it's meant to look like, but presumably not this grey box:

![image](https://user-images.githubusercontent.com/1101362/129871047-40483bcb-351a-4f0e-a06d-b19ceb94428a.png)

---

### 2. Missing space form submission buttons

The "Save"/"Confirm"/etc buttons shouldn't be right up against the text boxes:

![image](https://user-images.githubusercontent.com/1101362/129871386-4ef64058-e063-4087-856f-3273bee83374.png)
![image](https://user-images.githubusercontent.com/1101362/129871423-e806c2af-7fec-47b9-968b-e1a1cbd952ad.png)
![image](https://user-images.githubusercontent.com/1101362/129871450-b8a6225a-11bd-47d7-b313-276477c016e7.png)

---

### 3. Strange button layout on "personal data"

Should these both be on the same line? Should the "Delete" button really have a grey background (I would have thought red)? 

![image](https://user-images.githubusercontent.com/1101362/129871604-93d2fc2f-0f90-404c-856c-381cf08e2c38.png)

---

### 4. Extra blank space inside confirmation prompt

It doesn't look like the extra blank line should be there:

![image](https://user-images.githubusercontent.com/1101362/129871722-67c63801-ca6b-46bf-8513-60f24291c1af.png)

**Comment by SteveSandersonMS** [comment]
Also I tried the Angular project template, and the Identity UI in it has the following:

### A1. Weird close button on prompt

For some reason there are two overlapping X symbols:

![image](https://user-images.githubusercontent.com/1101362/129874062-da91600a-9d96-4cc4-99f0-e8ab11a04d7d.png)

**Comment by blowdart** [comment]
@HaoK is aware of some of these, we choose to get bootstrap 5.1 in place, and do more fit and finish after that was integrated,

**Comment by SteveSandersonMS** [comment]
Cool - feel free to close this if it's not useful - I was just keeping a record of what I saw in case it was unknown.

**Comment by blowdart** [comment]
Naw, we'll keep it, makes it easier to go through everything again :)
