### ISSUE TITLE
[Blazor] Discuss alternatives to change detection

### ISSUE THREAD

**Issue by devel112** [dotnet/aspnetcore#35447]
## Summary

Don't look for changes, compile the application to do only the changes needed! Since all references are accounted for this should be possible in theory?

Like [Svelte](https://svelte.dev/)

> Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app. Instead of using techniques like virtual DOM diffing, Svelte writes code that surgically updates the DOM when the state of your app changes.

## Motivation and goals

- Massive performance gains
- Less time spent optimizing the change detection algo
- Blazors don't need to work around poor change detection performance

## In scope

Philosophize and map out the best possible solution instead of grandfathering in concepts from the node frontend frameworks.

## Out of scope

...

## Risks / unknowns

Interoperbility with 3rd party JS libraries? 

## Examples

[Svelte](https://svelte.dev/)

#21085
#25356
#22432

**Comment by SteveSandersonMS** [comment]
Thanks for posting. I have no doubt this is a well intentioned post, but as it is, this suggestion is much too broad and open-ended for us to take any action on. I'm aware that other frameworks work in different ways, but we have made many tradeoffs to achieve a particular developer experience that fits in with .NET norms and existing libraries. Hopefully, Blazor is already flexible enough that if you're able to implement the change detection mechanism you want, you would be able to trigger rendering at only the times you want (note: components only need to implement `IComponent` which is agnostic to any particular change detection and rerendering strategy). 

If you're in a position to create a prototype of what you're looking for, I suspect many people would be interested.
