### ISSUE TITLE
Do not reload the same data .razor

### ISSUE THREAD

**Issue by doanhquang2005** [dotnet/aspnetcore#35445]
![image](https://user-images.githubusercontent.com/30622119/129870480-38f37360-e45f-450d-8e2c-c4d9a794874a.png)
When on page "/topic/1" and click on page "/topic/2", the page data does not change:
![image](https://user-images.githubusercontent.com/30622119/129870842-eef4389d-a1b3-4016-8620-ba95b889bbe0.png)
If change OnInitializedAsync to OnParametersSetAsync:
![image](https://user-images.githubusercontent.com/30622119/129872451-5436148a-d2f6-40b6-bbe4-c85bd2db5d46.png)
Will get the following error:
![image](https://user-images.githubusercontent.com/30622119/129872608-4197e391-7adc-4dcf-8dc0-23e4b6fda702.png)

**Comment by javiercn** [comment]
@doanhquang2005 thanks for contacting us.

Seems like you are running EF queries concurrently in your blazor application, which is not supported. For best practices using entity framework and Blazor check out [this doc](https://docs.microsoft.com/es-es/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
