### ISSUE TITLE
Feature request: Expose IsActive on NavLink.

### ISSUE THREAD

**Issue by rlindneresa** [dotnet/aspnetcore#35456]
## Background and Motivation

In order to set active class on an navigation list item it would be incredible usefull if we could access the match-result of the NavLink Component in a TwoWay bindable (is there something like OneWayToSource?) or maybe an IsActiveChanged Event.

## Proposed API
```c#
[Parameter]
public bool IsActive { get; set; }
```

## Usage Examples
```html
<li class="@(IsNavLinkActive? "active" : "")">
    <NavLink @bind-IsActive="IsNavLinkActive" />
</li>
```

**Comment by pranavkm** [comment]
Thanks for the issue. We think the matching behavior is easily reproducible in your app by using `string.Equals` / `string.StartsWith` and don't think it's a good idea to add additional parameters (and cause an additional re-render) to support this scenario. Closing this as we do not plan on making this change.
