### ISSUE TITLE
Blazor WASM: Upgrading to .NET 6 preview 7 breaks localization

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspnetcore#35459]
### Describe the bug
I've been building out a Blazor WebAssembly application that uses localization. It was working with .NET 6 preview 6, but since upgrading to .NET preview 7 — it has stopped working. Here is my commit with the updates: https://github.com/IEvangelist/learning-blazor/commit/cd60ac796257a5f882008e6a4f3f4ee81d06eed9.

### To Reproduce

- Create a simple Blazor WebAssembly project targeting .NET 6 preview 6.
- Add localization support and verify that it functions correctly, i.e.; change the locale observe the UI respect the change and see localized content.
- Upgrade the project to .NET 6 preview 7.
- Run the app again, and see that it's broken

### Further technical details
- **ASP.NET Core version**

> .NET 6 preview 7

- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  2.1.817 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- **The IDE**

> Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
> Version 17.0.0 Preview 3.1

**Comment by IEvangelist** [comment]
Any updates on this? I started putting together two sample apps that demonstrate it working in .NET 6 preview 6 and then the same code failing to localize in .NET 6 preview 7 but ran into issues with side-by-side preview collisions.

**Comment by SteveSandersonMS** [comment]
It's in the RC2 milestone so we plan to look at it during the next 2 weeks.

**Comment by IEvangelist** [comment]
Here is a repo with both projects in it:

https://github.com/IEvangelist/blazor-localization-bug

**_With .NET 6.0.100-preview.6.21355.2_**

Counter page with hardcoded `"en"` locale (and click me button and current count text are localized):
![image](https://user-images.githubusercontent.com/7679720/131735750-0e20f608-a909-47ce-81bd-57994477802e.png)

Counter page with hardcoded `"es"` locale (and click me button and current count text are localized):
![image](https://user-images.githubusercontent.com/7679720/131735563-ac68591e-2ece-47b0-a2b9-5e86992a48d0.png)

**_With .NET 6.0.100-preview.7.21379.14_**

Counter page with hardcoded `"en"` locale (and click me button and current count text are localized):
![image](https://user-images.githubusercontent.com/7679720/131738961-189eed10-95ae-4612-b374-d0cb38e73338.png)

Counter page with hardcoded `"es"` locale (and click me button and current count text are localized):
![image](https://user-images.githubusercontent.com/7679720/131738761-088052f4-f9bc-4cf3-97b1-9220e41aee15.png)

**Comment by SteveSandersonMS** [comment]
@IEvangelist I investigated and tracked this down to a bug in the .NET Core SDK, whereby if you use file-scoped namespaces, it no longer generates the correct resource names: https://github.com/dotnet/msbuild/issues/6828

Until this is fixed, a workaround is to change your `Counter.razor.cs` file contents from this:

```cs
namespace DotNetSixPreviewSeven.Pages;
public partial class Counter { }
```

to this:

```cs
namespace DotNetSixPreviewSeven.Pages
{
    public partial class Counter { }
}
```

Alternatively, delete the `Counter.razor.cs` file completely and rename your resources to `Counter.en.resx`/`Counter.es.resx`. I know it won't nest as nicely in VS if you do that, but it's another option.

I'm going to close this as external because it's entirely down to https://github.com/dotnet/msbuild/issues/6828 and not related to anything in the ASP.NET Core repo. Thanks for reporting it!
