### ISSUE TITLE
Publish nightly builds to an LKG location

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#35457]
Runtime & Installer both do this:

https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#nightly-builds-table
https://github.com/dotnet/installer#installers-and-binaries

We should also provide some aka.ms link that points to our latest nightly bits.

Related: https://github.com/dotnet/installer/pull/11568.

CC @dotnet/aspnet-build

**Comment by danmoseley** [comment]
Note without this the nightly DEB files linked from the installer repo are not useable - the package manager won't install them. As the page says,

> Our Debian packages are put together slightly differently than the other OS specific installers. Instead of combining everything, we have separate component packages that depend on each other. If you're installing the SDK from the .deb file (via dpkg or similar), then you'll need to install the corresponding dependencies first:
Host, Host FX Resolver, and Shared Framework
ASP.NET Core Shared Framework

If we don't begin publishing these, we should remove the nightly links from that page.

(As an aside, it would be nice if it wasn't necessary to curl and apt-get install each of 9 packages separately.)

**Comment by dougbu** [comment]
What exactly is involved in fixing this @wtgodbe❔

**Comment by wtgodbe** [comment]
I don't know, I haven't looked into it yet. I remember that Installer used to have a manual "Copy to latest" step, not sure if they still do, or if there's a built-in Arcade way to do it.

**Comment by danmoseley** [comment]
@marcpopMSFT have we considered, or does there exist, a script to make it easier to install a nightly build on Debian? Even after this is fixed so it's possible to do, it still requires curl/apt-get install of ~9 different URL's.

**Comment by marcpopMSFT** [comment]
@danmoseley I don't think we've put much focus on nightly builds on all platforms. The installer repo does produce .deb packages on aka.ms links: https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-x64.deb.  Not sure if the install scripts work.

**Comment by danmoseley** [comment]
@marcpopMSFT yup, that link is exactly how I got here. It's not possible to install that DEB. Hopefully they fix that (here) but then it would still involve 9 downloads and 18 commands. Not an urgent issue, just ease of use.
