### ISSUE TITLE
[Templates] Readme file included when no auth is used

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35462]
![image](https://user-images.githubusercontent.com/6995051/129939294-2c54a6ef-b76b-48ce-8606-b74f7990bd93.png)

This gets added even when Identity Server is not part of the app.

**Comment by HaoK** [comment]
@phenning hrm this is weird, I confirmed this to be the case too, running `dotnet new blazorwasm -ho` so `--auth Individual` was not specified.  I do see if `-ho` is skipped, the file is not dropped

The file in template.json has an explicit check for Hosted and IndividualLocalAuth:

```
    {
      "condition": "(Hosted && IndividualLocalAuth && HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "Server/Readme.txt"
    },
```

**Comment by phenning** [comment]
That is just the definition of the primary output.

I think you want something like this in the source modifiers if you want to keep the file from being written at all, no?

        {
          "condition": "(!Hosted || !IndividualLocalAuth)",
          "exclude": [
            "Server/Readme.txt"
          ]
        },

**Comment by HaoK** [comment]
Ah, that makes sense, thanks
