### ISSUE TITLE
Grpc Service Not Working In Visual Studio 2022

### ISSUE THREAD

**Issue by silenuz** [dotnet/aspnetcore#35466]
I was trying to verify that my current code for a grpc service and client apps using Net 5, was going to be easily portable to Net 6 and if not, at least determine what issues I might face.

However after upgrading to Net 6, most client calls from the various apps result in an error. I decided to just go to the basics and see if I could figure out the problem with my code. I followed the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio) to create a Grpc service / client and it raises the same error my client apps raise.

To duplicate simply follow the page (https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio) instructions. Create the service from the template (Grpc-AspNetCore(2.38.0)) , and make no changes. Create console application, add Grpc.Net.Client (2.38.0), Google.Protobuf (3.17.3), and Grpc.Tools (2.39.1).

Here is my program.cs code:
```
using Grpc.Net.Client;
using GrpcService1Client;


Console.WriteLine("Hello, World!");

var data = new HelloRequest { Name = "Bruna Belle" };
var grpcChannel = GrpcChannel.ForAddress("https://localhost:5001");
var client = new Greeter.GreeterClient(grpcChannel);
var response = await client.SayHelloAsync(data);
Console.WriteLine(response.Message);
Console.ReadLine();
```

When it gets to:
`var response = await client.SayHelloAsync(data);`

It raises this exception:
Failed to deserialize response message.

Full detail:

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Failed to deserialize response message.")
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <Program>$.<<Main>$>d__0.MoveNext() in K:\Visual Studio 2022\GrpcService1\ConsoleApp1\Program.cs:line 13
```
Which is the same exception my client applications raise. I tried using GrpcUI with the data service and it also raises an error. Though the error is uninformative it just says:
Unexpected error: error

**Comment by adityamandaleeka** [comment]
Triage: this is a known issue in VS 2022 at the moment that's being fixed. Until then, you can work around it by adding this to your Program.cs:

```c#
Environment.SetEnvironmentVariable("ASPNETCORE_PREVENTHOSTINGSTARTUP", "true");
```

**Comment by silenuz** [comment]
Thanks.

**Comment by jose8789** [comment]
I have found the same issue if I set up my Visual Studio 2022 preview 4 to run "Multiple Startup Projects", one Gpc Service and Wpf Client.
Obs: The workaround given by @adityamandaleeka works
