### ISSUE TITLE
Blazor WebAssembly prerendered root component types may get trimmed away in the client build

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#35461]
When using prerendering in an ASP.NET Core-hosted Blazor WebAssembly project, root components are specified via component tag helpers in server-side CSHTML pages (instead of `WebAssemblyHostBuilder.RootComponents` in the client project). Consequentially, root component types not directly referenced in the client project get trimmed away, so those root components take no effect outside of prerendering.

This was the cause of #35363, but the same bug could be experienced using any third-party/Blazor-framework root component.

**Comment by pranavkm** [comment]
As part of fixing https://github.com/dotnet/aspnetcore/issues/35363, Blazor fails noisily. The suggestion is for us to document what the workaround is (use `DynamicDependency` in the user's Program.Main to preserve these types).

**Comment by SteveSandersonMS** [comment]
Documented at https://github.com/dotnet/AspNetCore.Docs/pull/24200

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/AspNetCore.Docs/pull/24200
