### ISSUE TITLE
Add support for custom model binders in minimal APIs

### ISSUE THREAD

**Issue by lomholdt** [dotnet/aspnetcore#35472]
### Is your feature request related to a problem? Please describe.
I am trying to use a custom model binder in the new minimal APIs but it does not seem that this is possible at the moment. 

In the controller based approach I could create a custom binder as such

```csharp
public class CustomBinder<TEvent> : IModelBinder { ... }

public class CustomBinderProvider : IModelBinderProvider { ... }
```

and register it in `Startup.ConfigureServices`

```csharp
services.AddControllers(options =>
{
    options.ModelBinderProviders.Insert(0, new CustomBinderProvider());
});
```

and then use it 

```csharp
[HttpPost("foo-endpoint")]
public IActionResult Post(Foo customType) => Ok();
```

Where the `CustomBinderProvider` would react to the `Foo` and use the `CustomBinder`.

### Describe the solution you'd like
Using a custom model binding in the minimal API setup so it's possible to do the same as described above, or achieve the same result. 

```csharp
app.MapPost("foo-endpoint", (Foo customType) => "ok");
```

**Comment by DamianEdwards** [comment]
We're tracking discussion of future support for customizing parameter binding in Minimal APIs in #35489
