### ISSUE TITLE
Weatherforecast runs into unhandeled error with new VS2022 Update

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#35477]
I updated my VS2022 Project to Version 17.0.0 Preview 3.1

I am creating new Blazor WASM Hosted PWA App.

This is basic template that is failing.

Here is the Project file
[Link to Source Code](https://1drv.ms/u/s!AtHk7h6Srnk_h9cvgdBvHdfgL0n6AA?e=TfMCkE)

![Blazor Wasm Hosted PWA](https://user-images.githubusercontent.com/3267605/129988153-ba37030e-3bcd-4a51-87b1-7c4cbd10250e.png)

SDKs installed

```
C:\Users\admin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

We'll take a look and get back to you. Please note for the future that we prefer repros be made available as github repos, it allows us to see the code directly and allows us to avoid having to download the code to an isolated environment for inspection.

**Comment by BrennanConroy** [comment]
Are you running the client project? There was an issue where VS was setting the client project as the default project to run when it was supposed to be the server project selected.

**Comment by pranavkm** [comment]
If it's the issue that @BrennanConroy is indicating, it should be fixed in 17.0 p4.

**Comment by nssidhu** [comment]
No, I am running server project.


Sent from Yahoo Mail for iPhone


On Thursday, August 19, 2021, 10:15 AM, Brennan ***@***.***> wrote:




Are you running the client project? There was an issue where VS was setting the client project as the default project to run when it was supposed to be the server project selected.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nssidhu** [comment]
Looks like yes, it is defaulting to the client project. when i changed it to server it works.
Thanks for pointing that out
