### ISSUE TITLE
Let AddSpaStaticFiles be configured with multiple localized spa apps.

### ISSUE THREAD

**Issue by blogcraft** [dotnet/aspnetcore#35485]
### Is your feature request related to a problem? Please describe.
When using Angular i18n localization there are multiple apps created in the dist folder for all the languages the Angular app is supporting.

The problem is that .NET AddSpaStaticFiles only lets add one root path, being insufficient.

### Describe the solution you'd like
Add the ability to further configure AddSpaStaticFiles to be able to accept multiple localized apps
Accept Accept-Language value in the request header to set the language or also to be able to generate urls with the embedded locale.

**Comment by javiercn** [comment]
@blogcraft thanks for contacting us.

As of .NET 6.0 we are no longer using the SpaStaticFiles middleware in our templates. While its still there and you can use it, its unlikely that we will make any changes to it at this point. 

Moving forward SPA applications get copied to the wwwroot folder during publish and are served from there with a fallback route on the hosting server application. 

To that regard they should work like any other backend and you should be able to follow the same instructions Angular provides for doing this in any other backend.

**Comment by blogcraft** [comment]
Great! Thanks for the response, I'm looking forward to start testing .NET 6.

Are there some beta docs about this?
