### ISSUE TITLE
Open Views/Shared/_Layout.cshtml ,type " <input asp-test="" " in the <body> tag and delete a double quote, the format is incorrect.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspnetcore#35495]
**REPRO CONFIGURATION:**Win10 x64 20H1 + SDK 6.0.rc1 + Feed
**Latest SDK Version:** 6.0.100-rc.1.21418.40
**Latest Runtime Version:** 6.0.0-rc.1.21418.9

**INSTALL STEPS​:**
1. Clean machine: Win10 x64 20H1
2. Install the sdk 6.0.rc1 from: https://aka.ms/dotnet/6.0.1XX-rc1/daily/dotnet-sdk-win-x64.exe
3. Install VS Code from: [https://code.visualstudio.com/Download](url)
4. Install C# Extensions version: v1.23.15.vsix from: https://github.com/OmniSharp/omnisharp-vscode/releases
5. Apply feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

**Testcases Affected**
[SimpleWebAppRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)

**Platform**
- [x] Windows
- [ ] macOS
- [x] Linux

**Repro Steps**
1. Open a normal Terminal Emulator
2. Create mvc project and open it using VS code
```
  md mvc
  cd mvc
  dotnet new mvc
  code .
```
3. Go to [https://github.com/OmniSharp/omnisharp-vscode/releases](url) > Download the csharp-1.23.15.vsix.
4. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
5. Open Views/Shared/_Layout.cshtml and type " **<input asp-test=""** " in the `<body>` tag, then delete a double quote, wait a few seconds, the format is incorrect.

**Note:**
1. This issue repro on the SDK 6.0 preview 7 +  v1.23.15.
2. This issue not repro on C# Extensions is v1.23.14.
3. On Linux OS, delete a double quote, wait a few seconds, it will pops up CodeLens references.

**Actual Result**
![image](https://user-images.githubusercontent.com/82028229/130051918-c8b441aa-88ae-4b31-a078-f24ffd70541b.png)

 On Linux OS
![image](https://user-images.githubusercontent.com/82028229/130052477-c4c85ef3-9c32-4147-9ca9-bc57a4a96127.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/82028229/130052650-050a9d3b-5243-4ee4-b108-a7a80bf4e37a.png)

**Comment by NTaylorMullen** [comment]
This is by design because even though the quoted attributes are in-complete the attribute itself is still considered a TagHelper attribute which gets the different coloring.

**Comment by v-cazhang** [comment]
> This is by design because even though the quoted attributes are in-complete the attribute itself is still considered a TagHelper attribute which gets the different coloring.

But there is another question, on Linux OS ,like the picture shown above, there shows reference message under <header> tag, is this expected?

**Comment by NTaylorMullen** [comment]
> tag, is this expected?

No, does that happen consistently?

**Comment by v-cazhang** [comment]
@NTaylorMullen  I still meet this issue on 6.0.100-rc.1.21424.1 + csharp-1.23.15. Should we reactive this issue ?
![image](https://user-images.githubusercontent.com/82028229/130756485-7197728a-5445-4f9c-8715-6fbd0f70def4.png)
