### ISSUE TITLE
How to access the component instance in the Blazor Xunit test case?

### ISSUE THREAD

**Issue by BerlyChristopher** [dotnet/aspnetcore#35500]
Hi Team,

We can test the Blazor component with BUnit, XUnit test cases and etc. We can access the DOM element of the particular blazor component and write the test case with help of XUnit. But we need to access the component instance and modify the component value through the Selenium and XUnit test case. The same thing can be achieved by the BUnit test case. 

Any suggestion to access the component instance and modify the value with help of Selenium and XUnit test case in Blazor Server application?

Regards,
Berly B.C

**Comment by javiercn** [comment]
@BerlyChristopher thanks for contacting us.

There's no way to achieve what you want unless you put code in your application to do so. Components are handled internally by the framework and the only way to get a reference to an instance is via the `@ref` directive from a parent component or by creating a JSObjectReference from the component instance and passing it to JS.
