### ISSUE TITLE
Analyzers for Minimal APIs

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#35528]
This is issue is to track ideas for analyzers for Minimal API scenarios:

**Errors:**
- [x] Detecting when types that implement `IActionResult` are returned from route handlers. This will result in serializing the result as JSON which is unintended.
  ```C#
  app.Map("/", () => new JsonResult(new { Hello = "World" }));
  ```
- [x] #34404
- [x] #35638
  ```C#
  app.Map("/", () => Hello());
  
  [Authorize]
  void Hello() { }
  ```
- [x] #34553

**Comment by captainsafia** [comment]
Tagging https://github.com/dotnet/aspnetcore/issues/34543 onto this as well.

**Comment by rafikiassumani-msft** [comment]
Closing this issue. We will use the following issue for tracking analyzers work in NET7: https://github.com/dotnet/aspnetcore/issues/36637
