### ISSUE TITLE
Support DateOnly and TimeOnly as parsing options for [SupplyParameterFromQuery]

### ISSUE THREAD

**Issue by dannyBies** [dotnet/aspnetcore#35525]
### Is your feature request related to a problem? Please describe.
I want to use the `DateOnly` or `TimeOnly` types to parse querystring parameters but when I try to use either of those types I get:
```NotSupportedException: Querystring values cannot be parsed as type 'System.DateOnly'.```.
Seeing as `DateTime` is supported it would be great if we can add these types as well.

### Describe the solution you'd like
Support for the following code:
```
[Parameter, SupplyParameterFromQuery]
public DateOnly CurrentDate { get; set; }
[Parameter, SupplyParameterFromQuery]
public TimeOnly CurrentTime { get; set; }
```
I'd be happy to submit a PR if we want to support these scenarios.

**Comment by TanayParikh** [comment]
Hey @dannyBies, I think this seems like a good idea. 

> I'd be happy to submit a PR if we want to support these scenarios.

Sounds great, feel free to submit a PR! 😄

**Comment by TanayParikh** [comment]
Thanks @dannyBies, this seems like a great idea, will look into it further.
