### ISSUE TITLE
Blazor Hosted - Pass model to Server with NavigationManager

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#35530]
First off, I won't label this as a bug, because I don't even know whether this is possible or not. I have a Blazor Hosted app and I'm implementing a way to download a file stream. In the server I have an API that returns `File(...)` and I've read I can called the API from the client with `NavigationManager.NavigateTo(url, true)`. This way the UI won't freeze up until the file is downloaded. The problem comes with the `NavigateTo` method. The API expects the model `[FromBody]`. I don't see how the method will allow me to pass in the parameter.

**Comment by pranavkm** [comment]
The solution for this would look something like https://stackoverflow.com/questions/32545632/how-can-i-download-a-file-using-window-fetch - download the blob using `HttpClient`, and then use `JSInterop` to create a blob url which can then be downloaded. The plan is to include a sample for this to be included in our docs site (FYI @guardrex)
