### ISSUE TITLE
HTML comment completion broken

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#35536]
Repro steps:
1. `<!--`, auto-complete will add `-->`
2. Press space to... space out a bit

Expected result:
A space is added so your comment can look good.

Actual result:
`<a` gets completed, even though it isn't a valid result in that position.
![HtmlCommentOvertype](https://user-images.githubusercontent.com/14987221/130158676-55f7e403-cf24-43cf-9252-7f550ee0dced.gif)

**Comment by NTaylorMullen** [comment]
Fixed via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338934
