### ISSUE TITLE
W3CLog ends up in the wrong file at the end of the day

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#35546]
### Describe the bug
Currently in `FileLoggerProcessor` logs are writtern in files asynchronously, which means all the messages are added to a `BlockingCollection<string>` and another thread is processing the queue. 

Now there could be messages that are produced at 11:59 PM but the logging thread is processing them in 12:01 AM. Those logs would end up in a wrong file. Is this a bug or it is by design?

### To Reproduce
Wait for midnight (or change the time on your machine) and send a lot of requests at 11:59 PM!

**Comment by wtgodbe** [comment]
This was by design, we figured that writing to files based on processing time was good enough, and logging is fast enough that the set of entries logged on the wrong date would be sufficiently small.
