### ISSUE TITLE
[SignalR] Provide a way for Azure SignalR to read HttpConnectionDispatcherOptions

### ISSUE THREAD

**Issue by vicancy** [dotnet/aspnetcore#35544]
### Current issue
SignalR provided a auth expiration feature in [Close connection on auth expiration by BrennanConroy · Pull Request #32431](https://github.com/dotnet/aspnetcore/pull/32431), however, the option `CloseOnAuthenticationExpiration` is in `HttpConnectionDispatcherOptions`, this is one Option that Azure SignalR SDK is **not** able to fetch out value from.

A similar issue we encountered before is the `TransportType` option, since we are not able to fetch the `TransportType` value out from the option, we add a [similar option in Service SDK](https://github.com/Azure/azure-signalr/pull/1365#issuecomment-888017659)

### Proposed solution
It would be great if there is a way for the Azure SignalR SDK to read `HttpConnectionDispatcherOptions`, so that we don't need to create a similar option in the service SDK and users don't need to set a similar Option when using service SDK.

**Comment by davidfowl** [comment]
@BrennanConroy maybe we can stash this in endpoint metadata?

**Comment by BrennanConroy** [comment]
> stash this in endpoint metadata

That sounds like it's the best we can do at this point, can't backtrack and make the options come from DI now.

**Comment by BrennanConroy** [comment]
@vicancy Would adding endpoint metadata that contains the `HttpConnectionDispatcherOptions` work for you?

Similar to how we have the `HubMetadata` and `NegotiateMetadata` that the service uses https://github.com/Azure/azure-signalr/blob/16029cbde8f45af6fbac2923c5b7102e34d5a0c9/src/Microsoft.Azure.SignalR/Startup/AzureSignalRHostedService.cs#L30-L31

**Comment by vicancy** [comment]
Sounds good, cc @Y-Sindo
