### ISSUE TITLE
Set asp-append-version to true for everything

### ISSUE THREAD

**Issue by mattferderer** [dotnet/aspnetcore#35553]
It would be great if we could avoid having to write asp-append-version="true" to each JS script or CSS stylesheet we include on a Razor page. 

This relates to the check in the Link Tag Helper https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.TagHelpers/src/LinkTagHelper.cs#L283 

Would it be possible to use IWebHostEnvironment to pass a default value into the constructor via the Program.cs or Startup.cs file? 

I feel this is a low priority, would be nice to have convenience feature request.

**Comment by Tratcher** [comment]
IWebHostEnvironment isn't the right place for this kind of setting, it belongs in the mvc options somewhere.

**Comment by singh733** [comment]
Thank you @Tratcher. I will do it in mvc options.

**Comment by pranavkm** [comment]
We could consider putting this in `HtmlHelperOptions` instead. The options name is a bit unfortunate, but it'd be much closer to where this setting needs to be.

```diff
public class HtmlHelperOptions
{
+    /// <summary>Gets or sets a value that determines if a file version is appended by default to <c>LinkTagHelper</c> and <c> ScriptTagHelper</c> instances. This value is ignored if the tag helper specifies a value for the <c>asp-append-version</c> attribute.</summary>
+    public bool AppendFileVersionsToTagHelpers { get; set; }
}
```

## Usage:

```C#
services.AddRazorPages();
services.Configure<HtmlHelperOptions>(options => options.AppendFileVersionsToTagHelpers = true; });
```

I'm not a fan of the property name, but we might come up with something better during API review.

**Comment by singh733** [comment]
Thank you @pranavkm. I will do it in HtmlHelperOptions.

**Comment by singh733** [comment]
Hi @pranavkm , @Tratcher 

I have started working on this. I have noticed the following points.

a) if we don't have any of the asp attribute then Process function will never call. for example : `<link rel="stylesheet" href="~/css/site.css"/>`

b) If we have the few asp attribute then it return before the AppendVersion logic.  for example: 
```
<link rel="stylesheet" 
              href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
               />
```

c) Also looking at Unable to resolve service for type 'Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelperOptions' while attempting to activate 'Microsoft.AspNetCore.Mvc.TagHelpers.LinkTagHelper'.

**Note** : The first 2 steps i have performed by setting HTMLHelperOptions = null in the constructor of LinkTagsHelper.

I am working on all these points

Thank you

**Comment by singh733** [comment]
Hi @pranavkm , @Tratcher

I am working on https://github.com/dotnet/aspnetcore/issues/35553.

When i try to inject HtmlHelperOptions in LinkTagHelper then i got the below error.

![image](https://user-images.githubusercontent.com/83835739/147319695-d20a7733-a9f7-4f5b-b83c-1f4abb5a5020.png)

I fix it by adding the below code in the MvcRazorMvcCoreBuilderExtensions. Please let me know if this Approach is correct or not.

![image](https://user-images.githubusercontent.com/83835739/147319835-a1340d9f-184f-4ef6-a0f7-56bfe4744a38.png)

**Comment by DamianEdwards** [comment]
Just FYI you can achieve this today already with an `ITagHelperInitializer<>` registered for each Tag Helper that has the `AppendVersion` property. As others have pointed out, you also need to ensure the Tag Helper in question actually applies to the HTML tag instance based on its rules, which in the case of `script` and `link` can be enforced by using the `asp-src-include` and `asp-href-include` attributes instead of `src` and `href`.

Example:
**Program.cs**
``` csharp
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.AddSingleton<ITagHelperInitializer<ScriptTagHelper>, AppendVersionTagHelperInitializer>();
builder.Services.AddSingleton<ITagHelperInitializer<LinkTagHelper>, AppendVersionTagHelperInitializer>();
builder.Services.AddSingleton<ITagHelperInitializer<ImageTagHelper>, AppendVersionTagHelperInitializer>();

var app = builder.Build();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();

public class AppendVersionTagHelperInitializer :
    ITagHelperInitializer<ScriptTagHelper>,
    ITagHelperInitializer<LinkTagHelper>,
    ITagHelperInitializer<ImageTagHelper>
{
    private const bool DefaultValue = true;

    public void Initialize(ScriptTagHelper helper, ViewContext context)
    {
        helper.AppendVersion = DefaultValue;
    }

    public void Initialize(LinkTagHelper helper, ViewContext context)
    {
        helper.AppendVersion = DefaultValue;
    }

    public void Initialize(ImageTagHelper helper, ViewContext context)
    {
        helper.AppendVersion = DefaultValue;
    }
}
```

**_Layout.cshtml**
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication123</title>
    <link rel="stylesheet" asp-href-include="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="~/css/site.css" />
    <link rel="stylesheet" asp-href-include="~/WebApplication123.styles.css" />
</head>
<body>
    <header>
    ...
    ...
    ...
    <script asp-src-include="~/lib/jquery/dist/jquery.min.js"></script>
    <script asp-src-include="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script asp-src-include="~/js/site.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
```

**Comment by mattferderer** [comment]
Thank you for this @DamianEdwards. I will try it out & blog about it so it's easier to find. I think that's an easy to implement solution for this minor problem. I would be ok with this issue being closed.

**Comment by singh733** [comment]
Thank you @DamianEdwards . I will close my PR.

**Comment by pranavkm** [comment]
I'm adding a note about using initializers to our docs: https://github.com/dotnet/AspNetCore.Docs/pull/24540. Closing this issue as we don't have any additional work to do here.

**Comment by mattferderer** [comment]
Just a note, the above doesn't seem to work on images as it appears you need both a src & an asp-append-version for the image to be considered a tag helper.  One could create their own image tag helper though as per the docs. Thank you all again for your help on this!
