### ISSUE TITLE
Blazor Hosted WebAssembly, Failing to resolve the route.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#35589]
Using VS 2022 Preview 3.1 in Blazor Hosted Web Assembly project.

while using Swagger to test my API, it runs into error.
The same error also occurs when running from Blazor web assembly code.

endpoint configured in program.cs

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllers();
    endpoints.MapControllerRoute(
       name: "default",
       pattern: "{controller=Home}/{action=Index}/{id?}");
    endpoints.MapHub<ChatHub>("/chathub");
    endpoints.MapFallbackToFile("index.html");

});
```

Controller signature

        [HttpGet]
        [AllowAnonymous]
        [Produces("application/json")]
        public async Task<IActionResult> GetAllCountries()

![image](https://user-images.githubusercontent.com/3267605/130343007-5ecc4db0-fde6-42a3-864a-fa8c9f041195.png)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
