### ISSUE TITLE
Can not reference RCL assets using assembly name

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#35587]
To reproduce:

Create a Blazor project
Create a Blazor component library named MyComponents.

Edit RCL .csproj add: 

	<PackageId>MyCompany.MyComponents</PackageId>
	
Right click on the .csproj and note the assembly name is MyComponents. This is different from the nuget package name which is MyCompany.MyComponents.  Build the project and note MyComponents.dll in the bin folder.
	
Add a reference to the library from the project.  Do not add a reference to the nuget.

To reference assets from the RCL:

[This documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#razor-class-library-rcl-support-1) says to reference the RCL assembly name:

> In the following example:

> The static web asset base path is _content/ClassLib.
> The class library's assembly name is ClassLib.

	<link href="_content/ClassLib/ClassLib.bundle.scp.css" rel="stylesheet">

Referencing the assembly name (MyComponents.dll) does not work:

	<link href="_content/MyComponents/MyComponents.bundle.scp.css" rel="stylesheet" />

Referencing the name of the generated nuget package does work:

	<link href="_content/MyCompany.MyComponents/MyComponents.bundle.scp.css" rel="stylesheet" />
	
	
This issue may be related to [this one](https://github.com/dotnet/aspnetcore/issues/35366).

**Comment by javiercn** [comment]
@sam-wheat thanks for contacting us.

That's an error on the docs, it's always the package Id that is used. This is by design.

@guardrex can we update the docs to correctly reflect that fact?

**Comment by guardrex** [comment]
Thanks @sam-wheat and @javiercn ... It's taken two rounds of doc updates to address it between late last week and this morning. We're using new text/examples that have "package ID"/`{PACKAGE ID}`/`<PackageId>` with a remark that the package ID defaults to the assembly name if `<PackageID>` isn't specified. The doc updates will appear in the live doc set within 24 hours, and we'll take feedback to see if further updates are needed. Thanks again for calling this out.
