### ISSUE TITLE
ProtectKeysWithCertificate(thumbprint) does NOT Throw an Exception if the Certificate is Inaccessible due to Permissions

### ISSUE THREAD

**Issue by arex388** [dotnet/aspnetcore#35602]
### Describe the bug

When using Data Protection's `ProtectKeysWithCertificate(thumbprint)` method, if the certificate does not have the correct permissions in the certificate store, no exception is thrown and a key is generated using some fallback method. Furthermore, each time the app is restarted it will generate new keys since on each startup it fails to access the specified certificate.

For apps that share a key, such as `login.example.com` and `portal.example.com`, each app will generate their own key if `DisableAutomaticKeyGeneration()` is not specified for the non-`login` apps, and this will cause an infinite redirect loop between the two where `login` authorizes and redirects to `portal`, but `portal` can't verify and redirects back to `login`.

### To Reproduce

Create an ASP.NET Core site that uses Data Protection and specifies a certificate by its thumbprint to use and **test on IIS on a different machine**. Debugging locally does not expose the issue because, if like me you're an admin, then by default you have permissions to the certificates.

### Exceptions (if any)

No exceptions are generated. I'm asking *for* an exception to be generated because it took me days to remember about checking the permissions on the certificate.

### Further technical details

- ASP.NET Core version: **5, but I've seen it as far back as 2.0/2.1.**
- Include the output of `dotnet --info`: **N/A**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: **Visual Studio 2019 16.11.1**

**Comment by HaoK** [comment]
@arex388 can you clarify what permission behavior you are seeing?  When I tried accessing a certificate store I didn't have permission to(when running as non admin), I got an Access Denied exception from `Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateResolver.GetCertificateFromStore(StoreLocation location, String thumbprint)`

I need some help isolating the code path that you are hitting to see if we are swallowing exceptions/missing some logging, if you could provide a small repro app with some instructions on github that would be ideal.
