### ISSUE TITLE
[SPA] Using floating versions on the SPA repo in eng/Versions.props

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35608]
This is to make sure when building the templates locally we pick-up the latest available packages within a given preview/release version.

(For example, the current packages point to preview6 versions, and ideally we would want to match something like RC1 while in  the RC1 milestone and so on).

@dougbu do you foresee any problem in the asp.net core builds if we do this on eng/Versions.props within the spa-templates repo? As far as I understand, that gets ignored.

**Comment by dougbu** [comment]
> do you foresee any problem in the asp.net core builds if we do this on eng/Versions.props within the spa-templates repo?

@javiercn no, I don't foresee problems in dotnet/aspnetcore no matter how you change eng/Versions.props in dotnet/spa-templates.

I don't understand what you mean by "floating versions" in this issue. Last I heard, the idea was we'd manually update the versions in this repo as 6.0 releases occur. Wildcards would instead use nightlies. Could you clarify❔

Separately, it may be necessary to branch the dotnet/spa-templates repo as 6.0 and 7.0 diverge. That also requires updating the submodule in dotnet/aspnetcore's release/6.0 branch.

**Comment by pranavkm** [comment]
@javiercn changed his mind.
