### ISSUE TITLE
VS Code: Open Views/Shared/_Layout.cshtml and type " @da ", error info is no appear in PROBLEMS window.

### ISSUE THREAD

**Issue by v-eileengao** [dotnet/aspnetcore#35603]
**REPRO CONFIGURATION:** Win10 x64 ENU 21H1 + VS Code+ feed
**Latest SDK Version:**  6.0.100-rc.1.21410.51
**Latest Runtime Version:** 6.0.100-rc.1.21406.5
**INSTALL STEPS​:**

1. Clean machine: Win10 x64 ENU 21H1

2. Install the latest version of [VS Code](https://code.visualstudio.com/Download)

3. Install .NET 6.0 RC1 from “main(6.0.x Runtime)” branch of [GitHub - dotnet/installer](https://github.com/dotnet/installer)
3. Apply feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

4. Install C# Extensions version: v1.23.15-beta1 from [here]( https://github.com/OmniSharp/omnisharp-vscode/releases)

**Testcases Affected**
[SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)
[SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleBlazorRazorEditingWithVSCode.md)

**Platform**
- [x]  Windows
- [ ] macOS
- [x] Linux

**Repro Steps**
1. Open a normal Terminal Emulator
 2. Create mvc project and open it using VS code
 ```
   md mvc
   cd mvc
   dotnet new mvc
   code .
```
 3. Go to https://github.com/OmniSharp/omnisharp-vscode/releases > Download the csharp-1.23.15-beta1.vsix.
 4. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
 5. Open Views/Shared/_Layout.cshtml and type " @da ", error info is no appear in PROBLEMS window.
 
**Note:**

  1.This issue can repro on  Linux OS .
  2.When the installed C# Extensions is v1.23.14, this issue not repro.
 
**Actual**
![image](https://user-images.githubusercontent.com/81619747/128979824-a2af90a2-2a00-4aab-9279-cdeebd304abc.png)

**EXPECTED**
![image](https://user-images.githubusercontent.com/81619747/128980129-5b8904c5-25e3-43a8-93e0-0b503483f488.png)

**Comment by v-eileengao** [comment]
C# Extensions [v1.23.15-beta1] also caused the following issues, do we still need to open a bug separately?
1. Create a Blazor project, then open the  index.razor ,there are some warning messages in PROBLEM window.
    
![image](https://user-images.githubusercontent.com/81619747/128982134-01a8e335-b58b-4471-ab9c-57fe63c0d569.png)
2.  Create a Blazor project, then open the  index.razor, typing @SetParametersAsync() ,no prompts for signature help inside of the ().
![image](https://user-images.githubusercontent.com/81619747/128982570-13f53fe7-d9e3-4452-882c-8a0f4cfefbd2.png)

Create a Blazor project, open Pages/_Host.cshtml  and type @ThisDoesNotExist ,error info is also no appear in PROBLEMS window.
**Actual**
![image](https://user-images.githubusercontent.com/81619747/128983301-bf1d3660-da4d-42c9-a68e-4316ec666071.png)
**EXPECTED**
![image](https://user-images.githubusercontent.com/81619747/128983524-69df04f9-1c61-4237-9013-a30efe933eb6.png)

**Comment by Serena01** [comment]
We notice this issue cannot reproduce 
 if we choose xxx.csproj while open project as following
![image](https://user-images.githubusercontent.com/20184641/130427543-74f449e0-b25e-4aa3-9852-291f01301b1d.png)
then build the project as bellow:
![image](https://user-images.githubusercontent.com/20184641/130428523-a9997518-bf76-4e62-a7ef-0508ca389543.png)

**Comment by javiercn** [comment]
@v-eileengao thanks for contacting us.

@NTaylorMullen Is this something you need to look at?

**Comment by v-eileengao** [comment]
If we select .csproj file when opening the project, and then select "Yes" in the pop-up box in the lower right corner, the issue cannot be reproduced, so i closed it.
