### ISSUE TITLE
Blazor preserving prerended state does not seem to work

### ISSUE THREAD

**Issue by dannyBies** [dotnet/aspnetcore#35605]
### Describe the bug
I'm following the guide at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#preserve-prerendered-state to preserve the prerendered component state. However when I try to run the application I get the following error:
![image](https://user-images.githubusercontent.com/3967506/130435842-aec3e7ab-ecd9-4ab6-9109-b5caa20545b7.png)

### To Reproduce
1 -> Create new Blazor Server template
2 -> Add the `<preserve-component-state />` below `<script src="_framework/blazor.server.js"></script>` in `_Host.cshtml`
3 -> Change the code in `FetchDate.razor` to the code mentioned in https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#preserve-prerendered-state. 
4 -> Run application

It seems this issue also occurs using the hosted webassembly template but I'm not familiar enough with that approach to be 100% sure of that.

A few more potential issuesI have noticed:
* The prerendered html returns "An unhandled exception has occurred. See browser dev tools for details.", however no error is shown in the dev tools
* It seems like `ApplicationState.OnPersisting` is not working because when I add a breakpoint it doesn't seem to be getting hit
* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#stateful-reconnection-after-prerendering-1 seems the approach mentioned here can be replaced by `<preserve-component-state />`
* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly#preserve-prerendered-state does not have a section for the WebAssembly implementation

### Further technical details
ASP.NET Core version 6.0.100-preview.7.21379.14
Visual studio community 2022 preview 3.1

**Comment by guardrex** [comment]
Although we've made updates to the *Prerendering and integration* topic for 6.0, I haven't confirmed the guidance. I've noted to do so for this topic on the [6.0 docs tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/22045). I'll keep an 👁️ on this PU issue in the meantime.

**Comment by dannyBies** [comment]
I just had another quick look and I found the issue.
In the docs the following needs to be changed:
`if (!ApplicationState.TryTakeAsJson<WeatherForecast[]>("fetchdata", out var forecasts))`
to
`if (!ApplicationState.TryTakeAsJson<WeatherForecast[]>("fetchdata", out forecasts))`
as currently it shadows the `forecasts` variable. I completely overlooked that!

I'm assuming the issue with my templates not being up to date is because these have not been released yet. I'll have another look when a new update gets released for VS 2022, but for now my issue has been solved. 
Thanks for the help @guardrex!

**Comment by guardrex** [comment]
Thanks @dannyBies. The code was dumped into the doc from the blog post IIRC. When I get on RC1, all of (or *most of*) the code examples will be checked. Some of them, including that example, will be improved and loaded into a snippet sample app that will break on build on that type of error. I'll get the doc fixed up soon.

**Comment by dannyBies** [comment]
No problem at all, I'm working with preview bits after all :)
