### ISSUE TITLE
Untrusted localhost certificate used by Visual Studio to debug Blazor prevents WASM Debugging

### ISSUE THREAD

**Issue by tpups** [dotnet/aspnetcore#35618]
### Description
I am having some trouble debugging into Blazor WebAssembly apps, and I'm wondering if the issue is with my HTTPS certificate. I found when I create a template app without checking the HTTPS box in Visual Studio, I can debug into the client (WebAssembly) project. When I check the HTTPS box while creating a template app, I can't debug into the WASM project.

Which leads me to my localhost certificate. It is untrusted, according to any browser as well as MMC. Double clicking on the cert in MMC shows:

> This CA root certificate is not trusted. To enable trust, install this certificate in the Trusted Root Certification Authorities store.

I've tried deleting all instances of localhost certificates from MMC, under both user account and computer account, then repairing IIS and running the VS debugger to have the certificate re-installed. VS prompts me to both install and trust the certificate, but it remains untrusted.

I have copied the certificate from Personal > Certificates to Trust Root Certification Authorities > Certificates, but it still shows as not trusted, even though it then shows up under Certificates to Trust Root Certification Authorities > Certificates in MMC.

Finally, I've tried cleaning and trusting the certificates with the dotnet CLI:

> dotnet tool uninstall --global dotnet-dev-certs
> dotnet tool install --global dotnet-dev-certs
> dotnet dev-certs https --trust
> dotnet dev-certs https --clean
> dotnet dev-certs https --check
> dotnet dev-certs https
> dotnet dev-certs https --trust

To reproduce: create a new project in Visual Studio using the Blazor WebAssembly App template. Check the boxes for 'Configure for HTTPS' , 'ASP.NET Core Hosted' and 'Progressive Web Application'. Try to launch the debugger and see if the localhost certificate is trusted.

### Configuration
.NET 5.0.9
Windows  Version 10.0.19042 Build 19042
x64
Visual Studio 2019 16.11.1

### Regression?
This has been an issue for 6 months across several versions of .NET 5 and Visual Studio 2019.

**Comment by javiercn** [comment]
@tpups thanks for contacting us.

I would suggest you start by closing all instances of the browser after trusting the certificate and reopening it, browsers cache those things.

The next thing I would check is the certificate thumbprint from the certificate in the browser against the ones in the certificate store to make sure the certificate is coming from there.

**Comment by tpups** [comment]
@javiercn thanks for your response.

I have tried closing all instances of Edge, as well as launching the debugger using Chrome.

I've also confirmed the cert showing in the browser is the same one I'm seeing in the certificate store - the thumbprints match and this follows as even the certificate store says the certificate is untrusted.

**Comment by javiercn** [comment]
Does it happen with all browsers? Have you tried firefox or some other browser?

**Comment by tpups** [comment]
@javiercn Yes, with Edge, Chrome, and Firefox.

**Comment by javiercn** [comment]
Is the machine joined to AAD or something like that where an admin can be applying a group policy that is tweaking the settings?

**Comment by tpups** [comment]
@javiercn sorry for the delayed response - I'm using Kestrel. I've tried IIS Express but seem to have the same problem. IIS installs its own certificate but it is also untrusted.

**Comment by javiercn** [comment]
@tpups thanks for the additional details.

It seems that there is some issue on your system that prevents self-signed certificates from being trusted. I believe I've seen in the past, however I can't tell whether we were able to find a resolution for it. Something in your Windows configuration is configured to prevent self-signed certificates from being trusted (maybe you have some anti-virus or similar that is changing some policies?)

**Comment by javiercn** [comment]
@tpups I was actually able to find the issue we ran into last time, I would suggest you try this https://serverfault.com/questions/1008035/unable-to-import-certificate-into-user-trusted-root-certificate-store

**Comment by javiercn** [comment]
Added a docs issue https://github.com/dotnet/AspNetCore.Docs/issues/23233 to track troubleshoot steps
