### ISSUE TITLE
"DenyAnonymousAuthorizationRequirement" is not respecting "AuthorizationOptions.InvokeHandlersAfterFailure"

### ISSUE THREAD

**Issue by nazar-kuzo** [dotnet/aspnetcore#35610]
### Describe the bug
When building Authorization policies with PolicyBuilder and specifying either ".RequireAuthenticatedUser()" or explicitly adding "DenyAnonymousAuthorizationRequirement" wont fail authorization immediately after when  "AuthorizationOptions.InvokeHandlersAfterFailure" option is set to false.

### To Reproduce
Create empty aspnet project with any type of authentication.

Add authorization:
```
services
  .AddAuthorization(options =>
  {
      // indicates that authorization should fail immediately after
      // first failed policy and not to proceed to any other pending policies
      options.InvokeHandlersAfterFailure = false;
  
      options.DefaultPolicy = new AuthorizationPolicyBuilder()
          .RequireAuthenticatedUser()
          .RequireAssertion(context =>
          {
              // this code should newer be executed on unauthenticated request
  
              return context.User.Identity.IsAuthenticated;
          })
          .Build();
  });

```

Make unauthenticated request.

#### Expected result
All unauthenticated requests should fail on ".RequireAuthenticatedUser()" requirement and not execute further if "InvokeHandlersAfterFailure" is set to "false"

#### Actual result
Every unauthenticated request is executing "RequireAssertion" followed by ".RequireAuthenticatedUser()" requirement when "InvokeHandlersAfterFailure" is set to "false".

### Exceptions (if any)
None

### Root cause
"DenyAnonymousAuthorizationRequirement" implementation is never calling `context.Fail()` on unauthenticated request, hence not respecting "InvokeHandlersAfterFailure" set to "false" setting.
[DenyAnonymousAuthorizationRequirement.cs]https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authorization/Core/src/DenyAnonymousAuthorizationRequirement.cs#L20-L31

### Further technical details
- ASP.NET Core version 3.1
- VS 2019 Version 16.10.4

**Comment by blowdart** [comment]
@haok to check my assertion here.

This is an on-purpose design decision. We run through all requirements in a handler because some folks write requirements with side effects like logging.

**Comment by nazar-kuzo** [comment]
@blowdart thanks for a quick reply.

It would be great if you could point me to a documentation where it states that, or make this behavior more obvious.

Based on your statement, if it has to stay as it is,
what would be your recommended approach for custom policies implementation that expect user to be authenticated?

The only way I see it for now is to either build custom "DenyAnonymousAuthorizationRequirement" that will fail authorization or write `if (context.User.Identity.IsAuthenticated)` statement in every policy which is cumbersome to my mind.

**Comment by blowdart** [comment]
I'm afraid the cumbersome route is probably best, because remember policy can not only be called via attributes, but via code, and requirements can also be evaluated via code, and that route can be done anywhere, so you can't rely on user being filled at that point.

**Comment by nazar-kuzo** [comment]
@blowdart I do agree with you.
In that case I would suggest you to revisit the implementation of "AuthorizationOptions.InvokeHandlersAfterFailure" since it does not guarantee what it states and also provide some additional comments to "DenyAnonymousAuthorizationRequirement" that it also does not fail unauthenticated requests and every custom policy should always perform such checks on their own, since to me it is the big opening after a long time of using it 😀. Did a questionnaire to my colleges and as you can guess - it is no F way obvious to them neither.

**Comment by blowdart** [comment]
That's fair, we'll talk about it in triage later this week.

**Comment by blowdart** [comment]
Yea I'm not suggesting a rename, just wondering if docs can help here

**Comment by nazar-kuzo** [comment]
@blowdart, yes I would suggest to add additional explanation to `.RequireAuthenticatedUser()` saying that it is not failing the authorization on unauthenticated request, so there should be additional authentication check in every authorization requirement.

Also, make more clear in comment how `AuthorizationOptions.InvokeHandlersAfterFailure` behaves, add comment that it stops invocation only if handler explicitly called `.Fail()` and add reference to `DenyAnonymousAuthorizationRequirement`

But you decide whether it makes sense or not.
Personally, I would extend `DenyAnonymousAuthorizationRequirement` with optional parameter which fails requirement once specified. That would improve overall experience and not cause any breaking changes and no need in additional comments since it would be self explanatory

**Comment by HaoK** [comment]
@blowdart we can tweak https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationoptions.invokehandlersafterfailure?view=aspnetcore-5.0 to be specific, "Determines whether authentication handlers should be invoked after a failure." where "failure" can be changed to "AuthorizationHandlerContext.Fail" is called, but there's conceptually no other way for a failure to happen, but this might make it slightly clearer
