### ISSUE TITLE
W3CLogging "time" not precise enough, leading to "time-taken" being significantly wrong

### ISSUE THREAD

**Issue by ajkonkol** [dotnet/aspnetcore#35613]
### Describe the bug
When using the new W3CLogging, I've noticed that the "time" field is only precise down to the second.  This does not match many other web servers, including IIS, which log times with millisecond precision. Also, the "time-taken" field is calculated based on this imprecision "time" value, thus leading to very inaccurate time-taken values in the logs.  For example, if a request comes in at 01:30:00.800 and takes 10 milliseconds to process, then the time-taken that is written to the logs is 810 milliseconds, not the expected 10 milliseconds

### To Reproduce

1. In VS 2022, create a new ASP.NET Core Web App, targetting .NET 6.0 (Preview)
2. In the Program.cs file, add the following immediately before `var app = builder.Build();`

`builder.Services.AddW3CLogging(logging =>
{
    logging.LoggingFields = Microsoft.AspNetCore.HttpLogging.W3CLoggingFields.All;
});`

Also add the following immediately after `var app = builder.Build();`

`app.UseW3CLogging();`

3. Run the application, refresh the page several times, and take a look at the resulting w3clog-*.txt file.   You'll note that the "time" column is formatted as hh:mm:ss, but no milliseconds, and that the time-taken is all over the place, even though we are hitting a very simple page that in actuality is taking under 100ms to process.

### Exceptions (if any)

No exception, just inaccurate time-taken values

### Further technical details
- ASP.NET Core version: .NET 6.0 preview 7
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS 2022 17.0.0 Preview 3.1

**Comment by ajkonkol** [comment]
This is the related code in the W3CLogger that I believe is causing the time-taken to not be accurate:

https://github.com/dotnet/aspnetcore/blob/3c089fa29a441a390f2786e5107f0dcc8397898f/src/Middleware/HttpLogging/src/W3CLogger.cs#L56-L58

I believe simply adding the milliseconds to the time field and parsing it with the milliseconds included when calculating the time-taken would fix this issue.

**Comment by adityamandaleeka** [comment]
@wtgodbe PTAL

**Comment by wtgodbe** [comment]
I'm surprised that IIS logs to millisecond precision, the w3c spec calls for both `time` and `time-taken` to use second precision: https://www.w3.org/TR/WD-logfile.html. I agree that millisecond precision would be more informative here, so if the choice is between following the spec and matching IIS, I'm inclined to think that the usefulness of millisecond precision would break the tie here in favor of matching IIS. @Tratcher do you agree?

**Comment by Tratcher** [comment]
Agreed, use milliseconds. Most requests should not take a full second so that's not a useful unit anymore.

**Comment by wtgodbe** [comment]
Should be a quick fix, I'll include it for RC2.

**Comment by wtgodbe** [comment]
This will ship with 6.0-rc2
