### ISSUE TITLE
[Blazor] Availability of User in Startup

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#35611]
### Is your feature request related to a problem? Please describe.
Sometimes, configuration needs to run once on the server, such as in `Startup.Configure()`. With ASP.NET Core, the `IHttpContextAccessor` can be used, however, this isn't reliable in Blazor. Is there another way?

### Describe the solution you'd like
Any way to access properties of the current user in configuration that runs once on the server would be beneficial.

### Additional context
Please see this issue for background and more info: https://github.com/thepirat000/Audit.NET/issues/440

**Comment by pranavkm** [comment]
In Blazor, you could use `IAuthenticationStateProvider` which should act as an equivalent replacement to getting the `User` from an `IHttpContextAccessor`. The service should be available from DI the same way you acquire `IHttpContextAccessor`

**Comment by mrlife** [comment]
@pranavkm Thank you. Could you provide an example? I can't find `IAuthenticationStateProvider` with Intellisense or in [the docs](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&terms=IAuthenticationStateProvider).

**Comment by pranavkm** [comment]
My bad, it's `AuthenticationStateProvider`. Here's an example of it being used - https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#authenticationstateprovider-service-1

**Comment by mrlife** [comment]
Thank you. I tried `AuthenticationStateProvider` initially and got this error. It appears `Startup.Configure()` accesses the auth state before the user has logged in.

> System.InvalidOperationException: "GetAuthenticationStateAsync was called before SetAuthenticationState."

**Comment by mrlife** [comment]
Thank you. I tried `AuthenticationStateProvider` initially and got this error. It appears the auth state is accessed before the user has logged in.

> System.InvalidOperationException: "GetAuthenticationStateAsync was called before SetAuthenticationState."

When does `SetAuthenticationState` get called? I can't find it in the docs. Thank you.

**Comment by mrlife** [comment]
@pranavkm Can this be reopened so [this](https://github.com/dotnet/aspnetcore/issues/35611#issuecomment-904581998) doesn't get lost?

**Comment by mrlife** [comment]
@javiercn @mkArtakMSFT In the meantime, is there any way to store a user-specific value and recall it, both actions outside of the "Blazor scope"?

**Comment by enetstudio** [comment]
@mrlife,  don't call `AuthenticationStateProvider.GetAuthenticationStateAsync()`
from the Startup class...

You can access the HttpContext object from the Configure method like this:

            app.UseAuthentication();
            app.UseAuthorization();

            app.Use(async (context, next) =>
            {
                await next.Invoke();
                if (context.User.Identity.IsAuthenticated)
                {
                    var userName = context.User.Identity.Name;
                    using (var dbContext = context.RequestServices.GetRequiredService<ApplicationDbContext>())
                    {
                        var user = dbContext.Users.Where(u => u.UserName == userName).FirstOrDefault();
                        if (user != null)
                        {
                            //user.PhoneNumber = System.DateTime.Now;
                            //user.LastIpAddress = context.Connection?.RemoteIpAddress?.ToString();

                            user.PhoneNumber = "1234567";

                            dbContext.Update(user);
                            dbContext.SaveChanges();
                        }
                    }
                }
            });

Hope this help...

**Comment by mrlife** [comment]
@enetstudio Thank you, does your example use `IHttpContextAccessor` for `context` like in the following example?

```c#
public void Configure(IApplicationBuilder app, IHttpContextAccessor contextAccessor)
{
    Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
    {
        // right side of this statement must change for Blazor
        scope.Event.Environment.CustomFields["UserId"] = contextAccessor.HttpContext.User.FindFirstValue("UserId");
    });
    ...
}
```

This is how I've been using it, however Microsoft [says](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state):

> The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app.

**Comment by enetstudio** [comment]
@mrlife, my code is a middleware that accesses the HttpContext object  directly   from the Configure method. You can access the HttpContext.User property, and other values and do something interesting with them, as for instance, passing the User IP address to a service that may be injected into your Razor components, etc.

> The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app.

This simply means: Do not create, as for instance, a service which accesses the HttpContext object through IHttpContextAccessor, inject the service into a Razor component, and try to access the  HttpContext object from within your component. This should not be done even if sometimes it seems to work perfectly well.

Note: The initial request to your web app is always HTTP one. This is the time to capture the HttpContext and to extricate values from it to be used later in your app. This is also applicable when a user login into your app... This is the time the HttpContext object is available, and you can access it with no issues

**Comment by mrlife** [comment]
@enetstudio Thank you for this. Could you clarify how your `context` is defined in `Configure`?

**Comment by enetstudio** [comment]
What do you mean how it is defined ? This is a middleware from which I grab the HttpContext object passed in the HTTP pipeline. I do not define the `context`, it is passed as a parameter from preceding middleware... Did you try my code ? Did you play with it ? Why is this question ? Don't you know what is middleware ? Don't you know how the HTTP pipeline works ?

**Comment by mrlife** [comment]
@enetstudio My use case is for a third party package called Audit.NET. I need to access the `User` like in [this comment](https://github.com/dotnet/aspnetcore/issues/35611#issuecomment-922881033). I appreciate your example and having trouble applying it to my situation.

**Comment by mrlife** [comment]
@pranavkm Can this be reopened again?

**Comment by mrlife** [comment]
@mkArtakMSFT I believe this should be still be open since it is a real need. Could you reopen this issue?

**Comment by javiercn** [comment]
@mrlife What you are looking for is not possible, a Blazor application doesn't start until a websocket is established.

The best you can probably do is to use a [circuit handler](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.circuits.circuithandler?view=aspnetcore-6.0) to grab the user there and setup some circuit specific state.
