### ISSUE TITLE
.NET 6 Blazor Server hosted from another project fails with routing issue

### ISSUE THREAD

**Issue by rgwood** [dotnet/aspnetcore#35648]
### Describe the bug

I'm trying to host Blazor Server inside a Windows desktop application using the new minimal hosting APIs, but I'm running into a Razor routing failure at runtime:

```
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
```

### To Reproduce

[I've put together a minimal repro here](https://github.com/rgwood/BlazorRepro). Essentially:

1. Create a new project P with the Blazor Server App template (the latest one with minimal APIs)
2. Convert P to a library project
3. Move the contents of P's Program.cs into a public function F that can be called to start ASP.NET
4. Call F from another project to start up ASP.NET
5. Navigate to http://localhost:5003 (or whatever the port is for you) in a browser or a web view

My library code looks like this:

```cs
public static async Task<WebApplication> StartOnThreadpool() =>
    await Task.Run(async () =>
            await Task.Run(async () =>
        {
            var builder = WebApplication.CreateBuilder();
            ...
            await app.StartAsync();
            return app;
        });
```

And using it in a console or GUI app looks like this:

```cs
await BlazorServer.Hosting.StartOnThreadpool();
```

### Full Exception

```
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
  at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
  at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
  at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
  at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Context

I appreciate that this method of hosting Blazor is off the beaten path, many apologies if I'm doing something wrong here! I wasn't able to find documentation about embedding ASP.NET in a desktop application, but between the new minimal hosting APIs and WebView2 this is becoming an attractive option for desktop development.

This would be easier if I used the official Blazor Desktop controls, but [my app](https://github.com/rgwood/MinimalWebView) does not use WinForms/WPF/MAUI.

### Further technical details
I'm on the latest VS 2022 (17.0.0 Preview 3.1) with a nightly build of .NET 6 from earlier today.

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21423.17
 Commit:    54e6040be4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21423.17\

Host (useful for support):
  Version: 6.0.0-rc.2.21423.6
  Commit:  8ddb633523

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21423.17 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21420.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21423.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21423.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by davidfowl** [comment]
You need to set the application name to your blazor server's application name (this is so MVC can find the razor pages) and you need to set the content root to the blazor server path so that it can find static files.

**Comment by rgwood** [comment]
Thank you, that does it. [I had been trying that](https://github.com/rgwood/BlazorRepro/blob/main/BlazorServer/Hosting.cs#L11-L14) but I had the application name wrong and wrongly assumed that I was on the wrong track.

For posterity, fixing this in my `BlazorServer` project involves changing this:
```cs
var builder = WebApplication.CreateBuilder();
```
to this:
```cs
// TODO find a way to avoid hardcoding this path
const string ContentRootPath = @"C:\Users\reill\source\BlazorRepro\BlazorServer"; // path to this project
const string ApplicationName = nameof(BlazorServer);
var builder = WebApplication.CreateBuilder(new WebApplicationOptions() { ContentRootPath = ContentRootPath, ApplicationName = ApplicationName });
```

That code can probably be improved but it gets me past the routing issue for now.

P.S. I'm a huge fan of the new minimal APIs, thanks!

**Comment by davidfowl** [comment]
cc @jkotas (See people want to host in libraries too 😄).

**Comment by rgwood** [comment]
There are dozens of us 😄. FWIW, these are the considerations that led me to this approach:

1. I want to ship a small .NET desktop app on Windows using the latest .NET runtime
1. I'd like to use web UI for the front-end, and WebView2 is mature enough to make that practical now
1. I like the development experience of Blazor Server, and the new minimal hosting APIs in ASP.NET make it easy to spin up
1. I'd like to avoid taking a dependency on existing native UI frameworks (WinForms, WPF, MAUI) because they're _big_ and they have implications for trimming and NativeAOT (this one rules out the new Blazor Desktop controls)

**Comment by jkotas** [comment]
> See people want to host in libraries too

Yes, and when people host in the libraries, the defaults do not work well. https://github.com/dotnet/aspnetcore/issues/35648#issuecomment-904728134 confirms what I have said in https://github.com/dotnet/aspnetcore/issues/34838#issuecomment-890064404 that the `Assembly.GetCallingAssembly` default is not really helping the library hosting case.
