### ISSUE TITLE
TagHelper attribute colorization is broken cross-themes

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#35643]
![6uLdbcLzvO](https://user-images.githubusercontent.com/2008729/130534080-b83fe17d-0b41-4a57-bf62-743a42b62fd9.gif)

Blue:
![image](https://user-images.githubusercontent.com/2008729/130534682-6d4fd079-0fdf-441d-ad84-ffcf4a7d52d1.png)

Dark:
![image](https://user-images.githubusercontent.com/2008729/130534111-e52816de-c8ca-48c3-8461-570b73f2b979.png)

Light:
![image](https://user-images.githubusercontent.com/2008729/130534126-f7fac1db-7449-4242-96cf-ea1164b7178d.png)

Blue Extra contrast (The directive colors are a little interesting too 😄 ):
![image](https://user-images.githubusercontent.com/2008729/130534153-b2a61211-39a1-4d9a-9778-6b4ae1e0aa86.png)

**Comment by ryanbrandenburg** [comment]
No Repro. @NTaylorMullen, does this still happen on latest internal VS?

**Comment by NTaylorMullen** [comment]
> No Repro. @NTaylorMullen, does this still happen on latest internal VS?

It did, but now I'm going to try and reinstall the world. Could be a me problem

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen reported offline that this did not reproduce after reinstalling the world, I suspect that given my recent changes in the area he got an unlucky build which polluted his settings, shouldn't be a problem going forward.
