### ISSUE TITLE
Upload CSV File in Blazor hast the wron Format of German "Umlaute" 

### ISSUE THREAD

**Issue by JohnFasc** [dotnet/aspnetcore#35653]
### Describe the bug
I uploaded an csv file to our backen server and persist some data. the problem was, that when i read the file in the backen, the "Umlaute" where displayes as �;

### To Reproduce

i used the code from the docuemntation
`
long maxFileSize = 20971520;
                    using var content = new MultipartFormDataContent();

                    foreach (var file in browserFiles)
                    {
                        var fileContent = new StreamContent(file.OpenReadStream(maxFileSize));
                        if (file.Size < maxFileSize)
                        {
                            content.Add(
                                content: fileContent,
                                name: "\"files\"",
                                fileName: file.Name);
                        }
                    }

`

- Include the output of `dotnet --info`
- .NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pranavkm** [comment]
Thanks for your issue report. This sounds like a possible issue with the encoding of the file being read or being written to, and not a Blazor specific problem. If you think otherwise, and have a minimal app that reproduces the problem we could investigate. Otherwise, we would recommend posting this question on StackOverflow to reach a broader audience.
