### ISSUE TITLE
Capture Endpoint and RouteValues on IStatusCodeReExecuteFeature

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#35652]
## Background and Motivation
Capture original Endpoint and route values in `IStatusCodeReExecuteFeature`. The same thing has been done for `IExceptionHandlerFeature` in #34205.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Diagnostics
{
    public interface IStatusCodeReExecuteFeature
    {
+       /// <summary>
+       /// Gets the selected <see cref="Http.Endpoint"/> for the original request.
+       /// </summary>
+       Endpoint? Endpoint { get; }

+       /// <summary>
+       /// Gets the <see cref="RouteValueDictionary"/> associated with the original request.
+       /// </summary>
+       RouteValueDictionary? RouteValues { get; }
    }
}
```
## Risks

**Comment by davidfowl** [comment]
How do you think this would be used?

**Comment by Kahbazi** [comment]
> How do you think this would be used?

It gives the ability to create different body based on original endpoint metadata. For example the body for an API endpoint could be different than the body for a razor endpoint.

The original endpoint is being cleared in here 
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesExtensions.cs#L195-L199

**Comment by davidfowl** [comment]
I understand that in theory but, do you have an example of when you would need to do this?

**Comment by Kahbazi** [comment]
> Are you thinking problem details vs html?

Yes this is what I have in mind, when an application is both serving API and html and needs different type of response, but I have to say I don't need this API myself at the moment. I'm just suggesting it in case it might be useful to others.

**Comment by pranavkm** [comment]
**API review**: Make the change non-breaking by making these default interface methods.

```diff
public interface IStatusCodeReExecuteFeature
    {
+       /// <summary>
+       /// Gets the selected <see cref="Http.Endpoint"/> for the original request.
+       /// </summary>
+       public Endpoint? Endpoint { get; }

+       /// <summary>
+       /// Gets the <see cref="RouteValueDictionary"/> associated with the original request.
+       /// </summary>
+       public RouteValueDictionary? RouteValues { get; }
    }
```
