### ISSUE TITLE
UserManager.SetAuthenticationTokenAsync() is not updating an entity

### ISSUE THREAD

**Issue by uhfath** [dotnet/aspnetcore#35656]
I've been studying the [sources](https://github.com/dotnet/aspnetcore/blob/c663adee8e64ba5d379fa0edfb8201984a7df7d0/src/Identity/Extensions.Core/src/UserManager.cs#L2152) for a time and can't figure out why is it not working as expected.
I can see there are even [tests](https://github.com/dotnet/aspnetcore/blob/c663adee8e64ba5d379fa0edfb8201984a7df7d0/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs#L1725) that should identify an issue, but it seems they also pass.

But it just doesn't work for me.
A small repro:
```C#
var user = await userManager.FindByNameAsync(userName);
if (user == null)
{
    ModelState.AddIdentityError(errorDescriber.UserNameOrPasswordIncorrect());
    return Unauthorized();
}

var signInResult = await signInManager.CheckPasswordSignInAsync(user, password, true);
if (!signInResult.Succeeded)
{
    var isBlocked = signInResult is AppSignInResult appSignInResult && appSignInResult.IsBlocked;

    if (signInResult.IsLockedOut || signInResult.IsNotAllowed || isBlocked)
    {
        if (signInResult.IsLockedOut)
        {
            ModelState.AddIdentityError(errorDescriber.UserLockedOut());
        }

        if (signInResult.IsNotAllowed)
        {
            ModelState.AddIdentityError(errorDescriber.UserNotAllowed());
        }

        if (isBlocked)
        {
            ModelState.AddIdentityError(errorDescriber.UserBlocked());
        }
    }
    else
    {
        ModelState.AddIdentityError(errorDescriber.UserNameOrPasswordIncorrect());
    }

    return Unauthorized();
}

var tokenResult = await userManager.SetAuthenticationTokenAsync(user, "Jwt Bearer", "JWT", "456"); // store
var tokenValue = await userManager.GetAuthenticationTokenAsync(user, "Jwt Bearer", "JWT"); // read to test
```
Note that when used for the first time (no tokens been saved previously) it works - token is saved.
Problems occur when there is already a token in database and we need to update it.
The value is not updated and not errors returned.
Event the result is "Success".

Here are the logs after the SetAuthenticationTokenAsync() method:
https://pastebin.com/WNcy6SFW

And here are logs for the GetAuthenticationTokenAsync() call:
https://pastebin.com/NNVR55rz

### Further technical details
- ASP.NET Core version: **5.0.9**
- The IDE: **Visual Studio 2019 (16.11.1)**
- Include the output of `dotnet --info`:
https://pastebin.com/gsPcBJdX

**Comment by uhfath** [comment]
@HaoK, thanks for taking the time.
Sorry for not making it clear in the first post.
Yes, I have checked the database directly as a first step and the data wasn't changing.

I've created a clean new project (NET 5) without anything but the identity part and it seems to work, which is a bit weird to me.
Perhaps there is something with my setup in the main project that interferes with correct database update.
Any ideas what it could be?

In the mean time I'll try to move some parts from main project to test repro and see at which moment it breaks.

**Comment by uhfath** [comment]
@HaoK, I think I've found the source of the issue.
Here is a repro:
https://github.com/uhfath/TestAuthTokens

Just apply migrations before start.
After that in swagger simply use "Values" endpoint, by supplying any user name.

This part is the source of the problem:
https://github.com/uhfath/TestAuthTokens/blob/869bdf9f2f312f65e53fa0760eca6016dbadae43/TestAuthTokens/Startup.cs#L45

I am registering 3 Db context "instances" in DI:
- one for interface to work with data in a read-only mode for parts where no db context is accessible (this is needed in main project for other assemblies).
- one for assemblies which work only with identity db context
- one for normal db context operations

So the problem is the order, I beileve.
If I register interface part first (the one the has QueryTrackingBehavior.NoTracking then there is an issue with SetAuthenticationTokenAsync.
If I register this part second or last, then everything works as expected.

But why does the order matter in this case?
I don't think internal identity parts use my interface from DI so they should be getting "AddDbContext<IdentityDbContext, ApiDbContext>" which has no special setup and should work as expected.

What am I missing here?

**Comment by HaoK** [comment]
I'm not entirely sure why order matters here with the DbContext, @ajcvickers do you have any ideas about whether the behavior due to the order is expected or not?  NoTracking causes issues with identity

**Comment by ajcvickers** [comment]
Yeah, multiple calls to AddDbContext for essentially the same context type won't work. AddDbContext does more than just register the context type; it also registers things like the options. If you want to be able to resolve the same context type via different types from D.I., then call AddDbContext once, and add normal calls to AddScoped, etc. to do the other resolutions that you want. However, I doubt even doing this will allow you to resolve the same context type with different options. You will likely need different derived context types so that the registration of `DbContextOptions<TContext>` can be differentiated by the the `TContext` type.

**Comment by uhfath** [comment]
@ajcvickers, thank you for your explanation. I get the point.
We'll refactor our cases to use correct DI registration.
