### ISSUE TITLE
Request QueryString keys became case-sensitive

### ISSUE THREAD

**Issue by sergiorpvn** [dotnet/aspnetcore#35662]
I'm testing my project on .net6-preview7 to do some tests (it was on .netcore 2.1), and some GET requests from my front-end are failing now. 

The reason is that the query string parameters are now case-sensitive. In some requests, the front-end is sending the parameters with the first letter in uppercase and the parameter on my .net6 backend app is in lowercase, I changed the first letter to lowercase and it worked fine.

I saw on https://github.com/dotnet/aspnetcore/issues/3450 that you intentionally wanted it to be case insensitive, but it seems that it isn't the case anymore

**Comment by Tratcher** [comment]
It's still supposed to be case insensitive. Which API are you using? Can you give an example query string that reproduces this?

The query parser was refactored to use AdaptiveCapacityDictionary, but I see at least two code paths where that might not correctly pass the comparer.
https://github.com/dotnet/aspnetcore/blob/bcdb82d0e97e67f770e5c382b60dadb65d0ebfd5/src/Shared/Dictionary/AdaptiveCapacityDictionary.cs#L79
https://github.com/dotnet/aspnetcore/blob/bcdb82d0e97e67f770e5c382b60dadb65d0ebfd5/src/Shared/Dictionary/AdaptiveCapacityDictionary.cs#L522

**Comment by davidfowl** [comment]
Yikes let’s fix this for rc1 if possible
