### ISSUE TITLE
Add & publish a cm.1 file for each .rpm we ship

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#35725]
Generate and publish each RPM that you currently publish a second time, with cm.1 as part of the distro label
 
Runtime already does this for one file and produces dotnet-runtime-deps-6.0.0-preview.5.21324.12-cm.1-x64.rpm

https://github.com/dotnet/runtime/pull/52924/files

Needs to be done by 9/14

**Comment by epananth** [comment]
Just checking, any update on this? Want to make sure we hit the deadline :)

**Comment by wtgodbe** [comment]
I'm planning on taking care of this this week

**Comment by epananth** [comment]
Just FYI, You will just need this update in your repo -> https://github.com/dotnet/runtime/pull/58465
