### ISSUE TITLE
[debugger][blazor webassembly] Breakpoints on server not hit

### ISSUE THREAD

**Issue by thaystg** [dotnet/aspnetcore#35773]
Copied from https://github.com/dotnet/runtime/issues/57949 where a lot of bugs were reported.

Same behavior on the Blazor but with additional error that breakpoint will not hit.
Once the app has fully loaded , i have to apply the break points and only those breakpoints hits.
I have to reapply on every run(even when i have not changed any code).
again, if i continue from breakpoint it crashes the entire app and i have to start the app all over again.
Blazor Wasm Client side Debugger Breakpoint will not hit and crash on continue

https://1drv.ms/u/s!AtHk7h6Srnk_h9gJzotCWZLKviEQZQ?e=YFkrp7l

@nssidhu

**Comment by mkArtakMSFT** [comment]
@gregg-miskelly do you know who should look into this ? Thanks!

**Comment by danroth27** [comment]
@thaystg Looks like this is a Blazor WebAssembly debugging issue, not a server-side debugging issue. The breakpoint shown in the screen shot is in client-side code. So I think this still needs to be handled in the dotnet/runtime repo.
