### ISSUE TITLE
`Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager` Causing Large Amount of `System.Reactive` Components in Memory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35797]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftCodeAnalysisRazorProjectSys/1507243)._

---
After several hours of development within a solution with Razor Projects and components, I noticed a large amount of memory being consumed.  Taking a look via dotMemory, this appears to be in the form of `System.Reactive` components:

! [](https://i.imgur.com/fheOnPS.png)

Looking at the similar retention path, it appears that `Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager` is involved:

! [](https://i.imgur.com/MEZG83I.png)

Attaching a DMP for review.

---
#### DragonSpark on 8/18/2021, 07:08 AM: 

<p>Tracking/discussion here in aspnetcore repository:<br>
<a target='_blank' href="https://github.com/dotnet/aspnetcore/issues/35451">https://github.com/dotnet/aspnetcore/issues/35451</a></p>

#### Feedback Bot on 8/18/2021, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Fixed indirectly in https://github.com/dotnet/aspnetcore-tooling/pull/4153
