### ISSUE TITLE
HTTP/3: Support client certificates on non-Windows platforms

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#35800]
msquic currently only supports client certificates on Windows. Client cert tests are disabled on non-Windows OSes.

Resolving this issue will probably just involve waiting for msquic to improve its support and then enabling tests.

**Comment by adityamandaleeka** [comment]
Needs msquic and/or SNQuic support

**Comment by rzikm** [comment]
System.Net.Quic should already support this, we even have a unit test for it
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs#L396

**Comment by adityamandaleeka** [comment]
Thanks @rzikm
