### ISSUE TITLE
Blazor WebAssembly authentication relaying on archived oidc-clinet.js

### ISSUE THREAD

**Issue by plachor** [dotnet/aspnetcore#35825]
Hi, it seems that https://github.com/IdentityModel/oidc-client-js is archived and author is intending to close PRs by the end of the year. Are there already any plans for Blazor authentication future?

Additionally in current version it seems that:

2) `userinfo_endpoint` is required when doing authorization_code flow, I will try reconfigure oidcjs to disable `loadUserInfo` but in future do you plan enforcing `userinfo_endpoint` for such flow?

3) oidcjs has reference for outdated [`YUI` library with known vulnerabilities ](https://github.com/IdentityModel/oidc-client-js/issues/1119) so most probably your implementation is also dependent on that component

**Comment by plachor** [comment]
Thanks @javiercn for your quick response and clarification, you want to address **2.** by adding `skipUserInfo` to `AdditionalProviderParameters` of `OidcProviderOptions` in .NET6?

**Comment by plachor** [comment]
One more question, should out of the box solution propagate to Balzor  that session has ended (checkSession endpoint detected that user is no longer authenticated) and complete logout on all opened pages or do we have to add some manual event handling (from `oidcjs`)?

I've opened sample on based on .NET 5 and see in network tab that logout is being processed by `oidcjs` but I do not see any changed of state on Blazor layer. This could be however effect of my customization's.

**Comment by javiercn** [comment]
> Thanks @javiercn for your quick response and clarification, you want to allow control of **2.** by adding `skipUserInfo` to `AdditionalProviderParameters` of `OidcProviderOptions` in .NET6?

We don't plan to make any functional changes to this library in 6.0 other than bug fixes and things like that. At this point in the release we are not planning to add any new features nor public API area surface.

You can completely customize the behavior of the authentication library in two ways:
* Create and use your own AuthenticationService.js file
* Extend the library primitives to alter the behavior.

Note that we provide a library to perform authentication in most common cases and we expect folks to create implementations tailored to their needs for the cases we don't support.

**Comment by plachor** [comment]
I understand your point and had no intention to enforce any changes. I would like to relay on your implantation of `AuthenticationService.js`, just wanted to cross validate my assumption how to extend core behavior. 

Topic of `single logout` is it part of `common cases`, I'm about to call Blazor on `userSignedOut` event to notify that SLO happened ? Or I am missing something and it should work out of the box.
