### ISSUE TITLE
Add return types to DI extension methods in SpaStaticFilesExtensions

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/aspnetcore#35828]
## Background and Motivation

Dependency injection extension methods usually return the relevant builder type to allow easy chaining or convenient expression bodied members. 

## Proposed API

```csharp
namespace Microsoft.Extensions.DependencyInjection
{
    public static class SpaStaticFilesExtensions
    {
        public static IServiceCollection AddSpaStaticFiles(this IServiceCollection services, Action<SpaStaticFilesOptions> configuration = null);
        public static IApplicationBuilder UseSpaStaticFiles(this IApplicationBuilder applicationBuilder);
        public static IApplicationBuilder UseSpaStaticFiles(this IApplicationBuilder applicationBuilder, StaticFileOptions options);
    }
}
```

https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Spa/SpaServices.Extensions/src/StaticFiles/SpaStaticFilesExtensions.cs

**Comment by mkArtakMSFT** [comment]
Closing this as this will be a breaking change and we don't plan to make it.
