### ISSUE TITLE
dotnet watch can be extended

### ISSUE THREAD

**Issue by huunab** [dotnet/aspnetcore#35837]
Hi dotnet team,

is it possible to expose the filter capability to the end users so they customize how different files are handled as well as to allow the communication with other tools during a dotnet watch session?

https://github.com/dotnet/sdk/blob/94c3b563d2fc9b96edd4488c9f81bb1a478dc688/src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs#L37-L42

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do in the near future.
