### ISSUE TITLE
New templates have unnecessary using statement for OpenApi

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#35840]
### Describe the bug
With the change and merge of Program/Startup content for minimal hosting API support, an additional using that still exists is no longer needed due to the use of the new C# language feature and `new()` instead of using `new OpenApiInfo()` in the project file.  This triggers code fixes to show that this using is not needed.

![image](https://user-images.githubusercontent.com/4821/131164439-f65557d4-9f13-467e-8036-ae9f095463b3.png)

Generally we shouldn't emit code that our tools immediately flag as not needed.

### To Reproduce
From VS:
File...New Project...Web API (C#)
Open Program.cs
OBSERVE: Roslyn grays out and lightbulbs the using `Microsoft.OpenApi.Models`

### Further technical details
6.0.100-rc.1.21426.23
VS 2022 Int.Preview 4 (should repro on any VS2022 w/net6 sdk)

**Comment by DamianEdwards** [comment]
Good catch.
@Pilchie OK to target rc.2 for a fix?

**Comment by Pilchie** [comment]
Yes, but the PR needs to either be re-targeted, or use the bot to trigger a backport PR.

**Comment by DamianEdwards** [comment]
OK I'll attempt to drive this in.
