### ISSUE TITLE
Write to response partially instead of all at once

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#35887]
This might not be an issue for `DevelopeExceptionMiddleware` since it's not suppose to be in production but I was wondering if it is better to write to response body partially other than creating a string and writing it at once.

https://github.com/dotnet/aspnetcore/blob/e3230e53729098b8b4e73d19d7b3624542d1339f/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L141-L151

```csharp
await httpContext.Response.WriteAsync(errorContext.Exception.ToString());
await httpContext.Response.WriteAsync(Environment.NewLine);
await httpContext.Response.WriteAsync(Environment.NewLine);
await httpContext.Response.WriteAsync("HEADERS");
await httpContext.Response.WriteAsync(Environment.NewLine);
await httpContext.Response.WriteAsync("=======");
await httpContext.Response.WriteAsync(Environment.NewLine);
foreach (var pair in httpContext.Request.Headers)
{ 
    await httpContext.Response.WriteAsync(FormattableString.Invariant($"{pair.Key}: {pair.Value}"));
    await httpContext.Response.WriteAsync(Environment.NewLine);
} 
```

**Comment by davidfowl** [comment]
Why?

**Comment by Kahbazi** [comment]
> Why?

I don't know. That was my question! :grin: 

I'm wondering if there's a scenario like how the response is created in this middleware, is it better to use `StringBuilder` or to write to the response partially. The only benefit that I could think for writing partially is to prevent the creation of the `StringBuilder.ToString()`.

**Comment by javiercn** [comment]
@Kahbazi thanks for contacting us.

I don't think this makes any meaningful difference specially for a middleware aimed at development

**Comment by Kahbazi** [comment]
> I don't think this makes any meaningful difference specially for a middleware aimed at development

@javiercn How about for `HtmlDirectoryFormatter`?
https://github.com/dotnet/aspnetcore/blob/dd3c972e92d972df88b314efae688cabc3518979/src/Middleware/StaticFiles/src/HtmlDirectoryFormatter.cs#L216-L219

**Comment by davidfowl** [comment]
I don't see the value here.
