### ISSUE TITLE
HttpSysException : Failed to accept a request.

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#35892]
### Describe the bug
I see this exception in the Windows event viewer logs under ".NET Runtime". Level is "error".
Category: Microsoft.AspNetCore.Server.HttpSys.MessagePump
EventId: 5

Failed to accept a request.

Exception: 
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (1229): An operation was attempted on a nonexistent network connection.
   at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestsWorker() 

Is this indicative of client side disconnect? If so, can its level be turned down from "error"?

### Further technical details
- ASP.NET Core version : .NET 6.0, RC1 (6.0.100-rc.1.21420.39)
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
The native method returning this error is HttpReceiveHttpRequest.
https://github.com/dotnet/aspnetcore/blob/867cec475d18892b828ac44a82d74eccfbbb0e49/src/Servers/HttpSys/src/AsyncAcceptContext.cs#L118
https://docs.microsoft.com/en-us/windows/win32/api/http/nf-http-httpreceivehttprequest

**Comment by Tratcher** [comment]
> Most commonly this would occur if you were calling HttpReceiveHttpRequest with a request id, meaning you called previously without a request id and didn’t have a big enough buffer, and the connection for that request was terminated in between the two calls.  

https://github.com/dotnet/aspnetcore/blob/0b9dfa6c04db44734d1fc4f83d87c5f6178b5b93/src/Servers/HttpSys/src/AsyncAcceptContext.cs#L84-L85

We could suppress a sync ERROR_CONNECTION_INVALID result, reset the request id, and issue a new accept.

**Comment by Tratcher** [comment]
Repro:
```
            var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            await socket.ConnectAsync(IPAddress.Loopback, 5000);

            var largeValue = new string('a', 1024);

            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("GET / HTTP/1.1");
            stringBuilder.AppendLine("Host: localhost");
            stringBuilder.Append("1: ");
            stringBuilder.AppendLine(largeValue);
            stringBuilder.Append("2: ");
            stringBuilder.AppendLine(largeValue);
            stringBuilder.Append("3: ");
            stringBuilder.AppendLine(largeValue);
            stringBuilder.Append("4: ");
            stringBuilder.AppendLine(largeValue);
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();

            var request = stringBuilder.ToString();

            socket.Send(Encoding.ASCII.GetBytes(request));

            socket.LingerState = new LingerOption(true, 0);
            socket.Close();
```

Set a break point in AsyncAccetContext.IOCompleted so you can force the race condition between getting the ERROR_MORE_DATA result, the client resetting the connection, and issuing the next call to QueueBeginGetContext with the bigger buffer.
