### ISSUE TITLE
FormatValueAsString() running too often too many times.

### ISSUE THREAD

**Issue by KevinH404** [dotnet/aspnetcore#35908]
FormatValueAsString() runs too many times and it runs for all inputs.
Im crating a custom input text that inherits InputBase<T> and Im overriding both TryParseValueFromString() and FormatValueAsString(). Issue is that on every typed character typed (since event is oninput) FormatValueAsString() runs 4 times and TryParseValueFromString() only once.

![image](https://user-images.githubusercontent.com/12038888/131264054-90c39eb0-199b-4031-813f-b015b00dfe49.png)

This gets worse when having more than one input since typing a character on input one triggers the bahaviour on all inputs:

![image](https://user-images.githubusercontent.com/12038888/131264087-798f2e57-a679-4323-923b-be76f1e4363d.png)

To reproduce this issue I created a brand new Blazor project and the following code:

![image](https://user-images.githubusercontent.com/12038888/131264118-c900d923-943c-44fb-a917-607c0dd1cb37.png)

Index.razor:

![image](https://user-images.githubusercontent.com/12038888/131264151-ec723236-2863-407a-b01a-ebc23458f0d8.png)

Is this the right behavior? Can I prevent this from running on all inputs every time and from running more than once per input? Is this because Im using CurrentValueAsString?

We use those functions to format the input, for example, limit the decimal numbers. If I was to change it to CurrentValue, how could I achieve this.?

- Using .NET 5.0
- Microsoft Visual Studio Community 2019 Version 16.11.1

**Comment by javiercn** [comment]
@KevinH404 thanks for contacting us.

@SteveSandersonMS do you have any thoughts?

In general we don't care about how many times a method is called unless we have specific perf data that indicates its a bottleneck. 

If you have concrete perf-data about this scenario being problematic we would be interested in it.

Note that for us, that means the data shows up in a trace taking a significant (more than 5%) of the time, otherwise it's a micro-optimization we don't consider stacked against the risk of introducing a bug.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by KevinH404** [comment]
@mkArtakMSFT @javiercn will do. I have an example that shows functions are being called several times and triggered for all inputs when modifying just one. I will add a real life example that is giving us trouble (with formatting functions and all). Sorry for the delayed answer I am based in NZ.

**Comment by KevinH404** [comment]
@mkArtakMSFT @javiercn Thanks for your prompt respone. After some further investigation we found out there are other factors at play that impact the performance when typing into inputs. I know this is not what the issue described initially, but we thought that the fact that FormatValueAsString() and TryParseValueFromString() ran so often and so many times was the one to blame.
Thanks again.
