### ISSUE TITLE
Hot reload not working in visual studio 2022 preview

### ISSUE THREAD

**Issue by arvi15** [dotnet/aspnetcore#35902]
Hot reload not working in visual studio 2022 preview
I am using dotenet watch from command prompt
After changing the file it is showing  Hot reload of changes succeeded . But changes are not reflecting in the browser.

Changes will appear only if I restart.
Here for ega I have changed the counter header text .But
![image](https://user-images.githubusercontent.com/23286730/131235455-4af80b20-8ac3-4315-913a-c8c1b4b39a64.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Which specific SDK are you using here and what project type is this ? Blazor WebAssembly by any chance?
We know that this was broken in 6.0 Preview 7 with Blazor Web Assembly. If that's the case, the latest nightly build should have this resolved and you can try it now.

**Comment by arvi15** [comment]
hi,
I am using Blazor WebAssembly  project.
where can I get the e, the latest nightly build.

I downloaded the vs2022 from  https://visualstudio.microsoft.com/vs/preview/#download-preview
and community version

Thanks
Aravind
