### ISSUE TITLE
ClickOnce support for AspNet+WinForm projects (Electron-like)

### ISSUE THREAD

**Issue by JohnKiller** [dotnet/aspnetcore#35935]
### Is your feature request related to a problem? Please describe.
ClickOnce deployment is not supported by project sdk `Microsoft.NET.Sdk.Web`

### Describe the solution you'd like
I would like to publish an ASP.NET core app with ClickOnce in an Electron way

### Additional context
This may be related to Blazor desktop/MAUI. What I would like to do is create an Electron-like application using WebView2 and a React/Angular app hosted on a Windows Forms app, and then publish the bundle with ClickOnce.

If I change the project SDK to `Microsoft.NET.Sdk` then I can publish it, but `npm` never gets called so it doesn't compile.

Is this a supported scenario?

**Comment by javiercn** [comment]
@JohnKiller thanks for contacting us.

We've added support for this recently, it will be available in RC1.
