### ISSUE TITLE
RoleExistsAsync method not working in Identity RoleManager 

### ISSUE THREAD

**Issue by faresamr** [dotnet/aspnetcore#35946]
### Describe the bug
`roleManager.RoleExistsAsync("myRole")` always returns null value as if the role doesn't exist even if its there.

:raised_hands: **I will be glad to contribute a fix for it and check if there is any other methods do the same thing**

This happens because of role name gets normalized twice, first `RoleExistsAsync` normalize the parameter value then pass it to `FindByNameAsync` where it gets normalized for the second time which leads to a normalized value doesn't exists

https://github.com/dotnet/aspnetcore/blob/ad5cc24b163e51b046cfa666a82eaecd194927db/src/Identity/Extensions.Core/src/RoleManager.cs#L229-L238

https://github.com/dotnet/aspnetcore/blob/ad5cc24b163e51b046cfa666a82eaecd194927db/src/Identity/Extensions.Core/src/RoleManager.cs#L318-L327

This case was not covered by unit test because of `UpperInvariantLookupNormalizer` is being used as normalizer which dose not make any deference if the value gets normalized more than once, but my case I'm using hashing

### To Reproduce
```
await roleManager.CreateAsync(new IdentityRole("myRole"));
IdentityRole role = await roleManager.RoleExistsAsync("myRole");
//role is null
```

### Exceptions (if any)
No Exceptions.

### Further technical details
- ASP.NET Core 5.0

**Comment by HaoK** [comment]
Yeah this seems like a legit bug, @faresamr do you want to submit a PR?  We'd take this for 6.0-rc2 I think

**Comment by HaoK** [comment]
Feel free to update the unit tests to use a mutating normalizer to flush out this issue more generally

**Comment by faresamr** [comment]
Yes I can fix it and I will submit a PR today, how can I get access to submit PR?

**Comment by HaoK** [comment]
https://guides.github.com/activities/forking/
