### ISSUE TITLE
SignlalR HubConnectionBuilder cookie&proxy with HttpMessageHandlerFactory

### ISSUE THREAD

**Issue by kofifus** [dotnet/aspnetcore#35958]
I need a forgiving SSL certificate name policy on my SSL connection
I also use a cookie and a proxy

Looking here : https://github.com/dotnet/aspnetcore/issues/14102#issuecomment-535123235

I ended up with:

```
hubConnection = new HubConnectionBuilder()
.WithUrl(url, options => {
  options.Cookies.Add(authCookie); // ??? needed
  options.Proxy = proxy; // ??? needed

  var cookieContainer = new CookieContainer();
  cookieContainer.Add(authCookie);
  options.HttpMessageHandlerFactory = _ => new HttpClientHandler() {
    CookieContainer = cookieContainer,
    Proxy=proxy,
    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
  }; 
  options.WebSocketConfiguration = sockets => {
    sockets.RemoteCertificateValidationCallback = (sender, certificate, chain, policyErrors) => true;
  };
}.Build();
```

I can tell that my app does not work (authenticate) without setting the `CookieContainer` inside `options.HttpMessageHandlerFactory`

But in this case is there still a need to set `options.Cookies` and `options.Proxy` ?

IMO overall this seems very complicated for what is achieved

**Comment by davidfowl** [comment]
I think something like this should work. We pass you our `HttpClientHandler`  instance built up from the options so you can avoid creating a new one if you just need to modify some property on it. We don't expose the `ServerCertificateCustomValidationCallback` (maybe we should), so it could be set like cookies and proxy on the top level options object (cc @BrennanConroy). 

```C#
hubConnection = new HubConnectionBuilder()
.WithUrl(url, options => {
  options.Cookies.Add(authCookie);
  options.Proxy = proxy;

  options.HttpMessageHandlerFactory = handler => {
     if (handler is HttpClientHandler clientHandler)
     {
         clientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
     } 
     return handler;
   };
  options.WebSocketConfiguration = sockets => {
    sockets.RemoteCertificateValidationCallback = (sender, certificate, chain, policyErrors) => true;
  };
}.Build();
```

**Comment by kofifus** [comment]
Thanks @davidfowl , what is the need for `WebSocketConfiguration` ? that is not covered by `ServerCertificateCustomValidationCallback` ?

**Comment by BrennanConroy** [comment]
> We don't expose the `ServerCertificateCustomValidationCallback` (maybe we should)

https://github.com/dotnet/aspnetcore/issues/14427

> what is the need for `WebSocketConfiguration` ? that is not covered by `ServerCertificateCustomValidationCallback` ?

No it isn't, websockets use a different set of options than httpclient. We would like to make it nicer by having a first class option for this callback and we'll flow it to httpclient and websockets for you, see the issue I linked.

**Comment by kofifus** [comment]
It would be great to update or put a remark at https://github.com/dotnet/aspnetcore/issues/14102#issuecomment-535123235 (which is closed for me)

The code there for `HttpMessageHandlerFactory` replaces the handler where as the code here modifies it which is much better.
That comment is referenced in various stackoverflows etc
