### ISSUE TITLE
In-app IHostingStartup instances are not discovered/run when --applicationName is passed via args to WebApplication.CreateBuilder, e.g. from test projects

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#35956]
Using build:
```
SDK 6.0.100-rc.1.21427.28
Host 6.0.0-rc.1.21426.17
Microsoft.AspNetCore.App 6.0.0-rc.1.21427.16
Microsoft.NETCore.App 6.0.0-rc.1.21426.17
```

1. Create an empty web project, e.g. `dotnet new web`
2. Add an `IHostingStartup` class to the project and register it via the assembly attribute:
  ``` c#
  [assembly:HostingStartup(typeof(MyHostingStartup))]
  namespace MyTestWebApp;
  public class MyHostingStartup : IHostingStartup
  {
      public void Configure(IWebHostBuilder builder)
      {
          var test = "Test string";
      }
  }
  ```
3. Debug the web project and ensure that `MyHostingStartup.Configure` is called
4. Add an xUnit test project to the solution, e.g. `dotnet new xunit`
5. Add a reference to the web project to the test project, e.g. `dotnet add reference Path/MyTestProject.csproj`
6. Set internals visible to in the web project so the test project can see internal types, e.g. in the MyTestWebApp.csproj file:
  ``` xml
  <ItemGroup>
    <InternalsVisibleTo Include="MyTestWebApp.Tests" />
  </ItemGroup>
  ```
7. Add a test that uses `WebApplicationFactory` to send a request to the web project, e.g.:
  ``` c#
  using System.Net;
  using Microsoft.AspNetCore.Mvc.Testing;
  using Microsoft.Extensions.DependencyInjection;
  using Microsoft.Extensions.Hosting;
  using Xunit;
  
  namespace MyTestWebApp.Tests
  {
      public class HostingStartupTest
      {
          [Fact]
          public async Task Root_Responds_OK()
          {
              await using var application = new MyWebApplication();
              
              var client = application.CreateClient();
              var response = await client.GetAsync("/");
  
              Assert.Equal(HttpStatusCode.OK, response.StatusCode);
          }
  
          class MyWebApplication : WebApplicationFactory<Program>
          {
              protected override IHost CreateHost(IHostBuilder builder)
              {
                  // Add mock/test services to the builder here
  
                  return base.CreateHost(builder);
              }
          }
      }
  }
  ```
8. Debug the test and see that the `MyHostingStartup.Configure` method is not called

**Comment by davidfowl** [comment]
This is a bug with how early we observe the name specified by the host. We're not observing it in time for the logic that looks at hosting startup to find it in the application assembly instead of the entry assembly.

**Comment by DamianEdwards** [comment]
I wasn't able to repro this in a 3.1 app. Trying 5.0 now.

**Comment by DamianEdwards** [comment]
Doesn't repro in 5.0 app either. Trying a 6.0 app that doesn't use `WebApplication`

**Comment by DamianEdwards** [comment]
Doesn't repro there either. Seems to be just a regression in behavior with the new `WebApplication` API.
