### ISSUE TITLE
UseDeveloperExceptionPage plain-text response should set charset

### ISSUE THREAD

**Issue by garryxiao** [dotnet/aspnetcore#35954]
### Describe the bug
In ASP.NET Core 3.0 and later, the Developer Exception Page displays a plain-text response if the client doesn't request HTML-formatted output. The problem is, when display plain-text response, there is no charset set, just "Content-Type: text/plain" causing garbled when view the text but HTML-formatted output will set with "Content-Type: text/html; charset=utf-8" works.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by rafikiassumaniMSFT** [comment]
@davidfowl  and @halter73 is this something we can address as part of the following issue #35857 ?

**Comment by davidfowl** [comment]
Nope, this is unrelated.

**Comment by adityamandaleeka** [comment]
https://source.dot.net/#Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs,151

We're using WriteAsync which will use utf-8 here. We should update the content-type here.

**Comment by davidfowl** [comment]
Are we gonna backport this fix?

**Comment by halter73** [comment]
We did. https://github.com/dotnet/aspnetcore/pull/36072
