### ISSUE TITLE
Still producing the Readme.md about identity server when creating a Blazor webassembly app with AAD or AAD B2C auth

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#35971]
I thought we addressed this, however as of SDK 6.0.100-rc.1.21430.44 I still see the readme being created when I make a new blazor webassembly app with AAD auth (and potentially other auth types)

**Comment by HaoK** [comment]
Oops, looks like I forgot to backport this to 6.0, its only in main, and I need to add this to the SPA template.jsons too https://github.com/dotnet/aspnetcore/commit/6985c5c8f3d08743870a0f968c9c209ca1316096#diff-146dcb0c4b795775b3c2bfbd104df0b4dafec8d8b51c881dac18a7f3235b0dca

**Comment by HaoK** [comment]
Verified this is fixed now on todays sdk:

`dotnet new blazorwasm -ho` results in no readme.txt

```
6.0.100-rc.2.21451.19 [C:\Program Files\dotnet\sdk]

    Directory: C:\test\blazorwasm\Server


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          9/1/2021   1:40 PM                Controllers
d-----          9/1/2021   1:41 PM                obj
d-----          9/1/2021   1:40 PM                Pages
d-----          9/1/2021   1:40 PM                Properties
-a----          9/1/2021   1:40 PM            127 appsettings.Development.json
-a----          9/1/2021   1:40 PM            151 appsettings.json
-a----          9/1/2021   1:40 PM            545 blazorwasm.Server.csproj
-a----          9/1/2021   1:40 PM            788 Program.cs
```
