### ISSUE TITLE
Add an option to the Web API project template to allow the included content to use Minimal APIs instead of controllers

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#35996]
`dotnet new webapi --minimal` would produce a project that is functionally similar to the existing project the template creates (i.e. the weather API) but implemented with the new MinimalAPIs.

The option should be displayed in the Visual Studio new project dialog experience so that it's easily discoverable when creating projects there.

**Comment by rafikiassumaniMSFT** [comment]
@DamianEdwards  and @LadyNaggaga  will this work replace the need for this NuGet package ? https://github.com/dotnet/aspnetcore/issues/34010

**Comment by DamianEdwards** [comment]
If we end up going with this approach, I'd think yes.
