### ISSUE TITLE
[Feedback] New Razor (ASP.NET Core) editor .editorconfig issues (VS 2022 Preview 3.1)

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#36010]
Backing VSTS issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388770

**Comment by allisonchou** [comment]
Breaking this out into two separate issues and closing out this issue:
https://github.com/dotnet/aspnetcore/issues/36773
https://github.com/dotnet/aspnetcore/issues/36772
