### ISSUE TITLE
Allow more oidc-client options to be set in OidcProviderOptions for Blazor wasm authentication.

### ISSUE THREAD

**Issue by andrew-tevent** [dotnet/aspnetcore#36028]
I am using an OIDC provider that throttles requests to `/userinfo` so I want to be able to disable the Auth process from grabbing that data as I don't require it.

But unfortunately the [OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs) don't expose the oidc-client [loadUserInfo](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/OidcClientSettings.js#L67) boolean setting which could be turned off.

It just needs adding in:

```
[JsonPropertyName("loadUserInfo")]
public bool LoadUserInfo { get; set; }
```

There are [other settings in the oidc-client](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/OidcClientSettings.js#L67) that could maybe be exposed also, such as `clockSkew`.

**Comment by oatsoda** [comment]
Similar to #40286

**Comment by oatsoda** [comment]
Following up on this. 

It's a real maintenance pain to do all this just to change additional options:

1. Keep a copy of the [DefaultOidcProviderOptionsConfiguration](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/DefaultOidcProviderOptionsConfiguration.cs) in to your own `CustomOidcOptionsConfiguration` (regularly checking for updates to the source).
2. Create your own `CustomOidcProviderOptions` derived from `OidcProviderOptions`
3. Change startup from `AddOidcAuthentication` to call:

```
services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<RemoteAuthenticationOptions<CustomOidcProviderOptions>>, CustomOidcOptionsConfiguration>());
services.AddRemoteAuthentication<RemoteAuthenticationState, RemoteUserAccount, CustomOidcProviderOptions>(configure);
```

It feels like it could be a small-ish change to either:

- Create an overload of the `AddOidcAuthentication` which simply allows you to specify your own derived custom Options type.
or
- Add a few additional properties to the existing `OidcProviderOptions`

and this would remove this maintenance overhead of the above

**Comment by mkArtakMSFT** [comment]
This should already be possible: https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#pass-custom-provider-options
