### ISSUE TITLE
ASP.net Core Identity, password settings ignored

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/aspnetcore#36029]
This is a reference to [the same reported issue](https://github.com/dotnet/aspnetcore/issues/21817).

### Describe the bug

The password settings are still ignored. This issue have been on the table several years now (I find the same issue when searching on the net from as early as 2018). @HaoK have answered more than once that this is known, but there is no resolution to the issue, as it still remains the same. There is no workaround presented on how to make the password settings being honored by the UI.

### To Reproduce
From Visual Studio, create a Blazor server app, with Individual accounts authentication type. Then at the program.cs replace the following:
```
builder.Services.AddDefaultIdentity<IdentityUser>(options =>
{
    options.SignIn.RequireConfirmedAccount = true;
})
```
With:
```
builder.Services.AddDefaultIdentity<IdentityUser>(options =>
{
    options.SignIn.RequireConfirmedAccount = true;
    options.Password = new()
    {
        RequireDigit = false,
        RequiredLength = 4,
        RequiredUniqueChars = 0,
        RequireLowercase = false,
        RequireNonAlphanumeric = false,
        RequireUppercase = false,
    };
})
```
And next when the application is running, choose to register a new user. The following text shows up at validation:

`The Password must be at least 6 and at max 100 characters long`

Where the required length is 4 from the password settings.

### Further technical details
- ASP.NET Core version 6
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE Visual Studio 2022 preview 3

**Comment by HaoK** [comment]
cc @blowdart for his thoughts.  

We are aware that the experience for this is suboptimal, but the gist of it is that there's forms validation that occurs at the UI layer which has no knowledge or relation to the identity settings.  Having the UI use the values configured from the identity option layer would be something we would need to add support for

**Comment by jan-johansson-mr** [comment]
@blowdart @HaoK 

Thanks for moving this into the enhancement (next release) to look at. As @HaoK previously have pointed to (by included a [link to the source](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Register.cshtml.cs#L69) code for the model that's used), we do indeed see that the model is prepped with an attribute, pinning the validation as a static behavior. The rationale then was that since this was an attribute, then UI would not care for the password settings - as is quite obvious. A suggestion was to remove the attribute altogether, since the validation is taken care of anyway elsewhere (e.g., alphanumeric characters in password and so on). A suggestion that I think in this case was not too bad.

If the attribute will not be removed, and the UI will continue to not honor the password settings, then what's the path for a workaround? The first thing that pops into my mind is to do the forms myself - and that's fine - but is there another available path also?

**Comment by HaoK** [comment]
You can scaffold the page and change the attribute

**Comment by jan-johansson-mr** [comment]
Thanks @HaoK,

I found the following most helpful [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio) on how to do that.

**Comment by jan-johansson-mr** [comment]
There is one detail though that's interesting when scaffolding. In my case I got the following reported failure from VS 2022 Preview 3: **There was an error running the selected code generator: 'Scaffolding Identity is not supported for web applications with minimal APIs for hosting and routing'**.

Basically, what it means is: use the "old" way of initializing the application. I guess, when that's done, then I may use the added resources from scaffolding with my "new" way of initializing.

**Comment by jan-johansson-mr** [comment]
Unfortunately, the scaffolding explodes with my setup (see my environment dump at the start of this thread) with the following:
```
Finding the generator 'identity'...
Running the generator 'identity'...
The generic type '<>A{00000004}`3' was used with an invalid instantiation in assembly 'm4y3ymrr.l4u, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0() in Microsoft.VisualStudio.Web.CodeGeneration.Core.dll:token 0x6000011+0xec
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in Microsoft.VisualStudio.Web.CodeGeneration.Core.dll:token 0x60000f8+0x490
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args) in Microsoft.VisualStudio.Web.CodeGeneration.Core.dll:token 0x600000e+0x25
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args) in Microsoft.VisualStudio.Web.CodeGeneration.dll:token 0x6000002+0x75
```
