### ISSUE TITLE
Razor Pages Folder doesn't seen to see changes.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36038]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-Pages-Folder-doesnt-seen-to-see-c/1512819)._

---
[severity:I'm unable to use this version]
A Razor Page folder link may have been initially set to:

asp-page="FooInitial/FooActual/blah" 

Folder structure = "Pages/FooInitial/FooActual/blah"

If I then change this to:

asp-page="FooActual/blah" 

Folder structure = "Pages/FooActual/blah"

It always tries to resolve the original:

"FooInitial/FooActual/blah"

I've cleaned then deleted all the relative bin / obj folders. re-ran VS and rebooted. But it always wants to resolve the old folder structure.

It actually resolves the old page "FooInitial/FooActual/blah" even though it isn't there anymore.

I have attached an image that hopefully makes sense.

I know it's not release but this VS is really s*it. I've fixed a few issues from my last posts by assigning this VMWare Virtual Machine 32G of Ram ... 32Gig really. I really think you want to concentrate less on all the cool trendy cra*p and just make it at least fast and usable.

Not a fair comparison I know but VIM and GCC works on Linux in 2G and honestly I would moan at 'it' for speed but not related to this garbage.

...

---
#### Feedback Bot on 8/24/2021, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What is the .NET version that you're using? Can you share the output of `dotnet --info` please?
