### ISSUE TITLE
Add configurations to test matrix

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#36032]
We want to add the following configurations to our test matrix:

- [x] MacOs 12
- [x] Debian 11
- [ ] RHEL 8
- [ ] Fedora 35
- [x] Alpine 3.14
- [x] Windows 11
- [x] Windows Server 2022

And remove the following:
- [x] Debian 9
- [x] RHEL 7
- [x] Fedora 33
- [x] Alpine 3.12
- [x] Windows 7
- [x] Windows 8.1

We'll want to do this in `6` and `main`. CC @dougbu @HaoK @Pilchie @danmoseley 

Notes: 
- RHEL8 - we could use Fedora28, or see if core-eng can spin up a docker image
- Fedora35 - not out yet
- MacOs 12 - OSX.1200.Arm64.Open is the only queue, safe to use?
- Server 2022 - Don't think we have a pool yet
- Alpine 3.14 image doesn't work with Playwright:
> /root/helix/work/workitem/e/.nuget/playwrightsharp/0.192.0/build/netstandard2.0/PlaywrightSharp.targets(18,5): error MSB3073: The command "./playwright.sh install" exited with code 127.

https://github.com/dotnet/core-eng/issues/14309 tracks Server 2022
https://github.com/dotnet/core-eng/issues/13921 tracks MacOs 12/other new hardware

These changes should get backported to 6.0 as we make them.

**Comment by Pilchie** [comment]
> Windows Server 2012

I think we are still supporting this for .NET 6, so I don't see the need to remove it.

**Comment by wtgodbe** [comment]
List updated

**Comment by danmoseley** [comment]
Did you end up making any distinction between PR validation and nightly validation? In dotnet/runtime we're hoping to mix those up to get more coverage with fewer runs. This assumes your tests run are essentially the same. It could be a signficant win. Eg., you could test Server 2012 on PR and Server 2022 on nightly, and if it's very rare there's a bug unique to one of them, you have good protection with half the machine time.

**Comment by dougbu** [comment]
> Did you end up making any distinction between PR validation and nightly validation?

We already have such a distinction and multiple pipelines with different Helix configurations. We generally only run PR validation on build agents (when Helix doesn't work -- yet) and chosen / common Linux, macOS, and Windows Helix agents: Ubuntu 18.04, OSX 10.14, and Windows 10. (Slight wrinkle in that we run quarantined tests on Fedora 34.)

Not planning to expand our resource usage in PRs.

**Comment by dougbu** [comment]
@wtgodbe when you get back, please update this issue and move it into the appropriate milestone
