### ISSUE TITLE
"C# 10(preview) + ASP.NET Core Web App (.NET 6.0) + AppendTargetFrameworkToOutputPath=False" produce compilation error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36039]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-10preview--ASPNET-Core-Web-App-/1516151)._

---
[severity:It bothers me. A fix would be nice]
1. Create ASP.NET Core Web App Project (.NET 6)
2. Set LangVersion to preview
3. Set AppendTargetFrameworkToOutputPath=False

```
<Project Sdk="Microsoft.NET.Sdk.Web">

<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>
```

4. Then build it, you can't miss it these errors,

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\temp\WebApplication1\WebApplication1\obj\Debug\**net6.0**\StaticWebAssets.build.json'.

Could not find a part of the path 'C:\temp\WebApplication1\WebApplication1\obj\Debug\**net6.0**\StaticWebAssets.build.json'.
```

Because of AppendTargetFrameworkToOutputPath==False, StaticWebAssets.build.json file path shouldn't include "net6.0"

---
#### Feedback Bot on 8/29/2021, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This has been fixed already and will be part of the upcoming 6.0-rc1 release.
