### ISSUE TITLE
Not able to receive values from Route and Body in a POST call

### ISSUE THREAD

**Issue by mdmoura** [dotnet/aspnetcore#36063]
On an Asp.Net Core 5.0 project I have the `ApiController` route and Model:

    [HttpPost("users/{userId:int}/confirm-email")]
    public async Task<IActionResult> ConfirmEmail(Model model) { }

    public class Model { 
      [FromRoute] public Int32? UserId { get; set; }
      [FromQuery] public String Token { get; set; } 
    }

**Result:** I got what I expected ...  
      
    UserId = 10
    Token = "ABC"

I tried receive the token in the Body and not in the query parameter:

    public class Model { 
      [FromRoute] public Int32? UserId { get; set; }
      [FromBody] public String Token { get; set; } 
    }

In this case I got the error:

    "errors": {
      "$": [
        "The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1."
      ]
    }

I used Insomnia.Rest to call the API and the body is:

    {
	  "token": "ABC"
    }

Then I tried to add `[FromBody]` to Controller action:

    [HttpPost("users/{userId:int}/confirm-email")]
    public async Task<IActionResult> ConfirmEmail([FromBody]Model model) { }

    public class Model { 
      [FromRoute] public Int32? UserId { get; set; }
      [FromBody] public String Token { get; set; } 
    }

**Result:** I got the token from body but now userId is null.  
    
    UserId = null
    Token = "ABC" 

I have been trying a few variations but I can't figure out what is happening.

I also tried to call the API from Angular and the result is the same.

Am I missing something or is this a bug?

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by pranavkm** [comment]
MVC will infer that your parameter is bound from body [since it's a complex type](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#binding-source-parameter-inference). It does not look at nested properties while making this inference. You could apply the `[ModelBinder]` attribute on the property to prevent this inference at which point your properties should get correctly bound.

**Comment by lixaotec** [comment]
Im on the same situation... :(

@pranavkm could not get your tip. can you post an example, please?

**Comment by lixaotec** [comment]
reference to the subject in details, and a (not wished workaround third part)
https://www.seeleycoder.com/blog/mixed-model-binding-aspnetcore/
