### ISSUE TITLE
Control browserlink port or disable aspnetcore-browser-refresh.js

### ISSUE THREAD

**Issue by Ponant** [dotnet/aspnetcore#36085]
In .Net 6 Preview 7 (VS 2022), I have a razor page web app for customers that applies content security policy. The browser refresh works if I include connect-src in the policy. However, I would like to know:

-Is there a possibility to predict the port for the browser link, wss? I do not see it in launchsettings.json.
-Is there a way to disable this connection entirely, i.e. no broswer-refresh, no sockets etc?
-More  generaly, the RP webapp seems to inject from _framework, where can this be controlled?
Thank you

**Comment by mkArtakMSFT** [comment]
@jodavis, @BillHiebert do you guys have answers for these questions?

//cc @pranavkm

**Comment by mkArtakMSFT** [comment]
Ping @BillHiebert

**Comment by BillHiebert** [comment]
You can turn off support by seting this Tools\Option to false:

![image](https://user-images.githubusercontent.com/1553785/132394910-7cb32b85-c065-489f-82ff-e410d813c868.png)

**Comment by Ponant** [comment]
Thank you @BillHiebert , is the port for wss randomly chosen or can we get a hold of it?
