### ISSUE TITLE
Microsoft.Extensions.Caching.StackExchangeRedis disposing connections while in use

### ISSUE THREAD

**Issue by antonioortizpola** [dotnet/aspnetcore#36092]
### Describe the bug
As stated here https://github.com/StackExchange/StackExchange.Redis/issues/1498

> Getting the following error randomly - generally have to kill one of the web instances to "fix" it
> Any ideas, is this fix in a new version?
> 
> Key was: GBHCVTWO-PC:CASHWEB:900:PCP-1033346:0606:1.00:636821095169080876 System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'RD0003FF6F2022'.
> at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server)
> at BusinessObjects.Caching.RedisCacheProvider.StringSet(String key, String value, Nullable`1 expiry)
> at BusinessObjects.Caching.RedisCacheProvider.SetWithExpiry[T](String key, T value, TimeSpan expiration)
> 
> Exception: Cannot access a disposed object.
> Object name: 'RD0003FF6F2022'.
> Source: StackExchange.Redis

**Comment by adityamandaleeka** [comment]
Triage: Can you please provide a repro for this behavior so we can investigate? Is it happening during shutdown?
