### ISSUE TITLE
Performance issue on for / loop in Blazor WASM

### ISSUE THREAD

**Issue by VengateshManiraj** [dotnet/aspnetcore#36095]
I am facing a huge performance issue in Blazor WASM compare to Blazor Server.

      List<DateCollection<T>> events = new List<DateCollection<T>>();
 **events** having 3000 records.

            System.Diagnostics.Stopwatch watch1 = System.Diagnostics.Stopwatch.StartNew();
            for (int i = 0; i < events.Count; i++)
            {
                DateCollection<T> tempData;
                for (int j = i + 1; j < events.Count; j++)
                {
                    if (events[i].StartTime == events[j].StartTime)
                    {
                        var firstDuration = events[i].EndTime.Ticks - events[i].StartTime.Ticks;
                        var secondDuration = events[j].EndTime.Ticks - events[j].StartTime.Ticks;
                        if (firstDuration < secondDuration)
                        {
                            tempData = events[i];
                            events[i] = events[j];
                            events[j] = tempData;
                        }
                    }
                }
            }
            Console.WriteLine("Sorting time: " + watch1.ElapsedMilliseconds + " ms");
        
**Output:**

In Server: **Sorting time: 109 ms**
In WASM: **Sorting time: 4964 ms**

This loop executes in the Server app within **109ms**.

But the same loop will take **4964ms** to execute in WASM app.

Is there any possible solution to improve the performance here?

**Comment by javiercn** [comment]
@VengateshManiraj thanks for contacting us.

Looks like you are trying to sort the items. I would suggest you use `List.Sort` for that, see [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.sort?view=net-5.0#System_Collections_Generic_List_1_Sort_System_Comparison__0__)

Changing the sorting algorithm will have the most impact.
