### ISSUE TITLE
Find if session is expired with HttpContext

### ISSUE THREAD

**Issue by gabrielbeauchemin** [dotnet/aspnetcore#36090]
### Is your feature request related to a problem? Please describe.
I would like to be able to get if the session is expired with HttpContext. For now, the only way I find is:

`AuthenticateResult result = await HttpContext.AuthenticateAsync();
            return result.Failure is not null &&
                 result.Failure.Message.Equals("ticket expired", StringComparison.OrdinalIgnoreCase);`

I need with this solution to depend on the hardcoded string: "Ticket expired". This string is hardcoded in this file of your repo: https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L180

### Describe the solution you'd like
I would like to be able to get if the session is expired with HttpContext in a non hacky way. The fear I have is that you change the hardcoded string "Ticket expired" in your code base which would break functionalities in my program.

**Comment by blowdart** [comment]
I assume you meant authentication session, rather than, well, session session?

Can I ask why you want to check it? Generally we haven't seen scenarios where folks need to look at exact reasons as a fail in this case just triggers re-auth in the normal flow.

**Comment by poveilleux** [comment]
@blowdart Yes, he meant authentication session. The idea is when the authentication ticket (or user session if you prefer) expires, we redirect to the login page, but show a toast-like notification saying "Session timeout.". We wanted to leverage the built-in expiration of the authentication ticket to do this. This is a requirement from our UX team.

That's the way we found to achieve this, but maybe you know a better way to achieve this 😊

**Comment by blowdart** [comment]
The problem here I believe is the ticket is attached to the context, otherwise it wouldn't flow. Even the cookie is off the request, which is turn is off the context. @HaoK any clever ideas here?

**Comment by poveilleux** [comment]
The ticket is indeed present on the request when we end up getting the `"Ticket expired"` message. But the authentication could have failed for various reasons, like the data protected ticket is found invalid and not just because of the expired ticket. We cannot get the expiration from the authentication ticket when it is expired because the `IAuthenticationService` won't give it to us. I guess we'll wait on Hao's clever ideas!

**Comment by HaoK** [comment]
I guess another maybe less hacky option would be to have your ITicketStore's RemoveAsync implementation put something in the request marking whether it has removed anything so you could check that to detect expiration.  Otherwise you probably have to do something like derive your own CookieHandler and tweak things.

**Comment by poveilleux** [comment]
I'll be trying that this week, I'll keep this issue updated.

**Comment by poveilleux** [comment]
I tried the `ITicketStore` approach, but I would have to implement every method and also have a backing database to store all user sessions and I did not want to go that route just yet.

I will update once I have made the custom handler work.

**Comment by poveilleux** [comment]
Alright, I was able to create a custom handler based on the `CookieAuthenticationHandler` which will is able to determine in a cleaner way if a given user session has timed out.
```cs
public class SessionTimeoutCookieAuthenticationHandler : CookieAuthenticationHandler
{
    public SessionTimeoutCookieAuthenticationHandler(IOptionsMonitor<CookieAuthenticationOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock)
        : base(options, logger, encoder, clock) { }

    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        AuthenticateResult result = await base.HandleAuthenticateAsync();

        if (result.Failure is not null)
        {
            string? cookie = Options.CookieManager.GetRequestCookie(Context, Options.Cookie.Name!);
            if (!string.IsNullOrEmpty(cookie))
            {
                AuthenticationTicket? ticket = Options.TicketDataFormat.Unprotect(cookie, GetTlsTokenBinding());
                if (ticket is not null)
                {
                    DateTimeOffset currentUtc = Clock.UtcNow;
                    DateTimeOffset? expiresUtc = ticket.Properties.ExpiresUtc;

                    if (expiresUtc != null && expiresUtc.Value < currentUtc)
                    {
                        Context.Items.Add("SessionExpired", true);
                    }
                }
            }
        }

        return result;
    }

    private string? GetTlsTokenBinding()
    {
        byte[]? binding = Context.Features.Get<ITlsTokenBindingFeature>()?.GetProvidedTokenBindingId();
        return binding == null ? null : Convert.ToBase64String(binding);
    }
}
```

**Comment by HaoK** [comment]
Glad to hear @poveilleux

**Comment by poveilleux** [comment]
Also, for those wondering how to inject the custom authentication handler, here's how I did it
```cs
private static AuthenticationBuilder AddSessionTimeoutCookie(this AuthenticationBuilder builder, string authenticationScheme, Action<CookieAuthenticationOptions> configureOptions)
{
    builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<CookieAuthenticationOptions>, PostConfigureCookieAuthenticationOptions>());
    builder.Services.AddOptions<CookieAuthenticationOptions>(authenticationScheme).Validate(o => o.Cookie.Expiration == null, "Cookie.Expiration is ignored, use ExpireTimeSpan instead.");
    return builder.AddScheme<CookieAuthenticationOptions, SessionTimeoutCookieAuthenticationHandler>(authenticationScheme, null, configureOptions);
}
```
