### ISSUE TITLE
An item with the same key has already been added. Key: Content-Language when using UseRequestLocalization and UseStatusCodePagesWithReExecute

### ISSUE THREAD

**Issue by alexandrejobin** [dotnet/aspnetcore#36105]
When I use `UseRequestLocalization` and `UseStatusCodePagesWithReExecute` in the app, I get the error `An item with the same key has already been added. Key: Content-Language`.

The bug occur if I set `ApplyCurrentCultureToResponseHeaders = true` during the configuration because it set the `Content-Language` in the response header. Since that UseStatusCodePagesWithReExecute reexecute the request, the UseRequestLocalization try to add the `Content-Language` response header again and throw an `ArgumentException`.

### To Reproduce
Simply use this configuration and call a fake webpage like /abc/def.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    services.AddRequestLocalization(options =>
        {
            // Set the supported cultures
            var supportedCultures = new List<CultureInfo>
            {
                new CultureInfo("en-CA")
            };

            options.DefaultRequestCulture = new RequestCulture("en-CA");
            options.SupportedCultures = supportedCultures;
            options.SupportedUICultures = supportedCultures;

            options.ApplyCurrentCultureToResponseHeaders = true;
        });
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
        // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
        app.UseHsts();
    }
    app.UseHttpsRedirection();
    app.UseStatusCodePagesWithReExecute("/Home/HttpError", "?statusCode={0}");
    app.UseStaticFiles();
    app.UseRequestLocalization();
    app.UseRouting();

    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

### Exceptions
```
System.ArgumentException: An item with the same key has already been added. Key: Content-Language
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.HttpSys.Internal.HeaderCollection.Add(String key, StringValues value)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.StatusCodePagesExtensions.<>c__DisplayClass6_0.<<UseStatusCodePagesWithReExecute>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET Core version 5.0.9
- VS 2019

**Comment by Tratcher** [comment]
Middleware should not call Add, they should use one of the Set operations.

This was already fixed in .NET 6:
https://github.com/dotnet/aspnetcore/blame/cc5f8968e74c9ea2224b578d269e4bb3a2b0b085/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs#L130

**Comment by davidfowl** [comment]
Should we backport this fix?

**Comment by alexandrejobin** [comment]
I see that it's a very little fix to apply to Core v5 and it will not break anything. It would be great to have have it backported to the v5 branch.

**Comment by Tratcher** [comment]
It's hard to say how common this is, neither of these are default middleware and UseStatusCodePagesWithReExecute has especially low usage.

Note the fix would be slightly different in 5.0, the 6.0 fix used new APIs.

**Comment by davidfowl** [comment]
How do you work around this in .NET 5 and 3.1?

**Comment by alexandrejobin** [comment]
For me, I've just decided to put options.ApplyCurrentCultureToResponseHeaders = false until it's fixed. I don't need my http response to have this value for now but in the future, it would probably be good to have a good http response well documented with the Content-Language property set.

**Comment by alexandrejobin** [comment]
Just curious, you say that `UseStatusCodePagesWithReExecute` have low usage. How do people are managing the 404 or the other error codes? Nobody are showing a web page for those errors?

**Comment by davidfowl** [comment]
I don't know that we have data on usage of `UseStatusCodePagesWithReExecute`, I think that was just speculation.

**Comment by Tratcher** [comment]
Try this:
```
            app.UseStatusCodePagesWithReExecute("/Home/HttpError", "?statusCode={0}");
            app.UseStaticFiles();
            app.Use(async (context, next) =>
            {
                await next();
                if (!context.Response.HasStarted)
                {
                    context.Response.Headers.Remove(HeaderNames.ContentLanguage);
                }
            });
            app.UseRequestLocalization();
            app.UseRouting();
```
