### ISSUE TITLE
PageTitle component breaks in .NET 6 RC1 Blazor Server after hot reload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PageTitle-component-breaks-in-NET-6-RC1/1517456)._

---
The new PageTitle Blazor component in .NET 6 RC1 sets that HTML title for the current page. PageTitle is now included in the default Blazor Server template. If I create a new Blazor Server app in VS2022 Preview 4, the PageTitle component works fine when I first run the app, but it stops working after I hot reload a change to the UI. Instead of setting the page title, it renders as content on the page.

Repro steps:

- Install VS2022 Preview 4 (Version 17.0.0 Preview 4.0 [31626.483.main])
- Install .NET 6 RC1 (6.0.100-rc.1.21424.1)
- Create a new Blazor Server app
- Run it without debugging
- The app launches in the browser with the correct page title
- Edit Index.razor to change the content of the h1
- Click Apply Code Changes to hot reload the change

Expected result:
- The UI change is applied and the page title is still correct

Actual result:
- The UI change is applied, but the page title now renders as content instead of updating the HTML title.

! [image.png] (https://aka.ms/dc/image?name=B9412c997c97949529bd7d37aed13922b637659467601313822_20210830-115919-image.png&tid=9412c997c97949529bd7d37aed13922b637659467601313822)

Workaround:
- Use `dotnet watch`, which doesn't appear to have this issue.

Note that @tmat looked at this in VS, and it looks like the correct delta is being applied.

---
#### Feedback Bot on 8/31/2021, 02:10 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/31/2021, 11:04 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by danroth27** [comment]
This appears to be an issue with any component not in the app assembly. The component tag renders as content. I.e PageTitle shows up in the source.

**Comment by SteveSandersonMS** [comment]
If that's the case, it's deep in hot reload internals.

@pranavkm would be better to look into it, but I know he's quite busy. Pranav, is there any other applicable work you want to trade with me?

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck Removing you as I know you have other things to look into, and this seems definitely not to be an issue with `PageTitle` itself.

**Comment by SteveSandersonMS** [comment]
@pranavkm I've moved the assignment to you, because both RSG and hot reload are your areas. But let's sync up about it in case you think it's impractical to cover it this week, or if there's some other work I could take off your list. Alternatively I'm happy to spend some time on this tomorrow myself but would need to talk with you in some detail to get context on the whole flow.

**Comment by dougbu** [comment]
@mkArtakMSFT @pranavkm is RC1 correct for this issue❔ It remains open while the release is closed.

**Comment by mkArtakMSFT** [comment]
This has been fixed with the release of the VS 17 Preview4.1 patch: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.0.0-pre.4.1
