### ISSUE TITLE
Render Fragments Under Visual Studio 2022 Not Showing Up Under Intellisense

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#36120]
When I use visual studio 2022 and I am using a component that uses render fragments but not ChildContent, then after I use the tag for the component, the names are not showing up under intellisense.
Worked fine with Visual studio 2019 when not using the preview editor.
Would be worse if there was no way of showing the intellisense for the render fragments too when using razor components that use render fragments.  Its very common that if a razor component has more than one render fragment, then obviously childcontent which is default won't work so they have to be specified but without intellisense, hurts productivity.

**Comment by allisonchou** [comment]
Related to https://github.com/dotnet/aspnetcore/issues/36121.
