### ISSUE TITLE
Razor tag auto-completion still auto-closes if a tag already has an end-tag.

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#36125]
The first major bug is if a person for example had this code
<div>
</div>

and they edit the code for the div and reenter the > then it shows the </div> even though it was already there (which is wrong).

This happens with all html and razor components.

The second major bug is for razor components when choosing a parameter and I tab, its not entering the = and the 2 " signs with the cursor in the middle.

Those 2 things did not happen with visual studio 2019 when not using the preview editor.  If there was an option to use the old editor, then a person can either choose the new editor even though the intellisense has lots of problems or use the old version where the intellisense works but does not have newer features.

**Comment by allisonchou** [comment]
Related to https://github.com/dotnet/aspnetcore/issues/36121.

**Comment by NTaylorMullen** [comment]
@mikadumont this is another issue in regards to the lackign ="|" completion

**Comment by NTaylorMullen** [comment]
@musictopia2 thanks for the report! I'm re-purposing this issue to handle your first issue about tags auto-closing in unexpected scenarios. As for your second issue that's being tracked here: https://github.com/dotnet/aspnetcore/issues/30747
