### ISSUE TITLE
[BLAZOR WASM] Lagging textarea binding with large amount of text

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#36138]
It's actually still a problem.
An issue with this tile was closed before.
In my case I wasn't using input binding, in my experience I just put a textarea in blank page without blazor and it lags

**Comment by Xyncgas** [comment]
I am not even talking about, well exchanging large amount of data between wasm-land and dom is of course insanely slow, but the html textarea itself is lagging when you put a lot of text which kinda breaks the purpose of a text editor, notepad doesn't have problems editing 1GB file after loading it, so does visual studio code, so I think there's a bug in textarea.
Since edge is a microsoft product, since blazor would benefit from this issues too (this problem gets worst when you try to do anything in blazor with textarea including listening onkeyup which just return the key from the event instead of the entire text input), I hope this can be fixed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This limitation is not Blazor specific. We recommend filing this issue through browser feedback submission channel so the the appropriate owners find this.
