### ISSUE TITLE
ApiExplorer is useless

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/aspnetcore#36140]
### Is your feature request related to a problem? Please describe.
I have spent 10 minutes at making ApiExplorer work in my case for absolutely NOTHING because it refuses to work with MVC apps. Now I gotta make a good old Singleton to replace this useless garbage of ApiExplorer.

### Describe the solution you'd like
I want to propose to make ApiExplorer usefull by 2 points:
- Allow storing a DisplayName in ApiExplorerModel
- Allow ApiExplorer to be used with conventional routing

**Comment by davidfowl** [comment]
When you say you want it to work for MVC apps, what do you mean? Can you be a bit more specific about what you tried, what happened as a result and what you expected to happen?

**Comment by Yuri6037** [comment]
I tried to make a dynamic menu which as it's name implies is dynamically generated from the list of all controllers and actions in each controller.

**Comment by davidfowl** [comment]
I believe you, but if you want to make progress here you need to help us with more specifics. Maybe a sample project that demonstrates what you were doing and how you were able to fix it would be helpful.

**Comment by Yuri6037** [comment]
I will try to describe a bit more what I did:
- I made a Menu ViewComponent for an Asp.Net Core MVC project, the view component just renders a nav.
- The computer receives as input a list of all controllers and for each controller a list of actions. For each controller and action the component requires the route name and the DisplayName as given by some DisplayName attributes used to annotate all controllers and action methods.
- My problem was related to obtaining the data from all controllers in the application and transfering all data to the ViewComponent.
- I searched in the doc for ASP.NET Core and almost immediately found this ApiExplorer thing. I've implemented an IApplicationModelConvention in order to enable ApiExplorer for each controller and passing the required information through the Properties Dictionary in Action due to the fact no Properties property is present in the ApiExplorerModel.
- As soon as I tried to run the application with the new IApplicationModelConvention added to my MVC options, I reached an Asp.Net core runtime error which told me I had enabled ApiExplorer but my controllers uses conventional routing. I've searched the error on internet and found out why: ApiExplorer is basically useless in MVC apps because the default of MVC is to use conventional routing (no Route attribute).
- Following that result, I had the choice of rewriting all controllers, and due to the amount of controllers this is a big NO or the second choice was to make a singleton class that I can access through MyFixedUsefulApiExplorer.Instance and allowed me to globally store the information of all controllers and actions as I noticed that dispite ApiExplorer to be "unsupported" I could still list all actions and controllers without any problem in IApplicationModelConvention. So I just replaced the broken ASP.Net Core's ApiExplorer by my singleton and could transfer the data from IApplicationModelConvention to the ViewComponent which can then process and render the nav accordingly.

**Comment by pranavkm** [comment]
ApiExplorer is focused towards APIs, it's not well suited for building a map UI-centric actions. Getting the list of ActionDescriptors or RouteEndpoint might be one way to go about it. Here's a snippet of how the dotnet.microsoft.com website produces this:

```C#
public class SitemapService
{
    private IActionDescriptorCollectionProvider _actions;

    private Sitemap BuildSitemap()
    {
        var result = new Sitemap
        {
            Pages = _actions.ActionDescriptors.Items
                .OfType<ControllerActionDescriptor>()
                ...
                .Select(a => new { Action = a, TemplateUrl = BuildTemplateUrl(a) })
                .SelectMany(a => ExpandTemplateUrl(a.TemplateUrl, a.Action, _services))
                .Select(u => new Sitemap.SiteUrl { URL = u.ToLowerInvariant() })
                .ToList()
        };
        
        // ...

        return result;
    }
    
    private static string BuildTemplateUrl(ControllerActionDescriptor action)
    {
        var url = new StringBuilder(BaseUrl);
        if (action.RouteValues["controller"] != "Home")
        {
            url.Append("/");
            url.Append(action.RouteValues["controller"]);
        }

        if (action.RouteValues["action"] != "Index")
        {
            url.Append("/");
            url.Append(action.RouteValues["action"]);
        }

        foreach (var parameter in action.Parameters)
        {
            url.Append("/{");
            url.Append(parameter.Name);
            if (!parameter.ParameterType.IsValueType || Nullable.GetUnderlyingType(parameter.ParameterType) != null)
            {
                url.Append("?");
            }
            url.Append("}");
        }

        return url.ToString();
    }
}
```
