### ISSUE TITLE
Cannot programmatically reload configuration at runtime with WebApplicationBuilder

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36181]
### Describe the bug

An application that uses `WebApplicationBuilder` and attempts to reload the configuration at runtime via `IConfigurationRoot.Reload()` will not observe changes to the application's configuration.

This appears to be due to the way that the configuration sources/builders are layered in `WebApplicationBuilder`, which results in the configuration sources being wrapped inside an `ChainedConfigurationProvider` instance, which has a `Load()` implementation that is a no-op ([source](https://github.com/dotnet/runtime/blob/2a1eaa2ca6db40c72febe840cea1977490c7d0b8/src/libraries/Microsoft.Extensions.Configuration/src/ChainedConfigurationProvider.cs#L65)).

![image](https://user-images.githubusercontent.com/1439341/132096153-1c91517a-5af0-42fa-934b-d695c89c4bc2.png)

This results in the underlying configuration sources containing the data not having their `Load()` methods called, resulting in the application effectively not actually reloading the configuration despite `Reload()` being called on the configuration root.

### To Reproduce

I repurposed the existing [`SimpleWithWebApplicationBuilderTests`](https://github.com/dotnet/aspnetcore/blob/39b54a3785bc69acb521cb0e96421074b19ea9e5/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs#L17) test class to create the repro below.

Using just `IConfigurationRoot.Reload()` the custom configuration source is never reloaded.

If the application walks the root and its providers and reaches into the chained configuration source using reflection to manually reload the underlying `IConfiguration`, the source is reloaded and the value returned by the GET method changes.

The test case where `reload = false` fails with a message similar to the following:

```
 Microsoft.AspNetCore.Mvc.FunctionalTests.SimpleWithWebApplicationBuilderTests.Can_Reload_Configuration(force: False)
   Source: SimpleWithWebApplicationBuilderTests.cs line 24
   Duration: 1.5 min

  Message: 
Assert.NotEqual() Failure
Expected: Not "f51a7fcf-e830-45a0-a575-e87f22c4e444"
Actual:   "f51a7fcf-e830-45a0-a575-e87f22c4e444"

  Stack Trace: 
SimpleWithWebApplicationBuilderTests.Can_Reload_Configuration(Boolean force) line 40
--- End of stack trace from previous location ---
```

#### `Program.cs`

```csharp
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

(builder.Configuration as IConfigurationBuilder).Add(new RandomConfigurationSource());

builder.Services.AddControllers();

var app = builder.Build();

app.MapGet("/configuration/random", (IConfiguration config) => config["Random"]);
app.MapPost("/configuration/reload", (bool force, IConfiguration config) =>
{
    var root = (IConfigurationRoot)config;
    root.Reload();

    // The configuration can be forced to reload by using reflection to walk the chain and reload the child root(s)
    if (force)
    {
        foreach (var provider in root.Providers)
        {
            if (provider is ChainedConfigurationProvider chained)
            {
                var field = typeof(ChainedConfigurationProvider).GetField(
                    "_config",
                    BindingFlags.Instance | BindingFlags.NonPublic);

                var inner = (IConfiguration)field!.GetValue(chained)!;

                if (inner is IConfigurationRoot childRoot)
                {
                    childRoot.Reload();
                }
            }
        }
    }

    return Results.NoContent();
});

app.Run();

public class RandomConfigurationSource : IConfigurationSource
{
    public IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return new RandomConfigurationProvider();
    }
}

public class RandomConfigurationProvider : ConfigurationProvider
{
    public override void Load()
    {
        Data["Random"] = Guid.NewGuid().ToString();
    }
}
```

#### `SimpleWithWebApplicationBuilderTests.cs`

```csharp
using System.Net;
using System.Net.Http;

namespace Microsoft.AspNetCore.Mvc.FunctionalTests;

public class SimpleWithWebApplicationBuilderTests : IClassFixture<MvcTestFixture<SimpleWebSiteWithWebApplicationBuilder.FakeStartup>>
{
    private readonly MvcTestFixture<SimpleWebSiteWithWebApplicationBuilder.FakeStartup> _fixture;

    public SimpleWithWebApplicationBuilderTests(MvcTestFixture<SimpleWebSiteWithWebApplicationBuilder.FakeStartup> fixture)
    {
        _fixture = fixture;
        Client = _fixture.CreateDefaultClient();
    }

    public HttpClient Client { get; }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Can_Reload_Configuration(bool force)
    {
        // Arrange
        var before = await Client.GetStringAsync("http://localhost/configuration/random");

        Assert.NotNull(before);
        Assert.NotEmpty(before);

        // Act
        var response = await Client.PostAsJsonAsync($"/configuration/reload?force={force}", new { });

        await response.AssertStatusCodeAsync(HttpStatusCode.NoContent);

        // Assert
        var after = await Client.GetStringAsync("http://localhost/configuration/random");

        Assert.NotEqual(before, after);
    }
}
```

### Further technical details

- ASP.NET Core version - this repo at commit 39b54a3785bc69acb521cb0e96421074b19ea9e5.

**Comment by martincostello** [comment]
Yeah I wasn't sure if the root cause would be the way it was being used here, or something over in runtime, so I figured I'd start off here as it was easier to stand-up the repro.

**Comment by davidfowl** [comment]
I understand the issue and it could be fixed in either place (and might still be) but this does seem like a gap in the chained configuration provider https://github.com/dotnet/runtime/issues/58683.

I'll take a look.
