### ISSUE TITLE
Add MapPatch overloads to routing

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#36198]
## Background and Motivation

Today we have shortcuts for the most common HTTP methods for route handling (GET, POST, PUT, DELETE) but we don't have PATCH (or OPTIONS, TRACE, HEAD). We should add MapPatch to the set of methods we support. MapPatch is also interesting because people can now write custom binders in minimal APIs to handle the body. Today calling MapMethods(..) is the workaround (https://github.com/felipeoriani/MinimalBlogApi/blob/83732f1785a4c01a63ccf6909ca2a8190c63b4c9/Program.cs#L118) but it's kinda gross.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder
{
    public static class DelegateEndpointRouteBuilderExtensions
    {
+       public static DelegateEndpointConventionBuilder MapPatch(this IEndpointRouteBuilder endpoints, string pattern, Delegate handler);
    }
}
```

## Usage Examples

``` C#
app.MapPatch("/patch", (Patch<Model> patch)
{
      return patch.Changes;
});
```

## Risks

Low. 

Questions: 
- Do we also add RequestDelegate overloads here?

**Comment by pranavkm** [comment]
API approved. We discussed adding `MapHead` along with this, but think `MapGet` is a sufficient substitute for it at most times or would typically appear in a place where `GET` and `HEAD` need to be supported together. We should also add the RequestDelegate overload as part of this change:

```diff
namespace Microsoft.AspNetCore.Builder
{
    public static class DelegateEndpointRouteBuilderExtensions
    {
+       public static DelegateEndpointConventionBuilder MapPatch(this IEndpointRouteBuilder endpoints, string pattern, Delegate handler);
    }
}

namespace Microsoft.AspNetCore.Builder
{
    public static class EndpointRouteBuilderExtensions
    {
+        public static IEndpointConventionBuilder MapPatch(this IEndpointRouteBuilder endpoints, string pattern, RequestDelegate requestDelegate)
    }
}
```

**Comment by noamyogev84** [comment]
hey, i'll be happy to tackle this one 🎉
