### ISSUE TITLE
"Consumes" attribute alters the action endpoint when content-type mismatch

### ISSUE THREAD

**Issue by wayneyaoo** [dotnet/aspnetcore#36195]
### Describe the bug
Hi team, feel free to close if this is not a bug. I'm not so sure.

I'm running an ASP.NET Core Web API 5.0. I have a controller tagged with `[Consumes("application/x-www-form-urlencoded")]` attribute, and a customized attribute `[MyAttribute]`. I'm writing a middleware making (some but not all) decision by looking at what attributes the endpoint handling the request has, similar to this approach: https://github.com/dotnet/aspnetcore/issues/7795. 

Here's the problem: 

When tagged with both attributes, and the request made to the controller has expected content-type `application/x-www-form-urlencoded`: `Context.GetEndpoint().Endpoint` returns the correct endpoint, which is my controller (in debugger, the endpoint name string is something like `MyNamspace.Controllers.MyAction`).

When tagged with both attributes, but the request made to the controller has non-matching content-type e.g., `application/json`: `Context.GetEndpoint().Endpoint` returns another weird (internal?) endpoint, which is not my controller (in debugger, the endpoint name string is simply `415 HTTP Unsupported Media Type`), and the its metadata doesn't contain my attribute of course.

When tagged with only my attribute, it works fine. The context-returned endpoint is still my endpoint containing all the attributes.

So my question is:

1. I can see that the `Consumes` attribute internally is an `IResourceFilter`. So I'm wondering if peeking at metadata of an action in middleware which triggers flow in Filter pipeline is a bad practice? since normally filter pipeline runs after middleware pipeline. 

2. Is this behavior by design? or did I use it the wrong way. I expect to see the context-returned endpoint is still my endpoints.

3. If this is by design how can I achieve the behavior I want? I don't wanna put this in the filter pipeline since this middleware maps to a fundamental assumption and I want the request to be short-circuited as early as possible (like before model binding) if the assumption breaks, with exceptions that the action handling the request allows to not follow the assumption.

### To Reproduce

See above.

### Exceptions (if any)

When tagged with both attributes, but the request made to the controller has non-matching content-type e.g., `application/json`: `Context.GetEndpoint().Endpoint` still returns my endpoint with my attributes in the endpoint metadata.

### Further technical details
- ASP.NET Core version: 
5.0
 
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.117 [C:\Program Files\dotnet\sdk]
  5.0.205 [C:\Program Files\dotnet\sdk]
  5.0.206 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Rider.

**Comment by davidfowl** [comment]
> Is this behavior by design? or did I use it the wrong way. I expect to see the context-returned endpoint is still my endpoints.

The behavior is by design.

> If this is by design how can I achieve the behavior I want? I don't wanna put this in the filter pipeline since this middleware maps to a fundamental assumption and I want the request to be short-circuited as early as possible (like before model binding) if the assumption breaks, with exceptions that the action handling the request allows to not follow the assumption.

Don't use the consumes attribute. It affects route selection which is why you're seeing this behavior. If you make a request with an unsupported content type the route won't match and it'll pick a built in endpoint that will return a 415 here https://github.com/dotnet/aspnetcore/blob/c663adee8e64ba5d379fa0edfb8201984a7df7d0/src/Mvc/Mvc.Core/src/Routing/ConsumesMatcherPolicy.cs#L68-L69

**Comment by wayneyaoo** [comment]
Thanks for the quick response! So I assume that there's no way to customize the fallback endpoint, and I need to implement the "consumes" right?

**Comment by davidfowl** [comment]
That's right. Today the rejection endpoint is hardcoded.

**Comment by wayneyaoo** [comment]
Thanks. Noted.

Close the issue because question is answered.
