### ISSUE TITLE
🐞 `WebApplication.CreateBuilder(args).Host.Properties` cannot share context value.

### ISSUE THREAD

**Issue by MonkSoul** [dotnet/aspnetcore#36197]
Use the latest `WebApplication.CreateBuilder(args)` to create the object `builder` and set it's `Properties` value through the `Host` property. 

For example, add a `data` element, but the value just set cannot be obtained in the `ConfigureContainer` and `UseServiceProviderFactory` methods. It will always be displayed here as the initial value.

However, in the past version (`.NET5`), it was normal through the `Host.CreateDefaultBuilder(args)`.

See the detailed code and screenshot below.

```cs
var builder = WebApplication.CreateBuilder(args);

// step1: add some share data
builder.Host.Properties.Add("data", "aspnetcore");

builder.Host.ConfigureContainer<IServiceCollection>((hostContext, services) =>
{
    // step2: the data is lost
    var data = hostContext.Properties; // the data is lost
});
```

![image](https://user-images.githubusercontent.com/22766122/132167358-4ce04123-beda-42de-9516-929dc19795ce.png)

```cs
var builder = Host.CreateDefaultBuilder(args);

// step1: add some share data
builder.Properties.Add("data", "aspnetcore");

builder.ConfigureContainer<IServiceCollection>((hostContext, services) =>
{
    // step2: the data is normal
    var data = hostContext.Properties; // the data is normal
});
```

![image](https://user-images.githubusercontent.com/22766122/132167687-f65934e6-a03e-4af4-9e7f-5d20745ce785.png)

**Comment by davidfowl** [comment]
Yes this looks like a bug.

**Comment by davidfowl** [comment]
Actually, it looks like this is fixed in later builds. I assume you're on preview7.

**Comment by MonkSoul** [comment]
> Actually, it looks like this is fixed in later builds. I assume you're on preview7.

OK, thanks. I'll try using daily builds version.

**Comment by MonkSoul** [comment]
> Actually, it looks like this is fixed in later builds. I assume you're on preview7.

Pass the daily build test, thank you.

![image](https://user-images.githubusercontent.com/22766122/132300012-3349f5db-b051-4d9d-9317-95e4e30d8897.png)

![image](https://user-images.githubusercontent.com/22766122/132300174-46e94d9d-ffd1-4836-9f8b-4aa4d53d3082.png)

**Comment by davidfowl** [comment]
Sweet! I'll close out this issue once I add test coverage for it.
