### ISSUE TITLE
Reduce allocation for OnPrepareResponse event in StaticFile Middleware

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#36210]
## Background and Motivation
In static file middleware there's an `OnPrepareResponse` event which is called before the file has been written to the body.
https://github.com/dotnet/aspnetcore/blob/ccfb12cf73b0285c981c70a2061312a837510f7b/src/Middleware/StaticFiles/src/StaticFileContext.cs#L270
If `OnPrepareResponse` is set, an instance of `StaticFileResponseContext` is created on each request. `StaticFileResponseContext` is a class which holds two property of `HttpContext` and `IFileInfo`.
Is it possible to avoid this allocation by changing the `StaticFileResponseContext` from `class` to `readonly struct`?

## Proposed API

```diff
namespace Microsoft.AspNetCore.StaticFiles
{
+    public readonly struct StaticFileResponseContext_With_A_New_Name
+    {
+        public HttpContext Context { get; }
+        public IFileInfo File { get; }
+    }  

+  [Obsolete] 
    public class StaticFileResponseContext
    {
    }
 
}
namespace Microsoft.AspNetCore.Builder
{
    public class StaticFileOptions
    {
+       public Action<StaticFileResponseContext_With_A_New_Name> OnPrepareResponse_With_A_New_Name { get; set; }

+       [Obsolete] 
        public Action<StaticFileResponseContext> OnPrepareResponse { get; set; }
    }
}
```

## Alternative Designs
This could be an alternative way but it will limit the API for future changes.
```diff
+    public Action<HttpContext, IFileInfo> OnPrepareResponse { get; set; }
```

## Risks

**Comment by davidfowl** [comment]
Doesn't seem worth it IMO.

**Comment by davidfowl** [comment]
The best way to improve the performance of static files is caching the metadata, that's currently the most expensive thing.

**Comment by Pilchie** [comment]
@javiercn

**Comment by Kahbazi** [comment]
> The best way to improve the performance of static files is caching the metadata, that's currently the most expensive thing.

@davidfowl Which metadata are you referring to?

**Comment by davidfowl** [comment]
This https://github.com/dotnet/runtime/blob/d801ae267dc2ea1b177f84af4736d71f4c94d88e/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileInfo.cs#L26-L38

**Comment by adityamandaleeka** [comment]
Can this issue be closed now?

**Comment by javiercn** [comment]
I think so
