### ISSUE TITLE
Kestrel certificate with docker-compose: BIO routines:BIO_new_file:no such file

### ISSUE THREAD

**Issue by MinhMit** [dotnet/aspnetcore#36211]
I'm use docker-compose to deploy .net 5.0 application.
I used let's encrypt to generate certificate. When i'm run docker-compose up command. 
I retrieved error: BIO routines:BIO_new_file:no such file

This's docker-compose.yml 
![wEN9J](https://user-images.githubusercontent.com/5819667/132251005-adf5cf89-278e-493d-a1af-09f1b875e9d4.png)

This's cert directory on host
![QW0Xq](https://user-images.githubusercontent.com/5819667/132251015-15ffcb10-645b-423e-9d58-631ba81ac025.png)

And error i retrieved:
![BDaJn](https://user-images.githubusercontent.com/5819667/132251022-701fd508-ae96-43b8-aafe-3f513303ab3c.png)

What can i do to fix that error.

I'm using: 
Ubuntu 20.04 TLS 
Docker version 20.10.8, build 3967b7d 
docker-compose version 1.29.2, build 5becea4c

Thanks for your support.

**Comment by davidfowl** [comment]
@wfurt

**Comment by MinhMit** [comment]
Hello supporters.
Any update for my issue?

**Comment by wfurt** [comment]
Did you check file/directory permissions? Try to run `ls -al /app/certs` from _within_ the container. (either before or instead of kestrel) 
I assume the kestrel variables are correct @davidfowl ?

**Comment by MinhMit** [comment]
@wfurt 
Thanks for answer,
This's image's permission of /app/certs within my container

![Untitled](https://user-images.githubusercontent.com/5819667/132566521-d52909c3-e01f-4c53-a38d-874cb27173e5.png)

Is it wrong? And what can i do to fix this?

Again, thanks for your support

**Comment by wfurt** [comment]
The problem is that the files you are trying to access are symbolic links. And they are relative to the original location and not visible in the docker container. One way how to fix it is to map the '.../archive/megiservices.com-001/` instead of `.../localization/certs`

**Comment by MinhMit** [comment]
> The problem is that the files you are trying to access are symbolic links. And they are relative to the original location and not visible in the docker container. One way how to fix it is to map the '.../archive/megiservices.com-001/`instead of`.../localization/certs`

It's working, thanks you so much.

**Comment by davidfowl** [comment]
@wfurt is this worth adding to docs?

**Comment by wfurt** [comment]
What docs @davidfowl? This is basic container behavior but I don't know if you have any asp.net specific instructions. Generally app in container cannot use files not accessible the container itself. I see symlinks in /etc/ssl on certain distributions so it may be worth of mentioning.

**Comment by davidfowl** [comment]
@wfurt I was asking from a POV of, will you ever need to answer this question again 😄  or can we point people at some docs to show what to do in this scenario.
