### ISSUE TITLE
How to send Data to User id Saved in AspNetUsers Table In Blazor Server SignalR

### ISSUE THREAD

**Issue by sudip7139** [dotnet/aspnetcore#36222]
Here I have blazor server app in which I have signalR hub called SessionChatHub, and it contains method AssignmentCreatedNotification(HashSet<string> userIdList, string name) which receives userIdList(userIdList is identity id list accessed from database AspNetUsers table) and name as parameter and send the name to all the user of userIdList parameter.

Now the problem is that even after getting values in userIdList and name parameter, await Clients.User(userId).SendAsync("ReceiveAssignmentCreatedNotification", name) of hub doesnot call NotifyStudentAboutAssignmentCreated(string name) 

userIdList: (userIdList is identity id accessed from database AspNetUsers table)

Below is my hub

    public class SessionChatHub:Hub
    {
        
        public async Task AssignmentCreatedNotification(HashSet<string> userIdList, string name)
        {
            foreach (var userId in userIdList)
            {
                await Clients.User(userId).SendAsync("ReceiveAssignmentCreatedNotification", name);
            }
        }
        public async override Task OnConnectedAsync()
        {
            var userName = Context.User.Identity.Name;
            var UserId = Context.UserIdentifier;
            Console.WriteLine($"{Context.ConnectionId} connected");\
          
        }

        public override async Task OnDisconnectedAsync(Exception e)
        {
            Console.WriteLine($"Disconnected {e?.Message} {Context.ConnectionId}");
            await base.OnDisconnectedAsync(e);
        }
    }

Below is my oninitialized where we receive signalr  hub Clients.User(userId).SendAsync("ReceiveAssignmentCreatedNotification", name)

    protected async override void OnInitialized()
    {
        var container = new CookieContainer();
        var cookie = new Cookie()
        {
            Name = ".AspNetCore.Identity.Application",
            Domain = "localhost",
            Value = CookiesProvider.Cookie
        };

        container.Add(cookie);

        hubConnection = new HubConnectionBuilder()
      .WithUrl(NavigationManager.ToAbsoluteUri("/sessionchathub"), options =>
      {
          options.Cookies = container;
      }).Build();
        hubConnection.ServerTimeout = TimeSpan.FromMinutes(60);

        hubConnection.On<string>("ReceiveAssignmentCreatedNotification", NotifyStudentAboutAssignmentCreated);

        await hubConnection.StartAsync();
    }

Below is method to be called 

    public void NotifyStudentAboutAssignmentCreated(string name) // This method is not called from oninitialized  
    {
        var getName = name;
        NotificationHandler.AssignmentNotificationCount = 1;
        StateHasChanged();
    } 
I also have OnAfterRenderAsync

      protected async override Task OnAfterRenderAsync(bool firstRender)
        {
            

            //if (firstRender)
            //{
            await jSRuntime.InvokeVoidAsync("AddSelect2ForClassIdInCreateEditTeacherAssignment");
            await jSRuntime.InvokeVoidAsync("AddSelect2ForSubjectIdInCreateEditTeacherAssignment");
            await jSRuntime.InvokeVoidAsync("AddSelect2ForChapterIdInCreateEditTeacherAssignment");
            //}
            await base.OnAfterRenderAsync(firstRender);
        }

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
