### ISSUE TITLE
Error running signalr in google app engine

### ISSUE THREAD

**Issue by amir20001** [dotnet/aspnetcore#36249]
### Describe the bug
Issue running Signalr with google app engine.

I have set up a basic client to listen to Signalr msgs, I managed to get everything working locally.
When I deploy the service to google app engine, it seems like all messages stop coming through.

Debugging steps I have taken so far:
1. Force Signalr to use long polling in-case the WebSocket was being killed for some reason.
2. Setup trace logging and we see the following logs:

```
2021-09-07 22:01:44 signalr[b08e370-snapshot]  2021-09-07T22:01:44,089 DEBUG [OkHttp ...] c.m.s.LongPollingTransport: Message received.
2021-09-07 22:01:44 signalr[b08e370-snapshot]  2021-09-07T22:01:44,090 DEBUG [OkHttp ...] c.m.s.LongPollingTransport: Polling ...
2021-09-07 22:01:44 signalr[b08e370-snapshot]  2021-09-07T22:01:44,091 DEBUG [pool-4-thread-1] c.m.s.LongPollingTransport: OnReceived callback has been invoked.
```

This log message only shows up when run locally
```
2021-09-07T17:00:33,303 DEBUG [pool-3-thread-1] c.m.s.HubConnection: Received message of type STREAM_ITEM
``` 

### To Reproduce

```
         LOG.info("Setting up connection");
        hubConnection = HubConnectionBuilder
                .create("...")
                .withAccessTokenProvider(Single.just(token))
                .build();

        hubConnection.onClosed((ex) -> {
            if (ex != null) {
                LOG.error("Error with connection", e);
            }
        });
        hubConnection.start().blockingAwait();

        hubConnection.stream(Map.class, "ActionStream", "...")
                .subscribe((item) -> LOG.debug("New event found"),
                        (error) -> LOG.error("Error with SignalR", error),
                        () -> LOG.info("Server closed the connection unexpectedly")
                );
```

My best guess is that something is stalling in ReceiveLoop of HubConnection during the lock but there is no logging around that.
### Exceptions (if any)
None

### Further technical details
Running in a docker image with Java 8
Deployed in a google app engine flex environment
Signalr version: 5.0.9

**Comment by davidfowl** [comment]
Where is the server running and where is the client running?

**Comment by amir20001** [comment]
The server is running in AWS (Not managed by our company), they are using the SignalR subscription service. 
The client is running in Google app engine(us-central)

**Comment by davidfowl** [comment]
So there's an existing SignalR server running on AWS.

> they are using the SignalR subscription service.

What does this mean? They are using Azure SignalR or something else?

> The client is running in Google app engine flex(us-central)

So this problem is purely a client problem. You client, when running in app engine, isn't receiving messages?

**Comment by amir20001** [comment]
Turns out this was a problem with the server picking up on a bad config when deployed.
