### ISSUE TITLE
dotnet watch hot reload doesn't apply changes to hosted wasm client project

### ISSUE THREAD

**Issue by zHaytam** [dotnet/aspnetcore#36266]
### Describe the bug
I have created a new Wasm Hosted project from VS 2022 and ran `dotnet watch run` on the server project's folder. When changing a simple text in the Client project's Index razor page (e.g. "Welcome to your new app 2"), the changes are not applied.

```
Files changed: D:\Projects\X\X\Client\Pages\Index.razor~RF7a829ac8.TMP, D:\Projects\X\X\Client\Pages\lqplhles.t42~, D:\Projects\X\X\Client\Pages\Index.razor
watch : No hot reload changes to apply.
```

### To Reproduce

1. Create a new hosted wasm project
2. Run `dotnet watch run` on the server
3. Change something simple, e.g. a text

### Further technical details
- .NET 6 rc1
- VS 2022

**Comment by zHaytam** [comment]
On .NET 6 preview 6/7, I get:
```
watch : File changed: D:\Projects\X\X\Client\Pages\Index.razor.
watch : Hot reload of changes succeeded.
```

Except I don't see any changes in the browser as well.

**Comment by zHaytam** [comment]
Using `dotnet watch` (withoutthe run) works... What's the difference?

**Comment by pranavkm** [comment]
RC1 had a bug in the compiler that prevented watch from working effectively. I think a fix for this was merged in last night. Could you try updating the SDK and see if you continue seeing the issue?

**Comment by MichelJansson** [comment]
@pranavkm I'm having the same issue.
This started happening recently. Before installing VS 2022 preview 4, when I was using a little bit older daily build of RC1, it would say along the lines of it not being a hot-reloadable change etc. and ask me if i would like to rebuild.

Installing 6.0.0-rc.2.21470.23 did not solve the problem, and I'm still getting the below, with a brief flash of "Updating the page" message in the browser, but no actual change can be observed until manual restart of app.
```
watch : File changed: xyz\Web.BlazorClient\Pages\xyz.razor.
watch : No hot reload changes to apply.
```
