### ISSUE TITLE
Is it possible to configure the exception data to log in Log<Level> methods?

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/aspnetcore#36262]
For instance, can I configure somehow so that the `logger.LogError` method will log my own properties, or I can configure further more as to what gets logged? The current implementation seems to log the result of a simply call to `Exception.ToString()` method.

**Comment by davidfowl** [comment]
That's up to the logger implementation.

**Comment by nicholasyin** [comment]
> That's up to the logger implementation.

LOL. You're right.
