### ISSUE TITLE
ASP.NET Core SignalR C++ Client  32bit

### ISSUE THREAD

**Issue by grahambunce** [dotnet/aspnetcore#36276]
We are having trouble compiling this under 32bit - before we investigate further can you confirm if this is intended to support 32/64 bit or just 64 bit?

We wish to run on low-power, older hardware that is still 32bit.

**Comment by adityamandaleeka** [comment]
Can you share a repro or more info on what you're hitting?

**Comment by JonathanCrawshaw** [comment]
Hi @adityamandaleeka .  Thanks for responding to @grahambunce.  I am a collegue of his.
We have got past the issue, it was a problem with my vcpkg installation.  After a re-installing it we had no trouble installing the 32bit (x86) SignalR-Client-Cpp library.

**Comment by adityamandaleeka** [comment]
Great!
