### ISSUE TITLE
Blazor WebAssembly .Net Core Hosted - Delete temp file after its downloaded to the browser

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/aspnetcore#36282]
Hi,

I wrote a report generator the other day which generates an XML file on the .NET Core server, as part of the generation it creates temporary files that need removing once the file has been downloaded into the browser.

I have this javascript function in the `index.html` which does the download into the browser:
```js
var downloadFromUrl = function(url) {
    var anchorElement = document.createElement('a');
    anchorElement.href = url;
    anchorElement.click();
    anchorElement.remove();
}
```

Once the final report has been generated on the server I call the following to download the file and once complete delete the temporary files from the server:
```cs
try
{
    await JsRunTime.InvokeVoidAsync("downloadFromUrl", $"api/Export/GetExportFile?exportId={exportRunner.ExportId}&fileDownloadName={exportRunner.FinalExportFileName}&outputFormatType={exportRunner.OutputFormatType}");
}
finally
{
    await exportRunner.DeleteTempFilesOnServer();
}
```

This was working fine on a 100MB+ file.

I have today used the same approach to generate smaller files and am now hitting an issue.  It runs the `await exportRunner.DeleteTempFilesOnServer()` before `await JsRunTime.InvokeVoidAsync("downloadFromUrl", $"api/Export/GetExportFile?exportId={exportRunner.ExportId}&fileDownloadName={exportRunner.FinalExportFileName}&outputFormatType={exportRunner.OutputFormatType}");`, so the download into the browser fails as the files have been deleted.

It feels like `JsRunTime.InvokeVoidAsync` is not being awaited.

Is there a way I can make sure the file has finished downloading into the browser before the delete kicks in?

**Comment by pranavkm** [comment]
`InvokeVoidAsync` awaits the promise returned from your JS interop call or finishes as soon as your JS function executes. In your case, the JS function finishes synchronously. You would return a promise that would finish at the end of the browser finishing the download. An alternate solution might be to trigger removal from your API endpoint after it's been downloaded with some smarts around cleaning up if the API is never triggered.
