### ISSUE TITLE
WSS Closure Immediately after KeepAlive

### ISSUE THREAD

**Issue by SonoranBrian** [dotnet/aspnetcore#36308]
### Describe the bug
While using CloudFlare to proxy the WSS connection with SignalR, some users experience frequent disconnects. This is only reproducible while using a proxied connection with CF.

I've been trying to track down this issue for some time now, most recently with: #[29563 ](https://github.com/dotnet/aspnetcore/issues/34451)as it seems only certain users experience this. When the clients use a different version of the app without a CF proxy it works. My theory was it could be with CF closing idle WSS connections, but I can see with logging the keep-alives are being sent properly.

With this latest client, I can see a keepalive (type 6) sent at `22:37:23.634Z`, and the client detects the socket being closed immediately after at `22:37:23:666z`. The same thing occurs in the next screenshot.

There's no other errors detected on the client, and nothing about a timeout. Simply the `1006` error immediately after this type 6 (data of length 11).

![image](https://user-images.githubusercontent.com/56844125/132595386-d2e91fee-fd4f-446b-a508-a627f975c40d.png)
![image](https://user-images.githubusercontent.com/56844125/132596000-89c8e359-e34c-4a05-a6e1-9f38a51e53c4.png)

Any ideas what would cause the connection to close immediately after sending a keep alive?

### To Reproduce
Proxy WSS via Cloudflare

### Exceptions (if any)
`1006`

### Further technical details
- ASP.NET Core 5.0
- SignalR 5.0.7 (C# and JS)

**Comment by adityamandaleeka** [comment]
Triage: a possible explanation might be that CF is still connected to the backend, but has closed the connection with the client. The client doesn't notice that until it tries to send data.

**Comment by adityamandaleeka** [comment]
Possibly related: https://stackoverflow.com/questions/39668410/whats-disconnecting-my-websocket-connection-cloudflare-apaches-mod-proxy/41031976#41031976

**Comment by SonoranBrian** [comment]
> Triage: a possible explanation might be that CF is still connected to the backend, but has closed the connection with the client. The client doesn't notice that until it tries to send data.

This likely makes the most sense, I've been trying to contact CloudFlare on more info as to what can cause a closure. I was aware of them closing idle connections, but SignalR has built in keepalives being sent every 15 seconds, so these are by no means idle.

I also tried implementing a hard 15 second ping/pong heartbeat from the server to all clients every 15 seconds just to test, but some clients still are connected by CF or something in between anyways.

**Comment by adityamandaleeka** [comment]
@SonoranBrian Please let us know if you figure out a solution/workaround to this.

However, since it doesn't seem like this is an issue in our code, we'll close this issue for now. We can reopen if that changes.
