### ISSUE TITLE
DotNetStreamReference class no longer exists

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#36316]
In a recent issue I opened #36135, Steve suggested I could instantiate `DotNetStreamReference` class. Apparently that class no longer exist or has been renamed. I searched [here](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-5.0&terms=DotNetStreamReference)
![image](https://user-images.githubusercontent.com/63487874/132603285-aa0d55dd-7eeb-4d23-a0c2-9ed60b20f9b8.png)
and when you open the page and search for it, nothing comes up. Like if the page was modified.
![image](https://user-images.githubusercontent.com/63487874/132603569-a78b2fa5-c78f-43dc-aa25-e6bb6debff7a.png)

**Comment by javiercn** [comment]
@ylr-research thanks for contacting us.

We might have renamed it as part of our API review process and the docs might be out of date. @TanayParikh do you have thoughts?

**Comment by SteveSandersonMS** [comment]
It's in JSInterop: https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop/src/DotNetStreamReference.cs

**Comment by SteveSandersonMS** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript

**Comment by ylr-research** [comment]
Great!
