### ISSUE TITLE
Can we remove the MapToDocumentEdits call in Razor On Type formatting?

### ISSUE THREAD

**Issue by davidwengier** [dotnet/aspnetcore#36319]
Can we call `ApplyFormattedEditsAsync` directly in the existing on type formatting handler?

See https://github.com/dotnet/aspnetcore-tooling/pull/4203#discussion_r704929056

**Comment by NTaylorMullen** [comment]
Ya I think we could potentially get rid of the HTML C# OnTypeFormatting handler entirely and move all the logic over to the Razor language server
