### ISSUE TITLE
Prevent CSS039 Unexpected character sequence in property value.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#36321]
How one would remove this warning? Warning are getting really annoying as of lately.

![image](https://user-images.githubusercontent.com/3386797/132635631-50546f29-9afc-4988-ad0e-b7dcad51c125.png)

**Comment by Bartmax** [comment]
I forgot to mention that that line alone produces 21 Warnings for no reason.

![image](https://user-images.githubusercontent.com/3386797/132635834-9f0d37ec-2451-4cd8-8e4d-48659f1425b4.png)

**Comment by NTaylorMullen** [comment]
@jinujoseph I'm also going to want to bring this one through M2

**Comment by Bartmax** [comment]
is it possible to tell the IDE to ignore this warning in a consistent way? like, for all sln ?

**Comment by NTaylorMullen** [comment]
> is it possible to tell the IDE to ignore this warning in a consistent way? like, for all sln ?

I don't believe so :(
