### ISSUE TITLE
.NET 6 web app templates, remove  app.UseDeveloperExceptionPage();

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#36327]
The developer exception page is added automatically in development by `WebApplication`, so the following code should be removed from all the web app templates:

```
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
```

See [this GitHub comment](https://github.com/dotnet/AspNetCore.Docs/pull/23112#discussion_r697783111)

**Comment by vlada-shubina** [comment]
@Rick-Anderson @DamianEdwards I have transferred this issue to dotnet/aspnetcore, as it is related to asp.net templates.

**Comment by javiercn** [comment]
@vlada-shubina thanks.

This is indeed templates related

**Comment by pranavkm** [comment]
@DamianEdwards would you like to address this?

**Comment by Rick-Anderson** [comment]
RP and MVC apps go from:
```
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
```
To
```
if (!app.Environment.IsDevelopment())
{   
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
```

**Comment by DamianEdwards** [comment]
I thought I remember @BrennanConroy saying he was going to do this but he's OOF so I'm happy to make the change.

**Comment by DamianEdwards** [comment]
Yeah this has already been done in d1c349f29752ac0718bda7b809ab7fd4f82ca414. See #34548
