### ISSUE TITLE
Issue: Consume multiple BlazorCustomElements in js-frameworks (React, Vue, etc) 

### ISSUE THREAD

**Issue by TarasLobanov** [dotnet/aspnetcore#36329]
Hi! Thanks for this example - https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements. It works well for me with React or Vue (without any .net-backend). But now I be able to add only one blazor component to the project (BlazorAppProvidingCustomElements.dll from this example). If I try to add a second similar blazor component, things go wrong because there is only one "entryAssembly" in blazor.boot.json and I don't know how to set up blazor.boot.json or whatever to do it loads the assembly of my second component. Components must be independent from each other.
What exactly I do:
1. After compiling BlazorAppProvidingCustomElements.csproj, there is a "_framework" folder in the output path with everything I need.
2. Then I copy the "_framework" folder to the vue project folder like this:
![image](https://user-images.githubusercontent.com/16157501/132677486-e1d2ef6d-9783-4f10-b970-2a8432478980.png)
3. The next step is to add scirpts to index.html, as in the example:
![image](https://user-images.githubusercontent.com/16157501/132686943-a1457974-130a-4e93-8581-8810b17a3075.png)
It's okay, it works well.

After that I created the second component "BlazorAppProvidingCustomElements2.dll" and now I have a folder "_framework2" for all its assemblies:
![image](https://user-images.githubusercontent.com/16157501/132678442-75a7035b-e5c0-4896-934a-ffd95ac144b6.png)
The question is, what should I do next?
If I add line with "_framework2" to index.html:
![image](https://user-images.githubusercontent.com/16157501/132687352-a734cf33-8e25-4da9-96a2-778e5a8bfbd8.png)
Then the browser gets errors because it tries to load all scripts and assemblies twice.
So I want to be able to load system assemblies once and then load a few own blazor-components assemblies that reference those system .dlls. Is it possible now?
Thanks!

**Comment by pranavkm** [comment]
Thanks @TarasLobanov for your issue report and trying out the BlazorCustomElements feature. Unfortunately at this point Blazor does not support having multiple instances of the WebAssembly .NET runtime registered on the same page. This is something we'd like to think about in 7.0. In the meanwhile, the best suggestion we have is to compile multiple Blazor WASM apps in to a single one (by referencing them as class libraries).

**Comment by TarasLobanov** [comment]
@pranavkm thanks for answer!
I don't actually need multiple instances of the .NET WebAssembly runtime. On the contrary, I need one WebAssembly runtime for the entire application and several independent blazor components that run in it. To do this, I would like to know how to supply and load the WebAssembly runtime into the browser separately and then load the blazor components themselves. I assume this is also not supported yet, so I will keep an eye on the news.
P.S. Of course, it would be great to be able to create an Npm-package by analogy with a Nuget-package, where only the assembly of the component itself would be stored and be able to easily add it to JS-projects
