### ISSUE TITLE
InstallJdk incorrectly thinks jdk is already installed

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#36331]
https://github.com/dotnet/aspnetcore/blob/main/eng/scripts/InstallJdk.ps1#L28

In my case the folder `\.tools\jdk\win-x64\` exists but is empty, and the script no-ops. I think this could be improve to continue the installation in this case. If I had not looked at the folder I would have believed it.

**Comment by dougbu** [comment]
@javiercn is this a DoI issue or something we should just assign back to @sebastienros❔ Seems like a relatively simple fix but @wtgodbe and I are busy these days.

**Comment by javiercn** [comment]
@dougbu sounds good to me.

**Comment by dougbu** [comment]
Which sounds good @javiercn -- make it a DoI issue or ask @sebastienros to take it❔ (Both is another option 😺)

**Comment by javiercn** [comment]
Ask @sebastienros

**Comment by dougbu** [comment]
@sebastienros❔
