### ISSUE TITLE
Cannot set Response.StatusText 

### ISSUE THREAD

**Issue by xljiulang** [dotnet/aspnetcore#36359]
### Describe the bug
How should I set Response.StatusText, I want to respond to the request of Connect `HTTP/{ver} 200 Connection Established` 

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
Do you mean the HTTP response reason phrase?

https://github.com/dotnet/aspnetcore/blob/e23fd047b4baf3480ce93d7643a897732f960557/src/Http/Http/src/Features/HttpResponseFeature.cs#L29

Try this: `HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "Connection Established";`

**Comment by xljiulang** [comment]
Thank you very much
