### ISSUE TITLE
Move FromQuery and other meta attributes to a separate lib

### ISSUE THREAD

**Issue by IB38** [dotnet/aspnetcore#36369]
Hi there, dragging entire Microsoft.AspNetCore.Mvc.Core as dependency for contract lib simply because i need some of the atrributes for models is pretty bad.
Seems to be a pain for a lot of people whenever this topic comes up on stackoverflow.

I was thinking that moving attributes to a separate library with minimal or no dependencies could be the solution for this.

**Comment by javiercn** [comment]
@IB38 thanks for contacting us.

Microsoft.AspNetCore.Mvc.Core ships as part of the Microsoft.AspNetCore.App shared framework which is referenced via a `FrameworkReference`, so it doesn't really matter where it lives because you can only consume it through a `FrameworkReference`

**Comment by IB38** [comment]
Ah, my bad. Didn't know it became part of SDK since .net core 3.0.
