### ISSUE TITLE
Redundant FormatScope() override in FacebookHandler

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36370]
While looking at the code I noticed that the `FacebookHandler` class overrides the `FormatScope()` method, which then just calls the base implementation:

https://github.com/dotnet/aspnetcore/blob/e23fd047b4baf3480ce93d7643a897732f960557/src/Security/Authentication/Facebook/src/FacebookHandler.cs#L84-L86

As removing it causes the Public API analyzer to produce an error, I thought I'd ask if there's a reason for it to be there I'm missing? 

If not, would you accept a small PR to remove it for 7.0? As otherwise it seems redundant.

**Comment by Tratcher** [comment]
Facebook used to require a special format but does not anymore. However, removing the method is technically a binary break so we never did, and might never because there is nothing gained.

**Comment by martincostello** [comment]
No worries - I'll just close this then if it's just being kept indefinitely for back-compat.
