### ISSUE TITLE
ASP.NET Core 3.1 Hot Reload taking as long as build time

### ISSUE THREAD

**Issue by wayneforrest** [dotnet/aspnetcore#36376]
I have a project which takes 38 seconds to reload when a single character in a controller
file is changed. My build times are similiar.

What reload times should be considered acceptable?
Should hot-reloads be considerably faster than build times?

I posted a question on StackOverflow located here: https://stackoverflow.com/questions/69068130/asp-net-core-3-1-hot-reload-slow?noredirect=1#comment122072568_69068130

I have also tried creating a class library, and then modifying the class library, while measuring the hot reloads times. The re-load time was no different to that of modifying a controller.

**Comment by pranavkm** [comment]
Hot reload requires .NET 6 or newer. We haven't done any specific work to improve the inner loop performance for ASP.NET Core 3.1 in this release.

**Comment by wayneforrest** [comment]
Hi @pranavkm,

Would this be considered as a bug in `.NET 3.1  LTS`?

**Comment by pranavkm** [comment]
@wayneforrest for 3.1 apps, all dotnet-watch does is re-build the app on file changes which would explain why it's performance is comparable. Improving the inner loop performance for a previously shipped runtime wouldn't be necessarily considered a bug, 

Out of curiosity, how large is your project? If you run ` dotnet msbuild /clp:PerformanceSummary` it would tell you where in the build process it's spending most of the time, but 30-40s would be unusually high for moderately sized project.

**Comment by wayneforrest** [comment]
Hi @pranavkm thanks for the feedback.

I have been spending some time to migrate over to .NET 6 preview. I still have a way to,
especially with my ODATA stuff witch I find not as trivial - little breaking changes.

I can also confirm that builds are not twice as fast. I have a build time of 11 seconds, compared to my earlier 25 seconds - WOW!

Also the **hot reload's are super fast**. It is most definitely 3 seconds or less, when making a  simple changes to Controllers and the Startup.

**Comment by wayneforrest** [comment]
The performance for the .net 3.1 build:

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  netplus -> /Users/wayneforrest/Projects/netplus/netplus/bin/Debug/netcoreapp3.1/netplus.dll
  netplus -> /Users/wayneforrest/Projects/netplus/netplus/bin/Debug/netcoreapp3.1/netplus.Views.dll
  netplusTest -> /Users/wayneforrest/Projects/netplus/netplusTest/bin/Debug/netcoreapp3.1/netplusTest.dll

Project Evaluation Performance Summary:
       67 ms  /Users/wayneforrest/Projects/netplus/netplusTest/netplusTest.csproj   1 calls
     4836 ms  /Users/wayneforrest/Projects/netplus/netplus/netplus.csproj   1 calls

Project Performance Summary:
      961 ms  /Users/wayneforrest/Projects/netplus/netplus/netplus.csproj   5 calls
                  0 ms  GetTargetFrameworks                        1 calls
                  0 ms  GetNativeManifest                          1 calls
                  0 ms  GetCopyToOutputDirectoryItems              1 calls
     6013 ms  /Users/wayneforrest/Projects/netplus/netplusTest/netplusTest.csproj   1 calls
     6200 ms  /Users/wayneforrest/Projects/netplus/netplus.sln   1 calls

Target Performance Summary:
        0 ms  RazorComponentGenerate                     1 calls
        0 ms  _RazorPrepareForRun                        1 calls
        0 ms  BeforeCompile                              2 calls
        0 ms  PrepareForRazorGenerate                    1 calls
        0 ms  RazorGenerate                              1 calls
        0 ms  RazorCompile                               1 calls
        0 ms  RazorComponentGenerateCore                 1 calls
        0 ms  _RazorEnsureCompiled                       1 calls
        0 ms  PrepareResources                           2 calls
        0 ms  PrepareForRazorCompile                     1 calls
        0 ms  ResolveRazorCompileInputs                  1 calls
        0 ms  _GenerateRazorAssemblyInfo                 1 calls
        0 ms  ResGen                                     2 calls
        0 ms  AfterBuild                                 2 calls
        0 ms  _CopySourceItemsToOutputDirectory          2 calls
        0 ms  GetReferenceAssemblyPaths                  2 calls
        0 ms  AfterCompile                               2 calls
        0 ms  CreateSatelliteAssemblies                  2 calls
        0 ms  Compile                                    2 calls
        0 ms  BeforeResGen                               2 calls
        0 ms  GenerateMSBuildEditorConfigFile            2 calls
        0 ms  GenerateAssemblyInfo                       2 calls
        0 ms  PrepareResourceNames                       2 calls
        0 ms  PrepareProjectReferences                   2 calls
        0 ms  ResolveStaticWebAssetsInputs               1 calls
        0 ms  CreateCustomManifestResourceNames          2 calls
        0 ms  SetWin32ManifestProperties                 2 calls
        0 ms  PrepareForRun                              2 calls
        0 ms  BeforeBuild                                2 calls
        0 ms  AfterResolveReferences                     2 calls
        0 ms  ResolvePackageDependenciesForBuild         2 calls
        0 ms  BeforeResolveReferences                    2 calls
        0 ms  ValidateProjects                           1 calls
        0 ms  CoreBuild                                  2 calls
        0 ms  AddSourceRevisionToInformationalVersion    2 calls
        0 ms  _RemoveRazorDeclartionsFromCompile         1 calls
        0 ms  GetFrameworkPaths                          2 calls
        0 ms  AfterResGen                                2 calls
        0 ms  PrepareForRazorComponentGenerate           1 calls
        0 ms  GenerateRazorTargetAssemblyInfo            1 calls
        0 ms  InitializeSourceControlInformation         2 calls
        0 ms  ComputeIntermediateSatelliteAssemblies     1 calls
        0 ms  IncludeTransitiveProjectReferences         2 calls
        0 ms  BuildOnlySettings                          2 calls
        0 ms  EnableIntermediateOutputPathMismatchWarning   2 calls
        0 ms  _ComputeNETCoreBuildOutputFiles            2 calls
        0 ms  GetTargetPath                              2 calls
        0 ms  _DefaultMicrosoftNETPlatformLibrary        2 calls
        0 ms  _CheckForUnsupportedCppNETCoreVersion      2 calls
        0 ms  GetNativeManifest                          1 calls
        0 ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   2 calls
        0 ms  CopyAdditionalFiles                        2 calls
        0 ms  ExpandSDKReferences                        2 calls
        0 ms  _BeforeVBCSCoreCompile                     2 calls
        0 ms  ResolveSDKReferences                       2 calls
        0 ms  _CheckForObsoleteDotNetCliToolReferences   2 calls
        0 ms  ComputeDependencyFileCompilerOptions       2 calls
        0 ms  _CheckForUnsupportedNETCoreVersion         2 calls
        0 ms  _CheckForLanguageAndFeatureCombinationSupport   2 calls
        0 ms  ResolveLockFileAnalyzers                   2 calls
        0 ms  RazorGetAssemblyAttributes                 1 calls
        0 ms  _ResolveMvcAssemblyAttributes              1 calls
        0 ms  AddTransitiveFrameworkReferences           2 calls
        0 ms  PostprocessVSRepxManifestResourceNames     1 calls
        0 ms  GetTargetFrameworks                        1 calls
        0 ms  ResolveReferencedProjectsStaticWebAssets   1 calls
        0 ms  GenerateMSBuildEditorConfigFileShouldRun   2 calls
        0 ms  GenerateProgramFile                        1 calls
        0 ms  _GetProjectJsonPath                        2 calls
        0 ms  ValidateToolsVersions                      1 calls
        0 ms  CollectPackageReferences                   2 calls
        0 ms  GetRazorTargetAssemblyAttributes           1 calls
        0 ms  _CheckForUnsupportedAppHostUsage           2 calls
        0 ms  _RazorGetCopyToOutputDirectoryItems        1 calls
        0 ms  _PrepareForStaticWebAssets                 1 calls
        0 ms  GetAssemblyAttributes                      2 calls
        0 ms  _ComputePackageReferencePublish            2 calls
        0 ms  GetTargetPathWithTargetPlatformMoniker     2 calls
        0 ms  _GenerateSatelliteAssemblyInputs           2 calls
        0 ms  _CheckForCompileOutputs                    2 calls
        0 ms  PreprocessVSRepxManifestResourceNames      1 calls
        1 ms  _ResolveRazorTargetPath                    1 calls
        1 ms  CoreResGen                                 2 calls
        1 ms  _SetTargetFrameworkMonikerAttribute        2 calls
        1 ms  ResolveReferences                          2 calls
        1 ms  _GenerateCompileInputs                     2 calls
        1 ms  ReferencedPathMaps                         1 calls
        1 ms  ResolveRazorComponentInputs                1 calls
        1 ms  ResolveAssemblyReferenceRazorGenerateInputs   1 calls
        1 ms  GetAssemblyVersion                         2 calls
        1 ms  _SplitProjectReferencesByFileExistence     2 calls
        1 ms  GenerateBuildRuntimeConfigurationFiles     2 calls
        1 ms  CoreGenerateRazorTargetAssemblyInfo        1 calls
        1 ms  _CoreGenerateRazorAssemblyInfo             1 calls
        1 ms  _CreateRazorTargetAssemblyInfoInputsCacheFile   1 calls
        1 ms  _GenerateRuntimeConfigurationFilesInputCache   2 calls
        1 ms  ApplyImplicitVersions                      2 calls
        2 ms  _CreateRazorAssemblyInfoInputsCacheFile    1 calls
        2 ms  _RazorCopyFilesToOutputDirectory           1 calls
        2 ms  _ComputeUserRuntimeAssemblies              2 calls
        2 ms  SplitResourcesByCulture                    2 calls
        2 ms  ResolveRazorConfiguration                  1 calls
        2 ms  _DiscoverMvcApplicationParts               1 calls
        2 ms  _HashRazorGenerateInputs                   1 calls
        2 ms  _CopyOutOfDateSourceItemsToOutputDirectory   2 calls
        3 ms  GenerateTargetFrameworkMonikerAttribute    2 calls
        3 ms  CreateManifestResourceNames                1 calls
        4 ms  AssignProjectConfiguration                 2 calls
        4 ms  ResolveRazorGenerateInputs                 1 calls
        4 ms  CopyFilesToOutputDirectory                 2 calls
        4 ms  CoreGenerateAssemblyInfo                   2 calls
        4 ms  ResolveLockFileReferences                  2 calls
        4 ms  _CreateStaticWebAssetsInputsCacheFile      1 calls
        4 ms  _GetCopyToOutputDirectoryItemsFromThisProject   2 calls
        4 ms  CheckForImplicitPackageReferenceOverrides   2 calls
        4 ms  ResolveLockFileCopyLocalFiles              2 calls
        4 ms  CheckForDuplicateItems                     2 calls
        5 ms  _SetEmbeddedWin32ManifestProperties        2 calls
        5 ms  CreateGeneratedAssemblyInfoInputsCacheFile   2 calls
        5 ms  _ComputeReferenceAssemblies                2 calls
        5 ms  UpdateAspNetToFrameworkReference           2 calls
        5 ms  _CollectTargetFrameworkForTelemetry        2 calls
        5 ms  AssignTargetPaths                          2 calls
        6 ms  PrepareForBuild                            2 calls
        7 ms  GenerateStaticWebAssetsManifest            1 calls
        7 ms  _CheckForInvalidConfigurationAndPlatform   2 calls
        8 ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   2 calls
        8 ms  _ResolveGeneratedRazorCompileInputs        1 calls
        8 ms  ResolveTagHelperRazorGenerateInputs        1 calls
        9 ms  _GenerateCompileDependencyCache            2 calls
        9 ms  RazorCoreCompile                           1 calls
       10 ms  RazorCoreGenerate                          1 calls
       11 ms  ResolveTargetingPackAssets                 2 calls
       11 ms  GenerateBuildDependencyFile                2 calls
       12 ms  _GetRestoreProjectStyle                    2 calls
       16 ms  ValidateSolutionConfiguration              1 calls
       16 ms  ResolveFrameworkReferences                 2 calls
       17 ms  GetCopyToOutputDirectoryItems              2 calls
       19 ms  AssignRazorGenerateTargetPaths             1 calls
       19 ms  CoreCompile                                2 calls
       24 ms  _ResolveRazorGenerateOutputs               1 calls
       27 ms  _CopyReferenceOnlyAssembliesForBuild       2 calls
       27 ms  ResolvePackageAssets                       2 calls
       30 ms  IncrementalClean                           2 calls
       31 ms  _CopyFilesMarkedCopyLocal                  2 calls
       49 ms  ResolveProjectReferences                   2 calls
       68 ms  ResolveCurrentProjectStaticWebAssetsInputs   1 calls
      107 ms  FindReferenceAssembliesForReferences       2 calls
      120 ms  ResolveAssemblyReferences                  2 calls
      141 ms  _CleanGetCurrentAndPriorFileWrites         2 calls
      157 ms  _HandlePackageFileConflicts                2 calls
      242 ms  ProcessFrameworkReferences                 2 calls
     5654 ms  _GetProjectReferenceTargetFrameworkProperties   2 calls
     6178 ms  Build                                      3 calls

Task Performance Summary:
        0 ms  Delete                                     2 calls
        1 ms  GetAssemblyVersion                         2 calls
        1 ms  ResolveFrameworkReferences                 2 calls
        1 ms  AssignCulture                              2 calls
        1 ms  GetReferenceNearestTargetFrameworkTask     1 calls
        1 ms  ApplyImplicitVersions                      2 calls
        1 ms  FindInList                                 1 calls
        1 ms  Telemetry                                  2 calls
        1 ms  FindAppConfigFile                          2 calls
        1 ms  CheckForDuplicateFrameworkReferences       2 calls
        1 ms  CheckIfPackageReferenceShouldBeFrameworkReference   4 calls
        1 ms  JoinItems                                  2 calls
        1 ms  ConvertToAbsolutePath                      2 calls
        2 ms  ResolveAppHosts                            2 calls
        2 ms  Touch                                      3 calls
        2 ms  CreateCSharpManifestResourceName           1 calls
        3 ms  CheckForImplicitPackageReferenceOverrides   2 calls
        3 ms  AssignProjectConfiguration                 2 calls
        3 ms  CheckForDuplicateItems                     6 calls
        4 ms  GetRestoreProjectStyleTask                 2 calls
        4 ms  Message                                    8 calls
        4 ms  GetFrameworkPath                           2 calls
        4 ms  AssignTargetPath                          13 calls
        5 ms  MakeDir                                    2 calls
        6 ms  ReadLinesFromFile                          2 calls
        7 ms  Hash                                      10 calls
        8 ms  GetPackageDirectory                       12 calls
        9 ms  WriteLinesToFile                          10 calls
       10 ms  ResolveTargetingPackAssets                 2 calls
       12 ms  RemoveDuplicates                           4 calls
       15 ms  CallTarget                                 4 calls
       25 ms  ResolvePackageAssets                       2 calls
       57 ms  Copy                                      10 calls
      113 ms  FindUnderPath                             10 calls
      117 ms  ResolveAssemblyReference                   2 calls
      145 ms  ResolvePackageFileConflicts                2 calls
      238 ms  ProcessFrameworkReferences                 2 calls
    11832 ms  MSBuild                                    7 calls

**Comment by wayneforrest** [comment]
.NET 6  clean build time: Time Elapsed 00:00:08.56

also the performance for .net 6 build
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  netplus -> /Users/wayneforrest/Projects/netplus/netplus/bin/Debug/net6.0/netplus.dll
  netplusTest -> /Users/wayneforrest/Projects/netplus/netplusTest/bin/Debug/net6.0/netplusTest.dll

Project Evaluation Performance Summary:
      356 ms  /Users/wayneforrest/Projects/netplus/netplusTest/netplusTest.csproj   1 calls
      641 ms  /Users/wayneforrest/Projects/netplus/netplus/netplus.csproj   1 calls

Project Performance Summary:
      873 ms  /Users/wayneforrest/Projects/netplus/netplus/netplus.csproj   5 calls
                 11 ms  GetTargetFrameworks                        1 calls
                  5 ms  GetNativeManifest                          1 calls
                  0 ms  GetCopyToOutputDirectoryItems              1 calls
     1355 ms  /Users/wayneforrest/Projects/netplus/netplusTest/netplusTest.csproj   1 calls
     2274 ms  /Users/wayneforrest/Projects/netplus/netplus.sln   1 calls

Target Performance Summary:
        0 ms  _RazorPrepareForRun                        1 calls
        0 ms  ResolveStaticWebAssetsInputs               1 calls
        0 ms  CopyStaticWebAssetsToOutputFolder          1 calls
        0 ms  _GenerateRazorAssemblyInfo                 1 calls
        0 ms  BeforeCompile                              2 calls
        0 ms  ResGen                                     2 calls
        0 ms  PrepareForRazorGenerate                    1 calls
        0 ms  PrepareResourceNames                       2 calls
        0 ms  RazorCompile                               1 calls
        0 ms  AfterBuild                                 2 calls
        0 ms  BeforeResGen                               2 calls
        0 ms  ValidateProjects                           1 calls
        0 ms  GetFrameworkPaths                          2 calls
        0 ms  PrepareForRazorComponentGenerate           1 calls
        0 ms  SetWin32ManifestProperties                 2 calls
        0 ms  BeforeBuild                                2 calls
        0 ms  StaticWebAssetsPrepareForRun               1 calls
        0 ms  GetReferenceAssemblyPaths                  2 calls
        0 ms  _CopySourceItemsToOutputDirectory          2 calls
        0 ms  Compile                                    2 calls
        0 ms  GenerateImplicitNamespaceImports           2 calls
        0 ms  GenerateAssemblyInfo                       2 calls
        0 ms  CreateSatelliteAssemblies                  2 calls
        0 ms  InitializeSourceControlInformation         2 calls
        0 ms  PrepareProjectReferences                   2 calls
        0 ms  CreateCustomManifestResourceNames          2 calls
        0 ms  ResolvePackageDependenciesForBuild         2 calls
        0 ms  _BuildCopyStaticWebAssetsPreserveNewest    1 calls
        0 ms  AfterResolveReferences                     2 calls
        0 ms  CoreBuild                                  2 calls
        0 ms  BeforeResolveReferences                    2 calls
        0 ms  AddSourceRevisionToInformationalVersion    2 calls
        0 ms  AfterCompile                               2 calls
        0 ms  PrepareResources                           2 calls
        0 ms  _ChooseAppHost                             1 calls
        0 ms  GenerateMSBuildEditorConfigFile            2 calls
        0 ms  GetTargetPath                              2 calls
        0 ms  AfterResGen                                2 calls
        0 ms  PrepareForRun                              2 calls
        0 ms  _AddOutputPathToGlobalPropertiesToRemove   2 calls
        0 ms  BuildOnlySettings                          2 calls
        0 ms  IncludeTransitiveProjectReferences         2 calls
        0 ms  _GenerateScopedCssFiles                    2 calls
        0 ms  EnableIntermediateOutputPathMismatchWarning   2 calls
        0 ms  ComputeIntermediateSatelliteAssemblies     1 calls
        0 ms  _DefaultMicrosoftNETPlatformLibrary        2 calls
        0 ms  ResolveLockFileAnalyzers                   2 calls
        0 ms  _ComputeScopedCssStaticWebAssets           1 calls
        0 ms  _CheckForUnsupportedHostingUsage           2 calls
        0 ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   2 calls
        0 ms  RazorGetAssemblyAttributes                 1 calls
        0 ms  _CheckForObsoleteDotNetCliToolReferences   2 calls
        0 ms  _ReportUpgradeNetAnalyzersNuGetWarning     2 calls
        0 ms  ExpandSDKReferences                        2 calls
        0 ms  _ResolveMvcAssemblyAttributes              1 calls
        0 ms  ValidateToolsVersions                      1 calls
        0 ms  CopyAdditionalFiles                        2 calls
        0 ms  _BeforeVBCSCoreCompile                     2 calls
        0 ms  ValidateCommandLineProperties              2 calls
        0 ms  ResolveSDKReferences                       2 calls
        0 ms  AddImplicitDefineConstants                 2 calls
        0 ms  _CheckForUnsupportedNETCoreVersion         2 calls
        0 ms  ComputeDependencyFileCompilerOptions       2 calls
        0 ms  AddTransitiveFrameworkReferences           2 calls
        0 ms  CollectPackageReferences                   2 calls
        0 ms  _AddScopedCssBundles                       1 calls
        0 ms  PostprocessVSRepxManifestResourceNames     1 calls
        0 ms  BundleScopedCssFiles                       1 calls
        0 ms  ValidateExecutableReferences               1 calls
        0 ms  _CheckForTransitiveWindowsDesktopDependencies   2 calls
        0 ms  _CheckForUnsupportedCppNETCoreVersion      2 calls
        0 ms  _CheckForLanguageAndFeatureCombinationSupport   2 calls
        0 ms  _GetProjectJsonPath                        2 calls
        0 ms  _ComputeNETCoreBuildOutputFiles            2 calls
        0 ms  _CreateAppHost                             1 calls
        0 ms  _ResolveScopedCssOutputs                   1 calls
        0 ms  _EnsureContentRootFolders                  1 calls
        0 ms  _ComputePackageReferencePublish            2 calls
        0 ms  _ComputeCssScope                           1 calls
        0 ms  AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects   2 calls
        0 ms  GetTargetPathWithTargetPlatformMoniker     2 calls
        0 ms  ReferencedPathMaps                         1 calls
        0 ms  AddStaticWebAssetsManifest                 1 calls
        1 ms  _GetAppHostPaths                           1 calls
        1 ms  UpdateExistingPackageStaticWebAssets       1 calls
        1 ms  _CheckForUnsupportedAppHostUsage           2 calls
        1 ms  _BuildCopyStaticWebAssetsAlways            1 calls
        1 ms  _GenerateSatelliteAssemblyInputs           2 calls
        1 ms  _SetTargetFrameworkMonikerAttribute        2 calls
        1 ms  PreprocessVSRepxManifestResourceNames      1 calls
        1 ms  GetAssemblyAttributes                      2 calls
        1 ms  GenerateMSBuildEditorConfigFileShouldRun   2 calls
        1 ms  GetAssemblyVersion                         2 calls
        1 ms  ResolveRazorComponentInputs                1 calls
        1 ms  GenerateBuildRuntimeConfigurationFiles     2 calls
        1 ms  _SplitProjectReferencesByFileExistence     2 calls
        1 ms  _CreateRazorAssemblyInfoInputsCacheFile    1 calls
        1 ms  _ResolveCssScopes                          1 calls
        1 ms  _CoreGenerateRazorAssemblyInfo             1 calls
        1 ms  ResolveReferences                          2 calls
        1 ms  _GenerateCompileInputs                     2 calls
        1 ms  CoreResGen                                 2 calls
        1 ms  GetTargetFrameworks                        1 calls
        1 ms  _ComputeSkipAnalyzers                      2 calls
        1 ms  _ResolveBundlingConfiguration              1 calls
        1 ms  UpdateLegacyPackageScopedCssBundles        1 calls
        2 ms  ResolveRazorConfiguration                  1 calls
        2 ms  _SplitStaticWebAssetsByCopyOptions         1 calls
        2 ms  _DiscoverMvcApplicationParts               1 calls
        2 ms  _BlockWinMDsOnUnsupportedTFMs              2 calls
        2 ms  _GenerateRuntimeConfigurationFilesInputCache   2 calls
        2 ms  ResolveStaticWebAssetsConfiguration        1 calls
        3 ms  AddGlobalAnalyzerConfigForPackage_MicrosoftCodeAnalysisNetAnalyzers   2 calls
        3 ms  _ComputeUserRuntimeAssemblies              2 calls
        3 ms  _CopyOutOfDateSourceItemsToOutputDirectory   2 calls
        3 ms  _GetCopyToOutputDirectoryItemsFromThisProject   2 calls
        3 ms  ResolveLockFileCopyLocalFiles              2 calls
        3 ms  GenerateTargetFrameworkMonikerAttribute    2 calls
        3 ms  _CheckForNETCoreSdkIsPreview               2 calls
        3 ms  SplitResourcesByCulture                    2 calls
        3 ms  CreateManifestResourceNames                1 calls
        3 ms  _CollectAllScopedCssAssets                 1 calls
        3 ms  ResolveRazorGenerateInputs                 1 calls
        4 ms  UpdateAspNetToFrameworkReference           2 calls
        4 ms  ResolveLockFileReferences                  2 calls
        4 ms  GenerateNETCompatibleDefineConstants       2 calls
        4 ms  CoreGenerateImplicitNamespaceImports       2 calls
        4 ms  CheckForDuplicateItems                     2 calls
        4 ms  CheckForImplicitPackageReferenceOverrides   2 calls
        5 ms  _ComputeReferenceAssemblies                2 calls
        5 ms  ApplyImplicitVersions                      2 calls
        5 ms  GetNativeManifest                          1 calls
        6 ms  CoreGenerateAssemblyInfo                   2 calls
        6 ms  _CheckForCompileOutputs                    2 calls
        6 ms  _RestoreStaticWebAssetsBuildAssets         1 calls
        6 ms  CreateGeneratedAssemblyInfoInputsCacheFile   2 calls
        6 ms  _GenerateCompileDependencyCache            2 calls
        6 ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   2 calls
        6 ms  ResolveReferencedProjectsStaticWebAssets   1 calls
        7 ms  AssignProjectConfiguration                 2 calls
        9 ms  _SetEmbeddedWin32ManifestProperties        2 calls
        9 ms  _ResolveGeneratedRazorCompileInputs        1 calls
        9 ms  GenerateProgramFile                        1 calls
        9 ms  GenerateBuildDependencyFile                2 calls
       10 ms  CopyFilesToOutputDirectory                 2 calls
       10 ms  _CheckForInvalidConfigurationAndPlatform   2 calls
       10 ms  GetTargetFrameworksWithPlatformForSingleTargetFramework   1 calls
       11 ms  PrepareForBuild                            2 calls
       15 ms  ValidateSolutionConfiguration              1 calls
       15 ms  ResolveFrameworkReferences                 2 calls
       16 ms  AssignTargetPaths                          2 calls
       19 ms  ResolveScopedCssInputs                     1 calls
       20 ms  AssignRazorGenerateTargetPaths             1 calls
       20 ms  _CollectTargetFrameworkForTelemetry        2 calls
       20 ms  _GetRestoreProjectStyle                    2 calls
       20 ms  CoreCompile                                2 calls
       21 ms  _PrepareRazorSourceGenerators              1 calls
       24 ms  GetCopyToOutputDirectoryItems              2 calls
       25 ms  IncrementalClean                           2 calls
       26 ms  ResolveTargetingPackAssets                 2 calls
       27 ms  GenerateMSBuildEditorConfigFileCore        2 calls
       46 ms  _CopyFilesMarkedCopyLocal                  2 calls
       52 ms  GenerateStaticWebAssetsManifest            1 calls
       53 ms  ResolvePackageAssets                       2 calls
       63 ms  _CopyReferenceOnlyAssembliesForBuild       2 calls
       68 ms  ResolveProjectStaticWebAssets              1 calls
       85 ms  ResolveProjectReferences                   2 calls
       85 ms  _HandlePackageFileConflicts                2 calls
       99 ms  FindReferenceAssembliesForReferences       2 calls
      124 ms  _CleanGetCurrentAndPriorFileWrites         2 calls
      180 ms  ProcessFrameworkReferences                 2 calls
      313 ms  ResolveAssemblyReferences                  2 calls
      538 ms  _GetProjectReferenceTargetFrameworkProperties   2 calls
     2254 ms  Build                                      3 calls

Task Performance Summary:
        0 ms  ValidateExecutableReferences               1 calls
        0 ms  MergeManifestProperties                    1 calls
        0 ms  ComputeCssScope                            1 calls
        0 ms  CombineXmlElements                         1 calls
        0 ms  UpdatePackageStaticWebAssets               1 calls
        0 ms  CombineTargetFrameworkInfoProperties       1 calls
        1 ms  GetAssemblyVersion                         2 calls
        1 ms  FindInList                                 1 calls
        1 ms  ApplyCssScopes                             1 calls
        1 ms  DefineStaticWebAssets                      2 calls
        1 ms  FindAppConfigFile                          2 calls
        1 ms  AssignCulture                              2 calls
        1 ms  Delete                                     2 calls
        1 ms  ResolveFrameworkReferences                 2 calls
        1 ms  ApplyImplicitVersions                      2 calls
        1 ms  CheckForUnsupportedWinMDReferences         2 calls
        1 ms  CollectStaticWebAssetsToCopy               1 calls
        2 ms  JoinItems                                  2 calls
        2 ms  GenerateV1StaticWebAssetsManifest          1 calls
        2 ms  EncodeRazorInputItem                       1 calls
        2 ms  ConvertToAbsolutePath                      2 calls
        2 ms  CreateCSharpManifestResourceName           1 calls
        2 ms  CheckIfPackageReferenceShouldBeFrameworkReference   4 calls
        3 ms  ShowPreviewMessage                         2 calls
        3 ms  ResolveAllScopedCssAssets                  1 calls
        3 ms  CheckForImplicitPackageReferenceOverrides   2 calls
        3 ms  AllowEmptyTelemetry                        2 calls
        3 ms  CheckForDuplicateItems                     6 calls
        3 ms  Hash                                       7 calls
        4 ms  ReadStaticWebAssetsManifestFile            1 calls
        4 ms  Message                                    7 calls
        4 ms  CheckForDuplicateFrameworkReferences       2 calls
        5 ms  ReadLinesFromFile                          2 calls
        5 ms  CopyRefAssembly                            2 calls
        5 ms  RemoveDuplicates                           4 calls
        5 ms  GetRestoreProjectStyleTask                 2 calls
        5 ms  AssignProjectConfiguration                 2 calls
        6 ms  ComputeReferencedProjectAssets             1 calls
        8 ms  GetFrameworkPath                           2 calls
        8 ms  AssignTargetPath                          13 calls
        9 ms  MakeDir                                    3 calls
        9 ms  WriteLinesToFile                          11 calls
       12 ms  GetPackageDirectory                       16 calls
       13 ms  GenerateMSBuildEditorConfig                2 calls
       14 ms  CallTarget                                 4 calls
       16 ms  GenerateStaticWebAssetsDevelopmentManifest   1 calls
       19 ms  ResolveAppHosts                            2 calls
       19 ms  DiscoverDefaultScopedCssItems              1 calls
       25 ms  ResolveTargetingPackAssets                 2 calls
       33 ms  GenerateStaticWebAssetsManifest            1 calls
       46 ms  GetReferenceNearestTargetFrameworkTask     1 calls
       51 ms  ResolvePackageAssets                       2 calls
       57 ms  DiscoverStaticWebAssets                    1 calls
       71 ms  ResolvePackageFileConflicts                2 calls
      104 ms  FindUnderPath                             10 calls
      110 ms  Copy                                       9 calls
      145 ms  ProcessFrameworkReferences                 2 calls
      309 ms  ResolveAssemblyReference                   2 calls
     2746 ms  MSBuild                                    7 calls

**Comment by wayneforrest** [comment]
It seems this method call is significantly faster in **.NET 6 preview**:

GetProjectReferenceTargetFrameworkProperties:

**.NET 3.1**
5654 ms _GetProjectReferenceTargetFrameworkProperties 2 calls

**.NET 6 preview**
538 ms _GetProjectReferenceTargetFrameworkProperties 2 calls
