### ISSUE TITLE
Minimal API endpoints do not appear in OpenAPI if WithGroupName() is used

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36414]
### Describe the bug

If `WithGroupName(string)` is used with a Minimal APIs endpoint, it disappears from being displayed in OpenAPI.

#### Using `WithGroupName()`

![image](https://user-images.githubusercontent.com/1439341/132957753-ff83cb2c-ba49-4d44-95da-74f42ca05f7c.png)

#### No `WithGroupName()`

![image](https://user-images.githubusercontent.com/1439341/132957768-c1adbdc4-0a0f-486f-aaa3-181e8133878d.png)

### To Reproduce

Create an empty ASP.NET Core 6 project with a reference to `Swashbuckle.AspNetCore` with the below code as `Program.cs`.

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = builder.Environment.ApplicationName, Version = "v1" });
});

var app = builder.Build();

app.MapGet("/greeting", () => "Hello, world")
   .WithGroupName("Greetings");

app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.EnableTryItOutByDefault();
    options.SwaggerEndpoint("/swagger/v1/swagger.json", $"{builder.Environment.ApplicationName} v1");
});

app.Run();
```

### Further technical details

.NET SDK version `6.0.100-rc.1.21460.8`

**Comment by captainsafia** [comment]
Thanks for testing these scenarios, @martincostello!

So, the GroupName metadata is designed to be used when generating multiple Swagger documents. So the following:

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = $"{builder.Environment.ApplicationName} v1", Version = "v1" });
    options.SwaggerDoc("v2", new() { Title = $"{builder.Environment.ApplicationName} v2", Version = "v2" });
});

var app = builder.Build();

app.MapGet("/greeting", () => "Hello, world")
   .WithGroupName("v1");

app.MapGet("/farewell", () => "Bye, world")
   .WithGroupName("v2");

app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.EnableTryItOutByDefault();
    options.SwaggerEndpoint("/swagger/v1/swagger.json", $"{builder.Environment.ApplicationName} v1");
    options.SwaggerEndpoint("/swagger/v2/swagger.json", $"{builder.Environment.ApplicationName} v2");
});

app.Run();
```

Should work to display the `/greeting` API under the v1 subsection and the `/farewell` API under the v2 subsection.

![image](https://user-images.githubusercontent.com/1857993/133007281-8af2d555-0c53-4c0d-a1ce-89828d804b65.png)

![image](https://user-images.githubusercontent.com/1857993/133007291-d826f8ea-144a-481c-99c9-70bce2e46d31.png)

`WithTags` should work for grouping endpoints within a document.

**Comment by martincostello** [comment]
Ah, fair enough, my mistake!

I guess the nomenclature in this case is slightly confusing, but I'd probably have ended up doing the right thing via trial-and-error if the version I was using had `WithTags()` 👍

**Comment by captainsafia** [comment]
@martincostello No worries! BTW, I misspoke. The `WithTags` stuff doesn't totally work yet. You'll need to use the changes in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2210 to get it working in the E2E.

Closing this one for now.
