### ISSUE TITLE
Support BindAsync() without ParameterInfo for Minimal APIs

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36415]
### Is your feature request related to a problem? Please describe.

If a user wishes to use custom data binding for Minimal APIs using the `BindAsync()` pattern but does not require the `ParameterInfo` parameter when using Visual Studio, the IDE will warn about the unused `parameter` argument with `IDE0060`. I would _assume_ that other static analyzers would produce similar warnings, though I haven't tested/validated this.

While these warnings can be ignored/suppressed on an ad-hoc basis, they create noise. Static analysis tools will not warn about such unused parameters when a method is implementing a contract using an abstract method or an interface, but as neither use case applies here, the warning fires.

Omitting the parameter breaks the contract for custom binding with Minimal APIs, so it cannot be removed without stopping the feature from working.

### Describe the solution you'd like

Minimal APIs considers the `ParameterInfo` to be "optional" (not an optional parameter as in the formal C# language specification), so that if the parameter is not needed by the developer/implementation, it can be omitted and the custom binding behaviour will still work.

```csharp
public static ValueTask<PagingData?> BindAsync(HttpContext context)
```

**Comment by davidfowl** [comment]
I'm not sure this is valid for a couple of reasons:
- We wanted to support a single API shape because it's simpler
- If we provided an interface you had to implement, you'd have the same problem.

**Comment by martincostello** [comment]
Yep I get the simplicity argument, just a suggestion for consideration from a "UX" angle.

For the second point, I wasn't suggesting having this as an interface, but the tooling is usually smart enough that it recognises parameters that aren't used are needed to conform to the interface, so it won't raise this kind of warning.

In the case of Visual Studio and the built-in SDK analysers it could of course be a recognised pattern in the future to prevent the warning in the first place. It's just that in that case it needs to be fixed per analyser, so the net effort to prevent the noise would be greater (in principle, if not in fact).

**Comment by davidfowl** [comment]
But I'm saying if we had an interface (which we will eventually) you'll have the same problem.

**Comment by martincostello** [comment]
But I don't think you would have the same problem (unless we're talking about different things and I'm missing your point).

For example, if I implemented this interface like the below, the IDE/analyzers have been smart enough in my experience to not emit a warning as they understand that the argument is "used" by the interface declaration, even if it is never referenced in the method body.

```csharp
public interface IValidate<T>
{
    bool IsValid(T value);
}

public class AlwaysValid<T> : IValidate<T>
{
    public bool IsValid(T value)
    {
        // Don't care about value, YOLO
        return true;
    }
}
```

**Comment by davidfowl** [comment]
Ah, that's the thing I'm missing then.
