### ISSUE TITLE
WebApplicationBuilder does not canonicalize the --contentRoot argument

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36416]
### Describe the bug

If a custom content root is specified via the `--contentRoot` command-line argument to a application using WebApplicationBuilder, the user-provider path is not canonicalized before use.

```sh
> dotnet run -- --contentRoot=.\..\.
Building...
ContentRoot Path: C:\Coding\martincostello\MinimalApisRepros\bin\Debug\net6.0\.\..\.
```

Running without the argument produces the following:

```sh
> dotnet run
Building...
ContentRoot Path: C:\Coding\martincostello\MinimalApisRepros
Environment CurrentDirectory: C:\Coding\martincostello\MinimalApisRepros
```

In the above example I would expect the `ContentRootPath` value to be _either_ `C:\Coding\martincostello\MinimalApisRepros\bin\Debug` or `C:\Coding\martincostello`.

I'm not sure if the intended behaviour is to resolve relative to the current directory, or the assembly location. If the former then it's wrong and not canonicalized, if the latter then it's just not canonicalized.

### To Reproduce

Build and run the following application with the command `dotnet run -- --contentRoot=.\..\.`.

```csharp
var builder = WebApplication.CreateBuilder(args);
Console.WriteLine($"ContentRoot Path: {builder.Environment.ContentRootPath}");
Console.WriteLine($"Environment CurrentDirectory: {Environment.CurrentDirectory}");
```

### Further technical details

.NET SDK version `6.0.100-rc.1.21460.8`

**Comment by davidfowl** [comment]
I'm guessing this is the case today as well since .NET 3.x.

**Comment by rafikiassumaniMSFT** [comment]
Triage: We will re-evaluate this issue during .NET7 planning.

**Comment by davidfowl** [comment]
This was fixed in .NET 6
