### ISSUE TITLE
Minimal APIs route constraints break OpenAPI requests

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36413]
### Describe the bug

If a Minimal API endpoint uses a route constraint, for example `"/status/{code:range(200, 599)}"`, the constraint is exposed to OpenAPI documentation incorrectly, which causes the API to be called incorrectly, resulting in an HTTP 404.

`https://localhost:7168/status/%7Bcode:range(200,%20599)%7D`

![image](https://user-images.githubusercontent.com/1439341/132957637-3689240d-14b5-46a2-ac86-619dfade60ec.png)

### To Reproduce

Create an empty ASP.NET Core 6 project with a reference to `Swashbuckle.AspNetCore` with the below code as `Program.cs`.

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = builder.Environment.ApplicationName, Version = "v1" });
});

var app = builder.Build();

app.MapGet("/status/{code:range(200, 599)}", (int code) => Results.StatusCode(code));

app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.EnableTryItOutByDefault();
    options.SwaggerEndpoint("/swagger/v1/swagger.json", $"{builder.Environment.ApplicationName} v1");
});

app.Run();
```

### Further technical details

.NET SDK version `6.0.100-rc.1.21460.8`

**Comment by martincostello** [comment]
FYI, I didn't try any of the other possible constraints (like `length(n)`), but I assume they would have similar issues.

**Comment by captainsafia** [comment]
I think this is likely a Swashbuckle issue, similar to the one we had recently with the `?` in optional route parameters borking route rendering.

For this one, it looks like it is also happening for route constraints in controller-based APIs as well.

**Comment by BrennanConroy** [comment]
Done!
