### ISSUE TITLE
Support more ProblemDetails Titles out-of-the-box for Results.Problem()

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36417]
### Is your feature request related to a problem? Please describe.

If a developer using Minimal Actions uses the `Results.Problem()` method with an HTTP status code that is not part of [`ProblemDetailsDefaults`](https://github.com/dotnet/aspnetcore/blob/b33b4d4453d93be12a847a5e0c222d86edd706a0/src/Shared/ProblemDetailsDefaults.cs#L13-L65) by default, then without it being explicitly set themselves, a default `title` is not returned in the response.

Take the following intentionally obscure example:

```csharp
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/teapot", () => Results.Problem("I like tea", statusCode: 418));

app.Run();
```
Calling the `/teapot` resource will return the following JSON:

```json
{"status":418,"detail":"I like tea"}
```

If more default HTTP status codes were built in, the default experience would be more informative:

```json
{"title":"I'm a teapot","status":418,"detail":"I like tea"}
```

### Describe the solution you'd like

A more comprehensive list of HTTP status code descriptions are available in the [`ReasonPhrases`](https://github.com/dotnet/aspnetcore/blob/b33b4d4453d93be12a847a5e0c222d86edd706a0/src/Http/WebUtilities/src/ReasonPhrases.cs#L12) class.

However, using it directly in `ObjectResult` [here](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Http/Http.Results/src/ObjectResult.cs#L104-L108) is not possible as `Microsoft.AspNetCore.WebUtilities` is not referenced by `Microsoft.AspNetCore.Http.Results`.

The out-of-the-box experience for `Results.Problem()` could be improved with one of the following:

1. Make `Microsoft.AspNetCore.Http.Results` reference `Microsoft.AspNetCore.WebUtilities`, and then use `ReasonPhrases.GetReasonPhrase(string)` as a fallback.
2. Refactor the HTTP status code descriptions into shared source, and then have both assemblies use it to enhance `ObjectResult` and/or `ProblemDetailsDefaults` and to provide the implementation for `ReasonPhrases.GetReasonPhrase(string)`.

Otherwise, the developer has to manually specify the title for any HTTP status codes not already catered for, like this:

```csharp
// using Microsoft.AspNetCore.WebUtilities;
app.MapGet("/teapot", () => Results.Problem("I like tea", statusCode: 418, title: ReasonPhrases.GetReasonPhrase(418)));
```

### Additional context

Found using .NET SDK version `6.0.100-rc.1.21460.8`

**Comment by rafikiassumaniMSFT** [comment]
Triage: We will re-evaluate this during .NET7 planning.

**Comment by martincostello** [comment]
@brunolins16 Would your changes in #42384 make this easier to implement with things being moved around in the layers? If you think it does I'll take a look once your PR gets merged.

**Comment by brunolins16** [comment]
@martincostello probably not but let me check how close we are, because I did not know about this issue before. Thanks.

**Comment by GREsau** [comment]
I've run into this problem, so an improvement here would be very nice. When I implemented an API Gateway using [YARP](https://github.com/microsoft/reverse-proxy), it came as a bit of a surprise that `Results.Problem(statusCode: 502)` produced such an empty response.

Would it also be worth adding more default `type`s? So e.g. the 418 example above may result in:
`{"title":"I'm a teapot","status":418,"detail":"I like tea","type":"https://tools.ietf.org/html/rfc2324#section-2.3.2"}`

**Comment by martincostello** [comment]
I'd be happy to take a stab at implementing the changes for this if the aspnetcore team could give a steer as to a solution to the layering question at the top. Of course if it's too big a change to do at this stage without other changes, then it can stay here in the backlog.

**Comment by brunolins16** [comment]
@martincostello I'd be more than happy to help on it. 

I did not participate in the decision of creating the `ProblemDetailsDefaults` and not reuse the `ReasonPhrases` class but, in my opinion, I totally agree with you, and I don't see a reason why we couldn't reference `WebUtilities` from other layers (again I might have been missing some aspect of this change).


I like this approach:

>Refactor the HTTP status code descriptions into shared source, and then have both assemblies use it to enhance ObjectResult and/or ProblemDetailsDefaults and to provide the implementation for ReasonPhrases.GetReasonPhrase(string).

The **very initial** simple idea that I have in mind, would love to hear @dotnet/minimal-apis thoughts, is change the `Phrases` dictionary to include the `Reference URL` without changing how the `GetReasonPhrase` works, since it is a public API, and maybe expose another public API that expose both information. With that we can update the `ProblemDetailsDefaults` to use this new method in `Apply` instead the dictionary owned by `ProblemDetailsDefaults` (that could be removed). 

I see it as a simple change if no problem referencing `WebUtilities`.

**Comment by martincostello** [comment]
Thanks for the feedback Bruno. I'll look at pushing up a draft with your suggested preferred approach some time in the next week for you and the team to weigh-in on.

**Comment by brunolins16** [comment]
Let me have a discussion about this design before you start.

**Comment by khellang** [comment]
@martincostello Will you also update the URLs to RFC9110?

**Comment by martincostello** [comment]
I wasn't aware of a need to do it, but I can do so when I make the change if that's something the team is fine with.

**Comment by khellang** [comment]
Given all the existing URLs point to obsolete RFCs, I think it makes sense 😅

**Comment by brunolins16** [comment]
> Let me have a discussion about this design before you start.

@martincostello I did not hear anything against referencing `WebUtilities`, so, feel free to work on a draft.

**Comment by martincostello** [comment]
Great, thanks Bruno - I'll try and push up something tomorrow.

**Comment by martincostello** [comment]
#43232
