### ISSUE TITLE
Issues building from source. 

### ISSUE THREAD

**Issue by tombatron** [dotnet/aspnetcore#36410]
### Issue
I was attempting to follow the build instructions from here: [https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md)

After cloning (including submodules) and then invoking `.\restore.cmd` (with no errors or warnings), navigating to `\src\Caching\` and then starting Visual Studio 2019 via the `.\startvs.cmd` script, Visual Studio 2019 (Community Edition) opens "Caching.slnf".

### Exceptions (if any)

In total, 300 warnings are encountered that all look similar to:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Users\tommy\.nuget\packages\microsoft.netcore.app.ref\7.0.0-alpha.1.21457.1\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.Extensions.Caching.SqlServer (net6.0)		1	Active
```

In total 152 errors are encountered when trying to build, and they all look similar to the following:

```
1>CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.UseIsNullCheck.CSharpUseIsNullCheckForReferenceEqualsDiagnosticAnalyzer cannot be created from C:\Users\tommy\Projects\aspnetcore\.dotnet\sdk\7.0.100-alpha.1.21457.7\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```
### Further technical details

`main` branch @ commit b33b4d4453d93be12a847a5e0c222d86edd706a0

Microsoft Visual Studio Community 2019 - 16.11.2

Windows 10 - Version 20H2 (Build 19042, 1165)

I've verified that the DLLs are in the appropriate directories, for example:

![image](https://user-images.githubusercontent.com/119369/132956168-8a6458fe-cef7-4c2f-afa1-ec92c6333599.png)

**Comment by Tratcher** [comment]
Need to update the instructions, VS 2022 is now required.

**Comment by tombatron** [comment]
Looks like that did the trick! Once I got all of the required bits and bobbles installed I was able to build from within Visual Studio. 

![image](https://user-images.githubusercontent.com/119369/132999660-a6f3f3e7-b9fd-4908-bf19-acee2a51c4d4.png)

Thanks for the support on the weekend!
