### ISSUE TITLE
Blazor WASM : cannot convert from 'System.TimeSpan' to 'System.DateTime'

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#36427]
I am getting the following error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1503	Argument 1: cannot convert from 'System.TimeSpan' to 'System.DateTime'	XXXXXV6New.Client
```	

I am storing Just the Time (like 9:00 AM") to indicate start time and stop time in Time(7) field of Azure SQL DB.

Dbcontext generates that field as     
`public TimeSpan StartTime { get; set; }`

I am trying to bind this to input element
```
<input type="time" class="form-control time-control"    @bind:event="oninput"
                                   @bind="@_OrgLocation.StartTime" />
```

which is resulting into above mentioned error.

How do i resolve this issue ?

The idea is to store start and Stop time in database(just the Time part with AM/PM) like 9:00 am to 5:00 PM

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The `input type="time"` component is designed to work with `TimeSpan` and there is no conversation mechanism from DateTime to TimeSpan available out of the box. You can create a property which handles the conversation internally and bind to that instead.

**Comment by nssidhu** [comment]
if it does work with TimeSpan, the variable that is bound is of type TimeSpan, than why am i getting the Error ?
