### ISSUE TITLE
New analyzer rule: Don't write to your own parameters

### ISSUE THREAD

**Issue by VahidN** [dotnet/aspnetcore#36429]
This rule [is explained here](https://github.com/dotnet/aspnetcore/issues/24599#issuecomment-697588562) for the Blazor apps and a lot of newcomers don't know it and can be mistakenly forgotten easily.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. We plan to add an analyzer to help with this. The issue tracking that work is #26230
