### ISSUE TITLE
.NET 6.0 ASP.NET MVC DataAnnotations

### ISSUE THREAD

**Issue by kjdamen** [dotnet/aspnetcore#36437]
When you apply data annotations to a model and a string property has no attributes applied you receive a message that the property is required.

**Example controller**
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebApplication19.Controllers;
[ApiController]
[Route("[controller]")]
public class ExampleController : ControllerBase
{
    private readonly ILogger<ExampleController> _logger;

    public ExampleController(ILogger<ExampleController> logger)
    {
        _logger = logger;
    }

    [HttpPost]
    public IActionResult Test(Example test)
    {
        if(ModelState.IsValid)
        {
            _logger.LogInformation("Valid");
        }

        return Ok();
    }
}

public class Example
{
    [Required]
    public string FirsName {  get; set; }

    public string LastName { get; set; }
}

**Post**
{
  "firsName": "string"
}

**Result:**

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-1993612d16178692adc50903e7dfdd65-91b726cdf7164c74-00",
  "errors": {
    "LastName": [
      "The LastName field is required."
    ]
  }
}

**Expected result**
You would expect an Ok result here because the last name property is not required.

**Comment by sackri10** [comment]
I have tested a similar example with .NET 6 Preview and was not getting any validations errors if the Required attribute is not applied. Could you please some repo link to replicate the same...

**Comment by pranavkm** [comment]
@kjdamen, it's very likely the nullable annotations: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#non-nullable-reference-types-and-required-attribute

**Comment by kjdamen** [comment]
Thank you @pranavkm
