### ISSUE TITLE
Bug in preview 2022 - Rolling back from .net6 to .net5 in Blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36443]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-in-preview-2022---Rolling-back-from-/1520699)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Latest 2019]
My Blazor project worked fine when I changed in the project settings from .net5 to .net6, it builds, it launches in the browser and works as intended.

When I rollback by changing the project setting to .net5 from .net6 again, it builds, it launches in the browser, however... SignalR seems to then have a meltdown.

The project works fine in 2019, but in 2022 I get the following in the console:

`uncaught (in promise) error: failed to invoke 'startcircuit' due to an error on the server.`

Once it has run in 2019 fine, it then works again in 2022.

---
#### Feedback Bot on 9/2/2021, 06:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/8/2021, 08:33 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend cleaning up the project by manually removing `bin` and `obj` folders after switching the TFM.
