### ISSUE TITLE
Is it considerable to align the naming(version) of .NET stacks with .NET 7?

### ISSUE THREAD

**Issue by ScriptBox99** [dotnet/aspnetcore#36447]
Hello dear .NET Team and community members.
I would like to ask and was wondering we could expect to see more aligned naming of version of .NET with each coming major release.
To read many blog posts and Microsoft docs also has mentioned like that 'ASP.NET Core in .NET 5', 'in .NET 6', Blazor, EF Core has following same manner of context.
Since .NET 5 has announced as the first unified .NET as the future of .NET roadmap, TFM(net5.0), for .NET 6(net6.0) such I like it a lot because it looks very clear to understand and more to do.
But the remains of each stack of .NET to be clear always has to designate which .NET with 'in .NET 5', 'in .NET 6', that means .NET 7 would be same too.
After .NET 6 release the GA, I think no more conflicts between .NET and .NET Framework stacks for the versioning. 
So since .NET 7 release cycle, could consider the aligned version of each .NET stack such ASP.NET MVC, WebAPI, Razor, Blazor even WinForm, WPF too.
We may call most of all the version 7 for each stack except the MAUI.

.NET 5, 6 (.NET Core 3.1)
- ASP.NET Core MVC, WebAPI, Razor Pages, 
- EF Core
- Blazor
- WinForm
- WPF

.NET Framework
- ASP.NET MVC, WebAPI, WebForm
- EF
- WinForm
- WPF
- As I remember, the last version was MVC5, anyway.

.NET 7 (it may no more 'Core' veriant for each stack)
- ASP.NET 7, MVC 7, WebAPI 7, like that
- EF 7
- Blazor 7
- MAUI 
- WinForm 7
- WPF 7

I hope this idea would not bothering much for many folks even before the GA of .NET 6. 
Thanks.

**Comment by javiercn** [comment]
@ScriptBox99 thanks for contacting us.

This issue tracker is mostly focused on product issues and not a suitable place for this type of discussions, since it affects the whole ecosystem and not just ASP.NET Core. While our product naming, branding and versioning might change in the future, it is extremely unlikely that will be the case for .NET 6.0.

/cc: @danroth27 @DamianEdwards @LadyNaggaga
