### ISSUE TITLE
Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#36453]
### Describe the bug
Running the default blazor server-side template project with .NET 6.0 RC 1 throws an error. RC 1 is not officially released as of this writing, so I am testing with the [Release/6.0.1XX-rc1](https://github.com/dotnet/installer#installers-and-binaries) builds.

### To Reproduce
1. Use the builds for the upcoming RC1 as described in https://github.com/dotnet/aspnetcore/issues/35550#issuecomment-905796861
2. Clone https://github.com/Stamo-Gochev/blazor-host-error or create a new blazor server-side project from the CLI
3. Run the app (tested with both VS 2022 and from the CLI)

### Exceptions (if any)

Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21459.17
 Commit:    0edab9f0da

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21459.17\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21459.17 [C:\Program Files\dotnet\sdk]
```
- The IDE - VS 2022 17.0.0 Preview 3.1

**Comment by pranavkm** [comment]
@Stamo-Gochev I just tried this with `6.0.100-rc.1.21460.8` the most recent build of the installer and it appears to work correctly for me both on the CLI and VS 17.0 Preview 3.1. Are you able to reproduce this issue consistently / on a different machine than your regular dev machine?

If you'd like us to investigate this further attaching a binlog would be helpful. You can get one by running `dotnet build /bl` in the project directory which would produce a msbuild.binlog file. Note that binlogs capture your ambient environment variables. You can view what's being captured by it using a binlog viewer from https://msbuildlog.com.

**Comment by Stamo-Gochev** [comment]
@pranavkm As you have mentioned, the tool exposes some internal information, which I prefer not to share, so I am adding a modified screenshot of the result so that you can see the build is successful

<details>
<summary>msbuild log</summary>

![image](https://user-images.githubusercontent.com/1857705/133200004-4ad16fc2-08a2-458c-8e7d-01ff1498adde.png)

</details>

The command-line text that is generated by the program looks like (the exact path to the project is trimmed):

<details>
<summary>CLI</summary>

"C:\Program Files\dotnet\sdk\6.0.100-rc.1.21460.8\MSBuild.dll" D:\...\blazor-host-error\BlazorServerAppHostError\BlazorServerAppHostError.sln /t:Rebuild /v:diag /nologo /clp:NoSummary;Verbosity=minimal /bl

</details>

Here is the CLI result when the app is run with `dotnet run` and `http://localhost:5008` is opened in the browser. The message about `RazorSourceGenerator` will probably provide some clues:

<details>
<summary>dotnet run log</summary>

```

$ dotnet run                                                                  
Building...                                                                   
CSC : warning CS8784: Generator 'RazorSourceGenerator' failed to initialize. I
t will not contribute to the output and compilation errors may occur as a resu
lt. Exception was of type 'FileNotFoundException' with message 'Could not load
 file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=6.0.0.0, Cultu
re=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file 
specified.' [D:\...\blazor-host-error\BlazorServerA
ppHostError\BlazorServerAppHostError\BlazorServerAppHostError.csproj]         
info: Microsoft.Hosting.Lifetime[14]                                          
      Now listening on: https://localhost:7259                                
info: Microsoft.Hosting.Lifetime[14]                                          
      Now listening on: http://localhost:5008                                 
info: Microsoft.Hosting.Lifetime[0]                                           
      Application started. Press Ctrl+C to shut down.                         
info: Microsoft.Hosting.Lifetime[0]                                           
      Hosting environment: Development                                        
info: Microsoft.Hosting.Lifetime[0]                                           
      Content root path: D:\...\blazor-host-error\B
lazorServerAppHostError\BlazorServerAppHostError                              
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]    
      An unhandled exception has occurred while executing the request.        
      System.InvalidOperationException: Cannot find the fallback endpoint spec
ified by route values: { page: /_Host, area:  }.                              
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndp
ointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
                                                                              
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWit
hPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, Ca
ndidateSet candidateSet)                                                      
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__
AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, 
Task matchTask)                                                               
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.
Invoke(HttpContext context) 
```

</details>

**Comment by pranavkm** [comment]
Could you include a screenshot of the `Csc` task? Specifically the `Analyzers` node passed to it? We stopped using `Microsoft.AspNetCore.Razor.Language` in the source generator at the start of rc1 so it's weird to see it show up in there with a fairly new build of the installer.

**Comment by Stamo-Gochev** [comment]
@pranavkm THe issue is no longer reproducible with `6.0.100-rc.1.21458.32`.
