### ISSUE TITLE
Publish Microsoft.AspNetCore.Components.CustomElements

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#36454]
This is an experimental package with sources at https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements

We need to publish the package to nuget.org if we want it to be realistically usable.

**Comment by mymatrixpixel** [comment]
@SteveSandersonMS Can you publish the package to nuget.org. Thanks

**Comment by SteveSandersonMS** [comment]
That's what this issue is tracking.

**Comment by SteveSandersonMS** [comment]
Done: https://www.nuget.org/packages/Microsoft.AspNetCore.Components.CustomElements

**Comment by crackalak** [comment]
@SteveSandersonMS I'm having trouble getting the nuget package to work, took a look inside and there isn't a `staticwebassets` directory containing the `BlazorCustomElements.js` file

![image](https://user-images.githubusercontent.com/4701936/133343175-98978ea9-7596-4453-86ee-ad413269c26e.png)
