### ISSUE TITLE
DotNetSteamReference does not exist

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#36461]
I'm trying to create an instance of `DotNetStreamReference`  in a Blazor component, but I don't see it available. I'm using .NET 6 Preview 7.

![image](https://user-images.githubusercontent.com/63487874/133102559-ff38371b-94f1-4a27-8635-94416400ebc6.png)

**Comment by ShreyasJejurkar** [comment]
As I can see those APIs are still unshipped.txt

https://github.com/dotnet/aspnetcore/blob/e6a5af6633f08890afbd99a6ca7687c623454768/src/JSInterop/Microsoft.JSInterop/src/PublicAPI.Unshipped.txt#L8-L12

Maybe move it to shipped.txt!?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
`DotNetStreamReference` will ship as part of the upcoming RC1 release.
