### ISSUE TITLE
Validate state of Blazor with RC2 bits

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#36471]
Here are all the details about the build to use for validation:

### Installer to use
Version: [6.0.100-rc.2.21463.4](https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe)

### Feed configuration
```xml
<configuration>
  <packageSources>
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by mkArtakMSFT** [comment]
@javiercn , @pranavkm , @SteveSandersonMS, @TanayParikh this is waiting for your input, guys.
As we've agreed earlier, please add a comment about the app that you're going to build for validation. We can have a follow-up conversation then.

**Comment by javiercn** [comment]
I'm going to build some calorie tracker app or something like that, I'll focus on auth, JS runtime components and MVC integration

**Comment by SteveSandersonMS** [comment]
I'm focusing on WebAssembly specific features with AOT and native dependencies. For example, I'll try integrating with some library implemented in another wasm-targetable language like Go. I don't yet know what business domain gimmick I'll choose but it will probably end up feeding into my DotNetConf talk.

It's not absolutely clear how quickly I can move with this since native dependencies isn't yet available properly in the SDK. I'll talk with @radical or @lewing later today about timings.

**Comment by pranavkm** [comment]
I was planning to pick up one of the rc1 scenarios with STJ source generation, hot reload, and Blazor that is listed in the app building exercise, but with rc2 bits.

**Comment by TanayParikh** [comment]
Building a CRUD app integrating with auth, hot reload, aot, and JS interop.

**Comment by Eilon** [comment]
I will do SPA/React/Angular/etc. to build a Todo app with some API endpoints.

**Comment by TanayParikh** [comment]
Should we move to validating the GA bits rather than RC? It may have additional patches (and better reflect the final release).

https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe

```
6.0.100-rtm.21466.6
```

**Comment by Eilon** [comment]
_Notes in progress, will update as I continue work_

I created a new React SPA using command line and then editing in VS.

Notes:

* Couldn't initially find SPA templates in VS. I used the `SPA` keyword, which returns nothing.
* VS Hot Reload won't stop nagging about Edit/Stop when I save the file: https://developercommunity.visualstudio.com/t/hot-reload-wont-stop-its-incessant-and-irritating/1541597?from=email
* Go To Definition for `typeof(Program)` navigates to wrong location: https://developercommunity.visualstudio.com/t/go-to-definition-for-typeofprogram-highlights-the/1541614?from=email
* `<Nullable>enable</Nullable>` is very irritating when I am starting out. Green squiggles _everywhere_ in all the code I write.
* Had to modify `setupProxy.js` to handle my `api/...` routes. Maybe it could be improved with a more generic pattern so it doesn't have to be modified in every app?

**Comment by pranavkm** [comment]
I spent some time building a Blazor WASM app that connected to https://my.plantnet.org/ do some plant identification and cataloging. My focus was on using STJ source generators with Blazor WASM, Blazor's new streaming capabilities, editor performance, and hot reload. 

* The source generators are fairly solid and I wasn't able to find any issues with it. Blazor WASM's hot reload capabilities are still lacking with custom attributes, so it did make it slightly annoying to not be able to add a new item to the JsonContext and continue from there without doing a full restart.
* Didn't find any issues with the streaming APIs. The API endpoint limits what the size of the images are, so I played around with uploading large pictures, resizing them, and then streaming them over HtpClient. It worked pretty nicely and no oddities to report there.
* I was using 17.0 p4.1 for this exercise. While the editor performance wasn't an issue, the auto-formatting was incredibly frustrating (Editor would add indentation where I wished it hadn't).
* I +1ed one https://github.com/dotnet/aspnetcore/issues/34823. I needed it, and given how easy it was in MVC, I found it someone annoying to handwrite this with Blazor. Either way, binding enum values works pretty nicely. Also +1 ed https://github.com/dotnet/aspnetcore/issues/28640. Thankfully the current package on NuGet.org worked pretty well.
* Some VS issues I filed:
      * https://developercommunity.visualstudio.com/t/blazor-webassembly-performing-hot-reload-when-the/1530899
      * https://developercommunity.visualstudio.com/t/pressing-the-stop-button-when-a-hot-reload-rude-ed/1530873
      * https://developercommunity.visualstudio.com/t/add-razor-component-does-not-have-an-icon/1530777
      * https://developercommunity.visualstudio.com/t/hot-reload-rude-edit-diagnostics-from-source-gener/1528293
