### ISSUE TITLE
Add tooling to validate the correctness of package versions in servicing updates

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#3647]
_From @natemcmaster on Thursday, July 12, 2018 9:38:05 PM_

Follow-up to https://github.com/aspnet/Universe/pull/1257. In this PR, I manually did a lot of work to figure out what were the versions to use as the pinned baseline. We should add:

* More tests to verify this work is correct
* Add tests which will invalidate the build in future servicing updates when something is updated
* Add tests to assert any changes to nuspec dependencies are expected

_Copied from original issue: aspnet/Universe#1258_

**Comment by JunTaoLuo** [comment]
We have implemented tests that has addressed these concerns.
