### ISSUE TITLE
Avoid duplicates in automatically generated endpoint names

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#36487]
Currently, we automatically generate an endpoint name for an endpoint based on the name of the method.

```
app.MapGet("/foo", Foo);
```

Will produce an `EndpointName` with a `Foo` method. In https://github.com/dotnet/aspnetcore/pull/36353, we added more aggressive throwing of exceptions for duplicate endpoint names.

This, in combination with the feature above, means it is more likely for features to run into the confusing error message if the duplicate endpoint name is defined in a 3rd-party library that the user cannot control.

We can resolve this by:

- Providing an option to disable automatic endpoint generation
- Always generating fully-qualified endpoint names

**Comment by BrennanConroy** [comment]
Triage: We should remove the default endpoint name for now

**Comment by captainsafia** [comment]
Revert completed.
