### ISSUE TITLE
HTTP/3: Enable in Kestrel by default

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#36486]
Turn on HTTP/3 by default in .NET 7, i.e. default protocol is `Http1AndHttp2AndHttp3`. 🌶️ 🔥 💥

Should do this sooner rather than later to get feedback in .NET 7 previews.

**Comment by adityamandaleeka** [comment]
Before we enable H3 by default, we need:
- [ ] https://github.com/dotnet/aspnetcore/issues/34858
- [ ] Performance needs to match/exceed H2
- [ ] SNQuic team needs to consider SNQuic stable

**Comment by adityamandaleeka** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/37151

**Comment by halter73** [comment]
HTTP/3 support has now been enabled by default in HttpClient (https://github.com/dotnet/runtime/pull/73153). I'm nervous about doing this in .NET 7 for Kestrel though. I feel that HTTP/2 had more bake time before we enabled it by default.

I'm worried we're not properly hardened and perf tested given issues like https://github.com/dotnet/runtime/issues/49972 and https://github.com/dotnet/aspnetcore/issues/32034. @stephentoub

@sebastienros Do we have any HTTP/2 vs HTTP/3 benchmarks? Anything on https://aka.ms/aspnet/benchmarks?

**Comment by stephentoub** [comment]
> HTTP/3 support has now been enabled by default in HttpClient

You still need to opt-in to sending HTTP/3 requests, e.g. set the http message request version to 3.0. It's just that before that PR, you also had to toggle an appcontext switch or else HTTP/3 wasn't available at all.

**Comment by halter73** [comment]
I see. That's similar to how you currently have to opt-in with `HttpProtocols.Http3` (or more likely `HttpProtocols.Http1AndHttp2AndHttp3` for the alt-svc header to work) for Kestrel.

**Comment by JamesNK** [comment]
We removed the preview flags from `HttpProtocol.Http3` and `HttpProtocol.Http1AndHttp2AndHttp3` in Kestrel many previews ago.

I want to leave HTTP/3 opt-in in .NET 7 as well. We haven't seen any issues reported for it. Either there are no bugs or problems, or few people are using it so far.

**Comment by YohanSciubukgian** [comment]
Do you know if the communication between IIS and Kestrel in out-of-process scenario is upgraded to HTTP/3 by default if it's supported by both servers ? 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/http3?view=aspnetcore-6.0
> [HTTP/3](https://quicwg.org/base-drafts/draft-ietf-quic-http.html) is supported with ASP.NET Core in the following IIS deployment scenarios:
> 
> In-process
> [Out-of-Process](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0#out-of-process-hosting-model). In Out-of-Process, IIS responds to the client using HTTP/3, but the reverse proxy connection to the [Kestrel server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0) uses HTTP/1.1.

**Comment by rwkarg** [comment]
If HTTP/3 were "Enabled by default" then would that mean a client connecting would get upgraded to HTTP/3 without a specific opt-in?
I think that would mean that services behind a TCP load balancer (not UDP) would have clients told to upgrade to HTTP/3, fail to connect over UDP, then need to come back on HTTP/2 over TCP. Not sure what the performance impact would be on connections in that scenario.
