### ISSUE TITLE
blazor _httpContextAccessor.HttpContext null

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#36498]
`services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();`
```
@inject LinkGenerator _generator
@inject IHttpContextAccessor _httpContextAccessor
```
```
var callbackUrl = _generator.GetUriByPage(_httpContextAccessor.HttpContext,
    "/Account/ConfirmEmail",
    handler: null,
    values: new { area = "Identity", userId = user.Id, code = code, returnUrl = returnUrl },
    scheme: _httpContextAccessor.HttpContext.Request.Scheme);
```
I'm trying to generate a link, among other things, but I can never capture the HttpContext, because it's always null. I read somewhere that the blazor (server) no longer supports this. how can I solve similar cases?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You should use `NavigationManager.Uri` property to get access to the current URL.
In general, we don't recommend using HttpContextAccessor in Blazor server applications. You can learn more about those limitations here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state
