### ISSUE TITLE
Uncaught pause_on_uncaught

### ISSUE THREAD

**Issue by ABIOLI-COM** [dotnet/aspnetcore#36497]
After updating to the latest .NET 6 Preview, I get this error each time I start my Blazor WebAssembly application in Google Chrome:

`Uncaught pause_on_uncaught`

The real problem is that I have to open developer tools with F12, and then resume execution, otherwise the page loading appears 'frozen' (and it's also very slow, anyway).
On the source code side, I can pretty print the javascript code that is executed at that point:

```
...
mono_wasm_runtime_ready: function() {
        this.mono_wasm_runtime_is_ready = true;
        this._clear_per_step_state();
        this._next_call_function_res_id = 0;
        this._call_function_res_cache = {};
        this._c_fn_table = {};
        this._register_c_fn("mono_wasm_send_dbg_command", "bool", ["number", "number", "number", "number", "number"]);
        this._register_c_fn("mono_wasm_send_dbg_command_with_parms", "bool", ["number", "number", "number", "number", "number", "number", "string"]);
        if (globalThis.dotnetDebugger)
            debugger ;
        else
            console.debug("mono_wasm_runtime_ready", "fe00e07a-5519-4dfe-b35a-f867dbaf2e28")
    },
...
```

Execution is stopped at the line after `<if (globalThis.dotnetDebugger)>`, of course.
The file is called `dotnet.6.0.0-preview.7.21377.19.js`, so it's easy to understand which version I have.

To reproduce, just create an empty 'Blazor Webassembly App' from the template, and select 'ASP.NET Core Hosted' and 'Progressive Web Application'.
I don't know in other combinations, but the error will appear in the console log, although with a basic application it doesn't break.

**Update**: if I wait enough time (about 10 seconds?) the execution will resume anyway automatically, with or without opening the developer tools... really weird...

**Comment by javiercn** [comment]
@ABIOLI-COM thanks for contacting us.

This is a known issue and is being addressed by the runtime folks.

**Comment by javiercn** [comment]
@lewing @thaystg I know you made a fix for this. Did it make it into RC2?

**Comment by thaystg** [comment]
Yes.

**Comment by javiercn** [comment]
@thaystg thanks for confirming!
