### ISSUE TITLE
.Net Core 6 RC1 Blazor HotReload stops working after specific HTML update

### ISSUE THREAD

**Issue by chrdlx** [dotnet/aspnetcore#36528]
Repro steps:

1) Install VS2022 Preview 4 (Version 17.0.0 Preview 4.0 [31626.483.main]) /  .NET CORE 6.0.100-rc.1.21458.32
2) Create a new Blazor Server app
3) Run the app
4) In the launched browser go to the Counter page.
5) Press the counter button and see the number updating as expected.
6) Modify the `<h1>` content in the counter component to (for example): `<h1>Test</h1>`
7) Click Apply Code Changes to hot reload the modification
8) The browser updates showing the new content.
9) Press the counter button again, and now the "Current count" label doesn't update anymore. Even refreshing the page with F5 doesn't fix the counter button and the value doesn't update anymore.  You need to restart the app/server to make the app start working normally again.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which we plan to fix in the upcoming release. You can learn more about this from https://aka.ms/hrp4bug

**Comment by danroth27** [comment]
Duplicate of #35343
