### ISSUE TITLE
role based routing support

### ISSUE THREAD

**Issue by dpr-dev** [dotnet/aspnetcore#36524]
Hi there. What do you think about role-based routing in the asp net core ? I am working on the task management platform where users with the different roles have  different entity modification logic. Currently, I resolve this cases with the mediator. I check a user role in the controller and select handler that I need to run. For example
```cs
public async Task<IActionResult> ChangeTicket([FromBody] Action actoin, [FromServices] IMediator mediator) 
{
   ChangeTicketRequest request = [Role] switch 
   {
      "role-1-example' => new ChangeTicketOwnerRequest(action),
      "role-2-example' => new ChangeTicketAnotherRoleRequest(action),
      _ => null
   }

  if(request is null) {...}

  ChangeTicketResponse response = await mediator.Send(request); 
  return response.Match<IActionResult>(
    (result) => {}, 
    (exception) => {});
}


class ChangeTicketRequest : IRequest<ChangeTicketResponse> {}
class ChangeTicketOwnerRequest : ChangeTicketRequest {}
class ChangeTicketAnotherRoleRequest : ChangeTicketRequest {}
class ChangeTicketResponse {} 

class ChangeTicketOwnerRequestHandler
  : IRequestHandler<ChangeTicketOwnerRequest, ChangeTicketResponse> {}

class ChangeTicketAnotherRoleRequestHandler
  : IRequestHandler<ChangeTicketAnotherRoleRequest, ChangeTicketResponse> {}
```

What do you think about this approach ? 
```cs
[HttpPost("{id}/actions")]
[UseForRole("product-owner")
public async Task<IActionResult> ChangeTicketByProductOwner([FromBody] Action actoin, [FromServices] IMediator mediator) 
{
} 

[HttpPost("{id}/actions")]
[UseForRole("another-role")
public async Task<IActionResult> ChangeTicketByAnotherRole([FromBody] Action actoin, [FromServices] IMediator mediator) 
{
} 
```

Good questions
- What do we need to send to the client, if the application does not match any route? Send 404 or 401 / 403 ? (I don't know. In the my opinion it depends on the specific case)
- How to match endpoints if the user has multiple roles ? (maybe we should provide fallback or selectors priority)

**Comment by davidfowl** [comment]
I'm not sure something like this should be built-in but could be built on matcher policies (see IMatcherPolicy). It seems a little specialized IMHO.

**Comment by dpr-dev** [comment]
@davidfowl, in my opinion, this case is very popular. I’ve faced it in many projects where an application triggers some logic on the same resource for users with different permissions

**Comment by davidfowl** [comment]
I think you should write a matcher policy and make it available to others on nuget and see how popular it is. Post a link to it on this issue while else gather feedback. 

I'm not convinced this should be built into asp.net core
