### ISSUE TITLE
Release notes for packages such as Microsoft.Extensions.Logging.AzureAppServices

### ISSUE THREAD

**Issue by cosminstirbu** [dotnet/aspnetcore#36532]
Hello,

We've noticed that [Microsoft.Extensions.Logging.AzureAppServices](https://www.nuget.org/packages/Microsoft.Extensions.Logging.AzureAppServices) was recently updated to version 5.0.10.

It's not clear however where we can find the release notes to see what changed from 5.0.9 to 5.0.10.

What is the overall process for documenting release notes and where we can find the release notes?

Thank you,
Cosmin

**Comment by adityamandaleeka** [comment]
The short answer is that nothing changed between those two versions. You can find the commit delta here: https://github.com/dotnet/aspnetcore/compare/v5.0.9...v5.0.10

The release notes for the version would normally go here: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.10.md#notable-changes

**Comment by cosminstirbu** [comment]
Thank you.
