### ISSUE TITLE
Hot reload error on rc1 on VS or dotnet watch

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#36533]
### Describe the bug
The hot reload feature is not working as expected on RC1. 

- If I try on VS2022 it says:

![imagen](https://user-images.githubusercontent.com/12015993/133387897-3f26e3c3-2a08-4560-9f57-c464e0325f79.png)

If I press edit I can see an exception but it applies the change without restarting the app.

- And if I try on dotnet watch it says:

watch : Unable to handle changes using hot reload. And the app restarts (after asking you to restart) and everything works as expected except maintaining the state.

### To Reproduce
1. Create a new blazor hosted app
2. Launch on VS2022 with Ctrol+F5
3. Navigate to counter
4. Modify any html or code and save.
5. The error dialog will appear.

### Exceptions (if any)
    (0,0,0,0): Cannot apply changes -- unexpected error: 'Unexpected false - line 156'

### Further technical details
- ASP.NET Core version 6.0.100-rc.1.21458.32

- Include the output of `dotnet --info`
SDK de .NET (que refleje cualquier global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) is VS2022 preview 4, Version 17.0.0 Preview 4.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue with VS 2022, which we're planning to address in the future VS release.

**Comment by mkArtakMSFT** [comment]
Here is the tracking issue; https://developercommunity.visualstudio.com/t/0000:-Cannot-apply-changes----unexp/1527096

Note, that the issue happens only in Ctrl + F5 scenario, and you can avoid it by using F5 (debugging) only.

**Comment by timheuer** [comment]
https://developercommunity.visualstudio.com/t/hot-reload-fails-on-ctrlf5-in-aspnet-core-app/1529167

**Comment by pranavkm** [comment]
@CrahunGit it's possible that the error you're seeing is a "rude edit" - that is cannot be hot reloaded, and requires an app to rebuilt for the change to be applied. In 6.0, .NET Core WebAssembly's hot reload capabilities is not as robust as .NET Core's and consequently a number of kinds of edits that work in .NET Core would fail to hot reload. This is being improved for in 7.0.

There's currently a bug where errors from rude edits don't appear in the Error window (https://developercommunity.visualstudio.com/t/hot-reload-rude-edit-diagnostics-from-source-gener/1528293). dotnet-watch by default does not show rude edit diagnostics unless you run it with the `--verbose` switch.

**Comment by CrahunGit** [comment]
It was adding html or changing code. It’s working on rc2 so it’s not rude Edit, I suppose

**Comment by pranavkm** [comment]
Got it, in that case the link that @timheuer shared is what we're using to patch the VS preview4 / rc1 SDK. It was a bit surprising since you added `dotnet-watch` to the list which isn't affected by the bug that we're patching.

**Comment by CrahunGit** [comment]
To work fine with dotnet watch I had to disable razor source generator. If not I will not be able to work properly
