### ISSUE TITLE
X-Forwarded-For header parsing error and invalid fallback to reverse proxy IP

### ISSUE THREAD

**Issue by lafriks** [dotnet/aspnetcore#36537]
If `ForwardedHeadersMiddleware` fails to parse `X-Forwarded-For` header even outside of option `ForwardLimit` specified limit it logs debug log record with error `Unparsable IP: "2.2.2.2, 1.1.1.1` and falls back to last reverse proxy IP address.

Expected behavior would be to only trust parts of `X-Forwarded-For` header within `ForwardLimit`.

Sample values that fails to parse with `ForwardLimit` set to `1`:

```
X-Forwarded-For: "2.2.2.2, 1.1.1.1
X-Forwarded-For: 2.2.2.2", 1.1.1.1
X-Forwarded-For: 2.2"2.2, 1.1.1.1
```

Currently only workaround is to add additional middleware that cleans up `X-Forwarded-For` header before `ForwardedHeadersMiddleware` processes it.

NB! It was reported first using MSRC but got response that it is not security issue (that I don't agree with 😅) and should be reported here.

If additional info needed I can attach full report here.

I reported this about 7 months ago and affected Microsoft .NET Core Framework versions I tested was 2.1.25, 3.1.12 and 5.0.3. But as there have been no related code changes for `ForwardedHeadersMiddleware` up to date also latest versions should be still affected.

**Comment by blowdart** [comment]
It's an invalid header, we simply aren't going to guess at what it should be. Mismatched quotes, or any other weirdness should end up in a rejection as we may guess incorrectly, or the guessing mechanism we implement may be used to try to smuggle weirdness into the system. 

I don't see any reason here for the behaviour to change, a well behaved chain of proxies won't end up generating a header like this, so such a header could be an indicator of attack.

**Comment by blowdart** [comment]
Then the client, acting as a proxy in this case is adding a malformed string right at the beginning. So fix the client. The other proxies are doing it right, with no quotation marks, but you're starting from an invalid state and we can't make assumptions about why its invalid. It's safer to reject the entire header.

**Comment by lafriks** [comment]
No as client I mean an attacker who wants to hide it's real IP address from application

**Comment by lafriks** [comment]
For example if I set browser (with header extensions) to always send such header to web sites I could potentially hide my IP address from dotnet applications that would use this for request auditing or overcome some limitations if app checks restrictions for local network on localhost IP. I don't know what proxy is used in Azure but this will "work" also if netcore app is deployed as azure website.

**Comment by blowdart** [comment]
So what would you expect the behaviour to be here? Fail the entire request on a malformed string?

As an aside checking on IP address is always doomed to failure and not recommended as spoofing is incredibly easy without even bothering with the forwarded for header. Trying to filter based on IP isn't a great approach at all.

**Comment by lafriks** [comment]
Ok, let me clarify with example:

netcore app with enabled `ForwardedHeadersMiddleware`  and `ForwardLimit` set to `1` running behind (single proxy).

1) Attacker sends request with header `X-Forwarded-For: 1.1"1.1`
2) Proxy receives request and adds `, 2.2.2.2` to received header value
3) netcore app receives request from proxy with header `X-Forwarded-For: 1.1"1.1, 2.2.2.2` and gets 127.0.0.1 as client IP address

My proposal is that from:
```
X-Forwarded-For: 1.1"1.1, 2.2.2.2
^^^^^^^^^^^^^^^^        ^^^^^^^^^
```
only this part can be trusted as is provided by legitimate source so only up to limit value commas from the end of value can be trusted and everything else can be discarded.

So with trust limit 1 only everything after first comma from the end of string should be parsed that is `2.2.2.2`

**Comment by lafriks** [comment]
> So what would you expect the behaviour to be here? Fail the entire request on a malformed string?
> 
> As an aside checking on IP address is always doomed to failure and not recommended as spoofing is incredibly easy without even bothering with the forwarded for header. Trying to filter based on IP isn't a great approach at all.

I'm not saying that IP filter should be used but was just giving as an example. More of a concern is ability to hide IP address from audit logs.

**Comment by blowdart** [comment]
Honestly I think just throwing the request away would be better at this point.

@Tratcher your thoughts would be welcome here

**Comment by lafriks** [comment]
it could be combination of both, trust ending part and if that fails reject request

**Comment by lafriks** [comment]
btw current behavior can be checked at:

```sh
# curl https://xforwardforvuln.azurewebsites.net/
Hello from <redacted-ip!

# curl https://xforwardforvuln.azurewebsites.net/
Hello from <redacted-ip!

# curl -H 'X-Forwarded-For: "1.1.1.1'  https://xforwardforvuln.azurewebsites.net/
Hello from ::ffff:172.16.1.1!
```

**Comment by Tratcher** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/10302. The proposal is to reject requests with invalid forwarder headers.

**Comment by lafriks** [comment]
Oh, than my report did actually get to you, don't know why then MSCR report contact person told to open a new issue :)

Anyway any option that makes `X-Forwarded-For` reliable from security perspective works for me ;)

Closing as duplicate

**Comment by blowdart** [comment]
Oh that'll have been my miscommunication rather than MSRC, they act as a buffer between the product group and the finder, so they're generally passing on my messages, so my fault, not theirs.
