### ISSUE TITLE
Minimal APIs should return the standard media type for Problem Details responses

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#36557]
Minimal APIs that return the result of calling `Microsoft.AspNetCore.Http.Results.ValidationProblem` get a response media type of `application/validationproblem+json` which is [not compliant with the RFC7807 spec](https://datatracker.ietf.org/doc/html/rfc7807#section-3) that they're based on. The media type should be `application/problem+json`.

MVC has the same incorrect behavior but has since it was introduced in 2.x (see #36560).

We should fix this behavior in .NET 6.0 before final release.

**Comment by captainsafia** [comment]
Closing since it has been merged to RC2.
