### ISSUE TITLE
MVC actions returning Problem Details should return the standard media type for Problem Details responses

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#36560]
MVC actions that return the result of calling `ControllerBase.ValidationProblem` get a response media type of `application/validationproblem+json` which is [not compliant with the RFC7807 spec](https://datatracker.ietf.org/doc/html/rfc7807#section-3) that they're based on. The media type should be `application/problem+json`.

We should be using the standard media type. Given this has been the behavior of MVC since the feature was introduced in 2.x, we might want to consider mitigations to address potential compatibility issues, e.g. an option to configure the media type, the ability to set the media type at the time of generating the response, etc.

**Comment by DamianEdwards** [comment]
I think we should just fix this in .NET 6 given we're just completely out of spec here. We can add an app context switch for back-compat opt-in if we're concerned about it breaking folks.

**Comment by mkArtakMSFT** [comment]
Cleaning up the milestone so that you can see this during triage. From what I understand you wanted to fix this for RC2. @rafikiassumani-msft

**Comment by rafikiassumani-msft** [comment]
We have a similar issue in Minimal. Working with the team to see if we need to fix this as well for Minimal to be consistent with MVC.

**Comment by DamianEdwards** [comment]
@rafikiassumani-msft see #36557
