### ISSUE TITLE
Allow SignalR to work in AWS serverless environment

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#36575]
## Summary

Currently it is not possible to run a SignalR ASP.NET application in the AWS Lambda serverless environment. This is because the AWS Lambda instances are transitory.
However, the AWS infrastructure for sticky connections already exists in the WebSockets API gateway (since Dec 2018).

## Motivation and goals

Currently in the AWS Lambda environment, we are unable to use server-side Blazor in an AWS dotnet Lambda serverless scenario. This is because SignalrR only offers direct WebSockets, or long polling or server side events.
I propose an additional transport that can send and receive HTTP messages using a sticky connection id.

This will be useful in other load balancing scenarios outside of the Azure implementation.

AWS already provides the AWS Websockets API but because of the limited Transports available in SignalR, we have been unable to leverage it using Hubs.

## In scope

Allow SignalR to receive an HTTP incoming message that includes the sticky connection id and WebSockets message (routing and contents).

In AWS after creating a WebSockets API, received messages are routed to a Lambda instance. This passed JSON includes the sticky connection ID, the WebSockets frame contents and the route. I propose a proxiedWebSockets transport protocol that can accept this payload, route it to the appropriate Hub with the contents for the Hub to take action on. Upon Hub completion, the response is POSTed back to the sticky connection id (using PostToConnectionAsync) which the WeSockets API returns back to the client(s))

Examples of the AWS WebSockets API include https://gavinlewis.medium.com/getting-started-with-websockets-on-api-gateway-with-net-and-the-serverless-framework-9065f37d06e0
and Martin Beeby BUILDING A REAL-TIME SERVERLESS APP IN BLAZOR USING AWS https://meetupfeed.io/talk/real-time-serverless-app-aws

This concept is not new e.g. https://documentation.softwareag.com/onlinehelp/Rohan/num10-5/10-5_UM_webhelp/index.html#page/um-webhelp/co-websocketforwardproxy.html

KeepAlive would be false for this transport.

Essentially the WebSocket communication to the client takes place across a gateway that maintains a sticky WebSockets connection. A serverless Lambda DotNet application can be instantiated, route to the appropriate Hub, process, return the WebSockets result and exit. This makes this mechanism highly scalable.

## Out of scope

There will be no backdown to long polling or server side events because the AWS environment only offers Websockets stickiness.

## Risks / unknowns

The biggest risk appears to be that Asp.Net developers are not very familiar with the AWS environment.

## Examples

```
app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapHub<ChatHub>("/chathub", options =>
        {
            options.Transports =
                HttpTransportType.ProxiedWebSockets; //Force the transport to use Http with a sticky connection id
        });
    });
```

**Comment by davidfowl** [comment]
This should be a request for the AWS .NET sdk. 

cc @normj

**Comment by genifycom** [comment]
Hi David, I was told to write it up here.

It is possible to write the Proxied WebSockets transport to be platform agnostic and then just overwrite the specific return for AWS?

**Comment by davidfowl** [comment]
I don't see why we'd implement this if AWS is the only thing that implements it. What else does websockets like this?

**Comment by wegylexy** [comment]
SignalR is a lot more than that AWS stuff, and requires a real sticky connection context between the client and the server, more than just a connection ID.
That serverless thing is more like REST API, impossible to maintain a hub connection context without a separate database service. The browser just gets a persistent gateway on AWS, but subsequent requests may be routed to different backend servers that host the serverless functions. The backend servers may even go down, and you can still have another service pushing data back to the browser by the connection ID.
To ensure that Blazor apps are blazingly responsive, every client sticks to an actual server (directly or via a proxy, but not serverless) which stores all states in memory, without having to query a database service for every request.
**Would you consider Blazor WebAssembly instead?**

**Comment by genifycom** [comment]
Ok just to be clear, when a new client connects to the WebSockets API, in the connection event, the connection id is stashed in DynamoDB. When a client disconnects from WebSockets API, in the disconnect event, the connection id is removed from DynamoDB.

When a server message is to be sent to clients, the server enumerates those connection ids in DynamoDB and does a PostToConnectionAsync to each connection id which then sends to each client with the WebSockets API.

In my mind, this covers all of the sticky connection requirements for WebSockets. This is more scalable than the Azure WebSockets service approach.

Blazor WebAssembly is currently problematic to serve up from serverless for a number of reasons including that we cannot mix both server side razor pages and client WebAssembly pieces. Blazor WebAssembly adopts the SPA (i.e. we want to download the whole application from a single project) approach.

Thanks for responding.

**Comment by davidfowl** [comment]
> This is more scalable than the Azure WebSockets service approach.

I don't see how that's the case. Can you elaborate?

**Comment by wegylexy** [comment]
I see it reduces cost of operation by degrading responsiveness, but I don't see how it's _more_ scalable. So the issue is a feature request for Blazor to work as serverless functions like https://docs.microsoft.com/azure/azure-signalr/signalr-quickstart-azure-functions-csharp which is similar to AWS WebSockets API, and maintain all application states in a separate serverless database service rather than in memory on the same serving node. Every request then has to go through the WebSocket gateway, reach a backend function which queries a database from another service, etc. and finally a REST endpoint that will propagate the response back to the client through the WebSocket gateway.

@genifycom Why do you have to mix? Can't you serve the Blazor WASM from a CDN, and invoke your Web API serverless functions? This way, you won't need SignalR at all.
