### ISSUE TITLE
Missing .msg extension in FileExtensionContentTypeProvider

### ISSUE THREAD

**Issue by fmflurry** [dotnet/aspnetcore#36576]
### Describe the bug

Using `FileExtensionContentTypeProvider TryGetContentType` method with `.msg` file extension will not return `application/vnd.ms-outlook`.

We are using it to set Content-Type response header based on the file extension our user is trying to download. So far it’s working great but we had an issue where .msg files couldn’t be downloaded, and we found out in source code it is not supported.
 https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs

As a workaround we currently add `.msg` entry into `Mappings` but we believe that would be nice to support such a common extension.

**Comment by Tratcher** [comment]
FYI:
https://github.com/dotnet/aspnetcore/blob/f1b907b4f08602bfa466cf1f3f94cfe95f72ef07/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L17-L18

**Comment by fmflurry** [comment]
I'm aware of that comment, in my honest opinion `.msg` should be supported as outlook format is widely used in companies.
The change is trivial and that could avoid bugs / headaches in the future.

Shall I open a PR or do you're not planning to add a new entry for `,msg` ?

**Comment by adityamandaleeka** [comment]
Triage: we don't think this meets the bar for inclusion per the referenced comment.

Since people can modify this list themselves, we don't want to update the defaults for this.
