### ISSUE TITLE
Blazor Server .NET 6 new project template issues

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#36572]
### Describe the bug
Create a new project in VS Mac and the `.cs` files have this for the `namespace`:

```
namespace Blazor6Test3.Data;

public class WeatherForecast
{
	public DateTime Date { get; set; }

	public int TemperatureC { get; set; }

	public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

	public string? Summary { get; set; }
}
```

### To Reproduce
1. Create a new Blazor Server project using .NET 6
2. Open WeatherForecast.cs
3. Notice the code looks like the above
4. Try to run the project and notice the errors about the malformed 1namespace1 code

There is also a file called `Blazor6Test3.GlobalUsings.g.cs` that is throwing multiple errors and has these contents:

```
// <auto-generated/>
global using global::Microsoft.AspNetCore.Builder;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Http;
global using global::Microsoft.AspNetCore.Routing;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Net.Http.Json;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

### Further technical details
- ASP.NET Core version: ASP.NET Core 6 RC1
- IDE: VS Mac 8.10.9 (build 3)
- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.409 [/usr/local/share/dotnet/sdk]
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  3.1.413 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  5.0.401 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21458.32 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

I believe that VS 4 Mac is a bit behind on their C# 10 support, this will be addressed in a few weeks.

/cc: @mrward

**Comment by mrward** [comment]
Visual Studio for Mac 8.10 does not have support for .NET 6.

Visual Studio for Mac 17.0 does have support for .NET 6 and C# 10 but this has not yet been released - even with the private preivew which requires a signup - https://visualstudio.microsoft.com/vs/mac/preview/

**Comment by mrlife** [comment]
@javiercn and @mrward, thank you!

mrward, I have the VS Mac 17 preview, do you know when support might be available? With RC1 being supported for production scenarios, we are ready to start using it as soon as we can.

**Comment by mrward** [comment]
I do not have a specific date. There are a few bugs blocking the release of the next preview.

**Comment by mrlife** [comment]
@mrward Thanks for letting me know! VS Mac 17 has the new native UI, which is really nice. I like the darker dark theme better than on the previous incarnation.

While the UI is native, I think I read a while back that the internals between the Windows and macOS versions would be more similar. Is that sill the case/plan?

**Comment by mrward** [comment]
We are not there yet with the all internals but we are sharing more code over time.

**Comment by mrlife** [comment]
> I do not have a specific date. There are a few bugs blocking the release of the next preview.

@mrward Do you think the release will happen soonish or closer to .NET 6 official release in November?

**Comment by mrward** [comment]
There should be an updated VS Mac 17.0.0.3569 released on the private preview channel that has C# 10 and .NET 6 RC1 support.

**Comment by mrlife** [comment]
@mrward Thank you! Just curious if there are release notes for these releases or not until the official release.

**Comment by mrward** [comment]
No public release notes yet since they are internal previews unfortunately.

**Comment by mrlife** [comment]
Happy to see Visual Studio for Mac 2022 is now in public preview (with release notes!).

I noticed the templates are still presenting with some unexpected formatting, though the project runs fine. For example, in the Minimal API project (`dotnet new web -o MinApi`), the `Program.cs` file looks like:

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

**Comment by mrward** [comment]
`some unexpected formatting` - the text editor is not formatting things properly?

The contents of Program.cs looks OK.

**Comment by mrlife** [comment]
Sorry, I did mean the contents as opposed to the formatting. I didn't realize that the contents could run outside of a class and haven't found any documentation about it. Thanks for letting me know it's ok.

**Comment by mrward** [comment]
The more recent .NET 6 project templates use C# 10 features to reduce the amount of boiler plate code - https://www.hanselman.com/blog/exploring-a-minimal-web-api-with-aspnet-core-6

**Comment by mrlife** [comment]
Thank you! The file-scoped namespaces are really nice since they reduce the indentation by one.
