### ISSUE TITLE
API proposal: ObjectPool IServiceCollection helper extension

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/aspnetcore#36586]
## Background and Motivation

In a largish codebase I'm working on we have defined a handful of ObjectPools. We have the `new` going through the `IServiceProvider` and each object has a bit of logic we run on `Return` to clear some data or decide if we want to reuse it. I was able to turn a lot of copy-paste code creating very similar policy classes into a simple extension/helper. Posting here in case anyone else might find it useful.

If this goes ahead I would be happy to work on the PR.

## Proposed API

```csharp
namespace Microsoft.Extensions.DependencyInjection
{
   public static class ObjectPoolServiceCollectionExtensions
   {
	public static IServiceCollection AddObjectPool<T>(
		this IServiceCollection services,
		Func<T, bool>? onInstanceReturnedFunc = null)
		where T : class
	{
		return services
			.AddTransient<T>()
			.AddSingleton(sp =>
			{
				ObjectPoolProvider provider = sp.GetRequiredService<ObjectPoolProvider>();

				if (onInstanceReturnedFunc == null)
					onInstanceReturnedFunc = o => true;

				return provider.Create(new ServiceProviderPooledObjectPolicy<T>(sp, onInstanceReturnedFunc));
			});
	}
   }
}

namespace Microsoft.Extensions.ObjectPool
{
        // internal surface but useful to understand the extension
	internal sealed class ServiceProviderPooledObjectPolicy<T> : PooledObjectPolicy<T>
		where T : notnull
	{
		private readonly IServiceProvider _ServiceProvider;
		private readonly Func<T, bool> _OnInstanceReturnedFunc;

		public ServiceProviderPooledObjectPolicy(
			IServiceProvider serviceProvider,
			Func<T, bool> onInstanceReturnedFunc)
		{
			_ServiceProvider = serviceProvider;
			_OnInstanceReturnedFunc = onInstanceReturnedFunc;
		}

		public override T Create()
			=> _ServiceProvider.GetRequiredService<T>();

		public override bool Return(T obj)
			=> _OnInstanceReturnedFunc(obj);
	}
}
```

## Usage Examples

```csharp
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddObjectPool<MyPooledClass>();
			services.AddObjectPool<MyPooledClassWithClear>(onInstanceReturnedFunc: obj =>
			{
				obj.ClearData();
				return true;
			});
			services.AddObjectPool<MyPooledClassOwnsReturnDecision>(
				onInstanceReturnedFunc: obj => obj.ShouldBeReturned());
		}
```

**Comment by ShreyasJejurkar** [comment]
I think the correct repo for this one is the [dotnet/runtime](https://github.com/dotnet/runtime) repo, as they own the DepedencyInjection container.

**Comment by CodeBlanch** [comment]
@ShreyasJejurkar I think many users of `Microsoft.Extensions.DependencyInjection` would be very surprised if it suddenly took a dependency on `Microsoft.Extensions.ObjectPool` :smile:

IMO it is very common practice to put extension methods for the thing you are extending (`IServiceCollection`) in the namespace where it lives (`Microsoft.Extensions.DependencyInjection`).

Here is one of many examples in the aspnetcore repo: [DataProtectionServiceCollectionExtensions](https://github.com/dotnet/aspnetcore/blob/068797e16a1bfe66461e15c8a2ffa864369d384d/src/DataProtection/DataProtection/src/DataProtectionServiceCollectionExtensions.cs#L26)

PS: I'll update the proposed API to have a static class that might help with the confusion.

**Comment by adityamandaleeka** [comment]
Triage: we consider ObjectPool to be infrastructure for aspnetcore, so we're not really investing in adding features that make it more convenient for other uses. As a workaround, you can add this extension method in your own code.
