### ISSUE TITLE
Unable to publish views of a Microsoft.NET.Sdk.Web project

### ISSUE THREAD

**Issue by geetmenon** [dotnet/aspnetcore#36583]
Please let me know the steps I need to follow to publish views (.cshtml files) of  a Microsoft.NET.Sdk.Web project  instead of publishing a precompiled views.dll  I am using asp.net core 5.0, and please note it is not a Microsoft.NET.Sdk.Razor project.  

1) Tried the following settings but that didn't help. Do these work only for Microsoft.NET.Sdk.Razor projects? If yes, then what are corresponding settings in a  Microsoft.NET.Sdk.Web project for the following: 

```xml
<RazorCompileOnBuild>false</RazorCompileOnBuild>
<RazorCompileOnPublish>false</RazorCompileOnPublish>
<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
```

2) Also tried include Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package and including the AddRazorRuntimeCompilation(): 

```C#
services.AddMvc(options => options.Filters.Add(typeof(CustomExceptionFilter)))
                .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null)
                .AddControllersAsServices()
                .AddRazorRuntimeCompilation();
```

These didn't help. So please let me know what I need to do be able to publish views in a Microsoft.NET.Sdk.Web project .

**Comment by javiercn** [comment]
@geetmenon thanks for contacting us.

Microsoft.NET.Sdk.Web imports Microsoft.NET.Sdk.Razor, otherwise you wouldn't even be able to compile builds.

I'm not sure what you are trying to achieve, the best way for you to do this would probably be to set `EnableDefaultRazorGenerateItems ` and `EnableDefaultRazorComponentItems`

At that point they won't be considered for razor compilation and won't be compiled nor included in the dlls and is up to you to get them copied to wherever you want.

/cc: @pranavkm

**Comment by geetmenon** [comment]
1) @javiercn : You mentioned  ".. and is up to you to get them copied to wherever you want." . If we have to explicitly copy the views to the publish folder, then what is the purpose of CopyRazorGenerateFilesToPublishDirectory flag?

2) Currently we use MSBuild 12.0 to build our asp.net solution (based on .Net Framework 4.5.2). This automatically includes Views and Areas in the _PublishedWebsites folder. We do not have to explicitly copy Views and Areas folders into the _PublishedWebsites folder. 
We have migrated our solution to asp.net core now. However when we use MSBuild 16.10 to build this asp.net core solution (or use the Publish option from within VS 2019), it does not copy the Views and Areas folders in the publish folder Tried different settings but none of them help.   Our requirement is that instead of the compiled views dll in the publish folder,  we want to have the Views and Areas folders copied automatically into the publish folder (similar to how MSBuild 12.0 is doing). We are able to turn of the views.dll generation. So what should be the settings in project file, publish profile, MSBuild params that we need to use to have the Views and Areas folders made automatically available in publish folder when we publish or run MSBuild?

**Comment by pranavkm** [comment]
@geetmenon what you initially had looks correct. I tried your steps on a brand new project template and it appears to work correctly - the views are copied to the publish directory with `CopyRazorGenerateFilesToPublishDirectory` set. You will need the runtime compilation in addition to setting these properties to be able to compile the views at runtime. 

Do you have a minimal app that reproduces your issue? Also, out of curiosity, why are you attempting to turn off build time compilation? We think of build time compilation as the primary way to compile your app's views, and it's somewhat unusual to want to turn it off.

**Comment by geetmenon** [comment]
@pranavkm I need to pass this on to a different team who can work with the html/css. So we need to have the views published as is (instead of the compiled dll). 

I am using a solution that was upgraded to asp.net core using upgrade assistant.

Thare are the settings in my Microsoft.NET.Sdk.Web project file
 <PropertyGroup>
    <OutputPath></OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <EnableDefaultItems>false</EnableDefaultItems>
	<RazorCompileOnBuild>false</RazorCompileOnBuild>
	<RazorCompileOnPublish>false</RazorCompileOnPublish>
	<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <EnableDefaultRazorGenerateItems>true</EnableDefaultRazorGenerateItems>
	<EnableDefaultRazorComponentItems>true</EnableDefaultRazorComponentItems>
  </PropertyGroup> 
  
I am already using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package along with the following code:
services.AddMvc(options => options.Filters.Add(typeof(CustomExceptionFilter)))
                .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null)
                .AddControllersAsServices()
                .AddRazorRuntimeCompilation();

**Comment by pranavkm** [comment]
Here's what I tried: https://github.com/pranavkm/RuntimeCompilation. Publishing the app I can see the Views and verified that the published app can render them correctly.

**Comment by geetmenon** [comment]
The views get published in your project at  [https://github.com/pranavkm/RuntimeCompilation.](url)

I think the reason it is not getting published in my project is because I have implicit includes disabled. That is,
`<EnableDefaultItems>false</EnableDefaultItems>`
And I have explicitly specified all the include files.

When EnableDefaultItems is set to false in project file, what is that I need to do to have views (& areas and wwwroot)  published automatically when I publish via VS or via msbuild?

**Comment by pranavkm** [comment]
You'll have to manually include cshtml files as `Content` items:

e.g. `<Content Include="**\*.cshtml" />` (this does not include any of the the excludes that the Web.SDK adds by default).

**Comment by geetmenon** [comment]
As mentioned in my earlier comment I had explicitly specified each of the include files (including all .cshtml files) in my project file. That is, I had explicitly included (along with my Compile and None includes ) each of the Content include (i.e. cshtml) files in my csproj file corresponding to the sample project you had published
```
  <ItemGroup>
    <Content Include="Views\_ViewStart.cshtml" />
    <Content Include="Views\_ViewImports.cshtml" />
    <Content Include="Views\Home\Index.cshtml" />
    <Content Include="Views\Home\Privacy.cshtml" />
    <Content Include="Views\Shared\_Layout.cshtml" />
   <Content Include="Views\Shared\_ValidationScriptsPartial.cshtml" />
   <Content Include="Views\Shared\Error.cshtml" />
 </ItemGroup>
```
But this does not result in views getting published.

I also now tried using (in place of the above in includes)
`<Content Include="**\*.cshtml" />`
This also does not result in views getting published.  As a side note, I don't want to be using this generic include of all cshtml files since I want to explicitly include each of the cshtml files that I am interested in (for have a few that I do not want to get included).

**Comment by geetmenon** [comment]
This is issue is not resolved. I had added a comment yesterday (please see my previous comment). So please re-open it.

**Comment by javiercn** [comment]
@pranavkm can you take another look please?

**Comment by pranavkm** [comment]
Does `<Content Include="Views\_ViewStart.cshtml" CopyToPublishDirectory="PreserveNewest" />` work?

**Comment by geetmenon** [comment]
I tried adding this:
`<Content Include="Views\_ViewStart.cshtml" CopyToPublishDirectory="PreserveNewest" />`

and it does copy this particular view. But isn't there a better way to do this instead of having to specify this property for each file in my views folder, for each file in my areas views folder and for each file in my wwwroot folder? Please note that I want to do explicit includes (not default include  and not wild card include) in my project file.

Also what is the use of setting CopyRazorGenerateFilesToPublishDirectory property then, i.e.
`<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>`

**Comment by geetmenon** [comment]
Is there any update on this?  My requirement is that I want to do explicit includes of each file in my views and wwwroot. What do I need to do to have the views and area views and wwwroot folders to be published without having to specify CopyToPublishDirectory="PreserveNewest" against each file. Surely there must be a better way to do this.

Also what is the use of setting CopyRazorGenerateFilesToPublishDirectory property then, i.e.
<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
It doesn't seem to be doing anything for explicit includes.

**Comment by pranavkm** [comment]
I think putting `<Content Update="*.cshtml" CopyToPublishDirectory="PreserveNewest" />` after all your includes might work. That said this is a question specific to MSBuild evaluation, and perhaps folks on https://github.com/dotnet/msbuild or StackOverflow might be better suited to respond.

`CopyRazorGenerateFilesToPublishDirectory` applies to `RazorGenerate` items which are only calculated when`EnableDefaultItems` is true.

**Comment by geetmenon** [comment]
Thanks @pranavkm. Adding just `<Content Update="*.cshtml" CopyToPublishDirectory="PreserveNewest" />` did not help. 
For our requirement a) to explcitly include each view, and b) to publish views instead of views.dll,  I was however  able to get it to publish by views by doing the following. Note that I had to specify all 3 (i.e. CopyRazorGenerateFilesToPublishDirectory, Content Updates after the Content Includes, Folder includes).
  
1) Include package (to enable runtime compilation for Razor pages &) views)
	`Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation `
	

2) In ConfigureServices()  (to enable runtime compilation for Razor pages &) views)
```
    services.AddMvc(
	//....
	//...
	).AddRazorRuntimeCompilation();
```


3) In web.csproj add the following:
	
  ```
<PropertyGroup>
	<!-- To disable implicit includes of all views -->
	<EnableDefaultContentItems>false</EnableDefaultContentItems>

	<!-- To publish views instead of views.dll-->
	<EnableDefaultRazorGenerateItems>false</EnableDefaultRazorGenerateItems>
	<EnableDefaultRazorComponentItems>false</EnableDefaultRazorComponentItems>
	<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>
  
  <ItemGroup>
       <!-- Explicitly include each .cshtml files in the subfolders under Views and Area Views  -->

	
	<!-- Then add these 2 Content Updates--->
	<Content Update="Views\**\*.cshtml" CopyToPublishDirectory="PreserveNewest" /> 
	<Content Update="Areas\MyArea1\Views\**\*.cshtml" CopyToPublishDirectory="PreserveNewest" /> 
  </ItemGroup>
	
  <ItemGroup>
	<Folder Include="Views">
		 <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	</Folder> 
	<Folder Include="Areas\MyArea1\Views">
		 <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	</Folder>
  </ItemGroup>	
```

Thanks for all your help @pranavkm!
