### ISSUE TITLE
Blazor WASM: input checkbox rendering issue

### ISSUE THREAD

**Issue by dimmik** [dotnet/aspnetcore#36597]
### Describe the bug
**Summary:** Incorrect rendering of checkbox input "checked" state in list of items, when after clicking on checkbox input corresponding item disappears.
**Details:** 
List of items (such as ToDo item), each containing content and boolean flag "done" is rendered as an ordered list.
Only those items which have "done" attribute set to `false `are rendered: `@foreach (var i in items.Where(i => !i.Done))`
Checkbox is put left to content, and its `checked `attribute is set to "checked" if item's "done" property is true; `checked `attribute is omitted otherwise.
When checkbox is clicked, "done" flag of corresponding item is set to false:
```
                @if (i.Done)
                {
                    <span>
                        (checked)
                        <input type="checkbox" checked="checked"
                               @onclick="@(() => items.Where(ii => ii.Id == i.Id).First().Done = !items.Where(ii => ii.Id == i.Id).First().Done)" /> @i.Content (done: @i.Done id: @i.Id)
                    </span>
                }
                else
                {
                    <span>
                        (NOT checked)
                        <input type="checkbox"
                               @onclick="@(() => items.Where(ii => ii.Id == i.Id).First().Done = !items.Where(ii => ii.Id == i.Id).First().Done)" /> @i.Content (done: @i.Done id: @i.Id)
                        </span>
                }

```

**Expected behavior:** when checkbox is clicked, item disappears from list; other items remain in the list, their corresponding checkboxes remain unchecked
**Actual behavior:** when checkbox is clicked, item disappears from list, but checkbox that corresponds to **next** item becomes checked

### To Reproduce
**code:** 
_repo:_ https://github.com/dimmik/blazor-checkbox-issue
_component:_ https://github.com/dimmik/blazor-checkbox-issue/blob/master/BlazorCheckboxIssue/BlazorCheckboxIssue/Pages/Index.razor
**demo:** https://dimmik.github.io/blazor-checkbox-issue/
**gif with demonstration:**
![blazor issue gif](https://user-images.githubusercontent.com/5870912/133597327-6f1b1d41-554c-4d41-98ad-861dd6f976a9.gif)

### Exceptions (if any)
No

### Further technical details

**- ASP.NET Core version:** .NET 5
**- Browser:** Chrome Version 93.0.4577.63 (Official Build) (64-bit)
**- Include the output of `dotnet --info`:** 
```
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/runner/.dotnet/sdk/5.0.401/

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [/home/runner/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/home/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/home/runner/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:** N/A (reproducible by building by github actions)

**Comment by pranavkm** [comment]
Thanks for your issue report. It's possible that this is due to a not specifying an `@key` parameter for the component. Could you have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#use-key-to-control-the-preservation-of-elements-and-components-1 and see if it helps address your issue?

**Comment by dimmik** [comment]
> Thanks for your issue report. It's possible that this is due to a not specifying an `@key` parameter for the component. Could you have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#use-key-to-control-the-preservation-of-elements-and-components-1 and see if it helps address your issue?

Seems working. Thanks!

**Comment by Xyncgas** [comment]
To add to your knowledge, when you put stuffs in @if, and if the condition changed, blazor discards whatever states in the block that's now evaluated to false, but if you want to let's say change {checked="checked"} for the input, what you can do is
`checked="@($"{i.Done?"checked":""}")"`

**Comment by Xyncgas** [comment]
therefore discarding the needs to put your codes in the if block
