### ISSUE TITLE
RC1 update issue: Blazor don't wait for js interop call and its executed the code synchronous way

### ISSUE THREAD

**Issue by Venkat4655** [dotnet/aspnetcore#36599]
### Describe the bug
After upgrading to net6 and RC1 my app is unable to work as in the previous .net version 5. We have done some stuff based on boolean value after calling the JavaScript function. Here, that boolean value updated in JsInVokable method. 
This scenario worked in .Net 5 version, but it failed in the .Net 6

### To Reproduce

We have called JavaScript function in Button click function as like following code example,

```
@page "/"
@inject IJSRuntime JSRuntime
<button @onclick=ButtonClicked>Perform interop</button>
@code
{
. . . .
    private async Task ButtonClicked()
    {
        //Calling JavaScript function
        await JSRuntime.InvokeVoidAsync("buttonClick", "Hello");
        //Here boolean values is enabled while JavaScript to Server call
        if (Parent.IsTest) {
            Console.WriteLine("This is not executed"); 
        }
    }
}
```

In that JavaScript function, we have done some stuff and call server-side method as follows,

```
testMethod = function (args) { 
//some stuff
this.dotNetRef.invokeMethodAsync("ServerInteropMethod",param1, param2);
        }
```

And we have updated the boolean value in the  following Jsinvokable method,

```
 [JSInvokable]

        public void ServerMethod(string param1, string param2)
        {
        //SomeStuff
      Parent.IsTest= true;
       }
```
Here, JsInvokable method triggered after button click function execute in latest dotnet version. This JsInvokable method triggers once if called Javascript function. 

### Exceptions (if any)
There is no exception, asynchronous turning into synchronous. This is the root cause of our issue. The reported issue resolved while using **Task.Yield** method. Please refer the following code example,

```
private async Task ButtonClicked()
    {
        //Calling JavaScript function
        await JSRuntime.InvokeVoidAsync("buttonClick", "Hello");
        await Task.Yield();
        //Here boolean values is enabled while JavaScript to Server call
        if (Parent.IsTest) {
            Console.WriteLine("This is not executed"); 
        }
    }
```
### Further technical details
- ASP.NET Core version - .Net 6 RC1
- Include the output of `dotnet --info` -- 6.0.100-rc.1.21458.32
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version - VS2022

**Comment by pranavkm** [comment]
@Venkat4655 are you able to provide us a more complete repro app?

**Comment by TanayParikh** [comment]
Hello @Venkat4655, I tried reproducing this issue but it's working as expected for me.

I'm assuming this issue was on Blazor Server, **please confirm**.

I added the following to `index.html`:

```html
    <script>
        function runJS(objRef) {
            objRef.invokeMethodAsync("RunServerMethod");
        }
    </script>
```

And my `Index.razor` is as follows:
```razor
@page "/"
@inject IJSRuntime JSRuntime

<PageTitle>Index</PageTitle>

<button @onclick="DoOperations">Start</button>

@code
{
    bool serverExecuted = false;

    private async Task DoOperations()
    {
        var dotNetRef = DotNetObjectReference.Create(this);
        await JSRuntime.InvokeVoidAsync("runJS", dotNetRef);

        Console.WriteLine(serverExecuted ? "Server Executed" : "Server didn't execute");
    }

    [JSInvokable]
    public void RunServerMethod()
    {
        serverExecuted = true;
    }
}
```

This is producing an output of `Server Executed` (ie, the `Console.WriteLine` is executed after `RunServerMethod` & `InvokeVoidAsync`). Is this the issue you were facing, or was it something else? If you're still having this issue, please provide a minimal app as a GitHub repo.

**Comment by TanayParikh** [comment]
Hello @Venkat4655, I tried reproducing this issue but it's working as expected for me.

I added the following to `index.html`:

```html
    <script>
        function runJS(objRef) {
            objRef.invokeMethodAsync("RunServerMethod");
        }
    </script>
```

And my `Index.razor` is as follows:
```razor
@page "/"
@inject IJSRuntime JSRuntime

<PageTitle>Index</PageTitle>

<button @onclick="DoOperations">Start</button>

@code
{
    bool serverExecuted = false;

    private async Task DoOperations()
    {
        var dotNetRef = DotNetObjectReference.Create(this);
        await JSRuntime.InvokeVoidAsync("runJS", dotNetRef);

        Console.WriteLine(serverExecuted ? "Server Executed" : "Server didn't execute");
    }

    [JSInvokable]
    public void RunServerMethod()
    {
        serverExecuted = true;
    }
}
```

This is producing an output of `Server Executed` (ie, the `Console.WriteLine` is executed after `RunServerMethod` & `InvokeVoidAsync`). Is this the issue you were facing, or was it something else? If you're still having this issue, please provide a minimal app as a GitHub repo.
