### ISSUE TITLE
NavigationOption: ScrollAfterNavigation:false => Prevents scroll after navigation

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#36605]
When links have href to another page like for UX experience so user can copy url and share etc.
Let's say url:
/faq/1

it loads a faq page with collapsible items and dynamic question/content related info.
If you click on a link to /faq/2 it may be desired to prevent scrolling to the top.

```razor
NavigationManager.NavigateTo(@($"/faq/{id}"),new NavigationOptions () { ScrollAfterNavigation:false });
```

Pretty sure the functionability it's almost all already implemented on this [PR](https://github.com/dotnet/aspnetcore/pull/12423).

There's a comment on that PR that also asks for the same thing.

**Comment by jirisykora83** [comment]
Any progress on this?

**Comment by MackinnonBuck** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/40190
