### ISSUE TITLE
Return ok from controller before async Task complete

### ISSUE THREAD

**Issue by GrowSharp** [dotnet/aspnetcore#36600]
Hello,
I've been trying to implement a functionality, where I need to return a response from a controller early while still processing some "background" task. I have tried to achieve that with library called MediatR, but unfortunately even though on my local machine it worked just fine I realized that in production environment it was acting up - sometimes working as intended, sometimes it just seemed to wait for the "background" task to finish and then returned the response. I even managed to replicate that problem (just by trying it again and again) on my local machine so I decided to rework it using _[Background tasks with hosted services](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services)_.

Again, all seemed just fine, before I got reports, that on production environment it seemed to be not working properly..again. So as "experienced" debugger of this kind of issue I tried to replicate it on my machine by trying it again and again until I finally saw that it's acting up same the same way the first implementation (using MediatR) did.

I couldn't figure it out, I spent hours searching internet for answers and tried every possible trick etc. I could possibly think of. With no good results.

After a while I found an article with new approach. It seemed that the only thing I needed to do is to enclose the controller method body in try statement, calling the "background" task in finally block like this:

```
    [HttpGet]
    public async Task<IActionResult> ConfirmPairing([FromRoute] string someCode)
    {
      try
      {
        return Ok(new GeneralOkResponseModel());
      }
      finally
      {
        Response.OnCompleted(async () => { await SomeService.DoThePairingJobAsync(someCode, CancellationToken.None); });
      }
    }
```

And again, everything seemed fine. On my local computer, on test environment and for some time even on the production one! But not for long. Today I realized that it might be acting up again, so I did my debugging routine by trying it again and again until it happened.. The same result again. It waited before the PairingJob from the service was completed and then returned the Ok result to the browser..

I'm desperate now. I tried every possible way I found like using libraries like Quartz or Hangfire. But every time with same disappointing results. 

I know that the right way to achieve this would be by using some messaging mechanism (like RabbitMq, or Kafka) where I could just queue the work (which would take just a few ms), return the ok result and then asynchronously process it in some kind of consumer process, but the company I'm working for is afraid of these technologies and I'm afraid that it's gonna take some time before it goes trough all the necessary bureaucracy and I could start with implementation, but I need a quick fix now. 

So I'm asking you guys. Am I doing something wrong here? Is some specific kestrel configuration needed to achieve the right behaviour, or is just by design wrong? 

Shouldn't at least the _Background tasks with hosted services_ work correctly as it is a solution from MS team itself?

Any help or recommendation would be greatly appreciated. 

### Further technical details
- ASP.NET Core version: netcoreapp3.1
- Nothing more shall be needed as it is acting the same way in every possible environment I tried, but if so, just say it and I'll provide anything I could

EDIT: Added link to docs.microsoft.com

**Comment by davidfowl** [comment]
> I have tried to achieve that with library called MediatR, but unfortunately even though on my local machine it worked just fine I realized that in production environment it was acting up - sometimes working as intended, sometimes it just seemed to wait for the "background" task to finish and then returned the response

Did you try to use `Task.Run` to queue the background operation before returning the response:

```C#
[HttpGet]
public Task<IActionResult> ConfirmPairing([FromRoute] string someCode)
{
    _ = Task.Run(await () => 
    {
        try
        {
            await SomeService.DoThePairingJobAsync(someCode, CancellationToken.None)
        }
        catch (Exception ex)
        {
            // Log the exception
        }
    });
    
    return Ok(new GeneralOkResponseModel());
}
```

Also, nit:  It should probably return a 202 (accepted) instead of a 200.

**Comment by GrowSharp** [comment]
Yeah, I tried that. Same result. But now I figured I could combine the two and it seems to be working correctly.
Viz.:
     
```
 try
      {
        return Ok(new GeneralOkResponseModel());
      }
      finally
      {
        Response.OnCompleted(async () =>
        {
          try
          {
            _ = Task.Run(async () => await SomeService.DoThePairingJobAsync(someCode, CancellationToken.None), CancellationToken.None);
          }
          catch(Exception e)
          {
            Logger.Exception(e);
          }
        });
      }
```

And yeah, I agree with the 202 instead of a 200, but it's an endpoint for some crazy old database engine that expects 200 and we don't have access to change it (you don't even want to know what in that GeneralOkResponseModel to be fair..).

I'll give this a fair try, deploy it on production environment and I guess we will see.

Should I close the issue, or could I leave it open for a while.?

Thanks

**Comment by davidfowl** [comment]
I don't see how your fix can be better. It's delaying the operation until the end of the response instead of starting it before the response starts.

**Comment by GrowSharp** [comment]
Yeah, that's true, but it seems to work. At least locally. Without the try + finally statement it just waited until the Service task was finished..

**Comment by davidfowl** [comment]
Can you record a gif and show me how you're determining if it's working or not.

**Comment by GrowSharp** [comment]
I don't know how to record a gif, but I can tell you how I test it.
I use swagger to call that action and place a brakepoint at the beginning of the service task (`DoThePairingJobAsync`) and when I hit the breakpoint I look back at the browser to see if the request is finished or not. In (I guess our) last solution the request is finished with the 200 status code in the moment of the breakpoint hit so it seems okay.

**Comment by GrowSharp** [comment]
I know things are different with attached debugger and so on, but it's the best way I figured to test that.

**Comment by davidfowl** [comment]
> I don't know how to record a gif, but I can tell you how I test it.

https://www.screentogif.com/

> I know things are different with attached debugger and so on, but it's the best way I figured to test that.

Don't attach the debugger, just put an infinite delay in `DoThePairingJobAsync` and see if it reproduces.

**Comment by GrowSharp** [comment]
Thanks for the link.
And yes. With `thread.sleep` instead of breakpoint your solution (without the try, finally statement) seems to be working as well.

**Comment by emiliovmq** [comment]
If SomeService instance is injected into the controller (by DI for the current request scope), as soon as you get out of the request's scope you'll then lose that instance from the task (in the thread pool). I suggest using IServiceScopeFactory, create a new scope, and then get the service instance for that new scope (get a service might look like an anti-pattern but for situations like this - fire and forget - it is the recommended path). See https://michaelceber.medium.com/net-core-web-api-how-to-correctly-fire-and-forget-database-commands-from-controller-end-point-cad7a879630

**Comment by davidfowl** [comment]
Thanks for the reminder. See https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/Scenarios/Controllers/FireAndForgetController.cs for more examples

**Comment by GrowSharp** [comment]
Okay. Thank you all for your time and help. I believe you provided me with enough resources and ideas for me to make it work.
Closing.
