### ISSUE TITLE
SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#36601]
## Failing Test(s)

- `Microsoft.AspNetCore.Identity.Test.SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled`

## Stacktrace

```text
[xUnit.net 00:00:03.48]     Microsoft.AspNetCore.Identity.Test.SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled [FAIL]
[xUnit.net 00:00:03.49]       Assert.Equal() Failure
[xUnit.net 00:00:03.49]       Expected: 2021-09-17T04:18:01.0000000+00:00
[xUnit.net 00:00:03.49]       Actual:   2021-09-17T04:18:00.0000000+00:00
[xUnit.net 00:00:03.49]       Stack Trace:
[xUnit.net 00:00:03.50]         /_/src/Identity/test/Identity.Test/SecurityStampValidatorTest.cs(310,0): at Microsoft.AspNetCore.Identity.Test.SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled()
[xUnit.net 00:00:03.50]         --- End of stack trace from previous location ---
  Failed Microsoft.AspNetCore.Identity.Test.SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled [32 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 2021-09-17T04:18:01.0000000+00:00
Actual:   2021-09-17T04:18:00.0000000+00:00
  Stack Trace:
     at Microsoft.AspNetCore.Identity.Test.SecurityStampTest.OnValidateIdentityDoesNotExtendExpirationWhenSlidingIsDisabled() in /_/src/Identity/test/Identity.Test/SecurityStampValidatorTest.cs:line 310
--- End of stack trace from previous location ---
```

## Logs

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-32a74b2d27b9405db1/Microsoft.AspNetCore.Identity.Test--net6.0/1/console.e1a0f263.log?sv=2019-07-07&se=2021-10-06T04%3A03%3A38Z&sr=c&sp=rl&sig=O2hMa6JPtwpy1R%2BDfcgrLzAz2m1yqYbEO5DPLCDDT34%3D
## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1365521&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49

**Comment by blowdart** [comment]
@Tratcher you missed a test :)

**Comment by Tratcher** [comment]
That was the new test, but it looks like my math is off by 1s somewhere.

**Comment by adityamandaleeka** [comment]
Wait, is this just happening because UtcNow has moved up a second?

**Comment by Tratcher** [comment]
I see the problem. We're using IClock, but I forgot to replace it with a mock implementation.
