### ISSUE TITLE
Support binding parameters to type Uri in Minimal Actions

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#36649]
### Is your feature request related to a problem? Please describe.

In MVC controllers actions, it is possible to strongly-type a parameter expected to be a URI as `Uri`. For example:

```csharp
public IActionResult MyAction([FromQuery(Name = "redirect_uri")] Uri? redirectUri)
{
    // Implementation
}
```

However, attempting to replicate this with a Minimal Action endpoint results in an exception being thrown.

```csharp
app.MapGet("/my-action", ([FromQuery(Name = "redirect_uri")] Uri? redirectUri) =>
{
    // Implementation
});
```

```
  Message: 
System.InvalidOperationException : No public static bool Uri.TryParse(string, out Uri) method found for redirectUri.

  Stack Trace: 
RequestDelegateFactory.BindParameterFromValue(ParameterInfo parameter, Expression valueExpression, FactoryContext factoryContext)
RequestDelegateFactory.CreateArgument(ParameterInfo parameter, FactoryContext factoryContext)
RequestDelegateFactory.CreateArguments(ParameterInfo[] parameters, FactoryContext factoryContext)
RequestDelegateFactory.CreateTargetableRequestDelegate(MethodInfo methodInfo, RequestDelegateFactoryOptions options, FactoryContext factoryContext, Expression targetExpression)
RequestDelegateFactory.Create(Delegate handler, RequestDelegateFactoryOptions options)
DelegateEndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler)
DelegateEndpointRouteBuilderExtensions.MapMethods(IEndpointRouteBuilder endpoints, String pattern, IEnumerable`1 httpMethods, Delegate handler)
DelegateEndpointRouteBuilderExtensions.MapGet(IEndpointRouteBuilder endpoints, String pattern, Delegate handler)
```

### Describe the solution you'd like

Either of:
1. Minimal Actions (`RequestDelegateFactory`) special-cases `Uri` to bind parameters;
1. Minimal Actions supports extending model binding for types not owned by the application where a `TryParse` or `BindAsync` method cannot be added;
1.  The `Uri` type adds a `TryParse()` method that can be consumed by the built-in binding.

### Additional context

Found using .NET SDK `6.0.100-rc.1.21458.32` to port an existing MVC application to use Minimal Actions.

**Comment by davidfowl** [comment]
Yes this is because MVC supports TypeConverters natively. We could choose to do this as well but there are some concerns around that subsystem and AOT friendliness. If we did this, we would support `Uri` natively or support it via `TypeConverter`.

**Comment by rafikiassumani-msft** [comment]
We will revisit this in NET7. We might examine the following suggestion: `The Uri type adds a TryParse() method that can be consumed by the built-in binding.`

**Comment by davidfowl** [comment]
Seems like this might be the only type we don't support OOTB that MVC does (with built in TypeConverters). That's based on this list here https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#simple-types without consideration for extensibility via type converters. 

Also for the implementation, the type converter does this https://github.com/dotnet/runtime/blob/5605bdff4b104496941cc9e6acfc19783a52e7b8/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/UriTypeConverter.cs#L41-L49. We'll want a [TryCreate overload](https://docs.microsoft.com/en-us/dotnet/api/system.uri.trycreate?view=net-6.0#system-uri-trycreate(system-string-system-urikind-system-uri@)) with similar parameters.
