### ISSUE TITLE
Hot Reload: Net 6.0 RC1 - System.ArgumentException: 'The renderer does not have a component with ID 14.'

### ISSUE THREAD

**Issue by phillipmunn** [dotnet/aspnetcore#36648]
### Describe the bug
We are trying to use new Hot Reload with NET6.0 RC1 in our project with Server Side Blazor.
This is a minimal test case which shows the issue in our project.

### To Reproduce

Please see exact code shared in this repository:
[https://github.com/phillipmunn/-dotnet6-hotreload-bug](https://github.com/phillipmunn/-dotnet6-hotreload-bug)

1. Run the project with the debugger using Visual Studio 2022 Preview 4.
2. At the login page, enter the following test credentials.

```Email: bogija2900@silbarts.com```
```Password: Microsofttest1!```

3. Navigate to the component specified below in Visual Studio.

```DemoPortal\Components\Pages\Financial\Cashup\CashupBanking.razor```

4. Change the text 'TRY CHANGING THIS TEXT AND WATCH THE WORLD' to any other text.
5. Apply the Code changes by clicking the Hot Reload button in Visual Studio.
6. Observe the error: System.ArgumentException: 'The renderer does not have a component with ID 14.'

### Exceptions (if any)
```System.ArgumentException: 'The renderer does not have a component with ID 14.'```
At this point the debugger and the application stops.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```U:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.206 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
  
Microsoft Visual Studio Preview (64-bit)
Version 17.0.0 Preview 4.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The app that you've shared is quite large. Please strip out all the irrelevant bits from it so we can focus our investigation around the right area.

**Comment by phillipmunn** [comment]
Hello @mkArtakMSFT - I've gone through and removed more code to simply the solution further. Unfortunately if I remove any more of the remaining Blazor components in the project then the error disappears.

The error message now says: 'The renderer does not have a component with ID 4.' which I presume refers to the fact there is now less code in the project.

I have noticed the following message in the Javascript Console in the web-browser after the error appears, but I am unclear if this is a "cause" or a side-effect of the original issue which I have reported.

```[2021-09-20T20:10:49.171Z] Error: System.InvalidOperationException: Object of type 'Demo.Portal.Components.Pages.Financial.PaymentTypes.PaymentTypesModal' does not have a property matching the name '@ref'.

   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, String parameterName)

   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)

   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)

   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)

   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)```

**Comment by phillipmunn** [comment]
Version 17.0.0 Preview 4.1 has fixed this issue and the error message can no longer be seen with either the linked minimal repo project or our more complicated project which I cannot share for confidentially reasons.

Hot reload does take ~25 seconds to apply changes, but as this is out of scope of this ticket - I will close this.

**Comment by ryanbuening** [comment]
> Hot reload does take ~25 seconds to apply changes, but as this is out of scope of this ticket - I will close this.

@phillipmunn hot reload is really slow for me as well with the latest VS bits and RC1. Do you know if there is a fix for this or if that issue being tracked somewhere?

**Comment by phillipmunn** [comment]
@ryanbuening I've seen this open issue which suggests there's an improvement in RC2.
https://github.com/dotnet/aspnetcore/issues/32867#issuecomment-909425375

I have not downloaded RC2 myself to try this out though as it's not officially released (pre-release) I think. Hope this is useful.
