### ISSUE TITLE
Template: WeatherForecast for WebAPI template should be lower case

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#36658]
Rest APIs should be lower cased.

To reproduce:

`dotnet new webapi -o TodoApi`

See https://github.com/dotnet/AspNetCore.Docs/issues/23339

**Comment by pranavkm** [comment]
@Rick-Anderson can you elaborate on what needs to be lowercase? The controller name?

**Comment by Rick-Anderson** [comment]
@pranavkm  Yes. At least years ago, the default Apache server was case sensitive.  Maybe that's too picky and I should just document the Web API template showing lower case URLs.

**Comment by pranavkm** [comment]
>  I should just document the Web API template showing lower case URLs.

That would be a reasonable solution. Routing in ASP.NET Core is case insensitive, so it should be fine to demonstrate a lower cased url.
