### ISSUE TITLE
Call API to get Configuration values at Startup.cs

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#36650]
@davidfowl this is the scenario I was mentioning yesterday. Is it the best approach? Maybe not. Any suggestion will be greatly appreciated.

            var serviceProvider = services.BuildServiceProvider().GetService<IFooConfigurationService>();
            if (serviceProvider == null) 
            {
                //abort initialization
            }
            var model = serviceProvider.GetConfigurationAsync().Result;
            services.Configure<FooConfigurationModel>(m=> m= model);

            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = model.DefaultScheme;
                    // other options using model
                })
                .AddCookie(model.DefaultScheme, options =>
                {
                    options.Cookie.Name = model.CookieName;
                    // other options using model
                })
                .AddOpenIdConnect(model.DefaultChallengeScheme, options =>
                {
                    options.Authority = model.Authority;
                    // other options using model
                });

**Comment by halter73** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-core' tag.

**Comment by davidfowl** [comment]
@ylr-research can you show more of your code? You have a chicken and egg problem where you need to resolve something from DI to put in configuration. Does that thing need to be in the container?

**Comment by ylr-research** [comment]
Hi @davidfowl. Basically all those options live in another server which I need to call to get them before I can configure authentication. If you have a better suggestion, I'm all ears. Thanks for following up.
