### ISSUE TITLE
Signalr can't connect on latest RC1 Angular template

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/aspnetcore#36661]
I simply create Angular spa template on VS 2022 RC1 and integrate SignalR but unfortunately it can't connect to server over websocket or other connection options.  I am not sure what is missed 

I tested on previous template as well. 

Here is full project to review [SignalRTestApp](https://github.com/YakupIpek/SignalRTestApp)

My program.cs 
```
using Stratis.MarketPlace.Core;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllersWithViews();
builder.Services.AddSignalR();
var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();


app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");

app.MapHub<StoreHub>("hub");

app.MapFallbackToFile("index.html"); ;

app.Run();
```

Server files
```

    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };
        private readonly IHubContext<StoreClientHub, IStoreClientHub> storeHub;

        public WeatherForecastController(IHubContext<StoreClientHub, IStoreClientHub> storeHub)
        {
            this.storeHub = storeHub;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            storeHub.Clients.All.SendMessage("heyooo!");

            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }

    public class StoreHub : Hub
    {
    }

    public class StoreClientHub : Hub<IStoreClientHub>
    {
        public async Task SendMessage(string message)
        {
            await Clients.All.SendMessage(message);
        }
    }

    public interface IStoreClientHub
    {
        Task SendMessage(string message);
    }
```

My front end files

proxy.conf.js
```
proxy.conf.js

const { env } = require('process');

const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:8688';

const PROXY_CONFIG = [
  {
    context: [
      "/weatherforecast",
      "/hub"
   ],
    target: target,
    secure: false
  }
]

module.exports = PROXY_CONFIG;

```

store-hub.ts
```
import { Inject, Injectable } from '@angular/core';
import { HubConnection, HubConnectionBuilder, HttpTransportType, IHttpConnectionOptions, LogLevel } from '@microsoft/signalr';
import { Observable, Subject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class StoreHub {
  private connection: HubConnection;

  public onMessage = new Subject<string>();

  public onConnected: Promise<void>;

  constructor(@Inject('BASE_URL') baseUrl: string) {
    this.connection = new HubConnectionBuilder()
      .withUrl('/hub', {
        transport: HttpTransportType.WebSockets,
        logger: LogLevel.Trace
      })
      .build();

    this.onConnected = this.connection.start();

    this.connection.on("SendMessage", (message: string) => this.onMessage.next(message));
  }
}
```

and component file
```

import { Component, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { StoreHub } from './store-hub'

@Component({
  selector: 'app-fetch-data',
  templateUrl: './fetch-data.component.html'
})
export class FetchDataComponent {
  public forecasts: WeatherForecast[] = [];

  constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string, private storeHub: StoreHub) {

    this.storeHub.onMessage.asObservable().subscribe(message => {
      console.log(message);
      alert(message);
    });

    this.storeHub.onConnected.then(() => {
      http.get<WeatherForecast[]>(baseUrl + 'weatherforecast').subscribe(result => this.forecasts = result);
    });
  }
}

interface WeatherForecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string;
}

```

**Comment by BrennanConroy** [comment]
Share your logs please. Also, is that proxy an actual proxy? Those can cause issues with websockets, so if you can easily remove it does that solve the issue?

**Comment by javiercn** [comment]
@BrennanConroy talk to me about this.

**Comment by javiercn** [comment]
@YakupIpek thanks for contacting us.

It's likely that you need to specify the `ws:true` option in `proxy.conf.js`

**Comment by YakupIpek** [comment]
@javiercn I wish this was documented. I spend a week on this issue. Now it is connected successfully but server push messages doesn't reach to client :(

**Comment by javiercn** [comment]
@YakupIpek All SPA frameworks use the same underlying proxy middleware, there's detailed docs [here](https://github.com/chimurai/http-proxy-middleware/tree/v0.21.0#table-of-contents)

**Comment by javiercn** [comment]
@Rick-Anderson Do we have a docs section for SPA?

if not, can we start a new section in our docs, and point to [here](https://github.com/chimurai/http-proxy-middleware/tree/v0.21.0#table-of-contents) for details on how to configure the proxy?

**Comment by YakupIpek** [comment]
@javiercn I check connection count on internals of connection in debug mode and i see that count is 0. 

I added app.UseWebsockets(); to startup and still it is same

**Comment by javiercn** [comment]
@YakupIpek I'm marking this as investigate, since it seems there's something to figure out here (at the very least for our own understanding). We will triage it and update the issue accordingly.

**Comment by davidfowl** [comment]
@javiercn is this using the new proxy support we added? Does that properly handle websockets?

**Comment by javiercn** [comment]
@davidfowl it should. It's not clear what we are missing here, hence the investigate. 

I do know you need to configure some things (see the link above with all the detailed docs)

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Do we have a docs section for SPA?
> 
> if not, can we start a new section in our docs, and point to [here](https://github.com/chimurai/http-proxy-middleware/tree/v0.21.0#table-of-contents) for details on how to configure the proxy?

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular

![image](https://user-images.githubusercontent.com/3605364/134026781-67239fa0-fb7b-4597-b2ca-4384d79626e2.png)

**Comment by davidfowl** [comment]
I tried the repro project and the websocket request hangs. Feels like it's related to the proxy missing configuration

**Comment by YakupIpek** [comment]
@davidfowl 

`app.UseWebSockets();` was missing on repro project and i added it now. But still it is same.

**Comment by davidfowl** [comment]
UseWebSockets isn't required for SignalR. It does that automatically

**Comment by YakupIpek** [comment]
I hope there will be a fix for it soon. I am in waiting state :(

**Comment by YakupIpek** [comment]
@javiercn Is there any update on this. There may be a quick fix or workaround?

**Comment by javiercn** [comment]
Things work with the appropriate config without issue

```js
  {
    context: [
      "/hub"
    ],
    target: target,
    secure: false,
    ws: true,
  }
```

![image](https://user-images.githubusercontent.com/6995051/134518947-01a3fa2f-73f8-40a4-81aa-5faa788dcc47.png)

**Comment by javiercn** [comment]
Here is my entire config for reference
```js
const { env } = require('process');

const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:8688';

const PROXY_CONFIG = [
  {
    context: [
      "/weatherforecast",
      "/hub"
   ],
    target: target,
    secure: false
  },
  {
    context: [
      "/hub"
    ],
    target: target,
    secure: false,
    ws: true,
  }
]

module.exports = PROXY_CONFIG;
```

**Comment by javiercn** [comment]
It's not clear to me what you are trying to do with signalr here, but I do believe there is no websocket/proxy/spa issue involved after the suggested configuration changes.

If you clarify what you are trying to accomplish, someone on the signalr side of things will help you.

**Comment by YakupIpek** [comment]
Thanks for quick response

On controller side, i push `SendMessage` event when get method is called. 
```
  public IEnumerable<WeatherForecast> Get()
        {
            storeHub.Clients.All.SendMessage("heyooo!");

            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
```

I listen `SendMessage` event on client side in store-hub.ts and FetchDataComponent

```
    this.connection = new HubConnectionBuilder()
      .withUrl('/hub', {
        transport: HttpTransportType.WebSockets,
        logger: LogLevel.Trace
      })
      .build();

    this.onConnected = this.connection.start();

    this.connection.on("SendMessage", (message: string) => {

      alert(message);
      this.onMessage.next(message)
    });
```


Onfortunately this event `SendMessage` is never triggerred. 

I updated [SingnalR Test App](https://github.com/YakupIpek/SignalRTestApp). 

I need help :(

**Comment by BrennanConroy** [comment]
Your controller is using `IHubContext<StoreClientHub, IStoreClientHub>` but your client is connecting to `StoreHub`
https://github.com/YakupIpek/SignalRTestApp/blob/9a78caa2c520412d5b5edf47b12edf2e3f0a14d9/Project20/Program.cs#L27

**Comment by YakupIpek** [comment]
Sorry something made me confused on docs that i read. Ok Thank you it worked now :(

**Comment by davidfowl** [comment]
@javiercn this should be documented

**Comment by javiercn** [comment]
@Rick-Anderson can we add something to the docs here?
