### ISSUE TITLE
Minimal API experience in VS Code Dev Container / Codespaces

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#36678]
### Minimal API experience in VS Code Dev Container / Codespaces

VS Code has new features to develop and run apps using dev containers.  This can also be done using Github Codespaces. It will be great to investigate the experience of developing a Minimal API app using VS dev containers or Codespaces .  We would like to track the experience for below scenarios:

- Create a CRUD app 
- Add ef core, create and run migrations
- Add any other dependencies
- Run the app locally
- Debug 
- Create and run a simple Unit and Integration test for an endpoint
- Package and deploy to Azure app Service

**Comment by captainsafia** [comment]
Closing this issue for now. We've been able to demo minimal APIs in Codespaces for a few conference presentations now. There's no actionable work on the team for this area in .NET 8. If things come up, we can evaluate them independently.
