### ISSUE TITLE
Unable to deploy web app using MSBuild

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/aspnetcore#36686]
I am trying to compile a .net core web application using msbuild.

However, I am unable to deploy that build output(using zipdeploy extension in arm template) of web app.

I also noticed that the build output folder is quite different from the one when I try to run and publish using VS 2019(which uses Roslyn).

What is the corresponding command in msbuild to compile my web app correctly in order to deploy it to azure?

Here is the command that I am using-

msbuild -t:restore  "%~dp0\src\WebApplication1\ASMFeedbackWebApp.csproj" /p:Configuration=Release /p:platform=x64

msbuild "%~dp0\src\WebApplication1\ASMFeedbackWebApp.csproj" /p:configuration="release";platform="x64";DeployOnBuild=true;SkipInvalidConfigurations=true;DeployDefaultTarget=WebPublish;WebPublishMethod=FileSystem

Even when I tried msbuild /t:publish - I don't have success in using zipdeploy to deploy the web app.

Is there something that I could be missing?

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.413
 Commit:    8387734958

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.413\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@ssarin3194 thanks for contacting us.

Can you please include the error you are seeing?

**Comment by ssarin3194** [comment]
I am not seeing any error in the compilation. However, when I try to deploy using this msbuild command(using zipdeploy extension in my ARM template), I don't see the app running correctly.

I want to understand if the parameters that I am passing to msbuild are correct or not.

**Comment by Pilchie** [comment]
Tagging @vijayrkn.  My understanding is that you shouldn't really be using deployonbuild.

**Comment by ssarin3194** [comment]
Also, what would the webPublishmethod be? FileSystem or Package?

msbuild ""src\WebApplication1\ASMFeedbackWebApp.csproj" /p:configuration="release";platform="x64";SkipInvalidConfigurations=true;WebPublishMethod=Package -- would this do the trick?

**Comment by vijayrkn** [comment]
@ssarin3194 - You can look at the documentation here on how to publish .NET Core web apps: 
https://github.com/dotnet/sdk/tree/main/src/WebSdk#folder-publish

If you want to publish your web app to a folder, then you can simple use : 
`dotnet publish WebApplication.csproj /p:<custom params>`

If you want a web deploy package: 
`dotnet publish WebApplication.csproj /p:WebPublishMethod=Package /p:PublishProfile=DefaultMSDeployPackage`

Let me know if you still have questions that are not addressed as a part of the documentation.

**Comment by ssarin3194** [comment]
This is really helpful. Quick question- I am using ZipDeploy extension to deploy this web app(using arm template). I dont see any documentation for that...

**Comment by ssarin3194** [comment]
Also, can you shed light on publishing to a folder or using web deploy package? For deploying the package to azure, won't we be needing the latter?

**Comment by vijayrkn** [comment]
Web deploy package is a special type of deployment package that you use to package up the app and to deploy them later. It is mostly used in the IIS scenarios - https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/deploying-web-packages

If you are using Zip deploy, then it is not compatible with web deploy packages. I am not quite clear on what you mean by the zip deploy extension? Can you share a sample app with the command you are currently using to package up the app so that I can understand the scenario better?

**Comment by ssarin3194** [comment]
I was able to compile my application using zipdeploy by building the app using

msbuild "<>.csproj" /p:configuration="release";platform="x64";DeployOnBuild=true and zipping the publish package generated using this command.
