### ISSUE TITLE
We need better way to deal with css animations. Reliable OnAnimationEnd, allow element to force re-render or something.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#36700]
To make an element run animations we need one of this 2 things:

1: Reliable way to run code "onanimationend" (ideal)
2:  As a workaround, something to force an element refresh.

Currently to swap between two items and runs a simple fade in I need to hack it with option1: `Task.Delay`, unreliable javascript interop or option2: use a toggle variable and have 2 equal elements.

```
@code 
{
	bool toggle;

	public void SetActivateTab(Tab? tab)
	{
		if (ActiveTab != tab)
		{
			toggle = !toggle;
			ActiveTab = tab;
			StateHasChanged();
		}
	}
}

@if (toggle)
{
	<div class="fade-in">
		@ActiveTab?.ChildContent
	</div>
}
else
{
	<div class="fade-in">
		@ActiveTab?.ChildContent
	</div>
}
```

styles:
```
@keyframes fadein {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We haven't yet spent much time thinking about animations specifically, but we'll be looking into that in the future.
We track that work as part of #10389
