### ISSUE TITLE
WorkerService detect appsettings.json changes

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#36708]
Can appsettings.json changes be reloaded without restarting a WorkerService?

I was looking at the options pattern, specifically at the [Options interface](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#options-interfaces) which describes how to do it for a web app were requests (HTTP requests I think?) are available.

But how can we detected changes and reload the configuration for a non web app?

**Comment by Tratcher** [comment]
It is the same for a worker service.

**Comment by mihaimyh** [comment]
Thanks, I just tested it with `IOptionsMonitor` and it is working.
