### ISSUE TITLE
Blazor WebAssembly - How can I add a new *.razor page that don't need to recompile or build the project

### ISSUE THREAD

**Issue by chinhdnk** [dotnet/aspnetcore#36704]
I am developing a survey project which collects data from the client with Blazor Webassemly for the Client-side. Each survey form will have a different design and edit-checked rule. So I decide when I create a new survey form, the application will generate a new *.razor page automatically, for example, ClientSurvey.razor page. Everything works well until I navigate the web application to the ClientSurvey.razor I just have created. The system shows error 404 Not found. I have to rebuild the project again, and I can show the ClientSurvey.razor page on my website.
With Asp.net MVC before I don't have to rebuild the project when I add a new aspx page. Does it still work with blazor webassembly? If yes, what must I do?

And I also meet a problem that when I deploy the project in IIS, I don't see where the UI (.*razor) pages are stored. How can I keep them in raw files in the same way with Asp.net work? With Asp.net, when I deploy it in IIS, there is always a folder to store aspx pages.
Please the figure below to more clearly
![Question](https://user-images.githubusercontent.com/30072475/133949553-3dde0843-9c2e-435b-bd0b-d5b5883c9bfe.png)

**Comment by javiercn** [comment]
@chinhdnk thanks for contacting us.

You likely were relying on runtime compilation for razor files, that's not available in Blazor applications, you need to compile your app views into a `.dll` and redeploy the app for the changes to take effect.

During development we have a different feature that achieves "similar" results, which is called "hot reload" and will "patch" your application while its running for the changes to take effect.
