### ISSUE TITLE
VS2022 Preview 4 Very high CPU Consumption even when Idle

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#36710]
Not sure if this is correct repo to report the bug, but since i am developing Blazor WASM .NET core 6 RC1 thought of reporting it here.

I am running into weird problem where after upgrading to VS2022 Preview 4(.NET 6 RC1) I see constant High CPU usage 75%>
Not only that I am no longer able to continue using the VS2022, the only way to recover from this is to close the VS2022 and start it again. Than again I run into high CPU usage and I have to keep on repeating the closing and re-starting cycle of VS2022.

The spike in CPU usage does not happen immediately when I start the VS 2022 but over the time when developing and debugging the code.

Here is the screen video recording of it of high CPU when VS2022 is idle(none of the browser are running the App.)

https://1drv.ms/v/s!AtHk7h6Srnk_h9hBzmAkFcGqNwqrkg?e=4U4vXq

When I decided to report the incident via VS2022 Feedback tool, Interestingly I noticed _(👽spooky thing , may be Halloween is around)_ that  as soon as i hit record, the CPU usage came down and as soon as I hit the stop recording the CPU usage went up again.

**NOTE:** when i recorded this video none of the browser were running the App, visual studio is idle.

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019 is the best way to report these types of issues as it will capture more details about the environment.

**Comment by javiercn** [comment]
Closing this since it has been reported through the feedback tool

**Comment by nssidhu** [comment]
FYI: The screen recording in this issue has more details than what was reported via feedback tool.

**Comment by boukenka** [comment]
@nssidhu I have noticied the same issue. It is happening when editing the blazor pages or components. If I only modify the C# code, it is fine.
