### ISSUE TITLE
blazor = RenderFragment + MarkupString

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#36714]
I'm going through a situation that I don't know how to get around. I have a function that generates a sequence of components (texts, clickable buttons, etc) through RenderFragment. But this whole structure belongs to HTML code (which I can render as HTML using the MarkupString). But I can't use both at the same time. Is there any way I can use both?

![image](https://user-images.githubusercontent.com/12803050/133906211-370cb58a-c491-491c-bcb8-1d05eb1aa3d7.png)

```
--this method returns a RenderFragment
@VariableHelper.CreateGenericComponent(TreeElement.TextBlock.MainText)
```
```
--here I render my html code
@((MarkupString)TreeElement.TextBlock.MainText)
```
I want to be able to take my text and create the components I need and at the same time generate it as if it were an HTML component, but it's not being accepted
![image](https://user-images.githubusercontent.com/12803050/133906260-5e8ddf05-480f-450c-a0af-c5bf7036fb86.png)
![image](https://user-images.githubusercontent.com/12803050/133906279-d92e4580-e127-4e97-bb3e-2fb86fc27bda.png)

**Comment by Xyncgas** [comment]
```
var fragment = VariableHelper.CreateGenericComponent(TreeElement.TextBlock.MainText);
<div>
@fragment
</div>
```
BTW IS the TreeElement.TextBlock.MainText a random something text or actual html?
Why are you simply using (MarkupString)TreeElement.TextBlock.MainText or the component but you want both?
I think what you are doing is pretty elegant

**Comment by javiercn** [comment]
@drma-dev thanks for contacting us.

I suspect that @Xyncgas answer is correct; that said I don't think we have enough info to understand the scenario completely. If you could create a more detailed repro that illustrates the problem, that will help us make progress.

I'm marking this as answered

**Comment by drma-dev** [comment]
![image](https://user-images.githubusercontent.com/12803050/134001249-62b0ca1d-ae44-4066-9f98-47b7081f9320.png)
![image](https://user-images.githubusercontent.com/12803050/134001340-eb2e29fa-7770-4e11-840f-94907f5c169e.png)
doesnt work.

ok, this is my original code:
![image](https://user-images.githubusercontent.com/12803050/134001663-1d9a8117-fe67-48e2-a34b-c2fa64f0e913.png)
it's an html body, but it has special parts that I need to turn into a button (which calls a C# function). so i need to create component dynamically by a fragment method.
![image](https://user-images.githubusercontent.com/12803050/134001991-9077a8ca-5ac8-460a-a135-939ee49f715e.png)

**Comment by javiercn** [comment]
@drma-dev ok, so if I understood correctly, you have a bunch of markup (as a string) that you want to programmatically turn into a render fragment (with a button, event handler and so on). Am I correctly understanding the scenario?

**Comment by drma-dev** [comment]
Yes that's right. it's a mix of html body with components that need interaction with c#

**Comment by drma-dev** [comment]
I don't know if I understood what you meant.

is there any way to render this fragment as an HTML, without having to use the MarkupString?
or can you visualize any other way to do what I need that I can't see?

**Comment by drma-dev** [comment]
@javiercn  can I make a demo and send it to you, to see if you can see an alternative way to solve this? :)

**Comment by drma-dev** [comment]
[https://github.com/drma-dev/HtmlFragment](https://github.com/drma-dev/HtmlFragment)

**Comment by drma-dev** [comment]
@javiercn

**Comment by javiercn** [comment]
@drma-dev thanks for the clarification.

We don't support turning strings into render fragments at runtime, that's something you would need to build yourself (as you are trying to do). That said, I don't recommend going this route, since at that point you are pretty much writing a compiler.

**Comment by drma-dev** [comment]
@javiercn 
I can't think of any other way at the moment.  is it possible to call C# function only with HTML?  maybe using javascript to help

**Comment by javiercn** [comment]
@drma-dev no, its not possible.

You are replicating what the razor compiler does, but at runtime. You want to convert a string containing "razor" into the equivalent "compiled code", and that's something we do at compile time. 

As I mentioned before, what you are trying to achieve is the equivalent of implementing the razor compiler at runtime.

**Comment by drma-dev** [comment]
what do you mean it's not possible?  and the support that the blazor gives in the interaction between c# and javascript?

**Comment by javiercn** [comment]
@drma-dev My understanding is that you want `    public string html { get; set; } = "<p class='ql-align-justify'>{@button01} <span style='color: rgb(230, 0, 0);'>123 </span><strong style='color: rgb(255, 153, 0); background-color: rgb(0, 138, 0);'>abc</strong> xyz</p>";` to turn into code where `button01` is some sort of render fragment that can gets rendered inside the other component by razor. 

That's what I'm suggesting is not something supported "at runtime", if you put that string into a separate file, and compile it into a component, that's what is supported.

**Comment by drma-dev** [comment]
This string will be done by the user, so it can be anything.

If, instead of using fragment, i write the link code where i call a JavaScript that call a c# code. So, when the MarkupsString build the html body, it will make my link works ?

**Comment by Xyncgas** [comment]
I don't understand what you are saying personally and it's hard for me to help.
that said, I want to answer your question by saying, you can achieve turning user input to (HtmlMarkupString), if that's what you need, but it has to be html, which correct me if I am want, if you are trying to turn a plain text from user input into renderFragment as if you are building an online blazor compiler, then that's also possible by using CI/CD at least in my 'first-think-of'.
I also want to help by saying something, since I can't understand what you are asking, like dynamic rendering is definitely possible if you can build a compiler run it inside blazor and have it parse the user's text and spit out html on the screen, it doesn't have to be complete, as long it fits your need, one good example is MarkDown, and there's nuget library that you can install in a blazor project that let user write mark-down and rendering it into pages using your content/business logic. microsoft's documents are done this way too

**Comment by drma-dev** [comment]
Hi @Xyncgas , did you see the demo I left available here? I think it's clearer there what I'm waiting for.
