### ISSUE TITLE
Duplicated reference by transitive dependence

### ISSUE THREAD

**Issue by pedrofernandesfilho** [dotnet/aspnetcore#36728]
On a WebApi AspNetCore project has reference to a NuGet package that reference Microsoft.AspNetCore.Mvc.
The project WebApi AspNetCore is on version .NET 5 and NuGet package is on version .NET Core 2.2.

In build appear the warning message:
```
CSC : warning CS8034: Unable to load Analyzer assembly C:\...\.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.2.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll : Assembly with same name is already loaded [C:\....csproj]
```
In VS appear the warning message:
```
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'
```

![image](https://user-images.githubusercontent.com/508725/133942993-98b03a13-3f18-415a-9ec6-2914eafbb9f3.png)

What is the consequence of this? This double reference of Mvc can cause some problem in the application?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We recommend removing the reference to the microsoft.AspnetCore.Mvc package (2.2) as it's no long supported. That will also remove the analyzer dependency.

**Comment by pedrofernandesfilho** [comment]
Thanks for your recommendation.
I remain with the doubts: 
What is the consequence of this? Can this double reference of Mvc cause some problem in the application?
