### ISSUE TITLE
[dotnet-watch] Hot reload capabilities are sometimes not reported for blazor-wasm

### ISSUE THREAD

**Issue by sergiojrdotnet** [dotnet/aspnetcore#36723]
### Describe the bug
`dotnet watch` is not recognizing Razor changes on Blazor WebAssembly project.

### To Reproduce
1. `dotnet new blazorwasm`
2. `dotnet watch`
3. Apply a change on any razor file

### Exceptions
![image](https://user-images.githubusercontent.com/72770006/133925120-b75b944d-5b2e-43cd-9e27-158438fa5cab.png)

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

![image](https://user-images.githubusercontent.com/72770006/133925163-eac6f3e8-4ca4-49ce-bcfd-863aa6fc7d1b.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have tests validating that this works. So if you have some specific setup / repro setps that you'd like to share that would help us investigate this further.

**Comment by sergiojrdotnet** [comment]
Of course, I'll send a demonstration in a few moments

**Comment by sergiojrdotnet** [comment]
https://user-images.githubusercontent.com/72770006/134091870-6b484e13-33bb-45ed-b2e8-9a3dde9d3408.mp4

**Comment by sergiojrdotnet** [comment]
I also tried daily build `6.0.100-rc.2.21470.35` and the problem keeps occurring.

**Comment by mkArtakMSFT** [comment]
Thanks @sergiojrdotnet . Did you by any chance try this from VS and/or know whether that will work?

**Comment by sergiojrdotnet** [comment]
@mkArtakMSFT It didn't work either

https://user-images.githubusercontent.com/72770006/134261171-b9158ad0-d098-4637-a972-1a54cb87f1b6.mp4

**Comment by MisinformedDNA** [comment]
I'm seeing the same issue. Neither VS nor `dotnet watch` are working.

**Comment by pranavkm** [comment]
@sergiojrdotnet for your VS issue, unfortunately we haven't made hot reload for Blazor WebAssembly work with the debugger as yet. We're looking at addressing it, but it's unlikely to be solved prior to VS 2022 GA. However, if you run the app without the debugger attached (`Ctrl+F5`) it should work with VS 17.0 Preview 4.1. Do you mind giving that a try?


@MisinformedDNA could I bother you to file a separate issue (assuming it's not addressed by my previous comment)?

**Comment by sergiojrdotnet** [comment]
@pranavkm Yeah! It works on VS without debugger attached. Excelent!

**Comment by pranavkm** [comment]
For watch, we made a fix for a timing issue in the RC2 SDK that I think might address the issue you are seeing. You could try a [nightly build of the installer](https://github.com/dotnet/installer#installers-and-binaries) to see if it helps with the odd behavior you were seeing.

**Comment by sergiojrdotnet** [comment]
@pranavkm, unfortunately, the watch issue still the same here with version `6.0.100-rc.2.21473.35`.

**Comment by sergiojrdotnet** [comment]
@pranavkm It looks weird. With version `6.0.100-rc.2.21473.35` didn't work in the first attempt, worked after some time and does not work anymore. I'm trying to figure out what could possibly be interfering.

**Comment by pranavkm** [comment]
If you run `dotnet watch --verbose`, it should print some logs about that might help.

**Comment by sergiojrdotnet** [comment]
I really can't find what is happening. Sometimes it works, sometimes not, like a flip of a coin.

https://user-images.githubusercontent.com/72770006/134595593-58de8ec2-2388-4d70-8b68-b1bc559a26a9.mp4

**Comment by pranavkm** [comment]
It's a result of not being to infer the hot reload capabilities. The 2nd time around it print an empty string instead of "Hot reload capabilities: Baseline". I thought I'd fixed it, but perhaps didn't fix it hard enough

**Comment by ziaulhasanhamim** [comment]
Having the same issue. working perfectly fine with vs 2022. but not with dotnet cli. no hot reload changes are applied. Everytime I made a change I have to restart

**Comment by ziaulhasanhamim** [comment]
any progress on this issue?
