### ISSUE TITLE
[Blazor WebAssembly] Performing hot reload when the browser is closed results in a unhelpful exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36733]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-Performing-hot-relo/1530899)._

---
Repro steps:

1) Create a new blazorwasm app
2) Ctrl+F5
3) Make some edits to make sure hot reload is working
4) Close the browser
5) Make a non-rude edit

I'm ok treating this as a rude edit (the dialog pops up), but there's nothing in the diagnostic window indicating this is rude. If I look in the Hot Reload output window, I can see this:

```
TestApp (Web assembly): Applying updates failed: An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details. An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
TestApp (Web assembly): Sending updates to running application
TestApp (Web assembly): Applying updates failed: The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
```

---
#### Feedback Bot on 9/16/2021, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This turned out to be a VS bug so reopened the original feedback ticket.
