### ISSUE TITLE
Blazor server PageTitle component not working with Hot reload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-server-PageTitle-component-not-wo/1529911)._

---
[severity:I'm unable to use this version]
VS2022 Preview 4, Blazor server project.
! [Counter.png] (https://aka.ms/dc/image?name=B61204f3e8b024e0b8e58385f4f844285637672895268206801_Counter.png&tid=61204f3e8b024e0b8e58385f4f844285637672895268206801)

In <PageTitle>Counter</PageTitle> let's change the text "Counter" to "Counter changed"
and hit Hot Reload.

Instead of changing page title to the new "Counter changed" the text is rendered directly in Counter page.

---
#### Feedback Bot on 9/16/2021, 01:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which we're going to ship as part of the upcoming VS patch release.
