### ISSUE TITLE
RazorPage:  @code in index.cshtml produce compile error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36731]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/RazorPage:--code-in-indexcshtml-produc/1531927)._

---
The following code produces a compile error CS0103:
@page
@model IndexModel
@using Microsoft.AspNetCore.Components.Rendering

@{
    ViewData["Title"] = "Home page";
}

<h1>Hello world</h1>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<form method="post">
    <div class="form-group">
        <input asp-for="Product.Name" class="form-control" />
    </div>
    <br>
    @code {
        int i = 0;
    }
</form>

If I change '@code' against @function it works. Project is the RazorPageSample from https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio

Project framework is .Net 5.

---
#### Feedback Bot on 9/16/2021, 06:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This is actually by-design. `@code` block is a Blazor concept and is available only in `.razor` files.
