### ISSUE TITLE
Razor Class Library isn't adding static assets outside the ```wwwroot``` folder

### ISSUE THREAD

**Issue by Valks** [dotnet/aspnetcore#36740]
### Describe the bug

Building a Razor Class Library through a CI platform (Azure DevOps or Github Actions) isn't producing the same NuGet package I'm building locally.

The package is missing the ```staticwebassets``` that exist outside the ```wwwroot``` folder, i.e. ```Components/Svg.razor.js``` but still adding entries for those assets in the ```build/Microsoft.AspNetCore.StaticWebAssets.props``` file.

### To Reproduce

I can no longer reproduce the problem locally. After updating my local copy of dotnet (WSL) from preview.7 to rc.1 it stopped exhibiting the behaviour.

That said, when I was having the issue locally I was building out of the same directory on Windows (VS and cmd prompt) which generated a correct package and Linux (WSL) which exhibited the problem.

I have built the repo below as a sample to try and reproduce the issue but it's slightly different again from the main project I'm having issues with. For some reason, the GitHub actions version is missing the build folders.

I also added an azure pipeline and built it with Azure DevOps (Linux). That package is showing what I'm experiencing with my projects when building via CI.

https://github.com/Valks/RCLStaticResourceTest

Attached below is the same project built locally on my PC, as can be seen inside the NuGet package the staticwebapps folder is populated correctly and there's no ```content``` or ```contentFiles``` folders.

[RCLStaticResourceTest.1.0.0.zip](https://github.com/dotnet/aspnetcore/files/7194024/RCLStaticResourceTest.1.0.0.zip)

The pictures below are what I'm experiencing after building my main project via CI/CD.

![image](https://user-images.githubusercontent.com/3953780/133967120-fb71fad9-451e-4f08-96cd-a0b091e54e7d.png)
![image](https://user-images.githubusercontent.com/3953780/133967133-b0bf9044-362e-49dc-8416-5fd6c5949180.png)

### Further technical details
All built using .net 6.0 rc.1 (6.0.100-rc.1.21458.32)

**Comment by javiercn** [comment]
@Valks thanks for contacting us.

How were you including the assets in the package?

Also beware that (based on your file extension) we added a new feature in RC1 to do what you are doing here automatically. See [here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/#collocate-javascript-files-with-pages-views-and-components)

**Comment by Valks** [comment]
@javiercn I'm depending on that functionality to include the associated css and javascript files.

That said, at the moment I'm not calling the import function in code, could that be a reason the file is skipped?

**Comment by javiercn** [comment]
@Valks you mention preview7 on the bug report, we didn't have a feature for this until RC1, so were you doing this by yourself (in the csproj file) before RC1?

**Comment by javiercn** [comment]
@Valks no, this process is completely file based.

I'm going to go on a limb here, can you check to make sure the casing of the file matches the casing for the component? Could you capture the binlog from a build that produces the wrong results?

**Comment by Valks** [comment]
The preview 7 attempts were a mistake at the time. I'd forgot to check what version was installed.

The casing is correct.

That's straight from Azure DevOps, hopefully, it's what you're after.
[1_Job.txt](https://github.com/dotnet/aspnetcore/files/7195202/1_Job.txt)

**Comment by javiercn** [comment]
@Valks thanks for the additional details.

That simplifies things, I was asking for an msbuild.binlog file produced by passing `/bl` to the task in question.

**Comment by javiercn** [comment]
If you repro this in WSL, just go to your project and do `dotnet build/pack (whatever you are using) /bl`

**Comment by javiercn** [comment]
@Valks the job doesn't contain the details we need.

**Comment by Valks** [comment]
Finally got it setup. That log is from the build step. Hopefully, it contains something useful.

[build.zip](https://github.com/dotnet/aspnetcore/files/7195311/build.zip)

I'll take a look at trying to get DevOps to use RC2 and see what happens.

**Comment by javiercn** [comment]
@Valks Thanks for the binlog you provided. It does seem to be for a "vanilla" app and not your app, I can't find `Components/Svg.razor.js" on it.

**Comment by Valks** [comment]
The binlog was from the demo repo I setup:
https://github.com/Valks/RCLStaticResourceTest

It should have a Component1.razor.js
https://github.com/Valks/RCLStaticResourceTest/tree/master/RCLStaticResourceTest/Components

**Comment by javiercn** [comment]
@Valks nevermind, I think I repro it now

**Comment by user72356** [comment]
When is this RC2 coming out? I think I have the same issue. My *.js files in the wwwroot of my RCL, are not included when publishing a nuget package. They are referenced in the Microsoft.AspNetCore.StaticWebAssets.props file but it points to a non-existing staticwebassets folder in the nuget.

**Comment by Valks** [comment]
Thanks for the quick follow up. Glad it's definitely in the RTM. For my needs that's fine.

Also, thanks for the comment about ```GeneratePackageOnBuild```, always worth mentioning little details like that to pick up on those bits of advice, I'll rework my projects with that in mind (after RTM) and skip dotnet pack for now.

**Comment by robertmclaws** [comment]
Hey folks! I have a workaround for you: Put the following in your .csproj file:

```xml
  <ItemGroup>
    <None Include="$(BaseIntermediateOutputPath)\$(Configuration)\net6.0\scopedcss\projectbundle\*.scp.css" Visible="false">
      <PackagePath>staticwebassets</PackagePath>
      <Pack>true</Pack>
      <InProject>false</InProject>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
```

Should cover your bases for NuGet packages until RTM.
