### ISSUE TITLE
[blazor] Can nuget packages that enables p2p be supported in blazor? is it possible for now?

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#36741]
My understanding is the web-browser is a non-traditional platform and we are running mono and a lot of the stuffs is restricted to the browser and web-assembly's capability.
So if for example I am programming sockets / tcp peering in my c# code, is that even going to work in blazor, because I am not familiar with the landscape

**Comment by Xyncgas** [comment]
if it's impossible can we get it in .net 7

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This will never be possible unless the underlying brower/webplatform supports it.
