### ISSUE TITLE
Design issues on Registration/Login pages  in Angular SPA template 

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/aspnetcore#36750]
ASP.NET Core Angular SPA RC1 has design issues on Registraton page and login page. I tested on default template. It was fine in previous preview version. 

![14107e55a14c35b5f38becd696266f84](https://user-images.githubusercontent.com/335426/134043303-31ea2fb4-519d-4f52-ba8e-6328f5d0ae0d.png)

**Comment by javiercn** [comment]
@YakupIpek thanks for contacting us.

@HaoK did we not fix some of these things? Are we missing updates somewhere?

**Comment by HaoK** [comment]
What's the issue specifically here?  We switched to the floating text/larger button to align with bootstrap5's look and feel if that's the question, its supposed to look different:

https://getbootstrap.com/docs/5.1/examples/sign-in/
