### ISSUE TITLE
Blazor project debugger only breaks on `onchange` event when `onblur` and `onchange` both specified in a text input, and breakpoints are set for both handlers.

### ISSUE THREAD

**Issue by Owenll66** [dotnet/aspnetcore#36760]
### Describe the bug
Blazor project debugger only breaks on `onchange` event when `onblur` and `onchange` both specified in a text input, and breakpoints are set for both handlers.

I had a text input with both `onblur` and `onchange` event.

```html
<input type="text" @onblur="HandleOnBlur" @onchange="HandleOnChange" .../>
```

then I had handlers as below

```csharp
protected void HandleOnBlur(FocusEventArgs args)
{
    Console.WriteLine("On Blur Call");
}

protected void HandleOnChange(ChangeEventArgs args)
{
    Console.WriteLine("On Change Call");
}
```
In my experiment, I use Visual Studio 2019 to set breakpoints on both functions. If I do not edit the value just click in and click out, only `On Blur Call` is printed in the console, which is what I expect. If I edit the value to be different then tab out, only `HandleOnChange` is hit and only `On Change Call` is printed. Interestingly, if I remove both breakpoints, both `On Change Call` and `On Blur Call` will be printed.

(I think it might be a problem with Visual Studio 2019. So I am not 100% sure if I should post this issue here)
### To Reproduce

I have created my github repro here: https://github.com/Owenll66/BlazorTextInput
StackOverflow: https://stackoverflow.com/questions/69232903/blazor-why-onchange-and-onblur-event-are-not-both-triggered-if-i-set-breakpoint
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
**IDE - Microsoft Visual Studio Professional 2019 Version 16.11.3
Chome - Version 93.0.4577.82 (Official Build) (64-bit)**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Owenll66.
@thaystg has validated the same scenario in a pure html page and the behavior is the same, so debugger changes nothing here. Going forward, this is a good way to validate things :) We're closing this issue as the behavior is expected and there is no more action pending here.

Thanks for your help, @thaystg !
