### ISSUE TITLE
Error: Failed to start the connection: Error: None of the transports supported by the client are supported by the server

### ISSUE THREAD

**Issue by maloo** [dotnet/aspnetcore#36775]
### Describe the bug
I got a basic Blazor Server app that worked great in Preview7. I just updated it to RC1. Debugging/running the app locally on my machine works fine. When publishing to Azure App Services (Windows) I get the error below.

blazor.server.js:1 [2021-09-20T23:35:15.634Z] Error: Failed to start the connection: Error: None of the transports supported by the client are supported by the server.
blazor.server.js:1 [2021-09-20T23:35:15.634Z] Error: Error: None of the transports supported by the client are supported by the server.
blazor.server.js:1 [2021-09-20T23:35:15.635Z] Error: Failed to start the circuit.

### To Reproduce
I'm unable to share the code. But hoping you can at least improve the error message to give the user some indication of where to start looking. Also what type of protocols are we talking about? SignalR? http/https? HTTP 1/2? Error message is very vague. Could this be related to long polling being disabled in RC1? If so, does this mean we should not run Blazor Server apps on Azure?

### Further technical details
- ASP.NET Core version .NET 6 RC1
- Include the output of `dotnet --info`
- .NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.400 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.119 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS2022 preview 4

**Comment by danroth27** [comment]
See https://github.com/aspnet/Announcements/issues/470 for the related breaking change, although this change is being reverted in the next .NET 6 update.

**Comment by TanayParikh** [comment]
Hey @maloo, yes it's related to long polling being disabled as a default transport in RC1. Note we've reverted this change for RC2. 

Regarding it not working on Azure App Services, please see https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-6.0#configure-the-app-in-azure-app-service for configuration details. Web Sockets need to be explicitly enabled. 

To re-enable long polling, please see the breaking change notification here:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback
