### ISSUE TITLE
Planning for Minimal APIs in .NET 7

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#36770]
Super early list of potential areas to investigate in .NET 7:

- More OpenAPI
  - describe schemas, either from binders or metadata
  - query/header/path params
  - more automatic descriptions (less need to use manual metadata)
  - easier authn/z configuration with Swagger UI light-up
- More inferred parameter binding
  - Form & File binding
  - etc.
- Extensible parameter binding
- Extensible Result processing, e.g. delayed execution, shortcutting
- Validation
- Hot Reload, e.g. top-level statements, modifying route mappings, DI, etc.
- Composition, e.g.
  - Route grouping
  - Route handler filters
- 3rd-party extensibility
  - nSwag
  - OData
  - Microsoft....ApiVersioning
- Developer experience
  - Route debugging tool/features
  - Analyzers
  - API versioning
- Trimming and AoT
- Performance
- Problem Details everything
  - DeveloperExceptionPage
  - Middleware/ExceptionHandler
  - Something else?
- Anti-forgery support (XSRF), e.g. via a middleware
- Teach MVC to do more stuff like Minimal APIs, e.g. auto service resolution
- Expanding the minimalistic philosophy to other areas of ASP.NET Core
  - CORS
  - Authn/z
  - gRPC, SignalR, Orleans
- Razor support (e.g. `Results.Page()`)
-

**Comment by shaggygi** [comment]
Bedrock? Just curious.

**Comment by loic-sharma** [comment]
> Expanding the minimalistic philosophy to other areas of ASP.NET Core

Would introducing minimal APIs for generic hosts and [worker services](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers) make sense?

**Comment by gulshan** [comment]
Please keep asp.net core 7 runnable on .net 6 LTS runtime.

**Comment by DamianEdwards** [comment]
Closing this issue as many of these are done or tracked by other issues now.
