### ISSUE TITLE
Component script not being copied to _content folder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Component-script-not-being-copied-to-_co/1521632)._

---
Required JavaScript files are not copied to the _content folder for Blazor WASM applications when debugging.  Included are 3 screenshots: 2 for VS 2022 preview showing the error message and the missing file in the _content folder; 1 VS 2019 screenshot showing the correct number of folders in _content.  This is the same code compiled and debugged for both VS versions

---
#### Feedback Bot on 9/5/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Could you provide more info about your environment. What version of dotnet you are using as well as a minimal repro project in the form of a publicly accessible github repository that demonstrates the issue.
