### ISSUE TITLE
Chrome (93) Disconnect SignalR Connection Exactly After 5 Minutes 

### ISSUE THREAD

**Issue by n1developer-ubt** [dotnet/aspnetcore#36801]
I have seen that this bug is already fixed in new updates but unfortunately I still have this issue, the chrome browser disconnects the SignalR connection exactly after 5 minutes, it does not matter if the tab is active or not, the connection will be closed exactly after 5 minutes. The error I get on the client-side (Browser console is: Error: **Websocket closed with status code: 1006**)
SignalR Javascript Client Version: 5.0.10
ASP.NET Core: .NET5

**Comment by halter73** [comment]
> I have seen that this bug is already fixed in new updates but unfortunately I still have this issue,

We think you might be referring to a timer throttling issue that doesn't appear to be related to an ungraceful websocket close. Is there any firewall/proxy/load-balancer/... between the server and client?

Can you enable (preferably trace-level) [SignalR Core Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0) on the [client](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0#javascript-client-logging) and [server](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0#server-side-logging) and provide the logs from when the issue occurs?

**Comment by n1developer-ubt** [comment]
Yes, That's true, I deployed the application on the Kubernetes engine with LoadBalanacer and Ingress, is there any special configuration for SignalR on Kubernetes?

**Comment by BrennanConroy** [comment]
What Ingress controller are you using? You might need to configure it for websockets so it doesn't close them after 5 minutes.

**Comment by n1developer-ubt** [comment]
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: ingress
   annotations:
      networking.gke.io/managed-certificates: kakoa-cert
      kubernetes.io/ingress.class: "gce"
spec:
   rules:
      - host: ********
        http:
           paths:
              - path: /*
                backend:
                   serviceName: web-app-service
                   servicePort: 80

Here is the YAML file that I use for ingress.

**Comment by adityamandaleeka** [comment]
Triage: this is likely an issue with how the ingress controller is configured.

If you could collect the logs that @halter73 mentioned above, they'll likely show that the connection was terminated unexpectedly on the server side, which would give us further evidence of this.

**Comment by n1developer-ubt** [comment]
The issue was in the ingress controller and is now fixed! Thankyou.
