### ISSUE TITLE
Explore removing inline module script for Blazor Wasm

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#36805]
https://github.com/dotnet/aspnetcore/blob/57501251222b199597b9ac16888f362a69eb13c1/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L201-L215

**Comment by guardrex** [comment]
Side-note for docs tracking: I'm going to let this PU issue track the work and not keep a docs repo issue on this given that it's an *IF/WHEN* scenario at this time.

**Comment by TanayParikh** [comment]
Assigning to @pavelsavara as https://github.com/dotnet/aspnetcore/pull/38721 resolves this issue.

**Comment by pavelsavara** [comment]
We will use dynamic `import` instead of , but we will not remove it completely.
We will replace it with `<link rel="modulepreload" ... ` to implement integrity check for chromium.
[See](https://stackoverflow.com/questions/45804660/is-it-possible-to-use-subresource-integrity-with-es6-module-imports/63029759#63029759)

**Comment by TanayParikh** [comment]
Hmm, would that still fix this issue though as there's no inline script?

https://github.com/dotnet/aspnetcore/pull/38721/files#diff-a5167572a221c4bbe4fa36e4e110b39011b6e8f547ce0ab8bdd204f55201f1c0L211-R229

Essentially, does the app run without errors with the following tag within the `<head>` section of the `wwwroot/index.html` host page?

```html
<meta http-equiv="Content-Security-Policy" 
      content="base-uri 'self';
               block-all-mixed-content;
               default-src 'self';
               img-src data: https:;
               object-src 'none';
               script-src 'self' 
                          'unsafe-eval';
               style-src 'self';
               upgrade-insecure-requests;">
```

**Comment by pavelsavara** [comment]
Seems fine
![image](https://user-images.githubusercontent.com/271576/148927803-04bcffc5-4a90-4a83-8820-707ce0203a4a.png)

**Comment by pavelsavara** [comment]
Maybe I don't fully follow what is the issue/goal here. Could you please elaborate @TanayParikh ?

**Comment by guardrex** [comment]
@TanayParikh ... There's no repo issue here for the 7.0 Roadmap (yet), and it's not clear if this will make that roadmap when that issue is created. Don't we need a tracking issue on the docs side so that we don't forget to document this for 7.0? Note that we don't have the ability to pre-document 7.0 yet ... the ability to version content in docs for 7.0 will happen mid-year ... but we can have the issue on HOLD on the Blazor.Docs project so that we don't miss this when the time comes.

**Comment by TanayParikh** [comment]
> what is the issue/goal here. Could you please elaborate @TanayParikh ?

Discussed with @pavelsavara offline. The issue here was we had an inline JS which is not permitted with the default CSP policy:

https://github.com/dotnet/aspnetcore/blob/57501251222b199597b9ac16888f362a69eb13c1/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L212

To allow this script without triggering CSP errors we added the script's hash to the CSP:

https://github.com/dotnet/AspNetCore.Docs/pull/23365/files#diff-af9b6f8b5de38b13f29e909fd265e200641be05e82021bb432cff343b7dacd76R91


With @pavelsavara's changes here:
https://github.com/dotnet/aspnetcore/pull/38721/files#diff-a5167572a221c4bbe4fa36e4e110b39011b6e8f547ce0ab8bdd204f55201f1c0L211-R223

we no longer have the inline JS script, hence we also no longer need the script hash we added to the CSP. 


Thanks for pointing that out @guardrex, I've created https://github.com/dotnet/AspNetCore.Docs/issues/24570 to ensure we update the docs accordingly for .NET 7

**Comment by damienbod** [comment]
@TanayParikh This is cool, when will this be released?

Is there a way to add a CSP nonce to all the Blazor js scripts? It is easy to add this if the Blazor js script is added in the index/host file, but if the script is created dynamically then I don't see how this can be added. 

Greetings Damien

**Comment by TanayParikh** [comment]
> This is cool, when will this be released?

This'll be a part of .NET 7.

> Is there a way to add a CSP nonce to all the Blazor js scripts after this change?

The purpose of this change is specifically to facilitate removing the inline JS script hash from the Blazor WASM CSP.

I think you may be interested in https://github.com/dotnet/aspnetcore/issues/6001 for your use case. Feel free to leave a thumbs up and/or a comment in that issue with your details 😄
