### ISSUE TITLE
Access violation in cleaning up transport in connection_impl::stop_connection()

### ISSUE THREAD

**Issue by BhavanaMSFT** [dotnet/aspnetcore#36808]
Opening this tracking item as an ongoing investigation. Please feel free to close this if the outcome of the investigation suggests that the issue can be mitigated without changing signalr code.

The websocket_client->stop() finds itself accessing dead memory and crashes. The crash seems to stem from setting the connection_impl's m_transport to nullptr in connection_impl::stop_connection() method.

        websocket_client->stop([logger, callback, close_callback](std::exception_ptr exception)
            {
                try
                {
                    close_callback(exception);
                    if (exception != nullptr)
                    {
                        std::rethrow_exception(exception);
                    }
                    callback(nullptr); // Crashes here

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/SignalR-Client-Cpp/pull/73
