### ISSUE TITLE
parallel.For in blazor 

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#36804]
Is blazor single threaded and can it use parallel.For?
And if blazor is single threaded, can we get multi-threaded support, in .net 6/7

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

Blazor webassembly is single threaded as threads are not supported in all browsers wasm runtimes. We have a tracking issue for it already [here](https://github.com/dotnet/aspnetcore/issues/17730)
