### ISSUE TITLE
Blazor, methods not called after moving to another page, no errors in console also 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#36811]
I have a custom Popup component, which I call like this: 
```
<Popup @ref="popupRef" Buttons="buttons">
content
</Popup>
```
and I set the buttons in the constructor like this: 
```
public Index()
{
	buttons = new List<PopupButton> {
		new PopupButton {
			Content = "OK",
			Primary = true,
			Click = async () =>
			{
				Message = "clicked OK";
				await popupRef.Close();
		}},
		new PopupButton {
			Content = "Cancel",
			Click = async () =>
			{
				Message = "clicked Cancel";
				await popupRef.Close();
			}}
	};
}
```
if I open the popup and after move to another page ( i.e. from https://localhost:44356/ to https://localhost:44356/todo )
the popup will remain open, but If I click the buttons they won't do anything anymore because we're on a different page which doesn't have `popupRef` and `Message` I presume, at the same time I'm not getting any errors also.

I'm not doing anything specific, just testing the popup now, so for now my current solution is to add this in the popup component: 
```
    protected override void OnInitialized()
    {
        NavigationManager.LocationChanged += LocationChanged;
        base.OnInitialized();
    }

    void LocationChanged(object sender, LocationChangedEventArgs e)
    {
        Close();
    }
```
using  .net core 3.1

**Comment by omuleanu** [comment]
when I was opening the popup I would move the popup div just before `</body>` (js interop), without this move it actually disappears on its own when going to another page

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The behavior you're observing is due to your code modifying the DOM. You can learn more about this from https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-libraries-that-render-ui-1
