### ISSUE TITLE
404 when running blazorwasm -ho not in Development

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#36814]
Ran into this while investigating https://github.com/dotnet/aspnetcore/issues/36812

Repro steps (using `6.0.100-rc.2.21471.6` [C:\Program Files\dotnet\sdk]):

```
dotnet new blazorwasm -ho
```

- edit launchsettings to change ASPNETCORE_ENVIRONMENT to Staging, or otherwise change hosting environment to not development)
- Hit the server and see a 404
- Things work fine in development

I verified that doing this against `dotnet new mvc` works fine and loads in production

**Comment by pranavkm** [comment]
That's probably because the StaticWebAssets middleware is not configured in non-Dev environments. You're expected to configure it manually using `UseStaticWebAssets()` or publish the app.

**Comment by HaoK** [comment]
Ok cool, so this is expected
