### ISSUE TITLE
BlazorWasm IdentityServer fetch rejects clients in Production

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#36812]
Found via https://github.com/aspnet/AspNetCore-ManualTests/issues/913

Simplified repro:

```
dotnet new blazorwasm -ho --auth Individual
set ASPNETCORE_ENVIRONMENT=Staging
dotnet run --no-launch-profile
```

Go to fetch (expect redirect to login, instead get 500/error with the following server error:

```
info: Duende.IdentityServer.Events.DefaultEventService[0]
      {
        "ClientId": "wasm.Client",
        "Endpoint": "Authorize",
        "Scopes": "",
        "Error": "unauthorized_client",
        "ErrorDescription": "Unknown client or client not enabled",
        "Category": "Token",
        "Name": "Token Issued Failure",
        "EventType": "Failure",
        "Id": 2001,
        "ActivityId": "0HMBT678IK5QL:00000003",
        "TimeStamp": "2021-09-21T18:58:37Z",
        "ProcessId": 22268,
        "LocalIpAddress": "::1:5001",
        "RemoteIpAddress": "::1"
      }
```

@javiercn is this also potentially related to the customization of identity server not being what we expect anymore?

I did verify that things look fine in the startup of the app, i.e.:

```
var clients = app.Services.GetRequiredService<IEnumerable<Client>>();
var store = app.Services.GetRequiredService<IClientStore>();
var client = await store.FindEnabledClientByIdAsync(clients.First().ClientId);
```

The client is found in the options etc, this is the code that requestvalidator is failing on, so not sure what's going on

**Comment by javiercn** [comment]
@HaoK it can be.

It doesn't explain why we don't see this on a regular published app though. 

Looking at the code, we don't do anything with `IClientStore`

**Comment by HaoK** [comment]
Okay I think this might have been a redherring where my browser was caching the incorrect client page due to reusing ports or something so it was sending the wrong wasm.Client id, instead of the wasmIIS.Client id, so the error was correct, closing this bug as its different from the IIS issue
