### ISSUE TITLE
Razor VSCode `?` commit char conflicts with `??` Null Coalescing Operator

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#36821]
I was trying to write `??` but after the first `?`, it interpreted the second `?` as a completion commit char, yielding `?{COMPLETION_ITEM}?`

O# in a C# file seems to exclude `?` from being a completion trigger char, perhaps razor may want to do the same?

https://user-images.githubusercontent.com/14852843/134252469-93a5f96c-9740-4b05-bf16-e75c153c28d3.mov

**Comment by TanayParikh** [comment]
> O# in a C# file seems to exclude `?` from being a completion trigger char, perhaps razor may want to do the same?

https://github.com/dotnet/aspnetcore-tooling/blob/ddaa8903e03538fbffcda72169c29df1e18cf74f/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs#L25

Hmm looks like it's already excluded.

**Comment by NTaylorMullen** [comment]
@TanayParikh looks like this is an O# roslyn thing. They shoiuld not be providing a `?` commit character at that location. Would you mind moving?
