### ISSUE TITLE
After migrating to .NET 6 RC 1 No service for type Microsoft.Extensions.Configuration.IConfiguration can be found

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#36829]
In my `IServiceCollection` extension I have this code.

```c#
var serviceProvider = services.BuildServiceProvider();
var configuration = serviceProvider.GetRequiredService<IConfiguration>();
```

This breaks ofter migrating to .NET 6 using the `Program.cs` only and no `Startup` class.
Do I need to register this in my extension as well? How can I make this work for .NET 5 and .NET 6?

**Comment by davidfowl** [comment]
Why is extension method building the `IServiceProvider`?

**Comment by marcuslindblom** [comment]
@davidfowl In .NET 5, I thought I needed to?

**Comment by marcuslindblom** [comment]
So to be clear, this extension method is in a library I use both in .NET 5 and 6

**Comment by davidfowl** [comment]
Typically extension methods on IServiceCollection that need `IConfiguration` take in the user provided configuration via an argument. Building the service provider, builds a temporary throw away service provider and can results in a couple of problems:
- Multiple singleton instances
- Not disposing `IDisposable` services resolved when trying to resolve services from this temporary container.

Calling `BuildServiceProvider` is an anti-pattern because of those things. 

That said, in this particular case of resolving `IConfiguration`, the side effects are usually fine since the host usually resolves the same singleton instance.

**Comment by marcuslindblom** [comment]
Ok, so it's ok to do this but it's an anti-pattern, right?

This is how I use the configuration and the arguments. From a best practice stand point, is it possible to make this code compliant with both .NET 5 and 6?

```c#
public static IServiceCollection AddStrife(this IServiceCollection services, Action<DocumentStoreOptions> configureOptions) {

    var serviceProvider = services.BuildServiceProvider();
    var configuration = serviceProvider.GetRequiredService<IConfiguration>();
    services.Configure<DocumentStoreOptions>(options => options.Settings = configuration.GetSection(nameof(DocumentStoreSettings))?.Get<DocumentStoreSettings>()).Configure(configureOptions)

    return services;
}
```

**Comment by davidfowl** [comment]
Like so.

```C#
public static IServiceCollection AddStrife(this IServiceCollection services, Action<DocumentStoreOptions> configureOptions)
{
    services.AddOptions<DocumentStoreOptions>()
            .Configure<IConfiguration>((options, configuration) =>
            {
                options.Settings = configuration.GetSection(nameof(DocumentStoreSettings))?.Get<DocumentStoreSettings>();
            })
            .Configure(configureOptions);

    return services;
}
```

cc @IEvangelist we have a doc for guidance on how to build these sorts of libraries now right?

**Comment by marcuslindblom** [comment]
> Like so.
> 
> ```cs
> public static IServiceCollection AddStrife(this IServiceCollection services, Action<DocumentStoreOptions> configureOptions)
> {
>     services.AddOptions<DocumentStoreOptions>()
>             .Configure<IConfiguration>((options, configuration) =>
>             {
>                 options.Settings = configuration.GetSection(nameof(DocumentStoreSettings))?.Get<DocumentStoreSettings>();
>             })
>             .Configure(configureOptions);
> 
>     return services;
> }
> ```
> 
> cc @IEvangelist we have a doc for guidance on how to build these sorts of libraries now right?

Ok, thanks. Changed my configuration to your proposed solution.

**Comment by davidfowl** [comment]
No problem. I'm gonna fix this anyway since it's a compatibility break.

**Comment by IEvangelist** [comment]
> Like so.
> 
> ```cs
> public static IServiceCollection AddStrife(this IServiceCollection services, Action<DocumentStoreOptions> configureOptions)
> {
>     services.AddOptions<DocumentStoreOptions>()
>             .Configure<IConfiguration>((options, configuration) =>
>             {
>                 options.Settings = configuration.GetSection(nameof(DocumentStoreSettings))?.Get<DocumentStoreSettings>();
>             })
>             .Configure(configureOptions);
> 
>     return services;
> }
> ```
> 
> cc @IEvangelist we have a doc for guidance on how to build these sorts of libraries now right?

Yes sir, here you are @davidfowl

[Options pattern guidance for .NET library authors](https://docs.microsoft.com/dotnet/core/extensions/options-library-authors)
