### ISSUE TITLE
Check your `.csproj` file. I had the exact same problem, when I had the following in my `.csproj`:

### ISSUE THREAD

**Issue by MojtabaAzarani** [dotnet/aspnetcore#36837]
Check your `.csproj` file. I had the exact same problem, when I had the following in my `.csproj`:

```xml
  <ItemGroup>
    <Content Remove="Pages\SomeOtherPage.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\SomeOtherPage.razor" />
  </ItemGroup>
```

This somehow got in there when I added the page (I create Razor pages as Text fioles and rename them because the "New Razor Page" still creates old cshtmls).

When I removed these lines, the page started to work.

_Originally posted by @rabejens in https://github.com/dotnet/aspnetcore/issues/20786#issuecomment-629067938_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
