### ISSUE TITLE
Results.Problem does not support configuring Extensions

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#36848]
The `ProblemDetails` class defines an `Extensions` property that allows the user to configure the `ProblemDetails` object with additional metadata.

The `Results.Problem` extension method does not accept an `extensions` parameter for setting this leaving the user with no options to return a `ProblemDetails` with a custom `Extensions`.

Note: this change will require an API change.

https://github.com/dotnet/aspnetcore/blob/f7dc5e24af7f9692a1db66741954b90b42d84c3a/src/Http/Http.Results/src/Results.cs#L475-L495

**Comment by davidfowl** [comment]
@captainsafia this is fixed right?

**Comment by captainsafia** [comment]
Yep -- the fix was merged to RC2 today. Keeping this open to validate in published bits.

**Comment by captainsafia** [comment]
Validated in 6.0.100-rc.2.21477.4.
