### ISSUE TITLE
Hot Reload is not working at in Blazor wasm hosted app

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#36851]
I am using .NET 6 RC1 and VS2022 Preview 4. I start the app with CTL + F5(Start without Debugging) and than make change to one of the .razor pages <h3> title</h3> and save it, nothing happens. I even tried clicking the hot reload (red circle button) to see if that would apply the changes but even that does not do anything.
Are there any more setting to be done elsewhere ?

![image](https://user-images.githubusercontent.com/3267605/134405241-316fb185-bf2d-487f-abfb-9cbcab1f88c8.png)

![image](https://user-images.githubusercontent.com/3267605/134405399-ed583ec5-c461-41d6-8617-0af25ea5ea72.png)

![image](https://user-images.githubusercontent.com/3267605/134405464-478c873d-66ef-4ca4-a8fd-793f41a63cf1.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which we've released a fix for already. Please update to the latest VS 17 Preview 4.1 patch to get the fix.

**Comment by nssidhu** [comment]
Downloaded and tried that, still same issue.
