### ISSUE TITLE
ANCM restarts on any applicationHost.config change

### ISSUE THREAD

**Issue by npeeples** [dotnet/aspnetcore#36870]
It's stated in #8775 and #4808 that by design the aspnetcore module will restart if applicationHost.config changes. In a couple other places, there's strong suggestion that blue/green be used to deploy apps and avoid this. But if you are running blue/green ARR/webfarms on the same machine as the application (2 websites, 1 server farm) it's impossible to achieve this goal. The minute you disable the live server (which writes appHost.config) after draining it, the staged, warm server restarts.

I did attempt to set a server as unhealthy/unavailable, and not disable the server. That doesn't write anything to appHost, which is helpful. But this configuration doesn't survive a restart of the DefaultAppPool, which is setup to recycle every 30-ish hours (and in my case I have other apps running there).

AppPools already have a way to disable recycle on config changes. Is this something that can be borrowed?

If this isn't an option, is there anyway to achieve 0-downtime blue/green deployments on the same machine with IIS that I'm missing?

**Comment by adityamandaleeka** [comment]
Triage: we could investigate whether this is a class of config change that we choose not to restart on.

**Comment by BrennanConroy** [comment]
Seems like this was done in https://github.com/dotnet/aspnetcore/pull/37474?
