### ISSUE TITLE
Database error page fails when multiple DbContext types and some types can't be initialized

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/aspnetcore#36877]
Originally filed by @slavanap at https://github.com/dotnet/efcore/issues/22341#issuecomment-914812831

I investigated this and talked to @bricelam. It seems a pretty corner case, so I'm not sure it's worth doing anything. If we did want to support it, then we could capture errors but not fail immediately, and then only fail later if we haven't found a working context type.

----

Original issue:

Demo project files are listed at the bottom. When `HomeController.Index` method run into exception with ContextGood unable to connect to 0.0.0.0 and this exception is propagated, please notice the message in the logs:
```
fail: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseDeveloperPageExceptionFilter[7]
      An exception occurred while calculating the database error page content. Skipping display of the database error page.
      System.Exception: ContextBad is never used, although registered in DI. So this code should never hit
```

This message is unexpected because ContextBad hasn't been queried elsewhere.

Project.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication1 {

    public class ContextGood : DbContext {
        public DbSet<Post> Posts { get; set; }
        public ContextGood(DbContextOptions<ContextGood> options) : base(options) { }
    }

    public class ContextBad : DbContext {
        public DbSet<Post> Posts { get; set; }

        public ContextBad(DbContextOptions<ContextBad> options) : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            throw new Exception("ContextBad is never used, although registered in DI. So this code should never hit");
        }
    }

    public class Post {
        public int Id { get; set; }
        public string Title { get; set; }
    }


    class Startup {
        
        static void Main(string[] args) =>
            CreateHostBuilder(args).Build().Run();

        static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => {
                    webBuilder.UseStartup<Startup>();
                });


        public void ConfigureServices(IServiceCollection services) {
            services.AddDatabaseDeveloperPageExceptionFilter();
            services.AddControllers();
            services.AddDbContext<ContextBad>(opts => opts.UseInMemoryDatabase("test1"));
            services.AddDbContext<ContextGood>(opts => opts.UseNpgsql("server=0.0.0.0"));
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            if (env.IsDevelopment())
                app.UseDeveloperExceptionPage();

            app.UseRouting();
            app.UseEndpoints(endpoints => {
                endpoints.MapDefaultControllerRoute();
            });
        }
    }

    public class HomeController: Controller {
        readonly ContextGood _good;

        public HomeController(ContextGood good) {
            _good = good;
        }

        public IActionResult Index() {
            _good.Posts.Find(1);
            return Ok("test");
        }
    }

}
```

launchSettings.json
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:51923",
      "sslPort": 44378
    }
  },
  "profiles": {
    "WebApplication1": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by BrennanConroy** [comment]
Triage: This is an edge-case that we're not going to do anything about unless we see more feedback. Marking for closure.

**Comment by slavanap** [comment]
@BrennanConroy what do you mean "an edge-case".
`app.UseDeveloperExceptionPage()` is purposed for **development**.

At somewhat big projects development process in my experience it's very likely to run into described situation, which makes me remove totally this package from my projects in order to get away from noise connections it triggers.

So could you please elaborate on your triage arguments and provide at least a workaround (without unregistering any of DbContexts from DI)?

Thanks.

**Comment by ajcvickers** [comment]
@slavanap It's an edge case because you have multiple context types, one of which throws when it is initialized. The workaround is to ensure that your context types don't throw when initialized.

**Comment by slavanap** [comment]
@ajcvickers it may also through on connection. I know I can hook into execution strategy to handle the exception, but *how can I cancel the connection to ContextBad and see valuable debug information for the context, connection to which had succeeded, and not just exception stack trace?*

**Comment by ajcvickers** [comment]
@slavanap We don't try to connect with that context type, only build the model. You're making it throw when building the model.

**Comment by slavanap** [comment]
@ajcvickers 
The same behavior would be if connection to ContextBad would fail, not exception thrown. It seems I need to rewrite the sample to point that out, but that should not be mixed up with ContextGood failure to connect.

In my original message I've pointed that out https://github.com/dotnet/efcore/issues/22341#issuecomment-913560424

In short, if ContextGood is only used within handling aspnet method, and it runs into any DB exception, then connection to all other unused DB contexts will be triggered in UseDeveloperExceptionPage middleware, and if a connection to any of them runs into an exception, then purpose of UseDeveloperExceptionPage is lost because only original stack trace is shown.

It may also be caused by incorrect implementation of EF providers. In one of my projects I run into issues of debugging case when ContextGood is Oracle, and ContextBad is MySQL. When DB exception had triggered in Oracle provider then connection to MySQL was initiated because of UseDeveloperExceptionPage middleware.

**Comment by ajcvickers** [comment]
@slavanap I think it's worth taking a step back here and considering why the database error page exists. The motivation for this page is that when people are getting started with ASP.NET Core, they may not know that the database needs to be created. The error page is designed to provide feedback to these people. Once you get to the point of multiple different DbContext types all registered in the same service provider but connecting to different databases via different providers, then I think you are far beyond the scope of what was intended here. At that point, you hopefully have much more robust and maintainable process for managing your databases and migrations such that the database error page is no longer needed. If not, then I would suggest you move in that direction, rather than continuing to rely on a crutch designed to help people get started.

**Comment by slavanap** [comment]
@ajcvickers If that's the purpose of the package, then it would be good to have such description in the Nuget package description. I usually look to use whatever tools available to collect all feedback possible on the code I write, including static analyzers, nullability feature, various error pages with hints, DbContext sensitive information dump for development and so on. If the aforementioned description is the goal of the package then I agree with you that although I like all those toolsets, it's not helpful for me anymore.

Feel free to close the ticket if you don't see any actionables here.
