### ISSUE TITLE
Single sign on with Kerberos does not work on Firefox

### ISSUE THREAD

**Issue by lbalusek** [dotnet/aspnetcore#36878]
Hello,

We have ASP.NET Core Web API - its just example weather app from VS templates, running on CentOS 7 added to Windows domain and configured according to [these instructions](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#kestrel), so we are using Kerberos. 
Everything works great on chromium based browsers, when i go to the website(for now, we are using just http, not https), i am prompted to enter my credentials and after i provide them i see some weather report.
But for some reason, this does not work on **Firefox**, there is **no credentials prompt**, it just returns 401 - Unauthorized.

Startup class:
```csharp
public class Startup
{
      public Startup(IConfiguration configuration)
      {
          Configuration = configuration;
      }

      public IConfiguration Configuration { get; }

      // This method gets called by the runtime. Use this method to add services to the container.
      public void ConfigureServices(IServiceCollection services)
      {
          services.AddControllers();
          services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();
      }

      // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
      public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
      {
          if (env.IsDevelopment())
          {
              app.UseDeveloperExceptionPage();
          }

          app.UseRouting();

          app.UseAuthentication();
          app.UseAuthorization();

          app.UseEndpoints(endpoints =>
          {
              endpoints.MapControllers();
          });
      }
}
```

Program class:
```csharp
public class Program
{
      public static void Main(string[] args)
      {
          CreateHostBuilder(args).Build().Run();
      }

      public static IHostBuilder CreateHostBuilder(string[] args) =>
          Host.CreateDefaultBuilder(args)
              .ConfigureWebHostDefaults(webBuilder =>
              {
                  webBuilder.UseStartup<Startup>();
                  webBuilder.UseUrls("http://0.0.0.0:5000");
              });
}
```

Do you have any ideas, what we are doing wrong? 
Thank you.

**Comment by blowdart** [comment]
As you said it works in Chrome, it seems like Firefox is being fussy.

Could you try the "NTLM" instructions they give [here](https://support.mozilla.org/en-US/kb/Firefox%20asks%20for%20user%20name%20and%20password%20on%20internal%20sites)? I know it says NTLM, but I'm hoping that just adding the site to the equivalent of their intranet zone might kick it off.

**Comment by lbalusek** [comment]
Yes, but i was hoping for server side solution, so i wouldn't have to force our users to change settings of their browsers.
With `network.automatic-ntlm-auth.trusted-uris` i have got the same result - `401 Unauthorized`, no credentials prompt.

**Comment by blowdart** [comment]
We can't influence the browser unfortunately - we send the right headers to request it, but Firefox seems to require extra work for it to understand certain sites are ok.
