### ISSUE TITLE
[SDK] Static web assets pack improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#36880]
Pack is the only area we haven't "properly" fixed in 6.0. There are several aspects of it that are "problematic" since V1, that I believe we want to address:
* Multitargeting: We don't attach ourselves to the proper Nuget msbuild targets
  * Currently we attach to TargetsForTfmSpecificContentInPackage as described [here](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-scenarios)
  * This is problematic because we run our targets multiple times and can produce different results, leading to errors.
  * We need to identify the right target to attach to that ensures we only run once.

**Comment by SteveSandersonMS** [comment]
@javiercn Please split into two issues and make sure we re-triage the "compile-time assets" one in time for 6.0.

**Comment by mkArtakMSFT** [comment]
Moving to 7.0 planning. The ask you had @SteveSandersonMS is something @javiercn says has already in flight.

**Comment by javiercn** [comment]
https://github.com/dotnet/maui/issues/2955

**Comment by javiercn** [comment]
https://github.com/dotnet/sdk/pull/25011
