### ISSUE TITLE
Treating IHostEnvironment.ApplicationName as an assembly name for some reason?

### ISSUE THREAD

**Issue by AgentFire** [dotnet/aspnetcore#36883]
https://github.com/dotnet/aspnetcore/blob/24dacc25357988dbe699e72580a8ea569a33b4c4/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L85

That's quite bold to assume, that is.

I'm using `ApplicationName` as, you know, an application's real name, and VS-projects (aka assemblies in the end) can (and most certainly will) have different names.

The issue that I'm having is one assembly is responsible for creation of WebHost, and the other contains various Controllers. And `IHostEnvironmend.ApplicationName` is completely another thing.

Not only that particular line hopes for some actual assembly name located in a property which isn't called **AssemblyName**, I noticed that WebHost actually **changes** IHostEnvironment's ApplicationName into something other than what's already placed there, which is another unacceptable behaviour. But that would be another issue, I suppose.

**Comment by davidfowl** [comment]
> The issue that I'm having is one assembly is responsible for creation of WebHost, and the other contains various Controllers. And IHostEnvironmend.ApplicationName is completely another thing.

You have 2 options:
1. Manually change the application name to point to where the controllers are.
    ```C#
    webHostBuilder.UseSetting(WebHostDefaults.ApplicationName, typeof(MyController).Assembly.GetName().FullName);
    ```

2. Add an application part in MVC that points to the assembly where your controllers are.
    ```C#
    services.AddControllers().AddApplicationPart(typeof(MyController).Assembly);
    ```

**Comment by AgentFire** [comment]
I thank you all for your answers.

**Comment by AgentFire** [comment]
Both your code examples didn't do anything, the exception is still being thrown about how the MVC framework couldn't load an assembly, which name it has read from `ApplicationName` storage.

My workaround, which did work:

```cs
var vhe = services.Where(T => typeof(IWebHostEnvironment).IsAssignableFrom(T.ServiceType)).Single().ImplementationInstance as IWebHostEnvironment;
string? appName = null;

if (vhe is not null)
{
    appName = vhe.ApplicationName;
    vhe.ApplicationName = Assembly.GetEntryAssembly()!.GetName().Name;
}

services
    .AddControllers() // This line reads directly from IServiceCollection->IWebHostEnvironment, I so change that for this line.
    .AddControllersAsServices();

if (vhe is not null)
{
    vhe.ApplicationName = appName;
}
```

**Comment by davidfowl** [comment]
I didn't see anything about an exception in your original issue. Can you provide a repro? I'm not sure how it could throw other someone setting a non-assembly as the application name.

**Comment by AgentFire** [comment]
@davidfowl [There](https://github.com/AgentFire/web-host-exception-repro) you go.

**Comment by davidfowl** [comment]
So this is the problem https://github.com/AgentFire/web-host-exception-repro/blob/02e4627f5c6ca8f7f7339b4181293646aac0db9a/Web%20Host%20Repro/Program.cs#L26. Don't do this.

**Comment by AgentFire** [comment]
I know. But the `ApplicationName` property shouldn't be that brazenly captured by some "another service" of the Host. This is the Hosts's property, the Host sets, controls and maintains it.

Many other components of my application use this very property. Metrics, health checks, logs, you name it. it was designed specifically for the purpose of carrying the name of the entire application, not some internal assembly.

So, "Don't do this" doesn't really apply here as a solution, except may be for me "not to get that exception". But not for the MVC framework.

I understand that you think likewise, yet unable to fix it due to some reasons. Well, that's okay. I have my workaround, and you have your project; I've merely shown you the issue and it's up to you to disregard it.

**Comment by davidfowl** [comment]
Got it. Other parts of the stack will break but I guess you can workaround it when you hit those scenarios.
