### ISSUE TITLE
Flaky test - RouteTableFactoryTests.CanCacheRouteTable

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#36888]
## Failing Test(s)

- Microsoft.AspNetCore.Components.Routing.RouteTableFactoryTests.CanCacheRouteTable

## Error Message

```text
Assert.Same() Failure
Expected: RouteTable { Routes = [RouteEntry { ... }, RouteEntry { ... }, RouteEntry { ... }, RouteEntry { ... }] }
Actual:   RouteTable { Routes = [RouteEntry { ... }, RouteEntry { ... }, RouteEntry { ... }, RouteEntry { ... }] }
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.Routing.RouteTableFactoryTests.CanCacheRouteTable() in /_/src/Components/Components/test/Routing/RouteTableFactoryTests.cs:line 24
```
</details>

## Logs

None.

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1377733&view=ms.vss-test-web.build-test-results-tab&runId=40173528&resultId=102307&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Looks like it's a static class with static properties, that doesn't make for good testing since anything else in the process might also touch it and affect the test.

**Comment by adityamandaleeka** [comment]
This happened again [today](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348247&view=results). Looks like we didn't actually do anything to fix it. See @BrennanConroy's suggestion here: https://github.com/dotnet/aspnetcore/pull/37931#issuecomment-955025257

**Comment by javiercn** [comment]
Addressed by https://github.com/dotnet/aspnetcore/pull/49680
