### ISSUE TITLE
Consider to add more details to message about linking

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/aspnetcore#36903]
Blazor app prints message about linking when run in Debug configuration. I think the second part of the message might be a bit more specific and explain that the published app will be linked and thus be smaller.

Example of the current message:
`blazor.webassembly.js:1 blazor Loaded 8.86 MB resources   This application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.`

**Comment by mkArtakMSFT** [comment]
Closing this, as we haven't heard this being a concern for others.
