### ISSUE TITLE
Existing hot reload deltas aren't applied until after the application starts

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#36913]
I'm sure this is known and by design, but it warrants a bit more discussion to be sure this is absolutely what we want and whether this is something we might enhance either before or after 6.0 ships.

With Blazor WebAssembly, you can make some changes that get hot reloaded, and things are good. But when you reload the page in the browser, a quirky thing happens: first you see a stale version of your application *without* the change, then a second later it renders again with the change.

In many cases this is purely cosmetic and people could live with it. But in other cases, the old logic might be functionally wrong and could put the application in an invalid state, so you have no choice but to go back and restart the application (which in turn is a nonobvious process if you're unfamiliar with the tooling).

### Repro

If you put some new logic into an `OnInitializedAsync` lifecycle method, it won't run during the first hot reload. This is expected. But when you reload the page, you probably **do** expect it to run (since the application is reinitializing), but it won't run because the delta isn't applied until after the application is already started.

I changed the default `FetchData.razor` to have the title `<h1>Updated</h1>`, and added:

```cs
    protected override async Task OnInitializedAsync()
    {
        Console.WriteLine("This is new code");
        // ... existing code goes here
    }
```

Notice that when reloading the browser, the old title `<h1>Weather forecast</h1>` appears first, and the log message never appears:

![reload-stale](https://user-images.githubusercontent.com/1101362/134656730-90f29c67-dd35-4e82-9383-60992cdcf1b9.gif)

If I was changing the URL that it loads the data from, it would continue using the old URL, which would be super confusing.

@pranavkm Questions:

 * Have we already considered and rejected making the WebAssembly runtime delay its startup until it acquires and applies any pending deltas?
 * And if we did so, would it slow down the startup process much, both in the case where there's no delta, or there are some deltas?
 * If it does slow things down, would we consider things like stashing deltas in `sessionStorage` when we receive them the first time so that we can replay them without having to wait to fetch them from the server? I thought we had some discussion in the past about stashing the deltas locally, but don't remember whether we actually intended to do it in the end.

**Comment by pranavkm** [comment]
My intent was to apply these deltas before components began to render, but clearly it didn't and I hadn't followed up on it as yet. Perhaps you could help me figure out what's up:

* The host performs hot-reload initialization prior to components being rendered: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs#L138-L141
* This in turn tries to replay previously applied deltas by calling a JS Interop method: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs#L26-L34
* The interop method reads deltas from the cache or falls back to fetching from the middleware. It completes once deltas have been applied: https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/BrowserRefresh/BlazorHotReload.js

We're waiting the async operation, so I would expect components to be patched before we begin to execute them but clearly it doesn't work that way. Anything immediately jump out to you?

**Comment by SteveSandersonMS** [comment]
The logic looks like it *should* work. It's a bit unusual to use unmarshalled interop for async, but based on what `BINDING.js_to_mono_object` supposedly does, it looks like it should work.

Basically as long as `Blazor._internal.applyHotReload` completes synchronously, I don't know why it wouldn't work. I guess it needs some debugging.
