### ISSUE TITLE
SignalR can not get user identifier from ClaimsPrincipal

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/aspnetcore#36918]
I use ASP.NET 6 RC1 Angular template. 

I try to send message to specific user by user identifier and it doesn't push message to client. 

`await storeHub.Clients.User(userId).SendMessage(message);`

I realized UserIdentifier is null on user's connection and i wanted to set via my custom provider. The weird thing is below provider return null as identifier. 

```
    public class UserIdProvider : IUserIdProvider
    {
        public string GetUserId(HubConnectionContext connection)
        {
            return connection.User.FindFirstValue(ClaimTypes.NameIdentifier); //returns null
        }
    }
```

But the code on controller side is able to find and return identifier as `User.FindFirstValue(ClaimTypes.NameIdentifier)`

Not sure i missed something in here. I need help :(

**Comment by davidfowl** [comment]
What does your setup code look like?

**Comment by YakupIpek** [comment]
I will try it on clean project and link it here

**Comment by YakupIpek** [comment]
This is my program.cs and i set it up OpenId login via AddOpenIdConnect  and i am not sure it is right place to configuration external provider but i see that provider in login page and able to logged in. 
```
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    ContractResolver = new CamelCasePropertyNamesContractResolver()
};

var services = builder.Services;

services.AddRefitClient<INodeApi>()
    .ConfigureHttpClient((service, client) =>
    {
        var setting = service.GetRequiredService<AppSetting>();
        client.BaseAddress = setting.ExplorerApiUrl;
    });


services.AddSingleton(c => builder.Configuration.Get<AppSetting>());

services.AddSingleton<IUserIdProvider, UserIdProvider>();

services.AddScoped<IChainScanner, ChainScanner>();

services.AddHostedService<ChainScannerTask>();

services.AddDbContext<StoreContext>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

services.AddDatabaseDeveloperPageExceptionFilter();

services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<StoreContext>();

services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, StoreContext>();

services.AddAuthentication().AddOpenIdConnect("oidc", "My Identity Server Login", options =>
{
    options.Authority = builder.Configuration["Identity:Authority"];
    options.ClientId = builder.Configuration["Identity:ClientId"];

    options.Scope.Add("profile");

    options.GetClaimsFromUserInfoEndpoint = true;
}).AddIdentityServerJwt();

services.AddControllersWithViews();
services.AddRazorPages();
services.AddSignalR();
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();

app.UseAuthentication();
app.UseIdentityServer();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");
app.MapRazorPages();

app.MapHub<StoreClientHub>("hub/store");

app.MapFallbackToFile("index.html");

app.Run();

```

**Comment by YakupIpek** [comment]
@davidfowl It is enough knowledge for you ? It may difficult for me to provide full repro project.

**Comment by davidfowl** [comment]
I don't see anything obvious from the above configuration. What does the authorize attribute look like in your controllers and your hub?

**Comment by YakupIpek** [comment]
It is default implementation [Authorize] attribute located on my controller and my hub doesn't have any Authorize attribute. Even my hub doesn't have any methods.

**Comment by davidfowl** [comment]
Add the [Authorize] attribute to your hub.

**Comment by YakupIpek** [comment]
Is there an full project example for Angular SPA RC1 + Identity Server + Signalr ?

**Comment by brockallen** [comment]
>             return connection.User.FindFirstValue(ClaimTypes.NameIdentifier); //returns null

Try the "sub" claim and see if that gives you a user id:

             return connection.User.FindFirstValue("sub");

**Comment by YakupIpek** [comment]
@brockallen It is also null. 

One thing is quite weird. When user logged in Open Id Provider (AddOpenIdConnect) the claims obtained from external provider was exist in ClaimsPrincipal User in older version but in this ASP.NET 6 + Identity Server, none of claims exist from external provider in User. I am not sure this is bug or not.

**Comment by brockallen** [comment]
Ok, then not sure. Put a break point in your code and look at the list of claims.

**Comment by BrennanConroy** [comment]
Also have you looked at the docs for using Identity Server and SignalR?
https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#identity-server-jwt-authentication

**Comment by YakupIpek** [comment]
@brockallen 

This is what i see on claims 

![7df612caf50b1769f184666343f108d8](https://user-images.githubusercontent.com/335426/134719934-6052cdc9-4dc6-4ce4-8a55-3b95988b4ff2.png)
4666343f108d8.png

**Comment by YakupIpek** [comment]
I am not sure i really need authorization for hub because only authorized client will be connected and our hub has not any methods so client cant invoke any methods. SignalR push events on server side to client only. 

But i read those docs and implement it. I will update you  @BrennanConroy

**Comment by YakupIpek** [comment]
Now after reading article and providing access token and authorizing fixed the issue. @BrennanConroy 

But do i really need authorization for hub in my use case really ?

**Comment by BrennanConroy** [comment]
Yes, if you want to use Users in a Signalr context: `storeHub.Clients.User(userId)` then you need to have an authenticated SignalR connection.
