### ISSUE TITLE
VS Hot reload "Restart Application" VS gesture behaves badly

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#36914]
There are some cases (with WebAssembly at least) where you have to restart the application to make your code changes really take effect, e.g., #36913. When you're in this situation you'll have to click "Restart Application", but the behavior is suboptimal:

 * Instead of refreshing your existing browser tab(s), it opens a whole new one.
   * It's not even on the URL you were on before, but instead resets back to the root URL.
   * Repeatedly opening tabs quickly clutters things up - you have to keep closing them manually.
 * The existing browser tab(s) are left in an infinite "reloading" state, so you have to manually refresh or close them

@pranavkm My guess is that the "open browser tab" behavior is controlled by VS and will need to be reported there, whereas the "existing tab never finishes reloading" behavior is likely controlled by our injected `.js` files. Is that correct?

![reload-newtab](https://user-images.githubusercontent.com/1101362/134659562-6350d8b1-89cc-4f84-a0d0-d582d9136caa.gif)

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS the VS fix would eliminate that issue completely and there won't be a need to change a thing on our end. Would you mind reporting this through VS Feedback>

**Comment by mkArtakMSFT** [comment]
@BillHiebert  FYI
