### ISSUE TITLE
[Blazor] Include a checkbox for WebAssemblyPrerendered in the New Project Wizard

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#36915]
Changing a WASM app to WebAssemblyPrerendered is not a straightforward process. 

Could we please have a checkbox on the New Project wizard for this?

**Comment by guardrex** [comment]
Side-note on the coverage for it: It just went into the docs for 6.0 ...

* PR: https://github.com/dotnet/AspNetCore.Docs/pull/23364
* Live: https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly

The paint isn't quite dry on that 🚧👷, and we'll review and update it prior to 6.0 GA. Feedback is appreciated. Use the **This page** feedback button and form at the bottom of the topic.

**Comment by SteveSandersonMS** [comment]
@mrpmorris Funny you should raise this today. We just decided during a team standup yesterday to do this.

**Comment by guardrex** [comment]
Will it be for 6.0 GA or a future release?

**Comment by mrpmorris** [comment]
Yay!

**Comment by mkArtakMSFT** [comment]
Closing as the Blazor WebAssembly Hosted template was removed in .NET 8 in favor of the new Blazor Web App template and the option is not applicable any more.
