### ISSUE TITLE
Tag Helper enum attribute produces false IntelliCode CS0103 in a razor page in Visual Studio 2022 Preview 3.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36937]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Tag-Helper-enum-attribute-produces-false/1517895)._

---
[regression] [worked-in:VS 2019]
I have a custom tag helper ("MyTagHelper") with an enum property ("Theme"). It is used in Page1.cshtml as follows:

```
<my theme="Apple"></my>
```

"Apple" is the name of an enum field. This works fine in VS2019. 

In Visual Studio 2022 Preview 3.1, it produces "CS0103	The name 'Apple' does not exist in the current context" at the IntelliCode/IntelliSense level (that is, without actual compilation). When I build the project, it succeeds and works as expected.

Interesting, if I change theme="Apple" to theme="TagHelperEnumAttributeBug.MyTheme.Apple", IntelliCode  does NOT complain; however, the project won't build with "CS0117: 'MyTheme' does not contain a definition for 'TagHelperEnumAttributeBug'"

This looks like a regression to me.

Attached is a sample project that demonstrates the issue.

! [image.png] (https://aka.ms/dc/image?name=B81807e47974b41b599479f5dd96682d5637659925779121003_20210831-174256-image.png&tid=81807e47974b41b599479f5dd96682d5637659925779121003)

---
#### Feedback Bot on 8/31/2021, 02:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Looks like we have two bugs here:
1. The razor design-time build didn't fully qualify the name `Apple` and hence IntelliSense complains
2. The type name and the namespace are swapped in order in the error message: `CS0117: "MyTheme' does not contain a definition for 'TagHelperEnumAttributeBug'"`

**Comment by Eilon** [comment]
Possibly related (or not):
* https://github.com/dotnet/aspnetcore/issues/19139
* https://github.com/dotnet/aspnetcore/issues/12154

**Comment by TanayParikh** [comment]
> Possibly related (or not):
> 
> * [Support simpler syntax for Enum values in Blazor Component attributes #19139](https://github.com/dotnet/aspnetcore/issues/19139)
> * [[Blazor] Simplify passing enum values as attributes #12154](https://github.com/dotnet/aspnetcore/issues/12154)

Thanks @Eilon. I believe the difference here is those issues are for requesting the feature in Blazor Component Attributes, whereas this issue is specifically for a Razor TagHelper.

**Comment by TanayParikh** [comment]
I'm unable to repro this on the latest VS2022 Preview 5.

![image](https://user-images.githubusercontent.com/14852843/135926844-3acf66bc-45de-48c8-a5a4-aef5cabee06a.png)

Could you please upgrade to the latest available VS Preview and see if you're still experiencing this issue. If the issue persists, could you please clarify what version of .NET you're running, and provide a public GitHub repro project to allow us to investigate further?
