### ISSUE TITLE
Signout doesn't redirect to redirect uri specified in authentication properties.

### ISSUE THREAD

**Issue by safern** [dotnet/aspnetcore#36934]
### Describe the bug
While creating a website using OAuth configured as follows:

```cs
builder.Services.AddAuthentication(options =>
    {
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = "GitHub";
    })
    .AddOAuth("GitHub", "GitHub", options =>
    {
        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.ClientId = Configuration["ClientId"];
        options.ClientSecret = Configuration["ClientSecret"];
        options.CallbackPath = new PathString(GithubHttpClient.REDIRECT_ENDOPOINT);
        options.AuthorizationEndpoint = "https://github.com/login/oauth/authorize";
        options.TokenEndpoint = "https://github.com/login/oauth/access_token";
        options.UserInformationEndpoint = "https://api.github.com/user";
        options.ClaimsIssuer = "OAuth2-Github";
        options.SaveTokens = true;
        options.Scope.Add("user");
        options.Scope.Add("repo");

        options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "id");
        options.ClaimActions.MapJsonKey(ClaimTypes.Name, "login");
        options.ClaimActions.MapJsonKey(GithubHttpClient.GITHUB_LOGIN_CLAIM, "login");
        options.ClaimActions.MapJsonKey(GithubHttpClient.GITHUB_NAME_CLAIM, "name");
        options.ClaimActions.MapJsonKey(GithubHttpClient.GITHUB_URL_CLAIM, "html_url");
        options.ClaimActions.MapJsonKey(GithubHttpClient.GITHUB_AVATAR_CLAIM, "avatar_url");

        // Retrieving user information is unique to each provider.
        options.Events = new OAuthEvents
        {
            OnCreatingTicket = async context => { await CreateGitHubAuthTicket(context); }
        };
    })
    .AddCookie();
```

I have a Signout endpoint defined  as follows:

```cs
[HttpGet("~/logout")]
[HttpPost("~/logout")]
public IActionResult SignOutCurrentUser()
{
    return SignOut(new AuthenticationProperties { RedirectUri = "/" },
        CookieAuthenticationDefaults.AuthenticationScheme);
}
```

The logout button is defined as:
```html
<a class="btn btn-lg btn-danger" href="/logout?returnUrl=%2F">Sign out</a>
```

The site successfully signs out after the signout is made, however after the signout is completed, the site is not redirected to `"/"` which is the `RedirectUri`, I specified on the `SignOut` action.

### Further technical details
- ASP.NET Core version: 6.0.0-rc.1.21452.15
- Include the output of `dotnet --info`:
```cmd
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21360.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 4.1 [31717.71.d17.0]

**Comment by kevinchalet** [comment]
`AuthenticationProperties.RedirectUri` is only honored if the current request path matches the configured `CookieAuthenticationOptions.LogoutPath`: if you call `SignOut` for a different request path, the value is simply ignored.

It works the same way for sign-in operations.

I've never understood this restriction but it's always been a source of annoyance, for sure 😄

**Comment by safern** [comment]
Interesting, I haven't configured a `CookieAuthenticationOptions.LoginPath` either and it is working for signing, maybe it works because I'm using the `Challenge` operation for signing in with a specific provider rather than the `SignIn` operation?

**Comment by kevinchalet** [comment]
Yes: in this case, `RemoteAuthenticationHandler` flows a null `RedirectUri` to the "sign-in handler" (typically an instance of the cookies authentication handler) and does the "redirect to redirect URL" dance itself, without the restriction enforced by the cookies handler.

**Comment by kevinchalet** [comment]
If you're interested in the gnarly details, it happens right here:
  - https://github.com/dotnet/aspnetcore/blob/b507fc27d9f15747596c564f27c336a695b32f72/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L140-L145
  - https://github.com/dotnet/aspnetcore/blob/b507fc27d9f15747596c564f27c336a695b32f72/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L166-L175

**Comment by safern** [comment]
Thanks for sharing the code. That is an unfortunate behavior... I don't know if it is documented, I couldn't find anything about it. Let's see what aspnetcore folks have to share/say about this behavior.

**Comment by adityamandaleeka** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Yes that restriction is here:
https://github.com/dotnet/aspnetcore/blob/a5be6c5916e1a537f3cefcc31985b9f8a1fe0a27/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L400-L401
I'm not sure why that exists either, and the comments for it are terrible.
https://github.com/dotnet/aspnetcore/blob/a5be6c5916e1a537f3cefcc31985b9f8a1fe0a27/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L91

They other thing you can do is to call SignOut explicitly and then redirect as a separate step.
```
    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    return Redirect("/" );
```

**Comment by adityamandaleeka** [comment]
Triage: let's talk to the AAD team and figure out if there's any reason we need to keep this behavior. Is there an open redirect risk if we remove it?

**Comment by kevinchalet** [comment]
Is it something that could be done as part of 7.0? (FWIW, it's something that would be used with OpenIddict's new OIDC client: https://github.com/openiddict/openiddict-core/blob/a1215728db33dcc70d5c1e50d258fc2aba37867f/sandbox/OpenIddict.Sandbox.AspNetCore.Client/Controllers/AuthenticationController.cs#L119-L124)

**Comment by adityamandaleeka** [comment]
@ldillonel Can you please follow up on this one? Looks like the last time this was discussed in triage, we wanted to talk to the AAD team about it.

@Tratcher and/or @blowdart can likely help get you up to speed.

**Comment by kevinchalet** [comment]
@Tratcher I took a look at Katana - that has the same restriction - and I think I understand why it exists: Katana didn't support specifying a value for `AuthenticationProperties.RedirectUri` (so it was basically ignored) and only supported redirecting to the `ReturnUrl` parameter extracted from the current request, but it only it the request path matched the login endpoint. It made sense because trying to extract this parameter from any arbitrary request was likely not considered secure enough.

In ASP.NET Core, things are different and the same restriction should only apply to the same scenario, i.e when the `ReturnUrl` is extracted from the ambient request instead of being resolved from the authentication properties.

Does it make sense?

**Comment by Tratcher** [comment]
I see what you mean. That does make sense that we'd only trust the query param on certain paths, but specifying a redirect should be fine from anywhere.

https://github.com/dotnet/aspnetcore/blob/28823371bfda29412038856f47964c0708ddc9f0/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L398-L400
https://github.com/dotnet/aspnetcore/blob/28823371bfda29412038856f47964c0708ddc9f0/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L411-L426

As compared to Katana:
https://github.com/aspnet/AspNetKatana/blob/beb224c88712b08ce45f1d14bb8cf0cd9d4a8503/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs#L288-L301

(You really are an archeologist 😁)

**Comment by kevinchalet** [comment]
> (You really are an archeologist 😁)

🤣 

(let me know if you guys would be interested in a PR for this 😄)

**Comment by kevinchalet** [comment]
> (let me know if you guys would be interested in a PR for this 😄)

I went ahead and sent a PR: https://github.com/dotnet/aspnetcore/issues/36934

**Comment by blowdart** [comment]
Yea this is weird. If you're specifying in code you'd assume it was correct. Id say switch to be the expected behaviour above and see what happens 😬
