### ISSUE TITLE
fail `dotnet watch run` CS0246 The type or namespace name 'App' could not be found

### ISSUE THREAD

**Issue by ibocon** [dotnet/aspnetcore#36985]
### Describe the bug
> dotnet watch run --project AspCoreProject.csproj

> WebAssemblyProject\Program.cs(3,28): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [WebAssemblyProject.csproj] 

![image](https://user-images.githubusercontent.com/9730869/134812816-4d4c5aa6-e6c5-4ede-a98a-4f1a470ac04f.png)

### To Reproduce

1. Create Blazor WebAssembly project
2. run `dotnet watch run`

[Project](https://github.com/ibocon/StackOverflow/tree/dotnet/aspnetcore%2336985)

```cs
using BlazorApp1;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

await builder.Build().RunAsync();
```

### Exceptions (if any)
> WebAssemblyProject\Program.cs(3,28): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [WebAssemblyProject.csproj] 

### Further technical details
- ASP.NET Core version

SDK 6.0.100-rc.1

- Include the output of `dotnet --info`

![image](https://user-images.githubusercontent.com/9730869/134813013-b8610645-e553-4dc4-a873-41792c1f3e4c.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

![image](https://user-images.githubusercontent.com/9730869/134813197-9d5f0bc1-a6fd-4c44-bac6-76d0d4ac393f.png)

**Comment by ibocon** [comment]
Is there any work around for this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have tried this out but are unable to reproduce this issue. Can you please share a reliable repro project so that we can investigate this further? Thanks

**Comment by ibocon** [comment]
After uninstall and install .NET 6 RC 2, It is solved.
