### ISSUE TITLE
Blazor Server and Css Isolation using .Net 6 + VS Community 2022

### ISSUE THREAD

**Issue by moehoward** [dotnet/aspnetcore#36996]
I have two projects:

    Sdk="Microsoft.NET.Sdk.Web"
    Sdk="Microsoft.NET.Sdk.Razor"

The Blazor Server app (#1) references the Razor library (#2)
and it uses the following markup in its \<head\> section.

    <link href="BlazorApp1.styles.css" rel="stylesheet" />

The Razor library utilizes Css Isolation.
I am getting this error message in the browser's console.

    browserLink:77 Uncaught (in promise) TypeError: Cannot read property 'href' of null
        at tt (browserLink:77)
        at nt (browserLink:77)
        at tt (browserLink:77)
        at nt (browserLink:77)
        at tt (browserLink:77)
        at it (browserLink:77)
        at ct.ensureCssUpToDateAsync (browserLink:77)
        at browserLink:71
        at i (browserLink:71)
        at l (browserLink:71)

This error message was not present while using VS 2019 and .NET 5.
The browser's Network tab displays both files.

    BlazorApp1.styles.css
    RazorApp1.bundle.scp.css

And the BlazorApp1.styles.css contains the proper import.

    @import '_content/RazorApp1/RazorApp1.bundle.scp.css';

Any thoughts?
:<)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by mkArtakMSFT** [comment]
@jodavis  FYI
