### ISSUE TITLE
Razor page call "component.razor" causes a problem in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36995]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor-page-call-componentrazor-causes/1485964)._

---
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 2.1

Blazor Server Side project

In the Pages folder create a Razor component called "component.razor" with a lower case c.
This triggers the RZ10011 error in the error list.
The RZ10011 error link doesn't link to a page.

The RZ10011 error is reported to be in the file called CSC which does not exist in the project.

In my opinion this should not cause a problem, the default name is Component with a capital C and that one doesn't trigger any issue.

---
#### Feedback Bot on 7/26/2021, 01:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Component names can't start with lower case because that's how we differentiate them from HTML elements.

**Comment by NMJCaspers** [comment]
When that is the case i would expect an error message that says exactly that, and not an unspecified and undocumented error being indicated in a file that doesn't exist.
