### ISSUE TITLE
How to get Physical Path for virtual path in .NET 6 RC1?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#37008]
I am using .NET 6 RC1 Blazor Wasm Hosted App.

 I am running into issue where i don't get correct value for the virtual director's physical path.
 My app generates QR code which I need to temporarily store in images folder of virtual directory.

In the constructor of API controller i am resolving

`_webHostingEnvironment = serviceProvider.GetRequiredService<IWebHostEnvironment>();`
         
```
var webRootPath = ""; 
if (string.IsNullOrWhiteSpace(_webHostingEnvironment.WebRootPath)) 
  webRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot"); 
else 
   webRootPath = _webHostingEnvironment.WebRootPath
```

**Firstly _webHostingEnvironment.WebRootPath is always null_**, hence the code always gets the path from Directory.GetCurrentDirectory().

Directory.GetCurrentDirectory provide the path of Server, but not the actual deployed path of wwwroot which is further down like /bin/debug/net6.0/wwwroot.

Now i could append that static path to get full path, but no sure what to use when i deploy it on Azure App Service or while using other deployment models.

**Comment by adityamandaleeka** [comment]
@nssidhu Can you please share a repro for this?
