### ISSUE TITLE
Add RequestLoggingMiddleware

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#3700]
There's lots of advice on how to log the headers and body of an incoming and outgoing http request (and response) on the interwebs:

- https://stackoverflow.com/questions/46361958/asp-net-core-mvc-log-request-body
- https://elanderson.net/2017/02/log-requests-and-responses-in-asp-net-core/

To name a few of them. They are not done in very safe ways: 
- Some buffer the entire request body of every request (not respecting the IHttpBufferingFeature). This results in memory bloats (a potential DoS)
- Some don't rewind the Stream properly.
- The implementations aren't lazy 
- There are security implications as well (sensitive data may be in headers, other PII, GDPR?)

It seems like lots of people are doing this and doing it incorrectly and inefficiently, we should add a middleware here as this is very common and requires no new dependencies.

Strawman:

```C#
public class RequestLoggingMiddlewareExtensions
{ 
      public IApplicationBuilder UseRequestLogging(this IApplicationBuilder app) { }
      public IApplicationBuilder UseRequestLogging(this IApplicationBuilder app, RequestLoggingOptions options) { }
}

public class RequestLoggingOptions
{
     // Determines if the cookie header is logged
     public bool LogCookieHeader { get; set; }
     // Determines if the authorization header is logged
     public bool LogAuthorizationHeader { get; set; }
     // Determines the verbosity of the logs
     public RequestLoggingLevel RequestLogLevel { get; set; }
}

[Flags]
public enum RequestLoggingLevel
{
    None = 0,
    RequestHeaders = 1,
    ResponseHeaders = 2,
    RequestBody = 4,
    ResponseBody = 8,
    AllRequest = RequestHeaders | RequestBody
    AllResponse = RequestHeaders | RequestBody
    All = AllRequest | AllResponse
}
```

cc @Tratcher

**Comment by Tratcher** [comment]
HttpClientFactory has some of [this](https://github.com/aspnet/HttpClientFactory/blob/4dfcf7485e62819d0d73c00d7e7eb53d75abdbd3/src/Microsoft.Extensions.Http/Logging/LoggingHttpMessageHandler.cs).

Rather than having a bool for cookie and a bool for auth, it should be a collection where they can exclude whatever they like. Or you could invert it to an include collection. Do you need separate collections for request and response headers? Probably not.

Are the request/response first lines implicitly included in the Headers? Or do you assume Hosting is logging those separately? How about Exceptions?

RequestLoggingLevel => ComponentsToLog

`All` makes it awkward to add other components later (e.g. timing, session, etc.). What's the default?

It needs an event where you can determine the components to log per request.

The downside of logging the request/response body in a lazy way is that it gets spread out across the logs and takes extra work to re-assemble.

**Comment by jkotalik** [comment]
I was thinking about this too with regards to diagnosing failures on azure. Though this is useful, I think it will nice if we push for a more FREB like middleware, which will only activate when certain conditions are met (conditions like [status code and request timeout](https://docs.microsoft.com/en-us/iis/troubleshoot/using-failed-request-tracing/troubleshooting-failed-requests-using-tracing-in-iis#step-2--configure-your-failure-definitions)). In production environments, no one would want to have the RequestLoggingMiddleware on if it logs per request; this would give a nice middleground between diagnostics and performance. 

Maybe something like this:

```c#
public class RequestLoggingMiddlewareExtensions
{ 
      public IApplicationBuilder UseRequestLogging(this IApplicationBuilder app) { }
      public IApplicationBuilder UseRequestLogging(this IApplicationBuilder app, RequestLoggingOptions options) { }
}

public class RequestLoggingOptions
{
     // Determines if the cookie header is logged
     public bool LogCookieHeader { get; set; }
     // Determines if the authorization header is logged
     public bool LogAuthorizationHeader { get; set; }
     // Determines the verbosity of the logs
     public RequestLoggingLevel RequestLogLevel { get; set; }
     // Whether to only log failed requests (status code 500+)
     // Consider making this configurable with int ranges
     public bool OnlyLogFailedRequests { get; set; }
     // Determines the timeout for when we should log a long hanging request
     public TimeSpan RequestTimeout { get; set; } = TimeSpan.FromSeconds(10);
}

[Flags]
public enum RequestLoggingLevel
{
    None = 0,
    RequestHeaders = 1,
    ResponseHeaders = 2,
    RequestBody = 4,
    ResponseBody = 8,
    AllRequest = RequestHeaders | RequestBody
    AllResponse = RequestHeaders | RequestBody
    All = AllRequest | AllResponse
}
```

**Comment by davidfowl** [comment]
> Rather than having a bool for cookie and a bool for auth, it should be a collection where they can exclude whatever they like. Or you could invert it to an include collection. Do you need separate collections for request and response headers? Probably not.

Feels like overkill, do we know what other types of headers people will want to exclude? It's the most flexible option for sure but I need to see some more real use cases first.

> It needs an event where you can determine the components to log per request.

Maybe, it's not a bad idea. What are some examples of this and how does this interact with the RequestLoggingLevel enum? Is it basically `IsEnabled(HttpContext context)`?

> Are the request/response first lines implicitly included in the Headers? Or do you assume Hosting is logging those separately? How about Exceptions?

I thought about this a bit when I was writing the proposal and I almost included it but it's already included by hosting. This also doesn't log exceptions. The ExceptionHandler middleware would do that.

> All makes it awkward to add other components later (e.g. timing, session, etc.). What's the default?

Yep, possibly, maybe we just leave it out. Default would be just headers. Maybe we add AllHeaders to the enum.

> The downside of logging the request/response body in a lazy way is that it gets spread out across the logs and takes extra work to re-assemble.

Yes, but we have to do it that way. I don't want a middleware that buffers the entire request body. We can say responses/requests are written in 1K-4K chunks or something. 

It's possible we want to consider using event source for this as well.

@jkotalik Why is there a timeout on this middleware?

> Though this is useful, I think it will nice if we push for a more FREB like middleware, which will only activate when certain conditions are met (conditions like status code and request timeout)

The func that @Tratcher suggests can handle this.

**Comment by jkotalik** [comment]
> The func that @Tratcher suggests can handle this.

No it can't, the only way you can get the status code would be after the response is done, meaning we have to buffer the entire request/response. I guess these are tangential asks then as you don't want to buffer.

**Comment by Tratcher** [comment]
Interesting point. You could have a second event on response start to check if you want to log the response.

**Comment by Tratcher** [comment]
>> It needs an event where you can determine the components to log per request.

> Maybe, it's not a bad idea. What are some examples of this and how does this interact with the RequestLoggingLevel enum? Is it basically IsEnabled(HttpContext context)?

Func<HttpContext, RequestLoggingLevel> perhaps? Though you might need separate events for request and response.

**Comment by Tratcher** [comment]
> Determines the timeout for when we should log a long hanging request

Interesting, an explicit notification for requests that are taking too long.

**Comment by clement911** [comment]
> > The downside of logging the request/response body in a lazy way is that it gets spread out across the logs and takes extra work to re-assemble.
> 
> Yes, but we have to do it that way. I don't want a middleware that buffers the entire request body. We can say responses/requests are written in 1K-4K chunks or something.

I guess I understand for file upload requests, but for the vast majority of requests with HTTP FORM POST or json bodies, the body will be loaded in memory to deserialize to an object anyway.
Is it possible to check the content-type and decide whether to log the body eagerly or lazily based on it?
e.g. if content-type is json then eager. if file-upload, then lazy?
Maybe I'm missing something...

**Comment by davidfowl** [comment]
> I guess I understand for file upload requests, but for the vast majority of requests with HTTP FORM POST or json bodies, the body will be loaded in memory to deserialize to an object anyway.

The memory requires to represent an object in memory and the memory required to deserialize are different things. You can allocate 5 gigs to produce 5 mb (I've seen this before 😄 ).  Like it or not, you need to have limits, just log in reasonably sized chunks. 100KB is enough to blow up the large object heap. Here's a primer on some of the issues you can run into when running ASP.NET Core applications https://github.com/sebastienros/memoryleak.

**Comment by Mikilll94** [comment]
Is this going to be implemented?

**Comment by Mikilll94** [comment]
> To name a few of them. They are not done in very safe ways:
> 
> * Some buffer the entire request body of every request (not respecting the IHttpBufferingFeature). This results in memory bloats (a potential DoS)
> * Some don't rewind the Stream properly.

@Tratcher 
Could you elaborate more on how to do logging request and response bodies to avoid these problems?

**Comment by Mikilll94** [comment]
@Tratcher 
Thanks for explanation.

Are there any code examples on the Internet which shows how to correctly log requests and responses in ASP.NET Core?

**Comment by Tratcher** [comment]
I'm not aware of any fully built examples. Logging the full request and response is discouraged because A) it's expensive, B) it can log potentially sensitive information like user credentials.

**Comment by Mikilll94** [comment]
@Tratcher 

I know that requests for some endpoints should not be logged, i.e. endpoints related to authentication, but requests from other endpoints can be logged.

@davidfowl 

Maybe you know some fully-build examples done in the right way?

**Comment by xsoheilalizadeh** [comment]
@davidfowl, I'm working on a [library][1] that prepare some of your expectations.

[1]: https://github.com/xsoheilalizadeh/raccoonLog

**Comment by Mikilll94** [comment]
@xsoheilalizadeh 
Awesome!

**Comment by shirhatti** [comment]
Are there folks who already written their own middleware for request logging that they'd like to share as prior art for us to have a look at prior to designing something from a clean slate?

Open questions:
- What do you with large bodies? Truncation? Do you need streaming logs?
- What options would you like exposed?

Base proposal: Log should look like `httpRequestMessage.ToString()`

**Comment by xsoheilalizadeh** [comment]
@shirhatti you could check out my [implementation](https://github.com/xsoheilalizadeh/raccoonLog).

**Comment by davidfowl** [comment]
- I think we'd truncate by default and chunk of over a certain limit (configurable)
- Redacting headers

**Comment by jkotalik** [comment]
API Proposal:

```c#

    public static class HttpLoggingServicesExtensions
    {
        public static IServiceCollection AddHttpLogging(this IServiceCollection services) { }
        public static IServiceCollection AddHttpLogging(this IServiceCollection services, Action<HttpLoggingOptions> configureOptions) { }
    }

    public class HttpLoggingOptions
    {
        public HttpLoggingFields LoggingFields { get; set; } = HttpLoggingFields.RequestPropertiesAndHeaders | HttpLoggingFields.ResponsePropertiesAndHeaders;

        public ISet<string> AllowedRequestHeaders { get; } = new HashSet<string>()
        {
            HeaderNames.Accept,
            HeaderNames.AcceptEncoding,
            HeaderNames.AcceptLanguage,
            HeaderNames.Allow,
            HeaderNames.Connection,
            HeaderNames.ContentType,
            HeaderNames.Host,
            HeaderNames.UserAgent
        };

        public ISet<string> AllowedResponseHeaders { get; } = new HashSet<string>()
        {
            HeaderNames.ContentType,
            HeaderNames.Date,
            HeaderNames.ETag,
            HeaderNames.Server,
            HeaderNames.TransferEncoding
        };

        public Encoding? BodyEncoding { get; set; } = Encoding.UTF8;

        public List<MediaTypeHeaderValue>? SupportedMediaTypes { get; } = new List<MediaTypeHeaderValue>()
        {
            new MediaTypeHeaderValue("application/json"),
            new MediaTypeHeaderValue("application/xml"),
            new MediaTypeHeaderValue("text/*")
        };

        public int RequestBodyLogLimit { get; set; } = 32 * 1024;
        public TimeSpan RequestBodyTimeout { get; set; } = Debugger.IsAttached ? TimeSpan.FromDays(1) : TimeSpan.FromSeconds(1);
        public int ResponseBodyLogLimit { get; set; } = 32 * 1024; // 32KB
    }

    public class HttpLoggingMiddleware
    {
        public HttpLoggingMiddleware(RequestDelegate next, IOptions<HttpLoggingOptions> options, ILoggerFactory loggerFactory) { }
        public async Task Invoke(HttpContext context) { }
    }

    public enum HttpLoggingFields
    {

        None = 0,
        Path = 1,
        Query = 2,
        Protocol = 4,
        Method = 8,
        Scheme = 0x10,
        StatusCode = 0x20,
        RequestHeaders = 0x40,
        ResponseHeaders = 0x80,
        RequestBody = 0x100,
        ResponseBody = 0x200,
        RequestProperties = Path | Query | Protocol | Method | Scheme,
        RequestPropertiesAndHeaders = RequestProperties | RequestHeaders,
        ResponsePropertiesAndHeaders = StatusCode | ResponseHeaders,
        Request = RequestPropertiesAndHeaders | RequestBody,
        Response = StatusCode | ResponseHeaders | ResponseBody,
        All = Request | Response
    }

    public static class HttpLoggingBuilderExtensions
    {
        public static IApplicationBuilder UseHttpLogging(this IApplicationBuilder app) { }
    }
```

**Comment by BrennanConroy** [comment]
Namespace?

**Comment by magnusbakken** [comment]
With this proposal, how would you exclude specific endpoints, or conditionally enable/disable logging of specific items for specific endpoints?

**Comment by davidfowl** [comment]
@magnusbakken we skipped that feature for preview4 but have plans to tackle it for preview5. @jkotalik can you file that issue?

Also we need to have benchmarks for this middleware

**Comment by davidfowl** [comment]
@jkotalik can you update the proposal based on your latest changes?

**Comment by jkotalik** [comment]
Tomorrow morning; there are still more changes I need to make 😄

**Comment by jkotalik** [comment]
Console:

![image](https://user-images.githubusercontent.com/8302101/115052373-b7bd9180-9e92-11eb-988e-f0340e4af7c2.png)


JSON:
![image](https://user-images.githubusercontent.com/8302101/115053109-9c06bb00-9e93-11eb-984a-2f8440d7fa75.png)

![image](https://user-images.githubusercontent.com/8302101/115053155-aa54d700-9e93-11eb-8f1e-a0ea7ff96345.png)

**Comment by BrennanConroy** [comment]
The Console log should have a title so you can tell it's a request or response log easily.

**Comment by jkotalik** [comment]
Seq:
![image](https://user-images.githubusercontent.com/8302101/115056150-50561080-9e97-11eb-8798-68964e7783a7.png)

**Comment by davidfowl** [comment]
Is that X the redacted text?

**Comment by jkotalik** [comment]
RequestProperties -> no one loves this name, can't come up with something better. Offline suggestions appreciated
Trailers -> Add to enum now
Path, Query, etc -> prefix with Request/Response for clarity
Interfaces for Set and List (internal fields for middleware access)

**Comment by BrennanConroy** [comment]
Can we see an example of request and response bodies?
If I'm looking at the code correctly, it looks like the headers and other info is a separate log from the bodies, are we interested in linking them somehow so users can see which headers go with which bodies?

**Comment by jkotalik** [comment]
AllowedRequestHeaders -> VisibleRequestHeaders and same for response

**Comment by jkotalik** [comment]
Make sure that encoding last parts of the byte array are not splicing characters due to truncation.

**Comment by jkotalik** [comment]
MediaTypeHeaderValue has encoding, use that instead.

**Comment by jkotalik** [comment]
Default to UTF8 if one isn't specified in the MTHV

**Comment by jkotalik** [comment]
New type for MTHV list that allows supporting binary and Encodings

```c#
namespace Microsoft.AspNetCore.HttpLogging
{
public sealed class MediaTypeOptions
{
   AddBinary(MediaTypeHeaderValue);
   AddBinary(string);
   AddText(MediaTypeHeaderValue);
   AddText(string);
   AddText(string, Encoding);
   Clear();
}
}
```

**Comment by jkotalik** [comment]
> If I'm looking at the code correctly, it looks like the headers and other info is a separate log from the bodies, are we interested in linking them somehow so users can see which headers go with which bodies?

How would you suggest linking them?

**Comment by BrennanConroy** [comment]
Idk, delay the whole log until the body is written so they're part of the same message, or generate some ID that both logs use?

**Comment by jkotalik** [comment]
The response body can be consolidated today, but request cannot; if someone doesn't read the request body, the request wouldn't be logged.

@shirhatti what's the typical way these logs would be associated?

**Comment by shirhatti** [comment]
Via logging scopes. Request id is already on the scope

**Comment by jkotalik** [comment]
Initial implementation committed, closing as we have follow up issues filed.
