### ISSUE TITLE
How to obtain external login claims in Controller ? 

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/aspnetcore#37018]
I am trying to access external login claims via `await signInManager.GetExternalLoginInfoAsync()` and it returns null. 

What is proper way of doing it ? 

I am on ASP.NET 6 RC1 + Identity  + angular template.

**Comment by HaoK** [comment]
The external cookie is only around during the one request that exchanges the external auth cookie for the main identity/application cookie, so you would need to do something similar to this sample https://github.com/dotnet/aspnetcore/tree/main/src/Security/samples/Identity.ExternalClaims

**Comment by YakupIpek** [comment]
@HaoK I use `AddOpenIdConnect` method and there is no `OnCreatingTicket`  on the context parameter but i tried `OnTicketReceived`, `OnTokenValidated`, `OnTokenResponseReceived` events and i still couldn't see what i added in `User.Claims` on controller. 

That example project is .NET 6 RC1 ? I am not able fetch repository and test that project right now.
