### ISSUE TITLE
Huge Optimization Idea For Blazor Wasm

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#37015]
since microsoft has its own browser microsoft edge chromium, can we put dot.net framework inside the browsers, so blazor apps can now have two releases when published in visual studio, one for the other browsers which doesn't have the dotnet framework available which will continues to use the self-contained mode, one for microsoft edge which uses the framework-independent release, so now blazor apps/websites when visited using microsoft's browser it will try to use the slimmed down version that's going to make the downloading and loading of the blazor wasm applications way faster.
I know it only works on one browser but microsoft can advertise to people that their browser will let users visit some websites faster.

**Comment by Xyncgas** [comment]
Say "New Performance Improvement! Microsoft's Edge is continuing to evolve and bringing you new features. This time we've reduced the load time on websites that uses certain technologies to be 300% faster, and these websites are about 5% of the internet..." etc and everyone is going to be happy after hearing this. I think microsoft should start integrating common runtimes into the browser and we as developers can now release applications with two releases one being framework-dependent

**Comment by mrwcjoughin** [comment]
i don't think that is a good idea - its moving back to the Silverlight way of things. we shouldn't have care about what version of edge whether it has the right net to run our app. by including the parts of dotnet we are using in the distribution we don't have to worry about the browser having what we need - it just works

**Comment by Xyncgas** [comment]
the ability to deploy stand alone "just works" apps allow such optimizations, because it can be an opt-in feature at run time or load time

**Comment by Xyncgas** [comment]
Silverlight wasn't so bad, microsoft was just ahead of time. the web wasn't so rich and silver light wasn't very powerful but something fancy to not to bother. but there is not going to be a seperate eco system for a seperate set of applications, asp.net is still going to be asp.net. I would even suggest to add a feature in edge browser that lets user to installed ( and be prompted to install ) internal plug-ins like c++ compiler that also runs inside a sandbox in webassembly

**Comment by Xyncgas** [comment]
I feel like there's either two choices, browser is our new operating system, or we just abandon the browser and take the web standard on common runtime that's equally portable (.NET, other intepreted languages runtime...). I am excited for both, wondering if any other people feel the same way

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this is not directly Blazor specific.
