### ISSUE TITLE
ReadyToRun Compilation with runtime win-x64 gives error - NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture.

### ISSUE THREAD

**Issue by Ogglas** [dotnet/aspnetcore#37034]
### Describe the bug

Running the example command from ReadyToRun Compilation docs gives the error below.

https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run

> C:\Program Files\dotnet\sdk\5.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(316,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. 

### To Reproduce

Create a new Blazor WASM project targeting .NET 5 and run the following command:

`dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true`

Tried with ` linux-x64` with the same result and I have tried with running a restore first like this:  `dotnet restore -r win-x64`

Minimal repo:

https://github.com/Ogglas/BlazorTest

According to documentation it should work:

### Supported compilation targets are described in the table below when targetting .NET 5 and below.

SDK platform | Supported target platforms
-- | --
Windows X64 | Windows X86, Windows X64, Windows ARM64
Windows X86 | Windows X86, Windows ARM32
Linux X64 | Linux X86, Linux X64, Linux ARM32, Linux ARM64
Linux ARM32 | Linux ARM32
Linux ARM64 | Linux ARM64
macOS X64 | macOS X64

https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#cross-platformarchitecture-restrictions

Running `$LastExitCode` from Powershell after the command returns `1`.

### Exceptions (if any)

> C:\Program Files\dotnet\sdk\5.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(316,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. 

### Further technical details
ASP.NET Core version - 5.0.401
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version - Microsoft Visual Studio 2019 Version 16.11.3
Include the output of dotnet --info
.NET SDK (reflecting any global.json):
Version: 5.0.401
Commit: 4bef5f3dbf

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19043
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
Version: 5.0.10
Commit: e1825b4928

.NET SDKs installed:
5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by pranavkm** [comment]
@Ogglas ReadyToRun is specific to the platforms that you listed there. Blazor WebAssembly in .NET 6 supports AOT thru a different toolchain that is documented here: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation.
