### ISSUE TITLE
DateOnly and TimeOnly are displayed as complex objects in open-api schemas rather simple string

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#37045]
### Describe the bug

`DateOnly` and `TimeOnly` are being displayed as complex objects in open api schemas for Minimal API endpoints rather than being treated as simple strings.  It will make sense for open api to treat them as `string -$date-only` and  `string -$time-only`

`app.MapGet("/events", (DateOnly dateOnly, TimeOnly timeonly) => $" date and time values ... ")`

### Exceptions (if any)

``` csharp

  ### Further technical details
  .NET SDK (reflecting any global.json):
   Version:   6.0.100-rc.2.21465.13
   Commit:    0d1cdfa6a0
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19043
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21465.13\
```

**Comment by rafikiassumani-msft** [comment]
This may need a change in Swashbuckle and N-Swag for these new primitives.

**Comment by captainsafia** [comment]
Looked into this briefly. Draft 07 of the JSON schema adds support for the `date` and `time` formats on strings ([ref](https://json-schema.org/draft-07/json-schema-release-notes.html)). Until that is officially incorporated into the spec, it probably makes sense to keep this as an object.

**Comment by DamianEdwards** [comment]
Looks like this doesn't happen now in .NET 7, but it's still not perfect. It's now projected as a string (good!) but with the "date-time" format (bad!). Seems [Swagger does actually support "date" as a format now](https://swagger.io/docs/specification/data-models/data-types/#string) so we should get Swashbuckle updated to map `DateOnly` to "string" formatted as "date". [Swashbuckle has an issue filed for this already](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2319).

**Comment by DamianEdwards** [comment]
Workaround by adding a type mapping to Swashbuckle until they fix their defaults:

```c#
builder.Services.AddSwaggerGen(
    c.MapType<DateOnly>(() => new OpenApiSchema
    {
        Type = "date"
    });
);
```

**Comment by captainsafia** [comment]
@rafikiassumani-msft I think we should close this in favor of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2319. I already have a PR out to fix it at https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2480
