### ISSUE TITLE
Removal of DefaultViewCompilerProvider in RC1 breaks AddRazorRuntimeCompilation in previous version libraries

### ISSUE THREAD

**Issue by phil-scott-78** [dotnet/aspnetcore#37049]
With .NET 6 RC1, this [commit](https://github.com/dotnet/aspnetcore/pull/35017/files#diff-940b7b75940c08518ebeb80c4d993d5972765f34ceba07f6158384fff8332160L17) drops `DefaultViewCompilerProvider ` and combines it into `DefaultViewCompiler`. This causes issues when you have a previous framework version calling `AddRazorRuntimeCompilation` when running on .NET 6 RC1. The hardcoded name [DefaultViewCompilerProvider](https://github.com/dotnet/aspnetcore/blob/v3.1.19/src/Mvc/Mvc.Razor.RuntimeCompilation/src/DependencyInjection/RazorRuntimeCompilationMvcCoreBuilderExtensions.cs#L68) is used in the 3.1 library, but the runtime is now registering `DefaultViewCompiler` instead causing the check to fail.

Reproduction can be found here. https://github.com/phil-scott-78/DotNet31RazorOnDotNet6. Output is `Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler` when it should be `Microsoft.AspNetCore.Mvc.Razor.Compilation.RuntimeViewCompiler`

Unfortunately, I'm kinda at a loss at to how to resolve this other than keep `DefaultViewCompilerProvider` and `DefaultViewCompiler` separate.

**Comment by pranavkm** [comment]
Thanks for the issue report @phil-scott-78. We're looking to undo the change as part of https://github.com/dotnet/aspnetcore/issues/35267 for the .NET 6 GA release. That said, we generally recommend updating packages when updating TFMs.

**Comment by phil-scott-78** [comment]
Right on, that revert would be good

Issue is that I'm consuming Statiq.Framework which is 3.1 while my app is the net6. So my hands are tied due to the third party.

I think we have a work around, but it isn't one that I think anyone else that runs across this bug would figure out so I'm glad to see it'll be tracked for GA

**Comment by daveaglick** [comment]
For what it's worth, anyone else who happens upon this issue while using runtime Razor compilation (though I doubt there are many if any) can mitigate with the following code:

```
IMvcCoreBuilder builder = serviceCollection
    .AddMvcCore()
    .AddRazorViewEngine();

// Remove *any* existing IViewCompilerProvider registration before adding the one in AddRazorRuntimeCompilation
ServiceDescriptor serviceDescriptor = builder.Services.FirstOrDefault((ServiceDescriptor f) => f.ServiceType == typeof(IViewCompilerProvider));
if (serviceDescriptor is object)
{
    builder.Services.Remove(serviceDescriptor);
}

builder = builder.AddRazorRuntimeCompilation();
```

> That said, we generally recommend updating packages when updating TFMs.

That makes total sense when using the runtime and the Razor engine together as a consumer. Unfortunately in our situation this was a case of using the Razor engine in a library that still targets .NET Core 3.x. Updating that library to support an across-the-board version bump for all the ASP.NET Core bits to the latest LTS release will take some time. In the meantime, downstream consumers attempting to use the library + the latest runtime hit this. Thankfully the workaround above resolves the issue for users targeting any runtime - though like @phil-scott-78 said, an upstream fix is certainly appreciated.
