### ISSUE TITLE
OpenIdConnectHandler and PAR (Pushed Authorization Requests)

### ISSUE THREAD

**Issue by Riff451** [dotnet/aspnetcore#37059]
Hello,
I'm investigating the use of the openid connect middleware with a flow that makes use of the Pushed Authorization Requests ([PAR](https://datatracker.ietf.org/doc/html/rfc9126)).

What I was trying to do is implementing the `RedirectToIdentityProvider` event to call the PAR endpoint of the authorization server and build a custom authorization request with the `request_uri` returned from the PAR call.

The main issue I'm having is related to the `ProtocolMessage.State` that the `OpenIdConnectHandler` creates internally AFTER the call to `RedirectToIdentityProvider`. This way I'm not able to pass this `state` in the PAR call. This means the AS doesn't have the `state` that needs to be part of the redirect to the relying party in order to have the `OpenIdConnectHandler` working properly.

Is there any way I can achieve this without replacing/extending `OpenIdConnectHandler` (that I don't want to do as it would probably be an error prone workaround).

Thank you very much.

**Comment by blowdart** [comment]
It's not a flow we've looked at, and won't until it's much further along the draft process. When you start to dip into things like "custom authorization request" we start geting a little concerned that what we might right now we'll have to change when the rfc makes it out of draft.

**Comment by Riff451** [comment]
@blowdart Thanks for the quick response. Ok, it makes sense, I think it was promoted to RFC just a few days ago. Given the necessity to integrate with a (very custom) flow of the AS that requires PAR, what would you recommend? Just re-implementing the whole integration manually rather than trying to use of the  existing openid connect middleware?

**Comment by blowdart** [comment]
For now I'd think so yes unless @Tratcher has any good ideas.

I've added support to the list of things for 7 we should consider but obviously no promises.

**Comment by Tratcher** [comment]
RedirectToIdentityProvider allows you to call `RedirectContext.HandleResponse()` to skip the remaining logic.
https://github.com/dotnet/aspnetcore/blob/59baa0d6f93022e87cc82faaf0433fe3513a38a9/src/Security/Authentication/OpenIdConnect/src/Events/RedirectContext.cs#L37-L40
https://github.com/dotnet/aspnetcore/blob/59baa0d6f93022e87cc82faaf0433fe3513a38a9/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L446-L451

You would need to copy any parts of that skipped logic that you want to keep into your RedirectToIdentityProvider event, but that's better than copying the whole middleware.

**Comment by Riff451** [comment]
Thank you very much both!
For considering adding it in a future version and for a possible solution with the current one. I'll try it.
