### ISSUE TITLE
Question, is it possible to override Identity DefaultUI in a Razor class library

### ISSUE THREAD

**Issue by jhermsen** [dotnet/aspnetcore#37071]
I have been trying to get it to work, but either it doesn't work or I'm missing something.

In startup I used the services.AddDefaultIdentity<User>() to enable the DefaultUI and that works.

Now I'm trying to use a Razor class library to override the UI so I added the Areas\Identity\Pages\Account\Login.cs and cshtml.
Also added a Test.cs and cshtml in the folder Areas\Identity\Pages\Account to test and that is reachable.

But the Login doesn't seem to be resolved. Is that by design or am I forgetting something here?

**Comment by HaoK** [comment]
Its not entirely clear what end result you want here, but if you want to use Identity without the UI, you can use the more granular methods and just don't call AddDefaultUI on the identity builder, this is an example of what that looks like
```
            services.AddIdentityCore<ApplicationUser>()
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddSignInManager()
                .AddDefaultTokenProviders();

            services.AddAuthentication(o =>
            {
                o.DefaultScheme = IdentityConstants.ApplicationScheme;
                o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            })
            .AddIdentityCookies(o => { });
```

**Comment by jhermsen** [comment]
What I am trying to do is create a Razor class library to contain my custom pages.
Also a few of the Identity pages.

For example what does work:
1. A WebApp with the AddDefaultIdentity so using the default UI.

2. What also works is using this same WebApp and adding a custom login page.
So basicly createing or scaffolding a file like: /Areas/Identity/Pages/Account/Login.cshtml

3. A WebApp doing it the way you proposed and adding all scaffolded identity pages to a Razor class library.

What does _not_ work:
4. That same WebApp from 1. and adding a Razor library containing the same page (/Areas/Identity/Pages/Account/Login.cshtml). 

I am guessing it is because it is at the same level as the DefaultUI a class library.
But is there a way to tell the framework to allow overrides from a Razor library?

Does this make the question clearer?

**Comment by HaoK** [comment]
You can try and do something like this https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Identity/UI/src/IdentityBuilderUIExtensions.cs#L113 and selective remove/replace views to point at your class library

@javiercn might have more context for you

**Comment by javiercn** [comment]
No, that's not something we support.
