### ISSUE TITLE
Question: Blazor WebAssembly project template in .Net 6, no more main method?

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#37072]
I just got into .Net 6 RC1 via the preview of VS 2022. I'm shocked to see that there is no longer a main method in Program.cs and the content of the main is just flatly present in the file. What is this voodoo? Is this part of a new C# feature somehow? I must have missed which version of C# introduced the main-less programs. IMO it removes consistency and self-descriptiveness to the code base. For newcomers it makes it hard to understand where the app gets started. I know that when I come across a new app I always start reading at the Main()! Removing a good ol' C tradition to please the JS crowd: 👎 

EDIT: I see this was introduced in C# 9 (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements). Not a good idea to make use of this feature by default in the Blazor templates, just my 2 cents.

**Comment by davidfowl** [comment]
We use it everywhere, not just the Blazor templates.

**Comment by user72356** [comment]
Closing now that I have the explanation as to why there is no longer a Main method.
