### ISSUE TITLE
Blazor WASM Support running without server

### ISSUE THREAD

**Issue by Asherslab** [dotnet/aspnetcore#37084]
### Is your feature request related to a problem? Please describe.
I am currently attempting to possibly use Blazor WASM to design "widgets" for a Digital Display system (scala.com). Doing this requires blazor to be loaded from local files instead of from a remote server (file:// instead of http://). When attempting to do this i get this error:
`blazor.webassembly.js:1 Fetch API cannot load file:///Users/asherslab/Desktop/Publish/wwwroot/_framework/blazor.boot.json. URL scheme "file" is not supported.`
Which is to be expected with browser security.

### Describe the solution you'd like
I'd love a way for blazor to not use fetch for loading local files when run from a file:// location and instead load the files from system. I believe this might be achievable by having the index.html file have the relative references listed in them and have the browser handle "downloading" them from the local files and then blazor grab them (i am not skilled enough to know if that is feasible, i apologise)

**Comment by javiercn** [comment]
@Asherslab thanks for contacting us.

You can use our custom deployment layout for Blazor WebAssembly apps support to completely customize how Blazor loads and potentially achieve this. You'll have to come up with you own loading scheme, however it should be doable. See the details [here](https://devblogs.microsoft.com/aspnet/custom-deployment-layout-for-blazor-webassembly-apps/#comment-3678)

**Comment by Xyncgas** [comment]
electron
blazor desktop / MAUI
Embeded web server...
