### ISSUE TITLE
Consider adding 'SPA' keyword to all SPA templates (React, Angular, etc.)

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#37097]
I couldn't find the ASP.NET Core SPA templates in VS when using the `SPA` keyword in the New Project dialog. That keyword returns no results. We should consider adding the `spa` keyword to those templates.

Pros:
* It could make the templates easier to find
* It doesn't conflict with any other project items (so it wouldn't 'spam' the dialog and create confusing results)
* _If_ it's a commonly used industry term, it could help align with that

Cons:
* If it's _not_ a commonly used industry term, it could look silly
* It's work (but it's only like 10 minutes of work)

![image](https://user-images.githubusercontent.com/202643/135307569-c111e672-8666-4649-ac15-f4fe60eb57c0.png)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
