### ISSUE TITLE
.NET 6.0 RC1 on macOS Apple M1: Blazor WASM AOT build generates & serves both, large dotnet.wasm and all the .DLLs

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#37092]
I am using @SteveSandersonMS's PictureFixer sample, based on @danroth27's fork for .NET 6.0 RC1 (https://github.com/danroth27/PictureFixer/tree/net6rc1)

When building and publishing an AOT-ed version with `dotnet publish -c Release`, I see all the DLL files, plus a large `dotnet.wasm` file:

![image](https://user-images.githubusercontent.com/888718/135255899-b79e908a-511c-4a6b-9deb-a889d67f0fbd.png)

When serving the publish folder with `dotnet PictureFixer.Server.dll`, all the files are served and transferred:

![image](https://user-images.githubusercontent.com/888718/135256965-708c6722-100d-4039-b64e-fb5628a9ca3d.png)

I was expecting a large `dotnet.wasm` and no (or maybe a few) DLL files being served.
Maybe there is something I am missing for an AOT build?

Thanks!

.NET info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.1.21463.6/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  3.1.413 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  5.0.401 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21458.32 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21463.6 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by danroth27** [comment]
Hi @ChristianWeyer. This behavior is expected. Even when using ahead-of-time (AOT) compilation, the DLLs are needed for reflection metadata and for certain .NET runtime functionality.

**Comment by ChristianWeyer** [comment]
Thanks @danroth27 - so essentially, AOT makes the app way bigger, I still have the DLLs to download, and the build process takes way longer? :-)
That means people have to think real hard whether they will need the runtime performance AOT gives them - right?

Is there already in-depth documentation about AOT? .cc @guardrex 

Thanks.

**Comment by guardrex** [comment]
Mentioned briefly (with a cross-link) at the bottom of the Hosting Models section for WASM at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0#blazor-webassembly

... and the full bit is at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation

... where it says ...

> The drawback to using AOT compilation is that AOT-compiled apps are generally larger than their IL-interpreted counterparts, so they usually take longer to download to the client when first requested.

... and then ...

> The size of an AOT-compiled Blazor WebAssembly app is generally larger than the size of the app if compiled into .NET IL. Although the size difference depends on the app, most AOT-compiled apps are about twice the size of their IL-compiled versions. This means that using AOT compilation trades off load time performance for runtime performance. Whether this tradeoff is worth using AOT compilation depends on your app. Blazor WebAssembly apps that are CPU intensive generally benefit the most from AOT compilation.

**Comment by ChristianWeyer** [comment]
Thanks @guardrex !

I think it is extremely essential and important to mention the part @danroth27 explained above for the need of the DLL files (and why exactly they are needed).
Otherwise, people are confused ( as I was ;-) ).

Thanks.

**Comment by guardrex** [comment]
It's tracked now. I'll get to that in due course over the next couple of weeks, certainly by the time we reach 6.0 GA.
