### ISSUE TITLE
Packing Blazor Webassembly client excludes _framework folder

### ISSUE THREAD

**Issue by dmtuan** [dotnet/aspnetcore#37095]
### Describe the bug
When I try to pack a whole Blazor Webassembly client project to nuget, **resulting nuget package is missing _framework in staticwebassets folder** (other files from wwwroot are present).

My goal here is to distribute the whole Blazor Webassembly client in a nuget package and use it in a ASP.NET Core hosting app.

### To Reproduce
1. Create a new Blazor Webassembly project (ASP.NET Core hosted). In my case, I named it BlazorTest.
    This results in these created projects:
    - BlazorTest.Client
    - BlazorTest.Server
    - BlazorTest.Shared
2. Add IsPackable set to true to .csproj of BlazorTest.Client project to make it packable:
```
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <IsPackable>true</IsPackable> // <--- THIS LINE
</PropertyGroup>
```
3. Run Pack from Visual Studio on BlazorTest.Client project:
![image](https://user-images.githubusercontent.com/7838796/135280899-4f9d1c28-cc65-4580-8070-7fd1b34bd423.png)

When checking the files in resulting .nupkg package, the whole _framework folder with blazor.boot.json, blazor.webassembly.js files and such is missing. 

### Further technical details
- Running .NET 5.0.400

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not a supported feature for Blazor WebAssembly projects. So you should not add the `IsPackable` property in the project file. Note, that there is also a warning printed about this, when you add that property.
