### ISSUE TITLE
[Epic] OpenAPI in .NET 7

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#37098]
(*) ‼️ = Prevents users from successfully using OpenAPI, 🔨 = Improves the experience for using OpenAPI
S = A few hours
M = A few days
L = About a week
XL = Multiple weeks

| Issue                                                        | Category                           | Impact (*) | Priority | Size | Status                                                 |
| ------------------------------------------------------------ | ---------------------------------- | ---------- | -------- | ---- | ------------------------------------------------------ |
| Route constraints don't produce appropriate information in OpenAPI schema (https://github.com/dotnet/aspnetcore/issues/36525) | `aspnetcore-bugs`                  | ‼️          | P0       | M    | ✅  (7.0-preview1)                                      |
| ASP.NET Core templates that include both Open API and Authentication should include scaffolding for Swagger to authenticate users (https://github.com/dotnet/aspnetcore/issues/36185) | `aspnetcore-features`              | 🔨          | P1       | S    | :x: Superseded by #39761                               |
| Support Deprecated in Minimal APIs for Open API  (https://github.com/dotnet/aspnetcore/issues/35091) | `aspnetcore-features`              | 🔨          | P2       | S    | ✅  (7.0-preview4)                                      |
| Support setting server on `PathItem` or `Operation` for each endpoint/controller/action | `aspnetcore-features`              | ‼️          | P1       | S    | ✅  (7.0-preview4)                                      |
| Respect `EndpointGroupName` attributes in MVC ApiExplorer (https://github.com/dotnet/aspnetcore/issues/35055) | `aspnetcore-bugs`                  | ‼️          | P0       | S    | ✅  (7.0-preview1)                                      |
| Support minimal APIs in NSwag (https://github.com/RicoSuter/NSwag/issues/3560) | `partner-features`                 | 🔨          | P1       | M    | ✅  (7.0-preview1)                                      |
| Automatically set endpoint metadata for minimal APIs (https://github.com/dotnet/aspnetcore/issues/34544) | `aspnetcore-features`              | 🔨          | P1       | M    |                                                        |
| Create an analyzer to help verify and fix endpoint metadata of minimal APIs (https://github.com/dotnet/aspnetcore/issues/34543) | `aspnetcore-features`, `analyzers` | 🔨          | P1       | L    |                                                        |
| Support authentication and authorization in OpenAPI (https://github.com/dotnet/aspnetcore/issues/34546) | `aspnetcore-features`              | ‼️          | P0       | L    | :x: Closed as a dupe of #39761                         |
| DateOnly and TimeOnly are displayed as complex objects in open-api schemas rather simple string (https://github.com/dotnet/aspnetcore/issues/37045) | `aspnetcore-bugs`                  | 🔨          | P2       | S    | :x: DateOnly and TimeOnly not supported by JSON schema |
| Generating REST Clients for .NET Minimal / Web API APIs (https://github.com/dotnet/aspnetcore/issues/36636) | `aspnetcore-features`              | 🔨          | P1       | XL   |                                                        |
| API analyzers should support undeclared status codes (https://github.com/dotnet/aspnetcore/issues/15385) | `aspnetcore-bugs`, `analyzers`     | 🔨          | P3       | M    |                                                        |
| API analyzer doesn't recognize ControllerBase.ValidationProblem (https://github.com/dotnet/aspnetcore/issues/6061) | `aspnetcore-bugs`, `analyzers`     | 🔨          | P3       | M    |                                                        |
| ProblemDetails is not returned for 404NotFound and 500Exception (https://github.com/dotnet/aspnetcore/issues/4953) | `aspnetcore-bugs`                  | 🔨          | P3       | S    | :x: Not actually OpenAPI                               |
| Mvc.Api.Analyzers not recognizing methods from a Base Class (https://github.com/dotnet/aspnetcore/issues/4410) | `aspnetcore-bugs`                  | 🔨          | P3       | M    |                                                        |
| Security schemes cannot be generated for individual endpoints/actions | `aspnetcore-bugs`                  | ‼️          | P0       | M    |                                                        |
| Descriptions and examples cannot be set for endpoints or controllers (#37906) | `aspnetcore-bugs`                  | ‼️          | P0       | S    | ✅  (7.0-preview4)                                      |
| Share more RequestDelegateFactory.CreateArgument logic (https://github.com/dotnet/aspnetcore/issues/33644) | `aspnetcore-bugs`                  | 🔨          | P2       | M    |                                                        |

**Comment by mholec** [comment]
I am still surprised why so much effort is put into generating documentation for the OAS. Considering the popularity of approaches like microservices and API gateways, generating documentation generally misses the point. Generated documentation never reaches the quality of the specification and reflects implementation errors. Generated documentation is unusable in practice for automation, mocking and testing. The specification first approach has been a trend for several years. How can Minimal APIs be minimalistic when half of the extension methods are used for swashbuckle instructions? In my opinion, a developer should program functionality, not instructions to generate documentation.

**Comment by captainsafia** [comment]
> I am still surprised why so much effort is put into generating documentation for the OAS. Considering the popularity of approaches like microservices and API gateways, generating documentation generally misses the point. Generated documentation never reaches the quality of the specification and reflects implementation errors. Generated documentation is unusable in practice for automation, mocking and testing. The specification first approach has been a trend for several years. How can Minimal APIs be minimalistic when half of the extension methods are used for swashbuckle instructions? In my opinion, a developer should program functionality, not instructions to generate documentation. 

Although not outlined in this issue, our future direction rests on using a singular `WithOpenApi` extension method for modifying OpenApi-related details. We recognize that the plethora of extensions was problematic and switched to this design approach.

We've also got issues tracked here to generate more of the documentation by default. The extension methods are only there for explicitly overriding generated annotations.

**Comment by captainsafia** [comment]
@rafikiassumani-msft What are your thoughts on closing this and creating a new epic for for .NET 8?
