### ISSUE TITLE
Licence of AspnetCore 3.1 and 5?

### ISSUE THREAD

**Issue by ericbl** [dotnet/aspnetcore#37091]
In https://github.com/dotnet/aspnetcore/issues/18873
the licence was changed from Apache 2 to MIT,

This is effective on .NET 6 but not on .NET 5 and .NET Core 3.1.

Does it mean .NET Core 3.1 and .NET 5 are meant to stay on Apache2 for the rest of their lives (in 2022) ?

**Comment by pranavkm** [comment]
@Pilchie

**Comment by Pilchie** [comment]
Yes, that's correct.
