### ISSUE TITLE
MetadataUpdateHandlerAttribute callback not invoked in .NET 6 Preview 5

### ISSUE THREAD

**Issue by tomasherceg** [dotnet/aspnetcore#37100]
I am playing with `MetadataUpdateHandlerAttribute`, but the `UpdateApplication` method is never called - no matter if I run it through VS 2019 Preview or via dotnet watch. 

The hot reload itself works, dotnet watch reports on the console that the code changes were applied successfully, but the callback is not invoked.

Is this supposed to work in .NET 6 Preview 5? Or am I missing something else that needs to be present in the assembly?

```
    [assembly: MetadataUpdateHandler(typeof(HotReloadMetadataUpdateHandler))]
    public static class HotReloadMetadataUpdateHandler
    {
        public static void UpdateApplication(Type[]? updatedTypes) => ...;
    }
```

**Comment by wli3** [comment]
Do you know where the invoking code is?

**Comment by stephentoub** [comment]
> Do you know where the invoking code is?

For `dotnet watch` it's currently in https://github.com/dotnet/sdk/blob/65a84eee9ca199ebdf567831baa2d03aa9aee197/src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs.

**Comment by mkArtakMSFT** [comment]
We believe this is resolved already. If you see otherwise, please let us know.
