### ISSUE TITLE
React SPA template is cumbersome to use when adding new API routes due to the proxy requirement

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#37103]
In the React SPA template there is a file `setupProxy.js` that seems to control which client HTTP requests get routed to ASP.NET Core (or not):

https://github.com/dotnet/spa-templates/blob/main/src/content/React-CSharp/ClientApp/src/setupProxy.js#L8-L16

I found it a bit cumbersome to have to edit that file when I added new APIs. I ended up grouping all my APIs into `/api` so that I could just add one entry:

```js
const context = [
    "/weatherforecast",
    "/api",
];
```

Would it make sense to have some common prefix such as `/api` so that many common scenarios would just work without having to edit this file?

**Comment by leastprivilege** [comment]
I personally think that the `/weatherforcast` route would be sufficient for all my future API requirements.

**Comment by Eilon** [comment]
Well, yes, `weatherforecast` stands for "WEb Api Total Holistic Extremely Realistic Full Omnipotent Really Easy Completely Awesome Superb Technology". Thus, all APIs should go under that prefix!

**Comment by mkArtakMSFT** [comment]
Closing, as the SPA templates have been removed from .NET 8 SDK.
