### ISSUE TITLE
Blazor Slow OAuth iFrame Request

### ISSUE THREAD

**Issue by travis-pettry** [dotnet/aspnetcore#37127]
### Issue

On application load Blazor waits for 10 seconds (displays Authorizing...) before sending the user to the home page while OAuth is being used. During this 10 second delay there are two successful network calls. The first call is from the client to the OAuth server via a silent iFrame using prompt=none and response_type=query sent to the Authorize end point. This gets a 302 login_reqired sent back to the Blazor app.
```
authentication/login-callback?state=state&error=login_required&error_description=errordescription
```

The second call executes the redirect to the login-callback, this returns a 200. Then rest of the Blazor app then loads over the network. After the 10 second timer expires the home page of the Blazor app loads.

AuthenticationService.js - 10 second timer
```
var t = e.silentRequestTimeout || 1e4;
i.Log.debug("IFrameWindow.navigate: Using timeout of:", t),
this._timer = window.setTimeout(this._timeout.bind(this), t),
```

The user can login to the Blazor App after it loads, the the JWT's that are produced from the OAuth server can be used to secure the app.

### Further Research 
In 2020 someone posted a simular issue with AWS Cognito (https://github.com/dotnet/aspnetcore/issues/22651). However, (at the time) AWS Cognito did not support iFrames, prompt=none, and response_type=query. These items are not an issue with this OAuth service. 

###Blaszor WASM OAuth Code
```
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.ResponseType = "code";
    options.ProviderOptions.Authority = "{OAuth_Server_URL}";
    options.ProviderOptions.ClientId = "{Client_ID}";
});
```

Does the AddOidcAuthentication expect more from the OAuth server then iFrames, prompt=none, response_type=query or does it specifically only work with Microsoft back tech like AAD and B2C? I saw references to making a custom Msal.js but I don't believe this is required if the OAuth server is compliant.

**Comment by dpozimski** [comment]
Have the same issue using Google oidc auth

`            
services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.DefaultScopes.Add("email");
    options.ProviderOptions.Authority = config.GoogleAuth.Authority;
    options.ProviderOptions.ClientId = config.GoogleAuth.ClientId;
    options.ProviderOptions.PostLogoutRedirectUri = config.GoogleAuth.PostLogoutRedirectUri;
    options.ProviderOptions.RedirectUri = config.GoogleAuth.RedirectUri;
    options.ProviderOptions.ResponseType = config.GoogleAuth.ResponseType;
});
`

**Comment by travis-pettry** [comment]
There was an issue with the openid-configuration file on the server, This is a non issue with Blazor. 

@dpozimski here's a repo with Google Auth, I hope it helps.
https://github.com/javiercn/BlazorGoogleAuthSample
