### ISSUE TITLE
Blazor Exception - navigator.userAgent and CSS

### ISSUE THREAD

**Issue by johnmangam** [dotnet/aspnetcore#37128]
### Describe the bug
I get an exception and I'm not able to figure out the cause, I suspect CSS:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
blazor.server.js:1

### To Reproduce

Minimum repo can be found at https://valstekt.com/assets/public_docs/shop/myshop.zip

### Further technical details
- Microsoft.AspNetCore.App 5 for developing a Blazor Server-side web app

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. We'll look into this in the future and see what needs to be done.
