### ISSUE TITLE
[Kestrel] Using Expect: 100-continue header in a request doesn't produce expected results

### ISSUE THREAD

**Issue by mjurgilas** [dotnet/aspnetcore#37126]
### Describe the bug
We currently have an API that has an endpoint that accepts a file through form data. We don't have any custom logic to validate the file size of the submitted file because we rely on the MaxRequestBodySize (the default value) limit to block large incoming files. Usually when submitting a large file, instead of the expected kestrel's 400 response, we get a connection reset. I understand that this is expected as written here: [Kestrel Request Draining](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/request-draining?view=aspnetcore-5.0).
The article recommends to use Expect: 100-continue header in order to prevent these issues. If I understand correctly, with that header, kestrel inspects the incoming request headers and If something is wrong (i.e. the content length is greater than the limit) it should return the expected 400 response before the body gets sent and subsequently 'drained'. Sadly, sending that header did not change anything. Using wireshark I sometime see the HTTP 100 response when uploading a small file (but not always), yet large files still sometime cause the connection to be dropped.
I might be completely misunderstanding the benefit of that header - if so, please correct me. Ideally we would not want to see the connection reset errors when sending a request with a file above the limit, just the validation

### To Reproduce
https://github.com/mjurgilas/Expect100ContinueRepro/tree/master
This is a minimal repo with one endpoint that has a form body file upload. Run the application and try to post a request with a file larger than 50MB or so with any HTTP client using the Expect: 100-continue header. Some requests will end up being dropped.
For me it looks something like this:  [Image](https://imgur.com/HypcokM) . The red requests are the ones that get dropped
### Further technical details
- ASP.NET Core version: 5.0.10
- Output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

**Comment by Tratcher** [comment]
> If possible, it's better for clients to use the Expect: 100-continue request header and wait for the server to respond before starting to send the request body. That gives the client an opportunity to examine the response and abort before sending unneeded data.

HTTP always requires the full request body to be sent or the request to be aborted. 100-continue doesn't avoid that, it only gives the client a short timeout to observe the response before sending anything and lets it decide to abort itself. That can allow the client to resend the request even if it wasn't buffered. Not all clients will take advantage of that option. What client are you using?

It also matters if the request is using Content-Length or Transfer-Encoding: chunked. Content-Length requests that are too large can be rejected much earlier without consuming any of the body. Chunked requests have to send the 100 continue response, read the body to the limit, and then abort.

**Comment by mjurgilas** [comment]
For testing I'm using postman to make the http requests. Now, I am not sure about how it handles the Expect header. Just to be safe I've tried using a small .Net application with a 100mb ```MultipartFormDataContent``` body and HttpClient's ExpectContinue flag set to true. When running locally using the .Net Core HttpClient I do not get the dropped requests, but when I test the same client with the same application hosted on an Azure app service, the requests get dropped most of the time. The requests are using Content-Length. 

I understand that this is not a support forum, but as I understand there is nothing that I can actually do to mitigate this issue (or doing something like enforcing a separate file size limit in all client applications that call the API, before they actually call it)?

**Comment by Tratcher** [comment]
> I understand that this is not a support forum, but as I understand there is nothing that I can actually do to mitigate this issue (or doing something like enforcing a separate file size limit in all client applications that call the API, before they actually call it)?

Validating the upload size on the client would certainly provide a better user experience. That doesn't mean you remove the server limits, just that you avoid hitting them most of the time.
