### ISSUE TITLE
Hot reload runs stale build

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/aspnetcore#37136]
If I save before hot reload has finished building the previous change it skips the latest save. Some sort of cancellation perhaps is needed to get the latest changes or queue them up?

I am running from dotnet watch. Visual Studios hot reload is not working.

SDK:
6.0.100-rc.1.21463.6

**Comment by danroth27** [comment]
@pranavkm

**Comment by Xyncgas** [comment]
I guess it's the same thing as saving a document when a build has already started.
Hot reload probably hadn't kicked in at that point.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There has been a lot of improvements to Hot Reload experience in VS. Please try out the latest VS release and see whether the issue is resolved. If not, we recommend sharing that through the VS Feedback.
