### ISSUE TITLE
Omnisharp does not work with CodeSpaces

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#37134]
Today I gave to try to codespaces to work with the aspnetcore repo. The codespaces were set up successfully, the latest .NET alpha version was successfully installed along with omnisharp C# extension as well! 

I realized that I am not getting any references to count or 'go to definition, autocomplete anything like that. I thought maybe because of omnisharp glitched as usual. So I tried to restart omnisharp using CTRL + Shift + P and typing restart omnisharp, I choose that option but I got the following error window. 

![image](https://user-images.githubusercontent.com/17148381/135469226-2899f929-fc56-408c-96bc-0660c2f634b7.png)

Not sure if this issue is specific to the repo because of misconfiguration or less configuration of omnisharp before we move to omnisharp repo to file!

**Comment by javiercn** [comment]
@ShreyasJejurkar thanks for contacting us.

@captainsafia you've been doing stuff in this area, do you have some thoughts?

**Comment by TanayParikh** [comment]
Moving this to `omnisharp/vs-code`. O# is installed considering the command was found.

**Comment by TanayParikh** [comment]
Closing this issue here.

**Comment by captainsafia** [comment]
@ShreyasJejurkar Thanks for trying this out! Feel free to provide further feedback on #34436.

Does this error repro across multiple rebuilds of the Codespace? You can also try downgrading the version of the C# extension your instance is using.

**Comment by ShreyasJejurkar** [comment]
Yes @captainsafia I thought the same. So I tried uninstalling extension and reinstalling it. But it did not worked. Anyway I will let omnisharp people know about this!

And I will be keep working on improving codespaces experience for aspnetcore repo as I learn further more in process about codespaces! 

Thanks!
