### ISSUE TITLE
Failed to load resources _framework/dotnet.timezones.blat and _framework/icudt_EFIGS.dat , server returns 404.

### ISSUE THREAD

**Issue by UserIsAmitHasan** [dotnet/aspnetcore#37138]
### Describe the bug
The problem is not seen on local development machine but can be seen on server (Shared hosting server, no control over IIS). This issue is seen after updating to .net 6.0 RC1 from preview version of .net 6.0. Previous preview versions worked fine. #29433 did not help.

### To Reproduce
1. Create Blazor Webassembly App using Visual Studio 2022 Preview Starter template with .net 6.0 RC1
2.  Publish **Self Contained**
3.  Deploy to IIS 10 

### Exceptions (if any)

![Screenshot 2021-09-29 161339](https://user-images.githubusercontent.com/41125642/135503178-85d0cc7e-82fa-4d5d-80f4-475c5c4c8673.png)

### Further technical details
- ASP.NET Core 6.0 RC1
- IIS 10
- Installed Runtime .NET 5.0.10
- Visual Studio 2022 Preview

**Comment by javiercn** [comment]
@UserIsAmitHasan thanks for contacting us.

* Can you check if the file exists on disk after you publish?
* If you go to the network tab, is the file present there?
* Could you try the latest nightly build (RC2) from dotnet/installers and see if that solves your issue?

**Comment by UserIsAmitHasan** [comment]
@javiercn thank you too.

1. File exists after publishing but fails to load returns 404. 
2. Network Tab:
    
![Screenshot 2](https://user-images.githubusercontent.com/41125642/135606547-f8906c7e-0692-4180-9e79-39802cd54244.png)

3. .Net 6.0 RC2 shows exact same issue

**Comment by javiercn** [comment]
@UserIsAmitHasan can you show us your csproj file?

**Comment by UserIsAmitHasan** [comment]
Server csproj:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.0-rc.2.21475.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\BlazorApp4.Client.csproj" />
    <ProjectReference Include="..\Shared\BlazorApp4.Shared.csproj" />
  </ItemGroup>


</Project>
`


Client :
`<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-rc.2.21475.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0-rc.2.21475.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\BlazorApp4.Shared.csproj" />
  </ItemGroup>

</Project>
`

**Comment by UserIsAmitHasan** [comment]
Client csproj:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-rc.2.21475.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0-rc.2.21475.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\BlazorApp4.Shared.csproj" />
  </ItemGroup>

</Project>
```
Server csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.0-rc.2.21475.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\BlazorApp4.Client.csproj" />
    <ProjectReference Include="..\Shared\BlazorApp4.Shared.csproj" />
  </ItemGroup>
</Project>
```

**Comment by javiercn** [comment]
@UserIsAmitHasan thanks for the additional details. 

I just tried with `6.0.100-rc.2.21480.23` and I'm not able to reproduce the issue.

Could you clean the bin and obj folders in your project and try again?

**Comment by UserIsAmitHasan** [comment]
@javiercn sure.

**Comment by UserIsAmitHasan** [comment]
@javiercn  yes files exists.

**Comment by UserIsAmitHasan** [comment]
@javiercn and I can start the website from published directory successfully. The problem is only on the remote server.

**Comment by javiercn** [comment]
@UserIsAmitHasan thanks for the additional details.

That seems a different issue then, likely with your deployment target. I would start [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#diagnosing-integrity-problems-1) to diagnose what might be going wrong.

One quick test is to grab the url for one of the missing files and try to access it with powershell (Invoke-WebRequest), postman or fiddle and see if you get a 200 response. That will tell you if at least there's a file on the remove server. 

If there is a file I would check the hash of the file (Get-FileHash) and compare it with the hash of the file in your publish folder. If they are different, then it means that something is changing the file (and in that case the integrity error is legitimate).

You also should check the content of blazor.boot.json to see if the hash matches the one on the file. Note that the hash there is sha256/base64 encoded

**Comment by UserIsAmitHasan** [comment]
@javiercn the wwwroot folder is missing from both bin\Debug\net6.0 and bin\Release\net6.0 but wwwroot \_framework folder exists in published folder directory (bin\Release\net6.0\publish\wwwroot\_framework). 

retrying after cleaning the bin and obj folders did not work. 

Maybe it's a server issue. I'll contact my hosting provider about this. 

- Thanks for your time.

**Comment by javiercn** [comment]
@UserIsAmitHasan thanks for the additional details. Let me see if I understand.

doing `dotnet publish` produces the right outcome (bin\Debug\net6.0\wwwroot and bin\Debug\net6.0\publish\wwwroot exist locally in your disk)

After a deployment only the contents of the publish folder should be in the host, nothing else is needed (so the app exe, and the wwwroot folder with the contents).

In any case, this seems like something specific to your configuration or hosting provider. If you still have issues I recommend reading the deployment section for details.

**Comment by UserIsAmitHasan** [comment]
@javiercn thank you very much, really  appreciate your help.
