### ISSUE TITLE
Mixing Blazor WebAssembly and Blazor Server Pages in same application

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#37131]
I happen to come across Q & A in old Blazor Presentation by Ryan Nowak
@ 45.55 second
https://youtu.be/SbFLKt8eSXk?t=2742

Is there any update on how to do that ? What would routing look like which could handle both the wasm and server scenario ?

In my Blazor Hosted wasm app, I have need to send URL in SMS to the user and user can click the URL, 
but this time instead of loading entire Blazor WASM, I want a server side page to run and just render the HTML, instead of download the entire APP.

I think it is great idea to allow such functionality as maximum of the boiler plate code is already written on the server App and would prevent deploying the entire server app again  as Blazor Server again on Azure APP service. This also introduces maintenance  headaches.

**Comment by Xyncgas** [comment]
I guess you could still do it somehow without the support from microsoft (using supported tools), by serving client side mono and letting user to interact with it, while signalR updating your dom rendered on the server

**Comment by pranavkm** [comment]
Closing this since we're tracking this work as part of https://github.com/dotnet/aspnetcore/issues/38128.
