### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.CreateSerializer(Type type) swallows exception

### ISSUE THREAD

**Issue by brumlemann** [dotnet/aspnetcore#37132]
Consider https://github.com/dotnet/aspnetcore/blob/6c487dee63ada5cb4943973cd44a05df2dacb263/src/Mvc/Mvc.Formatters.Xml/src/XmlSerializerOutputFormatter.cs#L150

This is a really bad pattern (how many million $s lost on this is for the gods of coding to know). I just spent an entire day tracking this down as a silent null return will(!) pop up somewhere else in the code.

The actual exception thrown here was a "There was an error reflecting type..." error. That I can deal with, going back to my type and fixing the problem. When it's postponed to later execution to deal with a NullReferenceException it quickly becomes very time consuming.

**Comment by BrennanConroy** [comment]
We log the exception(s) as warning which shows up by default in apps created with dotnet cli or VS.

> postponed to later execution to deal with a NullReferenceException

We also have nullable annotations on the method to indicate that it can return null so your code knows that it needs to deal with potential null references. Are you seeing a null reference somewhere in the frameworks code?

At this time we can't throw as that would be a breaking change and we're happy with the current behavior (logging).

**Comment by brumlemann** [comment]
> At this time we can't throw as that would be a breaking change and we're happy with the current behavior (logging).

The central tenant in structured error handling is that you should not catch an exception if you cannot handle it. We are not happy with libraries that brake this tenant and we would very much prefer libraries that throw on uncontrollable exceptions.

Feel free to log it, but then (re)throw if you cannot handle. We would be very happy with a breaking change in Microsoft.AspnetCore.Mvc if that meant that all occurrences of 

`catch(Exception ex)
{
_logger.Log();
// Leaving it to the caller to handle the null value no matter what kind of bad things happen.
// Will spread to a much later stage in the code making it really hard to debug
return null; 
}`

where exchanged for 

`catch(Exception ex)
{
_logger.Log();
// Uncontrollable error. Something bad happened. Don't know what.
// Fail fast and make sure no null values propagate further down the stream to confuse the situation.
// Give the full stack trace and underlying exception message
throw;
}`

as a pattern. It would be exemplary to the .Net community.

Furthermore, the underlying code is doing reflection, which makes the error an uncontrollable implementation error (committed by me for sure in this case because I wrote the code for the type). Such an error can only be handled properly by a developer (me in this case) sitting down to fix the code for that type (i.e. the type that a serializer couldn't be create for).

 >Are you seeing a null reference somewhere in the frameworks code?
 
 Yes. We have our own override on XmlSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding), handle a few special cases ourselves and then leave the rest to base.WriteResponseBodyAsync(...). It's the latter that triggers a NullReferenceExpection when trying to create an XmlSerializer for the type and failing.
 
 The call stack is as follows.
 	Microsoft.AspNetCore.Mvc.Formatters.Xml.dll!Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.CreateSerializer(System.Type type) Line 145	C#
Microsoft.AspNetCore.Mvc.Formatters.Xml.dll!Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.GetCachedSerializer(System.Type type) Line 296	C#
Microsoft.AspNetCore.Mvc.Formatters.Xml.dll!Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.WriteResponseBodyAsync(Microsoft.AspNetCore.Mvc.Formatters.OutputFormatterWriteContext context, System.Text.Encoding selectedEncoding) Line 236	C#

Specifically, even though the faulty serializer is not cached, the null value is returned on https://github.com/dotnet/aspnetcore/blob/6c487dee63ada5cb4943973cd44a05df2dacb263/src/Mvc/Mvc.Formatters.Xml/src/XmlSerializerOutputFormatter.cs#L320

Luckily much of the infected code is protected virtual, so I will go ahead and fix it locally as it should have been.

This cost me a full day of debugging though :-(

**Comment by brumlemann** [comment]
I also see the comment

// We do not surface the caught exception because if CanWriteResult returns
// false, then this Formatter is not picked up at all.

So at least some consideration has been performed before creating the black hole. That's good, in a sense. But I am guessing it's just pointing to another problem. The fact of the matter I guess is that it **cannot write result**, because the serializer cannot be created...
