### ISSUE TITLE
Minimal Api doesn't work and throw Exception when project run

### ISSUE THREAD

**Issue by arminatwork** [dotnet/aspnetcore#37179]
Hi everybody.

I implement this code :

![bug](https://user-images.githubusercontent.com/68272602/135618937-941aa73d-61a1-455b-85ea-d4fc07f4744c.png)
 
when run my project throw Exception :

![bug](https://user-images.githubusercontent.com/68272602/135619232-bd87b85e-f355-442f-911a-37a4e7912775.png)

my project information is :

Framework version: latest version of dotnet 6 RC1.

CSharp language version : preview(10.0).

Visual Studio Version : 2022 preview 4.1

**Comment by davidfowl** [comment]
ExecutionEngineException sounds like something wrong in the runtime. Does it also happen when you create *any* project and run it?

**Comment by arminatwork** [comment]
> ExecutionEngineException sounds like something wrong in the runtime. Does it also happen when you create _any_ project and run it?

oh... I create a project with dotnet 6 latest preview version and I got above error(ExecutionEngineException)

**Comment by davidfowl** [comment]
So any project that you create has this problem?

**Comment by arminatwork** [comment]
> So any project that you create has this problem?

no, I have many project than has version is dotnet 3.1 and don't problem.
just my dotnet 6 RC1 version has error

**Comment by davidfowl** [comment]
@arminatwork Can you do 2 things:
1. Make a different .NET RC1 project, unmodifed and run it, does it have the same problem?
2. Put the .NET 6 RC1 project that has this problem on github and point to the repository

**Comment by arminatwork** [comment]
thanks @davidfowl.
I re-install dotnet 6RC1 SDK and problem solved.
I close this issue
