### ISSUE TITLE
Model validation. Different property name formats

### ISSUE THREAD

**Issue by iRumba** [dotnet/aspnetcore#37170]
### Describe the bug
Hi. I faced a strange behavior around model validation. 
When my model, posted as Json, is not valid, in model state i can see details with property name, for example "MyProperty".
But when model can't map from Json, JsonReader throws JsonException with Path, that starts with symbol "$". So, my property name will have name "$.myProperty". 

But i need unified output format. 

### To Reproduce
Create empty asp net application. 
Create api controller. 
Create some model with nullable number property and use RequiredAttribute above property.
Create controller method, that receive the model.
Run application.
Send request to the method with empty Json "{}" for raising Required validation filter.
In other browser (or other api testing app) tab send request to the method with property value, as string for raising parsing error.
Compare output property names from both tabs.

### Further technical details
- ASP.NET Core version .Net 5

**Comment by iRumba** [comment]
Also, when parsing raises error, in model state there is 2 properties insted of 1, First is method failed argument name.

so, if i have method

```
[HttpPost]
public IActionResult Post(MyModel myModelArgumentName)
{

}

public class MyModel
{
    [Required]
    public int? MyProperty { get; set; }
}
```
and the method receives { "myProperty" : "" }
I get 2 items in model state: "myModelArgumentName" and "$.myProperty".

but if the method receives { }
I get item "MyProperty".

How should I handle it?

**Comment by captainsafia** [comment]
@pranavkm Any thoughts on this?

**Comment by iRumba** [comment]
> With System.Text.Json, MVC reports JSON syntactical errors as-is which uses a json-path to represent the location of the error. With Newtonsoft.Json based formatters, MVC attempts to try and map these back to actual property paths, but there's a fair number of cases that it cannot map a property, or maps it incorrectly.
> 
> If it's pertinent to ensure that these paths are identical, you could consider authoring a action filter that transforms json-paths to a property path. The code that transforms the Newtonsoft.Json path is here in case it helps: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L333-L377

Of course, I can understand what path i see. Also, I can parse it programmatically. But this different pathes send to client by default! I must intercept "in box" response. It is strange.
