### ISSUE TITLE
StateHasChanged () does not work in Blazor server app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37193]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StateHasChanged--does-not-work-in-Blaz/1539193)._

---
Is this a bug?
https://blog.unikktle.com/blazor-server-%e3%81%ae%e7%94%bb%e9%9d%a2%e3%81%a7%e5%87%a6%e7%90%86%e4%b8%ad%e3%82%aa%e3%83%bc%e3%83%90%e3%83%bc%e3%83%ac%e3%82%a4%e3%82%92%e8%a1%a8%e7%a4%ba%e3%81%99%e3%82%8b/

While implementing the Blazor Server screen with .Net Core 5.0, the desynchronization of the DB processing did not work well by linking the DB processing using EFCore and the Blazor screen, and I was addicted to not displaying the "in-process overlay".
-StateHasChanged () is not resolved even if the number of execution points is increased.
・ Even if the O / R mapper is changed to Dapper instead of EFCore, the problem persists.
-Execute await Task.Delay (1); and forcibly return the thread to the screen to solve the problem.

---
#### Feedback Bot on 9/26/2021, 01:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
