### ISSUE TITLE
Blazor - cannot use layout from subdirectory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37196]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor---cannot-use-layout-from-subdirec/1534299)._

---
[severity:It's more difficult to complete my work]
1. Create new Blazor app (call it App) with server hosting model.
2. Add new folder under "App/Shared" and call it "Layouts"
3. Under newly created Layouts folder, create new Razor Component and call it: "NewLayout.razor":

```
@inherits LayoutComponentBase
<div class="container-fluid">
    @Body
</div>
```

4. Add `@using App.BlazorServer.Shared.Layouts`
5. In Pages folder create new page and git it this layout:

```
@layout NewLayout
@page "/SomePage"
```

Try to build it.
It should built, but the error occurs saying that NewLayout is unknown type. 
I didn't find any way to workaround this.

---
#### Feedback Bot on 9/21/2021, 09:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/22/2021, 01:11 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Your namespace in the `using` statement doesn't match the folder structure where the new layout is located. Did you try to fix it to match? If you are convinced that this is a framework issue and that you did get everything right but the issue still remains, please share a minimal repro project hosted in GitHub so that we can investigate this further.
