### ISSUE TITLE
'dotnet watch' add an arg to allow reloading in case of rude edits

### ISSUE THREAD

**Issue by vchirikov** [dotnet/aspnetcore#37190]
### Describe problem

I want to automate running `webpack watch` + `dotnet watch` via a C# (or Cake) program.
`dotnet watch` doesn't support `nointeractive` mode and always tries to interact with user:

https://github.com/dotnet/sdk/blob/3860d6e404bc7fc08ca55ca158fed212ccee12ad/src/BuiltInTools/dotnet-watch/HotReload/RudeEditPreference.cs#L34

I want to have an agrument to allow "rude edits" by default.

### Describe the solution you'd like

Add to `dotnet watch` an argument which can allow reload program in case of "rude edits"

**Comment by Blackclaws** [comment]
Definitely very annoying to have to work around this right now. We are deploying our applications into a kubernetes cluster and doign file sync via skaffold. We need to build our images in a way that works around this right now.

**Comment by syska** [comment]
Please please please get this fixed.

It has totally broken my workflow. I keep forgetting that I need to press 'a' to always restart when there is a rude edit.

Maybe also just a way to make it remember the answer.  For this API i can to always restart ... But for WASM app maybe i want another option.

**Comment by DavidShefcik** [comment]
+1

Trying to run my entire application stack in docker compose does not work because of the dialog coming up. There is no way for me to select an option while running it in docker compose so a CLI flag would be helpful.

**Comment by Craige** [comment]
This should definitely be an environment variable and/or flag. Hot reloading is awesome, but I'm continually having to re-boot my docker container for no reason.

With that said, considering the fiasco around getting hot reload in the CLI (ripped out at the last minute, only to be reinstated after community outrage), I imagine this isn't a huge priority for the project.

**Comment by rgwood** [comment]
Looks like a fix for this has been merged and backported to the upcoming .NET 6.0.2 release: https://github.com/dotnet/sdk/pull/23280/files

The behaviour will be configurable with the `DOTNET_WATCH_RESTART_ON_RUDE_EDIT` environment variable.

**Comment by TanayParikh** [comment]
Closing this out, thanks all.
