### ISSUE TITLE
Accepting HTTP Requests In Worker Service

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37195]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Accepting-HTTP-Requests-In-Worker-Servic/1489547)._

---
I see that worker services are now the cross-platform way to write what used to be windows services.  If I have a windows service that exposes an http endpoint, what is now the correct way to add that to my cross-platform worker service?

In other words, if my worker service is:

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using App.WorkerService;

using IHost host = Host.CreateDefaultBuilder(args)
    . ConfigureServices((hostContext, services) =>
    {
        services. AddHostedService<Worker>();
    })
    . Build();

await host. RunAsync();
```

Then, what is the correct way to add support for http requests?  I see many options online:
Simple Http service through HttpListener (.NET 2.0+)
SelfHosting based on WCF stack
Use ASP.NET HttpSelfHost to host WebAPI services (.NET 4.0+)
Use ASP.NET OWIN to host WebAPI services (. NET4.5 recommended by Microsoft) 

However, I also see that the OWIN option is considered deprecated.  What is the correct approach?

---
#### Feedback Bot on 7/29/2021, 02:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Brady Gaster [MSFT] on 9/30/2021, 11:08 AM: 

<p>Is your goal to accept arbitrary HTTP requests, or do you want to enable something more specific like a health check?</p>

---
### Original Solutions
(no solutions)

**Comment by bradygaster** [comment]
You have a few options here. You could swap out the generic host with a web host, or you could wire up an http host process on the generic host.  If you're after, specifically, code that demonstrates how to host an endpoint within a worker, we can provide that for you.
