### ISSUE TITLE
Improve Default Blazor WASM Loading Experience

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#37199]
Currently, when opening a Blazor Wasm app, the user sees `Loading...` till everything is downloaded and processed. 

Ideally, we'd provide an improved loading experience (ex. spinner, loading bar) which is neutrally themed. Users should still be able to easily replace it for their custom applications, but this allows us to provide a great basic alternative.

This loading experience is also the first thing end-users as well as prospective devs for Blazor Wasm would see when trying out a demo app. Consequently, a more visually engaging experience would be ideal. 

Accessibility should be a focus with this experience, ensuring screen readers are still able to convey the loading state.

I've seen users express concerns about this across various mediums in the past. Here are a couple of examples (though they're from blog posts providing guidance on how to have custom loading animations). 

> Until everything is loaded, it displays an ugly loading message:
https://www.meziantou.net/customizing-the-blazor-webassembly-loading-screen.htm

> It doesn't look great and it can be very easily fixed/enhanced.
https://www.neptuo.com/blog/2018/04/blazor-boot-screen/

**Comment by TanayParikh** [comment]
cc/ @danroth27, thoughts on this?

**Comment by danroth27** [comment]
We went with a vary minimal loading page because we expect that users will want to customize it anyway.

**Comment by papaja** [comment]
Please take into considerations and PWA flavor.

There is a (noticeable) period of time after "Loading..." is gone and before the real content is shown. It is much worse for overall UX than having plain "Loading...".

**Comment by TanayParikh** [comment]
Can be handled as a part of https://github.com/dotnet/aspnetcore/issues/40935

**Comment by TanayParikh** [comment]
> We went with a vary minimal loading page because we expect that users will want to customize it anyway.

@danroth27 thoughts on a loading spinner vs. loading screen with progress indicator (ex. 13/15 files / 87% loaded)?

cc/ @javiercn @mkArtakMSFT

**Comment by danroth27** [comment]
I lean towards keeping it simple and just having a spinner.

**Comment by cerasamson** [comment]
@danroth27 Do you have a specific design in mind or any UI resources that I should take a look at when creating the spinner?

**Comment by danroth27** [comment]
Nope :smile:. I think we want something simple, so that we can use it in both the empty template and the normal one. So something that's CSS only. No Bootstrap. I was thinking a simple donut spinner, maybe with the loading text below it. Maybe pick colors from the existing template palette. We want something simple and super fast to load.

**Comment by javiercn** [comment]
@cerasamson in addition to what dan suggested, feel free to come up with more than one option and then we can decide between the candidates.
