### ISSUE TITLE
Throws null exception on an integer that has actually been initialized

### ISSUE THREAD

**Issue by talldaniel** [dotnet/aspnetcore#37207]
Code worked as expected until I updated to the latest version of Visual Studio 2019.  Now for one component, which is a switching component, it is throwing an exception for a null value for an integer.
As you can see from the image there is not a lot of code here, and (it shouldn't matter) the parameter has been initialized and shows as a 1.
I have ten of these selector type components and only this one is failing.  It also fails on the Azure app when published.

![image](https://user-images.githubusercontent.com/5903328/95096007-9b20ef80-06e0-11eb-8b37-8dc6a3de798f.png)

**Comment by NTaylorMullen** [comment]
@allisonchou this would be compiler
