### ISSUE TITLE
Should ConfigureWebDefaults be removed from CreateDefaultBuilder?

### ISSUE THREAD

**Issue by bdgit** [dotnet/aspnetcore#37219]
Here is the line I think should be removed:
https://github.com/dotnet/aspnetcore/blob/cd8e89002761afba120ae1523b4311d129ac23c0/src/DefaultBuilder/src/WebHost.cs#L210

While reviewing this section of documentation, I was looking into the differences between non-HTTP workload and HTTP workload:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#set-up-a-host

For non-HTTP, it is basically:
`Host.CreateDefaultBuilder(args)`

For HTTP, it is basically:
`Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(...)`

Looking at ConfigureWebHostDefaults, it is calling ConfigureWebDefaults:
https://github.com/dotnet/aspnetcore/blob/cd8e89002761afba120ae1523b4311d129ac23c0/src/DefaultBuilder/src/GenericHostBuilderExtensions.cs#L33

That makes sense.  What I don't understand it why it is called from CreateDefaultBuilder too.  Should it be removed from CreateDefaultBuilder?  (or am I missing something?)

---

This looks to be a similar discussion around HostBuilder:
https://github.com/dotnet/aspnetcore/issues/32485

**Comment by davidfowl** [comment]
There are 2 methods for configuring the webhost:

`ConfigureWebHostDefaults` and `ConfigureWebHost`. If you don't want the defaults, you call the [latter method](https://github.com/dotnet/aspnetcore/blob/cd8e89002761afba120ae1523b4311d129ac23c0/src/Hosting/Hosting/src/GenericHostWebHostBuilderExtensions.cs#L22)

**Comment by bdgit** [comment]
Are you saying for non-HTTP, the documentation should be?
`Host.CreateDefaultBuilder(args).ConfigureWebHost(...)`

---

I'll continue exploring this.  At the moment, I am still confused why:
`Host.CreateDefaultBuilder` is calling `ConfigWebDefaults` on L210

Especially when the `ConfigureWebHostDefaults` is handling/calling `ConfigWebDefaults`.

---

Am I following the code wrong for HTTP?
`Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(...)`
as
`CreateDefaultBuilder` does appsettings/logging/env/etc... and calls `ConfigureWebDefaults` for Kestral/IIS/Routing/etc....
then
`ConfigureWebHostDefaults` simply calls `ConfigureWebDefaults` again

**Comment by davidfowl** [comment]
> Are you saying for non-HTTP, the documentation should be?

No, I'm saying that by default people should be using ConfigureWebHostDefaults, more advanced users who know what they are doing and want more control can use ConfigureWebHost.

**Comment by davidfowl** [comment]
> Host.CreateDefaultBuilder is calling ConfigWebDefaults on L210

It doesn't. 

`WebHost.CreateDefaultBuilder ` is not the same as `Host.CreateDefaultBuilder`

**Comment by bdgit** [comment]
Thank you David.  The confusion here turned out to be the two CreateDefaultBuilder extensions.  As you noted.

Looking back, I haven't considered or used WebHost since pre-netcore3.  Totally forgot it even existed and overlooked when I search github for CreateDefaultBuilder.

And, yes, ConfigureWebHostDefaults gets dumped early in projects for a more focused configuration.

Once again, thank you for the responses... on a weekend no less.

---

For others who find themselves here.

Here is the link to the `Host` CreateDefaultBuilder.  Be sure to follow its ConfigureDefaults for what it sets up.
https://github.com/dotnet/runtime/blob/87b928ab37d2b1fa2b7aeec93a76190e23a0bf61/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L53

And from the Migrations to 3.0 documentation.  It talks about replacing WebHost with Host.
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#hostbuilder-replaces-webhostbuilder
