### ISSUE TITLE
StaticFileMiddleware can generate the same ETag after a file modification

### ISSUE THREAD

**Issue by GSPP** [dotnet/aspnetcore#37232]
Currently, `StaticFileProvider` uses the last modified date and length of files to generate an ETag. The two values are xored. This means that an unfortunate change in last modified date and length at the same time could generate the same xored bits. This would lead clients to mistakenly keep using old content indefinitely.

This is not entirely unlikely since changes in time and changes in length both mostly affect the lower bits of their representation.

https://github.com/dotnet/aspnetcore/blob/cd8e89002761afba120ae1523b4311d129ac23c0/src/Middleware/StaticFiles/src/StaticFileContext.cs#L126-L127

**Comment by Tratcher** [comment]
In theory yes, but we've never seen this happen in practice. Have you?

**Comment by GSPP** [comment]
This is a theoretical observation. However, such design choices lead to hard to diagnose Heisenbugs. Also, end-users will rarely complain and just hit F5.

**Comment by Tratcher** [comment]
Yeah, the lack of reports here and the low impact of the issue if it were hit have made this a low priority investigation.

Those alternatives sound interesting, can you work up some detailed examples to show how they'd be better in practice?

**Comment by GSPP** [comment]
The issue can be demonstrated like this:

```
var dt1 = DateTime.UtcNow;
var dt2 = dt1.AddMinutes(1);

Console.WriteLine($"Ticks 1: {dt1.Ticks:X8}");
Console.WriteLine($"Ticks 2: {dt2.Ticks:X8}");

var length1 = 1000;
var length2 = length1 ^ (dt1.Ticks ^ dt2.Ticks);

Console.WriteLine($"Hash 1: {dt1.Ticks ^ length1:X8}");
Console.WriteLine($"Hash 2: {dt2.Ticks ^ length2:X8}");

Console.WriteLine($"File version 1: Date = {dt1}, Length = {length1}");
Console.WriteLine($"File version 2: Date = {dt2}, Length = {length2}");

/*
Ticks 1: 8D988A608BC19D8
Ticks 2: 8D988A62C7F5FD8
Hash 1: 8D988A608BC1A30
Hash 2: 8D988A608BC1A30
File version 1: Date = 06.10.2021 08:48:14, Length = 1000
File version 2: Date = 06.10.2021 08:49:14, Length = 616777192
*/
```

The file length would need to change from 1000 bytes to 600MB at the time I ran this code. The results vary a lot.

<hr>


Looking at this further, I'm afraid that `HashCode.Combine` doesn't work directly because it only produces a 32 bit output. That will definitely lead to sporadic collisions.

Concatenating the values would increase response size so that's not a no-brainer.

I understand this is a low-priority issue. The following is a quick fix with low risk that should take care of any practical concerns:

    //There is a risk that a change in both modified time and file length would leave the xor of
    //both values unchanges. This is not entirely unlikely since both values mostly change in the
    //lower bits. Rotate one of the values so that the lower bits mix with the higher bits.
    //This makes collisions less likely but not impossible.
    long etagHash = _lastModified.ToFileTime() ^ BitOperations.RotateLeft(_length, 32);

**Comment by Tratcher** [comment]
> The file length would need to change from 1000 bytes to 600MB at the time I ran this code.

Ha! So you've made me realize that the size and time are already partially shifted which makes conflicts less likely. Let's walk through it.

Here's all the relevant code:
https://github.com/dotnet/aspnetcore/blob/d847549c9ba95e74049ae19edd460c7b59f0be41/src/Middleware/StaticFiles/src/StaticFileContext.cs#L120-L127

The time is truncated to seconds, but then converted to 'file time' where 1s == 10,000,000 ticks. That means that a file size would have to change ~10mb per second before it would have a chance of conflicting with the time. A minute of difference is 600,000,000 ticks or ~572mb as you calculated, an hour is 36,000,000,000, ~33gb, and it only gets worse from there.

If the file size were shifted left by 32 bits then 1 byte of file size change would equal about 7 minutes of time change and 1kb ~= 30 hours. That seems more likely to cause a conflict, not less.
