### ISSUE TITLE
System.Globalization - RegionInfo.CurrentRegion

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#37235]
I'm not sure I'm in the right place, but...

I am physically in Brazil and changed my browser language to en-US.

so when I access `RegionInfo.CurrentRegion.Name`, it brings me as a result `US`.

**Comment by javiercn** [comment]
@drma-dev thanks for contacting us.

I imagine that property reflects the browser language/locale. It's not going to do anything fancy like use geolocation or a similar API to figure out where you are physically present. I imagine the behavior is by design.
