### ISSUE TITLE
Blazor Server custom auth without Identity

### ISSUE THREAD

**Issue by Bo0m21** [dotnet/aspnetcore#37249]
Hello dear friends! When working with the blazor server, we experience difficulties when we need to do custom authorization of the client without using Identity. I have also found many articles on stackoverflow with the note that many users cannot use JWT authentication on razor pages. The only problem with use is to save the token on the user side, this works great for wasm but it doesn't work when using Blazor Server with ServerRendering.

### Problem
For example, the user entered his username and password and pressed the button and we have several options to do this.
1 - Use IJSRunrime but problems occur later when reading. When the user enters the site again, we need to read his LocalStarage in AuthenticationStateProvider, but we cannot do this because we are using ServerRendering, and the error "JavaScript interop calls cannot be issued at this time"
2 - We cannot set cookies in the request, as we could in the same MVC, since we receive the error "headers are read-only, response has already started"

### And so on
Now for me as a developer it is not entirely clear how best to do authorization on the server without hooks and crutches. I think that many developers will support me in this problem, since there are a lot of questions about saving and custom authorization without using identity.

If necessary, I can prepare a template for the test in which this problem will be.

**Comment by javiercn** [comment]
@Bo0m21 thanks for contacting us.

Our default Blazor server template cookies for authentication. Either backed by Identity for account/credential management or by a third-party provider like AAD, AAD B2C or any of the other OpenID/Social providers that we offer.

It's not clear for us what you are trying to achieve, but if it involves some sort of "custom authentication" system within Blazor Server, that's not something we recommend at the time nor something we plan to provide official guidance on.

**Comment by Bo0m21** [comment]
> @Bo0m21 thanks for contacting us.
> 
> Our default Blazor server template cookies for authentication. Either backed by Identity for account/credential management or by a third-party provider like AAD, AAD B2C or any of the other OpenID/Social providers that we offer.
> 
> It's not clear for us what you are trying to achieve, but if it involves some sort of "custom authentication" system within Blazor Server, that's not something we recommend at the time nor something we plan to provide official guidance on.

Could you send me an example for Blazor server cookie auth?

I'm trying to get custom authorization to work after which it is necessary to save cookies or save a token on the user's side, but this does not work for the reasons I wrote above.

**Comment by javiercn** [comment]
> Could you send me an example for Blazor server cookie auth?

Create a new template with individual auth or create a template with AAD or AAD B2C. In general blazor server works in the same was as described [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-5.0&tabs=visual-studio)

**Comment by javiercn** [comment]
> I'm trying to get custom authorization to work after which it is necessary to save cookies or save a token on the user's side, but this does not work for the reasons I wrote above.

It's not clear to us what/how are you trying to do this (there's not enough information/details).

**Comment by Bo0m21** [comment]
> > I'm trying to get custom authorization to work after which it is necessary to save cookies or save a token on the user's side, but this does not work for the reasons I wrote above.
> 
> It's not clear to us what/how are you trying to do this (there's not enough information/details).

As I already wrote, I need to save information about his authorization on the user's side. This can be done in several ways, but none of them work. If we use IJSRunrime, then we cannot read the data when we received a request, if we want to write the data in cookies, then we cannot do this because the response has already been started.

If you need I can make a test case in short there will be this problem.

**Comment by Bo0m21** [comment]
> Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

Thanks for your answers, but I would like to get some advice in the documentation on how this can be done on the Blazor Server side without reloading the SPA.

For this, I created a separate [thread on Stackoverflow](https://stackoverflow.com/questions/69439850/blazor-server-auth-with-jwt), because many people are faced with this problem when logging in, and there is no good answer for it yet.
