### ISSUE TITLE
can you add a new component to body/div in Blazor ?

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#37253]
Is it possible to do something like this: 
```
    private async Task onBtnClick()
    {
        var c1 = new Comp1();
        c1.Title = "abc";

       // add c1 to body or a div
       someDiv.append(c1);

        await c1.Method();
    }
```

**Comment by javiercn** [comment]
@omuleanu you can't instantiate components directly.

The framework is responsible for the lifetime of components. If you want to get a reference to a component instance you can use `@ref` for that, but that's it.

**Comment by omuleanu** [comment]
@javiercn the framework could provide a way for us to instantiate components and add them to other container components like div/RenderFragment

**Comment by javiercn** [comment]
@omuleanu as I mentioned, the framework is responsible for the lifetime of the components, and decides when they are created, when they are destroyed and when they need to receive new parameters. That is a fundamental design aspect of Blazor and we don't plan to change it.

**Comment by omuleanu** [comment]
@javiercn what if instead of `new` we would use a framework `Create` method and instead of just setting `c1.Prop` we would pass a builder `Action` or `Func` that you could execute again each time you decide to create the component, but at the same time we could call this `Create` method each time we need to lazily add components
