### ISSUE TITLE
ReactRedux project template npm install EJSONPARSE failure

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#37287]
### Describe the bug

ReactRedux project template fails to build out of the box.

### To Reproduce

Install .NET 5.0.402 SDK
dotnet new reactredux -o test
cd test
dotnet build

Build fails during npm step:

```
  Restoring dependencies using 'npm'. This may take several minutes...
  npm ERR! code EJSONPARSE
  npm ERR! path test/ClientApp/package.json
  npm ERR! JSON.parse Unexpected token "}" (0x7D) in JSON at position 1580 while parsing near "...h\": \">=4.17.21\",\r\n  },\r\n  \"browserslist\"..."
  npm ERR! JSON.parse Failed to parse JSON data.
  npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     ~/.npm/_logs/2021-10-05T15_05_14_588Z-debug.log
test.csproj(30,5): error MSB3073: The command "npm install" exited with code 1.

```

Looks like an extra comma in the package.json after the lodash version causes NPM to fail. Removing this and dotnet build works.

https://github.com/dotnet/aspnetcore/blob/49f14b8e0d409c1ad9c38585c77676a85f2336b3/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/ClientApp/package.json#L55

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.402/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1
```

**Comment by javiercn** [comment]
Fixed here https://github.com/dotnet/aspnetcore/commit/4e47fd8f759dbdeeadadf689cd4e60c614932ae3#diff-9f2c6d0b97079fb2e1b7a51298aeec41ee137410d3ab42bade78fcca7666a8a4R50
