### ISSUE TITLE
Drawn controls support for Blazor

### ISSUE THREAD

**Issue by Martinn2** [dotnet/aspnetcore#37281]
### Is your feature request related to a problem? Please describe.
We would like to create drawn controls, that can be shared across all platforms (MAUI platforms + Blazor). Ideally we would like to draw on canvas on the whole screen, so no HTML, CSS is needed. Layouts (grid, flex etc.) would be included in the library. 

In .NET MAUI there is already an experimental project targeting the problem (repo here: https://github.com/dotnet/Microsoft.Maui.Graphics.Controls).
In Blazor, Controls would be drawn using SkiaSharp.

**Comment by javiercn** [comment]
@Martinn2 thanks for contacting us.

In the context of Blazor we would recommend authoring a Blazor component as it will run in all the platforms you mentioned. It's not clear to me that we are likely to pursue this in the future, however it could potentially be built on top of the existing framework.

Drawn controls probably present significant challenges and the programming model is unlikely to be a good fit for Blazor well established patterns. It is likely that in this case, something like UNO might be a better fit for your scenarios.
