### ISSUE TITLE
Blazor issue with generics ?

### ISSUE THREAD

**Issue by Continuitis** [dotnet/aspnetcore#37295]
Hello,

I tried to create a componenet with generics and constraint but I get a  CS0246 error even with usings...
I'm using .net 6 rc1
My component:
``` c#
@typeparam TDtoItem where TDtoItem : Common.Model.Dto.EntityDto.BaseEntityDto
@typeparam TRepository where TRepository : Ui.Repositories.IRepository<TDtoItem>

@if (isLoading)
{
    <SpinnerStartRoundCircle/>
}
else
{
    @ElementTemplate(item)
}

@code {
    [EditorRequired]
	[Parameter] public TRepository Repository { get; set; }
    [EditorRequired]
    [Parameter] public RenderFragment<TDtoItem> ElementTemplate { get; set; }
    [SupplyParameterFromQuery]
	[Parameter] public Guid? Id { get; set; }
    [Parameter] public EventCallback<TDtoItem> InitAsync { get; set; }
    bool isLoading = true;
    private TDtoItem? item = null;
    protected override async Task OnInitializedAsync()
    {
        if (Id.HasValue)
        {
            item = await Repository.GetAsync(Id.Value);
        }
        else
        {
           @* item = new();*@
        }
        if (InitAsync.HasDelegate)
        {
            await InitAsync.InvokeAsync(item);
        }
        isLoading = false;
    }

}

```

My _impots.cs has also the usings defined...
When I'm using my generic component I get:
 error CS0246: The type or namespace name 'IRepository' could not be found (are you missing a using directive or an assembly reference?)
 error CS0246: The type or namespace name 'BaseEntityDto' could not be found (are you missing a using directive or an assembly reference?) 

I can't figure out what is wrong... Any clue?

**Comment by TanayParikh** [comment]
Hello @Continuitis. Thanks for contacting us. Can you please confirm if this is via command line or Visual Studio (if VS, what version?). Also, please specify the version of .NET you're utilizing.

Also, can you please provide a **minimal** repro project publicly hosted on GitHub to allow us to investigate further.

**Comment by Continuitis** [comment]
Hi @TanayParikh,
I'm using the last .Net 6 version (rc1) - I tried to compile via both VS2022 & command line.
Here is a repo (dirty) that reproduce the error: https://github.com/Continuitis-fr/Bug

Thanks for your help!

**Comment by TanayParikh** [comment]
Thanks @Continuitis for the repro. I created a new wasm project, `dotnet new blazorwasm -o newproj`, and added the class library reference. I then copied over `NewPage.razor` to `newproj/Pages/NewPage.razor`. Everything is building as expected. Looks to be some sort of config issue in your `Bug` project.

**Comment by Continuitis** [comment]
Yes I know that removing the usage of NewPage in index make the build working but the goal is to use it :)
I tried to remove the Context but the issue is still here :/

**Comment by Continuitis** [comment]
Mhhh I fixed it:
When I call NewPage, I have to pass the types explicitly:
```
<NewPage TRepository="MyRepo" TDtoItem="MyDtoItem" Repository="myRepo">
```

Thanks for the help!
