### ISSUE TITLE
Document pattern for prerendering head section

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37293]
Currently, prerendering the `<head>` involves a nonobvious rendering order dependency, where you need your `<App>` to render before your `<HeadOutlet>`. In the default project template we make it work by a nonobvious trick of deferring the `<head>` rendering by putting it into a `_Layout.razor`.

People creating their own application won't figure this out, nor be able to reason about why a more natural app structure doesn't work.

Ideally we'd make it work better, but in the meantime, should at least have some docs to point people at.

**Comment by TomJD** [comment]
@Bartmax Hey, I see you have come across the same problem and manage to fix it. Could you by chance share a minimal repo that is working ? I cannot get it to work on my side: Blazor WASM Pre-rendered on NET 6.0

Contents of the `_Host.cshtml` are in the `_Layout.cshtml`. On DevTools it is rendering, but not on `view-source`.

Or, if it is easier, this is my `_Host` file

```
@page "/"
@{
    Layout = "_Layout";
}
```

And this is my `_Layout` file (some code removed for brevity)

```
@using Microsoft.AspNetCore.Components.Web
@namespace BlazorApp1.Server.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Globalization

<!DOCTYPE html>
<html lang="@CultureInfo.CurrentCulture.TwoLetterISOLanguageName">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <base href="~/" />
    <component type="typeof(HeadOutlet)" render-mode="WebAssemblyPrerendered" />
</head>
<body>
        <component type="typeof(BlazorApp1.Client.App)" render-mode="WebAssemblyPrerendered" />

    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="/" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```

**Comment by Bartmax** [comment]
Move this:

<component type="typeof(BlazorApp1.Client.App)" render-
mode="WebAssemblyPrerendered" />

To your _Host file. 
On November 9, 2021, Github ***@***.***> wrote:
> @Bartmax <https://github.com/Bartmax> Hey, I see you have come across
> the same problem and manage to fix it. Could you by chance share a
> minimal repo that is working ? I cannot get it to work on my side:
> Blazor WASM Pre-rendered on NET 6.0
>
> Contents of the _Host.cshtml are in the _Layout.cshtml. On DevTools it
> is rendering, but not on view-source.
>
> Or, if it is easier, this is my _Host file
>
> @page "/" @{ Layout = "_Layout"; }
> And this is my _Layout file (some code removed for brevity)
>
> @using Microsoft.AspNetCore.Components.Web @namespace
> BlazorApp1.Server.Pages @addTagHelper *,
> Microsoft.AspNetCore.Mvc.TagHelpers @using System.Globalization
> <!DOCTYPE html> <html
> ***@***.***"> <head>
> <meta charset="utf-8" /> <meta name="viewport" content="width=device-
> width, initial-scale=1.0, shrink-to-fit=no" /> <base href="~/" />
> <component type="typeof(HeadOutlet)" render-
> mode="WebAssemblyPrerendered" /> </head> <body> <component
> type="typeof(BlazorApp1.Client.App)" render-
> mode="WebAssemblyPrerendered" /> @RenderBody() <div id="blazor-error-
> ui"> <environment include="Staging,Production"> An error has occurred.
> This application may no longer respond until reloaded. </environment>
> <environment include="Development"> An unhandled exception has
> occurred. See browser dev tools for details. </environment> <a
> href="/" class="reload">Reload</a> <a class="dismiss">🗙</a> </div>
> <script src="_framework/blazor.webassembly.js"></script> </body>
> </html>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/aspnetcore/issues/37293#issuecomment-
964244000>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAZ23LJK5XX7A4XNAMXA7U3ULE267ANCNFSM5FMEO4RA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by SteveSandersonMS** [comment]
Documented at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly#prerendering-configuration
