### ISSUE TITLE
Blazor JS interop: Provide a way to better control the JSON.stringify() process 

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#37312]
### Is your feature request related to a problem? Please describe.
As part of writing JS library wrappers for Blazor, I often find myself needing to invoke Javascript functions from .Net that return complex objects (large objects, lots of functions, cyclic references, etc). Since these are 3rd-party libraries, I don't have control over the objects returned. The `JSON.stringify()` calls used internally in JS interop choke up on these complex objects, forcing me to write extra code on the JS side to massage the objects before they are passed to the .Net side.

### Describe the solution you'd like
I would like a way to influence the stringify process from .Net. For instance passing my own string array "replacer" argument to stringify, to be used as an allowlist, as described here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

At the moment Blazor is already passing its own replacer function for internal purpose. It would be excellent if I could hook up my own allowlist to this call.

UPDATE: Alternatively, or in addition to the above, a built-in option to eliminate circular references would be very welcome.

**Comment by javiercn** [comment]
@user72356 thanks for contacting us.

This is not an area where we plan to make changes in the near future. We encourage folks to keep the serialization boundaries between .NET and JS simple and coarse and stay away from marshalling large and complex objects back and forth.

If you insist on going this route, you can serialize your payload as a byte array (UInt8Array) and use that when performing the interop call, we'll marshal it efficiently and you'll get full control over the serialization and deserialization process.
