### ISSUE TITLE
Improve missing database experience for SPA apps 

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37324]
Repro:

 * Install .NET SDK 6.0.100-rtm.21505.64
 * Install VS Version 17.0.0 Preview 5.0 [31803.31.main]
 * File -> New project, choose ASP.NET Core with React
     * ... with Individual Auth
 * Ctrl+F5 to start it running
 * In the browser, click *Login*

Expected:

 * Something like a login prompt

Actual:

![image](https://user-images.githubusercontent.com/1101362/136234082-fe6fc5c1-b99a-4670-b474-18572939183c.png)

Based on the console output, this is probably just because the DB hasn't been created yet, but people don't have an easy way to either find that out or know how to fix it.

```
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "aspnet-MissionLog-53bc9b9d-9d6a-45d4-8429-2a2761773502" requested by the login. The login failed.
      Login failed for user 'username'.
         at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
```

Update: Yes, running `dotnet ef database update` fixes it. But still, we should show the UI in the browser that prompts the developer to apply the migrations.

**Comment by pranavkm** [comment]
Triage: For 6.0, let's document this as known limitation. 

For 7.0, we can consider adding some tooling or templating. Alternatively we could consider putting the database creation in the project template.

@adityamandaleeka / @HaoK this is a Identity experience concern, could you look at this?

**Comment by blowdart** [comment]
Oh how odd. Yea, documentation given this late stage, maybe we fix early in 7 and backport?

**Comment by javiercn** [comment]
@blowdart @HaoK I think this is something we should actually fix. I remember afterwards that the issue here is caused by Identity Server not using our development key during development and trying to use a key from the database.

**Comment by HaoK** [comment]
For context, why do we not just let it use the database to store the key, they would still need a database to login the user right?  Isn't a database required eventually anyway for the fetch/login flow to work?

**Comment by HaoK** [comment]
Can you point to the relevant sections in the doc that you are referring to so I can try it out?

**Comment by javiercn** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0#example-deploy-to-a-non-azure-web-hosting-provider
