### ISSUE TITLE
[SignalR] Initial ping is not guarded with connection lock

### ISSUE THREAD

**Issue by wegylexy** [dotnet/aspnetcore#37340]
### Description
It usually (but not always) throws when flushing buffer segments to send a SignalR hub invocation message over named pipe client stream.
- Managed Test: [wegylexy/SignalRTunnel/.../src/Test/Test.cs#L145](https://github.com/wegylexy/SignalRTunnel/blob/177e95c486bccaae09cb2d7a44dada23d18a401a/src/Test/Test.cs#L145)
- NativeAOT Test: [wegylexy/SignalRTunnel/.../src/Native/Connection.cs#L145](https://github.com/wegylexy/SignalRTunnel/blob/177e95c486bccaae09cb2d7a44dada23d18a401a/src/Native/Connection.cs#L145)

Coincidentally, they are both line 145 in my code.

Usually:
```
  Message: 
    System.ArgumentNullException : Value cannot be null. (Parameter 'array')

  Stack Trace: 
    TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
    BufferSegment.ResetMemory()
    StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
    HubConnection.SendHubMessage(ConnectionState connectionState, HubMessage hubMessage, CancellationToken cancellationToken)
    HubConnection.InvokeCore(ConnectionState connectionState, String methodName, InvocationRequest irq, Object[] args, String[] streams, CancellationToken cancellationToken)
    HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
    ForceAsyncAwaiter`1.GetResult()
    HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
    ...
```
Rarely:
```
  Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
    StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
    HubConnection.SendHubMessage(ConnectionState connectionState, HubMessage hubMessage, CancellationToken cancellationToken)
    HubConnection.InvokeCore(ConnectionState connectionState, String methodName, InvocationRequest irq, Object[] args, String[] streams, CancellationToken cancellationToken)
    HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
    ForceAsyncAwaiter`1.GetResult()
    HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
    ...
```
#### Stack reference sources
- [dotnet/runtime/.../TlsOverPerCoreLockedStacksArrayPool.cs#L130](https://github.com/dotnet/runtime/blob/v6.0.0-rc.1.21451.13/src/libraries/System.Private.CoreLib/src/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L130)
- [dotnet/runtime/.../BufferSegment.cs#L73](https://github.com/dotnet/runtime/blob/v6.0.0-rc.1.21451.13/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/BufferSegment.cs#L73)
- [dotnet/runtime/.../StreamPipeWriter.cs#L313](https://github.com/dotnet/runtime/blob/v6.0.0-rc.1.21451.13/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeWriter.cs#L313)
- [dotnet/aspnetcore/.../HubConnection.cs#L868](https://github.com/dotnet/aspnetcore/blob/v6.0.0-rc.1.21452.15/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L868)

### Configuration

.NET 6 RC1 on Windows 10 (21390) x64, no matter managed or NativeAOT

### Other information

Server can invoke methods on client via named pipe. It is just client that usually breaks.

Managed and native versions serialize hub invocation arguments differently. Managed version uses official package. Native version uses custom C++ code. Nonetheless, they get written to the buffer successfully, until flushing breaks it.

**Comment by davidfowl** [comment]
Then use a cancellation token?

**Comment by wegylexy** [comment]
The JSON handshake seems to always succeed, but then my hub invocation randomly fails with one of the exceptions above. It has nothing to with abort/dispose yet at that point.
- JSON or MessagePack does not matter.
- `PipeOptions.WriteThrough` or not does not matter.

It never throws for `Nerdbank.Streams.FullDuplexStream`.

**Comment by wegylexy** [comment]
@BrennanConroy Adding `await Task.Delay(1)` between `await client.StartAsync()` and `await client.InvokeAsync(...)` prevents the issue, but not `await Task.Yield()` nor 16 consecutive yields.
Why would the client have to wait a millisecond after handshake completes before invoking the first hub method?

**Comment by wegylexy** [comment]
Ignoring the flush failure and trying again right away results in a new exception (if not hanging):
```
Message: 
    System.Collections.Generic.KeyNotFoundException : No invocation with id '1' could be found.

  Stack Trace: 
    IInvocationBinder.GetReturnType(String invocationId)
    MessagePackHubProtocolWorker.CreateCompletionMessage(MessagePackReader& reader, IInvocationBinder binder)
    MessagePackHubProtocolWorker.ParseMessage(MessagePackReader& reader, IInvocationBinder binder)
    MessagePackHubProtocolWorker.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
    MessagePackHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
    HubConnection.ReceiveLoop(ConnectionState connectionState)
    HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
    ForceAsyncAwaiter`1.GetResult()
    HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
```

**Comment by wegylexy** [comment]
I've finally got it working with NativeAOT. It requires an even longer delay between handshake completes and first invocation.
See [wegylexy/SignalRTunnel/.../src/NativeTest/main.cpp#L68](https://github.com/wegylexy/SignalRTunnel/blob/1710f702da535d547ea4addce46640ab0df27b81/src/NativeTest/main.cpp#L68) and [wegylexy/SignalRTunnel/.../src/Test/Test.cs#L313](https://github.com/wegylexy/SignalRTunnel/blob/1710f702da535d547ea4addce46640ab0df27b81/src/Test/Test.cs#L313).
Without the delay, it throws the same `System.ArgumentNullException : Value cannot be null. (Parameter 'array')`.

**Comment by davidfowl** [comment]
6.0 RTM not RC2

**Comment by wegylexy** [comment]
In [wegylexy/SignalRTunnel/commit/80c61c6d](https://github.com/wegylexy/SignalRTunnel/commit/80c61c6d038ca888ae55f28fc1e71535445f5b67), I make the NativeAOT client wait for the server to invoke first such that the race above is bypassed.
But now, with or without additional delay, the client randomly hangs on first invocation of hub method.
What could be blocking? Another race condition?

**Comment by wegylexy** [comment]
@BrennanConroy going through [dotnet/aspnetcore/.../src/HubConnection.cs](https://github.com/dotnet/aspnetcore/blob/v6.0.0-rc.1.21452.15/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs), every send is protected by the connection lock.

@davidfowl It never fails for `Nerdbank.Streams.FullDuplexStream`; no delay is required for the in-memory duplex pipe to pass all the test cases every time. It's just asynchronous named pipe streams as [tested again](https://github.com/wegylexy/SignalRTunnel/commit/5bc94a9b44fc677c81e1e21f2445dae4d00b75ac#diff-95e9c1252ce391fa15209eb523075f3aa64049776b81a20bc1b8d1d49d41be6b) that often fail to flush.
That's why I created this issue in [dotnet/runtime](https://github.com/dotnet/runtime) initially.

**Comment by wegylexy** [comment]
I see.
[.../HubConnection.cs#L455](https://github.com/dotnet/aspnetcore/blob/0199dcc4cdfd7b15a6c9b8b3b080e26517775532/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L455) does not wait for the ping to complete flushing, thus further `WriteAsync()` and `FlushAsync()` may overlap [L1820](https://github.com/dotnet/aspnetcore/blob/0199dcc4cdfd7b15a6c9b8b3b080e26517775532/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1820).
