### ISSUE TITLE
WebAssembly+Identity template app produces "failed to fetch" error

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37355]
* Use latest .NET 6 and VS2022
* Create a Blazor WebAssembly app with "hosted on ASP.NET Core" and "Authentication: Individual accounts"
* Run the app and sign in

Now on each page load see the console:

![image](https://user-images.githubusercontent.com/1101362/136411895-a5f7d4c7-3ced-4565-a156-1e04ce4bb43e.png)

The first four of them are equivalent to issue https://github.com/dotnet/aspnetcore/issues/37326, and the last one is a longstanding issue that we already had in 5.0 (it's the auth system creating an iframe that reloads the whole application, and that one is unable to request `blazor.boot.json`, which I *think* because we set `credentials:include` and something about default policy doesn't allow that within an iframe).

The fact that the errors with `/connect/checksession` are duplicated might be indicative of another separate bug. For some reason the iframe for `/connect/checksession` gets injected into the page twice:

![image](https://user-images.githubusercontent.com/1101362/136418438-8eabc460-777f-455b-8f21-6e812672748e.png)

Why would this be? (**Update**: After using the app for a bit longer, it seems we keep injecting the iframe more and more. There are 5 copies of it in my app now, each of which logs 2 errors. All the more reason to fix this.)

### Why the errors matter

These errors don't functionally break anything, but it's really hard for an app developer to make sense of the health of their code when they have to disregard a slew of framework errors that aren't their fault. It looks really bad. And there may be some cases when people have error telemetry that they'd get functional problems too.

### Separate concern

**There's very nearly a further and more serious bug but it looks as if we're avoiding it due to a lucky quirk of timing.** When the auth system reloads the initial HTML in an iframe, the browserlink and `aspnetcore-browser-refresh.js` scripts are also injected into that iframe. If the frame stayed alive for even a second longer, I *think* the `aspnetcore-browser-refresh.js` would try to connect to the hot reload socket endpoint, and then because only one connection is permitted to VS, it would terminate the connection from the main window. Then hot reload would simply not work at all. We're at risk of this problem starting to occur in the future if we change the order in which things load. This whole business of reloading the whole app in an iframe is very dangerous; we should try to come up with an alternative.

**Comment by pranavkm** [comment]
We'll use https://github.com/dotnet/aspnetcore/issues/37326 to track fixing the browser-refresh.js error.

**Comment by SteveSandersonMS** [comment]
@javiercn The error from our auth code happens because, when the app tries to load `blazor.boot.json`, it specifies `credentials: include`. This is seemingly no longer allowed from within the iframe. If this really is an issue that's only just started happening recently, we should consider harder whether we could fix it.
