### ISSUE TITLE
Stop using loose typing in a strongly typed language

### ISSUE THREAD

**Issue by chriskuech** [dotnet/aspnetcore#37368]
## Summary

Not sure if this is the correct forum to voice this complaint, but I see increasing use of loose typing across ASP.NET code.  If developers wanted loose typing, they would have chosen a loosely typed language; however, developers choose C# precisely because it is a statically typed language with all the benefits of static typing.

## Motivation and goals

* It is hard to reason about the relationship between a type and its generic type parameter when that relationship is not encoded in an interface.
* C# + VS has the best developer experience for navigating code and documentation.  This is entirely attributed to strict typing and breaks when dynamic typing is used.
* Dynamic typing needlessly pushes more errors from compile time to run time.
* Developers choose C# because it is statically typed.  If they don't like static typing, they would be using Python or JS.

## In scope

* No code generated by `dotnet new` should include dynamic typing.
* Documentation examples should at least include static typed implementations.
* If dynamic method names and method argument lists are deemed too critical for the C# roadmap, then at a minimum, interfaces should support specifying the pattern for a dynamically referenced method name and support specifying if method arguments are dynamic, so that these constraints are still statically defined and discoverable in an IDE.

## Out of scope

N/A

## Risks / unknowns

N/A

## Examples

* Startup
* Middleware

**Comment by davidfowl** [comment]
I don't think the dynamic names are an important thing to address. Those can solved by not using those esoteric features and using if statements instead.

**Comment by chriskuech** [comment]
> I don't think the dynamic names are an important thing to address. Those can solved by not using those esoteric features and using if statements instead.

Because `Startup` does not implement `IStartup` after running `dotnet new`, my perception is that this is an intended feature rather than an esoteric feature.  If users had to opt in by removing the `IStartup` constraint, my perception would be reversed.
