### ISSUE TITLE
Work with the runtime team to consume rate limiters in the BCL

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#37386]
Assess usage of Rate Limiting in the BLC

  -  Pipelines
  -  Channels
  -  Streams
  -  HttpClient

**Comment by rafikiassumani-msft** [comment]
We might need to come up with better scenarios for rate limiting in the BCL.

**Comment by adityamandaleeka** [comment]
Closing. This looks like the same as #32039
