### ISSUE TITLE
Rate Limiting for Yarp implementations

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#37387]
- Assess Rate limiting usage for Yarp
- Design a solution

**Comment by Tratcher** [comment]
This is unblocked by https://github.com/dotnet/aspnetcore/blob/a633e8821026868f180be736112f35e6f63159e8/src/Middleware/RateLimiting/src/EnableRateLimitingAttribute.cs

**Comment by Tratcher** [comment]
Tracked by https://github.com/microsoft/reverse-proxy/issues/1776.
