### ISSUE TITLE
Blazor WASM site flagged as malicious by Google Ads

### ISSUE THREAD

**Issue by Sipowiz** [dotnet/aspnetcore#37388]
Hi, i noticed the issue at hand has already been open [here](https://github.com/dotnet/aspnetcore/issues/21824) some time ago but this closed issue really doesn't provide any solution to the problem. So here it is again. 

The problem is as follows:
My actual Blazor WASM app is hosted at https://app.contoso.fi (no ASP Net Core, only static files). Backend is hosted at Azure.
My google ads for the app are pointing to my lander site at https://contoso.fi.
The lander is a Wordpress site and there are buttons on the site that users can use to navigate to the actual app.
My ads aren't running because Google has flagged the content of my site malicious.

I have contacted Google Ads support asking them to reconsider and the first reply was very generic message that really didn't help me at all sorting the issue. After asking for further information they replied:

> Hi Ville,
> 
> Thank you for your reply!
> 
> Here's what our dedicated specialist team found from contoso.fi:
> An executable file (eg: .exe) is being auto downloaded whenever an Ad is being clicked on and this is figured as a malicious behaviour by our system.
> Triggering an auto download is against Google Ads policies and is not allowed. You has to remove those triggers or delete the landing page which is being used for that particular Ad.
> Please find the below few links which are triggering a download
> 1. [removed for privacy]
> 2. https[:]//app[.]contoso[.]fi/_framework/AutoMapper[.]dll
> 3. https[:]//app[.]contoso[.]fi/_framework/AutoMapper[.]Extensions[.]Microsoft[.]DependencyInjection[.]dll
> 
> Once you remove them, I'd suggest re-uploading your ads for faster processing.
> Should you have any further questions or concerns related to Google Ads, feel free to simply reply to this email, I’m always happy to help.
> 
> I wish you an awesome day!

The start of the message is a bit misleading. There are no .dll or other executables being downloaded when user lands to the contoso.fi. This only happens when user moves to the actual app via the buttons. This also shows in the file listing provided. Files seem to reside in the subdomain and are .dll files that the actual app is using. I think the list is incomplete and only there for demonstrative purposes.

We are heavily invested in Blazor WASM so we would really appreciate any help on getting our ads running again.
It would be nice to have a dedicated documentation in MS Docs regarding Blazor WASM SEO and online ads.

Br. Ville

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by danroth27** [comment]
We will look at the Google Ads issue as part of https://github.com/dotnet/aspnetcore/issues/36978.
