### ISSUE TITLE
[Epic]: Rate/Resource Limiting

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#37380]
This issue is intended to track work items for Rate or Resource Limiting feature. 

- [x] #37382
- [x] #37381
	• Fixed windows
	• Sliding windows
	• Token bucket
	• Concurrency limiter
- [x] #37383
- [x] #37384
     • Review current implementation in aspnetlabs
- [x] #37385
~~[ ] #37386~~
              • Bounded Channels ?
- [x] #37387
- [x] #38306
~~[ ] #13295~~
~~[ ] #41861~~

### Additional information

https://github.com/dotnet/designs/blob/main/proposed/rate-limit.md#dotnetruntime-pocs

**Comment by halter73** [comment]
> One of the constant issues with most rate limiter implementations that i see is an innate assumption that it will only be used in traditional rest api scenarios and this severely limits it's usability.

Check out the work we're doing in the runtime repo to address non-web scenarios: https://github.com/dotnet/runtime/issues/65400

If you take a look at the rate limiting middleware sample in our .NET 7 preview 4 blog post, you can see that `PartitionedRateLimiter.Create<TResource, TPartitionKey>()` can take any resource, not just `HttpContext`. `HttpContext` makes sense as a `TResource` for rate limiting requests, but for the graphql it might be `GraphQL.ExecutionOptions` or something else.

`PartitionedRateLimiter.Create` allows you to easily define and apply different rules based on whatever aspect of `TResource` is important to the application. Maybe it's the user that's making a request, or the id of the resource, or some combination of these.

If this interests you @brijeshb, I recommend trying this API out! It's already available in .NET 7 Preview 4. You can see how we use this API for middleware in this [AWESOME video](https://www.youtube.com/watch?v=gMTvNnKt3AA) by @Elfocrash

**Comment by brijeshb** [comment]
Hey Stephen,

Coincidently, that is the exact video that led me to come by :), but I think in my quick skim of that video, I had assumed that HttpContext is the only thing that can be injected in.

Glad to see the work happening in runtime, I think we'll be able to give it a realistic shot as soon as we get to prototype it for the non-http scenarios with a distributed store backing it, and maybe take it to prod a month or two after 7's release.

For the distributed scenario, I have a hypothesis that an implementation that relies on either being purely in a backing store like redis / or some other non-volatile storage may not be sufficient at scale. And that we could potentially reduce latency overhead of throttling further by splitting the tracking by having local counters that update the centralized store only when they cross some threshold or periodically.

Curious if you've had any discussions / brainstorms along these lines.

**Comment by halter73** [comment]
> Curious if you've had any discussions / brainstorms along these lines.

We have, but you've encouraged me to file a public issue at https://github.com/dotnet/aspnetcore/issues/41861.

**Comment by tpeczek** [comment]
Hi,

I've been playing with RateLimiting middleware in .NET 7 Preview 6 and it seems that retry-after metadata for `FixedWindowRateLimiter` always provides the window size. I'm not sure if this is a bug or by desing, but would it be possible for it to provide the actual time remaining till replenishing?

**Comment by rwkarg** [comment]
> Hi,
> 
> I've been playing with RateLimiting middleware in .NET 7 Preview 6 and it seems that retry-after metadata for `FixedWindowRateLimiter` always provides the window size. I'm not sure if this is a bug or by desing, but would it be possible for it to provide the actual time remaining till replenishing?

I don’t have a spec to reference but it would make sense to give the window size otherwise you’d have all of the throttled clients retrying at the same time when the “actual time” refreshes. 

 The Token limiter, at least, has the same behavior for retry-after.

**Comment by tpeczek** [comment]
> > Hi,
> > I've been playing with RateLimiting middleware in .NET 7 Preview 6 and it seems that retry-after metadata for `FixedWindowRateLimiter` always provides the window size. I'm not sure if this is a bug or by desing, but would it be possible for it to provide the actual time remaining till replenishing?
> 
> I don’t have a spec to reference but it would make sense to give the window size otherwise you’d have all of the throttled clients retrying at the same time when the “actual time” refreshes.
> 
> The Token limiter, at least, has the same behavior for retry-after.

In fact this is becoming quite sophisticated very quickly. In web context it's quite common to have different rate limits for different clients (based for example on client identifiers or IP addresses). I'm assuming that RateLimiting middleware is designed to handle similar cases, this is way it seems to be centralized around `PartitionedRateLimiter`.

This might be more of an opinion than a fact, but from my experience the usual expectation in the web context is that `Retry-After` HTTP header contains the actual remaining time to which clients add jitter. But as I said, I might be have been exposed to specific set of projects and maybe it's not like this in general.

Also I see a potential risk of "unlucky client" if entire window length is always returned. If a client makes his request close to the end of the window, gets rate limited, and then waits the entire window length, it becomes likely that he will be rate limited again as the whole quota has been already used by others. This way client might end up being constantly rate limited, so  a jitter on the client side may be required anyway and returning of the whole window just makes client unnecessary wait longer.

**Comment by rf-0** [comment]
Will this work for scale-out scenarios? ie: saved shared state externally like in Redis so rate limiting will work per user per request across multiple proxies/gateway instances?

I was looking into the combination of Yarp + Rate limiting (dotnet 7) for a microservices architecture.

**Comment by BrennanConroy** [comment]
See https://github.com/dotnet/aspnetcore/issues/41861
