### ISSUE TITLE
Automatically download the JDK as part of the build if not present

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#37396]
As per our discussion on DoI, if the JDK is not installed on the machine, download the appropriate binary distribution from the Microsoft distributions of the Open JDK and add it to the path.

**Comment by dougbu** [comment]
@javiercn, if decided in DoI meetings, should this be on the [DoI dashboard](https://github.com/orgs/dotnet/projects/15?fullscreen=true)❔ Note the issue isn't assigned yet.

**Comment by javiercn** [comment]
@dougbu I think we can close this issue and its already done.
