### ISSUE TITLE
Blazor: allow to specify an additional handler on a two-way binding 

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/aspnetcore#37405]
### Is your feature request related to a problem? Please describe.

Often there is a need to two-way bind but execute an additional code when the bind take places

Actually we can't subscribe to the same event used by two way binding because we get the error starting with
`The component parameter is used two or more times for this component`

The only way close to solve the problem are:
- do not use two way binding and handle the change event doing custom logic (and updating the member ourself)
- edit the setter of the property we are binding, with the cons of not being able to call async code (and if we are bound to an object property sometime the additional logic can't be put into it's `set` method

### Describe the solution you'd like

An additional syntax that allow to specify an additional `EventCallback` that will be called by blazor after the binding code takes place
something like

```
<MyComponent @bind-Value="MyValueProperty" @bind-Value:after-bind="MyAdditionalHandler" />
```

**Comment by MariovanZeist** [comment]
You could also use something like this component below, 

When you drop this component anywhere inside an ``<EditForm>``. ModelChanged will be called for any property that changes (Due to input changes), and you can use the ``FieldChangedEventArgs`` to determine which one.

```cs
public class ModelChange : ComponentBase, IDisposable
{
	private EditContext _previousEditContext;
	[CascadingParameter] EditContext EditContext { get; set; }
	[Parameter] public EventCallback<FieldChangedEventArgs> ModelChanged { get; set; }

	protected override void OnInitialized()
	{
		if (EditContext is null)
		{
			throw new InvalidOperationException($"{nameof(ModelChange)} have a valid {nameof(EditContext)}");
		}
		if (_previousEditContext == EditContext)
		{
			return;
		}

		if (_previousEditContext is not null)
		{
			_previousEditContext.OnFieldChanged -= HandleFieldChanged;
		}
		_previousEditContext = EditContext;
		EditContext.OnFieldChanged += HandleFieldChanged;
	}

	private async void HandleFieldChanged(object sender, FieldChangedEventArgs e)
		=> await ModelChanged.InvokeAsync(e);

	public void Dispose()
	{
		if (EditContext != null)
		{
			EditContex.OnFieldChanged -= HandleFieldChanged;
		}
	}
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is going to be covered as part of #22394.
With an async binding you will be able to run additional logic to run before binding takes place.
