### ISSUE TITLE
IIS ApplicationInitialization tests are not running on helix

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#37419]
Found while investigating https://github.com/dotnet/aspnetcore/issues/28089

These tests are currently all skipped on the windows helix queues because the machines don't have the application initialization module installed, meaning we don't have any coverage of preload on CI. Its possible there are other classes of RequireIIS(...) tests that are silently skipped on helix

We should try and get this feature enabled and ensure that any other IIS features we expect are enabled

I think we sort of want these kinds of tests to fail on windows CI, and only silently no-op skip on developer machines.

![image](https://user-images.githubusercontent.com/6537861/136640719-4271bdc7-b2c1-41b0-800f-c1f6d5fec3c2.png)

**Comment by HaoK** [comment]
Another cluster of tests that we seem to be not running at all: the httpsys functionals, at least some of these in quarantine are never run: (related test failure issue: https://github.com/dotnet/aspnetcore/issues/29126)

![image](https://user-images.githubusercontent.com/6537861/137995501-30a91878-bfee-40ce-b973-6ecfa832f32a.png)

**Comment by HaoK** [comment]
@MattGal is there an easy way for us to turn on the Application Initialization feature in IIS for the `Windows.11.Amd64.ClientPre.Open` helix queue?  https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization

**Comment by MattGal** [comment]
> @MattGal is there an easy way for us to turn on the Application Initialization feature in IIS for the `Windows.11.Amd64.ClientPre.Open` helix queue? https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization

No problem, I created https://github.com/dotnet/core-eng/issues/14817 and barring challenges getting the artifact to work properly this should be straightforward.  Note that I do take vacations at times and it may be preferable to tag @dotnet/dnceng for these times.

**Comment by HaoK** [comment]
Thanks Matt, I'll use the dnceng alias for these kinds of requests in the future

**Comment by HaoK** [comment]
Tests should will enabled now that once https://github.com/dotnet/core-eng/issues/14817 is fully rolled out to the windows queues
