### ISSUE TITLE
[Performance] Investigate bi-modality of some benchmarks

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#37465]
#### INTEL - Windows

**Plaintext Platform** 
Bi-modal between 9,450 and 10.212 on .NET 6.0. Didn't confirm on .NET 5.0.

**Json Platform**
Bi-modal between 727 K and 800 K on .NET 6.0. Didn't confirm on .NET 5.0

**Json**
Bi-modal between 706 K and 786 K on .NET 6.0. Didn't confirm on .NET 5.0

#### AMD - Linux

**Fortunes Platform**
Bi-modal between 362 K and 440 K on .NET 6.0. Didn't confirm on .NET 5.0

**Comment by shirhatti** [comment]
![image](https://user-images.githubusercontent.com/4734691/137550058-b0be1110-3fdb-4d79-a1c1-fbf19bee8270.png)

Notes: First run of the day is faster than the second run on the same day

**Comment by sebastienros** [comment]
Doesn't repro with new machines
