### ISSUE TITLE
[.Net 6.0] Sampler does not receive the correct ParentId when enabling ActivitySource listener for `Microsoft.AspNetCore`

### ISSUE THREAD

**Issue by vishweshbankwar** [dotnet/aspnetcore#37471]
### Describe the bug

Starting .NET6.0, There is an option to subscribe to Activity created by [HostingApplicationDiagnostics.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs) by enabling listener for ActivitySource named `Microsoft.AspNetCore`. However, the approach has following two issues:

1) When using sampling, the sampler does not receive the correct parent context as the parentId is extracted after calling _activitySource.CreateActivity() [here](https://github.com/dotnet/aspnetcore/blob/4bdaaebaa8dfa94c180ea899fb8d569cbd9bb501/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L285). Due to this, the sampler which relies on parent context will not be able to make accurate sampling decisions.

2) The approach will create a new traceId for the activity even if incoming headers have requestId. This case only gets triggered when trying to access traceId from `ActivityCreationOptions<ActivityContext> options` inside sampler.

### To Reproduce

The following example shows the behavior, the code flow follows the same flow as [HostingApplicationDiagnostics.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs)

```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        ActivitySource src = new ActivitySource("Test");
        using var listener = new ActivityListener
        {
            ShouldListenTo = activitySource => true,
            Sample = (ref ActivityCreationOptions<ActivityContext> options) =>  ComputeActivitySamplingResult(options)
        };

        ActivitySource.AddActivityListener(listener);

        var _activity = src.CreateActivity("Test", ActivityKind.Server);

        // Set ParentId extracted from header
        _activity?.SetParentId("00-35aae61e3e99044eb5ea5007f2cd159b-40a8bd87c078cb4c-00");  
        _activity?.Start();

        Console.WriteLine(_activity?.ParentId); // 00-35aae61e3e99044eb5ea5007f2cd159b-40a8bd87c078cb4c-00
        Console.WriteLine(_activity?.ParentSpanId); // Expected: 40a8bd87c078cb4c, Actual: 40a8bd87c078cb4c
        Console.WriteLine(_activity?.SpanId); // new SpanId
        Console.WriteLine(_activity?.TraceId); // Expected: 35aae61e3e99044eb5ea5007f2cd159b, Actual: New Id
    }

    private static ActivitySamplingResult ComputeActivitySamplingResult(
        in ActivityCreationOptions<ActivityContext> options)
    {
        var traceID = options.TraceId; // traceId here will be the traceId for created Activity.
        var parent = options.Parent; // Parent not available here.

        return ActivitySamplingResult.AllDataAndRecorded;
    }
}


```

Also adding sample Asp.Net Core app [here](https://github.com/vishweshbankwar/DotNet6_AspNetCore_ActivitySource)

**Comment by adityamandaleeka** [comment]
Triage: header extraction should happen before creation of Activity. See https://github.com/dotnet/aspnetcore/blob/bcb8843461d19746f6b071898bff16c1f1ba350d/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L298
