### ISSUE TITLE
Blazor-server-side Multi routing such as in mvc

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#37485]
I have two sides
```csharp
@page "/{article?}"

<h2>@article</h2>

@code {
    [Parameter]
    public string article { get; set; } = "";

    protected override async Task OnInitializedAsync() 
    {
        if(article != "testArticle")
        {
            // return NOTFOUND
        }
    }

}
```
```csharp
@page "/{game?}"

<h2>@game</h2>

@code {
    [Parameter]
    public string game { get; set; } = "";

    protected override async Task OnInitializedAsync() 
    {
        if(game != "testGame")
        {
            // NOTFOUND
        }
    }

}
```
I would like many sites to be able to run under one domain like in mvc
example:
```
domain.com/good-news
dmoain.com/best-game
domain.com/good-forwarding
domain.com/testGame
domain.com/testArticle
```
in mvc it was enough to give ``return NotFound();``

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

This is already possible today provided that you host your apps in different base paths. [Here](https://github.com/javiercn/BlazorMultipleApps) is a sample I wrote a while ago that you can use as a starting point. It's for Blazor webassembly, however you should be able to adapt it for Blazor server without much trouble.

**Comment by enetstudio** [comment]
@Alerinos, I believe that the Router's  OnNavigateAsync feature can solve your issue.

Here's a simple code sample, checking the url path and navigating to the required url. This fulfills what you requested at the start of your question.  I believe you can create a well-grained and complex navigation scheme. You can also query your database through Web Api end points, etc. See  [here the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#handle-asynchronous-navigation-events-with-onnavigateasync) and follow the explanations:

App.razor
-----------

```@using Pages
@inject NavigationManager NavigationManager

<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true" OnNavigateAsync="@OnNavigateAsync">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
@code {

 
    private async Task OnNavigateAsync(NavigationContext context)
    {
        if (context.Path.ToLower() == "testArticle".ToLower())
        {
            NavigationManager.NavigateTo("counter");
        }
        else if (context.Path.ToLower() == "testGame".ToLower())
        {
            NavigationManager.NavigateTo("fetchdata");
        }

        await Task.CompletedTask;
    }
}```

Index.razor
------------

    page "/{MyParam?}"

    @code 
    {
         [Parameter]
        public string MyParam { get; set; } = "";
    }

I do hope that's what you were after. It seems to me that you may also  need to use the pattern suggested by javiercn above.

**Comment by Alerinos** [comment]
@enetstudio Unfortunately that won't work, it will only create a redirect. For this to work, you need to use the `` RenderHandle '' and the `` Render '' function

@pranavkm Maybe it's worth taking a look at a custom router?
It is very useful.

**Comment by Alerinos** [comment]
Example:
```cs
app.UseEndpoints("/{name}",endpoints =>
{
    endpoints.MapControllerRoute(() => {
    if(db.ToDo.Any(x => x.Name == endpoints.name))
       RenderHandle.Redner(Pages.Counter)
    }
    );  
      
    endpoints.MapControllerRoute(() => {
    if(db.Weather.Any(x => x.ShortName == endpoints.name))
       RenderHandle.Redner(Pages.Fetchdata)
    }
    );        
}
);
```

**Comment by Alerinos** [comment]
Recently, I brought up this topic here https://github.com/dotnet/aspnetcore/issues/39719

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
