### ISSUE TITLE
HotReload - Blazor WA - is not working with Radzen components

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HotReload---Blazor-WA---is-not-working-w/1543060)._

---
After a change in line 29: "<th>Temp. (F)</th>":

info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\xxx\source\repos\BlazorApp5\BlazorApp5\Server
watch : Files changed: C:\Users\xxx\source\repos\BlazorApp5\BlazorApp5\Client\Pages\il0cdw0n.ccw~, C:\Users\xxx\source\repos\BlazorApp5\BlazorApp5\Client\Pages\FetchData.razor~RF32fdab90.TMP, C:\Users\xxx\source\repos\BlazorApp5\BlazorApp5\Client\Pages\**FetchData.razor**
watch : Unable to handle changes using hot reload.
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?

HR works if I comment Radzen's DataGrid on the page.

---
#### Feedback Bot on 9/30/2021, 00:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a limitation of the underlying Mono runtime. It's being tracked as part of https://github.com/dotnet/runtime/issues/57365
