### ISSUE TITLE
Minimal APIs ServiceBase

### ISSUE THREAD

**Issue by doddgu** [dotnet/aspnetcore#37540]
## Summary

I had a scene where I had to write a lot of apis, If all the apis were written in program.cs, feels very smelly to me.
So, I need a `ServiceBase` like `ControllerBase`.

## Motivation and goals

Can group apis like controllers

## In scope

Use Minimal APIs to write a lot of API.

## Risks / unknowns

The service needs to be added before the `WebApplicationBuilder` is built, and the `WebApplication` needs to be injected into the `ServiceBase` constructor via `DI`, so the constructor's operation on `app.Map` can be treated as a singleton, unlike controller  

## Examples

Program.cs
```csharp
var builder = WebApplication.CreateBuilder(args);

var app = builder.Services.AddServices(builder);

app.Run();
```

HelloService.cs
```csharp
public class HelloService : ServiceBase
{
    public HelloService(IServiceCollection services) : base(services)
    {
        App.MapGet("/Hello", Hello);
    }

    public IResult Hello(string word)
    {
        return Results.Ok($"Hello {word}");
    }
}
```

ServiceCollectionExtensions.cs
```csharp
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Add all classes that inherit from ServiceBase to Microsoft.Extensions.DependencyInjection.IServiceCollection
    /// <para>Notice: this method must be last call.</para>
    /// </summary>
    /// <param name="services">The Microsoft.Extensions.DependencyInjection.IServiceCollection to add the service to.</param>
    /// <param name="builder">The Microsoft.AspNetCore.Builder.WebApplicationBuilder.</param>
    /// <returns></returns>
    public static WebApplication AddServices(this IServiceCollection services, WebApplicationBuilder builder)
    {
        services.TryAddScoped(sp => services);

        services.AddSingleton(new Lazy<WebApplication>(() => builder.Build(), LazyThreadSafetyMode.ExecutionAndPublication))
                .AddTransient(serviceProvider => serviceProvider.GetRequiredService<Lazy<WebApplication>>().Value);

        services.AddServices<ServiceBase>(true);

        var serviceProvider = services.BuildServiceProvider();
        return serviceProvider.GetRequiredService<WebApplication>();
    }

    public static IServiceCollection AddServices<TService>(this IServiceCollection services, bool autoFire)
    {
        Type serviceType = typeof(TService);
        return (from t in Assembly.GetEntryAssembly()!.GetTypes()
                    where t.BaseType == serviceType
                    select t)
                .AddScoped(services);
    }

    public static IServiceCollection AddAndFireScoped(this IEnumerable<Type> serviceTypes, IServiceCollection services, bool autoFire)
    {
        foreach (Type serviceType in serviceTypes)
        {
            services.AddScoped(serviceType);
        }

        if (autoFire)
        {
           foreach (Type serviceType in serviceTypes)
           {
                    services.BuildServiceProvider().GetService(serviceType);
            }
        }

        return services;
    }
}
```

ServiceBase.cs
```csharp
public class ServiceBase : IService
{
    private ServiceProvider _serviceProvider = default!;

    public WebApplication App => _serviceProvider.GetRequiredService<WebApplication>();

    public IServiceCollection Services { get; protected set; }

    public ServiceBase(IServiceCollection services)
    {
        Services = services;
        _serviceProvider = services.BuildServiceProvider();
    }

    public TService? GetService<TService>() => _serviceProvider.GetService<TService>();

    public TService GetRequiredService<TService>()
        where TService : notnull
        => Services.BuildServiceProvider().GetRequiredService<TService>();
}
```

IService.cs
```csharp
public interface IService
{
    WebApplication App { get; }

    IServiceCollection Services { get; }

    TService? GetService<TService>();

    TService GetRequiredService<TService>() where TService : notnull;
}
```

**Comment by doddgu** [comment]
> I think you should feel empowered to build this on top of minimal APIs and ship a package with it (I can help you fix some of the problems some of the logic in ServiceBase) but this isn't something we're going to ship on top of minimal APIs from the framework itself.

Thanks for your reply.
You have a way to make my `ServiceBase` logic simpler, that's good too.

**Comment by doddgu** [comment]
@daviburg Yeah, `Carter` is nearest to Minimal APIs. But I don't need a framework. I want my app to keep the Minimal APIs primitive. 
Later I will make nuget package and create a github repo.

**Comment by doddgu** [comment]
> Wrong David probably. I am like a fish out of water in this thread.

I don't know what the Minimal API is.  If Minimal APIs are meant to simplify apis, `ServiceBase` support for grouping apis is still necessary.

**Comment by doddgu** [comment]
@davidfowl
Hi, is there any progress?

**Comment by davidfowl** [comment]
Progress on what? This issue is closed

**Comment by doddgu** [comment]
> I think you should feel empowered to build this on top of minimal APIs and ship a package with it (I can help you fix some of the problems some of the logic in ServiceBase) but this isn't something we're going to ship on top of minimal APIs from the framework itself.



> This is the biggest piece of broken code https://github.com/masastack/MASA.Utils/blob/af78655b06b79e24f87ff9c03e3ae2778189b1a8/src/Extensions/MASA.Utils.Extensions.DependencyInjection/ServiceCollectionExtensions.cs#L50. Building a new service provider and resolving services repeatedly.

@davidfowl 
https://github.com/masastack/MASA.Utils/blob/af78655b06b79e24f87ff9c03e3ae2778189b1a8/src/Extensions/MASA.Utils.Extensions.DependencyInjection/ServiceCollectionExtensions.cs#L50
Is there any method can let me like controller to add route?
