### ISSUE TITLE
id_token signature validation in OpenIdConnectHandler in case of authorization code flow

### ISSUE THREAD

**Issue by Riff451** [dotnet/aspnetcore#37549]
Hello,
I've noticed that the `OpenIdConnectHandler` is setting `TokenValidationParameters.RequireSignedTokens` to `false` in case of authorization code flow as per OIDC spec:
https://github.com/dotnet/aspnetcore/blob/2924ca229b3d6c91b7c9eded119b31dfd7aa1fef/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L685-L687

However the [`JwtSecurityTokenHandler.ValidateSignature()`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b5b7ed8fb8ce513469b51b87c5f76314783b74e3/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L854-L857) method that, if I'm not wrong, eventually gets called, validates the signature when the token is signed even if `TokenValidationParameters.RequireSignedTokens` is `false`.

Am I missing something?
Is this something expected in the `OpenIdConnectHandler`?

Thank you very much.

**Comment by adityamandaleeka** [comment]
@haok Not sure if you ever saw this one. Should this be in 8 planning?

**Comment by mikekistler** [comment]
Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
