### ISSUE TITLE
Kestrel settings are not applied if configure KestrelServerOptions in appsettings.json file

### ISSUE THREAD

**Issue by robinNode** [dotnet/aspnetcore#37544]
I am unable to configure KestrelServerOptions in appsettings.json file.
I tested the below settings, it doesn't work. it still takes default value (30,000,000 bytes => 28.6MB). 
-- MaxRequestBodySize
-- MaxRequestHeaderCount

```json
{
  "Kestrel": {
    "Limits": {
      "MaxRequestBodySize": 3000000,
      "MaxRequestHeaderCount": 10
    },
    "EndPoints": {
      "Http": {
        "Url": "http://*:10110"
      }
    }
  }
}
```

if I do it in C# code, it works.

```C#
services.Configure<FormOptions>(opt =>
{
    opt.MultipartBodyLengthLimit = 3000000;
});

services.Configure<KestrelServerOptions>(opt =>
{
    opt.Limits.MaxRequestBodySize = 3000000;
});
```

### Further technical details
- ASP.NET Core version: 5.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: vs2019 v16.11.4
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.118 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]
```

</details>

**Comment by Tratcher** [comment]
MultipartBodyLengthLimit is a different limit than you've set in config. Which exception do you get during a request?

**Comment by Tratcher** [comment]
Model binding has an opportunity to catch and handle request body exceptions.

A connection reset is expected when the request body size limits are exceeded, disconnecting the client is the only mitigation for a potential DOS attack.
