### ISSUE TITLE
DefaultTokenProviders don't work when having more than 2 user accounts

### ISSUE THREAD

**Issue by noahsalvadordenjo** [dotnet/aspnetcore#37555]
As soon as i add the third ```AddIdentityCore``` asp net core is unable to generate email confirmation tokens
```
            services.AddDbContext<ResaleWebsiteDbContext>(
                opt => opt.UseSqlServer(Configuration.GetConnectionString("Default"))
            );
            services.AddIdentity<ResaleWebsiteUser, IdentityRole>()
            .AddEntityFrameworkStores<ResaleWebsiteDbContext>()
            .AddDefaultTokenProviders();

            services.AddIdentityCore<Admin>(opt => {
                opt.SignIn.RequireConfirmedAccount = false;   
            })
            .AddRoles<IdentityRole>()
            .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<Admin, IdentityRole>>()
            .AddSignInManager<SignInManager<Admin>>()
            .AddEntityFrameworkStores<ResaleWebsiteDbContext>().AddDefaultTokenProviders();


            services.AddIdentityCore<Seller>(opt => {
                opt.SignIn.RequireConfirmedAccount = false;   
            })
            .AddRoles<IdentityRole>()
            .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<Seller, IdentityRole>>()
            .AddSignInManager<SignInManager<Seller>>()
            .AddEntityFrameworkStores<ResaleWebsiteDbContext>().AddDefaultTokenProviders();

            services.AddIdentityCore<Buyer>(opt => {
                opt.SignIn.RequireConfirmedAccount = false;   
            })
            .AddRoles<IdentityRole>()
            .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<Buyer, IdentityRole>>()
            .AddSignInManager<SignInManager<Buyer>>()
            .AddEntityFrameworkStores<ResaleWebsiteDbContext>().AddDefaultTokenProviders();
```

**Comment by HaoK** [comment]
Identity was not really designed to be called multiple times, so your mileage will vary trying to have multiple user managers and types like this, as there is only one set of options for identity: https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Identity/Extensions.Core/src/TokenOptions.cs#L12

You can likely do some workarounds to make things work, but you will have to fix up the places where the wrong types are being assigned, you won't be able to do things like AddDefaultTokenProviders but you can configure these directly via RegisterTokenProvider on each user manager instance

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Identity/Extensions.Core/src/UserManager.cs#L1766

**Comment by HaoK** [comment]
I'm not sure what you mean by a real world example, but you can look at how the authenticator token provider as an example: https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs
