### ISSUE TITLE
WebAssembly in .Net 6 RC2: The top level app must directly references to the assemblies used by it's referenced assemblies

### ISSUE THREAD

**Issue by jjzhang12** [dotnet/aspnetcore#37574]
### Describe the bug
In WebAssembly in .Net 6 RC2 (I did not test earlier version), if the Blazor app1 references to module M1, and M1 references to another module M2. Then app1 must directly reference to M2, or I get exception in runtime.
This is working fine in .net 5.

### To Reproduce
Run the sample application from https://github.com/jjzhang12/Net6Issue.git
This is a template Blazor wasm app, and one line is added to instantiate the MyClass, and MyClass requires MyAbstractClass.
An exception is logged in runtime.

### Exceptions (if any)
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters) window.Module.s.printErr @ blazor.webassembly.js:1 blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not load type of field 'BlazorApp1.Pages.Counter:class1' (1) due to: Could not resolve type with token 0100000c from typeref (expected class 'MyAbstractClass.Disposable' in assembly 'MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:MyAbstractClass.Disposable member:(null) System.TypeLoadException: Could not load type of field 'BlazorApp1.Pages.Counter:class1' (1) due to: Could not resolve type with token 0100000c from typeref (expected class 'MyAbstractClass.Disposable' in assembly 'MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:MyAbstractClass.Disposable member:(null) at System.RuntimeTypeHandle.CanCastTo(RuntimeType type, RuntimeType target) at System.RuntimeType.IsAssignableFrom(Type c) at Microsoft.AspNetCore.Components.RouteTableFactory.g__GetRouteableComponents|4_0(List`1 routeableComponents, Assembly assembly) at Microsoft.AspNetCore.Components.RouteTableFactory.GetRouteableComponents(RouteKey routeKey) at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey) at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable() at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass62_0.b__1(RenderTreeBuilder builder) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

### Further technical details
- ASP.NET Core version: 6.0 RC2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: 2022 Peview
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

</details>

**Comment by javiercn** [comment]
You should be using a ProjectReference [here](https://github.com/jjzhang12/Net6Issue/blob/master/MyClass/MyClass.csproj#L8-L10)

**Comment by jjzhang12** [comment]
Additional info: I can actually see the assembly is downloaded by looking at the Chrome network traffic, but some how it still cannot be used the app.

**Comment by RChrisCoble** [comment]
Seems like a fairly serious regression if it works properly in .Net 5.
