### ISSUE TITLE
Blazor WASM with LazyLoad - Cannot publish web project in RC2

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#37570]
### Describe the bug
After upgrading project from .Net 6 RC1 to .Net 6 RC2 I can no longer `dotnet publish` my app.

Upon inspection it seems that it cannot find the dlls that are lazy-loaded.  `wasm-tools` workload is installed.

Unfortunately this is preventing us from deploying our app in RC2 at the moment. It works fine in local debug.

> `dotnet build -c Release` works no problem - I suspect it's a problem related to `wasm-tools`

### To Reproduce
Repo is here: https://github.com/srpeirce/blazor-net6-rc2-lazyload-problem
Install workload if you haven't already:

```
dotnet workload install wasm-tools
```

Publish project:

```
dotnet publish -c Release .\Web\
```

### Exceptions (if any)
Microsoft (R) Build Engine version 17.0.0-preview-21501-01+bbcce1dff for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  LazyBlazy -> C:\code\P4\LazyLoadProblem\LazyBlazy\bin\Release\net6.0\LazyBlazy.dll
  Web -> C:\code\P4\LazyLoadProblem\Web\bin\Release\net6.0\Web.dll
  Web (Blazor output) -> C:\code\P4\LazyLoadProblem\Web\bin\Release\net6.0\wwwroot
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  LazyBlazy -> C:\code\P4\LazyLoadProblem\LazyBlazy\bin\Release\net6.0\LazyBlazy.dll
  Web -> C:\code\P4\LazyLoadProblem\Web\bin\Release\net6.0\Web.dll
  Web (Blazor output) -> C:\code\P4\LazyLoadProblem\Web\bin\Release\net6.0\wwwroot
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(524,5): error BLAZORSDK1001: Unable to find 'LazyBlazy.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project. [C:\code\P4\LazyLoadProblem\Web\Web.csproj]

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by TanayParikh** [comment]
cc/ @pranavkm potential RC2 regression.

**Comment by srpeirce** [comment]
This issue? https://github.com/dotnet/aspnetcore/issues/37546
