### ISSUE TITLE
Hot reload loses CSS from referenced projects

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37592]
**Repro steps:**

- Use latest .NET SDK (6.0.100-rtm.21512.45) and VS 31808.319.d17.0
- File->New Blazor Server project
- Right-click solution, Add->New Project
- Choose "Razor class library" - accept all defaults (so it's called `RazorClassLibrary1`) and add to solution
- Right-click Blazor Server project and add a project reference to your new RCL
- In `Index.razor`, add a `<RazorClassLibrary1.Component1 />`
- Ctrl+F5 to see it running in browser. Notice that the `Component1` is correctly styled with CSS.
- Edit a `.razor.css` file in your main project (not the RCL)
  - For example, open `Shared\MainLayout.razor.css` and change `.top-row`'s `background-color` value to `red`
  - Press Ctrl+S

Expected:
 - Top row changes to red, but nothing else is affected

Actual:
 - Top row changes to red, but `Component1` also loses all its CSS

It seems that when hot reload regenerates `YourApp.styles.css`, it forgets to include the `@import` declarations for referenced projects.

Although I've put this in `area-blazor`, I expect it applies just the same to MVC/Razor Pages with the corresponding scoped CSS feature. The severity of this is pretty bad because it means that, if you're using any component library (such as a 3rd-party library) then you can't edit the CSS in your own project without wrecking the appearance of your app until you fully rebuild and reload.

### Screenshots

Before the change:

![image](https://user-images.githubusercontent.com/1101362/137520619-00298e53-c2fa-421a-8888-b989adf14428.png)

After the change (notice the RCL component):

![image](https://user-images.githubusercontent.com/1101362/137520437-8271e394-49d2-47d5-be46-2bba22acf1bf.png)

**Comment by Oblomoff** [comment]
This bug is only fixed in Visual Studio, but it still remains on the command line (dotnet watch).
