### ISSUE TITLE
Missing fractional seconds of date-time in ModelBinding

### ISSUE THREAD

**Issue by mhotze** [dotnet/aspnetcore#37590]
### Describe the bug

When passing date-time with optional fractional seconds as key parameter `[FromRoute]` to Web-API, class `RouteValueProvider` is cropping milliseconds of bound `DateTimeOffset`. This way the key value doesn't match in nearly all requests.

### To Reproduce

Simply modify the test `GetValueProvider_ReturnsValue_UsesInvariantCulture` in https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/ModelBinding/RouteValueProviderTests.cs as follows.

```diff
        [Fact]
        [ReplaceCulture("de-CH", "de-CH")]
        public void GetValueProvider_ReturnsValue_UsesInvariantCulture()
        {
            // Arrange
            var values = new RouteValueDictionary(new Dictionary<string, object>
            {
-                { "test-key", new DateTimeOffset(2018, 10, 31, 7, 37, 38, TimeSpan.FromHours(-7)) },
+                { "test-key", new DateTimeOffset(2018, 10, 31, 7, 37, 38, 1, TimeSpan.FromHours(-7)) },
            });
            var provider = new RouteValueProvider(BindingSource.Query, values);

            // Act
            var result = provider.GetValue("test-key");

            // Assert
-           Assert.Equal("10/31/2018 07:37:38 -07:00", (string)result);
+           Assert.Equal("2018-10-31T07:37:38.0010000-07:00", (string)result);
        }
```

### Further technical details

`RouteValueProvider.GetValue()` should use `ToString("O")` in some way.

Refer to [Standard date and time format strings | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip) and [rfc3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6)

- ASP.NET Core version: 5.0.11
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by halter73** [comment]
The current implementation of `RouteValueProvider.GetValue(string key)` is pretty simple:

https://github.com/dotnet/aspnetcore/blob/962f55e6a1c9f0369a4d56846044c9aed0d3f21d/src/Mvc/Mvc.Core/src/ModelBinding/RouteValueProvider.cs#L104-L112

I'm hesitant to start special-casing types other than `string` here. It's annoying that we lose precision for `DateTime` and `DateTimeOffset`, but I'm not sure it's worth it to change behavior here. There could already be code out there that relies on the default `Convert.ToString` behavior for these types.

Furthermore, precision is not lost if the `DateTime` or `DateTimeOffset` is stored in the `RouteValueDictionary` as a string which is what happens by default. For example given the following endpoint and a request to https://localhost:5001/2018-10-31T07:37:38.0010000-07:00

```C#
[HttpGet("{date}")]
public string Test(DateTimeOffset date)
{
    return $"DateTimeOffset: {date.ToString("O")}";
}
```

You get `https://localhost:5001/2018-10-31T07:37:38.0010000-07:00` in response.

@mhotze What's putting the `DateTimeOffset` in the `RouteValueDictionary`? Do you have a custom `IRouter` doing this?

**Comment by mhotze** [comment]
I can confirm, that your simple sample preserves precision using string representation and must admit that `ODataAttributeRouting` (Package `Microsoft.AspNetCore.OData`) is putting the `DateTimeOffset` in the `RouteValueProvider`. I could provide a sample repro project, but we are constrained to a couple of modifications around `ODataAttributeRouting` and alternate keys. So this might be a bit difficult to setup and in the end it's likely an issue for the `Microsoft.ApsNetCore.OData`-Team.

We already solved the problem with a custom provider, but i would still consider this as a bug in your implementation. Sure, there might already be code out there as you mentioned, but this code has potentially the same problem. Maybe it's worth to be communicated as a breaking change.

**Comment by halter73** [comment]
> Maybe it's worth to be communicated as a breaking change.

What changed? I'm pretty sure `RouteValueProvider` always worked this way. It would be nice if you could file this issue in https://github.com/OData/AspNetCoreOData @mhotze . I'm not sure where `Microsoft.ApsNetCore.OData` is putting a `DateTimeOffset` in the `RouteValueProvider` or how to trigger this issue.

**Comment by mhotze** [comment]
> What changed? I'm pretty sure `RouteValueProvider` always worked this way.

I meant if you will change it, it could be a breaking change. Just to address the concerns regarding the code out there.

**Comment by halter73** [comment]
You're right it would be a breaking change. I don't think it's worth it considering it doesn't affect normal model binding and it's easy to work around.
