### ISSUE TITLE
Changing DI instance value in Middleware is not being reflected at other places, where DI of same type is used

### ISSUE THREAD

**Issue by vidhyasagarreddy** [dotnet/aspnetcore#37617]
Working scenario - change in Middleware is effecting all other areas, where DI of same type is used:
```
 public async Task Invoke(HttpContext httpContext)
 {
     ...
     ICustomer customer= htpContext.RequestServices.GetService(typeof(ICustomer));
     customer.Name = "Vidhya Sagar Reddy";
     ...
 }
```

Non-working scenario: change in Middleware is NOT effecting all other areas, where DI of same type is used:
```
 public async Task Invoke(HttpContext httpContext)
 {
     ...
     ICustomer customer= htpContext.RequestServices.GetService(typeof(ICustomer));
     customer = this.GetCachedCustomer();
     ...
 }
```

It is clear evident that changing/altering entire instance is causing the issue. But is this expected behavior ?

**Comment by vidhyasagarreddy** [comment]
Got it from the explanation, but with the C# example, it raised a new confusion and is not working like you said in the example. It ideally should refer to Joe from here on(after new assignment) right ?

**Comment by davidfowl** [comment]
@vidhyasagarreddy what's confusing you about the example?

**Comment by davidfowl** [comment]
This is the best drawing I could come up with 😄:

![Whiteboard](https://user-images.githubusercontent.com/95136/137612760-cc92c9c9-591a-4498-af9b-94022ad5e2e9.png)

There are 2 memory addresses (0 and 1) that have the data for customers joe and bob. The DI container points has a reference that points to bob and the middleware initially points to that same reference (hence the dotted line). Then you change the reference in the middleware to point to customer "joe" (location 1). It doesn't affect what's in the DI container so anyone else that looks at that reference sees bob.

Hope that helps.

**Comment by vidhyasagarreddy** [comment]
Thanks a lot David for that.
It's clear now. I am wondering how this would behave for nulls (DI resolving to null). Guessing it would always be null.
