### ISSUE TITLE
Blazor AOT compilation fails at ComputeBlazorPublishAssets.GroupExistingStaticWebAssets

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/aspnetcore#37610]
This follows on from issue #35633 which is closed but unfortunately not fixed for us in 6 RC2.

Please see output below. We have spent a lot of time trying to repro on a simple project, but without knowing what the key is, in a large project such as ours it has not yet been possible. 

Is it possible to report the key causing the problem?

Thanks, John

C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(404,5): Error : System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add) at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.GroupExistingStaticWebAssets(Dictionary2 assemblyAssets, Dictionary2 nativeAssets, Dictionary2 satelliteAssemblyAssets, Dictionary2 symbolAssets, Dictionary2 compressedRepresentations)
at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.Execute()

**Comment by javiercn** [comment]
@johngsandiford thanks.

This helps to better understand the issue. It seems that for some reason, when we compress the files some of them seem to be getting the same Identity.

Could you check on the binlog when you identify that the assets get duplicated?

Probably check if there are duplicates on the inputs to this task `GZipCompress` or right afterwards in the outputs of the task `(_BlazorBuildGZipCompressedFile)` or in `(_BlazorGzipStaticWebAsset)`

**Comment by johngsandiford** [comment]
The GZipCompress task has duplicates of the following 

C:\Users\<redacted>\bin\Debug\netstandard2.0\BayesServer.UI.Shared.dll

The ComputeBlazorFilesToCompress task before has no duplicates.

If you need the binlog, happy to share privately.

Regards, John

**Comment by javiercn** [comment]
@pranavkm I think this might have been fixed by the fix in https://github.com/dotnet/sdk/pull/22470, since it looks a lot like  https://github.com/dotnet/aspnetcore/issues/38186 and I believe your fix fixes that.

**Comment by TanayParikh** [comment]
@johngsandiford the .NET 6 patch for this issue came out today, please let us know if you're still facing this issue on .NET 6.0.1.
