### ISSUE TITLE
async void OnGet works perfectly on Windows but intermittent response on Oracle Linux

### ISSUE THREAD

**Issue by usa-m** [dotnet/aspnetcore#37618]
### Describe the bug
When async void is used with PageModel, testing on Windows machine produces perfect results; However, when same code is run on Oracle Linux, it works as intended for about 10~15% times, other times it produces un-predictable output.

### Exceptions (if any)
No exceptions, both on Windows as well as on Oracle Linux.

### Further technical details
- ASP.NET Core version: 5.0.400
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 16.11.3
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     ol
 OS Version:  8.4
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/testing-user/dnc/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/home/testing-user/dnc/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/home/testing-user/dnc/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/home/testing-user/dnc/shared/Microsoft.NETCore.App]
```

</details>

**Comment by davidfowl** [comment]
Don't use async void.
