### ISSUE TITLE
Scoped CSS hot reloading in WebAssembly "ASP.NET Core" hosted template causes browser hang/crash

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37629]
This bug differs from https://github.com/dotnet/aspnetcore/issues/37628 because that one is about static CSS files (`.css`) whereas this one is about scoped CSS files (`.razor.css`).

## Repro

**Create an ASP.NET Core-hosted app that references tailwind.css**

 * Use .NET Core 6.0.100-rtm.21512.45 and VS 31808.319.d17.0
 * File -> New Blazor WebAssembly project. Enable "ASP.NET Core hosted"
 * Download [the current `tailwind.min.css`](https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css) (right-click that link and *Save Link As...*) and add it into your client project's `wwwroot` folder
 * In the client project's `wwwroot\index.html`, add directly below the `<base href>` line the following: `<link href="tailwind.min.css" rel="stylesheet" />`
 * Ctrl+F5 to start
 * **Verify that your page has correctly loaded the Tailwind CSS library** (because bug https://github.com/dotnet/aspnetcore/issues/37508 might trick you here). Check the browser's devtools to ensure that it's genuinely loaded the tailwind CSS sources. If necessary, delete your bin/obj dirs and rebuild. Don't continue with the repro until you see the copyright/license notice from tailwind:

![image](https://user-images.githubusercontent.com/1101362/137628487-4ef686f9-c591-4c90-b00b-9c06f4718e2e.png)

**Edit a scoped CSS file**

* While the browser remains open, in VS, open the client project's `Shared\NavMenu.razor.css`
* Change any CSS rule. For example, change `.top-row`'s `background-color` value to `red` and press ctrl+s to save it. Observe the change appear in the browser after some delay. On my machine, this causes the browser to hang for about 2 seconds the first time I do this.
  * You can easily see it's hung because if you hover the mouse over a different navlink, the cursor does *not* change to a hand, nor does the highlighted background appear behind the navlink, while it is hung. Also you can't click on anything within that browser tab (e.g., the counter button).
* Repeat the previous step several times. Each time you do, the duration of the hang increases.
  * For me, the 2nd edit causes about an 8-second hang.
  * The 3rd edit causes about a 20-second hang.
  * At this rate of growth, you can only make a few edits before your browser is effectively dead forever and has to be force-killed.

## What's going on?

It's something in the browserlink JS script. There's a function called `ensureCssUpToDateAsync` which eats 100% of CPU time for an absolutely outrageous amount of time after each edit, completely blocking the browser tab's UI thread. Here it is taking 28 seconds after a 2nd edit:

![image](https://user-images.githubusercontent.com/1101362/137628748-473e95f5-c429-44f9-95b6-3db48392cb7a.png)

I tried to look into what that function is doing, but all the function/variable names are replaced by 2-char minified names, and [the GitHub sources for browserlink](https://github.com/aspnet/BrowserLink) only seem to include .NET code. I don't know where the JS code sources are. What I *can* see of the browerlink JS file suggests we could see other problems in the future, for example it bundles a complete copy of jQuery.

Note that this issue does **not** repro in the Blazor Server template, the WebAssembly standalone one, or (for some reason) if you reference Tailwind directly on its CDN instead of copying the file locally. There's something specific that goes wrong in the "ASP.NET hosted" case when the large CSS file is in `wwwroot`.

## Is this serious?

Fairly, yes. Tailwind is increasingly popular. If this is a computational-inefficiency thing, then it likely affects any other large CSS libraries too. Being unable to edit scoped CSS if you've referenced Tailwind is a killer to productivity.

## Workaround

The only sensible solution I can find is to disable "CSS Hot Reload" under tools  -> options -> Projects and Solutions -> ASP.NET Core. You can then still reload scoped CSS changes, but not static CSS changes (which don't even work anyway due to #37628). This completely eliminates the hanging. Of course, it also means that even when #37628 is fixed you still wouldn't get static CSS hot reload.

**Comment by mkArtakMSFT** [comment]
Thanks @jodavis . Closing this issue as I assume you are already tracking it on your side.
