### ISSUE TITLE
splatting/deconstruct `[Parameter]` from object

### ISSUE THREAD

**Issue by barahonajm** [dotnet/aspnetcore#37623]
### Description
If we have a `component` with multiple parameters and the caller of that `component` has a an object with the values of those parameters and others, it would be great if we can simply pass the object to the `component` and have it deconstruct the appropriate values onto the parameters.

### Describe the solution you'd like

I would image something like this:

_**Caller**_
```razor
@{
    var package = new
    {
        Name = "Blazor",
        Version = 3,
        Speed = "Blazing",
        Website = "https://example.com",
        Repository = "dotnet/aspnetcore"
    };
}

<SomeComponent @attributes="package" />    //suggestion 1
<SomeComponent @package />                 //suggestion 2

````

_**Component**_
```razor
<p>The name is @Name</p>
<p>The version is @Version</p>
<p>The speed is @Speed</p>
<p>The website is @Website</p>

@code {
    [Parameter]
    public string? Name { get; set; }

    [Parameter]
    public string? Version { get; set; }

    [Parameter]
    public string? Speed { get; set; }

    [Parameter]
    public string? Website { get; set; }
}
```

**Comment by javiercn** [comment]
@huunab thanks for contacting us.

It's not clear what you are looking for, this is already possible. Instead of creating an anonymous object for package, you need to create an `IDictionary<string,object>` and with that, the `@attributes` syntax should work.

**Comment by huunab** [comment]
Thanks, this would be a good feature but again I understand the limitations, thanks for the clarifications!
