### ISSUE TITLE
dotnet watch help is not localized

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/aspnetcore#37645]
### Describe the bug
See the hardcoded strings here: https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/dotnet-watch/Program.cs

### To Reproduce
```
set DOTNET_CLI_UI_LANGUAGE=es
dotnet watch -h
```

### Further technical details
6.0.100-rc.2.21505.57

**Comment by hishamco** [comment]
Please file an issue in https://github.com/dotnet/sdk repo
