### ISSUE TITLE
startup.cs missing from ProjectTemplate files

### ISSUE THREAD

**Issue by jonadv** [dotnet/aspnetcore#37674]
I'm following a tutorial of only a couple of years ago and I run into another issue. This one is discussed here: https://github.com/dotnet/aspnetcore/issues/9542.

A key comment, showing how it is implemented now in updated project templates, links to this repository but the link is [broken](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs#L105). 

Looking into [this repo](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates) and the appropriate path with templates, none of the folders have Startup.cs file in them. Why arent they in there? Where can i find the current resolvement of [this issue](https://github.com/dotnet/aspnetcore/issues/9542) now?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio
