### ISSUE TITLE
Session Value lost only in Chrome after AJAX post

### ISSUE THREAD

**Issue by bigcitydev** [dotnet/aspnetcore#37687]
Hello.
I am struggling with a very strange issue only in Chrome.

In my ASP.NET Core 5 MVC app, i submit login with AJAX.
If login successful, i set a Session value in the controller, display a loading screen with SignalR and return Ok().
When loading finishes, user get redirected on next page with JavaScript.

There i retrieve the session value in the action and display in model.
It works on the first time.
However, when i refresh page, the session value is null.
All other session values i set in middleware etc. are still there.

In Firefox i can retrieve the value unlimited times.
I already tried messing with cookie setup but nothing changed.

Only workaround i came up with is setting the value again right after reading it.

Maybe someone can help me please, i am struggling with this very long.

Thanks

**Comment by captainsafia** [comment]
@bigcitydev Based on your issue description, it looks like the problem might be occurring in the Chrome client and not in MVC. Do you have any extensions or config that would prevent cookies from being persisted in Chrome?

Also, if you have a repro info to reproduce this problem that would be helpful, including a project and the Chrome version you are on.
