### ISSUE TITLE
.NET 6 RC2 Blazor with server side rendering and Azure B2C

### ISSUE THREAD

**Issue by accent** [dotnet/aspnetcore#37713]
After creation of the Blazor project (Client and Server approach) in .NET 6 RC2, adding Azure B2C and migrated it to server side rendering (`render-mode="WebAssemblyPrerendered"`) approach (with `_Host.cshtml` on the Server project side), I started getting exception from Server part in Authorize part:

`System.InvalidOperationException: Cannot provide a value for property 'AuthenticationService' on type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorView'`

Going thru internet, somebody suggested to add in Startup AddApiAuthorization() which causes yet another exception 
`'Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider' to type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IRemoteAuthenticationService``1[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState]'`

That suggest to implement custom AuthenticationStateProvider, however it ended up with some more exceptions with casting.

Even if exception is thrown, authentication with Azure works correctly and data are rendered correctly. I guess, I'm missing something in configuration however, going thru official documentation and stackoverflow, I didn't find any solution for this therefore I'm not sure is it server side issue (misconfiguration) or Blazor bug.

B2C configuration on Client side:
```
builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAdB2C", options.ProviderOptions.Authentication);
});
```

In `Authentication.razor` on Client side
```
@page "/authentication/{action}"
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
<RemoteAuthenticatorView Action="@Action" />

@code{
    [Parameter] public string? Action { get; set; }
}

```

Important configuration part on Server side:
```
builder.Services.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration, "AzureAdB2C");
builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();

builder.Services.AddScoped<SignOutSessionStateManager>();
....


app.UseHttpsRedirection();

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapRazorPages();
app.MapBlazorHub();
app.MapControllers();
app.UseEndpoints(endpoints =>
{
    endpoints.MapFallbackToPage("/_Host");
});
```

And Server side `_Host.cshtml`
```

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
</head>

<body>
    <app>
        <component type="typeof(App)" render-mode="WebAssemblyPrerendered" />
    </app>

    <script src="_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
</body>

</html>
```

### Further technical details
- dotnet --version: 6.0.100-rc.2.21505.57
- The IDE - VS2022 Preview 6.0

**Comment by guardrex** [comment]
@accent ... There might be a more serious problem with the prerendering coverage with auth and hosted WASM. I need to analyze the coverage and probably make further updates. Keep an eye :eye: on https://github.com/dotnet/AspNetCore.Docs/issues/23570. I'll try to work that tomorrow (Thursday) morning. When you see the PR for that issue go up, you can look at the diff on the PR to see what changes I made.

**Comment by guardrex** [comment]
@javiercn @mkArtakMSFT ... I need a clarification on if a doc bug exists based on the content provided for not prerendering auth paths. The original content supplied for the topic is ......

```razor
<app>
    @if (!HttpContext.Request.Path.StartsWithSegments("/authentication"))
    {
        <component type="typeof(Wasm.Authentication.Client.App)" render-mode="Static" />
    }
    else
    {
        <text>Loading...</text>
    }
</app>
```

Cross-ref: https://github.com/dotnet/aspnetcore/issues/15253#issuecomment-604581439

Is that correct? ... It's counter-intuitive with the **not** (`!`) operator on the conditional check, so I need to confirm this guidance or else apply a quick bug fix to the doc.

**Comment by javiercn** [comment]
@guardrex I think that's a bug on my explanation.

```
<app>
    @if (HttpContext.Request.Path.StartsWithSegments("/authentication"))
    {
        <text>Loading...</text>
    }
    else
    {
        <component type="typeof(Wasm.Authentication.Client.App)" render-mode="WebAssemblyPrerendered" />
    }
</app>
```

**Comment by guardrex** [comment]
Very well ... thx ... I'll take care of the update on the docs side.

**Comment by devlife** [comment]
Has there been any movement on this? I'm trying to use WebAssemblyPrerender for my Blazor WASM Hosted project using Azure AD but am getting `Cannot read properties of undefined (Reading redirectUri)`
