### ISSUE TITLE
Removing lib folder with bootstrap and others, and html Links from template project, continues causing build errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37711]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Removing-lib-folder-with-bootstrap-and-o/1557224)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:VS Community 2022 17.0.0 Preview 5.0]
When the libs folder is deleted from wwwroot, and html Link references are removed, from a .net core 6.0 preview 2 project, the build process seems to cache the required js files, and complains.

This is still the case after cleaning the build.
Needed to re-open the solution.

---
#### Feedback Bot on 10/18/2021, 11:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

In order for us to make progress on this issue. Could you provide more details about your environment and preferably a minimal repro project in the form of a publicly accessible github repository with detailed steps on how to reproduce the issue?
