### ISSUE TITLE
High Number of LoopBack Connection

### ISSUE THREAD

**Issue by ss-markmontesa** [dotnet/aspnetcore#37738]
Hi,

![image](https://user-images.githubusercontent.com/55183624/138266195-1735d12c-7601-4fb6-a753-b50d78f84b14.png)

Our appservice suddenly experienced slowness due to high number of loopback connection.
Can you tell us what may it cause?
Our app build from AspNetCore + Angular
We are hosted on Azure.

**Comment by ss-markmontesa** [comment]
> 
> 
> @ss-markmontesa Yes, that would be fine. If you're able to collect a network trace and/or memory dump that would be helpful too.
> 
> You can send them to adityam [at] microsoft [dot] com.

Thanks. I'll send and email. Im just collecting memory dump.

**Comment by ss-markmontesa** [comment]
> 
> 
> @ss-markmontesa Yes, that would be fine. If you're able to collect a network trace and/or memory dump that would be helpful too.
> 
> You can send them to adityam [at] microsoft [dot] com.

I just send an email.

Thanks in advance.

**Comment by adityamandaleeka** [comment]
@ss-markmontesa We sent a follow-up email regarding the dump you sent, and haven't heard back. Are you still hitting this issue?
