### ISSUE TITLE
Packaging a client-side Blazor project into a single JS file

### ISSUE THREAD

**Issue by anthony-c-martin** [dotnet/aspnetcore#37732]
### Is your feature request related to a problem? Please describe.
My team owns a VSCode extension, which interacts with a [Language Server](https://microsoft.github.io/language-server-protocol/) written in C# (https://github.com/Azure/bicep) to provide interactive language features. We have a [demo playground](https://aka.ms/bicepdemo), which leverages Blazor to host the C# code in-browser.

With the recently-announced [VSCode.dev project](https://code.visualstudio.com/blogs/2021/10/20/vscode-dev), our extension is currently unsupported as it requires dotnet runtime to run the language server. It would be amazing if we could bundle our full language server and run it in-browser for the web version of VSCode. As far as I can tell, the main blocker here would be the requirement to bundle all extension JS into a single file.

Is anyone aware of a way of either generating a single JS file at publish time (including all DLLs, plus necessary framework dependencies), or utilizing a tool like webpack to package the full Blazor output into a single JS file?

### Describe the solution you'd like
A mechanism to bundle client-side Blazor code into a single JS file.

**Comment by javiercn** [comment]
@anthony-c-martin thanks for contacting us.

As part of 6.0 we are shipping the ability to completely customize Blazor deployments. It's very likely you can leverage that to create a single JS file with all the necessary info. You can read more details about it [here](https://devblogs.microsoft.com/aspnet/custom-deployment-layout-for-blazor-webassembly-apps/)

If you have more questions feel free to reach out.

**Comment by Thaina** [comment]
Are there already exist the way to setup and write blazor and C# in `vscode.dev` ? If not then is there any progress or stuck?

**Comment by javiercn** [comment]
Hi. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

**Comment by Elringus** [comment]
> 
> 
> Are there already exist the way to setup and write blazor and C# in `vscode.dev` ? If not then is there any progress or stuck?

Afaik, there is none and it's not even planned: https://github.com/dotnet/aspnetcore/issues/37910#issuecomment-954762657

The PR that resolves one of the blocking issues has been moved to 7.0 milestone: https://github.com/dotnet/runtime/pull/54640

I have the same needs and am currently experimenting with 6.0 branch trying to compile WASM runtime as a single-file js UMD library, which can be used in vscode. Will notify here if it'll get me anywhere.

**Comment by Thaina** [comment]
Thank you very much for your infos. I would hope this would possible soon

**Comment by Elringus** [comment]
As promised, here is the solution: https://github.com/Elringus/DotNetJS 

It allows compiling a C# project into single-file UMD library, which can be consumed in any JavaScript environment, including VS Code's web extensions. Here is a sample extension, that works both in desktop and web versions of VS Code: https://github.com/Elringus/DotNetJS/tree/main/Examples/WebExtension
