### ISSUE TITLE
Expose `ElementReference` through `EventArgs`  or through  `on<event>` delegate

### ISSUE THREAD

**Issue by huunab** [dotnet/aspnetcore#37733]
### Description
Currently the `ChangeEventArgs.Value` coming from `<input type="checkbox">` returns a "true" or "false", which is great as "checked" is the most common value, but actually  `<input type="checkbox">` can have a real value to which we do not have access too.

We can of course query that data by using JSInterop and adding @ref to the element we want to query, but unfortunately that is not too scalable, once you start having more than one checkbox and even tons of it.

### Describe the solution you'd like

Customer should potentially be able to access a `ElementReference` via `EventArgs.Target` property, and so we can do things like this:

```razor
@inject IJSRuntime JS

<input type="checkbox" @onchange="HandleChange">

public void HandleFlavourChange(ChangeEventArgs args)
{
    string value = await JS.InvokeVoidAsync("value", args.target);
    Console.WriteLine(value)
}
```

Alternatively we can just receive the `ElementReference` as second parameter 

```razor
@inject IJSRuntime JS

<input type="checkbox" @onchange="HandleChange">

public void HandleFlavourChange(ChangeEventArgs args, ElementReference target)
{
    string value = await JS.InvokeVoidAsync("value", target);
    Console.WriteLine(value)
}
```

**Comment by mkArtakMSFT** [comment]
As @javiercn has pointed out, you can achieve what you're trying to do using [Custom Event Args](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0#custom-event-arguments) feature. Hope that helps.
