### ISSUE TITLE
Issue with runing dotnet webApp after Edited the Index page

### ISSUE THREAD

**Issue by jamhaka** [dotnet/aspnetcore#37743]
![image](https://user-images.githubusercontent.com/48535096/138079096-f090d449-ae33-44d0-9b43-91e4ac29796c.png)

**Comment by mairaw** [comment]
It seems this is about the ASP.NET tutorial at https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/intro

Please make sure you're editing the .cshtml file and not .cs file. Maybe delete the folder and start over the tutorial?
