### ISSUE TITLE
Optional Certificates - With Host names instead of IP's

### ISSUE THREAD

**Issue by conkman** [dotnet/aspnetcore#37753]
@Tratcher I am looking to use your sample to integrate Azure API Manager (APIM) with an on prem Service Fabric cluster at one of my clients.  What would it take to use host names in your Sample instead of IP's?  You mentioned this in the Readme of the sample.  But  I am having a hard time finding a solution that could use subdomains.  Would I need to go the route that @leastprivilege went in creating Middleware to check the pipeline?

https://github.com/dotnet/aspnetcore/tree/9ce4a970a21bace3fb262da9591ed52359309592/src/Security/Authentication/Certificate/samples/Certificate.Optional.Sample

**Comment by Tratcher** [comment]
We should update that sample.

**Comment by lbosquett** [comment]
I would like to pick this issue to update the docs if still avaliable.
I already have an idea of how change the code using the `TlsHandshakeCallbackOptions` and can make a pull request to change it.

**Comment by Tratcher** [comment]
@lbosquett yes please.
