### ISSUE TITLE
using AssemblyInfo.cs for "ASP.NET Core Web App" : Razor ". Views" dll gets version "0.0.0.0"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/using-AssemblyInfocs-for-ASPNET-Core-/1554437)._

---
[severity:It bothers me. A fix would be nice]
## Context ##
We build our product (around 170+ projects, tests included) on Azure DevOps.  It is currently made up of . NETFramework projects (majority) but also .NET Standard and .NET (Core) 5  projects.  The idea is to have all assemblies of a particular build share the AssemblyVersion and AssemblyFileVersion. 

For this, one AssemblyInfo.cs file in the solution dir is linked to by all projects.
This is mentioned as a supported way of specifying the AssemblyVersion - for 'old style'  as well as 'Sdk'-style csproj project files.
We want to concentrate the versioning into one file as a "single point of version numbering", and because of the mix of projects, this is with AssemblyInfo.cs.

On DevOps, the file is manipulated by a pipeline task to record info that identifies the build, the source version (git hash) etc. as it is important for us (our support people) to know from which build (and so what source) a binary originated.

However, it appears that for .NET 5 Razor projects, the additionally generated ". Views.dll" assembly only gets a version number different from 0.0.0.0, if numbering is done via properties in the project file.

## Reproduction steps ##
1. start and build a new app called MyProject
    **dotnet new webapp**
then
**dotnet build**
1. Verify : both MyProject.dll as MyProject.Views.dll have AssemblyVersion "1.0.0.0" (the default)
1. add a file AssemblyInfo.cs
With contents : 
[assembly:System.Reflection.AssemblyVersion("1.0.0.0")]
then clean and build:
**dotnet clean**
**dotnet build**
1. Verify : MyProject.Dll has AssemblyVersion "1.0.0.0", MyProject.Views.dll has AssemblyVersion "0.0.0.0"

## Workaround ##
In Directory.build.props, add a PropertyGroup where:
*   **Version is to "1.0.0"
*  **GenerateAssemblyInfo** is set to **false** _:a file MyProject.RazorAssemblyInfo.cs is not generated_ 
*  **GenerateAssemblyVersionAttribute** is set to **true** _: af file MyProject.RazorTargetAssemblyInfo.cs is generated_

## Conclusion ##
Contrary to the documentation, for "Web/MVC/Razor Pages" projects, using AssemblyInfo.cs produces an additional . Views assembly with _no_ version, unless some trickery with build properties I consider internal to Razor, that could just be broken by a next update to the SDK

---
#### Feedback Bot on 10/14/2021, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/18/2021, 03:22 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
To add to @mkArtakMSFT's comment, you could consider assigning the `AssemblyVersion` MSBuild property rather than manually generating files with version attributes (since the SDK already knows how to generate and update these). Razor's view assemblies will use `AssemblyVersion` by default, unless a `RazorAssemblyVersion` is specified.
