### ISSUE TITLE
Incorrect groupIdentity/Identity for protobuf item template.

### ISSUE THREAD

**Issue by phenning** [dotnet/aspnetcore#37815]
The protobuf item template authoring is incorrect. 

The groupIdentity was updated to include version information while the idetnity should have been updated instead.

This resulted in Visual Studio being unable to find this template. This can be worked around in the Visual Studio template engine host by performing an additional lookup when the vstemplate stub invokes the real template engine template.

However, while we have a workaround for this now, this should be corrected in 6.0.1

We should update this for 6.0.1

**Comment by captainsafia** [comment]
@hcchappy This bug was fixed in 6.0.1. You might need to update your SDK version.

**Comment by captainsafia** [comment]
Closing since this has been resolved.
