### ISSUE TITLE
QUESTION: Is it possible to create a query parameter name transformer for blazor?

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/aspnetcore#37811]
This is related to `[SupplyParameterFromQuery]` attribute in .NET 6. The question itself: is it possible to set a default parameter name transformer if I want, for examle, automatically map all parameter names in camel casing rather than default pascal without explicitly specifying new parameter name as attribute propery? For example, for json we can set JsonNamingPolicy and do with propery names whatever we like. Is there something like this for blazor .NET 6 query parameters?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
