### ISSUE TITLE
Blazor wasm custom identity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37813]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-wasm-custom-identity/1518563)._

---
Visual Studio has a great template for creation Blazor Webassembly with Individual Account.
The only one problem that all works fine with default EF MsSQL database.

```c#
services. AddIdentityServer()
            . AddApiAuthorization<ApplicationUser, ApplicationDbContext>()
```

As long as I try to change it, application doesn't work anymore. For sample
https://damienbod.com/2017/04/14/asp-net-core-identityserver4-resource-owner-password-flow-with-custom-userrepository/

```c#
services. AddIdentityServer(
                    
. AddInMemoryIdentityResources(Config.GetIdentityResources())
                . AddInMemoryApiResources(Config.GetApiResources())
                . AddInMemoryApiScopes(Config.GetApiScopes())
                . AddInMemoryClients(Config.GetClients())
                . AddCustomUserStore();
```
I receive the error
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load settings from '_configuration/[Client name]'
      Error: Could not load settings from '_configuration/[Client name]'
          at Function.createUserManager (https://localhost:44373/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5893)

Can you add a template with customizable user storage as I need to use micro-services for sample. Or at least create a description how to do it.
I already did custom storage for Identity so I can write
            
```c#
services. AddDefaultIdentity<ApplicationUser>(options => options. SignIn.RequireConfirmedAccount = true)
                . AddRoles<IdentityRole>()
                . AddCustomStore(new CustomConnectionFactory());
```

Thanks Alex

---
#### Feedback Bot on 8/31/2021, 11:18 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by AlexNek** [comment]
Thanks for the answer but I think there are some misunderstanding.
I don't want to use any login and I want to have great product from Microsoft.

First, I have the blazor server project with Microsoft Identity Core and my own identity REST API. With help of  [IUserStore](https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity#userstore) and scaffolded Identity.
Second, I need a blazor PWA project which use the same identity REST API and the same identity pages.

As you remove cryptography completely from standalone blazor I can use blazor hosted projects only.
You standard template is great
![image](https://user-images.githubusercontent.com/2191467/139599440-208f5e88-8d35-4447-ad21-2e850f5c9ce1.png)
but AddApiAuthorization doing too many things, like managing of
https://<domain>/_configuration/BlazorHosted.Client
https://<domain>/.well-known/openid-configuration
If I remove AddApiAuthorization then I need to write a lot of additional code

>...not something we can
As long as you provide something similar as IUserStore, I think it could be possible.

I don't want to use angular, ionic-capacitor - I want to use blazor and MAUI for our new projects but for "fighting" I need a good advantages of the last ones.
