### ISSUE TITLE
Blazor Server app not terminating circuit as expected when an exception is rethrown in an event handler

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#37814]
### Describe the bug
I am rethrowing an exception in an event handler and expect a circuit termination.

### To Reproduce
I have a Blazor page with several components and the following code in the code-behind:
```
        protected async Task GridRowClicked(string caseIdentifier)
        {
            try
            {
                // Code here purposefully generates an exception
            }
            catch (Exception ex)
            {
                pToastService.ShowError(ex.ToString(), "Error in GridRowClicked in DashboardPage.razor.cs");
                throw;
            }
        }
```
When I create the exception, I see the Toast notification but then execution continues.

On the same page I have similar code in OnInitializaedAsync and the rethrow does as expected, ie, a circuit termination occurs.

### Exceptions (if any)
None, and this is the issue

### Further technical details
- ASP.NET Core version: .Net 6 RC2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 17.0.0 Preview 6.0
```
C:\Solutions\OHI\Optimiser\FindLargeWorkflows\bin\Develop_Server\net6.0>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.414 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\OHI\Optimiser\FindLargeWorkflows\bin\Develop_Server\net6.0>C:\Solutions\OHI\Optimiser\FindLargeWorkflows\bin\Develop_Server\net6.0>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.414 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\OHI\Optimiser\FindLargeWorkflows\bin\Develop_Server\net6.0>

**Comment by SteveSandersonMS** [comment]
I think this is a bug in Material.Blazor. On [this line](https://github.com/Material-Blazor/Material.Blazor/blob/main/Material.Blazor/Components/Grid/MBGrid.cs#L813), it's discarding the callback's task, so even if that task completed with an exception nothing else will know about it. If this was changed to:

```
return OnMouseClick.InvokeAsync(newRowKey);
```

(with the enclosing method being changed to return `Task`) then the exception would not be lost.

As a sidenote, I noticed the rendering logic in Material.Blazor will produce inefficient diffs due to incorrect use of sequence numbers. For example, see all the `rendSeq++` expressions in [here](https://github.com/Material-Blazor/Material.Blazor/blob/main/Material.Blazor/Components/Grid/MBGrid.cs#L239). More info about correct usage can be found at https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-6.0#sequence-numbers-relate-to-code-line-numbers-and-not-execution-order

Closing as external.

**Comment by MarkStega** [comment]
@SteveSandersonMS 

1) Changing the InternalMouseClick method to return a Task per your comment makes does the trick. That was a good catch, I never even thought to look at the invoking method. Thanks for spending the time to find what was clearly my error. Unfortunately, I can't remember what my original issue was that made me build the sample repository so I need to keep watching for that.

2) I've read the discussion of sequence numbers quite a few times and do not see a methodology to follow in MBGrid. I had tried the open/close region suggestion but it made no perceptible difference.  There are an arbitrary number of rows to be displayed (usually less than 100, occasionally as many as 2000). In any case, with the dataset sizes in real life use the UI updates are very fast so I am not too worried about the 'sub optimal' efficiency. For performance, it was actually much more important to prevent re-renders when no parameters changed hence the use of SetParametersAsync and the hashing of the incoming parameters.

Thanks again...
