### ISSUE TITLE
"An item with the same key has already been added." in Blazor Webasm

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/aspnetcore#37825]
### Describe the bug
In a Blazor Webasm Hosted Application (but launched as non hosted) I get the exception reported below. The exception (that can be seen from the browser console) gets raised twice sequentially. "Egea.Electron.Web.App", the key that raise the exception, is the main Razor component, the one added with ```builder.RootComponents.Add<App>("#app");```. It gets explicitly added only once, and the error appeared out of nowhere today, while yesterday the project was doing fine. The only thing I can think of is that I have updated from VS2022 RC1 to RC2. The project is currently targeting .NET 5.

### To Reproduce

I have no idea on how to reproduce, an app created from zero works fine and I can't show my project/is too complex to be shown

### Exceptions (if any)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An item with the same key has already been added. Key: Egea.Electron.Web.App
System.ArgumentException: An item with the same key has already been added. Key: Egea.Electron.Web.App
   at System.Collections.Generic.Dictionary`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryInsert(Type key, String[] value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Add(Type key, String[] value)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(IEnumerable`1 componentTypes)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(IEnumerable`1 assemblies)
   at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)

### Further technical details
- ASP.NET Core version: 5.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Using Visual Studio 2022 17.0.0 RC2 and Visual Studio 2019 16.11.5
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (che rispecchia un qualsiasi file global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

Thank you in advance for your help,
Manuele

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
