### ISSUE TITLE
. net 6 blazor release compression problem

### ISSUE THREAD

**Issue by berkerdong** [dotnet/aspnetcore#37836]
Hello, In the Blazor project of .net 5, the files in the wwwroot folder are automatically compressed into br and gz compressed files when they are released, but this function seems to have disappeared in the Blazor of .net 6. When the Blazor project of .net 6 was released, only the _ framework folder generated br or gz compressed format files. I didn't do any compression processing when I added it to wwwroot. I want to compress the files in wwwroot. 
How should we deal with it?

**Comment by thepra** [comment]
so... is there a way add back such compression to the files in wwwroot?

**Comment by berkerdong** [comment]
> so... is there a way to add back such compression to the files in wwwroot?

I haven't found any way yet.
