### ISSUE TITLE
VS2022 RC2 Blazor exception handling issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37849]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-RC2-Blazor-exception-handling-iss/1562121)._

---
I've created a new Blazor webassembly hosted application.
I updated the application to manage login using B2C.
I updated the Fetch data from the example application to load the data using a button, instead of the default OnInitialised method.
I press the button to call an api in the server and I get an exception that I'm capturing (I's not unhandled).
Even after capturing the Exception, the browser still shows the exception and asks for reload. That is the expected behavior for "Unhandled exception" but not when it's handled like in my case.
Also, another side effect is that after that exception, the breakpoints did NOT work anymore. I have to restart the application because the Debugger got messed up.

You can see the recording to see the problem.

---
#### Feedback Bot on 10/24/2021, 07:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rmencia-isv** [comment]
Also, something that I noticed is that after those exceptions, in a page refresh (F5), the debugger disconnects also after those exceptions.

I can't really create steps, I won't have time the next few weeks due to my everyday paid job requirements. Last examples and recordings took me a couple of hours of my unpaid time, which I don't have at the time. Maybe someone from your test team can follow the recording with the provided project.

**Comment by javiercn** [comment]
@rmencia-isv we appreciate the effort it takes to create a repro and repro steps.

I tried the project you provided personally and I'm not able to observe the behavior you are noticing, without a way of triggering the behavior its impossible for us to do anything. We don't have the bandwidth to try things until we find a problem as we might spend a significant amount of time without yielding results. We trust our E2E tests to ensure that the feature is working as expected.

If this is indeed an issue, then we will see more reports for it and maybe then we can act. Until then, I don't think we can make any progress.

**Comment by rmencia-isv** [comment]
What I have noticed also is that F5 in the browser disconnects the debugger. I'm not sure if that is something related or different.

**Comment by mkArtakMSFT** [comment]
@rmencia-isv given that we were unable to reproduce your issue using the repro project you've provided. Unfortunately, at this point we don't know how else to help you.
Maybe repairing your VS  installation would be a good next step. If that doesn't help - [StackOverflow](https://stackoverflow.com) would be a better place to try to find a solution for your specific problem.
