### ISSUE TITLE
Consider Integrating IResult into the request pipeline

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#37851]
Today with Minimal APIs and `RequestDelegateFactory`, any `IResult` instance returned by a route handler delegate is executed immediately. This prevents other middleware in the pipeline from being able to inspect of even modify the `IResult` before it's executed, as by the time control is returned to the middleware the `IResult` has already been executed. The ability to support delayed execution of the `IResult` and have the instance be available to middleware that is running after the endpoint would enable more opportunities for aspect-oriented operations and/or composition models that build upon and further extend the middleware/routing/endpoint model.

We should consider promoting `IResult` to be an intrinsic part of the request model. It would likely involve a new middleware that is the mirror of the routing middleware, wherein routing middleware does route matching and endpoint selection, and this new middleware does endpoint result execution. The middleware would be added to the pipeline by default (likely in the very first position) but would support detecting when it has been manually added in another position and ensuring execution occurs at that place instead (similar to how the routing middleware works today).

A new request feature, `IEndpointResultFeature`, would store the `IResult` returned by the endpoint so that middleware could inspect, modify, or even replace it, before it's eventually executed by the `EndpointResultExecutionMiddleware`. A middleware could even set an `IResult` in the middle of the pipeline and short-circuit the request such that an endpoint is never invoked, but the `IResult` is still executed upon the unwinding of the request pipeline.

```
1. Server -> 2. EndpointResultExecutionMiddleware -> 3. RoutingMiddleware -> 4. (rest of pipeline) -> 5. EndpointMiddleware
```

In the diagram above:
1. The server dispatches the request to the middleware pipeline
2. The `EndpointResultExecutionMiddleware` calls the next middleware in the pipeline
3. The `RoutingMiddleware` matches the incoming request against the route table and if there's a match sets the resultant endpoint
4. The other middleware in the pipeline are executed
5. The `EndpointMiddleware` executes the endpoint and the `IResult` returned is set in the `IEndpointResultFeature`
6. The request pipeline unwinds and middleware on the way are able to observe, mutate, or even replace the `IResult`
7. The `EndpointResultExecutionMiddleware` retrieves the `IResult` from the `IEndpointResultFeature` and if one is present, executes it

The existing behavior of the `RequestDelegateFactory` would be updated so that in the cases the route handler delegate does not return an `IResult` but rather an inferred result is "executed" that instead an `IResult` instance is created and set on the request so that all delegate behaviors, inferred or explicit, are observable and mutable by the rest of the middleware pipeline.

**Comment by adityamandaleeka** [comment]
Update: since we're working on endpoint filters right now, which should address some of the use cases for this, the current plan is to wait and see how they do in practice and whether we hear about pain-points that need to be addressed before deciding to go down this path.

**Comment by DamianEdwards** [comment]
Now that we have endpoint filters I'm don't think there's any reason to pursue this idea anymore.
