### ISSUE TITLE
Add maxLength in PasswordOptions

### ISSUE THREAD

**Issue by DennisThePineapple** [dotnet/aspnetcore#37866]
### Is your feature request related to a problem? Please describe.

At the moment, there is no way to easily set a maximum password length in PasswordOptions. According to OWASP, it's best to set a default password max length in order to prevent [long password Denial of Service attacks.](https://www.acunetix.com/vulnerabilities/web/long-password-denial-of-service/)

### Describe the solution you'd like
Add in another option for maxLength in PasswordOptions, with a reasonable default value.

**Comment by blowdart** [comment]
The linked too page is talking about a 1million character password. The default request limit would kick in long before then :)

Right now you can do it yourself by scaffolding the UI everywhere, and then also check on the backend. 

We'll look at this for 7

**Comment by adityamandaleeka** [comment]
After some discussion, we don't believe there's an attack vector here. Closing this issue.

cc: @blowdart @GrabYourPitchforks
