### ISSUE TITLE
Incorrect info tooltip for 'Enable OpenAPI support' checkbox

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37864]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-info-tooltip-for-Enable-OpenA/1563452)._

---
[severity:It bothers me. A fix would be nice]
When creating a new "ASP.NET core Web API" project in Visual Studio 2022 (v17.0 Preview 6.0), the **Additional Information** dialog that appears during the creation process has a checkbox labelled 'Enable OpenAPI support'. It has a little info icon next to it, and if you mouse over that, it displays a tooltip.

This tooltip's text describes the _opposite_ of what the checkbox does

! [image.png] (https://aka.ms/dc/image?name=B40786b4b22e64fdd938b6d5377529e30637708221348249618_20211026-061532-image.png&tid=40786b4b22e64fdd938b6d5377529e30637708221348249618)

Checking the button enables OpenAPI support. But the tooltip says it disables OpenAPI support.

Presumably whoever wrote that was thinking "I'll describe what happens when they uncheck this" because it is checked by default. But there are two problems here;

1. it displays the same text whether checked or not, so describing what it would do if you uncheck it is misleading when it's already unchecked
2. the checkbox immediately above it doesn't use this inverted logic - its tooltip says what happens when it is checked

(The checkbox above also explicitly states what happens when unchecked in the main text of the checkbox. Perhaps the OpenAPI one could follow suit, although I think that explicit description of the unchecked behaviour is probable more important on the top checkbox because this is really switching between two quite different modes, whereas the lower checkbox just turns a feature on or off. Arguably that top checkbox should be a pair of radio buttons.)

---
#### Feedback Bot on 10/26/2021, 00:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/38062
