### ISSUE TITLE
Virtualize component is missing support to virtualize DataTable.Rows

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#37875]
I have a large DataTable from which I want to display every row. 

Right now I have this code:
```
@foreach (DataRow row in preislistenImportService.Data.Rows)
{
    <tr>
                <td>@row[i].ToString()</td>
    </tr>
}
```

This results in slow performance because my DataTable has many rows. So I wanted to use Virtualization. The issue I am facing right now is that DataTable.Rows returns an object instead of a DataRow. So my context is unknown for the compiler. It suggested me to add TItem manually but this doesn't work either.
```
<Virtualize TItem="DataRow" Items="preislistenImportService.Data.Rows" Context="row">
<tr>
    <td>@row[i].ToString()</td>
</tr>
</Virtualize>
```

**Comment by pranavkm** [comment]
@MarvinKlein1508 the issue is that `DataRow` is a non-generic collection while Virtualize expects a generic `ICollection<T>`. Doing a `Cast<>` doesn't help since it produces an `IEnumerable<>` instead. What would work is to use the ItemsProvider parameter instead:

```razor
<Virtualize ItemsProvider="GetRows" Context="row">
   
</Virtualize>

@code{
    ValueTask<ItemsProviderResult<DataRow>> GetRows(ItemsProviderRequest request)
    {
        return new(new ItemsProviderResult<DataRow>(
            dataTable.Rows.OfType<DataRow>().Skip(request.StartIndex).Take(request.Count),
            dataTable.Rows.Count));
    }
}
```
