### ISSUE TITLE
Docker compose Linux container error "The path must be absolute."

### ISSUE THREAD

**Issue by p2pbsh** [dotnet/aspnetcore#37876]
### Describe the bug
Running a new web app project from the VS templates via docker compose with Linux containers causes a 'path must be absolute' error in WebApplication.CreateBuilder

Adding 'StaticWebAssetsEnabled' to false project causes exception to go away, but breaks web site. 

There are a bunch of other cases raised for this, but all now closed and marked as resolved. However, myself and several other users still appear to be experiencing in RC2. 

Weird thing is, this was working fine yesterday and just started experiencing this morning. Rolling back my mornings changes made no difference and now I see the same problem creating a fresh, simple web app from the templates. Is there a hidden config folder or some such for VS / Docker that could need flushing to resolve the problem? Only thing I can think of, proper head scratcher. 

#36180
#35285

@javiercn 
@ProgrammerAl
@sloscialo 
@cetindogu

### To Reproduce
Create .NET core web application with docker (linux)

### Exceptions (if any)
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args)

### Further technical details
Visual Studio 17.0.0 RC3 and .NET 6.0.0-rc.2.21480.5.

<details>
  <summary>dotnet --info Output</summary>

.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

</details>

**Comment by javiercn** [comment]
@p2pbsh thanks for contacting us.

The delta here seem to be Docker compose,

![image](https://user-images.githubusercontent.com/6995051/139914531-7048b6c3-e76f-4095-bb68-12f453e5908b.png)

The file tooling creates is correct but doesn't get used
![image](https://user-images.githubusercontent.com/6995051/139915184-723a5338-3f65-4b70-b950-f56d590fbff3.png)

**Comment by p2pbsh** [comment]
Hi @javiercn, thanks for taking a look at the issue. Just trying to get my head round what you're explaining, is there anything I can do to solve the problem my side or is it down to a docker compose related bug?

**Comment by javiercn** [comment]
@p2pbsh I was just adding information here for the record, It's a VS tooling issue for which we've already looped in the right folks.

**Comment by NCarlsonMSFT** [comment]
@javiercn I suspect you are seeing the same issue as in this bug: https://developercommunity.visualstudio.com/t/Not-able-to-debug-a-Blazor-Server-App-wi/1556545
There was a regression in docker-compose v2 that broke some of our handling for static assets files. If you disable docker-compose V2 in the settings that should unblock you:
![image](https://user-images.githubusercontent.com/14239288/140577193-10b7fc98-65b1-44b8-ad36-73bf00f3ee82.png)

**Comment by ProgrammerAl** [comment]
@NCarlsonMSFT I just tried this on my machine just now and still had the same issue after disabling Docker Compose v2. I restarted Docker and VS a couple times to be sure.

**Comment by p2pbsh** [comment]
Unfortunately, disabling V2 didn't resolve the issue for me either.

**Comment by NCarlsonMSFT** [comment]
@p2pbsh, @ProgrammerAl I'll try and create a clean repro machine and investigate further.

**Comment by NCarlsonMSFT** [comment]
@p2pbsh, @ProgrammerAl I was able to reproduce the issue on a clean install of the latest VS 2022 and Docker Compose tools. I think the reason you are still seeing the issue after disabling Compose V2 is that I forget to mention you need to do a rebuild (or delete the static assets files) to force regeneration of that bad file. Once I did the rebuild the error went away for me.

**Comment by p2pbsh** [comment]
@NCarlsonMSFT Just went back and double checked and you are indeed correct. Cleaning my solution after disabling V2 removed the error. Thanks a lot for your help.

**Comment by ProgrammerAl** [comment]
Adding the same comment. Did a rebuild on my solution and it works. Thanks for the find!

**Comment by cdavernas** [comment]
Disabling docker-compose V2, deleting images, cleaning the solution, restarting VS: nothing seems to fix it for me. I'm desperate: I cant work anymore on most my docker-compose projects. Anyone has a fix?

**Comment by NCarlsonMSFT** [comment]
@cdavernas please open an issue in https://github.com/Microsoft/DockerTools. Also can you please provide a minimized repro so that we can investigate?

**Comment by WillMarcouiller** [comment]
> @p2pbsh, @ProgrammerAl I was able to reproduce the issue on a clean install of the latest VS 2022 and Docker Compose tools. I think the reason you are still seeing the issue after disabling Compose V2 is that I forget to mention you need to do a rebuild (or delete the static assets files) to force regeneration of that bad file. Once I did the rebuild the error went away for me.

This has done it for me too!  Been searching for the issue for days!  Thx for sharing!

**Comment by marcelbeeker** [comment]
Disable docker-compose V2 and a rebuild of the solution worked for me too! Thanks!

**Comment by MayueCif** [comment]
Disable docker-compose V2 it worked for me! Thanks!

**Comment by divyeshdesanisos** [comment]
Disable docker-compose V2 and a rebuild of the solution worked for me too! 
Thank you very much for your help. Spent lots of time on this.

**Comment by 317jamtay317** [comment]
Disable docker-compose V2 and a rebuild of the solution worked for me too!

**Comment by genevill** [comment]
Disable docker-compose V2 and a rebuild of the solution worked for me too! Thanks!

**Comment by neozhu** [comment]
Has the problem finally been solved? I still can't work at the moment. Is this because of the official image?

**Comment by NCarlsonMSFT** [comment]
@neozhu see https://github.com/microsoft/DockerTools/issues/320 for the latest updates.

**Comment by kibblewhite** [comment]
I'm currently facing the same issue, yes I can confirm that the disabling of compose-v2 does indeed work, but unfortunately, I also need compose-v2 enabled for other projects, so I'm having to disable compose-v2 to get that project running, and then re-enable compose-v2 and rebuild and run the other project while the first project is running.

Microsoft Visual Studio Community 2022 (64-bit) / Version 17.0.5
Docker Desktop 4.4.4 (73704)
Docker version 20.10.12, build e91ed57

**Comment by kibblewhite** [comment]
I'm currently facing the same issue with the following:
- Microsoft Visual Studio Community 2022 (64-bit) / Version 17.0.5
- Docker Desktop 4.4.4 (73704)
- Docker version 20.10.12, build e91ed57

**Comment by NCarlsonMSFT** [comment]
@kibblewhite if disabling docker-compose V2 isn't an option, you can also switch to the preview channel, a fix was released in 17.1 Preview 3

**Comment by kibblewhite** [comment]
> @kibblewhite if disabling docker-compose V2 isn't an option, you can also switch to the preview channel, a fix was released in 17.1 Preview 3

Now with Microsoft Visual Studio Community 2022 (64-bit) / Version 17.1.0 Preview 6.0
But still the exact same issue. Apologies, don't mean to be a pain, I'll try and find a better route to provide feedback once I work out how and what that process is...

**Comment by NCarlsonMSFT** [comment]
@kibblewhite the best place to get support on this would be https://github.com/microsoft/DockerTools/issues/320.
As an aside, my admittedly hopeful knee-jerk would be: having upgraded to the new build you may still need to do a rebuild to clean out the bad generated files.

**Comment by kibblewhite** [comment]
Not sure if I should post this, but here goes, I've been stuck on this issue since November 2021 and I was determined not to give up, so if anyone is in the same boat as me and this post helps them, then it was worth it... Anyways, here's the story:

I was reading this article:
https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties

Popped open my: "docker-compose.dcproj"
And added the following two-lines:
```
      <Configurations>Debug;Release;staging;production</Configurations>
      <DockerComposeBaseFilePath>.\docker-compose</DockerComposeBaseFilePath>
```

Overview of the docker-compose.dcproj file content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" Sdk="Microsoft.Docker.Sdk">
   <PropertyGroup Label="Globals">
      <!-- rest of your config here ... //-->
      <Configurations>Debug;Release;staging;production</Configurations>
      <DockerComposeBaseFilePath>.\docker-compose</DockerComposeBaseFilePath>
   </PropertyGroup>
   <!-- more config here ... //-->
</Project>
```

I now have a working project, happy days 😊
