### ISSUE TITLE
[API Proposal]: Support dotnet watch in launchSettings.json

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/aspnetcore#37896]
### Background and motivation

I often add the following to my `launchSettings.json` file to allow me to run `dotnet watch` on my project. However, hitting F5 to start defaults to running with debugging enabled.

```json
"Watch Kestrel": {
    "commandName": "Executable",
    "executablePath": "dotnet",
    "workingDirectory": "$(ProjectDir)",
    "commandLineArgs": "watch",
    "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
}
```

### API Proposal

I would like an option to be added to `launchSettings.json` which can change the default to start without debugging:

```json
"startWithoutDebugging": true
```

### API Usage

```json
"Watch Kestrel": {
    "startWithoutDebugging": true
    "commandName": "Executable",
    "executablePath": "dotnet",
    "workingDirectory": "$(ProjectDir)",
    "commandLineArgs": "watch",
    "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
}
```

### Alternative Designs

An alternative is to provide a special `watch` `commandName`:

```json
"Watch Kestrel": {
    "commandName": "Watch",
    "workingDirectory": "$(ProjectDir)",
    "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
