### ISSUE TITLE
Redirect_uri not configured with NativeApp client

### ISSUE THREAD

**Issue by Greg7931** [dotnet/aspnetcore#37905]
Hello,

I have the current configuration in my appsettings.json:
  "IdentityServer": {
    "Clients": {
      "UWP": {
        "RedirectUris": [ "https://localhost:8080/callback"],
        "PostLogoutRedirectUris": [ "https://localhost:8080/logout" ],
        "AllowedScopes": [ "openid", "profile" ],
        "AllowedGrantTypes": [ "authorization_code" ],
        "RequireConsent": false,
        "AllowAccessTokensViaBrowser": true,
        "AllowOfflineAccess": true,
        "Profile": "NativeApp"
      }
}

When I tried to read the client through the _configuration URL, we can see the redirect stays the on by default.
![image](https://user-images.githubusercontent.com/24478288/139280916-255248c7-d186-4c24-8b6f-b5b049aba36d.png)

### Further technical details
- ASP.NET Core version: 5..0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2019

Thank you,

**Comment by blowdart** [comment]
Does anything else need AddNativeApp @javiercn? If not, we should kill it off in 7

**Comment by mikekistler** [comment]
This API is not supported in the latest version of .NET.
