### ISSUE TITLE
Clean syntax for Razor-emitting methods (avoiding __builder, _builder2, …)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#37907]
Currently, it's possible for `.razor` files to use methods inside their `@code` blocks that emit markup, e.g.:

```cs
private void SayHello(RenderTreeBuilder __builder)
{
    <h1>Hello!</h1>
}

private void SayHelloWithName(RenderTreeBuilder __builder, string name)
{
    <h1>Hello, @name!</h1>
}
```

This isn't something we've really emphasised or recommended, but it can be useful. However there are two main problems:

1. You have to use the weird parameter name `__builder`
2. Invoking it is only easy if it only takes a single parameter. For example, you can call `SayHello` just by writing `@SayHello` in some other Razor syntax. But to call `SayHelloWithName`, you have to do something like `@SayHelloWithName(__builder, someName)` which is unpleasant at the call site, and is error prone because the correct builder name might really be something like `__builder4` at the call site, depending on the generated code and its nesting. Using the wrong builder name would lead to corrupted output.

We should try to figure out if there would be a better syntax for this.

**Comment by mkArtakMSFT** [comment]
There is a better syntax for this already: https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-7.0#define-reusable-renderfragments-in-code-3
