### ISSUE TITLE
IServerVariablesFeature not supported by Kestrel

### ISSUE THREAD

**Issue by lucapivato** [dotnet/aspnetcore#37939]
Is there any way to read server variables when using ASP.NET Core (Kestrel)? IServerVariablesFeature always returns null. Not 100% sure but I thought it used to work in 3.1 or earlier.

**Comment by Tratcher** [comment]
Server variables are an IIS specific feature. Most of that data is available from other APIs, what you are you trying to find?

**Comment by lucapivato** [comment]
REMOTE_ADDR
REMOTE_HOST
REMOTE_USER
LOCAL_ADDR
LOGON_USER
SERVER_NAME
SERVER_PORT
SERVER_PORT_SECURE
SERVER_SOFTWARE
SERVER_PROTOCOL

Others I could find and rebuild a server variable collection.

**Comment by Tratcher** [comment]
Let's see...
https://docs.microsoft.com/en-us/iis/web-dev-reference/server-variables
REMOTE_ADDR: HttpContext.Connection.RemoteIpAddress
REMOTE_HOST: N/A
REMOTE_USER: HttpContext.User
LOCAL_ADDR: HttpContext.Connection.LocalIpAddress
LOGON_USER: HttpContext.User, though ASP.NET Core doesn't do impersonation.
SERVER_SOFTWARE: N/A
SERVER_PROTOCOL: HttpContext.Request.Protocol

These three are a bit different. Kestrel can map multiple bindings to the same site. The closest API is IServerAddressesFeature. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=macos#aspnet-core-server-infrastructure
SERVER_NAME
SERVER_PORT
SERVER_PORT_SECURE

**Comment by lucapivato** [comment]
Thanks I can reimplement a usable servervariables collection with these and the other headers.
