### ISSUE TITLE
How to set AppInsightKey based on Environment Variable in Blazor wasm Hosted App

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#37953]
I have Blazor wasm Hosted app using .NET 6 RC2.
I have Application Insight Key embedded in Index.html
I have different app insight key for dev, stage & Prod.

How do i read correct key in JavaScript based on where i am deployed ?

```
<script type="text/javascript">
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            cfg: { // Application Insights Configuration
                instrumentationKey: "XXXXXXXXXXXXXXXXX-7a0629a1e08f"
            }
        });
    </script>
```

**Comment by SteveSandersonMS** [comment]
The recommended way to solve this is by putting the key into your `appSettings.*.json` files. This allows you to have different values in different environments. See https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-5.0 for more info.

If you really need to read it from the host `index.html` file, then you can use JS interop to make a call into JavaScript and read the value from the DOM. See https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0 for more info.
