### ISSUE TITLE
Can not use BaseIntermediateOutputPath with v5.0.8

### ISSUE THREAD

**Issue by oakad** [dotnet/aspnetcore#37958]
Issue #20994 closed but not fixed?

A new, template app (v5.0.8, Linux):
> dotnet new blazorserver -o BlazorApp --no-https
> dotnet watch run

Everything works. Let's add Directory.Build.props as suggested in #20994:
```
<Project>
  <PropertyGroup>
    <BaseOutputPath>build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>build\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```
The build breaks horribly:
> Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
>
>  Determining projects to restore...
>  All projects are up-to-date for restore.
> /home/oakad/x4/BlazorApp/obj/Debug/net5.0/BlazorApp.RazorTargetAssemblyInfo.cs(15,12): error CS0579: > Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [/home/oakad/x4/BlazorApp/BlazorApp.csproj]
> /home/oakad/x4/BlazorApp/obj/Debug/net5.0/BlazorApp.RazorTargetAssemblyInfo.cs(16,12): error CS0579: > Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [/home/oakad/x4/BlazorApp/BlazorApp.csproj]
> /home/oakad/x4/BlazorApp/obj/Debug/net5.0/BlazorApp.RazorTargetAssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [/home/oakad/x4/BlazorApp/BlazorApp.csproj]

And so on (binlog is attached).
In many situations it is critically important not to write anything into the source tree. Please fix this at last.
[msbuild.zip](https://github.com/dotnet/aspnetcore/files/7448369/msbuild.zip)

**Comment by SteveSandersonMS** [comment]
If you change the location of the `obj` direction, please make sure you've deleted your `bin` and `obj` directories everywhere in your solution before the next build. Incrementalism can get quite confused otherwise.

If you've already tried this and still face issues, please let us know.

**Comment by oakad** [comment]
I figured out the "delete the other obj dir" part. :-)

However, this issue is more serious than it may seem when factoring the IDE in.

For example, let's say I want to specify the alternative paths explicitly (`-p:BaseIntermediateOutputPath=foo -p:BaseOutputPath=bar`) - the common need for this arises when testing CICD scripting.

If there's an IDE instance running, both my build will not succeed, and IDE tooling may get confused. Therefore, to build something I must make sure that all of the IDE instances are closed in advance and default "obj" dirs removed (seems like "bin" is not causing many issues on its own).

I'd say, this situation must be fixed somehow.

**Comment by javiercn** [comment]
I don't think this is up to us to solve.

What's happening here is that you are switching build configurations between the default `bin` and `obj` folders and your own. If you want to mix and match these configurations, you need to make sure you add `bin` and `obj` to the `DefaultItemExcludes` property explicitly `<DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**`.

The build already excludes these paths by default (it excludes `$(BaseOutputPath)` and `$(BaseIntermediateOutputPath)`).

We would suggest what @SteveSandersonMS  mentioned, which is to clean the environment before changing these properties. (In a CI/CD environment this should not be a problem as you should always be doing a clean build for repeatable results).

If you want to support this scenario for switching paths, you can unconditionally add those to the default list of item excludes as described above. The build can't make the general assumption that you want to avoid those paths and it does the right thing, which is to exclude `$(BaseOutputPath)` and `$(BaseIntermediateOutputPath)`. If you change those in between builds, you are responsible for making sure no old artifacts get in the way.

**Comment by oakad** [comment]
>  The build can't make the general assumption that you want to avoid those paths and it does the right thing

It's not.
No other popular build system behaves this way (and there are quite a few around). Basically, if build destination is moved, the other/previous/default build destination should have no effect whatsoever on the current build.
