### ISSUE TITLE
Blazor HeadOutlet is not pre-rendering

### ISSUE THREAD

**Issue by Anton0123** [dotnet/aspnetcore#37960]
I'm using a HeadOutlet on a server side pre-rendered net6.0 app to set some header tags such as meta description but the HeadOutlet is not populating the head tags until after the page has already rendered which makes search engines ignore it.

``` Razor
@page "/"
@namespace Example.Pages
@using Microsoft.AspNetCore.Components.Web
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
    <base href="~/" />

    <link href="css/site.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
</head>
<body>
    <component type="typeof(App)" render-mode="ServerPrerendered" />

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="/" class="reload">Reload</a>
        <a href="#" class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.server.js"></script>
    <script src="~/outsideHandleContainerJsInterop.js"></script>
</body>
</html>
```
``` Razor
@page "/test"

<HeadContent>
     <meta name="description" content="Hello World">
</HeadContent>
```

Viewing the page in a browser will render the meta tags in the head as expected but doing a get request in insomnia/postman returns the initial headers and a blazor pre-render tag comment
`<!--Blazor:{"sequence":0,"type":"server","prerenderId":"b0376004567c4aaf9c07defc4341e21e","descriptor":"<long string here>"}--><!--Blazor:{"prerenderId":"b0376004567c4aaf9c07defc4341e21e"}-->`

Is this a bug or am I missing something? I need the head to be rendered before or with the rest of the page so search engines can pick it up.

**Comment by willdean** [comment]
Have you looked at this:  https://github.com/dotnet/aspnetcore/issues/37293?

**Comment by Anton0123** [comment]
> Have you looked at this: #37293?

Yes, I'm not entirely sure if I understand how it's implemented but from what I can see I won't be able to put script tags in the header using that method?

**Comment by SteveSandersonMS** [comment]
Using the technique mentioned at #37293 won't change your ability to include script tags.

**Comment by Anton0123** [comment]
> Using the technique mentioned at #37293 won't change your ability to include script tags.

Maybe I just don't get what he means with his post then as I couldn't find a way to put script tags in a razor file
