### ISSUE TITLE
Missing of cookieless session management

### ISSUE THREAD

**Issue by lukecc42** [dotnet/aspnetcore#37978]
Currently all major browser producers are disabling more and more the usage of third party cookies by their browsers. So in this scenario to make apps fully working also in multi host environments (like using apis or iframes) is crucial to provide a way to manage session containers also without cookies.
Legacy ASP.Net framework provided by 10 years ago a way to manage this kind of sessions (cookieless=true in config). Now many standard .net applications are migrating to this feature to keep consistency with new browser policies.
I dont find the equal way to produce the equal result inside the .net core.
I am heading a project group for the porting of our .net legacy applications in the new .net core framework and this results to be a maior issue that will keep our applications on legacy framework for now.
Sure there is the possibility to create a custom session provider but there are many difficulties to produce this on our own, not less the reduction of general compatibility of the application (for example think at the integration of third party session managers or distributed cache providers for clusterization scenarios)

Regards

**Comment by blowdart** [comment]
We will not be bringing back cookieless sessions, they're an insecure technology which cannot be fixed.

Session cookies are never third party anyway, so the disablement of third party cookies would not be affected by such an action, the only thing that's close would be the not sending of first party cookies from third party sites which is already standardized with the same site cookie attribute and can be controlled by the developer.

**Comment by lukecc42** [comment]
Sorry but I dont understand your statements

1) Why cookieless sessions are unsecure? By my knowledge the only change between cookie session to cookieless is the position of the cookie or session identifier from request header to url path or url parameter. The missing of this force developers to trace the same identification with url path or query parameters, so I really dont understand which is the difference

2) In some scenario the third party cookie usage is mandatory (I mean with cookie sessions). For example when you have to call third party services through api or as in our case (gaming factory) where the presence of multiple iframe layers is mandatory for the application needings. In our case you have a main service running on frontend that authenticates and provide user account infromation and launches sub applications from third party providers in iframe layers, these sub applications are seen by browser as third party and you must keep sessions on these

**Comment by lukecc42** [comment]
Sorry I dont know also if I got exactly your last note on the usage of same site attribute, if you are talking about secure/samesite cookie attributes I think they are are not so standardized, they are often ignored by ios/macos safari (depending on versions), and also I am not so sure google chrome is planning to support them indefinitely, from general web discussions I am more inclined to think the general idea is to avoid in future any third party cookie usage because of the fact they are mainly used for tracking purpose

**Comment by blowdart** [comment]
The attack is known as [session fixation](https://owasp.org/www-community/attacks/Session_fixation) - basically the attack creates a session, sets up an app in a way that they get the desired results and then shares the URI with the session ID they've created. It even has its own [CWE](https://cwe.mitre.org/data/definitions/384.html).

Given that session cookies are _first_ party cookies there's nothing browser makers can do to remove support for session cookies without removing cookie support altogether.

**Comment by lukecc42** [comment]
Ok I read about that but from what I know using cookie session does not prevent at all the risk of session fixation, the real solution for that should be using different sessionId management techniques

About first party cookie, also I disagree, if you have your browser pointing to site A, any iframe inside this pointing to other sites are managing "third" party cookies for all communications (session or not). 
In most cases this kind of communication with third party sites is used for user tracing and not for session management so browser producers are limiting it
Safari in latest versions is starting with "third party" cookie allowing disabled, so you are not able to use cookie sessions in this scenario on third party calls, if not asking the users to explicitly change these settings
Google is planning to cut completely the usage of third party cookies for 2023 (https://blog.google/products/chrome/updated-timeline-privacy-sandbox-milestones/)

**Comment by blowdart** [comment]
But again, that's still 3rd party cookies. Session cookies are 1st party. If you app is being embedded via iframes in someone else's site that's a whole other problem.

**Comment by lukecc42** [comment]
It is not an another problem, it is our problem with this porting
I assure you that in our industry (gambling) the needing of iframe integrations is primary
Anyway I dont want to make it too long this was just a suggestion
We will find another way

**Comment by blowdart** [comment]
Maybe a short lived JWT token in the URL instead? That at least would be signed and of a limited lifetime, then use that as a primary key into your session cache somehow.

**Comment by davidfowl** [comment]
This is something we need to document. Our position and what the migration looks like for applications that were using this on System.Web and need to migrate.

**Comment by lukecc42** [comment]
Yes a token identification to retrieve data by cache can be a solution. But what I am not happy with is that is non standard solution. In any case we need to extend or integrate our solution we are on our own.
For example in server farm where we have hard load we use Alachisoft NCache session manager to clusterize session usage, by the way they use the .net session standard specifications, so that implies not having cookieless implementation in their .net .core version.
Also sessions in general take with them the session locking mechanism to serialize call sequences that is hard to replicate in a custom way.

**Comment by adityamandaleeka** [comment]
> This is something we need to document. Our position and what the migration looks like for applications that were using this on System.Web and need to migrate.

Moving to .NET 7 milestone to do that^.

**Comment by MrMicardo** [comment]
Session-handling should not be part of an URL. URLs should allow to be remembered as bookmarks, and navigated to at a later point in time, in this case starting a new session. Cookies (1st party) are perfectly designed to fulfill the task of session identification, and therefore should be used for it.

The problem of iframes accessing another app on behalf of the primary session is a different problem, and Google has quite some proposals to cover this need (CHIPS, 1st-party-sets, https://developer.chrome.com/en/blog/progress-in-the-privacy-sandbox-2021-12/ ). Please do not propose session-handling via URLs, this would be an awful solution.
