### ISSUE TITLE
Blazor Server limit @bind content size

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#37973]
Is there a way to limit the total size of messages in signalR.

In the following code

```
<input @bind="Text"/>

@code {
    string Text = string.Empty;
}
```
If an attacker inputs a very big string, such as a 1GB string as a payload, how can I make sure the payload never reaches the server? Is there a way to limit the total message size

**Comment by SteveSandersonMS** [comment]
A maximum size limitation is already imposed by default. SignalR has a "maximum message size" which defaults to 32KB. You can configure `MaximumReceiveMessageSize` using https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=dotnet#configure-server-options-1.

There's more information at https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-5.0#buffer-management
