### ISSUE TITLE
How to declare a method target attribute on `BuildRenderTree`?

### ISSUE THREAD

**Issue by ibocon** [dotnet/aspnetcore#37970]
### Is your feature request related to a problem? Please describe.

I want to declare a method target attribute on `BuildRenderTree`.

```razor
@* Sample.razor *@
@{
    // where should I put `[Logging(LogLevel.Debug)]`?
    base.BuildRenderTree(__builder);
}

@code {
    [Logging(LogLevel.Debug)]
    protected override void OnInitialized()
    {

    }
}
```

### Describe the solution you'd like

I do not know what would be a best approach to declare Attribute on `BuildRenderTree` method in razor syntax.

### Additional context

I use `Castle.DynamicProxy` to intercept logging.

**Comment by SteveSandersonMS** [comment]
We don't have a feature for this. However, depending on how your logging system works with inheritance, you might be able to declare your own base component class and inherit from it:

```cs
public class MyComponentBase : ComponentBase
{
    [Logging(LogLevel.Debug)]
    protected override void BuildRenderTree(RenderTreeBuilder builder) {}
}
```

... and then in your `.razor` files:

```razor
@inherits MyComponentBase
```
