### ISSUE TITLE
Error when trying to use Quic with current .NET 6 RC

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/aspnetcore#37971]
### Description

I have the currnt .NET 6 RC and referenced the last Quic Preview Package from Nuget

### Reproduction Steps

1. reference last Quic Packge from nuget
2. add following code to server startup:

```c#
               .UseQuic(options =>
               {
                   options.Alpn = "h3-29"; // Shouldn't need to populate this as well.
                   options.IdleTimeout = TimeSpan.FromHours(1);
               })
```

and add also:

```c#
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
```

### Expected behavior

Server should start and possible use quic

### Actual behavior

I got this exception:

{"Could not load type 'Microsoft.AspNetCore.Connections.Experimental.IMultiplexedConnectionListenerFactory' from assembly 'Microsoft.AspNetCore.Connections.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.":"Microsoft.AspNetCore.Connections.Experimental.IMultiplexedConnectionListenerFactory"}	System.TypeLoadException

**Comment by Tratcher** [comment]
Can you share your project dependencies? You shouldn't need any nuget packages for quic now. You also don't need to call UseQuic.

**Comment by jogibear9988** [comment]
@Tratcher 
then maybe this is the issue.

How do I setup quic in the Net6 RC? Only set 

         listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;

Will it automaticaly be used by Chrome/Edge?

Any why does this package exist for 6:
https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic/

**Comment by Tratcher** [comment]
@jogibear9988 check out the updated 6.0 docs:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-6.0

Yes, setting Http1AndHttp2AndHttp3 should be enough. The main limitation when testing with browsers is that they will not use self-signed certificates like the kestrel dev cert for HTTP/3, which makes localhost testing very difficult. I've found that HttpClient is the easiest to test with locally.

> Any why does this package exist for 6:
> https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic/

That package was moved into the framework after preview4.

@adityamandaleeka can someone please mark the Experimental.Quic 6.0 preview packages as obsolete on nuget?

**Comment by adityamandaleeka** [comment]
> > Any why does this package exist for 6:
> > https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic/
> 
> That package was moved into the framework after preview4.
> 
> @adityamandaleeka can someone please mark the Experimental.Quic 6.0 preview packages as obsolete on nuget?

@mkArtakMSFT Do you have the access to do that?

**Comment by jogibear9988** [comment]
I don't know that browsers don't support it on loopback. Thanks for the information.
 Do browsers use http3 at all at the moment?
Cause when I open google with newest chrome/edge I'll only see http2 in the network pane.

**Comment by Tratcher** [comment]
Loopback is not the issue, it's the stricter certificate requirements. See https://github.com/dotnet/AspNetCore.Docs/issues/23700.

Yes, browsers are using h3 by default on services that support it. While that's not every site or resource, there are many.
