### ISSUE TITLE
TypeNameHandling not working with abstract classes: "Type specified in JSON 'T' was not resolved."

### ISSUE THREAD

**Issue by speyck** [dotnet/aspnetcore#37986]
### Describe the bug
I am currently experimenting with EF and Blazor. In my asp.net project I have a class that holds a list of an abstract type:
```csharp
public class Survey 
{
    public int ID { get; set; }
    public string Title { get; set; }
    public virtual ICollection<Step> Steps { get; set; }
}
```
And here's the Step model which is abstract:
```csharp
public abstract class Step 
{
    public int ID { get; set; }
    public string Title { get; set; }
}
```
And here's one of the inheriting classes of step:
```csharp
public class Text : Step
{
    public string Placeholder { get; set; }
}
```

### To Reproduce
The project is public on here on Github, but it might be too complex to understand so I will try to still sum it up.
Here's the repo: [speyck/simple-surveys](https://github.com/speyck/simple-surveys)

In my [Startup.cs](https://github.com/speyck/simple-surveys/blob/main/SimpleSurveys/Server/Startup.cs) file (in the server project, the API) I added the following line of code to enable `TypeNameHandling`:
```csharp
services.AddControllersWithViews().AddNewtonsoftJson(options =>
{
    options.SerializerSettings.TypeNameHandling = TypeNameHandling.All;
});
```
Now when I try to make a POST request with postman with the following json;
```json
{
    "title": "Test Survey.",
    "steps": [
        {
            "$type": "SimpleSurveys.Shared.Models.Text",
            "title": "Give me an answer ;)",
            "placeholder": "Some text"
        }
    ]
}
```
I get the following as response:
```json
{
    "$type": "Microsoft.AspNetCore.Mvc.NewtonsoftJson.ValidationProblemDetailsConverter+AnnotatedValidationProblemDetails, Microsoft.AspNetCore.Mvc.NewtonsoftJson",
    "errors": {
        "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.String[], System.Private.CoreLib]], System.Private.CoreLib",
        "steps[0].$type.0": {
            "$type": "System.String[], System.Private.CoreLib",
            "$values": [
                "Type specified in JSON 'SimpleSurveys.Shared.Models.Text' was not resolved. Path 'steps[1].$type', line 13, position 55."
            ]
        }
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-21f7634638a11b46914f15475ae15e18-6c91c4ea882ee444-00"
}
```
The important part is this error message:
> "Type specified in JSON 'SimpleSurveys.Shared.Models.Text' was not resolved. Path 'steps[1].$type', line 13, position 55."

When I try to do the request in my client side blazor app with `HttpClient` using the following code;
```csharp
await Http.PostAsJsonAsync("api", </*survey object holding a single Text object in the Steps collection*/>);
```

I get the following as response error:
> Could not create an instance of type SimpleSurveys.Shared.Models.Step. Type is an interface or abstract class and cannot be instantiated. Path 'Steps[0].Placeholder', line 1, position 300.

---

What am I doing wrong when using `TypeNameHandling`? Is there some issue with `Newtonsoft.Json` and `System.Json` colliding? 

Or maybe I'm taking a whole wrong approach to using abstract types via the JSON API wrong.

### Further technical details
- ASP.NET Core version: 5.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2019
- Include the output of `dotnet --info`:
<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by pranavkm** [comment]
> "$type": "SimpleSurveys.Shared.Models.Text"

Perhaps you're expected to specify a fully qualified type name? Does it produce the same error if you attempt to deserialize using Json.NET directly in your app (without having ASP.NET Core's formatting involved)?

**Comment by speyck** [comment]
Hi @pranavkm, thank you for your reply.

I'm not quite sure what you mean by `fully qualified name`, but I stumbled upon [this StackOverflow post](https://stackoverflow.com/questions/13204720/get-the-fully-qualified-name-of-a-class) and using this I was able to get the following name:
> SimpleSurveys.Shared.Models.Text, SimpleSurveys.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

And wow - now that actually worked! I'm very surprised as I was looking almost 3 hours for a solution for this. 

---

Now using plain JSON I'm able to create an object with the API and get it created on my database. The next problem is using the `HttpClient` in my frontend to send and receive these objects, as the HttpClient does not seem to send any `$type` with it.

As I had to add the `TypeNameHandling` option in my backend when adding the Newtonsoft.Json service I think I also have to do the same on my frontend to have it enabled for the `HttpClient`?

**Comment by rafikiassumani-msft** [comment]
@speyck you can manually serialize your request body using `NewtonsoftJson` to a `PushStreamContent` instance.  See the following doc: https://docs.microsoft.com/en-us/previous-versions/aspnet/hh995285(v=vs.118)

See the following example: https://stackoverflow.com/questions/50059481/json-object-creation-pushstreamcontent/50060365#50060365

**Comment by speyck** [comment]
@rafikiassumani-msft thanks a bunch.

Using the following code, I'm able to do POST requests:
```csharp
JsonSerializerSettings settings = new()
{
    TypeNameHandling = TypeNameHandling.Objects
};

string json = JsonConvert.SerializeObject(<survey>, settings);

StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

HttpResponseMessage result = await Http.PostAsync("api", content);
```

---

The problem now lays in the GET request. I can receive the content just fine, but when I try to deserialize the objects into `Survey`s, it fails. Looking into the json, the given `$type` of the steps looks like this:
> $type: "Castle.Proxies.TextProxy, DynamicProxyGenAssembly2"

What is the cause of this?

**Comment by speyck** [comment]
I was able to fix this. The problem was using lazyloading proxies with the entityframework:
```csharp
services.AddDbContext<SomeContext>(options => options/*.UseLazyLoadingProxies()*/.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

I had to remove `UseLazyLoadingProxies()`.
