### ISSUE TITLE
Attempt to disable Blazor WASM AOT

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#37984]
If WASM AOT is disabled via the property in the project file ...

```xml
<PropertyGroup>
  <RunAOTCompilation>false</RunAOTCompilation>
</PropertyGroup>
```

... and the app is published (`dotnet publish -c Release`), I expected not to see .....

```dotnetcli
Compiling native assets with emcc. This may take a while ...
```

Am I misunderstanding what I see in the console? Is the property actually effective? Put another way, what part of console output indicates the difference between AOT and not-AOT compilation? I'd like to flesh out the coverage at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation

... to inform devs what they'll see to confirm AOT/not-AOT based on console output.

**Comment by SteveSandersonMS** [comment]
If the wasm tools are installed, then the build system will "relink" the `dotnet.wasm` file, which can make it smaller. That's what's happening here and is unrelated to AOT.
