### ISSUE TITLE
Versioning Api endpoints with webapi .net 6 and swagger error

### ISSUE THREAD

**Issue by developer9969** [dotnet/aspnetcore#37993]
### Describe the bug
I am trying to implement API versioning with Swagger and noticed that there is no version 6 of any kind for Versioning. Is this correct?
![image](https://user-images.githubusercontent.com/16970109/139718949-8a579ae8-99f1-4177-ab80-098dc67ffd89.png)

I have created a small repro project  
![image](https://user-images.githubusercontent.com/16970109/139719283-ac0828cd-3856-4b8e-b2fa-1c59401014e0.png)

### To Reproduce

1. Download the repo  https://github.com/developer9969/WebApiNet6VersioningIssue
2. You will see that there are 3 version  V1-V2-V3 
3. Launch the webapi
4. Swagger V1 Definition is fine
5. Select V2 or V3 definitions and you will see an error.
![image](https://user-images.githubusercontent.com/16970109/139719153-7be37c6c-7a1b-414c-a6a4-8c235b3c61e3.png)

Questions

1. Is there a version of .net 6 for the versioning api?
2. Am I missing something or is it bug that definition is not loading.

Many Thanks

```

**Comment by developer9969** [comment]
@pranavkm Hi there  I was hoping in a quick response but I see that you guys are overwhelmed with issues..

Does openapi and multiple versioning is supported in .net 6 ?  Sounds like a regression to me?
How do you do it in .net 6?

@rafikiassumani-msft  a bit confused with .net 7 planning on this one. Does it mean that you cannot have multiple versioning with open api in .net 6?

Thank you in advance for any suggestions

**Comment by medicodepublic** [comment]
@developer9969 the package is not compatible with .net 6 yet - i am just trying to find a solution myself. as you can see in package manager supported frameworks:

- .NETCoreApp 3.1 
- .NETCoreApp 5.0

maybe you could extend it to work with .net 6.

**Comment by developer9969** [comment]
@medicodepublic I have looked into it and I couldn't . If you do find a workaround can you share?
This thread is just dead so I guess we are on our own on this one.
It's a  bit shocking that  they didnt think about openapi

**Comment by ByteDecoder** [comment]
> @developer9969 the package is not compatible with .net 6 yet - i am just trying to find a solution myself. as you can see in package manager supported frameworks:
> 
> * .NETCoreApp 3.1
> * .NETCoreApp 5.0
> 
> maybe you could extend it to work with .net 6.

Any news on this?

**Comment by developer9969** [comment]
@ByteDecoder I dont have a solution and I am stuck

**Comment by Jens-H-Eriksen** [comment]
I'm having the exact same problem. Any solution would be appreciated

**Comment by developer9969** [comment]
This has now been sorted been a swagger issue that prevented the endpoint to work correctly when swapping them in swagger works fine with postman
