### ISSUE TITLE
dotnet.js whereabouts

### ISSUE THREAD

**Issue by Elringus** [dotnet/aspnetcore#37999]
Can someone please let know where `dotnet.x.x.xx.js` file bundled with Blazor distro (along with` blazor.boot.json`, `blazor.webassembly.js`, etc)  comes from and where we can find the sources for that file? I've tried searching this repository but wasn't able to find the sources, only mentions of that file in the build configs.

**Comment by pranavkm** [comment]
* dotnet.js comes from https://github.com/dotnet/runtime/tree/release/6.0/src/mono/wasm/runtime
* blazor.webassembly.js comes from https://github.com/dotnet/aspnetcore/tree/release/6.0/src/Components/Web.JS

The boot.json file is generated based when building a Blazor WebAssembly project.

**Comment by Elringus** [comment]
Thank you!
