### ISSUE TITLE
[Feature Request] Better support Dependency Inversion with SignalR Core

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/aspnetcore#38007]
### Is your feature request related to a problem? Please describe.

SignalR Core Hub, and IHubContext do not support patterns that rely on dependency inversion. One cannot define interfaces for these and inject those into different application layers where the concrete Hub is not referenceable.

`IHubContext<THub>` requires that `THub` is `Hub`. Which almost entirely negates the ability to define an interface for your Hub, and inject that.

### Describe the solution you'd like

Interface support for `Hub` and `IHubContext` such that we can define & register our own `IAppHub : IHub`, use it as `AppHub : Hub, IAppHub`, and inject it into a service as `IHubContext<IAppHub>`.

### Additional context

This is pretty straight forward, even if the solution is not. Asp.Net Core and the MS docs have been pushing for better architected codebases, but Signalr Core does a very poor job of fitting into that

**Comment by BrennanConroy** [comment]
It looks like you want `Hub<T>` and `IHubContext<THub, T>`.

See https://docs.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-5.0#strongly-typed-hubs and https://docs.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-5.0#strongly-typed-hubs

**Comment by douglasg14b** [comment]
Nope, that is not what I want. 

What I want is as the title says, `Dependency Inversion` support, and my described solution should clearly show the objective:

> Interface support for `Hub` and `IHubContext` such that we can define & register our own `IAppHub : IHub`, use it as `AppHub : Hub, IAppHub`, and inject it into a service as `IHubContext<IAppHub>`.

Just like you can define how the dependency injection will resolve your service,  `IServiceCollection.AddScoped<IMyService, MyService>()`, SignalR Core should support defining the resolution of the `Hub`. A potential example might be `endpoints.MapHub<IAppHub, AppHub>("/hubs/app");`

**Comment by BrennanConroy** [comment]
`IHubContext<IAppHub>` doesn't make sense with regards to `AppHub : Hub, IAppHub`.
`IAppHub` in this case is defining the shape of your hub which is the contract for your clients to call into. It is not usable from anywhere else in your app.

`IHubContext<T>` is how you call client methods from outside of the hub (and comes from DI). `T` is defining what your client looks like. I think you're mixing the two concepts.

`IHubContext<T>` is server to client.
`Hub : T` is client to server.

**Comment by douglasg14b** [comment]
> IHubContext<T> is how you call client methods from outside of the hub (and comes from DI). T is defining what your client looks like. I think you're mixing the two concepts.

<hr>

Please refer to my original note:

> **`IHubContext<THub>` requires that `THub` is `Hub`. Which almost entirely negates the ability to define an interface for your Hub, and inject that.**

This has nothing to do with the actual direction of requests, or requests in general, this is an architectural concern. Since an IHubContext<THub> requires that you provide your `Hub` instance as a generic argument, it is impossible to [invert the dependency ](https://en.wikipedia.org/wiki/Dependency_inversion_principle) of your `Hub`.

I have added additional context to the comment above at the same time you posted your comment, please re-parse it.

**Comment by davidfowl** [comment]
I re-read it but I'm not sure what you're trying to achieve. Can you accompany the explanation with a sample and the "why" behind it?

**Comment by douglasg14b** [comment]
Sure!

While I try and setup some form of example, the following images from the [docs ](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles#dependency-inversion)should get readers started on the problem space:

![image](https://user-images.githubusercontent.com/1400380/139777048-0ca37cd2-2a85-40f9-a744-1039b5914066.png)


![image](https://user-images.githubusercontent.com/1400380/139777039-1b3ee7c3-3d40-485c-a429-22d7f07c831a.png)

**Comment by davidfowl** [comment]
It's unclear how this applies to signalr and IHubConext

**Comment by douglasg14b** [comment]
Prerequisite to this example: https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures
<hr>

**This is overly simplified, please don't get overly caught up in trying to make the example fully robust.** 

I'm not entirely sure how else to explain this, the concept is fairly straight forward. You have multiple projects, you are to avoid circular dependencies. Your `Hub` exists in a project that references other projects. Those other projects cannot reference the project your `Hub` is in. Those other projects need to call functions on clients, so they need an `IHubContext`, they cannot get an `IHubContext` because the `IHubContext` requires a reference to the `Hub` implementation

A clear circular reference for a common architecture.

<hr>

![image](https://user-images.githubusercontent.com/1400380/139781049-3f2da288-ecb4-4b12-a4d8-caa63fa0e502.png)

![image](https://user-images.githubusercontent.com/1400380/139781090-0c5c9363-a3f0-49a7-8db3-5b675173af42.png)


```cs
// In Project.Web assembly
public class AppHub : Hub
{
    private readonly MyAppService _service;

    public AppHub(MyAppService service) 
    {
        service = _service
    }

    public async Task<string> DoSomething(string someStuff)
    {
        await _service.DoTheThing(someStuff)

        return "Thing was done";
    }
}

// In Project.Features assembly  
public class MyOtherAppService 
{
    private readonly IHubContext<AppHub> hubContext _hubContext;
    public MyOtherAppService(IHubContext<AppHub> hubContext) // <-- We cannot do this since we cannot reference AppHub from this project.
    {
        _hubContext = hubContext
    }

    public async Task RespondToSomething(object someEventData) 
    {
        await _hub.Clients.All.SendAsync("SomethingWasUpdated", someEventData);
    }

    public async Task TakeSomeAction(object someArgument) 
    {
        var someResult = DoSomething(someInputs);

        await _hub.Clients.All.SendAsync("SomethingWasDone", someResult);
    }
}
```

**Comment by davidfowl** [comment]
This is much clearer. Just that code sample alone makes it crystal clear. Yes today you need to reference the hub directly to make this work. Today we actually use that type as a discriminator for resolving other services related to said hub. 

Like anything in computer science, you can solve this with another layer of indirection. Treat the IHubContext as an implementation detail. Make an INotifier interface and make a signalr implementation that is backed by the IHubContext and exists in the project that know about the hub.

This scenario is interesting but I'm not seeing an easy change we can make to fix this at the moment.

**Comment by BrennanConroy** [comment]
Thanks for the explanation.

We have another related issue today where if you define two hub endpoints using the same hub `MapHub<Chat>("/1");` and `MapHub<Chat>("/2");` you can't specify which hub the `IHubContext<Chat>` will refer to.

David's comment provides a workaround that will make your example work.

One potential solution for both these problems could be to implement a `IHubContextFactory` type that behaves similarly to [`IHttpClientFactory`](https://docs.microsoft.com/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0). When a hub endpoint is created we use the route as the "name" and then when someone wants a specific `IHubContext` they use that name with the `IHubContextFactory` and get an instance of `IHubContext` that points to the correct hub.

**Comment by adityamandaleeka** [comment]
Closing this issue since there's a workaround above. Please reopen if the workaround isn't sufficient.
