### ISSUE TITLE
Assembly that ends in 'dotnet' fails ANCM in Azure

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/aspnetcore#38004]
Chatted with @shirhatti about an issue that I was seeing in Windows App Service when deploying an app that had a namespace ending in 'dotnet' and issue was resolved by updating the name to not end in 'dotnet'

See https://github.com/dotnet/aspnetcore/pull/18311

**Comment by Tratcher** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/35998

**Comment by adityamandaleeka** [comment]
This has been fixed in ANCM but the fix hasn't yet been ingested into the Azure App Service infrastructure. We'll update this issue when we can share timelines.

**Comment by adityamandaleeka** [comment]
This should be fixed.
