### ISSUE TITLE
File Upload with <InputFile> creates corrupted file in ASP.NET Core 6.0.0-rc.2.21480.5

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/aspnetcore#38019]
### Describe the bug
This code for uploading one or more files with a progress bar **worked well in .NET 5.0.x**
However, it creates corrupted files in the file system in .NET 6.0 RC1 und RC2. 

![2021-11-02_14-06-41](https://user-images.githubusercontent.com/3673169/139852638-f25a186a-0c16-43ce-a49f-dcf6e75368d3.jpg)

### To Reproduce

```
 foreach (IBrowserFile f in filesToUpload)
  {
   string newFilePath = Path.Combine(env.WebRootPath, f.Name);

   if (File.Exists(newFilePath)) File.Delete(newFilePath);

   using var newFile = File.OpenWrite(newFilePath);
   using var newFileStream = f.OpenReadStream(MAXFILESIZE);
   var buffer = new byte[10 * 1096];
   int bytesRead;
   double totalRead = 0;
   progressPercent = 0;

   while ((bytesRead = await newFileStream.ReadAsync(buffer)) != 0)
   {
    totalRead += bytesRead;
    await newFile.WriteAsync(buffer);

    progressPercent = (int)((totalRead / f.Size) * 100);

    StateHasChanged();
   }
   newFileStream.Close();
   newFile.Close();
  }
```

Complete Repo:
[Uploading BlazorServerUploadDemo.zip…]()

### Exceptions (if any)
Created files in the file system are too small and unusable

### Further technical details
- ASP.NET Core version:.NET 6.0.0-rc.2.21480.5
- Windows
- Kestrel

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't open `zip` files as a repro. Can you please share your repro project as a publicly hosted GitHub repo.
Please note, that you also have a bug in your code where you write data to your file (from the code snippet that you've shared). When writing to the `newFile` stream you want to write exactly the number of bytes you've just read. Based on this asking this question in [StackOverflow](https://stackoverflow.com) may be a faster way to get a response on your issue.

**Comment by TanayParikh** [comment]
Hi @HSchwichtenberg, may I also recommend checking out the `InputFile` upload documentation available at https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server.

**Comment by TanayParikh** [comment]
> When writing the file (`await newFile.WriteAsync(buffer)`), you need to use `bytesRead` to not write more data than what was read
> 
> ```
> await newFile.WriteAsync(buffer.AsMemory().Slice(0, bytesRead));
> ```

I don't believe `AsMemory` / `Slice` should be required. You should be able to use the `WriteAsync` overload which accepts the `offset` and `count`.

```csharp
public System.Threading.Tasks.Task WriteAsync (byte[] buffer, int offset, int count);
```

https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.writeasync?view=net-5.0#System_IO_Stream_WriteAsync_System_Byte___System_Int32_System_Int32_

**Comment by HSchwichtenberg** [comment]
> Please note, that you also have a bug in your code where you write data to your file (from the code snippet that you've shared). 

Thank you very much for your quick reply and that useful hint. I could fix the problem with
`    await newFile.WriteAsync(buffer, 0, bytesRead);`
  And
`    await newFile.WriteAsync(buffer.AsMemory().Slice(0, bytesRead));`
works as well.

I wonder, why this was not a problem in .NET 5.0. The app was working finde in .NET 5.0. What has changed in .NET 6.0 that this became a problem?

**Comment by HSchwichtenberg** [comment]
> Hi @HSchwichtenberg, may I also recommend checking out the `InputFile` upload documentation available at https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server.

Thanks, but the documentation (I read before) was not helpful for my case because it does not cover a showing the progress.

**Comment by TanayParikh** [comment]
> Thanks, but the documentation (I read before) was not helpful for my case because it does not cover showing the upload progress.

Thanks for pointing that out, we'll be adding in documentation that covers upload progress via https://github.com/dotnet/AspNetCore.Docs/issues/23717. 🎉
