### ISSUE TITLE
Blazor DI Service required

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#38023]
This is more a question than a bug. I have multiple Blazor components and each of them requires different services from DI. Is there any way to enforce these injectable services to be required? In other words, do not allow for null. Otherwise, I will have to add null check logic for each service in each component.

**Comment by javiercn** [comment]
@ylr-research thanks for contacting us.

We don't have anything for this, you'll have to add a null check for it.

**Comment by ylr-research** [comment]
Thanks
