### ISSUE TITLE
Reconsider EditorForAsync/DisplayForAsync for ASP.NET 7

### ISSUE THREAD

**Issue by eajhnsn1** [dotnet/aspnetcore#38043]
This is response response to the ASP.NET 7 Call to Action, issue #37373.

HtmlHelper.EditorFor and HtmlHelper.DisplayFor do not have async counterparts and, as a result, awaiting in a Template has been known to cause deadlocks.  See related, closed issue #4880.  #7083 relates to Html.Partial.

It's concerning that this feature of Razor engine is quietly prone to deadlocks, particularly with no warning that I've seen in documentation.  I wish these APIs would be reconsidered for a major .NET release.

If these APIs are not introduced, guidance and documentation as to the recommended way to get EditorFor functionality without using EditorFor would be greatly appreciated.

**Comment by pranavkm** [comment]
@eajhnsn1 in the ordinary cases, the view engine serves views compiled at build and the entire operation is synchronous. Blocking calls can happen if you have runtime compilation enabled in published apps which we believe is less common.

**Comment by eajhnsn1** [comment]
Pardon my ignorance in this area.  I was under the impression this is in the Render call chain, not related to compilation.  Specifically:  https://github.com/dotnet/aspnetcore/blob/15e717adb849a7744e9c1970131a276268c5276d/src/Mvc/Mvc.ViewFeatures/src/TemplateRenderer.cs#L136 

Perhaps I'm missing something here (I hope this is the case!)

**Comment by pranavkm** [comment]
Thanks for pointing that out, you are absolutely right. Making the ViewEngine async was primarily about making the view engine calls here async - https://github.com/dotnet/aspnetcore/blob/15e717adb849a7744e9c1970131a276268c5276d/src/Mvc/Mvc.ViewFeatures/src/TemplateRenderer.cs#L124-L129. But blocking the view rendering is problematic since it does have async code in there.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @eajhnsn1.
We'll cover this as part of #3956
