### ISSUE TITLE
Change visibility of IRemoteAuthenticationPathsProvider in Blazor WebAssembly to implement custom OAuth2

### ISSUE THREAD

**Issue by ErikApption** [dotnet/aspnetcore#38048]
## Background and Motivation

I'm trying to implement a custom OAuth2 provider for Discord. oidc-connect is only compatible with few major OIDC providers, the current flow requires a metadata address which is not available with Discord and many other OAuth2 providers. Looking at the current API model and source code for OAuth2/OIDC, it is not possible to bypass the metadata call on https://<provider>/.well-known/oidc-configuration 
The only way I've seen from the source code is to implement a new provider:
1) Enable AuthorizationCore
2) Implement AuthenticationStateProvider
3) Implement SignOutSessionStateManager
4) Implement IRemoteAuthenticationService
but this breaks because the next service required is IRemoteAuthenticationPathsProvider which cannot be configured in the services because of its visibility.

**Comment by javiercn** [comment]
@ErikApption Thanks for contacting us.

The approach here is to create your own AuthenticationService.js like MSAL does. https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/Authentication.Msal/src/MsalWebAssemblyServiceCollectionExtensions.cs#L53-L61

**Comment by brockallen** [comment]
There's already one implemented for Discord here: 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Discord

**Comment by javiercn** [comment]
@brockallen I believe this is asking for a Blazor Webassembly specific implementation, what you are suggesting is for ASP.NET Core and doesn't work for Blazor.

**Comment by brockallen** [comment]
Ah, they want one running in the client-side WASM code?

**Comment by javiercn** [comment]
Yep, all the mentioned types are Blazor Webassembly types.
