### ISSUE TITLE
Blazor Server Page Refresh/Scroll ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#38057]
I am using Blazor Server Project with .NET RC2.

I am noticing a Page Reset or Scroll.

In the screen recording attached i am on a page where i manually scrolled to bottom and then i am clicking the button.

On button click, page Scrolls up and then scrolls down.

Is this expected behavior in Blazor Server or am i missing some settings ?

https://1drv.ms/v/s!AtHk7h6Srnk_h9loTZ_Z3H98TUstYw?e=hiHS2i

**Comment by TanayParikh** [comment]
Hello @nssidhu, thanks for contacting us. This is definitely not expected behavior, and looks to be a configuration issue. 

To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the blazor tag.

**Comment by TanayParikh** [comment]
Thanks for the follow-up! 😄
