### ISSUE TITLE
Feature request: Allow `DataProtection` API to protect some data using a specific key

### ISSUE THREAD

**Issue by ionmincu** [dotnet/aspnetcore#38055]
### Is your feature request related to a problem? Please describe.
**Simplified version:** I want to use `DataProtection` to encrypt a user's **PII data**. When the user wants his data deleted, we could just remove the key used to encrypt his data, so he is certain his data is now safe.

**Realistic version**: Rather than deleting the key itself the user will delete his `Key_Encryption_key`. I would like some variant of 
`.ProtectKeysWithAzureKeyVault(new Uri("<users_personal_key>"), new DefaultAzureCredential());` where each user brings his own KeyVault. A custom implementation of `IXmlEncryptor` can easily be done right now, but that is not the problem.

The problem is I can not specify a an encryption key in the `Protect` method.

### Describe the solution you'd like
Allow `DataProtection` API to protect some data using a specific key.
```csharp
        byte[] Protect(Guid keyId, byte[] plaintext);
```
As an alternative allow `DataProtection` API to protect some data using a subset of keys with ownerId. This will allow key rotation and expiration, so a user can have multiple keys (that expire and new ones get created at some interval)
```csharp
        // one of these:
        byte[] Protect<T>(T ownerId, byte[] plaintext);
        byte[] Protect(Guid ownerId, byte[] plaintext);
```

**Alternatives I've tried:**
I tried creating an instance of a `DataProtectionProvider` per user (with it's own `ServiceCollection`) but it seems to be a bit heavy on memory. Using a simple program I've noticed that 1000 instances will consume about 15MB.
```csharp
    var protectors = Enumerable.Range(0, 1000)
        .Select(s => DataProtectionProvider.Create($"MyApp {s}"))
        .ToList();

    GC.Collect(3);
```

### Additional context
In the above description I mentioned users all the time, but the api should allow usage of this to extend this to organization level, not necessary a particular user.

**Comment by blowdart** [comment]
That's not what data protection is designed for. It's designed to be a "You don't have to think about keys, algorithms or anything" type system. As soon as you start being able to specify your own keys it moves away from the entire ethos behind it.

So no, this isn't a feature we'd develop I'm afraid.

**Comment by ionmincu** [comment]
@blowdart do you have any recommendations on how to solve the problem mentioned in the description (allow users to delete their data encryption key).
Any insights would be helpful, what I'm currently considering:
- custom implementations for DataProtection interfaces
- other library besides DataProtection (not sure which)
- custom implementation all the way (but don't really want to mess around with this stuff)

**Comment by blowdart** [comment]
Anything I recommend is going to end up being custom I'm afraid, and ventures into personal opinion rather than Msft guidance. With that in mind ...

If you're going the customer brought keyvault route that's interesting (although I'm not sure how cross tenant access would work) - keyvault provides a wrapping function for keys you hold locally, it's what we use in data protection. So you'd generate a key per customer, wrap that so it can only be decrypted while you have access to their keyvault, and then just go ahead and use [AesGsm](https://stackoverflow.com/questions/60889345/using-the-aesgcm-class) which gives you resilience against tampering built into the algorithm.

**Comment by ionmincu** [comment]
Thanks!
