### ISSUE TITLE
'dotnet watch run' for a console app keeps restarting after one modification

### ISSUE THREAD

**Issue by jhgbrt** [dotnet/aspnetcore#38064]
### Describe the bug
'dotnet watch run' for default console app at first just runs the app once and waits for a change. After one change however, it gets stuck in an endless loop: the app keeps getting restarted, instead of waiting for another change.

### To Reproduce
```
dotnet new console -o ConsoleApp1
cd ConsoleApp1
dotnet watch run
```
Until now, behaviour is as expected.

Now edit & save Program.cs in any editor: `dotnet watch` keeps restarting the console app in an endless loop, instead of only when something changes. 

### Exceptions (if any)
(none)

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jhgbrt** [comment]
Adding - -no-hot-reload fixes this issue.

**Comment by calvynsiong** [comment]
This defeats the purpose. Why does hot reload not work as intended, and keeps restarting the watch command. I am having this issue as well

**Comment by cphillips83** [comment]
Came here to say that this is indeed a bug and the workaround is to add `--no-hot-reload`.

@calvynsiong Correct me if I'm wrong, hot reload and this feature aren't related. Hot reload is about swapping out running code with no code where as `dotnet watch run` is about starting a file watcher and triggering a `dotnet run` every time a file is changed which causes a stop, build, execute loop.

**Comment by jhgbrt** [comment]
I agree, with my comment I just wanted to point out that the faulty behavior may be related to hot reload, or at least that as a workaround one can disable hot reload. For simple batch-style console apps, hot reload isn't that useful anyway. I'm also wondering why hot reload it was built into dotnet watch.

**Comment by kopkako** [comment]
What's going on with this? Literally the first time I'm trying out the much praised hot reload and I immediately run into this bug as well, it's a complete showstopper and renders the hot reload unusable.

Any update on this?

**Comment by tmat** [comment]
Works as intended with SDK 7.0.103:

```
D:\Temp\repro2>dotnet watch run
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  repro2 -> D:\Temp\repro2\bin\Debug\net7.0\repro2.dll
dotnet watch 🚀 Started
Hello, World!
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
dotnet watch 🔧 Building...
  repro2 -> D:\Temp\repro2\bin\Debug\net7.0\repro2.dll
dotnet watch 🚀 Started
First change
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
dotnet watch 🔧 Building...
  repro2 -> D:\Temp\repro2\bin\Debug\net7.0\repro2.dll
dotnet watch 🚀 Started
Second change
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```
