### ISSUE TITLE
VS2022 RC3 Blazor compilation errors showing only in generated .razor.g.cs files and not in my code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38069]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-RC3-Blazor-compilation-errors-sho/1564354)._

---
I have a solution and I've been doing some refactoring moving pages and files around. Due to that, the namespaces and include files for out of whack, but the errors from the build and in the Error List don't point to the errors in my files, only to the errors in the generated files from Blazor.

If by checking the error I find the razor file and I open it, then the Error list shows the error in the right location.
When I close the .razor file, the correct error goes away and it only shows the error in the generated file.

You can see attached recording
[BlazorErrorsInGeneratedFiles.gif] (https://aka.ms/dc/file?name=B895f2aae386147d783be2564e91b6f52637708949807453058_BlazorErrorsInGeneratedFiles.gif&tid=895f2aae386147d783be2564e91b6f52637708949807453058)

Issues: 
- build shows errors in generated files instead of mine
- Error list shows errors in generated files instead of mine
- Right errors only show in error list if I open the file.
- When I close the razor file, the right errors go away, and only the ones in the generated file remain

What I expect:
Generated files are completely hidden away and I never ever see them
Errors only show in my code (for the build and also the error list)
When I build in the server for continuous integration I won't want to see the errors in the generated code, only my code.

---
#### Feedback Bot on 10/26/2021, 08:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The fix for https://github.com/dotnet/aspnetcore/issues/38070 is going to address also this issue, so closing this as a dupe.
