### ISSUE TITLE
VS2022 RC2 Building Blazor error reporting not working well

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38072]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-RC2-Building-Blazor-error-reporti/1563404)._

---
[severity:It's more difficult to complete my work]
It seems that there is a number of issues with the building and reporting errors in Blazor projects:

- Builds don't show all the errors inside the razor files
- Errors are shown in generated files and not in the razor file that contains the error
- Clicking on the error in the Error list doesn't take you to the error

I have recorded the problem showing all those issues. See attachment.

This is a common example during a refactoring when moving files around and it make the process very difficult as we can't find the source of the errors and we need to investigate in multiple ways instead of being able to see all the errors and click on them to go directly to the problem to find a solution.

---
#### Feedback Bot on 10/26/2021, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 11/3/2021, 00:57 PM: 

<p>Thanks for contacting us. We’ve made multiple improvements in this area during .NET 6 release. Can you please confirm whether you see similar issues with .NET 6 apps or not? Thanks!</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please try out the .NET 6 release, where we've made a lot of improvements and see whether the issues are resolved? Thanks!
