### ISSUE TITLE
Parameterize Blazor virtualization ItemProvider

### ISSUE THREAD

**Issue by Cage-e** [dotnet/aspnetcore#38085]
### Is your feature request related to a problem? Please describe.
Let's say for example I want to filter the type of cars I want to load in virtualize ItemProvider. Would be nice to pass in the type as a parameter that can be used in the API call. 
Or for example if I have multiple virtualize in a component (e.g. in a loop) that all use one ItemProvider method. there is no way to know which virtualize is calling the provider method. 

### Describe the solution you'd like
if it would be possible to for example:

```
 @foreach(var brand in carBrands)
  {
      <Virtualize Context="car" ItemsProvider="@VirtualizeCars(brand.Name)" >...</Virtualize>
  }
```

**Comment by oiBio** [comment]
you could just 

```
@foreach(var brand in carBrands)
  {
      <Virtualize Context="car" ItemsProvider="@(async (e) => await VirtualizeCars(e,brand.Name))" >...</Virtualize>
  }
```

**Comment by Cage-e** [comment]
Thanks for the suggestion, I didn't think of passing e like this. Awesome!
