### ISSUE TITLE
Blazor Add Analyzer if JSInvokable Method isn't Public

### ISSUE THREAD

**Issue by Webreaper** [dotnet/aspnetcore#38080]
I noticed last night that if I declare a `[JSInvokable]` method as protected, the Javascript fails with an error in the console.

<img width="528" alt="Screenshot 2021-11-04 at 11 01 01" src="https://user-images.githubusercontent.com/4901102/140303072-6712790c-81ee-4390-adcb-450e5fb8ccd9.png">

<img width="813" alt="Screenshot 2021-11-04 at 11 00 24" src="https://user-images.githubusercontent.com/4901102/140303084-1669ec6d-cd61-45d6-ad09-8cf8e369a413.png">

It feels like there be a code analyzer that makes protected/private `JSInvokable` methods a warning/error?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
