### ISSUE TITLE
Dynamically managed authentication / authorization

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#38099]
---
**Issue moved from microsoft/reverse-proxy#582**
- Please respond to @macsux.

---

_From @macsux on Friday, November 27, 2020 9:02:51 PM_

It would be good to come up with an approach that allows for dynamic authentication scheme and authorization policies that does not require rebuilding the app. 

The current approach in YARP to security taps into standard ASP.NET core authorization middleware, which in turn taps authentication middleware. The issue with both of these is that they are built in-a-way that authentication schemes and authorization policies are not meant to be altered easily at runtime. The authentication schemes have a named options instance in DI container and a handler where it gets injected. In practice, authentication schemes are tied to a specific set of credentials (such as clientid/secret in OAuth2, or AD account if using Kerberos). While I can change the values on existing scheme, I can't introduce a new one dynamically with different set of creds. Authorization policies are tied to specific schemes which are triggered when authorization action is demanded. As DI container does not allow to be altered after construction, these policies are somewhat static for the lifetime of the app. This means that if I want to introduce a new app credential (clientid/secret, token endpoint) via config and say that a specific route should use this, I don't see how that's easily accomplishable using the current approach.

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#582**
- Please respond to @davidfowl.

---

_From @davidfowl on Tuesday, December 1, 2020 2:32:20 AM_

Can you give some examples of what you would like to add dynamically?

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#582**
- Please respond to @macsux.

---

_From @macsux on Tuesday, December 1, 2020 7:42:03 PM_

Sure. Some background first. I'm trying to plug an existing proxy project that we've been using with clients mainly for solving Kerberos authentication in older apps by offloading them into a reverse proxy, which is then run as full-fledged reverse proxy backing multiple apps, or a sidecar. I'm looking at what it would take to port this on top of YARP. 

Each route is associated with a given identity (authentication scheme) and authorization policy (such as "RequireAuthenticated", or "HasRole"). The configuration looks kinda like this:

```
    "Credentials": {
      "App1Identity": {
        "Type": "Kerberos",
        "UserAccount": "iwasvc@almirex.dc",
        "Password": "XXXX"
      }
    },
    "Ingress": [
      {
        "ListenPort": 5555,
        "TargetUrl": "http://localhost:5000",
        "Credentials": "App1Identity",
        "Routes": [
          {
            "Path": "/actuator/**",
            "Order": 10
          },
          {
            "Path": "/**",
            "PolicyName": "RequireAuthenticatedUser",
            "Order": 20
          }
        ]
      }
    ],
```
To keep things simple, each credential is registered as an authentication scheme at startup. I don't tie authorization policies directly to schemes so I can use the same policy names with multiple creds. Instead, a piece of middleware associates them with a given authentication scheme during execution time:
```
                var policy = await _policyProvider.GetPolicyAsync(matchingRoute.PolicyName);
                policy = new AuthorizationPolicy(policy.Requirements, new []{ authenticationScheme });
```
This allows me to easily reuse identities across multiple routes and apply different reusable authorization policies.
This is actually what prompted the creation of this issue https://github.com/dotnet/runtime/issues/45294 (which you already commented on).

@davidfowl  A few extra notes that might be of interest for you.

The proxy we've built supports egress scenarios too. The goal is to enrich outgoing requests from primary app by obtaining and attaching HTTP headers to them. This works very well for Kerberos scenarios, but can totally be extended for OAuth2. This removes the need to manage authentication inside the app itself. This mode is primarily used as a sidecar, so that when the app makes a call to another service, it calls a sidecar on a preconfigured port which is statically (configuration) mapped to a given Kerberos identity and a destination. 
```
    "Egress": [
      {
        "ListenPort": 3333,
        "TargetUrl": "http://localhost:5555",
        "Credentials": "App1Identity",
        "Spn": "host/iwasvc.apps.pcfone.io"
      }
```
It appends the necessary SPNEGO header and forwards the request - as far as the calling app is concerned it made the request with no auth. The port is essentially used as a "match" for the route (`HttpContext.Connection.LocalPort`) since the host header would end up being `localhost` by the calling app instead of where it actually wants to send the request. The use of port-based matching can be avoided if the calling app uses a sidecar as an actual HTTP proxy (even though it's considered a reverse proxy, it works just fine as a forward proxy), but that is often a cumbersome code change that clients are often happy to avoid. Unfortunately, I have not discovered a way to reconfigure Kestrel at runtime to expose new ports.

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#582**
- Please respond to @karelz.

---

_From @karelz on Thursday, December 17, 2020 6:13:37 PM_

Triage: This requires general authentication/authorization config extensibility.

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#582**
- Please respond to @Tratcher.

---

_From @Tratcher on Thursday, December 17, 2020 6:44:50 PM_

@macsux making AuthN/AuthZ more dynamic isn't a YARP specific scenario, this is a general AspNetCore ask and should probably be moved there.

**Comment by blowdart** [comment]
You should look at [implementing your own policy provider](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-6.0), this would free you from the DI based policy default implementation, and then you can manage the creation and deletion of policies in your own code.
