### ISSUE TITLE
More integration for Blazor Server and SignalR

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#38109]
@DamianEdwards:

> Today in the typical case one ends up with multiple connections from the client to the server: one for the Blazor circuit, the other for the app’s SignalR hubs

I expect the key scenario here would be scaling out notifications across multiple servers via SignalR's backplane support (because otherwise, Blazor Server already inherently has notification/update support within a single server).

**Comment by TanayParikh** [comment]
Added to consolidated https://github.com/dotnet/aspnetcore/issues/38127. fyi/ @javiercn

**Comment by DamianEdwards** [comment]
@SteveSandersonMS it's also about the programming model. SignalR's Hub primitives include one-to-one and one-to-many RPC from server to client, including support for arbitrary grouping of clients, and yes these concepts then scale seamlessly to scaled-out deployments. Building a multi-user chat app in "pure" Blazor Server today is totally possible, but would require the app to manage some of the aspects inherent in such a scenario manually (e.g. there's no concept of invoking a method on multiple circuits).

Adding @bradygaster and @davidfowl for their thoughts.

**Comment by mkArtakMSFT** [comment]
We haven't seen real-life scenarios where this is actually necessary. So closing for now.
