### ISSUE TITLE
[Question] How does ProducesResponseType inference work for ActionResult<T>?

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#38108]
[Docs say](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-5.0#actionresultt-type):

> - The `[ProducesResponseType]` attribute's `Type` property can be excluded. For example, `[ProducesResponseType(200, Type = typeof(Product))]` is simplified to `[ProducesResponseType(200)]`. The action's expected return type is instead inferred from the `T` in `ActionResult<T>`.

**Does produced type inference work exclusively for `ActionResult<T>` or is there any convention, so I can create my own result type, and OpenApi doc generator will be able to infer the produced type?**

I want to write:
```CSharp
Task<ApiResult<T>> Action() {} 
```
but the actual shape of the output is the following record:
```CSharp
public sealed Result<T>(bool isSuccess, T? result, string[] errors);
```

and I want swagger to show the correct shape of the result without the need to explicitly write the type.

**Comment by voroninp** [comment]
Can we reopen it? I got no response so far.

**Comment by davidfowl** [comment]
The [default API description provider](https://github.com/dotnet/aspnetcore/blob/c2bcc3ff65034045bdaabe75c6a9edefb6ddacb9/src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs) [understands the ActionResult<T> convention](https://github.com/dotnet/aspnetcore/blob/c2bcc3ff65034045bdaabe75c6a9edefb6ddacb9/src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs#L296-L298). You can add providers like this to add your own conventions as well.

**Comment by voroninp** [comment]
@davidfowl Awesome, thanks.

**Comment by voroninp** [comment]
@davidfowl Can I also change the shape of [returned BadRequest](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0#default-badrequest-response) when validation fails in case of applied `[ApiController]` ?

**Comment by voroninp** [comment]
The idea is that for statically typed clients (Blazor + Refit) it's very convenient to always have same response shape irrespective of status code.
