### ISSUE TITLE
VS Code Tooling Issue

### ISSUE THREAD

**Issue by chhinsras** [dotnet/aspnetcore#38103]
This is the code `options.SwaggerEndpoint("/swagger/v1/swagger.json", typeof(Program).Assembly.GetName().Name);`

When I try to run on Visual Studio. It works fine. But when I try to run on Visual Code on Mac.

`/Users/chhinsras/Desktop/Coding.nosync/SchoolManager/Server/Core/Extensions/ApplicationBuilderExtensions.cs(31,76): error CS0246: The type or namespace name 'Program' could not be found (are you missing a using directive or an assembly reference?) [/Users/chhinsras/Desktop/Coding.nosync/SchoolManager/Server/Server.csproj]`

**Comment by davidfowl** [comment]
Visual Studio for Mac doesn't support C# 10 as yet.

**Comment by chhinsras** [comment]
@davidfowl VS Code for Mac ? I havn't  tried Visual Studio for Mac.

**Comment by chhinsras** [comment]
@davidfowl VS Code for Mac ? I havn't  tried Visual Studio for Mac.

**Comment by davidfowl** [comment]
Oh that works if you upgrade omnisharp and am have upgraded to .net 6 rc2

**Comment by chhinsras** [comment]
@davidfowl right. the error has gone. however, i run dotnet watch run --project Server. it works and i see the port. but when i try opening the url (https:localhost:5001). it shows nothing

**Comment by chhinsras** [comment]
@davidfowl oh right. its running Server only, how can i run both with the same port? this is hosted asp.net core blazor. Weird!

**Comment by captainsafia** [comment]
> @davidfowl oh right. its running Server only, how can i run both with the same port? this is hosted asp.net core blazor. Weird!

Can you clarify what you are trying to achieve? When you're running a hosted Blazor app, you only want to run the server-side which will run your API server and host your Blazor client as well. You don't need to run the Client and Server using separate commands.

**Comment by chhinsras** [comment]
> > @davidfowl oh right. its running Server only, how can i run both with the same port? this is hosted asp.net core blazor. Weird!
> 
> Can you clarify what you are trying to achieve? When you're running a hosted Blazor app, you only want to run the server-side which will run your API server and host your Blazor client as well. You don't need to run the Client and Server using separate commands.

the problem is when i try to run blazor wasm hosted, running server project. the hot reload is only watching the change inside server project, not the blazor client project.

**Comment by captainsafia** [comment]
Hot reload for hosted apps is supported although it requires certain launch parameters. You can verify that you are not running into a variant of https://github.com/dotnet/aspnetcore/issues/35393 and confirm that `launchBrowser` is enabled in your `launchSettings`.

**Comment by chhinsras** [comment]
@captainsafia i am still facing same issue with hot reload not working

**Comment by captainsafia** [comment]
@chhinsras Can you file a new issue specifically about your Blazor WASM + hot reload problem?
