### ISSUE TITLE
HubMethodNameAttribute not used from interface in strongly typed hubs

### ISSUE THREAD

**Issue by angelaki** [dotnet/aspnetcore#38100]
Guess no more words needed 🙂 I'd like to define my hub methods in the interface, e.g.

```
public interface IClient
{
    [HubMethodName("Method")]
    Task MethodAsync();
}

public class ClientHub : Hub<IClient> { ... }
```

but right now need to repeat the interface in the implementation.

**Comment by halter73** [comment]
What version of ASP.NET are you using? I think this should be fixed there by dotnet/aspnetcore#23614 in .NET 5.

**Comment by angelaki** [comment]
Actually latest version. Can check the build but it is the latest 6.0 rc

**Comment by BrennanConroy** [comment]
Just tried this and it's working as expected

```csharp
public interface IClient
{
    [HubMethodName("Method")]
    Task MethodAsync();
}

public class ClientHub : Hub<IClient>
{
    public async Task DoSomething()
    {
        await Clients.All.MethodAsync(); // Calls "Method" on the client
    }
}
```

**Comment by halter73** [comment]
Do you get a different result when you call `Clients.All.MethodAsync()` vs `((Hub)this).Clients.All.SendAsync("Method")`?

**Comment by angelaki** [comment]
Ah, ok! It only defines the _clients_ methods name! I obviously misunderstood the concept! I thought it was used to define server methods, too!
