### ISSUE TITLE
Support rendering components outside of the HttpContext

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38114]
There has been a historical ask to be able to render UI using Razor without being in the context of a web application. Many of these requests are based on things like generating HTML fragments for sending emails or even generating content for sites statically.

In the past, we've relied on "tricks/hacks" to the Razor View Engine to guide customers on how to accomplish this. However all those "hacks" are very involved and require a lot of setup. Components offer an opportunity to do this with much upfront cost for us and our customers, since they don't have any dependency on the request primitives like the Razor View Engine does.

Being able to have this support also helps with the idea of being able to render root components from ASP.NET Core in the same way we do Razor pages/views and offers several advantages for prerendering scenarios (like dealing with meta/title/etc without hacks) and a path forward for a lighter way of authoring UIs within ASP.NET Core applications.

* https://github.com/dotnet/aspnetcore/issues/30717
* https://github.com/dotnet/aspnetcore/issues/21666
* https://github.com/dotnet/aspnetcore/issues/13687
* https://github.com/dotnet/aspnetcore/issues/7528

**Comment by BurkusCat** [comment]
I seen this ticket (#40023) about pre-rendering was closed and that it pointed here to this issue. Would the completion of this issue enable static pre-rendering similar to how this package does: https://github.com/jsakamoto/BlazorWasmPreRendering.Build ?

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/46935
