### ISSUE TITLE
Visual Studio somehow unload project

### ISSUE THREAD

**Issue by chhinsras** [dotnet/aspnetcore#38118]
I didnt do anything. 
![image](https://user-images.githubusercontent.com/31751665/140539928-944cefda-f923-4cfa-8770-0a32de557d8c.png)

I try to reload but no luck. I think something wrong with visual studio.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
