### ISSUE TITLE
Blazor server connection reliability improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38124]
Having a reliable connection in Blazor Server applications is a fundamental part of the value proposition for Blazor Server, we have several issues with regards to how we deal with circuits in mobile scenarios and after long disconnection periods, we should continue to invest in ways in which we can make this work out of the box and help users get back to their session after their app got disconnected or their session expired.

* https://github.com/dotnet/aspnetcore/issues/26985
* https://github.com/dotnet/aspnetcore/issues/25415
* https://github.com/dotnet/aspnetcore/issues/23340
* https://github.com/dotnet/aspnetcore/issues/18840
* https://github.com/dotnet/aspnetcore/issues/15317

**Comment by mkArtakMSFT** [comment]
Closing as we will be prioritizing individual issues.
