### ISSUE TITLE
Better Blazor Server integration with the rest of ASP.NET Core

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38125]
While Blazor is part of ASP.NET Core, there are several repeating pain points when integrating with the rest of the stack. Some of them are due to conflicts on how Blazor is configured and some others are due to the stateful nature of Blazor apps as opposed to the rest of ASP.NET Core apps.

https://github.com/dotnet/aspnetcore/issues/19578
https://github.com/dotnet/aspnetcore/issues/23662
https://github.com/dotnet/aspnetcore/issues/25758

**Comment by mkArtakMSFT** [comment]
Triaged individual issues.
