### ISSUE TITLE
Blazor server performance improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38127]
There are several performance improvements that we can make to reduce the bandwidth used by Blazor Server. Enabling compression requires us to investigate potential security issues with regards to HTTPS, packing the frames more tightly seems to offer a 30% improvement over the frame size, finally we can "minimize" some of our JS interop callbacks to reduce the size a bit further.

* https://github.com/dotnet/aspnetcore/issues/35897
* https://github.com/dotnet/aspnetcore/issues/12306
* https://github.com/dotnet/aspnetcore/issues/13025
* ~~https://github.com/dotnet/aspnetcore/issues/37260~~
* https://github.com/dotnet/aspnetcore/issues/38109

**Comment by mkArtakMSFT** [comment]
Time-boxing this effort to `M` as it's not clear what this work is and some of the issues are separately tracked already.

**Comment by SteveSandersonMS** [comment]
The only item remaining here is now tracked by https://github.com/dotnet/aspnetcore/issues/35897 so closing in favor of that.
