### ISSUE TITLE
Document launchSettings.json

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/aspnetcore#38120]
### Is your feature request related to a problem? Please describe.
The various settings in launchSettings.json are mostly undocumented. Many are self explanatory but some are not. It's not clear what some of them do. E.g. `dotnetRunMessages` is only documented here:

- https://github.com/dotnet/aspnetcore/issues/32273

In particular, I'm personally interested in a new setting called `useSSL` used when Docker is added:

```
"Docker": {
    "commandName": "Docker",
    "launchBrowser": true,
    "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
    "publishAllPorts": true,
    "useSSL": true
}
```

### Describe the solution you'd like
Please add a documentation page documenting each and every setting in launchSettings.json

**Comment by rafikiassumani-msft** [comment]
LaunchSettings.json schema needs to be updated with `useSSL`. We may need to check which new settings are not documented. 
Link to the schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/launchsettings.json

**Comment by jessegood** [comment]
I debated on opening a new issue, but will just comment here.
Right now the `$schema` keyword only appears in the Web API template:
https://github.com/dotnet/aspnetcore/blob/91271151f6c4363606ad3520526192a8f7c7292b/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Properties/launchSettings.json#L2

However, it is missing from all the other project templates. While not required, it would be nice at least to include it in all templates.
