### ISSUE TITLE
Blazor wasm auth diagnostics

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38123]
When something goes wrong is hard for people to figure out what's going on. As a result we get many issues filed that are the result of user having incorrectly configured their application.

* https://github.com/dotnet/aspnetcore/issues/37206
* https://github.com/dotnet/aspnetcore/issues/32883
* https://github.com/dotnet/aspnetcore/issues/29633

**Comment by mkArtakMSFT** [comment]
Closing as we will be prioritizing individual issues
