### ISSUE TITLE
Blazor webassembly debugging when hosting in gRPC Application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-webassembly-debugging-when-hostin/1571082)._

---
[severity:It's more difficult to complete my work]
When trying to debug a Blazor WASM application that is hosted in a gRPC Application, and thus in an HTTP/2 server, the debugger can not connect to the debugging websocket and the hosting process emits the failure message:

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.*
```

All development certficates are installed and trusted and the WebSocket connection is established using wss:// scheme. So the TLS negotiation should succeed.

---
#### Feedback Bot on 11/3/2021, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
@lewing , @thaystg  FYI

**Comment by bjoernhoeper** [comment]
Hey,
thanks for the fast responses. Please find a minimal example in thsi repository:

https://github.com/bjoernhoeper/blazorwasmdebuggingsample

I just created a gRPC Project and added a Blazor WASM Component and the neccessary packets and services to host it inside the gRPC Web Server. I also extended the launchSettings.json to launch the browser and use the inspectUri like this for the backend:

```
{
  "profiles": {
    "BlazorWasmDebuggingSample": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001",
      "applicationUrl": "http://localhost:5000;https://localhost:5001",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

JavaScript debugging is enabled in Visual Studio 2022 preview and my Browser is Google Chrome but also tried it with Edge.

When you remove the Kestrel Configuration for HTTP/2 debugging works fine but the gRPC calls will fail.

**Comment by javiercn** [comment]
@bjoernhoeper you are missing a `ProjectReference` to the Client process [here](https://github.com/bjoernhoeper/blazorwasmdebuggingsample/blob/main/BlazorWasmDebuggingSample/BlazorWasmDebuggingSample/BlazorWasmDebuggingSample.csproj#L11). Otherwise the server doesn't know it has to host it.

**Comment by bjoernhoeper** [comment]
> @bjoernhoeper you are missing a `ProjectReference` to the Client process [here](https://github.com/bjoernhoeper/blazorwasmdebuggingsample/blob/main/BlazorWasmDebuggingSample/BlazorWasmDebuggingSample/BlazorWasmDebuggingSample.csproj#L11). Otherwise the server doesn't know it has to host it.

Ah yes missed that when hacking together the example. But the reference was present in the project originally causing the project to fail. I corrected it in the sample repo and tried it out: the error is still the same.

**Comment by thaystg** [comment]
Also to help the investigation I tried to reproduce the same that you are getting in a net6 app, and it looks like it's working correctly.
Here is my project test: https://github.com/thaystg/BlazorApGRpc

**Comment by bjoernhoeper** [comment]
> Also to help the investigation I tried to reproduce the same that you are getting in a net6 app, and it looks like it's working correctly. Here is my project test: https://github.com/thaystg/BlazorApGRpc

Hey! I tried your code and there is a subtle difference in the configurations that make it seem to work: You do not have the 

```
"Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
```

section in your appsettings.json. This leads to Kestrel allowing Http1 and Http2. But if you now try to call the greeter service it will fail because of  a downgrade to Http1.1.

**Comment by mkArtakMSFT** [comment]
Thanks for additional details, @bjoernhoeper.
For gRpc to be accessed from the browser you have to use gRPC-Web, which doesn't seem to be included in your project at all. Here are the docs on how to enable this: https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-6.0#configure-grpc-web-with-the-net-grpc-client

Also, there is no need to enable Http2 as this isn't required by gRpc-Web.

**Comment by bjoernhoeper** [comment]
@mkArtakMSFT yes that did the trick! Thank you very much!
