### ISSUE TITLE
`msftbot` removes `Needs Author Feedback` when dotnet member comments

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38135]
![image](https://user-images.githubusercontent.com/14852843/140565637-d3836171-9883-49a3-b67e-8619a3b41cc9.png)

https://github.com/dotnet/aspnetcore/issues/38131

Notice how @mkArtakMSFT added `Needs Author Feedback`, the bot recognized and left a comment notifying the original poster (`vsfeedback`) of the request. Artak then left a second comment which resulted in the bot removing `Needs Author Feedback`.

**Comment by wtgodbe** [comment]
Testing if this still true

**Comment by wtgodbe** [comment]
Seems like it's not
