### ISSUE TITLE
[Blazor Server .NET 6] Dispose sometimes called after a while (or never) when tab or browser closed

### ISSUE THREAD

**Issue by bmarinsek** [dotnet/aspnetcore#38147]
I have simple app with one page that can be accessed only by one user at a time. I've made Singletone object that tracks who currently view a page. When user close tab or browser, lock is released - in Dispose() method i remove lock in singletone object. Problem is that sometimes when i close a tab or browser, dispose is not called instantly but after couple of minutes and sometimes never (after 2 days). I figured out that when i close browser in Firefox, dispose is never called.  Is this lag by design?

I call dispose like this:

`void IDisposable.Dispose()
{
        base.Dispose();
        AppData.InUseByuser=null;  
}`

**Comment by Xyncgas** [comment]
yeah it's supposed to be like that at least that's what I've been used to, objects aren't disposed until GC comes, you can call System.GC.Collect() but maybe just use a callback or call some method manually yourself.

**Comment by bmarinsek** [comment]
Hm..i need to know when the user is leaving a page (either close a tab or browser or just redirect to another page). Is there a special event for this that i can hook on?

**Comment by javiercn** [comment]
@bmarinsek thanks for contacting us.

There's no general way of knowing when the user "ends" a session if that happens abruptly, like when a user types something on the url bar or closes the tab. In that case, the circuit will become disconnected and will get disposed after a few minutes (by default 2 or 3) when the client doesn't reconnect.

**Comment by rjgotten** [comment]
> There's no general way of knowing when the user "ends" a session if that happens abruptly, like when a user types something on the url bar or closes the tab.

Iirc under any condition where the user navigates away from a page - including closing a tab or typing a new address in the URL bar - depending on the version of the WebSockets protocol that's being used, a compliant browser should either send a clean `[0xff][0x00]` frame to request closing the connection by the peer or send a hybi packet starting with a `[0x88]` byte to signal closing the data frame.

You could probably listen for that and optimistically close the connection early.

**Comment by javiercn** [comment]
@rjgotten we already do our best to deal with those things, however there are many situations in which the websocket doesn't terminate gracefully (like the ones mentioned above) or if something else abruptly terminates the browser/tab. 

We already do our best effort to notify the server in all possible situations.

**Comment by Xyncgas** [comment]
or maybe detect the user's mouse moving away from your browser's viewport, then block the UI thread so the browser refuses to close without waiting the webpage to be responsive at first, then take your chance to send termination signal in 2~3 seconds

**Comment by mkArtakMSFT** [comment]
We have documented a way for developers to detect the unloading event and react to it as necessary: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#disconnect-the-blazor-circuit-from-the-client-blazor-server
