### ISSUE TITLE
[Blazor webasm] Please provide global way to set JSON serialization settings

### ISSUE THREAD

**Issue by astrowalker** [dotnet/aspnetcore#38144]
When defaults suffice it is good and all but after some time one add some JSON converter (or switch to Newtonsoft), so please make life for Blazor client side equally easy as it is for server side. Namely please provide counterparts for those methods:
```
            services.AddControllers() // server side
                .AddJsonOptions(json => customization...))
                .AddNewtonsoftJson(json => customization...))
                ;
```

If you call the second or third method you will get serialization set once and for good. On the server side. 

So it would be great to have something similar -- i.e. one call -- for Blazor client side.

**Comment by mkArtakMSFT** [comment]
Thanks @javiercn. This is also related to https://github.com/dotnet/aspnetcore/issues/12685, where we basically said the same.
