### ISSUE TITLE
[asp.net core 7] [feature request] make it easier to build projects to electron

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38159]

**Comment by Xyncgas** [comment]
I want my blazor app to run in electron

**Comment by Xyncgas** [comment]
discussion to whether this is worth the effort is welcomed.

**Comment by Xyncgas** [comment]
would be the first to say we have .NET MAUI coming up so electron might be not needed, although if electron is what you want, then it's kinda helpful that we can make it much easier to make blazor run in electron that it is now

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

We don't plan to offer a direct integration package with electron, and instead we recommend you use MAUI for Desktop/Mobile scenarios.

/cc: @Eilon @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
You can read more about MAUI here: https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui
