### ISSUE TITLE
Blazor .NET5: SVG text tag not rendered

### ISSUE THREAD

**Issue by yoosYyd** [dotnet/aspnetcore#38155]
Hello.
text tag from SVG which is the contained in the razor markup not render.

```
<div class="col-auto w-auto h-auto" style="background: #dfe2e8">
	<svg height="630" width="250" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
		<style>
			.static {
				font: italic 7px sans-serif;
				fill: black;
			}

			.value {
				font: italic 8px sans-serif;
				fill: black;
			}
		</style>

		<rect x="1" y="@lowZoneY" rx="10" ry="10" width="160" height="@lowZoneH" fill="@lowZoneFill" />
		<rect x="1" y="@highZoneY" rx="10" ry="10" width="160" height="@highZoneH" fill="@highZoneFill" />
		<rect x="1" y="@meedZoneY" width="160" height="@meedZoneH" fill="@meedZoneFill" />
		<rect x="1" y="4" rx="10" ry="10" width="160" height="600" fill="none" stroke="black" />
		
		<g transform="translate(0,@valShift)">
			<line x1="1" y1="604" x2="161" y2="604" stroke="black" stroke-width="2" />
			<path d="M 160,604 180,594 180,614 Z" fill="black" />
			<text>
				<text x="183" y="594" class="value">!!!!</text>
			</text>
		</g>
	</svg>
</div>

@code {
	private int val = 0;
	private string valMeans = "value";

	private int lowZoneY = 0;
	private int lowZoneH = 0;
	private string lowZoneFill = "green";
	private int meedZoneY = 0;
	private int meedZoneH = 0;
	private string meedZoneFill = "blue";
	private int highZoneY = 0;
	private int highZoneH = 0;
	private string highZoneFill = "red";

	private int maxVal = 1000;
	private int lowZoneLim = 150;
	private int meedZoneLim = 650;
	private int highZoneLim = 1000;

	private int valShift = -300;

	protected override async Task OnInitializedAsync()
	{
		lowZoneH = (int) ( (float)lowZoneLim / (float)maxVal * 600.0f);
		lowZoneH = lowZoneH + 10;
		lowZoneY = 4 + (600 - lowZoneH);
		meedZoneH = (int)((float)meedZoneLim / (float)maxVal * 600.0f);
		meedZoneH = meedZoneH - lowZoneH;
		meedZoneY = 4 + (600 - meedZoneH - lowZoneH + 10);
		highZoneH = (int)((float)highZoneLim / (float)maxVal * 600.0f);
		highZoneH = highZoneH - meedZoneH - lowZoneH;
		highZoneY = 4 + (600 - meedZoneH - lowZoneH - highZoneH);
		highZoneH = highZoneH + 20;
	}
}
```

![image](https://user-images.githubusercontent.com/29675076/140639049-3b251cc6-572f-4bc6-b5d1-135b9c8e072e.png)

builded on VS2019 16.11.5

> C:\Users\user.DESKTOP-0PUH9K6.000>dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   5.0.402
>  Commit:    e9d3381880
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19043
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.402\
> 
> Host (useful for support):
>   Version: 5.0.11
>   Commit:  f431858f8b
> 
> .NET SDKs installed:
>   2.1.802 [C:\Program Files\dotnet\sdk]
>   2.1.818 [C:\Program Files\dotnet\sdk]
>   2.2.207 [C:\Program Files\dotnet\sdk]
>   3.1.201 [C:\Program Files\dotnet\sdk]
>   3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
>   3.1.414 [C:\Program Files\dotnet\sdk]
>   5.0.104 [C:\Program Files\dotnet\sdk]
>   5.0.303 [C:\Program Files\dotnet\sdk]
>   5.0.402 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by Xyncgas** [comment]
impossible

**Comment by Xyncgas** [comment]
there must be something wrong with your computer, maybe restart it, and reinstall visual studio, then scan your computer for any viruses.

**Comment by yoosYyd** [comment]
> there must be something wrong with your computer, maybe restart it, and reinstall visual studio, then scan your computer for any viruses.

I tried run this project on my working laptop, 

> C:\Users\user>dotnet --info
> Пакет SDK для .NET (отражающий любой global.json):
>  Version:   5.0.402
>  Commit:    e9d3381880
> 
> Среда выполнения:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.402\
> 
> Host (useful for support):
>   Version: 5.0.11
>   Commit:  f431858f8b
> 
> .NET SDKs installed:
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.526 [C:\Program Files\dotnet\sdk]
>   2.2.100 [C:\Program Files\dotnet\sdk]
>   3.1.414 [C:\Program Files\dotnet\sdk]
>   5.0.104 [C:\Program Files\dotnet\sdk]
>   5.0.303 [C:\Program Files\dotnet\sdk]
>   5.0.402 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

and got the same problem...

**Comment by javiercn** [comment]
@yoosYyd thanks for contacting us.

We have limited support for SVG in .NET 5.0 we've improved this in 6.0 would you give it a try with 6.0 and let us know if you still have issues?

**Comment by yoosYyd** [comment]
> @yoosYyd thanks for contacting us.
> 
> We have limited support for SVG in .NET 5.0 we've improved this in 6.0 would you give it a try with 6.0 and let us know if you still have issues?

which is version Visual Studio needs for migration to net6 sdk ?

**Comment by TanayParikh** [comment]
> > @yoosYyd thanks for contacting us.
> > We have limited support for SVG in .NET 5.0 we've improved this in 6.0 would you give it a try with 6.0 and let us know if you still have issues?
> 
> which is version Visual Studio needs for migration to net6 sdk ?

VS2022 was just released, check it out here: https://visualstudio.microsoft.com/vs/

**Comment by TanayParikh** [comment]
Oh, looks like [`svg` has a `text` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text), which may be conflicting with Razor's `text` tag. @javiercn do you happen to know if we special case disable the Razor `<text>` tag within svg to prevent a conflict / ambiguity?

**Comment by javiercn** [comment]
@NTaylorMullen do you know what the magic here is?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you know what the magic here is?

I donnn't think the compiler special cases svg so in the scenario when a user is trying to use the Razor languages `<text>` tag (only applicable in C# blocks IIRC) then you'd get into trouble

**Comment by TanayParikh** [comment]
> so in the scenario when a user is trying to use the Razor languages `<text>` tag (only applicable in C# blocks IIRC) then you'd get into trouble

Hmm. In this context I believe @yoosYyd is trying to use the [`svg` `<text>` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text), which based on what you said shouldn't be ambiguous in this context with the Razor `text` tag as we are _not_ in C#. 

Trying out the provided code, it appears the issue may be the nested `<text>` tags. I believe it may need to be 

```html
<text x="183" y="594" class="value">!!!!</text>
```

instead of

```
<text>
	<text x="183" y="594" class="value">!!!!</text>
</text>
```

Doing this yields `!!!!` next to the bar:

![image](https://user-images.githubusercontent.com/14852843/140828984-cff35bc7-bb7b-4d5a-b920-ba018a69dbea.png)

**Comment by javiercn** [comment]
@NTaylorMullen I was looking for the escape sequence, but @TanayParikh already found it.

**Comment by yoosYyd** [comment]
> > so in the scenario when a user is trying to use the Razor languages `<text>` tag (only applicable in C# blocks IIRC) then you'd get into trouble
> 
> Hmm. In this context I believe @yoosYyd is trying to use the [`svg` `<text>` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text), which based on what you said shouldn't be ambiguous in this context with the Razor `text` tag as we are _not_ in C#.
> 
> Trying out the provided code, it appears the issue may be the nested `<text>` tags. I believe it may need to be
> 
> ```
> <text x="183" y="594" class="value">!!!!</text>
> ```
> 
> instead of
> 
> ```
> <text>
> 	<text x="183" y="594" class="value">!!!!</text>
> </text>
> ```
> 
> Doing this yields `!!!!` next to the bar:
> 
> ![image](https://user-images.githubusercontent.com/14852843/140828984-cff35bc7-bb7b-4d5a-b920-ba018a69dbea.png)
> 
> @yoosYyd does this resolve your issue?

Yes.
But.Can you help me understand...
Why here (https://stackoverflow.com/a/64230404/4665067) is the suggested wrapping of svg text tag to razor text tag. And in my case this doesnt work ?

**Comment by javiercn** [comment]
@yoosYyd I believe th4e issue here is that Razor doesn't understand SVG, in essence it's unfortunate that they both use `<text>` for different things. 

What that causes is that depending on the context, Razor will interpret the <text> as the escape sequence to go back into markup or as an actual literal, hence why it sometimes needs to be wrapped.
