### ISSUE TITLE
Blazor WASM transfer file

### ISSUE THREAD

**Issue by onimor** [dotnet/aspnetcore#38166]
.NET5 , Blazor WASM.
I am trying to transfer a file to the server using gRPC in parts, it consumes a lot of RAM by the browser. 
A 100 MB file takes up 1 GIGABYTE... not to mention 500-900 MB files. 

Tried it [as described here](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=webassembly) but I get the same expense.

How can I upload files to the server at no great cost?
[Here is a test project with download and upload](https://github.com/onimor/CIMFileTest)

**Comment by javiercn** [comment]
@onimor thanks for contacting us.

When you are downloading files you seem to be putting all the data in a giant byte array. That's likely going to cause those memory spikes.

For uploading files, it's hard to tell based on your code what's goin on. We would suggest you try to do the same upload from a console app and make sure that the problem doesn't reproduce there.

@JamesNK do you know how streaming works for GRPC web?

**Comment by onimor** [comment]
@javiercn,  he commented on it as "I'm surprised this doesn't error. gRPC-Web in Blazor WebAssembly doesn't support client streaming. If it does work, then the client must be buffering all data before sending it. That would explain why you have high memory usage."

**Comment by javiercn** [comment]
@onimor use an HTTP endpoint for the file upload in chunks, maybe using a `Range` request.

**Comment by TanayParikh** [comment]
If you upgrade to .NET 6, you can leverage Blazor's streaming interop to transfer files. Documentation available here:

- https://docs.microsoft.com/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly
- https://docs.microsoft.com/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0

**Comment by JamesNK** [comment]
> @onimor use an HTTP endpoint for the file upload in chunks, maybe using a `Range` request.

Is that using HttpClient? As far as I know, in Blazor WebAssembly the HttpClient will always send via the fetch API, and it doesn't support streamed uploads.

**Comment by onimor** [comment]
> If you upgrade to .NET 6, you can leverage Blazor's streaming interop to transfer files. Documentation available here:

I made a commit where I  switched to .NET6 , also did the same following the example from the link. A 62mb file consumes 500 MB of RAM.

**Comment by onimor** [comment]
The problem is not solved...

**Comment by TanayParikh** [comment]
> also did the same following the example from the link

Could you provide a snippet of the exact code you're using to do this? Are you using the InputFile component? If not are you still experiencing the issue after using it?

> 62mb file consumes 500 MB of RAM.

What tool or methodology did you use to measure this.

**Comment by onimor** [comment]
> Could you provide a snippet of the exact code you're using to do this?
[Here is a test project with download and upload](https://github.com/onimor/CIMFileTest)

> Are you using the InputFile component?

`private async void UploadFiles(InputFileChangeEventArgs e)`



> What tool or methodology did you use to measure this.

I am watching how the RAM consumed by the browser in the task manager is growing

**Comment by TanayParikh** [comment]
Thanks for your response.

> I am watching how the RAM consumed by the browser in the task manager is growing.
> It can also be seen through debugging using the browser.

Neither would be representative ways of measuring the overall memory perf of Blazor, nor a specific feature within Blazor. 

The browser/task manager view shows the total memory consumption of the browser and is influenced by a large number of factors, including browser engine, installed extensions, other tabs and processes, etc. 

By "debugging using the browser" I'm assuming you're referring to the VS diagnostic tools that you can see when debugging. This would not be a definitive measure of memory as it's also influenced by a host of other factors. Additionally, all performance profiling should be done _without_ the debugger attached, and running in `Release` mode to ensure all compiler / linking optimizations have been made. 

I'd recommend reviewing https://github.com/sebastienros/memoryleak for more details on how we investigate performance and memory issues.

**Comment by onimor** [comment]
> By "debugging using the browser" I'm assuming you're referring to the VS diagnostic tools that you can see when debugging.

I meant Edge, it has a "Memory" tab, you can take pictures in it, as well as fully control consumption. The heap snapshot profiles show the memory allocation between the JS page objects and the corresponding DOM nodes.
