### ISSUE TITLE
[asp.net core 7] [feature request] make Github desktop ignore irrelevent files

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38167]
Currently every commit is like thoudsands of files.
Reproduceble -> create a new repository in github desktop.
push it to remote -> create your blazor project locally -> commit.

**Comment by matsE94** [comment]
Is there a reason why a .gitignore file is not sufficiant?

Put this in your .gitignore to only push relevant files
[Oo]bj/
[Bb]in/

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

@matsE94 answer is correct. In addition to that you can do `dotnet new gitignore` and it'll add a gitignore file to your project.

**Comment by Xyncgas** [comment]
in windows I cd-ed to the directory, ran dotnet new gitignore
![image](https://user-images.githubusercontent.com/35312807/140824349-40fbbd39-ec0a-47f4-b91f-01accad095a0.png)

**Comment by Xyncgas** [comment]
![image](https://user-images.githubusercontent.com/35312807/140824458-b1db22b6-46af-4d15-9f07-ef8cead1000c.png)

**Comment by Xyncgas** [comment]
I tried gitignore before, but it didn't work for me
I am using github desktop.
but I think it would be more appropriate to submmit this issues to github desktop
