### ISSUE TITLE
[asp.net core 7] [feature request] Multi-thread support for blazor

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38160]
So I can run compute heavy works in another thread.

**Comment by Xyncgas** [comment]
Although there's .NET MAUI Blazor APP already, which runs in native .NET process then using webUI to render web stuffs

**Comment by Xyncgas** [comment]
but it still would be nice to have threads in the blazer wasm

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/17730
