### ISSUE TITLE
[asp.net 7] [feature request] [experimental] bring figma sharp to light

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38161]
https://github.com/microsoft/FigmaSharp

**Comment by Xyncgas** [comment]
Let's make blazor app in GUI, like we did with .net framework for windows app

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

Our team is focused on the Blazor framework and Razor related tooling. We suggest you ask for support for Blazor in FigmaSharp directly, as this integration is not something that our team has immediate plans to work on.

/cc: @danroth27
