### ISSUE TITLE
[asp.net core 7] [Feature Request] Further Compressing Blazor's render html on release build.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38164]
For example if I am using <div class="abc123/> in a for loop, I want to minimize that 'abc123', in order to save memory on browsers

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is not something we plan to work on. The cost of implementing such a feature is very high and the hypothetical memory/bandwidth improvements don't justify such an investment.

You can replace the values in your example with static variables or a similar mechanism and have those populate at runtime the right value. However that will prevent important optimizations Razor performs on the generated markup, so it will very likely be detrimental.
