### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.2.21 has broken dependencies on NuGet

### ISSUE THREAD

**Issue by NinjaCross** [dotnet/aspnetcore#38172]
# The problem
The package **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation**, version **3.2.21** in NuGet (see https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation/3.1.21) refers to unexisting packages:

- https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.Extensions/3.1.21
- https://www.nuget.org/packages/Microsoft.CodeAnalysis.Razor/3.1.21

# To Reproduce
- Add the **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation**, version **3.2.21** package to any CSPROJ
- Try to build. The build will fail

**Comment by javiercn** [comment]
@NinjaCross thanks for contacting us.

@pranavkm @dotnet/aspnet-build any thoughts?

**Comment by rjgotten** [comment]
Ran across this as well.

`dotnet restore` seems to happily pick up and use the 5.x packages instead - which creates version conflicts further down the line. Having a look at the .csproj file for the `RuntimeCompilation` project, it doesn't seem to specify any version bounds. Might explain that weird quirk?

**Comment by BrennanConroy** [comment]
Looks like the aspnetcore-tooling repo was renamed to razor-tooling recently which broke the flow of nuget packages when pushing. We're working on getting the packages uploaded.

**Comment by NinjaCross** [comment]
The work-around we had to adopt was to force using the specific version 
https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation/3.1.20
instead of the floating version 3.1.*
A bit dirty, but works.

**Comment by NinjaCross** [comment]
>  Is this default NuGet behavior? (And if it's default behavior: holy crap: why is NuGet allowed to automatically switch over to a new major version?! I'd prefer it just flat out break, and really I'm probably not alone there.)

As far as I can see here, it shouldn't
https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution

**Comment by BrennanConroy** [comment]
Missing packages have been uploaded. Can someone double check that this is resolved?

**Comment by rjgotten** [comment]
> 
> 
> > Is this default NuGet behavior? (And if it's default behavior: holy crap: why is NuGet allowed to automatically switch over to a new major version?! I'd prefer it just flat out break, and really I'm probably not alone there.)
> 
> As far as I can see here, it shouldn't https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution

It seems like this particular case; `>= x` where `x` doesn't actually exist, isn't documented though.
Which leaves me with not-so slight unease that this is something of a bug in the current package dependency version resolution...

**Comment by NinjaCross** [comment]
> Missing packages have been uploaded. Can someone double check that this is resolved?

It works now, thanks
