### ISSUE TITLE
Windows 7: Blazor-Server CSS hot reload doesn't work

### ISSUE THREAD

**Issue by CommonLoon102** [dotnet/aspnetcore#38188]
### Describe the bug
CSS Hot reloading doesn't work on Windows 7 for Blazor-Server projects.
This bug either should be fixed or mentioned here:
https://docs.microsoft.com/en-us/troubleshoot/visualstudio/general/visual-studio-2022-unsupported-operating-systems#windows-7-and-windows-server-2008-r2

The below scenarios work just fine on Windows 10 (it is not even needed to save `site.css`, changes reflect instantly).

### To Reproduce
1. Create new Blazor-Server project
2. Run with or without debugging
3. Edit `site.css`
4. Add `background-color: black;` to `html, body`
5. Click Hot-Reload
6. Background didn't change to black
7. Workaround: click refresh (F5) in the browser, but then the application state won't persist

Other scenario:
1. Create new Blazor-Server project
2. Run with or without debugging
3. Edit `MainLayout.razor.css`
4. Comment out the `.sidebar` block
5. Click Hot-Reload
6. Sidebar's background didn't change

### Further technical details
- ASP.NET Core version: .NET 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 GA
- OS: Windows 7 64 bit
- Browser: MS Edge 95.0.1020.44
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.101 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\sha
red\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\
Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\
shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by pranavkm** [comment]
Thanks for the issue report @CommonLoon102. Could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue? That way it will get to the routed to the right that owns this experience in VS.
