### ISSUE TITLE
Vs2022 official version 17.0.0 asp.net core 6 MVC, unable to jump to the controller in the view

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#38197]
Vs2022 official version 17.0.0 asp.net core 6 MVC, unable to jump to the controller in the view

2019 right click the view to jump to the controller. In addition, when writing an HTML page, the keyword class = in 2022 will not automatically double quote. 2019 is OK.

**Comment by TanayParikh** [comment]
Hello @bbhxwl, thanks for contacting us. Could you please create a VS feedback issue (Report a Problem button in VS) so that it may be directed to the appropriate VS tooling team.

**Comment by bbhxwl** [comment]
> Hello @bbhxwl, thanks for contacting us. Could you please create a VS feedback issue (Report a Problem button in VS) so that it may be directed to the appropriate VS tooling team.

My English is not good. Where can I submit questions to vs2022 team?

**Comment by TanayParikh** [comment]
> > Hello @bbhxwl, thanks for contacting us. Could you please create a VS feedback issue (Report a Problem button in VS) so that it may be directed to the appropriate VS tooling team.
> 
> My English is not good. Where can I submit questions to vs2022 team?
> 


Hey @bbhxwl, please see https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 for details on reporting a problem.
