### ISSUE TITLE
Hi @jojorgeluisrdz198. It looks like you just commented on a closed PR. The team will most probably miss it. If you'd like to bring something important up to their attention, consider filing a new issue and add enough details to build context.

### ISSUE THREAD

**Issue by jojorgeluisrdz198** [dotnet/aspnetcore#38193]
Hi @jojorgeluisrdz198. It looks like you just commented on a closed PR. The team will most probably miss it. If you'd like to bring something important up to their attention, consider filing a new issue and add enough details to build context.

_Publicado originalmente por @msftbot en https://github.com/dotnet/aspnetcore/pull/37854#issuecomment-963789890_

**Comment by TanayParikh** [comment]
Seems to be referencing https://github.com/dotnet/aspnetcore/pull/37854#issuecomment-963789873, which is just a direct quote. Closing this out.
