### ISSUE TITLE
[Epic]: SignalR - .NET7

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#38196]
S = A few hours 
M = A few days (1-5 days)
L = About a week (1 - 2 weeks)
XL = > 2-3 weeks
XXL = ~ Milestone (Needs to be broken down)

| Issue                                                        | Category                           | Priority | Size | Status |
| ------------------------------------------------------------ | ---------------------------------- | -------- | ---- | ------ |
| Crank testing for SignalR (https://github.com/dotnet/aspnetcore/issues/37909)  | `testing`   | P1       | M    | Committed   |
| SignalR streaming (Broadcast) from server to client  (https://github.com/dotnet/aspnetcore/issues/10151)  | `client, server, protocol`| P3 | XXL|
| Seamless reconnect - Allows the server to retain the buffer and preserve state | `client, server`|  P2  | XXL| Stretch goal/re-evaluate
| Allow Values to be returned from client invocations (https://github.com/dotnet/aspnetcore/issues/5280) | `client, server`| P0   | XXL| Committed 
| Refresh authorization tokens (https://github.com/dotnet/aspnetcore/issues/5297) | `client, server, protocol`|  P1  | XXL|
| Blazor server + SignalR enhancements (https://github.com/dotnet/aspnetcore/issues/10407) | `client, server`|  P1  | XL |
| Fix streaming back-pressure - Needs support for flow control in the protocol (https://github.com/dotnet/aspnetcore/issues/33859) | `client, server, protocol`|  P2  | M|
| Orleans backplane for SignalR | `client, server, protocol`| P1   | XL| Experiment (E2E spike) @bradygaster @halter73 @ReubenBond 
| AFD (Azure Front Door) connection isssues - No support for websockets (https://github.com/MicrosoftDocs/architecture-center/issues/1891) | `Azure`|    | XL| Needs to reach out to Azure team
| Docs - https://github.com/dotnet/AspNetCore.Docs/issues/23357 | Docs | P2 | XL

**Comment by ThisWillDoIt** [comment]
No Azure Front Door support is a real stopper for adopting SignalR for us.  
As SignalR in itself is fine as it is, can we vote somewhere on any Azure board in case this whole EPIC won't be in .NET7?

**Comment by BrennanConroy** [comment]
> can we vote somewhere on any Azure board

https://feedback.azure.com/d365community/idea/c8b1d257-8a26-ec11-b6e6-000d3a4f0789
