### ISSUE TITLE
Choosing AOT in Blazor.Wasm Doesn't produce Webassembly files -->Click here to see details

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38191]
I am using visual studio 2022 Current
Testing AOT with a fresh project, which is created then pasted some razor + c# files inside
![image](https://user-images.githubusercontent.com/35312807/140851234-b7b140bf-4ecb-49c1-b6e9-1fef3badabbd.png)

According to 
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-4/#blazor-webassembly-ahead-of-time-aot-compilation

This option would create Webassembly files when published

But I look at my published site pressing F12, I see Mono.Wasm.Invalid
![image](https://user-images.githubusercontent.com/35312807/140851756-26816758-8d60-46fc-a42d-9e731108b57d.png)

**Comment by TanayParikh** [comment]
Hi @Xyncgas, thanks for contacting us. There have been many changes since 6.0 Preview 4, I'd recommend checking out the latest guidance here: https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation

**Comment by Xyncgas** [comment]
thanks

**Comment by Xyncgas** [comment]
although i am still wondering, after reading it, if mono-wasm.invalid means AOT failed to compile to wasm and using asm.js instead

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

AoT in .NET doesn't compile the entire application to Webassembly. Some things can't be AoT and would require you to change your code to avoid things like reflection or ILEmit that I believe are currently interpreted.
