### ISSUE TITLE
BUG: <PageTitle> not works in WasmPrerender mode

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/aspnetcore#38192]
### Describe the bug
When using 
```razor
<component type="typeof(Client.App)" render-mode="WebAssemblyPrerendered" />
```
page title won't update before you get page.
You get mearkup like
![image](https://user-images.githubusercontent.com/50731756/140857207-d8677c05-b561-4ad9-b6cf-74ce0b503059.png)

### To Reproduce
https://github.com/ParadiseFallen/WasmBlazorPrerendered
Just run Host project. look at Client project.
open link/counter
after some time title will update to "Counter 0"

Open postman
Send [GET]  link/counter
In markup title is Client

### Exceptions (if any)
no

### Further technical details
.net 6
VS 2022 Current

**Comment by ParadiseFallen** [comment]
@TanayParikh why this is feature? 
It seems to me that this is a bug. Components have been added to change the <head> but they are executed ONLY on the client side. which is not entirely correct.

**Comment by TanayParikh** [comment]
Feature labels are used in this repo to categorize issues by product areas.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is because you're prerendering only the body of the page, rather than the header, which you should also do. [Here are the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly) to help you with that.
You essentially need to add something like the below tag in your page's head section:

```razor
<component type="typeof(HeadOutlet)" render-mode="WebAssemblyPrerendered" />
```

**Comment by ParadiseFallen** [comment]
> Thanks for contacting us. This is because you're prerendering only the body of the page, rather than the header, which you should also do. [Here are the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly) to help you with that. You essentially need to add something like the below tag in your page's head section:
> 
> ```
> <component type="typeof(HeadOutlet)" render-mode="WebAssemblyPrerendered" />
> ```

it dont work also. i tryed it. did you download and run project?
[builder.RootComponents.Add<HeadOutlet>("head::after");](https://github.com/ParadiseFallen/WasmBlazorPrerendered/blob/4af73c41443cc2c4c50add518a54ce91edfa7073/Client/Program.cs#L7)

thats in client Program But!
event if ill use `component` it still dont work. test it. same behaviour

**Comment by mkArtakMSFT** [comment]
Thanks for trying that out and bringing this up. We will document the specific pattern so that other customers also follow the guidance going forward.

**Comment by mkArtakMSFT** [comment]
Actually, looks like we already have documentation on how to do this. Please follow the instructions here: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly#prerendering-configuration

**Comment by ParadiseFallen** [comment]
@mkArtakMSFT 
What?

the problem is in.  Om that even following the instructions (I updated the project with an example) during the pre-renderer on the server, the markup does not include the new PageTitle that was set in any component.

You just get markup with empty <title> or default <title>. But what i expect is title that was set from component. 

Now its not working. Its seems that it sets title via JavaScript and its sont execute while page renders on server for prerendering. 
And you dont get actuall title.

Thats a bug.

**Comment by ParadiseFallen** [comment]
```razor
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <title>Default page title</title>

    <component type="typeof(HeadOutlet)" render-mode="WebAssemblyPrerendered" />

    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="Client.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />

</head>

<body>

    <component type="typeof(Client.App)" render-mode="WebAssemblyPrerendered" />
    <persist-component-state/>

    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
</body>

</html>
```
`_Host.cshtml` markup
```razor
@page "/"

<PageTitle >Index page set from component</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />


```
`Index.razor` markup

Server response (made request with Postman ) (show only head part):
```html

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

	<title>Default page title</title>

	<!--Blazor:{"type":"webassembly","assembly":"Microsoft.AspNetCore.Components.Web","typeName":"Microsoft.AspNetCore.Components.Web.HeadOutlet","parameterDefinitions":"W10=","parameterValues":"W10=","prerenderId":"86b09d0ae82f4d8c8ffa2276f12af390"}-->
	<!--Blazor:{"prerenderId":"86b09d0ae82f4d8c8ffa2276f12af390"}-->

	<base href="/" />
	<link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
	<link href="css/app.css" rel="stylesheet" />
	<link href="Client.styles.css" rel="stylesheet" />
	<link href="manifest.json" rel="manifest" />
	<link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
	<link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />

</head>

```


And there bug.
cuz <title> was expected "Index page set from component" not "Default page title"

**Comment by ParadiseFallen** [comment]
Is there any progress on this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for additional details.
The issue remains because you didn't follow the instructions pointed out in the docs. Specifically, you haven't added the `_Layout.cshtml` file, which is a key here.
Razor pages are rendered in a way, where the components are rendered first and then the layout. In your code, you don't have a layout, so the rendering happens from top-down. Hence, when the rendering logic gets to rendering `HeadOutlet` component, at that point it doesn't know about the title that the app is going to set at a later time (from the `Index.razor`. Hence, the default title is being used. When the rendering gets to the `App` component, at that stage the title set by it is ignored, because the head portion of the page has already been rendered (earlier).
Now, when you introduce a `_Layout.cshtml` file, all the components are rendered before the layout itself, hence, the page title would be set before the `HeadOutlet` rendering starts, and so things would work as expected.

This is very rough explanation, but hope it helps to clarify the need for having _Layout.cshtml file.

**Comment by ParadiseFallen** [comment]
@mkArtakMSFT Good. So it works if I move everything to layout.
It seems strange to me. Because it forces me to use Layout when I don't really need it. I thought it would work the same as ViewBag.

Then the DOCS should have a warning about USING the layout if that's an important part of it.
But is there a way not to use Layout?

Or does this function only work in layout?

**Comment by mkArtak** [comment]
What matters here is the order in which rendering happens. That's a limitation we currently have and introducing layout helps with that.

@guardrex can you please add a highlighted section in the docs calling out that the usage of a layout is important per my comment above: https://github.com/dotnet/aspnetcore/issues/38192#issuecomment-976175350

**Comment by ParadiseFallen** [comment]
@mkArtak I saw somewhere suggestion about better components for razor pages

```razor
<component>
  //inner content
</component>
```
like it works in blazor but for razor pages.
it will help there if made <Head></Head> built in component and say rander it at end

If there only order matter then is it possible to:
TopLevelLayout
simpleLayout (that uses RenderBody() + use TopLevelLayout + HeadOutlet component)
_Host file with app.

will it works? cuz if i understand right it renders inside out starting from deepest component

**Comment by guardrex** [comment]
@mkArtak ... The DRAFT updates are on https://github.com/dotnet/AspNetCore.Docs/pull/24035. Please review carefully. That set of scenarios is complex and tricky. I usually only feel comfortable with changes to that guidance when I go through and test every scenario with a set of local set apps. I'm :ear: if you think that's necessary.

Testing was performed for 6.0 updates, but there's one scenario where I think I missed an update to control head content for RP/MVC apps that embed components from a hosted WASM app into pages/views. I didn't add the `HeadOutlet` component to the RP/MVC app's layout file. It's on the PR. That section was tested during 6.0 updates, but I failed to notice (or consider, really) that the `PageTitle` component of the embedded component wasn't setting the page's title ... **_IF this is even a working scenario._** Without local testing, I'm not really sure if it even will work. I can see devs wanting this behavior tho ... not so much for the page's title ... more so for **_setting head content with the `HeadContent` component_**.

I think the rest of the scenario updates for 6.0 were fine. To meet your ask here, I only needed to add a new NOTE in each section and a cross-link to a new section in the *Control \<head> Content* article that explains this layout requirement.

**Comment by ParadiseFallen** [comment]
@SteveSandersonMS It seems as solved issue. Im just waiting for docs impovement.

**Comment by mkArtakMSFT** [comment]
Thank you, @guardrex! Closing this issue now.
