### ISSUE TITLE
Expose ITlsHandshakeFeature for in-proc

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#3819]
https://github.com/aspnet/HttpAbstractions/pull/1019

**Comment by muratg** [comment]
HttpSys feature: https://github.com/aspnet/HttpSysServer/issues/83

**Comment by muratg** [comment]
@shirhatti could you also file the Kestrel bug?

**Comment by shirhatti** [comment]
Turns out Kestrel already does this- https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Connections.Abstractions/src/Features/ITlsHandshakeFeature.cs

**Comment by jkotalik** [comment]
Dup of #15397
