### ISSUE TITLE
Dashboard like Phoenix Liveview Dashboard for ASP.NET Core 7

### ISSUE THREAD

**Issue by GiorgioG** [dotnet/aspnetcore#38207]
https://github.com/phoenixframework/phoenix_live_dashboard

**Comment by blowdart** [comment]
It's unclear what you're asking for here. Do you want something like this? A telemetry dashboard?

**Comment by javiercn** [comment]
@blowdart I think the ask here is a built-in UI library to display diagnostic information.

/cc: @shirhatti FYI

**Comment by davidfowl** [comment]
Looks like dotnet monitor maybe.

**Comment by adityamandaleeka** [comment]
@GiorgioG Any clarification about what you're looking for here?

**Comment by davidfowl** [comment]
https://github.com/dotnet/dotnet-monitor
