### ISSUE TITLE
Blazor supporting an IEnumerable of RenderFragment as children

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/aspnetcore#38206]
### Is your feature request related to a problem? Please describe.
There are cases when you want your component to be just a styled wrapper around an undefined number of items. Currently, if you have a specific number of items, you can specify them inside the component with them being parameters of type RenderFragment. But what if I don't know how much items there will be? 
I've seen how Ant Design Blazor implemented it for their [BasicList](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/list) and they used a weird trick when each children gets a reference to the parent and adds itself to a list of render fragment, that gets rendered afterwards, but I find it too much obscure to be used normally. In React I can't differentiate between the children, but there is props.children that do exactly what I'm asking for

### Describe the solution you'd like

Definition
```razor
<div style="my-style">
   // This is a simple case, but children could be placed anywhere in the structure
   @Children
</div>

@code 
{
    [Parameter]
    IEnumerable<RenderFragment> Children {get;set;}
}
```

Usage
```
<MyComponent>
    @foreach(var item in Items) // We don't know how much elements there are
    {
         <div>@item.Title</div>
    }
</MyComponent>
```

Thank you and regards
Manuele

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're going to tackle this as part of https://github.com/dotnet/aspnetcore/issues/29379
