### ISSUE TITLE
The group can be removed if there is none in the group in signalr?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38200]
I can add a user to a group and I can remove it too.

but If I add to group it will create a group then I remove it the group will be removed?
if not there will be more and more group.

**Comment by BrennanConroy** [comment]
> then I remove it the group will be removed?

Yes, are you seeing issues?

**Comment by mcguu** [comment]
can you tell me where is the code that will remove the group ? @BrennanConroy

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/blob/dc8f45c7010b057eb5c34d0c5c89d656ab6ec7f3/src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs#L77

**Comment by mcguu** [comment]
@BrennanConroy  I know the code that remove the user from the group.

what I am confused is if the group will be deleted.

let me explain:
I add a user to group `order-1` and add another user to group `chat-2` 
if there is no user in `order-1` or `chat-2` the group will be deleted?
or there will be too many groups `chat-1` to `chat-1000000` right?

**Comment by adityamandaleeka** [comment]
@mcguu The group should go away if there are no users in it. Are you seeing an issue with that?

**Comment by halter73** [comment]
https://github.com/dotnet/aspnetcore/blob/dc8f45c7010b057eb5c34d0c5c89d656ab6ec7f3/src/SignalR/server/Core/src/Internal/HubGroupList.cs#L37-L44

**Comment by mcguu** [comment]
@halter73 thank you.

@adityamandaleeka  I do not see any issue yet. I just wonder if there will be any issue.I think there is no need to sendMessage onece the data is changed so I want to create a subscription. when the client want to get the change he can subscribe to one record. then there will be a lot of groups to send message.

now you can close this issue.

**Comment by mcguu** [comment]
dfsffsgsf

**Comment by mcguu** [comment]
sddddddddddddddddddddddd
