### ISSUE TITLE
RemoteJSRuntime uses SignalR global options instead of ComponentHub options

### ISSUE THREAD

**Issue by peerpalo** [dotnet/aspnetcore#38205]
### Describe the bug
I'm trying to deserialize a > 32KB Uint8Array from JavaScript to Blazor and I'm receiving "Exceeded the maximum byte array transfer limit for a call" even if I've increased "MaximumReceiveMessageSize"

![image](https://user-images.githubusercontent.com/6475341/140912793-9383b1ba-41f4-4c03-8981-dd56fc768aed.png)

The only way to fix it it's to increase SignalR global options "MaximumReceiveMessageSize"

![image](https://user-images.githubusercontent.com/6475341/140912969-0676292b-2599-4f73-8a89-1c802125df20.png)

Is that a wanted behaviour? From what I'm seeing problem is here https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L42 

### To Reproduce
Try to get a > 32KB Uint8Array from JavaScript to Blazor by using JSRuntime

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/6475341/140912659-7e966866-9c53-44b9-ba52-e742e9fc2919.png)

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: 17.0.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.520 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

</details>

**Comment by javiercn** [comment]
@peerpalo thanks for contacting us.

If you have large payloads we recommend you use https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-7/#blazor-streaming-interop-from-javascript-to-net instead of trying to receive the payload on a single message.

You'll be allocating up to 10MB arrays which is something you want to avoid.

**Comment by peerpalo** [comment]
> 
> 
> @peerpalo thanks for contacting us.
> 
> If you have large payloads we recommend you use https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-7/#blazor-streaming-interop-from-javascript-to-net instead of trying to receive the payload on a single message.
> 
> You'll be allocating up to 10MB arrays which is something you want to avoid.

Oh, wow, amazing. Guess I'll need to pay more attention to release notes 😀 - it's even better now: I'm removing also "MaximumReceiveMessageSize" from ComponentHub.

I don't know if this bug still applies or not

**Comment by javiercn** [comment]
@peerpalo I still want to keep it open to see what other folks thing about it.

@BrennanConroy might have thoughts here.

**Comment by mkArtakMSFT** [comment]
Ping @BrennanConroy

**Comment by BrennanConroy** [comment]
Looks like RemoteJSRuntime should look at the hub specific options first and fallback to global hub options.

Check `HubOptions<THub>` before `HubOptions`.
Example at https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/SignalR/server/Core/src/HubConnectionHandler.cs#L54-L55

Currently it's not possible to detect if the user set an option with a valid null value to null (like `MaximumReceiveMessageSize`), but for the majority of cases you should be able to correctly check hub specific options over global hub options.

Might want to file an issue for detecting if user set an option to null.

**Comment by TanayParikh** [comment]
> Might want to file an issue for detecting if user set an option to null.

I believe this should handle the `null` case:
https://github.com/dotnet/aspnetcore/pull/38947/files#diff-7fac6aa482260bd9b68de9fd59db0da9d8532c59ecdfd4468c0f51d371b562aaR43-R45
