### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#38201]
There is an error in documentation:
![image](https://user-images.githubusercontent.com/23618436/140893872-7360c456-75df-42e7-ab04-5b00a2afc0cc.png)

here:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#preserve-prerendered-state

and here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/preserve-component-state?view=aspnetcore-6.0&pivots=server#preserve-component-state-tag-helper

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

If you want to contribute a fix, feel free to send a PR to the docs repo. Otherwise, @guardrex can you get this bit updated?

**Comment by guardrex** [comment]
What's the error, @javiercn, because this coverage came from Dan's blog post at ...

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-2/#preserve-prerendered-state-in-blazor-apps

**Comment by guardrex** [comment]
Ah ... lol ... "preserve" vs. "persist" ..... **_MORE_** ☕ **_PLZ!_** 😄

I'll take care of it right now. Thanks @JulienM28!

**Comment by guardrex** [comment]
@danroth27 ... I was **too literal** on copying your blog post. It's exactly this way in your post in case u want to update it.

**Comment by guardrex** [comment]
This will be fixed by https://github.com/dotnet/AspNetCore.Docs/pull/23812. This PU issue can be closed.

**Comment by javiercn** [comment]
@guardrex thanks

**Comment by danroth27** [comment]
> @danroth27 ... I was too literal on copying your blog post. It's exactly this way in your post in case u want to update it.

Whoops! Should be fixed now on the blog post.
