### ISSUE TITLE
Make JSInterop (@microsoft/dotnet-js-interop) UMD-compatible

### ISSUE THREAD

**Issue by Elringus** [dotnet/aspnetcore#38208]
Can you please consider supporting [UMD](https://github.com/umdjs/umd) for the JSInterop library distributed via NPM (https://www.npmjs.com/package/@microsoft/dotnet-js-interop)?

I'm using this library to implement a single-file UMD dotnet JS runtime to be used in constrained environments (such as [web extensions for vscode.dev](https://code.visualstudio.com/api/extension-guides/web-extensions)) and have to replace `window` global to make it compatible.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to add support for out of the box.

**Comment by Elringus** [comment]
> 
> 
> Thanks for contacting us. This is not something we plan to add support for out of the box.

That's unfortunate. With a very basic change (just copy-pasting a UMD header template) that won't add any maintain cost or API changes on your side you could open the library for a much wider use cases.

**Comment by Elringus** [comment]
In case someone find this having similar problem, I've published UMD library based on the original JSInterop: https://www.npmjs.com/package/dotnet-js-interop It can be used in any environment: browser, nodejs, webview, etc.
