### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.Extensions package dependent on prerelease package 

### ISSUE THREAD

**Issue by Jupakabra** [dotnet/aspnetcore#38214]
### Describe the bug
We are upgrading our tools to dotnet 6 and noticed that `Microsoft.AspNetCore.Mvc.Razor.Extensions` is asking for `Microsoft.CodeAnalysis.CSharp >= 4.0.0` which is not available on nuget and we don't want to reference prerelease packages in our production builds. Will this be released later? Or it has to be fixed/listed?

We know we can remove 3.11.0 analyzer, but then our internal validation tools fail because of prerelease package usage.

### To Reproduce
Use this csproj file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>3.0.0</Version>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.Extensions" Version="6.0.0" />
  </ItemGroup>

</Project>
```
### Error
```
NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.0.0 directly to project to resolve this issue.
Project -> Microsoft.AspNetCore.Mvc.Razor.Extensions 6.0.0 -> Microsoft.CodeAnalysis.Razor 6.0.0 -> Microsoft.CodeAnalysis.Common (>= 4.0.0) 
Project -> Microsoft.CodeAnalysis.CSharp 3.11.0 -> Microsoft.CodeAnalysis.Common (= 3.11.0).	
```
![image](https://user-images.githubusercontent.com/12775282/140955834-f8b11ed7-daf7-457b-bac9-ad956b259d7b.png)

**Comment by pranavkm** [comment]
Both of these packages are present on NuGet.org, they're just marked as unlisted:

* https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/4.0.0
* https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/4.0.0

It shouldn't affect restore though. If you remove the downgraded version, it should work.

FYI @JoeRobich

**Comment by Jupakabra** [comment]
Yes but 4.0.0 gives this :(
> This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore.

**Comment by JoeRobich** [comment]
We are validating our 4.0.1 packages for publishing. I expect they will be published today or tomorrow depending on if there are issues. cc: @davidwengier

**Comment by davidwengier** [comment]
4.0.1 packages have now been published to nuget

**Comment by Jupakabra** [comment]
Thanks. 👍
