### ISSUE TITLE
Virtualize component - Adding Span<T> support

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#38216]
I have a scenario where I am working with a lot of Data.
So I am using a Span<T> instead of T[].
But when I pass it to the Virtualization component.
I get Argument cannot convert from Span<T> to ICollection<T>.
Is there a way to Virtualize a Span<T> ?
Because in my scenario T[] is expansive in my case.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we'll be able to support because Span<T> is a ref struct and it can't be hold indefinitely in-memory as is the case with an ICollection type.

**Comment by mkArtakMSFT** [comment]
However, you can utilize the ItemProvider property of the Virtualize component and populate it using your own data source.
