### ISSUE TITLE
Upgrading app to .Net 6 Shows multiple app errors under browser console

### ISSUE THREAD

**Issue by arman-g** [dotnet/aspnetcore#38215]
### Describe the bug
I just upgraded my ASP.Net Angular application to use .Net 6 and now I see multiple errors under the browser console (see below image). It seems .Net 6 by default uses Application Insights and sends telemetry to **https://dc.services.visualstudio.com/v2/track** which fails with  **accessing a cross-origin** and eventually entire call chain fails.
For some reason it adds **AI-sentBuffer** and **AI_buffer** under application session also. I am not sure why it was made to have this as a default behavior in .Net 6.

If I switch back to .Net 5 this hole thing goes away except having AI-sentBuffer & AI_Buffer under the application session. I think this is happening because of the new VS2022 default wired setting. This hole experience with .Net 6 and VS 2022 is so disappointing. How can we shot sending application insights telemetry down? 

### Exceptions (if any)
![IMG1](https://user-images.githubusercontent.com/22778273/140965153-483e00be-2b1f-4411-bc12-e0c4fc506531.png)

### Further technical details
- ASP.NET Core version: 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022

**Comment by Xyncgas** [comment]
in my experience, create a new project in .NET 6, then copy your code line by line.
because it seems in .NET 6 projects are a little bit different, if you just simply target a .NET 5 project to .NET 6 it's not going to work at least in my case

**Comment by javiercn** [comment]
@arman-g thanks for contacting us.

It's not clear to us where the error is coming from since we are not able to see the entire call stack from the browser. It might be that Visual Studio is injecting some script on to the page for debugging purposes or that you have some customization on your app for app insights?

If that's not the case, let us know.

In addition to what I mentioned, we dramatically changed the approach to developing SPAs in .NET 6.0, so that might be something you want to check out.

**Comment by arman-g** [comment]
Hi @javiercn, I switched the web app project back to use .Net 6 with VS 2022 and run the application from command-line (see the image below). I don't see any browser console errors. I even don't see **AI-sentBuffer** and **AI_buffer** enteries under browser sessionStorage or cookies.
I haven't changed anything how the application configured, it still uses .Net 5 way with program and startup class. My understanding is that .Net 6 will support the Startup class as well so I don't see any breaking changes between .Net 5 and .Net 6.

I think the issue I am having is related to VS 2022. For some reason it is configured to send application insights telemetry to https://dc.services.visualstudio.com/v2/track which on its turn throws exception due to cross-origin request.

![IMG2](https://user-images.githubusercontent.com/22778273/141191733-0e7a0120-89b7-46a1-a83c-fc7a8d22e123.png)

**Comment by javiercn** [comment]
@arman-g I suggest you report the issue through the Visual Studio report a problem dialog.

@vijayrkn can you route this issue?

**Comment by mkArtakMSFT** [comment]
Ping @vijayrkn

**Comment by mkArtakMSFT** [comment]
Hi @arman-g.
As @javiercn has pointed out, the behavior you're observing is controlled by Visual Studio.
Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by arman-g** [comment]
Already [done](https://developercommunity.visualstudio.com/t/vs-2022-problem-with-countless-calls-to-dcservices/1584356) thank you.
