### ISSUE TITLE
runtime cannot find System.Security.Cryptography.Pkcs 

### ISSUE THREAD

**Issue by frankashley** [dotnet/aspnetcore#38227]
runtime compiled razor app .net 6 asp.net InvalidOperationException: Cannot find compilation library location for package 'System.Security.Cryptography.Pkcs'

### To Reproduce
create a runtime compiled .net 6 asp.net razor app
Out of Process Console Application

this means in Program.cs:
builder.Services.AddRazorPages().AddRazorRuntimeCompilation();

web.config
environmentVariable name="ASPNETCORE_HOSTINGSTARTUPASSEMBLIES" value="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"

and NuGet packages
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
Microsoft.VisualStudio.Web.CodeGeneration.Design
both version 6.

### Exceptions (if any)
InvalidOperationException: Cannot find compilation library location for package 'System.Security.Cryptography.Pkcs'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies)

### Further technical details
if System.Security.Cryptography.Pkcs.dll is placed in bin, there is no problem. Cannot find any way to get that file there other than copy paste. Have tried using the NuGet for that without success.

- ASP.NET Core version: 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Windows Visual Studio 2022
- Include the output of `dotnet --info`:
 .NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
6.0.100 [C:\Program Files\dotnet\sdk]
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by frankashley** [comment]
this worked in .net 5 so i am suspecting its in the NuGet for Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation v6

**Comment by xantari** [comment]
@frankashley This is exactly what I ran into as well. You gotta make sure Microsoft.VisualStudio.Web.CodeGeneration.Design is updated to V6. For whatever reason that one project reference wasn't updated to V6 along with all the other nuget packages and was causing this issue.
