### ISSUE TITLE
After Updating to Visual Studio 2022 Current from Visual Studio 2022 Preview, Blazor project display error when debuggin

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38229]
it seems I can still debug it.
here's the error 
![image](https://user-images.githubusercontent.com/35312807/141000553-6db1230e-bf7a-4f5b-b18f-f895c054f00f.png)

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

I believe there's an issue where the VS installer will setup the path for the 32 bit version of dotnet before the path for the 64 bit version and that can cause this issue to happen.

Check the PATH environment variable on your machine and make sure that `C:\Program Files\dotnet` appears earlier in the path than `C:\Program Files (x86)\dotnet`

/cc: @adityamandaleeka @HaoK

**Comment by Xyncgas** [comment]
it works, thanks
