### ISSUE TITLE
Razor Source Generator question/follow-up regarding comment in .NET Conf session.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/aspnetcore#38238]
I saw that razor generation is now being handled using a C# source generator; however, when looking at a default ASP.NET Core Web App and diving down into the Dependencies/Analyzers in the Solution Explorer I'm finding the section for Microsoft.NET.Sdk.Razor.SourceGenerators but it shows "This generator is not generating files.".  The default project template only contains .cshtml files; so not sure if this is because there aren't any .razor files or if I'm not understanding completely what it "means" to state that razor is now utilizing the C# Source Generators feature.  Or is there some mechanism in place to "prevent" seeing the file(s) generated in a Source Generator.. if so, why would this be?

Thanks in advance.

**Comment by pranavkm** [comment]
Thanks for your question @DualBrain. The empty node is a bug with a fix that is fairly involved and might take us work in the 7.0 milestone to address. In the meantime, if you configure the `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` as an  msbuild property in your project file, you can see the generated output in the project's obj directory.

### More details:
Razor tooling (the stuff that is used to give you completion and syntax highlighting for Razor files) generates what is called a design time code for the Razor file that isn't runnable, and is only meant to support tooling. Until 6.0, the IDE produced these files and add them to the VS workspace, MSBuild / csc produced the runtime code that participated in compilation and the two did not interfere with each other. 

Starting in 6.0, to make hot reload work, we had to start inserting the runtime code in to VS's workspace. There's some very fun workaround that goes about replacing the design time version with the runtime copy, which leaves solution explorer entirely confused leading to the "The generator is not generating files" message. The `EmitCompilerGeneratedFiles` tells the compiler to dump it's output to disk, so you can use that to peruse what gets generated.  https://github.com/dotnet/aspnetcore/issues/35395 is the issue tracking trying to clean up the workaround in 7.0.

**Comment by Xyncgas** [comment]
nice cat

**Comment by DualBrain** [comment]
Following these instructions, I'm certainly able to access the generated files in the /obj/ folder.  

With that cleared up, did I misunderstand the comment in the presentation regarding the source generation for .razor and/or .cshtml is now completely switched over to C# Source Generators?  If it is, why the bug (I'm now interested so I can avoid whatever this may be when I create solutions around Source Generators)?  Or is this some sort of hybrid/mode?  Or incomplete?  Or completely off-base that we can chalk up to language collision / product naming confusion?

**Comment by pranavkm** [comment]
> I ask these questions as I'm under the impression that C# Source Generators are simply visible, by default, in the Solution Explorer under Dependencies/Analyzers. 

Definitely true of all other source generators. Razor just happens to be unique because it has some legacy design limitations around how it supports it's tooling. If you look at the logging or System.Text.Json's source generator, both of which are shipped in box, you'll notice they have no trouble showing generated content in Solution Explorer.
