### ISSUE TITLE
Error when publishing Blazor Hosted Project with a custom web.config

### ISSUE THREAD

**Issue by mrunks** [dotnet/aspnetcore#38239]
Describe the bug

If I try to publish a blazor hosted project that was previously created in Visual Studio 2019 and has a custom web config, Visual studio 2019 and Visual Studio 2022 will fail telling indicating it has 2 files with the same name.

Error says:
Found multiple publish output files with the same relative path: 

C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\BlazorWasm.web.config

C:\TFS\EnvSystems\Research\Development\Rads.Web\Server\web.config.

I have three Blazor WebAssembly projects and since installing Visual Studio 2022 I am not longer able to publish any of them either using Visual Studio 2019 or Visual Studio 2022.   I still receive the same error.

The Details of Visual Studio 2019 are as follows:
Microsoft Visual Studio Enterprise 2019
Version 16.11.6
VisualStudio.16.Release/16.11.6+31829.152
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.94.52318

I believe this is the same issue as Issue #35031. 

https://github.com/dotnet/aspnetcore/issues/35031

I am still targeting the .NET5 framework. I have changed nothing in any of the projects which fail to publish.

**Comment by javiercn** [comment]
@mrunks thanks for contacting us.

The fixes on the referenced issues only apply when you target .NET 6.0, could you update to .NET 6.0 and give it a try?

**Comment by mrunks** [comment]
Hi @javiercn when you refer to updating to .NET 6 do you mean use Visual Studio 2022 ?  When I open VS 2019 and tried to change the version to .NET 6 there is no option.  .NET 5 is the highest version.  I have the latest updates for VS 2019.

**Comment by javiercn** [comment]
@mrunks I meant updating your project to target .NET 6.0. You need to use VS 2022 to use .NET 6.0 from Visual Studio. If you can't do that, you should be able to at least change it on the project and publish from the command-line.

**Comment by javiercn** [comment]
@mrunks the fix that we did was specific to .NET 6.0

**Comment by mrunks** [comment]
So if both versions installed then I will need to upgrade each WebAssembly App to .NET6 and use Visual Studio 2022.  From what I can tell this only happens with WebAssembly applications.

**Comment by javiercn** [comment]
@mrunks that is correct.

**Comment by HugCoder** [comment]
Wait, what, if I got a .NET5 Blazor WASM project, developed in VS2019, but I installed VS2022 and thus also the .NET6 SDK, the .NET5 Blazor project will no longer publish if there's a custom web.config?

I'm currently experiencing similar issues where even if I target .net5 I keep getting mixed references to .net6 in Nuget packages, and publish keeps failing at later stages, but this seems really weird if this is the cause.
