### ISSUE TITLE
VS2022 RC3 Blazor compiling files that have been excluded from the project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38234]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-RC3-Blazor-compiling-files-that-h/1564528)._

---
I have a number of razor pages in the project that have been excluded from the project, even though the files exist.
The only way to see them in the Solution explorer is by using the option to show all, and they show as hidden.

However, building the application builds those files as well, even if they are excluded.
You can see in the image below how I get errors in the excluded files. Those files should not be built. 
I want to have them there because I'm doing some refactoring and slowly adding them to the solution and fixing them one at the time.

! [image.png] (https://aka.ms/dc/image?name=B72a2c9594ac14383ac923e2c134e4fb5637709021656654093_20211027-142925-image.png&tid=72a2c9594ac14383ac923e2c134e4fb5637709021656654093)

---
#### Feedback Bot on 10/26/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/9/2021, 00:55 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Could you share the contents of the project file which excludes these files? My guess is that the way the files have been excluded isn't correct and doesn't result in the files from being excluded from the `Content` item group which is what the Razor compiler uses to determine what files to process.

**Comment by Xyncgas** [comment]
yeah the IDE usually isn't very interactice with these errors it's just doing jobs it's supposed to do, that's not to say there is anything wrong with the user even still it sometimes just happens as you are developing an applications you run into these cases then from there you learn more about how everything works and what it takes to fix the problem, then as you build a mental map of what things are required to do a certain job, the experience turns into problem solving skills, at that point I just wanna say "damn I wish the IDE could just tell me what's not working" as you start to think for yourself you start to think for the rest of the humanity and their futures
