### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#38240]
xamarin.android    
Microsoft.AspNetCore.SignalR.Client  5.0.12

![image](https://user-images.githubusercontent.com/26525599/141042549-c520f626-54aa-490e-8959-89a3356052f7.png)

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/mono/mono/issues/20805#issuecomment-791440473
