### ISSUE TITLE
Please implement `IJSUnmarshalledRuntime` for `WebViewJSRuntime`

### ISSUE THREAD

**Issue by JinShil** [dotnet/aspnetcore#38242]
### Is your feature request related to a problem? Please describe.

I have a JS Interop library that relies on the `IJSUnmarshlledRuntime` interface for performance reasons.  I'd like to utilize that library in a Blazor desktop WebView application, but I currently can't because `WebViewJSRuntime` does not implement the `IJSUnmarshalledRuntime` interface. 

### Describe the solution you'd like

I would like to be able to utilize a high-performance JS Interop library that relies on the `IJSUnmarshalledRuntime` in a Blazor desktop WebView (WPF and WinForms) application.

**Comment by TanayParikh** [comment]
Thanks @JinShil for reporting. @Eilon should we dup this with https://github.com/dotnet/aspnetcore/issues/37647?

**Comment by javiercn** [comment]
@JinShil It's not feasible, as IJSUnmarshlledRuntime is only available with interprocess communication (webassembly) and that's not something available in Blazor Desktop as the webview runs in its own process.
