### ISSUE TITLE
Model binder does not bind properties with private setter

### ISSUE THREAD

**Issue by maelmahdy86** [dotnet/aspnetcore#38243]
Hi,

I've a API project built with .NET 6, the models are immutable (POCO classes with private setter properties)

When I call the API from postman and pass the model values; these properties are not bound and their values are still null

Let's say this is the model/command class:

```
    public class CreateUserCommand : ICreateCommand<bool>
    {
        public string Name { get; private set; }
    }
```

and this is the action method:

```
    [HttpPost]
    public async Task<ActionResult> Post(CreateUserCommand command)
    {
         // do work
        return Ok();
    }
```

AFAIK, model binder should work with private setters as well but it doesn't so I need to know if I'm missing something here

**Comment by pranavkm** [comment]
> AFAIK, model binder should work with private setters as well

It does not. It treats non-public setters as read-only properties. There are some exceptions around collection properties with non-public setters, but in general, you want them to be public. 

> the models are immutable

Have you considered using a record type? MVC will model bind constructors for record types.
