### ISSUE TITLE
Microsoft.AspNetCore.Connections.Abstractions Version=6.0.0.0 brakes on dependency injection with .Net 5.0

### ISSUE THREAD

**Issue by ASP-WAF** [dotnet/aspnetcore#38246]
I have noted that updating nuget package Microsoft.AspNetCore.Connections.Abstractions to the latest version brakes website running in .Net 5.0. with SDK 5.0.403 when using the nuget package on gets the following exception when the site loads:

`System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Connections.Experimental.IMultiplexedConnectionListenerFactory' from assembly 'Microsoft.AspNetCore.Connections.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

My workaround is to skip the latest NuGet package by conditionally linking my NuGet Package that supports both.net 5.0 and .net 6.0:
```
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="6.0.0" Condition="'$(TargetFramework)'=='net6.0'" />
		<PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="5.0.12" Condition="'$(TargetFramework)'!='net6.0'" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.RazorPages" Version="2.2.5" />
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="6.0.0" />
	</ItemGroup>
```

I guess any user using my package in his application can update his consumed packages and override my hack running in the same issue so I am eager to figure out the correct way/package I need to resolve the issue.

Here is my stack:
[Stack.txt](https://github.com/dotnet/aspnetcore/files/7510757/Stack.txt)

**Comment by davidfowl** [comment]
Why are you referencing these combination of packages? The versions look out of wack. What's the intent here?

**Comment by ASP-WAF** [comment]
I am using IMultiplexedConnectionListenerFactory in my code, it will not work when using the new 6.0 version in .net 5, it does in .net 6

**Comment by davidfowl** [comment]
Can you show the entire project file and what code you're writing? That type did change completely in .NET 6 so you can't cross the streams with what versions you're using.

**Comment by Bellarmine-Head** [comment]
I wonder if NuGet offered you a 6.0.0 package update with a .NET 6.0 dependency for a .NET 5.0 project, like I was for `Microsoft.AspNetCore.Components.WebAssembly`: https://github.com/dotnet/aspnetcore/issues/38256

I was suspicious of this and _didn't update_.

**Comment by adityamandaleeka** [comment]
@ASP-WAF Please share your project file so we can help with this.

**Comment by halter73** [comment]
> I am using IMultiplexedConnectionListenerFactory in my code, it will not work when using the new 6.0 version in .net 5, it does in .net 6

I think you're going to have to conditionally compile for net5.0 and net6.0 because `IMultiplexedConnectionListenerFactory` moved from  the `Microsoft.AspNetCore.Connections.Experimental` to the `Microsoft.AspNetCore.Connections` namespace.
