### ISSUE TITLE
Code used in .NetConf Day 1

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#38253]
Hello,

@javiercn and @danroth27 presented on .NetConf Day 1 the Microsoft.AspNetCore.ClientAssets experimental library. Is the code used in the demo available anywhere?

Thanks

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

You can find the code [here](https://github.com/javiercn/DotNetConfDemos)
