### ISSUE TITLE
Add support for CSS isolation in MVC tag helpers

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#38265]
### Describe the solution you'd like
I'd like to be able to use CSS isolation with tag helpers e.g. the `<input>` tag.

**Comment by javiercn** [comment]
@BrunoBlanes thanks for contacting us.

I'm going to mark this as a dupe of https://github.com/dotnet/aspnetcore/issues/30213 since this is the approach that we would take. Please feel free to upvote that issue instead.

**Comment by BrunoBlanes** [comment]
But that's for Blazor, what about MVC?

**Comment by javiercn** [comment]
@BrunoBlanes we'll do it for both, we didn't have CSS isolation support for MVC when we filed the issue.

**Comment by BrunoBlanes** [comment]
Lovely, thanks!
