### ISSUE TITLE
Regression in AddDataProtection from RC2

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/aspnetcore#38274]
I have a working app in ASP.NET Core 6 RC2. It stores data protection keys in Azure Blob Storage, and protects them with Key Vault:

```
builder.Services.AddDataProtection()
  .PersistKeysToAzureBlobStorage(new Uri(config["DataProtectionBlobUri"]))
  .ProtectKeysWithAzureKeyVault(
    new Uri(config["DataProtectionKey"]),
    new ClientSecretCredential(config["MicrosoftTenantId"], config["MicrosoftClientId"], config["MicrosoftClientSecret"])
  );
```

In the Dockerfile, if I change these lines:
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0.0-rc.2 AS base
...
FROM mcr.microsoft.com/dotnet/sdk:6.0.100-rc.2 AS build
```
to
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
...
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
```

Then the app still runs, but all existing cookies and encrypted strings are rejected. Reverting to RC2 makes everything work again.

An example error message is, when trying to decrypt a string: `The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning`

The package versions are:
* Azure.Extensions.AspNetCore.DataProtection.Blobs v1.2.1
* Azure.Extensions.AspNetCore.DataProtection.Keys v1.1.0
* Azure.Storage.Blobs v12.10.0

**Comment by Tratcher** [comment]
Can you show how `config` is created in this example? Or show the whole Program.cs for completness?

**Comment by jamesgurung** [comment]
Sorry, I should have said:

```
var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;
```

I can see that it's returning the right configuration values.

**Comment by adityamandaleeka** [comment]
This is unexpected since I don't think we did anything in this area after RC2. @HaoK can you please try to repro this?

**Comment by jamesgurung** [comment]
I have created a minimum repro: [github.com/jamesgurung/DataProtectionDemo](https://github.com/jamesgurung/DataProtectionDemo)

This is deployed with GitHub Actions to three Azure web apps (all with identical configuration):
* [.NET 6 RTM deployment](https://dpdemo60.azurewebsites.net/)
* [.NET 6 RC2 deployment](https://dpdemo60rc2.azurewebsites.net/)
* [Another .NET 6 RC2 deployment](https://dpdemo60rc2other.azurewebsites.net/)

Web endpoints:
* `/` returns an encrypted string
* `/{encryptedText}` will attempt to decrypt an encrypted string

Each deployment can decrypt its own messages, and the two RC2 deployments can decrypt each others' messages as expected. However, .NET 6 RTM cannot decrypt messages created by .NET 6 RC2 (and vice versa).

Points to note:
* The problem occurs even without `ProtectKeysWithAzureKeyVault` so this is not included.
* If I modify the `keys.xml` file, the error now says `CryptographicException: The key {xxx} was not found in the key ring`. This suggests that it is correctly reading the key file from Azure Blob Storage. It's just that once it has the key, it's not able to use it to decrypt payloads created with the other .NET version.
* By stepping through the source, it looks like the error is coming from the method `ManagedAuthenticatedEncryptor.Decrypt`, in "Step 4: Validate the MAC provided as part of the payload."

**Comment by HaoK** [comment]
Hey @jamesgurung thanks for the detailed repro and I'll start investigating to see what's going on.  Have you tried .PersistKeysToFileSystem and used the same key directory in your apps as well?  It'd be helpful to remove Azure from the potential causes

**Comment by HaoK** [comment]
So I can repro this without azure, there definitely are two different payloads generated rc2 vs rtm:

```
rc2: CfDJ8GlGR3YnSRpCpl391nz7WgU99vpdLMj5Wbfb0ZTWJV1GUIuh7mOyqy9BpgF5YXSFVe4cd8WVarOe4Kn3ZNd4GgnHDJw4rU_USMuveJ_0kdGEb32HQi6SY90W5toj2p8s6Q
rtm: CfDJ8GlGR3YnSRpCpl391nz7WgVYb4CMMop4KqNvRC-pVj-38nBAuxPRxRg1Sd4-PEkf6yXxxMrhoq07wYKzqWtTDNZ3Lxvw3MsKtJyhKl904ktOlHsBsWRTSWxmcXDSSV4dtg
```

**Comment by HaoK** [comment]
Okay I think the behavior is expected due to some changes in rtm on how the content root is calcluated, dataprotection uses that to compute the application name: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname

So if you need rc2/rtm to be compatible you will need to specify the `.SetApplicationName("shared app name")`

This looks to be a side effect of https://github.com/dotnet/aspnetcore/commit/366a6180e0b226c5020d638abd81d860a0b4dddb#diff-ba481cde89becdcb3c4495e617a4071a9ee9a3fba3746ab63a452c86fd945c15 

@jamesgurung can you confirm that setting fixes things for you as well?

**Comment by brockallen** [comment]
And so any old DP keys won't work unless the v6 version sets the app name to the old content root calculated name? IOW, is this a breaking change for a live update (e.g. data protected auth cookies) from pre-v6 to v6?

**Comment by HaoK** [comment]
It'd only be affecting anything using the new DefaultBuilder/minimal API, so it wouldn't affect any pre v6 apps

**Comment by brockallen** [comment]
Ah, so it's only doing this different content root calculation with the new minimal API? Got it. ty!

**Comment by jamesgurung** [comment]
@HaoK Thank you so much for looking into this.

What string should I use with `SetApplicationName` to keep backwards-compatibility with .NET 6 RC2? I already have an RC2 app running in production (which doesn't manually specify an application name on `AddDataProtection`), and I don't want to lose the cookies and encrypted tokens that are already in use. Is it just the project name?

**Comment by Tratcher** [comment]
@HaoK can you give examples of the content-root and app name for 5.0 vs 6.0? Any regression between those should be addressed, even if it's only in the new minimal host.

**Comment by HaoK** [comment]
I can't speak to 5.0 vs 6.0, I am only looking at rc2 vs 6.0 after the minimal change which affected dataprotection for the same app.   I'll see if I can print out what the input differences are that cause the auto logic to generate different results now

**Comment by HaoK** [comment]
@jamesgurung I'll have to take a look to see if there's a way you can do that, I believe setting the application name turns off some of the default inference logic, so I'm not sure there's an easy way to do what you want

**Comment by HaoK** [comment]
Looks like the difference is with a trailing slash:

6.0
```
Running .NET 6.0.0-rtm.21522.10
ContentRoot: C:\Test\dp\
```

rc2
```
Running .NET 6.0.0-rc.2.21468.3
ContentRoot: C:\test\dp
```

**Comment by HaoK** [comment]
@jamesgurung so maybe you can try setting the content path in 6.0 rtm to trim out the trailing slash (and maybe match casing too in case that matters)

**Comment by jamesgurung** [comment]
@HaoK Using `SetApplicationName` works, so this is definitely the source of the problem. However, in my case I can't do that for backward compatibility, and normalising the content root path does not seem to work. Am I doing it right?

I've added to [Program.cs](https://github.com/jamesgurung/DataProtectionDemo/blob/master/Program.cs):

```
builder.Environment.ContentRootPath =
  builder.Environment.ContentRootPath.TrimEnd('/');
```

And here are the deployed demo apps:
* https://dpdemo60.azurewebsites.net
* https://dpdemo60rc2.azurewebsites.net

**Comment by jamesgurung** [comment]
Ok, I've got it working! Thank you for all your help.

```c#
var builder = WebApplication.CreateBuilder(args);

var dpBuilder = builder.Services.AddDataProtection()
  .PersistKeysToAzureBlobStorage(new Uri(builder.Configuration["DataProtectionBlobUri"]));

// In .NET 6 RTM, manually set the Application Name to the RC2 default for backwards compatibility
if (RuntimeInformation.FrameworkDescription.Contains("rtm")) {
  var legacyContentRootPath = builder.Environment.ContentRootPath.TrimEnd('/');
  dpBuilder.SetApplicationName(legacyContentRootPath);
}
```

**Comment by brockallen** [comment]
So this does raise a good point about the "environmental" (for lack of a better word) about the two different styles of Setup. They produce different values, and thus with the default DP config they are incompatible. This is a very important distinction to at least document, and in general really means the docs should reinforce that setting an app name in DP is almost mandatory.

**Comment by Tratcher** [comment]
I'd argue that the 6.0 change should be reverted to preserve back-compat with 5.0.

**Comment by davidfowl** [comment]
Thou shall not use an unnormalized path for anything in the future 😄

**Comment by blowdart** [comment]
Trailing /s are normalization, they may or may not refer to a default document or a directory, because lol

**Comment by rafikiassumani-msft** [comment]
@halter73 will update the migration docs with the workaround provided in this discussion.

**Comment by myrup** [comment]
Crazy that this isn't a 6.0.x hotfix 😂 !?

**Comment by davidfowl** [comment]
The best part about making it a hotfix is that it'll break 6.0 applications 😄

**Comment by adityamandaleeka** [comment]
> @halter73 will update the migration docs with the workaround provided in this discussion.

Leaving this open for that ^
