### ISSUE TITLE
@microsoft/signalr V6.0.0 is not working on react-native apps

### ISSUE THREAD

**Issue by erez-unitronics** [dotnet/aspnetcore#38286]
I updated @microsoft/signalr library on my react native app (v0.66.2) to the new version (v6.0.0) and now i get this error:

"HubConnection failed to start successfully because of error 'ReferenceError: Can't find variable: document'."

**On previous version (v5.0.12) everything was working fine.**

is there a way to fix this on react-native?

**Comment by BrennanConroy** [comment]
Where is the error coming from? Everywhere in the SignalR library that we use `document` we first check if it's available, and there is only 1 new usage of `document` between 5.0 and 6.0

**Comment by erez-unitronics** [comment]
Hi @BrennanConroy 

The error is coming when I try to start the connection. 
This is part of the code:

**
        hubConnection = new HubConnectionBuilder()
            .withUrl(DOMAIN_URL + '/' + HUB_NAME, { transport: HttpTransportType.WebSockets })
            .withAutomaticReconnect()
            .configureLogging(LogLevel.Debug)
            .build();

        hubConnection.start()
            .then(() => {
                // Some code
            })
            .catch((error) => {
               // error => "Debug: HubConnection failed to start successfully because of error 'ReferenceError: Property 'document' doesn't exist'."
            });
**

Full log:
 LOG  [2021-11-12T13:52:18.901Z] Debug: The HttpConnection connected successfully.
 LOG  [2021-11-12T13:52:18.902Z] Debug: Sending handshake request.
 INFO  [2021-11-12T13:52:18.906Z] Information: Using HubProtocol 'json'.
 LOG  [2021-11-12T13:52:19.622Z] Debug: Server handshake complete.
 LOG  [2021-11-12T13:52:19.629Z] Debug: HubConnection failed to start successfully because of error 'ReferenceError: Property 'document' doesn't exist'.


**I didn't change anything here after the upgrade to 6.0 version

**Comment by BrennanConroy** [comment]
I see, I think we should be using `window.document` here https://github.com/dotnet/aspnetcore/blob/337b53cd379cf591f218fc8c085a6ae583c12018/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L183

**Comment by erez-unitronics** [comment]
Any updates for the current version?

**Comment by BrennanConroy** [comment]
You might be able to workaround this by adding:
```typescript
if (!globalThis.document) {
  (globalThis.document as any) = undefined;
}
```
to your project.

**Comment by erez-unitronics** [comment]
Thanks! works fine now

**Comment by BrennanConroy** [comment]
Keeping open for tracking fixing the issue.
