### ISSUE TITLE
Publish Blazor WebAssembly from Visual Studio with Web Deploy to Azure AppService results in lots of errors: Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by MarcelWolterbeek** [dotnet/aspnetcore#38289]
When I publish my (ASP.NET Core hosted) Blazor WebAssembly App from Visual Studio 2019 version 16.11.5 with Web Deploy to an Azure AppService everything works fine.

But publishing from Visual Studio 2019 version 16.11.6 or Visual Studio 2022 results in a lot of "Failed to find a valid digest in the 'integrity' attribute for resource" errors whe the App is started after publishing.

I looked at [Diagnosing integrity problems:](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#diagnosing-integrity-problems-1)
- All requests have a status 200
- Clearing the browser cache does not solve the problem.
- Adding `<BlazorCacheBootResources>false</BlazorCacheBootResources>` solves the problem, but that is not what I want of course.

I still have a machine with Visual Studio 2019 version 16.11.5 so for now I have a workaround, but I want to upgrade to VS 2022.

Publish settings:
- Target Framwork: net5.0
- Deployment mode: Self-contained
- Target Runtime: win-x86

Errors shown:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/Ical.Net.dll' with computed SHA-256 integrity 'wpsWxP2dI/M+eOsY6EUhR8y3xP79FEDqA74wvJcsXFo='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

blazor.webassembly.js?v=03:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at blazor.webassembly.js?v=03:1
    at blazor.webassembly.js?v=03:1
    at Object.throw (blazor.webassembly.js?v=03:1)
    at s (blazor.webassembly.js?v=03:1)
d.printErr @ blazor.webassembly.js?v=03:1

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/System.IO.Pipelines.dll' with computed SHA-256 integrity 'qZYTUS+ga7CydtH54fYPbehFCvx3B49I74G8dxreTog='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/Microsoft.Net.Http.Headers.dll' with computed SHA-256 integrity 'Wvp5b2xB1gZg9yya2UqQycv2STns92xStLKpmRv5Aww='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/Microsoft.JSInterop.dll' with computed SHA-256 integrity 'zUWQN3o4+SD4D3IrJA37DwEjqztNaqUAgCT8zBENjIE='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/Microsoft.JSInterop.WebAssembly.dll' with computed SHA-256 integrity 'hNl8iqfAyBbbi5beUQrD8YE0aIHK9OlEgG8nQ2sJXcQ='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/Newtonsoft.Json.dll' with computed SHA-256 integrity 'dynSyVRw634jYoxRfV3ogqFeCGZk7RFbdDmfT1x04F0='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

toproosterapi-manualbuild.azurewebsites.net/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://toproosterapi-manualbuild.azurewebsites.net/_framework/NodaTime.dll' with computed SHA-256 integrity 'jNbb5/TCGMJ5TVSsS1QNCnXeeX3yMZDyjI8yjTBWz4M='. The resource has been blocked.
toproosterapi-manualbuild.azurewebsites.net/:1 Unknown error occurred while trying to verify integrity.

**Comment by javiercn** [comment]
@MarcelWolterbeek thanks for contacting us.

We had a similar issue recently and it seems that there were some files being left behind on the deployment environment.

Checkout [this issue](https://github.com/dotnet/aspnetcore/issues/37861) and let us know if any of the solutions there fixes your issue.

**Comment by LoupaLoupa** [comment]
Definitely there is an issue with blazor.webassembly.js , I have a 404 when trying to execute a Blazor WASM app that was working in 3.1, ever since I passed it to .net 6. Been trying to pin it down

Request URL: http://localhost:6001/_framework/blazor.webassembly.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:6001
Referrer Policy: strict-origin-when-cross-origin

But it finds other file that are at the same place

Request URL: http://localhost:6001/_framework/aspnetcore-browser-refresh.js
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:6001
Referrer Policy: strict-origin-when-cross-origin

**Comment by mnbeer** [comment]
Same issue, but by I am publishing to IIS, not an Azure App Service. Installed VS 2022 yesterday. Can no longer publish .NET 5 Blazor hosted Web Assembly app. Files are 200/OK but Publishing via VS 2019 UI and dotnet cli both result in SHA-256 integrity errors. Looks like dotnet is calling the latest msbuild.  Failures publishing to local IIS and IIS on remote VM. Application runs fine locally via dotnet run or starting from within VS 2019.

**Comment by MarcelWolterbeek** [comment]
Removing the bin and obj folders from the Blazor and the Api project solved the problem.
Thanks @javiercn

**Comment by mnbeer** [comment]
Removing the bin and obj folders worked for me as well.

**Comment by nssidhu** [comment]
Removing the bin and obj folders worked for me as well.
