### ISSUE TITLE
Input elements not generating scope identifier from CSS isolation

### ISSUE THREAD

**Issue by Oyyou** [dotnet/aspnetcore#38299]
As the title suggests. I was just checking my app while it was running, and noticed the lack of scope identifiers on the input tags

I can see they are being generated in the compiled css but not when running. Is this a bug in my code, Blazor, or something else?

Form.razor:
![image](https://user-images.githubusercontent.com/2433994/141340639-784c6ab1-c7a9-4527-b4a4-74b0b74ef04c.png)

Form.razor.css
![image](https://user-images.githubusercontent.com/2433994/141341001-cee81517-5c4c-4da4-b9f2-a0356af6feed.png)

Form.razor.rz.scp.css
![image](https://user-images.githubusercontent.com/2433994/141341075-7a06e267-77bf-4dfe-83cd-e692ff899228.png)

Code on localhost:
![image](https://user-images.githubusercontent.com/2433994/141341202-db438bf3-d107-4f29-a7cb-c465055ed345.png)

**Comment by javiercn** [comment]
@Oyyou thanks for contacting us.

CSS Isolation applies to html elements on the file, not other components. You can use the `::deep` combinator to define a style based on a parent HTML element on the file.

We have an issue opened to allow components to opt-in on receiving the CSS scope for their parent components here.

https://github.com/dotnet/aspnetcore/issues/30213
