### ISSUE TITLE
Blazor:  File referenced in nuget .props file but the file itself is not in the nuget package

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#38294]
I created a Blazor control and built it as a NuGet package.

When I tried to add the control to my host project I got this error:

> Error	MSB4018	The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\sam\.nuget\packages\pkg\1.0.10-beta.1\staticwebassets\css\bootstrap-4.1.3-dist\css\.DS_Store'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

Upon investigating the NuGet pagkage I found that .DS_Store is indeed referenced in Microsoft.AspNetCore.StaticWebAssets.props:

	<StaticWebAsset Include="$(MSBuildThisFileDirectory)..\staticwebassets\css\bootstrap-4.1.3-dist\css\.DS_Store">
      <SourceType>Package</SourceType>
      <SourceId>pkg</SourceId>
      <ContentRoot>$(MSBuildThisFileDirectory)..\staticwebassets\</ContentRoot>
      <BasePath>_content/pkg</BasePath>
      <RelativePath>css\bootstrap-4.1.3-dist\css\.DS_Store</RelativePath>
    </StaticWebAsset>
	
	
However the file itself does not exist in the staticwebassets\css\bootstrap-4.1.3-dist\css folder.

The file does exist in wwwroot\css\bootstrapp-4.1.3-dist\css in source code.
   
The .nuget package was generated by Visual Studio 2019 build.  There are no build directives added or removed.

     <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="5.0.11" />

      <PropertyGroup>
          <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
          <GenerateMvcApplicationPartsAssemblyAttributes>true</GenerateMvcApplicationPartsAssemblyAttributes>
          <RazorCompileOnBuild>true</RazorCompileOnBuild>
          <IncludeRazorContentInPack>false</IncludeRazorContentInPack>
          <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
          <EnableDefaultRazorGenerateItems>true</EnableDefaultRazorGenerateItems>
        </PropertyGroup>

**Comment by javiercn** [comment]
@sam-wheat thanks for contacting us.

Can you provide a minimal repro project as a github repostory so that we can investigate?

What dotnet version are you using? (5.0.x)? (Based on the fact that you are running VS 2019)

**Comment by sam-wheat** [comment]
[Repo is here](https://github.com/leaderanalytics/LeaderPivot.Blazor)
I have deleted the file in an attempt to resolve the problem (you are welcome to add a file of the same name locally).
I don't consider the problem solved, BTW, I just need to get past this.

I am now facing another problem, perhaps related:

Error	MSB4018	The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\sam\.nuget\packages\leaderanalytics.leaderpivot.blazor\1.0.11-beta.1\staticwebassets\css\open-iconic\ICON-LICENSE' is denied.

I realize this may be a different issue I will write up a different ticket if necessary.
I am researching it as best I can - thus far I have deleted the .nuget cache on my local machine but no luck.

**Comment by sam-wheat** [comment]
[This is the repo I am trying to add the nuget to](https://github.com/leaderanalytics/Vyntix.Fred.Downloader/tree/main/Downloader.Blazor/Client)

The project I am adding the nuget to is Downloader.Blazor.Client (not Downloader.APIClient).
There are a couple of projects in this solution however for the purpose of the issue I am having this is very much a standard Blazor app.

**Comment by javiercn** [comment]
@sam-wheat thanks for the additional details.

We made significant changes in this area on .NET 6.0 could you update your app and library to .NET 6.0 and see if the problem is still there?

**Comment by javiercn** [comment]
WRT to C:\Users\sam.nuget\packages\leaderanalytics.leaderpivot.blazor\1.0.11-beta.1\staticwebassets\css\open-iconic\ICON-LICENSE, it's not clear what's going on, but we did fix an issue for this in 6.0 and we would ask for you to try out and see if you still have issues after upgrading to .NET 6.0

**Comment by sam-wheat** [comment]
@javiercn  thanks very much for looking into this.  I will try to build it in .net 6 this weekend.

**Comment by javiercn** [comment]
@sam-wheat thanks for giving it a try. Let us know once you do.

**Comment by sam-wheat** [comment]
This issue may be closed prematurely.  I have not had a chance to test the problem reported in VS2022 because I am blocked by [this issue](https://developercommunity.visualstudio.com/t/Blazor-Server-and-Css-Isolation-using-N/1540537?port=1025&fsid=c97fad61-1dcf-4643-a466-0c58b40ef2be&entry=myfeedback&ref=native&refTime=1637421903704&refUserId=40a7cec2-823f-4138-930a-e949506e91a7).
