### ISSUE TITLE
Configurable Reconnection Behavior

### ISSUE THREAD

**Issue by myrup** [dotnet/aspnetcore#38305]
### Describe the bug
After upgrading from asp.net core 3.1 to 6.0 Blazor is still working, but the browser can no longer locate `Blazor.defaultReconnectionHandler._reconnectCallback` .

We use this to implement browser refresh on reconnections.

### Exceptions (if any)
`TypeError: undefined is not an object (evaluating 'Blazor.defaultReconnectionHandler._reconnectCallback)`

### Further technical details
- ASP.NET Core version: 6.0
<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by TanayParikh** [comment]
Hello @myrup, thanks for contacting us.

`Blazor.defaultReconnectionHandler._reconnectCallback` is an undocumented internal API, and we do not recommend using it directly within your application code as its subject to change without notice. 

In this specific case, the reconnection logic was refactored as a part of https://github.com/dotnet/aspnetcore/pull/36126/files.

**Comment by myrup** [comment]
@TanayParikh What's the recommended way of making the browser reload on a reconnect then? When googling the problem the following pattern seems fairly reoccurring (now broken): 
```
Blazor.defaultReconnectionHandler._reconnectCallback = function (d) {
    document.location.reload();
}
```
We need something like this while waiting for https://github.com/dotnet/aspnetcore/issues/27576

**Comment by TanayParikh** [comment]
> When googling the problem the following pattern seems fairly reoccurring (now broken):

Thanks for pointing that out. I see the following resource that recommend that approach:
- https://www.syncfusion.com/faq/how-do-i-reconnect-blazor-server-side-automatically#:~:text=To%20reconnect%20the%20Blazor%20server%20automatically%20you%20need,%3D%20function%20%28d%29%20%7B%20document.location.reload%20%28%29%3B%20%7D%20%3C%2Fscript%3E

I don't believe we have an official way to reload on reconnect (someone can correct me if I'm wrong). If you absolutely need a workaround, you could try listening for when the `#components-reconnect-modal` [display changes](https://stackoverflow.com/questions/1397251/event-detect-when-css-property-changed-using-jquery) from [`none` to `block`](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#reflect-the-connection-state-in-the-ui-blazor-server). Note this is entirely unsupported / undocumented, and may or may not work, or may stop working abruptly. 

I'm leaving this issue open to consider supporting refreshing the page when the `Reload` button is shown in the reconnection UI.

**Comment by BrennanConroy** [comment]
Wouldn't https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#modify-the-reconnection-handler-blazor-server let you do this?

**Comment by TanayParikh** [comment]
> Wouldn't https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#modify-the-reconnection-handler-blazor-server let you do this?

Yep you're right, I believe that'd work as well. Nice catch!

**Comment by myrup** [comment]
@BrennanConroy Yeah, I also considered using that, but I gave up on it because I find the documentation lacking on how to create a `reconnectionHandler` without breaking normal reconnection behaviour.

Blazor stops automatically reconnecting (`reconnectionOptions` are ignored) when I specify a `reconnectionHandler`. I don't know the wirings of a default `onConnectionDown` and `onConnectionUp` , so I don't know how to overload them without breaking things. I simply wish to hook into reconnections while using default reconnection logic.

**Comment by myrup** [comment]
To whom it may concern I managed to hack this together with:
```
Blazor.start().then(() => {
    Blazor.defaultReconnectionHandler._reconnectionDisplay = {
        show: () => {},
        update: (d) => {},
        rejected: (d) => document.location.reload()
    };
});
```

But I'm still using the internal api because it's undocumented how to overload `reconnectionHandler` (@BrennanConroy)  without breaking things. 

My concerns echo the unresolved https://github.com/dotnet/aspnetcore/issues/29991 , so maybe it should be reopened?

**Comment by TanayParikh** [comment]
> I don't know the wirings of a default `onConnectionDown` and `onConnectionUp` , so I don't know how to overload them without breaking things.

The default wirings are here:

https://github.com/dotnet/aspnetcore/blob/f186d9c9814825d70245db608dbf335a04727f4b/src/Components/Web.JS/src/Platform/Circuits/DefaultReconnectionHandler.ts#L23-L40

And its set here:

https://github.com/dotnet/aspnetcore/blob/f186d9c9814825d70245db608dbf335a04727f4b/src/Components/Web.JS/src/Boot.Server.ts#L49-L51

**Comment by pcarnella** [comment]
> To whom it may concern I managed to hack this together with:
> 
> ```
> Blazor.start().then(() => {
>     Blazor.defaultReconnectionHandler._reconnectionDisplay = {
>         show: () => {},
>         update: (d) => {},
>         rejected: (d) => document.location.reload()
>     };
> });
> ```

This isn't working for me, F12 error: Blazor has already started.   I put the code in _layout:
...
<script src="_framework/blazor.server.js"></script>
    <script>
        Blazor.start().then(() => {
            Blazor.defaultReconnectionHandler._reconnectionDisplay = {
                show: () => {},
                update: (d) => {},
                rejected: (d) => document.location.reload()
            };
        });
    </script>
</body>
...

Any other ideas for forcing reload after publish/app pool recycle?

**Comment by TanayParikh** [comment]
For:

```
<script src="_framework/blazor.server.js"></script>
```

Add an autostart="false" attribute and value to the <script> tag for the Blazor script.

Please see https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0 for more details.

**Comment by kostya9** [comment]
The fix with setting a custom `_reconnectionDisplay` removes the nice modal informing the user about the reconnect. I hacked together a wrapper that leaves the modal intact and reloads the page if the server was rebooted and we can't recover:
```js
Blazor.start().then(() => {
        Object.defineProperty(Blazor.defaultReconnectionHandler, '_reconnectionDisplay', {
            get() {
                return this.__reconnectionDisplay;
            },
            set(value) {
                this.__reconnectionDisplay = {
                    show: () => value.show(),
                    update: (d) => value.update(d),
                    rejected: (d) => document.location.reload()
                }
            }
        });
    });
```

**Comment by aryehsilver** [comment]
I get an error when using any of these options:
`Uncaught TypeError: Cannot set properties of undefined (setting '_reconnectionDisplay')`

**Comment by TanayParikh** [comment]
I'll just reiterate @BrennanConroy's point above about the official recommended approach to achieve this behavior is documented here: https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#modify-the-reconnection-handler-blazor-server

`_reconnectionDisplay` is a framework internal undocumented API subject to change without notice, and we do not recommend taking that approach.

**Comment by aryehsilver** [comment]
@TanayParikh But I don't want to reconstruct the whole reconnection display! Why can't there be an official way to customise it without reconstructing it?
It is a very sought after feature so why can't you give an official way to reload the page when it can't connect to the server?
This should even be the default in every application. Why would an end user want anything else? If it can't connect the app is useless so what else would you want to do besides reload?

**Comment by myrup** [comment]
@aryehsilver @TanayParikh @BrennanConroy I agree the official way is borderline useless because of its complexity to implement. I suggest making something like _reconnectionDisplay officially supported.

**Comment by aryehsilver** [comment]
> I suggest making something like _reconnectionDisplay officially supported.

@myrup That will never happen, it would be too useful!

**Comment by TanayParikh** [comment]
Re-opening to consider adding additional doc details on the reconnection behavior or provide alternate reconnection configurability.

**Comment by TanayParikh** [comment]
Thanks all for the discussion, I'm closing this issue out as a duplicate, and tracking progress here: https://github.com/dotnet/aspnetcore/issues/9256
