### ISSUE TITLE
<ProjectName>.GlobalUsings.g.cs not generate on `franken project`.

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/aspnetcore#38301]
C# 10 and enable ImplicitUsings, SDK-style proejct hash <ProjectName>.GlobalUsings.g.cs file, asp.net project no <ProjectName>.GlobalUsings.g.cs file.

This issure should in here?

**Comment by javiercn** [comment]
@pengweiqhca thanks for contacting us.

@pranavkm do you know about this?

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by pengweiqhca** [comment]
I think is Franken-proj not support `ImplicitUsings`, not only asp.net (not core) project.

[Demo](https://github.com/pengweiqhca/FrankenProjectGlobalUsings)

**Comment by pranavkm** [comment]
`ImplicitUsings` requires an SDK-style project. It's not supported in the non-sdk style project like the one you linked to.
