### ISSUE TITLE
Investigation: Impersonation issue for inprocess to access  app folder

### ISSUE THREAD

**Issue by pan-wang** [dotnet/aspnetcore#3830]
IIS allows user to specific user name and password to access the application folder. Worker process will impersonate the configured user when access files in the application folder. This impersonation is not a big issue for out process as user must grant worker process access permission to the application folder due to the fact of Kestrel child process. For in-process, we need verify, whether there is any issue for such scenario.

**Comment by jkotalik** [comment]
Closing as this is stale and no external customer reports.
