### ISSUE TITLE
error trying to run dotnet watch

### ISSUE THREAD

**Issue by piskovvx** [dotnet/aspnetcore#38303]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet watch command  threw this error:

Hmmm… can't reach this pageIt looks like the webpage at https://localhost:7246/ might be having issues, or it may have moved permanently to a new web address.
ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like the tutorial calls out to use `http` and not `https` endpoint, whereas you're trying to reach the webpage using `https`.
