### ISSUE TITLE
AspNet.Core.Components Version 6.0 Causes CRC Error 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38313]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/AspNetCoreComponents-Version-60-Cause/1579611)._

---
I am 3 days into upgrading all my projects to .Net 6.0, 42 more days to go probably, and I ran into a problem.

First Off, AspNet.Core.Components 6.0 not being able to reference a 5.0 project is frustrating (end rant), but I will describe the problem below:

Using a 3rd party component library (EPPPlus, 30 million downloads, so very popular) and in a WinForms environment on .Net 6.0 I am still able to use my open source library and open it / save it.

You can argue this is the 3rd party components problems, and maybe it is, but why would it open in .Net 5.0 in Blazor and in .Net 5.0 or .Net 6.0 in WinForms if it is the vendor's fault?

When trying to open in my Blazor project, the same file works in 5.0 (I just verified), and I get an error in 6.0:
crc error: the file being extracted appears to be corrupted. expected 0x6e626095, actual 0xb26ef2c7'.

The file isn't corrupted, I can open the file in Excel, or using my library in a WinForms .Net 5.0 or 6.0 project.

Your push to 64 bit was not worth it to me.

---
#### Feedback Bot on 11/10/2021, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. To confirm my understanding here, are you saying that opening a file using the [EPPlus](https://www.nuget.org/packages/EPPlus) library from within a Blazor WebAssembly application works correctly in .NET 5, but the same fails when run on .NET 6?
If so, please provide a minimalistic repro project (hosted as a public GitHub repository) that illustrates the problem. Note, that the project should contain only code showcasing the issue with no other depenendencies.
