### ISSUE TITLE
Problem with OpenId authentication on Blazor serverside.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38317]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-with-OpenId-authentication-on-Bl/1580569)._

---
See the following Program.cs, as soon as I add **app. UseAuthentication();** the normal routing stop working, I get a blank page but can still use url to reach pages. It works fine in older version than . NET6....

//
using CAD;
using CadCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System.Security.Claims;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder. Services.AddRazorPages();
builder. Services.AddServerSideBlazor();

builder. Services.AddAuthentication(options =>
{
    options. DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options. DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
}).
AddCookie(CookieAuthenticationDefaults.AuthenticationScheme).
AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    options. ResponseType = OpenIdConnectResponseType.Code;
    options. Authority = "https://localhost:5001/";
    options. ClientId = "cadserver";
    options. ClientSecret = "XXXXXXXX";
    options. SaveTokens = true;
    options. Scope.Add("openid");
    options. Scope.Add("profile");
    options. Scope.Add("email");
    options. Scope.Add("offline_access");
    options. Scope.Add("roles");
    options. Scope.Add("cadcore");
    options. SignedOutCallbackPath = "/";
    options. ClaimActions.MapJsonKey(ClaimTypes.Role, "role");
    options. GetClaimsFromUserInfoEndpoint = true;
    options. TokenValidationParameters.NameClaimType = "email";
    options. Events = new OpenIdConnectEvents
    {
        OnAccessDenied = context =>
        {
            context. HandleResponse();
            context. Response.Redirect("/");
            return Task.CompletedTask;
        }
    };
});

builder. Services.AddAuthorization();

builder. Services.AddHttpClient<ICadCoreData, CadCoreData>( client =>
{
    client. BaseAddress = new Uri("https://localhost:7011/api/cc/");
});
builder. Services.AddScoped<TokenProvider>();

var app = builder. Build();

// Configure the HTTP request pipeline.
if (!app. Environment.IsDevelopment())
{
    app. UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app. UseHsts();
}

app. UseHttpsRedirection();

app. UseStaticFiles();

app. UseRouting();

app. UseAuthentication();
app. UseAuthorization();

app. UseEndpoints(endpoints =>
{
    endpoints. MapRazorPages();
    endpoints. MapBlazorHub();
    endpoints. MapFallbackToPage("/_Host");
});

app. Run();
//

App.Razor
//
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (context. User.Identity?. IsAuthenticated != true)
                    {
                        <div>Not auth->re-direkt-></div>
                    }
                    else
                    {
                        <p role="alert">You are not authorized to access this resource.</p>
                    }
                </NotAuthorized>
            </AuthorizeRouteView>
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <PageTitle>Not found</PageTitle>
            <LayoutView Layout="@typeof(MainLayout)">
                <p role="alert">Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
//

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We would need a minimal repro project as a public github repo for us to make progress in this issue.
