### ISSUE TITLE
[question] Because Blazor is single threaded does that mean there is no way to get thread racing issues

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38316]

**Comment by Xyncgas** [comment]
if I have a bunch of async or parallel for adding 1 to int i, the final result would be as expected ?

**Comment by javiercn** [comment]
Thanks for contacting us @Xyncgas.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.
