### ISSUE TITLE
Incorrect completion in Razor when code block is missing closing curly brace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38315]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-completion-in-Razor-when-code-/1580149)._

---
Repro steps:

- Create a new Blazor Server project
- In Index.razor, add the following code at the end of the file (note the closing curly brace for the `@code` block is deliberately missing:

```
<ul>

</ul>

@code {
    IEnumerable<string> items = new string[] { "test1", "test2" };
```

- Inside the `ul` try to type `@foreach (var item in items) {}`

Expected result: Characters are added as typed

Actual result: When typing `items` it gets replaced with `ItemsProviderDelegate` once you type the closing paren:

! [hNhym4QSKj.gif] (https://aka.ms/dc/image?name=Be4c8402e5bcd4282995ee9ae600e55e9637722162455970395_20211111-003044-hNhym4QSKj.gif&tid=e4c8402e5bcd4282995ee9ae600e55e9637722162455970395)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen  has investigated this and said it's compiler issue (thanks @NTaylorMullen 👍 ):

> Because the foreach is incomplete it’s consuming the rest of the document instead of recovering in partial scenarios.
> Lol it thinks the IEnumerable etc. is markup:
> ![image](https://user-images.githubusercontent.com/34246760/141393704-64e51029-e479-4fa7-8591-d0a9f324f4c5.png)

**Comment by TanayParikh** [comment]
Looks like this is a dup of https://github.com/dotnet/aspnetcore/issues/27133?

**Comment by TanayParikh** [comment]
Closing as a duplicate of https://github.com/dotnet/aspnetcore/issues/27133.
