### ISSUE TITLE
Blazor Webassembly Razor Class Library CSS Isolation

### ISSUE THREAD

**Issue by vasquezjames** [dotnet/aspnetcore#38311]
### Describe the bug
I create a Razor Class Library named RCL01 this class library have the component named Cmp01.razor and this component have a css file Cmp01.razor.css (CSS Isolation).

Then I create a Blazor Webassembly App project named BlazorApp01 and I add a reference to the Library RCL01 and used in the Component Counter.razor. The CSS Isolation DON'T work.

Then I create a Razor Class Library project named RCL02 inside the same solution of the project BlazorApp01, this new Library have the component named Cmp02.razor  and this component have a css file Cmp02.razor.css (CSS Isolation).

In the project BlazorApp01 I add a project reference to the Project RCL02  and used in the Component Counter.razor. The CSS isolation WORKs!

Whats thats means the CSS isolation in Razor Class Library only work with Razor Class Libraries that are projects that are inside the solution of the main Blazor App project? not with a Razor Class Library compiled outside the main Blazor App project?

### To Reproduce
The code:

https://github.com/vasquezjames/RCL-CSSISOLA

### Further technical details
- ASP.NET Core version: .NET 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 17.0.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by javiercn** [comment]
@vasquezjames thanks for contacting us.

All projects need to be part of the solution and referenced by consumed projects for CSS isolation to work, since we compute a bundle with all the generated scoped css files.
