### ISSUE TITLE
VS2022 Release: Blazor component inheritance fails when defining base class in the partial class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38320]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Release:-Blazor-component-inherit/1579625)._

---
I have a number of pages and I like to keep all the code in the razor.cs file to separate UI and code behind.
However, if I want to change the base class for a page or a component in blazor, it has to be done in the .razor file using the @inherits.
If I move that inheritance to the code behind, I get an error. 
I should be able to keep all my logic in the code behind and not having to split part of the declaration in the UI part.
Additionally, it's quite a confusing error. It took me a while until I figured out the problem, as the message is based on the generated file and doesn't translate well to my code.

That is very confusing, because when I want to look at the code I can't see the base class. It should work either or.

Check the recording to see that when I move the base class from the razor file to the code behind, it fails.

---
#### Feedback Bot on 11/10/2021, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

This is not something that we currently support, since the compiler will add the base class to the generated code, you need to use `@inherits` to make sure the generated code is in sync with your code behind.
