### ISSUE TITLE
How to reference IFormFile in .net 6 library assembly (Migrating .net 3.1 to .net 6)

### ISSUE THREAD

**Issue by penfold** [dotnet/aspnetcore#38329]
I'm upgrading an Asp.net core solution to .net 6, looking to correctly reference IFormFile in non-AspNetCore assembly.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfile?view=aspnetcore-6.0

This API bound parameter is passed to a method on a class in a separate assembly (targeting .net 6). I can't seem to work out which Nuget package to reference. I've tried adding Microsoft.Extensions.Features but this doesn't seem to work. There is no helpful Alt-Enter intellisense suggestion that makes sense. 

IFormFile seems to be referenced correctly in the API Controller class.

I can't see any breaking changes or other guidance. What am I missing?

This package doesn't seem to have a .net 6 (non-preview) version: https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Features/6.0.0-preview.4.21253.5

Thanks,
Paul

**Comment by ArminShoeibi** [comment]
Please read this document:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio
delete any packages like Microsoft.Extensions.Features instead reference the framework.

**Comment by penfold** [comment]
Thanks - not sure how I missed this when we moved to 3.1.
