### ISSUE TITLE
Auto update or refresh the token in blazor to signalr?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38325]
There is no the feature that auto refresh the `access token`?

I add the dependency injection in program.cs
```
builder.Services.AddSingleton(sp => new HubConnectionBuilder()
.WithUrl("https://www.mysite.com/myhub", options => { options.AccessTokenProvider = () => Task.FromResult(App.Token); })
.Build());

```
if first the token is a null string.

then I get the token so I have to disconnect the hub and re-connect it?
just 
```
@inject HubConnection Connection;

Connection.StopAsync();
Connection.StartAsync();
```

or to re add the dependency injection?

**Comment by BrennanConroy** [comment]
> There is no the feature that auto refresh the `access token`?

Correct, the work is being tracked by https://github.com/dotnet/aspnetcore/issues/5297

> then I get the token so I have to disconnect the hub and re-connect it?

Yeah, that's probably the best option right now.

**Comment by mcguu** [comment]
@BrennanConroy  I added the code 
```
var accessToken = context.Request.Query["access_token"];

                   // If the request is for our hub...
                   var path = context.HttpContext.Request.Path;
                   if (!string.IsNullOrEmpty(accessToken) &&
                       (path.StartsWithSegments("/logcornerhub")))
                   {
                       // Read the token out of the query string
                       context.Token = accessToken;
                   }
```
and the accessToken has the token value and context.Token is set to the accesstoken.

but then in Context.User.Identity.IsAuthenticated is still false. why?

**Comment by adityamandaleeka** [comment]
I think @mcguu's question has been addressed elsewhere. Closing this issue.
