### ISSUE TITLE
Blazor WASM dev server Add Custom header for Cross origin Isolation

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#38327]
I need to add 2 headers in Blazor WASM dev server for local testing

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
These are required for `.wasm` file which uses `SharedArrayBuffer`.
In actual deployment i could add these 2 headers in server config i need to add them for local testing.

How can i add these 2 headers in Blazor WASM Dev server?

**Comment by Blackclaws** [comment]
What exactly are you trying to do here? Embedding/Requesting the Blazor App in a different page?

The problem you are running into here is that the WebAssemblyHost is a really limited subset of the standard host. I think your best bet is to check out how Blazor WASM prerendering works and use that host to configure CORS.

**Comment by sps014** [comment]
I am trying to use [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) in blazor wasm,
So ffmpeg.wasm internally uses `SharedArrayBuffer` which is used for multi threading on client. Currently to use `SharedArrayBuffer` what ever is server for Blazor wasm which serves static files need these 2 headers in some one fetches the `.wasm` file.

If i were to deploy static wasm site, on providers like netlify i would add these headers in toml file but for locally runninf i need these 2 headers

**Comment by javiercn** [comment]
@sps014 thanks for contacting us.

Is it not possible to add the headers as meta tags in Index.html? We don't have the ability to tweak the headers returned from the dev server. 

We would recommend you host the app in an ASP.NET Core for development purposes
