### ISSUE TITLE
Why are so many useless things generated? How to modify and delete them?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#38337]
And vs2022 has poor CSS prompts, such as bootstrap

asp.net core 6

![image](https://user-images.githubusercontent.com/26525599/141504276-b60037ea-4368-421d-8e40-303c5df8dfbf.png)

**Comment by javiercn** [comment]
@bbhxwl thanks for contacting us.

Those attributes are related to CSS isolation.

**Comment by bbhxwl** [comment]
@javiercn javiercn
https://github.com/dotnet/aspnetcore/issues/38348

**Comment by bbhxwl** [comment]
It hasn't been solved
