### ISSUE TITLE
System.text.json JsonSerializerOptions defaultbuffersize

### ISSUE THREAD

**Issue by candrewtemenoscom** [dotnet/aspnetcore#38343]
I am working on json streaming and would like to know how I should set the JsonSerializerOptions defaultbuffersize in the serialization or deserialization situation. Is there any guideline? I know the default is 16,384 bytes. What would happen if my json stream exceed this buffer? Thanks.

**Comment by pranavkm** [comment]
If you're looking to configure the JsonOptions used with MVC is what you'd wwant: https://docs.microsoft.com/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0#configure-systemtextjson-based-formatters. For minimal actions, here's what you would do: https://docs.microsoft.com/aspnet/core/web-api/route-to-code?view=aspnetcore-6.0#configure-json-serialization

If you're specifically asking about the `IAsyncEnumerable<>` support added in .NET 6, the streaming ignores the buffer size limit and writes directly to the underlying stream (in ASP.NET Core's case, the HTTP response stream). For all other data types, that's the size that is the maximum size buffered in memory before it flushes to the underlying stream. 

FYI @eiriktsarpalis
