### ISSUE TITLE
CSS isolation will not be closed. How can we really isolate?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#38348]
How can CSS isolation be truly isolated? The CSS referenced below will be merged. Even if page1 is accessed, the style of Page2 will be loaded. If there are many pages. Many unnecessary things will be loaded, or how to turn off CSS isolation so that it does not generate so many useless names

asp.net core 6
![image](https://user-images.githubusercontent.com/26525599/141599941-5391b3dd-1382-4247-816b-0b3750adb8f7.png)
![image](https://user-images.githubusercontent.com/26525599/141599959-463b3c55-789d-4c59-a347-146f4de955d9.png)
![image](https://user-images.githubusercontent.com/26525599/141599995-6eb132ea-c55b-423a-a903-fc3ceffc20db.png)

**Comment by javiercn** [comment]
@bbhxwl thanks for contacting us.

Is not truly clear what you are asking us. CSS isolation is about making sure that styles defined for a file don't conflict with other styles on the page. The mechanism used involves adding an attribute to the generated markup and automatically transforming CSS rules to only target elements with that attribute.

If you want a different type of isolation we suggest you look into leveraging Shadow DOM within your project, but that is not something we currently support.

**Comment by bbhxwl** [comment]
> @bbhxwl thanks for contacting us.
> 
> Is not truly clear what you are asking us. CSS isolation is about making sure that styles defined for a file don't conflict with other styles on the page. The mechanism used involves adding an attribute to the generated markup and automatically transforming CSS rules to only target elements with that attribute.
> 
> If you want a different type of isolation we suggest you look into leveraging Shadow DOM within your project, but that is not something we currently support.

I don't want my project to generate attributes, because I never use isolation. He will still add random attributes to all my tags, because I feel that adding this without isolation will add a lot of useless code to my page as a whole.

**Comment by javiercn** [comment]
@bbhxwl You can remove all `.razor.css` and `.cshtml.css` files from the template and they won't be used. In addition to that, you can explicitly disable CSS isolation from your project by setting `<ScopedCssEnabled>false</ScopedCssEnabled>`.

That said, bear in mind that you'll have to update the styles in your project and require additional changes to your project file when you are using a library that contains scoped CSS files.

**Comment by bbhxwl** [comment]
> @bbhxwl You can remove all `.razor.css` and `.cshtml.css` files from the template and they won't be used. In addition to that, you can explicitly disable CSS isolation from your project by setting `<ScopedCssEnabled>false</ScopedCssEnabled>`.
> 
> That said, bear in mind that you'll have to update the styles in your project and require additional changes to your project file when you are using a library that contains scoped CSS files.

I don’t have an extra .cshtml.css file, but it will generate it. I’ll go home and try the features you mentioned. The only thing I don’t understand now is that if I want to use css isolation, it’s similar to writing a .css file in wwwroot. Same, is it okay to let only one page refer to this css isolation? I think the css file under the view is more convenient to manage. Instead of loading all the css that are not needed on other pages, if there are 100 css, I only visit one page, he will also load 100 css, in order to open a page, access to 100 css, it is a bit expensive.

**Comment by bbhxwl** [comment]
Where should I add?

<ScopedCssEnabled>false</ScopedCssEnabled>
![image](https://user-images.githubusercontent.com/26525599/141801074-15ceb71a-307f-4274-8786-c31290923adc.png)

**Comment by javiercn** [comment]
@bbhxwl you add that within the `PropertyGroup`

**Comment by javiercn** [comment]
> I don’t have an extra .cshtml.css file, but it will generate it. I’ll go home and try the features you mentioned. The only thing I don’t understand now is that if I want to use css isolation, it’s similar to writing a .css file in wwwroot. Same, is it okay to let only one page refer to this css isolation? I think the css file under the view is more convenient to manage. Instead of loading all the css that are not needed on other pages, if there are 100 css, I only visit one page, he will also load 100 css, in order to open a page, access to 100 css, it is a bit expensive.

We only generate the attribute when we are able to match a css file to a razor file. By default we bundle all the scoped CSS files and import them. You get one bundle per project and the main bundle brings in all the bundles from referenced projects/packages.

If you are observing this behavior, please provide a minimal repro project as a public github repository so that we can make progress on the issue.

You can opt-in to disable bundling, and do your own bundling or import the generated scoped CSS files manually on each file.

That said, we recommend you use bundling and import all the CSS directly because its not going to have a significant performance impact on the application load time and is much easier to manage and maintain.

**Comment by bbhxwl** [comment]
> > I don’t have an extra .cshtml.css file, but it will generate it. I’ll go home and try the features you mentioned. The only thing I don’t understand now is that if I want to use css isolation, it’s similar to writing a .css file in wwwroot. Same, is it okay to let only one page refer to this css isolation? I think the css file under the view is more convenient to manage. Instead of loading all the css that are not needed on other pages, if there are 100 css, I only visit one page, he will also load 100 css, in order to open a page, access to 100 css, it is a bit expensive.
> 
> We only generate the attribute when we are able to match a css file to a razor file. By default we bundle all the scoped CSS files and import them. You get one bundle per project and the main bundle brings in all the bundles from referenced projects/packages.
> 
> If you are observing this behavior, please provide a minimal repro project as a public github repository so that we can make progress on the issue.
> 
> You can opt-in to disable bundling, and do your own bundling or import the generated scoped CSS files manually on each file.
> 
> That said, we recommend you use bundling and import all the CSS directly because its not going to have a significant performance impact on the application load time and is much easier to manage and maintain.
![image](https://user-images.githubusercontent.com/26525599/141811168-faa57373-2783-4d26-b700-60bfa4f78eee.png)

![image](https://user-images.githubusercontent.com/26525599/141811081-89c21a56-8460-4c56-a502-7592b5821185.png)
![image](https://user-images.githubusercontent.com/26525599/141811123-e97e36f5-b06e-46a9-8817-e5f6624dc3ec.png)

https://github.com/bbhxwl/TestCss

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/141811431-71559027-f938-4d71-870b-c5867e5014cf.png)

That is triggering the attributes to be generated for each file with an associated .razor.css or .cshtml.css file.

**Comment by bbhxwl** [comment]
> ![image](https://user-images.githubusercontent.com/6995051/141811431-71559027-f938-4d71-870b-c5867e5014cf.png)
> 
> That is triggering the attributes to be generated for each file with an associated .razor.css or .cshtml.css file.
I updated the project. This is the minimum version. If you want to reference only one style name, can you use namespace.view.style.css like this?
Not namespace.style.css

https://github.com/bbhxwl/TestCss


![image](https://user-images.githubusercontent.com/26525599/141873583-7db9d087-53c4-4c33-a3db-b61efc24751c.png)
![image](https://user-images.githubusercontent.com/26525599/141873633-b68c8cc1-c760-4f7a-b29f-25a9e31f298f.png)
