### ISSUE TITLE
PageTitle Not Working with .Net 6.0 Blazor wasm project migrated from .Net 5.0

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#38356]
### Describe the bug
I migrated my `net5.0` blazor wasm project to `.net6.0` and noticed that `<PageTitle>` doesn't seem to work. However `<PageTitle>` works with brand new `net6.0` blazor wasm project. Upon further investigation, I noticed from [migration docs](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#blazor) that for blazor project we are asked to create new `.net6.0` blazor wasm project and move components to that. But doing so I'll lose all my project history. Is there any possibilities to migrate without losing history?

### To Reproduce
1. Create a `.net5.0` blazor wasm project.
2. Migrate to `.net6.0`.
3. Add `<PageTitle>` component to any component and check.

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 Current 17.0 Enterprise Edition on Windows 11
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by pranavkm** [comment]
@guardrex could we rephrase the "Create a new 6.0 Blazor project from one of the Blazor project templates. For more information, see Tooling for ASP.NET Core Blazor." or possibly drop that statement entirely? Telling people to create a new app as part of the migration guideline seems very wrong.

@fingers10 have you followed the instructions from https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly to enable prerendering for the Blazor app? There are some very specific set of steps that need to followed. Could you verify you've done this?

**Comment by guardrex** [comment]
That was embraced by @danroth27 because we can't quickly explain out step-by-step how to adopt every feature and app change (i.e., file change) required given all of the churn, especially including things like the layout change that touched so many Blazor features ... and including the NRT deltas, too.

@danroth27 ... Do you want to reconsider it and do what we did for 5.0? ... but if you do pull the trigger on it, 😅 it's a 🐻 to pull off (based on my 5.0 experience doing it) and it's going to be **_costly_** 💰💰💰.

**Comment by pranavkm** [comment]
I don't think we need to document how to update your app to use every new feature, as long as they are covered as part of individual feature sections (which at least in the prerendering case it is).

**Comment by guardrex** [comment]
Yes ... they're cross-linked there in the migration remarks ... the link here ...

<img width="471" alt="Capture" src="https://user-images.githubusercontent.com/1622880/141859369-53facb4c-3561-4a20-beef-13edd784debe.PNG">

**Comment by guardrex** [comment]
It could remark that the individual features are adopted ad hoc but that if you want them all you'd go the new project route.

I'll open an issue for improved wording and work it first thing tomorrow morning.

**Comment by guardrex** [comment]
@fingers10 ... I'm going to also make an improvement in the morning for the `HeadOutlet` coverage to mention that it's also used by the `PageTitle` component to work properly. Right now, that section only mentions `HeadContent` explicitly. Mentioning this aspect of the `PageTitle` is only in the API doc today, but I'll call that out in the topic tomorrow morning along with these migration topic changes.

* https://docs.microsoft.com/aspnet/core/blazor/components/control-head-content#headoutlet-component
* https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.components.web.pagetitle

**Comment by fingers10** [comment]
@pranavkm I'm using blazor wasm app. Do I need to enable prerendering for `<PageTitle>` component to work?

**Comment by guardrex** [comment]
Improvements are going in on https://github.com/dotnet/AspNetCore.Docs/pull/23929.

**Comment by pranavkm** [comment]
Closing this since the doc work is also complete. Thanks @guardrex for updating the text.
