### ISSUE TITLE
Error after update node_modules in template ASP.NET CORE with React.js

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-after-update-node_modules-in-templ/1576663)._

---
[severity:It's more difficult to complete my work]
**Error:** [AuthorizeRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment> 

**Steps to Reproduce**
1. Open Visual studio
2. Create Project ASP.NET Core with React.js
3. Select in Authentication Type: individual accounts
4. Update packages to the latest version ClientApp\package.json
5. run npm install in package manager console
6. Run Project

Also authorization does not work. Problem in **App.js** -> ApplicationPaths.ApiAuthorizationPrefix

---
#### Feedback Bot on 11/9/2021, 10:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

There seem to be multiple issues here. What version of node.js are you using? We recommend using Node 16.x as its the current LTS version that we test things with. If you are using an older version you might need to recreate your package-lock.json.
