### ISSUE TITLE
VS2022 Release Blazor calling my OnParametersSetAsync 4 times on the same control

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38350]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Release-Blazor-calling-my-OnParam/1581319)._

---
In my application I've just noticed that Blazor is calling OnParametersSetAsync 4x on the same component 4x.

By the way, I only have 1 parameter in the class and this is how I initialise it.

![image.png](https://aka.ms/dc/image?name=B7524b2bc04d34e6aa541de38c8a88a1e637722875221446046_20211112-151841-image.png&tid=7524b2bc04d34e6aa541de38c8a88a1e637722875221446046)

I have recorded it tracking an identifier validate that it was indeed the same component.

---
#### Feedback Bot on 11/12/2021, 00:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

It is perfectly normal for SetParameters to be called more than once if a given parent component re-renders multiple times and Blazor is not able to detect that the parameters to that component have not changed. You can see more details [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)
