### ISSUE TITLE
Areas do not work in ASP.NET Core with Angular project

### ISSUE THREAD

**Issue by dushkostanoeski** [dotnet/aspnetcore#38354]
### Describe the bug
Making calls to controllers that have an area attribute returns 404

### To Reproduce
Create a new ASP.NET Core with Angular project, add an `Areas` folder and in it another `Weather` folder. Move the `Controllers` folder into the `Weather` folder.

Change the namespace of the `WeatherForecastController` class to `Project1.Areas.Weather.Controllers` and change the attributes to the following:
```
[ApiController]
[Route("[area]/[controller]")]
[Area("Weather")]
```
In `Program.cs` add the following line before the default route (I tried this with `UseEndpoints()` but got the same result):
```
app.MapControllerRoute("areas", "{areas:exist}/{controller}/{action=Index}/{id?}");
```
and at last add `weather/` to the url in the `http.get` call in the `fetch-data` angular controller.

Once you run the app, you get 404 when making the API call.

### Further technical details
- ASP.NET Core version: 6.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by dushkostanoeski** [comment]
Turns out it's not a bug, you have to list all the Areas in the `PROXY_CONFIG` `context`  parameter in `proxy.conf.js`. This should be documented a lot better than it currently is, which is quite close to 0...

**Comment by javiercn** [comment]
@dushkostanoeski thanks for contacting us.

Thanks for pointing this out. we'll add this to our docs.

**Comment by rashedulalam46** [comment]
Give me the code for PROXY_CONFIG context file

**Comment by mkArtakMSFT** [comment]
Closing as there has been no response from the author.
