### ISSUE TITLE
Blazor Scaffolding Logout page has incorrect route

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Scaffolding-Logout-page-has-incor/1350193)._

---
[severity:It bothers me. A fix would be nice]
I created a standard Blazor Server application, with Individual authentication.
I then Added a new scaffolded Item -> Identity -> Logout

When I run the application, and try to logout, I get a 404 error.  Upon further examination, the scaffolded Logout item has a blank @page route.  In LoginDisplay.razor, the route specified for logout is:  Identity/Account/LogOut.

If I change the pathing in the URL from:

https://localhost:44310/Identity/Account/LogOut

to

https://localhost:44310/Identity/Account/Logout

then the redirect works properly.  I presume the solution is to change the code generation for this scaffolded item to match what is (defaulted) in LoginDisplay.

---
#### Feedback Bot on 2/25/2021, 06:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/25/2021, 10:07 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by adityamandaleeka** [comment]
@HaoK Can you please follow up? Looks like the path is case-sensitive in this case? 

I don't know if this is the exact thing being used here but you can see we have "LogOut" with the capital O:

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Shared/LoginDisplay.IndividualLocalAuth.razor#L4
