### ISSUE TITLE
False Build Failure: Static web asset svg has invalid source type ''

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38366]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/False-Build-Failure:-Static-web-asset-sv/1542516)._

---
[severity:I'm unable to use this version]
I have a large solution which I switch between 2019 and 2022 depending on what I'm doing.  (Heavily prefer 2022, but it's not quite 100% for my needs yet).  

In 2019, the entire solution builds clean.  However, in 2022, I get a single error:

`67>C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets(500,5): error : Static web asset 'C:\[obfuscated]\wwwroot\assets\fonts\[obfuscated]_bold-webfont.svg' has invalid source type ''.`

The project in question (#67) is a React SPA initially created by 2019 several years ago.  The file in question is a static web asset, and works fine in 2019.  I have many other svg assets, none of which complain.

I've searched in vain several times, and I've got no idea what I might be able to do on my end...  If this isn't a false build error, then at least the error message should give some indication on how to address the issue.  But since everything works without info/warn/failure in 2019, I'm pretty confident this is a bug in 2022.

---
#### Feedback Bot on 9/29/2021, 10:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/30/2021, 02:26 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### Javier Calvarro Nelson [MSFT] solved on 10/6/2021, 11:03 AM, 0 votes: 

<p>Thanks for contacting us.</p>
<p>This is a known issue that was fixed in 6.0 RC2 and we’ll be available in the near future. If you want to get unblocked, you can try out using the nightly RC2 SDK from the <a target='_blank' href="https://github.com/dotnet/installer">https://github.com/dotnet/installer</a></p>

**Comment by mkArtakMSFT** [comment]
Looks like this was a dupe and it was fixed already in rc2.

**Comment by mkArtakMSFT** [comment]
Here is the fix: https://github.com/dotnet/sdk/commit/36eed0b9fede16001f5541e92b22e918bffd5e7c
