### ISSUE TITLE
Install Icon not showing on published WebAssembly PWA .NET application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38364]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Install-Icon-not-showing-on-published-We/1565555)._

---
I have created a project with Web Assembly template and selected the Progressive Web Application checkbox. ( Microsoft Visual Studio Community 2022 Preview (64-bit)Version 17.0.0 Preview 5.0 and .NET core 6.0.0-rc.1.21452 ). without any changing to the template when I run it in localhost, the install icon is appeared in address bar but after publishing it doesn't show the icon.

---
#### Feedback Bot on 10/28/2021, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### mahdi.haghnegar on 10/28/2021, 02:48 AM: 

<p>by cleaning the solution and updating to Version 17.0.0 Preview 7.0 this error is added after publishing:<br>
Streaming compilation failed. Falling back to ArrayBuffer instantiation.  out of memory</p>

#### Feedback Bot on 10/28/2021, 11:15 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please try to update the late RTM version of .NET 6 and VS and see whether that issue is resolved?

**Comment by mahdihaghnegar** [comment]
I Updated my vs to Version 17.1.0 Preview 1.1 and created again a new pwa webasembly blazor project and published it. 
but the problem did not solve and  there isn't any install icon in my address bar.

**Comment by javiercn** [comment]
@mahdihaghnegar do you get any error on the browser developer tools?

**Comment by mahdihaghnegar** [comment]
@javiercn 
Hi, here is my console:

Service worker: Install
DevTools failed to load source map: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/escape.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
Failed to find a valid digest in the 'integrity' attribute for resource https://pwa.********.ir/css/bootstrap/bootstrap.min.css with computed SHA-256 integrity 'Tal4izkv1K5rKM5wQFFTOQf1CBe/hF2jyI7FlM9m5Z4='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:22 Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:22
    at async onInstall (service-worker.js:22)

**Comment by mahdihaghnegar** [comment]
@javiercn 

DevTools failed to load source map: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
(index):26 Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at (index):26
(anonymous) @ (index):26
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/escape.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by mahdihaghnegar** [comment]
@javiercn 
I just published the template without any changing.

**Comment by mkArtakMSFT** [comment]
@mahdihaghnegar we were unable to reproduce this issue. So we will need a reliable repro project to be able to investigate this further. So please share with us a minimal repro project publicly hosted  on GitHub.

Also, something to try - can you please try to run the same steps with a browser running `in-private` mode, so there are no extensions loaded and see whether you get different results? Thanks!

**Comment by mkArtakMSFT** [comment]
You can run Google Chrome with this command to load without extensions: "C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-extensions
