### ISSUE TITLE
Blazor Custom Elements not rendering RenderFragment content in an angular app

### ISSUE THREAD

**Issue by Macrossium** [dotnet/aspnetcore#38369]
### Describe the bug
When running the sample [Blazor Custom Elements](https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements#blazor-custom-elements) if a RenderFragment Parameter is added and set in angular the RenderFragment is not rendered.

This works fine when running in a pure blazor application however we need this support so that we can integrate blazor components into the root of an angular app for things such as setting up [Telerik UI](https://docs.telerik.com/blazor-ui/getting-started/what-you-need#common-configuration) support which needs a blazor element inserted at the root of the app to work properly.

Appologies if I missed a previous post already on this and thank you for any help you are able to offer.

### To Reproduce

1. Take a copy of  [Blazor Custom Elements](https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements#blazor-custom-elements).

2. In Counter.razor add `@ChildContent` to the HTML section and `[Parameter] public RenderFragment ChildContent { get; set; }` 
To the code section.

3. In app.component.ts in the my-blazor-counter instance add an inner div tag with some string content.

4. Run the blazor and angular application as instructed on the page.

5. Click the 'add blazor counter' button

6. Observe that the string content is not rendered as expected in the my-blazor-counter blazor control.
### Further technical details
- ASP.NET Core version: 6.0.0-rc.2.21480.5
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 17.0.0 Preview 4.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
C:\Program Files\Microsoft Visual Studio\2022\Preview>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.414 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.208 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by SteveSandersonMS** [comment]
@Macrossium The custom elements package doesn't try to accept `RenderFragment` parameters. It's theoretically possible we could do something in this are in the future, but it's complex and potentially confusing to users. There are at least 3 cases:

 * The markup is just pure static HTML (not involving either Blazor or 3rd-party SPA framework template logic). This would be relatively easy to make work, but is very limiting.
 * The markup contains Blazor template logic (e.g., other Blazor components, or Razor control flow like `@if (...) { ... }`). This isn't possible to make work because the Razor compiler doesn't compile the 3rd-party SPA source code, e.g. Angular templates or React `.jsx` files. There isn't a Razor compiler at runtime either.
 * The markup contains 3rd-party SPA framework template logic (e.g., other Angular components, or Angular template control flow). This might be possible by somehow mapping the concept of parameters to [WebComponent slots](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots), but we haven't investigated this in detail to figure out its practicality. It might be possible to do this already just by declaring a slot in your input and output. It certainly might require using different parameter syntax.

Longer term, assuming the custom elements package is productized in .NET 7, we'd certainly want to do something to meet this need.

**Comment by Macrossium** [comment]
Hi @SteveSandersonMS,

Thank you for your detailed response.

I think we are in the situation you describe in your 2nd and 3rd points in that the markup contains 3rd-party SPA framework template logic (Angular) AND blazor template logic (other Blazor custom elements) so I guess this isn't possible at this stage?

In regards to your 2nd point does it make a difference that the markup contains Blazor custom elements?

Can you please direct me to what you mean by declaring a slot in your input and output?

Thank you again Steve, I appreciate you taking the time to answer my question.


Kind regards,
Macrossium
