### ISSUE TITLE
Possible bug in Visual Studio Professional 2022 Preview (64-bit) Version 17.0.0 Preview 6.0?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38365]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Possible-bug-in-Visual-Studio-Profession/1561944)._

---
[regression] [worked-in:64-bit Version 17.0.0 Preview 6.0]
Hi, I receive this error in web browser when running local development of Azure React project asp.net core 3.1. This was working ok with VS 2022 preview version 5. No error when running this project in VS 2019

This error is related to SignalR subscription and occur every time at startup. (not sporadic)

POST http://localhost:7072/api/negotiateErrorMessages net::ERR_CONNECTION_REFUSED
_callee$ @ useConnection.ts:23
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
.......

---
#### Feedback Bot on 10/24/2021, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/26/2021, 00:07 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
