### ISSUE TITLE
[Question] DistributedSession CommitAsync

### ISSUE THREAD

**Issue by csturm83** [dotnet/aspnetcore#38370]
I'm a bit confused about how `DistributedSession` `CommitAsync` should work. The [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.session.distributedsession.commitasync?view=aspnetcore-6.0#Microsoft_AspNetCore_Session_DistributedSession_CommitAsync_System_Threading_CancellationToken_) states that it _may_ throw if the data store is unavailable.

However, I see it exits early here without an exception if the cache is unavailable:
https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Middleware/Session/src/DistributedSession.cs#L270

I suppose an exception could still be thrown in `CommitAsync` if the cache becomes unavailable after a successful initial `Load`.

I'll note that the Session *Common Errors* documentation [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-6.0#common-errors) seems more strongly worded:

> CommitAsync throws an exception if the backing store is unavailable. If CommitAsync fails, the app can process the exception. LoadAsync throws under the same conditions when the data store is unavailable.

I wonder if that may be a bit misleading? My initial interpretation when I read the Common Errors section was that `CommitAsync` will _always_ fail when the cache is unavailable.

**Comment by rafikiassumani-msft** [comment]
@csturm83  we will be happy to accept a PR that clarifies the doc wording.

**Comment by csturm83** [comment]
@rafikiassumani-msft I'm not entirely convinced this is a docs issue. I did some more digging into the history of that file and found that the code in question changed in [this commit](https://github.com/dotnet/aspnetcore/pull/26098/commits/f99b482fe0ac72958d7bc5ed88e956fb62971c09) of a PR related to nullability.

@pranavkm Was this change in behavior intentional and/or considered breaking? Should `CommitAsync` throw _always_ when the cache is unavailable, like it did previously? My honest expectation is that it would, and should.

**Comment by cabal95** [comment]
I believe the referenced commit also causes CommitAsync() to always deserialize the session, even if the request never accessed it. The getter for "IsAvailable" property calls Load() directly. Which means even if the session hasn't yet been deserialized, and thus no changes made, it will first deserialize it before checking if it has been modified.

**Comment by michalsznajder** [comment]
@cabal95 I opened https://github.com/dotnet/aspnetcore/issues/42009 for issue you mention. I am suppressed it was not caught by any regression...

**Comment by adityamandaleeka** [comment]
https://github.com/dotnet/aspnetcore/pull/43059 removed the `IsAvailable` check in `CommitAsync` and restored the prior behavior here, so I guess this can be closed now.
