### ISSUE TITLE
Resources built for razor library are not copied to publish folder

### ISSUE THREAD

**Issue by JohnKiller** [dotnet/aspnetcore#38374]
### Describe the bug
A task in the csproj file that produces assets in the wwwroot folder are not copied in the publish directory. This works for projects that aren't libraries.

### To Reproduce

1. Clone repo https://github.com/JohnKiller/TestCopyFile
2. Run `dotnet publish -c Release BlazorApp1`
3. Notice that in the publish folder we get the file `test.txt` but it doesn't exist in `_content\RazorClassLibrary1`
4. If you run the command again, it now works because the file is already present

To create the file I've added this line to both projects:

	<Target Name="CompileStaticAssets" AfterTargets="AfterBuild">
		<Exec Command="echo test > $(MSBuildProjectDirectory)/wwwroot/test.txt" />
	</Target>

You can also observe the same behavior by publishing directly the library project: `dotnet publish -c Release RazorClassLibrary1`

Not sure if related: https://github.com/dotnet/sdk/issues/7618

**Comment by javiercn** [comment]
@JohnKiller thanks for contacting us.

That's not going to work as we don't get to see that content. 

We've put together an experimental package as well as a blog post on how to correctly achieve this scenario. You can read the details [here](https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/).
