### ISSUE TITLE
CSS Isolation not works for Img elements

### ISSUE THREAD

**Issue by miladahmadi33** [dotnet/aspnetcore#38376]
### Describe the bug
When I use CSS Isolation and I set id for img element, then I write css style for img element in index.cshtml.css,  the css styles not works for the img element and styles not effect on the img element

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual studio 2022 17.0.0

**Comment by javiercn** [comment]
@miladahmadi33 thanks for contacting us.

We believe this is a dupe of https://github.com/dotnet/aspnetcore/issues/38377
