### ISSUE TITLE
How to solve "Invalid Emulator component" issue in Mobile Blazor Bindings

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#38379]
I've created a Mobile Blazor Bindings project as described [here](https://docs.microsoft.com/en-gb/mobile-blazor-bindings/walkthroughs/build-first-app) 

by running this command: `dotnet new mobileblazorbindings -o FirstMobileBlazorBindingsApp`

When I run the app, the Andriod Device Manager displays a message whose title is "Invalid Emulator component", asking me to Reinstall. Clicking the button starts a process at the end of which the same message is re-displayed. Why the emulator component is not valid, and how can I solve this issue?

Thank you...

**Comment by javiercn** [comment]
This issue was moved to dotnet/MobileBlazorBindings#431
