### ISSUE TITLE
CSS Isolation not works for nested CSS selector

### ISSUE THREAD

**Issue by miladahmadi33** [dotnet/aspnetcore#38377]

**Comment by javiercn** [comment]
@miladahmadi33 thanks for contacting us.

You need to define your rule as `div ::deep img` (or `div::deep img`, I don't remember if the space was relevant).

You can check more details [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#child-component-support)
