### ISSUE TITLE
POSTing array into an "object" action parameter does not work

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/aspnetcore#38383]
### Describe the bug
POSTing array via form data into an "object" action parameter does not work

### To Reproduce

1) Action method
```
[HttpPost]
public IActionResult MyAction(object value)
{
    
}
```

2) Now send a POST form-data request with this payload:
```
value[]: 1
value[]: 2
```
Where "xxx[]" is a common convention for POSTing arrays via form-fields.

3) Result: `value` is an empty `object`. Should be some form of array/ienumerable/etc.

### Further technical details
- ASP.NET Core version: 5.0 + MVC
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by pranavkm** [comment]
Model binding uses the target (parameter) type to determine how to bind a type, it's not influenced by the shape of the data that is being received. Using a array / `IEnumerable<T>` type should allow binding to suceed.

**Comment by alex-jitbit** [comment]
@pranavkm OK, fair enough, I'm closing the issue, thanks for taking the time.

I think it worked in .NET Framework though, But I can be mistaking.
