### ISSUE TITLE
@inject IWebHostEnvironment Environment in Page not working in .NET 6

### ISSUE THREAD

**Issue by Abianue1** [dotnet/aspnetcore#38384]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0246	The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rafikiassumani-msft** [comment]
@Abianue1 can you make sure that you have ` @using Microsoft.AspNetCore.Hosting`?

**Comment by Abianue1** [comment]
@rafikiassumani-msft Thanks for reaching out. Yes I ensured to to add the using to the page
![image](https://user-images.githubusercontent.com/24936467/142056985-bfb91e4c-969a-4d48-a004-fd7b4f76a883.png)

**Comment by pranavkm** [comment]
@Abianue1 could I bother you to share a minimal app that reproduces the problem? I'm assuming this is a Blazor Server app?

**Comment by Abianue1** [comment]
No problem. the same application works perfectly when running in .net 5
[NgLivePrint.App.zip](https://github.com/dotnet/aspnetcore/files/7550120/NgLivePrint.App.zip)

**Comment by pranavkm** [comment]
@Abianue1 you're building a Blazor WebAssembly app which is running in a browser. Using `IWebHostEnvironment` or writing to disk might not be the right way to go about what you're trying to do. I'll recommend following up on StackOverflow under the blazor tag to figure out how best to approach your problem at hand.

**Comment by Abianue1** [comment]
@pranavkm thanks for your feedback. I kinda suspected that the issue would be overlooked and you would focus on what I was doing. I believe regardless of what the code is doing I can't inject the IWebHostEnvironment in .NET 6 and same code works perfectly fine in .NET 5. Thanks again for taking time to have a look. I will stick with dotnet 5 for now
