### ISSUE TITLE
Allow developers to use Dependency Injection within components the same way DotNetCore does with everything else.

### ISSUE THREAD

**Issue by LandanParker** [dotnet/aspnetcore#38385]
### Is your feature request related to a problem? Please describe.
I want to use real dependency injection, rather than a delayed property set by the RenderTreeBuilder.
I can't access the ServiceProvider before components are instantiated.
I have to wait until the component has already been instantiated, which is not dependency injection.

### Describe the solution you'd like
Allow developers to have their injected properties available during component instantiation.
Or, Allow developers to access the DI via constructor parameters like normal.

**Comment by bbhxwl** [comment]
var forwarder = app.Services.GetService<IHttpForwarder>();

**Comment by javiercn** [comment]
@LandanParker thanks for contacting us.

You can use `@Inject` to perform property injection as well as provide your own `IComponentActivator` to achieve this in conjunction with a constructor on your component.

**Comment by bbhxwl** [comment]
> @LandanParker thanks for contacting us.
> 
> You can use `@Inject` to perform property injection as well as provide your own `IComponentActivator` to achieve this in conjunction with a constructor on your component.

He may be talking about code injection, because @ inject also has the feature of net core 3.1. I think he should know. I called injection in main yesterday. No, I won't do it today.

**Comment by javiercn** [comment]
@bbhxwl it's not clear to me what you are referring to.

There are two types of injection, by default we will call the default constructor and inject services on properties marked with InjectAttribute `(@inject)` when we create components.

Developers can register a custom IComponentActivator implementation on DI to override how the components get instantiated, for example to instantiate them directly from the DI container.
