### ISSUE TITLE
Blazor Wasm Hosted Project : API Call not working, Returns Index.html for all API Calls

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#38396]
I created windows 11 VM and installed visual studio 2022 so that I can have clean environment. using .NET 6

GitHub source Code.
https://github.com/nssidhu/BlazorAppTimezone

Published Version
https://blazorapptimezoneserver20211114202356.azurewebsites.net/

Screen Recording
https://1drv.ms/u/s!AtHk7h6Srnk_h9oDmK19vXG4CJOavg?e=obU0Gf

1) First part, running it from visual Studio 2022, it works as expected.
2) Second part, when i publish it locally and try to run locally, it works as expected
3) Publishing it to Azure App Service. (Does not seems to be working)
   None of the call to API are working, it is just returning index.html, even swagger is not working on the published version.
   Looks Like it is always defaulting to MapFallbackToFile("Index.html").

```
C:\Users\admin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Your issue is that the value you are sending contains an encoded `/` as `https://blazorapptimezoneserver20211114202356.azurewebsites.net/api/WeatherForecast/GetTimeZonetime/America%2FChicago`

**Comment by nssidhu** [comment]
I tried that, did not help. 
Few point i want to make here. Why does it work when using in Visual studio ? also it does work when published locally to folder.
But when published to Azure App Server it does not work.
Also there is swagger end point which also does not work on the published version(azure app service), but swagger works locally.
Any clues ?

**Comment by javiercn** [comment]
Because when you deploy to app service there is an IIS frontend that performs the decoding from `%2F` to `/`. Hence my suggestion to avoid special characters like `/` on your URLs.
