### ISSUE TITLE
Visual Studio 2022  Couldn't start the SPA development server with command 'npm start'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38398]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022--Couldnt-start-the-S/1578685)._

---
[severity:I'm unable to use this version] [regression] [worked-in:visual Studio 2019]
After I create a new ASP.Net Angular Project I can't run it because I get the following error "Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Couldn't start the SPA development server with command 'npm start'."

---
#### Feedback Bot on 11/10/2021, 07:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 11/12/2021, 09:51 PM: 

<p>Thanks for contacting us. What happens when you try to start your project from CLI using <code>dotnet run</code> command? Does it start or do you observe a similar behavior?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What is the version of the Node that you have on your machine?
Also, what happens if you go to the `ClientApp` folder and run `npm run start` ?

**Comment by JMS-reTro** [comment]
I have the same problem. (Couldn't start the SPA development server with command 'npm start'.)

**Comment by javiercn** [comment]
@JMS-reTro thanks for contacting us.

If you navigate on the console to the `ClientApp` folder and execute `npm run start` is the SPA proxy able to start or do you get an error (and if so what error)

**Comment by JMS-reTro** [comment]
> angulartest@0.0.0 prestart
> node aspnetcore-https

> angulartest@0.0.0 start
> run-script-os

"run-script-os" is not recognized as an internal or external command, program, or executable batch file.

**Comment by zerogr4vity** [comment]
@JMS-reTro try installing the package: npm install --save-dev run-script-os

**Comment by JMS-reTro** [comment]
> @JMS-reTro try installing the package: npm install --save-dev run-script-os

Thanks a lot!! It worked.

**Comment by javiercn** [comment]
@JMS-reTro I'm glad that you figured out the issue. I suspect for some reason `npm install` didn't run the first time, the package should be there as its listed in package.json

Closing this issue since it has been resolved.
