### ISSUE TITLE
Add IIS Express launch profile for gRPC templates

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#38405]
IIS Express has been updated in Dev 17.1 Preview1 and gRPC workloads are now supported. We should consider adding back the IIS Express launch profile settings for gRPC projects

**Comment by Tratcher** [comment]
How do we handle the OS version check? It's broken right now: https://github.com/dotnet/aspnetcore/issues/37831

**Comment by rafikiassumani-msft** [comment]
Triage: We would need to wait until #37831 is closed before doing the template changes.

**Comment by adityamandaleeka** [comment]
We don't plan to do this.
