### ISSUE TITLE
(Blazor) Append boolean to LocationChangedEventArgs indicating whether the navigation came from NavigationManager

### ISSUE THREAD

**Issue by ericgrantholland** [dotnet/aspnetcore#38402]
### Is your feature request related to a problem? Please describe.
I am unable to keep an accurate stack of the pages the user has visited while on the site. This is due to not knowing whether a user has explicitly navigated to a page or used the back/forward button to go to the previous/next page. If the user explicitly chose to go to the previous page(NOT clicking back button, clicking a link in-app or something), a new entry in the stack should be appended. If the back button was used, we should remove the current page from the stack so the previous page is at the top. 

### Describe the solution you'd like
I'm using the NavigationManager.LocationChanged event to handle updating the stack. There is currently an IsNavigationIntercepted bool on LocationChangedEventArgs, but the value is "false" when clicking the browser back button vs calling NavigationManger.NavigateTo("/SomePath"). I'd like a boolean added(LocationChangedEventArgs.IsFromNavigationManager) to LocationChangedEventArgs that indicates if NavigateTo was called to initiate the location change event. 

An alternative would be to put the type of location change into the event args(Redirect, BackNavigation, ForwardNavigation, etc). Not sure if this is possible/easy.

**Comment by MackinnonBuck** [comment]
You can now use `NavigationOptions.HistoryEntryState` to add state to the history stack when calling `NavigationManager.NavigateTo()`. Then you can retrieve that state in a `LocationChanged` handler via `LocationChangedEventArgs.HistoryEntryState`. This should be enough to determine if a page has already been visited, at least if it was navigated to programmatically.
