### ISSUE TITLE
Investigate not requiring unintuitive requirements for pre-rendering PageTitle

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#38400]
Pre-rendering for PageTitle requires rendering things in a specific order and relies on  a _Layout.cshtml which is not very intuitive. See https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly#prerendering-configuration for all of the steps involved here.

Possible things to look at:

a) Can we do away with requiring a separate `_Layout`?
b) If the first option is difficult, could we produce an error if the `PageTitle` component is being rendered before any other component?

**Comment by mkArtakMSFT** [comment]
Marking as P1 for investigation to understand what the solution will look like. Depending on the findings we can reevaluate and see whether it's still P1 or not.
