### ISSUE TITLE
Blazor action and function object type is not disposed.

### ISSUE THREAD

**Issue by Bala-tec** [dotnet/aspnetcore#38423]
**This issue is related to static reflection caches** - https://github.com/dotnet/aspnetcore/issues/37315#issuecomment-935720927

I ran the App in release mode without a debugger attached to it and took a memory usage snapshots using profiler.

![image](https://user-images.githubusercontent.com/93471823/141881009-25c00280-5db8-42f6-91b9-80f486a71b96.png)

![image](https://user-images.githubusercontent.com/93471823/141881345-118201f9-7ad1-44c3-8f83-2df72623d365.png)

Attached [Repo](https://github.com/Balaji-Elumalai/Blazor_TextBox.git)

**Is there a way to force clear these caches?**

**Comment by javiercn** [comment]
@Bala-tec thanks for contacting us.

No, there is no way to clear the reflection caches we use.
