### ISSUE TITLE
Expose timing and connection information in in-proc

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#3842]
In Windows 19H1, the `HTTP_REQUEST_INFO` struct supports following new info types-
- `HttpRequestInfoTypeRequestTiming`: Returns timestamps (KeQueryPerformanceCounter) for significant events in Request life time (e.g. connection start, SSL handshake timings, delivery timings etc.)
- `HttpRequestInfoTypeTcpInfoV0`: Returns information about underlying TCP connection via `TCP_INFO_V0`.
- `HttpRequestInfoTypeRequestSizing`: Returns information about different sizes from underlying components (e.g. HTTP header size, SSL handshake send/receive sizes etc.). In addition, it also returns more information about connection like if TCP fast open was used, TLS Session Resumption/False Start was used etc.

We should expose this information via new features

**Comment by shirhatti** [comment]
Clearing milestone so this shows up in triage

**Comment by BrennanConroy** [comment]
Might need new IIS APIs, need to investigate.

**Comment by NGloreous** [comment]
@BrennanConroy we have built a native IIS pipeline that is able to extract this data. I can point you to the code if you are interested.

**Comment by adityamandaleeka** [comment]
Triage: this should be very easy to do if we do #35012 first.

**Comment by Tratcher** [comment]
Nevermind, we can track this all with https://github.com/dotnet/aspnetcore/issues/35012.
