### ISSUE TITLE
ScopedServices property of OwningComponentBase may not be disposed.

### ISSUE THREAD

**Issue by liangpeihui** [dotnet/aspnetcore#38424]
### Describe the bug
I access a component derived from OwningComponentBase. After shutting down the host directly, his scoped service cannot be disposed.
![image](https://user-images.githubusercontent.com/79532375/141900854-f406d6b1-74fb-412c-9075-369365f6bfc2.png)
![image](https://user-images.githubusercontent.com/79532375/141901110-05e0eddc-6676-46d1-bfa6-04d5b6ae862d.png)
![image](https://user-images.githubusercontent.com/79532375/141901188-ff2e2676-8473-4cf8-8b5f-78732f6d107a.png)

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
