### ISSUE TITLE
Prevent ASP.NET Core SignalR Hub from being cached from CDN on LongPolling

### ISSUE THREAD

**Issue by pedroagp** [dotnet/aspnetcore#38437]
We have an application which exposes an endpoint which is an asp.net core signalr hub.

When testing on longpolling (mandatory) we found out erratic behaviour from the cdn (in this case, cloudfront) caching the responses the hub makes to the client.

Is there any way to add Cache-Control headers in LongPolling responses ? 

Reconfiguring cloudfront would not be an option, unfortunately.

**Comment by rafikiassumani-msft** [comment]
Triage: We will add the Cache-Control headers by default. @BrennanConroy  can you provide a workaround for this ?

**Comment by BrennanConroy** [comment]
You should be able to workaround this by adding a middleware before `UseEndpoints`
```csharp
app.Use((context, next) =>
{
    // change to be the path of your hub
    if (context.Request.Path == "/default")
    {
        context.Response.Headers.CacheControl = "no-cache,no-store";
        context.Response.Headers.Pragma = "no-cache";
    }
    return next(context);
});
```

**Comment by pedroagp** [comment]
Thank you for the quick response and workaround.

I saw this labeled for NET 7 planning and being this a best-practice on long polling (https://tools.ietf.org/id/draft-loreto-http-bidirectional-07.html#network) , what would be the chance for this (by default behaviour) to be added still on NET 6 roadmap (or even as an optional/opt-in feature?)

**Comment by BrennanConroy** [comment]
This is the first time we're seeing someone report this issue in the more than 4 years since releasing. Combined with the workaround it's unlikely we'll patch this at this point.
https://github.com/dotnet/aspnetcore/blob/main/docs/Servicing.md#servicing-bar
