### ISSUE TITLE
When using .net core 3.1 runtime with System.Text.Json 6.0.0 the serialization doesn't honor new API.

### ISSUE THREAD

**Issue by brandonseydel** [dotnet/aspnetcore#38438]
### Describe the bug
When using .net core 3.1 runtime and System.Text.Json 6.0.0 the addjsonoptions for nullability does not work with the new api.
### To Reproduce

Set up a .net core 3.2 project with System.Text.Json 6.0.0.
This works
```
.AddJsonOptions(y =>
				{
					y.JsonSerializerOptions.IgnoreNullValues = true;
				})
```
This does not
```
.AddJsonOptions(y =>
				{
					y.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
				})
```

**Comment by javiercn** [comment]
@brandonseydel thanks for contacting us.

I'm not sure this is something that is expected to work.

**Comment by pranavkm** [comment]
This is a known issue. The 3.1 version of the formatter had a custom copy constructor that only configured properties available in 3.1. This was addressed in 5.0. Outside of rolling a custom formatter or upgrading to a newer version, there isn't a great resolution here.

**Comment by brandonseydel** [comment]
@pranavkm - Can you refernce the list of known issues so I can validate whether or not we can move forward.  I am  in need of the new reference ignore ability, but the client does not want to move past 3.1 atm.

**Comment by pranavkm** [comment]
I guess the closest I could find was the original ask to add the copy constructor which describes this problem - https://github.com/dotnet/runtime/issues/30445.
