### ISSUE TITLE
Blazor and .NET6 creates an error: EntrypointInvoker in assembly Microsoft.AspNetCore.Components.WebAssembly

### ISSUE THREAD

**Issue by erossini** [dotnet/aspnetcore#38436]
I have my simple project with Blazor. I updated the project from .NET5 to .NET6. I deploy to the production environment using `Web Deploy`. On the production server, I am getting this error

> Error: Could not find class: Microsoft.AspNetCore.Components.WebAssembly.Hosting:EntrypointInvoker in assembly Microsoft.AspNetCore.Components.WebAssembly

![image](https://user-images.githubusercontent.com/9497415/141995243-d209457e-d0a8-469a-ac49-b30e1bada24d.png)

The configuration of Web Deploy is 

![image](https://user-images.githubusercontent.com/9497415/141995376-4b653310-4094-46ac-8a70-4041d1d2550f.png)

**Comment by erossini** [comment]
This is the csproj

```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSC.Blazor.Components.DataTable\PSC.Blazor.Components.DataTable.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\img\psc_logo.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </Content>
  </ItemGroup>

</Project>
```

**Comment by pranavkm** [comment]
@erossini do you also mind including the `obj\project.assets.json` for this file? It might be one of your references is causing an older version of blazor.webassembly.js to be used, instead of the 6.0.0 version, and the resolved package references might give us some hints. Alternatively, if there's a minimal app you could share with us that reproduces the problem, that would be great.

**Comment by erossini** [comment]
This is the `project.assets.json`

[project.assets.zip](https://github.com/dotnet/aspnetcore/files/7554594/project.assets.zip)

**Comment by legistek** [comment]
Same problem here. I cleared out all bin/obj and other intermediate files I could find.

**Comment by legistek** [comment]
Ohh but clearing my browser cache fixed it. Try that!

**Comment by erossini** [comment]
ohh @legistek you are right. It made me crazy... simple solution... Thank you everybody!

**Comment by pranavkm** [comment]
Do you have your server configured to include the correct cache headers? For instance, in a Blazor hosted app, or in development, Blazor will include the following headers when serving this file:

![image](https://user-images.githubusercontent.com/174281/142253739-179c3a45-0446-499f-94de-7855637d4eac.png)

If you are unable to configure the server headers, you could consider using some cache busting mechanism such as adding a nonce to your blazor.webassembly.js script src.

**Comment by erossini** [comment]
> Do you have your server configured to include the correct cache headers? For instance, in a Blazor hosted app, or in development, Blazor will include the following headers when serving this file:
> 
> ![image](https://user-images.githubusercontent.com/174281/142253739-179c3a45-0446-499f-94de-7855637d4eac.png)
> 
> If you are unable to configure the server headers, you could consider using some cache busting mechanism such as adding a nonce to your blazor.webassembly.js script src.

When you say "cache busting mechanism", what do you mean? How can I do that? 

I saw those links:
- https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-5.0
- https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/content-security-policy.md
- https://github.com/dotnet/AspNetCore.Docs/issues/22121

**Comment by legistek** [comment]
Good to know @pranavkm thanks! My only hesitation though is won't that hurt us with those large AOT payloads?

**Comment by erossini** [comment]
> Good to know @pranavkm thanks! My only hesitation though is won't that hurt us with those large AOT payloads?

Why do you use AOT? In my test, it is working also without it

**Comment by legistek** [comment]
> > Good to know @pranavkm thanks! My only hesitation though is won't that hurt us with those large AOT payloads?
> 
> Why do you use AOT? In my test, it is working also without it

I'm just asking if the HTTP headers prohibited caching, wouldn't that make it slower for users to download the application after the first visit? I just mention AOT because it adds significant file size.

**Comment by pranavkm** [comment]
@legistek it's specifically for the blazor.webassembly.js file. Blazor manages downloading all other files which does not rely on the browser's HTTP cache.

**Comment by legistek** [comment]
Ah very clever! Thanks for clarifying!

**Comment by Swimburger** [comment]
Ran into the same issue, but it wasn't in the browser cache, it was in the CDN cache (Cloudflare in my case).
Don't forget to purge the cache.

**Comment by wynnytsky** [comment]
> Ran into the same issue, but it wasn't in the browser cache, it was in the CDN cache (Cloudflare in my case). Don't forget to purge the cache.

In my case the response header includes "x-cdn: Imperva" only when I'm off the corporate VPN.  Get back on the VPN and the x-cdn falls off, and I see different values for content-length + ETag.

**Comment by SteveDunn** [comment]
> Ran into the same issue, but it wasn't in the browser cache, it was in the CDN cache (Cloudflare in my case). Don't forget to purge the cache.

I'm getting the same issue with an Azure CDN. It must be the caching as the same app works from an in-private window

**Comment by SteveDunn** [comment]
I found that this works:  change the line where you reference the .js file and add a version to the url, e.g.

`<script src="_framework/blazor.webassembly.js?version=6"></script>`
