### ISSUE TITLE
Blazor in production: can't find bindings module assembly: System.Private.Runtime.InteropServices.JavaScript

### ISSUE THREAD

**Issue by erossini** [dotnet/aspnetcore#38433]
I have a Blazor Web Assembly project. When I run it on my machine, the project is working fine. So, I use Web Deploy to deploy the project in `Release` in my production server. If I open the page on the production, I have an error

> Uncaught (in promise) Can't find bindings module assembly: System.Private.Runtime.InteropServices.JavaScript

[![enter image description here][1]][1]

The Web Deploy configuration is (all of them are default configuration and there are not other options)

- Configuration: release
- Target framework: net5.0
- Deployment Mode: self-contained
- Target Runtime: browser-wasm 

[![enter image description here][2]][2]

The root has this files

[![enter image description here][3]][3]

and then in the `wwwroot` folder I have all the files

[![enter image description here][4]][4]

The `web.config` is the default one

    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <system.webServer>
        <staticContent>
          <remove fileExtension=".blat" />
          <remove fileExtension=".dat" />
          <remove fileExtension=".dll" />
          <remove fileExtension=".json" />
          <remove fileExtension=".wasm" />
          <remove fileExtension=".woff" />
          <remove fileExtension=".woff2" />
          <mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
          <mimeMap fileExtension=".dll" mimeType="application/octet-stream" />
          <mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
          <mimeMap fileExtension=".json" mimeType="application/json" />
          <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
          <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
          <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
        </staticContent>
        <httpCompression>
          <dynamicTypes>
            <add mimeType="application/octet-stream" enabled="true" />
            <add mimeType="application/wasm" enabled="true" />
          </dynamicTypes>
        </httpCompression>
        <rewrite>
          <rules>
            <rule name="Serve subdir">
              <match url=".*" />
              <action type="Rewrite" url="wwwroot\{R:0}" />
            </rule>
            <rule name="SPA fallback routing" stopProcessing="true">
              <match url=".*" />
              <conditions logicalGrouping="MatchAll">
                <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
              </conditions>
              <action type="Rewrite" url="wwwroot\" />
            </rule>
          </rules>
        </rewrite>
      </system.webServer>
    </configuration>

What can I do to fix the problem?

  [1]: https://i.stack.imgur.com/CzbdO.png
  [2]: https://i.stack.imgur.com/tlEln.png
  [3]: https://i.stack.imgur.com/n1i31.png
  [4]: https://i.stack.imgur.com/iDPki.png

**Comment by javiercn** [comment]
@erossini thanks for contacting us.

Could you try to upgrade to .NET 6.0 and see if you still have the same issue?

Are there any network errors on the network tab?

**Comment by erossini** [comment]
Yes, I updated the project to .NET6 and for this I opened another issue :) https://github.com/dotnet/core/issues/6922

No, there is no errors in the network tab

**Comment by javiercn** [comment]
@erossini what happens when you remove the `self-contained` flag?

**Comment by erossini** [comment]
I can't. In the Web Deploy settings, it is the only option and I can't deselected.

**Comment by javiercn** [comment]
@erossini is this a standalone or hosted webassembly app?

**Comment by erossini** [comment]
webassembly

**Comment by javiercn** [comment]
@erossini yes, but standalone or hosted :)

**Comment by erossini** [comment]
sorry :) standalone

**Comment by TanayParikh** [comment]
Note; I've moved https://github.com/dotnet/aspnetcore/issues/38436 into dotnet/aspnetcore.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Given that updating to 6.0 fixed the original reported issue, and the other issue you're facing is tracked as part of a separate issue there seems to be nothing else to investigate this. So closing this one.
