### ISSUE TITLE
problem converting a 3.1 core app to 6.0, routing is using more than 12-13 gig of ram

### ISSUE THREAD

**Issue by Spirch** [dotnet/aspnetcore#38444]
I have a working 3.1 core asp.net application with this routing

```
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "SubstanceArea",
                    pattern: "{culture=en}/{area:exists}/{reportId}/{substanceId}/{controller}/{action=Index}/{id?}/{auxId?}");

                endpoints.MapControllerRoute(
                    name: "ReportArea",
                    pattern: "{culture=en}/{area:exists}/{reportId}/{controller}/{action=Index}/{id?}");

                endpoints.MapControllerRoute(
                    name: "CommonArea",
                    pattern: "{culture=en}/{area:exists=common}/{controller=Home}/{action=Index}/{id?}");
            });
```

under 3.1 when I start the application in debug mode, iisexpress load the welcome page after using 270 meg of ram

with 6.0 I had to stop the debugging process after iisexpress was using over 13 gig of ram

I tried to remove SubstanceArea routine and ReportArea routing, it reach about 400 meg after the welcome page is loaded

if I add back ReportArea, it use around 900 meg of ram

if I remove ReportArea and add SubstanceArea, it use  around 7 gig of ram

I have around 100 controller, an average of 4 action per controller, 3 different areas

**Comment by javiercn** [comment]
@Spirch thanks for contacting us.

I believe the large number of parameters in your app might be causing this. Could you try following the guidance [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#guidance-for-large-route-tables) and let us know if that helps solve the issue?

**Comment by Spirch** [comment]
> 
> 
> @Spirch thanks for contacting us.
> 
> I believe the large number of parameters in your app might be causing this. Could you try following the guidance [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#guidance-for-large-route-tables) and let us know if that helps solve the issue?

thanks for the link, it seem adding **:int** to **reportId** and **substanceId** fix the issue, it now load the welcome page after using 400 megs of ram, still more than previously but for now I can continue converting to .net 6.0 and come back later to see if I can reduce it

**Comment by javiercn** [comment]
@Spirch It's great to hear that it worked. 

You can probably reduce it much lower if you use a regex constraint on the culture parameter, Like `[a-zA-Z]{2}(-[a-zA-Z]{2})?` to support things like `en` or `en-US`

**Comment by Spirch** [comment]
@javiercn it doesnt help, for culture I have put in a RequestLocalizationOptions maybe the routing pick it up and already check what is valid from it? so adding a regex doesnt help?

**Comment by javiercn** [comment]
@Spirch those two things should be independent.

Taking another look at the routes, it's likely that the constraints you applied are enough. There might be some more optimizations that can be done, but its hard to offer some guidance without the full list of routes.
