### ISSUE TITLE
Img tags do not receive scope identifier in .Net 6 MVC Core

### ISSUE THREAD

**Issue by RobinWeitzel** [dotnet/aspnetcore#38450]
### Describe the bug
Image tags (<img />) do not receive scope identifiers meaning that CSS isolation does not work. For all other tags the identifier is set correctly.

Example:
![image](https://user-images.githubusercontent.com/12135433/142061340-7df1719f-51e8-44a2-8daf-fd201464fe27.png)

### To Reproduce
Create a .Net 6 MVC Core project, add an image tag to a page, run the app and inspect the image tag in the browser.

### Exceptions (if any)
None found

### Further technical details
- ASP.NET Core version: .Net6 MVC
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022
- Include the output of `dotnet --info`:

.NET SDK (gemäß "global.json"):
 Version:   6.0.100
 Commit:    9e8b04bbff

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@RobinWeitzel thanks for contacting us.

Can you share the source for the razor page where you are using it? I suspect you are using `~` in your url and that's transforming the tag into a tag helper. We only apply css scope identifiers to plain HTML elements.

We have an issue to allow third-party components to opt-in to it in the future [here](https://github.com/dotnet/aspnetcore/issues/30213)

**Comment by buchatsky** [comment]
Same for \<a\> tags. Standard ASP.NET Core Web App (M-V-C) project template:
```
<header>
    <nav b-bddmc6yalx class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div b-bddmc6yalx class="container-fluid">
            <a class="navbar-brand" href="/">WebApplication1</a>
            <button b-bddmc6yalx class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"

```

**Comment by buchatsky** [comment]
@javiercn in my case both \<img> and \<a> tags obtain the scope identifier when they are not tag helpers

**Comment by sanme98** [comment]
@javiercn I found for `<a>` tag, it only without the scope identifier if with asp-xxx attribute. E.g.

```
<a class="navbar-brand" asp-area="" asp-page="/Index">testing</a>
```
If I remove the asp-area and asp-page attributes, the scope identifier will be back
```
<a class="navbar-brand">testing</a>
```
