### ISSUE TITLE
Why was the "Individual User Accounts" option removed?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#38457]
When creating an AP.NET Core Web API application, the *Authentication type* options now include:

- None
- Microsoft Identity Platform
- Windows

I understand Microsoft Identity Platform provides a lot of new and powerful features. But I just have a simple API that will be accessed by a handful of applications, perhaps with a couple of authorization levels. I'm not using Azure, Active Directory or anything like that. None of the available options would seem appropriate for my application. And so I'm left to write my own.

Why was the *Individual User Accounts* option removed? Isn't that still a viable option for developers who don't need Microsoft Identity Platform?

**Comment by javiercn** [comment]
@SoftCircuits thanks for contacting us.

We never supported Individual User Accounts for Web APIs.

**Comment by SoftCircuits** [comment]
@javiercn Are you sure? According to [Microsoft Documentation](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/individual-accounts-in-web-api):

> In Visual Studio 2013, the Web API project template gives you three options for authentication:
> 
> - Individual accounts. The app uses a membership database.
> - Organizational accounts. Users sign in with their Azure Active Directory, Office 365, or on-premise Active Directory credentials.
> - Windows authentication. This option is intended for Intranet applications, and uses the Windows Authentication IIS module.

If this Individual accounts was an option today, it seems like adding authentication to my Web API would be as straight forward as with MVC and Razor Pages. As it is, I'm left writing a bunch of custom code, and every article I can find does it differently. I don't understand why this wouldn't be an option.
