### ISSUE TITLE
open a page as modal?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38459]
I think we need a feature that open a page or component as a modal page.

we do not have to write a modal div just open the page there will be open the modal page.

**Comment by javiercn** [comment]
@mcguu thanks for contacting us.

There are already libraries that you can use for this, like Microsoft fluent web components that already provide this functionality in a convenient way to consume.

Our focus is on building the framework primitives that enable building new experiences and we don't focus that much on individual components.
