### ISSUE TITLE
IAsyncEnumerable with System.Text.Json in IIS 10 - problem

### ISSUE THREAD

**Issue by candrewtemenoscom** [dotnet/aspnetcore#38460]
I am trying to use the Asynchronous iterator pattern to provide streaming Web API hosting in IIS. The application reads the data from DB asynchronously and yield return each row out to the response stream. However, I found that the row data did not come out one by one but in a single chuck. For example, in a 10 row datatable,  it will show one row on the browser and then waiting for a while and the 9 rows altogethers. However, if I switch to use Krestrel as hosting. The behaviour is correct that it splits out one row at a time. It seems that there is a problem to use IIS as hosting for streaming API using the asp.net core 6. Is it a bug

**Comment by candrewtemenoscom** [comment]
Sorry I forgot to post my code snippet

await foreach (var item in _datasetGateway.RunDatasetQueryAsync(query).ConfigureAwait(false))
                    {
                        await Task.Delay(500);
                        yield return item;
                    }

**Comment by davidfowl** [comment]
It's likely you'll need a line like this on the HTTP Context

```C#
HttpContext.Features.Get<IHttpResponseBodyFeature>()?.DisableBuffering();
````

PS: I found some other bugs you'll experience in development while using this feature. Hot reload for CSS and .NET need to be disabled to make this work on IIS 😢. We'll get this fixed.

**Comment by candrewtemenoscom** [comment]
Thank you for your prompt response. I appreciated that.

**Comment by adityamandaleeka** [comment]
This issue is related: https://github.com/dotnet/aspnetcore/issues/38477
