### ISSUE TITLE
Visual Studio 2022 Launches Chrome - Only with limited features when running standalone React.Js projects

### ISSUE THREAD

**Issue by sangeethnandakumar** [dotnet/aspnetcore#38464]
Description
1. I created a Standalone React app in Visual Studio 2022.
2. When I launch my app, It always opens in a chrome window with no extensions, bookmarks, logins, profiles etc.. something similar to an incognito window. (Image attached)
3. My application uses Google authentication for login.
4. But when browser opens like this Google won't allow to login due to some security reasons.
5. Then I had to copy the exact URL and paste it in a standard chrome browser for it to works flawlessly.

Why Visual Studio launches Chrome with this limited support. I think there are some flags passing to Chrome to work like this.
How can I change this behavior?

How To Reproduce
1. Create a standalone React.Js project in Visual Studio 2022
2. Launch it

Import Part In Package.json
```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**WHEN OPENS FROM VISUAL STUDIO**

![issue](https://user-images.githubusercontent.com/24974154/142138404-93d86796-2df4-467f-bd49-e79abf7b579e.png)

**WHEN MANUALY PUT URL IN A STANDARD CHROME BROWSER**

![issue2](https://user-images.githubusercontent.com/24974154/142138507-8033dc65-550f-42de-9847-b10b78a1753a.png)

**Comment by TanayParikh** [comment]
Hi @sangeethnandakumar. This is because a chromium profile is being used for debugging. 

Please close all browser windows before you start debugging or follow the steps here: https://github.com/dotnet/aspnetcore/issues/20915#issuecomment-614933322

Please note this repo is for aspnetcore. Please report general VS issues using the VS 'Report a Problem' button to ensure it gets directed to the correct team.

**Comment by sangeethnandakumar** [comment]
Thanks @TanayParikh , I've gone through the options

1. Please close all browser windows before you start
----------------------------------------------------------
I can't do this. As I mentioned I'm running frontend as a standalone ReactJs app with VS.
I also have a WebAPI running over a different VS instance with Swagger opened (on Chrome) behind the scene.
Without the API project running, It's a no use for me.

2. Creating a different user profile for Chrome (From issue #20915)
--------------------------------------------------------------------------
I cannot find that "Browse With" menu on the debug dropdown. (As shown in the image in issue #20915)
May be it works if I have a ASP.NET backed React project.
I'm running a pure ReactJs standalone project inside VS and there are only 2 options there I could see. (Run with Chrome and Run with Edge)

The Resolution
-----------------
It looks like this is a potential drawback with Chrome and not to do with Visual Studio.
- Thus closing the issue. Thanks @TanayParikh .!
