### ISSUE TITLE
Not Able to Navigate Custom URL using GetUriWithQueryParameter

### ISSUE THREAD

**Issue by KarthiSekar24** [dotnet/aspnetcore#38478]
**Bug Description:** 

I need to create a new URI based on the custom path value. But it is not able to achieve from my end.

**Replication Steps:**

```
var uri = NavigationManager.GetUriWithQueryParameter("value",3);
NavigationManager.NavigateTo(uri);
```
In the above sample it navigate to `https://localhost:7141/?value=3`

But i need to Navigate a value using custom path
```
    var path = "counter";
   NavigationManager.NavigateTo(path + NavigationManager.GetUriWithQueryParameter("value",3), true);
```
 **Expected Result:**  `https://localhost:7141/counter?value=3`
**Actual Result:** `counterhttps://localhost:7141/?value=3`

For your reference i have attached the sample, 

[BlazorApp2.zip](https://github.com/dotnet/core/files/7555882/BlazorApp2.zip)

Could you please suggest any solution to achieve this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The API to use for this scenario is [this one](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanagerextensions.geturiwithqueryparameters?view=aspnetcore-6.0#Microsoft_AspNetCore_Components_NavigationManagerExtensions_GetUriWithQueryParameters_Microsoft_AspNetCore_Components_NavigationManager_System_String_System_Collections_Generic_IReadOnlyDictionary_System_String_System_Object__).

You'll need to pass in `counter` as the `string` parameter and pass in the querystring parameters through the dictionary.
