### ISSUE TITLE
Slow Blazor wasm build in Visual Studio 2022 .NET 5.0 based

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38476]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Slow-Blazor-wasm-build-in-Visual-Studio-/1579238)._

---
[regression] [worked-in:2019]
I have a quite simple Blazor WASM app, created from the Blazor client/server template. Besides Blazor client and server projects it also has three more library projects.  All .NET 5.0.  Everything works in Visual Studio 2019. The solution builds in 5 seconds.
When I open it in Visual studio 2022 release (and I've noticed that behavior in the preview), the same solution hangs for about a minute during the build. "dotnet build" from the command line - 5 seconds . When I build library projects individually - compile time is almost instant.   When I change project bindings to .NET 6  - the build is under 5 seconds. Back to .NET 5 - a minute.
I cannot upgrade to .NET 6 at the moment. 
Please advise.
Thanks.

Project Performance Summary:
5>        4 ms  I:\Wasm.Utils.csproj   5 calls
5>        4 ms  I:\Wasm.Contracts.csproj   5 calls
5>       10 ms  I:.\TrialApp.Data.csproj   5 calls
5>       24 ms  I:\TrialApp.Web.Client.csproj   5 calls
5>    42015 ms  I:\TrialApp.Web.Server.csproj   1 calls
5>
5>Target Performance Summary:
5>        0 ms  _CollectTargetFrameworkForTelemetry        1 calls
5>        0 ms  ResolveRazorComponentInputs                1 calls
5>        0 ms  _ComputeCssScope                           1 calls
5>        0 ms  _ResolveCssScopes                          1 calls
5>        0 ms  PrepareForRazorComponentGenerate           1 calls
5>        0 ms  _RemoveRazorDeclartionsFromCompile         1 calls
5>        0 ms  RazorComponentGenerateCore                 1 calls
5>        0 ms  RazorComponentGenerate                     1 calls
5>        0 ms  GenerateCompiledExpressionsTempFile        1 calls
5>        0 ms  _GenerateRazorAssemblyInfo                 1 calls
5>        0 ms  _BeforeVBCSCoreCompile                     1 calls
5>        0 ms  AddImplicitDefineConstants                 1 calls
5>        0 ms  _ComputeSkipAnalyzers                      1 calls
5>        0 ms  PreXsdCodeGen                              1 calls
5>        0 ms  _ReportUpgradeNetAnalyzersNuGetWarning     1 calls
5>        0 ms  AfterCompile                               1 calls
5>        0 ms  ResolveRazorConfiguration                  1 calls
5>        0 ms  AfterRebuild                               1 calls
5>        0 ms  GenerateAssemblyInfo                       1 calls
5>        0 ms  CoreGenerateAssemblyInfo                   1 calls
5>        0 ms  BeforeResGen                               1 calls
5>        0 ms  CoreResGen                                 1 calls
5>        0 ms  AfterResGen                                1 calls
5>        0 ms  ResGen                                     1 calls
5>        0 ms  PrepareResources                           1 calls
5>        0 ms  TypeScriptDeleteOutputFromOtherConfigs     1 calls
5>        0 ms  GetTypeScriptOutputForPublishing           1 calls
5>        0 ms  Compile                                    1 calls
5>        0 ms  SetWin32ManifestProperties                 1 calls
5>        0 ms  GenerateMSBuildEditorConfigFileShouldRun   1 calls
5>        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls
5>        0 ms  GenerateTargetFrameworkMonikerAttribute    1 calls
5>        0 ms  GetAssemblyVersion                         1 calls
5>        0 ms  InitializeSourceControlInformation         1 calls
5>        0 ms  AddSourceRevisionToInformationalVersion    1 calls
5>        0 ms  GetAssemblyAttributes                      1 calls
5>        0 ms  _GenerateCompileInputs                     1 calls
5>        0 ms  PrepareResourceNames                       1 calls
5>        0 ms  _GenerateSatelliteAssemblyInputs           1 calls
5>        0 ms  GetTargetPathWithTargetPlatformMoniker     1 calls
5>        0 ms  _RazorPrepareForRun                        1 calls
5>        0 ms  _IncludeGeneratedStaticWebAssetsManifest   1 calls
5>        0 ms  _RazorGetCopyToOutputDirectoryItems        1 calls
5>        0 ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   1 calls
5>        0 ms  GetTypeScriptCopyToOutputDirectoryItems    1 calls
5>        0 ms  AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects   1 calls
5>        0 ms  _CopySourceItemsToOutputDirectory          1 calls
5>        0 ms  _ComputeUserRuntimeAssemblies              1 calls
5>        0 ms  ComputeDependencyFileCompilerOptions       1 calls
5>        0 ms  _ResolveRazorTargetPath                    1 calls
5>        0 ms  PrepareForRun                              1 calls
5>        0 ms  CoreBuild                                  1 calls
5>        0 ms  AfterBuild                                 1 calls
5>        0 ms  Build                                      1 calls
5>        0 ms  CleanupEmptyRefsFolder                     1 calls
5>        0 ms  RazorCompile                               1 calls
5>        0 ms  GenerateRazorTargetAssemblyInfo            1 calls
5>        0 ms  ResolveRazorCompileInputs                  1 calls
5>        0 ms  _ResolveRazorGenerateOutputs               1 calls
5>        0 ms  _ResolveScopedCssOutputs                   1 calls
5>        0 ms  _GenerateScopedCssFiles                    1 calls
5>        0 ms  ResolveStaticWebAssetsConfiguration        1 calls
5>        0 ms  _AddGeneratedScopedCssFiles                1 calls
5>        0 ms  ResolveCurrentProjectStaticWebAssetsInputs   1 calls
5>        0 ms  _AddGeneratedScopedCssFilesForReference    1 calls
5>        0 ms  _BlazorWasmReplaceBundle                   1 calls
5>        0 ms  CreateSatelliteAssemblies                  1 calls
5>        0 ms  _ComputeCssBundles                         1 calls
5>        0 ms  ResolveStaticWebAssetsInputs               1 calls
5>        0 ms  BundleScopedCssFiles                       1 calls
5>        0 ms  _PrepareForScopedCss                       1 calls
5>        0 ms  _PrepareForStaticWebAssets                 1 calls
5>        0 ms  AssignRazorGenerateTargetPaths             1 calls
5>        0 ms  _RazorEnsureCompiled                       1 calls
5>        0 ms  PrepareForRazorGenerate                    1 calls
5>        0 ms  _AddScopedCssBundles                       1 calls
5>        0 ms  CreateCustomManifestResourceNames          1 calls
5>        0 ms  BeforeCompile                              1 calls
5>        0 ms  Rebuild                                    1 calls
5>        0 ms  ResolveRazorGenerateInputs                 1 calls
5>        0 ms  GetReferenceAssemblyPaths                  1 calls
5>        0 ms  GetFrameworkPaths                          1 calls
5>        0 ms  BuildOnlySettings                          1 calls
5>        0 ms  BeforeBuild                                1 calls
5>        0 ms  CleanXsdCodeGen                            1 calls
5>        0 ms  Clean                                      1 calls
5>        0 ms  BeforeRebuild                              1 calls
5>        0 ms  BeforeClean                                1 calls
5>        0 ms  _DefaultMicrosoftNETPlatformLibrary        1 calls
5>        0 ms  CheckFileSystemCaseSensitive               1 calls
5>        0 ms  _ComputePackageReferencePublish            1 calls
5>        0 ms  AfterClean                                 1 calls
5>        0 ms  CleanPublishFolder                         1 calls
5>        0 ms  CleanReferencedProjects                    1 calls
5>        0 ms  _CheckForTransitiveWindowsDesktopDependencies   1 calls
5>        0 ms  PrepareProjectReferences                   1 calls
5>        0 ms  AddTransitiveFrameworkReferences           1 calls
5>        0 ms  _RemoveComponentAnalyzer                   1 calls
5>        0 ms  GetTargetFrameworks                        2 calls
5>        0 ms  IncludeTransitiveProjectReferences         1 calls
5>        0 ms  ResolvePackageDependenciesForBuild         1 calls
5>        0 ms  _SdkBeforeRebuild                          1 calls
5>        0 ms  _AddOutputPathToGlobalPropertiesToRemove   1 calls
5>        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls
5>        0 ms  CopyAdditionalFiles                        1 calls
5>        0 ms  ExpressionBuildExtension                   1 calls
5>        0 ms  ValidationExtension                        1 calls
5>        0 ms  _CheckForUnsupportedHostingUsage           1 calls
5>        0 ms  ResolveReferences                          1 calls
5>        0 ms  AfterResolveReferences                     1 calls
5>        0 ms  BeforeResolveReferences                    1 calls
5>        0 ms  _ChooseAppHost                             1 calls
5>        0 ms  _GetProjectJsonPath                        1 calls
5>        0 ms  _CheckForUnsupportedCppNETCoreVersion      1 calls
5>        0 ms  _GetAppHostPaths                           1 calls
5>        0 ms  _CheckForObsoleteDotNetCliToolReferences   1 calls
5>        0 ms  CollectPackageReferences                   1 calls
5>        0 ms  EnableIntermediateOutputPathMismatchWarning   1 calls
5>        0 ms  ResolveSDKReferences                       1 calls
5>        0 ms  _ComputeNETCoreBuildOutputFiles            1 calls
5>        0 ms  GetNativeManifest                          2 calls
5>        1 ms  RazorGenerate                              1 calls
5>        1 ms  ValidateCommandLineProperties              1 calls
5>        1 ms  ExpandSDKReferences                        1 calls
5>        1 ms  CoreGenerateRazorTargetAssemblyInfo        1 calls
5>        1 ms  IncrementalClean                           1 calls
5>        1 ms  TypeScriptDeleteCompilerOutput             1 calls
5>        1 ms  CheckForImplicitPackageReferenceOverrides   1 calls
5>        1 ms  PrepareForBuild                            1 calls
5>        1 ms  GenerateMSBuildEditorConfigFileCore        1 calls
5>        1 ms  SplitResourcesByCulture                    1 calls
5>        1 ms  DesignTimeXamlMarkupCompilation            1 calls
5>        1 ms  _CreateRazorAssemblyInfoInputsCacheFile    1 calls
5>        1 ms  PrepareForRazorCompile                     1 calls
5>        1 ms  AssignTargetPaths                          1 calls
5>        1 ms  ResolveLockFileAnalyzers                   1 calls
5>        1 ms  FindConfigFiles                            1 calls
5>        1 ms  AddGlobalAnalyzerConfigForPackage_MicrosoftCodeAnalysisNetAnalyzers   1 calls
5>        1 ms  _PrepareForBundling                        1 calls
5>        1 ms  _ResolveMvcAssemblyAttributes              1 calls
5>        1 ms  GenerateMSBuildEditorConfigFile            1 calls
5>        1 ms  ValidateExecutableReferences               1 calls
5>        1 ms  _CheckForCompileOutputs                    1 calls
5>        1 ms  GetRazorTargetAssemblyAttributes           1 calls
5>        1 ms  _CheckForLanguageAndFeatureCombinationSupport   1 calls
5>        1 ms  _ResolveGeneratedRazorCompileInputs        1 calls
5>        1 ms  ReportTypeScriptVersion                    1 calls
5>        1 ms  _SplitProjectReferencesByFileExistence     1 calls
5>        1 ms  GetTargetFrameworksWithPlatformForSingleTargetFramework   2 calls
5>        1 ms  ApplyImplicitVersions                      1 calls
5>        1 ms  AssignProjectConfiguration                 1 calls
5>        1 ms  _SetEmbeddedWin32ManifestProperties        1 calls
5>        1 ms  _IncludeDebugProxyBinariesAsContent        1 calls
5>        1 ms  _CheckForUnsupportedAppHostUsage           1 calls
5>        1 ms  GetCopyToOutputDirectoryXamlAppDefs        1 calls
5>        1 ms  _CoreGenerateRazorAssemblyInfo             1 calls
5>        1 ms  _GetCopyToOutputDirectoryItemsFromThisProject   1 calls
5>        1 ms  ResolveScopedCssInputs                     1 calls
5>        1 ms  UpdateAspNetToFrameworkReference           1 calls
5>        1 ms  _SdkBeforeClean                            1 calls
5>        1 ms  GetTargetPath                              1 calls
5>        1 ms  _CreateRazorTargetAssemblyInfoInputsCacheFile   1 calls
5>        1 ms  _HashRazorGenerateInputs                   1 calls
5>        2 ms  _CollectAllScopedCssAssets                 1 calls
5>        2 ms  GenerateNETCompatibleDefineConstants       1 calls
5>        2 ms  _GenerateRuntimeConfigurationFilesInputCache   1 calls
5>        2 ms  ResolveLockFileCopyLocalFiles              1 calls
5>        2 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
5>        2 ms  _GetRestoreProjectStyle                    1 calls
5>        3 ms  _RazorCopyFilesToOutputDirectory           1 calls
5>        3 ms  CheckForDuplicateItems                     1 calls
5>        3 ms  ResolveLockFileReferences                  1 calls
5>        3 ms  _BlockWinMDsOnUnsupportedTFMs              1 calls
5>        4 ms  CopyFilesToOutputDirectory                 1 calls
5>        4 ms  _DiscoverMvcApplicationParts               1 calls
5>        4 ms  ResolveAssemblyReferenceRazorGenerateInputs   1 calls
5>        4 ms  ResolveFrameworkReferences                 1 calls
5>        5 ms  ProcessFrameworkReferences                 1 calls
5>        6 ms  _CopyOutOfDateSourceItemsToOutputDirectory   1 calls
5>        7 ms  GenerateBuildRuntimeConfigurationFiles     1 calls
5>        7 ms  _GenerateCompileDependencyCache            1 calls
5>        9 ms  GenerateStaticWebAssetsManifest            1 calls
5>       10 ms  GetCurrentProjectStaticWebAssets           1 calls
5>       10 ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   1 calls
5>       11 ms  _ComputeReferenceAssemblies                1 calls
5>       12 ms  GetCopyToOutputDirectoryItems              1 calls
5>       12 ms  _CleanGetCurrentAndPriorFileWrites         1 calls
5>       13 ms  _GetProjectReferenceTargetFrameworkProperties   1 calls
5>       15 ms  CreateGeneratedAssemblyInfoInputsCacheFile   1 calls
5>       16 ms  ResolveTargetingPackAssets                 1 calls
5>       19 ms  _CreateAppHost                             1 calls
5>       21 ms  ResolveProjectReferences                   1 calls
5>       22 ms  CoreClean                                  1 calls
5>       25 ms  GenerateBuildDependencyFile                1 calls
5>       26 ms  _HandlePackageFileConflicts                1 calls
5>       28 ms  FindReferenceAssembliesForReferences       1 calls
5>       29 ms  _CreateStaticWebAssetsInputsCacheFile      1 calls
5>       35 ms  ResolvePackageAssets                       1 calls
5>       37 ms  _CopyFilesMarkedCopyLocal                  1 calls
5>       64 ms  RazorCoreCompile                           1 calls
5>       72 ms  CoreCompile                                1 calls
5>       97 ms  ResolveReferencedProjectsStaticWebAssets   1 calls
5>      185 ms  ResolveAssemblyReferences                  1 calls
5>    20272 ms  RazorCoreGenerate                          1 calls
5>    20865 ms  ResolveTagHelperRazorGenerateInputs        1 calls
5>
5>Task Performance Summary:
5>        0 ms  AllowEmptyTelemetry                        1 calls
5>        0 ms  CombineXmlElements                         2 calls
5>        0 ms  FindAppConfigFile                          1 calls
5>        0 ms  AssignCulture                              1 calls
5>        0 ms  ResolveNonMSBuildProjectOutput             1 calls
5>        0 ms  GetFrameworkPath                           1 calls
5>        0 ms  GenerateMSBuildEditorConfig                1 calls
5>        0 ms  GetAssemblyVersion                         1 calls
5>        0 ms  CheckFileSystemCaseSensitive               1 calls
5>        0 ms  WriteCodeFragment                          3 calls
5>        0 ms  RemoveDuplicates                           3 calls
5>        0 ms  FindInList                                 1 calls
5>        0 ms  DiscoverDefaultScopedCssItems              1 calls
5>        0 ms  ComputeCssScope                            1 calls
5>        0 ms  ApplyCssScopes                             1 calls
5>        0 ms  RemoveDir                                  2 calls
5>        0 ms  CheckForImplicitPackageReferenceOverrides   1 calls
5>        0 ms  CopyRefAssembly                            1 calls
5>        0 ms  FindConfigFiles                            1 calls
5>        1 ms  ResolveAllScopedCssAssets                  1 calls
5>        1 ms  ReadLinesFromFile                          2 calls
5>        1 ms  GetReferenceNearestTargetFrameworkTask     1 calls
5>        1 ms  Touch                                      4 calls
5>        1 ms  MakeDir                                    3 calls
5>        1 ms  JoinItems                                  1 calls
5>        1 ms  ValidateExecutableReferences               1 calls
5>        1 ms  CheckForDuplicateFrameworkReferences       1 calls
5>        1 ms  FormatLocalizedString                      1 calls
5>        1 ms  CombineTargetFrameworkInfoProperties       2 calls
5>        1 ms  ApplyImplicitVersions                      1 calls
5>        1 ms  AssignProjectConfiguration                 1 calls
5>        1 ms  ResolveFrameworkReferences                 1 calls
5>        1 ms  GenerateV1StaticWebAssetsManifest          1 calls
5>        1 ms  AssignTargetPath                          10 calls
5>        1 ms  CheckIfPackageReferenceShouldBeFrameworkReference   2 calls
5>        1 ms  FindUnderPath                              7 calls
5>        2 ms  CheckForDuplicateItems                     3 calls
5>        2 ms  ValidateStaticWebAssetsUniquePaths         1 calls
5>        2 ms  ResolveAppHosts                            1 calls
5>        2 ms  ProcessFrameworkReferences                 1 calls
5>        2 ms  Message                                    5 calls
5>        2 ms  GetRestoreProjectStyleTask                 1 calls
5>        3 ms  GetPackageDirectory                        8 calls
5>        3 ms  CheckForUnsupportedWinMDReferences         1 calls
5>        3 ms  WriteLinesToFile                           9 calls
5>        4 ms  FindAssembliesWithReferencesTo             1 calls
5>        6 ms  GenerateRuntimeConfigurationFiles          1 calls
5>        9 ms  ConvertToAbsolutePath                      1 calls
5>       11 ms  CallTarget                                 3 calls
5>       15 ms  ResolveTargetingPackAssets                 1 calls
5>       17 ms  Hash                                       7 calls
5>       19 ms  CreateAppHost                              1 calls
5>       19 ms  ResolvePackageFileConflicts                1 calls
5>       20 ms  Delete                                     4 calls
5>       24 ms  GenerateDepsFile                           1 calls
5>       35 ms  ResolvePackageAssets                       1 calls
5>       44 ms  Copy                                       6 calls
5>      136 ms  Csc                                        2 calls
5>      136 ms  MSBuild                                    5 calls
5>      185 ms  ResolveAssemblyReference                   1 calls
5>    20271 ms  SdkRazorGenerate                           1 calls
5>    20864 ms  SdkRazorTagHelper                          1 calls
5>
5>Build succeeded.
5>    0 Warning(s)
5>    0 Error(s)
5>
5>Time Elapsed 00:00:42.01
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========

---
#### Feedback Bot on 11/10/2021, 07:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Closing as 5.0 is out of support already.
