### ISSUE TITLE
Blazor Server: Websocket problems with WAN-optimization / change port for SignalR / websocket connection

### ISSUE THREAD

**Issue by heckradr** [dotnet/aspnetcore#38472]
### Problem
At one of our customers we have a problem running a blazor server app when accessing the app from a different location as the server. We found already the cause at the WAN optimization (riverbed steelheads). With enabled latency optimization the websocket is unable to connect and the application falls back to long-polling mode. Maybe it's problematically for the steelhead if binary and HTTP traffic will use the same port. If I connect the client to the network at the same location as the server the problem is gone. So this is no client related issue / no browser problem. 

Browser output with enabled SignalR debugging:

![WebsocketError](https://user-images.githubusercontent.com/48717990/142219806-03a3d1e2-b65c-410c-ba68-0168cc6b45f4.png)

### Feature request
We could solve the issue with a configuration change in the steelheads (add an exception for the corresponding server). I don't like this solution because this will affect also other running web-applications on port 80 at the same system.
I'm wondering if there is a possiblity to change the port for the SignalR connection? I found no easy way for that. Maybe a little bit javascript can do the trick? A simple config option via the Startup.cs would be ideal. So I would be able to run the normal HTTP traffic over port 80 with enabled optimization and another port (not optimized) for the SignalR / websocket traffic. An azure solution is not acceptable for the customer, the app must be hosted on-premise.

**Comment by BrennanConroy** [comment]
> So I would be able to run the normal HTTP traffic over port 80 with enabled optimization and another port (not optimized) for the SignalR

You can listen on multiple ports by configuring the server urls. Then point your SignalR clients at the secondary port and other traffic at the original port.
https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0#server-urls

**Comment by adityamandaleeka** [comment]
@heckradr If you want to constrain traffic on an endpoint, you can also use host matching as described here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#host-matching-in-routes-with-requirehost
