### ISSUE TITLE
unsubscribe message or remove handlers in signalr?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38489]
I can not unsubscribe a message or remove the handlers right?

let me explain:

in page! and pageB have the code:

```
connection.On<byte>("GetGroups",(response)=>
{
///....
})

```
But If I open pageA and pageB only 1 will get the response.

what I want is to have a function that can unsbscribe the message.

**Comment by davidfowl** [comment]
On returns an IDisposable. You can dispose if you want to unregister the event.

**Comment by mcguu** [comment]
@davidfowl  but in blazor webassembly there is no ON Page closed function right?

So I do not know when to dispose it unless in other pages

**Comment by davidfowl** [comment]
You can make your component implement IDisposable and dispose your handlers in there.

**Comment by mcguu** [comment]
@davidfowl  I am a newbie can you tell me how to implement IDisposable in a components?

I can not find the method .

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-disposal-with-idisposable-and-iasyncdisposable
