### ISSUE TITLE
[BUG]: Reiterate. <PageTitle></PageTitle> not works in WebAssemblyPrerendered mode

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/aspnetcore#38484]
This is reiteration of #38192

## Describe the bug
When you using WebAssemblyPrerendered mode
```razor
<component type="typeof(Client.App)" render-mode="WebAssemblyPrerendered" />
```
for app any change of head outlet wont work.

It seems that head content is changed by javascript call on client side only after app loaded and run.
It dosen't work when you trying to prerender on server. (check #38192)

## To Reproduce
https://github.com/ParadiseFallen/WasmBlazorPrerendered
Just run Host project. look at Client project.
open link/counter
after some time title will update to "Counter 0"

Open postman
Send [GET] link/counter
In markup title is Client

## Exceptions (if any)
no

## Further technical details
.net 6
VS 2022 Current

**Comment by TanayParikh** [comment]
Closing out this issue, duplicating against https://github.com/dotnet/aspnetcore/issues/38192 which I've re-opened.
