### ISSUE TITLE
Latest .NET SDK 7.0.100-alpha.1.21558.2 not found. Blocking development

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#38485]
Update SDK PR https://github.com/dotnet/aspnetcore/pull/38417

![image](https://user-images.githubusercontent.com/17148381/142353018-8ba3e064-f6fb-4f8b-9bd7-f9ae44b290fb.png)

**Comment by TanayParikh** [comment]
Hey @ShreyasJejurkar, I'm having the same issue. You can revert the commit 0d9d51daf89e83f52fadcbae9b3b0a07c2852a04 locally and be good to go! This happens occasionally, I believe it's something to do with how the SDK propagates throughout the infra.

**Comment by ShreyasJejurkar** [comment]
@TanayParikh Hahaha. Yeah, that can be done. But why does PR even get merged if the SDK failed to download in the first place itself! 


cc @pranavkm

**Comment by ShreyasJejurkar** [comment]
Interestingly the CI also fetched the SDK from the same location with the `dotnet-install` script, it succeeded there, but it's failing on our local machine.

https://dev.azure.com/dnceng/public/_build/results?buildId=1470678&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=2f754404-b52c-5665-45a1-cdacbbf9ac37&l=38
