### ISSUE TITLE
Server component not working

### ISSUE THREAD

**Issue by Tarakeswarab** [dotnet/aspnetcore#38496]
### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

**Comment by javiercn** [comment]
@Tarakeswarab thanks for contacting us.

It's not clear to us what you issue is, could you please fill in more details about what is not working for you?

**Comment by javiercn** [comment]
Closing as we don't have actionable information. Please provide additional details and we'll re-open the issue.

**Comment by Tarakeswarab** [comment]
While calling the fetch-data from for weather forecast it is not working. Through the .Net application able to display the weather forecast. After npm start it will provide the URL. Using that URL weather forecast is not working.

**Comment by javiercn** [comment]
@Tarakeswarab thanks for the additional information.

Can you provide a minimal repro project as a public github repository so that we can make progress investigating this issue?
