### ISSUE TITLE
Razor should have it’s own SFC

### ISSUE THREAD

**Issue by jakenuts** [dotnet/aspnetcore#38499]
The utility of a single file that joins markup, scripts and styling for a component is undeniable. While Razor supports this the tooling to extract, bundle and async/import them when necessary is lacking. 

I'd like to be able to build a page or component with all it's related content together and have a build tool that, like Webpack can isolate, bundle and provide them when that page/component is loaded.

**Comment by javiercn** [comment]
@jakenuts thanks for contacting us.

We already support CSS isolation and JS isolation through [Scoped CSS](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0) and [JS modules](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#collocate-javascript-files-with-pages-views-and-components). 

We already bundle and auto-import the CSS and for JS it is easy to achieve this behavior in your own component base class. For bundling JS, you can integrate a JS bundling pipeline into the build as described [here](https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/).
