### ISSUE TITLE
Blazor lazy loading and plugin architecture

### ISSUE THREAD

**Issue by vrassouli** [dotnet/aspnetcore#38497]
### Is your feature request related to a problem? Please describe.
In a blazor web assembly application, in order to be able to load an assembly at runtime, you need to be aware of the assembly at compile time, and need to mark the assembly with BlazorWebAssemblyLazyLoad at your csproj file.

### Describe the solution you'd like
It would be great if we were able to just request for an assembly, which the project has no reference to it at compile time.

### Additional context
For developing an enterprise application, with plugin architecture, which loads already built assemblies into the runtime context and consumes it with the shared contracts, it's required to be able to request the assemblies from client to the server, at runtime.

I couldn't figure out any solution for such scenario.

Thanks for any help

**Comment by javiercn** [comment]
@vrassouli thanks for contacting us.

Unfortunately that's not something we plan to pursue. Loading assemblies at runtime without compile-time knowledge interferes in a fundamental way with features like linking, and the result would be in most cases a non-working app as dependencies for the runtime loaded assemblies will be linked out from the application.

You can create your own lazy loading scheme by fetching the dlls and loading them manually. Other frameworks like Octane, I believe do it this way. That said, this is not something we plan to work on for the reasons stated above.
