### ISSUE TITLE
Describe that ResponseCachingOptions takes Bytes as input. 

### ISSUE THREAD

**Issue by Strepto** [dotnet/aspnetcore#38490]
https://github.com/dotnet/aspnetcore/blob/f993b272df3187500f5afef52dc9a726118cfbc0/src/Middleware/ResponseCaching/src/ResponseCachingOptions.cs#L13-L24

### Is your feature request related to a problem? Please describe.

I was trying to use the ResponseCaching but could not without inspecting the source find out which metric was used for the SizeLimit. It says taht the default is 100mb, and I would think taht a value of 100 == 100mb then?

### Describe the solution you'd like

Update the docs describing that this takes "bytes" as input

### Additional context

![image](https://user-images.githubusercontent.com/3185998/142379309-9ed9f9d4-d981-4cce-948c-41f41a823ba0.png)

**Comment by BrennanConroy** [comment]
> Update the docs describing that this takes "bytes" as input

The docs do say the size limit is bytes.

"The size limit for the response cache middleware in **bytes**."

**Comment by Strepto** [comment]
I'm obviously blind. 👀

Consider this resolved...
