### ISSUE TITLE
Reloading(forceReload:true) doesn't refill "offline-cache-..." if empty/absent

### ISSUE THREAD

**Issue by thepra** [dotnet/aspnetcore#38495]
### Describe the bug
I noticed that despite che cache named `blazor-resources-/` is always refilled if it was previously emptied or absent when I go with a simple:
```C#
Navigation.NavigateTo(Navigation.Uri, forceLoad: true);
```
this doesn't happen with the cache behind `offline-cache-<hash>`.
Is this supposed to work like this, half way?
And if true is there any way to force the refill of the `offline-cache-<hash>`?

### To Reproduce
Setup a js function to call from C# like this:
```js
window.clearCache = async () => {
    const cachesNames = await caches.keys()
    for (let i = 0; i < cachesNames.length; i++)
        await caches.delete(cachesNames[i])
}
```
after running it perform a forced reload of the page with:
```C#
Navigation.NavigateTo(Navigation.Uri, forceLoad: true);
```

### Further technical details
- ASP.NET Core version: 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 Community
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by javiercn** [comment]
@thepra thanks for contacting us.

Can you clarify a bit the scenario? The local cache Blazor uses is not random, it's based on the SHA256 hash for the dll, so if that changes a new entry will be added.

**Comment by thepra** [comment]
@javiercn yes, that hash string, my bad for calling it `random`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and clarification. After some discussion we've decided that this is not something we will do in the framework. However Service Worker caching is controlled in the service worker and you can control it with your own code.
