### ISSUE TITLE
Blazor Server Side - WebSocket closed with status code: 1006 ()

### ISSUE THREAD

**Issue by endstreet** [dotnet/aspnetcore#38492]
On IISExpress/dev environment I have NO errors. I find no way to force this error either. I can load a page > 20mb without errors, way more than will ever be hit on the published (IIS) site,
On IIS I have  WebSocket closed with status code: 1006 ()  error. (which is then followed by another 8 attempts to reload the page with the same result by signalr default config. )
The application has many routes that all work fine (and fast) this only happens when I am trying to load a large page (> +-10mb)
The error occurs after 16 seconds of waiting for the page to load. 

The error happens during load of a collection of cards:

    @foreach (var file in sheets)
    {
        <FileCoverSheet BrmBarCode="@file.BrmNo"></FileCoverSheet> //Card layout for item
    }

If the Count() of sheets exceed about 60 the error occurs. There are no errors in the Component or in the data.

I have spent 3 days already and cannot find the root of the difference between IISExpress and IIS to cause this error.

I have tried:
Different versions of IIS on different servers.
Fiddling with IIS timeouts has no effect.
ApplicationPool Privatememory is infinite.

Complete code for offending page:

@page "/coversheets/{BoxNo}"
@layout PrintLayout

@inject BRMDbService db
@inject BarCodeService bcService
@inject IJSRuntime Js

<div>
    <button class="btn btn-primary active" @onclick="btnBack_Click">Back</button>
    <button class="btn btn-primary active" @onclick="btnPrint_Click">Print</button>
</div>
@if(sheets == null)
{
    <p>Loading...</p>
}
else
{
    @foreach (var file in sheets)
    {
        <FileCoverSheet BrmBarCode="@file.BrmNo"></FileCoverSheet>
        **WebSocket closed with status code: 1006 () here after 16 seconds**
    }
}

@code {

    [Parameter]
    public string BoxNo { get; set; }
    public List<ReboxListItem> sheets;

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(200);
        sheets = await db.GetAllFilesByBoxNo(BoxNo); **--Loads in<1sec**
    }

    private async Task btnPrint_Click()
    {

        await Js.InvokeVoidAsync("printPage");
    }

    private void btnBack_Click()
    {
        Js.InvokeVoidAsync("window.close");
    }
    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        Task.Delay(20);
        StateHasChanged();
        return base.OnAfterRenderAsync(firstRender);
    }

}

**Comment by endstreet** [comment]
else
{
    @foreach (var file in sheets)
    {
        <FileCoverSheet BrmBarCode="@file.BrmNo"></FileCoverSheet>
        **WebSocket closed with status code: 1006 () here after 16 seconds**
    }
}

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This has already been discussed in #21546
