### ISSUE TITLE
Blazor JSInterop failure/exception not reported in Blazor app

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#38502]
### Describe the bug
I have a working application that is experiencing a JSInterop exception. That exception is not surfaced making it very difficult to find the problem in the app.

### To Reproduce

This repo is being used to report 2 separate issues. Use button #2, see the same developer exception as in https://github.com/dotnet/aspnetcore/issues/38501, but wait out the minute for the exception to be thrown and note that no exception is evident.

The repo is https://github.com/OptimiumHealth/BlazorJSInteropApp

### Exceptions (if any)

None, but I want one!

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

```
C:\Solutions\TemporarySolutions\BlazorJSInteropApp>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\TemporarySolutions\BlazorJSInteropApp>
```

**Comment by TanayParikh** [comment]
Hello, thanks for contacting us. I'm not sure I follow. How does this differ from https://github.com/dotnet/aspnetcore/issues/38501. What's the difference between `internalClick1` and `internalClick2`?

**Comment by MarkStega** [comment]
internalClick2 does not have a try/catch block and the exception is 'silent' which makes it almost impossible to find in a real application.

**Comment by TanayParikh** [comment]
> internalClick2 does not have a try/catch block and the exception is 'silent' which makes it almost impossible to find in a real application.
> 
> I commented in #38501 that "OK, the wrong call is being used, but why does it take a full minute for the exception?"

Just to confirm, you're saying that the exception isn't thrown even after a full minute, and the circuit remains active?

**Comment by MarkStega** [comment]
Yes, the exception is not thrown and the circuit remains active

**Comment by MarkStega** [comment]
See #38501

This was fixed when tested with DN7.preview 7
