### ISSUE TITLE
Performance issue: Why Blazor Web assembly loop is far slower than Javascript?

### ISSUE THREAD

**Issue by madnik7** [dotnet/aspnetcore#38505]
I have created two simple loops in Javascript and Blazor WebAssembly. I was going to love Blazor and had expected web assembly to be faster because it was compiled and optimized, but it was far slower than Javascript. I used .NET 6 Blazor web assembly. Did I do something wrong or Blazor is not designed for this scenario at all?

**Javascript:** 3 seconds

**Blazor:** 95 seconds

Javascript:
```javascript
function Foo() 
{
  let fruit = [];
  for (var i = 0; i < 5000000; i++) {
    fruit[i] = "zzzz" + i.toString() + "yyy" + i.toString() +
      i.toString() + i.toString() + i.toString();
  }

  let counter = 0;
  for (var j = 0; j < fruit.length; j++)
    if (fruit[j].indexOf("111") > 0)
      counter++;
  console.log(counter);
}
```

Blazor Web assembly:
```c#
void Foo()
{
    DateTime dateTime = DateTime.Now;
    var items = new string[5000000];
    for (var i=0; i<items.Length; i++)
        items[i] = "some string some string 111" + i.ToString();

    var counter = 0;
    for (var i = 0; i < items.Length; i++)
        if (items[i].IndexOf("111") > 0)
            counter++;
}
```

**Comment by javiercn** [comment]
@madnik7 thanks for contacting us.

Are you running the published Ahead of Time compiled app in Release mode?

**Comment by madnik7** [comment]
Thank you for replying.
No, it was off. But now I have turned it on, but the performance is still the same. I have also created a new Blazor project with VS2022 .NET 6 default template and turned AOT on in release mode, then run it, but the performance is still the same. Tested on the latest version of EDGE and Chrome.
![image](https://user-images.githubusercontent.com/3189803/142500160-6f821f10-90f0-4e2a-ab43-a4fb570e0933.png)

It looks like any string manipulation or compression drastically degrade the performance. Is it normal?

**Comment by TanayParikh** [comment]
How are you measuring the time for JS / Blazor. It's not immediately clear based on the snippet you provided. Also, just confirming you do _NOT_ have the debugger attached, correct?

**Comment by madnik7** [comment]
I use a simple timer and alert to measure time. Also I "start without debugging" and the browser console is off
```c#
    private void Foo()
    {
        DateTime dateTime = DateTime.Now;
        var items = new string[5000000];
        for (var i = 0; i < items.Length; i++)
            items[i] = "some string some string 111" + i.ToString();

        var counter = 0;
        for (var i = 0; i < items.Length; i++)
            if (items[i].IndexOf("111") > 0)
                counter++;
        
        JsRuntime.InvokeVoidAsync("alert", (DateTime.Now - dateTime).TotalSeconds.ToString()); // Alert
    }
```

![image](https://user-images.githubusercontent.com/3189803/142503778-3583e0ee-3ca2-437e-bf0e-4f3fc679a7a9.png)

**Comment by azbo** [comment]
这个差距有点大
![image](https://user-images.githubusercontent.com/5110699/142535186-8cc0d5d1-d987-4e68-8df4-808f090a6689.png)

![image](https://user-images.githubusercontent.com/5110699/142534689-8adb490f-177e-4921-8b3e-4c085571557b.png)

**Comment by azbo** [comment]
65 times the gap in my machine

**Comment by madnik7** [comment]
I had to publish the project to get benefits from AOT. Now the performance gets 5x faster, but still, Blazor code is almost 3x slower than javascript. 

**Javascript**: 3 seconds
**Blazor**: 10 seconds

I really like Blazor, but the performance is disappointing. I've come from VueJS, Now I can completely feel the amount of lag in my Blazor project even though my project is very small now. I hope there is a solution for this performance.

**Comment by azbo** [comment]
50000
.net core console:1.65s
java:0.27s
javascript:0.203s



.net core console
![image](https://user-images.githubusercontent.com/5110699/142553542-b8832b2c-39ca-4b53-9273-b783bf13b95e.png)
![image](https://user-images.githubusercontent.com/5110699/142553521-d482776f-e573-4178-bc46-8904bd1e7b63.png)

java:
![image](https://user-images.githubusercontent.com/5110699/142553599-f5a135f6-bd6c-4467-8f73-459e64f9c846.png)

javascript:
![image](https://user-images.githubusercontent.com/5110699/142553687-7394e26e-b48d-4b53-9b0e-a5cab4421336.png)

**Comment by azbo** [comment]
> 我使用一个简单的计时器和警报来测量时间。此外， 我 "开始不调试" 和浏览器控制台关闭
> 
> ```cs
>     private void Foo()
>     {
>         DateTime dateTime = DateTime.Now;
>         var items = new string[5000000];
>         for (var i = 0; i < items.Length; i++)
>             items[i] = "some string some string 111" + i.ToString();
> 
>         var counter = 0;
>         for (var i = 0; i < items.Length; i++)
>             if (items[i].IndexOf("111") > 0)
>                 counter++;
>         
>         JsRuntime.InvokeVoidAsync("alert", (DateTime.Now - dateTime).TotalSeconds.ToString()); // Alert
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/3189803/142503778-3583e0ee-3ca2-437e-bf0e-4f3fc679a7a9.png)



> 我在 Javascript 和布拉佐网络组装中创建了两个简单的循环。我本想爱布拉佐尔，并期望网络组装更快，因为它是汇编和优化，但它比Javascript慢得多。我用. NET 6 布拉佐尔网络组装。我做错了什么还是布拉佐根本不是为这种情况设计的？
> 
> **爪哇脚本：3**秒
> 
> **布拉佐尔：** 95 秒
> 
> 爪哇脚本：
> 
> ```js
> function Foo() 
> {
>   let fruit = [];
>   for (var i = 0; i < 5000000; i++) {
>     fruit[i] = "zzzz" + i.toString() + "yyy" + i.toString() +
>       i.toString() + i.toString() + i.toString();
>   }
> 
>   let counter = 0;
>   for (var j = 0; j < fruit.length; j++)
>     if (fruit[j].indexOf("111") > 0)
>       counter++;
>   console.log(counter);
> }
> ```
> 
> 布拉佐尔网络装配：
> 
> ```cs
> void Foo()
> {
>     DateTime dateTime = DateTime.Now;
>     var items = new string[5000000];
>     for (var i=0; i<items.Length; i++)
>         items[i] = "some string some string 111" + i.ToString();
> 
>     var counter = 0;
>     for (var i = 0; i < items.Length; i++)
>         if (items[i].IndexOf("111") > 0)
>             counter++;
> }
> ```



> 我使用一个简单的计时器和警报来测量时间。此外， 我 "开始不调试" 和浏览器控制台关闭
> 
> ```cs
>     private void Foo()
>     {
>         DateTime dateTime = DateTime.Now;
>         var items = new string[5000000];
>         for (var i = 0; i < items.Length; i++)
>             items[i] = "some string some string 111" + i.ToString();
> 
>         var counter = 0;
>         for (var i = 0; i < items.Length; i++)
>             if (items[i].IndexOf("111") > 0)
>                 counter++;
>         
>         JsRuntime.InvokeVoidAsync("alert", (DateTime.Now - dateTime).TotalSeconds.ToString()); // Alert
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/3189803/142503778-3583e0ee-3ca2-437e-bf0e-4f3fc679a7a9.png)






items[i].IndexOf  change  items[i].AsSpan()

**Comment by azbo** [comment]
DateTime dateTime = DateTime.Now;
        var items = new string[500000];
        for (int i = 0; i < items.Length; i++)
        {
            items[i] = $"some string some string 111{i}";
        }

        var counter = 0;
        for (var i = 0; i < items.Length; i++)
        {
            if (items[i].AsSpan().IndexOf("111") > 0)
            {
                counter++;
            }
        }

        Console.WriteLine($"耗时 {(DateTime.Now - dateTime).TotalSeconds} s");
        Console.WriteLine(items.Length);

**Comment by javiercn** [comment]
@madnik7 I don't think this type of benchmark is super relevant.

I suspect the JS implementation is able to internally use SIMD, hence the speed-up, and the .NET runtime doesn't leverage SIMD on WASM yet. Other things that might be affecting the benchmark might be the fact that you are forcing .NET to initialize a large array (5 million elements), which can probably be avoided with `[SkipLocalInits]`

In the JS case you are actually "mostly" not running JS, since the `toString()`, `indexOf()`, and other functions are natively implemented by the browser. A more fair comparison would be if you were to put the strings in arrays and perform the indexOf and toString() operations within JS.

That said, there are always going to be microbenchmarks where you can bet the WASM code, the reality is that all it matters is what works for your app. I would suggest you try to build something realistic that you would use in real-life and check if you have performance problems with it or if the trade-off against performance works for you or not and decide based on that.

After all, we are also a great backend for other JS frameworks 😉 and you can mix and match Blazor with them too!

**Comment by madnik7** [comment]
Dear javiercn,
Thank you for answering me directly.

>> After all, we are also an excellent backend for other JS frameworks, and you can mix and match Blazor with them too!
We didn’t move to Blazor until Blazor Web Assembly was offered. We prefer to decouple the frontend and backend and connect via Web API. We use AspNetCore as the backend and use SPA for our frontend. So we can choose many different frontend frameworks. In this case, we compare Blazor Web Assembly with other frontend frameworks.

>> I would suggest you try to build something realistic that you would use in real-life
Actually, now I think it was our fault that we switched to Blazor and built a realistic app before checking this basic performance check. String manipulation is a significant operation for many frontends. I haven’t posted this issue to just say "Hey, Blazor performance is poor!" As a pro C# developer, we have started to build a project because we like C# and believed web assembly would be faster as it doesn’t require interpret like javascript code. It is typesafe and has many more development benefits. Still, we can easily feel that Vue apps are incredibly smoother. In Blazor app we have a feeling that it looks we are trying to run in water, there are much more delays and lags. 

The story is that we are using MudBlazor as our UI component, We could feel our app noticeably not smooth as Vuetify but believed that there may some issue in the component framework and also hoped to performance get improved by .NET 6. After just fetching 1000 rows from our server in a real environment and putting it in a table, we found a huge lag in the filtering table or simple dropdown box. As we went into more details we found the main culprit is a simple string compression of 1000 rows. This was the last straw, now we understand why many UI frameworks are not smooth. End-Users don’t care how we implement the system, they feel our competitive app is much smoother.

Yes, Blazer component rendering is fast, but the reality is that many developers use heavy scripting over web platforms at the client-side. We can’t just ask developers to push them into the backend or tell them not to use certain string operations while they can do it easily in the javascript platforms. I can’t delude myself, it is disappointing but the reality is that the Emperor is nude!

I have experience in many UI platforms, even Silverlight! I hope to use C# for the web, but it looks the time has not come yet.

**Comment by Grizzlly** [comment]
@madnik7 Blazor is just as good as React, Angular, you name it. I use it in production and the experience is awesome. I don't get this:

> String manipulation is a significant operation for many frontends.

What do you mean by this? The only string manipulation I use is Json Serializing, Deserializing, and a few other very small things. I suggest you redo your benchmarks by measuring how fast you get the UI to be responsive rather than how fast you process 5 million elements... Not to mention that with the power of async/await you don't even need to wait for everything to load.

**Comment by chucker** [comment]
>As a pro C# developer, we have started to build a project because we like C# and believed web assembly would be faster as it doesn’t require to interpretation like javascript code.

Modern browsers typically run JS in a JIT, so it isn't interpreted. In that sense, JS actually has an advantage over C#: WebAssembly doesn't allow for a JIT, so all .NET can do is either run interpreted (still the default for Blazor WASM), or in a hybrid AOT+interpreted mode (as explored in this thread; for some scenarios such as Reflection, pure AOT isn't feasible). Plus, there's the inevitable overhead of JS interop, at least as long as direct DOM manipulation from WASM isn't an option.

Thus, for many scenarios, Blazor WASM always be slower than JS.

> String manipulation is a significant operation for many frontends.

I'm interested in why you think so.

**Comment by madnik7** [comment]
@chucker Thank you for your comment. String operations for Html generation, client-side filtering, user file parsing, especially in PWA.

**Comment by Grizzlly** [comment]
@madnik7 1. If you generate html with blazor you might be doing something wrong. Razor Components are the way.
2. Client-side filtering for user input is explained very well [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0).
3. File parsing for? If you send the file to the server you have to check it again anyway.

**Comment by hoangdovan** [comment]
@madnik7 @javiercn  I have same experience. Blazor performance cannot compare to javascript. In my case, I have to do millions of number calculation. It take so long time. My solution: do unmarshalled call to javascript interop. Blazor has large bundle size, slower than javascript... It's not ready yet for serious project!

**Comment by MariovanZeist** [comment]
@hoangdovan Blazor might not be a perfect fit for you, but it is for others. If you have a process that is very calculation-intensive, and you have to do it client-side, you could write that part in javascript if you want. Or maybe in your case Angular or Vue are better alternatives.
A lot of my applications are CRM or ERP systems, where there are few calculations client-side, but a lot of User Interface pages for data collection and display. Blazor has helped us tremendously in building robust and scalable applications.

**Comment by hoangdovan** [comment]
@MariovanZeist Don't get me wrong. I love C# and really hope Blazor can be game changer. At the moment, I just rewrite some Angular app to evaluate Blazor. The only benefit I can see in Blazor is just full stack C#, but it just cannot win the trade-off. In my opinion, Blazor (Web assembly) now have some main disadvantages:
- 1. Big bundle size, slow start-up.
- 2. Poor runtime performance
- 3. Painful debug experience, so slow, so buggy.
To be honest, I don't think so many people will select Blazor for serious project at the moment....
