### ISSUE TITLE
Blazor JS Interop Takes 1 min to throw exception

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#38501]
### Describe the bug
I am doing a simple JSInterop call to display a document in a new browser tab. The document is displayed but the await hangs for one minute and then delivers an exception. If you run the same code using Firefox as your browser no exception occurs.

### To Reproduce

This repository shows the issue. Build & run then select "button 'Press me#1'". Wait one minute to see the exception.

https://github.com/OptimiumHealth/BlazorJSInteropApp

### Exceptions (if any)

System.Threading.Tasks.TaskCanceledException: A task was canceled. at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Obj... is observed in the blazor app

Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at D (blazor.server.js:1)
    at blazor.server.js:1

is observed in the chrome developer console

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

```
C:\Solutions\TemporarySolutions\BlazorJSInteropApp>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\TemporarySolutions\BlazorJSInteropApp>
```

**Comment by TanayParikh** [comment]
This is due to the use of `InvokeAsync<object>`. JS is trying to return a `window` which isn't serializable leading to this exception.

In this case, I'd recommend using `InvokeVoidAsync` here:
https://github.com/OptimiumHealth/BlazorJSInteropApp/blob/3790681367335a5b4631946391bbecca53a8fc6f/BlazorJSInteropApp/Pages/Index.razor#L33

and here:

https://github.com/OptimiumHealth/BlazorJSInteropApp/blob/3790681367335a5b4631946391bbecca53a8fc6f/BlazorJSInteropApp/Pages/Index.razor#L45

**Comment by MarkStega** [comment]
@TanayParikh Thanks for the quick response. Unfortunately there are a plethora of examples of how to open a document in a new tab in Blazor that show that pattern that I used. Why does the error take a full minute to be reported?

**Comment by TanayParikh** [comment]
> @TanayParikh Thanks for the quick response. Unfortunately there are a plethora of examples of how to open a document in a new tab in Blazor that show that pattern that I used. 

Thanks for pointing that out, there were recent changes in this area which enabled the improved pattern with `InvokeVoidAsync`. This improved pattern may not have been utilized by external documentation yet. Do you have any examples of official Blazor documentation recommending this pattern? If so that's something we'd be able to fix right away 😄 


> Why does the error take a full minute to be reported?

It shouldn't. Is it just with this exception, or are you seeing that with any (JSInterop) exception?

**Comment by MarkStega** [comment]
Because of the 'silence' that I reported in #38502 I don't know of any other JSInterop exceptions. Other, non JSInterop exceptions, are reported 'as they occur. So I believe that this is something to do with the JSInterop ;

A bit of microsoft documentation using the incorrect pattern: https://docs.microsoft.com/en-us/answers/questions/217767/blazor-open-a-page-in-a-new-browser-tab-using-navi.html

**Comment by MarkStega** [comment]
I really don't believe this should be closed. Still not explained is why it take a full minute for the exception to occur.

**Comment by TanayParikh** [comment]
> why it takes a full minute for the exception to occur

Re-opening to see why this is the case, and to determine if it's indicative of a deeper issue. If it's specific to the pattern from the original issue (using `InvokeAsync<object>` instead of `InvokeVoidAsync`) this'll likely be closed out given the improved pattern is available.

**Comment by MarkStega** [comment]
Thanks for reopening -- I still maintain that even if the delay is specific to the pattern the exception certainly shouldn't take a minute to be thrown & should not be 'silent' (#38502)

I like the idea of an analyzer warning

**Comment by mkArtakMSFT** [comment]
After some conversation in the team we think we don't catch JavasScript serialization exceptions thrown during JSInterop.

**Comment by MarkStega** [comment]
@mkArtakMSFT In the repo that I attached you can see that the addition of the try/catch does show the exception (but one full minute after it occurs).

**Comment by mkArtakMSFT** [comment]
@MarkStega we think this may have been fixed in 7.0 already. Could you please give it a try and confirm? Thanks!

**Comment by MarkStega** [comment]
@mkArtakMSFT In DN7.preview 7 I can confirm that with Chrome & Edge that the exception is thrown immediately. Firefox doesn't throw an exception. And with the switch to InvokeVoidAsync in the 2nd example there is no exception thrown.

**Comment by TanayParikh** [comment]
Note, I've closed out https://github.com/dotnet/aspnetcore/issues/38502

**Comment by mkArtakMSFT** [comment]
Closing as it seems this has already been addressed.
