### ISSUE TITLE
ModelState validation result should be consistent between `BadRequestObjectResult` and  `ApiControllerAttribute`

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#38504]
Currently, ModelState validation result is not consistent between `BadRequestObjectResult` and  `ApiControllerAttribute`.

For `ApiControllerAttribute`, the validation result is as follows:

```JSON
{
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "UserName": ["The UserName field is required."]
  }
}
```

If we add a custom validation message in the controller action method and then return `BadRequest(ModelState)`, then the validation result shows as follows:

```JSON
{
   "UserName": ["The UserName is already taken."]
}
```

This inconsistency makes it difficult to handle the server-side errors on the client-side.

The closest workaround is doing as follows:

```C#
builder.Services.AddControllersWithViews()
    .ConfigureApiBehaviorOptions(options =>
    {
        options.InvalidModelStateResponseFactory = context =>
        {
            return new BadRequestObjectResult(context.ModelState);
        };
    });
```

This overrides the `ApiControllerAttribute` the validation result and returns as follows:

```JSON
{
   "UserName": ["The UserName field is required."]
}
```

But problem is that vice versa is not possible. We want to return the validation result for the `BadRequest(ModelState)` as follows:

```JSON
{
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "UserName": ["The UserName is already taken."]
  }
}
```

Please add an option so that `BadRequest(ModelState)` return the validation result with `ValidationProblemDetails(ModelState)`.

Thanks in advance.

**Comment by rafikiassumani-msft** [comment]
Triage: Changing `BadRequest` will be breaking as there is already an existing format for the response. Is this something that you can achieve by writing a custom helper method that returns a `ValidationProblemDetails(ModelState)` ?

**Comment by TanvirArjel** [comment]
@rafikiassumani-msft 
> Is this something that you can achieve by writing a custom helper method that returns a ValidationProblemDetails(ModelState)?

We are aware of this. If *Changing BadRequest will be breaking as there is already an existing format for the response.* then there should be an option to configure it from the startup as follows:

```C#
builder.Services.AddControllersWithViews()
    .ConfigureApiBadRequestObjectResult(options =>
    {
        options.BadRequestObjectResultResponseFactory = context =>
        {
            return new BadRequestObjectResult(ValidationProblemDetails(context.ModelState));
        };
    });
```

**Comment by rafikiassumani-msft** [comment]
@TanvirArjel We don't intend to add first class support for this in MVC. You can create a filter to convert `BadRequest` to `ValidationProblemDetails` and registers the filter in the startup class.

**Comment by TanvirArjel** [comment]
@rafikiassumani-msft This is what you suggested, am I correct?

```C#
public class BadRequestResultFilter : IResultFilter
{
    public void OnResultExecuting(ResultExecutingContext context)
    {
        if (context != null && !context.ModelState.IsValid)
        {
            context.Result = new BadRequestObjectResult(new ValidationProblemDetails(context.ModelState));
        }
    }

    public void OnResultExecuted(ResultExecutedContext context)
    {
        // Do nothing
    }
}
```
and
```C#
services.AddControllers(options =>
{
    options.Filters.Add(typeof(BadRequestResultFilter));
});
```

**Comment by rafikiassumani-msft** [comment]
@TanvirArjel your approach is fine. One thing to consider would be to also check if ```context.Result is BadRequestObjectResult```. This will limit your result transformation to only consider `BadRequestObjectResult` type and not everything else.
