### ISSUE TITLE
GRPC Web does not pass cookies

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/aspnetcore#38500]
### Describe the bug
When using Grpc Web integration, cookies aren't passed along to the backend as part of the XHRHttpRequest, this prevents people from using Cookie based session authentication on Grpc Web endpoints.

### To Reproduce
1. Create Blazorwasm project
2. Create Backend Project
3. Create Backend endpoint that allows login and sets a cookie
4. Create a shared GRPC Service that is exposed via GRPC Web
5. See that it doesn't work because the web request doesn't send cookies along

### Further technical details
- ASP.NET Core version: 6
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</details>

**Comment by blowdart** [comment]
GRPC as a protocol does not support cookies, or cookie authentication, it's "limited" to certificate authentication and bearer token authentication by design and in its spec, GPRC simply has no concept of cookies

You'll notice that the documentation for the asp.net implementation [does not mention cookies at all](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-6.0).

**Comment by Blackclaws** [comment]
While its true that the GRPC spec doesn't mention cookies that doesn't mean GRPC Web shouldn't have support for it. See also: https://github.com/improbable-eng/grpc-web/issues/103

There are legitimate use cases in Browser - Backend communication that make cookies simply a more secure alternative to bearer tokens.

Grpc between servers obviously doesn't really have a need for cookies nor do they really provide benefits. In the web they can be used to authenticate clients without those credentials ever passing through userspace in the browser.

**Comment by Blackclaws** [comment]
Ok scratch _everything_ I've said. This does work but its poorly documented even for CORS Rest calls. You need to actually create a delegating handler that sets the request to include credentials:

```csharp
public class DelegatingCredentialHandler : System.Net.Http.DelegatingHandler
{
    public DelegatingCredentialHandler(HttpMessageHandler inner) : base(inner)
    {
        
    }
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.SetBrowserRequestCredentials(BrowserRequestCredentials.Include);
        return base.SendAsync(request, cancellationToken);
    }
}
```

and then use it like so:

```csharp
       var channel = GrpcChannel.ForAddress("https://localhost:7156", new GrpcChannelOptions()
        {
            HttpHandler = new DelegatingCredentialHandler(new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler())),
        });
```

In general I couldn't find any part of the documentation that talks about having to explicitly set this on requests in order to include credentials. To me it has just been a given that HttpClient in browsers will do this (for some reason). Maybe we need a bit of documentation to support this. Also the section on Grpc Web can include this as well as I think it might be useful to others.
