### ISSUE TITLE
.NET 6 & VS2022 minimal API templates

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38513]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-6--VS2022-minimal-API-templates/1582918)._

---
[severity:It bothers me. A fix would be nice]
To better improve the usability of Visual Studio 2022, there should be an option when creating projects which allows you to choose between the new minimal APIs and the old format that many of us know and prefer.

I personally have no interest in using the new minimal format, this is my personal preference and isn't really something that I have to justify. It would be nice to not have create a project targeting .NET 5 to avail of the old project template format before then updating the project to target .NET 6. What happens when .NET 5 is end of life?

As such, having a checkbox, which defaults to "Yes", to allow us to opt-in to the minimal API project format would be greatly appreciated.

---
#### Feedback Bot on 11/15/2021, 00:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/15/2021, 09:44 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by luky92** [comment]
any update on this will this be adressed?

**Comment by ColinM9991** [comment]
Commenting to reopen.

**Comment by rov3rPL** [comment]
I concur with the addressed issue. An option to create a new project with the old template should be available in .NET 6 as old approach is more frequent still and Minimal Apis are less! That's a lot of starter code to copy-paste it : ((
