### ISSUE TITLE
After update to core6 strange error, browser-wasm

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-update-to-core6-strange-error-bro/1587306)._

---
[severity:I'm unable to use this version] [regression] [worked-in:5]
Hi, after update solution from core5 to core6 on webassembly app i get this error:

Errore	NETSDK1082	non è disponibile alcun pacchetto di runtime per Microsoft.AspNetCore.App per l'elemento RuntimeIdentifier specificato 'browser-wasm'.	Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	

the client project is built from scratch core6 and after copy file from core5

all the rest of the projects are ok (some library + aspnetcore webapi), i tryed to understand what is the problem but no solution, someone have idea?

---
#### Feedback Bot on 11/17/2021, 10:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Blackclaws** [comment]
This looks like an error where you might be referencing aspnetcore libraries in a webassembly context that don't work there, (non-web) grpc is one example.
