### ISSUE TITLE
Unmarshalled calls with arrays is much slower with WASM 6.0.0

### ISSUE THREAD

**Issue by jahnotto** [dotnet/aspnetcore#38510]
After upgrading Microsoft.AspNetCore.Components.WebAssembly from 5.0.12 to 6.0.0, unmarshalled calls with a large array as parameter is much slower.

I am doing the following call with a byte[94371840] array:

```
var unmarshalledJs = (IJSUnmarshalledRuntime)Js; // Js is a IJSRuntime

unmarshalledJs.InvokeUnmarshalled<byte[], int>("createBufferU8", myLargeArray);
```

The JavaScript function looks like this:

```
function createBufferU8(arrayFromNet) {
    const start = Date.now();

    let byteArray8 = Blazor.platform.toUint8Array(arrayFromNet);

    let elapsed = Date.now() - start;

    console.log('Getting blazor array of size ' + byteArray8.length + ' took ' + elapsed + ' ms');

    // ...and more here, not relevant for this sample
}
```

With WebAssembly 5.0.12, this took ~1 ms. With WebAssembly 6.0.0, this takes ~25 ms.

I am aware that arrays can now be passed without base64 encoding without unmarshalled calls. However, this is just as slow as the unmarshalled call. 

Is this a bug, or can this be done differently now with the same performance as WebAssembly 5.0.x?

**Comment by TanayParikh** [comment]
In .NET 6 arrays are sent from .NET to JS here:

https://github.com/dotnet/aspnetcore/blob/30a18721e225241127c968e653662fbf810f39f7/src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs#L73-L76

and received by JS here:

https://github.com/dotnet/aspnetcore/blob/504c502b6b783cf3ebc48623e2099f09fe1af74d/src/Components/Web.JS/src/Boot.WebAssembly.ts#L186-L190

Note the unmarshalled interop is handled by the client, so the `let byteArray8 = Blazor.platform.toUint8Array(arrayFromNet);` should no longer be necessary. This duplicate call may be contributing to the issue. Given this, measuring perf based on JS start/elapsed wouldn't be possible, it would have to be done before/after the .NET `InvokeUnmarshalled` call (along with being done in release mode, on a published app, without the debugger attached). Note you may be able to leverage `JSInProcessRuntime.Invoke<byte[]>` as well, like we do in the framework internal E2E tests:

https://github.com/dotnet/aspnetcore/blob/30a18721e225241127c968e653662fbf810f39f7/src/Components/test/testassets/BasicTestApp/InteropComponent.razor#L200

**Comment by javiercn** [comment]
@jahnotto thanks for contacting us.

Please try the suggestions recommended by @TanayParikh and let us know if you still have issues.

**Comment by jahnotto** [comment]
Thanks for your reply @TanayParikh . 

The above code gives an error -- I assume that this is because your code is TypeScript rather han JavaScript:

`Microsoft.JSInterop.JSException: monoPlatform is not defined ReferenceError: monoPlatform is not defined`

Is there a JavaScript equivaluent?

**Comment by TanayParikh** [comment]
> Thanks for your reply @TanayParikh . 
> 
> The above code gives an error -- I assume that this is because your code is TypeScript rather han JavaScript:
> 
> `Microsoft.JSInterop.JSException: monoPlatform is not defined ReferenceError: monoPlatform is not defined`
> 
> Is there a JavaScript equivalent?

The typescript snippet I linked was an example of what the framework does internally. This is not something which has to be done in user code as it's handled by the framework. As I mentioned above, I recommend just removing the `let byteArray8 = Blazor.platform.toUint8Array(arrayFromNet);` line you have in your JS function as the framework already provides a Uint8Array to `createBufferU8(arrayFromNet)`.

**Comment by jahnotto** [comment]
Hello again @TanayParikh. I try to simply use the array without converison like this:

.NET side:

```
                var someBytes = new byte[500 * 500 * 360];
                someBytes[0] = 1;
                someBytes[1] = 2;

                _unmarshalledJs.InvokeUnmarshalled<byte[], int>("setArrayDirect", someBytes);
```

On the JavaScript side:

```
function setArrayDirect(inputArray) {
    console.log('Input array direct: ' + inputArray[0] + ' ' + inputArray[1]);

    return 0;
}
```

However, when I run this, the following is logged to the console:

`Input array direct: undefined undefined`

**Comment by TanayParikh** [comment]
Hmm, that's strange. Is the `inputArray` a Uint8Array? What happens if you just log `inputArray`. Also, to confirm, you're doing this in Blazor WebAssembly on .NET 6?

If you can provide a minimal repro app in a public github repository, I can take a look further.
