### ISSUE TITLE
Hot Reload not working on converted project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hot-Reload-not-working-on-converted-proj/1585906)._

---
I have a large project with multiple Blazor library references. See image.  
[BigProject.png] (https://aka.ms/dc/file?name=B572622f069b34185992022a94bcf6afe637726825736210778_BigProject.png&tid=572622f069b34185992022a94bcf6afe637726825736210778)

They were all initially built in .Net 5, and recently upgraded to .Net 6, with all NuGet packages updated as well.  This process worked pretty well, and the application runs ok.

The problem is that Hot Reload is not working.  I tried a simple HTML edit.  I expected to get the checkmark in the browser indicating that it had received the update, but nothing happens.

This is a fresh install of Visual Studio 2022 on a fresh install of Windows 11

---
#### Feedback Bot on 11/16/2021, 11:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Kevon Houghton on 11/18/2021, 09:17 AM: 

<p><a target='_blank' href="https://github.com/dotnet/aspnetcore/issues/28293">https://github.com/dotnet/aspnetcore/issues/28293</a></p>
<p>This is the issue, exactly.</p>
<p>I can appreciate the complication related to trying to get hot reload working with compression.  You guys need to message the heck out of this.  You’re touting Hot Reload as “works everywhere” but there needs to be some disclaimers and lists of “gotchas” like this one.  You need to be clear and LOUD about this stuff.  It is beyond frustrating when you say that something just “works” but it doesn’t.</p>
<p>If MY QA department failed to catch something as critical as this, I’d have strong words for them.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Are you still seeing this issue with the latest public release of VS? If so, are you able to share a minimal app that reproduces the issue?
