### ISSUE TITLE
.NET 6 WPF DI How to get an instance of IHubContext manually

### ISSUE THREAD

**Issue by LuGuangguang** [dotnet/aspnetcore#38516]
I want to get an instance to used for dependency injection，I browse the MSDN documentation from https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-6.0 "Get an instance of IHubContext from IHost";
But I found it is based on .net 5 or less.
I run the code normally under .net core 3.1.
`   IHubContext<ChatHub>? hubContext = _host.Services.GetService(typeof(IHubContext<ChatHub>)) as IHubContext<ChatHub>;
            services.AddSingleton<IHubContext<ChatHub>>(hubContext);`
![@A1A S84 P4@XN9NLL3S4}0](https://user-images.githubusercontent.com/34500722/142534763-bed23bea-1e63-42b5-90d3-4fc932dfa03d.png)

You know the asp.net core 6.0 Use the WebApplication to Host, so I try code
`IHubContext<ChatHub>? hubContext = app.Services.GetService(typeof(IHubContext<ChatHub>)) as IHubContext<ChatHub>; services.AddSingleton<IHubContext<ChatHub>>(hubContext);`

But when I use the hubContext,I found the Client link count aways 0.

![S1X35SE7}GY5XRJ(P4EKXG3](https://user-images.githubusercontent.com/34500722/142533671-91945c00-bbf1-466c-830d-be093917ff64.png)

Is my method is error or otherings?

**Comment by davidfowl** [comment]
```
services.AddSingleton<IHubContext<ChatHub>>(hubContext);
```

Why are you doing this?

**Comment by LuGuangguang** [comment]
> ```
> services.AddSingleton<IHubContext<ChatHub>>(hubContext);
> ```
> 
> Why are you doing this?

Because my project is a  WPF type, I need to DI

**Comment by davidfowl** [comment]
SignalR owns the `IHubContext<>` registration and you're overriding it. It's not clear why.

**Comment by LuGuangguang** [comment]
> SignalR owns the `IHubContext<>` registration and you're overriding it. It's not clear why.

I know the web that owns, because it is registered internally.But I use WPF ,I need register manually，otherwise it will throw “Null reference” Error.

**Comment by LuGuangguang** [comment]
I don’t know why, but suddenly it’s normal.
I will continue to follow it.
Trouble you a lot. @davidfowl
