### ISSUE TITLE
AuthorizeRouteView is missing the Policy Property

### ISSUE THREAD

**Issue by eluchsinger** [dotnet/aspnetcore#38525]
### Describe the bug

I am not sure, if this is a Bug, a Feature or an API Change.

Developers using the `<AuthorizeView>` component, can [set the Policy using a Property](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0#role-based-and-policy-based-authorization). Example:

```html
<AuthorizeView Policy="content-editor">
    <p>You can only see this if you satisfy the "content-editor" policy.</p>
</AuthorizeView>
```

According to the documentation, `<AuthorizeRouteView>` is a combination of `<AuthorizeView>` and `<RouteView>`, **but the Policy option is missing**. So using the `AuthorizeRouteView`, in combination with policies appears to be unsupported.

From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.authorization.authorizerouteview?view=aspnetcore-6.0) of `<AuthorizeRouteView>`:

> Combines the behaviors of AuthorizeView and RouteView, so that it displays the page matching the specified route but only if the user is authorized to see it. Additionally, this component supplies a cascading parameter of type Task<TResult>, which makes the user's current authentication state available to descendants.

### Further technical details
- ASP.NET Core version: 6

**Comment by javiercn** [comment]
@eluchsinger thanks for contacting us.

This is by design. On `AuthorizeRouteView` you set the policy on each page via the `[Authorize]` attribute
