### ISSUE TITLE
StaticWebAssets.xml missing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38522]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StaticWebAssetsxml-missing/1568815)._

---
[regression]
I have no problems with VS 2019 but in VS2022 Version 17.0.0 Preview 7.0 I get (during compile)

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3030	Could not copy the file "C:\Projects\OTP\KIS\source\OTP. KIS. Service\obj\Debug\net5.0\staticwebassets\MyProject.StaticWebAssets.xml" because it was not found.	Otp.Kis.AdminInterface.Wpf	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5100

---
#### Feedback Bot on 11/1/2021, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/5/2021, 02:29 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

In order for us to make progress, could you provide a minimal repro project as a **public github repository** and detailed steps on how to reproduce the issue?
