### ISSUE TITLE
Customize ValidationMessage classes

### ISSUE THREAD

**Issue by eluchsinger** [dotnet/aspnetcore#38528]
### Is your feature request related to a problem? Please describe.

Using Blazor/Razor, there is a way to override the CSS classes that are using when validating form components, like `<InputText>` (read the docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#custom-validation-css-class-attributes-1)).

The custom CSS rules only work for form fields, but not for the `<ValidationMessage>` component. The class attribute is overridden/set in the `ValidationMessage` component (see [here](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Web/src/Forms/ValidationMessage.cs#L77)).

### Describe the solution you'd like

I would expect to be able to override the css classes used for the `ValidationMessage` in the same way I can override the other input's css using the `FieldCssClassProvider`. Even better would be to be able to override the CSS directly in the `ValidationMessage` component using the `class`-attribute.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The solution would be to swap lines 76 and 77 here: https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Web/src/Forms/ValidationMessage.cs#L77

Do you want to send us a PR with that change?

**Comment by eluchsinger** [comment]
@mkArtakMSFT thanks. I will take a look at it!

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/39990
