### ISSUE TITLE
Update our processes to reserve time as part of milestone for better validation

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#38535]
Reserve time as part of milestone to validate other team members' features / fixes and file CTI scenarios for these as well. When filing CTI validation scenario, also consider exploratory testing too (if needed).

**Comment by mkArtakMSFT** [comment]
@rafikiassumani-msft , @adityamandaleeka I've incorporated this into our planning and I'd like to close this unless you think there is more work here.

**Comment by rafikiassumani-msft** [comment]
I am fine closing this. Thanks.
