### ISSUE TITLE
partial tag helper content not rendered in asp.net core 6 hosted in IIS 10

### ISSUE THREAD

**Issue by candrewtemenoscom** [dotnet/aspnetcore#38541]
Migrated our application from asp.net core 5 to 6, after deployed to IIS 10, we found that the partial view not rendered properly in IIS (please see our code snippet below) by the razor view engine. However, the same application runs without any issue on IIS Express or Kestrel. You can see the partial tag not processed with the chrome inspector.

```razor
<code snippet on view --- begin>
<input type="hidden" id="contentDetailUrl" value="@contentDetailUrl" />
<partial name="~/Areas/Shared/Views/ContentTreeMenu.cshtml" view-data="ViewData" />
<div id="contentSplitter" class="splitter"></div>
<div id="frmContent-Container" class="">
    @{        
        await Html.RenderPartialAsync($"~/Areas/Report/Views/Browser/ContentDetails.cshtml", modelAndTreeData, null);
    }
</div>
<code snippet on view --- end>
```

<img width="551" alt="Capture" src="https://user-images.githubusercontent.com/6600394/142706086-9c3bc7b1-0bd3-49c3-94b9-37c6c7508ed8.PNG">

**Comment by candrewtemenoscom** [comment]
The following is the code snippet hidden in the previous post.


<input type="hidden" id="contentDetailUrl" value="@contentDetailUrl" />
<partial name="~/Areas/Shared/Views/ContentTreeMenu.cshtml" view-data="ViewData" />
<div id="contentSplitter" class="splitter"></div>
<div id="frmContent-Container" class="">
    @{
        
        await Html.RenderPartialAsync($"~/Areas/Report/Views/Browser/ContentDetails.cshtml", modelAndTreeData, null);
    }
</div>

**Comment by candrewtemenoscom** [comment]
![image](https://user-images.githubusercontent.com/6600394/142706317-74d7566e-7895-4ab6-9d56-668699c7f003.png)

**Comment by candrewtemenoscom** [comment]
I investigate this further and run the app within vs 2022 in debug mode on IIS Host. The view rendered without any issue. This should simulate the app running on IIS 10. Does it mean it is not related to IIS 10 but rather the publish process? Any idea?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by candrewtemenoscom** [comment]
I was trying to reproduce the same issue with <partial> tag helper by creating a demo from vs 2022 with the latest asp.net core web app template. However, I cannot reproduce the same issue that we are facing with the demo. We keep removing everything from our page except that partial view, we notice that the razor view templating engine did not render it at all as we set a breakpoint in the view but did not get hit. There is no exception or anything being logged in the event viewer. In addition, we use a partial tag helper to render partial view in other razor views and they are fine. The difference we notice is the other razor views that have the partial tag helpers are rendered by the ViewRendererService to render the view as a string while the one that has the problem does not use that. Again, we are not sure what causes the problem but it only happens on the deployed application on IIS (in-process) with our application upgraded from asp.net core MVC 5.

Hope the above information can help Microsoft if there are other cases of this kind of issue showing up.

**Comment by SteveSandersonMS** [comment]
@pranavkm We're hoping you might have some insights here.

**Comment by pranavkm** [comment]
It makes sense that this does not produce an exception - for some reason the partial tag helper isn't being resolved (you'll note that it's emitting it verbatim in markup). 

Unfortunately without some sort of a repro, it's going to be difficult to figure out why this is happening given this is the only report of this kind we've received. On an off chance, does including `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` to the [top of the cshtml file](https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0#addtaghelper-makes-tag-helpers-available) make a difference?

**Comment by candrewtemenoscom** [comment]
Interestingly, the workaround suggested by adding @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers on top of my cshtml view does make it work on deployment when hosting on IIS. I just could not quite understand even though I had already added that to the _ViewImports.cshtml. It used to work (the partial tag helper does render) without any issue on IIS when it was on asp.net core 5.
