### ISSUE TITLE
Can't launch Kestrel if the startup takes 'long' time in Visual Studio 2022 .NET 6

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/aspnetcore#38544]
The screenshot explains. I just simulated the case when the startup might take a long time.
![image](https://user-images.githubusercontent.com/17007651/142710195-986d2eb8-283c-478a-8cc0-faf018c01f21.png)

This error only happens when launching using Kestrel. With IIS Express it can allow a long startup time.

**Comment by nicholasyin** [comment]
Wonder if there's any options that I can change to tolerate this?

**Comment by davidfowl** [comment]
It works fine but the IDE is failing to launch the browser because the server isn't listening on the port as yet (because of the sleep). I don't think there's a way to tweak how long the Visual Studio will wait before it gives up on trying to connect to the application, but you can turn it off in `Properties/launchSettings.json` by setting `"launchBrowser": false`

cc @vijayrkn @BillHiebert

**Comment by nicholasyin** [comment]
I also tried with 8 seconds and it works. Anyway, the point is that I don't think my real startup code takes that long time. But the IDE appears to see so. I don't know where the time was spent, and also don't know from what point of time does the IDE start to count. From the successful build, or what. The process is very vague to me and I don't have a clue as to solve this.

**Comment by davidfowl** [comment]
I explained what the problem was and described a work around, did you try it?

**Comment by nicholasyin** [comment]
Yes, thanks for the workaround. I say it's a workaround, not a solution, because without the browser I can't know that the application is ready to accept request. Not quite convenient, but looks like it's the best that can be done, though.

**Comment by Tratcher** [comment]
> because without the browser I can't know that the application is ready to accept request.

You'll know the server is ready to accept requests by looking at the console log output.

**Comment by nicholasyin** [comment]
> > because without the browser I can't know that the application is ready to accept request.
> 
> You'll know the server is ready to accept requests by looking at the console log output.

Well, that's true.

**Comment by Pilchie** [comment]
@davidfowl - what was the reason for re-opening?  Do you see an action for us here?

**Comment by nicholasyin** [comment]
> > because without the browser I can't know that the application is ready to accept request.
> 
> You'll know the server is ready to accept requests by looking at the console log output.

Well, that's true.

**Comment by davidfowl** [comment]
The tooling experience could be better (its why I cced @vijayrkn and @BillHiebert). Off the top of my head, it could:
- Have an option to disable the timeout or allow setting custom timeout (that could be in launch settings). There are multiple failure cases here and we're treating them similarly:
    - Unable to bind to socket (maybe it's not a real web app and somebody turned on the launch browser option)
    - Unable to start (we can keep track of the process and know if it is running but there's no bound port)
    - Taking long to start.
- We can show better pop up a dialog when the default timeout has been reached asking the user if they want to keep waiting or stop trying to launch the browser. We would remember this setting for future launches.

**Comment by nicholasyin** [comment]
My original expectation would be a configurable timeout setting somewhere. But this is higher and further.

> The tooling experience could be better (its why I cced @vijayrkn and @BillHiebert). Off the top of my head, it could:
> 
> * Have an option to disable the timeout or allow setting custom timeout (that could be in launch settings). There are multiple failure cases here and we're treating them similarly:
>   
>   * Unable to bind to socket (maybe it's not a real web app and somebody turned on the launch browser option)
>   * Unable to start (we can keep track of the process and know if it is running but there's no bound port)
>   * Taking long to start.
> * We can show better pop up a dialog when the default timeout has been reached asking the user if they want to keep waiting or stop trying to launch the browser. We would remember this setting for future launches.

**Comment by vijayrkn** [comment]
> The tooling experience could be better (its why I cced @vijayrkn and @BillHiebert). Off the top of my head, it could:
> 
> * Have an option to disable the timeout or allow setting custom timeout (that could be in launch settings). There are multiple failure cases here and we're treating them similarly:
>   
>   * Unable to bind to socket (maybe it's not a real web app and somebody turned on the launch browser option)
>   * Unable to start (we can keep track of the process and know if it is running but there's no bound port)
>   * Taking long to start.
> * We can show better pop up a dialog when the default timeout has been reached asking the user if they want to keep waiting or stop trying to launch the browser. We would remember this setting for future launches.

Will create an item to track on the VS side.

**Comment by Pilchie** [comment]
Closing this in favor of @vijayrkn's VS issue.
