### ISSUE TITLE
Add support to add RouterLink to the Router

### ISSUE THREAD

**Issue by ilijevicdenis** [dotnet/aspnetcore#38553]
Currently, Blazor defines the route on the razor page using the @page directive.  Even though is OK on larger projects this approach is no good because developers are locked from implementing strategies for route management.  If a router exposes one simple method like RegisterRouter you would make our life easier. 

Angular way of route defining would be nice to have 

const appRoutes: Routes = [
  { path: 'crisis-center', component: CrisisListComponent },
  { path: 'heroes', component: HeroListComponent },
];

Router.Register(routes);

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
