### ISSUE TITLE
Signalr MaxBuffersize settings causing large increase in memory on client

### ISSUE THREAD

**Issue by vinaykapoor** [dotnet/aspnetcore#38558]
I am using the following options
**Signalr Hub options //data publisher
options.TransportMaxBufferSize = 65536;
options.ApplicationMaxBufferSize = 0;
sig.MaximumReceiveMessageSize = 65536;**
 
**and on the Signalr .NET Client HubConnection option
options.TransportMaxBufferSize = 65536;
options.ApplicationMaxBufferSize = 0;**
 
I have began noticing my applications memory increase very quickly and touches around 20GB after 3-4 hours of application run all while my CPU is well below 10%.
It looks like the back pressure causes the memory to increase.
 
Will it be better if I assign ApplicationMaxBuffersize to a value like 65536 (65MB? If the unit of each of these properties in MB ). It would help to have that in the api's documentation or intellisense.
I was refering to the final check in made under https://github.com/dotnet/aspnetcore/pull/35107.
 
If you could suggest how to set the app buffer size to 2GB and send & recv buffer size to 65MB for both signalr hub publisher and Signalr .NET Client subscriber, I will really appreciate it. Right now I am guessing how to avoid the memory increase.

Thank you

**Comment by davidfowl** [comment]
You should collect a memory dump to figure out where the memory is allocated. How did you arrive at changing those settings and how did you verify that they were the right numbers?

**Comment by vinaykapoor** [comment]
I had not made any changes to the application other than upgrading to .net 6. My intent was to set the incoming buffer to around a gig on the client end. I actually don’t know what the number to set should be on the server and client side since the documentation for default setting for server mentions 64kb and client 1MB. I wanted to set both to be around a gig. Is the unit of the settings a KB or MB?

Vinay

**Comment by davidfowl** [comment]
The unit is bytes. 1GB for client memory? Why would you want that? What is this application doing?

**Comment by vinaykapoor** [comment]
I had set the memory size to 65546 for 65MB. I tried to set a celing of 1 GB so it doesn’t surpass that and applies throttling. Is my usage of that incorrect?

Vinay

**Comment by vinaykapoor** [comment]
I was trying to set the buffer limit to 65MB. But I had set it to 0 since your documentation suggested that 0 sets the buffer size to max available. I was not sure how that regulated the memory, so I wanted to try to set it to 1GB. 

Vinay

**Comment by davidfowl** [comment]
65546 is 65K not 65MB.
