### ISSUE TITLE
[Blazor] SVG, emit numeric attributes with InvariantCulture

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#38568]
When the culture for the server is not english, we emit numeric fields with the wrong separator. To fix it in the code, we’d need to change each place that emits a numeric value inside the SVG to use culture-invariant formatting. For example, for each @value, replace it with @value.ToString(CultureInfo.InvariantCulture).

**Comment by SteveSandersonMS** [comment]
@javiercn I thought this was a bug in the sample code, not in the framework. Am I misunderstanding?

**Comment by javiercn** [comment]
@SteveSandersonMS maybe I understood your answer wrong? I thought that your comment was that the framework should take care of this, but if that's not the case, then closing it.
