### ISSUE TITLE
Add overload to DataProtection PersistKeysToRedis for a factory which accepts IServiceProvider as an argument

### ISSUE THREAD

**Issue by Nysosis** [dotnet/aspnetcore#3856]
### Is your feature request related to a problem? Please describe.
I'm trying to register a Redis connection to [persist my data protection keys to redis](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1#azure-and-redis), however my Redis connection is already registered with my `IServicesCollection` as a singleton, and I would like to reuse that same instance for the data protection call

### Describe the solution you'd like
Add additional overload(s) to `Microsoft.AspNetCore.DataProtection.RedisDataProtectionBuilderExtensions` which accepts a `Func<IServiceProvider, IConnectionMultiplexer>` factory, so I can resolve the `IConnectionMultiplexer` from the `IServiceProvider`

### Describe alternatives you've considered
I can't find the source code for this particular extension method, so I can't essentially duplicate it's behaviour with the functionality I require locally.

**Comment by blowdart** [comment]
The source (until the mono-repo merge) is at https://github.com/aspnet/DataProtection/blob/master/src/Microsoft.AspNetCore.DataProtection.StackExchangeRedis/RedisDataProtectionBuilderExtensions.cs

**Comment by natemcmaster** [comment]
FYI @blowdart, DataProtection source has been merged. aspnet/DataProtection is archived and doesn't represent latest code anymore.

https://github.com/aspnet/AspNetCore/tree/master/src/DataProtection

**Comment by davidfowl** [comment]
I suggest we don't make this change at least not in this way. We should use options to allow taking a ConnectionMultiplexer.

**Comment by davidfowl** [comment]
Yep, it's one of the harder things to do right as well, see https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#constructors. Getting the ConnectionMultiplexer requires a call to Connect or ConnectAsync. It might be better to use the sync version (but that's blocking IO that happens lazily).

This is why we need async startup 😄 . Maybe an IHostedService can ConnectAsync.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
