### ISSUE TITLE
How to use IFormFile in .Net 6

### ISSUE THREAD

**Issue by doanhquang2005** [dotnet/aspnetcore#38562]
In .Net 5, I use package "Microsoft.AspNetCore.Http.Features". But update .Net 6, I don't know how to do?

**Comment by Tratcher** [comment]
Can you give an example of how you were using it before?

IFormFile is part of the AspNetCore shared framework. If you're writing an app then you reference the Web SDK in your project file. If you're writing a library then you can reference the framework like this:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#use-the-aspnet-core-shared-framework
