### ISSUE TITLE
Comma needs to be deleted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38578]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Comma-needs-to-be-deleted/1591055)._

---
[severity:I'm unable to use this version]
! [image.png] (https://aka.ms/dc/image?name=B3374551c9e004b14a1299094630bccc2637730832191954441_20211121-102018-image.png&tid=3374551c9e004b14a1299094630bccc2637730832191954441)
Project : AspNetcore + React & Redux
There was a comma at end of line 55 that broke package file

---
#### Feedback Bot on 11/21/2021, 10:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've fixed that issue already as part of https://github.com/dotnet/aspnetcore/pull/37739 and the fix will ship as part of the upcoming December patch release.
