### ISSUE TITLE
[API Review] Support SkipStatusCodePages on endpoints and authorized routes

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#38573]
## Background and Motivation

https://github.com/dotnet/aspnetcore/issues/10317 identifies an issue where the behavior of the `AuthorizationMiddleware` circumvents the filter logic in `SkipStatusCodeAttribute` and results in the `StatusCodePageMiddleware` being executed when it shouldn't and masking the underlying 401 from the `AuthorizationMiddleware`.

This PR attempts to resolve this issue by removing the dependency on the `IFilter` execution order from the `SkipStatusCodeAttribute` by introducing an `ISkipStatusCodesMetadata` interface.

## Proposed API

```csharp
namespace Microsoft.AspNetCore.Http.Metadata;

public interface ISkipStatusCodePagesMetadata
{
    bool Enabled { get; }
}
```

```diff
- public class SkipStatusCodePagesAttribute : Attribute, IResourceFilter
+ public class SkipStatusCodePagesAttribute : Attribute, IResourceFilter, ISkipStatusCodePagesMetadata
{
+  public bool Enabled { get; }
}
```

## Usage Examples

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapGet("/", [SkipStatusCodePages] (c) =>
    {
        c.Response.StatusCode = 404;
        return Task.CompletedTask;
    });
});
```

PR located at https://github.com/dotnet/aspnetcore/pull/38509

**Comment by pranavkm** [comment]
**API review**:

Approved. We can remove the `Enabled` property and make this a vanilla 

```diff
namespace Microsoft.AspNetCore.Http.Metadata;

+ public interface ISkipStatusCodePagesMetadata
+ {
+ }

namespace Microsoft.AspNetCore.Mvc;

- public class SkipStatusCodePagesAttribute : Attribute, IResourceFilter
+ public class SkipStatusCodePagesAttribute : Attribute, IResourceFilter, ISkipStatusCodePagesMetadata
{
}
```

**Comment by Kahbazi** [comment]
@pranavkm I'm curios, why remove the `Enable` property and go against the [routing guideline](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#creating-routing-integrated-middleware).

> DO make it possible to override metadata

> The best way to follow these guidelines is to avoid defining marker metadata:
> - Don't just look for the presence of a metadata type.
> - Define a property on the metadata and check the property.

**Comment by pranavkm** [comment]
@Kahbazi we haven't seen any asks from users to want to toggle the feature which is in when we think a `Enabled` property would make sense. Our plan was to fix this with a narrow API that replicates the behavior of the MVC filter by turning it in to metadata.

**Comment by captainsafia** [comment]
Closing as completed.

**Comment by Kahbazi** [comment]
@captainsafia Just curious. Is there any follow up issue for https://github.com/dotnet/aspnetcore/pull/38509#issuecomment-977271675?

**Comment by halter73** [comment]
@Kahbazi Here's a follow up issue: https://github.com/dotnet/aspnetcore/issues/39472
