### ISSUE TITLE
.Net Core 6 Signal R Client to .Net Core 2 Signal R 1.0 Server

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/aspnetcore#38577]
Getting this error:
`ServerSentEvents failed: The transport does not support the 'Binary' transfer format.`

Is there any way to turn off "binary" transfer and use whatever is previously accepted?
I can seem to find much on this particular error.

Any help appreciated, thanks!

---
 `at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__44.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__41.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__40.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__57.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncInner>d__49.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__48.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at <StartSyncHub>d__2.MoveNext() in`

**Comment by BrennanConroy** [comment]
It looks like you're trying to use MessagePack on the client which does not work with ServerSentEvents. You need to either not use MessagePack or not use ServerSentEvents.

**Comment by OpenSpacesAndPlaces** [comment]
@BrennanConroy 

I'm using:
`IHubProtocol ihp = new JsonHubProtocol()`

But my only options seem to be:
```
IOptions<JsonHubProtocolOptions> ioHubOptions = Options.Create(new JsonHubProtocolOptions()
{
       PayloadSerializerOptions = new JsonSerializerOptions()
});
```

How would I modify my hub initialization to mess with:
`MessagePackHubProtocolOptions`

Or whichever other options point I should be.

Thanks for the help!

**Comment by BrennanConroy** [comment]
Share your hub connection code please

**Comment by OpenSpacesAndPlaces** [comment]
```
....
  Channel = sHostChannel;
                Uri uHostUrl = new Uri(sHostUrl);
                HttpTransportType tt;
                HttpTransportType.TryParse(sTransport, out tt);
                HttpConnectionOptions hco = new HttpConnectionOptions()
                {
                    Transports = tt,
                    Url = uHostUrl,
                    //After the server closes, if the client fails to close within this time interval, the connection is terminated.
                    CloseTimeout = new TimeSpan(0, 0, 0, 10)//Default 5 seconds

                };
                IConnectionFactory ic = new HttpConnectionFactory(new OptionsWrapper<HttpConnectionOptions>(hco), lg);
                IHubProtocol ihp = new JsonHubProtocol();
                UriEndPoint ie = new UriEndPoint(uHostUrl);
                SyncHub = new HubConnection(ic, ihp, ie, serviceProvider, lg);

                //If the client doesn't send an initial handshake message within this time interval, the connection is closed. This is an advanced setting that should only be modified if handshake timeout errors are occurring due to severe network latency. 
                SyncHub.HandshakeTimeout = new TimeSpan(0, 0, 0, 30);//Default 15 seconds

                //Timeout for server activity. If the server hasn't sent a message in this interval, the client considers the server disconnected and triggers the Closed event (onclose in JavaScript). This value must be large enough for a ping message to be sent from the server and received by the client within the timeout interval. 
                SyncHub.ServerTimeout = new TimeSpan(0, 0, 1, 0);//Default 30 seconds


                    await SyncHub.StartAsync();
                    await SyncHub.SendAsync("Join", sHostChannel)
```

**Comment by BrennanConroy** [comment]
Why are you manually creating a HubConnection instead of using the HubConnectionBuilder?
https://docs.microsoft.com/aspnet/core/signalr/dotnet-client?view=aspnetcore-6.0&tabs=visual-studio#connect-to-a-hub

**Comment by OpenSpacesAndPlaces** [comment]
Originally I was using this with .Net Framework - so no program.cs/startup.cs initializers?

Is there a simple way to fix what I have, or is there no configuration with a manual initialization anymore?

Worst case I could spool up a second Signal R server running on .Net 6 so the compatibility issues go away - but I was assuming whatever my problem was could be a one line code change.

**Comment by BrennanConroy** [comment]
> Is there a simple way to fix what I have, or is there no configuration with a manual initialization anymore?

All of that code you pasted should be able to simplify down to:
```
SyncHub = new HubConnectionBuilder().WithUrl("url").Build();
```

**Comment by OpenSpacesAndPlaces** [comment]
That worked - ended up with:
```

  Uri uHostUrl = new Uri(sHostUrl);
  HttpTransportType tt;
  HttpTransportType.TryParse(sTransport, out tt);

  SyncHub = new HubConnectionBuilder().WithUrl(uHostUrl, tt, options =>
  {
      options.DefaultTransferFormat = TransferFormat.Text;
      options.CloseTimeout = new TimeSpan(0, 0, 0, 10); //Default 5 seconds
  }).WithAutomaticReconnect().Build();

  SyncHub.HandshakeTimeout = new TimeSpan(0, 0, 0, 30);//Default 15 seconds
  SyncHub.ServerTimeout = new TimeSpan(0, 0, 1, 0);//Default 30 seconds
```
