### ISSUE TITLE
Why was the "Individual User Accounts" option removed?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#38583]
When creating an AP.NET Core Web API application, the *Authentication type* options now include:

- None
- Microsoft Identity Platform
- Windows

I understand Microsoft Identity Platform provides a lot of new and powerful features. But I just have a simple API that will be accessed by a handful of applications, perhaps with a couple of authorization levels. I'm not using Azure, Active Directory or anything like that. None of the available options would seem appropriate for my application. And so I'm left to write my own.

Why was the *Individual User Accounts* option removed? Isn't that still a viable option for developers who don't need Microsoft Identity Platform?

If Individual accounts was an option today, adding authentication to my Web API would be as straight forward as with MVC and Razor Pages. As it is, I'm left writing custom code, and every article I can find does it differently. I don't understand why this wouldn't be an option.

Microsoft Identity Platform just doesn't seem like a good option for me.

*Note: This was previously posted as https://github.com/dotnet/aspnetcore/issues/38457 but I was told that individual user accounts were never supported by Web API and the question was closed. However, I responded with proof that this claim was simply wrong.*

**Comment by HaoK** [comment]
The video is slightly misleading as the individual user account options in that selection is actually azure ad b2c as you can see here, so Javier is correct, WebAPI never supported asp.net identity.

![image](https://user-images.githubusercontent.com/6537861/142962708-125eb927-14db-4117-8536-62acd070e4f2.png)

**Comment by SoftCircuits** [comment]
> The video is slightly misleading as the individual user account options in that selection is actually azure ad b2c as you can see here, so Javier is correct, WebAPI never supported asp.net identity.

What about the documentation I posted?

And can anyone tell me why we wouldn't want this option for Web API? Seems like the viable options require significant programming that is easy to get wrong. I don't understand what I'm missing.

**Comment by gulbanana** [comment]
That documentation is for ASP.NET, not ASP.NET Core.

**Comment by SoftCircuits** [comment]
> That documentation is for ASP.NET, not ASP.NET Core.

That was the point: Why has the option been removed in .NET Core? And why can't it be restored?

**Comment by blowdart** [comment]
Because .NET Core does not ship with a token server. That decision was made over 5 years ago, and has been the subject of lots of community discussion, and it will not ship with a token server. There are community options for this, OpenIddict and Identity Server and we see no need to compete with those.

**Comment by SoftCircuits** [comment]
> Because .NET Core does not ship with a token server.

Well, that doesn't seem like a reason. Maybe I'll be able to find one of these many discussions about it. I haven't found any so far.
