### ISSUE TITLE
Blazor server side prefix url

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#38584]
I need to handle a dynamic url prefix for each page. How can I do this? 
I want to achieve something like this:
```
domain.com/prefix/home
domain.com/prefix2/home
domain.com/home
```
Ideally, you should handle regex. I am trying to solve the razor ``IPageRouteModelConvention`` but unfortunately it won't work for me.

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

It's not clear what you are trying to accomplish. Do you have multiple hubs for your blazor app?

**Comment by Alerinos** [comment]
@javiercn 
wants to create a prefix in routing. So that some value can be added before each routing. Example:
```
domain.com/{prefix}/routing
domain.com/s1/home
domain.com/s2/home
domain.com/test/home
```
And an option without a prefix.
``domain.com/home``

I want to make a language system. So that before each routing it is rigidly prefixed like: en-us
domain.com/en-us/home
But after entering the site, the prefix turns into a cookie and the user can already see a normal link without the prefix. (Site map for google with language prefix, user has no prefix)

Example, prefix ``pl-pl``
```
https://www.g2a.com/pl-pl/assassins-creed-steam-key-europe-i10000032971003
https://www.g2a.com/assassins-creed-steam-key-europe-i10000032971003
```

**Comment by javiercn** [comment]
@Alerinos I would handle that on the server before Blazor gets involved.

Map an endpoint to "/{prefix:regex([a-zA-Z]{2}(-[a-zA-Z]{2})?)}/{**rest}" grab the prefix, set it on a cookie and redirect to `**rest`

**Comment by Alerinos** [comment]
@javiercn 
```cs
                endpoints.MapGet("/{culture:regex(^[a-zA-Z]{{2}}(-[a-zA-Z+]{{2}})?$)=pl}/{**rest}", async context =>
                {
                    var culture = context.Request.RouteValues["culture"] ?? "pl";
                    var rest = context.Request.RouteValues["rest"];

                    /*
                     * Set cookie
                     */
                    var option = new CookieOptions();
                    option.Expires = DateTime.Now.AddYears(1);
                    context.Response.Cookies.Append("culture", culture.ToString() ?? "", option);

                    context.Response.Redirect($"/{rest}", permanent: false);

                    //return Task.CompletedTask;
                });
```
This causes a redirect of the type:
``domain.com/en-us/home`` on ``domain.com/home``
How to do that instead of redirecting ``context.Response.Redirect($"/{rest}", permanent: false);`` 

The page from the link above is displayed? How do I redirect traffic to _Host?

```cs
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/{culture:regex(^[a-zA-Z]{{2}}(-[a-zA-Z+]{{2}})?$)=pl}/{**rest}", async context =>
                {
                    var culture = context.Request.RouteValues["culture"] ?? "pl";
                    var rest = context.Request.RouteValues["rest"];

                    /*
                     * Set cookie
                     */
                    var option = new CookieOptions();
                    option.Expires = DateTime.Now.AddYears(1);
                    context.Response.Cookies.Append("culture", culture.ToString() ?? "", option);

                    context.Response.Redirect($"/{rest}", permanent: false);

                    //return Task.CompletedTask;
                });

                endpoints.MapBlazorHub("/Management/_blazor");
                endpoints.MapFallbackToAreaPage("/Management/{*path:nonfile}", "/_Host", "Management");

                endpoints.MapBlazorHub("/_blazor");
                endpoints.MapFallbackToAreaPage("/{*path:nonfile}", "/_Host", "Web");

            });
```

**Comment by javiercn** [comment]
@Alerinos If you don't do a redirect you can't change the URL on the browser, which doesn't match your initial description.

Otherwise, you can specify MapFallbackToPage multiple times to support both patterns.

**Comment by Alerinos** [comment]
```
endpoints.MapFallbackToAreaPage("/{culture:regex(^[a-zA-Z]{{2}}(-[a-zA-Z+]{{2}})?$)=en}/{*path:nonfile}", "/_Host", "Web");
```
I don't quite want to work ... I get this message from blazor: 
``Sorry, there's nothing at this address.``

Can you give me an example? @javiercn
