### ISSUE TITLE
> I am trying to access IWebHostEnvironment in a class library, referenced by my web project. It contains my business logic.

### ISSUE THREAD

**Issue by OriginatorStar** [dotnet/aspnetcore#38586]
> I am trying to access IWebHostEnvironment in a class library, referenced by my web project. It contains my business logic.

Do you need access to the WebRoot? If yes, then your class library needs to target netcoreapp3.0 (see https://github.com/aspnet/Announcements/issues/324) and it needs a `<FrameworkReference Include="Microsoft.AspNetCore.App" />`

_Originally posted by @davidfowl in https://github.com/dotnet/aspnetcore/issues/7749#issuecomment-546758234_

I did this, and got:

Version conflict detected for Microsoft.EntityFrameworkCore. Install/reference Microsoft.EntityFrameworkCore 3.1.3 directly to project Domain.Middleware.Telemetry to resolve this issue. 
 Domain.Middleware.Telemetry -> Domain.Web.Infrastructure 3.1.3 -> Microsoft.EntityFrameworkCore (>= 3.1.3) 
 Domain.Middleware.Telemetry -> Microsoft.AspNetCore.App 2.2.8 -> Microsoft.EntityFrameworkCore (>= 2.2.6 && < 2.3.0).	TelemetryMiddleware

How can I fix this. Domain.Web.Infraestructure must be 3.1.3. cannot change it, and Microsoft.AspNetCore.App max version is 2.2.8, so cannot update that.

Is this a void in the libraries and namespaces compatibility in net core framework?

**Comment by BrennanConroy** [comment]
Don't reference the nuget package Microsoft.AspNetCore.App.
In 3.1+ you should reference Microsoft.AspNetCore.App by framework reference, as shown in the comment you copied.
`<FrameworkReference Include="Microsoft.AspNetCore.App" />`

**Comment by adityamandaleeka** [comment]
@OriginatorStar Have you tried removing the package reference to `Microsoft.AspNetCore.App 2.2.8` after adding the FrameworkReference?

**Comment by OriginatorStar** [comment]
> Don't reference the nuget package Microsoft.AspNetCore.App. In 3.1+ you should reference Microsoft.AspNetCore.App by framework reference, as shown in the comment you copied. `<FrameworkReference Include="Microsoft.AspNetCore.App" />`

Thank you, it worked : D
