### ISSUE TITLE
Blazor+WASM+Static hosting: Is the advice to use a fallback Brotli decoder correct?

### ISSUE THREAD

**Issue by gulbanana** [dotnet/aspnetcore#38587]
Some hosting providers like Github Pages don't support the use of precompressed .gz or .br files. The Blazor hosting documentation (https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression) recommends that in this case developers use a Javascript Brotli implementation to serve up dotnet.wasm.br and friends. 

I've tried this in a trivial project (https://github.com/gulbanana/stains/commit/476164ce25b1e2dd257ff9392a98861311449452). In my unscientific experiment, decode.min.js works correctly and reduces the wire size considerably, from 2.8 MB transferred to 1.6 MB transferred... but the point of reducing bandwidth cost is to reduce loading time, and it doesn't do that. The overhead (an extra script, no autostart, in-JS decoding...) means that the Brotli-compressed version is _slower_ to load - 2.1 seconds instead of 2.0.

Without decode.min.js: 
![image](https://user-images.githubusercontent.com/1612285/142971853-a3b18586-40a1-440e-baac-f7a9d973cb27.png)
With decode.min.js: 
![image](https://user-images.githubusercontent.com/1612285/142971829-5012c677-e7a9-404b-ad59-fe46d22e0f3b.png)

This is actually the best result - I've seen load times as slow as 3.5 sec for the compressed version, but variance is high. What worries me is that I am using a fast computer. It's a Ryzen 5900x CPU, which should be able to execute a compression algorithm in Javascript quite quickly... what about slow mobile devices? Will they actually benefit from fallback-based decompression, or would they be better off to take the filesize hit and load the larger uncompressed runtime?

**Comment by SteveSandersonMS** [comment]
> In my unscientific experiment, decode.min.js works correctly and reduces the wire size considerably, from 2.8 MB transferred to 1.6 MB transferred... but the point of reducing bandwidth cost is to reduce loading time, and it doesn't do that. The overhead (an extra script, no autostart, in-JS decoding...) means that the Brotli-compressed version is slower to load - 2.1 seconds instead of 2.0.

You've got a tradeoff between bandwidth use and CPU time. For users with slow internet connections but fast CPUs, they will still appreciate the reduction in size and will get an overall faster load time. For users with a faster connection and slower CPU, the reverse may be true. So it's up to you to decide which one to prefer!
