### ISSUE TITLE
Blazor WebAssembly Hosted w/Individual Accounts does not work published to IIS. Multiple issues won't load.

### ISSUE THREAD

**Issue by Aquaritek** [dotnet/aspnetcore#38589]
### Describe the bug
Alright, so this could be just me being an idiot and expecting the default templates to work. However, for the dang life of me 20hrs at this now. I cannot get this application to run after being published. When I run locally through VS everything is fine (including running on an iisexpress instance).

After publish and deploy with every appropriate module installed (running another blazor server-side .net 6 application without a single hitch on the same server). 

I'm met with nothing but a blank screen on initial application load to the root of the domain with a 500 error. Go ahead and check it out here: **************

Then if you manually goto ************** this is where the real fun begins. Hardly a lick of information on this anywhere.
essentially the site cannot reach the OidcConfigurationContoller which results in a 500 at GetClientRequestParameters and that just locks the entire system from getting past the loading screen.

I don't know what exactly I need to do from here:
I have basically attempted every single fix I could find regarding the 500 at _configuration/{app}.Client issue (that's a rare one apparently)

I keep hearing about people running IS4 on another server.. Is that something you actually have to do, I thought the basic libraries were functioning within the template itself.

I am nearly complete in reading every single article and line over at: https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0

I'm just at a loss. The only thing I don't quite understand is the amount of detail the Identity articles go into at the docs website there. Do I need to continue configuration to the letter throughout that documentation? It doesn't make sense that everything works fine locally and just fails completely after publishing.

Eh.. I'm done for the day. Thanks in advance for any information here.

### To Reproduce
This happens even with the default template. The site I'm running has had further development but nothing at the core of the template has changed.

### Exceptions (if any)
500 Errors

### Further technical details
All the latest tooling
VS 2022 Preview
.Net 6.0
Server 2019 (ok not latest ugh..)
IIS 10.0.17763.1
Default BlazorWASM template with the fixens Hosted, IA, HTTPS, PWA

**Comment by Aquaritek** [comment]
Alright guys,

I was experiencing a ruthless ID10T error. 

However, I think this needs to turn into a straightforward documentation update. I don't have a lot of experience with IS4 and this all came down to certificate issues. 

It should clearly be states you must configure the project for production deployment with either an issued certificate for IS4 and or a self-signed one. However, I could never get a self-signed cert to work so I just bought a secondary one ugh!

You also have to make sure that installed in a LocalMachine store and specifically deployed through IIS.

What a freaking nightmare lol.

**Comment by SteveSandersonMS** [comment]
Thanks for confirming you got it to work!
