### ISSUE TITLE
Cannot use "checked" as variable name in razor file

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#38588]
### Describe the bug
Defining a variable with the name ```checked``` in a blazor project (in a razor file code section) causes unexpected compile errors:
```
error CS1001: Identifier expected 
error CS1002: ; expected
error CS1514: { expected
error CS1525: Invalid expression term '='
```

### Reproduce
Standard template (dotnet new blazorserver), modify `IncrementCount` in `Counter.razor` to:
```
    private void IncrementCount()
    {
        currentCount++;
	bool checked = false;
    }
```

**Comment by ShreyasJejurkar** [comment]
`checked` is a keyword in C# and it has a special meaning, you cannot use it as a variable name as you have done in your `IncrementCount()` method. 

More about keyword here -> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked

If you really wanted to use `checked` as a variable name then you can use it by prefixing it with `@` like this `@checked`. 
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGY4gNwmQAIssBjACwFNGBrVgE1oF5apANwUSpAJwAKBi3ZduASiFA==
