### ISSUE TITLE
Razor Class Library - Static Web Assets that are being built during the pack process don't get added in Net6.0

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/aspnetcore#38596]
### Describe the bug
Its a regression from .net 5.0 similar to this: https://github.com/dotnet/aspnetcore/issues/36740 

When creating staticwebassets as part of the build process (scss compiler etc.) they are not considered staticwebassets if the build is run as part of.
```
dotnet pack
```

Does net6.0 by any chance not honor ResolveStaticWebAssetsInputsDependsOn anymore?

If you change the project to net5.0 (and remove the incompatible features) it correctly packs on first try.

This is particularly problematic because it breaks our razor component builds that rely on creating staticwebassets during the build. As a workaround you can run ``` dotnet build ``` before packing but that also requires an adjustment everywhere.

### To Reproduce

Repro repository: https://github.com/Blackclaws/MinimalReproRazorClassPack

1. Check out project
2. Run 
```
dotnet pack -o pack
```
3. Unpack the resulting package, see that GeneratedFile is in content/wwwroot
4. Run
```
dotnet pack -o pack
```
again

5. Unpack the resulting package, see that GeneratedFile is now properly in staticwebassets/

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by javiercn** [comment]
@Blackclaws thanks for contacting us.

We did significant changes to the internal workings of static web assets in .NET 6.0. We published a blog post a couple of weeks ago and an experimental package that describes how to do this moving forward.

You can check them both [here](https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/).

Alternatively, if you change the target to run before AssignTargetPaths, that should work too.

Give the experimental package we published a try and let us know if you run into any issues, we are looking to make this scenario in a future release and are looking for feedback.
