### ISSUE TITLE
SignalR Java Library method "On" not calling error when class type has wrong parameters

### ISSUE THREAD

**Issue by diegocunhawarren** [dotnet/aspnetcore#38593]
### Describe the bug
When you call the method `on` of hubConnection with a Type class and this Type class has a wrong contract parameter type, the method `on` is never called with updates.

### To Reproduce
```
//Class model in project to be used on HubConnection on method
data class Ticker(val value: Double, name: String)

//Contract model sent by server
{
    value: 2.22,
    name: {
        name: "Foo",
        formatted: Foo
    }
}

//hub connection method
fun startHub(){
    hubConnection.on("MarketData", { logEvent(it.toString()}, Ticker::class.java)
}
```
- ASP.NET Core version: 6.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Android Studio Arctic Fox

**Comment by BrennanConroy** [comment]
> Type class has a wrong contract parameter type, the method `on` is never called with updates.

That's expected. We can't call your registered method if you don't use the type the server sends.
If you turn on logging you'll see that we log either a warning that no handler was found, or an error that we failed to call your handler (if one is registered with the wrong type(s)).

**Comment by diegocunhawarren** [comment]
Hey @BrennanConroy 

How can I turn on logging for this scenario?

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/aspnet/core/signalr/java-client?view=aspnetcore-6.0#add-logging
