### ISSUE TITLE
Blazor app fails to run with JS error "Failed to invoke 'StartCircuit' due to an error on the server" after upgrading from .NET5 to .NET6

### ISSUE THREAD

**Issue by MrYossu** [dotnet/aspnetcore#38599]
### Describe the bug
I have a Blazor server-side app that has been running under .NET5. I just tried upgrading to .NET6 by changing the `TargetFramework` value to `net6.0`, and upgrading/adding references to the ASP.NET packages as follows...

```xml

    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0">
```

I then deployed to a brand new test site.

When I access the site, Blazor stuff doesn't work, and the browser console shows the following error...

```
Uncaught (in promise) Error: Failed to invoke 'StartCircuit' due to an error on the server.
    at t.callbacks.<computed> (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at WebSocket.i.onmessage (blazor.server.js:1)
```

The app runs fine in VS2022, it's only when deployed that I get the problem.

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 Community on Windows 10 x64
- Include the output of `dotnet --info`: Can't do this on the server as I don't have access, but I know .NET6 is installed, as a brand-new (ie not upgraded from .NET5) Blazor app works fine.

Thanks

**Comment by javiercn** [comment]
@MrYossu thanks for contacting us.

Can you turn the logging level to Debug on the server so that we can you can get more details on the exception thats causing the issue?

**Comment by mkArtakMSFT** [comment]
Thanks for getting back to us, @MrYossu. Glad that you've managed to get things in good state.
