### ISSUE TITLE
Update MouseEventArgs. Add MovementX MovementY

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/aspnetcore#38602]
Add MovementX and MovementY to MouseEventArgs

**Comment by SteveSandersonMS** [comment]
I'll add this to the backlog. Note that if you need this functionality sooner, you can implement custom event args as described at https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0#custom-event-arguments

**Comment by ParadiseFallen** [comment]
@SteveSandersonMS  i have no access to that link

**Comment by oiBio** [comment]
Use this link
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0#custom-event-arguments

**Comment by ParadiseFallen** [comment]
I would like to see a more detailed example with the implementation of all handlers

**Comment by TanayParikh** [comment]
Resources:
- https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX
- https://github.com/dotnet/aspnetcore/pull/38792
