### ISSUE TITLE
Getting source IP behind proxy

### ISSUE THREAD

**Issue by SonoranBrian** [dotnet/aspnetcore#38607]
I have a .Net Core application running in a docker container as my backend service. Clients connect to the backend through HAProxy -> Kestrel -> .Net Core Service

I'm trying to capture the user's IP address, but am unable to get the true client IP.

startup.cs
```
public void ConfigureServices(IServiceCollection services)
        {
            // Proxy Forwarded Headers
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
                options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("::ffff:172.21.0.2"), 104));
            });
        }

---------------------------------------------

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseStaticFiles();
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
                ForwardLimit = 2
            });
            app.UseRouting();
            app.UseCors("CorsPolicy");
            app.UseAuthentication();
            app.UseAuthorization();
       }
```

Getting the client IP (Signalr)
```
// Extract user IP
        public IPAddress getIp(HubCallerContext cntxt)
        {
            // Return the Context IP address
            if (cntxt != null)
            {
                HttpContext request = cntxt.GetHttpContext();
                if (request != null)
                {
                    return request.Connection.RemoteIpAddress;
                }
                else
                {
                    return IPAddress.Parse("1.1.1.1");
                }
            }
            else
            {
                return IPAddress.Parse("0.0.0.0");
            }
```

The IP address captured is `::ffff:XXX.XX.X.X` (The X representing our HA Proxy server, not the client IP)

I've also tried manually setting the HAProxy forwarded IP to 1.1.1.1:  ```http-request set-header X-Forwarded-For 1.1.1.1``` but this still shows as the HAProxy's internal IP and not the forced 1.1.1.1.

In HAProxy if I try to enable `send-proxy` I receive the following error:
> Server example-backend/example_backend is DOWN, reason: Layer7 wrong status, code: 505, info: "HTTP Version Not Supported", check duration: 1ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.

Any help is greatly appreciated!

**Comment by adityamandaleeka** [comment]
@SonoranBrian @Plasma Sorry this was stuck in the wrong repo for a while. Are you still hitting this issue?

BTW this doc might be useful for troubleshooting: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0#troubleshoot
