### ISSUE TITLE
Layout in project templates with individual auth is no longer centered in 6.0 apps

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#38600]
Found during CTI testing:

### 5.0 
![image](https://user-images.githubusercontent.com/55483444/142369967-60e3f4db-71e7-4c99-a835-ca1a0f5933f1.png)

### 6.0
![image](https://user-images.githubusercontent.com/55483444/142369915-47fd5985-131d-44bd-9ad2-d4d32349aad0.png)

Perhaps this was an intentional choice in case this can be closed.

**Comment by pranavkm** [comment]
FYI @HaoK

**Comment by HaoK** [comment]
@blowdart thoughts on what we want to do for 7.0, do we want to make them centered again?

**Comment by blowdart** [comment]
It's weird footer is centered but header isn't. I have no thoughts on which is better, but it should be consistent. 

If I look at the [bootstrap 5 samples](https://getbootstrap.com/docs/5.1/examples/album/), the header is wrong, and footer is right, so if I have to make a choice, it's make it centered again.
