### ISSUE TITLE
Blazor issue with new DotNetStreamReference in net6

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#38618]
Hi, i would like to use the new `DotNetStreamReference` class to optimize file download in blazor wasm.

The sample code on https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0
show this js method:

```
async function downloadFileFromStream(fileName, contentStreamReference) {
  const arrayBuffer = await contentStreamReference.arrayBuffer();
  const blob = new Blob([arrayBuffer]);

  const url = URL.createObjectURL(blob);

  triggerFileDownload(fileName, url);

  URL.revokeObjectURL(url);
}
```

in this code the stream is full read on memory and the trigger the download...

```
const arrayBuffer = await contentStreamReference.arrayBuffer();
const blob = new Blob([arrayBuffer]);
```

 i would like to stream directly to disk, avoiding memory issues with large files, is this possible?

Thanks

**Comment by javiercn** [comment]
@Gambero81 thanks for contacting us.

I don't believe that's possible, the browser does not offer any API to do that, AFAIK. 

That said this is not a Blazor specific question, so I would check stackoverflow or a similar site to see if you can find more details on alternative approaches.
