### ISSUE TITLE
Authentication failure - return a message to the user?

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#38617]
At the moment, returning Failure from an AuthenticationHandler results in a 401 Challenge response. Is there a way to return an error message as the body of this response somehow? We want to indicate which part of the two tokens we receive is invalid.

Best regards,
D.R.

**Comment by Tratcher** [comment]
You could have the auth handler do that in the challenge. Here's an example where JwtBearer adds that information to the challenge headers:
https://github.com/dotnet/aspnetcore/blob/8d559c6c1a1d006807978310d2e685f53082dd8f/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L219-L286

**Comment by drauch** [comment]
I see, okay.

For further reference if somebody stumbles upon this thread. If you don't want to put it into the headers but into the body, you can use a very similar solution from https://stackoverflow.com/a/58643186/1400869 which has been pointed out to me by a colleague of mine.

Best regards,
D.R.
