### ISSUE TITLE
VS.Redist packages contain different .msi Package Codes than Bundles

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#38629]
This mismatch is new in 6.0.

The VS.Redist packages wind up with .msi's containing different Package Codes than the .msi's in the SharedFx Bundles - our current suspicion is that this is due to signing. We manually sign the VS.Redist .nupkg during every build, so post-build signing winds up treating the .msi contained there differently than the one in our bundles, and therefore gives them different package codes upon rebuild. It's possible we can do away with manual signing altogether in this repo.

Note this affected 6.0 RTM - installing the VS version containing RTM, after installing the RTM SDK/SharedFx/Hosting Bundle, will fail because the PackageCodes of the SharedFx .msi are different, so WiX detects a downgrade and fails the install.

Maybe relevant: https://github.com/dotnet/aspnetcore/pull/26506.

@safern @ericstj does dotnet/runtime ever manually sign its VS.Redist .nupkg's before pushing them to the VS Package feed?

CC @mmitche, @joeloff, @dougbu

**Comment by wtgodbe** [comment]
Also CC @Pilchie - this will affect anyone who installs the SDK (or Hosting Bundle, or standalone runtime), then installs the version of VS containing RTM. We're trying to figure out a workaround offline

**Comment by joeloff** [comment]
Note, this isn't so much a downgrade. We have two MSIs with the same version, ProductCode, UpgradeCode, but different PackageCode (this comes from the MSI summary information stream). It changes each time you rebuild and since post-build sign compiles/links the MSIs again, we get a new package code and then use the one MSI for VS and the post-build signed copy goes into all the standalone installers.

**Comment by safern** [comment]
From what I know and I can see on dotnet/runtime's official build the only thing we sign there is the cross dac. Everything else is signed at post build signing.

**Comment by joeloff** [comment]
@wtgodbe the redist packages don't need to be signed, only the contents (MSIs)

**Comment by mmitche** [comment]
What is supposed to happen is that if the msis are the **same file name** and have the **same file hash**, then the post-build signing system will recognize them as identical, dedupe them, sign and repack them a single time.

Do you have the exact file names that ended up with different product codes? That would point to either them being signed two different times, or repacked twice. I may be able to dig through the post-build signing logs to figure out why.

**Comment by wtgodbe** [comment]
The .msi is `aspnetcore-runtime-6.0.0-rtm.21526.8-win-x64.msi`, which has one PackageCode in `VS.Redist.Common.AspNetCore.SharedFramework.x64.6.0` and another in the SDK/Hosting Bundle/Asp.Net SharedFx installer

**Comment by joeloff** [comment]
This happens because the repacking compiles/links, which changes the PackageCode - this is different from the ProductCode and is generated during linking/compiling

**Comment by mmitche** [comment]
> This happens because the repacking compiles/links, which changes the PackageCode - this is different from the ProductCode and is generated during linking/compiling

In theory though, the compiling/linking should only happen once for each of these MSIs, so the product codes should remain the same. I'll poke on this in a few mins.

**Comment by joeloff** [comment]
The ProductCode won't change, the package code will when you invoke candle/light during post build signing.

**Comment by mmitche** [comment]
> The ProductCode won't change, the package code will when you invoke candle/light during post build signing. I'm almost 100% sure this happens during linking when Light writes the package summary information stream into the MSI - that's what holds the package code.

I think I'm missing something then. The VS.Redist packages produced by the build and the msi should be identical. Those VS.Redist packages produced during the runtime build are never pushed to the VS feed. They are only pushed after post-build signing happens.

**Comment by joeloff** [comment]
My understanding from talking to Will was that ASP.NET signed the MSI that went into the redist, and post build signed the copy of the MSI that went into the standalone installers and because post build runs candle/light to put the MSI together, the package code changes and differs from the MSI in the redist that's already signed.

**Comment by mmitche** [comment]
The MSI shouldn't be signed in the asp.net build because the msi also contains other files which need signing. So post-build signing should be handling all of the msis. The VS.Redist package is incomplete until post-build signing runs.

**Comment by wtgodbe** [comment]
It looks like I was wrong about the root cause here - we're not signing anything during the repo build.

But, I just looked at the staging pipelines for 6.0.0 and 6.0.1 - in both cases, the .msi package code is _not_ mismatched between `VS.Redist` and the SharedFx Bundle. Somehow the VS.Redist that got consumed by VS in 6.0.0 was different than the one produced by the staging build (it also doesn't match the unsigned one originally produced by AspNetCore). @mmitche any other ideas on how this could have happened?

For reference - 
Unsigned 6.0.0 PackageCode (`VS.Redist` nupkg, standalone .msi, .msi in bundles): `{26A1C3CD-DC54-4A97-ACBF-5ABA64122B94}`
Signed 6.0.0 PackageCode from staging pipeline (`VS.Redist` nupkg, standalone .msi, .msi in bundles): `{E8626F01-B37E-4680-9AA6-144F9D608B39}`
6.0.0 PackageCode from `VS.Redist` package in VS Feed: `{F3C8CA20-26C1-4198-9301-E09D259B850D}` (Package is [here]({F3C8CA20-26C1-4198-9301-E09D259B850D})

The package version of the VS.Redist package in all cases is `6.0.0-rtm.21526.8`

**Comment by wtgodbe** [comment]
Closing as it's not an aspnetcore issue
