### ISSUE TITLE
Unable to pack .NET 6 blazorserver as dotnet tool

### ISSUE THREAD

**Issue by Ne4to** [dotnet/aspnetcore#38620]
### Describe the bug
Unable to pack an empty .NET 6 Blazor Server project as dotnet tool.
I'm building a developer helper tool with web UI and would like to distribute it as a dotnet tool.

### To Reproduce
- dotnet new blazorserver
- modify .csproj
- dotnet pack

csproj modification:
```diff
<PropertyGroup>
  <TargetFramework>net6.0</TargetFramework>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>  
+ <IsPackable>true</IsPackable>
+ <PackAsTool>true</PackAsTool>
</PropertyGroup>
```

Minimal repo project: https://github.com/Ne4to/issues-22564

### Exceptions (if any)
> C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(411,5): error : Conflicting assets with the same target path 'issues-22564.styles.css'. For 'All' assets 'Identity: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle\issues-22564.styles.css, SourceType: Computed, SourceId: issues-22564, ContentRoot: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle, BasePath: _content/issues-22564, RelativePath: issues-22564.styles.css, AssetKind: All, AssetMode: CurrentProject, AssetRole: Primary, RelatedAsset: , AssetTraitName: ScopedCss, AssetTraitValue: ApplicationBundle, CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle\issues-22564.styles.css' and 'Identity: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle\issues-22564.styles.css, SourceType: Computed, SourceId: issues-22564, ContentRoot: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle, BasePath: _content/issues-22564, RelativePath: issues-22564.styles.css, AssetKind: All, AssetMode: CurrentProject, AssetRole: Primary, RelatedAsset: , AssetTraitName: ScopedCss, AssetTraitValue: ApplicationBundle, CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\obj\Debug\net6.0\scopedcss\bundle\issues-22564.styles.css'. [C:\Users\Ne4to\projects\GitHub\Ne4to\issues-22564\issues-22564.csproj]

### Further technical details
- ASP.NET Core version: 6.0 (but it works with .NET 5.0)
The issue is similar to: https://github.com/dotnet/sdk/issues/22564

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by SteveSandersonMS** [comment]
I'm afraid this just isn't a scenario we support. It might be possible for you to figure out some way to do it, but since it's not a scenario that many other customers are concerned with, it's unlikely it would be prioritised highly enough for us to make it a built-in feature.

Sorry I can't be more helpful here!
