### ISSUE TITLE
[Feature Request] - Add Support for rendering Render Fragment / Component into string

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#38622]
I would like to be able to render a RenderFragment or a Component into string

### Scenarios

I have a virtualized grid component, where cell templates are defined as render fragments.
I need to get innet html and inner text of the cell in order to support export and custom copy&paste.
It cannot be done using js interop, because not all rows are rendered because of Virtualize component.

Other scenarios are in the attached links, e.g. email templates.

### Describe the solution you'd like

```csharp:
[Parameter] public RenderFragment ChildContent {get; set;}

public string ExportAsString() {
    renderingService.RenderToString(ChildContent);
}
```

### Additional context

Requested also here: https://github.com/dotnet/aspnetcore/issues/9493 and  here: https://github.com/dotnet/aspnetcore/issues/22266

It has been asked also on stackoverflow: [How to render a Blazor component into an HTML string](https://stackoverflow.com/questions/60437439/how-to-render-a-blazor-component-into-an-html-string)

There is event 3rd party library trying to provide this functionality:
https://github.com/conficient/blazortemplater

Please, leave the issue open, so that other can vote for it :)

**Comment by SteveSandersonMS** [comment]
This duplicates https://github.com/dotnet/aspnetcore/issues/23258 and https://github.com/dotnet/aspnetcore/issues/38114 which already have more commentary and votes, so I'll close this one as a duplicate.
