### ISSUE TITLE
Blazor DynamicComponent does not pass parameters to component if case does not match

### ISSUE THREAD

**Issue by rborosak** [dotnet/aspnetcore#38635]
If you create a component dynamically like this

`<DynamicComponent Type="typeof(MyComponent)" Parameters="@(new Dictionary<string,object>() { {"myvalue", "Test" })"/>`

created component (`MyComponet`) does not get the "myvalue" parameter if the parameter on the `MyComponent` if defined like

`[Parameter] public string MyValue { get; set; }`

One would expect that the parameter names are case insensitive.

**Comment by SteveSandersonMS** [comment]
Thanks for the report. Are you able to supply a minimal repro project as a GitHub issue? We will then investigate.
