### ISSUE TITLE
Blazor performance with a large data set

### ISSUE THREAD

**Issue by alderic** [dotnet/aspnetcore#38636]
Hello,
mb I don't understand something, but why is the performance in blazor so low?

For example filling array of strings and ints values with 1 000 000 records:

**[JS](https://jsfiddle.net/dagaric/uf1q6svc/)** fill array with int values **20-50ms**, str values **200-300ms**

**[Blazor Wasm](https://blazorfiddle.com/s/5cq7l6h2)** fill array with int values **200-400ms**, str values **3000-4000ms**
(in .net6 the performance is the same)

the examples show simple code like this:
`var arr = [];`
`for (var i = 0; i < 1000000; i++){`
    `    arr.push(i);`
`}`
I understand that we pay for converting msil mono> wasm> native, but not so dramatically

**Comment by javiercn** [comment]
@alderic thanks for contacting us.

There are a few important things missing in your benchmark.
* It's not possible to tell if the assembly is compiled in Debug or Release configuration.
* You are running against the non-AoT version of the app which means all .NET Code is interpreted as opposed to the JS code that is JITed by the VM.

**Comment by SteveSandersonMS** [comment]
Hopefully this is adequately answered! Please remember to use AOT compilation if you want to check the performance of CPU-bound code.
