### ISSUE TITLE
Upgrade to .net 6.0 broke styles in Identity MVC pages

### ISSUE THREAD

**Issue by maxima120** [dotnet/aspnetcore#38637]
I have Angular SPA project which was built from `aspnetcore with identity` template for .net 5.0
After migrating to 6.0 the MVC pages responsible for identity now look differently.

### Describe the bug
The vertical space between elements in a form (at least Login and Register.cshtml) are now 0 - see the picture

![image](https://user-images.githubusercontent.com/10121753/143443010-c1cf1460-532a-4227-a7cc-4edf0dffce1b.png)

### Exceptions (if any)
there is nothing in dev console of the browser nor in VS Output windows

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 Pro
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
</details>

**Comment by blowdart** [comment]
Yup. This is due to the upgrade to bootstrap, and there's no clean path provided by bootstrap. We use their default styles, and don't customize at all. If you actually start from scratch you'll see it's very different,

![Screenshot 2021-11-25 051514](https://user-images.githubusercontent.com/796298/143448247-3e07d61e-dce7-4efd-a6d6-8ddf59d9a308.jpg)

What you have is a mix of the old UI and new CSS, so you can either switch back to bootstrap4, or revamp your layouts to use bootstrap5 and customize. 

If you want to switch back to 4 you can use an MSBuild property in your csproj file

```
<IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion>
```
