### ISSUE TITLE
Allow Blacklist mode for HttpLoggingMiddleware for logging Headers.

### ISSUE THREAD

**Issue by RaulBurian** [dotnet/aspnetcore#38634]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

We want to utilize the new out of the box `HttpLogggingMiddleware` that was introduced in .Net 6 for logging and diagnostics.
The issue we are currently facing right now is that the current behavior for logging headers is only to whiltelist allowed headers which proves to be very cumbersome in our case since we have many headers to whitelist.

### Describe the solution you'd like

We would like to be able to switch the mode for Redacting headers to a "blacklist" behavior. 

Taking inspiration from `Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.RedactLoggedHeaders` we could provide a way to allow us to blacklist headers we do not want either by providing a collection of blacklisted header names or by providing a predicate that checks if a header should be `Redacted`.

An initial proposal of how that could be done:

Create an enum for the `HeaderRedactMode.cs`

```
public enum HeaderRedactMode
{
    Whitelist, // the current behavior
    Blacklist, // switch to blacklist collection
    Predicate // switch to checking with a predicate
}
```

Inside `Microsoft.AspNetCore.HttpLogging.HttpLoggingOptions`

```

public Func<string, bool> ShouldRedactRequestHeader { get; set; } = (header) => false; // by default all headers are logged when opting in for predicate mode if one does not set the function

public HeaderRedactMode RequestHeaderRedactMode { get; set; } = HeaderRedactMode.Whitelist; // the default behavior for backwards compability

public ISet<string> BlacklistedRequestHeaders => _internalBlacklistedRequestHeaders;

internal HashSet<string> _internalBlacklistedRequestHeaders = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    HeaderNames.Authorization,
    // other common sensitive headers
}

// can be mirrored for ResponseHeaders as well
```

Then inside `Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware`

```
internal static void FilterRequestHeaders(List<KeyValuePair<string, object?>> keyValues, IHeaderDictionary headers, HttpLoggingOptions options)
{
    switch (options.HeaderRedactMode)
    {
        case HeaderRedactMode.Whitelist:
            FilterHeaders(keyValues, headers, new Func<string, bool>(headerName => options._internalWhitelistedResponseHeaders.Contains(headerName)));
            break;
        case HeaderRedactMode.Blacklist:
            FilterHeaders(keyValues, headers, new Func<string, bool>(headerName => !options._internalBlacklistedResponseHeaders.Contains(headerName)));
            break;
        case HeaderRedactMode.Predicate:
            FilterHeaders(keyValues, headers, options.ShouldRedactRequestHeader);
            break;
    }
}

internal static void FilterRequestHeaders(List<KeyValuePair<string, object?>> keyValues, IHeaderDictionary headers, Func<string, bool> headerInclusionPredicate)
{
    foreach (var (key, value) in headers)
    {
        if (headerInclusionPredicate(key))
        {
            keyValues.Add(new KeyValuePair<string, object?>(key, value.ToString()));
            continue;
        }
        keyValues.Add(new KeyValuePair<string, object?>(key, Redacted));
    }
}
```

### Additional context

Thank you for taking your time to read and consider my issue.

**Comment by blowdart** [comment]
We discussed this from a security point of view during development. Safelists are, well, much safer from a security point of view, because you know the context of your application and you know what's safe. 

An unsafelist is dangerous because you may end up logging sensitive information, like tokens, passwords, PII etc. If some in your team adds a new header which contains PII, but forgets to update the exclusions list the safe list approach has your back.

_Note that we try to avoid using whitelist & blacklist as terms_

**Comment by RaulBurian** [comment]
First of all, thank you for the quick reply.

I understand your point about enhanced security by only allowing safelists since it is harder to "leak" information that way.
I wanted to ask about this since for our use case unsafe lists would be more convenient and that is what we were using prior to the migration to .Net 6.

Also, thank you for the notice about the terms and I am sorry for them.
I will close the issue now then.

**Comment by blowdart** [comment]
Please don't concern yourself with the terms usage, it's one of those things where the industry is evolving and, if English isn't your first language, it's something that's not immediately obvious.
