### ISSUE TITLE
ASPNETCORE_URLS is being ignored in .NET 6 + React Template

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/aspnetcore#38631]
### Describe the bug

I set the `ASPNETCORE_URLS` value in `.env` to `https://redacted.azurewebsites.net`. When I clicked on `Fetch data`, I expected the request to be proxied to `https://redacted.azurewebsites.net/weatherforecast`. Instead I get a 404. 

When I run Fiddler, I don't see any attempt to contact the remote server.

I also tried changing `.env.development`.

### To Reproduce

1. Create an ASP.NET Core + React application using the built-in templates
2. Deploy the services to a server (e.g. Azure)
3. Open `.env` and set `ASPNETCORE_URLS` to the server in step 2.
4. Run just the client using `npm start`.

### Exceptions (if any)
404

### Further technical details
- ASP.NET Core version: .NET 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Command line.

Code from template: `ClientApp\src\setupProxy.js`

```
const createProxyMiddleware = require('http-proxy-middleware');
const { env } = require('process');

const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:12107';

const context =  [
  "/weatherforecast",
];

module.exports = function(app) {
  const appProxy = createProxyMiddleware(context, {
    target: target,
    secure: false
  });

  app.use(appProxy);
};
```

**Comment by Grauenwolf** [comment]
Here's the console output when I start the application:

```
C:\Temp\ClientApp>npm run start

> kpmg.mdp.dashboardnoauth@0.1.0 start
> rimraf ./build && react-scripts start

[HPM] Proxy created: [ '/weatherforecast' ]  ->  https://redacted.azurewebsites.net
i ｢wds｣: Project is running at http://192.168.5.136/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Temp\ClientApp\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Compiled successfully!
```

When I paste `https://redacted.azurewebsites.net/weatherforecast` into a browser, I get my expected result.

**Comment by javiercn** [comment]
@Grauenwolf thanks for contacting us.

The proxy doesn't change origins by default and doesn't target sites outside of localhost for security reasons. We recommend you check the react docs for details [here](https://create-react-app.dev/docs/proxying-api-requests-in-development/)

**Comment by Grauenwolf** [comment]
This should be clarified in the documentation provided by the readme in the template. It is not at all clear that a remote development server is not allowed, and that's a very common use case. 

For that matter, why does env.ASPNETCORE_URLS exist at all of it just going to be ignored and we're only allowed to change the port number?

In general, the file `setupProxy.js` in general is lacking the code comments that one would expect from a professional grade product.

****

Please don't just close tickets like this out of hand. Even if we don't get our desired outcomes, it demonstrates that work is needed on the documentation.

**Comment by Grauenwolf** [comment]
The link you provided doesn't really explain it well either. It talks about exposing the dev backend server accidentally, but that's not what's happening here. Instead, I want to proxy to what is effectively a production server that is already publicly available. 

And I'm not seeing `Invalid Host Header` errors as described by the link, suggesting that it's not related.
