### ISSUE TITLE
About time incorrect of docker image about aspnet-6 

### ISSUE THREAD

**Issue by tonyjianhu** [dotnet/aspnetcore#38648]
Hello:
     I ran asp.net core application in docker container , used version of .Net 6 for mcr.microsoft.com/dotnet/aspnet:6.0-focal mirror versions. In my program, executed:
[Console.WriteLine (Datetime.Now.ToString("yyyy-MM-dd HH:mm:ss"))] ,the command output was [2021-11-26 12:58:12]. And then I entered the container and executed   [date] command.The output was [Fri Nov 26 20:59:12 CST 2021].
That was almost an eight-hour difference.  In.NET 5, there is no such problem.

**Comment by javiercn** [comment]
@tonyjianhu thanks for contacting us.

@richlander can you transfer this to the dotnet-docker repo? For some reason I'm not able to

**Comment by yaobo-lab** [comment]
> @tonyjianhu thanks for contacting us.
> 
> @richlander can you transfer this to the dotnet-docker repo? For some reason I'm not able to

I have the same problem. How to solve？？

**Comment by yaobo-lab** [comment]
> Hello: I ran asp.net core application in docker container , used version of .Net 6 for mcr.microsoft.com/dotnet/aspnet:6.0-focal mirror versions. In my program, executed: [Console.WriteLine (Datetime.Now.ToString("yyyy-MM-dd HH:mm:ss"))] ,the command output was [2021-11-26 12:58:12]. And then I entered the container and executed [date] command.The output was [Fri Nov 26 20:59:12 CST 2021]. That was almost an eight-hour difference. In.NET 5, there is no such problem.

i konw the problem. the reason is :  You need to inject time zone environment variables  

for  example: 

`ENV TZ=Asia/Shanghai`
