### ISSUE TITLE
[Blazor] Custom input component doesn't re-render

### ISSUE THREAD

**Issue by aventus13** [dotnet/aspnetcore#38656]
### Describe the bug
I'm trying to create a custom component containing an input text element, and only allowing numeric values  within a specified range. If the provided value is out of the range, it should change back to the minimum or the maximum value, whichever is closer. However, when trying to use this component, it will only re-render if the value actually changed from one value to a different value. Otherwise, changing to the same value doesn't affect the input element which retains the entered, incorrect value.

I'm trying to figure out what's the best way to achieve this, and whether there is a problem with the way rendering works or if I don't understand it properly.

`NumberInput.razor`
```csharp
<input value="@Value"
       @onchange="InputChanged"
       class="form-control @(IsValid ? string.Empty : "is-invalid")"
       id="@Id"
       name="@Name">

@code {
    [Parameter]
    public bool IsValid { get; set; } = true;

    [Parameter]
    public string Id { get; set; }

    [Parameter]
    public string Name { get; set; }

    [Parameter]
    public int Min { get; set; }

    [Parameter]
    public int Max { get; set; }

    [Parameter]
    public int? Value { get; set; }

    [Parameter]
    public EventCallback<int?> ValueChanged { get; set; }

    private async Task InputChanged(ChangeEventArgs e)
    {
        // If the received value is not numeric then just reset the input with empty
        if (!int.TryParse(e.Value?.ToString() ?? string.Empty, out var value))
        {
            await ValueChanged.InvokeAsync(null);
            return;
        }

        Value = value switch
        {
            _ when value > Max => Max,
            _ when value < Min => Min,
            _ => value
        };

        await ValueChanged.InvokeAsync(Value);
        // StateHasChanged(); // Even when this is uncommented it doesn't make the component to re-render
    }
}
```

`Parent component using the above`
```csharp
<NumberInput @bind-Value="Model.CompletionPercent" IsValid="@Model.IsCompletionPercentValid" Min="0" Max="100" />
```

### To Reproduce
- Use the above component
- Enter value 99
- The value 99 will show as expected in the input element
- Enter value 101
- The value will change to 100 as expected, given that it's the maximum allowed value
- Enter value 101 again

Expected outcome
- The value will change to 100 again

Actual outcome
- The value remains displaying as 101

Please note that the above outcome will also occur even if `StateHasChanged` is invoked after each `InputChanged` trigger. It looks like because the parent component receives the same value (100), the `NumberInput` doesn't re-render. I don't understand though why invoking `StateHasChanged` doesn't change the behaviour.

**Comment by pranavkm** [comment]
Have a look at https://docs.microsoft.com/aspnet/core/blazor/components#overwritten-parameters. Assigning a component parameter after it has been initialized can result in the kind of behavior you're observing.

**Comment by aventus13** [comment]
Thanks for your response @pranavkm. Unfortunately, even if I don't overwrite the passed-in parameter value in the child component, and use a backing property instead, the issue remains. 

When using the code below, I'm using a `RawValue` property to store the current value, and bind that value to the `input` HTML element. Then in the event handler I perform the decision making on what the new value should be, and pass it on. Even though the new value gets assigned to `RawValue`, the input element doesn't update.

```csharp
<input value="@RawValue"
       @onchange="InputChanged"
       class="form-control @(IsValid ? string.Empty : "is-invalid")"
       id="@Id"
       type="number"
       min="@Min"
       max="@Max"
       step="1"
       name="@Name">

@code {
    // The new backing property that is bound to the input element
    private string RawValue { get; set; }

    [Parameter]
    public bool IsValid { get; set; } = true;

    [Parameter]
    public string Id { get; set; }

    [Parameter]
    public string Name { get; set; }

    [Parameter]
    public int? Min { get; set; }

    [Parameter]
    public int? Max { get; set; }

    [Parameter]
    public int? Value { get; set; }

    [Parameter]
    public EventCallback<int?> ValueChanged { get; set; }

    protected override void OnInitialized()
    {
        // Assign the initial value
        RawValue = Value?.ToString();
    }

    private async Task InputChanged(ChangeEventArgs e)
    {
        if (!int.TryParse(e.Value?.ToString() ?? string.Empty, out var value))
        {
            RawValue = null;
            await ValueChanged.InvokeAsync(null);
            return;
        }

       // Decide what is the new value
        var newValue = value switch
        {
            _ when value > Max => Max,
            _ when value < Min => Min,
            _ => value
        };

       // Assign to the bound property
        RawValue = newValue?.ToString();

       // Pass it on to parent
        await ValueChanged.InvokeAsync(newValue);
        // StateHasChanged();
    }
}
```

**Comment by aventus13** [comment]
Moreover, the same problem occurs if I completely comment out updating parent's value. In the example below, the only value that I actually update is `RawValue`, and try to force a state change. Yet, the input element continues displaying an invalid value.

```csharp
    private async Task InputChanged(ChangeEventArgs e)
    {
        if (!int.TryParse(e.Value?.ToString() ?? string.Empty, out var value))
        {
            RawValue = null;
            //await ValueChanged.InvokeAsync(null);
            return;
        }

        var newValue = value switch
        {
            _ when value > Max => Max,
            _ when value < Min => Min,
            _ => value
        };

        RawValue = newValue?.ToString();
        //await ValueChanged.InvokeAsync(newValue);
        StateHasChanged();
    }
```

**Comment by aventus13** [comment]
I have fixed this by setting the `RawValue`, yielding a `Task` to ensure that the new value is included in the updated render tree, and then following the standard way of updating to a new (corrected) value. However, I would welcome any comments as I'm curious if there is a better/more optimal solution to this problem.

```csharp
    private async Task InputChanged(ChangeEventArgs e)
    {
        if (!int.TryParse(e.Value?.ToString() ?? string.Empty, out var value))
        {
           // This "hack" is needed to ensure that the UI re-renders if invalid input is provided, 
           // i.e. a text is inserted instead of a number for a second time
            RawValue = RawValue == null ? string.Empty : null;
            await ValueChanged.InvokeAsync(null);
            return;
        }

        RawValue = value.ToString();
        await Task.Yield(); // Yield and await to ensure that the UI gets updated

        var newValue = value switch
        {
            _ when value > Max => Max,
            _ when value < Min => Min,
            _ => value
        };

        // The actual value we want to use and display
        RawValue = newValue?.ToString();
        await ValueChanged.InvokeAsync(newValue);
    }
```

**Comment by pranavkm** [comment]
You could substitute the `Task.Yield()` with a `StateHasChanged()` callback (it's effectively what ComponentBase does when the event handler yields - https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs#L301-L315). Glad you got this sorted!
