### ISSUE TITLE
Option to have area views without an areas folder

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#38650]
There was a way to previously enable this before .NET 6. Click [here](https://github.com/aspnet/Razor/issues/2425) to view the original issue. However this no longer works as now Razor views are compiled using source generators.

I have upgraded the samples to show a working ASP.NET Core 5 application and an almost identical app targetting ASP.NET Core 6 which does not work. To test run the applications and click on the "MyLibrary" link.

[AspNetCore5.zip](https://github.com/dotnet/aspnetcore/files/7609050/AspNetCore5.zip)
[AspNetCore6.zip](https://github.com/dotnet/aspnetcore/files/7609054/AspNetCore6.zip)

When I compare .NET 5 which produces the following attribute (with the MSBuild metadata fix in the original issue):

```
[RazorSourceChecksum("SHA1", "xxx", "/MyLibrary/Views/Home/Index.cshtml")]
```

However in .NET 6 it produces:

```
[RazorCompiledItemMetadata("Identifier", "/Areas/MyLibrary/Views/Home/Index.cshtml")]
```

Therefore from my understanding I need to override the identifier produced in the `RazorCompiledItemMetadataAttribute`. Searching for that led me to the [CreateNewOnMetadataUpdateAttributePass](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/CreateNewOnMetadataUpdateAttributePass.cs) class. It seems the indentifier's value is generated by the following code:

```
var identifierFeature = Engine.Features.OfType<IMetadataIdentifierFeature>().First();
var identifier = identifierFeature.GetIdentifier(codeDocument, codeDocument.Source);
```

I'm guessing I need to implement my own `IMetadataIdentifierFeature` and register it first in the list of features. This is where I got lost as I can't see how I can inject my own feature. I'll keep looking but if you could help point me in the right direction or let me know if I'm going down the wrong path that would be appreciated.

**Comment by pranavkm** [comment]
You could consider turning off the source generator by adding `<UseRazorSourceGenerator>false</UseRazorSourceGenerator>` to the project file which should restore parity with the 5.0 behavior. In general, we don't really have support consuming the Razor compiler as a library, so I'm not sure how far you'd get tweaking that.

**Comment by nfplee** [comment]
Thanks but does this mean hot module reloading will not work? Although I couldn’t get hot module reloading to work for razor class libraries anyway.

**Comment by pranavkm** [comment]
> but does this mean hot module reloading will not work

Yup. Turning off the source generator would disable hot reload for cshtml / .razor files.

**Comment by nfplee** [comment]
I’ll leave this open as it’s a regression.

Is hot module reloading supposed to work for views within a razor class library (Microsoft.NET.Sdk.Razor)? Even if I have my view contained within an areas folder I still cannot get hot module reloading to work although manually reloading does. It seems to work fine in the view is within an area in the web (Microsoft.NET.Sdk.Web) project.

**Comment by nfplee** [comment]
Can you please re-open this.
