### ISSUE TITLE
Performance issue (2 second delay) in use of KestrelServerOptions.Listen compared to ListenLocalhost or ListenAnyIP for Grpc

### ISSUE THREAD

**Issue by AlexVallat** [dotnet/aspnetcore#38651]
### Describe the bug
Using `ConfigureKestrel(options =>{ options.Listen(IPAddress.Loopback,` there is a 2 second delay before responding to a request from a Grpc client. This delay is not present when using `ConfigureKestrel(options =>{ options.ListenLocalhost(`, which should be equivalent. This also applies to `options.Listen(IPAddress.Any,` compared to `options.ListenAnyIP(`. I would expect both to be equivalent.

### To Reproduce
Start with the standard Grpc Greeter sample: https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio (or https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/grpc/grpc-start/sample6)

Modify it by adding to the server Program.cs, before `builder.Build()`:

```c#
builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(IPAddress.Loopback, 7091, configure =>
    {
        configure.UseHttps();
    });
});
```

Run the client and note a 2 second delay before the SayHelloAsync call returns.

Modify the code to instead be:

```c#
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenLocalhost(7091, configure =>
    {
        configure.UseHttps();
    });
});
```

Note that there is no delay when running the client. The same test can be done with `options.Listen(IPAddress.Any,` compared to `options.ListenAnyIP(`

Tested under net6.0 and net5.0

**Comment by Tratcher** [comment]
The difference between these pairs of APIs is that `Listen(IPAddress.Loopback` and `Listen(IPAddress.Any` only listen on IPv4, while `ListenLocalhost` and `ListenAnyIP` listen on both IPv4 and IPv6. DNS resolves IPv6 addresses first, so the client tries to connect, times out after 2s, and then retries on IPv4. This is all by design.

**Comment by AlexVallat** [comment]
Ah, mystery solved! Thank you for answering.
