### ISSUE TITLE
Blazor WASM application Hangs on MSAL Authentication

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#38653]
.Net 5 & .Net 6

I have a Blazor Wasm using Azure AD Authentication

Program.cs
```csharp
builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAD", options);
});
```

appsettings.json
```json
"AzureAD": {
    "ProviderOptions": {
      "Authentication": {
        "Authority": "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555",
        "ClientId": "11111111-2222-3333-4444-555555555555",
        "RedirectUri": "URL DE PROD",
        "PostLogoutRedirectUri": "URL DE PROD",
        "ValidateAuthority": true
      },
      "DefaultAccessTokenScopes": [
        "openid",
        "offline_access",
        "https://graph.microsoft.com/User.Read"
      ],
      "LoginMode": "redirect",
      "Cache": {
        "CacheLocation": "LocalStorage"
      }
    }
  }
```

When authenticating the application hangs on code reception:

https://localhost:5001/authentication/login-callback#code=0.AQkATCPeDuwBZkeUL-NyxJ-DnkVC9cdHKE5Eqq6Vdp3VDegJAMc.AQABAAIAAAD--DLA3VO7QrddgJg7Wevr5XLHSvF2swPM7D4b5t8mlbEc-C154Ehe5HV9aBE8-1X8pzMqgD_nUf0t9n3ZlznuWdoExmiNqPF5QVk_nnFhX3lvOzUeG-52Z7uK_lANjBETQ8QfjEfbUqOWGHpRslopGeFSvkexy-y6EHlZfAAi9reTowISinz1iOrPfHtfttDqREue4WwW2zjBoJwIQf27GU2GoSW2ydoVgmEuA3gf8dlBEIcecjvOUwAHlrdQsn1YU9UU11X0j6CFWWoJ9bwXAgrEN9TtaJUNxAgltmWefDIl8G9OZntWQph4crc7YjA7r0N4vlPvQNU744Z-39lZ3TRRTbLgLTXRHLXgeKj6ccfWj1Wr5yUB4IUvPP2IRllA9zm45YKeoB_9aLkuBjHJJ92foG89n3JZxs06HAc0xUf45z826BwS-p6wsFBHmpofi_E0eL5hCOH_X5ssG4SPIa2U_Ru6OJXKp9uB8AIMNvDBmANVmkPUmtiX9aZkzpaAh1XSWdFkTUJ6uz4rug3MFmJlKPPqWYdHgCTAUo4i6THuSUQDfgPVcyQ6v-GcKUncI57hkMYCg-MwcFgV9bxNoJoTxfmdUlMneaLO5aQ_ntXgLXt5nRfL-bao6iBimzWWYqwTLlS1SzXl1fry3m5XzEWvbe36ktaaGNHB2Vcy3gvJUUpobpabeQ3C9NUXOH8HJonG8jPHCwMTRZm6bdby7xChHmqtJB-VQdeiCThAqTcv23oCDab_-rify_29Ix67LBx6llHtR_5KZBsBTHIyttMV7hDowCjjEZwGB-AmepfSKcGp-7TkJQvnG9rhYM4gAA&client_info=eyJ1aWQiOiI4Zjc5Nzg5ZS02ZjBjLTQ5MTUtOTNhMi04YTcyZTQxNjg1YzQiLCJ1dGlkIjoiMGVkZTIzNGMtMDFlYy00NzY2LTk0MmYtZTM3MmM0OWY4MzllIn0&state=eyJpZCI6IjQ0YmZiOTg4LTU5ZWYtNDE5Zi1hYzIzLWRjNjhlNDEzNjJjZCIsInRzIjoxNjM3OTQyODY2LCJtZXRhIjp7ImludGVyYWN0aW9uVHlwZSI6InJlZGlyZWN0In19%7cSyB9CFaZlcvIzyytvYXAV1Yz0bc9azio0rdjpWkbQCs&session_state=d280705e-3e63-4b17-a828-7f15f4d8b770

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by adam-becker** [comment]
We are also seeing this exact same thing while developing a Blazor WASM application. The issue is intermittent, sometimes it doesn't happen at all. The really odd thing is if we open the developer tools then it stops hanging and proceeds as usual. I can try to provide more information if that would help.
