### ISSUE TITLE
How to detect whether IJSRuntime is initialized?

### ISSUE THREAD

**Issue by zxyao145** [dotnet/aspnetcore#38664]
Hi all, I'm I'm using blazor (serve mode), when render-mode is ServerPrerendered, the injected IJSRuntime cannot be used if `((Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime)value).IsInitialized` is false. I want to assign it to a variable and save it, is there any way to detect whether it is available except to the assign it to a variable in `OnAfterRenderAsync`.

 My code  like this, and I want to detect whether Store.JsRuntime is available. 

```c#

public partial class App
{
    [Inject]
    public IJSRuntime JsRuntime
    {
        get => Store.JsRuntime;
        set => Store.JsRuntime = value;
    }
}
```

I've used IServiceProvider as follow, but it doesn't work:

```c#
internal static IJSRuntime  GetJSRuntime (out IServiceScope scope)
{
    scope = ServiceProvider.CreateScope(); // ServiceProvider is IServiceProvider
    try
    {
        return scope.ServiceProvider.GetService<IJSRuntime>();
    }
    catch (Exception)
    {
        scope.Dispose();
        throw;
    }
}
```

**Comment by pranavkm** [comment]
> is there any way to detect whether it is available except to the assign it to a variable in OnAfterRenderAsync.

Unfortunately not. Determining if `OnAfterRenderAsync` has been executed is the only way to detect this. Creating a new instance of IJSRuntime is not going to help since it's only initialized after a connection to the browser has been established.

**Comment by zxyao145** [comment]
OK, so the best way to save it now is to do it in OnAfterRenderAsync

**Comment by pranavkm** [comment]
Yup. If you absolutely needed it, you could register something in DI that is initialized by the root component and consume it in your JSRuntime wrapper. https://github.com/dotnet/aspnetcore/issues/17282#issuecomment-557147273
