### ISSUE TITLE
How get render mode?

### ISSUE THREAD

**Issue by zxyao145** [dotnet/aspnetcore#38663]
Hi everyone, is there any to get the render mode in blazor? I want to know if it's render as WASM or Server or ServerPrerendered. 
Thanks a lot!

**Comment by pranavkm** [comment]
`OnAfterRenderAsync` isn't called during pre-rendering. You can use that to determine if the component isn't being pre-rendered: https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#detect-when-the-app-is-prerendering. 

> I want to know if it's render as WASM or Server 

You can use `OperatingSystem.IsBrowser()` to determine if the component is being executed in the context of browser-webassembly.

**Comment by zxyao145** [comment]
Hi, 
>OnAfterRenderAsync isn't called during pre-rendering. You can use that to determine if the component isn't being pre-rendered: https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#detect-when-the-app-is-prerendering.

I think this is not elegant enough. For some blazor extension libraries, there may not be any blazor components (OnAfterRenderAsync cannot be used). So is there a better way?
