### ISSUE TITLE
Add Compile Time pre processor for WASM

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#38667]
Currently while writing blazor libraries , only way to know if blazor server or wasm which is the current platform
 ```cs
if(OperatingSystem.IsBrowser())
         IsWasm = true;
```

if there is compile time processor directive  like
```cs
#if __BLAZORWASM
```

it would make life much easier.
MAUI for supported platform does same thing eg `ANDROID`
Kindly add some compile time functionality to do the same.

**Comment by pranavkm** [comment]
Unlike MAUI, Blazor WASM isn't a target platform. For instance, during pre-rendering, components from a Blazor WASM app are executed in the context of a .NET Core app. Using the runtime check is the only way to infer the executing context at this time.
