### ISSUE TITLE
[Blazor] State manager for blazor maybe other

### ISSUE THREAD

**Issue by timeshift92** [dotnet/aspnetcore#38665]
### Is your feature request related to a problem

First of all, many thanks for the work done, please add a status manager, https://github.com/jspuij/Cortex.Net. there is one library if you look and compare with others, then the idea of ​​implementation is convenient, so I think it is necessary to add hooks to the blazer to create a glabal state

### Describe the solution you'd like
Adding state manager

### Additional context
https://github.com/jspuij/Cortex.Net

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
