### ISSUE TITLE
MapControllers has no effect?

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/aspnetcore#38672]
As a part of a pet-project, I'm working on a mini-framework to rapidly prototype ready to use asp.net core services which:
- can be natively hosted on kubernetes
- consist of preconfigured pipelines so that they share behavior and integrate with kubernetes
- use `IHost` instead of `WebApplication` b/c I need more control over my app than the WebApplication provides (such as support for `CancellationToken` in `RunAsync` as I like to start/stop my service instances in integration tests

One of the service "modes" is "Api Controller". 

In this case the service is expected to be configured in the same way as a minimalistic dotnet template which uses ASP.NET Core Controllers & Open API support. In order for this to happen, the service needs to :

- register required authorization services via `services.AddAuthorization()`
- register required controller services via `services.AddControllers()`
- register required middleware via:
```csharp
        app.UseRouting();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
``` 

### Describe the bug
The service starts properly, however:
- `/swagger` endpoint does not indicate any other endpoints are present
- `/weatherforecast` endpoint returns a 404

> **Note**
> - I'm not getting this behavior when using minimalistic APIs via `.MapGet()`
> - I'm not getting this behavior when using HotChocolate nad mimicking the startup sample with GraphQL

### To Reproduce
I've managed to create a minimalistic repro project located [here](https://github.com/mmisztal1980/net6ihost-repro) which is consistently failing on my Windows and MacOS machines.
- download dotnet sdk `6.0.100`
- clone the repository
- build the `Repro.ApiControllers.Demo`
- run the `Repro.ApiControllers.Demo`
- attempt to access `/weatherforecast` (404 will be returned)

### Exceptions (if any)
None. I suspect it's either an interesting issue or a really stupid bug, however I haven't been able to spot this for the past couple of evenings.

### Further technical details
- ASP.NET Core version:  6 (dotnet sdk 6.0.100)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 v4.8.04.084
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
 Maciek@KATANA  ~  dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by pranavkm** [comment]
Likely a dupe of https://github.com/dotnet/aspnetcore/issues/7315. https://github.com/dotnet/aspnetcore/issues/7315#issuecomment-482458078 has a workaround. Could you give it a try and see it addresses your issue?

**Comment by mmisztal1980** [comment]
@pranavkm I've added a commit to reflect the comment from #7315 and it started working as described.

Given the problem appears to be related to the `Startup` class's location itself (if my understanding is correct) and the original suggestion was made by @davidfowl I feel maybe it's possible to "pivot" the solution slightly? I fear that the solution might impact running the service from test assemblies negatively.

@davidfowl is it possible to compose the processing pipeline without the `Startup` class when using the `IHost` ? We sure can register the required services via `ConfigureServices`, but what about the pipeline itself?
- can it be done?
- would that solve the problem?

**Comment by davidfowl** [comment]
You can use `Configure(Action<IApplicationBuilder>)` to build the pipeline without a startup

**Comment by mmisztal1980** [comment]
Hi @davidfowl , thanks for your suggestion. Do you feel this will be a viable workaround?

**Comment by davidfowl** [comment]
https://github.com/mmisztal1980/net6ihost-repro/pull/1

**Comment by mmisztal1980** [comment]
@davidfowl has provided a fix for the `Startup`-less version of the problem with a brief explanation in the PR above.

Again, thank you for spending time on this.
