### ISSUE TITLE
Ability to read page title in a .razor file (e.g. `layout.razor`)

### ISSUE THREAD

**Issue by conficient** [dotnet/aspnetcore#38686]
With .NET 6 we are able to set a browser page title using the `<PageTitle>` component in a `.razor` file, which is rendered in the `<head>` using the `<HeadOutlet>` component. All good.

I wished to use the page title in a `<h1>` tag that is in the `MainLayout.razor` template - however I could not see a way to obtain this from the way `<HeadOutlet>` works?

I was able to make a work-around by creating a cascading `PageManager` class, and setting the page title via this, but it seems it should be easier?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is no better way to do this yet, so what you've got to is a fine solution. We plan to improve this in the future as part of the #28182
