### ISSUE TITLE
Blazor Wasm: Guidance on updating integrity digest of blazor.boot.json after renaming .dll files 

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#38691]
We have developed a Blazor WASM application using .Net 6. However, Azure Application Gateway was blocking .dll and .dat files. So I followed the guidance [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0) to rename .dll to .bin files using the post-publish Powershell script provided in the linked article. However, because the contents of the blazor.boot.json got changed, this file is now getting blocked due to integrity check failure. 

Could you please update the documentation to provide the step to fix the integrity digest of blazor.boot.json. Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@danroth27, @SteveSandersonMS do you know how this is done?

**Comment by SteveSandersonMS** [comment]
There’s only a hash to validate in the PWA case. For non-PWAs, you can freely edit blazon.boot.json, whereas for PWAs you’d also have to update the hash in the service worker assets manifest JSON file.

**Comment by bancroftway** [comment]
@SteveSandersonMS, for the PWA case, what command can I issue to automatically update the hash of blazor.boot.json inside the service worker? Thanks

**Comment by SteveSandersonMS** [comment]
@bancroftway It's probably easier not to modify the `blazor.boot.json` file at all. Instead, you could supply a custom [loadBootResource](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0#load-boot-resources) function that replaces each of the URLs with a modified one while loading. For example, 


```html
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      if (type === 'assembly') {
        return defaultUri.replace(/\.dll$/, '.dat');
      }
    }
  });
</script>
```

This will cause the browser to fetch the assemblies from URLs ending with `.dat` instead of `.dll`.

**Comment by javiercn** [comment]
The appropriate way to do this is via customizing the deployment layout. https://devblogs.microsoft.com/dotnet/custom-deployment-layout-for-blazor-webassembly-apps/
