### ISSUE TITLE
[.NET 6 WebAssembly] What i can use to encrypt/decrypt ?

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#38695]
Hello guys, for my project i need to encrypt/decrypt data in a webassembly app (actually only decrypt because the encryption is not made by a webassembly app).

All the example i find on internet finish with Cryptographic exception, i know most of encryption class is not supported on webassembly, but i really need something to make the job.

this encryption don't really need to be super strong, it just here to prevent the user update the data by itself (if he do that it will finish on error and im fine with that)

Even something which is not dependant of system.Cryptography and who can be hack by a specialist is OK, the end user are not specialist, but without that they can easily overpass the licencing system of my client which is a big problem (its not public app, its an app for companies running only on intranet)

the data encrypted is store in a shortcut the user have on his desktop, shortcut which will launch chrome with the url of my webapp and a GET  parameter ?MyData=<EncryptedData>, data i decrypt at the startup. (i want to conserve the integrity of EncryptedData)

Can you provide some guideline or example of code ?

thanks !

PS : I target specifically chrome, in case there is some browser limitation

**Comment by sps014** [comment]
This is expected behaviour `System.Cryptography` is not supported at this moment,  For workaround you can use JS cryptographic libraries and use `JS interops` to call those functios C# side.

**Comment by mkArtakMSFT** [comment]
Thanks for your question.
@sps014 is right.
Here is a writeup on the current state of Cryptography support on Blazor WebAssembly: https://github.com/dotnet/designs/blob/main/accepted/2021/blazor-wasm-crypto.md
