### ISSUE TITLE
Problem using Microsoft.AspNetCore.ClientAssets with spaces in outputpath

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/aspnetcore#38702]
When using the experimental Microsoft.AspNetCore.ClientAssets, library the build fails when there is a space in the output path.

The build output shows:
``` `webpack --mode development "--output-path"``` 
```"D:\My" "Projects\Redacted\src\MyLibrary.Components\obj\Debug\net6.0\clientassets/"` ```

but should say:
``` `webpack --mode development --output-path```
```"D:\My Projects\Redacted\src\MyLibrary.Components\obj\Debug\net6.0\clientassets/"` ``` 

(for readability I put the path part on the next line) 

### Further technical details
Version: "0.1.0-alpha.21528.2"
Net6.0:

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is going to be addressed as part of https://github.com/dotnet/aspnetcore/issues/38445
