### ISSUE TITLE
hot reload does not work with razor page project (that uses net5.0 style API)

### ISSUE THREAD

**Issue by solrevdev** [dotnet/aspnetcore#38717]
### Describe the bug
While hot reload works for me when I create a razor pages project using `dotnet new webapp` it does not work with existing projects that I have migrated from .NET5.0 to .NET6.0 and where I use Startup.cs over the new minimum API 

My existing projects have been upgraded through the .NET Core versions and I am yet to migrate any to use the minimum API's so I suspect that is the issue.

### To Reproduce
I have taken an existing project and paired it down as much as I can so that I can repro it. 

Clone the following and run dotnet watch. Then edit Pages/Shared/_Layout.cshtml and watch it NOT hot reload as it should.

https://github.com/solrevdev/hotreload-issue

### Further technical details
<details>
<summary>dotnet --version</summary>

```text
 dotnet --version
6.0.100
```
</details>

<details>
<summary>Visual Studio Code Insiders</summary>

```text
Version: 1.63.0-insider
Commit: b9cf83f70bb6b4697b544a97c7056dfd28fccc5f
Date: 2021-11-30T05:13:11.628Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
</details>

<details>
<summary>dotnet --info Output</summary>

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

</details>

**Comment by pranavkm** [comment]
dotnet-watch specifically ignores cshtml files if you have runtime compilation enabled since they effectively serve the same purpose during development: https://github.com/solrevdev/hotreload-issue/blob/master/web.csproj#L9-L11. Try removing the reference and it should work.

**Comment by solrevdev** [comment]
> dotnet-watch specifically ignores cshtml files if you have runtime compilation enabled since they effectively serve the same purpose during development: https://github.com/solrevdev/hotreload-issue/blob/master/web.csproj#L9-L11. Try removing the reference and it should work.

Bingo! 🎉

That was indeed the issue

For reference I've created a [pull request](https://github.com/solrevdev/hotreload-issue/pull/2/files) in my repro repository and I'll summarise here the changes quickly. 

StartupServicesExtensions.cs

```diff
-   services.AddControllersWithViews().AddRazorRuntimeCompilation();
-   services.AddRazorPages().AddRazorRuntimeCompilation();
+   services.AddControllersWithViews();
+   services.AddRazorPages();
```

 web.csproj
 
 ```diff
-   <ItemGroup>
-       <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />
-   </ItemGroup>
 ```


Thanks so much for your help, will close the issue now.  🙏
