### ISSUE TITLE
Due to seasonal holidays, many of our members are taking time off. Please expect delayed responses until early January.

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#38711]
As the holidays are approaching, many of our team members are taking time off to get some rest.
Because of this, responses to new issues, PRs, and comments may be delayed till early next year.

Happy Holidays!

**Comment by Xyncgas** [comment]
Merry Christmas

**Comment by 3DSX** [comment]
rest!

**Comment by MariovanZeist** [comment]
Happy New Year Team.
