### ISSUE TITLE
Support for subdomains in a session for different domains

### ISSUE THREAD

**Issue by hyperion-cs** [dotnet/aspnetcore#38712]
### Is your feature request related to a problem? Please describe.
The session is now configured through [AddSession](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.sessionservicecollectionextensions.addsession) in `ConfigureServices`. In one of the overloads of this method, we can specify one Domain to associate with Cookies. For example (including subdomains):
```cs
services.AddSession(options =>
{
    options.Cookie.Domain = ".site.com";
});
```

However, if one backend has to serve several domains at once (and their subdomains too), this cannot be resolved within a single running instance of the application. Imagine that there are several sites (`site1.com`, `site2.com`) that are not essentially different, but there is some variation depending on the HTTP header `Host` (i.e. domain name).
Now we have to run several backend instances with different values for `Cookie.Domain`. This is inconvenient and creates additional resource overhead.
Note that I'm **not talking** about sharing session between different domains (only subdomains). I'm talking about supporting several different domains at once (so that each has its own session).

### Describe the solution you'd like
I propose to implement functionality where `Cookie.Domain` is binded to a `Host` HTTP header, with support for subdomains.
This should not be a problem even when using a third-level or higher domain name.
Another way is to allow AddSession to be used multiple times in the same application instance and to statically specify domain names. Something like:
```cs
services.AddSession(options =>
{
    options.Cookie.Domain = ".site1.com";
});

services.AddSession(options =>
{
    options.Cookie.Domain = ".site2.com";
});
```
However, it looks like we still have to compare the Host header.

**Comment by Tratcher** [comment]
You should be able to do this by replacing SessionOptions.Cookie with a derived CookieBuilder that overrides Build and customizes the Domain based on the Host.
https://github.com/dotnet/aspnetcore/blob/5adbdcb18ce1167321e919b930d575cbbfb7512c/src/Middleware/Session/src/SessionOptions.cs#L28-L32
https://github.com/dotnet/aspnetcore/blob/5adbdcb18ce1167321e919b930d575cbbfb7512c/src/Http/Http.Abstractions/src/CookieBuilder.cs#L94-L107
Make sure to set the other fields as needed:
https://github.com/dotnet/aspnetcore/blob/5adbdcb18ce1167321e919b930d575cbbfb7512c/src/Middleware/Session/src/SessionOptions.cs#L50-L56

**Comment by hyperion-cs** [comment]
@Tratcher, thank you very much! That solved my problem.
