### ISSUE TITLE
Configuring multiple authentication schemes using Microsoft Identity Web

### ISSUE THREAD

**Issue by chintanr97** [dotnet/aspnetcore#38714]
### Describe the bug
We are trying out to setup multiple Azure AD authentication schemes with our project. The `AddAuthentication` and `AddAuthorization` calls are configured as follows:

```
 services.AddAuthentication("AzureAd1")
    .AddJwtBearer("AzureAd1", options =>
    {
        options.Authority = "https://login.microsoftonline.com/tenantId1";
        options.Audience = "clientId1";
    })
    .AddMicrosoftIdentityWebApi(configuration, "AzureAd2", "AzureAd2");

...

services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .AddAuthenticationSchemes("AzureAd1", "AzureAd2")
        .Build();
});

...

services.AddMvc(options =>
{
    options.Filters.Add(new AuthorizeFilter());
});
```

In the `Startup.cs` for the project we are configuring the app as follows:
```
...
app.UseHttpsRedirection();
app.UseRouting();
app.UseAuthentication();
app.UseMiddleware<TestMiddleware>();
app.UseAuthorization();
...
```

On the controller we have the following attribute set: `[Authorize]`. Now, when a request is received for the token corresponding to `AzureAd1` scheme, the authentication works correctly. However, when we send a request with token issued with respect to `AzureAd2` scheme, then the authentication fails. 

We try to debug the code by traversing the ASP .NET Core code base.

1. The call from `Microsoft.Identity.Web` for adding the authentication scheme using the method: `AddMicrosoftIdentityWebApi` can be found [here](https://github.com/AzureAD/microsoft-identity-web/blob/1.16.1/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs#L158). Implicitly, it calls the add JWT bearer method to add the scheme for protecting the Web API.
2. The `AddJwtBearer` call adds the scheme to the authentication builder as visible [here](https://github.com/dotnet/aspnetcore/blob/v5.0.12/src/Security/Authentication/JwtBearer/src/JwtBearerExtensions.cs#L67). 
3. Now the `AddScheme` implementation expects that the handler type for the scheme is assignable to `IAuthenticationRequestHandler` as available [here](https://github.com/dotnet/aspnetcore/blob/v5.0.12/src/Http/Authentication.Core/src/AuthenticationSchemeProvider.cs#L149). However, if one attempts to achieve that with `JwtBearerHandler` then it fails. Therefore, the property `_requestHandlersCopy` remains empty always.
4. Now, with the help of `UseAuthentication` functionality used for configuring the app, the `AuthenticationMiddleware` is invoked. In the authentication middleware it uses the `Schemes` property to fetch the schemes using: `GetRequestHandlerSchemesAsync` (as suggested [here](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L58)). However, the method `GetRequestHandlerSchemesAsync` in the `AuthenticationSchemeProvider` simply returns the value for `_requestHandlersCopy` (as shown [here](https://github.com/dotnet/aspnetcore/blob/v5.0.12/src/Http/Authentication.Core/src/AuthenticationSchemeProvider.cs#L129)). Now because the `_requestHandlersCopy` is empty array, the `AuthenticationMiddleware` receives the same and does not iterate over any of the added schemes. Because of this reason, it will continue to get the default scheme and try to parse using the `AzureAd1` scheme (based on our example above) - which leads to failure for an access token issued for `AzureAd2` scheme.
5. Given the identity as not authenticated simply by using the `UseAuthentication` call, it results into an issue where, let us say if we have a custom middleware immediately after the authentication middleware, here invoked by: `UseMiddleware<TestMiddleware>()` - then in this middleware, the Invoke function's (`Invoke(HttpContext httpContext)`) HTTP context `httpContext` does not populate the `User.Identity` correctly and `httpContext.User.IsAuthenticated` remains `false`.

Now, looking at the implementation I wanted to identify if this is truly achievable using the ASP .NET core authentication middleware or if I missing some configuration change that is leading to this behaviour.

### To Reproduce

We can reproduce the error using the sample published by the Microsoft Identity Web library as available [here](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/MultipleAuthSchemes). We can extend the project to include the custom middleware as follows:

<details>
    <summary>TestMiddleware.cs</summary>

```
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace mvcwebapp_graph.Middlewares
{
    public class TestMiddleware
    {
        private readonly RequestDelegate next;
        
        public TestMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            var userIdentity = httpContext.User.Identity;
            if (userIdentity?.IsAuthenticated == true && userIdentity is ClaimsIdentity @identity)
            {
                // do something.
            }

            await this.next(httpContext);
        }
    }
}
```
</details>

### Further technical details
- ASP.NET Core version: 5.0.12
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS Enterprise 2019 (Version 16.11.5)
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3
```

</details>

**Comment by blowdart** [comment]
This would be better asked in the identityweb repo - https://github.com/AzureAD/microsoft-identity-web

As they're a different org I can't move the issue I'm afraid.

**Comment by chintanr97** [comment]
Hi @blowdart ,

Thanks a lot for the pointer. I will definitely raise the query there. Along side that, I wanted to ensure that the issue does not correlate with the way in which the ASP .NET core is populating the `_requestHandlersCopy` property in the `AuthenticationSchemeProvider`. To be specific, I wanted to understand, why the JWT bearer handler is not being assignable to the `IAuthenticationRequestHandler`. 

When I dived into the code, I saw that only `RemoteAuthenticationHandler` and `NegotiateHandler` implement the `IAuthenticationRequestHandler`. If this is true, does it imply that only these handlers can be called apart from default handler configured using `AddAuthentication`.

Please let me know if I am missing something here.

**Comment by chintanr97** [comment]
Hi @HaoK / @blowdart ,

I wanted to follow up for any updates on this. Looks like the query (linked just above this comment) in the Microsoft Identity Web also suggested me to identify the answer using ASP .NET core functionality. Please let me know if I am missing something here.

Regards,
Chintan Rajvir

**Comment by HaoK** [comment]
JwtBearer is indeed not a remote authentication handler, its just looking at the bearer header to do auth, that type of handler is for flows that require going to another remote destination to complete the flow like OAuth, OpenID, etc.  

The only scheme that gets automatically authenticated by the AuthenticationMiddleware is the DefaultScheme.  Otherwise you can also specify which scheme you want authenticated via the https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.iauthorizedata.authenticationschemes?view=aspnetcore-6.0#Microsoft_AspNetCore_Authorization_IAuthorizeData_AuthenticationSchemes property

**Comment by chintanr97** [comment]
Hi @HaoK ,

Thanks a lot for your response. In that case, what happens in case the user is planning to take some decision based on the authentication schemes configured immediately after `UseAuthentication` call (here, through the `TestMiddleware`)? 

Ideally, if the developer has setup multiple authentication schemes on the service collection, then the primary use case for them would be to try all schemes directly when `UseAuthentication` is called. Setting `AuthenticationSchemes` during the `AddAuthorization` call will trigger validation of the identity while processing the `UseAuthorization` (or at least that is what I observed - so correct me if I am wrong). 

What I am unable to understand is the use case of tying multiple authentication schemes to be used with `AddAuthorization` call and not being supported with `AddAuthentication` calls in first place. There may be several scenarios where multiple authentication schemes are needed but they may not require to set authorization policies - just for it.

Please let me know if I am missing something here.

Regards,
Chintan Rajvir

**Comment by HaoK** [comment]
I'm not sure what exactly you are asking, the schemes are all configured, its only that some schemes need additional ability to participate in request processing to handle auth flows, JwtBearer is not one of those since it works against a header.  

> Ideally, if the developer has setup multiple authentication schemes on the service collection, then the primary use case for them would be to try all schemes directly when UseAuthentication is called. 

This is not the design today, only the default scheme is automatically used, otherwise the schemes need to be explicitly specified to have any effect.  Developers are certainly free to directly call the auth services with the schemes they want to try, but the framework doesn't enumerate them all by default (except for the ones that get an opportunity to handle requests)

**Comment by chintanr97** [comment]
Hi @HaoK ,

Let me bit expand on what I wish to achieve, and may be then you can share if that is really feasible or if I am missing something in the implementation.

1. Let us I added 2 authentication schemes during the services initialization as follows: 
```csharp
services.AddAuthentication("AzureAd1")
    .AddMicrosoftIdentityWebApi(configuration, "AzureAd1", "AzureAd1");

services.AddMicrosoftIdentityWebApiAuthentication(configuration, "AzureAd2", "AzureAd2");
```
2. Now, what I am hoping for is, whenever a request is received, and authentication is triggered, I want the `HttpContext.User.Identity` in the `TestMiddleware` to be assigned with the parsed token claims by validating the tokens against any of the 2 schemes: "AzureAd1" or "AzureAd2". 
3. I think what you are suggesting is for me to use `[Authorize(AuthenticationSchemes = "AzureAd1,AzureAd2")]` over the controller to which the request is coming. That works perfectly fine - but it only gives me valid identity claims inside the controller. 
4. For the example in point 1 just above, if the token is issued for `AzureAd2` configuration, then the `HttpContext.User.Identity` (inside `TestMiddleware`) is not populated with the expected claims and `ClaimsIdentity.IsAuthenticated` is also `false`.

I want to identify following: Is the above scenario achievable?
1. If yes, is there a configuration error I am making or is the `Microsoft.Identity.Web` having some issue implicitly?
2. If not, I would like to learn about the reason for the same.

Regards,
Chintan Rajvir

**Comment by HaoK** [comment]
You can try creating a policy scheme: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/policyschemes?view=aspnetcore-6.0 that logically will combine the two schemes to accomplish what you want, so you'd then just use this "BothAzureAd" scheme everywhere you want to do this.

**Comment by chintanr97** [comment]
Hi @HaoK ,

Right, so following other examples, we had resolved this issue on our end by writing a custom authentication handler (an extension of `AuthenticationHandler<TOptions>`) where `TOptions` is using derived class over the authentication scheme options (`AuthenticationSchemeOptions`). The custom authentication handler would iterate over the authentication schemes (in our case 2 Azure AD API authentication schemes) and try to authenticate the identity.

However, we wanted to primarily figure out if we are missing something on the configuration part, or the reason for this not being supported in .NET core authentication logic out-of-the-box. I mean, if I simply do this:
```csharp
// OPTION 1:
services.AddAuthentication("AzureAd1")
    .AddJwtBearer("AzureAd1", options =>
    {
        options.Authority = "https://login.microsoftonline.com/tenantId1";
        options.Audience = "clientId1";
    })
    .AddMicrosoftIdentityWebApi(configuration, "AzureAd2", "AzureAd2");

// OR OPTION 2:
services.AddAuthentication("AzureAd1")
    .AddMicrosoftIdentityWebApi(configuration, "AzureAd1", "AzureAd1");

services.AddMicrosoftIdentityWebApiAuthentication(configuration, "AzureAd2", "AzureAd2");

// NOTE: I cannot call `AddMicrosoftIdentityWebApiAuthentication` or `AddMicrosoftIdentityWebApi` in a nested way. Is that the limitation?
```

Why this is unable to iterate over both the configured schemes during the authentication phase itself and give me an authenticated identity in the `HttpContext.User`? It would save the effort of configuring custom authentication handler or the authentication option classes.
