### ISSUE TITLE
Publish updated version of Microsoft.AspNetCore.Components.CustomElements built against .NET 6

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#38724]
The published version of Microsoft.AspNetCore.Components.CustomElements has .NET 6 RC1 dependencies. 

https://github.com/aspnet/AspLabs/blob/main/src/BlazorCustomElements/src/Microsoft.AspNetCore.Components.CustomElements/Microsoft.AspNetCore.Components.CustomElements.csproj#L13

We should publish an updated version built against .NET 6 GA packages.

**Comment by Bouke** [comment]
Why is this added to the 7.0 milestone? What's keeping from publishing a release that's build against the current public release of 6.0(.2)?

**Comment by danroth27** [comment]
> Why is this added to the 7.0 milestone? What's keeping from publishing a release that's build against the current public release of 6.0(.2)?

Hi @Bouke. We don't plan to ship a stable version of this package until .NET 7 releases later this year. We unfortunately don't plan to release a stable version of this package based on .NET 6. Right now the team is completely focused on delivering Blazor support for .NET MAUI. Note that the underlying mechanism in Blazor used by this package to enable support for custom elements is part of .NET 6, so you can enable support for custom elements yourself.

**Comment by mkArtakMSFT** [comment]
An updated package has been published: https://www.nuget.org/packages/Microsoft.AspNetCore.Components.CustomElements/0.1.0-alpha.22320.2
