### ISSUE TITLE
StaticWebAssets.xml not found when using SDK 6.0.100 and targeting NET5

### ISSUE THREAD

**Issue by jsheetzati** [dotnet/aspnetcore#38726]
Hello,

We recently upgraded our build servers to use SDK 6.0.100. When running `dotnet test` / `dotnet publish`, we get an error message indicating that StaticWebAssets.xml was not found. The issue happens when we are targeting a NET5 project with the NET6 SDK.

```
F:\BuildAgents\vsts-agent-4-1\_work\_tool\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(5100,5): error MSB3030: Could not copy the file "F:\BuildAgents\vsts-agent-4-1\_work\4\s\DotNetCore\Source\WebApi\obj\release\net5.0\staticwebassets\WebApi.StaticWebAssets.xml" because it was not found. [F:\BuildAgents\vsts-agent-4-1\_work\4\s\DotNetCore\Source\WebApi.Test\WebApi.Test.csproj]
```

This error seems very similar to other issues, but we are still running into the problem with SDK Version 6.0.100.
https://github.com/dotnet/sdk/issues/21056
https://github.com/dotnet/sdk/issues/20008
https://github.com/dotnet/sdk/issues/19665
https://github.com/dotnet/aspnetcore/issues/35345

**Comment by jsheetzati** [comment]
With this being moved to the NET7 milestone, what is the workaround in the mean time for this issue? I thought the SDK is backwards compatible with older runtimes. This is blocking us from upgrading our build servers to use SDK6.

**Comment by madelson** [comment]
This is happening to me as well using VS2022.

**Comment by javiercn** [comment]
@jsheetzati is this still happening to you?

If so, please provide a minimal repro project with steps on how to reproduce this issue.

We believe this was likely caused by building the project from a dirty state with a new SDK. Doing a one time clean of the bin and obj folders should likely solve the problem after you've upgraded to a 6.0 SDK

**Comment by madelson** [comment]
> We believe this was likely caused by building the project from a dirty state with a new SDK. Doing a one time clean of the bin and obj folders should likely solve the problem after you've upgraded to a 6.0 SDK

@javiercn isn't this still a bug that should be fixed? I feel like you shouldn't have to do a clean in order to change things like Configuration, TargetFramework, etc. but in my experience VS often struggles with that.
