### ISSUE TITLE
Disable forceful re-render after a button click in Blazor

### ISSUE THREAD

**Issue by arsinclair** [dotnet/aspnetcore#38728]
At some point I noticed that when I click on a `<button>` in my component that has an event handler attached, it causes the re-render of my component, wiping its internal state. After some googling I found that this is an intended behaviour, and to opt out we need to implement an `IHandleEvent` in the component. 
I found and precisely followed [these docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-5.0&pivots=server#avoid-rerendering-after-handling-events-without-state-changes-1) that describe how to do it, however whatever I do, my button still refreshes the state of a component. I've spent a couple of days trying to troubleshoot this, but I believe I'm missing something very simple, so I though I'd ask for help.

Below is the code of my component:
```razor
@implements IHandleEvent

<div class="form-group">
    <input type="text" class="form-control" value="@Output">
    <button @onclick="Clear" class="btn btn-sm btn-outline-dark">Clear</button>
</div>

@code {
    private async Task Clear()
    {
        var a = 2 + 2;
    }

    private object output;
    [Parameter]
    public object Output
    {
        get => output;
        set
        {
            if (output?.ToString() == value.ToString()) return;
            output = value.ToString();
        }
    }

    Task IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, object arg) => callback.InvokeAsync(arg);
}
```

The value for the input comes from the parent component.

---

The test I do is very simple:
- I modify the internal state of the input component, add some characters inside
- then I click the button to execute `2+2`
- immediately after that my component is refreshed and the characters from step 1 disappear, leaving me with its initial state that comes from the parent

![Animation](https://user-images.githubusercontent.com/2878904/144108012-bcfd2d72-1524-4073-8c2d-4cae2481e215.gif)

I don't think the docs are incorrect, as someone would have reported it by now, so what am I doing wrong?

**Comment by willdean** [comment]
I think your fundamental problem is that re-rendering the component is changing its state, not that the re-rendering happens.

**Comment by arsinclair** [comment]
> re-rendering the component is changing its state, not that the re-rendering happens.

I don't see how the component can be changing state, as `Clear` function is just sums 2 + 2 and assigns it to a variable. Or maybe I misunderstood your point? Could you elaborate better, please. Also, what kind of test can I do to test your theory?

**Comment by pranavkm** [comment]
Is the browser submitting the document when you press Clear? I can see it spinning.

**Comment by arsinclair** [comment]
> Is the browser submitting the document when you press Clear? I can see it spinning.

Yeah, you're right, it looks like the whole page is refreshed.

![image](https://user-images.githubusercontent.com/2878904/144191871-f9bf5cac-197c-4474-a8cb-07ca1df6c4c4.png)

Why would this be happening after a simple button click?

**Comment by arsinclair** [comment]
Okay, I think I was being dumb here: the button is located inside of the `<form>` tag, therefore when clicked, a form submission happens.

The only part I am not sure about is that the button needs to have `type="submit"` to submit the form, however mine doesn't have it, still a form submission happens.

**Comment by arsinclair** [comment]
Thank you for your help, gentlemen, it was really valuable, and I'm sorry for my negligence. This can be closed now.
