### ISSUE TITLE
Quarantine IHttpActivityFeatureIsAssignedToIfItExists

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38736]
## Failing Test(s)

- Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsAssignedToIfItExists

## Error Message

```text
Assert.NotEqual() Failure
Expected: Not Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsAssignedToIfItExists() in /_/src/Hosting/Hosting/test/HostingApplicationTests.cs:line 163
```
</details>

## Logs

<details>

[console.08f3e2b4.txt](https://github.com/dotnet/aspnetcore/files/7629580/console.08f3e2b4.txt)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1490937&view=ms.vss-test-web.build-test-results-tab&runId=42613500&resultId=111867&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Tratcher** [comment]
Related: #35142

**Comment by JamesNK** [comment]
Test removed
