### ISSUE TITLE
.NET 6 - Cascading Value & StateHasChanged

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#38734]
Hello,

Here is the code to illustrate the problem/issue.
When the button is clicked, all the razor components are rendered.
In the console, the value ```There is a Title``` is present and displayed for all the ```OnAfterRender``` component methods.
But the value ```There is a Title``` is not rendered. The display is always ```There is no Title``` on the screen.
A second click displays the correct value which is ```There is a Title```.
Why does this happen?
The Title parameter of the CCTitle child is changed.
The CCTitle parent is rendered.
But the value ```There is a Title``` is not rendered on the screen.
Is it possible to solve it ? Is it required to use the ```StateHasChanged``` method after the first click? 
Is there somewhere in the official documentation an explanation? Is it by design?
Thanks for any answer.

```C#
Index.razor
<button @onclick="Do">Do</button>
<CCTitle>
    <CTitles>
        <CTitle Title="@title"></CTitle>
    </CTitles>
</CCTitle>

@code {
    private string? title = "There is no title";

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine($"Index {title}");
        Console.WriteLine("Index OnAfterRender");
    }

    private void Do()
    {
        title = "There is a title";
    }
}
```

```C#
CCTitle.razor
<CascadingValue Value="this" Name="CCTitle">@CTitles</CascadingValue>
<text>@_cTitle?.Title</text>

@code {
    private CTitle? _cTitle;
    [Parameter] public RenderFragment? CTitles { get; set; }

    public void Add(CTitle cTitle)
    {
        _cTitle = cTitle;
    }

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine($"CCTitle {_cTitle?.Title}");
        Console.WriteLine("CCTitle OnAfterRender");
    }
}
```
```C#
CTitle.razor
@code {
    [CascadingParameter(Name = "CCTitle")] private CCTitle? CCTitle { get; set; }
    [Parameter] public string? Title { get; set; } 

    protected override void OnInitialized()
    {
        CCTitle?.Add(this);
    }

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine($"CTitle {Title}");
        Console.WriteLine("CTitle OnAfterRender");
    }
}
```
![image](https://user-images.githubusercontent.com/16502423/144132115-2f46030e-0a82-46bf-8b65-3cf6547eb079.png)

**Comment by MariovanZeist** [comment]
The problem happens because you are updating a parent component ```CCTitle``` from a child component ```CTitle``` ,
without a way for Blazor to know if it should Rerender the ```CCTitle``` component because something has changed. 
You are updating a property of an internal object (```private CTitle? _cTitle```), and Blazor can't detect such changes.

So in this case the value displayed always lags behind 1 click. (The initial condition is that no text is displayed)

There needs to be a way for the Parent Component to know that something has changed.

You could fix it for example to see if your title property changes in the ```CTitle```  component to then call a function on the parent ```CCTitle``` component to trigger an update

So add the following to the ```CCTitle``` component
```CS
 internal void UpdateTitle()
 {
     StateHasChanged();
 }
  ``` 
  
And add this to the ```CTitle``` component
 ```CS
 public override async Task SetParametersAsync(ParameterView parameters)
 {
     var oldTitle = Title;
     await base.SetParametersAsync(parameters);
     if  (oldTitle != Title)
     {
         CCTitle?.UpdateTitle();
     }
 }
 ```

**Comment by boukenka** [comment]
@MariovanZeist Thank you for the explanation and the proposed solution.

**Comment by boukenka** [comment]
@MariovanZeist Hello again. What do you think about this more generic solution (based from your original proposition) ?

```C#
CTitle.razor
@code {
    private IReadOnlyDictionary<string, object> _parameters = new Dictionary<string, object>();
    [CascadingParameter(Name = "CCTitle")] private CCTitle? CCTitle { get; set; }
    [Parameter] public string? Title { get; set; }

    protected override void OnInitialized()
    {
        CCTitle?.Add(this);
    }

    public override async Task SetParametersAsync(ParameterView parameters)
    {
        var _shouldRender = false;
        await base.SetParametersAsync(parameters);

        if (_parameters.Count > 0)
        {
            foreach (var parameter in parameters)
            {
                if (parameter.Value != _parameters[parameter.Name])
                {
                    _shouldRender = true;
                }
            }
        }
        else
        {
            _shouldRender = true;
        }

        _parameters = parameters.ToDictionary();
        if (_shouldRender)
        {
            CCTitle?.UpdateTitle();
        }
    }
}
```
