### ISSUE TITLE
[Feature Request] Replace all browsers on windows with only one browser that can run compiled websites.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38745]
This is the state of modern applications btw, everything is running on top of something, blocked by the delay of implementations of features in the underlying platform, when the good old days you just give people your app, and it runs as long they have a cpu that the program was compiled for.

I am hoping, since people are running windows, let's have a single browser that's in the operating system, there will be no chromes on windows, unless they interface it with the OS's browser, then we can do crazy things like run any code in any language targetting this browser, which runs on .NET, which then expose pretty UI letting people maybe design it using html & css, but also allowing c# to manipulate UI like xamarin, it's going to be a major platform that evolves along with .NET, providing many benifit and the freedom to make features available, without worrying about what browsers your users have. if they run windows they can visit your website.

this technology can be duo-cored, one that still use chromium for legacy websites and one for new-compiled-websites, and when you put the word legacy out there websites that pretend this isn't a thing will die out fast.

Old websites can continue to work.

But dev can now believe there is a docker / .NET stack in everyone's pc who's running windows that can vist their application via url, they can write their website using asp.net core, compile it to IL which is way better than handing out javascript, then the browser downloads the website and JIT-compile when users visits the URL. ASP.net applications can alternatively download the IL along with mono.net to compile it like blazor is doing but it will be slower since OS' browser already has the .NET there, so blazor wasm can now be renamed to aspnet.Neutrinum project or some other names which'll be able to output in legacy mode to support old browser venders or use the new ecosystem & features to output compiled codes that can be rendered into website once the user visits the url, which from there you can also access native system resource like disks, people are going to be writing websites in c# that supports multi-threading because it's running on .NET, they can easily take the UI off their project and now it's a command line program that can run on the server, you can do local caching and prompt for install, just like the actual applications.

Looking back the way web has evolved, webassembly.. unified UI.. unified everything.. multi-threading scenario in the browser.. PWA.. electron.. Take a hint already, people need only one browser that's more than what a browser is today, throw away everything, keep the sandbox, then give everything that's already there. Make javascript go away, make it optional for people to use html / css, I am sure a lot people will be happy. Make it work, give me threads, give me access to the pc's hard-drive through permissions and maybe sub-directory on a local particition besides C: that's specially created for the browser to use that can grow its size dynamically so it doesn't take up user's disk space from the beginning but gradually as the user downloads more applications and as those applications put stuffs in the local storage, re-define the web because we all need the web so we gotta be serious about the things we use everyday.

**Comment by Xyncgas** [comment]
also a lot people don't like apple, they don't like google, we can make them our bitch. and the things we are going to do, is going to be benifiting a lot of people, with apple having its walled garden not allowing anyone to use the web-browsers they want besides what IOS allows you to use we are in a good spot to suit apple for doing it first, then if that case failed we can go ahead and abandon all these legacy big tech companies and make our own microsft owned new web, only this way you are getting the developer communities involved that's already been pushing .NET forward, it's no longer the ugly browser battle decades ago.

**Comment by pranavkm** [comment]
Thanks for filing this issue, but this isn't the right forum to express it. Closing this as there does not appear to be any actionable work for us to here.
