### ISSUE TITLE
When behind TLS-terminating reverse proxy, static file middleware redirects from HTTPS to HTTP to append trailing slash

### ISSUE THREAD

**Issue by cmeeren** [dotnet/aspnetcore#38744]
By default, the static files middleware redirects using 301 in order to append trailing slashes. This in itself is fine with me. However, my web app is behind a reverse proxy that does TSL termination and uses HTTP internally. It seems that when ASP.NET Core performs this redirect, it uses HTTP (as the web app is internally called with), not HTTPS (as the client originally requested). The `Location` header in the redirect response contains the correct URL, except it uses HTTP instead of HTTPS. **This makes some clients, e.g. `HttpClient`, not follow the redirect automatically.**

I am not sure what the best course of action would be.

(No repro solution since this largely depends on the environment, not the code.)

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0 for generating correct redirects with x-forwarder headers.

**Comment by cmeeren** [comment]
I'm fairly sure I'm already forwarding headers as described there, but I'll test and verify tomorrow morning.

**Comment by cmeeren** [comment]
I found out that there was an additional reverse proxy in our network infrastructure that was not in fact forwarding the `X-Forwarded-Proto` header. It now forwards this header, and my issue is resolved.
