### ISSUE TITLE
Custom Claim is null after successfully login with in max15 minutes

### ISSUE THREAD

**Issue by akbarbd** [dotnet/aspnetcore#38749]
### My Startup Code 
      services.AddIdentity<AspUser, AspRole>(
                options => options.SignIn.RequireConfirmedEmail = false)
                .AddEntityFrameworkStores<MyIdentityDbContext>()
                .AddDefaultTokenProviders();

        services.Configure<IdentityOptions>(options =>
            {
                // Password settings.
                options.Password.RequireDigit = false;  
                // Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5); 
             });

       services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                
                options.Cookie.Name = "MyCookie";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromDays(2);
                options.LoginPath = "/LoginPage URL";
                options.AccessDeniedPath = "AccessDenied URL";
                options.SlidingExpiration = true;
            });

             services.AddAuthentication(defaultScheme: CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.Cookie.Name = "MyCookie";
                    options.Cookie.HttpOnly = true;
                    options.ExpireTimeSpan= TimeSpan.FromDays(2);
                    options.LoginPath = "/LoginPage URL;
                    options.LogoutPath = "/LogOut URL";
                    options.AccessDeniedPath = "/AccessDenied URL";
                    options.Cookie.SameSite = SameSiteMode.Lax;
                    options.SlidingExpiration = true;
                });

     **app configuration section**
    var cookiePolicyOptions = new CookiePolicyOptions
            {
                MinimumSameSitePolicy = SameSiteMode.Strict,
                HttpOnly = Microsoft.AspNetCore.CookiePolicy.HttpOnlyPolicy.Always,
                Secure = CookieSecurePolicy.None,
                
            };
            app.UseCookiePolicy(cookiePolicyOptions);
            app.UseAuthentication();
            app.UseAuthorization();

###  Login Controller Function
             var dbUserInfo = await _userManager.FindByNameAsync(model.UserName);
             var result = await _userManager.CheckPasswordAsync(dbUserInfo, model.Password);
              if (result)
                {
                   //SessionKey  My Constans Value
                       List<Claim> _claim = new() {
                            new Claim(ClaimTypes.NameIdentifier, dbUserInfo.Id.ToString()),
                            new Claim(ClaimTypes.Name, dbUserInfo.UserName),
                            new Claim(ClaimTypes.Email, userdata.Email ?? ""),
                            new Claim(SessionKey.COMPANY_ID, userdata.CompanyID.ToString()),
                            new Claim(SessionKey.COMPANY_NAME, userdata.CompanyName ?? ""),
                            new Claim(SessionKey.EMPLOYEE_ID, userdata.EmployeeID.ToString()),
                            new Claim(SessionKey.User_EMPLOYEE_Code, userdata.EmployeeCode ?? ""),
                            new Claim(SessionKey.IsSuperAdmin, userdata.IsSuperAdminRole.ToString()),
                          }
                    var authenticationProperties = new AuthenticationProperties { 
                                                                           IsPersistent = model.RememberMe,
                                                                           ExpiresUtc = DateTime.Now.AddDays(2) 
                                                                    };
                      await _signInManager.SignInWithClaimsAsync(dbUserInfo, authenticationProperties, _claim);
                         
                        return LocalRedirect(returnUrl);
               }else
                  {
                    return View();
                   } 
### _Now What Happen_
       Valid user successfully login. After login  I found all claim (User Db Claim and custom claim).
         But with in 15 minutes Custom claim (SessionKey.COMPANY_ID,  SessionKey.EMPLOYEE_ID, SessionKey.IsSuperAdmin, 
       SessionKey.User_EMPLOYEE_Code) is null.

  I am stack here,  Please give me a solution.

**Comment by blowdart** [comment]
Every 15 minutes identity refreshes the identity stored in the cookie to ensure [any changes in the backend are reflected in the next request](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-6.0#react-to-back-end-changes), so that's why things are getting lost.

Rather than put your claim code inside login you need to look at the [UserClaimsPrincipalFactory](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio#add-claims-to-identity-using-iuserclaimsprincipalfactoryapplicationuser) and move your code to there, that will persist over the refreshes

**Comment by akbarbd** [comment]
I got this point.
Thanks
