### ISSUE TITLE
Process Handler Load Failure

### ISSUE THREAD

**Issue by bhavikpatel994** [dotnet/aspnetcore#38746]
HTTP Error 500.0 - ANCM In-Process Handler Load Failure

This is the issue which is occurred when I try try run my .NET core solution. Please give me some suggestions.

**Comment by pranavkm** [comment]
Have you tried the troubleshooting guide at https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis#app-startup-errors as yet?

**Comment by bhavikpatel994** [comment]
> Have you tried the troubleshooting guide at https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis#app-startup-errors as yet?

I have tried but I didn't find solution

**Comment by adityamandaleeka** [comment]
Triage: unfortunately there's not much we can do with just the info provided. Any chance you could provide more logs and/or a minimal repro?

**Comment by bhavikpatel994** [comment]
I can provide the whole error
when I start my .Net core application the browser shows me this error
I have tried to compare my backup project and current project and there no difference between, but still I got this error. even though backup project runs perfectly.
"HTTP Error 500.0 - ANCM In-Process Handler Load Failure"

what to do now?

**Comment by adityamandaleeka** [comment]
@bhavikpatel994 As I said above, we can't really help you unless we have more info.

Can you share your web.config (or even the whole project)?
What version of .NET are you using?
What architecture are you building for?
