### ISSUE TITLE
Loading appsettings.json many json "data" entries is very slow in Blazor WASM

### ISSUE THREAD

**Issue by markusrt** [dotnet/aspnetcore#38770]
### Describe the bug

When adding an `appsettings.json` to a dotnet  core wasm project with 600 lines of "data", then loading this via `IOptions` is very slow. The performance depends on the size of the JSON. I.e. smaller configs are faster. Maybe the issue is related to deserialization.

@javiercn Recreated this issue after #38555 got closed. Somehow I made a mistake when porting my repro project to dotnet 6. I actually forgot the appsettings.json 🤦‍♂️... Unfortunately after re-adding it, the issue came back.

#### What I did

- `dotnet new blazorwasm`
- Stripped out anything but counter
- Added a new service which makes use of `IOptions` to access configuration data
- Register dependency to service and options in `Program.cs`
- Inject my service to `Counter.razor`

#### What happens

Upon accessing Counter-page the client spends ~5 seconds in the constructor of `MicStepsService`:

![image](https://user-images.githubusercontent.com/299753/144295494-f54dd1e2-19fa-4c5c-bf16-3578f2ca4610.png)

Delay is caused when accessing the config value:

```cs
 _configValue = config.Value;
```

Removing configuration entries linearly reduces the delay. I also tried to change the code to read data [via embedded resource](https://github.com/markusrt/SlowWasmAppSettings/blob/master/MyCode/MicStepServiceEmbedded.cs#L22-L31). This fixed the issue as well:

![image](https://user-images.githubusercontent.com/299753/144295560-66f25bf5-335b-4a59-9cc8-e0141ecb1fe6.png)

#### Repro project

https://github.com/markusrt/SlowWasmAppSettings

### Exceptions (if any)

no Exceptions

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Microsoft Visual Studio Enterprise 2022
- Browser: Chrome Version 96.0.4664.45 (64-Bit)
- Include the output of `dotnet --info`:
  <details>
    <summary>dotnet --info Output</summary>
    
    ```
     .NET SDK (reflecting any global.json):
     Version:   6.0.100
     Commit:    9e8b04bbff
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.19042
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\6.0.100\
    
    Host (useful for support):
      Version: 6.0.0
      Commit:  4822e3c3aa
    
    .NET SDKs installed:
      3.1.402 [C:\Program Files\dotnet\sdk]
      5.0.403 [C:\Program Files\dotnet\sdk]
      6.0.100 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    
    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download
    ```
  
  </details>

**Comment by TanayParikh** [comment]
I'm going to close this issue out as a dup of https://github.com/dotnet/aspnetcore/issues/38555, and re-open that issue so the thread context is maintained.
