### ISSUE TITLE
blazor webassembly OnInitializedAsync will call many time?

### ISSUE THREAD

**Issue by mcguu** [dotnet/aspnetcore#38777]
in my page there is a `OnInitializedAsync` and in it there is a signalr connection:

```
protected override async Task OnInitializedAsync()
{
    _connection.On<List<MyList>>("GetList",(list)=>
    {
        //code
    }

await _connection.SendAsync("GetList");
}
```

If I first open the page it will be called once of the code.

if I then open another page then open this page the code will be called twice

then will called 3 again more and more times

I do not know if it is the signalr 's issue or blazor's.

**Comment by pranavkm** [comment]
@mcguu there isn't enough details in the issue for us to determine what the issue is. Could you include a minimal app (preferably as a GitHub repo) that demonstrates what the issue is? Thanks!
