### ISSUE TITLE
Blazor Server side components inside an Iframe does not connect through Websockets

### ISSUE THREAD

**Issue by germansak** [dotnet/aspnetcore#38781]
Hi, the company I'm working has a webapp hosted in Azure that has an MVC app (hosted somewhere else) inserted as an Iframe on the parent app. This second MVC app is hosted on a Linux Server with Nginx.

For faster development workflow I proposed using Blazor Server side for developing components on the second app and it was working really well, but when we deploy the app on the linux server it wouldn't connect through websockets but instead, it's making a lot of XMLHttpRequest

![image](https://user-images.githubusercontent.com/702172/144411818-ff548ee5-4f4c-4ae9-aaf6-145af63c7a53.png)

this leads to several timeouts per minute and the message "... could not connect to the server..." for a second until connection is restored, but obviously, it's quite annoying for the client.

The error I'm getting on the client side (browser) is this

![image](https://user-images.githubusercontent.com/702172/144412882-e67096c1-91e7-4729-8855-06ff69903a37.png)

I have enabled websockets on both servers (azure and linux) and still no luck

I'm not sure even where to start to troubleshoot this issue. I would be grateful if you could tell me at least a starting point to solve this problem.

I don't know what other information to provide, but feel free to ask me anything and I will gladly give all information you need

Thanks a lot

**Comment by BrennanConroy** [comment]
You need to figure out who isn't allowing the websocket connection. Can you enable logging on the server to see if the websocket request reaches the server, and if it errors.
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging

**Comment by germansak** [comment]
Hi, first of all thanks for your quick response. After trying several things from all over the web on both Azure site and Linux server,  I finally made it work. It was the Nginx configuration (to which I didn't have access). This is the .conf file on /etc/nginx/sites-available and all the things I've tried

```
# Added to enable websockets
map $http_upgrade $connection_upgrade {
        default Upgrade;
        ''      close;
    }

server {
    listen 80;
        resolver 8.8.8.8;
        location ~*(/appname)/([a-zA-Z0-9]*)/*(.*)$ {
          return 200 "redirect x To  http://appname2.azurewebsites.net/$3";
        proxy_pass http://appname2.azurewebsites.net/$3$is_args$args;
        //

        # needed for websockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # added 1 - didn't work
        real_ip_header X-Real-IP;

        # added 2 - didn't work
        proxy_cache_bypass $http_upgrade;
        
        # added 3 (I thought it was a querystring size issue)- didn't work
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;

        # added 4 - didn't work (but apparently is needed)
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        
        # added 5 - WORKED!
        proxy_http_version 1.1;
        proxy_set_header   Connection keep-alive;
    }
```
Now I need to start removing all the configurations that didn't work and see if some of them breaks again the websocket connection.
So, apparently my issue is resolved. Thanks again and I hope this helps someone else

**Comment by BrennanConroy** [comment]
Also for reference, we have docs on Nginx configuration
https://docs.microsoft.com/aspnet/core/signalr/scale?view=aspnetcore-6.0#linux-with-nginx
