### ISSUE TITLE
Hot Reload: allow *always* restart for rude edits

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#38798]
I'm developing an app using `dotnet watch` with hot reload, and of course I come across this just about every session:

```
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

Hmm... you keep using that word... `Always`.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/9710256/144514157-e9c2a398-7354-431b-a184-a8f3b643b508.png">

But, in all seriousness, may we please have a hook of some sort to configure hot reload to *ALWAYS* reload without asking once every session?  An environment variable would be great.

Thank you all for this feature (hot reload) as it's great when it works. But for me this little issue is a bit of a regression from old-school watch as I didn't have to wonder whether or not `dotnet watch` asked me a question on another screen while I'm in another context.

**Comment by willdean** [comment]
There is another issue somewhere else which I have read but now can't find where someone asks for a command line option to do this, which seems like a good solution (personally I would prefer that to an environment variable).   TBH I think it should be the default anyway.

The UX of this current message is also hopeless, as by the time I realise it's given-up on reloading, the message has long since scrolled off the console - I just have to dab at the 'A' key and hope something happens.

And "rude edit" is a dreadful term, but that's another issue...

**Comment by zbecknell** [comment]
Indeed a command line option would be preferable for me, but given the fragility of hot reload, I figured I'd ask for something that'd be path of last resistance.

And by fragility, I mean that ANY deviation (that I've found) from `dotnet watch` -- with the exception of `dotnet watch -v` for verbose logging -- will cause it to revert to old dumb `dotnet watch run` mode.

It also is highly dependent on the default console logging provider. I have a script I use to set various log levels just for watch mode so I can control it a little better.  We have various custom targets to do things like run CSS on build, notify when the build is complete, etc., and these each break hot reload, so I had to create custom environment variables to disable these for watch only, since there is no other possible way to hook into the process right now.

I just have a `watch.ps1` script I run, so after figuring it all out it's now not bad to start up.  But there's certainly a learning curve and a lot of undocumented behavior to discover for anyone approaching this for the first time.

Here's a simplified version of my script:

```powershell
Write-Host "Executing 'dotnet watch'" -ForegroundColor Magenta

try {
	# These 3 are all custom -- they will be set just for this console session
	$Env:MINIMAL_LOGGING = "1"
	$Env:DISABLE_CSS_ON_BUILD = "1"
	$Env:DISABLE_NOTIFICATION_ON_BUILD = "1"

	# Quiet logging down in the console
	$Env:Logging__Console__LogLevel__Microsoft = "Warning"
	$Env:Logging__Console__LogLevel__Protobuf = "Warning"
	$Env:Logging__Console__LogLevel__Hangfire = "Warning"

	# Browser launching and reload depends on logging from the host to the console...
	${Env:Logging__Console__LogLevel__Microsoft.Hosting.Lifetime} = "Trace"

	dotnet watch -v
}
finally {
	Write-Host "And now the watch is ended" -ForegroundColor Magenta
}
```

**Comment by rose-rey** [comment]
I would really appreciate this feature! I'm running dotnet watch run inside a docker container, and so I can't just press a key to respond to the rude edit prompt. For now I've gone back to the previous full rebuild watch behavior with `--no-hot-reload`

**Comment by rgwood** [comment]
Related issue: https://github.com/dotnet/aspnetcore/issues/37190. This is a blocker for many common workflows.

@pranavkm, what do you think about @zbecknell's [proposed fix](https://github.com/dotnet/sdk/pull/22891)? I'm in favour of it - a `DOTNET_WATCH_ALWAYS_RESTART` environment variable feels like a simple+easy way forward.

**Comment by rgwood** [comment]
Looks like a fix for this has been merged and backported to the upcoming .NET 6.0.2 release: https://github.com/dotnet/sdk/pull/23280/files

The behaviour will be configurable with a`DOTNET_WATCH_RESTART_ON_RUDE_EDIT` environment variable. Thank you @zbecknell and @pranavkm for making this happen!
