### ISSUE TITLE
Blazor Debug `Failed to attach to process: Unknown Error: 0x80131c69`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38790]
### Describe the bug

Getting this issue in GitHub codespaces when I try to attach to a running `BlazorServerApp`.

```
Failed to attach to process: Unknown Error: 0x80131c69
```

This is in the toast notification as well as the `Debug` tab. No other logs present.

**Comment by TanayParikh** [comment]
Note, this was in a loop:

```razor
while (!System.Diagnostics.Debugger.IsAttached)
{
    Console.WriteLine($"Attach at {Environment.ProcessId}");
    System.Threading.Thread.Sleep(1000);
}
```

It works without the loop. But I don't see why that should make a difference?

**Comment by SteveSandersonMS** [comment]
@gregg-miskelly Do you have any idea how we could proceed with diagnosing or resolving this? Seems to be just plain .NET debugging in codespaces (not related to Blazor).

**Comment by TanayParikh** [comment]
> Seems to be just plain .NET debugging in codespaces

The loop mentioned above is used to print the PID to the console & sleep until the debugger is attached. I then attached to the printed PID via the .NET Attach launch config:

https://github.com/dotnet/aspnetcore/blob/bf9225b8d7fd5f8ee855dd50407a90587b812662/.vscode/launch.json#L10-L15

**Comment by gregg-miskelly** [comment]
That is: CORDBG_E_ASSEMBLY_UPDATES_APPLIED

I am guessing you did a hot reload before trying to attach a debugger?

**Comment by TanayParikh** [comment]
Yes I did, thanks for the clarification!

**Comment by gregg-miskelly** [comment]
@TanayParikh What version of the debugger are you using? We already map that error code to a better description.

**Comment by TanayParikh** [comment]
This was on GitHub Codespaces with O# `v1.23.17`.

**Comment by TanayParikh** [comment]
Thanks Gregg, I'll try to repro and will create a new issue on the O#-vscode repo with the details.

**Comment by TanayParikh** [comment]
No repro now 😄 

> Failed to attach to process: Attaching a .NET debugger to this process is not allowed because code changes have been applied. The process must be restarted to allow debugging.
