### ISSUE TITLE
Why does the following middleware works perfectly well in Blazor Server App

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#38795]
but fails to do so in Blazor WebAssembly?

Here' the code:

            app.Use(async (context, next) =>
            {
                 await next.Invoke();
                if (context.User.Identity.IsAuthenticated)
                {
                      var userName = context.User.Identity.Name;

                    using (var dbContext = context.RequestServices.GetRequiredService<ApplicationDbContext>())
                    {
                        var user = dbContext.Users.Where(u => u.UserName == userName).FirstOrDefault();
                        if (user != null)
                        {
                                 user.PhoneNumber = "1234567";
                                 dbContext.Update(user);
                               dbContext.SaveChanges();
                        }
                    }
                }
             });

Thanks...

**Comment by pranavkm** [comment]
Could you elaborate on "but fails to do so in Blazor WebAssembly?"? Did you mean the server in a Blazor WASM Hosted application? A Blazor WebAssembly app does not have a middleware pipeline, so it's a bit difficult to make sense of this question.

**Comment by enetstudio** [comment]
@pranavkm, thanks for your quick response...

I'm adding the middleware in the Startup class of the server project in a Blazor WebAssembly App hosted. It seems to be called, but `context.User.Identity.IsAuthenticated` always returns false, even if the use has been authenticated. Note sure why, as the same middleware works in Blazor Server App...

Thanks again

**Comment by pranavkm** [comment]
Are you able to share a minimal app that exhibits the issue? Particularly given this doesn't sound like a Blazor WASM specific issue,  the sample doesn't have enough details to indicate why this might not be working.

**Comment by HaoK** [comment]
This works as expected as far as I can tell, I created a new blazor wasm app (hosted) and added the 
```
app.Use(async (context, next) =>
{

    await next.Invoke();
    if (context.User.Identity.IsAuthenticated)
    {

        var userName = context.User.Identity.Name;


        using (var dbContext = context.RequestServices.GetRequiredService<ApplicationDbContext>())
        {
            var user = dbContext.Users.Where(u => u.UserName == userName).FirstOrDefault();
            if (user != null)
            {
                user.PhoneNumber = "1234567";
                dbContext.Update(user);
                dbContext.SaveChanges();

            }
        }
    }


});

```

After `app.useAuthorization()` and before `app.MapRazorPages()`

I ran the app, applied the EF migrations, registered a user, then hit the code in the debugger after logging in and logging out and could see that context.User.identity does flip between true and false.

**Comment by enetstudio** [comment]
@HaoK, OK...Got it... Thanks....
