### ISSUE TITLE
Image srcset and size on Blazor WASM are not working on Safari.

### ISSUE THREAD

**Issue by vlasgeorge** [dotnet/aspnetcore#38804]
Responsive image is not showing up on Safari.

### To Reproduce
Debug project on Windows. You will see four images. These images also show up on the browser dev tools when in iPhone - iPad emulation. The images however will not show up when the project is published on Azure and then ran on Safari but they will show up on Android and Windows desktop.
https://github.com/vlasgeorge/Blazor-WASM

### Further technical details
- ASP.NET Core version: 5.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by pranavkm** [comment]
@vlasgeorge does this issue reproduce if you use srcset in a vanilla HTML page? That way we could eliminate the browser as a possible cause for the issue.

**Comment by vlasgeorge** [comment]
@pranavkm no it does not reproduce in a vanilla HTML page.  https://imagekitio.github.io/responsive-images-guide/srcset-sizes.html this page has the same code as the repro project. The issue also appears in Blazor server but somewhat different as the image first appears but then disappears. The issue though does not appear in an MVC project. Chrome on iPhone has the same issue but I guess that is normal since it is a Safari wrapper. It should also be noted that pictures appear in Chrome on a Mac computer.

**Comment by vlasgeorge** [comment]
@pranavkm how can you be sure that this is not a Safari related problem since it works as expected on Chrome?

**Comment by vlasgeorge** [comment]
Also the same project does not load on iOS 10.3.4, it stops at the initial loading screen. Tested on iPhone 5.

**Comment by pranavkm** [comment]
Sorry I was out a fair bit of last month. I'm catching up on my work and will look at this shortly.

**Comment by vlasgeorge** [comment]
@pranavkm how's the investigation proceeding?

**Comment by pranavkm** [comment]
This appear to be an issue with Safari parsing document fragments. You can reproduce this independent of Blazor by doing this:

```html
<script>
    const template = document.createElement('template');
    template.innerHTML = '<img src="https://ik.imagekit.io/ikmedia/women-dress-2.jpg" srcset="https://ik.imagekit.io/ikmedia/women-dress-2.jpg?tr=w-225 225w,https://ik.imagekit.io/ikmedia/women-dress-2.jpg?tr=w-300 300w,https://ik.imagekit.io/ikmedia/women-dress-2.jpg?tr=w-350 350w,https://ik.imagekit.io/ikmedia/women-dress-2.jpg?tr=w-640 640w" sizes="(max-width: 400px) 100vw, (max-width: 700px) 50vw, (max-width: 900px) 33vw, 225px" />';
    document.body.appendChild(template.content.firstChild);
</script>
```

This works on browsers other than Safari. Interestingly using `createElement` to produce an img element and appending it to the DOM works fine. You can cause Blazor to use `createElement` by interleaving C# with your markup for e.g you could do something like this:

```razor
<img unsued="@false" ... 
```
which appears to resolve this issue. Given this is a browser issue, I'm going to mark this as resolved.
