### ISSUE TITLE
Append /Index to directory asp-page

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/aspnetcore#38816]
### Is your feature request related to a problem? Please describe.
I am trying to send the reader to the index page in a directory but the generated link is to the main page.

### Describe the solution you'd like
If the [referenced page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.anchortaghelper.page) is not found because it is a directory, the anchor tag helper should append `/Index` to the directory.

### Additional context
Currently the directory reference is treated like a missing page reference.

## Is this a Bug or Feature request?:
Feature

## Steps to reproduce
------------------- Please fill in this section -------------------------
Have a valid page `Pages/Test/Index.cshtml`.
Do not have a page ~`Pages/Test.cshtml`~.

Page `Index.html`:
```cshtml
<a asp-page="Test" >Test</a >
```

## Description of the problem:
------------------- Please fill in this section -------------------------

Expected behaviour:
```html
<A HREF="Test" >Test</A >
````

Actual behaviour:
```html
<A HREF="/" >Test</A >
````

## Logs
Nothing interesting.

#### OmniSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/dell/prog/mozilla_dell0/mozilla_dell0.csproj'.

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 18:04:25] -- Starting Issue Data Collection-- 
[Client - 18:04:47] -- Stopping Issue Data Collection-- 
```

</p>
</details>

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
Non Razor file as active document
```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
Could not determine CSharp content
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
Could not determine Html content
```

</p>
</details>

## Machine information

**VSCode version**: 1.62.3
**Razor.VSCode version**: 1.23.16
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Środowisko uruchomieniowe:
 OS Name:     opensuse-tumbleweed
 OS Version:  20211201
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.15.10|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.9.2|
|cpptools|ms-vscode|1.7.1|
|cpptools-extension-pack|ms-vscode|1.1.0|
|cpptools-themes|ms-vscode|1.0.0|
|csharp|ms-dotnettools|1.23.16|
|dotnet-interactive-vscode|ms-dotnettools|1.0.2602010|
|doxdocgen|cschlosser|1.3.2|
|Ionide-fsharp|Ionide|5.10.2|
|jupyter|ms-toolsai|2021.10.1101450599|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.4|
|python|ms-python|2021.11.1422169775|
|remote-containers|ms-vscode-remote|0.205.2|
|remote-ssh|ms-vscode-remote|0.66.1|
|remote-ssh-edit|ms-vscode-remote|0.66.1|
|remote-wsl|ms-vscode-remote|0.58.5|
|vscode-dotnet-pack|ms-dotnettools|1.0.4|
|vscode-language-pack-pl|MS-CEINTL|1.62.4|
|vscode-markdown-notebook|ms-vscode|0.0.26|
|vscode-pull-request-github|GitHub|0.32.0|
|vscode-pylance|ms-python|2021.11.2|
|vsliveshare|ms-vsliveshare|1.0.5090|
|vsliveshare-audio|ms-vsliveshare|0.1.91|;

</p>
</details>

**Comment by yecril71pl** [comment]
I created `Test.cshtml` with a redirect and got the following error:

> AmbiguousMatchException: The request matched multiple endpoints. Matches:
> /Test
> /Test/Index
> Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)

It seems the resolver can see the directory but the tag helper cannot.

**Comment by pranavkm** [comment]
For the page, `Pages/Test/Index.cshtml`, the value the `asp-page` parameter would expect to be specified is `Test/Index`; it's the path to the page starting from the pages root, without the extension. I believe using that should resolve your issue.

Changing the behavior of asp-page to append an additional token by default would be a breaking change which we're unlikely to consider.
