### ISSUE TITLE
Helix InstallLocalDb sometimes hangs on windows.11 queue

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#38819]
This affects all tests that depend on `<TestDependsOnMssql>true</TestDependsOnMssql>` which is BlazorTemplates and Diagnostics.Functionals, which are skipped due to this issue

Example Failing build
https://dev.azure.com/dnceng/public/_build/results?buildId=1496152&view=ms.vss-test-web.build-test-results-tab&runId=42710494&resultId=121669&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

Console log:
```
Console log: 'Diagnostics.FunctionalTests--net7.0' from job ed95df83-80b8-4bec-ae0b-2e1a7a4e0f27 workitem 36d49f76-85f9-41dc-8a73-fc6692046ff1 (windows.11.amd64.clientpre.open) executed on machine a002VHW

C:\h\w\BE6B0A32\w\A8870934\e>set PATH=C:\h\w\BE6B0A32\p\dotnet-cli;C:\python3.9.1\Scripts\;C:\python3.9.1\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\runner\AppData\Local\Microsoft\WindowsApps 

C:\h\w\BE6B0A32\w\A8870934\e>set DOTNET_ROOT=C:\h\w\BE6B0A32\p\dotnet-cli 

C:\h\w\BE6B0A32\w\A8870934\e>set DOTNET_CLI_TELEMETRY_OPTOUT=1 

C:\h\w\BE6B0A32\w\A8870934\e>set DOTNET_CLI_HOME=C:\h\w\BE6B0A32\w\A8870934\e\.dotnet 

C:\h\w\BE6B0A32\w\A8870934\e>set NUGET_PACKAGES=C:\h\w\BE6B0A32\w\A8870934\e\.nuget 

C:\h\w\BE6B0A32\w\A8870934\e>call RunPowershell.cmd mssql\InstallSqlServerLocalDB.ps1   || exit /b 1 
"PS: Running 'C:\h\w\BE6B0A32\w\A8870934\e\mssql\InstallSqlServerLocalDB.ps1' "
Installing SQL Server 2016 Express LocalDB

Downloading 'SqlLocalDB.msi' to 'C:\h\w\BE6B0A32\w\A8870934\e\mssql\obj\SqlLocalDB.msi'.
GET https://download.microsoft.com/download/9/0/7/907AD35F-9F9C-43A5-9789-52470555DB90/ENU/SqlLocalDB.msi
Download of 'https://download.microsoft.com/download/9/0/7/907AD35F-9F9C-43A5-9789-52470555DB90/ENU/SqlLocalDB.msi' complete, saved to C:\h\w\BE6B0A32\w\A8870934\e\mssql\obj\SqlLocalDB.msi...

Running 'msiexec /package "C:\h\w\BE6B0A32\w\A8870934\e\mssql\obj\SqlLocalDB.msi" /NoRestart /Passive IACCEPTSQLLOCALDBLICENSETERMS=YES HIDEPROGRESSBAR=YES'.
```

**Comment by SteveSandersonMS** [comment]
This probably also caused these failures:

https://dev.azure.com/dnceng/public/_build/results?buildId=1593779
https://dev.azure.com/dnceng/public/_build/results?buildId=1588543

**Comment by wtgodbe** [comment]
@HaoK is it worth checking to see if these work on Helix again?

**Comment by HaoK** [comment]
Did we disable them or is this just a test failure issue?

**Comment by HaoK** [comment]
I believe they are currently running still, just not on helix

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/blob/9c29067c4087014a63df37341213b221413a1997/src/Middleware/Diagnostics/test/FunctionalTests/Diagnostics.FunctionalTests.csproj#L9-L10

> I believe they are currently running still, just not on helix

Right, I'm wondering if we can re-enable them on helix

**Comment by HaoK** [comment]
Lets try it? we have retries now too

**Comment by mkArtakMSFT** [comment]
Let's try to reenable these tests and see if the issue still persists.

**Comment by wtgodbe** [comment]
Draft PR: https://github.com/dotnet/aspnetcore/pull/45573

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/45573
