### ISSUE TITLE
Allow handling of malformed HTTP Requests by supplying custom HttpParser

### ISSUE THREAD

**Issue by Danielku15** [dotnet/aspnetcore#38829]
### Is your feature request related to a problem? Please describe.
I am trying to use Kestrel for building a Ntrip v1 server where clients might send malformed HTTP requests (missing end of header terminator) but Kestrel rejects any malformed HTTP request.

### Describe the solution you'd like
It would be great if we can get a bit more control over what Kestrel does in case of detecting malformed requests. 
As described below there can be different kind of malformed requests from Ntrip clients: 

1. They might only send a status line, but nothing more. Clients will expect the server to reply after that single status/request line. 
2. They might send a status line and headers, but do not terminate the header and directly start sending some body data. 

To allow using kestrel in this Use Case I see two potential extensions as feasible:

* Allow injecting a custom [IHttpParser](https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs#L15) through DI. Currently it is [created internally](https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs#L132) and there seems is no way to supply a custom one. 
* Allow extending the built-in HttpParser to handle certain errors by overriding methods more specifically. I would like to avoid a copy-paste of the original parser code but rather reuse and extend it but this part could also be optional. It's not so much code.  

To achieve Ntrip v1 compatibility and solve the issues above I would use the proposed features in this way: 

1. Once the request line is read, I would start a timeout mechanism. If no further data is received within a threshold, the request would be considered a fully received. This way we can handle clients only sending a request/status line without further bytes. Not sure if `KestrelServerLimits.RequestHeadersTimeout` could be repurposed for that. The logic of it lives on the `Http1Connection` level.
2. [At the location](https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs#L230) where the parser rejects connections due to a wrong header format, I would also like to flag the request as complete at the line start and treat the remaining data already as body. 

### Additional context

Ntrip is a standard in the GNSS Positioning domain which leverages the HTTP handshake to establish a permanent connection to a data stream. You can compare it with something like WebSockets where the protocol takes a HTTP request and response handshake. Afterwards the TCP connection stays open and raw data can be transmitted between the parties. 

In Version 1 standard description of the protocol, there were quite imprecise in defining the need of a header terminator `\r\n\r\n` when a client makes a request to the server. This lead to many client implementations which send malformed requests and servers need to be able to handle this. In Version 2 they luckily corrected it. 

In our custom server implementation we have various heuristics to detect whether a request might be malformed and we have to consider the header as completed already. If we would manage to get these heuristics into Kestrel we could fully rely on it for our server needs and even use further ASP.net core pipeline features.  

https://igs.bkg.bund.de/ntrip/about
https://en.wikipedia.org/wiki/Networked_Transport_of_RTCM_via_Internet_Protocol

The benefits we would gain would basically be all benefits of using Kestrel over a custom Server: 

1. Awesome performance
2. Ntrip over HTTP/2 and HTTP/3 
3. TLS support.
4. Smooth integration into ASP.net core pipelines.

**Comment by davidfowl** [comment]
Anything that affects the performance of the HTTP parser would not be ideal so I'd be very opposed to parser extensibility for a use case that doesn't seem very broad.

Why not start with a custom IServer implementation based on Kestrel (or is that what you already have?)?

**Comment by Danielku15** [comment]
I understand your initial worries about the performance and that's why my proposal aims for a minimal impact for the default implementation. Let's recap on the proposal (numbers as above): 

1. This part proposes to allow injecting a custom `IHttpParser` through DI instead of [directly creating it](https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs#L132). This part luckily is a 1 time creation. There is 1 instance of the parser created for the whole `IServer` which is also a Singleton.  
2. Here I see some potential risks depending on the extension points we offer. It's hard to tell what would be needed to actually fulfill my needs. I could live with making no changes there, but rather pulling a copy of it into my application code. Making the `RejectRequestHeader` protected+virtual, include the request handler and include a more precise reason on what is wrong, could be a start. 

So let's focus on part 1 only and see if it would be feasable. 

> Why not start with a custom IServer implementation based on Kestrel (or is that what you already have?)?

We currently build on a completely different socket server library and have an own protocol handler there which is parsing the HTTP request and sending responses on a raw byte level. 

Adapting the [`KestrelServerImpl`](https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs) to our level does not seem feasable because some classes like the `TransportManager` and `Heartbeat` are internal. It would require me to copy quite a bunch of the original source instead of just using it.

**Comment by blowdart** [comment]
To add onto David's concern we reject a lot of invalid requests for security purposes. Allowing them for such a narrow use case in the base parser would be a big security no.

**Comment by Danielku15** [comment]
@blowdart Yes, I fully understand that. That's the primary reason why I did not request that the base implementation is adapted to generally allow such HTTP requests. I know that requesting a change on the base parser to allow accepting more malformed requests is not within the goals of Kestrel. Of course Kestrel is already extensible to custom protocols with connection handlers, but it just feels wrong inventing an own HTTP connection handler. 

My request concerns mostly this line where a fixed implementation of the `HttpParser` is created: 
https://github.com/dotnet/aspnetcore/blob/ddf24d9f4187c0f1d009da309441b48926a213fc/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs#L132

I would like to provide a custom `IHttpParser` there. To stay consistent with other extension principles like the `IConnectionListenerFactory` it could look like this: 

```cs
// Interface 
public interface IHttpParserFactory { IHttpParser<TRequestHandler> CreateHttpParser(bool showErrorDetails) where TRequestHandler : IHttpHeadersHandler, IHttpRequestLineHandler; }
// Default implementation registered as singleton. 
public class DefaultHttpParserFactory { IHttpParser<TRequestHandler> CreateHttpParser(bool showErrorDetails) => new HttpParser<TRequestHandler>(showErrorDetails); }
// usage in KestrelServerImpl
private static ServiceContext CreateServiceContext(IOptions<KestrelServerOptions> options, 
    ILoggerFactory loggerFactory, 
    DiagnosticSource? diagnosticSource
    IHttpParserFactory httpParserFactory /* new parameter, provided like ILoggerFactory through DI */)
{
    // ...
    return new ServiceContext
    {
        Log = trace,
        Scheduler = PipeScheduler.ThreadPool,
        HttpParser = httpParserFactory.CreateFactory>(trace.IsEnabled(LogLevel.Information)),
        // ..
    };
}
```

Theoretically it would also be possible to add a factory method to `KestrelServerOptions` (parallel to the `ConnectionFilter` extension point). The pro on this variant would be that the impact is on a minimal level (1 new option + call it in the `CreateServiceContext` where it is available), the con would be that it does not align well with the factory pattern which is more common. 

If there is a good chance to get this minmal change in, I would be willing to start a PR for further discussions there on the details.

**Comment by ddvk** [comment]
any progress? We ran into this just recently, we have iot devices that worked with IIS/Katana, but they send an extra `\r\n` between requests, which Kestrel started rejecting. 
The quickfix/hack was to patch ParseHeaderLine, but this is not idea at all. An option to inject a custom HttpParser would be nice.

**Comment by davidfowl** [comment]
We have no plans to allow malformed requests.
