### ISSUE TITLE
Hot Reload doen't work with UseResponseCompression Enabled

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/aspnetcore#38832]
Hot Reload doen't work with UseResponseCompression Enabled.
It took me 3 hours to find it. If you don't plan to fix it please improve the docs.

[hot-reload docs](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)

related : [28293](https://github.com/dotnet/aspnetcore/issues/28293)

**Comment by rjgotten** [comment]
Hot Reload is a hot mess.

The reason it doesn't work with response compression enabled, is that there's an injector middleware at play which has to wedge a script tag into your response which loads the JavaScript-side of the hot reload infrastructure. It can't do that properly with response bodies which are compressed.

It also completely breaks any and all responses that are type `text/html` but are _not_ meant as actual page loads. For instance: what if I have an authoring application with an HTML editor which wants to load _another_ HTML document via `fetch`?

There isn't even a proper way to turn the ASP.NET add-ons _off_ and retain only the server-side C# hot reloading features. Even if you switch off the Hot Reload features under `Tools -> Projects and Solutions -> ASP.NET Core -> Hot Reload` in VS 2022, the script injector will still run. The only way to turn it off 'from the outside' is to configure VS 2022 to turn off the _entire_ hot reloading feature _as well as_ the legacy edit & continue feature, under `Tools -> Debugging -> .NET / C++ Hot Reload`.

Imho this 'automagical' nature of wiring in a feature which applies potentially destructive mutations to markup and the browser runtime environment is return to WebForms mistakes from the past and whoever decided it was a good idea to include this injector middleware as part of defaults should get a boot up their ass.

**Comment by DamianEdwards** [comment]
Duped to #38454.
We'll add logging to ensure finding these incompatibilities is easier.

**Comment by rjgotten** [comment]
@DamianEdwards 
So, let me get this straight: you're marking this as a dupe of an issue that was pushed out to the planning phase for .NET 7, for consideration/evaluation?

You're marking what is clearly a hideous bug in .NET 6 that corrupts response bodies; for which the only simple workaround is to disable and remove feature functionality from Visual Studio 2022, including features that worked fine in VS 2019 and earlier (namely: basic Edit & Continue) -- as a dupe of something that will only _potentially_ be fixed with .NET 7?
When .NET 6 is the actual LTS?

Wow.

**Comment by DamianEdwards** [comment]
Please see my comment in https://github.com/dotnet/aspnetcore/issues/32767#issuecomment-1020519246

One can disable Hot Reload in the launch/debug profile of the project so that Edit and Continue keeps working but the browser refresh script is not injected.
