### ISSUE TITLE
StatusCodes: improve documentation

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/aspnetcore#38833]
### Is your feature request related to a problem? Please describe.
I am trying to provide a textual representation of a HTTP status code&mdash;but the definition of [StatusCodes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes) is one way only.

### Describe the solution you'd like
The documentation for [Status404NotFound](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes.status404notfound) should say:

> The numeric value of [NotFound](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-6.0#System_Net_HttpStatusCode_NotFound).

### Additional context
That way, the reader can discover that there *is* an enum for HTTP status codes, which is exactly what is needed to have a two-way mapping, and understand what these status codes really mean without leaving the documentation portal.

Fixed by #38831.

**Comment by Tratcher** [comment]
What is the two way mapping is for? Do you mean you're trying to programmatically display status codes as text, as well as reverse lookup by text back to integers?  Have you tried the ReasonPhrases class?
https://github.com/dotnet/aspnetcore/blob/bf9225b8d7fd5f8ee855dd50407a90587b812662/src/Http/WebUtilities/src/ReasonPhrases.cs#L90

> and understand what these status codes really mean without leaving the documentation portal.

The current comment for Status404NotFound reads: `HTTP status code 404.` I could see expanding that to something like `HTTP status code 404, meaning the resource wasn't found.`
