### ISSUE TITLE
Blazor SDK Targets Packaging Fixes

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38844]
> It's the files package.json and dotnet.d.ts which I added to native of the Microsoft.NETCore.App.Runtime.Mono.browser-wasm.7.0.0-dev.nupkg in runtimes\browser-wasm\native. Each of them twice, once as is, and second as .gz, that's why 4 new items in the diff.

> The Blazor would put those files into wwwroot\_framework\
I think that they would do not harm in there, but I would prefer to keep them compile time files, not copied to wwwroot.
How is that achieved ?

This is a rough corner of how we build the runtime pack, I suspect the new files are probably just escaping a work around in the blazor sdk targets.  We should fix that but I'd like to solve the underlying problem as well.

cc @TanayParikh @javiercn

_Originally posted by @lewing in https://github.com/dotnet/sdk/pull/22892#issuecomment-985933133_

**Comment by SteveSandersonMS** [comment]
Still to be determined if we definitely need to do something here.
