### ISSUE TITLE
In Blazor, load a page inside a page

### ISSUE THREAD

**Issue by vcarlucci** [dotnet/aspnetcore#38849]
I am trying to load a Blazor page inside another Blazor page.

With html <iframe../> it loads the whole Blazor page including the sidebar etc. what is not what we are looking for. What we would achieve is to load just the pageXY.razor inside another page somewhere in a defined region.

Please let me know ASAP, because we are in the middle of a project and this issue is getting important for us on how we proceed here.. Thank you in advance!

*Note: I could not find any documentation regarding my requirement, so I am not sure if this is already possible in a way or not.

**Comment by TanayParikh** [comment]
Based on your description, it appears you're trying to utilize a Blazor component.

Ie. you want to show ComponentABC.razor inside of HomePage.razor. In that case, you can just do:

HomePage.razor:

```razor
<ComponentABC></ComponentABC>
```

ComponentABC.razor:

```razor
Hello World from Component ABC!
```

Documentation on using components is found here https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components#use-components. No need to utilize iFrames! 😄 

I'd recommend checking out the Blazor demo by doing `dotnet new blazorserver`. Note how the `<SurveyPrompt>` component (`SurveyPrompt.razor`) is used inside `Index.razor`.

**Comment by vcarlucci** [comment]
Hi

Thank you for your prompt reply. Sorry I forgot, we are now working with Blazor and we dont have to think so complicated anymore 😉

Of course, your solution works just perfect. 

Thank you for your help!

..back to work.
