### ISSUE TITLE
Instruction pointer stays in commented out code after hot reload

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38846]
Repro:

1. Enter the instruction pointer into a `while` loop (example below)
2. Comment out the `while` loop. Hot reload should be triggered.

Expected: Instruction pointer is advanced to the next line after the commented out code.
Actual: The instruction pointer behaves as if it is still inside the (now commented out) `while` loop (ie. continues printing `Attach at ...` in the example below).

```csharp
while (!System.Diagnostics.Debugger.IsAttached)
{
    Console.WriteLine($"Attach at {Environment.ProcessId}"); // Comment out loop and hot reload when this starts printing
    System.Threading.Thread.Sleep(1000);
}

Console.WriteLine("Outside loop");
```

**Comment by pranavkm** [comment]
The method needs to be re-executed for changes applied by hot reload to be picked up. If your while loop surrounded the functional call, this would work e.g.:


```C#
while (!System.Diagnostics.Debugger.IsAttached)
{
   PrintAndSleept();
}

void  PrintAndSleep()
{
    Console.WriteLine($"Attach at {Environment.ProcessId}"); // Comment out loop and hot reload when this starts printing
    System.Threading.Thread.Sleep(1000);
}
```

Some of these restrictions are removed with the debugger attached (in .NET Core), but this behavior is by design.
