### ISSUE TITLE
WebApplicationBuilder should not Require wwwroot Directory

### ISSUE THREAD

**Issue by WispArchitecture** [dotnet/aspnetcore#38857]
Creating a `WebApplicationBuilder` fails when `wwwroot` directory is not present.
Error @ WebApplication.CreateBuilder(...): ` System.IO.DirectoryNotFoundException: 'C:\..\..\app\wwwroot\'`
Attempting to bypass with `WebApplicationOptions` (`WebRootPath = null` or '/') has no effect. 

This is inconsistent with previous web host builder behavior and seems to force apps to `UseStaticFiles`. This should be optional.
It makes sense as a default. But using the option `WebRootPath = null` should bypass this.

**Comment by davidfowl** [comment]
cc @captainsafia

**Comment by captainsafia** [comment]
@WispArchitecture How are you configuring your `WebApplicationBuilder`? 

I'm not able to repro with the following variants:

```
var builder = WebApplication.CreateBuilder(new WebApplicationOptions());
var app = builder.Build();
```
```
var builder = WebApplication.CreateBuilder();
var app = builder.Build();
```

The current behavior is that it will attempt to create a new directory if it doesn't exist.

**Comment by WispArchitecture** [comment]
It looks like the issue is that an `include` is getting added to the `.csproj` for `wwwroot`.
Once appears and I delete it, it doesn't seem to come back.

I'm able to repro. I use sockets. 
Create a new app and trim it down, and replace `Program` code with the code below.
Ensure it runs, and delete `wwwroot`. The error occurs.

 VS2022/Net6 - Create new Web App. Trim to:
![image](https://user-images.githubusercontent.com/88837883/145403604-5c04dec8-e830-4efa-a5dd-a2ae859826e4.png)
 
Code
```
using System.Net.WebSockets;
using System.Text;

await BuildWeb().StartAsync();
new AutoResetEvent(false).WaitOne();

/* **********   Locals   ********** */

WebApplication BuildWeb() {
    WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
    WebApplication app = builder.Build();
    _ = app.UseRouting();
    _ = app.AppeaseChrome();
    _ = app.UseWebSockets();
    _ = app.MapGet("/", async (HttpContext context) => {
        if(!context.WebSockets.IsWebSocketRequest) { await Boot(context); }
        if(context.WebSockets.IsWebSocketRequest) { await Run(context); }
    });
    return app;

    /* **********   Locals   ********** */

    async Task Boot(HttpContext context) => await context.Response.WriteAsync(Resources.WebBoot);

    async Task Run(HttpContext context) {
        WebSocket socket = await context.WebSockets.AcceptWebSocketAsync();
        await socket.SendText(Resources.Command);
        Console.WriteLine(await socket.WaitOnText());
    }
}

/* **********   Utility   ********** */

static class Resources {
    public static string WebBoot => @"<script>
self.AsyncFunction = Object.getPrototypeOf(async function () { }).constructor;
self.socket = new WebSocket(location.origin.replace('http', 'ws'));
socket.onmessage = async (msg) => socket.send(await (new AsyncFunction(msg.data))());
self.loadDocument = (content) => { const newHTML = document.open(); newHTML.write(content); newHTML.close(); }
</script>";

    public static string Command => @"loadDocument('<h2>Home</2>')";
}

public static class Ext {
    public static async Task SendText(this WebSocket socket, string msg) =>
        await socket.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(msg)),
            WebSocketMessageType.Text, true, CancellationToken.None);

    public static async Task<string> WaitOnText(this WebSocket socket) {
        ArraySegment<byte> buffer = WebSocket.CreateServerBuffer(1024);
        WebSocketReceiveResult? response = await socket.ReceiveAsync(buffer, CancellationToken.None);
        string? data = Encoding.UTF8.GetString(buffer.Slice(0, response.Count));
        return data;
    }

    public static WebApplication AppeaseChrome(this WebApplication app) {
        _ = app.MapGet("/favicon.ico", async context => {
            await context.Response.SendFileAsync($"{app.Environment.ContentRootPath}\\favicon.ico");
        });
        return app;
    }
}
```

**Comment by captainsafia** [comment]
> It looks like the issue is that an include is getting added to the .csproj for wwwroot.

Yep, this seems to be the contributing factor. I wasn't able to repro without the include in the csproj (or adding it in after the fact).

Backlogging this for now since I don't see an obvious bug in the config loading that merits fixing.

**Comment by code1line** [comment]
> @WispArchitecture How are you configuring your `WebApplicationBuilder`?
> 
> I'm not able to repro with the following variants:
> 
> ```
> var builder = WebApplication.CreateBuilder(new WebApplicationOptions());
> var app = builder.Build();
> ```
> 
> ```
> var builder = WebApplication.CreateBuilder();
> var app = builder.Build();
> ```
> 
> The current behavior is that it will attempt to create a new directory if it doesn't exist.

You can repro this by setting WebRootPath to another value, e.g. "Web".

**Comment by aschuhardt** [comment]
Is there a workaround for this?

**Comment by captainsafia** [comment]
> It looks like the issue is that an include is getting added to the .csproj for wwwroot.

@WispArchitecture Can you share an example of what the csproj that triggers the bug looks like?

**Comment by captainsafia** [comment]
> You can repro this by setting WebRootPath to another value, e.g. "Web".

I'm not able to repro this (https://github.com/captainsafia/WebRootPathExamples/tree/main/WebRootPathSet). I'm observing the directory is created.

> Ensure it runs, and delete wwwroot. The error occurs.

Are you deleting the wwwroot path during runtime? That might explain the behavior here.

Closing this as no-repro for now. Examples are available [here](https://github.com/captainsafia/WebRootPathExamples).
