### ISSUE TITLE
RuntimeBinderException: 'System.Dynamic.DynamicObject' does not contain a definition for 'UserName'

### ISSUE THREAD

**Issue by hhakangull** [dotnet/aspnetcore#38863]
### Description
I'm trying to dotnet core 6 on VSCode. When I changed ViewBag.Username="XXX" to "YY"  on HomeController.cs or another Controller.cs  I got this error => "RuntimeBinderException: 'System.Dynamic.DynamicObject' does not contain a definition for 'UserName'  "  on html page  with dotnet watch run

### Configuration

Windows 11 x64
.NET Core 6.0.100

### Regression?

When I restart to "dotnet watch run" it is fixed but when I change again ViewBag.Username it's happened again

**Comment by danroth27** [comment]
This is a know issue with hot reload and dynamic types. See https://github.com/dotnet/aspnetcore/issues/38845
