### ISSUE TITLE
Blazor wasm hot reload refresh server only accessible at ws:// in Visual Studio

### ISSUE THREAD

**Issue by Karql** [dotnet/aspnetcore#38888]
Hi!

I have noticed that when I run Blazor wasm project (CTRL+F5) from Visual Studio 2022 17.0.2
refresh server is only accessible at ws:// url.

![hr-hsts](https://user-images.githubusercontent.com/173098/145180617-29576942-a54e-4909-8676-451279cdaf88.png)

![hr-no-wss-vs](https://user-images.githubusercontent.com/173098/145180650-9f636688-c5e3-44e9-8296-c47bf2303f8e.png)

Chrome by default blocks request to ws:// when page is visited by https.

This behavior prevent hot reload feature from working.

When project is run from cli command refresh server is accesible by both wss:// and ws://

![hr-wss-cli1](https://user-images.githubusercontent.com/173098/145181417-32a1d006-8a23-42e3-b853-5f4c860a66be.png)

![hr-wss-cli2](https://user-images.githubusercontent.com/173098/145181442-3ab2e3da-cc0c-4ee5-823f-2354fd88f523.png)

A workaround I clear chrome policies in: `chrome://net-internals/#hsts`

![hr-hsts-off](https://user-images.githubusercontent.com/173098/145181601-146dd7a6-0d92-4959-8fb2-21b201c3139c.png)

My question is: Wheter run project from Visual Studio should also add possibility to connet to refresh server by wss protocol?

Best regards,
Mateusz

**Comment by pranavkm** [comment]
Since this is a VS specific issue, could you use the VS feedback tool - https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 to file this? That way this gets routed to the right team.

FYI @BillHiebert
