### ISSUE TITLE
Opening and closing port at runtime

### ISSUE THREAD

**Issue by adamradocz** [dotnet/aspnetcore#38885]
### Is your feature request related to a problem? Please describe.
I use the kestrel as TCP server for a gateway solution, and I need a solution to open/close/change a port in the kestrel at runtime.

### Describe the solution you'd like
Be able to open/close/change the listening ports at runtime, just like when you change the appsettings.json and kestrel update its port.

@guardrex

**Comment by davidfowl** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/21244
