### ISSUE TITLE
Add possibility to customize `Server` response header in `KestrelServerOptions`

### ISSUE THREAD

**Issue by plachor** [dotnet/aspnetcore#38895]
Hi we have option to disable response header `Server=Kestrel` however in our case we would like to use a generic `CodeName` instead `Kestrel`. We want to preserve header itself as it allows us to distinguish which layer has responded (microservice, load-balancer  or cdn and etc) but for security reasons we do not want to expose which concrete implementation we are relaying on. 

I know we could disable adding server header by Kestrel itself and adding it manually in middleware,  however I believe we would risk on rare occasions responses without this header if request would be terminated before reaching our middleware.

**Comment by davidfowl** [comment]
> I know we could disable adding server header by Kestrel itself and adding it manually in middleware, however I believe we would risk on rare occasions responses without this header if request would be terminated before reaching our middleware.

This is the recommended approach.

**Comment by Tratcher** [comment]
> I believe we would risk on rare occasions responses without this header if request would be terminated before reaching our middleware.

That is possible, though it should only happen with requests that are rejected due to being invalid (400 Bad Request). Missing a server header on those seems low risk.

**Comment by plachor** [comment]
For 400 (Bad Request) I'm not worried as my middleware is first in pipeline so I can handle it myself. I'm more worried about transient issues like network partition, closed connection or other internal server error (corner case bug) that will terminate this request on Kestrel level before reaching my middleware.

On such occasions I worry that we will end with internal server error response (like bad gateway) without clue which server terminated this. That is why I believe it will be more robust to allow us customize default value and let Kestrel to worry to append it on very last phase.
