### ISSUE TITLE
Node.js processes *still* don't quit after stopping debugging

### ISSUE THREAD

**Issue by casperOne** [dotnet/aspnetcore#38897]
### Describe the bug

The same issue as #5204, *many* nodejs instances continue to run after debugging an ASP.NET Core application.

Currently, I am using `taskkill.exe /F /IM node.exe /T` to shut down instances after *each* debugging session to mitigate this.  Here's a screenshot showing 18 nodejs processes running (all children of VS.NET) after debugging:

![image](https://user-images.githubusercontent.com/561862/145219792-95869712-db3f-4d53-b53b-36cdd068bade.png)

One (or more) of these is typically (but not always) consuming a large amount of CPU.

It tends to slow down performance on my machine quite a bit after this.

### To Reproduce

This is an ASP.NET Core React SPA application that was created with the template ~ASP.NET Core 2.1.  It's been upgraded over time and is currently on ASP.NET Core 5.0.

Debugging occurs in VS.NET 2022.

I do have a private github repo that I'm willing to share privately to assist.

**Comment by TanayParikh** [comment]
Hello @casperOne, thanks for contacting us. Are you still experiencing this issue in .NET 6?

**Comment by casperOne** [comment]
@TanayParikh Yes, after switching to 6.0, after going through two debug sessions, there were 13 nodejs processes that were hanging around.

![image](https://user-images.githubusercontent.com/561862/145238324-1ad6cd74-965a-4e62-b7d1-08f8b36e6048.png)

**Comment by TanayParikh** [comment]
Hmm that's certainly strange. We've had issues with processes not being killed after debugging, but having 13 errant processes after just 2 debug session seems very odd. 

Are you sure the processes are all being created by .NET / VS? Could you try using [Proc Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to get an idea of the process hierarchy / tree?

**Comment by casperOne** [comment]
@TanayParikh I've looked into this more.  While debugging, the process tree looks like this:

![image](https://user-images.githubusercontent.com/561862/145242190-9c4b3f5c-3e23-4332-8305-a4726dc228d8.png)

You can see that the node instances are children of iisexpress.  The full command line of the cmd.exe process that controls the nodejs process is

````
"cmd" /c npm run start -- 
````

However, when I close the browser (effectively ending the debugging session), the cmd.exe (with the child nodejs processes) gets orphaned:

![image](https://user-images.githubusercontent.com/561862/145243003-6012669f-2581-4d83-a2a1-d6f9b981d9e2.png)

**Comment by TanayParikh** [comment]
Thanks @casperOne that's really helpful. Do you have a minimal, public, GitHub repro project that we could use to investigate further? Note we aren't able to use private repos

**Comment by TanayParikh** [comment]
Linking in https://github.com/dotnet/aspnetcore/issues/34425 and the associated PR: https://github.com/dotnet/aspnetcore/pull/34427.

**Comment by casperOne** [comment]
@TanayParikh I will try and whittle this down to something I can post on a public repo.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @javiercn can you please look into this when you're back from vacation and see what's the culprit here? Thanks!

**Comment by casperOne** [comment]
@mkArtakMSFT @javiercn @TanayParikh I have a minimal example here

https://github.com/casperOne/asp-net-core-react-spa-note-wont-shut-down

It's my project, reduced to bare bones that sets up the ASP.NET Core side, displaying "Hello there" through React.

I've confirmed that the behavior with orphaned nodejs processes occurs with this example.

Note: You'll have to run `yarn install` to initialize your `node_modules` directory before debugging.

**Comment by Smoovsky** [comment]
Same here. 

I personally run a script every time after I'm done with debugging to get around with this.

```PowerShell
# powershell script
get-process | where {$_.Name -eq 'node'}| foreach {$_.Kill()}
```
or with AutoHotKey(ctrl + k, ctrl + n)
```AutoHotkey
#k::
    Input, OutputVar, L1

    If (Asc(OutputVar) = Asc("n"))
    {
        If(FileExist("C:\Program Files\PowerShell\7\pwsh.exe"))
        {
            Run "C:\Program Files\PowerShell\7\pwsh.exe" -Command "get-process | where {$_.Name -eq 'node'} | foreach {$_.Kill()}"
        }
    }

    Return
``` 
It will simply kill all node processes. You can also make it part of the debug flow(add it to .csproj or launch.json), but it's not recommended.

**Comment by casperOne** [comment]
@Smoovsky 

> I personally run a script every time after I'm done with debugging to get around with this.

Yes, this (or some variation of this) can be done, the big problem is that it will kill other node processes that are running that are not involved with asp.net development.

While this would apply to my case, I see this as a "break in case of emergency" solution that shouldn't be the common approach in this scenario (even if it is currently the only approach that works).

**Comment by mkArtakMSFT** [comment]
Thanks for the repro project, @casperOne.
We believe this has been addressed in .NET 6.

Also note, that .NET 5 is out of support.
