### ISSUE TITLE
Building package.json with ClientAssets results in 404 Not Found

### ISSUE THREAD

**Issue by AB017JH** [dotnet/aspnetcore#38898]
Hello,

I have changed the semi-automatic build process to use the new alpha version ClientAssets NuGet following the blog and sample, unfortunately, it does not work for my case.
The npm install and build script ran fine. Outputting the correct .js files into the obj folder the set script in index file is in the current format
```
<script src="_content/ComponentsLibrary/749.js"></script>
<script src="_content/ComponentsLibrary/main.js"></script>
```
unfortunately getting the
```
749.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Using .net5.0, running Blazer hosted via http.sys
When using the semi-automatic build I was having the beforeBuild task in .csproj running the webpack and copying the file in the 
ComponentsLibrary/wwwroot/dist that worked fine
`webpack ./src/dockmanager.js -o ../wwwroot/dockManager.bundle"` 
now I have just
`webpack ./src/dockmanager.js` 
which results in files being in the
"ComponentsLibrary\obj\Debug\clientassets\749.js"
"ComponentsLibrary\obj\Debug\clientassets\main.js"

Did I miss some configuration?

Thank you for your help,

Stanislav.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please note that .NET 5 is out of support already.
We're also going to address some of the remaining issues in this area as part of https://github.com/dotnet/aspnetcore/issues/38445
