### ISSUE TITLE
Issues with RegEx behaviour in .NET 5

### ISSUE THREAD

**Issue by nickfinch71** [dotnet/aspnetcore#38894]
A statement calling the IsMatch method returns true when compiled to .NET 3.1 and .NET 6, but false when compiled to .NET 5.

**To Reproduce:**
The following statement outputs True when compiled to .NET 3.1 and .NET 6, but false when compiled to .NET 5

Console.WriteLine(new Regex("^(?:[0-9a-fA-F]{3,4}){1,2}$").IsMatch("8DB3E2"));

**Comment by gfoidl** [comment]
@stephentoub I believe this issue may be of interest for you (and this issue should be in runtime-repo).

**Comment by stephentoub** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/56721 which was fixed for .NET 6 in https://github.com/dotnet/runtime/pull/56735.
