### ISSUE TITLE
How to generate Component.razor.g.cs?

### ISSUE THREAD

**Issue by zxyao145** [dotnet/aspnetcore#38908]
Hi, I'm using .NET 6 and VS 2022, and how should I configure to generate the *.razor.g.cs in the "obj/Debug/net6.0/RazorDeclaration" directory. It's eassy in .NET 5.

**Comment by TanayParikh** [comment]
Hey @zxyao145, can you try:

```
$ dotnet build /p:EmitCompilerGeneratedFiles=true
```

**Comment by zxyao145** [comment]
> Hey @zxyao145, can you try:
> 
> ```
> $ dotnet build /p:EmitCompilerGeneratedFiles=true
> ```

Thank you! This is useful! And, the following configuration is also possible.

```xml
<PropertyGroup>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
```
