### ISSUE TITLE
DefaultDisplayTemplates: semantic HTML for ObjectTemplate 

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/aspnetcore#38915]
## Summary

The current output of `ObjectTemplate` is non-semantic; it uses generic `div` elements to present both properties and values.  It should use a definition list (`DL`) instead.

## Motivation and goals

It is harder to understand output that is non-semantic.  You cannot tell a name from a value.

## In scope

I display an [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) and I want to be able to understand the display.

## Out of scope

The case of an object with no properties need not be supported.

## Risks / unknowns

Unable to see any.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

```cshtml
@(Html .DisplayFor (model => model .Failure))
```

## Work-around
```cshtml
@functions {
    void DisplayObject (string name, object p) {
        IDictionary < string, object > d = HtmlHelper .ObjectToDictionary (p);
        if (d .Count > 0X0) {
          <DL >
          @foreach (string k in d .Keys .ToImmutableSortedSet ()) {
            <DT >@(Html .DisplayFor (m => k))</DT>
            <DD >@(
              Html .Display (string .Join ('.', new [] { name, k }))
            )</DD>
          }
          </DL>
        }
    }
}
```

### Notes
1. This work-around also *orders* the properties by name, which IMHO should also be done by default in order to improve readability.
2.  Note that although we would like to say `<DD ><P >` for message properties, it is not possible to use `<P >` by default because the value may be rendered as a block element.
3. It is not possible to use [DisplayFor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.rendering.htmlhelperdisplayextensions.displayfor) for values because the type of each value is not known at compile time.  That makes the interface less convenient to use.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We won't be able to implement this as it'll be a breaking change.
However, DisplayFor supports templates. [Here is a StackOverflow post](https://stackoverflow.com/questions/5710140/how-do-i-create-a-mvc-razor-template-for-displayfor) on this topic, which explains how you can do that. Hope that helps.

**Comment by yecril71pl** [comment]
> Thanks for contacting us. We won't be able to implement this as it'll be a breaking change. However, DisplayFor supports templates. [Here is a StackOverflow post](https://stackoverflow.com/questions/5710140/how-do-i-create-a-mvc-razor-template-for-displayfor) on this topic, which explains how you can do that. Hope that helps.

No, it does not.  I want to change the default behaviour.  I am not going to pepper my code with references custom templates to fix bugs in ASP.
