### ISSUE TITLE
Issues running .net 5 / 6 console app on VS2022

### ISSUE THREAD

**Issue by Pinox** [dotnet/aspnetcore#38913]
Hi Guys,

Not sure this is the right place to file this issue, but I filed an issue on Visual Studio Feedback hub and it was just closed again by the bot.

I have an .net 5 console app that I would like to upgrade to .net 6 but immediately ran into a problem with localhost certificates that does not work on port 443.  For comparison I kept my console app on .net 5 and it works in VS2019 and VS2019 Preview but not in VS2022.

I have attached a sample project that replicates the issue.

When I run this project in VS2019 , it runs the app on port 443 and everything works as expected. API is visible on refreshes in the browser. Certificate is perfect.

![image](https://user-images.githubusercontent.com/5297255/145359466-269009c3-34ae-408f-87e8-b4a4c3ed0708.png)

![image](https://user-images.githubusercontent.com/5297255/145359530-003ff9e4-53fc-4e96-9395-c74be96dc5c1.png)

When I run the same app on VS2022 then the app runs but the localhost certificate in the browser no longer works. 
My code references a certificate in Onedrive.

![443](https://user-images.githubusercontent.com/5297255/145359762-d260bbef-f839-430d-8d47-09156e4bc5aa.png)

In VS2022 the app runs fine but can't find the localhost certificate and therefor the api is no longer visible. Sometimes I see the API on first display but when I then refresh the page in Edge it displays the errors below.

![image](https://user-images.githubusercontent.com/5297255/145359976-8cfbfd29-a784-415d-abd6-69448e0c5f99.png)

![image](https://user-images.githubusercontent.com/5297255/145360026-139c8c16-74cc-407c-a132-63351ae96ee7.png)

Any suggestions or pointers will be much appreciated.

Sample project that reproduces the behavior below.

[Test443.zip](https://github.com/dotnet/aspnetcore/files/7683412/Test443.zip)

**Comment by adityamandaleeka** [comment]
Triage: A 500 error isn't a certificate error. Can you take a look at the server output to see what the error is?
