### ISSUE TITLE
Blazor cannot execute OnChange Event

### ISSUE THREAD

**Issue by indieza** [dotnet/aspnetcore#38916]
Hello,
I have an issue with the InputSelect tag, I want to execute OnChange handler and pass additional parameters into it, but situation is that, the OnChange method is successfully completed but the selected value of the target drop-down was deselected. I upload my code. The problem is hit on the first InputSelect

`ValueChanged="@((UserRoleType value) => this.GetUsersInOutOfRole(value, false))"`

```
@page "/AdministrationPanel"
@attribute [Authorize(Roles = GlobalConstants.AdministratorRole)]
@inject IAdministrationService administrationService

<PageTitle>Administration Panel</PageTitle>

<h3 class="pageHeading">Administration Panel</h3>
<hr />
<div class="row">
    <div class="col-12 col-sm-12">
        <h4 class="sectionHeading">Add User In Role</h4>
    </div>
</div>

<EditForm Model="@this.model" OnValidSubmit="@(async () => await this.AddUserInRole())">
    <DataAnnotationsValidator />
    <ValidationSummary />
    <div class="form-group">
        <div class="row">
            <div class="col-5 col-sm-5">
                <label>Role Type</label>
                <InputSelect
                 class="form-control"
                 ValueExpression="@(() => this.model.RoleType)"
                 Value="@this.model.RoleType"
                 ValueChanged="@((UserRoleType value) => this.GetUsersInOutOfRole(value, false))">
                    <option value="" selected disabled>Select role...</option>
                    @foreach (var roleType in ((UserRoleType[])Enum.GetValues(typeof(UserRoleType))).OrderBy(x => x.ToString()))
                    {
                        <option value="@roleType">@(roleType.ToString().SplitCamelCase())</option>
                    }
                </InputSelect>
                <ValidationMessage For="@(() => this.model.RoleType)" />
            </div>
            <div class="col-5 col-sm-5">
                <label>Username</label>
                <InputSelect class="form-control" @bind-Value="this.model.UserName">
                    <option value="" selected disabled>Select user...</option>
                    @foreach (string username in this.usernames.OrderBy(x => x.ToString()))
                    {
                        <option value="@username">@(username)</option>
                    }
                </InputSelect>
                <ValidationMessage For="@(() => this.model.UserName)" />
            </div>
        <div class="col-2 col-sm-2">
            <button class="btn btn-primary" type="submit">Add</button>
        </div>
        </div>
    </div>
</EditForm>

@code {
    AddRemoveUserToFromRoleInputModel model = new AddRemoveUserToFromRoleInputModel();
    List<string> usernames = new List<string>();

    private async Task AddUserInRole()
    {
    }

    private async Task GetUsersInOutOfRole(UserRoleType roleType, bool inRole)
    {
        this.usernames =await this.administrationService.GetUsernamesInOutOfRole(roleType, inRole);
        this.StateHasChanged();
    }
}
```

Regards,
Simeon Valev

**Comment by MariovanZeist** [comment]
You aren't updating the
```this.model.RoleType``` value inside the ```GetUsersInOutOfRole``` function. This will result in ```this.model.RoleType``` never changing.

and might be what's causing your issue.

**Comment by TanayParikh** [comment]
> the OnChange method is successfully completed but the selected value of the target drop-down was deselected.

Thanks for contacting us @indieza. I'm not sure I follow what the issue is. Are your saying the OnChange is triggered onblur (when you click outside the element)? If so, that's expected behavior. 

> The problem is hit on the first InputSelect\n\nValueChanged=\"@((UserRoleType value) => this.GetUsersInOutOfRole(value, false))\

Are you having an issue with ValueChanged or OnChange?

Here's some (external) documentation on the differences between OnChange and ValueChanged which may be helpful: https://docs.telerik.com/blazor-ui/components/combobox/events

**Comment by indieza** [comment]
@MariovanZeist your solution works, but now I have a problem with the default value of the first InputSelect

`<option value="" selected disabled>Select role...</option>`

When I load the page for first time, that default value is not selected as I expect. Any ideas why?

Regards,
Simeon Valev

**Comment by MariovanZeist** [comment]
@indieza You could make ```this.model.RoleType``` nullable. That way the default value of the input will be shown.

**Comment by TanayParikh** [comment]
Thanks @MariovanZeist, marking resolved.
