### ISSUE TITLE
Better Support for multiple forms on the same Razor Page

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#38920]
My page has two forms, each with a corresponding model decorated with the `BindProperty` attribute.

```
[BindProperty]
public TripDetailsUpdateDto UpdateTrip { get; set; }

[BindProperty]
public TripNoteUpdateDto UpdateNote { get; set; }
```

Although either form works fine on its own, having both of them causes `ModelState.IsValid` to return false. This is because both models are combined and, when only one model is submitted, the properties of the other model haven't been set and so are invalid.

Is there any way to have better support for multiple forms on a Razor Page?

I tried dealing with this by writing a method that uses reflection to loop through each property of the model being validated, and removes those items from `ModelState` that are not a property. But then I discovered that `ModelState` items that represented posted values have keys like `UpdateNote.Text`, while items that were never posted have keys like `Text`.

So, I don't know if it's safe to simply remove all items from `ModelState` where the key contains a period, if this is the most performant way of addressing this, or if there is a completely different way to deal with this that is better.

This must be a common issue. Is there any way to add better support for this?

---

So, as mentioned, you could add a method to `ModelStateDictionary` that accepts the model type as an argument. And then uses reflection to remove all those items from `ModelState` that are not a property of that type.

But the simpler method below also seems to work for me.

        public void RemoveNonpostedItems()
        {
            foreach (string key in Keys)
            {
                if (!key.Contains('.'))
                    modelState.Remove(key);
            }
        }

**Comment by pranavkm** [comment]
Couldn't you bind properties in the handler method instead of attempting to bind them as common properties?

**Comment by DamianEdwards** [comment]
We intended for page handlers and their parameters to be the solution to this scenario, e.g.
``` c#
public TripDetailsUpdateDto UpdateTrip { get; set; }
public TripNoteUpdateDto UpdateNote { get; set; }

public void OnPostTripDetails(TripDetailsUpdateDto updateTrip)
{
    UpdateTrip = updateTrip;
}

public void OnPostTripNote(TripNoteUpdateDto updateNote)
{
    UpdateNote = updateNote;
}
```

**Comment by SoftCircuits** [comment]
Cool. I didn't realize that worked differently. Yes, I agree that is much better. Thanks.

**Comment by SoftCircuits** [comment]
Question: How would you declare this in the markup? Since there is no page model object to refer to?
