### ISSUE TITLE
Razor class libraries static resources are not available in another project

### ISSUE THREAD

**Issue by DenisPolagaev** [dotnet/aspnetcore#38924]
**Describe the bug:**
 want to create a nuget package with a certain library of components.

Creating a razor class library project with the name TestBlazor.

Changing the standard component:

Component1.blazor

```c#
@inject ExampleJsInterop js;

<div class="my-component">
    This component is defined in the <strong>Test</strong> library.
</div>

@code{
    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await js.Prompt("asasgg");
        }
    }
}
```
ExampleJsInterop:

```c#
using Microsoft.JSInterop;

namespace TestBlazor
{
    // This class provides an example of how JavaScript functionality can be wrapped
    // in a .NET class for easy consumption. The associated JavaScript module is
    // loaded on demand when first needed.
    //
    // This class can be registered as scoped DI service and then injected into Blazor
    // components for use.

    public class ExampleJsInterop : IAsyncDisposable
    {
        private readonly Lazy<Task<IJSObjectReference>> moduleTask;

        public ExampleJsInterop(IJSRuntime jsRuntime)
        {
            moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>(
               "import", "./_content/TestBlazor/exampleJsInterop.js").AsTask());
        }

        public async ValueTask<string> Prompt(string message)
        {
            var module = await moduleTask.Value;
            return await module.InvokeAsync<string>("showPrompt", message);
        }

        public async ValueTask DisposeAsync()
        {
            if (moduleTask.IsValueCreated)
            {
                var module = await moduleTask.Value;
                await module.DisposeAsync();
            }
        }
    }
}
```
Now I want to call my component in another solution:

I connect it to the project for the test:

![image](https://user-images.githubusercontent.com/32395325/145356913-85c1c243-821a-44f4-92cc-2e14f1d70434.png)

and I use my own component:

```c#
builder.Services.AddTransient<TestBlazor.ExampleJsInterop>();
```
```c#
<TestBlazor.Component1></TestBlazor.Component1>
```

I get an error:
Microsoft.JSInterop.JSException: Failed to resolve module specifier 'https://localhost:7181/_content/TestBlazor/exampleJsInterop.js'

tried solutions from here:

https://github.com/dotnet/aspnetcore/issues/13103

but nothing worked

**Version used:**
e.g. VS2022 17.0 Preview 1
.net 6

**Comment by TanayParikh** [comment]
> I connect it to the project for the test:
> 
> ![image](https://user-images.githubusercontent.com/32395325/145356913-85c1c243-821a-44f4-92cc-2e14f1d70434.png)

Hello @DenisPolagaev, it looks like you're referencing the dll instead of the nuget package. Can you please try referencing the packed nuget package?
