### ISSUE TITLE
CloseOnAuthenticationExpiration Does not exist in class properties

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/aspnetcore#38922]
https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/SignalR/common/Http.Connections/src/HttpConnectionDispatcherOptions.cs#L31

document:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.httpconnectiondispatcheroptions.closeonauthenticationexpiration?view=aspnetcore-6.0
As this document says, there should be a boolean property as `CloseOnAuthenticationExpiration` on the `HttpConnectionDispatcherOptions` class which there is not according to definition. Does this property removed from the class and what is the reference?

**Comment by halter73** [comment]
I'm confused. Are you not seeing this?

https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/SignalR/common/Http.Connections/src/HttpConnectionDispatcherOptions.cs#L130-L137

**Comment by pranavkm** [comment]
@halter73 perhaps they're on an earlier version. The API appears to have been introduced in 6.0

**Comment by pranavkm** [comment]
@abdollahkahne what's the `TargetFramework` of the app you're building?

**Comment by abdollahkahne** [comment]
@pranavkm @halter73 
Yes, I am sorry for taking your time.I see it now. I should check it on net6.0 too. I working with 5.0 while view 6.0 documentation.

Where I can ask a feature for `@microsoft/signalr.js` package? Is it maintained here? Thanks again

**Comment by halter73** [comment]
> Where I can ask a feature for `@microsoft/signalr.js` package? Is it maintained here? Thanks again

Yes. It's maintained in this repo [here](https://github.com/dotnet/aspnetcore/tree/69f09eea69dbb42b8cbc044306c0b3f44d98f8d2/src/SignalR/clients/ts/signalr).
