### ISSUE TITLE
Problems with using WebSocket in Edge

### ISSUE THREAD

**Issue by dlyltm** [dotnet/aspnetcore#38929]
I developed a asp.net core web project with vs2019. I wrote the WebSocket program according to the method in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-5.0. The program works well in ie,but not in Edge. What's the reason for this?

**Comment by adityamandaleeka** [comment]
Can you provide more info about what your program is doing and how it's failing on Edge? What error do you see?

Also, are you using SignalR or direct WebSockets?

**Comment by dlyltm** [comment]
The problem has been solved. It is caused by a js statement that is not supported by Edge.
