### ISSUE TITLE
Blazor WASM does not load on iOS 10.3.4.

### ISSUE THREAD

**Issue by vlasgeorge** [dotnet/aspnetcore#38938]
Blazor WASM does not load on iOS 10.3.4, it stops at the initial loading screen. I have tried  to debug it using my PC and an iPhone 5 but I get no errors at dev tools, it just stops at the initial loading screen.

### To Reproduce
Publish [repro project ](https://github.com/vlasgeorge/Blazor-WASM)on Azure, then run the app on an iPhone that has iOS 10.3.4.

### Further technical details
- ASP.NET Core version: .NET 5
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by TanayParikh** [comment]
Hello @vlasgeorge, thanks for contacting us. Safari updates are tied to the iOS version. It appears the last iOS 10 update was on 22 Jul 2019 and it is now out of support (from what I can tell). Thus, this version of Safari isn't supported as Blazor is only officially supported on "current" browsers. 

https://docs.microsoft.com/aspnet/core/blazor/supported-platforms?view=aspnetcore-6.0
