### ISSUE TITLE
ForwardedHeaders and incorect RemoteIpAddress 

### ISSUE THREAD

**Issue by AlexanderOpran** [dotnet/aspnetcore#38940]
### Describe the bug
I am using ForwardedHeaders and even though the header (X-Forwarded-For) is present in the request (I have added logging just after the useForwardedHeaders to see all headers) and contains the real ip of the client, RemoteIpAddress still returns an invalid IP (it just returns the IP of the node).

### To Reproduce
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
                options.KnownNetworks.Clear();
                options.KnownProxies.Clear();
            });

          /* .......................... */
        }
```
 ` app.UseForwardedHeaders();` - first thing in `Configure`

I have tried various other iterations of it, including:

```
         var forwardingOptions = new ForwardedHeadersOptions()
            {
              ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            };
            forwardingOptions.KnownNetworks.Clear(); 
            forwardingOptions.KnownProxies.Clear(); 

            app.UseForwardedHeaders(forwardingOptions);
```

### Further technical details
- ASP.NET Core version: NET 5 (5.0.12)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022

**Comment by Tratcher** [comment]
Try the troubleshooting steps at https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer?#troubleshoot and let us know what you find.

**Comment by AlexanderOpran** [comment]
I have done the troubleshooting steps. I am logging all the headers and then the IP address (this happens immediately after `useForwardedHeaders`).

```
        var forwardingOptions = new ForwardedHeadersOptions()
            {
              ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            };
            forwardingOptions.KnownNetworks.Clear(); // Loopback by default, this should be temporary
            forwardingOptions.KnownProxies.Clear(); // Update to include

            app.UseForwardedHeaders(forwardingOptions);
            app.Use((c, n) =>
            {
                foreach (var header in c.Request.Headers)
                {
                    Console.WriteLine($"{header.Key}: {header.Value}");
                }
                Console.WriteLine($"Remote IP Address: {c.Connection.RemoteIpAddress}");
                return n();
            });

```

**Results:**

```
Content-Type: application/json
Accept-Encoding: gzip,deflate
Host: example.com
User-Agent: Apache-HttpClient/4.5.12 (Java/1.8.0_292)
Content-Length: 45
x-forwarded-for: 1.2.3.4
x-envoy-external-address: 10.42.10.0
x-request-id: 94d246c8-bd98-4093-adac-2c988a783f91
x-envoy-attempt-count: 1
x-forwarded-client-cert: certificate
x-b3-traceid: 6ccdfc3ff5b801d1ea2d9f63c04afc1a
x-b3-spanid: afb70cfe007b3caa
x-b3-parentspanid: ea2d9f63c04afc1a
x-b3-sampled: 0
X-Original-For: 127.0.0.1:55358
X-Original-Proto: http

Remote IP Address: 10.42.10.0
```

**Comment by Tratcher** [comment]
Oh, the forwarders were applied, but you have two proxies so there were two entries in x-fowarded-for. I can tell because X-Original-For was added. 

Raise the ForwardLimit to 2.
https://github.com/dotnet/aspnetcore/blob/a39afae2bfe184ce580c6e66640aeb242d68f661/src/Middleware/HttpOverrides/src/ForwardedHeadersOptions.cs#L59-L64

**Comment by AlexanderOpran** [comment]
@Tratcher  Thanks for the help, it gets the correct IP Address now. One thing that I noticed though is that it will remove the X-Forwarded-For header from the request. Is this intended? Thanks! 

Also, wouldn't it make sense to get the utmost left value (since that is the initial "real ip") instead of the utmost right one? (given that the default limit is 1)

**Comment by Tratcher** [comment]
Yes, it shifts values from X-Forwarded-For to RemoteIp to X-Original-For. Not a great design in hindsight...

Values are processed right to left because of the risk of spoofing, you should be verifying each step is an expected proxy, not clearing KnownNetworks/Proxies.

**Comment by AlexanderOpran** [comment]
@Tratcher Yes, we will not clear the `KnownNetworks `or `KnownProxies` but will instead use two specific networks here. 🐱 Thanks for clearing things up! Can be closed. Perhaps the documentation can be updated a bit to highlight some pottential issues.
