### ISSUE TITLE
`browser-refresh.js` not found at `localhost` when using remote debugging

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38946]
I'm doing `dotnet watch` in Codespaces. As such, instead of `localhost`, the app is served up at `https://tanayparikh-{ORGANIZATION}-{REPOSITORY}-*-{PORT}.githubpreview.dev/`. Thus the `browser-refresh` isn't found at the `ws://localhost` location it's queried at.

![image](https://user-images.githubusercontent.com/14852843/145612787-77696c78-8f3c-4d9a-a11e-3ce036e1a259.png)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
