### ISSUE TITLE
SignalR: Handling Redis lost connection. 

### ISSUE THREAD

**Issue by mudassarawanpk** [dotnet/aspnetcore#38944]
The SignalR connection between the Client and the Server is interrupted due to some network issue and messages to and from other servers (via Redis) will be lost.

The client will connect again after some tries but could not registered with redis server somehow and due to this messages are not being sent between the clients. Any quick resolution?

**Comment by halter73** [comment]
SignalR should automatically reconnect to Redis, but any messages sent while the Redis server is down will be lost. https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-5.0#redis-server-errors

Is this not what you're seeing? If you're seeing different behavior like SignalR not automatically reconnecting, can you provide [ASP.NET Core logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)?
