### ISSUE TITLE
[Feature Request] :Improve visual studio snippet feature by using pseudo-random-looking named functions instead of storing pasted codes

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38959]
I want to have a place in visual studio, for me to write static functions and just throw them in there.
It should support any language quite well.
what it should do is to add them to the source code before compilation.

Then I would like the ability to define where these functions should be (for example all in a static partial class of mine) and then support non public functions.

This allow me to write random functions with a summery which makes my code look cleaner, we can remember numbers or X00000000 better than remembering the whole archetecture and we can reuse it through the code faster than I would reuse it by clicking and pasting snippets with a mouse. My teams should be able to use these functions as I've created them in visual studio, so now when people are writing code and they want a feature, they can either use one already there if it's already there, or if they've never wrote that piece of code and they didn't know it existed they can just make a new one and throw them in the snippet.

this can also be done by some other kinds of precompiler hacks like reserved named for hidden classes for snippet usage.

this would cost no performance because it just gets inlined during optimizations and unused functions are trimmed, and we don't have to worry about maintaining garbage if we assume everything we wrote is garbage, that's why we use peudo-random-names because does X00000000 means anything to you? no. you have no attachment. it's like a kid you got and you didn't expect it and you are like oh ok I guess whatever. People can hover their mouse if they want to know what that function did in the IDE, if the method that's calling it hasn't already communicated it to the developer through function names and comments. This way developers only put their brain capacity at what's important - - the top layer of the abstraction, and let their mussle memory do the works for unimportant tasks, implementing S programs.

**Comment by Xyncgas** [comment]
what's more, what defines a function should be the things it does, that's why you can always navigate to the function you are calling within the same project to look at its source code instead of trusting what the function name tells you, which you get lazy and people make mistakes for trusting a function to do something it's expected to do but it didn't do what it's expected to do but you are the one at fault because you are stupid you made that mistake and you are getting paid and you chose to trust that function to throw no exceptions when its name says log token_(turns out it assumed something was available), it's like when a man is telling you he sells candy but it turns out you need to put it in your nose instead of your mouth in order to ingest it.

**Comment by TanayParikh** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options) to report this issue, so the team who owns the area can track the ask.
