### ISSUE TITLE
blazor wasm first load after release cause the error . TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by zarinportal** [dotnet/aspnetcore#38961]
### Describe the bug
blazor wasm first load after release cause the error . TypeError: NetworkError when attempting to fetch resource.

### To Reproduce

exp: [https://tpanel.inotex.com](https://tpanel.inotex.com)

### Exceptions 
Console Errors:
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Uncaught (in promise) Error: Failed to start platform. Reason: TypeError: NetworkError when attempting to fetch resource.

### Further technical details
- .Net 6 Blazor
- Visual Studio 2022

<details>
  <summary></summary>

```

```

</details>

**Comment by TanayParikh** [comment]
Hey thanks for contacting us,

> ### To Reproduce
> exp: https://tpanel.inotex.com

I'm not actually seeing that error when I visit that site. Do you have a minimal, public github repro of the issue?

> Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
> Uncaught (in promise) Error: Failed to start platform. Reason: TypeError: NetworkError when attempting to fetch resource.

Is this the whole error, or was there something more about the specific resource which couldn't be loaded.

**Comment by zarinportal** [comment]
Depending on the speed of the Internet, the number of errors will increase or decrease. To retest, make sure you clear the cache and disable it 

![image](https://user-images.githubusercontent.com/44922871/145709426-b9a88444-a6c8-4911-97c7-a5b077f5ac95.png)


![image](https://user-images.githubusercontent.com/44922871/145709439-f4e814d7-8057-4bd0-94ac-80722ecf6c3f.png)

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @zarinportal. Looking at your shared website it looks like your server network speed is low and maybe unreliable. We recommend hosting your website on a server with reliable network connection and that would most probably address your issues.
As a side note, from my experience, the download speed for the content from that server is was about ~20Kb/s and a lot of requests have been failing.

**Comment by zarinportal** [comment]
Thanks
