### ISSUE TITLE
[.NET6] Referencing Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation breaks hot reload for .cshtml files

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/aspnetcore#38965]
Similar to [issue #38809](https://github.com/dotnet/aspnetcore/issues/38809) but this is about regular Razor views, not Blazor components.

Here's the repro steps.

- Create a new project with `dotnet new mvc`
- Reference the razor view runtime compilation package with `dotnet add package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`
- **Issue:** hot reload is no longer watching changes done to `.cshtml` files. Verify it by running `dotnet watch --list`. All `.cshtml` files are no longer listed in the output. Here's a sample output.
```
> dotnet watch --list
E:\myproject\Controllers\HomeController.cs
E:\myproject\Models\ErrorViewModel.cs
E:\myproject\Program.cs
E:\myproject\MyProject.csproj
E:\myproject\Views\Shared\_Layout.cshtml.css <-- All .cshtml files from /Views are missing
E:\myproject\wwwroot\css\site.css
E:\myproject\wwwroot\favicon.ico
...
```
I would happily do without the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package if [OmniSharp issue #4822: integrate debugging with dotnet watch](https://github.com/OmniSharp/omnisharp-vscode/issues/4822) was solved. I'm a VSCode user and I would like to use `dotnet watch` all the time for development but I can't because the debugger won't attach automatically when the process is restarted.

**Comment by pranavkm** [comment]
RuntimeCompilation and hot reload for cshtml are effectively trying to solve the same problem. As a result, dotnet-watch opts out of watching .cshtml files if the runtime compilation package is reference. That said, you should be able to hit refresh in the browser and see changes to your cshtml files as it has worked in earlier versions of .NET.

**Comment by BrightSoul** [comment]
> RuntimeCompilation and hot reload for cshtml are effectively trying to solve the same problem

Hot reload is also responsible for refreshing the browser page and that stops happening when the RuntimeCompilation package is referenced. That's the issue.
Instead, it should keep refreshing the page even if the compilation step is performed by the RuntimeCompilation package. 

It's underwhelming to hear this is "by design" since there's still no complete solution.
- With hot reload, we don't get the debugger automatically attached;
- With the RuntimeCompilation package, the browser page won't reload automatically.

**Comment by dotnetshadow** [comment]
One possible workaround is to do this:
<ItemGroup>
	  
	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
  </ItemGroup>
  
  What is the impact of doing this?
  
  Also is there a way to only use RuntimeCompilation when you want to publish?
