### ISSUE TITLE
The problem of re-initializing components during routing.

### ISSUE THREAD

**Issue by DezareD** [dotnet/aspnetcore#38966]
### Describe the bug
The main problem is that if let's say I am on page "/user/32" and go to page "/user/ 55" then the page is not reinitialized. Is there a way to get around this somehow and force it to reinitialize when I call NavigateTo (...). 
Probably blazor should have settings to change this.

Important: this problem can be solved by using forceReload in the parameters of the NavigateTo (...) method, but I want to build a complete SPA application without reloading.

### To Reproduce

Submit a page with some attribute and create links to this page so that only the url segment changes.
I use await _js.InvokeVoidAsync("Blazor._internal.navigationManager.navigateTo", ...); 

### Further technical details
- .NET 5.0
- Visual Studio 16.10.3
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
Џ ЄҐв SDK ¤«п .NET (®ва ¦ ойЁ© «оЎ®© global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

‘аҐ¤  ўлЇ®«­Ґ­Ёп:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by pranavkm** [comment]
You could perform your initialization as part of `OnParametersSet` / `OnParametersSetAsync` instead of OnInitialized. Also I would recommend using `NavigationManager.NavigateTo` rather than the implementation JS methods `Blazor._internal....` since those are subject to breaking changes.
