### ISSUE TITLE
How to access PageModel in classlibrary

### ISSUE THREAD

**Issue by miladahmadi33** [dotnet/aspnetcore#38972]
### Describe the bug
I want to use PageModel in class library, I installed Microsoft.AspNetCore.Mvc in my class library but still, I can't access ```[PageRemote]``` in the class library.

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

**Comment by pranavkm** [comment]
You'll need to reference the ASP.NET Core shared framework (https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework) in your class library.
