### ISSUE TITLE
Environment Variables on Blazor Webasm issues

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/aspnetcore#38987]
### Describe the bug
 I'm developing a project using Blazor Webasm + ASP.NET Core WebAPI as the backend.

When I want to concentrate on the frontend stuff, I run the webasm project directly without the backend using it's own launchSettings. I added other variables other than ASPNETCORE_ENVIRONMENT to choose some settings when I launch the website, while maintaining ASPNETCORE_ENVIRONMENT as Develop. This thing works like a charm when I do the same on the backend and I can retrieve the values using Environment.GetEnvironmentVariable() but on the frontend it just doesn't work. I suppose it's because in the browser the env variables are handled differently, but ASPNETCORE_ENVIRONMENT is injected in some ways.

Do you have any idea on how could I achieve the same thing? I've seen something like adding the variables in the head of index.html, but this means I have to create a different ASPNETCORE_ENVIRONMENT to differentiate, but I would prefer to avoid it.

### To Reproduce

Create a new blazor webasm project (even without backend), add a new variable under the "env" object in launchsettings.json and then launch the project. If you try to get the variable value it will be empty

### Further technical details
- ASP.NET Core version: 6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022 17.0.1
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (che rispecchia un qualsiasi file global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Environment variables aren't available to Blazor WebAssembly. We recommend using application settings configuration APIs to pass configuration to a Blazor WebAssembly apps. You can read more about it from [our docs](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/configuration).
