### ISSUE TITLE
Remove obsolete types from code and code parts that uses types not available in higher versions. 

### ISSUE THREAD

**Issue by andres291** [dotnet/aspnetcore#38985]
Using Unity it is a problem to have the obsolete type Microsoft.AspNetCore.Http.Authentication.AuthenticationManager in the assembly Microsoft.AspNetCore.Http.Abstractions because it uses Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext type that is not in assembly Microsoft.AspNetCore.Http.Features of version 5.0.12, that we currently use. Unity unloads the assembly Microsoft.AspNetCore.Http.Abstractions.

Error: Could not load signature of Microsoft.AspNetCore.Http.Authentication.AuthenticationManager:AuthenticateAsync due to: Could not resolve type with token 01000058 (from typeref, class/assembly Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext, Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) assembly:Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext member:(null) signature:<none>

Same here:

Using Unity it is a problem to have the type Microsoft.Net.Http.Headers.DateTimeFormatter:AppendYear in the assembly Microsoft.Net.Http.Headers because it uses Microsoft.Extensions.Primitives.InplaceStringBuilder type that is not in assembly Microsoft.Extensions.Primitives of version 5.0.1, that we currently use. Unity unloads the assembly Microsoft.Net.Http.Headers.

Error: Could not load signature of Microsoft.Net.Http.Headers.DateTimeFormatter:AppendYear due to: Could not resolve type with token 01000026 (from typeref, class/assembly Microsoft.Extensions.Primitives.InplaceStringBuilder, Microsoft.Extensions.Primitives, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) assembly:Microsoft.Extensions.Primitives, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.Extensions.Primitives.InplaceStringBuilder member:(null) signature:<none>

### To Reproduce
Use Unity and open the unity project from here: https://github.com/andres291/aspnetcore-38985

**Comment by pranavkm** [comment]
I'm not entirely sure how Unity projects references packages or `FrameworkReference`s, but it sounds like your app is mixing 5.0 .NET Core framework reference and 2.2 ASP.NET Core package references. Mixing major versions is unsupported and likely to produce errors like the ones you're seeing. Additionally, ASP.NET Core 2.2 has been [out of support](https://docs.microsoft.com/lifecycle/products/microsoft-net-and-net-core) for some time now, so definitely shouldn't be using those.

Doing a cursory reading of how Unity works, my guess is you're not going to be able to reference the 5.0 ASP.NET Core framework from a unity app. Your best bet might be to copy in individual types that are relevant to your app in to a separate dll that you can then consume.
