### ISSUE TITLE
Access to the IDatabase field in RedisCache

### ISSUE THREAD

**Issue by bramve-fenetre** [dotnet/aspnetcore#38993]
### Is your feature request related to a problem? Please describe.
I'm creating a RedisCache instance using it's constructor directly, so i have the full RedisCache instance API available to me. However i wish to use some additional functionality that is only provided by the IDatabase object, which is a private field in RedisCache, so i cannot access it without using reflection

### Describe the solution you'd like
Would it be possible to just make the IDatabase field public and the Connect method so i can just use all the standard functionality provided by the RedisCache class but custom functionality as provided by the IDatabase interface?

### Additional context
For context in our project we have a custom cache interface replacing the IDistributedCache with some additional functionality. We would really like that our implementation of this cache behaves exactly the same as the RedisCache class except with the additional features that are not in there. Which is why i thought this would easily be possible if IDatabase was just public.

Note: I think there are similar issues on here like https://github.com/dotnet/aspnetcore/issues/28374 . But in my case i do not need it in the IDistributedCache interface, i just need the IDatabase field in the RedisCache to be public.

**Comment by bramve-fenetre** [comment]
@Tratcher Yes indeed, but i would prefer to just use the RedisCache implementation directly if possible, since if it is improved upon in this repository then we would just have to update the nuget package.

**Comment by Tratcher** [comment]
This implementation's purpose is to implement IDistributedCache. Your requirements go well beyond that and aren't something we plan to pursue.
