### ISSUE TITLE
[.NET 6 Blazor server] can't catch properly an ObjectDisposedException when stream from c# to Js

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#39017]
Hello guys, I had a bug on my code which thrown an "System.ObjectDisposedException: Cannot access a closed Stream", when i was sending a stream to js. 

The error was pretty clear, i was trying to consume a stream already consumed.

but anyway, i saw the exception was not catch so it let the app in a incoherent State.

I have an ErrorBoundary also in the app which was not updated.

I see anyway the error in the chrome console.
[2021-12-14T11:21:57.920Z] Error: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass46_0.<<SendDotNetStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.SendDotNetStreamAsync(DotNetStreamReference dotNetStreamReference, Int64 streamId, Byte[] buffer)

I now manage how to deal to avoid this exception, but im wonder why it can't be catch properly and let the app in inchoherent state.

To reproduce:
- Create a MemoryStream in the initialized of a component
- on a button click, send the stream to the js (surround with try catch)
- click again on the button, you will have the app broken

**Comment by TanayParikh** [comment]
Interestingly, doing something like `_ = await JS.InvokeAsync<string>("nonExistantFunction");` upon button press doesn't crush the circuit and successfully triggers the error boundary.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue further, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by Tyme-Bleyaert** [comment]
I think my issue #53376 is also partially related to this.
The difference is I don't try to access a closed / consumed stream but also get an exception I'm unable to catch.
