### ISSUE TITLE
Use JSON Property Name attributes when creating ModelState Validation errors

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#39010]
## Background and Motivation
Currently, when the model validation produces the ModelErrorDictionary it will use the property name as error's key, as described in the example bellow, however in scenarios as SPA applications it can be difficult to handle the response since most of the time the property name is an implementation detail and not exactly what is expose through the JSON data.

```c#
public class Outer
{
    [Range(1, 100)]
    [JsonPropertyName("bar")]
    public int Num { get; set; }
    
    [Required]
    public InnerClass SubClass { get; set; }

    public class InnerClass
    {
       [Range(1,10)]
       public int Test1 { get; set; }
    }
}
```

```json
{
  "errors": {
    "Num": [
      "The field Num must be between 1 and 100."
    ],
    "SubClass.Test1": [
      "The field Test1 must be between 1 and 100."
    ]
  }
}
```
Also, even when the JSON attributes are not used to define the property name the current implementation does not follow the JSON Naming Policy, that have been a complain since 2016 (#5590).

The proposal is to add two new Metadata Providers, `JsonMetadataProvider` and `NewtonsoftJsonMetadataProvider`, the last will be added when the `AddNewtonsoftJson` is called while the first one could be added by the customer using the `MvcOptions`. These new providers will be responsible for read from `Newtonsoft.Json.JsonPropertyAttribute` or `System.Text.Json.SerializationJsonPropertyNameAttribute` to set the new property  `ValidationMetadata.ValidationModelName` that will be used during the `Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry` creation.

When the new providers are included, the same example provided will produce the following result:

```json
{
  "errors": {
    "bar": [
      "The field bar must be between 1 and 100."
    ],
    "subClass.test1": [
      "The field test1 must be between 1 and 100."
    ]
  }
}
```

Related:
- #17999

## Proposed API
```diff
namespace Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
   
+ /// <summary>
+ /// An implementation of <see cref="IDisplayMetadataProvider"/> and <see cref="IValidationMetadataProvider"/> for
+ /// the System.Text.Json.Serialization attribute classes.
+ /// </summary>
+ public class JsonMetadataProvider: IDisplayMetadataProvider, IValidationMetadataProvider
+ {
+     /// <summary>
+     /// Creates a new <see cref="JsonMetadataProvider"/> with the default <see cref="CamelCaseNamingStrategy"/>
+     /// </summary>
+     public JsonMetadataProvider()

+     /// <summary>
+     /// Creates a new <see cref="JsonMetadataProvider"/> with an optional <see cref="JsonNamingPolicy"/>
+     /// </summary>
+     /// <param name="namingPolicy">The <see cref="JsonNamingPolicy"/> to be used to configure the metadata provider.</param>
+     public JsonMetadataProvider(JsonNamingPolicy namingPolicy)

+     public void CreateDisplayMetadata(DisplayMetadataProviderContext context)

+     public void CreateValidationMetadata(ValidationMetadataProviderContext context)

+ }
```

```diff
namespace Microsoft.AspNetCore.Mvc.NewtonsoftJson;
   
+ /// <summary>
+ /// An implementation of <see cref="IDisplayMetadataProvider"/> and <see cref="IValidationMetadataProvider"/> for
+ /// the Newtonsoft.Json attribute classes.
+ /// </summary>
+ public class NewtonsoftJsonMetadataProvider : IDisplayMetadataProvider, IValidationMetadataProvider
+ {
+     /// <summary>
+     /// Creates a new <see cref="JsonMetadataProvider"/> with the default <see cref="CamelCaseNamingStrategy"/>
+     /// </summary>
+     public NewtonsoftJsonMetadataProvider()

+     /// <summary>
+     /// Initializes a new instance of <see cref="NewtonsoftJsonMetadataProvider"/> with an optional <see cref="NamingStrategy"/>
+     /// </summary>
+     /// <param name="namingStrategy">The <see cref="NamingStrategy"/> to be used to configure the metadata provider.</param>
+     public NewtonsoftJsonMetadataProvider(NamingStrategy namingStrategy)

+     public void CreateDisplayMetadata(DisplayMetadataProviderContext context)

+     public void CreateValidationMetadata(ValidationMetadataProviderContext context)

+ }

```

```diff
namespace Microsoft.AspNetCore.Mvc.ModelBinding.Metadata
{
   public class ValidationMetadata
   {
+     public string? ValidationModelName { get; set; }
   }
}
```

## Usage Examples

 ```csharp
services..AddControllers(options => options.ModelMetadataDetailsProviders.Add(new JsonMetadataProvider()))
 ```
or

 ```csharp
services.Configure<MvcOptions>(options =>
        options.ModelMetadataDetailsProviders.Add(new JsonMetadataProvider(JsonNamingPolicy.CamelCase)));
 ```

Is also possible remove the default provider, if needed:

 ```csharp
services.Configure<MvcOptions>(options => {
                options.ModelMetadataDetailsProviders.RemoveType<NewtonsoftJsonMetadataProvider>();            
});
```

**Comment by oliverjanik** [comment]
While this overlooked and downplayed bug is being looked at, what workarounds exist?

**Comment by pranavkm** [comment]
Let's seal these types and name them to be more explicit about what they are associated with (STJ vs NewtonsoftJson and that they have to do with validation)

```diff
- public class JsonMetadataProvider
+ public sealed class SystemTextJsonValidationMetadataProvider

-  public class NewtonsoftJsonMetadataProvider : IDisplayMetadataProvider, IValidationMetadataProvider
+ public sealed class NewtonsoftJsonValidationMetadataProvider : IDisplayMetadataProvider, IValidationMetadataProvider
```

**Comment by brunolins16** [comment]
> Let's seal these types and name them to be more explicit about what they are associated with (STJ vs NewtonsoftJson and that they have to do with validation)
> 
> ```diff
> - public class JsonMetadataProvider
> + public sealed class SystemTextJsonValidationMetadataProvider
> 
> -  public class NewtonsoftJsonMetadataProvider : IDisplayMetadataProvider, IValidationMetadataProvider
> + public sealed class NewtonsoftJsonValidationMetadataProvider : IDisplayMetadataProvider, IValidationMetadataProvider
> ```

@pranavkm just to include we discussed that will not add the providers as default. So, they will need to be included during the configuration using:

### STJ

```csharp
services..AddControllers(options => options.ModelMetadataDetailsProviders.Add(new SystemTextJsonValidationMetadataProvider()))
```
or
```csharp
services.Configure<MvcOptions>(options =>
       options.ModelMetadataDetailsProviders.Add(new SystemTextJsonValidationMetadataProvider(JsonNamingPolicy.CamelCase)));
```

### NewtonsoftJson

```csharp
services..AddControllers(options => options.ModelMetadataDetailsProviders.Add(new NewtonsoftJsonValidationMetadataProvider ()))
```
or
```csharp
services.Configure<MvcOptions>(options =>
       options.ModelMetadataDetailsProviders.Add(new NewtonsoftJsonValidationMetadataProvider (new CamelCaseNamingStrategy())));
```

**Comment by RehanSaeed** [comment]
Any reason why this is not enabled by default?

**Comment by brunolins16** [comment]
@RehanSaeed, the new providers will set the new internal `ValidationModelName` that is used during the ModelState error creation, and `DisplayName` that is used during the error creation but also in other parts of the framework, that means, in case, you have a Model, with Json attributes, that is been used for both Views and APIs  (not recommended but possible) with the new providers added, the metadata will change for both cases. So, we decided to give the control when this behavior is applicable.

**Comment by niemyjski** [comment]
@brunolins16 will there be a way to configure this without mvc options? I'm using api controllers with ModelState driven Problem Details

**Comment by brunolins16** [comment]
@niemyjski  can you share a sample app, so, I can provide what you need to do.

Right now we do not have plans to backport.

**Comment by niemyjski** [comment]
@brunolins16 here is a link to one of our apps: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Web/Startup.cs#L269-L272

**Comment by brunolins16** [comment]
@niemyjski you can add the provider here:

https://github.com/exceptionless/Exceptionless/blob/940a04c28c74cad34221113a865a979510c2d432/src/Exceptionless.Web/Startup.cs#L48

Example:

``` diff
        services.AddControllers(o => {
            o.Filters.Add<ApiExceptionFilter>();
+           o.ModelMetadataDetailsProviders.Add(new SystemTextJsonValidationMetadataProvider());
            o.ModelBinderProviders.Insert(0, new CustomAttributesModelBinderProvider());
            o.InputFormatters.Insert(0, new RawRequestBodyFormatter());
        }).AddNewtonsoftJson(o => {
            o.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Include;
            o.SerializerSettings.NullValueHandling = NullValueHandling.Include;
            o.SerializerSettings.Formatting = Formatting.Indented;
            o.SerializerSettings.ContractResolver = Core.Bootstrapper.GetJsonContractResolver(); // TODO: See if we can resolve this from the di.
        });
```
