### ISSUE TITLE
Render another partial view (B) within a partial view (A) by specifying relative path to current partial view (A)

### ISSUE THREAD

**Issue by datvm** [dotnet/aspnetcore#39014]
### Is your feature request related to a problem? Please describe.

I have a Razor Pages project (no Controller) with structure like this:

![image](https://user-images.githubusercontent.com/6388546/145939402-62a6b794-460c-405d-8dbd-4fea0020dcfe.png)

From the main `Index.cshtml`, I would render a partial view for its content depend on the Theme name, for example:

```cshtml
@* Default will be replaced with theme name *@
<partial name="Themes\Default\HomeContent" />
```

In `HomeContent.cshtml`, I would like to render many other partial views within its folder. However this wouldn't work:

```cshtml
<p>Content</p>

<partial name="_DefaultThemePartial" />
```

[The engine only searches these locations:](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-6.0#partial-view-discovery)

> InvalidOperationException: The partial view '_DefaultThemePartial' was
> not found. The following locations were searched:
> 
> /Pages/_DefaultThemePartial.cshtml
> 
> /Pages/Shared/_DefaultThemePartial.cshtml
> 
> /Views/Shared/_DefaultThemePartial.cshtml

I have also tried `<partial name="./_DefaultThemePartial" />` or `<partial name=".\_DefaultThemePartial" />` or try putting them in a subfolder named `Shared` (within the Default folder). None of them works, only the above 3 locations are searched.

### Describe the solution you'd like

Razor Pages should search for a file in the same folder as its current partial view in addition to the current paths.

### Additional context

It may also be nice that we can interfere with the path discovery. Is it possible?

**Comment by datvm** [comment]
> It may also be nice that we can interfere with the path discovery. Is it possible?

I found out it's actually possible using `IViewLocationExpander` although I cannot find any official documentation on how to use it:

```c#
public class PartialViewLocationExpander : IViewLocationExpander
{
    public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
    {
        if (!context.Values.TryGetValue("FromView", out var fromView))
        {
            return viewLocations;
        }

        var folder = Path.GetDirectoryName(fromView) ?? "/";
        var name = context.ViewName;
        if (!name.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase))
        {
            name += ".cshtml";
        }

        var path = Path.Combine(folder, name)
            .Replace('\\', '/');

        return viewLocations.Concat(new[] { path });
    }

    public void PopulateValues(ViewLocationExpanderContext context)
    {
        var ctx = context.ActionContext as ViewContext;
        if (ctx == null) { return; }

        var path = ctx.ExecutingFilePath;
        if (!string.IsNullOrEmpty(path))
        {
            context.Values["FromView"] = path;
        }
    }
}

// Register
services.Configure<RazorViewEngineOptions>(options =>
{
    options.ViewLocationExpanders.Add(new PartialViewLocationExpander());
});
```

**Comment by TanayParikh** [comment]
Hi @datvm, this is by design. Partial view lookup is done in two ways:

- By name
- By file path

You've done the lookup by name (without file extension), if you want to use a relative path, make sure you specify the file extension.

```cshtml
<partial name="_DefaultThemePartial.cshtml" />
```

**Comment by datvm** [comment]
> You've done the lookup by name (without file extension), if you want to use a relative path, make sure you specify the file extension.
> 
> ```
> <partial name="_DefaultThemePartial.cshtml" />
> ```

Ahh! I didn't know these are different! Thanks a lot, your solution works much better without extra code.

**Comment by rjgotten** [comment]
> if you want to use a relative path, make sure you specify the file extension.

Bad idea in the general sense.
Performing a lookup by filename is iirc a fallback which happens only after all lookups via the normal view location method have failed. In other words: relying on file names for relative view lookups would probably prevent those lookups from working in combination with other application features added via view location expanders, such as localized views - e.g. `Example.en-US.cshtml`.
