### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.1.22 has broken dependencies on NuGet

### ISSUE THREAD

**Issue by rjgotten** [dotnet/aspnetcore#39020]
### The problem
The package `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`, version 3.1.22 in NuGet refers to unexisting packages:
- `Microsoft.AspNetCore.Mvc.Razor.Extensions`, version 3.1.22
- `Microsoft.CodeAnalysis.Razor`, version 3.1.22

### To Reproduce

- [Inspect the package](https://nuget.info/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation/3.1.22)
- Follow the listed non-existant dependencies
- This takes you to the 6.0.1 versions, as the 3.1.22 versions do not exist.

Note that an attempt to install the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`, version 3.1.22 package to any project using .NET Core 3.1 will result in a failing build, because of the bad 6.0.1 CodeAnalysis dependency.

### Note

This is a repeat of the same problem with version 3.1.21 reported last month in #38172.
Fix your release process, please. This is shameful.

At the very least incorporate a _correct_ upper bound on the package dependencies, so they _cannot_ automatically resolve versions that go with a later framework. Right now, the dependencies only specify a lower bound:
![image](https://user-images.githubusercontent.com/442808/146029920-0b1df96b-cbcc-4f56-867e-1ffce68da9c2.png)

Under no circumstance whatsoever is it acceptable that when faced with a non-existing version, you allow NuGet to skip into the latest version. Actually; someone should look into that NuGet behavior. It giving you the 'next version up' might be a rational choice - still a _stupid_ choice, if that's a new major version which breaks semantic versioning, but rational. However, what NuGet appears to be doing when the requested dependency doesn't exist is just flat out tossing up its arms and going: "Oh whatever; latest version it is!"

**Comment by TanayParikh** [comment]
cc/ @dotnet/aspnet-build, seems to be related to the `aspnetcore-tooling` -> `razor-tooling` migration.

**Comment by TanayParikh** [comment]
Hello @rjgotten, thanks for pointing this out. The packages should now be available, could you please give it a try?

**Comment by dougbu** [comment]
Sounds like the release process had a hiccup today but everything is now sorted. If you agree @rjgotten, please close this issue.

**Comment by rjgotten** [comment]
I've heard back from a co-worker who has verified that builds are succeeding again.
So; guess it's ok again for now.

Hopefully we won't be looking at a repeat again next month.
