### ISSUE TITLE
Update Release Manifests with New Packages

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#39027]
`Microsoft.AspNetCore.Mvc.Razor.Extensions` and `Microsoft.CodeAnalysis.Razor` are not being automatically published as part of our release process. 

We've had customer reports on release days for this issue:
- https://github.com/dotnet/aspnetcore/issues/39020
- https://github.com/dotnet/aspnetcore/issues/38172

**Comment by dougbu** [comment]
@wtgodbe who from the release or CQB teams should be assigned this bug❔

**Comment by wtgodbe** [comment]
@rbhanda

**Comment by wtgodbe** [comment]
@rbhanda has this been fixed? Seems like it has: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Razor/3.1.27

**Comment by rbhanda** [comment]
Have not heard any complaints so looks like this is resolved
