### ISSUE TITLE
Using Custom ILogger with ErrorBoundary produces exception = null

### ISSUE THREAD

**Issue by musamalou** [dotnet/aspnetcore#39039]
I have a blazor webassembly project with a custom ILogger that worked fine. However, after I used the new ErrorBoundary, the public void Log<TState> method of the ILogger is called with logLever = Error and a null exception. 

```razor
 <ErrorBoundary @ref ="errorBoundary">
        <ChildContent>
            @Body
        </ChildContent>
        <ErrorContent Context="ex">  
             <div class="alert alert-danger alert-dismissible fade show m-3" role="alert" style="display:flex; z-index:99999;">
                 <div style="justify-content:flex-start;flex:10;"> <strong>Error:</strong>@ex.Message  </div>
                 <div style="justify-content:flex-end;flex:1"><a href="@CurrentPath" class="reload"  style="float:right;cursor:pointer;" >Reload <span class="material-icons" title="refresh"> refresh </span> </a> </div>                        
            </div>           
        </ErrorContent>
    </ErrorBoundary>
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by musamalou** [comment]
To reproduce the issue follow these steps:
                 1. Place a break point in the log method of the CustomLogger.cs.
                 2. Run the project
                 3. Click on Counter/Error menu
                 4. Clikc on the 'Click Me' button to throw an exception
                 6. Check the value of the exception.
                 7. Run the project without enclosing @Body in ErrorBoundary

                **The Result is: Without an error boundary, you should get the exception in log method of CustomLogger.cs that was thrown from the counter.razor** 

                8. Now enclose the @Body in ErrorBoundary and build and run the project again

                 The Result is: With the body enclose in the ErrorBoundary tag, the error is thrown, but the exception in the log method of CustomLogger.cs is null
[BlazorAppWithILoggerErrorBoundary.zip](https://github.com/dotnet/aspnetcore/files/7736579/BlazorAppWithILoggerErrorBoundary.zip)

**Comment by pranavkm** [comment]
Looks like a bug: https://github.com/dotnet/aspnetcore/pull/39202
