### ISSUE TITLE
Consider producing fewer log files per Helix work item (10k+ in some instances)

### ISSUE THREAD

**Issue by MattGal** [dotnet/aspnetcore#39038]
The test work item "Microsoft.AspNetCore.Server.Kestrel.Core.Tests" currently uploads something like 10.6k text files per execution.  I noticed this during other investigations, but if possible it would be much simpler for folks reading logs, downloading result files, and other tasks if this could be reduced either via concatenation or zipping.

Example:
```
Files
| where WorkItemId == 843889212
```

**Comment by sebastienros** [comment]
Can you confirm it's an issue with the "number" of files? We are curious about the issue that it triggers.

**Comment by MattGal** [comment]
> Can you confirm it's an issue with the "number" of files? We are curious about the issue that it triggers.

First I want to clarify; if you feel that it's important to store off 10,000 files for a single work item for data-driven tests, you are absolutely fine keep doing this.  In fact, aside from causing a bunch of extra compute and spurious DB entries, this problem barely would be noticed if not for the queue depth alerts it spurred.  It also does make the logs (since we have fairly verbose Azure storage client library logging on) enormous.

The linked issue goes into the synergy of irritation this causes (leading to there being 12,000 "jobs" for this job in our Kusto db)  but **TL;DR**" It's triggering a limitation in the service where if all the work items finish in a job, every event thereafter to come in (one per file) for that job triggers the "end of job" code.  Yes, we should and will hopefully eventually fix this, but it's trickier than it sounds to do.

**Comment by dougbu** [comment]
Preserving for posterity the Kusto data as of today for a recent rolling build of 'main'. The top 10 Helix work items for file upload count were

WorkItemFriendlyName | count
-- | --
Microsoft.AspNetCore.Server.Kestrel.Core.Tests--net7.0 | 6187
InMemory.FunctionalTests--net7.0 | 3756
Microsoft.AspNetCore.SignalR.Client.FunctionalTests--net7.0 | 2402
Interop.FunctionalTests--net7.0 | 908
Microsoft.AspNetCore.SignalR.Tests--net7.0 | 783
Microsoft.AspNetCore.Http.Extensions.Tests--net7.0 | 548
Microsoft.AspNetCore.SignalR.Client.Tests--net7.0 | 493
Microsoft.AspNetCore.Http.Connections.Tests--net7.0 | 435
ProjectTemplates.Tests--net7.0 | 274
Sockets.FunctionalTests--net7.0 | 237

Thanks again to @ulisesh

**Comment by dougbu** [comment]
If I'm reading the above correctly, our worst offenders all rely on `LoggedTestBase`. Those test classes create per-test and (for `[Theory]`s) per-testcase log files. Focusing there may be enough though covering other uses of the lower-level `AssemblyTestLog` class would be even better.

**Comment by dougbu** [comment]
Fixed in main now. @MattGal @dotnet/aspnet-build any thoughts on taking this to release/5.0 and release/6.0 (where we also use Helix)❔
