### ISSUE TITLE
Hosted services start later with minimal API

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#39037]
I've found another problem with the new minimal API introduced in .NET 6 which I haven't seen announced. Hosting services appear to start later than they did before. Here's a sample application which demonstrates the problem:

[WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/7715122/WebApplication1.zip)

<details>
 <summary>Program.cs</summary>

```C#
using Microsoft.AspNetCore.Mvc;

Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(builder => {
        builder.ConfigureServices((context, services) => services.AddServices())
            .Configure(app => app.UseMiddleware());
    })
    .Build()
    .Run();

//var builder = WebApplication.CreateBuilder(args);

//// Add services to the container.
//builder.Services.AddServices();

//var app = builder.Build();

//app.UseMiddleware();

//app.Run();

public static class ServiceCollectionExtensions {
    public static IServiceCollection AddServices(this IServiceCollection services) {
        services.AddOptions<MvcOptions>().Configure(options => {

        });
        services.AddHostedService<TestHostedService>();
        services.AddControllers();

        return services;
    }
}

public static class ApplicationBuilderExtensions {
    public static IApplicationBuilder UseMiddleware(this IApplicationBuilder app) {
        return app.UseRouting()
            .UseEndpoints(endpoints => endpoints.MapControllers());
    }
}

public class TestHostedService : IHostedService {
    public Task StartAsync(CancellationToken cancellationToken) {
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}


```

</details>

If you put a breakpoint between the `Configure` callback (line 25) and the hosted service `StartAsync` method (line 43) and run the application you will see that the `StartAsync` method runs first. However if you comment out the old startup code (lines 3 to 9) and un-comment the new code (lines 11 to 20) you will notice the breakpoints are hit the other way around. This causes a problem to me as I need the hosted service to run first. Is there a way to fix this using the minimal API?

**Comment by halter73** [comment]
Thanks for the report @nfplee.

The generic host could run the `Configure(IApplicationBuilder)` method or callback as part of `StartAsync()` after other hosted services completed. Unfortunately, it's not possible to delay the execution of code referencing the `WebApplication`. As soon as the `WebApplication` is built, code can start adding middleware.

We could consider starting hosted services as part of `WebApplicationBuilder.Build()` (excluding the `GenericWebHostService`), but that would force developers into sync-over-async. And while this usually only happens once in a process's lifetime instead of more often like per request, it feels bad to force that on people.

> This causes a problem to me as I need the hosted service to run first.

I'm not questioning the validity of this, but I'm curious why the hosted service needs to run first.

> Is there a way to fix this using the minimal API?

You could set up all your middleware using an `IStartupFilter`, but that doesn't feel very ergonomic. I'd probably go back to the generic host at that point. This issue has me wondering if we shouldn't run `IStartupFilter`s during `Build()` since those aren't async and they also normally run before `Configure(IApplicationBuilder)` since they return the thing that calls it.

**Comment by nfplee** [comment]
Thanks for your response @halter73. I need the hosted services to run before the application starts as it allows my database migrations to be applied. To be abit more specific I have the following in my startup:

```cs
services.AddOptions<MvcOptions>().Configure<ILocalizationManager>((options, localizationManager) => {
	options.Conventions.Insert(0, new LocaleRouteConvention(localizationManager));
});
```

The localization manager retrieves the locales from the database and adds custom routes for each locale. The problem though is that when I first run my application it creates the locales table (via the migrator hosted service), or atleast it did do before upgrading to use the minimal API. Now it throws an error as it tries to retrieve the locales before the migration to create the table has been applied.

**Comment by nul800sebastiaan** [comment]
Not sure what the protocol is for getting some attention on this one but I will just note here that Umbraco is affected by this problem as well. As it stands we can't move to minimal hosting model because of this timing problem. Hope it gets some attention for .NET 8! 🤞

**Comment by mitchdenny** [comment]
I have been thinking about this scenario a bit more. If we are talking about database migrations or database reads that have to occur before you can start doing things like mapping routes, it seems like it is something that has to occur in a controlled fashion with the application startup.

Simplisticly - why wouldn't the following work:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSingleton<DatabaseMigrator>();

var app = builder.Build();

var databaseMigrator = app.Services.GetRequiredService<DatabaseMigrator>();
await databaseMigrator.DoMigrationStuffAsync();

app.MapGet("/", () => "Hello, world");

app.Run();

public class DatabaseMigrator
{
    public async Task DoMigrationStuffAsync()
    {

    }
}
```

In the example above the database migration logic runs before you map any routes. Is that not what you are trying to achieve?

**Comment by nfplee** [comment]
Thanks @mitchdenny I'll give this a check on Monday. I thought I'd respond before the bot automatically tries to close this issue.

**Comment by mitchdenny** [comment]
How did you go @nfplee?

**Comment by nfplee** [comment]
Hi @mitchdenny, I've just got around to testing this and your suggestion does work. Thanks again.

However, I did have to convert my hosted services to implement a custom interface and then run them before mapping any routes, like so:

```cs
var preRunServices = app.Services.GetServices<IPreRunService>();

foreach (var service in preRunServices) {
    await service.ExecuteAsync();
}
```

This allowed me to keep my application more modular.

I suppose this issue could be closed now as I guess an `IHostedService` no longer blocks the application from starting up. I'll leave it open for someone on the team to close, unless they think this scenario should be better supported in the framework.

**Comment by mitchdenny** [comment]
OK great. I'm going to go ahead and close this. Whilst this is a change from the previous hosting model I think that this represents the best approach for folks that need to perf actions synchronously before the application actually starts.

I always thought that folks using hosted services to race to do things before the app starts vs. just invoking the specific operation you want to do was unnecessary complexity.
