### ISSUE TITLE
Use string interpolation in .NET 6 minimal API routes

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/aspnetcore#39054]
Minimal API routes are mapped using strings, but it looks like there is no way to specify a "base" part of the route and substitute this in route strings with interpolation when the route contains a parameter. This means parts of the route are repeated for every mapped handler. Is it possible to do the following?

```
private const string BASE_RESOURCE = "my-resource";

app.MapGet($"/api/{BASE_RESOURCE}/{id}");
```
At the moment this obviously does not compile.

Thanks

### Is your feature request related to a problem? Please describe.
I am trying to do not repeat common parts of a route string but cannot do this using interpolation for routes that have 1 or more parameters which are also in braces {}.

### Describe the solution you'd like
A way to avoid repeating common parts of the route for every mapping.

**Comment by slang25** [comment]
You should be able to escape the braces by doubling them like this:
```csharp
app.MapGet($"/api/{BASE_RESOURCE}/{{id}}")
```

**Comment by sjbthfc2** [comment]
Hi @slang25, thank you so much, that works perfectly.
