### ISSUE TITLE
Blazor WebbAssembly exception when calling javascript function?

### ISSUE THREAD

**Issue by MuscleBy** [dotnet/aspnetcore#39056]
I have a C# function that is invoking a Javascript function, this is the C# function:

`await _jsRuntime.InvokeVoidAsync("setMediaUsingStreaming", type, dotnetImageStream);`

And this is the Javascript function:

```
   async function setMediaUsingStreaming(fileType, fileStream) {
            try {

                const arrayBuffer = await fileStream.arrayBuffer();
                const blob = new Blob([arrayBuffer]);
                const url = URL.createObjectURL(blob);

                var newHTMLElement;
                var fileHTMLElement = document.getElementById('fileDisplay');

                if (fileType == "image") {
                    newHTMLElement = document.createElement('img');
                }
                else {
                    newHTMLElement = document.createElement('video');
                    var attribute = document.createAttribute('controls');
                    newHTMLElement.setAttributeNode(attribute);
                }

                fileHTMLElement.appendChild(newHTMLElement);
                newHTMLElement.src = url;

            } catch (Exception)
            {
                console.log(Exception)
            }
   }
``` 

When the C# function is invoking the Javascript function I receive this error :

> blazor.webassembly.js:1 Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Cannot set properties of null (setting 'src') TypeError: Cannot set properties of null (setting 'src')

The weird thing is that I receive this error when I run the app in publish mode (withouth a debugger) but it works perfectly in debug mode. The catch from the javascript function is not hit when I receive this error, it seems that is the C# method that is throwing it.

I know what the error is saying, that the url variable is null, but I don't understand why is null, and why it works on debug mode.

Repro steps: add and call the javascript function in any project.

Do you have any ideas ?

**Comment by TanayParikh** [comment]
Hello @MuscleBy, thanks for contacting us. I tried out the code snippet you provided however the issue didn't reproduce. Could you please provide a minimal, public github repro project. Please ensure any unnecessary code to the repro is trimmed, ex only keep code for `img` or `video` above.

**Comment by MuscleBy** [comment]
I tried to reproduce this issue on a clean project and it did reproduce. I also did not encountered the issue after clean rebuild and restart. I will close this issue. Thanks.
