### ISSUE TITLE
Identity Specification Tests Issues

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/aspnetcore#39050]
## Failing Test(s)
For target `netcoreapp3.1` any test checking logging fails due to the removal of logging user IDs in [this commit](
https://github.com/dotnet/aspnetcore/commit/71fef28e47db385efee14f80135391cf9ab516b6#diff-510a59e10134ab112b6061fbd305108dfb7ebf37210bb15edfebb503b61d8b83).

These are the tests that fail:

-    IdentitySpecificationTestBase.AddUserToRoleFailsIfAlreadyInRole
-   IdentitySpecificationTestBase.CanGetRolesForUser
-    IdentitySpecificationTestBase.CanQueryableRoles
-    IdentitySpecificationTestBase.RemoveUserNotInRoleFails
-    UserManagerSpecificationTestBase.AddDupeLoginFails
-    UserManagerSpecificationTestBase.AddPasswordFailsIfAlreadyHave
-    UserManagerSpecificationTestBase.CanChainUserValidators
-    UserManagerSpecificationTestBase.CanEnableLockoutManuallyAndLockout
-    UserManagerSpecificationTestBase.CanFindUsersViaUserQuerable
-    UserManagerSpecificationTestBase.CanGenerateAndVerifyUserTokenWithStaticTokenProvider
-    UserManagerSpecificationTestBase.CanUpdatePasswordUsingHasher
-    UserManagerSpecificationTestBase.CanVerifyPhoneNumber
-    UserManagerSpecificationTestBase.ChangeEmailFailsWithEmail
-    UserManagerSpecificationTestBase.ChangeEmailFailsWithWrongToken
-    UserManagerSpecificationTestBase.ChangePasswordFallsIfPasswordWrong
-    UserManagerSpecificationTestBase.ChangePhoneNumberFailsWithWrongToken
-    UserManagerSpecificationTestBase.CheckSetUserNameValidatesUser
-    UserManagerSpecificationTestBase.ConfirmEmailWithStaticTokenFailsWithWrongToken
-    UserManagerSpecificationTestBase.ConfirmTokenFailsAfterPasswordChange
-    UserManagerSpecificationTestBase.EmailFactorFailsAfterSecurityStampChangeTest
-    UserManagerSpecificationTestBase.LockoutFailsIfNotEnabled
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockAddPassword
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockChangePassword
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockCreateUser
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockResetPasswordWithStaticTokenProvider
-    UserManagerSpecificationTestBase.PhoneFactorFailsAfterSecurityStampChangeTest
-    UserManagerSpecificationTestBase.ResetPasswordWithStaticTokenProviderFailsWithWrongToken
-    UserManagerSpecificationTestBase.SingleFailureLockout
-    UserManagerSpecificationTestBase.TwoFailureLockout
-    UserManagerSpecificationTestBase.UserValidatorCanBlockCreate
-    UserManagerSpecificationTestBase.UserValidatorCanBlockUpdate
-    UserManagerSpecificationTestBase.VerifyTokenFromWrongTokenProviderFails
-    UserManagerSpecificationTestBase.VerifyWithWrongSmsTokenFails

## Error Message

Example: Assert.Contains() Failure
Not found: User d27a6851-ffac-40e6-82ef-21bae2332e2d is already in role addUserDupeTest968bcd82-58e2-429d-a40e-c45096ac09d0.
In value:  List<String> ["User is already in role addUserDupeTest968bcd82-58"...]

## Additional Test Issues

`CanQueryableRoles` in `IdentitySpecificationTestBase` is not virtual so for some `IQueryable` implementations (Comsos) that don't implement all expressions in the base test, I can't override it to adjust the test. In contrast `CanFindUsersViaUserQuerable` on `UserManagerSpecificationTestBase` is virtual and I can work around this issue via an override.

~~`CanGetRolesForUser` in `IdentitySpecificationTestBase` is also failing. Issue seems to be that `UserManager` will add the role to the user in normalized form, but the test retrieves the `RoleId` un-normalized for the Assert comparison:~~
```cs
removed```

Thanks!

**Comment by sebastienros** [comment]
Looking at https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Identity/Specification.Tests/src/IdentitySpecificationTestBase.cs#L510 it seems that the tests should have failed.

**Comment by AndrewTriesToCode** [comment]
Thanks for taking a look. When you say should have failed do you mean it is intended to be a test that fails or am I misunderstanding?

**Comment by HaoK** [comment]
Yeah this is a bit of a headache since its going to be expected that older versions won't pass against the newer specification tests, have you tried running against the 3.1 version of the specification tests?

**Comment by AndrewTriesToCode** [comment]
Sorry I didn't specify clearly, but the tests works for `net5.0` and `net6.0`, the issue is for `netcoreapp3.1` and I tried referencing both 
`<PackageReference Include="Microsoft.AspNetCore.Identity.Specification.Tests" Version="3.1.0" />`
and
`<PackageReference Include="Microsoft.AspNetCore.Identity.Specification.Tests" Version="3.1.22" /> but it seems the changes to the tests for 'net5.0' weren't backported.

Also please note the other items I mentioned at the bottom of the issue.

I wanted to raise this to your awareness but I understand its not high priority. Would a PR with fixes be well received?

**Comment by HaoK** [comment]
Sure if you have a PR that would fix things for you that certainly would help.

The specification tests only will pass against the matching version of the identity packages, if you are running newer identity code that doesn't have the log id, they are going to fail, what are the referenced versions for all the relevant packages for your test run

**Comment by AndrewTriesToCode** [comment]
I'll work on that PR. I understand that for the 3.1 test fixes I'd need to submit it to merge against that release branch.

Here is the csproj file in my test project where I'm running into this.

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net5.0;netcoreapp3.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <UserSecretsId>5c84a5c6-53a6-4c34-839b-9a24c1e3beb6</UserSecretsId>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.23.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0"/>
        <PackageReference Include="xunit" Version="2.4.1"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="3.1.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
    <Choose>
        <When Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
            <ItemGroup>
                <PackageReference Include="Microsoft.AspNetCore.Identity.Specification.Tests" Version="3.1.22" />
                <FrameworkReference Include="Microsoft.AspNetCore.App" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <PackageReference Include="Microsoft.AspNetCore.Identity.Specification.Tests" Version="5.0.13" />
            </ItemGroup>
        </Otherwise>
    </Choose>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Finbuckle.CosmosIdentity\Finbuckle.CosmosIdentity.csproj"/>
    </ItemGroup>
</Project>
```

**Comment by HaoK** [comment]
So this was reported to us before, https://github.com/dotnet/aspnetcore/issues/27873 which is how we noticed that we accidentally stopped shipping this specification package for 5.0, but just to be clear:

Are you expecting to mix and match versions?

> If I use Microsoft.Extensions.Identity.Stores 3.1.10 and Microsoft.AspNetCore.Identity.Specification.Tests 3.1.10 and the test project target framework is netcoreapp3.1, it works, tests don't failed.

You can't use any of the identity 5.0+ bits and run the older specification tests and expect them to work.

You should be running against the 5.0+ specification tests and 5.0 identity bits, how is your CosmosIdentity referencing identity

**Comment by AndrewTriesToCode** [comment]
@HaoK You nailed the issue -- my library under test targeted `netstandard2.0` but referenced net5.0+ Identity stores and tests. That issue is resolved when I change the library to reference 3.1 versions of those packages. Regarding the other items I mentioned, shown below, I'll submit a PR and reference this issue. Thanks.

> ## Additional Test Issues
> `CanQueryableRoles` in `IdentitySpecificationTestBase` is not virtual so for some `IQueryable` implementations (Comsos) that don't implement all expressions in the base test, I can't override it to adjust the test. In contrast `CanFindUsersViaUserQuerable` on `UserManagerSpecificationTestBase` is virtual and I can work around this issue via an override.
> 
> `CanGetRolesForUser` in `IdentitySpecificationTestBase` is also failing. Issue seems to be that `UserManager` will add the role to the user in normalized form, but the test retrieves the `RoleId` un-normalized for the Assert comparison:
> 
> ```cs
> // Here rs came from the UserManager and was originally normalized when added to the user, but expected role
> // comes from the role manager and is not normalized. Assert fails.
> string expectedRoleName = await roleManager.GetRoleNameAsync(role1);
> Assert.Contains<string>((IEnumerable<string>) rs, (Predicate<string>) (role => role == expectedRoleName));
> ```
> 
> Thanks!

**Comment by AndrewTriesToCode** [comment]
I submitted a PR for typoes and the Queryable test issues. Thanks for your help.

I also struck out the issue I mentioned above for `CanGetRolesForUser` since it was an implementation difference between the EFCore implementation and mine. I ended up copying EFCore's behavior in that regard.

**Comment by HaoK** [comment]
Thanks again for finding and addressing this @AndrewTriesToCode
