### ISSUE TITLE
RenderTreeDiffBuilder – components after components with @key are often recreated

### ISSUE THREAD

**Issue by jirikanda** [dotnet/aspnetcore#39053]
## Observation
```
<div>
    
    @for (int i = 0; i < count; i++)
    {
        <SomeComponent @key="i" /> @* I understand setting the key to the "i" which is useless. I just need to use a key. *@
    }

    <AnotherComponent />
</div>
```
* Everytime when the count field is decreased, the AnotherComponent is removed, and new instance is created. As a result, it loses its state.
## Repro steps
* https://github.com/jirikanda/Blazor-KeyIssueRepro
* Run the application in debug mode (F5). There is a breakpoint in the AnotherComponent which will be hit, continue (F5).
* Click -1 button in the browser page.
* Breakpoint in the AnotherComponent will be hit as a proof of creating a new instance.

## Analysis
I analyzed of the stack trace and RenderTreeDiffBuilder.AppendDiffEntriesForRange to understand why the component, which visualy never disappears from the UI, is created as a new instance.
The path through the method is described on this picture (red bubbles are “thoughts”, blue are “facts”).
![image](https://user-images.githubusercontent.com/5111719/146155631-34c44431-786c-4f51-b4a2-9e70e8fa9db6.png)
![image](https://user-images.githubusercontent.com/5111719/146156271-1b4f9d91-a867-4367-9cc1-1c8cbd78fb5c.png)

## Suggestion
The main idea of this issue is to consider the situation. We have a frame with a key in old tree which is not in the new tree. I consider it is clear the frame in the old tree must be removed. Should it be preferred to remove the frame from the old tree instead of inserting a frame from the new tree?

### Additional context
.NET 6

**Comment by MariovanZeist** [comment]
Although this issue could be mitigated by moving ``AnotherComponent`` outside the div, or adding an additional div around ``AnotherComponent``.  I would classify that more as a workaround, and not a fix.

This seems like either a bug or an oversight in the original diff algorithm.

**Comment by jirikanda** [comment]
Hi Mario,

thank you very much for your answer. Yes, I agree, we found a workaround in a subtle component re-arrangement.
Luckily, we were able to apply the same workaround in the business application.

We spent some time to explain you this issue. I hope, together, we are going to make the Blazor product better!

**Comment by SteveSandersonMS** [comment]
Resolved in https://github.com/dotnet/aspnetcore/pull/40261
