### ISSUE TITLE
Razor views generated during a BeforeBuild target are not compiled into the assembly

### ISSUE THREAD

**Issue by jpoehls** [dotnet/aspnetcore#39068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are upgrading a project from .NET 3.1 to .NET 6 and found this problem.

We have a PreBuild target in our `.csproj` file that generates `.cshtml` Razor views. After upgrading to .NET 6, these generated `.cshtml` files are no longer being embedded in our assembly with our other views.

It appears that there is a Razor related build step running prior to `BeforeBuild` and because our `.cshtml` file does not exist at that point in time, it is not being included in the compilation.

How can we workaround this? We need to generate views as a pre-build step and have them included in the full Razor compilation process.

Here is our current `.csproj` target and a screenshot that illustrates the issue.

```xml
<Target Name="PreBuild" BeforeTargets="BeforeBuild">
	<Exec Command="generate-view.cmd" />
</Target>
```

![Screen Shot 2021-12-15 at 4 05 54 PM](https://user-images.githubusercontent.com/72149/146272878-6a5c5ce8-e68d-4e19-a746-30d4492eceb4.png)

### Expected Behavior

`.cshtml` files generated by a `<Target BeforeTargets="BeforeBuild" />` should be included in the Razor compilation process.

### Steps To Reproduce

1. Clone https://github.com/jpoehls/GeneratedRazorViewRepro
2. Run `build.cmd`
3. Reflect the output assembly to confirm `Generated.cshtml` view is not embedded

### .NET Version

6.0.100

**Comment by pranavkm** [comment]
Could you try `BeforeTargets="ResolveRazorGenerateInputs"`? That's the target that calculates what items end up being compiled: https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets#L495-L513

**Comment by jpoehls** [comment]
@pranavkm: Thank you, that tip helped us find a solution. We used the `ResolveRazorGenerateInputs` target in combination with some `<Content Update="..." />`, `Include="..."`, and `Remove="..."` related to our generated files and have our project working now.
