### ISSUE TITLE
Model validation with Minimal API

### ISSUE THREAD

**Issue by asifshakir** [dotnet/aspnetcore#39063]
What would be the recommended method to perform model validations with Minimal API, considering that EF Core is being used so the entity models have data annotations.

Something which can be used in production.

**Comment by pranavkm** [comment]
For 6.0, there isn't a story out of the box. It's something we plan on addressing as part of .NET 7. That said, @DamianEdwards wrote a library around DataAnnotations that he's been successfully using in his app: https://github.com/DamianEdwards/MiniValidation. You could consider using that.

**Comment by asifshakir** [comment]
Ok. 

Yes, I have seen the library created by @DamianEdwards but it is still in prerelease so I assume he doesn't recommend it for production application right away.

I will revert to the traditional MVC approach for WebApi then and review Minimal API integration once .NET 7 is released for our apps.
