### ISSUE TITLE
Rename Microsoft.AspNetCore.Razor.Internal.Transport package in razor-compiler repo

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#39072]
The package contains pdbs transported from razor-compiler -> razor-tooling. There's a conflict in 6.0.2xx since it's also produced by dotnet/aspnetcore's 6.0 branch. Renaming the package like we did for other transport packages would be the easiest fix for this.

**Comment by dougbu** [comment]
👀
