### ISSUE TITLE
Is there a way to add metadata to all GET endpoints in ASP.NET Core?

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#39081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the following statement, the `AsBffApiEndpoint()` adds an attribute to all endpoints. Then there is a middleware specifically looking for that attribute and if present will check for an antiforgery header to be present.

`endpoints.MapControllers().RequireAuthorization().AsBffApiEndpoint();`

I need to be able to bypass that check on all GET endpoints. Most importantly, this is third party library, hence I have no control over the implementation.

I have try many things without success. Last attempt was to add a middleware custom middleware `app.Use(...)` and if the attribute was present, then remove it. However that's not possible since the list of metadata is `readonly`. Then, my last hope is to find a way to add same attribute -to all GET- with a flag `false` which ignores the check. In other words, all `AsBffApiEndpoint()` does is decorate an endpoint with `[BffApi]` attribute. This attribute ignores antiforery headers if use like this `[BffApi(false)]`. I know the solution is hacky because I will end up with something like this.

    [BffApi]
    [BffApi(false)]
    //endpoint definition here

The good news is they get the endpoint metadata ordered `endpoint.Metadata.GetOrderedMetadata<BffApiAttribute>()`. Meaning as long as `[BffApi(false)]` takes priority in the list I should be good.

### Exceptions (if any)

None

### .NET Version

6.0.101

**Comment by pranavkm** [comment]
You could create a `RemoveBff(TBuilder builder) where TBuilder : IEndpointConventionBuilder` and operate on `EndpointBuilder.Metadata` which is mutable.

**Comment by ylr-research** [comment]
Thanks for the answer @pranavkm. I tried the following and it didn't work. It says System.InvalidOperationException: 'Sequence contains no matching element' on line for getAttribute

```
  public static TBuilder AsBffApiEndpointBypassAntiforgeryOnGET<TBuilder>(this TBuilder builder, string routePrefix) where TBuilder : IEndpointConventionBuilder
  {
      builder.Add(endpointBuilder =>
      {
          var getAttribute = endpointBuilder.Metadata.First(m => m.GetType() == typeof(HttpGetAttribute)) as HttpGetAttribute;
          var routeAttribute = endpointBuilder.Metadata.First(m => m.GetType() == typeof(RouteAttribute)) as RouteAttribute;
          if (getAttribute != null && routeAttribute != null && routeAttribute.Template.StartsWith(routePrefix))
          {
              endpointBuilder.Metadata.Add(new BffApiAttribute(false));
          }
          else
          {
              endpointBuilder.Metadata.Add(new BffApiAttribute(true));
          }
      });

      return builder;
  }
```

**Comment by brunolins16** [comment]
@ylr-research Besides the fact that your action is called `GetSheetLayout `based on your screenshot it is configured with `HttpPost` instead of `HttpGet` and the exception is an expected outcome since you are using `First` instead of `FirstOrDefault`.

**Comment by ylr-research** [comment]
@brunolins16 thanks for pointing that out. `FirstOrDefault()` indeed solved my problem. I'll add the solution below and close it.
