### ISSUE TITLE
Blazor WASM, ongoing timers cause a global exception when browser loses focus for some time

### ISSUE THREAD

**Issue by markdchurchill** [dotnet/aspnetcore#39089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Blazor WASM, ongoing timers with async work when browser loses focus (and possible stops executing js) for some time cause a global exception on return.

Various Microsoft.AspNetCore.*: 6.0.0

```
Tried to resynchronise rentrantly
(anonymous)	@	blazor.webassembly.js:1
put_char	@	dotnet.6.0.0.knfbj4uiz6.js:1
write	@	dotnet.6.0.0.knfbj4uiz6.js:1
write	@	dotnet.6.0.0.knfbj4uiz6.js:1
doWritev	@	dotnet.6.0.0.knfbj4uiz6.js:1
_fd_write	@	dotnet.6.0.0.knfbj4uiz6.js:1
$func1705	@	00945abe:0x4217d
$func8844	@	00945abe:0x1ca1cd
$func2588	@	00945abe:0x805d7
$func2307	@	00945abe:0x689a7
$func7015	@	00945abe:0x17bac4
$func6830	@	00945abe:0x172bc5
$func3524	@	00945abe:0xb47cc
$func675	@	00945abe:0x16602
$func6537	@	00945abe:0x166a21
$Hb	@	00945abe:0x176082
(anonymous)	@	dotnet.6.0.0.knfbj4uiz6.js:1
pump_message	@	dotnet.6.0.0.knfbj4uiz6.js:1
setTimeout (async)		
_schedule_background_exec	@	dotnet.6.0.0.knfbj4uiz6.js:1
$func1289	@	00945abe:0x2f8dc
$func6721	@	00945abe:0x16c00e
$func2588	@	00945abe:0x806c2
$func2307	@	00945abe:0x689a7
$func7015	@	00945abe:0x17bac4
$func6830	@	00945abe:0x172bc5
$func3524	@	00945abe:0xb47cc
$func675	@	00945abe:0x16602
$func6537	@	00945abe:0x166a21
$Hb	@	00945abe:0x176082
(anonymous)	@	dotnet.6.0.0.knfbj4uiz6.js:1
pump_message	@	dotnet.6.0.0.knfbj4uiz6.js:1
setTimeout (async)
```

Last setTimeout...setTimeout stack repeats many times.

I can work on a cleaner reproduction and update this if needed. My suspicion is that a several-minute timer that kicks of some async work is causing this. It may well be my own stupid fault - but this is a Friday, and the first time I've seen this in my local browser, rather than on a test device.

Doesn't stop the timer from continuing to fire (and then succeed at some web calls). Just the scary banner appears.

### Exceptions (if any)

Error is logged in browser console, blazor unhandled banner appears and scares people.

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

**Comment by pranavkm** [comment]
Could you share a minimal app that reproduces the issue? I tried a stock Blazor WASM app, configured [background throttling](https://docs.google.com/document/d/11FhKHRcABGS4SWPFGwoL6g0ALMqrFKapCk5ZTKKupEk/view#heading=h.dhi2xkb0jjmb) to trigger quickly and focused away. I can see the throttling take effect, but the WASM app functions without any issues.

**Comment by markdchurchill** [comment]
This likely does not need further investigation as I could not replicate with a minimal app. I suspect this is an issue in one of the packages I am using for local storage or indexeddb.
