### ISSUE TITLE
AddStackExchangeRedisCache & ForceReconnect for Azure App Service Linux containers

### ISSUE THREAD

**Issue by ShaneCourtrille** [dotnet/aspnetcore#39082]
As per https://github.com/StackExchange/StackExchange.Redis/issues/1848 there is a problem with accessing Redis after nodes are restarted (In our case we're seeing this once a month when our Azure Redis instance is being updated).  The recommended fix of modifying container settings isn't allowed on Azure App Service which leaves us with the recommendation to implement the ForceReconnect pattern.  

Is this even possible when depending on the IDistributedCache?

**Comment by jco-d** [comment]
Would just like to add our voice to this.

We have just implemented the IDistributedCache and are experiencing exactly the same problems while using the Azure Cache for Redis service.

Although the TCP settings change provides some relief, it also impacts other network interactions and quite frankly, is a band-aid fix.

We have been in discussions with the Cache for Redis product team, and their clear guidance is that the ForceReconnect should be implemented - to the point of suggesting we abandon the use of the IDistributedCache.

It would be wonderful if these two Microsoft teams could maybe coordinate and have this resolved, as quite frankly they do rather go hand in hand .. in a manner that could be considered "core" .. a distributed cache without something like Azure Cache for Reds service just doesn't make sense - it is also *very* clear what the fix needs to be (Microsoft even provides implementation examples of how to sort this out - https://github.com/Azure-Samples/azure-cache-redis-samples/tree/main/quickstart - so it would be great if Microsoft followed its own recommendations).

**Comment by adityamandaleeka** [comment]
@mgravell Can you please take a look at this?
