### ISSUE TITLE
Net.Maui Blazor not running on Android 7.1 Tablet 

### ISSUE THREAD

**Issue by whann0205** [dotnet/aspnetcore#39086]
### Description

The screen loading.... appears but nothing happens.
But...when i create a new project selecting net.maui app instead
of net.maui blazor the project runs just fine with Android 7.1 on
the same device.

### Steps to Reproduce

1. Create new Project and select net.maui blazor
2. Connect an Android 7.1 device mine here is a samsung tablet with lineage os 14.1
3. Simply start debugging or build the project and run it

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1

### Did you find any workaround?

Nope.

**Comment by Eilon** [comment]
Note to triage: This is potentially a bug on this line of code in this repo:

https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L181

Apparently this `catch` syntax is relatively new in JavaScript. Or maybe TypeScript should be handling that when it converts to JavaScript? Either way, it's something for this repo to consider.
