### ISSUE TITLE
[.NET 6.0 Blazor server] same sessionId for two browser connected on same Machine

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#39096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, In my blazor server app i use httpContext?.Session?.Id to identify each client

It works fine, unless if the client open two instance of chrome for example  on the webapp, the app return the same sessionId, which is a problem for me. if it will be on the same instance on different tab, i can totally understand.

But now, it prevent users to use two instance of the app in the same laptop.

Id i open an instance of chrome with mode incognito activated, he generate a new sessionid (which is what i want)

Can you explain me this behavior ?

to see the SessionId generated you can put a middleware

````
  app.UseRouting();

            app.UseSession();

            //middleware après session
            app.Use((httpContext, nextMiddleware) =>
            {
                string sessionID = httpContext?.Session?.Id;
                return nextMiddleware();
            });

            app.UseAuthentication();
            app.UseAuthorization();
````

thanks !

### Expected Behavior

Have a session Id different between each client which connect to my app (include two instance of browser on the same machine)

### .NET Version

6.0.100

**Comment by MariovanZeist** [comment]
using ``HTTPContext`` in a Blazor server app is not recommended. There is no one-on-one relationship between a ``HTTPContext`` and a ``SignalR`` connection. 

And the ``session.Id`` you are using should not be used to identify Blazor clients.

I would recommend using some ASP.NET Core authentication mechanism to authenticate the user, and use the resulting ``ClaimsPrincipal`` to identify the user.

See: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0&tabs=visual-studio#authenticationstateprovider-service

**Comment by Tratcher** [comment]
Two instances of chrome and two chrome tabs are the same thing, chrome shares cookies across all tabs and instances. Using incognito or a completely different browser (e.g. Edge) is the only way to open a separate session.

**Comment by julienGrd** [comment]
@MariovanZeist yes you are right but anyway it will bé cookie based do it dont solve my Problem of multi instance.
@Tratcher yes i forgot that... but it will bé a problèm for me because i want my app to bé multi instance. Can i rely on some other mechanism, like json web token stored in the session storage ? (Which is not share between instance right ?). Is it something useable through blazor server but also webassembly ? (M'y app work in thèse two mode).

Thanks for your help !

**Comment by Tratcher** [comment]
According to this [blog](https://blog.guya.net/2015/06/12/sharing-sessionstorage-between-tabs-for-secure-multi-tab-authentication/), session storage is not shared across tabs or instances.

**Comment by julienGrd** [comment]
@Tratcher yes its whats i see. so it will be perfect to have a jwt for example stored on this,  but i don't know how to deal with this kind of authentication, especially in blazor server side. I don't find any good ressources on how to perform that. 

Do you have have any ressources on this ?

thanks !

**Comment by Tratcher** [comment]
I don't. The blazor team will review this when they get back in January.

**Comment by pranavkm** [comment]
You should be able to configure the SignalR builder on the client to use a different kind of authentication. Here are the relevant sections in the documentation:

* https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-client-logging-blazor-server
* https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#bearer-token-authentication

**Comment by julienGrd** [comment]
@pranavkm thanks for the links it will be useful ! 

But because the signalr blazor server is not the same objects and method than the classic signalr connection i struggle to find where tu put the AccessTokenProvider
I try this

````
Blazor.start({
	configureSignalR: function (builder) {
		builder.configureLogging("information");
		builder.withUrl("/_blazor", options => {
			options.AccessTokenProvider = () => {
				// Get and return the access token.
				return "access_token";
			};
		});
	}
});

but it failed at startup with error message in chrome console
Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: 'WebSockets' is disabled by the client. ServerSentEvents failed: Error: 'ServerSentEvents' is disabled by the client. LongPolling failed: Error: 'LongPolling' is disabled by the client.
````
i try also this
````
Blazor.start({
    configureSignalR: function (builder) {
        builder.configureLogging("information");
        builder.AccessTokenProvider = () => {
            // Get and return the access token.
            console.log("retrieve acces_token");
            return "access_token";
        };;
    },
});
````
i don't have exception but the console don't show "retrieve acces_token" so i think its just ignored

can you guide me on how to implement this on blazor server ?
