### ISSUE TITLE
Blazor WASM publishing error. Streaming compilation failed. Falling back to ArrayBuffer instantiation. TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function blazor webassembly After update to .net 6.0.1 and Visual Studio 2022 17.0.4

### ISSUE THREAD

**Issue by arthastheking113** [dotnet/aspnetcore#39092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I got this error after update my Blazor WASM project to .net 6.0.1 and Visual Studio 2022 to 17.0.4. My project run normally in localhost. I used the BrotliDecode method to minimize the download size for my application.

The error happen when I deploy my project to Azure App Service, and the weird part is this error only appear in the Url without www. and only in Google Chrome. I tested it on Firefox, Opera, and Edge with and without www. and It worked fine. 

For Example: if you go to this link https://www.ygovietnam.com/ , it worked normal, but if you go to this link https://ygovietnam.com/ using Google Chrome on PC , it error :( 

I'm not sure this is only my problem or this is something wrong with the new update.

These are the following error I got from Google Chrome and without www.

Streaming compilation failed. Falling back to ArrayBuffer instantiation.  TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function

blazor.webassembly.js:1 TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
(anonymous) @ blazor.webassembly.js:1
createWasm @ dotnet.6.0.1.ynjylm5yl3.js:1
(anonymous) @ dotnet.6.0.1.ynjylm5yl3.js:1

blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js:1
    at async blazor.webassembly.js:1
    at async blazor.webassembly.js:1

Edited: updated my dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Update more information:

This error only specificly happen on Google Chrome on PC on URL not contain www.

My application works fine on Firefox, Edge, and Opera with and without www, it works fine in all mobile browsers.

I updated all nuget package to the newest version 6.0.1, but still getting this error on PC.

### Steps To Reproduce

I will love to share my project to add anyone who want to find the issue but not public for everyone to look at it.

### .NET Version

6.0.101

**Comment by Grizzlly** [comment]
Issue #39087 might be related to this update too.

**Comment by arthastheking113** [comment]
> Issue #39087 might be related to this update too.

I'm not sure because my error only happen in Google Chrome on PC with URL not contain www. , with www. URL, my application works fine.

**Comment by arthastheking113** [comment]
For anyone looking for answers. I contacted Azure App Service team and this is a known issue and .NET team already working on this. 

I resolve this by using this trick.

1/ Remove my Custom Domain without www. from Custom Domain in Azure App Service.

2/ Remove A record and TXT asuid on Godaddy from the Records section.

3/ Add forward domain to www.yourdomain.com

4/ Wait an hour for that forward to be completed.

5/ Remove that Forward from Godaddy.

6/ Remove A record created automatically by Godaddy for forwarding to www.yourdomain.com.

7/ Add a new Custom Domain on Azure App Service using a domain without www..

8/ Delete old Private Key Certificate of the domain without www. if you forgot to delete.

9/ Create a new Private Key Certificate for for the domain without www you just created in the last step.

10/ Add that new Private Key Certificate to the domain without www.

11/ Wait a few seconds/minutes to get it effective.



This is just a way to Trick Google Chrome to regconize your url. Forwarding and remove forward is how I resolve this.

I will close this issue.
