### ISSUE TITLE
`invokeMethodAsync` 5x slower in Firefox compared to Edge or Chrome

### ISSUE THREAD

**Issue by amura11** [dotnet/aspnetcore#39102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a very similar issue to [this](https://github.com/dotnet/aspnetcore/issues/32689) issue but I'm only passing 2 strings and the issue is only seen in Firefox.

When calling a C# method from JavaScript using `invokeMethodAsync` there is a significant delay in Firefox. The code is fairly simple:

```
element.addEventListener("change", e => dotNetWrapper.invokeMethodAsync("OnTextChanged", stringValue1, stringValue2));
```

When this code is run in Firefox there is a noticeable delay but in Edge and Chrome there is no obvious delay. Looking at the performance from each browser Edge and Chrome take ~60ms while Firefox takes ~300ms to execute the same method with the same data. Below are screenshots of the captures.

**Firefox (95.0)**
![image](https://user-images.githubusercontent.com/1559993/146583404-a2460be5-0da1-4c17-b091-26e3771e21d7.png)

**Edge (96.0.1054.57)**
![image](https://user-images.githubusercontent.com/1559993/146583466-6d0a1734-1de4-49df-b4ff-8953c02b9828.png)

**Chrome (96.0.4664.110)**
![image](https://user-images.githubusercontent.com/1559993/146583726-6543ed7f-19d8-48a6-b6cf-f094e05dcc0b.png)

### Expected Behavior

Firefox would perform at least similar to Edge and Chrome in terms of speed

### Steps To Reproduce

**MyComponent.razor**

```
<input @ref="_inputReference" />
```

**MyComponent.razor.cs**

```
public partial class MyComponent : ComponentBase, IAsyncDisposable
{
	private bool _isJavascriptInitialized = false;
	private ElementReference _inputReference;

	protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		await base.OnAfterRenderAsync(firstRender);

		if (firstRender == true && _isJavascriptInitialized == false)
		{
			_isJavascriptInitialized = true;

			IJSInProcessObjectReference jsLibraryReference = await this.JsRuntime.InvokeAsync<IJSInProcessObjectReference>("import", "mycomponent.js");
			DotNetObjectReference<MyComponent> selfReference = DotNetObjectReference.Create(this);

			IJSObjectReference jsObjectReference = await jsLibraryReference.InvokeAsync<IJSObjectReference>("init", _inputReference, selfReference);
		}
	}

	[JSInvokable]
	public async void OnTextChanged(string value)
	{
		Console.WriteLine(value);
	}
}
```

**mycomponent.js**

```
export function init(element, dotNetWrapper) {
    element.addEventListener("change", e => dotNetWrapper.invokeMethodAsync("OnTextChanged", element.value));
}


### Exceptions (if any)

_No response_

### .NET Version

5.0.404

### Anything else?

**ASP .NET Core Version:** `5.0.0`
**Visual Studio 2019 Version:** `16.11.8`
**dotnet --info:**

```
.NET SDK (reflecting any global.json):
 Version:   5.0.404
 Commit:    72c68b830a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.404\

Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  5.0.404 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by TanayParikh** [comment]
Hello, thanks for reaching out. I see you're using .NET 5. .NET 6 was recently released with a wide variety of feature and performance improvements. Could you please upgrade your project and let us know if you're still seeing this issue?
