### ISSUE TITLE
asp-page tag helper converted all the URLs into the one page url  at runtime

### ISSUE THREAD

**Issue by Raja-Ashutosh** [dotnet/aspnetcore#39106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team,

I am using the feature folder in asp.net core 6.  and register all Route , for example:

```
 options.RootDirectory = "/Features";
options.Conventions.AddPageRouteModelConvention("/Pages/Home/Home", ReplacePageRoute("home"));
options.Conventions.AddPageRouteModelConvention("/Pages/Test/Test", ReplacePageRoute("test"));
```
added  in the layout 
```
<a asp-page="home">HomeTest</a>
    <a asp-page="test">Test-Test</a>
```

When i have launched url with localhost:5001/test or localhost:5001/home

both the links automatically converted to either test or home based on the url i hit. 

 

### Expected Behavior

Should be generate two different url

### Steps To Reproduce

launched url with localhost:5001/test or localhost:5001/home

both the links automatically converted to either test or home based on the url.

### .NET Version

3.1 and 6

**Comment by pranavkm** [comment]
My guess is that the values here need to be:

```
<a asp-page="Home/Home">HomeTest</a>
<a asp-page="Test/Test">Test-Test</a>
```

going by the conventions that are being configured. In the absence of this, the URL will resolve to a null / empty string. If that's not the issue, could you share a minimal app that reproduces the problem for us to investigate?

**Comment by Raja-Ashutosh** [comment]
@pranavkm , please try this repo : https://github.com/Raja-Ashutosh/Testing-Asp.netRoute.git

**Comment by pranavkm** [comment]
These need to use the page names (the same ones you use to set up the route conventions):

https://github.com/Raja-Ashutosh/Testing-Asp.netRoute/blob/master/Admin/Features/Shared/_Layout.cshtml#L14-L15

```razor
    <a asp-page="/Pages/Home/Home">HomeTest</a>
    <a asp-page="/Pages/Test/Test">Test-Test</a>
```

**Comment by Raja-Ashutosh** [comment]
@pranavkm , then in the url will expose the physical file map. What is the benift of route config? This issue wil onky happened if I used asp-page but its working fine with href

**Comment by pranavkm** [comment]
`asp-page` is used to resolve the url in the framework. It’ll map to the routes that you have configured to use.
