### ISSUE TITLE
[Blazor WASM] error boundary throw exception.

### ISSUE THREAD

**Issue by Bala-tec** [dotnet/aspnetcore#39109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the blazor server, error boundary UI content shows without exception. But error boundary throws an exception in the blazor web assembly.

![image](https://user-images.githubusercontent.com/93471823/146656727-90a2b2ba-3d7c-4145-b1a7-e8fb35e463e5.png)

Attached sample [here]( https://github.com/Bala-tec/ErrorBound-wasm)

### Expected Behavior

Expect error boundary UI content shows without exception in the wasm.

### Steps To Reproduce

Run the attached sample
Switch to the counter page. Increase the count more than two and an exception will throw.

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/93471823/146656751-415a512d-1c2e-40a2-8d81-5641109ba47c.png)

### .NET Version

6.0.100

**Comment by pranavkm** [comment]
The `ErrorBoundary` component logs exceptions to the console to make it easy to debug. You could derive from it to suppress this behavior by overriding: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Web/ErrorBoundary.cs#L22-L25.

**Comment by Bala-tec** [comment]
@pranavkm - thanks for the reply
Not able to override the OnErrorAsync method, MainLayout already inherits LayoutComponentBase. Any suggestion to use OnErrorAsync method in the MainLayout razor file?

![image](https://user-images.githubusercontent.com/93471823/146699593-c1549279-4f4d-4664-bd73-ae447a0c1e46.png)

**Comment by pranavkm** [comment]
@Bala-tec you'd create a separate `CustomErrorBoundary` component that derives from `ErrorBoundary` and use that in your layout component.
