### ISSUE TITLE
asp-page tag helper not behaving as described in online docs

### ISSUE THREAD

**Issue by jparnzen** [dotnet/aspnetcore#39107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `asp-page` tag helper isn't behaving as described in the online Razor Page docs at https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio#razor-pages (c.f. bottom of that section of the page).

In particular, for index razor pages in subfolders under Pages (e.g. /Pages/Test/Index.cshmtl{,.cs}), `asp-page` doesn't resolve `asp-page="/Test"` to `asp-page="/Test/Index"` as that doc page describes. It instead doesn't "see" the /Test/Index page at all, giving an empty href.

For reference, here's a snap of the part of interest in the docs:

![image](https://user-images.githubusercontent.com/13322960/146652213-123be361-26e4-4266-a540-dcb1029bbce8.png)

So bug/question: which is correct? I've seen other closed issues mention that "/Test/Index" is the correct way, but the online official doc Overview says that "/Test" should give the same result (other sites such as [learnrazorpages.com](https://www.learnrazorpages.com/razor-pages/routing) also echo the official doc).

Tested with both .NET 5.0 and 6.0 simple/basic web app project templates.

### Expected Behavior

According to https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio#razor-pages:

`<a asp-page="/Test"> ... </a>`

should behave the same as:

`<a asp-page="/Test/Index"> ... </a>`

### Steps To Reproduce

1. Create a new, barebones web app project (.NET 5.0 or 6.0) using razor pages.
2. Add a new folder under Pages (e.g. /Pages/Test/)
3. Add a new Index.cshtml{,.cs} razor page under /Pages/Test => /Pages/Test/Index.cshtml{,.cs} (making sure that Index.cshtml includes @page at the top)
4. In /Pages/Index.cshtml, add 2 links: `<a asp-page="/Test">Test without Index</a>` and `<a asp-page="/Test/Index">Test with Index</a>`
5. Build and run the project, examining the link destinations for the two new links. They *should* be the same according to the docs, but the first link destination will be the same as the home page (no href in the first link a tag).

### .NET Version

.NET 5.0 and 6.0

### Anything else?

If this is a documentation issue, please let me know if this can be passed along to them by you all or if I should pass it along myself (and to which project/repo that is).

Did this behavior ever work as documented? (Perhaps in pre-Core versions?)

**Comment by pranavkm** [comment]
The value for asp-page is the PageName which is the path to page without `/Pages` (or the `PagesRoot`) and the extension. The column on the right talks about the incoming urls that will be matched for the page by default. The documentation is correct in that regards.

**Comment by jparnzen** [comment]
Hi, Pranav: Thanks for your reply! I'm aware of the `/Pages` portion of the URL.

My issue/question is in regard to the discrepancy shown in the 4th URL example and the 2nd bullet from the docs, and that `asp-page` doesn't seem to honor what's shown.

**Comment by pranavkm** [comment]
> Per my example and the steps in Expected Behavior, asp-page="/Test" is not resolving/routing to /Pages/Test/Index.cshtml

So what the docs is saying is that when for `/Pages/Test/Index.cshtml` will be served for either of the following HTTP requests: 

* https://mysite.com/Test
* https://mysite.com/Test/Index

It's not talking about the value for `asp-page` which would be `/Test/Index` for this file.

**Comment by jparnzen** [comment]
Ah! Thank you for that explanation, @pranavkm! I was conflating the `asp-page` path and the route-path matching.

So just for my own edification: `asp-path` doesn't use the same route matching algorithm? Is that route matching happening in the framework or in Kestrel?
