### ISSUE TITLE
Blazor WASM application hangs on MSAL Authentication.

### ISSUE THREAD

**Issue by adam-becker** [dotnet/aspnetcore#39104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Same as #38653. When using MSAL authentication in a Blazor WASM application, the login page hangs on the pop-up. Opening the browser's (specifically Chrome) developer tools causes the pop-up to stop hanging and proceed as normal. Our application was created from the Blazor WASM (PWA) template, no modifications have been done to any of the PWA related scripts.

### Expected Behavior

The pop-up shouldn't hang at all, regardless of whether the developer tools are open or not.

### Steps To Reproduce

To get the issue (it's intermittent as noted in [here](https://github.com/dotnet/aspnetcore/issues/38653#issuecomment-997025363)) we just click our sign-in button, the pop-up appears and just sits there. When this happens, opening the browser's developer tools does _something_ and causes the pop-up to proceed and close.

```csharp
// Program.cs
builder.Services
    .AddMsalAuthentication<RemoteAuthenticationState, CustomUserAccount>(options =>
    {
        builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
        options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/openid");
        options.UserOptions.RoleClaim = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
    })
    .AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, CustomUserAccount, CustomUserFactory>();
```

I can provide more details directly to whoever needs to look at it.

### .NET Version

5.0

### Anything else?

IDE: Visual Studio 2022 (2019 also seeing the same issue).
Output of `dotnet --info`:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by TanayParikh** [comment]
Thank you for filing this issue. In order for us to investigate, please provide a minimal public GitHub project that reproduces this issue.

**Comment by adam-becker** [comment]
> Thank you for filing this issue. In order for us to investigate, please provide a minimal public GitHub project that reproduces this issue.

@TanayParikh I will try, might not be able to get to it until next week.

**Comment by eamonn-coleman** [comment]
I can reproduce the problem with this command:

dotnet new blazorwasm -au SingleOrg --api-client-id <guid1> --app-id-uri <guid1> --client-id <guid2> --default-scope my.api.access --domain somedomain.com -ho -o SomeApp --tenant-id <guid3>

First login works.
Logout works.
Second login hangs.

Opening devtools appears to reliably work around the problem.

**Comment by adam-becker** [comment]
Thanks @eamonn-coleman! Looks like the same issue I'm seeing.

**Comment by norbythegeek** [comment]
With Edge, if the browser is launched in InPrivate mode, hangs do not occur during authentication.

**Comment by villodre77** [comment]
I'm facing the same issue here. Any workaround or solution on this yet?

**Comment by dstretch** [comment]
Same problem here :(

**Comment by villodre77** [comment]
I could get around myself setting the login mode as 'Redirect'.

`  ...
  builder.Services
    .AddMsalAuthentication<RemoteAuthenticationState, CustomUserAccount>(options =>
    {options.ProviderOptions.LoginMode = "redirect";`

**Comment by AndreErb** [comment]
Same problem here, with the Blazor project being created from default VS2022 (V17.2.3) templates and no additional changes.
 
Seems to be related to the Popup-Window and "MsalProviderOptions" being on default "LoginMode=popup". The problem occurs only in Chrome (for me) and not in Edge.
The [workaround ](https://github.com/dotnet/aspnetcore/issues/39104#issuecomment-1117082810)of @villodre77 works for me, too and like @eamonn-coleman [wrote](https://github.com/dotnet/aspnetcore/issues/39104#issuecomment-999629970) the hanging login-popup closes only and as soon as one opens Chrome-DevTools

**Comment by ToddEvansHome** [comment]
I have the same problem for months now w/ VS2022 v17.2.3 and "LoginMode=popup".  A temp workaround I use is to have the Chrome DevTools open prior to login.
I have not tried Edge.

**Comment by Roneri75** [comment]
Does not seem to be a difference in browsers, I get it in both Edge and Chrome.
Same problem as everyone else, opening Dev Tools closes the login popup dialog and I get logged in to my App, changing LoginMode to "redirect" like @villodre77 suggested works for me too.
I have a 2 or 3 Blazor WASM with no server projects that have the same issue.
.NET 6.0.7, VS Community 2022 v17.1.0

**Comment by EricOnGit** [comment]
Same here and the issue is getting worst by the day. Originally (a couple months back), this was happening a couple times a day. Now every debugging cycle takes 2-3 application restarts to eventually get through the login process. The login process gets stuck at /authentication/login-callback#state=... in the popup window.

**Comment by Hona** [comment]
I get this problem too - large application, does a little bit of work on the login event. High CPU usage about 20% ongoing while deadlocked.

**Comment by Hona** [comment]
```
	options.ProviderOptions.LoginMode = "redirect";
	options.ProviderOptions.Cache.CacheLocation = "localStorage";
```

using redirect mode & localStorage

**Comment by Hona** [comment]
A bit of context for on our Authentication page:

```html
	<RemoteAuthenticatorView Action="@Action" OnLogInSucceeded="@UpdateAuthenticationState" OnLogOutSucceeded="@ClearAuthenticationState">
		<LoggingIn>
			<LoadingSpinner/>
		</LoggingIn>
		<CompletingLoggingIn>
			<LoadingSpinner/>
		</CompletingLoggingIn>
	</RemoteAuthenticatorView>
```

```cs
    public async void UpdateAuthenticationState()
    {
		var authState = await AuthenticationStateTask;
		var user = Application.User.PortalUserAccessor.MapPortalUser(authState);

        await FeatureFlagsClient.GetFeatureFlagsForUserAsync();

        await BusinessContextService.LoadDefaultOrLocalStorageBusinessContext(user);

		PortalUserAccessor.InvokePortalUserChanged();
    }
```

Here's some minimal snippets.

From lots of poking around with this obscure bug I'm guessing it is when there is long running work on the OnLogInSucceeded callback

**Comment by TomDacquinDMS** [comment]
I have the exact same issue in Google Chrome Mobile. My project is .NET 7.
Authentication flow is stuck on .../authentication/login-callback#code.0.AX.................

it seems to only happen when the #code.... part is added to the call-back. (tried to configure this in Azure Portal, with no luck)
Adding: options.ProviderOptions.LoginMode = "redirect" did not fix my problem.

**Comment by Fabster1993** [comment]
> I have the exact same issue in Google Chrome Mobile. My project is .NET 7. Authentication flow is stuck on .../authentication/login-callback#code.0.AX.................
> 
> it seems to only happen when the #code.... part is added to the call-back. (tried to configure this in Azure Portal, with no luck) Adding: options.ProviderOptions.LoginMode = "redirect" did not fix my problem.

I have the exact same issue. Flow is stuck on "CompletingLogOut". This seems related to [this](https://github.com/dotnet/aspnetcore/issues/43293). For me a fix was, to disable trimming for the app or just disable trimming for the auth assembly:

`    <ItemGroup>
        
        <TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    </ItemGroup>`

**Comment by javiercn** [comment]
We think this was addressed as part of the fixes we did in .NET 7.0. Please update to that version and give it another try.
