### ISSUE TITLE
IHttpConnectionFeature missing after migrate from .net-5 to .net-6

### ISSUE THREAD

**Issue by zeinali0** [dotnet/aspnetcore#39113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I just migrate from `.net-5` to `.net-6` but `IHttpConnectionFeature` is missing while namespace `Microsoft.AspNetCore.Http.Features` exist
I also tried to add `Microsoft.AspNetCore.Http.Features` package but there is not .net-6 version and when add version 5.0.13(it's latest version on nuget), it has conflict with other packages

my project packages:
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
  </ItemGroup>
```

### .NET Version

6.0.101

**Comment by zeinali0** [comment]
solved by upgrading `Microsoft.AspNetCore.Connections.Abstractions` package to 6.0.1

**Comment by Tratcher** [comment]
IHttpConnectionFeature lives in the Microsoft.AspNetCore.Http.Features assembly which no longer ships as a package, it's part of the shared framework. See https://github.com/aspnet/Announcements/issues/462
