### ISSUE TITLE
Adding EntryAssembly to AddRazorPages/AddControllers*

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#39126]
## Background and Motivation
Currently, the default behavior in MVC to load the default `ApplicationParts` from the `entryassembly` is rely on the `IWebHostEnvironment`, however, as reported in the #10611, there are scenarios where the developer wants to just create a new `ServiceCollection` and configure as needed. This scenario is not supported today because some providers will not be loaded, eg. `RazorCompiledItemProvider` required in Razor Pages.

The proposal is to add a new overload to all `Add*` methods available to include `Assembly entryAssembly` parameter that will be used to load the default `ApplicationParts` from.

Related:
- #10611

## Proposed API
```diff
namespace Microsoft.Extensions.DependencyInjection
{
   public static class MvcServiceCollectionExtensions
   {
+      public static IMvcBuilder AddControllers(this IServiceCollection services, Assembly entryAssembly) 
+      {}

+      public static IMvcBuilder AddControllers(this IServiceCollection services, Assembly entryAssembly, Action<MvcOptions>? configure)
+      {}

+      public static IMvcBuilder AddControllersWithViews(this IServiceCollection services, Assembly entryAssembly) 
+      {}

+      public static IMvcBuilder AddControllersWithViews(this IServiceCollection services, Assembly entryAssembly, Action<MvcOptions>? configure)
+      {}

+      public static IMvcBuilder AddRazorPages(this IServiceCollection services, Assembly entryAssembly) 
+      {}

+      public static IMvcBuilder AddRazorPages(this IServiceCollection services, Assembly entryAssembly, Action<RazorPagesOptions>? configure)
+      {}

   }
}
```

```diff
namespace Microsoft.Extensions.DependencyInjection
{
   public static class MvcCoreServiceCollectionExtensions
   {
+      public static IMvcCoreBuilder AddMvcCore(this IServiceCollection services, Assembly entryAssembly)
+      {}
   }
}
```

### RazorPages

 ```csharp
services.AddRazorPages(typeof(Startup).Assembly);
 ```

### Controllers

 ```csharp
services.AddControllers(typeof(Startup).Assembly);
 ```

### Controllers with views

 ```csharp
services.AddControllersWithViews(typeof(Startup).Assembly);
 ```

**Comment by pranavkm** [comment]
* Let's make the configure non-nullable in the API (without null-checking it so users can pass in a null if they really want to). e.g.

```diff
+ public static IMvcBuilder AddControllers(this IServiceCollection services, Assembly entryAssembly) 
{}

public static IMvcBuilder AddControllers(this IServiceCollection services, Assembly entryAssembly, Action<MvcOptions> configure)
+      {}
```

Given that the API touches the startup code, and the plan is to update the templates we should run it by @davidfowl  / @DamianEdwards

**Comment by DamianEdwards** [comment]
I admit I'm not quite following the full plan here. In addition to the new overloads, are we planning to update the templates to call them? What is passed in for the `entryAssembly` parameter? If so, why do we think the default/idiom needs changing? Will the existing overload produce a warning or be documented as legacy?

**Comment by pranavkm** [comment]
> are we planning to update the templates to call them

Yup. 

> What is passed in for the entryAssembly parameter?

We want to pass in the assembly that is the root for scanning controllers / components etc. The actual value to be passed is a bit something to be figured out. We can't quite do `GetType().Assembly` and the generated top-level statement type is currently unmentionable. There isn't another type in app root namespace to do `typeof(WellKnownType).Assembly` so 🤷🏽 

> Will the existing overload produce a warning or be documented as legacy?

We hadn't discussed that, but we could consider doing so. It does mean it'll produce a lot of noise in a whole slew of apps as they are updated.

**Comment by DamianEdwards** [comment]
I **really** don't think we should change the default/idiom here (including the template). Exposing that concept so early and for so many seems like a bad fit. For the vast majority of cases in an app, don't we just want this to be the app assembly itself, which is the entry assembly already?

**Comment by brunolins16** [comment]
> I **really** don't think we should change the default/idiom here (including the template). Exposing that concept so early and for so many seems like a bad fit. For the vast majority of cases in an app, don't we just want this to be the app assembly itself, which is the entry assembly already?

In my opinion, the way MVC detects the entry assembly is **obscure** and hard to find what is going on when errors similar to the reported in the issue happens, however, I think this behavior is there for so many years (i am not sure if the users complained or not before) that I agree with @DamianEdwards that is better no change the default and instead just add the new overload and we maybe we can include in the docs scenarios where they are a better option.

**Comment by dazinator** [comment]
> > I **really** don't think we should change the default/idiom here (including the template). Exposing that concept so early and for so many seems like a bad fit. For the vast majority of cases in an app, don't we just want this to be the app assembly itself, which is the entry assembly already?
> 
> In my opinion, the way MVC detects the entry assembly is **obscure** and hard to find what is going on when errors similar to the reported in the issue happens, however, I think this behavior is there for so many years (i am not sure if the users complained or not before) that I agree with @DamianEdwards that is better no change the default and instead just add the new overload and we maybe we can include in the docs scenarios where they are a 

Makes sense - just wanted to mention that if templates remain using previous method, then it may be prudent to throw an exception when that method cannot locate the entry assembly due to missing prerequisite services, perhaps with the error indicating that the service used to locate entry assembly cannot be found so either register it or use the new overload that takes the entry assembly as a param?

**Comment by brunolins16** [comment]
@dazinator After some discussion we decided that this API is not totally correct, and we should not add it, right now. What I will add instead, for now, is just a log message informing that no actions were detected and could be caused by a misconfiguration. Also point to this documentation [Share controllers, views, Razor Pages and more with Application Parts](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-6.0) that explains the usage of `AddApplicationPart` and `ConfigureApplicationPartManager`
