### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error/ Error code 0x8007000d

### ISSUE THREAD

**Issue by bldevuid798** [dotnet/aspnetcore#39123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.Net Core 6.0 apps on IIS 10 with only Windows Server Hosting bundle 6.0 installed on Win 11 cannot read the web.config file - "This error occurs when there is a problem reading the configuration file for the Web server or Web application. In some cases, the event logs may contain more information about what caused this error."

### Expected Behavior

The app should be able to read the config file, launch and run successfuly.

### Steps To Reproduce

Deploy a 6.0 web app to IIS 10 with only Server Hosting 6.0 bundle on it on Win 11 and run it.

### .NET Version

6.0.1

### Anything else?

When you add Hosting bundle 5.0 (with 6.0 still installed) the app runs successfuly. If you remove Hosting bundle 5.0 the app becomes unable to read the web.config file again.

**Comment by Tratcher** [comment]
Can you share the web.config file for the published app?

**Comment by wtgodbe** [comment]
The install of the 6.0.1 hosting bundle looks normal to me, could you confirm if your app works using the 6.0.0 hosting bundle (after uninstalling 6.0.1) available [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer)? This would help us confirm if it's related to a change to ANCM that was made in 6.0.1. If possible, could you also share your app and/or the event logs from the failure?

**Comment by bldevuid798** [comment]
@Tratcher Here are the contents of an example file. Happens on any app.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\WebApplication3.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: cdad204a-42e0-4cd7-bd4e-4e3809d74eec-->
```

**Comment by bldevuid798** [comment]
In flipping out the various versions of hosting bundle to test, things have begun working as expected with 6.0.1. Not sure what the issue was there (perms were all set right, etc.).

Cheers, so much.
