### ISSUE TITLE
>>NET6 Blazor WASM debugging when running in IIS

### ISSUE THREAD

**Issue by djfoz** [dotnet/aspnetcore#39125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're currently looking at options for migrating an JS based SPA over to Blazor WASM. We believe as of NET6 blazor is now in a good place to start planning this.

In order to aid with this, we're looking at running Blazor WASM hosted in IIS as an application. The idea is that will reference the runtime and then render components via Javascript method. The good news is that we have working without too much of a problem. However, the issues start when it comes to debugging. I just cannot to seem to get debugging working when running via IIS. The documentation on doing this seems a little light, so I'm not even certain if using IIS for Dev is even a support scenario? 

### Expected Behavior

To be able to run the project and for the break points to be hit.

### Steps To Reproduce

I'm able to re-pro the issue with the above setup using the the standard project template for Blazor WASM.

I can confirm running via project and IIS express works and I can debug as a expected, the issue is just when running via IIS.

Here is the following contents of my launchSettings.json file:

```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iis": {
      "applicationUrl": "https://localhost/mytest/",
      "sslPort": 0
    },
    "iisExpress": {
      "applicationUrl": "http://localhost:5855",
      "sslPort": 0
    }
  },
  "profiles": {
    "BlazorApp5": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "http://localhost:5022",
      "dotnetRunMessages": true
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
    },
    "IIS": {
      "commandName": "IIS",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/mytest/_framework/debug/ws-proxy?browser={browserInspectUri}"
    }
  }
}
```

This is how the app is currently showing in IIS:
![image](https://user-images.githubusercontent.com/10595414/146794614-dc4d05ed-3699-4a53-b8d6-8f3a27953337.png)

This is the generated web.config file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="..\..\..\..\..\..\..\Program Files\dotnet\dotnet.exe" arguments="&quot;C:\Users\ommitted_Name\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\6.0.1\build\../tools/blazor-devserver.dll&quot; --applicationpath &quot;C:\Users\ommitted_Name\source\repos\Mam.VastOnline\src\BlazorApp1\bin\Debug\net6.0\BlazorApp1.dll&quot;" stdoutLogEnabled="false" hostingModel="InProcess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

Note I had to make sure IIS app pool has access to both the project and the microsoft.aspnetcore.components.webassembly.devserver package path.

When I have the 'inspectUri' set under "IIS". Starting debugging results in the browser window opening and loading. Eventually, VS will top the debug process and show the error diaglog:

![image](https://user-images.githubusercontent.com/10595414/146795328-093d7ac0-4da4-424e-8fd2-884ea826cf8d.png)

If I remove the the 'inspectUri' under IIS settings, everything seems to work other than been able to hit any break points.

Here is the following JS debugging log file.
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/7746452/visualstudio-js-debugger.txt)

### .NET Version

6.0.101

**Comment by JulienClaudeDiallo** [comment]
We are having the exact same problem. Any plans for working on this soon? Any work arrounds? Thank you!

**Comment by mkArtakMSFT** [comment]
@thaystg can you please look into this one? Any recommendations regarding how to debug Blazor W ebAssembly hosted under IIS?

**Comment by thaystg** [comment]
@mkArtakMSFT can you please explain me how to debug using IIS? For me it only shows IIS express, is there any documentation how to setup under IIS?

**Comment by mkArtakMSFT** [comment]
We have documentation for IIS hosting: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#iis I think the specific question I had was if there is something unique about IIS to make debugging work.

**Comment by thaystg** [comment]
I think it should work, I'll need to test it to see why it's not working.

**Comment by mkArtakMSFT** [comment]
Ok, maye we should start from asking @djfoz. @djfoz is sthis still a problem for you, or should we just close this at this point?

**Comment by MackinnonBuck** [comment]
Closing this out at the request of @djfoz. Glad you were able to find a solution!

**Comment by JulienClaudeDiallo** [comment]
Hi all!
@djfoz We are still having the problem you described on our side. Can you explain to me how you solved it? We are hosting our Blazor WASM (hosted) under IIS and the same error prompt pops-up. 

When we remove the `"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/XXXX/_framework/debug/ws-proxy?browser={browserInspectUri}"`, the application runs but not breakpoints (client side) hit in Visual Studio. We are forced to use the chrome debugger.

**Comment by djfoz** [comment]
@JiDiCi Not sure I can be of much help, the need to use IIS was mostly historic. We switched to using kestrel for dev. We still host on IIS for prod, but no longer bother with for dev, other then a few older FW projects we're yet to convert over.
