### ISSUE TITLE
using IClaimsTransformation on-demand

### ISSUE THREAD

**Issue by mkgn** [dotnet/aspnetcore#39134]
I understand that IClaimsTransformation gets called multiple times. But what if I want to modify the claim based on a specific condition that will occur rarely. So, if it's possible to do something like below; I think it'll be much more performant.

    if (condition = true){
         currentPrincipal.AddClaim("rarely-updated-claim",value);
         IClaimsTransformation.TransformAsync(currentPrincipal)
    }
    // From this point onwards my Identity should have the updated claim (rarely-updated-claim) until the session ends.

In this kind of a scenario, there is no need for the claimtransform to execute on every request as it is happening now. It should just update the identity on-demand with updated claims.

Is this possible?

**Comment by Tratcher** [comment]
When do you detect this condition? In middleware? In your endpoint?

You don't need to run claims transformation to modify the current user, you just need to update the value on HttpContext.User in most cases.

**Comment by mkgn** [comment]
@Tratcher , Yes a middleware. The requirement is that before every call we need to check whether the authenticated user have accepted the privacy statement. So, when user logs in (we use AspNet core Identity); with other user claims we add a claim stating whether the user has accepted privacy statement.

In subsequent calls we need to check that claim value and redirect to a page where he can agree/disagree. Once agreed, update db, update the current session claim and continue with the application. The only difference in this use case is that claimstransfomer should not get called every time. Middleware calls the transform.

I am not sure how to do this by directly updating the HttpContext.User values. As far as I am aware once the identity is created to properly update it you must go through ClaimsTransform? 

I am not sure whether this is a use case where other users will also find useful. But having a feature to transform the current claims on-demand seems useful. Otherwise you need to force logout user to get it refreshed.

As of now, if we don't have any other option, we thought to just stick some data in headers via middleware and use that value instead of trying claims. AuthorizationPolicy is also another option I guess, but middleware seems more natural in this case....

**Comment by Tratcher** [comment]
I'm not sure you need the claims transformer at all in this example.

The privacy statement check/claim is a long-lived value persisted in the database with the other user claims. You'd have a middleware or an authorization policy check this is present for the current user and trigger the redirect if not. On the acceptance page you add the new claim to the user database. To update the current user you do not need to run ClaimsTransformation, you call the SignInManager to refresh the cookie with the new set of claims. (@haok, what's the API for that, SignInAsync?). The user doesn't have to be signed out before you sign them back in with new claims. Then you redirect back to the original page they were accessing.

**Comment by mkgn** [comment]
Since I have been hacking it away in a test application with middleware and claimtransformation, I wanted to give it a shot. Anyway I agree with your approach. The confusion I had was I assumed IClaimsTransform will persist the claim changes throughout. Well it does but only for the current request. So, if you want to persist the updated claim, I had to do both below;

                    await SignInManager.SignOutAsync();
                    await SignInManager.SignInWithClaimsAsync(user, false, updatedClaims);

But I need to make some changes to the code to do what you said. Thank you!
