### ISSUE TITLE
Advanced NewtonsoftJson parsing error handling

### ISSUE THREAD

**Issue by DaveLaa** [dotnet/aspnetcore#39132]
Advanced Newtonsoft parsing error handling

I have a suggestion to the Microsoft.AspNetCore.Mvc.NewtonsoftJson project to improve the possibility of parsing error handling. 

In my services project I have the need to be able to decide which parsing error of json objects sent to my service are tollerable and can be safely ignored. I achieve this goal by adding an error handler in the SerializerSettings of NewtonsoftJson and setting the Handled property to true.
This was no problem as long as my service project was compiled against .Net Framework. But now we refactored the services to compile against .Net Core 5 and here I found out that there is no way to have this decision.

In my new Startup I added the NewtonsoftJson support and also my error handler like this:

```
public class Startup {
	
	...

	public void ConfigureServices( IServiceCollection services ) {
	
		...

		services.AddControllers().AddNewtonsoftJson( opts => {
				...
				opts.SerializerSettings.Error = ( sender, args ) => {
					if(...){
						...
						args.ErrorContext.Handled = true;
					}
				};
		} );
		
		...
	}
}

```

But whatever i declare handeld, the error was allways thrown anyways by the AspNet framework. I debugged the NewtonsoftJsonInputFormatter and found out that here all errors are passed to the ModelStateDictionary regardless of being handled before or not. More important is that the parsed model ist not returned (always `return InputFormatterResult.Failure();`) and my service entdpoint gets a null object instead. There is also no way to configure a different behaviour.

My suggestion ist now to look into the Handled property and ignore errors that are already handled by user in external code:

```
public class NewtonsoftJsonInputFormatter : TextInputFormatter, IInputFormatterExceptionPolicy
{
	...

	public override async Task<InputFormatterResult> ReadRequestBodyAsync(
		
		...
		
		void ErrorHandler(object sender, Newtonsoft.Json.Serialization.ErrorEventArgs eventArgs)
		{
>>			if( eventArgs.ErrorContext.Handled ){
>>				// Error was already handeld by User in external code
>>				return;
>>			}
		
			successful = false;
			....
		}
	}

	...
}

```

Is it possible to implement this feature in future versions of .Net Core 5?

**Comment by pranavkm** [comment]
@DaveLaa your suggestion makes good sense. I'm going to use https://github.com/dotnet/aspnetcore/issues/37323 to continue discussing this since it's also talking about tackling this specific scenario.
