### ISSUE TITLE
Downloading large files in Blazor WASM - memory leak?

### ISSUE THREAD

**Issue by jahnotto** [dotnet/aspnetcore#39131]
I am trying to download several large files (~200 MB). Even if I am not storing the data, the browser consumes ~800 MB of memory every time I try to download the file until I get an OutOfMemoryException or the following exception in the console window:
        
       Uncaught RuntimeError: memory access out of bounds
    at 009705ea:0x1c7e95
    at 009705ea:0x927b2
    at 009705ea:0x94525
    at 009705ea:0x96ad
    at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.6.0.1.ynjylm5yl3.js:1)
    at Object.managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle [as _release_js_owned_object_by_gc_handle] (managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle:16)
    at Object._js_owned_object_finalized (dotnet.6.0.1.ynjylm5yl3.js:1)
    at FinalizationRegistry.cleanupSome (<anonymous>)

The file is read as following:

```
 public class Loader
    {
        public static async Task LoadIt(HttpClient http)
        {
            await using var stream = await http.GetStreamAsync("/largefile.dat");

            var buf = new byte[1024 * 1024];
            int bytesRead = 0;

            while (true)
            {
                int readNow = stream.Read(buf, 0, buf.Length);

                if (readNow == 0)
                {
                    break;
                }

                bytesRead += readNow;
            }
        }
  }
```

The download is triggered via a button handler:

```
@page "/"
@inject HttpClient HttpClient;

<button @onclick="LoadClicked">Download</button>

@code {
    private async Task LoadClicked()
    {
        await Loader.LoadIt(HttpClient);

        GC.Collect();
    }
}
```

I have also tried to create a new HttpClient instead of injecting it, disabling caching: 

```
using var http = new HttpClient { BaseAddress = new Uri("https://localhost:7255/") };
            http.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue
            {
                NoStore = true
            };
```

Any ideas?

**Comment by MariovanZeist** [comment]
``GetStreamAsync(Uri)`` will load the entire response body before completion. so in your case the 200Mb files will be loaded into memory before you start copying it.

use something like:

```cs
  var response = await Client.GetAsync("/largefile.dat", HttpCompletionOption.ResponseHeadersRead);
  //^returns when headers are read
  using var stream = await response.Content.ReadAsStreamAsync();
````

**Comment by jahnotto** [comment]
Thanks a lot @MariovanZeist ! That seems to do the trick.
