### ISSUE TITLE
Blazor WASM SEO issues

### ISSUE THREAD

**Issue by keerthirajap** [dotnet/aspnetcore#39137]
Blazor WASM needs simple and quick solution on SEO for rendering Title, Meta and Link tags on Twitter and Facebook cards. 

bing webmasters is showing errors on using PageTitle and HeadContent tags.

Provide inbuilt option for Robot.txt and sitemap.xml

**Comment by keerthirajap** [comment]
I temporally resolved by using prerender.io and cloudflare.com services for the website launched in IIS, by following the blog : https://www.baskaran.dev/posts/2021/1/blazor-seo-prerendering

**Comment by pranavkm** [comment]
Do you have prerendering enabled in your app? https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly

**Comment by keerthirajap** [comment]
I tried it, Its not working with dependency injection and Authentication, Authorization.

I am asking this support for WASM only, but your link says we need to have in server and client project.

**Comment by javiercn** [comment]
Closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/27592 since it's a duplicate. 

Please upvote the other feature instead.
