### ISSUE TITLE
Whether the TimeOnly.ToDateTime method is missing this

### ISSUE THREAD

**Issue by joesdu** [dotnet/aspnetcore#39135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wanted to convert the existing DateOnly type to the DateTime type, but when I used the ToDateTime function I found that it could not be converted directly, and after decompiling it through ReSharper, I found that the function was not an extension method of DateOnly
![image](https://user-images.githubusercontent.com/13188169/146927229-393e3cd5-3b11-48a7-a427-2575bf753648.png)

### Expected Behavior

var birthday = "595628199405088126".CalculateBirthday().ToDateTime();
// Birthday : 1994-05-08 00:00:00 UTC +8

### .NET Version

6.0.101

**Comment by MariovanZeist** [comment]
The ``ToDateTime`` function of ``DateOnly`` expects a ``TimeOnly`` parameter to fill in the Timepart.
You could use ``dateOnlyVariable.ToDateTime(TimeOnly.MinValue)`` If you want the time part to be 0

**Comment by joesdu** [comment]
> The `ToDateTime` function of `DateOnly` expects a `TimeOnly` parameter to fill in the Timepart. You could use `dateOnlyVariable.ToDateTime(TimeOnly.MinValue)` If you want the time part to be 0

I got it, thanks.
