### ISSUE TITLE
FindByIdAsync requires string instead of int even with ApplicationUser: IdentityUser<int>

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#39157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I might be seeing this wrong but shouldn't FindByIdAsync accept an int instead of string when ApplicationUser: IdentityUser<int>?

I'm using var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == userId); as an alternative but just wanted to be sure of this.

Thank you!

### .NET Version

.net 6

**Comment by blowdart** [comment]
It's a design decision. String is the lowest common denominator here, as ToString() works for all primitives nicely. Trying to make this more generic, when we simply don't know what key type you might be using would be an api usability nightmare and honestly would make things less usable for most users, and making customizing the user class even more difficult.

**Comment by HybridSolutions** [comment]
> It's a design decision. String is the lowest common denominator here, as ToString() works for all primitives nicely. Trying to make this more generic, when we simply don't know what key type you might be using would be an api usability nightmare and honestly would make things less usable for most users, and making customizing the user class even more difficult.

ok thanks.,
