### ISSUE TITLE
a blazor page has many iframe and iframe is also blazor webassembly app

### ISSUE THREAD

**Issue by superlitt** [dotnet/aspnetcore#39153]
a blazor page has many iframe and iframe is also blazor webassembly app
how to quick speed.
and the page is in app(android or ios) how does it active quick.
3q

**Comment by TanayParikh** [comment]
Based on your description, it appears you're trying to utilize a Blazor component.

Ie. you want to show ComponentABC.razor inside of HomePage.razor. In that case, you can just do:

HomePage.razor:

```razor
<ComponentABC></ComponentABC>
```

ComponentABC.razor:

```razor
Hello World from Component ABC!
```

Documentation on using components is found here https://docs.microsoft.com/dotnet/architecture/blazor-for-web-forms-developers/components#use-components. No need to utilize iframes! 😄 

I'd recommend checking out the Blazor demo by doing `dotnet new blazorserver`. Note how the `<SurveyPrompt>` component (`SurveyPrompt.razor`) is used inside `Index.razor`.
