### ISSUE TITLE
Problem with the ASP.NET Core-Web-API template if creating new project with "swagger"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39158]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-with-the-ASPNET-Core-Web-API-te/1610841)._

---
[severity:It's more difficult to complete my work]
The problem is this part of code in startup.cs:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env. IsDevelopment())
            {
                app. UseDeveloperExceptionPage();
                app. UseSwagger();
                app. UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "WebApplication1 v1"));
            }
```

The Lines of code where used for "swagger" are in the if blog.
It seems like wrong, because my external hosting service will discard "swagger" so.
In generell this lines should be outside of this blog. Than swagger will run on my external website.

---
#### Feedback Bot on 12/12/2021, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Swagger is intentionally enabled only in Development. Most users do want to expose their entire API map outside of development. If you would like to enable it in production, removing the condition is fairly trivial.
