### ISSUE TITLE
CORS AllowAnyOrigin starts not working after .NET 6 upgrade 

### ISSUE THREAD

**Issue by ldsenow** [dotnet/aspnetcore#39152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

After .NET6 upgrade, my web api project starts not recognizing the AllowAnyOrigin for CORS for some reason.
When I put the domain in the WithOrgions list, it works. Not sure if it is a breaking change or a bug?

Could someone have a look at this?

Cheers,
LD

### Steps To Reproduce

services.AddCors();

app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod()
            );

### .NET Version

6.0.101

**Comment by brunolins16** [comment]
@ldsenow, I just tried and seems to work for me.

![image](https://user-images.githubusercontent.com/12376385/147136921-ef2bfdba-05a9-4615-96b5-3e5e42362a2f.png)

Can you share a repro project?

Here is the code I used:

``` csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddCors();

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseAuthorization();

app.MapControllers();

app.UseCors(x => x.AllowAnyOrigin()
    .AllowAnyHeader()
    .AllowAnyMethod()
);

app.Run();
```

**Comment by ldsenow** [comment]
I found a solution to it today. Since the project was upgraded from .NET core 3.1 to .NET 5 to .NET 6, somehow, the IHost.Start() is being used in program start. It was working fine until .net 6, I now change it to IHost.Run(), it fixes the problem. A bit of heart attack before releasing to prod.
