### ISSUE TITLE
Set asp-append-version to true for everything

### ISSUE THREAD

**Issue by singh733** [dotnet/aspnetcore#39150]
**Goals**

#35553 

Proposed Solution:
a) Add **AppendVersion** property in the **MvcOptions** file.
b) Then use that property in the **LinkTagHelpers.cs**
c) if someone has set the **asp-append-version** in the .cshtml page then we use that otherwise we will use from the **Mvc options**.

Sample

![image](https://user-images.githubusercontent.com/83835739/147048123-4003171f-6f43-4f31-b681-d2c25c93753d.png)
![image](https://user-images.githubusercontent.com/83835739/147048179-d503afde-0f7f-4813-8dbb-441ec7c7416f.png)

**Comment by pranavkm** [comment]
We could consider putting this in `HtmlHelperOptions` instead. The options name is a bit unfortunate, but it'd be much closer to where this setting needs to be.

```diff
public class HtmlHelperOptions
{
+    /// <summary>Gets or sets a value that determines if a file version is appended by default to <c>LinkTagHelper</c> and <c> ScriptTagHelper</c> instances. This value is ignored if the tag helper specifies a value for the <c>asp-append-version</c> attribute.</summary>
+    public bool AppendFileVersionsToTagHelpers { get; set; }
}
```

## Usage:

```C#
services.AddRazorPages();
services.Configure<HtmlHelperOptions>(options => options.AppendFileVersionsToTagHelpers = true; });
```

I'm not a fan of the property name, but we might come up with something better during API review.

**Comment by pranavkm** [comment]
Continuing this discussion in https://github.com/dotnet/aspnetcore/issues/35553
