### ISSUE TITLE
[.NET 6.0] server serve static file without specify any charset in the Content-Type Response Header

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#39169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, in my blazor app i serve some static files and show them by embedding them a iframe (so the browser deal directly with the type of file, can be image, video, sound, pdf, etc)

I notice encoding problem on accentuated character on the txt and the html files when its shown in the iframe

I try to insert a `<meta charset="utf-8">` inside the head on the iframe but same result

i notice on the http call to the file these Response Headers
````
accept-ranges: bytes
content-encoding: br
content-type: text/plain
date: Thu, 23 Dec 2021 13:15:47 GMT
etag: "1d7f7ff334b008b"
last-modified: Thu, 23 Dec 2021 13:15:48 GMT
server: Kestrel
vary: Accept-Encoding
````

Im surprise there is no utf-8 specified in the content-type header, im wondering if this is the source of my problem ?
I expected something like that `content-type: text/plain; charset=utf-8`

i try to play with the StaticFileOptions in Startup to change the headers but even put empty option maker the app broken at startup
````
app.UseStaticFiles(new StaticFileOptions { 
});
//even doing this break the app, when the app start the file blazor.server.js finish in 404 on client side
````
So i can't really make something here

th serve my static files, i use a virtual directory on this manner
````
app.UseFileServer(new FileServerOptions
                {
                    FileProvider = new PhysicalFileProvider(Sys.Web.AppliIs.Path_Webdav),
                    RequestPath = new PathString("/" + Sys.Web.AppliIs.WEBDAV_FOLDER),
                    EnableDirectoryBrowsing = false
                });
````

I notice i don't have encoding problem when i open the link directly with chrome, its only inside my iframe for now, i can't explain that.

Thanks for your help

### Expected Behavior

charset specify in the content-type response header, or a way to add it

### Steps To Reproduce

Access to a static file and check the response header content-type

### .NET Version

6.0.100

**Comment by BrennanConroy** [comment]
You shouldn't be calling UseStaticFiles directly when using blazor and should instead be configuring options as described in https://docs.microsoft.com/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0#blazor-server-file-mappings-and-static-file-options

For the charset, there is no way for us to know the charset of a file when serving it. Static files does provide a callback for you to set headers if you know what it should be.

**Comment by julienGrd** [comment]
I was able to override the OnPrepareResponse to add the charset, i don't know why but i have to put ISO charset to resolve encoding problems
````
var lOptions = new FileServerOptions
                {
                    FileProvider = new PhysicalFileProvider(Sys.Web.AppliIs.Path_Webdav),
                    RequestPath = new PathString("/" + Sys.Web.AppliIs.WEBDAV_FOLDER),
                    EnableDirectoryBrowsing = false,
                };
                lOptions.StaticFileOptions.OnPrepareResponse = (context) =>
                {
                    var headers = context.Context.Response.Headers;
                    var contentType = headers["Content-Type"];

                    contentType += "; charset=ISO-8859-1";

                    headers["Content-Type"] = contentType;

                };

  app.UseFileServer(lOptions);
````

anyway thanks for your help
