### ISSUE TITLE
IClaimsTransformation TransformAsync not called in Firefox (asp.net core 6.0 razor pages web app)

### ISSUE THREAD

**Issue by bairog** [dotnet/aspnetcore#39177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Claims Transformer's constructor is called as expected, but TransformAsync is not in latest Firefox 95.0.2. Start page is not showing.
TransformAsync is called in latest Chrome, MS Edge and Opera. Start page is showing correctly.

### Expected Behavior

TransformAsync is called in all browsers. Start page is showing correctly.

### Steps To Reproduce

1. Create new ASP.NET Core 6.0 Web App from a template, set Authentification Type to Windows.
2. Add simple ClaimsTransformer class
```
public class ClaimsTransformer : IClaimsTransformation
    {
        private readonly IHttpContextAccessor _accessor;

        public ClaimsTransformer(IHttpContextAccessor accessor)
        {
            _accessor = accessor;
        }
        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            return Task.FromResult(principal);
        }
    }
```
3. Add HttpContextAccessor and ClaimsTransformer to services
```
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();

builder.Services.AddAuthorization(options =>
{
    // By default, all incoming requests will be authorized according to the default policy.
    options.FallbackPolicy = options.DefaultPolicy;
});

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<IClaimsTransformation, ClaimsTransformer>();

builder.Services.AddRazorPages();

var app = builder.Build();
```
4. Run app - the Claims Transformer's constructor is called as expected, but TransformAsync is not in latest Firefox 95.0.2

This reproduces on Windows 10 1909, Windows 10 21H2 and Windows 11.

sample repo - https://github.com/bairog/ClaimsTransformerTest

### .NET Version

6.0.101

### Anything else?

ASP.NET Core version - 6.0

The IDE Visual Studio 2022 Pro 17.0.4

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Sfairait** [comment]
Exactly same thing for me with ASP.NET Core version - 6.0 The IDE Visual Studio 2022 Community 17.0.4 on Windows 11.

**Comment by Tratcher** [comment]
IClaimsTransformation only runs if authentication succeeds. When I tried this on firefox the browser didn't even try to respond to the initial 401 challenge. It worked after I went to `about:Config` and enabled `network.negotiate-auth.allow-non-fqdn` since I was testing on localhost. Does that work for you?

**Comment by bairog** [comment]
> It worked after I went to `about:Config` and enabled `network.negotiate-auth.allow-non-fqdn` since I was testing on localhost. Does that work for you?

For me it's also working with enabled `network.negotiate-auth.allow-non-fqdn` option. Thank you.
