### ISSUE TITLE
Blazor JSInterop Callback to .NET Method fails with dotnet.js: Cannot set properties of undefined in async javascript webgpu context

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/aspnetcore#39173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Version: aspnetcore 6.0.1

Ok this might be a quite to experimental problem but maybe you can throw me a bone.

I want to test blazor with the experimental WebGPU in Edge Canary.

Now a weird problem occures after starting the engine I want to make callback to Blazor,
here I tried both returning a promise with a value from a async Method or invoking invokeMethodAsync of a DotNetObjectReference both result in the errors below:

- If I use babylon.js with WebGPU (BABYLON.WEbGPUEngine.initAsync) the code fails with the code below
- But if I use babylon.js with WebGL the code works fine.
- This is not an issue of edge/chrome canary since if I deactivate there web-gpu and the WebGL fallback is used
it also works fine.
- Even when I start a setTimeout in the WebGPU "Initalizing" Thread, the callback still fails.
- It is not the async function since in the code beforehand already a async call is invoked.
- It seems after activiating webgpu in the javascript-"thread", something strange happens with this thread.

_**Now even if you cannot help me, is there a maybe a non compressed version of dotnet.js that I can at least debug what is happening?**_

![grafik](https://user-images.githubusercontent.com/4217002/147263012-7cc3084a-bba3-4d93-a6a3-e4e73b68d462.png)

```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '11712739')
    at Object._unsafe_set (:5043/_framework/dotnet.6.0.0.180186c4m7.js:1:115437)
    at Object.set (:5043/_framework/dotnet.6.0.0.180186c4m7.js:1:116277)
    at Object.mono_wasm_new_root (:5043/_framework/dotnet.6.0.0.180186c4m7.js:1:120016)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet (mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:6:35)
    at Object.beginInvokeDotNetFromJS (:5043/_framework/blazor.webassembly.js:1:41941)
    at b (:5043/_framework/blazor.webassembly.js:1:1995)
    at N.invokeMethodAsync (:5043/_framework/blazor.webassembly.js:1:3845)
    at SceneCallback.EngineStartComplete (renderbundle.js:141:35)
    at BabylonRenderer.startEngine (renderbundle.js:45:28)
```

In case web-gpu is activated a async method is executed and this later causes a problem when trying to callback dotnet

![grafik](https://user-images.githubusercontent.com/4217002/147264225-9c2d2e60-f322-4a3b-9f37-6dbcb0d501a1.png)

### Steps To Reproduce

If you would want to reproduce:
get 
https://github.com/MichaelPeter/BlazorHybridWebGPUTest](https://github.com/MichaelPeter/BlazorHybridWebGPUTest/tree/bug/dotnet-6-fails-callbacks
Importaint: Use the Branch: bug/dotnet-6-fails-callbacks

Follow these instructions:
```
Goto the BlazorHybridWebGPUTest.Controls project
execute npm install for the typescript depencenties
(First step can be emitted if already build)

    Install Edge Canary or Chrome Canary
    goto edge://flags or chrome://flags
    Activate: Unsafe WebGPU
    Restart the Browser
```

Start Project BlazorHybridWebGPUTest.Server

The Importaint files in the project are:
BlazorHybridWebGPUTest\Controls\wwwroot\js\renderbundle.js
BlazorHybridWebGPUTest\Controls\Scene.razor

### .NET Version

6.0.100

**Comment by pranavkm** [comment]
Thank you for your issue report @MichaelPeter. It looks like quite a bit of user code is involved in your application and it's not clear if this is an issue specific to Blazor. If you're able to provide us a minimal repro that indicates it's a problem with the framework, we'd be happy to investigate. Consider posting this issue on StackOverflow using the _area-blazor_ tag to get to a wider audience of users.
