### ISSUE TITLE
SignalR HubConnection is logging an incorrect Timeout

### ISSUE THREAD

**Issue by tcs-devel** [dotnet/aspnetcore#39171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a SignalR HubConnection is terminated by the server due to `ClientTimeoutInterval` being elapsed, it generates an incorrect log entry because the configured timeout is interpreted as ticks instead of milliseconds.

Sample output for a timeout set to 90s:
```
21-12-23 08:05:01.845 [DBG] [Microsoft.AspNetCore.SignalR.HubConnectionContext] Client timeout (9ms) elapsed without receiving a message from the client. Closing connection.
```

The configured timeout is stored as milliseconds in the following line:
https://github.com/dotnet/aspnetcore/blob/c65dac77cf6540c81860a42fff41eb11b9804367/src/SignalR/server/Core/src/HubConnectionContext.cs#L66

but interpreted as ticks in this line
https://github.com/dotnet/aspnetcore/blob/c65dac77cf6540c81860a42fff41eb11b9804367/src/SignalR/server/Core/src/HubConnectionContext.cs#L673

### Expected Behavior

The generated log entry should show the correct timeout value.

### .NET Version

6.0.101

**Comment by BrennanConroy** [comment]
Nice catch, we'd welcome a PR if you're interested!
