### ISSUE TITLE
Back action behavior is different in Blazor Server (server-side) and Blazor WebAssembly (client-side)

### ISSUE THREAD

**Issue by Bilchenko** [dotnet/aspnetcore#39172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

We use Blazor Server, so it is too inconvenient for users, that pages opened on top, when user click back. 

Blazor Server: 
Index page scroll down, go to Counter, Click Back, Index page opened with scroll position on top.
Blazor WebAssembly: 
Index page scroll down, go to Counter, Click Back, Index page opened with scroll position on bottom.

In my opinion need check this [ResetScrollIfNeeded](https://github.com/dotnet/aspnetcore/issues/10482)

### Expected Behavior

In my opinion, behavior should be same for WebAssembly and Server.
I prefer behavior, which Blazor WebAssembly used.

### Steps To Reproduce

Add Simple code to new Blazor Project Index Page
`@for (var i = 0; i <= 100; i++)`
`{`
`  <p>test line</p>`
`}`
`<a href="Counter">Go to Counter</a>`

### .NET Version

6.0.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
