### ISSUE TITLE
Blazor server: 'global using Microsoft.AspNetCore.Components.Web' not working

### ISSUE THREAD

**Issue by hypeartist** [dotnet/aspnetcore#39188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For all global usings I use some dedicated file (`GlobalUsings.cs`). Most usings defined there are works as expected, but `Microsoft.AspNetCore.Components.Web` doesn't. 

![image](https://user-images.githubusercontent.com/3519388/147393649-158e0394-de5f-4e17-b40e-0290c6192514.png)

See that `@onclick:preventDefault` on `p` tag in `TestComponent`. To make it work we need reference `Microsoft.AspNetCore.Components.Web` so I've added that reference into my `GlobalUsings.cs`. Seems like ok, but no. Trying to run the app `TestComponent` creation fails with:

`
Failed to execute 'setAttribute' on 'Element': '@onclick:preventDefault' is not a valid attribute name.)
` 

To make it finally work I had to reference `Microsoft.AspNetCore.Components.Web` explicitly in `TestComponent.razor`:

![image](https://user-images.githubusercontent.com/3519388/147393743-7f9d54b4-e93c-4470-bb9f-28fbe322a2c9.png)

### .NET Version

6.0.101

**Comment by pranavkm** [comment]
There's a [known issue](https://github.com/dotnet/aspnetcore/issues/34719) where global usings don't affect Razor files. For now I'll recommend using Imports.razor to add a using to all of your .razor components.
