### ISSUE TITLE
not working blazor server on docker compose

### ISSUE THREAD

**Issue by Alireza2125** [dotnet/aspnetcore#39190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

bug on visual studio 2019 and 2022

create blazor server
add Linux docker
add to docker compose
run and get exception: The path must be absolute.

bug in /app/bin/Debug/net6.0/BlazorApp1.staticwebassets.runtime.DT.json
exist windows path in this file but run on Linux and app can't find wwwroot directory

### .NET Version

6.0.1

**Comment by pranavkm** [comment]
Could you use the [VS feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to file this issue? It'll help get this routed to the right team in VS to look at the issue.
