### ISSUE TITLE
ApiAuthorization VS Authentication: Null reference on missing configuration dependency 

### ISSUE THREAD

**Issue by motmot80** [dotnet/aspnetcore#39206]
## Summary
AspNetCore API dependencies should be well documented, comprehensible and visible. Missing dependencies should result in a human readable error.

## Motivation and goals
I spent serveral hours of debugging to find the cause of a null reference exception when calling `UseIdentityServer`.

```
Microsoft.Extensions.DependencyInjection.ConfigureApiResources.GetApiResources() in ConfigureApiResources.cs
   Microsoft.Extensions.DependencyInjection.ConfigureApiResources.Configure(Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationOptions) in ConfigureApiResources.cs
    Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string) in OptionsFactory.cs
    Microsoft.Extensions.Options.UnnamedOptionsManager<TOptions>.Value.get() in UnnamedOptionsManager.cs
    Microsoft.Extensions.DependencyInjection.IdentityServerBuilderConfigurationExtensions.AddClients.AnonymousMethod__8_1(System.IServiceProvider) in IdentityServerBuilderConfigurationExtensions.cs
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, TArgument) in CallSiteVisitor.cs
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext) in CallSiteRuntimeResolver.cs
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, TArgument) in CallSiteVisitor.cs
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext) in CallSiteRuntimeResolver.cs
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, TArgument) in CallSiteVisitor.cs
```

Then I found out that a call to `services.AddAuthentication.AddIdentityServerJwt()` was missing and solves this issue. That absolutely wasn't a face palm for event for me. I think if asp-net-core keeps change-friendly it must be more beginner-friendly to not drive users away.

## In scope
If a dependency is missing there should be an error hinting to the solution, the component or even the package.

## Examples
A missing dependency between `AddApiAuthoritaton` (`Microsoft.AspNetCore.ApiAuthorization.IdentityServer`) and `AddAuthentication` (`Microsoft.AspNetCore.Authentication`) should NOT just result in an null reference exception.

Check if the configuration is setup right and if not throw `InvalidOperationException`s with a hint what might be misconfigured.

**Comment by pranavkm** [comment]
Is this a .NET 6 app? There was a similar null-ref that was resolved in the release: https://github.com/dotnet/aspnetcore/issues/32334
