### ISSUE TITLE
Make REST API a hosted service explicitly

### ISSUE THREAD

**Issue by Banyc** [dotnet/aspnetcore#39215]
## Background and Motivation

REST servers should be treated the same as user defined services. The nowadays usage of the REST functionality heavily relies on `WebApplicationBuilder`, a web-centric design. But, in fact, the REST server is a remote process interface, no difference than the message queue adaptors for Kafka, RabbitMQ alike or than grpc. In the original 
version, the message queue adapters look inappropriately inferior to the mere REST server.

Also, WebApplication is in itself a `IHostedService` as illustrated here (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0#:~:text=a%20web%20app%2C-,one%20of,-the%20IHostedService%20implementations) and demonstrated here (https://github.dev/dotnet/aspnetcore/blob/ab80f42b175c8fdace4198a1cdcd3f856b2544e6/src/Hosting/Hosting/src/GenericHostWebHostBuilderExtensions.cs#L61). Aided with the principle of decoupling, It could be another feasible motive to back this proposal.

## Proposed API

```csharp
var builder = Host.CreateDefaultBuilder(args);

builder.ConfigureServices(services =>
{
    // the REST thing
    services.AddHostedService<RestServer>(serviceProvider =>
    {
        var config = serviceProvider.GetRequiredService<IConfiguration>();
        var logger = serviceProvider.GetRequiredService<ILogger<RestServer>>();
        var server = new RestServer(config, logger);
        server.UseHttpsRedirection();
        server.UseAuthorization();
        server.AddEndpoint<WeatherForecastController>("/weatherforecast");
        return server;
    });

    // the message queue thing
    services.AddHostedService<MessageQueueConsumer>();
});
var host = builder.Build();
await host.RunAsync();

class RestServer : IHostedService
{
    private readonly IConfiguration config;
    private readonly ILogger<RestServer> logger;
    public RestServer(IConfiguration config, ILogger<RestServer> logger)
    {
        this.config = config;
        this.logger = logger;
    }
    public Task StartAsync(CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}
```

## Usage Examples

The usage is already included above.

## Alternative Designs

```csharp
var builder = Host.CreateDefaultBuilder(args);

// the REST thing
builder.ConfigureWebHostDefaults(webBuilder =>
{
    // Add services to the container.
    webBuilder.ConfigureServices(services =>
    {
        services.AddControllers();
        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen();
    });

    // Configure the HTTP request pipeline.
    webBuilder.Configure((ctx, app) =>
    {
        if (ctx.HostingEnvironment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }

        app.UseHttpsRedirection();

        app.UseRouting();

        app.UseAuthorization();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    });
});

builder.ConfigureServices(services =>
{
    // services.AddHostedService<>();
});
var host = builder.Build();
await host.RunAsync();
```

## Risks

The proposal might pose few additional risks since the decoupling does not affect the usage of `WebApplication`. 

diff --git a/.github/ISSUE_TEMPLATE/25_api_proposal.md b/.github/ISSUE_TEMPLATE/25_api_proposal.md

**Comment by BrennanConroy** [comment]
We aren't planning on redesigning this area.

Have you taken a look at the Minimal APIs? https://docs.microsoft.com/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0

**Comment by Banyc** [comment]
@BrennanConroy It's still a web-centric design but at least it works.
