### ISSUE TITLE
ASP.NET CORE 6 - Blazor - Infer the component type for child components from a method

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#39217]
### Is your feature request related to a problem?
I am trying to infer the component type from a method. Here are 2 components.

**Column.razor**
```C#
@typeparam TTT

@code {
    [CascadingParameter] public Grid<TTT>? MyGrid { get; set; }

    protected override void OnInitialized()
    {
        MyGrid?.Add(this);
    }
}
```
**Grid.razor**
```C#
@attribute [CascadingTypeParameter(nameof(TTT))]
@typeparam TTT

<CascadingValue Value="this">
    @Columns
</CascadingValue>

@code {
    [Parameter] public List<TTT>? Items { get; set; }
    [Parameter] public RenderFragment? Columns { get; set; }
    [Parameter] public Func<Task<IEnumerable<TTT>>>? ItemsProvider { get; set; }
    private readonly List<Column<TTT>> MyColumns = new();

    public void Add(Column<TTT> column)
    {
        MyColumns.Add(column);
    }
}
```

When using these 2 components on the Index page below, I got the following error messages:

_RZ10001 The type of component 'Column' cannot be inferred based on the values provided.
Consider specifying the type arguments directly using the following attributes: 'TTT'.
CS0411 The type arguments for method 'TypeInference.CreateColumn_1(RenderTreeBuilder, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly._

**Index.razor**
```C#
<Grid ItemsProvider="@Provide">
    <Columns>
        <Column></Column>
    </Columns>
</Grid>

@code {
    List<Test> tests = new();

    async Task<IEnumerable<Test>> Provide()
    {
        await Task.Delay(1);
        return new List<Test>() { new Test() { Name = "Name" } };
    }
}
```

### Describe the solution you'd like
The issue can be fixed by:

A) Define the type explicitly for the Column:  ```<Column TTT="Test">```
B) Define the Items parameter for the Grid: ```<Grid ItemsProvider="@Provide" Items="tests">```
C) Use the ```ItemsProvider``` delegate defined for the official Virtualize component.

I wish there was another solution that avoided A, B and C. Is this possible to implement it?
It would be more user friendly and easier to implement when proposing a library with components.
I also think that any answer will help people facing the same situation and could be added in the official [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-6.0).
Or maybe I am missing something?

PS: Column.razor and Grid.razor are in a library.

**Comment by TanayParikh** [comment]
Hi @boukenka, thanks for contacting us. Can you please confirm what the `Columns` component is in this case. 

I'm assuming the `Test` class is just something trivial like `class Test { string Name { get; set; } }`.

**Comment by TanayParikh** [comment]
Thanks @boukenka for reporting. I've confirmed the issue, marking as enhancement.

**Comment by boukenka** [comment]
@mkArtakMSFT Hello. Could this issue be added to the [[WIP] ASP.NET Core Roadmap for .NET 7](https://github.com/dotnet/aspnetcore/issues/39504) in the _ASP.NET Web UI / Razor Compiler_ section?

**Comment by javiercn** [comment]
@boukenka this is a general limitation of the C# compiler. It cannot infer the `TTT` from the `Func<Task<IEnumerable<Test>>` being passed in.
