### ISSUE TITLE
Blazor wasm PWA runs under LAN and there is no installation icon button

### ISSUE THREAD

**Issue by NJadeRabbit** [dotnet/aspnetcore#39222]
### Describe the bug

![e12af2dcfb84f4743c9e580b65997e5](https://user-images.githubusercontent.com/48701698/147640397-b3049541-d9cd-4524-93d1-2a57819a4bc1.png)
```
WLAN adapter WLAN:
   IPv4 Address . . . . . . . . . . . . : 192.168.0.98
```
Without localhost, I lost PWA The install icon button does not exist in the local WLAN IPV4.

### .NET Version

dotnet6

**Comment by blowdart** [comment]
"Blazor Wasm PWA cannot be accessed when running under non-localhost"

Please provide your `launchSetttings.json` file

In profiles you should have something like the following,

```json
  "profiles": {
    "WebApplication1": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://0:0:0:0:5164",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

When I use that application URL I see 

```
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5164
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\BarryDorrans\source\repos\WebApplication1\WebApplication1\
```

The listening line is different. I also had to tell Windows to allow connections through the firewall once I started listening on all IP addresses

**Comment by NJadeRabbit** [comment]
Ok. Thank you for your reply.
My firewall has been turned off.

"Blazor Wasm PWA cannot be accessed when running under non-localhost"
Is the LAN inaccessible? Blazor Wasm PWA 

"applicationUrl": "http://0:0:0:0:5003", =》0:0:0:0:5003 ❓
"applicationUrl": "http://0.0.0.0:5003", =》0.0.0.0:5003 ✔
```
{
  "profiles": {
    "BlazorApp1.Server": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://0.0.0.0:5003",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```


> “在非本地主机下运行时无法访问 Blazor Wasm PWA”
> 
> 请提供您的`launchSetttings.json`文件
> 
> 在配置文件中，您应该具有以下内容，
> 
> ```json
>   “配置文件”：{
>      “WebApplication1”：{
>        “commandName”：“项目”，
>        “dotnetRunMessages”：true，
>        “launchBrowser”：true，
>        “applicationUrl”：“ http://0:0:0:0:5164 ”，
>        “环境变量”：{
>          “ASPNETCORE_ENVIRONMENT”：“开发” 
>       } 
>     }
> ```
> 
> 当我使用该应用程序 URL 时，我看到
> 
> ```
> Building...
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://[::]:5164
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Development
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: C:\Users\BarryDorrans\source\repos\WebApplication1\WebApplication1\
> ```
> 
> 听音线不一样。一旦我开始侦听所有 IP 地址，我还必须告诉 Windows 允许通过防火墙进行连接

**Comment by NJadeRabbit** [comment]
> "Blazor Wasm PWA cannot be accessed when running under non-localhost"
> 
> Please provide your `launchSetttings.json` file
> 
> In profiles you should have something like the following,
> 
> ```json
>   "profiles": {
>     "WebApplication1": {
>       "commandName": "Project",
>       "dotnetRunMessages": true,
>       "launchBrowser": true,
>       "applicationUrl": "http://0:0:0:0:5164",
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     }
> ```
> 
> When I use that application URL I see
> 
> ```
> Building...
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://[::]:5164
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Development
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: C:\Users\BarryDorrans\source\repos\WebApplication1\WebApplication1\
> ```
> 
> The listening line is different. I also had to tell Windows to allow connections through the firewall once I started listening on all IP addresses

Ok. Thank you for your reply.
My firewall has been turned off.

"Blazor Wasm PWA cannot be accessed when running under non-localhost"
PWA cannot be used in local area network?? Blazor Wasm PWA 

```
WLAN adapter WLAN:

   IPv4 Address . . . . . . . . . . . . : 192.168.3.87
```
visit http://192.168.3.87:5003/
![UD3KZVP 2@4}@941N1T_{EV](https://user-images.githubusercontent.com/48701698/147673419-86f041e8-ec60-4c81-8a3c-b0f0c06c825a.png)


"applicationUrl": "http://0:0:0:0:5003", =》0:0:0:0:5003 ❓
"applicationUrl": "http://0.0.0.0:5003", =》0.0.0.0:5003 ✔
```
{
  "profiles": {
    "BlazorApp1.Server": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://0.0.0.0:5003",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
Operation results.
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:5003
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\20178\source\repos\BlazorApp1\BlazorApp1\Server\
```

**Comment by blowdart** [comment]
What do you mean with the red box here? The icon you see in the address bar does not indicate a PWA, and a PWA will work in a local area network quite happily?

**Comment by NJadeRabbit** [comment]
> What do you mean with the red box here? The icon you see in the address bar does not indicate a PWA, and a PWA will work in a local area network quite happily?

The project is new, but the address has been changed to. http://0.0.0.0:5003

The red box is accessed in the LAN and I lost the installation icon button. There is an installation icon under localhost.

Can this installation icon be used in the LAN? I can't use it in a LAN.



I'm very upset. I want to create a gadget with blazor wasm PWA in the LAN for my team to use. Even use this tool in an offline environment.

Is there a good and simple way for me to do it?

**Comment by NJadeRabbit** [comment]
![image](https://user-images.githubusercontent.com/48701698/147720563-de7f25d0-0def-4e72-b309-fc1cddebd59e.png)
I opened the console and found。

192.168.0.98/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://192.168.0.98:7004/') with script ('https://192.168.0.98:7004/service-worker.js'): An SSL certificate error occurred when fetching the script.

**Comment by NJadeRabbit** [comment]
localhost
![image](https://user-images.githubusercontent.com/48701698/147720916-b05c6b39-2aa4-46b3-b94a-d62331919815.png)
LAN
![image](https://user-images.githubusercontent.com/48701698/147720938-67232d5b-384d-4a32-b2a9-70d7ba5df15a.png)

I opened the console and found.
I found a problem

**Comment by NJadeRabbit** [comment]
Https Much better
Missing service-worker.js manifest.json   , because of SSL?
Can LAN solve it
![image](https://user-images.githubusercontent.com/48701698/147727297-14a3e46a-8ffb-4249-8e31-1db7165db0c8.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This doesn't seem to be related to Blazor. You will probably be able to get help on [StackOverflow](https://stackoverflow.com) so we recommend posting your question there.
