### ISSUE TITLE
The configuration does not work to avoid circular reference in minimal api

### ISSUE THREAD

**Issue by DnarvaezCode** [dotnet/aspnetcore#39220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The configuration does not work to avoid circular reference in minimal api

### Expected Behavior

The configuration does not work to avoid circular reference in minimal api

### Steps To Reproduce

[APIFacturaV1.zip](https://github.com/dotnet/aspnetcore/files/7786770/APIFacturaV1.zip)

### .NET Version

6.0.100

### Anything else?

![image](https://user-images.githubusercontent.com/82119553/147615414-bc7f463f-ecd9-44f7-ba62-96d044138ce4.png)
![image](https://user-images.githubusercontent.com/82119553/147615477-2c5482ae-f3e4-49cb-b698-1eeedf21e7a9.png)
![image](https://user-images.githubusercontent.com/82119553/147615494-61162a72-50f9-41a9-b370-c3dc4c900337.png)
![image](https://user-images.githubusercontent.com/82119553/147615576-042d5c9a-7736-4d87-931b-38b22c1b2f2d.png)

**Comment by rafikiassumani-msft** [comment]
@DnarvaezCode Can you try the following configuration ? 

``` c#
  builder.Services.AddControllers().AddJsonOptions(x => x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve);
```

Also, creating `DTOs` may help you avoid some of the cycles with your request/response POCOs.

**Comment by DnarvaezCode** [comment]
If I use DTOs, this configuration is not necessary 
builder.Services.AddControllers().AddJsonOptions(x => x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve); But otherwise if DTOs are not used the circular reference configuration does not work in the minimal api.

**Comment by rafikiassumani-msft** [comment]
@DnarvaezCode DTOs have other design advantages.  However, let me clarify: Would you like to ignore circular references or preserve and handle them? 

See below for further documentation which provides guidelines on how to ignore or preserve circular references:  https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-preserve-references?pivots=dotnet-6-0

**Comment by pranavkm** [comment]
@DnarvaezCode for a minimal action you'll need to configure a different `JsonOptions` instance in the framework. `AddJsonOptions` that you currently are configuring only affects JSON serialization for controllers. See https://docs.microsoft.com/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#customize-json-binding
