### ISSUE TITLE
In ServerPrerendered mode, how to cache Html after Blazor rendering is complete?

### ISSUE THREAD

**Issue by linqingfeng** [dotnet/aspnetcore#39225]
Hi,

In ServerPrerendered mode, how to cache Html after Blazor rendering is complete?

Refer to #14828, I tried to test with the following code, but it was unsuccessful.

```
<cache expires-after="@TimeSpan.FromHours(4)" vary-by="@MY_KEY">
    <component type="typeof(App)" render-mode="ServerPrerendered" />
    <persist-component-state />
</cache>
```

This will cause the following error：

blazor.server.js:1 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at Tt._connectionClosed (blazor.server.js:1)
    at _t.Tt.connection.onclose (blazor.server.js:1)
    at _t._stopConnection (blazor.server.js:1)
    at bt.transport.onclose (blazor.server.js:1)
    at bt._close (blazor.server.js:1)
    at bt.stop (blazor.server.js:1)
    at _t._stopInternal (blazor.server.js:1)
    at async _t.stop (blazor.server.js:1)
    at async Tt.stop (blazor.server.js:1)
_connectionClosed @ blazor.server.js:1
Tt.connection.onclose @ blazor.server.js:1
_stopConnection @ blazor.server.js:1
transport.onclose @ blazor.server.js:1
_close @ blazor.server.js:1
stop @ blazor.server.js:1
_stopInternal @ blazor.server.js:1
await in _stopInternal (async)
(anonymous) @ (index):617

How can I cache the rendered Html? Thank you so much!

**Comment by pranavkm** [comment]
Each Blazor circuit is unique per user connection (not session) and the rendered HTML includes circuit specific metadata. Unfortunately, you're not going to be able to cache the output of a ServerPrerendered component.
