### ISSUE TITLE
Passing IEnumerable FromBody  vs FromQuery

### ISSUE THREAD

**Issue by yongkeecho** [dotnet/aspnetcore#39234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My API endpoint works with FromQuery.

**POST api?ids=id1&ids=id2**

```
public async Task<ActionResult<IEnumerable<string>> Post([FromQuery] IEnumerable<string> ids)
{
    return  ids == null ? BadRequest() : Ok(ids);
}
```
But with FromBody, ids are always null

**POST api**
`[ "id1", "id2"]`
```
public async Task<ActionResult<IEnumerable<string>> Post([FromBody] IEnumerable<string> ids)
{
    return  ids == null ? BadRequest() : Ok(ids);
}
```

Isn't this a bug?

### .NET Version

.NET 6

**Comment by pranavkm** [comment]
This works fine for me: https://github.com/pranavkm/repro/blob/model-binding/Controllers/WeatherForecastController.cs#L9-L13

```
> curl ttps://localhost:7217/test -X POST -H "Content-Type: application/json" --data-raw "[\"test1\", \"test2\"]"
["test1","test2"]
```

Do you have a minimal app that reproduces the issue?

**Comment by yongkeecho** [comment]
My bad. FromBody works fine for non-OData endpoint. For OData endpoint, `Post` expects a specific data type; fails to deserialize JSON as IEnumerable<string>.
