### ISSUE TITLE
Microsoft.AspNetCore.Http.DefaultHttpContext)HttpContext). Session

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39233]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftAspNetCoreHttpDefaultHttpCon/1611993)._

---
[severity:I'm unable to use this version]
Hi,

I'm starting using VS2022 with Net 6.0 and trying to update a solution received the message:

'((Microsoft.AspNetCore.Http.DefaultHttpContext)HttpContext). Session' threw an exception of type 'System.InvalidOperationException'

when the code line:

HttpContext.Session.SetString("Sesionid", DateTime.Now.ToString() + m_usuario.ID.ToString());

is executed, could you help me please, it works fine on Net 5.0

Thanks.

---
#### Feedback Bot on 12/13/2021, 07:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sebastienros** [comment]
I can't repro the issue on .NET 5 or .NET 6. What I can repro however is the same exception if the Session middleware is registered after the handler that used the session:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Session has not been configured for this application or request.
         at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
```

Which means you probably called `app.UseSession();` too late. Try moving it before `UseMvc()` or `UseEndpoints` like this:

```c#
    app.UseStaticFiles();  
  
    app.UseSession();  
  
    app.UseMvc(routes =>  
    {  
        routes.MapRoute(  
            name: "default",  
            template: "{controller=Home}/{action=Index}/{id?}");  
    });  
```
