### ISSUE TITLE
HttpClient functionality difference between VS 2019 and VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39232]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HttpClient-functionality-difference-betw/1617516)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10.2]
Hi,

We have an Android app that is listening on port 1338 for commands relating to printing, this uses HttpListener.
We have a Blazor client/server solution that makes calls to this port using

`Task.Run(() => Http.PostAsync(@"http://192.168.1.111:1338/setup", content). Wait());`

where content is data we want to pass over.

In Visual Studio Community 2019 16.10.2 the data can be passed over (communication works fine, the app receives the callback).
In Visual Studio Community 2022 17.0.2 the Android app no longer receives a callback despite using the same communication method.

Something has broken between these two versions.

Can you shed some light on this? This is a bit of a show-stopper.

Richard

---
#### Feedback Bot on 12/20/2021, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@TanayParikh can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Looks like I have missed the fact that this is a Xamarin app. Closing and will reopen the original Feedback ticket and move it to the Xamarin team to investigate.
