### ISSUE TITLE
Blazor\Razor components: @layout in component do not work for Html.RenderComponentAsync in cshtml

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39230]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BlazorRazor-components:-layout-in-comp/1610773)._

---
Hi, I have following problem with razor components in prerendering mode: 
@layout annotation do not work 

Steps to reproduce: 
1) create new .NET 6 web app 
2) create layout component Layout.razor with content:
@Inherits LayoutComponentBase
1
@Body

 3) create component Component.razor with content 
@layout Layout
2

4) add following line somewhere in index.cshtml: @(await Html.RenderComponentAsync(RenderMode.Static)) Actual render result:
2

rendered as result Expected render result:
1
2

It makes prerendering mode useless, because I'm not able to prerender page

---
#### Feedback Bot on 12/12/2021, 11:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Roma solved on 12/10/2021, 02:45 PM, 0 votes: 

<p>[Workaround]<br>
As as temporary workaround I was able to find:<br>
Component.razor:<br>
&lt;Layout&gt;<br>
&lt;Body&gt;<br>
&lt;div&gt;2&lt;/div&gt;<br>
&lt;/Body&gt;<br>
&lt;/Layout&gt;</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We'll wait to see see whether this is an issue more impacting others too and if so we'll investigate it then.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
