### ISSUE TITLE
Ability to load a local Blazor WASM application without a http server

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#39248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When publishing a Blazor WASM application, it will not load locally as the javascript framework initialization script (`blazor.webassembly.js`) uses `fetch` which when requesting via the `file` scheme, uses `origin: none`. Chrome fails to fufill the request with the following error `Fetch API cannot load /publish/wwwroot/_framework/blazor.boot.json. URL scheme "file" is not supported.`

Running a WASM application should not explicitly require a HTTP server to load resources from.

### Expected Behavior

I should be able to publish a Blazor WASM application and open `index.html` and have all of the resources loaded as `file://`

### .NET Version

.NET 6

**Comment by pranavkm** [comment]
You could look at https://docs.microsoft.com/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0#load-boot-resources to customize the bootstrapping and support non-HTTP urls. Personally I use https://www.nuget.org/packages/dotnet-serve to serve my published standalone blazor wasm app. That said, supporting this out of the box is a non-goal for us, so I'm marking this as resolved.
