### ISSUE TITLE
Call async method from non-async method in blazor web assembly

### ISSUE THREAD

**Issue by vrassouli** [dotnet/aspnetcore#39249]
I'm trying to develop an extensible application with Blazor WASM, which downloads plugins from server, and caches them at browser storage. Both downloading and caching APIs are async.

The following AssemblyLoadContext, is responsible to load plugin assemblies. As plugins may contain multiple assembly files, and as the project should support lazy loading of referenced assemblies, I'm handling the Resolving event as follow:

```
public class PluginAssemblyLoadContext : AssemblyLoadContext
{
    private readonly IPluginResolver? _pluginResolver;

    public PluginAssemblyLoadContext(string name) : this(name, null)
    {

    }

    public PluginAssemblyLoadContext(string name, IPluginResolver? pluginResolver) : base(name, isCollectible: true)
    {
        _pluginResolver = pluginResolver;

        if (pluginResolver != null)
        {
            Resolving += ResolveAssembly;
        }
    }

    protected override Assembly? Load(AssemblyName name)
    {
        return null;
    }

    private Assembly? ResolveAssembly(AssemblyLoadContext context, AssemblyName assemblyName)
    {
        try
        {
            var assembly = AssemblyLoadContext.Default.Assemblies.FirstOrDefault(x => x.GetName().Name == assemblyName.Name);

            if (assembly == null)
            {
                var task = _pluginResolver?.ResolveAsync(context, assemblyName);
                if (task != null)
                {
                    task.Wait();            // <- The problem!
                    assembly = task.Result; // <- The problem!
                }
            }

            if (assembly == null)
            {
                // TODO: Log...
            }

            return assembly;
        }
        catch (Exception ex)
        {
                // TODO: Log...
            throw;
        }
    }
}
```

The problem is that I can't call the async API from this method as it throws an exception telling "Cannot wait on monitors on this runtime." and I couldn't figure out how should I call them synchronously.

Thanks for any help

**Comment by pranavkm** [comment]
> and I couldn't figure out how should I call them synchronously.

You'll have to design the feature in a way that prefetches assemblies since blocking in WebAssembly is disallowed by the browser sandbox. Blazor WebAssembly ships with a lazy loading feature that might help with this - have you looked at it at all - https://docs.microsoft.com/aspnet/core/blazor/webassembly-lazy-load-assemblies?

I'm marking this issue as resolved since it's a question about designing your app. I'll recommend following up on StackOverflow with the blazor tag to reach a wider audience.
