### ISSUE TITLE
Segmentation fault in Docker ASP.NET core startup after .net6 upgrade

### ISSUE THREAD

**Issue by meghma** [dotnet/aspnetcore#39253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I upgraded to net6.0 and changed to mcr.microsoft.com/dotnet/sdk:6.0 in Dockerfile

Given below is the log at start up with segmentation fault that happens in the container but no issues running locally. Never had this issue in container with net3.1

```
Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory..ctor||Registered model binder providers, in the following order: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DateTimeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexObjectModelBinderProvider|
Segmentation fault
```

### Expected Behavior

Service should start up.

### Steps To Reproduce

Do not have a re-pro project.

### .NET Version

6.0.101

### Anything else?

Docker file  excerpts:

FROM ...dotnet/sdk:6.0 AS build

FROM ...dotnet/aspnet:6.0

**Comment by Pilchie** [comment]
Can you turn up the verbosity of the logging?  What about capturing a core dump of the seg fault so we can see a stack?

**Comment by meghma** [comment]
Hi @Pilchie 
With the help of our devops team we found the root cause to be https://github.com/dotnet/runtime/issues/60906
We copied NetSecurityNativeFix.cs class provided by danielsrenwick and used as the first line in the Main method:
NetSecurityNativeFix.Initialize();

But I really hope, this workaround can be replaced by a robust solution.

**Comment by Pilchie** [comment]
Thanks for letting us know. I'm going to close this as I believe it's tracked by dotnet/SqlClient#1390, and there is nothing for us to do here.

(I can't speak to the robustness of the workaround that you have unfortunately, that would be better off followed up on one of those issues).
