### ISSUE TITLE
Snapshot debugging encountered error of a referenced type which isn't available

### ISSUE THREAD

**Issue by Elvis254** [dotnet/aspnetcore#39267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The snapshot debugging is giving out this error:

`[12:04:25] Error: Failed to load user options: 'Unexpected type: Microsoft.VisualStudio.ProductionDebug.SnapshotDebuggerSolutionUserOptions'.`

whenever I load my project solution.

### Expected Behavior

Visual studio enterprise 2019 was not giving me this error, but 2022 is doing it.

### .NET Version

5.0.13

### Anything else?

ASP.NET Core version: 5.0.13
IDE: Visual Studio 2022 Enterprise

**Comment by hoseinprg** [comment]
@Elvis254 
 Try repairing your Visual Studio installation and see if the problem still repros

**Comment by Elvis254** [comment]
@hoseinprg I have done it but nothing has changed the error is still reproducing...

**Comment by pranavkm** [comment]
Could you use the [VS Feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) to report this issue? Thanks!

**Comment by Elvis254** [comment]
@pranavkm okay...!
