### ISSUE TITLE
Adding Microsoft.AspNetCore.Identity.UI to .Net 6 Blazor Webassembly Shared project causes build Error

### ISSUE THREAD

**Issue by patrickwensel** [dotnet/aspnetcore#39263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I add a reference to Microsoft.AspNetCore.Identity.UI to the Shared project, I get the following error:

Error NETSDK1082 There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'. WaterWithdrawl.Client C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets 427

I did not change anything from the Visual Studio .Net 6 Blazor Assemble Template

### Expected Behavior

Build without errors

### Steps To Reproduce

Create a new Blazor Webassembly App

![image](https://user-images.githubusercontent.com/3652914/147869712-ecc2761a-01f3-419b-9aef-40380b923d5b.png)

![image](https://user-images.githubusercontent.com/3652914/147869716-2c541335-c2cf-4beb-a15f-40bab3f74b78.png)

Authentication Type: Individual Accounts

![image](https://user-images.githubusercontent.com/3652914/147869721-141caf3d-695a-4f9a-b3ca-aaa4dee1a257.png)

Add Microsoft.AspNetCore.Identity.UI to Shared Project

![image](https://user-images.githubusercontent.com/3652914/147869724-b57a7d8f-ac76-47ce-9bb4-7a80db965970.png)

Build

![image](https://user-images.githubusercontent.com/3652914/147869726-ff8935ee-d8bb-4220-92d4-5ba68db99566.png)

### .NET Version

6.0

**Comment by patrickwensel** [comment]
I was trying to move my ApplicationUser object to my Shared project.  Microsoft.AspNetCore.Identity.UI is not needed to reference Identity in the Shared project, you only need Microsoft.AspNetCore.Identity.EntityFrameworkCore.  Do you want to close this?

**Comment by hoseinprg** [comment]
look at this:
https://github.com/dotnet/aspnetcore/issues/27738

**Comment by patrickwensel** [comment]
I am ok with you closing the issue because there was a simple solution but the article you sent did not seem to address the issue.

**Comment by pranavkm** [comment]
Identity UI depends on the ASP.NET Core shared framework that cannot be referenced from a blazor wasm app. By adding it to the shared project, you're adding a transitive reference to the ASP.NET Core shared framework which is what produces the error.

**Comment by patrickwensel** [comment]
That is more helpful to the next person that reads it but can you explain it a little more clearly. For example: Why can't a "Identity UI depends on the ASP.NET Core shared framework that cannot be referenced from a blazor wasm app"
