### ISSUE TITLE
Use Date Pipe for Angular Client

### ISSUE THREAD

**Issue by giuliohome** [dotnet/aspnetcore#39274]
You should be using a [date pipe](https://angular.io/api/common/DatePipe) in fetch-data.component.html at [line 18](https://github.com/dotnet/spa-templates/blob/main/src/content/Angular-CSharp/ClientApp/src/app/fetch-data/fetch-data.component.html#L18), the fix is shown below

```html
    <tr *ngFor="let forecast of forecasts">
      <td>{{ forecast.date | date }}</td>
```
or complete with time part
```html
    <tr *ngFor="let forecast of forecasts">
      <td>{{ forecast.date | date :'medium' }}</td>
```

It looks quite better - either just a date

![image](https://user-images.githubusercontent.com/3272563/134780546-74679658-13ea-47bc-82a8-88c2223d5feb.png)

or date and time -

![image](https://user-images.githubusercontent.com/3272563/134780720-bd98be6e-6173-49a6-8bbc-1af25ccc54f6.png)

than the original vanilla version in ISO format

![image](https://user-images.githubusercontent.com/3272563/134780580-ef33f3bc-a81a-4ca7-b53a-278fd1f01fa9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @giuliohome feel free to send us a PR with the proposal.
We'll get someone to review it next week.

**Comment by giuliohome** [comment]
At the moment I'm experiencing an issue with https and angular proxy: since it seems [locked/limited]((https://github.com/angular/angular-cli/issues/4322)) in angular and unrelated to this specific issue here, I ignore it (*) by omitting the first htts url from applicationUrl in launchSettings.json and I proceed with the test of this PR.

(*) I will open a different issue for this, just in case it will be needed... I read that you recently introduced this [new proxy approach](https://github.com/dotnet/aspnetcore/pull/31564)... At the moment I don't know why it doesn't work for me, so, again, I detour it for now.

**Comment by mkArtakMSFT** [comment]
Thank you for your effort.
As you may have seen already, we have decided to remove the SPA project templates from the .NET 8 SDK. As a result, we will not be taking any new changes here for non-servicing related needs.
