### ISSUE TITLE
Idea on improving WebAssembly Performance

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#39277]
I notice a serious issue that makes webassembly too slow for all cases.
I noticed in the app razor file (componeny), the code is something like this.

```
<Router AppAssembly="@GetType().Assembly">
```

The problem is the GetType.Assembly is too slow since it uses reflection.
Reflection is always too slow for webassembly.
I think there should be a better way (even using source generators) for specifying what assembly to use with no reflection to improve speed on that part.

**Comment by pranavkm** [comment]
Thanks for the suggestion @musictopia2. Using reflection more sparingly is something we're looking at since it doesn't play well trimming / AOT.
