### ISSUE TITLE
Using mvcBuilder.AddRazorRuntimeCompilation() causes slow first page load when porting asp.net core from .net 5 to .net 6

### ISSUE THREAD

**Issue by Fulgan** [dotnet/aspnetcore#39272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have ported my application from asp.net core 5.0 to asp.net core 6.0 (following the [recommended steps](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio) but keeping the .net core 5 hosting model) and I'm having a problem in dev: the initial load time of pages in the new version is very slow.

I have more or less pitpointed the issue to the use of Razor Runtime compilation:

            IMvcBuilder mvcBuilder = services
                .AddControllersWithViews()
                .AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.Suffix)
                .AddDataAnnotationsLocalization(option =>
                {
                    option.DataAnnotationLocalizerProvider = (type, factory) => factory.Create(typeof(SharedResource));
                })
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.PropertyNamingPolicy = null;
                })
                .AddFluentValidation();

            if (environment.IsDevelopment())
            {
                mvcBuilder.AddRazorRuntimeCompilation(); // commenting out this line resolves the issue
            }

When the line is present, initial load for all pages takes up to 30 seconds (typically, the first page takes 30 seconds and other pages are often quicker).

If I comment out the option, then everything works fine again. This is clearly not a problem in production but it's really problematic (and frustrating) for developpement.

The problem is not present in asp.net core 5.0

Adding the AddRazorRuntimeCompilation option to a new .net 6.0 using the new hosting model) application seems to induce the same issue but I'm not sure because the compilation of pages in a nearly empty application is very quick.

### Expected Behavior

With the software configured as above, I expect the initial time required to display pages for the first time to be (roughly) equivalent to what it was under .net 5.0

### Steps To Reproduce

I cannot post our project code, unfortunately, but if necessary, I can do a remote to demonstrate the issue.

### .NET Version

6.0.101

### Anything else?

Using asp.net core version 6.0.1 in VS 2022 (17.0.4)

Output of dotnet --info:

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by hez2010** [comment]
I don't think you will need `mvcBuilder.AddRazorRuntimeCompilation()` in .NET 6 anymore, since you can just use `dotnet watch` to enable .NET 6 hot reload which doesn't require the `AddRazorRuntimeCompilation` approach.

**Comment by Fulgan** [comment]
> I don't think you will need `mvcBuilder.AddRazorRuntimeCompilation()` in .NET 6 anymore, since you can just use `dotnet watch` to launch your website with .NET 6 hot reload enabled during development, which doesn't require the `AddRazorRuntimeCompilation` approach. With .NET 6 hot reload, any changes made both in C# code and razor code will be applied immediately without needs of restarting the application.

Pardon me if I'm wrong but I don't think that work while debugging the application

**Comment by hez2010** [comment]
Hot reload works if you're debugging your app with Visual Studio or Rider. Visual Studio Code is not supported for now.

**Comment by Fulgan** [comment]
Hot reload kind of works but it's way less convenient for pages than razor compilation: it takes a lot longuer for the new page to be available and there is no way for the tester to actually know when the page has been refreshed except by hitting "refresh" and trying to figure out - often from the source code - if the version served is the new one or the old one.

By contrast, razor runtime page compilation is about 3 times faster and the user just has to refresh the page once: it will delay load until the compilation has finished.

Finally, hot reload seems to wreak havok with dynamic objects: from my test, the application will crash every 3 or 4 hot reload complaining about the viewbag's properties being unknown (in views and controllers untouched by the compilation)

**Comment by liangpeihui** [comment]
[https://github.com/dotnet/aspnetcore/issues/37359#issuecomment-1009573159](url)

**Comment by Fulgan** [comment]
Thank you, @liangpeihui Looks like you're right: my report is a duplicate of this one.
