### ISSUE TITLE
can't use @onchange inside RenderFragment, bind works

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#39288]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

 in the default Blazor demo I've isolated the problem to this:
```
@foreach (var forecast in forecasts)
{
    <tr>
        <td>
            @temp()(forecast)
        </td>
    </tr>
}

@code {
private Func<WeatherForecast, RenderFragment> temp()
{
    return (forecast) => @<input type="text" @onchange="@(e => { })"/>;
}
}
```
### Exceptions (if any)

when trying to build it will give an error in the `razor.g.cs` file 
Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

### Expected Behavior

however `@bind="forecast.TemperatureC" ` works, 
I wanted to use `value` and `@onchange` instead of `@bind` because I need to bind the row to a dictionary

### .NET Version

5.0

### Anything else?

VS2019

**Comment by omuleanu** [comment]
I opened my solution in VS2022 and switched Target Framework to .net 6.0,
now it works

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and also for trying out .NET 6.
Closing as this now works in .NET 6 and there is no further action pending from our side.
