### ISSUE TITLE
ARM64 support for ASP.NET Core on IIS (ANCM)

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#39281]
Tracking issue for current plan:

- [x] CI: start Build arm64 ancm as part of main windows x64 build step [Draft PR](https://github.com/dotnet/aspnetcore/pull/38997)
- [x] CI: arm64 installer changes [Est. Preview 3] [Installable installers](https://github.com/dotnet/aspnetcore/pull/39523)
   - [x] Start with changes arm64 changes from https://github.com/dotnet/aspnetcore/pull/30680/files
- [ ] CI: arm64 test changes
   - [x] Get IIS tests running on helix on win arm64 queue (PR)[https://github.com/dotnet/aspnetcore/pull/39420] 
   - [ ] Need to get IIS installed on WinArm64 queues (issue)[https://github.com/dotnet/core-eng/issues/15334]
   - [x] IIS-Express support on arm64
     - [x]  [Need to insert new ancms + arm64 version of iisexpress](https://github.com/dotnet/aspnetcore-internal/blob/main/docs/release/InsertingANCMInToVisualStudio.md)
     - [x] Add new arm64 only manifest to install the arm64 msi in VS
   - [x] [Fix Integration csproj](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/IIS/IntegrationTesting.IIS/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj#L41)
   - [ ]  [Fix testsites.props](https://github.com/dotnet/aspnetcore/blob/0aec8b4490fcaef571931b5fe95d346467450d99/src/Servers/IIS/build/testsite.props#L23)
   - [x] [Reenable skip on arm tests](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/test/Identity.FunctionalTests/Microsoft.AspNetCore.Identity.FunctionalTests.csproj#L6) also AuthSamples functionals
   - [x] Add [CTI coverage](https://github.com/aspnet/Tooling-ManualTests/issues/1597)
- [x] Make actually stuff work
   - [x] Use host fxr, start from [PR](https://github.com/dotnet/aspnetcore/pull/10829)
   - [x] Msi installs on arm64
   - [x] InProc IIS +ANCM ARM64 working (manual msi + manual publish/setup)
   - [x] OutOfProc IIS +ANCM ARM64 working (manual msi + manual publish/setup) (currently crashes with Unhandled exception at 0x00007FFDF660A138 (aspnetcorev2_outofprocess.dll) in w3wp.exe: 0x80000002: Datatype misalignment. maybe https://blog.quarkslab.com/unaligned-accesses-in-cc-what-why-and-solutions-to-do-it-properly.html ?)
   - [x] Figure out how to remove ANCMv1 entries in IIS ARM64 applicationHost.config since those don't work on arm64 and stop IIS from running (currently looks like this is coming from VS chaining in old ANCMv1 installers, might not require any changes on our end)
- [ ] Developer productivity/VS/build cleanup
   - [x] i.e. update vs json files from https://github.com/dotnet/aspnetcore/pull/30680/files
   - [x] Do we still need the hand added assets.props temp items in https://github.com/dotnet/aspnetcore/commit/cb32de3910e93ae1a7d406acdfc9f6b8d41c9090#diff-9585fee44fcd04a01abfb8d0b31f73b3577655e66c07a3d1b3074cabf8f55bf3 that got lost (no after confirming with brennan)
   - [ ] Revert always building against release in native projects once we have a debug version of libnethost
   - [ ] Try to remove asp net copy of fx_ver (linker issues only in debug Win32/x86)
   - [ ] Try to use runtime version of [ends_with](https://github.com/dotnet/runtime/blob/df69293bdbe75bf5903583c472fcd257119dbda4/src/native/corehost/hostmisc/utils.cpp#L32)
   - [ ] Do we need emulation support from joeloff: Definitely ask IIS team. just like hosting both x86 and x64 app pools someone might want to host arm64 and x64 app pools on the same machine. There was a pretty big drive late in .NET 6 around x64 emulation on arm64

**Comment by snickler** [comment]
The new Windows Insiders Dev Channel Build 22563 contains IIS! 

https://twitter.com/sinclairinat0r/status/1496932123894288384

**Comment by HaoK** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/42392 for tracking the helix queue
Filed https://github.com/dotnet/aspnetcore/issues/42393 to track the misc cleanup items

**Comment by adityamandaleeka** [comment]
Woohoo!
