### ISSUE TITLE
Unable to get library fully installed

### ISSUE THREAD

**Issue by BrandonH333** [dotnet/aspnetcore#39292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not that great with C++ but following the instructions, I'm missing something for sure.  I need to get SignalR running on the client side in C++ for a school project but I'm installing the libraries directly from the nuget package and it is not able to find the following source files:

#include "signalrclient/hub_connection_builder.h"
#include "signalrclient/signalr_value.h"

Currently trying to test this out in a C++ console app first.  I cloned this library and performed the build steps in Windows, although, idk how that will include the missing source files above based off the examples provided in the instructions.

Any tip would be appreciated.

**Comment by BrennanConroy** [comment]
> I'm installing the libraries directly from the nuget package

There aren't any nuget packages. What specifically are you trying?

**Comment by BrandonH333** [comment]
I'm trying the example usage here: 
https://github.com/aspnet/SignalR-Client-Cpp#example-usage

**Comment by BrennanConroy** [comment]
Ok, did you first build the library successfully? How are you referencing the built library? Is the include folder part of your include path so signalr_value.h and hub_connection_builder.h can be found?

**Comment by BrandonH333** [comment]
Yes I built it successfully however, there is no reference to this library so I'll dig into how I can reference an external project.  Thanks for the help.
