### ISSUE TITLE
Runtime dependencies are out of date

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#39294]
We're 8 days behind runtime dependencies. The runtime update PR has been failing in the Blazor e2e tests for the past week. The failure appears to be related to [recent runtime change](https://github.com/dotnet/runtime/commit/00c169230672b48ff2c77df9ac18aeae0a55ee6a)

Here's the exception:

```
Unhandled exception rendering component: Could not resolve type with token 010000fa from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
System.TypeLoadException: Could not resolve type with token 010000fa from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
   at Microsoft.AspNetCore.Components.ComponentBase.\u003C.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by pranavkm** [comment]
FYI @jkotas

**Comment by jkotas** [comment]
These types of errors are typically caused by manually mixing old .NET runtime binaries and new .NET runtime binaries in a single setup.

Where are these tests getting the .NET runtime binaries from?

**Comment by sebastienros** [comment]
Might have been blocked by the SDK not being up-to-date. The PR passed.
