### ISSUE TITLE
Receiving [Browserslist] Could not parse <ProjectDirectory>/ClientApp/package.json when using ASP.NET+React.js template

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39309]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Receiving-Browserslist-Could-not-parse/1573522)._

---
[severity:I'm unable to use this version]
I have tried creating a sample project using the ASP.NET+React.js template in Visual Studio 2019 for Mac but keep encountering the following error when trying to launch the app: 

```
AggregateException: One or more errors occurred. (One or more errors occurred. (The npm script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: [Browserslist] Could not parse <ProjectDirectory>/ClientApp/package.json. Ignoring it. ))

System.Threading.Tasks.Task<TResult>. GetResultCore(bool waitCompletionNotification)
System.Threading.Tasks.Task<TResult>.get_Result()
Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout<T>(Task<T> task, TimeSpan timeoutDelay, string message)
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task<Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)
Microsoft.AspNetCore.Builder.SpaProxyingExtensions+<>c__DisplayClass2_0+<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This occurs in both .NET Core 3.1 and .NET 5.0, Node and NPM version output is as follows:

```
node --version
v17.0.1

npm ---version
8.1.0
```

Given the exception, I tried changing the following in package.json from this:

```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
}
```

To this:

```
"browserslist": [
      ">0.2%",
      "not dead",
      "not op_mini all"
]
```

However, this had no impact. Additionally, I tried executing the following command from the ClientApp directory:

`npx browserslist --update-db`

This still did not resolve the issue. I have a clean install of Node and this issue happens regardless of .NET versions. If anyone could help with this, it would be greatly appreciated. 

Thanks

---
#### Feedback Bot on 11/7/2021, 11:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/16/2021, 02:12 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by konak** [comment]
Hi !
I have faced the same issue ...
I have just created a ReactJS project in Visual Studio for Mac.
Project is attached.

[ldk-demo.zip](https://github.com/dotnet/aspnetcore/files/7914287/ldk-demo.zip)

**Comment by konak** [comment]
Found out that 403 error becomes after updating Mac OS to Monterey ... It has started using port number 5000 (default port of .net web applications) ... So Mac users should change port of application just after creating it.

**Comment by jakerutter** [comment]
I, too am experiencing the same problem. All roads have led me back to this thread, so I think there is an ongoing issue.

**Comment by q-omar** [comment]
Experiencing same issue. The relevant bit for my package.json looks like:

 "resolutions": {
    "url-parse": ">=1.5.0",
    "lodash": ">=4.17.21"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]

![Screen Shot 2022-01-26 at 11 39 28 AM](https://user-images.githubusercontent.com/25255233/151225938-13efe160-b7a1-4f9b-9984-67244e016772.png)

**Comment by q-omar** [comment]
> Experiencing same issue. The relevant bit for my package.json looks like:
> 
> "resolutions": { "url-parse": ">=1.5.0", "lodash": ">=4.17.21" }, "browserslist": [ ">0.2%", "not dead", "not ie <= 11", "not op_mini all" ]
> 
> ![Screen Shot 2022-01-26 at 11 39 28 AM](https://user-images.githubusercontent.com/25255233/151225938-13efe160-b7a1-4f9b-9984-67244e016772.png)

I copied the contents of package.json, deleted it, created a new file and pasted the contents. App began working then. I think there was some invisible character that was throwing off the parser 🤷‍♂️

**Comment by BrassHead** [comment]
The package.json file from the template was saved in "utf8 with BOM". The BOM causes parsing to fail. Removing the BOM (by creating a new file and copy paste the contents as suggested by @q-omar  or using some other tool) will fix the problem.

**Comment by konak** [comment]
Creating a new file in Visual Studio and making just copy / paste did not helped ... Only after I have created a file using vi in terminal it has worked.

Thanks for solution !

P.S.
Anyway there is an issue in SV for Mac on creating config file.

**Comment by gbulicanu** [comment]
I resolved this form me by editing .env file:
```
BROWSER=chrome
```
