### ISSUE TITLE
Blazor Web Assembly - Debugger crashes on VS 2022 after OIDC redirect

### ISSUE THREAD

**Issue by GiannhsR** [dotnet/aspnetcore#39301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When pressing F5 on a Blazor WASM application, after the OIDC redirection to the login page of the IdP the application crashes throwing the following exception,

### Expected Behavior

Debugger working as normally.
Application not crashing.

### Exceptions (if any)

```
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]::Run:
 Exception System.AggregateException: One or more errors occurred.
```

### .NET Version

.NET 6

### Anything else?

Visual Studio 2022
Version 17.0.4

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
@thaystg can you please take a look at this? Thanks!

**Comment by mkArtakMSFT** [comment]
@thaystg also, if you need any input from us, please let us know.

**Comment by thaystg** [comment]
I think this is already fixed, could you please tell me the dotnet version that is being used? Also the version of this package:
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.0" />

**Comment by GiannhsR** [comment]
@thaystg Hello, the dotnet version that is being uses is .NET 6.

Also, the Blazor WASM application isn't hosted anywhere so the aforementioned package does not exist.

**Comment by thaystg** [comment]
And these packages? Which version are you using?
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0" PrivateAssets="all" />
```

**Comment by GiannhsR** [comment]
![image](https://user-images.githubusercontent.com/18198166/148245457-09f423fa-f4ac-43b1-a793-80a14cb2401d.png)

**Comment by thaystg** [comment]
I was asking that questions because I have already fixed something related with OIDC before: https://github.com/dotnet/runtime/issues/60613#issuecomment-946999702

But it looks like it's not the same case.

Can you help me to reproduce it? Like sharing a code that reproduces it?
When you say that the application crashes, is Chrome that is crashing? Which version of chrome are you using?

**Comment by GiannhsR** [comment]
Updating with the full exception that I am getting:
![image](https://user-images.githubusercontent.com/18198166/148507911-546093a6-07ff-401c-a0fb-5e1f96b493d5.png)

> When you say that the application crashes, is Chrome that is crashing? Which version of chrome are you using?

The process that runs the Blazor wasm application crashes and as a result, since I am I have `"launchBrowser": true`  in my launchSettings.json, Chrome stops running too.

The version of Chrome is : 97.0.4692.71

**Comment by GiannhsR** [comment]
>if you run using the option "Start Without Debugging" it works correctly?

Yes, launching the application through "Start Without Debugging" works as expected.

**Comment by thaystg** [comment]
Can you please attach the Log that you can find at:
`C:\Users\[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt`

**Comment by GiannhsR** [comment]
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/7844362/visualstudio-js-debugger.txt)

This is the generated log exactly after the application loaded with the aforementioned exception.
