### ISSUE TITLE
SignalR Core StartAsync() CancellationToken not respected?

### ISSUE THREAD

**Issue by AHComp** [dotnet/aspnetcore#39315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After invoke the canselationtokensource.cancel() nothing happens.
StartAsync() will wait until an Timeout is thrown or the connection succeeds.
The timeout needs over 60 sec.
If port number is wrong is needed to cancel the current connection and reconnect with other credentials.
It is not usable to wait for the timeout.

2019 was allready a bug to  topic [#10059](https://github.com/dotnet/aspnetcore/issues/10059)

### Expected Behavior

StartAsync() should throw an OperationCancelledException after few second. Any negotiation or handshake should be aborted if it was not already successfully completed within few second.

### Steps To Reproduce

                    Connection = new HubConnectionBuilder()
                        .WithUrl(serverUrl, options => SetHttpConnectionOptions(options))
                        .WithAutomaticReconnect(new EsiRetryPolicy())
                        .AddNewtonsoftJsonProtocol() // Perhaps we have some trouble with this check client side implementation for date converting
                        .Build();

### Exceptions (if any)

```
[data.esi.mobil] Explicit concurrent copying GC freed 3123(208KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4404KB/8808KB, paused 557us total 5.503ms
[data.esi.mobil] Explicit concurrent copying GC freed 3(16KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4404KB/8808KB, paused 268us total 4.605ms
Wait for disconnecting
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[10]
      Failed to start connection. Error getting negotiation response from 'http://192.168.178.2:15337/EsiSuite/EsiSuiteClientHub'.
      System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.Net.Sockets.SocketException: Connection timed out
        at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x000c8] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:65 
         --- End of inner exception stack trace ---
        at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00180] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:84 
        at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
        at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ea] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:385 
        at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
        at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:543 
        at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
        at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x0003f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:284 
        at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00070] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:32 
        at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ff] in <0ff77aac3a5348fa82d58cb6c49bd84c>:0 
        at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00095] in <0ff77aac3a5348fa82d58cb6c49bd84c>:0 
        at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:531 
        at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync (System.Uri url, System.Net.Http.HttpClient httpClient, Microsoft.Extensions.Logging.ILogger logger, System.Threading.CancellationToken cancellationToken) [0x00147] in <0ff77aac3a5348fa82d58cb6c49bd84c>:0 
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[5]
      Skipping dispose, connection is already disposed.
```

### .NET Version

6.0.1 &  .netstandard 2.0

### Anything else?

Signalr is in a assembly based on .netstandard 2.0
This assembly is used in a xamarin forms 5 project
The error ocourse in Android and iOS.

**Comment by BrennanConroy** [comment]
What version of the SignalR client are you using? The cancellation change you linked to applies to 3.0+.

**Comment by AHComp** [comment]
Newest 6.0.1 signalr.
All nuget packages are updated to the last available.
Also the newest xamarin forms.
I compile also on newest iOS and Android.

**Comment by BrennanConroy** [comment]
Are you able to reproduce the issue just using `HttpClient`?
```csharp
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
var handler = new HttpClientHandler();
// handler.Proxy etc. should be set here
var client = new HttpClient(handler);
client.Timeout = TimeSpan.FromSeconds(60);
// client.DefaultRequestHeaders.Add(..., ...);
using (var request = new HttpRequestMessage(HttpMethod.Post, "https://yourendpoint/negotiate"))
{
    request.Version = new Version(1, 1);

    using (var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cts.Token))
    {
    }
}
```

**Comment by AHComp** [comment]
Yes i can reproduce with you code !

![image](https://user-images.githubusercontent.com/35998144/148563130-1611b6d4-07ea-4f2e-9f46-05843602a4ac.png)

I add your snipped in my auth request section.

The result of the request is a exception after 3 minutes 180 seconds then : "One or more errors occurred. (A task was canceled.)"

Here the log:

`1/7/2022 3:01:59 PM
Thread started: <Thread Pool> #10
[HostConnection] HostConnection::get() New Host Connection established 0x7d3a3e03d210, tid 6632
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0x7d3a2e080c10: maj 3 min 0 rcv 3
[EGL_emulation] eglMakeCurrent: 0x7d3a2e080c10: ver 3 0 (tinfo 0x7d39ceeb3d90) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x7d3a3e0423d0, tid 6632
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3c3ffe000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Davey! duration=9218ms; Flags=1, IntendedVsync=218439527463738, Vsync=218440194130378, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=218440206530996, AnimationStart=218440206549796, PerformTraversalsStart=218440207991596, DrawStart=218448707847596, SyncQueued=218448725051496, SyncStart=218448726251196, IssueDrawCommandsStart=218448727334496, SwapBuffers=218448745465796, FrameCompleted=218448747125196, DequeueBufferDuration=296100, QueueBufferDuration=594200, GpuCompleted=0, 
[Choreographer] Skipped 512 frames!  The application may be doing too much work on its main thread.
Thread finished: <Thread Pool> #9
Der Thread 0x9 hat mit Code 0 (0x0) geendet.
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread finished: <Thread Pool> #11
Der Thread 0xb hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #12
Der Thread 0xc hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #2
Thread started: <Thread Pool> #14
Der Thread 0x2 hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #14
Thread started: <Thread Pool> #15
Der Thread 0xe hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #13
Der Thread 0xd hat mit Code 0 (0x0) geendet.
Thread started: <Thread Pool> #16
Thread started: <Thread Pool> #17
Thread started: <Thread Pool> #18
1/7/2022 3:04:09 PM`

Normaly after 10 seconds a exception should be raised !!! But like in the old issue the cancelationtoken will be ignored !

**Comment by AHComp** [comment]
Now i also checked in the wpf client.

`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<LangVersion>preview</LangVersion>
		<UseWPF>true</UseWPF>
		<RootNamespace>Esi.Bootstrap</RootNamespace>
		<StartupObject></StartupObject>
		<PackageId>Esi.Bootstrap</PackageId>
		<Authors>sidata.com GmbH</Authors>
		<Company>sidata.com GmbH</Company>
		<Product>Esi.Bootstrap</Product>
		<AssemblyName>Esi.Bootstrap</AssemblyName>
		<Platforms>AnyCPU;x64</Platforms>
		<Description>Startup, install and updatating tool for sidata MSAccess solutions</Description>
		<AssemblyVersion>3.1.11.3</AssemblyVersion>
		<FileVersion>3.1.11.3</FileVersion>
		<Version>3.1.11.3</Version>
	</PropertyGroup>`

Here the cancel token will be fired like expected !

I can NOT reproduce the bug on this plattform with the same code/assemblly.

**Comment by halter73** [comment]
HttpClient not respecting the CancellationToken appears to be a mono bug on Android. https://github.com/mono/mono/issues/19357

There's some more context at https://github.com/xamarin/Xamarin.Forms/issues/12986. It looks like you can possibly workaround this in general by using `Xamarin.Android.Net.AndroidClientHandler`, but SignalR does not make it super easy to replace the `HttpClientHandler` it uses.

**Comment by halter73** [comment]
Correction. You should be able to replace the `HttpClientHandler` using the `HttpMessageHandlerFactory`.

https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#configure-additional-options

E.g:

```csharp
var hubConnection = new HubConnectionBuilder()
    .WithUrl(url, options =>
    {
        options.HttpMessageHandlerFactory = handler =>
        {
            // TODO: Copy settings from the handler argument.
            return new Xamarin.Android.Net.AndroidClientHandler();
        };
    })
    .Build();
```

**Comment by AHComp** [comment]
On this place no Error occurs, the bug is the StartAsync()
Methode !!!

**Comment by halter73** [comment]
Did you try replacing the `HttpMessageHandlerFactory` on Android? I know there isn't an error when you build the `HubConnection`, but `StartAsync()` calls into the `HttpMessageHandler` with the `CancellationToken`, and it appears the default one is ignoring this `CancellationToken` on Android.

**Comment by AHComp** [comment]
On this place I have no access to Android the Code is in a separate assembly (.netstandard2.0)
The assembly is shared with many Clients.

**Comment by AHComp** [comment]
I try to implement a delegate for the factory tomorrow.
Then I can Set it from Plattform Level.

**Comment by AHComp** [comment]
The next question then is how I fix it in iOS ?

**Comment by halter73** [comment]
Possibly using [NSUrlSessionHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.nsurlsessionhandler?view=xamarinios-10.8) on iOS similar to how you'd use `AndroidClientHandler` on Android. You could change the default HttpMessageHandler using build options instead of changing the code if you want to change this globally and not just for SignalR. https://theconfuzedsourcecode.wordpress.com/2020/01/13/xamarin-forms-native-httpclienthandler-for-httpclient/

You can test whether changing the handlers fixes the issue directly using HttpClient with code similar to what @BrennanConroy suggested in https://github.com/dotnet/aspnetcore/issues/39315#issuecomment-1005939157 but with the platform-specific `handlers`.

**Comment by AHComp** [comment]
Sorry your idea are not working or i do something wrong !
I try in android first and fill the message service over the contructor with a object you told me !

`            LoadApplication(new App());

            var service = new MessageService(new Xamarin.Android.Net.AndroidClientHandler());
            DependencyService.RegisterSingleton<IMessageService<DataMessage>>(service);`

and fill it:

`        public MessageService(object httpMessageHandlerFactory)
        {
            _httpMessageHandlerFactory = httpMessageHandlerFactory;`

Then i try to use the new handler for the factory and the request:

`if (_httpMessageHandlerFactory != null)
                {
                    options.HttpMessageHandlerFactory = handler =>
                    {
                        // TODO: Copy settings from the handler argument.
                        return (HttpClientHandler)_httpMessageHandlerFactory;
                    };
                }

                if (AuthObject != null)
                    options.Cookies = (CookieContainer)AuthObject;
                else
                {
                    WrongCredentials = false;

                    HttpClientHandler handler = (HttpClientHandler)_httpMessageHandlerFactory ?? new HttpClientHandler();
                    handler.CookieContainer = new CookieContainer();
                    var client = new HttpClient(handler);
                    var uri = new Uri(EsiClient.ServiceUrl + "/esisuite/esiclient/authenticate");
                    var tokenResponse = client.PostAsJsonAsync(uri, EsiClient);
                    EsiClient = tokenResponse?.Result?.Content?.ReadAsJsonAsync<EsiClient>()?.Result ?? EsiClient;`

the result is a exception on var client = new HttpClient(handler); :

`Cannot access a disposed object.
Object name: 'SocketsHttpHandler'.`

**Comment by AHComp** [comment]
On Android it's working but on iOS i got the problem

`namespace Esi.Mobile.iOS.Service
{
    /// Contains methods for accessing
    /// local images on the file system
    public class HTTPClientService : IHTTPClientService
    {
        public HttpClientHandler GetHttpClientHandler()
        {
#if DEBUG
            var iosClientHandler = new NSUrlSessionHandler();
            iosClientHandler.TrustOverride += (sender, trust) =>
            {
                return true;
            };
            return iosClientHandler;
#else
            return new NSUrlSessionHandler();
#endif
        }
    }
}`

 that the NSUrlSessionHandler is a HttpMessageHandler and not a HttpClientHandler.
 
On the android side it works
`namespace Esi.Mobile.Droid.Services
{
    /// Contains methods for accessing
    /// local images on the file system
    public class HTTPClientService : IHTTPClientService
    {
        public HttpClientHandler GetHttpClientHandler()
        {
#if DEBUG
            return new CustomAndroidClientHandler();
#else
            return new AndroidClientHandler();
#endif
        }
    }
}`

 But i need access to the cookie container to save !

`options.HttpMessageHandlerFactory = httpMessageHandlerFactory =>
            {
                HttpClientHandler handler = HttpClientHandler;
                if (AuthObject != null)
                    handler.CookieContainer = (CookieContainer)AuthObject;
                else
                {
                    WrongCredentials = false;
                    try
                    {
                        var client = new HttpClient((HttpMessageHandler)handler);
                        var uri = new Uri(EsiClient.ServiceUrl + "/esisuite/esiclient/authenticate");
                        var tokenResponse = client.PostAsJsonAsync(uri, EsiClient, CancellationTokenSource.Token);
                        var result = tokenResponse.Result;
                        if (result != null && result.StatusCode == HttpStatusCode.OK)
                        {
                            EsiClient = result.Content?.ReadAsJsonAsync<EsiClient>()?.Result ?? EsiClient;
                            if (EsiClient.UpdateForce)
                            {
                                OnUpdateForce(this, EsiClient);
                            }
                            else
                            {
                                if (!string.IsNullOrEmpty(EsiClient.Token))
                                    OnToken(this, EsiClient.Token);
                                if (handler.CookieContainer != null)
                                {
                                    OnCookie(this, GetCookies(handler.CookieContainer));
                                }
                            }
                        }
                        else if (tokenResponse.Result.StatusCode == HttpStatusCode.BadRequest)
                        {
                            WrongCredentials = true;
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                }
                return handler;
            };`

**Comment by BrennanConroy** [comment]
https://stackoverflow.com/questions/51175748/using-cookiecontainer-with-nsurlsessionhandler

**Comment by AHComp** [comment]
Tis is not a solution i also found !!! I have no access from my assembly with .netstandrd 2.0

Why xamarin.ios not implement the default HttpClientHandler ?

**Comment by AHComp** [comment]
`public class CustomHttpMessageHandler : NSUrlSessionHandler, ICustomHttpMessageHandler
    {
        public CustomHttpMessageHandler()
        {
            TrustOverride += (sender, trust) =>
            {
                return true;
            };
            if (CookieContainer == null)
            {
                CookieContainer = new CookieContainer();
            }
        }
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var result = await base.SendAsync(request, cancellationToken);
            var cookieHeaders = result.Headers.Where(h => h.Key.Equals("Set-Cookie", StringComparison.InvariantCultureIgnoreCase)).ToList();
            foreach (var header in cookieHeaders)
            {
                if (header.Value != null)
                {
                    var cookieParts = header.Value.First().Split(';');
                    var cookieValue = cookieParts[0].Split('=');
                    if (CookieContainer != null)
                    {
                        CookieContainer.Add(new Cookie(cookieValue[0], cookieValue[1], "/", request.RequestUri.Host));
                    }
                }
            }        
            return result;
        }
    }`

I found the bug, the cookie container is always null and if i create in the contructor a new instance it will be filled in the background !

![image](https://user-images.githubusercontent.com/35998144/148999085-0e422ace-47d1-4f8e-8632-8b132b6bbd19.png)

so also without override the sendasync it works, it seams that iOS/xamarin will fill the cookiecontainer in the background ???

**Comment by halter73** [comment]
It makes sense to me that the default implementation of `NSUrlSessionHandler.SendAsync` would use its `CookieContainer` if set. If you want to make it work with cookies set via [HttpConnectionOptions.Cookies](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.client.httpconnectionoptions.cookies?view=aspnetcore-6.0), you'll want to copy the `CookieContainer` reference passed into the `HttpMessageHandlerFactory` via the original `HttpClientHandler`.

https://github.com/dotnet/aspnetcore/blob/c65dac77cf6540c81860a42fff41eb11b9804367/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs#L550-L552

SignalR uses an empty `CookieContainer` by default, so you shouldn't need to manually create one in the `CustomHttpMessageHandler` constructor if you do that.

**Comment by AHComp** [comment]
For me it makes no sense that their are difference between android and ios in xamarin. In android it's not neccessary to create a instance for cookie Container.
