### ISSUE TITLE
[BindNeverAttribute] is not respected during JSON model binding (JSON over-posting vulnerability)

### ISSUE THREAD

**Issue by BrendanRidenour** [dotnet/aspnetcore#39337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When POSTing (or PUTing) to an ApiController in JSON, all properties of a model are model bound, even those decorated with a BindNeverAttribute.

### Expected Behavior

I expect the BindNeverAttribute to apply to all model binding, no matter its format (JSON, XML, etc.).

### Steps To Reproduce

**See**: [Repro Project](https://github.com/BrendanRidenour/BindNeverJsonIssue)

1. Run the app
2. Use Swagger to post an IssueModel to "/issue" with any string as the Value property.
3. Model binding sets the IssueModel.Value even though that property is decorated with a BindNeverAttribute.

### .NET Version

.NET 6

**Comment by pranavkm** [comment]
BindNever only works for model binding and not for JSON / XML serialization as noted in our docs: https://docs.microsoft.com/aspnet/core/mvc/models/model-binding#attributes-for-complex-type-targets. 

You'll have to use the formatter specific gesture to skip serializing / deserializing a property e.g.

* System.Text.Json - [JsonIgnoreAttribute](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonignoreattribute)
* Newtonsoft.Json - [JsonIgnoreAttribute](https://www.newtonsoft.com/json/help/html/PropertyJsonIgnore.htm)
* XmlSerializer - [XmlIgnoreAttribute](https://docs.microsoft.com/dotnet/api/system.xml.serialization.xmlignoreattribute)

**Comment by BrendanRidenour** [comment]
I investigated the System.Text.Json.JsonIgnoreAttribute. However, this attribute blocks serialization on both deserialization AND serialization. This creates an issue because, to protect against over-posting, model binding must block properties from binding during deserialization, but then allow the property to be serialized back out for the result.

**Step 1**: A user POSTs to an endpoint to create a resource. Certain properties should not be bound to protect against over-posting. JsonIgnore will accomplish this.

**Step 2**: However, after the resource is created, the endpoint must return the newly created entity, including the properties blocked during POST. This is where JsonIgnore fails because any property marked with this attribute will also be blocked from serialization.

**Comment by pranavkm** [comment]
System.Text.Json also does not deserialize read-only properties or properties with private setters by default - https://github.com/dotnet/runtime/issues/29743. You could rely on that. In general though, our guidance is to use a view model to prevent over-binding, it's reliable regardless of how the model is being bound.
