### ISSUE TITLE
Requests using the absolute-form in the request line require the host to match

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#39335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are known clients that send the request with the full url in the request line, but then also include a malformed Host header that doesn't match. IIS/Http.Sys ignores the invalid host in this scenario, Kestrel rejects it.

### Expected Behavior

Ignore the invalid/mismatched Host header.

### Steps To Reproduce

```
GET http://www.foo.com/api/data HTTP/1.1
HOST: www.foo.comConnection: …
```

Produces a "400 Bad Request".

### .NET Version

6.0

**Comment by Tratcher** [comment]
Fixed for 6.0.2. It's not clear if we need this in 7.0, or if the customer will be able to resolve the client issue by then. I'm putting this in 7.0-planning to re-visit ~June 2022.

**Comment by adityamandaleeka** [comment]
@Tratcher Let's follow up on this one and close it if it's not needed on > 6.

**Comment by adityamandaleeka** [comment]
Reopening to consider for 7+.
