### ISSUE TITLE
Error BLAZOR102 when using CSS preprocessing

### ISSUE THREAD

**Issue by JohnKiller** [dotnet/aspnetcore#39344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Follow up of https://github.com/dotnet/aspnetcore/issues/38374 I've successfully managed to use [the documentation](https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/) to copy compiled files to the wwwroot folder using MSBuild.

Now I would like to do the same with Blazor scoped css, but every tutorial I've found just places the compiled CSS file inside the git repository instead of the recommended `obj/` folder.

I've update my repo here https://github.com/JohnKiller/TestCopyFile

Inside `RazorClassLibrary1/RazorClassLibrary1.csproj` I've placed a fake compilation step that just copies the scss in the `obj/` folder and then includes it:

	<Target Name="NpmRunBuild" BeforeTargets="AssignTargetPaths" Inputs="Component1.razor.scss" Outputs="$(IntermediateOutputPath)Component1.razor.css">
		<Exec Command="copy Component1.razor.scss $(IntermediateOutputPath)Component1.razor.css" />

		<ItemGroup>
			<Content Include="$(IntermediateOutputPath)Component1.razor.css" Link="Component1.razor.css" />
		</ItemGroup>
	</Target>

But this is the error I get:

`obj\Debug\net6.0\Component1.razor.css : error BLAZOR102: The scoped css file 'obj\Debug\net6.0\Component1.razor.css' was defined but no associated razor component or view was found for it.`

To me it looks like since the path is inside `obj\Debug` the framework misinterprets the path to be outside the component project location and refuses to bundle it.

### Expected Behavior

I would like this solution to work so I can avoid adding the compiled css file to the git repo and keep only the source scss. Using `.gitignore` is not an option because it causes the problem described in https://github.com/dotnet/aspnetcore/issues/38374

### Steps To Reproduce

Build https://github.com/JohnKiller/TestCopyFile

### Exceptions (if any)

`obj\Debug\net6.0\Component1.razor.css : error BLAZOR102: The scoped css file 'obj\Debug\net6.0\Component1.razor.css' was defined but no associated razor component or view was found for it.`

### .NET Version

6.0.101

**Comment by althepal78** [comment]
I don't know why I am getting this stupid ass message I am not using blazor at all wtf

**Comment by iykeypat** [comment]
**error BLAZOR102:** `The scoped css file 'obj\Debug\net6.0\Component1.razor.css' was defined but no associated razor component or view was found for it.`

**Solution:** `I recreated the razor component with a different name, copied my code to it, scoped the css file again and copied the css from the former one to it and voila, the error stopped.`

**Comment by Albiniivari** [comment]
Also having this issue at my work. The generated Scss files stays after switching branches, and thus creates this error. Is any solution found?

**Comment by KurtGarrettALS** [comment]
Same issue as reported above . To test; I created new Blazor Server solution targeting .net 6. Then created Razor component CustomNotFound.razor and then CustomNotFound.razor.css. VS attaches the css file correctly but then throws error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	BLAZOR102	The scoped css file 'Pages\CustomNotFound.razor.css' was defined but no associated razor component or view was found for it.	CustomerService	C:\VSApps\Development\CustomerService\CustomerService\Pages\CustomNotFound.razor.css	1	

![ScopedCssErrorScreenshot](https://user-images.githubusercontent.com/31772255/211155564-c42671dc-cb46-46c7-b8f4-2d2c701da5dc.jpg)

**Comment by rmeise** [comment]
Same error as @KurtGarrettALS

**Comment by schwindy** [comment]
I had a similar error, except it was for a `.js` file.

In my case, I was running `dotnet publish src/example/example.csproj -o path/to/publish`. The key was the `-o`, using a "custom output directory".

Using `-o`, the error always occurred if I ran `dotnet publish` twice in a row. The only way to fix it was to manually delete the `path/to/publish` myself. The next publish would work, and the cycle would repeat.

By removing the `-o` from my `dotnet publish`, it caused the output of the build to be published to `./bin/Release/net8.0/publish`.

Summed up, by leaving `-o` as default, the error went away. :monkey: I am somewhat new to C# but that does not seem intended. Hope this helps someone else.

**Comment by javiercn** [comment]
The solution is to use `ResolveScopedCssInputs` as inidicated https://github.com/dotnet/aspnetcore/issues/39344#issuecomment-1658251940

**Comment by vijaya33** [comment]
Hi developers,

I saw a similar problem in BLAZOR, initially I created the FileName_Abc.razor.css file inside the "Components/Layout" folder and saw that error, then dragged the FileName_Abc.razor.css file onto the "Components/Pages/FileName_Abc.razor and that resolved the error. 

so the file structure looks like below: 

"/Components/Pages/FileName_Abc.razor"
                                          &nbsp;&nbsp;  "/Components/Pages/FileName_Abc.razor.css" 

- Vijaya Laxmi Kumbaji.
