### ISSUE TITLE
 "AspNetCore.OpenIdConnect.Nonce" and "AspNetCore.Correlation" cookies unable to set cookie as Session cookies

### ISSUE THREAD

**Issue by mirza21** [dotnet/aspnetcore#39351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Microsoft.AspNetCore.Authentication.OpenIdConnect middleware in my application for openidcocnnect protocol. When Client application get redirected  two persistent cookies are created "AspNetCore.OpenIdConnect.Nonce" and "AspNetCore.Correlation". As per my under standing these cookies should be session cookies instead of peristent cookies as they contains user session related information.

### Expected Behavior

As per my understanding these cookies ("AspNetCore.OpenIdConnect.Nonce" and "AspNetCore.Correlation") should be set as session cookies by Microsoft.AspNetCore.Authentication.OpenIdConnect  middleware .  Is there any particular reason to make them persistent cookies.

### .NET Version

Asp.net core 2.1.403

**Comment by Tratcher** [comment]
Any cookie with an expiration is considered persistent, and both of these use a short expiration. That expiration is expected to be shorter than a normal browser session, we're not trying to extend the cookies, but to constrain them. They are also deleted as soon as the auth flow completes.
