### ISSUE TITLE
Wildcard in launchSettings.json causes "The hostname could not be parsed."

### ISSUE THREAD

**Issue by reinux** [dotnet/aspnetcore#39366]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/5127297/148486728-11536199-cacb-40ac-b166-ac3c2f6c62d2.png)

I guess this happens because without a specific URL, it doesn't know what URL to open in the shell/browser, but this error occurs even with `launchBrowser: false`. But it doesn't have trouble with a semicolon delimited list of URLs.

This makes it difficult to set up default launch settings in a portable way.

### Expected Behavior

For a URL like `https://+:5000`, replace `+` with `localhost`, or just produce a warning saying you can't use `launchBrowser` with wildcard applicationUrls, and accept it otherwise.

### Steps To Reproduce

- Create a new ASP.net Core project of any sort
- Set `applicationUrl` to `http://+:5000` in launchsettings.json
- Debug the program.

### .NET Version

6.0.101

### Anything else?

- ASP.NET Core 6.0.0.0
- VS 2022 17.0.4
- dotnet version 6.0.101
- Windows 11

**Comment by pranavkm** [comment]
Could you use the [VS feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report this issue? Thanks!
