### ISSUE TITLE
Cannot start Docker container on Raspberry Pi 4 using ASP.NET Core 6

### ISSUE THREAD

**Issue by mu88** [dotnet/aspnetcore#39372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've upgraded [my Dockerized Blazor application](https://github.com/mu88/ShopAndEat/blob/main/ShopAndEat/Dockerfile) from .NET 5 to .NET 6. On my Windows dev machine everything works fine. But on my Raspberry Pi 4 I cannot even start the Docker container. The container exits immediately without forwarding any detailed error to the console and `docker logs` does not contain anything.

Before the upgrade I've been using `5.0-buster-slim-arm32v7`. Since I didn't find any successor for my used OS version _Buster_ (e. g. `6.0-buster-slim-arm32v7`), I switched over to `6.0-bullseye-slim-arm32v7`. I already had a conversation with @mthalman ([see here](https://github.com/dotnet/dotnet-docker/issues/3334)). But I didn't upgrade my Raspi to _Buster_.

### Expected Behavior

The container starts as before.

### Steps To Reproduce

- Build [the Dockerfile](https://github.com/mu88/ShopAndEat/blob/main/ShopAndEat/Dockerfile)  
`docker build -f .\ShopAndEat\Dockerfile -t mu88/shopandeat:latest .`
- Create and start a new container  
`docker run -p 5002:80 -d -v /home/<<user>>/Docker/ShopAndEat/DB/:/db --name shopandeat mu88/shopandeat:latest`  
→ The container immediately exits.
- Getting more logs via `docker logs <<container ID>>` returns nothing

### Exceptions (if any)

No exceptions are returned to the shell.

### .NET Version

6.0.1

**Comment by mthalman** [comment]
Does it work if you call `docker run` with the `--privileged` option? If so, then the issue is likely that your [libseccomp pkg version needs to be updated](https://github.com/dotnet/dotnet-docker/issues/3253#issuecomment-956378676) on your Raspberry Pi.

**Comment by mu88** [comment]
Thanks man, that solved my issue!
