### ISSUE TITLE
Can't inject service in ValidationAttribute

### ISSUE THREAD

**Issue by sipi41** [dotnet/aspnetcore#39382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dear friends, yes, it's me again to bother you again! :-(

I love learning and found an article that woke up my mind, it was about creating a custom validation attribute (**ValidationAttribute**) but trying to inject a service (X) in order to get access to data or a method, etc... the idea sounds like a real project and I decided to give it a try... unfortunately every time I try to get a service I just get NULL... and yes, I tried to get some help from the MS help but the documentation is poor, no examples. (except a simple one where you learn how to override the IsValid method)

I created a simple class with a list of names and a method... the idea is that the Validation Attribute inject this as a service and then may ask the method if the name is valid or not... (if is on the list):

public class NamesService
    {
        public List<string> Names { get; set; } = new() { "Guillermo", "Cinthy" };
        public bool IsAValidName(string Name) {
            return Names.Contains(Name);
        }
    }

Then I basically injected this as an Scoped service on my program.cs as follow:

...
builder.Services.AddScoped<NamesService>();
...

I did try to inject the service on a regular class and it works, also on a Blazor page and it works also... now, I created another class where I tried in 2 ways:

1. Using the IValidatableObject like this, and you can see I made a breakpoint and the value is NULL:

![image](https://user-images.githubusercontent.com/688562/148632541-a10af5aa-c782-4dea-be1b-dd500676f277.png)

2. Ok, so I created a Custom Validation Attribute and the result is the same, like this:

![image](https://user-images.githubusercontent.com/688562/148632588-1916c7b5-c0c9-4b43-a6c4-a35f7c191e51.png)

Now I noticed several other options on the context, like:

- validationContext.InitializeServiceProvider
- validationContext.CreateAsyncScope

But no examples or what's the purpose or how to use these options? or will this help resolve the problem I'm facing?

Thank you for your help, this will help with what's being said all around... https://andrewlock.net/injecting-services-into-validationattributes-in-asp-net-core/

### .NET Version

6

**Comment by MariovanZeist** [comment]
Hi @sipi41 it seems that Blazor doesn't support getting a service from a ``ValidationContext``, the needed ``IServiceProvider`` is not supplied to the ``ValidationContext`` constructor 
[Here:](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Forms/src/EditContextDataAnnotationsExtensions.cs#L74-L75) and [Here:](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Forms/src/EditContextDataAnnotationsExtensions.cs#L96-L98)

Looking at the code it shouldn't be too hard to implement, but there could have been good reasons not to.
If you really need this functionality, you could create your own ``DataAnnotationsValidator`` class [DataAnnotationsValidator.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Forms/src/DataAnnotationsValidator.cs) and inject a ``IServiceProvider`` into that class, and create your own extension methods [EditContextDataAnnotationsExtensions.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Forms/src/EditContextDataAnnotationsExtensions.cs)

**Comment by sipi41** [comment]
thank you @MariovanZeist  it seems so difficult to implement... at least I never have done my own DataAnnotationsValidator, I think this is more commonly needed than I think, as in many real-life cases, interconnection is needed a lot.

I could instantiate my class with new, but will this be the preferred way instead? I mean, is there another way other than trying to re-do the .net framework?

**Comment by pranavkm** [comment]
Description: 
`EnableDataAnnotationsValidation` adds DataAnnotations validation support to an EditContext. The added instance currently does not configure the `IServiceProvider` on the DataAnnotations ValidationContext. This API change adds an additional overload that allows passing an instance of `IServiceProvider` that is then configured on the validation context.


```diff
static class EditContextDataAnnotationsExtensions
{
    public static IDisposable EnableDataAnnotationsValidation(this EditContext editContext)
+    public static IDisposable EnableDataAnnotationsValidation(this EditContext editContext, IServiceProvider? serviceProvider)
```

Usage:

We generally don't expect user code to invoke this but use the component instead.

```C#
EditContext.EnableDataAnnotationsValidation(ServiceProvider);
```

Alternatives:

`EditContext` has a property bag that could be used to pass the `IServiceProvider`.

**Comment by pranavkm** [comment]
Leaving the issue open for API review.

**Comment by sipi41** [comment]
@pranavkm Hello and thank you for the follow-up... I'm a little lost, would you please add a short example on what you said five days ago? If that's possible, it could be awesome! :-)

**Comment by pranavkm** [comment]
@sipi41, @MariovanZeist sent us a PR that added support for this feature - https://github.com/dotnet/aspnetcore/pull/39445 that would become available as part of .NET 7 preview 1. 

Our team has a formal review of all changes to public API surface. Since the PR added / changed existing APIs, I made a note of it to present in during the API review.

**Comment by pranavkm** [comment]
API review:

- [Obsolete("This API is obsolete and will be removed in a future version")]
- + [Obsolete("This API is obsolete and will be removed in a future version. Consider using the overload that accepts an IServiceProvider.")]
