### ISSUE TITLE
k8s docker connection reset by peer / Unexpected end of request content

### ISSUE THREAD

**Issue by ncaridi** [dotnet/aspnetcore#39393]
Hi, 
Not sure if this is the right place to ask 
I have a asp.net core 5 which I recently upgraded to 6.0 
with both versions I encountered the same issue. 
my setup is a kestrel server deployed in k8s cluster. 
when I load test the system with jmeter I can do around 600 RPS without any issues with great response times. 
With the same system I have around 150K requests during day  (which isn't much according to the 600 RPS it can handle) 
but I sometimes get the following errors : 
either ,
Error Message = Unexpected end of request content.
or 
Connection reset by peer

Not sure this is related but I used to get an error about data arriving to slow 
and I changed my min data rate to null in my program.cs options.

CPU usage for the nodes is between 2% to 5 %.

I did a dotnet counters for my process after deployment  this is what came up 

```
Press p to pause, r to resume, q to quit.
    Status: Running

[System.Runtime]
    % Time in GC since last GC (%)                                 0    
    Allocation Rate (B / 1 sec)                                    0    
    CPU Usage (%)                                                  0    
    Exception Count (Count / 1 sec)                                0    
    GC Committed Bytes (MB)                                        0    
Press p to pause, r to resume, q to quit.
    Status: Running

[System.Runtime]
    % Time in GC since last GC (%)                                 0    
    Allocation Rate (B / 1 sec)                                    0    
    CPU Usage (%)                                                  0    
    Exception Count (Count / 1 sec)                                0    
    GC Committed Bytes (MB)                                        0    
    GC Fragmentation (%)                                           0    
    GC Heap Size (MB)                                              0    
    Gen 0 GC Count (Count / 1 sec)                                 0    
    Gen 0 Size (B)                                                 0    
    Gen 1 GC Count (Count / 1 sec)                                 0    
    Gen 1 Size (B)                                                 0    
    Gen 2 GC Count (Count / 1 sec)                             8,168    
    Gen 2 Size (B)                                                 0    
    IL Bytes Jitted (B)                                            0    
    LOH Size (B)                                                  44    
    Monitor Lock Contention Count (Count / 1 sec)                 58.769
    Number of Active Timers                                       17    
    Number of Assemblies Loaded                                    0    
    Number of Methods Jitted                                   4,504    
    POH (Pinned Object Heap) Size (B)                              0    
    ThreadPool Completed Work Item Count (Count / 1 sec)     115,120    
    ThreadPool Queue Length                                        0    
    ThreadPool Thread Count                               35,318,880    
    Time spent in JIT (ms / 1 sec)                         2,522,816    
    Working Set (MB)                                       4,074,640    
                                                                   0 
```

any help / insight is much appreciated. 

Thank you . 

Nadi.

**Comment by Tratcher** [comment]
> Error Message = Unexpected end of request content.
> or
> Connection reset by peer

Those are common errors reported when clients abort requests. 

> Not sure this is related but I used to get an error about data arriving to slow and I changed my min data rate to null in my program.cs options.

That's also a common error for a misbehaving client. You should not disable the min data rate limit to accommodate them, you risk leaking resources on the server.

Do you have any reason to believe any of these errors are not caused by the clients?

**Comment by ncaridi** [comment]
Hi , 
I appreciate your reply. 

> > Error Message = Unexpected end of request content.
> > or
> > Connection reset by peer
> 
> Those are common errors reported when clients abort requests.
> 
> > Not sure this is related but I used to get an error about data arriving to slow and I changed my min data rate to null in my program.cs options.
> 
> That's also a common error for a misbehaving client. You should not disable the min data rate limit to accommodate them, you risk leaking resources on the server.
> 
What value shot I set for the min data rate ? 
Is it safe to filter out these errors ? 

> Do you have any reason to believe any of these errors are not caused by the clients?

I'm just turning stones , trying to find out why this happens . 
I read on a different post that this might be due to thread starvation (?) 
But it's not making much sense to me since I'm on less than 1/4 of the load testing rps and I get these errors .

Thank you . 

Nadi

**Comment by Tratcher** [comment]
> What value shot I set for the min data rate ?

Leave it at the default.

> Is it safe to filter out these errors ?

Yes

> I'm just turning stones , trying to find out why this happens .
> I read on a different post that this might be due to thread starvation (?)
> But it's not making much sense to me since I'm on less than 1/4 of the load testing rps and I get these errors .

It's possible for starvation to affect the timers, but we've added other logs to help you detect real starvation.

Can you repro any of these with a healthy client?

**Comment by ncaridi** [comment]
Thank you. 
So is it possible that min data rate would cause these other errors to show up or they're not related ?

what other logs should I look at to detect real starvation ? 

I wasn't able to reproduce these errors with a healthy client , when go beyond what my software / hardware is capable handling I get response 503 and not these errors . 
I was expecting to see these under stress but I see no stress.

**Comment by halter73** [comment]
Unless you see an issue with what a healthy client, I would chalk this up to general network flakiness. If your `ThreadPool Queue Length` is 0 under load, you don't have thread pool starvation.
