### ISSUE TITLE
Blazor NavigationManager additional features

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#39390]
I would like the `NavigationManager` in blazor to be able to open to new tab/window, refresh as well as close current window

**Comment by Grizzlly** [comment]
Right now, with `NavigationManager` you can only refresh using the forceLoad parameter. For opening and closing, you have to do JS interop.

**Comment by ctigrisht** [comment]
Yes I know about that @Grizzlly , but this is a feature request so I'm wondering if it this will get implemented

**Comment by javiercn** [comment]
@ctigrisht thanks for contacting us.

That's not a feature we plan to implement on navigation manager, navigation manager is focused on handling client-side navigation, not in creating new browsing contexts or managing the current one. You can implement those things via JS interop calls instead.

**Comment by ctigrisht** [comment]
@javiercn Then what about a feature that allows to go back to the previous page in blazor?
