### ISSUE TITLE
Why CascadingValue doesn't supported custom comparer?

### ISSUE THREAD

**Issue by wangzengxing** [dotnet/aspnetcore#39396]
I am trying to cascading a value with custom type,and override it's Equals method,but sames not work?
So,what's going on?

**Comment by javiercn** [comment]
@wangzengxing thanks for contacting us.

Blazor has a very conservative change detection algorithm and doesn't rely on custom comparers provided by the user. For reference objects (except strings), we assume they have changed, as getting equality wrong produces really hard to troubleshoot issues

**Comment by wangzengxing** [comment]
Thanks a lot!

**Comment by wangzengxing** [comment]
Sorry,another question,why not provider a parameter for CascadingValue to let us control this feature?
