### ISSUE TITLE
[Blazor] Disconnect alternative proposal

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#39409]
Based on https://github.com/dotnet/aspnetcore/issues/39370

We currently do this within the unload event because that's when we know the page is going to be terminated. As @TanayParikh points out this event isn't raised in some scenarios (closing a tab, mobile user switches apps, etc.) and the circuit remains disconnected for the default reconnection grace period instead of being fully terminated.

We could potentially do better in this scenario by changing the approach into a "soft" disconnect. The way this works is as follows:
* When we detect an unload event, we register a handler that calls /disconnect(false) on the server.
* In that case, the server registers a timestamp of when this happened.
* If a disconnection happens within a grace period after the "disconnect" call happens (lets say 10 seconds) the server terminates the circuit right away instead of adding it to the disconnected registry.
* If the grace period has passed after the signal was sent, we assume that the original signal was dismissed and we put the circuit on the disconnected registry instead.

This gives us a bit more flexibility as normally, given the `unload` event is unreliable, we at least get to be notified in other cases. As @TanayParikh mentions, visibilitychange might be another option. (For example, if the visibility changes right before loosing the connection)

**Comment by mkArtakMSFT** [comment]
@javiercn are you still interested in us pursuing this proposal?

**Comment by mkArtakMSFT** [comment]
I'm closing assuming the answer is "no". If you disagree, please reopen and move to the .NET 9 PLanning milestone.
