### ISSUE TITLE
[Feature request] [blazor] :Smarter value initialization for blazor's lifecycle

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#39400]
![image](https://user-images.githubusercontent.com/35312807/148736208-0f5b042e-fbed-42ed-b48c-e7ff729a162e.png)
Currently I have to do this for me to render stuffs properly. Because component references will be null until they are rendered in my experience. Therefore we probably should automatically call StateHasChange() again for these values to be initialized (not nulled) instead of having users to do it manually.

**Comment by ctigrisht** [comment]
I don't see the problem with calling a manual refresh if values have changed in `OnAfterRender`, because if the changed values do update the UI, it could end up in a loop

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is not something that we plan to change, this needs to be a user decision based on the specific context. If you want this behavior you can create your own base class, override OnAfterRenderAsync and implement this logic there yourself.

**Comment by Xyncgas** [comment]
I mean it's good to call StateHasChanged by default after firstRender
this solves the problem of component references obtained through @ref is null. Users doesn't expect this behavior, they expect that if they @ref their component after writing it down, they can reference this component immediately instead of after firstRender therefore I propose making it the case @javiercn

**Comment by javiercn** [comment]
> I mean it's good to call StateHasChanged by default after firstRender

No; it will trigger an additional render unconditionally the first time the component renders and it's not necessary on the vast majority of components, so it needs to be a user decission. 

We don't plan to change this behavior as it would be breaking for existing applications.

**Comment by Xyncgas** [comment]
sure. Thanks for replying anyways
