### ISSUE TITLE
Make it simpler for customers to investigate Blazor Auth issues

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#39412]
There have been many issues customers run into, where it's hard to understand what is the underlying issue. Whether it's a configuration issue or framework issue. This issue will be used to track the work for simplifying such investigations.

**Comment by Lukazoid** [comment]
I feel like even allowing setup of the oidc-client logger would help a lot.

Currently I have a token endpoint returning a valid access_token and id_token but the UI simply says: "There was an error trying to log you in: ''", with nothing in the console or VS output window, really not sure how to investigate this further.

**Comment by andrew-tevent** [comment]
Agree, `AuthenticationService.js` should have config options which allow the `Oidc.Log.Logger = console` and `Oidc.Log.LogLevel = ?`.  This would at least be a start.  It's a pain that you have to build a custom version of `AuthenticationService` to turn the OIDC logging on.

**Comment by mkArtakMSFT** [comment]
Moving to the RC1 milestone, as @javiercn has some work on hand which is going to improve this. Let's close this issue when the related PRs get merged.

**Comment by javiercn** [comment]
We did add logging support on the JS libraries which covers this

**Comment by oatsoda** [comment]
@javiercn Is there an example anywhere as to what we can configure?

**Comment by javiercn** [comment]
@oatsoda not yet, it was added in RC1 which has not been released yet.

**Comment by mkArtakMSFT** [comment]
> We did add logging support on the JS libraries which covers this

@javiercn will these logs show up as part of normal / default ASP.NET Core app logs, or is there any special configuration required to enable them?

**Comment by guardrex** [comment]
@javiercn ... Is there anything to document for 7.0 on this one?

**Comment by javiercn** [comment]
@guardrex turning the logging for Microsoft.AspNetCore.Components.WebAssembly.Authentication to debug or trace will log additional information on the browser console to help troubleshoot issues.
