### ISSUE TITLE
Route syntax highlighting and autocompletion

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#39441]
ASP.NET Core has a stable, well-defined syntax for routing. It supports a variety of features: 

- Parameters - /product/{id} 
- Parameter constraints - /product/{id:int} 
- Parameter defaults - /{page=Home} 
- Optional parameters - /files/{filename}.{ext?} 
- Catch-all parameters - /blog/{*slug} 
- Complex segments - /cube/{width:int}-{height:int} 
- Token replacement - /api/[controller]/[action] 

Understanding routing is essential to successfully using ASP.NET Core MVC, Web APIs, and Minimal APIs. While a basic route with a parameter is simple enough to use, few developers will have dedicated the complete range of routing features and syntax to memory. Additionally, there are rules and gotchas to using some of the more advanced features. E.g., a catch-all parameter must be the last parameter, or an optional parameter can’t have a default value, etc.  

The big problem here is the only way to figure out whether a route is correct or not is to run a web app, try to use the route, and see what happens. It’s not a good experience.  

We can improve this with tooling. Route syntax highlighting, auto-complete, and code analysis, can make route templates easier to understand and use. 

## Motivation and goals   

Routing is a highly used feature. We have the tools to make it better: Roslyn embedded language and Roslyn code analyzers. We’ve done this before for regexes and date format strings. 

Regular expressions: 

![image](https://user-images.githubusercontent.com/303201/148993171-dabe529a-7586-4b2f-a045-92bc5cbc2f88.png)

Date format strings: 

![image](https://user-images.githubusercontent.com/303201/148993243-94864221-9a3e-4502-8530-3f63ee5064f3.png)

The same improvements can be applied to routes: syntax highlighting, code analysis and autocomplete. These features would be available in APIs that define routes. 

Controller route attributes (Route, HttpGet, HttpPost, etc): 

![image](https://user-images.githubusercontent.com/303201/148993297-434e7898-ea39-403f-a431-d26d45e275c8.png)

Action route attributes (Route, HttpGet, HttpPost, etc): 

![image](https://user-images.githubusercontent.com/303201/148993337-e9f9df2d-a31c-4c91-9ccf-f98d10b1f12f.png)

Minimal API map methods (MapGet, MapPost, etc): 

![image](https://user-images.githubusercontent.com/303201/148993551-11c54fdc-1faa-4743-8d66-8b5e5dfe995a.png)

MVC conventional routing methods (MapControllerRoute, MapAreaRoute): 

![image](https://user-images.githubusercontent.com/303201/148993401-e6b41210-6450-4617-b510-77a9bba40d81.png)

Razor @page directive: 

![image](https://user-images.githubusercontent.com/303201/148993441-da6e109d-fcbf-4c06-9909-d318fe3bfbe9.png)

## Potential improvements

- Route syntax highlighting 
- Code analysis that validates the overall route syntax is valid (e.g. catch-all parameter isn't in the wrong location) 
- Code analysis of route parameters against minimal API or MVC parameters (e.g. a minimal API expects a parameter that the route doesn't capture, or there is a mismatch between a parameter's route constraint and the .NET type) 
- Autocomplete dropdown of built-in constraints 
- Autocomplete dropdown of route parameter names (inspect the minimal API delegate or MVC action arguments to get a list of candidates)

**Comment by ShreyasJejurkar** [comment]
This looks great!

Just for the info, rider already provides IntelliSense for putting route constraints! Not sure why VS doesn't, maybe it's isn't there yet!

**Comment by rogihee** [comment]
This would be really great for Blazor routes as well

**Comment by JamesNK** [comment]
Definitely. One complication is Blazor routes are slightly different from ASP.NET Core routes. Supporting them will require extra work.

**Comment by rogihee** [comment]
Sometimes you want to pass around a route outside a directive or attribute. How would you then let the compiler or analyzer know a string is a route? Perhaps a Route object or string extension?

**Comment by JamesNK** [comment]
See https://github.com/dotnet/runtime/issues/62505. You would need to place the attribute (with the right string language name) on the APIs that take a route string.

**Comment by danroth27** [comment]
> Definitely. One complication is Blazor routes are slightly different from ASP.NET Core routes. Supporting them will require extra work.

@JamesNK Can we use this issue to also track the support for Blazor routes, or should we track that separately?

@mkArtakMSFT @javiercn

**Comment by JamesNK** [comment]
I think a new one would be best. There will be a lot of reuse but extra work is going to have to happen to support blazor routes: displaying in razor pages, and handling the differences between blazor routes and standard routes.

**Comment by stephentoub** [comment]
> See dotnet/runtime#62505. You would need to place the attribute (with the right string language name) on the APIs that take a route string.

[StringSyntax(...)] has been added.

**Comment by TXRock** [comment]
Since this has been working like a charm with minimal APIs and Web APIs, but not for `Razor @page directives`. Just out of confirmation, am I missing something or is the work for `Razor @page directives` still in progress/obsolete?

**Comment by murshex** [comment]
Just wanted to say that I noticed the blue highlight for the "[controller]" part for RouteAttribute doesn't work if the controller is internal.
