### ISSUE TITLE
ElementReference.FocusAsync() does not focus a div with a tabindex in Blazor WASM

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#39448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling `ElementReference.FocusAsync()` does not focus a div element that has a tab index. This is verified by using the CSS selector `:focus` to visually show if the div is focused or not, by changing the background colour. 

If you manually click on the div element, the CSS selector is applied.

This has also been confirmed when using the event `@onfocus` (it's never called until manually focused).

### Expected Behavior

The referenced div is focused.

### Steps To Reproduce

```cs
<button @onclick="Focus">Focus</button>

<div @ref="_reference" tabindex="0" @onfocus="Focused" style="display: @(_show ? "block" : "none");">Hello World</div>

@code {
    private ElementReference _reference;
    private bool _show = false;

    private async Task Focus()
    {
        _show = true;
        await _reference.FocusAsync();
    }

    private void Focused()
    {
        Console.WriteLine("Focused");
    }
}
```

### .NET Version

.NET 6

### Anything else?

If you await a delay of 1ms between `_show = true` & `await _reference.FocusAsync();`, the element is focused.

**Comment by KristofferStrube** [comment]
You can't focus an element that has style `display:none`

This minimal HTML/JS example showcases this:

```html
<html>
    <head></head>
    <body>
        <div id="div" tabindex="0" style="display:none;">Hello World</div>
        <script>
            var div = document.getElementById("div");
            div.addEventListener("focus", (e) => {
                console.log("Focused");
            });
            div.focus();
        </script>
    </body>
</html>
```

The problem occurs because the DOM has not been updated when the focus function is invoked trough JSInterop.
You can change your `Focus()` method to the following to get around the problem:
```csharp
private async Task Focus()
{
    _show = true;
    await Task.Run(async () => await _reference.FocusAsync());
}
```

Another alternative is to use a span inside the div that gets displayed instead:
```razor
<div @ref="_reference" tabindex="0" @onfocus="Focused"><span style="display: @(_show ? "block" : "none");">Hello World</span></div>
```

**Comment by KieranDevvs** [comment]
> Hey @KieranDevvs,
> 
> You can't focus an element that has style `display:none`
> 
> This minimal HTML/JS example showcases this:
> 
> ```
> <html>
>     <head></head>
>     <body>
>         <div id="div" tabindex="0" style="display:none;">Hello World</div>
>         <script>
>             var div = document.getElementById("div");
>             div.addEventListener("focus", (e) => {
>                 console.log("Focused");
>             });
>             div.focus();
>         </script>
>     </body>
> </html>
> ```
> 
> The problem occurs because the DOM has not been updated when the focus function is invoked trough JSInterop. You can change your `Focus()` method to the following to get around the problem:
> 
> ```cs
> private async Task Focus()
> {
>     _show = true;
>     await Task.Run(async () => await _reference.FocusAsync());
> }
> ```
> 
> Another alternative is to use a span inside the div that gets displayed instead:
> 
> ```
> <div @ref="_reference" tabindex="0" @onfocus="Focused"><span style="display: @(_show ? "block" : "none");">Hello World</span></div>
> ```

Ok thanks for the info!
