### ISSUE TITLE
Unable to run ASP.net Core 6.0 Web API on IIS 10 Windows Server 2019

### ISSUE THREAD

**Issue by sreenathkurpad123** [dotnet/aspnetcore#39452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I built ASP.net Core 6.0 Web API using default template in Visual Studio 2022. The application is configured to use inProcess hosting, IIS as reverse proxy. I followed all the steps provided in Microsoft docs- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0. I hosted the application in IIS 10 Windows Server 2019 by creating a new application under default web site. The application pool is set to No Managed Code.  When I hit the API end point, I get an error HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit. Event log has this error : Application '/LM/W3SVC/1/ROOT/WeatherAPI' with physical root 'C:\Inetpub\WWWroot\WeatherAPI\' failed to load coreclr. Exception message: Managed server didn't initialize after 120000 ms. I tried many things suggested online but couldnt rectify this error. I am not sure what I am missing. Hoping someone can throw light on this issue.

Few things to note:

1. The same api can be invoked using Kestrel in the same Windows Server 2019
2. The sample API built with Dotnet core 3.1 is working on IIS and Kestrel

### Expected Behavior

I should be able to invoke the API end point using IIS as reverse proxy. 

### Steps To Reproduce

Step 1: Open VS 2022
Step 2: Select ASP.net Core Web API
Step 3: Select .Net 6.0 LTS, keep the controllers checked (do not use minimal APIs)
Step 4: Publish the app to IIS using VS 2022 publish option
Step 5: Create Application under default website or Create a new website (shouldnt matter)
Step 6: Create application pool with default identity , set CLR to No managed code
Step 7: Associate the application to the above pool
Step 8: Hit the API end point from a browser

### Exceptions (if any)

Issue: 
HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit 

Common solutions to this issue: 
ASP.NET Core app failed to start after 120000 milliseconds 
Troubleshooting steps: 
• Check the system event log for error messages 
• Enable logging the application process' stdout messages 
• Attach a debugger to the application process and inspect 

### .NET Version

dotnet 6.0.101

### Anything else?

ASP.net Core 6.0
IIS 10
Windows Server 2019

**Comment by Tratcher** [comment]
Have you tried these steps yet? Especially the stdout logs.
https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#troubleshoot-on-iis

**Comment by klorens** [comment]
@sreenathkurpad123 Have you managed to solve this problem? I am currently experiencing very similiar issue and ran out of ideas.

**Comment by Alex-Torres** [comment]
I am experiencing same exact issues.
