### ISSUE TITLE
Polymorphic binder on collection attempts to bind an extra element

### ISSUE THREAD

**Issue by farinha** [dotnet/aspnetcore#39461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using [Polymorphic model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#polymorphic-model-binding) with a collection of objects that are rendered using a custom editor template via `@Html.EditorFor()` I came across some weird behaviour (bug?) during the binding where the binding mechanism seems to be attempting to bind a non-existing item.

### Steps To Reproduce

https://github.com/farinha/aspnetcore-binding-issue

Place a breakpoint on `BindModelAsync` to be able to step through the issue.

Run the project and once the page loads point it to `/Device`. Submit the form (the values don't matter).
Using the browser dev tools to inspect the payload it's possible to check what is getting submitted:
![image](https://user-images.githubusercontent.com/1678330/149183684-9f72e1ce-fa16-4f45-b11d-61d5bd2ad6cd.png)

`BindModelAsync` is called once for each of the objects being bound. Note the value of `bindingContext.ModelName`. On the first hit it's "Devices[0]", letting it run through will move on to "Devices[1]" and that should be it. But letting it run through again stops on an "extra" item:
![image](https://user-images.githubusercontent.com/1678330/149183296-3b4a3a62-d193-4352-b35e-31a0bd5d59bc.png)

It's okay to let it run again. The code handles this non-existing item by marking its binding as failed, but no further problems seem to arise from it.

### .NET Version

5.0.404

### Anything else?

Microsoft Visual Studio Professional 2019 Version 16.11.8

**Comment by pranavkm** [comment]
That's kinda how collection binding works. It keeps attempting to bind additional elements until no more elements can be bound. You could optionally specify the exact indices to bind by including a `index` field: https://docs.microsoft.com/aspnet/core/mvc/models/model-binding#collections goes over this.

**Comment by farinha** [comment]
Thank you for clarifying @pranavkm. I couldn't find this behaviour documented anywhere, but your clarification makes sense.
