### ISSUE TITLE
Blazor virtualization can't work with `flex-wrap: wrap` and grid layouts

### ISSUE THREAD

**Issue by dredav** [dotnet/aspnetcore#39468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there 👋 

I'm not sure how to deal with the blazor virtualization... so I'm opening here an issue.

## What I'm trying to archive
I want to use the virtualization to render items. I'm using a flex layout and will wrap (`flex-wrap: wrap`) these items when the width is fully used. The first items will be rendered as expected (as long you didn't touch the scrollbar). When starting scrolling all items will flicker and the control insn't usable anymore. 

Code example: https://blazorrepl.telerik.com/GQublwQk09jdnEVr22
![virtualize](https://user-images.githubusercontent.com/731073/149216400-7fa6db0c-1a55-4b54-b533-eb3e1e28e220.gif)

## Grid isn't a alternative
I also try to change the layout to a grid based one. That works fine, but the first and last item is a blazor virtualization `<div height=0` item, which will use a grid column itself. I found a GH issue which says that virtualization will not work with grid layouts.

Set the special div items to `display: none` will break the virtualization too.
```css
.grid-virtualize > :first-child,
.grid-virtualize > :last-child{
 display: none;
}
```

See also #28056

## Looking forward
So I'cant use a grid layout and can't use a flex layout with wrapping here in't a creat experience. Currently I think the implementation of blazors virtualization has some "design issues" when working with external css and I should remove it for my use-case.

Is there any recomended layout guids for blazors virtualization? Also are there any other solution to get the virtualization  working in my case?

### .NET Version

6.0.100

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This scenario is not supported. To find out what is supported, you can read the [Blazor Virtualization docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0#advanced-styles-and-scroll-detection).
