### ISSUE TITLE
.NET garbage collection doesn't run until memory pressure occurs

### ISSUE THREAD

**Issue by Fabi** [dotnet/aspnetcore#39483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Basically https://github.com/dotnet/aspnetcore/issues/37066 or https://github.com/dotnet/aspnetcore/issues/30210

Even the default app when creating a project got issues. Or an app with empty pages. Every visit/refresh causes new memory to be allocated. dotMemory etc. only show unmanaged memory there. Even after hours it gets never freed. Only a resart of the server will do that of course.

This is definitively a bug in the framework.

### .NET Version

6.0

**Comment by TanayParikh** [comment]
Hello @Fabi thanks for contacting us. 

> Every visit/refresh causes new memory to be allocated.

Could you please clarify where this new memory is being allocated (client / server), as well as how you're measuring the memory allocation. Please confirm you're using a release build, without the debugger attached. 

> Even after hours it gets never freed. Only a resart of the server will do that of course.

Please note, no garbage collection will be triggered unless the system is running low on memory. [This article](https://devblogs.microsoft.com/dotnet/garbage-collection-at-food-courts/) provides an excellent metaphor for how the .NET garbage collection works.. I suggest you check out [this repo](https://github.com/sebastienros/memoryleak) for best practices when analyzing memory in .NET applications.

**Comment by Fabi** [comment]
> Hello @Fabi thanks for contacting us.
> 
> > Every visit/refresh causes new memory to be allocated.
> 
> Could you please clarify where this new memory is being allocated (client / server), as well as how you're measuring the memory allocation. Please confirm you're using a release build, without the debugger attached.
> 
> > Even after hours it gets never freed. Only a resart of the server will do that of course.
> 
> Please note, no garbage collection will be triggered unless the system is running low on memory. [This article](https://devblogs.microsoft.com/dotnet/garbage-collection-at-food-courts/) provides an excellent metaphor for how the .NET garbage collection works.. I suggest you check out [this repo](https://github.com/sebastienros/memoryleak) for best practices when analyzing memory in .NET applications.

Well. Of course the allocations happens on server side. I used different things. dot memory from jet brains, looking at the task manager etc. All of these indicate a bunch of memory usage.

The default server side project will go to gigabytes of memory usage of a few 1000 requests. Limiting the memory through a VM will make the whole website unrenderable once it reaches it max memory usage (a big chunk unmanaged memory sometimes).

Its easy to reproduce for anyone.
1. Create default server blazor app
2. Start
3. Refresh often or open many tabs and close the browser
4. See the memory usage growing and staying high through a tool of your choice.

This is a a whole design issue of these server side apps and should never happen. It should always be freed when not longer required but that does not happen. Please stop treating this as a user issue.

**Comment by TanayParikh** [comment]
> I used different things. dot memory from jet brains, looking at the task manager etc. All of these indicate a bunch of memory usage.

Please confirm you're using a release build, without the debugger attached.

> Limiting the memory through a VM will make the whole website unrenderable or really slow once it reaches it max memory usage (a big chunk unmanaged memory sometimes).

Just to confirm, are you actually running into this situation, or are you extrapolating based on the initial performance (and initial lack of GC)? As I mentioned above:

> no garbage collection will be triggered unless the system is running low on memory. This article provides an excellent metaphor for how the .NET garbage collection works.. I suggest you check out this repo for best practices when analyzing memory in .NET applications.

**Comment by Fabi** [comment]
> > I used different things. dot memory from jet brains, looking at the task manager etc. All of these indicate a bunch of memory usage.
> 
> Please confirm you're using a release build, without the debugger attached.
> 
> > Limiting the memory through a VM will make the whole website unrenderable or really slow once it reaches it max memory usage (a big chunk unmanaged memory sometimes).
> 
> Just to confirm, are you actually running into this situation, or are you extrapolating based on the initial performance (and initial lack of GC)? As I mentioned above:
> 
> > no garbage collection will be triggered unless the system is running low on memory. This article provides an excellent metaphor for how the .NET garbage collection works.. I suggest you check out this repo for best practices when analyzing memory in .NET applications.


And I test in Debug and Release builds. Both. So yes I did.

I limited my docker container to 1GB usage and it was basically slow. really slow. But that is only a little part of the point here.
It should NEVER hold unused memory of things that are not longer required, not when the system is low on memory. And a refresh of the same browser tab (even with an empty white page) will make the memory go very high after enough refreshes. This stays like that even after hours closing the browser then.

"no garbage collection will be triggered unless the system is running low on memory." is not how it should work. Changing the GC mode also does not change anything.

**Comment by SteveSandersonMS** [comment]
I've updated the issue title to better reflect the concern.

**Comment by javiercn** [comment]
We've covered improved documentation as well as pointed out the reference docs for how memory works in .NET https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-7.0#blazor-server-memory-model.

**Comment by davidfowl** [comment]
FYI @Maoni0

**Comment by Maoni0** [comment]
> "no garbage collection will be triggered unless the system is running low on memory." is not how it should work.

and that is not how the GC works at all. to debug any memory issue, the best way to start is to [capture a top level trace with GC metrics](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#how-to-collect-top-level-gc-metrics). is this something you could do and share the resulting trace (which does not contain PII)? without any data it's impossible to say what happened.

**Comment by Maoni0** [comment]
also CC-ing @mangod9

**Comment by Maoni0** [comment]
I see there was already simple repro steps mentioned. @davidfowl can you repro with the steps above? I'd think if that's the case you would've already come to us. also CC-ing @mangod9.
