### ISSUE TITLE
.Net6 Blazor SignalR Hub Connection causing high CPU in web browser

### ISSUE THREAD

**Issue by bryan-arn** [dotnet/aspnetcore#39482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Have been struggling with an issue where a hub connection in my .Net6 Blazor apps cause the browser (both Chrome and Edge) CPU to max out over time (10 mins to several hours), causing the apps to become unresponsive. This is only occurring when using Visual Studio 2022 and .Net6, and self-hosting.

I created 2 extremely simple test apps, one in VS2019/.Net5 and the other in VS2022/.Net6 (both Enterprise). They are the same except for the versions. Have tried on 3 different PCs with similar results. The CPU for the browser as viewed in Task Manager begins an upward trend until it reaches 20% +. This can take 30 minutes or more. The .Net5 app generally remains < 1%.

This occurs even if no listeners are configured, though the upward trend is much faster if messages are being received.

### Expected Behavior

It is expected that the browser CPU remains low, as it does when using .Net5.

### Steps To Reproduce

Example is at https://github.com/bryan-arn/_SignalRCpuDev

For the example, the solution creation overview is:
1. Create new Blazor app - .Net6, no authentication, no HTTPS, Core Hosted
2. Add Hub class and map endpoint in Program.cs - endpoints.MapHub<ServiceHub>("/serviceHub");
2. Add class to use as BackgroundService, add as hosted service in Program.cs - builder.Services.AddHostedService<SignalRCpuDevService>();
3. Use BackgroundService to connect to hub and send current time every second (or however long specified in delay) as string to hub.
4. In Index.cs, connect to hub, add receiver for 'receiveText' method and populate label.

So it is an extremely simple SignalR app.

### .NET Version

6.0.101

### Anything else?

Microsoft Visual Studio Enterprise 2022 (64-bit) 
Version 17.0.4
Standard Blazor Webassembly template

**Output from dotnet --info:**
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.407 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by davidfowl** [comment]
[This logic](https://github.com/bryan-arn/_SignalRCpuDev/blob/33c11ac6a552be8afd81d1925a887babf4c9d8c9/_SignalRCpuDev/Server/SignalRCpuDevService.cs#L10) wouldn't typically use the SignalR client, instead it would use an `IHubContext<ServiceHub>` and directly call the clients.

**Comment by bryan-arn** [comment]
Thanks David, have changed the server to use IHubContext. If I want to set up listeners too, do I need to use a HubConnection still? The hubContext doesn't seem to have anything like hubContext.On<>.

Most importantly though, the CPU usage issue still remains.

**Comment by bryan-arn** [comment]
Just further to this, I have now also tested with Firefox - and it seems to behave itself, CPU is usually < 1%. The Chrome instance is at 20% +.  Edge seems to be better but it still gets up there, just slower. So it seems it may be browser related? The Chrome installs are up to date, version 97.0.4692.71, Edge is 97.0.1072.62.

**Comment by BrennanConroy** [comment]
@kg or @pavelsavara could you help with diagnosing cpu issues in a wasm app?

**Comment by kg** [comment]
This may be the timers issue (https://github.com/dotnet/runtime/issues/62227), which is fixed by https://github.com/dotnet/runtime/pull/62705. I don't know when the fix will make it into a release but it is planned to make it into a 6.0 update.

**Comment by adityamandaleeka** [comment]
@bryan-arn Can you please check if that fix solves this issue? You can find a pre-release 6.0.2 build here: https://aka.ms/dotnet/6.0.2xx/daily/dotnet-sdk-win-x64.exe

**Comment by bryan-arn** [comment]
@adityamandaleeka I have installed the 6.0.2 preview however when I try to build I am getting this:

CSC : warning CS8032: An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\Program Files\dotnet\sdk\6.0.200-preview.22069.5\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

This is happening both with the existing test app and a new app created from the Blazor template. Any ideas on what is causing this?

**Comment by BrennanConroy** [comment]
Try https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe

**Comment by bryan-arn** [comment]
HI Brennan - have now tried that version but it has the same issue. Sounds like I may need to wait for the offical release of 6.0.2?

**Comment by adityamandaleeka** [comment]
Closing for now, please reopen if you still see this in 6.0.2.
