### ISSUE TITLE
Expose reason why ValidateAsync in IUserTwoFactorTokenProvider fail

### ISSUE THREAD

**Issue by lufo88ita** [dotnet/aspnetcore#39491]
Hi,
I'm using Microsoft.AspNetCore.Identity.UserManager
### Is your feature request related to a problem? Please describe.
I'm developing a web site and I didn't understand why VerifyUserTokenAsync (in UserManager) return false for a token I generate when a user change his email.
I was forced to implement a version of the method ValidateAsync of DataProtectorTokenProvider to retrieve the error and fix my code

### Describe the solution you'd like
As the title said, it will be great if the api will expose the reason why a token is not valid. I guess the simplest change is to modify the return type of ValidateAsync  in IUserTwoFactorTokenProvider (and  VerifyUserTokenAsync as well) from bool to string. 
string empty = verification success
otherwise
the reason it fail

A better approach is maybe use a enum or an object rather then a string, but a string it will be sufficient.

**Comment by adityamandaleeka** [comment]
Triage: this is by design. We don't recommend showing different error messages based on authentication failures.

**Comment by lufo88ita** [comment]
> Triage: this is by design. We don't recommend showing different error messages based on authentication failures.
Ok, I don't want to raise a discussion about this decision, but at least add more debug information. The developer need this info to understand why it doesn't work. In the console log I see only a generic fail, without explanation and i spent about two hours to understand what's wrong and less than 5 minutes to fix my code.
