### ISSUE TITLE
Add support for Blazor Component Extension like C# code extension for reusable components

### ISSUE THREAD

**Issue by sake402** [dotnet/aspnetcore#39494]
### Is your feature request related to a problem? Please describe.
The main purpose of extension code in C# is so we can add methods/operations to an object without adding the member to the class itself. 
In Blazor however, in order to reuse a piece of UI code, you have to wrap it into a component or use an C# extension as below 
```C#
RenderFragment GetButton(this ComponentBase caller, ButtonType buttonType, Theme buttonTheme)
{
    return (builder) =>
    {

    };
}
```

This method can then be called from any component as

```C#
@this.GetButton(ButtonType.Icon, Theme.Primary)
```

Component creation however can be costly in terms of performance as blazor has to manage and maintain the state of the components.
However some components can be very basic in terms of functionalities, for example a Button Component simply wraps ``<button>`` and a couple of ifs.
A grid cell component is just a ``td``

### Describe the solution you'd like
What is proposed is that such basic component should be expressable as an extension method in .razor file or .cs file that returns RenderFragment and takes a number of parameter that would rather be decorated with ``[Parameter]`` in the component.

```C#
public static class ComponentExtension
{
    //user must supply all parameters except optional ones which are optional
    //Extension component name must start with a Get and returns RenderFragment
    //Can have parameters and even optional ones
	
	//this component can be used from any component
    public static RenderFragment GetButton(this ComponentBase callerComponent, ButtonType buttonType, Theme buttonTheme, EventCallback click, int optionalParameter = 0)
    {
        return @<button @onclick="click" class="@buttonType @buttonTheme"></button>;
    }

	//this component can be used from any component
    public static RenderFragment GetButton2(this ComponentBase callerComponent, ButtonType buttonType, Theme buttonTheme, EventCallback click, int optionalParameter = 0)
    {
        return (builder) => 
        {
             builder.OpenElement("button");
             //more builders
             builder.CloseElement();
        }
    }
	
	//this component can be used only in CardComponent or super classes
	public static RenderFragment GetButton3(this CardComponent callerComponent, ButtonType buttonType, Theme buttonTheme, EventCallback click, int optionalParameter = 0)
    {
        return (builder) => 
        {
             builder.OpenElement("button");
             //more builders
             builder.CloseElement();
        }
    }
	
	//this component can be used only in super classes of MyBaseComponent
	public static RenderFragment GetButton4<TComponent>(this CardComponent callerComponent, ButtonType buttonType, Theme buttonTheme, EventCallback click, int optionalParameter = 0) where TComponent : MyBaseComponent
    {
        return (builder) => 
        {
             builder.OpenElement("button");
             //more builders
             builder.CloseElement();
        }
    }
}
```

The razor generator will however allow this Component Extensions to be referenced like a normal component as

```HTML
<Button ButtonType="ButtonType.Icon" ButtonTheme="Theme.Primary" Click="DoSomething"></Button>
<Button2 ButtonType="ButtonType.Icon" ButtonTheme="Theme.Primary" Click="DoSomething"></Button2>
```

and will generate a call to the extension method

```C#
builder.AddContent(1, this.GetButton(ButtonTyp.Icon, Theme.Primary, EventCallback.Factory.Create(this, DoSomething)));
```

### Additional context
The advantage of this majorly is that the numbers of such component created will not have drawback on performance as it is simply a method call while user still get a feel of razor syntax instead of C# code in razor file.

This feature will not affect the Blazor Microsoft.AspNetCore.Component in any way, just the tooling support to call extension methods directly instead of buiilding the component with builder.OpenComponent

If this is a welcomed idea, I'd be willing to contribute this feature to the ``Microsoft.NET.Sdk.Razor.SourceGenerators``

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@jaredpar here is another ask for having markup support in C#. Unfortunately, I was unable to find the duplicate issue, but I'm sure there are multiple tracking this already.

**Comment by sake402** [comment]
Closing an issue based on being unable to find it's duplicate. If there is really a duplicate, I'd like to add my vote to it.
