### ISSUE TITLE
Hot reload still not working for cshtml

### ISSUE THREAD

**Issue by sbsw** [dotnet/aspnetcore#39508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing and saving code in a cshtml does not affect the HTML displayed in the debug session browser window. This seems to be the same issue as issue [#36098](https://github.com/dotnet/aspnetcore/issues/36098), which appears to be closed/resolved.

### Expected Behavior

If I run an ASP.Net MVC (net5.0) app under debug and I change the cshtml view code for the current page, the changes should be visible on that page.

### Steps To Reproduce

* Create new ASP.NET Core Web App targeting net5.0
* F5
* Open index.cshtml, change the welcome text, and save the changes.

**Expected Behavior:**
Welcome text changes

**Actual Behavior:**
Welcome text does not change

**Other things I've tried**
* Set Hot Reload on File Save (under the Hot Reload button on the VS toolbar)
* Click the Hot Reload button on the VS toolbar
* Reload the web page in the browser

### .NET Version

6.0.101

### Anything else?

**Visual Studio version:**
Microsoft Visual Studio Professional 2022 (64-bit)
Version 17.0.5

**Comment by TanayParikh** [comment]
Hello @sbsw, thanks for contacting us. This issue is being discussed here: https://github.com/dotnet/aspnetcore/issues/38809

Closing this out as a duplicate.

**Comment by sbsw** [comment]
Hello @TanayParikh, issue #38809 seems to be all about projects that include Blazor. This is just a vanilla ASP.NET Core MVC app.

**Comment by SteveSandersonMS** [comment]
@sbsw I'm afraid hot reload requires .NET 6 (so, target net6.0).

**Comment by sbsw** [comment]
> hot reload requires .NET 6 (so, target net6.0)

That gem of wisdom is seriously not obvious. Now that the UI has a "hot reload" button, something in the vicinity of that button needs to look at the project(s) and prominently warn if some project settings (such as the target) need to be changed for Hot Reload to actually work.

**Comment by TanayParikh** [comment]
Thanks for the feedback @sbsw. Would you mind filling a VS issues (Report a Problem dialog in VS) with that feedback so it may be directed to the appropriate team.
