### ISSUE TITLE
(Suggestion) Blazor: RenderFragment target String

### ISSUE THREAD

**Issue by LukeTOBrien** [dotnet/aspnetcore#39506]
Hello,

I would like to return a `RendeFragment` as a string, I understand this is not currently possible but I would like to suggest the idea for future consideration.  
This issue is the same as https://github.com/dotnet/aspnetcore/issues/22266 and https://github.com/dotnet/aspnetcore/issues/9493

## Use case

In my case I am creating a wrapper component around a WebComponent I have, in my WebComponent I have a `itemTemplate` function that returns a `Promise<string>`:

```ts
itemTemplate: (obj: any) => Promise<string>;
```

Inside the `OnAfterRenderAsync` method, I then call the JavaScript function to set the itemTemplate:

```ts
setItemTemplate = (id: string, dotNet: DotNet.DotNetObject) => {
        let el = document.getElementById(id);
        if (el) {
            el.itemTemplate = (obj) => {
                return dotNet.invokeMethodAsync<string>('OnItemTemplate', obj);
            }
        }
    }
```

Finally in the Blazor component I return the RenderFragment as a string: ( I have found a hacky workaround)

```csharp
[JSInvokable]
        public async Task<string> OnItemTemplate(T obj)
        {
            var fragment = ItemTemplate(obj);
            var builder = new RenderTreeBuilder();
            fragment(builder);
            var els = builder.GetFrames().Array.Where(x => !string.IsNullOrWhiteSpace(x.MarkupContent));
            var html = string.Join("", els.Select(x => x.FrameType == RenderTreeFrameType.Element ? $"<{x.MarkupContent}>" : x.MarkupContent));
            return html;
        }
```

## Possible solution

The fragment renders to a `RenderTreeBuilder` , would it be be possible to abstract the TreeBuilder into an interface?  

```csharp
[JSInvokable]
        public async Task<string> OnItemTemplate(T obj)
        {
            var fragment = ItemTemplate(obj);
            var target = new StringRenderer();
            fragment(target);
            return target.GetString();
        }
```

What are your thoughts on this?

**Comment by TanayParikh** [comment]
Note; may be related to https://github.com/dotnet/aspnetcore/issues/17200.

**Comment by javiercn** [comment]
@LukeTOBrien thanks for contacting us.

This is not something we support.

There are technical reasons for it, like the fact that we don't know the instantiation of the type parameter T when you invoke it through JavaScript and even if we knew, we can't allow unbounded generic instantiations as that would lead to a type explosion.

One path forward that might work is to use a JS root component to represent the template for the item, in that case, inside your content you can render a JS root component and that should allow you to pass in an argument (you would need to specify a concrete type)
