### ISSUE TITLE
Issue with Multiple Schemes, context.AuthenticateAsync(scheme) not able to authenticate in version 6.0.0 onwards

### ISSUE THREAD

**Issue by spineshanks** [dotnet/aspnetcore#39500]
@pranavkm if you can help.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi We are migrating nuget package **Microsoft.AspNetCore.Authentication.JwtBearer 5.0.13 to 6.0.1,** however, with the latest release, authentication stopped working. we have multiple JWT schemes like below
```
foreach (var scheme in schemes)
                {
                    = services.AddAuthentication().AddJwtBearer(scheme, options =>
                    {// Token Validation code
}
}
```

using middleware from here https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs

```
foreach (var scheme in _multiAuthenticationOptions.Schemes)
                {
                    var result = await context.AuthenticateAsync(scheme).ConfigureAwait(false);
                    if (result?.Principal != null)
                    {
//set user context if principal found
                    }
}
```

this code is working fine till nuget versions 5.0.13. but not working in the latest.
any one facing the same issues. or any idea what got changed internally.

### .NET Version

6

**Comment by Tratcher** [comment]
That's the error/symptom?

**Comment by spineshanks** [comment]
> That's the error/symptom?

That's the running code till now, with the latest version "context.AuthenticateAsync(scheme)" is not authenticating against JWT toke. getting error, default auth schema is required. I have multiple Auth schemes so can't specify default to a single scheme.

for testing, I provided a default scheme to one scheme, post that code is throwing "invalid-token" error.

**Comment by adityamandaleeka** [comment]
@spineshanks Can you provide a self-contained repro for this?
