### ISSUE TITLE
Blazor RemoteAuthenticatorView OnLogInSucceeded event firing multiple times

### ISSUE THREAD

**Issue by aklysheiko** [dotnet/aspnetcore#39507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue was closed, but the problem has never been resolved: 
https://github.com/dotnet/aspnetcore/issues/29235

Me and a lot of other people are reporting the same issue. 

### Expected Behavior

Callback fired only once

### Steps To Reproduce

The original (closed) issue has all steps to reproduce

### .NET Version

6.0.200-preview.21617.4

### Anything else?

  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.21617.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by b1tzer0** [comment]
I am having this issue as well.  When the user logs in, it performs this action 3 times.  That can be expensive when making db calls.

**Comment by AlbertoPa** [comment]
This issue is a problem for any attempt to capture a successful login (and possibly a logout). It effectively seems to make the OnLoginSucceeded event unusable because it is triggered multiple times when it is supposed to be triggered only once.

Since net 6 is LTS, it doesn't seem fine to move this to 7.

**Comment by stephajn** [comment]
I absolutely agree with @AlbertoPa. This should be fixed sooner rather than later.

**Comment by MackinnonBuck** [comment]
Done in #43844

**Comment by b1tzer0** [comment]
As previously stated, since .NET6 is the LTS, the fix really should be merged in to .NET 6 release as well.

**Comment by stephajn** [comment]
> As previously stated, since .NET6 is the LTS, the fix really should be merged in to .NET 6 release as well.

@b1tzer0 I opened Issue #43925 for this very reason if you want to upvote it.

**Comment by javiercn** [comment]
@b1tzer0 thanks for your interest. 

We normally get fixes in a preview version before we decide to backport them.
