### ISSUE TITLE
External Google login breaks when logging from mobile device where there are multiple google accounts

### ISSUE THREAD

**Issue by feugen24** [dotnet/aspnetcore#39513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm working on a asp.net core (.net 5, Authentication v5.0.13 packages ), app that uses Google login. All seemed to be working ok until I noticed android login from chrome no longer works. 

This happened only when there are multiple logon accounts on mobile both android and safari on ipad (android chrome/settings- click on your account, add account). If I remove accounts and leave only one it works again.

**The problem**: 

When /signin-google?state= path is called for single account I have in Request header "Referer: https://my-site.com/"
but when there are multiple accounts it introduces the account pick screen and that changes "Referer: https://accounts.google.com/", because of this the cookie from response "Identity.External" is ignored because it has samesite=lax (see attached pic)

The next request is to ExternalLogin with no "Identity.External" cookie so "await _signInManager.GetExternalLoginInfoAsync();" will return null.

**The fix:** same as [issue 318](https://github.com/aspnet/Announcements/issues/318)

```
services.ConfigureExternalCookie(options =>
{
    // Other options
    options.Cookie.SameSite = SameSiteMode.None;
});
```

I could not find this in [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-6.0) or issues from other users, and it was very difficult to debug (~3 days) but the problem seems very general so maybe I'm missing something.

### Expected Behavior

Google login should work with multiple accounts.

### Steps To Reproduce

I assume a basic .net 5 (not sure about 6), nuget for authentication libs v5.0.13, project with Google authentication, multiple google accounts but without the code: 

```
 services.ConfigureExternalCookie(options =>
{
    // Other options
    options.Cookie.SameSite = SameSiteMode.None;
});
```

### Exceptions (if any)

await _signInManager.GetExternalLoginInfoAsync(); returns null

### .NET Version

5

### Anything else?

![google_multiple_login](https://user-images.githubusercontent.com/5929142/149493206-2ea867c9-1878-45f2-b281-6a824aafefcb.png)

**Comment by adityamandaleeka** [comment]
Triage: Let's document this behavior in the docs to help others who will hit the same thing.

Might also consider changing the default for the External cookie to having SameSite None.

**Comment by mikekistler** [comment]
Thanks for contacting us. This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
