### ISSUE TITLE
SignalR TypeScript Client - The next event handler is not called if the previous event handler removes itself

### ISSUE THREAD

**Issue by mr-fedorof** [dotnet/aspnetcore#39512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The next event handler is not called if the previous event handler removes itself.

### Expected Behavior

All registered event handlers have to be called.

### Steps To Reproduce

```TypeScript
const connection = new HubConnectionBuilder();

...

function emitter1() {
    connection.off(eventName, emitter1);
    console.log('emitter1');
}

function emitter2() {
    console.log('emitter2');
}

connection.on(eventName, emitter1);
connection.on(eventName, emitter2);

```

When the first event comes in then only emitter1 is called, but not emitter2.

**Comment by adityamandaleeka** [comment]
Triage: this is happening because the underlying foreach is iterating over a modified collection. We could consider cloning the array before starting to iterate.

**Comment by BrennanConroy** [comment]
Affected area: https://github.com/dotnet/aspnetcore/blob/a899ce80c36138df814b3258093a21de3ca95c5c/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L678
