### ISSUE TITLE
Blazor is breaking build. We do not use Blazor. How to get rid of it.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39526]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-is-breaking-build-We-do-not-use-/1629617)._

---
[severity:I'm unable to use this version] [regression] [worked-in:It worked until I downloaded 2022]
I just downloaded Visual Studio 2022 to review, and it’s broken our Asp Core 5 app in Visual Studio 2019. 

When trying to build our Core 5 (in VS 2019) app I’m now getting a Blazor error:
“The scoped css file” [lots_of_css_files].css "was defined but no associated razor component or view was found for it"

We don’t use Blazor. It was never in our app. We don’t want it in our app. How do I get rid of it so our app will build?

Thanks.

---
#### Feedback Bot on 1/5/2022, 10:21 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and reporting this issue.
You can disable CSS Isolation feature using the `<ScopedCssEnabled>false</ScopedCssEnabled>` flag in your project.
This, however isn't intentional and we will look into ways to address this without forcing customers who migrate their apps to do this.
