### ISSUE TITLE
The Web Project Description Error ,OpenAPI OR OpenAI？

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39529]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Web-Project-Description-Error-OpenA/1626963)._

---
[regression] [worked-in:17.0.4]
! [OpenAPI-or-OpenAI.png] (https://aka.ms/dc/image?name=Be4663abe5585420ca530c7da3d8f9df8637767800375879538_OpenAPI-or-OpenAI.png&tid=e4663abe5585420ca530c7da3d8f9df8637767800375879538)

As The Image with the red rectangle , the tip of OpenAPI Support  is OpenAI  , interesting , haha

visual studio version:Microsoft Visual Studio Community 2022 (64 位)  版本 17.0.4

---
#### Feedback Bot on 1/4/2022, 00:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/4/2022, 02:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Here is the error: 
![image](https://user-images.githubusercontent.com/34246760/149569367-1249c3ff-8389-485e-b2f2-0025062d9d01.png)

**Comment by halter73** [comment]
Do we need to forward-port https://github.com/dotnet/aspnetcore/pull/38062 plus this fix to main?

**Comment by captainsafia** [comment]
Yep, I tracked down where the confusion was. https://github.com/dotnet/aspnetcore/pull/37367 added the option to the templates.

https://github.com/dotnet/aspnetcore/pull/38062 backported to release/6.0 _and_ added the translations.

**Comment by captainsafia** [comment]
This has already been fixed in both 6.0 and 7.0.
