### ISSUE TITLE
Please help add Blazor components for Fluid Framework 

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#39536]
### Describe the solution you'd like
While examples exist for other front-end frameworks like Angular, React and Vue, it would be nice to also have components to use Fluid framework from Blazor.

### Additional context

It would be nice to leverage real time update capabilities of Fluid framework from Blazor, without using Javascript frameworks like React.

**Comment by skylerjokiel** [comment]
Unfortunately the Fluid Framework is currently only supported in javascript. We are definitely excited about brining the power of Fluid to more languages but due to the client focused architecture this is a large undertaking.

**Comment by javiercn** [comment]
@bancroftway thanks for contacting us.

From what I understand, fluid is a data synchronization library for JavaScript. Offering a .NET version would be something that the people working on Fluid will do if they deem it worth it, whether its via JS interop or a native .NET implementation, it's not something that our team will handle. I suggest you file an issue directly on their GH repo as they'll be in a better position to help.

**Comment by javiercn** [comment]
@skylerjokiel let me know if I'm missing something here, (I'm not very familiar with Fluid)
