### ISSUE TITLE
"ASP.Net Core with React.js" template does not have a full/proper implementation of Reactstrap out-of-the-box, or as part of the demos.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39533]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNet-Core-with-Reactjs-template-do/1592440)._

---
[severity:I'm unable to use this version]
**Steps to Reproduce the Issue**

1. Install a fresh copy of _Windows 10 Professional_
2. Run all _Windows Updates_.
3. Install _Visual Studio 2019_ (version 16.11.7)
4. Install necessary tools for _Web Development_, including _Node.js_
5. Start _Visual Studio 2019_
6. After launch, select the _Create a new project_ option.
7. Choose either _ASP.Net Core with React.js_ or _ASP.Net Core with React.js and Redux_.  Both templates are broken.
8. Finish the wizard and finish creating the project.
9. After VS loads the new solution/project, hit **F5** to build and run the application.

**Expected Behavior**

When the page loads, you expect to see the new project's sample title on the left on the navbar, and then a drop-down menu option on the right with links to the three separate pages that are part of the template sample.  This is because the default project implements the Reactstrap `Navbar` object with a properly defined `NavbarToggler` with a `Collapse` and `NavItem` components.

**Actual/Broken Behavior**

The templates show a `Navbar` component with the app name, however, instead of seeing a properly rendered and working `Navbar` with a `NavbarToggler`, you see a list of links ordered in a row on the Navbar.

The is a bigger problem than just the Navbar component in the demo.  The default implementation of the Bootstrap/Reactstrap tools cannot implement any collapsible components such as _Dropdown_ components or other Navbar items, so even if you delete the code in NavMenu.js and implement your own Bootstrap code, it will not work.

**Notes**

I included the steps for a fresh Win10 install because this has been a long journey just to get these templates to work "out of the box".  I would like to create a new project within Visual Studio and use React and I have actually re-installed VS within a re-imaged PC to try and get this to work.  

Building and running the project is not an issue. However, since these critical third-party libraries are broken within the VS templates, finding how to fix the broken implementations has been difficult , especially since the browser does not report any specific errors in the code, nor does IntelliSense find any issues.

Collapsible menus are a critical part of most applications and I'm personally fond of, and familiar with, Bootstrap components.  Please fix this.

---
#### Feedback Bot on 11/22/2021, 10:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/23/2021, 02:03 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
We will consider this feedback as part of the template update work we will do as part of .NET 7.
