### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.DevServer 6.0.1 Update not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39531]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftAspNetCoreComponentsWebAssem/1621679)._

---
[severity:It bothers me. A fix would be nice]
I created a standard Blazor WEB Assembly project and updated Microsoft.AspNetCore.Components.WebAssembly.DevServer/Microsoft.AspNetCore.Components.WebAssembly to version 6.0.1 . After that I can't start to debug the project. The error is:
The target process terminated without raising an event to start CoreCLR. Verify that the target process is configured to use .NET Core. This may be expected if the target process is not under . NET code.
The program "[26328] dotnet.exe" was terminated with code 2147516566 (0x80008096).

---
#### Feedback Bot on 12/23/2021, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/24/2021, 00:23 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Internal ticket: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1454427

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by TanayParikh** [comment]
Hello, thanks for contacting us. I'm unable to reproduce this issue:

![image](https://user-images.githubusercontent.com/14852843/151456145-4c8d9c64-3ed7-4748-bc30-b55f1e43d2d6.png)

If you're still experiencing this issue, kindly provide a minimal, public, github repository which reproduces the issue and leave a comment here 😄
