### ISSUE TITLE
AddAuthentication doesn't contain AddMicrosoftAccount

### ISSUE THREAD

**Issue by victorquanlam** [dotnet/aspnetcore#39543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created an ASP.NET Core 6 with React Template and Individual Accounts Authentication Type project. I added Microsoft Authentication and received this error below:
![image](https://user-images.githubusercontent.com/53363594/149614525-261c17db-562e-465b-a901-1d530f256cce.png)

### .NET Version

6

**Comment by Kahbazi** [comment]
@victorquanlam Have you installed the [Microsoft.AspNetCore.Authentication.MicrosoftAccount](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.MicrosoftAccount) nuget package?

**Comment by victorquanlam** [comment]
Yeah that's right I haven't got it installed yet. Thanks for your quick reply.
