### ISSUE TITLE
Unable to render script inside blazor component

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#39557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to embed `github gist` in my `.net 6 blazor wasm` application. `<script>` tag in general is not allowed inside blazor component. so I added it as `MarkupString` as shown below,

```razor
@(new MarkupString(@"<script src=""https://gist.github.com/fingers10/44eb8a5a5427b472d1c48ecb1b4268f7.js""></script>"))
```

But the rendered output is empty. When I inspected the html using browser, no such content is present in html.

### Expected Behavior

Script should be added in html document and needs to be executed for github gist to be rendered.

### Steps To Reproduce

1. Create new blazor wasm project.
2. Create a new component.
3. Add the following `MarkupString` in the component html `@(new MarkupString(@"<script src=""https://gist.github.com/fingers10/44eb8a5a5427b472d1c48ecb1b4268f7.js""></script>"))`
4. Run the application.

### .NET Version

6.0.101

**Comment by KristofferStrube** [comment]
I have tried to execute the steps to reproduce and I get a script tag in my DOM so this does not seem to be a problem.
```razor
@page "/"

@(new MarkupString(@"<script src=""https://gist.github.com/fingers10/123456.js""></script>"))
```

Result:
```html
<html lang="en">
   <head>
      <!--- Unrelated --->
   </head>
   <body>
      <div id="app">
         <!--!--><!--!--><!--!--><!--!--><!--!--><!--!--><script src="https://gist.github.com/fingers10/123456.js"></script><!--!-->
         <!--!-->
      </div>
      <!--- Unrelated --->
   </body>
</html>
```

To dynamically import or execute JS scripts I would recommend to take a look at [JS interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0).

If you don't need it to be dynamic then I would recommend to add it to your wwwroot/index.html file.

**Comment by javiercn** [comment]
@KristofferStrube thanks for contacting us.

I'm not sure what the compiler output is, but I imagine is not detecting that as a rendering operation. It's likely that if you put the markup content in a variable and render that, it will work.

Let us know if that's not the case.

**Comment by fingers10** [comment]
@javiercn I tried adding the `MarkupString` as variable but still the scipt is getting added in component html but not getting rendered.

**Test.razor.cs:**
```cs
public class TestBase: ComponentBase
{
    protected MarkupString snippet => new MarkupString(@"<script src=""https://gist.github.com/fingers10/44eb8a5a5427b472d1c48ecb1b4268f7.js""></script>");
}
```

**Test.razor:**
```cshtml
@page "/test"
@inherits TestBase

@snippet
```

**Actual Output:**
```html
<!--!--><script src="https://gist.github.com/fingers10/44eb8a5a5427b472d1c48ecb1b4268f7.js"></script><!--!-->
```

**Expected Output:**

**Html:**
![Rendered Html Markup for Github Snippet](https://user-images.githubusercontent.com/43729469/149802602-b3f888e9-0092-437f-b246-5f28ac9a9f68.png)


**Rendered Html:**
![Github Code Snippet Rendering Expected Output](https://user-images.githubusercontent.com/43729469/149802300-3611578d-315f-44f4-9838-865e975501f2.png)


@javiercn Please can you assist further?

**Comment by KristofferStrube** [comment]
Hey @fingers10 if you need af workaorund for now then this works:

```razor
@inject IJSRuntime JSRuntime

@JSRuntime.InvokeVoidAsync("document.write", @"<script src=""https://gist.github.com/fingers10/44eb8a5a5427b472d1c48ecb1b4268f7.js""></script>")
```

**Comment by fingers10** [comment]
@KristofferStrube I ended up improving your answer as component,

**GithubGistSnippet.razor:**
```razor
@inherits GithubGistSnippetBase

<section class="[ flex flex-col ]">
    <h4 class="[ bg-gray-200 ] [ p-2 ] [ font-semibold ] [ text-black ] [ flex items-center ]">
        <svg xmlns="http://www.w3.org/2000/svg" class="[ icon icon-tabler icon-tabler-code ] [ text-purple-700 ] [ fill-purple-500 ]" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <polyline points="7 8 3 12 7 16"></polyline>
            <polyline points="17 8 21 12 17 16"></polyline>
            <line x1="14" y1="4" x2="10" y2="20"></line>
        </svg> Code Sample - @Title
    </h4>
    <article id="@Id" class="[ bg-gray-300 ]">
    </article>
</section>
```

**GithubGistSnippet.razor.cs:**
```cs
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;

namespace Web.Components;

public class GithubGistSnippetBase : ComponentBase, IAsyncDisposable
{
    private IJSObjectReference? module;

    protected string Id = Guid.NewGuid().ToString();

    [Inject] private IJSRuntime JSRuntime { get; set; } = default!;

    [Parameter, EditorRequired] public string Title { get; set; } = default!;
    [Parameter, EditorRequired] public string UserId { get; set; } = default!;
    [Parameter, EditorRequired] public string FileName { get; set; } = default!;

    protected override async Task OnInitializedAsync()
    {
        module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./js/githubgist.js");

        await module.InvokeVoidAsync("printSnippetFrom", Id, UserId, FileName);
    }

    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (module is not null)
        {
            await module.DisposeAsync();
        }
    }
}
```

**githubgist.js:**
```js
export function printSnippetFrom(id, userId, filename) {
    const target = document.getElementById(id);
    const iframe = document.createElement('iframe');
    const iframeId = `${userId}-${filename}`;
    iframe.setAttribute("id", iframeId);
    iframe.setAttribute("width", "100%");
    target.appendChild(iframe);

    let doc = iframe.document;
    if (iframe.contentDocument) doc = iframe.contentDocument;
    else if (iframe.contentWindow) doc = iframe.contentWindow.document;

    const gistScript = `<script src="https://gist.github.com/${userId}/${filename}.js"></script>`;
    const styles = "<style>*{font-size:12px;}</style>";
    const resizeScript = `onload="parent.document.getElementById('${iframeId}').style.height=document.body.scrollHeight + 'px'"`;
    const iframeHtml = `<html><head><base target="_parent">${styles}</head><body ${resizeScript}>${gistScript}</body></html>`;

    doc.open();
    doc.writeln(iframeHtml);
    doc.close();
}
```

**Usage:**
```razor
<GithubGistSnippet Title="DeSerialization" UserId="fingers10" FileName="44eb8a5a5427b472d1c48ecb1b4268f7"></GithubGistSnippet>
```

**Output:**
![GithubGistSnippet Component Output](https://user-images.githubusercontent.com/43729469/149861130-a75f88a8-0fa5-41d5-8cf0-a226164d43e5.png)

**Comment by javiercn** [comment]
@fingers10 I think I remember now and I don't believe we support `@value` with a markup string. I think the RenderTreeBuilder API needs to be used explicitly in this case, since we don't know while we are compiling the type for `@(expression)`.
