### ISSUE TITLE
Blazor connects to Vue/react/angular

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/aspnetcore#39562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

At present, blazor components are directly connected to HTML elements and events. It is easy to c# develop blazor components based on HTML CSS. But the workload is heavy.

Vue has many ready-made components. I was wondering whether to connect the blazor component to the Vue component. Specifically, the properties of the blazor component are connected to the properties of the Vue component. When the properties of the blazor component are changed, the properties of the Vue component are automatically updated, and finally the HTML element is updated. Events can be similar.

In this way, we can easily migrate the existing Vue component library to blazor. The same method is also applicable to react and angular.

Note that this is different from generating Vue and react components from blazor. The latter has blazor first and then generates the target components, which cannot use the existing component libraries of Vue and react.

### Describe the solution you'd like

I think JS interoperability can achieve this goal, but it is difficult for me.
Can the official provide such ideas or documents?

**Comment by javiercn** [comment]
@bxjg1987 thanks for contacting us.

This is not something we plan to work on the near future, we suggest you take a look at the integrations we did for JS root components with custom elements,  React and Angular and use that as a basis for implementing the same thing in the opposite direction.

In general, Blazor only knows about attributes, so we would suggest you wrap your vue, angular, react, etc elements on a custom element and react to attribute changes on those. From there, your custom elements will behave like any other element with regards to Blazor.
