### ISSUE TITLE
Inject a Blazor component instance into the app?

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#39560]
Hello. 
Suppose I have a Blazor Server application and a StatusBar component.
This component shows various status messages at the bottom of any page.
The status bar is static. It is a part of the layout just like NavMenu or top row with links as seen in the Blazor Server project template.
There should be 1 instance per user (circuit), so the instance scope is "Scoped",
Every component in the app must be able to put a message in this statusbar.

Program.cs:

`services.AddScoped<StatusBar>();
`

MainLayout.razor

![github aspnet](https://user-images.githubusercontent.com/64279914/149678253-ff4008ed-896c-4782-abcd-201b416ce4f1.png)

The result is `BlazorApp1.Components.Custom.StatusBar` printed in the place where the status bar should be rendered.
That means .ToString() method had been called instead of rendering the StatusBar.

I see that there is `@Body` which is a RenderFragment. The way to render the statusbar is probably using this technique. How can it be done? I haven't found a way to render an **_existing instance of a component_**. Is it even possible?

A workaround is: 

- not using DI for the StatusBar and instead:
- using a scoped StatusBarService which contains StatusBar reference
- the StatusBar reference is filled upon first render of the StatusBar (the StatusBar registers itself in the StatusBarService
- in MainLayout.razor, the StatusBar is declared as `<StatusBar/>` so in fact an instance is created in-place

But this workaround is not a nice solution as injecting the component instance everywhere.

Edit: I am sorry for adding the markup content if MainLayout as image but displaying XML markup does not work here

**Comment by oiBio** [comment]
i think your workaround is the right way. just dont fill it with the StatusBar reference. You should instead put only the properties in there that you need in the component. E.g. "DisplayText", "Icon" etc...

Then set your StatusBar component so that it works with the properties from the service, or displays only these.

To make the update work, you should register an event and execute a StateHasChanged in the StatusBar component, if the property in the service changes.

**Comment by javiercn** [comment]
@janseris thanks for contacting us.

Don't register the component in DI as a scoped service, Blazor controls the lifetime of the component instances and what you are doing can lead to bad rendering bugs and potential memory leaks.

Instead, create a scoped service that every component can reference and register an event on your status bar component to receive change notifications and update the UI.
