### ISSUE TITLE
Failed to find runtime module (coreclr.dll or clr.dll or libcoreclr.so), 0x80004002

### ISSUE THREAD

**Issue by felixxu06** [dotnet/aspnetcore#39564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`PS C:\dumps> dotnet-dump analyze .\my.gcdump
Loading core dump: .\my.gcdump ...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the session.
> clrstack
Failed to find runtime module (coreclr.dll or clr.dll or libcoreclr.so), 0x80004002
Extension commands need it in order to have something to do.
For more information see https://go.microsoft.com/fwlink/?linkid=2135652
> dumpobj
Failed to find runtime module (coreclr.dll or clr.dll or libcoreclr.so), 0x80004002
Extension commands need it in order to have something to do.
For more information see https://go.microsoft.com/fwlink/?linkid=2135652
> q
PS C:\dumps> dotnet --list-sdks
2.1.818 [C:\Program Files\dotnet\sdk]
2.1.818 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
PS C:\dumps> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]`

### Expected Behavior

display the corresponding clrstack or dumpobj information in the console.

### .NET Version

.net core 3.1

**Comment by javiercn** [comment]
@felixxu06 thanks for contacting us.

I've opened an issue in dotnet/diagnostics where they'll be better able to help you.

**Comment by mikem8361** [comment]
What is the complete version of the runtime you are targeting (the x in 3.1.x)?  You have quite a few 3.1 versions installed.  

What does `sosstatus` display?  Can you enable logging with `logging enable` before running `clrstack`? 

Thanks.

**Comment by felixxu06** [comment]
@mikem8361 
Hi Mike, Thanks for reaching out. Following is the information. Not quite sure why so many 3.1 versions installed.
When I install VS 2019, I install one. I have manually installed one 3.1 SDK. 

Following is the information printed in my console while enabling the log
```
PS C:\dumps> dotnet-dump analyze .\my.gcdump
Loading core dump: .\my.gcdump ...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the session.
> logging enable
Logging is enabled
> sosstatus
Target OS: WINDOWS Architecture: X64 ProcessId: 16960 (0x4240)
Dump path: C:\dumps\my.gcdump

Directory: C:\dumps
Cache: C:\Users\felix.xu\AppData\Local\Temp\SymbolCache
Server: https://msdl.microsoft.com/download/symbols/
> clrstack
dotnet-dump Information: 0 : SOS initialized: sosPath 'C:\Users\felix.xu\.dotnet\tools\.store\dotnet-dump\6.0.257301\dotnet-dump\6.0.257301\tools\netcoreapp3.1\any\win-x64\sos.dll'
Failed to find runtime module (coreclr.dll or clr.dll or libcoreclr.so), 0x80004002
Extension commands need it in order to have something to do.
For more information see https://go.microsoft.com/fwlink/?linkid=2135652
dotnet-dump Error: 0 : SOS command FAILED 0x80004002
```
