### ISSUE TITLE
aspnetcore reporting tool

### ISSUE THREAD

**Issue by Jcitaato7** [dotnet/aspnetcore#39579]
Please which reporting tools ship with aspnetcore/net6.0?

**Comment by javiercn** [comment]
@Jcitaato7 thanks for contacting us.

It's not clear what you are asking for, but we do not provide any reporting tool as part of the framework. Depending on what you are trying to do, other products can offer integration with ASP.NET Core, but I'm not aware of any. There might be third-party solutions you might be able to leverage in this space, but we can't make a concrete recommendation.

**Comment by Jcitaato7** [comment]
@javiercn thanks for the reply
I am migrating a simple .NET Framework application to ASPNETCore. My problem is with the rdlc reports in the .NET project. It seems the rdlc reports are not supported in .NET Core.
can you please suggest other alternatives that I can use to get the rdlc reports working in .NET Core? Thanks
