### ISSUE TITLE
Use server garbage collection in the Worker Service project template

### ISSUE THREAD

**Issue by ghelyar** [dotnet/aspnetcore#39578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Creating a worker service project with `dotnet new worker` does not enable server garbage collection by default, but it seems like it should, as it's similar to a web service project - likely to be a long-running application with a `BackgroundService` and a generic host builder. Web service projects do enable server GC by default.

`Microsoft.NET.Sdk.Worker` could use `<ServerGarbageCollection>true</ServerGarbageCollection>`, or the `worker` project template could put it in the generated project file.

I used `System.Runtime.GCSettings.IsServerGC` to test this.

**Comment by gfoidl** [comment]
I don't agree nor disagree (as it depends on the use-case) -- tendency is to enable it as proposed.

But there should be at least a hint* (like link to docs on GC) on how to enabled / disable server-GC, as a lot of people aren't even aware that there's a difference in GC-modes.

\* either in the docs or even better as comment in the project file

**Comment by adityamandaleeka** [comment]
Triage: It's not clear that server GC should be on for this template (since as mentioned above, the decision is dependent on a lot of factors that can vary by use-case). See also https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc

**Comment by ghelyar** [comment]
Could you at least make it more obvious that it's not using server GC by default? e.g. add it to the docs or add it to the generated project file but leave it as false?

**Comment by adityamandaleeka** [comment]
That might be worth considering.

**Comment by adityamandaleeka** [comment]
cc @IEvangelist to get this into the docs

**Comment by IEvangelist** [comment]
> cc @IEvangelist to get this into the docs

Hi @adityamandaleeka - captured here: https://github.com/dotnet/docs/issues/27945

**Comment by adityamandaleeka** [comment]
Thanks @IEvangelist!

**Comment by adityamandaleeka** [comment]
Looks like this has been done (https://github.com/dotnet/docs/pull/27952). Closing issue.
