### ISSUE TITLE
submit form js/c# from outside without having submit button 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#39574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In blazor having an EditForm like this:
`<EditForm id="form1"`
I noticed that in js if you call:
`$('#form1').submit()` - the page will reload
`$('#form1 [type=submit]').click()` - it will submit the form normally (no reload, blazor OnValidSubmit action executed)
seems that the blazor js somehow handles form submits but only in certain situations

the only way for me to submit from outside the form is by having a button like this:
`<button type="submit" form="form1" class="awe-btn">submit</button>`

### Describe the solution you'd like

but I would like to avoid having `id` defined on the form (in js I can identify the form without id)

is there a way (C# or js)  to submit a blazor EditForm from a click outside the `<form>`  ?

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

It's not clear to us what you are trying to do. Are you trying to submit the form bypassing Blazor or trigger the event in Blazor from JavaScript.

**Comment by omuleanu** [comment]
@javiercn I want to place the submit button outside the form,
and I tried to do it using js:
`<button onclick='mysubmit(event)'`
` $(event.target).parent().find('form').submit()`
I doesn't matter if I bypass blazor or not

**Comment by javiercn** [comment]
@omuleanu thanks for the clarification.

I don't think that's something we support.

/cc: @SteveSandersonMS in case he has any thoughts

**Comment by omuleanu** [comment]
my current solution is to do something like this:
```
$('#form1').append('<input type="submit"/>'); 
$('#form1').find('[type=submit]').click();
```

**Comment by KristofferStrube** [comment]
Hey @omuleanu,

You can check if the form is valid programmatically and make a check for that like so:

```razor
@using System.ComponentModel.DataAnnotations

<EditForm @ref=@editForm Model=@exampleModel >
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText id="name" @bind-Value="exampleModel.Name" />
</EditForm>

<button @onclick="Submit">Submit</button>

@code {
    protected ExampleModel exampleModel { get; set; } = new();

    protected EditForm editForm { get; set; }

    private void Submit()
    {
        if (editForm.EditContext.Validate())
        {
            Console.WriteLine("Valid Submit");

            // Handle Submit
        }
    }

    public class ExampleModel
    {
        [Required]
        [StringLength(10, ErrorMessage = "Name is too long.")]
        public string Name { get; set; }
    }
}
```

**Comment by SteveSandersonMS** [comment]
As far as I know you can use normal JS APIs to dispatch a `submit` event directly on the `<form>` element: https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#creating_custom_events

**Comment by omuleanu** [comment]
@SteveSandersonMS yes, you can, and it will reload the page (native/unhandled behaviour), but when you click a submit button inside the form the reload doesn't happen, blazor action will be executed instead (handled behaviour)

**Comment by SteveSandersonMS** [comment]
@omuleanu Is it possible you didn't configure your event to bubble? Could you show the code you're using to trigger the event?

**Comment by omuleanu** [comment]
@SteveSandersonMS I tried both jquery:
`$('#form1').stubmit()`
and js:
`$('#form1')[0].stubmit()`
I haven't configured anything.
Maybe this is what you're mentioning:

> The event is not sent to the form when calling the form.submit() method directly.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

**Comment by SteveSandersonMS** [comment]
I'm not suggesting those APIs. I'm suggesting the use of `dispatchEvent` as in the link from above: https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#creating_custom_events. Remember to configure the `Event` instance to enable bubbling: https://developer.mozilla.org/en-US/docs/Web/API/Event/bubbles

**Comment by SteveSandersonMS** [comment]
Note that you don't need to call `addEventListener` because Blazor is already listening for the event and has its own handler.

**Comment by omuleanu** [comment]
the solution was to call:
`$('#form1')[0].dispatchEvent(new Event('submit'));`
Thanks @SteveSandersonMS
