### ISSUE TITLE
Authentication Error with Latest Microsoft.AspNetCore.Authetication.JwtBearer(6.0.1)

### ISSUE THREAD

**Issue by vivekgunnala-sl** [dotnet/aspnetcore#39586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As part of our package upgrades, we have updated to the latest Authentication.JwtBearer package. Since then we are getting a token error, where we are unable to authenticate the JWT token from different schemes. The error seems to be originating from the AuthenticateSync function. 

**Package Name** - "Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.1"
**Authentication Middle ware-** https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs

_Note: Authentication is working fine till version 5.0.13, post that version 6.0.0 and 6.0.1 are failing to authenticate JWT tokens._

### Expected Behavior

Authentication should be successful, with multiple schemes.

### .NET Version

.net 6

**Comment by vivekgunnala-sl** [comment]
@pranavkm

**Comment by Tratcher** [comment]
What was the exact error and stack trace?

Please provide a minimal project that reproduces this error.

**Comment by vivekgunnala-sl** [comment]
> What was the exact error and stack trace?
> 
> Please provide a minimal project that reproduces this error.

Error Details

No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).

we don't want to specify default JWT scheme.

**Comment by Tratcher** [comment]
I still need the stack trace and some example code to see how you were calling into the authentication stack.

**Comment by vivekgunnala-sl** [comment]
found the fix. nuget package "System.IdentityModel.Tokens.Jwt" is missing. as one of the dependencies of package "Microsoft.AspNetCore.Authentication.JwtBearer" post version 6.x.x. working with latest version of both..

Thanks @Tratcher  for your time.

**Comment by zblesk** [comment]
Adding that package fixed the issue for me as well. Thanks, @vivekgunnala-sl.
