### ISSUE TITLE
Blazor WASM PWA not returning static files from wwwroot on first request after publish due to service worker cache

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#39592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a image placed inside `wwwroot\images\image.png` in my `blazor wasm` app. After publishing, when I request the image for the first time in browser with URL `https://localhost/images/image.png` browser gets `404` response. Now if I press `Shift` + `F5` the image is getting served in browser. I think blazor routing has some issues with explicit static file request handling. I'm not sure. Please can anyone assist me?

### Expected Behavior

The requested static file from `wwwroot\images\image.png` should be served instead of `404` or without pressing `Shift` + `F5`

### Steps To Reproduce

1. Create new `.net 6 blazor wasm` app.
2. Add a image file inside `wwwroot\images\image.png`.
3. Publish the app.
4. Now run the published version and request the `image.png` via `https://localhost:port/images/image.png`.
5. You should get `404` in browser.
6. Now press `Shift` + `F5`, image will be served.

### .NET Version

6.0.101

### Anything else?

```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @javiercn can you please take a look at this? Thanks!

**Comment by javiercn** [comment]
@fingers10 thanks for contacting us.

Is your application being hosted on an asp.net core process or is it a standalone blazor app?

Is the file available in the wwwroot folder of the published app? (I suspect so, given the fact that a hard refresh makes the file show up).

Are you able to reproduce this behavior in an incognito window? (fresh browsing context)

Are you hosting your app on the same origin during development and publish?

**Comment by fingers10** [comment]
@javiercn here are the responses,

1. This is a standalone blazor wasm app.
2. Yes file is available in wwwroot after publish.
3. No. I don't face this issue in Incognito Window.
4. Yes.

You can try this url - https://ilovedotnet.org/image/blogs/blazor/wasm/blazor-wasm-exception-handling-and-error-boundary-1200w.png

This is a production version of the issue that I'm facing in my blazor wasm app hosted in github pages. I have also faced similar issues when hosting the blazor wasm app in IIS.

This [stackoverflow post](https://stackoverflow.com/questions/67385162/blazor-wasm-not-serving-static-files-from-wwwroot-after-deploying-to-iis) is related to this issue. This is for additional reference.

**Comment by javiercn** [comment]
@fingers10 @fingers10 this seems to be an artifact produced by a combination of causes:
* Using the same origin for development and development.
* Using a non-clean browser context.

It's likely that something from your dev environment is remaining cached and its causing the issue when you visit the site the first time in production. This is an "artificial" artifact caused by the two things mentioned above rather than a "real" issue (as in your users won't observe this behavior).

I would suggest a few things to mitigate it. Configure caching headers for your assets appropriately if needed, and avoid reusing a context between development and production.

Blazor routing doesn't play any role in handling images, we only intercept navigations from `a` elements with `href` targeting somewhere in the URL space.

**Comment by javiercn** [comment]
@fingers10 something you can check also is if when this happens the request is actually sent to IIS or if the browser itself is returning the response directly. 

Also, for completeness. Does this happen to be a PWA?

**Comment by fingers10** [comment]
@javiercn ,

I'm using different origin in development and production. And yes my blazor app is PWA configured.

Please can you assist on how to check if the request is sent to IIS or returned from browser?

Also any inputs on how to to devise cache strategy for blazor wasm static assets?

**Comment by javiercn** [comment]
> Please can you assist on how to check if the request is sent to IIS or returned from browser?

You can check on the network tab of the browser (edge/chrome and it should tell you where the file is retrieved).

Another option would be to use Fiddler or a similar tool to intercept the traffic from the browser to the deployed app. That would show up if the request is being sent to IIS.

**Comment by fingers10** [comment]
I'll share detailed analysis.

**Comment by fingers10** [comment]
@javiercn I have updated the issue with needed details above.

**Comment by javiercn** [comment]
@fingers10 I would suggest you check the response here:

![image](https://user-images.githubusercontent.com/6995051/150375327-fd622949-e17d-405d-b63f-d22297a6a8bf.png)

It seems that its coming from the service worker installed in the app, so I would check the service worker code to understand what's happening.

It can be that somehow the image isn't being correctly cached by the service worker or that a new version of the service worker needs to be updated.

**Comment by brischt** [comment]
Is there actually any workaround for this? We have an application that serves static pdfs, and this issue prevents us from going live.

**Comment by javiercn** [comment]
@brischt please file a separate issue with a minimal repro project, otherwise it's much harder for us to get the right context.

**Comment by javiercn** [comment]
@fingers10 The issue here has nothing to do with static web assets but with the fact that the service worker is caching the data.

**Comment by fingers10** [comment]
@javiercn thanks for pointing out. But this service worker code comes with default blazor web assembly template with pwa enabled. Can this be updated in default template?

**Comment by fingers10** [comment]
@javiercn Here is the [https://github.com/fingers10/BlazorWasmPwaStaticFileIssue](Sample Repo) to reproduce this issue.

**Comment by brischt** [comment]
@javiercn Do you still need a repro from me, or is @fingers10 's repro sufficient?

**Comment by fingers10** [comment]
@javiercn please can you assist? Is this fixed? The status has been changed to closed.

**Comment by fingers10** [comment]
@javiercn and @brischt  I have made below changes in the service-worker.js

From this,

`const shouldServeIndexHtml = event.request.mode === 'navigate';`

to this,

`const shouldServeIndexHtml = event.request.mode === 'navigate' && new URL(event.request.url).pathname === '/';`

This now loads the correct content without force reload. @javiercn Please can you help to validate. The issue seems to be closed without resolution.

**Comment by javiercn** [comment]
@fingers10 on second look, I think there is some improvement we can do here. I've filed a separate issue with the team for discussion.

Your solution doesn't work in the sense that it would prevent users from navigating to pages like `/counter` when the app is offline. You can try out the more detailed proposal that I made on the new issue below:

https://github.com/dotnet/aspnetcore/issues/40678

**Comment by blakepell** [comment]
@fingers10 I used your solution and it worked for me, thank you for sharing (I'm not concerned about offline usage).  All of my JavaScript resources weren't loading after the first load without a hard refresh (index.html got served for them which would manifest as `Uncaught SyntaxError: Unexpected token '<'` or an integrity failure (since the index.html served didn't match the sha hash for the JavaScript file that was supposed to be loaded, in my case those were the bootstrap and jQuery bits).
