### ISSUE TITLE
Blazor Server app not find static file when changing environment from Development

### ISSUE THREAD

**Issue by Kuznetsov-Alexey** [dotnet/aspnetcore#39596]
**Is there an existing issue for this?**
Issue with environment's name, but linked to a hot reload supporting in Blazor WebAssembly app.
#39269 

**Describe the bug**
When launching application on local machine with any Environment name different from "Development", application can't find "{name of startup project}.styles.css" file and shows page without any styles.

**Expected behavior**
Loading of static files should not depend on the environment's name.
We have a situation, when need in different names for environments during development. But now this possibility is not available.

**Steps to reproduce**
1. Create new Blazor Server application.
2. Change ASPNETCORE_ENVIRONMENT in the project's launchSettings.json from "Development" to anything else.
3. Start application via changed profile.

**.NET Version**
6.0.100

**Solution with reproduced bug**
[TestEnvironmentBlazorApp.zip](https://github.com/dotnet/aspnetcore/files/7887691/TestEnvironmentBlazorApp.zip)

**Additional information**
Application can not find static files from Razor class libraries when environment name is different from "Development".

**Comment by javiercn** [comment]
@Kuznetsov-Alexey thanks for contacting us.

This is by design. We only enable static web assets by default in Development as it serves random paths from disk. If you want to enable them in an environment other than development, you need to do so explicitly by calling StaticWebAssetsLoader.UseStaticAssets

**Comment by Kuznetsov-Alexey** [comment]
@javiercn thank you so much for fast and understandable response.

Just implemented and all works perfectly as expected.
