### ISSUE TITLE
Reminder for #33785

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#39598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a reminder for issue #33785 which got closed to inactivity again.

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

For future reference please comment on the issue and we'll consider taking action to re-open the issue if we think its appropriate, otherwise it creates more tracking work for us.

**Comment by javiercn** [comment]
@SteveSandersonMS can you take a look at the original issue since you were assigned on it?

**Comment by SteveSandersonMS** [comment]
I'll reopen the original issue.
