### ISSUE TITLE
InstallVisualStudio.ps1 and BuildFromSource.md should update to VS 2022

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#39599]
### Describe the bug

The install script and doc both still assume people want to use VS2019. I got a bit confused just now because my machine only has 2022 and `InstallVisualStudio.ps1` was trying to make me install 2019 (because I didn't know to pass `-Version`), and the doc only talks about 2019.

Since 2022 is now GA, everything could move to that by default

### Expected Behavior

Use VS 2022

### Steps To Reproduce

Try to build the repo following instructions.

**Comment by adrianwright109** [comment]
I'm happy to submit a PR to remove VS 2019 and make VS 2022 the default if this change is desired for this repo.

**Comment by dougbu** [comment]
Many thanks to @DamianEdwards for 9217656f967cc6d040071df73b99cd94fddc5e84

**Comment by DamianEdwards** [comment]
I think 45376ce136c837f434906664c7a890a35c7dd887 is more specific to this issue 👍
