### ISSUE TITLE
Blazor Download File From Stream Error

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#39603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documentation here results in an error. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0

```csharp
@code {
    private async Task DownloadFileFromStream()
    {
        var fileStream = GetFileStream();
        var fileName = "log.bin";

        //the using statement here causes an exception.
        using var streamRef = new DotNetStreamReference(stream: fileStream);

        await JS.InvokeVoidAsync("downloadFileFromStream", fileName, streamRef);
    }
}
````

### Expected Behavior

Code should not result in an exception. Removing the using statement seems to fix the issue but this seems like it would result in a memory leak. At best the documentation should address this. It is unclear of how to properly dispose of the stream reference without creating resource leaks.

### Steps To Reproduce

Run the code sample in the post. 

### Exceptions (if any)

Microsoft.JSInterop.JSException: Failed to fetch

### .NET Version

6.0.101

**Comment by groogiam** [comment]
[Repro39603.zip](https://github.com/dotnet/aspnetcore/files/7891071/Repro39603.zip)

See attached repro. The issue manifests when the DotNetStreamReference is wrapped in helper function as in the JsInteriopService class.

**Comment by TanayParikh** [comment]
> [Repro39603.zip](https://github.com/dotnet/aspnetcore/files/7891071/Repro39603.zip)
> 
> See attached repro. The issue manifests when the DotNetStreamReference is wrapped in helper function as in the JsInteriopService class.

Thanks @groogiam. Unfortunately we aren't able to open zip files. Could you please provide the repro as a public github repository so I may take a look. Also, please ensure it is a **minimal** repro. Meaning everything needed to reproduce the issue should ideally be in one file, and there shouldn't be any unnecessary classes, functions, etc, that aren't core to the repro. This is required so we may focus on the core issue, rather than delving into debugging user code 😄.

**Comment by TanayParikh** [comment]
Hello @groogiam, thanks for the repro. I took a look, and narrowed down the repro a bit more:

```razor
@page "/"
@inject IJSRuntime _js

<PageTitle>Index</PageTitle>

<button @onclick="DownloadFileFromStream">
    Download File From Stream
</button>

@code {
    private async Task DownloadFileFromStream()
    {
        var fileName = $"{DateTime.Now.ToFileTime()}_log.json";
        await using var ms = new MemoryStream(new byte[100000]);
        
        //works
        //using var streamRef = new DotNetStreamReference(ms);
        //await JS.InvokeVoidAsync("downloadFileFromStream", fileName, streamRef);

        //does not work
        await DownloadFromStream(fileName, ms);
    }


    public ValueTask DownloadFromStream(string fileName, Stream data)
    {
        //using causes exception
        using var streamRef = new DotNetStreamReference(data);
        return _js.InvokeVoidAsync("downloadFileFromStream", fileName ?? string.Empty, streamRef);
    }
}
```

Essentially what's happening here is in your `DownloadFromStream` function, you're using a `using` statement, which causes the `streamRef` to be disposed when the function finishes execution. However, you're returning the `streamRef` for async execution outside of the scope of the function. You'll therefore be using a reference after it's been disposed leading to your error. Notice in the docs we do:

```csharp
    private async Task DownloadFileFromStream()
    {
        var fileStream = GetFileStream();
        var fileName = "log.bin";

        using var streamRef = new DotNetStreamReference(stream: fileStream);

        await JS.InvokeVoidAsync("downloadFileFromStream", fileName, streamRef);
    }
```

The key difference being, we `await` the async invocation, thereby the `stremRef` isn't disposed before it can be utilized. Likewise, if you do everything within the original `DownloadFileFromStream` function you don't get this issue as you're awaiting the result. [This](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#remarks) may be a helpful resource for understanding how `using` statements are scoped.

**Comment by groogiam** [comment]
@TanayParikh Makes sense. I probably should have noticed that noticed that I did not await that call. Thanks for taking the point out and clearly explain the logic issue.
