### ISSUE TITLE
Error building src/Components in VS 2022

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#39601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`src/Components` gives a build error in VS, even though it builds OK in CLI.

See *Steps To Reproduce*

### Steps To Reproduce

 * Get to a clean repo state: `git clean -xdf`
 * `.\eng\build.cmd`  - succeeds
 * `cd src/Components`
 * `startvs.cmd` - I'm using VS 2022 17.0.5
 * Build solution via ctrl+shift+b

Expected: builds successfully, given that the whole thing was already built successfully in CLI

Actual:

```
CSC : error CS0006: Metadata file '(repopath)\artifacts\bin\Microsoft.AspNetCore.Server.Kestrel.Transport.Quic\Debug\net7.0\ref\Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll' could not be found
```

**Comment by campersau** [comment]
`Microsoft.AspNetCore.Server.Kestrel.Transport.Quic` is missing in a lot of `slnf` files.

**Comment by SteveSandersonMS** [comment]
Thanks @campersau - that does fix it. https://github.com/dotnet/aspnetcore/issues/39601
