### ISSUE TITLE
Update IdentityModel dependency

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#39612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would like to configure the `OpenIdConnectOptions`  for each request.
As the `OpenIdConnectHandler` requires an `IOptionsMonitor` (singleton), I registered the services as scoped like this: 

```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped<IOptionsMonitor<OpenIdConnectOptions>, OptionsMonitor<OpenIdConnectOptions>>();
builder.Services.AddScoped<IOptionsMonitorCache<OpenIdConnectOptions>, OptionsCache<OpenIdConnectOptions>>();
```

It seems from .NET 6, this way of doing things causes a memory leak (the memory keeps growing):

![NET 6](https://user-images.githubusercontent.com/64366368/150004114-a367a01a-ec74-4005-a734-deffaf87ce95.PNG)
For my test, I simply inject an instance of `IOptionsMonitor<OpenIdConnectOptions>` into a controller and run a bench (a few hundred requests) 

.NET 5 results (same test):

![NET 5](https://user-images.githubusercontent.com/64366368/150004076-c41893ab-5ca1-4ec8-a1f1-386f252ad6ab.PNG)

It seems also that the issue only concerns `OpenIdConnectOptions` (but maybe not) because I tried with a custom options class and I didn't notice any issue.

### Expected Behavior

Same behavior as .NET 5

### Steps To Reproduce

The repo to reproduce the issue: https://github.com/ylabade/options-memory-leak

### .NET Version

6.0.101

**Comment by ylabade** [comment]
The issue doesn't seem to be related to `IOptionsMonitor` but rather to `OpenIdConnectOptions`

You can just try:
```cs
for (int i = 0; i < 1000; i++)
{
    var options = new OpenIdConnectOptions();
}
```

**Comment by adityamandaleeka** [comment]
@ylabade It looks like there are just fewer GC's on .NET 6? As you can see there were a series of GCs that were freeing up memory in your .NET 5 chart, but in the two .NET 6 ones there were just fewer GCs. You can test this theory by either forcing GC with the "Force GC" button or by adding periodic GC.Collect calls in your code. 

Based just on the info here, we don't have reason to believe there's a memory leak here.

**Comment by ylabade** [comment]
```cs
for (int i = 0; i < 10000; i++)
{
    var options = new OpenIdConnectOptions();
}
````
With .NET 5:
![image](https://user-images.githubusercontent.com/64366368/150217672-c66b0ddd-8c49-4284-8673-2f54437ac0ef.png)

.NET 6. GC is triggered with the "Force GC" button:
![image](https://user-images.githubusercontent.com/64366368/150217089-7d48a425-b220-4ecd-bb0d-4e4e999d838f.png)

Unfortunately ,there is clearly a difference between the two versions

**Comment by sebastienros** [comment]
There is a way to prove there is a leak. Let it run until there is an `OutOfMemoryException`.

**Comment by adityamandaleeka** [comment]
Those images show a difference in behavior for sure, but still not a sign of a leak, and certainly not a leak of `OpenIdConnectOptions` which (a) wouldn't be using unmanaged memory and (b) wouldn't escape Gen 0. 

There may be a change in GC behavior that makes your steady state memory usage look different, but unless you have a specific reason for caring about it, it's fine to ignore :smile:.

**Comment by moisoiu** [comment]
Hello, I've also taken a look and I saw that some objects are not being disposed from the ConcurrentQueueSegment.

After a bit more looking, I think the cause comes from `InMemoryCryptoProviderCache `  [Link](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/InMemoryCryptoProviderCache.cs
)

Which is called by `CryptoProviderFactory.cs` [Link](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs) somehow, which eventually goes to `JwtSecurityTokenHandler.cs`  [Link](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs) 

And a new `JwtSecurityTokenHandler.cs` is initialized by `OpenIdConnectOptions.cs` [Link](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs)

I hope it helps a little bit, somehow I think is related with one of these two

```
        private readonly EventBasedLRUCache<string, SignatureProvider> _signingSignatureProviders;
        private readonly EventBasedLRUCache<string, SignatureProvider> _verifyingSignatureProviders;
```

Since in the snapshot these one of these two is the biggest (or maybe both). 

![image](https://user-images.githubusercontent.com/5052365/150224561-cbdd716c-b8a3-4bae-83b1-54988b85e7a8.png)

**Comment by ylabade** [comment]
> Those images show a difference in behavior for sure, but still not a sign of a leak, and certainly not a leak of `OpenIdConnectOptions` which (a) wouldn't be using unmanaged memory and (b) wouldn't escape Gen 0.
> 
> There may be a change in GC behavior that makes your steady state memory usage look different, but unless you have a specific reason for caring about it, it's fine to ignore 😄.

Agree with you, this is not necessary a sign of a leak. How do you explain that the memory keeps increasing ?
![Capture](https://user-images.githubusercontent.com/64366368/150229621-f389bef9-5be0-4ff9-9d07-35ba917a06b4.PNG)

**Comment by sebastienros** [comment]
investigation:

OpenIdConnectOptions.ctor()
-> OpenIdConnectProtocolValidator.ctor()
-> CryptoProviderFactory.ctor()
-> InMemoryCryptoProviderCache.ctor()
-> EventBasedLRUCache.ctor()

which used to create a new `Timer` before this PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1783. Also before this PR I don't see any Dispose() implementation (or finalizer) so probably the Timer would not even be released on GCs.

So definitely a performance issue when using multiple instances of this class. I'd recommend to use the option as a singleton, as I assume how it's intended. If you can't use a singleton, maybe try to update the library, they seem to have shipped the one with the improvements: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases

**Comment by ylabade** [comment]
@sebastienros thanks for your input.

With the last version of `Microsoft.IdentityModel.Protocols.OpenIdConnect` is clearly better even if the memory consumption is still a bit high (and the unmanaged memory is gradually increasing without decreasing).

Do you know why ASP.NET reference such an old version of `System.IdentityModel.*/Microsoft.IdentityModel.*` packages ?

**Comment by HaoK** [comment]
So the ask is just to bump our versions of IdentityModel in servicing?  That doesn't seem too scary I guess

**Comment by HaoK** [comment]
We should probably do it in 7 and let it bake a bit before bumping things in 6 if this is something we are interested in doing

**Comment by sebastienros** [comment]
There has been 10 releases with bug and security fixes though ... some of them have baked quite a bit already ;)

**Comment by HaoK** [comment]
The issue is that some of the surface area leaks directly out of our auth providers, so if there are subtle changes those turn into breaking changes for AspNetCore apps, which is generally frowned on for servicing

**Comment by sebastienros** [comment]
Yes, no breaking changes. None of these were listed on the release page. I don't know if they follow semantic versioning, or even list the breaking changes explicitly.

**Comment by Tratcher** [comment]
@sebastienros IdentityModel doesn't have a good track record with breaking changes, we'd definitely want to test this in 7.0 first.

**Comment by Tratcher** [comment]
The good news is that updating the dependency in AspNetCore servicing isn't required, customers can update the IdentityModel dependency locally.

**Comment by adityamandaleeka** [comment]
Sounds good. We should update the dependency for 7, and soon so it has enough bake time.

**Comment by adityamandaleeka** [comment]
Thanks for reporting this @ylabade
