### ISSUE TITLE
Blazor Wasm server hosted get path conflict error on build solution

### ISSUE THREAD

**Issue by danfer** [dotnet/aspnetcore#39627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor Wasm server hosted on scaffold identity get favicon added into server´s wwwroot and get path conflict error on build solution

### Expected Behavior

No error

### Steps To Reproduce

Scaffold identiy pages on server project, using identiy

### Exceptions (if any)

Severity	Code	Description	Project	File	Line	Suppression State
Error		Conflicting assets with the same target path 'favicon.ico'. For assets 'Identity: C:\Users\dhabe\source\repos\BusinessIntel\BusinessIntel\Client\wwwroot\favicon.ico, SourceType: Project, SourceId: BusinessIntel.Client, ContentRoot: C:\Users\dhabe\source\repos\BusinessIntel\BusinessIntel\Client\wwwroot\, BasePath: /, RelativePath: favicon.ico, AssetKind: All, AssetMode: All, AssetRole: Primary, RelatedAsset: , AssetTraitName: , AssetTraitValue: , CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: wwwroot\favicon.ico' and 'Identity: C:\Users\dhabe\source\repos\BusinessIntel\BusinessIntel\Server\wwwroot\favicon.ico, SourceType: Discovered, SourceId: BusinessIntel.Server, ContentRoot: C:\Users\dhabe\source\repos\BusinessIntel\BusinessIntel\Server\wwwroot\, BasePath: _content/BusinessIntel.Server, RelativePath: favicon.ico, AssetKind: All, AssetMode: All, AssetRole: Primary, RelatedAsset: , AssetTraitName: , AssetTraitValue: , CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: wwwroot\favicon.ico' from different projects.	BusinessIntel.Server	C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	411	

### .NET Version

6.0.101

**Comment by javiercn** [comment]
@danfer thanks for contacting us.

The error is legitimate and is pointing out that there are two files on the same path, `favicon.ico` on your project and `favicon.ico` on the wasm project.

In this case this seems to be caused by the logic on scaffolding, including a `favicon.ico` when the blazor webassembly app is already providing one. We suggest that you remove the favicon.ico from the wwwroot that got generated by the scaffolder.

**Comment by danfer** [comment]
Thanks Javier.

Saludos,
Danfer.

De: Javier Calvarro Nelson ***@***.***>
Enviado el: Wednesday, January 19, 2022 8:36 AM
Para: dotnet/aspnetcore ***@***.***>
CC: Danfer Habed ***@***.***>; Mention ***@***.***>
Asunto: Re: [dotnet/aspnetcore] Blazor Wasm server hosted get path conflict error on build solution (Issue #39627)


@danfer<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdanfer&data=04%7C01%7C%7C968cffecff8042d37fb308d9db59073e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781997685107118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wMxjWtr3o3C9XFwDMaDjCEXVoDOhXIkDZaDxrKMQwDg%3D&reserved=0> thanks for contacting us.

The error is legitimate and is pointing out that there are two files on the same path, favicon.ico on your project and favicon.ico on the wasm project.

In this case this seems to be caused by the logic on scaffolding, including a favicon.ico when the blazor webassembly app is already providing one. We suggest that you remove the favicon.ico from the wwwroot that got generated by the scaffolder.

-
