### ISSUE TITLE
Visual support in visual studio for organizing razor code

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#39630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's easy to write code in one single components, but when I am starting to separate the components, **it's going to get hard** to manage them all, because it requires people to have a structure laid out and a plan put on the table before starting the implementation, I put my effort creating many components in a library, but it still made me face the problem that when I am making something from scratch inside visual studio everything is going to be changed and debugged it requires changes to code that's frequent and I only have one monitor it gets hard when the component gets large (Visual -) which has all client UI implementation that I can't put to my library and it gets hard to manage when I put them in different components **(Maintainability -)** I just can't afford the attention span on my own but I feel like if the tool is a bit better I can definitely spend more time changing the code rapidly (also I use variables that requires passing into components when I do separate them which creates the problem that if I later don't use this variable or use another one or I just want to test out different things I now have to fix all the errors in different files instead of one)

### Describe the solution you'd like

Emphasize the idea that separating a component is optional and make visual elements to accommodate it

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

It's not clear to us what your ask is, but since this is a tooling ask, you'll get a better and faster response if you file the issue via the suggest a feature functionality in visual studio. You can check the details [here](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022)
