### ISSUE TITLE
Confusion using FileExtensionContentTypeProvider Class

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#39635]
When we need to work with MimeTypes we have the FileExtensionContentTypeProvider Class that helps us out. The issue is, which package should be used? Microsoft.AspNetCore.StaticFiles 2.2.0 (latest version) or the mentioned Package in the [documentation ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.staticfiles.fileextensioncontenttypeprovider?view=aspnetcore-6.0#definition) Microsoft.AspNetCore.App.Ref v6.0.0 although the package specifies that "This package is an internal implementation of the .NET Core SDK and is not meant to be used as a normal PackageReference.".

This is starting to get confusing...

Thank you!

**Comment by adityamandaleeka** [comment]
The `FileExtensionContentTypeProvider` no longer ships in a package. You just need to reference the Web SDK or the framework reference.

This might be helpful: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#use-the-aspnet-core-shared-framework
