### ISSUE TITLE
.Net 6.0.1 Blazor Wasm - Cannot move or rename MainLayout.razor

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#39638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When renaming MainLayout.razor and moving it to a different folder, the style of the app is not the same.

### Expected Behavior

Should be allowed to move and/or rename MainLayout.razor without affecting the style of the app.

### Steps To Reproduce

- VS 2022 Community Version 17.0.5
- Create new Blazor WebAssembly .Net 6 project
- Create folder structure:  /Features/Shared/RazorComponents
- Create new razor component: /Features/Shared/RazorComponents/MainLayoutComponent.razor
- Copy contents of /Shared/MainLayout.razor to /Features/Shared/RazorComponents/MainLayoutComponent.razor
- Add @using [Root Namespace].Features.Shared.RazorComponents to _Imports.razor
- Change App.razor to use MainLayoutComponent instead of MainLayout in both places
- Run the app and notice the style is not the same

### .NET Version

6.0.1

### Anything else?

- VS 2022 Community Version 17.0.5

PS C:\Users\roy.surles> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.21617.4
 Commit:    58f9685dd5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200-preview.21617.4\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.21617.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Users\roy.surles>

**Comment by TanayParikh** [comment]
Hello @roysurles, thanks for contacting us. 

> * Run the app and notice the style is not the same

Can you please confirm you've done a hard refresh (or tried in incognito). Just want to ensure this isn't a local caching issue.

**Comment by roysurles** [comment]
@TanayParikh Yes.  I am using MS Edge.  after starting the app, I have pressed CTRL+F5 several times with no affect.  Also tried a new MS Edge 'InPrivate' window with the same results... the style is messed up.

![image](https://user-images.githubusercontent.com/37274814/150231938-a06de262-4df5-499c-85c0-a028786de9d5.png)

**Comment by TanayParikh** [comment]
Have you added `@namespace [Root Namespace].Features.Shared.RazorComponents` to `/Features/Shared/RazorComponents/MainLayoutComponent.razor`?

**Comment by roysurles** [comment]
@TanayParikh I did not think it was necessary to add the @namespace to new razor components as I thought they inherited the folder structure.  But, i just did add the namespace to the MainLayoutComponent.razor with the same results... no success.

![image](https://user-images.githubusercontent.com/37274814/150235302-735c1b27-0f83-4dc1-a217-981d7a22e729.png)

![image](https://user-images.githubusercontent.com/37274814/150235365-d016e325-a58e-41fd-bcff-aa6f0370a526.png)


![image](https://user-images.githubusercontent.com/37274814/150235432-df6ffb4e-abea-4560-a35e-c2fa368f421b.png)

![image](https://user-images.githubusercontent.com/37274814/150235541-57ed4852-e1b0-4f7b-81f6-8992e0572a1d.png)

**Comment by TanayParikh** [comment]
Oh I see the issue now. The `MainLayout.razor.css` file wasn't moved/copied. Notice how `MainLayout.razor` has a `>` next to it. Hit that and it'll show the scoped .css file. You'll want to move that over to `/Features/Shared/RazorComponents/MainLayoutComponent.razor.css`.

**Comment by roysurles** [comment]
@TanayParikh Ok, so in this scenario, i did: in VS 2022, right click on 'Features/Shared/RazorComponents' folder --> Add --> Razor Component --> named it MainLayoutComponent.Razor... so how do we get / force VS 2022 to create the corresponding css file (MainLayoutComponent.razor.css)  that you are referring to?  Or are you saying i have to do this manually?

**Comment by roysurles** [comment]
@TanayParikh this is issue is not resolved / closed.  I created a new razor component and VS 2022 did not create the necessary resulting supporting files.

**Comment by TanayParikh** [comment]
> @TanayParikh Ok, so in this scenario, i did: in VS 2022, right click on 'Features/Shared/RazorComponents' folder --> Add --> Razor Component --> named it MainLayoutComponent.Razor... so how do we get / force VS 2022 to create the corresponding css file (MainLayoutComponent.razor.css)  that you are referring to?  Or are you saying i have to do this manually?

You'll have to create it manually. The feature is called scoped CSS, and the documentation is available [here](https://docs.microsoft.com/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0).

**Comment by roysurles** [comment]
@javiercn @danroth27 @SteveSandersonMS just wanted to double check on the results of this issue.  So for any new razor component(s) that i create in a .Net 6 (plus) Blazor Wasm project, i need to also manually create a corrsponding*.css file as to match it as well?  I am pretty sure this was not the case with VS 2019 & .Net 5, but i will need to try to repro tomorrow to verify. if this is the case, the i will make note... thanks

**Comment by TanayParikh** [comment]
> need to also manually create a corrsponding*.css file as to match it as well? 

The scoped CSS files (.razor.css) are optional files, they don't _need_ to be created. If provided, they facilitate component isolated styles.

**Comment by javiercn** [comment]
@roysurles this has always been the case. As @TanayParikh mentions scoped CSS files are optional and we don't add them to components/views by default, users need to manually add them and move them if along the Razor files if they change their location.

@danroth27 Maybe there's an editor feature that we need here to move dependent files along with the main files.
