### ISSUE TITLE
Better documentations about blazor dom events

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#39645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Yes it's a problem of documentations.
![image](https://user-images.githubusercontent.com/35312807/150283322-a25b9a07-3622-4bae-9f3b-5d2118565f2b.png)
I would like information about what is onabort what is onchange what is onfocusin etc... instead of having to google it if it's available to see in intellisense it's faster to make the decisions about their usage

### Describe the solution you'd like

I want to see in visual studio's intellisense for a more detailed description about the dom events (```@``` keyword in <div> tag)

**Comment by Xyncgas** [comment]
in the pictured that's linked for example, it doesn't show what onabort is

**Comment by javiercn** [comment]
@Xyncgas what description do you get if you don't use `@`

**Comment by Xyncgas** [comment]
nothing
![image](https://user-images.githubusercontent.com/35312807/150425617-f370b2f3-5376-4e06-ad1e-bc6526007ccc.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
