### ISSUE TITLE
Is it possible to get full path of isolated JS/CSS assets for Blazor

### ISSUE THREAD

**Issue by sergeyzwezdin** [dotnet/aspnetcore#39651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-isolation-in-javascript-modules) about JavaScript isolated modules says to call `import` to to get isolated JS reference:

```csharp
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        module = await JS.InvokeAsync<IJSObjectReference>("import", 
            "./scripts.js");
    }
}
```

The problem is the path of the JS file. Assuming we have `Pages/CallJsExample6.razor` and `Pages/CallJsExample6.razor.js` javascript module.

Then we should call `await JS.InvokeAsync<IJSObjectReference>("import", "./Pages/CallJsExample6.razor.js")`.

Once we move `CallJsExample6.razor` to the external class library, it will have a path like `./_content/ExternalAssemblyName/Components/CallJsExample6.razor.js`.

So, the question is whether it's possible to resolve asset's path after project publishing in runtime? 

### Describe the solution you'd like

Something like `var path = Resolver.GetContentPath('./Pages/CallJsExample6.razor.js');`

**Comment by guardrex** [comment]
Side note that our current guidance on collocated JS with RCLs is at (2nd bullet at the end of the section) ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component

I'll keep an 👁️ on this issue in case we need further updates there.

**Comment by sergeyzwezdin** [comment]
@javiercn okay, can we make it possible then? otherwise, it potentially can cause bugs related to resource loading.
At least, msbuild's publish step is doing it somehow, right?

**Comment by javiercn** [comment]
@sergeyzwezdin It's not clear to me what you are trying to achieve.

If you are building an app, your resources are essentially in the root, and if its a library they are in "_content/Library/...". You shouldn't be loading resources across app/library boundaries, and within your app/library there should be no ambiguity since you know if you are authoring a library or an app.

If you are concerned about moving things from one place to another, then you can author a helper method to help you compute the prefix for the resource.

All the resource paths get decided at build/publish time via MSBuild after the application has been compiled, so you need to know ahead of time where the resource is going to end.

**Comment by sergeyzwezdin** [comment]
@javiercn well, the problem I want to solve is to connect .NET code with isolated JS in a more straightforward manner.

While CSS isolation works out of the box in Blazor, for JS resources you have to have magic strings like `./_content/blahblahbla` to make it work. It is a very unobvious and bugs causing approach, as for me.
 
What we can do instead? We can register `IJSObjectReference` for every Razor component in DI and inject this directly into the component.

I've created the prototype for that — https://github.com/sergeyzwezdin/blazor-javascript-isolation/tree/development

How it works:

1. We add `builder.Services.AddJavascriptReferences()` at `Startup.cs`/`Program.cs`. It registers required services for JS interop.
2. We add `Component.razor.js` file for `Component.razor`. The similar way like we do when CSS file needed.
3. `Component.razor.js` exports javascript functions that could be called from C#.
4. We inject javascript module reference directly in Razor component — `@injectIJSObjectReference<Component> JSModule`.
5. Now we can call JS functions from C# - `await JSModule.Exports.run<string>(DateTime.Now.ToLongTimeString());`

See the example how it works here — https://github.com/sergeyzwezdin/blazor-javascript-isolation/tree/development/samples/SampleSharedLib

SampleSharedComponent.razor:
```razor
@inject IJSObjectReference<SampleSharedComponent> JSModule

<div class="alert alert-primary mt-4 align-top">
    <strong class="d-block">Sample Shared Component</strong>

    @if (_result != null)
    {
        <div class="text-nowrap">@_result</div>
    }

    <button class="mt-2 btn btn-primary btn-sm" @onclick="Invoke">Invoke component's Javascript</button>
</div>

@code {
    private string? _result;

    private async Task Invoke()
    {
        _result = await JSModule.Exports.run<string>(DateTime.Now.ToLongTimeString());
    }
}
```

SampleSharedComponent.razor.js:
```javascript
export function run(param)
{
    return 'SampleSharedComponent: ' + param;
}
```

Everything is perfect in this approach, except we need to know path to `SampleSharedComponent.razor.js` that is being constructed during publishing.

**Comment by javiercn** [comment]
@sergeyzwezdin thanks for the additional details.

Unfortunately you can't make the general claim that JS modules are going to be located in a specific path on the site. "_content/Library" is just a convention. If you intend to do this for yourself, it will work, as a generic helper it won't.

Given these constraints, the simplest way for you to do this, would be to add an assembly attribute to each of your assemblies that captures the base path for the assets and then when your code needs the path it can do `type.Assembly.GetCustomAttribute<MyAttribute>().BasePath`

**Comment by sergeyzwezdin** [comment]
@javiercn thank you for the suggestion, but how custom attribute could help here? I didn't get the idea.

So, in other words, if I be able to get relative path of `.razor` file inside the project, I'll be able to calculate JS path, i.e.:
- `SampleSharedLib/Components/SampleSharedComponent/SampleSharedComponent.razor` - I need this part: `Components/SampleSharedComponent`

**Comment by javiercn** [comment]
If you have a component MyComponent.razor there is going to be a type MyComponent, so in your generic type you do `typeof(T).Assembly.GetCustomAttribute<MyAttribute>().BasePath` at that point, when its instantiated with MyComponent you can retrieve that to get the attribute you stamped on the assembly with the base path

**Comment by sergeyzwezdin** [comment]
Could you please create simple example project to demonstrate the idea? What is `BasePath` of custom attribute?

**Comment by sergeyzwezdin** [comment]
Actually, the problem is not solved, not sure why it's closed 😕
