### ISSUE TITLE
Disconnect event takes 10 minutes to trigger

### ISSUE THREAD

**Issue by bencz** [dotnet/aspnetcore#39666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm developing an ASP.Net core service that uses Signalr, an android app connects to the signalr HUB.

When performing the test of disconnecting the cell phone from the internet network, while it is connected to the HUB, there is a delay of 10 minutes to trigger the disconnect event on the server. 

I'm currently using SignalR's default timeout settings.

The bug/feature is, the time that the SignalR uses to trigger the disconnect event.
According to the documentation this time should be just a few seconds. 

### Expected Behavior

The quick disconnect trigger.

### Steps To Reproduce

Create some Hub with ASP.Net core and SignalR
Create some VM or Android APP that connect to the SignalR hub
Connect the app to the hub
Disconnect the VM or app machine from network

### .NET Version

6.0.101

**Comment by BrennanConroy** [comment]
What version of the SignalR client are you using?

Are you running the server inside a debugger?

**Comment by bencz** [comment]
@BrennanConroy Good question hahah
6.0.1 ?
There is no explict nuget-package about SignalR on the project...
I'm using the last one that comes with ASP.Net core project

About the debugger
I read that when the debugger is attached, the disconnect event doesn't stop at the Break point, so I put a "Console.WriteLine" in the "OnDisconnectedAsync" so I know when it went through the event.
And I performed the test in release mode and the same problem continued... the event only ran after 10 minutes.

**Comment by BrennanConroy** [comment]
> There is no explict nuget-package about SignalR on the project...

There is no explicit package for the server side of SignalR. But there is for the client, so what version of the client are you using?

It might be useful to see the server logs at debug level, could you provide those? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging
