### ISSUE TITLE
[Question] :Is MAUI.NET blazor shipped with a browser like electron?

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#39673]

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

Blazor Hybrid uses the platform browser of the operating system via the Webview control supplied on each platform. That means Edge on Windows, Chrome on Android and Safari on iOS/Mac.

**Comment by Xyncgas** [comment]
Thanks

**Comment by Xyncgas** [comment]
> @Xyncgas thanks for contacting us.
> 
> Blazor Hybrid uses the platform browser of the operating system via the Webview control supplied on each platform. That means Edge on Windows, Chrome on Android and Safari on iOS/Mac.

What if they don't have edge installed on windows, chrom installed on android ?
