### ISSUE TITLE
Authorization fails in Controllers after Login is successful 

### ISSUE THREAD

**Issue by dobrinsky** [dotnet/aspnetcore#39688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a blank NET6 Angular project with Individual User Accounts in which I added the code from my old project which was in NET5. 

Everything worked ok until a point where now I continuously get 401 Unauthorized for all APIs even though the LogIn is successful.

I did not changed anything in the scaffolded pages so I do not understand what the problem is.

### Expected Behavior

The Controllers should see that the user is authorized since in Angular the authentication.service.isAuthenticated returns true. 

### Steps To Reproduce

I can privately share the code of my application.

### Exceptions (if any)

var usersIds = _httpContextAccessor.HttpContext.User.FindAll(ClaimTypes.NameIdentifier).ToList();

Returns zero results even though Angular sees the user as loggedIn

I get the "There was an error signing in" in authorize.service.ts in method: 

public async completeSignIn(url: string): Promise<IAuthenticationResult> {
    try {
      await this.ensureUserManagerInitialized();
      const user = await this.userManager!.signinCallback(url);
      this.userSubject.next(user && user.profile);
      return this.success(user && user.state);
    } catch (error) {
      console.log('There was an error signing in: ', error);
      return this.error('There was an error signing in.');
    }
  }

but I did not changed absolutely anything here and it used to work...

### .NET Version

6.0.101

**Comment by dobrinsky** [comment]
I have been investigating the problem for more than one week. From my last tests, it is clearly a bug in ASP.NET. I do not know what it is, but there clearly is one.

Bear with me...

I migrated the code from an older ASP.NET Core 3.1 app to a new ASP.NET 6 project to integrate with the supported ASP.NET Individual Accounts functionality.

I created the project from the Visual Studio template and them copied my C# Models and Controllers.

The problem is that I get 401, or in some cases 404 for all my APIs, but no matter what I do the weatherForecast API, it works...that is...until I just paste the code from any of my APIs into that one...them I get 401 or 404 error. What I mean is:

 The template is:


        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }

with the Controller having the following attributes:

    [Authorize]
    [ApiController]
    [Route("[controller]")]

My Controllers all only have the [Authorize] attribute, while have for each API the Route integrated in it:

[HttpGet("user/get-loggedInUserInfo")]

Which worked, but for which I get only 401 Unauthorized responses. What I have tried and it worked:

Copying the API from the WeatherForecast Controller into the UserController and changing the Route:

        [HttpGet("weatherforecast/get-weatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
                return Enumerable.Range(1, 7).Select(index => new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = Random.Shared.Next(-20, 55),
                    Summary = Summaries[Random.Shared.Next(Summaries.Length)]
                })
                .ToArray();
        }

and in the fetch-data.component.ts:

    http.get<WeatherForecast[]>(baseUrl + 'weatherforecast/get-weatherForecast').subscribe(result => {
      this.forecasts = result;
    }, error => console.error(error));

this works...then I proceeded to add all the different functionalities of my other APIs as follows:

        [HttpGet("weatherforecast/get-weatherForecast")]
        public async Task<IActionResult> Get2()
        {
            try
            {
                return Ok(Enumerable.Range(1, 7).Select(index => new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = Random.Shared.Next(-20, 55),
                    Summary = Summaries[Random.Shared.Next(Summaries.Length)]
                })
                .ToArray());
            }
            catch (Exception e)
            {
                Error.Add(e);

                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

And it...works

Then I just switched the API Routes between them:

        [HttpGet("weatherforecast/get-loggedInUserInfo")]
        public async Task<IActionResult> Get2()
        {
            try
            {
                return Ok(Enumerable.Range(1, 7).Select(index => new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = Random.Shared.Next(-20, 55),
                    Summary = Summaries[Random.Shared.Next(Summaries.Length)]
                })
                .ToArray());
            }
            catch (Exception e)
            {
                Error.Add(e);

                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

this works...

but then...if I switch the code in the API which means that I simply copy the code from the other method in the Controller:

        [HttpGet("weatherforecast/get-loggedInUserInfo")]
        public async Task<IActionResult> Get2()
        {
            try
            {
                {
                    ApplicationUser user = await _context.Users.SingleOrDefaultAsync(c => c.UserName == User.Identity.Name);

                    if (user != null)
                    {
                        var rolesForUser = await _userManager.GetRolesAsync(user);
                        string userRole = "";

                        if (rolesForUser.Count > 0)
                            userRole = rolesForUser.ElementAt(0);
                        else
                            userRole = "";

                        var response = new
                        {
                            email = user.Email,
                            username = user.UserName,
                            role = userRole,
                            language = user.Language,
                            
                            hasExpiringConnection = user.HasExpiringConnection,

                            hasEnvironmentalTaxAccess = user.HasEnvironmentalTaxAccess,
                            hasReusablePackagingManagementAccess = user.HasReusablePackagingManagementAccess,
                            hasEstimatesAccess = user.HasEstimatesAccess,

                            hasEnvironmentalProtectionAccess = user.HasEnvironmentalProtectionAccess,

                            hasWasteManagementAccess = user.HasWasteManagementAccess,
                            hasInternalWasteManagementAccess = user.HasInternalWasteManagementAccess,
                            hasScalesAccess = user.HasScalesAccess,
                            hasProductionWastesAccess = user.HasProductionWastesAccess,
                            hasLogisticsWastesAccess = user.HasLogisticsWastesAccess,
                            hasSortedWastesAccess = user.HasSortedWastesAccess,
                            hasProcessedWastesAccess = user.HasProcessedWastesAccess,
                            hasGeneratedWastesAccess = user.HasGeneratedWastesAccess,
                            hasTakenWastesAccess = user.HasTakenWastesAccess,
                            hasManagedWastesAccess = user.HasManagedWastesAccess,
                            hasWasteEconomicOperatorsAccess = user.HasWasteEconomicOperatorsAccess,
                            hasWasteDocumentsAccess = user.HasWasteDocumentsAccess,
                            hasWasteConstantsAccess = user.HasWasteConstantsAccess
                        };

                        var json = JsonConvert.SerializeObject(response, _serializerSettings);
                        return new OkObjectResult(json);
                    }
                    else
                    {
                        return NotFound();
                    }
                }

                return Ok(Enumerable.Range(1, 7).Select(index => new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = Random.Shared.Next(-20, 55),
                    Summary = Summaries[Random.Shared.Next(Summaries.Length)]
                })
                .ToArray());
            }
            catch (Exception e)
            {
                Error.Add(e);

                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

In this case, I get 404 NotFound, the only change I made was to simply copy the code...Firstly, I do not even understand why I get NotFound when the Route worked, then I do not understand what the code has that makes the Routing not work.

My Program.cs is:

using AutoMapper;
using HelpersLibrary.Database;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI;
using Microsoft.EntityFrameworkCore;
using SIGAD.Data;
using SIGAD.Mapping;
using SIGAD.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

DatabaseConnection.ConnectionString = connectionString;

builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>();

builder.Services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

builder.Services.AddAuthentication()
    .AddIdentityServerJwt();

// Auto Mapper Configurations
var mappingConfig = new MapperConfiguration(mc =>
{
    mc.AddProfile(new MappingProfile());
});

IMapper mapper = mappingConfig.CreateMapper();
builder.Services.AddSingleton(mapper);

builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();

app.UseAuthentication();
app.UseIdentityServer();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");
app.MapRazorPages();

app.MapFallbackToFile("index.html"); ;

app.Run();

**Comment by HaoK** [comment]
There seem to be a lot of moving pieces here, can you try slimming things down to isolate where the behavior change lies?  Perhaps you can simplify your authentication/authorization to simply look for any claims instead of actually checking roles/hitting the identity db.  Without an actual repro with steps the best we can do is provide guidance on how to narrow down where the source might be.

Between 3.1 and 6, we've updated many things, identity server could be another area you need to look at as we went to duende in 6.0.  Just copying things from a 3.1 app into a 6.0 angular app unfortunately isn't just going to work, there's a lot of different assumptions between those two kinds apps where its unlikely that things will just work.
