### ISSUE TITLE
Analyzer: Warn that IResult should not be returned from Controller Actions

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#39692]
Today, with the new Microsoft.AspNetCore.Http.Results class is very easy to get confused and implement a Controller Action similar with that, or any other variation of the methods exposed by this class:

``` csharp
[HttpGet]
public IResult Get()
{
    return Results.Ok();
}
```

Also, is very easy to use an `Microsoft.AspNetCore.Http.IResult` custom implementation as a return of a controller action, like this:

``` csharp
public class MyCustomResult : IResult
{
    public Task ExecuteAsync(HttpContext httpContext) => Task.CompletedTask;
}
```

``` csharp
[HttpGet]
public IResult Get()
{
    return new MyCustomResult();
}
```

Both examples will not throw exception but will serialize the class. For the first example the action will return the following payload:

``` json
{
  "value": null,
  "statusCode": 200,
  "contentType": null
}
```

In rare situations it will be the expected behavior. With that, we should add an analyzer that detects if the action return an `Microsoft.AspNetCore.Http.IResult` and fail/warn. It might be also possible provide a code fix suggestion in cases where the `ControllerBase` has a similar method, eg:

From:

``` csharp
[HttpGet]
public IResult Get()
{
    return Results.Ok();
}
```

To:
``` csharp
[HttpGet]
public IResult Get()
{
    return Ok();
}
```

**Comment by davidfowl** [comment]
Or maybe we should support them?

**Comment by brunolins16** [comment]
@davidfowl In my opinion, it is very confusing already and will become even more when we start look into https://github.com/dotnet/aspnetcore/issues/37502. However, this is just my initial thoughts related to #33403 and maybe we support them might be a better option.

**Comment by davidfowl** [comment]
Yea I see how that can be very problematic from a developer POV. Also unfortunately the controller base class has all of those methods that make it hard to move away from action result and prefer Results.XX. Maybe throwing is a fine way to start.
