### ISSUE TITLE
Analyzer: Change expression-bodied property to action method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#39698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/975719/in-code-analyzer-add-a-suggestion-to-change-expres.html)._

I faced an unusual problem when re-creating an example from ASP.NET Core MVC book. I accidentally forgot to put parentheses in expression body controller methods

```csharp
public class CustomerController : Controller
{
    public ViewResult Index => View("Results", new Result { ... });
    public ViewResult List => View("Results", new Result { ... });
}
```
 
This silently turned methods `Index()` and `List()` to properties `Index` and `List`, which I didn't intend to do. This in turn caused all calls to the controller to return 404 error. And although it's completely valid to have properties in controllers, this is much less common than to have action methods. And this kind of error is easy to overlook. I wasted more than an hour trying to debug this error, validating Startup class, routes, my hosts file, etc. Then I showed this error to my friends. I pointed out that the error is _in this piece of code_, and they couldn't find what's wrong.

My suggestion is to add to code analyzers a warning saying something like "_Did you mean to create an action method?_" at least for controller properties of type `IActionResult`.

Thank you in advance.

#### Visual Studio Feedback System on 4/3/2020, 01:21 AM:
Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. We'll provide an update once the issue has been triaged by the product team.

_Originally posted by @vsfeedback in https://github.com/dotnet/roslyn/issues/43112_

**Comment by captainsafia** [comment]
We discussed this during triage and decided that we won't be pursuing it at the time because the risk of false positives is high and it's relatively low-priority compared to the other items in our analyzers bucket for .NET 7.
