### ISSUE TITLE
Add RouteValuesAddress .ToString ()

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/aspnetcore#39708]
## Background and Motivation

The following message is unsatisfactory:

> Microsoft.AspNetCore.Routing.DefaultLinkGenerator: Debug: No endpoints found for address Microsoft.AspNetCore.Routing.RouteValuesAddress

## Proposed API

```diff
namespace Microsoft.AspNetCore.Routing
{
    public class RouteValuesAddress
    {
+       public override string ToString();
    }
}
```

## Usage Examples

``` C#
        if (endpoints.Count == 0)
        {
            Log.EndpointsNotFound(_logger, address);
        }
        else
        {
            Log.EndpointsFound(_logger, address, endpoints);
        }

```

## Alternative Designs

Given the address is generic, It seems easier to define `RouteValuesAddress .ToString ()` than to modify `Log.EndpointsNotFound(_logger, address)` to display something useful.

## Risks

Defining this API is a breaking change.  I do not think it will break anything because the current implementation is useless.

diff --git a/.github/ISSUE_TEMPLATE/25_api_proposal.md b/.github/ISSUE_TEMPLATE/25_api_proposal.md

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Feel free to send us a PR with the proposed fix and we'll review it.

**Comment by pranavkm** [comment]
Approved. See https://github.com/dotnet/aspnetcore/issues/39792#issuecomment-1031796143
