### ISSUE TITLE
UseHttpLogging not working .NET 6 RC 1 #37577   and the answer    You need to have information level logging for HttpLogging to show up, right now you're set at warning level

### ISSUE THREAD

**Issue by 3cdota** [dotnet/aspnetcore#39701]
You need to have information level logging for HttpLogging to show up, right now you're set at warning level
https://github.com/no-stack-dub-sack/dotnet-issue-repro/blob/ac42ab81e5e634024641404d56b3f45e385187f7/Repro/appsettings.Development.json#L5

_Originally posted by @BrennanConroy in https://github.com/dotnet/aspnetcore/issues/37577#issuecomment-944450808_

I run the  code in the repro ,and change the  Microsoft level to Information ;but it still doen't work!

**Comment by adityamandaleeka** [comment]
Can you share more about how you're running the code?
