### ISSUE TITLE
I want to set the permissions of an administrator and agent. I won't use it

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#39706]
I read the official website and only set restrictions, but I don't know how to make him pass this restriction. How to distinguish between permission 1 and permission 2? I don't see how to authorize permissions on the official website

https://docs.microsoft.com/zh-cn/aspnet/core/security/authorization/roles?view=aspnetcore-6.0

**Comment by Tratcher** [comment]
@HaoK, @blowdart?

**Comment by blowdart** [comment]
@bbhxwl I don't understand the scenario here. 

What are you using for your user database? ASP.NET identity? Azure AD? Something else? 

How are the permissions represented in the identity your login provider gives you, is it roles, is it claims?

**Comment by bbhxwl** [comment]
> @bbhxwl I don't understand the scenario here.
> 
> What are you using for your user database? ASP.NET identity? Azure AD? Something else?
> 
> How are the permissions represented in the identity your login provider gives you, is it roles, is it claims?

https://stackoverflow.com/questions/70820187/authorize-attribute-how-should-i-use-it?noredirect=1#comment125239072_70820187

**Comment by bbhxwl** [comment]
> @bbhxwl I don't understand the scenario here.
> 
> What are you using for your user database? ASP.NET identity? Azure AD? Something else?
> 
> How are the permissions represented in the identity your login provider gives you, is it roles, is it claims?

[Authorize("admin")]    I don't want to know how to authorize this? Let him pass. I only know that this can be limited. I want dynamic authorization.

**Comment by blowdart** [comment]
Admin is what? A username? A role? A group membership? 

And, as asked previously what is your authentication method? You can't authorize without authenticating first.

**Comment by bbhxwl** [comment]
> Admin is what? A username? A role? A group membership?
> 
> And, as asked previously what is your authentication method? You can't authorize without authenticating first.

[Authorize("admin")] 
Isn't this authentication? I don't know how to verify this sentence. After I add this, the controller can't access and has no permission. I don't know how I can make the current user have this permission.

**Comment by blowdart** [comment]
No

[Authorize("admin")] is authorization.

Authentication is when a user tells you who they are, for example by logging in.
Authorization is when you decide what the user can do, by examining who/what they authenticated as

So you're adding authorization to a page without knowing what makes a user an admin, and that is part of authentication. Without knowing what you're using to log a user in I can't give any advice on how you authorize a user or give them any properties that make them an admin.

**Comment by bbhxwl** [comment]
> No
> 
> [Authorize("admin")] is authorization.
> 
> Authentication is when a user tells you who they are, for example by logging in. Authorization is when you decide what the user can do, by examining who/what they authenticated as
> 
> So you're adding authorization to a page without knowing what makes a user an admin, and that is part of authentication. Without knowing what you're using to log a user in I can't give any advice on how you authorize a user or give them any properties that make them an admin.

Maybe the translation software I use doesn't understand very well. I mainly want to see how the code passes the admin permission.

**Comment by blowdart** [comment]
The permissions depend on your authentication provider. The identity that is built when you login can have an admin role, or an admin claim. You then write a policy which looks for that.

What's your natural language? I can try to find a native speaker in the team, and we can go to email and into detail?

**Comment by bbhxwl** [comment]
> The permissions depend on your authentication provider. The identity that is built when you login can have an admin role, or an admin claim. You then write a policy which looks for that.
> 
> What's your natural language? I can try to find a native speaker in the team, and we can go to email and into detail?

What's your email address? I am used to Chinese, but I can also use translation software to read English. If it is code, I should be able to understand it. I just don't know how to define strategy.

**Comment by blowdart** [comment]
Chinese I can probably find :)

barry.dorrans@microsoft.com - please use your native language and I'll try to find someone who can translate.
