### ISSUE TITLE
Information in the JwtBearer comments is not up-to-date

### ISSUE THREAD

**Issue by tndata** [dotnet/aspnetcore#39725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In this class:

https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/JwtBearer/src/JwtBearerOptions.cs

The default values that the comments refer to has changed to 12 hours and 5 minutes respectively.

```
    /// <summary>
    /// 1 day is the default time interval that afterwards, <see cref="ConfigurationManager" /> will obtain new configuration.
    /// </summary>
    public TimeSpan AutomaticRefreshInterval { get; set; } = ConfigurationManager<OpenIdConnectConfiguration>.DefaultAutomaticRefreshInterval;

    /// <summary>
    /// The minimum time between <see cref="ConfigurationManager" /> retrievals, in the event that a retrieval failed, or that a refresh was explicitly requested. 30 seconds is the default.
    /// </summary>
    public TimeSpan RefreshInterval { get; set; } = ConfigurationManager<OpenIdConnectConfiguration>.DefaultRefreshInterval;
```

Perhaps worth updating?

### .NET Version

Latest (6.0.1)

### Anything else?

nope

**Comment by tndata** [comment]
Also, is 5 minutes RefreshInterval  not quite a long time? especially at startup if the Identity provider is not responding when the API startsup? Then the API will be down for 5 minutes?

**Comment by adityamandaleeka** [comment]
@Tratcher Can you please take a look? Perhaps we can link to the type rather than hardcoding the default value in these comments?

**Comment by Tratcher** [comment]
When did the defaults change? I think we're still referencing an older version.

**Comment by rbipin** [comment]
hello, can I give this a try? this is my first-time contribution. I felt like this is a less risky one.

**Comment by Tratcher** [comment]
@rbipin yes, please.
