### ISSUE TITLE
Can't get SignalR to work behind AWS ALB

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/aspnetcore#39736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't get SignalR to work using Amazon's Application Load Balancer (ALB) - or ELB for that matter. It falls back to server side events, which I don't want to use. Works fine when there is no LB.
The app is ASP.NET using SignalR 2.4.3 on the angular client and back end. There are two instance of the AspNet project that SignalR is hosted in, running on different EC2 instances behind the load balancer.  We are not using, no wish to use, sticky sessions. The connection is over HTTPS. We use a SQL server SignalR backplane.
What am I missing? 

### Expected Behavior

For WSS to connect

### Steps To Reproduce

Try to connect using WSS. In Chrome console tab:

jquery.signalR.js:1893 WebSocket connection to 'wss://dev.ger911.com/webapi/signalr/connect?transport=webSockets&clientProtocol=2.1&connectionToken=JOEfhF6U0ihzdbgF6DQGn%2BSnifhkljaQU%2Bt%2BZ3LU%2F1OI6oqEmT2KLnU0rAwAJ7aIwYnhjjKrFszOZrJ%2FolmdECgsPdWm4D%2FDoxmrYy32Xsb4TMdy&connectionData=%5B%7B%22name%22%3A%22datachangehub%22%7D%5D&tid=5' failed: 

### .NET Version

4.6

**Comment by johnkwaters** [comment]
Update - we tried with and without sticky sessions, no luck. Then we switched the AWS target group form HTTP/2 to HTTP/1 and  now WSS connects just fine. Is there an issue with HTTP/2 and the WSS connection upgrade flow? (works now without sticky as well!)

**Comment by davidfowl** [comment]
None of the HTTP/2 implementations support websockets at the moment. It's a pretty new feature in most browsers.

**Comment by johnkwaters** [comment]
Thanks for confirming that @davidfowl - seems like a good tidbit to get out there somehow. It spent me days of digging to stumble across this (because I wasn't  the one that had set the protocol in AWS to be HTTP/2).
