### ISSUE TITLE
Ability to use DiagnosticSource in Kestrel without the rest of ASP.NET Core

### ISSUE THREAD

**Issue by Jevvry** [dotnet/aspnetcore#39744]
## Background and Motivation

Net6 introduced diagnostics in Kestrel. Specifically `DiagnosticSource` with the `Microsoft.AspNetCore.Server.Kestrel.BadRequest` event name. And this works fine if you use the whole ASP.NET Core, but if you use only the Kestrel server like:
```
            var serverOptions = CreateServerOptions(config);
            var loggerFactory = CreateLoggerFactory(loggerProvider);
            var transportFactory = CreateTransportFactory(loggerFactory);

            var server = new KestrelServer(serverOptions, transportFactory, loggerFactory);
```

[There is](https://github.com/dotnet/aspnetcore/blob/v5.0.13/src/Servers/Kestrel/Core/src/KestrelServer.cs#L19) no way to pass a DiagnosticSource.
It seems to be possible to allow adding a custom DiagnosticListener or at least be able to enable it in my case.

## Proposed API

Possible option to add:
```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Core
{
    public class KestrelServer : IServer
    {
        private readonly KestrelServerImpl _innerKestrelServer;

        public KestrelServer(
+           IOptions<KestrelServerOptions> options, IConnectionListenerFactory transportFactory, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
        {
            _innerKestrelServer = new KestrelServerImpl(
                options,
                new[] { transportFactory ?? throw new ArgumentNullException(nameof(transportFactory)) },
+              null,
                loggerFactory,
+              diagnosticSource);
        }
}
```

## Usage Examples
``` C#
var listener = new DiagnosticListener("MyListener");

var server = new KestrelServer(serverOptions, transportFactory, loggerFactory, listener);
```
Or perhaps another API option
```C#
var enableEvents = true;

var server = new KestrelServer(serverOptions, transportFactory, loggerFactory, enableEvents);
```

**Comment by Jevvry** [comment]
Kestrel server is used in proxy service with custom instrumentations. We create the server object manually to avoid the overhead of using all of ASP.NET. And all usage comes down to creating a KestrelServer object, setting up the instrumentation, and calling StartAsync().

**Comment by adityamandaleeka** [comment]
Can you share your code in a repo (or at least a sample with enough to show how you're using it)?
