### ISSUE TITLE
Test failure - "DefaultReconnectionHandler.test - invokes update on each attempt"

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#39758]
## Failing Test(s)

- DefaultReconnectionHandler.test - invokes update on each attempt

## Error Message

```text
FAIL tests/DefaultReconnectionHandler.test.ts (23.354 s)
    ΓùÅ DefaultReconnectionHandler ΓÇ║ invokes update on each attempt
  
      expect(jest.fn()).toHaveBeenCalledTimes(expected)
  
      Expected number of calls: 6
      Received number of calls: 5
  
        90 |
        91 |     await delay(500);
      > 92 |     expect(testDisplay.update).toHaveBeenCalledTimes(maxRetries);
           |                                ^
        93 |
        94 |   })
        95 | });
  
        at Object.<anonymous> (tests/DefaultReconnectionHandler.test.ts:92:32)

```

## Build

[](https://dev.azure.com/dnceng/public/_build/results?buildId=1567128&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4a2ac175-72f0-54eb-c8b6-eb1e5d86c7d5&s=6884a131-87da-5381-61f3-d7acc3b91d76)

**Comment by JamesNK** [comment]
I don't know how to quartine this type of test.

https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Components/Web.JS/tests/DefaultReconnectionHandler.test.ts#L79-L94

@mkArtakMSFT can you please pass this on to someone. This is at least the second time this test has failed in the last couple of days. @BrennanConroy noticed a failure yesterday and included detail in this issue: https://github.com/dotnet/aspnetcore/issues/39727

**Comment by TanayParikh** [comment]
This one's odd, we haven't really changed anything in this area for a while (aside from @ShreyasJejurkar's recent [PR](https://github.com/dotnet/aspnetcore/pull/39700) which shouldn't have any impact on behavior). Wondering if this has something to do with one of our dependencies.

**Comment by pranavkm** [comment]
@TanayParikh one option would be to remove these tests entirely. I don't think we've done any work to maintain them and pretty much rely on browser automation for testing anyway.

**Comment by TanayParikh** [comment]
Would be nice to get rid of another dependency (jest) in that case. Any objections @dotnet/aspnet-blazor-eng?

**Comment by pranavkm** [comment]
I'd go for it. I was the one that added the tests, and it got 0 traction from the remainder of the team. We're really not losing any meaningful coverage removing it.
