### ISSUE TITLE
Inferring `FromBody.AllowEmptyBehavior = Allow` based nullability information

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#39754]
## Current design

Today, MVC infer optionality for parameters/properties based on nullability or if they have default value for all Binding Sources, eg.:

``` csharp
#nullable enable
    public IActionResult Post([FromBody] string? name);
    public IActionResult Get([FromQuery] string? name);
    public IActionResult Post([FromForm] string? name);
#nullable restore
```
Or 
``` csharp
#nullable disable
    public IActionResult Post([FromBody] string name = null) ;
    public IActionResult Get([FromQuery] string name = null);
    public IActionResult Post([FromForm] string name = null);
#nullable restore
```
All examples above will allow the `null` value for the parameter `name`, however, when the binding `From Body` (inferred or not) the current default behavior is `fail` when the `Content-Length == 0`.

``` json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-1a27854a7f1211e53fbc64e054801c11-a79404ee342e26ff-00",
    "errors": {
        "": [
            "A non-empty request body is required."
        ]
    }
}
```
Currently, are available 2 options to override this behavior and any of those available options are based on the `Nullability` information and need to be explicitly specified by the user.

Globally:
``` csharp
builder.Services.Configure<MvcOptions>(options =>
{
    options.AllowEmptyInputInBodyModelBinding = true;
});
```
Scoped:
```csharp
public IActionResult Post([FromBody(EmptyBodyBehavior = EmptyBodyBehavior.Allow)] string? name);
```

## Proposed Change

As part of the idea to bring `Minimal APIs` enhancements to `MVC` the proposal is applying the same default behavior and allow empty input body (`Content-Length = 0`) when the parameter/property is nullable or has the default value.  

The suggestion is to always allow empty input (`Content-Length = 0`) when a `[FromBody]` parameter/property sets a default value or is nullable without allowing or requiring configuration.

After this change the following scenarios will allow an empty input:

``` csharp
#nullable disable
    public IActionResult Action([FromBody] string value);
    public IActionResult Action([FromBody] string value = null);
#nullable restore
```

``` csharp
#nullable enable
    public IActionResult Action([FromBody] string? value);
    public IActionResult Action([FromBody] string? value = null);
#nullable restore
```

## Usage Examples

If the users are affected by this change and they would like a different behavior, the simplest way to avoid it is to define the action parameter/property correctly based on the optionality, as the examples listed below.

#### Before
``` csharp
#nullable disable
    public IActionResult Action([FromBody] string value);
    public IActionResult Action([FromBody] string value = null);
#nullable restore
```
#### After
``` csharp
#nullable disable
    public IActionResult Action([FromBody][Required] string value);
#nullable restore

```

#### Before
``` csharp
#nullable enable
    public IActionResult Action([FromBody] string? value);
    public IActionResult Action([FromBody] string? value = null);
#nullable restore
```
#### After
``` csharp
#nullable enable
    public IActionResult Action([FromBody] string value);
#nullable restore
```

**Comment by pranavkm** [comment]
This looks great. 

> The suggestion is to always allow empty input (Content-Length = 0)

Super unrelated to this change, but could we update the check to use the feature instead of relying on `Content-Length: 0`: https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Http/Http.Features/src/IHttpRequestBodyDetectionFeature.cs#L9

**Comment by brunolins16** [comment]
> This looks great.
> 
> > The suggestion is to always allow empty input (Content-Length = 0)
> 
> Super unrelated to this change, but could we update the check to use the feature instead of relying on `Content-Length: 0`:
> 
> https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Http/Http.Features/src/IHttpRequestBodyDetectionFeature.cs#L9

Actually, I was looking at exactly that because of this issue https://github.com/dotnet/aspnetcore/issues/29570. Thanks for mention that.

**Comment by brunolins16** [comment]
I have been talking with @halter73 offline and one aspect of this change that we agreed is that having a mechanism to infer the EmptyBody based on optionality even when the `AllowEmptyInputInBodyModelBinding  = false` seems weird and might be worth instead just change the default to `true` and let the actual validation mechanism check the parameter validity without any inferred behavior for the EmptyBody.

cc: @pranavkm.

**Comment by brunolins16** [comment]
After, design conversations the final the infer mechanism will allow empty body only when:

``` csharp
modelMetadata.NullabilityState == NullabilityState.Nullable || 
modelMetadata.IsNullableValueType || 
modelMetadata.HasDefaultValue
```

That means the following scenario will still not allowing empty body as default, unless the default is changed by the current options available:

``` csharp
#nullable disable
    public IActionResult Ref([FromBody] TestClass val) => Ok(val);
#nullable restore
```
