### ISSUE TITLE
.Net 6, Minimal API - Endpoint does not appear in swagger-output if Microsoft.AspNetCore.Http parameter exists in "MapXXX"

### ISSUE THREAD

**Issue by michisnewsletter** [dotnet/aspnetcore#39766]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I want to use minimal API with swagger, but if i use the "HttpContext" in the parameter-list, the endpoint is not showing in the swagger-result (json and output).

The error only happens if the "HttpContext" parameter stands alone.

Is this a bug or a misunderstanding ?

You can see the example above, the endpoint "WithContext" is not showing in swagger-output/json, all ohter are showing.

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();
app.UseSwagger();
app.MapGet("/", () => "Hello World!"); // => is showing

// is showing
app.MapGet("/WithHttpResonse", async (HttpResponse response) =>
    await response.WriteAsJsonAsync("Test")).WithName("GetWithHttpResonse");

// is showing
app.MapGet("/WithHttpResonseV2", async (HttpResponse response,HttpContext httpContext) =>
    await httpContext.Response.WriteAsJsonAsync("Test")).WithName("GetWithHttpResonseV2");

// DOES NOT APPEAR
app.MapGet("/WithContext", async (HttpContext context) =>
    await context.Response.WriteAsJsonAsync("Test")).WithName("GetWithContext");

app.MapSwagger();
app.UseSwaggerUI();
app.Run();
```

### Expected Behavior

The endpoint "WithContext" is showing in the swagger-output.

### Steps To Reproduce

See code-example in description

### .NET Version
```
Visual Studio Community 2022 (17.0.5)

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Arclight3** [comment]
A valid situation to define an endpoint that is affected by this issue is for health checking (which I have in all APIs).

```C#
app.MapGet("api/health", async context =>
        await context.Response.WriteAsync("My API is healthy!"))
   .WithName("HealthCheck")
   .WithDisplayName("HealthCheck");
```

Since this practice is common I think many applications are affected.

**Comment by adamfoneil** [comment]
On the very first minimal API handler I ever created I thought needed an `HttpContext` argument. (Maybe I really didn't, and that was the misunderstanding.) I'd spent several hours trying to figure out why the handler didn't appear. I guess it makes sense (now that I think about it) that the HttpContext is not something you can submit via swagger form -- so I kinda get why it doesn't appear. But it was pretty frustrating to have "silent fail" behavior. It would be nice if there was a warning somewhere that certain handler arguments can't be represented in Swagger

**Comment by willmcgowan85** [comment]
I ran into this issue because I was testing the reading of headers using [Authorize] attribute which don't show up as part of the request since I'm using a middleware to handle that part. 

So it's not uncommon for the only parameter to be the HttpContext. 

Also, isn't .NET 6 going to be around longer than .NET 7 since 6 is LTS and 7 is not?

**Comment by captainsafia** [comment]
Notes from a little bit of investigation on this.

I was able to repro this on .NET 7 Preview 7 and narrowed it down to the fact that the endpoint with `HttpContext` is not populated via the `ApiDescriptionProvider`. However, it looks like this issue isn't repoing in the latest developing bits (7.0.100-rc.2.22419.21).

![image](https://user-images.githubusercontent.com/1857993/185713275-5e477877-c781-41b5-be19-33f74a7c5d39.png)

We'll probably want to do some bisecting to figure out what commit might have inadvertently fixed this in the event we want to backport.
