### ISSUE TITLE
[API Proposal]: Add DisplayAttribute.Size

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/aspnetcore#39779]
### Background and motivation

Whenever I expect Razor to create an input element for a property, I have to set its [size](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-size) attribute by hand and to the same value.  

### API Proposal

```C#
namespace System.Collections.Generic
{
    public class DisplayAttribute
    {
        public byte Size { get; set; } = 0;
    }
}
```

### API Usage

```C#
public class Model { [ Display (Size = 0X6) ] public string Property { get; set; } }
```

```cshtml
<input asp-for="Model.Property" />
```

### Alternative Designs

```C#
public class Model
 { const byte PROPERTY_DISPLAY_SIZE = 0X6; public string Property { get; set; } }
```

```cshtml
<input asp-for="Model.Property" size="@Model.PROPERTY_DISPLAY_SIZE" />
```

### Risks

None AFAICT

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
