### ISSUE TITLE
Strange behaviour of [CallerFilePath]

### ISSUE THREAD

**Issue by hypeartist** [dotnet/aspnetcore#39772]
OS: Windows 11 (22000.434)
.NET: 6.0.200-preview.22055.15

I've stumbled upon a strange issue when using `CallerFilePath` attribute. 
Here is the method of some class `Settings` that uses the attribute:
```cs
	public void SetJSModulePath([CallerFilePath] string componentPath = default!)
	{
		var componentPathSpan = componentPath.AsSpan();
		if (componentPathSpan.EndsWith(".js"))
		{
			JSModulePath = componentPath;
			return;
		}
		if(!componentPathSpan.EndsWith("razor.cs")) return;
		componentPathSpan = componentPathSpan[componentPathSpan.IndexOf(GetType().Assembly.GetName().Name)..];
		var span  = MemoryMarshal.CreateSpan(ref MemoryMarshal.GetReference(componentPathSpan), componentPathSpan.Length);
		span[^2] = 'j';
		span[^1] = 's';
		JSModulePath = new string(span);
	}
```
and here is the method of some class `UISplitView` from which `SetJSModulePath` is being called:
```cs
	protected override void OnSetup(Settings settings)
	{
		settings.SetJSModulePath();
	}
```
`OnSetup` is the member of a class located at **D:\Repos\Ivt\Ivt.Web.Blazor.Components\Library\UISplitView\UISplitView.razor.cs** and thus this path is expected to be the value for `componentPath` in `SetJSModulePath` upon a call. 
And this exactly what happens on the first call from `UISplitView.OnSetup` into `Settings.SetJSModulePath`.
But on the second call (since I have two `UISplitView` components)  the value of `componentPath` in `SetJSModulePath` is set to **D:\Repos\Ivt\Ivt.Web.Blazor.Components\Library\UISplitView\UISplitView.razor.js**!!! (note the file extension)

How could that be?! Do I miss something or...?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like your code does modify the string and replaces the last to characters to be `js` from the original `cs`.
Closing as there doesn't seem to be any issue in the framework here.

**Comment by SteveSandersonMS** [comment]
To emphasise, the `[CallerFilePath]` string instance is (presumably) the same instance on successive calls, because the assumption is that strings are immutable. If you've found a way of mutating that string, then you've defeated the compiler :)

**Comment by hypeartist** [comment]
Oh! You are absolutly right! I appologize for such stupid time-wasting issue! Shame on me and thank so much for your answers!
