### ISSUE TITLE
Blazor WASM Auth force token renew

### ISSUE THREAD

**Issue by johan-v-r** [dotnet/aspnetcore#39775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to renew the user's access token without needing to refresh the page.

### Describe the solution you'd like

I'd like to call a function on something like `IAccessTokenProvider.RenewUserToken` or `RemoteAuthenticationService.RenewUserToken()`

## Setup
I'm using the standard `AddOidcAuthentication` extension with my `.AddHttpClient(...).AddHttpMessageHandler(sp => sp.GetRequiredService<AuthorizationMessageHandler>().ConfigureHandler(...))` on multiple `HttpClient` registrations.

## Reason
Our JWT contains some dynamic data for multi-tenant use. So after certain user actions (i.e. switching tenants), they require a new JWT.

## Attempts

Simply requesting a new JWT ourselves is insufficient as the other middleware needs to be notified of this.

Tried extending the `RemoteAuthenticationService` class to trigger `NotifyAuthenticationStateChanged` and various other functions, but seems like everything first checks for the (still valid) session token - so no renewal.

Couldn't see exactly what happens when the token expires, but it basically does what I want. Can that functionality be exposed somehow?

**Comment by javiercn** [comment]
@johan-v-r thanks for contacting us.

Are you asking for a way to renew an ID token or for a way to renew an access token. Can you clarify?

**Comment by johan-v-r** [comment]
Hi @javiercn - just the access token would be fine. Although renewing both together would probably make sense as it's part of the Token endpoint..?

But yes the access token is the critical one.

**Comment by johan-v-r** [comment]
Yes basically update it after the user has already been authenticated. Similar to what happens currently when the token expires.  
I don't need to handle the token in my own code.

**Comment by javiercn** [comment]
@johan-v-r thanks for the clarifications.

If you don't need to request a different set of scopes (which we currently don't support) then you can redirect the user to "authentication/login" and that should trigger a new authorization flow (if I remember correctly).

I believe @TanayParikh added some logic to invalidate tokens in the auth handler, but I might be wrong. If that's not the case, then you can author your own handler using ours as a template (code [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs))
