### ISSUE TITLE
SignalR : Want to send signal to client when it reconnects to server

### ISSUE THREAD

**Issue by nagtilaklaxman** [dotnet/aspnetcore#39770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.
**SignalR**
I want to send signal to client when it reconnects. I am not able to find any overload to detect that client is reconnected

### Describe the solution you'd like

can you provide method as  OnReconnection in hub to override?

**Comment by BrennanConroy** [comment]
ASP.NET Core does not have stateful reconnects. What this means is that when you reconnect you are a completely new connection with a new connection ID and the server will not store information about your previous connection ID for you. So, an OnReconnection method does not make sense for us to add to the Hub.
