### ISSUE TITLE
BlazorWebAssemblyLazyLoad By Dependency Injection

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/aspnetcore#39774]
Hello
I want to use **BlazorWebAssemblyLazyLoad** with **Dependency Injection** In Blazor WASM Project, but the problem is that when the secondary **dll** itself is not loaded, how can its dependencies be injected? As a result, the project gets an error. What is the solution? 
PLZ Help

**Comment by javiercn** [comment]
@masoodafar-web thanks for contacting us.

Our DI container doesn't support registering dependencies after the container has been built. You need to register your dependencies ahead of time or use a third-party container that can support registering dependencies after the container has been built.
