### ISSUE TITLE
Upgrading Authentication.JwtBearer 6.0.1 throws null exception at runtime

### ISSUE THREAD

**Issue by aarondrabeck** [dotnet/aspnetcore#39787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A valid claims principle is returned from my custom ISecurityTokenValidator, then sometime after that, an internal null exception is thrown.  

Error:
![image](https://user-images.githubusercontent.com/9825025/151225197-ed1a383b-3e07-4c8a-9990-46a0fe54ed0d.png)

Config:
![image](https://user-images.githubusercontent.com/9825025/151225410-1627e7d6-b198-4f87-9a0c-4985bbfd2392.png)

### Expected Behavior

All WebAPI calls to not throw a 500.

### Steps To Reproduce

Upgrade Microsoft.AspNetCore.Authentication.JwtBearer from 5.0.13 to 6.01

### .NET Version

6

### Anything else?

Downgrading to "Microsoft.AspNetCore.Authentication.JwtBearer 5.0.13" fixes issue

**Comment by TanayParikh** [comment]
Hello @aarondrabeck, thanks for contacting us. I believe this may be a duplicate of https://github.com/dotnet/aspnetcore/issues/39181, could you please confirm?

**Comment by aarondrabeck** [comment]
do not think its the same issue.  Only packages I have installed are these.  

![image](https://user-images.githubusercontent.com/9825025/151242302-1fb5f01d-0269-439d-91b7-3d6c5d3709e0.png)

**Comment by adityamandaleeka** [comment]
Can you please confirm whether you've also upgraded to .NET 6? JwtBearer 6 should only be used with .NET 6.

**Comment by adityamandaleeka** [comment]
@aarondrabeck Can you please try to repro this issue under a debugger with first-chance exceptions enabled? 

This might be helpful: https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022#tell-the-debugger-to-break-when-an-exception-is-thrown

**Comment by BrennanConroy** [comment]
I'm guessing you're setting a null token in your `ISecurityTokenValidator.ValidateToken(...)`?

We should probably add a null check to our code, IdentityModel is likely not nullable annotated, so we just assumed it wasn't null.
