### ISSUE TITLE
Load a script from an external JavaScript file (.js) collocated with a component

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39784]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Load-a-script-from-an-external-JavaScrip/1638313)._

---
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.1.0 Preview 2.0

I am trying to follow the instructions at:
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component

A collocated js file in an RCL works fine. However, if I try to do the same in a Blazor server app I get an error that it can't find the file. Perhaps I just don't understand how to do this correctly?

! [JSDemoError.png] (https://aka.ms/dc/image?name=B8b10c349d34b4df9b9d877e918e077aa637779431597648847_JSDemoError.png&tid=8b10c349d34b4df9b9d877e918e077aa637779431597648847)

I've attached the solution:
[BlazorSvrJsDemo.zip] (https://aka.ms/dc/file?name=B70e1935b7e4e4d7893d492535d1b74b0637779432532194171_BlazorSvrJsDemo.zip&tid=70e1935b7e4e4d7893d492535d1b74b0637779432532194171)

---
#### Feedback Bot on 1/17/2022, 00:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

The issue is in the `~` on your url. `~` is an ASP.NET Core concept, not a Blazor one. Blazor will automatically use the `base href` from the document to import scripts when you call import so `Pages/JsDemo.Razor.js` is the proper string to use.
