### ISSUE TITLE
Improve endpoint metadata debugging by overriding ToString

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#39792]
# Background and Motivation

It is useful to understand what behavior endpoint metadata is adding to an endpoint. A human-readable summary of metadata would make this much easier. It can be viewed when debugging, and in logs when metadata is logged.

https://github.com/dotnet/aspnetcore/issues/34604 is another potential use of human-readable endpoint metadata.

# Proposed API

I propose overriding ToString on metadata types. See changes in https://github.com/dotnet/aspnetcore/pull/35231 and https://github.com/dotnet/aspnetcore/pull/39753 as examples.

```
override Microsoft.AspNetCore.Routing.DataTokensMetadata.ToString() -> string!
override Microsoft.AspNetCore.Routing.EndpointNameMetadata.ToString() -> string!
override Microsoft.AspNetCore.Routing.HostAttribute.ToString() -> string!
override Microsoft.AspNetCore.Routing.HttpMethodMetadata.ToString() -> string!
override Microsoft.AspNetCore.Routing.RouteNameMetadata.ToString() -> string!
override Microsoft.AspNetCore.Routing.SuppressLinkGenerationMetadata.ToString() -> string!
override Microsoft.AspNetCore.Routing.SuppressMatchingMetadata.ToString() -> string!
```

# Alternative Designs

An alternative approach is to add an interface to get display information:

```csharp
public interface IEndpointDebugText
{
    string DebugText { get; }
}
```

I don't think this adds anything. We already have ToString that is pretty much for this situation.

`DebuggerDisplayAttribute` is not appropriate because there are situations where it is useful to get the debug value at runtime. e.g. logging. It is only useful if we provide debug text using something other than ToString.

# Risks

Someone uses endpoint metadata ToString to drive application behavior, and we change the ToString value. I don't think this is a valid concern. Someone could depend on text in exception messages and logging, and those change from time to time.

**Comment by davidfowl** [comment]
Where does this show up to the user or when debugging?

**Comment by JamesNK** [comment]
```csharp
endpoints.MapGet("/", c =>
{
    var endpoint = c.GetEndpoint();

    var metadata = endpoint.Metadata; // view all metadata
    var nameMedata = metadata.GetMetadata<EndpointNameMetadata>(); // view one metadata
}
```

**Comment by pranavkm** [comment]
API review: API approved. We're happy to consider using ToString instead of alternate ways such as interface implementation. We do not guarantee that the returned string would be consistent across releases. We should try and make the strings appear similar without  dictating a serialization format. Legibility is the primary motive here.

**Comment by SeanFarrow** [comment]
Has anybody taken this, if not I'd be happy to do this as a first contribution.

**Comment by halter73** [comment]
Thanks @SeanFarrow! I think this could be a good candidate for a first contribution. Before you go ahead with a PR, can you show what the new ToString() output will look like for both the `Endpoint` base type and `RouteEndpoint`?

It's probably a good idea to look at [EndpointDataSource.GetDebuggerDisplayStringForEndpoints](https://github.com/dotnet/aspnetcore/blob/88ba76b8574ef7b5162119bc24d7db0b98c0259f/src/Http/Routing/src/EndpointDataSource.cs#L89) as a starting point. That's for a list of endpoints and not a single one, but I imagine we'll want similar output. It might make sense for `GetDebuggerDisplayStringForEndpoints` to call into `Endpoint.ToString()` as part of this change.

**Comment by SeanFarrow** [comment]
@halter73 
Let me have a look at this, I'll come back to you in a day or two.

Thanks,
Sean.

**Comment by SeanFarrow** [comment]
@halter73  Having looked at this, I think the easiest thing to do would be to move any code related to stringifying the RouteEndpoint class members to its own encapsulated ToString method (as you rightly suggest) and then have the EndpointDataSources GetDebuggerDisplayString method call in to a new ToString method which would encapsulate the endpoint iteration logic that was not pulled out.

I would then add a ToString method to the Endpoint base class so that this could participate in endpoint collection iteration as it currently does now.

**Comment by halter73** [comment]
Sounds good to me. Try to get all the metadata types listed in the original issue if you can. We might be a little slow with reviews because of the holidays. Thanks!

**Comment by SeanFarrow** [comment]
@halter73 No worries, we all like to have tome off!

**Comment by SeanFarrow** [comment]
@halter73  Do we want a set of tests for the ToString methods we need to override? There doesn't appear to be many tests for any GetDebuggerDisplayString methods currently.

**Comment by halter73** [comment]
No tests that I'm aware of. I don't think it's really necessary since we reserve the right to change the results. We obviously don't want it to throw exceptions or anything though.

**Comment by SeanFarrow** [comment]
@halter73 
I'm just completing this and need to understand how Microsoft uses PublicAPI.Shipped.txt and PublicAPI.Unshipped.txt.

Which file should the new API's (specifically ToString) be added too, at least initially?

**Comment by JamesNK** [comment]
Add new ToString APIs to PublicAPI.Unshipped.txt please.

**Comment by SeanFarrow** [comment]
@JamesNK  Thanks, I will.

has someone already done some of this, I'm seeing merge conflicts with master.

Can you assign me please?

Thanks,
Sean.

**Comment by SeanFarrow** [comment]
I'm just in the process of finishing this, however I think I've found a bug, or at least a deficiency in the analyser that adds new methods to the public unshipped api.

When I try to add the ToString method of hte EndpontMetadataCollection class, it seems to add it to the public API of wrong assembly. Is this type forwarded from a specific assembly?

Thanks for any help.

**Comment by JamesNK** [comment]
I'm not sure. I haven't seen that happen before, but type forwarding it pretty rare.

The PR doesn't need to be perfect when you create it. After you've made the PR we can loop in experts to help fix strange warnings like that.

**Comment by SeanFarrow** [comment]
Thanks James.

Should I leave this as a build error?

Sean.

**Comment by JamesNK** [comment]
Go ahead with creating a PR. It's easier for us to figure out the build error when we can see the source code and build logs.

**Comment by JamesNK** [comment]
Merged! Thanks for the help here @SeanFarrow
