### ISSUE TITLE
JS Isolation not working on .net 5 blazor server app / 404

### ISSUE THREAD

**Issue by sipi41** [dotnet/aspnetcore#39799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to the MS documentation: (https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-isolation-in-javascript-modules) I should be able to do javascript isolation on my blazor app... for some reason is not working and is returning a 404 instead of the actual js file.

My application is using .net 5 / Blazor Server and is very simple, basically its a page that when loads, after renders it will  try to load a companion .js file, in this case as you can see below, the page is called Test2.razor and the js is called Test2.razor.js

![image](https://user-images.githubusercontent.com/688562/151269014-c4d217b8-d5c2-4262-8de0-72d1b4349d5e.png)

The problem is that is always reporting that it can't load the js file (js isolation) because the resource not found.

I even marked my JS file as "copy always" in the properties but nothing seems to work... I have checked my syntax, compared to other examples, and can't get it done. Please help.

PD. This is happening on my work computer with .net 5 and my computer with .net 6, the project was made on .net 5 (just to try reproducing the bug)

### .NET Version

5

**Comment by javiercn** [comment]
@sipi41 thanks for contacting us.

JS isolation is a .NET 6.0 feature.

**Comment by javiercn** [comment]
> My application is using .net 5 / Blazor Server and is very simple, basically its a page that when loads, after renders it will try to load a companion .js file, in this case as you can see below, the page is called Test2.razor and the js is called Test2.razor.js

In .NET 5.0 you would need to put that file inside the wwwroot folder of your app.

**Comment by sipi41** [comment]
@javiercn thank you, that's correct, its just very dark to read in the docs, at least now we know why this problem is there, something to read over the net.
