### ISSUE TITLE
Evaluate Migrating Deleted NPM/Jest Web.JS Tests to Selenium E2E Test Suite

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#39793]
We recently removed the npm/jest Web.JS tests via https://github.com/dotnet/aspnetcore/pull/39763. 

This issue is to track whether we want to replicate any of these tests within our Selenium E2E suite to ensure we don't lose any test coverage.

**Comment by mkArtakMSFT** [comment]
@TanayParikh it doesn't look like there is high value out of this work? If you believe so, let's discuss. For now I'm closing this.

**Comment by TanayParikh** [comment]
I'm fine closing it out as well, don't feel strongly about this. Mainly put up this issue to get feedback in case others felt differently.
