### ISSUE TITLE
Host a Blazor WASM component in an Angular app?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#39800]
https://stackoverflow.com/questions/57274230/is-it-possible-to-embed-a-blazor-component-in-a-non-net-website?rq=1

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio

Is it possible to host a Blazor component in an Angular app? If so, where might I find documentation or better yet an example app?

**Comment by pranavkm** [comment]
@sam-wheat have you had a look at 

* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#render-razor-components-from-javascript
* https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#blazor-custom-elements / https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements#blazor-custom-elements
