### ISSUE TITLE
Blazor and WebComponents

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#39806]
In our organization there are some custom WebComponents, based on [Lit](https://lit.dev/) that we can re-use when we need to do web development in order to preserve the same look and feel of our apps.

These WebComponents are custom HTML elements, written in JavaScript, which includes styling, forms, localization and more.

Is there a way to make use of them in Blazor?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

You can use web components (custom elements if that's what you are referring to) in the same way you would use any other html tag. You might want for a better experience, to wrap them in blazor components. You can check https://github.com/microsoft/fast-blazor for an example library that does this.

**Comment by mihaimyh** [comment]
@javiercn Thanks, this is what I want to achieve, I will have a look
