### ISSUE TITLE
How to detect the current application is web assembly or server application in source.

### ISSUE THREAD

**Issue by kmkrish001** [dotnet/aspnetcore#39805]
How to detect the current application is web assembly or server application in source ?

**Comment by Vake93** [comment]
I think the following should work:

```C#
using System.Runtime.InteropServices;

if (RuntimeInformation.OSArchitecture == Architecture.Wasm)
{
    Console.WriteLine("We're on Web Assembly!");
}
```

**Comment by kmkrish001** [comment]
https://www.techiediaries.com/check-blazor-app-running-webassembly-ijsinprocessruntime/

The above solution works fine.
