### ISSUE TITLE
Window Authentication in Linux .net core

### ISSUE THREAD

**Issue by uyau** [dotnet/aspnetcore#39816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

0

I'm trying to make work window authentication in Linux/Debian server with Kerberos. I'm using .net core 3.1 and IdentityServer4. For now I had joined Linux to the Windows AD like docs say: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#kestrel-1

I have managet to work kerberos from bash with -kinit command. I also made work Apache2 with kerberos.

But in .net core it's always returns in logs [17:39:53 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler AuthenticationScheme: Negotiate was challenged.

[17:39:54 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler None

if I set in krb5.conf wrong encript type I have error like:

Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Unspecified GSS failure. Minor code may provide more information(Request ticket server **** kvno 4 enctype aes256-cts found in keytab but cannot decrypt ticket). at System.Net.Security.NegotiateStreamPal.GssAcceptSecurityContext(SafeGssContextHandle& context, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags) at System.Net.Security.NegotiateStreamPal.AcceptSecurityContext(SafeFreeCredentials credentialsHandle, SafeDeleteContext& securityContext, ContextFlagsPal requestedContextFlags, Byte[] incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, ContextFlagsPal& contextFlags)

So the token is passing GSSAPI in normal mode and trying to validate user, but there is alwayse None in anwser. 

### Expected Behavior

win auth

### .NET Version

3.1

**Comment by Tratcher** [comment]
It looks like you're hitting this log, which was removed in a later version:
https://github.com/dotnet/aspnetcore/blob/7b22a279ec975335bbb0a7cbadef2e45ee15aa9c/src/Security/Authentication/Negotiate/src/NegotiateHandler.cs#L132

There should be more logs?

**Comment by uyau** [comment]
Idk if there should be more logs. I'm using Nuget package Microsoft.AspNetCore.Authentication.Negotiate 3.1.22 version. And if I set my krb5.conf to default settings,I mean  without broken  settings like **default_tgs_enctypes = des3-hmac-sha1**, I allways get logs about "Negotiate was Challanged" and "None", it seems like there is no valid token I'm passing to gssapi? But when I use only Apache2 for kerberos - there is no problem with spn or keytab or token I'm passing.

**Comment by uyau** [comment]
okey, as I mentued, I'm getting "None" from that statuses I guess. 
`if (errorCode == SecurityStatusPalErrorCode.OK
                    || errorCode == SecurityStatusPalErrorCode.ContinueNeeded
                    || errorCode == SecurityStatusPalErrorCode.CompleteNeeded)
                {
                    status = BlobErrorType.None;
                }`
So, my request can't pass some steps in  `private byte[] GetOutgoingBlob(byte[] incomingBlob, out BlobErrorType status, out Exception error)` method.
I will try to find what cause that, but I will be thankful for eny suggestions.

**Comment by Tratcher** [comment]
None is a good thing, it means it finished successfully. So what makes you think there's a problem? Do you not see the user on HttpContext?

Please share your code from Startup.

**Comment by uyau** [comment]
```
public class Startup
    {
        public IWebHostEnvironment Environment { get; }
        public Startup(IWebHostEnvironment environment)
        {
            Environment = environment;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate(NegotiateDefaults.AuthenticationScheme, "Windows Authentication", options => 
                {
                    
                });

            var builder = services.AddIdentityServer()
                .AddInMemoryIdentityResources(Config.IdentityResources)
                .AddInMemoryApiScopes(Config.ApiScopes)
                .AddInMemoryClients(Config.Clients)
                .AddTestUsers(TestUsers.Users)
                .AddDeveloperSigningCredential();
            services.AddAuthorization();
            services.AddControllersWithViews();
        }

        public void Configure(IApplicationBuilder app)
        {
            
            app.UseDeveloperExceptionPage();
            
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor | 
                Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto
            });
            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthentication();
            app.UseIdentityServer();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
        }
```

This is my Startup.cs, also I have 2 Controllers where I use `return Challenge("Negotiate");` in first, and `await HttpContext.ChallengeAsync("Negotiate");` in second. In logs I see token coming from client in Header "Authorize Negotiate YII...." so I'm sure it's passed to backend. And after "None" in logs, I get new 401 request with WWW-Authenticate Negotiate. There is no user Claims, and I tryed to detect Principials with `await HttpContext.AuthenticateAsync("Negotiate");`. It's always nothing in it. Wierd thing that Apache2 works well, if I don't use dotnet, and set config in apache to use Win Auth. All comands run well from bash. So I'm trying to fight this issue almost 1 month.

**Comment by Tratcher** [comment]
Are you going through a proxy? Most proxies break with Negotiate since it's a connection bound protocol. However, I'd expect errors in that case. Does it work without the proxy? Also try it without IdentityServer.

**Comment by uyau** [comment]
I'm using Apache as reverse proxy, and I get from client **WWW-Authenticate: Negotiate** header. But, yes, I tried to run app without apache by using comand ** dotnet App.dll --urls ...** and also tryed use win auth without IdentityServer package, by deploing app with negotiate package with .net core 5.0. I thought maybe it is problem with joining to AD, that I did some wrong, but kerberos wors fine. <br>
`[14:58:00 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler
AuthenticationScheme: Negotiate was challenged.

[14:58:13 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler
AuthenticationScheme: Negotiate was challenged.

[14:58:13 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler
None

[14:58:13 Information] Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler
AuthenticationScheme: Negotiate was challenged.
` <br>
I get this responses from negotiate. As I understand I should get WWW-Authenticate: Negotiate header which contains valid session token. But all I get is new 401 request.

**Comment by uyau** [comment]
I made another app in 3.1, for testing. I managet it work with kerberos only with attr `[Authorize]` and in startup.cs
 `services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();`
 so there is a problem with `await HttpContext.ChallengeAsync("NegotiateDefaults.AuthenticationScheme");` and `return Challenge(NegotiateDefaults.AuthenticationScheme)` using in Linux/Debian server. Maybe I'm missing some additional configurations to manage Challenge work? It would be not so comfortable to do extra controller for win auth with [Authorize] attr. I would love to use Challenge.

**Comment by uyau** [comment]
Btw, Attribute **[Authorize(AuthenticationSchemes = NegotiateDefaults.AuthenticationScheme)]** work's behind apache revers proxy server, so I think it won't be problem to implement `ChallengeAsync()` or `Challenge` with apache as reverse proxy.

**Comment by Tratcher** [comment]
Can you show your controller that's calling Challenge? Negotiate auth returns to the same endpoint once the login is complete, so you might be calling Challenge in a loop when the user is already logged in.

**Comment by uyau** [comment]
I made it work with Challenge, thanks. One more question, in Negotiate package no EnableLdap and LdapSettings. This two classes I'm trying to run in my app is enough, to load authenticated user windows group?
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Negotiate/src/LdapSettings.cs
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs

**Comment by Tratcher** [comment]
You're using .NET 3.1, the LDAP functionality wasn't available until .NET 5.0. You should update rather than trying to re-implement it.

**Comment by uyau** [comment]
Got you. Thanks for helping, closing issue at this point.
