### ISSUE TITLE
.net Blazor markup "if" code compiles and executes dispite being bad written

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#39824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Razor markup compiles even having a bad written if statment. This is a minor issue but... If i'm getting this right...

### Expected Behavior

The expected behavior is some kind of compiler error message

### Steps To Reproduce

Just past the fofflowing code and create the variables for it to execute. The problem is in the if statment. It's a one liner but then i open curled brackets and it executes the foreach.

`   string activa="";
                                @if (utilizadors.Count > 0 && utilizadors.Count < 2) activa = "Active";
                                {
                                    @foreach (var item in utilizadors)
                                    {
                                        <a style="cursor:pointer;" @onclick="()=>SelecionarUtilizador(item.Id)" class="list-group-item list-group-item-action @activa">@item.Nome+" - "+@item.Email</a>
                                    }
                                }
                            `

### .NET Version

6.0.101

### Anything else?

![imagem](https://user-images.githubusercontent.com/16858416/151451626-06d9e896-e41b-4c9d-8839-7662c3456b02.png)

**Comment by pranavkm** [comment]
It's perfectly legal in C# to use braces to [create a new block scope](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/statements). Related StackOverflow question: https://stackoverflow.com/questions/6136853/why-does-c-sharp-allow-code-blocks-without-a-preceding-statement/6136865
