### ISSUE TITLE
Review NPM distribution files

### ISSUE THREAD

**Issue by shelland** [dotnet/aspnetcore#39829]
After installing of SignalR files from NPM (https://www.npmjs.com/package/@microsoft/signalr) or any other package manager (e.g. LibMan from Visual Studio) there are 2 files in `dist/browser` directory:

- signalr.js [41.1 KB]
- signalr.min.js [41.2 KB]

Both files are minified while `signalr.js` is expected to be readable. `signalr.min.js` is minified as expected, but it is even larger than unminifed file.

Not sure what type of issue it should be.

**Comment by BrennanConroy** [comment]
Fixed in 7.0-preview2 and will be fixed when 6.0.3 ships.
