### ISSUE TITLE
JSON string content is null in Put action when request is done using fetch

### ISSUE THREAD

**Issue by prvavill** [dotnet/aspnetcore#39826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am posting JSON string (with JSON.stringify(requestBody)) from Java script using fetch and want to receive it as string in .Net Web API controller (we are still on 4x) as below

Post ex:

fetch("apiurl",
{
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
method: "PUT",
body: JSON.stringify({a: 1, b: 2})
})

Controlloer:

public string JsonStringBody([FromBody] string content)
{

}
but I see content as null on .Net controller side
if I post the request with same content (JSON.Stringify) and content type from postman, it works even with string

the difference looks like here is when it is posted using fetch, the content is coming as JSON Payload (though used JSON.Stringify) instead of JSON escaped string and  JsonMediaTypeFormatter is getting failed to read the content.  is this expected behavior?

if I use JObject on the .Net controller side instead of string, it works as expected (JsonMediaTypeFormatter  parse it properly).

### .NET Version

4X

**Comment by pranavkm** [comment]
`JSON.stringify({a: 1, b: 2})` produces a JSON string representation of your object, but does not produce a JSON string which is what you're attempting to bind. If you look at the ModelState errors, it should include a message to that effect.

**Comment by prvavill** [comment]
Thank you Pranav for your reply. Not sure I followed 'produces a JSON string representation of your object, but does not produce a JSON string'. what is mean by representation here, is this not JSON string?  from here https://onlinetexttools.com/json-stringify-text I see that 'The JSON.stringify() method converts a JavaScript object or value to a JSON string'
![image](https://user-images.githubusercontent.com/45833121/151601440-3798d954-d6bf-432d-a0ba-c9607ed31cb9.png)

Please correct me if my understanding is wrong?

**Comment by davidfowl** [comment]
We don't support getting the body as a string. If you want the raw JSON, you can use JsonElement and then do a ToString or manually read the entire body as a raw string.

**Comment by davidfowl** [comment]
This was resolved offline.
