### ISSUE TITLE
Sections doesn't populate from partials.

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/aspnetcore#39830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When partial contains
```cshtml
// partial view
// some html markup
@section [SectionName]
{
  [SectionBody]
}
```
([SectionBody] and [SectionName] are placeholders)
And then use this partial as 
```cshtml
// Index.cshtml
// some html markup
<partial name="[PartialName]" />
@section [SectionName]
{
  [SectionBody]
}
```
and render it in `_Layout`
then in `_Layout` will be partial & index `HTML` markup *BUT* there will be ONLY `SectionName` from `Index.cshtml` and no from `partial`.

### Expected Behavior

Sections from partials must be rendered in `_Layout` same as sections from pages.
In attached repo on page must be extra `Partial loaded` `h1` text.

### Steps To Reproduce

https://github.com/ParadiseFallen/AspNetCore.RazorPages.SectionIssue

### .NET Version

6.0.101

### Anything else?

.net 6.0
aspnetcore 6
VS 2022

output of `dotnet --info `:
 Version:   6.0.101
 Commit:    ef49f6213a

 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@ParadiseFallen thanks for contacting us.

This behavior is by design. Sections only apply to the main view rendered by a given layout, they can't be rendered from partials.

**Comment by ParadiseFallen** [comment]
@javiercn thanks for quick answer. 

Then i wanna change it from bug to feature request

**Comment by javiercn** [comment]
@ParadiseFallen I don't remember the exact details, but I believe this was not easy to implement with our current view engine design and we don't think this is a direction we plan to take in the near future as we haven't receive enough feedback in this area to warrant the investment.
