### ISSUE TITLE
blazor errors without ambiguity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/blazor-errors-without-ambiguity/1647918)._

---
when working with blazor I often get build errors which are very difficult to find because double clicking on them in the ErrorList window does nothing.

A lot of them are pointing to a razor.g.cs file which I don't know the location of and the double click won't open it.

And right now I'm getting a "} expected" error but without any clue where this "}" is expected

( 
it was a ";" that needed to be removed after a Func<RenderFragment> property setting 
Prop = () => @<text>hi</text>;
)

---
#### Feedback Bot on 1/26/2022, 11:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
