### ISSUE TITLE
ASP .NET Core Razor Page Data Annotations Localizations fail

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39849]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASP-NET-Core-Razor-Page-Data-Annotation/1644558)._

---
[severity:I'm unable to use this version] [regression] [worked-in:3.1]
Data Annotations do not localize in .NET 6. For example:
public class MyViewModel
{
...
[Display(Name = "name")]
...
}

Razor Page:
...
<label asp-for="myView.Name></label>

renders as "name" not the string value in the resource file.

---
#### Feedback Bot on 1/23/2022, 07:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by frnds1** [comment]
Replacing: 

    opts.DataAnnotationLocalizerProvider = (type, factory) =>
        factory.Create(typeof(SharedResource));

with:

    opts.DataAnnotationLocalizerProvider = (type, factory) =>
    {
        var assemblyName = new AssemblyName(typeof(SharedResource).GetTypeInfo().Assembly.FullName!);
        return factory.Create(nameof(SharedResource), assemblyName.Name!);
    };

Solves the problem in .NET 6.

**Comment by mkArtakMSFT** [comment]
Glad that you've been able to solve this. Closing as there is no further action pending here.
