### ISSUE TITLE
Areas for Blazor

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/aspnetcore#39854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to get 2 separate "areas" in Blazor.. the frontend and the admin area.. with different CSS, etc.

Firstly, yes I did see issue #33862, but it's not exactly relevant here. My issue is not really about routing, as about wanting different layouts/themes for different sections of my site. Example: An admin area would be the most obvious section of the site different to the frontend.

### Describe the solution you'd like

I came across this solution (the answer given by Viacheslav):
[Blazor routing and layout when inside an area](https://stackoverflow.com/questions/59428730/blazor-routing-and-layout-when-inside-an-area/62979970#62979970)

It seems promising. However, I get this error when navigating to the admin area:

![Blazor Error](https://user-images.githubusercontent.com/2860937/151639910-e71b9004-0e70-4edd-910c-2a61ebca6cb7.PNG)

I am not sure what the issue is or how to resolve it.

I made a sample project: [BlazorAreas](https://github.com/gordon-matt/BlazorAreas)

1. How to get this working?

2. Is there a better solution? If not, is there a better solution in the works?

### Additional context

Perhaps some kind of official support for areas (different to MVC).. where each area has its own `App.razor` and/or `_Host.razor`.

There should also be some way to override the `_Layout.cshtml` being used. I did try using a condition like this:

```
if (Request.Path.StartsWithSegments("/admin"))
{
    Layout = "/Areas/Admin/Pages/_Layout.cshtml";
}
else
{
    Layout = "_Layout";
}
```

Note that this was my original attempt at using a different "area" for admin.. and yes, it did try to use the correct layout, but it then complained about not being able to find other .cshtml views, because Blazor kept looking in the normal locations and not under the `/Admin` folder for them, the way MVC would. Anyway, the other solution (I described above) looks better for Blazor areas... but this kind of thing here (overriding a layout.cshtml) should also be possible for cases like theming.. for example: multi tenant situations.. or user preference (dark vs. light themes), etc.

**Comment by javiercn** [comment]
Thanks for contacting us @gordon-matt.

It looks like this is a question about how to use ASP.NET Core Blazor. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by gordon-matt** [comment]
@javiercn Thanks, but that's not exactly the case. Yes, it's true that I'm asking how to get a workaround working properly, but I am also asking for a proper solution to be implemented in a future version of Blazor.. my workaround (which is not working properly) serves as an example of WHY we need a proper solution for Blazor areas.. Please read the issue again with this in mind.

**Comment by javiercn** [comment]
@gordon-matt It's not clear from your example what issues you are running into.

> Perhaps some kind of official support for areas (different to MVC).. where each area has its own App.razor and/or _Host.razor

This is something that you can do today.

> There should also be some way to override the _Layout.cshtml being used. I did try using a condition like this:

This should also be possible.

**Comment by gordon-matt** [comment]
As stated in the original post, I already tried the thing where each area has its own `App.razor` and/or `_Host.razor`. It's not working and I showed a screenshot of the error I was getting. Maybe I am doing something wrong. That's why I provided a sample solution so you can run it and see for yourself. Alternatively, since you say it should already be supported (and not a workaround), do you have some documentation and/or demo to point me to?

And for the Layout thing, I'm not sure if you read what I said.. Yes it kind of works, but the problem is it does NOT then look for other .cshtml files (example: partial views) in the correct location. It keeps trying to get them from the default (null) area instead of the admin area... even though the Layout file I pointed it at was itself in the admin area. Anyway, this is just a smaller issue.. it's the one above that I really want to get solved (each area with own `App.razor` and/or `_Host.razor`).

I hope this clarifies it now.

**Comment by gordon-matt** [comment]
@javiercn Commenting so the bot doesn't close this issue. It's been a while.. I'm busy with other things, but this is still an issue and something I'll be coming back to as soon as I can. Would be nice to have an example.. perhaps a link to some documentation or demo project on how to do what you say is currently possible.
