### ISSUE TITLE
With .NET 7 SDK, the docs link should be updated when creating mvc/razor project in CLI

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/aspnetcore#39862]
### Environment
.NET 7 SDK 7.0.100-preview.1.22078.7(runtime-7.0.0-preview.1.22076.8 )

### Steps To Reproduce
1. Install .NET 7 SDK 7.0.100-preview.1.22078.7
2. Create a new mvc/razor in CLI

### Expected Behavior
It should be the link for .NET 7.0

### Actual Behavior
The link is still for .NET 6.0
![image](https://user-images.githubusercontent.com/87680983/151654956-7801fc82-56c3-460c-a2f0-4b8d0a6248db.png)

### Dotnet info
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.1.22078.7
 Commit:    019ef6e10b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.1.22078.7\

Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c

.NET SDKs installed:
  7.0.100-preview.1.22078.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.1.22077.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.1.22077.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
This has been addressed by @wtgodbe 's PR:  https://github.com/dotnet/aspnetcore/pull/39783
