### ISSUE TITLE
[Blazor wasm, auth] 404 Static files downloading from /authentication

### ISSUE THREAD

**Issue by andersson09** [dotnet/aspnetcore#39876]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

- I'm using Blazor wasm Azure ad b2c. For some reason, during the login-callback and logout-callback, Blazor is trying to download static files from /authentication as well as from the correct location:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/70258509/151703811-db5b75ed-e4ba-4b78-8e36-d06e6c1663a0.png">

### Expected Behavior

- Blazor should be dowloading from correct static location only

### Steps To Reproduce

- Open blazor wasm app with azure ad b2c enabled
- log in or log out
- Check console / networking

### Exceptions (if any)

GET https://localhost:5011/authentication/css/app.min.css net::ERR_ABORTED 404
GET https://localhost:5011/authentication/app.styles.css net::ERR_ABORTED 404

### .NET Version

6.0.101

**Comment by javiercn** [comment]
@andersson09 thanks for contacting us.

Are you missing a `<base href="/">`  tag in your index.html?

**Comment by andersson09** [comment]
> @andersson09 thanks for contacting us.
> 
> Are you missing a `<base href="/">` tag in your index.html?

I'm setting it dynamically. I need to have a different base path on non local environments.

**Comment by javiercn** [comment]
@andersson09 from what we can tell, this is an issue on your app produced by the base path not being correctly initialized. So the answer is to fix this within your app

**Comment by andersson09** [comment]
Why is everything working fine apart from the login and logout callback?  How do you correctly set a custom base path? Are you saying baseref must be set to "/" at all times and we can't change it?

**Comment by javiercn** [comment]
@andersson09 because in your callback you are likely setting the base path incorrectly.

If you were to to a top level navigation to "/authentication/login" or "/authentication/logout" and set the base path to that, it would likely fail too.

Base path needs to be set to the root of your app at all times:
* If you serve the page from the root of the domain, it needs to point to that.
* If you serve the page from a virtual directory, then the base path needs to point to that VD at all times.

**Comment by andersson09** [comment]
My issue is that this works fine:

`<base href="/" />`

but this doesn't during the callbacks, i.e. the authentication library is not respecting the base path:

```
<base />
<script>
         const base = document.getElementsByTagName('base')[0];
         base.setAttribute('href', '/');
</script>

```

**Comment by javiercn** [comment]
@andersson09 you probably need to check at what time the script is being loaded/executed.

There's really nothing special about how this works on a Blazor app compared to a regular HTML document, so whatever mechanism you come up with, if it works with a regular HTML document it should work with Blazor.

From what I can tell, there's something in the way that you are setting the base path dynamically that doesn't work in this scenario and that's not something we can help with.

**Comment by andersson09** [comment]
> @andersson09 you probably need to check at what time the script is being loaded/executed.
> 
> There's really nothing special about how this works on a Blazor app compared to a regular HTML document, so whatever mechanism you come up with, if it works with a regular HTML document it should work with Blazor.
> 
> From what I can tell, there's something in the way that you are setting the base path dynamically that doesn't work in this scenario and that's not something we can help with.

Is there a dotnet build/publish parameter I can pass which allows me to set the base path instead of dynamically setting it in the html at runtime? This would also meet my requirement.

**Comment by javiercn** [comment]
@andersson09 there is no such parameter.

The best option you have is to implement this yourself with an MSBuild task that reads a "template" index.html and replaces a constant value with the base path you expect.

**Comment by andersson09** [comment]
Thanks @javiercn. Similarly I just used sed to replace the base tag in my ci. However, it feels like a hack so would maybe be nice in the future to allow a parameter to be passed. :)

**Comment by javiercn** [comment]
@andersson09 what we recommend in these situations is that you make your dev environment match your production environment and use a base path during development too.

**Comment by andersson09** [comment]
Unfortunately I need to use different base paths depending on the environment
