### ISSUE TITLE
[Question] `HttpContext.TraceIdentifier` vs `Activity.Current.Id`

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#39873]
I asked this [on SO](https://stackoverflow.com/q/70828928/9971404) first. There are no relevant docs.

I use a "trace id" in logs. Advice here, on the docs site and on SO is to get a traceid from `HttpContext.TraceIdentifier`.

But when the [framework](https://github.com/dotnet/aspnetcore/blob/55738ff96b832439076e25584cfe0eb3bace9b01/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L90) creates a `ProblemDetails` for a validation failure, it uses `Activity.Current?.Id`.

Examples:
````C#
var traceId1 = Activity.Current?.Id;         // 00-2a8ee37903e657e3a95b41178dafc56e-91b02006afcf3133-00
var traceId2 = HttpContext.TraceIdentifier;  // OWZ4G27FO6UWH:00000003
````

I'm worried that *my logs use one type, and the framework uses another* - and when I need to analyse logs I'll have a problem.

Which does the framework typically use? And which should I use?

**Comment by adityamandaleeka** [comment]
@lonix1 Activity is a logical concept that can be defined at whatever granularity makes sense for the use case. The idea is that you can have one unit of tracking that spans as much as you need it to for the purpose of your diagnostics.

HttpContext's TraceIdentifier, on the other hand, is for a specific request.

As a concrete example, if you had a social networking site with multiple backend services, you may choose to define "load a user's profile page" as an Activity, and have many requests to the various services happen in the context of that Activity.

Therefore the answer to "which should I use" is really dependent on how you use Activity in your use case, and your needs for how to consume the logged information (do you need per-request granularity? do you want logs for a logical action across multiple requests to be easily correlated? etc.).

**Comment by lonix1** [comment]
@adityamandaleeka Thanks for the info! So simply stated an activity spans multiple requests. I can see how that could be useful, especially in a microservices design.

However the underlying problem still exists. The standard approach is to use `HttpContext.TraceIdentifier`, but I discovered the framework uses `Activity.Current?.Id` in at least one place, possibly more. When I analyse my logs and try to correlate "stuff", I will fail because different logs - related to the same request - were logged using different trace ids. Hence the original question.

I think anyone reading this now will understand the difference between the two. But we still need clarity as to which the framework uses when it does any kind of logging. I want to use whatever the framework uses, and I hope that the framework is consistent in how it does logging.

**Comment by Tratcher** [comment]
It sounds like what you want is scopes. Take a look at this:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#automatically-log-scope-with-spanid-traceid-parentid-baggage-and-tags

**Comment by lonix1** [comment]
Thanks for that info. *I might be misunderstanding*, but it seems like more than what I'm after.

What I concerns me is that all logging docs say to use `HttpContext.TraceIdentifier` which works nicely. But the framework uses `Activity.Current.Id` (in one, possibly more places) and so my logs have two types of trace ids which cannot be correlated. That is the issue: I'm interested in the discrepancy.

**Comment by rafikiassumani-msft** [comment]
@lonix1 Which document are you referring to that recommends using `TraceIdentifier` ?

**Comment by lonix1** [comment]
@rafikiassumani-msft I'm sorry I don't have ready links anymore. But whether the docs need updating or not, on StackOverflow that is the standard advice. Namely, "get a trace id from `HttpContext.TraceIdentifier`".

But there are two ways to do this. Which is the proper way? I want to do whatever the framework does to keep consistent.

**Comment by lonix1** [comment]
This shouldn't be locked - it hasn't been addressed.
