### ISSUE TITLE
Blazor Wasm Hosted App startup Project issue

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#39878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am running into problem after upgrading VS2022 to latest version (Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.1.0 Preview 4.0)

Every time open the project the startup project is now the client project. I can change that manually to Server project, but looks like it has no effect. I can tell that because all my API calls are returning back index.html.

Changing the startup project manually does highlight(bold) the server project but looks like when i run it, it run the client project.

### Expected Behavior

It should run the Project that is marked as startup project.

### Steps To Reproduce

Upgrade the project to latest version of Visual Studio, open the Blazor Wasm Hosted Project and you will notice that it has changed the startup project to Client Project.

### Exceptions (if any)

after running the app it loads the ui form client project and clicking any button which makes calls to backend API returns the index.html as response.

### .NET Version

 Version:   6.0.200-preview.22055.15

### Anything else?

C:\Users\admin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22055.15
 Commit:    a3c3a2bf3b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nssidhu** [comment]
Update, Debugging works fine(runs the server project) , but Start without Debugging (Ctlr + F5) always runs the Client Project

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

This seems to be a Visual Studio issue. In order for you to get a better and faster answer, we recommend you report this through the [visual studio report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) functionality in Visual Studio.

/cc: @BillHiebert @vijayrkn
