### ISSUE TITLE
SignalR can't invoke server method from client with throttled connection

### ISSUE THREAD

**Issue by dani2221** [dotnet/aspnetcore#39885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Invoking a server method from a javascript client with a throttled connection from the developer console (slow 3g, fast 3g) fails. The connection is established correctly, but cannot invoke any hub methods. If the connection isn't throttled it works as expected.

### Expected Behavior

Should be able to invoke hub methods on throttled connections to simulate real-life scenarios. It should work the same as non-throttled connections but slower.

### Steps To Reproduce

- Using DotNet 6 with SignalR and a javascript client
- Open the developer console on the client and throttle the connection to slow 3g, fast 3g, or a custom one
- Try invoking a hub method

### Exceptions (if any)

Getting the following exceptions on the client side:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/55097438/151760228-7d5a2d2e-576b-4d74-be47-b5b6912c53f7.png">

### .NET Version

v6.0.100

### Anything else?

Using chrome developer tools,

dotnet --info output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by BrennanConroy** [comment]
Until a couple months ago it looks like Chrome didn't do anything to throttle WebSocket connections.
Chrome 96 looks like it added the feature but if you read the issue, you can see that there are bug fixes after the feature landed.
> Streamline websocket interruption logic and fix issue when reading frame is not restarted after the interceptor interruption.

https://bugs.chromium.org/p/chromium/issues/detail?id=423246#c98

Downloading the dev channel of Chrome (Chrome 99) and trying this out results in a working WebSocket connection when using "Fast 3G" and "Slow 3G".
