### ISSUE TITLE
FromServices in MVC package instead of DependencyInjection?

### ISSUE THREAD

**Issue by sweeperq** [dotnet/aspnetcore#39881]
What is the reason **FromServicesAttribute** is in the MVC package instead of in **Microsoft.Extensions.DependencyInjection**?  I have some classes with one method and often use constructor injection with private backing fields to provide the dependencies for the single method. It would be nice to shorten things up with **FromServices**, but that would also require dragging the MVC namespace into my application layer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d2cf2e-55fb-33a4-b1d4-c97b2d531741
* Version Independent ID: f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf
* Content: [Dependency injection into controllers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
`Microsoft.Extensions.DependencyInjection` doesn't understand this attribute, it's always been an MVC feature.
