### ISSUE TITLE
Starting the Server from WebApplicationFactory

### ISSUE THREAD

**Issue by steinbachio** [dotnet/aspnetcore#39893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to make the Application start from my Test Project with WebApplicationFactory so I can run E2E Tests with Playwright but I can't use it via HTTP. Only the integrated HttpClient (from .CreateClient()) works.

AFAIK thats by design because the Application only starts 'InMemory' and die client is simulating real HTTP.

With .net 5 and earlier it was not that hard to write an WebApplicationFixture that creates the Server and uses the StartUp class.
With .net 6 and Minimal API, StartUp is gone and I am not able to Modify and Start the Application like before.

### Describe the solution you'd like

It would be nice to have either documentation on how to achieve this. I could find very few documentation on Integration Tests (which is using the InMemory features) and no official documentation on how to run E2E Tests with any of the Major Testing Frameworks.

Adding a Function to WebApplicationFactory that really runs the application would be great. Extending the Documentation for that would also help.

**Comment by davidfowl** [comment]
I believe @martincostello has a ton of experience with this.

**Comment by martincostello** [comment]
Hey @steinbachio - I've got a sample repo that you can take a look at for some guidance on how to achieve self-hosting an ASP.NET Core application using Minimal Hosting with `WebApplicationFactory` and using it to write automated browser tests using Playwright.

You can find the code for it at https://github.com/martincostello/dotnet-minimal-api-integration-testing, with the [`HttpServerFixture`](https://github.com/martincostello/dotnet-minimal-api-integration-testing/blob/main/tests/TodoApp.Tests/HttpServerFixture.cs) class providing the relevant code for hosting the application with a real HTTP port available for browser testing.

I also did a talk about it at a meet-up last year, which is [available on YouTube](https://youtu.be/FPpSg1ZEYZM?t=2077) (the link skips to the specific part of the recording).

Let me know if anything needs any further explanation or isn't clear.

**Comment by steinbachio** [comment]
@martincostello Wow! Thats exactly what I was looking for!

Somehow I didn't find it in the last days when I was searching for E2E, asp.net core and Playwright. Maybe because its saying Integration Tests.

If you could add this to the official documentation, probably a lot of people would benefit from that!

Now I have what I was looking for. Thank you!
