### ISSUE TITLE
SignalR HttpContext access

### ISSUE THREAD

**Issue by emanuel-v-r** [dotnet/aspnetcore#39894]
Hi,

I am accessing HttpContext via IHttpContextAccessor in the context of signalR connections.
From time to time I am getting NullReference exceptions, as sometimes HttpContext seems to be null.
I didn't understand the pattern yet (maybe the issue is with long polling, not sure) but I've realized that the proper way to get the HTTP context via SignalR connections could be the following extension method https://github.com/aspnet/SignalR/blob/master/src/Microsoft.AspNetCore.SignalR/GetHttpContextExtensions.cs.
Assuming that this way of accessing HttpContext would solve my issue, something that I would like to avoid is passing this HTTP context to all subsequent method calls.
Do we have any way of accessing it via DI?
I know that we have access to IHubContext interface via DI https://github.com/SignalR/SignalR/blob/main/src/Microsoft.AspNet.SignalR.Core/IHubContext.cs, but the problem is that it doesn't expose HttpContext.
Thanks in advance.

**Comment by adityamandaleeka** [comment]
If you're already in a hub method, you can use `Context.GetHttpContext` as you mentioned.

If you preserve the execution context, IHttpContextAccessor should work. This might be helpful: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#httpcontext-access-from-a-background-thread

**Comment by emanuel-v-r** [comment]
> If you're already in a hub method, you can use `Context.GetHttpContext` as you mentioned.
> 
> If you preserve the execution context, IHttpContextAccessor should work. This might be helpful: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#httpcontext-access-from-a-background-thread

That's the thing, IHttpContextAccessor in some scenarios is not working. I suspect that it may be related to Long Polling...
As for the GetHttpContext, yes I can do it inside the Hub, my question is if it's possible to get it outside the hub, by using DI.

**Comment by BrennanConroy** [comment]
> My understanding is that under the hood SignalR handles specifically scenarios such as Long Polling, in a way that GetHttpContext would return a not null http context while the IHttpContextAccessor would return a null http context.

Correct.

> my question is if it's possible to somehow get it outside the hub, by using DI.

Not unless you pass the HttpContext from somewhere that has it (like your Hub method), or use IHttpContextAccessor. It wouldn't make sense to have arbitrary services that aren't necessarily running in the context of a request get an HttpContext from DI. The workaround if you know you are running during a request is IHttpContextAccessor.

**Comment by emanuel-v-r** [comment]
> > My understanding is that under the hood SignalR handles specifically scenarios such as Long Polling, in a way that GetHttpContext would return a not null http context while the IHttpContextAccessor would return a null http context.
> 
> Correct.
> 
> > my question is if it's possible to somehow get it outside the hub, by using DI.
> 
> Not unless you pass the HttpContext from somewhere that has it (like your Hub method), or use IHttpContextAccessor. It wouldn't make sense to have arbitrary services that aren't necessarily running in the context of a request get an HttpContext from DI. The workaround if you know you are running during a request is IHttpContextAccessor.

Right, that's what I am currently doing, but then I have the risk of getting null context in scenarios such as long Polling (still I haven't confirmed that this the case, as the majority of the clients are probably getting ws connections)
Seems that I will have to pass this http context through the subsequent method calls.
Thanks for the help
