### ISSUE TITLE
Blazor WASM Hot Reload fails with websocket error

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/aspnetcore#39891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

When creating a new Blazor WASM project in VS 2022 17.0.5 (either WASM only or ASP.NET hosted), Hot Reload does not work. When looking at the browser log in Chrome there is a failure to call the websocket endpoint:

`WebSocket connection to 'ws://localhost:63660/BlazorApp1/' failed: `

which originates from aspnetcore-browser-refresh.js.

I have tried re-starting VS and re-booting to no avail. This happens when running under Kestrel. If I run with dotnet watch, everything works fine with no websocket failure and Hot Reload functioning correctly.

When running from VS, note there is a /BlazorApp1/ appended to the websocket address, however when running with dotnet watch it does not have this.

Am I doing something wrong or is something not setup correctly? I have the following in launchSettings.json:

`{
  "profiles": {
    "BlazorApp1": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "hotReloadEnabled": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:7035;http://localhost:5035",
      "dotnetRunMessages": true
    }
  }
}`

I have tried this in both VS2022 and VS 2022 preview.

Many  thanks for any help here as it would be great to have this running from VS2022.

### Expected Behavior

Blazor WASM Hot Reload should work from VS 2022 without websocket issues.

### Steps To Reproduce

1. Create a brand new Blazor WASM app (client only or ASP.NET hosted).
2. Run without debugging (Ctrl F5).
3. Changes not updated in browser, Chrome console shows websocket call failure:
![image](https://user-images.githubusercontent.com/3796984/151816855-8a8076a4-167f-4eb7-816b-79301bfa1dac.png)

### .NET Version

6.0.200-preview.22055.15

### Anything else?

6.0.200-preview.22055.15

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by sjbthfc2** [comment]
Hi,

Sorry, I don't understand, is this not the place to report Blazor issues such as WASM Hot Reload? Is this not supported in VS 2022?

Thanks

**Comment by javiercn** [comment]
@sjbthfc2 the best place to report VS issues is through the Visual Studio report a problem dialog. We do don't directly work on the visual studio integration and while we do pass these issues along to the right team, reporting it that way makes sure the team doesn't miss the report and are able to collect additional information like the exact version number, etc.

https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2022

**Comment by sjbthfc2** [comment]
Looks like this has already been raised:
https://developercommunity.visualstudio.com/t/Blazor-wasm-hot-reload-refresh-server-on/1608357?space=8&ftype=problem&preview2=true&q=blazor+hot+reload
