### ISSUE TITLE
Consider aliasing user-secrets CLI command as dev-secrets

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#39897]
We'd like to possibly consider expanding the scope of the user-secrets tool but reinforce the idea that it is a development time utility. This issue tracks adding an alias `dev-secrets` to the dotnet CLI command. 

Tools such as user-secrets / dotnet-watch in the SDK are resolved by https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/CommandFactory/CommandResolution/DotnetToolsCommandResolver.cs. The work here might be to update this to make it aware of the alias.

**Comment by pranavkm** [comment]
FYI @DamianEdwards

**Comment by adityamandaleeka** [comment]
Triage: we think this might add confusion, since there will be docs/guidance talking about user-secrets.
