### ISSUE TITLE
IIS: Using Windows Authentication assigns ClaimsPrincipal to User if AuthenticationSchemes are defined in an AuthorizationPolicy

### ISSUE THREAD

**Issue by snickler** [dotnet/aspnetcore#39901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running under IIS / IIS Express with Windows Authentication enabled, defining an AuthorizationPolicy with AuthenticationSchemes will assign a ClaimsPrincipal to the User of the current request instead of a WindowsPrincipal. 

In the past (.NET Core 2.1), I've unknowingly worked around this by returning an empty string array into the authenticationScheme parameter in the `AuthorizationPolicy` constructor, but I've noticed that simply adding any existing defined authentication scheme to the parameter - including "Windows" - will result in a `ClaimsPrincipal` assigned to `HttpContext.User` instead of a `WindowsPrincipal`.  

### This will return a `WindowsPrincipal` when `HttpContext.User` or `ControllerBase.User` is called. 

```
builder.Services.AddAuthorization(pol =>
 {
     pol.AddPolicy("WindowsAuth",
         new AuthorizationPolicy(
             new[] {new SomeRequirement() }, 
             Enumerable.Empty<string>());
 });
```

### This will return a `ClaimsPrincipal` when `HttpContext.User` or `ControllerBase.User` is called. 

```
builder.Services.AddAuthorization(pol =>
 {
     pol.AddPolicy("WindowsAuth",
         new AuthorizationPolicy(
             new[] {new SomeRequirement() }, 
             new string[] {"Windows"});
 });
```

I'm currently experiencing this in .NET Core 3.1, but realized that it also affects .NET 6 (and probably 5)

### Expected Behavior

If "Windows" is passed into the set of AuthenticationSchemes an AuthorizationPolicy should affect, a WindowsPrincipal should be assigned to the User of the current request instead of a ClaimsPrincipal.

### Steps To Reproduce

Repro Repo: https://github.com/snickler/authpolicyrepro

### .NET Version

6.0.101

**Comment by HaoK** [comment]
We improved this area already early in 7.0, if there's a single scheme we no longer copy it, so WindowsPrincipals would be unaffected when Windows is the only scheme asked for, this was added in https://github.com/dotnet/aspnetcore/pull/37135

But the setting of the User when an Authentication Scheme is specified is by design, we just wanted to smooth out the cases where we don't actually need to merge claims principals

**Comment by HaoK** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/32340

**Comment by snickler** [comment]
> Dupe of #32340

Does this fix only apply when there's ONE scheme defined? Or does it apply when with multiple schemes, as long as Windows is still defined as an auth scheme?

**Comment by HaoK** [comment]
Only one, if you specify multiple schemes, they get combined into one ClaimsPrincipal, basically don't mix windows auth with other auth schemes if you want to get a Windows Principal

**Comment by snickler** [comment]
Hmmm, then my problem would still persist. Only dealing with Windows auth I could sustain with my initial workaround, but needing to specify more than one would keep me in the same boat. Basically, I need Windows auth to continue as a WindowsPrincipal if it's challenged. Everything else should be a ClaimsPrincipal. 

For example, if I have Windows Auth and JWT Bearer registered as schemes in the Auth Policy (The ACTUAL issue that led me to opening this, but in troubleshooting saw that just any defined scheme caused the issue), if Windows Auth is picked up - I need it to be a WindowsPrincipal. If a Bearer token was sent, then it needs to be a ClaimsPrincipal.

**Comment by HaoK** [comment]
Can you split up your policies if you have hard requirements for them to be either a ClaimsPrincipal or WindowsPrincipal?  Or you will have to write your handler code to check what kind of principal it is

**Comment by snickler** [comment]
OH! 

I just tested with multiple auth schemes using the latest .NET 7 build from CI (7.0.100-preview.2.22103.2) and it works properly! 

Accessing an endpoint using Windows Auth brings in a WindowsPrincipal, whereas sending a Bearer token in will create a ClaimsPrincipal. 

I'm definitely fine with this behavior.

**Comment by snickler** [comment]
> Can you split up your policies if you have hard requirements for them to be either a ClaimsPrincipal or WindowsPrincipal? Or you will have to write your handler code to check what kind of principal it is

The way I currently make it work with .NET Core 3.1 / 6 as a hacky workaround is to check whether the user isn't a WindowsPrincipal but the Identity is a WindowsIdentity. That's how I know it was initiated through Windows Auth. From there, I just assign a WindowsPrincipal. That gets me around the problem. 

```csharp
if (!(ctx.HttpContext.User is WindowsPrincipal) && ctx.HttpContext.User.Identity is WindowsIdentity wi)
                    ctx.HttpContext.User = new WindowsPrincipal(wi);
```
