### ISSUE TITLE
EnableAuthenticatorModel shows page even if user was not found

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [dotnet/aspnetcore#39909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `EnableAuthenticator` shows the page even if the respective user was not found. There seems to be a `return` missing in the check [here](https://github.com/dotnet/aspnetcore/blob/15fa3ad10859abcc54e3ad5557dc928f6c94994d/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/Manage/EnableAuthenticator.cshtml.cs#L108).

**Comment by HaoK** [comment]
Keeping this open until the scaffolding side is done as well

**Comment by HaoK** [comment]
https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cs.cshtml#L109

**Comment by danirzv** [comment]
@HaoK I've sent a PR for it a moment ago.
https://github.com/dotnet/Scaffolding/pull/1819

**Comment by HaoK** [comment]
Awesome closing this out as fixed now
