### ISSUE TITLE
Unhandled exception rendering component: The provided expression contains a PropertyExpression which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object

### ISSUE THREAD

**Issue by nyluhe** [dotnet/aspnetcore#39906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/86660154/151964316-d896beac-9113-484d-90b0-fc580a7f3732.png)

I am getting the above exception when trying to load any razor component that contains a Blazor Input. Any Razor component that contains simple html inputs is working fine. The issue we're having is that this isn't an issue when running locally, but when we upload this project to a Web App in Azure, we see this exception. 

Here is the view I am trying to render:
![image](https://user-images.githubusercontent.com/86660154/151964605-3f383fbc-a683-421c-82cd-ee31646d45c1.png)

I have tried removing the ValidationMessages, the DataAnnotation Validators and using InputText's for both of the fields in the form. The Dto is a simple class:

` public class UserLoginDto`
    `{`
        `public string Email { get; set; }`
        `public string Password { get; set; }`
        `public bool IsPersistent { get; set; }`
    `}`

I believe this to be an issue with dotnet.5.0.13.js/dotnet.5.0.13 in general as we have multiple projects that run on dotnet 5.0.9 - 5.0.11 without issue in Azure - all using WASM and all using the exact same Azure configurations.

### Expected Behavior

The Edit Form renders.

**Comment by nyluhe** [comment]
I can attempt to link to a GitHub repo if necessary, but you'd be required to upload to Azure to see an impact.

**Comment by nyluhe** [comment]
Ok here is the site that I'm hosting: https://example-wasm.azurewebsites.net/ you need to go to the home page to catch the error.

Here is the repo: https://github.com/nyluhe/ExampleBlazorWasm/tree/master/ExampleBlazorWasm/Client

The Input fields have been added to the SurveyPrompt blazor component. I've created two forms, one that uses EditContext and one that uses Dto.

I'm also going to add another version to a different page that doesn't use validations too.

**Comment by nyluhe** [comment]
I have tried this on Firefox, and Chrome (both up to date) so I don't think this issue is browser based. I have tried to revert my current application back to 5.0.11, but it seems to maintain the 5.0.13 dotnet.js file regardless of what I do in VS.

**Comment by pranavkm** [comment]
@nyluhe could you try adding a global.json file to your repo to pin to specific version of the SDK? `5.0.402` is the version of the SDK that shipped alongside 5.0.11 so we could start from there. 

{
  "sdk": {
    "version": "5.0.402"
  }
}

I can't reproduce your issue locally, but I can see it failing in the app. I can observe some curious build artifacts and indications that the app was being built with a 6.0 SDK, perhaps this is the result of one of these?

**Comment by nyluhe** [comment]
@pranavkm the issue doesn't happen locally, it only seems to happen when published to azure. I've added global.json pointing to the .NET SDK (5.0.404) but I'm unsure how this could have been built against a .NET 6.0 SDK? We use a template project that was on 5.0.9 and I updated it to 5.0.13 before starting the current project I'm on.

**Comment by pranavkm** [comment]
> but I'm unsure how this could have been built against a .NET 6.0 SDK

Unless constrained by a global.json, VS / dotnet cli will use the highest available version of the .NET SDK. VS 2022 would have installed a 6.0 SDK installed, so perhaps that's how you had one. Did adding the global.json and republishing the app to App Services help remedy the issue?

**Comment by nyluhe** [comment]
Hi, @pranavkm, that did resolve it. However, this still seems like an issue in my opinion - I have been using .NET 2017 with multiple versions of NET in the last year and have never had to do this before.

So why is this now an issue when using .NET 5 on VS 2022?
