### ISSUE TITLE
LogLevel Warning is somewhat verbose for LoggerEventIds.VerifyUserTokenFailed in the UserManager

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#39910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The log level `warning` for failed token verification is somewhat verbose.

Consider the case of TOTP tokens used for email verification. Those tokens might expire faster than a token in an url, or even more the user might not directly confirm their email using the TOTP token.
Logging those as `warning` seems somewhat verbose.

### Describe the solution you'd like

Reduce the log level to `information`?

### Additional context

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/UserManager.cs#L1725

**Comment by Tratcher** [comment]
Triage: A common error like this should be logged at the Debug level.
