### ISSUE TITLE
Develop RDLC Generating Library for Cross Plateform

### ISSUE THREAD

**Issue by chhinsras** [dotnet/aspnetcore#39912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There is library like AspNetCore.Reporting. But this is seemed buggy and not active matain. 
Or this .https://github.com/lkosson/reportviewercore

### Describe the solution you'd like

Should there be some small library for generating local report from RDLC.

**Comment by javiercn** [comment]
@chhinsras thanks for contacting us.

Our team is focused on the runtime and the framework and very rarely works on other integrations.

For you to get a better and faster answer I would encourage you to make this request through the [suggest a feature for visual studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022) option.

/cc @danroth27 @JeremyLikness as you might know who to forward this request to.

**Comment by JeremyLikness** [comment]
Hi, there are no plans for any future development of RDLC. For more information see: [this blog post](https://powerbi.microsoft.com/blog/how-to-integrate-power-bi-reporting-into-net-apps/).
