### ISSUE TITLE
Should `failureMessage` in `AuthenticateResult` be nullable?

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/aspnetcore#39916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following two signature state that `failureMessage` is non-nullable.

```csharp
public static AuthenticateResult Fail(string failureMessage) 
    => Fail(new Exception(failureMessage));

public static AuthenticateResult Fail(string failureMessage, AuthenticationProperties? properties)
    => Fail(new Exception(failureMessage), properties);
```

But `failureMessage` is passed into `Exception(string? message)`, where `message` _is_ nullable. I don't see any other constraints as to why `failureMessage` should be non-nullable.

`failureMessage` was originally nullable until [this commit](https://github.com/dotnet/aspnetcore/commit/00bbb78d3c96d81afa9febb128aacf5c1365293d).

I ran into this because I was trying to pass `null` into `failureMessage` and didn't understand why it was complaining.

### Expected Behavior

`failureMessage` is nullable.

### Steps To Reproduce

```csharp
AuthenticateResult.Fail(null);
```

### .NET Version

6.0.101

**Comment by Tratcher** [comment]
Hmm, we'd recommend there be a failure message for diagnostic purposes, but you're right that there doesn't technically need to be. Is there a reason you don't want to pass a message?

**Comment by MisinformedDNA** [comment]
I was refactoring code, so I wasn't directly setting the messages. I think `Message` is nullable because it is `null` when `IsSuccess` is `true` (see below).

```csharp
class AuthResult
{
   public bool IsSuccess { get; set; }
   public string? Message { get; set; }
}
```

**Comment by HaoK** [comment]
While we could allow failureMessage to be nullable, its intent is to provide a useful error message, since developers can always ! or pass string.empty we don't plan on changing this.
