### ISSUE TITLE
HttpLoggingMiddleware doesn't always log request body

### ISSUE THREAD

**Issue by clapis** [dotnet/aspnetcore#39911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The request body is not always logged, or more precisely, it's logged as empty in some cases. 

It seems to be only logged when the request body stream has been read by another middleware or component (In [BufferingStream](https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Middleware/HttpLogging/src/BufferingStream.cs#L58), `_head` & `_tail` are never set if the stream is not accessed and thus log output is empty). 

### Expected Behavior

Maybe this is by design, but I did expect the request body to be logged even if the request body is not used by another middleware. I can think of two scenarios where this is an issue (see repro project):

- When the body of the request is not declared/used in the controller's action
- When developers want to log any request to the application 

### Steps To Reproduce

Repro project: https://github.com/clapis/http-logging-middleware-issue/

```
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpLogging(opts => opts.LoggingFields = HttpLoggingFields.RequestBody);

var app = builder.Build();

app.UseHttpLogging();

app.MapPost("/hello", (Person person) => $"Hello {person.Name}!");

app.MapPost("/bye", () => "Bye!");

app.Run();

class Person
{
    public string Name { get; set; } = "Stranger";
}
```

```
## OK - request body is logged as expected
curl --location --request POST 'http://localhost:5000/hello' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "Bob"
}'

## Request body is not logged 
curl --location --request POST 'http://localhost:5000/bye' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "Bob"
}'


## 'Unhandled' requests also don't log the request body
 curl --location --request POST 'http://localhost:5000/things' \
 --header 'Content-Type: application/json' \
 --data-raw '{
 "id": 123
 }'


```

### .NET Version

6.0.101

### Anything else?

$ dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.415 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  5.0.300 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by davidfowl** [comment]
The middleware doesn't read the body preemptively. It logs when another component consumes the body. This would need to be another option to eagerly read the body (would would be less efficient since that would imply the entire body would be buffered). To work around this, you can add a middleware that does the buffering/consuming of the body and then rewinds it for future middleware to consume.

**Comment by clapis** [comment]
I thought the intention of this bit here was to log the request body in case the stream hadn't been entirely consumed (and logged) before

https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L165

Which seems to make sense (in my head 😅) also when a stream hasn't been consumed at all - it would be read solely by the logging middleware once. Perfomance-wise it would be still a single read of the stream and no need to eagerly buffer the entire stream, no?

**Comment by Tratcher** [comment]
@clapis I think that logs what has been read so far(?). Reading the request body on behalf of the application is dangerous since the app may have chosen not to consume the body on purpose (e.g. authorization failure or other refused requests).

**Comment by clapis** [comment]
Oh I see, didn't realize this security aspect in play here 👍 

Thank you for the clarification! 🙏
