### ISSUE TITLE
Blazor server side, NavigationManager.NavigateTo not checking AuthenticationState

### ISSUE THREAD

**Issue by giuseppe-terrasi** [dotnet/aspnetcore#39929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I navigate to a protected page using NavigationManager.NavigateTo("/path") the AuthenticationState is never updated and I can see the page even if I delete the cookie from the browser. It works fine if the page is refreshed. I tried to use the OnNavigateAsync parameter of the Router to read the cookie from the request before navigating to the target page and I noticed that it is always sent until I refresh the page. Checking the request path, it is "/_blazor" so the request read by the authentication state is the WebSocket connection which contains the old cookie.

### Expected Behavior

Redirect to the login page or NotAutorized component execution

### Steps To Reproduce

Startup.cs
```
public void ConfigureServices(IServiceCollection services) {
...
services.AddAuthentication("Identity.Application").AddCookie();
...
}


public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {

...

  app.UseRouting();

  app.UseAuthentication();
  app.UseAuthorization();

}
```

App.razor
```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData">
                <Authorizing>
                </Authorizing>
                <NotAuthorized>
                    <RedirectToLogin />
                </NotAuthorized>

            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```
RedirectToLogin.razor
```
@inject NavigationManager Navigation
@layout EmptyLayout

@code {
    [CascadingParameter]
    private Task<AuthenticationState> AuthenticationStateTask { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var authenticationState = await AuthenticationStateTask;

        if (authenticationState?.User?.Identity is null || !authenticationState.User.Identity.IsAuthenticated)
        {
            var returnUrl = Navigation.ToBaseRelativePath(Navigation.Uri);

            if (string.IsNullOrWhiteSpace(returnUrl))
                Navigation.NavigateTo("/Login", true);
            else
                Navigation.NavigateTo($"/Login?returnUrl={returnUrl}", true);
        }
    }
}
```

### .NET Version

6.0.101

### Anything else?

`dotnet --info` output:

```
.NET SDK (che rispecchia un qualsiasi file global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
```

**Comment by javiercn** [comment]
@giuseppe-terrasi thanks for contacting us.

The user Identity in Blazor Server is established when the app connects through the websocket and its maintained for the lifetime of the circuit unless you update it in your app code.

**Comment by giuseppe-terrasi** [comment]
@javiercn Thanks for your reply. 

How can I update it? I haven't found anything in all the examples, including the generated code of a new project with authentication.

**Comment by javiercn** [comment]
@giuseppe-terrasi I asked @SteveSandersonMS for the samples/docs as I'm not able to find them myself. There is a `RevalidatingAuthenticationStateProvider` base class that you can use and I believe that when you are using Identity there is a concrete implementation that we drop on the project during creation. See https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Areas/Identity/RevalidatingIdentityAuthenticationStateProvider.cs for a sample

**Comment by giuseppe-terrasi** [comment]
@giuseppe-terrasi I saw the class `RevalidatingAuthenticationStateProvider ` inside the project but it doesn't perform the operation that you suggest. In fact, the described issue is present: 

- create a new project with individual user authentication,
- run the migration
- Add `[Authorize]` attribute on a page, say Counter
- run the application
- login into the application
- delete the cookie 
- navigate to Counter page **without refreshing the page**
- You are able to navigate instead of getting blocked

**Comment by javiercn** [comment]
@giuseppe-terrasi I pointed the code as a "base" you can use for implementing what you are looking for.

As I mentioned, in Blazor Server the authentication context is established when the app starts (first connects to the websocket) and is maintained through the lifetime of the circuit. If you want to update it after the app has started, you need to use a mechanism similar to the one Identity uses.

**Comment by giuseppe-terrasi** [comment]
As "base" code for a project with authentication, I will aspect that this "base" functionality was implemented out of the box or at least documented somewhere in the official documentation. Checking the authentication during navigation is a must-have in all projects.

**Comment by SteveSandersonMS** [comment]
> Checking the authentication during navigation is a must-have in all projects.

That is indeed what happens, however you should not expect cookies to be involved in that. Cookies are only sent when making an HTTP request to the server, which is not what happens when the user navigates. The auth state that is checked when the user navigates is their auth state within the circuit, which you can update at any time on the server using `RevalidatingAuthenticationStateProvider` or custom code.

I know this differs from a traditional server-rendered website which does make new HTTP requests with cookies on every page navigation. The fact that this is not obvious is a concern and perhaps we need to emphasise it more strongly in the docs.

**Comment by javiercn** [comment]
To add to what @SteveSandersonMS said.

I think there is a mismatch on the expectations here.

* From our point of view, the authentication context is established when the app is started and preserved through the lifetime of the circuit as opposed to a traditional web application where it happens on each request.
* We provide an out of the box solution based on Identity to revalidate the user identity periodically.
* We provide extensibility for people to plug-in their own mechanisms if you are using any other form of authentication.

**Comment by giuseppe-terrasi** [comment]
@SteveSandersonMS I agree with you about emphasizing this concept more strongly in the docs.

@javiercn and @SteveSandersonMS the periodic revalidation mechanisms could not be enough in some circumstances. Could overriding the NavigationManager class be a solution to achieve the Identity validation during the navigation? I noticed now that the NavigateToCore method is now a virtual method, it was abstract previously.

Thanks.
