### ISSUE TITLE
Add EndpointMetadataCollection.GetRequiredMetadata

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#39921]
## Background and Motivation

`EndpointMetadataCollection` has a `GetMetadata<T>()` method:

```csharp
public T? GetMetadata<T> () where T : class;
```

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.endpointmetadatacollection.getmetadata?view=aspnetcore-6.0#microsoft-aspnetcore-http-endpointmetadatacollection-getmetadata-1

It returns null if there is no matching metadata. It would be useful to have a `GetRequiredMetadata<T>()` method that returns a value or throws.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http
{
    public class EndpointMetadataCollection
    {
+       public T GetRequiredMetadata<T> () where T : class;
    }
}
```

The method would function the same as getting a required service from DI or a required feature from a feature collection.

## Usage Examples

```csharp
endpoints.MapGet("/", context =>
{
    var endpoint = context.GetEndpoint();
    var requiredMetadata = endpoint.Metadata.GetRequiredMetadata<MyMetadata>();
});
```

**Comment by pranavkm** [comment]
API review: we discussed moving the method to `Endpoint`, but didn't think it was necessary. API approved as proposed.
The exception message and type should follow the same pattern `GetRequiredFeature` / `GetRequiredService`

**Comment by JamesNK** [comment]
Error example from `GetRequiredFeature`: https://github.com/dotnet/aspnetcore/blob/d40eea990edd1ac7205a983cbe4d13a71fd4ad68/src/Extensions/Features/src/FeatureCollectionExtensions.cs#L28

**Comment by berkansasmaz** [comment]
@JamesNK Hello! I can work on this. Can you please assign it, if it isn't being worked on already?
