### ISSUE TITLE
Survey: Repo Contribution Experience 2022

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#39936]
It's that time of the year again!

We spend a lot of time making ASP.NET Core better through the year, but keeping the repo productive, approachable, and healthy is important to us as well!

Over the past year, we've been rolling out small improvements to improve approachability in the repo:

- Adding support for GitHub Codespaces
- Improving our build documentation
- Improved documentation of our issue management and triage process

We'd love to learn more about what we can do to keep making contributing and participating in the aspnetcore repo better!

To that end, we've love your feedback in this year's repo contribution experience survey.

Survey Link: https://www.surveymonkey.com/r/8QTQTGJ?Source=aspnetcore

**Comment by captainsafia** [comment]
@campersau @Youssef1313 @ShreyasJejurkar @martincostello @Kahbazi @albi005 @yecril71pl @CodeBlanch @ylabade @z77ma @gbtb @AraHaan @fvoronin @lbosquett @david-acker @vanillajonathan @adrianwright109 @egil 

Pinging a few repo regulars and contributors from the past year to share feedback on the survey in case you haven't already!

**Comment by danmoseley** [comment]
Survey is now closed and we'll dig through your feedback. Thanks everyone that responded.
