### ISSUE TITLE
Authorize attribute with JWT token is checked only when connection is made on websocket

### ISSUE THREAD

**Issue by gregoriusus** [dotnet/aspnetcore#39934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I found interesting bug. If I use Signalr via websocket and JWT token for authentication, Authorize attribute on Hub method doesn't have any effect once connection is made. JWT token is sent via query string and this is covered via accessTokenFactory parameter. Great. But if the token expires later, Authorize doesn't have any effect anymore. I guess that validation of the token should be checked upon every message sent from the client. Just like for API is checked upon each HTTP call.

### Expected Behavior

Check JWT token validation for every message sent. And enable token refresh functionality, without reconnecting when the token expires.

### Steps To Reproduce

Enable [Authorize] on Hub Method. Set JWT authentiaction on Signalr as it is described in documentation. Create short lived JWT token and call Hub method. Even if token expires, method still can be called.

### .NET Version

CORE 6.0

**Comment by gregoriusus** [comment]
But still. On high loaded system it is not recommended to close and reconnecte session on x minutes when the token expires. Is there a solution in planning to refresh the token and leave the connection open? Just to change token in URL of connection.

**Comment by BrennanConroy** [comment]
There are plans on improving auth tracked in https://github.com/dotnet/aspnetcore/issues/5297
We'll still likely close the connection though.

**Comment by gregoriusus** [comment]
There is already opened issue and I am closing this issue and commenting on #5297

**Comment by gregoriusus** [comment]
There is already an opened issue and I am closing this issue and commenting on #5297
