### ISSUE TITLE
FileBufferingReadStream - CanRead and CanSeek should return !_disposed

### ISSUE THREAD

**Issue by snakefoot** [dotnet/aspnetcore#39939]
https://github.com/dotnet/aspnetcore/blob/6850cc8187751cdec3e4071e8786aeffe29d11ee/src/Http/WebUtilities/src/FileBufferingReadStream.cs#L187-L195

**Comment by pranavkm** [comment]
That sounds like a reasonable change @snakefoot. Would you like to send us a PR?

**Comment by snakefoot** [comment]
@pranavkm Created PR #40016
