### ISSUE TITLE
Blazor Hybrid validation cases

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#39933]
This issue is to track creation of automated or CTI tests for Blazor Hybrid scenarios.

| Target | from Windows | from Mac |
| :------------- | :------------- | :------------- |
| Android | ✅https://github.com/dotnet/maui/issues/4919 | ✅https://github.com/dotnet/maui/issues/4925 |
| iOS | ✅https://github.com/dotnet/maui/issues/4921 | ✅https://github.com/dotnet/maui/issues/4920 |
| Mac | ✅https://github.com/dotnet/maui/issues/4923 | ✅https://github.com/dotnet/maui/issues/4924 |
| WinUI |✅https://github.com/dotnet/maui/issues/4926 | n/a |
| WinForms | ❌ [Some steps fail](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VS/BlazorHybrid/60_BlazorHybrid_WinForms.md) | n/a |
| WPF | ✅https://github.com/dotnet/maui/issues/4927 | n/a |

⌛ = No CTI steps yet prepared

TODO: Determine which of the above are supported. Some combinations might be publish-only without an accompanying developer experience (e.g., Linux CI might be able to publish with `-r win-x64`).

TODO: In each supported case, create and link to a CTI test that covers:

 * Creating the project
 * Core developer experience
   * Launching the app (e.g., in simulator/emulator where applicable)
   * Hot reload
   * Debugging
 * Core webview/Blazor-specific functionality
   * Consuming an RCL with components and static assets
   * Navigating between Blazor components and to external URLs
   * Event handling
   * File inputs
   * Unhandled exceptions
 * Publishing, and observing that the resulting app (including RCL assets, etc) does work

We may find that some of the core webview/Blazor-specific functionality can actually be covered by automated tests and hence is not needed in the CTI script.

**Comment by davidortinau** [comment]
For .NET MAUI:

- Mac as a target is not a supported scenario from Windows. 
- Windows as a target is not a supported scenario from Mac.
- "from Linux" is not a supported, though may work for Android

**Comment by SteveSandersonMS** [comment]
Thanks @davidortinau. I've updated the matrix.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT FYI I've filed issues for all the other scenarios here, and am bumping this meta-issue forwards into 7.0 Preview 3.

My suggestion is we treat the need for coverage like this:

P1:
- Android from Windows
- iOS from Mac
- iOS from Windows
- macOS from Mac
- WinUI
- WPF

P2:
- macOS from Windows (because mostly the tech will be covered by iOS from Windows)
- Android from Mac (because mostly the tech will be covered by Android from Windows)
