### ISSUE TITLE
Blazor WASM Lazy Loading with App Bundling

### ISSUE THREAD

**Issue by todd-urbo** [dotnet/aspnetcore#39935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have implemented both app bundling and lazy loading. However, when we try to navigate to a route that lazy loads an assembly we are getting an error indicating it cannot find the assembly.

### Expected Behavior

Lazy loading assemblies should work the same as without app bundling.

### Steps To Reproduce

Implement app bundling and lazy loading in the same client wasm project.

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/56551421/152206667-83e6cce3-c110-4dbd-b64f-29be091506bc.png)

### .NET Version

6.0

**Comment by javiercn** [comment]
Very likely [this](https://github.com/dotnet/aspnetcore/blob/8a95ee9b8b1bbd41357cd756375d78cec6936116/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L390-L398) shouldn't be passing the relative url.

**Comment by MackinnonBuck** [comment]
Closing this out since it's not evident that there's a framework problem to address.
