### ISSUE TITLE
Validation for MetadataType

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#39938]
this issue seem to be solved by @Xaeco and merged in net6: https://github.com/dotnet/runtime/pull/51772

Is it available in the current official release?

how to manage validation?

i tried using MetadataType attribute in a net6 blazor project but seem not working:

```
[MetadataType(typeof(MyMetadataType))]
public class MyClass
{
   public string MyProperty {get;set;}
}

public class MyMetadataType
{
   [Required]
   public string MyProperty {get;set;}
}
```

**Comment by ajcvickers** [comment]
@pranavkm @mkArtakMSFT Looks like a Blazor issue.

**Comment by mkArtakMSFT** [comment]
@Gambero81 did you try the suggestion provided by @Xaeco?

**Comment by CDEngineer** [comment]
Hello @Xaeco, I am learning Blazor, could you please take a quick look at my demo (is very, very simple code, I promise) and show me where I have to use that line of code? I tried several places with no success. Thanks in advance!

**Comment by aterbo** [comment]
I never managed to make this work satisfactorily either. It seems like something that either should be addressed or clearly added to the documentation where to make the `.AddProviderTransparent` call suggested by @Xaeco.

**Comment by Xaeco** [comment]
Here is a very basic example in C# not using Blazor. 

Create a new .NET 6 C# console app and replace the contents with the following
``` c#
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

// Associate the metadata type VehicleRequirementsMetaData to the Vehicle class
TypeDescriptor.AddProviderTransparent(new AssociatedMetadataTypeTypeDescriptionProvider(typeof(Vehicle), typeof(VehicleRequirementsMetaData)), typeof(Vehicle));

// Create a valid vehicle object with both properties populated
var newTruck = new Vehicle
{
    Name = "My Truck",
    Manufacturer = "Cool Hybrids Inc"
};

// Validate the object against it's attributes
var truckValidationResults = new List<ValidationResult>();
var truckValidationContext = new ValidationContext(newTruck);
if (Validator.TryValidateObject(newTruck, truckValidationContext, truckValidationResults))
{
    Console.WriteLine("newTruck object is valid");
}
else
{
    Console.WriteLine("newTruck object is invalid");
    foreach (var result in truckValidationResults)
    {
        Console.WriteLine(result);
    }
}

// Create a vehicle object that is missing the property assignment for Manufacturer
var newCar = new Vehicle
{
    Name = "My car"
};

// Validate the object against it's attributes
var carValidationResults = new List<ValidationResult>();
var carValidationContext = new ValidationContext(newCar);
if (Validator.TryValidateObject(newCar, carValidationContext, carValidationResults))
{
    Console.WriteLine("newCar object is valid");
}
else
{
    Console.WriteLine("newCar object is invalid");
    foreach (var result in carValidationResults)
    {
        Console.WriteLine(result);
    }
}

public class Vehicle
{
    public string Name { get; set; }
    public string Manufacturer { get; set; }
}

public class VehicleRequirementsMetaData
{
    [Required]
    public string Manufacturer { get; set; }
}
```

**Comment by Xaeco** [comment]
You can use the same approach in Blazor to associate the metadata type

**Comment by CDEngineer** [comment]
Hello @Xaeco,
Thanks for the code.
For Blazor, this did the trick:

```
    protected override void OnInitialized()
    {
        TypeDescriptor.AddProviderTransparent(new AssociatedMetadataTypeTypeDescriptionProvider(typeof(Collaborator), typeof(CollaboratorMetadata)), typeof(Collaborator));
    }

```

Thank you!

**Comment by Gambero81** [comment]
@Xaeco using `TypeDescriptor.AddProviderTransparent` validation seem to work, but now my problem is to check if a class property has a validation attribute (added explicitely or via `TypeDescriptor.AddProviderTransparent`).  

If a add a validation attribute explicitely to the class property, i can check:
`var attribute = (RequiredAttribute)property.GetCustomAttribute(typeof(RequiredAttribute), true);`

but adding an attribute in MedaData / `TypeDescriptor.AddProviderTransparent` it return null.

How can i check the presence of attributes added in this way?

Thanks
