### ISSUE TITLE
Provide documentation to use Owin correctly with ASP.NET Core 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#39943]
ASP.NET Core's current owin documentation does not details on adding the glue code to plug in things like logging, data protection, hosting shutdown tokens etc. For instance, https://www.codeproject.com/Articles/1122162/Implement-Owin-Pipeline-using-Asp-net-Core has a section about configuring the `OnAppDisposing` token using `IApplicationLifetime.ApplicationStopping`. 

This glue code is required to robustly run a existing Katana-based app on ASP.NET Core. This issue tracks this work.

**Comment by adityamandaleeka** [comment]
@Tratcher I'll let you decide how/when this should be addressed.

**Comment by Tratcher** [comment]
How about moving it to https://github.com/dotnet/systemweb-adapters/issues?

**Comment by davidfowl** [comment]
Sounds good to me.

**Comment by Tratcher** [comment]
Moved to https://github.com/dotnet/systemweb-adapters/issues/161
