### ISSUE TITLE
Cache IResult types for well known status codes and results without parameters

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#39951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We should optimize result allocation by caching common result instances (known status codes etc).

### Describe the solution you'd like

Caching of these result types.

**Comment by davidfowl** [comment]
Also any know status code.

**Comment by brunolins16** [comment]
> Also any know status code.

@davidfowl is this list good enough:

    `Status200OK`
    `Status204NoContent`
    `Status400BadRequest`
    `Status401Unauthorized`
    `Status403Forbidden`
    `Status404NotFound`
    `Status409Conflict`
    `Status412PreconditionFailed` 
    `Status415UnsupportedMediaType`
    `Status500InternalServerError`

Or, you want a cache for every known status code listed here (maybe it is too much 😂):
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/StatusCodes.cs

I am planning to have an `StatusCodeHttpResult` cached instance for each of them, in addition to, what I mentioned before.

**Comment by davidfowl** [comment]
Everything in that class.

**Comment by halter73** [comment]
@davidfowl @brunolins16 Do you think we should codegen this?

**Comment by brunolins16** [comment]
@halter73 I am benchmarking different ideas for the caching, but I have a feeling that it might be a good idea to codegen whatever idea we end up with.

**Comment by davidfowl** [comment]
Yes please t4?
