### ISSUE TITLE
Blazor IDisposable not working

### ISSUE THREAD

**Issue by rborosak** [dotnet/aspnetcore#39953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IDisposable is not working when the component implements both IDisposable and IAsyncDisposable.

Based on the empty Blazor Server project

`public partial class Counter : IDisposable, IAsyncDisposable`
`{`
`public void Dispose() {}`
`public ValueTask DisposeAsync(){ return ValueTask.CompletedTask; }`
`}`
           
 Only DisposeAsync method is called.  

### Expected Behavior

Both Dispose and DisposeAsync should be called.

### .NET Version

.NET 6

**Comment by javiercn** [comment]
@rborosak thanks for contacting us.

When you implement `IAsyncDisposable` it is preferred over `IDisposable` the expectation is that you fully dispose the object in both cases. It is expected that Dispose is called within the DisposeAsync, see [here](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern) for details
