### ISSUE TITLE
Add general property bag to cookies to support potential new cookie "standards:

### ISSUE THREAD

**Issue by blowdart** [dotnet/aspnetcore#39968]
### Problem

Google in their quest to remove third party cookies are [proposing moving to](https://developer.chrome.com/en/blog/progress-in-the-privacy-sandbox-2021-12/#cookie-cataloguing) yet [another cookie standard](https://github.com/WICG/CHIPS).

It's both better than, and worse than the same site changes we had to go through before to keep oauth's lights on for IdPs that couldn't support more modern flows.

The [CHIPS](https://github.com/WICG/CHIPS) proposal adds new attributes to cookies, and as we've traditionally had strong properties on cookies any new cookie property needs a lot of work to support, and we end up having a slow reaction.

### Potential solution

I propose a general property bag of names and values (with values allowing for NULL) for outbound cookie properties, which would allow customers to be more flexible in what gets added as a cookie property and not have to wait for us to push new code to test out a standard which may, or may not get ratified. 

Of course the property bag would have to nicely sync with the existing "strong" properties.

**Comment by Tratcher** [comment]
Design point: both `key=` and `key` can be valid formats depending on the parameter.  We might not know how to properly format entries from a key-value collection. A `List<string>` might be better, or even a flat `string` for people to append extra stuff to.

**Comment by blowdart** [comment]
@adityamandaleeka weve been asked by a couple of internal teams to make this available, rather than it just being me planning.

Please assign to a milestone coming soon so it doesn't get lost and adjust priority upwards as you see fit.

**Comment by Tratcher** [comment]
A contributor added SetCookieHeaderValue.Extensions back in 5.0 that should work for this. This covers the lowest layer that parses and serializes cookies.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.setcookieheadervalue.extensions
https://github.com/dotnet/aspnetcore/pull/22181

The next layer up that we need to add this to is CookieOptions and then CookieBuilder:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookieoptions
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiebuilder

These two APIs are used most places we work with cookies, like HttpResponse.Cookies.Append and CookieAuthenticationOptions, so we shouldn't have to do much additional work to expose it on individual components.

**Comment by Tratcher** [comment]
API Proposal:

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public class CookieOptions
{
+    public CookieOptions(CookeOptions options); // Copy constructor
+    public IList<string> Extensions { get; };
+    public SetCookieHeaderValue CreateCookie(string name, string value); // Factory
}

public class CookieBuilder
{
+    public IList<string> Extensions { get; };
}
```

## Usage Examples

```csharp
httpContext.Response.Cookies.Append(testCookie, "value", new CookieOptions()
{
     Extensions = { "simple", "key=value" }
});
```

```csharp
services.AddAuthentication().AddCookie(o =>
{
     o.Cookie.Extensions.Add("extension");
});
```
