### ISSUE TITLE
Differences between health check execution (.NET 3.1 and 6.0)

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/aspnetcore#39974]
While migrating from .NET 3.1 and .NET 6.0 we executed performance tests (JMeter) and detected that tests fails with high error percentage rate when executed with 100 parallel users on .NET 6.0. The same test on same environment with .NET Core 3.1 completes without no problem.

With further inspection we found that the cause of test to fail was that our Readiness probe failed on .NET 6 and it is not failing on .NET Core 3.1. Result of readiness probe was Unhealthy because it could not get Connection from Pool of Database connections (Postgres).

After deep analysis we found out that the issue on .NET 6 was that we have Health Check implementation which calls Async operations on Database (EF Core) with Wait() instead of using async await.

After changing everything to Async await the test passed fine.

Could someone please explain why did this work without the issue on .net core 3.1 and why it is not working now without the  changes we did?

Thanks

**Comment by captainsafia** [comment]
Hello @vasicvuk -- there haven't been any major changes in HealthChecks between 3.1 and 6.0 but some of the behavior that you are seeing might be related to changes in EF and the way you're invoked its APIs.

**Comment by vasicvuk** [comment]
@captainsafia Thanks for response, We changed all calls to async so it works now without any issue, i just wanted to know what was changed if someone knows.

Nevertheless, I am closing the issue since we resolved it.
