### ISSUE TITLE
Weird mix of Turkish and English when restoring

### ISSUE THREAD

**Issue by Forgind** [dotnet/aspnetcore#39978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Messages when running restore.cmd were in a mix of Turkish and English on a Turkish OS:
```
Building of NodeJS projects is disabled since node is not detected on Path and no BuildNodeJs or NoBuildNodeJs setting is set explicitly.
WARNING: Some managed projects depend on NodeJS projects. Building NodeJS is disabled so the managed projects will
fallback to using the output from previous builds. The output may not be correct or up to date.

  Geri yüklenecek projeler belirleniyor...
  'dotnet-serve' arac─▒ (s├╝r├╝m '1.8.15') geri y├╝klendi. Kullan─▒labilen komutlar: dotnet-serve
  'microsoft.playwright.cli' arac─▒ (s├╝r├╝m '1.2.2') geri y├╝klendi. Kullan─▒labilen komutlar: playwright

  Geri y├╝kleme ba┼şar─▒l─▒ oldu.
  C:\Users\forgind\.nuget\packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22080.1\tools\Tools.proj geri yüklendi (578 ms içinde).
  Geri yüklenecek projeler belirleniyor...
  C:\Users\forgind\Documents\GitHub\aspnetcore\eng\tools\GenerateFiles\GenerateFiles.csproj geri yüklendi (144 ms içinde).
  GenerateFiles -> C:\Users\forgind\Documents\GitHub\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.props
  GenerateFiles -> C:\Users\forgind\Documents\GitHub\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.targets
Attempting to install dotnet from public location.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
...
```

There were also clearly some encoding errors, though that might have just been the terminal. I should try changing the console code page to see if that helps there.

### Expected Behavior

Various messages printed out in Turkish.

### Steps To Reproduce

Run .\restore.cmd from the root of the aspnetcore repo on a Turkish OS.

### .NET Version

SDK not installed, but VS 17.0.5 (Community)

### Anything else?

I would guess this isn't just an asp.net core issue, but restore.cmd is probably one piece of the problem, alongside perhaps the sdk or nuget.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
