### ISSUE TITLE
Installing aspnetcore-runtime-6.0.1-win-x64.exe fails to detect IIS on Windows Server 2019 and does not install ASPNetCoreModule.

### ISSUE THREAD

**Issue by devteam-itconsilium** [dotnet/aspnetcore#39988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Installing aspnetcore-runtime-6.0.1-win-x64.exe fails to detect IIS on Windows Server 2019 and does not install ASPNetCoreModule.

### Expected Behavior

Asp.net Core module is not listed in IIS  module list    IIS Version 10.0.17763.1

 %Program Files%\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll missing

### Steps To Reproduce

Login as Server Administrator

Install aspnetcore-runtime-6.0.1-win-x64.exe  

version 6.0.1.21567

### .NET Version

6.0.101

**Comment by Tornhoof** [comment]
Aren't you supposed to install the hosting bundle? 
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
"On Windows, we recommend installing the Hosting Bundle, which includes the .NET Runtime and IIS support."

**Comment by devteam-itconsilium** [comment]
Oops!!
