### ISSUE TITLE
More stable response time on .NET 3.1 then .NET 6

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/aspnetcore#39981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading from .NET 3.1 to .NET 6 simple endpoint returning textual data from Database using EF Core takes more time and is unstable.

Calling endpoint on .NET Core 3.1 with postman multiple times get response time from 17ms to 25ms.
On .NET 6 it never gets below 19ms, but also it happens that random requests take 69ms, 80ms, and similar which does not happen on .NET Core 3.1.

### Expected Behavior

Expected performance improvements in .NET 6 instead of degradation.

### .NET Version

6.0.0

### Anything else?

dotnet --info

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### Additional context

Running on Linux Docker image on Kubernetes. Same hardware spec for both machines running the Container.

**Comment by rafikiassumani-msft** [comment]
@vasicvuk Can you provide a minimal repro app and the ways to test the observed perf degradation?

**Comment by vasicvuk** [comment]
@rafikiassumani-msft Seems that performance degradation is coming from PostgreSQL EF Core or .net 6 driver. I opened issue there and created repro, so I am closing this issue for now.

Thanks
