### ISSUE TITLE
ASP.NET Core Web App (MVC) generates controller with blocked namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39992]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNET-Core-Web-App-MVC-generates-con/1651325)._

---
[severity:It bothers me. A fix would be nice]
Rather small bug, but I find it weird that when you create an ASP.NET Core Web App using .net core 6 that the HomeController comes with a block-scoped namespace, but whenever you create a controller, the namespace is file-scoped, rather inconsistent.

To reproduce just create an MVC ASP.NET Core Web App and navigate to the Controllers/HomeController.cs file and view it.

---
#### Feedback Bot on 2/2/2022, 05:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
We own the scaffolded content. The change should be made in the dotnet/scaffolding repo. Here is an example: https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Controller/MvcController.cs

**Comment by mkArtakMSFT** [comment]
@vijayrkn do you know whether this was fixed already or not?

**Comment by vijayrkn** [comment]
block_scoped vs file_scoped can be controlled with the following editor config setting - https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#namespace-options 

Our approach is to use one form of the template and the editorconfig setting will help with the customization.
