### ISSUE TITLE
Blazor CascadingTypeParameter does not pass type parameter to children that have multiple type parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39994]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-CascadingTypeParameter-does-not-p/1649554)._

---
I have component TNCRGridColumn<TItem, TValue, TEdit> where explicitly passing TValue and TEdit type parameters but TItem does not passes through CascadingTypeParameter(nameof(TItem)) attribute declared in parent component TNCRDataGrid<TItem>

! [image.png] (https://aka.ms/dc/image?name=B117d2f0f655e4899aefb9e5f6db6eaf1637789406552343124_20220128-122414-image.png&tid=117d2f0f655e4899aefb9e5f6db6eaf1637789406552343124)

---
#### Feedback Bot on 1/27/2022, 10:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

This is a known limitation that we can't compensate for. We don't support "partial" generic type inference in the same way the C# compiler doesn't let you specify half of the generic type parameters for a type. You need to either specify all type parameters or none.

@guardrex can you add something to the docs to this effect?
