### ISSUE TITLE
Blazor Inconsistent Claim types between Token, Blazor and aspnet dotnet 6

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39991]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Inconsistent-Claim-types-between-/1652437)._

---
[severity:It's more difficult to complete my work]
Blazor wasm and aspnet core load the claims with different types for the same token.

i.e: for a B2C token that has the claim "**oid**", in Blazor the claims shows as "**oid**", but in aspnet core 6 it shows as "**http://schemas.microsoft.com/identity/claims/objectidentifier**"

This makes complicated to reuse a lot of the code between client and server libraries and also the code prone to errors.

Blazor Claims should be consistent with Server side Claims. Also Blazor server in sync, otherwise we would have Blazor server and wasm not loading the claims in the same way.

---
#### Feedback Bot on 2/2/2022, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
The long names are used by default for historical reasons. You can adjust that behavior as shown here:
https://github.com/dotnet/aspnetcore/issues/4660
