### ISSUE TITLE
Produce a System.Web.HttpContext adapter based on ASP.NET Core HTTP types

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40001]
This is part of our effort to allow migrating apps targeting .NET Fx / System.Web to .NET Core. We'd like to enable users targeting .NET Framework, and possibly .NET Standard class libraries, to target a library that shims System.Web.HttpContext and related types that are implemented using Microsoft.AspNetCore.Http types. Users could then cross-compile their libraries, referencing these types
and run their apps on .NET Core with minimal changes to existing code.

 This issue tracks

* [ ] Producing adapter for HttpContext and related types
    * [x] HttpContext (https://github.com/aspnet/AspLabs/pull/427)
    * [x] HttpRequest (https://github.com/aspnet/AspLabs/pull/435)
    * [x] HttpResponse (https://github.com/aspnet/AspLabs/pull/458)
    * [x] HttpContextBase
    * [x] HttpRequestBase
    * [x] HttpResponseBase
    * [x] HttpServerUtility
    * [x] Items (https://github.com/aspnet/AspLabs/pull/434)
    * [x] Cache (https://github.com/aspnet/AspLabs/pull/443)
    * [ ] HttpBrowserCapability
    * [x] Headers (https://github.com/aspnet/AspLabs/pull/437)
    * [x] Cookies (https://github.com/aspnet/AspLabs/pull/467)
    * [ ] Parameters
    * [x] Form (https://github.com/aspnet/AspLabs/pull/451)
    * [x] Server Variables (https://github.com/aspnet/AspLabs/pull/444)
    * [x] Query (https://github.com/aspnet/AspLabs/pull/451)
* [ ] Producing adapters for filler APIs that are commonly used in .NET Framework apps and libraries e.g. MimeMapping, VirtualPathUtility etc
* [x] Producing a middleware that ensures synthesizes System.Web-like behavior in ASP.NET Core apps.
    * [x] Enable per-endpoint configuration (https://github.com/aspnet/AspLabs/pull/447)
    * [x] Buffer request stream (https://github.com/aspnet/AspLabs/pull/447)
* [ ] Adding tests to ensure the implementation is highly compatible.

**Comment by pranavkm** [comment]
FYI @twsouthwick

**Comment by nil4** [comment]
Something similar to https://github.com/dotnet/corefxlab/pull/2940 ?

**Comment by pranavkm** [comment]
@nil4 not particularly. That one is a ref-only assembly to make it possible to compile code that uses System.Web types. This would let you run the same code by shimming the implmentaiton.

**Comment by adityamandaleeka** [comment]
Moving this to Preview 3 tentatively since this is actively being worked on.
