### ISSUE TITLE
Is there a way to update the user's claims when using OpenID?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/aspnetcore#40011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a situation where I want to update some of the the claims of a user that was authenticated by Azure AD. In my case I have a [hierarchical multi-tenant](https://www.thereformedprogrammer.net/building-asp-net-core-and-ef-core-hierarchical-multi-tenant-apps/) where the key for the tenant is stored in the claims. When a tenant is moved the key needs to be updated on any logged-in users. 

While I could use the `IClaimsTransformation` approach that would reduce the performance of every HTTP request because  recalculating the key claim requires a database access. The best approach is have a common `DateTime` holding the last time a DataKey has been changed and have a DateTime "LastTimeClaimsWhereUpdated" claim in the user's claims - by compared these two `DateTime`s you can decide if the user's claims / identity cookie needs to be updated.

In the individual users account provider I have used the cookie's `OnValidatePrincipal` event and added a DateTime "LastTimeClaimsWhereUpdated" claim to the user's claims.

### Describe the solution you'd like

I'm hoping there is something I don't know about that would work with OpenId. 😄 Something like individual users account provider and its cookies `OnValidatePrincipal` event would be great, but let me know if there is anything else I could do.

If there isn't a feature already I doubt it's worth adding a new feature for my request.

### Additional context

I'm using ASP.NET Core 6

**Comment by JonPSmith** [comment]
Thanks @Tratcher,

That's great news, but I did try OnValidatePrincipal, but it didn't work so I must have set it up incorrectly. Here is part of my setup (using startup class but running under net6)

```c#
public void ConfigureServices(IServiceCollection services)
{
    var connectionString = _configuration.GetConnectionString("DefaultConnection");
    services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApp(_configuration.GetSection("AzureAd"));

    services.ConfigureApplicationCookie(options =>
    {
        options.Events.OnValidatePrincipal = CookieEventMethod.ValidateAsync; // static class - works with individual users account 
    });

    services.AddControllersWithViews();
    services.AddRazorPages()
         .AddMicrosoftIdentityUI();

    //... rest of setup left out
```

PS. I do use the OpenIdConnectEvent `OnTokenValidated` and that works.

**Comment by Tratcher** [comment]
ConfigureApplicationCookie is adjusting the wrong cookie instance, AddMicrosoftIdentityWebApp sets up a different one. I think you need this overload to configure it:
https://github.com/AzureAD/microsoft-identity-web/blob/18345c8c19d41c1ef41f93e8c6943e5dad6b2f96/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L116-L120

**Comment by JonPSmith** [comment]
Great, that fixed it (even if the setting up the AAD options is a bit messy). Here is my code now in case anyone what's to do this.

```c#
public void ConfigureServices(IServiceCollection services)
{
    var connectionString = _configuration.GetConnectionString("DefaultConnection");
    services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApp( identityOptions =>
        {
            var section  = _configuration.GetSection("AzureAd");
            identityOptions.Instance = section["Instance"];
            identityOptions.TenantId = section["TenantId"];
            identityOptions.ClientId = section["ClientId"];
            identityOptions.CallbackPath = section["CallbackPath"];
            identityOptions.ClientSecret = section["ClientSecret"];
        }, cookieOptions => 
            cookieOptions.Events.OnValidatePrincipal = CookieEventMethod.ValidateAsync);

    services.AddControllersWithViews();
    services.AddRazorPages()
         .AddMicrosoftIdentityUI();

    //... rest of setup left out
```

Thanks for that - it really helps and I will most likely create a article to show how to do this.
