### ISSUE TITLE
Network Access by default for Web applications

### ISSUE THREAD

**Issue by proinfocus** [dotnet/aspnetcore#40019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Web applications often need testing on multiple resolutions and making mobile friendly applications and testing them on physical mobile/tablet devices instantly will make design/development faster.

### Describe the solution you'd like

Solution is to enable and display the URL:port for network access on LAN when the application is running similar to the URL displayed for http and https for the running apps. This will allow developers to use their physical devices to test the web applications and APIs while also testing the design aspects of the application.

Note: We can do mobile resolution testing from browser, but doing from a physical device gives a real-time experience.

Eg: When the application is running, the user should be given the info about the network IP and Port to access from the LAN...
Local Access: https://localhost:7001
Network Access: https://192.168.1.100:7001

### Additional context

I see there is just one requirement while running the app, like adding the port to the firewall for inbound and outbound access.

**Comment by davidfowl** [comment]
What's the request here?

**Comment by proinfocus** [comment]
When a web app/api is run, it should be accessible by default from local area network and the URL:port for access should be displayed...

**Comment by davidfowl** [comment]
I think this should be a tooling change that is opt in via some launch setting (you can already set the URL there BTW). By default we bind to local host to avoid needing to configure any firewall settings that might require elevation on the OS.

**Comment by proinfocus** [comment]
Can this be made readily available as an element in the property group of the project file, which we can enable or disable quickly.

<EnableNetworkAccess>False</EnableNetworkAccess>

When enabled, it should display the IP and port for access...

VS it can be in tools, but for CLI it would be easy and quick...

**Comment by davidfowl** [comment]
`launchSettings.json` works for both the `dotnet run` and when launching form visual studio. You can change the addresses in there today and get this to work. ASP.NET Core applications print out the bound address by default to the console. Change the properties from localhost to * or 0.0.0.0 and it should bind to the machine ip.

**Comment by proinfocus** [comment]
David, I know it can be done by changing it in the `launchSettings.json` and then we need to get the PORT and add it to the Inbound firewall rules. If I have multiple projects to run for example, a web app and a web API, then these has to be repeated.

I was suggesting to make this default or just provide a flag in `.csproj` to turn network access ON or OFF and the tooling will do the manual steps and the developer can just start using it.

**Comment by davidfowl** [comment]
I don't see this being a part of the framework. This is a tooling feature.

cc @vijayrkn

**Comment by vijayrkn** [comment]
Thanks for looping me in. 

@proinfocus - Can you please port this issue as a Visual Studio Suggestion? This allows the right teams to pick it up, triage on the Visual Studio side and provide updated status on the suggestion. 

This link has the details - https://review.docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022&branch=main

**Comment by proinfocus** [comment]
Thanks David/Vijay for support/guidance. I have suggested this as a feature request using the Visual Studio 2022. I am sure the relevant team will do the needful.
