### ISSUE TITLE
Missing dispose in security area

### ISSUE THREAD

**Issue by ylabade** [dotnet/aspnetcore#40017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I notice some missing `dispose` in the security area like for the request and the response here:
https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Security/Authentication/Google/src/GoogleHandler.cs#L37-L40
https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Security/Authentication/Facebook/src/FacebookHandler.cs#L44
Is there a particular reason or is it just an oversight?

### .NET Version

6.0.100

### Anything else?

CA2000 (Dispose objects before losing scope) can help to find those lacks

**Comment by Tratcher** [comment]
It's not necessary. HttpRequest/ResponseMessage.Dispose only dispose their HttpContent. The request doesn't have any content, and the response is fully buffered so disposing it doesn't do anything. We could add `using var` to these if we wanted to enable CA2000, but it wouldn't change the behavior.
