### ISSUE TITLE
Crash on "Register" and "Log In"

### ISSUE THREAD

**Issue by LeoRis** [dotnet/aspnetcore#40024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys.
I am using VS19, .NET Framework 4.7.2. When building my app, and click on "Register" or "Log In", the app crashes and it takes me directly at Register.cshtml or Login.cshtml at this section of the source code:

```
@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })  // This is where I get the:  
                                                                System.NullReferenceException: 'Object reference 
                                                                not set to an instance of an object.'
        </div>
    </div>
```
```
@using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Use a local account to log in.</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })  // This is where I get the:  
                                                                  System.NullReferenceException: 'Object reference 
                                                                  not set to an instance of an object.'
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
```

I've read a couple of reported issues here, and one of them mentioned that this issue is fixed in the latest Visual Studio 2022.
But how do we work around this issue at VS19? Do you have any suggestions or advise on how to bypass it?

Many thanks in advance :)

### .NET Version

4.7.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please clarify whether the crash is in the app (at runtime) or is it the Visual Studio that crashes ?

**Comment by LeoRis** [comment]
Yes - the crash occurs in the app, once I click on "Register" or "Login". Once one of those two is clicked, the program takes me back in VS at the abovementioned code and it points out the "NullRefEx".

**Comment by adityamandaleeka** [comment]
@LeoRis can you share more info about your app and what framework you're targeting?

**Comment by LeoRis** [comment]
Hi @adityamandaleeka . It's an ASP.NET MVC app, target framework is .NET Framework 4.7.2
What else can I provide to be out of use?

**Comment by adityamandaleeka** [comment]
@LeoRis Can you put a repro of this on a GitHub repo and share it here?

**Comment by LeoRis** [comment]
Hi @adityamandaleeka . Here is my repo: https://github.com/LeoRis/ASP.NET_MVC_Vidly
Please do not hesitate to contact be if you need further info. I am really curious to find out what seems to be the problem, as I tried creating another project, and the problem still persists. Thank you.

**Comment by adityamandaleeka** [comment]
@LeoRis I tried your repro and it looks like there's no crash. What you're seeing are [first-chance exceptions](https://devblogs.microsoft.com/devops/understanding-exceptions-while-debugging-with-visual-studio/). You'll notice that if you continue execution when you see them, they are handled and everything continues to work normally.

FWIW, you can configure your debugger not to stop on these exceptions.
