### ISSUE TITLE
Blazor WASM: Possible to pass pointer to JavaScript?

### ISSUE THREAD

**Issue by jahnotto** [dotnet/aspnetcore#40027]
I am passing large byte arrays to JavaScript using IJSInProcessObjectReference. However, because of memory and garbage collector issues  (#64047), I am trying to handle memory allocation and deallocation myself with Marshal.AllocHGlobal.

Is it possible to pass an IntPtr or any other type of pointer (ushort*, byte*, void*) to JavaScript? If I pass it as an IntPtr, it seems like I'm simply getting an integer on the JavaScript side.

**Comment by javiercn** [comment]
@jahnotto thanks for contacting us.

I would point out a few things. I imagine you are doing unmarshalled interop using the mono bindings APIs. In general, I would stay away from this type of interop as its not guaranteed to be stable and might break in the future.

Pointers are represented as number instances on the JavaScript side. You need to go through the mono APIs to do things like access object members and so on. If you are looking to do something like `pointer.Field` in JavaScript, that's not something I believe is possible.
