### ISSUE TITLE
ConfirmEmail.cshtml returnUrl not working

### ISSUE THREAD

**Issue by MSIH** [dotnet/aspnetcore#40032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ConfirmEmail.cshtm does not use the returnUrl paramter in the confirmation URL.

Register.cshtml.cs sends an email to confirm the user. The email contains a confirmation link to ConfirmEmail.cshtml. The confirmation link includes three parameters: ```userId,  code, returnUrl```

https://FQDN/Identity/Account/ConfirmEmail?userId=12345678-f866-43dd-bbb8-710616122ce2&code=12345678ZFhkV3hmUTVoS3ZqbUhRYXhkQ0lXM0ZYd3BoVWhvKzJYNFZwck5CUUdzVXFWMFlOY2RpTE8vK1pnd25mNkVsQXlobnVteW95UlovMWtSdjBHQzFoTWFpSkdoSFg0OHlTVGhLVXVjMlVib0ZOMXg1bVdzeEZaOFpyWSs1TW5veWw3S21maGNLU1ZrSDRCeEFBaUpWYTdrNWNrcm5VWkRGOGtTQzJMWlJUK1VablhDdDVheGdmMjNtMzJZeVVaTjV0VEZmVCtENWQwdzhia0taNTd2MHRvWTZZMEYwak5wcGZveVZGdFRwSy9ReHJBSTR2YTVLVmVnZmFaMVZ3bi93dz09&returnUrl=%2FProfile

```
var callbackUrl = Url.Page(
 "/Account/ConfirmEmail", pageHandler: null,
 values: new { area = "Identity", userId = user.Id, code = code, returnUrl = returnUrl },
  protocol: Request.Scheme);

 await _emailSender.SendEmailAsync(Input.Email,  "Confirm your email",
  $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
```

ConfirmEmail.cshtm.cs OnGetAsync signature only is using two parameters:
```
public async Task<IActionResult> OnGetAsync(string userId, string code)
```

So the returnUrl is never processed.

### Expected Behavior

After users email ti confirmed should be redirected to the return URL.

### .NET Version

6.0.101

**Comment by adityamandaleeka** [comment]
@blowdart @HaoK

**Comment by blowdart** [comment]
This is a very specific design decision. Confirming an email is not performaing a login, a click of a link isn't authentication, so even after confirming emails we go to login on purpose. 

We don't see this as something that needs fixed.

**Comment by MSIH** [comment]
I disagree this is not a bug. Either 

1. the Confirmation Email URL should not include the returnUrl parameter, because the ConfirmEmail.cshtm.cs OnGetAsync is not using it

or
 
2.  the Confirmation Email URL should contain the returnUrl parameter, because the ConfirmEmail.cshtm.cs OnGetAsync is using it

Please do the right thing an remove the returnUrl parameter from the Confirmation Email. Thanks
