### ISSUE TITLE
WebApplication.New().ServerFeatures is null 

### ISSUE THREAD

**Issue by NGloreous** [dotnet/aspnetcore#40042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using minimal APIs in ASP.NET Core 6, after creating a new application from the existing app, the ServerFeatures property of the new application is null. 

Per @Tratcher, this is because the ServerFeatures are never put in the property bag of the application: https://github.com/dotnet/aspnetcore/blob/d1c349f29752ac0718bda7b809ab7fd4f82ca414/src/DefaultBuilder/src/WebApplication.cs#L70-L71.

### Expected Behavior

ServerFeatures shouldn't be null.

### Steps To Reproduce

```c#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
var newApp = (app as IApplicationBuilder).New();
Debug.Assert(newApp.ServerFeatures != null);
```

### .NET Version

6.0.100

**Comment by Tratcher** [comment]
@halter73

**Comment by skyflyer** [comment]
We've encountered this same issue when trying to conditionally use HTTPS redirection middleware like:

```cs
app.UseWhen(
    (ctx) => !ctx.Request.Path.StartsWithSegments("/health"),
    (appBuilder) => {
        appBuilder.UseHsts();
        appBuilder.UseHttpsRedirection();
    }
);
```

The workaround for us is to simply use `appBuilder.UseMiddleware<HttpsRedirectionMiddleware>();` instead.

**Comment by campersau** [comment]
A general workaround is:
```c#
((IApplicationBuilder)app).Properties["server.Features"] = ((IApplicationBuilder)app).ServerFeatures;
```
