### ISSUE TITLE
Razor parser confused by using reserved keywords as identifiers

### ISSUE THREAD

**Issue by JakubJanowski** [dotnet/aspnetcore#40049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Identifiers can be prefixed with @ to use a reserved keyword as a name. This creates a problem when the identifier with the @ prefix is itself a keyword.

Having declared a class like this:
```C#
class @using {}
```

and writing in CSHTML file the following, it does not compile.
```Razor
@{
    @using b = new @using();
}
```

This however does compile for some reason.
```Razor
@{
    var a = new @using();
    @using b = new @using();
}
```

The errors that I'm getting when it's not compiling are:
- error CS1041: Identifier expected; 'new' is a keyword,
- error CS0116: A namespace cannot directly contain members such as fields, methods or statements,
- error CS1022: Type or namespace definition, or end-of-file expected,
- error CS1525: Invalid expression term ')'.
Which suggests that it is recognising the `@using` as a directive for importing namespaces.

I'm noticing similar behavior with  `@addRazorTag`, `@if`, `@model`, etc. The workaround is simple and obvious (don't use reserved keywords as identifiers) so it doesn't bother me much. Just wanted to document this here as it defeats the purpose of having such a feature in the first place.

### Expected Behavior

Both code samples should compile and recognize `b` to be an instance of the `@using` class.

### Steps To Reproduce

1. In an ASP.NET Core Web App project create new Razor page file with the below contents:

```Razor
@page
@{
    @functions {
        class @using {}
    }
    //var a = new @using();
    @using b = new @using();
}
```

2. Uncomment the line to see it compile.

### .NET Version

6.0.101

**Comment by pranavkm** [comment]
`@` is special in Razor. You'll need to use `@@` in most places where you need to escape it: https://docs.microsoft.com//aspnet/core/mvc/views/razor?#razor-syntax

**Comment by JakubJanowski** [comment]
I thought `@@` can be used to escape HTML only, so I've learned something new today. Still it's surprising to see that adding apparently unrelated line of code, the compiler's behavior changes.
Thanks
