### ISSUE TITLE
Blazor InputText FormatValueAsString behaves in a strange way

### ISSUE THREAD

**Issue by samihuutoniemi** [dotnet/aspnetcore#40058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To add events and formatters to the InputText component of Blazor, I have created an inherited component, InputText2.
It looks like in the attached screenshot.

The Formatter parameter takes a Func that modifies the string in some way. In my example, I wanted postal codes in the format "12345" to be formatted "123 45". In FormatValueAsString, result gets the correct value, but this is not reflected in the UI after rendering. However, if I do set CurrentValueAsString to result, then it works. But I can't find any reason for this. And in other examples, that property is never touched either. Also, setting CurrentValueAsString seems to create loops between FormatValueAsString and TryParseValueFromString.

Am I doing this wrong?

### Expected Behavior

The Input in the UI should have the value returned from FormatValueAsString

### Steps To Reproduce

https://github.com/samihuutoniemi/InputTextIssue

### .NET Version

6.0.200-preview.22055.15

### Anything else?

![image](https://user-images.githubusercontent.com/2758838/152949821-5d9a387b-c766-471d-9d0a-bba351b398a3.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to be related to https://github.com/dotnet/aspnetcore/issues/40097.
