### ISSUE TITLE
Disable BlazorTemplates.Tests from running in quarantined pipelines

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#40051]
These tests were disabled in the helix environment via https://github.com/dotnet/aspnetcore/pull/38814/files#diff-0ccc4599c1cd44580f93ef1ab4182e747b297872577a970d651be18220d91768R13. This issue tracks disabling the tests from the quarantined pipelines as well until we're able to make some improvements to the underlying test suite. 

Related: https://github.com/dotnet/aspnetcore/issues/38818

**Comment by dougbu** [comment]
Why disable the tests running in the quarantined pipeline while the tests are all quarantined❔ Or, are you suggesting a quick fix of moving from quarantined to skipped❔
