### ISSUE TITLE
Mark more blobs as non-shipping

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#40050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As discussed in dotnet/core-eng#15249, aspnetcore-targeting-pack-6.0.2.tar.gz, aspnetcore-targeting-pack-6.0.2.tar.gz.sha512, aspnetcore-targeting-pack-6.0.2.zip, and aspnetcore-targeting-pack-6.0.2.zip.sha512 might not ship (I'm not positive about all of them) and should be marked w/ `NonShipping="true"` in our asset manifests.

The `aspnetcore-runtime-internal-*` should all be marked w/ `NonShipping="true"`.

### Expected Behavior

Our asset manifests should match what actually does or doesn't ship.

**Comment by dougbu** [comment]
Thoughts @wtgodbe❔

**Comment by wtgodbe** [comment]
My understanding for blobs is that the `shipping`/`nonshipping` markers only affect versioning, since they all wind up on the same blob feed anyways. I think that means it's right to keep all `aspnetcore-targeting-pack-` blobs marked as `shipping`, except maybe the `.sha512` file. @dotnet/dnceng is that an accurate assessment?

**Comment by adiaaida** [comment]
@mmitche I’m not actually sure on the answer to this. Do you know?

**Comment by mmitche** [comment]
Yeah the switch is primarily about versioning. It will not affect the SBOM. Eventually all artifacts, whether they go to customers or not, will have an SBOM.

I don't think much is to be gained by reclassifying the outputs.

**Comment by dougbu** [comment]
I think we should at least align our manifest creation w/ versioning. `aspnetcore-runtime-internal-*` packages don't and won't have stable versions but the blobs are marked as shipping for some reason.

**Comment by dougbu** [comment]
Separately, we _might_ have another (perhaps slight) issue in our asset manifest files: The files do not list the Microsoft.Web.Xdt.Extensions.pdb file, likely because it's placed into the formerly-special artifacts/symbols/ folder and otherwise ignored. Does this mean the file is no longer published even though the corresponding assembly ships in the following❔

- Microsoft.AspNetCore.AzureAppServices.SiteExtension.7.0.0-preview-3-22117-6.nupkg (this one will be marked as shipping once we leave previews)
- Microsoft.AspNetCore.AzureAppServices.SiteExtension.7.0.x64.7.0.0-preview-3-22117-6.nupkg
- Microsoft.AspNetCore.AzureAppServices.SiteExtension.7.0.x86.7.0.0-preview-3-22117-6.nupkg

**Comment by dougbu** [comment]
If the [above](https://github.com/dotnet/aspnetcore/issues/40050#issuecomment-1048170110) is a problem, probably worth mixing into this issue.

**Comment by wtgodbe** [comment]
@dotnet/dnceng is there an easy way for us to tell if `Microsoft.Web.Xdt.Extensions.pdb` is getting published to the symbol server? It's from an assembly that doesn't have its own package, and ships only in `Microsoft.AspNetCore.AzureAppServices.SiteExtension.7.0.0-preview-3-22117-6.nupkg`

**Comment by ulisesh** [comment]
I don't think we have a way to do this. @garath recommended to use [SymChk](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-symchk) but I'm not sure if it is enough for your scenario

**Comment by mmitche** [comment]
- You might also check the binlog from the publishing tasks associated with a build. I think it will show the files uploaded to the symbol server.
- You could also use `dotnet-symbol` to do it. I think you can pass it the assembly anhd 

My guess is that it's not being published though, since I think we only publish items in .symbols.nupkgs as well as explicit PDBArtifacts.

**Comment by wtgodbe** [comment]
I see these in the binlog of a promotion build

> Uploading missing Blob:7a6ad65fb3b21307bec76e09057c3e209246645da792e3b11e2a8931149dd06900 file D:\a\_work\1\a/PDBArtifacts/Release\net462\Microsoft.Web.Xdt.Extensions.pdb index microsoft.web.xdt.extensions.pdb/e49c12bae0f44aeb88ab3984e3d5305fFFFFFFFF/microsoft.web.xdt.extensions.pdb uri https://microsoftpublicsymbols.vsblob.visualstudio.com/

> Uploading missing Blob:7a6ad65fb3b21307bec76e09057c3e209246645da792e3b11e2a8931149dd06900 file D:\a\_work\1\a/PDBArtifacts/Release\net462\Microsoft.Web.Xdt.Extensions.pdb index microsoft.web.xdt.extensions.pdb/e49c12bae0f44aeb88ab3984e3d5305fFFFFFFFF/microsoft.web.xdt.extensions.pdb uri https://microsoftpublicsymbols.vsblob.visualstudio.com/

Which suggests the .pdb is getting sent to the symbol server. So I think we just need to get it added to the asset manifest - though I'm surprised it wouldn't already be there if it's getting published

**Comment by dougbu** [comment]
We're actually probably fine on `Microsoft.Web.Xdt.Extensions.pdb` if Arcade publishes all symbol files in `PdbArtifacts` -- even if they're not listed in the MergedManifest.xml file. Agree not requiring an entry in the MergedManifest.xml file is a bit of a surprise.
![image](https://user-images.githubusercontent.com/6431421/155375955-1635c7f2-1b3b-44aa-aa56-90d695db6eb6.png)

**Comment by riarenas** [comment]
PDBArtifacts is a bit special. We try and upload everything in there because there are some repos that need individual dlls that aren't in a symbol package to be indexed in the symbol servers. We don't necessarily want those stray dlls to show up in the manifest when they are contained in other nupkgs that are already there.

**Comment by wtgodbe** [comment]
@riarenas this .pdb is a bit "special" - it's not in any package, but it does go to the symbol server. Should we be including it in the manifest? Right now it's not there

**Comment by riarenas** [comment]
I think it would make things clearer in the future to avoid this confusion you went through, but if it's not in any package, won't be used during releases, it's not used during dependency flow, and it's getting published to the symbol servers correctly, I don't see it as a strict requirement.
