### ISSUE TITLE
Naming convection confusion 

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/aspnetcore#40057]
Sorry for choosing the wrong category, I had no idea where to ask this question.

Hence .NET developers consider ASP.NET source code as best practice for many thing things like naming convention, I'm wondering what is the naming convention for protected fields?
For example, in [ActionEndpointDataSourceBase](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.cs#L19) class, some protected fields' names start with `_` and some start with a capital letter (PascalCasing).
![image](https://user-images.githubusercontent.com/1659032/152949849-6f0f0894-59f2-4d04-80d1-14404ff85455.png)

According to [Names of Fields](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields) convention for public static and protected fields, it should be PascalCasing.

**Comment by javiercn** [comment]
@mo-esmp thanks for contacting us.

We don't really offer guidance on these topics. We normally use `_` to identify fields members of the class, and we don't really have a strict rule about it, at the very least with respect to fields, specially when they are part of internal classes, though the `convention` is to `_` if you want.

For public types, we rarely (if ever) expose a field directly; normally those things are exposed via a property. 

Hope that helps.

**Comment by mo-esmp** [comment]
@javiercn thanks for the reply.

Microsoft documentation mentioned that protected fields names should be PsacalCase. It's kind of confusing for people like me that documentation is offering something and codes written by Microsoft offer something else.
