### ISSUE TITLE
Possible incorrect sorting in KnownHeaders.cs

### ISSUE THREAD

**Issue by VasilievSerg** [dotnet/aspnetcore#40062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

Looks like there are some incorrect sorting operations in [KnownHeader.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/shared/KnownHeaders.cs).

Perhaps, there should be the `.OrderBy(...).ThenBy(...)` invocation sequence instead of `.OrderBy(...).OrderBy(...)`.

[The first case](https://github.com/dotnet/aspnetcore/blob/3b8ce2746c6835690a4e1b9c97e3a9ea43844909/src/Servers/Kestrel/shared/KnownHeaders.cs#L147):
```
....
.Concat(corsRequestHeaders)
.OrderBy(header => header)
.OrderBy(header => !requestPrimaryHeaders.Contains(header))
.Select((header, index) => new KnownHeader
....
```

[The second case](https://github.com/dotnet/aspnetcore/blob/3b8ce2746c6835690a4e1b9c97e3a9ea43844909/src/Servers/Kestrel/shared/KnownHeaders.cs#L216):
```
....
.Concat(corsResponseHeaders)
.OrderBy(header => header)
.OrderBy(header => !responsePrimaryHeaders.Contains(header))
.Select((header, index) => new KnownHeader
....
```

[The third case](https://github.com/dotnet/aspnetcore/blob/3b8ce2746c6835690a4e1b9c97e3a9ea43844909/src/Servers/Kestrel/shared/KnownHeaders.cs#L241):
```
....
.OrderBy(header => header)
.OrderBy(header => !responsePrimaryHeaders.Contains(header))
.Select((header, index) => new KnownHeader
....
```

**Comment by rafikiassumani-msft** [comment]
@VasilievSerg Can you provide an example of where this is generating an incorrect order? We can't think of any example that would produce an incorrect order at the moment.

**Comment by VasilievSerg** [comment]
@rafikiassumani-msft unfortunately, I don't have the information about how the code affects the sorting order. :(

I found these issues while inspecting the code. Re-calling `OrderBy` after `OrderBy` resets the previous sorting result. However, I don't know how exactly this manifests in this case - I haven't investigated this question yet.

**Comment by adityamandaleeka** [comment]
There isn't a bug here; `OrderBy` does a stable sort and the second `OrderBy` in these cases just checks for presence in a set, so we always end up with the same result (specifically, one where the headers are in order and the primary ones come first).

I suppose it would be _slightly_ cleaner for us to first sort on set presence, then use `ThenBy` to sort by header which would accomplish the same thing.

**Comment by adityamandaleeka** [comment]
Closed with https://github.com/dotnet/aspnetcore/pull/40410
