### ISSUE TITLE
.NET CORE6 + ReactJS Template 

### ISSUE THREAD

**Issue by 1988gadocansey** [dotnet/aspnetcore#40064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After creating asp.net core(6) with reactjs project using the rider(jetbrains) template. I cannot call controllers actions from REACTJS using axios. It always returns 404.

<img width="706" alt="Screen Shot 2022-02-08 at 1 05 18 PM" src="https://user-images.githubusercontent.com/7513799/152992757-0b648ddd-3153-48a7-9908-6516ee58c840.png">
<img width="973" alt="Screen Shot 2022-02-08 at 1 05 35 PM" src="https://user-images.githubusercontent.com/7513799/152992789-416e9d5d-fbf6-4b5c-886f-0d85ff909d40.png">
<img width="579" alt="Screen Shot 2022-02-08 at 1 05 52 PM" src="https://user-images.githubusercontent.com/7513799/152992841-597fe298-ad27-4269-90ba-4390e640a1e8.png">

<img width="1070" alt="Screen Shot 2022-02-08 at 1 08 15 PM" src="https://user-images.githubusercontent.com/7513799/152993232-7fa49669-ccb6-40a2-9eb3-f10862623c31.png">

### .NET Version

6

**Comment by javiercn** [comment]
@1988gadocansey thanks for contacting us.

Are you able to access the endpoint directly through the browser?

**Comment by 1988gadocansey** [comment]
I can't access Controller endpoint from browser except the reactjs routes
.. There's a setupproxy in the react Src..  I actually don't know how to
configure the controler endpoints to that proxy

**Comment by javiercn** [comment]
@1988gadocansey It's not clear what's going on, but it seems its something that has to do with how your application is configured. 

In order for us to be able to assist here, we would need you to create a minimal repro project as a public github repository.

**Comment by 1988gadocansey** [comment]
Issue resolved.

**Comment by vanillajonathan** [comment]
@1988gadocansey How did you resolve the issue?

**Comment by 1988gadocansey** [comment]
The issue is with the react app( setupproxy.js) when you run npm start in the ClientApp, the proxies are created but if i use Rider IDE run proxies don't usually work. The proxy is really making it difficult to call endpoints from the controllers.

**Comment by 1988gadocansey** [comment]
> The issue is with the react app( setupproxy.js) when you run npm start in the ClientApp, the proxies are created but if i use Rider IDE run proxies don't usually work. The proxy is really making it difficult to call endpoints from the controllers.



> @1988gadocansey How did you resolve the issue?
