### ISSUE TITLE
Sending byte array with SignalR NewtonsoftJsonProtocol

### ISSUE THREAD

**Issue by Roy19** [dotnet/aspnetcore#40069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During SignalR streaming, I know that the stream data can be of various data types. Suppose I try to send some byte array using NewtonsoftJsonProtocol. I know that I should be encoding the data first into Base64 or some other format and then be sending the data but the channel writer does not prevent me from sending a byte array. If I send the data I should be receiving the data back in the correct format as well in the client. But it seems that is not the case. I get data back in a manner that seems to be absurd. The data seems to be repeating again, or be missing some values. This however is not the case when I convert it to a Base64 string and stream the data. With that said, how is data encoding being handled by the underlying SignalR protocols?

### Expected Behavior

Data should be sent and received correctly regardless of the underlying type.

### Steps To Reproduce

Create a server to client downstream channel. Try to read the contents of a file in a byte array and write the byte array to the channel writer.

### .NET Version

6.0.101

### Anything else?

ASP.NET Core version: 6.0

**Comment by BrennanConroy** [comment]
> I get data back in a manner that seems to be absurd. The data seems to be repeating again, or be missing some values.

If I had to guess, you're re-using a buffer when reading from the file so there is a race between you getting more data from the file and SignalR writing the given buffer to the wire.

I recommend trying streaming with [`IAsyncEnumerable<T>`](https://docs.microsoft.com/aspnet/core/signalr/streaming?view=aspnetcore-6.0#server-to-client-streaming) as that's a pull based model and should avoid issues with you reusing the buffer before it's been consumed by SignalR.

**Comment by Roy19** [comment]
Here's a sample app with a SignalR server and an Angular client that might be of use: https://github.com/Roy19/TestServerClient

**Comment by halter73** [comment]
Does it work if you change the following?

```C#
                    byte[] b = new byte[chunkLength];
                    while (fs.Read(b, 0, b.Length) > 0)
                    {
```

```C#
                    while (fs.Read(b, 0, b.Length) > 0)
                    {
                        byte[] b = new byte[chunkLength];
```

**Comment by Roy19** [comment]
Right this works. My mistake. The buffer was getting rewritten to, but the string was new.

**Comment by Roy19** [comment]
Just a query. So does `await writer.WriterAsync(b, cancellationToken)` not wait to write data directly to the SignalR wire?

**Comment by davidfowl** [comment]
No it does not. SIgnalR has to enumerate the IAsyncEnumerable and copy those bytes into the output stream with more surrounding framing (the protocol itself).

**Comment by Roy19** [comment]
Thanks. That provides some explanation.
