### ISSUE TITLE
[Migration] Figure out a story for sharing session state with ASP.NET apps

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40079]
As part of https://github.com/dotnet/aspnetcore/issues/40078, we want to figure out if there is a way to allow a frontend ASP.NET Core app and a backend System.Web based app to share session state. 

* [ ] Can we support one of the existing session state providers such as SQL Server state provider?
* [ ] Could we build a state state provider using IDistributedCache? Is that sufficient for large apps?
* [ ] Are there framework components such as MVC's TempDataProvider that need to be investigated for compatibility?

**Comment by adityamandaleeka** [comment]
Closing since this is addressed with the session sharing features in https://github.com/dotnet/systemweb-adapters
