### ISSUE TITLE
.NET Core RedirectToAction method fails when passing param

### ISSUE THREAD

**Issue by davidremus** [dotnet/aspnetcore#40075]
Hello,

I tried to pass QueryParam named 'action' using the RedirectToAction method in the following way:
```
public IActionResult Index()
{
     return RedirectToAction(nameof(DoIt), new { action = "action" });
}
public IActionResult DoIt([FromQuery] string action)
{
     return Json(action);
}
```

I saw that the action property name is ignored. If I use 'actionx' or 'action1' it works.

The only way I was able to use was with the Redirect method and manually building the URL.

Is this a bug, or a feature?

**Comment by pranavkm** [comment]
`action` is a [special keyword in MVC](https://github.com/dotnet/aspnetcore/wiki/MVC-Reserved-Keywords). It's meant to denote the controller action to route to. Using a different name would be the right way to go. See also https://docs.microsoft.com/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0#reserved-routing-names

**Comment by davidremus** [comment]
> `action` is a [special keyword in MVC](https://github.com/dotnet/aspnetcore/wiki/MVC-Reserved-Keywords). It's meant to denote the controller action to route to. Using a different name would be the right way to go. See also https://docs.microsoft.com/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0#reserved-routing-names

Thank you, unfortunately I missed this link!
