### ISSUE TITLE
Session values not maintained between HttpClient call and normal XHR requests

### ISSUE THREAD

**Issue by PremKumarMadhanRaj** [dotnet/aspnetcore#40089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding a session value while calling a web API method using HttpClient and trying to call another web API method in the same controller with Xhr request, the session value is returned as null or not available. Please check the below code snippet

**Controller**
```C#
[Route("Test1")]
    public void Test1(string args)
    {
        HttpContext.Session.SetString("key", "value");
    }
    [Route("Test2")]
    public void Test2(string args)
    {
        string value = HttpContext.Session.GetString("key"); // value becomes null here 
    }
```

**Index** 

```cshtml
@inject IJSRuntime JS

<button @onclick="HttpClientCall">Read</button>
<button @onclick="XhrCall">Client Call1</button>

@code {
    static HttpClientHandler handler = new HttpClientHandler { UseCookies = true };
    HttpClient HttpClient = new HttpClient(handler);

    async Task HttpClientCall()
    {
        await HttpClient.PostAsync("https://localhost:44301/api/Test/Test1", null);
    }
    
    async Task XhrCall()
    {
        await JS.InvokeVoidAsync("createXhr");
    }
}
```

script

```html
<script>
        window.createXhr = () => {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () { };
            xhr.open('GET', 'https://localhost:44301/api/Test/Test2');
            xhr.send()
        };
    </script>
```

### Expected Behavior

I need to get the session values within the controller properly

### Steps To Reproduce

1 . Run the attachment sample
2. Click the Read button (uses httpClient call for web API call)
3. On the controller method we have set a value to the session
4. Now click the ClientCall 1 button
5. On the controller method, we can't get the session value

### .NET Version

5.0

**Comment by PremKumarMadhanRaj** [comment]
[Issue_Sample.zip](https://github.com/dotnet/aspnetcore/files/8030035/Issue_Sample.zip)

**Comment by Tratcher** [comment]
@mkArtakMSFT Isn't this the Blazor HttpClient?

**Comment by PremKumarMadhanRaj** [comment]
@Tratcher yes this is Blazor HttpClient only.

**Comment by javiercn** [comment]
@PremKumarMadhanRaj If you check the request on the server is likely that the cookie is not coming through.

You need to set the request credentials mode see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions.setbrowserrequestcredentials?view=aspnetcore-6.0#microsoft-aspnetcore-components-webassembly-http-webassemblyhttprequestmessageextensions-setbrowserrequestcredentials(system-net-http-httprequestmessage-microsoft-aspnetcore-components-webassembly-http-browserrequestcredentials)) for details
