### ISSUE TITLE
RequestDecompression middleware

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#40080]
The same way we have a `ResponseCompression` middleware we should have a `RequestDecompression` one that automatically decompress the requests containing `Content-Encoding` with supported formats (gzip, deflate, brotli, ...). Based on the same extensible compression factories.

Scenario: a client sends files to a server using gzip compressed streams. The developer of the server application doesn't have to care about how to decrompress the body.

**Comment by Tratcher** [comment]
Prior ask: https://github.com/dotnet/aspnetcore/issues/30544

**Comment by david-acker** [comment]
I'd be interested in helping out with this. This should follow the same pattern that the `ResponseCompression` middleware uses, correct? (i.e., an `IDecompressionProvider` interface that's implemented by the `-DecompressionProvider` classes for each of the supported formats)

**Comment by sebastienros** [comment]
@david-acker I think it should do the same thing, yes. Go for it! Since nobody would do it for now. I would use it then instead of doing it my controllers: https://github.com/dotnet/crank/blob/main/src/Microsoft.Crank.Agent/Controllers/JobsController.cs#L389

**Comment by alexanderkozlenko** [comment]
I would be glad to offer my help as well if needed: I've been using my own middleware implementation for a few years:

- GitHub: https://github.com/alexanderkozlenko/aspnetcore-request-decompression
- NuGet: https://www.nuget.org/packages/Anemonis.AspNetCore.RequestDecompression

**Comment by david-acker** [comment]
@sebastienros From a practical perspective, does it make sense to support decompressing requests that have multiple Content-Encodings applied (e.g. compressed with Brotli and then GZip)? I'd be happy to add this if you think it's worthwhile, but I just wanted to confirm first.

I'll put a draft PR with the working implementation soon so I can get some feedback.

**Comment by david-acker** [comment]
That was my thought as well. I saw this mentioned in RFC 2616 and a few other places online (not with any examples of actual implementations though), so I figured I ask just to be sure.

**Comment by pranavkm** [comment]
API Review:

```diff
namespace Microsoft.AspNetCore.Http.Metadata;
+ public interface IRequestSizeLimitMetadata
+ {
+     public long MaxRequestBodySize { get; }
+ }

+ namespace Microsoft.AspNetCore.RequestDecompression;
+ public interface IDecompressionProvider
+ {
+     Stream GetDecompressionStream(Stream stream);
+ }

+ public interface IRequestDecompressionProvider
+ {
+     IDecompressionProvider? GetDecompressionProvider(HttpContext context);
+ }

+ public sealed class RequestDecompressionMiddleware
+ {
+     public RequestDecompressionMiddleware(RequestDelegate next, IRequestDecompressionProvider provider);
+     public Task Invoke(HttpContext context);
+ }

+ public sealed class RequestDecompressionOptions
+ {
+     public IDictionary<string, IDecompressionProvider> DecompressionProviders { get; }
+ }
 
namespace Microsoft.AspNetCore.Builder;

+ public static class RequestDecompressionBuilderExtensions
+ {
+     public static IApplicationBuilder UseRequestDecompression(this IApplicationBuilder builder);
+ }

namespace Microsoft.Extensions.DependencyInjection;

+ public static class RequestDecompressionServiceExtensions
+ {
+     public static IServiceCollection AddRequestDecompression(this IServiceCollection services);
+     public static IServiceCollection AddRequestDecompression(this IServiceCollection services, Action<RequestDecompressionOptions> configureOptions);
+ }
```

**Comment by pranavkm** [comment]
API review:

Approved. Update the `IRequestDecompressionProvider` to return the Stream instead of the provider:

```diff
+ public interface IRequestDecompressionProvider
+ {
+     Stream? GetDecompressionStream(HttpContext context);
+ }
```

**Comment by halter73** [comment]
We should also support the `DisableRequestSizeLimitAttribute` if we're going to support `RequestSizeLimitAttribute`. This requires updating `IRequestSizeLimitMetadata.MaxRequestBodySize` to be nullable. Here are my proposed updates to the already-approved API:

```diff
namespace Microsoft.AspNetCore.Http.Metadata;

public interface IRequestSizeLimitMetadata
{
-    public long MaxRequestBodySize { get; }
+    public long? MaxRequestBodySize { get; }
}

namespace Microsoft.AspNetCore.Mvc;

- public class DisableRequestSizeLimitAttribute : Attribute, IFilterFactory, IOrderedFilter
+ public class DisableRequestSizeLimitAttribute : Attribute, IFilterFactory, IOrderedFilter, IRequestSizeLimitMetadata
```

Context: https://github.com/dotnet/aspnetcore/pull/40279#discussion_r872892536

**Comment by halter73** [comment]
API Review:

We think this is filling a gap. People would be surprised if the `RequestSizeLimitAttribute` works but `DisableRequestSizeLimitAttribute` doesn't.

We should update our docs to make it clear that disabling request size limits can be a security concern, particularly if the request body is being buffered. @david-acker Do you mind updating the doc comments for `DisableRequestSizeLimitAttribute` with a remark to this effect in your PR when you add the `IRequestSizeLimitMetadata` implementation to `DisableRequestSizeLimitAttribute`?

**Comment by david-acker** [comment]
I've added the following as a remark to the doc comments for `DisableRequestSizeLimitAttribute`:

`Disabling the request body size limit can be a security concern in regards to uncontrolled resource consumption, particularly if the request body is being buffered.`

Let me know if there's anything that you'd like me to add or change.
