### ISSUE TITLE
InputText and other input components do not use SetUpdatesAttributeName() for two-way binding

### ISSUE THREAD

**Issue by hakenr** [dotnet/aspnetcore#40097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi @SteveSandersonMS,
is there any reason why the `InputText` implementation (and implementation of other input components) do not use the `SetUpdatesAttributeName("value")` method when it replicates the `<input @bind-value="..." />` in `BuildRenderTree()`?

The changes in DOM get not synchronized to the .NET model then.

As a result when someone wants to derive his own component from `InputText` e.g. to apply some text formatting and you enter the same text input twice, the first callback causes the UI to replace the value with the formatted value but the second callback leaves the input intact as it does not detect any change in the .NET model to be synchronized to DOM (no matter you call the `StateHasChanged()` or not).

### Expected Behavior

.NET model of `InputText` and other input components reflect DOM changes (two-way binding) from their underlying `input` elements.

### Steps To Reproduce

```csharp
public class MyInputText : InputText
{
	protected override bool TryParseValueFromString(string? value, out string? result, [NotNullWhen(false)] out string? validationErrorMessage)
	{
		if (value == "24h")
		{
			result = "24:00:00";
		}
		else
		{
			result = value;
		}
		validationErrorMessage = null;
		return true;
	}
}
```

```razor
<EditForm Model="model">
    <MyInputText @bind-Value="@model.Value" />
</EditForm>
@model.Value

@code
{
    private Model model = new Model();
    private class Model
    {
        public string Value { get; set; }
    }
}
```
![2022-02-09_16-49-57](https://user-images.githubusercontent.com/12828888/153237638-f5038582-35e3-487d-bef2-9243b9cce7a0.gif)

This fixes the issue:
```csharp
public class MyInputText : InputText
{
	protected override bool TryParseValueFromString(string? value, out string? result, [NotNullWhen(false)] out string? validationErrorMessage)
	{
		if (value == "24h")
		{
			result = "24:00:00";
		}
		else
		{
			result = value;
		}
		validationErrorMessage = null;
		return true;
	}

	protected override void BuildRenderTree(RenderTreeBuilder builder)
	{
		builder.OpenElement(0, "input");
		builder.AddMultipleAttributes(1, base.AdditionalAttributes);
		builder.AddAttribute(2, "class", base.CssClass);
		builder.AddAttribute(3, "value", BindConverter.FormatValue(base.CurrentValue));
		builder.AddAttribute(4, "onchange", EventCallback.Factory.CreateBinder<string>((object)this, (Action<string>)delegate (string? __value)
		{
			base.CurrentValueAsString = __value;
		}, base.CurrentValueAsString, (CultureInfo?)null));
		builder.SetUpdatesAttributeName("value");              // <-------- THIS FIXES THE ISSUE
		builder.CloseElement();
	}
}
```

### .NET Version

6.0.101

### Anything else?

If it helps, I can prepare a PR for this.

Related issue [#17281](https://github.com/dotnet/aspnetcore/issues/17281)

**Comment by SteveSandersonMS** [comment]
@hakenr Yes, I think you're right. Thanks for providing such a clear issue description and for checking into the solution.

If you are willing to provide a PR for this (along with some E2E test cases showing that it makes a difference), I'd be happy to work with you to get it merged soon.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/46434
