### ISSUE TITLE
Hot reload using dotnet watch doesn't work 98% of the time

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#40091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My colleges and I use Macs and the .NET CLI for development. Our solution contains two Blazor Wasm hosted apps and a .NET Web API. There are 4 of us and in the past month only 2 of us have seen hot reload work and that was for a grand total of two days. 

Running `dotnet watch -v` shows the following: `watch : Hot reload capabilities: .` which I'm sure I read somewhere is not a good sign?

I appreciate this isn't much to go on and I'd love to provide more information but I'm not sure what. But I'm happy to provide any other details.

### Expected Behavior

Hot reload should work more than not.

### .NET Version

6.0.101

**Comment by pranavkm** [comment]
Thanks for reporting this. We addressed this as part of https://github.com/dotnet/aspnetcore/issues/36723 for the 6.0.200 release of the SDK. Could you try grabbing a nightly build of the SDK from https://github.com/dotnet/installer#installers-and-binaries and see if it helps?

**Comment by chrissainty** [comment]
Thanks, @pranavkm. I'll try this out either later today or tomorrow and report back.

**Comment by chrissainty** [comment]
@pranavkm I'm struggling to install the nightly build. I'm getting an error from MacOS: "dotnet-sdk-6.0.201-osx-x64.pkg cannot be opened because it is from an unidentified developer." I couldn't find anything addressing this issue on the readme.

**Comment by chrissainty** [comment]
@pranavkm So good and bad news. I installed the nightly build (6.0.201) and hot reload started working... for a day or two. But I'm back to `Hot reload capabilities: .`. Are there anymore details or things I can try?
