### ISSUE TITLE
'atob' on Window error on .NET 6.0

### ISSUE THREAD

**Issue by reappl** [dotnet/aspnetcore#40113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I have a working .NET 5.0 blazor app with a function to show binary (pdf) content but converting the project to .NET 6.0 this logic is broken and I get the following javascript error:

Error: Microsoft.JSInterop.JSException: **Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.**
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at openFileInNewWindow ..........

### Steps To Reproduce

Switching the target framework from 5.0 to 6.0 will generate this error.

[JSProblem.zip](https://github.com/dotnet/aspnetcore/files/8040057/JSProblem.zip)

### Exceptions (if any)

blazor.server.js:1 [2022-02-10T10:05:22.080Z] Error: Microsoft.JSInterop.JSException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at openFileInNewWindow (http://localhost:9503/main.js:2:32)
.......

**Comment by javiercn** [comment]
@reappl thanks for contacting us.

We did a change in .NET 6.0 to avoid base64 encoding byte arrays for improved performance. You should be able to get the UInt8Array directly without using atob

**Comment by reappl** [comment]
got it working and can confirm the performance improvement
