### ISSUE TITLE
Cannot Inject ApplicationUser into Controller .NET CORE6

### ISSUE THREAD

**Issue by 1988gadocansey** [dotnet/aspnetcore#40117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[WebApplication6.Models.ApplicationUser]' while attempting to activate 'WebApplication6.Controllers.HomeController'
<img width="1171" alt="Screen Shot 2022-02-10 at 1 24 57 PM" src="https://user-images.githubusercontent.com/7513799/153417152-ec4c72c0-cfe6-4cf4-8dc7-d63d253fde4c.png">
<img width="1378" alt="Screen Shot 2022-02-10 at 1 25 13 PM" src="https://user-images.githubusercontent.com/7513799/153417201-7713c18f-7eb6-4975-82fd-954c4c43da49.png">
.

### .NET Version

6

**Comment by adityamandaleeka** [comment]
@1988gadocansey Can you check to see if you're calling `AddIdentity` as @fretje pointed out, and if you are already doing that and it's not working, please share your Startup code.

**Comment by 1988gadocansey** [comment]
> You need to call [`AddIdentity()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.addidentity?view=aspnetcore-6.0) in your app startup, otherwise those services won't be available.

I did

But i cant get the User object in the controller. I don't know maybe i'm not doing it right
<img width="845" alt="Screen Shot 2022-02-12 at 3 10 53 PM" src="https://user-images.githubusercontent.com/7513799/153716808-0e3e8b1e-9642-43ab-b4c4-a52ee7edbb55.png">

<img width="1226" alt="Screen Shot 2022-02-12 at 3 10 05 PM" src="https://user-images.githubusercontent.com/7513799/153716776-8ae8031f-a502-4e1b-a2c9-2d73d35cc586.png">
<img width="650" alt="Screen Shot 2022-02-12 at 3 10 29 PM" src="https://user-images.githubusercontent.com/7513799/153716791-003f6d6d-974c-4767-8ec1-d3571d732118.png">

**Comment by 1988gadocansey** [comment]
var applicationUser = await _userManager.GetUserAsync(User); 

loggedIn user (applicationUser) is always null. please help me.

**Comment by HaoK** [comment]
There's not enough info here to say for sure what's wrong, are you sure you have an application cookie in your request?  Did you login successfully first?

**Comment by 1988gadocansey** [comment]
Is working now. thanks.
