### ISSUE TITLE
Generate Minimal API from OpenAPI file

### ISSUE THREAD

**Issue by masonyc** [dotnet/aspnetcore#40135]
I was using https://github.com/OpenAPITools/openapi-generator to generate server code from an OpenAPI file. However, this will generate controllers that inherit from the Controller base class. I am wondering is it possible to generate controller code in minimal API style from an OpenAPI file currently? Thanks.

**Comment by skalinets** [comment]
maybe this request should be in https://github.com/OpenAPITools/openapi-generator and not here?

**Comment by masonyc** [comment]
thanks I will ask there, just trying to make sure I am not missing anything here

**Comment by rafikiassumani-msft** [comment]
@masonyc We are not planning to support server stub code (Controllers) generation with OpenAPI file. We have a feature on our road to improve how we generate client code. Should this plan change, we will include communication through our roadmap.
