### ISSUE TITLE
Is there something like IIS recycling periodically for Kestrel server on Linux?

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [dotnet/aspnetcore#40147]
I re-read all documentation of how to host ASP.NET website on Linux and in all cases it is Apache or nginx that just forwards traffic to Kestrel server that is running as service.

But is there any way to recycle ASP.NET periodically on Linux? Or shutdown web suite when it is idle and start on first request?

I can restart service by timer, but it will affect requests it is processing and for some time (few seconds) new requests will not be processed.

Thank you,
Vlad

**Comment by adityamandaleeka** [comment]
If you need to periodically restart Kestrel, you'd need to use an orchestrator to do it; there's no built-in support for that type of thing in Kestrel.

Similarly, while you could write some code that would shut down the server when it's idle, you'd need something external to start it again when a request comes in.

**Comment by vladimir-cheverdyuk-altium** [comment]
Do you know any such orchestrator by any chance?

**Comment by davidfowl** [comment]
Systemd on Linux.

**Comment by vladimir-cheverdyuk-altium** [comment]
Thank you @davidfowl. Do you know by any chance, does ASP.NET supports it? I had mixed results when searched internet.
Also do you know, will it work with periodic recycling? I meant if I restart service, will it finish with current requests and then restart my service and then process new requests?

Thank you,
Vlad

**Comment by davidfowl** [comment]
> Thank you @davidfowl. Do you know by any chance, does ASP.NET supports it?

Yes. https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Systemd/ and [UseSystemd](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.kestrelserveroptionssystemdextensions.usesystemd?view=aspnetcore-6.0) to enable socket activation for Kesterl.

> Also do you know, will it work with periodic recycling?

I have no idea. That's a systemd questions.

>  I meant if I restart service, will it finish with current requests and then restart my service and then process new requests?

It should, the system is designed with graceful shutdown in mind but I don't know how systemd handles the creation of a new process after draining the existing one.

**Comment by davidfowl** [comment]
Three's also PM2 https://pm2.keymetrics.io/ (it says node js but it's a generic process monitor)

**Comment by vladimir-cheverdyuk-altium** [comment]
Thank up @davidfowl. It looks like systemd with socket activation is all I need. I still need to do some testing but it looks promising from documentation. Once I get results I will post them here.
