### ISSUE TITLE
MarkupString not working and encode character &

### ISSUE THREAD

**Issue by WinnetouP** [dotnet/aspnetcore#40141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to obtain an URL with & character but after the last update of visual studio (february 2022) all & characters is always converted to `&amp;`
I tested with a simple string, it's converted
I tested with a MarkupString, it's converted also and it's not good because normally MarkupString must keep what I provided into a string

### Steps To Reproduce

```
<img src="@ImageUrl" />
@code {
private MarkupString ImageUrl = new MarkupString("https://xxxx/yyyy?field1=x&field2=y");
}
```

### .NET Version

6.0.102

### Anything else?

Microsoft.AspNetCore.App 6.0.2

**Comment by javiercn** [comment]
@WinnetouP thanks for contacting us.

You don't need to use MarkupString inside an attribute

**Comment by WinnetouP** [comment]
I know, I switched on MarkupString after the last update of Visual Studio, my previous code was based on string

**Comment by javiercn** [comment]
@WinnetouP It's not clear to me what you are implying, are you suggesting that the string gets encoded if you pass it directly on to the attribute?

**Comment by javiercn** [comment]
@WinnetouP thanks for the additional details.

Did you upgrade from a previous version like 3.1 or 5.0?

**Comment by WinnetouP** [comment]
No always on .net 6

**Comment by WinnetouP** [comment]
After the Visual Studio 2022 update version 17.0.6

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
