### ISSUE TITLE
Blazor WASM Environnement issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#40146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor Wasm hosted project.

Environnements are not working as expected:

Queries contains Blazor environment header : blazor-environment: Development
but appsettings files are not loading accordingly. Only base appsettings file is loading.

I have to force environnement with 
```
    <script>
        Blazor.start({
            environment: "Development"
        });
    </script>
```
to have my appsettings files loading correctly.

Although I tried to display Environment in my web page.
When the environnement is forced by Startup script I see Development, so it's fine.
But When I let blazor-environment header determine the environment, I see Development, Development

I noticed something weird with 
blazor.webassembly.js:
![image](https://user-images.githubusercontent.com/23618436/153629187-9d08a8a1-f42d-45d5-8eaa-21f2d9ec0f8f.png)

blazor.boot.json
![image](https://user-images.githubusercontent.com/23618436/153629380-15d6338f-02fb-4cbd-972e-a8494483ac5f.png)

and donet.js
![image](https://user-images.githubusercontent.com/23618436/153629501-9f2315f0-6d96-4c77-9a51-b52f3e3414e3.png)

It should be the explanation of the issue.

### .NET Version

6.0.102

**Comment by javiercn** [comment]
@Julien-Marpault thanks for contacting us.

It seems that something in your app is causing `Blazor-Environment` to be appended to the response multiple times. Do you have multiple invocations of `UseBlazorFrameworkFiles`?

**Comment by Julien-Marpault** [comment]
@javiercn Unfortunately no.

Here's the pipeline:

```csharp
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.DefaultModelsExpandDepth(-1);

    });

}

app.UseHttpsRedirection();

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapFallbackToFile("index.html");

app.Run();
```

**Comment by Julien-Marpault** [comment]
We found the issue.
Someone added blazor-environment header in Helm chart.
It worked fine until we added the hosting application.

My apologies for this mistake.

**Comment by javiercn** [comment]
@Julien-Marpault No worries
