### ISSUE TITLE
Referencing incompatible dependency in a Blazor WebAssembly project will result in an unhelpful error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40157]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problems-adding-an-Razzor-class-library-/1655826)._

---
[severity:I'm unable to use this version]
I'm using VS2022 latest, Webassembly 6.0.1

When I try to add an razor class library to an Blazor WebAssembly Project than I get following error on compile

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	**There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'**.	MccClient	C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	427

---
#### Feedback Bot on 2/7/2022, 07:22 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. After discussing this some more we've decided to close this as the current error we think is good enough based on the information available at the time it is thrown.
