### ISSUE TITLE
Razor view CSS isolation does not support HTML header tag

### ISSUE THREAD

**Issue by Jaffacakes82** [dotnet/aspnetcore#40151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The HTML `<header>` tag does not seem to be supported by CSS isolation in Razor views.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/4850159/153649717-eb8c8d12-b83a-4c32-917e-072a569c0ccd.png">

From the above image, you can see no uniquely named attribute is applied to the markup.

### Expected Behavior

The HTML `<header>` tag is given a uniquely named attribute and applies styles defined in the scoped CSS file.

### .NET Version

6.0.101

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/x64/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [/usr/local/share/dotnet/x64/sdk]
  5.0.404 [/usr/local/share/dotnet/x64/sdk]
  6.0.101 [/usr/local/share/dotnet/x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
@Jaffacakes82 thanks for contacting us.

Could you produce a minimal repro project for us to make progress?
