### ISSUE TITLE
VS 2022: Default Angular and React web apps do not start

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40155]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022:-Default-Angular-and-React-web-a/1657146)._

---
1. Create Angular or React web app.
2. Press F5.

The web app doesn't start. Instead infinite loop occurs.
! [image.png] (https://aka.ms/dc/image?name=Be0b0462a46f348be91461955e9b09283637799379964202660_20220208-202634-image.png&tid=e0b0462a46f348be91461955e9b09283637799379964202660)

---
#### Feedback Bot on 2/8/2022, 06:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/8/2022, 11:31 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you have Node installed on your machine and which version?

**Comment by JohnyL** [comment]
VS 2022 17.2.0 Preview 1.0 - all works fine!
