### ISSUE TITLE
Razor: Duplicate ids generated by INPUT tag helpers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40156]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Razor:-Duplicate-ids-generated-by-INPUT-/1656912)._

---
The following mark-up makes perfect sense:

> `<INPUT ASP-FOR=CMD VALUE=OK > <INPUT ASP-FOR=CMD VALUE=DEL >`

where the page model decides what to do based on the value of `CMD` received from the client.  But the input tag helper generates the same `ID` for both `INPUT` elements, making the generated code invalid.  The workaround is to specify the `ID` explicitly:

> `<INPUT ASP-FOR=CMD VALUE=OK ID=CMD-OK > <INPUT ASP-FOR=CMD VALUE=DEL ID=CMD-DEL >`

This is lame and annoying.

---
#### Feedback Bot on 2/8/2022, 09:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We recommend setting unique values for your `id` in the tag explicitly.
Given that this has been the behavior for a long time and we haven't seen any other concerns with current behavior we don't plan to change this.
