### ISSUE TITLE
Hot reload fails when running the blazor wasm hosted app in without debugging mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40154]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hot-reload-fails-when-running-the-blazor/1659625)._

---
i ran the blazor wasm hosted app (without debugging mode), made a simple change in a text field and when the app tried to hot reload it fails with below error

! [image.png] (https://aka.ms/dc/image?name=B09f7a67e9b9b40fa83a7bc99ec534cf9637800700714612010_20220210-113751-image.png&tid=09f7a67e9b9b40fa83a7bc99ec534cf9637800700714612010)

---
#### Feedback Bot on 2/10/2022, 05:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you by any chance changed your hosting environment?

**Comment by mkArtakMSFT** [comment]
Error from the link:
![B09f7a67e9b9b40fa83a7bc99ec534cf9637800700714612010_20220210-113751-image](https://user-images.githubusercontent.com/34246760/160887993-1dc7b4c1-2bc4-41a5-bb7f-2489a2cda7ad.png)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
