### ISSUE TITLE
LogLevel Warning is somewhat verbose for UserManager

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#40160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Same issue as in #39910 

Our logging system gets somewhat spammed by common user mistakes. Such as sign-up errors (i.e. failing password validation) or sign-in errors such as invalid passwords. See image below

![image](https://user-images.githubusercontent.com/5054780/153663923-e6cf1032-054a-48b2-9a76-ae3b88d4040e.png)

### Describe the solution you'd like

I would suggest logging such common errors as Debug.

### Additional context

@Tratcher

**Comment by msschl** [comment]
However, I think some of those events should somehow be recorded. Maybe with the new metric counters provided by dotnet?

```cs
private static readonly Counter<int> _signInAttemptsCounter = Meter.CreateCounter<int>("sign_in_attempts_total");
```

 When the sign-in succeeds, it could be recorded as the following:
```cs
_signInAttemptsCounter.Add(1, new KeyValuePair<string, object?>("success", true));
```

When the sign-in fails, it could be recorded as following (`invalid_credentials` being the placeholder for the failed reason):
```cs
_signInAttemptsCounter.Add(1, new KeyValuePair<string, object?>("success", false), new KeyValuePair<string, object?>("reason", "invalid_credentials"));
```

However, I think this could be a separate discussion.

**Comment by adityamandaleeka** [comment]
@msschl We'd take a PR for changing the log level to Debug for these (as you did for the other one in https://github.com/dotnet/aspnetcore/pull/40000).
