### ISSUE TITLE
IWebHostENvironment returns incorrect path when deployed to server

### ISSUE THREAD

**Issue by BaronMatrix** [dotnet/aspnetcore#40162]
Hi,
I'm working with a .Net 6 project and I have some code that grabs an HTML template from the ContentRootPath to send an email. It works fine locally but when I deploy the application, Env.ContentRootPath returns C:\home\site\wwwroot which is the WebRootPath. The file is located in a folder in the root folder.

The app throws an exception and doesn't send the email.

How can I correct this?

**Comment by BaronMatrix** [comment]
The code is in the middle of a block, but it's just the call to Env.ContentRootPath that fails. The line is in bold.

` MailMessage accountMsg = new MailMessage(siteAddress, userAddress);

                accountMsg.Bcc.Add(new MailAddress("orders@popsandbigrubes.com"));
                accountMsg.BodyEncoding = Encoding.ASCII;
                accountMsg.IsBodyHtml = true;
                accountMsg.Subject = "Your Order From Pops And Big Rubes";

                List<string> mealList;
                int sideCount, drinkCount, sandCount;
                GetMeals(cart, out mealList, out sideCount, out drinkCount, out sandCount);
                var cartTotal = string.Format("{0:0.0.00}", total);

                var guid = GetReceiptDetails.GetNewGuid();
                var siteName = "https://www.popsandbigrubes.com";
                var dataDictionary = new Dictionary<string, string>();
                dataDictionary.Add("sender", "orders@popsandbigrubes.com");
                dataDictionary.Add("date", DateTime.Today.ToShortDateString());
                dataDictionary.Add("name", model.DisplayName);
                dataDictionary.Add("location", model.Address);
                dataDictionary.Add("sides", sideCount.ToString());
                dataDictionary.Add("sands", sandCount.ToString());
                dataDictionary.Add("drinks", drinkCount.ToString());
                dataDictionary.Add("urlAction", siteName + "/Cart/ViewOrder?cart=" + cart.UserId + "&ip=" + guid.ToString());
                for (var i = 0; i < mealList.Count; i++)
                {
                    var item = mealList[i].Split(",");
                    var meal = "meal" + i;
                    var price = "price" + i;
                    dataDictionary.Add(meal, item[0]);
                    dataDictionary.Add(price, "$" + item[1].Substring(0, item[1].Length - 2));

                }
                dataDictionary.Add("Total", cartTotal);

                **var loc = Env.ContentRootPath + "/Templates/Notifications/ReceiptEmail.html";
                ViewBag.loc = loc;
                var template = System.IO.File.ReadAllText(Env.ContentRootPath + "/Templates/Notifications/ReceiptEmail.html");**`

**Comment by BaronMatrix** [comment]
**[](https://github.com/BaronMatrix)**var loc = Env.ContentRootPath + "/Templates/Notifications/ReceiptEmail.html";
            ViewBag.loc = loc;
            var template = System.IO.File.ReadAllText(Env.ContentRootPath + "/Templates/Notifications/ReceiptEmail.html");**`

**Comment by davidfowl** [comment]
Do you think you can make something that I can run to observe the problem? If this was broken all the time I think we would have seen more things broken. So it's likely there's something being configured in your setup that's causing this to happen or a bug somewhere that is triggered under certain conditions. We'd need a reproduction of the issue to make progress here.

**Comment by BaronMatrix** [comment]
It's a very simple file access. The problem is that it only happens when deployed so you can't see it locally. In .Net 5 it was suggested to add this code to Startup.cs. This was before Minimal APIs though and it doesn't translate directly.

AppDomain.CurrentDomain.SetData("ContentRootPath", env.ContentRootPath);
AppDomain.CurrentDomain.SetData("WebRootPath", env.WebRootPath);

Either way it should never return a path that isn't the location of the app. I'm looking for a way to ensure that it doesn't refer to the local drive. I'm on 17.0.0 deploying to an ISP. Placing a try around the code found it.

**Comment by davidfowl** [comment]
I don't know what the problem is if the bug can't be reproduced. Can you reproduce it in production with a new application?

**Comment by BaronMatrix** [comment]
Was out. Thanks for the reply. As a former "softie" I know th edrill. I just don't have extrra web sites I can deploy code to. I'm just trying to figure out HOW it would possibly read from the C: Drive.

**Comment by davidfowl** [comment]
```
AppDomain.CurrentDomain.SetData("ContentRootPath", env.ContentRootPath);
AppDomain.CurrentDomain.SetData("WebRootPath", env.WebRootPath);
```

How is the above snippet related to the problem? Somethings that could help debugging if you can't setup a repro with a new project:
- Dump the directory structure on the server
- Dump all of the configuration (don't paste them here tho)

That might give some more data.

**Comment by BaronMatrix** [comment]
I'll try FTP ing and see the folders. It may be just taking the local drive letter rather than taking the ContentRootPath. The snippet was something suggested when first using the new APIs.

**Comment by BaronMatrix** [comment]
FTP solved the issue. The file actually isn't there. The path is correct. Will talk to the ISP to see why it's not copying in a full deploy.

**Comment by BaronMatrix** [comment]
Now I can get the email sent but it still throws the error. WOW!
