### ISSUE TITLE
Add Results.Empty

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#40168]
## Background and Motivation

Sometimes you want to return a result that does not mutate the response in anyway. This happens when you have multiple branches in a route handle and one of them should be a noop. You are forced to return an IResult and we don't have a built in result type that fills this role. Mvc has EmptyResult for this purpose.

## Proposed API

```C#
namespace Microsoft.AspNetCore.Http
{
    public static class Results
    {
        public static IResult Empty(); // This could also be a property
    }
}
```

## Usage Examples

``` C#
app.MapGet("/{id}", (HttpContext context, string id) =>
{
    var httpProcessor = GetTargetStream(id);
    if (httpProcessor is null) return Results.NotFound();
 
    await httpProcessor.ProcessAsync(context);
     // Don't change what the httpProcessor did
    return Results.Empty();
});
```

## Alternative Designs

Force people to write their own.

## Risks

None

**Comment by pranavkm** [comment]
API review:

We'll use properties instead. Here's the approved API:

```diff
public static class Results
{
+   public static IResult Empty { get; } = new EmptyResult();
}

public class ControllerBase
{
+    public static EmptyResult Empty { get; } = new ();
}
```

**Comment by ShreyasJejurkar** [comment]
Hi @davidfowl @pranavkm, do we need to address this for MVC as well? I mean in property in ControllerBase??

**Comment by davidfowl** [comment]
Yep
