### ISSUE TITLE
Generate dictionary keys in blazor @bind

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#40185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to propose that `@bind="MyDictionary[keyVariable]"` creates the key in dictionary, please check the following example

```
@foreach(var obj in List)
{
    <input @bind="Data[obj.Id]"/>
}

@code{
    Dictionary<string, string> Data = new ();
}
```

### Describe the solution you'd like

I would like the blazor to dynamically create keys from a @bind

**Comment by KristofferStrube** [comment]
Bind cares about wheter or not you can get and set the property that is passed to it. We don't have this capability for lists or arrays either. If it were to automatically add the key then that would not be the behaviour I would expect.

You can instead achieve this with a custom Class like so:
```razor
@foreach (var obj in List)
{
    <input @bind="Data[obj.Id]" />
}

@foreach(string s in Data.InternalDict.Values)
{
    <p>@s</p>
}

@code {
    public AutoAddDict<string, string> Data = new();

    IEnumerable<Thing> List { get; set; } = Enumerable.Range(0, 5).Select(i => new Thing() { Id = i.ToString() });

    private class Thing
    {
        public string Id { get; set; }
    }

    public class AutoAddDict<TKey, Tvalue>
    {
        public Dictionary<TKey, Tvalue> InternalDict { get; } = new();

        public Tvalue this[TKey key]
        {
            get
            {
                if (!InternalDict.ContainsKey(key))
                {
                    InternalDict.Add(key, default);
                }
                return InternalDict[key];
            }
            set
            {
                InternalDict[key] = value;
            }
        }
    }
}
```

But I think this would be nicer to achieve by instead adding some string property to the Thing that you iterate over and then Bind the input to that if possible.
