### ISSUE TITLE
CSS Hot Reload Causing Browser Link Error in JS Console in Browser

### ISSUE THREAD

**Issue by stap123** [dotnet/aspnetcore#40189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we run our app we get a browser link error but we do not have the `Microsoft.VisualStudio.Web.BrowserLink` package. There is no meaningful error message, what is shown is "net::ERR_CONNECTION_RESET" trying to access [https://localhost:44399/2306cefcc23b46319f5293f8b35d9ad6/browserLink](https://localhost:44399/2306cefcc23b46319f5293f8b35d9ad6/browserLink)

### Expected Behavior

No error should be shown when the feature isn't used.

### Steps To Reproduce

Create a new ASP.NET Core Web App with default settings. Run in browser, you should see the browser link error.

### .NET Version

6.0.200-preview.22055.15

### Anything else?

I found that when you turn off CSS Hot Reload in VS the error isn't shown (Projects and Solutions > ASP.NET Core > CSS Hot Reload).

*Using VS2022 Current, 6.0.2 packages, everything up to date*

**Comment by javiercn** [comment]
@stap123 thanks for contacting us.

In order for you to get a better and faster answer we would suggest you report this issue directly through the report a problem dialog in Visual Studio. See details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)

/cc @jodavis

**Comment by stap123** [comment]
Report created https://developercommunity.visualstudio.com/t/css-hot-reload-causing-browser-link-error-in-js-co/1663250?from=email
