### ISSUE TITLE
Issue running BlazorWebAssemblyCustomInitialization sample

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#40195]
@javiercn @pranavkm 

Regarding this issue - https://github.com/dotnet/aspnetcore/issues/17504

It has been closed with 
pranavkm: Is this resolved as part of the JS initializers work?
javiecrn: Yes

I can't do anything with that solution text :)

Would you mind providing me with some information, please? What has been done to fix this, and was it released in .NET 6? I'd have asked on the original issue, but it is locked.

Thanks

Pete

**Comment by egil** [comment]
This might be the information you are looking for: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#javascript-initializers

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

The link @egil points to has the details.

You can add a file to your library that will be automatically loaded by Blazor and will support running code before blazor boots and after the host has been started, so you can do things like initialize custom elements or completely change the way Blazor boots.

**Comment by javiercn** [comment]
Here is a sample https://github.com/aspnet/AspLabs/blob/main/src/BlazorWebAssemblyCustomInitialization/Microsoft.AspNetCore.Components.WebAssembly.MultipartBundle/wwwroot/Microsoft.AspNetCore.Components.WebAssembly.MultipartBundle.lib.module.js

**Comment by mrpmorris** [comment]
@javiercn does blazor just look for all exported functions named `afterStarted` and then executes it?

**Comment by javiercn** [comment]
@mrpmorris Yes. they need to be exported from the module, there's no defined order between modules and you get the Blazor object.

**Comment by ChristianWeyer** [comment]
> Indeed, there is no `packages` folder at all in `artifacts` @javiercn

Any more ideas here @javiercn? - no luck so far...

**Comment by javiercn** [comment]
@ChristianWeyer Do you get an error if you go to the tasks project and run `dotnet pack`? (You might need to use the local dotnet from the repo bootstrap script).

**Comment by ChristianWeyer** [comment]
`dotnet pack` ran without errors in that `*.Tasks `project folder.

**Comment by ChristianWeyer** [comment]
Do you think we can find a good way to get this beast compiled and running @javiercn ? 😉
