### ISSUE TITLE
In JS interop, handle ValueTask equivalently as Task

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#40198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, `[JSInvokable]` methods can be sync or async, but if they are async, they are limited to returning `Task`/`Task<T>`.

We don't currently allow `ValueTask`/`ValueTask<T>`. If a developer does in fact define a method like this:

```cs
[JSInvokable]
ValueTask<T> SomeMethod() { ... }
```

... then because there's no logic in JSInterop to recognize `ValueTask`/`ValueTask<T>`, we JSON-serialize the whole ValueTask and treat it as a synchronous result. As it happens, `ValueTask` JSON-serializes quite happily so there's no exception, but the result on the JS side is pretty useless.

### Describe the solution you'd like

I can't immediately think of any reason we shouldn't update `DotNetDispatcher.cs`'s `BeginInvokeDotNet` logic to recognize `ValueTask` and handle it in the same way we handle `Task`.

### Additional context

I think there are legit use cases for a JS-invokable method to want to return `ValueTask<T>`, e.g., when the method returns possibly-cached values, if the cache entry exists synchronously, it can do `ValueTask.FromResult(result)`.

**Comment by senbar** [comment]
I have started working on this issue
