### ISSUE TITLE
[Docs] More detail for `Microsoft.AspNetCore.Http.ConnectionInfo.RemoteIpAddress`

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#40191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

One uses `HttpContext.Connection.RemoteIpAddress` to get a client's IP address.

[`Microsoft.AspNetCore.Http.ConnectionInfo.RemoteIpAddress`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connectioninfo.remoteipaddress) is marked as [nullable](https://github.com/dotnet/aspnetcore/blob/v5.0.14/src/Http/Http.Abstractions/src/ConnectionInfo.cs#L24).

The docs linked above just say *"Can be null"* - under what conditions can it be null?

### Describe the solution you'd like

The docs for `Microsoft.AspNetCore.Http.ConnectionInfo.RemoteIpAddress` are unclear. Please add more detail.

**Comment by davidfowl** [comment]
If the connection isn’t a tcp connection. It could be a Unix domain socket or a transport that isn’t up based

**Comment by lonix1** [comment]
Thanks @davidfowl !

So to summarise for the docs, "It could be null when:"
- Kestrel is behind a reverse proxy server, and `UseForwardedHeaders` is not configured (one will have [problems](https://stackoverflow.com/questions/35441521/remoteipaddress-is-always-null))
- The request did not arrive on a TCP connection, which occurs when
  - It is a Unix domain socket
  - It's a non-IP transport

What should I do with this issue, close it or leave it open? I didn't know which repo is for API docs.

**Comment by Tratcher** [comment]
> * Kestrel is behind a reverse proxy server, and `UseForwardedHeaders` is not configured

When Kestrel is behind a reverse proxy then RemoteIpAddress will report the address of the proxy rather than null.

**Comment by ZarakiKanzaki** [comment]
Is there any update for this issue? I'd like to help correcting the documentation.

**Comment by Tratcher** [comment]
@ZarakiKanzaki feel free.

Another unusual situation is when using TestServer or WebApplicationFactory, these use an in-memory transport and do not set RemoteIpAddress.

I don't think we want to describe too many specific situations, but we could generalize these different situations by saying that this could be affected by using proxies, alternative transports, and test infrastructure.
