### ISSUE TITLE
Host blazor webassembly app with different base path is not working as described in documentation

### ISSUE THREAD

**Issue by DrLeh** [dotnet/aspnetcore#40205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Webassembly, .NET hosted application. On the server we host it on, the base path of the app will be `mydomain.com/coolapp`. Therefore, to try to get the app to render correctly on the server, I've been following Microsofts steps outlined in the "App base path" section of this page: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path

I'm following all the steps as I see there, but when I try to run the application, I'm getting 404's from blazor framework files. As far as I can tell, I'm doing everything described in the docs. 

### Expected Behavior

Following the steps as outlined in documentation should allow me to run my app locally, despite being configured to run at the `/coolapp` path when hosted on another server. Instead I get 404's from key files that are still hosted at the wrong path. Documentation is unclear whether I'm missing something.

### Steps To Reproduce

1. Create New blazor wasm project, .net core hosted option checked
1. Change the base tag in `index.html` to: `<base href="/coolapp/" />`
1. Add this line to `Program.cs`: `app.UsePathBase("/coolapp");`
1. Add `app.UseStaticFiles("/coolapp"); //without this, you get 404's from blazor.framework.js and nothing loads`
1. Set launch options for command line argument `"commandLineArgs": "--pathbase=/coolapp",` in the `"BlazorApp1.Server"` profile 
1. Run BlazorApp1.Server application
1. go to `localhost:port/coolapp` path

From there, the app shows "An unhandled error has occurred. [Reload](https://localhost:7238/coolapp/)" link, indicating that it has loaded some javascript. Inspecting the network tab in dev tools shows that the .dll files are 404ing.

[![enter image description here][1]][1]

If I navigate to this path directly it 404s, but if I remove the `/coolapp` from the url of the dll, it will download the file. So it's like it's still being hosted to the base path of `/` rather than `/coolapp`. 

What am I missing? I'm trying the most basic example possible. I pushed my code here for examination: https://github.com/DrLeh/BlazorAppNewBasePath

  [1]: https://i.stack.imgur.com/rq3lQ.png

### .NET Version

6.0.101

### Anything else?

Companion SO question: https://stackoverflow.com/questions/71113666/how-to-host-blazor-webassembly-app-with-different-base-path

**Comment by guardrex** [comment]
Hello @DrLeh ... I work on the Blazor docs and have 👀 on your issue/discussion here. We've had our share of successes and failures trying to cover the app base path scenarios with that guidance. Some readers have reported it works perfectly, others ... as in this case ... have trouble with it. We usually sort out the situation and make further updates to the content. I'll take a look at your posted repro as soon as I can, but I'm 🏃 on a few high priority issues at the moment. I hope to be free on Thursday.

**Comment by guardrex** [comment]
@DrLeh ... I didn't get too deep into your repro sample before noticing that your call to `UsePathBase` is rather low in middleware ordering. Can you move it **_UP_** in the order? Try placing it immediately after the `var app = builder.Build();` line.

This is per our current middleware guidance, but it isn't cross-linked directly to the Blazor *App base path* section, which I think we'll need to do ... even if it doesn't resolve some or all of the foul routing behavior with your app.

> Usually middleware that appears before routing modifies some property of the request, such as `UseRewriter`, `UseHttpMethodOverride`, or `UsePathBase`.

Cross-reference: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#aspnet-core-endpoint-definition

**Comment by guardrex** [comment]
I see. I can't explain that behavior.

I do think that it makes sense for the Blazor *App base path* section to recommend the setting **_early in the request processing pipeline_** ... **first** is where I normally place it. I'll open an issue to address that aspect and remain 👂 here for further discussion.

**Comment by guardrex** [comment]
FYI @mkArtakMSFT ... I made a doc update to prompt devs to place a call to `UseBasePath` early in the request processing pipeline to set the base path prior to middlewares that interact with the path. If that's all that this requires at this time, the PU issue can close. Otherwise, I'm 👂 here for additional relevant doc guidance for the *App base path* section.

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex.
Closing this as no further action is pending here.
