### ISSUE TITLE
Add an EventSource event when the server is listening for incoming requests

### ISSUE THREAD

**Issue by noahfalk** [dotnet/aspnetcore#40238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This request is one part of https://github.com/dotnet/runtime/issues/64993

As an asp.net developer I want to trace the startup of my asp.net core app so that I can understand and optimize my startup performance.

### Describe the solution you'd like

Add a Listening event to the HostingEventSource and invoke it near where we log similar messages to ILogger: https://source.dot.net/#Microsoft.AspNetCore.Hosting/GenericHost/GenericWebHostedService.cs,143

**Comment by adityamandaleeka** [comment]
Sounds reasonable to me.

**Comment by adityamandaleeka** [comment]
Done in #40585
