### ISSUE TITLE
Documentation on the steps to create a blazor webasm or server app from scratch

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [dotnet/aspnetcore#40236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create a blazor web assembly or a blazor server app from scratch so that I can then create a custom template.

### Describe the solution you'd like

I would like to see a howto guide on how to create a blazor app from scratch without using the project templates i.e. starting from using the ASP.NET Empty Project. I would like to see this for both Blazor WebAssembly and Blazor Server parts. Becasue there are times when I want to use my own layout and don't want the extra components the project template creates. 

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25006

**Comment by javiercn** [comment]
@dhaanpaa-lab0 thanks for contacting us.

This is not something we plan to provide. We suggest you create a new template and an empty template and review the diff to see the steps involved.
