### ISSUE TITLE
Blazor Server - Ambiguous Routes when changing Base Path

### ISSUE THREAD

**Issue by TomJD** [dotnet/aspnetcore#40243]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a solution, which is currently split in 3 different projects in order to achieve a simulation of micro-frontends.

- Project.Common : This handles the layout for the other two projects. Just a razor class library.

- Project.BlazorServerApp : This is a Blazor Server App with base path let's say pathA

- Project.BlazorServerApp2 : This is a Blazor Server App with base path, let's say pathB

The two Blazor Server Apps have references to Common for their common layout.
BlazorServerApp has reference to BlazorServerApp2 as it will act as a base application for the other smaller apps, and loads the assemblies inside the `App.razor` component.

Each app can also be hosted independently as well, and will run on the start-up base path specified for each one.

However, when running BlazorServerApp with `Index.razor` being `@page "/"` and loading in BlazorServerApp2 with its `Index.razor` also being `@page "/"`, an exception is returned for ambiguous routes.

### Expected Behavior

`BlazorServerApp` starts running on `https://domain/pathA`
`BlazorServerApp2` starts running on `https://domain/pathB`

If `BlazorServerApp` has a component with `@page "/counter"`, this is `https://domain/pathA/counter`
If `BlazorServerApp2` has a component with `@page "/counter"`, this is `https://domain/pathB/counter`

Should not return an exception, as they are running under different base paths

### Exceptions (if any)

System.InvalidOperationException: The following routes are ambiguous:
'/counter' in 'BlazorServerApp.Pages.Index'
'/counter' in 'BlazorServerApp2.Pages.Index'

   at Microsoft.AspNetCore.Components.RouteTableFactory.RouteComparison(RouteEntry x, RouteEntry y)
   at System.Collections.Generic.ComparisonComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)

### .NET Version

,NET 5

**Comment by javiercn** [comment]
@TomJD thanks for contacting us.

Blazor routing doesn't know about the base path in your app, it only knows that there are two pages with a "/" handler. It's not super clear to us how you've configured Blazor routing in your app, but it seems that you are passing both assemblies to the router, hence the router finds both pages and points out the conflict.

**Comment by TomJD** [comment]
Hello @javiercn 

thank you for your reply.

Yes, that is the case, passing down the assembly to the router. I know a fix would be to prefix each page with "/pathA/component", but is there no other way to achieve the same passing this prefix down to the components for that project?

**Comment by javiercn** [comment]
@TomJD there isn't. The routing system only sees your two components with the "/" path and if you add both to the router the routes are ambiguous. It can't know the "global" context. No router for that matter can, as the prefix is not involved in routing.
