### ISSUE TITLE
Can't Use IJSRuntime.InvokeVoidAsync to Call JavaScript Arrow Function

### ISSUE THREAD

**Issue by MarkSky** [dotnet/aspnetcore#40258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use this code to call js
```
ElementReference DivAreaRef;
JSRuntime.InvokeVoidAsync("scrollToBottom", DivAreaRef);
```
If my js code is:
```
function scrollToBottom(divarea) {
            console.log('A');
            divarea.scrollTop = divarea.scrollHeight;
        }
```
It's work.
But If my js code is:
```
const scrollToBottom = (divarea) => {
            console.log('B');
            divarea.scrollTop = divarea.scrollHeight;
        };
```
It's not work.

### Expected Behavior

 If my js code is:
```
const scrollToBottom = (divarea) => {
            console.log('B');
            divarea.scrollTop = divarea.scrollHeight;
        };
```
In the browser devtool sould show "B"

### Steps To Reproduce

In index.razor
```
@page "/"
@inject IJSRuntime JSRuntime
<div style="height: 500px; width: 100%;" @ref="DivAreaRef">Test</div>
<button type="button" class="btn btn-primary" @onclick="ScrollIt">Send</button>

@code {
    ElementReference DivAreaRef;

    vioid ScrollIt()
    {
        JSRuntime.InvokeVoidAsync("scrollToBottom", DivAreaRef);
    }
}
```

In index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>BlazorChatSignalR</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="BlazorChatSignalR.Client.styles.css" rel="stylesheet" />
    <script>
        const scrollToBottom = (divarea) => {
            console.log('B');
            divarea.scrollTop = divarea.scrollHeight;
        };
    </script>
</head>

<body>
    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
</body>

</html>
```

### .NET Version

6.0.200

### Anything else?

ASP.NET Core version: 6.0
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Microsoft Visual Studio Community 2022 (64 位元) - Current Version 17.1.0
Include the output of dotnet --info:
.NET SDK (反映任何 global.json):
 Version:   6.0.200
 Commit:    4c30de7899

執行階段環境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.211 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by campersau** [comment]
Variables defined with `let` or `const` are not automatically defined on `window` / `globalThis` see https://stackoverflow.com/questions/55030498/why-dont-const-and-let-statements-get-defined-on-the-window-object
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/const
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/let

Which means you have the following options:
- use `var` instead.
```js
var scrollToBottom = (divarea) => {
    console.log('B');
    divarea.scrollTop = divarea.scrollHeight;
};
```
- assign the method manual on the `window` / `globalThis`.
```js
const scrollToBottom = (divarea) => {
    console.log('B');
    divarea.scrollTop = divarea.scrollHeight;
};
window.scrollToBottom = scrollToBottom;
```
- define the method directly on the `window` / `globalThis`.
```js
window.scrollToBottom = (divarea) => {
    console.log('B');
    divarea.scrollTop = divarea.scrollHeight;
};
```

**Comment by javiercn** [comment]
@MarkSky thanks for contacting us.

@campersau answer is correct here. The function needs to be available on the global scope. As an alternative you can define a JS module and export the function from the module and use JS interop to import the module, get a reference to it from C# and invoke it.

**Comment by MarkSky** [comment]
Thank you for your help. It work now.
So I have to use global js for IJSRuntime.
