### ISSUE TITLE
Run `startvscode.sh` returns a syntax error

### ISSUE THREAD

**Issue by tatwd** [dotnet/aspnetcore#40250]
When run the script `startvscode.sh` without any args, just like that:
```sh
./startvscode.sh
```
it will returns a syntax error:
```txt
./startvscode.sh: line 23: [: =: unary operator expected
```

Could I send a PR to fix this?

**Comment by javiercn** [comment]
@tatwd thanks for contacting us.

@captainsafia do you know about this?

**Comment by tatwd** [comment]
Maybe, another solution like this?

```diff
-if [ $1 = "" ]; then
+if [ "$1" = "" ]; then
```

**Comment by captainsafia** [comment]
That works as well although I prefer the first variant because it guides the user as to what to do.

**Comment by mkArtakMSFT** [comment]
Looks like this has been addressed by https://github.com/dotnet/aspnetcore/pull/40597
