### ISSUE TITLE
SetCookieHeaderValue - System.TypeLoadException: Could not load type Microsoft.Extensions.Primitives.InplaceStringBuilder'

### ISSUE THREAD

**Issue by joaocpaiva** [dotnet/aspnetcore#40255]
### Description

This API is raising an exception because it cannot find type Microsoft.Extensions.Primitives.InplaceStringBuilder.

This happens both on .NET Framework 4.7.2 as well as .NET 6.0. I tried reference Microsoft.Net.Http.Headers 2.2.8, but the same exception is raised.

#region Assembly Microsoft.Net.Http.Headers, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// D:\Git\AD-AggregatorService-Common\packages\microsoft.net.http.headers\2.2.0\lib\netstandard2.0\Microsoft.Net.Http.Headers.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion

Test method Microsoft.Identity.Services.Http.UnitTest.CookieTest.Cookie_HeaderRoundtripping_Test threw exception: 
System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Stack Trace: 
    SetCookieHeaderValue.ToString()
    Cookie.ToSetCookieHeader() line 115
    CookieTest.Cookie_HeaderRoundtripping_Test(String originalHeader, String expectedHeader) line 33

### Reproduction Steps
```c#
        internal string ToSetCookieHeader()
        {
            SetCookieHeaderValue header = new SetCookieHeaderValue(this.Name, this.Value);
            header.Domain = this.Domain;
            header.Path = this.Path;
            header.MaxAge = this.MaxAge;
            header.Expires = this.Expires;
            header.HttpOnly = this.HttpOnly;
            header.Secure = this.Secure;
            header.SameSite = ConvertSameSiteModeAppToFramework(this.SameSite);

            return header.ToString();
        }
```
### Expected behavior

SetCookieHeaderValue.ToString() should not throw.

### Actual behavior

SetCookieHeaderValue.ToString() raises TypeLoadException.

### Configuration

.NET Framework 4.7.2 and .NET 6

Windows 11, x64

**Comment by eerhardt** [comment]
Transferring to dotnet/aspnetcore to decide if `Microsoft.Net.Http.Headers` NuGet package should be updated to work with the latest Microsoft.Extensions.Primitives versions. If we aren't going to update `Microsoft.Net.Http.Headers`, then please close the issue.

@joaocpaiva - did the above instructions help?

**Comment by davidfowl** [comment]
Most of these packages are dead because everything is included in the shared framework. The right solution is to multi target.

**Comment by joaocpaiva** [comment]
> Most of these packages are dead because everything is included in the shared framework. The right solution is to multi target.

The VS Test project where this fails, is targeting each framework respectively: net6.0 and net472.

The test project depends on another assembly that targets **netstandard2.0** and references Microsoft.AspNetCore.Http 2.2.2 where SetCookieHeaderValue API is available. Do you mean that we should change that assembly to multi-target instead of doing **netstandard2.0**?

**Comment by davidfowl** [comment]
That's right. These assemblies are no longer compatible with ASP.NET Core from 3.0 and above (that's when the move away from .NET Standard happened). https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#migrate-libraries-via-multi-targeting

**Comment by joaocpaiva** [comment]
Ok, I am able to fix for .NET 6 though I can't find a good solution for .NET Framework 4.6.2. Even after target all dependencies to .NET Framework 4.6.2, I still get the exception because InlineStringBuilder cannot be loaded from Microsoft.Extensions.Primitives :|

**Comment by eerhardt** [comment]
> Even after target all dependencies to .NET Framework 4.6.2, I still get the exception because InlineStringBuilder cannot be loaded from Microsoft.Extensions.Primitives

For .NET Framework 4.6.2, make sure you aren't referencing any `Microsoft.Extensions.*` packages with versions greater than 3.0. Make sure all the `Microsoft.Extensions.*` packages are version `2.1.*`. You can check in your "Dependencies" node in VS, or by inspecting the `obj\project.assets.json` file in your project to see which versions are being used.

**Comment by Smartisa** [comment]
> This issue is pretty annoying because it means you can run into problems whenever you pair one of the older packages with a newer version of Microsoft.Extensions.Primitives.
> 
> This situation is relatively easy to get yourself into if you have libraries that need to support .NET Framework and .NET Core, since .NET Framework only works with the older ASP.NET Core 2.x packages which rely on `InPlaceStringBuilder`.
> 
> If the `InPlaceStringBuilder` API had been retained or could be restored it would have (and still could) save us a lot of pain. Seems like it could just be marked as `Obsolete`.

Backward compatibility is a headache. Do you know how to judge whether the version of a package is backward compatible or the API has changed?
Thanks!

**Comment by davidfowl** [comment]
> Do you know how to decide whether the version of a package is backward compatible or the API has changed?

By looking at the API diff or assuming major versions will have breaking changes.

**Comment by halter73** [comment]
Triage: It doesn't look like there's anything left for us to do here.
