### ISSUE TITLE
Enable packages for Mariner 2.0

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/aspnetcore#40253]
We need to enable proper support for Mariner 2.0 with specific DEPS package and new set of '-cm.2' packages.

While we can continue using 1.0 packages short-term, to simplify build and deployment experience, a new set of packages for Mariner 2.0, with '-cm.2' in name, would be needed.

Required work:

- [x] New set of RPM packages, with '-cm.2' in the name
- [ ] Ensure all architectures are covered, including arm64: https://github.com/dotnet/aspnetcore/issues/40252

Main issue for tracking work across dotnet/runtime, dotnet/aspnetcore and dotnet/installer: https://github.com/dotnet/runtime/issues/64756

This is needed for 7.0 and 6.0 servicing.

**Comment by NikolaMilosavljevic** [comment]
I'm looking for your team to complete this work. Do let me know if this requires more info. I am almost done with changes in dotnet/runtime and dotnet/arcade - perhaps some of that work would contribute to enabling experience in this repo.

**Comment by wtgodbe** [comment]
@dougbu we need to have this done in time for April servicing - let's discuss at standup today

**Comment by wtgodbe** [comment]
Still need this for arm64
