### ISSUE TITLE
Error boundaries are not catching all exceptions

### ISSUE THREAD

**Issue by inmistlosted** [dotnet/aspnetcore#40260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When method is using `async void` construction Error boundaries are not able to catch exception inside such method and application will crash.

For example:  If I have a component wrapped with error boundaries and it has such methods inside it, so this code will lead to a crash.

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
        await base.OnAfterRenderAsync(firstRender);

        ThrowError();
}

private async void ThrowError()
{
        await Task.Delay(100);

        throw new Exception("Some exception");
}

```

Is there a way how to prevent app from crashing in this case?
Can you add something, so error boundaries will be able to catch exceptions in `async void` methods?

### Expected Behavior

Crash not happening with error boundaries even if `async void` method had thrown an exception.

### Exceptions (if any)

Error: System.Exception: Some exception
   at TestNet6.Components.ComponentWithError.ThrowError() in C:\Data\Blazor\TestNet6\TestNet6\Components\ComponentWithError.razor:line 47
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

### .NET Version

6.0.101

**Comment by javiercn** [comment]
@inmistlosted thanks for contacting us.

That's known and by design. We don't support `async void`. Our synchronization context does nothing to capture `async void` because the framework support `async` throughout the stack and we recommend returning a Task

**Comment by javiercn** [comment]
@guardrex can we add an explicit statement on the docs (if we don't have it already) to explicitly warn about using async void?

**Comment by inmistlosted** [comment]
@javiercn ok, got it, thank you for your response.

**Comment by guardrex** [comment]
@javiercn Is it nuanced for component updates based on an external event? ... or is the following example incorrectly coded/described? ...

```csharp
private async void HandleTimer(object? source, 
        System.Timers.ElapsedEventArgs e)
```

... in ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#invoke-component-methods-externally-to-update-state

**Comment by javiercn** [comment]
@guardrex that sample needs updating to use the new PeriodicTimer in .NET 6.0 https://docs.microsoft.com/en-us/dotnet/api/system.threading.periodictimer?view=net-6.0

**Comment by guardrex** [comment]
Thanks ... I'll move up the priority on the docs issue to P1 and get on it right after we get this last Blazor Hybrid tutorial (WPF) in place. It's a top priority at the moment, and I'm even *LATE* 🕐🏃 this morning with it.

The sync context section then gets (along with `PeriodicTimer` for 6.0) ...

> Blazor's synchronization context doesn't capture methods marked \`async void\`. The framework supports asynchronous (\`async\`) methods that return a \<xref:System.Threading.Tasks.Task>.

**Comment by javiercn** [comment]
I wouldn't mention the synchronization context, just mention that the framework doesn't track void returning async methods and as a result exceptions will not be caught in those scenarios and they need to change the return type to return a Task

**Comment by guardrex** [comment]
Is the sync context section the right spot then, or should I create a section for this remark?

> \#\# Asynchronous methods (\`async\`) don't support returning \`void\`
>
> The Blazor framework doesn't track \`void\`-returning asynchronous methods (\`async\`). As a result, exceptions aren't caught if \`void\` is returned. Always return a \<xref:System.Threading.Tasks.Task> from asynchronous methods.
