### ISSUE TITLE
HotReload displays WebSocket connection error message in browser console for ASP.NET Core app run in VS2022 but not on dotnet watch run

### ISSUE THREAD

**Issue by ChaosEngine** [dotnet/aspnetcore#40264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HotReload displays:
 
![image](https://user-images.githubusercontent.com/1271428/154291064-4187d04c-f347-4820-81c2-6eb8c6047b66.png)

`WebSocket connection to 'wss://localhost:62139/AppName/' failed:`

message in browser console for ASP.NET Core app run in VS2022. This is happening ONLY in VS2022 (version 17.1.0 ) but not on `dotnet watch run` session. Then all works ok.

This is probably originating from `/_framework/aspnetcore-browser-refresh.js` script. JS stack trace:
```
(anonymous)	@aspnetcore-browser-refresh.js:234 
getWebSocket @aspnetcore-browser-refresh.js:231
(anonymous)	@aspnetcore-browser-refresh.js:15
```

### Expected Behavior

Error should not be displayed and presumably the connection endpoint shoyuld be the same for VS2022 and `dotnet watch run` 

### Steps To Reproduce

Create any dotnet core app (dotnet 6) and enaable hotreload in VS2022. Ctrl+F5 (no debug tun)
Result:
![image](https://user-images.githubusercontent.com/1271428/154292184-864b7c8c-058a-4d40-86eb-42a672ad424b.png)

### .NET Version

6.0.200

### Anything else?

When run from VS2022 I see this as web socket end-point (line 10 in aspnetcore-browser-refresh.js):

```
const webSocketUrls = 'wss://localhost:62139/NoHotReloadWithServiceWorker/,ws://localhost:62140/NoHotReloadWithServiceWorker/'.split(',');
```

when run from `dotnet watch` it is like this:

```
 const webSocketUrls = 'wss://localhost:61215,ws://localhost:61216'.split(',');
```

**Comment by jscarle** [comment]
I can confirm this issue is present on ASP.NET Core, even without Blazor.

When I Debug launch with IIS Express, it opens my project at https://localhost:44385/Portal/.

The following gets appended to the HTML source:
```
<!--StartFragment-->
<!-- Visual Studio Browser Link -->
<script type="text/javascript" src="https://localhost:44399/4f6e351106ba4179b7dcf32b17ac9091/browserLink" async="async" id="__browserLink_initializationData" data-requestId="d2d1e6a926684f3cbccc7a30ca013154" data-requestMappingFromServer="False"></script>
<!-- End Browser Link -->
<script src="/_framework/aspnetcore-browser-refresh.js"></script>
<!--EndFragment-->
```

And the following appears in the JavaScript console:
![Screenshot 2022-02-17 101629](https://user-images.githubusercontent.com/29762210/154512291-7debd719-5400-4137-a0cc-9cd143f02e24.png)

**Comment by tmehreen-corenxt** [comment]
facing the same issue while running blazor client app. VS Version is 17.1
is this due to vs?

**Comment by pranavkm** [comment]
@tmehreen-corenxt, yes it's a VS specific issue.

**Comment by tmehreen-corenxt** [comment]
Is there a workaround? or is the VS time trying to resolve it in near future?

> @tmehreen-corenxt, yes it's a VS specific issue.

**Comment by dazinator** [comment]
> Thanks for reporting this. There's a non-public VS bug that is tracking this - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1481343 which we'll use to resolve this.
> 
> FYI @sayedihashimi / @BillHiebert

Just wondering if this item should be closed? I was just about to open another ticket as I saw this was closed but the issue persists...

**Comment by elgabato** [comment]
Is this issue resolve?

**Comment by sayedihashimi** [comment]
@BillHiebert is there a workaround that can be applied until we can fix this?

**Comment by SH-Engineer02** [comment]
it looks like has been solved after update vs 2022 to version 17.1.5

**Comment by ChaosEngine** [comment]
> it looks like has been solved after update vs 2022 to version 17.1.5

Yes, looks like it. Good job.

**Comment by elgabato** [comment]
Good Job

**Comment by jscarle** [comment]
Confirmed as fixed on my end.

**Comment by jottone** [comment]
This issue persists in VS2022 17.1.3

**Comment by krompaco** [comment]
Still getting this error in Version 17.2.0 with 6.0.300
