### ISSUE TITLE
BACKROUND SERVICE IN ASP.NET CORE

### ISSUE THREAD

**Issue by Timbuktu-Chance** [dotnet/aspnetcore#40266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello ,

I have a web api created in asp.net core 3.1 , i want to be able to process some long running task in a "job like" however without creating a console application or without using a queuing (pub/sub).

How do i achieve this in asp.netcore.

Example
request -> example.com/api/submit_application -> response --> {"message":"thanks you we have recieved your application"}

Function longruningtask submit_application{

check if applicant is valid
check claimtype
check if qualifies
check contact exits
check claim
send email
notify representative
validate claim
log claim in database
............
}

### Describe the solution you'd like

Hello ,

I have a web api created in asp.net core 3.1 , i want to be able to process some long running task in a "job like" however without creating a console application or without using a queuing (pub/sub).

How do i achieve this in asp.netcore.

Example
request -> example.com/api/submit_application -> response --> {"message":"thanks you we have recieved your application"}

Function longruningtask submit_application{

check if applicant is valid
check claimtype
check if qualifies
check contact exits
check claim
send email
notify representative
validate claim
log claim in database
............
}

### Additional context

Capacity for asp.net core to invoke and register background services

**Comment by Tratcher** [comment]
Something like this?
https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services#queued-background-tasks

**Comment by Timbuktu-Chance** [comment]
> Something like this? https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services#queued-background-tasks

Indeed , something like this , however does it apply to aspdotnetcore3.1

**Comment by Tratcher** [comment]
Why not? It should.

**Comment by Timbuktu-Chance** [comment]
Thanks
