### ISSUE TITLE
Some Blazor WebAssembly DLLs are quarantined by anti-virus

### ISSUE THREAD

**Issue by JesperEkenberg** [dotnet/aspnetcore#40283]
Our anti-virus (Cisco Endpoint Security) quarantines some of the Blazor WebAssembly framework files.
We've gotten around the problem initially by disabling the Trimmer feature (PublishTrimmed) but would really like to used it to minimize the footprint of the application.
It seems the problem is that the output DLLs are no longer digitally signed when they have been processed by the Trimmer.

**Comment by javiercn** [comment]
@JesperEkenberg thanks for contacting us.

The dlls can no longer be digitally signed as they are manipulated and the build process doesn't have access to the MS certificate for digitally signing the dlls.

We support completely customizing the deployment process for Blazor Webassembly Applications and we provide an out of the box experimental package that might help you workaround these false positives.

https://devblogs.microsoft.com/dotnet/custom-deployment-layout-for-blazor-webassembly-apps/#using-the-multipartbundle-package

In addition to this, there are other packages developed by the community to solve this and similar problems that you might want to try, or use the steps in the post above to create your own version that works for you.
