### ISSUE TITLE
Visual Studio for mac 运行 net6 mvc 时,The view '···' was not found.

### ISSUE THREAD

**Issue by luuunnn** [dotnet/aspnetcore#40280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当我使用 vs for mac 运行 net6 版本的 mvc 项目时,所有的 view 都无法被找到.
事实上,这些 view 都存在,并且毫无异常.
同一个项目,在 windows 系统上可以正常运行.

### Exceptions (if any)

An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Login' was not found. The following locations were searched:
/Views/Auth/Login.cshtml
/Views/Shared/Login.cshtml

### .NET Version

net6

### Anything else?

VS4Mac latest

**Comment by javiercn** [comment]
Translation
```
When I run the net6 version of the mvc project using vs for Mac, all the views cannot be found.
In fact, these views are present and there are no exceptions.
The same project works correctly on a Windows system
```

**Comment by javiercn** [comment]
@luuunnn thanks for contacting us.

Could you create a minimal repro project as a public github repository so that we can make progress and help determine what's going on?

**Comment by javiercn** [comment]
@luuunnn thanks for the additional details.

Are you running this on an x86 Mac or one of the new M1 Macs

**Comment by luuunnn** [comment]
> @luuunnn thanks for the additional details.
> 
> Are you running this on an x86 Mac or one of the new M1 Macs

您好,下图是我的设备信息截图.
![image](https://user-images.githubusercontent.com/43459241/155253986-5e330ab0-93ae-4772-969c-34aebf4e9dd7.png)

**Comment by javiercn** [comment]
@luuunnn thanks for providing additional details.

While we do our best to look at all issues in a timely manner, we are currently busy with other work and it will take us some time before we can take a more in depth look. 

Thanks you for your patience.

**Comment by luuunnn** [comment]
@javiercn 好的，麻烦各位了！非常感谢！

**Comment by luuunnn** [comment]
@javiercn 您好,补充说明一点:虽然我无法使用 VS4Mac 运行该项目,但是却可以使用 dotnet run 命令成功运行该项目.
希望这条信息可以帮助你们定位问题.

**Comment by javiercn** [comment]
@luuunnn I gave your repro a try using the latest VS4Mac and the issue seems to have been resolved.

Are you using the VS4Mac preview? (That's the one that has support for .NET 6.0)

**Comment by javiercn** [comment]
@luuunnn I'm not able to reproduce the issue with the latest VS4Mac preview

**Comment by javiercn** [comment]
Great, I'm going to consider this as resolved then.

Thanks again for reporting the issue and providing all the details.

**Comment by luuunnn** [comment]
非常感谢你们的帮助,vs 和 dotnet 都是很好的产品.感谢各位的努力奉献!
