### ISSUE TITLE
Add support for passing Metadata Seed to the underlying oidc-client in WASM Authentication

### ISSUE THREAD

**Issue by Hawxy** [dotnet/aspnetcore#40286]
## Summary

Some third-party OIDC vendors are not conformant with OIDC's session management and do not return a `end_session_endpoint` from the OIDC configuration endpoint, yet still need a redirect to occur as part of the logout flow. A large vendor impacted by this is Auth0, with logouts in Blazor not acting correctly as a hook does not exist to time this redirect properly. This issue is outlined in #40046. 

When `oidc-client-js` is implemented in isolation with Auth0, the usual answer is to set the `end_session_endpoint` property on the `metadataSeed` setting, which is then merged with the metadata coming from Auth0's configuration. The `oidc-client` will then redirect as expected during a logout. I've tested that this resolves the problem via my own workaround, and I propose the same solution here.

## Motivation and goals

- Unblocks the use of Auth0 with Blazor WASM for production scenarios
- Permits the setting of default metadata for other providers

## Examples

```cs
builder.Services.AddOidcAuthentication(options =>
{
    // ....
    var authority = builder.Configuration["Auth0:Authority"];
    var clientId = builder.Configuration["Auth0:ClientId"];
    options.ProviderOptions.AdditionalMetadata.EndSessionEndpoint = $"{authority}/v2/logout?client_id={clientId}&returnTo={builder.HostEnvironment.BaseAddress}";
});
```

## Detailed design

I'm not sure about the name `AdditionalMetadata` (maybe `DefaultMetadata`, or `SeededMetadata`?).

My proposal is to map out some or all of the fields on the [oidc-client-js metadata interface](https://github.com/IdentityModel/oidc-client-js/blob/dev/index.d.ts#L525) :

```diff
namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication;

public class OidcProviderOptions
{
+    [JsonPropertyName("metadataSeed")]
+    public OidcMetadata AdditionalMetadata { get; set; } = new ();
}


+ public class OidcMetadata
+ {
+    [JsonPropertyName("end_session_endpoint")]
+    public string EndSessionEndpoint { get; set; } = null!;

+    [JsonPropertyName("userinfo_endpoint")]
+    public string UserInfoEndpoint { get; set; } = null!;

     //cont ...
+}
```
The remote metadata takes precedence over the seeded metadata so there isn't a massive risk with writing a bunch of null values, but it might be worth avoiding any unintended side effects via `JsonIgnoreCondition.WhenWritingNull`.

**Comment by javiercn** [comment]
This is already possible today. 

Here is an example https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#pass-custom-provider-options

**Comment by Hawxy** [comment]
@javiercn It's been a while since I last looked at this and yes that does work, but it also results in the `IPostConfigureOptions` not being registered unlike the usual `AddOidcAuthentication` call. So`RedirectUri`, `PostLogoutRedirectUri` & `UserOptions.AuthenticationType` all need to be manually set, which isn't mentioned in the doco. I'll consider this covered given there's two different workarounds anyways.
