### ISSUE TITLE
Identity: email confirmation codes are case sensitive

### ISSUE THREAD

**Issue by vborovikov** [dotnet/aspnetcore#40285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using the code generated by Identity scaffolding in VS 2022.
 
This is how the confirmation code is created:
```cs
var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
var code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(token));
```
This is how the code is confirmed:
```cs
var token = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
var result = await _userManager.ConfirmEmailAsync(user, token);
```

If the web app configuration enables lowercase URLs and query parameters, i.e.
```cs
services.Configure<RouteOptions>(options =>
{
    options.LowercaseUrls = true;
    options.LowercaseQueryStrings = true;
});
```
then the confirmation codes cannot be properly decoded.

### Expected Behavior

Confirmation codes must be case insensitive.

### Steps To Reproduce

Generate a ASP.NET 6 web app with Identity authentication and individual accounts enabled. Modify `RouteOptions` to lowercase URLs and query parameters. Try register a new account in the app and then confirm the account email by following the link from the confirmation email. you'll get the message "Error confirming your email.".

### .NET Version

6.0.102

**Comment by blowdart** [comment]
Base64 cannot be base insensitive.

@HaoK / @pranavkm is there a way for an endpoint to say "I don't care about what you configured, this endpoint must have case sensitivity"? That would be the correct solution here

**Comment by adityamandaleeka** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/13838

Is there a way to prevent an individual route from having query string lowercased?

**Comment by javiercn** [comment]
@adityamandaleeka there's already a way to do this.

https://docs.microsoft.com/es-es/dotnet/api/microsoft.aspnetcore.routing.linkgeneratorroutevaluesaddressextensions.getpathbyroutevalues?view=aspnetcore-6.0#microsoft-aspnetcore-routing-linkgeneratorroutevaluesaddressextensions-getpathbyroutevalues(microsoft-aspnetcore-routing-linkgenerator-microsoft-aspnetcore-http-httpcontext-system-string-system-object-system-nullable((microsoft-aspnetcore-http-pathstring))-microsoft-aspnetcore-http-fragmentstring-microsoft-aspnetcore-routing-linkoptions)

Not sure the code in Identity that is using it, but you can pass in explicit options that will override the globals. You might nee to switch from UrlHelper to LinkGenerator, but it should be trivial.

**Comment by adityamandaleeka** [comment]
Thanks @javiercn. Sounds like people who are using the LowercaseQueryStrings option can scaffold out the pages and customize this using that API.

**Comment by adityamandaleeka** [comment]
@pranavkm Is there a way to easily set this setting per route?

**Comment by adityamandaleeka** [comment]
Thanks @javiercn . Closing this issue since there's a workaround that can be used.
