### ISSUE TITLE
Custom icon is not getting set in visual studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40289]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Custom-icon-is-not-getting-set-in-visual/1665350)._

---
I wanted to display custom icon for my MVC application (Visual studio 2019) . I created an icon of size 32*30 and used it in my _layout.cshtml <head> tag as follows:

```
<link rel="icon" type="image/x-icon" href=@Url.Action("~/customicon.ico") />
```

But, this icon is not getting displayed in any of the browsers. Only the standard browser icons are getting displayed.
Since , this was not working, I cleared cache of browser and all other temporary folders. Still, it is not working.

If I use this same icon in Visual studio 2017, it works fine.

---
#### Feedback Bot on 2/15/2022, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/15/2022, 01:19 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Can you check the generated HTML to see what the value for the href on the link tag is?

It seems that you are trying to create a link to a file. Based on that, don't you mean:
```
<link rel="icon" type="image/x-icon" href=@Url.Content("~/customicon.ico") />
```
in your app?

If none of those things work, could you please create a minimal repro project as a public github repository so that we can make progress?
