### ISSUE TITLE
Razor in CSS preprocessor support 

### ISSUE THREAD

**Issue by dorthl** [dotnet/aspnetcore#40281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I try to use gulp less preprocessors and in the project configure
```
<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
  <Exec Command="echo Output written to $(TargetDir)" />
  <Exec Command="node --version" ContinueOnError="true">
	  <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
  </Exec>
  <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
  <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." Condition="!Exists('$(SolutionDir)node_modules')"  />
  <Exec WorkingDirectory="$(SolutionDir)" Command="npm install" Condition="!Exists('$(SolutionDir)node_modules')" />
  <Exec WorkingDirectory="$(SolutionDir)" Command="npm run gulp:pro" />
</Target>
```
to join the dotnet build process.
What I envision is to generate .css files for CSS isolation before Blazor compiles.
But in practice even if the css file has been generated ,{ASSEMBLY NAME}.styles.css file but not.
Visual Studio Task Runner Explorer or Delegate.SassBuilder are not feasible in cross-platform scenarios.

### Describe the solution you'd like

Looking for a way to have CSS preprocessor support in the Blazor build process

**Comment by javiercn** [comment]
@dorthl thanks for contacting us.

We have an experimental package to make this easier to achieve. You can check the details [here](https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/)

**Comment by dorthl** [comment]
@javiercn thanks 
I tried to reference the package MicrosoftAspNetCore.ClientAssets, but there is a problem.
Create the [assets] folder [package.json] file in the project as follows.
```
{
    "name": "project ",
    "version": "1.0.0",
    "scripts": {
        "gulp": "gulp",
        "build:Debug": "gulp --gulpfile ../gulpfile.js",
        "build:Release": "gulp --gulpfile ../gulpfile.js"
    },
    "dependencies": {
        "antd": "^4.16.0"
    },
    "devDependencies": {
        "gulp": "^4.0.2",
        "gulp-clean-css": "^4.3.0",
        "gulp-concat-css": "^3.1.0",
        "gulp-less": "^5.0.0",
        "gulp-rename": "^2.0.0",
        "gulp-sourcemaps": "^3.0.0",
        "gulp-uglify": "^3.0.2",
        "husky": "^7.0.4",
        "less-plugin-npm-import": "^2.1.0",
        "vinyl-buffer": "^1.0.1",
        "vinyl-source-stream": "^2.0.0"
    }
}
```
There is a problem with executing npm run gulp after npm install.
```
[10:51:14] Local gulp not found in 'ProjectPath'
[10:51:14] Try running: npm install gulp
```
I think it's because node_modules is in assets folder.
The role of gulp is to generate CSS preprocessor css files based on less.
Is there a compatibility issue with this?

**Comment by dorthl** [comment]
@javiercn
