### ISSUE TITLE
Reopen of #40132

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/aspnetcore#40292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Reopen plesae #40132

### Describe the solution you'd like

Reopen plesae #40132

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @ParadiseFallen.
We'll re-triage the issue you've raised earlier and get back to you.
