### ISSUE TITLE
AddRazorRuntimeCompilation Error

### ISSUE THREAD

**Issue by shaair** [dotnet/aspnetcore#40291]
**Describe the bug:**
My project base on net6.0 is working fine but when i added serivce. One thing i noted that issue come in IIS only and at IISExpress and Seflhost running fine.

services.AddRazorPages().AddRazorRuntimeCompilation();
Or
services.AddMvc().AddRazorRuntimeCompilation();
Or
services.AddControllersWithViews().AddRazorRuntimeCompilation();

everywhere i tried but after register getting error
![image](https://user-images.githubusercontent.com/3183215/154418779-4f32d5cb-f425-41bb-a0b4-34a211f24dde.png)

**Version used:**
e.g. VS2022 17.0 Preview 1

**Comment by SteveSandersonMS** [comment]
cc @pranavkm

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're looking to addressing this as part of 7.0, given that there is a workaround available for 6.0: https://github.com/dotnet/aspnetcore/issues/38892

**Comment by shaair** [comment]
> Thanks for contacting us. We're looking to addressing this as part of 7.0, given that there is a workaround available for 6.0: #38892

Thank you . yes issue has been resolved .
