### ISSUE TITLE
Add RenderFragment-like functionality to pure partials and view components in pure Razor SST

### ISSUE THREAD

**Issue by michalsznajder** [dotnet/aspnetcore#40299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently it is hard to easily pass HTML content into partial or custom component in Razor Pages or MVC scenarios. If you want to create a server side rendered component for box with header only way is to write custom tag helper. 

Razor Components (available with [Component Tag Helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-6.0) with static rendering are not a solution since they don't support HtmlHelper and Tag Helpes (so no linking via `asp-page` or no antiforgery protection in forms). 

### Describe the solution you'd like

Solution proposed in https://github.com/dotnet/aspnetcore/issues/4901 would be a good start. There is even example implementation in https://github.com/rdlaitila/AspNetCore.Mvc.ViewComponentSlots.

### Additional context

Idea for this comes from Ruby on Rails where you can easily create HTML based components by using partial. See [3.4.2 Using Partials to Simplify Views](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials-to-simplify-views) section from Rails manual.

See also https://andrewlock.net/dont-replace-your-view-components-with-razor-components/ for some problems when tryign to convert from View Component into Razor Component.

**Comment by seangwright** [comment]
I created this same feature request (referencing #4901) before the ASPNET Core 7 roadmap was defined
https://github.com/dotnet/aspnetcore/issues/37434

I'd love to see this feature.

**Comment by michalsznajder** [comment]
I am also on server side rendering only camp. By using Turbo from Rails 7 I can have pretty responsive app without all the burden of complicated JS frameworks or Blazor.

What I am missing is easy way to reuse render code in templates.

**Comment by seangwright** [comment]
MVC has never had a component model (like Web Forms or Blazor do), so HTML composition in the ways mentioned above has always been difficult/impossible 😖.

If static Blazor is meant to eventually replace classic MVC/Razor Pages style Razor rendering then we'd at least get a component model for our SSR HTML. Otherwise we need something like View Component slots to keep our Razor templates well factored and organized.

**Comment by danroth27** [comment]
We think we will enable this with components as part of https://github.com/dotnet/aspnetcore/issues/6348

**Comment by seangwright** [comment]
@danroth27 Does this mean developers that are building aspnetcore sites serving server-rendered HTML with View Components and Tag Helpers could weave them in with Razor Components for additional server-rendering flexibility?

Would this solution require any aspects of Blazor WASM or would enhanced Blazor server-side rendering be usable without the client-side aspect?

**Comment by danroth27** [comment]
> Does this mean developers that are building aspnetcore sites serving server-rendered HTML with View Components and Tag Helpers could weave them in with Razor Components for additional server-rendering flexibility?

Yup, that's the idea. Lots of details to work out though, so this could change.

> Would this solution require any aspects of Blazor WASM or would enhanced Blazor server-side rendering be usable without the client-side aspect?

We already have a component tag helper that supports pure server-side rendering via RenderMode.Static, whichout involving Blazor Server or Blazor WebAssembly. The idea is to more deeply integrate using Blazor components for server-side rendering.
