### ISSUE TITLE
[7.0 preview 1] HTTP DELETE sometimes treated as HTTP POST

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#40301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a bit of a weird one, and I'm not sure _exactly_ what's at fault, but code that works fine with ASP.NET Core 6 is not working _some of the time_ with ASP.NET Core 7 preview 1.

Testing a sample app of mine with preview 1 is getting test failures in UI tests that attempt to delete items from a Razor Pages UI using some Minimal API endpoints. The upgrade PR illustrating the issue is here: martincostello/dotnet-minimal-api-integration-testing#257.

Some UI tests fail in GitHub Actions on Linux and Windows, but none of the UI tests on macOS do.

Debugging this locally on my Windows 11 laptop, I've been able to fairly reliably repo the issue with Firefox but not with Chrome.

The behaviour is that attempting to delete a _second_ Todo item from the application via the UI fails with an HTTP 400 error, which appears to be coming from anti-forgery.

Turning up logging and looking at the Network tab in Firefox appears to show that the second HTTP DELETE request from the browser is being interpreted by the app as an HTTP POST, which then doesn't match the Minimal API delete endpoint, and then goes through into MVC, where it then hits anti-forgery because there's no request token.

MVC blocking the request due to the missing token makes sense, but the sample app shouldn't be getting that far, as it should be just going to the Minimal API's delete endpoint.

Specific lines from the application logs that are interesting are shown below, with the full logs at the bottom of this issue.

First working request for the HTTP DELETE:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 DELETE https://localhost:5001/api/items/dcd544d4-ff5a-4828-ad35-a6420acec150 - -
<snip>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 DELETE https://localhost:5001/api/items/dcd544d4-ff5a-4828-ad35-a6420acec150 - - - 204 - - 215.2596ms
```

Second failing request for the HTTP DELETE:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2 - -
trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
      All hosts are allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint '405 HTTP Method Not Supported'
<snip>
trce: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[2]
      Authorization Filter: Before executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "RequestVerificationToken" is not present.
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
trce: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Authorization Filter: After executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
<snip>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2 - - - 400 0 - 46.7893ms
```

## Screenshot showing the two HTTP DELETE calls

![image](https://user-images.githubusercontent.com/1439341/154684635-ea6ebedd-9825-4817-8dcc-0c07c77b0c7b.png)

## Application logs

[delete-fails-logs.txt](https://github.com/dotnet/aspnetcore/files/8097262/delete-fails-logs.txt)

### Expected Behavior

The HTTP DELETE succeeds.

### Steps To Reproduce

* Clone martincostello/dotnet-minimal-api-integration-testing@8e09b89d7d3699deeb21688adaec1f3ca85e1dfe
* [Configure GitHub auth secrets](https://github.com/martincostello/dotnet-minimal-api-integration-testing/tree/8e09b89d7d3699deeb21688adaec1f3ca85e1dfe#debugging)
* Run the application
* Navigate to `https://localhost:5001` in Firefox
* Create two new Todo items
* Delete the two Todo items - the second delete should fail

### .NET Version

7.0.100-preview.1.22110.4

**Comment by martincostello** [comment]
I'm not sure exactly what is wrong, but debugging this locally this seems to be an issue with HTTP/2 in Kestrel. It seems to be ""remembering"" the HTTP method from somewhere, and then using `POST` instead of the `DELETE` from the request, causing the eventual request failure.

If I disable HTTP/2, my tests all pass again.

```csharp
builder.WebHost.ConfigureKestrel(
    options => options.ConfigureEndpointDefaults(
        defaults => defaults.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1));
```

See https://github.com/martincostello/dotnet-minimal-api-integration-testing/pull/257/commits/5952920a729e0a7946d5a81bfa3c7d7c16011dc1.

Looking at the commit history, I wonder if it's something related to #38581 and/or #38834?

**Comment by martincostello** [comment]
I've reached the limit of my understanding of HTTP/2 now, but seems that for some reason the code thinks it needs to use `HeaderType.Dynamic` for index `3` (which are `:method` and `POST`), instead of using the literal value submitted in the request (which are `:method` and `DELETE`).

![image](https://user-images.githubusercontent.com/1439341/154844753-262a33e7-b155-4708-84cf-811efa1936db.png)

https://github.com/dotnet/aspnetcore/blob/3e6a9ea08460d8666b13b1f4750c50e8eb323940/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L655-L659

**Comment by adityamandaleeka** [comment]
Thanks for the detailed report @martincostello. We'll take a look.

**Comment by Tratcher** [comment]
@martincostello in case we have trouble reproducing this, can you capture kestrel connection level logs (after UseHttps decryption)? That should show us the RAW HTTP/2 bytes received and enable us to craft a manual repro.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#connection-logging

**Comment by adityamandaleeka** [comment]
@Tratcher I've got a repro of this.

**Comment by martincostello** [comment]
Full logs from a repro session attached below. The request that fails is on line 8801.

[dotnet-aspnetcore-issue-40301.txt](https://github.com/dotnet/aspnetcore/files/8124923/dotnet-aspnetcore-issue-40301.txt)

Captured with this configuration:

```csharp
builder.WebHost.ConfigureKestrel((context, serverOptions) =>
{
    serverOptions.Listen(IPAddress.Any, 5000, listenOptions =>
    {
        listenOptions.UseConnectionLogging();
    });
    serverOptions.Listen(IPAddress.Any, 5001, listenOptions =>
    {
        listenOptions.UseHttps();
        listenOptions.UseConnectionLogging();
    });
});
```

**Comment by adityamandaleeka** [comment]
@martincostello Thanks again for filing this issue.

In short, in cases where we are supposed to be using the HPACK static table for just the name of the header and not the value, we are accidentally using both.

For instance, in this particular case, the :method header hits `OnHeaderCore` with the value `DELETE` and the static table index for :method POST (https://datatracker.ietf.org/doc/html/rfc7541#appendix-A). This is fine, and we have a codepath that should take care of this:

https://github.com/dotnet/aspnetcore/blob/b1df1de3f1982a2f60a19e25cfed6cd6cced7bf6/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L1442

The bug is that we are incorrectly passing `indexOnly: true` here:

https://github.com/dotnet/aspnetcore/blob/b1df1de3f1982a2f60a19e25cfed6cd6cced7bf6/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L1446

which tells the HttpStream logic to disregard the value and just use the name and value from the static table, which is obviously incorrect.

I will send a PR for this soon. The fix is easy but adding a test is a bit tricky; we'll need to make some changes in our HTTP/2 test code to be able to exercise use of the dynamic table this way.

**Comment by martincostello** [comment]
@adityamandaleeka Thanks for the explanation of the root cause - I'm not familiar with HPACK so I was lost in the context of what it should or shouldn't be doing with respect to HPACK when I tried debugging it myself 😄

**Comment by adityamandaleeka** [comment]
Reopening to get this into Preview 2.

**Comment by adityamandaleeka** [comment]
Merged into Preview 2 with https://github.com/dotnet/aspnetcore/pull/40460
