### ISSUE TITLE
ILogger/ILoggerProvider is unable to log general exceptions

### ISSUE THREAD

**Issue by sykesbPragmatics** [dotnet/aspnetcore#40308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I personally find the logging documentation for Blazor WASM extremely limited: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-6.0

But I have succeeded in implementing an ILoggerProvider which is sending logs successfully to my backend API but with one glaring omission: errors trapped in the browser log are never called/logged by the ILoggerProvider.  Its possible that I have this configured wrong and would definitely like to solve the problem.  I have the following loglevels set:

options.LogLevels.Add(LogLevel.Information);
    options.LogLevels.Add(LogLevel.Warning);
    options.LogLevels.Add(LogLevel.Error);
    options.LogLevels.Add(LogLevel.Trace);
    options.LogLevels.Add(LogLevel.Critical);

Items such as information always work, and if I enable debug that works as well.  However if i set up a scenario that creates a crash condition that is not wrapped by a try/catch the UI updates with the nice bar at the bottom saying an exception has occurred, it shows up in the browser console log but the LoggerProvider is never notified.

### Expected Behavior

If an exception occurs that appears in the browser's console log the ILoggerProvider should also be called with the exception.

### Steps To Reproduce

Add a LoggerProvider to a blazor wasm app and create a crash scenario.  The browser's console shows the error but it is never logged to the LoggerProvider. 

### .NET Version

6.0.200

**Comment by pranavkm** [comment]
@sykesbPragmatics are you using an `ErrorBoundary`  component in your app? You might be running in to https://github.com/dotnet/aspnetcore/issues/39039

**Comment by sykesbPragmatics** [comment]
No I have not implemented one yet, working on cross cutting concerns.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SteveSandersonMS** [comment]
> create a crash scenario.

Can you give exact details on how you are doing that?

**Comment by javiercn** [comment]
@sykesbPragmatics thanks for the additional details.

I took a quick look at the code and couldn't see any issue. We are calling the logger at the place where these errors appear. The text you pasted is coming from the logger:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: This is a test
```

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs#L121

Based on this, it seems that something in your app/logger provider might not correctly configured.

Does your logger ever get called?

**Comment by sykesbPragmatics** [comment]
If I inject a logger:

```
 [Inject]
 public ILogger<ComponentTypeName> Logger {get; set;} = default!;
```

and then call this in the same spot within the OnInitializedAsync:
```
Logger.LogError("This is a test!");
```` 

I end up with a logged error all the way down to my database (through the logging provider and then to the rest api which calls a custom logging controller, then to the db etc).

More than anything I wanted to make sure this was not expected behavior.  I suspect I have something misconfigured but at a loss what it could be since everything else seems to be working.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue.
We have a end to end test which uses custom logger and doesn't run into this problem. Can you see how we've implemented it and maybe you can find something that you're doing wrong:
- https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/ErrorComponent.razor
- https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/Program.cs#L45-L46

If not, we'll need a minimalistic repro project (ideally a GitHub repo) that illustrates the problem so that we can investigate this further.

**Comment by sykesbPragmatics** [comment]
Ok I found the problem.  No issue with the wasm logger itself, but several related items that MIGHT be worth a look/change.

So it turns out that the issue was not in the ILoggerProvider but the fact that you cannot properly serialize an Exception object and send it to a REST API.  The Logger was calling the RestClient via "PostAsJsonAsync", which is the OTHER problem as the Log function is synchronous and I blindly used the  PostAsJsonAsync method and the error was being eaten even inside a try/catch block and nothing was showing up in the console.

So here is the REAL problem.  How do you use an async httpClient from within synchronous Blazor ILogger.Log function?  Simply calling the PostAsJsonAsync WORKS if you accept the fact that any errors that might occur with the call (say authentication failed..) are going to be eaten and completely invisible.  

That said this (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#no-asynchronous-logger-methods) article basically states (correctly) "Logging should be so fast that it isn't worth the performance cost of asynchronous code".  

I'm basically going to have to build a wasm background worker service to store the logs and push them to the API service to fix this the RIGHT way:
https://stackoverflow.com/questions/67619072/periodic-background-task-in-blazor-wasm

**Comment by sykesbPragmatics** [comment]
@mkArtakMSFT Recommend updating the Blazor logging documentation to note that if the user wishes to send the logs to a server-side target there is the danger of using an HttpClient inside the ILogger.  It might also be good to suggest a background job or even PROVIDE a best-practice mockup.

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-6.0

**Comment by javiercn** [comment]
@sykesbPragmatics Your assessment is correct.

However I don't think I agree with the conclusions:
* Using synchronous code for logging is an explicit design decision of the system as it is a perf critical code path.
* You can look at how other implementations do this, but in essence, they buffer the log calls and send/write logs in batches.

You can probably look at something like serilog or similar to see what they do in this scenario.

**Comment by javiercn** [comment]
> @mkArtakMSFT Recommend updating the Blazor logging documentation to note that if the user wishes to send the logs to a server-side target there is the danger of using an HttpClient inside the ILogger. It might also be good to suggest a background job or even PROVIDE a best-practice mockup.

This is out of the scope of Blazor and not something we would likely document here. It would be something more suited for Microsoft.Extensions.Logging. Blazor pretty much piggybacks on that infrastructure

**Comment by sykesbPragmatics** [comment]
@javiercn Agreed.  I'm just trying to avoid other developers falling into the same pit I did.  We have all the logging libraries (serilog, NLog) to fall back on from the server side but those libraries are still updating to integrate into Blazor/wasm and the documentation/best practices are difficult to find if they aren't associated with the primary microsoft documentation.  I spent a good bit of time trying to find a turnkey solution for what I eventually wrote on my own, perhaps my google-fu was not good enough :)  Until those turnkey solutions are available at least providing some links to best practices and things to watch out for would be good.  (I'm thinking of the Unit Testing [docs ](https://docs.microsoft.com/en-us/aspnet/core/blazor/test?view=aspnetcore-6.0))

Do you have any examples of "other implementations" in the Blazor/wasm area.  I saw [this](https://nblumhardt.com/2019/11/serilog-blazor/) serilog example but mostly skipped it because it depended on having serilog implemented on the server side but I think i'm going to have to seriously consider using it now.
