### ISSUE TITLE
Blazor: Improve the way data-* can be passed to a component

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/aspnetcore#40300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A component is not guaranteed to generate an html element but in most scenario it happens.
Actually there is a way to allow a component to allow to receive undefined explicit parameters, by using `CaptureUnmatchedValues `property of `ParameterAttribute`.

This mechanism is sub-optimal because you can't for instance filter which attributes you'll get, it's a "catch'em all"

For advanced scenario, using a data-* attribute is very useful, the problem is that we have either to explicit define all the different attributes we want to get with explicit properties like

`[Parameter] public string DataTarget { get; set; }`
```
<div data-target="@DataTarget">
</div>
```

or we just rely on the CaptureUnmatchedValues where we can just splat the dictionary into the div @attributes 

Since data-* attributes are very useful to extend a component behavior by making use of the element dataset (e.g. to alter the DOM in javascript or let another component to attach event handlers to the DOM), the component creator doesn't know which data- attribute the component user needs and so the component user is forced to wrap the component in an html element and apply the data attribute there (being it a limiting factor).

would be helpful to have a way to allow a component to receive any `data-*` attribute and not everything.

### Describe the solution you'd like

I can think about 2 solutions:
being able to automatically register data-attributes in ComponentBase, that would have a new exposed property 
`public Dictionary<string, object> DataAttributes { get; set; }`

or allow to further configure the ParameterAttribute to explicit set the subset of attributes we are interested in catching (maybe using regex expression or tailoring this explicitly for data-* .

`[Parameter( CaptureDataAttributes = true) ] public Dictionary<string, object>DataAttributes { get; set; }`

The binding example could then have a way to bind all data attributes by using a syntax like
`@attributes:data`, `@data`, `@data-attributes`  or any other syntax that may have sense

```
<div @attributes:data="@DataAttributes">
</div>
```

Thanks

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. It might be possible to do this already by defining your own helper method, e.g.:

```razor
<div @attributes="@AllUnmatched.WithDataPrefix()">
</div>

@code {
    [Parameter(CaptureUnmatchedValues=true)] public IDictionary<string, object> AllUnmatched { get; set; }
}
```

... where `WithDataPrefix` is an extension method on `IDictionary<string, object>` that returns an enumerable of keyvalue pairs, filtering on the key name to pick out those starting with `data-`.

Similarly you could define an extension method called `WithoutDataPrefix` if you want all the others.

Would this meet your needs?

**Comment by MithrilMan** [comment]
Thanks for the reply.
Filtering is for sure a way even if being able to narrow down which "unmatched values" the component designer allows would be better.

Being able to split data-attributes from all other unmatched attributes is a pros because allows a `component designer`  to let the user extend the behavior of a component (e.g. by using the html `dataset` in javascript) while at the same time it protects the `component user` from specifying other unmatched properties.

At the same time I'm still thinking if the concept of data attributes (that's actually a data _bag_) could be promoted to a ComponentBase concept (or a hypothetical `ComponentBaseDataAware` class) that would allow a component user to "attach data" to components that aren't designed explicitly to carry these external data.

Of course I'm free to create such a base class in my project, I'm thinking out loud if this could benefit Blazor framework itself (at the end this is similar to the [IFeatureCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ifeaturecollection?view=aspnetcore-6.0) concept that some aspnetcore classes already implement.

Thanks
