### ISSUE TITLE
Similar to MarkupString but for custom components.

### ISSUE THREAD

**Issue by Said1996** [dotnet/aspnetcore#40311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a requirement to make an App where user can fill a page with components, customize them as he like, and then be able to save that state in a database.
I am aware of Dynamic Components but saving such thing in database is troublesome opposing to just creating everything as a string and saving as a string in database, retrieving as a string etc... you get the idea.

### Describe the solution you'd like

A way to create components at runtime using string.

**Comment by javiercn** [comment]
@Said1996 thanks for contacting us.

This is not a direction we plan to go in the near future. This would require the runtime to parse and evaluate Razor code at runtime, which is not something we plan to do.
