### ISSUE TITLE
blazor wasm using new Claim("roles", role) cause @attribute [Authorize(Roles = "admin")] not work

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/aspnetcore#40314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello , when I use new claims.Add(new Claim(ClaimTypes.Role, role)); @attribute [Authorize(Roles = "admin")] and AuthorizeView Roles="admin" works correctly. But when I use claims.Add(new Claim("roles", role)); AuthorizeView(Roles="admin") doesn't work and show an error in browser console:

"RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (admin)"

I tested options.TokenValidationParameters.RoleClaimType = "roles"; in AddIdentity() and RoleClaimType = "roles" in TokenValidationParameters but those don't work.

How can we use our "roles" key instead of ClaimTypes.Role?

My project is here : http://github.com/mammadkoma/Attendance

### Expected Behavior

Don't show FetchDate link in nav menu for user role and show for admin role.

### Steps To Reproduce

http://github.com/mammadkoma/Attendance

### Exceptions (if any)

Browser console error : "RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (admin)"

### .NET Version

.net 6.0.200

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0

**Comment by MariovanZeist** [comment]
Hi @mammadkoma 
The ``<AuthorizeView Roles="Admin">`` will specifically look at claims of type ``ClaimTypes.Role``  which eqauls to "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" to see if there is a match. 
You can't use that to lookup claims of your own claim type called "roles"

The way to get it working is by using Policies.


For example when you register the following Policy (``IsAdmin``):
```cs
  //For Blazor server use:
  services.AddAuthorization(config =>
  {
    config.AddPolicy("IsAdmin", policy => policy.RequireClaim("roles", "admin"));
  });
  
  //For Blazor Wasm use:
  services.AddAuthorizationCore(config =>
  {
    config.AddPolicy("IsAdmin", policy => policy.RequireClaim("roles", "admin"));
  });
```

You can then use AuthorizeView as follows ``<AuthorizeView Policy="IsAdmin">`` to see if the user is an administrator.

[Additional information](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0#role-based-and-policy-based-authorization)

**Comment by mammadkoma** [comment]
Hello and thank you @MariovanZeist
I Used your code and getting error in console:
"crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The AuthorizationPolicy named: 'admin' was not found.
System.InvalidOperationException: The AuthorizationPolicy named: 'admin' was not found."
![image](https://user-images.githubusercontent.com/17564001/154829735-e6164657-4477-4612-8aff-fbd39d673ca6.png)
![image](https://user-images.githubusercontent.com/17564001/154829746-f2f1d96f-b67e-4043-9766-d6eb74d8f8f3.png)
![image](https://user-images.githubusercontent.com/17564001/154829755-9de5845d-313b-4457-bcd0-932afaad4b93.png)

**Comment by MariovanZeist** [comment]
@mammadkoma 
You might have put the code in the wrong project.
Looking at your code it seems that you added 
```cs
builder.Services.AddAuthorizationCore(config =>
{
    config.AddPolicy("IsAdmin", policy => policy.RequireClaim("roles", "admin"));
});
```
to your ``Attendance.Server`` project, but you should add it to your ``Attendence.Client`` project.

In your ``Attendance.Client`` project int``program.cs`` there is already a line 
```cs
 builder.Services.AddAuthorizationCore()
```
replace that with the lines above.

**Comment by mammadkoma** [comment]
Thank you @MariovanZeist
After adding config.AddPolicy("admin", policy => policy.RequireClaim("roles", "admin")); to AddAuthorizationCore() in program.cs of **client** project , <AuthorizeView Policy="admin"> and @attribute [Authorize(Policy = "admin")] works correctly.
Wish we could use the same Roles = , but thanks again.

**Comment by MariovanZeist** [comment]
@mammadkoma after reading your question again, I think I misread your question. 
If you want to use "roles" so you can use it as ``<AuthorizeView Roles='admin'> `` you could modify your ``AuthStateProvider`` class 

change :
```cs
  new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(ParseClaimsFromToken(token), "jwtAuthType")))
```
to
```cs
  new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(ParseClaimsFromToken(token), "jwtAuthType", ClaimTypes.Name , "roles")))
```

**Comment by mammadkoma** [comment]
Thank you very mauch
It was that we want.

But there is a security tip : when we guard a menu in navmenu.razor by Role= and user is not admin , browser console shows the required role : "RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (admin)"

**Comment by MariovanZeist** [comment]
@mammadkoma 
These messages are shown because the default Loglevel in Blazor Wasm apps is ``Loglevel.Information`` 
You can change this by lowering the LogLevel to ``LogLevel.Warning`` 

Add this line to your ``Program.cs`` in your client application

```cs
  builder.Logging.SetMinimumLevel(LogLevel.Warning);
```
(You might want to do this only in production for debugging purposes)
[More information](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-6.0)
