### ISSUE TITLE
Blazor: window.onresize event

### ISSUE THREAD

**Issue by iSeiryu** [dotnet/aspnetcore#40325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there a reason `onresize` is not a part of this yet https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Web/EventHandlers.cs ?

Resizing in general handled well via CSS. But when it comes to [HTML canvas ](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) it becomes necessary to catch that event to scale the graphics (especially for the games) accordingly and to possibly do other things (e.g. pause or restart).

The [current](https://swharden.com/blog/2021-01-07-blazor-canvas-animated-graphics/) [hacks](https://github.com/EdCharbeneau/BlazorSize) are way too magical and bulky and may require a lot of maintenance as Blazor evolves.

https://github.com/dotnet/aspnetcore/issues/16017#issuecomment-390938079
Is this "uber-API-package" still in development or was it abandoned?

### Describe the solution you'd like

Add `onresize` to https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Web/EventHandlers.cs so we could subscribe to it in C# code.

### Additional context

HTML Canvas needs more love from Blazor in general! It'd be great to write Web-based games and other 2D/3D animations using .NET.

**Comment by javiercn** [comment]
@iSeiryu thanks for contacting us.

Those events are for DOM nodes, not global things like the window object. We think that this is achievable with JS interop and that there are already packages available (like the one you referenced) that simplify this scenario. We might do something in the future, but currently this is not a direction we plan to move on.
