### ISSUE TITLE
OnInitialized not being called for component inside RenderFragment after StateHasChanged on parent

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#40329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

having a component where the content is rendered by a `Func<RenderFragment>` on StateHasChanged the components from inside the RenderFragment don't call OnInitialized anymore, here's an example:

Index.razor:
`<MyComp1/>`

MyComp1.razor: 
```
<div @onclick="() => {}" >click me (to rerender/call StateHasChanged)</div>
<div>
    @getContent()
</div>

@code {
    Func<RenderFragment> getContent;

    protected override void OnInitialized()
    {
        getContent = () =>
        {
            var opt = new MyObj1();
            return @<MyContComp1 Opt="opt" />;
        };
    }
}
```
MyContComp1.razor:
```
<div>ContComp</div>
<div>
    @Opt.Data
</div>

@code {
    [Parameter]
    public MyObj1 Opt { get; set; }

    protected override void OnInitialized()
    {
        Opt.Data = "initialized";        
    }
}
```
first you'll see text "initialized", but after you click on "click me" (rerender), the text will disappear because Opt.Data was never set.

### Expected Behavior

I wanted to confirm if this is the behaviour that you are expecting, I have ways around this problem by putting the  
`var opt = new MyObj1();` 
outside the `Func<RenderFragment> getContent`

### .NET Version

6

### Anything else?

VS 2022

**Comment by SteveSandersonMS** [comment]
> I wanted to confirm if this is the behaviour that you are expecting

Yes. Where possible, render fragments retain instances of child components. You can put your setup logic into `OnParametersSetAsync`, or use `@key` to control whether or not child instances should be retained.

**Comment by omuleanu** [comment]
> render fragments retain instances of child components. 
just to confirm, this is a `Func<RenderFragment>` so the `RenderFragment` was recreated on main component's render

**Comment by SteveSandersonMS** [comment]
Yes, that doesn't change anything. If its output is the same, the diffing system still attempts to retain child instances.
