### ISSUE TITLE
Create 6.0 BlazorWebAssemblyApp project with the command and run the "dotnet publish" command,  for the first time meet error:'MSB4018: The "GetFileHash" task failed unexpectedly'.

### ISSUE THREAD

**Issue by v-wenkecheng** [dotnet/aspnetcore#40328]
**Azure DevOps work item**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1484614?src=WorkItemMention&src-action=artifact_link

**INSTALL STEPS**
1.Clean M1 macOS machine
2. Install SDK 6.0.200 arm64 from:https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Testcases Affected
[[6.0]BlazorWebAssemblyWithPWANoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/3x_BlazorWebAssemblyWithPWANoAuth.md)
[[6.0]SignalRWithBlazorWebAssembly](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/3x_SignalRWithBlazorWebAssembly_Mac.md)

Platform
- [ ] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
1. Open terminal.
2. Run`dotnet new blazorwasm -o BlazorWasmApp_net60`the command line.
3. `cd BlazorWasmApp_net60`
3. Run `dotnet run`
4. Run `dotnet publish`

**Actual Result**
1. Run the "dotnet publish" command,  for the first time meet error:'MSB4018: The "GetFileHash" task failed unexpectedly'.
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/69494255/154904158-17c4dce3-e951-4e61-bdd7-c12cd9b74fa0.png)
2. Run the "dotnet publish" command again a second time, it will work fine, no error.

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/69494255/154904483-953ce6c6-1b7c-4d58-8cee-2adca6a58252.png)

The following publish error file is IDELog.
[publish error.rtf.zip](https://github.com/dotnet/aspnetcore/files/8106938/publish.error.rtf.zip)

**EXPECTED**
Running the "dotnet publish" command with the command works fine without errors.

**Comment by mkArtakMSFT** [comment]
Closing as the issues was fixed internally.

**Comment by danroth27** [comment]
Internal tracking issue was reactivated.

**Comment by mkArtakMSFT** [comment]
Closing as the internal ticket has been resolved.
