### ISSUE TITLE
Consider removing Mono specific code in SqlServerCache

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40345]
I'm pretty sure it's untested (and possibly unsupported?): https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Caching/SqlServer/src/SqlServerCache.cs#L76-L83. Also why wouldn't we have users run on .NET instead?

**Comment by ArminShoeibi** [comment]
hi there folks, may I do the cleanup?
