### ISSUE TITLE
Friendly blazor for webpack

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#40343]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I work on a project where we rewrite a page in MVC to blazor. Additionally, the entire layout is generated in the webpack. Css truncation, generating dynamic classes in div, code optimization and many other things. Unfortunately, blazor has C # code in html, which makes it impossible to create an automatic solution. You have to do everything manually, also the work of creating a layout for blazor is very uncomfortable. It requires a fairly frequent recompilation of the code. In the documentation I found an option that you can create a file in which we put functions. Unfortunately, @page is missing there.
It would also be nice to create new HTML tags for loops, if etc.

### Describe the solution you'd like

Example:
```                 
<table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Tytuł</th>
                      <th scope="col">Autor</th>
                      <th scope="col">Wyświetlenia</th>
                      <th scope="col">Data</th>
                      <th scope="col">Edycja</th>
                      <th scope="col">Status</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  @foreach(var a in _search.All()){
                    <tr>
                        <th>@a.Get.Details.Title</th>
                        <td>@a.Get.Details.Author</td>
                        <td>@a.Get.Views</td>
                        <td>@a.Get.Details.Created.ToString("MM/dd/yy HH:mm")</td>
                        <td>@a.Get.Details.Updated.ToString("dd/MM/yy HH:mm")</td>
                        <td>@a.Get.Status.ToString()</td>
                        <td><a href=""><i class="fas fa-edit"></i></a></td>
                        <td><a href="Article/@a.GetName()" target="_blank"><i class="fas fa-eye"></i></a></td>
                    </tr> 
                  }
                  </tbody>
</table>
```

```
<foreach key="a" value="_search">
<tr>
  <th><div key="a.Get.Details.Title"></div><th>
  ...
</tr>
</foreach>
```
You can apply tags to each option, so you can easily manage this data in node and webpack. The easier and more friendly the syntax is, the more you can replace files each time without running into problems.

### Additional context

What do you think about such a solution? I find it very necessary, HTML should be completely isolated from C#.

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

It's a bit unclear what your request here is, could you clarify the "webpack" part?

> It would also be nice to create new HTML tags for loops, if etc.

With regards to the piece above, this is not something we plan to do. It is an explicit design decision in Blazor that control flow is expressed in C#, not markup.

That said, nobody prevents you from creating your own components to do that.

**Comment by Alerinos** [comment]
> It's a bit unclear what your request here is, could you clarify the "webpack" part?

Having a large page that contains a lot of subpages, it is easier to create it with a webpack that generates ready html and css code.
Unfortunately, the implementation of changes involves a manual transfer of changes every time. So if the department responsible for the front UI updates it, then you have to manually change everything again.
I created a webpack that generates a ready front in razor files
Example:
/Pages/Counter.razor
Unfortunately webpack is not able to generate C # code, so I used ComponentBase
```cs

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lib.Articles;
using Microsoft.AspNetCore.Components;

namespace Website.Areas.Web.Pages.Articles
{
    public partial class Article : ComponentBase
    {
        [Inject] Lib.Articles.Articles Articles { get; set; } = null!;
        [Parameter] public string Name { get; set; } = "";

        public Lib.Articles.Article? _article { get; set; }
        public IEnumerable<Lib.Articles.Models.Article>? _recommendations { get; set; }


        protected override async Task OnParametersSetAsync()
        {
            _article = Articles.Article(Name);
            _recommendations = _article.Recommendations().Where(x => x.Status == Lib.Articles.Models.Article.StatusType.Show);
            await _article.AddViewsAsync();

            await Task.CompletedTask;
        }
    }
}
```
Unfortunately, it lacks, for example:
```
@page "/article/{Name}"
```

I also understand the blazor premise, the C # code is good and fast but you can create a layer in the compiler that helps the front end and reduces the workload. Create a solution that will automatically generate ready code.

Now times are changing, what matters is the optimization of the front. Reducing the css code, securing the klass by generating random names so that scrap bots have a harder time.

**Comment by javiercn** [comment]
@Alerinos it's still a bit unclear.

Are you trying to do static site generation with Razor Components?
