### ISSUE TITLE
Add GetMultipleFiles() method to InputFileChangeEventArgs and specify exceptions thrown.

### ISSUE THREAD

**Issue by Grizzlly** [dotnet/aspnetcore#40341]
## Summary

[InputFileChangeEventArgs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/InputFileChangeEventArgs.cs) should also have a `GetMultipleFiles` method that just returns the files.

`GetMultipleFiles` and `File` should have an `<exception>` tag that specifies the exception thrown (`InvalidOperationException`).

## Motivation and goals

The only way to return all the files is to call `GetMultipleFiles(FileCount)`.

## In scope

* A more elegant way of returning all files uploaded.

## Risks / unknowns

There are not any risks that come to mind.

## Examples

```c#
var uploadedFiles = GetMultipleFiles();

var forUpload = uploadedFiles.Take(maxNumber).ToList().AsReadOnly();

```

**Comment by javiercn** [comment]
@Grizzlly thanks for contacting us.

> [InputFileChangeEventArgs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/InputFileChangeEventArgs.cs) should also have a GetMultipleFiles method that just returns the files.

This is an explicit design choice as there are security implications around this feature in Blazor Server. In addition to that, the parameter has a default value, so you can invoke it without providing a value.

> GetMultipleFiles and File should have an <exception> tag that specifies the exception thrown (InvalidOperationException).

We would gladly accept a PR to improve the docs.
