### ISSUE TITLE
Change "Blazor component" to "Razor component" in a few spots

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#40344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

"Blazor component" is merely an *informal name* for components in Blazor. The formal name is "Razor component." MS pubs became wildly inconsistent on the point, even including the use of both terms in the same doc 😵. This can lead to confusion because the Blazor docs *never use* "Blazor component," which was decided by DR in ancient Blazor days 🦖.

Updates to MS pubs are proceeding: .NET MAUI (`dotnet/maui`) and .NET docs (`dotnet/docs`) have already been updated. I'm in the process of getting Learn Modules on-board.

This issue is to ask if we can purge the "Blazor component" lingo from a few spots in the framework ...

* Test app component renders the term: https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/ExternalContentPackage.razor
* One mention in a code comment that won't appear in API docs: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/LogicalElements.ts
* One mention for API docs: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/WebViewManager.cs
* Test app component renders the term: https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/DynamicallyAddedRootComponent.razor

The following files use `Blazor-Component-State`, but this is probably by-design (i.e., `Razor-Component-State` isn't welcome for some reason in these cases):

```
const blazorStateCommentRegularExpression = /^\s*Blazor-Component-State:(?<state>[a-zA-Z0-9+/=]+)$/;
```

```
Assert.Equal("<!--Blazor-Component-State:e30=-->", content);
```

* https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Services/ComponentDescriptorDiscovery.ts
* https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.TagHelpers/test/PersistComponentStateTagHelperTest.cs

### Describe the solution you'd like

I can submit the PR for the first four bullets ☝️ ... *let me know* 👂 ... and the fifth point (`Blazor-Component-State` :point_right: `Razor-Component-State`) if you wish it updated, but I think you'll say that last one is OK.

### Additional context

Cross-references:

* https://github.com/dotnet/docs-maui/issues/295
* https://github.com/dotnet/docs/pull/28324
* https://github.com/dotnet/maui/discussions/4799
* Learn Module updates are being discussed offline because there's no public repo for open discussion.

**Comment by javiercn** [comment]
@guardrex thanks for filing an issue.

In general, for stuff that appears in API docs, I agree with you. For stuff that doesn't appear in API docs, we don't really care. Same as for code that we don't ship (samples, test projects, etc.)

**Comment by javiercn** [comment]
@guardrex feel free to send a PR with whatever fixes you deem appropriate.
