### ISSUE TITLE
Allow custom headers on SignalR WebSockets on React Native

### ISSUE THREAD

**Issue by RobertSasak** [dotnet/aspnetcore#40346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

SignalR client library in Typescript on React Native do not support custom headers. When connecting to hub security token is appended into url. This url then shows in various IIS logs and can be a security issue. You can see it in logs like this.
```
Information: WebSocket connected to wss://myhub.example/hub?access_token=eyJh....
```
In addition no other custom headers can be added.

This issue apply only to React Native. 

### Describe the solution you'd like

@BrennanConroy addressed exactly the same issue for NodeJS in https://github.com/dotnet/aspnetcore/pull/37205 
Solution is to allow his changes also on React Native.

**Comment by javiercn** [comment]
@RobertSasak thanks for contacting us.

@davidfowl  has been trying to fix this since forever. AFAIK, websockets don't support custom headers on the handshake and as a result the token needs to be included in the URL.

**Comment by RobertSasak** [comment]
I agree that WebSockets in a browser do not support custom headers. However this should be possible in React Native the same way as it is possible in NodeJS.
