### ISSUE TITLE
DelegationRule should continue to work after receiver process restart

### ISSUE THREAD

**Issue by NGloreous** [dotnet/aspnetcore#40358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using http.sys delegation, there are two processes involved, the delegator (the process creating the DelegationRule to delegate requests it receives) and the receiver (the process the delegator transfers requests to). It's possible that the receiver may restart independently from the delegator and ideally, we want the delegator to continue to be able to delegate requests after the receiver restarts. Currently, this does not work, and the delegator needs to detect when the receiver restarts and dispose and re-create the DelegationRule.

### Describe the solution you'd like

After talking with the http.sys team, it seems one of the reasons HttpDelegateRequestEx was added was to address this issue. It supports passing the UrlGroup id as a parameter but this value can be 0 to let http.sys find the UrlGroup to use for the request.

Currently, when ASP.NET Core creates a DelegationRule, it looks up the UrlGroup id for the given urlprefix and then uses this id when calling HttpDelegateRequestEx. Instead, it should just pass 0 here instead.

https://github.com/dotnet/aspnetcore/blob/de3019b7dab5b5995942db1fbec6aa466c4af34c/src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs#L288-L293

**Comment by Tratcher** [comment]
Is there a downside to passing 0? It seems like this would simplify the implementation.

**Comment by NGloreous** [comment]
Http.sys would have to do the lookup instead so a small cost there but minor. Per the http.sys team the main reason for adding HttpDelegateRequestEx was to allow passing 0.

**Comment by NGloreous** [comment]
@Tratcher thoughts on backporting this to .NET 6? There is a workaround so possibly not worth it?
