### ISSUE TITLE
Blazor Add validation error/message for field

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#40357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

is it possible (is there plans to implement) to add a validation error like in MVC `AddModelError(key, errorMessage)` ?

for now I have temporary workaround which looks like this: 

```
public class CustomValid : ValidationAttribute
{
    public override bool IsValid(object value)
    {
        if (value is null) return true;
        
        ErrorMessage = (string)value;
        return false;
    }
}
```
ViewModel:
```
[CustomValid]
public string Vld1 { get; set; }
```
save code:
```
input.Vld1 = input.Name == "Foo" ? "Name not unique" : null;
if (!editContext.Validate()) ...
```

### Describe the solution you'd like

`EditContext.AddFieldError(fieldName, errorMessage)`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is already supported and you can learn how to do it from https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#basic-validation
Please look for `ValidationMessageStore` API.

**Comment by omuleanu** [comment]
@mkArtakMSFT it's a lot more complicated comparing to MVC's `ModelState.AddModelError` ,
and you can't call await inside `HandleValidationRequested`

is this part important: 
```
    public void Dispose()
    {
        if (editContext is not null)
        {
            editContext.OnValidationRequested -= HandleValidationRequested;
        }
    }
```
wouldn't dispose, dispose  the `editContext ` which is field in the component ?
