### ISSUE TITLE
After VS Upgrade to 17.1 Hot Reload Issue

### ISSUE THREAD

**Issue by airwedge1** [dotnet/aspnetcore#40354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After VS upgrade to 17.1 existing or new template projects where are created with the WASM templated and then modified to run as Blazor Server Hot reloading no longer works.

To explain why we do this.  We like to separate the client side UI from the back-end logic.  In addition with this setup we can switch  between execution between blazor server and blazor wasm by changing a configuration file.  This has worked excellent up until visual studio 17.1.  In VS 17.1 hot reloading no longer functions. 

### Steps To Reproduce

I started with a basic template Blazor WASM project and then copy and pasted the _Host, _Layout and Program.cs from the basic Blazor Server template. Then modified / simplified to allow it to run as a blazor server project.

Please see https://github.com/airwedge1/BlazorApp7

### .NET Version

6.0.200

### Anything else?

Visual Studio 2022 Professional 17.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
