### ISSUE TITLE
ProtectedBrowserStorage documentation or source code security algorithm description

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#40360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to find out how this works - symmetric cryptography? Assymetric cryptography? Where does/do the key/keys come from? Where is/are the key/keys stored? How are keys preserver between application sessions?
I am not able to find any answers to these questions.

### Describe the solution you'd like

Clear description of security algorithm used for ProtectedBrowserStorage so I can analyze the behavior and detect security issues for our customers.

**Comment by pranavkm** [comment]
It uses the [Data Protection APIs](https://docs.microsoft.com/aspnet/core/security/data-protection/introduction) to encrypt and decrypt values. The docs include implementation details which should cover most of your question.

FYI @blowdart
