### ISSUE TITLE
Razor view can't render JSON-LD.

### ISSUE THREAD

**Issue by kyuranger** [dotnet/aspnetcore#40373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am about to add structured-data (for example: https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data) to my asp.net core 6 project for SEO.

The structured-data render or not will by a logic, just like this:
```
@if(//some logic)
 {
 <script type="application/ld+json">
       {
         "@@context":"https://ziyuan.baidu.com/contexts/cambrian.jsonld",
         "@@id":"http://m.example.com/path/page.html",
         "appid":"",
         "title":"@Model.title",
         "images":["@($"www.abc.com/images/topics/Index/{id}.png")"],
         "description": "@Model.description",
         "pubDate":"@Model.publish_time.ToString("s")",
         "upDate":"@Model.update_time?.ToString("s")",
         "lrDate":"@Model.publish_time.ToString("s")"
       }
     </script>
 }
```

The project runs without any error while the structured-data is never rendered on the page whether the logic is true or not.

I have asked a question in https://docs.microsoft.com/en-us/answers/questions/745835/how-can-i-raw-special-character-in-razor-view.html .

And the Microsoft Employee told me that it seems the asp.net core does not support it and maybe it is a bug.

I am looking forward Microsoft to fix this in the new version.

### Expected Behavior

Fix this bug and support the structured-data.

### .NET Version

6.0.200

**Comment by javiercn** [comment]
@kyuranger thanks for contacting us.

You can inject `IJsonHelper` and use that to render the serialized JSON object directly on to the page.

**Comment by kyuranger** [comment]
> @kyuranger thanks for contacting us.
> 
> You can inject `IJsonHelper` and use that to render the serialized JSON object directly on to the page.

All right. Honestly, I don't know why Microsoft designed it like this. But I think it should render it directly without any library or helper.

**Comment by kyuranger** [comment]
> 

I am afraid the IJsonHelper is not available any more in asp.net core 6:https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.jsonhelper?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-6.0

**Comment by javiercn** [comment]
@kyuranger https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/Rendering/IJsonHelper.cs It is, I'm not sure why the docs say the opposite.
