### ISSUE TITLE
Razor runtime compilation with dynamic assemblies fails

### ISSUE THREAD

**Issue by gyankov** [dotnet/aspnetcore#40377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I load an assembly and then try to use any of its types as a view model I get an error that the provided instance does not match the expected type:

![image](https://user-images.githubusercontent.com/16634965/155345884-0cd09cb9-8393-4295-a450-0fedd0a1894a.png)

As you can see the weird part is that the expected and actual types are the same.

Below are the view, controller and model definitions:

```
using Microsoft.AspNetCore.Mvc;

namespace DemoNamespace
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {

            return View(new TestViewModel{Name = "Test"});
        }
    }
}
```

```
namespace DemoNamespace
{
    public class TestViewModel
    {
        public string Name { get; set; }
    }
}
```

```
@using DemoNamespace

@model TestViewModel

<h1>@Model.Name</h1>
```

I made sure that the assembly is loaded only once and also tested to create an instance of the model within the view manually which worked, so the assembly must be loaded correctly. Also, changing the model directive to `dynamic` worked as well.

### Expected Behavior

To work without any errors.

### Steps To Reproduce

Load an assembly runtime and use any of its types as a view model.

**Comment by javiercn** [comment]
@gyankov thanks for contacting us.

@pranavkm do you have any thoughts here? Is this supported at all?

**Comment by pranavkm** [comment]
I'm going to guess the dynamically loaded assembly and the view are both in different / non-default load contexts. Views are in a non-default one since it uses `Assembly.Load`. Perhaps loading the dynamic assembly using `AssemblyLoadContext.Default` should help here?

**Comment by gyankov** [comment]
I already load the dynamic assembly in the default context:
```
                AssemblyLoadContext.Default.LoadFromAssemblyPath(assembly.Location);
                partManager.ApplicationParts.Add(part);
```
The view is provided through a custom file provider, not sure if relevant.

**Comment by gyankov** [comment]
I have created a [sample](https://progresssoftware-my.sharepoint.com/:u:/g/personal/gyankov_progress_com/Eah-GhvaGSpBnJDq7V_ahAQBVbdZYKkPnrAj4GtbbeQ6Tg?e=47NbNb) where the issue replicates. Please note that the assembly is loaded to the default load context but if I try to use a type from the new assembly in a view, an exception is thrown.

I have a follow-up question, how do you unload an assembly from the default context? From what I've read in your documentation, you can only unload the whole load context. Is that really the case? If so, is it possible to use a custom load context in the runtime compilation?

**Comment by aloksharma1** [comment]
@gyankov i have the same issue as you from version 3.1 till now, its not fixed.
