### ISSUE TITLE
Skip authentication on specific razor pages (.razor)

### ISSUE THREAD

**Issue by sp-yang** [dotnet/aspnetcore#40375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Authentication and authorization are implemented at the blazor project level. So every razor pages will require authentication by default. But, in some situations, some razor pages shall be accessible without authentication. Having tried [AllowAnonymous] attribute tag, no success. Is it possible to bypass authentication and directly render some specific razor pages? If yes, how to do it? Thanks.

### Describe the solution you'd like

It is possible to skip authentication and access specific razor pages directly via e.g. annotation, configuration or other approach.

**Comment by javiercn** [comment]
@sp-yang thanks for contacting us.

If you don't put an [Authorize] attribute on the page it should be enough

**Comment by sp-yang** [comment]
@javiercn Thank you for getting back to me. 
Actually there is no [Authorize] attribute on each razor page, the authentication is applied globally. Besides [AllowAnonymous], I also use RouteView instead of AuthorizeRouteView, it still requires authentication. Is there any way to simply "trust" the razor page before authentication?

**Comment by javiercn** [comment]
@sp-yang How are you applying authorization?

**Comment by sp-yang** [comment]
@javiercn We implement authorization as follows:
# Startup.cs
public void ConfigureServices(IServiceCollection services)
{
       services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(options =>
                    {
                        Configuration.Bind("AzureAd", options);
                        options.Events.OnTokenValidated = async context =>
                        {
                            string tenantId = context.SecurityToken.Claims.FirstOrDefault(x => x.Type == "tid" || x.Type == "http://schemas.microsoft.com/identity/claims/tenantid")?.Value;
                            if (string.IsNullOrWhiteSpace(tenantId))
                                throw new UnauthorizedAccessException("Unable to get tenantId from token.");

                            // To check if there is a record in our TenantDB
                            var authorizedTenant = tenants.FirstOrDefault(x => x.Tenantid == tenantId);
                            if (authorizedTenant == null)
                                throw new UnauthorizedTenantException("This tenant is not authorized");
                        };
                        ...
                     }
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
       ...
       app.UseAuthentication();
       app.UseAuthorization();
       ...
}

# App.razor
<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
            <Found Context="routeData">
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
</Router>

**Comment by javiercn** [comment]
@sp-yang Is this Blazor Server of WebAssembly

**Comment by sp-yang** [comment]
@javiercn It's Blazor Server.

**Comment by javiercn** [comment]
@sp-yang It's likely that your default policy requires authentication. You might define a separate policy for those pages and put @attribute [Authorize("AllowAnonymousPolicy")] on them.
