### ISSUE TITLE
IISIntegration tests in VS don't detect changes

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#40387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Note: I don't think release is required, but I've primarily been debugging/running in release due to some ANCM tests only working in release

I'm using VS2022 17.1.0/against main branch (with IIS installed + Admin powershell)
1. git clean -xdff/restore.cmd/activate.ps1
2. cd src/Servers/IIS
3. build.cmd -c Release
4. startvs.cmd / switch to Release/x64 platform
5. Wait for test explorer to load all the tests, then go to Microsoft.AspNetCore.Server.IIS.NewShim.FunctionalTests.StartupTests.CheckInvalidHostingModelParameter
6. Double click on test to open StartupTests.cs (C:\Github\aspnetcore\src\Servers\IIS\IIS\test\Common.LongTests\StartupTests.cs)
7. Comment out the `[SkipNonHelix("https://github.com/dotnet/aspnetcore/issues/25107")]` on line 41
8. Run the test, notice that nothing builds as things are considered up to date and yet still is skipped.
10. Add `<DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>` to src\Servers\IIS\IIS\test\IIS.NewShim.FunctionalTests\IIS.NewShim.FunctionalTests.csproj
11. Run the test and notice it rebuilds and the test is no longer skipped.

I'm guessing this is might be due to StartupTests is being a file included from shared tests 
`<Compile Include="..\Common.LongTests\**\*.cs" />`
`

**Comment by mkArtakMSFT** [comment]
Moving this to the `area-runtime` as this seems very specific to this project.

**Comment by halter73** [comment]
@HaoK Do you know how to fix this? Should we just add the `<DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>` to the csproj?

**Comment by HaoK** [comment]
Yeah that was how it was before I believe but Kevin wanted us to do a pass to remove that and increase the build perf...

**Comment by Pilchie** [comment]
Could definitely just re-add the `<DisableFastUpToDateCheck>true</>` if you don't want to dig in.  Possible that @dougbu already fixed this issue in https://github.com/dotnet/aspnetcore/commit/9a431eed6988793fdfc142399fec0e73834c7cd6 though.

**Comment by adityamandaleeka** [comment]
I think this can be closed. These projects have `DisableFastUpToDateCheck` enabled already (e.g. https://github.com/dotnet/aspnetcore/blob/main/src/Servers/IIS/IIS/test/IIS.NewShim.FunctionalTests/IIS.NewShim.FunctionalTests.csproj#L8).

I also checked that, if that setting is removed, the skip detection does get correctly picked up between invocations of the test from test explorer (i.e. the incremental build scenario).
