### ISSUE TITLE
Blazor, InputText does not support changing the EditContext dynamically, when adding forms dinamically

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#40388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

you can see a mini demo here: https://blazorfiddle.com/s/pcei4obi
you get the error either by 
1) clicking on "add" twice
2) or by clicking on at least one "edit" and after on "add"
(errors shown in browser console)

(in my actual code I would get the error only after canceling/saving 2 items and after clicking "add" twice)
a solution is to add `@key="item"` on the `<p>` but it looks like you should have a look.
(in the actual code `@key="item.Key"` helps, just `="item"` doesn't)

the mini demo code (shown in blazorfiddle also):
```
<button @onclick="() => {
    var model = new MyModel();
    model.Id = id++;
    items.Insert(0, new ItemState{ Model = model, EditContext = new EditContext(model)});
}">
    add
</button>

@foreach (var item in items)
{
    <p>
        @item.Model.Id 

        @if (item.EditContext is not null)
        {           
            <CascadingValue Value="item.EditContext">
                <InputText @bind-Value="item.Model.Name" />
            </CascadingValue>
        }
        else
        {
            @item.Model.Name
            <button 
            @onclick="() => {
                item.EditContext = new EditContext(item.Model);
            }"
            >edit</button>
        }
    </p>
}
@code
{
    private int id = 200;
    private List<ItemState> items = new()
        {
            new ItemState { Model = new MyModel { Name = "item 1", Id = 100 } },
            new ItemState { Model = new MyModel { Name = "item 2", Id = 101 } },
            new ItemState { Model = new MyModel { Name = "item 3", Id = 102 } }
        };
}
public class ItemState
{
    public MyModel Model { get; set; }

    public EditContext EditContext { get; set; }
}

public class MyModel
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

### Expected Behavior

not to get this error

### .NET Version

6

### Anything else?

VS2022

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The solution you've found with adding the `@key` attribute is fine to use.
As for the `EditContext`-s, we recommend using single one and not try to create multiple.

**Comment by omuleanu** [comment]
@mkArtakMSFT can you use a single `EditContext` for multiple forms that the user can save/cancel individually ?
