### ISSUE TITLE
[release/6.0.2xx] source-build: Remove *.Razor.*.Tooling.Internal prebuilts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#40395]
The following Razor tooling prebuilts have been detected in release/6.0.2xx.  These need to be removed by either ensuring the prebuilt is included in source-build or by excluding the reference in source-build.

```
    <Usage Id="Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal" Version="6.0.2-1.22056.2" File="src/sdk.8a705ab1294ff07ae66ea41ca890b004cfa6fd9f/artifacts/buildObj/source-build/self/src/artifacts/obj/Microsoft.NET.Sdk.Razor.Tool/project.assets.json" IsDirectDependency="true" />
    <Usage Id="Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal" Version="6.0.2-1.22056.2" File="src/sdk.8a705ab1294ff07ae66ea41ca890b004cfa6fd9f/artifacts/buildObj/source-build/self/src/artifacts/obj/Microsoft.NET.Sdk.Razor.SourceGenerators/project.assets.json" IsDirectDependency="true" />
    <Usage Id="Microsoft.CodeAnalysis.Razor.Tooling.Internal" Version="6.0.2-1.22056.2" File="src/sdk.8a705ab1294ff07ae66ea41ca890b004cfa6fd9f/artifacts/buildObj/source-build/self/src/artifacts/obj/Microsoft.NET.Sdk.Razor.Tool/project.assets.json" IsDirectDependency="true" />
```

**Comment by wtgodbe** [comment]
Sure, @MichaelSimons is there guidance on how to get the razor-compiler repo source-building?

**Comment by MichaelSimons** [comment]
Sorry for the delayed response - I've been OOF.  Here is the [source build guidance for onboarding new repos](https://github.com/dotnet/source-build/blob/main/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md).  If you run into any issues or have questions, please let me know and I will be glad to help.

**Comment by MichaelSimons** [comment]
@wtgodbe - do you have an ETA on this?

**Comment by wtgodbe** [comment]
Sure, I can take a look tomorrow or Monday

**Comment by wtgodbe** [comment]
Should be fixed by https://github.com/dotnet/sdk/pull/24794 https://github.com/dotnet/sdk/pull/24795 https://github.com/dotnet/sdk/pull/24796
