### ISSUE TITLE
Add overload to modify StaticFileOptions for UseBlazorFrameworkFiles

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#40390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

My app has a public and a private area. Our Blazor WASM app is a hosted app, in a Razor Page that is protected using RequireAuthorization on the endpoint mapping.  

All static files not in the public area are protected using StaticFileOptions, something like:
```
app.UseStaticFiles(new StaticFileOptions
        {
            OnPrepareResponse = ctx =>
            {
                if (ctx.Context.User.Identity is not { IsAuthenticated: true })
                {
                         // thou shall not pass
                         ctx.Context.Response.ContentLength = 0;
                         ctx.Context.Response.Body = Stream.Null;
                        ctx.Context.Response.Redirect("/");                
                }
            }
        });
```

We expected this would also protect the Blazor WASM framework files and all our application DLL's, but this is not the case.  

Blazor use its own modified `StaticFileOptions`, bypassing the options as set in Startup:

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L86-L129

### Describe the solution you'd like

What would be ideal if there was a way to pass our own `StaticFileOptions` in an overload for `UseBlazorFrameworkFiles`, that would combine our logic with Blazor logic. 

I worked around this issue for now by copying the static file code and modifying it accordingly using the identity check.

**Comment by javiercn** [comment]
@rogihee thanks for contacting us.

The way we recommend people do this is by using MapWhen in front of the middleware and do any check there. 

For example

```
app.MapWhen(ctx => ctx.User.Identity is not { IsAuthenticated: true }, subApp => {
   ctx.Response.Redirect("/");
});
app.UseBlazorFrameworkFiles();
```
