### ISSUE TITLE
Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(442,5): error : Two assets found targeting the same path with incompatible asset kinds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40416]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftNETSdkRazorStaticWebAssets/1675359)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:.Net Core 3.1]
C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(442,5): error : Two assets found targeting the same path with incompatible asset kinds:  [D:\Migration\XXXXXX\XXXX.App\XXXX.csproj]
C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(442,5): error : 'D:\Migration\XXXXXX\XXXX.App\wwwroot\assets\images\AAA.png' with kind 'All' [X:\Migration\XXXXXX\XXXX.App\XXXX.csproj]
C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(442,5): error : 'X:\Migration\XXXXXX\XXXX.App\wwwroot\assets\images\AAA.png' with kind 'All' [D:\Migration\XXXXXX\XXXX.App\XXXX.csproj]
C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(442,5): error : for path 'assets/images/Cancel.png' [D:\Migration\XXXXXX\XXXX.App\XXXX.csproj]
    0 Warning(s)
    1 Error(s)

Error occurs while building the Solution. Not sure why this error is happening in .NET 6, the same copy of wwwroot folder content to output directory works fine in . Netcore3.1. But giving error in .Net 6. 

Did initial research on any other alterative for this problem. It only builds if content of wwwroot folder are deleted each time in the project directory location. hence works fine on the first time of clean workspace.

Background: basically need to copy the icons and images used in client to wwwroot folder and also copying this to output directory using  <ItemGroup>
       <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

---
#### Feedback Bot on 2/23/2022, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
Thanks for contacting us.

Could you provide a minimal repro project that demonstrates the issue as a public github project so that we can make progress?

**Comment by Shruthi1984** [comment]
Hi @javiercn , please find the link to the project sln in https://github.com/Shruthi1984/StaticWebAssestscopyissue.
try to perform the dotnet build where sln file resides, when there is content in the wwwroot folder inside the project directory StaticWebAssestscopyissue\MyMiniProj\MyMiniProj, you get the build error with above probelm. if there is no wwwroot folder in the project directory StaticWebAssestscopyissue\MyMiniProj\MyMiniProj then dotnet build works fine. Kindly have a look and let me know if you need more information.
