### ISSUE TITLE
Jquery menu navigation is not working at the initial load in Blazor server

### ISSUE THREAD

**Issue by EffiTPMU1** [dotnet/aspnetcore#40429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to use Jquery menu navigation and called my js in _Host.cshtml file but the same wasn't working during initial load and it was working when we reload the page again.

### Expected Behavior

Jquery functionality should work during the initial load.

### Steps To Reproduce

I am using Dore Jquery template for menu navigation. Please use jquery, bootstrap, perfect-scrollbar, datatables and dore.scripts js file to replicate the same.

### .NET Version

dotnet 5

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
