### ISSUE TITLE
Razor automatic encoding inside <script> tags

### ISSUE THREAD

**Issue by lukoerfer** [dotnet/aspnetcore#40423]
Using string variables inside Razor views will automatically apply HTML encoding to those variables. However, it seems like using string variables inside `<script>` tags in Razor will apply another encoding (related to JavaScript):

```csharp
@{
    var test = "Überraschung!";
}

@test
<script>@test</script>
```

This code sample will lead to the following HTML output:
```html
Überraschung!
<script>&#xDC;berraschung!</script>
```

Is there any dedicated documentation on this behavior or could you provide the place in the code where it is implemented? Are there any other tags that will change the way how the content will be encoded?

**Additional background:**

We are using the Kendo UI framework by Telerik. It supports the definition of [HTML templates](https://docs.telerik.com/kendo-ui/framework/templates/overview) that will be evaluated in the Browser using `<script>` tags with `type="text/x-kendo-template"` or `type="text/html"` (for proper syntax highlighting in VS):

```html
<script id="boxTemplate" type="text/html">
    <div id="box">#: firstName #</div>
</script>
```

Now, when using string variables inside such an HTML template, it is necessary to use some workaround like `@Html.Raw(...)` (bad idea for displaying user input) or packing the variable in an `HtmlString`, as variables of type `IHtmlContent` won't be encoded a second time:

```html
<!-- Won't work -->
<script id="boxTemplate" type="text/html">
    <div id="box">@test #: firstName #</div> 
</script>

<!-- Works (but dangerous for user inputs) -->
<script id="boxTemplate" type="text/html">
    <div id="box">@Html.Raw(test) #: firstName #</div>
</script>

<!-- Works (can be shortened by importing the namespace, but not really clean) -->
<script id="boxTemplate" type="text/html">
    <div id="box">@(new Microsoft.AspNetCore.Html.HtmlString(test)) #: firstName #</div>
</script>
```

Using `@Html.Encode` does not work, as it returns a string instead of some `IHtmlContent` (weird design decision in my opinion), which will be encoded a second time leading to the same problem:

```html
<!-- Won't work -->
<script id="boxTemplate" type="text/html">
    <div id="box">@Html.Encode(test) #: firstName #</div>
</script>
```

**Comment by pranavkm** [comment]
@lukoerfer Razor does not have special encoding behavior for content inside script tags - `@` will uniformly HTML encode in all places that it gets used. 

> Works (can be shortened by importing the namespace, but not really clean) 
> <script id="boxTemplate" type="text/html">
>    <div id="box">@(new Microsoft.AspNetCore.Html.HtmlString(test)) #: firstName #</div>
> </script>

Note that this is equivalent to [`Html.Raw`]( https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/HtmlHelper.cs#L619-L622)

**Comment by lukoerfer** [comment]
> Razor does not have special encoding behavior for content inside script tags - @ will uniformly HTML encode in all places that it gets used.

Then how to explain the behavior in the first example? I will try to create a minimal, complete and verifiable example next, but right now I got no idea what else could cause the encoding of the umlaut inside the `<script>` tag.

> Note that this is equivalent to `Html.Raw`

Thanks for pointing this out, I somehow expected `HtmlString` to HTML encode the string for me. The method documentation says:

> An `IHtmlContent` implementation that wraps an HTML encoded `String`.

Which is only true if and only if you actually pass an HTML encoded string. It may actually wrap any string, as shown by `Html.Raw`.

**Comment by pranavkm** [comment]
Here's what I tried in a .NET 6 MVC view:

```razor
@{
    var test = "Überraschung!";
}

@test
<script>@test</script>
```

And here's what I see in the output:

```html
&#xDC;berraschung!
<script>&#xDC;berraschung!</script>
```

**Comment by lukoerfer** [comment]
You are right, it's not the Razor engine that treats the tags in a different way, but the browser that seems to ignore the actual content type. I tried the same example but this time I did not check the resulting HTML in the browser. Instead I fetched the page using wget and got the same result as you did.

Regarding my actual problem, it seems like the only way to prevent using `@Html.Raw` (or its equivalent `new HtmlString(...)`) inside `<script>` would be a custom `HtmlEncoder` that allows certain (or all) Unicode characters. Are there any other options?

I found the following part in the documentation:

> The reasoning behind this is to protect against unknown or future browser bugs (previous browser bugs have tripped up parsing based on the processing of non-English characters). If your web site makes heavy use of non-Latin characters, such as Chinese, Cyrillic or others this is probably not the behavior you want.

Would you consider allowing the whole range of Unicode characters to the `HtmlEncoder` as safe? Should I use this custom encoder only for specific cases (e.g. inside `<script>` tags) and otherwise rely on the default one?

**Comment by pranavkm** [comment]
> Would you consider allowing the whole range of Unicode characters to the HtmlEncoder as safe? 

There's a way to do this by registering a `HtmlEncoder` with the a widened safe-list. See https://docs.microsoft.com/aspnet/core/security/cross-site-scripting?#customizing-the-encoders. You could always use two different sets of `HtmlEncoder` instances, one with the more lenient config that is used within `script` blocks if that helps.

**Comment by lukoerfer** [comment]
@pranavkm Thanks for your help and guidance on this topic!

If any future readers may encounter the same problem, I solved it by adding the following extension method to `IHtmlHelper`:

```
public static IHtmlContent Safe(this IHtmlHelper _, string value)
{
    var encoder = HtmlEncoder.Create(UnicodeRanges.All);
    return new HtmlString(encoder.Encode(value));
}
```

Now it is possible to call `@Html.Safe` instead of `@Html.Raw` inside the script tags to limit the encoding to HTML specific characters (e.g. `<` and `>`). All other Unicode characters won't be encoded when using `@Html.Safe`, but will still be encoded when just using strings inside Razor.
