### ISSUE TITLE
Make extensions classes public if the type and fields they 'extend' or access are public

### ISSUE THREAD

**Issue by pszeder** [dotnet/aspnetcore#40437]
## Background and Motivation

While developing a custom select input component I came across some limitations, extensions classes marked as internal, which blocked me from easily inheriting from `InputBase<TValue>`. In an ideal world, copying the source of `InputSelect<TValue>` would compile straight away and would be a good base for modifications. 

## Proposed API
In the above-mentioned case, I have found the following two classes that blocked me, however, it would be nice to review all similar extensions classes.

```diff
namespace Microsoft.AspNetCore.Components.Rendering;

-internal static class RenderTreeBuilderExtensions
+public static class RenderTreeBuilderExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void AddAttributeIfNotNullOrEmpty(this RenderTreeBuilder builder, int sequence, string name, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            builder.AddAttribute(sequence, name, value);
        }
    }
}
```

```diff
namespace Microsoft.AspNetCore.Components.Forms;

-internal static class InputExtensions
+public static class InputExtensions
{
```

## Usage Examples

Examples omitted. 

## Alternative Designs

Not applicable.

## Risks

No breaking changes. Would slightly increase the public API surface that needs to be maintained and kept compatible in future releases.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear how the internal extension methods blocked you from deriving from `InputBase<TValue>`.
Can you please clarify?

As a side note, we've put a lot of thought into deciding which types should be public and we still don't see this being a wrong choice here.

**Comment by pszeder** [comment]
@mkArtakMSFT 
It did not block me, just made it harder. If the base class `InputBase<TValue>` is public, and `InputSelect<TValue>` and other implementations are public and non-sealed, why would any helper methods used by either of these be internal? 

As I said above, in a perfect world I would expect to copy the source of `InputSelect<TValue>` into my project and it would compile straight away. Currently, it does not, because it depends on those two extension classes. I ended up having a copy of both classes in my project.

**Comment by mkArtakMSFT** [comment]
Thanks for additional details, @pszeder.
After further discussion we've decided not to expose these types and keep them as is. As you've mentioned in the original comment, you're free to copy the code into your app to use.
