### ISSUE TITLE
ReUse installed .NET runtime

### ISSUE THREAD

**Issue by Dargazo** [dotnet/aspnetcore#40431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In blazor WASM, the .NET runtime is downloaded if not in browser cache

### Describe the solution you'd like

If the correct .NET runtime is already installed, have (e.g.) Edge load the .NET runtime into the browser, and skip downloading the runtime, but still downloading other assemblies and dependencies etc..

If the correct .NET runtime is not installed on the pc, then download the runtime.

I guess this feature would require changes in Edge, as well as blazor WASM

### Additional context

This suggestion expands on e.g. [#38278](https://github.com/dotnet/aspnetcore/issues/38278)

**Comment by ShreyasJejurkar** [comment]
> > I guess this has been asked earlier as well, but the answer remains the same. We cannot ask browsers to pack with .NET runtime. That will make browsers bloated and also browsers are not made for that usecase.
> 
> I am not asking for browsers to pack any runtime(s). Only that the runtime on disk is used if it is installed on the client's pc. (E.g. as part of some other application, e.g. Paint .NET)
> 
> For this to work, browsers would have to check if the runtime is installed, if so, use it, and skip the download. If it is not present, default back to the current behavior.

Browser apps run in the sandbox, they don't have access to the native file system, so they cant check does user machine has runtime installed. And also what happens (in case the browser gets access to the native file system) if the blazor wasm app is built using .NET 6 and the client machine has .NET 5 installed? We cannot ask the client machine to install a specific .NET version just to visit a site, that will be a bad user experience!

**Comment by Dargazo** [comment]
> Browser apps run in the sandbox, they don't have access to the native file system, so they cant check does user machine has runtime installed.

Yes, And I don't propose browser apps gain such access. Only a way to determine if the app needs to download the runtime, or if it is already installed. Thinking perhaps a bit out of the box, maybe this can already be handle via creating an browser plugin/extension? 

> And also what happens (in case the browser gets access to the native file system) if the blazor wasm app is built using .NET 6 and the client machine has .NET 5 installed? We cannot ask the client machine to install a specific .NET version just to visit a site, that will be a bad user experience!

I agree. In the case you mention, it would default back to the current behavior (i.e. download the .NET 6 runtime from the app server.). Only if the correct runtime is already installed on the client machine, it is used by the blazor app (inserted by the browser), and downloading it from the application server be skipped.

**Comment by blowdart** [comment]
_maybe this can already be handle via creating an browser plugin/extension?_

This would be a plugin that would break the browser sandbox model and be a potential security threat because it's accessing the file system. and creating processes. This would be a non-starter from a security perspective.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
