### ISSUE TITLE
Add additional overloads for RouteValueDictionary ctor

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#40438]
`RouteValueDictionary`'s current constructor that accepts a single `value` parameter special cases `RouteValueDictionary`, `IEnumerable<KeyValuePair<string, object>>` and `IEnumerable<KeyValuePair<string, string>>`. In the case `value` is neither, it falls back to performing reflection. Since these are all runtime checks, it's not trimmer friendly. To address this, the suggestion is to add additional overloads that can turn runtime checks in to compile time checks:

```diff
public class RouteValueDictionary : IDictionary<string, object?>, IReadOnlyDictionary<string, object?>
{
+   [RequiresUnreferencedCode]
    public RouteValueDictionary(object? values);
+   public RouteValueDictionary(RouteValueDictionary? values);
+   public RouteValueDictionary(IEnumerable<KeyValuePair<string, object?>>? values);
+   public RouteValueDictionary(IEnumerable<KeyValuePair<string, string?>>? values);
}
```

**Comment by halter73** [comment]
https://github.com/dotnet/aspnetcore/pull/40430
