### ISSUE TITLE
Log format in net6.0 has changed and broken k8s log output

### ISSUE THREAD

**Issue by DanoThom** [dotnet/aspnetcore#40448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We recently upgraded out project from dotnet 3.1 -> 6x. This seems to have changed the fundamental structure of any logging being produced by ASPNET Core. If I use kubectl logs po... it now dumps out a huge wall of text whereas it used to mirror the normally formatted Console output of ASPNET Core. I've checked and it's only the new net6.0 api projects that are producing this issue.

![image](https://user-images.githubusercontent.com/4973075/155989588-9ceeced1-25a0-46e1-a530-641659e562ea.png)

Is there something I'm missing that's changed with logging that has caused this break in log output in external applications i.e. k8s etc?

### Expected Behavior

I expect the logs output in k8s to look like it used to:

![image](https://user-images.githubusercontent.com/4973075/155990175-4a4860f5-f187-43f1-a5a4-4e91d8f032dd.png)

### .NET Version

6.0.101

**Comment by martincostello** [comment]
There's information about this change at the following links:

* https://stackoverflow.com/a/70108423/1064169
* https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter
* https://github.com/dotnet/dotnet-docker/issues/3274
