### ISSUE TITLE
Blazor Server router avoid instantiating MainLayout twice

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#40455]
I have a suggestion for Blazor for an alternative Router sample or documentation where MainLayout component would not be instantiated twice but still would be used as a wrapper to display information about the page being not found.

Consider that there is a singleton component, e.g. a StatusBar or an AuthenticationPanel or any other component which should be instantiated exactly once for a user.
This is possible by placing the component into App when the component does not have any UI.
However some custom components which have UI, e.g. a StatusBar or an AuhenticationPanel (a bar at the top which shows user info or Log In button), they must be placed into the MainLayout component somewhere together with NavMenu etc.
When using the default Router with Found and NotFound, it uses MainLayout for both cases but in a way that MainLayout is instantiated for every case - both Found and NotFound. 
This is not ideal.
I don't know where to ask for a solution about this so I created his proposal for sample/documentation.

![image](https://user-images.githubusercontent.com/64279914/156075790-e06d3d28-574d-4b6b-b5cd-0c8a8b00a42d.png)

Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Your Router component can be within a single Layout and not use any layout for its views at all. If you have a `StatusBar` component which has some expensive logic to run, that component can then move out from the router in the wrapping layout.
