### ISSUE TITLE
SignalR connections start slower and slower in Firefox in VS 2022 (up to 60 seconds)

### ISSUE THREAD

**Issue by janseris** [dotnet/aspnetcore#40453]
**Update by @SteveSandersonMS** Since I've [tracked this down to be something that happens in all SignalR apps](https://github.com/dotnet/aspnetcore/issues/40453#issuecomment-1194063911), not just Blazor Server, I've changed the label to `area-signalr` so the relevant people can take a look. Lots of this discussion is about Blazor Server, but don't be distracted into thinking it's specific to that!

-----

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor Server is said to handle thousands or tens of thousands of users. 
With this behavior, best I can do is between 5 and 20 in Firefox (all subsequent circuits take 30 or 60 seconds to load).

This issue is best visible when using `render-mode="Server"` because with this setting, the page is blank white before the circuit is opened (with ServerPrerendered, the page is shown instantly and is responsive for html links but irresponsive for actual Blazor content).

When opening multiple tabs in Firefox (latest - 97.0.1 (64-bit)), circuits take longer and longer to instantiate - 1,1,2,3,5,10,20,30,60, ... seconds with more and more tabs created.
This does not happen in Microsoft Edge or Chrome.

This behavior is not affected by Firefox add-ons. I have disabled them all and the bug persists.

Note: there is no significiant CPU usage when I am waiting for the page load in Firefox. Also, opening circuits in MS Edge while waiting 60 seconds for a circuit in Firefox can be done without any issue. They will still open instantly.

This bug is present in the default .NET 6 Blazor Server application template and also in the .NET Core 3.1 Blazor Server application template. I haven't tested .NET 5 or any other.

This can be seen more clearly when overriding the default CircuitHandler which captures the lifetime of circuits.
I have created a sample application and a sample video to show this with printing into Console.

### Expected Behavior

Circuits are created instantly in Firefox, too.

### Steps To Reproduce

Create .NET 6 or .NET 3.1 Blazor Server app from template.
Switch to render-mode Server for clearer evidence.
Run the application in Firefox (I used latest - 97.0.1 (64-bit)) and open new tabs. They will take longer and longer to load - 1,1,2,3,5,10,20,30,60, ... seconds with more and more tabs created.

### .NET Version

6.0.200

### Anything else?

VS 2022 Preview (latest) and also non-preview (latest).
[Blazor Server circuits in Firefox bug.zip](https://github.com/dotnet/aspnetcore/files/8156185/Blazor.Server.circuits.in.Firefox.bug.zip)

https://user-images.githubusercontent.com/64279914/156048565-0399f456-4e5e-41d4-b1f5-64d27d9ab23d.mp4

Video: skip to 1:40 to watch the behavior in Firefox.

**Comment by TanayParikh** [comment]
Hello, thanks for contacting us. Can you please confirm if you're seeing this behavior specifically while debugging, or also in production (release build, no debugger attached).

**Comment by janseris** [comment]
> Hello, thanks for contacting us. Can you please confirm if you're seeing this behavior specifically while debugging, or also in production (release build, no debugger attached).

this happens in both Debug and Release run (without debugger) via Visual Studio.

**Comment by mkArtakMSFT** [comment]
Hi @janseris , please share your sample as a publicly hosted GitHub repo so that we can look into it.

**Comment by janseris** [comment]
> Hi @janseris , please share your sample as a publicly hosted GitHub repo so that we can look into it.

The issue can be seen in the default Blazor Server app template fór .NET6 or .NET Core 3.1

**Comment by abdollahkahne** [comment]
I test a Blazor Server App on my Firefox (97.0 64 bit) on Ubuntu both `Server` and `ServerPrerendered` mode and It works smoothly for up to 100 instance as I tried. I am using vs code and C# for Visual Studio Code (powered by OmniSharp) extension for development.

**Comment by mkArtakMSFT** [comment]
Thanks @janseris.
We'll try to repro this and go from there.

**Comment by janseris** [comment]
@mkArtakMSFT  
hi, any info on this?

**Comment by janseris** [comment]
Created a Firefox bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1781065

**Comment by SteveSandersonMS** [comment]
@janseris Thanks. It's pretty likely that people on the Firefox side won't investigate unless supplied with a repro that is reduced to some very basic HTML+JS only code, not involving any .NET (maybe just using a minimal Node.js websockets server). However please don't take this as pressure from me - totally up to you whether you choose to engage in the Bugzilla report and push that forwards.

**Comment by janseris** [comment]
@SteveSandersonMS OK, I will not provide any repro there. One reason is that I never did WebSockets/SignalR in Javascript and the second is that am solving too many other issues with .NET (especially MAUI at the moment).
