### ISSUE TITLE
Not able to run Asp.net Core 6.0 Web API on IIS 10 Windows Server 2019

### ISSUE THREAD

**Issue by Alex-Torres** [dotnet/aspnetcore#40489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Describe the bug
I built ASP.net Core 6.0 Web API using default template in Visual Studio 2022. The application is configured to use inProcess hosting, IIS as reverse proxy. I followed all the steps provided in Microsoft docs- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0. I hosted the application in IIS 10 Windows Server 2019 by creating a new application under default web site. The application pool is set to No Managed Code. When I hit the API end point, I get an error HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit. Event log has this error : Application '/LM/W3SVC/1/ROOT/WeatherAPI' with physical root 'C:\Inetpub\WWWroot\WeatherAPI' failed to load coreclr. Exception message: Managed server didn't initialize after 120000 ms. I tried many things suggested online but couldnt rectify this error. I am not sure what I am missing. Hoping someone can throw light on this issue.

Few things to note:

The same API using older versions of Dotnet core work fine. 

### Expected Behavior

I should be able to call the API endpoint using IIS both inprocess or outprocess.  

### Steps To Reproduce

Step 1: Open VS 2022
Step 2: Select ASP.net Core Web API
Step 3: Select .Net 6.0 LTS, keep the controllers checked (do not use minimal APIs)
Step 4: Publish the app to IIS using VS 2022 publish option
Step 5: Create Application under default website or Create a new website (shouldnt matter)
Step 6: Create application pool with default identity , set CLR to No managed code
Step 7: Associate the application to the above pool
Step 8: Hit the API end point from a browser

### Exceptions (if any)

For "inprocess" I get the following: 
HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit

Common solutions to this issue:
ASP.NET Core app failed to start after 120000 milliseconds
Troubleshooting steps:
• Check the system event log for error messages
• Enable logging the application process' stdout messages
• Attach a debugger to the application process and inspect

For "outofProcess", I get the following:

HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure.
Common solutions to  this issue:

- The application process failed to start
- The application process started then stopped.
- The application process started but failed to listen on the configured port. 

Troubleshooting steps:

- Check the system even log for error messages.
- Enable logging the application process 'stdout messages
- Attach a debugger to the application process and inspect. 

After inspecting the server log going into "Event Viewer": 

Windows Logs => Application:

Level: Error
Source: IIS AspNetCore Module V2

Application '/LM/W3SVC/1/ROOT "appName" with physical root C:\inetpub\wwwroot\'FilePath' failed to start process with commandline "dotnet" .appName.dll with multiple retries.  Failed to bind to port '13197'.  First 30 KB characters of captured stdout and stderr logs from multiple retries. 

### .NET Version

dotnet 6.0.102

### Anything else?

I am attempting to run this on a Windows Server 2019 Datacenter Virtual Server (VM), IIS 10.   

I have reviewed the troubleshooting IIS information available htps://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#troubleshoot-on-iis).

**Comment by adityamandaleeka** [comment]
@Alex-Torres Can you collect the stdout log using these instructions? That may give us some clues. https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#aspnet-core-module-stdout-log-iis

**Comment by Alex-Torres** [comment]
![image](https://user-images.githubusercontent.com/2220697/156637345-0565d27c-ec02-47d2-8be2-341408000edf.png)

I enabled stdout logs but they appear empty.  

I checked Event Viewer to see if additional information was generated and I see the following:
![image](https://user-images.githubusercontent.com/2220697/156637690-e73c1c56-5ee1-4b3a-8915-70fb5d9e1063.png)

**Comment by adityamandaleeka** [comment]
@Alex-Torres it looks like you don't have everything installed just yet; you just have the Desktop runtime. Can you go [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime) and install the .NET Runtime (on the left) and the Hosting Bundle (on the right)?

**Comment by Alex-Torres** [comment]
Hey @adityamandaleeka, thanks for following up.  I previously shared an old screenshot of the runtimes installed, here is the latest:

![image](https://user-images.githubusercontent.com/2220697/157242132-7c360293-3851-4c72-8cfb-5fb3d3b1f430.png)

I also ran repair and I am still having the same issues.

**Comment by HaoK** [comment]
Other than making sure you retry everything in htps://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#troubleshoot-on-iis) and see if anything new is in the std out logs or event viewer...

The lowest level you can go is turning on CORHOST_TRACE=1/CORHOST_TRACEFILE=somefile.txt to see if its even trying to load the clr: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing

**Comment by Alex-Torres** [comment]
@HaoK will try what you suggested today.

**Comment by Alex-Torres** [comment]
So apparently the issue was related to Dynatrace.  We uninstalled Dynatrace from the server and all is working now.
