### ISSUE TITLE
Passing tab character to API returns bad request

### ISSUE THREAD

**Issue by bdebaere** [dotnet/aspnetcore#40495]
Consider the API method below.

    [ApiController]
    [Route("api/[controller]")]
    public class FunctionsController : ControllerBase
    {
        [HttpGet("Search/{searchText}/{searchPattern}")]
        public IActionResult Search(
            string searchText,
            string searchPattern)
        {
            return Ok(searchText.Contains(searchPattern));
        }
    }

Calling this method with the parameters below results in the following:

 - localhost/api/Functions/Search/%00SearchText/%00: 400 bad
   request
 - localhost/api/Functions/Search/%09SearchText/%09: 400
   bad request
 - localhost/api/Functions/Search/%12SearchText/%12:
   works
 - localhost/api/Functions/Search/%20SearchText/%20: 400
   bad request

I can understand that passing %00 or %20 leads to a 400 bad request response. I would also understand it if for example %10 or %33 would lead to a 400 bad request response (they do not). However the tab character seems as mundane as any other character, especially since it can be compared to the newline character, which does not lead to a 400 bad request response.

I don't understand this limitation at all. Can someone enlighten me if this is functionality that needs to be added or if there's a reason this will never work?

**Comment by javiercn** [comment]
@bdebaere thanks for contacting us.

@Tratcher @rafikiassumani-msft I suspect this might be a combination of URL decoding + model binding.

**Comment by Tratcher** [comment]
Are you using Kestrel, IIS, or Http.Sys?
`localhost/api/Functions/Search/%00SearchText/%00` is blocked by Kestrel with `BadHttpRequestException: Invalid request target`.
`localhost/api/Functions/Search/%09SearchText/%09` isn't blocked by Kestrel, that must be failing at a higher layer.
`localhost/api/Functions/Search/%20SearchText/%20` isn't blocked by Kestrel either.

**Comment by bdebaere** [comment]
@Tratcher I can't say that I'm super familiar with Kestrel. But as I recall, it is enabled by default for ASP.NET Core projects. I simply created a new ASP.NET Core Web API for .NET 6.0 from the template. I'm testing locally. The project does not use IIS Express to run. For reference, I added the project here https://github.com/bdebaere/TabCharacterParameter.

For me at least, calling http://localhost:5013/api/Functions/Search/SearchText/%09 returns a 400 bad request response with the body below. But perhaps you will find something faulty in the code.

```
{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "One or more validation errors occurred.",
	"status": 400,
	"traceId": "00-8c0678c2d0b8c44ac3dbd0410ec23529-ea57572132f6e694-00",
	"errors": {
		"searchPattern": [
			"The searchPattern field is required."
		]
	}
}
```

**Comment by rafikiassumani-msft** [comment]
@bdebaere This is an existing behavior. Since you are sending "tab" or "space" characters, the model validation is failing. You'll need to make your parameters nullable to be able to allow those values.

**Comment by bdebaere** [comment]
@rafikiassumani-msft Excuse me, but why would %09 translate to NULL and not to \t, while %09%12 translates to "\t\u0012"?

**Comment by brunolins16** [comment]
@bdebaere `%09` is decoded to `\t` (tab character) and, as @rafikiassumani-msft answered, the current MVC behavior is to check the string value using [String.IsNullOrWhiteSpace](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=net-6.0) and because the value is just a "tab" character it is treated as a whitespace only, causing the model validation error, different than `%09%12` that will be decoded but contains more than just the "tab" character and will bind the value to the parameter. As mentioned, if your action accepts empty/null strings you can make your parameters `nullable`.

However, when you send the `\t` it is treated as a text not the escape sequence, similar to `string content = "\\t"` or  `string content = @"\t"` ([Verbatim String Literals](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#regular-and-verbatim-string-literals)). 

We could discuss if treat as text is the most correct approach, but this behavior is part of MVC behavior for a while and changing it could be a breaking change.

**Comment by bdebaere** [comment]
@brunolins16 I see now... I assume the code we are speaking about is at https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ModelBinding/Binders/TryParseModelBinder.cs#L90?

I tried overriding the behavior with a custom IModelBinder for string properties (see below for a crude implementation), which appears to work i.e. I'm getting \t in and since I'm setting ModelBindingResult to Success thus no error is thrown. I assume this is the preferred method of handling this?

```
    public class StringModelBinder : IModelBinder
    {
        public StringModelBinder(ILoggerFactory loggerFactory)
        {
        }

        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var values = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);

            if (values.Length == 0)
            {
                return Task.CompletedTask;
            }

            if (values.FirstValue == null)
            {
                return Task.CompletedTask;
            }

            var result = values.FirstValue;
            bindingContext.Result = ModelBindingResult.Success(result);
            return Task.CompletedTask;
        }
    }
```

**Comment by brunolins16** [comment]
> assume the code we are speaking about is at https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ModelBinding/Binders/TryParseModelBinder.cs#L90?

Here is the binder that will handle string types https://github.com/dotnet/aspnetcore/blob/53baae11e362b65dce5b3594d1ee3a497b186068/src/Mvc/Mvc.Core/src/ModelBinding/Binders/SimpleTypeModelBinder.cs#L71

**Comment by bdebaere** [comment]
@brunolins16 Interesting that there is a `bindingContext.ModelMetadata.ConvertEmptyStringToNull`, can this be leveraged instead of a custom IModelBinder like I did?

**Comment by brunolins16** [comment]
> Interesting that there is a `bindingContext.ModelMetadata.ConvertEmptyStringToNull`, can this be leveraged instead of a custom IModelBinder like I did?

It will probably work.However, the  `ConvertEmptyStringToNull` is set based on `DisplayFormatAttribute`
that is only allowed in Properties and Fields, not parameters.

https://github.com/dotnet/runtime/blob/9053aa1e66ab7c1af7a14e649fb0bf0b0c501cde/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/DisplayFormatAttribute.cs#L13

**Comment by brunolins16** [comment]
@bdebaere just to make sure I can provide you the best approach, what exactly you want to do when your APi receives a "tab" character?

**Comment by bdebaere** [comment]
@brunolins16 I want consumers of my API to be able to search for tabs in a string if they so desire. I don't think modifying the searchPattern to a nullable string type and searching for NULL is the right approach when the consumer passes a tab character (or a combination of any whitespace characters).

**Comment by brunolins16** [comment]
> @brunolins16 Bruno Lins de Oliveira FTE I want consumers of my API to be able to search for tabs in a string if they so desire. I don't think modifying the searchPattern to a nullable string type and searching for NULL is the right approach when the consumer passes a tab character (or a combination of any whitespace characters).

Based on that, unfortunately MVC will not support it by design, I recommend you create your own binder that have total control over the binding, however, if you want to use the `ConvertEmptyStringToNull` you can create a custom attribute to use with your parameter, otherwise you will need to apply the attribute to a property or field, and work with the correct validation needed.

``` csharp
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class DoesNotConvertStringToNullAttribute : DisplayFormatAttribute
{
    public DoesNotConvertStringToNullAttribute()
    {
        ConvertEmptyStringToNull = false;
    }
}
```
