### ISSUE TITLE
Update `RouteHandlerFilterContext.Parameters` API

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#40514]
Follow-up to https://github.com/dotnet/aspnetcore/pull/40491

```diff
- public sealed class RouteHandlerInvocationContext
+ public class RouteHandlerInvocationContext
{
-  public HttpContext HttpContext { get; }
+ public virtual HttpContext HttpContext { get; }

- public List<object?> Parameters { get; }
+ public virtual List<object?> Parameters { get; }

+ public virtual T GetParameter<T>(int index) { }
}
```

**Comment by captainsafia** [comment]
Moving this back into .NET 7 Planning to prioritize completing the performance tests in https://github.com/dotnet/aspnetcore/issues/40655 for preview3.

**Comment by captainsafia** [comment]
We've added performance tests for some basic scenarios with minimal APIs and route handler filters.

- A route handler with no parameters and no filter
- A route handler with no parameters and a "pass through filter"
- A route handler with parameters and a "pass through filter"
- A route handler with parameters and a filter

All the route handlers above tested on a string input/output for the route handler. While testing other input/output types might provide more "real world" values, the bare scenario is sufficient for observing the net impact of the barebones filters logic.

All told, adding a filter to an endpoint reduces throughput (measured in RPS) by about 9%. There's generally a bigger impact when adding parameters to an endpoint filter and parameter processing is a larger cost in the process than endpoint filters.

Regardless of the perf impact, IMO, this work is relevant to pursue because exposing parameters as an untyped list is 🤢 .

**Comment by halter73** [comment]
API Review Notes:

- Should we make the generic implementations public?
  - This seems noisy and low value.
- Abstract?
  - Yes. Let's save some fields
-  `Parameter` -> `ParameterValues`? `Arguments`?
  - Let's go with `Arguments` and `GetArguments`

```diff
- public sealed class RouteHandlerInvocationContext
+ public abstract class RouteHandlerInvocationContext
{
-     public RouteHandlerInvocationContext(HttpContext httpContext, params object[] parameters)

-    public HttpContext HttpContext { get; }
+    public abstract HttpContext HttpContext { get; }

-     public IList<object?> Parameters { get; }
+     public abstract IList<object?> Arguments { get; }

+     public abstract T GetArgument<T>(int index) { }
}

+ public class DefaultRouteHandlerInvocationContext : RouteHandlerInvocationContext
+ {
+     public RouteHandlerInvocationContext(HttpContext httpContext, params object[] parameters)
+
+     public override HttpContext HttpContext { get; }
+     public override IList<object?> Arguments { get; }
+     public override T GetArgument<T>(int index) { }
+ }
```
