### ISSUE TITLE
Build fails if Blazor Parameter namespace matches a nested namespace

### ISSUE THREAD

**Issue by Kloizdena** [dotnet/aspnetcore#40524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Server-side project named BlazorApp1. There is an external type that I want to use as the parameter of my Blazor component:
**Data.cs**
```csharp
namespace NS1
{
	public class Data
	{
	}
}

```

I have another nested namespace containing some other types:
**NS1.cs**
```csharp
namespace BlazorApp1.NS1
{
	// ...
}
```

**ParentComponent.razor**:
```razor
@using global::NS1
<ChildComponent Data=data></ChildComponent>
@code {
    private Data data = new();
}

```

**ChildComponent.razor**:
```razor
@using global::NS1

@code {
    [Parameter]
    public Data? Data { get; set; }
}

```

When I want to build it, I get the following error:

```
1>C:\src\BlazorTest\BlazorApp1\BlazorApp1\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Components_ParentComponent_razor.g.cs(95,133,95,137): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'BlazorApp1.NS1' (are you missing an assembly reference?)
1>C:\src\BlazorTest\BlazorApp1\BlazorApp1\Components\ParentComponent.razor(2,22,2,26): error CS1503: Argument 1: cannot convert from 'NS1.Data' to 'BlazorApp1.NS1.Data'
```

I get the same error when I use the global namespace on the property:
```razor
public global::NS1.Data? Data { get; set; }
```

I also tried with namespace alias, but I got the same result:
```razor
@using N = global::NS1

@code {
    [Parameter]
    public N.Data? Data { get; set; }
}

```

Checking the generated output, the global namespace is missing from the generic parameter:
```csharp

namespace BlazorApp1.Components
{
 // ...
    public partial class ParentComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<BlazorApp1.Components.ChildComponent>(0);
            __builder.AddAttribute(1, "Data", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<NS1.Data>(
#nullable restore
#line 2 "C:\src\BlazorTest\BlazorApp1\BlazorApp1\Components\ParentComponent.razor"
                     data

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseComponent();
        }
```

May be related to https://github.com/dotnet/aspnetcore/issues/12116

### Expected Behavior

The project should build without errors.

### Steps To Reproduce

Add the above code to a .NET 6 Blazor Server-side project and try to build it.

### .NET Version

6.0.200

**Comment by pranavkm** [comment]
Could you try building your app with a nightly build of the 7.0 SDK? A fair number of these issues were to due to not fully qualifying types in the generated code which were addressed as part of #18757

**Comment by Kloizdena** [comment]
@pranavkm I tried it out, and it works with with .NET 7 preview SDK. Thank you!

**Comment by pranavkm** [comment]
Thanks! Great to have a confirmation. SDKs are highly backwards compatible against previously shipped runtime versions / tfms, so feel free to continue using it if it unblocks your scenario.

FYI @javiercn
