### ISSUE TITLE
ViewEngine can't find view in RCL without 'Views' folder in WebAPI project

### ISSUE THREAD

**Issue by Martijn-W** [dotnet/aspnetcore#40537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When referencing a Razor Class Library from a WebApi project, the ViewEngine can't find any views.
Only when you create a folder named 'Views' in the root of the WebApi project the ViewEngine will be able to pick up views inside of the RCL.

### Expected Behavior

I expect that the WebApi project can find views in the RCL project without a 'Views' folder in the WebApi project.

### Steps To Reproduce

1. Create a new ASP Web Api project
2. Create a new RCL project
3. Reference the RCL project in the Web Api project
4. Create a view inside the RCL (e.g. 'Views/Subfolder/MyTestView.cshtml')
5. Implement a view -> string renderer in the Web Api Project (example: see point 6; [https://www.learnrazorpages.com/advanced/render-partial-to-string](https://www.learnrazorpages.com/advanced/render-partial-to-string))
6. Observe that the Web Api Project cannot find the view
7. Create a 'Views' folder in the root of the Web Api project
8. Observe that the view can be found

### .NET Version

6.0.101

### Anything else?

ASP .Net version: 6.0.1
OS: WSL/Linux
Environment: Docker

**Comment by pranavkm** [comment]
I tried returning a View from a controller action and that [appears to work just fine](https://github.com/pranavkm/ViewsRepro). It's likely that the tutorial you are using is incorrect. 

We have a sample of rendering a view to a string available her: https://github.com/aspnet/Entropy/tree/master/samples/Mvc.RenderViewToString, you could try using that to see if it helps here.

**Comment by Martijn-W** [comment]
@pranavkm Thank you. Your examples seems to work just fine. 
This issue can be closed :)
