### ISSUE TITLE
Reactive HubConnectionState

### ISSUE THREAD

**Issue by lepicekmichal** [dotnet/aspnetcore#40536]
Right now, I can access connection status via method com.microsoft.signalr.HubConnectionState.getConnectionState(). However I am not getting updates reactively. I don't know when the state changes.

Please implement state changes through reactive pattern, some observable.

[Android]

**Comment by BrennanConroy** [comment]
All the state transitions have a hook already so you can implement this feature yourself.
Connected state is when HubConnection.start completes
Disconnected state is when HubConnection.onClosed is called

And those are the only two interesting states today.
