### ISSUE TITLE
Rewrite React template as function component with hooks

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#40540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The React community has largely moved on from the old class-based components and now favors function components with hooks.

### Describe the solution you'd like

Rewrite the `Counter.js`, `FetchData.js`, `Home.js`, `Layout.js`, `NavMenu.js` and `App.js` files to use a function component with hooks.

### Additional context

Use the [`useState`](https://reactjs.org/docs/hooks-state.html) hook.

**Comment by javiercn** [comment]
@vanillajonathan thanks for contacting us.

This is not something we plan to do in the near future. Code in the templates is a starting point and updating them is costly without a clear benefit on using a different pattern.

If you have a concrete proposal and we think its reasonable, we might be open to accepting a PR

**Comment by Vadimyan** [comment]
Hi! I've prepared a PR https://github.com/dotnet/spa-templates/pull/41 with fully refactored react template. Now it use functional components with react hooks. Also I brought the code in template to a single code style. 

But now I think that it can be a good time to rewrite this template to typescript. It can help beginners to start learning aspnet with TS from the template, and in the case of new projects, it'll allow developers not to rewrite existing code to TS. 

Is it worth creating a separate issue about it or could it be part of the discussion of the current one?

**Comment by vanillajonathan** [comment]
Good job @Vadimyan!
I think TypeScript is a separate issue. Nonetheless interesting.

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck do you remember if the updated you've made to the templates were equivalent to regenerating new react app? Our approach should be to keep the template as aligned with new react and angular apps as possible.

**Comment by mkArtakMSFT** [comment]
Closing this as we have removed the SPA project templates from the SDK in .NET 8.
