### ISSUE TITLE
Unable to write Integration Tests for Blazor Webassembly (deps.json is missing) and Dependency Injection

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#40549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.NET Core - 6
Blazor Webassembly (Standalone)
Visual Studio 2022

I have a standalone Blazor Webassembly that make calls to protected APIs. I have integration tests for this Blazor Webassembly via a xUnit project

As per [asp.netcore docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0) I am using the WebApplicationFactory to setup the test fixture but I get error whenever I try to create an instance of a service that uses Dependency Injection

    public class BlazorWebAssemblyTests
    {
        public BlazorWebAssemblyTests()
        {
            factory = new WebApplicationFactory<Program>();

           // THIS LINE CAUSES the (deps.json is missing) error
            accelerator = ActivatorUtilities.CreateInstance<IBlahService>(factory.Services);
        }

        [Fact]
        public void BlahTest_ShouldPass()
        {
             accelerator.GetBlahResult().Should().Be(true);
        }

        private IBlahService accelerator;
        private WebApplicationFactory<Program> factory;
    }

I get this error

Can't find '***\bin\Debug\net6.0\TestBlazorAssembly.deps.json'. This file is required for functional tests to run properly. 

I looked at the build output the **.deps.json** is not generated for BalzorWebassembly.  

I also tried setting `<PreserveCompilationContext>true</PreserveCompilationContext>` but  it does not help.

### Expected Behavior

I should be able to write Integration tests for Blazor Webassembly similar to ASP.NET Core or a Blazor Server project.

### .NET Version

6.0.200

**Comment by javiercn** [comment]
@ameyasubhedar thanks for contacting us.

This is not a scenario WebApplicationFactory is designed for.  We recommend you use a browser automation framework like Playwright for this.
