### ISSUE TITLE
Add `AuthorizationFilterAttribute` likes `ActionFilterAttribute`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#40542]
## Background and Motivation

It's simple to define a custom action filter via inheriting the `ActionFilterAttribute`, maybe we could add `AuthorizationFilterAttribute` likes `ActionFilterAttribute` to simplify the custom authorization filter

## Proposed API

```diff
namespace Microsoft.AspNetCore.Mvc.Filters;

+ [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
+ public abstract class ActionFilterAttribute : Attribute, IAuthorizationFilter, IAsyncAuthorizationFilter
+ {
+     public virtual void OnAuthorization(AuthorizationFilterContext context) {}
+     public virtual Task OnAuthorizationAsync(AuthorizationFilterContext context)
+     {
+         ArgumentNullException.ThrowIfNull(context);
+         OnAuthorization(context);
+         return Task.CompletedTask;
+      }
+ }

```

## Usage Examples

``` C#
public class MyAuthorizationFilterAttribute: AuthorizationFilterAttribute
{
    public override void OnAuthorization(AuthorizationFilterContext context) 
    {
        // ...
    }
}
```

Use on controller or action  as attribute

``` c#
public class ValuesController: ControllerBase
{
    [MyAuthorizationFilter]
    public IActionResult Index(){}
}
```

## Risks

Since it would be a new type, think it's no risk from what I can see

**Comment by pranavkm** [comment]
The filter attributes exist for backwards compatibility with MVC5. For most MVC filter types, we'll recommend implementing the interfaces instead. You're of course free to have it be an attribute to. Specifically with authorization, we would recommend considering using the authorization middleware via authorization policies and authorization handlers since it works better with the `AuthorizationMiddleware`.

**Comment by WeihanLi** [comment]
Hi @pranavkm , thanks for your reply, I think sometimes the `AuthorizationFilter` is more simple to use, it can be used without having any knowledge about the authentication design and the authorization system

**Comment by javiercn** [comment]
@WeihanLi thanks for contacting us.

This is not a direction we plan to move in the future.
