### ISSUE TITLE
Visual Studio 2022 v 17.1 corrupting serviceworker.js when publishing to Windows app service not Linux app service

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#40544]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-v-171-corrupting-ser/1676444)._

---
[severity:It's more difficult to complete my work]
When using Visual Studio 2022 to publish a Blazor WASM PWA to an Azure Web Service the following character are appended to the serviceworker.js file: ⨯䴠湡晩獥⁴敶獲潩㩮删啚楎祓⁉⼪਍.  This does not happen when the same application is published to an Azure Linux app service.  The additional characters result in the serviceworker.js failing on install and the app not being registered as a PWA.  This failure results in the "install this app' option to be hidden in the browser.  Also, using the browser developer tools will show that the Service Worker is not registered.  Attached is the serviceworker.published.js file as it is currently in the application and the serviceworker.js file that was copied using Kudu from the actual web app.  

To replicate this problem create a new Blazor WASM PWA hosted in asp.net and publish to both an Azure Linux web app and an Azure Windows web app.  The PWA published in the Linux web app should behave as expected while the Windows app service will not.
[Corrupted ServiceWorker.js.txt] (https://aka.ms/dc/file?name=B5d566afa9cf64bd89c29be3485376c46637813113137635951_Corrupted_ServiceWorker.js.txt&tid=5d566afa9cf64bd89c29be3485376c46637813113137635951)
[serviceworker.published.js.txt] (https://aka.ms/dc/file?name=Bc0a20c69692b40a6bdd58c298a4df7dd637813113714250380_serviceworker.published.js.txt&tid=c0a20c69692b40a6bdd58c298a4df7dd637813113714250380)

---
#### Feedback Bot on 2/24/2022, 09:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/27/2022, 11:26 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We would need a minimal repro project as a public github repository to make progress on this issue.

I would suggest cleaning the bin and obj folders before publishing in case that helps.

**Comment by mareich555** [comment]
I cleaned the bin and obj folders but the problem still persists.  I have never participated in bug tracking before so I need to know exactly what needs to be in the public GitHub project.  The project requires Azure, Google and OpenWeather api access to function and the credentials are kept in Azure secrets.  Must the application be functional to debug this problem or must it just compile for publishing?  Thx.
