### ISSUE TITLE
Reporting and Printing In Blazor

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/aspnetcore#40557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Blazor should have **At least basic level of built-in components** 
for Reporting and Printing that can be further extended by developer as per their need like :-

1. Pdf-Generator And Viewer Components.
2. Fully Bound/Unbound DataGrid Component.
3. Print Preview & Direct Printing Capabilities.

Thease are the main features required for enterprise level of applications..
please consider

Regards-
Sanjeeb

**Comment by javiercn** [comment]
@hintsofttech thanks for contacting us.

Our team is focused on delivering a great runtime/framework to build Blazor applications. This is not something we plan to tackle in the near future as there is a rich ecosystem of third party components that we think better supports these scenarios.

**Comment by hintsofttech** [comment]
> third party components

every developer don't want to depend on third party controls.
at least basic levels fo components should be built in..
