### ISSUE TITLE
[investigation] - Investigate option `useMordernNet` of omnisharp for aspnetcore codespaces

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#40560]
Recently omnisharp team announced a new option of `omnisharp.useMordernNet` in omnisharp settings. By default, it set it to false as it's under preview. What basically this option does is that it uses MSBuild from installed SDK itself instead of using MSBuild from the omnisharp package. 
For personal usage, I am using this option right from the beginning for `aspnetcore` and other .NET codespaces repositories. I find it really good and I experience a quite good performance boost in terms of analysis of projects and intellisense that omnisharp provides. 

I am planning to have this option enabled by default for `aspnetcore` but before that I want people and team members (those who use codespaces for development) to try it out, on their own by modifying the `devcontainer.json` file and adding `"omnisharp.useModernNet": true` under settings node. (you need to rebuild the container to take effect). 

It does work great, but I do have a concern about the confusing logs that omnisharp split, once this option gets enabled. 

If you see the below image, it shows that the omnisharp server started with .NET 7 SDK (which at the time was mentioned in global.json in aspnetcore repo). But then it found an `MSBuild` instance of .NET core SDK 6.0.101 17.0.0 under workspace `.dotnet` folder. And then it registered that .NET 6 `MSBuild` instance for usage, so is that correct? Or it should use .NET 7 MsBuild instance? 

I checked after that, the intellisense and other things work perfectly fine, but shouldn't it use .NET 7 instance? Or this is correct? This is not a question to omnisharp people, I am just figuring out do we need to do anything in settings of omnisharp so that it will use correct instance.  

![image](https://user-images.githubusercontent.com/17148381/156919502-2a16189f-5303-4a4a-b98e-588bc75a13f8.png)

Tagging people here that I know who uses codespaces @captainsafia @TanayParikh and @filipw for omnisharp question that I have! :)

**Comment by filipw** [comment]
A .NET 6.0 build of OmniSharp is a framework dependent application, which is started with `dotnet OmniSharp.dll`, so it may end up using the newer framework than 6.0, but it cannot be lower than 6.0.100 https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/OmniSharpDotnetResolver.ts#L15

The MSBuild Resolver that is used to located MSBuild, however, is the resolver which is in sync with 6.0 SDK https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tools/packages.config#L17 so it will only find the SDK from the 6 "generation".

Overall the performance and stability of the .NET 6.0 build will be much better so I would recommend setting it. It will become the default one quite soon anyway, though that decision lies in the hands of @JoeRobich

**Comment by captainsafia** [comment]
I actually spotted this flag in the PR introducing Codespaces to the efcore repo and thought it would be interesting to adopt.

I'm cool waiting until this is the default and adopting it "automagically" via a C# extension update so we have less config to manage.

**Comment by TanayParikh** [comment]
Thanks @ShreyasJejurkar for the suggestion. Based on @filipw & @captainsafia's comments above, I believe we'll hold off on this change until we can consume it directly from O#. Closing out this issue.
