### ISSUE TITLE
Blazor WASM : Adding MVC Route does not work on published version but works on lcoal

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#40565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am creating Blazor Client(wasm) hosted PWA App. with .NET 6.

I added MVC controller support to it and created necessary routes.
**NOTE: I am modifying the original Blazor WASM hosted project by adding MVC support to it**

The App works perfectly fine as expected when running it from Visual Studio 2022 Preview in Local Development.
But when deployed to Azure App Service(windows), none of the MVC related routing is working and instead it defaults back to index.html of Blazor wasm. Why is there difference in behaviour when published to Azure App Service vs Running it from Visual Studio 2022 dev environment ?

I have added the following in(only partial lines are shown here) program.cs (Server Side)
```
builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();
app.UseBlazorFrameworkFiles();
app.UseStaticFiles();
app.UseRouting();

app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllers();

    endpoints.MapControllerRoute(
        name: "MVC",
        pattern: "MVC/{controller=LandingPage}/{action=Index}/{id?}");

    endpoints.MapControllerRoute(
       name: "QrCode",
       pattern: "QRCode/{controller=QrCode}/{action=Index}/{id?}");

    endpoints.MapControllerRoute(
       name: "default",
       pattern: "{controller=Home}/{action=Index}/{id?}");

    endpoints.MapHub<GetInLineSignalRHub>("/MySignalRHub");
   
    endpoints.MapFallback(HandleFallback);
   
});

```
When i run it from Visual studio 2002 Preview

https://localhost:5001/QrCode?tokenguid=jkllkjkooooo 
(Works as expected: loads the page with QRCode Generated for supplied value)

https://localhost:5001/mvc/landingpage 
(Works as expected: loads the landing page)

https://localhost:5001/index.html 
(Works as expected, loads Blazor Wasm)

When i deploy it to Azure App Service, 

https://localhost:5001/QrCode?tokenguid=jkllkjkooooo
 Does not works, instead loads index.html(which is Blazor wasm page)

https://localhost:5001/mvc/landingpage (loads the landing page)
  Does not works, instead load index.html(which is Blazor wasm page)

https://localhost:5001/index.html 
(Works as expected, loads Blazor Wasm)

### Expected Behavior

It should display content from MVC route/view  as it does during the Local development in Visual Studio 2022 Preview

### Steps To Reproduce

Add MVC Controller and view in the server side hosted project in Blazor wasm hosted project.
Add Routes for the MVC routing.

### Exceptions (if any)

None

### .NET Version

6.0.200-preview.22055.15

**Comment by nssidhu** [comment]
Here is the git repo for source code.
https://github.com/nssidhu/BlazorWasmHostedWithMVCV

**Comment by javiercn** [comment]
@nssidhu The issue is in your service worker code.

You need to update it to avoid serving the paths for the controllers.

**Comment by nssidhu** [comment]
@javiercn I did not get what need to be fixed, can you elaborate on what need to be fixed or what fix need to be applied ?

**Comment by javiercn** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-6.0&tabs=visual-studio#support-server-rendered-pages

**Comment by nssidhu** [comment]
@javiercn , Thanks that helped.
