### ISSUE TITLE
Minor error in null checking of constructor of Microsoft.AspNetCore.Routing.Template class.

### ISSUE THREAD

**Issue by jiabiao** [dotnet/aspnetcore#40571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Http/Routing/src/Template/TemplateParser.cs#L22

Should be 

```csharp
throw new ArgumentNullException(nameof(routeTemplate));  
```

**Comment by javiercn** [comment]
@jiabiao thanks for contacting us.

Feel free to send us a PR
