### ISSUE TITLE
build fails for new WebAPI project after switching to TargetFrameworks (plural)

### ISSUE THREAD

**Issue by astaerk** [dotnet/aspnetcore#40577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a ASP.Net Core Web API project with a reference to 'Swashbuckle.AspNetCore'.
When I switch to TargetFrameworks (plural) in the project file, I get two build errors:

> No method 'BuildWebHost', 'CreateHostBuilder' or 'CreateWebHostBuilder' found in type 'Program' with expected signatures.	TestAPI	C:\Users\<username>\.nuget\packages\microsoft.extensions.apidescription.server\3.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets	62

and

> MSB3073	The command "dotnet "C:\Users\<username>\.nuget\packages\microsoft.extensions.apidescription.server\3.0.0\build\/../tools/dotnet-getdocument.dll" --assembly "C:\dev\projects\misc\ASPWebAPITargetFrameworksError\TestAPI\bin\Debug\net6.0\TestAPI.dll" --file-list "obj\TestAPI.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v6.0" --output "obj" --project "TestAPI" --assets-file "C:\dev\projects\misc\ASPWebAPITargetFrameworksError\TestAPI\obj\project.assets.json" --platform "AnyCPU" " exited with code 4.
C:\Users\<username>\.nuget\packages\microsoft.extensions.apidescription.server\3.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets	62	

The project works fine as long as I stick to tag TargetFramework (singular).
It also seems to work when I remove the PackageReference to Swashbuckle.AspNetCore and all its usages. But that removes OpenAPI support obviously.

In the end I'm trying to switch to TargetFrameworks (plural) to be able to target multiple versions of .NET. But it doesn't seem to make a difference if I actually use multiple versions or if I only leave it with net6.0. As soon as I use the plural version it no longer builds.

### Expected Behavior

The project should build with the same output no matter if I use TargetFramework or TargetFrameworks.

### Steps To Reproduce

I created a small demo project for this:
[https://github.com/astaerk/ASPWebAPITargetFrameworksError](https://github.com/astaerk/ASPWebAPITargetFrameworksError)

This is a new/empty project where I just switched from TargetFramework to TargetFrameworks. When you try to build this project, you will get two errors.

Here is a description of what I did:
1. create a new project using the template 'ASP.NET Core Web API' in VS2022
(.NET 6.0, Authentication: None, Configure for HTTPS = true, Docker = false, use controllers = true, enable OpenAPI = true)
2. open project file and change _TargetFramework_-Tag to _TargetFrameworks_ (plural)
3. reload the project in VS (VS asks you to do so)
4. rebuild the project -> 2 build errors occur

### .NET Version

6.0.200

### Anything else?

Visual Studio 2022 (17.1.0) on Windows 10 21H2

.NET SDK (gemäß "global.json"):
 Version:   6.0.200
 Commit:    4c30de7899

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by captainsafia** [comment]
Resolved by updating the M.E.ApiDescription.* dependencies in NSwag.
