### ISSUE TITLE
SignalR cant invoke a parameterless method

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/aspnetcore#40573]
when I have a method that has no parameters

```cs

public async Task TestSignalR()
{
    ..
}
```

and then using `SenAsync("TestSignalR")` the method does not get invoked.
however when I use a parameter

```cs
public async Task TestSignalR(string data) 
{
    ..
}
```
and then using `SendAsync("TestSignalR", "random content")` it gets invoked.

**Comment by BrennanConroy** [comment]
What client are you using? What version(s)? Are you calling `SendAsync` from the server or the client?
A minimal repro as a github repo would be helpful.

**Comment by HeroinGyrl** [comment]
> What client are you using? What version(s)? Are you calling `SendAsync` from the server or the client? A minimal repro as a github repo would be helpful.

I'm using for the client the nuget package `Microsoft.AspNetCore.SignalR.Client 7.0.0-preview.1.22109.13` and a normal blazor server app. I mean everything works but it just dont invoke a parameterless method.

`SendAsync` is called from the client to the server.

`public async Task TestSignalR()` - `SendAsync("TestSignalR")` - `not working`
`public async Task TestSignalR(string content)` - `SendAsync("TestSignalR", "random content")`  - `working`

**Comment by BrennanConroy** [comment]
Please provide a minimal repro as a github repo.

**Comment by HeroinGyrl** [comment]
> Please provide a minimal repro as a github repo.

sorry, there was a nullable check which caused to stop sending any commands to the server, everything works now.
