### ISSUE TITLE
Blazor Standalone WebAssembly with MSAL Microsoft work accounts does not return JWT (access_token)

### ISSUE THREAD

**Issue by apspi** [dotnet/aspnetcore#40582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a use case where we support Microsoft accounts (any org and personal) to log in. The preview version of this is here [https://marketplace.perpetualintelligence.com/](https://marketplace.perpetualintelligence.com/). build with .NET6 and Blazor Standalone Webassembly

We have used the official recommendation as per Microsoft docs [ Secure Blazor WebAssembly standalone app with Microsoft Accounts](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-6.0)

The authentication with Azure AD works flawlessly, and I can authenticate the incoming users (within my tenant, any other tenant, or any other Microsoft personal account).

Authority is https://login.microsoftonline.com/common

App Registration in Azure Portal is  SPA

![image](https://user-images.githubusercontent.com/13166236/157089169-113387e6-5f82-4f0d-a8ba-5256b1c6dd30.png)

All Microsoft accounts
![image](https://user-images.githubusercontent.com/13166236/157089312-14bf232c-bdf0-4bac-a316-78a38de64f26.png)

Appsettings
![image](https://user-images.githubusercontent.com/13166236/157089541-01a0bf64-2a97-4193-b72a-5f64c305ff74.png)

After authentication, the MSAL generates an access_token, not in JWT format. And this causes the backend not to be able to validate the token.

Browser snapshot after authentication
![image](https://user-images.githubusercontent.com/13166236/157093858-b50cc43d-fb00-4507-87c1-3c54825cea0e.png)

So I have two issues here:

1. Why is MSAL generating an access_token that is not in JWT format?
2. If this is expected for MSAL to generate an opaque or an encrypted JWT, How does the backend API validate the generated non-JWT token and check the claims?

I have backend Azure functions that need to validate the access_token and check specific claims and roles before further actions.

This is blocking issue for us, how do I achieve token validation here?

### Expected Behavior

Either a JWT token or ability to validate the encrypted access_token at the backend API.

### .NET Version

6.0.200

### Anything else?

Blazor Web Assembly
Visual Studio 2022
MSAL

**Comment by rafikiassumani-msft** [comment]
@ameyasubhedar This could be related to your app configuration in Azure AD. Do you mind creating an issue at the following msal repository:https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

**Comment by ameyasubhedar** [comment]
@rafikiassumani-msft, My App Configuration seems correct in Azure AD. Not sure what is wrong ? Also created an issue with msal.

**Comment by MackinnonBuck** [comment]
Closing this out since it's not clear that there is an issue with the framework. Please open a new issue if you continue to experience the problem and believe it is a bug in Blazor.
