### ISSUE TITLE
No brotli compression _blazor

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#40581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While doing the tests, it showed an error that the page ``_blazor`` does not have data compression.
This is the server side version
![image](https://user-images.githubusercontent.com/42449535/157089917-9db402aa-dc73-4ebc-81e0-6ebd594107d5.png)
![image](https://user-images.githubusercontent.com/42449535/157089970-d6131936-7b4c-46c7-8298-ee9ca28f59e2.png)

### Expected Behavior

How to compress the page ``_blazor``?

### Steps To Reproduce

Startup:
```cs
            services.Configure<BrotliCompressionProviderOptions>(o =>
            {
                o.Level = CompressionLevel.Optimal;
            });
            services.Configure<GzipCompressionProviderOptions>(o =>
            {
                o.Level = CompressionLevel.Optimal;
            });
            services.AddResponseCompression(options =>
            {
                options.EnableForHttps = true;
                options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] {
                    "application/javascript",
                    "application/json",
                    "application/xml",
                    "application/xhtml+xml",
                    "text/css",
                    "text/json",
                    "text/plain",
                    "text/html",
                    "text/plain",
                    "text/xml",
                    "image/jpeg",
                    "image/png",
                    "image/webp",
                    "application/font-woff2",
                    "image/svg+xml",
                    "image/x-icon",
                    "image/svg+xml",
                    "font/woff2",
                });
                options.Providers.Add<BrotliCompressionProvider>();
                options.Providers.Add<GzipCompressionProvider>();
            });
```
```cs
            app.UseResponseCompression();           // Compression
            app.UseHttpsRedirection();              // wwwroot
            app.UseStaticFiles();
```
I use "text/plain" compression, am I doing something wrong or is it a bug?

### .NET Version

.net core 7 preview

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

From what I can tell you are using Blazor Server.

It seems to me that you are trying to apply Brotli compression to the underlying SignalR endpoint, which is not something we currently support.
