### ISSUE TITLE
Using HttpContextAccessor in Asp.NET Core hosted Blazor Web Assembly throws error

### ISSUE THREAD

**Issue by Lingala-Joshna** [dotnet/aspnetcore#40590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to get the User details in ASPNET Core Hosted Blazor Web Assembly application using HttpContextAccessor it throws the below error

![image](https://user-images.githubusercontent.com/93309503/157224347-7bb79c07-62b5-4303-b9dd-e76b01a22fea.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/93309503/157224546-e7ab8e46-6091-44b1-8b1c-d73733ed7c57.png)

### .NET Version

.NET5.0
.NET6.0

Thanks in advance.

**Comment by javiercn** [comment]
@Lingala-Joshna thanks for contacting us.

HttpContextAccessor is not available in Blazor Webassembly.

**Comment by Lingala-Joshna** [comment]
Hi @javiercn ,

Thanks for the update.

Is there any possibility that HttpContextAccessor can be used in AspNet Core Hosted Webassembly application to get the User details.

Regards,
Joshna
