### ISSUE TITLE
Use Vite in the SPA templates

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#40594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

[Vite](https://vitejs.dev/) is a front end tooling with lightning fast Hot Module Replacement (HMR).
Instead of recompiling the whole application it just replaces the module that changed, this makes it very fast, especially for larger SPAs resulting in a better developer experience through a faster inner development loop.

This would replace the [`http-proxy-middleware`](https://www.npmjs.com/package/http-proxy-middleware) npm package. This should allow us to get rid of the `aspnetcore-https.js `and `aspnetcore-react.js` files from the `ClientApp` directory. Less boilerplate code. More generic with no ASP.NET-specific code or configuration. Easier configuration with [`vite.config.js`](https://vitejs.dev/config/).

### Describe the solution you'd like

Replace `http-proxy-middleware` with `vite` in the SPA templats (Angular and React).

**Comment by javiercn** [comment]
@vanillajonathan thanks for contacting us.

We don't plan to deviate from what the default angular/react experience offers. We will consider updating to vite if they do so within `ng new` or `create-react-app`
