### ISSUE TITLE
Build ASP.NET Core from Source error 

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/aspnetcore#40596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
The download is for the main branch code
When I run` . \restore.cmd` the end result shows an error

![image](https://user-images.githubusercontent.com/27860834/157276413-01074f30-6e15-4864-80f0-020a103ceacb.png)

Failed to install dotnet from any of the specified locations.
C:\Users\Administrator\.nuget\packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22117.2\tools\InstallDotNetCore.targets(15,5): error : dotnet-install failed [C:\Users\Administrator\.nuget\packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.2211
7.2\tools\Tools.proj]

A repeat of https://github.com/dotnet/aspnetcore/issues/37442

**Comment by quan0zhou** [comment]
The download is for the main branch code

**Comment by wtgodbe** [comment]
Could be a transient issue with dotnet-install, @dotnet/dnceng is there a known outage?

**Comment by dougbu** [comment]
@quan0zhou the other possibility is you have an older version of the dotnet-install.ps1 script in your E:\Code\aspnetcore-main\.dotnet\ folder. Please remove that file and try again.

If it matters, I was able to restore everything w/o error earlier today.

**Comment by missymessa** [comment]
It looks like this on your personal machine? Have you followed the instructions @dougbu provided?

**Comment by quan0zhou** [comment]
Contents of the dotnet-install.ps1 file
[dotnet-install.txt](https://github.com/dotnet/aspnetcore/files/8211142/dotnet-install.txt)

**Comment by quan0zhou** [comment]
I found the reason, it just so happens that the paragraph reporting the error is `\aspnetcore\.dotnet\x86\dotnet-install.ps1 `execution, I know by printing the marker
![image](https://user-images.githubusercontent.com/27860834/157370328-6bf1418a-01c2-489d-962d-15f36024fdb2.png)
Because in dotnet-install.ps1 I modify this script, at line 1073 of the code, On my computer $diskInfo.Free / 1MB = 0, so it keeps reporting errors
` 
if ( ($null -ne $diskInfo) -and ($diskInfo.Free / 1MB -le 100)) {
        throw "There is not enough disk space on drive ${installDrive}:"
    }
`
![image](https://user-images.githubusercontent.com/27860834/157371433-f46f62c2-d7bc-4a58-845b-d2c194fdcff2.png)
