### ISSUE TITLE
Allow validation attributes on PageModel itself

### ISSUE THREAD

**Issue by danielgreen** [dotnet/aspnetcore#40591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is this a Bug or Feature request: Feature request

See https://github.com/dotnet/aspnetcore/issues/4911

4 years on from that issue being raised, it is still not possible to have automatic validation of a Razor Pages PageModel.
Having to run validation manually, or create an extra class to be a child property of the PageModel is self-defeating.

Could that be addressed in .NET 7?

### Describe the solution you'd like

Please enable automatic validation of PageModels

**Comment by javiercn** [comment]
@danielgreen thanks for contacting us.

Unfortunately, we haven't changed or mind from the issue you linked to. There are problems with doing this regarding accidentally validating deep object graphs that we don't think set up people for success.
