### ISSUE TITLE
Blazor server - Using IJSStreamReference after browser reconnect throws "Cannot send data if the connection is not in the 'Connected' State"

### ISSUE THREAD

**Issue by Mrlten** [dotnet/aspnetcore#40608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our application we use `IJSStreamReference`s to transfer data (Blobs) from the browser to the server. We've found the following bug in that functionality:

When you've used a `IJSStreamReference` in the current Blazor session, let the browser lose its connection (so the reconnect message is shown), reconnect again and use a (new) `IJSStreamReference`, you'll get the following error in the browser: `Cannot send data if the connection is not in the 'Connected' State`. And after a while (30 seconds or so?) you'll get a `TimeoutException` at the server.

Note that we don't reuse the `IJSStreamReference` and put the correct `using` statements in the code. See the Steps To Reproduce for the link to a small sample project.

### Expected Behavior

`IJSStreamReference` can be used after the browser has reconnected to its Blazor session.

### Steps To Reproduce

Link to a sample project to reproduce the bug: https://github.com/Mrlten/BlazorIJSStreamReferenceError

All functionality for the repro can be found in the `site.js`, `Index.razor` and `Index.razor.cs`.

Steps to reproduce:
1. Start the sample application.
2. Click on the 'Retrieve data using IJSStreamReference' button at least once (the `IJSStreamReference` must be used at least once in the current session to get the error).
3. Let the browser lose its connection to the server (the browser must connect to the original session on the server so don't shutdown the server process).
4. After the browser reconnected to the (original) session click on the 'Retrieve data using IJSStreamReference' button again.
5. Now the following things will happen:
   - The `RetrieveBlobAsync` server-side method is succesfully called.
   - The `retrieveBlob` javascript function is succesfully called.
   - The following javascript error is immediately thrown in the browser's console:
```
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52004)
    at kt._sendMessage (blazor.server.js:1:68639)
    at kt._sendWithProtocol (blazor.server.js:1:68680)
    at kt.send (blazor.server.js:1:68788)
    at blazor.server.js:1:129930
````
   - After 30 (?) seconds the following error is thrown at the server process:
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
    Unhandled exception in circuit 'gdrrToRh8Rwr9lh70UeQR8_kBwaW5nkxAtDwy4y1LYo'.
    System.TimeoutException: Did not receive any data in the allotted time.
    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
    at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
```
   - Followed by two `Microsoft.JSInterop.JSDisconnectedException`'s.

### Exceptions (if any)

In the browser:
```
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52004)
    at kt._sendMessage (blazor.server.js:1:68639)
    at kt._sendWithProtocol (blazor.server.js:1:68680)
    at kt.send (blazor.server.js:1:68788)
    at blazor.server.js:1:129930
```

At the server after a while:
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
    Unhandled exception in circuit 'gdrrToRh8Rwr9lh70UeQR8_kBwaW5nkxAtDwy4y1LYo'.
    System.TimeoutException: Did not receive any data in the allotted time.
    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
    at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
```

### .NET Version

6.0.201

### Anything else?

 - Not dependent on the VS version
 - dotnet info output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by TanayParikh** [comment]
Hi @Mrlten, thanks for contacting us. I really appreciate your detailed issue report and the repo you provided. This was extremely helpful and I was able to reproduce the issue.

At first glance, what strikes me as odd is after the reconnection, you're getting:

> Cannot send data if the connection is not in the 'Connected' State.

This would mean that the SignalR connection has still not recovered despite the "reconnection". The subsequent timeout exception ([would occur after 60 seconds by default](https://github.com/dotnet/aspnetcore/blob/2e132384878df1513b37b152ce36aa0e6eb8d757/src/Components/Server/src/Circuits/RemoteJSDataStream.cs#L204-L215)), is expected in the case where the client fails to send any JS stream data to the server. 

Given you're able to press the button and the server is able to request the stream by calling `retrieveBlob`, the connection appears to be "connected". However, when the [client attempts to send the stream chunks](https://github.com/dotnet/aspnetcore/blob/2e132384878df1513b37b152ce36aa0e6eb8d757/src/Components/Web.JS/src/Platform/Circuits/CircuitStreamingInterop.ts#L53), things break down and the `not in the Connected state` error is thrown. Will need to dig into why the connection breaks down here...
