### ISSUE TITLE
Blazor WebAssembly won't start using WebAssembly.DevServer v6.0.3

### ISSUE THREAD

**Issue by Sebbs128** [dotnet/aspnetcore#40611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the latest version (v6.0.3) of the Microsoft.AspNetCore.Components.WebAssembly.DevServer package, a Blazor WebAssembly app is unable to be started from within Visual Studio.

The error below appears
![image](https://user-images.githubusercontent.com/20781632/157437896-d1150add-1e3b-4865-9048-7dd514976f20.png)

The Debug Output window in VS has only
```
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[18148] dotnet.exe' has exited with code 2147516566 (0x80008096).
```

The app is able to start successfully using previous versions (tested with 6.0.2 and 6.0.1) of this package.

### Expected Behavior

Application should start with debugger attached.

### Steps To Reproduce

1. Create new Blazor WebAssembly application with default options
eg. 
![image](https://user-images.githubusercontent.com/20781632/157438570-85eb4aa9-bc7a-4caf-9ca5-f67c72cb18c2.png)

2. Update version of `Microsoft.AspNetCore.Components.WebAssembly.DevServer` package to 6.0.3.
3. Start debugging. Error should appear.

I haven't attempted repro using CLI.

### .NET Version

6.0.200

**Comment by pranavkm** [comment]
The DevServer typically requires a corresponding version of the ASP.NET Core shared runtime to be installed. Do you happen to have to have the 6.0.201 SDK / 6.0.3 ASP.NET Core runtime installed?

**Comment by Sebbs128** [comment]
Thanks @pranavkm.

> VS reports failure to run an app due to a missing runtimes in the Output window.

Not in any of VS's output windows. Some how I had missed the console window that had been launched, and the error message is in that.

Updated sdk and runtime and it works as expected.
