### ISSUE TITLE
Quarantine StreamPool_StreamIsInvalidState_DontReturnedToPool

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#40626]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.StreamPool_StreamIsInvalidState_DontReturnedToPool

## Error Message

```text
Assert.True() Failure
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.StreamPool_StreamIsInvalidState_DontReturnedToPool() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:line 578
--- End of stack trace from previous location ---
```
</details>

## Logs

[Http2ConnectionTests_StreamPool_StreamIsInvalidState_DontReturnedToPool.log](https://github.com/dotnet/aspnetcore/files/8218205/Http2ConnectionTests_StreamPool_StreamIsInvalidState_DontReturnedToPool.log)

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1651060&view=ms.vss-test-web.build-test-results-tab&runId=45546776&resultId=108023&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by amcasey** [comment]
This test hasn't failed in 30 days.

**Comment by amcasey** [comment]
Lines have moved, but it's probably [this assert](https://amcasey@github.com/amcasey/aspnetcore/blob/9040213b46c98a7ff57a2cbde1d5e6bc40871000/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs#L590).

**Comment by amcasey** [comment]
The test is waiting for the stream to complete, but it's not obvious that that implies the stream will also have been disposed.

**Comment by amcasey** [comment]
While it's not clear to me why we can assume that dispose will have been called before the tick handler returns, putting a delay ahead of the dispose call doesn't break the test.

**Comment by amcasey** [comment]
It certainly looks like the continuation of `Pipe.CancelPendingRead` is happening on the same thread and that's why the output producer is disposed by the time `TriggerTick` returns.  This seems like it might not happen with a [`ThreadPoolScheduler`](https://source.dot.net/#System.IO.Pipelines/System/IO/Pipelines/ThreadPoolScheduler.netcoreapp.cs,672ba1cd669541e9), but locally, I'm seeing an `InlineScheduler`.

**Comment by amcasey** [comment]
It [looks](https://github.com/dotnet/aspnetcore/blob/6b047bc57f9f9d3f015f348caad64f5d1bd3f0de/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L1841) like the write scheduler is unconditionally inline, whereas the read scheduler comes from the ServiceContext.

**Comment by amcasey** [comment]
I can't explain what changed, but the code (linked above) doesn't look racy now.
