### ISSUE TITLE
Invoking an static method of JS Class inside OnAfterRenderAsync in First Render throw undefined class error

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/aspnetcore#40621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to define a **js class** with **static** methods and then invoke one of its static methods through `JSInterop` in Blazor `WebAssembly` Razor Components inside `OnAfterRenderAsync`. It give an error that the method is not exist since the class is undefined. 
Example:
1- JS Class (I placed it inside Head of document )
```
class JSLibrary {
            static _DotNetObjectReference;
            static CreateInstance(instance) {
                JSLibrary._DotNetObjectReference = instance;
            }
            static GetScores() {
                var scores = _DotNetObjectReference.invokeMethod("GetScore", 0, 21);
                console.log(scores);
            }
            static GetCredits() {
                var credits = _DotNetObjectReference.invokeMethod("GetCredit");
                console.log(credits);
            }
            static GetAverage() {
                _DotNetObjectReference.invokeMethod("GetAverage");
            }
        }
```
2- Invocation of static method inside `OnAfterRenderAsync` :
```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _jsmodule = DotNetObjectReference.Create(jSModule);// create the reference and pass to Static methods in js
            await JS.InvokeVoidAsync("JSLibrary.CreateInstance",_jsmodule);
        }
        await base.OnAfterRenderAsync(firstRender);
    }
```
Error:
```
Microsoft.JSInterop.JSException: Could not find 'JSLibrary.CreateInstance' ('JSLibrary' was undefined).
      Error: Could not find 'JSLibrary.CreateInstance' ('JSLibrary' was undefined).
```

### Expected Behavior

Expected to work as methods defined inside modules or global namespace in Java Script.

### Steps To Reproduce

Create a Blazor web assembly using template and then add the `class` definition to head of `index.html `and put `OnAfterRenderAsync` at one of the components and test it (go to url regarded to component and check the developer logs in browser to see error)

### .NET Version

6.0.201

### Anything else?

![image](https://user-images.githubusercontent.com/48277995/157513541-df38123c-c717-4dae-9085-3b5b2f951266.png)

**Comment by guardrex** [comment]
@abdollahkahne ... See my answer on the docs issue that you opened for this. Your JS is in the wrong spot. This issue can be closed.

**Comment by abdollahkahne** [comment]
> > I placed it inside Head of document
> 
> @abdollahkahne ... See my answer on the docs issue that you opened for this. Your JS is in the wrong spot. This issue can be closed if that's the problem.

Thanks. I checked it too. It give me error yet. I think there is something related to JS Whoisting of Class which do not do as it do for other variables. By the way I test both approaches and I get the error in both.

**Comment by javiercn** [comment]
@abdollahkahne can you create a minimal repro project as a public github repository so that we can make progress in determining if there's something wrong here?

**Comment by abdollahkahne** [comment]
I added a minmal project here:
[Link to GitHub](https://github.com/abdollahkahne/JSStaticMethods)
I do not upload bin and obj folder due to their size. Is they are necessary?!

**Comment by javiercn** [comment]
@abdollahkahne you need to add the class to the window object, otherwise it's not globally defined and Blazor can't find it.

**Comment by javiercn** [comment]
`window.JSLibrary = JSLibrary`
