### ISSUE TITLE
Visual Studio React template project doesn't work with hook based components - Error: Invalid hook call

### ISSUE THREAD

**Issue by xuhaohems** [dotnet/aspnetcore#40631]
I am using the React web application template in Visual Studio 2022 to create a web project. Right after project is created, I installed a component that’s implemented with hooks, e.g. React-Bootstrap by package management command -
npm install react-bootstrap bootstrap@5.1.3

Then I import it to home.js -

import Button from ‘react-bootstrap/Button’;
and add an element -

<div>
<Button variant=“primary”>Button #1</Button>
<Button variant=“secondary” className=“mx-2”>Button #2</Button>
<Button variant=“success”>Button #3</Button>
</div>
Run the project and I get the following error -

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

I haven’t added any other code and I think there is something wrong with the code in the template but I can’t figure out the issue.

**Comment by Pilchie** [comment]
Hi - this doesn't seem to be an ASP.NET Core question, but rather something about react.  Unfortunately, that's outside the scope of our team.

Can you say exactly which template title you created?

**Comment by xuhaohems** [comment]
This is about the ASP.Net Core with React.js template (C#)
The template generated can't work with any hook based component. You can follow the step to repro the issue.

**Comment by Pilchie** [comment]
Thanks for confirming. Unfortunately, our team are not react developers, and can't really help debug issues with the react part of the template.  We mostly just take the output of a new react project and add it to the template.

**Comment by javiercn** [comment]
Our templates are a starting point and you can choose to modify them to use new features as needed. In this case, hooks seem to be incompatible with the default style of the templates (which is class based components). You can feel free to change the code to use function components and leverage hooks, but that is not something we plan to do.
