### ISSUE TITLE
Build template packages in servicing

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#40637]
Currently building release/6.0 doesn't produce the template packages.

Microsoft.DotNet.Web.ItemTemplates
Microsoft.DotNet.Web.ProjectTemplates
Microsoft.DotNet.Web.Spa.ProjectTemplates

This doesn't work well for .NET source-build which needs to product the entire product for every build (e.g. previews, rtm, servicing, etc).

Would it be amenable to always produce the template packages during servicing builds?  An alternative less desirable option would be to build them only in source-build.

Currently source-build treats these packages as text-only packages that are checked in/reverse engineered. This solution is not ideal as it requires manual updates, is a maintenance burden, and in general is problematic.

This issue is similar in nature to https://github.com/dotnet/aspnetcore/issues/39471 and https://github.com/dotnet/templating/issues/4337.

**Comment by javiercn** [comment]
@MichaelSimons thanks for bringing this up to our attention.

@dotnet/aspnet-build do you know what might be going on here?

**Comment by wtgodbe** [comment]
The template packages do get built in servicing builds, see the `PackageArtifacts` of a recent 6.0 build here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1654283&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by wtgodbe** [comment]
Ah, sorry for the confusion - we exclude everything except the targeting pack & SharedFx from source build. I can add the templates to that exclusion list as well. Do you need this further back than 6.0?
