### ISSUE TITLE
Authorize attribute does not work

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [dotnet/aspnetcore#40632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a "Buy" method in "CartController" class decorated with "Authorize" attribute, yet the user can access it even if they are not
logged in.

        ```
        public IActionResult Buy(int id)
        {
            ProductModel productModel = new ProductModel();
            List<Items> cart = SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart");

            if (cart == null)
            {
                cart = new List<Items>() { productModel.find(id)};
                cart.First().Quantity = 1;
            }
            else
            {
                int index = isExist(id);

                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(productModel.find(id));
                    cart.Last().Quantity = 1;
                }
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }
```

**Comment by BrennanConroy** [comment]
Share a minimal repro app as a project on GitHub.

**Comment by mahmoudahmedarafa** [comment]
When I try to add the project to the repository it doesn't prompt me to type password for my github username.

![Capture](https://user-images.githubusercontent.com/22199398/158034006-17dd6b06-f11f-43e6-8a1d-0626983bdf5d.PNG)

**Comment by BrennanConroy** [comment]
`git remote add origin <url>`
Use the url of your repo on github, not the file path.

**Comment by mahmoudahmedarafa** [comment]
I corrected it but again it says "Logon failed". I am sure I entered correct username and password.
It doesn't even prompt me to type password in cmd.

![Capture](https://user-images.githubusercontent.com/22199398/158081332-f6ad7c26-8a26-4d0b-84fb-456b7c35bd51.PNG)

**Comment by adityamandaleeka** [comment]
Take a look at this: https://stackoverflow.com/questions/55768926/logon-failed-use-ctrlc-to-cancel-basic-credential-prompt-to-git-in-azure-devop

**Comment by mahmoudahmedarafa** [comment]
https://github.com/mahmoudahmedarafa/ShoppingCart/blob/master/Controllers/CartController.cs

Please see "Buy" function decorated with "Authorize" attribute. Authorization doesn't work when user buys an item.

**Comment by BrennanConroy** [comment]
You don't have UseAuthorization in your app so Auth wont run.

**Comment by mahmoudahmedarafa** [comment]
![Capture](https://user-images.githubusercontent.com/22199398/158812134-62baf4f5-b45b-4bcd-a368-4dbac2ed959f.PNG)

Error CS1061 'IApplicationBuilder' does not contain a definition for 'UseAuthorization'.
I am using .NET Core 2.2.

**Comment by BrennanConroy** [comment]
.NET Core 2.2 has been out of support for years https://docs.microsoft.com/lifecycle/products/microsoft-net-and-net-core
Please switch to a supported version.

If you use 2.1 you need to install the https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization.Policy/2.1.2 package, if you use 3.1+ you don't need to install a nuget package.
