### ISSUE TITLE
Add a code analyzer to ensure that razor pages that define Dispose actually implement IDisposable

### ISSUE THREAD

**Issue by Webreaper** [dotnet/aspnetcore#40638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's very easy when writing a Razor page to forget to add the `@implements IDisposable` line at the top when implementing the Dispose pattern. This can mean that developers can unwittingly have dangling handlers which will cause memory leaks because the `Dispose` method they carefully wrote will never actually get called. 

### Describe the solution you'd like

It would be great to have a code analyzer in VS that will put a wiggly red line under Dispose methods that are declared in a .razor file that doesn't explicitly have the statement `@implements IDisposable`.

**Comment by javiercn** [comment]
@Webreaper thanks for contacting us.

The compiler should take care of that by producing a compile time error if you don't have a Dispose method within your implementation.

**Comment by javiercn** [comment]
@Webreaper that's not something we plan to do. 

I don't think the C# compiler does it either. There is no reason for us to assume that Dispose() means you want to implement IDisposable, specially since you might already be implementing IAsyncDisposable.

**Comment by Webreaper** [comment]
Good point about IAsyncDisposable. But it seems pretty likely to me that Dispose() means that the razor page was attempting to implement IAsyncDisposable or IDisposable, so this would be a useful hint for either, no? If somebody writes a method and happens to call it Dispose but it's nothing to do with IDisposable/IAsyncDisposable, then the user can just rename their method? 

But if you don't think this a useful code analysis, then fair enough. I just thought I'd flag it as I had two instances of this in my code across about 15 razor pages that implement Dispose(), and had the IDE warned me, I wouldn't have had these two memory leaks to fix. :)
