### ISSUE TITLE
IResult support in MVC

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#40639]
## Background and Motivation

Today, with the new `Microsoft.AspNetCore.Http.Results` class is very easy to get confused and implement a Controller Action similar with that, or any other variation of the methods exposed by this class:

``` csharp
[HttpGet]
public IResult Get()
{
    return Results.Ok();
}
```

Also, is very easy to use an `Microsoft.AspNetCore.Http.IResult` custom implementation as a return of a controller action, like this:

``` csharp
public class MyCustomResult : IResult
{
    public Task ExecuteAsync(HttpContext httpContext) => Task.CompletedTask;
}
```

``` csharp
[HttpGet]
public IResult Get()
{
    return new MyCustomResult();
}
```

Both examples will not throw exception but will serialize the class. For the first example the action will return the following payload:

``` json
{
  "value": null,
  "statusCode": 200,
  "contentType": null
}
```

## Proposed API

The proposal is the creation of a new `public` action result that will store an instance of the `IResult` and call the `IResult.ExecuteAsync` method instead instead of using the `IActionResultExecutor` to write the Http Response. With this, we will miss all the content-negotiation available in MVC through the `ObjectResultExecutor` but we will have the correct serialization and all the other components, like `Middleware`, `Filters` etc., will work.

``` diff
+namespace Microsoft.AspNetCore.Mvc;

+public class HttpResultsActionResult : ActionResult
+{
+    public IResult Result { get; }
+    public MinimalActionResult(IResult result){}
+    public override Task ExecuteResultAsync(ActionContext context){}
+}
```

The controller's action can return a `Microsoft.AspNetCore.Http.IResult` that will be converted to the new `HttpResultsActionResult` when the `ActionResultTypeMapper.Convert` is invoked. Eg.:

``` csharp
[HttpGet]
public IResult Get() => Results.Ok(new Todo() { Id = 1, Title = "Sample todo"});
```
The sample action will produce the following payload:

``` json
{
  "id": 1,
  "title":  "Sample todo"
}
```

### Controller's action using the `HttpResultsActionResult`

``` csharp
    [HttpGet()]
    public ActionResult Get(int id)
    {
        var result = Results.Ok(new Contact() { ContactId = id });
        return new HttpResultsActionResult(result);
    }
```

### Result's filter using the `HttpResultsActionResult`

``` csharp
public class HttpResultResultFilter : IResultFilter
{
    public void OnResultExecuted(ResultExecutedContext context)
    {
        if (context is { Result: HttpResultsActionResult { Result: IResult httpResult } })
        {
            // Do something after the result executes.
        }        
    }
}
```

If the proposal #40656 is approved, the results instance could be further inspected, eg.:

``` csharp
public class HttpResultResultFilter : IResultFilter
{
    public void OnResultExecuted(ResultExecutedContext context)
    {
        if (context is
            {
                Result: HttpResultsActionResult
                { Result: IStatusCodeHttpResult { StatusCode: StatusCodes.Status200OK } }
            })
        {
            // Do something after the result executes.
        }      
    }
}
```

## Alternative Designs

The new type could have a `private` constructor, that could avoid undesired instantiation

``` diff
+namespace Microsoft.AspNetCore.Mvc;

+public class HttpResultsActionResult : ActionResult
+{
+    public IResult Result { get; }
+    public override Task ExecuteResultAsync(ActionContext context){}
+}
```

Or the new action result could be `internal` instead, that will make this proposal irrelevant, but the feature will be available, however, will not be possible to create Result Filters as shown in the example.

**Comment by halter73** [comment]
## API Review Notes
- Should the new type and constructor be public?
  - Yes for the type, because it could be useful for filters
  - Yes for the constructor. Even though no one should really call it, this is expected for `ActionResult` implementations.
- What about renaming the type not to include "Result" twice?

``` diff
+namespace Microsoft.AspNetCore.Mvc;

+public class HttpActionResult : ActionResult
+{
+    public IResult Result { get; }
+    public HttpActionResult(IResult result){}
+    public override Task ExecuteResultAsync(ActionContext context){}
+}
```

- The above might be too similar to https://docs.microsoft.com/en-us/previous-versions/aspnet/dn202095%28v%3dvs.118%29.
- We will continue to discuss naming of the public type in the next API review, but we can take the PR with the implicit conversion and the internal type for now.

**Comment by brunolins16** [comment]
Here are few name ideas for the next review meeting:

- `HttpActionResult`
- `HttpApiResult`
- `HttpResult`
- `HttpResultActionResult`
- `MinimalHttpResult`
- `MinimalApiResult`
- `MinimalActionResult`
- `SimpleHttpResult`
- `SimpleApiResult`
- `SimpleActionResult`
- `ApiResult`
- `ApiActionResult`

**Comment by halter73** [comment]
API Review:

After considering the many additional proposed names, we like the originally proposed `HttpActionResult` even if it's similar to `IHttpActionResult` the most.

That said, we don't expect people to new these up since there's already an implicit conversion effectively when returned from Actions. We will wait for developer feedback to see if the use case of inspecting `IResult`s in action filters is important enough to add new public API.
