### ISSUE TITLE
Blazor 6 : "Microsoft.TypeScript.MSBuild" and a collocated JavaScript file with a .razor file cause a build error on the Ubuntu

### ISSUE THREAD

**Issue by jsakamoto** [dotnet/aspnetcore#40640]
### Describe the bug

On the Ubuntu Linux 20.04 LTS, for a Blazor WebAssembly project (.NET 6) with the following conditions, 2nd time or later of execution, `dotnet build` command causes the build error "Two assets found targeting the same path with incompatible asset kinds".

- The project references "Microsoft.TypeScript.MSBuild" NuGet package.
- The project contains .razor.js files that are collocated with .razor files.
- The project also contains .razor.ts files, and they are transpiled to the .razor.js files above.

#### Notice:

- I encountered this problem with the .NET SDK 6.0.x on Ubuntu Linux 20.04 LTS on WSL2 on my Windows 11 Pro 21H2 x64, and GitHub Actions of `ubuntu-latest`.
- The build error never occurred on Windows OS. (I don't know the case on a macOS because I could not try it on macOS.)
- The 1st execution of the `dotnet build` was completed successfully whether runs on Ubuntu or Windows.
- It seems the error happens only when the transpiled .razor.js files already exist before the build has been started.
- If I do not use TypeScript for collocated JavaScript with Razor component, the build error never occurred even though I continue using TypeScript for located JavaScript under the "wwwroot" folder.
- At that time, I used "Microsoft.TypeScript.MSBuild" NuGet package version 4.6.2, but in my case, the build error seems to happen even another version of "Microsoft.TypeScript.MSBuild" NuGet package such as version 3.x.

#### Requirements

- Use the minimal project below that can reproduce this problem.
  - [📦BlazorCollocateJsWithRazor-net-sdk-6.0.201.zip](https://github.com/dotnet/sdk/files/8215023/BlazorCollocateJsWithRazor-net-sdk-6.0.201.zip)
- Prepare a Ubuntu Linux 20.04 LTS and install the .NET SDK 6.0.201 in it. 

#### Steps to reproduce

1. Open a terminal on the Ubuntu Linux 20.04 LTS.
2. Change the current directory to where you extracted the "BlazorCollocateJsWithRazor-net-sdk-6.0.201.zip" file.
3. Execute `dotnet build command` and confirm it will be a success.
4. Execute `dotnet build command` one more time, then you will see the build error.

### Exceptions (if any)

The build error message is below:

```
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.JSModules.targets(95,5): error : Two assets found targeting the same path with incompatible asset kinds:  [/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/BlazorCollocateJsWithRazor.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.JSModules.targets(95,5): error : '/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/App.razor.js' with kind 'All' [/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/BlazorCollocateJsWithRazor.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.JSModules.targets(95,5): error : '/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/App.razor.js' with kind 'All' [/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/BlazorCollocateJsWithRazor.csproj]
/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.JSModules.targets(95,5): error : for path 'App.razor.js' [/mnt/c/Projects/Blazor/Trials/BlazorCollocateJsWithRazor/BlazorCollocateJsWithRazor.csproj]
```

#### `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.406 [/usr/share/dotnet/sdk]
  6.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by jsakamoto** [comment]
@mkArtakMSFT Thank you for replying.

However, sorry to bother you, but... I was too disappointed with that reply, and I've felt really sad due to the careless attitude of that reply. 😢

I understand well that the product development team is very busy, and therefore, it is needed to prioritize so many issues.
So I would not mind if this issue is made a low priority.

However, I've felt that you have read my post with a careless attitude.

- The sample project that I provided includes copying assets to the `wwwroot` folder, but it doesn't matter for this issue. The purpose of that is just for proof that copying assets to the `wwwroot` folder don't matter for this issue. In fact, after removing the `App.razor.ts`, building on both Linux and Windows will **be a success even though the project still includes copying assets to the `wwwroot` folder**.
- This issue looks depends on the OS platform deeply. In my investigation, this problem happens **only on Linux OS** never happens on Windows OS.
- This issue also looks to **depend on collocated JavaScript files with Razor Component files since .NET 6**, too. (as I said previously, JavaScript files that are copying to the `wwwroot` folder don't cause the build error in this scenario.)
-  I understand that the reason for this problem might be the "Microsoft.TypeScript.MSBuild" package side, not the .NET SDK side. 
- In my opinion, at this time, the pieces of evidence above tell us that **the blog post you introduced may not be involved with this issue**, I think.

I apologize if I don't understand that you might not be able to spend enough time understanding my post because you are so busy. 🙇
However, I appreciate it if you or your team try to investigate well this issue again.

Anyway, I hope this post would be helpful to save the developers working on Linux OS and reduce the people who feel "I don't like .NET platform due to often happening such a build error". ❤️

**Comment by javiercn** [comment]
@jsakamoto we apologize if you thought we didn't pay close attention to your issue. 

We normally comb through dozens of issues on a weekly basis and this is an issue that we've seen in the past, so our first action was to point out the common answer we give people in these situations.

I took a second look at your issue and it seems to be caused by the TypeScript MSBuild tasks adding additional content items on Linux for some reason as opposed to windows where it does not:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/6995051/158167063-7dc344a3-67ff-4843-9f5e-1b726783a985.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/6995051/158167269-43d53519-9356-4a2d-b478-c27d57fb80f6.png">

The issue seems to come from the `GetTypeScriptOutputForPublishing` producing different results on Linux and on Windows, so on Linux the content is added twice

**Comment by javiercn** [comment]
Filed an issue on TypeScript to track this problem [here](https://github.com/microsoft/TypeScript/issues/48271)

**Comment by jsakamoto** [comment]
@javiercn Thank you for your sincere reply and for investigating this issue. 

> We normally comb through dozens of issues on a weekly basis 

I can imagine it must be too much tough work.
So I always appreciate the product development team. ❤️

Sorry to bother you, but getting the reply "We are still triaging", "Wait for more time" or "We don't have enough time" might be better for me than getting a reply "It seems the same as a common issue" without well investigating.

> caused by the TypeScript MSBuild tasks adding additional content items on Linux 

Yes, I feel so too.

Just curious, I feel strange that the `wwwroot/Helper.js` does not cause the build error even though it is also translated from the `wwwroot/Helper.ts` by the TypeScript MSBuild task like the `App.razor.js`.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/95908/158375076-ed662cad-47a0-4a3f-b827-e2ececf6fee9.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/95908/158375095-c7daf8c7-cf99-4c64-a8b9-4a50a9b24d9f.png">

Anyway, I do not mind if there is no reply to this comment.
I just hope somebody will resolve this problem in the future.

> Filed an issue on TypeScript to track this problem here

Many thanks for your reaction.
Again, thank you for your effort to resolve this scenario.
