### ISSUE TITLE
Blazor - Error Boundary not triggered inside of EditForm Component

### ISSUE THREAD

**Issue by casper7526** [dotnet/aspnetcore#40649]
If you have the following:
```
<ErrorBoundary>
<ChildContent>
@Body
</ChildContent>
</ErrorBounday>
```

You expect that any exceptions within your pages will flow upwards and hit the errorbounday handling code. For 99% of things I have tried this holds true.

HOWEVER

If you trigger an exception while inside of Editforms methods (onSubmit,OnValidSubmit) you will bypass the errorboundary handler and be shown the default circuit error at the bottom of the screen.

```
<EditForm OnValidSubmit="OnSubmit"> .....

public void OnSubmit(){
throw new Exception("Error");
}
```

This seems to bypass the intended function of ErrorBoundary and while I am explaining it in a global manner it would still fail if it was done within a page itself.

**Comment by gbthakkar** [comment]
Hi,
I too ran into this today. ErrorBoundry works in normal case work but not when EditForm trigger the error like given by @casper7526 . But then Blazor being the SPA, I have situation where has the pages are having EditForm on it. (I believe, will be the case for most developer). 
So by the time you consider this as valid case, kindly provide some alternative to cover this situation.
... try-catch is one thing which is obvious on our side. But looking for something like ErrorBoundry.
Thanks

**Comment by casper7526** [comment]
I'm closing this issue, I was able to solve it on my own.

I was using a public async void as a method and Blazor is unable to await that (which is needed for boundaries).

Changing the method to be public async Task allows boundaries to work inside an EditForm
