### ISSUE TITLE
Clarification on AuthenticateResult.NoResult vs AuthenticateResult.Failure. 2nd iteration.

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#40645]
I am confused by the explanation given [here](https://github.com/dotnet/aspnetcore/issues/38685)

I also asked the question at [StackOverflow](https://stackoverflow.com/q/71423716/921054)

From @blowdart 's response it follows that there can be a set of authentication handlers. However, as I see from the api and docs, each authentication handler is mapped to specific authentication scheme which gets resolved first. If handler returns `NoResult` there won't be any other handler to attempt authentication, because other authentication schemes won't be probed, right?

**Comment by blowdart** [comment]
You can have multiple handlers attempting to process the same HTTP Authentication scheme, that's how some folks use JWT. 

I don't believe we don't probe based on the header scheme, we go through everything in the auth handler collection. The "scheme" you might be seeing (it's hard to tell because you don't show us where in the api or does you see a mapping) is a unique key in the collection and not linked to the scheme in the header.

**Comment by voroninp** [comment]
Yes, I mean the key `authenticationScheme`, 

```
public virtual AuthenticationBuilder AddScheme<TOptions, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] THandler>(string authenticationScheme, Action<TOptions>? configureOptions) where TOptions : AuthenticationSchemeOptions, new() where THandler : AuthenticationHandler<TOptions>
```

I created a default application:

Program.cs:

```CSharp
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;
using System.Security.Claims;
using System.Text.Encodings.Web;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddAuthentication()
    .AddScheme<AuthenticationSchemeOptions, AuthHandler>("1", null)
    .AddScheme<AuthenticationSchemeOptions, AuthHandler>("2", null)
    .AddScheme<AuthenticationSchemeOptions, AuthHandler>("3", null);

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();


sealed class AuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public AuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options, 
        ILoggerFactory logger, 
        UrlEncoder encoder, 
        ISystemClock clock) : base(options, logger, encoder, clock)
    {
    }

    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        if (Scheme.Name == "3")
        {
            var identity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.NameIdentifier, "user")
            },
            "3");
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, "3");
            return AuthenticateResult.Success(ticket);
        }

        return AuthenticateResult.Fail("Not Lucky");
    }
}
```

WeatherForecastController.cs:

```CSharp
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApiWithAuth.Controllers
{
    [ApiController]
    [Route("[controller]")]
    [Authorize(AuthenticationSchemes = "1,2,3")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}
```

So all three handlers are called because of `[Authorize(AuthenticationSchemes = "1,2,3")]`, but auth succeeds anyway for the scheme `3`. But how can I model the process you described: If any of the handlers yield `Fail`, authentication fails?

**Comment by blowdart** [comment]
I don't believe we guarantee order. @HaoK am I wrong here in expecting fail to work like context.Fail would in policies?

**Comment by HaoK** [comment]
So authentication is a bit different than AuthZ because its done on a per scheme basis, while authorization is all about a full list of requirements.

So if you ask for Authentication 1,2,3 that generates 3 individual calls to Authenticate for 1,2,3 they don't really have a concept of hard Fail(other than if you have an uncaught exception), but its perfectly normal to get results or no results from schemes (i.e. no cookie, or no bearer), and then its usually our AuthZ logic that is making sense and combining those results into the ClaimsPrincipal that we use as the User for authorization.

There's no way to have multiple handlers for a specific authentication scheme, which is why we added Policy Schemes to make easier to delegate/forward/compose schemes.

**Comment by voroninp** [comment]
@HaoK , do I get it right that for AuthN handlers there's no difference between `Fail` and `NoResult` ?

**Comment by voroninp** [comment]
Also I am trying to understand how to support authentication with bearer tokens coming from different Identity providers (Okta, Auth0) when federation is not enabled.  Do I need to register two authN schemes and then specify them in `[Authorize]`?

**Comment by HaoK** [comment]
> @HaoK , do I get it right that for AuthN handlers there's no difference between Fail and NoResult ?

I'm not sure what you mean by no difference, at the authentication service level, AuthenticateAsync always returns a result  NoResult is you don't have a cookie or bearer token, Fail will result in an error/exception that the caller can look at.  But if you are enough in the stack, i.e. only looking at behavior from `[Authorize]` both will look like no principal, i.e. it wasn't a successful authentication

**Comment by voroninp** [comment]
@HaoK, ok, but in implementation of `AuthenticationHandler` does it cause different behavior in the auth process depending on what was returned: `Fail` or `NoResult`?

**Comment by HaoK** [comment]
Again it depends on the caller, lots of code only checks if the authentication was a Success which doesn't distinguish between NoResult or Failure, but clearly the handler returns different results.

**Comment by voroninp** [comment]
> Again it depends on the caller

Are there many places in framework where AuthN handler is called?
