### ISSUE TITLE
Localized metadata for template is not localized templatestrings.{lang}.json 

### ISSUE THREAD

**Issue by phenning** [dotnet/aspnetcore#40666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The templatestrings.{lang}.json files need to be localized.

Currently the strings in these files all contain the english seed data.

### Expected Behavior

The templatestrings.{lang}.json files should contain translated strings.

This resutls in the template name and description being localized in both dotnet new --list and also in the new project dialog in VB.

### Steps To Reproduce

Either:
run dotnet new --list on a non ENU machine. 

or 
1. Set VS to non ENU locale.
2. Launch new Project dialog

### .NET Version

7.0.100-preview.2.22156.6

### Anything else?

Template version: 7.0.100-preview.2.22156.6

**Comment by bekir-ozturk** [comment]
I searched the repo, but arcade/onelocbuild doesn't seem to be configured: https://dev.azure.com/dnceng/internal/_search?action=contents&text=onelocbuild.yml&type=code&lp=buildrelease-Project&filters=ProjectFilters%7Binternal%7DRepositoryFilters%7Bdotnet-aspnetcore%7D&pageSize=25&result=DefaultCollection/internal/dotnet-aspnetcore/GBmain//eng/common/templates/job/onelocbuild.yml

There are also no `xlf` files created for the `.resx` files. I was expecting something like we have in the templating repo: https://github.com/dotnet/templating/tree/main/src/Microsoft.TemplateEngine.Cli/xlf 

I'm wondering if localizations were never setup in this repo?
