### ISSUE TITLE
Introduce Microsoft.AspNetCore.OpenApi package

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#40676]
Consider introducing a new package *Microsoft.AspNetCore.OpenApi* that provides integration features for ASP.NET Core HTTP APIs and OpenAPI. This package takes a dependency on [*Microsoft.OpenApi* ](https://github.com/microsoft/OpenAPI.NET) and contains the logic that maps primitive ASP.NET Core endpoint details to representations in endpoint metadata using the object model provided by *Microsoft.OpenApi*, along with projecting these details into the legacy `ApiExplorer` API from MVC. Furthermore, it provides helper methods for easily adding user-specified OpenAPI relevant details directly to endpoint metadata.

This would essentially be a strategy shift so that instead of continuing to add more metadata types to the framework to allow more details about endpoint APIs to be declared and published in MVC's `ApiExplorer` (e.g. #40084), we embrace the existing OpenAPI object model in *Microsoft.OpenApi* and allow all operation details to be specified in an endpoint's metadata and projected into `ApiExplorer` so that existing libraries like *Swashbuckle* continue to work.

The package would do the following:
- Depend on *Microsoft.OpenApi*
- Contain the logic that maps the `MethodInfo` for a route handler delegate in the endpoint metadata, to the requisite `Microsoft.OpenApi.Models.OpenApiOperation`
- Provide extension methods to easily allow mutating a route handler delegate's OpenApi metadata, e.g.
    ``` c#
    app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync())
        .WithOpenApiDetails(operation =>
        {
            operation.OperationId = "GetAllTodos";
            operation.Description = "This API returns all the Todos.";
        });
    ```
- Preserves the `Microsoft.OpenApi.Models.OpenApiOperation` in the endpoint metadata
  - This requires a new extensibility point be added such that the package can mutate the metadata for endpoints built by the route endpoint builder
- Contain the `IApiDescriptionProvider` that projects a route handler's details from its OpenAPI endpoint metadata into `ApiExplorer`
- Be referenced in the Web API project template
- **Would not** reference *Swashbuckle.AspNetCore*, rather a project would still need to reference the SwaggerUI/OpenAPI library it wishes to use and call the requisite configuration methods for it to be configured

We need to consider of course how we do this without breaking (too much) stuff. In .NET 6, Minimal API endpoints are added to the `ApiExplorer` if MVC is configured, or the `AddEndpointsApiExplorer()` services extension method is called.

**Comment by davidfowl** [comment]
cc @darrelmiller @bradygaster

**Comment by bradygaster** [comment]
i really like this idea.

**Comment by bradygaster** [comment]
Also DM's library can translate betwixt versions of OpenAPI (and output format - YAML/JSON). We could use that.

**Comment by darrelmiller** [comment]
Sign us up.

**Comment by dosper7** [comment]
I'm sold 🤑 really like this one.

**Comment by jchannon** [comment]
![giphy](https://user-images.githubusercontent.com/105126/162234876-59c0e3f0-b069-4e06-a4ab-542f46c1839d.gif)

**Comment by captainsafia** [comment]
## Proposed API

```csharp
namespace Microsoft.AspNetCore.OpenApi;

public static class OpenApiRouteHandlerBuilderExtensions
{
  public static RouteHandlerBuilder WithApiDescription(
    this RouteHandlerBuilder builder,
    Action<OpenApiPathItem>? configureDescription = null) { }
}
```

```csharp
public static class OpenApiServicesExtensions
{
  public static IServiceCollection AddOpenApiGenerator(this IServiceCollection services) {}
}
```

```csharp
public class OpenApiGenerator
{
  public OpenApiGenerator(
        IHostEnvironment? environment,
        IServiceProviderIsService? serviceProviderIsService) { }
}
```

## Usage Examples


```csharp
var builder = WebApplication.CreateBuilder();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApiGenerator();

var app = builder.Build();

app.MapGet("/todo/{id}", (int id) => {})
.WithApiDescription(desc => {
  desc.Operations[OperationType.Get].Summary = "Get a Todo by ID";
  desc.Operations[OperationType.Get].Parameters[0].Summary = "The ID associated with the Todo";
  desc.Operations[OperationType.Get].Parameters[0].Required = true;
});
```

**Comment by DamianEdwards** [comment]
Some alternatives for `AddOpenApiGenerator`:
- `AddOpenApiEndpoints`
- `AddOpenApiEndpointMetadata`
- `AddOpenApi`

**Comment by captainsafia** [comment]
Note: `WithApiDescription` should change naming and input parameter.

```csharp
WithOpenApi();
WithOpenApi(Func<OpenApiOperation, OpenApiOperation> produceOperation);
```


Remove:

```
public static IServiceCollection AddOpenApiGenerator(this IServiceCollection services) {}
```

Make this type internal:

```csharp
internal class OpenApiGenerator
{
  internal OpenApiGenerator(
        IHostEnvironment? environment,
        IServiceProviderIsService? serviceProviderIsService) { }
}
```

**Comment by halter73** [comment]
API Review Notes:

- New sample usage (pending copy constructor https://github.com/microsoft/OpenAPI.NET/issues/832).

```csharp
using Microsoft.AspNetCore.OpenApi;

// ...

app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync())
    .WithOpenApi(operation => new(operation)
    {
        OperationId = "GetAllTodos",
        Description = "This API returns all the Todos.",
    })
```
- Are we worried about the extensibility of `OpenApiOperation` since we do not own the type? No. We can lean on the `OpenApiOperation.Extensions` dictionary if we really must.

Final approved API:


```diff
+ namespace Microsoft.AspNetCore.OpenApi;
+
+ public static class OpenApiRouteHandlerBuilderExtensions
+ {
+   public static RouteHandlerBuilder WithOpenApi(this RouteHandlerBuilder builder)
+   public static RouteHandlerBuilder WithOpenApi(this RouteHandlerBuilder builder, Func<OpenApiOperation, OpenApiOperation> configureOperation)
+ }

namespace Microsoft.AspNetCore.Builder;

public abstract class EndpointBuilder
{
+  public IServiceProvider? ServiceProvider { get; set; }
}
```
