### ISSUE TITLE
.net 7 is on ubuntu 21.10 and libmsquic on 20.04 http3

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#40679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using .net 7 preview 1, unfortunately it requires ubuntu 21.10. I want to test http3 on ubuntu. Documentation tells me to install libmsquic. Unfortunately, the package in version 21.10 does not have this library. I searched the internet and can't find anything. Do you have any ideas what to do?
https://docs.microsoft.com/pl-pl/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-6.0
https://docs.microsoft.com/pl-PL/windows-server/administration/linux-package-repository-for-microsoft-software

It's nice if this library was already built into .net
So that when compiling the project, it already made a dependency without additional installations.

### .NET Version

.net core 7 preview 1

**Comment by adityamandaleeka** [comment]
> I am using .net 7 preview 1, unfortunately it requires ubuntu 21.10. 

Where do you see that?
