### ISSUE TITLE
[Blazor] Fetch logic should check if the asset is present in the list of included assets before deciding to serve index.html

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#40678]
https://github.com/dotnet/aspnetcore/blob/2b4a186c29667003d06bef8d629f5d3266b5804a/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/wwwroot/service-worker.published.js#L41-L59

This causes issues when users try to access a resource on the page directly through the address bar.

The proposal involves updating the service worker to make sure that if a request is for an offline resource, we never serve index.html

Something like 
```
const shouldServeIndexHtml = event.request.mode === 'navigate' && !self.assetManifest.assets.some(asset => asset.url === event.request.url)
```

**Comment by javiercn** [comment]
@allprogrammers go for it!

**Comment by allprogrammers** [comment]
Thank you. 

I can just copy paste your suggestion but I want to be able to recreate the issue first and see what really the problem is. Can you give some instructions to do that?

**Comment by MatthewKing** [comment]
Is there a recommended solution for this issue yet?

**Comment by javiercn** [comment]
@MatthewKing it's sitting in our up for grabs category, meaning it's not a current priority, since people affected by it can address it in their own code (the service-worker code is in the template).

We welcome a PR if you are willing to contribute it.

**Comment by MatthewKing** [comment]
Thanks @javiercn - It's a bit out of my area of familiarity which is why I was hoping there was an existing/recommended solution. If I resolve it to my satisfaction, I will send a PR. Cheers

**Comment by javiercn** [comment]
@MatthewKing it's been a while, but I believe the suggestion above should work. If that works for you, then we'll happily take the contribution. If you come up with an alternative implementation, we'll have to discuss it a bit further.

**Comment by javiercn** [comment]
@MatthewKing from what I can tell, the origin is a bit problematic, but there is not much we can do about it.

I think the origin won't be enough, as it won't account for the path component (for example if you are hosting your app in `https://www.example.com/dir`. I suspect origin will be just `https://www.example.com/`)

So I think we should do a couple of things.
* Use URL to build the actual URL as [here](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)
* Avoid computing the list of URLs on each request.
  * Just compute the list of URLs in the global scope and use that inside the handler.

**Comment by MatthewKing** [comment]
My current solution is as follows:

Add to the global scope:
```js
// Replace with your base path if you are hosting on a subfolder. Ensure there is a trailing '/'.
const base = "/";
const baseUrl = new URL(base, self.origin);
const manifestUrlList = self.assetsManifest.assets.map(asset => new URL(asset.url, baseUrl).href);
```

Add to the onFetch method:
```js
// For all navigation requests, try to serve index.html from cache,
// unless that request is for an offline resource.
// If you need some URLs to be server-rendered, edit the following check to exclude those URLs
const shouldServeIndexHtml = event.request.mode === 'navigate'
    && !manifestUrlList.some(url => url === event.request.url);
```

This seems to do the trick for me, and also works when I did a basic test hosting the app in a subdirectory.

I'm happy to leave the info here for anyone else who hits the issue, and if this solution is deemed satisfactory I'm also happy to put it in a PR.

Cheers

**Comment by javiercn** [comment]
@MatthewKing Yes, this sounds good, we would be happy to take a PR in.
