### ISSUE TITLE
Unable to load test appsettings in integration tests

### ISSUE THREAD

**Issue by abuzaforfagun** [dotnet/aspnetcore#40681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to do some condition checks on the Program file (AKA Startup). That condition is dependent on some configuration. I put that configuration in `appsettings.josn`. 
In the test project I used different appsettings configurations. But unable to get the value of test configuration.

### Expected Behavior

Need to bind the `appsettings.json` of test project.

### Steps To Reproduce

Create a ASP Net Core Web API project selecting .net 6. Uncheck minimal API.

Put this to the program file.
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

var useTests = builder.Configuration.GetValue<bool>("UseTests"); // not binding from test appsettings
if (useTests)
{

}
var app = builder.Build();

app.MapControllers();

app.Run();

public partial class Startup{}
```

Here is the custom web application factory:
```
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup> where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureAppConfiguration(config =>
            {
                var projectDir = Directory.GetCurrentDirectory();
                var configPath = Path.Combine(projectDir, "appsettings.json");
                config.AddJsonFile(configPath);
            });
        }
    }
```

Write a test:

```
public class UnitTest1 : IClassFixture<CustomWebApplicationFactory<Startup>>
    {
        private readonly CustomWebApplicationFactory<Startup> _factory;
        private readonly HttpClient _client;
        public UnitTest1(CustomWebApplicationFactory<Startup> factory)
        {
            _factory = factory;
        }
        [Fact]
        public void Test1()
        {
            var application = new CustomWebApplicationFactory<Startup>();
            var client = _factory.CreateClient();
            var result = client.GetAsync("WeatherForecast");
            Assert.Equal(true, true);
        }
    }
```

### .NET Version

6.0.100

**Comment by halter73** [comment]
The fundamental issue here is that `CustomWebApplicationFactory.ConfigureWebHost()` is called during `var app = builder.Build();` after `var useTests = builder.Configuration.GetValue<bool>("UseTests");` already ran. It's important that `ConfigureWebHost()` runs this late so it can override services and configuration set up before the call to `builder.Build()`.

If you want to configure the `app.Configuration` you can do so with the `WebApplicationFactory`, but you cannot influence `builder.Configuration`. As a workaround, if you need to influence app logic before calling `builder.Build()`, maybe you can set an environment variable from the test and reading that.

Long term we could consider a new `WebApplicationFactory` method that gets called when the `WebApplicationBuilder` is constructed that could influence the initial `builder.Configuration` and `builder.Services`, but this would require some design.

**Comment by halter73** [comment]
> [learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0)
> shows an example that includes ConfigureAppConfiguration. If I add code like that to my code, ASP0013 analyzer tells me not to use it.

Thanks for pointing this out. I opened https://github.com/dotnet/AspNetCore.Docs/pull/28697 to address it.

I agree we need to make a much easier and obvious way to override the config from tests before `WebApplicationBuilder.Build()` is called. We have a duplicate issue tracking this at #37680. I think the [highest rated answer](https://github.com/dotnet/aspnetcore/issues/37680#issuecomment-1032922656) is currently the best one:

```csharp
private class MyWebApplicationFactory : WebApplicationFactory<Program>
{
    protected override IHost CreateHost(IHostBuilder builder)
    {
        builder.ConfigureHostConfiguration(config =>
        {
            config.AddInMemoryCollection(new Dictionary<string, string> { { "Result", "Override" } });
        });

        return base.CreateHost(builder);
    }

    // ...
```
