### ISSUE TITLE
Blazor WebAssembly cached client-side routing is taking precedence over reverse-proxy routing.

### ISSUE THREAD

**Issue by ScionOfDesign** [dotnet/aspnetcore#40684]
I recently deployed a Blazor client-server application. The WebAssembly client and the server application are deployed in separate docker containers (Server is a dotnet container and the WASM is in a Nginx one). The app itself works perfectly at mydomain.net but I have some different applications on different servers located at mydomain.net/myotherapp. They are routed to via a reverse proxy on a different server.

The problem is that now if I have the Blazor app at mydomain.net cached in my browser, visiting mydomain.net/myotherapp now directs me to the "not found" page of the webassembly app unless I force-refresh with Ctrl+F5. Even then, this only resolves the issue for _that page_ of the other application.

This seems to be because the client-side routing is not actually returning a 404 error code as would happen with a multi-page application.
Is there any way to tell the Blazor WASM application to **not** process certain routes? Or at least tell the application to refresh the URL and _ignore_ all caches?

- Changing the Nginx configuration does not seem to affect the Blazor app's behavior after it has been served once.
- Forcing a redirect with javascript in header of index.html causes a redirect loop.
- Forcing a redirect in the 404 page in `OnInitialized` also causes a redirect loop.

I would use subdomains instead if I easily could, but these applications were configured using subdirectories instead. Changing their URL's would require my set of users to update their URL's as well.

**Comment by SteveSandersonMS** [comment]
Is your Blazor WebAssembly application a PWA? This would make a big difference to the situation.

**Comment by ScionOfDesign** [comment]
> Is your Blazor WebAssembly application a PWA? This would make a big difference to the situation.

Yes it is. I would prefer to keep it a PWA if it's feasible.

**Comment by SteveSandersonMS** [comment]
In that case, I don't think this is an aspect of Blazor routing at all. I think this is your service handling requests.

If you're using the service worker that came by default in the Blazor template (`service-worker.published.js`), then you can edit which URL patterns it handles by editing the `onFetch` logic.

**Comment by ScionOfDesign** [comment]
Thanks, I'll try that and post my results.

**Comment by ScionOfDesign** [comment]
I was able to add this section of code to the 'onFetch' function and now it works great! Thanks!
```javascript
if (shouldBlockRoute(event.request.url))
{
   return fetch(event.request);
}
```
