### ISSUE TITLE
System.IO.DirectoryInfo doesn't work properly in client-side Blazor

### ISSUE THREAD

**Issue by Muitsonz** [dotnet/aspnetcore#40686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a System.IO.DirectoryInfo instance created in client-side blazor, it always get a prefix '/' which stop me to access files by absolute paths on Windows.
Most of the codes below are generated by project template, and I only add line 11.
![1](https://user-images.githubusercontent.com/34186630/158123884-58395adf-7814-4ac0-8747-52f59ef845f4.png)

However, server-side blazor works fine. I only see the bug in client-side blazor, so I post the issue here.

### Steps To Reproduce

+ Create a project by project template "Blazor WebAssembly App", with no authentication nor https support, but checked "ASP.NET Core hosted". (with Visual Studio 17.1.1)
+ In Client project, like Program.cs, create an instance of System.IO.DirectoryInfo

### .NET Version

6.0.201

**Comment by SteveSandersonMS** [comment]
I'm afraid client-side Blazor runs client-side, so it can't see the server-side disk. If it could, that would be a massive security vulnerability for your server.

For whatever information you want to make available to your client side code, you should create server-side APIs and call them using HttpClient.
