### ISSUE TITLE
DO NOT WARN : BL0005

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#40685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

warning BL0005: Component parameter '<parameterName>' should not be set outside of its component.

It's fine, I am calling a method ```public void Mutate(Action<ExampleComponent> lambda) { lambda(this); StateHasChanged(); } ```
I understand the code I am writing, I can't disable warning on all projects that uses my library, so just remove this warning unless I can disable it in my library and for everyone that's using my library

### Expected Behavior

don't warn, it's meaningless, remove it

**Comment by SteveSandersonMS** [comment]
Can you post a minimal sample showing what you're doing? It's unclear to me why you're unable to disable this warning in your own project. The warning isn't going to appear for people who *use* your library unless they are also writing their own code of that form.
