### ISSUE TITLE
Add support for argument list surrogates in minimal APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#40712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The idea here is to support using a type that can act like a surrogate for the argument list in a minimal API. The motivation is about refactoring a minimal API that takes a large set of parameters into one that takes a single object with top level properties that represent what were once arguments. This is a common pattern seen with CQRS frameworks where a request object is made to bind all inputs.

### Describe the solution you'd like

```C#
app.MapGet("/products/{id}", (int id, int pageSize, int page, ILogger<Program> logger, MyDb db) =>
{
    logger.LogInformation("Getting products for page {Page}, page);
    
    return db.Products.Skip((page - 1) * pageSize).Take(pageSize);
});
```

The user wishes to refactor this to:

```C#
app.MapGet("/products/{id}", ([Parameters]ProductRequest req) =>
{
     req.Logger.LogInformation("Getting products for page {Page}, req.Page);
    
     return req.Db.Products.Skip((req.Page - 1) * req.PageSize).Take(req.PageSize);
});

public record ProductRequest(int Id, int PageSize, int Page, ILogger<Program> Logger, MyDb Db);
```

The parameter or type needs to be marked explicitly to identify that this is not from the body or elsewhere (query etc). These properties should also support binding attributes:

```C#

public class ProductRequest
{
  [FromRoute]
  public int Id { get; set; } 

  [FromQuery]
  public int PageSize { get; set; }

  [FromQuery]
  public int Page { get; set; } 

  [FromServices]
  public ILogger<Program> Logger { get; set; } 

  [FromServices]
  public MyDb Db {get; set; }
}
```

This would only work for top level properties in this object.

### Additional context

Open questions:
- Do we want to support multiple of these? No 😄

**Comment by Acerby** [comment]
I suspect its fairly common for a number of API method to support a common set/subset of options/properties. Being able to do something akin to:
app.MapGet("/chairs/{cid}", (int cid, [Parameters]CommonProps) => {...}
app.MapGet("/seats/{sid}", (int sid, [Parameters]CommonProps) => {...}
would seem to provide a nice way to allow these to be declared/managed/used in a consistent way.
Additionally common pre-processing operations could be encapsulated by methods/extension-methods on the above CommonProps class.

**Comment by Acerby** [comment]
It feels like there is an overlap between this functionality and that supported by the IModelBinder interface. The primary difference being the class is based declarative automatic generation of the fields based as opposed to being generated via bespoke code. I guess one potential approach to implementation would be to use the [Properties] attribute on the class as a trigger to the complier to auto generate the code to add a default implementation of the IModelBinder interface on the give class.

**Comment by brunolins16** [comment]
## Proposed API

Add new `attribute` that users can decorate their **classes** or **delegates parameters** to allow refactoring a minimal API that takes a large set of parameters into one that takes a single object with top level properties that represent what were once arguments.

``` diff
namespace Microsoft.AspNetCore.Http;

+[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
+public sealed class ParametersAttribute : Attribute
+{ }
```

The idea is supporting the attribute in multiples parameters and also mixed with parameters without the atrribute.

## Usage Examples

#### Attribute specified in the delegate parameter

``` csharp
app.MapGet("/products/{id}", ([Parameters]ProductRequest req, [Parameters]Paging pageInfo) =>
{
     req.Logger.LogInformation("Getting products for page {Page}, req.Page);
    
     return req.Db.Products.Skip((req.Page - 1) * req.PageSize).Take(req.PageSize);
});

public record ProductRequest(int Id, ILogger<Program> Logger, MyDb Db);
public record Paging(int PageSize, int Page);
```

#### Attribute specified in the class/struct

``` csharp
app.MapGet("/products/{id}", (ProductRequest req) =>
{
     req.Logger.LogInformation("Getting products for page {Page}, req.Page);
    
     return req.Db.Products.Skip((req.Page - 1) * req.PageSize).Take(req.PageSize);
});

[Parameters]
public record ProductRequest(int Id, int PageSize, int Page, ILogger<Program> Logger, MyDb Db);
```

## Alternative Designs

As an alternative design, we could also create a public interface (marker).

``` diff
namespace Microsoft.AspNetCore.Http.Metadata;

+public interface IFromParametersMetadata
+{}
```

``` diff
namespace Microsoft.AspNetCore.Http;

+[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
+public sealed class ParametersAttribute : Attribute, IFromParametersMetadata
+{ }
```

That will allow users to create their own attribute implementation, as we have for `IFromServiceMetadata`, `IFromRouteMetadata`, etc.

**Comment by halter73** [comment]
I'm not sure that I like how generic `[Parameters]` is for a parameter attribute. I don't think many people would guess what the attribute does without already knowing. It almost seems redundant. Of course, a parameter is a parameter 😆

This is going to be in a global using by default as part of the `Microsoft.AspNetCore.Http` namespace, so it could show up in a lot of contexts. This is different than all the other attributes we currently use in route handlers like `[FromBody]` that lives in `Microsoft.AspNetCore.Mvc`.

I know what we're really trying to indicate is that the properties of the parameter are treated as a top-level parameter and that it's hard to communicate this in a reasonably short attribute name though. Maybe `[Flatten]` would work? That's less seemingly redundant but just as ambiguous. `[PropertiesAsParameters]`? Would we ever put this in another namespace? We cannot reasonably put it in `Microsoft.AspNetCore.Mvc` unless MVC also supports it which seems unlikely.

**Comment by davidfowl** [comment]
I was waiting for this ugly name discussion 😄. I agree parameters is too generic. I can't wait to 🚲 shed on this.

**Comment by brunolins16** [comment]
Some additional name ideas:

`[Parameters]`
`[AsParameters]`
`[Flatten]`
`[PropertiesAsParameters]`
`[ParameterList]`
`[Surrogate]`

**Comment by JamesNK** [comment]
Does this feature work in MVC? If not, are there any plans to add it? It seems like the idea can be applied to both frameworks.

**Comment by JamesNK** [comment]
Issue for adding support to MVC: https://github.com/dotnet/aspnetcore/issues/42271
