### ISSUE TITLE
Blazor is NOT loosing SignalR connection. Browser is!

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#40721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Those who work with Blazor are fully aware of the SignalR connection failed issue and the adorable "Reload" message. In a recent project, I noticed something very interesting that I never saw mentioned by anyone.

### Steps To Reproduce

Test 1

1. Opened two tabs in Edge browser, latest version, Windows 11, each with different websites using Blazor.
2. Waited for 10 minutes. Both tabs went into "sleep" mode. 
3.  Went back to each of the tabs and there it was, the no connection message with the reload option.

Test 2

1. Opened two tabs in Edge browser, latest version, Windows 11, each with different websites using Blazor.
2. For the second tab I opened Developer Tools (f12) and made sure the no cache option was on.
3. Waited for 10 minutes.  Tabs 1 went into "sleep" mode.  Tab 2 did not because of the Developer Window being open.
4. Went back to each of the tabs. Tab 1 had the "no connection/reload message". Tab 2 still had the website working perfectly.
5. Tested again, but now leaving the browser untouched for more that 2h and tab 1 failed once again while tab 2 resisted and worked perfectly.

Test 3
Just did the same tests but reversed the websites in tab 1 and 2. Now the website in tab 1 is working fine every time and the one in tab 2, consistently fails after awhile. 

Tested this more than 5 times and the result is exactly the same every time. Opening Developer Tools with the no cache option on, is somehow preventing SignalR connection to fail or at least is allowing it to reconnect every single time without a glitch.  Are you aware of this?

### .NET Version

.NET 6 latest version

**Comment by TanayParikh** [comment]
@HybridSolutions if I follow correctly, you're pointing out that the Blazor Server SignalR connection remains connected (doesn't time out/disconnect) if the dev tools (with cache disabled) is left opened. Is that correct?

The fact that the tab with developer tools doesn't go to sleep isn't surprising, it's likely just an edge feature. The fact that having the dev tools open prevents the SignalR connection from going "on standby" is the part I'm unsure about. @BrennanConroy is this expected SignalR behavior?

**Comment by HybridSolutions** [comment]
@TanayParikh that's exactly what I'm saying. I can make a video of my screen if you need to see it happening. I find this behaviour amazing because all the issues out there are always mentioning a problem on SignalR connection but after all there's no issue with it since it can hold wonderfully even longer than a regular session would. 

You can test it for yourself too. Just go to a website like [Blazorise](https://blazorise.com/docs) that uses Blazor, and do my Teste 1 and 2.

**Comment by BrennanConroy** [comment]
If the tab is "active" from the browsers point of view, then SignalR will continue to function. If the tab goes to sleep, then SignalR will stop working. This is the expected behavior.

**Comment by HybridSolutions** [comment]
@BrennanConroy I'm not saying it's not the expected behavior, but the problem that troubles so many developers about Blazor apps keep disconnecting after so little time and having to deal with the browser message is not a Blazor problem after all. It's because of the browser sleeping feature. Maybe Edge could receive an indication in the header that sleeping is not allowed 😁 That would solve the problem

**Comment by BrennanConroy** [comment]
If you want to "solve" the sleeping tab problem there are solutions you can implement to workaround it.
https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-6.0&tabs=visual-studio#bsleep

> Have to say that Microsoft created a problem that works against Blazor with that feature...

Tab sleeping isn't a Microsoft only feature btw.

**Comment by HybridSolutions** [comment]
> If you want to "solve" the sleeping tab problem there are solutions you can implement to workaround it. https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-6.0&tabs=visual-studio#bsleep
> 
> > Have to say that Microsoft created a problem that works against Blazor with that feature...
> 
> Tab sleeping isn't a Microsoft only feature btw.

Yes I know that. Just kidding. Thanks for the link. I'll give a look into it.  It's important that this issue could be better documented, including perhaps warnings about this sleeping tabs Blazor "enemy", because there's a lot of complaints out there about lost connections in very small amount of time. Personally, for now, I developed a solution that automatically refreshes the current page if no connection is possible after a few attempts but I hope this is improved in Blazor in a near future.

**Comment by TanayParikh** [comment]
> but I hope this is improved in Blazor in a near future.

There are a couple of issues tracking work in this area: https://github.com/dotnet/aspnetcore/issues/9256, https://github.com/dotnet/aspnetcore/issues/27576

**Comment by HybridSolutions** [comment]
@TanayParikh  Thanks, I was already following those.

**Comment by konradbartecki** [comment]
Hey that's a good find, but on mobile browsers you have to assume they will always suspend the tab much more aggressively to preserve resources.

So if you ask me, fix should be done on a Blazor side anyway to gracefully restore connections, or have #32113 as a workaround where we just restart the page automatically.

**Comment by HybridSolutions** [comment]
> Hey that's a good find, but on mobile browsers you have to assume they will always suspend the tab much more aggressively to preserve resources.
> 
> So if you ask me, fix should be done on a Blazor side anyway to gracefully restore connections, or have #32113 as a workaround where we just restart the page automatically.

Yes you are right, mobile is another nightmare. I'm using something similar to this

`Blazor.defaultReconnectionHandler.onReconnectionFailed = function (d) {
        document.location.reload(); 
    }`

but with connection retry before it reloads automatically. It works great for now.

**Comment by konradbartecki** [comment]
True but if I remember correctly in .NET 5 and earlier there's like a 3s delay before your connection actually fails, not sure if they fixed that in new .NET versions.

**Comment by konradbartecki** [comment]
I believe it is because after some time the state of the connection on a server side gets disposed, thus there is nothing to reconnect to, so it will always fail.

**Comment by HybridSolutions** [comment]
@konradbartecki I'm not sure what can be done, but something must happen because this behaviour it's not a good experience for users/clients. They just don't like that their websites and web apps keep showing these connection messages after returning from a coffee break. I'm sure .NET/Blazor team will come up with something 💪
At least is on the .NET 7 list and that is already good.... I guess...

**Comment by SteveSandersonMS** [comment]
We think this is covered by #32113, so will close in favour of that.
