### ISSUE TITLE
Support falling back to ConnectionId when RawConnectionId is 0 in HTTP.sys

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#40728]
Currently, on HTTP.sys, HttpContext.Connection.Id always returns a value of 0 on Windows Server 2019 and below. It is populated on Server 2022.

HttpContext.Connection.Id returns RawConnectionId https://github.com/dotnet/aspnetcore/blob/371c81a6945aa71fd7a73f1842c24d2aa26672e6/src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs#L533

If RawConnectionId is 0, HttpContext.Connection.Id should fallback to ConnectionId https://github.com/dotnet/aspnetcore/blob/371c81a6945aa71fd7a73f1842c24d2aa26672e6/src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs#L518 

Related: https://github.com/dotnet/aspnetcore/pull/37945

**Comment by Tratcher** [comment]
Note this regressed in 6.0.1 and 7 when we switched from ConnectionId to RawConnectionId, we hadn't tested on older platforms.
