### ISSUE TITLE
Cant get the Site to work on Publish

### ISSUE THREAD

**Issue by Ariasm55** [dotnet/aspnetcore#40722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we are codding and we are using visual studio to test our Website everything is working fine, but the moment that we want to deploy the App the API deploys correctly, but the WEBSITE does not load, I do get these errors on the console.
<img width="814" alt="image" src="https://user-images.githubusercontent.com/8022173/158445476-a19e425d-caa2-4aac-a4a2-7dbb5c98c341.png">

I have looked online but there are no results on this.
As mentioned if I debug this on Visual Studio there are no Problems, but once deployed into IIS, we cant make this Website work.

### .NET Version

6.0.201

### Anything else?

The IDE is VS

PM> dotnet --version
6.0.201
PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TanayParikh** [comment]
Thanks for reporting @Ariasm55, could you please provide a minimal, public, github repository which reproduces this issue?

**Comment by Ariasm55** [comment]
HI @TanayParikh 

https://github.com/Ariasm55/GettyxPub

Here is the Public Version of the APP

**Comment by feiyun0112** [comment]
it caused by `dotnet.timezones.blat` and `icudt_EFIGS.dat` cannot download

you can see the error in Chrome Dev Tool `Network` tab

add `.blat` and `.dat` MIME type in IIS can solve it

**Comment by javiercn** [comment]
@Ariasm55 @feiyun0112 answer is probably correct.

it's not clear how you are deploying the files, but I couldn't find `UseBlazorFrameworkFiles` anywhere in your app being called. I would suggest you compare your setup against the setup from the template to determine the differences as well as https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0 for things you might be missing

**Comment by feiyun0112** [comment]
clear cache and reload

**Comment by quan0zhou** [comment]
I cloned your code and deployed it to iis and found that it works fine
![image](https://user-images.githubusercontent.com/27860834/158813822-36462055-62ed-41ac-afc0-b2a018f75510.png)

**Comment by Ariasm55** [comment]
Team,

Thanks for all the help I got the Issue fixed due to a Visual Studio Error on Deploy, 
GOt an update on VS and the issue got fixed.
