### ISSUE TITLE
How to change Blazor Wasm stand-alone to hosted

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#40739]
If we start out with a Blazor Wasm stand-alone app, how do we change it to hosted with the server app?  Is there any documentation on this?

.Net 6.0.

**Comment by javiercn** [comment]
@roysurles thanks for contacting us.

There are no concrete steps for this. The recommendation is that you create a hosted template and move the code to it or compare your app against the template.

In general it involves adding a project reference from the host project to the webassembly app and setting up middleware within the host (`app.UseBlazorDebuggerProxy();`... `app.UseBlazorFrameworkFiles();` `app.MapFallbackToFile("index.html")`)
