### ISSUE TITLE
Consider transpiling Microsoft.JSInterop to ES2018

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#40741]
Done to support older devices specifically in the case of Blazor Hybrid.

Use case: 
- https://github.com/dotnet/aspnetcore/issues/39086
- https://github.com/dotnet/aspnetcore/pull/40737

**Comment by mkArtakMSFT** [comment]
@javiercn, @MackinnonBuck any thoughts about this one? Is this still needed?

**Comment by MackinnonBuck** [comment]
Closing since this will probably get done automatically as part of our other JS modernization efforts.
