### ISSUE TITLE
dotnet-watch flaky test Run_WithHotReloadEnabled_ReadsLaunchSettings

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#40740]
This test seems to be flaky and has a bad track record of passing.

**Comment by mkArtakMSFT** [comment]
PR which disabled the tests: https://github.com/dotnet/sdk/pull/24407

**Comment by javiercn** [comment]
This fails around 75% of the time. I don't believe the output from the builds to be significative as the test is pretty straightforward.
