### ISSUE TITLE
Automated InvokeVoidAsync on loaded Blazor component to refresh javascript init

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#40743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Here's the situation and my question is all about architecture so that the best possible way of doing such a thing can be achieved.

Lest's assume I'm using Bootstrap framework that offers some functionality that requires javascript to run after DOM is loaded. For this exercice let's use Tooltips and Popover components. With regular HTML or even Razor Pages this is very easy. We just need to load the required scripts and create a .js file where we initialize the component by using a custom function:

```
var initialized = false;
function blazorInit() {
    if(!initialized)
    {
          var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
          var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
              return new bootstrap.Tooltip(tooltipTriggerEl)
           })

           var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
           var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
                return new bootstrap.Popover(popoverTriggerEl)
           })
           initialized = true;
   }
}
```

In Blazor, this is not that easy.  We also load the required scripts and create the same .js file to initialize both the Tooltip and Popover components but it's necessary to make each Blazor component that is loaded and uses those features to refresh that initialization with the following:

In MyComponent1.razor

```
@inject IJSRuntime JS
@inject NavigationManager MyNavigationManager

protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {            
            await JS.InvokeVoidAsync("blazorInit");
        }
    }
```

And that's it. The problem with this is that if we only do this, we will have to apply this code to every Blazor Component that uses Tooltips or Popovers. My question is, wouldn't it be possible for Blazor to optionally provide a mechanism to run Initialization javascript automatically and behind the scenes avoiding this hassle. Yes I could make a blazor component with this code and reuse it but that would force me to place it on every single component.

I could also define a ComponentBase type base classe and apply it to all my blazor components:

```
public class JsComponentBase : ComponentBase
    {
        [Inject] protected IJSRuntime? JSRuntime { get; set; }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            await base.OnAfterRenderAsync(firstRender);
            if (firstRender)
            {
                await JSRuntime.InvokeVoidAsync("blazorInit");
            }
        }
    }
```

and MyComponent1.razor inherit that base class:

`public partial class MyComponent1: JsComponentBase`
 

### Describe the solution you'd like

How could this be improved at the present time to avoid inserting this initialization mechanism in each component? How can I make this work?

Thank you!

**Comment by javiercn** [comment]
@HybridSolutions thanks for contacting us.

We don't plan to offer this type of functionality out of the box. We try to keep the primitives in the framework as lightweight as possible and this adds a non trivial overhead.

Our recommendation in these cases is one of your suggestions. Define your own base class and perform whatever logic you want/need there and then use that base class in the components you need.

**Comment by HybridSolutions** [comment]
ok I understand your point. It would be handy to have an event for StatusChanged that could be overridden.
