### ISSUE TITLE
Upgrade `Microsoft.IdentityModel.Protocols.OpenIdConnect` dependency to use none-blocking method `ValidateTokenAsync`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#40748]
Currently, we're using `Microsoft.IdentityModel.Protocols.OpenIdConnect` 6.10.0, and the `ValidateToken` method is a .sync-operation.

https://github.com/dotnet/aspnetcore/blob/618b78ed87ff5e4542778d887b1d3926502bb57f/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L114

From `1.16.0`, the token handler introduced `ValidateTokenAsync`, maybe we should prefer `ValidateTokenAsync`

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6.16.0/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1654

**Comment by WeihanLi** [comment]
Could I try to make a PR for this? @adityamandaleeka

**Comment by adityamandaleeka** [comment]
@WeihanLi sure

**Comment by WeihanLi** [comment]
Hi @adityamandaleeka , from the info from <https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1827#issuecomment-1084852912>, the `ValidateToken`  could not be replaced by `ValidateTokenAsync` for now, so I'm going to close this issue
