### ISSUE TITLE
Using WithSummary() for Minimal API endpoints does not render when using Swashbuckle.AspNetCore

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#40753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the [new `WithSummary()`](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/#provide-endpoint-descriptions-and-summaries-for-minimal-apis) method (or `[EndpointSummary]` attribute) on a Minimal API endpoint in ASP.NET Core Core 7 preview 2 does not render the summary in the OpenAPI document generated by Swashbuckle.AspNetCore.

I figure this is because Swashbuckle.AspNetCore would need changes to consume the new metadata to use and output it, but as I thought I'd raise this for visibility as I couldn't immediately see anything in the backlog related to this and because #37906 is closed which seems to imply it should "just work™️".

## Using `SwaggerOperationAttribute`

![image](https://user-images.githubusercontent.com/1439341/158797389-295bb561-9a1c-453e-95fa-f8db091f4b17.png)

## Using `WithSummary()`

![image](https://user-images.githubusercontent.com/1439341/158797460-f3c9312b-de6e-408b-8c7f-ac1ba8cbfb5a.png)

### Expected Behavior

The string passed to the `WithSummary()` method of `[EndpointSummary]` attribute is rendered in the OpenAPI JSON document generated by Swashbuckle.AspNetCore.

### Steps To Reproduce

Clone https://github.com/martincostello/api/commit/66fbf8e8803efed640c8c6c75c432e49b7f32e63, run the application, and navigate to the `/docs` URL in a browser.

### Exceptions (if any)

N/A

### .NET Version

7.0.100-preview.2.22153.17

### Anything else?

N/A

**Comment by hwoodiwiss** [comment]
I'd interested in picking this up if that's alright?

**Comment by captainsafia** [comment]
@hwoodiwiss Absolutely! The changes will need to happen in the Swashbuckle repo but happy to provide guidance here.

**Comment by captainsafia** [comment]
> Would this be a good opportunity to provide general support for the new I..Metadata Interfaces from Miscrosoft.AspNetCore.Http.Metadata interfaces in Swashbuckle? as the Attributes produced by the WithX extensions implement these.

We've generally gone for the approach of adding individual support for each of the new types that were added (see [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2210) and [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2173)).

Moving forward, we'll be relying on the Micorosft.OpenAPI stuff for annotating this stuff directly (see [this](https://github.com/dotnet/aspnetcore/issues/40676)).

**Comment by hwoodiwiss** [comment]
> > Would this be a good opportunity to provide general support for the new I..Metadata Interfaces from Miscrosoft.AspNetCore.Http.Metadata interfaces in Swashbuckle? as the Attributes produced by the WithX extensions implement these.
> 
> We've generally gone for the approach of adding individual support for each of the new types that were added (see [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2210) and [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2173)).
> 
> Moving forward, we'll be relying on the Micorosft.OpenAPI stuff for annotating this stuff directly (see [this](https://github.com/dotnet/aspnetcore/issues/40676)).

Oh interesting, yeah, I can see that rendering any changes I make obsolete fairly quickly.

I've made a "first-pass" implementation over here: https://github.com/hwoodiwiss/Swashbuckle.AspNetCore/tree/hwoodiwiss/asp7-endpointsummarymetadata however this doesn't inlcude the changes for CI that would bee necessary for a PR.

What's the plan with the `WithX` style functions? 
It seems to me that it would make sense for them to act as a bit of a builder(-ish) for an `OpenApiOperation` and then that object would be available in the endpoint metadata?

**Comment by captainsafia** [comment]
> It seems to me that it would make sense for them to act as a bit of a builder(-ish) for an OpenApiOperation and then that object would be available in the endpoint metadata?

Yep, the existing `WithX` methods will remain but in the future we'll be adopting the `WithApiDescription` for modifying any parts of the API.

**Comment by hwoodiwiss** [comment]
Ah that makes sense.

Given that [this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2404) has been merged, is there any need to explicitly support the individual metadata types in Swashbuckle, or is the advice going forward to use WithOpenApi with them to have them populate the generated `OpenApiOperation`, which will then be picked up by Swashbuckle?

**Comment by captainsafia** [comment]
> is there any need to explicitly support the individual metadata types in Swashbuckle, or is the advice going forward to use WithOpenApi with them to have them populate the generated OpenApiOperation, which will then be picked up by Swashbuckle?

Since the summary and description attributes have already been merged and released, I think it is still worthwhile to merge in support for the metadata in Swashbuckle!

**Comment by hwoodiwiss** [comment]
Okie doke, that makes sense, it'll still be nice to be able to supplement info provided using the Swashbuckle attributes without generating the whole `OpenApiOperation` as endpoint metadata.

I'll open the PR over in the Swashbuckle Repo at some point this week, although I can't imagine it will make it into a release until much closer to the release of .NET 7.

**Comment by ylr-research** [comment]
Hi, I am using the latest .NET 7 preview and this is still an issue. I cannot display summary, description, nor produces. Is there any update on this?

**Comment by hwoodiwiss** [comment]
> Hi, I am using the latest .NET 7 preview and this is still an issue. I cannot display summary, description, nor produces. Is there any update on this?

Yeah, there's a PR open with the fix here: domaindrivendev/Swashbuckle.AspNetCore#2414 but it hasn't been merged yet. I'll be looking to get it reviewed and merged when the first RC for .NET 7 is released.

**Comment by captainsafia** [comment]
Howdy folks!

I'm going to close this issue for now since it is external to ASP.NET Core (Swashbuckle needs to pick up the ISummaryMetadata attributes).

Furthermore, for the long term, we are recommending that folks leverage the new `WithOpenApi` to modify the summary and other aspects of the `OpenApiOperation`.

```csharp
app.MapGet("", () => ..)
  .WithOpenApi(o => {
    o.Summary = "Summary";
  });
```

**Comment by ylr-research** [comment]
Thanks @captainsafia for the help today.
