### ISSUE TITLE
IIS HTTP/2 features version check wrong?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#40756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/b184b4facd3657d62fb893126fd0db6684f07724/src/Servers/IIS/IIS/src/Core/IISHttpContext.cs#L400

Is 20348 in the OS version check correct? I see it matches the minimum version of Windows Server 2022 of [20348](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info), but it disallows current versions of Windows 11 (which starts at 10.0.22000).

To allow all Window 11 versions, shouldn't the version number be 20200 or greater? Windows Server 2019 version number stops at 19xxx so it should only allow Windows 11 and Windows Server 2022.

### Expected Behavior

Allow all Windows 11 and Windows Server 2022 versions.

**Comment by JamesNK** [comment]
re: https://github.com/dotnet/aspnetcore/pull/40310

@adityamandaleeka @Tratcher

**Comment by adityamandaleeka** [comment]
> Is [20348](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info) in the OS version check correct? I see it matches the minimum version of Windows Server 2022 of 20348, but it disallows current versions of Windows 11 (which starts at 10.0.22000).

Win 11 works... 22000 > 20348

**Comment by JamesNK** [comment]
Oops. For some reason I misread it as 22348. Never mind 😄

**Comment by JamesNK** [comment]
At least I’m consistently wrong https://github.com/dotnet/AspNetCore.Docs/pull/25353
