### ISSUE TITLE
Ignore Null Properties

### ISSUE THREAD

**Issue by devmayank05** [dotnet/aspnetcore#40751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team, 

The requirement for non-premium licenses we have to ignore certain properties . And we dont wanted to show keep that properties in response.

Can you please help if we can ignore such null properties for some specific controllers?

### Expected Behavior

NA

### .NET Version

3.1

### Anything else?

NA

**Comment by javiercn** [comment]
@devmayank05 thanks for contacting us.

It's not clear what you are trying to accomplish here, could you clarify a bit more your scenario?

**Comment by devmayank05** [comment]
We just wanted to ignore null properties in ODataResponse only for some specific controller.

**Comment by rafikiassumani-msft** [comment]
@devmayank05 We do not clearly understand your scenario or use case. If this is related to Odata can you create an issue on the following repo: https://github.com/OData/odata.net? StackOverflow might also be useful. We will close this issue as we believe it's not related to ASPNET.
