### ISSUE TITLE
WebHostBuilderExtensions UseStartup() uses incorrect logic to determine AssemblyName

### ISSUE THREAD

**Issue by NeilMacMullen** [dotnet/aspnetcore#40755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is possible to control the configuration of a TestServer using a Startup object 

```
var startup = new MyStartup();
var builder = WebHost.CreateDefaultBuilder().UseStartup(_=>startup );
var server =new MyTestServer<MyStartup>(builder);
```

Unfortunately the logic used in UseStartup to determine the AssemblyName fails if the code to create the server is in a different assembly to the declaration of the Startup class.  This is due to this code . (line 45 of WebHostBuilderExtensions) ..

` var startupAssemblyName = configureApp.GetMethodInfo().DeclaringType!.Assembly.GetName().Name!;.`

which attempts to derive the assembly name from the factory method implementation rather than the startup type.  Something like 

` var startupAssemblyName = typeof(TStartup).Assembly.GetName().Name;`

would be more appropriate

The effect of this misbehaviour is that the configuration step appears to fail to correctly locate and bind controllers.

### Expected Behavior

When the Startup object is defined in a separate assembly, to the code that calls UseStartup, the behaviour should be insensitive to the way that the factory delegate is created.  For example in the code below it is very opaque to the user why TestWillSucceed and TestWillFailWIth404 behave differently.

**TestAssembly:**
```
class MyStartup {..}
[Test]
public void TestWillSucceed()
{
    var startup = new MyStartup(...test parameters...);
    using (var server = TestServer<MyStartup>.Create(_=>startup);
   ... try calling controllers...
}

[Test]
public void TestWillFailWith404()
{
    var startup = new MyStartup(...test parameters...);
    using (var server = TestServer<MyStartup>.CreateWithFailedRouting()=>startup);
   ... try calling controllers...
}
```

**TestSupportAssembly:**
```
class MyTestServer : TestServer {
 public static MyTestServer<T> Create()<T>(Func<WebHostBuilderContext, T> createStartup)
 {
     var builder = WebHost.CreateDefaultBuilder().UseStartup(createStartup);
     return new MyTestServer<T>(builder);
 }

public static MyTestServer<T> CreateWithFailedRouting()<T>(Func<T> createStartup)
 => Create(-=>createStartup());
}
```
Really, the whole design is a bit test-unfriendly - if it is indeed the controller binding that is failing it would be desirable to bind these from the original project assembly; the intent here is to create a test that uses a production client communicating with a  TestServer and faked backend services.  Maybe the real fix is to introduce a UserStartupForTest variant that is a bit less bound to the production/deployment conventions ?
 

### Steps To Reproduce

See above

### .NET Version

6.0.201

### Anything else?

>     <PackageReference Include="Flurl.Http" Version="3.2.2" />
>     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
>     <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="6.0.3" />
>     <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.3" />
>     <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />

> ➜ dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   6.0.201
>  Commit:    ef40e6aa06
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.201\
> 
> Host (useful for support):
>   Version: 6.0.3
>   Commit:  c24d9a9c91
> 
> .NET SDKs installed:
>   5.0.404 [C:\Program Files\dotnet\sdk]
>   6.0.200 [C:\Program Files\dotnet\sdk]
>   6.0.201 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by NeilMacMullen** [comment]
So it turns out there is a workaround which is to change 

` services.AddControllers() 
   . ....`

in your customer startup class to 

```
var controllerAssembly = typeof(MyController).Assembly;
...
 services.AddControllers() 
         .AddApplicationPart(controllerAssembly)
         .AddControllersAsServices()
         . ...
```

It still seems wrong though that the default assembly is derived from the method though rather than the startup type.

**Comment by adityamandaleeka** [comment]
Triage: since this is in WebHost code that's not under active development, and there is a workaround, we're not going to address this issue.
