### ISSUE TITLE
@Blackleones

### ISSUE THREAD

**Issue by neozhu** [dotnet/aspnetcore#40767]
@Blackleones 

Maybe I've found a possible workaround: just disable the IdentityContext's change tracking:

```
          services.AddDbContext<IdentityContext>(options =>
            {
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
                options.UseSqlServer(
                    configuration.GetConnectionString("DefaultConnection"));
            }, ServiceLifetime.Transient);
```

I'm currently trying this approach and  at first sight it seems to work.

_Originally posted by @sven5 in https://github.com/dotnet/aspnetcore/issues/22031#issuecomment-650170443_

I tried. Unfortunately, I couldn't change RoleManager<ApplicationRole>  UserManager<ApplicationUser> lifetime

**Comment by adityamandaleeka** [comment]
Closing, this looks like a response to another comment?
