### ISSUE TITLE
`DataAnnotationsValidator` validates unexpectedly when a custom child component changes state

### ISSUE THREAD

**Issue by space-alien** [dotnet/aspnetcore#40780]
My `EditForm` with a `DataAnnotationsValidator` contains a custom `MyComponent` component. The minimal repro below is [published here](https://github.com/space-alien/DataAnnotationsValidatorIssue).

When the button in `MyComponent` is clicked, validation fires on the `EditForm`. This occurs even when none of the form fields have been modified, which is undesirable.

Is this behaviour expected? If so, how can I avoid the form validation being triggered by a change to the child component?

This is occurring in a Blazor Server project on .NET 6.0.3.

## Index.razor

```razor
@page "/"
@using System.ComponentModel.DataAnnotations

<EditForm Model="model">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <label>
        Name:
        <InputText @bind-Value="model.Name" />
    </label>
    <MyComponent />
</EditForm>

@code {
    MyModel model = new();

    class MyModel
    {
        [Required]
        public string? Name { get; set; }
    }
}
```

## MyComponent.razor
```razor
<p>
    MyComponent: @(Switch ? "ON" : "OFF")

    <button @onclick="() => Switch = !Switch">Toggle</button>
</p>

@code {
    bool Switch = false;
}
```

**Comment by casper7526** [comment]
You probably have something like this.
<Button onclick blah blah>
The default type of a button is submit
Does your problem still occur if you use

<Button type="button"

**Comment by space-alien** [comment]
@casper7526 Thank you, you are correct. The button no longer triggers form validation with the `type="button"` attribute.
