### ISSUE TITLE
Published Hosted Blazor WASM does not contain PDB files.

### ISSUE THREAD

**Issue by SwiftMJ** [dotnet/aspnetcore#40787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to publish a hosted blazor wasm application with PDB files.

I couldn't find any way to this this apart from by using the `BlazorEnableDebugging` flag. https://github.com/dotnet/aspnetcore/pull/18859#discussion_r380155392

This flag seems to work for blazor wasm applications, but with hosted the pdb files for the client project are still not output to the publish/wwwroot/_framework directory.

### Expected Behavior

When running the command: 

`dotnet publish -c Release -p:BlazorEnableCompression=false -p:PublishTrimmed=false -p:BlazorEnableDebugging=true`

on a hosted blazor wasm application the pdb files should be included in the following directory:

< server project >/bin/Release/< target framework >/publish/wwwroot/_framework

and the `blazor.boot.json` file should contain a list of the pdbs.

### Steps To Reproduce

Create a blazor wasm hosted solution.

Run the following command to publish from within the Server folder

`dotnet publish -c Release -p:BlazorEnableCompression=false -p:PublishTrimmed=false -p:BlazorEnableDebugging=true`

I have created an [Example Repo](https://github.com/SwiftMJ/BlazorApp1) with these steps complete.

As you can see the `BlazorApp1.Client.pdb` is output in the [client bin folder](https://github.com/SwiftMJ/BlazorApp1/tree/main/BlazorApp1/Client/bin/Release/net6.0/wwwroot/_framework) and on line 205 of the [blazor.boot.json](https://github.com/SwiftMJ/BlazorApp1/blob/main/BlazorApp1/Client/bin/Release/net6.0/wwwroot/_framework/blazor.boot.json) the pdb's are listed.

But in the [server publish folder](https://github.com/SwiftMJ/BlazorApp1/tree/main/BlazorApp1/Server/bin/Release/net6.0/publish/wwwroot/_framework) there is no `BlazorApp1.Client.pdb` and the pdb section is null in the [blazor.boot.json](https://github.com/SwiftMJ/BlazorApp1/blob/main/BlazorApp1/Server/bin/Release/net6.0/publish/wwwroot/_framework/blazor.boot.json)

### .NET Version

6.0.300-preview.22154.4

**Comment by javiercn** [comment]
@SwiftMJ thanks for contacting us.

Symbols are not copied to the publish folder by default. You might use `CopyOutputSymbolsToPublishDirectory` in your csproj folder to control this.

**Comment by SwiftMJ** [comment]
@javiercn Thanks, I added [that](https://github.com/SwiftMJ/BlazorApp1/commit/f427d68148b625ebae0cb996f3ac52d90073d5a7) to the .csproj file for the Client, Server and Shared projects. 

The `BlazorApp1.Client.pdb` is now included in the [publish/wwwroot/_framework](https://github.com/SwiftMJ/BlazorApp1/tree/main/BlazorApp1/Server/bin/Release/net6.0/publish/wwwroot/_framework) although the `BlazorApp1.Shared.pdb` file is not. Any ideas why this would be?

**Comment by javiercn** [comment]
@SwiftMJ I suspect you might need to potentially add that flag to each and every project. We gather the dlls and pdbs from the `ResolvedFilesToPublish` item group, so if it's not there, we won't detect it and copy it.
