### ISSUE TITLE
Authorize Attribute Error

### ISSUE THREAD

**Issue by dor1202** [dotnet/aspnetcore#40797]
Hi.
I think I found a bug when using 
`@attribute [Authorize]`

When the attribute is used in a specific page it works pretty well, but when you want to authorize all the pages and place the attribute in the `_import.razor` file, it will will redirect to another url but not as the first option.

I'm adding the source files.
[test oidc01.zip](https://github.com/dotnet/aspnetcore/files/8315356/test.oidc01.zip)

On the server side I am using orchard core server.

Dor.

**Comment by javiercn** [comment]
@dor1202 thanks for contacting us.

Could you convert the project to a public github repo we can browse?

**Comment by dor1202** [comment]
Hi @javiercn , Thank you for the response!
I can send the client as a repo for sure!
Unfortunately the server is a commercial project so I can't.
Adding the client URL here:
https://github.com/dor1202/ExampleOpenIdProj

**Comment by javiercn** [comment]
@dor1202 New project -> Blazor Webassembly -> Select the hosted option on the checkbox, Select Individual authentication on the authentication options -> Create.

**Comment by dor1202** [comment]
@javiercn I will try it and notify you as soon as posible!
