### ISSUE TITLE
How I can cross compile SignalR C++ Client on raspberry pi(armv7l)?

### ISSUE THREAD

**Issue by G-MoYang** [dotnet/aspnetcore#40815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

cross compile SignalR C++ Client on raspberry pi(armv7l)

**Comment by rafikiassumani-msft** [comment]
@G-MoYang have you tried to follow the Linux build guide document in the following README https://github.com/aspnet/SignalR-Client-Cpp/#build-on-linux?

**Comment by G-MoYang** [comment]
So I changed the file: SignalR-Client-Cpp/submodules/vcpkg/triplets/x64-linux.cmake, set(VCPKG_TARGET_ARCHITECTURE **x64**) to set(VCPKG_TARGET_ARCHITECTURE **arm**), then it can compile openssl. But it fail in compiling boost-regex:x64-linux: 
![image](https://user-images.githubusercontent.com/63628919/159930272-d0cdc62a-ff69-4c85-95ff-a8358c2e9095.png)

**Comment by BrennanConroy** [comment]
This doesn't sound like an issue with SignalR specifically. I recommend checking with https://github.com/Microsoft/vcpkg.

**Comment by G-MoYang** [comment]
Hi Brenan, yes, so I sloved issue by checking this https://github.com/microsoft/vcpkg/pull/11880/commits/6c6af5d7280d36a2901030e87761d016cfb7ccb4#diff-b93dff802371176cfb748f08cd609b9185a5003aba8f1240a78d4f8d8146ee4f
