### ISSUE TITLE
Blazor Server project template: Static assets versioning with `asp-append-version` tag-helpers

### ISSUE THREAD

**Issue by hakenr** [dotnet/aspnetcore#40818]
Before creating a PR I would like to propose and discuss a change in Blazor Server template:

## Summary

In Blazor Server project template (and potentially also ASP.NET Core Hosted Blazor WebAssembly project template) the _Host.cshtml/_Layout.cshtml references static asset files (site.css, CSS isolation .styles.css file, blazor.server.js, ...).
I would like to add `asp-append-version` tag helper to elements linking these files to prevent using browser-cached versions of files when changed.

```razor
<link href="css/site.css" rel="stylesheet" asp-append-version="true" />
```

## Motivation and goals

* When the file changes, browser often uses cached version of the file.
* We want to show the users simple way to solve the pain + incorporate such linking from .cshtml Razor Pages as best-practice.

## In scope

* Adding `asp-append-version` tag helper to Blazor Server project template (https://github.com/dotnet/aspnetcore/blob/66e149ef96fbf785ecd778301438dbc5260d6ab3/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/_Host.cshtml)

## Out of scope (may be discussed as separate issue)

* Migrating ASP.NET Core Hosted WebAssembly project template from Client `index.html` to Server `_Host.cshtml'/`_Layout.cshtml` + applying the same logic with `asp-append-version` there.

## Examples

You can se a source-code examples here:
* https://github.com/havit/NewProjectTemplate-Blazor/blob/master/Web.Server/Pages/_Layout.cshtml
* https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap.Documentation.Server/Pages/_Layout.cshtml

And a running version of the application here:
* https://havit.blazor.eu (_View page source_ in browser)

## Open points to discuss
* [ ] Do we want to add the versioning only to linked CSS files or both the CSS and JS files such as `blazor.server.js`?

**Comment by javiercn** [comment]
@hakenr thanks for contacting us.

Sadly, the proposed change won't work as you expect, since it will only affect the styles.css file and not the other files that it imports (from razor class libraries) which will lead to unexpected results.

The "correct" thing to do here is to set the cache, etag headers on the responses for the files. Sadly, that's not trivial to do and we don't want to include that logic by default on the template.

While the browser might use a cached version of a file, in general, in the absence of a cache directive, the browser won't cache it for very long (I don't know the exact times).

**Comment by hakenr** [comment]
Aah, I see, the appended version does not change when @import-ed files content changes (CSS isolation).
But it is not Blazor-specific, it is just the way query-string-based versioning works. We can also say it does not cover images, fonts or any other static assets referenced from indirectly. We would have to apply similar versioning to the generated @import directives, url() directives and many others to cover the indirect assets reliably.

I think the `asp-append-version` approach is better than nothing and is good-enough for most cases, but I understand that it can create a misleading assumption that it covers everything.
