### ISSUE TITLE
Meaningless usage of Enumerable.OrderBy

### ISSUE THREAD

**Issue by Catalan-1ap** [dotnet/aspnetcore#40824]
Possible you mean Enumerable.ThenBy?

https://github.com/dotnet/aspnetcore/blob/3b8ce2746c6835690a4e1b9c97e3a9ea43844909/src/Servers/Kestrel/shared/KnownHeaders.cs#L146-L147

https://github.com/dotnet/aspnetcore/blob/3b8ce2746c6835690a4e1b9c97e3a9ea43844909/src/Servers/Kestrel/shared/KnownHeaders.cs#L215-L216

**Comment by martincostello** [comment]
Same as #40062?

**Comment by Catalan-1ap** [comment]
> Same as #40062?

Yes, thank you for the reply.
