### ISSUE TITLE
Is .net core compatible with IIS Webdav module ?

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#40838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, I actually a migrate an old asp .net framework 4 web app to asp .net core 6.

This webapp was serving docx et xlsx files through IIS and webdav to allow end users edit directly files on the server

On the old app, the config was like that

- a virtual directory on IIS to associate a virtual Path Webdav to a physical path
- an IHttpModule which allow me to intercept all request on the server and add some authentication when the request point out /webdav (webdav don't support anonymous authentication)
````
HttpContext.Request.Headers.Remove("Authorization");
HttpContext.Request.Headers.Add("Authorization", "Basic " + base64string); 
````
On the new app

- the virtual directory is manage directly on the code (Startup)

````
var lOptions = new FileServerOptions
                {
                    FileProvider = new PhysicalFileProvider(Sys.Web.AppliIs.Path_Webdav),
                    RequestPath = new PathString("/" + Sys.Web.AppliIs.WEBDAV_FOLDER),
                    EnableDirectoryBrowsing = false,

                };
                app.UseFileServer(lOptions);
````
- i intercept the request to add my authentication in a custom middleware (called before the code above)
````
app.Use(async (context, next) =>
            {
                AppliGeckosSL.WriteLogDebug($"intercept {context.Request.Path}, Method : {context.Request.Method}", null);//just to log everything which arrived
                var lFileInfo = lHostEnv.ContentRootFileProvider.GetFileInfo(context.Request.Path);
                if (lFileInfo != null)
                {
                    WebdavFileManager.HandleRequest(context, lFileInfo.PhysicalPath);
                }


                // Call the next delegate/middleware in the pipeline.
                await next(context);
            });

````
When i test the new code (opening a file stored in the server with word), it failed. Whe i inspect the logs, i notice thow things :
- On the IIS logs, i see my different request called by word

````

2022-03-23 11:20:31 ::1 OPTIONS /Webdav/ - 7520 - ::1 Microsoft+Office+Protocol+Discovery 200 0 0 47
2022-03-23 11:20:31 ::1 HEAD /Webdav/BeWise.docx - 7520 - ::1 Microsoft+Office+Existence+Discovery 200 0 0 4
2022-03-23 11:20:31 ::1 OPTIONS /Webdav/ - 7520 - ::1 Microsoft+Office+Existence+Discovery 200 0 0 5
2022-03-23 11:20:31 ::1 LOCK /Webdav/BeWise.docx - 7520 - ::1 Microsoft+Office+Core+Storage+Infrastructure/1.0 405 0 0 4
2022-03-23 11:20:31 ::1 GET /Webdav/BeWise.docx - 7520 - ::1 Microsoft+Office+Core+Storage+Infrastructure/1.0 404 0 3 2
````
we can see the Lock method finished in 405 We can also see the get finishing in 404 which i can't understand because the HEAD finished on 200 on the same file

- The log of my middleware give me only this

````
23/03 12:20:32:023 [FW] intercept /Webdav/BeWise.docx, Method : HEAD
23/03 12:20:32:055 [FW] intercept /Webdav/, Method : OPTIONS
````
so we see the LOCK and the GET are not handle by my server

I see many solutions on this problem on this forum and others which recommand to disable webdav, solution which dont fit me because i want to use webdav

There is not a lot of documentations about .net core and webdav, im not even sure its supported.

I try to remove the virtual directory by code and set a virtual directory through IIS like the old app but still not working, in this case the lock not finish in 405 but in 401. I notice my middleware in not called, so i cant add my authentication. I suppose with this option we don't go through the asp .net core pipeline.

What do you think ? Is it possible to make it work ? if no, whats my other solutions to edit distant document like webdav ?

Thanks for your help !

### Expected Behavior

Have a solution to make the IIs webdav module work with my asp .net 6 app

### .NET Version

6.0.300-preview.22154.4

**Comment by adityamandaleeka** [comment]
While we haven't actively tried to support WebDAV, we don't know of any fundamental limitations that would prevent you from being able to support it in your own code.

The 405 likely indicates a misconfiguration in your routing logic, though you'd have to debug that in your code yourself.

**Comment by julienGrd** [comment]
The configuration is very simple, there is nothing specific, except i have to do something specific for webdav ?

It look asp.net core have trouble to handle some webdav verbs like OPTIONS, PROPFIND or LOCK or HEAD

I create a repro project to illustrate the problem (starter project of webassembly app .net hosted) : https://github.com/julienGrd/TestWebdav

Requirements :
- IIS installed, with webdav and basic authentication activated
- Microsoft word version > 2010

- clone the repository
- update the code tu put a user of your system on this line
````
//TODO put a user of your system here
byte[] toEncodeAsBytes = System.Text.ASCIIEncoding.ASCII.GetBytes("admin:admin");
````
- publish somewhere in the file system
- create the website in iis
- activate webdav for the website 
- add basic authentication for the website
- launch

you will normally see some files in the home page, click on one file
Word will be unable to open the file, when you inspect the log of iis you will see something like that
````
022-03-24 08:49:46 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 200 0 0 0
2022-03-24 08:49:46 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 200 0 0 0
2022-03-24 08:49:46 ::1 HEAD /Webdav/Fichier1.docx - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 200 0 0 0
2022-03-24 08:49:46 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Word - 200 0 0 0
2022-03-24 08:49:46 ::1 LOCK /Webdav/Fichier1.docx - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 405 0 0 0
2022-03-24 08:49:46 ::1 GET /Webdav/Fichier1.docx - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 404 0 3 0
````
the lock finish in 405 and then the GET in 404

I have to play with the web.config to make it works at this step, especially this line
````
 <add name="aspNetCore" path="*" verb="GET,POST,PUT,DELETE, HEAD, LOCK, PROPFIND" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
````

if i let the verb="*" i have a different behavior, the OPTIONS verb finish in 404
````
2022-03-24 09:12:26 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 404 0 0 5
2022-03-24 09:12:26 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Protocol+Discovery - 404 0 0 0
2022-03-24 09:12:26 ::1 OPTIONS /Webdav/ - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 404 0 0 0
2022-03-24 09:12:26 ::1 LOCK /Webdav/Fichier1.docx - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 405 0 0 0
2022-03-24 09:12:26 ::1 GET /Webdav/Fichier1.docx - 5000 - ::1 Microsoft+Office+Word+2014+(16.0.14332)+Windows+NT+10.0 - 404 0 3 0
````

so i have to explicitely remove the options verbs to make it works (maybe its here the problem ?)

What do you think about that ?


I wait for your suggestions

**Comment by julienGrd** [comment]
interesting link here : https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/troubleshooting-http-405-errors-after-publishing-web-api-applications
but it don't give me clue on how resolve my errors.
