### ISSUE TITLE
Blazor Server - Cannot find the fallback endpoint specified by route values: { page: /_Host, area: } exception

### ISSUE THREAD

**Issue by pufpufpuf** [dotnet/aspnetcore#40854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Installing the latest .NET SDK 6.0.201 gives back error [https://github.com/dotnet/aspnetcore/issues/36535](url).
Reverting back to 6.0.101 as a workaround for now.

### Exceptions (if any)

```
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: },
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContexthttpContext,CandidateSetcandidates)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContexthttpContext,IEndpointSelectorPolicy[]policies,CandidateSetcandidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g_AwaitMatch|8_1(EndpointRoutingMiddlewaremiddleware,HttpContexthttpContext,TaskmatchTask)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContextcontext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContextcontext)
```

### .NET Version

.NET 6.0.201

**Comment by javiercn** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem as a public github repository?

**Comment by MedizinPumPer** [comment]
got the same error -> I open a new Project with Blazor-Server App, start it and get the same error. Net 6.0.3
