### ISSUE TITLE
Updating Blazor Server app in IIS causes exception when calling ProtectedLocalStorage

### ISSUE THREAD

**Issue by MartinThorsen** [dotnet/aspnetcore#40862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We use ProtectedLocalStorage in our Blazor Server App to store e.g. a user name.

If we update the app and re-deploy it to IIS, then the next time a page tries to access the local storage the exception shown below is thrown.

Deleting the LocalStorage entries "fixes" the issue. I.e. now the localStorage can be set and retrieved with no issue. It is persisted as expected and works as expected between browser restarts. As soon as the app updated is deployed, the issue reappears.

### Expected Behavior

LocalStorage to be accessible between Blazor server app updates.

I am a newbie to Blazor apps so I am sure I am missing some setting somewhere?

I read through this post (https://gist.github.com/SteveSandersonMS/ba16f6bb6934842d78c89ab5314f4b56#gistcomment-4101106)  by @SteveSandersonMS where other people mention the problem, but I don't see any solutions for Blazor Server apps? Having the user delete the browser's local storage is not a solution for us.

### Steps To Reproduce

1. Make sure your Blazor Server app uses ProtectedLocalStorage to set/get e.g. a username.
2. Deploy a Blazor Server App to IIS.
3. Open your browser and connect to the Blazor app.
4. Make sure state gets saved,
5. Close the browser.
6. Make a change to the server app and republish to IIS.
7. Open your browser and connect to the Blazor app.
8. Navigate to page that attempts to read from local storage.
9. Exception as below.

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/77176292/160019659-394b54a6-5f67-4ab3-a4c2-e37b53c250f6.png)

### .NET Version

6.0.201

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by SteveSandersonMS** [comment]
@MartinThorsen The underlying question here is about how to use ASP.NET Core's DataProtection feature, since that's what's providing the encryption and is reporting the error about your keys.

There's documentation about this at https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0, which contains a range of options for how keys can be stored and used across app deployments.

**Comment by MartinThorsen** [comment]
Fixed by setting 'Load User Profile' to true for my Application Pool.
