### ISSUE TITLE
2FA sign in only returns locked out after n+1 failed attempts

### ISSUE THREAD

**Issue by jennablackwell** [dotnet/aspnetcore#40860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug here https://github.com/dotnet/aspnetcore/issues/26429 was wrong to be closed, so I am going to recreate because it is in fact a bug and our QA team has logged a bug for our app because of this.

We have set 
options.Lockout.MaxFailedAccessAttempts = 3;

When the user has 3 incorrect attempts with using regular password sign in and passing the lockoutOnFailure: true.
           result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, false, lockoutOnFailure: true);
This will return the result that user is locked out as expected on the 3rd failure.

However, when using the 2FA, you can't pass the lockoutOnFailure, which is probably why you have to attempt a 4th time to get hte lockout error in the result.  I did see in the database, the user is indeed locked out.  However, my team is being logged a bug because the result returned doesn't return with lockedout until the 4th attempt.      

var result = await _signInManager.TwoFactorSignInAsync(TokenOptions.DefaultPhoneProvider, 
                Input.Code, true, Input.RememberDevice);

### Expected Behavior

The SignInResult returned should have IsLockedOut = true immediately when the lockout occurs instead of having to attempt an extra time to get IsLockedOut = true.

### Steps To Reproduce

- Set MaxFailedAttempts = 3
- Attempt 2 Factor Sign in with invalid code 3 times.
 var result = await _signInManager.TwoFactorSignInAsync(TokenOptions.DefaultPhoneProvider, 
                Input.Code, true, Input.RememberDevice);
- Notice the result does not have IsLockedOut = true
- Attempt invalid sign in again.  
- Now you receive IsLockedOut = true.

### .NET Version

.NET Core 3.1

**Comment by HaoK** [comment]
This is just how TwoFactorSignInAsync is implemented:

https://github.com/dotnet/aspnetcore/blob/84c0baa9a57bd6448cd1bf78b64d2c1658bf5ef6/src/Identity/Core/src/SignInManager.cs#L523

If you see, it only returns locked out if the user was locked out when you call this method, otherwise it just returns success or failure.  You can always check for lock out yourself when you get a failure result from tfa if you want to distinguish between locked out and failure for some reason

**Comment by adityamandaleeka** [comment]
Triage: We're okay with keeping the behavior as-is. There's a workaround mentioned above if you need to distinguish between lockout and failure.
