### ISSUE TITLE
Razor Component weird namespace issue

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#40861]
I have a standalone project for Razor Components with the namespace XPTO.Components. Here's a simple one stored in the subfolder "DataListComponent":

```
namespace XPTO.Components
{
    public partial class XPTOxDataList<TItem>: ComponentBase
    {
        [Parameter] public IEnumerable<TItem> Data { get; set; }

        [Parameter] public RenderFragment<TItem> ItemTemplate { get; set; }
    }
}
```

My question is, if I don't inherit from ComponentBase, when using this component on a page, I can't access it by using just <XPTOxDataList> and have instead to use "<XPTO.Components.DataListComponent.XPTOxDataList> or import the namespace "XPTO.Components.DataListComponent". Why is directory included if I don't inherit from ComponentBase?

Is this normal?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
