### ISSUE TITLE
SignalR Java Client not working in Android 12

### ISSUE THREAD

**Issue by johnifegwu** [dotnet/aspnetcore#40874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I implemented SignalR Java Client in my Android Project. It works well on Android Versions 6 to 11 but fails on Android 12, I'm not sure what the problem is.

### Expected Behavior

I expected SignalR Java Client to work seamlessly on Android 12 just as it is on Android 11 and Lower. 

### Steps To Reproduce

Here is my code:
```
import android.content.Context;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.microsoft.signalr.HubConnection;
import com.microsoft.signalr.HubConnectionBuilder;
import com.microsoft.signalr.OnClosedCallback;

import org.json.JSONObject;

import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;

import timber.log.Timber;

public class SignalRChatService {

Timer timer = new Timer();

public void startTimer()
{
    timer.scheduleAtFixedRate(new TimerTask() {
        @Override
        public void run() {
            // Your code here
            Timer_Elapsed();
        }
    }, 1000, 2000);
}

private void Timer_Elapsed()
{
    try
    {
        module.checkNetwork(context);

        if(!Connected)
        {
            Init();
        }
    }
    catch (Exception e)
    {
        Connected = false;
    }
}

private HubConnection _connection;

public boolean Connected;

public String instanceName;
public int instanceProfileId;

private boolean connecting;

private SignalRMessageReceivedEvents signalRMessageReceivedEvents;

private final Gson gson;

private final Context context;

public SignalRChatService(Context context, String instanceName, int instanceProfileId, SignalRMessageReceivedEvents signalRMessageReceivedEvents) {
    this.instanceName = instanceName;
    this.instanceProfileId = instanceProfileId;
    this.connecting = false;
    this.context = context;
    this.signalRMessageReceivedEvents = signalRMessageReceivedEvents;
    gson = new GsonBuilder().setPrettyPrinting().create();
}

public void Stop()
{
    try
    {
        _connection.stop();
    }
    catch(Exception ignored)
    {}
}

public void Init()
{
    if (connecting)
    {
        return;
    }
    try
    {
        connecting = true;

        _connection  = HubConnectionBuilder.create("https://" + instanceName.trim().toLowerCase() + ".com").build();

        try
        {
            _connection.start();
            Connected = true;
        }
        catch (Exception e)
        {
            Connected = false;
            Timber.e("SignalR Push connect: %s", e.getLocalizedMessage());
            return;
        }

        _connection.on("Message", (message) ->
        {
            try
            {
                // Separate this code affterwads
                JSONObject messageObject =  new JSONObject(message);
                String Messagetype = (String) messageObject.get("messageType");
                HandleWebSocketMessage(Messagetype, message);
            }
            catch (Exception ignored)
            {

            }
        }, String.class);

        _connection.onClosed(new OnClosedCallback() {
            @Override
            public void invoke(Exception exception) {
                handleClosed();
            }
        });

    }
    catch (Exception ignored)
    {

    }
    finally
    {
        connecting = false;
        startTimer();
    }

}

private void handleClosed()
{
    try
    {
        TimeUnit.MILLISECONDS.sleep(100);
    }
    catch (Exception ignored)
    {

    }
    Init();
}
}
```

### Exceptions (if any)

java.net.SocketException: Socket closed [Ljava.lang.StackTraceElement;@e95116d

### Anything else?

ASP.NET Core SignalR Java Client versions 3.0.0 to 6.0.3

**Comment by BrennanConroy** [comment]
What's not working? Is it a compile time error? A runtime error? Are there any exception messages?
If you remove the SignalR library does your app still run?

**Comment by johnifegwu** [comment]
Hi,

There are no compile time errors and as far as I know there are no runtime errors.
The code works fine on Android 11 and lower, it connects fine and receives data from the Server, but fails to receive any data on Android 12.

**Comment by johnifegwu** [comment]
The App runs with or without the SignalR Library.

**Comment by BrennanConroy** [comment]
Ok, share logs and/or a network trace
https://docs.microsoft.com/aspnet/core/signalr/java-client?view=aspnetcore-6.0#add-logging
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#network-traces

> as far as I know there are no runtime errors.

I am a bit suspicious of this because you are ignoring any errors that HubConnection.Start might be throwing. Start returns an RX Completable and if you don't observe it then you won't see the exceptions if there are any.

**Comment by johnifegwu** [comment]
I will work on this and get back to you ASAP.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by johnifegwu** [comment]
> Ok, share logs and/or a network trace
> https://docs.microsoft.com/aspnet/core/signalr/java-client?view=aspnetcore-6.0#add-logging
> https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#network-traces
> 
> > as far as I know there are no runtime errors.
> 
> I am a bit suspicious of this because you are ignoring any errors that HubConnection.Start might be throwing. Start returns an RX Completable and if you don't observe it then you won't see the exceptions if there are any.

Any exception on HubConnection.Start is Logged, see my code above. But I will also work on providing a Network Trace.

**Comment by BrennanConroy** [comment]
> Any exception on HubConnection.Start is Logged, see my code above.

No, that's what I just explained.
Start returns an RX Completable and if you don't observe it then you won't see the exceptions if there are any.

A simple example is try to connect to an endpoint that doesn't exist like http://localhost:5030 and you wont see an error. Then if you do `_connection.start().blockingAwait();` you will see an error.

**Comment by johnifegwu** [comment]
Hi I did change from `_connection.start(); ` to  `_connection.start().blockingAwait();   ` yet no Exceptions, and SignalR Java Client is not receiving data on Android 12.

**Comment by johnifegwu** [comment]
I finally have an Exception:
`java.net.SocketException: Socket closed
[Ljava.lang.StackTraceElement;@e95116d ` this is from Android 12 Samsung S21 Ultra

**Comment by rafikiassumani-msft** [comment]
@johnifegwu Were you able to resolve the socket issue after examining the exception?

**Comment by johnifegwu** [comment]
I don't know how get that done, I was actually thinking it will be resolved by the SignalR Team.

**Comment by BrennanConroy** [comment]
SocketException is probably coming from the OkHttpClient so not directly related to SignalR. This could be because you need to change the configuration of the HttpClient or the Android config. SignalR doesn't do anything different between Android 11 and 12 so this likely isn't a SignalR specific issue.

**Comment by johnifegwu** [comment]
Hi @BrennanConroy ,

I got it, thanks. But do you have a clue on what should be done to fix this? Any thing that can help me solve this will be really appreciated. Many thanks in advance.

**Comment by captainsafia** [comment]
Triage: It looks like this issue might not be related to SignalR. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com).
