### ISSUE TITLE
Kestrel should ignore Content-Length for 204 responses

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#40883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5
> Metadata in the
   response header fields refer to the target resource and its selected
   representation after the requested action was applied.

>    A 204 response is terminated by the first empty line after the header
   fields because it cannot contain a message body.

https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.4.1

So, while the 204 it may not contain a response body, it may still contain headers that describe what the body would be after this operation, similar to if you had issued a HEAD request.

Identified by a YARP customer:
-	YARP proxies the request
-	IIS responds with 204, a Content-Length: 11, and no body.
-	YARP copies the response status and headers, and when it goes to copy the body it reads 0 data.
-	YARP exits gracefully, it never triggered the 204 body exception because it never wrote any body data to kestrel.
-	Kestrel ends the response and sees that not enough data was written to match the content-length. It converts the response to a 500.

### Expected Behavior

Ignore Content-Length headers for 204 and 304 responses, similar to HEAD requests.
https://github.com/dotnet/aspnetcore/blob/5a5b2e2e18b9f9fa4fbb88fa91a881cedd2fc91a/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L884-L892

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMGDO9DRPO4F", Request id "0HMGDO9DRPO4F:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 11).
```
(no stack trace, I don't think this exception is actually thrown, just logged).

### .NET Version

6

**Comment by Tratcher** [comment]
On further reading, the spec has been updated to clarify this situation:
https://httpwg.org/specs/rfc7230.html#header.content-length
A server MUST NOT send a Content-Length header field in any response with a status code of 1xx (Informational) or 204 (No Content).

**Comment by Tratcher** [comment]
Recommendation:
- No changes to Kestrel
- Consider filtering out this header in YARP since this is known behavior of IIS apps

**Comment by halter73** [comment]
Should we close this issue then?
