### ISSUE TITLE
Having an issue with input type="range"

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#40894]
The code below creates an input type="range" element that when dragged, display the changes in a span element. The issue is that while dragging the slider it is jumping and its display is distort. I succeeded to solve the issue by adding `style="display: block"` to the span element or using a div instead of the span. In short, the element  above the input type="range" is a block element. This, as I have said, solve the issue described above. My question is why does the change I made solve the issue. What is going on here.

Thank you...

```razor
@page "/"

<span>Detection Threshold: @_objectDetectionThreshold %</span>
<input type="range" class="slider" min="0.0" step="0.1" max="100.0"
       @bind-value="_objectDetectionThreshold" @bind-value:event="oninput"
       data-toggle="tooltip" title=@_objectDetectionThreshold data-placement="top" />

@code
{
 private float _objectDetectionThreshold { get; set; } = 80.0f;
 }
```

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

Does this issue reproduce if you do it with plain HTML + JavaScript?

**Comment by enetstudio** [comment]
Hi, javiercn,

> Does this issue reproduce if you do it with plain HTML + JavaScript?

No, it is not. It works perfectly well with plain HTML + JavaScript.

Thank you...

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

We believe this is an artifact of how you are styling your application and not something related to Blazor, the flickering happens because of the way the value is being rendered in the `span`
