### ISSUE TITLE
Disable log in custom AuthenticationHandler

### ISSUE THREAD

**Issue by tytannial** [dotnet/aspnetcore#40895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I can't disable log by using 
`
"Logging": {
    "LogLevel": {
      "Microsoft.AspNetCore.Authentication": "Warning"
    }
  }
`
in appsettings.json, but if I set logging level for a custom AuthenticationHandler. It will disable all other logs that I provided.
I just want to disable the logs from "Microsoft.AspNetCore.Authentication", the parent class.

Using "Microsoft.AspNetCore.Authentication": "Warning" to change log level only for the parent class.

**Comment by Tratcher** [comment]
The same logger is used in the parent and derived class. The workaround would be to create your own logger instance in the derived class that uses a different category name. 

https://github.com/dotnet/aspnetcore/blob/34f71bb22ce65e59c9b9bfbe3e183db395ef5595/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L112

**Comment by tytannial** [comment]
So... I need create logger separately for base class and inherited class. :D

**Comment by tytannial** [comment]
The problem is the parent class "Microsoft.AspNetCore.Authentication.AuthenticationHandler.Logger"
Create logger with the name "MySite.Auth.TokenAuthHandler"

"Logging": { "LogLevel": { "MySite.Auth.TokenAuthHandler": "Warning" } }

is working, but it will disable all the log form this class...

**Comment by Tratcher** [comment]
You'd need to give your logger in the derived class a different category name so you can configure it independently from be base class.

**Comment by Marusyk** [comment]
> You'd need to give your logger in the derived class a different category name so you can configure it independently from the base class.

@Tratcher
Could you please explain how it will work because the problem is in that the Base and Derived logger will be the same.
Look:

```
public class MyAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{

	private readonly ILogger<MyAuthenticationHandler> _logger;

	public SharedAccessSignatureAuthenticationHandler(
		IOptionsMonitor<AuthenticationSchemeOptions> options,
		ILoggerFactory logger,
		UrlEncoder encoder,
		ISystemClock clock,
		IConfiguration configuration)
		: base(options, logger, encoder, clock)
	{
		_logger = logger.CreateLogger<MyAuthenticationHandler>();
	}
	
	protected override Task<AuthenticateResult> HandleAuthenticateAsync()
	{
		_logger.LogWarning("MyAuthenticationHandler");	
		return Task.FromResult(AuthenticateResult.Success(GetAuthenticationTicket()));
	}
}
```

Then the log will be:
> MyAuthenticationHandler
> AuthenticationScheme: MyAuthenticationScheme was challenged.

and the logger name for both is `MyAuthenticationHandler`. How to disable logs from `AuthenticationHandler` (AuthenticationScheme: MyAuthenticationScheme was challenged.)?

**Comment by Tratcher** [comment]
> Should we then create something like this in MyAuthenticationHandler :
> 
> ```
> _logger = logger.CreateLogger("DummyMyAuthenticationHandler");
> ```

Yes, that's what I was thinking.

> It looks strange!

What do you mean? You can name that category anything you want.
