### ISSUE TITLE
How to set SpaDevelopmentServerOptions SpaProxyMaxTimeoutInSeconds?

### ISSUE THREAD

**Issue by awtkeithlin** [dotnet/aspnetcore#40892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

https://github.com/dotnet/aspnetcore/blob/ae1a6cbe225b99c0bf38b7e31bf60cb653b73a52/src/Middleware/Spa/SpaProxy/src/SpaDevelopmentServerOptions.cs

I want to pass 	<SpaProxyMaxTimeoutInSeconds>9999999</SpaProxyMaxTimeoutInSeconds> to it how to do?
<SpaProxyServerUrl>https://localhost:5001</SpaProxyServerUrl>  is okay
<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>   is okay

SpaProxyMaxTimeoutInSeconds => not work
   app.UseMiddleware<SpaProxyMiddleware>();  => not work

### Describe the solution you'd like

Angular build project may need 3 min  so spa proxy  need wait it.

**Comment by awtkeithlin** [comment]
is SpaProxyTimeoutInSeconds?

**Comment by javiercn** [comment]
@awtkeithlin thanks for contacting us.

You can set `SpaProxyTimeoutInSeconds` in your csproj file and that should pick it up.
