### ISSUE TITLE
Is .net core compatible with IIS Webdav module ?

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#40903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, this issue is exactly the same than https://github.com/dotnet/aspnetcore/issues/40838, but this last one was closed a bit quickly, and i think there was misunderstood about what i want to achieve. I don't want to provide my own implementation of webdav, but let webdav module make the job for me.

the question is : Is the webdav module in IIS (https://docs.microsoft.com/en-us/iis/install/installing-publishing-technologies/installing-and-configuring-webdav-on-iis) can be activated and used Inside an asp .net core app ?

actually when you write webdav and .NET core in google, 100% of the answer are "disable the webdav module its a problem with asp .net core". I see nobody try or able to make the module work in asp .net core.

there is some documentation about modules and asp.net core (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules?view=aspnetcore-6.0), but the webdav module is absent from the list.

Can you clarify the position of microsoft about this module ?  
- if not working, update your documentation at this subject
- if working, provide some guidelines on how to avoid the 404/405, response on the exotics verbs used by webdav.

Thanks for you time and your help, this problem block actually one of my client stuck in .NET framework because of that

### Expected Behavior

clarification about IIS Webdav module and asp .net core

### .NET Version

6.0.300-preview.22154.4

**Comment by blowdart** [comment]
No. The IIS WebDav module is for old fashioned ASP.NET framework pieces and is not compatible or detectable from ASP.NET.

To be honest webdav is a security worry, it's not something I'd want ASP.NET to ever support going forward.

I've created a docs PR to call it out as unsupported.

**Comment by blowdart** [comment]
Yea, there's nothing close to it I'm afraid, aside from Office's hosted options now, which are more secure because it's all within the app,
