### ISSUE TITLE
Dev certificate inside docker container is not valid

### ISSUE THREAD

**Issue by Rubbiroid** [dotnet/aspnetcore#40910]
Hello,

for our ci we build windows docker images where AspNetCore projects are tested. Some of the test (with WireMock.Net) need a valid trusted ssl certificate to be installed in the system. We can't use `dotnet dev-certs https --trust` for this, as an user interaction is required for that.
What have we tried:

- generate certificate during image build and import it in container using `certutil`

    ```
    dotnet dev-certs https -ep $pfxFile -p $password
    certutil -f -enterprise -p $password -importpfx my $pfxFile
    certutil -f -enterprise -p $password -importpfx root $pfxFile```
- generate a CA and localhost certificate and install it using `certutil` (similar to our linux images, where it works as expected)
- do these steps during the build or in entrypoint of the image

in all cases AspNetCore (`dotnet dev-certs https -c -t`) doesn't find a valid certificate when we start a container. Magically it is valid during the build of the image, but after start.

If we add `-v` to the check certificate in running container, we get an exception. The tests are not working:

    PS C:\> dotnet dev-certs https -c -t -v
    [1] Listing certificates from CurrentUser\My
    [7] An error occurred while listing the certificates: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist

Do you have any advise or solution, how can we solve the issue and force asp.core to recognise the certificate?

Thank you in advance,
Pavel Fischer

**Comment by javiercn** [comment]
@Rubbiroid thanks for contacting us.

The dev certificate is not meant to be used within test containers or similar test infrastructure, it's strictly designed for development workflows. I would suggest you provision your own certificate and install it on the machine, configuring your app to load it at runtime, for example via an environment variable.

**Comment by Rubbiroid** [comment]
Thank you for the answer. We will then generate the certificates and use it in the config
