### ISSUE TITLE
Introduce interface with static abstract BindAsync method for custom bound parameters of route handler delegates

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#40927]
C# 11 introduces support for **static abstract** interface members. We should update the support for custom parameter binding via a static `BindAsync` method in Minimal APIs to discover and invoke the `BindAsync` method via a newly defined interface (see below). We would continue to support the existing discovery and invocation via reflection approach we introduced in .NET 6 to maintain backwards compatibility.

``` c#
public interface IBindableFromHttpContext<TSelf>
    where TSelf : class, IBindableFromHttpContext<TSelf>
{
    static abstract ValueTask<TSelf?> BindAsync(HttpContext context, ParameterInfo parameter);
}
```

I welcome additional interface name suggestions :smile:

**Comment by halter73** [comment]
API Review Notes:

- Let's use the Http.Abstractions namespace
- Add class constraint from PR

``` c#
namespaces Microsoft.AspNetCore.Http.Abstractions;

public interface IBindableFromHttpContext<TSelf>
    where TSelf : class, IBindableFromHttpContext<TSelf>
{
    static abstract ValueTask<TSelf?> BindAsync(HttpContext context, ParameterInfo parameter);
}
```
