### ISSUE TITLE
URL Protocol Issue in the HTML Output with Razor Engine

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [dotnet/aspnetcore#40923]
No protocol is added to the html output even though I specifically specify the https protocol. That's why I get the warning in the Google Lighthouse. 

![image](https://user-images.githubusercontent.com/55924924/160480971-1988698b-13e3-4eda-9d22-5853e2a50fd0.png)

Actually, the html code contains the protocol but is not rendered in the output.

**_Layout.cshtml**
`<link rel="canonical" href="https://gurkantuna.com" />`

I tried many ways to get it as https:// but no matter what i do i can't produce the protocol in the html output because they are already in the same root and the output is "//". So, how can I add the protocol?

Lighthouse Issue link https://github.com/GoogleChrome/lighthouse/issues/13786

**Comment by javiercn** [comment]
@g-u-r-k-a-n thanks for contacting us.

Could you create a minimal repro project as a public github repository that illustrates the issue?

Do you have any other software in the pipeline that is inspecting and possibly altering the response?

**Comment by g-u-r-k-a-n** [comment]
> @g-u-r-k-a-n thanks for contacting us.
> 
> Could you create a minimal repro project as a public github repository that illustrates the issue?
> 
> Do you have any other software in the pipeline that is inspecting and possibly altering the response?

Oh, you're right @javiercn, it was my bad :pensive: I found the cause in a [3rd party package](https://github.com/Taritsyn/WebMarkupMin) in the pipeline. It turns out that strangely manipulating the protocol. I don't know, maybe there is a parameter in the package to fix this issue. I will review the source code and report to the author as the case may be. Thanks for your help. :+1:
