### ISSUE TITLE
AddGoogle/ AddOpenIdConnect Does not work for Blazor Server

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/aspnetcore#40936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to implement Authentication using Google for my Blazor Server App. I Already do it for a Asp.Net MVC App and it works perfectly. I did same in BlazorServer App but unfortunately it do not complete. In case of implementing it using AddGoogle it throw the following error:
![image](https://user-images.githubusercontent.com/48277995/160644467-4fbc9ee0-26d6-41e4-b7b9-680a45cc80b3.png)
And in case of implementing it using OpenID Connect it throws following errors:
![image](https://user-images.githubusercontent.com/48277995/160645639-3a54ba24-53c8-4a08-b637-403590cc5ae0.png)

### Expected Behavior

Add should works as it do in MVC App

### .NET Version

6.0.201

**Comment by javiercn** [comment]
@abdollahkahne thanks for contacting us.

There's nothing specific about this in ASP.NET Core Blazor. In Blazor server authentication happens before the application starts, so if you are using Google + Cookie to authenticate users and setup a session that should work.

**Comment by abdollahkahne** [comment]
Thanks for your response @javiercn 
I am not sure what is the reason for solving the error exactly but the difference in MVC template and Blazor Template was using `UseAuthorization` Middleware. After adding the middleware to Blazor Server Project, it works as it in MVC. It would be great if some one  describe me what happens behind the scene by adding `UseAuthorization`. I think it do nothing except calling `AuthorizationService` in case of using Authorize attributes!

Thanks for making me to challenge myself instead of framework @javiercn .

**Comment by abdollahkahne** [comment]
Sorry. It was a typo in callback (I have a path equal to Callback Path in my app, so instead of Authentication Handler, my logic get called!). Thanks for your response as always.
