### ISSUE TITLE
SignalR 405 when connecting via TestServer

### ISSUE THREAD

**Issue by Phylum123** [dotnet/aspnetcore#40939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.net 6.0 web api app. using .net 6.0 xunit test app.
Test based on: [https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)

When I try to connect to the SignalR server via TestServer using a WebApplicationFactory, I get an Http error 405 - Method not Allowed. From what I could find searching online, this means either a compatibility issue or CORS is not enabled. CORS is enabled on my web API and I have  stepped through the code that enables it, to make sure it was being called. As for compatibility I made sure I didn't install a singalR nuget library by mistake on the SUT, and verified I am using the correct client on my test app. PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.3". I am writing an integration test and previously it was working, so I know that my factory is correctly creating the web API in memory and I verified it was successfully executing a POST call. I made sure in Startup I have services.AddSignalR(); and that the hub was mapped at the endpoints. Below is the code I introduced into the arrange section of the previously working integration test. I simply want to detect if the SingalR event is firing when a web API url post is called. It fails on the last line with the 405 error. 

### Expected Behavior

No error when connecting.

### Steps To Reproduce

```
            var connection = new HubConnectionBuilder()
                .WithUrl(_client.BaseAddress + _webApiUrlPart + "ApprovalsHub", 
                    o => o.HttpMessageHandlerFactory = _ => _factory.Server.CreateHandler())
                .Build();
            
            connection.On<ApprovalType, IEnumerable<ApprovalDto>>(nameof(IApprovalsHub.ApprovalsRefresh), 
                (approvalType, approvalList) => { refreshCalled = true; });

            await connection.StartAsync().ConfigureAwait(false);
```

### Exceptions (if any)

HTTP 405 - Method Not Allowed

### .NET Version

6.0

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/issues/11888 is tracking making this easier.

For 6.0 you need to use the new WebSocketFactory option on the client, see https://github.com/dotnet/aspnetcore/issues/11888#issuecomment-938550932 for an example

**Comment by Phylum123** [comment]
Thank you for your help. Following the code I found in the link you provided, I have changed my code to what you see below. However, now I get "Incomplete handshake, status code 400"

```
            // Act
            var url = _client.BaseAddress + _webApiUrlPart + "ApprovalsHub";

            var connection = new HubConnectionBuilder()
                .WithUrl(url, o => {
                    o.Transports = HttpTransportType.WebSockets;
                    o.SkipNegotiation = true;
                    o.HttpMessageHandlerFactory = _ => _factory.Server.CreateHandler();
                    o.WebSocketFactory = async (context, cancellationToken) =>
                    {
                        var wsClient = _factory.Server.CreateWebSocketClient();

                        return await wsClient.ConnectAsync(new Uri(context.Uri.ToString()), cancellationToken);
                    };
                }).Build();
            
            connection.On<ApprovalType, IEnumerable<ApprovalDto>>(nameof(IApprovalsHub.ApprovalsRefresh), 
                (approvalType, approvalList) => { refreshCalled = true; });

            await connection.StartAsync().ConfigureAwait(false);
```

**Comment by BrennanConroy** [comment]
It'd be interesting to see if there are any logs/exceptions for the error.

**Comment by Phylum123** [comment]
The stack trace is below. How else can I get more detailed information on the error? I have already turned on detailed errors on signalR. I also made sure the test server has logging setup (using the same logging as the SUT), but I don't see any logs produced and only have this exception to work with. 


   at Microsoft.AspNetCore.TestHost.WebSocketClient.<ConnectAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.CIIS.Pario2.Approvals.WebApi.ApprovalsTests.<>c__DisplayClass9_0.<<Post_CreateApproval>b__3>d.MoveNext() in C:\Users\JTower\source\repos\Pario2NewModel\Test.CIIS.Pario2.Approvals.WebApi\ApprovalsTests.cs:line 92

**Comment by BrennanConroy** [comment]
> I don't see any logs produced and only have this exception to work with

That's unfortunate, the exception is just the 400 error so that's not new information.

I think we're going to need a minimal repro app as a github repo in order to investigate this.
