### ISSUE TITLE
Program.Main.cs for the worker template should not use Company.WebApplication1 for the namespace

### ISSUE THREAD

**Issue by Treit** [dotnet/aspnetcore#40942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The recently added `src\ProjectTemplates\Web.ProjectTemplates\content\Worker-CSharp\Program.Main.cs` file should not use `Company.WebApplication1` for the namespace, because background worker services are not 'web applications'. This is the currently checked in code:

```cs
using Company.Application1;

namespace Company.WebApplication1;

public class Program
{
    public static void Main(string[] args)
    {
        IHost host = Host.CreateDefaultBuilder(args)
            .ConfigureServices(services =>
            {
                services.AddHostedService<Worker>();
            })
            .Build();

        host.Run();
    }
}
```

### Expected Behavior

The namespace should be something like `Company.BackgroundService1` or something similar to more accurately reflect the nature of the service.

**Comment by TanayParikh** [comment]
Hi @Treit, thanks for contacting us. Per my understanding the `Company.WebApplication1` namespace is just a placeholder and is overwritten by the templating engine when you actually use the template to create a project. I could be mistaken though, so will leave the issue open so we can get confirmation on that understanding.

**Comment by javiercn** [comment]
@Treit thanks for contacting us.

We use that name as a placeholder in all our templates as @TanayParikh suggested. This is an internal implementation detail that doesn't get reflected on the generated projects and that we don't have intention to change, since it makes it harder to make changes across all our templates when needed.
