### ISSUE TITLE
Shorten -ep option on the dev-certs tool to a single character

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#4094]
Linux [conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) typically only allow a single character following the hyphen to enable -zydafkldfh syntax.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
