### ISSUE TITLE
Worker service template should include use of IHostApplicationLifetime

### ISSUE THREAD

**Issue by Treit** [dotnet/aspnetcore#40941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The template used by `dotnet new worker` does not include use of `IHostApplicationLifetime` to cause the host process to exit when the worker service terminates.

This actually bit us in production because it was not intuitive that exiting your worker service's `ExecuteAsync` method would not result in the application terminating. We ended up with a zombie process not doing any actual work.

I polled several developers on my team about the current behavior and they all were surprised to find the process remains running.

### Describe the solution you'd like

The template for `worker` should include registering and injecting an `IHostApplicationLifetime` into the service so that `StopApplication()` can be called to gracefully exit the process when the service is no longer running.

**Comment by Treit** [comment]
Actually I believe the only change would be in Worker.cs to get the lifetime manager via DI, as an IHostApplicationLifetime seems to be automatically registered already.

**Comment by davidfowl** [comment]
Was you expectation that on graceful exit of the all background services, the host would shutdown?

cc @eerhardt

**Comment by eerhardt** [comment]
My understanding is that a "worker service" is an app that stays running in the background - like a web server, windows service, daemon, etc. If you want an app that exits when it is done, why not just use a console app?

**Comment by Treit** [comment]
> Was you expectation that on graceful exit of the all background services, the host would shutdown?
> 
> cc @eerhardt

Yes, I didn't really expect that the host would continue running when there were no longer any background services actually doing anything, meaning the host was no longer hosting anything.

To answer @eerhardt, the service is intended to run indefinitely but if it detects that it has gotten into a bad state it exits so that the hosting infrastructure (Azure container instances in this case) will see that the process died and restart it.

So the intent is not that the service is ever "done" in the normal case, but in edge cases it may decide to stop running.

Throwing an unhandled exception would achieve the same purpose I suppose, it simply didn't occur to me that exiting would result in a zombie process.

**Comment by adityamandaleeka** [comment]
>  it was not intuitive that exiting your worker service's ExecuteAsync method would not result in the application terminating

We should at least document the surprising behavior.

**Comment by adityamandaleeka** [comment]
This was added in https://github.com/dotnet/docs/pull/30288

See https://docs.microsoft.com/en-us/dotnet/core/extensions/workers#signal-completion
