### ISSUE TITLE
Use -o | --output for specifying the certificate export path following CLI conventions

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#4095]
Currently the `--export-path` option of the dev-certs tool signals both the desire to export a certificate and also the path of the exported certificate. For consistency with the CLI we should be using `-o | --output` for the output path and make the intention to export the certificate more explicit: `dotnet dev-certs https --export -o <path> -p <password>`

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
