### ISSUE TITLE
Add ASP.NET Core Visual Basic project template

### ISSUE THREAD

**Issue by skurth** [dotnet/aspnetcore#40954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Like written in https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/ there is "ASP.NET Core Web API" support for Visual Basic, but there is no template available in VS2019 and also not in VS2022.

Without a template this is not really supported. 

The same template with the same options like in C# should be available for VB:
![image](https://user-images.githubusercontent.com/11660701/160857075-22f5b69e-604d-4c34-8f8d-9806437ad938.png)

![image](https://user-images.githubusercontent.com/11660701/160857142-ee289b50-5bfb-40e5-94f6-4fc4c1225dc1.png)

(It's the same issue like https://github.com/dotnet/aspnetcore/issues/34788. It was closed without a reason. At least in VS2022 there should be a template. It was also asked multiple times in blog post comments like https://devblogs.microsoft.com/dotnet/whats-new-for-visual-basic-in-visual-studio-2022/)

### Describe the solution you'd like

Available ASP.NET Core Visual Basic project template in VS2022 with the same options like C#

**Comment by javiercn** [comment]
@skurth thanks for contacting us.

While Visual Basic is supported in ASP.NET Core, we don't have plans at the moment to offer Visual Basic based templates.

/cc: @DamianEdwards

**Comment by skurth** [comment]
This is not what MS promised for VB.

Please have a look at this change:
In VS2019, it was possible to create a C# WebApi and convert it with [this tool](https://github.com/icsharpcode/CodeConverter) to VB and it was possible to run it. 
In VS2022, it's not possible anymore because of the new design of Program.cs:
![image](https://user-images.githubusercontent.com/11660701/160991029-3dfa7a4c-304e-41b8-993e-b8add6208c81.png)

So please tell me how a VB dev can know how to set up a new ASP.NET Core Web Api in VS2022?

If you don't provide a template in VS2022, at least please provide an official example somewhere (GitHub, Blog post, ...).

@LadyNaggaga @KathleenDollard
