### ISSUE TITLE
Coding Standards: naming private variable members

### ISSUE THREAD

**Issue by ibthmcts** [dotnet/aspnetcore#40951]
## Summary
Whilst going through some of the code, I noticed there were some inconsistences in how variables are named e.g. some private static variables begin with a capital letter but some begin with underscore.

## Motivation and goals
- As someone new to the code, consistency (or a coding standard) helps in following along
- It helps when contributing also as it all looks uniform
- Developers are guided in how to write their code
- The application looks like one piece, instead of different parts put together

## Out of scope
- Developers naming variables in their own way as opposed to an agreed standard.

## Risks / unknowns
- Making a change such as prefixing all private static variables with "_" might break existing parts of the code that use "nameOf(...)" or pieces of code that have code templates as a string or rely on reflection and the private static members being named a certain way.

## Examples
- Here are some examples I found after doing a search for "private static " in the source code. Notice the naming convention is different:
- "private static volatile Process _redisServerProcess;"
- "private static readonly object _redisServerProcessLock = new object();"
- "private static readonly string[] NamespaceParts = new[] { "RenderTree", "Components", "AspNetCore", "Microsoft", };"

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by Pilchie** [comment]
@javiercn - this might be something we talk about with @dotnet/aspdoi

**Comment by javiercn** [comment]
We discussed this at the time, and we decided that the benefit was not worth the churn it would cause in the repo.
