### ISSUE TITLE
Unable to uninstall .NET Core 2.1.30 Hosting Bundle

### ISSUE THREAD

**Issue by adrho** [dotnet/aspnetcore#40955]
### Description

Ran into the same issue as dotnet/runtime#62853 https://github.com/dotnet/runtime/issues/62853. I can't uninstall dotnet core 2.1.30 Hosting Bundle, as it crashes midway through the uninstall. 

I've tried with Add or Remove Programs -> .NET Core Windows Server Hosting -> Uninstall. 
I've tried Repairing the program.
I've tried to use the dotnet-core-uninstall tool, all of them fail. 

Here is what I find in Event Viewer after the uninstaller crashes

Faulting application name: dotnet-hosting-2.1.30-win.exe, version: 2.1.30.60071, time stamp: 0x5ec2f717
Faulting module name: wixstdba.dll, version: 3.14.4118.0, time stamp: 0x5ec2f758
Exception code: 0xc0000005
Fault offset: 0x00003c80
Faulting process id: 0x4bb0
Faulting application start time: 0x01d843bfaba3ab50
Faulting application path: C:\ProgramData\Package Cache\{b74cd41c-f2e8-49b0-b4f4-e558fdfcd8a5}\dotnet-hosting-2.1.30-win.exe
Faulting module path: C:\WINDOWS\Temp\{8255EBA5-5260-40CB-B7A0-CFB6E0A29AE3}\.ba\wixstdba.dll
Report Id: bd53ffd1-46c8-4a96-9cee-2d26981f018a
Faulting package full name: 
Faulting package-relative application ID: 

Log file from the uninstaller (found in %TEMP%)
[dd_dd_DotNetCoreWinSvrHosting__20220329155230.log](https://github.com/dotnet/runtime/files/8375580/dd_dd_DotNetCoreWinSvrHosting__20220329155230.log)

### Reproduction Steps

Control Panel -> right click .NET Core 2.1.30 hosting bundle -> uninstall.

Other .NET Core 2.1.30 applications can be uninstalled fine.

### Expected behavior

To be able to uninstall the framework.

### Actual behavior

Does not uninstall anything.

### Known Workarounds

The suggestion in the linked issue is to install a later version, which won't work since 2.1.30 is the latest version of 2.1.

**Comment by joeloff** [comment]
@wtgodbe as an FYI

Based on the logs, the ASP.NET runtime which ships in other installers were referenced by both VS and the .NET SDK:

`[4BB0:7278][2022-03-29T15:52:30]w328: Found dependent: VS.{AEF703B8-D2CC-4343-915C-F54A30B90937}, name: Unknown
[4BB0:7278][2022-03-29T15:52:30]w328: Found dependent: {a9e37bb1-ee5d-4b41-9f49-44820b0a19c8}, name: Microsoft .NET Core SDK 2.1.818 (x64)`

**Comment by wtgodbe** [comment]
Interesting - is that not the case with 3.1 and higher?
