### ISSUE TITLE
Add a --create option to the dev-certs tool and clarify in the help text that it is the default

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#4096]
It's not clear that `dotnet dev-certs https` creates a certificate. I'd like to add an optional --create option that shows up in the help text with a comment that says it is the default. In other words, `dotnet dev-certs https` is short for `dotnet dev-certs https --create`.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
