### ISSUE TITLE
Disable Minimal API

### ISSUE THREAD

**Issue by Ximik87** [dotnet/aspnetcore#40968]
Is there an option to disable minimal API templates in .net 6? Let me explain - when there is little code, minimal api is great, but when there is a lot of code, everything turns into spaghetti code, the division into ConfigureServices and Configure methods give a clear separation of what and when to set up

**Comment by davidfowl** [comment]
There isn't an option no, and we don't plan to add one. If you want to keep the startup class, there's a documented pattern for how to continue using the startup class with the new hosting model https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#use-startup-with-the-new-minimal-hosting-model

**Comment by MariovanZeist** [comment]
@Ximik87 you might be interested in https://github.com/dotnet/aspnetcore/issues/40877
And it looks like this feature may be backported to 6.0.300

**Comment by Ximik87** [comment]
@MariovanZeist this is what I need, thanks!
