### ISSUE TITLE
ContentRootPath normalization / DataProtection Discriminator

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#40964]
https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/DataProtection/DataProtection/src/Internal/HostingApplicationDiscriminator.cs#L23

Changes in trailing / no slash are what causes cookies to break between versions

we need to figure out where/how to normalize things

cc @blowdart

**Comment by blowdart** [comment]
We're going to break someone no matter what we do *sigh* Didn't we break from 3.1 and 5 to 6?

**Comment by HaoK** [comment]
Well prior to 6, there was no trailing slash in the content root.
In 6 (for minimal style apps), there's a trailing slash
Now in 7, its back to no trailing slash, so non minimal apps will behave the same, its just minimal apps from 6 won't be able to read their cookies in 7

So for non minimal apps, i think there's no issue in any versions, as content root never had a slash.

Its only minimal style hosting apps that are seeing things change

**Comment by blowdart** [comment]
Oh well if it's "just" minimal apps, then minimal apps should change to be the same as everything that came before (and a quirk ported back to 6)

**Comment by HaoK** [comment]
I believe the issue is at the hosting layer (minimal vs non minimal use a different hosting environment I think?), which is why we have to pick between changing the hosting behavior (to enforce no trailing slashes), or add some logic to our discriminator which now will strip trailing slashes from the content root.

**Comment by HaoK** [comment]
So @blowdart are we okay just normalizing the default data protection application discriminator to always trim trailing slashes?  I think that will get us out of this business of content root changes breaking data protection

**Comment by HaoK** [comment]
Alternatively we could clean it up here: which seems less ideal

https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/DataProtection/DataProtection/src/DataProtectionUtilityExtensions.cs#L45

**Comment by blowdart** [comment]
Works for me. And obviously documentation in release notes

**Comment by HaoK** [comment]
7.0 change is in, using this to track 6.0 servicing fix

**Comment by HaoK** [comment]
@blowdart @Tratcher @adityamandaleeka wait a second, while I was writing up the Customer Impact/Risk for the 6.0 port of this fix.  Won't this almost certainly cause exactly the issue we are trying to avoid?  All of a sudden their dataprotection application discriminator will potentially be different and cause all their apps to sign out/invalidate all cookies in a servicing release, since 6.0 currently has a trailing slash.

This seems to be way worse than doing nothing and just fixing things in 7.0 no?

**Comment by adityamandaleeka** [comment]
Let's leave 6.0 alone for now, since we don't want to break people with a patch update. There is a known workaround already.
