### ISSUE TITLE
Make shadow copy a non-experimental feature

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspnetcore#40961]
TODO list (WIP):
- [x] Change setting name (currently `experimentalEnableShadowCopy`) https://github.com/dotnet/aspnetcore/pull/41006
- [x] Add official doc content (https://github.com/dotnet/AspNetCore.Docs/issues/25499)

**Comment by HaoK** [comment]
Do we want to keep supporting the old experimentalEnableShadowCopy name as well for back compat?

**Comment by adityamandaleeka** [comment]
No, I think we're okay with not supporting that version of the option.

**Comment by HaoK** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/25499 is the doc issue to track what content we want to put in the official docs

**Comment by adityamandaleeka** [comment]
Closing, this is done.
