### ISSUE TITLE
Rename dev-certs -q option to -v | --verbosity following CLI convention

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#4097]
For consistency with the CLI commands the dev-certs tool should follow the `-v | --verbosity` CLI convention for setting verbosity:

```
-v|--verbosity        Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
```

Quiet should have no output
Minimal should only output errors and warnings (equivalent to existing -q option)
Normal would be the default verbosity
Detailed and diagnostic would both be the same as the existing --verbose option

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
