### ISSUE TITLE
GetUserAsync takes very long

### ISSUE THREAD

**Issue by DaveInAus** [dotnet/aspnetcore#40989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

GetUserAsync(Request?.HttpContext.User) takes very long with an Azure SQL remote database connection
However if one uses the following in lieu of GetUserAsync its significantly faster (200ms apposed to 1600ms)
```
var uid = userManager.GetUserId(Request?.HttpContext.User);
if (uid == null) { return Unauthorized(); }
var user= await userManager.FindByIdAsync(uid);
```

### Expected Behavior

GetUserAsync should not take longer that FindByIdAsync

### Steps To Reproduce

```
//Case 1
Stopwatch stopwatch = Stopwatch.StartNew();
var user = GetUserAsync(Request?.HttpContext.User) ;
var timeTaken =stopwatch.ElapsedMilliseconds;
stopwatch.Restart();
//Case 2
var uid = userManager.GetUserId(Request?.HttpContext.User);
if (uid == null) { return Unauthorized(); }
var user= await userManager.FindByIdAsync(uid);
var timeTaken =stopwatch.ElapsedMilliseconds;
```

### .NET Version

6.0.3

**Comment by adityamandaleeka** [comment]
@DaveInAus Let us know if swapping them does in fact make the other approach faster.
