### ISSUE TITLE
Remove JsonPropertyNameAttribute from all properties of ProblemDetails

### ISSUE THREAD

**Issue by anreton** [dotnet/aspnetcore#41005]
## Background and Motivation

At the moment, all properties ProblemDetails have attribute JsonPropertyNameAttribute with camelCase-style.

[ProblemDetails](https://github.com/dotnet/aspnetcore/blob/b6630137b2109042dc11ece3164782e451647bff/src/Http/Http.Extensions/src/ProblemDetails.cs)

But not everyone uses style camelCase-style in their projects, e.g. like this:

```csharp
_ = services
	.AddControllers()
	.AddJsonOptions
	(
		jsonOptions =>
		{
			jsonOptions.JsonSerializerOptions.PropertyNamingPolicy = null;
		}
	);
```

For casing-style consistency with the rest of the project, it might make sense to remove the JsonPropertyNameAttribute from all properties of ProblemDetails.

**Comment by Tornhoof** [comment]
Problem Details is specified in RFC 7807
https://datatracker.ietf.org/doc/html/rfc7807
It is very specific about the spelling/casing of the individual properties.
So you can't really remove the fixed values.

**Comment by anreton** [comment]
> Problem Details is specified in RFC 7807 https://datatracker.ietf.org/doc/html/rfc7807 It is very specific about the spelling/casing of the individual properties. So you can't really remove the fixed values.

@Tornhoof, thank you for your response.

Looked through the specification Problem Details. But nowhere did I find a specific requirement about casing of the properties.

**Comment by Tornhoof** [comment]
The RFC contains the literal spelling of the individual properties, they even quote each occurrence.

I don't think your goal of configuration is bad, just your suggested method, as it will break conformance with the RFC.

**Comment by monterolebronhg** [comment]
@anreton you can also create a new JsonConverter only for ProblemDetails

**Comment by anreton** [comment]
@monterolebronhg, indeed, thanks for the replies.

Perhaps I should close the issue.
