### ISSUE TITLE
[Trimming] Microsoft.AspNetCore.Http.Results

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#41015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Microsoft.AspNetCore.Http.Results is not yet trimmed.

### Describe the solution you'd like

Trim Microsoft.AspNetCore.Http.Results. All dependencies have been trimmed.

**Comment by ShreyasJejurkar** [comment]
Can we have new label for trimming related issues, just like we have linker-friendlyness!?

**Comment by JamesNK** [comment]
They're the same thing.

**Comment by brunolins16** [comment]
@JamesNK has a PR related to this issue, moving to .NET Preview 2.

https://github.com/dotnet/aspnetcore/pull/46082

**Comment by JamesNK** [comment]
Fixed with https://github.com/dotnet/aspnetcore/pull/46082
