### ISSUE TITLE
How to set a secret to null or "" using dotnet user-secrets?

### ISSUE THREAD

**Issue by ljani** [dotnet/aspnetcore#4101]
Here's my use case: I'm trying to override [`Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerOptions.Authority`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.authority?view=aspnetcore-2.1#Microsoft_AspNetCore_Authentication_JwtBearer_JwtBearerOptions_Authority) with either `null` or empty string `""` to disable the authority during development time. Next I would set [`Microsoft.IdentityModel.Tokens.TokenValidationParameters.IssuerSigningKey
`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.issuersigningkey?view=aspnetcore-2.1#Microsoft_IdentityModel_Tokens_TokenValidationParameters_IssuerSigningKey) (hey, missing docs) to a symmetric key and use a JWT signed by that with my rest client.

However when documenting this procedure, I ran in to a issue with `dotnet user-secrets` that it does not accept eg. `--null`, `""`, `''` as the value parameter. As a workaround in this case I can use `" "` and it'll work, because I'm checking the authority with `string.IsNullOrWhiteSpace`. Someone else might not have this option. Can we draft how this should work?

Directly editing `$env:APPDATA\Microsoft\UserSecrets\x\secret.json` works perfectly.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
