### ISSUE TITLE
ExcludedRoles parameter in Authorize and AuthorizeView

### ISSUE THREAD

**Issue by aterbo** [dotnet/aspnetcore#41012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is it possible to make a parameter for `<AuthorizeView>` that is basically the opposite or `Roles`, such as `ExcludedRoles`, where if a user is in a specific role group they will see the `<NotAuthorized>` section?

For a lot of my components, they will be visible to all roles except for one or two. It would be nice to have the flexibility to say "don't show this to anyone in this role" instead of the default of "show this to all of these roles." 

Using only the allowed `Roles` parameter requires that I maintain a current list of all roles except for the one or two that won't have access. If I add a new role, I need to actively add it to all lists.

There is the issue of dealing with users in two roles, where one role is authorized and one is excluded. Priority could either be set with a flag parameter, or it could default to the more stringent set up where excluded roles take precedence. 

### Describe the solution you'd like

Assuming you have `Admin`, `User`, `Manager`, roles, some structure like the following. In this example, `ExcludedRoles` takes precedence over authorized `Roles`:

```
<AuthorizeView>
    <Authorized>
        //All logged in users will see this section
    </Authorized>
</AuthorizeView>

<AuthorizeView Roles="Admin, Manager">
    <Authorized>
        //All Admins and Managers will see this section
    </Authorized>
</AuthorizeView>

<AuthorizeView ExcludedRoles="User">
    <Authorized>
        //Anyone in the Users role will NOT see this section.
    </Authorized>
    <NotAuthorized>
        //All Users will see this section
    </NotAuthorized>
</AuthorizeView>


<AuthorizeView Roles="Manager" ExcludedRoles="User">
    <Authorized>
        //Anyone who is a manager will see this section.
    </Authorized>
    <NotAuthorized>
        //All Users will see this section, even if they are also a manager
    </NotAuthorized>
</AuthorizeView>
```

**Comment by MariovanZeist** [comment]
Hi @aterbo 
Might I suggest a different approach.
You could use profiles.
For example I set up 3 profiles in ``ConfigureServices`` for invoices like this:

```cs
services.AddAuthorization(opt =>
{
	opt.AddPolicy("CanCreateInvoice", policy => policy.RequireRole("user" ));
	opt.AddPolicy("CanViewInvoice", policy => policy.RequireRole("user", "admin", "manager"));
	opt.AddPolicy("CanEditInvoice", policy => policy.RequireRole("admin", "manager"));
});
```
and you can use it like this:

```razor
<AuthorizeView  Policy="CanViewInvoice">
    <Authorized>
        //All Users, Admins and Managers will see this section
    </Authorized>
</AuthorizeView>

<AuthorizeView  Policy="CanEditInvoice">
    <Authorized>
        //Only Admins and Managers will see this section, not Users
    </Authorized>
</AuthorizeView>
```

This way if you add roles, you will only have to change the policies, and not every ``<AuthorizeView>`` 

I am scratching the surface here of what you can do with policies but take a look [here](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0)

**Comment by blowdart** [comment]
Security uses allowed lists over disallowed lists as it's less risky. Taking an exclusionary approach means you'd end up reviewing everything when you add a new role, because that new role would have access to everything by default if all you did was exclude. In your example it's strange that managers aren't considered system users, in a typical design managers are users, just with extra rights.

Adding an exclusion based rule would go against that principal and isn't something we'd bake into the product.

**Comment by aterbo** [comment]
@MariovanZeist  @blowdart  Thank you for the responses. They are definitely good approaches that make sense.
