### ISSUE TITLE
Published app can't be accesed

### ISSUE THREAD

**Issue by 0djek** [dotnet/aspnetcore#41020]
Hello, I created asp.net + React app and when debugging, I can access it with no problems. But when I publish it and launch it with dotnet <name>.dll, I can't access it. I get this error: 
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMGKU86UO80S", Request id "0HMGKU86UO80S:00000037": An unhandled exception was thrown by the application.
      System.InvalidOperationException: No signing credential is configured by the 'IdentityServer:Key' configuration section.

Any help would be appreciated on how to fix it, thank you!

**Comment by javiercn** [comment]
@0djek thanks for contacting us.

You need to configure the signing key to use in production. Check [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0#example-deploy-to-azure-app-service) for details
