### ISSUE TITLE
Mac: dotnet dev-certs https --trust does not explain how to undo this

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/aspnetcore#4102]
When you run this command, it does not say what actually is taking place, it leaves a critical element, which is needed later to undo this:

```
$ dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <<certificate>>'
This command might prompt you for your password to install the certificate on the system keychain.
```

I could not figure out what certificate was added to my system, it took me a while to debug this as the actual certificate is replaced with the string `<<certificate>>` above.

**Comment by adityamandaleeka** [comment]
This is the message being referenced here: https://github.com/dotnet/aspnetcore/blob/c085e17ae390c43961adb8047b127611ad14b207/src/Tools/dotnet-dev-certs/src/Program.cs#L368

We should make it give some kind of breadcrumb so the user knows how to find it (or even make the message a runnable snippet).
