### ISSUE TITLE
Blazor app fails to run with JS error "Failed to invoke 'StartCircuit' due to an error on the server"

### ISSUE THREAD

**Issue by MrYossu** [dotnet/aspnetcore#41023]
Hello,

I have a server-side Blazor app that I've been developing, and runs fine locally. I have just deployed it to a test server for the first time, but none of the Blazor bits work, meaning that pages are pre-rendered, but none of the Blazor interaction works.

Looking in the browser console, I see the following...

>Uncaught (in promise) Error: Failed to invoke 'StartCircuit' due to an error on the server.
>    at t.callbacks.<computed> (blazor.server.js:1:23131)
>    at e.processIncomingData (blazor.server.js:1:24367)
>    at e.connection.onreceive (blazor.server.js:1:17286)
>    at WebSocket.i.onmessage (blazor.server.js:1:46503)

This is a brand-new .NET6 app, not an upgrade from .NET5. I have tried republishing and redeploying a few times, but I always get the same error.

The project file looks like this...

```html
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.0.3" />
    <PackageReference Include="Kveer.XmlRPC" Version="1.2.0" />
    <PackageReference Include="LanguageExt.Core" Version="4.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pixata.Blazor" Version="1.12.0" />
    <PackageReference Include="Pixata.Blazor.LanguageExtComponents" Version="1.0.2" />
    <PackageReference Include="Pixata.Blazor.TelerikComponents" Version="1.4.0" />
    <PackageReference Include="Pixata.Email" Version="1.0.0" />
    <PackageReference Include="Pixata.Extensions" Version="1.20.0" />
    <PackageReference Include="Square" Version="17.3.0" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>

```

`Program.cs` looks like this...

```c#
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

string connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<AppDbContext>(options => {
  options.UseSqlServer(connectionString);
  options.EnableSensitiveDataLogging();
  options.EnableDetailedErrors();
}, ServiceLifetime.Transient);
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddIdentity<User, IdentityRole>(options => {
    options.SignIn.RequireConfirmedAccount = false;
    options.Password.RequiredLength = 4;
    options.Password.RequireNonAlphanumeric = false;
    options.Password.RequireUppercase = false;
    options.Password.RequireLowercase = false;
    options.Password.RequireDigit = false;
    options.User.RequireUniqueEmail = true;
  })
  .AddDefaultTokenProviders()
  .AddEntityFrameworkStores<AppDbContext>();

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor().AddCircuitOptions(options => {
  options.DetailedErrors = true;
});
builder.Services.AddTelerikBlazor();
builder.Services.AddTransient<AntamediaHelper>();
builder.Services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<User>>();
builder.Services.AddTransient<PaperCutHelper>();
SmtpSettings smtpSettings = builder.Configuration.GetSection("Smtp").Get<SmtpSettings>();
builder.Services.AddSingleton(smtpSettings);
builder.Services.AddTransient<PixataEmailService>();
builder.Services.AddTransient<RazorRenderEngine>();
SquareData squareData = builder.Configuration.GetSection("Square").Get<SquareData>();
builder.Services.AddSingleton(squareData);
builder.Services.AddTransient<SquareHelper>();

WebApplication app = builder.Build();

if (app.Environment.IsDevelopment()) {
  app.UseMigrationsEndPoint();
} else {
  app.UseExceptionHandler("/Error");
  app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapBlazorHub();
app.MapFallbackToAreaPage("/_Host", "General");

```

The `Logging` section of `appSettings.json` looks like this...

```json
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Debug",
      "Microsoft.AspNetCore": "Debug"
    }
  },
```

Anyone any ideas what's going wrong? The code shown above was pretty much all copied from a previous app that works fine.

Thanks

P.S. Please let me know if there is any more information I can give.

**Comment by TanayParikh** [comment]
Hi @MrYossu, thanks for contacting us. Can you please try to create a new blazor server project (`dotnet new blazorserver`) and deploy that to your remote environment. Does the issue still persist?

**Comment by MrYossu** [comment]
@TanayParikh Thanks for the reply. Yes, a new Blazor server-side project works fine.

What do I do now? Thanks again.

**Comment by MrYossu** [comment]
@TanayParikh Hmm, this is more weird than a really weird thing.

I deleted all the out-of-the-box Blazor app files and uploaded my own again, and got all sorts of different problems. I then republished, and now it's working fine.

I have no idea what is/was going on here, but I wasted hours trying to get this site deployed, only to have the original code work. I haven't changed anything, not on the site, nor on the server.

Any ideas what might have gone wrong?

**Comment by javiercn** [comment]
@MrYossu We can't tell what might have gone wrong with the information available to us. I would recommend if this happened again you turn the logging level up to Debug or Trace and capture the logs when you try to connect to the deployed app.

**Comment by MrYossu** [comment]
@javiercn Where would I see the logs? Bear in mind this is on a third-party server, not my local machine, so I don't have a console. Where would the logging be shown?

Thanks

**Comment by MrYossu** [comment]
@javiercn OK, thanks. I don't (yet) have logging in this app, as it's still in the early stages. I just wondered if there was anywhere that logging might show up by default, like it does in the console when you're running in VS.

Thanks again.
