### ISSUE TITLE
SymmetricSecurityKey used in JwtBearer TokenValidationParameters does not implement RFC2104 key padding

### ISSUE THREAD

**Issue by aussieklutz** [dotnet/aspnetcore#41024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Setting a key, with a length less than the block size of a HMACSHA256 or 512, in a SymmetricSecurityKey, and then providing it to a JwtBearer TokenValidationParameters results in failed validation of JWT's. RFC2104 states that the key should be padded by \0 null bytes out to the block length, prior to validation. 

The following demonstrates the issue:

`builder.Services.AddAuthentication(options => {
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options => {
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateAudience = true,
        ValidateIssuer = true,
        ValidIssuer = "https://localhost:7046/",
        ValidAudience = "https://localhost:7046/",
        RequireSignedTokens = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("shortsecret")),
        ValidateLifetime = true
    };
});`

This will fail to validate with a JWT generated from JWT.IO with the same secret. Long keys are appropriately handled.

### Expected Behavior

The following shows a viable workaround for the current behavior, for a HS512 token:

`builder.Services.AddAuthentication(options => {
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options => {
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateAudience = true,
        ValidateIssuer = true,
        ValidIssuer = "https://localhost:7046/",
        ValidAudience = "https://localhost:7046/",
        RequireSignedTokens = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("shortsecret".PadRight((512/8), '\0'))),
        ValidateLifetime = true
    };
});`

### Steps To Reproduce

https://github.com/aussieklutz/JwtPaddingDemo

### .NET Version

 dotnet --version 6.0.201

**Comment by aussieklutz** [comment]
I am unsure where exactly this should be rectified. Probably in the JwtBearerHandler somewhere...

**Comment by blowdart** [comment]
We don't actually do any of the crypto work, that falls to [identity model](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) so an issue should be filed there. Having said that I wouldn't be surprised if they said "No", because encouraging the use of short keys would be an odd security decision, and as you already have a work around 🤷‍♂️

**Comment by aussieklutz** [comment]
Thanks for the response. I half wanted to raise this, to enable the work around to be findable.
