### ISSUE TITLE
Debugging Blazor WASM after publish

### ISSUE THREAD

**Issue by vrassouli** [dotnet/aspnetcore#41033]
Hello every body
I've build a Hosted Blazor WASM project, and I'm able to debug blazor code inside the browser using Alt+Shift+D. Starting the app both without debugging or with debugging, using the visual studio. It works just as expected...

But the problem is that, when I publish it (both with Release or Debug configuration), and when I launch the output executable, Alt+Shift+D throws an error on the browser console:
`Cannot start debugging, because the application was not compiled with debugging enabled.`

Also, I tried to manually launch the application from bin folder (build output of visual studio, which works as expected), but it also throws the same error.

Is there any way to debug Blazor after publish?

Thanks in advance

**Comment by javiercn** [comment]
@vrassouli thanks for contacting us.

You need to make sure you enable `DebuggerSupport` as well as `CopyOutputSymbolsToPublishDirectory` when you publish

**Comment by javiercn** [comment]
@guardrex do we have docs on how to publish and debug blazor webassembly apps? Could we add a section if not?

**Comment by vrassouli** [comment]
> @vrassouli thanks for contacting us.
> 
> You need to make sure you enable `DebuggerSupport` as well as `CopyOutputSymbolsToPublishDirectory` when you publish

Thank you for your guidance
Adding <DebuggerSupport>true</DebuggerSupport> resolved the issue.
