### ISSUE TITLE
[dotnet-watch] Detect that I'm in a solution folder

### ISSUE THREAD

**Issue by Tarmil** [dotnet/aspnetcore#4103]
When I run `dotnet watch` within a project folder, it detects this project and I don't have to type

    dotnet watch -p myproject.fsproj <command>

I can just do

    dotnet watch <command>

and that's great.

However, that doesn't work with solution files. For example given this structure:

    |- mysolution.sln
    |- webproject/
    |   |- webproject.fsproj
    |   |- ...source files...
    |- backendproject/
        |- backendproject.fsproj
        |- ...source files...

if I want to watch the whole solution and run `webproject`, it would be nice to be able to run

    dotnet watch run -p webproject

but right now I have to do

    dotnet watch -p mysolution.sln run -p webproject

**Comment by AnthonyMastrean** [comment]
In _some_ scenarios, passing the solution file to the `format` doesn't work correctly. I was setting up a VS Code custom task and it complained about the absolute path format:

**tasks.json**
```typescript
        {
            "label": "format",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "--project ${workspaceFolder}/Example.sln",
                "format",
            ],
            "isBackground": true,
            "problemMatcher": []
        }
```

**output**
```
> Executing task: C:\Program Files\dotnet\dotnet.exe watch --project C:\Users\anthony.mastrean\example/Example.sln format <


watch : Could not find a MSBuild project file in 'c:\Users\anthony\example'. Specify which project to use with the --project option.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

It also didn't like this relative path format:

**tasks.json**
```typescript
        {
            "label": "format",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "--project Example.sln",
                "format",
            ],
            "isBackground": true,
            "problemMatcher": []
        }
```

**output**
_(same error)_

It _only_ wanted the explicitly relative path format!

**tasks.json**
```typescript
        {
            "label": "format",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "--project ./Example.sln",
                "format",
            ],
            "isBackground": true,
            "problemMatcher": []
        }
```

All this to say... automatic solution discovery would be great!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While we thing this is a reasonable ask we don't plan to add this feature to the tool.
