### ISSUE TITLE
Blazor wasm: Cannot wait on monitors on this runtime, when calling odata in OnInitializedAsync

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#41046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting "Cannot wait on monitors on this runtime" error when trying to get odata inside `OnInitializedAsync`

### Steps To Reproduce

this is my page:
```
@page "/fetchdata"
@using BlazorApp1.Client.Model

@foreach(var person in people)
{
    <p>
        @person.FirstName @person.LastName
    </p>
}

@code {
    private IEnumerable<Person> people = new List<Person>();
    protected override async Task OnInitializedAsync()
    {       
        var serviceRoot = "https://services.odata.org/V4/TripPinServiceRW/";
        var cx = new ODataContext(new Uri(serviceRoot));

        people = await cx.People.ExecuteAsync();
    }
}
```
and my odata context:
```
public class ODataContext : DataServiceContext
{
    public ODataContext(Uri serviceRoot) : base(serviceRoot)
    {
        this.People = base.CreateQuery<Person>("People");
    }

    public DataServiceQuery<Person> People { get; }
}

// Person class with Odata annotations
[Key("Id")]
public class Person
{
    public string Id { get; set; }
    public string UserName { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

### .NET Version

6

**Comment by TanayParikh** [comment]
Hi @omuleanu, thanks for reaching out. Are you calling `Task.Result` anywhere? Mono & JS are single threaded. Blocking calls can cause this issue.

Related:
- https://github.com/dotnet/aspnetcore/issues/40096
- https://github.com/dotnet/aspnetcore/issues/26314

**Comment by omuleanu** [comment]
Hi @TanayParikh,
The code that I posted is basically the whole app,
I'm only calling `await` inside `OnInitializedAsync`, as you can see in the code above.
I would assume there's something that `DataServiceContext` does, that is not compatible with blazor wasm.

**Comment by javiercn** [comment]
I've moved the issue to the OData repo
