### ISSUE TITLE
PassThroughAuthorizationHandler does not respect AuthorizationOptions.InvokeHandlersAfterFailure

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#41043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If `AuthorizationOptions.InvokeHandlersAfterFailure` is set to false, it is expected that other handlers are short-circuited when `AuthorizationHandlerContext.HasFailed` is true.

Microsoft has given consumers the option that an `AuthorizationHandler` and `IAuthorizationRequirement` be defined in a single class and also skipping the part where consumers are required to register the handler in DI by utilizing [PassThroughAuthorizationHandler](https://source.dot.net/#Microsoft.AspNetCore.Authorization/PassThroughAuthorizationHandler.cs,411e6638c5e08359,references) as explained [here,](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0#handler-registration-1) but that class fails to respect the cases where a requirement that handles itself has responded with `AuthorizationHandlerContext.Fail()`, as it does not make any attempts or checks against `AuthorizationOptions.InvokeHandlersAfterFailure`, nor if the executed handler has failed.

### Expected Behavior

That `AuthorizationOptions.InvokeHandlersAfterFailure` is respected, i.e other handlers in `PassThroughAuthorizationHandler` will not be executed if  `AuthorizationOptions.InvokeHandlersAfterFailure` has been set to false and the handler that was just executed has failed.

### .NET Version

5

### Anything else?

If this is something that warrants a pull request with code changes, I'd love to contribute to it.

**Comment by adityamandaleeka** [comment]
@HaoK PTAL

**Comment by SpiritBob** [comment]
@HaoK thank you for fixing this! In the future, should I start with a draft pull request if I want to get involved in the process, as I really wanted to be? The only thing that was vague for me personally was how and where the unit tests would be done.

**Comment by HaoK** [comment]
Oh my bad, I didn't see that you offered to do a PR at the bottom of the issue, for something straightforward like this, you can always open a PR at the same time you file the issue.
