### ISSUE TITLE
Tag a new version of the SignalR C++ client project, push out to vcpkg

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#41045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The current port of the SignalR-Client-Cpp project is set to 0.1.0-alpha3#1. The alpha3 tag was released on Aug 6, 2021.  It would be nice to be able to use a later version of the signalr client via vcpkg.

### Describe the solution you'd like

Two things are needed:
* The signalr c++ project needs a new tag. 
* The vcpkg port needs to be updated to pick up the tag.

**Comment by BrennanConroy** [comment]
We are planning on doing this once we update some logs on shutdown. Should be in a week or so.

**Comment by BrennanConroy** [comment]
There is a new version now.
