### ISSUE TITLE
dotnet-watch for MSBuild does not restart process when new file is added

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4104]
**Repro:**
watch an MSBuild project that uses globs.
Add a new file that would match one of the globs.

**Expected**
dotnet-watch should restart process.

**Actual**
new file is ignored

**Remarks**
We should revisit the testing as the tests supposedly test this scenario and are passing, but this does not actually work.

**Comment by mkArtakMSFT** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/8321
