### ISSUE TITLE
Blazor project template - lower left nav can be inaccessible in short browser window

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#41050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The left navigation doesn't scroll when some of it is cut off by a short browser window. When more items are in the left navigation, the issue is more likely to be experienced.

### Expected Behavior

The left navigation should scroll when some of it is cut off by a short browser window

### Steps To Reproduce

1. Create and run a new Blazor Server project
2. Drag the bottom of the browser window up so that it covers some of the left navigation items
3. Notice that the navigation items that are cut off are no longer accessible

### .NET Version

6.0.3

**Comment by TanayParikh** [comment]
The default blazor server app is a basic sample, and fully customizable to meet user needs. It would have to be a (very?) small window if the vertical height doesn't even allow the 3 nav items along with the header. 

cc/ @danroth27 is this something we want to change?

**Comment by danroth27** [comment]
The user notes that if you add more items to the nav then you are more likely to hit this. But this doesn't seem critical to fix. I think we'd happily accept a community contribution for this.

**Comment by mrlife** [comment]
> The user notes that if you add more items to the nav then you are more likely to hit this. But this doesn't seem critical to fix. I think we'd happily accept a community contribution for this.

Thanks @danroth27, added the PR here: https://github.com/dotnet/aspnetcore/pull/41062.
