### ISSUE TITLE
Bitdefender Total Security detects a Trojan when viewing published Blazor WebAssembly as well as while publishing too

### ISSUE THREAD

**Issue by chintanbug** [dotnet/aspnetcore#41063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bitdefender Total Security detects a Trojan in the Microsoft.JSInterop.WebAssembly.dll of Blazor WebAssembly which is published in DEBUG/RELEASE.

_framework/Microsoft.JSInterop.WebAssembly.dll
Threat name: Trojan.GenericKD.39437478_

### .NET Version

6.0

**Comment by danroth27** [comment]
We've discussed this issue with Bitdefender and we believe the issue with their products is now resolved. Please let us know if though if you're still having issues!
