### ISSUE TITLE
dotnet-inspect

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4106]
A tool to inspect detailed information about the current setup. Here is a list of information that might be useful for support engineers, our team, and devs in general.

- optimized package cache. Available? In use? Cache misses? etc.
- Show graph of dependencies
  - what is lifting/downgrading specific package version
  - show sources of package conflicts
- list available shared runtimes (peek inside dotnet/sdk)
- List all resolved MSBuild properties, including implicit/inferred properties from Microsoft.NET.Sdk

It's like `dotnet --info` on steroids.

**Comment by BrennanConroy** [comment]
Issue https://github.com/dotnet/sdk/issues/7876 is tracking the possibility of adding this.
