### ISSUE TITLE
Blazor Http client doesn't timeout

### ISSUE THREAD

**Issue by sWozzAres** [dotnet/aspnetcore#41069]
Blazor WASM HttpClient doesn't seem to ever timeout. I have tried 5 methods and none of them have any effect.

Demo project at [BlazorApp1](https://github.com/sWozzAres/BlazorApp1)

Using a named client...

```
var timeoutPolicy = Policy.TimeoutAsync<HttpResponseMessage>(
    TimeSpan.FromSeconds(10));

builder.Services.AddHttpClient("ServerAPI",
    client =>
    {
        client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
        client.Timeout = TimeSpan.FromSeconds(5);
    })
    .ConfigureHttpClient(x =>
    {
        x.Timeout = TimeSpan.FromSeconds(5);

    })
    .AddPolicyHandler(httpRequestMessage =>
        timeoutPolicy);
    //.SetHandlerLifetime(TimeSpan.FromSeconds(5))

builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("ServerAPI"));
```
also
```
var client = HttpClientFactory.CreateClient("ServerAPI");
client.Timeout = TimeSpan.FromSeconds(5);
forecasts = await client.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast",
    cancellationToken: (new CancellationTokenSource(TimeSpan.FromSeconds(5)).Token));
```
then on the server, setting a delay of 10 seconds
```
[HttpGet]
public async Task<IEnumerable<WeatherForecast>> Get()
{
    await Task.Delay(10000);
    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateTime.Now.AddDays(index),
        TemperatureC = Random.Shared.Next(-20, 55),
        Summary = Summaries[Random.Shared.Next(Summaries.Length)]
    })
    .ToArray();
}
```
Interestingly, just setting this delay on the server to 5 seconds or more stops the client from ever receiving the data!

The HttpMessageHandler will expire after 120 seconds, but still no timeout is raised in the client.

```
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[103]
      HttpMessageHandler expired after 120000ms for client 'ServerAPI'
```
Am I missing something? It seems like it isn't possible to change the timeout duration and the blazor client will never be notified of any timeouts.

**Comment by sWozzAres** [comment]
It seems I can detect a timeout, but I have to install a continuation function and trap an AggregateException that holds a TaskCanceledException!

```
var client = Factory.CreateClient("ServerAPI");
client.Timeout = TimeSpan.FromSeconds(5);
try
{
    forecasts = await client.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast").ContinueWith(continuationFunction =>
    {
        Logger.LogInformation("ContinueWith executed: {IsCanceled} {IsCompleted} {IsCompletedSuccessfully}", continuationFunction.IsCanceled, continuationFunction.IsCompleted, continuationFunction.IsCompletedSuccessfully);
        return continuationFunction.Result;
    });
}
catch (System.AggregateException ex)
{
    ex.Handle((x) =>
    {
        if (x is TaskCanceledException) 
        {
            _message = "A timeout occurred!";
            StateHasChanged();
            return true;
        }
        return false; 
    });
}
```
So when the HttpClient timeout activates, it sends a cancellation token to the server and then generates an AggregateException. Surely there is a way for it to simply generate a HttpRequestException?

**Comment by javiercn** [comment]
@sWozzAres thanks for contacting us.

I'm not sure I can reproduce what you are experiencing. From what I can tell everything is working as expected. When you run that, I get to see the exception in the browser. The other part that I changed was the Thread.Sleep.

If you use Task.ContinueWith is expected that you see an AgregateException. `await` unwraps the inner exception (among other things) which you don't get if you are using `ContinueWith` directly.

```csharp
public async Task<IEnumerable<WeatherForecast>> Get()
{
    await Task.Delay(3000);
    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateTime.Now.AddDays(index),
        TemperatureC = Random.Shared.Next(-20, 55),
        Summary = Summaries[Random.Shared.Next(Summaries.Length)]
    })
    .ToArray();
}
```

Some sample code here:
```csharp
    protected override async Task OnInitializedAsync()
    {
        try
        {
            var client = Factory.CreateClient("ServerAPI");
            client.Timeout = TimeSpan.FromSeconds(1);
            forecasts = await client.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
```

**Comment by sWozzAres** [comment]
When a timeout occurs, nothing appears in the log and Blazor doesn't pick it up. This leaves you thinking that no timeout has happened. You just see the Http client send the message and then nothing.

Having to trap a TaskCanceledException is non-intuitive but it seems that this has been discussed at length before. Unless I missed it in the hours I searched the documentation, perhaps it would be helpful to add a section on handling timeouts in Blazor.
