### ISSUE TITLE
Add header `Request-Context` to class Microsoft.Net.Http.Headers.HeaderNames

### ISSUE THREAD

**Issue by kevinharing** [dotnet/aspnetcore#41084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's used by Application Insights.

### Describe the solution you'd like

Add header `Request-Context` to class Microsoft.Net.Http.Headers.HeaderNames

### Additional context

It's missing currently

**Comment by blowdart** [comment]
Ah sorry @MihaZupan 

@[evinharing you could ask AppInsights if they wanted to add an extension method to Microsoft.Net.Http.Headers.HeaderNames, that way if you were importing AppInsights you'd get it.

**Comment by halter73** [comment]
> The header you requested is a non-standard header only used by app insights. As the Microsoft.Net.Http.Headers.HeaderNames class is for "well-know headers", i.e. the ones defined in RFCs it doesn't really meet the bar for inclusion.

Triage: Agreed with the above. We like the idea of an extension method for HeaderNames, but it wouldn't work today on a static class. We could consider an extension point like `Microsoft.AspNetCore.HttpResults.Extensions`, but I doubt we'd do it.
