### ISSUE TITLE
There is no file with ID 1. The file list may have changed

### ISSUE THREAD

**Issue by MuscleBy** [dotnet/aspnetcore#41085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a ASP.NET Core WebAssembly project and I want to upload some files on azure using `<InputFile>` component. When I'm trying to upload the files all at once everything works fine. If I upload the files one by one I receive an exception:  

> There is no file with ID 1. The file list may have changed.

The issue is also described here: [https://github.com/SteveSandersonMS/BlazorInputFile/issues/36](url)

I created a project that you can download where the issue is reproduced:

[https://github.com/MuscleBy/BlazorFilesUploadBUG](url)

I'm using the latest version of Visual Studio: 17.1.3 and .NET CORE 6.

### Expected Behavior

Files can be uploaded one by one.

### Steps To Reproduce

1. Downlod the repo at this link: [https://github.com/MuscleBy/BlazorFilesUploadBUG](url)
2. There are 2 files used to reproduce this issue in this solution. `Index.razor` on client and `BlobController.cs` on Server. On  BlobController.cs there are 2 properties: `StorageAccountName `and `AccessKey `where you can add your credentials in order to receive a SAS link used to upload the files to a blob storage if you want.
3. Run the solution and try to upload two ore more files at once. It works fine. If you try to upload them each one by one you will receive the exception at line 112 in `Index.razor` on await `cloudBlockBlob.UploadAsync(file);` There is a debugger added on line 115 which will catch the exception.

### Exceptions (if any)

'There is no file with ID 1. The file list may have changed.\nError: There is no file with ID 1. The file list may have changed.\n    at Be (https://localhost:7113/_framework/blazor.webassembly.js:1:31526)\n    at Object.readFileData (https://localhost:7113/_framework/blazor.webassembly.js:1:31452)\n    at https://localhost:7113/_framework/blazor.webassembly.js:1:3332\n    at new Promise (<anonymous>)\n    at Object.beginInvokeJSFromDotNet (https://localhost:7113/_framework/blazor.webassembly.js:1:3306)\n    at Object.Rt [as invokeJSFromDotNet] (https://localhost:7113/_framework/blazor.webassembly.js:1:59738)\n    at _mono_wasm_invoke_js_blazor (https://localhost:7113/_framework/dotnet.6.0.3.ni6r0hhy5a.js:1:194973)\n    at wasm://wasm/00970a1e:wasm-function[219]:0x1a0fa\n    at wasm://wasm/00970a1e:wasm-function[167]:0xcac8\n    at wasm://wasm/00970a1e:wasm-function[166]:0xb9db'

### .NET Version

6.0

### Anything else?

A fix or a workaround would be nice.

**Comment by MuscleBy** [comment]
Yeah, it seems like what you described is also my scenario. But I still don't understand why the exception is raised when I want to upload the files to azure, and not in any other case. Anyway, I attached the solution, if you want to take a look.
[BlazorFilesUploadBUG.zip](https://github.com/dotnet/aspnetcore/files/8443790/BlazorFilesUploadBUG.zip)

**Comment by MuscleBy** [comment]
What I did in my solution is to add the files in a list of files and upload them  later on when the user clicks the submit button but still, I have the same isssue, as you described in #40574 it does not seems to bu cumulative. Any way I will probably just add a new component for each file to be uploaded, this way I think I should overcome the issue.

**Comment by TanayParikh** [comment]
> But I still don't understand why the exception is raised when I want to upload the files to azure, and not in any other case

Without getting too deep into your particular implementation details, I suspect this may be the point where you actually try to _read_ the stream, and thus that's where the exception is thrown.

> What I did in my solution is to add the files in a list of files and upload them later on when the user clicks the submit button but still, I have the same isssue, as you described in https://github.com/dotnet/aspnetcore/issues/40574 it does not seems to bu cumulative.

Yep, that won't work unless you actually cache the file data (which has its own security ramifications as you're storing arbitrary user data on disk/memory).

> Any way I will probably just add a new component for each file to be uploaded, this way I think I should overcome the issue.

👍
