### ISSUE TITLE
ASP.NET Core IIS hosting failure (In-Process) if a file called "dotnet" is present in the project root.

### ISSUE THREAD

**Issue by AlexKeene** [dotnet/aspnetcore#41089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Same as https://github.com/dotnet/aspnetcore/issues/17393 presumably.

Creating a file named "dotnet" in the project root directory an ASP.Net Core (net6.0) project causes the application to fail to start & an error page to appear:

> HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process) 

Two application error events are logged:

>Application 'C:\Users\alexk\source\repos\Junk\Test\Test\' failed to start. Exception message: Unable to find hostfxr directory at C:\Users\alexk\source\repos\Junk\Test\Test\host\fxr 
>   Process Id: 18928. 
>   File Version: 16.0.21322.1. Description: IIS ASP.NET Core Module V2. Commit: 4e7d976438b0fc17f435804e801d5d68d193ec33 

>Failed to start application '/LM/W3SVC/2/ROOT', ErrorCode '0x8007023e'. 
>   Process Id: 18928. 
>   File Version: 16.0.21322.1. Description: IIS ASP.NET Core Module V2. Commit: 4e7d976438b0fc17f435804e801d5d68d193ec33 

Deleting the file restores functionality.

### .NET Version

6.0.201

**Comment by Tratcher** [comment]
While we've addressed some common issues here, the core feature that checks for dotnet is used to find the runtime. Renaming the file should avoid this.
