### ISSUE TITLE
Support running arbitrary command from dotnet-watch

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4108]
At the moment "dotnet" is implied. We should provide a way to suppress that.

One idea:
```
dotnet watch -x|--exec [[--] [<ARGS...>]]

Example:
dotnet watch -x ./build.sh
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future.

**Comment by atifaziz** [comment]
> This is not something we plan to do in the near future.

Care to explain why not?

**Comment by mkArtakMSFT** [comment]
> 
> 
> > This is not something we plan to do in the near future.
> 
> Care to explain why not?

@atifaziz we're not a big team and we choose to work on things which will add value to the community. For this particular issue, we haven't heard much community feedback/request hence we've decided we won't do this.

**Comment by atifaziz** [comment]
@mkArtakMSFT I can understand that and thanks for the frank explanation, but then why not leave it open as an “up for grabs”? It doesn't seem like running arbitrary commands from dotnet-watch sounds outrageous or something that would be a misfit of a feature.

**Comment by mkArtakMSFT** [comment]
Well, this particular issue has been around for more than two years now, and nobody from the community was interested in submitting a PR.

**Comment by atifaziz** [comment]
@mkArtakMSFT Fair enough.
