### ISSUE TITLE
Write old code with .net 6

### ISSUE THREAD

**Issue by amin1best** [dotnet/aspnetcore#41096]
Hi, I have an old code in asp.net webforms:
```cs
ClientWS ccws
{
    get
    {
        if (Session["ccws_ws"] == null)
        {
            ClientWS _ccws = new ClientWS();
            _ccws.CookieContainer = new CookieContainer();
            int r = _ccws.Login("user", "pass", _ccws.GetRandomNumber())
            Session["ccws_ws"] = _ccws;
            _ccws.Timeout = 400000;
        }
        return (ClientWS)Session["ccws_ws"];
    }
    set
    {
        Session["ccws_ws"] = value;
    }
}
```
I want to write this code with .net 6. I wrote the following code: 
```cs
using ServiceReference;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

ClientWSSoapClient _ccws = new ClientWSSoapClient(ClientWSSoapClient.EndpointConfiguration.ClientWSSoap);
int r = _ccws.Login("user", "pass", _ccws.GetRandomNumber());

app.MapGet("/", () => r);
app.Run();
```
But it does not work.
I used this:
dotnet-svcutil --sync http://*.asmx
and dotnet-svcutil.params.json:
```json
{
  "providerId": "Microsoft.Tools.ServiceModel.Svcutil",
  "version": "2.0.3",
  "options": {
    "inputs": [
      "http://*.asmx"
    ],
    "namespaceMappings": [
      "*, ServiceReference"
    ],
    "outputFile": "Reference.cs",
    "sync": true,
    "targetFramework": "net6.0",
    "typeReuseMode": "All"
  }
}
```

I have three problems:
1. How can I use **Session["ccws_ws"] = _ccws** like old code in .net 6 ? 
2. _ccws does not have a property called **CookieContainer**?
3. _ccws does not have a property called **Timeout**?

The service provider has said that these are mandatory. If anyone can help, thank you for suggesting a complete code.

**Comment by Tratcher** [comment]
This looks like a usage question rather than a product issue. Such questions are better directed to forums like [Stackoverflow.com](Stackoverflow.com).
