### ISSUE TITLE
Results<T1, TN> union types should implement IEndpointMetadataProvider

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#41097]
The new `Results<TResult1, TResultN>` union types should implement the also new `IEndpointMetadataProvider`. As the union type is essentially just a wrapper for the concrete `IResult` types used as its type args, it would just delegate the call to `IEndpointMetadataProvider.Populate()` on to `TResultN` types that implement `IEndpointMetadataProvider`.

``` c#
public class Results<TResult1, TResult2> : IResult, IEndpointMetadataProvider
{
    // Existing members...
    
    static void IEndpointMetadataProvider.PopulateMetadata(EndpointMetadataContext context)
    {
        // Call through to TResult1.PopulateMetadata() if TResult1 implements IEndpointMetadataProvider
        // Call through to TResult2.PopulateMetadata() if TResult2 implements IEndpointMetadataProvider
    }
}
```

**Comment by halter73** [comment]
API review:

This is filling a gap. Approved.
