### ISSUE TITLE
dotnet D:/d1/d2/...xx/web1.dll  will cause Confusing webroot-path if the command-path is different with web1.dll real path

### ISSUE THREAD

**Issue by yangbocheng** [dotnet/aspnetcore#41103]
## Summary

When use dotnet D:/d1/d2/...xx/web1.dll and the CD comand-base-path is different with web1.dll-real-path.  then the web will start port 5000 and ignore the real appsettings.json and wwwroot. 

## Motivation and goals
When i use  dotnet D:/d1/d2/...xx/web1.dll, the web allways get 404 for those resources like xx/js/site.js , xx/css/site.css.
So i have to always CD to  the web1.dll's path , and then try dotnet web.dll, then the web run well. 

I guess it's the problem of contentpath.  So why not use the dll's assembly path as the contentpath when in commandline by default ?.
It's really confusing

**Comment by davidfowl** [comment]
The content root defaults to cwd because in development we don’t want to have to copy files to the output folder to see static file changes. You can easily set the content root via an env variable or command line argument to change this.

**Comment by yangbocheng** [comment]
thanks~, I understand this is designed to facilitate the use of the dotnet run command.? However, maybe that instructions such as dotnet /xx/x/web.dll are usually used to start the real program. At this time, it will reduce the configuration(like set env variable or command argument) and reduce that start-up errors if the contentroot path is set to the assembly path

**Comment by davidfowl** [comment]
That's not a change we're going to make (and it's a major breaking change) but you can change it for your application.

**Comment by yangbocheng** [comment]
That's all right for me. But it's better to give some tips in dotnet docs to avoid this usage,
I'm guessing that many people have tried the usage of dotnet /x/x/web.dll, they may find the same error, or the css.file miss, or the appsettings.json file seems to be invalid after a lot of time

**Comment by halter73** [comment]
@davidfowl @yangbocheng What docs should be updated and what should they say?
