### ISSUE TITLE
SPA  Hot Reload

### ISSUE THREAD

**Issue by maikebing** [dotnet/aspnetcore#41105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync starts an npm at each debug and shuts down when it stops debugging, which causes the front end to start for a very long time and the front end cannot be hot reloaded. 

### Describe the solution you'd like

The npm process is not shut down

**Comment by javiercn** [comment]
@maikebing thanks for contacting us.

We've changed the approach we use with the SPA templates on 6.0 and we directly leverage the SPA proxy in front of the .NET backend. Our recommendation is that you switch to that approach that doesn't involve `Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync` and that allows you to use hot reload both on the server and the client.

**Comment by maikebing** [comment]
Thank you, my problem was solved.
