### ISSUE TITLE
When doing hot reload, if it must rebuild, add an option to have it start on the page it was last.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41111]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-doing-hot-reload-if-it-must-rebuil/1688020)._

---
This would speed up development of pages by not having you navigate back to where you were previously. Using Blazor Server.

---
#### Feedback Bot on 3/10/2022, 03:26 AM: 

(private comment, text removed)

**Comment by jmaillet** [comment]
I often drop to the command line and manually run `dotnet watch run` so that the browser doesn't close when restarting is necessary.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
