### ISSUE TITLE
Hot Reload still not working in VS2022 v17.2 in aspnet core web app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41112]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hot-Reload-still-not-working-in-VS2022-v/1670852)._

---
Hot reload is not working in this scenario in VS 2022 v17.2 :

aspnet core web app - css updates do not trigger an update.
aspnet core web app - html updates do not trigger an update.
aspnet core web app - forced manual start button on hot reload menu button no longer enabled.
aspnet core web app - clicking hot reload button has not effect.
aspnet core web app - output window no longer showing hot reload option in output drop down.

---
#### Feedback Bot on 2/21/2022, 06:47 AM: 

(private comment, text removed)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
