### ISSUE TITLE
Template 'ASP.NET Core Web App' adds unnecessary usings to Startup.cs

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#41114]
Impact: 
New users can be overwhelmed by having extra information.

Steps to reproduce:

1. Open VS 2022
2. Create a ASP.NET Core Web App
3. Open Startup.cs

Unnecessary usings:
Microsoft.AspNetCore.HttpsPolicy;
System;
System.Collections.Generic;
System.Linq;
System.Threading.Tasks;

![image](https://user-images.githubusercontent.com/14852843/162507753-49ae4789-394e-4715-87dd-70aee2dcaaf6.png)

https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1422801

**Comment by javiercn** [comment]
@TanayParikh that's a good catch.

I'm surprised to see those there. @DamianEdwards do you know about this?

Also @TanayParikh what version are you using? That seems to be 5.0 or 3.1 based on the fact that there is a startup class. Not sure if we care a lot about 3.1 and 5.0 templates at this point.

**Comment by TanayParikh** [comment]
This was a user reported issue (https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1422801), I just copied over the contents so we can better track it via GitHub (transfer via Migration bot wasn't an option). The user did not specify the version they're using, and we do not have any logs to determine that directly. I've reached out to the user and will reply back here should we get more info.
