### ISSUE TITLE
After changing some code in Counter.razor, then click "Hot Reload" button, the Counter button on the home page will disappear.

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#41110]
REPRO STEPS

1. File > New project > Blazor Server App > .NET 7.0 (Preview)  > Create.
2. Build and run the project.
3. Add <Counter /> to Index.razor and click Hot Reload button.
4. Open Counter.razor, update the method IncrementCount(): change "currentCount++;" to "currentCount+=5;".
5. Click "Hot Reload" button, the Counter on the home page will disappear.

ACTUAL:
![52d78d49-8a30-4532-948b-11ffdd0cfca8](https://user-images.githubusercontent.com/14852843/162502689-f7267c1b-8487-4463-88ff-6b2b28b4010b.gif)

Expected:
![image](https://user-images.githubusercontent.com/14852843/162502607-ba659e34-539e-427c-a320-86f3a3074d94.png)

Internal issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1477458

**Comment by mkArtakMSFT** [comment]
@TanayParikh if this is still an issue, it will need to be handed over to @tmat !

**Comment by danroth27** [comment]
I'm unable to reproduce this with .NET 7 RC1.

**Comment by TanayParikh** [comment]
Thanks Dan, closing as fixed in that case.
