### ISSUE TITLE
Dontnet core 3.1 --->6.0 both the cases Error: rzc generate exited with code -2147450730

### ISSUE THREAD

**Issue by janakiramangara** [dotnet/aspnetcore#41122]
Severity	Code	Description	Project	File	Line	Suppression State
Error		rzc generate exited with code -2147450730.	WebApplication3	C:\Program Files\dotnet\sdk\6.0.103\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.CodeGeneration.targets	150	

Unable to build any MVC project in VS2019, VS2022 also. OS: Win11.

**Comment by TanayParikh** [comment]
Unfortunately we don't think we have enough information to help. Could you report this through the visual studio report a problem dialog? (Details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio))

That will capture more information about the environment and will help in the troubleshooting process.

In the meantime you can also try cleaning the project / deleting the `bin` and `obj` folders and retrying the build.
