### ISSUE TITLE
Allow property navigation for `ChildComponent` rendering when using `CascadingTypeParameter`

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#41120]
### Is your feature request related to a problem? Please describe the problem.

I am trying to simplify my `Table` component design for the consumer of my library. Currently it is implemented as follows:

### Table.razor
```razor
@using Microsoft.AspNetCore.Components.Web.Virtualization

@typeparam TItem
@attribute [CascadingTypeParameter(nameof(TItem))]

<CascadingValue IsFixed="true" Value="this">@ChildContent</CascadingValue>

<div class="table-container column">
    <Virtualize Items="Items" Context="item">
        @foreach (var column in columns)
        {
            @column.GetValue(item)
        }
    </Virtualize>
</div>

@code {
    private List<TableColumn<TItem>> columns = new();

    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    [Parameter]
    public ICollection<TItem>? Items { get; set; }

    internal void AddTableColumn(TableColumn<TItem> column)
    {
	columns.Add(column);
    }
}
```

### TableColumn.cs
```csharp
public partial class TableColumn<TItem> : ComponentBase
{
    private Func<TItem, object>? compiledExpression;

    [CascadingParameter]
    public Table<TItem>? Table { get; set; }

    [Parameter]
    public Expression<Func<TItem, object>?>? Expression { get; set; }

    protected override void OnInitialized()
    {
	Table?.AddTableColumn(this);
	base.OnInitialized();
    }

    internal object? GetCellValue(TItem item)
    {
	ArgumentNullException.ThrowIfNull(compiledExpression);
	return compiledExpression(item);
    }
}
```

### Usage
```razor
<Table Items="group?.Blocks">
    <TableColumn Expression="block => block.Name" />
    <TableColumn Expression="block => block.Id" />
    <TableColumn Expression="block => block.Group" />
</Table>
```

### Describe the solution you'd like

I'd like for the end user to be able to define the table as follows:

```razor
<Table Items="group?.Blocks" Context="block">
    <TableColumn>@block.Name</TableColumn>
    <TableColumn>@block.Id</TableColumn>
    <TableColumn>@block.Group</TableColumn>
</Table>
```

I've tried a few things, but the way `RenderFragment` seems to be implemented now doesn't allow this to work.

### Additional context

I've been looking around for topics on this issue and found https://github.com/dotnet/aspnetcore/issues/29379 which is related but I don't think addresses this specificly.

**Comment by javiercn** [comment]
@BrunoBlanes thanks for contacting us.

You can already do this by passing a RenderFragment<T> instead of a RenderFragment. It's not clear that we are missing anything here.

Your child content in Table.razor as well as in TableColum.razor need to be `RenderFragment<T>`, but afterwards, it should work.

**Comment by BrunoBlanes** [comment]
Thanks, with your help and the help of [this article](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-6.0) I got it working. I'm gonna go dig myself a hole to cry on in fetal position for all the hours I spent on trial and error now...

**Comment by BrunoBlanes** [comment]
Quick question, is it possible to know when `@ChildContent(T)` will return `string.Empty` or `null`?
