### ISSUE TITLE
Small grammar mistake in ./wiki/Engineering-guidelines#coding-guidelines

### ISSUE THREAD

**Issue by icnocop** [dotnet/aspnetcore#41121]
Hi.

I noticed a small grammar mistake in https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#coding-guidelines

> One common exception to this is that the namespace for middleware extension methods is normally always the same is the namespace of `IAppBuilder`.

Should read:

> One common exception to this is that the namespace for middleware extension methods **are** normally always the same **as** the namespace of `IAppBuilder`.

Thank you.

**Comment by TanayParikh** [comment]
Thanks, updated!
