### ISSUE TITLE
Blazor Server RuntimeCompilation like in Razor pages

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#41126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm using a Blazor component as a template for a page. I'm using Razor pages and Blazor Server on the same project. This .razor file only has HTML and 2 or 3 Blazor components in it. Everything works fine except that if this .razor file is changed using a simple editor just to tweak the HTML, we can't see those updates reflect on the website without having to recompile the whole thing! 

### Describe the solution you'd like

Razor pages .cshtml files update fine after adding the not included by default feature `.AddRazorRuntimeCompilation()` to our program.cs but it does not work for Blazor files. Is this a limitation when using Blazor Server? How can use templates in websites and having designers update them without the development team compile the entire source each time we need to add a simple `<p>Hello world</p>` html code or change a style on an html element??

Can you please provide some feedback on this and if there's any solution other than quit using Blazor?

Thank you in advance

**Comment by javiercn** [comment]
@HybridSolutions thanks for contacting us.

There is already a feature for it called Hot Reload in .NET 6.0. We don't have plans to implement the equivalent of Runtime compilation for Razor Components as they work in a very different way compared to razor pages.

The way to see changes in Blazor Server applications while the app is running is to do so using Hot Reload.

**Comment by HybridSolutions** [comment]
> @HybridSolutions thanks for contacting us.
> 
> There is already a feature for it called Hot Reload in .NET 6.0. We don't have plans to implement the equivalent of Runtime compilation for Razor Components as they work in a very different way compared to razor pages.
> 
> The way to see changes in Blazor Server applications while the app is running is to do so using Hot Reload.

Hot reload dies not work in production server. It's only valid while you are developing. How do you have a designer update a minor html piece of a already deployed website without having to ask a developer to recompile the whole thing?!

It's a real problem and I'm not the only one complaining about this.

This also prevents the usage of templates because you can't tweak the html or even change an in-line style of a button.

If Hot reload works while developing, why can't it work on the server? If a change is detected, recompile and show updated version.

**Comment by davidfowl** [comment]
There's a directional change here that has been made intentionally that moves away from runtime compilation and back to compilation at build time. That's the journey ASP.NET Core has taken and it simplifies pretty much everything about the application and improves performance.

The runtime compilation has been slowly moved out of the mainline scenario (and is now completely external package in .NET 6) that can be added back for razor pages scenarios. The Blazor compilation model was created *after* we moved razor to ASP.NET Core and we have no plans to on bringing dynamic compilation to it.

Expect us to move further and further away from scenarios like this in production and this feature coming from extensibility that can be added on top of the existing framework instead.
