### ISSUE TITLE
Allow knowing before render if `RenderFragment<T>` will return null or empty

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#41138]
### Is your feature request related to a problem? Please describe the problem.

I am trying to set a placeholder value for when the component's `Value` parameter is `default(TItem)`, `new()` or `null`.

I've tried the following but it does not catch `new()`:
```razor
@if (Value is null || EqualityComparer<TItem>.Default.Equals(Value, default))
{
	<p class="placeholder">@Placeholder</p>
}

else
{
	<p>@ChildContent(Value)</p>
}
```

### Describe the solution you'd like

I'd like to be able to check if `@ChildContent(Value)` will return an empty value or not, maybe through some new method like:

```cs
if (ChildContent(Value).IsNullOrEmpty())
```

**Comment by BrunoBlanes** [comment]
So how can you check if the templated property is null since you don't have access to it from within the container? You can check if `Value` is null, but not `Value`'s property, which is what we are displaying here.

**Comment by javiercn** [comment]
@BrunoBlanes I'm missing something.

`@ChildContent` is a `RenderFragment<T>`. It doesn't return anything. It calls methods on a `RenderTreeBuilder`. It's not clear to me what you mean by `new()` as in a just created object? There's nothing in C# that will tell you that.

**Comment by BrunoBlanes** [comment]
I'm sorry, I might not have provided enough information. I am trying to display a placeholder value for when the bind property is equal to `null`, `default` or `new()`. Take a look at the following example:
```razor
<Dropdown Items="dogColours" Context="colour" @bind-Value="newDogColour" Placeholder="Select a color">@colour.ColourName</Dropdown>

@code {
    private IList<DogColour>? dogColours;
    private DogColour>? newDogColour = new();
}
```

And the model looks like:
```csharp
public record class Dog
{
    public string Name { get; set; }
    public DogColour? Colour { get; set; }

    public Dog()
    {
        Name = string.Empty;
    }
}

public record class DogColour
{
    public string? ColourName { get; set; }
    public int Red { get; set; }
    public int Green { get; set; }
    public int Blue { get; set; }
}
```

In this example, I have initialized `newDogColour`, but `ColourName` is `null` and I am using the `ColourName` property of the model to display the dropdown list, and since I am value binding to the variable `newDogColour`, `Dropdown.Value` will not be `null`, however since `ColourName` is, the Dropdown will just display an empty string.

The issue here is, I need to check if the templated property is `null` so I can display the `Placeholder` instead of the binding `Value`, which is `null`.

**Comment by BrunoBlanes** [comment]
@javiercn I'm sorry to ping you, but is this even remotely possible? Did the example above clarify what I am trying to achieve?

Right now what I had to do was add an extra parameter `PropertyName` so then I can use reflection to check the value. Somehow I think this could be optimized.

**Comment by javiercn** [comment]
@BrunoBlanes There's no way you can detect if an object was just initialized, if that's what you mean. You can check for default (which is equal to null in the case of reference types) but you can't check for `new()` if that means (as I interpreted it) that the object/struct was just initialized.

**Comment by BrunoBlanes** [comment]
> You can check for default (which is equal to null in the case of reference types) but you can't check for `new()` if that means (as I interpreted it) that the object/struct was just initialized.

Yes, I my point is that I need to check if the object's property is `null` and not the object itself. I currently can't do that with `RenderFragment<T>`.
