### ISSUE TITLE
Add the code in Counter.razor, press Ctrl + F5 then delete this code, error "ENC0033 Deleting auto-property 'IncrementAmount' requires restarting the application" pop up

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/aspnetcore#41133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

INSTALL STEPS
1. Clean machine: Win10 x64 ENU 20H1 (2004) 
2. Install Dev17.2 Preview 3 [[main-32330.462](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5961044&view=ms.vss-build-web.run-extensions-tab)] VSP
Select Web + Azure workload 
Check .NET Core 5.0/3.1/2.1 runtime under IC tab

TESTCASES AFFECTED
[6.0] Hot Reload rude edits in Blazor Server app 

Platform

 

- [X] Windows
- [ ] macOS
- [ ]  Linux

### Expected Behavior

No error in Error List

### Steps To Reproduce

REPRO STEPS
1.File > New > Project > Blazor Server App > Framework: .NET 6.0 > Authentication type: None > Create.
2.Add code "[Parameter] public int IncrementAmount { get; set; } = 1;" in line 13 in Counter.razor and save.
3.Press Ctrl + F5 to run the project.
4.Delete code "[Parameter] public int IncrementAmount { get; set; } = 1;"

### Anything else?

.NET Core SDK (CLI) Version: 6.0.300-preview.22178.8
Latest .NET Core runtime Version: 6.0.3

**Comment by mkArtakMSFT** [comment]
Talked to @tmat. This is a existing limitation which is going to be addressed by https://github.com/dotnet/roslyn/issues/59264
