### ISSUE TITLE
Multiple Authentication Schemes Validation chain behavior

### ISSUE THREAD

**Issue by Marusyk** [dotnet/aspnetcore#41130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have multiple custom Authentication Schemes like BasicAuth and ApiKey. 
For BasicAuth and ApiKey there are AuthenticationHandlers
```
public class BasicAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
public class ApiKeyAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
```
I need to allow access to any of the schema. So there is the action:
```
[Authorize(AuthenticationSchemes = "ApiKey")]
[Authorize(AuthenticationSchemes = "BasicAuthentication")]
public async Task<IActionResult> Get(CancellationToken token)
```

- When I use Basic credentials in the `Authorization` attribute - it fails validation in the first schema ApiKeyAuthenticationHandler, then BasicAuthenticationHandler will start and validate
- When I use an API key in the `X-API-KEY` attribute - `ApiKeyAuthenticationHandler` returns `AuthenticateResult.Success` but then the other schemes start running (BasicAuthentication) - it of course returns `AuthenticateResult.Fail` after that I can reach the action and it will return 200 Ok. 

So, when the first schema returns `AuthenticateResult.Success` - others will start (they can (and they will) return `AuthenticateResult.Fail` but it will be ignored)

### Expected Behavior

- when the first schema returns `AuthenticateResult.Fail` - others will start
- when the first schema returns `AuthenticateResult.Success` - others will not start

Then I can use multiple authentication schemes for my actions.

### Steps To Reproduce

Please see: https://github.com/Marusyk/IssuesReproducing/tree/main/MultipleAuthenticationSchemes
Make the request: `GET https://localhost:7245/WeatherForecast` with header `X-API-KEY` value `KEY` - both AuthenticationHandlers will work

### .NET Version

6.0.201

**Comment by davidfowl** [comment]
This is by design. See https://github.com/dotnet/aspnetcore/issues/40820 for an example of how or chain auth schemes.

**Comment by Marusyk** [comment]
Thanks, however, there is not enough information about the behavior. I didn't find the answer to why this is by design.

**Comment by Marusyk** [comment]
But the problem was not solved

**Comment by davidfowl** [comment]
cc @HaoK

**Comment by HaoK** [comment]
@Marusyk you need to pick between the schemes based on the presence of the header, as API key as opposed to challenging both, you do this via ForwardDefaultSelector, something like 

```
    .AddAuthentication("ApiKey")
    .AddScheme<AuthenticationSchemeOptions, BasicAuthenticationHandler>("BasicAuthentication", options => { })
    .AddScheme<AuthenticationSchemeOptions, ApiKeyAuthenticationHandler>("ApiKey", options => {
       options.ForwardDefaultSelector = context => context.Request.Headers.ContainsKey("X-API-KEY") ?
         "ApiKey" :
         "BasicAuthentication"
      });
```

Which will pick ApiKey if the header exists, otherwise it will try basic auth.  Resolving this as dupe of the other issue which tracks adding this to the docs as an example

**Comment by Marusyk** [comment]
What if I have 2 different providers of Bearer tokens?
There is one Bearer token from Azure B2C and another Bearer token from the custom Identity Server. 
Both of them come in the Authorization header and with Bearer schema. 
Could you please advise how to handle this case?

**Comment by davidfowl** [comment]
How would you write logic to handle this case?

**Comment by davidfowl** [comment]
We should clarify how the auth system works so you can reason about the behavior you are seeing. 

When you put multiple auth attributes on an endpoint, you're asking the system to build a single policy that runs all of the authentication handlers with the specified schemes. It runs each of the handlers specified, in the above example, it'll call into your `HandleAuthenticateAsync` on both `Custom1AuthenticationHandler` and `Custom2AuthenticationHandler`, get the results and merge them into a single ClaimsPrincipal with multiple identities (that's what you asked it to do).

It's unclear to me why that's a problem in your case, and if it is a problem, there's nothing built in that will fix it without you writing code and telling the system to do them "in order" and only take the first successful authentication handler. That feature doesn't exist.

**Comment by HaoK** [comment]
Right, you would have to write basically a composite bearer handler, and register that as your Bearer auth that is responsible for attempting to validate the bearer tokens.  The implementation of this CompositeAuthHandler's Authenticate would just be to call Authenticate against "Custom1" first, and return that if it succeeds, otherwise return the result of "Custom2" authenticate.

**Comment by Marusyk** [comment]
Thank you all

> It's unclear to me why that's a problem in your case, and if it is a problem, there's nothing built in that will fix it without you writing code and telling the system to do them "in order" and only take the first successful authentication handler. That feature doesn't exist.

because there is one more case, in some handlers I need to go to a database (to get the API KEY for example) and it will make useless calls to DB in second-third-... handler in case of success in the first 🙃
