### ISSUE TITLE
SignalR: AllowAnonymous and Authorize don't play well together under Windows authentication

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/aspnetcore#41139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to authenticate users in SignalR, **but allow anonymous users too**. So I added both `[Authorize]` and `[AllowAnonymous]` attributes like this StackOverflow answer suggests: https://stackoverflow.com/questions/63844687/signalr-hub-authenticate-users-but-allow-anonymous-users-too

```
[Authorize]
[AllowAnonymous]
public class ChatHub : Hub
{
}
```

This works perfectly for Cookies-based authentication. When users are authenticated (have the auth-cookie) - `Context.User.Identity.IsAuthenticated` is `true` and I can get their usernames. Anonymous users have `Context.User.Identity.IsAuthenticated` set to `false` and that's OK.

But this does not work with Windows-integrated authentication - the `Context.User.Identity.IsAuthenticated` is always false. This is understandable, b/c AllowAnonymous prevents sending the 401 challenge to the browser. But if I remove the `AllowAnonymous` - then anonymous users are disallowed compeltely. So how do we achieve the desired behaviour under Windows-integrated authentication then? I need users to authenticate via built-in windows credentials. But I also need anonymous users too.

Currently it's either *everyone is anonymous* or *everyone is required to authenticate, if not - a password prompt is shown*

Marking particular hub-methods with `AllowAnonymous` also does not work, the browser shows password prompt during hte negotiate phase

### Expected Behavior

`Context.User.Identity.IsAuthenticated` should be true for windows-authenticated users, false for anonymous users.

### Steps To Reproduce

Add windows auth to the app

```
services.AddAuthentication(IISDefaults.AuthenticationScheme);
```

Then build a hub

```
[Authorize]
[AllowAnonymous]
public class ChatHub : Hub
{
}
```

All users are anonymous in the hub.

Works perfectly fine if we change to forms authentication

```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
```

### .NET Version

6.0

**Comment by JamesNK** [comment]
This is a complex scenario. Mixing auth like this with Windows authentication is difficult.

A workaround is to have one hub and map it twice to create endpoints. One mapping has `RequireAuthorization`, and the other doesn't have any auth required. This can be used for anonymous access.
