### ISSUE TITLE
dotnet publish --no-build on ubuntu fails with error: Manifest file at '/someFolder/staticwebassets.build.json' not found.

### ISSUE THREAD

**Issue by yepeekai** [dotnet/aspnetcore#41149]
I am trying to optimize the build on azure devops.  I build all projects in a previous task with dotnet build --configuration release.
I force the use of dotnet 6.0.x which is 6.0.201 at the moment.

I then execute the following command:
/opt/hostedtoolcache/dotnet/dotnet publish /home/vsts/work/1/s/mywebproject /mywebproject .csproj --configuration release --output /home/vsts/work/1/a/mywebproject --no-build

It throws the error: /opt/hostedtoolcache/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(681,7): error : Manifest file at '/home/vsts/work/1/s/mywebproject /obj/release/net6.0/staticwebassets.build.json' not found. [/home/vsts/work/1/s/mywebproject /mywebproject .csproj]

On my windows machine, I started with a clean repository and executed exactly the same tasks as specified in my azure build and it works fine.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @yepeekai.
@javiercn can you please look into this? Thanks!

**Comment by yepeekai** [comment]
Workaround, if I do a dotnet build for the web project specifically, it works.
It doesn't work if I do a dotnet build without specifying the web project.  It doesn't work also if I specify the sln file which is probably the same thing as without specifying anything.

**Comment by javiercn** [comment]
@yepeekai thanks for contacting us.

Could you capture an MSBuild binary log (append /bl) and share it with us to help us determine exactly what's going on? It would also help us to understand the build steps you are taking and if you are customizing anything in the build process.

We do have tests for `dotnet publish --no-build` so I want to see if there is a concrete thing that is triggering this issue.

**Comment by yepeekai** [comment]
[msbuild_publish_nobuild.zip](https://github.com/dotnet/aspnetcore/files/8522362/msbuild_publish_nobuild.zip)
Sorry, I though you needed the build task.  Here is the one for the publish task

**Comment by yepeekai** [comment]
wait, the error is not there...  I will do it again

**Comment by yepeekai** [comment]
I found the problem! I made a typo at the time for the buildconfiguration to use.  I used release instead of Release.  "dotnet build" and "dotnet test" figured out automagically that I meant Release but it was not the case for "dotnet publish"
"dotnet publish" tries to use a path with "release" which doesn't exist in linux world.  I think it would be nice to make this more obvious.  I don't think I will be the last one to incorrectly type the configuration with the wrong case.

**Comment by javiercn** [comment]
@yepeekai thanks for the additional details.

This seems to be an issue with Publish not normalizing `release` to `Release`. Could you file an issue in `dotnet/sdk` with the concrete commands you run so that folks from the SDK/CLI can chime in?

Maybe it is expected that you use the exact casing or maybe it is a bug in that publish doesn't get normalized when it should, they would know better in any case.

From our side, I don't think we need to do anything on our targets, as we would expect the values to be Release or Debug and consistent across invocations.
