### ISSUE TITLE
Request Body as a string.

### ISSUE THREAD

**Issue by darcome** [dotnet/aspnetcore#41145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to log every request in the database and I am interested in the body too since my project is a Minimal API. As it stands, reading the body in a middleware involves opening it as a buffered stream so that it can then be read by the other middlewares and the final endpoint. Doing this has a big performance penalty.

### Describe the solution you'd like

Would it be possible to define a variable like ThresholdLengthForString (configurable by the user) so that bodies smaller or equal to the variable will be read as a string and immediately available for reading? That's because, usually, in an API is uncommon to see request bodies greater than 1Kbyte (probably even less).

Of course there would also be another variable like IsBodyString (or something like that) so that it is possible to know if the body is a string or needs to be read as a stream in case of a file upload or something else. And of course there would be the variable holding the string itself.

All of the above, of course, makes sense if asp.net core is able to read the body without using the buffered stream or in a way that doesn't incur in a big performance penalty. (I don't know if such a methodology exists or if can be implemented).

Thanks in advance,
Luca

**Comment by JamesNK** [comment]
Reading the request body will always have a performance cost. I'm afraid that if you want to read the request body for logging you'll always have some performance cost.

There are some things you can do to detect the request body size, such as check for a content-length header, but that isn't always present. Quite often the server doesn't know how long the request body is until it reads it. Also, the server doesn't know if the request body is a string. As far as it is concerned, the body is just incoming bytes. A good guess can be made using the content-type, but if there is no content type then there isn't a way to tell. An endpoint might know what the request body should be, so you could get the current endpoint from the HttpContext, and get metadata from it, and use that to make a decision, but that is fairly advanced.

I don't think this is something we can build into ASP.NET Core.
