### ISSUE TITLE
[signalr-client-c++] Client does not send access_token for calls after negotiate.

### ISSUE THREAD

**Issue by alex-kuhl** [dotnet/aspnetcore#41159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During the call to negotiate, the client receives a jwt "access token" that is used to complete it. However, this data is not included in future calls for auth purposes. This does not match the behaviour of the javascript signalr client.

### Expected Behavior

When the server receives a call, the SignalRService.InvocationContext.Query should have the same access_token that was sent during negotiate.

### Steps To Reproduce

1. Connect to a signalr server.
2. 'invoke` a function.
3. On the server, note that you do not receive the jwt access_token.

### Anything else?

It appears the access token is only used during the negotiate and then discarded.

May be related to #8716

**Comment by BrennanConroy** [comment]
Look at the headers, you should be getting an Authorization header. Also, there should never be an "access_token" in the query for any http requests from the client.

**Comment by alex-kuhl** [comment]
Hey again Brennan, thanks for the quick response.

I may be using the wrong terminology as I am not familiar with the server side of things. There is no authorization header received by the server in regular invokes after the successful negotiate. The list of headers I get are:
Host
Request-Id
X-ASRS-Connection_Id
X-ASRS-Hub
X-ASRS-Category
X-ASRS-Event
X-ASRS-User-Id
X-ASRS-User-Claims
X-ASRS-Client-Query (notably missing the access_token field when using the C++ client)
X-ASRS-Signature

In the Query field I get `hub` and `id`.

If I do the same call with the javascript client, everything else is the same, while the X-ASRS-Client-Query header and the Query field will have the access_token

**Comment by BrennanConroy** [comment]
I'm not familiar with any of those X-ASRS-* headers, looks like Azure SignalR Service though. If you remove ASRS does the Authorization header work as expected?

**Comment by BrennanConroy** [comment]
Ok, you're using something I've never used before so I may say things that don't make sense in that context. But, are you actually seeing issues with your scenario or are you just saying that the "access_token" is included with javascript and not with c++ but doesn't cause problems?

Have you configured auth for your endpoint? https://docs.microsoft.com/azure/azure-signalr/concept-upstream#authentication-settings

**Comment by alex-kuhl** [comment]
Right, the issue I am encountering is not that a signalr call is directly failing, it's that the javascript and C++ versions of the signalr client are being configured and used the same way as best I can tell, yet are not sending the same data, which is causing compliance validation failures on our server side.

So to me it looks like either the javascript side is sending non-standard extra data that our server dev is using for validation purposes, or the C++ client is missing this data. Looks like the javascript client is appending it [here](https://github.com/SignalR/SignalR/blob/50d7c4f06f6aeef69fcfc22d405e609a077ab717/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js#L357). We're also using websockets/cpprestsdk on the C++ side.

**Comment by BrennanConroy** [comment]
You've pointed to the SignalR/SignalR repo a couple times now, so I have to ask, what C++ client are you using?

**Comment by alex-kuhl** [comment]
We are using both the the [C++ client](https://github.com/aspnet/SignalR-Client-Cpp) (recently updated to latest to see if it would resolve this issue) for win32 buidls, and [microsoft/signalr.js](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-6.0&tabs=visual-studio) client for web builds.

For the C++ client, we are using the cpprestSDK backend.

Both clients share the same backend and server code.

**Comment by alex-kuhl** [comment]
Digging into this more this morning, it looks like the access_token field is a fallback for browser-based implementations of SignalR, and our server probably shouldn't be relying on it like it is right now.

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0

Would love to hear if you have anymore thoughts you might have though. Is the JWT sent for every invoke call so our server can capture it that way? I haven't been able to figure out how to capture the C++ client's traffic with fiddler, though it looks like it is using websockets and I've configured the proxy, so not sure what's going on there.

I'm not privy to what all our security requirements are on the server side, but I believe they want to receive and validate the JWT on every service call.

My setup is pretty basic and looks like this:
```
auto nativeBuilder = signalr::hub_connection_builder::create( config.url );
nativeBuilder.with_logging( std::make_shared<Logger>(), DefaultTraceLevel );

auto nativeConnection = nativeBuilder.build();

signalr::signalr_client_config nativeConfig;
if ( !config.authorizationToken.empty() )
	nativeConfig.get_http_headers().emplace( "Authorization"s, "Bearer "s + config.authorizationToken );

nativeConfig.set_proxy( { web::web_proxy::use_auto_discovery } );

nativeConnection.set_client_config( nativeConfig );

// subscribe to disconnect and events
```

**Comment by BrennanConroy** [comment]
> Is the JWT sent for every invoke call so our server can capture it that way?

If there is an access token configured for the client then it should be sent with every HTTP request. In the browser we try to send the token in the Authorization header, but have to fall back to query string in some cases, like when using WebSockets.

The C++ client should only be using the Authorization header as it doesn't have the same limitations that the browser does.

**Comment by alex-kuhl** [comment]
Okay, thanks for the clarification!

> If there is an access token configured for the client

To confirm, is this done differently from adding the auth header as my code snippet above? I don't see anything else in the configuration api that looks like a good match.

**Comment by alex-kuhl** [comment]
Okay great, thanks for your help Brennan.
