### ISSUE TITLE
AddDatabaseDeveloperPageExceptionFilter is added in all environments

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#41164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `AddDatabaseDeveloperPageExceptionFilter` method has the remark "This should only be enabled in the Development environment." but is included without any environment check.

### Expected Behavior

The developer exception filter should be called conditionally inside a if clause that checks `app.Environment.IsDevelopment()`.

### Steps To Reproduce

- Create a new Blazor Server App project.
- Open the `Program.cs` file.
- See that `builder.Services.AddDatabaseDeveloperPageExceptionFilter();` is called unconditionally.

### .NET Version

6.0.202

### Anything else?

ASP.NET Core 6.0.4
Visual Studio 2022, 17.1.4.
https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Program.cs

**Comment by mkArtakMSFT** [comment]
@ajcvickers can you please look into this and suggest what needs to happen, if anything? Thanks!

**Comment by javiercn** [comment]
@mkArtakMSFT no need for @ajcvickers to do anything here.

The service is always added, but the middleware is only added during development.

See the following code for reference: 
https://cs.github.com/dotnet/aspnetcore/blob/d4e09edefac2978b114030d55eefde22361accfd/src/DefaultBuilder/src/WebApplicationBuilder.cs#L141
