### ISSUE TITLE
EditForm bindable validation state

### ISSUE THREAD

**Issue by uecasm** [dotnet/aspnetcore#41163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In [this example](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#enable-the-submit-button-based-on-form-validation), the goal is to make a submit button enabled or disabled based on the current validation state of the form, which seems like a reasonably common requirement.

However, the current implementation of this requires switching to an `EditContext` instead of using the `Model`, and intercepting the `FieldChanged` event directly.  I suggest that this is a bit too complicated (and not entirely correct, since it might fire before validation is updated) and it would be better to do this another way.

### Describe the solution you'd like

In my own code (which I'd be happy to submit as a PR if there is interest), I've implemented a component (like `DataAnnotationsValidator` or `ValidationSummary`) which handles listening for validation events for you -- specifically it listens to the `OnValidationStateChanged` (assuming that the validator component itself will trigger this after field change) and exposes this as `IsValid` and `IsInvalid` bindable properties.  Thus you can simply:

```
<EditForm Model="..." ...>
    <... validator component .../>
    <ValidationWatcher @bind-IsInvalid="formInvalid" />
    <... form content .../>
    <button type="submit" disabled="@formInvalid">Submit</button>
</EditForm>
```

An alternative implementation might be to add these bindable properties to `EditForm` itself, rather than using a separate component.  (But an advantage of having it as a separate component is that it will also work with other form components based on `EditContext`; for example [BlazorStrap](https://blazorstrap.io/) defines its own [`BSForm`](https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Components/Forms/BSForm.cs) that uses `EditContext` but not `EditForm`; so an extra component will just work for both, while modifying `EditForm` would need to duplicate the changes there.)

This seems a lot tidier to have as a standard part of the framework.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
