### ISSUE TITLE
Client Certificate is discarded on TLS 1.3+IIS hosting

### ISSUE THREAD

**Issue by itn3000** [dotnet/aspnetcore#41162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I hosted ASP.NET Core app on IIS(Windows Server 2022).
I found client certificate in HttpContext is null from some clients.

I found some clients used TLS 1.3.
Requests from other clients which used TLS 1.2 can pass client certificate without any problems.
I want to use client certificate on ASP.NET Core for authentication.

And I tested on Kestrel hosting, client certificate was passed.

### Expected Behavior

HttpContext.Connection.ClientCertificate is not null even if client use TLS 1.3 when ASP.NET app is hosted on IIS.

## Environment

* Windows Server 2022 for hosting server
* ubuntu-20.04 with curl for HTTP client
* test code is https://gist.github.com/itn3000/53a83626e2c9dd0a4c5a44a493615a4c

## setup

1. creating self signed CA certificate using openssl and import to server root CA store
2. creating server certificate from CA certificate using openssl and import to server computer cert store
3. creating client certificate from CA certificate using openssl and convert to pkcs12 file
4. enable IIS on Windows Server 2022
5. install [ASP.NET Core 6.0 Hosting Bundle](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
6. build and publish ReturnClientCertificateThumbprintIIS project
7. [setting up ASP.NET Core IIS hosting](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0)
8. deploy ReturnClientCertificateThumbprintIIS project on `/aspnetcoretest`
9. [set IIS's client certificate setting to "Accept"](https://docs.microsoft.com/en-us/iis/manage/configuring-security/how-to-set-up-ssl-on-iis)
10. build and publish ReturnClientCertificateThumbprintKestrel project
11. run ReturnClientCertificateThumbprintKestrel
12. allow 443/tcp(IIS) and 5001/tcp(Kestrel) port

## run

1. run `curl https://[host]:[IIS port]/aspnetcoretest -k -E client.p12:[pkcs12 password] --tlsv1.3 --tls-max 1.3`
    * IIS+tls1.3
3. run `curl https://[host]:[IIS port]/aspnetcoretest -k -E client.p12:[pkcs12 password] --tlsv1.2 --tls-max 1.2`
    * IIS+tls1.2
5. run `curl https://[host]:[Kestrel port]/ -k -E client.p12:[pkcs12 password] --tlsv1.3 --tls-max 1.3`
    * Kestrel+tls1.3
7. run `curl https://[host]:[Kestrel port]/ -k -E client.p12:[pkcs12 password] --tlsv1.2 --tls-max 1.2`
    * Kestrel+tls1.2

## actual result

IIS+tls1.3 pattern returns `client cert is null`,
other pattern returns `client cert is [certificate hash string]`

### .NET Version

6.0.300-preview.22154.4

### Anything else?

here is `dotnet --info` output

```
.NET SDK (global.json �𔽉f):
 Version:   6.0.300-preview.22154.4
 Commit:    1eb22793b6

�����^�C����:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  2.1.803 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by JamesNK** [comment]
Thanks for the detailed report. I think we'll need to investigate what is going on and find where the issue is. TLS 1.3 is quite new and we may not validate this particular combination (IIS + TLS 1.3 + client certificates)

**Comment by itn3000** [comment]
In my additional investigation, same result(TLS 1.3 is always null, TLS 1.2 is ok) in ASP.NET Web Forms(.NET Framework 4.8).
so this issue could be IIS issue.

**Comment by Tratcher** [comment]
TLS 1.3 handles client certificates quite differently. The prior mechanism used to renegotiate the connection security and request a client certificate mid HTTP request was removed for security reasons. It was replaced by a new extension designed specifically for client certs, but that has not been implemented by some clients. Delayed client certificate negotiation causes many other problems and should be avoided in favor of requiring the certificate at the start of the connection.

See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0#optional-client-certificates

**Comment by itn3000** [comment]
I found when IIS's client certificate setting is changed from "Accept" to "Require",
IIS returned 403 in TLS-1.3.
Therefore, I have begun to suspect there is the problem in IIS before aspnetcore.

**Comment by Tratcher** [comment]
Try using netsh.exe to set that the client cert is required for that TLS binding. That does something different than IIS's Require option.

**Comment by itn3000** [comment]
Sorry, I found when HTTP2 is disabled and using HTTP1.1 by curl client, webapp could get client certificate even if TLS 1.3 is on.
TLS 1.3+HTTP2, client certificate is still null.

**Comment by Tratcher** [comment]
HTTP/2 does not allow delayed client certificate negotiation, client certs need to be negotiated when the connection is established. Try the netsh recommendation above.

**Comment by itn3000** [comment]
I understand this is not a bug, so I will try above solutions.
Thank you for responding.
