### ISSUE TITLE
Blazor Forms

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#41184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Razor Pages + Blazor components can bring back web forms!
We can have a toolbox to drag and drop html and Balzor controls on a designer, and a properties window to manage properties and events. Blazor components code can be part of the project to allow the user to customize them. I imagine that the API should be as close as possible to web forms to make it easy to upgrade.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by Eilon** [comment]
We do have a few resources that help Web Forms developers use Blazor, which you might be interested in:

* [.NET Conf 2020 Talk: From Web Forms to Blazor - Introducing the Blazor Web Forms Components](https://docs.microsoft.com/en-us/events/dotnetconf-2020/from-web-forms-to-blazor-introducing-the-blazor-web-forms-components)
* [BlazorWebFormsComponents: A collection of Blazor components that emulate the web forms components of the same name](https://github.com/FritzAndFriends/BlazorWebFormsComponents)

These don't enable drag & drop, but they can offer a smoother migration path.
