### ISSUE TITLE
Diagnosing production performance issues - missing PUT requests

### ISSUE THREAD

**Issue by houserrob** [dotnet/aspnetcore#41187]
Our service exposes a REST API which uses a AspNetCore.Kestrel 5.2 based web front end which in turn is hosted in a Service Fabric application.  We've been in production without any significant code changes for a couple of years and other than keeping the AspNet version relatively up to date we've rarely updated this part of the code.  In the last few weeks we've been seeing a much higher failure rate from our calling applications, they are receiving 408 errors.  Traffic has been growing recently but is nowhere near our historic highs and our load testing shows we should support much higher RPS/QPS than we currently see (5x at least) so this appears to have something do with a change in the call pattern to the service.  In particular we tend to be skewing to smaller payloads which process quickly (30-100 msec). However some of our payloads can cause much longer processing times (2000 msec-5000 msec) though these are somewhat less frequent.   

The pattern observed in our logs suggests that for a given session the series of queries sent to our service execute fine (perhaps a 100 or more) but then randomly fail for a few seconds and then resume normal operation.  From looking at the AspNet logs we've observed that the failing queries don't appear to leave behind any logging at all in the controller, acting like we never see the query at all.  We have an ILogger enabled and see "Request starting HTTP/1.1 PUT https..."  as our earliest logging entry for an payload that will successfully process.  We've not been able to find additional logging that starts earlier in the process than that.   We've profiled the code and the hot path is generally in communicating via proxy to send the payload off to the worker process.  We do wait for the result via await and have taken care to make sure all of our code is async.   

Is there any suggested ways to diagnose issues like this?  We are seeing the issue in production only so our ability to instrument there is limited and in any case it's not clear what we'd even instrument since our code doesn't get a chance at the payload in the failure cases. 

Thanks

**Comment by davidfowl** [comment]
> AspNetCore.Kestrel 5.2

What is this? ASP.NET Core 5.0?


Are you collecting counters in production? I would start with this suite of tools here https://docs.microsoft.com/en-us/dotnet/core/diagnostics/

**Comment by houserrob** [comment]
5.2 is the version of the nuget package we use to include Kestrel - Microsoft.ServiceFabric.AspNetCore.Kestrel.

Thanks for the link, I'd not run across this one yet and will see what we can apply in our case. 

We do have a large set of counters already being logged.  Nothing in terms of CPU, memory, disk read/write stands out.  Memory never exceeds 70%, CPU never exceeds 12%, disk read/write doesn't change during the event time period.   I did just find that the process hosting Kestrel doesn't log Thread Count (though other processes do) so I'll see if I can get that added.   Is there a particular set of counters that may be useful?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters

**Comment by noahfalk** [comment]
> We are seeing the issue in production only so our ability to instrument there is limited and in any case it's not clear what we'd even instrument since our code doesn't get a chance at the payload in the failure cases.

In terms of finding instrumentation when you don't know what exists in .NET I usually employ a couple strategies.
1. Some key libraries have documented what diagnostics are available such as: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/diagnostics, https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters, and https://docs.microsoft.com/en-us/dotnet/core/diagnostics/well-known-event-providers
2. Sometimes I find instrumentation that was added but never documented by searching in the source for types that are associated with instrumentation such as [EventSource](https://source.dot.net/#System.Private.CoreLib/EventSource.cs,70e1bbc6716a8d5d,references), [ILogger](https://source.dot.net/#Microsoft.Extensions.Logging.Abstractions/ILogger.cs,0976525f5d1b9e54,references), [Trace](https://source.dot.net/#System.Diagnostics.TraceSource/System/Diagnostics/Trace.cs,c63a0f19b2d4db69,references), and [DiagnosticListener](https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/DiagnosticListener.cs,1f0522930f6c2da8,references)

You should be able to tap into existing instrumentation earlier in the request processing pipeline to see if you can determine at what layer the request is being dropped/failed. A first place could be where requests have been parsed by Kestrel. If you see evidence the requests get to that point then you would be looking deeper into Kestrel's implementation and middleware vs if it doesn't reach that point you would be looking at things like connection setup, request parsing, OS, and physical network. When Kestrel starts processing a request the code runs through [here](https://source.dot.net/#Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs,46) and it is logged in a few different ways that you could observe:
- An [ILogger call](https://source.dot.net/#Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs,198) that is logged under category "Microsoft.AspNetCore.Hosting.Diagnostics" that you could [enable via logging configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging)
- An [EventSource call](https://source.dot.net/#Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs,307) you could [monitor](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-collect-and-view-traces) wither either out-of-process monitoring tools or an in-process EventListener. This also increments the Total-Requests counter in Microsoft.AspNetCore.Hosting so you might be able to compare the count of requests reaching this point vs. the count that arrives in your request handlers to detect a disparity.
- A [DiagnosticSource call](https://source.dot.net/#Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs,234) you could monitor with a [DiagnosticListener](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md)

I don't know in advance what will be the best option for you but you can look at how much information each one makes available and whether it would be easier for you to modify configuration files outside of the app, modify the app's code, or configure an out-of-process monitoring tool that runs in parallel with your app. Hopefully that helps give you some tools to make progress and feel free to follow up if you have more questions. Good luck cracking the case!

**Comment by houserrob** [comment]
Thanks Noah these are really great links.  I was able to get a little more logging along the connection path using your hints and was able to tone down some of the other logging so that things aren't unmanageable to bring this change to our production environment.  I'll see what I can find there.

For others I found that these two settings gave the best info on when the connection is accepted and the body read
..
      "Microsoft.AspNetCore.Server.Kestrel": "Debug",
      "Microsoft.AspNetCore.Hosting": "Information",
..

Rob
________________________________

**Comment by JamesNK** [comment]
Were you able to get enough information to figure out your issue?
