### ISSUE TITLE
Headers are accepting non-ASCII characters after moving to .NET 6

### ISSUE THREAD

**Issue by ppekrol** [dotnet/aspnetcore#41186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

our .NET Core 3.1 code is testing a scenario where we are trying to put non-ASCII characters into the headers. Code looks like follows:

```
                try
                {
                    HttpContext.Response.Headers["Content-Type"] = "aA\t";
                }
                catch (InvalidOperationException e)
                {
                    if (HttpContext.Response.Headers.ContainsKey("Content-Type"))
                        HttpContext.Response.Headers.Remove("Content-Type");
                }
```

This is working fine on our 3.1 branch, but after moving to .NET 6 (and ASP.NET Core 6) we are not getting any exception and our Client API is receiving that header. Is this by design? I'm almost sure that non-ASCII characters are not allowed in headers.

### Expected Behavior

Throw exception that header contains invalid characters.

### .NET Version

6.0.4

**Comment by davidfowl** [comment]
Turns out tabs are allowed.

https://github.com/dotnet/aspnetcore/issues/40599

**Comment by ppekrol** [comment]
Wow, that is new to me. Thanks for quick response!
