### ISSUE TITLE
Add an auth sample for cookies + bearer

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#4118]
This is a constant ask. Our guidance is to place `[Authorize("Bearer")]` on the API controllers but we have now sample showing this approach.

This or a similar sample should be a SPA app with a built in token server.

**Comment by HaoK** [comment]
@blowdart can we consider this done with our SPA templates now?

**Comment by blowdart** [comment]
I guess. Maybe. We hate mixing this anyway because it's too easy to get confused. a SPA or blazor would be the right way to go.

Closing.
