### ISSUE TITLE
LLVM Error When publishing blazor wasm

### ISSUE THREAD

**Issue by mrm7697** [dotnet/aspnetcore#41192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i want to Compile blazor wasm project as AOT i get this error in Console : 
clang version 13.0.0 (C:swircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 5852582532b3eb3ea8da51a1e272d8d017bd36c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\bin
 (in-process)
 "C:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\\6.0.4\\tools\\bin\\clang++.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj --mrelax-relocations -disable-free -main-file-name MudBlazor.dll.bc -mrelocation-model static -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility hidden -debugger-tuning=gdb -v "-fcoverage-compilation-dir=D:\\Projects\\Web.time2Work.ir\\Psyco.Time2Work.UserInterface\\Psyco.Time2Work.UserInterface" -resource-dir "C:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\\6.0.4\\tools\\lib\\clang\\13.0.0" -O2 -Werror=implicit-function-declaration "-fdebug-compilation-dir=D:\\Projects\\Web.time2Work.ir\\Psyco.Time2Work.UserInterface\\Psyco.Time2Work.UserInterface" -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -iwithsysroot/include/SDL "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o "C:\\Users\\User149\\AppData\\Local\\Temp\\2\\tmp1034.tmp" -x ir "D:\\Projects\\Web.time2Work.ir\\Psyco.Time2Work.UserInterface\\Psyco.Time2Work.UserInterface\\obj\\Release\\net6.0\\wasm\\for-publish\\MudBlazor.dll.bc"
clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-pc-windows-msvc
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: "C:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\\6.0.4\\tools\\bin\\clang++.exe" -target wasm32-unknown-emscripten -DEMSCRIPTEN -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=23 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL "--sysroot=C:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\\6.0.4\\tools\\emscripten\\cache\\sysroot" -Xclang -iwithsysroot/include\\compat -O2 -v -c D:\\Projects\\Web.time2Work.ir\\Psyco.Time2Work.UserInterface\\Psyco.Time2Work.UserInterface\\obj\\Release\\net6.0\\wasm\\for-publish\\MudBlazor.dll.bc -o C:\\Users\\User149\\AppData\\Local\\Temp\\2\\tmp1034.tmp
1.	Code generation
2.	Running pass 'Function Pass Manager' on module 'D:\Projects\Web.time2Work.ir\Psyco.Time2Work.UserInterface\Psyco.Time2Work.UserInterface\obj\Release\net6.0\wasm\for-publish\MudBlazor.dll.bc'.
3.	Running pass 'WebAssembly Instruction Selection' on function '@MudBlazor_MudBlazor_Filled__ctor'
0x00007FF6EAFCD716 (0x0000000000000016 0x00007FF6EAFCD710 0x0000000200000008 0x0000006E00000001) <unknown module>
0x00007FFB4131D88D (0x00007FF6EAFCD710 0x0000000200000008 0x0000006E00000001 0x0000000000000001) <unknown module>
0x0000000000000016 (0x0000000200000008 0x0000006E00000001 0x0000000000000001 0x0000000000000012) <unknown module>
0x00007FF6EAFCD710 (0x0000006E00000001 0x0000000000000001 0x0000000000000012 0x0000006EB5786F60) <unknown module>
0x0000000200000008 (0x0000000000000001 0x0000000000000012 0x0000006EB5786F60 0x00007FFB4131D493) <unknown module>
0x0000006E00000001 (0x0000000000000012 0x0000006EB5786F60 0x00007FFB4131D493 0x0000000000000000) <unknown module>
0x0000000000000001 (0x0000006EB5786F60 0x00007FFB4131D493 0x0000000000000000 0x0000000000000001) <unknown module>
0x0000000000000012 (0x00007FFB4131D493 0x0000000000000000 0x0000000000000001 0x0000022DCD6C40B0) <unknown module>
0x0000006EB5786F60 (0x0000000000000000 0x0000000000000001 0x0000022DCD6C40B0 0x0000000000004040) <unknown module>
0x00007FFB4131D493 (0x0000000000000001 0x0000022DCD6C40B0 0x0000000000004040 0x00007FFB412C5310) <unknown module>
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (C:swircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 5852582532b3eb3ea8da51a1e272d8d017bd36c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\bin
clang++: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
emcc: error: '"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\bin\clang++.exe" -target wasm32-unknown-emscripten -DEMSCRIPTEN -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=23 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL "--sysroot=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\emscripten\cache\sysroot" -Xclang -iwithsysroot/include\compat -O2 -v -c D:\Projects\Web.time2Work.ir\Psyco.Time2Work.UserInterface\Psyco.Time2Work.UserInterface\obj\Release\net6.0\wasm\for-publish\MudBlazor.dll.bc -o C:\Users\User149\AppData\Local\Temp\2\tmp1034.tmp' failed (returned 1) [took 249.94s]

**Comment by TanayParikh** [comment]
Hi @mrm7697, thanks for contacting us. Can you please confirm what command you're using to build the Blazor WASM project with AOT? Are you using `dotnet build` or something else? If you're using `dotnet`, can you please provide a minimal, public GitHub project that reproduces this issue? Also if you could kindly confirm what OS and version you're using (I assume Windows based on the `C:/` but just checking).


If you're using another tool aside from `dotnet`, this may be something that needs to be reported to LLVM directly (per the console output in your snippet):

```
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
```
