### ISSUE TITLE
Issue reading two querystrings from HttpContext.Request.Query 

### ISSUE THREAD

**Issue by izzyjere** [dotnet/aspnetcore#41191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a function that generate an email confirmation link as shown below:
````csharp
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var route = "user/confirm-email";
            var endpointUri = new Uri(string.Concat($"{origin}/", route));
            var verificationUri = QueryHelpers.AddQueryString(endpointUri.ToString(), "userId", Convert.ToString(user.Id));
            verificationUri = QueryHelpers.AddQueryString(verificationUri, "code", code);
            return verificationUri;
````

### Expected Behavior

Here is the full url I am getting:  

"......../user/confirm-email?userId=1018&amp;code=Q2ZESjhCYW5VeGFEWlNOT2hBNklVLzNvM1N4ajg3THl3QUpxWlZLdUZlenFGODZqTmFvUTVQaklIbFIxTWlJUXI3WDExS3dqZ0J4SWRSZUFoOFdONlNFaWtWV29KRmZvRFptN0lMNElseWtpUTFyVEo1eW1uN0RyVGR4bHExTmJzL2ZxQldZZ0VaMVBackUrTHEzT2kxWkNyT3FyeUhRQjAwaGJWWm9SZWtwdytxUGlpT3JvdmNvUnBwbzhMUzVRMXk1ZDRqWDg2WExTK05MUWFRRSs0dTdidWljPQ"

However when I try to read the two query string using 
````csharp
             var code = HttpContext.Request.Query["code"].ToString(); //this returns null
             var userId = HttpContext.Request.Query["userId"].ToString();
````
I later discovered that if I do this:
````csharp
    var code = HttpContext.Request.Query["amp;code"].ToString(); //I am able to get the value.
````

### Exceptions (if any)

None

### .NET Version

6.0.200-preview.22055.15

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22055.15
 Commit:    a3c3a2bf3b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21996
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Tratcher** [comment]
`"amp;code"` that implies the url is being html encoded but then not decoded before used. Can you share a Fiddler trace for this scenario?

**Comment by HaoK** [comment]
There's no product issue here, as you do need to be careful when generating your email links, here's the relevant code in how we do it to generate an url:

```
            var userId = await _userManager.GetUserIdAsync(user);
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            EmailConfirmationUrl = Url.Page(
                "/Account/ConfirmEmail",
                pageHandler: null,
                values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
                protocol: Request.Scheme);
```

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/RegisterConfirmation.cshtml.cs#L79
