### ISSUE TITLE
Quarantine ConfigurationChangeCanBeIgnoredInProcess

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#41207]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ConfigurationChangeCanBeIgnoredInProcess

## Error Message

```text
System.InvalidOperationException : Didn't get response that satisfies predicate after 10 retries
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.RetryRequestAsync(HttpClient client, String uri, Func`2 predicate) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 128
   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ConfigurationChangeCanBeIgnoredInProcess() in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 424
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text

```
[ShutdownTests_ConfigurationChangeCanBeIgnoredInProcess.log](https://github.com/dotnet/aspnetcore/files/8497012/ShutdownTests_ConfigurationChangeCanBeIgnoredInProcess.log)

</details>

## Build

Two consecutive failures on Windows.11.Amd64.ClientPre.Open:
https://dev.azure.com/dnceng/public/_build/results?buildId=1719615&view=ms.vss-test-web.build-test-results-tab&runId=46697984&resultId=121334&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=1718864&view=ms.vss-test-web.build-test-results-tab&runId=46682882&resultId=111308&paneView=debug

**Comment by Tratcher** [comment]
Two additional failures in Windows.Amd64.Server2022.Open and Windows.10.Amd64.Server20H2.Open:
https://dev.azure.com/dnceng/public/_build/results?buildId=1719780&view=ms.vss-test-web.build-test-results-tab&runId=46701768&paneView=debug&resultId=121809

**Comment by HaoK** [comment]
Note: I think something changed/regressed here because this test went from very reliable to almost always failing with 75%+ failure rate, this should go on the higher investigate list

**Comment by HaoK** [comment]
Seems to have started after we took a runtime update in https://github.com/dotnet/aspnetcore/commit/c357496023623aeaf0fbaddf70042b0c0e4e62ef

**Comment by HaoK** [comment]
This is passing now, so the regression seems to have been fixed

**Comment by HaoK** [comment]
Unquarantined in https://github.com/dotnet/aspnetcore/pull/42932
