### ISSUE TITLE
OnInitializedAsync runs on every page load

### ISSUE THREAD

**Issue by Atulin** [dotnet/aspnetcore#41200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I made a Razor component

```cs
@using System.IO
@using Serilog
<div style="border: 3px solid firebrick">
    <h3>File Test</h3>
    <pre>@_text</pre>
</div>

@code {
    private string _text = string.Empty;
    protected override async Task OnInitializedAsync()
    {
        Log.Error("[{Date}] Running!", DateTime.Now);
        _text = await File.ReadAllTextAsync("config.json");
    }
}
```

that gets embedded inside of a `.cshtml` Razor page with

```html
<component type="typeof(FileTestComponent)" render-mode="Static"></component>
```

From what I read, `OnInitializedAsync()` runs only once, on first render, and render mode being `Static` should generate static HTML.

And yet, every time I refresh the page, I see the message logged to the console. Which tells me that no, this code doesn't run only on first render

![image](https://user-images.githubusercontent.com/11233299/163524626-12003ce5-44d7-4ff6-b51e-ca43d0d1b45e.png)

### Expected Behavior

Code runs only once, be it on first request or even on build time

### Steps To Reproduce

https://github.com/Atulin/ComponentDemo

### .NET Version

6.0.104

**Comment by javiercn** [comment]
@Atulin thanks for contacting us.

render-mode="Static" means that the content will not be made interactive afterwards either via Blazor Server or Blazor Webassembly. It doesn't mean that the content only gets generated once.

The content will be generated on each request, but the result will just be static markup.

**Comment by Atulin** [comment]
I'm assuming, similarly, `OnInitializedAsync()` doesn't actually run only once either?
