### ISSUE TITLE
Double setting of Bound Variable when using EventCallback Async Await with HttpClient call

### ISSUE THREAD

**Issue by UnAnalogFG** [dotnet/aspnetcore#41217]
### Description

I was trying to fetch some data via HttpClient on a Button Click and setting a bound Variable.
when I realised that using the HttpClient leads to setting the a bound variable twice. 
Once with the old object, once with the new one.
I was suspecting the await to wait for the result of the Http-Call before the framework fires the 'StateHasChanged' Event for the 'OnClick' EventCallback.

### (Im-)Possible workaround 
Even if I do an early out on the setter in the sub component based on an object-comparison, the OnSetParameter-Event is nevertheless fired twice, which is not necessary.

### Some Code
```
<!-- the Page -->
<!-- snippet-->

@page "/"
@inject HttpClient Http

<button @onclick="ClickHttpAsync"> Do </button>
<DataSubView Data="Data"/>

@code{

private X Data {get;set;}

// calls the setter 2times
public async Task ClickHttpAsync()
{
    var newData = await Http.GetAsync("http://XXX");
    Data = newData;
}

// set only once
public async Task ClickAsync()
{
    await InvokeAsync(()=>{Thread.Sleep(1000);});
    Data = new X();
}

// sets only once
public void Click()
{
    Data = new X();
}
```
```
<!-- the DataSubView Component -->
<!-- snippet -->

@code
{
    private X data;

    [Parameter]
    public X Data
    {
        get=>data;
        set
        {
            if (value == data) Console.WriteLine ("Old Data Re-Set");
            data = value;
        }
    }
}
```

### Demo Repo
I made a small Repo to show the behaviour

https://github.com/UnAnalogFG/BlazorWasmAsyncEventBug

### Expectation
I would expect all ClickEvents to behave the same, calling the setter only once as the await should "synchronize" the async call.
As it does on the one that does not use the HttpClient

### Configuration
.Net Core 6.04, Blazow WASM, Windows 10, X64, Chrome, Edge, Firefox

**Comment by javiercn** [comment]
@UnAnalogFG thanks for contacting us.

This is expected and by design. You can read more about how it works [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#lifecycle-events).

Essentially your InvokeAsync+Thread.Sleep is doing nothing because the task is being inlined and Thread.Sleep is blocking, so everything runs synchronously.

On the HttpClient case when the synchronous part of the code execution finishes running a render is triggered, then when the asynchronous call completes, another render is triggered.

**Comment by UnAnalogFG** [comment]
But why is a re-render triggered on the HTTPClient await return ?. What's the reason. 
If I'm not setting "Data = newData", then no re-render is done at all. 
So It seems the Re-Render is triggered by setting Data = new Data but that happens after the await.
