### ISSUE TITLE
Cannot build the project which reference to another project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41210]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-build-the-project-which-reference/10013045)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Visual Studio 2022 17.2.0 Preview 3.0]
I am working with Visual Studio 2022 17.2.0 Preview 3.0.
I have created Blazor library in one solution and then open the second new Blazor project, add existing library and it cannot build it. 

What is strange that when I will try to run practically same app inside of same solution as library and it works fine and build properly. 

I have tried to clean projects, rebuild, delete manually bin and obj (during closed VS and open again) and stilll nothing. It is hard to describe here are some pictures:

First window with full solution including library VEBlazor and its dependend project VEDriversLite. Here it builds ok:

![image.png](https://aka.ms/dc/image?name=B34ee80f7224a46f185abf7edd490925d637854824441987624_20220413-173402-image.png&tid=34ee80f7224a46f185abf7edd490925d637854824441987624)

Here is the second window with Blazor WASM and connected existing project VEBlazor. 

![image.png](https://aka.ms/dc/image?name=Bf8124126c59e4674af4afc89a00f0eb0637854825107534281_20220413-173509-image.png&tid=f8124126c59e4674af4afc89a00f0eb0637854825107534281)

Even if I will prebuild it in the first window and it pass, then second window will build it again and fail. Maybe I am missing something, but dont know. before install of update it worked fine, so maybe it is something about it. If you want we can call and you can download some logs from me.

Thanks for help.

Tomas

---
#### Feedback Bot on 4/14/2022, 03:32 AM: 

(private comment, text removed)
#### Tomáš Svoboda on 4/14/2022, 06:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by fyziktom** [comment]
> 

Hello. 
[The repository](https://github.com/fyziktom/VirtualEconomyFramework/tree/101-feature-nftxray)

I have been working in branch 101. The [BDP App](https://github.com/fyziktom/VirtualEconomyFramework/tree/101-feature-nftxray/VirtualEconomyFramework/BDP-WASM) was possible to build without trouble

I [had this project] (https://github.com/fyziktom/VirtualEconomyFramework/tree/101-feature-nftxray/VirtualEconomyFramework/VEBlazor.Demo.EventsAndTickets) in separated solution before, when it was not possible to build. The library VEBlazor was added to same solution as existing project and then added as reference to the blazor project.
When I tried to place it to the same main VirtualEconomyFramework solution it worked fine, so it was not trouble of the syntax.

**Comment by javiercn** [comment]
@fyziktom thanks for the additional details.

Unfortunately the repro that you have provided is too big for us to effectively determine if there is an issue in the SDK without expending a significant amount of time on it. For us to make progress we need the repro to contain the minimal amount of code necessary to trigger the issue, so please take out anything that is not necessary from the repro and share that with us as well as the concrete steps to trigger the issue (what project to build and how (from VS or using dotnet build))

**Comment by fyziktom** [comment]
> @fyziktom thanks for the additional details.
> 
> Unfortunately the repro that you have provided is too big for us to effectively determine if there is an issue in the SDK without expending a significant amount of time on it. For us to make progress we need the repro to contain the minimal amount of code necessary to trigger the issue, so please take out anything that is not necessary from the repro and share that with us as well as the concrete steps to trigger the issue (what project to build and how (from VS or using dotnet build))


yeah...sorry for that :D I was busy, so I just wrote report. 

[In this new repo](
https://github.com/fyziktom/VSBugReportExamples/issues/1) you can find the example repo with simple Class Lib, Razor Component Lib and then two Blazor WASM apps which simulate the same error.

**Comment by javiercn** [comment]
@fyziktom thanks for the additional details.

I don't think there is anything specific to Blazor here. The behavior you are seeing is expected and by design. Visual Studio won't build projects outside of the solution even if you have project references to them. You need to build those projects ahead of time either from the command line or from a different solution. 

The same thing happens when you use solution filters. If you have a dependent project that is not part of the solution or solution filter, it needs to be already built by other means for the build in Visual Studio to succeed.

**Comment by fyziktom** [comment]
It happened even if the lib has been already built. That was one of the point. But maybe it is just my not understand of Visual Studio, so sorry for that :D

**Comment by javiercn** [comment]
@fyziktom no need to be sorry about anything. I tried the repro and I wasn't able to reproduce it. Make sure you build the solution with the dependency first and then the other solution. The error should go away.

**Comment by fyziktom** [comment]
Ok. thanks for help.
