### ISSUE TITLE
Adding swagger to Blazor Server app break the Blazor Server App.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#41223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding swagger to Blazor Server break the Blazor Server App.
Here is the program.cs file

```
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();


ApplicationInsightsServiceOptions aiOptions = new ApplicationInsightsServiceOptions();
aiOptions.EnableAdaptiveSampling = false;
aiOptions.InstrumentationKey = builder.Configuration["ApplicationInsights:InstrumentationKey"];
aiOptions.EnableQuickPulseMetricStream = true;
builder.Services.AddApplicationInsightsTelemetry();

builder.Services.AddAutoMapper(typeof(AutoMapperProfile));

builder.Services.AddSingleton<WeatherForecastService>();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen();

builder.Services.AddHttpContextAccessor();


builder.Services.AddHttpClient("default", client =>
{
    //client.BaseAddress = new Uri("");
    client.DefaultRequestHeaders.Add("Accept", "");
    client.DefaultRequestHeaders.Add("User-Agent", "API");
});

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "v1"));


// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();

}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");


app.Run();

```

### Expected Behavior

Should load the Blazor App along with the swagger

### Steps To Reproduce

Add Swagger to new Blazor server Template

### Exceptions (if any)

This localhost page can’t be found 
No webpage was found for the web address: https://localhost:7099/index.html
HTTP ERROR 404

### .NET Version

6.0.300-preview.22154.4

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22154.4
 Commit:    1eb22793b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

If this is a Blazor Server application there is no index.html page as described above.

I would suggest you start by turning logs to debug level and inspect the output to see what might be going on. 

It is highly unlikely swagger impacts Blazor in any way as the two systems don't interact together.
