### ISSUE TITLE
Random CSS class name generation

### ISSUE THREAD

**Issue by Jukpfusi** [dotnet/aspnetcore#41227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It is not related to any problem.

### Describe the solution you'd like

Hello,
I haven't found a solution to rename CSS classes with random class names (a kind of "obfuscation") :
![image](https://i.ibb.co/GtYV2r9/unknown.png)
Class names would be regenerated only once (and not at each request).

What is the best way to implement this "obfuscation", I thought about middleware but it would cause too much performance slowdown.

Maybe the cshtml files would have to be modified at startup, during razor pages compilation?

Note: if someone is willing to implement this, we can do it together.

**Comment by javiercn** [comment]
@Jukpfusi thanks for contacting us.

This is not a direction we plan to move in the near future. It is a lot of work to get this implemented and maintained and we don't see a significant reason to consider this valuable. 

In addition to that, you can implement this yourself with a helper method in C# to transform the class from a legible value into something you want, by for example computing a sha-256 of the class name and hex encoding some bits of it to use as the transformed class name. You would need to apply the same transform to your CSS files.

I would suggest you reconsider your reasons for doing this type of work and reevaluate whether it is truly worth it.
