### ISSUE TITLE
Consider registering the authentication state provider conditionally

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#41235]
Use `TryAddScoped` here instead of `AddScoped`

https://github.com/dotnet/aspnetcore/blob/02e7e14782509c11e15cd559e5b07211600572ba/src/Components/Server/src/DependencyInjection/ComponentServiceCollectionExtensions.cs#L82

It's not clear to me why we do this, but I suspect that it is because in the past we might have had a different implementation registered by default inside MVC for rendering components statically.

I don't believe we need this any longer and it creates a hard to debug issue for our customers as it forces an order when customers want to provide a custom implementation (on something that we tell customers to customize).

I can't foresee any drawback on changing this to use `TryAddScoped` instead, so we should do so.

**Comment by javiercn** [comment]
This issue came as a result of looking into https://github.com/dotnet/aspnetcore/issues/41228

**Comment by damienbod** [comment]
Hi @javiercn I could try this one if you want, I would like to look the Blazor authentication anyway.
