### ISSUE TITLE
Adopt consistent approach for defining InternalsVisibleTo in the repo

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#41244]
This is a follow-up to some PR feedback I received in https://github.com/dotnet/aspnetcore/pull/41238#discussion_r852307921 (and other PRs).

We use two different strategies for defining IVT in the repo at the moment:

- Property in the build
- Assembly attribute in source

For consistency, we might want to consider adopting one standard throughout the repo and using that everywhere.

**Comment by Tratcher** [comment]
Declaring it in the csproj file is simpler and cleaner. We used the assembly attribute before because the csproj option wasn't available.
