### ISSUE TITLE
Quarantine InteropTests.InteropTests.ClientCompressedUnary

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#41248]
## Failing Test(s)

- InteropTests.InteropTests.ClientCompressedUnary

## Error Message

```text
System.InvalidOperationException : Error while running client process.
```

## Stacktrace

<details>

```text

```
</details>

## Logs

<details>

[console.7d6b1551.txt](https://github.com/dotnet/aspnetcore/files/8508274/console.7d6b1551.txt)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1723679&view=ms.vss-test-web.build-test-results-tab&runId=46765000&resultId=120261&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1723144&view=ms.vss-test-web.build-test-results-tab&runId=46752406&paneView=debug&resultId=120019

**Comment by davidfowl** [comment]
This was failing on my PR so I'll take this one.
