### ISSUE TITLE
dotnet watch hangs while a Time Machine backup is being run on macOS Monterey

### ISSUE THREAD

**Issue by peterlgarland** [dotnet/aspnetcore#41257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I don't know if this is an issue to reach out to you or to Apple.

I have an M1 Pro MacBook Pro backing up via Time Machine to a Sparse Disk Image on a Windows Server. This is not a problem.

The problem is, if I'm running dotnet watch and a back is occuring, changes aren't Hot Reloading and when I exit the command it hangs, and I mean hangs! You can't kill it and if you restart the Mac, it Panics.

Now, it was really racking my brains what was causing this issue, but if I unmount the Time Machine backup drive, the problem goes away, so I'm assuming it's related to the fact that Mac is watching those files at the same time dotnet is?

I can replicate the problem at anytime by reconnecting the drive, but therefore also stop the problem by disconnecting it and happy to provide any further information if required.

### Expected Behavior

For dotnet watch to work as it should, and it does if the Time Machine backup drive isn't connected and a backup isn't running.

### Steps To Reproduce

Attach a TIme Machine Backup disk to an M1 Mac on macOS Monterey and it works fine, until you notice it doesn't! This will be when the automatic backup has started.

### .NET Version

6.0.202

### Anything else?

% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Using both VS Code and trialling Visual Studio 2022 Preview. I'm developing a .Net 6.0 WebAssembly Blazor App / ASP.Net Core Server.

**Comment by Rick-Anderson** [comment]
@peterlgarland can you exclude your source directory from the backup and do frequent pushes to GitHub to back up your code?

If you want nearly instant backup in case of a drive failure, system crash, etc, you can have the development project backed up by OneDrive, Google Drive, or Dropbox.

My guess is that TMB is causing the problem.

**Comment by halter73** [comment]
> The problem is, if I'm running dotnet watch and a back is occuring, changes aren't Hot Reloading and when I exit the command it hangs, and I mean hangs!

If this is true, that sounds like that would have to be a bug in [FileSystemWatcher](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0) which `dotnet watch` uses. Given the lack of similar issues being reported, this does seem unlikely. I suspect there's something more to this than just a simple Time Machine backup.

Is it possible that there's just some sort of resource bottleneck (maybe disk bandwidth) while the backup is going on? What does the data read/second and write/second show in ActivityMonitor when the problem occurs? Also, does `kill -9 <pid>` (or `killall -9 dotnet` if you're struggling to find the right `<pid>`) really not kill the process? Can you provide the output `clrstack -all` using [dotnet-dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#using-dotnet-dump) when the dotnet watch process is hanging?

> You can't kill it and if you restart the Mac, it Panics.

Is this a kernel panic? If so, you should definitely take the option to automatically report it to Apple. It should not be possible for a userland process like dotnet-watch to cause a panic no matter how buggy the userland process is.
