### ISSUE TITLE
Update spa templates to facilitate multi-stage docker builds

### ISSUE THREAD

**Issue by tmds** [dotnet/aspnetcore#41275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The spa templates use `npm` for the client-side, and `dotnet` for the server-side.

The .NET sdk container images do not provide npm. So they can not be used directly to build the spa templates.

Another option is to use a multi-stage build, with a separate stage that uses a node image. The templates are not written to support this scenario.

### Describe the solution you'd like

With some tweaks to the template, the project can more easily support a multi-stage build that has a node/npm stage.

```
$ dotnet new angular -o angular
$ cd angular
```
Modify the `csproj`:
```xml
     <Nullable>enable</Nullable>
     <IsPackable>false</IsPackable>
     <SpaRoot>ClientApp\</SpaRoot>
+    <SpaBuildCommand>npm run build -- --prod</SpaBuildCommand>
     <SpaProxyServerUrl>https://localhost:44411</SpaProxyServerUrl>
     <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
     <ImplicitUsings>enable</ImplicitUsings>
@@ -33,8 +34,8 @@
   
   <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
     <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
-    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
-    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod" />
+    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" Condition="'$(SkipSpaBuild)' != 'True'"/>
+    <Exec WorkingDirectory="$(SpaRoot)" Command="$(SpaBuildCommand)" Condition="'$(SkipSpaBuild)' != 'True'"/>
 
     <!-- Include the newly-built files in the publish output -->
     <ItemGroup>
```

This app can be built using the following multi-stage `Dockerfile`:
```Dockerfile
# Publish Spa
FROM node:lts-alpine as node-build
WORKDIR /src
COPY . ./
# cd to csproj <SpaRoot>
WORKDIR /src/ClientApp
# restore npm dependencies
RUN npm install
# run csproj <SpaBuildCommand>
RUN npm run build -- --prod

# Publish application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnet-build
USER 0
WORKDIR /src
COPY . ./
# Copy SpaRoot
COPY --from=node-build /src/ClientApp /src/ClientApp
RUN dotnet restore .
# Skip Spa build during publish
RUN dotnet publish --no-restore -c Release -o /out . /p:SkipSpaBuild=True

# Build application image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=dotnet-build /out /app
CMD ["dotnet", "/app/angular.dll"]
```

**Comment by tmds** [comment]
@davidfowl @richlander ptal.

**Comment by javiercn** [comment]
@tmds thanks for contacting us.

This is a good point. At the very least we should have docs covering this scenario.

**Comment by richlander** [comment]
Repeating @javiercn ... this is a good point.

We should have a design constraint of Docker build-ability. I can see that MSBuild and Docker are not easy to align. Perhaps there needs to be a way to suppress the node/npm commands within msbuild or alternatively specifically target those commands.

@glennc @danroth27

**Comment by javiercn** [comment]
@tmds I'm ok if we do something on the project to skip the node steps when building inside docker. There is an environment variable we can use.

I do have a repo where I did something similar to what you did. https://github.com/javiercn/AngularWithDocker

Anything [here](https://github.com/javiercn/AngularWithDocker/blob/23c5f8996c63a8cdf67206af93cf65a4a3c95d36/AngularWithDocker/AngularWithDocker.csproj#L25-L49) I'm happy if we key it off of '$(DOTNET_RUNNING_IN_CONTAINER)' == ''

@richlander What would need to happen here for us to update the  dockerfiles/docker images to better support SPAs?

**Comment by javiercn** [comment]
Based on investigations, I think it is better we document that you need to install node into the container image in an extra stage and do the build there
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-with-spa
RUN bash -E $(curl -fsSL https://deb.nodesource.com/setup_18.x | bash - ); apt install -y nodejs

From build-with-spa as build
```

**Comment by javiercn** [comment]
I have filed a separate issue https://github.com/dotnet/dotnet-docker/issues/3909 to consider adding an additional container image that already contains the node tools installed for web projects.

**Comment by tmds** [comment]
Multi-stage builds are best practice and allow to manage build dependencies as images.

> I have filed a separate issue https://github.com/dotnet/dotnet-docker/issues/3909 to consider adding an additional container image that already contains the node tools installed for web projects.

They allow the people that build dotnet-docker images to focus on .NET.
While others focus on maintaining nodejs images.

**Comment by tmds** [comment]
Because it's a best practice, it would be nice if the templates support it.

**Comment by mkArtakMSFT** [comment]
We've decided not to make this change in the framework and instead include more details in docs about how to achieve this. /cc @javiercn
