### ISSUE TITLE
Razor Class Library isn't adding typescript output to static web assets

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#41279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've RCL with a typescript sources and I want to include the generated javascript in the package as staticwebassets.

I've followed the docs: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio#typescript-integration

However, the javascript files are not included as staticwebassets:
![image](https://user-images.githubusercontent.com/3494407/164255938-bc96818e-9564-4540-90af-6463eb0f7c09.png)

Here is my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>
	<PropertyGroup>
		<TypescriptOutDir>wwwroot</TypescriptOutDir>
	</PropertyGroup>
	<PropertyGroup>
		<ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
			CompileTypeScript;
			$(ResolveCurrentProjectStaticWebAssetsInputs)
		</ResolveCurrentProjectStaticWebAssetsInputsDependsOn>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.2" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>
</Project>
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/3494407/164256936-497b7ce9-447a-41e0-8d6d-87bbd7c9e99a.png)

### Steps To Reproduce

1. Create .csproj file from the xml above
2. Add scripts/file1.ts
3. run `dotnet build`
4. Check the generate nuget

### .NET Version

6.0.300-preview.22154.4

### Anything else?

I've tried  SDK v6.0.200 as well - the same result

**Comment by javiercn** [comment]
@Liero thanks for contacting us.

I think the docs need to be updated for this one, we changed a bit the way our targets run in .NET 6.0, so you need to add the following

```
<PropertyGroup>
  <AssignTargetPathsDependsOn>CompileTypeScript;$(AssignTargetPathsDependsOn)<AssignTargetPathsDependsOn>
</PropertyGroup>
```

We do have an issue to improve this area in .NET 7.0, I would suggest you upvote it here https://github.com/dotnet/aspnetcore/issues/40572

**Comment by Liero** [comment]
@javiercn : I have added what you suggested and the result is the same

**Comment by javiercn** [comment]
@Liero it seems that the targets in typescript have changed a bit.

```xml
<PrepareForBuildDependsOn>GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
```

Should do the trick.

**Comment by Liero** [comment]
Thanks @javiercn.

 Following minimal csproj worked for me:

```msbuild
<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.2" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<TypescriptOutDir>wwwroot</TypescriptOutDir>
		<PrepareForBuildDependsOn>GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
		<AssignTargetPathsDependsOn>
			CompileTypeScript;
			$(AssignTargetPathsDependsOn)
		</AssignTargetPathsDependsOn>
	</PropertyGroup>	
</Project>
```

**Comment by Liero** [comment]
@javiercn: Notice that I'm just doing `dotnet build` with `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>`. I don't specifically execute `dotnet pack --no-build`

**Comment by guardrex** [comment]
Thanks @Liero ... Yes, let's have the discussion continue here or on a new docs issue, if needed. I'm going to lock down the PR in case any new readers wander by there.

@javiercn remarked before the preceding comment:

> @Liero thanks for the additional details.
>
> I didn't try pack explicitly, but I don't think that
>
> ```xml
> <AssignTargetPathsDependsOn>
> 		CompileTypeScript;
> 		$(AssignTargetPathsDependsOn)
> ```
>
> does anything.
>
> WRT to packing, you might have run into a different bug if you were doing something like pack --no-build

**Comment by Liero** [comment]
@guardrex: Ok, do you need some more input from me? I think it would be suitable to remove labels `Resolution: Duplicate` and `Status: Resolved`

**Comment by javiercn** [comment]
Yeah, the GeneratePackageOnBuild is the delta here

**Comment by Liero** [comment]
@javiercn: I've just tried and **it does not work** :( 
I guess you didn't cleaned the generated js files before build.
Please reopen.

Here is my full csproj for reference:

<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PrepareForBuildDependsOn>GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
		<TypescriptOutDir>wwwroot</TypescriptOutDir>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.2" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>

**Comment by Liero** [comment]
Here is repo: https://1drv.ms/u/s!An7wnk66a6RRlqsR9ME32HR2wMNB5g?e=Xx7RIM
