### ISSUE TITLE
Doc misinformation for the property displayName in the UserLoginInfo Constructor

### ISSUE THREAD

**Issue by florenzetti** [dotnet/aspnetcore#41284]
The documentation for the constructor’s parameter displayName of the class UserLoginInfo is not the same of the property it is used for.
This can cause a misunderstood on how to use this property / constructor. 

I assume that the documentation for the property ProviderDisplayName is the accurate one.

    /// <summary>
    /// Creates a new instance of <see cref="UserLoginInfo"/>
    /// </summary>
    /// <param name="loginProvider">The provider associated with this login information.</param>
    /// <param name="providerKey">The unique identifier for this user provided by the login provider.</param>
    /// <param name="displayName">The display name for this user provided by the login provider.</param>
    public UserLoginInfo(string loginProvider, string providerKey, string? displayName)
    {
        LoginProvider = loginProvider;
        ProviderKey = providerKey;
        ProviderDisplayName = displayName;
    }

    /// <summary>
    /// Gets or sets the display name for the provider.
    /// </summary>
    /// <value>
    /// The display name for the provider.
    /// </value>
    /// <remarks>
    /// Examples of the display name may be local, FACEBOOK, Google, etc.
    /// </remarks>
    public string? ProviderDisplayName { get; set; }

**Comment by adityamandaleeka** [comment]
If you want to fix this, we'd accept a PR that unifies the comments.
