### ISSUE TITLE
Cannot obtain windows account in blazor server using smart card authentication 

### ISSUE THREAD

**Issue by lockbox23** [dotnet/aspnetcore#41285]
I'm using the code below in blazor server on IIS with only Windows authentication enabled, SSL required and accept client certificates.

If I log in with username/password, { user.identity.name  } will display **domain\username**. If I log in using a smart card, { user.identity.name  } will display **first** and **last** name, but not from the user's domain account. 

I had to add the certificate authentication services in program.cs, otherwise the user will not be authenticated and will endlessly be prompted to enter a pin number. Without the certificate authentication services, "The user is not authenticated."

1. If the user is authenticated, why is the value of user.identity.name not domain\username?
2. Where is it pulling the first and last name from? The certificate? On the domain controller, I changed the user's full name to **first3 last3**, display name to **first2 last2**, and first and last name to **first1** and **last1**.   { user.identity.name  } displays **first last** without any numbers. 

I've tried several HttpContextAccessor.HttpContext.User codes samples I could find, and those also don't return domain\username. It's either blank, generates an error, or displays **first last**.

I read somewhere that access to UserManager was depreciated. Is that correct? 

Is there another way to get the windows account that was used to log in/authenticate? Preferably with domain? Any help would be appreciated. Thanks!! 

Index.razor
```
protected override async Task OnInitializedAsync() 
{  
    var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();  
    var user = authState.User;  
    if (user.Identity.IsAuthenticated)  
    {
        userAuthenticated = $"{ user.Identity.Name} is authenticated.";
    }  
    else  
    {  
        userAuthenticated = "The user is NOT authenticated.";  
    }
}
```

program.cs
```
builder.Services
    .AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
    .AddCertificate(options =>
    {
        options.AllowedCertificateTypes = CertificateTypes.All;
    });
```

**Comment by Tratcher** [comment]
Certificate auth populates the identity with the information contained in the certificate. It does not map the certificate to a domain account to fetch details, that's something you'd have to add in the cert auth events by directly contacting the domain using System.DirectoryServices and asking it about the user identified by the cert.

**Comment by lockbox23** [comment]
@Tratcher  Thanks for replying! You've answers both of my questions, but I'm not happy with the answers. lol

> Certificate auth populates the identity with the information contained in the certificate.

That's interesting. I disagree that certificate auth should be populating  { user.Identity.Name } with the info in the certificate. Cert info can be obtained via this code:

```
options.Events = new CertificateAuthenticationEvents
{
    OnCertificateValidated = context =>
    {
        var claims = new[]
        {
            new Claim(
                ClaimTypes.Name,
                context.ClientCertificate.Subject,
                ClaimValueTypes.String, context.Options.ClaimsIssuer)
        };

        context.Principal = new ClaimsPrincipal(
            new ClaimsIdentity(claims, context.Scheme.Name));
        context.Success();

        return Task.CompletedTask;
    }
};
```
> It does not map the certificate to a domain account to fetch details, that's something you'd have to add in the cert auth events by directly contacting the domain using System.DirectoryServices and asking it about the user identified by the cert.

Ugh! Just to clarify, by directly, you mean doing an LDAP query, right?

Windows/IIS/Blazor server authenticated the user, so it already knows what domain account is tied to the certificate. If { user.Identity.Name } can be populated with the domain account when using a username and password, why can't it populate { user.Identity.Name } with the domain account when using a certificate? Or populate something like { user.Identity.**Account** } ?

**Comment by Tratcher** [comment]
> Windows/IIS/Blazor server authenticated the user, so it already knows what domain account is tied to the certificate. If { user.Identity.Name } can be populated with the domain account when using a username and password, why can't it populate { user.Identity.Name } with the domain account when using a certificate? Or populate something like { user.Identity.**Account** } ?

> so it already knows what domain account is tied to the certificate

No, it doesn't, that association is only known by the client and the domain controller. The server only knows that the certificate is valid, we don't know that it represents a user on the domain controller. Client certs can be issued from many sources, they're self-contained identities. If you expect all of your client certs represent users on the domain controller then you need to do that extra LDAP lookup to verify that.

**Comment by lockbox23** [comment]
Got it. Thanks!
