### ISSUE TITLE
Dispose httpclient in IIS tests

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#41281]
We can speed up the tests by disposing the httpclient

Context: https://github.com/dotnet/aspnetcore/pull/41271#discussion_r854280037

**Comment by Tratcher** [comment]
There was a regression in IIS in the Win10 timeframe where IIS won't stop the site until the client closes the connections. People keep claiming it doesn't exist, has aways existed, or has been fixed, and not much progress has been made on a real investigation. https://github.com/dotnet/aspnetcore/issues/25107

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/41283
