### ISSUE TITLE
#40786 reopened: Blazor InputNumber and InputDate components fail to compile on .NET 7 Preview 3

### ISSUE THREAD

**Issue by sevinul** [dotnet/aspnetcore#41296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

#40786 reopened: In .NET 7 Preview 3 Visual Studio 2022 is not accepting blazor InputNumber and InputDate components.

Compiling the code piece below in a blazor component will cause a not specified error in the RazorSourceGenerator, hence the project will fail with the error: "Type or namespace name 'Blazor1' was not found":

        <InputNumber 
            @bind-Value=@someValue 
            @oninput=@SomeMethod />

The same happens with InputDate. InputCheckbox and InputText will compile ok.
This behaviour did not occur with .NET 7 Preview 1.

As the compiler did not point to the failing blazor component in a large project source the problem was hard to identify within a time consuming trial and error session.

Best regards
Sevin Ulukut

### Expected Behavior

The code above should compile OK.

### Steps To Reproduce

https://github.com/sevinul/BlazorApp1 illustrates the problem. It is a standard blazor client with lines 11-26 added to Pages/index.razor .

### Exceptions (if any)

Type or namespace name 'Blazor1' was not found

### .NET Version

7.0.100-preview.3.22179.4

### Anything else?

Visual Studio 2022 Version 17.2.0 Preview 3.0

**Comment by javiercn** [comment]
@sevinul thanks for contacting us.

This is a known issue in preview3, I believe it was addressed in preview4, but just in case, I tried the nightly bits (preview5) and it seems to be fixed.

```
    <InputNumber 
        @bind-Value=@someValue 
        @oninput=@SomeMethod />

@code{
    private int someValue;
    private void SomeMethod(ChangeEventArgs args)
    {
        
    }
}
```

![image](https://user-images.githubusercontent.com/6995051/164458587-d4842037-364d-4c86-a2f1-d75c6a3724b3.png)

**Comment by sevinul** [comment]
Thanks a lot☺️
