### ISSUE TITLE
Why is this issue still not planned to fix, it is almost mid of 2022? What heck is stopping it to do? If not then what is alternate to support ssrs reports in .net core 3, 5 or 6?

### ISSUE THREAD

**Issue by usmanaliabbasse** [dotnet/aspnetcore#41298]
Thanks for contacting us. This is not something we plan to do.

_Originally posted by @mkArtakMSFT in https://github.com/dotnet/aspnetcore/issues/22304#issuecomment-635489199_

**Comment by javiercn** [comment]
@usmanaliabbasse thanks for contacting us.

Our team doesn't own SSRS nor similar technologies. There are a number of alternative third-party and open source reporting solutions that we believe cover this scenario.

I would bring this question to the SQL Server team via their user voice channel [here](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0), we only work on the framework components and functionality like this is not something we would work on.

I understand that this might not be what you expect or want to hear, however I hope it is clear that this type of features is not something that the .NET team is directly involved in and as such, there's not much we can do but to suggest you raise this feedback through the appropriate channels.
