### ISSUE TITLE
Suggested workaround for lack of Blazor WASM log scopes

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#41300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It looks like `BeginScope` is callable from an `ILogger` in a Blazor WASM app, but it looks like there isn't a config for `IncludeScopes`. I tried via confg from an `appsettings.json` file (per [our guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-6.0#logging-configuration)) and looked for the C# property but didn't see it. It looks like it's a no-op for WASM. I also didn't find anything in the ref source indicating that log scopes work in WASM apps.

If that's not correct, how is `IncludeScopes` enabled in WASM so that `BeginScope` will work?

If it is a no-op, can I recommend to devs in our WASM logging doc that they can create a custom `ILoggerProvider` to get log scopes? I'm ***not*** going to show it in a doc. I'm merely going to say that log scopes aren't supported in WASM apps and recommend that they create a custom logger and refer them to the custom logger section of the doc for an (unrelated) example.

### Expected Behavior

`Pages/Counter.razor`:

```razor
@page "/counter"
@inject ILogger<Counter> logger

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        logger.LogInformation("Someone has clicked me!");

        using (logger.BeginScope("Custom Log Scope"))
        {
            logger.LogInformation("Someone has clicked me!");
            logger.LogInformation("Yes! I was clicked!");
        }

        logger.LogInformation("Someone has clicked me!");

        currentCount++;
    }
}
```

... where I'd like to see the log scope indicated. However, the log scope isn't indicated. The dev tools console output is merely ...

> info: BlazorSample.Pages.Counter[0]
> Someone has clicked me!
> info: BlazorSample.Pages.Counter[0]
> Someone has clicked me!
> info: BlazorSample.Pages.Counter[0]
> Yes! I was clicked!
> info: BlazorSample.Pages.Counter[0]
> Someone has clicked me!

### Exceptions (if any)

None ... but it no-ops for log scopes.

Ordinarily, I'd assume that `IncludeScopes` is defaulting to `false`, but I don't see how to set that in a WASM app.

### .NET Version

6.0.300-preview.22204.3

**Comment by javiercn** [comment]
@guardrex I don't think our console logger support scopes.

**Comment by guardrex** [comment]
Ok, thanks. I'll recommend a custom logger then. I think that would work 🤞.
