### ISSUE TITLE
Update Microsoft.AspNetCore.ApiAuthorization.IdentityServer dependencies (Duende.IdentityServer)

### ISSUE THREAD

**Issue by marcoatribeiro** [dotnet/aspnetcore#41315]
Currently Microsoft.AspNetCore.ApiAuthorization.IdentityServer depends on Duende.IdentityServer version 5.2.0, but version 6.0.4 is available.
This outdated dependency is causing versioning conflict of other dependencies (e.g. AutoMapper).

**Comment by adityamandaleeka** [comment]
@blowdart

**Comment by HaoK** [comment]
Talked to @blowdart offline, plan will be to update the versions to 6.0, and document in the 7.0 readme the potential dataschema issues that users may run into: https://docs.duendesoftware.com/identityserver/v6/upgrades/v5.2_to_v6.0/

Something like: "We're updating to the latest supported Identity Server in our extensions. Either don't use the extensions and use their configuration methods or update your schema and use our helpers""

**Comment by HaoK** [comment]
Keeping this open to track both the docs and updating to 6.1

**Comment by HaoK** [comment]
We decided on sticking with 6.0.4 for 7.0 due to 6.1 having a database schema update https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.0_to_v6.1/
