### ISSUE TITLE
Blazor webassembly App: Cannot call unknown function mono_wasm_set_is_debugger_attached, make sure it is exported

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41324]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-webassembly-App:-Cannot-call-unkn/10019177)._

---
[severity:I'm unable to use this version]
I have a Blazor Web assembly app.
In debug mode I do not have any issue.
However, in release mode I get the following:
From Visual  Studio 2022 Debug output I get the following:
Loaded 14.75 MB resources from cache
Loaded 0.08 MB resources from network
Assertion failed: Cannot call unknown function mono_wasm_set_is_debugger_attached, make sure it is exported

From Google Chrome debug console:
Assertion failed: Cannot call unknown function mono_wasm_set_is_debugger_attached, make sure it is exported
window.Module.s.printErr @ blazor.webassembly.js:1
abort @ dotnet..d9oeubh791.js:1
assert @ dotnet..d9oeubh791.js:1
getCFunc @ dotnet..d9oeubh791.js:1
ccall @ dotnet..d9oeubh791.js:1
(anonymous) @ dotnet..d9oeubh791.js:1
mono_wasm_get_loaded_files @ dotnet..d9oeubh791.js:1
(anonymous) @ VM55:1
mono_wasm_runtime_ready @ dotnet..d9oeubh791.js:1
(anonymous) @ blazor.webassembly.js:1
callRuntimeCallbacks @ dotnet..d9oeubh791.js:1
postRun @ dotnet..d9oeubh791.js:1
doRun @ dotnet..d9oeubh791.js:1
run @ dotnet..d9oeubh791.js:1
runCaller @ dotnet..d9oeubh791.js:1
removeRunDependency @ dotnet..d9oeubh791.js:1
h @ blazor.webassembly.js:1
await in h (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
callRuntimeCallbacks @ dotnet..d9oeubh791.js:1
preRun @ dotnet..d9oeubh791.js:1
run @ dotnet..d9oeubh791.js:1
runCaller @ dotnet..d9oeubh791.js:1
removeRunDependency @ dotnet..d9oeubh791.js:1
receiveInstance @ dotnet..d9oeubh791.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
window.Module.s.instantiateWasm @ blazor.webassembly.js:1
createWasm @ dotnet..d9oeubh791.js:1
(anonymous) @ dotnet..d9oeubh791.js:1

---
#### Feedback Bot on 4/21/2022, 01:15 AM: 

(private comment, text removed)
#### Denis Ruffo on 4/21/2022, 09:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please specify how exactly you're running the app without the debugger? Ctrl+F5 should be it. And in that case there should be no messages in the debug window when the app starts.
