### ISSUE TITLE
W3CLogging file rotation seems to be deleting files out of order

### ISSUE THREAD

**Issue by dustinsoftware** [dotnet/aspnetcore#41326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Use `dotnet new webapi` to create a new .NET 6 app on macOS or Linux. I haven't tested if this is happening on Windows too.

```
builder.Services.AddW3CLogging(options =>
{
    options.LogDirectory = "/olo/logs/http/loggingtest";
});
app.UseW3CLogging();
```

Restart the app 5 times. Note that each time the app restarts, a new file is created with an incrementing number starting with 0000.

After the fifth attempt, `w3clog-20220422.0000.txt` gets deleted, and `w3clog-20220422.0004.txt` gets created.

Restart the app another time. Note that this time, no new file is created, and logging stops happening for any future requests.

Setting a breakpoint in RollFiles indicates that the log counter is starting over at `0000`, but then immediately deleting the created file.  

<img width="946" alt="Screen Shot 2022-04-22 at 3 03 25 PM" src="https://user-images.githubusercontent.com/942358/164778046-cdc88f6c-38e5-4e10-9dd5-2ab02082bf7c.png">

I'm happy to PR a fix if it's confirmed as a bug.

### Expected Behavior

File based w3c logging does not stop when the app restarts several times within the same day.

### Steps To Reproduce

Clone this repo and launch the app 6 times: https://github.com/dustinsoftware/logging-demo/blob/4780c75f3f69626382b809d306353d33461b328b/Program.cs#L9

### Exceptions (if any)

No exceptions or warnings that this is happening.

### .NET Version

6.0.101

### Anything else?

We noticed this issue on both macOS and Linux .NET 6 runtimes.

**Comment by wtgodbe** [comment]
This is (almost) the expected behavior - W3CLoggerProcessor won't do anything on startup if its log directory is already full (it does know how to delete old files when it hits its max file count while already executing, but we don't want to assume a user is OK with us deleting pre-existing files on startup if the directory is already full). There _is_ an off-by-1 error here in that it should have stopped logging after the 4th attempt - this line should be `if (_fileNumber >= W3CLoggerOptions.MaxFileCount - 1)`

https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L162

We'd gladly accept a PR for this if you want to make one, otherwise a team member will fix it for preview5.

If you want to keep more files, increase `W3CLoggerOptions.RetainedFileCountLimit`: https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/W3CLoggerOptions.cs#L37-L53

If you feel strongly that the behavior should be different, we'd consider changing it in the .net 7 time frame.

**Comment by dustinsoftware** [comment]
To give a bit more context for what we are seeing:

MaxFileCount is 10000: https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/W3CLoggerOptions.cs#L17
RetainedFileCount is 4 https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/W3CLoggerOptions.cs#L12

In our application, the web API is very high throughput and has a sidecar service that shuttles these logs off to an external long-term storage service within a few seconds of being written to disk. It's plausible that, within a single day, we'll reach the RetainedFileCountLimit (4 by default it looks like). What we'd like is:

1. When rolling logs, the app deletes the oldest log file written to disk, right after a new log file is created
2. On restart, the file counter does not restart at 0

For 1, the app already behaves like this today as long as an app restart does not occur. The restarts are what are currently problematic for our use case (we have a CI job that deploys the app at several times per day to the same server)

For 2, because the counter is reset to 0, this affects RollFiles since it tries to delete what it thinks is the oldest file, since it's sorting by name.

https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L279-L282

RollFiles appears to be using `maxRetainedFiles` to control how many old log files to remove.

We're testing a fix internally by setting:

```
    private long _fileNumber = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
```

This produces a file name similar to `w3clog-20220422.1650663997.txt`. I'm not sure ergonomically if this is a problem since the old logs used an incrementing number, and if this would be a surprising change to folks migrating to .NET 7. Maybe it's fine?

Alternatively we could loop over all the log files and increment the counter by one more than the max number found in the file names, but are unsure about the safest way to do that (we'd need some logic to ignore junk filenames in that folder). If the newest file was  `w3clog-20220422.0005.txt`, the next log would be  `w3clog-20220422.0006.txt`. The timestamp approach seems like a reasonably safe way to do that while not changing the sort order used in RollFiles (maybe we need to render leading zeroes to be extra sure).

If using a timestamp in the log name, we could also sort by `CreatedDate` instead of `Name`. However, we could not make that change while the file counter initializes at 0 during app start.
 https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L281

**Comment by wtgodbe** [comment]
We'd like to avoid changing the file name structure if possible.

> Alternatively we could loop over all the log files and increment the counter by one more than the max number found in the file names, but are unsure about the safest way to do that (we'd need some logic to ignore junk filenames in that folder). If the newest file was w3clog-20220422.0005.txt, the next log would be w3clog-20220422.0006.txt. The timestamp approach seems like a reasonably safe way to do that while not changing the sort order used in RollFiles (maybe we need to render leading zeroes to be extra sure).

This is what `FileLoggerProcessor` already does today: https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L151-L171

> RollFiles appears to be using maxRetainedFiles to control how many old log files to remove.

This is true, and `maxRetainedFiles` is equal to `loggerOptions.RetainedFileCountLimit`, which is configurable:

https://github.com/dotnet/aspnetcore/blob/bcdb13d1f2e42f2d318ead75e5e86fc27c78a117/src/Middleware/HttpLogging/src/FileLoggerProcessor.cs#L61

You should be able to get around this problem by increasing `RetainedFileCountLimit`

```
        services.AddW3CLogging(logging =>
        {
            // Log all W3C fields
            logging.RetainedFileCountLimit = 1000;
        });
```

**Comment by dustinsoftware** [comment]
You are correct that setting the retained file count to 1000 allows logging to continue since files won’t roll unless the process restarts 1000 times within a single day. 

I’ll do some experimenting tomorrow to see if we can determine the correct value for _fileNumber when the process restarts. Would you look at a PR that, upon app start, loops over the file names and attempts to safely parse the number segment after the date part?

Eg if the log folder contains 03 and 04, upon next app start the counter would begin at 05.txt
