### ISSUE TITLE
Need report exception when model deserialize failed

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#41322]
I have this model:
```c#
class Foo
{
    DateTime Date {get;set;}
}
```

When client post a body like this:
`{"Date":""}`

The handler got a `null`, I want a `exception`:
```c#
void OnPost([FromBody] Foo foo)
{
    // foo is null, I need a exception
}
```

Please help.

**Comment by rafikiassumani-msft** [comment]
@ahdung Can you provide some more context to help us guide you?

1. Which version of .NET are you using? 
2. Do you have nullability enabled in your project?
3. Is your intent to be able to see the exception within the `OnPost` method? Or are you just looking for better ways to validate your model properties? 
4. Have you looked at the following document? https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0

**Comment by ahdung** [comment]
@rafikiassumani-msft Thanks for your response.
1. `.net 6.0` asp.net core web application
2. No
3. I hope got a deserialize exception in the log.
4. Yes.

Note this issue happend in Razor page model handler, not `ApiController`, `ApiController` always response 400 when model invalid, it never give a `null` into `Action`. There are some picture:

![微信截图_20220427170250](https://user-images.githubusercontent.com/12094247/165485134-b7e11908-9f04-42f7-a1d9-bc67f7930d3a.png)

![微信截图_20220427170342](https://user-images.githubusercontent.com/12094247/165485265-9ba6600a-4b06-491e-8408-8cebfc20533f.png)

**Comment by captainsafia** [comment]
> Note this issue happend in Razor page model handler, not ApiController, ApiController always response 400 when model invalid, it never give a null into Action. There are some picture:

This is expected behavior. The rules for validating the request body are different for controllers and Razor pages because the two are intended for different scenarios. We recommend either:

- Moving your logic to an ApiController instead of a Razor page so you can take advantage of the built-in validation rules
- Leveraging a filter to validate the request body before the request makes it to your Razor page

**Comment by ahdung** [comment]
@captainsafia I don't understand what makes you think that in the razor page, when the model deserialization fails, you should pass `null` into the method? Does `null` make any sense?
