### ISSUE TITLE
NullReference exception when evaluating JS

### ISSUE THREAD

**Issue by fairking** [dotnet/aspnetcore#41339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having the following code I would like to evaluate a javascript inside the BlazorWebView. Unfortunately I get an NullReferenceException:
``` c#
public partial class MainPage : ContentPage
{
    public MainPage()
    {
	InitializeComponent();
    }

    private async void button_Clicked(object sender, EventArgs e)
    {
	var js = webView.Handler.MauiContext.Services.GetService<IJSRuntime>();
	var result = await js.InvokeAsync<string>("executeMe", "DEF");
	Debug.WriteLine(result);
    }
}
```

``` html
    <script type="text/javascript">
        window.executeMe = (a) => {
            console.log("Call: " + a);
            return a + " OK!";
        };
    </script>
```

Error:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.Components.WebView
  StackTrace:
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime.BeginInvokeJS(Int64 taskId, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at MauiApp1.MainPage.<button_Clicked>d__1.MoveNext() in C:\Code\MauiApp1\MauiApp1\MainPage.xaml.cs:line 17

  This exception was originally thrown at this call stack:
    [External Code]
    MauiApp1.MainPage.button_Clicked(object, System.EventArgs) in MainPage.xaml.cs
```

### Expected Behavior

I expect the javascript function should return the string "DEF OK!".

### Steps To Reproduce

- Download the project here [MauiApp1.zip](https://github.com/dotnet/aspnetcore/files/8547616/MauiApp1.zip) or from [repo](https://gitlab.com/fairking/mauiblazorwebview). 
- Run in VS. 
- Run debugger in Windows Mode.

### .NET Version

6.0.300-rc.1.5355

### Anything else?

[MauiApp1.zip](https://github.com/dotnet/aspnetcore/files/8547616/MauiApp1.zip)

**Comment by TanayParikh** [comment]
@fairking, could you please provide the repro app as a public github repository?

**Comment by fairking** [comment]
Sure, please give me a moment

**Comment by TanayParikh** [comment]
Oh I see what's going on here, you're trying to use the JSInterop outside of a component. That isn't currently supported.https://github.com/dotnet/maui/issues/5804

**Comment by fairking** [comment]
I cannot understand why it's not possible. Isn't `BlazorWebView` inherited from `WebView` which always had a method called `EvaluateJavaScriptAsync` ??

**Comment by fairking** [comment]
> Oh I see what's going on here, you're trying to use the JSInterop outside of a component. That isn't currently supported. Duplicate of [dotnet/maui#5804](https://github.com/dotnet/maui/issues/5804)

Thank you. I appreciate you quick reply 👍

**Comment by fairking** [comment]
It's not building on Android ;-(

**Comment by fairking** [comment]
![image](https://user-images.githubusercontent.com/13495631/164946867-e6404c0a-32b7-4d06-ac47-752910cdde1c.png)

**Comment by TanayParikh** [comment]
> ![image](https://user-images.githubusercontent.com/13495631/164946867-e6404c0a-32b7-4d06-ac47-752910cdde1c.png)

Hmm don't think I've seen that error before. If you're still having it, please create a new issue in the `dotnet/maui` repo.
