### ISSUE TITLE
Change 'http' to 'https' in the HttpRequestsComponent.razor example

### ISSUE THREAD

**Issue by JeepNL** [dotnet/aspnetcore#41346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Config: Blazor WASM,  ASP.NET 7 preview 3

In the example here : https://github.com/dotnet/aspnetcore/blob/7c1e6d553209741f615628a8fbe3d7d09c0c43b0/src/Components/test/testassets/BasicTestApp/HttpClientTest/HttpRequestsComponent.razor

you'll get the error: "Failed to fetch" with the default URL `string? uri = "http://api.icndb.com/jokes/random";` because it should be 'https' (https://api.icndb.com/jokes/random).

### Expected Behavior

Return a JSON response from the http(s)://api.icndb.com/jokes/random API

### Steps To Reproduce

Run the code: https://github.com/dotnet/aspnetcore/blob/7c1e6d553209741f615628a8fbe3d7d09c0c43b0/src/Components/test/testassets/BasicTestApp/HttpClientTest/HttpRequestsComponent.razor

### .NET Version

.NET 7 preview 3

**Comment by mkArtakMSFT** [comment]
Thanks for catching this, @JeepNL.
Would you like to send a PR to address this? We'd appreciate it.
