### ISSUE TITLE
Use interned strings in Hub protocol implementations

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#41342]
## Background and Motivation

Looking at profiles for one of my SignalR applications I see lots of string allocations showing up and most of them seem to come from the protocol implementation:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/95136/164957053-2766d670-daff-4f93-bf9b-c7a3d4294ac3.png">

It's:
- Hub method names
- ~Invocation ids~ Not worth it unless we could optimize the number path and never allocate them.

We end up invoking these methods over and over and allocating the same strings for both invocation ids (numbers in our clients) and for hub method names (which are known at startup).

We should be using cached strings for these. Right now we don't have a clean extensibility model to inject this behavior. Maybe we can add something to the options.

## Proposed API

```diff
namespace Microsoft.AspNetCore.SignalR;

public interface IInvocationBinder
{
+ #if NETCOREAPP
+    string? GetTarget(ReadOnlySpan<byte> utf8Bytes) => null;
+ #endif
}
```

## Usage Examples

Called by SignalR protocols to get the cached hub name from the binder (if there exists any).

## Alternative Designs

An alternative would be a new interface that can be optionally implemented on the `IInvocationBinder`:

```class
public interface ITargetResolver
{
    string? GetTarget(ReadOnlySpan<byte> utf8Bytes);
}
```

## Risks

None

**Comment by davidfowl** [comment]
To support this, we need to add a new API:

**Comment by halter73** [comment]
API Review Notes:

- Why cross compile? DIMs.
- Do we like a new interface to support netstandard2.0? No, it's hard to discover and perf-sensitive libs should cross-compile.

Approved as proposed:

```diff
public interface IInvocationBinder
{
+ #if NETCOREAPP
+    string? GetTarget(ReadOnlySpan<byte> utf8Bytes) => null;
+ #endif
}
```
