### ISSUE TITLE
Razor binding in button isnt displayed

### ISSUE THREAD

**Issue by Hu1buerger** [dotnet/aspnetcore#41357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A binding in a razor component to into a html button isnt displayed.

### Expected Behavior

the rendered button should contain the bound string.

### Steps To Reproduce

1. create a `dotnet new blazorserver -o BlazorApp --no-https -f net6.0` as described in [quickstart guide](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create)
2. create a blazor component

```csharp
//blazor component
<button>NEXT @{ State.ToDisplayString();}</button>

@code{
  [Parameter]
  public FilterState State {get; set;} = FilterState.INCLUDE;
}
```

3. create the model

```csharp
public enum FilterState
{
    INCLUDE,
    EXCLUDE,
    IGNORE
}

public static class FilterStateExtension
{
    public static string ToDisplayString(this FilterState fs)
    {
        return "Test";
        return fs.ToString();
        switch (fs)
        {
            case FilterState.INCLUDE:
                return "Include";
                //return @"\U+2227"; //Logical and
            case FilterState.EXCLUDE:
                return "Exclude";
                //return @"\U+00AC"; // Logical not
        }
    }
}
```

4. Include the Component into a page and display it.

## Now find

The button will always be rendered with `NEXT` but should be atleast `NEXT Test`.

### .NET Version

6.0.201

### Anything else?

$dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /Users/user/.dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/Users/user/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/Users/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/Users/user/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by TanayParikh** [comment]
Hello @Hu1buerger, please try:

```
<button>NEXT @State.ToDisplayString()</button>
```

does that resolve your issue?

**Comment by Hu1buerger** [comment]
@TanayParikh why would @{} not work as it afaik is just the long version of @ .

Therefore it should behave similarly.

And it doesn't seem to work
