### ISSUE TITLE
Azure App Services: consider grabbing environment variable when using InsertOrAppend

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#4136]
@glennc @Tratcher 

Currently if you add `DOTNET_ADDITIONAL_DEPS` or `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` as environment variables in the Azure Portal they are ignored if you have `Microsoft.AspNetCore.AzureAppServices.SiteExtension` enabled (which is on by default) because `InsertOrAppend` doesn't look at environment variables when inserting/appending

**Comment by muratg** [comment]
Moving out since preview2 already shipped.

**Comment by Eilon** [comment]
@glennc / @tratcher / @BrennanConroy - is there any work required here? What doesn't work? Where would the fix go?

**Comment by Tratcher** [comment]
It's a conflict between site extensions trying to set the same environment variables. I don't know how many of those we're still using. Any fix would likely be in https://github.com/aspnet/AspNetCore/tree/master/src/SiteExtensions/Microsoft.Web.Xdt.Extensions/src

**Comment by Eilon** [comment]
Thanks @Tratcher .

@anurse - is SiteExtension in an area you own? What `area-` label should it be? And, any thoughts on the importance of this issue?

**Comment by anurse** [comment]
I guess? I'd say `servers` is probably most appropriate.

**Comment by anurse** [comment]
Or maybe installers... we'll play with it.

**Comment by anurse** [comment]
I need a little more context on this issue. Will sync with @Tratcher and @BrennanConroy

**Comment by anurse** [comment]
Queuing this for re-triage. There's no customer report yet.

**Comment by JunTaoLuo** [comment]
We're closing this as stale since there hasn't been any traffic on this issue and it's been many years since it was originally opened.

**Comment by Tratcher** [comment]
Re-opening due to a customer report via support.

**Comment by dougbu** [comment]
@Tratcher why did you reopen this❔ @BrennanConroy if it should be open, what bucket should it be in❔ `area-infrastructure` doesn't seem right&hellip;

**Comment by Tratcher** [comment]
Moved to area-servers.

This was re-opened because we had the same issue reported through MS support. They're currently evaluating workarounds, but if that's not viable then we'll need to provide a fix.

**Comment by davidfowl** [comment]
Who should this be assigned to?

**Comment by davidfowl** [comment]
@shirhatti we should switch to a Startup hook here.

**Comment by dougbu** [comment]
This issue has been sitting for a while since @davidfowl suggested something that sounds like it should work. Could we get an assignee at least❔

Should switching to a Startup hook be considered `feature-installers`❔

**Comment by Tratcher** [comment]
@dougbu the issue is in the backlog, is there something that would make us reconsider that? The customer has not reported back after being given a workaround back in January.

**Comment by dougbu** [comment]
@Tratcher I was mostly double-checking whether @davidfowl's [comment](https://github.com/dotnet/aspnetcore/issues/4136#issuecomment-808932245) changed anything. If not, fine to leave as-is.

Separately, I remain unsure about using `feature-installers` for a bug about adding a Startup hook&hellip;
