### ISSUE TITLE
SignalR: Content-Type header in GET requests

### ISSUE THREAD

**Issue by jmajoor** [dotnet/aspnetcore#41378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WAF is flagging signalR long polling requests due to them having the Content-Type header on GET requests.

The issues was also report on the old code base: https://github.com/SignalR/SignalR/issues/4373

### Expected Behavior

There should be no content-type header for SignalR long polling GET requests.

### Steps To Reproduce

Use a long polling TypeScript client to communicate to a signalR hub.
Inspect the long polling requests in the developer tools of the browser and you see that the GET requests have a content type set.
"Content-Type": "text/plain;charset=UTF-8",

### .NET Version

.NET 6

### Anything else?

Ideally I would like to see POST requests and then also move the access token from the query string to the body of the request.

**Comment by casmrv** [comment]
This has also been reported previously against asp.net.
Given that signalr long polling frequently ends up being the fallback due to network complexities, it would be good to get this fixed.

**Comment by BrennanConroy** [comment]
We accept PRs 😃 

This one should be fairly straightforward; my biggest concern is that react-native on android should be tested to make sure we don't break it again, as the addition of the header was made for that scenario.

**Comment by davidfowl** [comment]
> Ideally I would like to see POST requests and then also move the access token from the query string to the body of the request.

Not following this one. File a new issues and describe why, I'm not understanding the reasoning here.
