### ISSUE TITLE
OpenIdConnect Access Token Claims

### ISSUE THREAD

**Issue by emanuel-v-r** [dotnet/aspnetcore#41385]
When using OpenIdConnect Authentication handler, I've noticed that it only adds to User.Claims the claims that are present in the id_token, and therefore it doesn't add the claims that are present in the access_token.
Is this expected? Can it be configured somehow?
Thanks

**Comment by blowdart** [comment]
Access tokens are opaque strings which are meant to be sent without interpreting it. Picking it apart would make no sense, even if it were in a format we would be sure of understanding. As it's opaque it may not contain claims at all, it may just be a guid.
