### ISSUE TITLE
.NET 6 application sometimes loading incorrect appsettings.{environment}.json

### ISSUE THREAD

**Issue by urielzen** [dotnet/aspnetcore#41381]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a .NET 6.0 application deployed to Azure App Service.

I have the following appsettings in my root.

`appsettings.development.json`
`appsettings.PROD.json`

and the following setting in the Azure Portal App Service
![image](https://user-images.githubusercontent.com/7947179/165384944-cfeeaa60-cb28-4392-8a6a-e3c9d412107f.png)

I know the ASPNETCORE_ENVIRONMENT variable is loaded correctly because for most scenarios the app uses the variables from the `appsettings.PROD.json`. But there was an edge case in the application when it loaded a variable from the `appsettings.development.json` instead of from `PROD`.

The variables in question are the following:

from the `appsettings.development.json`
![image](https://user-images.githubusercontent.com/7947179/165385557-5e6fb602-01f6-4673-8c0d-49ac0e33ad6f.png)

from the `appsettings.PROD.json`
![image](https://user-images.githubusercontent.com/7947179/165385776-e2aa22a1-f5ff-4f33-be30-f2cc402153aa.png)

for explanation purposes, lets assume that the url in the `ReferencePageBaseUrl` for `PROD` is `https://contoso.com/reference/`

There are no environment variables in the Azure App Service configuration overwriting the ones above.

These settings are used to send some emails in a background service that implements `Microsoft.Extensions.Hosting.BackgroundService`

```csharp
public class AutomatedReferenceRequestBackgroundService : BackgroundService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly AutomatedReferenceRequestSettingsOptions _automatedReferenceRequestSettings;
    private readonly EmailNotificationSettingsOptions _emailNotificationSettings;
    private readonly ILogger<AutomatedReferenceRequestBackgroundService> _logger;
    private const string _refRequestPrefix = "CredentialRefRequest";
    public AutomatedReferenceRequestBackgroundService(
         IServiceScopeFactory scopeFactory
        , IOptions<AutomatedReferenceRequestSettingsOptions> automatedReferenceRequestSettings
        , IOptions<EmailNotificationSettingsOptions> emailNotificationSettings
        , ILogger<AutomatedReferenceRequestBackgroundService> logger
        )
    {
        _scopeFactory = scopeFactory;
        _automatedReferenceRequestSettings = automatedReferenceRequestSettings.Value;
        _emailNotificationSettings = emailNotificationSettings.Value;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await BackgroundProcessing(stoppingToken);
    }

    public override Task StopAsync(CancellationToken cancellationToken)
    {
        return base.StopAsync(cancellationToken);
    }

    private async Task BackgroundProcessing(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                while (true)
                {
                    bool isEmailsEnabled = _automatedReferenceRequestSettings.EmailsEnabled;
                    string refReqBaseURl = _automatedReferenceRequestSettings.ReferencePageBaseUrl;
                    string refReqEmailTemplateBaseURl = _automatedReferenceRequestSettings.ReferenceEmailTemplateFileName;

                    if (isEmailsEnabled)
                    {
                        var objReferenceRequests = await GetCredentialRequestReferenceQueueAsync(stoppingToken);

                        var subject = "Reference Request for ";

                        foreach (var referenceRequestsQueueItem in objReferenceRequests)
                        {
                            var emailMessage = @$"
                                <p>Hi {referenceRequestsQueueItem.RefName},</p>
                                <p>You have been listed as a reference for {referenceRequestsQueueItem.NameOfClinician}.</p>
                                <p>It would be greatly appreciated if you could answer a few questions by using the link below.</p>
                                <a target=""_a"" href=""{refReqBaseURl}{referenceRequestsQueueItem.CredentialExtID}"">
                                    Submit a Reference
                                </a>
                                <br>
                                <p>Thank you,</p>";

                            var referenceReqEmailTemplate = PopulateEmailTemplate(emailMessage, refReqEmailTemplateBaseURl);

                            await SendMailToReferenceAsync(referenceRequestsQueueItem.ReferenceRequestId,
                                                              referenceRequestsQueueItem.RefMailTo,
                                                              $"{subject}{referenceRequestsQueueItem.NameOfClinician}",
                                                              referenceReqEmailTemplate, isEmailsEnabled, stoppingToken);
                        }

                    }

                    await Task.Delay(_automatedReferenceRequestSettings.IntervalMilliseconds, stoppingToken);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while Background Processing Automated Reference Requests.");
            }
            finally
            {
                await Task.Delay(_automatedReferenceRequestSettings.IntervalMilliseconds, stoppingToken);
            }
        }
    }
}
```

Some code not included for brevity, but where I think the issue happens is at:
```csharp
 string refReqBaseURl = _automatedReferenceRequestSettings.ReferencePageBaseUrl;
```

Now looking at our email monitoring system I can see the following two emails were sent within a space of 1 minute

![image](https://user-images.githubusercontent.com/7947179/165393585-d4223d0f-5a22-4366-8fd8-b460a16adb17.png)

The emails body looks like this:
![image](https://user-images.githubusercontent.com/7947179/165393821-6333994b-1564-495e-afc2-8d5e263e7fbd.png)

And inspecting the html of the emails, the "Submit a Refence" link in one of the emails sends the user correctly to `https://contoso.com/reference/`. (The email with 09:51AM timestamp)

But the link in the other email (The email with 09:52AM timestamp) sends the user to `http://localhost:50190/reference/`, which is the variable for `appsettings.development.json`, but it should be the `PROD` one, like in the other email.

There were no code deployments nor any other configuration change in Azure during that 1 minute span from one email to the other.

More over, there were more emails after the 09:52AM one, and those had the correct link URL.
And other emails before the 09:51AM and those had the correct link URL as well. 
So just randomly the one at 09:52AM failed to pull the correct environment variable value.

![image](https://user-images.githubusercontent.com/7947179/165397348-72b696bd-ac16-42b6-a56e-83d5dca0dd40.png)

### Expected Behavior

The appsettings environment variables should always come from the corresponding environment consistently.

### Steps To Reproduce

I cannot reproduce this locally, but the email proof that this happens in PROD sometimes, is a big issue. Please help.

### .NET Version

6.0.202

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Tratcher** [comment]
AutomatedReferenceRequestBackgroundService is created and reads settings once at the start of the app. For the values to change and be re-read the application would have to restart.

The simplest explanation is someone changing the env var temporarily to debug something, restarting the site, and then changing it back and restarting again. Or deploying a parallel test instance. Do you see application logs to that effect?

**Comment by urielzen** [comment]
I am actually logging when the BackgroundService starts and ends, but I had removed that code from the pasted code in my original post for brevity.

Here is the original:
![image](https://user-images.githubusercontent.com/7947179/165409145-68a2ef28-42d3-4eed-a287-e61c768a7363.png)

And these logs are not found in the application logs anywhere close to the 09:51AM mark.

Additionally, no one else has access to Azure Portal to make changes to the environment variables or to restart the app.

In Azure Portal I can also see logs regarding app restart. Nothing close to 09:51AM

![image](https://user-images.githubusercontent.com/7947179/165410624-ed71d874-d7c1-4952-a0e7-7b301c11a6ed.png)

Opening the details of those logs shows that there were no variables changes either.

![image](https://user-images.githubusercontent.com/7947179/165410879-4da0339d-c220-48f0-895f-d8fcfdf709c6.png)

If I go a few more days in the past I can see that some environment variables were changed (by me) on 04/22, but nothing on 04/25

![image](https://user-images.githubusercontent.com/7947179/165412722-133c3773-5bc3-4d33-b072-ac2129a7db13.png)

I get that the IOptions pattern is only read once when the app starts. But according to the info above the issue was not due to a variable change nor an app restart.

**Comment by davidfowl** [comment]
Delete the development settings from prod and see what happens?

**Comment by urielzen** [comment]
Thank you all for your help, after more research I found out there was a developer testing in his local launchSettings with ASPNETCORE_ENVIRONMENT = PROD

...smh...

So the background service in his local was processing the productions data, in addition to that he had manually changed some other environment variables in his local appsettings.PROD.json file, including the issue with the URL in the emails.

Thanks again for your recommendations. It helped navigate in the right direction to find this issue.
