### ISSUE TITLE
Blazor navigation not work properly on Safari iOS latest

### ISSUE THREAD

**Issue by wizd** [dotnet/aspnetcore#41390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Navigation works on Safari macOS but not Safari iOS.

### Expected Behavior

Safari iOS should work like Safari macOS.

### Steps To Reproduce

Demo: https://app.lyra.live/ 
Re-produce: Up right corner tap the plus, then 'Scan' menu
Source: https://github.com/LYRA-Block-Lattice/LyraApp/blob/master/UserLibrary/Components/TopBarClient.razor

### .NET Version

6.0.300-preview.22204.3

### Anything else?

Dotnet 6.0.202
Visual Studio 2022

.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22204.3
 Commit:    4f23310c97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TanayParikh** [comment]
Hello @wizd, thanks for contacting us. Can you please clarify how exactly the behavior is different between safari on Mac and iOS? I tried your app and the scan to pay button seems to be working.
