### ISSUE TITLE
F# asp.net 5.x app broken after migration to 6.x

### ISSUE THREAD

**Issue by psantoro** [dotnet/aspnetcore#41398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an F# web app (Sdk="Microsoft.NET.Sdk.Web") that uses MVC, Razor runtime compilation, and Identity scaffolding.  It has worked fine in .net core 2.x - 5.x.  It no longer works correctly in .net 6.  I converted my fsproj file to .NET 6 as follows:

- changed TargetFramework to net6.0
- added `<IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion>`
- changed all MS.NET PackageReferences Versions from 5 to 6

The updated project builds without issue under .NET 6, but has the following notable issues at runtime:

- the overridden/scaffolded Identity code is not called (the default MS Identity code is called instead)
- many static files are not found

### Expected Behavior

I expected that after modifying the project file for .NET 6.x that the project would work as it did in prior .NET versions.

### Steps To Reproduce

I'm not able to submit the source code, but I've attached two log files.  The net5.txt log file is the application run under .net 5.x  The net6.xt log is the application run under .net 6.x.  Each log file is the result of the following user actions:

- load home page
- click link to login page
- click link to register page
- click link to home page

Note that the login and register pages are scaffolded/customized.

I also added one call to custom TRACING middleware in the .NET 6 version to log the following values:

ContentRootPath
WebRootPath

Note that the above values in the net6.txt log file appear to be correct.

When reviewing the net6.txt log, note the following:

- many static files yield HTTP GET "responded 404" log entries, note that the paths unexpectedly start with /Identity
- unlike the net5.txt log file, there are no "Invalidating compiled view at path" entries for /Areas/Identity/Pages/*

### .NET Version

6.0.202

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

[logs.zip](https://github.com/dotnet/aspnetcore/files/8574880/logs.zip)

**Comment by adityamandaleeka** [comment]
@HaoK Can you please take a look?

**Comment by HaoK** [comment]
@danroth27 @blowdart so what exactly is our story for F#, this is the first time I've tried F# with our templates, and when i tried creating an mvc app in F# on VS2022, although it did create a site, I didn't even get options for authentication/identity.  Is this supposed to work?

**Comment by HaoK** [comment]
There were some pretty big changes underneath the covers from 5.0 to 6.0 specifically to the static files and some of the identity UI plumbing.  I'm not sure how you generated your scaffolded files but is there an easy way for you to regenerate things from the 6.0 app instead of trying to migrate?  Without seeing more of your app/files, I'm not sure how much we can help you without a way to reproduce this

**Comment by psantoro** [comment]
@HaoK I created 2 .net 6 apps that demonstrate the MS Identity scaffolding issue that I'm seeing in my migrated .net 5.x F# app:

CSWEB APP (csharp)

1. created initial csweb app via `dotnet new mvc --auth Individual --use-local-db -lang=C#`
2. enable identity scaffolding via add-identity-to-proj6.bat script
3. generate identity pages that will be overriden
`dotnet aspnet-codegenerator identity --force --files "Account.Manage._ManageNav;Account.ConfirmEmail;Account.Register;Account.Login;Account.ResendEmailConfirmation"`
4. remove redundant Program.cs dbcontext code
5. mark identity login and register cshtml pages as **scaffolded** to easily verify that they are being used at runtime

FSWEB APP (fsharp)
1. created initial fsweb app via `dotnet new mvc -lang=F#`
2. manually copy over csweb Areas folder
3. manually add support for EF Core and MS Identity
4. manually modify views and wwwroot folders to match csweb
5. replaced Areas *.cs files with account.fs

If you follow the **Steps to Reproduce** user actions above, the CSWEB app works as expected (i.e. the Login and Register pages are marked as Scaffolded from the modified cshtml files).  The FSWEB application instead loads the default Login and Register pages which are not marked as Scaffolded.  This is the behavior that I saw after converting my .net 5.x F# app to .net 6.x.  I haven't been able to reproduce the static file path issue yet in a small sample, but I'll keep on working on that.

[csweb.zip](https://github.com/dotnet/aspnetcore/files/8586023/csweb.zip)
[fsweb.zip](https://github.com/dotnet/aspnetcore/files/8586025/fsweb.zip)

**Comment by psantoro** [comment]
@HaoK and @adityamandaleeka  I'm sorry, but I don't have time to create git repos for the uploaded zips.  It appears that [this .net 6.0 change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/razor-compiler-doesnt-produce-views-assembly) is likely behind the change in behavior(s) that I'm seeing.  If so, then perhaps a possible workaround might be to include the associated hidden/magic .net 6.0 csproj configuration(s) into fsproj files to create the _AspNetCoreGeneratedDocument_ namespace.

I'm currently refactoring the application to use [Giraffe](https://giraffe.wiki/) instead of ASP.NET MVC.  That will also allow me to replace the Razor stuff with [Giraffe's F# view engine DSL](https://giraffe.wiki/view-engine).  I only used ASP.NET MVC initially, because another developer had some _legacy ASP.NET MVC_ experience and I was trying to accommodate him.  My gut told me not to use OOP ASP.NET MVC and I should have listened.  A simpler dependency is almost always better than a more complicated one - especially when you don't control it.

**Comment by HaoK** [comment]
That change seems like it would be a likely culprit since that required a fair bit of plumbing on the identity ui side.  I assume you are no longer blocked if you are moving away from razor/mvc?

**Comment by psantoro** [comment]
@HaoK Yes, my initial testing indicates that I can use ASP.NET Identity without razor/mvc.  Unfortunately, it is effectively a rewrite of the application and will require significant backwards compatibility testing to ensure that I don't cause issues for any existing production users.

As a side note, it would be helpful if the default MS Identity scaffolding views/pages did not include developer comments/links, as they force developers to override those pages - just to get rid of those front-end visible comments/links.  That adds a lot of unnecessary work, as those pages must be monitored/updated with every ASP.NET release (i.e. due to possible MS bug/security fixes being applied to those overridden razor pages and associated back-end csharp logic).  I recommend including any developer comments/links into the default/scaffold  back-end logic csharp files instead of the front-end visuals (i.e. razor files).  At least that way, a default/scaffolding view/page can be used without any extra work, if only the associated back-end csharp logic needs to change.
