### ISSUE TITLE
Unstated build dependency for e2e tests + tests won't run

### ISSUE THREAD

**Issue by kg** [dotnet/aspnetcore#41408]
After following the steps to install prerequisites in https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md, ```dotnet test``` in the ```src/Components/test/e2etest``` folder failed with an error about 'selenium-standalone' not being a recognized command or batch file. It seems like the fix for this is to run ```npm install -g selenium-standalone```, so it seems like this is just a documentation change that needs to happen - or does this problem indicate that something else went wrong?

After installing this and the other deps (jdk, yarn, chrome) i'm still unable to run the e2e tests because of some sort of a selenium paths error:
```Error: Missing C:\users\kg\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\chromedriver\99.0.4844.35-x64\chromedriver```

It's not clear to me how to resolve this, do I need to install a specific revision of selenium-standalone? Is it broken because Chrome 100 and Chrome 101 rode the trains and 99.x chromedriver is out of date?

**Comment by kg** [comment]
I tried ```selenium-standalone install``` as suggested by https://github.com/webdriverio/selenium-standalone/blob/main/README.md#as-global-npm-package and while that makes ```selenium-standalone start``` work in my shell, I still get the 'missing ... chromedriver' error when running the tests :(

**Comment by kg** [comment]
```selenium-standalone install --singleDriverInstall=chrome --drivers.chrome.version=99.0.4844.35``` (based on https://github.com/webdriverio/selenium-standalone/blob/main/docs/CLI.md#command-line-interface) seems to have grabbed the correct chromedriver, but tests fail with another issue so I feel like there needs to be a README.md or equivalent in the e2etest folder explaining how you are meant to run the tests:

```
> selenium-standalone "start" "--config" "C:\\Users\\kg\\Documents\\Projects\\aspnetcore\\src\\Shared\\E2ETesting\\selenium-config.json" "--" "-port" "55086"
Was passed main parameter '-port' but no main parameter was defined in your arg class
Usage: standalone [options]
  Options:
    --allow-cors
<more lines snipped>
```

**Comment by TanayParikh** [comment]
You should be able to replicate the steps the CI uses to run the e2e tests via:

https://github.com/dotnet/aspnetcore/blob/543c4b88811dec686826e6a4c1143531d3117b93/.azure/pipelines/components-e2e-tests.yml#L41-L57

**Comment by kg** [comment]
I saw a suggestion online that a bug in powershell causes this arguments error but using cmd didn't make a difference. Looking around, there's a typo in SeleniumStandaloneServer.cs, where it passes ```-port {port}``` instead of the correct ```--port {port}```. Hand-editing that made it able to successfully start Selenium.

**Comment by kg** [comment]
OK, from further testing the version of selenium-standalone installed by 'npm install' in the e2etest directory only accepts ```-port```, while latest selenium-standalone wants ```--port```. So if we ever update our version of that package it'll break. I will also note that using latest selenium-standalone makes webdriver crash constantly, so tests basically don't work there.

The version installed by npm unfortunately fails with "This version of ChromeDriver only supports Chrome version 99", and the version of chrome installed by the script in ./eng/ is chrome 101, so it's still not possible to run the e2e tests as-is since Google has no official LTS mechanism I can use to install chrome 99 on my windows machine. Are E2E tests only intended to be run on CI using specific dependency versions? chrome 99 is from weeks and weeks ago.

**Comment by kg** [comment]
It looks like if you edit ```selenium-config.json``` to update the chrome version to match the latest version of chrome *before* you do ```npm install```, it will give you the correct version of chromedriver and then tests will work.

**Comment by wtgodbe** [comment]
@captainsafia @javiercn was this fixed by any of the recent changes to `selenium-config.json`? https://github.com/dotnet/aspnetcore/commits/main/src/Shared/E2ETesting/selenium-config.json

**Comment by captainsafia** [comment]
AFAIK, I don't believe so.

**Comment by mkArtakMSFT** [comment]
Given that this is determined by the version of the selenium, and we do update these dependencies from time to time, it'll be automatically fixed eventually (if not already). Hence, closing this issue as there isn't much community engagement to force an immediate action here.
