### ISSUE TITLE
SignalR es5

### ISSUE THREAD

**Issue by ricardonogues** [dotnet/aspnetcore#41419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SignalR does not work on older browsers (chrome 52) due to async/await feature

### Expected Behavior

SignalR to work on older browsers

**Comment by ricardonogues** [comment]
Is there a way to make SignalR work on older browsers? In my case Chrome 52. I'm including it in an other project and I'm using babel to transpile the code but I'm assuming dependencies are not transpiled. Is there a way to transpile SignalR to make it work on these browsers? Thanks.

**Comment by rafikiassumani-msft** [comment]
@ricardonogues  Did you try to transpile Signalr.js or signalr.min.js using your preferred JS transpiling tool? (Babel, etc. ?)

**Comment by ricardonogues** [comment]
@rafikiassumani-msft Thank you for the quick response. I've compiled signalR with babel with signalr.js but, when compiling my app with webpack, it's complaining about some node modules that are missing, namely http, https and utils. I've configured webpack to ignore those modules through the resolve property but I don't think signalR will work properly this way wright?

**Comment by BrennanConroy** [comment]
> I don't think signalR will work properly this way

Have you tried it? SignalR will use the browsers built in HTTP stack, the node modules would only be used when running with Node.

**Comment by captainsafia** [comment]
Triage: SignalR support is limited to evergreen browsers. You can read about the current support standards at https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-6.0.

> I've configured webpack to ignore those modules through the resolve property 

This might be your problem. You'll probably want to add polyfills for these modules if the browsers you are running on don't support them.

**Comment by ricardonogues** [comment]
@captainsafia Thank you for your response. We've ended up removing signalR from our app.
