### ISSUE TITLE
Kestrel host throws null exception when writing response

### ISSUE THREAD

**Issue by jonasrembratt** [dotnet/aspnetcore#41416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Writing a simple OIDC client using a Kestrel host for the callback but when I attempt to write a response the Kestrel host throws a `NullReferenceException`. I have traced the problem to the `HttpProtocol.CreateResponseHeader` method fetching `DateHeaderValues` from `DateHeaderValueManager.GetDateHeaderValues()`, which simply returns its private `_dateValues` field. That field is unassigned at that time.

I have read that a [solution for this issue](https://github.com/dotnet/aspnetcore/issues/28112) is to replace the package reference to Microsoft.AspNetCore.Server.Kestrel with a FrameworkReference to Microsoft.AspNetCore.App. That does not work for my solution and I don't know why (the `UseKestrel` extension method becomes unavailable).

Is there another way to resolve this issue, other than replacing a single Nuget with an entire framework?

### .NET Version

.NET 5 + .NET Standard 2.0

**Comment by Tratcher** [comment]
Please share your csproj file.

The `Microsoft.AspNetCore.Server.Kestrel` package is obsolete since 3.0 and needs to be removed. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#remove-obsolete-package-references

**Comment by jonasrembratt** [comment]
> Please share your csproj file.
> 
> The `Microsoft.AspNetCore.Server.Kestrel` package is obsolete since 3.0 and needs to be removed. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#remove-obsolete-package-references

This is the .csproj file content:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.15</AssemblyVersion>
    <FileVersion>1.0.0.15</FileVersion>
    <Version>1.0.0.15</Version>
    <PackageVersion>1.0.0-alpha.15</PackageVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>Tetra Pak SDK library for cross-platform (XP) applications</Title>
    <Description>A common set of code APIs and tools for Tetra Pak .NET development</Description>
    <Copyright>Tetra Pak</Copyright>
    <PackageReleaseNotes>Early alpha for internal testing</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TetraPak.XP.DependencyInjection\TetraPak.XP.DependencyInjection.csproj" />
    <ProjectReference Include="..\TetraPak.XP.Web.Http\TetraPak.XP.Web.Http.csproj" />
    <ProjectReference Include="..\TetraPak.XP.Web\TetraPak.XP.Web.csproj" />
  </ItemGroup>
</Project>
```

**Comment by jonasrembratt** [comment]
Ok, thanks. I'll replace the pack with the framework for .NET 5. 
But how do I work around this issue with .NET Standard 2?

**Comment by davidfowl** [comment]
Cross compile for netstandard 2.x and .NET Core https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#migrate-libraries-via-multi-targeting

**Comment by jonasrembratt** [comment]
> Cross compile for netstandard 2.x and .NET Core https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#migrate-libraries-via-multi-targeting

Sorry, I must be misunderstanding something. By supporting two targets (.NET 5 & :NET Standard 2.0), doesn't that mean different binaries will be linked in for each, and that the .NET Standard 2.0 compilation will link in the binaries from the (deprecated) Microsoft.AspNetCore.Server.Kestrel pack?

**Comment by davidfowl** [comment]
You can have netstandard 2.0 but you can't use those incompatible packages when using newer versions of ASP.NET Core 3.1. So you need to multi target your library.

**Comment by jonasrembratt** [comment]
> You can have netstandard 2.0 but you can't use those incompatible packages when using newer versions of ASP.NET Core (>= 3.1). So you need to multi target your library.

Ok, that's taken care of but is there any way to fix the Kestrel problem when targeting .NET Standard 2.0?

**Comment by davidfowl** [comment]
@jonasrembratt Can you elaborate? What version of Xamarin? What assemblies are being used when you use that version of Xamarin? Things will work as long as you don't cross the streams. ASP.NET Core 2.x is incompatible with 3.x and onwards.

**Comment by adityamandaleeka** [comment]
What is the [TFM](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) being used by `TetraPak.XP.Mobile`?

In general, the comment above about not mixing 2.x with 3.x and higher applies.

**Comment by jonasrembratt** [comment]
> What is the [TFM](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) being used by `TetraPak.XP.Mobile`?
> 
> In general, the comment above about not mixing 2.x with 3.x and higher applies.

So, the TetraPak.XP.Mobile is intended for cross-platform development, including Xamarin. So, for Xamarin use it's .NET Standard 2.0. I don't quite understand the recommendation to not mix 2.x with 3.x and higher. A Xamarin mobile app targets .NET Standard 2.0 (.NET Core 2.0), right? Are you saying that a Nuget supporting multiple frameworks can cause problems even though a given compile is targeting one of them?

**Comment by davidfowl** [comment]
These packages cannot be used on an application targeting .NET Core 3.x. That's the bottom line. When you run any application that uses these packages and you load it into a .NET Core >= 3.x process, it will break.

**Comment by jonasrembratt** [comment]
> These packages cannot be used on an application targeting .NET Core 3.x. That's the bottom line. When you run any application that uses these packages and you load it into a .NET Core >= 3.x process, it will break.

So, if I understand correctly, my Xamarin app (TFM=netstandard20) should work fine wheres a console app with TFM=net6, for example, should break (both consuming the TetraPak.XP.Browsers, which supports net5 and netstandard20)?

Again, I'm sure I misunderstand, but I'm pretty much seeing the exact opposite to that and, if that where the case, what would be the point building multi-framework Nugets at all?

**Comment by davidfowl** [comment]
Xamarin apps have their own TFM, it's not netstandard 2.0 (netstandard is just an API spec). I would assume these packages work fine when running in the xamarin application.

> Again, I'm sure I misunderstand, but I'm pretty much seeing the exact opposite to that and

So to have all of the information in a single place... In this specific scenario, you are running on legacy Xamarin and using a netstandard 2.0 package with:

```
<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
```

And seeing a null reference at runtime. 

Is that correct?

**Comment by jonasrembratt** [comment]
> Xamarin apps have their own TFM, it's not netstandard 2.0 (netstandard is just an API spec). I would assume these packages work fine when running in the xamarin application.
> 
> > Again, I'm sure I misunderstand, but I'm pretty much seeing the exact opposite to that and
> 
> So to have all of the information in a single place... In this specific scenario, you are running on legacy Xamarin and using a netstandard 2.0 package with:
> 
> ```
> <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
> <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
> <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
> ```
> 
> And seeing a null reference at runtime.
> 
> Is that correct?

Affirmative! :-)

**Comment by davidfowl** [comment]
Can you confirm the issue is exactly the same as referenced in the original description? Can you show the running application and the stack trace of the exception? Can you also dump all loaded binaries in the application so we can verify what assemblies are being loaded in the legacy Xamarin application?
