### ISSUE TITLE
Api Suggestion [ViewModel ] Attribute for for poco tags

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#41423]
Normally when we have to create DTO Objects we must create them as such.

    public class Players
    {   
        public int Id { get; set; }
        public int? Type { get; set; }
        public string? PlayerLevel { get; set; }
        public int? CoachId { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? TeamId { get; set; }
        public int? Year { get; set; }
        public string? FirstName { get; set; }
        public string? Surname { get; set; }
    }

If I was to create a view model I would normally have to do this would then be used on the front end. What I see as a better option is this.

    public class PlayersPlayersVIewModel
    {   
       public string? FirstName { get; set; }
       public string? Surname { get; set; }
    }

    public class Players
    {   
        public int Id { get; set; }
        public int? Type { get; set; }
        public string? PlayerLevel { get; set; }
        public int? CoachId { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? TeamId { get; set; }
        public int? Year { get; set; }
        [ViewModel  , Edit=True,Save=True) ]
        public string? FirstName { get; set; }
        public string? Surname { get; set; }
    }

        [ViewModel , Edit=True,Save=True) ]

With the above
 ViewModel  would determine if  the model is being used on the razor file it would then have the when coming from a razor file or cshtml file in blazor the front end would parse the model looking for ViewModel   attribute .

Thus 
 With above we  would only have one model to deal with instead of having two models in the current api.

**Comment by javiercn** [comment]
@davidbuckleyni thanks for contacting us.

Unfortunately we are not sure we grasp what you are asking for with the data you provided. Could you try to clarify the scenario further?

**Comment by davidbuckleyni** [comment]
HI @javiercn I am better explaining over teams  but basically an attributable that would be filtered when we call a model from the front end. I am trying to minimize the need to repeat code in the asp.net core for duplication of models using view models

**Comment by javiercn** [comment]
@davidbuckleyni thanks for the additional details.

This is already available by passing to the `@bind` attribute the list of fields you want to bind. https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.bindattribute?view=aspnetcore-6.0.

This is based on an include/allow list, we don't have plans to do an exclude/deny list.

**Comment by davidbuckleyni** [comment]
Why does the bot always go to resolved it was not what I was looking for
