### ISSUE TITLE
Allow parameter and return types of route handler delegates (API Controllers) to contribute to endpoint metadata

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#41421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Introduce the capability for types used for parameters and return values for `API controller action`s to contribute to metadata of the endpoint they're mapped to. This will allow types that implement custom binding logic via TryParse and IResult types, to add metadata that describes the API parameters and responses in Swagger UI and OpenAPI documents.

This is an idea of feature parity with Minimal API, after #40646.

### Describe the solution you'd like

We should introduce the same support for the new interfaces, `IEndpointParameterMetadataProvider` and `IEndpointMetadataProvider` that currently is implemented in Minimal Actions.

**Comment by captainsafia** [comment]
Triage: Bruno proposes implementing this as an ApiConvention.

We also discussed whether this would worthwhile to do if MVC does not support `BindAsync` and concluded there is value in this work even though MVC doesn't support `BindAsync` as of writing.
