### ISSUE TITLE
Client generated code, from OpenAPI, could not bind route parameter of a Minimal Endpoint when route pattern's parameter and delegate's parameter case does not match

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#41422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have a minimal endpoint `route pattern` that includes a `route parameter` that does not match the delegate parameter name case, eg.:

``` c#
app.MapGet("/todo/{id}", (int Id)  => Results.Ok());
```

The route system will be able to bind the parameter value correctly, since it is `case insensitive` and all incoming request will be processed correctly.

https://github.com/dotnet/aspnetcore/blob/4b514766b2c119fffde8b4e3290ead8861dacab1/src/Http/Routing/src/Patterns/RoutePattern.cs#L146

However, when the `OpenAPI` metadata is enabled, the following metadata is generated, where the parameter name matches the delegate parameter name case instead of the `route parameter`.

``` json
"paths": {
    "/todo/{id}": {
      "get": {
        "tags": [
          "WebApplication4"
        ],
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
```

This behavior might seem irrelevant and undetectable, however, when the Open API metadata is used in a client generation tool, eg. `VS Connected Service`s tool or even `Swagger UI`, this error will cause the client to no provide the route parameter value correctly, causing the following issue because the request url will be something like `http://server:port/todo/{id}` since the generated code is not able to replace the {id} with the provided value.

``` logs
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to bind parameter "int Id" from "{id}".
   at lambda_method2(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The following block of code is an example of the client generated code where the request url is build and fail to replace the placeholder with the appropriated value.

``` c#
var urlBuilder_ = new System.Text.StringBuilder();
urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/todo/{id}");
urlBuilder_.Replace("{Id}", System.Uri.EscapeDataString(ConvertToString(id, System.Globalization.CultureInfo.InvariantCulture)));
```

This error could be easily fixed by changing the delegate's parameter or route pattern's parameter case, however, as mentioned the error is undetectable and only the client generation will be affected. Another important point is that this error will be more likely to happen when #40712 is available

### Expected Behavior

Since the routing system is case insensitive already, I would expect that the following endpoints produce the same metadata:

``` c#
app.MapGet("/todo/{id}", (int Id)  => Results.Ok());
app.MapGet("/todo/{id}", (int id)  => Results.Ok());
```

``` json
"paths": {
    "/todo/{id}": {
      "get": {
        "tags": [
          "WebApplication4"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
```

If the correct metadata generation is not possible, we should at least have the tool available in Visual Studio able to generate a client capable of binding the route parameter value correctly.

#### Program.cs
``` c#
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

app.MapGet("/todo/{id}", (int Id)  => Results.Ok());

app.Run();
```

### Client

While running the server application, collect the metadata json file and try to create the generated client with the following steps:

1. Add a service reference from OpenAPI
![image](https://user-images.githubusercontent.com/12376385/165767820-6f8a27d8-c578-4a49-8634-4f924ed8d2f9.png)

2. Specify the required information for the reference
![image](https://user-images.githubusercontent.com/12376385/165768148-9e66d06d-0433-4270-a51c-1e9de9e9fda6.png)

3. Add the following code to your app
``` c#
using var httpClient = new HttpClient();
var todoService = new ConsoleApp2.Endpoints.TodoService("[your app url]", httpClient);
await todoService.TodoAsync(10);

```

### Exceptions (if any)

``` logs
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to bind parameter "int Id" from "{id}".
   at lambda_method2(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### .NET Version

7.0.100-preview.4.22218.7

### Anything else?

N/A

**Comment by captainsafia** [comment]
Triage: We do have access to the `RoutePattern` in both the `ApiExplorer` and the new `M.A.OpenApi` package so we can determine the actual parameter name as defined in the route instead of the mismatched parameter name.

In general, we propose adding a new rule here that favors using the name in the template instead of the parameter name for request parameters where applicable.
