### ISSUE TITLE
Disable authenticator app

### ISSUE THREAD

**Issue by 9Rune5** [dotnet/aspnetcore#41420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

As a user I have enabled both phone and authenticator app as 2FA methods.

However, I would like to disable the authenticator app without disabling 2FA completely (and still use phone/email).

### Describe the solution you'd like

Add `public async Task<IdentityResult> DisableAuthenticatorAsync(User user, CancellationToken cancellationToken)` in UserManager.cs.

At first glance, I thought ResetAuthenticator() would do the trick, but that will simply issue a fresh key. Looking at various examples, there is a test to see if the authenticator key is null (or empty) when enabling the authenticator.

Nulling the authenticator key is what I ended up doing:
```
            await store.SetAuthenticatorKeyAsync(user, null, cancellationToken).ConfigureAwait(false);
            await UpdateSecurityStampInternal(user, cancellationToken).ConfigureAwait(false);
            return await UpdateAsync(user).ConfigureAwait(false);
```

**Comment by HaoK** [comment]
It looks like you are just talking about what the identity UI pages do by default, so yeah https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/Manage/TwoFactorAuthentication.cshtml.cs#L84 is just looking at whether there is an authenticator key to determine if it has an authenticator.  So nulling it out is a reasonable way to accomplish this, is there something that you are currently blocked on, or were you just wondering if what you were doing was correct?
