### ISSUE TITLE
Blazor WASM: Misleading error message when calling DotNetObjectReference.invokeMethod and then calling JSRuntime.InvokeAsync<T>

### ISSUE THREAD

**Issue by SwissJimmy** [dotnet/aspnetcore#41438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This was detected in .net5 Blazor WASM for multiple versions of Microsoft.JSInterop. In short, if you try to call async Javascript from within a dotnet function that was invoked with a sync context, then you receive error:

`blazor.webassembly.js:1 System.Text.Json.JsonException: A possible object cycle was detected.`

The mistake here was actually to try to invoke async Javascript from within a sync context.

For example, I may have some Javascript:

`dotNetObjectReference.invokeMethod("MyFunction");`

This calls the C#:

```
private async Task<string> MyFunction<T>()
{
    var value = await JSRuntime.InvokeAsync<string>("getAString");
    return value;
}
```

The return value here is a string and so there is no possibility of a genuine circular reference. The problem is that the error message is quite misleading.

### Expected Behavior

An error should be raised to the effect that you cannot make an async invocation from within a synch context. 

### .NET Version

5.0.404

**Comment by javiercn** [comment]
@SwissJimmy thanks for contacting us.

Can you provide a minimal repro project as a public github repository and steps to trigger the issue so that we can get a very clear picture of what's going on here?
