### ISSUE TITLE
How to properly write an implementation of the IClaimsTransformation interface in ASP.NET core 6 ?

### ISSUE THREAD

**Issue by EnricoMassone** [dotnet/aspnetcore#41440]
In aspnet/Security#1399 some [guidelines](https://github.com/aspnet/Security/issues/1399#issuecomment-327946649) are provided to  properly write an implementation of the [IClaimsTransformation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-6.0) interface.

The underlying issue of aspnet/Security#1399 has also been reported in #11462 and has been resolved in pull request #12028

In the `AuthenticationService` a [cache](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Http/Authentication.Core/src/AuthenticationService.cs#L16) has been introduced to keep track of the execution of the claims transformation on the authenticated request principal. The request principal instance is [added to the cache](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Http/Authentication.Core/src/AuthenticationService.cs#L93) after the execution of the claims transformation, so that [the transformation is never executed again on the same request principal](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Http/Authentication.Core/src/AuthenticationService.cs#L85).

So, based on my understanding, when using ASP.NET core 6, it is no more necessary to adhere to the [guidelines](https://github.com/aspnet/Security/issues/1399#issuecomment-327946649) given in aspnet/Security#1399. Am I correct ? 

Specially returning a brand new instance of `ClaimsPrincipal` from `TransformAsync` totally defeats the whole purpose of the [cache used to track the claims transformation execution](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Http/Authentication.Core/src/AuthenticationService.cs#L93), because the equality of [ClaimsPrincipal](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal?view=net-6.0) instances is based on object references. Is it ok to implement  `TransformAsync` by **directly mutating** the `ClaimsPrincipal` instance provided as a parameter ? 

I have a last point about which lifetime to choose when registering `IClaimsTransformation` on the DI container. In this [sample](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Security/samples/ClaimsTransformation/Startup.cs#L37) the service is registered as transient. Is this mandatory ? Is it ok to register a stateless implementation of `IClaimsTransformation` as a singleton ?

Thanks for helping.

**Comment by EnricoMassone** [comment]
Just to add more context on this, I've recently found [this documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0#extend-or-add-custom-claims-using-iclaimstransformation) which seems to confirm that it's fine to directly mutate the `ClaimsPrincipal` argument. 

This documentation seems to ignore the changes introduced by pull request #12028 because it explicitly says the following:

> This method might get called multiple times. Only add a new claim if it does not already exist in the ClaimsPrincipal

The provided code sample is actually defensive when new claims are added to the principal identity:

```
var claimType = "myNewClaim";
if (!principal.HasClaim(claim => claim.Type == claimType))
{
    claimsIdentity.AddClaim(new Claim(claimType, "myClaimValue"));
}
```

Based on my understanding this defensiveness is useless, because of changes introduced by #12028. Am I correct ?

Maybe this documentation is accounting for the possibility of custom authentication handlers, which can possibly **not** caching the claims principal and return a new instance each time [`handler.AuthenticateAsync()` is called](https://github.com/dotnet/aspnetcore/blob/f1ebd5d426a1996980eec00be55459352c6f27dc/src/Http/Authentication.Core/src/AuthenticationService.cs#L78). @HaoK has actually pointed out the possible issue with custom authentication handlers [in the pull request discussion](https://github.com/dotnet/aspnetcore/pull/12028#issuecomment-546125494). If this is the case, maybe it's worth clarifying this in the docs. By searching through blog posts and code samples all over the internet, the fact that a claims transformation can be run multiple times on the same authenticated request principal seems to be a common belief (it's event pointed out in the [docs for the IClaimsTransformation interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-6.0#methods))

**Comment by HaoK** [comment]
There are a lot of questions here, what is it that you are trying to do exactly @EnricoMassone ?  If you are writing a claims transform for a specific handler or set of handlers which you know the behavior for, that's a much simpler problem as you then know how the caching will behave.  So I guess the answer is it depends on what you are trying to do and the exactly what context/handlers your transformations are being run on.

**Comment by EnricoMassone** [comment]
> There are a lot of questions here, what is it that you are trying to do exactly @EnricoMassone ? If you are writing a claims transform for a specific handler or set of handlers which you know the behavior for, that's a much simpler problem as you then know how the caching will behave. So I guess the answer is it depends on what you are trying to do and the exactly what context/handlers your transformations are being run on.

Hello @HaoK thanks for replying. 

My contenxt is the following:

1. I'm working with an  ASP.NET core 6 MVC application
2. I'm using a cookie based authentication, which creates the user identity by using an external openid connect provider. This is done by using IdentityServer4 as the gateway between the openid connect provider and my application. I have configured the authentication as explained in this [IdentityServer4 sample](https://github.com/IdentityServer/IdentityServer4/blob/5bcc2abbcf6c47200c4eb3b77e756f1bc0e04358/samples/Quickstarts/3_AspNetCoreAndApis/src/MvcClient/Startup.cs#L17). So, basically, I'm using cookie authentication and the auth challenges are handled by identity server. 

I'm using a claims transformation because I want to keep the authentication cookie as small as possible and I want to add some 
custom claims to the user identity server side, on my MVC application. These custom claims are used by the authorization policies of my MVC application to decide whether or not the request principal is allowed to invoke some protected action methods on my controllers. 

My questions are the following:

1. Given this scenario, based on my understanding, the claims transformation will be run exactly one time on the authenticated user, because of the changes introduced with #12028. So, I can simplify the code of my claims transformation by avoiding any defensive strategy (such as add a marker claim to keep track of the claims transformation execution or explicitly checking on the user claims collection before adding any new claim to the user identity). Is this correct ?
2. All the code samples provided in the docs register the implementation of IClaimsTransformation as a transient service. Is this mandatory for any reason ? My implementation can safely be registered as a singleton service (it's basically a stateless class depending on another singleton service), is there any reason I should register it as a transient instead ?

**Comment by HaoK** [comment]
1. Probably?  I'd just try it and see, if your principal doesn't look weird, you are fine.
2. Singleton should be fine

**Comment by EnricoMassone** [comment]
> 1. Probably?  I'd just try it and see, if your principal doesn't look weird, you are fine.
> 2. Singleton should be fine

Thanks ! I'll do some testing and I'll keep this open until I'll be able to provide some feedbacks. Based on first testing it seems to work fine.
