### ISSUE TITLE
Cleanup u8 string literal workarounds

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#41455]
Changes that can be cleaned up are introduced in https://github.com/dotnet/aspnetcore/pull/41449. CertificateManager and DataProtectionTests were the areas affected.

Improvements to the u8 string literal feature are being tracked in https://github.com/dotnet/roslyn/issues/60644

**Comment by DamianEdwards** [comment]
This is causing issues in Visual Studio in release/6.0 now as well. I've applied the required fixes in branch dedward/41529-template-namespace

**Comment by wtgodbe** [comment]
@BrennanConroy looks like the roslyn work was done in https://github.com/dotnet/roslyn/pull/61532, so we should be able to do the reaction soon. Should I assign you?
