### ISSUE TITLE
Blazor route parameters not work with custom type

### ISSUE THREAD

**Issue by ErlinEmrys** [dotnet/aspnetcore#41467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use custom type as route parameter, but I'm getting error "Specified cast is not valid." in the browser.
Similar approach is used on server-side controllers and it works flawlessly. Am I doing something wrong?

### Expected Behavior

The custom type have `TypeConverter` that is able to convert from string, so there should not be "Specified cast is not valid." error at all.

### Steps To Reproduce

1. Create default WASM Asp.Net hosted project.
2. Create CustomId.cs file in Shared project with following content:
```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlazorApp1.Shared;

[TypeConverter(typeof(CustomIdConverter))]
public struct CustomId
{
    public static CustomId Empty { get; }

    public int First { get; set; }
    public int Second { get; set; }

    private const string ID_SEPARATOR = ":";

    public override string ToString()
    {
        return $"{First}{ID_SEPARATOR}{Second}";
    }

    public static CustomId Parse(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return CustomId.Empty;
        }

        string[] parts = text.Split(ID_SEPARATOR);
        int left = int.Parse(parts[0], CultureInfo.CurrentCulture);
        int right = int.Parse(parts[1], CultureInfo.CurrentCulture);
        return new CustomId() { First = left, Second = right };
    }
}

public class CustomIdConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
    {
        if (sourceType == typeof(string))
        {
            return true;
        }

        return base.CanConvertFrom(context, sourceType);
    }

    public override object ConvertFrom(
        ITypeDescriptorContext context,
        CultureInfo culture,
        object value
    )
    {
        if (value is string text)
        {
            return CustomId.Parse(text);
        }

        return base.ConvertFrom(context, culture, value);
    }
}
```

3. Change the Client file of Counter.razor to following:
```razor
@page "/counter/{Id}"
@page "/counter"
@using BlazorApp1.Shared

<h1>@Id</h1>

@code {
    [Parameter]
    public string Id_String { get { return Id.ToString(); } set { Id = CustomId.Parse(value); } } 

    [Parameter]
    public CustomId Id { get; set; }
}
```

4. Start the project and go to URL ~/counter/1:2 (or different numbers).
5. The error described will appear. The Id "1:2" from URL is not stated on the page.

6. Change first line of Client file Counter.razor to following:
`@page "/counter/{Id_String}"`
7. Start the project and go to URL ~/counter/1:2
8. The page now correctly shows the Id "1:2" (or different based on the URL)

### Exceptions (if any)

blazor.webassembly.js:1
crit: 
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'Id' on object of type 'BlazorApp1.Client.Pages.Counter'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'Id' on object of type 'BlazorApp1.Client.Pages.Counter'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[Counter,CustomId](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

### .NET Version

6.0.202

### Anything else?

I have also tried to add implicit conversion operator, but it did not help either:
`public static implicit operator CustomId(string text) => CustomId.Parse(text);`

**Comment by javiercn** [comment]
@ErlinEmrys thanks for contacting us.

Custom type parameters are not supported. Only a limited set of primitive types is supported by routing in Blazor.
