### ISSUE TITLE
"@ref" can not get correct value

### ISSUE THREAD

**Issue by BurningTeng** [dotnet/aspnetcore#41469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I click the span. **The file  name to be downloaded is wrong**. I use .Net to invoke JS function. Code As below:
```
. . . 
  @foreach (var file in loadedFiles)
  {
      <li>
          <ul>
              <li >
                  Name: <button class="btn btn-link"@onclick="DownloadFileFromURL" @ref="fileNameReference">
                          @file.Name
                  </button>
              </li>
              <li>Last modified: @file.LastModified.ToString()</li>
              <li>Size (bytes): @file.Size</li>
              <li>Content type: @file.ContentType</li>
          </ul>
      </li>
  }
. . .
@code {
       ElementReference fileNameReference {get; set;}
    private async Task DownloadFileFromURL()
    {
        //引用的是最后设置的那个值。
        await JS.InvokeVoidAsync("triggerFileDownload",  fileNameReference);
    }
}
``` 

JS code 

```javascript
    <script>
        function triggerFileDownload(element) {
            console.log(element);
            console.log(element.innerText);
            var url = "https://localhost:7135/files/" + element.innerText;
            var fileName = element.innerText;
            const anchorElement = document.createElement('a');
            anchorElement.href = url;
            anchorElement.download = fileName ?? '';
            anchorElement.click();
            anchorElement.remove();
        }    
    </script>
```

### Expected Behavior

When I click the span item,  the file  name to be downloaded is wrong**. Or Is there any when to get the span reference.?Thanks

### Steps To Reproduce

1. You can run code at https://gitee.com/XiaoBoLiLun/blazor-bug-for41469
2. Select "文件上传" item
3. Select three files to upload
4. click each file name to download
5. All down load file name is last file name

### .NET Version

.NET6

**Comment by javiercn** [comment]
@BurningTeng thanks for contacting us.

We don't think that there is an issue in the framework based on your repro code. There seems to be some problem in your app code, however `@ref` seems to be working as expected.
