### ISSUE TITLE
Add HTTP status code 499 Client Closed Connection

### ISSUE THREAD

**Issue by tvardero** [dotnet/aspnetcore#41475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Imo, it's a QoL feature. 
499 status code - Client Closed Connection. Status code was [originally proposed by nginx](https://docs.apigee.com/api-platform/troubleshoot/runtime/499-client-closed-connection) and used in cases when client cancels the request before server responds. **499 status code is non-standard.**

In ASP.NET could be used in API controller actions with injected CancellationToken.

### Describe the solution you'd like

- Automatic respond with 499 status code on unhandled OperationCanceledException( TaskCanceledException ) raised in controller actions, if the injected cancellation token was the cause of the exception.
- Adding Status499ClientClosedConnection to Microsoft.AspNetCore.Http.StatusCodes enum.
- Documentation on 499 status code

### Additional context

Could be backported to .Net 6, as I see no breaking changes.

**Comment by tvardero** [comment]
My current code, where I use this status code:
```c#
// EmployeeController:
[HttpPost]
public async Task<IActionResult> CreateEmployeeAsync(Employee model, CancellationToken cancel)
{
    try
    {
        Employee addedModel = await _employees.AddAsync(model, cancel);
        return CreatedAtAction(nameof(GetEmployee), new { id = addedModel.Id }, addedModel);
    }
    catch (OperationCanceledException)
    {
        // ClientClosedConnection - sent when client cancels the request before server replies
        return StatusCode(499, new { status = 499, message = "ClientClosedConnection" }); 
    }
}
private readonly IRepository<Employee> _employees;

// IRepository<Employee> implementation:
public async Task<Employee> AddAsync(Employee entity, CancellationToken cancel = default)
{
    var result = await _ctx.Employees.AddAsync(entity, cancel);
    await _ctx.SaveChangesAsync(cancel);
    return result.Entity;
}
private readonly AppDbContext _ctx;
```

**Comment by davidfowl** [comment]
I'm not sure we should add this. Doesn't seem to be accepted as the standard in any other of the language runtimes that I checked.

> Could be backported to .Net 6, as I see no breaking changes.

We don't backport new APIs so that's a non-starter.

**Comment by Tratcher** [comment]
If the client closes the connection then this status code would only ever be seen in logs. I don't think that's any better than a log saying the client disconnected.

Note if the disconnect happened after the response headers were sent then it wouldn't be possible to change the status code regardless.

**Comment by adityamandaleeka** [comment]
Triage: this is a non-standard code, and we already do something similar using the status code 0 in this case. There's minimal value in adding this.
