### ISSUE TITLE
MultipartReader - BodyLengthLimit is not the total length

### ISSUE THREAD

**Issue by dldldlepl** [dotnet/aspnetcore#41479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `MultipartReader` has a property `BodyLengthLimit`, which is documented as "The optional limit for the total response body length." Applying this limit to a `MultipartReader`. does not limit the overall body size to this number of bytes. Instead the limit of each section of the multipart content is limited to this size. The overall length is not limited to the size of this parameter, therefore allowing to accept much more data than expected.

### Expected Behavior

The `MultipartReader` should limit the body length to the given size of the overall request or the documentation of the parameter BodyLengthLimit should indicate that this is the length limit per Body section.

**Comment by adityamandaleeka** [comment]
Thanks, we'd accept a PR to fix the documentation.

**Comment by Tratcher** [comment]
> The `MultipartReader` should limit the body length to the given size of the overall request or the documentation of the parameter BodyLengthLimit should indicate that this is the length limit per Body section.

The total body length is already limited by other components like the servers which all default to 30mb limits on requests. You're right that this setting only covers individual sections, and the comment should be updated to clarify that.
