### ISSUE TITLE
Blank AspNetCore SpaProxy template doesn't run

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/aspnetcore#41474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- Create a new ASP.NET Core project - Angular template
- Run the project
- Fails because there's a space in the path

Following image should tell everything:

![image](https://user-images.githubusercontent.com/9629574/166215297-6f3a03d7-6abf-49ec-b285-5af79ecf43b4.png)

### Expected Behavior

Run the app.

### .NET Version

6.0

**Comment by PieterjanDeClippel** [comment]
Solution is in modifying the project template: **ASP.NET Core and angular**

ClientApp/package.json:

```
{
  "name": "project1",
  "version": "0.0.0",
  "scripts": {
    ...,
    "start:windows": "ng serve --port 44405 --ssl --ssl-cert \"%APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem\" --ssl-key \"%APPDATA%\\ASP.NET\\https\\%npm_package_name%.key\"",
    "start:default": "ng serve --port 44405 --ssl --ssl-cert \"$HOME/.aspnet/https/${npm_package_name}.pem\" --ssl-key \"$HOME/.aspnet/https/${npm_package_name}.key\""
  },
  ...
}
```

Please DO NOT FORGET to put quotes around all the paths!!! I'm experiencing the same troubles with [NX](https://github.com/nrwl/nx/issues/10009)

**Comment by javiercn** [comment]
@PieterjanDeClippel thanks for contacting us.

Feel free to send us a PR to dotnet/spa-templates and we'll be happy to accept a contribution.

**Comment by PieterjanDeClippel** [comment]
Hi, can you move this issue to https://github.com/dotnet/spa-templates ?
