### ISSUE TITLE
Serving RCL Static Assets with the _content/LibraryName prefix

### ISSUE THREAD

**Issue by Thf772** [dotnet/aspnetcore#41480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

My use case is a project where the Razor Pages reside in a separate assembly than the one setting up the Web Host and running the app. Basically the project structure is as follows:

```text
MyApp.Server
    appsettings.json
    Program.cs          // Configures WebHost

MyApp.Web
    WebSetup.cs         // Configures the Razor-specific WebApplication pipeline
    Pages
        Index
        ...
    wwwroot
        favicon.ico
        css
        lib
        js
```

I have managed to get the Razor Pages server properly by the app, however, they cannot load the static JS and CSS files, because these static files are not in the default folder. The pages from the template look for them at the root, in `/lib`, `/js` or `/css`, but they are in a subdirectory: respectively as `_content/MyApp.Web/lib`, `_content/MyApp.Web/js` and `_content/MyApp.Web/css`.

I have not modified the `cshtml` files from the Razor Pages project template (the one you get when doing `dotnet new webapp`), since I want to get the default pages working before I change anything in them.

### Describe the solution you'd like

I know that I can change the file paths to include the `_content` prefix. However, I really don't like this solution: since my `Server` project will never contain any static files, and these static files are only used by the `Web` project, it does not make any sense to keep them in a subdirectory. Even more so since the Razor pages themselves are not in a subdirectory.

Is there a way to have the static assets from a Razor Class Library merge with the root-level static assets of the main project? If not, is it possible to add it?

This is somewhat similar to issue #14568 where they wanted the base path of their RCL assets to be the same on the dev project and in the server, except in my case I want an empty base path, but it gets erased by the build process. I have succesfully been able to replace `_content/MyApp.Web` with another non-empty string like `assets`,  but not an empty string (note that when I used `assets`, the Razor Pages still did not include it in the static file paths). I even tried creating a cutom target invoked after `ResolveCurrentProjectStaticWebAssetsInputs` that forced `StaticWebAssetBasePath` to reset to an empty string, but it cause the build to crash further down the line.

### Additional context

Here is an example file path inside `_Layout.cshtml`, as they are in the project template:
```` html
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
```` 

Here is the same file path, in the generated HTML I get when I open the page in my browser (in `localhost:5001/Index`):
```` html
<link rel="stylesheet" href=/css/site.css" />
```` 

And here is what I get when I get the file listing from `IWebHostEnvironment.WebRootFileProvider`:
```text
/_content/MyApp.Web/css/site.css
```

It was my understanding the the tilde prefix should resolve the static file from the project the `cshtml` is in, but it looks like this is not the case.

If it makes any importance, the only way I have been able to make Razor Pages work was by adding `services.AddRazorPages().AddApplicationPart(typeof(WebSetup).Assembly);` in my app initialization code. It did not work without `AddApplicationPart`.

**Comment by javiercn** [comment]
@Thf772 thanks for contacting us.

> It was my understanding the the tilde prefix should resolve the static file from the project the `cshtml` is in, but it looks like this is not the case.

The `~` only resolves the virtual path for the server, if for example your site is hosted on `https://www.example.com/virtualpath`

**Comment by Thf772** [comment]
I see, so if the static assets are kept in their directory the prefix must be in the Razor files no matter what.

I'm using .NET 6.0, but with the 5.0 `HostBuilder` initialization style due to personal preference.

**Comment by javiercn** [comment]
@Thf772 You can use `<StaticWebAssetBasePath>/</StaticWebAssetBasePath>`.

It's not completely clear what you are trying to do (if you have a website being referenced by something else, that's not something we really support).

If you put everything on a razor class library and reference that from another project and use  `<StaticWebAssetBasePath>/</StaticWebAssetBasePath>` that should work.

**Comment by Thf772** [comment]
> @Thf772 You can use `<StaticWebAssetBasePath>/</StaticWebAssetBasePath>`.

That worked, thank you. Nothing I found suggested that the path could be an absolute path, and I haven't been able to find any official documentation for `StaticWebAssetBasePath` either...
