### ISSUE TITLE
Create new Web API using `dotnet new webapi` with use-minimal-apis and use-program-main options set, you get a warning on build

### ISSUE THREAD

**Issue by balachir** [dotnet/aspnetcore#41491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create new Web API using `dotnet new webapi` with use-minimal-apis and use-program-main options set, you get a warning on build.

>The entry point of the program is global code; ignoring 'Program.Main(string[])' entry point.

This seems to be happening because it creates both a Program.Main.cs and a Program.cs.

### Expected Behavior

No warnings or errors on build

### Steps To Reproduce

INSTALL STEPS
1. Clean Windows 10 x64 machine
2. Install .NET SDK 6.0.300

REPRO STEPS
1. Create new Web API using `dotnet new` with use-minimal-apis and use-program-main options set
2. Build project `dotnet build`

```
>dotnet new webapi -o WebApi02 --use-minimal-apis --use-program-main
The template "ASP.NET Core Web API" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\<user>\Solutions\Projects02\WebApi02\WebApi02.csproj...
  Determining projects to restore...
  Restored C:\Users\<user>\Solutions\Projects02\WebApi02\WebApi02.csproj (in 352 ms).
Restore succeeded.



>cd WebApi02

>dotnet build
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Users\<user>\Solutions\Projects02\WebApi02\Program.Main.cs(5,24): warning CS7022: The entry point of the program is
global code; ignoring 'Program.Main(string[])' entry point. [C:\Users\<user>\Solutions\Projects02\WebApi02\WebApi02.csp
roj]
  WebApi02 -> C:\Users\<user>\Solutions\Projects02\WebApi02\bin\Debug\net6.0\WebApi02.dll

Build succeeded.

C:\Users\<user>\Solutions\Projects02\WebApi02\Program.Main.cs(5,24): warning CS7022: The entry point of the program is
global code; ignoring 'Program.Main(string[])' entry point. [C:\Users\<user>\Solutions\Projects02\WebApi02\WebApi02.csp
roj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.16

```

### .NET Version

6.0.300

### Anything else?

I'm also able to reproduce this with SDK 6.0.203.

**Comment by DamianEdwards** [comment]
Taking a look at the source it seems the Web API template isn't intended to support both `--use-program-main` and `--use-minimal-apis` simultaneously, but when they are both specified it doesn't correctly remove the top-level statements based .cs file.

At any rate, it seems odd now that those two options shouldn't be supported together (i.e. use a full `Program` class but use minimal APIs rather than controllers for the web APIs). I'll update the template to support this combination in 7.x and we can backport that fix to the 6.0.xxx servicing trains.
