### ISSUE TITLE
Question:  In Blazor Wasm, is it possible to capture the generated html from a Blazor component?

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#41508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Use case:  capture the generated html from a Blazor component and send it to a pdf.

### Describe the solution you'd like

In Blazor Wasm, capture the generated html from a Blazor component

**Comment by javiercn** [comment]
@roysurles thanks for contacting us.

It's not possible as the components don't generate HTML, they generate a sequence of instructions that get transmitted to the browser where JavaScript turns that into HTML.

On webassembly you could render the component on to the page and then use JS interop to capture/retrieve the serialized DOM text as a string.

If you were on a server you could "prerender" the component to obtain the HTML.

**Comment by javiercn** [comment]
We do have an issue to support rendering components in isolation, if you are interested on such functionality I would suggest you upvote the issue [here](https://github.com/dotnet/aspnetcore/issues/38114)
