### ISSUE TITLE
Automatic validation with ApiController does not work as expected

### ISSUE THREAD

**Issue by liborpansky** [dotnet/aspnetcore#41505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Automatic validation for non-nullable properties does not work as expected for all inheritance hierarchy. There are some properties that are not being validated for null value.

### Expected Behavior

Validation works correctly and returns 400 bad request API response.

### Steps To Reproduce

Create empty .NET API project with nullable enabled.

Create a test structure with 4 levels and one generic property:
```c#
public class OuterWeatherForecast : MiddleWeatherForecast<InternalWithInheritance>
{
    public string OuterRequired { get; set; } = null!;
}

public class MiddleWeatherForecast<T> : WeatherForecast<T>
{
    public string MiddleRequired { get; set; } = null!;
}

public class WeatherForecast<T> : BaseForecast
{
    public string TestRequired { get; set; } = null!;
    public T Inner { get; set; }
}

public class BaseForecast
{
    public string BaseRequired { get; set; } = null!;
}

public class Internal
{
    public string InnerRequired { get; set; } = null!;
}

public class InternalWithInheritance : Internal
{
    public string InternalWithInhRequired { get; set; } = null!;
}
```
Create a simple POST API endpoint within a controller with `[ApiController]` attribute.
```
[HttpPost(Name = "UpdateWeatherForecast")]
public void Update(OuterWeatherForecast model)
{
}
```
POST without `TestRequired` or `MiddleRequired` properties does not fire validation process and 200 OK is being returned. For the rest of the properties, validation works as expected with a standard validation result `"FieldName": ["The FieldName field is required." ]`

### .NET Version

6.0.202

**Comment by BrennanConroy** [comment]
@brunolins16 could you take a look at this? If you need to, feel free to ping me or Rafiki to load balance.

**Comment by brunolins16** [comment]
@liborpansky Just to give you a quick update I was able to repro your issue in .NET 6 and also can confirm that it is already fixed in .NET 7, however, I am still trying to track down where it was fixed.

**Comment by brunolins16** [comment]
So, the fix happened in this PR [dotnet/aspnetcore/pull/39219](https://github.com/dotnet/aspnetcore/pull/39219) where we changed to use `NullabilityInfoContext` to detect the property `Nullability`. In .NET 6 we explicitly decided to no infer the property as required for `Generic Types`, so, you need to include the `[Required]` attribute for that.
 https://github.com/dotnet/aspnetcore/blob/fd5cd4302211ada851a2e547309f47528800fdd2/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsMetadataProvider.cs#L518

**Comment by lsimone** [comment]
> In .NET 6 we explicitly decided to no infer the property as required for `Generic Types`, so, you need to include the `[Required]` attribute for that.

@brunolins16 this is not consistent at all with the [provided .NET 6 documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#non-nullable-reference-types-and-required-attribute): don't you think it should be considered a bug then?

**Comment by brunolins16** [comment]
> > need to include the `[Required]` attribute for that.
> 
> @brunolins16 this is not consistent at all with the [provided .NET 6 documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#non-nullable-reference-types-and-required-attribute): don't you think it should be considered a bug then?

Good catch! I will open a docs issue to try make it more clear.
