### ISSUE TITLE
Custom framework based on blazor server 

### ISSUE THREAD

**Issue by AlirezaDadrass** [dotnet/aspnetcore#41510]
Hi
I'm working on a custom framework project based on blazor server for organizing my own team an it takes almost 2 years to complete the architecture.

Now I'm wondering how I can make this framework works like a pre defined project template in dot net environment with considering that the main code base that my guys have to develop is a razor page dll not a asp.net project.
I have some issues for deployment of the template:
First, dll projects are not executable so i have to make an extra project just for running the dll and debugging. 

Second, I'm not able to convert dll to a single asp project because the main platform is modular and final release will be installed in it.
I'll If you can help me to provide a solution for this issue I will be appreciated

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. For your project template ask we recommend using custom templates for dotnet following the [documentation here](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates).1

As for your second question we recommend asking on on the [StackOverflow](https://stackoverflow.com) forum as that way you will get a faster response there.
