### ISSUE TITLE
With "Do not use top-level statements" checked, in Blazor WebAssembly App/ Blazor Server App/gRPC, the namespace is "Company.WebApplication1" rather than the solution name.

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/aspnetcore#41529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Blazor WebAssembly App/ Blazor Server App/gRPC, the namespace is "Company.WebApplication1" rather than the solution name. 
![image](https://user-images.githubusercontent.com/35762055/166883951-5baf9160-742d-475a-8984-ec86073c6cd1.png)

### Expected Behavior

The namespace should be same as the solution name. 
![image](https://user-images.githubusercontent.com/35762055/166884348-98dbdd61-3875-4921-9d7a-f11f5242f3f3.png)

### Steps To Reproduce

In latest Dev17.2 GA(Include latest 6.0.300 SDK), Create .NET 6.0 ~ Blazor Server App/Blazor WebAssembly App/gRPC project **with checking "Do not use top-level statements" checkbox.**. 
After project created, open Program.cs file, the namespace is "Company.WebApplication1", rather than the solution name.

### .NET Version

6.0.300

**Comment by javiercn** [comment]
@Andy-Win thanks for contacting us.

@DamianEdwards can you take a look?

**Comment by DamianEdwards** [comment]
I'll look at adding a test that ensures the template's configured `sourceName` does not appear in the template output content so this doesn't happen again.

**Comment by mkArtakMSFT** [comment]
@DamianEdwards I think this should be closed already, shouldn't it?

**Comment by DamianEdwards** [comment]
Yes, thanks!
