### ISSUE TITLE
Blazor, OnTimeUpdate and similar events: make argument more specific and clear

### ISSUE THREAD

**Issue by AlessandroMartinelli** [dotnet/aspnetcore#41528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi,
As of today Blazor supports [events](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0) like ontimeupdate, however the argument is a generic [EventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.eventargs?view=net-6.0) and it is not very clear how to use it, I cannot find any documentation explaining it.

If e.g. I have an html video element and I register a callback method for event ontimeupdate
`<video @ontimeupdate="OnTimeUpdate"><source ...></video>`
`@code {
    private void OnTimeUpdate(EventArgs e) {
        // how can I use argument?
    }
}`
it is not clear how I'm supposed to retrieve data like current playback time.

### Describe the solution you'd like

Wouldn't it make sense to have a more specific data type for events argument instead of the generic EventArgs?

**Comment by AlessandroMartinelli** [comment]
Hi, thank you for the answer. 
By "query the element attribute" I suppose you mean by means of javascript interop, since from what I understand there is no way of accessing element attributes directly in Blazor, is it correct?

**Comment by javiercn** [comment]
@AlessandroMartinelli Yes.

That's why I suggested the custom event route. You can enrich the event to capture that info directly from JavaScript.
