### ISSUE TITLE
Add ability to register IHubContext<T> service in DI

### ISSUE THREAD

**Issue by ayelchin** [dotnet/aspnetcore#41538]
## Summary

You can't access generic interface `IHubContext` outside of web project, even if you use `Microsoft.AspNetCore.SignalR` NuGet package. Hubs are created within Web project, therefore right now you are required to reference Web project to use IHubContext<T>.
Add possibility to register `IHubContext` specifying concrete `Hub`.

## Motivation and goals

This would enable to use `IHubContext` without direct reference to specific `Hub`, therefore leaving ability for client(outside) to pass specific implementation `IHubContext<T>`.

## In scope

I think one of the part was discussed in #30167 but right now only with `Microsoft.AspNetCore.App` framework there is an access to non-generic `IHubContext`.

## Out of scope

N/A.

## Risks / unknowns

Nothing comes to mind.

## Examples

Imagine following layers:

- Application
- Infrastructure
- WebApi

Application layer contains `INotificationService` interface. 
Infrastructure layer implements `SignalRDispatchService : INotificationService`.
WebApi has `MyHub : Hub`.

Inside application layer there is a UseCase, which has its own business logic and at the end it calls `INotificationService`. `INotificationService` is implemented by `SignalRDispatchService`, which should send message to all clients, with new notification.
Because WebApp runs the app, it has a reference to the Infrastructure layer, to register all required dependencies in DI. `SignalRDispatchService` can't reference WebApi, since it will result with a circular dependency.

Would be great to have some kind of factory, which would register specific clients.
**WebApi, Startup:**
```
...
builder.Services.AddHubContext<MyHub, SignalRDispatchService>();
...
```

**Infrastructure, SignalRDispatchService:** 
```
public class SignalRDispatchService : INotificationService
{

    public SignalRDispatchService(IHubContext hubContext)
    {
        _hubContext = hubContext;
    }

    public async Task SendNotification(MyRequest request)
    {
        ...
        await _hubContext.Clients.Group(request.GroupName).SendAsync("myMethod", request.Message);
        ...
    }
}
```

P.S. If this whole idea is not looking good and if there are clean workarounds, please suggest some.

Thank you.

**Comment by davidfowl** [comment]
The infrastructure layer cannot implement `SignalRDispatchService`, it needs to go into the web layer. The infrastucture layer can use the `INotificationService`. That's your abstraction that can be used anywhere but the SignalR implementation is tied to the web project.

**Comment by ayelchin** [comment]
@davidfowl, yes that's what I did for now, I have put `SignalRDispatchService` into web project but if we talk in context of Clean Architecture, I don't feel good putting it there, since in WebApi I should implement output ports.

**Comment by BrennanConroy** [comment]
`IHubContext` exists today without a reference to a specific Hub type. This allows you to pass an `IHubContext<MyHub>` to other layers that don't have access to the specific Hub type.

If you want this to work with DI, you should be able to write something like:
```csharp
services.AddSingleton(provider =>
{
    var context = provider.GetRequiredService<IHubContext<MyHub>>();
    return new SignalRDispatchService((IHubContext)context);
});
```

**Comment by ayelchin** [comment]
@BrennanConroy 
Oh nice! Thanks, that will do a job. I have tested it and it works if `SignalRDispatchService` is placed in WebApi project but still I can't do it in library.
I can't access generic interface `IHubContext`. I have tried to use `Microsoft.AspNetCore.SignalR`,  `Microsoft.AspNetCore.SignalR.Common`, `Microsoft.AspNetCore.SignalR.Core` and `Microsoft.AspNetCore.SignalR.Client` NuGet packages. 
Seems like generic interface is only accessible via framework. Am I missing something?

**Comment by ShreyasJejurkar** [comment]
By Clean architecture principles `SignalRDispatchService` should exist in WebApp, as it deals with output things in this case Web layer. There is no point in keeping `SignalRDispatchService` in the infrastructure layer, as SignalR itself is built upon web sockets which is an HTTP feature so it has to be in the Web layer. 

It would have made sense to keep SignalR service in the infra layer if it would have worked without the web which it doesn't!

**Comment by ArminShoeibi** [comment]
> @BrennanConroy Oh nice! Thanks, that will do a job. I have tested it and it works if `SignalRDispatchService` is placed in WebApi project but still I can't do it in library. I can't access generic interface `IHubContext`. I have tried to use `Microsoft.AspNetCore.SignalR`, `Microsoft.AspNetCore.SignalR.Common`, `Microsoft.AspNetCore.SignalR.Core` and `Microsoft.AspNetCore.SignalR.Client` NuGet packages. Seems like generic interface is only accessible via framework. Am I missing something?

Hello there @ayelchin, Please reference the framework instead of installing Nuget packages.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore

**Comment by ayelchin** [comment]
Thank you all for the suggestions and help!
I have options to go with, will consider all of them.
