### ISSUE TITLE
HttpClient from HttpClientFactory is faulty after call to offline Redis cache

### ISSUE THREAD

**Issue by pbfrederiksen** [dotnet/aspnetcore#41553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue was also posted on StackExchange.Redis, but was dismissed by one of the contributers - because SE.Redis does nothing with http.
[Issue 2128](https://github.com/StackExchange/StackExchange.Redis/issues/2128)

I hope someone here can help me with this weird behavior.

I am using the Redis cache with the nuget package Microsoft.Extensions.Caching.StackExchangeRedis.
I made my cahce service so it would return null if the Redis cache database is offline.
But I experience some weird behavior: After a call to the offline Redis cache, my other service calls will fail with an error that includes an url to the Redis cache backend (database).

This only happens if I use IHttpClientFactory to create a HttpClient and configure AccesTokenManagement for a named client - if I create a new HttpClient or do not configure AccessTokenManagement I do not get the above error.

Kind regards
Peter Bøtker Frederiksen

### Expected Behavior

I expect my other service calls that are independent of the Redis cache, to continue to work when the Redis cache is offline.

### Steps To Reproduce

[Repro project in GitHub](https://github.com/pbfrederiksen/RedisConnectionFaultRepro)

### Exceptions (if any)

`StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: HMGET IdentityModel.AspNetCore.AccessTokenManagement::TestClient::; UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.4.27433, mc: 1/1/0, mgr: 10 of 10 available, clientName: WSPEBOFR, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767), v: 2.2.4.27433`
and
`UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.4.27433`

### .NET Version

6.0.202

**Comment by adityamandaleeka** [comment]
Looks like you've figured this out. Closing the issue.
