### ISSUE TITLE
Blazor Server App - Rename default .AspNetCore. cookie name

### ISSUE THREAD

**Issue by Huntk23** [dotnet/aspnetcore#41560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having a difficult time renaming the `.AspNetCore`. cookie in a Blazor Server App. I cannot find any documentation or past/current issues with the same or similar problem.

Create a brand new Blazor Server App and attempt modifying the `.AspNetCore.` default application cookie name.

Can this default cookie be edited in Blazor Server App?

### Expected Behavior

The cookie `.AspNetCore.` to be renamed with one of the following methods in the reproduce section.

No matter what I do, I cannot get the cookie to rename:

![image](https://user-images.githubusercontent.com/3951241/167185784-913c1477-0504-499a-9543-8b432ccb5558.png)

### Steps To Reproduce

1. Create a brand new Blazor Server App with SDK 6.0.202
2. Choosing with or without Authentication shouldn't matter
    - Happening on both for me
3. Attempt renaming the cookie

```cs
builder.Services.ConfigureApplicationCookie(x => x.Cookie.Name = ".NewCookieName.");

var app = builder.Build();
```

```cs
builder.Services.ConfigureExternalCookie(x => x.Cookie.Name = ".NewCookieName.");

var app = builder.Build();
```

```cs
builder.Services.Configure<CookieAuthenticationOptions>(x => x.Cookie.Name = ".NewCookieName.");

var app = builder.Build();
```

```cs
builder.Services.ConfigureApplicationCookie(x => x.Cookie.Name = ".NewCookieName.");
builder.Services.ConfigureExternalCookie(x => x.Cookie.Name = ".NewCookieName.");
builder.Services.Configure<CookieAuthenticationOptions>(x => x.Cookie.Name = ".NewCookieName.");

var app = builder.Build();
```

 Making sure these calls all happen just before the `builder.Build()`

In the authentication example for Microsoft Identity with Azure AD, only difference is these methods are called before trying to modify the cookie name:

```cs
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection(nameof(AzureAd)));
builder.Services.AddControllersWithViews()
    .AddMicrosoftIdentityUI();
```

### .NET Version

6.0.202

**Comment by Tratcher** [comment]
AddMicrosoftIdentityWebApp has an overload that will let you change the CookieAuthenticationOptions and rename the cookie.

**Comment by Huntk23** [comment]
> AddMicrosoftIdentityWebApp has an overload that will let you change the CookieAuthenticationOptions and rename the cookie.

Incredible! I don't know how I missed that overload.

Fixed by changing to:

```cs
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(x => builder.Configuration.GetSection(nameof(AzureAd)).Bind(x), options => options.Cookie.Name = ".NewCookieName.");
```

@Tratcher Thank you!
