### ISSUE TITLE
Rendering Blazor Custom Element from Leaflet

### ISSUE THREAD

**Issue by mu88** [dotnet/aspnetcore#41577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my [app](https://github.com/mu88/Project28/), I'm combining the JS mapping framework [Leaflet](leafletjs.com/) and Blazor Server. I have a Blazor component `LifePointDetail.razor` which is embedded into a Leaflet popup as a [Blazor Custom Element](https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements):
```js
let marker = L.marker([latitude, longitude]);
marker.bindPopup("<life-point-detail></life-point-detail>");
marker.addTo(leafletMap);
```

This works fine so far, but I'm stumbling across an issue which I don't know how to solve: Leaflet popups have the ability to automatically pan the map when opening a popup ([see docu](https://leafletjs.com/reference.html#popup-autopan)). But in conjunction with my Blazor Custom Element, this doesn't work. Please see the following screenshot to better understand the problem:  
![image](https://user-images.githubusercontent.com/4560672/167306291-011d3b54-b6f6-4163-a81d-afae89fb96a4.png)

### Expected Behavior

Instead, it should look like this after clicking the marker and opening the popup:  
![image](https://user-images.githubusercontent.com/4560672/167306280-6b5be58c-4015-4ee7-8db8-f8d1bd83b16e.png)

Please note that in a vanilla Leaflet application, you don't have to pan manually: the popup automatically gets centered in the middle so that it is completely visible.

### Steps To Reproduce

1. Create a Blazor app.
2. Create a very basic Blazor component `MyBlazorComponent` and make it a Blazor Custom Element.
4. Add this Blazor component to a Leaflet popup:  
```js
let marker = L.marker([latitude, longitude]);
marker.bindPopup("<my-blazor-component></my-blazor-component>");
marker.addTo(leafletMap);
```

### .NET Version

6.0.202

### Anything else?

The guys on the Leaflet side don't consider this a bug on their side ([see related issue](https://github.com/Leaflet/Leaflet/issues/8217)). So I'm in a typical sandwich position 🤷🏻‍♂️

I assume it could be related to some sort of timing: when Leaflet renders `marker.bindPopup()`, the Blazor Custom Element `<my-blazor-component>` is not yet ready rendered. Therefore the components extent (width and height) are not yet known/accessible for Leaflet - maybe `width` and `height` are `0` at a certain point in time when Leaflet tries to render them?

**Comment by mu88** [comment]
@danroth27 @SteveSandersonMS FYI

**Comment by javiercn** [comment]
@mu88 thanks for contacting us.

It's a bit hard for us to follow a repro of this size. So I'm going to try and give you some pointers to see if it helps you unblock yourself.

> I assume it could be related to some sort of timing: when Leaflet renders `marker.bindPopup()`, the Blazor Custom Element `<my-blazor-component>` is not yet ready rendered. Therefore the components extent (width and height) are not yet known/accessible for Leaflet - maybe `width` and `height` are `0` at a certain point in time when Leaflet tries to render them?

I don't know for sure the sequence of events that result in the rendering, but I would suggest a few things:
* Give the custom element an initial height and width via CSS using `:not(:defined) { }`.
* Add console log traces to identify the sequence of events (confirm that the component is rendering afterwards hence the `0` width and length).
* If the last statement in your snippet triggers everything, then it's a problem.
  * If this is not the case, you could try to wait until the component has been rendered by triggering an event inside OnAfterRender.

Let us know if you are stuck after trying these suggestions out and we might be able to offer further guidance.

**Comment by mu88** [comment]
Thank you @javiercn for your super fast feedback! I've condensed my example to the bare minimum: https://github.com/mu88/BlazorLeafletTest  
Hopefully that makes life easier.

Please take a look on the generated output:
```
[17:14:43 INF] Start createMarker
[17:14:43 INF] Marker created
[17:14:43 INF] Popup bound
[17:14:43 INF] Marker added to map
[17:14:43 INF] Map-OnAfterRenderAsync
<<< Here I click on the marker to open the popup >>>
[17:14:58 INF] LifePointDetail-OnInitializedAsync
[17:14:58 INF] LifePointDetail-OnAfterRenderAsync
```

The first four log statements are coming from the JS code inside `LifePointDetail.razor.js` which generates the popup for the marker.  
If I'm correct, my Blazor Custom Element `<life-point-detail>` gets rendered when opening the popup. Probably that is too late, it should be between `[17:14:43 INF] Marker created` and `[17:14:43 INF] Popup bound`, am I right?

**Comment by javiercn** [comment]
@mu88 I think what's happening here is "by design". As per the comment in the lines below:
https://github.com/aspnet/AspLabs/blob/main/src/BlazorCustomElements/src/Microsoft.AspNetCore.Components.CustomElements/js/BlazorCustomElements.ts#L42-L47

I suspect that when rendering as a custom element you'll have to account for the element being defined but not yet rendered. It is not clear that we can do something here since I believe there are technical reasons why its done this way.

Essentially what's happening is that the element is added, but the render with the actual content doesn't happen until the UI thread becomes "idle" (this is somewhat of an oversimplification).

There are several things that you could try to overcome this:
* Use CSS to provide the element size ahead of time.
* Check if there is a method you can trigger to update the popup to react to the size change when the render happens.
* Check if you can provide some content or wrap the custom element in some other element with a defined size.

**Comment by SteveSandersonMS** [comment]
Looks like this would be handled by calling Leaflet's `update` method after the DOM content is rendered (e.g., in Blazor's `OnAfterRenderAsync`) as suggested at https://github.com/Leaflet/Leaflet/issues/8217#issuecomment-1121436852.

**Comment by mu88** [comment]
Thank you @SteveSandersonMS ! I tried this approach today as you can see in my [latest commit](https://github.com/mu88/BlazorLeafletTest/commit/64ab46f9bc207b2a3fa9768a44332a7b65fa17fe). Now I have the following situation:
- The popup remains completely empty (no content at all).
- The [`_lifePointDetailModule`](https://github.com/mu88/BlazorLeafletTest/blob/master/src/WebApp/Shared/LifePointDetail.razor#L36) (the Blazor reference to the JS file `LifePointDetail.razor.js` where the marker's popup `update()` happens) is sometimes `null` and sometimes not.
- The Leaflet code to `marker.getPopup().update()` is called very often and not only once, as you can see in the [BlazorLeafletTest.log](https://github.com/dotnet/aspnetcore/files/8686008/BlazorLeafletTest.log). Please notice that this log output is the result of a single click on the marker, not several clicks.

**Comment by SteveSandersonMS** [comment]
@mu88 I'm afraid that debugging into 3rd-party JS code is outside the scope of what we have capacity to do in this issue tracker. I know it's tricky when you have an issue that falls in the interaction between separate technologies.

**Comment by mu88** [comment]
I could solve it 💪🏻 instead of calling `marker.getPopup().update()`, I had to do the following:
```js
let popup = marker.getPopup();
popup._updateLayout();
popup._updatePosition();
popup._adjustPan();
```

This is exactly the same code as [Leaflet's original](https://github.com/Leaflet/Leaflet/blob/main/src/layer/DivOverlay.js#L170), except that `popup._updateContent();` isn't called. Doing so triggers an infinite loop between Leaflet trying to render the popup, Blazor creating its component and afterwards updating the popup, Leaflet trying to render the popup again, etc. This infinite loop will be interrupted sometime by the browser.
