### ISSUE TITLE
Blazor Css Isolation Is Not Recognized in Maui-Blazor WinUI Application

### ISSUE THREAD

**Issue by salghazaly** [dotnet/aspnetcore#41594]
Hi, this is a known issue and is fixed in the upcoming preview 7 update.

_Originally posted by @Eilon in https://github.com/dotnet/aspnetcore/issues/35195#issuecomment-895599806_

I have faced this issue in the candidate release also
I think it's not solved yet

**Comment by Eilon** [comment]
Hi @salghazaly , we're not aware of any issues with CSS isolation in .NET MAUI Blazor apps. If you are using the most recent release candidate and still have an issue, please file a new issue at https://github.com/dotnet/maui/issues with detailed steps to reproduce the issue, as well as information about what error(s) you are seeing (please include logs or screenshots).
