### ISSUE TITLE
Kestrel WebSocket AcceptWebSocketAsync NRE

### ISSUE THREAD

**Issue by mishhan** [dotnet/aspnetcore#41602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi!

I'm building library which encapsulates web-server for WebSocket connection using `Kestrel` (let's name it **A**)

```c#
/* simple version of my code */
var hostBuilder = new WebHostBuilder()
	.UseKestrel()
	.UseUrls("http://127.0.0.1:8008/");
hostBuilder.Configure(app =>
{
	app.UseWebSockets();
	app.Run(async context =>
	{
		if (context.WebSockets.IsWebSocketRequest)
		{
			await context.WebSockets.AcceptWebSocketAsync(); // throws NRE at ConnectAsync request
			Console.WriteLine("Connected");
		}
	});
});
var host = hostBuilder.Build();
host.Start();
```

In my specific case:
dinamic link library **A** is loaded in my project in runtime using

```c#
Assembly.LoadFrom(assemblyPath);
...
Activator.CreateInstance(...);
```
Which means I need all dependent dlls in output folder where my main application starts, so all dependecies could be resolved in runtime.

Problem with websockets was already discussed here
- https://github.com/dotnet/aspnetcore/issues/28112
- https://github.com/dotnet/aspnetcore/issues/29884
- https://github.com/dotnet/aspnetcore/issues/41416

According to https://github.com/dotnet/aspnetcore/issues/28112#issuecomment-733635589 the problem only appears if `Microsoft.Extensions.Configuration` greater than 2.2.0 is used.

In my specific case:
dependencies from other projects use `Microsoft.Extensions.Configuration` 5.0.0 so I can't use 2.2.0

I tried solution mentioned here https://github.com/dotnet/aspnetcore/issues/28112#issuecomment-733662430 :

```csproj
<ItemGroup>
+    <FrameworkReference Include="Microsoft.AspNetCore.App" />
-    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
</ItemGroup>
```
but for project with 
```csproj
<OutputType>Library</OutputType>
```
_FrameworkReferenced_ dlls aren't copied in output folder 😞 even with flags (but referenced nuget packages are copied)
```csproj
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

So if I use

```csproj
<ItemGroup>
   <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```

I got 
```Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'```

But if I manually copy all runtime dlls from folder: `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.4` to output folder, everything works fine.

Reading comments from other issues and migration guide, I'm still not sure what to do in my case and how to make it work 😢
I mean, I don't understand is there problem with my approach? Will the problem with `Microsoft.Extensions.Configuration` be fixed or I should change my approach?
 
Is there any workaround for my problem, at the moment?

Same mechanism with `HttpSys` works fine.

Thank you in advance!

### Expected Behavior

WebSocket connection accepted without NRE.

### Steps To Reproduce

Reproduction of problem with websockets - https://github.com/mishhan/kestrel-websocket-bug-repro
Simple reproduction of my specific case - https://github.com/mishhan/kestrel-webscocket-activator-bug-repro

### Exceptions (if any)

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FlushAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpUpgradeFeature.UpgradeAsync()
   at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.UpgradeHandshake.AcceptAsync(WebSocketAcceptContext acceptContext)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() at C:\Users\misha\source\repos\KestrelWebSocket\KestrelWebSocket\Program.cs:строка 22

### .NET Version

6.0.200

**Comment by Tratcher** [comment]
Why do you use `Assembly.LoadFrom` rather than having a directly dependency on the library? A direct dependency would allow the compiler to resolve these dependency mismatches for you.

`<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />` must not be used with any application running on .NET Core 3 or later, so it's not going to work in your .NET 6 app. `<FrameworkReference Include="Microsoft.AspNetCore.App" />` is the correct dependency for .NET 6.

**Comment by mishhan** [comment]
@Tratcher,

> `<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />` must not be used with any application running on .NET Core 3 or later, so it's not going to work in your .NET 6 app. <FrameworkReference Include="Microsoft.AspNetCore.App" /> is the correct dependency for .NET 6.

Ok, got it, so it means I have to somehow "deliver" all dlls in output folder.

> Why do you use Assembly.LoadFrom rather than having a directly dependency on the library? A direct dependency would allow the compiler to resolve these dependency mismatches for you.

Yeah, I tried that and it works... 
To explain why I don't use it I'll provide a bit of context. The whole app looks like this:
```
MainApp (depends on Common)
Common (contains IWebServer) - based on the environment loads WebServer.[Windows/Linux].dll
... other stuff...
WebServer.Windows - HttpSys (contains HttpSysWebServer which implements IWebServer)
WebServer.Linux - Kestrel (contains KestrelWebServer which implements IWebServer)
```

I don't want my `MainApp` to "know" about these projects (`WebServer.Windows`, `WebServer.Linux`) directly. That is why I don't have them as direct dependency. 
So at the execution time I take environment-specific dll, load it into the app and it works (at least with HttpSys).

Is it possible to add all dlls in output folder using `<FrameworkReference Include="Microsoft.AspNetCore.App" />`  with my approach? I suppose that is the only way to make it work in my case.

It just looks kinda strange (at least from my point of view) that `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` works for `PackageReference` but doesn't work for `FrameworkReference` which would solve my case.

**Comment by davidfowl** [comment]
Just remove those package dependencies and use a framework reference. Your host application should also have that same framework reference and it will work like magic 😄
