### ISSUE TITLE
Blazor Webassembly SEO - Links are not crawled - Lighthouse

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#41600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Standalone Blazor Web assembly, I noticed that the index.html has a default error handler, and it adds 2 `<a>` elements for reloading and dismissing the error.

```
<div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
```

Running the Lighthouse on the web app shows the report below. None of the anchors could be crawled.

![image](https://user-images.githubusercontent.com/13166236/167524444-88a897f7-dc44-4e9e-b5c5-8d1af03bdb4b.png)

How to fix this ?

**Comment by javiercn** [comment]
@ameyasubhedar thanks for contacting us.

You can update the code in the template to provide an alternative way to display errors or remove the snippet altogether. See https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#detailed-errors-during-development for details.
