### ISSUE TITLE
E2E tests ignore javascript errors

### ISSUE THREAD

**Issue by kg** [dotnet/aspnetcore#41607]
If a javascript error occurs during execution of an E2E test, it's ignored and not surfaced to the console or logs. If it causes an assertion to fail (due to missing content, etc) the test will "fail" but you will have no way to see that the JS error caused it. If the assertions pass, everything looks good which is a really bad outcome.

I think chromedriver probably has a way to get logged errors, but if not the E2E tests should register an unhandled error handler on the window so they can propagate this out somehow (maybe into a hidden dom element that the test runner checks at the end).

An easy way to reproduce this is to shove a setTimeout that throws an error somewhere in the blazor code (this sample code is from a blazor bug I'm troubleshooting), like:

```javascript
  private insertText(batch: RenderBatch, parent: LogicalElement, childIndex: number, textFrame: RenderTreeFrame) {
    let textContent = batch.frameReader.textContent(textFrame)!;
    if (typeof (textContent) !== "string") {
      textContent = "";
      window.setTimeout(() => {
        throw new Error(`Found non-string in batch text content with parent ${parent}`);
      }, 1);
    }
    const newTextNode = document.createTextNode(textContent);
    insertLogicalChild(newTextNode, parent, childIndex);
  }
```

This will produce an error in the browser console, but the test will not fail or dump the error to stdout/stderr, even if you sleep before your assertions to give time for the error to fire. If you turn the setTimeout into a regular throw, the test will fail.
![image](https://user-images.githubusercontent.com/198130/167662433-85dfbf4b-3340-4658-b108-24688849e0b9.png)

![image](https://user-images.githubusercontent.com/198130/167662699-37b76708-f19b-4a3b-8d29-28d27c3188ae.png)

**Comment by TanayParikh** [comment]
> we normally don't check for errors on the console to drive the outcome of tests

and in the _rare_ cases that we do need the console output, it's down as per below:

https://github.com/dotnet/aspnetcore/blob/7259991b5d2ecef36979fd55e48884de8d69f114/src/Components/test/E2ETest/ServerExecutionTests/ServerReconnectionTest.cs#L81-L82

**Comment by javiercn** [comment]
@kg we pipe this to the ITestOutput (or whatever is called) from xUnit. At the very least it shows up in Visual Studio.

**Comment by mkArtakMSFT** [comment]
@javiercn looks like this has been answered. Did you want to keep this around for something else, or should we close it now?

**Comment by MackinnonBuck** [comment]
Closing this out. Let's reopen a new issue if we need to further address anything in this area.
