### ISSUE TITLE
Blazor webassembly Hosting Problem

### ISSUE THREAD

**Issue by douglassimaodev** [dotnet/aspnetcore#41604]
Hi, 

I know we can find a lot of post about this here but none solve my problem..

Steps:

Create new blazor webassembly with PWA support, framework 6.0
Either SPA or asp.net Hosted (no authentication)

When I simply publish it and copy the files over to IIS server folder
HTTPS configured via LetsEncrypt

When I open in Chrome for the first time all fine, then when I try to reload it, either by hitting F5 or from reload in chrome then I get the error:
Failed to find a valid digest in the 'integrity' attribute for resource 'https://xxxxxx/_framework/dotnet.6.0.0.w1ug730vgp.js' with computed SHA-256 integrity 'GypavvZZdIRFqAx5L67eifOe8jYJHMy0tA6zNnh8t18='. The resource has been blocked.

if I press CTRL +F5 then it loads fine, any navigation from the app menu works fine too

In Edge it does not work at all

If I create a Blazor webassembly without PWA support it works fine in Chrome, in Edge only in private mode so even me cleaning the cache seems to have something saved there that is not working

If I create a Blazor server side then everything works fine

Any Idea?

**Comment by javiercn** [comment]
@douglassimaodev thanks for contacting us.

When you say IE, do you mean internet explorer or Edge.

**Comment by douglassimaodev** [comment]
I configure the Pipeline (Release) in azure to delete all previous file before publishing,   

also I am running  iisreset in the server just to be sure

995.4MB used out of 4047 MB storage quote

All fines ddls status 304 other files getting 200  and service-worker.js status (pending)


`blazor.webassembly.js:1 Uncaught (in promise) Error: Blazor has already started.
    at Object.At [as start] (blazor.webassembly.js:1:55685)
    at login:31:16`
    
    and  login:1 Failed to find a valid digest in the 'integrity' attribute for resource

**Comment by javiercn** [comment]
@douglassimaodev I'm trying to determine if some config in IIS or the browser is causing older files to be served/cached. In general, this issue is caused by two reasons:
* Some file is not accessible (server returns 404)
* The file wasn't updated correctly on the server (it was not updated or it was manipulated after the publish gesture).
* The file being returned is different from the file on the server.
* There is a mismatch between the hash inside blazor.boot.json or service-worker-assets.js of the actual file.
  * You could try to perform a clean build (if your CI doesn't already do so). making sure you remove the contents of the bin and object folders.

**Comment by douglassimaodev** [comment]
Hi @javiercn , Yes my CI is deleting everything before publishing, I have no 404 files in network tab, but I will try to re publish it again

**Comment by douglassimaodev** [comment]
I am not fully sure what it will impact but I changed service-worker.published.js

from   await caches.open(cacheName).then(cache => cache.addAll(assetsRequests)); to  await caches.open(cacheName).then(); 

removed cache => cache.addAll(assetsRequests) and it is working fine

**Comment by javiercn** [comment]
@douglassimaodev thanks.

I think we'll have to do some digging here to see what might be going wrong.

**Comment by douglassimaodev** [comment]
nevermind I am still getting after a while the same error even removing that cache thing,...

Failed to find a valid digest in the 'integrity' attribute for resource 'https://xxxx/_framework/dotnet.6.0.0.w1ug730vgp.js' with computed SHA-256 integrity 'GypavvZZdIRFqAx5L67eifOe8jYJHMy0tA6zNnh8t18='. The resource has been blocked.

**Comment by douglassimaodev** [comment]
Hi,

Again, I am not sure what it will impact in a blazor webassembly with pwa support, but I added this in my .csproj file
<BlazorCacheBootResources>false</BlazorCacheBootResources>

I still have service-worker.published.js await caches.open(cacheName).then(); and till now so far it is up and running

**Comment by javiercn** [comment]
@douglassimaodev at this point we are likely going to spend some cycles looking at the area, but we have to prioritize it in comparison to other tasks and plan for that in a future sprint so it will take some time for us before we can look in more detail and get back to you.
