### ISSUE TITLE
OpenAPI Client Generator, Generating multiple clients named same thing.

### ISSUE THREAD

**Issue by maxfridbe** [dotnet/aspnetcore#41627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is similar to bug [21656](https://github.com/dotnet/aspnetcore/issues/21656). But the underlying causes are different

I have a OpenAPI json file which I believe is to spec (below) it generates multiple clients in the same namespace offering me no way to make only one client or to separate the clients name. I have tried the workaround in [21656](https://github.com/dotnet/aspnetcore/issues/21656) and it does not seem to work.

### Expected Behavior

That i can specify something like
      <ClassName>{tags}Client</ClassName>
under <OpenApiReference>
So that the client generates properly, 
Or that the client generates properly under one client name as this has no collisions in the JSON, so I am unsure why the tool is doing this.

### Steps To Reproduce

Generate a Client in vs 2022 based on this JSON FILE:
https://devopsishealthy.kldev.io/api/openapi/V2_JSON?domain=https://devopsishealthy.kldev.io

### Exceptions (if any)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0102	The type 'cli' already contains a definition for '_baseUrl'	ConsoleApp2	C:\Users\Developer\source\repos\ConsoleApp2\ConsoleApp2\obj\V2_JSON1Client.cs	614	Active
Error	CS0102	The type 'cli' already contains a definition for '_httpClient'	ConsoleApp2	C:\Users\Developer\source\repos
.... etc
```

### .NET Version

6.0.202

### Anything else?

Visual Studio 2022

info:

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by maxfridbe** [comment]
Actually I retested the workaround by deleting the obj folder and that seems to have worked.
 <ClassName>{controller}Client</ClassName>

**Comment by BrennanConroy** [comment]
Glad you solved the issue, we'll keep tracking the original report with https://github.com/dotnet/aspnetcore/issues/21656
