### ISSUE TITLE
CSS Isolation & RCL Support does not generate the correct CSS import for WASM Apps not hosted at root

### ISSUE THREAD

**Issue by philip-reed** [dotnet/aspnetcore#41625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documentation here states that CSS from the RCL's stylesheet is imported at the top of the app's stylesheet:

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#razor-class-library-rcl-support

However, if the Blazor app is not hosted from root (for example where multiple WASM apps are being hosted from a single server at different urls), the URL created in the import statement ignores the `StaticWebAssetBasePath`.

However the documentation for hosting multiple WASM applications states that RCL CSS should be added manually to index.html

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#static-assets-and-class-libraries-for-multiple-blazor-webassembly-apps

Adding the RCL CSS this way solves the problem, but the RCL is still also imported into the parent app CSS, and results in a 404.
However adding the base path to the imported css file path results in a 200.

![image](https://user-images.githubusercontent.com/7798175/167867338-a14922af-7da0-42a5-89fb-c9a5e8785f06.png)

### Expected Behavior

Either the CSS Import should use the correct url, or there should be a way to disable the import statement and link the css manually in Index.html

### Steps To Reproduce

Example App here:
https://github.com/philip-reed/HostedBlazorWithBaseHrefCss

The BlazorApp1.Client has a reference to RasorClassLibrary1 which has a SharedCounter component with custom CSS.
BlazorApp1.Client is served from /demo

![image](https://user-images.githubusercontent.com/7798175/167867972-9cd3db97-edd2-4f7d-8376-b536cc7d3e42.png)

### Exceptions (if any)

NONE

### .NET Version

6.0.201

### Anything else?

Visual Studio 2022 - Running locally
ASPNETCORE_ENVIRONMENT=Development

**Comment by javiercn** [comment]
@philip-reed thanks for contacting us.

Your app is missing `app.UseBasePath("/demo")` here: https://github.com/philip-reed/HostedBlazorWithBaseHrefCss/blob/main/BlazorApp1/Server/Program.cs#L30

**Comment by philip-reed** [comment]
@javiercn 

Thanks for taking a look.
I assume you mean to use `UsePathBase(baseRef)`? 
If so, then I don't think this has made a difference.

I have updated the repro with this included.

**Comment by philip-reed** [comment]
Sorry I misread that document, it seems you use one or the other when using the Blazor Server hosting model.
But for standalone, it says to use both.

It isn't clear what to use when using the Hosted Wasm model.

**Comment by javiercn** [comment]
Alternatively
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
}
else
{
    app.UseExceptionHandler("/Error");
}

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.MapRazorPages();
app.MapControllers();
app.MapFallbackToFile("/demo/{*path:nonfile}", "/demo/index.html");

await app.RunAsync();
```

**Comment by philip-reed** [comment]
@javiercn 

The last code sample you provided seems to do the job for me too, thank you.
I landed on this issue when hosting multiple Blazor clients from the same hosted server.
This is why the code in the demo app uses `app.UseWhen` to try and match the route for the specific client app.

If its not too much to ask, what would this look like if a second Blazor Client project was added?
And the second client also had a reference to the shared counter component?

**Comment by guardrex** [comment]
@philip-reed ... When you reach a final working approach based on @javiercn's remarks, please comment on the docs issue that I opened at ...

https://github.com/dotnet/AspNetCore.Docs/issues/25836

... with the changes you made to your repro project at ...

https://github.com/philip-reed/HostedBlazorWithBaseHrefCss

... to get it working. That will aid in updating docs for this scenario.

**Comment by philip-reed** [comment]
@javiercn  

I have tried what you suggested and have pushed another branch named `multipleClients` which contains a second Blazor client.  I fear I have missed something as the app1 fails to load, and app2 gets a 404.

![image](https://user-images.githubusercontent.com/7798175/167912935-d0c5d109-e752-41b4-8610-093e325b82a3.png)
![image](https://user-images.githubusercontent.com/7798175/167912970-aed1b313-8c1a-480d-b092-287eaa95e56c.png)

**Comment by philip-reed** [comment]
Is this documentation also out of date perhaps?

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-multiple-blazor-webassembly-apps

![image](https://user-images.githubusercontent.com/7798175/167914560-ac76c1bc-065f-47d1-995b-02048bb6704c.png)

**Comment by philip-reed** [comment]
Leaving this for today, will pick up again tomorrow, family time :)
Thanks for your help so far.

**Comment by javiercn** [comment]
@philip-reed no worries. We are working on getting the docs updated.

**Comment by guardrex** [comment]
@javiercn ... The guidance in that section worked for me recently when discussing a scenario with a reader who was implementing it for a production app that ran on subdomains and with RP/MVC support. There were no problems locating stylesheets at that time ... nor any failures with the apps running and rendering components/pages/views.

I think I'll need to work through it with @philip-reed's repro and your remarks here. You might close this issue and let the docs issue cover it.

@philip-reed ... I'm a bit buried ⛰️⛏️😅 at the moment in Blazor Hybrid work. I'll be free ... **_or free-er-ish_** 😄 really ... on Friday or Monday.
