### ISSUE TITLE
dotnet watch does not apply changes in razor page

### ISSUE THREAD

**Issue by wondertalik** [dotnet/aspnetcore#41645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Helo, after upgrading from 6.0.4 (x64) to 6.0.5 hot reload is not working. Should restart manualy. Downgrade to 6.0.4 solved my problem. I tried on 3 different computers with mac os Monterey. Result is the same.

```
dotnet watch ⌚ File changed: ./Areas/Identity/Pages/Account/RegisterCompany.cshtml.
dotnet watch ⌚ No hot reload changes to apply.

```

### Expected Behavior

Apply hot reload

### .NET Version

6.0.300

### Anything else?

IDE: Rider, VS code

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  3.1.404 [/usr/local/share/dotnet/sdk]
  3.1.405 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  3.1.408 [/usr/local/share/dotnet/sdk]
  3.1.409 [/usr/local/share/dotnet/sdk]
  3.1.418 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]
  5.0.407 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by TanayParikh** [comment]
@wondertalik can you please provide a minimal, public, github repository which reproduces this issue?

**Comment by wondertalik** [comment]
> @wondertalik can you please provide a minimal, public, github repository which reproduces this issue?

yes, i will try to prepare this weekend. thanks

**Comment by javiercn** [comment]
@mkArtakMSFT I did a quick test for this and I was not able to reproduce it.

![image](https://user-images.githubusercontent.com/6995051/168813528-99e978f3-572c-4329-9524-4bdad3e47f4b.png)

I think as @TanayParikh mentioned we need a repro here.

**Comment by javiercn** [comment]
@wondertalik One thing to try out would be to remove the bin and obj folders and see if the problem goes away. It might be something got incorrectly cached between the builds when you updated 6.0.4 to 6.0.5

**Comment by wondertalik** [comment]
Hi all.

sorry for being a little late, trying to find the problem

> @wondertalik One thing to try out would be to remove the bin and obj folders and see if the problem goes away. It might be something got incorrectly cached between the builds when you updated 6.0.4 to 6.0.5
Did it. The same.

So, [example](https://github.com/wondertalik/dotnet_issue_41645). I tried to leave all as simple as possible.

Result like i said with 6.0.5 doesnt work, 6.0.4 everything ok.

6.0.4
```
/usr/local/share/dotnet/dotnet watch run
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  YourJobsApp -> /Users/aa/dotnet_issue_41645/src/YourJobsApp/bin/Debug/net6.0/YourJobsApp.dll
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7074
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5055
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/aa/dotnet_issue_41645/src/YourJobsApp/
watch : File changed: /Users/aa/dotnet_issue_41645/src/YourJobsApp/Pages/Index.cshtml.
watch : Hot reload of changes succeeded.

```

6.0.5

```
➜ YourJobsApp git:(main) ✗ dotnet watch run
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
Determining projects to restore...
All projects are up-to-date for restore.
YourJobsApp -> /Users/bb/dotnet_issue_41645/src/YourJobsApp/bin/Debug/net6.0/YourJobsApp.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
Now listening on: https://localhost:7074
info: Microsoft.Hosting.Lifetime[14]
Now listening on: http://localhost:5055
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
Content root path: /Users/bb/dotnet_issue_41645/src/YourJobsApp/
dotnet watch ⌚ File changed: ./Pages/Index.cshtml.
dotnet watch ⌚ No hot reload changes to apply.
```

But after changing `Pages/Index.cshtml.cs` hot reload work in both version without problem.

One strange thing, after removing directory `src/YourJobsApp/Areas/Checkout/Pages/Checkout` it works in both versions.
```
Content root path: /Users/bb/dotnet_issue_41645/src/YourJobsApp/
dotnet watch ⌚ File changed: ./Pages/Index.cshtml.
dotnet watch 🔥 Hot reload of changes succeeded.

```

**Comment by javiercn** [comment]
@wondertalik can you capture more details with `dotnet watch run --verbose`

**Comment by wondertalik** [comment]
> @wondertalik can you capture more details with `dotnet watch run --verbose`

6.0.5
```
➜  YourJobsApp git:(main) ✗ dotnet watch run --verbose
dotnet watch ⌚ Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. 
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
dotnet watch 🚀 Started '/usr/local/share/dotnet/dotnet' '' with process id 4213
  Determining projects to restore...
  All projects are up-to-date for restore.
  YourJobsApp -> /Users/bb/dotnet_issue_41645/src/YourJobsApp/bin/Debug/net6.0/YourJobsApp.dll
dotnet watch ⌚ Process id 4213 ran for 4148ms
dotnet watch ⌚ Running MSBuild target 'GenerateWatchList' on '/Users/bb/dotnet_issue_41645/src/YourJobsApp/YourJobsApp.csproj'
dotnet watch 🚀 Started '/usr/local/share/dotnet/dotnet' '' with process id 4219
dotnet watch ⌚ Process id 4219 ran for 705ms
dotnet watch ⌚ Watching 13 file(s) for changes
dotnet watch ⌚ dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
dotnet watch ⌚ Configuring the app to use browser-refresh middleware.
dotnet watch ⌚ Refresh server running at wss://localhost:59211,ws://localhost:59212.
dotnet watch 🔥 HotReloadProfile: Default.
dotnet watch 🚀 Started '/Users/bb/dotnet_issue_41645/src/YourJobsApp/bin/Debug/net6.0/YourJobsApp' '' with process id 4225
dotnet watch ⌚ Running YourJobsApp with the following arguments: run
dotnet watch 🚀 Started
dotnet watch ⌚ Application supports the following capabilities Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7074
dotnet watch ⌚ Launching browser.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5055
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/bb/dotnet_issue_41645/src/YourJobsApp/
dotnet watch ⌚ MSBuildWorkspace warning: [Warning] Duplicate source file '/Users/bb/dotnet_issue_41645/src/YourJobsApp/Areas/Checkout/Pages/Checkout/Checkout.cshtml' in project '/Users/bb/dotnet_issue_41645/src/YourJobsApp/YourJobsApp.csproj'
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
dotnet watch ⌚ File changed: ./Pages/Index.cshtml.
dotnet watch ⌚ No deltas modified. Applying changes to clear diagnostics.
dotnet watch ⌚ No hot reload changes to apply.
dotnet watch 🔥 Hot reload change handled in 97427.9594ms.
```

**Comment by javiercn** [comment]
@wondertalik if you try to make more changes after waiting for a bit (like 1 minute), do those changes get applied?

**Comment by wondertalik** [comment]
> @wondertalik if you try to make more changes after waiting for a bit (like 1 minute), do those changes get applied?

nop, without any changes.

**Comment by javiercn** [comment]
@wondertalik any errors on the browser console?

I'm trying to see if we can capture more info that gives us a hint of what might be going on, but we might need an actual repro project as @TanayParikh suggested for us to be able to see what's happening.

Another thing I would try is to run dotnet watch and give it a couple of minutes before making a change. My theory (based on things that I've seen) is that if a change happens too quickly before "everything" is setup/initialized, it can be lost.

However, what I've seen is that if you make another change afterwards, both are normally picked up.

**Comment by wondertalik** [comment]
> @wondertalik any errors on the browser console?
no errors, unfortunately.

This problem only appears when markup razor files are being edited.

> One strange thing, after removing directory src/YourJobsApp/Areas/Checkout/Pages/Checkout it works in both versions.
Maybe it has relations with Areas. I dont know.

> another thing I would try is to run dotnet watch and give it a couple of minutes before making a change. 
waited 5 minutes, same result

**Comment by javiercn** [comment]
@wondertalik I'm afraid we then need a repro project as @TanayParikh suggested.

**Comment by wondertalik** [comment]
> @wondertalik I'm afraid we then need a repro project as @TanayParikh suggested.

you have it my second response, 

> So, [repository to reproduce](https://github.com/wondertalik/dotnet_issue_41645). I tried to leave all as simple as possible.

git clone and try to reproduce all things that you need. i checked this repo on two dirrerent computers.

**Comment by javiercn** [comment]
@wondertalik my apologies, it was a long day and I missed it :).

**Comment by wondertalik** [comment]
> @wondertalik my apologies, it was a long day and I missed it :).

hi there, any news?

**Comment by javiercn** [comment]
@wondertalik I started looking at it and discovered that the compiler is not producing the expected updates when the file is changed. 

I have reached out to people with knowledge on the area for assistance. It will take some time to resolve this as it involves several people across multiple teams. 

I will post here when we have an update.

**Comment by javiercn** [comment]
@wondertalik We found the issue, it's something in your app.

 if you run `dotnet watch --verbose` you'll see that it shows a warning:
```
dotnet watch ⌚ MSBuildWorkspace warning: [Warning] Duplicate source file 'C:\work\scratch\dotnet_issue_41645\src\YourJobsApp\Areas\Checkout\Pages\Checkout\Checkout.cshtml' in project 'C:\work\scratch\dotnet_issue_41645\src\YourJobsApp\YourJobsApp.csproj'
```

This is because in your csproj file you have the following:
```xml
<ItemGroup>
    <AdditionalFiles Include="Areas\Checkout\Pages\Checkout\Checkout.cshtml" />
</ItemGroup>
```

Which is causing the file to be included twice. Is there a reason why you are adding the file manually to that ItemGroup? (You shouldn't need to).

**Comment by wondertalik** [comment]
> Which is causing the file to be included twice. Is there a reason why you are adding the file manually to that ItemGroup? (You shouldn't need to).

I didn't do it, maybe it's some kind of IDE mistake. But anyway, don't you think that this kind of warnings shouldn't cause problems?

**Comment by jaredpar** [comment]
>  I'm wondering if the source generator or the SDK could de-duplicate the items.

The compiler already de-duplicates and prints warnings with the same item is specified multiple times: 

``` 
>csc.exe .\Program.cs .\Program.cs /nologo
warning CS2002: Source file '.\Program.cs' specified multiple times
```

**Comment by javiercn** [comment]
@jaredpar does it also do it for source generators? (the item gets added to the AdditionalFiles)

**Comment by jaredpar** [comment]
Additional files are de-duped but without a warning.
