### ISSUE TITLE
Error with Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation after updating to 6.0.4/6.0.5

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#41642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating project to 6.0.5, publishing to server, and attempting to start the Windows service, the service will not start. The same was true when updating for 6.0.4, but was fine before that.

### Expected Behavior

After performing the above steps, the service should start.

### Steps To Reproduce

1. Update project to 6.0.5
2. Turn off Windows service on host server
3. Publish to host server
4. Turn on Windows service on host server -> service will not start

### Exceptions (if any)

In Windows Event Viewer:

CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, Version=6.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, Version=6.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Program.<Main>$(String[] args)

### .NET Version

3.1.405

**Comment by TanayParikh** [comment]
Package is available / published on NuGet: https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation/6.0.5, so it doesn't appear to be a publishing issue from yesterdays release.

**Comment by mrlife** [comment]
> Package is available / published on NuGet: https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation/6.0.5, so it doesn't appear to be a publishing issue from yesterdays release.

Yes, that's the package I'm using.

**Comment by javiercn** [comment]
@TanayParikh binding redirects are not a thing in .NET Core

**Comment by javiercn** [comment]
@mrlife can you check out the publish output from your app to make sure that the published dlls are correct? Did you do a clean build?

**Comment by mrlife** [comment]
@javiercn I got it to work by deleting everything on the host server and then publishing fresh. This isn't something I'd want to have to do, but does that information help narrow down the issue?

I'm sorry, I don't have the previous publish attempt's files since I deleted them for the above workaround. If there's anything else I can do to help troubleshoot, please let me know. I did do a rebuild/publish before I created this issue.

**Comment by mrlife** [comment]
@javiercn Thanks for bringing that up. There is an open issue (https://github.com/dotnet/sdk/issues/16792) to address some of the contents in pubxml, including `<DeleteExistingFiles>true</DeleteExistingFiles>`, being ignored with the `dotnet publish` command. Do you have any way to help move that along? 🙂

**Comment by javiercn** [comment]
@mrlife not really :(. It's not an area where I actively work, but if we see enough people having issues it is likely going to get revisited at some point.

In general as I mentioned unlike build, `publish` is not meant to be incremental. Meaning you shouldn't publish to a folder that already contains files. If that were to change it would involve a non trivial amount of work spanning multiple teams and publishing to a separate is "trivial".

**Comment by mrlife** [comment]
> Meaning you shouldn't publish to a folder that already contains files.

@javiercn This is interesting to hear. Isn't it normal that an application will be published to the same folder every time?

**Comment by javiercn** [comment]
@mrlife potentially; I'm not saying the behavior today is great. I'm saying it is like that today and the recommendation is the one I mentioned. In most cases it is not a problem specially if you are publishing from a CI machine where the environment is clean every time.

**Comment by mrlife** [comment]
@javiercn I understand...thank you for taking the time to talk about this with me.

The only thing that's not clear is why it's been ok for a few years now and the last 2 updates ran into this issue. I would be interested in knowing this, if possible.

**Comment by javiercn** [comment]
> The only thing that's not clear is why it's been ok for a few years now and the last 2 updates ran into this issue. I would be interested in knowing this, if possible.

Unfortunately, it's not something we can determine with the current information. It's just a theory that it was because the build environment was dirty or maybe you accidentally did something to the publish folder afterwards that caused it to get in an invalid state. There are many things that can cause situations like that, which is a reason why it is recommended to always publish clean.
