### ISSUE TITLE
WebAPI template Swagger API versioning support

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/aspnetcore#41643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

problem it is difficult to get the minimal web api with swagger template work with the support for API versioning.

### Describe the solution you'd like

It would IMHO to have the Web API template support swagger API versioning as a OOB experience; as this is good practice and would assist/guide beginners down a path that leads to a good outcome.

### Additional context

this could also be an option for health checks; live/readyness checks are becoming more standard as well as health checks for external resources ...

**Comment by BrennanConroy** [comment]
Triage: We aren't going to add versioning by default. We try to keep the templates small and simple to understand.
