### ISSUE TITLE
SignalR HubConnectionBuilder doesn't pass Client Certificate to server.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41653]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SignalR-HubConnectionBuilder-doesnt-pas/10005394)._

---
[severity:I'm unable to use this version]
Our external webserver is required client certificate in order to establish connection. When building HubConnection with HubConnectionBuilder, client certificate is added to options.ClientCertificates collection. But when try to access the certificate on Asp.Net server side HttpContext.Connection.ClientCertificate is null.

Very simple to reproduce: 
Just follow your example from https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet

On client side:
```
var connection = new HubConnectionBuilder()
    .WithUrl("target url", options => {
...
        options.ClientCertificates.Add(/* ... */);
...
    })
    .Build();
```
On server side you can create a custom middleware just get access to the HttpContext, then if you examine HttpContext.Connection.ClientCertificate it is always null.

Please advice.

Thank you, 
Michael.

---
#### Feedback Bot on 4/6/2022, 01:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rafikiassumani-msft** [comment]
Did you use the following guide to configure your server certificates: [Configure certificate authentication in ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0)? Can you provide a GitHub repo with a full repro (Client and Server configs) for our team to help?

**Comment by Md23Mh** [comment]
Hi everyone, I have exactly same issue, searched everywhere but no luck solving it. I also checked out the links mentioned here.  So I provided a very simple code in my github. I only expect to receive the certificate on server side so only required changes are made on server.  [Md23Mh/SignalR (github.com)](https://github.com/Md23Mh/SignalR/tree/main)  
I would really appreciate it if you could lead me in the right direction if I'm doing it wrong.

**Comment by davidfowl** [comment]
Are you trying to get access to the cert in the hub? Or just do client cert auth? If you're trying to access the certificate itself we don't expose it in the cloned httpcontext we give to the hub (ITlsConnectionFeature). This is a bug. The certificate is being passed to the server but not to the hub. 

We'll fix this issue. Do you need the cert in the hub? If so why?

**Comment by Md23Mh** [comment]
I was trying to get the certificate in OnCertificateValidated but this event never run so I thought maybe I should look for it in the hub itself. Would you please let me know how exactly I can get it on the server? 

Here is the code that I expect to see the certificate:

```
services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
               .AddCertificate(options =>
               {
                   options.AllowedCertificateTypes = CertificateTypes.SelfSigned;
                   options.RevocationMode = X509RevocationMode.NoCheck;
                   options.Events = new CertificateAuthenticationEvents
                   {
                       OnCertificateValidated = async context =>
                       {
                           var validationService =
                               context.HttpContext.RequestServices.GetService<CertificateValidationService>();
                           var customerId = validationService.ValidateCertificate(context.ClientCertificate);
                           if (customerId is not null)
                           {
                               var claims = new[]
                               {
                                   new Claim(ClaimTypes.NameIdentifier,
                                       context.ClientCertificate.Subject,
                                       ClaimValueTypes.String,
                                       context.Options.ClaimsIssuer),
                                   new Claim(
                                       ClaimTypes.Name,
                                       context.ClientCertificate.Subject,
                                       ClaimValueTypes.String,
                                       context.Options.ClaimsIssuer),
                                   new Claim(
                                       "CustomerId",
                                       customerId.ToString(),
                                       ClaimValueTypes.String,
                                       context.Options.ClaimsIssuer)
                               };
                               context.Principal = new ClaimsPrincipal(new ClaimsIdentity(claims, context.Scheme.Name));
                               context.Success();
                           }
                           else
                           {
                               context.Fail("invalid cert");
                           }
                       }
                   };
               })
```

**Comment by Md23Mh** [comment]
Also as mentioned in the first comment, even in a custom middleware  the client certificate is null. It seems that the client side never passes certificate.

**Comment by BrennanConroy** [comment]
Did you configure your server to require cert auth? https://docs.microsoft.com/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0#configure-your-server-to-require-certificates

**Comment by davidfowl** [comment]
We should update this doc to use `ConfigureKestrel`

```C#
builder.WebHost.ConfigureKestrel(options =>
{
    options.ConfigureHttpsDefaults(options =>
        options.ClientCertificateMode = ClientCertificateMode.RequireCertificate);
});
```

**Comment by Md23Mh** [comment]
Thanks I managed to solve it using Kestrel.

**Comment by halter73** [comment]
Glad we could help. We'll try to improve docs in this area. Feel free to make recommendations: https://github.com/dotnet/AspNetCore.Docs/pull/25881
