### ISSUE TITLE
HTTP OPTIONS verb

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#41659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Performing a request at a controller endpoint using the [OPTIONS](https://httpwg.org/specs/rfc7231.html#OPTIONS) verb results in a response with the HTTP status code 405 Method Not Allowed.

```
$ curl -X OPTIONS https://localhost:44339/WeatherForecast -i
HTTP/1.1 405 Method Not Allowed
Transfer-Encoding: chunked
Allow: GET
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Thu, 12 May 2022 12:00:38 GMT
```

### Describe the solution you'd like

ASP.NET Core should return 204 No Content when a endpoint is requested using the OPTIONS verb.

**Comment by javiercn** [comment]
@vanillajonathan thanks for contacting us.

I don't remember if there is support for OPTIONS requests outside of CORS out of the box. However, this is something that you can add yourself by creating an endpoint to handle it.

**Comment by BrennanConroy** [comment]
CORS is a middleware that needs to be added to your application.
See the docs for how to configure this: https://docs.microsoft.com/aspnet/core/security/cors?view=aspnetcore-6.0#enable-cors

You can use `[EnableCors]` and `[DisableCors]` attributes on your Controller methods to influence the CORS behavior, but you still need to setup the CORS middleware.

**Comment by vanillajonathan** [comment]
I am aware of CORS and the CORS middleware, but I am not talking about the OPTIONS verb in relation to CORS. I am talking about more general OPTIONS support as a discovery mechanism for valid verbs on HTTP endpoints. More in the context of REST.

**Comment by javiercn** [comment]
@vanillajonathan supporting OPTIONS is a decision for your app to make, not the framework. You can create an endpoint to support OPTIONS on a given path if that's what makes sense for your app.

**Comment by vanillajonathan** [comment]
But then the developer would have to add a method to handle OPTIONS on every controller. The logic for the method would be the same in every controller. It would be just boilerplate code. The code would not be specific to the application, so it is not application logic, it is framework logic.

**Comment by javiercn** [comment]
@vanillajonathan it is an opinion your app has if that's a feature you want to support, not something the framework needs nor is required to offer by default on every application.

It is also not true that every controller needs to do this. You can introspect the app endpoints and add a generic endpoint to handle options for existing routes.

**Comment by vanillajonathan** [comment]
Endpoint introspection sounds like a framework concern, not an application concern.
Is it unreasonable to expect an ASP.NET Core application to adhere to respond to an OPTION request?

It already does respond to such a request, but it returns 405 Method Not Allowed which is an error status code to what should be a valid request. The response contains the `Allow` header so ASP.NET Core already does endpoint introspection, it just doesn't return the proper 204 No Content status code.
