### ISSUE TITLE
dotnet watch locked on file changed

### ISSUE THREAD

**Issue by gldfdp** [dotnet/aspnetcore#41654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an asp.net core project (SDK Microsoft.NET.Sdk.Web) hosting a blazor wasm other project. When I launch it via console (`dotnet watch --project . -v`) the following message is displaid : "`Application supports the following capabilities Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters`."

However when I edit a project file and save it, "`File Changed`"+ filename is written the console but nothing happens after and the console remains stuck on this message.

Perhaps the following can help your investigation: 
If I perfom  Ctrl + C the following message occurs :"
`Reading hot reload capabilities failed. Using default capabilities.`
dotnet watch ⌚ System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.WaitForClientConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyDeltaApplier.<>c__DisplayClass7_0.<<GetApplyUpdateCapabilitiesAsync>g__GetApplyUpdateCapabilitiesCoreAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyHostedDeltaApplier.GetApplyUpdateCapabilitiesAsync(DotNetWatchContext context, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.CompilationWorkspaceProvider.GetHotReloadCapabilitiesAsync(Task`1 hotReloadCapabilitiesTask, IReporter reporter)
dotnet watch ⌚ Killing process 41904
dotnet watch ⌚ A task was canceled.
  ❔ Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
  ❔ dotnet watch ⌚ Caught top-level exception from hot reload: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Extensions.Tools.Internal.ConsoleRequester.GetKeyAsync(String prompt, Func`2 validateInput, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.RudeEditDialog.EvaluateAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
" 

### Expected Behavior

I would expect that file changed detection being correctly performed and the command prompt "Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?" displaid

### Steps To Reproduce

Steps:

1. Run dotnet watch or dotnet watch --project . -v
2. Edit a file and save it

### .NET Version

6.0.300

### Anything else?

IDE VS2022 17.3.0 Preview 1.0

Dotnet info:

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by gldfdp** [comment]
@mkArtakMSFT Please find the repository here: https://github.com/gldfdp/rallye i have invited as it is private

**Comment by Oblomoff** [comment]
Same issue. Hot reload is dead.

**Comment by sajrashid** [comment]
Same issue here running hosted or wasm, says file changed and does nothing oddly started working for a few days a few weeks ago, I've turned of ad blocker AV etc, cant find why browser is not connecting

`dotnet watch 🚀 Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 7004
dotnet watch ⌚ Process id 7004 ran for 467ms
dotnet watch ⌚ Watching 148 file(s) for changes
dotnet watch ⌚ dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
dotnet watch ⌚ Configuring the app to use browser-refresh middleware.
dotnet watch ⌚ Refresh server running at wss://localhost:53670,ws://localhost:53671.
dotnet watch 🔥 HotReloadProfile: BlazorHosted. C:\Users\Me\source\repos\ReflowHosted\src\Server\ReflowHosted.Server.csproj references BlazorWebAssembly project C:\Users\Me\source\repos\ReflowHosted\src\Client\ReflowHosted.Client.csproj.
dotnet watch ⌚ Waiting for a browser to connect
dotnet watch 🚀 Started 'C:\Users\Me\source\repos\ReflowHosted\src\Server\bin\Debug\net6.0\ReflowHosted.Server.exe' '' with process id 30984
dotnet watch ⌚ Running ReflowHosted.Server with the following arguments: run
dotnet watch 🚀 Started
dotnet watch ⌚ Application supports the following capabilities Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5000
dotnet watch ⌚ Launching browser.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Me\source\repos\ReflowHosted\src\Server\
**dotnet watch ⌚ File changed: C:\Users\Me\source\repos\ReflowHosted\src\Client\Components\QueryBuilder\Container.razor.`**

**Comment by MackinnonBuck** [comment]
I was unable to repro the issue with the ASP.NET Core Hosted Blazor WebAssembly App template.

@gldfdp, does this issue repro on your machine with a project created from a template? If so, which template? If not, would you please be able to provide a _minimalistic_, _public_ repro project? Thanks!

**Comment by MackinnonBuck** [comment]
@gldfdp I'm not able to access your private nuget feeds. A minimalistic, public repro project is the best way we're able to debug issues like this.

Have you experienced this issue on other projects? How long has this been an issue in the project you shared? Does this issue only appear to occur on large projects?

Thanks.

**Comment by gldfdp** [comment]
@MackinnonBuck the credentials for the private nuget feed are in the readme at the root of the project.

> Have you experienced this issue on other projects?
Yes on all my existing projects 


> How long has this been an issue in the project you shared? 
More or less 1 month now

> Does this issue only appear to occur on large projects?
It does not appear on fresh projects but after no matter the size

**Comment by gldfdp** [comment]
@MackinnonBuck I have updated the repo with the packages in the solution so no more need for private feed.

> In that case, do you have a smaller project you can share (which exhibits the dotnet watch issue) that can be built without access to private NuGet feeds?

It is my smallest project, sorry

**Comment by gldfdp** [comment]
@MackinnonBuck per example if I modify the text "Connexion " on LoginPage

![image](https://user-images.githubusercontent.com/4867906/172312931-120ee97a-c54a-4e7e-918b-8110eaa46e38.png)

As you can see, change is detected but nothing happened after

> Are there specific file modifications that reproduce the bug? Do some types of modifications work correctly when you try them?

No, every file modification produce error on my side

**Comment by gldfdp** [comment]
@mkArtakMSFT If it can help,  if I  manually put <script src="/_framework/aspnetcore-browser-refresh.js"></script> in the host file, hot reload work correctly.

**Comment by SteveSandersonMS** [comment]
@gldfdp Thanks for the additional info. However, we'll still need a minimal repro project in order to investigate.

**Comment by gldfdp** [comment]
@SteveSandersonMS I have furnished one. Perhaps it works on your computer but not on mine neither on some other pepople above in this tread. So you will need to investigate further. I can launch tools of your choice on mine and send you their feedback if it can help as it needs to be solved.

**Comment by SteveSandersonMS** [comment]
@gldfdp Unfortunately the supplied repro isn't public or minimal, so we're not able to make any further progress on investigating this. I'll mark this as closed now but if you're able to provide the minimal repro as a public repo and file a new issue, we'd be happy to take a look.

**Comment by gldfdp** [comment]
@SteveSandersonMS i already gave access to your colleague. I can give you access too  if you want

**Comment by gldfdp** [comment]
@SteveSandersonMS you have access now, so please reopen this case.
