### ISSUE TITLE
Setting User Token Reminding Attempt

### ISSUE THREAD

**Issue by AliRezaBeigy** [dotnet/aspnetcore#41662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to write a security check test in the asp.net 6 project.
 ```csharp

        var anonymousUser = GetClient();

        var targetEmail = "TestUserSecurityCheck@AAAAA.app";
        var hackerPhoneNumber = "001 123444444";

        await new AddOrEditPhoneNumberTests(OutputHelper, anonymousUser).AddOrEditPhoneNumber(hackerPhoneNumber, targetEmail);

        var smsToken = await System.IO.File.ReadAllTextAsync("sms_token");

        var startingCode = int.Parse("100000");
        for (var i = startingCode; i < startingCode + 100; i++)
            await new ConfirmPhoneNumberTests(OutputHelper, anonymousUser)
                .ConfirmPhoneNumber(hackerPhoneNumber, targetEmail, i.ToString(), ErrorCode.InvalidInput);
        
        await new ConfirmPhoneNumberTests(OutputHelper, anonymousUser)
            .ConfirmPhoneNumber(hackerPhoneNumber, targetEmail, smsToken, ErrorCode.InvalidInput);
```
`AddOrEditPhoneNumber` endpoint use `GenerateChangePhoneNumberTokenAsync` to generate 6 digit as token and their is no option to set remining attempt

This test failed in the last line because token is not expired after 100 attempt from hacker.

### Describe the solution you'd like

Add an option to the user token generator methods in UserManager for setting reminding attempts and checking reminding attempts in token validation methods

**Comment by blowdart** [comment]
Tokens are not linked to the number of users, they have a validity time (see [RFC 6238](https://www.rfc-editor.org/rfc/rfc6238)).

So they can be used multiple times in that period, it's just how it works.

**Comment by AliRezaBeigy** [comment]
> Tokens are not linked to the number of users, they have a validity time (see [RFC 6238](https://www.rfc-editor.org/rfc/rfc6238)).
> 
> So they can be used multiple times in that period, it's just how it works.

@blowdart 
Thanks for your answer

I realized we don't need this feature because the token expired in [3 minutes](https://github.com/dotnet/aspnetcore/blob/3888fda44771dd6d45f305a831b2f37427303ae4/src/Identity/Extensions.Core/src/Rfc6238AuthenticationService.cs#L16)


I have a question, at the end of the [RFC 6238](https://www.rfc-editor.org/rfc/rfc6238), there is an example code implement counter, based on [RFC 4226](https://www.rfc-editor.org/rfc/rfc4226)
```
         // Using the counter
         // First 8 bytes are for the movingFactor
         // Compliant with base [RFC 4226](https://www.rfc-editor.org/rfc/rfc4226) (HOTP)
         while (time.length() < 16 )
             time = "0" + time;
```
see [RFC 4226](https://www.rfc-editor.org/rfc/rfc4226)
```
   T       throttling parameter: the server will refuse connections
           from a user after T unsuccessful authentication attempts.
```
Is this counter related to what I said in this issue?
