### ISSUE TITLE
Dynamic Cookie.Domain in cookie middleware

### ISSUE THREAD

**Issue by Tobias-08** [dotnet/aspnetcore#41678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We want the cookie middleware to set the `options.Cookie.Domain` dynamically based on the URL that was requested.

Background: We have a SPA that communicates with an ASP.NET Core WebAPI backend. There are multiple instances of the SPA (tenants) hosted in different domains that access one single instance of the WebAPI. Due to single domain requirements of cookies the WebAPI should be accessed under different URLs (one per SPA domain). The cookie granted is supposed to have the specific `Cookie.Domain`.

### Describe the solution you'd like

I'd like the configuration for the cookie middleware (`AddCookie`) to provide context (URL) of the current request.

Or is this something that is even possible today (e. g. injecting `HttpContext` but I did not find a working sample)?

**Comment by Tratcher** [comment]
Are you trying to share the cookie across the domains, or prevent that? Clients prevent cross domain sharing by default, they use the domain from the current request if one is not set in the cookie.

**Comment by Tobias-08** [comment]
Thanks for your comment. Our context is not about sharing the cookie across domains but about issueing different cookies (with different domain scopes) depending on the URL that was used for reaching the WebAPI.

We now succeeded in doing this by implementing a custom `ICookieManager` and registering it with `opts.CookieManager` in the cookie middleware.
