### ISSUE TITLE
appcmd.exe is not reading appsettings from appsettings.json

### ISSUE THREAD

**Issue by geetmenon** [dotnet/aspnetcore#41676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had opened a ticket (#41596) for this earlier. It was closed by msftbot without providing proper resolution. The comment added by  @adityamandaleeka is wrong and unacceptable. Please provide a resolution for this.

### Expected Behavior

Enhance appcmd.exe so that it can read from appsettings.json.

### Steps To Reproduce

1. Create a asp.net core app with appsettings.json

2. Let there be the following json entry in your appsettings.json
"MyFlag1": false

3. Add a website named "MyWebSite" pointing to this app.

4. Run the following command
%windir%\system32\inetsrv\appcmd.exe set config "MyWebSite" -section:appSettings /[key='MyFlag1'].value:"true"

### Exceptions (if any)

ERROR ( message:Cannot find requested collection element. )

### .NET Version

AspNetCore.App 5.0.10 NetCore.app.5.0.10

**Comment by javiercn** [comment]
@geetmenon thanks for contacting us.

I think @adityamandaleeka answer is correct here. While I understand that doesn't match your expectations, `appcmd.exe` is a management tool for IIS and not a management tool for ASP.NET Core.

Support for something like the one you are asking for should be requested https://social.msdn.microsoft.com/Forums/en-US/home?forum=iisfeaturefeedback as that's where the IIS team will be able to look at.

That said, as @adityamandaleeka pointed out, `appcmd.exe` deals with web.config files and not appsettings.json or any other configuration system the app might be using. The settings you place in web.config are specific to IIS, while ASP.NET Core is host independent so its configuration system is independent of IIS.

In the same way, IIS can host any type of framework, not just ASP.NET Core, so it shouldn't be responsible for understanding other configuration systems.

What I'm trying to convey is:
ASP.NET was tied to IIS so it leveraged the IIS config system directly. ASP.NET Core is not tied to IIS and so it doesn't leverage its config system. It is not IIS responsibility to support alternative config systems in their tooling unless they want to.

Finally, I would suggest that if what you are looking for is a way to set configuration via command line on a script. I recommend you do this with PowerShell, which has commands to read and manipulate JSON you can use for this effect. If you still think appcmd.exe should support this scenario, I encourage you to direct the feedback in the link I have provided, as this is not a product/feature the ASP.NET Core team can work on.

I understand that this might not match your expectations; However, I hope that at least we shed some clarity on why this are the way they are and what alternative options you have.

**Comment by davidfowl** [comment]
I replied on the other issue. Lets close this since that one has more context.

**Comment by geetmenon** [comment]
Before Microsoft recommended that we move to appsettings, it should have at least warned us of this. Its Microsoft responsibility to see the full picture and impact. Things like, one tool can read appsettings.json, while another one cannot, and its IIS team (and not aspnetcore) that needs to look into this if they decide is all poor excuses and not at all customer friendly. Microsoft should have thought through all this. Most of the companies using aspnet host their apps on IIS. Support for this basic configuration should have been thought through prior to recommending that we migrate to appsettings.json. I can understand if you give these excuses if ours was very custom scenario or if we were hosting it on another server. But ours is most basic/simple scenario. So I do not agree that this is the expected behavior because Microsoft has not this through properly. 

Being able to do this via powershell or even batch scripts is possible and we all know that. But that is not the question here. Here is a tool that was able to change our appsettings prior to migration and now it cannot. And it is breaking our system. So now we have to add workarounds just because Microsoft continues to not do proper impact analysis.
