### ISSUE TITLE
Advanced component Blazor

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#41684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I create a "Card" component that has content, title, picture and lots of other information.
```cs
@using Microsoft.AspNetCore.Components.Forms

<div class="@Class mb-2 bg-transparent text-text dark:text-text_dark">

    @if (Image is not null)
    {
        <img class="w-full" src="@Image" alt="@Title"/>
    }

    <div class="mx-2 md:mx-5 py-3">

        @* Title *@
        @if (Title is not null)
        {
            <div class="my-2 justify-center">
                <p class="text-3xl ">@Title</p>
            </div>
        }

        @* Content *@
        <div>
            @Content
        </div>

    </div>
</div>

@code {
    [Parameter]
    public RenderFragment? Title { get; set; }

    [Parameter]
    public RenderFragment? Content { get; set; }

    [Parameter]
    public string? Class { get; set; }

    [Parameter]
    public string? Image { get; set; }
}
```
It is called like this
```cs
        <Card>
            <Title>Title</Title>
            <Content>
Content
            </Content>
        </Card>
```

### Describe the solution you'd like

I miss extra attributes in the ``RenderFragment``
I wanted to create something like this:
```cs
        <Card>
            <Image Src="example.com/test.png"/>
            <Title Class="test" Size="30">Title</Title>
            <Content>
Content
            </Content>
        </Card>
```
Unfortunately, when looking for solutions on the Internet, it is not possible. Is it possible to do something like this?

I know you can create an extra new component, but then it will be another object that doesn't necessarily match the card. The problem is to make unique components that fit everywhere.

Why?

In Card we have a Title which displays the card element to us. Image requires us to have the title of the image as well. You then have to assign the title twice.

A nice option would be to introduce something like this:
```cs
@code {
    [Parameter]
    public RenderFragment<TitleContent>? Title { get; set; }

    [Parameter]
    public RenderFragment? Content { get; set; }

    [Parameter]
    public string? Class { get; set; }

    [Parameter]
    public string? Image { get; set; }

    public class TitleContent {
        public string Class {get;set;}
        public int Size {get;set;} = 3;
        public RenderFragment Content {get;set;}
    }
}
```
Then you can get this effect:
```cs
        @if (Title is not null)
        {
            <div class="my-2 justify-center">
                <p class="text-@(Title.size)xl @Title.Class">@Title.Content</p>
            </div>
        }
```

### Additional context

What do you think about such a solution? I searched the internet and found nothing. I believe that such a solution can greatly facilitate the creation of unique components.

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

To summarize your request, you would like the ability to define attributes on render fragments and for those attributes to be captured in an additional property that you can then pass down to the render fragment. Am I understanding this correctly?

**Comment by Alerinos** [comment]
@javiercn 
Yes. It would be very convenient, then you can create a component in one file with dedicated parameters. At the moment, many separate components need to be created.

**Comment by javiercn** [comment]
@Alerinos thanks for the additional details.

I don't think this is something we want/plan to do for the time being. It creates an ambiguous syntax between components and render fragments (looking at the code you wouldn't know if `Title` is a render fragment or a component) and involves a lot of assumptions/conventions with "little" gain over authoring a component. There are three arguments I can see for this:
* Performance: Using the render fragment vs rendering a component is not going to matter in the vast majority of scenarios.
* Intellisense for the structure inside the render fragment for the component (enforcing/suggesting some level of structure/required tags): This is something that can be achieved using alternative approaches on the compiler.
* Convenience (defining things in a single place): This is something that could be achieved in different ways, like allowing people to define "nested" components within the file.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
