### ISSUE TITLE
IdentityUser Primary Key

### ISSUE THREAD

**Issue by No1e** [dotnet/aspnetcore#41689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Dear ASP.NET Idenity Core Team,

I am sorry that I missusing issue reporting to ask a question, but I was not able to find an answer anywhere else, and I hope you can help me out to understand. 

The question is why is the primary key of IdentityUser saved as guid? What is the reason behind?  Why not db generated int? 
I know that I can change this, but I really like to know why guid?

Thank you and best regards,
Novak

**Comment by Alerinos** [comment]
GUID makes a unique key, this is also for security purposes. It is more difficult to find a user by GUID than by INT, where you can jump from 0,1,2,3 ... 999999

**Comment by No1e** [comment]
@Alerinos thank you!

I have one more question. When I look at the model in source code, for example IdentityUser, I can see that all properties, including non navigation properties, like Username, PasswordHash etc., are defined as virtual. Why is that?

Best regards,
Novak

**Comment by HaoK** [comment]
https://stackoverflow.com/questions/23891446/why-is-asp-net-identity-2-0-using-a-guid-string-as-user-id is a reasonable discussion of some of the tradeoffs between guid/int

The POCO is meant to be a base class, so all the properties are virtual for derivation
