### ISSUE TITLE
Hot reload for Blazor Web Assembly in VS 17.2.0 does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41681]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hot-reload-for-Blazor-Web-Assembly-in-VS/10041823)._

---
Hot reload for Blazor Web Assembly in VS 17.2.0 does not work (not debug mode).

![Screenshot 2022-05-13 151015.png](https://aka.ms/dc/image?name=B79e9c407ed814b18a06d0ed79821eb33637880406591484071_Screenshot_2022-05-13_151015.png&tid=79e9c407ed814b18a06d0ed79821eb33637880406591484071)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't have enough information here to understand what's causing this. Please share more information about your environment (.NET SDK version, project that you're using).
Also, does this happen for a newly created Blazor WebAssembly project or not ?
