### ISSUE TITLE
Detect public properties that will fail when databinding a SelectList

### ISSUE THREAD

**Issue by ianw1223** [dotnet/aspnetcore#41680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When trying to build a SelectList in Razor Pages, if the class that is the basis for that list has public properties, the SelectList constructor will succeed but the page rendering will fail with "Object not set to an instance of an object' amid some messy reflection errors. Diagnosing that error can be time consuming and frustrating.
```
public void OnGet()
{
    var listOfChoices = new List<ChoiceModel>()
    {
        new ChoiceModel(){Id=1,Name="LetterA"},
        new ChoiceModel(){Id=2,Name="LetterB"},
    };
    ChoiceSL = new SelectList(listOfChoices, nameof(ChoiceModel.Id), nameof(ChoiceModel.Name));
}
public class ChoiceModel
{
    public int Id;                // Omit at your peril: { get; set; }  
    public string? Name;   // Omit at your peril: { get; set; }
}
//-----
<form method="post">
    <select asp-for="ChoiceNumber" asp-items="Model.ChoiceSL"></select>
    <button>Submit</button>
</form>
```

### Describe the solution you'd like

Anything to identify the cause of this error would be valuable, either a better runtime error message, a compiler warning or compiler error. 

My suggestion: The SelectList constructor should fail with an error if the properties are public. Its job is to create a correct and usable list that is capable of databinding.

### Additional context

Please note how difficult this bug is to solve for those new to C#.

**Comment by javiercn** [comment]
@ianw1223 thanks for contacting us.

Unfortunately, it is not possible to do eager validation as it would break existing applications. SelectList can be used with types provided by the user which can have getters and setters and can be setup after they've been passed into the SelectList (as you are doing).

The best way to handle this is to make sure your models always provide the required data (Id and Name) to ensure that you don't fail later in the pipeline.

**Comment by ianw1223** [comment]
Thanks, @javiercn . Understood. (I learned the importance of correct models the hard way.) Is there any way to provide a slightly more helpful error when it crashes on page rendering with "Object not set to an instance of an object"?
