### ISSUE TITLE
[SignalR] Add HttpClientHandler change support

### ISSUE THREAD

**Issue by alexeygritsenko** [dotnet/aspnetcore#41685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hey, when I work with a hub, I may have problems with some hosts: **The SSL connection could not be established, see inner exception**.  If it was a HttpClient then it is enough for me replace **HttpClientHandler** to **Xamarin.Android.Net.AndroidClientHandler** and it helped. I think SignalR need the same functionality. Otherwise, I have to ignore the certificate, which I consider wrong and unsafe.
```
connection = new HubConnectionBuilder()
.WithUrl("https://mydomain/hub", options =>
{
    options.HttpMessageHandlerFactory = factory => new HttpClientHandler
    {
        ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; }
    };
})
.WithAutomaticReconnect()
.Build();
```

### Describe the solution you'd like

SignalR client must support HttpClientHandler assignments (overloading).

### Additional context

I use Microsoft.AspNetCore.SignalR.Client 6.0.5 in Xamarin.Forms Android project.

**Comment by davidfowl** [comment]
Why doesn't the `HttpMessageHandlerFactory`  work in this scenario?

**Comment by alexeygritsenko** [comment]
Oh yes... I can implement it like DependencyService
`options.HttpMessageHandlerFactory = factory => DependencyService.Get<IHttpService>().CreateHandler();`
Excuse me, got tired today .. It was a false alarm.
