### ISSUE TITLE
define an interface for HubConnectionContext for signalR

### ISSUE THREAD

**Issue by armin-git** [dotnet/aspnetcore#41709]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to extend `HubConnectionContext` and create custom method for it, specialy an overload for `WriteAsync` , that act as **fire an forget** pattern but ther is no way to create a custom class and inject it in program.cs because HubConnectionContext does not inherent from any interface.

the goal is create an overload for WriteAsync method and pick up `ValueTask(CompleteWriteAsync(task))` and make the method synchronously that act as fire and forget pattern

### Describe the solution you'd like

create an interface like `IHubConnectionContext` and put it in `SignalRDependencyInjectionExtensions.cs` so we can inject our new custom class to signalR with DI

**Comment by armin-git** [comment]
when a client connect to server, the `OnConnectedAsync` method fire in server and when a client refresh the page or close the browser, the `OnDisconnectedAsync` method fire in server. but when aclient goes to offline mode or have a poor connection conectivity, the massge await for some second to user back online, i dont know exactly what happen in background but i sense the message shouldn't be await,

![image](https://user-images.githubusercontent.com/8854504/168953708-465a016d-c5af-4ed5-991d-98620713a441.png)


i need a sync version of `WriteAsync` method in `HubConnectionContext.cs`. send a message and if user is not online (not disconnected but is offline), dont wait for user to back online.

for more detail, when server send many message to user and user is offline, the message get queue, but i found there isnt any queue, it just an await method. so after the user back online, all those message come in and its not good, becase i want signalR send message and forget the state of it (fire and forget pattern).

in continue i handle the message list in rabbit or redis and when a user recive a message, send a message to server as an ACK and delete the message from rabbit or reddis.

having awaitable method in this scenario like the server is not stateless and buffer the message that i cant handle it.

it would be very nice if i could extend the inner functionality of signalR by an interface or something else.

**Comment by BrennanConroy** [comment]
This is not possible, there are far too many layers involved that all do their own buffering. The TCP routing layer, the OS, the server, SignalR itself, etc.

If you want to lower the amount of time that the SignalR connection will stay open when a client goes offline, then you can configure the keep alive interval and timeout. You'll need to configure both client and server https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#configure-server-options
