### ISSUE TITLE
In C# Client HubConnection.Connected event needed

### ISSUE THREAD

**Issue by JiriZidek** [dotnet/aspnetcore#41717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use SignalR C# Microsoft.AspNetCore.SignalR.Client in legacy code, that is not based on await/async and to do something after connection is established. 

### Describe the solution you'd like

It would be helpful to expose Connected event on HubConnection (beside existing Reconnected, Closed or Reconnecting). It would allow to decouple code of starting connection and doing something after that. 

### Additional context

It is possible to invoke StartAsync this way

``` C#
Task.Run( async () => {
      await hubconnection.StartAsync(); 
      if(hubconnection.State==HubConnectionState.Connected ) OnConnected(new EventArgs);
});
```

But does it really cover really all situations ? What if after StartAsync state is not Connected ?

**Comment by halter73** [comment]
Even if there was a `Connected` event, it would be possible for the state to change before the event actually fired. We don't see the value in a separate event. If you want one, you can call it yourself after `StartAsync()` completes successfully.

**Comment by JiriZidek** [comment]
> it would be possible for the state to change before the event actually fired

Why is it different for Reconnected, Closed or Reconnecting ? Isn't this valid for them as well then, but still considered to be useful ?

> after StartAsync() completes successfully

Does it mean it may throw some "operative" exceptions (like IOSocket) ? Docs are silent about such possibility: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnection.startasync?view=aspnetcore-6.0

**Comment by BrennanConroy** [comment]
> Why is it different for Reconnected, Closed or Reconnecting

Those are all events that can be/are triggered outside of the user calling a function, so they are only reliably visible via an event. Connected is always observable by `StartAsync` completing successfully (or in reconnects via Reconnected) and so it doesn't need an event.

> Does it mean it may throw

Yes, there are plenty of reason `StartAsync` can throw, network issues, server declining the request for various reasons, `StopAsync` being called before `StartAsync` completes, dll load issues, etc.
