### ISSUE TITLE
GrpcTemplate is quarantined

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#41716]
The SDK now gives warnings for C# variables with all lowercase names - Grpc Protobuf auto-generates such variable names, so we've had to suppress the warning in a bunch of places & quarantine the GrpcTemplate test. Once https://github.com/grpc/grpc/issues/29672 is resolved & we can ingest a package with the fix, we should undo the `NoWarn` additions from https://github.com/dotnet/aspnetcore/pull/41697 & un-quarantine `GrpcTemplate`

**Comment by JamesNK** [comment]
The original issue is fixed. Now failing because of a new ARM Helix queue. It must be skipped.

**Comment by JamesNK** [comment]
100% passing after test is disabled on ARM Helix queue:

![image](https://user-images.githubusercontent.com/303201/216757014-2f67afc3-8e57-4adb-bde4-8cc3b88cde1f.png)
