### ISSUE TITLE
Asp.net core source code gives compile time errors in Visual studio

### ISSUE THREAD

**Issue by singh733** [dotnet/aspnetcore#41727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I fork the asp.net core source code from https://github.com/dotnet/aspnetcore and then download the code from my repository it did not work. Every time when I do fresh download it gives error.

For example:
![image](https://user-images.githubusercontent.com/83835739/168970952-0839e9f8-4138-4007-87e1-81597c513b63.png)

### Expected Behavior

Asp.net core source code should building fine  with visual studio.

### Steps To Reproduce

a) Fork the repository from  https://github.com/dotnet/aspnetcore
b) git clone --recursive https://github.com/YOUR_USERNAME/aspnetcore
c) git submodule update --init --recursive
d) git remote add upstream https://github.com/dotnet/aspnetcore.git
e) git checkout tags/v7.0.0-preview.4.22251.1 -b New_Branch  (I checked out the specific latest tag. Although if you  have latest source code also it gives different errors )
f) In the eng/scripts folder run  ".\InstallVisualStudio.ps1 -Edition {Professional} -Channel {Preview} -Version {2022}"
g) In the eng/scripts folder run  ".\InstallJdk.ps1 -Force"
h) In the root folder run .\restore.cmd
i) in the specifc repository run .\build.cmd
j) run .\startvs.cmd

When visual studio opened it gives you the below error:

![image](https://user-images.githubusercontent.com/83835739/168972504-811a0417-d709-4842-91b9-0cf63ed29234.png)

### .NET Version

7.0.100-preview.4.22204.1

### Anything else?

Please note the following points:

a) I have Java_home correct enviorment path

![image](https://user-images.githubusercontent.com/83835739/168972909-01bad901-3d2c-48c2-a7d4-ae57b0019381.png)

b) Node
![image](https://user-images.githubusercontent.com/83835739/168973696-5d390400-f25d-432f-b16f-c41c34dc5c5d.png)

c) tar
![image](https://user-images.githubusercontent.com/83835739/168973763-2fa874ba-979e-4e92-8d9c-4e9bc863c475.png)

d) Git

![image](https://user-images.githubusercontent.com/83835739/168973835-0109f7f5-8e05-4f18-a1f4-d67b8893abb4.png)

e) Yarn

![image](https://user-images.githubusercontent.com/83835739/168973910-a28f7983-1d61-496a-ba33-19542654151b.png)

f) .dotnet

![image](https://user-images.githubusercontent.com/83835739/168974148-3f7846c8-bce0-41e1-8563-bf9bdaac8e01.png)

**Comment by davidfowl** [comment]
What version of visual studio are you running?

**Comment by singh733** [comment]
Visual studio  2022 preview.

I ran the following command in eng/scripts

.\InstallVisualStudio.ps1 -Edition {Professional} -Channel {Preview} -Version {2022}

**Comment by BrennanConroy** [comment]
> 7.0.100-preview.4.22204.1

You have an old fork of the repo, this was fixed when we updated to 7.0.100-preview.5.22228.6, see https://github.com/dotnet/aspnetcore/commit/c4b57c452447f70ab874097436226542c70d74c0

**Comment by singh733** [comment]
@BrennanConroy  Just wondering then why it says build succeed here. 

![image](https://user-images.githubusercontent.com/83835739/169071062-e15f213c-d988-4a3b-a91d-4fdb42b1f5fd.png)

**Comment by wtgodbe** [comment]
Looks like this was a known issue that was fixed, closing the issue. @singh733 feel free to re-open if you're still having problems. If you don't have a strong reason _not_ to, we recommend just checking out & building `main`.
