### ISSUE TITLE
Add option to control whether controller names are trimmed or not when used for routing

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#41730]
## Background and Motivation

I never understood why the controller names used for routing have to differ from the actual class name. Having it the same as the class name allows avoiding magic strings in your code base by utilizing the `nameof()` expression. We already have this option for the [Async suffix](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcoptions.suppressasyncsuffixinactionnames?view=aspnetcore-6.0) for the names of a controller's methods. Does it make sense to also make it possible for the controller itself to have these trimming capabilities, i.e whether for the controller's name to be `HomeController`, or the current variant which is `Home` if it were named `HomeController`.

Thanks!

## Proposed API
An additional `bool` property in [MvcOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/MvcOptions.cs) named **for example** `SupressControllerSuffixInControllerNames` which the end-user can modify to their liking by using the already establish architecture for configure an `MvcOption` instance.

## Usage Examples
```

services.AddControllers(options => options.SupressControllerSuffixInControllerNames = true);

**Comment by halter73** [comment]
Does using the `[Route(string)]` attribute work for you?

```csharp
 [Route(nameof(HomeController))]
 public class HomeController : Controller
 {
    [Route(nameof(Index)]
    [Route("")]
    [Route("/")]
    public IActionResult Index()
    {
        return ControllerContext.MyDisplayRouteInfo();
    }
 ```

 https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0#combining-attribute-routes
 
 Once you start with attribute routing at the hub level, you'll no longer get the default matching, so you'll probably need to attribute the methods as well.

**Comment by SpiritBob** [comment]
The problem I'm trying to avoid is the following scenario:

```
public class HomeController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
       // Controller name parameter is expected to be "Home" instead of "HomeController".
       // We can't use nameof(HomeController), hence we start relying on magic strings!
        return Ok(Url.Action(nameof(Example), "Home", new { text = "Hello " }, Request.Scheme));
    }

    [HttpGet]
    public IActionResult Example(string text)
    {
          return Ok(text + "World");
     }

**Comment by BrennanConroy** [comment]
Triage: We don't think this is something we want to add to the framework. If you want to use `nameof` everywhere and keep `Controller` in the name you can use the attributes as described in https://github.com/dotnet/aspnetcore/issues/41730#issuecomment-1132364740.
