### ISSUE TITLE
Allow specifying authentication schemes where anti-forgery checks are (not) required

### ISSUE THREAD

**Issue by Aaronmsv** [dotnet/aspnetcore#41759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Our project supports a lot of different authentication types: Cookie, multiple API keys, OAuth, IODC, WS-Federation, etc. Some of these are not vulnerable to cross-site request forgery (like the API keys or token-based types), only authentication types like Cookie, Basic and Digest.

However, when using the `AutoValidateAntiforgeryToken` attribute, anti-forgery is checked on all authentication types, leading to 400s when not including anti-forgery data in requests using authentication types that are not vulnerable to anti-forgery.

### Describe the solution you'd like

A way to specify which authentication schemes the should be checked for anti-forgery and/or which ones don't need to be checked.

My plan was to override the  `ShouldValidate` of the `AutoValidateAntiforgeryTokenAuthorizationFilter` and add this logic myself. Or derive directly from `ValidateAntiforgeryTokenAuthorizationFilter` and do it there instead. However, both are internal, so this approach is not possible.

Would you mind making them public and `ShouldValidate` virtual? Or do you know of a better solution?

Edit: maybe an even better solution could be to add a new flag on the authentication scheme or handler, and let the filter check this flag?

### Additional context

Using ASP.NET Core 6.

**Comment by adityamandaleeka** [comment]
Triage: at this point we don't want to add any complexity to how `AutoValidateAntiforgeryToken` works. Your workaround of doing this manually is the way to go.
