### ISSUE TITLE
[Feature Request] Make `asp-for` compatible with the Constraint Validation API

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#41750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The `asp-for` tag helper adds various validation-related attributes to the DOM, which are used by the "jQuery Validation" and "jQuery Unobtrusive Validation" plugins.

Modern browsers have the ["Constraint Validation" API](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Constraint_validation), which allows native handling of such things. But the runtime does not generate compatible attributes.

For example, this razor markup:
````razor
<input 
  type="text" 
  asp-for="Name" />
````

is translated to this final markup:
````html
<input 
  type="text" 
  data-val="true" 
  data-val-length="The field Name must be a string with a maximum length of 20." 
  data-val-length-max="20" 
  data-val-required="The Name field is required." 
  maxlength="20" 
  name="Name" 
  value="">
````

All the relevant data is there. But not in a format that will work with the Constraints API.

The obvious example: the markup includes `data-val-required` but not `required`. There are [others too](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Constraint_validation#validation-related_attributes).

Current workaround: manually add all that, or use a script to map from the one to the other.

### Describe the solution you'd like

If the generated markup adhered to the standard, the page would be much easier to use with frontend libraries - importantly, with style libraries such as Bootstrap and Tailwind.

Please update the the tag helper to output the correct attributes. If you must keep the current ones so as not to break support for jQuery Validation and jQuery Unobtrusive Validation, that's fine. Just add the standard attributes as well.

### Additional context

Thank you.

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

I'm going to close this issue as a dupe as we will take this input to be covered as part of https://github.com/dotnet/aspnetcore/issues/8573
