### ISSUE TITLE
[dotnet-watch] Experience improvements for injecting the scripts into the document

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#41772]
Failing to automatically inject the dotnet-watch scripts into the document can result in **really hard** to debug issues. See https://github.com/dotnet/aspnetcore/issues/41732 for details.

In essence:
* When the automatic script injection fails the only way to notice it is by turning logging to debug level.
* The logic for looking for the body tag is fragile as it is very strict and will only find the body end tag if it appears in a single buffer.
* Any transformation that happens to the response will cause the script to fail.

Proposed actions:
* Emit a log with Warning level when the middleware fails to automatically inject the script:
  * Suggest injecting the scripts manually on to the page in the message.
  * Detect known causes for failure (like looking at the `Accept-Encoding` header on the response) and pointing that out.
* Buffer the entire response in memory for inspection:
  * There is no value in the micro-optimization that we get for not buffering the contents internally to perform the injection.
  * Instead buffer the entire contents or at least check the end of the buffer to see if it could potentially contain the start of the end body tag to make sure we can inject the scripts even if the body is chunked.

**Comment by mkArtakMSFT** [comment]
Related: https://github.com/dotnet/sdk/issues/25510

**Comment by EricOnGit** [comment]
> Thanks for contacting us.
> 
> We're moving this issue to the `.NET 7 Planning` milestone for future evaluation / consideration. We would like to keep this around to collect more feedback, which can help us with prioritizing this work. We will re-evaluate this issue, during our next planning meeting(s). If we later determine, that the issue has no community involvement, or it's very rare and low-impact issue, we will close it - so that the team can focus on more important and high impact issues. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md).

Why such a fix has to be postponed until a full .NET release? Have we lost the ability to deliver incremental bug fixes. When was the last minor release of any .NET release? 
Looks like it's becoming a habit to defer to the next full release instead of fixing the current version.
The idea of pushing this in .NET 7 means we'll have to move to a short term support version just to get some bug fixed which will then lead to another migration to the next LTS.

**Comment by MackinnonBuck** [comment]
Done in https://github.com/dotnet/sdk/pull/27537
