### ISSUE TITLE
IIS In Process aspnetcore process failing to start under load

### ISSUE THREAD

**Issue by adamzest** [dotnet/aspnetcore#41770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running our .Net 6 services under IIS in process 'sometimes' our services fail to start up properly, leaving the app pool running but the service completely unresponsive (in reality it looks like it didn't get as far as starting the dotnet application - see logs from aspnetcore). This tends to be following a reboot of a server or during an IISRESET where the CPU is very busy starting up many services/app pools, and a few fail to start the 'in process' process properly.

Having enabled aspnetcore debug tracing I can see a difference in output between success and failure of the service to startup.  The key difference is that on failure we see this in the log:
Thread reading stdout/err hit timeout, forcibly closing thread.

Also note that if we switch the web.config to use 'outofprocess', then we are not able to recreate - i.e. the service always starts successfully.

[aspnetcore startup failure.txt](https://github.com/dotnet/aspnetcore/files/8740318/aspnetcore.startup.failure.txt)
[aspnetcore startup success.txt](https://github.com/dotnet/aspnetcore/files/8740319/aspnetcore.startup.success.txt)

Based on the logs I believe this is happening before launching the service.

### Expected Behavior

Service should reliably startup when using IIS in process hosting.

### Steps To Reproduce

This is tricky... as per description this does not appear to be related to the application being hosted, but rather the aspnetcore hosting process.

Configure IIS server with many app pools (aspnet core, in process) that auto start.
Reboot server/IISRESET inducing high cpu load
Some processes dont start properly leaving the app pool running but no requests are serviced (application doesnt appear to have been started)

### Exceptions (if any)

AspNetCoreModuleV2 module outputs to debug log:
Thread reading stdout/err hit timeout, forcibly closing thread.

### .NET Version

6.0.300

**Comment by adamzest** [comment]
We have now recreated this with an unmodified service created from the VS 2022 "ASP.Net Core Web App" template, so I would argue it is obvious that this is a bug in the framework.

**Comment by HaoK** [comment]
Can you give a detailed set of repro steps using the template to demonstrate the problem?

**Comment by adamzest** [comment]
Reproducible on multiple servers using Azure VMs (Standard E2as v4 (2 vcpus, 16 GiB memory), however it is hard to recreate without the specific circumstances. Our IT team would be happy to help with additional diagnostics or demonstration.

Our IIS Configuration is:

- 6 application, with always running app pools configured for 'no managed code'. Application can be the .Net 6 'ASP.Net Core Web App template' running 'in process' (the more instances of these services the greater the chance of catching 1 failing)
- 44 applications, with always running app pools running .Net Framework 4.7.2 WCF servers (what seems critical is that there is enough load to create 100% cpu load for several minutes following an IISRESET)

Steps:
Either reboot VM, or perform an IISRESET
Observe high CPU load for around 5 minutes whilst services are starting - this is critical to the repro.
Attempt to load the services via http requests
Some of the .net 6 'In process' apps do not respond to http requests. Those services will:
- have a started up app pool which does not detect failure
- are using minimal memory (around 5mb)
- have not executed any app code (we do not believe AspNetCoreModuleV2 actually started the process at all)
- AspNetCoreModuleV2 module outputs the following to its debug log: "Thread reading stdout/err hit timeout, forcibly closing thread."

**Comment by adamzest** [comment]
Any update on this please? It continues to plague us daily.

**Comment by HaoK** [comment]
Its hard for us to make much progress without a way to reproduce the issue so we can debug/take a deeper look.  Can you try to isolate a small repro app with a series of steps to demonstrate the issue?
