### ISSUE TITLE
Expose OnErrorAsync in ErrorBoundary 

### ISSUE THREAD

**Issue by sengiv** [dotnet/aspnetcore#41784]
## Background and Motivation
Simply put this would allow parent to supply event handler for OnError in ErrorBoundary.
ErrorBoundary as is works well. But when using it in projects I find the need to access OnErrorAsync & CurrentException from parent.
So we end up wrapping ErrorBoundary just to access OnError.
Maybe there is good reason why this is done this way. If so please share your input.
Else, this proposal could help ErrorBoundary be more customizable without the hassle of wrapping.

## Proposed API
Example page-level error boundary in `MainLayout.razor`
At the moment this is not possible.
```
<div class="main">
    <div class="content px-4">
        <ErrorBoundary @OnError="OnError">
            @Body
        </ErrorBoundary>
    </div>
</div>

@code {
        private void OnError(Exception exception) => Console.WriteLine(exception.Message);
}
```

@SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We'll park this in the `Backlog` for now to accumulate more feedback about this. If we hear a lot of asks for this, then we will be able to prioritize this.

**Comment by danroth27** [comment]
> But when using it in projects I find the need to access OnErrorAsync & CurrentException from parent.

@sengiv We'd like to understand your scenario better. Can you share with us some examples of when this is useful?

**Comment by sengiv** [comment]
Thanks for your reply. 😄 Turns out I wasn't using ErrorBoundary correctly.
Now my code looks like this, without a wrapper class.
```
<ErrorBoundary>
      <ChildContent>
           @Body
      </ChildContent>
       <ErrorContent Context="ex">
            @{ OnError(@ex); } 
           <p>@ex.Message</p> 
       </ErrorContent>
</ErrorBoundary>
```

**Comment by SteveSandersonMS** [comment]
The pattern you have here will work, but it's worth being aware that if the enclosing component re-renders while you're in an errored state, then your custom `OnError` method will get called a second time.

If you want to ensure you only get one call for each error, it would be best to follow the subclassing approach. If you want, you can make a single subclass that accepts a `[Parameter] public Action<Exception> OnError { get; set; }` parameter, and then reuse that throughout your application.

**Comment by sengiv** [comment]
Good point, I was not aware of the 2nd call. But now that you mentioned it makes sense. Thanks for your input.
