### ISSUE TITLE
Trying to access IWebHostEnvironment in a class library, referenced by my web project

### ISSUE THREAD

**Issue by chinthakaherath** [dotnet/aspnetcore#41780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm accessing IWebHostEnvironment in a class library, referenced by my web project in .Net 6. I saw several suggestions (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#use-the-aspnet-core-shared-framework). But this suggestion `<FrameworkReference Include="Microsoft.AspNetCore.App" />` not working and getting issue 

> Initialization method ExceptionServiceTests.Initialize threw exception. Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'OperatorContextBuilder' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.AspNetCore.Hosting.IWebHostEnvironment webHostEnvironment' of constructor 'Void .ctor(ServiceFacade.Contracts.IOperatorService, ServiceFacade.Contracts.IOperatorServiceAdmin, Microsoft.AspNetCore.Hosting.IWebHostEnvironment, Microsoft.Extensions.Configuration.IConfiguration)'..

Any suggestion to resolve this issue

### .NET Version

6.0.202

**Comment by davidfowl** [comment]
When you say it's not working you mean it can't be resolved. The suggestion is about being able to add the appropriate reference so that the type resolves at compile time. It looks like whatever application you are running doesn't include that implementation. If you can share the code or explain what the application is doing we might be able to resolve the issue.

Is it a web application?

**Comment by chinthakaherath** [comment]
@davidfowl [davidfowl](https://github.com/davidfowl)  My API project is using IWebHostEnvironment, I'm referring to this API project in my integration testing project then getting this issue when unit tests are running

**Comment by davidfowl** [comment]
Then your test isn't setting up the environment properly it seems.
