### ISSUE TITLE
StringContent constructors ignore content string

### ISSUE THREAD

**Issue by SED4906** [dotnet/aspnetcore#41786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using ASP.NET with F#, returning a StringContent or an HttpResponseMessage with a StringContent in the Content property from the HttpGet function does not include the content, causing Edge to display only a JSON formatting of the server response.

### Expected Behavior

The response should contain content.

### Steps To Reproduce

[The project](https://github.com/SED4906/FSharpWiki)

### .NET Version

6.0.202

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25120
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by davidfowl** [comment]
These HttpClient types aren't supported by ASP.NET Core.
