### ISSUE TITLE
RedisCache has no virtual methods?

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/aspnetcore#41793]
Currently RedisCache

is completely locked down so, if you want to do something like 

```
public class CacheManagerRedis : RedisCache
{
        public CacheManagerRedis(IOptions<RedisCacheOptions> optionsAccessor) : base(optionsAccessor)
        {


        }
}
```

where you want to extend the functionality of the existing class, you cant override the existing method as none are virtual.

Also wen doing this you most likely want access to: (which is also private)
```
private volatile IConnectionMultiplexer _connection;
```

shouldn't the get and sets methods be virtual?

Main issue with the current implementation is you can query if its connected (online or offline) you cant hook into 
these mothod available on redis.

- ConnectionFailed

- ConnectionRestored
 
The IDistributedCache interaface would be nice if it had a method IsConnected exposed.

**Comment by davidfowl** [comment]
Nothing should be virtual, but it would make sense to understand how you want to extend the redis cache so we could make a decision about it.

**Comment by Seabizkit** [comment]
HI @davidfowl, sure...

I'm wanting to have my method only try Redis if Redis is available.
something like.... but...to achieve this is tricker than one would think.
```c#
public T GetOrAddDistributed<T>(string cacheKey, Func<T> factory)
{
    cacheKey = GetEnviromentCacheKey(cacheKey);
    ArgumentNullException.ThrowIfNull(factory);
    if (string.IsNullOrEmpty(cacheKey)) throw new ArgumentNullException("key");

    if (_distributedAvailable)
    {

        RedisValue redisValue = Cache.StringGet(cacheKey);
        if (redisValue.HasValue && redisValue != "{}")
        {
            return _jsonHelper.DeserializeObject<T>(redisValue);
        }
    }
    var result = factory();
    if (_distributedAvailable)
    {
        var mystring = _jsonHelper.SerializeObject(result);
        Cache.StringSet(cacheKey, mystring);
    }
    return result;
}
```
so currently im using Redis and registering it via, 

```c#
services.AddStackExchangeRedisCache(options =>
{
    options.Configuration = redisConn;
});
```
all good and working... but i want to implement a fallback, aka it can not access the Redis server for whatever reason....
I would like it to call the factory, which is just a delegate to the action on how to get the data.

Example:

````c#
var data =  _cacheManager.GetOrAddDistributed(cacheKey, () =>
{
    var res =  _organisationRepo.GetOrgIdByOrgName(orgName);
    return res;
});
````

now when Redis is down i want it to just do the actual call instead of trying redis....and only try redis again when back up.

should be able to hook into 
- ConnectionFailed
- ConnectionRestored

```c#
_connectionMultiplexer.ConnectionFailed += (sender, args) =>
{
    _distributedEnabled = false;
    var msg = "Connection failed, disabling redis...";
    _logger.LogCritical(msg);
};
_connectionMultiplexer.ConnectionRestored += (sender, args) =>
{
    _distributedEnabled = true;
    var msg = "Connection restored, redis is back...";
    _logger.LogCritical(msg);
};
```
on redis _connectionMultiplexer but its more involved than just this.
Can not get this working 100% yet but also its made even harder when you dnt have access to the internals, when you want to reuse all the goodness which is already been done.

**Comment by halter73** [comment]
What's wrong with implementing your own `IDistributedCache` that uses a private `RedisCache` field?

**Comment by BrennanConroy** [comment]
You can also provide your own implementation of `IConnectionMultiplexer` using [ConnectionFactory](https://source.dot.net/#Microsoft.AspNetCore.SignalR.StackExchangeRedis/RedisOptions.cs,57e86bd3b02bc2be,references).

**Comment by davidfowl** [comment]
This doesn't feel like a derived class, it feels like it would be better modeled via composition. Store an instance of the RedisCache implementation (what @halter73 said before I hit send 😄).
