### ISSUE TITLE
Kestrel network crash without any exceptions.

### ISSUE THREAD

**Issue by lvlkoo** [dotnet/aspnetcore#41792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In some cases app stops listen port, no exceptions, no logs, no extremely memory usage, nothing, just closes port and stops respond to requests.
netstat show that port isn't listening
Reproduces only in production, maybe it depends on requests amount.

### Steps To Reproduce

Self contained, single file, build for linux musl x64, packed to docker image.
Running on centos 7 behind apache

### Exceptions (if any)

I didn't found any dependencies (causing request, operation), its fully random, except of traffic. When app is high loaded it crashes ever 3-5 min. 

### .NET Version

6.0

### Anything else?

Please, I need some advice how to catch the problem, maybe I can enable some extra logging or anything else.

**Comment by davidfowl** [comment]
Try this https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/diagnostics?view=aspnetcore-6.0
