### ISSUE TITLE
Blazor Server-side Loses Connection Upon Extended Phone Lock

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#41791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This is based on this thread in the .NET Twitter Community/Group:
https://twitter.com/BuildItBusk/status/1528325252366884865

It appears that when a phone is locked for an extended period of time (10-20 minutes) and unlocked when visiting a Blazor server-side application, the connection is lost and it is not automatically reloaded, resulting in a poor user experience.

The connection appears to reconnect if locked for a few minutes, but for extended periods of time the connection gets lost altogether.

### Describe the solution you'd like

When thinking of sites such as Twitter, Facebook, etc, which all use WebSockets, this issue does not occur to them and is accounted for with their own mechanisms.  Ideally, this should also be easily addressed/configured with Blazor server-side applications as well.  If the connection is lost, there should be the option to:

1. Ask the user to reload (current/default)
2. Automatically refresh the browser for the user without prompting
3. Attempt to re-establish/reconnect/recreate the connection without having the need to refresh the browser at all

Number 3 is the most ideal and should arguably be the default in future versions.

### Additional context

Thank you for all your great work out there. I for one cannot underscore enough how much you are changing lives for the better with your efforts. :)

**Comment by javiercn** [comment]
@Mike-E-angelo thanks for contacting us.

This scenario is something we would like to cover as part of https://github.com/dotnet/aspnetcore/issues/30344

I'm going to mark this issue as a dupe, and I would suggest you upvote the referenced issue instead.

**Comment by Mike-E-angelo** [comment]
Great, thank you for the update and efforts out there @javiercn. 👍🙏
