### ISSUE TITLE
SignalR Error : Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#41809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to implement Authentication for SignalR hub and following this article
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#bearer-token-authentication

In the Code below i am trying to pass the Token, it just errors out,
if i comment this line, it works, options.AccessTokenProvider = () => Task.FromResult("This is jwt Token");
How can i pass the Token, if this method does not work ? 

```
hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/chathub"), options =>
            {
               **options.AccessTokenProvider = () => Task.FromResult("This is jwt Token");**
            
            })
            .WithAutomaticReconnect()
            .Build();
```

```
Failed to load resource: the server responded with a status of 500 ()
chathub/negotiate?negotiateVersion=1:1 
blazor.webassembly.js:1 System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
blazor.webassembly.js:1    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
2blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
blazor.webassembly.js:1    at BlazorChatApp.Client.Pages.MessagePage.OnInitializedAsync() in C:\Users\nssid\source\repos\BlazorChatApp\BlazorChatApp\Client\Pages\MessagePage.razor:line 76
```

### Expected Behavior

Should be able to pass jwt token to each message in SignalR

### Steps To Reproduce

Try to implement the step mentioned in this link
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#bearer-token-authentication

### Exceptions (if any)

Failed to load resource: the server responded with a status of 500 ()
chathub/negotiate?negotiateVersion=1:1 
blazor.webassembly.js:1 System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
blazor.webassembly.js:1    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
2blazor.webassembly.js:1    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
blazor.webassembly.js:1    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
blazor.webassembly.js:1    at BlazorChatApp.Client.Pages.MessagePage.OnInitializedAsync() in C:\Users\nssid\source\repos\BlazorChatApp\BlazorChatApp\Client\Pages\MessagePage.razor:line 76

### .NET Version

6.0.300

**Comment by BrennanConroy** [comment]
> the server responded with a status of 500

What do your server logs say? https://docs.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging
