### ISSUE TITLE
Missing project template translations for 'Do not use top-level statements' option in .NET 6.0.300 SDK

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#41802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.NET 6.0.300 SDK introduced a new 'Do not use top-level statements' option for the project templates. This new option is missing translations:

https://github.com/dotnet/aspnetcore/blob/98d12ef042ada22d022d8af11c67fd05e0b57e7f/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/.template.config/template.json#L389

```
    "UseProgramMain": {
      "type": "parameter",
      "datatype": "bool",
      "defaultValue": "false",
      "displayName": "Do not use top-level statements",
      "description": "Whether to generate an explicit Program class and Main method instead of top-level statements."
    }
```

https://github.com/dotnet/aspnetcore/blob/98d12ef042ada22d022d8af11c67fd05e0b57e7f/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/.template.config/fr-FR/strings.json

```
{
  "version": "1.0.0.0",
  "strings": {
    "name": "API web ASP.NET Core",
    "description": "Modèle de projet permettant de créer une application ASP.NET Core avec un exemple de contrôleur pour un service HTTP RESTful. Vous pouvez également utiliser ce modèle pour les vues et contrôleurs ASP.NET Core MVC.",
    "parameter.DisableOpenAPI.name": "Activer la prise en charge d'_OpenAPI",
    "parameter.DisableOpenAPI.description": "Active la prise en charge d'OpenAPI (Swagger)",
    "parameter.UseMinimalAPIs.name": "Utiliser des contrôleurs (décocher pour utiliser un minimum d'API)",
    "parameter.UseMinimalAPIs.description": "S'il faut utiliser des API minimales au lieu de contrôleurs."
  }
}
```

### Expected Behavior

The project template options are translated.

In Visual Studio for Mac this new option is not translated.

![image](https://user-images.githubusercontent.com/372361/169852078-f3ca5f49-eb4b-4140-afb3-72626087f671.png)

Presumably this is also the case in Visual Studio on Windows.

### .NET Version

6.0.300

### Anything else?

VS Mac 17.3

SDK .NET (reflétant tous les fichiers global.json) :
 Version:   6.0.300
 Commit:    8473146e7d

Environnement d'exécution :
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by captainsafia** [comment]
Will be fixed in 6.0.10.
