### ISSUE TITLE
Blazor WASM SEO Performance Test Issue

### ISSUE THREAD

**Issue by WalidMoheyEldin** [dotnet/aspnetcore#41807]
Hello,
How can I make SEO friendly application with Blazor WASM. I tried the default template and the test in GTMETRIX was 41% performance and after the search I found that I have to change the app to pre-render, after I changed it to pre-render the test was 68% and I have authentication issue that announced in Microsoft docs. 
I tried the DLL lazy loading but I can’t load assembly dll files on navigation even in the route because it is not working with pre-render.
So, please advise!

**Comment by SteveSandersonMS** [comment]
Prerendering is the main thing you need to do for SEO.

We don't have a specific list of suggestions on how to raise this GTMETRIX score higher - I'm afraid you'll have to look up how this particular score is determined. If you are able to provide specific requirements on what Blazor should be doing we can certainly consider that. If you find a specific bug when using prerendering with lazy loading, could you please post a full bug report with minimal repro steps?

There is some documentation about how to minimize the size of the WebAssembly app payload at https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-6.0#minimize-app-download-size
