### ISSUE TITLE
Custom serialization with TextOutputFormatter is slow

### ISSUE THREAD

**Issue by venknar** [dotnet/aspnetcore#41804]
Hi,
We have a need for custom serialization in asp.net core and have implemented a TextOutputFormatter that serialize specific entity to Json format. In that context have a custom TextOutputFormatter that serialize the content to Json.

Sample implementation is as follows:

```
    public class CustomerItemResponseFormatter : TextOutputFormatter
    {
        private const string ContentType = "application/json;odata.streaming=true";

        public CustomerItemResponseFormatter() : base()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse(ContentType));
            SupportedEncodings.Add(Encoding.UTF8);
        }

        public override bool CanWriteResult(OutputFormatterCanWriteContext context)
        {
            return context.Object is CustomerItemResponse;
        }
        public override async Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
        {
            CustomerItemResponse itemResponse = context.Object as CustomerItemResponse;
            if (itemResponse != null)
            {
                var response = context.HttpContext.Response;
                response.ContentType = ContentType;

                var pipeWriter = context.HttpContext.Response.BodyWriter;
                await WriteCustomerJsonData(pipeWriter, itemResponse);
            }
        }
     }
     
     public async Task WriteCustomerJsonData(PipeWriter pipeWriter,  CustomerItemResponse response)
     {
           PipeReader pipeReader = response.GetCustomerPicture();
           await pipeWriter.WriteAsync(response.Name);
           await pipeWriter.WriteAsync(response.Address);
           while (true)
           {
                 ReadResult result = pipeReader.ReadAsync();
                 ReadOnlySequence<byte> resultByte = result.Buffer
                 pipeWrite.WriteAsync(resultByte);
           }
     }
      
```

While testing in a single box setup (client and service are running in same box), the latency for reading 1MB data is approx 330 ms vs when I do not pipeWriter.WriteAsync then the latency comes down to 70 ms.

I understand that writing to the wire is taking time. But why does 75% of the time goes in this in a single box setup.
Is the data getting buffered or are we approaching the custom serialization in incorrect manner ?

Any guidance suggestions on how to implement this kind of custom serialization with low latency. 

Thank you

**Comment by davidfowl** [comment]
Are you asking for advice on how to better optimize your serializer? If you can share the implementation we might be able to help but it the code sample about is missing lots of details and performance results. What did you measure, did you take a performance profile? What is the client doing?

If you can produce a repeatable benchmark that anyone can run, we can help.

**Comment by venknar** [comment]
Hi
I have 2 questions.
1. Is this the right approach with asp.net core to do custom serialization or there is a better approach? Goal of doing this way is to ensure that we do not bring the entire data into memory and hence we use the pipeReader and pipeWriter from asp.net to send the data out.
2. Is the latency number expected ? In the sense for a total time of X ms, the 75% of X is going in streaming the data out using the pipeWriter.WriteAsync ? Should I explicitly do Flush Async or explicitly disable bufferring ? Any suggestions on how to speed up the streaming  of the data. 

The latency was measured from the caller. In this case we did some load testing using Jmeter. Are there any suggestion on what performance profile do I take to measure the latency ?

Let me try to create a standalone application that simulates this and share the same. 

Thank you for the help and inputs.

**Comment by davidfowl** [comment]
> Is this the right approach with asp.net core to do custom serialization or there is a better approach? Goal of doing this way is to ensure that we do not bring the entire data into memory and hence we use the pipeReader and pipeWriter from asp.net to send the data out.

Not sure what you mean. What serialization format are you using?

> Is the latency number expected ? In the sense for a total time of X ms, the 75% of X is going in streaming the data out using the pipeWriter.WriteAsync ? Should I explicitly do Flush Async or explicitly disable bufferring ? Any suggestions on how to speed up the streaming of the data.

I don't have thoughts on the top of my head.

**Comment by venknar** [comment]
Serialization format is Json with encoding being UTF8.

**Comment by davidfowl** [comment]
Why not use System.Text.Json? It does all of this an is optimized already. What made you go this route?

**Comment by venknar** [comment]
I think I found the root cause. The use of httpsys causes the slow down. 
In the Program.cs, we have this in the CreateHostBuilder
            webBuilder.UseHttpSys(options =>
                    {
                        options.UrlPrefixes.Add("https://+:444/CustomerService/");
                    });

If I use httpSys the latency is around 330 ms vs when i dont use its 75 ms

**Comment by davidfowl** [comment]
> In the above example for the field picturedata, we get a pipeReader to read the contents in chunk. If we go with System.text.Json, then we need to read the entire contents for picturedata in memory and then write the field picture data and its corresponding value.

Got it, you want to write individual JSON fields without buffering that entire field first. Thanks for the context. This makes sense.

So you are writing a custom serializer that writes out these fields and you'd like to make it efficient. How big are these field values?

> If I use httpSys the latency is around 330 ms vs when i dont use its 75 ms

Why are you using http.sys? This isn't a problem but just for my edification.

**Comment by venknar** [comment]
>> So you are writing a custom serializer that writes out these fields and you'd like to make it efficient. How big are these field values?
Yes. Using a custom serializer to write out these fields and want to make it efficient. The nice thing with custom serializer is that we can do this without buffering the entire data. The size of these fields can be from 1 MB to 32 MB max. For now we are mainly looking at 1 MB to 4 MB data.

>> Why are you using http.sys? This isn't a problem but just for my edification.
We have issues with port sharing with kestrel. Hence using http.sys. 

Is there any perf counter or profile that can check between using kestrel vs http sys and show that http sys is slower ? Any suggestions welcome.

Thanks for all your inputs and suggestions.

**Comment by venknar** [comment]
Finally found the root cause. It was not httpsys vs kestrel. Its http vs https. https encryption is making it slow. Thanks for all the help and inputs. Closing this issue. If its http then the latency is 70 ms vs https its 330 ms
