### ISSUE TITLE
HTTP/2: Consider increasing default window sizes

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#41825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The default HTTP/2 window sizes in Kestrel are relatively small. 96 KB for stream window size, 128 KB for connection window size. These will limit the speed a client can upload to Kestrel, especially in a high-latency scenario.

This is a simpler alternative to dynamic window sizing.

### Describe the solution you'd like

Increasing window size is simple to do. Should think about the implications of larger sizes from perf and resource usage, and consider making them bigger.

**Comment by adityamandaleeka** [comment]
Notes: we can introduce artificial latency in our benchmarks to tune the right values here.
