### ISSUE TITLE
.NET 6 Web API not working without .NET Core 2.1 Runtime in the server.

### ISSUE THREAD

**Issue by ponkumarpandian** [dotnet/aspnetcore#41837]
We are using below nuget packages for our WebAPI project. Since .NET Core 2.1 support has been end, as per our organization policy we are suppose to remove the .NET Core 2.1 runtime from the server as this is consider as a vulnerability. But we uninstall the .NET core 2.1 version , application not working and getting 500 internal server error .

Project 'XXX.YYY.ABC.FFF.Service' has the following package references
   [net6.0]:
   Top-level Package                                    Requested   Resolved
   > Microsoft.AspNetCore.Authentication.JwtBearer      6.0.0       6.0.0
   > Microsoft.AspNetCore.Cors                          2.2.0       2.2.0
   > Microsoft.AspNetCore.Mvc.NewtonsoftJson            6.0.0       6.0.0
   > Microsoft.EntityFrameworkCore                      6.0.0       6.0.0
   > Microsoft.EntityFrameworkCore.Design               6.0.0       6.0.0
   > Microsoft.EntityFrameworkCore.Relational           6.0.0       6.0.0
   > Microsoft.EntityFrameworkCore.SqlServer            6.0.0       6.0.0
   > Microsoft.IdentityModel.Tokens                     6.14.1      6.14.1
   > ncrontab                                           3.3.1       3.3.1
   > Serilog.Extensions.Logging.File                    2.0.0       2.0.0
   > System.DirectoryServices.Protocols                 6.0.0       6.0.0
   > System.Linq                                        4.3.0       4.3.0
   > System.Linq.Expressions                            4.3.0       4.3.0

**Comment by Tratcher** [comment]
> Microsoft.AspNetCore.Cors 2.2.0 2.2.0

This is likely your issue, remove that reference. The Tokens and Protocols packages should be fine.

**Comment by ponkumarpandian** [comment]
I have tried that as well and it did not help much. Problem with `Microsoft.Identity.Client 4.44.0 ` which is indirectly referenced in `Microsoft.EntityFrameworkCore.SqlServer 6.0.0` library. Here is the reference hierarchy,

`Microsoft.EntityFrameworkCore.SqlServer `==>` Microsoft.Data.SqlClient 4.1.0 `==> `Microsoft.Identity.Client 4.44.0`

So `Microsoft.Identity.Client 4.44.0` has .NET Core 2.1 framework dependency. Please refer the [nuget](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/6.0.0) for more details.

Please let me do you have any road map to remove 2.1 framework dependency? As per our organization policy .NET Core 2.1 consider as a vulnerability since support and update has been stopped. If you provide me the estimated deadline, I can convey the same.

**Comment by teo-tsirpanis** [comment]
> So `Microsoft.Identity.Client 4.44.0` has .NET Core 2.1 framework dependency. Please refer the nuget for more details.

You shouldn't be worried about _libraries_ targeting unsupported .NET Core versions. A library targeting .NET Core 2.1 means it can run .NET Core 2.1 _or newer_. It is your main executable app that needs to target a sufficiently new framework version. And this package is getting regular updates which means that it is supported.

**Comment by ponkumarpandian** [comment]
> > So `Microsoft.Identity.Client 4.44.0` has .NET Core 2.1 framework dependency. Please refer the nuget for more details.
> 
> You shouldn't be worried about _libraries_ targeting unsupported .NET Core versions. A library targeting .NET Core 2.1 means it can run .NET Core 2.1 _or newer_. It is your main executable app that needs to target a sufficiently new framework version. And this package is getting regular updates which means that it is supported.

Yes, But our application is not working if we don't install .net core 2.1 Runtime. May be due the above reference to 2.1 core .

**Comment by ponkumarpandian** [comment]
Getting 500 internal error and when I check the event logs, it says .netcore 2.1 not found  error.

**Comment by davidfowl** [comment]
@ponkumarpandian Can you paste the *exact* error message, or screen shot it. It's a bit ambiguous right now.

**Comment by ponkumarpandian** [comment]
@davidfowl Here is the details error message when run the api on the server with localhost url. I have attached the portion of my application dependency json content (highlighted in bold) which has a .NETCore2.1 framework dependency. 

**Error:**
_HTTP Error 500.21 - Internal Server Error
Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list_

![Error-500](https://user-images.githubusercontent.com/1834011/171018146-9abecea5-f4cc-4705-8c9e-c94327c68423.JPG)


{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v6.0",
    "signature": ""
  },

  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v6.0": {
      "PwC.SDC.TQE.Audit.Service/2.0.7": {
        "dependencies": {
          "DocumentFormat.OpenXml": "2.16.0",
          "Ical.Net": "4.2.0",
          "Microsoft.AspNetCore.Authentication.JwtBearer": "6.0.0",
          "Microsoft.AspNetCore.Mvc.NewtonsoftJson": "6.0.0",
          "Microsoft.EntityFrameworkCore": "6.0.0",
          "Microsoft.EntityFrameworkCore.Design": "6.0.0",
          "Microsoft.EntityFrameworkCore.Relational": "6.0.0",
          **"Microsoft.EntityFrameworkCore.SqlServer": "6.0.0",**
          "Microsoft.IdentityModel.Tokens": "6.14.1",
          "Serilog.Extensions.Logging.File": "2.0.0",
          "System.DirectoryServices.Protocols": "6.0.0",
          "NCrontab": "3.3.1"
        },
        "runtime": {
          "PwC.SDC.TQE.Audit.Service.dll": {}
        }
      },
      "Microsoft.Identity.Client/4.21.1": {
        "runtime": {
          **"lib/netcoreapp2.1/Microsoft.Identity.Client.dll": {**
            "assemblyVersion": "4.21.1.0",
            "fileVersion": "4.21.1.0"
          }
        }
      },
      "Microsoft.IdentityModel.JsonWebTokens/6.10.0": {
        "dependencies": {
          "Microsoft.IdentityModel.Tokens": "6.14.1"
        },
        "runtime": {
          "lib/netstandard2.0/Microsoft.IdentityModel.JsonWebTokens.dll": {
            "assemblyVersion": "6.10.0.0",
            "fileVersion": "6.10.0.20330"
          }
        }
      }
}

**Comment by ponkumarpandian** [comment]
@davidfowl Here is my web.config and detailed error message. As I mentioned earlier `Microsoft.Identity.Client` still have .netcoreappp 2.1 reference due to that it got failed. 

Please let me if you need any further information.

```
Content root path: E:\SME Review\Prod\Services\Audit
Now listening on: http://127.0.0.1:12232
Application started. Press Ctrl+C to shut down.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: PwC.SDC.TQE.Audit.Service.Controllers.AuditsController[0]
      The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
      System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
       ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
      File name: 'Microsoft.Identity.Client, Version=4.21.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
         at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider..ctor(String applicationClientId)
``` 



```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <remove name="X-Powered-By" />
      </customHeaders>
    </httpProtocol>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" requestTimeout="00:10:00">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

**Comment by ponkumarpandian** [comment]
Just wanted to give update on what I understood on this issue, I have manually upgraded the following packages to latest version and it is started working, 
`Microsoft.EntityFrameworkCore.SqlServer - 6.0.0 --> 6.0.5`
`Microsoft.Data.SqlClient -  2.1.4  --> 4.1.0`
`Microsoft.Identity.Client  - 4.21.1 -->  4.44.0`

But the question when we upgrade Microsoft.EntityFrameworkCore.SqlServer to latest version, it's dependencies also should upgrade to the latest version. Please let me know what is the expected behaviour on this?

**Comment by ponkumarpandian** [comment]
Sorry I was wrong, I am still getting same error even though I upgraded to the latest one. I just cross verified my server had `.net core 2.1.3 - Windows Server Hosting` and because of that it worked . 
If I uninstall `.net core 2.1.3 - Windows Server Hosting` from my server, I am getting same error as mentioned before.

Can someone please let me know the work around? I am running out time , need to resolve as soon as possible otherwise my application need to be go down. It will be great if someone respond this issue quickly.

**Comment by adityamandaleeka** [comment]
> If I uninstall .net core 2.1.3 - Windows Server Hosting from my server, I am getting same error as mentioned before.

There are two errors shown above, the one about the bad module and the one about `SqlAuthenticationProviderManager`. Which one are you seeing?

**Comment by ponkumarpandian** [comment]
@adityamandaleeka Bad module error resolved once I update the web.config with `AspNetCoreModuleV2` model. After upgrading the package I am still facing the  `SqlAuthenticationProviderManager` error due to .netcoreapp 2.1 dependency and my IIS server doesn't have .netcoreapp 2.1 version installed.

**Comment by davidfowl** [comment]
@ponkumarpandian Can you clarify what you mean by the netcoreapp2.1 dependency? What are you referring to?

**Comment by ponkumarpandian** [comment]
@davidfowl Please refer to the below screenshot, `Microsoft.Identity.Client` package reference in `Microsoft.Data.SqlClient` which is referenced in `Microsoft.EntityFrameworkCore.SqlServer` package. It is clearly shows  `Microsoft.Identity.Client` has `.netcoreapp 2.1` framework dependency. Due to this package has .netcoreapp2.1 framework dependency, our application not even starting since the application running on IIS onprime server where we don't have .netcore 2.1 framework installed. This server have only .NET 6 run time. 

Please let me know if you need further information and help me to resolve this issue as soon as possible. 

![NETCore2 1_Dependancy](https://user-images.githubusercontent.com/1834011/172141112-7e4e00e8-ab0f-49c0-a93d-945b1e1ecb3d.jpg)

**Comment by adityamandaleeka** [comment]
It looks like the Microsoft.Identity.Client library only supports netcoreapp2.1 and net5.0-windows10.0.17763 (https://www.nuget.org/packages/Microsoft.Identity.Client/4.44.0). Unfortunately, there's nothing we (ASP.NET Core) can do about that.

Can you file this issue over at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet so that they can add net6 support? .NET 5 is now out of support.

**Comment by ponkumarpandian** [comment]
@adityamandaleeka You mean if I target my application to .Net 5.0 and deploy the application to server without .netcore 2.1 framework, will it work?
