### ISSUE TITLE
No SignalR server ping when using WebHost and IHostApplicationLifetime

### ISSUE THREAD

**Issue by Fl0GUI** [dotnet/aspnetcore#41833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A SignalR server does not send out server pings when using a `WebHost` in Program.cs and configuring `IHostApplicationLifetime` as a singleton service.
This causes client to close the connection after its server timeout.

I don't know the internals of aspnetcore but I think the `ApplicationLifetime` service is being overwritten which causes the heartbeat of SignalR's internals to not fire. Removing or using `TryAddSingleton` for the `IHostApplicationLifetime` creates no bugs.

### Expected Behavior

The Server pings the client when no other traffic is sent to the client.

### Steps To Reproduce

1) Open the [ChatSample](https://github.com/aspnet/SignalR-samples/tree/main/ChatSample). It also works on the tutorial from [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-6.0&tabs=visual-studio).

2) In Program.cs:
use 
```C#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
   WebHost.CreateDefaultBuilder(args)
   .UseStartup<Startup>();
```
instead of `CreateHostBuilder`.

3) In Startup.cs:
add
```C#
services.AddSingleton<IHostApplicationLifetime, ApplicationLifetime>();
```
to `ConfigureServices`.

4) Run it and observe the traffic in the websocket, or rather the lack of ping traffic from the server to the client. Reduce the `KeepAliveInterval` in the server to speed things up (and see nothing faster 😁). Switching between `CreateWebHostBuilder` and `CreateHostBuilder` clearly shows the difference however.

### .NET Version

3.0 for the chatsample, 5.0 for the tutorial

### Anything else?

A workaround for this is to not add the `IHostApplicationLifetime` singleton. Everything works fine without that line. Unfortunately this was already in place when I was tasked with adding SignalR functionality. This bug has been terrible to discover.

**Comment by Tratcher** [comment]
Why are you registering IHostApplicationLifetime? That's provided by the host.

**Comment by BrennanConroy** [comment]
If you replace the `IHostApplicationLifetime` then you also need to be responsible for triggering the `ApplicationStarted` cancellation token. Otherwise, components (like SignalR) that rely on `ApplicationStarted` being triggered wont act as expected.
