### ISSUE TITLE
Enable an XSS Prefix to JSON formatted output.

### ISSUE THREAD

**Issue by grosch** [dotnet/aspnetcore#41848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When outputting JSON, it's prevalent to prefix with a well-known set of characters:  )]}',\n

Chrome, Angular, etc... all know to strip that from the output when it's there. Right now that is incredibly difficult to accomplish in an API. 

### Describe the solution you'd like

When calling `AddJsonOptions` on an `IServiceCollection` it would be great to be able to just do something like this:

```cs
builder.Services.AddJsonOptions(options => options.JsonSerializerOptions.XssPrefix = ")]}',\n");
```

### Additional context

Right now, to accomplish that, the only way I've found is this monstrosity:

```cs
public class JsonPrefixFilter : IAsyncResultFilter
{
    #region IAsyncResultFilter implementation
    public async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
    {
        var response = context.HttpContext.Response;

        // ASP.NET Core will always send the contents of the original Body stream back to the client.
        var originalBody = response.Body;

        // We want to write into a memory stream instead of the actual response body for now.
        using var ms = new MemoryStream();
        response.Body = ms;

        // After this call the body is written into the memory stream and the properties
        // of the response object are populated.
        await next();


        if (response.ContentType != null && response.ContentType.StartsWith("application/json") && response.StatusCode != 204) {
            var prefix = Encoding.UTF8.GetBytes(")]}',\n");
            var buffer = ms.ToArray();
            
            context.HttpContext.Response.Headers.ContentLength = buffer.Length + prefix.Length;

            using var prefixMemoryStream = new MemoryStream();

            await prefixMemoryStream.WriteAsync(prefix);
            await prefixMemoryStream.WriteAsync(buffer);

            prefixMemoryStream.Seek(0, SeekOrigin.Begin);

            // Now put the stream back that .NET wants to use and copy the memory stream to it.
            response.Body = originalBody;
            await prefixMemoryStream.CopyToAsync(response.Body);
        } else {
            // If it's not JSON, don't muck with the stream, so just put things back.
            response.Body = originalBody;
            ms.Seek(0, SeekOrigin.Begin);
            await ms.CopyToAsync(response.Body);
        }
    }
    #endregion
}
```

Plus you can imagine the joy that is writing tests for that :)

**Comment by javiercn** [comment]
@grosch thanks for contacting us.

I'll let other folks in this area chime in, but I believe there are easier ways to accomplish this.

You could wrap the IHttpResponseBodyFeature inside a middleware and if you detect that the response contains JSON (based on the response content-type) then you write the prefix. That avoids all the additional buffering that you are now doing, since you get a chance to intercept the writes to the actual response stream.

**Comment by blowdart** [comment]
_When outputting JSON, it's prevalent to prefix with a well-known set of characters: )]}',\n_

I'd like to chime in on this - by asking why? The browser knows it's json, the browser knows how to render a json response if it hits it directly, what do you feel is the XSS risk?
