### ISSUE TITLE
Link in gRPC template creating a client support points to .NET Core 3.0 tutorial

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#41852]
Should be updated to point to relevant version for the template.

FYI @JamesNK

**Comment by JamesNK** [comment]
Do you mean this link? https://github.com/dotnet/aspnetcore/blob/fc94cb7bcee8d37378ecc471a53b72cb4fb1782c/src/ProjectTemplates/Web.ProjectTemplates/content/GrpcService-CSharp/Program.cs#L6

It points to https://docs.microsoft.com/aspnet/core/grpc/troubleshoot#unable-to-start-aspnet-core-grpc-app-on-macos (note: no version)

**Comment by DamianEdwards** [comment]
Hmmm, I'll have to check but when I clicked on it I landed on a docs page for 3.1.

**Comment by DamianEdwards** [comment]
Fixed.
