### ISSUE TITLE
Hot Reload (Blazor WASM) not working when Solution Configuration is not Debug

### ISSUE THREAD

**Issue by mishael-o** [dotnet/aspnetcore#41867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot reload throws an exception when using a custom solution configuration and debugging from Visual Studio 2022. See below.

Custom Solution Configuration:
![image](https://user-images.githubusercontent.com/49244132/170469297-5363fcc5-d5ab-4ebf-a593-73e698c2e5ba.png)

Visual Studio Error:
![image](https://user-images.githubusercontent.com/49244132/170468450-c865eaf8-1311-422c-a691-d1b6aa817656.png)

Error Log:
![image](https://user-images.githubusercontent.com/49244132/170469125-a37fd456-78fb-4bc3-8cad-c4b5db60bac8.png)

However if I change the configuration back to **Debug**, it works.  It also doesn't work if I change it to **Release**.

Interestingly, if I do a `dotnet watch run` on the cli with the custom solution configuration it works.

Visual Studio Version: 17.2.2

### Steps To Reproduce

- Create a new Blazor WASM project
- Add a custom solution configuration
- Run project in debug mode with custom solution configuration
- Try to apply code changes via Hot Reload

### .NET Version

6.0.300

**Comment by SteveSandersonMS** [comment]
@mishael-o Sorry for the inconvenience. The hot reload system currently relies on knowing more about what's going on during the build, and this is triggered by the Debug configuration.

For the time being the most realistic way forwards for you would be to use hot reload only in conjunction with the Debug configuration. Longer term we may be able to generalize this.

**Comment by mishael-o** [comment]
@SteveSandersonMS Thanks for the feedback, however that workaround won't be feasible on some other projects we work on, as we use Development, QA and Production as our solution configurations. It's unfortunate that it only works if there is a Debug configuration present.

**Comment by mkArtakMSFT** [comment]
We think this is fixed already. Can you please try out the latest 8.0 release and see if you still experience this issue? Thanks!

**Comment by mishael-o** [comment]
@mkArtakMSFT thanks. This looks to be resolved.
