### ISSUE TITLE
builder.Services.AddHostedService<TimerBackgroundService>();  has no effect

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#41860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a Blazor MAUI Hybrid Project.
I was trying to run a service in the background using the following command

```C#
builder.Services.AddSingleton<TimerBackgroundService>();
builder.Services.AddHostedService(sp => sp.GetRequiredService<TimerBackgroundService>());
```

This has no effect whatsoever, even the constructor of TimerBackgroundService does not run

All the examples i saw were for server side scenario, not sure if this is supported in Blazor wasm or Blazor Hybrid Porjects.

If it is supported, why is it not executing .

Here is the actual background service

```C#
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace SchedulingMobile.Services
{
    public class TimerBackgroundService : BackgroundService
    {
        public TimerBackgroundService()
        {
            Console.WriteLine("Instance Created");
        }
        public static event Func<DateTime, Task> UpdateEvent;
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while(!stoppingToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(10)); //Every 1 minute
                await UpdateEvent(DateTime.Now);
            }
        }

        public override Task StartAsync(CancellationToken cancellationToken)
        {
            return base.StartAsync(cancellationToken);
        }
    }
}

```

### Expected Behavior

Was expecting the TimerBackground service code to execute.

### Steps To Reproduce

Add the  
builder.Services.AddSingleton<TimerBackgroundService>();
 builder.Services.AddHostedService(sp => sp.GetRequiredService<TimerBackgroundService>());

in Blazor Wasm or BlazorHyrbid Project

### Exceptions (if any)

None

### .NET Version

6.0.300

**Comment by eerhardt** [comment]
> If it is supported, why is it not executing .

It isn't supported. See reasoning here: 

https://github.com/dotnet/maui/issues/4393

Specifically (4), which I copied here:

> Extensions.Hosting's main concept is its "Hosted Services" or BackgroundService. While this is definitely a useful concept in a client application, the abstraction isn't correct for client apps. Hosted Services get "Start" and "Stop". But what if the app is getting deactivated? Can the service tell the difference between that and the app being closed? Should all the Hosted Services get resumed when the app is resumed? These are all scenarios that would need to work and the Hosted Service abstraction isn't designed for these scenarios. Maui apps that need background service functionality need to use something that is designed for client apps.

**Comment by eerhardt** [comment]
There are other ways to enable this scenario, though. One example is https://github.com/shinyorg/shiny. I've never personally used it, but my understanding is that it works well.

**Comment by nssidhu** [comment]
Shiny looks promising, but version specific to MAUI is in alpha release, the stable ones are for Xamarin platform.

**Comment by aritchie** [comment]
You don't want a hosted service.  ASP.NET will wait for all hosted services to start - android & ios apps cannot.  What you really want is an IMauiInitializeService or yes, Shiny also has IShinyStartupTask which is similar.  Both of these concepts can be found here: https://github.com/shinyorg/shiny/tree/master/src/Shiny.Hosting.Maui

**Comment by nssidhu** [comment]
@aritchie 
when do you think shiny version 3 will be released ?
