### ISSUE TITLE
CookieBuilder SameSite XML documentation is incorrect

### ISSUE THREAD

**Issue by Simeon231** [dotnet/aspnetcore#41871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The XML documentation of [CookieBuilder SameSite](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/CookieBuilder.cs#L51) is incorrect. As mention here [SameSite Documentation](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-6.0#api-usage-with-samesite) and in this [Issue](https://github.com/dotnet/aspnetcore/issues/8212) the default value of SameSite is not always Unspecified. The default value varies for the different components.

### Expected Behavior

The behavior that I would expect is to remove this sentence `The default value is <see cref="SameSiteMode.Unspecified"/>` from the XML documentation and add the official URL where it is explained better i.e. https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-6.0#api-usage-with-samesite.

**Comment by blowdart** [comment]
The documentation is correct, you see the [default value] (https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/CookieBuilder.cs#L51)for CookieBuilder being set just after the XML documentation. 

The SameSite documentation discusses how individual components override the default for their own purposes.

**Comment by Simeon231** [comment]
I understand that the components are overriding the default behaviour and I think this is where it is confusing. I was using OpenIdConnect and this comment confused me quite a lot. Wasted some time until I realized that the default behaviour is different than what is says. I think either CookieBuilder XML comment should be updated or the components XML comments should be updated.

**Comment by Simeon231** [comment]
I took a look at all components (should have done it earlier) and what I thought initially is not 100% correct. I thought all of the components SameSite XML comments are incorrect but after I saw all of them only a few are incorrect. [TwitterOptions](github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Twitter/src/TwitterOptions.cs#L84), [RemoteAuthenticationOptions](github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L140) and  [OpenIdConnectOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L293). I hope now it makes more sense. So I guess what should be changed is their XML comments.

**Comment by adityamandaleeka** [comment]
Adding some context in a remark (link to conceptual doc) on CookieBuilder would be okay, if only to clarify what other things might do with the CookieBuilder.
