### ISSUE TITLE
[Feature request] Office 365 + Blazor = perfect add-in framework

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/aspnetcore#41885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I know it's a long shot and probably even I choose wrong repo (MS Office isn't as open as .NET) but maybe with some insider's help it will reach right people.

I'm a long-time VBA developer and in the big corporate world it's not going anywhere due to following reasons:
1. Straightforward runtime. Every computer with MS Office installed is able to run a macro out-of-the-box
2. IDE Availability. Every computer with MS Office installed is also dev machine - VBE is default component
3. No-IT fuss. Not to upset anyone but asking IT to install something on your (or users) machine can be a massive hurdle
4. Distribution simplicity. Code can be embedded and distributed with the xlsm archive

However for developer in 2022 it's a nightmare to use VBE and outdated APIs when we also know how nice .NET, VS and VS Code can be.

Previous attempts to replace VBA did not landed well imo. VSTO add-in model being based on .NET Framework works on Windows only (no Web or other platforms support). Then we had web-based addins. Devs learned Node.js and javascript with all of its quirks, just to be slowed down by sandbox environment, poor performance and problematic distribution model. 

It feels that modern ASP.NET Core combined with Blazor (especially WASM) would fit perfectly in the landscape giving best of both worlds - native performance and web compatibility. It would also be more welcoming for dev's who already know .NET, C# and are used to modern tools. 

MS Office must catch up. Please.

### Describe the solution you'd like

Upgrade MS Office applications with modern dev tools:
1. Integrate .NET (not .NET Framework or Node.js)
2. Add C# and F# scripting support
3. Integrate modern IDE like VS Code not Script Lab
4. Use Blazor as a modern UI framework

**Comment by javiercn** [comment]
@BieleckiLtd thanks for contacting us.

We appreciate all feedback, unfortunately this is not an area of work we would try to tackle as our team focuses on the core libraries and experience. For that reason, I'm going to close this issue, but I'll ping some people to see if we can forward this feedback to the appropriate teams.

**Comment by rysweet** [comment]
@BieleckiLtd - my first inclination is to ask if you have considered PowerApps/PowerAutomate for filling that same need of lightweight easy to deploy apps inside of or integrated with Office and "under the radar of IT"? 

In the meantime I'm also trying to make sure the relevant people in other teams have a look at your message. Thanks for the feedback!
