### ISSUE TITLE
Help on #41471 use my own NewtonsoftJsonInputFormatter

### ISSUE THREAD

**Issue by DaveLaa** [dotnet/aspnetcore#41883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is sad to hear that #41471 will not be fixed in .Net 6.

I was migrating from .Net Framework to .Net 5 and then up to .Net 6 and this is the only breaking change in the core framework that prevents my project to run. My frontend developers have to work through milions of lines of code just to fix problems that have not been there in .Net Framework before, just because the NewtonsoftJsonInputFormatter is not error tollerant like the old mechanism was.

But ok.

Can you plz tell me how i can "deserialize the message body" myself then (like halter73 suggested in https://github.com/dotnet/aspnetcore/issues/41471#issuecomment-1132257323)? I mean I dont want to rewrite the complete Microsoft.AspNetCore.Mvc.NewtonsoftJson project just to add this one line of code... Is there a simple way to just override the NewtonsoftJsonInputFormatter with my own implementation and activate and use my class?

**Comment by brunolins16** [comment]
@DaveLaa we decided to backport the change to .NET 6 and we are planning to have it available in 6.0.7. You will need to opt-in to the new behavior by setting a [AppContext switch](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=net-6.0#appcontext-for-library-consumers).

**SwitchName**:  `Microsoft.AspNetCore.Mvc.NewtonsoftJson.EnableSkipHandledError`
