### ISSUE TITLE
Make Web API Analyzers part of the default template

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41889]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Make-Web-API-Analyzers-part-of-the-defau/1689638)._

---
Created a new Web API project targeting dotnet 6. It would be nice if the new project referenced the web api analyzers to help me build a controller with good Open API annotations.

https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-6.0

---
#### Feedback Bot on 3/10/2022, 11:45 PM: 

(private comment, text removed)

**Comment by captainsafia** [comment]
Thanks for filing this issue!

At the moment, we don't feel there is significant value add in enabling this property by default in the templates so we'll opt out of this addition.
