### ISSUE TITLE
Asp.net core DI error

### ISSUE THREAD

**Issue by shkar-dev** [dotnet/aspnetcore#41881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i want to insert data into database with EF core 6 while using DI in my controller  the error is shown which says you have multiple constructors which i have only one  and this is a error message 

InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'test1.Controllers.CompanyController'. There should only be one applicable constructor.

### Expected Behavior

 

        private readonly test1.Data.ApplicationContext _context;
        public CompanyController(test1.Data.ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        //public async Task<IActionResult> Create(Company company)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (_context.Companies != null)
        //        {
        //            _context.Companies.Add(company);
        //            await _context.SaveChangesAsync();
        //            Message("Success");
        //            return RedirectToAction("Index");
        //        }
        //        Message("Failed");
        //        return  RedirectToAction("Index");
        //    }
        //     Message("Failed");
        //        return  RedirectToAction("Index");
        //}

        public void Message(string Type )
        {
            if(Type == "Sucess")
            {
                ViewBag.Text = "Information Inserted Successfully";
            }
            else
            {
                ViewBag.Text = "There is an Error !";
            }
        }
    }
}

### Exceptions (if any)

InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'test1.Controllers.CompanyController'. There should only be one applicable constructor.

### .NET Version

dotnet version 6.0.300

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.300
  

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
   

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

**Comment by davidfowl** [comment]
That errors seems pretty clear to me. You have ambiguous constructors. Can you remove one of them?

**Comment by shkar-dev** [comment]
i have only one constructor
