### ISSUE TITLE
Inconsistent `crossgen2` build failures

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#41891]
## Build Information
Build: https://runfo.azurewebsites.net/view/build/?number=1788535
Leg Name: `*Windows*`

## Error Message

```json 
{ "ErrorMessage":"Unable to load native library 'Microsoft.DiaSymReader.Native'" }
```

## If you hit this

The problem usually goes away on retry. `Rerun failed jobs` in the AzDO pipeline, `Re-run` in the `Checks` tab of your PR, add an `/azp run` comment in your PR (avoid this if you can, it's inefficient), or update your PR's branch.
#### Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

**Comment by dougbu** [comment]
@AlitzelMendez @missymessa @riarenas will the infrastructure handle wildcards in the `Leg Name` portion of the template❔ If not, what's the best way to handle both `Build: Windows ARM` and `Build: Windows x64/x86`❔

**Comment by riarenas** [comment]
I think only the error message is important for the automation to get the issues picked up, and the leg Name is more so that we don't have to guess where exactly in a build with multiple jobs the error might have happened. 

@AlitzelMendez and @ulisesh to confirm and/or correct my understanding.

**Comment by dougbu** [comment]
Thanks @riarenas

**Comment by ulisesh** [comment]
> I think only the error message is important for the automation to get the issues picked up, and the leg Name is more so that we don't have to guess where exactly in a build with multiple jobs the error might have happened.
> 
> @AlitzelMendez and @ulisesh to confirm and/or correct my understanding.

That's correct. The leg name is for people who are investigating the issue but isn't used by the automation

**Comment by dougbu** [comment]
`runfo` query for this problem is <https://runfo.azurewebsites.net/search/build-logs/?bq=started%3A~14%20definition%3Aaspnetcore-ci%20targetbranch%3Amain&lq=text%3A%22unable%20to%20load%20native%20library%20%27microsoft.diasymreader.native%27%22%20logname%3Awindows>. Other recent failures (not all of which show up in this query right now) include:

- [20220518.35](https://dev.azure.com/dnceng/public/_build/results?buildId=1778379&view=results)
- [20220519.24](https://dev.azure.com/dnceng/public/_build/results?buildId=1780869&view=results)
- [20220521.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1782895&view=results)
- [20220521.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1783116&view=results)
- [20220523.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1784393&view=results)
- [20220523.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1784615&view=results)

**Comment by dougbu** [comment]
External issue is dotnet/runtime#69743. @MichalStrehovsky has dotnet/runtime#69842 open to get more information. Once that merges, the next failure here should help understand what's going wrong.

@BrennanConroy did you learn anything from the binary logs you were looking at yesterday❔

/fyi @MackinnonBuck if you're contacted about a failure that looks like this one, please check to make sure it's shown in the `Build Analysis` page under the `Checks` tab. I may have messed up the template.

**Comment by dougbu** [comment]
Another question for @riarenas @ulisesh @AlitzelMendez @missymessa: I added a newline after the Error Message JSON because otherwise the closing triple-ticks weren't recognized and the `If you hit this` second was also considered JSON. Will this prevent associating failures w/ this issue❔

**Comment by am11** [comment]
[symreader](https://github.com/dotnet/symreader/blob/652d0a3e60467021e60cd8b933da84d69b7f5b3c/README.md)'s README recommends:

> It is recommended that new applications and libraries read Portable PDBs directly using APIs provided by [System.Reflection.Metadata](https://www.nuget.org/packages/System.Reflection.Metadata) package. These APIs are much more efficient than DiaSymReader APIs. Microsoft.DiaSymReader.PortablePdb bridge is recommended for existings apps that already use DiaSymReader APIs and need to be able to read Portable PDBs without significant changes to their source.

`System.Reflection.Metadata` currently does not support reading Windows PDB (it only supports Portable PDB), I think that is why various components of runtime (including CG2) still depend on  DiaSymReader.Native.

(If we want to continue to support Windows PDB in .NET indefinitely) Ideally, we can act on David's suggestion https://github.com/dotnet/runtime/issues/43904#issuecomment-880256125 and add managed WindowsPdbReader/Writer to get rid of symreader dependency once in for all, but it is a non-trivial task. https://github.com/microsoft/microsoft-pdb and LLVM's PDB [reader](https://github.com/llvm/llvm-project/blob/0e8f4ce31df192d188239575839d8cceb47caf85/llvm/lib/DebugInfo/PDB/Native/NativeSession.cpp#L92) and [writer](https://github.com/llvm/llvm-project/blob/0e8f4ce31df192d188239575839d8cceb47caf85/lld/COFF/PDB.cpp#L1569) are likely the most relevant / battle-tested references, if someone is looking to write managed counterpart.

**Comment by agocke** [comment]
FYI @MichalStrehovsky, I'm not sure if this could be a problem with native resource loading in NativeAOT. I downloaded the package and it has the following files:

>clrjit_universal_arm_x64.dll    
clrjit_win_x64_x64.dll  crossgen2.exe                 
Microsoft.DiaSymReader.Native.amd64.dll
clrjit_universal_arm64_x64.dll  
clrjit_win_x86_x64.dll 
 crossgen2.runtimeconfig.json
clrjit_unix_x64_x64.dll         
crossgen2.deps.json     
jitinterface_x64.dll

**Comment by ulisesh** [comment]
> Another question for @riarenas @ulisesh @AlitzelMendez @missymessa: I added a newline after the Error Message JSON because otherwise the closing triple-ticks weren't recognized and the `If you hit this` section was also considered JSON. Will this prevent associating failures w/ this issue❔

It shouldn't prevent it, the way it is written right now should work

**Comment by dougbu** [comment]
#41866 should have resolved this issue by bringing in dotnet/runtime#69937 fix🤞 I believe the plan is to close the issue a few days after that merged, assuming no further failures. I'll check back on Monday or Tuesday.
