### ISSUE TITLE
Detected package version outside of dependency constraint: Duende.IdentityServer.EntityFramework.Storage 5.2.0

### ISSUE THREAD

**Issue by Ogglas** [dotnet/aspnetcore#41897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I got a warning/error in Visual Studio when installing NuGet `AutoMapper`:

> NU1608 Detected package version outside of dependency constraint:
> Duende.IdentityServer.EntityFramework.Storage 5.2.0 requires
> AutoMapper (>= 10.0.0 && < 11.0.0) but version AutoMapper 11.0.1 was
> resolved.

I tracked this to NuGet `Microsoft.AspNetCore.ApiAuthorization.IdentityServer`

https://www.nuget.org/packages/Microsoft.AspNetCore.ApiAuthorization.IdentityServer

If you look at Microsoft.AspNetCore.ApiAuthorization.IdentityServer NuGet dependencies is:

 - net6.0
 - Duende.IdentityServer (>= 5.2.0)
 - Duende.IdentityServer.AspNetIdentity (>= 5.2.0)
 - Duende.IdentityServer.EntityFramework (>= 5.2.0)
 - Duende.IdentityServer.EntityFramework.Storage (>= 5.2.0)
 - Duende.IdentityServer.Storage (>= 5.2.0)
 - Microsoft.AspNetCore.Authentication.JwtBearer (>= 6.0.5)
 - Microsoft.AspNetCore.Identity.EntityFrameworkCore (>= 6.0.5)
 - Microsoft.AspNetCore.Identity.UI (>= 6.0.5)
 - Microsoft.Extensions.Http (>= 6.0.0)
 - Newtonsoft.Json (>= 13.0.1)

I can solve the warning manually by updating the libraries below:

 - Duende.IdentityServer
 - Duende.IdentityServer.AspNetIdentity
 - Duende.IdentityServer.EntityFramework
 - Duende.IdentityServer.EntityFramework.Storage
 - Duende.IdentityServer.Storage 

Duende.IdentityServer.EntityFramework.Storage 6.1.0 has the following dependencies which will fix it:

 - net6.0
 - AutoMapper (>= 11.0.0 && < 12.0.0)
 - Duende.IdentityServer.Storage (>= 6.1.0)
 - Microsoft.EntityFrameworkCore.Relational (>= 6.0.0)

https://www.nuget.org/packages/Duende.IdentityServer.EntityFramework.Storage/

However this led to the exception below after running a migration in `endpoints.MapRazorPages();`.

> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or
> more of the requested types. Method 'get_ServerSideSessions' in type
> 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1'
> from assembly 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer,
> Version=6.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
> does not have an implementation.'

### Describe the solution you'd like

Latest `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` should be compatible with latest `Duende.IdentityServer.EntityFramework.Storage`

**Comment by StonedHackerman** [comment]
same issue

**Comment by wtgodbe** [comment]
@HaoK related to https://github.com/dotnet/aspnetcore/issues/41315, do we need to backport that change to 6.0?

**Comment by HaoK** [comment]
I don't think so, upgrading versions for 7 isn't the same thing as bumping up versions in 6, if they are able to upgrade the packages to make everything work.

@Ogglas is everything working after you upgraded all of the relevant duende packages yourself?

**Comment by Ogglas** [comment]
@HaoK Nope I got the exception below in `endpoints.MapRazorPages();`.

> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or
> more of the requested types. Method 'get_ServerSideSessions' in type
> 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1'
> from assembly 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer,
> Version=6.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
> does not have an implementation.'

**Comment by BrennanConroy** [comment]
Looks like there may be breaking changes between Duende 5.x and 6.x. We recommend using 7.0 once we [update the dependency to 6.x](https://github.com/dotnet/aspnetcore/pull/41896). We can't update the dependency in .net 6.0 as it may be breaking.

**Comment by picBuilderLabs** [comment]
Getting the following exception
`System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types. Method 'get_ServerSideSessions' in type 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1' from assembly `
 after updating the nuget package Duende.IdentityServer.EntityFramework to version 6.1.0. Reverting this package back to 6.0.4 resolves this error , seems like there is an incompatibility introduced. If anyone has a fix so I can upgrade this package is appreciated.

**Comment by neozhu** [comment]
@picBuilderLabs 
I have the same problem when upgrading to Duende.IdentityServer.EntityFramework to version 6.1.0.

**Comment by borgarer** [comment]
@picBuilderLabs same issue here. Have you guys found any workarounds orther than reverting back to 6.0.4?

**Comment by yakeer** [comment]
Any news on this issue?

**Comment by borgarer** [comment]
Hi @yakeer 
In my case, it turned out that I wasn't actually using anything from the Microsoft.AspNetCore.ApiAuthorization.IdentityServer package. So by removing its reference from my .csproj the exception disappeared. 

I see they have releaased v. 6.0.7 only 7 days ago. You might also want to try and see if the issue has been addressed there.
