### ISSUE TITLE
Why HashPassword method inside Identity PasswordHasher<T> class has TUser as a parameter ?

### ISSUE THREAD

**Issue by fededim** [dotnet/aspnetcore#41898]
It should only accept the string which has to be hashed. Moreover if you look at the [implementation](https://github.com/dotnet/aspnetcore/blob/b56bb17db3ae73ce5a8664a2023a9b9af89499dd/src/Identity/Extensions.Core/src/PasswordHasher.cs#L96L111) the user parameter is not even used or checked.

```
public virtual string HashPassword(TUser user, string password)
    {
        if (password == null)
        {
            throw new ArgumentNullException(nameof(password));
        }

        if (_compatibilityMode == PasswordHasherCompatibilityMode.IdentityV2)
        {
            return Convert.ToBase64String(HashPasswordV2(password, _rng));
        }
        else
        {
            return Convert.ToBase64String(HashPasswordV3(password, _rng));
        }
    }
```

**Comment by vanbukin** [comment]
For me it’s an extensibility point. I can implement custom logic that depends on user properties.

**Comment by HaoK** [comment]
Yes this was explicitly added so custom logic can access the user's properties to do more complex things

**Comment by fededim** [comment]
Just a thought: since TUser is a database table and it is mutable by default, any additional parameter that you wish to use in the hashing function should be saved together with the resulting hash (like you do for salt) in order to get the same hash on the same password; this would involve an increase in the size of the hash without getting, IMHO, any real advantage over the actual implementation.
