### ISSUE TITLE
Security vulnerability reported for event source package

### ISSUE THREAD

**Issue by swasun99** [dotnet/aspnetcore#41892]
We use signalR package in our application which internally references eventsource version 1.0.7.
We have the below security vulnerability reported for this version asking us to upgrade to 2.0.2

_When fetching an url with a link to an external site (Redirect), the users Cookies & Autorisation headers are leaked to the third party application. According to the same-origin-policy, the header should be "sanitized."_

We noticed that even the latest signalR version 6.0.5 still doesnt upgrade the eventsource package version.

Could you please advise how we can go about this?

**Comment by blowdart** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/41829, https://github.com/dotnet/aspnetcore/issues/41813, https://github.com/dotnet/aspnetcore/issues/41729, https://github.com/dotnet/aspnetcore/issues/41728

Fixing in https://github.com/dotnet/aspnetcore/pull/41270
