### ISSUE TITLE
Add HttpContext ot ITicketStore methods (CookieAuthenticationHandler)

### ISSUE THREAD

**Issue by vanbukin** [dotnet/aspnetcore#41907]
## Summary
Current [ITicketStore](https://github.com/dotnet/aspnetcore/blob/v7.0.0-preview.4.22251.1/src/Security/Authentication/Cookies/src/ITicketStore.cs) interface didn’t have any methods that provides access to HttpContext

## Motivation and goals

If I try to use any scoped service in my ITicketStore implementation, then I have two options:
- Inject the IServiceScopeFactory, create scope that separated from a current request's scope and then resolve and use any scoped service there
- Inject IHttpContextAccessor, that holds HttpContext in [AsyncLocal](https://github.com/dotnet/aspnetcore/blob/v7.0.0-preview.4.22251.1/src/Http/Http/src/HttpContextAccessor.cs#L11) and then resolve scoped service from there

## In scope

It will improves developer experience in scenarios when storage is implemented by the scoped service ([EF DbContext](https://github.com/dotnet/efcore/blob/v7.0.0-preview.4.22229.2/src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L564-L605) for example, and [comment](https://github.com/dotnet/aspnetcore/issues/6946#issuecomment-461672976) in another ITicketStore issue).

## Risks / unknowns

There is no risks. ITicketStore [already have methods](https://github.com/dotnet/aspnetcore/blob/v7.0.0-preview.4.22251.1/src/Security/Authentication/Cookies/src/ITicketStore.cs#L26), that accepts cancellation tokens, and default interface implementation is just calls an overload without cancellation tokens. Methods that accepts HttpContext can be safely added in a same way. That will help to avoid any breaking changes.
The only place when the ITicketStore is called is [CookieAuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs), and all callers has access to HttpContext and can pass it to ITicketStore.

## Examples

Proposed API
```csharp
namespace Microsoft.AspNetCore.Authentication.Cookies;

public interface ITicketStore
{
    Task<string> StoreAsync(AuthenticationTicket ticket);
    Task<string> StoreAsync(AuthenticationTicket ticket, CancellationToken cancellationToken) => StoreAsync(ticket);
    Task<string> StoreAsync(HttpContext httpContext, AuthenticationTicket ticket, CancellationToken cancellationToken) => StoreAsync(ticket, cancellationToken);
    Task RenewAsync(string key, AuthenticationTicket ticket);
    Task RenewAsync(string key, AuthenticationTicket ticket, CancellationToken cancellationToken) => RenewAsync(key, ticket);
    Task RenewAsync(HttpContext httpContext, string key, AuthenticationTicket ticket, CancellationToken cancellationToken) => RenewAsync(key, ticket, cancellationToken);
    Task<AuthenticationTicket?> RetrieveAsync(string key);
    Task<AuthenticationTicket?> RetrieveAsync(string key, CancellationToken cancellationToken) => RetrieveAsync(key);
    Task<AuthenticationTicket?> RetrieveAsync(HttpContext httpContext, string key, CancellationToken cancellationToken) => RetrieveAsync(key, cancellationToken);
    Task RemoveAsync(string key);
    Task RemoveAsync(string key, CancellationToken cancellationToken) => RemoveAsync(key);
    Task RemoveAsync(HttpContext httpContext, string key, CancellationToken cancellationToken) => RemoveAsync(key, cancellationToken);
}
```

**Comment by davidfowl** [comment]
@vanbukin This should use the API proposal template.

**Comment by vanbukin** [comment]
@davidfowl re-open with API proposal template #41908
