### ISSUE TITLE
Consider adding Text overloads to support UTF8 text

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#41919]
## Background and Motivation

We've added the utf8 text literals to C# 11 and it would be nice to add some convenience helpers for producing results with utf8 string content.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public static class Results
{
+    public static IResult Text(ReadOnlySpan<byte> utf8Content, string? contentType = null, Encoding? contentEncoding = null, int? statusCode = null) 
}

public static class TypedResults
{
+    public static ContentHttpResult Text(ReadOnlySpan<byte> utf8Content, string? contentType = null, Encoding? contentEncoding = null, int? statusCode = null);
}
```

## Usage Examples

```C#
// UTF8 literals
app.MapGet("/utf8-0", () => Results.Text("Hello World"u8));
app.MapGet("/utf8-1", () => TypedResults.Text("Hello World"u8));

// UTF8 Memory<byte>, not the most efficient by yah
var utf8FileBuffer = File.ReadAllBytes("/utf8Files/utf8file1.txt");

// Response with the first 30 bytes
app.MapGet("/u8-5", () => Results.Text(utf8FileBuffer[..30]));
```

## Risks

None

**Comment by gfoidl** [comment]
Does
```c#
ReadOnlyMemory<byte> foo = "foo"u8;
```
work without intermediate `byte[]`-allocation?
For ROS<byte> it works as expected, but I'm not aware that the same works for ROM<byte> (which doesn't mean that latest discussion around that topic includes support for ROM too, of course).

**Comment by davidfowl** [comment]
I believe that allocates but @stephentoub would know.

**Comment by stephentoub** [comment]
That won't compile as of the latest language design and compiler version. You'd need to write:
```C#
ReadOnlyMemory<byte> foo = "foo"u8.ToArray();
```
which does of course allocate. The code you wrote with the existing compiler allocates as well.

**Comment by davidfowl** [comment]
Hmm I need to get an updated compiler..

**Comment by halter73** [comment]
API review notes:

- @stephentoub Is there type for UTF8 literals like "foo"u8 other than `ReadOnlyMemory<byte>` that would allow us to directly take it as a parameter with `.ToArray()`?
- Let's wait on approval until we can test with new language version.

**Comment by stephentoub** [comment]
> Is there type for UTF8 literals like "foo"u8 other than ReadOnlyMemory<byte> that would allow us to directly take it as a parameter with .ToArray()?

The natural type of "..."u8 is `ReadOnlySpan<byte>`.  There are no other types it implicitly or explicitly target types.

**Comment by halter73** [comment]
If we're going to have to copy either way which it seems like we will because there's no way for the developer returning `Results.Text(...)` to know when they can reclaim pooled memory, maybe we should just take `ReadOnlySpan<byte>`.

**Comment by davidfowl** [comment]
@halter73 Sure.

**Comment by Tarun047** [comment]
Hi Guys, 
I'd like to take this one up, if it's available, 
As this my first time around here, I'm not sure if it's okay to create a PR directly.
I'm thinking this is the change to be done to 
aspnetcore/src/Http/Http.Results/src/TypedResults.cs:
<img width="1132" alt="Screenshot 2022-06-18 at 11 23 38 AM" src="https://user-images.githubusercontent.com/32017154/174425012-b9af5736-f39d-4cc4-bba3-181bf175283e.png">

And for aspnetcore/src/Http/Http.Results/src/Results.cs:
```cs
public static IResult Text(ReadOnlySpan<byte> utf8Content, string? contentType = null, Encoding? contentEncoding = null, int? statusCode = null) => TypedResults.Text(utf8Content, contentType, contentEncoding, statusCode);

**Comment by davidfowl** [comment]
Almost. We don't want to convert to a String here. 

@halter73 We missed an API (my bad) there should also be a new `Utf8ContentHttpResult` that we create as part of this:

```C#
public sealed partial class Utf8ContentHttpResult : IResult
{
    public Memory<byte> ResponseContent { get; internal init; }

    public string? ContentType { get; internal init; }

    public int? StatusCode { get; internal init; }

    public Task ExecuteAsync(HttpContext httpContext);
}
```

**Comment by davidfowl** [comment]
Made a few changes to the API:
- Removed the content encoding, these are UTF8 APIs
- Added Utf8ContentHttpResult 

```diff
namespace Microsoft.AspNetCore.Http;

public static class Results
{
+    public static IResult Text(ReadOnlySpan<byte> utf8Content, string? contentType = null, int? statusCode = null) 
}

public static class TypedResults
{
+    public static ContentHttpResult Text(ReadOnlySpan<byte> utf8Content, string? contentType = null, int? statusCode = null);
}

+public sealed partial class Utf8ContentHttpResult : IResult
+{
+   public Memory<byte> ResponseContent { get; internal init; }
+
+    public string? ContentType { get; internal init; }
+
+    public int? StatusCode { get; internal init; }
+
+    public Task ExecuteAsync(HttpContext httpContext);
+}
```

**Comment by davidfowl** [comment]
@Tarun047 my bad, I forgot you wanted to do this one 😞

**Comment by Tarun047** [comment]
No worries @davidfowl 😀

**Comment by BrennanConroy** [comment]
`Utf8ContentHttpResult` should also implement `IContentHttpResult`

**Comment by davidfowl** [comment]
OK now it matches what ContentHttpResult would have.

**Comment by halter73** [comment]
I think I see why. Should we make `IStatusCodeHttpResult.StatusCode` nullable instead?

**Comment by brunolins16** [comment]
> I think I see why. Should we make IStatusCodeHttpResult.StatusCode nullable instead?

In my opinion, I don't think we should because the only reason for `IStatusCodeHttpResult` is to describe a `HttpResult` that contains a `StatusCode`. 

I did not want to change it in my PR but, in my opinion, `ContentHttpResult`, `JsonHttpResult` and `Utf8ContentHttpResult` should be changed to non-nullable `StatusCode` and explicitly set a default value (`HTTP 200 OK`) avoiding relying on the underlying behavior (similar issue happened in MVC https://github.com/dotnet/aspnetcore/issues/27165).

**Comment by halter73** [comment]
> in my opinion, `ContentHttpResult`, `JsonHttpResult` and `Utf8ContentHttpResult` should be changed to non-nullable StatusCode and explicitly set a default value (HTTP 200 OK) avoiding relying on the underlying behavior

I think there's a big difference between a result that always sets a 200 OK result vs a result that just skips setting the status code. Certain result types like `Utf8ContentHttpResult` can do either based on its state. I think that's why it's important that `IStatusCodeHttpResult.StatusCode` can take distinct values (200 and null respectively in this case) for when a status code is set vs when it's skipped.

**Comment by davidfowl** [comment]
Did we close on this? Should it be nullable or not?
