### ISSUE TITLE
SignalR Client Javascript contains dependency of eventsource which contains Critical vulnerability

### ISSUE THREAD

**Issue by pauljnovak** [dotnet/aspnetcore#41933]
after executing yarn audit report says 

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Exposure of Sensitive Information in eventsource             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ eventsource                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path        | @microsoft/signalr > eventsource                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070403                     │
└───────────────┴────────────────────────────────────────────────────────────── 
please upgrade this dependency

**Comment by dchennaraidu** [comment]
Dup: https://github.com/dotnet/aspnetcore/pull/41270
