### ISSUE TITLE
JSRuntime "open" with "_blank" throws TaskCanceledException 60 seconds later

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#41934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking a button that calls the following results in a TaskCanceledException about 60 seconds later.

```c#
await JSRuntime.InvokeAsync<string>("open", $"https://www.microsoft.com", "_blank");
```

### Expected Behavior

No TaskCanceledException is thrown

### Steps To Reproduce

1. Run the project (tested with `dotnet run` and VS Mac (ARM)) in Safari or Firefox on macOS
2. Click a button that calls the following: `await JSRuntime.InvokeAsync<string>("open", $"https://www.microsoft.com", "_blank");` via an `@onclick` method
3. Notice in the exception in the browser console (and in VS Mac (ARM) as well if started there)

### Exceptions (if any)

browser console error:
> Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)

VS Mac (ARM) error:
> Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll

### .NET Version

6.0.300

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by mrlife** [comment]
Hi @javiercn, thanks for getting back in touch. Note that after clicking the button to open the new tab, I don't do anything else, just wait about 60 seconds.

I listed a browser console error above, but didn't include all of it since it had some personal information. Here is it is in full (redacted):

> Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at MyProject.MyRazorComponent.MyMethod(MouseEventArgs mouseEventArgs) in /Users/MyUserName/MyProject/MyRazorComponent.razor:line 42
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

**Comment by javiercn** [comment]
@mrlife that's what I figured.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like you should use `InvokeVoidAsync` instead to avoid this error.
We're also looking at improving this experience by a PR which will be linked shortly.

**Comment by mkArtakMSFT** [comment]
https://github.com/dotnet/aspnetcore/pull/41916

**Comment by SteveSandersonMS** [comment]
BTW the error message should get clearer when https://github.com/dotnet/aspnetcore/pull/41916 is merged
