### ISSUE TITLE
Skipped: ProjectTemplates tests on Windows

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#41937]
Some of the ProjectTemplates tests are failing in Helix on Windows platforms. See: https://dev.azure.com/dnceng/public/_build/results?buildId=1793028&view=ms.vss-test-web.build-test-results-tab.

Tests are failing with variations of the following error message: `Expected <something> to have status 'OK' but it was 'NotFound'.`

It's possible this is caused by the `ASPNETCORE_ENVIRONMENT` variable not getting set correctly. One of the failing tests is `Microsoft.AspNetCore.Mvc.FunctionalTests.SimpleWithWebApplicationBuilderTests.DefaultEnvironment_Is_Development`, and the logs of the failing tests list `Hosting environment: Production` even though `ASPNETCORE_ENVIRONMENT` should be getting set explicitly to `Development` in those tests: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-41573-merge-2d1b8917cccd4614ab/ProjectTemplates.Tests--net7.0/1/console.b5f7596f.log?helixlogtype=result

https://github.com/dotnet/aspnetcore/pull/41936

**Comment by dougbu** [comment]
Do we have a way to mark this as having a high priority @adityamandaleeka @rafikiassumani-msft @mkArtakMSFT❔ We're losing a fair amount of project template coverage atm.

**Comment by javiercn** [comment]
@MackinnonBuck not sure what's going on here, the tests setup the environment [here](https://github.com/dotnet/aspnetcore/blob/d02dca7d2285090888fa18bd7789c94504c97191/src/ProjectTemplates/Shared/Project.cs#L182)

**Comment by dougbu** [comment]
- [ ] #42139
- [ ] #42140

**Comment by dougbu** [comment]
/fyi I'm taking this because I have what appear to be workaround PRs open
