### ISSUE TITLE
.net 7 preview 4 Using mudblazor 6.0.10

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/aspnetcore#41932]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When i migrate my project from .net 6 to .net 7 preview 4 i have issue With EventHandlers:
The attribute 'onmouseenter' was matched by multiple event handler attributes. Duplicates:
Mudblazor.EventHandlers
Microsoft.AspNetCore.Components.Web.EventHandlers

**Comment by MariovanZeist** [comment]
Hi @sajjadarashhh 
MudBlazor is not a project maintained by Microsoft.
I think you will get a better response on the MudBlazor GitHub page: https://github.com/MudBlazor/MudBlazor/issues

**Comment by sajjadarashhh** [comment]
@MariovanZeist But this issue must be solved in .net
i seen the same issue like this in another projects that themselves create eventHandlers for onmouseenter and onmouseleave
and what happend when developers wana to use custom event handlers in their repositories for that events!? :D

**Comment by javiercn** [comment]
@sajjadarashhh thanks for contacting us.

Can you provide a minimal repro project that ilustrates the issue?

**Comment by sajjadarashhh** [comment]
@javiercn  https://github.com/sajjadarashhh/Test.net7/tree/main/MultipleEventHandlers

**Comment by sajjadarashhh** [comment]
Thanks to .net team to cover this but iwana to solve this and contribute myself to make solution to this problem
i can!?
@mkArtakMSFT

**Comment by SteveSandersonMS** [comment]
Reported at https://github.com/MudBlazor/MudBlazor/issues/4951. Closing this issue as external.

**Comment by mckaragoz** [comment]
I'm not a spokesperson but MudBlazor doesn't have 7.x.preview yet. This was the case for .net 6, MudBlazor 6.x releases appeared on the day .net 6 was officially released. So I don't think there is any guarantee at this time for this or any other possible net 7 changes.
