### ISSUE TITLE
Add ValueTask overloads to EventCallBack<T>

### ISSUE THREAD

**Issue by jessegood** [dotnet/aspnetcore#41946]
## Background and Motivation
Seems to me an oversight that ValueTask is not supported as an EventCallBack

## Proposed API
```
public EventCallback Create(object receiver, Func<ValueTask> callback)
public EventCallback Create(object receiver, Func<object, ValueTask> callback)
public EventCallback<TValue> Create<TValue>(object receiver, Func<ValueTask> callback)
public EventCallback<TValue> Create<TValue>(object receiver, Func<TValue, ValueTask> callback)
```

## Usage Examples
The use case for this would mainly be JavaScript Interop:

```
<button @onclick=ClickMe>Click Me</button>

@code {
    private ValueTask ClickMe()
    {
        return JSRuntime.InvokeVoidAsync("alert", "You clicked me");
    }
}
```

## Alternative Designs
None

## Risks
I don't see any risks, but let me know.

**Comment by soenneker** [comment]
Pretty routinely wish this was supported; it's no fun wrapping ValueTask methods with lambdas.

**Comment by sake402** [comment]
These extension methods resolve this issue for the time being
```
        public static EventCallback Create(this EventCallbackFactory factory, object receiver, Func<ValueTask> callback)
        {
            return factory.Create(receiver, () => callback().AsTask());
        }

        public static EventCallback<T> Create<T>(this EventCallbackFactory factory, object receiver, Func<T, ValueTask> callback)
        {
            return factory.Create<T>(receiver, (t) => callback(t).AsTask());
        }
        
        public static EventCallback<T> Create<T>(this EventCallbackFactory factory, object receiver, Func<ValueTask> callback)
        {
            return factory.Create<T>(receiver, () => callback().AsTask());
        }

```

**Comment by jamesquox** [comment]
Thanks for the code @sake402 
Looking at the underlying EventCallbackFactory I've amended your code to new up a EventCallback - seems to work for me.
`#pragma warning disable IDE0130
namespace Microsoft.AspNetCore.Components;

/// <summary>
/// Remove when EventCallback is able to handle ValueTask
/// https://github.com/dotnet/aspnetcore/issues/41946
/// </summary>
public static class EventCallbackFactoryExtension
{
    /// <summary>
    /// Creates an <see cref="EventCallback"/> for the provided <paramref name="receiver"/> and
    /// <paramref name="callback"/>.
    /// </summary>
    /// <param name="receiver">The event receiver.</param>
    /// <param name="callback">The event callback.</param>
    /// <returns>The <see cref="EventCallback"/>.</returns>
    public static EventCallback Create(this EventCallbackFactory _, object receiver, Func<ValueTask> callback)
    {
        return CreateCore(receiver, callback);
    }

    /// <summary>
    /// Creates an <see cref="EventCallback"/> for the provided <paramref name="receiver"/> and
    /// <paramref name="callback"/>.
    /// </summary>
    /// <param name="receiver">The event receiver.</param>
    /// <param name="callback">The event callback.</param>
    /// <returns>The <see cref="EventCallback"/>.</returns>
    public static EventCallback<TValue> Create<TValue>(this EventCallbackFactory _, object receiver, Func<ValueTask> callback)
    {
        return CreateCore<TValue>(receiver, callback);
    }

    /// <summary>
    /// Creates an <see cref="EventCallback"/> for the provided <paramref name="receiver"/> and
    /// <paramref name="callback"/>.
    /// </summary>
    /// <param name="receiver">The event receiver.</param>
    /// <param name="callback">The event callback.</param>
    /// <returns>The <see cref="EventCallback"/>.</returns>
    public static EventCallback<TValue> Create<TValue>(this EventCallbackFactory _, object receiver, Func<TValue, ValueTask> callback)
    {
        return CreateCore<TValue>(receiver, callback);
    }

    /// <summary>
    /// Taken from <see cref="EventCallbackFactory"/>
    /// </summary>
    private static EventCallback CreateCore(object receiver, MulticastDelegate callback)
    {
        return new EventCallback(callback?.Target as IHandleEvent ?? receiver as IHandleEvent, callback);
    }

    /// <summary>
    /// Taken from <see cref="EventCallbackFactory"/>
    /// </summary>
    private static EventCallback<TValue> CreateCore<TValue>(object receiver, MulticastDelegate callback)
    {
        return new EventCallback<TValue>(callback?.Target as IHandleEvent ?? receiver as IHandleEvent, callback);
    }
}`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
