### ISSUE TITLE
SupplyParameterFromQuery should work in (non routable) components and two-way

### ISSUE THREAD

**Issue by gingters** [dotnet/aspnetcore#41963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'd like to build a deep-linkable tabbed control.
The requirement is to be able to deep-link into the Blazor application with the correct tab selected.
For that, the selected tab index of the (non-routable!) component should be set through a query string parameter.
Also, any changes on the parameter should be reflected in the current url (two-way binding).

The current workaround would be:
```
public partial class DeepLinkableComponent: ComponentBase
{
    [Parameter]
    public Guid DataId { get; set; }
    
    private int selectedTab = 0;

    [Inject]
    private NavigationManager? _navigationManager { get; set; }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        // From Query (because [Parameter, SupplyParameterFromQuery(Name = "XX")] does not work in components)
        var query = HttpUtility.ParseQueryString(new Uri(_navigationManager.Uri).Query);
        var queryParameter = query["selectedTab"];
        int.TryParse(queryParameter, out selectedTab);
    }

    private void OnSelectionChanged(int newIndex)
    {
        // Modify local state
        selectedTab = newIndex;

        // Persist change in URI (to be able to be copied / deeplinked)
        var newUri = _navigationManager.GetUriWithQueryParameter("selectedTab", newIndex);
        _navigationManager.NavigateTo(newUri);
    }
}
```

### Describe the solution you'd like

Ideally, the code would look like this:

```
public partial class DeepLinkableComponent: ComponentBase
{
    [Parameter]
    public Guid DataId { get; set; }

    [Parameter, SupplyParameterFromQuery(Name = "tab")]   
    private int SelectedTab {get; set;} = 0;
}
```

Now I would two-way bind the `SelectedTab` property to the index property of the tab component (i.e. MudBlazors MudTab) used in my component.

The user can select a tab, the new tab index will be automatically reflected in the Url, and the user can copy the url, send it to another user and the other user can open the page and the tab component will automatically preselect the correct tab.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestions.

We did consider all these possibilities when first designing the querystring support, and came to the current design based on lots of considerations and tradeoffs. You can read more about the design process and tradeoffs at https://github.com/dotnet/aspnetcore/issues/33338, including specific discussions about the idea of "two way" binding and how that can best be achieved.

I'll leave this open on backlog in case people want to comment further, but we're not specifically planning changes here as there are already decent solutions and there are a lot of tradeoffs involved in making this work well as a whole.

**Comment by MackinnonBuck** [comment]
Closing this out since there hasn't been any community activityon this issue.
