### ISSUE TITLE
user-jwts should just create the UserSecretsId if not found

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#41975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `dotnet user-jwts create` if there is no UserSecretsId it will fail saying one is not found.  We should either:

- (Preferred) Generate the UserSecretsId for the user...this is non-impacting for the code and creates a delighter to complete the task fully that I asked it to do (show in output 'user secrets not found, generated [guid]' before adding the newly created token
- Clarify what to do in the event UserSecretsId is not there (IMO, not an awesome experience to use a separate tool)		

https://github.com/dotnet/aspnetcore/pull/41956#discussion_r886980367

### Expected Behavior

The token is just created for me, doing what is needed to create the secrets/file association if not found.

**Comment by adityamandaleeka** [comment]
@captainsafia, assigning this to you since it's follow-up from the user-jwts work.
