### ISSUE TITLE
Add support for specifying a launch profile to `dotnet watch run`

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#41988]
As part of [[EPIC] Revisiting HTTPS defaults in ASP.NET Core](https://github.com/dotnet/aspnetcore/issues/41990)

ASP.NET Core projects are being updated to have multiple launch profiles by default. As such, we'd like it to be easier to select a launch profile when running the project using `dotnet watch`/`dotnet watch run`.

We propose supporting `-lp` as an option alias for `--launch-profile`, e.g.:

```
$ dotnet watch -lp https
```

Matching issue for `dotnet run`: dotnet/sdk#25770

**Comment by TanayParikh** [comment]
Is this related to https://github.com/dotnet/aspnetcore/issues/38408 in any way?

**Comment by DamianEdwards** [comment]
Not directly, I think, but the existing logic within `dotnet watch` to select the launch profile it uses may well have some determinism issues.
