### ISSUE TITLE
browserlink CSP support .NET 7 

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#42007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Would it be possible to implement the **browserlink** debugging function in such a way so that I do not need to disable my CSP in local development? The closer the development system is to the production, the less surprises you have. 

If it was possible to use the CSP nonce or a hash, I would not need to disable the CSP then. 

**Feature request:** could you implement the browserlink to support a good CSP?

Actual Error: (7.0.0-preview.4.22251.1)

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-tVFibyLEbUGj+pO/ZSi96c01jJCvzWilvI5Th+wLeGE='), or a nonce ('nonce-...') is required to enable inline execution.  https://localhost:44348/_vs/browserLink

Sample repo:

https://github.com/damienbod/BlazorNet7

### Describe the solution you'd like

develop with CSP active.

**Comment by javiercn** [comment]
@damienbod thanks for contacting us.

Could you report this issue through the report a problem dialog in Visual Studio? I'll route this to the appropriate folks, but that will likely give you a better and faster answer.

/cc @jodavis FYI

**Comment by damienbod** [comment]
VS issue: 

https://developercommunity.visualstudio.com/t/browserlink-CSP-support-NET-7/10061464?entry=problem

**Comment by jodavis** [comment]
Thank you, @damienbod, we will follow up on the VS issue from here.
