### ISSUE TITLE
DistributedSession always loads session in CommitAsync even when session is not modified

### ISSUE THREAD

**Issue by michalsznajder** [dotnet/aspnetcore#42009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As part of https://github.com/dotnet/aspnetcore/pull/26098/commits/f99b482fe0ac72958d7bc5ed88e956fb62971c09 code is `DistributedSession.CommitsAsync` was modified to check `IsAvailable`. 

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L263

`IsAvailable` always loads session from backing store and loads it in synchronous way.
https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L96

On the other hand `SessionMiddleware` always calls `DistributedSession.CommitAsync` to save session. This means that in 6.0 session is **always loaded** even if application code did not touch it at all. In case of using Redis as backing store this incurs two Redis calls on each RazorPage rendered.  

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/SessionMiddleware.cs#L119

In the past (5.0) when session was not touched `DistributedSession._isModified` prevented session data from being loaded when session was not modified.

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L274

@pranavkm Could you tell why `IsAvailable` was moved?

### Expected Behavior

Don't loading session data from backing store when session data is not modified by app code.

### .NET Version

6.0.300

**Comment by adityamandaleeka** [comment]
Reopening for 6.0 servicing consideration. The performance impact of this is meaningfully affecting people (e.g. https://github.com/dotnet/aspnetcore/pull/43059#issuecomment-1272696654)

**Comment by adityamandaleeka** [comment]
This was fixed in 6.0 servicing in this PR: https://github.com/dotnet/aspnetcore/pull/44610
