### ISSUE TITLE
Microsoft Dev Box integration with dotnet/aspnetcore

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#42004]
The [Microsoft Dev Box](https://techcommunity.microsoft.com/t5/azure-developer-community-blog/introducing-microsoft-dev-box/ba-p/3412063) was recently announced. 

> Dev teams preconfigure Dev Boxes for specific projects and tasks, enabling devs to get started quickly with an environment that’s ready to build and run their app in minutes.  

This issue tracks setting up the `dotnet/aspnetcore` repo within a [devbox environment](https://devbox.microsoft.com/), potentially with a rolling nightly build.

**Comment by ShreyasJejurkar** [comment]
Signed up for the preview! Can't wait to build aspnetcore repo on it!. 😅😂
