### ISSUE TITLE
Enable CA1854 analyser

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#42008]
I spotted a new analyser being dogfooded in https://github.com/dotnet/runtime/pull/70157 that suggests using `TryGetValue()` on dictionaries over `ContainsKey()` & the indexer.

I've spotted a few uses of the latter pattern in the repo from time to time, so it would be good to enable that analyser and fix-up any warnings from it once the relevant change has been ingested into this repo.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @martincostello.
@dotnet/aspnet-api-review crew, any objections to enabling this analyzer on the repo?
/cc @adityamandaleeka, @rafikiassumani-msft, @captainsafia, @JamesNK, @javiercn

Please use the voting reactions on this issue to indicate your preference:
- 👍 - supportive
- 👎  - not supportive

**Comment by BrennanConroy** [comment]
This was done in https://github.com/dotnet/aspnetcore/pull/44799
