### ISSUE TITLE
Remove explicit parameterName from calls to ArgumentNullException.ThrowIfNull where it can be inferred via the CallerMemberNameAttribute

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#42018]
There's a number of places in the code base where `ArgumentNullException.ThrowIfNull(object? argument, string paramName)` is called explicitly. The RegEx `ArgumentNullException\.ThrowIfNull\(\w+,` can be used to locate them (see image below).

The second argument can be omitted in cases where the parameter is passed directly as the first argument, as the method uses `CallerMemberNameAttribute` to get that name automatically at compile time.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/249088/171925199-0ef9d415-dfd9-48fd-9abe-720cd60d01ab.png">

**Comment by Pilchie** [comment]
Not exactly infrastructure, but cross-cutting enough that nothing else really fits either.
