### ISSUE TITLE
Logging intermittently stops until website is recycled.

### ISSUE THREAD

**Issue by JeanJeanDijon** [dotnet/aspnetcore#42017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As per the title, logging randomly stops.

Website is built with .NET Core 3.1, running AspNetCoreModuleV2 modules and InProcess hosting. The process is running on two servers in parallel for high availability and load balancing. In spite of that, it is not a high traffic website with say more than twenty users at a time.

We are using a configuration that supports an absolute, network path, and a shared log.
![image](https://user-images.githubusercontent.com/56313421/171907903-52246f78-f8b0-4a5b-97a9-ace4dbe4107c.png)

We create the logger in our Startup.cs, ConfigureServices(IServiceCollection services).
![image](https://user-images.githubusercontent.com/56313421/171908197-2cb4db62-fd7d-496c-9864-468a2b0fc5e4.png)

We handle the the application stopping when IIS detects the website is idle and close and flush the log.
![image](https://user-images.githubusercontent.com/56313421/171909267-ee60f48a-4260-41e2-9c09-e989203ee567.png)

So because we are sharing the log between two processes, we will see each Log.CloseAndFlush() followed by a CreateLogger() in our logs. However, from 09:42 until 14:51, when we manually recycled our website, there was no logging. The curious thing I notice is that there is one more CreateLogger() than Log.CloseAndFlush(), almost like we missed closing and flushing the log from one of the processers some time before we stopped logging.
![image](https://user-images.githubusercontent.com/56313421/171909569-23107464-b829-45ac-bb7a-9b6bf9664588.png)

I'd be grateful for any help please. Thanks very much.

### Expected Behavior

Logging to be continuous without interruption.

### .NET Version

.Net Core 3.1

**Comment by Tratcher** [comment]
Try wiring up Serilog as recommend here: https://github.com/serilog/serilog-aspnetcore. Then you don't have to manually close the log, the DI container should take care of it on shutdown.
