### ISSUE TITLE
SignalR: Distributed HubConnectionStore 

### ISSUE THREAD

**Issue by evman182** [dotnet/aspnetcore#42011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The dependency on the HubConnectionStore and its use of an in-memory dictionary as it's data store means that any load balanced SignalR endpoints must use sticky sessions, which in certain environments can be difficult to setup.

### Describe the solution you'd like

I'd like to see a configurable option for the HubConnectionStore, allowing the use of a plugin-able distributed store, such as Redis.

### Additional context

I'm willing to work on this myself, but am wondering if there's a technical reason that the connection store has been limited to just an in-memory option so far.

**Comment by evman182** [comment]
@DamianEdwards My understanding is the Redis backplane allows distribution for the messages, but that the connections themselves are still stored in-memory on the server.

**Comment by DamianEdwards** [comment]
Ah OK, misunderstood. RE connection state my understanding is we've long avoided making that pluggable due to the complexities that can arise once it's not a synchronous/atomic in-memory operation, e.g. interactions with downstream APIs that aren't async. Fundamentally the system is designed around the idea of events/messages rather than state, but I completely understand the motivation for the request.

All that said, I'm not sure about the latest state of the world here. I know there's been recent thinking about the idea of using something like Orleans to implement distributed versions of some of the backing primitives. @davidfowl?

**Comment by davidfowl** [comment]
We don't have any plans to write a distributed `HubConnectionStore` , it's a simple data structure to aid in writing your a backplane. Why not just use something like entity framework or orleans to build distributed storage?

**Comment by evman182** [comment]
I just wanted to make sure there wasn't a reason that the connection store couldn't be distributed before going down that path.

**Comment by davidfowl** [comment]
Can you elaborate on the scenario? What are you trying to implement?

**Comment by evman182** [comment]
For the moment we're not able to use websockets, and we're relying on HTTP polling, and so yea, the issue is during the negotiation handshake.

**Comment by davidfowl** [comment]
And your environment doesn't support sticky sessions?

**Comment by evman182** [comment]
Short answer: no it doesn't

**Comment by davidfowl** [comment]
Got it, SignalR can't work with long polling or server sent events without sticky sessions.

**Comment by evman182** [comment]
I understand that long polling doesn't currently work without sticky sessions. What I'm wondering is if there's any technical reason that it has to be that way (other than that it's a constraint of the current implementation).

**Comment by davidfowl** [comment]
Yes we made a architectural decision to treat the any connection like a persistent socket and to avoid baking in the idea of a backplane or distribute storage at this layer for performance reasons.

The virtual connection abstraction must act like a stream from a single source. 

I’m theory you could build a new transport layer that routes bytes to the right server no matter where the request lands using various technologies, but it would be inefficient and less reliable than a direct connection.

This isn’t something we would build but if you wanted some pointers on how to do so, we could help.

**Comment by davidfowl** [comment]
Actually I just remembered the other reason why this is so hard, connection lifetime management. If the connection can exists across multiple servers, it's more difficult to know when it's disconnected. This is the other reason we didn't do this.

ASP.NET Core SignalR is split into 2 distinct protocols:
- The transport protocol - https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md
- The hub protocol - https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/HubProtocol.md

They are separate so the hub protocol can be expressed on top of any streaming transport. 

In your environment, can the nodes talk to each other?
