### ISSUE TITLE
Use ToString() of bool instead of normal boolean strings in HostingAbstractionsWebHostBuilderExtensions

### ISSUE THREAD

**Issue by ArminShoeibi** [dotnet/aspnetcore#42020]
## Summary

Hello there folks.
I think we can use bool.TrueString and bool.FalseString instead of actual strings of boolean in the HostingAbstractionsWebHostBuilderExtensions class
https://github.com/dotnet/aspnetcore/blob/d96a100bddc72606f7417b665428411388b8ac54/src/Hosting/Abstractions/src/HostingAbstractionsWebHostBuilderExtensions.cs#L43

https://github.com/dotnet/aspnetcore/blob/d96a100bddc72606f7417b665428411388b8ac54/src/Hosting/Abstractions/src/HostingAbstractionsWebHostBuilderExtensions.cs#L159

https://github.com/dotnet/aspnetcore/blob/d96a100bddc72606f7417b665428411388b8ac54/src/Hosting/Abstractions/src/HostingAbstractionsWebHostBuilderExtensions.cs#L170

## Motivation and goals

We can reduce magic strings.
We can Find references to those static fields easily.
We can reuse those fields.

## In scope
-

## Out of scope

-

## Risks / unknowns

I think there isn't any risks about this change.

## Examples
-
Please let me know and I will create a PR. Thanks

**Comment by ArminShoeibi** [comment]
for example we can do this:
`
return hostBuilder.UseSetting(WebHostDefaults.CaptureStartupErrorsKey, captureStartupErrors.ToString()); 
`

**Comment by ArminShoeibi** [comment]
![image](https://user-images.githubusercontent.com/68565441/171968000-b98fbea5-5341-4bea-bbda-2898d6b8da11.png)

**Comment by ArminShoeibi** [comment]
Can we benefit from GetValue<T> for these value types instead of that local function " string? GetConfig(string key)" ?
https://github.com/dotnet/aspnetcore/blob/2323644cf6e4562d40fd25b37f66576cf11cf280/src/Hosting/Hosting/src/Internal/WebHostOptions.cs#L30

**Comment by adityamandaleeka** [comment]
@ArminShoeibi is there a reason why you see this as valuable? The impact of this seems really small to be worth changing.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi is there a reason why you see this as valuable? The impact of this seems really small to be worth changing.

It is not really a big thing as much as other things, but I think we can Improve this section.

**Comment by BrennanConroy** [comment]
Triage: We think this is low value and not worth tracking.
