### ISSUE TITLE
Stackable Pages i.e. Multiple Pages on Top of Each Other Like MdiContainer In Winform

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/aspnetcore#42041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

wanted to develop erp-solution in blazor.
but we required **multiple pages to open on top of each-other i.e. z-ordered stackable pages**.
how to do so ?
this feature is **must for erp-level-projects**.

### Describe the solution you'd like

like **mdi container in winform**, windows should be stackable within.
we have tried third party library like winbox.js, mdiware.js etc but not fit as much as we required.
thus, we believe this feature **should come built in with blazor itself**.

we think @Body should handle these things for us.
or whatever you experts think will be better.

**Comment by javiercn** [comment]
@hintsofttech thanks for contacting us.

In general that's not how pages on the web works. If you want page stacking similar to what you might find in some native platforms, that is something you need to build yourself or use a third-party component for. It is not something that we plan to provide outside of the box nor something we plan to implement in the near future.
