### ISSUE TITLE
Custom Server Sent Event in ASPNET Core

### ISSUE THREAD

**Issue by cpc-chukka** [dotnet/aspnetcore#42058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Created a server sent event with asp.net core and code word as expected without authorization [event stream created], however with authorization enabled we get a 200 OK but the event stream is not Created.

### Expected Behavior

Server Sent Event without and with Authorization should work as expected. 

### Steps To Reproduce

Public Repo: https://github.com/cpc-chukka/sse-authorize

- Run the project commenting out the authorize attribute [Works as Expected]
- Run the code with the authorize attribute in the weather controller and it doesn't work as expected [we get a 200 OK but no event stream]

Constraints:
Cannot share the audience and issuer information
"JWT": {
    "aud": "",
    "iss": ""
  },

### .NET Version

6.0

### Anything else?

IDE: Visual Studio 2022 - 17.2.3

"Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.5"
 "Microsoft.AspNetCore.Authorization" Version="6.0.5"
 "Newtonsoft.Json" Version="13.0.1" 
  "Swashbuckle.AspNetCore" Version="6.2.3"

**Comment by rafikiassumani-msft** [comment]
@cpc-chukka Triage:  Can you provide a repro of your client code to help us investigate the issue?

**Comment by cpc-chukka** [comment]
@rafikiassumani-msft The code has swagger turned on and we use that to test. It currently fails to create and event stream with swagger turned on when we enable authentication. We are able to call the controller methods with and without authorize, behavior is different.

If you have client code that shows that it is working, can you please share it with us, currently with swagger we can confirm it doesn't work with authorize attribute turned on.

**Comment by BrennanConroy** [comment]
Issue does not repro with your linked app (after fixing compilation errors, and configuring jwt auth).

Without a token the SSE request completes with a 401 and with a token it hangs forever because you use `while(true)`, but commenting that out shows a successful response.

**Comment by BrennanConroy** [comment]
> check if you are looking at the event stream and not just the http response please

What are you saying? There wont be an event stream when auth fails. You get a 401 for the http request.

![image](https://user-images.githubusercontent.com/7574801/174353659-23975f2b-9f60-4134-8945-b380c27ecc3e.png)

**Comment by cpc-chukka** [comment]
> > check if you are looking at the event stream and not just the http response please
> 
> What are you saying? There wont be an event stream when auth fails. You get a 401 for the http request.
> 
> ![image](https://user-images.githubusercontent.com/7574801/174353659-23975f2b-9f60-4134-8945-b380c27ecc3e.png)

When auth succeeds the behavior is not the same, we don't get an event stream, we get a 200 OK instead. There is a difference in behavior when auth is enabled and succeeds vs when auth is not enabled. The difference is that we don't get an event stream. Please let me know if we need to collect additional diagnostics.

**Comment by BrennanConroy** [comment]
This doesn't seem to be an issue with ASP.NET Core. It looks like it's probably a browser issue, you can see a [similar looking bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1025893&q=event-stream&can=2) where you don't get events in the event stream unless you use the `EventSource` class in javascript. But you do still receive the messages and they are being output to the webpage.

**Comment by cpc-chukka** [comment]
We do not receive the messages and they are not output to chrome when we have authorization enabled, we are intentionally not talking about client code using Event Source, if we introduce that discussion it adds additional complexity

**Comment by BrennanConroy** [comment]
> if we can make it work just with swagger that would be great

Can you be super clear about what is and isn't working? Your original issue and screenshot don't mention swashbuckle being part of the issue.

> we are intentionally not talking about client code using Event Source

This should be relevant, otherwise you may be seeing the issue I linked where Chrome doesn't show the EventStream which is exactly what you're complaining about.

**Comment by cpc-chukka** [comment]
> > if we can make it work just with swagger that would be great
> 
> Can you be super clear about what is and isn't working? Your original issue and screenshot don't mention swashbuckle being part of the issue.
> 
> > we are intentionally not talking about client code using Event Source
> 
> This should be relevant, otherwise you may be seeing the issue I linked where Chrome doesn't show the EventStream which is exactly what you're complaining about.

We are unable to see the event stream when we have [Authorize] tag on the controller, we get a 200 response back but no event stream.

If you can share client javascript code that consumes an event stream produced by a web api controller that has the [Authorize] attribute it will be very helpful.

**Comment by BrennanConroy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventSource
```javascript
let eventSource = new EventSource(url);
eventSource.onopen = function() {
  console.log("eventsource started.");
};
eventSource.onmessage = function(e) {
  console.log(e.data);
};
```

Unfortunately browser APIs do not allow setting headers on EventSource so you either need to use query string for auth or cookies.

**Comment by cpc-chukka** [comment]
> 

Can you share sample javascript code to this with either a query string or cookies, we can replace the value with the value of the token,

**Comment by cpc-chukka** [comment]
> A query string is just an addition to the url `(url.indexOf("?") < 0 ? "?" : "&") + 'access_token=token';` But you would need to change your server-side auth code to check for the query string value when parsing the access token.
> 
> Cookies is a server-side concept, you would need to return an cookie from the server and future http calls from the client will contain the cookie.

Is there a way to test the SSE event with security (Authorize header enabled) using the swagger documentation, before adding in client side code. Currently we have 1 challenge SSE with authorize enable is not returning client side data, however if we loop in client side code that interacts with SSE would we be taking an additional challenge of figuring out client side code.

I'm hoping for some of the below resolutions please, your assistance is greatly appreciated

- If possible can we please demonstrate SSE works with the built in authorize attribute [the current repository does not work when we enable authorize attribute] 
- can you please share the client side code that calls the SSE event with authentication (cookies or otherwise) so i can test it

we currently have a local setup of the code repository linked to the issue, we are unable to move ahead. the code as we wrote it does not work. any assistance is greatly appreciated
