### ISSUE TITLE
Exceptions in SignalR streaming results are not reported in the server logs

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/aspnetcore#42050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a streaming method on a SignalR server that does a transformation of received data
```cs
public async IAsyncEnumerable<string> Do()
{
    await foreach(var message in _service.GetMessages())
    {
        yield return Transform(message);
    }
}
```
When `_service.GetMessages()` throws, the exception is not logged anywhere. It's only the client that receives an "An error occured on the server…" message, obviously without any details.

### Expected Behavior

There should be a full error log entry with message, stack trace, etc. as there is when an Web API request fails with an exception.

### Exceptions (if any)

None visible :-/

https://github.com/dotnet/aspnetcore/blob/b806844373440a538192181652d466b621a14494/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L479-L486

### .NET Version

6.0.300

### Anything else?

Currently to get this logged, you have to lower the `await foreach` manually due to C# restrictions (https://github.com/dotnet/csharplang/issues/2949) which gets rather cumbersome, verbose and unmaintainable

**Comment by MikeOnTea** [comment]
Maybe somewhat related, though an own ticket might be better: We tried exception handling/logging with a Hubfilter and faced a similar issue.  A filter around each enumerator invocation of a streaming method to be able to catch exceptions occuring during streaming in a filter would be useful to handle this.
