### ISSUE TITLE
Build the Kestrel.Transport.Sockets nuget package

### ISSUE THREAD

**Issue by qzwzqty** [dotnet/aspnetcore#42067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There are plans to release Kestrel.Transport.Sockets as a separate package to Nuget? Currently there is only one older version of the package on Nuget

### Describe the solution you'd like

I'd like to build my own socket service using Kestrel.Transport.Sockets

**Comment by Tratcher** [comment]
No, we no longer produce packages for assemblies that are part of the core framework. You can reference these assemblies by referencing the framework.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

**Comment by qzwzqty** [comment]
@Tratcher OK, thanks.
 Can set some classes in Kestrel to public, like SocketConnection, TransportManager, etc.

**Comment by davidfowl** [comment]
@qzwzqty No you don't need those to be public. See https://github.com/davidfowl/BedrockFramework.

**Comment by qzwzqty** [comment]
@davidfowl OK, thanks.
