### ISSUE TITLE
Antiforgery token validation failed

### ISSUE THREAD

**Issue by damienmartel2** [dotnet/aspnetcore#42068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I'm developping a Blazor (server) website. The authentication is based on openiddict (oauth) in aspnet core. We have a website for the application (web) and an other website for authentication (idp) on same domain. 

When you are going to the web, if you are not connected you are redirected to the idp (/idp/Identity/Account/Login). An antiforgery token cookie is generated and verified on server after login.

It works perfectly on multiples platform. 

We have a problem with a platform where the antiforgery token is not present when i am on login page. The token is present on the page.

The log:
(Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter) Antiforgery token validation failed. "The required antiforgery cookie \".AspNetCore.Antiforgery.TKeVMinbTDc\" is not present."
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.TKeVMinbTDc" is not present. 

The issue occurs with firefox, chrome, edge and with the same navigator it work on an other platform (the same site installed on other platform)...

### .NET Version

6.0.4

**Comment by javiercn** [comment]
@damienmartel2 thanks for contacting us.

That looks like a cookie issue. I don't think I have enough details to pinpoint what's going on, but it sounds like you are doing a cross-origin redirect and the cookie policy is not correctly configured.

I don't think Blazor Server has anything to do here because all this happens before a Blazor Server app gets a chance to start.

**Comment by damienmartel2** [comment]
the customer ended up telling us that he had installed a tool on the workstation and after uninstalling it it works... sorry for the inconvenience
