### ISSUE TITLE
Secrets are not being read from k8s mounted folder - AddKeyPerFile - Core3.1

### ISSUE THREAD

**Issue by mehrdad-goudarzi** [dotnet/aspnetcore#42086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have developed a Console application using netcoreapp3.1 and it has references to the following packages:
`        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.16" />`

and I am reading secrets from the mounted folder like this:
`.AddKeyPerFile(KubernetesSecretsPath, true)
`
When I am using package version **3.1.25**, It doesn't read mounted secrets in k8s deployment.
I checked the related files and folder to the secret files are mounted in the related container or not, they are mounted correctly and everything with the file path is correct.

I just downgrade the packages to version 3.1.16 and everything starts working.

### .NET Version

3.1.419

**Comment by BrennanConroy** [comment]
Can you try using 6.0.x packages and see if the issue repros?

Also, did you only downgrade the Microsoft.Extensions.Configuration.KeyPerFile dependency or did you downgrade other packages as well at the same time? We haven't made any changes in KeyPerFile between 3.1.16 and 3.1.25 so it's unlikely to be related to the KeyPerFile package.

**Comment by mehrdad-goudarzi** [comment]
@BrennanConroy  I did downgrade all packages together. We will upgrade to net6.0 in future but it is still a problem for us and the others who are using .net core 3.1.

**Comment by adityamandaleeka** [comment]
@mehrdad-goudarzi Can you share a minimal repro that demonstrates this problem so we can investigate?
