### ISSUE TITLE
Can't run Blazor wasm hosted solution from VS 2022 with a custom environment 

### ISSUE THREAD

**Issue by luisabreu** [dotnet/aspnetcore#42081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've used Visual Studio 2022 to create a new Blazor wasm hosted app and I want to create a new custom environment that should be used instead of the predefined Development that is setup by default.

I've create a [demo project](https://github.com/luisabreu/BlazorHostedDemo) that reproduces the issues I'll be describing. I've also created a [post](https://stackoverflow.com/questions/72515702/blazor-wasm-adding-custom-environment-does-not-work) at stackoverflow that describes the issues in depth.

After creating the project, I have:

- created  new appsettings (appsetings.express.json) files for the server and client projects to keep the new environment settings
- added new index.html pages for each environment (index.html, index.development.html and index.express.html) and changed the way blazor is loaded (from autostart to custom start so that the enviroment can be defined when calling `Blazor.start`)
- updated the launchSettings.json on the server project so that the `ASPNETCORE_ENVIRONMENT` is set to Express
- changed the default `MapFallbackToFile` call so that the default index.html file loaded depends on the environment

### Expected Behavior

Expected to be able to run the app from VS by hitting F5, but setting the server side environment to anything different from Development will always end up with a 404 for the root page. 

### Steps To Reproduce

I've created a [demo project](https://github.com/luisabreu/BlazorHostedDemo) on github. If you hit run, you won't get the default page.

### .NET Version

6.0.3

### Anything else?

ASP.NET Core 6
Visual Studio 2022

**Comment by javiercn** [comment]
@luisabreu thanks for contacting us.

You need to explicitly enable static web assets if you want to use a custom environment by calling `UseStaticWebAssets()`

**Comment by luisabreu** [comment]
Hello.

Just out of curiosity, where does razor calls this method on the server side?

**Comment by javiercn** [comment]
@luisabreu this is not a razor feature but an asp.net core feature, the default host sets it up during development in the same way it does for other areas like UserSecrets

**Comment by luisabreu** [comment]
Thanks again. Maybe it would be good idea to put something about custom environment support for blazor wasm app

**Comment by jtleaming** [comment]
Ah, I found the answer over [here](https://github.com/dotnet/aspnetcore/issues/38212). Apparently there is a static `StaticWebAssetsLoader` class you call for `UseStaticWebAssets`.

**Comment by jtleaming** [comment]
> @luisabreu thanks for contacting us.
> 
> You need to explicitly enable static web assets if you want to use a custom environment by calling `UseStaticWebAssets()`

@javiercn can you explain why this is? I have seen nothing in the documentation on Blazor and static web assets which suggests this is needed. I can see the physical file providers being loaded up in the development environment but not other environments but I can't find the explicit code which prevents these from being loaded outside of development.

This seems like weird behavior, and more so weird that there is not explicit documentation on it when reading about static assets in blazor or aspnet core.
