### ISSUE TITLE
Connection disconnected with error 'Error: Server returned handshake error: Handshake was canceled.;Server returned handshake error: Handshake was canceled.;No Connection with that ID: Status code '404' (anonymous) @ chat.js:36 Promise.catch (async) (anonymous) @ chat.js:35

### ISSUE THREAD

**Issue by 18374907010** [dotnet/aspnetcore#42107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/86545790/172816090-8728829d-4d35-416d-9fc0-fa1ca025c73f.png)
![image](https://user-images.githubusercontent.com/86545790/172816139-6401ce41-09ac-4a6c-af6c-c884ac94a9e1.png)
The front and rear ends are used separately；Excuse me, what is the reason

### Expected Behavior

![image](https://user-images.githubusercontent.com/86545790/172816408-135e2e83-284a-4e55-83b8-3610de6f9781.png)
This is the expectation；

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/86545790/172816577-20d8228c-c999-4070-b589-66adff9da702.png)
![image](https://user-images.githubusercontent.com/86545790/172816712-c65a1912-d75c-4d80-9a26-d670cdf668d8.png)
This is the repeat step

### .NET Version

6.0

**Comment by 18374907010** [comment]
Can you guys help me out here，my fellow friend

**Comment by BrennanConroy** [comment]
Your server is behind IIS when not hosting on localhost and it looks like you haven't enabled WebSockets on IIS. https://docs.microsoft.com/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0#iisiis-express-support
