### ISSUE TITLE
Out of memory issue throws when rendering the 2040 * 2040 elements.

### ISSUE THREAD

**Issue by kmkrish001** [dotnet/aspnetcore#42108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we are trying to render the 2040 * 2040 elements in the Blazor application then we are facing the out of memory issue.

### Expected Behavior

The elements needs to be render without any issues.

### Steps To Reproduce

Run the below code with the Blazor application.

`@if (!DataLoaded)
{
    <h3>Loading data ...</h3>
}
else
{
    for (int i = 0; i < 2040; i++)
    {
        for (int j = 0; j < 2040 ; j++)
        {
            <div class="data">@DataSource[i,j]</div>
        }
    }
}

@code {

    bool DataLoaded = false;
    int[,] DataSource;

    protected override async Task OnInitializedAsync()
    {
        DataSource = await GetData();
        DataLoaded = true;
    }
    async Task<int[,]> GetData()
    {
        Random rand = new Random();

        int[,] fakeData = new int[2040, 2040];

        await Task.Run(() =>
        {
            for (int column = 0; column < 2040; column++)
            {
                for (int row = 0; row < 2040; row++)
                {
                    fakeData[column, row] = rand.Next(50);
                }
            }
        });

        return fakeData;
    }
}`

### .NET Version

6

**Comment by javiercn** [comment]
@kmkrish001 thanks for contacting us. 

Is this Blazor server or Blazor webassembly?

**Comment by kmkrish001** [comment]
Hi @javiercn 

It's blazor server application, our requirement is to render the large number of cells. So, we have simply reproduced the same with html elements.
