### ISSUE TITLE
AspNetCore.DataProtection deserialize a key file serialised (with nuget 5.0.x) using nuget 6.0.x lead to Invalid Payload exception

### ISSUE THREAD

**Issue by Whiletru3** [dotnet/aspnetcore#42111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On macOS, a key file was saved using AspNetCore.Dataprotection version 5.0.x.
When I try to decrypt content using version 6.0.x, I got an exception in 
ManagedAuthenticatedEncryptor.Decrypt(ArraySegment<byte> protectedPayload, ArraySegment<byte> additionalAuthenticatedData)

```
// Step 4: Validate the MAC provided as part of the payload.

                        if (!CryptoUtil.TimeConstantBuffersAreEqual(correctHash, 0, correctHash.Length, protectedPayload.Array, macOffset, eofOffset - macOffset))
                        {
                            throw Error.CryptCommon_PayloadInvalid(); // integrity check failure
                        }
```

in the key file the deserialiser type is Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=**5.0.0.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60"

after changing it to 
Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=**6.0.0.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60" manually, I no longer have the exception.

### Expected Behavior

No exception when loading a key serialized with an older version.

### Steps To Reproduce

I got the issue using this repo in a net6 application : https://github.com/integrativesoft/CrossProtectedData

### Exceptions (if any)

Error.CryptCommon_PayloadInvalid()

### .NET Version

6.0.300

**Comment by wtgodbe** [comment]
This may be related to a change we made to ContentRootPath in 6, could you try this workaround? https://github.com/dotnet/aspnetcore/issues/38274#issuecomment-969940980
