### ISSUE TITLE
Razor Class Library isn't adding typescript output to static web assets 

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#42110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm reopening the bug #41279, because the proposed solution does not work (it was closed prematurely).

I've RCL with a typescript sources:
scripts/file1.ts
scripts/tsconfig.ts

 and I want to include the generated javascript in the package as staticwebassets.

I've followed the docs: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio#typescript-integration

However, the javascript files are not included as staticwebassets when doing fresh build (without the generated files already being present).

Here is my csproj
```xml
<PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PrepareForBuildDependsOn>GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
	<TypescriptOutDir>wwwroot</TypescriptOutDir>
</PropertyGroup>

<ItemGroup>
	<SupportedPlatform Include="browser" />
</ItemGroup>

<ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.2" />
	<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.4">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/3494407/164256936-497b7ce9-447a-41e0-8d6d-87bbd7c9e99a.png)

### Steps To Reproduce

 1. Here is repo: https://1drv.ms/u/s!An7wnk66a6RRlqsR9ME32HR2wMNB5g?e=Xx7RIM

 2. **Important:** Make sure to delete the generated js files from wwwroot before each build
 
     `dotnet clean`

 3. `dotnet build`
 4. 
 5.   Open the package in Nuget Package Explorer: bin\Debug\RazorClassLibrary1.1.0.0.nupkg'

### .NET Version

6.0.300

**Comment by javiercn** [comment]
@Liero You are right, the line needs to be 

```xml
<PrepareForBuildDependsOn>CompileTypeScript;GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
```

@guardrex can we update the docs?
