### ISSUE TITLE
Latency during model binding

### ISSUE THREAD

**Issue by chandimar001** [dotnet/aspnetcore#42116]
We are investigating an issue where a small percent of requests take longer than the 500ms timeout the client sets. The majority of these requests spend most of it's time between the request body being read and the controller. The controller uses FromBody to bind the request body to data model. We are using Kestrel and .Net 5.

![image](https://user-images.githubusercontent.com/24394646/172900134-f65b6bf4-aa37-45dd-81b6-c8a49f9e383f.png)

"Started BlahMethod" is logged in the first line of the controller.

Notice that 906ms elapsed between request body read completion and the first log in controller. None of our code is being executed between these two lines. I assume this latency is occurring during model binding?

Notes:
- This happens with about 0.2% of traffic during peak
- Average latency for the other 99.8% of requests at the same time is around 20ms
- CPU is running at about 20% at this time
- The [kestrel diagnostic metrics](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/diagnostics?view=aspnetcore-6.0) don't show any requests or connections queuing up

Any thoughts on debugging this further?

**Comment by Tratcher** [comment]
What is the format of the request body, JSON, XML, etc.? And what type of parameters are you binding from it?

I see you're using Request Decompression. Does this repro if you remove that?

Note .NET 5 is out of support, you should update to .NET 6 and re-test this scenario.

**Comment by chandimar001** [comment]
The request body is in JSON format. The request body is pretty large and maps to complex classes which ultimately map to simple types like nullable strings, int and booleans. There are some dictionaries but they eventually all boil down to simple types.

We can't remove the decompression without a performance impact. The client is sending the request body with gzip compression so we have to decompress it. We can't remove it without making corresponding client side changes as well. That being said, request decompression finishes its logic very quickly. It literally takes less than 1ms to finish it's logic.
![image](https://user-images.githubusercontent.com/24394646/172917944-c9c44b69-6a64-4c82-bda9-9fd3e3f0538e.png)

Do you suspect the decompression having an effect on how long it takes for the deserialization?

.NET 6 is on our road map but looking for any intermediate solutions or ideas in the meantime.

**Comment by Tratcher** [comment]
If the decompression is processed lazily as data is read then the timestamps reported here only cover the setup, not actual decompression. The decompression would start after "started reading request body" and finish after "done reading request body".  Without instrumenting the decompression stream itself we can't know how long that takes.

**Comment by chandimar001** [comment]
RequestDecompressionMiddleware is a custom middleware that uses the code below. Are you saying that context.Request.Body is being set to a GZipStream object but the actual decompression happens inside the code executing the "started reading request body" logic?

```
public async Task Invoke(HttpContext context)
{
	this.logger.LogInfo("RequestDecompressionMiddleware - Hit RequestDecompressionMiddleware on the way in");
	this.logger.LogInfo($"{context.Request.Method}, Request ContentLength:{context.Request.ContentLength}");

	var contentEncodingHeaderValues = context.Request.Headers.GetCommaSeparatedValues(HeaderNames.ContentEncoding);

	this.logger.LogInfo("RequestDecompressionMiddleware - Got contentEncodingHeaderValues");
	this.logger.LogInfo("RequestDecompressionMiddleware - Start GetDecompressedStream");

	using (var decompressedStream = GetDecompressedStream(context, contentEncodingHeaderValues))
	{
		context.Request.Body = decompressedStream;

		this.logger.LogInfo("RequestDecompressionMiddleware - Finished GetDecompressedStream. Moving to next middleware.");

		await this.next(context);

		this.logger.LogInfo("RequestDecompressionMiddleware - Hit RequestDecompressionMiddleware on the way out");
	}
}

private static Stream? GetDecompressedStream(HttpContext context, string[] contentEncodingHeaderValues)
{
	if (contentEncodingHeaderValues.Contains("gzip"))
	{
		return new GZipStream(context.Request.Body, CompressionMode.Decompress);
	}

	return null;
}
```

**Comment by Tratcher** [comment]
Right, that's just setup code, the actual decompression happens later when the body is read. I don't know that it's the sole cause of your delays, but you won't know how much it's contributing until you can test without it.

**Comment by chandimar001** [comment]
Thanks! We are still trying to debug this. I am looking at migrating to .Net 6 and found something interesting. The project's TargetFramework is currently net5.0. I found a dependent project referencing nuget package Microsoft.AspNetCore.Http version 2.2.2. This is the last published version of the package (the service started off as .net core 2.1 service). We use the Microsoft.AspNetCore.Http package to access the request context and get headers and QSPs. Should we remove this package and replace the code references to use IHttpContextAccessor instead? I'm curious if this mix of Asp .Net Core 2.2 and 5.0 is making requests run through some non-performant code paths.

**Comment by Tratcher** [comment]
Yes, remove Microsoft.AspNetCore.Http, that assembly is now part of the shared framework. You shouldn't need IHttpContextAccessor if you're not already using it.
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30#remove-obsolete-package-references

**Comment by adityamandaleeka** [comment]
@rafikiassumani-msft Moving this back since the compression stuff mentioned here is orthogonal to the original issue.

**Comment by chandimar001** [comment]
Thanks for the prompt feedback. It is very much appreciated. We are continuing to investigate but there is not much more I can get from this thread so will close the issue. I will re-open it in case we get more diagnostics and need your advice. Thanks!
