### ISSUE TITLE
 The type or namespace name does not exist in the namespace '__Blazor

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#42129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Basically reopening https://github.com/dotnet/aspnetcore/issues/18310.

Can I get more details why https://github.com/dotnet/aspnetcore/issues/18310#issuecomment-573602614 is an accepted answer? A more complex component can have N templates with different `RenderFragment<TContext>` definitions and `TContext` classes - does this mean that the component should have N generic arguments? This seems impractical as a non-generic component can have various `RenderFragment<T>` without problems.

Having a real workaround (instead of adding more and more generics) will be appreciated as we need to support versions prior to .NET 7.0 where this might have been fixed https://github.com/dotnet/aspnetcore/issues/18757

Another alternative seems to have https://github.com/dotnet/razor-compiler/pull/34 ported to .NET 3.x (which is supported until Dec 2022) and .NET 6.0.

**Comment by javiercn** [comment]
@Stamo-Gochev thanks for contacting us.

I'm not sure I understand the issue here.

Could you put an example of what you are trying to accomplish and what code you would expect the compiler to generate?

**Comment by Stamo-Gochev** [comment]
I will need more time to provide a reproducible project.
