### ISSUE TITLE
[dotnet-sdk-7.0.100-preview.6.22310.18] https://localhost:5001 is not listened for Asp.Net Core apps that use Https

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#42161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**When testing the ASP.NET 3rd party apps against .NET 7 Preview 6, https://localhost:5001 is not listened. All of apps using https to access the site in our Lab are affected. We found there is a breaking change issue https://github.com/aspnet/Announcements/issues/486, it seems related to it.** 

**Application Name**:  All Asp.Net Core App that use Https
**OS**: Windows 10 RS5
**CPU:** X64
**.NET Build Number:** dotnet-sdk-7.0.100-preview.6.22310.18

**Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.6.22310.18: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22307.18: Pass

### Expected Behavior

The application window will show both http://localhost:5000/ and https://localhost:5001/ are listened like below shows.
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Appcompat\Desktop\demo app\bin\Debug\net7.0
```

### Steps To Reproduce

**Minimal Repro Steps:**
**The machine only has dotnet-sdk-7.0.100-preview.6.22310.18 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**

1. Create a Test folder.
2. Open command prompt window and navigate to the Test folder.
3. Run "dotnet new webapp" command to create a default asp.net core web app.
4. Run "dotnet publish" command to publish the app.
5. Run "dotnet dev-certs https --trust" command to install develop certificate.
6. Go to the publish folder and launch the exe file.

**Actual Result:**
Only http://localhost:5000/ is listened, as below shows:
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Appcompat\Desktop\demo app\bin\Debug\net7.0
```

### .NET Version

dotnet-sdk-7.0.100-preview.6.22310.18

### Anything else?

**Findings:**

1. If run the app with "dotnet run" command, both of http and https urls are listened.
2. This is the breaking change issue link we found that related to this issue: https://github.com/aspnet/Announcements/issues/486
3. dotnet --info
```
.NET SDK:
Version: 7.0.100-preview.6.22310.18
Commit: fcbddffa37

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19044
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.100-preview.6.22310.18\

global.json file:
Not found

Host:
Version: 7.0.0-preview.6.22309.9
Architecture: x64
Commit: e026f392b2

.NET SDKs installed:
7.0.100-preview.6.22310.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 7.0.0-preview.6.22310.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0-preview.6.22309.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 7.0.0-preview.6.22309.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

@dotnet-actwx-bot @dotnet/compat

**Comment by javiercn** [comment]
@Junjun-zhao thanks for contacting us.

This is expected and by design, you need to use `--urls` when you invoke the project or set the `ASPNETCORE_URLS` environment variable.

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT 
Thanks for your information. 
We tried some apps by updating appsettings.json file, most of the app work well. 1 app "Xplace ProjectNotifier" doesn't work with this but work with set the ASPNETCORE_URLS environment variable and urls , we checked its code, it doesn't use IConfiguration to load appsettings.json file. We think this is why it does not work with this way.

Now we are updating our automation script for all the affected apps with set the ASPNETCORE_URLS environment variable as it is easier way for us and will let you know if we encounter any issue fail on these 3 ways.

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT  
These is an issue for Blazor Server apps found that site will be disconnected about every 5s with System.Net.WebSockets.WebSocketException when binding https manually, we filed the bug https://github.com/dotnet/aspnetcore/issues/42224 for it. Could you please help check it? Thanks
