### ISSUE TITLE
Support authenticate attribute to specify authN schemes for controllers or method

### ISSUE THREAD

**Issue by Yitengyu** [dotnet/aspnetcore#42163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to get authenticated context with multiple AuthN schemes before AuthZ in my Web API service, but I got trouble.
Here is my use case:
```c#
  app.UseAuthentication();
  // It's trying to throttle with authenticated context
  app.UseThrottlingMiddleware();
  app.UseAuthorization();
```

I have many controllers with different schemes, one of the controllers can be
```C#
[Authorize(AuthenticationSchemes = “SchemeA, SchemeB”)]
[Route("/api/hello")]
public class HelloController : ControllerBase
{
    //...
}
```
It worked well before I wanted to add the `ThrottlingMiddleware` even without `AuthenticationMiddleware`. The authentication results will be combined in AuthZ then I can validate them.
Since the whole AuthZ costs more than AuthN, I'd like to add a throttling between AuthN and AuthZ. But I don't see a solution to do something in AuthN like `PolicyEvaluator.AuthenticateAsync` does.

A workaround is to implement a custom authN middleware with "First half" of the authZ middleware, but that's not friendly and it turns to validate token twice - one in AuthN and one in AuthZ.
I learned I can chain authentication schemes like #40820, but that would be complex and not supporting multiple identities from different scheme authentication.

### Option 1
Let authentication middleware respect `IAuthorizeData.AuthenticationSchemes`

### (Preferred) Option 2
Add an attribute like `AuthenticateAttribute` to define what schemes AuthN will use and deprecate `IAuthorizeData.AuthenticationSchemes`

**Comment by davidfowl** [comment]
> Since the whole AuthZ costs more than AuthN, I'd like to add a throttling between AuthN and AuthZ. But I don't see a solution to do something in AuthN like PolicyEvaluator.AuthenticateAsync does.

Can you help quantify this?

**Comment by Yitengyu** [comment]
> > Since the whole AuthZ costs more than AuthN, I'd like to add a throttling between AuthN and AuthZ. But I don't see a solution to do something in AuthN like PolicyEvaluator.AuthenticateAsync does.
> 
> Can you help quantify this?
My bad, I mean, MY AuthZ costs 10 times more than AuthN. My AuthZ needs to send some requests while AuthN can run almost locally.

**Comment by davidfowl** [comment]
>My bad, I mean, MY AuthZ costs 10 times more than AuthN. My AuthZ needs to send some requests while AuthN can run almost locally.

Can you quantify this? Show performance numbers? Explain the situation more?

**Comment by Yitengyu** [comment]
> Can you quantify this? Show performance numbers? Explain the situation more?

My AuthN simply validate tokens and get identities, it takes 1ms in average;
My AuthZ needs to communicate with other services to check users' permissions and licenses, it takes from 20ms to 500ms.

Please let me know if you want to know more.

**Comment by davidfowl** [comment]
I'm a bit confused. What exactly do you want to happen?

**Comment by Yitengyu** [comment]
1. I want to add throttling mechanism to my service
2. I hope my throttling rule can run against customer tenant, that's why I need authenticated context before throttling.
3. I also hope my throttling can also protect my AuthZ process, so I put the middleware before authorization middleware.

My problem is that I can't get authenticated context via built-in AuthenticationMiddleware while I'm using multiple auth schemes.

**Comment by HaoK** [comment]
You should try using the `IAuthorizationService` directly do to authorization exactly how you want rather than trying to reuse middleware/attributes 

See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0#iauthorizationservice
