### ISSUE TITLE
[Windows ARM64] Warn occured when dotnet run F# webapi/MVC in CLI.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/aspnetcore#42180]
### Steps To Reproduce

1.  Installed SDK: 7.0.100-preview.6.22313.2 from https://github.com/dotnet/installer on Windows ARM64.
2.  Created a new F# webapi/mvc in CLI.
3.  Dotnet run the project.

### Expected Behavior

Dotnet run the project without warning.

### Actual Behavior
Dotnet run F# webapi/mvc with warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
F# webapi project:
![image](https://user-images.githubusercontent.com/99376012/173483900-b3da0a28-7912-4e5d-a65f-b84bc95ea74f.png)
F# mvc project:
![image](https://user-images.githubusercontent.com/99376012/173484011-f91d19e5-87d9-4ccc-9b15-880846b94092.png)

### .NET Version

7.0.100-preview.6.22313.2 from https://github.com/dotnet/installer.

### Note
Dotnet run the F# wewbapi and mvc project successfully.

### dotnet --info:
.NET SDK:
 Version:   7.0.100-preview.6.22313.2
 Commit:    d3ce508e97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25094
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   D:\Program Files\dotnet\sdk\7.0.100-preview.6.22313.2\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.6.22312.1
  Architecture: arm64
  Commit:       5c5e66e6c0

.NET SDKs installed:
  7.0.100-preview.6.22313.2 [D:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.6.22312.2 [D:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22312.1 [D:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.6.22311.2 [D:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@vzarytovskii so you own F# ASP.NET Core project templates?
//cc @rafikiassumani-msft

**Comment by v-xiaofchen** [comment]
This issue not repro on SDK: 7.0.100-preview.5.22305.3.
F# webapi:
![image](https://user-images.githubusercontent.com/99376012/173538330-9479cae9-b88f-4e74-b846-86254b40e1dc.png)
F# mvc:
![image](https://user-images.githubusercontent.com/99376012/173538502-8fe9a5f3-aa74-45ef-8397-ee5c2332bd6a.png)

**Comment by vzarytovskii** [comment]
> Thanks for contacting us. @vzarytovskii so you own F# ASP.NET Core project templates? //cc @rafikiassumani-msft

Yeah, I guess, our team owns F# templates, I will look at it.

Do you maybe know if something HTTPS-related changed between `preview.5.22305.3` and `preview.6.22313.2`?

**Comment by mkArtakMSFT** [comment]
This is the breaking change in Kestrel: https://github.com/aspnet/Announcements/issues/486

**Comment by vzarytovskii** [comment]
> This is the breaking change in Kestrel: [aspnet/Announcements#486](https://github.com/aspnet/Announcements/issues/486)

Got it, so would adding `urls` to the config be the easiest fix for it, or was it already covered by #42027

**Comment by SteveSandersonMS** [comment]
Thanks @DamianEdwards. Closing as expected.
