### ISSUE TITLE
Create 5-10 canonical scenarios encompassing "how to do cloud native .NET" and make them friction-free.

### ISSUE THREAD

**Issue by bradygaster** [dotnet/aspnetcore#42189]
[This item was moved from planning repo]

Create a series of samples that are demonstrative of real-life customer scenarios and encapsulate those scenarios in a single repository showing how to achieve that *one specific thing*. 

## Content Production

- [x] [ASP.NET core razor front end with 2+ APIs hidden from the public internet](https://github.com/Azure-Samples/dotNET-FrontEnd-to-BackEnd-on-Azure-Container-Apps)
- [x] [ASP.NET core razor front-end with 2+ APIs hidden from the public internet using DAPR for API discovery](https://github.com/Azure-Samples/dotNET-FrontEnd-to-BackEnd-with-DAPR-on-Azure-Container-Apps)
- [ ] [Multiple ASP.NET Core front-ends with YARP proxying on container apps](https://github.com/bradygaster/ASPNETCoreWithYarpOnAzureContainerApps)
- [x] https://github.com/dotnet/orleans/issues/7553
- [x] https://github.com/dotnet/orleans/issues/7554
- [x] https://github.com/dotnet/orleans/issues/7675
- [ ] An article demonstrating web/queue/worker with .NET Core projects, and ideally using Connected Services for configuration.
- [x] [An sample demonstrating using ASP.NET feature flags and Azure App Configuration together to enable A/B testing](https://github.com/Azure-Samples/dotNET-Frontend-AB-Testing-on-Azure-Container-Apps)
- [x] [Sample demonstrating using ASP.NET gRPC and Workers to communicate](https://github.com/Azure-Samples/dotNET-Workers-with-gRPC-messaging-on-Azure-Container-Apps)

## Content Distribution
- [x] [Work with Azure Container Apps team to make sure .NET is represented with content when Azure Container Apps GA's.](https://docs.microsoft.com/en-us/azure/container-apps/samples)
- [x] Work with docs team to get official guidance for Orleans on Container Apps once Azure Container Apps GA's.
- [x] Get samples from `bradygaster` organization into the `azure-samples` organization and, hopefully, into the [Microsoft Docs Samples Browser](https://docs.microsoft.com/en-us/samples/browse/)

**Comment by amcasey** [comment]
Improving this experience is now tracked by https://github.com/dotnet/aspnetcore/issues/53654.
