### ISSUE TITLE
Standalone Blazor WASM with Azure Static App causes net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#42203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.NET 6 Standalone Blazor WASM  deployed on Azure Static Apps causes first-time load errors in Firefox, Chrome, and Edge. Next, load correctly and loads the app.

I can consistently reproduce the issue in Chrome Incognito mode. But the error comes when I clear all the cache and load the app the first time on regular tab  (the error is random, but it comes frequently).

Test  App: https://black-moss-05a44c41e.1.azurestaticapps.net

**Google Chrome**
![Chrome Error](https://user-images.githubusercontent.com/13166236/173809541-5d2f0643-d70f-4953-bbfb-ab073b456644.PNG)

**Firefox**
![Firefox error](https://user-images.githubusercontent.com/13166236/173809742-323f8b68-eaf2-4d40-af0d-6e133a11a062.PNG)

### Expected Behavior

The app should load correctly first time and subsequent time as well.

### .NET Version

6.0.300

### Anything else?

VS 2022

**Comment by javiercn** [comment]
@ameyasubhedar thanks for contacting us.

I'm trying the url you provided but I'm not able to reproduce the issue. How often does this happen? Would you be able to capture a network trace using wireshark or a similar tool so that we can see if there is something happening at the TCP level?

**Comment by ameyasubhedar** [comment]
@javiercn, the issue is random but I can reproduce frequently, especially in incognito mode and after clearing the cache.

I have the wireshark trace, how do I share it with you. GitHub does not allow the file.

Here is the network log from chrome, its complaining about CORS and Http2 error But I don't call make any API .
[black-moss-05a44c41e.1.azurestaticapps.net.log](https://github.com/dotnet/aspnetcore/files/8919906/black-moss-05a44c41e.1.azurestaticapps.net.log)
[black-moss-05a44c41e.1.azurestaticapps.net-1655386663639.log](https://github.com/dotnet/aspnetcore/files/8919907/black-moss-05a44c41e.1.azurestaticapps.net-1655386663639.log)

**Comment by ameyasubhedar** [comment]
@javiercn, even the VS report does not allow wireshark file extension. I just renamed the extension and uploaded here...
[wireshark-error.txt](https://github.com/dotnet/aspnetcore/files/8920121/wireshark-error.txt)

Please rename to .*pcapng

**Comment by javiercn** [comment]
@ameyasubhedar I was suggesting using VS because it allows to share it privately. You shouldn't share pcapng files in the open as they might contain private information.

I've removed the link from your comment just in case.

**Comment by ameyasubhedar** [comment]
Ok thanks, Noted. So you have the data now for your debugging purposes ?

**Comment by javiercn** [comment]
@ameyasubhedar yep.

What I'm seeing is a LOT of network errors, which might explain the errors you are seeing

**Comment by ameyasubhedar** [comment]
Ok but they are specific to my test Blazor WASM on static app. I don't see these errors on any other sites.

**Comment by SteveSandersonMS** [comment]
@anthonychu Do you think someone on the Azure Static Web Apps team could look at this?

Blazor itself is just the files being served so it can't cause this HTTP2 protocol error as far as I understand. I don't know if there's an Azure Static Web Apps problem or not here, but I guess someone on that side would be best to look into that!

**Comment by ameyasubhedar** [comment]
@javiercn, I just tried a minor color change and redeployed to Azure and tested on a different machine. Got the same Http2 Error. The first time load gets stuck on 

![image](https://user-images.githubusercontent.com/13166236/174265861-88932b51-202a-4c5f-927e-d1c28c2c14ef.png)

Console errors
![image](https://user-images.githubusercontent.com/13166236/174266120-f82806dd-eb11-450d-9233-f3c1fccd6666.png)

**After errors I hit F5 to refresh** 
![image](https://user-images.githubusercontent.com/13166236/174266245-bd500eb1-7f88-47f0-8c80-5696758d1f7b.png)

This pattern is consistent, so this is definitely the first time load after change or in incognito mode without cache that causes the error.

**Comment by asperpint** [comment]
**+1**,  I have been scratching my head from last 4 days and facing the same random load issue for our production apps. They started throwing random HTTP2 errors. The only change we made is that we upgraded to .NET 6.0.300 from .NET 6.0.201

Both our production apps have the same random errors (Build with Blazor WASM Standalone .NET6 and Deployed on Azure Static App). 

1. https://www.perpetualintelligence.com/
2. https://consumer.perpetualintelligence.com/

@javiercn, **The error is random and hitting F5 makes it go away.** The typical sign of the error is it take a long time to load and then times out with Http2 error. There is no network interruption. I have verified that.

![image](https://user-images.githubusercontent.com/106403372/174268661-c66aaa83-6319-479a-8ad0-9e58186ed513.png)

**After Refresh on the same tab:**
![image](https://user-images.githubusercontent.com/106403372/174268967-8c92927b-c5c1-4893-b826-666502a7f627.png)

**Comment by javiercn** [comment]
@ameyasubhedar thanks for the additional details.

Was the other machine also on the same network as the current one? Could you try accessing the page from your phone via 4G or 5G?

From what I can tell (and the fact that I can't repro) it is likely caused by a network issue at some point between your connection and Azure. I'm not sure it is Azure either, since I see no problems accessing from my end.

Also FYI I'm trying to route this to the appropriate teams in Azure, since this is very likely not caused by Blazor.

**Comment by javiercn** [comment]
@asperpint thanks for the report.

Could you file a separate issue so that we can track your concrete scenario separately? Otherwise it makes it really hard to get the details if several people is adding their own info. Lets leave this issue for @ameyasubhedar problem and use a separate issue to deal with the problems you are facing.

**Comment by mishapos** [comment]
@ameyasubhedar Hi, looking into this from the Static Web Apps side, and even when using incognito mode and refreshing and using .Net 6.0.300, I was not able to reproduce this behavior. If you are still experiencing this issue, could you please open a support ticket with Azure and route it to Azure Static Web Apps, so we can get the network trace and see what's going on? Thanks so much!
