### ISSUE TITLE
IDX10206: Unable to validate audience. The 'audiences' parameter is empty

### ISSUE THREAD

**Issue by jeanyves7** [dotnet/aspnetcore#42207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to validate the token issued from keycloak in the frontend and sent in the authorization header to the backend to be validated, the request is failing with the following message:
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10206: Unable to validate audience. The 'audiences' parameter is empty.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   ...
   
Below is an extract of the code used:
![Screenshot 2022-06-15 180234](https://user-images.githubusercontent.com/68806505/173860482-a5eb5bdb-26da-41cf-b929-47bd5ff9ba1c.png)

### Expected Behavior

The code should be able to validate the token.

**Comment by jeanyves7** [comment]
> 

i sincerely don't know if we have it or no

**Comment by jeanyves7** [comment]
> If you capture the JWT (fiddler, or just console.writeline/logging in, maybe, [OnMessageReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbearerevents.onmessagereceived?view=aspnetcore-6.0#microsoft-aspnetcore-authentication-jwtbearer-jwtbearerevents-onmessagereceived) ) you'll see it, in the form of "aud" : "_something_", it's not encrypted or anything.
> 
> Technically you can have a jwt without it, it's just an odd thing, because you want scoped tokens.

Thank you I will try it and see what is happening

**Comment by jeanyves7** [comment]
> If you capture the JWT (fiddler, or just console.writeline/logging in, maybe, [OnMessageReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbearerevents.onmessagereceived?view=aspnetcore-6.0#microsoft-aspnetcore-authentication-jwtbearer-jwtbearerevents-onmessagereceived) ) you'll see it, in the form of "aud" : "_something_", it's not encrypted or anything.
> 
> Technically you can have a jwt without it, it's just an odd thing, because you want scoped tokens.

Thank you for your feedback after debugging and parsing the generated token, I found out that keycloak is not including the audience in the "aud" field you need to manually specify in keycloak what audience are added to the token

**Comment by blowdart** [comment]
Ah wonderful :) Technically it's within the spec, practically everything will expect an audience, otherwise you get a token that would be usable everywhere. I'm glad you figured it out.
