### ISSUE TITLE
No nullable warning on WaitForShutdown()

### ISSUE THREAD

**Issue by nobody-famous** [dotnet/aspnetcore#42238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a nullable WebApplication reference calls WaitForShutdown, no warning is given about the reference being null.

### Expected Behavior

There should be a warning.

### Steps To Reproduce

dotnet new web

edit Program.cs to contain the following code,

-----
var builder = WebApplication.CreateBuilder(args);
WebApplication? app = null;

app.WaitForShutdown();
-----

dotnet build

Build's clean, no warning. Change the code to,

-----
var builder = WebApplication.CreateBuilder(args);
WebApplication? app = null;

app.GetType();
app.WaitForShutdown();
-----

dotnet build

Warning on line 4.

### .NET Version

6.0.100

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by adityamandaleeka** [comment]
@nobody-famous It looks like this has already been fixed in .NET 7. Can you please upgrade to the latest preview release and try it out?
