### ISSUE TITLE
[Blazor] Reference to component (@ref) is set after entire container is rendered

### ISSUE THREAD

**Issue by macias** [dotnet/aspnetcore#42239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Documentation -- https://docs.microsoft.com/en-in/aspnet/core/blazor/components/?view=aspnetcore-6.0#capture-references-to-components -- states that the reference to component is captured after component is rendered. It seems not be the case -- entire container has to be rendered.

> A component reference is only populated after the component is rendered

### Expected Behavior

Behavior like the documentation says, once it is rendered, the reference is set.

### Steps To Reproduce

Create such demo page:

```
<PageTitle @ref="toggle"></PageTitle>
<button @onclick="clicked">Re-render</button>
@if (toggle == null)
{
    <p>It is null</p>
}
else
{
    <p>Not null now</p>
}

@code
{
    private PageTitle? __toggle;
    private PageTitle? toggle
    {
        get { return __toggle; }
        set
        {
            __toggle = value;
            Console.WriteLine($"Setting null? {value == null}");
        }
    }

    private void clicked()
    {
        Console.WriteLine("Triggering render");
        StateHasChanged();
    }

}
```

Open console in your browser and run it. You will see in the console that the reference is set, but on the web page the info says it is null (component at this point should be fully rendered). Now click the button "rerender" to trigger state change, nothing really is changed, but it triggers rendering. And after that the web page also says the reference is not null.

It should happen on the first render.

### .NET Version

6.0.301

**Comment by javiercn** [comment]
@macias thanks for contacting us.

The component reference is captured and available within `OnAfterRender` which happens after the component has rendered. In your example, it is expected that the reference is null at that point.

**Comment by macias** [comment]
Of course maybe it is my English, but at the closing tag of the component, component has all the data, so it is done (rendered). After this point reference should be available, and it is not. It is only available after entire container (parent, or root) is rendered.

So I would say that at least the documentation is misleading, but also if currently it is intended it would be good to change the behaviour so it would work in such scenarios like above.

So... the question is, is it carved in stone, or would be useful to report is as wish-request?

**Comment by javiercn** [comment]
> Of course maybe it is my English, but at the closing tag of the component, component has all the data, so it is done (rendered). After this point reference should be available, and it is not. It is only available after entire container (parent, or root) is rendered.

It's not after the `<PageTitle @ref="toggle"></PageTitle>` component is rendered, but after your demo page is done rendering. 

We don't plan to change this behavior because it prevent us from rendering components independent of each other and imposes a strict ordering that drastically reduces the performance.

Component rendering in Blazor is a declarative process where the component builds a list of frames, the framework diffs those frames against the previous render and produces a set of changes that need to be applied to the DOM, and after those changes are applied, is that component and element references are made available within OnAfterRender.

You should not rely on component or element references outside of OnAfterRender.

**Comment by javiercn** [comment]
To answer your question, this behavior is pretty much carved in stone, it would be a massive breaking change and would lead to worse performance.
