### ISSUE TITLE
Unable to create Blazor Server project with Identity feature.

### ISSUE THREAD

**Issue by rccnw** [dotnet/aspnetcore#42242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using VS2022 17.2.4, I created a new project and selected Blazor Server with Identity Platform.
When prompted to install additional components during the project creation, it appears to fail (spins then stays at that step).
Cancelling that prompt, the solution appears normal but doesn't seem to contain Identity components.
Running the application fails with Exceptions related to Identity.

So, this is an 'out of the box' template usage with no modification.
Doing the same workflow with the same selections but selecting no Authentication type is successful.

### Expected Behavior

Able to complete the project creation workflow without cancelling out of the 'additional components' step.
Able to run the application without errors.

### Steps To Reproduce

Using VS2022 17.2.4, I created a new project and selected Blazor Server. 

I selected .NET 6, Authentication 'Microsoft Identity Platform', Configure for HTTPS, and 'Do not use top-level statements'

I selected 'Create', and am prompted with a 'Required Components' dialog.  'Required components need to be installed, Click Next to install components.  The component listed is:  dotnet msidentity tool.

I click 'Next' and the program is busy for 15 seconds, during which it displays in the lower left 'Installing required components...'
Repeating 'Next' repeats this behavior.
Clicking 'Finish' very briefly displays 'Connecting..' (its just 1/2 second).

Clicking 'Finish' dismisses the dialog.
Building the program is successful.
Running the program fails

### Exceptions (if any)

System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)

System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

6.0

### Anything else?

VS2022 17.2.4,
Here is the project file in text form:

(angle brackets removed so it will display correctly)

Project Sdk="Microsoft.NET.Sdk.Web"

  PropertyGroup
    TargetFramework net6.0 /TargetFramework
    Nullable enable /Nullable 
    ImplicitUsings enable/ImplicitUsings
    UserSecretsId  aspnet-TestSuiteConfiguration-BE30FC9F-AE3E-41A8-8ACD-AEC536859DF7  /UserSecretsId>
    WebProject_DirectoryAccessLevelKey 0 /WebProject_DirectoryAccessLevelKey
  /PropertyGroup

  ItemGroup
    PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.6" NoWarn="NU1605"/
    PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.6" NoWarn="NU1605" /
    PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" /
    PackageReference Include="Microsoft.Identity.Web.UI" Version="1.16.0" /
  /ItemGroup>

/Project

**Comment by TanayParikh** [comment]
cc/ @HaoK @deepchoudhery does this need to go via VS feedback?

**Comment by HaoK** [comment]
This isn't asp.net identity, this is @jennyf19 microsoft.identity stuff

**Comment by jennyf19** [comment]
@HaoK this is actually the VS tooling, I believe, so @sayedihashimi and @vijayrkn should be able to help.

**Comment by vijayrkn** [comment]
Adding @zahalzel 

Looks like the issue is with installing the dotnet msidentity tool. 
`
I click 'Next' and the program is busy for 15 seconds, during which it displays in the lower left 'Installing required components...'
Repeating 'Next' repeats this behavior.
Clicking 'Finish' very briefly displays 'Connecting..' (its just 1/2 second).
`

@zahalzel - Can you please share the manual steps to install the local tool to see why the local tool install is failing?

**Comment by adityamandaleeka** [comment]
@vijayrkn Is there another repo that this should be transferred to?

**Comment by vijayrkn** [comment]
You can move it to dotnet/scaffolding which is the closest repo. The ideal place would be VS developer community since the issue is VS related.

**Comment by rccnw** [comment]
I attempted to install the ms identity package from the command line and that failed. I finally determined that the package source for nuget.org was not enabled.  I'm not sure but this may be the root of the issue reported above.

**Comment by vijayrkn** [comment]
> I attempted to install the ms identity package from the command line and that failed. I finally determined that the package source for nuget.org was not enabled. I'm not sure but this may be the root of the issue reported above.

Does it work once you add the NuGet source?

**Comment by zahalzel** [comment]
Seems like there needs to be a check to make sure that the tool installs, and I don't think "Finish" should be enabled on the External Components installation page for the Identity connected services flow, so I'll check into these

**Comment by rccnw** [comment]
>> Does it work once you add the NuGet source?

After manually installing the package, yes I can create a new Blazor Server project with Identity, and that works correctly.  

However, this is now a different test case.  Because this time the package was installed already manually by me, so when I created a similar new project Visual Studio did not try to install it, which is where the initially reported error occurred.  

I strongly assume that original test case would succeed, but because it now skips that installation step I wasn't exactly testing the original scenario.  

I also should mention, the way I figured this out was by using 'dotnet nuget list source' in a command window. I saw that nuget.org was not enabled.  I performed 'dotnet nuget enable source nuget' and then re-tried the manual install of the identity package which then succeeded.

**Comment by vijayrkn** [comment]
> However, this is now a different test case. Because this time the package was installed already manually by me, so when I created a similar new project Visual Studio did not try to install it, which is where the initially reported error occurred.

Thanks for the confirmation. You can always uninstall the tool globally and let VS install the right version locally for the project. This way you can be certain that you will get the latest compatible version of the tool for each project.

**Comment by zahalzel** [comment]
PR for this: https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/406009
will close the bug once it's merged

**Comment by adityamandaleeka** [comment]
@zahalzel Can this be closed now? Looks like that PR was merged.

**Comment by zahalzel** [comment]
> @zahalzel Can this be closed now? Looks like that PR was merged.

Yep closing, thanks :)

**Comment by zahalzel** [comment]
@rachkoud  can you try this:

dotnet tool uninstall microsoft.dotnet-msidentity -g
dotnet tool install microsoft.dotnet-msidentity -g 

and then run the scenario in VS

**Comment by rachkoud** [comment]
@zahalzel Great that works! Thanks!
