### ISSUE TITLE
Deploy Blazor WASM with MySQL on Ubuntu (Ansible)

### ISSUE THREAD

**Issue by Spec86** [dotnet/aspnetcore#42253]
Hello, how are deploy Blazor WASM with MySQL on Ubuntu? Not local deploy. Deploy on production server. Step by step. May be you have Ansible file with code comments for this procedure?

**Comment by javiercn** [comment]
@Spec86 thanks for contacting us.

You can read about deployment for webassembly applications [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0).

We don't plan to offer any integration with Ansible for the time being, the community is free to do so if they choose to.
