### ISSUE TITLE
Add BlazorServer into Ansible Galaxy

### ISSUE THREAD

**Issue by Spec86** [dotnet/aspnetcore#42255]
There are not ansible files for BlazorServer in Ansible Galaxy. Can you add Ansible files (BlazorServer with any databases) into Ansible Galaxy repository for funs of BlazorServer?

**Comment by javiercn** [comment]
@Spec86 thanks for contacting us.

This is not something that we plan to do. We don't generally handle integrations with third-party products, but the community is free to do so.
