### ISSUE TITLE
Add Blazor WASM into Ansible Galaxy

### ISSUE THREAD

**Issue by Spec86** [dotnet/aspnetcore#42254]
There are not ansible files for Blazor WASM in Ansible Galaxy. Can you add Ansible files (Blazor WASM with any databases) into Ansible Galaxy repository for funs of Blazor WASM?

**Comment by javiercn** [comment]
@Spec86 thanks for contacting us.

This is not something that we plan to do. We don't generally handle integrations with third-party products, but the community is free to do so.
