### ISSUE TITLE
can't deploy .net 7 preview 5 to iis(win server2012)

### ISSUE THREAD

**Issue by coader** [dotnet/aspnetcore#42274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

because I have to use @onmousemouse in blazor, and it's only exists in .net 7
after I install .net 7 in server(win2012),  the website which is base on .net7 can't be started
and  those applications use .net 6 also throw errors:

HTTP Error 500.19
result code is 0x8007000d

then I tried to uninstall .net 6 and reinstall .net 7,
still got this error

this application is running correctly in my PC (win11)

### Expected Behavior

app base on .net 7 should running in IIS(8)

### .NET Version

7.0.100-preview.5.22307.18

**Comment by DamianEdwards** [comment]
Can you check the Windows event application log to see if there's more details of the error?

Did you install the [ASP.NET Core 7 Hosting Bundle](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-7.0.0-preview.5-windows-hosting-bundle-installer)?

**Comment by coader** [comment]
yes, already installed hosting bundle, 
not found any events in windows event viewer

**Comment by blowdart** [comment]
Please note support for 2012 and 2012r2 ended in 2018, unless you have an extended support agreement. You really should be on a supported server OS.
