### ISSUE TITLE
Is the IsReusable property of the ModelStateInvalidFilter class necessary?

### ISSUE THREAD

**Issue by pea-sys** [dotnet/aspnetcore#42279]
※My English isn't so good so feel free to ask me if there is anything unclear.

## Summary
I found one error in the document.  
ModelStateInvalidFilter.IsReusable property description is System.Object.IsReusable.
※ [Doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.modelstateinvalidfilter.isreusable?view=aspnetcore-6.0#microsoft-aspnetcore-mvc-infrastructure-modelstateinvalidfilter-isreusable)
After reviewing the source code, I did not see the need for this property.

## Motivation and goals
* Avoid user confusion

## In scope

A list of major scenarios, perhaps in priority order.
* If the IsReusable property is needed, fix the property description in the documentation.
* If the IsReusable property is not needed, I will remove it from the source code and documentation to avoid user confusion.

## Out of scope

* No response

## Risks / unknowns

* Misunderstanding of design intent

## Examples

None

**Comment by javiercn** [comment]
@pea-sys thanks for contacting us.

That implementation comes from `IFilterFactory` so it is not something that we can remove. That property is meant to indicate whether the filter can be cached by the pipeline or if a new instance needs to be created on every request.
