### ISSUE TITLE
Can't use VS 2022 Latest preview (public) to generate a Angular project if .net 7 preview 5 is installed

### ISSUE THREAD

**Issue by anirugu** [dotnet/aspnetcore#42287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/35772421/174468244-0a98ba40-7b9b-4dcb-ac97-31c4094086db.png)

### Expected Behavior

It should generate the project. Currently it's failing.

### Steps To Reproduce

Install VS 2022 Latest public preview and .net 7 preview 5 and install angular cli and then create the project it's failing. It have no relation with .net 7 so it must be able to generate it.

If you check the screenshot, I don't even check the checkbox to add asp.net core dependencies to the project. previews

### Exceptions (if any)

VS gives exceptions. look at the screenshot.

### .NET Version

7.0.100-preview.5.22307.18

### Anything else?

NA

**Comment by javiercn** [comment]
@anirugu thanks for contacting us.

You are trying to use the JavaScript standalone project which is something that our team doesn't own. I am routing this to the right folks, but you will get at better and faster answer if you report this issue directly through the [Report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) UI in Visual Studio
