### ISSUE TITLE
Web Assembly Prerender Not Rendered 

### ISSUE THREAD

**Issue by XHAlawa** [dotnet/aspnetcore#42280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've Followed Microsoft Doc Page To Convert My Wasm App to PreRenderd

but Content Still The Same

![image](https://user-images.githubusercontent.com/46560141/174443713-2ffdbecb-4d8d-41c9-a2a7-80c3aa673e70.png)

### Expected Behavior

Static Content Should Be Rendered

### .NET Version

.Net Core 6

**Comment by javiercn** [comment]
@XHAlawa thanks for contacting us.

Can you point us to what guide you followed, whether you are observing any errors/logs on the server/command line and if possible, provide a repro project as a public github repository so that we can help determine what is going on?

**Comment by XHAlawa** [comment]
Hello @javiercn  , I've Followed This Tutorial 
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly

After Checking Logs and Step By Step Debugging No thing Was Wrong
Except for IJSRuntime Invoke and this  exception was handled by UI Framework  , 
then I've searched on microsoft docs  again about that exception and some refactor
now it's working fine with me.

but there some thing strange most of items rendered  by wasm Prerender not acting  the same actions by normal wasm 

thanks for your effort.
