### ISSUE TITLE
NavigationManager should be able to cancel the navigation request on LocationChanged in Blazor

### ISSUE THREAD

**Issue by kashifasif** [dotnet/aspnetcore#42285]
The NavigationManager should be able to cancel the navigation request on LocationChanged

Sometime we need to cancel the current navigation request let say i want user to stop going back or forward when user has changes into form without saving it and i want to show a Moda/Popup that you have unchanged changes into form etc.

**Comment by javiercn** [comment]
@kashifasif thanks for contacting us.

This is not generally possible as location changed can triggered by several browser mechanics like the user clicking the forward or back button and browser don't currently allow preventing those navigations from happening, as it would be a security issue that would allow an attacker to trap a user in a given page.
