### ISSUE TITLE
Add Microsoft.Extensions.Http.Polly to the aspnetcore shared framework and ref pack.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/aspnetcore#42282]
## Summary

I would like for [this](https://github.com/dotnet/aspnetcore/blob/main/src/HttpClientFactory/Polly/src/Microsoft.Extensions.Http.Polly.csproj) to be added to the Microsoft.AspNetCore.App shared framework and ref packs because it can be useful without having to worry about using it as an nuget package (it exists in this repo so why not just add it to the aspnetcore framework). If this gets done then I can use it in my Discord Bot (yes I use the AspNetCore framework to run the Discord Bot using the generic host libraries that exist in the aspnetcore framework allowing me to bypass what would normally run for server programs). However my Discord Bot also uses EFCore so I will also open issue to create AspNetCore specific projects for that which will exclude packages that exist in the aspnetcore shared framework and ref packs.

## Motivation and goals

What pain points would this solve?
- It would reduce dependencies on dependencies that I use which would make my FDD deployements smaller.
- It would allow me to open a pull request to those dependencies (Remora.Discord, and dotnet/efcore) to add a version of those projects that prefer the aspnetcore framework reference over the packages.
  - Sad part about the package issue is that even when FDD ``dotnet publish`` they still get copied when I want the package assemblies to get trimmed for the ones from the framework, however trimming does not like FDD deployments.
  - An alternative to this could be that the SDK could tell nuget to look for \<TFM\>-aspnetcore specific folders in their lib/ref folders in the nuget packages and use them as if they were made to be AspNetCore specific packages which would normally target just the base TFM (aka fake TFM) but only when the project references the Microsoft.AspNetCore.App framework.

**Comment by martincostello** [comment]
I doubt this will idea will fly given the package depends on Polly, a third-party dependency.

**Comment by DamianEdwards** [comment]
As @martincostello points out, we have a policy of not putting 3rd party packages in the shared frameworks/ref packs.
