### ISSUE TITLE
AddRoleValidator incorrect generic argument name

### ISSUE THREAD

**Issue by Narsun** [dotnet/aspnetcore#42294]
According to the documentation, method `Microsoft.AspNetCore.Identity.IdentityBuilder.AddRoleValidator` adds an IRoleValidator<TRole>. 
But! Name of generic parameter of method AddRoleValidator is TRole, instead of TValidator or TValidator<TRole>.
![image](https://user-images.githubusercontent.com/16048127/174502695-cea81193-cf9e-4d9c-a647-3ed9d5b0611a.png)
on this screenshot we can see, `<typeparam name="TRole">The role validator type.</typeparam>`, but TRole is incorrect name for this. I think, it called like in AddUserValidator, - TValidator. because TRole or TUser - is a concrete implementation of TEntity, not an TValidator.
doc: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identitybuilder.addrolevalidator?view=aspnetcore-6.0
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identitybuilder.adduservalidator?view=aspnetcore-6.0

**Comment by adityamandaleeka** [comment]
Triage: Yea, this name isn't great... unfortunately however, we don't think this meets the bar for making an API breaking change.
