### ISSUE TITLE
RenderFragment becomes visible after hot reload

### ISSUE THREAD

**Issue by jburman** [dotnet/aspnetcore#42312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Runtime: 6.0.5
SDK: 6.0.300

Scenario: 

I have a WinForms app with Blazor Web View, running from command line with **dotnet watch run**.

In the MainLayout I have a snippet like below:

```
<If Value="AppState.AdminMode">
    <True>
        <a href="#" class="btn btn-outline-dark btn-lg float-right mr-2" @onclick="HandleExitAdminClicked">Exit Admin</a>
    </True>
</If>
```

The **If.razor** component is as below:

```
@if (Value)
{
    @True
}
else if(False is not null)
{
    @False
}

@code 
{
    [Parameter] public bool Value { get; set; }

    [Parameter] public RenderFragment True { get; set; } = default!;
    
    [Parameter] public RenderFragment? False { get; set; }
}
```
When app initially loads, AppState.AdminMode has a value of false, and the Exit Admin button is hidden. If I change some text in the MainLayout and hot reload runs, AppState.AdminMode is still false, but the Exit Admin button becomes visible.
Is there an explanation for this? The same thing happens across the app for all If component usages (this component is defined in a separate Razor Component library if that matters.)

**Note:** Replacing the **If** component with a if() statement causes the button to be correctly hidden.

Here is my .csproj settings...
```

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release</Configurations>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="6.0.312" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
...removed...
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
</Project>
```

### Expected Behavior

The <True> RenderFragment should not be rendered.

### Steps To Reproduce

Create a WinForms project with a Blazor WebView, add the <If> component (defined above) somewhere, and run with dotnet watch run. Trigger a hot reload.

### .NET Version

6.0.5

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
