### ISSUE TITLE
The method `AddPolicyRegistry` is called multiple times, and only the last one takes effect

### ISSUE THREAD

**Issue by saber-wang** [dotnet/aspnetcore#42321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The method `IServiceCollection AddPolicyRegistry(this IServiceCollection services, Action<IServiceProvider, IPolicyRegistry<string>> configureRegistry)` is called multiple times, and only the last one takes effect

https://github.com/dotnet/aspnetcore/blob/69d3755451b48d6c5a60ce7c1d1070a03727c90e/src/HttpClientFactory/Polly/src/DependencyInjection/PollyServiceCollectionExtensions.cs#L79-L106

### Expected Behavior

Multiple calls will be registered in the `PolicyRegistry`

### Steps To Reproduce

```
 var builder = WebApplication.CreateBuilder();
 builder.Services.AddPolicyRegistry((sp,registry)=> registry.Add("test1", Policy.NoOpAsync()));
 builder.Services.AddPolicyRegistry((sp, registry) => registry.Add("test2", Policy.NoOpAsync()));

 using var app = builder.Build();

var registry = app.Services.GetRequiredService<IReadOnlyPolicyRegistry<string>>();
Assert.IsNotNull(registry.Get<AsyncPolicy>("test1")); 
Assert.IsNotNull(registry.Get<AsyncPolicy>("test2"));
```

### Exceptions (if any)

System.Collections.Generic.KeyNotFoundException: The given key 'test1' was not present in the dictionary.

### .NET Version

6.0.301

### Anything else?
You can wrap `policyregistry ` in `options` to handle this problem
```
public static IServiceCollection AddPolicyRegistry(this IServiceCollection services, Action<IServiceProvider, IPolicyRegistry<string>> configureRegistry)
    {
        if (services == null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        if (configureRegistry == null)
        {
            throw new ArgumentNullException(nameof(configureRegistry));
        }
       
      
        // Create an empty registry, configure it and register it as an instance.
        // This is the best way to get a single instance registered using all the interfaces.
        services.AddOptions<PolicyRegistry>().Configure(configureRegistry);

        services.AddSingleton<IConcurrentPolicyRegistry<string>>(serviceProvider => serviceProvider.GetRequiredService<IOptions<PolicyRegistry>>().Value);
        services.AddSingleton<IPolicyRegistry<string>>(serviceProvider => serviceProvider.GetRequiredService<IOptions<PolicyRegistry>>().Value);
        services.AddSingleton<IReadOnlyPolicyRegistry<string>>(serviceProvider => serviceProvider.GetRequiredService<IOptions<PolicyRegistry>>().Value);

        return services;
    }
```

**Comment by martincostello** [comment]
The method is adding a new registry on each call, with each configured differently. Then then leans into the standard container behaviour where the last service wins if you request a single service (`T GetService<T>()`) where as requesting multiples (`IEnumerable<T> GetServices<T>()`) would return all of them.

You would get similar issues with various other services if you called them multiple times trying to run multiple configuration delegates by calling an `Add*()` method multiple times.

Instead, you should be configuring all of your policies in the same callback:

```csharp
builder.Services.AddPolicyRegistry((_, registry) =>
{
    registry.Add("test1", Policy.NoOpAsync());
    registry.Add("test2", Policy.NoOpAsync());
});
```
