### ISSUE TITLE
No default value for missing Enumerable QueryParameter

### ISSUE THREAD

**Issue by Lyra2108** [dotnet/aspnetcore#42320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I define an optional Query Parameter which is any type of a collection because I expect the query parameter to be present multiple times.

If this QueryParameter is then missing. I will always get back an empty collection instead of the default value I set.

### Expected Behavior

I would expected that if the parameter is missing the default value would apply instead of an empty collection

### Steps To Reproduce

https://github.com/Lyra2108/QueryParam/commit/19507eed5f21c4cb6d8c9dc11c06b0a6be50b992

It is simple to reproduce you can see it in this commit above.

### .NET Version

6.0.300

### Anything else?

See the repository for the version. 
The IDE does not seem to matter I had this issue with VS Enterprise and with Rider.

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Lyra2108** [comment]
Hey, If this will be considered for .NET 7. Is there a good way I can get this behavior locally in .NET 6? I am currently a little bit helpless with this behavior.

**Comment by Lyra2108** [comment]
Ok I workaround the issue now by creating a custom array model binder https://github.com/Lyra2108/QueryParam/commit/88ccdccc63c037b618bb6c8333b4517fb9e0c766

**Comment by brunolins16** [comment]
@Lyra2108 sorry I didn't have a chance to look this issue before.

The ArrayBinder explicitly creates a empty collection https://github.com/dotnet/aspnetcore/blob/ff873a58981aef5ecd1c70697aed83aaf6858a80/src/Mvc/Mvc.Core/src/ModelBinding/Binders/CollectionModelBinder.cs#L135 not sure what was the reason behind this but I believe we should make it smarter and leverage the default value when it is is available.

Since you are exploring solutions, if you are interested, you are very welcome to contribute to the repo with this fix. I can help you to get it done.

**Comment by Lyra2108** [comment]
I am interested in a fix and would love to do it. Unfortunately I am currently quite busy with the migration of an .Net-Framework 4.6.2 WCF SOAP/REST service to .Net6 and my colleagues and me are behind schedule. So I am afraid I will not manage to contribute the fix for the next couple of weeks. :/

**Comment by Lyra2108** [comment]
@brunolins16 It looks like I can manage to do the fix in two to three weeks from now. Is there anything which would be good for me to read/set up to get started on a fix?

**Comment by brunolins16** [comment]
@Lyra2108 sorry about that, but I was looking into the issue to provide you some guidance and I found a very small change that could fix the issue. I went ahead and sent a PR 😅.

You are very welcome to contribute if you still have time, here is a list of issue where you can find one that you might be interested in: https://github.com/dotnet/aspnetcore/labels/help%20wanted.
