### ISSUE TITLE
Blazor Wasm Published Failed with Lazy Loading

### ISSUE THREAD

**Issue by shujamughal** [dotnet/aspnetcore#42336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,
I am using the following command to publish the Blazor Wasm Standalone Application however it is failing and by looking error, it looks like due to lazy loading assemblies.

The error is given below

C:\Program Files\dotnet\sdk\6.0.106\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(532,5): error BLAZORSDK1001: Unable to find 'Microsoft.EntityFrameworkCore.Relational.dll;System.Private.Xml.dll;System.Text.Encoding.CodePages.dll;Microsoft.EntityFrameworkCore.dll;Microsoft.Identity.Client.dll;System.Data.Common.dll;Microsoft.IdentityModel.Tokens.dll;System.Private.DataContractSerialization.dll;Newtonsoft.Json.dll;System.Linq.Expressions.dll;Microsoft.EntityFrameworkCore.SqlServer.dll;Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project. [D:\Products\sukhdari\Sukhdari\Sukhdari_Client\Sukhdari_Client.csproj]

and the command to publish is as follow.

dotnet publish -c Release -r linux-x64

Please let me know how to publish with lazy loading enabled?

### Expected Behavior

The publication step should be completed without any error.

### .NET Version

6.0.106

### Anything else?

VS Code

**Comment by javiercn** [comment]
@shujamughal thanks for contacting us.

Could you provide a minimal project as a public github repository that reproduces the issue so that we could make progress in determining what is going on here?

**Comment by shujamughal** [comment]
Hi,

Please fine the link of public repo at following link

run the above-mentioned command in the Sukhdari Client Project and you will get the same error as I mentioned above. If you remove the lazy loading from the project then it works

https://github.com/shujamughal/Sukhdari/tree/master/Sukhdari_Client

**Comment by TanayParikh** [comment]
Hey @shujamughal, thanks for reaching out and providing the repro. I took a look, and as the error message suggests:

> Confirm that project or package references are included **and the reference is used in the project**

(emphasis added).

I removed the unused references from the lazy loading:

```xml

  <ItemGroup>
    <!-- <BlazorWebAssemblyLazyLoad Include="Microsoft.EntityFrameworkCore.Relational.dll" /> -->
    <BlazorWebAssemblyLazyLoad Include="System.Private.Xml.dll" />
    <!-- <BlazorWebAssemblyLazyLoad Include="System.Text.Encoding.CodePages.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.EntityFrameworkCore.dll" />
    <BlazorWebAssemblyLazyLoad Include="Microsoft.Identity.Client.dll" /> -->
    <BlazorWebAssemblyLazyLoad Include="System.Data.Common.dll" />
    <!-- <BlazorWebAssemblyLazyLoad Include="Microsoft.IdentityModel.Tokens.dll" /> -->
    <!-- <BlazorWebAssemblyLazyLoad Include="System.Private.DataContractSerialization.dll" /> -->
    <BlazorWebAssemblyLazyLoad Include="Newtonsoft.Json.dll" />
    <BlazorWebAssemblyLazyLoad Include="System.Linq.Expressions.dll" />
    <!-- <BlazorWebAssemblyLazyLoad Include="Microsoft.EntityFrameworkCore.SqlServer.dll" /> -->
    <!-- <BlazorWebAssemblyLazyLoad Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll" /> -->
  
  </ItemGroup>
```

[here](https://github.com/shujamughal/Sukhdari/blob/a5c8c50d55b50dd503a2e7ea1b59273d53cdbf15/Sukhdari_Client/Sukhdari_Client.csproj#L25-L39)

and things are now building as expected.

Also note, you can simplify the [logic in `App.razor`](https://github.com/shujamughal/Sukhdari/blob/a5c8c50d55b50dd503a2e7ea1b59273d53cdbf15/Sukhdari_Client/App.razor#L29-L36) to load the assemblies at once, and you'll have to ensure the lazy loaded assemblies are added.

```csharp
                var assemblies = await AssemblyLoader.LoadAssembliesAsync(
                    new[] { "System.Private.Xml.dll", "System.Data.Common.dll", "Newtonsoft.Json.dll", "System.Linq.Expressions.dll" }
                );
                lazyLoadedAssemblies.AddRange(assemblies);
```

The [lazy loading documentation](https://docs.microsoft.com/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-6.0#complete-example) provides further guidance and details.
