### ISSUE TITLE
signalr data deposition

### ISSUE THREAD

**Issue by khoatbd55** [dotnet/aspnetcore#42402]
I'm using asp.net core signalr to send real-time data. I have written a runtime service that collects client's data to the hub and then distributes it from the hub to another client. But is suffering from data stagnation in the hub's queue. That is, when the client connects to the hub to get data, it sometimes loses data for 1,2 minutes, then 40.50 messages continuously shoot down from the hub while their data is very stable without such loss of connection. Have any of you encountered this situation?

**Comment by rafikiassumani-msft** [comment]
@khoatbd55 Can you provide a GitHub repo to help us reproduce this issue?
