### ISSUE TITLE
Blazor, during the first visit, the page loads twice

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#42400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The problem occurs on the Blazor Server Side. If we enter the website, it loads statically for the first time, everything is fine. Then the next loading is dynamic.
Video: (Test network Fast 3G)
https://www.awesomescreenshot.com/video/9628814?key=df3856b7747e341d4c44c561c7887af2
https://gyazo.com/42990466ec4368bb980f71a65c40c981

During the first charge
![image](https://user-images.githubusercontent.com/42449535/175515134-d99101b9-2a3d-4ddb-a4eb-9d8ee0a97a82.png)

Then the sida server immediately loads
![image](https://user-images.githubusercontent.com/42449535/175515152-e181e321-0753-478c-8aae-bc905454a57e.png)

I noticed that in this case there are even 3 page loads ...

This problem occurs everywhere, even in the clean design created by vs.

URL page:
https://[instytutkrypto.pl](https://instytutkrypto.pl/)/

What could it be? How to prevent this from happening? I once saw a tutorial on this but only for wasm.

### Expected Behavior

The page should load once, not jump.

### .NET Version

.net core 7 preview 5

**Comment by yugabe** [comment]
Once during prerendering, once after. This is by design.

[Relevant docs.](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-initialization-oninitializedasync)

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

This is currently by design. There is an issue to change how this work that can be found here https://github.com/dotnet/aspnetcore/issues/15317

I would suggest you upvote that issue instead.

**Comment by Alerinos** [comment]
@yugabe 

![image](https://user-images.githubusercontent.com/42449535/175524615-b9110be3-9983-4ed1-bcc7-9d317ac8ff2c.png)
If I set the method not asynchronous, my code will not execute.

@javiercn 
I gave a thumbs up. In my opinion, the .net 7 version should be catching up, not creating minimal interfaces and things that are not must-have.

Do you have any idea / method to fix this problem quickly? Unfortunately, I can't call a non-async method.

**Comment by javiercn** [comment]
@Alerinos I would suggest you check https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#persist-prerendered-state
