### ISSUE TITLE
Change DefaultFiles/DirectoryBrowser/StaticFileMiddleware to only no-op if there's an active endpoint with a non-null RequestDelegate

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#42413]
The `DefaultFilesMiddleware`, `DirectoryBrowserMiddleware`, and `StaticFileMiddleware` currently no-op (fall through to the next middleware in the pipeline) if they detect the request has an active endpoint ([see code here](https://github.com/dotnet/aspnetcore/blob/3f2ea7d91442fdf56eebf116f6e7099a8bb08d9f/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L95)).

This prevents the middleware from running even in cases where there's an endpoint with a `null` `RequestDelegate`. This prevents the ability to have an active endpoint for the purposes of communicating metadata to middleware while allowing middleware like the `StaticFileMiddleware` to keep performing its function, e.g. have a "dummy" endpoint to carry `IAuthorizeData` metadata so that the `AuthorizationMiddleware` performs authorization on a request before the `StaticFileMiddleware` runs ([example here](https://github.com/DamianEdwards/AspNetCorePathAuthorization)).

We should consider updating the check in these middleware to instead only no-op if the active endpoint's request delegate is null, i.e.:

```csharp
// Return true because we only want to run if there is no endpoint request delegate.
private static bool ValidateNoEndpointRequestDelegate(HttpContext context) => context.GetEndpoint()?.RequestDelegate == null;
```

If there are other middleware with similar behavior we should consider updating those in a similar fashion.

**Comment by DamianEdwards** [comment]
@Tratcher @davidfowl @JamesNK any thoughts if this would cause any issues?

**Comment by Tratcher** [comment]
Could RequestDelegate ever be null before?

**Comment by DamianEdwards** [comment]
`Endpoint.RequestDelegate` is marked as nullable, so yes?

**Comment by Tratcher** [comment]
Sure, but in practice where there any situations where it was null that we would now handle differently?

**Comment by DamianEdwards** [comment]
Not that I'm aware of, but that's impossible to prove absolutely. Is your question basically "Are there cases where the middleware would now start handling the request where before it didn't?"

**Comment by Tratcher** [comment]
Right. If a null RequestDelegate was common for some situation before, those requests could now collide with StaticFiles. If this wasn't a pattern we saw in use before then the change is harmless.

**Comment by DamianEdwards** [comment]
I'll let the others chime in on that then, given I only found out today that `Endpoint.RequestDelegate` could even be `null` 😃

**Comment by davidfowl** [comment]
I am supportive of this change. It opens up something we're trying to do with endpoints and policies. An endpoint without a request delegate is pretty rare which is why I feel comfortable taking this one. It is a breaking change though, so maybe its worth documenting anyways.

**Comment by wtgodbe** [comment]
> Do we feel it warrants an appcontext switch (I'm guessing... no)?

Triage - we don't think it needs one. If we can get this in for preview7 without breaking anybody, we say go ahead
