### ISSUE TITLE
blazor webassembly project can't run in .net7

### ISSUE THREAD

**Issue by coader** [dotnet/aspnetcore#42421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use default template to create new blazor webassembly project, choose .net 7 preview 5
after build & run, nothing show in page and got this error:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

7.0.100-preview.5.22307.18

**Comment by TanayParikh** [comment]
Hi @coader, thanks for reaching out. This is due to a known issue with Preview 5. I'd recommend downloading Preview 4, 6 or 7 from the GitHub.com/dotnet/installer repo. That should resolve your issue.

**Comment by SNiedinger** [comment]
I got the same error after manually upgrading my proj files from "6.0.6" to "7.0.0-preview.5.*"
I fixed it by deleting obj and bin folder files.

**Comment by revbones-duplicate** [comment]
Still happening in .NET 7 preview 6

**Comment by TanayParikh** [comment]
> Still happening in .NET 7 preview 6

Can you please confirm if you're experiencing this issue on a brand new blazor webassembly project as well?

**Comment by TanayParikh** [comment]
If people are still experiencing this issue, please try @SNiedinger's suggestion above:

> I fixed it by deleting obj and bin folder files.

If that doesn't resolve the issue, please let us know by creating a new issue, and linking this issue.
