### ISSUE TITLE
The code is not compiled

### ISSUE THREAD

**Issue by Mr0N** [dotnet/aspnetcore#42426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/61237140/175786546-e95105d1-d9db-4746-a9ad-5fed5e38d49b.png)
The code is not compiled

### Expected Behavior

-

### Steps To Reproduce

-

### Exceptions (if any)

-

### .NET Version

6

### Anything else?

-

**Comment by Mr0N** [comment]
ASP .Net Core MVC

**Comment by Mr0N** [comment]
Razor

**Comment by davidfowl** [comment]
There's not enough information here to help.

**Comment by Mr0N** [comment]
http://data-point.com.ua/ all source code html

**Comment by KristofferStrube** [comment]
We still need to know more about what the problem is, what you expect to happen, and if possible some minimal reproducible example.

Are you wishing to reproduce the linked website or is there some part of the site that doesn't work as expected currently?

**Comment by Mr0N** [comment]
> Нам все еще нужно знать больше о том, в чем проблема, что вы ожидаете, и, если возможно, какой-нибудь минимальный воспроизводимый пример.
> 
> Вы хотите воспроизвести связанный веб-сайт или какая-то часть сайта в настоящее время не работает должным образом?

![image](https://user-images.githubusercontent.com/61237140/175807099-f69eea01-26b4-46e6-82f9-4abea896adfb.png)
![image](https://user-images.githubusercontent.com/61237140/175807120-8669eef2-5efc-4e1a-929a-79b300ea9ff9.png)

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/175807257-319a0b1c-8f41-4cfd-b5f9-0652d0e58ea8.png)

**Comment by Mr0N** [comment]
The form is generated from above, not from below

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/175807318-499ada82-69df-463f-a076-ace50e5dfa3d.png)

**Comment by KristofferStrube** [comment]
*Just to restate the problem to others:*
They have a form on their site that uses the [FORM tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0) to submit some contact information.
The tag helper has not generated the result that they intended.

I think the problem is that you have not specified a method for the form. You should do something like this.
```razor
<form asp-action="Send" asp-controller="Message" method="post">
...
</form>
```

**Comment by Mr0N** [comment]
> 

![image](https://user-images.githubusercontent.com/61237140/175807826-6ba76027-06b5-49a8-ae63-4d9eb6cd42d7.png)

**Comment by KristofferStrube** [comment]
Okay, then I don't know.
If you want the best chances of getting help then you can share code samples (not in the form of screenshots) and even better would be a link to a minimal codebase where the issue is reproduced.

**Comment by Mr0N** [comment]
> Okay, then I don't know. If you want the best chances of getting help then you can share code samples (not in the form of screenshots) and even better would be a link to a minimal codebase where the issue is reproduced.

It seems to me razor can not just parse html, the browser can because its logic is such that everything should work under any conditions

**Comment by Mr0N** [comment]
Only it is not clear why razor does not throw any errors

**Comment by Mr0N** [comment]
> Okay, then I don't know. If you want the best chances of getting help then you can share code samples (not in the form of screenshots) and even better would be a link to a minimal codebase where the issue is reproduced.

The problem is in html because in one document, there are two forms, one works normally from above, the form from below does not work, I dropped html.

**Comment by antomys** [comment]
@Mr0N Please provide additional information. Especially where is `MessageController` exists, where is `Send` or `SendAsync` exists in this controller, etc. It would be cool if you provide additional information, because i personally have not faced this issue using this syntax in `.cshtml`.

**Comment by Mr0N** [comment]
> @Mr0N Please provide additional information. Especially whether `MessageController` exists, whether `Send` or `SendAsync` exists in this controller, etc. It would be cool if you provide additional information, because i personally have not faced this issue using this syntax in `.cshtml`.

![image](https://user-images.githubusercontent.com/61237140/175814511-8b694805-37f0-49a0-a118-22fc9f80856c.png)

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/175814524-117541fc-c683-4ade-bb38-e6127844d3c9.png)

**Comment by antomys** [comment]
So i've tested two approaches (see screenshot). Everything seems to work fine (screenshot below). I'm assuming there is a problem in your code, not in .net. Please make sure that you do refer to the existing method in an existing controller and building an object right.
![Screenshot 2022-06-26 at 15 53 40](https://user-images.githubusercontent.com/50595040/175815127-28f10f2a-41fe-4673-a90a-548de6a13dcf.png)

Also providing controller logic (for getting references how it works)
![Screenshot 2022-06-26 at 15 54 34](https://user-images.githubusercontent.com/50595040/175815161-305509b8-b557-4296-aae6-b2ef2da84880.png)


@Mr0N fyi

**Comment by javiercn** [comment]
@Mr0N very likely you are missing `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` within the page or within _ViewStart.cshtml

**Comment by Mr0N** [comment]
> @Mr0N very likely you are missing `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` within the page or within _ViewStart.cshtml

What is this for, the document has 3 forms, two are normally generated, the third is not, all forms are the same

**Comment by Mr0N** [comment]
are generated using attributes

**Comment by Mr0N** [comment]
> @Mr0N could you provide a minimal repro project as a public github repository so that we can make progress in understanding what the problem is?

I will not download the source code, but I don’t want to make an example because it takes a long time, you can try to make an example yourself, I downloaded the html for this

**Comment by viacheslav-boiko** [comment]
Dear dear Mister. I guess the strict way of speaking event with bot - is a not good approach to fix your problem. Really there are not enough details for us. You left Expected Behavior, Steps To Reproduce and other important stuff out. It's not good. Think more, provide more details and I believe you will be helped. Good luck

**Comment by Mr0N** [comment]
-

**Comment by Mr0N** [comment]
Clode

**Comment by Mr0N** [comment]
https://github.com/Mr0N/ExampleASP 
Example

**Comment by Mr0N** [comment]
https://github.com/Mr0N/ExampleASP
Example

**Comment by javiercn** [comment]
@Mr0N thanks for the additional details.

You have a bug in your code `<div data-bg="url('/img/men.jpg" ')"` should be `                            <div data-bg="url('/img/men.jpg')"` on line 150 of your index.cshtml

**Comment by Mr0N** [comment]
> 

Why didn't the compiler tell me about this?

**Comment by Mr0N** [comment]
> 

it does not work, there is an asp attribute in the code that does not exist
