### ISSUE TITLE
Member-level trimming breaks ASP.NET tracing instrumentation

### ISSUE THREAD

**Issue by kerams** [dotnet/aspnetcore#42434]
### Description

Traces produced by OpenTelemetry instrumentation for ASP.NET (`AddOpenTelemetryTracing`) lack almost all expected data when running an application with member-level trimming enabled. `AddHttpClientInstrumentation` does not seem to be affected.

### Reproduction Steps

Create a Kestrel server serving favicon.png. Set the following in the project file:

```
<TargetFramework>net7.0</TargetFramework>
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>link</TrimMode>
```

Set up OpenTelemtry instrumentation for [ASP.NET](https://opentelemetry.io/docs/instrumentation/net/automatic/), send it to Jaeger (or use the console exporter).

Publish as self-contained for win-x64 (also reproducible for linux-musl-x64), run.

Send a GET request for `/favicon.png`.

### Expected behavior

Span has the right display name and attributes.

![vivaldi_ha6f7DeNXm](https://user-images.githubusercontent.com/5063478/175785295-c68f6c20-f165-4dea-86b7-1d8fcf5eb3a5.png)

### Actual behavior

Span is for all intents and purposes empty.

![vivaldi_EqtZBT6RaV](https://user-images.githubusercontent.com/5063478/175785297-baa8a1a0-28f2-4ecf-8e16-9769c37903d2.png)

### Known Workarounds

Use `<TrimMode>copyused</TrimMode>`.

### Configuration

Built with SDK 7.0.100-preview.5.22307.18.
On Windows 10 running the self-contained executable.
On Linux running in Docker with base `mcr.microsoft.com/dotnet/runtime-deps:7.0.0-preview.5-alpine3.16`.

**Comment by vitek-karas** [comment]
@kerams you mention that you didn't get any warnings - that is very weird. Can you please make sure that you didn't disable them, typically via `SuppressTrimAnalysisWarnings` property?

**Comment by kerams** [comment]
@vitek-karas, I've tried creating a minimal C# repro (the solution where I noticed the problem is F#) and I do see the warnings. A similar minimal F# project does not seem to surface them. @vzarytovskii, could it be possible or am I doing something wrong?

The original issue still stands though, right? The trimming metadata is not 100% correct in some assembly, otherwise the latter would not be touched during trimming?

**Comment by vitek-karas** [comment]
The promise is only: If there are no warnings, the app should work when trimmed. If F# (or something there) disables the warnings, it probably shouldn't do that.

I vaguely remember that open telemetry specifically is relatively problematic for trimming, but I don't remember the details and if there were some potential solutions.

**Comment by kerams** [comment]
Ok, my misunderstanding lay in thinking that trimming only affected assemblies that include relevant metadata, and assemblies that are explicitly enumerated in project files with `TrimmableAssembly`.

Thanks, feel free to close this if there's nothing actionable here.

**Comment by vitek-karas** [comment]
"Trim safety" is a global problem. Currently we enable trimming on assemblies which themselves don't cause problems (or are correctly annotated), but it's a heuristic. If you have code in your app which uses reflection to reach into some private field of the framework type, it is likely to break - we would trim the framework type, potentially removing the field. That's where the warnings come in - those should work globally and should tell you that the reflection code which does this is problematic (if we can't figure it out).

**Comment by davidfowl** [comment]
> I vaguely remember that open telemetry specifically is relatively problematic for trimming, but I don't remember the details and if there were some potential solutions.

Diagnostic source is fundamentally not trim safe since it basically (https://github.com/dotnet/runtime/blob/475858d14c580a765c3e32cbb3f90cd5825e8b5c/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSource.cs#L19).

Most consumers of these events use reflection to consume the data to avoid versioning problems (e.g. https://github.com/open-telemetry/opentelemetry-dotnet/blob/f234829964a2e59078d3d02c1a881ff35ffd65b8/src/OpenTelemetry/DiagnosticSourceInstrumentation/PropertyFetcher.cs)

This type is doing reflection on the framework (which is marked trim safe) and it doesn't declare that it's doing that so as a result, these members disappear.

**Comment by davidfowl** [comment]
No, this should probably be in open telemetry but we should investigate and understand the repro first.

**Comment by JamesNK** [comment]
I repoed this with gRPC + OpenTelemetry + Zipkin

HttpClient is generating correct info with OT. I looked at what they're doing to still work and [DynamicDependency is added to HttpClient diagnostic source APIs](https://github.com/dotnet/runtime/blob/31164f445de0a0ebf9007c231c35f64e46c863db/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L217-L223) while we aren't (at least with these ones).

Updated: https://github.com/dotnet/aspnetcore/pull/42512

**Comment by JamesNK** [comment]
Verified as fixed with https://github.com/dotnet/aspnetcore/pull/42591.

![image](https://user-images.githubusercontent.com/303201/178096477-b3551fc3-45e7-430c-9806-143a4dcad19c.png)
