### ISSUE TITLE
Move OpenAPI extension methods to M.A.Builder namespace

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#42445]
## Background and Motivation

In preview4, we introduced support for an OpenAPI package that included extension methods on the then `RouteHandlerBuilder` (now `IEndpointBuilder`) for constructing an `OpenApiOperation` from an endpoint. These extension methods were placed in the `Microsoft.AspNetCore.OpenApi` namespace.

For consistency with the rest of the ecosystem, we want to move these extension methods to the Microsoft.AspNetCore.Builder namespace.

## Proposed API

```diff
- namespace Microsoft.AspNetCore.OpenApi;
+ namespace Microsoft.AspNetCore.Builder;

public static class OpenApiRouteHandlerBuilderExtensions
{
  ...
}
``` 

## Usage Examples
**Before Change**
```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.OpenApi;

var app = WebApplication.Create();
app.UseRequestDecompression();
app.MapGet("/", ...).WithOpenApi();
```

**With Change**
```csharp
using Microsoft.AspNetCore.Builder;
// No additional namespace references needed

var app = WebApplication.Create();
app.UseRequestDecompression();
app.MapGet("/", ...).WithOpenApi();
```

## Alternative Designs

Not applicable.

## Risks

None, API waas introduced in .NET 7 so no risk of breaking change and delta allows us to confirm with the standard for builder extension methods elsewhere.

**Comment by BrennanConroy** [comment]
API review notes:
- Noticed two `OpenApiRouteHandlerBuilderExtensions` types, let's rename this one to something like `OpenApiEndpointConventionBuilderExtensions`

```diff
+ namespace Microsoft.AspNetCore.Builder;

- public static class OpenApiRouteHandlerBuilderExtensions
+ public static class OpenApiEndpointConventionBuilderExtensions
{
  ...
}
``

API approved!
