### ISSUE TITLE
Add status code attribute 409 Conflict to DefaultApiConventions.Post

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#42467]
## Background and Motivation
`DefaultApiConventions.Post` includes status code 201 and 400 only but not 409 Conflict.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.defaultapiconventions.post?view=aspnetcore-6.0

## Proposed API
Add an attribute for status code 409 Conflict.
```diff
[Microsoft.AspNetCore.Mvc.ApiExplorer.ApiConventionNameMatch(Microsoft.AspNetCore.Mvc.ApiExplorer.ApiConventionNameMatchBehavior.Prefix)]
[Microsoft.AspNetCore.Mvc.ProducesDefaultResponseType]
[Microsoft.AspNetCore.Mvc.ProducesResponseType(201)]
[Microsoft.AspNetCore.Mvc.ProducesResponseType(400)]
+[Microsoft.AspNetCore.Mvc.ProducesResponseType(409)]
public static void Post (object model);
```

**Comment by rafikiassumani-msft** [comment]
@vanillajonathan Thank you for your request. Unfortunately, we are not planning to modify the default conventions as the changes will be breaking. You have a few options to consider: 

- Create your own default convention and add the status code 409 as describe in the following document: https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-6.0#create-web-api-conventions
- Copy the code in the `DefaultApiConventions.cs` class and modify it to fit your API scenarios https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Mvc/Mvc.Core/src/DefaultApiConventions.cs.

**Comment by vanillajonathan** [comment]
I am not sure how adding a status code to the default convention would be a breaking change.

**Comment by rafikiassumani-msft** [comment]
@vanillajonathan Adding an extra status code means all the generated OpenAPI docs will have the additional response status code during an upgrade to .net7. This will be an unintentional behavior for most users. It could also potentially impact client code generation.

**Comment by davidfowl** [comment]
We’re not going to remove the default convention, that’d be a big breaking change. It’s fine if you don’t agree with the defaults and have your own opinions though, that’s why we made it possible to define your own.
