### ISSUE TITLE
ClientAssets package beta not behaving as expected

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#42472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@javiercn I've implemented the section of your blog post about the ClientAssets beta that follows the "Reusing MsBuild code" to just try to build my css

1) In the blog post most of the first 'PropertyGroup' elements have improper closures, nothing serious that isn't easy to fix

2) When I run a build I see the 'npm install' run followed by my commands to build css, but then the 'npm install' runs again as does the build command, this time with an output parameter added to the npm command
```
1>> material.blazor@2.0.0 buildStaticWebAssetsCSS
1>> npm run build-css2&&npm run build-min-css2&npm run build-material-css2 "-o" "C:\\Solutions\\OHI\\Material.Blazor\\Material.Blazor\\obj\\Debug\\net6.0\\clientassets/"
```

3) To have separated css/js builds is it simply replicating the target NpmRunBuild step, changing files as needed?

### Expected Behavior

I don't expect the duplicate 'runs' of npm & build

### Steps To Reproduce

See bug description

### .NET Version

6.0.301

**Comment by javiercn** [comment]
@MarkStega can you point me to a branch?

**Comment by MarkStega** [comment]
@javiercn 

On my fork of material blazor (https://github.com/OptimiumHealth/Material.Blazor) there is a branch called StaticResources

**Comment by MarkStega** [comment]
After several hours of experimentation:

1) I am seeing two 'npm install' commands after renaming the targets but only one build. I 'swallowed' the error caused by the output path on the last npm command in the chain by adding '&&npm --version'

2) 'npm install' seems to always run on a build

3) The output files are not getting marked as content. For some reason, the clientassetsbuild.complete.txt file is going to the intermediate path, not the one that I specified.

The aforementioned branch is updated.

**Comment by MarkStega** [comment]
@javiercn I ended up having to use '.' as the staticassetsdirectory; Everything was fine when I was building css, but when I tried to build my typescript I ran afoul with includes. After several hours of trying to get the ts build to work I gave up, moved the directory to '.'.

The assets are being generated & stored in 'StaticAssets' (my version of 'dist') but still aren't getting tagged as content (same issue as #3 above I suspect).

**Comment by javiercn** [comment]
@MarkStega I'm a bit busy with other workitems, but I'll take a look at your solution when I can. @TanayParikh is going to be working in this area, so he'll have throughts as he works through the implementation for the actual SDK feature.

There might be bugs with the package, mainly because it is much harder to test (it essentially manual testing) compared to when the feature is built-in into the product where we already have the infrastructure to test all the MSBuild cases.

**Comment by MarkStega** [comment]
@javiercn No worries, look when you can, our current solution is OK even though we have extra copies of the web assets in the nuget package.

**Comment by mkArtakMSFT** [comment]
Closing this will be covered as part of https://github.com/dotnet/aspnetcore/issues/38445
