### ISSUE TITLE
Installer only get Shared in .\dotnet\shared\Microsoft.AspNetCore.App 

### ISSUE THREAD

**Issue by 1w1f** [dotnet/aspnetcore#42503]
after Intaller the result of    .\eng\build.cmd -buildInstallers in tag v6.0.0  ps: aspnetcore-runtime-6.0.0-dev-win-x64.msi 
I found a new folder  .dotnet\shared\Microsoft.AspNetCore.App\6.0.0 ,
but add a new web project is ref the framework in .dotnet\packs\Microsoft.AspNetCore.App.Ref
How to change to ref the framework I get from the Installer ?

**Comment by wtgodbe** [comment]
The assets at `.dotnet\shared\Microsoft.AspNetCore.App\6.0.0` are not what were installed by the `.msi` you mentioned - running that `.msi` will drop 6.0.0 assets in your `Program Files` directory. You also don't need to worry about `dotnet\packs\Microsoft.AspNetCore.App.Ref`, that comes from the repo build & is unrelated to the installers you produced.

You should just be able to run `dotnet new web` in a new cmd/powershell window after installing the .msi & it will pick up your newly installed Asp.Net Shared Framework.
