### ISSUE TITLE
https://github.com/dotnet/announcements/issues/222 issue -- 

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/aspnetcore#42507]
**Describe the bug:**

We are seeing this vulnerability https://github.com/dotnet/aspnetcore/issues/41609

**Version used:**

However, we already have the appropriate versions installed

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.420
 Commit:    c4a02e4c2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.420\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.409 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**To reproduce:**
This is what I am seeing on my VS 2019. Also, my windows is upto date.

**Expected behavior:**

**Actual behavior:**

**Additional context:**

**Comment by adityamandaleeka** [comment]
@ssarin3194 If you believe you've found a potential security issue, please email details to [secure@microsoft.com](mailto:secure@microsoft.com).

**Comment by ssarin3194** [comment]
@adityamandaleeka  the CG team has reported to update our packages. However, I see we already have the .net SDKs updated as expected.

**Comment by adityamandaleeka** [comment]
@ssarin3194 As I said above, please describe the security issue you're seeing to [secure@microsoft.com](mailto:secure@microsoft.com) who can help you with next steps. I'll close this issue now.
