### ISSUE TITLE
Blazor Drag and Drop broke between .NET Core 3.0 and .NET 6.0

### ISSUE THREAD

**Issue by clamchoda** [dotnet/aspnetcore#42517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I followed [Chris Saintys demo](https://chrissainty.com/investigating-drag-and-drop-with-blazor/) for drag and drop which was very clever.  I added the [polyfill](https://github.com/Bernardo-Castilho/dragdroptouch) to make the example work on mobile.

I use [Conveyor](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1448185.ConveyorbyKeyoti) to debug drag and drop on mobile and everything works great (Safari and Chrome on IOS mobile ). Unfortunately if I upgrade the demo to .NET 6.0 from .NET Core 3.0 the **@ondragstart** and **@ondrop** no longer fire on the mobile. It's odd that even though on mobile the events are ignored on blazor, they are still raised by javascript. Therefore the polyfill is still working.

**For example on mobile while the following javascript _dragstart_ is firing;**
```
document.addEventListener('dragstart', function(ev) {
    if (ev.target.classList.contains('draggable')) {
        console.log('dragging');
    } else {
        console.log('ignoring draggable');
    }
});
```
**The following blazor _dragstart_ is being ignored;**
```
<li class="draggable" draggable="true" title="@JobModel.Description" @ondragstart="@(() => HandleDragStart(JobModel))" >
    <p class="description">@JobModel.Description</p>
    <p class="last-updated"><small>Last Updated</small> @JobModel.LastUpdated.ToString("HH:mm.ss tt")</p>
</li>

@code {
    [CascadingParameter] JobsContainer Container { get; set; }
    [Parameter] public JobModel JobModel { get; set; }

    private void HandleDragStart(JobModel selectedJob)
    {
        Container.Payload = selectedJob;
    }
}
```

What could be causing this behavior by upgrading .NET versions?

**Note** that everything works perfectly fine on desktop versions in both .NET 6.0 and .NET Core 3.0.

### Expected Behavior

I expected the drag and drop to work in both .NET Core 3.0 and .NET 6.0.

### Steps To Reproduce

- download the source from his [git.](https://github.com/chrissainty/SimpleDragAndDropWithBlazor) 
- added the [polyfill](https://github.com/Bernardo-Castilho/dragdroptouch) to make the example work on mobile.
    - `<script id="DragDropTouch" src="https://bernardo-castilho.github.io/DragDropTouch/DragDropTouch.js"></script>`
- add javascript and invoking for monitoring events

**Javascript**
```
function InitDrag()
{
    document.addEventListener('dragstart', function(ev) {
        if (ev.target.classList.contains('draggable')) {
            console.log('dragging');
        } else {
            console.log('ignoring draggable');
        }
    });
}

```

**Index.razor**
```
[Inject] IJSRuntime JS { get; set; }
protected override async Task OnAfterRenderAsync(bool firstRender)
{
     await JS.InvokeVoidAsync("InitDrag");
}
```

Everything works fine in mobile Safari and Chrome in .NET Core 3.0. If you upgrade to .NET 6.0 you will see that only the javascript events are being fired. Therefore the drag and drop no longer works.

### Exceptions (if any)

none, just missing events.

### .NET Version

6.0.300-preview.22204.3

### Anything else?

iOS 14.8

**Comment by javiercn** [comment]
@clamchoda thanks for contacting us.

Could you provide a minimal repro project as a public GitHub repo that we can use to make progress on this issue?

**Comment by clamchoda** [comment]
@javiercn sure thing!

[BlazorTouchEventsNet](https://github.com/clamchoda/BlazorTouchEventsNet) - Drag and drop events **not** working on mobile (.NET 6.0).
[BlazorTouchEventsNetCore](https://github.com/clamchoda/BlazorTouchEventsNetCore) - Drag and drop events working on mobile (.NET Core 3.1)

Both projects are a copy and paste of the same projects except ones built in .NET 6.0 and the other .NET Core 3.1. 

When you drag the item labeled _Description 1_ from one box to another I expect two alerts to be raised from events. A drop event raised from javascript and a drop event raised from blazor;

- _"Dropped handled on js."_
- _"Dropped handled on blazor."_

 On desktop Chrome _(Version 103.0.5060.66 (Official Build) (64-bit))_ both events are raised as expected. On mobile Chrome and Safari _(iOS Version 14.8)_ both events are only raised in the [BlazorTouchEventsNetCore](https://github.com/clamchoda/BlazorTouchEventsNetCore) project using .NET Core 3.1. In the [BlazorTouchEventsNet](https://github.com/clamchoda/BlazorTouchEventsNet) - project using .NET 6.0 on mobile, only the javascript event is raised.

**Comment by clamchoda** [comment]
My apologies. It was the polyfill. Fix for .NET 6.0 can be found here: https://github.com/dotnet/aspnetcore/issues/41394#issuecomment-1113146280

**Comment by javiercn** [comment]
@clamchoda no worries, I'm glad that you were able to figure it out.
