### ISSUE TITLE
Add Microsoft.AspNetCore.Server.Kestrel.Core to default namespaces

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#42516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The `HttpProtocols` enum is in this namespace. Configuring Kestrel protocols in code is ugly:

```cs
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel(c =>
{
    c.ListenLocalhost(50009, listner =>
    {
        listner.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http3;
        listner.UseHttps();
    });
});
var app = builder.Build();
```

### Describe the solution you'd like

Add Microsoft.AspNetCore.Server.Kestrel.Core to default namespaces.

There isn't much in it: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core?view=aspnetcore-6.0

And there doesn't appear to be any conflicts on the name `HttpsProtocols` in .NET APIs: https://docs.microsoft.com/en-us/dotnet/api/?term=HttpProtocols

**Comment by adityamandaleeka** [comment]
Triage: this seems fairly low-value, especially once H3 gets enabled by default.
