### ISSUE TITLE
Single-file components - @css block in .razor

### ISSUE THREAD

**Issue by gulbanana** [dotnet/aspnetcore#42525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

It's extremely common to have a .razor file and associated .razor.css. The CSS isolation feature transforms the styles you write into scoped versions which operate only within the styled razor component, but you still need to switch between separate files. Razor components already combine HTML and C#, optionally allowing the C# code to be moved into a code-behind .razor.cs file - but for simple components, it's easier to keep it in a @code block. How about adding the same feature for styles? 

```razor
@code {
    void OnClick() => Console.WriteLine("Clicked!");
}

@css {
    .layout {
        display: flex;
        flex-direction: column;
    }
    a:hover { 
        font-weight: bold; 
    }
}

<div class="layout">
    <button @onclick="OnClick">Click me</button>
    <a @onclick="OnClick">Or click me</a>
</div>
```

We'd be able to write really concise components that have styling and interaction defined right there in the same source file. This is the approach used by Vue.js, and it produces very maintainable code.

**Comment by Xyncgas** [comment]
Related https://github.com/dotnet/aspnetcore/issues/33361#issuecomment-857283047

**Comment by Xyncgas** [comment]
I think it would be helpful to do something simple within one file

**Comment by javiercn** [comment]
@gulbanana thanks for contacting us.

This is not a direction we plan to move on the near future. It involves a non-trivial amount of compiler work compared to the benefits we think this brings.

**Comment by Xyncgas** [comment]
Return of investment imo is what a lot of people in the dotnet team thinks because they are working for microsoft, I understand. I want to get better in coding with dotnet to work on these things myself.

**Comment by gulbanana** [comment]
> This is not a direction we plan to move on the near future. It involves a non-trivial amount of compiler work compared to the benefits we think this brings.

Understood. I just wanted to make sure the idea is out there :)
