### ISSUE TITLE
Analyzer: Detect using Task<T> with RequestDelegate

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#42523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

`RequestDelegate` can be used with methods/lambdas that return a value which is then ignored.

Delegate signature:
https://github.com/dotnet/aspnetcore/blob/86c7e0100ab40a19fcccf6ee80550b44e8e62444/src/Http/Http.Abstractions/src/RequestDelegate.cs#L6-L11

Because `Task` is the base type of `Task<T>`, generic variance means it's possible to do this:
```cs
Task<string> HelloWorld(HttpContext c) => Task.FromResult("Hello " + c.Request.RouteValues["name"]);

// The compiler prefers RequestDelegate overload over the Delegate overload.
// The return value is never used. Not what the user expects.
endpoints.MapGet("/", HelloWorld);
```

Example: https://github.com/dotnet/aspnetcore/issues/39956

### Describe the solution you'd like

Write an analyzer that detects using a method or lambda that returns `Task<T>` with `RequestDelegate` and warns the user.

**Comment by martincostello** [comment]
Same as #36408?

**Comment by JamesNK** [comment]
No.

Your analyzer issue is for checking what's passed to `Result.Ok` (and friends).
This analyzer issue is about using a method that returns `Task<T>` with `RequestDelegate`.
