### ISSUE TITLE
LeakTrackingObjectPool does not report leaks because it only throws in Microsoft's own debug builds

### ISSUE THREAD

**Issue by Jehoel** [dotnet/aspnetcore#42524]
### Is there an existing issue for this?

- [X] I have searched the existing issues ([no other issues mention `LeakTrackingObjectPool`](https://github.com/dotnet/aspnetcore/issues?q=LeakTrackingObjectPool))

### Describe the bug

The `LeakTrackingObjectPool<T>` ([which is in this repo](https://github.com/dotnet/aspnetcore/tree/4094430163458ac10f42736daba09bdec4d0dffc/src/ObjectPool/src) instead of `dotnet/runtime`) is intended to call `Debug.Fail` if a rented pooled object is ever finalized without being explicitly returned back to the pool. This is implemented by using `ConditionalWeakTable` with its nested class (`LeakTrackingObjectPool<T>.Tracker`).

Because this checker (ab)uses finalizers for error-reporting it [cannot throw an exception due to complications](https://stackoverflow.com/questions/20358401/throwing-exception-in-finalizer-to-enforce-dispose-calls) but instead calls `Debug.Fail`, which should at-least alert the programmer when debugging an application.

...except it doesn't, because `Debug.Fail` call-sites are elided by the `csc` compiler (not the JIT) unless in a `DEBUG` build - and unfortunately the `Microsoft.Extensions.ObjectPool.dll` binaries we're all using are all built as `RELEASE` builds, so the `Tracker.~Tracker()` finalizer is effectively giant NOOP...

...this is what we see in ILSpy:

![image](https://user-images.githubusercontent.com/1693078/176865779-4644c157-83ce-40dd-a13e-dc34cf7cb36d.png)

As the call to `Debug.Fail` would be present in the CIL in a `DEBUG` build I expected the `Microsoft.Extensions.ObjectPool` NuGet package to include a debug build of the `.dll`, but no such assembly is present inside the `.nupkg` file. The `.nuspec` file does not mention any debug details either - in fact, I can't see how to get a debug build of this at all.

### Expected Behavior

I expected _something_ to happen when debugging when intentionally leaking pool resources in my own `DEBUG` builds, but nothing happened because the `Tracker.~Tracker()` finalizer is always a NOOP.

### Steps To Reproduce

This program reproduces the problem (the lack of an errror when debugging in the stock `LeakTrackingObjectPoolProvider` and also demonstrates it working as-intended in Debug builds with a tweaked opy+paste implementation.

```csharp
void Main()
{
	RunDefault(); // <-- this should throw or otherwise fail in Debug mode, but it does not.
	
	RunMine(); // <-- This reimplementation *does* fail, as-expected.
	
	String x = "foo";
}

static void RunDefault()
{
	ObjectPoolProvider        innerDefault             = new DefaultObjectPoolProvider();
	ObjectPoolProvider        leakTrackingPoolProvider = new LeakTrackingObjectPoolProvider( innerDefault );
	ObjectPool<StringBuilder> sbPool                   = leakTrackingPoolProvider.CreateStringBuilderPool();

	Rent3ButReturn1( sbPool );

	Stopwatch sw = Stopwatch.StartNew();

	GC.Collect();

	TimeSpan t1 = sw.Elapsed;

	GC.WaitForPendingFinalizers();

	TimeSpan t2 = sw.Elapsed;

	String x = "foo";
}

static void RunMine()
{
	ObjectPoolProvider        innerDefault             = new DefaultObjectPoolProvider();
	ObjectPoolProvider        leakTrackingPoolProvider = new MyLeakTrackingObjectPoolProvider( innerDefault );
	ObjectPool<StringBuilder> sbPool                   = leakTrackingPoolProvider.CreateStringBuilderPool();

	Rent3ButReturn1( sbPool );

	Stopwatch sw = Stopwatch.StartNew();

	GC.Collect();

	TimeSpan t1 = sw.Elapsed;

	GC.WaitForPendingFinalizers();

	TimeSpan t2 = sw.Elapsed;

	String x = "foo";
}

static void Rent3ButReturn1( ObjectPool<StringBuilder> sbPool )
{
	StringBuilder sb1 = sbPool.Get();
	StringBuilder sb2 = sbPool.Get();
	StringBuilder sb3 = sbPool.Get();
	
	sbPool.Return( sb2 );
}

//

public class MyLeakTrackingObjectPoolProvider : ObjectPoolProvider
{
	private readonly ObjectPoolProvider inner;
	
	public MyLeakTrackingObjectPoolProvider( ObjectPoolProvider inner )
	{
		this.inner = inner;
	}
	
	public override ObjectPool<T> Create<T>( IPooledObjectPolicy<T> policy )
	{
		ObjectPool<T> pool = this.inner.Create( policy );
		
		return new MyLeakTrackingObjectPool<T>( pool );
	}
}

public class MyLeakTrackingObjectPool<T> : ObjectPool<T> where T : class
{
	private readonly ConditionalWeakTable<T, Tracker> trackers = new ConditionalWeakTable<T, Tracker>();
	private readonly ObjectPool<T> inner;

	public MyLeakTrackingObjectPool( ObjectPool<T> inner )
	{
		this.inner = inner ?? throw new ArgumentNullException(nameof(inner));
	}

	/// <inheritdoc/>
	public override T Get()
	{
		T value = this.inner.Get();
		this.trackers.Add(value, new Tracker());
		return value;
	}

	public override void Return(T obj)
	{
		if (this.trackers.TryGetValue(obj, out var tracker))
		{
			this.trackers.Remove(obj);
			tracker.Dispose();
		}

		this.inner.Return(obj);
	}

	private sealed class Tracker : IDisposable
	{
		private readonly String  stack;
		private		     Boolean isDisposed;

		public Tracker()
		{
			this.stack = Environment.StackTrace;
		}

		public void Dispose()
		{
			this.isDisposed = true;
			GC.SuppressFinalize(this);
		}

		~Tracker()
		{
			if (!this.isDisposed && !Environment.HasShutdownStarted)
			{
				String msg = $"{typeof(T).Name} was leaked. Created at: {Environment.NewLine}{this.stack}";
				throw new InvalidOperationException(msg);
//				Debug.Fail(msg);
			}
		}
	}
}
```

### .NET Version

.NET 6.0.6

### Anything else?

* The quick-fix would be to change the call to `Debug.Fail` to `Environment.FastFail` so it will always work regardless if whether `Microsoft.Extensions.ObjectPool` is a Release or Debug build.
* However as-it-is, the `LeakTrackingObjectPool`  type really should expose a method to allow consumers to check for leaks and throw a (catchable) exception - or return false - instead of abusing finalizers.
* ...and make `LeakTrackingObjectPool` implement `IDisposable` too, and have its own `Dispose` method throw if there are any leaked objects.
* And document the package too: [right now the documentation is completely empty](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.objectpool.leaktrackingobjectpool-1) :(

**Comment by adityamandaleeka** [comment]
Triage: it's unclear if this is used anywhere... we should just obsolete it.

**Comment by Jehoel** [comment]
@adityamandaleeka If `LeakTrackingObjectPool` worked correctly I would find it useful in my own projects - that's how I found this bug, in fact. Unless there's a better way to determine if a pooled object was never returned?

**Comment by adityamandaleeka** [comment]
@Jehoel Since we don't use this anywhere (and we know nobody is depending on it since it doesn't even work in the builds we ship) it doesn't make sense for us to maintain it as public API surface, which is why we are choosing to mark it obsolete.

You are welcome to copy the code and adapt it to your needs (the suggestions you had above seem reasonable).
