### ISSUE TITLE
Multiple login page for redirect

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/aspnetcore#42531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, in MVC/razor page authorization, you can configure only one login page to redirect for all types of users. There is no way to configure different login pages for different roles(or policies) of users. 

### Describe the solution you'd like

```c#
builder.Services.ConfigureApplicationCookie(options => 
{
    options.Events.OnRedirectToLogin = async context =>
    {
        // provide appropriate data about the roles and policies that the user didn't have in context obj 
        // using that data it can be determined where to redirect
    };
});
```

**Comment by blowdart** [comment]
I'm confused about how you would expect this to work.

OnRedirectToLogin happens when a user is anonymous and is trying to access a resource that requires authentication.

At that point there are no roles or policies that can be applied, because there is no user instance because they haven't logged in.

What would you expect to branch on?

**Comment by ziaulhasanhamim** [comment]
I want to branch depending on the Roles/Policies property on AuthorizeAttribute

**Comment by blowdart** [comment]
But you don't have roles or things to check in policies if the user isn't logged in, because there are no roles, or user properties.

Are you thinking about something like a multi-tenant scenario where you have a custom login page based on an application property or the URL?

**Comment by ziaulhasanhamim** [comment]
> But you don't have roles or things to check in policies if the user isn't logged in, because there are no roles, or user properties.

I'm talking about required roles, not user roles.
```c#
[Authorize(Roles = "Admin")] // This role. Provide this in that callback
public classs CreateModel : PageModel
{
}
```
```c#
builder.Services.ConfigureApplicationCookie(options => 
{
    options.Events.OnRedirectToLogin = async context =>
    {
        context.RequiredRoles // maybe
    };
});
```
This is so that multiple login pages can be used

**Comment by blowdart** [comment]
So if you hit a page requiring an administrator you'd redirect to an administrator specific login page?

What would be different? Some sort of text saying "Please login with an administrator account"? To me that is a small information leak, you'd be telling anyone the requirements to hit a page, and worse, you'd probably want to reject users who don't qualify during the login, so user account enumeration attacks would also start to reveal internal roles.

It's not something we support, nor do I feel it's something we should support.

**Comment by ziaulhasanhamim** [comment]
Yeah got the point

**Comment by blowdart** [comment]
Thank you for giving me some new to think about today, I've had fun pondering this.
