### ISSUE TITLE
chinese characters shows ascii code in web page,

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42541]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/chinese-characters-shows-ascii-code-in-w/10070599)._

---
I have a website witata.com. It is developed with asp.net core mvc6. I open the web page source and find many Chinese characters to show ASCII code. Those are from Controller. other Chinese characters are written in _Layout.cshtml can be shown normally.  
you can get the attach file from web pages.

How can I show normally all Chinese characters coming from controller?

thank you very much!

---
#### Feedback Bot on 6/15/2022, 01:24 AM: 

(private comment, text removed)
#### Feedback Bot on 6/15/2022, 02:41 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Xyncgas** [comment]
it look normal to me
