### ISSUE TITLE
Page Flashing After Initial Load

### ISSUE THREAD

**Issue by RoyIL** [dotnet/aspnetcore#42544]
### Describe the bug

After the initial page load (i.e. the first time the page is loaded), the Blazor Server website seems to render twice, which creates a weird flickering/flashing effect. Has anyone experience a similar issue before, and is there any way to solve it within the current limitations of Blazor?

### Expected Behavior

Page loads without flashing/flickering, even if it is going to take more time to load.

### .NET Version

6.0.301

### Anything else?

https://user-images.githubusercontent.com/18168368/176953431-849bb8c9-b207-4340-b32d-9fa546f2730e.mp4

**Comment by Xyncgas** [comment]
it's normal because blazor updates DOM, instead of providing a static page

**Comment by RoyIL** [comment]
Well, the weird thing is that the flashing happens even when the render mode is set to render-mode="Server" in the _Host.cshtml file. Alsom @Xyncgas, would you know of any good way to implement that?

**Comment by javiercn** [comment]
@RoyIL thanks for contacting us.

That's expected since the initial render doesn't include content as you are using `render-mode="Server"`

**Comment by RoyIL** [comment]
Hi @javiercn, thanks for your comment! It's actually seems to work the other way around for me! When the render-mode is set to `Server` and I persist the application state, the flashing seems to almost disappear. 

However, when the render-mode is set to `ServerPrerendered` and I attempt to persist the application state, the flashing keeps occurring! Prior to opening this issue, I only attempted persisting the state with the `ServerPrerendered` mode.
