### ISSUE TITLE
Unable to access created Subfolder or razor page under page in ASP.NETCore

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42540]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-access-created-Subfolder-or-ra/10074684)._

---
[severity:It's more difficult to complete my work]
I can't seem to access any newly created razor page in my Pages folder of the ASP.NET CORE project I am currently working on. The project runs okay with the index showing, but when i added a new folder(Categories) under the pages and added a razor page(Index) under the Categories I can't locate the index page under the Categories even after replacing the privacy under the _layout to be `<a class="nav-link text-dark">Categories</a>`, clicking the categories just refreshes homepage. I created a "view" razor page directly under the pages folder and I still can't access the view too even after directly trying to access it using "https://localhost:7113/View" it gives me a "This localhost page can’t be found No webpage was found for the web address: https://localhost:7113/View"

---
#### Feedback Bot on 6/19/2022, 08:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
You might be missing a `@page` attribute on the page. Also, it looks like your `<a>` tag is missing an `href` attribute.

If these suggestions do not resolve your issue, would you please share a minimal, public GitHub project that demonstrates your issue? Thanks!
