### ISSUE TITLE
RequestAborted token should stay identical once retrieved

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/aspnetcore#42547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The HttpContext.RequestAborted token cannot be reread after it was triggered.

The relevant code lives here:

https://github.com/dotnet/aspnetcore/blob/b9fcd82fe9d0883e9828864a8e8b2231f469254f/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L285-L295

There are two scenario's to consider:

1. _connectionAborted is true and _abortedCts was never allocated, this should stay as is today, as an optimization.
2. _connectionAborted is true but `_abortedCts` was also already allocated, this should instead return `_abortedCts.Token`, not `CancellationToken(true)`.

The behavior today is problematic is because it hinders filtering out any `OperationCancelledException` caused by a cancelled request. And in our case we need to distinguish between it and other causes. As it stands we need to capture and flow the token as another parameter to the relevant exception filtering code while it also has access to the HttpContext, where it should just be able to reread RequestAborted.

**Comment by Tratcher** [comment]
UsePathBase _moves_ the given prefix from Path to PathBase, if present.
https://github.com/dotnet/aspnetcore/blob/c094384b2d119e147a205851e7f457149c3bbfb8/src/Http/Http.Abstractions/src/Extensions/UsePathBaseMiddleware.cs#L49-L61

Assigning PathBase does not modify the Path.

**Comment by adityamandaleeka** [comment]
We should return the existing `_abortedCts` if it's not null at this point:
https://github.com/dotnet/aspnetcore/blob/b9fcd82fe9d0883e9828864a8e8b2231f469254f/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L284-L288

And we'd also need to stop nulling out the `_abortedCts` in `CancelRequestAbortedTokenCallback`.
