### ISSUE TITLE
Swagger does NOT work with non-'/' path base

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#42559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Relevant to https://github.com/dotnet/aspnetcore/issues/42553
```
    app.UseSwagger().UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint($"{pathBase}/swagger/v6.0/swagger.json", "AspNetCoreWebApi V6.0");
    });
```
Tried both `app.UsePathBase()` and the following code:
```
app.Use(async (context, next) =>
    {
          context.Request.PathBase = new PathString(pathBase); // Kubernetes ingress rule. This works.
          await next(context);
    }
```
Swagger UI does not use the PATH_BASE as configured to reach the API endponts.
![Screenshot from 2022-07-04 13-20-17](https://user-images.githubusercontent.com/3871483/177088736-f4b9fd22-ad23-417c-be44-e243bce72127.png)

### Expected Behavior

Swagger to use configured PATH_BASE to reach API endpoints.

### .NET Version

6.0.301

**Comment by rafikiassumani-msft** [comment]
@khteh Thank you for reporting this issue. We believe this is an issue in the Swashbuckle code.  Feel free to create an issue at the following [repository](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues) or use the following existing issue to track progress: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1253
