### ISSUE TITLE
Blazor: virtualization on grid flickering

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/aspnetcore#42552]
I've seen some issues already but all of them are closed. however when I use a grid or a flex that has 3 columns in a row everything flickers.

I'm not sure why this happens but when I use one column so every element is stacked vertically it works. 

**Not Working** (flickering not able to load any data)
Element | Element | Element

**Working**
Element
Element
Element

**Comment by MariovanZeist** [comment]
Hi @HeroinGyrl 
I would love to look at the problem, but I do not have enough information.
Could you provide a minimal GitHub repro, so we can better figure out what might be the issue?

**Comment by HeroinGyrl** [comment]
> Hi @HeroinGyrl I would love to look at the problem, but I do not have enough information. Could you provide a minimal GitHub repro, so we can better figure out what might be the issue?

I uploaded a test repo on https://github.com/HeroinGyrl/VirtualizeBugProof

everything will flicker and if you scroll down it's empty

**Comment by javiercn** [comment]
@HeroinGyrl I believe Virtualize needs fixed size items.

/cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
That's correct. You can have as many columns as you like, but you need them to be in a fixed-height container element.

**Comment by HeroinGyrl** [comment]
I added a fixed height but it still flickers?

```cs
<div class="grid grid-cols-5 h-[400px] overflow-x-hidden">
    <Virtualize Items="TestList" Context="a">
        <div class="p-5 bg-slate-500 rounded-lg shadow-lg h-20">
            <p>@a</p>
        </div>
    </Virtualize>
</div>
```

Is there a code example I can take a look at.

**Comment by HeroinGyrl** [comment]
![Animation1](https://user-images.githubusercontent.com/33988671/177130479-50a07010-0e3c-400e-a906-e8442a5d0206.gif)

**Comment by MariovanZeist** [comment]
Thank you for the repo @HeroinGyrl 

The reason why it flickers is that you are using bootstrap's grid system to display 5 items on a single row.
This doesn't play nice with the fact that ``<virtualize>`` expects every item to be 1 single row.

Below's code has a working demonstration and will display 5 items on a single row 

```razor
@page "/"

<PageTitle>Index</PageTitle>

<Virtualize Items="TestList" Context="a">
    <div class="row">
        @foreach (var item in @a)
        {
            <div class="col p-5 bg-slate-500 rounded-lg shadow-lg" >
                <p>@item</p>
            </div>
        }
    </div>
</Virtualize>

@code {
    private List<IEnumerable<string>> TestList = new();

    protected override void OnInitialized()
    {
        for (int i = 0; i < 20; i++)
            TestList.Add(GetRow());
    }

    IEnumerable<string> GetRow()
    {
        var rows = new List<string>();
        for (int i = 0; i < 5; i++)
        {
            rows.Add(Guid.NewGuid().ToString());
        }
        return rows;
    }
}

```

**Comment by HeroinGyrl** [comment]
Awesome, it worked now, a bit complicated but at least it works.
