### ISSUE TITLE
Typo in ArgumentNullException.ThrowIfNull

### ISSUE THREAD

**Issue by iSazonov** [dotnet/aspnetcore#42558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Typo in:
https://github.com/dotnet/aspnetcore/blob/7bed0d138516191a916ec05beeb9ebe834ff0bca/src/Shared/PropertyAsParameterInfo.cs#L61-L70

### Expected Behavior

Must be:
```c#
        ArgumentNullException.ThrowIfNull(parameters, nameof(parameters));
        ArgumentNullException.ThrowIfNull(cache, nameof(cache));
```

**Comment by campersau** [comment]
This should work too:

```c#
     ArgumentNullException.ThrowIfNull(parameters); 
     ArgumentNullException.ThrowIfNull(cache); 
```

**Comment by javiercn** [comment]
@iSazonov thanks for contacting us.

Feel free to send us a PR
