### ISSUE TITLE
Additional Extensibility of `CreateHandler()` on `TestServer` 

### ISSUE THREAD

**Issue by justindbaur** [dotnet/aspnetcore#42567]
## Background and Motivation
When trying to make integration tests for a multi project application I sometimes have to have the projects talk to each other through [`HttpClient`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs). The existing [`WebApplicationFactory<TEntryPoint>`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs) has a helpful method [`CreateDefaultClient()`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L473-L500) among others for giving you an `HttpClient` that mocks the behavior of your request and sends it through your application as an [`HttpContext`](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/HttpContext.cs). This makes it so that a user can create the client use it as a mock response to [`IHttpClientFactory.CreateClient()`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/IHttpClientFactory.cs#L36). Then your application is able to communicate with another instance of [`TestServer`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs) so long as all communication is done through [`IHttpClientFactory`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/IHttpClientFactory.cs). 

The problem: The `HttpClient` created by `TestServer` lacks some extensibility points that make it unusable in it's current form for my usage. I need to be able to set the [`HttpContext.Connection.RemoteIpAddress`](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Features/HttpConnectionFeature.cs#L23). While it is great that there is a [`TestServer.SendAsync(Action<HttpContext>)`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs#L193-L220) method given so that you are able to set more of these underlying features it means I can't use `WebApplicationFactory<TEntryPoint>.CreateDefaultClient()` and its underlying handler [`ClientHandler`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/ClientHandler.cs) and would have to create my own implementations much like the ones you have with only minor changes so I can use it to mock returns from `IHttpClientFactory.CreateClient()`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.TestHost;

public class TestServer : IServer
{
+   public HttpMessageHandler CreateHandler(Action<HttpContext> configureContext);
}

public class ClientHandler : HttpMessageHandler
{
+   private readonly Action<HttpContext> _additionalContextConfiguration;

+   internal ClientHandler(PathString pathPase, ApplicationWrapper application, Action<HttpContext> additionalContextConfiguration);

    public override async Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        ...
        contextBuilder.Configure((context, reader) =>
        {
            ...
        }

        // Much like: https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs#L217
+       contextBuilder.Configure((context, reader) => _additionalContextConfiguration(context));

        var response = new HttpResponseMessage();
        ...
    }
}
```

## Usage Examples

```csharp
var handler = testServer.CreateHandler(context =>
{
    context.Connection.RemoteIpAddress = IPAddress.Parse("1.1.1.1");
});
var httpClient = new HttpClient(handler);
```
## Alternative Designs

I had also thought about an option to help set the initial feature collection of `DefaultHttpContext` but wasn't as big of a fan since the builder would then override some of those features and the user could find that quite annoying. 

```diff
namespace Microsoft.AspNetCore.TestHost;

public class TestServer : IServer
{
+   public HttpMessageHandler CreateHandler(IFeatureCollection initialHttpContextFeatures);
}

public class ClientHandler : HttpMessageHandler
{
+   private readonly IFeatureCollection _initialHttpContextFeatures;

+   internal ClientHandler(PathString pathPase, ApplicationWrapper application, IFeatureCollection initialHttpContextFeatures);
}

internal sealed class HttpContextBuilder : IHttpBodyControlFeature, IHttpResetFeature
{
+   internal HttpContextBuilder(ApplicationWrapper application, bool allowSynchronousIO, bool preserveExecutionContext, IFeatureCollection initialHttpContextFeatures)
    {
        ...
-       _httpContext = new DefaultHttpContext();
+       _httpContext = new DefaultHttpContext(initialHttpContextFeatures)
        ...
    }
}
```

## Risks

The main issue I see is that users could use it to set and remove things that are already set by the default behavior and this could mean that it would then fail to return a good response. But that is already the case of `TestServer.SendAsync(Action<HttpContext>)`. A user could mess it up so that the Content they supplied to the `HttpRequestMessage` is no longer used and the call doesn't have a body anymore but they would have done that to themselves. And this is why I propose only putting this extensibility point on the `CreateHandler` method. Anyone looking to create the handler themselves is probably looking to do something a little fancier than just `CreateClient()` and they may be less likely to trip over themselves. 

I don't believe there would have to be any breaking changes, the change to the constructor is done on an internal constructor so no one should be consuming it anyways. But also we could just add another construct that defaults the `additionalContextConfiguration` to a no op `_ => { }`. The other possibility is that someone already has an extension method like this but I could not find any with the same signature on grep.app. 

I also don't believe that there would be any noticeable performance regression. If people do not use the extra configuration the code would execute a method that does nothing and has no closures but if you utilize it then the performance regression would come only from the user.

**Comment by halter73** [comment]
API Review Notes:

- Awesome proposal. Simple and elegant.

If you want to submit a PR with a test @justindbaur, we'd welcome it.

It might be possible to use this to clean up some of our existing tests that previously had to use lower level HttpContext feature-based TestServer APIs. This doesn't have to be done as part of the initial change though.
