### ISSUE TITLE
Can't open multiple windows from blazor server.

### ISSUE THREAD

**Issue by anirugu** [dotnet/aspnetcore#42570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I write automation in Blazor. Through code, I make calls to API, bring data, and open the page in a browser.  I need to open multiple pages at once. 

I make a call to API, bring the data and in loop, I am opening a page. This is only work for 1 time. I tried to change idenitifier as well for `JSRuntime.InvokeAsync<string>(item.id, $"https://abcd.jobs{item.job_path}", "_blank").GetAwaiter().GetResult();`

I tried to use OnAfterRender(bool firstRender) OnInitializedAsync() etc. I am only able to open 1 page. I am not getting any error. What could be better way to make it work. Should I write javascript and opening by call there or I can do same without js.

### Expected Behavior

foreach loop should be able to open all the pages

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/35772421/177261091-1090205d-385b-406f-be77-9190a3dc7d80.png)

I have attached screenshot for given issue.

### Exceptions (if any)

I didn't see any exception.

### .NET Version

7.0.100-preview.5.22307.18

### Anything else?

I have compiled it against the latest preview.

**Comment by javiercn** [comment]
Thanks for contacting us @anirugu.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by anirugu** [comment]
@javiercn  Thanks for reply,  I reported it as bug since I only see it's opening window once, I was thinking as it's happening due to idenitifier must be unique. When I change them I still see it's opening once. 

The issue is I am not able to open the multiple window using forach loop, although code is look ok but it's not working.
