### ISSUE TITLE
Blazor Wasm Microsoft.JSInterop.JSException: Could not find 'blazorCulture.get'

### ISSUE THREAD

**Issue by EmilAlipiev** [dotnet/aspnetcore#42574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have same error as reported before here https://github.com/dotnet/aspnetcore/issues/22417 

![image](https://user-images.githubusercontent.com/10422347/177299382-3f79ccdb-fd31-4640-b33e-8b4e4916f69e.png)

unfortunately @huazhenhz didnt write his solution if he ever found one and issue was closed that cannot comment thats why
I am reopening this because a lot of research and trying but cannot find the solution. Either there is a bug or documentation is incomplete. 

In the other issue @mkArtakMSFT mentioned that configuration step is missing but I am not sure which one he means. Under the [Dynamically set the culture by user preference](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1&pivots=webassembly#dynamically-set-the-culture-by-user-preference-2) is mentioned any specific configuration but only code which I have used exactly 100% as in the documentation.

### Expected Behavior

that it doesnt return any js error

### Steps To Reproduce

Configuration in .csproj file

```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>false</InvariantGlobalization>
		<UseRazorSourceGenerator>false</UseRazorSourceGenerator>
		<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
		<BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>
```

in the program.cs of the client
```

builder.Services.AddLocalization();

var host = builder.Build();

CultureInfo culture;
var js = host.Services.GetRequiredService<IJSRuntime>();
var result = await js.InvokeAsync<string>("blazorCulture.get");

if (result != null)
{
    culture = new CultureInfo(result);
}
else
{
    culture = new CultureInfo("en-US");
    await js.InvokeVoidAsync("blazorCulture.set", "en-US");
}

CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;

await host.RunAsync();



```

in the Index.html  or I tried also in seperate .js file but doesnt make difference

```
<script>
  window.blazorCulture = {
    get: () => window.localStorage['BlazorCulture'],
    set: (value) => window.localStorage['BlazorCulture'] = value
  };
</script>
```

It works fine but when changing the language and calling   `Nav.NavigateTo(Nav.Uri, forceLoad: true);`
causes program.cs to be re-executed and then this error is showing that cannot find blazorculture.get js function. 

```
private CultureInfo Culture
    {
        get => CultureInfo.CurrentCulture;
        set
        {
            if (CultureInfo.CurrentCulture != value)
            {
                var js = (IJSInProcessRuntime)JS;
                js.InvokeVoid("blazorCulture.set", value.Name);

                Nav.NavigateTo(Nav.Uri, forceLoad: true);
            }
        }
    }
```

it is not happening everytime but randomly. I am not sure if that can be also related to invoking the js as Async. But when i check with f12 on the browser i can see that js is loaded fine. 

### .NET Version

6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It feels to us that this is a timing issue and due to how the script is being loaded, the script runs before Blazor is being loaded.
Anyway, to be certain, we will need a minimal repro project. Can you please create a new Blazor project and add only bits required for the repro. Host it as a public GitHub repo and share it.

**Comment by EmilAlipiev** [comment]
@mkArtakMSFT thats exactly what i thought also. i thought that it could be due to running InvokeVoidAsync and i have converted all those calls to InvokeVoid as sync. It seems that it reduced amount of errors but I am still getting occasionally this error. I will try to create a repro later soon.

**Comment by EmilAlipiev** [comment]
@mkArtakMSFT does that make sense to put cultureget.js and cultureset.js as first? I have just realized that I have those as last and if there are other js files in between to load and it takes time while Blazor in between already loaded? 

```
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="js/cultureget.js"></script>
    <script src="js/cultureset.js"></script>
```

**Comment by javiercn** [comment]
@EmilAlipiev I am not sure what you are trying to accomplish, however you should be able to do with with a JS initializer. Those allow you to run code before blazor starts and after blazor has started, so in your case, if you are calling JS interop during startup you can use an initializer to make sure that the script is setup at the correct time.
https://github.com/dotnet/aspnetcore/issues/38128
