### ISSUE TITLE
Expose RoutePatternFactory.Combine

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#42593]
## Background and Motivation

Custom EndpointDataSource implementations need the ability to combine route patterns with the group prefix for custom route grouping semantics.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Routing.Patterns;

public static class RoutePatternFactory
{
+    public static RoutePattern Combine(RoutePattern? left, RoutePattern right);
}
```

## Usage Examples

```csharp
var prefixPattern = RoutePatternFactory.Parse("/api");
var pattern = RoutePatternFactory.Parse("/products/{id}");
var combinedPattern = RoutePatternFactory.Combine(prefixPattern, pattern);
```

## Risks

None

**Comment by halter73** [comment]
API review notes:

1. This is very nice to have when writing your own `GetGroupedEndpoints` implementation in an `EndpointDataSource`.
2. Do we think `left` should be nullable? Yes. It's convenient when called from `Endpoints`.

API Approved!

```
namespace Microsoft.AspNetCore.Routing.Patterns;

public static class RoutePatternFactory
{
+    public static RoutePattern Combine(RoutePattern? left, RoutePattern right);
}
```

**Comment by davidfowl** [comment]
Fixed
