### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]       Unhandled exception rendering component: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by jkanamarlapudi** [dotnet/aspnetcore#42598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I delete a item from the MudTable and did call below lines it was throwing error.
```
await InvokeAsync(StateHasChanged);
await Table.ReloadServerData();
MudDialog.Cancel();
```

razor code:

`<MudTable ServerData="@(new Func<TableState, Task<TableData<Employee>>>(GetData))"
          Breakpoint="Breakpoint.None" Elevation="0" Striped="true" Class="mud-border single-action-button-table" @ref=_table>
    <ToolBarContent>
        @if (@Title)
        {
            <MudText Typo="Typo.h6">In review</MudText>
        }
        <MudTablePager InfoFormat="@($"Showing {infoFormat}")" />
    </ToolBarContent>
    <HeaderContent>
        <MudTh>Submitted</MudTh>
        <MudTh>Status</MudTh>
        <MudTh>Address</MudTh>
        <MudTh Class="button-td-1">Cancel</MudTh>
    </HeaderContent>
    <RowTemplate>
        <MudTd DataLabel="Submitted">@context.CreatedOnUtc?.ToDateTime().ToPacificDateString()</MudTd>
        <MudTd DataLabel="Status">
            <div class="status-container in-review">
                <MudIcon Icon="@Icons.Material.Filled.Circle" Title="Status" />
                In review
             </div>
        </MudTd>
        <MudTd DataLabel="Address">@context.Supply.UnparsedAddress</MudTd>
        <MudTd DataLabel="Cancel listing" Class="button-td-1">
            <MudIconButton OnClick="@(() => OpenCancelConfirmationDialog(context))" Icon="@Icons.Material.Filled.Cancel" aria-label="Cancel" Color="Color.Primary" />
        </MudTd>
    </RowTemplate>
    <NoRecordsContent>
        No Data
    </NoRecordsContent>
    <PagerContent>
        <MudTablePager PageSizeOptions="@_pageSizeOption" InfoFormat="@($"Showing {infoFormat}")" RowsPerPageString="Properties per page" />
    </PagerContent>
</MudTable>`

Error : 
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The given key '{ "id": 123456,..............,}' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2[[, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MudBlazor.MudTr, MudBlazor, Version=6.0.11.0, Culture=neutral, PublicKeyToken=null]].get_Item(SupplyLead key)
   at MudBlazor.TableContext`1[[Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Remove(MudTr row, Object item)
   at MudBlazor.MudTr.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)

### .NET Version

6.0

**Comment by jkanamarlapudi** [comment]
So anyone looking at this one yet ?

**Comment by javiercn** [comment]
@jkanamarlapudi thanks for contacting us.

That seems like an issue with the third-party component you are using. We would suggest you file an issue in their repo directly so that they can help you.

**Comment by javiercn** [comment]
@jkanamarlapudi this issue tracker is for issues related to the Blazor framework itself, we don't handle issues with third-party components. From what I can see in the callstack the issue you are having is originated somewhere in MudBlazor, hence why we are recommending you follow up with them.
