### ISSUE TITLE
Address dotnet-user-jwts prebuilt in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#42599]
dotnet-user-jwts is being reported as a prebuilt in .NET source-build.  This package needs to be built as part of source-build or the bundled global tool should be removed for source-build.  Looking at the dependencies in the [source](https://github.com/dotnet/aspnetcore/blob/main/src/Tools/dotnet-user-jwts/src/dotnet-user-jwts.csproj#L29), `System.IdentityModel.Tokens.Jwt` is concerning if the desire is to include it because this is not included in source-build and appears to come from a [repo](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) outside of the dotnet org.

See the source-build [repo guidance](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-dependencies.md) on how to handle new dependencies.

cc @dotnet/source-build-internal, @richlander, @omajid, @mmitche.

**Comment by captainsafia** [comment]
Re-opening since we still need to consume the new externals package in ASP.NET. Working on that now...
