### ISSUE TITLE
Support disabling auto-registering auth middlewares in WAB

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#42596]
## Background and Motivation

In preview5, we added support for automatically registering authentication and authorization middlewares in the WebApplicationBuilder when users have registered an authentication scheme. We want to provide an option for disabling this behavior for users who do not prefer it.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

namespace WebApplicationOptions
{
+ public bool DisableAutomaticAuthMiddlewareRegistration { get; init }
}
```

## Usage Examples

```csharp
var builder = WebApplication.CreateBuilder(new()
{
  DisableAutomaticAuthMiddlewareRegistration = true
});

builder.Services.AddAuthentication.AddJwtBearer();

var app = builder.Build();

// Will fail because middlewares have not been registered
app.MapGet("/foo", ...).RequireAuthorization();

app.Run();
```

Or more likely...

```csharp
var builder = WebApplication.CreateBuilder(new()
{
  DisableAutomaticAuthMiddlewareRegistration = true
});

builder.Services.AddAuthentication.AddJwtBearer();

var app = builder.Build();

app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/foo", ...).RequireAuthorization();

app.Run();
```

**Comment by halter73** [comment]
API Review Notes:

- Can this be a `WebHostDefaults` key that we read from config when constructing the WAB?
   - This feels more like something that is specific to how the application is written and not environmental.
- Do we need this?
  - If no endpoints require auth, is there really a problem?
  - It could break an app upgrading to 7 that used auth services but no middleware!?
  - This can be disabled with `IApplicationBuilder.Properties[SOME_UNDOCUMENTED_KEY]` if you really want.
