### ISSUE TITLE
ProtectedLocalStorage cannot be mocked for unit tests

### ISSUE THREAD

**Issue by rafaelf82** [dotnet/aspnetcore#42594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If we use Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedLocalStorage we cannot mock it for Unit Tests because the class is sealed.

Attempting to instantiate a ProtectedLocalStorage with mocked IJSRuntime and IDataProtectionProvider is also difficult, the steps I had to do are explained in this answer: https://stackoverflow.com/questions/71769067/mock-protectedsessionstorage-for-blazor/72887836#72887836

### Describe the solution you'd like

Make the class not sealed or implement an interface we can mock for testing.

### Additional context

Also, because ProtectedBrowserStorageResult has an internal constructor we can't Mock the GetAsync method of a ProtectedBrowserStorage.

**Comment by TanayParikh** [comment]
Hey @rafaelf82, thanks for getting in touch. I believe https://github.com/dotnet/aspnetcore/issues/25677 will resolve this issue.

**Comment by rafaelf82** [comment]
> Hey @rafaelf82, thanks for getting in touch. I believe #25677 will resolve this issue.

Definitely, thanks!
