### ISSUE TITLE
SignalR Core Nuget Package is deprecated?

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/aspnetcore#42601]
The nuget package shows as deprecated, supposedly as part of a deprecation effort for out-of-support, or abandoned packages. https://github.com/dotnet/announcements/issues/217

https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR

![image](https://user-images.githubusercontent.com/1400380/177632032-fd7883e1-7474-4f6a-8551-7bb805354fb5.png)

Is SignalR Core no longer maintained or abandoned? If not, what package are we supposed to be using...?

**Comment by BrennanConroy** [comment]
In 3.1 we moved to the "shared framework" concept. This made it so we don't need to release a lot of the packages that were released before and they are now included by default when you build an ASP.NET Core application. This is what happened to the SignalR server packages, they are now included in the shared framework and we no longer produce a standalone package.

Another common question is "how do I write a library for server applications that uses SignalR?". This can be done by adding a reference to the shared framework in your library. See https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio for details.
