### ISSUE TITLE
repeat audience property will be generate during using JwtSecurityToken class

### ISSUE THREAD

**Issue by CarlWhite2020** [dotnet/aspnetcore#42609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use JwtSecurityToken to generate new jwt token when token expired，but the new token will generate another repeate audience (aud) claim property in array.
`token = new JwtSecurityToken(
                issuer: ConfigUtil.GetValue("Jwt", "Issuer"),
                claims: claims,
                notBefore: DateTime.Now,
                audience: ConfigUtil.GetValue("Jwt", "Audience"),
                expires: DateTime.Now.AddDays(Convert.ToInt32(ConfigUtil.GetValue("Jwt", "Expired"))),
                signingCredentials: creds);`
![image](https://user-images.githubusercontent.com/62589030/177735335-fb68528a-8542-4c23-b80f-ab6d278023d4.png)

### .NET Version

NET6

**Comment by javiercn** [comment]
@CarlWhite2020 thanks for contacting us.

You will likely get a faster and better answer if you file this issue in the identity model repo https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet.
