### ISSUE TITLE
Use of [AsParameters] attribute

### ISSUE THREAD

**Issue by jaliyaudagedara** [dotnet/aspnetcore#42605]
.NET 7 Preview 5 has introduced `[AsParameters]` attribute.

But it's usage is only for ASP.NET Core Minimal APIs. `[AsParameters]` isn't working for classic approach (use of Controllers).

Do you think it's ideal to introduce new types that will work only when using Minimal APIs? If it's different technologies (Windows vs Web), that's completely understandable. Minimal APIs vs using Controllers are just different ways of writing APIs. I am thinking this is going to make things harder to follow. If it's working for classic controllers and not working for Minimal APIs, that again is understandable.

What do you think?

**Comment by brunolins16** [comment]
@jaliyaudagedara thanks for filing the issue.

I understand your point but there are several differences between MVC and Minimal APIs and this is one of them. Was decided to not make it available in MVC, since it is something that already works in MVC.

**Comment by campersau** [comment]
See also https://github.com/dotnet/aspnetcore/issues/42271

**Comment by jaliyaudagedara** [comment]
Yes, for MVC actions, we don't have to use `[AsParameters]` attribute. As long as the Model is not an abstract or value type, it gets bound based on other binding attributes (`FromHeader`, `FromQuery` etc.)

```
[ApiController]
[Route("[controller]")]
public class ToDosController : ControllerBase
{
    [HttpGet]
    public IActionResult Get([FromQuery] GetRequest getRequest)
    {
        return Ok();
    }
}

public record class GetRequest(int Offset, int Limit);

// GET: /Todos?offset=0&limit=10 -> getting bound
```

One important thing I am seeing in `AsParameters` is that it supports structs. And it's not supported with default model binding in MVC. I mean if I change the `GetRequest` to this, it won't work.

```
public record struct GetRequest(int Offset, int Limit);
```

In that case, shouldn't `[AsParameters]` be supported in MVC as well?
