### ISSUE TITLE
Blazor Server `FetchData` Page Missing `Authorize` Attribute

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#42615]
In the WASM template, the `FetchData` page has the `Authorize` attribute if authentication is enabled:

https://github.com/dotnet/aspnetcore/blob/202fafe68774e2a968d8b175c0fd3fb318778903/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Pages/FetchData.razor#L2-L11

We don't have this for Blazor Server:

https://github.com/dotnet/aspnetcore/blob/202fafe68774e2a968d8b175c0fd3fb318778903/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/FetchData.razor#L1-L3

We can use the `NoAuth` symbol to determine whether or not we want the attribute:

https://github.com/dotnet/aspnetcore/blob/202fafe68774e2a968d8b175c0fd3fb318778903/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/.template.config/template.json#L431-L434

**Comment by javiercn** [comment]
Very likely we didn't do this because we don't know where to / how to redirect
