### ISSUE TITLE
Model Binding in Razor Page

### ISSUE THREAD

**Issue by sxr1999** [dotnet/aspnetcore#42610]
I have a Razor Page project with a property of type `Dictionary<string, List<string>>` which represents chosen countries by continent. I would like to bind it to the value of a `<select>` control.

```
[BindProperty]
    public Dictionary<string, List<string>?> ChosenCountries { get; } = 
        new Dictionary<string, List<string>?>()
        {
            ["America"] = null
        };

   
    public List<string> Countries { get; } = new List<string>
    {
        "Mexico", "Canada", "USA"
    };
```

Here is my Page Code

```
@page
@model IndexModel

@if (Request.Method == "GET")
{
    
    <form method="POST">
        <select asp-items=@(new SelectList(Model.Countries)) data-placeholder="select a country" asp-for="@Model.ChosenCountries["America"]" >
            
        </select>
        <input  name="123" value="hello" type="hidden"/>
        
        <button>Submit</button>
    </form>
} 
```
<img width="557" alt="截屏2022-07-07 18 35 23" src="https://user-images.githubusercontent.com/83857035/177754136-aaca51b4-be26-4fef-bc49-9a783b075bab.png">

Now In the page, If i choose an option in `select`, It will bind normally.

<img width="1217" alt="截屏2022-07-07 18 32 05" src="https://user-images.githubusercontent.com/83857035/177754046-05f7dce6-d2c8-456e-ad1f-949dcf071ca1.png">

But, If i don't choose any options and submit directly, The `name` and `value` in `<input/>` will be  bound to this dictionary property. I don't understand why this happens , If I don't choose any options,  Shouldn't this dictionary property be null?
<img width="1419" alt="截屏2022-07-07 18 43 26" src="https://user-images.githubusercontent.com/83857035/177755561-2cdae1a8-edd7-4b22-aacf-dcceccbb86c3.png">

**Comment by mkArtakMSFT** [comment]
Looks like this has already been answered on StackOverflow already: https://stackoverflow.com/questions/72874900/asp-net-core-binding-dictionarystring-liststring-to-select-strange-resul

**Comment by Eilon** [comment]
@sxr1999 also one thing to try is to keep your existing code, but change the `[BindProperty]` to be this:

```c#
[BindProperty(Name = nameof(ChosenCountries))]
    public Dictionary<string, List<string>?> ChosenCountries ......
```

And perhaps setting `Name` explicitly will force the binding to only use that prefix.
