### ISSUE TITLE
WebASM-Blazor slices

### ISSUE THREAD

**Issue by YordanYanakiev** [dotnet/aspnetcore#42622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

A pieces of code encapsulated in WebASM which containing pieces of Blazor code, which can run inside the browsers as a services, which are doing specific background jobs if allowed with minimum possible resources ( or user defined resource volume ) - like:
- creating a popups or notifying by some why that something have changed in the site which they are belonging to.
- doing long running background tasks even with closed their owner site, while the browser is active.
- preloading content from the site which they are belonging to.
- wait in ready-to-act state from the site which they are belonging to, even if the site is closed, but the browser is active. ( like video call request, gaming invitations, etc.

**Comment by javiercn** [comment]
@YordanYanakiev thanks for contacting us.

This seems very close to https://github.com/dotnet/aspnetcore/issues/38128. I am going to mark this issue as dupe and would suggest you upvote that issue instead.

**Comment by YordanYanakiev** [comment]
It is completely unrelated.
I am speaking about isolated working on it's own service models.

**Comment by javiercn** [comment]
> It is completely unrelated.
> I am speaking about isolated working on it's own service-alike models which doesnt even need a document to run on.

I don't understand what you mean by this, could you define a concrete scenario and how would you expect it to work?

**Comment by YordanYanakiev** [comment]
For instance :
The client opens a page which having this small WebAsms. The Blazor page setup them to do things related to the page.
The client browser opening a confirmation for the user to allows a background services which will continue working on background even with the page closed.
When the user accept this - the browser creating a sandbox isolates space with specific, corresponding to the needs of the services and their granted permissions isolation level, and these webasm services start working on the client computer communicating with the page ( if available trough sockets for instance ) if available, or creating on their own page or windowses if needed to interact with the user.

**Comment by javiercn** [comment]
@YordanYanakiev thanks for the additional details.

This is not something we plan to do. The size and scope of this idea is not something we have the bandwidth nor have seen the community interest to push for. We don't build features that don't rely on browser standards that are widely supported across different browsers.

Even if we could spearhead something for chrome/edge, we wouldn't implement a feature if Safari or Firefox don't do so.
