### ISSUE TITLE
lowercase url configuration in .net 6 razorpages lacking capability

### ISSUE THREAD

**Issue by shearer3000** [dotnet/aspnetcore#42625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, RouteOptions has properties for LowercaseUrls and LowercaseQueryStrings, but doesn’t support the scenario of the url being in lowercase but with parameters remaining in their original format/verbatim. This is important when a parameter is case sensitive such as a cryptographically secure token. Currently, it will be emitted as lowercase also. 

For example (with LowercaseUrls set to true):
Expected: /sign-up/J8w5h7bzA5Mpc5jJN4Nxv2EY7DGMFeRNsaum0VhY
Actual: /sign-up/j8w5h7bza5mpc5jjn4nxv2ey7dgmfernsaum0vhy

### Describe the solution you'd like

Two solutions I can think of would be another property on RouteOptions that tells  the route generator not to alter parameter value casing if desired, or maybe even being able to define a casing constraint on the parameter in the route definition that the route generator would honour.

**Comment by javiercn** [comment]
@shearer3000 thanks for contacting us.

You should be able to override this behavior when you are generating the link, for example https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.controllerlinkgeneratorextensions.getpathbyaction?view=aspnetcore-6.0#microsoft-aspnetcore-routing-controllerlinkgeneratorextensions-getpathbyaction(microsoft-aspnetcore-routing-linkgenerator-microsoft-aspnetcore-http-httpcontext-system-string-system-string-system-object-system-nullable((microsoft-aspnetcore-http-pathstring))-microsoft-aspnetcore-http-fragmentstring-microsoft-aspnetcore-routing-linkoptions) allows your to pass the LinkOptions explicitly.
