### ISSUE TITLE
Scoped CSS import order is incorrect

### ISSUE THREAD

**Issue by uecasm** [dotnet/aspnetcore#42626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is somewhat of a sequel to #42332, but it is a separate problem.

Currently, when multiple RCL projects are in use within a project, the order in which the scoped CSS files are imported appears to be in name order.

### Expected Behavior

It should be in dependency order instead.  The order in which CSS files are imported is significant and it must be correct.

### Steps To Reproduce

1. Clone https://github.com/uecasm/CascadingStyles.git
2. Run and observe that the component background is orange when it is expected to be green.

This occurs because the imports in `Main.styles.css` are generated as:

```css
@import '_content/Child/Child.bundle.scp.css';
@import '_content/Grandchild/Grandchild.bundle.scp.css';
```

For correct behaviour, one of the following should happen instead:
1. `Main` should import only `Child`, and `Child`'s bundle should import `Grandchild` before adding its own rules.
2. `Main` should import `Grandchild` first since it is a dependency of `Child`.

(It should perhaps be noted that the `Child.styles.css` file does include the correct import, but this is omitted from the `Child.bundle.scp.css` file that actually ends up being imported by the main app.)

Granted, this is a highly contrived example since it's been reduced to an MCVE, but it is an entirely reasonable coding structure to define "default styles" in the grandchild component and then build a containing component that wants to re-use that component but with slightly different styling (and hence override the styles).  However this can't reliably occur unless the styles are imported in the correct order: most-dependent-first.  (Or unless the styles are overridden in the top-level unscoped CSS, but that breaks the Child RCL's scope.)

### .NET Version

6.0.300

### Anything else?

In this specific case, without any other changes, CSS Specificity can be used to produce correct behaviour, by altering the `ChildComponent.razor.css` file to use `.child ::deep .my-component` as its selector instead (adding `.child`), thus becoming a longer and more specific selector, which works even though imported in the "wrong" order.  But this should not be needed (and can be more tricky to do in the general case, as it's not always safe to add an outer div/class).

**Comment by javiercn** [comment]
@uecasm thanks for contacting us.

We don't define an order for the way scoped CSS project files are imported, that's by design. I am not 100% clear on what you are trying to achieve here, however, we consider the styles in each project bundle to be scoped to that project, and intentionally using `::deep` to escape that "sandbox" it is not something we want to consider.

There is no way to produce a correct order because you can have something like this in your graph:

```mermaid
stateDiagram-v2
    App --> ClassA
    App --> ClassB
    ClassB --> ClassC
    ClassA --> ClassC
```

and there is no way for us to know in which way to order ClassA and ClassB. in App imports.

The point being, you are responsible for your styles not escaping your project when you use `::deep` in the same way you are responsible when you use `unsafe` in C#. We don't implement an order because we can't guarantee a correct one, so we choose to order by name because it is as valid as any other option.

Hope this helps clarify things.

**Comment by uecasm** [comment]
No, that graph is not correct.  Main references a component in Child only.  And Child references a component in Grandchild only.  It is a simple dependency chain, not a loop.  Even the projects are a simple chain, there is no direct reference of Grandchild from Main.  There is no ambiguity, the current behaviour is simply incorrect.

But let me provide a more concrete example, then.  Someone creates a general component library, with for example a slider control, progress bar, etc.  Someone else wants to create an enhanced library that contains an "enhanced slider" or slider/progress combo control or something like that, but with slightly tweaked CSS styles to change the theme or resize some element beyond what the first library author originally anticipated.  Finally, an application author wants to use this enhanced control in their application.  But whoops, the styles are unpredictable and it breaks.

Surely you're not suggesting that Blazor is not intended to support composition of components and style adjustment, and the only correct solution would be to duplicate and rewrite the control instead of incorporating it?
