### ISSUE TITLE
Publishing Blazor Linux creates SHA-256 failures

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Publishing-Blazor-Linux-creates-SHA-256-/10078200)._

---
[regression] [worked-in:17.2.1]
A Blazor WASM no longer runs after building with the latest versions of .NET 6, to include the latest preview and the latest released version.  It will start, but it gives errors for various DLLs, all of them Nuget packages or framework files similar to: "Failed to find a valid digest in the 'integrity' attribute for resource 'https://192.168.1.250/_framework/System.Drawing.Common.dll' with computed SHA-256 integrity 'YuZXvPiqucu81zOCAO/J4dmwBOOzIRV70HfBYyGnIBo='. The resource has been blocked." 
We are currently targeting .NET 5.  The same error occurs when we target and use .NET 6. This happened to my entire team when we upgraded from various versions of 17.2 to 17.2.4.  It also effects 17.3 Preview 2.

Please advise.

---
#### Isaac Sherman on 6/22/2022, 02:09 PM: 

(private comment, text removed)
#### Feedback Bot on 6/22/2022, 08:11 PM: 

(private comment, text removed)
#### Isaac Sherman on 6/23/2022, 10:18 AM: 

(private comment, text removed)

---
#### Isaac Sherman solved on 6/22/2022, 02:10 PM, 0 votes: 

<p>[Workaround]<br>
The only workaround I’ve found that works is to roll back to .NET 5 and use it to build by employing the global.json file to target .NET SDK 5.0.408.  I have attempted rolling back .NET 6 to many of the available SDKs and none of them work.<br>
Attempting to use the available .NET 6 SDK fails.  We are still able to continue using Visual Studio 2022 with this workaround, but we are forced to use .NET 5 for publishing.</p>

**Comment by TanayParikh** [comment]
More context in original issue on VS Developer Community: https://developercommunity.visualstudio.com/t/Publishing-Blazor-Linux-creates-SHA-256-/10078200

**Comment by javiercn** [comment]
Thanks for contacting us. This might be related to your app. Could you add a minimal repro project that demonstrates the issue?

For reference, we tried to reproduce this with the out of the box template and inside a container and were not able to reproduce the issue.

**Comment by IsaacSherman** [comment]
Make sure when trying to reproduce that the template project is a Blazor WebAssembly App created by checking both the Configure for HTTPS and the Hosted in ASP NET.Core boxes, and further that the container is running Debian 10 to get as close as possible to our setup.  I'm unable to run in containers in my development environment, so reproduction with a small project may take me a while.  I have confirmed this happens when I publish to the target runtimes linux-64 and Portable.  I've attached a copy of our pubxml file to see if that helps reproduce the error.  
[PublishDebugRemote.pubxml.txt](https://github.com/dotnet/aspnetcore/files/9095956/PublishDebugRemote.pubxml.txt)

**Comment by javiercn** [comment]
> Make sure when trying to reproduce that the template project is a Blazor WebAssembly App created by checking both the Configure for HTTPS and the Hosted in ASP NET.Core boxes, and further that the container is running Debian 10 to get as close as possible to our setup. I'm unable to run in containers in my development environment, so reproduction with a small project may take me a while. I have confirmed this happens when I publish to the target runtimes linux-64 and Portable. I've attached a copy of our pubxml file to see if that helps reproduce the error.

we haven't been able to reproduce this issue, so unless we get a minimal repro project with detailed instructions on how to trigger the issue, there is nothing we can do about it.

Also, seems from your publish file that you are targeting .NET 5.0, which is out of support, so our first suggestion would be to update to a supported version.

**Comment by 2932** [comment]
তোমাকে চুতবো আমি
