### ISSUE TITLE
Introduce per-HealthCheck Delay and Period

### ISSUE THREAD

**Issue by francedot** [dotnet/aspnetcore#42645]
In the current implementation, delay, periodicity of the healthchecks are set at the `HealthCheckPublisherOptions` configuration level and shared among all the `HealthCheckRegistration`:

```csharp
builder.Services.Configure<HealthCheckPublisherOptions>(options =>
{
    options.Delay = TimeSpan.FromSeconds(10);
    options.Period = TimeSpan.FromSeconds(2);
});
```

API proposal is to introduce per-HealthCheck parameters to the `HealthCheckRegistration` used by `IHealthChecksBuilder.Add(HealthCheckRegistration registration)`. Here is an example of how the new flavor of HealthChecks would be used:

```csharp
builder.Services.AddHealthChecks()
   .Add(new HealthCheckRegistration(
               name: "SampleHealthCheck1",
               instance: new DelegateHealthCheck(_ => Task.FromResult(HealthCheckResult.Healthy(HealthyMessage))),
               failureStatus: null,
               tags: null,
               timeout: default,
               delay: TimeSpan.FromSeconds(40),
               period: TimeSpan.FromSeconds(30)));
```

### HealthCheckRegistration.cs

```diff

namespace Microsoft.Extensions.Diagnostics.HealthChecks;

public sealed class HealthCheckRegistration
{
     public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
+    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay);
+    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay, TimeSpan? period);
     public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
+    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay);
+    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay, TimeSpan? period);

+    public TimeSpan? Delay { get; }
+    public TimeSpan? Period { get; }
}

```

## Usage Examples

```csharp
builder.Services.AddHealthChecks()
   .Add(new HealthCheckRegistration(
               name: "SampleHealthCheck1",
               instance: new DelegateHealthCheck(_ => Task.FromResult(HealthCheckResult.Healthy(HealthyMessage))),
               failureStatus: null,
               tags: null,
               timeout: default,
               delay: TimeSpan.FromSeconds(40),
               period: TimeSpan.FromSeconds(30)));
```

## Alternative Designs

It might have been possible to implement HC periodicity by reusing the HC Registration Predicate delegate to condition the execution of the check instance i.e. `<Timer_Run> * MULTIPLIER < HC_Periodicity`. Although this would only to create HCs with periodicity set to a multiple of the default one.

## Risks

Performance regressions due to multiple timers introduction in `HealthCheckPublisherHostedService`.

**Comment by halter73** [comment]
API review notes:

- Let's make sure the proposed API matches the PR.
- Let's update the full proposed API to be a diff like the way the `HealthChecksBuilderDelegateExtensions.cs` section was edited.

**Comment by francedot** [comment]
> API review notes:
> 
> * Let's make sure the proposed API matches the PR.
> * Let's update the full proposed API to be a diff like the way the `HealthChecksBuilderDelegateExtensions.cs` section was edited.

These are now aligned with changes from related PR.

**Comment by halter73** [comment]
API Review Notes:

- Do we need to add "Individual" in the new API names, or can we add new overloads?
  - We are worried that this would be a source breaking change without a new method name.
  - But only for `AddIndividualTypeActivatedCheck`, so let's only keep that as a non-overload.
- Do we want to add new async callbacks that don't take a `CancellationToken`?
  - This is the existing pattern, but we don't want to continue doing this.
- Can we make `AddIndividualTypeActivatedCheck`'s `TimeSpan` parameters nullable?
- `Task` to `ValueTask` for `AddAsyncCheck` since the `Func` can probably complete immediately in many cases.

API Approved!

```diff

namespace Microsoft.Extensions.Diagnostics.HealthChecks;

public sealed class HealthCheckRegistration
{
     public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
+    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay, TimeSpan? period);
     public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
+    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout, TimeSpan? delay, TimeSpan? period);

+    public TimeSpan Delay { get; set; }
+    public TimeSpan Period { get; set; }
}

namespace Microsoft.Extensions.DependencyInjection;

public static HealthChecksBuilderAddCheckExtensions
{
     public static IHealthChecksBuilder AddCheck(this IHealthChecksBuilder builder, string name, IHealthCheck instance, HealthStatus? failureStatus = null, IEnumerable<string>? tags = null, TimeSpan? timeout = null);
+    public static IHealthChecksBuilder AddCheck(this IHealthChecksBuilder builder, string name, IHealthCheck instance, HealthStatus? failureStatus = null, IEnumerable<string>? tags = null, TimeSpan? timeout = null, TimeSpan? delay = null, TimeSpan? period = null);
+    public static IHealthChecksBuilder AddCheck<T>(this IHealthChecksBuilder builder, string name, HealthStatus? failureStatus = null, IEnumerable<string>? tags = null, TimeSpan? timeout = null, TimeSpan? delay = null, TimeSpan? period = null);
+    public static IHealthChecksBuilder AddIndividualTypeActivatedCheck<T>(this IHealthChecksBuilder builder, string name, HealthStatus? failureStatus, IEnumerable<string> tags, TimeSpan timeout, TimeSpan? delay, TimeSpan? period, params object[] args);
}

public static HealthChecksBuilderDelegateExtensions
{
     public static IHealthChecksBuilder AddCheck(this IHealthChecksBuilder builder, string name, Func<HealthCheckResult> check, IEnumerable<string>? tags = null, TimeSpan? timeout = default);
+    public static IHealthChecksBuilder AddAsyncCheck(this IHealthChecksBuilder builder, string name, Func<CancellationToken, ValueTask<HealthCheckResult>> check, IEnumerable<string>? tags = null, TimeSpan? timeout = null, TimeSpan? delay = null, TimeSpan? period = null);
+    public static IHealthChecksBuilder AddCheck(this IHealthChecksBuilder builder, string name, Func<HealthCheckResult> check, IEnumerable<string>? tags = null, TimeSpan? timeout = null, TimeSpan? delay = null, TimeSpan? period = null);
}
```

**Comment by captainsafia** [comment]
Triage: Adding the `api-needs-work` label to this given there are updates that need to be made to the spec.

**Comment by francedot** [comment]
Updated the API spec for review. Listing here a couple of thoughts on re-using the `HealthCheckPublisherOptions` in the `HealthCheckRegistration` and `AddCheck` APIs.

- There are now two ways to set the HC timeout, one being as the already-existing param to the `AddCheck`, and the other from `HealthCheckPublisherOptions`.
- The `Predicate` delegate of `HealthCheckPublisherOptions` might make sense to be used as a replacement to the abandoned `IsEnabled` prop - see https://github.com/dotnet/aspnetcore/issues/42939

**Comment by halter73** [comment]
> * There are now two ways to set the HC timeout, one being as the already-existing param to the `AddCheck`, and the other from `HealthCheckPublisherOptions`.

Good point. This is getting advanced enough that I'm wondering if we shouldn't just go back to adding `Delay` and `Period` properties the `HealthCheckRegistration`. Given that `IHealthChecksBuilder.Add(HealthCheckRegistration)` exists, maybe we don't even need to bother adding all the extension methods since this is a pretty advanced scenario. I think we could also clean things up by not adding any new constructors to `HealthCheckRegistration`. These could just be nullable settable (init only?) properties. Most of the properties are already settable anyway.

`IsEnabled` is a little trickier. If we go back to creating new API that doesn't reuse `HealthCheckPublisherOptions`, using callback like `Predictate` feels even worse. Having a running application react to a boolean property being set without any sort of change token is very non-standard though. I think that would break a lot of people's expectations about how the framework works.

Maybe we could add a `IHealthCheck.IsEnabled` property that defaults to always returning true?

**Comment by francedot** [comment]
> > * There are now two ways to set the HC timeout, one being as the already-existing param to the `AddCheck`, and the other from `HealthCheckPublisherOptions`.
> 
> Good point. This is getting advanced enough that I'm wondering if we shouldn't just go back to adding `Delay` and `Period` properties the `HealthCheckRegistration`. Given that `IHealthChecksBuilder.Add(HealthCheckRegistration)` exists, maybe we don't even need to bother adding all the extension methods since this is a pretty advanced scenario.

I like the proposal + nothing stops the consumers on replicating what we have already for the `AddCheck(..)`. If we go for this proposal we should better align the docs with this niche usage. 

> I think we could also clean things up by not adding any new constructors to `HealthCheckRegistration`. These could just be nullable settable (init only?) properties. Most of the properties are already settable anyway.

I am more in favor of providing all the cctors needed for a more fluent `IHealthChecksBuilder.Add(HealthCheckRegistration)` invocation. See usage example above.

**Comment by halter73** [comment]
> I am more in favor of providing all the cctors needed for an inline `IHealthChecksBuilder.Add(HealthCheckRegistration)` invocation:

What about doing something like the following for inline invocation?

```csharp
builder.Services.AddHealthChecks()
    .Add(
        new("SampleHealthCheck1", new DelegateHealthCheck(_ => Task.FromResult(HealthCheckResult.Healthy(HealthyMessage))))
        {
            Delay = TimeSpan.FromSeconds(40),
            Period = TimeSpan.FromSeconds(30),
        }));
```

We might also be able to enable selectively enabling HealthChecks as requested in #42939 by adding a new `HealthStatus`. I think this would be a bit cleaner than adding a `HealthCheckRegistration.IsEnabled` `Func<HealthCheckContext, bool>` as a property.

```diff
namespace Microsoft.Extensions.Diagnostics.HealthChecks;

public sealed class HealthCheckRegistration
{
+    public HealthCheckRegistration(string name, IHealthCheck instance);

    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags);
    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags);
    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);

    public Func<IServiceProvider, IHealthCheck> Factory { get; set; }
    public HealthStatus FailureStatus { get; set; }
    public TimeSpan Timeout { get; set; }
    public string Name { get; set; }
    public ISet<string> Tags { get; }

+    public TimeSpan Delay { get; set; }
+    public TimeSpan Period { get; set; }

//+    public Func<HealthCheckContext, bool> IsEnabled { get; set; } = () => true; // Should this be async?
}

public struct HealthCheckResult
{
    public HealthCheckResult(HealthStatus status, string? description = null, Exception? exception = null, IReadOnlyDictionary<string, object>? data = null);

    public IReadOnlyDictionary<string, object> Data { get; }
    public string? Description { get; }
    public Exception? Exception { get; }
    public HealthStatus Status { get; }

    public static HealthCheckResult Healthy(string? description = null, IReadOnlyDictionary<string, object>? data = null)
    public static HealthCheckResult Degraded(string? description = null, Exception? exception = null, IReadOnlyDictionary<string, object>? data = null);
    public static HealthCheckResult Unhealthy(string? description = null, Exception? exception = null, IReadOnlyDictionary<string, object>? data = null);

+    public static HealthCheckResult Disabled();
}

public enum HealthStatus
{
    Unhealthy = 0,
    Degraded = 1,
    Healthy = 2,
+    Disabled = 3, // Or -1?
}
```

We could also to the `IHealthCheck` interface. You wouldn't be able to selectively enable a `DelegateHealthCheck`, but this seems like a niche enough scenario that requiring the developer to implement `IHealthCheck` wouldn't be too onerous. It's a pretty simple interface, but IHealthCheck is in Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll which cross-targets netstandard.

```diff
public interface IHealthCheck
{
    Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default);

+ #if NETCOREAPP
+        bool IsEnabled(HealthCheckContext context) => true; // Should this be async?
+ #endif
}
```

**Comment by halter73** [comment]
API Review Notes:

- What about the new HealthCheckRegistration ctor? Why don't we take a factory instead? Let's hold off on the constructor since you can use existing ones and this is somewhat advanced.
- Should the new properties be nullable? Yes. Unlike `Timeout`, this falls back to the HealthCheckPublisherOptions when null.
- Do we need HealthStatus.Disabled? Maybe not. HealthStatus.Healthy might be sufficient to skip over things, and it's less likely to break existing code that does checks like `status != HealthStatus.Healthy`. We can keep https://github.com/dotnet/aspnetcore/issues/42939 open for now to track adding API for selectively enabling things.

```diff
namespace Microsoft.Extensions.Diagnostics.HealthChecks;

public sealed class HealthCheckRegistration
{
    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags);
    public HealthCheckRegistration(string name, IHealthCheck instance, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);
    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags);
    public HealthCheckRegistration(string name, Func<IServiceProvider, IHealthCheck> factory, HealthStatus? failureStatus, IEnumerable<string>? tags, TimeSpan? timeout);

    public Func<IServiceProvider, IHealthCheck> Factory { get; set; }
    public HealthStatus FailureStatus { get; set; }
    public TimeSpan Timeout { get; set; }
    public string Name { get; set; }
    public ISet<string> Tags { get; }

+    public TimeSpan Delay { get; set; }
+    public TimeSpan Period { get; set; }
}
```

API Approved!
