### ISSUE TITLE
Kestrel: Wrong certificate used

### ISSUE THREAD

**Issue by No1e** [dotnet/aspnetcore#42642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wrong certificate can be used for communication encryption when setting up certificate by using certificate subject.

### Expected Behavior

Correct certificate should be used.

### Steps To Reproduce

1. Create and install two certificates. 
- One with subject "CN=something.com"
- Another one with subject "CN=something.com, CN=somethingelse.com".

2. Set private key access to user, under which the web app will be running
3. In the appsettings.json, under Kester, specify the following configuration: 
    "Certificates": {
      "Default": {
        "Subject": "something.com",
        "Store": "My",
        "Location": "LocalMachine"
      }
    }
3. Second certificate is loaded, instead of the first one. API endpoints are not reachable. Furhtermore, there is even no error logs in this case.

### .NET Version

6.0.3

**Comment by Tratcher** [comment]
How is the system supposed to differentiate between the two? I think it's taking the first one it finds with a matching subject.

**Comment by blowdart** [comment]
As an aside [a certificate subject should only have one common name](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.6). You have an invalid certificate.

Multiple hosts are done using the SAN extension
