### ISSUE TITLE
Blazor Server silent connection crash when using InputFile Component

### ISSUE THREAD

**Issue by mhehle** [dotnet/aspnetcore#42656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you select more than 250 Files in `InputFile` Component In Blazor Server, the connection will crash silently. 
The specified InputFile `OnChange` method will not get called, there is no way to catch or handle the underlying error/exception.

This issue exists in a production environment with no debugger attatched.

### Expected Behavior

InputFile `OnChange` will get called, no connection crash.

### Steps To Reproduce

1. Execute `dotnet new blazorserver`
2. Go to Index page 
3. Add following sourcecode

```c#
<h3>Upload</h3>
<p>Please select 300 files to upload</p>
<InputFile OnChange="@UploadImages" multiple/>

@code
{
   private const int MaxFiles = 100;
    
    private void UploadImages(InputFileChangeEventArgs args)
    {
        try
        {
            var files = args.GetMultipleFiles(MaxFiles);
            foreach (var file in files)
            {
                Console.WriteLine(file.Name);
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
    }
}
```
4. Run project
5. Upload 300 files
6. Connection will crash

Demo repository: https://github.com/mhehle/BlazorServerInputFileComponentIssue

### .NET Version

Version: 6.0.3  Commit:  c24d9a9c91

**Comment by mhehle** [comment]
possible relevant issues:
- https://github.com/dotnet/aspnetcore/issues/26756
- https://github.com/dotnet/aspnetcore/issues/28547

**Comment by javiercn** [comment]
@mhehle thanks for contacting us.

Can you turn on the logs to debug level and paste what information you see on the console/log output?
Could you check on the browser logs to see any message that might be logged out in the client?

**Comment by javiercn** [comment]
@mhehle check appsettings.json because I think those might change the levels. There should be plenty of debug logs if you did this correctly.

I am going to go on a limb and theorize that you are likely hitting the signalr message size level. Very likely you can increase the message size and it will work. Note however there are security implications in doing so https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-6.0#buffer-management

**Comment by mhehle** [comment]
@javiercn you were right, the `Debug` log shows an InvalidDataException with the hint that the maximum message size of 32768B was exceeded.

```
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[2]
      => SpanId:fbbce1ebdd4cd062, TraceId:f08cc5cb503b0ebd1300a0bea5894b1a, ParentId:0000000000000000 => ConnectionId:0HMJ38F2TNPAN => RequestPath:/_blazor RequestId:0HMJ38F2TNPAN:00000002 => TransportConnectionId:H1LuAuA7tUEWvq5NRo7Dag
      Error when processing requests.
      System.IO.InvalidDataException: The maximum message size of 32768B was exceeded. The message size can be configured in AddHubOptions.
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)

```

Is there a more reliable way to solve the problem than increasing the message size?

Nevertheless, the hint would be very helpful in the documentation. currently I can't find anything about this.

**Comment by javiercn** [comment]
> Is there a more reliable way to solve the problem than increasing the message size?

Unfortunately, no, it would complicate the InputFile implementation a lot and it would benefit only a small number of users dealing with a very large number of file uploads, which they can already do by increasing the message size, so it is hard for us to justify any investment to lift this limitation.

In your case, I would either increase the message size limit (as long as you don't give it anything extreme, like 1GB, you are likely ok (try with 64Kb for example). However as with any security limit, you need to understand the impact and test accordingly) or limit the number of files to something you are guaranteed to succeed with, like 50, 100 or 150 (not sure where the boundary is).
