### ISSUE TITLE
 Blazor running under IIS starts throwing 503 without any error. 

### ISSUE THREAD

**Issue by DeadlyEmu** [dotnet/aspnetcore#42661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have been stumped on this for a while. essentially the issue relates to the site suddenly reporting 503 when running under IIS(Express / full )

if i run it as a standard project via VS i dont get the same error. 

I originally build a Blazor server app for a new project i have been working on. Testing as a standard project and all was performing well until i published this to an IIS server which started giving occasional 503 errors without reason. I did further testing on my dev environment and was only able to reproduce the error when debugging with IIS express. 

the only reference i could find on this was #40494

I took some time enabling all of the logging i could find and non of this was telling me anything which was causing the app to shutdown in IIS. 

after a break away from the project i came back to it over the weekend and decided to mock up a small part of the site via Blazor WASM in an attempt to get around the issue. 

Configured the api to pull the relevant data from the database which the client site would pull. i created a powershell script to pull this result from the api and after X amount of times it would return 503 again. 

changed to run as a standard project and reused the powershell script again and was able to get the data over 100,000 times with 0 errors or failed attempts occurring 

the only thing i can think of causing this is the was im pulling the data together. im not the best with SQL so i do multiple pulls of data from SQL and combine the data. 

this is the function i have setup 

`

        [HttpGet("AllRoutes")]
        public List<CurrentRoutes> Routes()
        {
          
                List<CurrentRoutes> routes = new List<CurrentRoutes>();
                List<Groups> groups = new List<Groups>();
                List<Routes> RouteList = new List<Routes>();
                //     CurrentRoutes routes = new CurrentRoutes();
                var builder = WebApplication.CreateBuilder();
                var connetionString = builder.Configuration.GetConnectionString("DefaultConnection");
            try
            {
                using (var conn = new SqlConnection(connetionString))
                using (var cmd = new SqlCommand("SELECT * FROM Groups", conn))
                {
                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        Groups Group = new Groups();
                        Group.GroupID = (int)reader["GroupID"];
                        Group.GroupName = (string)reader["GroupName"];
                        groups.Add(Group);

                    }
                    conn.Close();

                }
            }
            catch(SqlException e)
            {
                Console.WriteLine(e.Message);
            }

            Routes routes2 = new Routes();
            routes2.RouteID = 0;
            routes2.Name = "Phone lines open";
            RouteList.Add(routes2);
            try
            {
                using (var conn = new SqlConnection(connetionString))
                using (var cmd = new SqlCommand("SELECT * FROM AdhocRoutes", conn))
                {
                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        Routes routes1 = new Routes();
                        routes1.RouteID = (int)reader["routeid"]; ;
                        routes1.Name = (string)reader["RouteName"];
                        RouteList.Add(routes1);

                    }
                    conn.Close();

                }
            }
            catch(SqlException e)
            {
                Console.WriteLine(e.Message);
            }

            foreach (Groups group in groups)
            {
                try
                {
                    using (var conn = new SqlConnection(connetionString))
                    using (var command = new SqlCommand("GetCurrentRouteGroup", conn))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.Add("@groupid", SqlDbType.Int).Value = group.GroupID;
                        conn.Open();
                        SqlDataReader reader = command.ExecuteReader();

                        while (reader.Read())
                        {
                            CurrentRoutes currentRoute = new CurrentRoutes();

                            currentRoute.GroupName = group.GroupName;
                            currentRoute.RouteName = RouteList[(int)reader["route"]].Name;
                            routes.Add(currentRoute);
                        }
                        conn.Close();
                    }              
                }
                    catch (SqlException e)
                    {
                        Console.WriteLine(e.Message);
                    }
        }

            return routes;
        }
`

As mention running under IIS this will work for maybe 300 - 600 requests from my experience but running the project direct it will never error out.

Any ideas on this would be great.

### Expected Behavior

Enabling logging across IIS and asp. 

### .NET Version

6.0.301

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It is not clear how this is Blazor specific, so in order for us to investigate this further, we will need a reliable repro project (hosted as a public GitHub repository).

It may be useful to post this issue in [StackOverflow](https://stackoverflow.com) to get help from the community with debugging your issue to better understand the underlying cause.

**Comment by DeadlyEmu** [comment]
I took your point on its likely not a blazor issue but a IIS issue. I have just tested creating a simple API interface without all of the blazor points and still the dame issue. 

I have created a repo to reproduce the issue 
[IIS 503 Repo](https://github.com/DeadlyEmu/IIS_503-Error)

**Comment by adityamandaleeka** [comment]
@HaoK can you please try out the repro and see if there's anything causing the process to recycle or something?

**Comment by HaoK** [comment]
Hi @DeadlyEmu I took a look at your repro app, and it contains a sqldb which you are querying in your controller https://github.com/DeadlyEmu/IIS_503-Error/blob/main/IIS%20503%20Error/Controllers/GitHubTest.cs, that seems likely to be the culprit,
I suggest you also try running this under kestrel so you can see the console output, that might be enough to demonstrate the problem

If that doesn't work you can try enabling more sql logging  you can turn on logging for sql via https://docs.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver16

**Comment by HaoK** [comment]
You can try turning on trace level logs via https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-6.0#enhanced-diagnostic-logs to see if there's any useful info in there for why the worker process gets shut down

**Comment by DeadlyEmu** [comment]
When I orgionally had this issue on a blazor server project I did this with no luck. Youn see the request coming in and being answered fine and then suddenly starts returning 503 without any reason

**Comment by HaoK** [comment]
Can you show the log message for the event with the app pool shutting down?

**Comment by DeadlyEmu** [comment]
> the app pool shutting do

I thought i could recreate it but i cant....... Annoying. 

I have done some more testing and got the following trace out of IIS when the 503 is being outputted. the IIS log doesnt give you anything really but the trace may. Uploaded both 
[ex220721.zip](https://github.com/dotnet/aspnetcore/files/9159473/ex220721.zip)

**Comment by DeadlyEmu** [comment]
While testing i have been running under IISExpress. i have a site i can replicate the issue on under Full IIS which i can confirm the application pool will continue to show started. 


I have removed the try/ catch blocks as requested. Nothing showing in output to explain anything. reuploaded latest trace / log
[ex220722.zip](https://github.com/dotnet/aspnetcore/files/9165986/ex220722.zip)

**Comment by HaoK** [comment]
So the 503s are just sporadic, i thought from your earlier trace once you got a 503 you got a string of them.

**Comment by DeadlyEmu** [comment]
incorrect. Once you get the 503 this will be the response for all requests until the App pool is restarted.

**Comment by HaoK** [comment]
So just to clarify, once it starts returning 503s, your app pool shows shutdown until you restart it then?

**Comment by HaoK** [comment]
You can try disabling rapid fail protection in IIS to see if that helps as well, just turn it off completely: https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/failure

**Comment by DeadlyEmu** [comment]
> So just to clarify, once it starts returning 503s, your app pool shows stopped until you restart it then? Or its showing started but will always return 503/shutdown

when it breaks the app pool will remain in a "started"  state. it wont be until you restart the app pool that requests begin to respond correctly.

I have also tried to do that within IIS and still no luck 
![image](https://user-images.githubusercontent.com/6854643/180627159-0afb67c1-9422-4612-b08d-e0d8b533ca78.png)

**Comment by HaoK** [comment]
Can you double check to see if you are getting 503 from http sys or not from the response headers, i.e.

![image](https://user-images.githubusercontent.com/6537861/181381681-a1ea15f9-8694-49be-a11b-9a8663b1c7f6.png)

**Comment by DeadlyEmu** [comment]
When you get the API route it comes from Microsoft-IIS/10.0

200 response 
![image](https://user-images.githubusercontent.com/6854643/181568394-b216646f-6c8d-4713-999d-cad41d04b499.png)

503 response 
![image](https://user-images.githubusercontent.com/6854643/181568500-33875a9c-3ac2-4427-8e25-4175ecd0cfe7.png)

**Comment by HaoK** [comment]
Okay, next you can try some of the tips on here https://www.leansentry.com/guide/iis-aspnet-hangs specifically check the perf counters to make sure you aren't filling up any IIS queues or running out of SQL connections or the like

**Comment by HaoK** [comment]
One other thing that could help in terms of logs during 503s, is if you turn on the console logs, and see if there's any errors in here once things are constantly giving 503s:

https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#aspnet-core-module-stdout-log-iis

**Comment by DeadlyEmu** [comment]
Hey,

I have been through added as much logging as i can from the above links with little luck. I have attached logs for the last attempt which fails in the same way.
[stdout_20220801170643_39676.log](https://github.com/dotnet/aspnetcore/files/9235942/stdout_20220801170643_39676.log)
[ancm.log](https://github.com/dotnet/aspnetcore/files/9235943/ancm.log)

**Comment by DeadlyEmu** [comment]
So did some further investigation into this. Used both procdump and process monitor.

from the procdump after iis starts to throw 503 errors i found this after analyzing. 
![image](https://user-images.githubusercontent.com/6854643/182257002-8a215752-ca3b-4cff-b25a-fd5e4c0a6372.png)

I haven't done much with debugging dumps like this so i may be mistaken if this is not an error or expected. 

As for the process monitor. i monitored just the IIS express process only and found below. 

As the 503 came up there was a bunch of close file actions
![image](https://user-images.githubusercontent.com/6854643/182257387-be59ea8e-7155-49c6-a268-d1aba063d2a4.png)
followed by more create thread create and then writing the error files form the logging. i have uploaded the process monitor log. 
[Logfile.zip](https://github.com/dotnet/aspnetcore/files/9237782/Logfile.zip)
 
If you want to take a look at the DMP let me know and i will upload.

**Comment by HaoK** [comment]
This is what I would expect given your app is doing a lot of SQL queries over and over again, at this point we can safely say this is due to each request doing a large amount of sql querying

**Comment by DeadlyEmu** [comment]
the queries being run are not intensive though, Few select statements and one SP

**Comment by HaoK** [comment]
You are making 3 sql connections in a single request, but anyways, the behavior you are seeing is specific to your app, closing as external, as this behavior is not due to anything in asp.net core here
