### ISSUE TITLE
API additions for RateLimitingMiddleware

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#42667]
NOTE - This is the original draft of the proposal. The updated proposal is at this comment: https://github.com/dotnet/aspnetcore/issues/42667#issuecomment-1192954022

```diff
namespace Microsoft.AspNetCore.RateLimiting

+    public interface IRateLimiterMetadata
+    {
+    }

+    public interface IRequireRateLimiterMetadata : IRateLimiterMetadata
+    {
+        string PolicyName { get; }
+    }

+    public class RequireRateLimiterMetadata : IRequireRateLimiterMetadata 
+    {
+        public RequireRateLimiterMetadata (string policyName)
+        public string PolicyName { get; }
+    }

+    public interface IDisableRateLimiterMetadata : IRateLimiterMetadata
+    {
+    }

+    public class DisableRateLimiterMetadata : IDisableRateLimiterMetadata 
+    {
+        public RequireRateLimiterMetadata ()
+    }

    public interface IRateLimiterPolicy<TPartitionKey>
    {
-        Func<OnRejectedContext, CancellationToken, ValueTask>? OnRejected { get; }
+        ValueTask OnRejected(OnRejectedContext onRejectedContext, CancellationToken cancellationToken)
    }

namespace Microsoft.AspNetCore.Builder

   public static class RateLimiterApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseRateLimiter(this IApplicationBuilder app)
-       public static IApplicationBuilder UseRateLimiter(this IApplicationBuilder app, RateLimiterOptions options)
    }

+   public static class RateLimiterServiceCollectionExtensions
+    {
+        public static IServiceCollection AddRateLimiter(this IServiceCollection services, Action<RateLimiterOptions > configureOptions)
+    }

    public static class RateLimiterOptionsExtensions
    {
-        public static RateLimiterOptions AddNoLimiter(this RateLimiterOptions options, string policyName)
    }

    public static class RateLimiterEndpointConventionBuilderExtensions
    {
+        public static TBuilder DisableRateLimiting<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
    }
```

Q's - keep `OnRejected` as a `Func` because it's nullable? Change extension methods like `AddTokenBucketLimiter` to `AddTokenBucketLimiterPolicy`? Add an attribute for MVC Controllers?

**Comment by BrennanConroy** [comment]
I like the idea of skipping the middleware suggested in https://github.com/dotnet/aspnetcore/issues/41667#issuecomment-1160056013

**Comment by halter73** [comment]
Meeting notes:

- Let's get rid of the inheritance
- Rename `IRequireRateLimiterMetadata` to `IRateLimiterMetadata`. And `RequireRateLimiterMetadata` to `RateLimiterMetadata`
- `IDisableRateLimiterMetadata` stays the same name.
- Should we allow policies defined inline?
  - It seems straightforward enough to implement well with the little time we have and it would be nice to be able to define rate
- `UseRateLimiter(this IApplicationBuilder app, RateLimiterOptions options)` should stay. We should still add `AddRateLimiter`. This is the same pattern as `AddWebSockets`.
- Let's keep `Func<OnRejectedContext, CancellationToken, ValueTask>? OnRejected { get; }` so we know whether or not to call the global `OnRejected` callback. If we make it a normal method instead, we'd have to be okay with okay with always running the global `OnRejected` first.
- Let's add attributes!
  - How about `[RateLimit("MyPolicy")]`?
  - Anything else?
- Let's put everything in the ASP.NET Core shared framework. We'll have to include `System.Threading.RateLimiting` in the ASP.NET Core shared framework similar to `System.IO.Pipelines`.

- One last curveball from @DamianEdwards: Why can't I configure the rate limiter options (e.g. `TokenBucketRateLimiterOptions`) with a callback like every other "option" type?
  - The properties are read-only. You need to use the constructor
  - Let's fix that and add setters and a default ctor to all the options types. It will have to go through runtime API review.
  - We'll also have to update methods like `AddTokenBucketLimiter` to take an `Action<TokenBucketRateLimiterOptions>` instead of  `TokenBucketRateLimiterOptions` directly.

**Comment by davidfowl** [comment]
This looks great so far 😄

**Comment by Kahbazi** [comment]
> IDisableRateLimiterMetadata stays the same name.

How about this one:
```diff
+    public interface IDisableRateLimiterMetadata
+    {
+        bool IsDisabled { get; }
+    }
```
This is according to the [Guidelines](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#creating-routing-integrated-middleware) and can be overriden if necessary.

> How about [RateLimit("MyPolicy")]?

Also `[DisableRateLimit]`?

> We'll also have to update methods like AddTokenBucketLimiter to take an Action<TokenBucketRateLimiterOptions> instead of TokenBucketRateLimiterOptions directly.

Can it be `Action<TokenBucketRateLimiterOptions, HttpContext>`? This way the options could be based on the custom metadata on an endpoint.

**Comment by davidfowl** [comment]
Agree with @Kahbazi on the disable attribute. We need attributes for anything we have methods for.

**Comment by Kahbazi** [comment]
> Why does the `IDisableRateLimiterMetadata` need a property at all? Shouldn't it simply be a marker, like `IAllowAnonymous`?

I'm just quoting the [Guidance which exists in ASP.NET Core Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#creating-routing-integrated-middleware)
 
> The best way to follow these guidelines is to avoid defining marker metadata:

> Don't just look for the presence of a metadata type.
> Define a property on the metadata and check the property.

And this could be done if the metadata has a property.
```csharp
public class SuppressDisableateLimitAttribute : Attribute, IDisableRateLimiterMetadata 
{
    public bool IsDisabled => false;
}

[DisableRateLimit]
public class MyController : Controller
{
    public void Unlimit() { }

    [SuppressDisableateLimit]
    public void Limited() { }
}
```

**Comment by davidfowl** [comment]
This example applies to route groups as well

**Comment by DamianEdwards** [comment]
@Kahbazi hmm, do we have an example of us actually doing that somewhere in the framework? We don't follow that for `IAuthorizeData` AFAIK, i.e. we simply have `IAllowAnonymous` that circumvents anything defined via `IAuthorizeData` in metadata.

In your example, am I understanding correctly that this is supposed to facilitate *re-enabling* rate limiting when other metadata  for the endpoint already disables it? How do we do that in the AuthZ system? [The code seems to suggest](https://source.dot.net/#Microsoft.AspNetCore.Authorization.Policy/AuthorizationMiddleware.cs,91) we just ignore any AuthZ failures if the allow anonymous metadata is present at all.

**Comment by Kahbazi** [comment]
@DamianEdwards You are right. This is not how it's done today in AUTH or CORS. Now if there's an `IAllowAnonymous` or `IDisableCorsAttribute` metadata on an endpoint there's no way to negate its effect. 
Although this is not a bad thing to have. I suggest add this to Auth and Cors as well. It could be achieve without breaking changes using default interface methods.

**Comment by wtgodbe** [comment]
Runtime API proposal: https://github.com/dotnet/runtime/issues/72389

**Comment by wtgodbe** [comment]
```diff
namespace Microsoft.AspNetCore.RateLimiting

+    public interface IRateLimitAttribute
+    {
+        string PolicyName { get; }
+    }

+    public class RateLimitAttribute : Attribute, IRateLimitAttribute
+    {
+        public RateLimitAttribute (string policyName)
+        string PolicyName { get; }
+    }

+    public interface IRateLimiterMetadata
+    {
+        string PolicyName { get; }
+    }

+    public class RateLimiterMetadata : IRateLimiterMetadata 
+    {
+        public RequireRateLimiterMetadata (string policyName)
+        public string PolicyName { get; }
+    }

+    public interface IRateLimiterPolicyMetadata<TPartitionKey>
+    {
+        IRateLimiterPolicy<TPartitionKey> Policy { get; }
+    }

+    public class RateLimiterPolicyMetadata<TPartitionKey>  : IRateLimiterPolicyMetadata<TPartitionKey> 
+    {
+        public RateLimiterPolicyMetadata (IRateLimiterPolicy<TPartitionKey> policy)
+        public IRateLimiterPolicy<TPartitionKey> Policy { get; }
+    }

+    public interface IDisableRateLimiterMetadata
+    {
+    }

+    public class DisableRateLimiterMetadata : IDisableRateLimiterMetadata 
+    {
+        public DisableRateLimiterMetadata ()
+    }

namespace Microsoft.AspNetCore.Builder

+   public static class RateLimiterServiceCollectionExtensions
+    {
+        public static IServiceCollection AddRateLimiter(this IServiceCollection services, Action<RateLimiterOptions > configureOptions)
+    }

    public static class RateLimiterOptionsExtensions
    {
-        public static RateLimiterOptions AddNoLimiter(this RateLimiterOptions options, string policyName)
-        public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, TokenBucketRateLimiterOptions tokenBucketRateLimiterOptions)
+       public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, Action<TokenBucketRateLimiterOptions> configureOptions)
-        public static RateLimiterOptions AddFixedWindowLimiter(this RateLimiterOptions options, string policyName, FixedWindowRateLimiterOptions fixedWindowRateLimiterOptions)
+       public static RateLimiterOptions AddFixedWindowLimiter(this RateLimiterOptions options, string policyName, Action< FixedWindowRateLimiterOptions> configureOptions)
-        public static RateLimiterOptions AddSlidingWindowLimiter(this RateLimiterOptions options, string policyName, SlidingWindowRateLimiterOptions slidingWindowRateLimiterOptions)
+       public static RateLimiterOptions AddSlidingWindowLimiter(this RateLimiterOptions options, string policyName, Action< SlidingWindowRateLimiterOptions> configureOptions)
-        public static RateLimiterOptions AddConcurrencyLimiter(this RateLimiterOptions options, string policyName, ConcurrencyLimiterOptions concurrencyLimiterOptions)
+       public static RateLimiterOptions AddConcurrencyLimiter(this RateLimiterOptions options, string policyName, Action< ConcurrencyLimiterOptions> configureOptions)
    }

    public static class RateLimiterEndpointConventionBuilderExtensions
    {
+        public static TBuilder DisableRateLimiting<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
+       public static TBuilder RequireRateLimiting<TBuilder, TPartitionKey>(this TBuilder builder, IRateLimiterPolicy<TPartitionKey> policy) where TBuilder : IEndpointConventionBuilder
    }
        
```

**Comment by Kahbazi** [comment]
1. What's the difference between `IEnableRateLimitingAttribute` and `IRateLimiterMetadata`? Isn't one metadata interface for enabling rate limiting is enough? The same thing goes for `IDisableRateLimitingAttribute` and `IDisableRateLimiterMetadata`.
2.  How about remove the `Attribute` suffix from the interface metadata? `IDisableRateLimitingAttribute` -> `IDisableRateLimiting`. `IEnableRateLimitingAttribute` -> `IEnableRateLimiting`
3. What would happen if there are multiple `IRateLimiterPolicyMetadata<TPartitionKey>` on an endpoint?
4. @DamianEdwards So it's a _No_ on adding `IsDisabled` to the metadata?

**Comment by wtgodbe** [comment]
> What's the difference between IEnableRateLimitingAttribute and IRateLimiterMetadata? Isn't one metadata interface for enabling rate limiting is enough? The same thing goes for IDisableRateLimitingAttribute and IDisableRateLimiterMetadata.

Yes, the only difference is that one is an attribute. We can probably combine them as you suggested in `2`.

> What would happen if there are multiple IRateLimiterPolicyMetadata<TPartitionKey> on an endpoint?

Right now, the first one added gets used. We don't yet throw an exception when multiple get added to the same endpoint, but we could start doing so here: https://github.com/dotnet/aspnetcore/blob/1380236774e252fa565602fcae689a4546d1fcab/src/Middleware/RateLimiting/src/RateLimiterEndpointConventionBuilderExtensions.cs#L25-L28

Though that gets less consistent when the metadata & attribute are combined.

> So it's a No on adding IsDisabled to the metadata?

I'm leaning towards following the CORS pattern, but I'm open to the change. We'll discuss in API review.

**Comment by davidfowl** [comment]
The attribute should be a concrete type not an interface so I assume it should be:

```C#
public class EnableRateLimitingAttribute : Attribute, IRateLimiterMetadata 
```

**Comment by Kahbazi** [comment]
```diff
+ public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, Action<TokenBucketRateLimiterOptions> configureOptions)
+ public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, Action<TokenBucketRateLimiterOptions, HttpContext> configureOptions)
```
Also I think it's useful to have an overload with `HttpContext` as well. It could be used to set the rate limiter options based on the current endpoint.
```csharp
rateLimiterOptions.AddTokenBucketLimiter("policy", (options, context) => 
{
    options.TokensPerPeriod = context.GetEndpoint().Metadata.GetMetadata<MyLimiterMetadata>().TokensPerPeriod;
};
```

**Comment by halter73** [comment]
API Review Notes:

- Do we need interfaces and non-attribute classes for metadata.
  - Not technically, but we have interfaces for both CORS and Auth, so we're breaking the pattern here if we don't.
  - That said, it's not clear whether we prefer an interface hierarchy or a bool property to indicate what's disabled.
  - If we decide how the interfaces should work, we *could* add them later to the attributes.
  - DisableRateLimitingAttribute always wins if present
  - Let us seal the attributes as well.
- `RateLimiterPolicyMetadata<TPartitionKey>` attribute?
  - Attributes don't make sense when you're specifying an instance.
  - Let us remove `RateLimiterPolicyMetadata<TPartitionKey>` for now and give the policy an unspeakable name and reference it using `EnableRateLimitingAttribute`.
- We like the IServiceCollection Add* extension method for configuring options
  - We still allow configuring options via `UseRateLimiting(options)`. We will prefer the more local options if specified.
- We changed the rate limiting options type to be mutable so they can follow the more conventional pattern of configuring options in ASP.NET
- Is `RequireRateLimiting<TBuilder, TPartitionKey>` going to require specifying both generic parameters all the time?
  - Since the `TPartitionKey` can be inferred from the policy instance we pass in, this shouldn't be necessary.

```diff
namespace Microsoft.AspNetCore.RateLimiting
+    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
+    public sealed class EnableRateLimitingAttribute : Attribute
+    {
+        public EnableRateLimitingAttribute(string policyName);
+        string PolicyName { get; }
+    }
+
+    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
+    public sealed class DisableRateLimitingAttribute : Attribute
+    {
+        public DisableRateLimitingAttribute();
+    }

namespace Microsoft.AspNetCore.Builder

+   public static class RateLimiterServiceCollectionExtensions
+    {
+        public static IServiceCollection AddRateLimiter(this IServiceCollection services, Action<RateLimiterOptions> configureOptions);
+    }

    public static class RateLimiterOptionsExtensions
    {
-       public static RateLimiterOptions AddNoLimiter(this RateLimiterOptions options, string policyName)
-       public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, TokenBucketRateLimiterOptions tokenBucketRateLimiterOptions)
+       public static RateLimiterOptions AddTokenBucketLimiter(this RateLimiterOptions options, string policyName, Action<TokenBucketRateLimiterOptions> configureOptions)
-       public static RateLimiterOptions AddFixedWindowLimiter(this RateLimiterOptions options, string policyName, FixedWindowRateLimiterOptions fixedWindowRateLimiterOptions)
+       public static RateLimiterOptions AddFixedWindowLimiter(this RateLimiterOptions options, string policyName, Action< FixedWindowRateLimiterOptions> configureOptions)
-       public static RateLimiterOptions AddSlidingWindowLimiter(this RateLimiterOptions options, string policyName, SlidingWindowRateLimiterOptions slidingWindowRateLimiterOptions)
+       public static RateLimiterOptions AddSlidingWindowLimiter(this RateLimiterOptions options, string policyName, Action< SlidingWindowRateLimiterOptions> configureOptions)
-       public static RateLimiterOptions AddConcurrencyLimiter(this RateLimiterOptions options, string policyName, ConcurrencyLimiterOptions concurrencyLimiterOptions)
+       public static RateLimiterOptions AddConcurrencyLimiter(this RateLimiterOptions options, string policyName, Action< ConcurrencyLimiterOptions> configureOptions)
    }

    public static class RateLimiterEndpointConventionBuilderExtensions
    {
+       public static TBuilder DisableRateLimiting<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
+       public static TBuilder RequireRateLimiting<TBuilder, TPartitionKey>(this TBuilder builder, IRateLimiterPolicy<TPartitionKey> policy) where TBuilder : IEndpointConventionBuilder
    }
```

**Comment by wtgodbe** [comment]
> Also I think it's useful to have an overload with HttpContext as well. It could be used to set the rate limiter options based on the current endpoint.

We think that this isn't a broad enough use case to merit its addition at the moment, though we could be open to it in the future. It would also add complexity in the way we instantiate RateLimiters/Policies, since for the ones added in this way, we'd have to wait until we were in the middleware to do so.

**Comment by halter73** [comment]
I think the nullability change makes sense here. Someone could easily name their policy `"DefaultRateLimiterPolicy"`, and now there might be some confusion about what policy that actually means. We could just a more obscure name and prevent anyone from adding a conflicting policy name, but I prefer making it clear that a policy can be unnamed.

I think we should approve this API.

**Comment by halter73** [comment]
API review Notes:

- We prefer nullability over a well-known name because it makes it clearer these polices haven't been given a real name.
- We don't need to change the constructor because we need the extension method to add an inline policy. This is not supported directly with the attribute.

API Approved! (Diff from previously approved API)

```diff
namespace Microsoft.AspNetCore.RateLimiting

 [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
 public sealed class EnableRateLimitingAttribute : Attribute
 {
    public EnableRateLimitingAttribute(string policyName);

-    string PolicyName { get; }
+    string? PolicyName { get; }
 }
```
