### ISSUE TITLE
Question: Process for adding a provider to the "Community Maintained Store Providers" documentation

### ISSUE THREAD

**Issue by toiyabe** [dotnet/aspnetcore#42663]
Quick question: What is the process for adding a new community provider to the documentation located below?

- [Community Maintained Store Providers](https://github.com/dotnet/AspNetCore/tree/main/src/Identity#community-maintained-store-providers)

I imagine there might be a vetting process involved, but I'm not sure a PR is not the proper path for this.

Thanks

**Comment by adityamandaleeka** [comment]
@toiyabe The process is to open a PR with the change you'd like to add, and then we can vet it for inclusion.

If you'd like us to vet something first, feel free to ask here in this issue.

**Comment by toiyabe** [comment]
@adityamandaleeka  Thank you for the reply.  I would like to update the documentation to add a listing for the following Cosmos DB Store Provider for ASP.NET Core Identity:

- [CosmosSoftware/AspNetCore.Identity.CosmosDb](https://github.com/CosmosSoftware/AspNetCore.Identity.CosmosDb)

I would propose to change the following documentation:

* [ASP.NET Identity CosmosDB SQL Provider](https://github.com/dlmelendez/identitycosmosdb)

To the following:

*  ASP.NET Identity CosmosDB SQL Providers:
    * [By dlmelendez](https://github.com/dlmelendez/identitycosmosdb)
    * [By pierodetomi](https://github.com/pierodetomi)
    * [By toiyabe](https://github.com/CosmosSoftware/AspNetCore.Identity.CosmosDb/)

Would that be a proper suggestion for a PR?

**Comment by toiyabe** [comment]
Absolutely!

**Comment by toiyabe** [comment]
Now as I think about it. How about letting the PR process finish? Then consider reorganizing the documentation as a separate issue?

**Comment by davidfowl** [comment]
I’m fine with that. Can you open a docs issue and well

**Comment by toiyabe** [comment]
Sure can.  Would this be the proper repository?

[https://github.com/dotnet/AspNetCore.Docs](https://github.com/dotnet/AspNetCore.Docs)
