### ISSUE TITLE
Test Blazor WebAssembly with Edge WASM interpreter ("DrumBrake")

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#42662]
[Edge enhanced security docs](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer)
[Edge enhanced security blog post](https://microsoftedge.github.io/edgevr/posts/Introducing-Enhanced-Security-for-Microsoft-Edge/)
[WASM interpreter ("Drumbrake") public spec](https://docs.google.com/document/d/1OIJ4Sv2XfTlI5NmTS1QI8v8wPL0LUT5s1W2D9OlJmMc/preview#)

DrumBrake is available on the Edge Canary version (102.0.1243.0 and above)

You can launch and test it out with:

```console
"C:\Users\<USER>\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe" --js-flags="--jitless --wasm-jitless" --user-data-dir=...
```
                
Be mindful of StartupBoost. If Edge is running in the background, the command line process will transfer control to the already running Edge. The command line is just lost. You should do 1 of these before running the command above:

1. Kill the Edge processes from task manager
2. Run msedge.exe --suspend-background-mode first to kill the processes 
3. Disable startup boost.

@lewing

**Comment by lambdageek** [comment]
From the Drumbrake public spec doc:

> Missing features
> The initial version of DrumBrake should implement all features of the current Wasm spec (Release 1.1), and multithreading and atomics. 

> Other experimental features like SIMD, exception handling can be postponed to the next release.

We build the runtime with exception handling turned on (and take advantage of it for AOT compilation) in .NET 7. So that's going to be an issue.

**Comment by mkArtakMSFT** [comment]
Closing this as @SteveSandersonMS has handled this already.
