### ISSUE TITLE
New AddHostedService extension accepting Type as parameter

### ISSUE THREAD

**Issue by delebru** [dotnet/aspnetcore#42673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I usually define my services with custom class attributes: ScopedServiceAttribute and SingletonServiceAttribute. And then load the services when the app starts by looping through all assembly types containing those attributes. Might not be the most elegant or performant solution, but when apps have many services it ends up quite repetitive to have to remember to register all services. Those attributes are also handy when working on a service class, having the service definition on top also gives me a way to quickly find out what type of service this is.

I can do this because `ServiceCollectionServiceExtensions.AddScoped` and `ServiceCollectionServiceExtensions.AddSingleton` accept a Type as parameter for the service to be registered. Unfortunately, there isn't a similar solution for `ServiceCollectionHostedServiceExtensions.AddHostedService`.

### Describe the solution you'd like

Create a new `AddHostedService` method @ `ServiceCollectionHostedServiceExtensions` accepting `Type` as parameter.

### Additional context

This is how I currently register services:
```
[AttributeUsage(AttributeTargets.Class)]
public class ScopedServiceAttribute : Attribute { }

[AttributeUsage(AttributeTargets.Class)]
public class SingletonServiceAttribute : Attribute { }

public static class IServiceExtensions
{
    public static void AddAppServices(this IServiceCollection services)
    {
        var assemblyTypes = Assembly.GetExecutingAssembly().GetTypes();

        foreach (Type scopedServiceType in assemblyTypes.GetTypesWithAttribute(typeof(ScopedServiceAttribute)))
        {
            services.AddScoped(scopedServiceType);
        }

        foreach (Type singletonServiceType in assemblyTypes.GetTypesWithAttribute(typeof(SingletonServiceAttribute)))
        {
            services.AddSingleton(singletonServiceType);
        }

        // This isn't supported:        
        //foreach (Type hostedServiceType in assemblyTypes.GetTypesWithAttribute(typeof(HostedServiceAttribute)))
        //{
        //    services.AddHostedService(hostedServiceType);
        //}
        // Hosted services need to be registered manually:
        services.AddHostedService<HostedService1>();
        services.AddHostedService<HostedService2>();
        // (...)
        services.AddHostedService<HostedServiceN>();
    }

    private static IEnumerable<Type> GetTypesWithAttribute(this Type[] types, Type attributeType)
        => types.Where(x => x.GetCustomAttributes(attributeType, true).Length > 0);
}
```

Then services only need an attribute to be automatically registered:
```
[ScopedService]
public class ExampleService {
    // this is an empty scoped example service
}
```

**Comment by pinkfloydx33** [comment]
HostedService extensions are in the runtime repo. [But all they do](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs#L19) is register your type as an `IHostedService`... So that's all you need to do

```csharp
services.TryAddEnumerable(ServiceDescriptor.Singleton(typeof(HostedService), typeof(YourServiceType))
```

**Comment by delebru** [comment]
> HostedService extensions are in the runtime repo. [But all they do](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs#L19) is register your type as an `IHostedService`... So that's all you need to do
> 
> ```cs
> services.TryAddEnumerable(ServiceDescriptor.Singleton(typeof(HostedService), typeof(YourServiceType))
> ```

Thanks for the reference! Didn't think of checking the AddHostedService source 😅 Works nicely with the code below:

```
[AttributeUsage(AttributeTargets.Class)]
public class HostedServiceAttribute : Attribute { }

[AttributeUsage(AttributeTargets.Class)]
public class ScopedServiceAttribute : Attribute { }

[AttributeUsage(AttributeTargets.Class)]
public class SingletonServiceAttribute : Attribute { }

public static class IServiceExtensions
{
    public static void AddAppServices(this IServiceCollection services)
    {
        var assemblyTypes = Assembly.GetExecutingAssembly().GetTypes();

        foreach (var hostedServiceType in assemblyTypes.GetTypesWithAttribute(typeof(HostedServiceAttribute)))
        {
            services.TryAddEnumerable(ServiceDescriptor.Singleton(typeof(IHostedService), hostedServiceType));
        }

        foreach (var scopedServiceType in assemblyTypes.GetTypesWithAttribute(typeof(ScopedServiceAttribute)))
        {
            services.AddScoped(scopedServiceType);
        }

        foreach (var singletonServiceType in assemblyTypes.GetTypesWithAttribute(typeof(SingletonServiceAttribute)))
        {
            services.AddSingleton(singletonServiceType);
        }
    }

    private static IEnumerable<Type> GetTypesWithAttribute(this Type[] types, Type attributeType)
        => types.Where(x => x.GetCustomAttributes(attributeType, true).Length > 0);
}
```
