### ISSUE TITLE
failed to start process with commandline

### ISSUE THREAD

**Issue by kingdark99** [dotnet/aspnetcore#42680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is error on window server IIS
when call api get HTTP 503 

Application '/LM/W3SVC/2/ROOT/ekyc' with physical root 'C:\Application\ekyc\' failed to start process with commandline 'C:\Application\ekyc\ekyc.exe ' with multiple retries. Failed to bind to port '22421'. First 30KB characters of captured stdout and stderr logs from multiple retries:

.net5
window server 

I must have stop and start application pool to make an application work.

### Expected Behavior

-find root cause
-prevention

### .NET Version

.net 5

**Comment by javiercn** [comment]
@kingdark99 thanks for contacting us.

.NET 5.0 is out of support, we would recommend you upgrade to .NET 6.0 as a first step.

**Comment by kingdark99** [comment]
web.config using hostingModel="OutOfProcess"
Is the only krestel make a "Sent shutdown HTTP message to process with Id '12452' and received http status '202'."
if I change to Inprocess that not have this case happened again ?.

**Comment by adityamandaleeka** [comment]
@kingdark99 Moving to the in-process hosting model should help avoid this type of issue.

Also, as @javiercn mentioned, you should upgrade to .NET 6 :smile:
