### ISSUE TITLE
"The path must be absolute" when running Blazor.Server in Linux docker

### ISSUE THREAD

**Issue by uecasm** [dotnet/aspnetcore#42684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Possibly a regression of #35285?

I created a Blazor Server application from VS2022, using the options to generate a Linux docker image.  This initially worked as expected.

After iterating on the code a bit (including adding an RCL), while it still runs locally, trying to debug via Docker fails with the exception below during the initial app startup (at the `WebApplication.CreateBuilder` line).

Most of the call stack of the bug is optimised away so I can't glean much of interest, but of note is that inside the `ManifestStaticWebAssetFileProvider` constructor, the `manifest.ContentRoots` collection contains a mixture of Linux and Windows absolute paths (notably, using the Windows path for the RCL paths).  So I suspect it's breaking on the Windows paths.  (But as these are paths on the dev machine, I don't see why they exist at runtime at all...)

### Expected Behavior

Either a build error (that hints at the correct fix, assuming there is one) or running successfully.

### Steps To Reproduce

1. Create a new Blazor Server project with Linux docker support enabled
2. Create a new RCL project in the same solution but *not* inside the solution's directory
3. Reference the library from the app and use a component somewhere.
4. Run in regular mode; observe no problems.
5. Run in docker mode; observe no build errors, but the exception below occurs.

It appears to work as expected when all of the referenced projects are either packages or are within the same solution directory, and falls over whenever referencing something "outside".

I wondered if perhaps this needed some additional copying in the `Dockerfile`, except that the actual docker build does seem to work, even though it only appears to copy the app project file prior to the restore.

### Exceptions (if any)

```
System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute. (Parameter 'root')
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in C:\Drives\pavlova\FreshTracker.UI\FreshTracker.UI.Server\Program.cs:line 4
```

### .NET Version

6.0.300

### Anything else?

VS2022 17.2.3

**Comment by uecasm** [comment]
FWIW the "outside" project doesn't even need to be very far away -- in my test it failed even though the project was just one directory up from the solution directory (i.e. at `../OtherLib/OtherLib.csproj` relative to the solution).

Possibly also of interest is that if I symlink the other library so that it does appear beneath the solution directory (and also manually edit the solution and project references accordingly, since VS will add the "real" path instead of the symlink path), it still doesn't work, although it gets further -- the new exception is:
```
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=/src/OtherLibrary/obj/Debug/net6.0/scopedcss/projectbundle/
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs:line 65
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs:line 46
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot) in /_/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs:line 42
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory) in /_/src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs:line 31
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest) in /_/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs:line 44
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration) in /_/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs:line 32
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs:line 182
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in D:\Drives\blazor\DockerApp\BlazorApp\Program.cs:line 1
```

Though again, these paths shouldn't even exist at runtime, especially on a published build...

**Comment by uecasm** [comment]
Also, this might be a separate issue, but all of the above was while VS was set to the Debug configuration (despite the Dockerfile itself only using the Release configuration).  If I switch VS to Release, then even without the above outside-solution shenanigans (and in fact even on a completely new unmodified-from-template solution) the build fails with this every time:

```
1>docker build -f "D:\Drives\blazor\BlazorApp5\Dockerfile" --force-rm -t blazorapp5  --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=BlazorApp5" "D:\Drives\blazor\BlazorApp5"
1>#1 [internal] load build definition from Dockerfile
1>#1 sha256:0936a9b11352e6751939c427d2397246be12d71936d308d944ef070c250f3a6c
1>#1 transferring dockerfile: 32B 0.0s done
1>#1 DONE 0.0s
1>
1>#2 [internal] load .dockerignore
1>#2 sha256:550b3702ee9d376da742543696fc4ae6e5a9eda9eee081cd4f3775434fa2291c
1>#2 transferring context: 35B done
1>#2 DONE 0.0s
1>
1>#4 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0
1>#4 sha256:ac4494cbca04ddb415c76edcbcc7688784c2a6ea65dd656286c013738aa3b75f
1>#4 DONE 0.0s
1>
1>#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0
1>#3 sha256:9eb4f6c3944cfcbfe18b9f1a753c769fc35341309a8d4a21f8937f47e94c712b
1>#3 DONE 0.7s
1>
1>#5 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:6.0
1>#5 sha256:50f1ddc10932c4a74c7af5704e931a9489c710faea4f2381fe2380827a900e00
1>#5 DONE 0.0s
1>
1>#6 [base 2/2] WORKDIR /app
1>#6 sha256:bc3cf6c390e5fe0e66017b4845c8fcf3e56c7adac9f514a00c2c986024f377a4
1>#6 CACHED
1>
1>#7 [final 1/2] WORKDIR /app
1>#7 sha256:3baba3edbb555769ad9a49e827de88d7dcc4f72ad6e2b42e576964e4a30eac96
1>#7 CACHED
1>
1>#8 [build 1/7] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:4c45d75732f4834aa37cf01506dc8df46dbd89261e5d5012bfbb5399e69518fc
1>#8 sha256:1477de687fc664e9924ad7651c508022f8f17b20bb51c08c109a112200d36008
1>#8 resolve mcr.microsoft.com/dotnet/sdk:6.0@sha256:4c45d75732f4834aa37cf01506dc8df46dbd89261e5d5012bfbb5399e69518fc 0.0s done
1>#8 sha256:4c45d75732f4834aa37cf01506dc8df46dbd89261e5d5012bfbb5399e69518fc 2.17kB / 2.17kB done
1>#8 sha256:475fd401cbde0994fd1247bb9eb24d2af3a40be56cf59f6e04a67791161d52f2 2.01kB / 2.01kB done
1>#8 sha256:074061fd62610bb2dd4275aab6d90dddd5b47d4679c21b57650bcea02ab1e29f 0B / 25.37MB 0.1s
1>#8 sha256:75960f6d1ced2421f6c99d5c179de5e4f10d644feb834a75298513817a4d1438 7.16kB / 7.16kB done
1>#8 sha256:c5aeeaa9e3d38490004e7563fe069e719515c713bd3a4a3a42a4a2c376e33455 0B / 12.89MB 0.1s
1>#8 CANCELED
1>
1>#10 [internal] load build context
1>#10 sha256:deed4861bcd5cfc36b9eb93ce582dca478fc67ac0f504ef5e54ddcd690dac6ad
1>#10 transferring context: 476.57kB 0.1s done
1>#10 CANCELED
1>error from sender: context canceled
```

**Comment by javiercn** [comment]
@uecasm thanks for contacting us.

Are you building on windows and then running on Linux?

**Comment by uecasm** [comment]
I already did include all the necessary repro steps.  But ok:

1. Clone https://github.com/uecasm/DockerApp.git
2. Open `Solution\DockerApp.sln` in VS2022
3. Select the `Debug` configuration and `BlazorApp` debug/run profile, if not already selected
4. Press F5, observe that the app runs as expected
5. Close and quit the debugger
6. Select the `Docker` debug/run profile
7. Press F5, observe `ArgumentException` on startup
8. Close and quit the debugger
9. Select the `Release` configuration (still with `Docker`)
10. Press F5, observe failure to build container

The last failure can also be observed simply by creating a new project, switching to `Release`+`Docker`, and pressing F5; no code changes or extra libraries needed.

It's a little trickier to repro the `DirectoryNotFoundException`; that involves making a symlink/junction and editing some project paths.

```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@uecasm thanks for the additional details.

It seems that it is an issue with Visual Studio Docker tools failing to correctly map the paths for the library.

![image](https://user-images.githubusercontent.com/6995051/178469634-bc848f03-0b11-484d-8f49-1dd17563b9db.png)

This is very likely because the library and the solution are "siblings" instead of the solution file being in a parent folder. You can try to set your environment that way and report the issue through the report a problem feature in Visual Studio including the details you provided. That way they will be able to give you a faster and better answer and you'll be able to track the progress towards a fix.

Once you have the issue filed through Visual Studio, please paste the link here so that we can keep track of it too.

**Comment by NCarlsonMSFT** [comment]
@uecasm I've submitted a PR to your repo repro with an example fix for your issue: https://github.com/uecasm/DockerApp/pull/1.
Referencing a file outside of the docker [build context](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#understand-build-context) is not supported. By default, the Visual Studio tools use the Solution directory as the build context; but the MSBuild property [`DockerfileContext`](https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2022) can be used to change that. **Note** when you change `DockerfileContext` you need to update all source paths in the Dockerfile and move the .dockerignore file to the new location. If there is not a reasonable shared folder between the Blazor project and the Library project, then I would recommend using a NuGet instead of a direct project reference.

A few other notes:
* The more files included in your build context, the slower the build will be. If you need to move your build context up, consider adding to your [.dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file) to remove unneeded files.
* The difference between the Debug and Release behavior is explained here: https://aka.ms/containerfastmode#debugging
* Your failure in the release configuration appears to be an unrelated issue in Docker. Based on the log something is cancelling pulling the SDK image. Not sure why that would happen, but try `docker pull mcr.microsoft.com/dotnet/sdk:6.0` on the command line to see if that is illuminating.

**Comment by uecasm** [comment]
Using a NuGet is not a great alternative when you want to edit both projects at the same time without explicit publishing.  It's also quite annoying to use a private feed (afaik a private folder can't be used because the nuget.config file can't provide different paths for Windows and Linux).  Keeping projects in the solution folder (or even in close proximity) is not always practical when you want to share things between multiple solutions.  (Although it's not helped by git submodules being terrible.)

I know you're subject to some limitations of Docker itself here, but why couldn't it (before invoking docker) copy "outside" files to an obj folder or somewhere else that is inside the context if required?  But more importantly, since the build seems to work fine even when the files are not in the context, why does it fail only at runtime?  This still sounds like it's putting in absolute paths to build locations in the final output, which is entirely incorrect.

Regarding the debug vs. release thing, it's trying to pull the same images for debug as for release, but it works in debug and it fails in release, every time.  There are no errors if pulled on the command line (and it still tries to pull during build, it's just faster when it's already local).

**Comment by NCarlsonMSFT** [comment]
@uecasm Build works fine on the Windows host b/c it has access to the referenced project and it's static files. As per (https://aka.ms/containerfastmode#debugging) in Debug (or more specifically ContainerDevelopmentMode Fast) we don't build the entire image, we only build the first stage and use volume mounts to mount the locally built files. The files you are referencing from outside the build context don't have auto-generated mounts so our tool that re-writes paths in the static web assets (which does contain absolute paths) file fails to remap them resulting in the exception you're encountering. In Release mode (or if you just call Docker build) we build the project and all referenced projects in an intermediate stage based on mcr.microsoft.com/dotnet/sdk:6.0, anything that is not brought in through the build context of the dotnet restore can't be used. That is why Debug fails at runtime but Release would fail at build time (the dotnet restore step should fail).

For the private folder for the NuGet there are two solutions:
1) If you are using ContainerDevelopmentMode Fast (default for Debug) the build happens on the windows side, and we use mounts to expose the NuGet cache to the container, so as long as VS can get the NuGet you'll be fine.
2) You can copy the NuGet to a folder in the solution and reference it there when testing, that way it would be in the build context for full image builds.

To the question of 
> why couldn't it (before invoking docker) copy "outside" files to an obj folder or somewhere else that is inside the context if required

The dockerfile that we scaffold is designed to be stand-alone and not require anything more than docker to run. Hower it is completely possible for you to customize it, and your project to handle the referenced project being copied locally first. That said, I'm not sure what you would copy: The whole project? A published NuGet of the project?

**Comment by uecasm** [comment]
It still seems like there ought to be _some_ kind of better automatic integration for solutions that contain ProjectReferences outside of the solution directory.  I don't know exactly what that should be, but it's a very common scenario.  And I don't think converting everything to PackageReferences is the right solution.

FWIW, if I do ensure that everything is within the solution directory and then build the Dockerfile from the command line, then it does build and run correctly (I haven't explicitly tested building from the command line while some projects are "outside").

Doing a Release (or Regular container mode Debug) from within VS still always cancels while pulling the images, though, even if they've previously been successfully pulled on the command line.

**Comment by NCarlsonMSFT** [comment]
@uecasm Please open a suggestion on [Developer Community](https://developercommunity.visualstudio.com/report?entry=suggestion&space=8) for Project References outside the solution.

For you Docker build issues, please open an issue in the [Docker Tools repo](https://github.com/microsoft/DockerTools/issues/new) and we can continue the conversation there.
