### ISSUE TITLE
Requests with new lines at the end cause extra 400 responses

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#42697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a follow up to https://github.com/dotnet/aspnetcore/issues/40747. That fixed an issue where extra CRLF's between requests would cause 400s. It missed a case where if those CRLFs where after the last request of a connection then that would also trigger an extra 400.

### Expected Behavior

Extra CRLFs after the body are ignored and the connection gracefully closed.

### Steps To Reproduce

Send a request. Include one or more extra CRLF's at the end that are not accounted for in the normal body (e.g. beyond the content-length). After the server responds to the initial request, half-close the connection from the client. This triggers the incoming pipe reader to complete and the HttpParser errors if there's still data left, producing an extra 400 response.

### Exceptions (if any)

```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

### .NET Version

6.0

**Comment by Tratcher** [comment]
Milestone?

**Comment by adityamandaleeka** [comment]
Reopened for 6.0.
