### ISSUE TITLE
IJSRuntime in documentation

### ISSUE THREAD

**Issue by bertramdryan** [dotnet/aspnetcore#42693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to inject JSRuntime into a service or POCO, with the ability to access the JSRuntime. 

IJSRuntime cannot be simply injected into any .cs class.  It can be injected into a razor.cs, but injecting it into another service doesn't work. 

Something like this:
``` csharp
var jsRuntime = host.Services.GetRequiredService<IJSRuntime>();

builder.Services.AddSingleton<IAuthorizationService, AuthorizationService>(
    service => new AuthorizationService(
        service.GetService<IUserAuthClient>(),
        jsRuntime
        )
);
```

Or something like:

``` csharp
builder.Services.AddSingleton<IAuthorizationService, AuthorizationService>(
    service => new AuthorizationService(
        service.GetService<IUserAuthClient>(),
        service.GetService<IJSRuntime>()
        )
    );
```

The error is that that this cannot be scoped.  I'm wondering what other solutions might work, and perhaps an example of how to inject this into other services might be useful on this page. 

---
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26404

### Describe the solution you'd like

A solution to being able to inject JSRuntime into a service, and potentially adding it to the documentation if there is a solution to this. 

### Additional context

The app is being written for an Outlook add-in, to gain access to the limited persistent storage and user profile information, such as email and a place to store a refresh token.

**Comment by javiercn** [comment]
@bertramdryan thanks for contacting us.

As you mentioned, the problem that you are running into is that IJSRuntime is a scoped service and you are trying to inject it into a singleton service. This is by design. There are two things that you can do, change your service to be scoped (which makes sense if you are dealing with user specific state). Pass in the IJSRuntime to your service instead of injecting it into the singleton.

**Comment by bertramdryan** [comment]
@javiercn Thank you for your help. I'll give this a try immediately.
