### ISSUE TITLE
SpaProxyLaunchManager invoked with wrong path in VS 2022 for Mac

### ISSUE THREAD

**Issue by chrisbecke** [dotnet/aspnetcore#42707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I cannot debug a dockerized react application in Visual Studio 2022 for Mac as the SpaProxyManager fails to start npm as it is using a host, rather than container, relative path:

### Expected Behavior

I should be able to use Visual Studio 2022 for Mac to debug Dockerized projects.

### Steps To Reproduce

[Reference on containerizing React Apps in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022)

In a new directory on a Mac with Visual Studio 2022 for Mac installed:

```bash
dotnet new sln
dotnet new react -o react
dotnet sln add react
open test.sln
```
This should open Visual Studio 2022 for Mac
Now, rightclick and "Add Docker Support" to the react project.

Edit the generated `Dockerfile` to add the following

```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
...
```

As Visual Studio for Mac does not use launchSettings for the docker-compose project, the other instructions from the reference can't be followed. Instead edit the `docker-compose.override.yml` file to ensure the environment is set:

```yaml
version: '3.4'

services:
  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
```

Now ensure that the `docker-compose` Profile is current and execute the project. The SPA Landing page will open in the browser, but the debug output for the react client indicates that npm could not be started.

### Exceptions (if any)

info: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      No SPA development server running at https://localhost:44449 found.
Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager: Information: No SPA development server running at https://localhost:44449 found.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Diagnostics.Process.dll'. Cannot find or open the PDB file.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.IO.Pipes.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Diagnostics.Process.dll
fail: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Failed to launch the SPA development server 'npm start'.
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
      System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/bin/npm' with working directory '/Users/chrisb/Projects/tmp/react-demo/client/ClientApp/'. No such file or directory
         at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager.LaunchDevelopmentProxy()
Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager: Error: Failed to launch the SPA development server 'npm start'.

System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/bin/npm' with working directory '/Users/chrisb/Projects/tmp/react-demo/client/ClientApp/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager.LaunchDevelopmentProxy()
Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager: Error: Couldn't start the SPA development server with command 'npm start'.
fail: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Couldn't start the SPA development server with command 'npm start'.
      SPA proxy is not ready. Returning temporary landing page.

### .NET Version

6.0.301

### Anything else?

Visual Studio for Mac 17.0.5 (build 6)

**Comment by chrisbecke** [comment]
This does actually seem similar to #41093

**Comment by javiercn** [comment]
@chrisbecke thanks for contacting us.

When running in docker you need to launch the spa proxy manually and adjust the proxy path in proxy.conf.js or setupProxy.js

**Comment by javiercn** [comment]
Closing this issue as we will be using 41093 to track improvements in this area
