### ISSUE TITLE
Use top level statements does not have an accelerator key in display name for Visual Studio

### ISSUE THREAD

**Issue by phenning** [dotnet/aspnetcore#42719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576097/

Accelerator key should be displayed for use top level statements (and probably other template defined options as well)

![image](https://user-images.githubusercontent.com/2433750/178797704-1f38b44c-614c-4b90-94e5-b4990b706535.png)

See also, https://github.com/dotnet/templating/issues/4961

### Expected Behavior

Some sort of accelerator key should be indicated.

### Steps To Reproduce

Repro steps:
Launch VS and open NPD
Choose any web project template and click "Next" to "Additional information"
Click "Alt" on the keyboard
Observe the "Do not use top-level statements" option

**Comment by TanayParikh** [comment]
cc/ @DamianEdwards & @dougbu as this may impact ongoing localization efforts

**Comment by dougbu** [comment]
I don't see a localization issue here. Added underscores in template.json or ide.host.json files should automatically cause those underscores to be reflected in templatestrings.en.json files (assuming the dev does a local build and includes updated localize/* files in their PR). The next `OneLocBuild` handback PR should propagate them to the other language files.

**Comment by phenning** [comment]
@dougbu is correct, worse case is that non-enu would not have the accelerators until the updated language strings files got checked in by OneLocBuild.

**Comment by phenning** [comment]
A bit greater concern is how dotnet new handles underscores in display names in the help text. I asked that question in the dotnet/templating version of this issue.

**Comment by dougbu** [comment]
@phenning is it a bug that underscores are duplicated from template.json files (if that's where they first appear) into templatestrings.{lang}.json files as part of the `$(UsingToolTemplateLocalizer)` processing❔ I suspect underscores that appear only in ide.host.json files will avoid both any `dotnet new` issues and problematic translations but I'm not sure how accelerators work in a localized VS instance.

/cc @jonfortescue
/fyi @cristianosuzuki77

**Comment by phenning** [comment]
I'm not sure what you mean, do you mean that a string like "Do not use _top level statements" would added to templatestrings.en.json as "Do not use __toplevel statements"? Have you seen this with other strings?  That seems like it would be a bug to me, since I would think we would want the accelerator indicator preserved.

/cc @vlada-shubina

**Comment by phenning** [comment]
Vlada informed me that the CLI does not currently use the displayName property. So it is safe to put the accelerators into the template.json and templatestrings.json files as the displayName.

**Comment by jonfortescue** [comment]
Accelerators can be loc'd, but under our current loc process they often require manual intervention to ensure we're not breaking our product with duplicate accelerators. There's not much we can do about that without significantly overhauling the loc process. Basically, if using accelerators, make sure to scrutinize the loc PR handbacks.

**Comment by vlada-shubina** [comment]
According to https://github.com/dotnet/templating/issues/4961#issuecomment-1189365318 suggestion we will be using T as accelerator.

**Comment by captainsafia** [comment]
Closed via https://github.com/dotnet/aspnetcore/pull/42802.
