### ISSUE TITLE
Signing certificates on the fly in `ServerCertificateSelector` can not return the signed certificate.

### ISSUE THREAD

**Issue by Ruikuan** [dotnet/aspnetcore#42715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try signing the certificate for hostname in the `ServerCertificateSelector` on the fly to enable no matter what domain name users visiting, they will get the right https certificate.

The code can be viewed in this gist: https://gist.github.com/Ruikuan/11089e62a7916abbd3fbc967a7d7ebde.

The problem is, I can't return the signed `X509Certificate2` directly, when trying to return it, 
the browser can not connect to the server. Even I removed all of the `using` statements, it's not working.

https://gist.github.com/Ruikuan/11089e62a7916abbd3fbc967a7d7ebde#file-program-cs-L50

The workaround is to export that certificate then import it into another certificate and return this new created certificate.

Don't know if it's an issue of ASP.NET Core or `X509Certificate2`, or I used it in the wrong way.

### Expected Behavior

The signed certificate can be return directly, don't need the workaround.

### Steps To Reproduce

https://gist.github.com/Ruikuan/11089e62a7916abbd3fbc967a7d7ebde#file-program-cs-L50

### .NET Version

7.0.100-preview.6.22352.1

**Comment by davidfowl** [comment]
cc @bartonjs @wfurt

**Comment by davidfowl** [comment]
What would throw?

**Comment by davidfowl** [comment]
@wfurt does it make sense to throw this exception from `SslStream.AuthenticateAsServerAsync`?

**Comment by wfurt** [comment]
It would but I'm not sure we can detect that reliably. This is also trickier as the key _may_ be somewhere in the store and not directly attached to the certificate object. There is lot of hidden magic in Schannel and CAPI.

**Comment by Ruikuan** [comment]
Reopen it. Feel free to close it if we have any conclusions, exceptions, documents or so on.
