### ISSUE TITLE
Blazor :Code doesn't compile following official documentation 

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#42710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Here is a piece of code in the offical documentation for the Virtualized Component :
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0#item-provider-delegate

As you can see, it suggests the use of :
```
private Virtualize<FetchData>? virtualizeComponent;

protected override void OnInitialized()
{
    WeatherForecastSource.ForcecastUpdated += async () => 
    {
        await InvokeAsync(() =>
        {
            await virtualizeComponent?.RefreshDataAsync();
            StateHasChanged();
        });
    });
}
```

However, if you are awaiting inside InvokeAsync, the delegate should at least be async void

### Expected Behavior
Update the documentation to the correct usage of RefreshDataAsync and StateHasChanged.
I understand that you have to use InvokeAsync otherwise exceptions will be throw, although the documentation didn't touch on this.
Unfortunately I don't know how to use this component, nor do I know what's the right way to fix this code, to me it was simply not compiling while I was trying the example

_No response_

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

@MackinnonBuck can you take a look and make sure the docs are correct?

**Comment by javiercn** [comment]
@Xyncgas can you point out what you are suggesting doesn't work with that sample? That delegate will already be `async void` since the compiler will type it that way to coerce it to the event signature.

**Comment by Xyncgas** [comment]
The official document has this code
```
await InvokeAsync(() =>
        {
            await virtualizeComponent?.RefreshDataAsync();
            StateHasChanged();
        });
```
If you are awaiting inside a delegate it should be async

**Comment by Xyncgas** [comment]
Meanwhile I would say I would love a bit clarification as to this quote in the document :
**If [RefreshDataAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.web.virtualization.virtualize-1.refreshdataasync) is triggered separately from a background task or event, such as in the following ForcecastUpdated delegate, call [StateHasChanged](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.statehaschanged) to update the UI at the end of the background task or event:**

1) I am not sure if the code provided was the correct example since it doesn't compile
2) in that case I wonder if I should call StateHasChanged before RefreshDataAsync or after
3) Do I even need to call RefreshDataAsync since the document sounds like I need to call StateHasChanged for a reason
