### ISSUE TITLE
Wasm is Not Caching the blazor-resource

### ISSUE THREAD

**Issue by avichhetri8** [dotnet/aspnetcore#42714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I add my localhost url using the host file example    `    127.0.0.1        localtest.appservice.dev.com ` then the Blazor wasm project could not cache the DLL file in the Cache Storage 
![image](https://user-images.githubusercontent.com/48516639/178724766-ea9b804e-8aa8-47b2-ad78-1529967d95b6.png)

With localhost:5000 url
![image](https://user-images.githubusercontent.com/48516639/178724886-50c47001-324e-4247-8cce-2b25cf9d58ea.png)

### Expected Behavior

Wasm project should cache the dll files in the localtest.appservice.dev.com host also.

### .NET Version

6

**Comment by avichhetri8** [comment]
> It caches for me if I was building pwa blazor wasm

Change your localhost to another end from windows/system32/drivers/etc host file

**Comment by avichhetri8** [comment]
> It caches for me if I was building pwa blazor wasm

Change your localhost to another end from windows/system32/drivers/etc host file

**Comment by javiercn** [comment]
@avichhetri8 browsers make an exception for localhost and treat it as a secure context, that's why it works.
