### ISSUE TITLE
OutOfProcess and IIS Threads

### ISSUE THREAD

**Issue by FlorianGrimm** [dotnet/aspnetcore#42713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In the ASP.NET Community Standup - ASP.NET Core Architecture - Part 5 Video @davidfowl asked why somebody still uses the OutOfProcess setting.
I have a web application starting from .Net Framework + ASP.NET Core 2, migrated to .NET Core 6 + ASP.NET Core 6.
The application has a scheduler and long running task triggered by an request. Back than the IIS killed the thread if running longer than 30/120? sec - cannot remember - and .Net Framework had the feature marking Background Thread to prevent the timeout killing.
Because of the video I tried this to reproduce on .NET Core 6 - I could not - the long running tasks runs. 
I tried to find out when this behavior changed. I could find a docu for this.

### Describe the solution you'd like

Please provide a documentation for the changes for the IIS thread killing. (Or point me to this)

### Additional context

I don't know if this is a feature request, but I 'll guess this is not a bug...

**Comment by adityamandaleeka** [comment]
@FlorianGrimm Are you still using out-of-process hosting in .NET 6?

In-process hosting is the default mode now, and the [`requestTimeout` attribute](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-6.0#attributes-of-the-aspnetcore-element) doesn't apply to in-process hosting.

**Comment by FlorianGrimm** [comment]
@adityamandaleeka Yes I'm using it because it do not know if why the IIS killed the framework threads but not the .net core threads... And until I saw the video I had no reason questioning this decision. 
To understand the difference I ask for some documentation. 
I ddin't modify requesttimeout. The application handle long running task, triggered by a request, in an hosted service.

**Comment by adityamandaleeka** [comment]
The linked documentation should cover the behavior on Core. It shows that the default for `requestTimeout` is 2 minutes, and also that it doesn't apply to in-process:

> Doesn't apply to in-process hosting. For in-process hosting, the module waits for the app to process the request.

In general, we recommend switching to in-process hosting, especially if you don't see any issues with it (and if you do, let us know).

**Comment by adityamandaleeka** [comment]
Or better yet, move to Kestrel :smile:

**Comment by FlorianGrimm** [comment]
I have two deployment targets OnPremises with Windows AuthN and App Services, which uses also IIS IMHO.
But back to the question: The fact that ASP.Net Core do not use the SynchronizationContext is this the reason why their is no timeout or some ting else?
