### ISSUE TITLE
Microsoft.AspNetCore.ApiAuthorization.IdentityServer: Need support for password grant type

### ISSUE THREAD

**Issue by lnaie** [dotnet/aspnetcore#42711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For a native app, I would like support for a simple user and password auth flow.

Right now there is a definition for ```NativeApp``` in the ```https://github.com/dotnet/aspnetcore/blob/main/src/Identity/ApiAuthorization.IdentityServer/src/Configuration/ApplicationProfiles.cs```, but when is loaded from appsettings.json it locks me in the code grant type, which is not what I need.

This file here ```https://github.com/dotnet/aspnetcore/blob/main/src/Identity/ApiAuthorization.IdentityServer/src/Configuration/ConfigureClients.cs``` reveals what is going on, however not properly documented here ```https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-6.0&tabs=visual-studio#app-settings```. 

Maybe creating a Password profile in the ```ApplicationProfiles``` that would allow me to load the client id and secret from appsettings.json, would be the minimal implementation. 
```
"IdentityServer": {
  "Clients": {
    "ClientName": {
      "Profile": "Password",
      "Secret": "the_client_secret"
    }
  }
}
```

Its setup could be like this:
```
        var client = CreateClient(clientId);
        return new ClientBuilder(client)
            .WithApplicationProfile(ApplicationProfiles.Password)
            .WithAllowedGrants(GrantTypes.Password)
            .WithClientSecrets(/*loaded via IConfiguration*/)
            .WithScopes(IdentityServerConstants.StandardScopes.OfflineAccess, IdentityServerConstants.StandardScopes.OpenId, IdentityServerConstants.StandardScopes.Profile, IdentityServerConstants.StandardScopes.Email);
```

I understand that is not highly recommended, but I need it and I couldn't see a way to work around the existing code.

Thanks

**Comment by javiercn** [comment]
@lnaie thanks for contacting us.

resource owner credentials flow is something that is discouraged by the specs and we have no plans to support.

If you need to support this flow (which we again discourage you from) you will need to use an IdP that supports this directly, but it is not something we plan to do.

**Comment by javiercn** [comment]
@lnaie and you can configure that directly in Duende IDS, our integration package will not support that scenario, nor will we provide guidance on how to enable it.

**Comment by lnaie** [comment]
Ok, it's clear your set-in-stone position.

Is there a sample for the NativeApp profile with dotnet maui? Because that's what is hot right now, besides blazor.

Thanks

**Comment by lnaie** [comment]
not very helpful all that code, is it? 
cheers
