### ISSUE TITLE
ConfigureRouteHandlerJsonOptions naming 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/aspnetcore#42718]
Reading here I see what is `ConfigureRouteHandlerJsonOptions` today used to be named `ConfigureHttpJsonOptions`  https://github.com/dotnet/aspnetcore/issues/39226

`ConfigureRouteHandlerJsonOptions` does not seem like a better name. `Request.ReadFromJsonAsync` and `Response.WriteAsJsonAsync` use the same options, yet these methods are commonly used from middleware which has absolutely nothing to do with route handlers. 

/cc @captainsafia

**Comment by davidfowl** [comment]
cc @halter73 @captainsafia

**Comment by halter73** [comment]
API review notes:
- `ConfigureHttpJsonOptions` does seem like a better name than `ConfigureRouteHandlerJsonOptions` given that it also affects `Request.ReadFromJsonAsync` and `Response.WriteAsJsonAsync`.

API Approved!

```diff
namespace Microsoft.Extensions.DependencyInjection;
 

public static class RouteHandlerJsonServiceExtensions
{
-    public static IServiceCollection ConfigureRouteHandlerJsonOptions(this IServiceCollection services, Action<JsonOptions> configureOptions);
+    public static IServiceCollection ConfigureHttpJsonOptions(this IServiceCollection services, Action<JsonOptions> configureOptions);
}
```

**Comment by captainsafia** [comment]
While working on the PR, I made another change to the API. 

```diff
namespace Microsoft.Extensions.DependencyInjection;
 

- public static class RouteHandlerJsonServiceExtensions
+ - public static class HttpJsonServiceExtensions
{
-    public static IServiceCollection ConfigureRouteHandlerJsonOptions(this IServiceCollection services, Action<JsonOptions> configureOptions);
+    public static IServiceCollection ConfigureHttpJsonOptions(this IServiceCollection services, Action<JsonOptions> configureOptions);
}
```

Amongst other things, this ensures that the class name and file name match. It also makes sense in the context of this change.
