### ISSUE TITLE
Reset the Counter on a Specific RateLimiter

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#42729]
## Background and Motivation
There comes a time when we need to reset counter for a specific customer or and endpoint. 

## Proposed API
```diff
namespace Microsoft.AspNetCore.RateLimiting;

public sealed class RateLimiterOptions
{
      // Reset all limiter for the policy.
+    public ValueTask ResetRateLimiterAsync(string policy);

      // Reset all limiter for the policy with the specific partition.
+    public ValueTask ResetRateLimiterAsync<TPartitionKey>(string policy, TPartitionKey partition);
}
```
In order to achieve this the Runtime needs to add API to `PartitionedRateLimiter`.

The method is async in case the Runtime provide another storage rather than in memory in future.

## Usage Examples
A customer calls and for whatever reason we have to reset the counter of its limiter.
```csharp
public class AdminController
{
    private readonly IOptions<RateLimiterOptions> _options;

    public AdminController(IOptions<RateLimiterOptions> options)
    {
        _options = options;
    }

    public Task ResetAsync(string policy, string userId)   
    {
        _option.ResetRateLimiterAsync("UserBased", userId);
    }
}
```

## Alternative Designs
Reset the application!! 😅

**Comment by davidfowl** [comment]
> There comes a time when we need to reset counter for a specific customer or and endpoint.

Can you provide some examples?

Is this at the wrong layer API wise? The options are a poco, they shouldn't have behavior like this.

**Comment by Kahbazi** [comment]
> Can you provide some examples?

For me it happens rarely but a user can do some actions (transfer money, adding contacts, ...) limited number of times per hour/day and when they reached their limits most of them wait! but some of them would call the support team and ask to remove the limit for them. Right now we clear the user key in Redis which holds its data.

**Comment by Tratcher** [comment]
That scenario is interesting, but these APIs don't seem like the right place to implement such an override. I wouldn't expect a support team to create a rate limiter instance like this just to reset an individual's lockout.

More likely they'd have tools that connected to the distributed store directly and reset things at that layer. I think we'd want to design this kind of capability from the bottom up, starting in runtime and working with the distributed stores, and see how it might be exposed to support staff.

**Comment by adityamandaleeka** [comment]
Closing this issue. I left a comment in https://github.com/dotnet/aspnetcore/issues/41861 that this scenario should be considered when that's designed.
