### ISSUE TITLE
Add IStreamClosedFeature

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#42725]
## Background and Motivation

HTTP/3 uses QUIC as a transport. HTTP/3 needs a way to get a notification from QUIC that the connection is closed. Currently, that is done with the `ConnectionContext.ConnectionClosed` cancellation token. It is fired each request which means allocations and overhead. We want a lightweight API for registering a callback with the context.

Note that HTTP/3 is in Kestrel.Core and QUIC is in Kestrel.Transports.Quic so public API is needed to communicate between them.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Connections.Features;

+public interface IStreamClosedFeature
+{
+    void OnClosed(Func<object?, Task> callback, object? state);
+}
```

## Usage Examples

```cs
quicStream.OnClosed(static s =>
{
    var stream = (Http3Stream)s!;

    if (!stream.IsCompleted)
    {
        // An error code value other than -1 indicates a value was set and the request didn't gracefully complete.
        var errorCode = stream._errorCodeFeature.Error;
        if (errorCode >= 0)
        {
            stream.AbortCore(new IOException(CoreStrings.HttpStreamResetByClient), (Http3ErrorCode)errorCode);
        }
    }
    return Task.CompletedTask;
}, this);
```

## Alternative Designs

`IConnectionComplete.OnComplete` was considered, but it should be used once the transport is no longer in use.

HTTP/3 isn't doing any async in the callback, so it doesn't need to return Task. Callback could be `Action<object?>`.

## Risks

Open questions:
* What happens if `OnClosed` is called and the stream has already closed? Error? No-op? Run callback immediately? (running immediately would only be possible if the callback wasn't async)
* In `QuicStreamContext` the cancellation token is canceled inside a call to `ThreadPool.UnsafeQueueUserWorkItem`. This matches what `SocketsConnection` does. Is there any requirement to do the same thing with this API? Does being async or not make a difference?

**Comment by halter73** [comment]
API Review Notes:

- We like running the callback inline if the stream is already closed when the callback is registered
  - Ideally this should be as similar in behavior as possible to the `ConnectionClosed` token. It should just allocate less.
- We don't think the callback needs to return a `Task`.
  - Again we're trying to stay as close to a `CancellationToken` registration as possible with the callbacks.
- Do we need to dispatch?
  - Maybe? Whatever we do as far as dispatching, it should be the same was how we cancel the `ConnectionClosed` token. We can avoid allocations while dispatching if necessary.
  - It doesn't look like we need to await the completion of the callback for any reason.

API Approved!

```diff
namespace Microsoft.AspNetCore.Connections.Features;

+public interface IStreamClosedFeature
+{
+    void OnClosed(Action<object?> callback, object? state);
+}
```

**Comment by davidfowl** [comment]
Does it need to be async?

**Comment by JamesNK** [comment]
The final design isn't async.
