### ISSUE TITLE
Documentation for Microsoft.AspNetCore.SpaProxy

### ISSUE THREAD

**Issue by snebjorn** [dotnet/aspnetcore#42732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm looking for some documentation on what Microsoft.AspNetCore.SpaProxy is capable of. And how it can be configured.

All I currently have to go on is what's been done in the "ASP.NET Core with Angular" template.

### Describe the solution you'd like

Some docs on https://docs.microsoft.com/ or a README in this repo.

**Comment by javiercn** [comment]
@snebjorn thanks for contacting us.

This is a dupe of https://github.com/dotnet/AspNetCore.Docs/issues/26373

**Comment by snebjorn** [comment]
I see. Looking forward to the docs 👍
