### ISSUE TITLE
Enable BindNever or BindingBehavior(BindingBehavior.Never) for Blazor WebAssembly Shared Project(Model)

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/aspnetcore#42736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have implemented a **Single Page Application** using **Blazor WebAssembly**. the solution contains three projects:
1-Server Side Web Api : **MySolution.Server**
2-Client Side Blazor WebAssembly: **MySolution.Client**
3-Shared Project contains **EF Core** Models:**MySolution.Shared**
I use this EF Core Models in my Presentation and Model Binding Directly.
let say we have a simple model named **Person** :
```
public class Person
{
        [BindNever] // doesn't work in Blazor Shared Project and Produces Error
        public int Id{ get; set;}
        public string LastName{get; set;}
        public string Name{get; set;}
}
```
in My Web Api Controller, I want to prevent Model Binding for my EF Core Properties :**Id** and **Name**:
```
public IActionResult CreateNew(Person person)   // [Bind(Exclude("Id"))] is not implemented in DotNetCore
{
      if(ModelState.IsValid)
      {
           //Do Other Works
      }
}
```
### The Problem:
1-You are not Allowed to use `BindNever` or` BindingBehavior(BindingBehavior.Never)` for Models Properties in **Shared Project**.
2-The Exclude property is removed from BindAttribute class in Dotnet. So I can not use following code in my Web Api:
`
public IActionResult CreateNew([Bind(Exclude("Id"))]Person person) // Not Available
`
Request:
**How Can I Exclude Some Properties from Model Binding for Classes that are defined in Blazor Shared Project?**

### Describe the solution you'd like

Like past, please add support for **BindNever** or **Bind(Exclude)** (or something like that) for Models that are defined in **Blazor Shared Project.**

**Comment by mkArtakMSFT** [comment]
This is not possible today, as the model binding attributes are defined in the Mvc.Core assembly, which is part of the ASP.NET Core Shared Framework and you can't reference it from Blazor WebAssembly (as the shared project is referenced from the client project).

What we think you want to do instead, is to utilize the JsonIgnore attribute. Simply decorate the properties that you wish to not get be transferred with the request: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties?pivots=dotnet-6-0

**Comment by hamiddd1980** [comment]
Thanks for reply.but the mentioned solution (using **JsonIgnoreAttribute**) can not solve the problem.
In fact doing this way intensify the problem:
1-in Creating a new item(here **Person** class), it's required and for security reasons recommended to ignore some properties (like Id)//  using [Bind(Exclude)]
2-in other scenarios like **EDIT** and **DELETE** ,I need to extract **Id** property by Model Binder.
by using **JsonIgnoreAttribute** ,**ASPNET core** `ModelState.IsValid`  still returns **False**. 
So I would appreciate it if support for **BindNever** or **Bind(Exclude)** is added to Blazor Webassembly.
Thank you for your consideration.

**Comment by javiercn** [comment]
@hamiddd1980 thanks for the additional details.

Seems that the approach you are trying to take is at odds with the functionality/behavior the framework provides. In these cases, we suggest you create a DTO with the exact data you need to bind and use that instead of trying to reuse the same model across different layers, which might bring complications like the one you are facing.

You can't reference types from Microsoft.AspNetCore.App in a shared library as that brings the dependency everywhere and its not supported on webassembly.
