### ISSUE TITLE
QuickGrid: QuickGridItemsProvider naming suggestion

### ISSUE THREAD

**Issue by alfattack** [dotnet/aspnetcore#42738]
I was having a look at the QuickGrid implementation and noticed that the `GridItemsProviderResult` and `GridItemsProviderRequest` structs as well as the `GridItemsProvider` delegate could be generally useful in custom list components. 

In this case, I was wondering if it would make more sense for the naming to not assume that your component is going to use a grid layout.

**Comment by javiercn** [comment]
@alfattack thanks for contacting us.

We don't have plans to generalize anything inside the QuickGrid to be used elsewhere.

@SteveSandersonMS can chime in if he has different thoughts.

**Comment by SteveSandersonMS** [comment]
Agreed with @javiercn.

Thanks for the feedback @alfattack. We can certainly consider this sort of thing in the long run, but it's much too early to say in what particular ways we'd generalise QuickGrid if/when we brought it into the core framework.
