### ISSUE TITLE
core identity tokens should already be safe for urls

### ISSUE THREAD

**Issue by shearer3000** [dotnet/aspnetcore#42730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Why do the tokens from the UserManager.GenerateEmailConfirmationTokenAsync and UserManager.GeneratePasswordResetTokenAsync methods create codes that aren’t safe for urls i.e. need explicit encoding and decoding. For example, the aspnet core identity scaffolding has this code:

ForgotPassword 
https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/ForgotPassword.cshtml.cs
line 66
`code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));`

ResetPassword
https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/ResetPassword.cshtml.cs
line 100
`code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));`

### Describe the solution you'd like

solution idea: generate tokens that are already url-safe strings by moving the use of the .net library method: WebEncoders.Base64UrlEncode() down into where the code/token is originally generated (i.e. part of User Manager)

**Comment by javiercn** [comment]
@shearer3000 thanks for contacting us.

Identity doesn't presume where the codes are going to be used at that level. It is not the UserManager responsibility but the responsibility of the presentation layer to make sure the code can be presented and read in the right format for a given implementation.

**Comment by blowdart** [comment]
Also by limiting the codes generated to only URL safe characters you'd be reducing the overall entropy available to code generating systems.

So, no, this isn't something we'd do.

**Comment by shearer3000** [comment]
hi @javiercn and @blowdart - actually, Identity does presume where codes are going to be used by its very name, **_aspnetcore_**. reducing the overall entropy by excluding the use or url safe characters - really? not in any significant way that would detriment security. It would be a convenience improvement that should definitely be done/considered further.
