### ISSUE TITLE
Microsoft Default Blazor WASM app not launched in Https configuration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42745]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Microsoft-Default-Blazor-WASM-app-not-la/10096402)._

---
Microsoft Default WASM application was not launched in HTTPs configuration. It was failed with following error.

`Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.`

We have tried the following comments and deleting certificates options by checking other references regarding this issue. Still faced the same issue. Could you please suggest any other way to resolve this issue?

>dotnet dev-certs https –clean

>dotnet dev-certs https -t

---
#### Feedback Bot on 7/15/2022, 02:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Could you provide more details about how you are launching the app? Is this a standalone or hosted app, what environment are you running on? (.NET Version, OS, etc).
