### ISSUE TITLE
dotnet watch run --no-hot-reload still reloads some files

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/aspnetcore#42767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`dotnet watch run --no-hot-reload` appears to still be reloading some files using hot reload when it should be turned off via the command line flag.

Example:

![image](https://user-images.githubusercontent.com/1374013/179420501-0fab2459-ecc8-4349-ad32-7abac8d63c47.png)

### Expected Behavior

Hot reload to not be enabled if I turn it off.

### Steps To Reproduce

* Start application with `dotnet watch run --no-hot-reload`
* Edit a static file in `wwwroot` folder 

### .NET Version

6.0.7

### Anything else?

* Windows 11
* Windows Terminal/PowerShell

**Comment by TanayParikh** [comment]
Thanks for contacting us @RickStrahl. Can you please tell us a bit more about your app (what type of app is it)? A minimal, public, GitHub repro would also be helpful. 

As per the description, the flag only works on "supported apps".

**Comment by RickStrahl** [comment]
It's a ASP.NET Core app MVC/Razor Pages.
