### ISSUE TITLE
Skipped `internal` properties on InvokeAsync<T> calls

### ISSUE THREAD

**Issue by msynk** [dotnet/aspnetcore#42768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The internal properties are getting skipped/ignored on calls to InvokeAsync of JS interop calls.

for example:

```cs
public class Bounds
{
    public double Width { get; set; }
    internal double Height { get; set; }
}
```

```js
function getBoundingClientRect(element) {
    const bounds = element.getBoundingClientRect();
    return {
        width: bounds.width,
        height: bounds.height
    };
}
```

you can see the problem in the result of the following line:

```cs
var bounds = await js.InvokeAsync<Bounds>("getBoundingClientRect", element);
```

---

It's probably because of the limitations of the STJ (discussed here: https://github.com/dotnet/runtime/issues/31511) or something similar, but to be more clear it is a blocking issue for assemblies that don't want to expose their internal types to the outside world.
Btw, I can bypass this issue by making the type itself Internal and changing the properties access modifier to public.

### Expected Behavior

The internal properties should receive their corresponding values from js interop calls.

### Steps To Reproduce

you can see this problem in action in this repo:

https://github.com/msynk/blazor-internal-props-skip-invokeasync

it has both Blazor Server and Wasm.

### .NET Version

6.0.302

**Comment by javiercn** [comment]
@msynk thanks for contacting us.

This is by design. The data gets serialized under the hood using System.Text.Json and that does not serialize internal properties. You can write a custom converter to change that. In addition to that, if you trim the app during publish and the property is not used elsewhere, the trimmer might not infer its usage and remove it.
