### ISSUE TITLE
Disable Tracing in production

### ISSUE THREAD

**Issue by chigivigi** [dotnet/aspnetcore#42776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Staging and Production need to have the same code version. If a problem is detected in production, I need to be able to check trace logs when testing the functionality inside the Stage environment. Trace logs cannot be written in production logs so that I can  keep exception logs for longer periods of time in case they are needed at later date.

### Describe the solution you'd like

I would like to have a option where I can disable trace logs for production environment when adding Blazor Application Insight in WebAssemblyBuilder Services.

**Comment by javiercn** [comment]
Thanks for contacting us @chigivigi.

You can already do this today in the same way it is done by asp.net core either in code or via appsettings.json.

there is however a set of logs that we produce during startup that is not configurable and we have no plans to offer a way to turn them off.
