### ISSUE TITLE
Allow @ref be used with existing declaration syntax, instead of having to declare it seperately

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#42804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Would be nice if I can :
<Element @ref="Element K" style="background-color:purple;"/>
<div @onclick="()=>{do something with K}"/>

instead of :
@code{
Element K;
}
<Element @ref="Element K" style="background-color:purple;"/>
<div @onclick="()=>{do something with K}"/>

### Describe the solution you'd like

^

**Comment by Xyncgas** [comment]
Of course you can also just declare :
```
@code{
Element K = new();
}
//Then use K
```
But my point's would be nice if I can declare it with @ref

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

We don't want to put declarations inside the Markup body, that created great complexity in the compiler for little benefit. There are reasons why we can't autogenerate the `@ref` fields that are explained in similar issues, and we don't plan to address for the time being.

**Comment by Xyncgas** [comment]
Thank you
