### ISSUE TITLE
When the logging fields is all, the request query is not logging

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#42807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/44b3ddd19216a31c9ace4b6f8b8fb74f0643be44/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L178

When the logging fields is all, the request query is not logging

### Expected Behavior

logging  request query

**Comment by Tratcher** [comment]
Hmm, RequestQuery isn't included in any of the aggregates:
https://github.com/dotnet/aspnetcore/blob/44b3ddd19216a31c9ace4b6f8b8fb74f0643be44/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L44
https://github.com/dotnet/aspnetcore/blob/44b3ddd19216a31c9ace4b6f8b8fb74f0643be44/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L161
https://github.com/dotnet/aspnetcore/blob/44b3ddd19216a31c9ace4b6f8b8fb74f0643be44/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L147
https://github.com/dotnet/aspnetcore/blob/44b3ddd19216a31c9ace4b6f8b8fb74f0643be44/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L141

**Comment by adityamandaleeka** [comment]
@Varorbc This was an intentional choice, given that the query might contain sensitive information:

https://github.com/dotnet/aspnetcore/blob/b120cefca18a2000c93e5b297d7a4d68c6e89e47/src/Middleware/HttpLogging/src/HttpLoggingFields.cs#L38-L44

The workaround (as you've figured out) is to use `All | RequestQuery`

@wtgodbe Can you please do a pass on making sure that "All" is clear about what's not included?

**Comment by adityamandaleeka** [comment]
> Although it contains sensitive information, it should include all the contents in the common understanding of people who choose all

I see your perspective, but our general philosophy with these design decisions is to make it unlikely for people to accidentally do something that would compromise privacy/security/etc. Sometimes, such as in this case, that means making certain features be awkward to use or require explicit steps/confirmation (and have appropriate warnings in place).

cc: @blowdart
