### ISSUE TITLE
jQuery License outdated

### ISSUE THREAD

**Issue by janani66** [dotnet/aspnetcore#42815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The additional extensions to the MIT License in https://github.com/dotnet/aspnetcore/blob/main/src/Identity/testassets/Identity.DefaultUI.WebSite/wwwroot/lib/jquery/LICENSE.txt#L33 seem to be outdated.

 The node_modules and external directories are not there and this License seems have already been updated upstream at: https://github.com/jquery/jquery/commit/29e76e254059f8c2b695f4e41054260b52a6910d

Also Upstream License at jQuery mentions to JSFoundation have been replaced with OpenJSFoundation (  https://github.com/jquery/jquery/commit/11611967adf2bd9ff4304132f917629ec1134049 )

See  https://github.com/jquery/jquery/blob/main/LICENSE.txt for latest jQuery License

**Comment by omajid** [comment]
cc @leecow @richlander

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. We're already working to address this, and we should have some updates on this front relatively soon.

/cc @richlander, @ChrisSfanos

**Comment by mkArtakMSFT** [comment]
The 4.0 version of the library has shipped now: https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation/4.0.0

**Comment by mkArtakMSFT** [comment]
The remaining work here is to update the dependencies of test projects to incorporate these updates.
