### ISSUE TITLE
ASP.NET 6 JSON special characters serialization issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42833]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNET-6-JSON-special-characters-serial/10087105)._

---
Hi, I'm working on Blazor Server project and I wish to make special characters like Chinese not encoded, but when I config global setting it doesn't work, I have to apply setting for single `JsonSerializer.Serialize` method, wondering did I do something wrong?
My dotnet version is 6.0.301 and I'm using VS 2022 17.2.1.
`Program.cs`
```using BlazorServer.Data;
using System.Text.Encodings.Web;
using System.Text.Unicode;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Encoder = JavaScriptEncoder
        .Create(UnicodeRanges.BasicLatin, UnicodeRanges.CjkUnifiedIdeographs);
});
builder.Services.AddServerSideBlazor();
...
```
`Index.razor`
```@page "/"

@jsonString

@code {
    public string jsonString { get; set; }
    protected override async Task OnInitializedAsync()
    {
        jsonString = JsonSerializer.Serialize(new
            {
                Name = "你的名字"
            });
    }
}
```
![image.png](https://aka.ms/dc/image?name=Bc8fb5132186c4422ba1ca053dbede9c7637925183986597907_20220704-155957-image.png&tid=c8fb5132186c4422ba1ca053dbede9c7637925183986597907)

---
#### Feedback Bot on 7/4/2022, 10:35 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
When invoked in this fashion, the serialization options will not be pulled from DI. You'll probably want to inject the options into your Razor component and then pass them into the `JsonSerializer.Serialize` call.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
