### ISSUE TITLE
Asp Net Core Identity. After publishing each release validation token is not valid

### ISSUE THREAD

**Issue by wondertalik** [dotnet/aspnetcore#42837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using asp net core 6, razor pages with identity. Everything working perfect. But i have found one small thing that i dont understand.

I am using linux server with kestrel + nginx. After publishing each new release all sended token for validation email going to be failed. I got "VerifyUserTokenAsync() failed with purpose: EmailConfirmation for user.". User should resend new token to validate his email. Why happens this? What should i read?

By the way after each release all logined users should sign one more time.

All detail i have explained in [stackoverflow](https://stackoverflow.com/questions/72859443/asp-net-core-identity-after-publishing-each-release-validation-token-is-not-val)

### .NET Version

6.0.302

**Comment by javiercn** [comment]
@wondertalik thanks for contacting us.

Are you persisting your data protection keys?

**Comment by wondertalik** [comment]
> @wondertalik thanks for contacting us.
> 
> Are you persisting your data protection keys?

What do you mean? Propbably not=). I am using generated appsettings.json, this is probably one file shared between releases.

**Comment by Tratcher** [comment]
Yes, that doc will help you save your encryption keys across app restarts and publishes.

**Comment by wondertalik** [comment]
Nothing changed, added [entityframework provider](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-6.0&tabs=visual-studio#entity-framework-core). Table DataProtectionKeys created, i see one line with some generated value. This token does not changed between releases. 

```
builder.Services.AddIdentity<User, Role>(options =>
    {
        options.SignIn.RequireConfirmedEmail = false;
        options.Password.RequiredLength = 6;
        options.Password.RequiredUniqueChars = 1;
        options.Password.RequireNonAlphanumeric = true;
        options.Password.RequireLowercase = false;
        options.Password.RequireUppercase = false;
        options.Password.RequireDigit = true;
    })
    .AddErrorDescriber<LocalizedIdentityErrorDescriber>()
    .AddEntityFrameworkStores<AppDbContext>().AddDefaultTokenProviders();

app.UseCookiePolicy();

builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>();
```

**Comment by Tratcher** [comment]
Interesting. There's one other config to check, the application's ContentRoot. It should be logged at the start of the app. Does it change run to run?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-6.0&tabs=linux#content-root
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname

**Comment by Tratcher** [comment]
Ah, then you'll need to update the ApplicationName as shown in the data-protection docs.

**Comment by wondertalik** [comment]
> Ah, then you'll need to update the ApplicationName as shown in the data-protection docs.

thanks. thats exactly that i was looking for. working like a charm.
