### ISSUE TITLE
Explicitly Enumerate the Subset of C# Blazor WASM Supports

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [dotnet/aspnetcore#42850]
## Summary

The Blazor documentation says that some things may throw exceptions or fail to run/compile if deployed as Blazor WASM, _yet the MSDN documentation never states what these features are exactly!_

**Comment by javiercn** [comment]
@devshgraphicsprogramming thanks for contacting us.

Can you point out to the article that you are referring to? (For future reference, if you are on a doc page, you can provide feedback about the page directly there).

The only language feature that I can think of will have issues is `dynamic`. Any other language construct should work. Besides that, the other limitations are related to .NET framework features and are related to linking/trimming, which are already documented separately.

**Comment by devshgraphicsprogramming** [comment]
> 



> @devshgraphicsprogramming thanks for contacting us.
> 
> Can you point out to the article that you are referring to? (For future reference, if you are on a doc page, you can provide feedback about the page directly there).
> 
> The only language feature that I can think of will have issues is `dynamic`. Any other language construct should work. Besides that, the other limitations are related to .NET framework features and are related to linking/trimming, which are already documented separately.

https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0#complete-net-api-compatibility

I don't see a list or a link to an explainer about what isnt available.

**Comment by javiercn** [comment]
@devshgraphicsprogramming thanks for the additional details.

There is no static list that you can look anywhere for that. The framework APIs are annotated for the most part when they are specific to a given platform with the `SupportedOSPlatformAttribute` and similar attributes and there is a built-in analyzer that will flag incorrect usages of such APIs.
