### ISSUE TITLE
Blazor , RenderFragment to Raw Html string

### ISSUE THREAD

**Issue by infofromca** [dotnet/aspnetcore#42854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

then, we can use the string for dialog

### Describe the solution you'd like

#9493

**Comment by javiercn** [comment]
@infofromca thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/38114 we would suggest you upvote that issue instead.
