### ISSUE TITLE
[Question] When _transformCache(HashSet<ClaimsPrincipal>)  in AuthenticationService will really help ?

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/aspnetcore#42852]
I was checking how IClaimsTransformation works and look at the code in
https://github.com/dotnet/aspnetcore/blob/db855a52419caa732a169472ae15d6c58681641a/src/Http/Authentication.Core/src/AuthenticationService.cs#L84

At my project I want to extend the original ClaimsPrincipal with few more claims based on the already existing. If I read the code correctly looks like the only way to cache to work is - to return same object extended. Is this correct ? I've tried it , but if I repeat request through Fiddler with the same Bearer token - principal doesn't contain my claims + TransformAsync is called.
Am I missing something in the design here ?
Isn't it better to be dictionary with original principal and transformed one ?

**Comment by wtgodbe** [comment]
@HaoK do you have any comments on this one?

**Comment by HaoK** [comment]
The idea here is to only run transforms once per claims principal instance by default, if you return the same instance it shouldn't reapply transform, this test might also help with understanding the idea:

https://github.com/dotnet/aspnetcore/blob/db855a52419caa732a169472ae15d6c58681641a/src/Http/Authentication.Core/test/AuthenticationServiceTests.cs#L28

But the general idea is we don't want to repeatedly transform the same principal instance

**Comment by TrayanZapryanov** [comment]
Thank you.
