### ISSUE TITLE
Incorrect URL decoding, '%3A' character is mistakenly replaced with ':'

### ISSUE THREAD

**Issue by nlyu** [dotnet/aspnetcore#42859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.NET would ignore the `%3A` character in the request URL.

When we send a request to our ASP.NET MVC app, url: 

 ```
Request starting HTTP/1.1 GET https://localhost:2443/api/apim/sharepointonline/shared-sharepointonl-716950e5-a914-4653-be9e-a0a8e130ced0/datasets/https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FBusinessApplicationsandPlatformBAP/GetFileByPath?path=%2fShared+Documents%2fAnnouncements%2fFAQ%2fBAP+FAQ_Reorg_July+2021.docx&queryParametersSingleEncoded=true
```

The url that we saw on the app end becomes:

```
Request finished HTTP/2 GET https://localhost:10000/api/apim/sharepointonline/shared-sharepointonl-716950e5-a914-4653-be9e-a0a8e130ced0/datasets/https:%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FBusinessApplicationsandPlatformBAP/GetFileByPath?path=%2fShared+Documents%2fAnnouncements%2fFAQ%2fBAP+FAQ_Reorg_July+2021.docx&queryParametersSingleEncoded=true
```

Notice the `%3A` replaced with ':' in the URL. Its causing problem since controller is no longer getting hit.

### Expected Behavior

ASP.NET should not alter any encoding in the URL.

### Steps To Reproduce

Any .NET 6 ASP.NET Core MVC app, send a request to the app like: `https://localhost:10000/api/%3A%2F%2F`

And the app side, we can see the incoming request url becomes: `https://localhost:10000/api/:%2F%2F}`

### .NET Version

6.0.302

**Comment by Tratcher** [comment]
> The url that we saw on the app end becomes:

Do you mean that you're forwarding or proxying this original request to a second app? Can you show how that's being done?

Also, %3A ":" is an explicitly allowed character in uri paths and is not supposed to be encoded.

https://www.rfc-editor.org/rfc/rfc3986#appendix-A
```
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```
https://www.rfc-editor.org/rfc/rfc3986#section-2.2

>    URI producing applications should percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.


How does having it un-escaped interfere with your routing?

**Comment by nlyu** [comment]
[Correct and revise description]
@Tratcher sry my previous statement of `%3A` is removed is wrong. In our observation, it is replaced by `:`.

Add @davidni fyi

The way we reproduce is by launching a simple asp.net app.
And hit the app with url `https://localhost:10000/api/%3A%2F%2F` in broswer.
Then in the debugger I check the app url once the request land on this app, and the url path now becomes `:%2F%2F`

In startup.cs
```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ProcessLifetimeMetrics processLifetimeMetrics, ILogger<Startup> logger)
        {
            app.Use(async (context, next) =>
            {
                // This is no doing anything, just so that we can check what incoming url looks like.
                // Here we see the %3A is replaced by :
                await next.Invoke();
            });

            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            ........ other logic

```

**Comment by Tratcher** [comment]
> Then in the debugger I check the app url once the request land on this app, and the url path now becomes `:%2F%2F`

Which field are you checking?

This is following standard URI normalization rules, you would see something similar for %31 => '1'. How does this normalization affect your application?
