### ISSUE TITLE
builder.RootComponents.Add<App>("#app");

### ISSUE THREAD

**Issue by 731315163** [dotnet/aspnetcore#42855]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

builder.RootComponents.Add<App>("#app"); 

vscode show “ not defined found for app”

```csharp
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Testweb;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
await builder.Build().RunAsync();
```

I dont create "Testweb" namespace

### .NET Version

6.0.101

**Comment by 731315163** [comment]
`
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
await builder.Build().RunAsync();`

**Comment by 731315163** [comment]
C:\project\Web\Chart\Program.cs(3,7): error CS0246: The type or namespace name '**Testweb**' could not be found (are you missing a using directive or an assembly reference?) [C:\project\Web\Chart\Chart.csproj]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear where from the `Testweb` is appearing in your project, given that your project name is (assuming) Chart.
Can you share the exact steps you've used to create that project, so that we can try it out too?
And share a repro project for us too please (hosted as a public GitHub repo).
