### ISSUE TITLE
Problem Restoring NuGet Packages

### ISSUE THREAD

**Issue by Ahmed313522** [dotnet/aspnetcore#42868]
**After Performing following steps:** 
git clone https://github.com/dotnet/aspnetcore.git
git checkout v3.0.0-preview8.19405.7
navigating to src\Mvc and running dotnet restore

**I got the following error**
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\NuGet.targets(123,5): error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json. [D:\aspnetcore\src\Mvc\Mvc.sln]

C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [D:\aspnetcore\src\Mvc\Mvc.sln]

C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [D:\aspnetcore\src\Mvc\Mvc.sln]

**Comment by javiercn** [comment]
@Ahmed313522 thanks for contacting us.

3.0 is out of support, and I don't think we maintain the required artifacts to build it.

**Comment by javiercn** [comment]
/cc: @dotnet/aspnet-build in case they want to add anything.

**Comment by wtgodbe** [comment]
@javiercn is correct - we no longer support that version. I recommend checking out a 3.1 tag instead, like v3.1.27
