### ISSUE TITLE
Using C# in the Internet browser from an ASP.NET MVC application

### ISSUE THREAD

**Issue by vcrobe** [dotnet/aspnetcore#42875]
I want to start using C# in the client side (Internet Browser) of an ASP.NET MVC application when I've to add new features.

Porting it to Blazor is not an option because the app is huge and in active development.

Is there any technical documentation about how Blazor load the .Net framework in the browser?

I really want to stop writing TypeScript/JavaScript code.

Thank you

**Comment by danroth27** [comment]
You could try publishing a standalone Blazor WebAssembly app into your ASP.NET app and then load it by loading blazor.webassembly.js. You could then render root Blazor components based on CSS selectors or [render Blazor components from JavaScript](https://docs.microsoft.com/aspnet/core/blazor/components/?view=aspnetcore-6.0#render-razor-components-from-javascript). This isn't a scenario though that we support in any sort of integrated way.
