### ISSUE TITLE
SignalR guaranteed message delivery

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/aspnetcore#42874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A restaurant is piloting my online food ordering website and back-of-house kitchen displays.  One kitchen workstation in particular frequently doesn't receive the SignalR messages.  The tablet is not losing the SignalR connection, yet the messages never arrive there.  The station may not have perfect internet connectivity.  Nonetheless, I must accommodate such imperfect connectivity.  I've added an Azure SignalR Service to my ASP.NET Core app's deployment to App Service, but I haven't noticed an improvement.

### Describe the solution you'd like

Ideally, I'd like SignalR to guarantee message delivery in the order they were sent.  If that's something you'd consider, please count this issue as a feature request for it.  Regardless, I have to immediately address this issue since the restaurant is relying on my software.  What's the state-of-the-art for guaranteed message delivery on this tech stack?  Is the expectation that I will implement this myself, on top of SignalR?  What are the most popular approaches that other developers are taking?  I'm particularly interested in any popular libraries that already solve this problem, that I can leverage in my code.

**Comment by littlehoneybunnytuttifruttipumpkinpie** [comment]
Maybe try to pull the data from your server via REST/API every 1-5 minutes, as a backup or temporary solution until you get your push issues resolved? This could also be useful as a backup to verify that all clients have all the data, again until you get the sync working perfectly.

**Comment by HappyNomad** [comment]
Another .NET dev I know recommends that I leverage Redis Pub/Sub in a permanent solution.  For each "correct" message that a client receives, it would call the server to acknowledge receipt.  When the server isn't called with the receipt (after a specified time period, I guess), it retries until it does get receipt.  Regarding message sequencing: it only matters for messages concerned with the same subject, so that logic is application-specific.

Is the above approach generally accepted?  Is Redis Pub/Sub state-of-the-art?  What are popular alternatives?

**Comment by BrennanConroy** [comment]
> I'd like SignalR to guarantee message delivery in the order they were sent

This is not something the library will add support for.

> Is the above approach generally accepted? Is Redis Pub/Sub state-of-the-art?

I wouldn't use Redis, unless that was just one layer of your storage, as Redis could go down and would lose all message state. Something like a database or durable queue would likely need to be used for persisting messages long term.

In 7.0 SignalR will have client results which would allow you to easily write an "ack" system by invoking a method on the client and `awaiting` the result on the server side. If the server side gets a successful result then you know the client received the result which will let you know to mark in your storage that the sent message was received by the client.

**Comment by dicksonkimeu** [comment]
Kindly explain the new improvement on .net 7
