### ISSUE TITLE
Microsoft.Extensions.Http.Polly.PolicyHttpMessageHandler  - missing ConfigureAwait(false) in version 6.0.7

### ISSUE THREAD

**Issue by cermakp** [dotnet/aspnetcore#42883]
### Is there an existing issue for this?

Issue is already fixed in version 7.0 preview however not in version 6 - [39874](https://github.com/dotnet/aspnetcore/pull/39874) 

### Describe the bug

Hello,

we are currently using `Microsoft.Extensions.Http.Polly.PolicyHttpMessageHandler` (version 6.0.7) in our project using .NET Framework 4.8. Using `IHttpClientFactory` and `PolicyHttpMessageHandler` causes unfortunately deadlock in our application. We have found the root cause - it is caused by missing of `.ConfigureAwait(false)` in `SendCoreAsync(...)` method.

As we can see this issue has been already fixed but released only in version 7.0 which is currently in preview version. However I would like to ask if it is possible to release the fix also in version 6.

There is a PR fixing that issue already - [link](https://github.com/dotnet/aspnetcore/commit/fbfb11e951c7f4d6776fcbc903e91072021f828c)

Thanks in advance

Pavel

### Expected Behavior

There will not be a deadlock when running in sync Context.

### Steps To Reproduce

1. Create http client in .NET Framework 4.8 project using sync context
2. Define polly policy handler
3. Create request through http client class

### .NET Version

4.8

**Comment by petr-konopelko** [comment]
Hello, Could you please advise when this could be released?
It causes deadlocks in .Net Framework application.
Thank you

**Comment by martincostello** [comment]
Looks like this won't be available until at least the September servicing release on Tuesday the 13th.

**Comment by cermakp** [comment]
> Hello, Could you please advise when this could be released? It causes deadlocks in .Net Framework application. Thank you

Hello, this is also blocker for our project right now. So till the fix is released in version 6, we have forked the version of 6.0.7 and made a fix by ourselves - it means we basically copied the code from the `Microsoft.Extensions.Http.Polly.` and imported it into our code base (there are basically extension methods over the http client implementation - just 2 files).

When the fix will be released in next 6 version we will replace the solution in our project.

**Comment by petr-konopelko** [comment]
> Hello, this is also blocker for our project right now. So till the fix is released in version 6, we have forked the version of 6.0.7 and made a fix by ourselves - it means we basically copied the code from the `Microsoft.Extensions.Http.Polly.` and imported it into our code base (there are basically extension methods over the http client implementation - just 2 files).
> 
> When the fix will be released in next 6 version we will replace the solution in our project.

Yeah, this is the solution for now. Just wanted to know the approximate date it could be released.
Thank you all for the answers)

**Comment by BrennanConroy** [comment]
Like Martin said, this will likely be in September, probably Tuesday the 13th.
