### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

### ISSUE THREAD

**Issue by cwsheng** [dotnet/aspnetcore#42888]
### Describe the bug

Environment
System：Win Server 2016
dotnet : dotnet3.1.100

Occasionally recorded in the log：
The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

### Exceptions (if any)

Describe the bug:

Error Microsoft.AspNetCore.Server.Kestrel Connection id "0HMIL0ROLTD9T", Request id "0HMIL0ROLTD9T:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.
at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.b__1(HttpContext context, Func`1 next)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)

### .NET Version

3.1.100

**Comment by javiercn** [comment]
@cwsheng thanks for contacting us.

We would recommend updating to 6.0 as a first step, publishing the files to the `wwwroot` folder and using `MapFallbackToFile`. Check a brand new .NET 6.0 template for details.

**Comment by cwsheng** [comment]
> @cwsheng thanks for contacting us.
> 
> We would recommend updating to 6.0 as a first step, publishing the files to the `wwwroot` folder and using `MapFallbackToFile`. Check a brand new .NET 6.0 template for details.


.net core 3.1 can't solve this accidental problem

**Comment by javiercn** [comment]
@cwsheng we are not sure what you mean by that.

We recommend that you update to .NET 6.0 because it deals with SPA files using a simplified approach that will avoid the issues you are having.

If you want to stay on 3.1, we need more information to troubleshoot the issue, so we would ask that you provide a minimal repro project as well as detailed steps on how to trigger the issue.

**Comment by cwsheng** [comment]
> @cwsheng we are not sure what you mean by that.
> 
> We recommend that you update to .NET 6.0 because it deals with SPA files using a simplified approach that will avoid the issues you are having.
> 
> If you want to stay on 3.1, we need more information to troubleshoot the issue, so we would ask that you provide a minimal repro project as well as detailed steps on how to trigger the issue.



Since the problem is accidental, the reproduction steps are not clear for the time being.

What else do I need to provide?

**Comment by javiercn** [comment]
@cwsheng unfortunately, we can't make progress without a minimal repro project that clearly demonstrates the issue. Otherwise, we can't tell if it's an issue in the framework or on your environment and we can't effectively investigate.
