### ISSUE TITLE
Is there a way to drag diagram to design via blazor?

### ISSUE THREAD

**Issue by wangrd** [dotnet/aspnetcore#42889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need a vidual editor in my work for the workflow. and i have known blazor has it's stable release, but i haven't found any way or implement for me to make it.

### Describe the solution you'd like

I want use it to design a workflow by draging diagrams. it may like this:
![image](https://user-images.githubusercontent.com/30856466/180680514-093d0cb3-8f06-4e15-9265-d20f4cc57097.png)

### Additional context

As I know, there are some implements via js.

**Comment by javiercn** [comment]
@wangrd thanks for contacting us.

We do not offer features like this, we only work on the core framework functionality. It is not something we plan to offer in the near future (or ever). You can, however, use whatever JS library that suits your needs and create a wrapper to use it with Blazor.
