### ISSUE TITLE
[Blazor] Make IsKnownImmutableType return true for enum

### ISSUE THREAD

**Issue by alix-tlse** [dotnet/aspnetcore#42891]
I see the Guid has been added, can you add the test "type.IsPrimitive  || **type.isEnum** || ..." in the IsKnownImmutableType, because using a constant enum parameter always raise the SetParameter for a component. 

https://github.com/dotnet/aspnetcore/blob/7b22a279ec975335bbb0a7cbadef2e45ee15aa9c/src/Components/Components/src/ChangeDetection.cs#L39

**Comment by alix-tlse** [comment]
OK I send a pull request (it's my first one) : https://github.com/dotnet/aspnetcore/pull/42901

**Comment by javiercn** [comment]
@alix-tlse no worries. We'll help along the way.
