### ISSUE TITLE
Maximum number of WebSocket connections caps at 10

### ISSUE THREAD

**Issue by vgt-lukas-oberholzer** [dotnet/aspnetcore#42898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running a .NET Core Web API with WebSocket (System.Net.WebSockets.WebSocket) handling on IIS or Azure the maximum number of concurrent connections open seems to be 10. Further connections opened are stuck in the connecting state until another already established connection closes.

This issue seems to be related to the issue reported [here](https://github.com/dotnet/AspNetCore.Docs/issues/19330).

### Expected Behavior

Unlimited (or limited by the IIS or Azure) concurrent connections of WebSockets open at the same time.

### Steps To Reproduce

1. Using IIS 10 on a Windows 10 Pro machine. _OR_ Using Azure Hosting with App Services.
2. Hosting a .Net Core Web API on the IIS (or Azure).
3. Implementation of a WebSocket Handler like [this tutorial from YouTube](https://www.youtube.com/watch?v=2QS55uqcRrg) or the [official MS docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0) (I tested both).
4. Using a WebSocket library of your choice to connect to the server. After the 10th connection no more connections are accepted by the server.

### .NET Version

6.0.200

### Anything else?

Using Microsoft Visual Studio 2022 (64-bit) - Version 17.1.0

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Possibly related: https://github.com/dotnet/AspNetCore.Docs/issues/19330

**Comment by davidfowl** [comment]
This is an old windows client limitation when using IIS. Fixes are:
- Use windows server 
- Use kestrel 
- Use Linux

**Comment by vgt-lukas-oberholzer** [comment]
Thanks @davidfowl for the answer. I've done some further testing on a Windows Server 2016 with an IIS on which it works perfectly fine. So it really seems that the Windows 10 Pro (or Home) is the issue. 

Also I did some further debugging on the Azure App and found out that it isn't related to this issue as the `await _socket.ReceiveAsync(...);` blocks the entire request queue despite being run asynchronous by the `HttpGet`. Because of this it made the impression that Azure suffered from the same issue but it didn't.
