### ISSUE TITLE
using httprequest pipereader in a custom middleware to read request body

### ISSUE THREAD

**Issue by ok10d** [dotnet/aspnetcore#42900]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Pipeline pipereader example in this [document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-6.0) works in Kestrel but when the same API is deployed in IIS, I am getting “non-empty request body is required” fluent validation error. 

When I add enablebuffering to request, it also works in IIS. I am bit confused because according to documentation enablebuffering ensure multiple reads for request body. GetListOfStringFromPipe does not use request’s body stream but uses request’s pipereader.

context.Request.EnableBuffering();
 GetListOfStringFromPipe(contect.Request.BodyReader);
context.Request.Body.Position = 0;

What is the correct way of using pipereader in a custom middleware to read httprequest body?

```cs

private async Task<List<string>> GetListOfStringFromPipe(PipeReader reader)
{
    List<string> results = new List<string>();

    while (true)
    {
        ReadResult readResult = await reader.ReadAsync();
        var buffer = readResult.Buffer;

        SequencePosition? position = null;

        do
        {
            // Look for a EOL in the buffer
            position = buffer.PositionOf((byte)'\n');

            if (position != null)
            {
                var readOnlySequence = buffer.Slice(0, position.Value);
                AddStringToList(results, in readOnlySequence);

                // Skip the line + the \n character (basically position)
                buffer = buffer.Slice(buffer.GetPosition(1, position.Value));
            }
        }
        while (position != null);


        if (readResult.IsCompleted && buffer.Length > 0)
        {
            AddStringToList(results, in buffer);
        }

        reader.AdvanceTo(buffer.Start, buffer.End);

        // At this point, buffer will be updated to point one byte after the last
        // \n character.
        if (readResult.IsCompleted)
        {
            break;
        }
    }

    return results;
}

private static void AddStringToList(List<string> results, in ReadOnlySequence<byte> readOnlySequence)
{
    // Separate method because Span/ReadOnlySpan cannot be used in async methods
    ReadOnlySpan<byte> span = readOnlySequence.IsSingleSegment ? readOnlySequence.First.Span : readOnlySequence.ToArray().AsSpan();
    results.Add(Encoding.UTF8.GetString(span));
}

```

### Describe the solution you'd like

IIS and Kestrel should have the same behaviour

**Comment by adityamandaleeka** [comment]
@ok10d Can you please share more info? What is the actual exception you're getting (and stack trace)? And please provide a minimal repro if possible.

**Comment by davidfowl** [comment]
Are you using mvc? Does your action method posts body? Then it needs to be buffered and reset.

**Comment by ok10d** [comment]
> Are you using mvc? Does your action method posts body? Then it needs to be buffered and reset.

UseMvc is not called, Project is an API project but I see that Controllers are derived from Controller class in Microsoft.AspNetCore.Mvc namespace.
I tried to repro it in a new API broject but it failse both for Kestrel and IIS.

Action is an HttpPost :
```csharp
[HttpPost]
[Route("/somemodel/process")]
[ProducesResponseType(201)]
[ProducesResponseType(400)]
[ProducesResponseType(401)]
public async Task<ActionResult<SomeModel >> Process([FromBody] SomeModel body)
{

}

````

**Comment by ok10d** [comment]
> Are you using mvc? Does your action method posts body? Then it needs to be buffered and reset.

Can you also guide me on how to buffer and reset HttpRequest's BodyReader?
Thanks.

**Comment by davidfowl** [comment]
You’re using Mvc (controllers). You need to enable Buffering on the steam the way you did before:

context.Request.EnableBuffering();
GetListOfStringFromPipe(context.Request.BodyReader);
context.Request.Body.Position = 0;

the pipe itself isn’t resettable but when you enable buffering on the request. It should do the right thing.
