### ISSUE TITLE
[Blazor] Using the `<Navigating>` parameter in the Router causes a re-render of all components of the Layout on navigation

### ISSUE THREAD

**Issue by msynk** [dotnet/aspnetcore#42902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After adding the `<Navigating>` parameter to the Router, all of the components on the Layout (for example, NavMenu or Header) get re-rendered on each navigation and their full lifecycle methods will run again.
This happens for components of a page too if no actual route change happens (for example clicking on a navlink/link with href of the current route url).
This causes all states of components of the Layout to be lost and basically makes the Navigating component unusable in some cases.

### .NET Version

6.0.302

**Comment by javiercn** [comment]
@msynk thanks for contacting us.

What is the `Navigating` component? We do not ship any such component as part of the framework.

**Comment by msynk** [comment]
@javiercn 
sry about the misinformation, I've already edited the issue, it's a Router parameter actually

**Comment by javiercn** [comment]
@msynk thanks for contacting us.

Very likely is because your navigating RenderFragment doesn't contain a Layout within it, you should specify the same Layout using the LayoutDisplay component to make sure that the component is reused.

**Comment by msynk** [comment]
@javiercn thanks for your response.

I've already tested this parameter with the `LayoutView` component. I'm not sure if it makes any difference but lemme test it out with `LayoutDisplay` too.

**Comment by msynk** [comment]
It seems there is no `LayoutDisplay` component. can you please provide a sample that explains your solution?
this is my Router configuration:

```razor
<Router AppAssembly="@typeof(App).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
    <Navigating>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Navigating...</p>
        </LayoutView>
    </Navigating>
</Router>
```

**Comment by javiercn** [comment]
@msynk I meant `LayoutView`

**Comment by msynk** [comment]
@javiercn yeah ok
So, as you can see in the sample code I've provided in the previous comment, using the LayoutView won't fix anything.
it gets renewed and re-rendered and loses its state.

**Comment by javiercn** [comment]
@msynk do you mean that the component gets disposed and a new one gets created or do you mean that OnParametersSet gets called. If you are not sure, implement `IDisposable` and check if it is getting called.

**Comment by SteveSandersonMS** [comment]
This is expected. You have a totally separate `<LayoutView>` component instance inside `<Navigating>`, so that new instance (and any descendant components) will be constructed each time `<Navigating>` is displayed, and then torn down when it switches back to `<Found>`.

There are two main ways to deal with this:

1. Keep the state you want outside the layout component instance, so it doesn't matter if the layout component instance changes
2. Or, move the layout rendering outside the `<Router>` so it retains the same instance indefinitely. For example, change `App.razor` to:

```razor
<LayoutView Layout="@typeof(MainLayout)">
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <PageTitle>Not found</PageTitle>
            <p role="alert">Sorry, there's nothing at this address.</p>
        </NotFound>
        <Navigating>
            <p>Navigating...</p>
        </Navigating>
    </Router>
</LayoutView>
```

**Comment by msynk** [comment]
@SteveSandersonMS 
thanks a lot. it clears a lot of things for me.

**Comment by msynk** [comment]
@SteveSandersonMS @javiercn @mkArtakMSFT 
I suggest changing the default project template of Blazor (both Server and WASM) use the code you've shown above, instead of this one:

```razor
<Router AppAssembly="@typeof(App).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```
