### ISSUE TITLE
Question: catch-all route difference between '*' and '**'

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#42909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sample code:

``` c#
app.UseRouting();

app.UseEndpoints(endpoints =>
{
    endpoints.Map("/test1/{*any}", (string any) => $"test1 {any}");
    endpoints.Map("/test2/{**any}", (string any) => $"test2 {any}");
});
```

![image](https://user-images.githubusercontent.com/7604648/180900305-76afcc70-d463-4eda-8383-f5a65dda42f0.png)
![image](https://user-images.githubusercontent.com/7604648/180900430-3f173f60-8dbe-45be-80e7-7cef6f503597.png)

It seemed these two patterns have the same behavior, then what's the difference?

### Expected Behavior

From the document

![image](https://user-images.githubusercontent.com/7604648/180907399-8ca40a3c-0a8d-4f4f-b0e3-c0194a89fcb2.png)

Maybe the '*' route should output `test1 hello%20abc`?

### .NET Version

6.0

**Comment by javiercn** [comment]
@WeihanLi thanks for contacting us.

The difference applies when you are generating a link via LinkGenerator or IUrlHelper, if you are just returning the string from the endpoint, the behavior is the same.

**Comment by WeihanLi** [comment]
@javiercn thanks very much for your reply
