### ISSUE TITLE
Query params arrays with empty square bracket notation (HTTP GET)

### ISSUE THREAD

**Issue by markwalsh-liverpool** [dotnet/aspnetcore#42921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is an expectation from prior frameworks that both empty square brackets notation query param binding would also work along with non-square bracket notation, either that or I've failed to find the relevant documentation. 

### Expected Behavior

Given the following repository:

https://github.com/markwalsh-liverpool/Repo

I'd expect both requests to successfully be deserialized:

https://localhost:7074/WeatherForecast?Ids%5B%5D=1&Ids%5B%5D=2&Statuses%5B%5D=1&Statuses%5B%5D=2
https://localhost:7074/WeatherForecast?Ids=1&Ids=2&Statuses=1&Statuses=2

But only the second is

### Steps To Reproduce

https://github.com/markwalsh-liverpool/Repo

Run API and then perform a GET to:

https://localhost:7074/WeatherForecast?Ids%5B%5D=1&Ids%5B%5D=2&Statuses%5B%5D=1&Statuses%5B%5D=2
https://localhost:7074/WeatherForecast?Ids=1&Ids=2&Statuses=1&Statuses=2

### Exceptions (if any)

N/A

### .NET Version

6.0.301

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by davidfowl** [comment]
The documentation is here https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0.

**Comment by markwalsh-liverpool** [comment]
@davidfowl It does indeed explain the expected behaviour here:

https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections-1

Specifically:

`selectedCourses[]=1050&selectedCourses[]=2000 `

For the POST

`public IActionResult Post(string productIndex, List<Product> products)`

Which may work in a post but if you check my repo in the steps to reproduce it doesn’t behave this way on a GET.

**Comment by brunolins16** [comment]
@markwalsh-liverpool sorry about that but this documentation was updated recently, and we accidentally removed the following:

![image](https://user-images.githubusercontent.com/12376385/181618493-85f59b7f-dc7b-47ee-920b-4a3b3a1adbb2.png)

Basically, the syntax without the index is only allowed with `form data` and you should specify an index zero-based when in a `query string`:

`selectedCourses=1050&selectedCourses=2000 `
or
`selectedCourses[0]=1050&selectedCourses[1]=2000`
or
`[0]=1050&[1]=2000`
or
`selectedCourses[a]=1050&selectedCourses[b]=2000&selectedCourses.index=a&selectedCourses.index=b`
or
`[a]=1050&[b]=2000&index=a&index=b`

I will have the documentation fixed soon.

**Comment by markwalsh-liverpool** [comment]
Cool! Makes sense.  It’s not a blocker or anything for me, just wondered why the behaviour had changed since .Net Core but good to know the docs are soon to be updated
