### ISSUE TITLE
Rename `AddEndpointFilter` to `AddEndpointFilterFactory`

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#42933]
## Background and Motivation

In preview3, we added `AddFilter` overloads that allowed a user to register a filter onto route handler through either a filter delegate or a filter factory delegate. The same method name is used for both overloads that take different delegate types, however but current limitations make it hard to disambiguate between two overloads with delegate types. To work around this and make user code more readable, we propose renaming `AddEndpointFilter` with a filter factory delegate to `AddEndpointFilterFactory`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public static class EndpointFilterExtensions
{
-   public static TBuilder AddEndpointFilter<TBuilder>(this TBuilder builder, Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate> filterFactory)
        where TBuilder : IEndpointConventionBuilder
+   public static TBuilder AddEndpointFilterFactory<TBuilder>(this TBuilder builder, Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate> filterFactory)
        where TBuilder : IEndpointConventionBuilder
}
```

## Usage Examples

**Before**
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => {})
  .AddEndpointFilter((invocationContext, next) => {
    return next(invocationContext);
})
  .AddEndpointFilter((routeHandlerContext, next) => {
    return invocationContext => next(invocationContext);
});
```

**After**
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => {})
  .AddEndpointFilter((invocationContext, next) => {
    return next(invocationContext);
})
  .AddEndpointFilterFactory((routeHandlerContext, next) => {
    return invocationContext => next(invocationContext);
});
```

**Comment by halter73** [comment]
I think that the `AddEndpointFilterFactory` name clears up a lot of ambiguity between the factory and per-invocation delegate overloads of `AddEndopointFilter`. I assume the `Func<EndpointFilterInvocationContext, EndpointFilterDelegate, ValueTask<object?>>` overload will be the more common one, so having it keep the shorter existing name makes sense.

I wonder if it would make sense to have a reference from `EndpointFilterInvocationContext` to the associated `EndpointFilterFactoryContext` in case someone wants to quickly access the `MethodInfo` or some other useful thing we add to the context later. Right now, you can access all the same info from `EndpointFilterInvocationContext.HttpContext` with some effort if you really want to, so it's not really necessary, but `EndpointFilterInvocationContext` is an abstract class being introduced for the first time, so it makes sense to add this now if we think it makes sense.

**Comment by halter73** [comment]
On second thought, if people want to `EndpointFilterFactoryContext`, they can just use `AddEndpointFilterFactory`.

**Comment by captainsafia** [comment]
> I wonder if it would make sense to have a reference from EndpointFilterInvocationContext to the associated EndpointFilterFactoryContext in case someone wants to quickly access the MethodInfo or some other useful thing we add to the context later.

Yeah, I worry that this will exasperate the "context fatigue" users will have when dealing with all these context types and the APIs that use/consume them.

> On second thought, if people want to EndpointFilterFactoryContext, they can just use AddEndpointFilterFactory.

Yep, I don't necessarily see a scenario where using `AddEndpointFilter` with an `EndpointFilterInvocationContext` that contains an `EndpointFilterFactoryContext` is better than just using `AddEndpointFilterFactory` directly.
