### ISSUE TITLE
Selectively Enable/Disable HealthChecks

### ISSUE THREAD

**Issue by francedot** [dotnet/aspnetcore#42939]
## Background and Motivation

In the current implementation, HealthChecks are set to run always. This can cause unneedeed noise, especially during debugging sessions.

We should come up with a simpler mechanism to quickly enable/disable HealthCheck, in order for the developer to focus on the debugging session of the HealthCheck under investigation.

API proposal is to introduce per-HealthCheck `IsEnabled` at the `HealthCheckRegistration` level, as with the following example:

```csharp

// Usage Example: fetch the registrations from the HealthCheckServiceOptions and disable the target HealthCheck
var registrations = healthCheckServiceOptions.Value.Registrations;
registrations.First(r => r.Name == "DisabledCheck1").IsEnabled = false;

```

### HealthCheckRegistration.cs

```diff

namespace Microsoft.Extensions.Diagnostics.HealthChecks;

public sealed class HealthCheckRegistration
{
+    public bool IsEnabled { get; set; } = true; // Enabled by default
}

```
## Usage Examples

Based on a JSON Configuration file, user can develop a FileSystemWatcher observing which HealthCheck should be enabled in the current debugging session. Example:

```json
// appsettings.json
"HealthCheckSettings": [
     {
     "HealthCheckName": "GetNamesApiCheck",
     "IsEnabled": false
     },
     {
     "HealthCheckName": "GetActionsApiCheck",
     "IsEnabled": true
     }
]
```

```csharp
// Program.cs
var registrations = healthCheckServiceOptions.Value.Registrations.ToDictionary(r => r.Name, r => r);

foreach (var healthCheckSetting in healthCheckSettings) {
     registrations[healthCheckSetting.HealthCheckName] = healthCheckSetting.IsEnabled;
}
```

## Alternative Designs

It is currently possible to implement the same pattern above using `Predicates`, which can be difficult to code for simple and quick use cases like this.
Also, if we take into consideration PR #42646 we might want to disable the underlying Timers if the `HealthCheckRegistration` is set to `IsEnabled=false`.  For this purpose, we can have the `PublisherHostedservice` observe changes in the `HealthCheckRegistrations` and update the corresponding Timers accordingly.

## Risks

None.

**Comment by sebader** [comment]
I really like the proposal! just ran into the same very use case

**Comment by francedot** [comment]
Update: an implementation is now provided as part of https://github.com/dotnet/aspnetcore/pull/42646

**Comment by francedot** [comment]
API proposal https://github.com/dotnet/aspnetcore/issues/42645 to include selectivity based on the individual `HealthCheckPublisherOptions` Predicate.
