### ISSUE TITLE
Trying to set ChannelPrefix for Redis SignalR Backplane but prefix is being ignored

### ISSUE THREAD

**Issue by suntereo** [dotnet/aspnetcore#42942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to prefix my Redis SignalR backplane using ChannelPrefix.

It's honoring the prefix setting for the first approach shown below. But it's not honoring it for the second.

Approach 1 -- This works:
```
.AddSignalR()
.AddStackExchangeRedis("MyConnectionStringHere", options =>
{
    options.Configuration.ChannelPrefix = "ThisPrefixWorks_";
});
```
If I monitor the Redis profiler, I can see that the prefix is successfully applied. Great!

Approach 2 -- This does not work:
```
.AddSignalR()
.AddStackExchangeRedis(option =>
{
    option.Configuration.ChannelPrefix = "ThisDoesNotWork_";
    option.ConnectionFactory = async writer =>
    {
        ...
    };
});
```
If I monitor the Redis profiler, I see that the prefix is not applied.

### Expected Behavior

I would expect that the prefix would be applied for approach 2 but it is not. It is as if the prefix is not being set at all. 

### .NET Version

6.0.300

### Anything else?

I'm using ASP.Net Core .Net 6 and StackExchange.Redis 2.6.48.

**Comment by BrennanConroy** [comment]
If you supply a value for `ConnectionFactory` then there is no way we can set any of the values from `Configuration` since you own the creation of the `IConnectionMultiplexer`.

**Comment by suntereo** [comment]
Ahhhhh. That makes sense. Thank you!

For anybody else with same problem, here's how I resolved based on Brennan's answer:

```
.AddSignalR()
.AddStackExchangeRedis(option =>
{
    option.ConnectionFactory = async writer =>
    {       
		var connection = await ConnectionMultiplexer.ConnectAsync(
			"MyConnectionStringHere",
			options => { options.ChannelPrefix = "ThisWillWork_"; }, // do this instead
			writer
		);
							
		...

        return connection;
    };
});
```
