### ISSUE TITLE
Scaffolding Identity breaks ApplicationDbContext

### ISSUE THREAD

**Issue by bsimser** [dotnet/aspnetcore#42947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There seems to be a bug when you create a new project using Individual Accounts then add a new Identity scaffolded item. It ends up duplicating the ApplicationDbContext class, even though you specify the existing one when scaffolding the item.

NOTE: This works with *any* identity override, not just the one listed in the steps to reproduce.

### Expected Behavior

Expected Behavior:

- Existing ApplicationDbContext class in Data folder is updated

Actual Behavior:

- New ApplicationDbContext class is created in Areas/Identity/Data
- Project won't compile because there are two ApplicationDbContext classes in the project

### Steps To Reproduce

1. Create new project using ASP.NET Core Web App (Model-View-Controller)
2. Select Individual Accounts for Authentication type
3. Build and run the project and run the initial migrations
4. Right click on the project and add an scaffolded item
5. Select Identity
6. Select your layout (/Views/Shared/_Layout.shtml)
7. Select a file to override (Account\Manage\EnableAuthenticator)
8. Choose your existing Data context class from the dropdown
9. Click Add 

### .NET Version

6.0.302

### Anything else?

Visual Studio Professional 2022 Version 17.2.6

**Comment by HaoK** [comment]
@deepchoudhery is this something you are aware of?

**Comment by deepchoudhery** [comment]
Yup aware of this issue. Fix coming out soon.

**Comment by HaoK** [comment]
Thanks @deepchoudhery please close this issue once the fix is in

**Comment by bsimser** [comment]
This is labeled with the 7.0-rc1 milestone. Does that mean it won't be fixed for .NET 6 then and only 7?

**Comment by deepchoudhery** [comment]
It will be fixed for both .NET 6 (next servicing update) and .NET 7.

**Comment by adityamandaleeka** [comment]
@deepchoudhery Has this fix been merged?

**Comment by deepchoudhery** [comment]
Yes it has been merged and is out now in 6.0.8 and 7.0.0-Preview7. Closing.
