### ISSUE TITLE
Don't log exception in exception handling middleware

### ISSUE THREAD

**Issue by stevendarby** [dotnet/aspnetcore#42950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If using `UseExceptionHandler()` middleware and `ExceptionHandlerOptions.ExceptionHandler` to handle an exception, the exception is still logged as an Error with the message "An unhandled exception has occurred while executing the request."

https://github.com/dotnet/aspnetcore/blob/6df6573d746f4a3b12cea51af9a15bfab9e0743a/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L115

This seems wrong - given the name of the middleware & the name of the delegate on the options, this is all about handling an exception, so seeing a log about an unhandled exception is surprising.

This comes up from time to time and workarounds are given for how to remove it from logs e.g. https://stackoverflow.com/questions/59553325/prevent-microsoft-logging-from-log-when-unhandled-exception-thrown

### Describe the solution you'd like

Don't log, so people don't have to workaround it. Application code can log it if needed. Perhaps the middleware could log it as an unhandled error, but only after it's given a chance to be handled.

**Comment by adityamandaleeka** [comment]
Triage: We believe that having the log message here is the appropriate default. As you've already seen, you can disable this by setting your log level to `None` for `Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware`

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#configure-logging
