### ISSUE TITLE
use minimal apis can not get entpoint in Middleware

### ISSUE THREAD

**Issue by MayueCif** [dotnet/aspnetcore#42957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in my project,i use minimal apis instead controller。i want to use middleware get entpoint metadata,but it not work,i saw .net 7 preview4 add filter, solve this problem?
middleware code like this
```
public async Task InvokeAsync(HttpContext context)
    {
        //context.GetEndpoint().Metadata
        Console.WriteLine($"Endpoint: {context.GetEndpoint()?.DisplayName ?? "(null)"}");
        await _next(context);
    }
```
route code like this
```
app.MapGet("/test", [MasaAuthorize] () => {
    return "test";
});
```

### .NET Version

6.0.302

### Anything else?

.NET SDK (反映任何 global.json):
 Version:   6.0.302
 Commit:    c857713418

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

**Comment by davidfowl** [comment]
I'm unclear on what you're trying to do. The code below works for me when I hit the "/test" end point. 

```c#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.Use((context, next) =>
{
    var ep = context.GetEndpoint();
    var auth = ep?.Metadata.GetMetadata<MasaAuthorize>();
    
    return next(context);
});

app.MapGet("/test", [MasaAuthorize] () => "Hello World!");

app.Run();

[System.AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = true)]
sealed class MasaAuthorize : Attribute
{
}
```

**Comment by MayueCif** [comment]
Sorry, it's my problem,app.Use In the wrong place，i modify my code  `app.UseRouting`-> `app.Use`->`app.UseEndpoints`,it`s worked.
