### ISSUE TITLE
Adding UseHttpsRedirection conditionally via UseWhen fails in ASP.NET Core 6

### ISSUE THREAD

**Issue by cieciurm** [dotnet/aspnetcore#42959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'd like to conditionally include `UseHttpsRedirection` middleware using `UseWhen` extension method on `IApplicationBuilder`.

I've found an example on: https://haacked.com/archive/2020/09/28/azure-swap-with-warmup-aspnetcore/

```C#
public void Configure(IApplicationBuilder app)
{
    // ...
    app.UseWhen(context =>
    {
        var path = context.Request.Path.Value ?? string.Empty;
        return !path.Equals("/statuscheck", StringComparison.OrdinalIgnoreCase);
    },
    mainApp =>
    {
        mainApp.UseHttpsRedirection();
    });
    // ...
}
```

This works just fine on ASP.NET Core 3.x

I tried doing the same thing in version 6 and got the Null Reference Exception when executing `mainApp.UseHttpsRedirection();` on application startup.

### Expected Behavior

Should not throw a Null Reference Exception

### Steps To Reproduce

- Generate ASP.NET Core Web API app from the VS template
- Add the snippet mentioned above
- Run
- See a Null Reference Exception being thrown

### Exceptions (if any)

Null Reference Exception

### .NET Version

6.0.301

### Anything else?

The generated app from the template has a reference to `Microsoft.AspNetCore.App.Ref` in version `6.0.6`

**Comment by davidfowl** [comment]
I can reproduce the error:

```C#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.UseWhen(context =>
{
    return true;
},
static app =>
{
    app.UseHttpsRedirection();
});

app.Run();
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/95136/181496902-0e071038-bef1-4593-8f8e-39ade7d5a560.png">

Here's a more minimal repro (and unit test for the fix):

```C#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

var serverFeatures = ((IApplicationBuilder)app).ServerFeatures; // This is non null
var serverFeauresNew = ((IApplicationBuilder)app).New().ServerFeatures; // This is null

app.Run();
```

**Comment by davidfowl** [comment]
Side note: @JamesNK seems like that nullability wise [IApplicationBuilder](https://github.com/dotnet/aspnetcore/blob/f7b8b7e16bcab537fb9872a26cfb1e0d3a3a253c/src/Http/Http.Abstractions/src/IApplicationBuilder.cs) might be wrong? Or maybe our implementations should be throwing?

**Comment by davidfowl** [comment]
Oh look this was reported https://github.com/dotnet/aspnetcore/issues/40042 😄

**Comment by campersau** [comment]
The [fix](https://github.com/dotnet/aspnetcore/pull/40183) did not get backported as you can use
```c#
((IApplicationBuilder)app).Properties["server.Features"] = ((IApplicationBuilder)app).ServerFeatures;
```
as a workaround.

https://github.com/dotnet/aspnetcore/issues/40042#issuecomment-1039314443

**Comment by davidfowl** [comment]
Yea, we should backport this fix to 6.0

**Comment by halter73** [comment]
> Side note: @JamesNK seems like that nullability wise [IApplicationBuilder](https://github.com/dotnet/aspnetcore/blob/f7b8b7e16bcab537fb9872a26cfb1e0d3a3a253c/src/Http/Http.Abstractions/src/IApplicationBuilder.cs) might be wrong? Or maybe our implementations should be throwing?

Agreed. Throwing or even just returning an empty feature collection seem preferable to returning null.

**Comment by adityamandaleeka** [comment]
Closing, this was merged into 6.
