### ISSUE TITLE
Blazor startup before DOM Content Loaded leads to malformed component error

### ISSUE THREAD

**Issue by TheAtomicOption** [dotnet/aspnetcore#42954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor server with pre-rendering, using autostart, can sometimes fail to boot when it runs before all prerendered DOM content is loaded. This results in an opaque 'malformed component' error when (in my specific example case) the comment marking the end of the component is not found in the iterator over `.childNodes`

I investigated this primarily using Chrome 104, but coworkers have occasionally encountered the bug in other browsers. Firefox seems to have this problem much less frequently. 

### Expected Behavior

blazor.server.js running with autostart should either:

a) wait to automatically boot until all DOM content has loaded by default
b) wait to automatically boot until it's certain that all blazor related DOM content has loaded into the DOM
c) on failure to find any part of a component comment, check/wait until the DOM is more fully loaded and reattempt before throwing an error.

### Steps To Reproduce

**What would constitute a repro, and why I'm not sure how to create one**

The key for creating a repro is for blazor.server.js to autostart prior to the `DOMContentLoaded` event such that the iterator over prerendered nodes does not yet contain the blazor end comment. While I'm certain of the problem, I'm uncertain how to create a small and consistent example which does this as JS doesn't offer an obvious way to do this on purpose.

In my case this was happening at a point where the first 50 childNodes of prerendered component html inside Blazor's containing element have loaded, but not the html comment with prerenderid marking the end of the Blazor component. Inside blazor.server.js since the loop over the iterator completes without finding the end comment, it throws an error stating that the end comment was not found. This error is caught in the outer component discovery function, and discarded in favor of a more generic error for "malformed component" (see exceptions block) which is thrown to the browser's console. 

---

**Some stats on the page this is occurring in**

The prerendered document this occurs in is approximately 100kb and 1000 lines of HTML with about 30 js scripts of various sizes outside of blazor.server.js. the script tag for blazor.server.js is at about line 450 about one hundred lines above the blazor start comment at about line 550 with the end comment being at about 780. 

---

**Current workaround**

My current attempt at a work around is to set autostart to false and use `document.addEventListener("DOMContentLoaded", function() { Blazor.start(); });` But I've been unable to find any documentation about how to determine when this is _necessary_ or what I might have been doing wrong to make this error possible with autostart in the first place.

### Exceptions (if any)

example exception:
```
Uncaught (in promise) Error: Found malformed component comment at Blazor:{"sequence":0,"type":"server","prerenderId":"bf67aeb283414d3c90e694ae186c02b4","descriptor":"CfDJ8K9cH\u002Bv7LtlOmuMX\u002BkP7jAxrDYBdcj7cWijRXjIKSSD4EQMdI70QYXgojNbx\u002BzmdrDsWlos5v9yR69\u002BteNEa\u002BqoAsAQBxod27ewPqtMmiNTHh3egKB3Wbmegoy7OcUw5K23IxuXpONtcvzRIAiznQJmFl2gfLJya76OO4gyPG8M0r4azv7AsmuogDjS9ju28bq7nOFD0h1N1nCer\u002B5Slbg/yL7r7TtszlBt2SzGZedGwEy23TviwwYUtujZTugzzf9UfC\u002BdGp08rLlv7qft2sDAssFNqP0nx4vdFor2wlGI6MhV2Wjwh9eZeBLN43oxI2IJWXsCOef3nBhlE7JtY\u002BBae1E7KSbOYuBQ2AxYMtnfQjLKmh/wAnZ5eGbDyKI\u002BrEwyS2saL/rspmYrCNTMN5bofJjpczB6knKX1n94UO6RnTHLFRsbGtfU0f8YggiIiEMKwKVdsRBOrwBV\u002Bly6/sOke1jlUF7jgtiNI2uAFYLCHzAYAgsXE0xvJ6fqOOopv3Q=="}
    at zn (ComponentDescriptorDiscovery.ts:149:15)
    at jn (ComponentDescriptorDiscovery.ts:112:30)
    at jn (ComponentDescriptorDiscovery.ts:116:28)
    at jn (ComponentDescriptorDiscovery.ts:116:28)
    at jn (ComponentDescriptorDiscovery.ts:116:28)
    at ComponentDescriptorDiscovery.ts:11:29
    at ComponentDescriptorDiscovery.ts:6:14
    at Zn (Boot.Server.ts:54:22)
```

### .NET Version

.NET 6.0.7

### Anything else?

**If for any reason no other action is taken, please improve the error message:** 

It would be very helpful if the "malformed component" exception included text to the effect of "The Blazor comment nodes may not have been loaded by the DOM yet, or may have been altered or removed."

Getting to the root of this has required many hours of investigation by myself and other devs at my company because the only useful clue/reference I'd found online about this was [this comment mentioning that it might have to do with things in the DOM](https://github.com/dotnet/aspnetcore/issues/39580#issuecomment-1015653044).

---

Thanks for reading!

**Comment by javiercn** [comment]
@TheAtomicOption thanks for contacting us.

By default Blazor starts when the script gets loaded. There are ways in JavaScript to control this, so we recommend you use one of the well known techniques. You can do something like [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0#initialize-blazor-when-the-document-is-ready)

Or you can mark the script with the [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) attribute for a similar result.

**Comment by TheAtomicOption** [comment]
Thanks for the recommendations. As mentioned, that is the work around I finally arrived at, but it's unclear why Blazor should behave this way by default.

It's also unfortunate that this isn't at all clear from the error message. If there's no intent to change Blazor's start behavior, then with this post as context would you consider reopening https://github.com/dotnet/aspnetcore/issues/39580 to improve the error message with the suggestion I put into the Anything Else section above?

**Comment by TheAtomicOption** [comment]
In response to the bot, the @javiercn for my response might not have gone through since I added it to the comment with an edit, so apologies for the double ping.

The error message should do a better job of communicating when this happens.

**Comment by javiercn** [comment]
@TheAtomicOption do you have a concrete suggestion?

**Comment by TheAtomicOption** [comment]
@javiercn yes, as stated above it should be something like "The Blazor component comment nodes could not be parsed correctly. They may not have been fully loaded by the DOM prior to Blazor startup, or may have been altered or removed."

This phrasing communicates that the comments themselves may be fine, which is wrongly dismissed by the current error's assertion that they are "malformed."  It also implies the work around I found of loading Blazor at a later time through autostart="false" with Blazor.start() from an event, or the additional ones you mentioned of tag order or defer.

**Comment by TheAtomicOption** [comment]
>yes... something like "The Blazor component comment nodes could not be parsed correctly. They may not have been fully loaded by the DOM prior to Blazor startup, or may have been altered or removed."

@javiercn just wanting to make sure this doesn't fall through the cracks. Does the improved error message above work for you? 

Happy to help however I can to get this through the next steps so others don't get stuck where my team did.
