### ISSUE TITLE
Blazor Webassembly dll files missing on publish

### ISSUE THREAD

**Issue by Darkatek7** [dotnet/aspnetcore#42958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I use the Visual Studio publish profile to publish the release output of my Blazor Webassembly app 
only "wwwroot" and web.config are published to the folder. It is missing all the dll's etc.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/50767771/181434896-3fef1c7e-241b-48b8-9960-ecfbbefc6415.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/50767771/181434958-3f59972a-753a-411c-8e88-86138d91fb2d.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/50767771/181435215-442d6bc9-c1bb-47e6-adb2-b10f2e4365ee.png">

### Expected Behavior

On clicking publish, I expect all needed dll's etc to be in the publish directory.

### Steps To Reproduce

I created a new Blazor Webassembly project using the template. Chose no User Authentication and Progressive Application. 
Target is .Net 6
Visual Studio Version: 17.2.6

### .NET Version

6.0.400-preview.22330.6

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22330.6
 Commit:    da7c9ccceb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22330.6\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by javiercn** [comment]
@Darkatek7 thanks for contacting us.

There should be no dlls in the publish folder if you are creating a standalone blazor webassembly apps. Blazor puts the dlls inside the _framework subfolder.
