### ISSUE TITLE
Blazor WASM docker not starting

### ISSUE THREAD

**Issue by Darkatek7** [dotnet/aspnetcore#42964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a Blazor WASM project, added docker support using Visual Studio which created the following dockerfile:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["PersonFinder.NET6.Web/PersonFinder.NET6.Web.csproj", "PersonFinder.NET6.Web/"]
COPY ["PersonFinder.NET6.DAL/PersonFinder.NET6.DAL.csproj", "PersonFinder.NET6.DAL/"]
RUN dotnet restore "PersonFinder.NET6.Web/PersonFinder.NET6.Web.csproj"
COPY . .
WORKDIR "/src/PersonFinder.NET6.Web"
RUN dotnet build "PersonFinder.NET6.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PersonFinder.NET6.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PersonFinder.NET6.Web.dll"]
```

Now I created a docker-compose file to build the project easier etc:
```
version: '3.4'

services:
  client:
    image: tapcounter
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8071:80
    restart: unless-stopped
```

Now when I run the `docker-compose build` command everything runs fine.
But when I run `docker-compose up` I get the following error:

> client_1  | The command could not be loaded, possibly because:
client_1  |   * You intended to execute a .NET application:
client_1  |       The application 'TapCounter.Web.dll' does not exist.
client_1  |   * You intended to execute a .NET SDK command:
client_1  |       No .NET SDKs were found.
client_1  | 
client_1  | Download a .NET SDK:
client_1  | https://aka.ms/dotnet-download
client_1  | 
client_1  | Learn about SDK resolution:
client_1  | https://aka.ms/dotnet/sdk-not-found

### Expected Behavior

Host my Blazor WASM Website to be accessible using IP + Port

### Steps To Reproduce

- Create Solution from Blazor WASM Template
- Add Docker Support
- Build the Dockerfile
- Run the Docker Container

### Exceptions (if any)

> client_1  | The command could not be loaded, possibly because:
client_1  |   * You intended to execute a .NET application:
client_1  |       The application 'TapCounter.Web.dll' does not exist.
client_1  |   * You intended to execute a .NET SDK command:
client_1  |       No .NET SDKs were found.
client_1  | 
client_1  | Download a .NET SDK:
client_1  | https://aka.ms/dotnet-download
client_1  | 
client_1  | Learn about SDK resolution:
client_1  | https://aka.ms/dotnet/sdk-not-found`

### .NET Version

6.0.302

### Anything else?

VS: 17.2.6

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-arm64
 Base Path:   /home/pi/.dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.202 [/home/pi/.dotnet/sdk]
  6.0.302 [/home/pi/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/home/pi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/home/pi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/home/pi/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/home/pi/.dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by javiercn** [comment]
@Darkatek7 thanks for contacting us.

Is this a blazor webassembly hosted or standalone project.

**Comment by Darkatek7** [comment]
Options I've chosen on creating it from the template was no asp.core hosted (so it's standalone I think) though I checked progressive web application

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear where from the `TapCounter...` assembly is coming into the picture as your projects seem to be named differently.
At this point it looks like you're doing something wrong in your setup.

Another thing to keep in mind is that there is no server involved in your scenario to serve the static files that your application has published, hence it won't "just start".

**Comment by SteveSandersonMS** [comment]
> Options I've chosen on creating it from the template was no asp.core hosted (so it's standalone I think)

If it's standalone, then your publish output is just static files. There's no webserver in your Docker container as far as I can tell, so there's nothing to run them.

To serve those files from the container, consider copying the publish output into a web server container (e.g., use the `nginx:alpine` base image). There's a good tutorial at https://chrissainty.com/containerising-blazor-applications-with-docker-containerising-a-blazor-webassembly-app/
