### ISSUE TITLE
Is there a way to drag diagram to design via blazor?

### ISSUE THREAD

**Issue by wangrd** [dotnet/aspnetcore#42976]
**Is your feature request related to a problem? Please describe.**
I need a vidual editor in my work for the workflow. and i have known blazor has it's stable release, but i haven't found any way or implement for me to make it.

**Applicable Scenarios**
I want use it to design a workflow by draging diagrams. it may like this:
![image](https://user-images.githubusercontent.com/30856466/180680514-093d0cb3-8f06-4e15-9265-d20f4cc57097.png)

**Describe alternatives you've considered**
As I know, there are some implements via js.

**Comment by javiercn** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/42889
