### ISSUE TITLE
Confirmation email fails after confirmation  phone

### ISSUE THREAD

**Issue by tonisimakov99** [dotnet/aspnetcore#42985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I generate tokens for confirmation during registration:
` var emailToken = await userManager.GenerateEmailConfirmationTokenAsync(user);`
`var phoneToken = await userManager.GenerateChangePhoneNumberTokenAsync(user, user.PhoneNumber);`
than I confirm:
`userManager.ChangePhoneNumberAsync(user, user.PhoneNumber, phoneToken);`
`userManager.ConfirmEmailAsync(user, emailToken);`

Confirmation email is fail.

### Expected Behavior

Confirmation email is success.

### Steps To Reproduce

https://github.com/tonisimakov99/ConfirmationEmailFailExample 

### .NET Version

6.0.202

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  5.0.407 [/usr/share/dotnet/sdk]
  6.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by HaoK** [comment]
Confirming/changing either the phone number or the email will invalidate the user's security stamp which will invalidate all other outstanding tokens, so this behavior is expected, you can only use one token at a time, you can't generate 2 and then use both.
