### ISSUE TITLE
HTTP/3: Ephemeral port and connection already in use

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#42982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A set of ASP.NET Core HTTP/3 tests failed - https://github.com/dotnet/aspnetcore/issues/42967. They are both configured to start on 127.0.0.1:0. Because the port is 0 (ephemeral) the listener should start on an unused port assigned by Windows.

Instead, this error is thrown: `System.Net.Quic.QuicException : The local address is already in use.`

The problem is Kestrel listening on HTTP/1.1 (TCP), HTTP/2 (TCP), and HTTP/3 (UDP).

The ephemeral port is used to bind a TCP socket first, which returns the assigned port. Then that port is reused with QUIC because we want the listener connections to share the same port number.

The problem is there's a chance that the free port for TCP is in use with UDP, causing this error.

### Expected Behavior

1. Kestrel starts up and is free from address in use errors.
2. The endpoint shares the same port numbers.

### Steps To Reproduce

Kestrel + epemeral port + HTTP/1.1, HTTP/2, HTTP/3

The error will only happen if a TCP port is assigned and the same number UDP port is in use.

### Exceptions (if any)

`System.Net.Quic.QuicException : The local address is already in use.`

**Comment by JamesNK** [comment]
The current design tries to have a listener with multiple protocols and an ephemeral port use the port number. A simple solution is to allow different port numbers.

A solution that keeps the same port, but is kind of gross, is to put connection binding in a loop and keep retrying until both start successfully on the same port number.

**Comment by JamesNK** [comment]
The problem with allowing different port numbers is that you have no idea which port is TCP and UDP. `IServerAddressesFeature` gives a simple list of addresses without extra information about what each supports.

**Comment by halter73** [comment]
This reminds me how binding to "localhost:0" requires binding to both `127.0.0.1` and `::1` which has similar problems. We just [throw](https://github.com/dotnet/aspnetcore/blob/6797f926dc6991294fb5e84505f13b672c2d97c6/src/Servers/Kestrel/Core/src/LocalhostListenOptions.cs#L15-L18) in that case, and most people then just use ​`127.0.0.1:0`​ instead.

Not supporting port-zero binding for Http1AndHttp2AndHttp3 feels bad, but it's a niche enough use case that might be our best bet. If someone want to try binding to a random port and retry on failures in a loop, they can do that manually. Anything we did under the covers in this case would not be significantly better than that.

**Comment by JamesNK** [comment]
I'm not sure if throwing will work here as the eventual plan is to have `Http1AndHttp2AndHttp3` be the default. That'll break people who are binding 0 and upgrade to .NET vNext.

**Comment by adityamandaleeka** [comment]
Triage: log at Error level and add to docs.
