### ISSUE TITLE
Cors not working in Minimal API endpoints

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#42994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a client application that send a `DELETE` request to a Minimal API endpoint hosted in an application. Since it is a Cross-Origin request, the browser tries to send a preflight request `Options` that fails even when my application is configured correctly to allow `Origin`, `Method` and `Headers`.

`Access to fetch at 'https://localhost:7083/api/category/7' from origin 'https://localhost:7280' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. `

Based on the logs, listed below, the `CORS` policy is not found and a `405 HTTP Method Not Supported` response is generated. 

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:7083/api/category/7 - -
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware[10]
      No CORS policy found for the specified request.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '405 HTTP Method Not Supported'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '405 HTTP Method Not Supported'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:7083/api/category/7 - - - 405 0 - 2.8323ms
```

I did some investigation and the `fake` `405 HTTP Method Not Supported` is generated by the `EndpointRoutingMiddleware`, not CorsMiddleware, specifically the `HttpMethodMatcherPolicy`. 

It is happening because when the `MapXXX` methods are called, a `HttpMethodMetadata` is added to the endpoint, however the `AcceptCorsPreflight` is not set (default: `false`).

`MVC/API Controllers` suffers the same problem, however the call to `AddCors` adds an `IApplicationModelProvider` that changes all `HttpMethodMetadata's` `AcceptCorsPreflight ` properties to `true`.

https://github.com/dotnet/aspnetcore/blob/6df6573d746f4a3b12cea51af9a15bfab9e0743a/src/Mvc/Mvc.Cors/src/CorsApplicationModelProvider.cs#L147

### Expected Behavior

Since my application is configured correctly, the `OPTIONS` request should completed successfully and set the required headers and the browser will send the `DELETE` request.

### Steps To Reproduce

``` c#
const string CorsPolicyName = "_myCorsPolicy";

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddCors(options 
  => options.AddPolicy(name: CorsPolicyName, builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

var app = builder.Build();

app.UseHttpsRedirection();
app.UseCors();

var apis = app.MapGroup("/api").RequireCors(CorsPolicyName);
apis.MapDelete("category/{id}", async (int id) => Results.Ok());
```

### .NET Version

7.0.100-preview.7.22370.3

**Comment by BrennanConroy** [comment]
Likely also broken in 6.0
https://github.com/dotnet/aspnetcore/blob/ec68a6b23c4e77843738e4d291af3c81b14add49/src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs#L113

**Comment by brunolins16** [comment]
In my PR we noticed that we would need a small API change:

``` diff
namespace Microsoft.AspNetCore.Routing;

public interface IHttpMethodMetadata
{
    bool AcceptCorsPreflight
    {
      get=> throw;
+     set => throw;
    }
}

public sealed class HttpMethodMetadata : IHttpMethodMetadata
{
-    public bool AcceptCorsPreflight { get; }
+    public bool AcceptCorsPreflight { get; set; }
}
```

**Comment by BrennanConroy** [comment]
The getter didn't have a default behavior before, probably shouldn't add one either.

**Comment by brunolins16** [comment]
> The getter didn't have a default behavior before, probably shouldn't add one either.

I am not fan with the `IHttpMethodMetadata` change but, if we want to update the interface with a default implementation fot the setter, we will need to add an `get` default implementation as well. We don't need to throw, maybe it could simple return `false` instead.

`error CS0501: 'IHttpMethodMetadata.AcceptCorsPreflight.get' must declare a body because it is not marked abstract, extern, or partial`

**Comment by halter73** [comment]
Like @BrennanConroy, I wish we could not provide a default implementation for the getter in this case, but given that we have to provide a default implementation, I prefer the alternative design that doesn't throw from the getter. That's less likely to blow up in scenarios where someone add the CORS middleware for the first time who might not be able to easily modify the Endpoint's IHttpMethodMetadata.

It will still throw if anything tries to set it to `true`, so it would still throw if it's a real problem that it's not implemented.

**Comment by halter73** [comment]
@jaredpar Is https://github.com/dotnet/aspnetcore/issues/42994#issuecomment-1206716695 expected? Basically we have a getter on an interface but want to add a setter with a default implementation that throws. Does this mean that we now have to provide a default implementation for the getter as well? It seems reasonable, but I just want to make sure.

**Comment by brunolins16** [comment]
> Like @BrennanConroy Brennan Conroy FTE, I wish we could not provide a default implementation for the getter in this case, but given that we have to provide a default implementation, I prefer the alternative design that doesn't throw from the getter. That's less likely to blow up in scenarios where someone add the CORS middleware for the first time who might not be able to easily modify the Endpoint's IHttpMethodMetadata.
> 
> It will still throw if anything tries to set it to `true`, so it would still throw if it's a real problem that it's not implemented.

I am fine with that, BTW the PR is already changed.

**Comment by jaredpar** [comment]
@333fred for the DIM question

**Comment by 333fred** [comment]
> Does this mean that we now have to provide a default implementation for the getter as well?

Yes, you will need to provide a DIM for the getter, you cannot have a half-abstract property.

**Comment by halter73** [comment]
API Review Notes:

- We'd prefer leaving the getter unimplemented if possible, but it's not.
- Adding a default getter that returns false seems like the best alternative.

API Approved!

``` diff
namespace Microsoft.AspNetCore.Routing;

public interface IHttpMethodMetadata
{
-    bool AcceptCorsPreflight { get; }
+    bool AcceptCorsPreflight { get => false; set => throw new NotImplementedException(); }
}

public sealed class HttpMethodMetadata : IHttpMethodMetadata
{
-    public bool AcceptCorsPreflight { get; }
+    public bool AcceptCorsPreflight { get; set; }
}
```
