### ISSUE TITLE
Data annotation ErrorMessage not working in asp.net core 6 razor pages for DateTime property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42991]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Data-annotation-ErrorMessage-not-working/10101535)._

---
ASP.NET Core 6 C# Razor Pages.

x.cs file:

```csharp
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations.Schema;

namespace x.Models
{
    [ModelMetadataType(typeof(ModelMetaDataTypeX))]
    public partial class X
    {
        public DateTime Date { get; set; }
    }

    public class ModelMetaDataTypeX
    {
        [Display(Name = "X Date")]
        [Required(ErrorMessage = "X date is required")]
        [DataType(DataType.Date, ErrorMessage = "X date is required")]
        public DateTime Date { get; set; }
    }
}
```
-------------------------------------

x.cshtml file:

```cshtml
@page
@model x.Pages.xModel

@{
    ViewData["Title"] = "Create X";
}


<h1>Create X </h1>

<hr>
<div class=row>
    <div class=col-md-8>
        <form>
            <div class=text-danger> </div>
            <div class=form-group>
                <label class=control-label></label>
                <input class=form-control>
                <span class=text-danger></span>
            </div>
            <div class=form-group>
                <input type=button value=Create class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
```
--------------------------------------

x.cshtml.cs file:

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using x.Models;
namespace x.Pages
{
    public class xModel : PageModel
    {
        public void OnGet()
        {
            
        }
        [BindProperty]
        public X X { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            return Page();
        }
    }
}
```

---------------------------

Load the razor page and press 'Create' button without entering any data in the input box.
A red text appears: "The value '' is invalid.".
With data annotations Required and DataType added and their ErrorMessage set to "X date is required", the red text should have displayed the ErrorMessage value.
I tried the RegularExpression data annotation but this only works for a string property and the problem I have is with the DateTime property.

Please fix this issue.

---
#### Feedback Bot on 7/21/2022, 06:58 PM: 

(private comment, text removed)
#### Feedback Bot on 7/25/2022, 01:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

Seems that your form in the CSHTML file is not using any tag helper, so that is likely the reason validation is not being applied in this case.

See https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0#the-validation-message-tag-helper
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0#the-validation-summary-tag-helper
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0#the-form-tag-helper
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0#the-input-tag-helper

for details
