### ISSUE TITLE
API Calls Fail on mobile safari browser

### ISSUE THREAD

**Issue by lightbulb110** [dotnet/aspnetcore#43006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a angular v13 application on the front end that makes a few http calls on load. When using any browser other then Safari mobile the http calls complete.

When someone attempts to load the page using Safari mobile, the http calls fail.

Why would a angular http call fail only on Safari?

Here's what I'm seeing in my logs.

Exception type: XMLHttpRequestProgressEvent
Error: 0 Unknown Error
HTTP Result code:   0 
Browser: iOS 15.5 Mobile Safari 15.5

Debugging details: I tested on a MacBook - connected to a tablet and received the following in the dev tools/network tab: "

"Failed to load resource: Preflight response is not successful"

angular v14 .NET Core 6 | CORS configured per the documentation

### Expected Behavior

Should be:

HTTP Result code: 200

### .NET Version

6

**Comment by josephaw1022** [comment]
Can you provide more context and show what exactly is happening? Can you show drop a link to the repo and the point out where the api call is being made and where the error is occurring?

**Comment by lightbulb110** [comment]
> Can you provide more context and show what exactly is happening? Can you show drop a link to the repo and the point out where the api call is being made and where the error is occurring? @lightbulb110 Because this could be a problem specific to the angular http client that you are using or some project specific error occurring.

Hi Joseph. This isn't a open source project so I don't have a link to send you. I agree, it's hard to say for sure if this is a issue with the angular http client or .NET core.  The issue is only occurring in production (however I develop on a pc). http calls to a third party API do complete however (from the same angular application), which makes me lean toward a issue with the backend (.NET Core in this case). Very frustrating issue. Reproducing/demonstrating it with a dummy solution is going to be a fair amount of work (infrastructure setup, etc.). Hoping someone from the .NET team/community can provide some help without having to go through all that. I am at a loss and this is a very serious issue as it seems to effect most if not all iPhones/Apple tablets.
