### ISSUE TITLE
Expose entire EndpointBuilder to filter factories

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#43000]
## Background and Motivation

In reaction to #42592, I think we should expose the entire `EndopintBuilder` via `RequestDelegateFactoryOptions`. This would allow downcasting to `RouteEndpointBuilder` and seeing the `RoutePattern` too from filters.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class RequestDelegateFactoryOptions
{
-    public IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? EndpointFilterFactories { get; init; }
-    public IList<object>? EndpointMetadata { get; init; }
+    public EndpointBuilder? EndpointBuilder { get; init; }
}
```

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class EndpointFilterFactoryContext
{
-    public EndpointFilterFactoryContext(MethodInfo methodInfo, IList<object> endpointMetadata, IServiceProvider applicationServices);
+    public EndpointFilterFactoryContext(MethodInfo methodInfo, EndpointBuilder endopintBuilder);

-    public IList<object> EndpointMetadata { get; }
-    public IServiceProvider ApplicationServices { get; }
+    public EndpointBuilder EndpointBuilder { get; }
}
```

## Usage Examples

Before:

```C#
RequestDelegateFactoryOptions factoryOptions = new()
{
    ServiceProvider = _applicationServices,
    RouteParameterNames = routeParamNames,
    ThrowOnBadRequest = _throwOnBadRequest,
    DisableInferBodyFromParameters = ShouldDisableInferredBodyParameters(entry.HttpMethods),
    EndpointMetadata = builder.Metadata,
    // builder.EndopintFilterFactories is not settable so is always a List.
    EndpointFilterFactories = (IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>)builder.EndpointFilterFactories,
};
```

After:

```C#
RequestDelegateFactoryOptions factoryOptions = new()
{
    ServiceProvider = _applicationServices,
    RouteParameterNames = routeParamNames,
    ThrowOnBadRequest = _throwOnBadRequest,
    DisableInferBodyFromParameters = ShouldDisableInferredBodyParameters(entry.HttpMethods),
    EndpointBuilder = builder,
};
```

## Alternative Designs

We could keep the filter factories directly on `RequestDelegateFactoryOptions` but rename `EndpointFilterFactories ` to `FilterFactories` to match the name in `EndpointBuilder` and make it an `IList` instead of `IReadOnlyList` which aligns with `RequestDelegateFactoryOptions.Metadata`.

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class RequestDelegateFactoryOptions
{
-    public IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? EndpointFilterFactories { get; init; }
+    public IList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? FilterFactories { get; init; }
}
```

We could also keep it as an `IReadOnlyList`.  Arguably this communicates better that the `RequestDelegateFactory` won't mutate it. RDF *does* mutate `EndpointMetadata` which is an `IList` so that might add to the confusion.

## Risks

Low. This affects API that has only been released in previews and few people depend on.

**Comment by halter73** [comment]
API Review Notes:

- Exposing the entire `EndpointBuilder` to filters seems cleaner. It's less properties on `RequestDelegateFactoryOptions` and `EndpointFilterFactoryContext` and everything that is required on `EndpointBuilder`is required for filters.
- Will callers expect `EndpointBuilder.RequestDelegate` to be set upon completion?
  - Metadata is filled in upon completion, so why not the `RequestDelegate`?
  - I think we should `RequestDelegate`. At the very least if it is null going in.

API Approved!

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class RequestDelegateFactoryOptions
{
-    public IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? EndpointFilterFactories { get; init; }
-    public IList<object>? EndpointMetadata { get; init; }
+    public EndpointBuilder? EndpointBuilder { get; init; }
}

public sealed class EndpointFilterFactoryContext
{
-    public EndpointFilterFactoryContext(MethodInfo methodInfo, IList<object> endpointMetadata, IServiceProvider applicationServices);
+    public EndpointFilterFactoryContext(MethodInfo methodInfo, EndpointBuilder endopintBuilder);

-    public IList<object> EndpointMetadata { get; }
-    public IServiceProvider ApplicationServices { get; }
+    public EndpointBuilder EndpointBuilder { get; }
}
```

**Comment by davidfowl** [comment]
Isn't this a little weird? What does it mean if the EndpointBuilder  has a RequestDelegate set?

**Comment by halter73** [comment]
I'm not sure it ever really makes sense to pass in an EndointBuilder with a RequestDelegate already set considering the implication of calling the factory is that it could at the very least be changed. Even in the `RequestDelegate` case, I plan to only pass that in via the `Delegate` to `RequestDelegateFactory.Create()` and not via `RequestDelegateFactoryOptions.EndpointBuilder.RequestDelegate`.

Since this is new API, we can just throw if it's not null. I don't see a problem with that. There's no real point to setting it that early.

**Comment by davidfowl** [comment]
I think the point is that the coupling here seems unnecessary. Why is the endpoint builder being passed into the request delegate factory?

**Comment by halter73** [comment]
Because it can include the display name, route pattern, order, and potentially different things in the future. Anything on the builder is of interest to filters. It doesn't make sense to copy most of the properties of `EndpointBuilder` and not give filters access to anything in the derived type.

Also, it's not required. You can still use RequestDelegateFactory just fine without it although you're giving filters less information than they might have otherwise had. Once filters started mutating the real `EndpointBuilder.Metadata` `IList` rather than working on a copy so that they could inspect the endpoints actual metadata so far, this was the natural conclusion.

I think `EndpointMetadataContext` and `EndpointParameterMetadataContext` should get the same treatment next.

**Comment by davidfowl** [comment]
So this is about flowing the context through, I see.

**Comment by halter73** [comment]
API Review Notes:

- Will this work with MVC?
  - Mvc's `EndpointMetadataConvention.cs` doesn't have access to one. It's not clear we could flow one through.
  - We could fake one, but that seems bad if metadata is the only thing that's supported.
- Without evidence this can work well in MVC too, we reject this API.
- We still like #42592 which doesn't have these problems.

API Rejected (unless we find an easy way to do this in MVC).

**Comment by halter73** [comment]
> Since this is new API, we can just throw if it's not null. I don't see a problem with that. There's no real point to setting it that early.

I want to make a slight adjustment to the approved API. Because we reject non-null `EndpointBuilder.RequestDelegate`s in `RequestDelegateFactory.Create()` it becomes more necessary to construct `RouteEndpontBuilder`s with null request delegates.

This was already possible because the `RouteEndpontBuilder` never null checked the argument and the `RouteEndpontBuilder.RequestDelegate` property was already nullable. Marking the constructor parameter as nullable is just recognizing the current state of affairs. You could argue this is just a nullability fixup instead of a real API change.

I also want to use required init for EndpointFilterFactoryContext now that we have access to it. This seems to generally be the better choice for context types. Here's the updated API proposal:

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class RequestDelegateFactoryOptions
{
-    public IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? EndpointFilterFactories { get; init; }
-    public IList<object>? EndpointMetadata { get; init; }
+    public EndpointBuilder? EndpointBuilder { get; init; }
}

public sealed class EndpointFilterFactoryContext
{
-    public EndpointFilterFactoryContext(MethodInfo methodInfo, IList<object> endpointMetadata, IServiceProvider applicationServices);
+     public EndopintFilterFactoryContext();

-    public MethodInfo MethodInfo { get; }
+    public required MethodInfo MethodInfo { get; init; }

+    public required EndpointBuilder EndpointBuilder { get; }
}
```

**Comment by BrennanConroy** [comment]
I think you meant to include `init` in `public required EndpointBuilder EndpointBuilder { get; }`

**Comment by BrennanConroy** [comment]
👍 `required init`, the nullable part is a bit odd, since we aren't passing null in anywhere ourselves, and it needs to be non-null by the time you call build. But to your point, it does need to be null for `RequestDelegateFactory` (after your changes).

**Comment by halter73** [comment]
API Review Notes:

1. Do we need mutable metadata at all for factories?
    1. Maybe. Maybe not.

**Comment by halter73** [comment]
API Review Notes

- Is it reasonable for RDFOptions to have an EndpointBuilder property?
  - Yes. It's pretty low level. And EndpointBuilder allows things like the `IEndpointMetadataProvider` to see the `RoutePattern` even though RDF doesn't have a reference to routing itself. 
- Should filters participate in endpoint construction? 
  - Here's the original request from @DamianEdwards asking for *mutating* metadata is at https://github.com/dotnet/aspnetcore/issues/41722?
    - Do we have other scenarios? We don't think this scenario is super compelling.
    - You *could* have your `IEnpointConventionBuilder` extension method add both a filter and "convention" together.
  - The other scenario is *read-only* endpoint metadata that we might want to cache in the filter factory.
    - The thing I'm (@halter73) scared of is exposing something that's almost like `Endpoint` or `RouteEndpoint` but it's not final.
- What if we delete the first phase completely?
  - You'd have to grab the `MethodInfo` from `HttpRequest.GetEndpoint()`
  - If we don't make filters two-phase. A two-phase RDF that infers before the call to Create() can infer all metadata before create. Otherwise, factories could add metadata in Create().

API review decision. No more `EndpointFilterFactoryContext.EndpointMetadata` or `EndpointFilterFactoryContext.EndpointBuilder` for .NET 7. You can use conventions if you want to modify endpoint metadata.

API Approved!

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class RequestDelegateFactoryOptions
{
-    public IReadOnlyList<Func<EndpointFilterFactoryContext, EndpointFilterDelegate, EndpointFilterDelegate>>? EndpointFilterFactories { get; init; }
-    public IList<object>? EndpointMetadata { get; init; }
+    public EndpointBuilder? EndpointBuilder { get; init; }
}

public sealed class EndpointFilterFactoryContext
{
-    public EndpointFilterFactoryContext(MethodInfo methodInfo, IList<object> endpointMetadata, IServiceProvider applicationServices);
+     public EndopintFilterFactoryContext();

+    public required MethodInfo MethodInfo { get; init; }
}

namespace Microsoft.AspNetCore.Routing;

public sealed class RouteEndpointBuilder : EndpointBuilder
{
-    public RouteEndpointBuilder(RequestDelegate requestDelegate, RoutePattern routePattern, int order);
+    public RouteEndpointBuilder(RequestDelegate? requestDelegate, RoutePattern routePattern, int order);
}
```

**Comment by DamianEdwards** [comment]
@halter73 seems this one should go in rc.2 as well?
