### ISSUE TITLE
Add alt-used to known headers

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#43013]
## Background and Motivation

`alt-used` is added to request headers when `alt-svc` is used from response headers. See https://datatracker.ietf.org/doc/html/rfc7838#page-13

For example:
1. Browser makes HTTP/2 request to the server.
2. The server sends `alt-svc` in response with HTTP/3 details.
3. Browser reads `alt-svc`, supports HTTP/3 and decides to use it.
4. Browser sends HTTP/3 request to the server with `alt-used` header.

Want to add it to Kestrel known headers to allow string reuse.

## Proposed API

```diff
namespace Microsoft.Net.Http.Headers;

public static class HeaderNames
{
+    public static readonly string AltUsed = "Alt-Used";
}
```

```diff
namespace Microsoft.AspNetCore.Http;

public partial interface IHeaderDictionary
{
+    StringValues AltUsed { get => this[HeaderNames.AltUsed]; set => this[HeaderNames.AltUsed] = value; }
}
```

## Usage Examples

The primary user is Kestrel string reuse.

**Comment by halter73** [comment]
API Review Notes:

- Given "The primary user is Kestrel string reuse." does this really need to be public API? Can we keep these internal yet still reuse them?
  - This reminds me of how we just mad a bunch of psudo-header names obsolete and decided not to add any more of them to `HeaderNames`.
  - If something like YARP actually needs to read this header, then I can see the point of making this public. I do want to keep `HeaderNames` limited to headers commonly used by application-level code.
