### ISSUE TITLE
Binding issue with dynamic controls 

### ISSUE THREAD

**Issue by rajshukla09** [dotnet/aspnetcore#43015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The control (textbox)is generated dynamically via JavaScript, and then one is removed from.
Say I generated 1,2,3 ,4 5, 6.
Again I removed 4 dynamically, so the controls now present is 1,2,3,5,6 then with post method, the bindings are not found for 5 and 6.

### Expected Behavior

The bindings should be available for 1,2,3,5, 6

### Steps To Reproduce

<div id="divRecipeIngredient"> </div>
 <input type="button" value="Add Ingredient" class="btn btn-sm btn-warning mg-b-10" onclick="addRecipeIngredient(1);" />

function addRecipeIngredient(rowCount) {    
    var m = $('#divRecipeIngredient').children().last().find('input[type=text]').attr('name');
    var index = rowCount; //Index from where new Ingredient textbox will be created.
    if (m != null && m.length > 0) {
        index = m.split('RAIngredients[')[1].replace('].Ingredient', ''); //This should match the Ingredient textbox names generated, Input.RAIngredients[].Ingredient
        index++;
    }
    var html = '';
    html += '<div id="inputRecipeRow">';
    html += '<br /> <input id=\"RAIngredients' + index + '_Ingredient\" class="form-control" required type="text" name=\"RAIngredients[' + index + '].Ingredient\">';
    html += '<button id="removeRecipeRow" type="button" class="btn btn-danger btn-xs">Remove</button>';
    html += '</div>';
    $('#divRecipeIngredient').append(html);
};
$(document).on('click', '#removeRecipeRow', function () {
    $(this).closest('#inputRecipeRow').remove();
});

If check see Request.Form object I am able to see 1,2,3,5, 6

### .NET Version

3.1,5.0

### Anything else?

![image](https://user-images.githubusercontent.com/56117141/182076309-871f197d-7d08-4bc3-a760-03dbac0a0c27.png)
![image](https://user-images.githubusercontent.com/56117141/182076365-083b9dfd-d63b-4b9c-9324-f248d30ed6d9.png)

**Comment by ShreyasJejurkar** [comment]
Instead of removing those textboxes, just hide them and have some null or string empty condition at the server side code side so that you won't insert those record in DB or somewhere!

**Comment by javiercn** [comment]
@rajshukla09 thanks for contacting us.

I believe you can't have "holes" in the indexes. See https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections-1 for details. If you are trying to model "add and remove" I would suggest doing so by modeling the different operations (add, remove) and keeping track of the indexes separately as part of the payload instead of inside the collection.
