### ISSUE TITLE
Derived class properties are not serialized

### ISSUE THREAD

**Issue by Clemkd** [dotnet/aspnetcore#43018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm migrating from Newtonsoft to System.Text.Json and I can't get all the properties of the derived class via the API. 

Simple example to show the problem:

```c#
public class Person
{
    public string Name { get; set; }
}

public class Employee : Person
{
    public string Job { get; set; }
}
```

```c#
[ApiController]
[Route("[controller]")]
public class EntitiesController : Controller
{
    [HttpGet]
    public IActionResult Get()
    {
        return Ok(GetEntitiesAsync());
    }

    // Changing "Person" by "Employee" is not a solution
    // In my real world case, I would like to return a different type of derived class depending on the parameters
    public async IAsyncEnumerable<Person> GetEntitiesAsync()
    {
        for (var i = 0; i < 2; i++)
        {
            yield return new Employee()
            {
                Name = $"Test_{i}",
                Job = "Developer"
            };
        }
    }
}
```

Result:
```
GET /entities

[{"name":"Test_0"},{"name":"Test_1"}]
```

Only the "Name" property is serialized by System.Text.Json...

### Expected Behavior

Expected:
```
GET /entities

[{"name":"Test_0","job": "Developer"},{"name":"Test_1","job": "Developer"}]
```

### .NET Version

6

**Comment by javiercn** [comment]
@Clemkd thanks for contacting us.

You can check https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism#serialize-properties-of-derived-classes to see how this works with system.text.json
