### ISSUE TITLE
Hot Reload Stopped Working Blazor WASM

### ISSUE THREAD

**Issue by SeanLeitzinger** [dotnet/aspnetcore#43035]
I have a project that I built back in late 2021. Hot reload worked well back then and into early 2022. I went to do some more work on this project and now hot reload is completely broken. I'm using Visual Studio 2022 current version and this project has only ever run on .NET 6. Changing inline CSS causes the whole project to rebuild and launch again. In other cases, it just sits there and says there are no code changes. Other times I get the following:

![image](https://user-images.githubusercontent.com/24277209/182241863-875bcf6a-290b-4689-a0ec-dfb676bdc562.png)

Hot reload works when I create a new WASM project. Only thing I can think of is that there was an update somewhere along the way that broke the hot reload. Is this a known issue or something I need to update in my project?

**Comment by TanayParikh** [comment]
> or something I need to update in my project?

It's possible. Please make sure you're using the latest .NET SDK / latest version of Visual Studio, and your package references (in the .csproj) are also up to date.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeanLeitzinger.
Do you know if the issue you're facing is specific to .NET 6 projects, or are you facing similar issues with .NET 7 projects (.NET 7 Preview 6 is the latest release)?

@tmat, @SteveSandersonMS FYI

**Comment by SeanLeitzinger** [comment]
@TanayParikh All nuget packages are up to date. Visual studio version is 17.2.6.

@mkArtakMSFT Switching over to .NET 7 using VS 2022 preview 17.3 Preview 5 actually seems worse. Editing inline CSS displays the following:
![image](https://user-images.githubusercontent.com/24277209/182251076-0b9f5023-7596-45b7-aa9d-844cfb98b66a.png)

**Comment by mkArtakMSFT** [comment]
So to summarize, this issue you're facing is specific to that one project and for a newly created projects things seems to be working just fine.

**Comment by SeanLeitzinger** [comment]
It appears so. Nothing changed between when it worked and now other than Nuget package upgrades and VS 2022 upgrades.

**Comment by javiercn** [comment]
@SeanLeitzinger have you enabled compression in your project?

Are the hot reload JS files being correctly loaded on the browser?

**Comment by javiercn** [comment]
@SeanLeitzinger do you see any errors on the browser console?

**Comment by SeanLeitzinger** [comment]
@javiercn There are no errors in the console.

**Comment by javiercn** [comment]
@SeanLeitzinger any logs in the output window?
![image](https://user-images.githubusercontent.com/6995051/182407385-ece03b56-0585-406a-82c8-6cc317ddad0b.png)
![image](https://user-images.githubusercontent.com/6995051/182407548-9bfffb26-7c44-4772-9522-08cb361febd1.png)

**Comment by SeanLeitzinger** [comment]
@javiercn It appears dotnet watch run from a command prompt works and hotreload works again as expected. So it looks like it's broken only when running from Visual studio.

I set the logging verbosity to Diagnostic in Build and Run in options. I didn't see anywhere else to set this at if your screenshot was setting it elsewhere:
![image](https://user-images.githubusercontent.com/24277209/182436531-4acdfb87-0ec2-4d1d-8d72-a074e8754623.png)

Output:
EdgesideSystems.Api (Web server): Hot reload session started
EdgesideSystems.Proxy (Web server): Hot reload session started
Starting session.
EdgesideSystems.Web (Web assembly): Hot reload session started
Checking for updates (without debugger)...
EdgesideSystems.Api (Web server): Sending updates to running application
Applying changes (without debugger)...
EdgesideSystems.Api (Web server): Updates applied successfully
EdgesideSystems.Proxy (Web server): Sending updates to running application
EdgesideSystems.Proxy (Web server): Updates applied successfully
EdgesideSystems.Web (Web assembly): Sending updates to running application
EdgesideSystems.Web (Web assembly): Applying updates failed: The connection to the web browser was lost.
An unexpected error has occurred, any pending updates have been discarded.
EdgesideSystems.Api (Web server): Stopping application
Shutting down all hot reload agents.
Finalizing session.
EdgesideSystems.Proxy (Web server): Stopping application
EdgesideSystems.Proxy (Web server): Hot reload session complete
EdgesideSystems.Api (Web server): Hot reload session complete
EdgesideSystems.Web (Web assembly): Stopping application
EdgesideSystems.Web (Web assembly): Hot reload session complete

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/182450286-16399bd1-d7d9-4d09-9837-834a6d5a1617.png)

**Comment by SeanLeitzinger** [comment]
Yeah, I don't have the log option.

![image](https://user-images.githubusercontent.com/24277209/182450659-be19a460-c8fd-416f-b4c2-b347a1a7ebc0.png)

**Comment by javiercn** [comment]
@SeanLeitzinger ah, that might only be available on Visual Studio 2022 Preview. Could you try installing that?

Also, at this point, since this is a VS issue, I would report it through the Visual Studio Report a problem dialog, as that will capture more details. Just make sure you mentioned that it works with dotnet-watch and link to this issue

**Comment by SeanLeitzinger** [comment]
I'll download preview again. I actually uninstalled it because preview was being used on the command line and I wanted to make sure dotnet watch was working.

**Comment by SeanLeitzinger** [comment]
Here's the output from logging diagnostic turned on in preview 2022. I've gone ahead and created an issue with the report problem functionality. Thanks for the help.

15:44 54.82 Starting session.
15:44 54.99 EdgesideSystems.Web (Web assembly): Hot reload session started
15:44 55.01 EdgesideSystems.Proxy (Web server): Hot reload session started
15:44 55.01 EdgesideSystems.Api (Web server): Hot reload session started
15:45 55.90 Checking for updates (without debugger)...
15:46 02.24 Applying updates (without debugger)...
15:46 02.24 EdgesideSystems.Api (Web server): Sending updates to running application
15:46 02.51 EdgesideSystems.Api (Web server): Updates applied successfully
15:46 02.51 EdgesideSystems.Api: Refreshing web browser
15:46 02.51 EdgesideSystems.Proxy (Web server): Sending updates to running application
15:46 02.51 EdgesideSystems.Api: Refreshing the web browser failed. You may need to manually refresh the web browser to see the changes: No web socket connection
15:46 02.66 EdgesideSystems.Proxy (Web server): Updates applied successfully
15:46 02.66 EdgesideSystems.Proxy: Refreshing web browser
15:46 02.66 EdgesideSystems.Web (Web assembly): Sending updates to running application
15:46 02.68 EdgesideSystems.Web (Web assembly): [Error] Applying updates failed: The connection to the web browser was lost.
15:46 02.69 An unexpected error has occurred, any pending updates have been discarded.
15:46 04.26 Shutting down all hot reload agents.
15:46 04.26 EdgesideSystems.Api (Web server): Stopping application
15:46 04.27 EdgesideSystems.Api (Web server): Hot reload session complete
15:46 04.29 EdgesideSystems.Proxy (Web server): Stopping application
15:46 04.29 EdgesideSystems.Proxy (Web server): Hot reload session complete
15:46 04.29 EdgesideSystems.Web (Web assembly): Stopping application
15:46 04.30 EdgesideSystems.Web (Web assembly): Hot reload session complete
15:46 04.30 Ending session.

**Comment by javiercn** [comment]
@SeanLeitzinger thanks for the additional details.

Can you link the Visual Studio ticket here?

**Comment by SeanLeitzinger** [comment]
@javiercn https://developercommunity.visualstudio.com/t/Blazor-WASM-Hot-Reload-Broken-in-VS-2022/10109841

**Comment by javiercn** [comment]
@SeanLeitzinger Thanks!

I am going to close the issue for now as we are going to be using the VS issue to track the investigation.
