### ISSUE TITLE
OAuthCreatingTicketContext still uses Newtonsoft JObject rather than JsonElement as replaced back in 2019?

### ISSUE THREAD

**Issue by WillMarcouiller** [dotnet/aspnetcore#43034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently writing an OAuthHandler.  The OAuthCreatingTicketContext still requires a JObject as per below screenshot.

![image](https://user-images.githubusercontent.com/6224870/182229525-03658283-2ecd-4f43-9d9f-bee7ca3c1872.png)

Yet, when I look at the source code, it is clear that **`JObject`** has been replaced by **`JsonElement`**.

[https://github.com/dotnet/aspnetcore/blob/0c1a5de1abb14d9b5766374b64c320abb4ac5010/src/Security/Authentication/OAuth/src/Events/OAuthCreatingTicketContext.cs#L15](url)

Also when I look at the file's history, I can see that the change took place on the 5th of Feb. 2019 as per change #7105.

[https://github.com/dotnet/aspnetcore/commit/67037a003904efb67d1a9534c0c56936a37d5547#diff-50d7e69d5fb6bc63ce8a4cdd1c89c7de05253ccb7e90b9571946169132a83861](url)

And an announcement has been made for it as well.

[https://github.com/dotnet/aspnetcore/issues/7289](url)

### Expected Behavior

I then expected to be able to pass on a **`JsonElement`** as per examples for Google Authentication and the others.

[https://github.com/dotnet/aspnetcore/blob/0c1a5de1abb14d9b5766374b64c320abb4ac5010/src/Security/Authentication/Google/src/GoogleHandler.cs](url)

`    /// <inheritdoc />
    protected override async Task<AuthenticationTicket> CreateTicketAsync(
            ClaimsIdentity identity,
            AuthenticationProperties properties,
            OAuthTokenResponse tokens)  {
            // Get the Google user
            var request = new HttpRequestMessage(HttpMethod.Get, Options.UserInformationEndpoint);
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", tokens.AccessToken);
            var response = await Backchannel.SendAsync(request, Context.RequestAborted);
            if (!response.IsSuccessStatusCode)
            {
                throw new HttpRequestException($"An error occurred when retrieving Google user information ({response.StatusCode}). Please check if the authentication information is correct.");
            }

            using (var payload = JsonDocument.Parse(await response.Content.ReadAsStringAsync(Context.RequestAborted)))
            {
                // Here, the payload.RootElement is a JsonElement.
                var context = new OAuthCreatingTicketContext(new ClaimsPrincipal(identity), properties, Context, Scheme, Options, Backchannel, tokens, payload.RootElement);
                context.RunClaimActions();
                await Events.CreatingTicket(context);
                return new AuthenticationTicket(context.Principal!, context.Properties, Scheme.Name);
           }
        }`

### Steps To Reproduce

1.  Create new .Net 6 Project
2.  Install package Microsoft.AspNetCore.Authentication.OAuth

![image](https://user-images.githubusercontent.com/6224870/182235312-c1693988-3587-4c03-a883-b4fa86c5f702.png)

4.  Replicate code from Google Authentication

[https://github.com/dotnet/aspnetcore/blob/0c1a5de1abb14d9b5766374b64c320abb4ac5010/src/Security/Authentication/Google/src/GoogleHandler.cs](url)

5.  Then you should see a red underline for **payload.RootElement**

![image](https://user-images.githubusercontent.com/6224870/182234269-813f90b7-b645-4df8-b4f0-42dc54fdb21f.png)

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/6224870/182234381-5d415b3f-1e56-4901-81be-83e16f9f6f22.png)

![image](https://user-images.githubusercontent.com/6224870/182234474-4d06a2cc-f1eb-4ba5-9fc3-4e5d8e4875b3.png)

### .NET Version

7.0.100-preview.6.22352.1

### Anything else?

.Net 6 Project
VS 2022 v17.2.6
Nuget Package Manager v6.2.1

I noticed that the package Microsoft.AspNetCore.Authentication.OAuth was built from an archived source at 

[https://github.com/aspnet/Security/tree/93926543f8469614c2feb23de8a8c0561b8b2463](url)

Rather than current source like the other authentication providers.

**Comment by WillMarcouiller** [comment]
Looks like the package hasn't been updated since 2018.

![image](https://user-images.githubusercontent.com/6224870/182240681-d442ef49-2f3e-4a17-bbce-e42cf9e1fb09.png)

What am I supposed to do when the official release ain't updated with latest changes?

**Comment by BrennanConroy** [comment]
The package is part of the ASP.NET Core shared framework, so it is automatically included in ASP.NET Core apps.
https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#remove-obsolete-package-references

Remove the package reference to Microsoft.AspNetCore.Authentication.OAuth that you added and you should see System.Text.Json being used instead.

**Comment by WillMarcouiller** [comment]
> The package is part of the ASP.NET Core shared framework, so it is automatically included in ASP.NET Core apps. https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#remove-obsolete-package-references
> 
> Remove the package reference to Microsoft.AspNetCore.Authentication.OAuth that you added and you should see System.Text.Json being used instead.

When I remove the added package, all of my code is being highlighted in red like below screenshot.
![image](https://user-images.githubusercontent.com/6224870/182247584-dfebbce2-7504-4d75-b1ec-86bab4271b15.png)
How should I resolve this?

**Comment by BrennanConroy** [comment]
You're probably writing a class library, so you need to add a framework reference.
https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

**Comment by WillMarcouiller** [comment]
> You're probably writing a class library, so you need to add a framework reference. https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

This seems to have solved my issue and yes, now the **`OAuthCreatingTicketContext`** now takes a **`JsonElement`**.

Now, this is the first time I ever encounter such an issue whilst writing a class library.  Shouldn't such elements (FrameworkReference) be already included into the class library itself to ease it all?  Because if you didn't have the kindness to answer my questions, I would still be stuck as I asked a question on StackOverflow and no answer came in.  No one seems to know about it, except people who work in the framework itself.
