### ISSUE TITLE
OpenIdConnect Nonce and Correlation cookies cause "Nginx Request Header Or Cookie Too Large" over http

### ISSUE THREAD

**Issue by asiehmokarian** [dotnet/aspnetcore#43041]
When communications happen over http, OpenIdConnect Nonce and Correlation cookies are not removed after successful authentication and it will cause "Nginx Request Header Or Cookie Too Large" error.

The Microsoft.AspNetCore.Authentication.OpenIdConnect Version=3.1 is used for the web application authentication. After first login, the user will be challenged every time they want to switch between some services. By every re-authentication, two new Nonce and Correlation cookies will be generated. If the communications happen over http, these cookies will not be removed after successful authentication until they got expired (15 mins). If the user keeps switching between services in this period, the app will fail for them with "Nginx Request Header Or Cookie Too Large" error.

**Comment by blowdart** [comment]
> The Microsoft.AspNetCore.Authentication.OpenIdConnect Version=3.1 is used for the web application authentication. After first login, the user will be challenged every time they want to switch between some services.

This is not normal. The correlation cookies drop away. What you do mean by switching between services here? What causes the reauthentication?

**Comment by asiehmokarian** [comment]
@blowdart thanks for the reply. It turned out that there was some misconfiguration on `OpenIdConnnect` options. The problem was that the try to remove cookies was failing because of missing "secure" option. After setting the "SecurePolicy" to "Always" for Nonce and Correlation cookies. they were removed successfully.
