### ISSUE TITLE
MapHealthChecks().AllowAnonymous() not working

### ISSUE THREAD

**Issue by abuzaforfagun** [dotnet/aspnetcore#43042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Health check does not work when you use `OpenIdConnect` for authentication and authorization. The health check endpoint returns the expected result. But OpenIdConnect logs the request as an unauthorized one.
Here is log: `OpenIdConnect was not authenticated. Failure message: Not authenticated`.

### Expected Behavior

`OpenIdConnect` should not treat the request as unauthorized one.

### Steps To Reproduce

- Create new .net 6 web application and use the code added below.
- Run the application
- From your browser go to `{ApplicationUrl}:{Port}/live`
- Check console output

**Program.cs**
```
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.UI;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();


// Add services to the container.
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));


builder.Services.AddControllersWithViews(options =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .RequireRole("user")
        .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});

builder.Services.AddRazorPages()
    .AddMicrosoftIdentityUI();
builder.Services.AddHealthChecks();

var app = builder.Build();

app.UseHttpLogging();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();
app.MapHealthChecks("/live", new HealthCheckOptions { Predicate = r => r.Tags.Contains("live") }).AllowAnonymous();
app.MapHealthChecks("/ready", new HealthCheckOptions { Predicate = r => r.Tags.Contains("ready") }).AllowAnonymous();
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
app.MapRazorPages();

app.Run();
```

**appsettings.json**
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler": "Information"
    }
  },
  "AllowedHosts": "*",
  "AzureAd": {
  }
}
```

**Application.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="6.0.7" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="6.0.7" />
		<PackageReference Include="Microsoft.Identity.Web.UI" Version="1.25.1" />
	</ItemGroup>

</Project>
```

### .NET Version

6.0.201

**Comment by davidfowl** [comment]
I’m not understanding what exactly isn’t working based on the above configuration.

**Comment by abuzaforfagun** [comment]
@davidfowl when you run the application, and hit `/live` or `ready`, in the console you will get `OpenIdConnect was not authenticated. Failure message: Not authenticated`.

**Comment by adityamandaleeka** [comment]
Triage: It sounds like this is expected today. The endpoint is set to `AllowAnonymous` but the configured auth scheme logs the fact that OpenIdConnect isn't authenticated (which is okay).

We could consider checking for IAllowAnonymous in here:

https://github.com/dotnet/aspnetcore/blob/8ce81e9dac0db17415dd21eea4f02ce025f3924c/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L215-L218

and not logging if so.

**Comment by davidfowl** [comment]
Oh the endpoint works fine its just that there's a log.

**Comment by abuzaforfagun** [comment]
@davidfowl Yeap, endpoiint works, as expected, but we should not get this mis information to the logs. It's confusing and as the live or ready endpoints are called simultaneously, the logs are overweighted.
