### ISSUE TITLE
Count how many blazor - signalR connections are currently opened

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/aspnetcore#43044]
This is follow-up from[ year 2020](https://github.com/dotnet/aspnetcore/issues/18231), because the issue is locked.

_Using Blazor Server-Side, is possible to know how many users (signalR connections) are currently connected?_

**Comment by TanayParikh** [comment]
Hey @LukasKubicek, thanks for contacting us. 

Did you happen to try out [Pranav's suggestion in the original post](https://github.com/dotnet/aspnetcore/issues/18231#issuecomment-572715258)?

More information on SignalR performance can be found here: https://docs.microsoft.com/aspnet/signalr/overview/performance/signalr-performance

@BrennanConroy do you have any suggestions for achieving this?

**Comment by LukasKubicek** [comment]
> Hey @LukasKubicek, thanks for contacting us.
> 
> Did you happen to try out [Pranav's suggestion in the original post](https://github.com/dotnet/aspnetcore/issues/18231#issuecomment-572715258)?
> 
> More information on SignalR performance can be found here: https://docs.microsoft.com/aspnet/signalr/overview/performance/signalr-performance
> 
> @BrennanConroy do you have any suggestions for achieving this?

Hi Tanay, the suggested post by Pranav mentions that the CircuitHandler has a bug that counts some events twice. Has this been resolved?

It would be great if you could provide complete example how to correctly count how many  connections are opened withing Blazor Server webapp.
