### ISSUE TITLE
Blazor Hosted WASM app cannot be published as runtime-dependent if not self-contained from dotnet CLI

### ISSUE THREAD

**Issue by yugabe** [dotnet/aspnetcore#43068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hosted Blazor WASM applications cannot be published as a runtime-dependent, explicitly not self-contained (meaning: framework-dependent) applications via the dotnet CLI.

### Expected Behavior

I'd expect the application to be able to be published this way.

### Steps To Reproduce

In a new command window:
`dotnet new blazorwasm -n BlazorNoScd -f net7.0 -ho`
`dotnet publish .\BlazorNoScd\Server -r linux-x64 --no-self-contained`

(I originally included the `-p:PublishSingleFile=true` flag by mistake when copying the command; the error persists regardless.)

The second command fails.

### Exceptions (if any)

When running locally, on Windows:
```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.6.22324.4\Sdk\WasmApp.targets(190,5): error : $(MicrosoftNetCoreAppRuntimePackDir)='', and cannot find %(ResolvedRuntimePack.PackageDirectory)=. One of these need to be set to a valid path [C:\...\BlazorNoScd\Client\BlazorNoScd.Client.csproj]
```

I tried running the same on Azure DevOps Pipelines on ubuntu-latest, and it produces the error:
```
/opt/hostedtoolcache/dotnet/sdk/7.0.100-preview.6.22352.1/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(220,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/home/vsts/work/1/s/src/Client/MyClientApp.Client.csproj]
```

### .NET Version

7.0.100-preview.6.22352.1

### Anything else?

Weirdly, the same app can be published without errors in Visual Studio with the following publish profile:

```xml
<Project>
  <PropertyGroup>
    <DeleteExistingFiles>false</DeleteExistingFiles>
    <ExcludeApp_Data>false</ExcludeApp_Data>
    <LaunchSiteAfterPublish>true</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>bin\Release\net7.0\publish\</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <_TargetId>Folder</_TargetId>
    <SiteUrlToLaunchAfterPublish />
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <ProjectGuid>13dbba23-9c3f-4926-8ba9-4f3fa45884f6</ProjectGuid>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
</Project>
```

This also prevents smaller single-file deployments.

**Comment by javiercn** [comment]
It is likely `-p:PublishSingleFile=true` as we do not support that for Blazor applications.

**Comment by yugabe** [comment]
Oh yeah, I forgot to pull that out, it doesn't work either way (with or without single file deployment).

**Comment by javiercn** [comment]
does `dotnet publish .\BlazorNoScd\Server -r linux-x64` work?

**Comment by yugabe** [comment]
Yes, but it produces a self-contained build, and the following warning:
`C:\Program Files\dotnet\sdk\7.0.100-preview.6.22352.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1117,5):
 warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used.
[C:\...\BlazorNoScd\Client\BlazorNoScd.Client.csproj]`

**Comment by javiercn** [comment]
@yugabe does it work if you put `<SelfContained>false</SelfContained>` in the project file?

**Comment by yugabe** [comment]
Very weird. It seems that putting `<SelfContained>false</SelfContained>` in the project file seems to work and produce a non-SCD publish. The warning still persists in the CLI though.

**Comment by javiercn** [comment]
We do have tests fort this scenario here, I think the issue is with the `-r linux-x64` as I think it applies it to all the projects and overrides the project RID https://cs.github.com/dotnet/sdk/blob/f638199c2848bf6d7b6442afd1f57628ac24900e/src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs#L1077:~:text=Execute(%22-,/p%3ARuntimeIdentifier%3Dlinux%2Dx64,-%22%2C%20%22

**Comment by yugabe** [comment]
I was trying to minimize the size of the server app for quicker publishes, and as I know the target it's going to be run on, I wanted to strip out the native dependencies that weren't needed for that platform. Putting `<SelfContained>false</SelfContained>` solves my issue, but there seem to be multiple, possibly unrelated issues here:

- The warning should be probably suppressed when the project built contains the property, even if it wasn't passed to the CLI.
- The error message seems to point to some path properties being unavailable or empty. The message on ubuntu seems to point in the right direction, but it recommends I double check that I'm building an SCD app. I don't want an SCD app, I want a smaller deployment.
- Disabling SCD from the project file seems to work, but the warning message persists.
- Disabling SCD from the CLI breaks the build altogether.
- Publishing from Visual Studio works with the same configuration, from the CLI it does not.

**Comment by javiercn** [comment]
@yugabe I gave this a quick try and this is what I did.

```console
dotnet publish /p:RuntimeIdentifier=linux-x64
```
Server.csproj file
```xml
  <PropertyGroup>
    ...
    <SelfContained>false</SelfContained>
  </PropertyGroup>
```

I see no error nor warning in this case, and it produces a platform dependent build

The issue is that some of the flags passed to `dotnet publish` don't work well with Blazor apps because they apply to all projects unconditionally, so those settings must be specified using the MSBuild property (Blazor overrides the rid for example) or in the project file itself so that they only apply to them.

I believe that this is a limitation on the CLI/MSBuild pipeline that we can't easily overcome, hence the recommendation to do it as described above.

@guardrex could we add a section to describe how to do this in the deployment section for hosted apps?

**Comment by yugabe** [comment]
Thanks very much for the help, @javiercn. It seems like a very hard issue to solve, as it seems it hits many parts of the infrastructure. For example, providing the runtime as `-r linux-x64` shows the warning, but `/p:RuntimeIdentifier=linux-x64` does not. I think it would be fair to expect the same results.

**Comment by javiercn** [comment]
@yugabe Unfortunately, things like `-r` override the runtime on every project, so it is impossible for us to override them, and we end up trying to build with the wrong RID. It is a known limitation that we don't have plans to change since its costly and there are alternatives to it.

**Comment by yugabe** [comment]
Thanks, I'll be able to work with this. I didn't know the CLI flags and `/p` parameters weren't interchangeable.

The original error message might be worth checking out nonetheless, it might point to a deeper issue somewhere else, and if anyone else stumbles onto it, might not find an easy solution: `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.6.22324.4\Sdk\WasmApp.targets(190,5): error : $(MicrosoftNetCoreAppRuntimePackDir)='', and cannot find %(ResolvedRuntimePack.PackageDirectory)=. One of these need to be set to a valid path [C:\...\BlazorNoScd\Client\BlazorNoScd.Client.csproj]`
