### ISSUE TITLE
Packing a Razor Class Library with `--no-build` produces bad output

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#43062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In build scripts it's common to split the work into discrete steps (clean, restore, build, pack) rather than one (pack).

But when I pack a Razor Class Library in a single or multiple steps I get different `.nupkg` files. If I reference the one produced by multiple steps - i.e. the preferred approach - then the project fails to compile.

### Expected Behavior

I expect the two scenarios to produce the same `npkg` file.

#### Prepare a project
````sh
dotnet new razorclasslib --support-pages-and-views --output MyProject
cd MyProject
mkdir wwwroot
touch wwwroot/Foo.css                 # <--- this causes all the trouble
````
#### Scenario 1: one step (works)
Run:
````sh
rm -f bin/Release/MyProject.1.0.0.npkg
dotnet pack --configuration Release
unzip -l bin/Release/MyProject.1.0.0.npkg | grep css
````
Result:
````
0  2022-08-03 01:18   staticwebassets/MyProject.css
````
Notice there is only one `css` file in there. This is correct.

#### Scenario 2: multiple steps (preferred, but fails)
Run:
````sh
rm -f bin/Release/MyProject.1.0.0.npkg
dotnet restore
dotnet build --configuration Release --no-restore
dotnet pack --configuration Release --no-restore --no-build
unzip -l bin/Release/MyProject.1.0.0.npkg | grep css
````
Result:
````
0  2022-08-03 01:18   staticwebassets/MyProject.css
0  2022-08-03 01:18   content/wwwroot/MyProject.css
0  2022-08-03 01:18   contentFiles/any/net6.0/wwwroot/MyProject.css
````
There are three `css` files in there. If this library is referenced by some other project, **it will fail to compile**.

This is a simplistic repro. For a complex build, the single-step workaround is simply no good.

### .NET Version

6.0.302

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

WE have fixed this issue in 7.0.

**Comment by lonix1** [comment]
Thanks Javier!

I think I'll wait for November though... The workaround is non-ideal but works for now.

**Comment by javiercn** [comment]
@lonix1 I would encourage you to at least try with a preview so that we can make sure your concrete case is fixed (It should be, but builds are "complicated").
