### ISSUE TITLE
[Blazor] Handle _GlobalPropertiesToRemoveFromProjectReferences in the SDK

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#43067]
Update https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets#L682 to include `;$(_GlobalPropertiesToRemoveFromProjectReferences)`

Update https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets#L725 to include `;$(_GlobalPropertiesToRemoveFromProjectReferences)`

Update https://github.com/dotnet/sdk/blame/main/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets#L539 to include `;$(_GlobalPropertiesToRemoveFromProjectReferences)`

Ideally, we would capture this in MergeConfigurationProperties instead after the first invocation to get the projects configuration with a couple of new properties GlobalBuildPropertiesToRemove, GlobalPublishPropertiesToRemove, for which we would pass the `$(_GlobalPropertiesToRemoveFromProjectReferences)`

**Comment by mkArtakMSFT** [comment]
This issue is the cause for dotnet/maui#7479

**Comment by TanayParikh** [comment]
> Ideally, we would capture this in MergeConfigurationProperties instead after the first invocation to get the projects configuration with a couple of new properties GlobalBuildPropertiesToRemove, GlobalPublishPropertiesToRemove, for which we would pass the `$(_GlobalPropertiesToRemoveFromProjectReferences)`

Just to clarify, this would be the "ideal" approach, but there's a reason we aren't/we can't do it? Just wondering if I should go ahead with the changes in the three spots you called out or investigate this other path more?

**Comment by javiercn** [comment]
The only reason I can think of is that $(_GlobalPropertiesToRemoveFromProjectReferences) is a property, so if we capture it in the manifest and reuse that value afterwards, we will lose any update to it that happens at a later time.

Since this is a one-off that everybody has agreed upon (search for it on cs.github.com) let's just do it that way. The value of the manifest is that we capture it once and we do not have to worry about it afterwards.

**Comment by TanayParikh** [comment]
Thanks for the clarification! I've closed out https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1539200, and using this issue to track the fix.
