### ISSUE TITLE
Blazor Server SPA is returning 'Soft 404' error while accessing an URL/page directly from SEO crawler

### ISSUE THREAD

**Issue by ananthmk** [dotnet/aspnetcore#43075]
**Problem** 
Blazor Server SPA is returning 'Soft 404' error while accessing an internal URL/page directly from SEO crawler. If we access the same from Browser, it returns expected page content and not getting any error.   Please help resolve this 'soft 404' issue by returning the page content to SEO crawler as browser get. 

We have developed this SPA using Blazor Server technology(ASP.NET Core 6.0) and deployed in AWS EC2. It is a public site which serves the dynamic page content based on the route.  For SEO, given the sitemap.xml file which contains all the navigation URLs available in our site.

**More details:-**
Blazor-render-mode: Server
SignalR Version: Microsoft.AspNetCore.SignalR.Client 6.0.0

**Response for the URL requested:**

> An error has occurred. This application may no longer respond until reloaded. [Reload ]()🗙
> Attempting to reconnect to the server... [Reload ]()
> 
> Reconnection failed. Try [Reload ]() the page if you're unable to reconnect.
> 
> Couldn't connect to the server [Reload ]()

### _Host.cshtml

```
@page "/"
@namespace App.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

@*
    If we are use the renderMode as ServerPreRender, the CustomAuthenticationStateProvider throws
    the exception on accessing local storage in pre rendering state.
    NOTE: Due to pre-rendering in Blazor Server you can't perform any JS interop until the OnAfterRender lifecycle method.
    *@
<component type="typeof(App)" render-mode="Server" />
```

### _Layout.cshtml
```
<head>
    <base href="~/" />
	
    <component type="typeof(HeadOutlet)" render-mode="Server" />
</head>	
<body>
    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <environment include="Staging,Production,Development">
        <div id="components-reconnect-modal" class="my-reconnect-modal components-reconnect-hide">
            <div class="show">
                <p>
                    Attempting to reconnect to the server...
                    <a href="" target="_top">Reload</a>
                </p>
            </div>
            <div class="failed">
                <p>
                    Reconnection failed. Try 
                    <a href="" target="_top"> Reload </a>
                    the page if you're unable to reconnect.
                </p>
            </div>
            <div class="rejected">
                <p>
                    Couldn't connect to the server
                    <a href="" target="_top">Reload</a>
                </p>
            </div>
        </div>
    </environment>

    <script src="_framework/blazor.server.js"></script>
</body>
</html>
```
### My understanding ###
While directly accessing the page from crawlers, the Blazor components and SignalR connection will not be established by default. How can we achieve that and get the page content instead of getting reconnect error?

**Comment by javiercn** [comment]
@ananthmk thanks for contacting us.

If you want the content to be there for crawlers you need to prerender the page (ServerPrerendered), otherwise the content is not generated up until a connection is established interactively from the browser.

**Comment by SteveSandersonMS** [comment]
@javiercn I think the question here is more specific to integrating prerendering with auth.

**Comment by ananthmk** [comment]
> @javiercn I think the question here is more specific to integrating prerendering with auth.

Yes, we moved to "Server" render mode to access local storage. But, it is not returning any data for SEO crawler. So, we are trying to give a SEO friendly web application with local storage auth.  We appreciate a better solution.   Thanks.

**Comment by javiercn** [comment]
@ananthmk You can't access local storage on the server, so you need to avoid accessing it when you are rendering static HTML or avoid doing prerendering.

**Comment by ananthmk** [comment]
We are providing dynamic content only and we need the authentication part after the user access our landing page.  So, first of all, we need to sent the landing page content for crawler request instead of 'Reload' error.  How to achieve this?
Also, to avoid local-storage authentication issue, is there any help/sample to store it in Server-side Relational DB storage?

**Comment by javiercn** [comment]
> We are providing dynamic content only and we need the authentication part after the user access our landing page. So, first of all, we need to sent the landing page content for crawler request instead of 'Reload' error. How to achieve this?
Also, to avoid local-storage authentication issue, is there any help/sample to store it in Server-side Relational DB storage?

What type of 'local-storage' authentication you are using? Is that something you built yourself?

**Comment by ananthmk** [comment]
> > We are providing dynamic content only and we need the authentication part after the user access our landing page. So, first of all, we need to sent the landing page content for crawler request instead of 'Reload' error. How to achieve this?
> > Also, to avoid local-storage authentication issue, is there any help/sample to store it in Server-side Relational DB storage?
> 
> What type of 'local-storage' authentication you are using? Is that something you built yourself?

Local-storage we are using is 'Microsoft.AspNetCore.Components.ProtectedBrowserStorage' inside our 'CustomAuthenticationStateProvider'.  This is extended from 
 Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider'

**Comment by ananthmk** [comment]
Yes, we do have our own SQL server system for authentication and authorization purpose. Our CustomAuthenticationStateProvider is handling this. We decided to use this before deciding prerendering or server rendering mode.

**Comment by javiercn** [comment]
@ananthmk I believe you need to either implement a prerendering friendly authentication mechanism or give up on prerendering.
