### ISSUE TITLE
Extracting and setting values in Middleware vs Filter

### ISSUE THREAD

**Issue by venknar** [dotnet/aspnetcore#43074]
Hi

This is more of a question to understand whether to use Middleware vs Filter.

In my scenario, we have a need for all the request we need to check if there is a specific header (say location hint) and then validate if its in the right format and if so extract the values and set it in the request header which would be used by the controller to do the actual execution.

The middleware would extract the header from the request by looking for the request header key = locationHint. Then it validates the format of the location hint. It would be of the format place@state and we would extract the place, state and do some validation on these 2 values and if good we would set it on the request headers. We map the place@state to say latitude, longitude.

In the controller we look for 2 request headers (say latitude and longitude) and then do the actual logic in the controller.

In this scenario, I want to understand whether this should be modelled as a middleware or a filter. Also is this approach of using the middleware to look for header, do some validation and map it to latitude, longitude the right approach or should this be done inside the controller as part of its execution ?

Since we would need this for all our actions and controllers, we are taking this approach. 

Please provide inputs. 

Thanks

**Comment by davidfowl** [comment]
Why not model it as a model binder? It’s transforming the header values into some object that will be consumed later right?

**Comment by venknar** [comment]
Yes. Right. From the header values, we validate the header value is in right format, then we can another service that would take the header value and convert to latitude and longitude. And then set those values into another header.

So what you are suggesting is that make this a model binder and the model would have a lat and longitude property. The model binder would convert the header values into the model after validation. Is that the right understanding?

**Comment by davidfowl** [comment]
Yep

**Comment by venknar** [comment]
One other question. This is a ASP.NET Core Web API project and it supports both gRPC and OData end point. With the middleware it is always run for both the end points.

**Comment by davidfowl** [comment]
What’s the question?

**Comment by venknar** [comment]
I did not read your entire explanation on the usage of middleware vs filter vs model binding. My mistake. Sorry. Its clear on how to approach this. Closing this issue.
