### ISSUE TITLE
Specifying bind source for blazor bindings

### ISSUE THREAD

**Issue by vrassouli** [dotnet/aspnetcore#43073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In blazor, if you want to bind a value from Component1, to Component2, you need to define a variable in parent companent and pass value from one component to another.
Something like this:
`<Component1 @bind-Value="_myVar" />
<Component2 @bind-Value="_myVar" />

@code {
    int _myVar = 1;
}`

This way, value changes from one component, will pass to another component.

### Describe the solution you'd like

It would be better if you could specify a source for bindings from one component to another.
Something like this (Similar to binding in XAML)

`<Component1 @name="mySourceComponent" />
<Component2 @bind-Value="Value" @bind-source="mySourceComponent" />

@code {
    int _myVar = 1;
}`

### Additional context

In some cases, parent component has nothing to do with the values, and we need only inter-component relation.
Like when you have a master-detail list of items, the detail component just needs to be notified of SelectedItem from master list.

Having such ability, would increase productivity and would lead to more readable and understandable code.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
