### ISSUE TITLE
Allow HttpMethodAttribute (HttpGet, HttpPost, etc) to apply to class

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#43071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

To follow the strict  single-responsibility principle, I only use one method per controller.
```
[Route("{template")]
public class CreateProductController : Controller
{
    [HttpPost]
    public async Task<IActionResult> HandleAsync(CreateProductCommand command)
    {
    }
}
```
I would like to apply the [HttpPost] directly to the class.
```
[HttpPost("{template")]
public class CreateProductController : Controller
{
    public async Task<IActionResult> HandleAsync(CreateProductCommand command)
    {
    }
}
```

### Describe the solution you'd like

```
[AttributeUsage(**AttributeTargets.Class** | AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public abstract class HttpMethodAttribute : Attribute, IActionHttpMethodProvider, IRouteTemplateProvider;
```

**Comment by javiercn** [comment]
@alienwareone thanks for contacting us.

We do not have plans to change this in the near future. You can create your own attribute that does this by implementing the `IActionHttpMethodProvider, IRouteTemplateProvider` interfaces.
