### ISSUE TITLE
Blazor Wasm is not Caching DLL files when loaded from IFrame

### ISSUE THREAD

**Issue by avichhetri8** [dotnet/aspnetcore#43086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I loaded the blazor product using IFrame and the DLL files were not cached. All the Dll files were downloaded after refreshing the page.

Loaded using IFrame
![image](https://user-images.githubusercontent.com/48516639/182827706-12053c70-e6b3-4bb6-81fd-d4054f97aa2b.png)

Loaded directed using Url: It was able to cache the DLL files
![image](https://user-images.githubusercontent.com/48516639/182827802-a299177a-3d29-4414-bde3-c76eee57c0a2.png)

### Expected Behavior

DLL files must be cache when loaded using IFrame

### .NET Version

6

**Comment by javiercn** [comment]
@avichhetri8 thanks for contacting us.

It might be that your iframe is not considered a securecontext and the cache APIs are not available there. I would set a breakpoint in your iframe and check if the CacheStorage API is available there.

Blazor does not make any distinction on whether the app is running inside an iframe or not.

**Comment by javiercn** [comment]
@avichhetri8 I was suggesting that you open the developer tools and check if the actual API is available on the iframe. That's likely the reason blazor is not caching the dlls.
