### ISSUE TITLE
Blazor WASM terrible runtime performance from mobile browser

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#43090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When deploying my app to Azure app service and accessing via a PC web browser, performance is fine, everything feels responsive and button clicks are immediate. When accessing from a mobile browser it's a completely different story. Clicking any button takes 4-5 seconds to do anything (which would be kind of ok if these buttons were making web requests, but they're not, they are just opening modals), on click events sometimes don't even fire at all so you have to press buttons multiple times for anything to happen. I've AOT'd the app to try and improve things but from what I can see, runtime perf is no better but users have to wait 30 secs to initially load.

Client has the following build configuration:
```
<RunAOTCompilation>true</RunAOTCompilation>
<InvariantGlobalization>true</InvariantGlobalization>
<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
<BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
```

The story is the same with the simplest of apps, create an app using the MudBlazor template (https://github.com/MudBlazor/Templates), deploy to the web and access via a mobile browser. See the delay on button presses.

This terrible performance is from a OnePlus 6T so not even a low end device. Something needs to be addressed here as this is unacceptable for a production app.

### Expected Behavior

I expect button clicks to be responsive (certainly not taking 4-5 seconds)

### .NET Version

6.0.302

**Comment by ScottKane** [comment]
@SteveSandersonMS Accessing that site from mobile is better but still has a delay of 2-3 secs on button presses, it doesn't seem to eat on click events though which would be an improvement.

**Comment by ScottKane** [comment]
Even if the issues are being caused by MudBlazor, I'm struggling to figure out what they could be doing that's making the perf this bad on mobile but not on desktop browsers. Their components are structured fairly similarly to my own with no glaringly obvious issues.

**Comment by ScottKane** [comment]
Actually testing the experience from a PC browser emulating a low/mid end device shows pretty much the same behaviour

**Comment by SteveSandersonMS** [comment]
> Accessing that site from mobile is better but still has a delay of 2-3 secs on button presses
> Actually testing the experience from a PC browser emulating a low/mid end device shows pretty much the same behaviour

I've no doubt you can find devices or set a CPU throttling level such that it becomes slow. And it's good that you're testing to see how things will work on the specific devices you care about.

Nonetheless I am still surprised about the 6T taking multiple seconds to navigate. I tried just now with a fairly low-spec mobile device (iPad Air 2, 8 years old) and it was more or less fine. The first navigation click did take maybe 800ms to complete (which is when it will be caching the interpreter-transformed instructions), but subsequent navigation clicks went down to somewhere between instant and 200-300ms depending on which page. It felt as fast as any other website on this old device. Of course, on a more recent device - a 3-year old iPhone - it was instant from the start.

According to https://browser.geekbench.com/, your OnePlus 6T should be a bit faster than an iPad Air 2, though admittedly only about 1/3 the speed of a recent iPhone. So I guess there must be something more to it than just the CPU benchmarks.

**Comment by ScottKane** [comment]
The default MudBlazor sample app is nowhere near as slow as my production app, the only thing I can think is that I have `CascadingAuthenticationState` and `CascadingValue Value="_hubConnection"`. I imagine these cascading values are what's slowing things down dramatically but I will have to do some testing to figure out if that is the case. I don't know what alternatives there are if this is the problem though.

**Comment by MackinnonBuck** [comment]
@ScottKane Please let us know if you end up tracking down the issue and it turns out to be a framework issue.

**Comment by timbze** [comment]
> visiting https://aspnet.github.io/quickgridsamples/

Very fast on my Pixel 3. Every action is < 500 ms
