### ISSUE TITLE
IFormFile.OpenReadStream() “stream.ReadTimeout”引发了类型“System.InvalidOperationException”的异常

### ISSUE THREAD

**Issue by xiaorenwuaiziyou** [dotnet/aspnetcore#43092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IFormFile.OpenReadStream() “stream.ReadTimeout”引发了类型“System.InvalidOperationException”的异常

### Expected Behavior

![20220804222701](https://user-images.githubusercontent.com/3072528/182872431-f0ef29da-956d-4386-80da-4cd524811900.png)

### .NET Version

6.0.302

**Comment by davidfowl** [comment]
ReadTimeout does not work for most streams with async IO, you should use the CancellationToken on ReadAsync to timeout specific read operations.

**Comment by xiaorenwuaiziyou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
