### ISSUE TITLE
Page not found after changing chtml file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Page-not-found-after-changing-chtml-file/10102350)._

---
[regression] [worked-in:16.2.x]
When i change the view cshtml page of [Authorize] controller ( I am logged in), then hot reload, it gives page not found on the browser, I have to restart the debugger to see my changes.

I just updated today to the latest version, it used to work before.

---
#### Feedback Bot on 7/24/2022, 08:14 PM: 

(private comment, text removed)
#### Feedback Bot on 7/25/2022, 03:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

@tmat this seems like another hot reload regression. They claim it worked in 16.2, so I suspect something in the SDK or VS must have changed. (no code has changed in the runtime in this area).

Gave this a quick try with new web app -> Individual auth, this is what I am getting if I try to do it to the C# class
![image](https://user-images.githubusercontent.com/6995051/183428534-75d1244d-f4ce-4e73-aa3c-412a7a664049.png)

If I try something on the cshtml page it doesn't complain

**Comment by javiercn** [comment]
It is not clear what is happening here. Could you provide detailed steps on how to trigger the issue? Ideally a minimal repro project to demonstrate it.
