### ISSUE TITLE
Blazor WASM: Recursive layout causes freeze and makes it unusable

### ISSUE THREAD

**Issue by AxxiD** [dotnet/aspnetcore#43118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `@layout` directive and referencing the same page it will freeze the entire page in the browser.

Why is this a problem? 
When opening a page with this construct as seen below the page/browser tab freezes and becomes unresponsive.
It also uses quiet some CPU and consumes more and more system memory.
The only option to stop it is closing the tab or browser.

Example:
`MyTestPage.razor`
```
@layout MyTestPage
@page "/test"

<p>Test page</p>
```

Tested with:
- Firefox 103.0.1
- Chrome 103.0.5060
- Chrome 104.0.5112

### Expected Behavior

I'd like to have either a compilation error or warning at least that this recursion is happening and that it will cause issues down the road.

### Steps To Reproduce

[https://github.com/AxxiD/blazor-recursion-bug](https://github.com/AxxiD/blazor-recursion-bug)

### Exceptions (if any)

None but probably out of memory after some time if the browser does not kill the tab itself.

### .NET Version

6.0.301

### Anything else?

Firefox puts up a banner that tells the user that the page is slowing down the browser with the option to stop its execution.

**Comment by javiercn** [comment]
@AxxiD thanks for contacting us.

That's by design. Compilers don't prevent you against infinite recursion and we do not do so either.
