### ISSUE TITLE
Release of project

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/aspnetcore#43111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

blazor.webassembly.js:1 Assertion failed: Cannot call unknown function mono_wasm_set_is_debugger_attached, make sure it is exported
window.Module.s.printErr @ blazor.webassembly.js:1
abort @ dotnet.6.0.7.3mqbcvvc1b.js:1
assert @ dotnet.6.0.7.3mqbcvvc1b.js:1
getCFunc @ dotnet.6.0.7.3mqbcvvc1b.js:1
ccall @ dotnet.6.0.7.3mqbcvvc1b.js:1
(anonym) @ dotnet.6.0.7.3mqbcvvc1b.js:1
mono_wasm_get_loaded_files @ dotnet.6.0.7.3mqbcvvc1b.js:1
(anonym) @ VM20:1
mono_wasm_runtime_ready @ dotnet.6.0.7.3mqbcvvc1b.js:1
(anonym) @ blazor.webassembly.js:1
callRuntimeCallbacks @ dotnet.6.0.7.3mqbcvvc1b.js:1
postRun @ dotnet.6.0.7.3mqbcvvc1b.js:1
doRun @ dotnet.6.0.7.3mqbcvvc1b.js:1
run @ dotnet.6.0.7.3mqbcvvc1b.js:1
runCaller @ dotnet.6.0.7.3mqbcvvc1b.js:1
removeRunDependency @ dotnet.6.0.7.3mqbcvvc1b.js:1
h @ blazor.webassembly.js:1
await in h (asynkron)
(anonym) @ blazor.webassembly.js:1
(anonym) @ blazor.webassembly.js:1
callRuntimeCallbacks @ dotnet.6.0.7.3mqbcvvc1b.js:1
preRun @ dotnet.6.0.7.3mqbcvvc1b.js:1
run @ dotnet.6.0.7.3mqbcvvc1b.js:1
runCaller @ dotnet.6.0.7.3mqbcvvc1b.js:1
removeRunDependency @ dotnet.6.0.7.3mqbcvvc1b.js:1
receiveInstance @ dotnet.6.0.7.3mqbcvvc1b.js:1
(anonym) @ blazor.webassembly.js:1
await in (anonym) (asynkron)
window.Module.s.instantiateWasm @ blazor.webassembly.js:1
createWasm @ dotnet.6.0.7.3mqbcvvc1b.js:1
(anonym) @ dotnet.6.0.7.3mqbcvvc1b.js:1
3blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: NoElements
System.InvalidOperationException: NoElements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Char](IEnumerable`1 )
   at D_T.Manager.set_Value(String value)
   at E_A_H.Component.set_Value(String value)
   at E_A_H.Component.<BuildRenderTree>b__0_0(String __value)
   at Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.<>c__DisplayClass32_0`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<CreateBinderCore>b__0(ChangeEventArgs )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
window.Module.s.printErr @ blazor.webassembly.js:1
Fe._internal.dotNetCriticalError @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.7.3mqbcvvc1b.js:1
$func158 @ 008cd406:0x1637d
$func106 @ 008cd406:0x7085
$func105 @ 008cd406:0x5f9e
$func7257 @ 008cd406:0x18256e
$func1515 @ 008cd406:0x70df5
$func1513 @ 008cd406:0x70d67
$func972 @ 008cd406:0x527b9
$func158 @ 008cd406:0x16336
$func106 @ 008cd406:0x7085
$func105 @ 008cd406:0x5f9e
$func7257 @ 008cd406:0x18256e
$func1515 @ 008cd406:0x70df5
$func1519 @ 008cd406:0x71526
$mono_wasm_invoke_method @ 008cd406:0x1b42a2
Module._mono_wasm_invoke_method @ dotnet.6.0.7.3mqbcvvc1b.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
(anonym) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
A @ blazor.webassembly.js:1
N @ blazor.webassembly.js:1
dispatchGlobalEventToAllElements @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1

What can it be?

Only getting this error in chrome

Website : https://object.social

### Steps To Reproduce

work well in debug but not in release

### Exceptions (if any)

work well in debug but not in release

**Comment by javiercn** [comment]
@PirasathLuxchumykanthan thanks for contacting us.

Seems that you are trying to debug in the release configuration. You need to turn `<DebuggerSupport>true</DebuggerSupport>` inside a propertygroup in your csproj file.
