### ISSUE TITLE
Blazor app is not starting when host environment name is changed from Development

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#43110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The problem is that `index.html` file resides in Blazor project.
There's an API which processes `.staticwebassets.runtime.json` file, so static assets are served correctly when running not published app with `dotnet run`.

But default app builder uses it [only for dev environment](https://github.com/dotnet/aspnetcore/blob/4e7d976438b0fc17f435804e801d5d68d193ec33/src/DefaultBuilder/src/WebHost.cs#L219).

If I add this call, Blazor works again (with debug mode, though, but you already have [tickets](https://github.com/dotnet/aspnetcore/issues/23536) for this).

### Expected Behavior

I'd propose default templates (and docs as well) contain a commented section with the explanation that this call must be used for any other environment:

```
// Uncomment it, if you are developing using Environment name other than `Development`
// See docs: .... some link.
// StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);
```

### .NET Version

6.0.7

**Comment by javiercn** [comment]
@voroninp thanks for contacting us.

We are aware of this behavior. However, we do it this way to prevent the feature from being accidentally turned on in production as it serves files from separate locations on disk other than the project.

**Comment by voroninp** [comment]
@javiercn That's fine, but it's nice to have it documented maybe?
