### ISSUE TITLE
Support Int128 and UInt128 in API binding, ApiExplorer, etc.

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#43119]
.NET 7 introduces the new `Int128` and `UInt128` structs to represent 128-bit numbers. Attempting to use these new structs in parameters of or responses from minimal APIs or MVC APIs results in broken behavior though, as the type inference logic and serialization doesn't recognize these types.

For example, the following minimal API ends up being described as accepting a string parameter and returning a complex type `Int128` with no members (see auto-generated swagger document further below):

```c#
app.MapGet("/numbers/{number}", (Int128 number) => new NumbersResult(number, (long)number))
    .WithName("Numbers");

record NumbersResult (Int128 Number, long AsLong);
```

```json
{
    "openapi": "3.0.1",
    "info": {
        "title": "WebApplication6",
        "version": "1.0"
    },
    "paths": {
        "/numbers/{number}": {
            "get": {
                "tags": [
                    "WebApplication6"
                ],
                "operationId": "Numbers",
                "parameters": [
                    {
                        "name": "number",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/NumbersResult"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Int128": {
                "type": "object",
                "additionalProperties": false
            },
            "NumbersResult": {
                "type": "object",
                "properties": {
                    "number": {
                        "$ref": "#/components/schemas/Int128"
                    },
                    "asLong": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "additionalProperties": false
            }
        }
    }
}
```

<img width="343" alt="image" src="https://user-images.githubusercontent.com/249088/183161655-3d608d6b-ce25-4923-8586-e57686b6e682.png">

**Comment by captainsafia** [comment]
Triage: @DamianEdwards will validate if this is still an issue given that it seems like the appropriate `TryParse` overloads do exist in the BCL.

**Comment by DamianEdwards** [comment]
So parameters are parsed correctly, but the schema of `Int128` is inferred incorrectly (both as parameters and response type). A query parameter of type `Int128` is described as a string, and an `Int128` member on a schema definition is described as a complex type (`"object"`) with no additional properties. This likely means the change needs to be made in SwashBuckle rather than ASP.NET Core.

**Comment by captainsafia** [comment]
Filed https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2611 to follow-up on the schema-related changes in Swashbuckle.
