### ISSUE TITLE
System.Runtime error

### ISSUE THREAD

**Issue by IonRobu** [dotnet/aspnetcore#43115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I configured from scratch a .NET 6.0.7 Blazor WASM application on a machine with Windows Server 2016. When I try to start from console with 'dotnet Webapp.Server.dll' I get error:
'Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### .NET Version

6.0.7

**Comment by TanayParikh** [comment]
Hey @IonRobu, thanks for contacting us. Can you please clarify what command you're using to start the application:

> When I try to start from console with 'dotnet Webapp.Server.dll' 

Are you trying to run a published application? Does it work if you just do `dotnet run` instead? If you have Visual Studio installed, is the application running from there?

**Comment by IonRobu** [comment]
Hi @TanayParikh ,

I started app with `dotnet` command (`Webapp.Server.dll` is my entry dll). It works from Visual Studio and when I start the published app on my dev PC (where I have installed NET SDK 6.0.302 on Windows 10). The problem appears on a deploy machine where I have NET 6.0.7 Hosting Bundle on Windows 2016 (no Visual Studio installed). 
I cleaned the solution, deleted bin and obj files manually, published again, but no luck. That dll (`System.Runtime`) does not appear in output folder, but seems to be referred by many others.

Thanks,
Ion

**Comment by javiercn** [comment]
@IonRobu thanks for contacting us.

It very likely seems that you have a version mismatch in your dependencies. Check on your dependencies node what (if any) is targetting .NET 7.0 (check the TFM on your project too). It might mean that you have 7.0 installed on your dev box and are compiling against that or that you have something installed on the publish machine that is causing this.

**Comment by IonRobu** [comment]
Hi all
I solved by creating a new Blazor WASM project, add library projects as dependencies and migrating the content from old project. Not sure what caused the error (very probably a wrong dependency), but it works now.

Thanks!
Ion
