### ISSUE TITLE
Meta Tags added via HeadContent not detected when sharing to social media

### ISSUE THREAD

**Issue by rr-code-base** [dotnet/aspnetcore#43128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am adding page specific meta tags for a blazor server side app. When I inspect the pages the meta tags are present but when I try to share the page to various social sites the tags are not detected probably because they are added dynamically.
I have tried using both Server and ServerPrerendered modes for the HeadOutlet and App component but get the same issue.
Any way to get this to work as expected?

Thanks,
EE

### Expected Behavior

Page specific meta tags injected via HeadContent should be detected when page is shared with social media sites.

### Steps To Reproduce

Create a blazor server side app.
In _Layout.cshtml include the HeadContent:
`<component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />`

In Index.razor include HeadContent:
`
<HeadContent>
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="my title">
    <meta name="twitter:description" content="my desc">
    <meta name="twitter:site" content="my site">
</HeadContent>
`

Try to share the page on Twitter or point to the page using Twitter Meta Debugger and see that you get errors that tags are missing. Get same issues with Facebook og meta tags.

### .NET Version

6.0

**Comment by rr-code-base** [comment]
Sorry for the delay, had a family emergency to attend to. 
If I do a view source the tags are not there but if I inspect the page post render the tags are there.

**Comment by MackinnonBuck** [comment]
> If I do a view source the tags are not there but if I inspect the page post render the tags are there.

It might be that a non-prerendered component is populating the `<HeadOutlet>`, and since Twitter only gets the prerendered view of the page, it doesn't pick up the dynamically generated head content.

If this is an issue you're still experiencing, could you provide us with a minimal repro project, hosted as a public GitHub repository? I know it's been over a year, but I want to check again before blindly closing this issue.
