### ISSUE TITLE
Roll back the template to use an organized structure

### ISSUE THREAD

**Issue by jcbeppler** [dotnet/aspnetcore#43126]
As already exhaustively discussed on many issues, the new code is messy and without any structure. The issue below on Console application should be enough to make a point:

https://github.com/dotnet/docs/issues/27420

And please make the full-template the only option to prevent beginners from learning the wrong way.

## In scope

Preferably every C# project template, so people don't need to open the same issue everywhere.

## Risks / unknowns

There's the risk of making the majority of developers happy.

## Examples

An example from the **current code** from .NET 6 (Messy without any namespace or anything):

```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();

var app = builder.Build();

```

An example from the **old code**  from .NET 5 (Organized with namespace and a true template):

```
using System.Linq;
using System.Threading.Tasks;

namespace BlazorApp2
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
        }
.....
```

**Comment by javiercn** [comment]
@jcbeppler thanks for contacting us.

We do not have plans to do this. Blazor webassembly apps do not (and have never) supported startup and we do not plan to change the new startup in other project types. There is a switch you can use on other templates to avoid using top-level statements and you can plug in a Startup class if you choose to do so, but we do not plan to offer that option in the near future.

**Comment by jcbeppler** [comment]
@javiercn I am talking about Blazor Server side. Blazor Webassembly is in Xamarim/MAUI which is something I hope to never have to use.
