### ISSUE TITLE
[Blazor] the `pointerenter` and `pointerleave` events not getting fired

### ISSUE THREAD

**Issue by msynk** [dotnet/aspnetcore#43129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Out of all pointer events, the `pointerenter` and `pointerleave` events are not getting fired, in both Blazor Server and Blazor WASM.
I need the `leave` event since its non-bubbling nature is required for my use case. the `out` event does not help since its bubbling feature breaks my app. the only solution that I can think of, is fallback to javascript.

### Expected Behavior

like the other pointer events, the enter and leave events should get fired correctly.

### Steps To Reproduce

consider this sample:

```razor
<div @onpointerleave=@(Log("pointer leave"))
     @onpointerenter=@(Log("pointer enter"))
     @onpointermove=@(Log("pointer move"))
     @onpointerover=@(Log("pointer over"))
     @onpointerout=@(Log("pointer out"))
     @onpointercancel=@(Log("pointer cancel"))
     @onpointerdown=@(Log("pointer down"))
     @onpointerup=@(Log("pointer up"))>
    <h1>Hello, world!</h1>
</div>

@code {
    [Inject] private IJSRuntime _js { get; set; } = default!;

    private Func<Task> Log(string value) => async Task () => await _js.InvokeVoidAsync("console.log", value);
}
```

if you check the console, you can see that only the `pointer leave` and `pointer enter` phrases never get printed out.

### .NET Version

6.0.302

**Comment by TanayParikh** [comment]
Thanks for calling that out @msynk. That's definitely a bit strange, it appears it's defined appropriately already:

https://github.com/dotnet/aspnetcore/blob/55616fa5b272d6d957d20059a681a68901807486/src/Components/Web.JS/src/Rendering/Events/EventTypes.ts#L149-L150

https://github.com/dotnet/aspnetcore/blob/f7b8b7e16bcab537fb9872a26cfb1e0d3a3a253c/src/Components/Web/src/Web/EventHandlers.cs#L75-L76

https://github.com/dotnet/aspnetcore/blob/f7b8b7e16bcab537fb9872a26cfb1e0d3a3a253c/src/Components/Web/src/WebEventData/WebEventData.cs#L174-L175

**Comment by msynk** [comment]
@TanayParikh thanks for your response.
I'm guessing since these two events (and their mouse counterparts, mouseneter & mouseleave) do not bubble, they can't be caught with the Blazor's global event handlers.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/43542
