### ISSUE TITLE
Sessions - How to report / capture engagement information.

### ISSUE THREAD

**Issue by TehWardy** [dotnet/aspnetcore#43137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I realise that from the list of many issues in the past on this subject that the aspnet team don't want to do anything here but i've come for some advice only.

Related issues found ...
  - https://github.com/dotnet/aspnetcore/issues/3331
  - https://github.com/dotnet/aspnetcore/issues/3025 
  - https://github.com/aspnet/Session/issues/20
  - https://github.com/dotnet/aspnetcore/issues/9536

To be clear here ...
I'm not asking the team to implement anything I purely want advice on building accurate engagement reports with my platform.

### Describe the solution you'd like

I'm faced with a business requirement, our clients want to know about engagement with the product, i've been asked to provide A report that contains the following information ...
 - Current active users over a time period
 - Login counts (per user, per group, per tenant, ect) for a given time period
 - Length of time users engage with the application "per session" on average, min, max
 - Various business events (out of scope for this question)

Historically as pointed out by other tickets I would have put in a hook on session start and end events and log key information to the database so that I can build this report later.

I noticed that there was some conflation or mention that client sessions and server sessions are different things and the usage of auth auth cookies vs session cookies for things like session persistence.

I'd like to be able to make the product as convenient as possible by not having the user login each time they open a new tab or at the start of a new day (sticky sessions) but I'd like also like handle engagements and draw key lines in the report that actually relate to the users interaction with the platform.

I realise this is a point of frustration for the key people involved (@Tratcher, @davidfowl are probably sick of seeing this by now) but I wondered if you'd if you offer some guidance notes on how this kind of business requirement could be met without the ability to accurately track a distributed "session instance" (by that I mean "user interaction session" as opposed to a client or server session in the technical sense).

Any advice you guys could offer would be extremely helpful here.

### Additional context

I'm using SQL as my session store.
My applications are all Azure App Service hosted applications in the cloud.
I have a multi-tenancy solution.

**Comment by javiercn** [comment]
@TehWardy thanks for contacting us.

I would check if there were a third-party solution like `application insights` that might help you in this area. Providing this kind of guidance is out of the scope of what we can help with in this repo.

That said, I am going to leave it open in case other people want to chime in.

**Comment by TehWardy** [comment]
Thank @javiercn I realise this is a bit of an edge case for the team.
Do you know if application insights data can be read directly? (my understanding is that AI is basically just a way to log to the cloud platform and then have that serve up the data but I have noticed you can build AI queries in the cloud UI, I assume this means I can make rest calls that do the same thing in to host platform)

I find the whole insights thing to be a bit of a black box, it's huge and vaguely documented IMO.
I'm looking for something that will allow me to build my own dataset here ideally by handling events directly in the application.

My other issue is that "logging and analytics" appears on our cloud service bill and it's getting stupid expensive, so i'd rather just turn those features off and capture what I need.

Unless application insights can be configured to dump it's data in to my db like I did with session data?
I'm not aware that this is an option though.

**Comment by Tratcher** [comment]
Yeah, this doesn't seem to be about 'Session' at all. You're trying to generate stats about 'user' usage. You need two things to track this:
A) Use the auth events to track stats about new sign-ins.
https://github.com/dotnet/aspnetcore/blob/51ccce6d743dddf995b3661f07b0e1990b68dc7d/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L32
B) Write your own middleware that emits logs/data/events each time it sees a user. If you're using Cookie auth you could use the OnValidatePrincipal event for this, which is called per request.
https://github.com/dotnet/aspnetcore/blob/51ccce6d743dddf995b3661f07b0e1990b68dc7d/src/Security/Authentication/Cookies/src/CookieAuthenticationEvents.cs#L17

All stats would then be generated with a second level of post-processing. E.g. Current active users is counting unique users with events emitted in the last x minutes. A session is tracked by aggregating events for a user that are closer together than a given idle timeout (e.g. there were no events for this user for at least 30 minutes after this event, this must mark the end of the session).

**Comment by TehWardy** [comment]
I've put a catch all in there so that I can capture all API calls, and I've figured out how to attach sessions, users and tenants to the event data I'm capturing.
I think with a little more tinkering I should be able to deliver what's needed here.

Thanks for the input @Tratcher, good call suggesting that it's "not quite sessions" that I was after, that I think was the missing piece of the puzzle.
