### ISSUE TITLE
[Blazor][wasm] Authorization to SignalR hub with Authorize attribute

### ISSUE THREAD

**Issue by Cage-e** [dotnet/aspnetcore#43130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm working on connecting to a hub from ASPNET core hosted blazor wasm and want to keep the hub access limited to the Authotized users.
I've done what was suggested in [this documentation ](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#signalr-cross-origin-negotiation-for-authentication-blazor-webassembly) on how to handle authorization to a SignalR hub on the server. I use Authorize attribute on the hub class and implemented the suggested solution but I still get Unauthorized 401 response back. 
I have no problem with authorization on HttpClient calls to the controllers. The problem is with SignalR hub and the hub works as expected when I remove the Authorize attribute from the hub class.

Is this a bug or what's the solution?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26648

### Expected Behavior

Be able to connect to the SignalR hub by authorized users only and receive their roles and claims.

### Steps To Reproduce

https://github.com/Cage-e/HubAuth

run the server project and the 401 response will occur on Index.OnInitializedAsync. 
If you want to be sure that the hub is working, you can remove the Authorize attribute form Hub1.cs.

### Exceptions (if any)

'Response status code does not indicate success: 401 (Unauthorized).'

### .NET Version

6.0.400-preview.22301.10

**Comment by javiercn** [comment]
@Cage-e thanks for contacting us.

Blazor server runs on the server, not on the client, so when you are connecting to the hub, you are doing so from Server to Server, and the server does not have the cookie that was set on the browser (assuming you are using cookie auth).

**Comment by guardrex** [comment]
In that case, don't we need to scope the following section to say that the purpose isn't to authorize hub connections ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#signalr-cross-origin-negotiation-for-authentication-blazor-webassembly

... that devs should see ...

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz

... which is already cross-linked there for more info on authorizing users for hubs?

**Comment by javiercn** [comment]
@guardrex ah, my bad. This was labeled as Blazor Server.

**Comment by Cage-e** [comment]
I found the point I had missed in the link @guardrex shared, [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#bearer-token-authentication)
I also [committed](https://github.com/Cage-e/HubAuth/commit/5af089f0c5d63c6ea7dc880b34b6492a479b4d45) the solution to the repo. 
So I don't think this was a bug. It just needs a bit more clarification [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#signalr-cross-origin-negotiation-for-authentication-blazor-webassembly) maybe.

I appreciate your tips. You all rock! :)
