### ISSUE TITLE
Add overload with `AuthenticationProperties` to `SignInManager.ExternalLoginSignInAsync`

### ISSUE THREAD

**Issue by paviad** [dotnet/aspnetcore#43138]
## Background and Motivation

When using asp.net core identity with external login, the developer might want to persist the external identity provider authentication tokens in the application cookie. Right now there is no way to do it easily.

Most `SignInManager` sign in methods have an overload which accepts an `AuthenticationProperties` parameter, but not `ExternalLoginSignInAsync`.

So right now, there is no straightforward way to persist authentication tokens in the application cookie during external login.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Identity;

public class SignInManager<TUser> where TUser : class
{
+    public virtual async Task<SignInResult> ExternalLoginSignInAsync(string loginProvider, string providerKey,
+          bool bypassTwoFactor, AuthenticationProperties properties) ...
}
```

## Usage Examples

In the asp.net core identity quick start scaffolded item `ExternalLogin.cshtml.cs` in the method `OnGetCallbackAsync(...)` you might want to persist external login tokens by like so:

```csharp
var info = await _signInManager.GetExternalLoginInfoAsync();
if (info == null) {
    ErrorMessage = "Error loading external login information.";
    return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
}

var props = new AuthenticationProperties();
props.StoreTokens(info);

var result =
    await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, bypassTwoFactor: true, props);
```

## Risks

There is no regression or performance risks, the only risk is that by including this API we imply that this practice is considered good, while some might think it is not because it increases cookie size and also makes it easy to store the refresh token in the cookie which also might be considered bad practice.

Having said that, this solution is still proposed as valid in the documentation (with the cookie size caveat).

## Additional Info

PR #43132 shows a possible implementation of this change
Issue https://github.com/dotnet/aspnetcore/issues/12047 shows one complaint regarding the lack of this API.

**Comment by HaoK** [comment]
Thanks for the PR @paviad but as you already pointed out in the Risks, we don't recommend this approach to store the tokens in the cookie, if users want to do this, they always can store it as a user claim via the normal identity apis, so they can already accomplish this in other ways.  

We discussed this in triage today and this isn't an pattern we want to encourage with an overload

**Comment by paviad** [comment]
Should the PR be closed as well?
