### ISSUE TITLE
[Blazor] Isolated css: generated attribute placement

### ISSUE THREAD

**Issue by richx** [dotnet/aspnetcore#43157]
### Is there an existing issue for this?

- [x]  I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Current approach for isolated CSS adds generated attribute at the end of selector. And it makes it hard to have more complex selectors and have a nested components. The simplest solution is to add ::deep to the beginning every selector, but it makes CSS file messy. 

### Describe the solution you'd like

Here's a screenshot of how generated CSS file looks right now.

![VIy4n8wDYX](https://user-images.githubusercontent.com/1933239/183630809-4f5a9662-bc41-4ec4-9c66-cd5eb9798a2d.png)

- **The problem** block shows the problem I get when I use isolated CSS with custom complex selector. 
- **Expected** block shows the expected result I'd like to see when I'm not providing the ::deep selector attribute
- There's a way to attach to root component element if we really want to do it, but it doesn't sound to be that important

Overall I'd like to have a functionality similar to how [_Sass_  nesting](https://sass-lang.com/documentation/style-rules) works. The generated attribute should be placed at the beginning of every selector (e.g. "[HASH] .child-tag", "[HASH] .child-tag>.component").

It would allow us to fully describe all the layout and tiny details for given component and to be able to use BEM or similar CSS approaches and not to think about this custom attribute (that currently breaks CSS code quite often) and have it just as an additional safety net.

It could be something that we could enable in  project properties and it would alter the attribute placement globally for all Isolated CSS files. Otherwise currently we have to add ::deep selector to the beginning of every selector just to be sure that it's not placed at the end of complex selector and breaks this statement.

### Additional context
*No response*

**Comment by TanayParikh** [comment]
Hi @richx, thanks for contacting us! Based on the example you've provided on line 31 in your example, it appears you want the style to apply to your component and any components that are nested inside it. We recommend using the `::deep` selector to achieve this. 

We're leaving this issue open to get additional community feedback, and measure interest.

**Comment by richx** [comment]
@TanayParikh That's correct. And I'm already using that ::deep atribute. But it means that I have to provide this attribute for most of the component's child selectors. 

Component basically already is the scope and Blazor adds that attribute to the root element of the component. So then the question is why it's not working that way by default already? Or at least, why there is no option to do it that way?

I'd  say that "set style for element in component" is the usual way how we are using the isolated CSS. So the cases where we want to attach that attribute at the end of selector are pretty rare.

**Comment by MackinnonBuck** [comment]
Closing this out since there hasn't been any additional community interest.
