### ISSUE TITLE
Request.HttpContext.Connection.RemoteIpAddress.AddressFamily always returns InterNetworkV6 for both iPv4 and IPv6

### ISSUE THREAD

**Issue by danyhm** [dotnet/aspnetcore#43165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

in ASP.NET Core Web API project published to Linux (ubuntu 16) (.net core 3.1) the following property always returns InterNetworkV6 even for IPv4 addresses.

`Request.HttpContext.Connection.RemoteIpAddress.AddressFamily`

### Expected Behavior

It should return `InterNetworkV6 `for IPv6 and `InterNetwork` for IPv4 addresses.

### Steps To Reproduce

in any method controller call 
`Request.HttpContext.Connection.RemoteIpAddress.AddressFamily`

observe the behavior by calling the sample `weatherforecast `API.
you need to call the API once with the IPv4 of the server and once with IPv6
the client must have IPv6 connectivity

example repo
`https://github.com/danyhm/bug_AddressFamily`

### .NET Version

Irrevelant

### Anything else?

Host (useful for support):
  Version: 3.1.28
  Commit:  ce3350c1cc

**Comment by danyhm** [comment]
in addition to the above the following behavior is also observed, however I don't know if they are by design:

**when making a call to the server using IPv4** the following is returned when calling 
`Request.HttpContext.Connection.RemoteIpAddress.MapToIPv6().ToString()`
=> `::ffff:xxx.xxx.xxx.xxx`
where the x is the IPv4 address, is this by design? because for `MapToIPv4().ToString()` it only returns the correct IPv4 address.

**when making a call to the server using IPv6** the following is returned when calling 
`Request.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString()`
`0.0.0.1`
should it not be all zeros?

**Comment by Tratcher** [comment]
This is because of your configuration here:
https://github.com/danyhm/bug_AddressFamily/blob/0f2a643b67b47d0535a313841ba2970d07ea9da9/Program.cs#L31-L32

When you use ListenAnyIP it creates one IPv6 socket with Dual Mode enabled, allowing it to accept requests from IPv4 or IPv6 clients. Because it's an IPv6 socket, all addresses are displayed as IPv6. You can use [IPAddress.IsIPv4MappedToIPv6](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.isipv4mappedtoipv6?view=net-6.0) to check for this situation.

MapToIPv4 should only be used if IsIPv4MappedToIPv6 is true.

**Comment by Tratcher** [comment]
> **when making a call to the server using IPv4** the following is returned when calling `Request.HttpContext.Connection.RemoteIpAddress.MapToIPv6().ToString()` => `::ffff:xxx.xxx.xxx.xxx` where the x is the IPv4 address, is this by design? because for `MapToIPv4().ToString()` it only returns the correct IPv4 address.

"::ffff:" is the prefix used to mark when an IPv4 address is being stored as an IPv6 address.

> **when making a call to the server using IPv6** the following is returned when calling `Request.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString()` `0.0.0.1` should it not be all zeros?

The client's address was probably "::1", so this is expected.

**Comment by danyhm** [comment]
Thank you very much for the detailed explanation and sorry for wasting your time!
