### ISSUE TITLE
Net 6 Blazor server application::Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

### ISSUE THREAD

**Issue by rajaashutosh** [dotnet/aspnetcore#43175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am running the .Net 6 Blazor server application. The application is working fine in localhost/ with a single instance. However, when I deployed to a pivotal cloud foundry with multiple instances it starts breaking.

With a single instance, its page loads look fine.

With multiple instances, the page is showing blank. please refer to the screenshot.
![image](https://user-images.githubusercontent.com/5811752/183756184-98515d78-10cd-4803-ab75-c59772dbdc4c.png)

![image](https://user-images.githubusercontent.com/5811752/183756265-1139695e-cc10-45bd-bf70-16d5801e4374.png)

Error:
[2022-08-09T20:26:06.460Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

Also after a couple of refresh pages showing up, again if I start to navigate to other links its kind of not working.

### Expected Behavior

Page should up and running with multiple instances 

### Exceptions (if any)

Not using any Nginx rule for now.  the deployment env is Linux 

### .NET Version

6

### Anything else?

ASP.NET Core version 6

**Comment by BrennanConroy** [comment]
From the error message:
> If you have multiple servers check that sticky sessions are enabled.

Do you have sticky sessions enabled when using multiple instances?

**Comment by rajaashutosh** [comment]
for sticky sessions: Added this 
 services.AddMemoryCache();
builderService.AddSession(options =>
                {
                    options.IdleTimeout = TimeSpan.FromSeconds(10);
                    options.Cookie.HttpOnly = true;
                    options.Cookie.IsEssential = true;
                });

**Comment by BrennanConroy** [comment]
Sticky sessions is done at the proxy layer.
https://github.com/cloudfoundry/routing-release/blob/develop/docs/session-affinity.md

**Comment by rajaashutosh** [comment]
@BrennanConroy , are you saying, Cloud foundry infrastructure level? I am not using any Nginx yet.

**Comment by BrennanConroy** [comment]
Yes, as the link I provided shows.

**Comment by rajaashutosh** [comment]
@BrennanConroy , let me talk to infra team and let you guys update

**Comment by javiercn** [comment]
@rajaashutosh @BrennanConroy suggestions are on point. For more information on how to deploy Blazor Server applications check-out these [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-6.0)

**Comment by rajaashutosh** [comment]
Thanks, Team, It's working with multiple instances, here is the solution in pivotal cloud foundry.

**Mainfast.yml**
```
applications:
- name: unifieddeals-admin-ci
  stack: cflinuxfs3
  buildpacks:
    - dicf_dotnet_core_buildpack_2343_cflinuxfs3
  instances: 2
  memory: 4G
  disk_quota: 2G
  env:
    ASPNETCORE_ENVIRONMENT: CI
    router.sticky_session_cookie_names: "JSESSIONID"
  services:
  - secrets-unifieddeals-admin
```

**Program.cs :**
In Middleware 
```
app.Use(async (context, next) =>
                {
                    //context.Response.Headers.Add("Content-Security-Policy", "{POLICY STRING}");
                    context.Response.Cookies.Append("JSESSIONID", Guid.NewGuid().ToString(), new
                        CookieOptions()
                    {
                        Secure = true,
                        HttpOnly = true,
                        SameSite = SameSiteMode.Strict
                    });
                    await next();
                });
```
