### ISSUE TITLE
AdditionalProbingPaths are not honored by ASP.NET Core

### ISSUE THREAD

**Issue by mattersonline** [dotnet/aspnetcore#43176]
I've been researching potential ways of sharing packages between our web applications. One that I was looking into was using "additionalProbingPaths" in the *.runtimeConfiguration.json file to tell the application to pull libraries from a Nuget cache.

I had issues getting it to work with a fully built web application. I tried removing a library from the build output and adding a probing location pointing at the cache. Whenever I tried to run it though, it couldn't find the assembly. I verified all of the paths were correct between the deps.json file and my .nuget/packages folder.

So, I tried creating a small console app to test with. I imported Newtonsoft and referenced it once in the program.cs. Then after building, I removed the reference from the build output. When I ran it, it of course errored because it was missing Newtonsoft but after I added the probing location, it ran fine. I viewed the application in Process Explorer and found it was pulling the library from my nuget cache the way I wanted it to.

After that, I did the same thing again but this time I created a basic ASP.NET Core MVC application. I put a reference to Newtonsoft in the HomeController and then repeated the process from earlier. However, the ASP.NET application fails to load the assemblies from the nuget cache, despite having the same setup as the console application. It's worth

I attached my two sample projects for review. You'll have to update the probing path to point at your package cache.
[LibraryTest.zip](https://github.com/dotnet/aspnetcore/files/9294608/LibraryTest.zip)
[AspLibraryTest.zip](https://github.com/dotnet/aspnetcore/files/9294609/AspLibraryTest.zip)

Note: I did one more test with the ASP.NET Application. This time, I tried with IISExpress. We don't develop using it because we deploy our apps with IIS itself. I found that it did load the Newtonsoft from my nuget cache when using IISExpress but not IIS.

**Comment by adityamandaleeka** [comment]
@mattersonline Can you check which user your app is running as when it's running in IIS? IIS application pools run as a different user which may not have access to your nuget cache.

Ensuring your probing path uses a directory which your IIS user has permission to might be a good first step.

**Comment by mattersonline** [comment]
I did give IUSR Full Access to the nuget folder. I'll take another look though and see if it'll help if I move it to a different location on the C drive.

**Comment by mattersonline** [comment]
That did work. I had to give permissions to the app pool itself. Thanks for the help.
