### ISSUE TITLE
Cannot add `scoped` AuthorizationHandler in .NET 7 Preview 7

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/aspnetcore#43188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding a scoped `IAuthorizationHandler` works in `net6.0` but fails with and `InvalidOperationException` if upgraded to .NET 7 Preview 7.

Singleton `IAuthorizationHandler`s continue to work in .NET 7 Preview 7.

### Expected Behavior

I expect to be able to add a scoped `IAuthorizationHandler` - for example, a handler that depends on a `DbContext`.

### Steps To Reproduce

See https://github.com/frankbuckley/aspnet-7-scoped-authhandler-repro

In a new `net6.0` Web API project, add:

```c#
builder.Services.AddAuthentication();
builder.Services.AddAuthorization();
builder.Services.AddScoped<IAuthorizationHandler, MyAuthHandler>();

// ...

public class MyAuthHandler : IAuthorizationHandler
{
    public Task HandleAsync(AuthorizationHandlerContext context)
    {
        return Task.CompletedTask;
    }
}
```

Run. Starts OK.

Change to `<TargetFramework>net7.0</TargetFramework>`

Run. Fails with System.InvalidOperationException.

Change `AddScoped` to `AddSingleton`. Run. Starts OK.

### Exceptions (if any)

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot resolve 'Microsoft.AspNetCore.Authorization.IAuthorizationHandlerProvider' from root provider because it requires scoped service 'Microsoft.AspNetCore.Authorization.IAuthorizationHandler'.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.ConfigureApplication(WebHostBuilderContext context, IApplicationBuilder app)
   at Microsoft.WebTools.BrowserLink.Net.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\dev\temp\AuthScopedTest\AuthScopedTest\Program.cs:line 36
```

### .NET Version

7.0.100-preview.7.22377.5

**Comment by Kahbazi** [comment]
I investigate this issue. Seems like a bug. 

https://github.com/dotnet/aspnetcore/blob/202fafe68774e2a968d8b175c0fd3fb318778903/src/DefaultBuilder/src/WebApplicationBuilder.cs#L187

Here it is trying to create `IAuthorizationHandlerProvider` in order to add AuthZ middleware.
The fix could be to either create a scope here or to register a dummy service in [AddAuthorizationCore](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs#L21) and get that instead of `IAuthorizationHandlerProvider`.
I would like to send a PR for the fix if it's approved.

@frankbuckley Until then I guess the workaround could be to register the `IAuthorizationHandler` with transient lifetime and only inject `ISerivceProvider` to it, and get `DbContext` from `ISerivceProvider` in the methods of `IAuthorizationHandler` and not constructor. 🤔

**Comment by HaoK** [comment]
@captainsafia fyi

**Comment by davidfowl** [comment]
This is a bug, I can reproduce it.

**Comment by captainsafia** [comment]
> The fix could be to either create a scope here or to register a dummy service in [AddAuthorizationCore](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs#L21) and get that instead of IAuthorizationHandlerProvider.

This was actually what was originally implemented in the PR [here](https://github.com/dotnet/aspnetcore/pull/42585). To minimize the introduction of new APIs, I leveraged an internal marker service and IVT but there was some back and forth on this approach (see [here](https://github.com/dotnet/aspnetcore/pull/42585#discussion_r915243393)) and we eventually settled on the model above.

If you wanted to, you could pluck the commit from that PR with the marker service approach and integrate it here.

cc: @halter73 @Tratcher Thoughts?

**Comment by Tratcher** [comment]
@captainsafia what about the approach of creating a scope here?

**Comment by captainsafia** [comment]
> @captainsafia what about the approach of creating a scope here?

That works as well and is likely a good compromise given where we landed on the IVT thing (nowhere).

My main qualm with _not_ using a marker service is that we might run into issues like this in the future related to how end-users are registering the services that we end up attempting to resolve.

**Comment by davidfowl** [comment]
Let’s not create a scope here, we don’t need to be activating authz handlers at startup. Let’s do something without side effects

**Comment by Kahbazi** [comment]
Is it possible to use `IServiceProviderIsService` here? Does all `IServiceProvider` implementations have that?

**Comment by ibrahimmsarfm** [comment]
We equally facing same issue. We reverted to .NET 6.0 and waiting for quick fix.
