### ISSUE TITLE
Blazor Websocket disconnects when not authenticated (AllowAnonymous)

### ISSUE THREAD

**Issue by youss2017** [dotnet/aspnetcore#43218]
I'm using windows authentication but there are pages that are accessible by everyone. I allow anonymous by adding this `@attribute [Authorize, AllowAnonymous]`  to _Hosts.cshtml.

Problem: Although the page still loads, since the websocket disconnects, all blazor events such as `@onclick, @bind` no longer work.

Expected behavior:
The user is not allowed to view Authorized pages however anonymous page should be visible and have all blazor events working.

Edge Console error:
![image](https://user-images.githubusercontent.com/30071252/184189482-580c794e-73fc-425c-b9b9-b992e0aaaea6.png)

Program.cs
`
public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            Configuration = builder.Configuration;

            // Add services to the container.
            builder.Services.AddRazorPages();
            builder.Services.AddServerSideBlazor();
            builder.Services.AddHttpClient();
            builder.Services.AddControllers();
            builder.Services.AddHttpContextAccessor();

            // Add services to the container.
            builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();
           
            builder.Services.AddAuthorization(options =>
            {
                // By default, all incoming requests will be authorized according to the default policy.
                options.FallbackPolicy = options.DefaultPolicy;
            });

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            //app.UseHttpsRedirection();

            app.UseStaticFiles();
            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapFallbackToPage("/_Host");
                endpoints.MapBlazorHub();
            });

            app.Run();
        }
    }
`

**Comment by javiercn** [comment]
@youss2017 thanks for contacting us.

The problem with windows server is that it is all or nothing, you either require the users to authenticate or not, but you can't have both since Blazor Server is a connected model and Windows authentication establishes the user identity at the connection level too, so it can't change afterwards.

**Comment by youss2017** [comment]
I was not able to fix this however I have a workaround. I disable authentication on my blazor server and use a web services (MVC Controller) to authenticate the user and send the user information back to my blazor server. Afterward, I use a blazor component with the cached `UserPrinicipal` to determine whether to show to the page or not.

**Comment by youss2017** [comment]
Note: This method is not secure (may depend on implementation) however this is fine for internal use.
