### ISSUE TITLE
Testserver doesn't validate dependency injection as a normal host server

### ISSUE THREAD

**Issue by avidalcarrasco** [dotnet/aspnetcore#43217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While testing my project I noticed that the TestServer that can be created using `Host.CreateDefaultBuilder`
is not taking into consideration the miss-configuration while using dependency injection.
For example, I was able to inject a Scoped object into a Singleton object, which, if I run the application normally, fails.

### Expected Behavior

I expect that the TestServer throws error when dependency injection is miss-configured as the normal host will do.

### Steps To Reproduce

I created a repro to reproduce the issue: [Link](https://github.com/avidalcarrasco/TestServerNoChecks)

For the expected behavior just run the web application.
For the error behavior just run the test in the test project.

### Exceptions (if any)

Using `WebHostBuilder` for building the application instead of `Host.CreateDefaultBuilder` the error doesn't happen.
But it's not related to the issue that TestServer doesn't behave while getting it from `Host.CreateDefaultBuilder` 

### .NET Version

6.0.400

### Anything else?

Using Visual Studio Professional  2022 17.3.0

`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ```

**Comment by davidfowl** [comment]
It's because the environment isn't set the "Development". The scopes are only checked in dev by default.

**Comment by avidalcarrasco** [comment]
That is quite interesting!
Indeed, if I use `b.UseEnvironment("Development");` the testserver behave as I expected.
So now I have several points on this:

1. Why only in development?
2. Is not a different behavior on different environments problematic or confusing?
3. Is this documented somewhere and I totally missed it?
4. Why is this kind of injection working? I mean, why I can inject scoped into singletons at runtime.

Thank you for your time!

**Comment by davidfowl** [comment]
> Why only in development?

Performance reasons. We don't want the extra overhead of checking once you've found all of the bugs in development. You can set the flag outside of the environment as well, those are just the defaults when you use the host. Also historically, this feature didn't exist and then we added it and turned it on by default only in dev.

> Why is this kind of injection working? I mean, why I can inject scoped into singletons at runtime.

Hopefully you'd see the exception in development.

**Comment by avidalcarrasco** [comment]
Thank you, I understand the concern about performance loss.

> You can set the flag outside of the environment as well, those are just the defaults when you use the host.

Can you point me to the right setting? 
Is this documented?

> Hopefully you'd see the exception in development.
Sometimes you can build libraries that "can't be run" and are tested using unit testing only.

Also I guess that normally pipelines and it's test are running on testing env, not development env.

**Comment by adityamandaleeka** [comment]
> Also I guess that normally pipelines and it's test are running on testing env, not development env.

@avidalcarrasco Just making sure, are you running with "Testing" instead of "Development" for your Environment?

If you want to get the behavior that you're looking for, setting the Environment to "Development" is the easiest way to achieve that.

**Comment by avidalcarrasco** [comment]
Hello.
In my local machine I use "development" and in the pipeline i use "testing" and "acceptance", but needed to force the test server with `b.UseEnvironment("Development");` as @davidfowl suggested for any env.
For me this is fine but just noticing the lack of documentation or not being clear at least for me.
As the problem is "solved" for now, I will close this issue.
If you think you need to take action about it, please feel free to open it again.
