### ISSUE TITLE
Blazor Wasm Transient Disposable registrations of AuthorizationMessageHandler

### ISSUE THREAD

**Issue by oatsoda** [dotnet/aspnetcore#43234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As I understand it, in Blazor Wasm, registering Disposable dependencies with Transient lifetimes causes memory leaks as every instance of the dependency created throughout the lifetime of the app will never be garbage collected due to the DI Container maintaining a reference to each instance (presumably as part of its need to Dispose the instance; though why it doesn't release the reference after Disposing, I'm not quite sure).

There's even some sample code on how to detect if you have accidentally registered some Transient Disposables:
https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-6.0#detect-transient-disposables-in-blazor-server-apps

I've just run some very similar code on my app to check and was surprised to find that there are a couple of Blazor classes which are Disposable being registered as Transient:

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L43-L44

```
services.TryAddTransient<BaseAddressAuthorizationMessageHandler>();
services.TryAddTransient<AuthorizationMessageHandler>();
```

Which presumably means throughout the lifetime of the app these are never being garbage collected?

### Expected Behavior

As delegate handlers I guess these must be Transient, so it would mean that the `AuthorizationMessageHandler` would need another mechanism of unsubscribing from the `AuthenticationStateChanged`.

Unless of course, my understanding of Transient Disposables is incorrect?

### Steps To Reproduce

Apply some code, such as [here ](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L43-L44)to detect Transient Disposable classes and run your Blazor Wasm app - and observe that the above two types are detected.

### .NET Version

6.0.302

**Comment by oatsoda** [comment]
Here's a link to where the sample code for detecting the Transient Disposables was added https://github.com/dotnet/AspNetCore.Docs/issues/18786

**Comment by javiercn** [comment]
@oatsoda thanks for contacting us.

This is a requirement for the handlers to be used with HttpClientFactory, which creates its own DI scopes, so it is not a problem in that case.

**Comment by oatsoda** [comment]
@javiercn Thanks. OK, so the HttpClientFactory will dispose the Scope at which point it would remove all of the references to the disposable transients - but presumably during the lifetime of that Scope, those instances which are no longer used still aren't garbage collected?

**Comment by javiercn** [comment]
@oatsoda yep.

**Comment by oatsoda** [comment]
@javiercn What's the likely timespan of the Scope on the HttpClientFactory?  We're talking more like hours than seconds, right?

**Comment by javiercn** [comment]
@oatsoda the lifetime I believe is configurable, but I believe is between 2 and 5 minutes. Once HttpClientFactory creates an instance, it reuses it for the lifetime of the scope, I believe.
