### ISSUE TITLE
Unable to connect to the SPA development server at 'https://localhost:44490'. / Visual Studio 2022 - ASP.NET Core Angular

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43243]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-connect-to-the-SPA-development/10116778)._

---
I just created a project in angular with asp.net core and I get this error, I checked the paths that give me error and found nothing strange, I get the same error when trying to run from visual studio code or with "dotnet run", this does not happen if I create a project with angular cli in vs code, it only happens with vs. The project is brand new so I did not touch anything.

Error: Module not found: Error: Can't resolve 'C:/Users/ALEXANDER/Desktop/p/c#/Project1/Project1/ClientApp/src/app/nav-menu/nav-menu.component.css?ngResource' in 'C:\Users\ALEXANDER\Desktop\p\c#\Project1\Project1\ClientApp'

Error: Module not found: Error: Can't resolve 'C:\Users\ALEXANDER\Desktop\p\c#\Project1\Project1\ClientApp\node_modules\webpack-dev-server\client\index.js?protocol=auto%3A&username=&password=&hostname=0.0.0.0&port=0&pathname=%2fws&logging=info&reconnect=10' in 'C:\Users\ALEXANDER\Desktop\p\c#\Project1\Project1\ClientApp'

Error: The loader "C:/Users/ALEXANDER/Desktop/p/c#/Project1/Project1/ClientApp/src/app/nav-menu/nav-menu.component.css" didn't return a string.

---
#### Feedback Bot on 8/11/2022, 09:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@MackinnonBuck can you take a look?

**Comment by MackinnonBuck** [comment]
I was able to reproduce this by having "c#" in the pathname. Renaming the folder to "csharp" fixed the issue.

Could you try creating the project in a location that does not include "#" in the pathname, and let us know if that resolves your issue? Thanks.

**Comment by javiercn** [comment]
@MackinnonBuck thanks for looking into it. Yeah, having a special character like `#` in the path is bound to create problems.

I think we can resolve this as by design.

**Comment by Manzana0703** [comment]
@MackinnonBuck That worked, of all the problems I would never expect that character to cause such an error. Thanks for your help.
