### ISSUE TITLE
Can I auto switch blazor server to wasm when user view web pages?

### ISSUE THREAD

**Issue by moll33er** [dotnet/aspnetcore#43262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I want use blazor server by first load, and wasm download with background.  when wasm download finish and navigate to other url, used wasm.
[like this blog](https://blog.csdn.net/qq_32174441/article/details/122350559)

**Comment by MackinnonBuck** [comment]
Thanks for the suggestion. This idea has been brought up before and may be something we consider for the future.

Dupe of #27821
