### ISSUE TITLE
Simpler empty Blazor templates

### ISSUE THREAD

**Issue by fadihania** [dotnet/aspnetcore#43265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

One of the new features of Blazor in .NET 7 is the Empty templates, a nice idea to help in getting started immediately without having to clean the project.
Usually in other front-end frameworks like Angular and Vue, it's much simpler template that contains a single root component without any routing. In Blazor empty templates there's still more details that could be cleaned and simplified.

### Describe the solution you'd like

I will focus on Blazor WebAssembly as an example. In the project we could have a project that has simply .csproj, wwwroot/index.html, Program.cs and a single root component App.razor.

`Program.cs`
```
using MinimalBlazor;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.RootComponents.Add<App>("#app");

await builder.Build().RunAsync();
```

`App.razor`
```
<h1>Hello World</h1>
```

That's all what we need, it make it easier for those getting started with Blazor to understand components and bootstrapping of root component. There could be an option similar to hosted or PWA to include routing if required.

**Comment by MackinnonBuck** [comment]
Thanks for your feedback. We've added new empty project templates in .NET 7, and we're going to wait and see what the community feedback is before making additional template changes.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
