### ISSUE TITLE
[BlazorWasm] Too much is trimmed when not building web host

### ISSUE THREAD

**Issue by agr** [dotnet/aspnetcore#43283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I want just to produce a "library" for using in Javascript without running web host and trim a Blazor Wasm project, publishing produces code that fails to load reporting

> Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly

### Expected Behavior

No excessive trimming.

### Steps To Reproduce

1. `mkdir blazorwasm2; cd blazorwasm2; dotnet new blazorwasm --use-program-main`
2. under the `Client` directory add `Test.cs` with the following content:
```
using Microsoft.JSInterop;
public class Test
{
    [JSInvokable("Test")]
    public static int T()
    {
        return 42;
    }
}
```
3. Edit `Client/Program.cs` and remove all content of the `Main` method.
4. Edit `blazorwasm2.csproj` and add `<PublishTrimmed>true</PublishTrimmed>` under `<PropertyGroup>`.
5. `dotnet run`, open the page in browser, open the dev console and make sure `DotNet.invokeMethod('blazorwasm2', 'Test')` produces `42`.
6. Stop the server and publish: `dotnet publish -c Release`.
7. Run published version: `dotnet serve --directory bin\Release\net7.0\publish\wwwroot --port 8003` (assuming `dotnet tool install -g dotnet-serve` has been installed)
8. Open in a browser, check dev console, notice the following exception:

>  Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly

### Exceptions (if any)

> Uncaught (in promise) Error: Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly
    at Co (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:3:56607)
    at Object.$o [as bind_static_method] (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:3:52973)
    at st (blazor.webassembly.js:1:45835)
    at blazor.webassembly.js:1:42812
    at postRun (blazor.webassembly.js:1:43784)
    at callRuntimeCallbacks (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:12:16164)
    at postRun (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:12:12040)
    at doRun (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:12:122635)
    at run (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:12:122792)
    at runCaller (dotnet.7.0.0-preview.7.22375.6.rzhw1q5fn9.js:12:122272)

### .NET Version

7.0.100-preview.7.22377.5, also happens with 6.0.400

**Comment by MackinnonBuck** [comment]
Closing since this issue hasn't received any community engagement since the initial post.
