### ISSUE TITLE
What cause error "A connection that was expected to be kept alive was closed by the server"

### ISSUE THREAD

**Issue by huanyingtianhe** [dotnet/aspnetcore#43287]
Our service is an Asp.net core apllication, and we use Kestrel. now we are testing our two kinds of requests, one is put job, the other is delete job and we have limited job numbers for put job api in our service, so if we put  jobs more than the number of the upper limit, the backend should report an error, and as expected, the client in our test will receive the error message, however, when we doing the cleanup work(calling delete job api) , we will receive the error: "A connection that was expected to be kept alive was closed by the server".  our test code just like this:

```
try {
    putJob()
}
catch (exception ex){
    verifyException(ex)
}
finally{
    deleteJob();
}
```
during putJob and deleteJob we both start 4 threads to call the corresponding api, and there are two connections during the call. and each putJob-operation will last around 800ms , delete-job operation will last 450 ms, the test will last around 10 minutes.

![image](https://user-images.githubusercontent.com/5997003/184609884-f9d9a993-6026-4352-91e4-6ae8a87de6cf.png)

if I change the ServicePointManager.DefaultConnectionLimit to 4, we will not meet the error during deleting. it doesn't like the connection is closed by keep alive in server side. does Kestrel close the connection if application code throw exception? could you please help me to find the reason? [halter73](https://github.com/halter73)

**Comment by adityamandaleeka** [comment]
@huanyingtianhe Can you share server logs from when this happens? It would help understand why the server is closing the connection.

It would also be great if you could share a minimal repro project that demonstrates this issue.

**Comment by huanyingtianhe** [comment]
> @huanyingtianhe Can you share server logs from when this happens? It would help understand why the server is closing the connection.
> 
> It would also be great if you could share a minimal repro project that demonstrates this issue.

yeah, let me try, currently we did not enable the Kestrel log, it is hard to see the root cause

**Comment by adityamandaleeka** [comment]
@huanyingtianhe Thanks, please let us know when you have the server logs available.

**Comment by huanyingtianhe** [comment]
after enable logs, we have found the root cause, it is our problem, we can close it. thanks
