### ISSUE TITLE
Issue getting protected route to work in 6.0 but works in 5.0

### ISSUE THREAD

**Issue by Ninja4Code** [dotnet/aspnetcore#43296]
My application is an SPA with React.  I'm doing some Antiforgery token creation and validation.  React does not support Antiforgery out of the box so you have to roll your own implementation.  In 5.0, I created a protected route in Startup that when that endpoint is reached it will create a antiforgery header that I stick into the post request later via fetch.  This all works very nicely in 5.0.  But for some reason can't get this functionality in 6.0 now that they've messed with the Program/Startup mix.  Here's the endpoint setup in 5.0 that worked.  Earlier in ConfigureServices I'm wiring up Antiforgery.

For 6.0 I've tried to do this in the Program.cs and Startup.cs to no avail.  The endpoint is never reached.  I look at the logging and see that there's a DeveloperException in the pipeline that's saying that favicon.ico is not being proxied.  The one difference in my code for 6.0 is I'm using UseEffect in a functional component instead of a stateful component.  

I've also read that there were some issues with UseEffect in 6.0 with proxying to favicon.  So I'm just looking for a way to create the antiforgery token  in 6.0 because 5.0 is no longer supported.

`app.UseEndpoints(endpoints =>       
            {
                endpoints.MapGet("antiforgery/token", context =>
                {
                    var tokens = antiforgery.GetAndStoreTokens(context);
                    context.Response.Headers.Append("XYZ", tokens.RequestToken!);
                    return Task.FromResult(StatusCodes.Status200OK);
                }).RequireAuthorization("AuthenticatedOnly");                
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}");
            });`
UPDATE: I did get this working in 6.0!  I created the endpoint in Program.cs.  You can feel free to close out this ticket but would love to know how to get rid of the proxying error to favicon.  I suspect this is only an issue on the dev server.

**Comment by MackinnonBuck** [comment]
Happy to hear your issue is resolved. Closing this issue.
