### ISSUE TITLE
Why are methods that are not Async suffixed with Async in ProtectedBrowserStorage class?

### ISSUE THREAD

**Issue by Yashuaa** [dotnet/aspnetcore#43295]
Hi I noticed that here: https://github.com/dotnet/aspnetcore/blob/51ccce6d743dddf995b3661f07b0e1990b68dc7d/src/Components/Server/src/ProtectedBrowserStorage/ProtectedBrowserStorage.cs#L72

There are multiple methods that return a `ValueTask `and aren't marked with the `async` modifier, yet suffixed with the word **Async**... Why? That means they are synchronous methods being suffixed with Async right? Won't that confuse the caller and potentially tie up the whole thread?

**Comment by MackinnonBuck** [comment]
Even if a method is not declared with the `async` keyword, the convention is if it returns a `Task` or `ValueTask`, the method name is suffixed with `Async`.

**Comment by Yashuaa** [comment]
@MackinnonBuck - That's simply just not true, and never has been. If that is the case, then these [docs  ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async#:~:text=Use%20the%20async%20modifier%20to%20specify%20that%20a%20method%2C%20lambda%20expression%2C%20or%20anonymous%20method%20is%20asynchronous.%20If%20you%20use%20this%20modifier%20on%20a%20method%20or%20expression%2C%20it%27s%20referred%20to%20as%20an%20async%20method)need to explicitly state that... The suffix of **Async** _literally_ comes from the keyword _async_, so suffixing a **non-async** method with `Async` and saying that "because it returns a `Task` we can do that" - literally makes no sense at all. 

It is totally contradictory to two things

1) `async` methods are `async`, they have the `await` keyword
2) per the docs - "_Use the async modifier to specify that a method, [lambda expression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions), or [anonymous method](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/delegate-operator) is asynchronous. If you use this modifier on a method or expression, it's referred to as an async method_"

**Comment by Yashuaa** [comment]
I talked to some people on this discord who helped expand on your answer a bit more.. It makes sense but I think you all should clarify this in the docs.
