### ISSUE TITLE
Swagger / OpenAPI support in gRPC JSON transcoding

### ISSUE THREAD

**Issue by mparry** [dotnet/aspnetcore#43294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We need Swagger generation (and also, less importantly, would like the Swagger UI) when using gRPC JSON transcoding to produce a REST API on top of gRPC.

### Describe the solution you'd like

Similar - or better! - Swagger / OpenAPI support as was available in the experimental `Microsoft.AspNetCore.Grpc.*` APIs.

### Additional context

I hope that this is an appropriate way to raise this. Besides our specific needs, it seemed useful for there to be an issue about the feature in this repo.

We have been evaluating the new gRPC JSON transcoding libraries with `7.0.0-preview.7`, migrating our existing usage of the experimental `Microsoft.AspNetCore.Grpc.*` APIs under .NET 6.

Previously, in [this blog](https://devblogs.microsoft.com/dotnet/announcing-grpc-json-transcoding-for-dotnet/#comment-15495), it was stated that the aim was to provide a solution in .NET 7, or else there would at least be a new experimental library providing an interim solution. Neither is available yet, as of `preview.7`. Would it be possible to share the current aims or what is now likely to be the outcome as of .NET 7 final?

Thanks!

**Comment by captainsafia** [comment]
Assigning to @JamesNK to investigate publishing the experimental APIs to NuGet.

**Comment by JamesNK** [comment]
Done with https://github.com/dotnet/aspnetcore/pull/43384. An updated Microsoft.AspNetCore.Grpc.Swagger will ship with RC1.
