### ISSUE TITLE
Content not being posted to textarea ASP.NET Core

### ISSUE THREAD

**Issue by ilyesbek** [dotnet/aspnetcore#43301]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hello,
After uploading a file. I want to display its content in a textarea in the same web page. Below the controller. 

```
 public async Task<IActionResult> Check(IFormFile ConfigFilePath)
        {
  
            REST_API.JsonResult jsonResultOutput = ProgramAPI.Check(ConfigFilePath);

            string OutputMessage = jsonResultOutput.message;

           return Ok(OutputMessage);
        }

```

OutputMessage is where the file content is being stored from a JSON Result. When I return using Ok(). the expected result is displayed in another page.

And this is the HTML, knowing that textarea is inside the form.

`<textarea asp-for="OutputMessage" type="text" class="form-control" rows="5" id="MessageInputField" autofocus></textarea>`

### Expected Behavior

Result content is to be displayed in the textarea. not in another web page

### .NET Version

6.0

**Comment by TanayParikh** [comment]
Hello @ilyesbek, thanks for contacting us. The scenario you're describing isn't immediately clear. Could you please provide a minimal, public, github reproduction application so we may take a look. This repro app should not have any other code except what is required to reproduce this issue.
