### ISSUE TITLE
NodeJS projects are still built when passing /p:BuildNodeJS=false when nodejs is installed

### ISSUE THREAD

**Issue by lbussell** [dotnet/aspnetcore#43310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Tested on Ubuntu 20.04, with this docker image: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/20.04/amd64/Dockerfile

See this logic in build.sh:
https://github.com/dotnet/aspnetcore/blob/main/eng/build.sh#L255-L269

If nodejs is installed on the system, and `/p:BuildNodeJs=false` is passed to the build, nodejs projects are still built. This means that when running an offline source-build on a machine with nodejs installed, the offline build fails since Yarn.MSBuild is not source-build friendly and we don't produce or ship it. On an online build, this results in Yarn.MSBuild being restored from the internet and reported as a prebuilt.

### Expected Behavior

If `/p:BuildNodeJs=false` is passed, we should never have `build_nodejs` set to true.

### Steps To Reproduce

1. install nodejs
2. build aspnetcore with the argument `/p:BuildNodeJs=false`
3. observe that nodejs projects are still being built.

### .NET Version

7.0.100-rc.1.22410.15

**Comment by wtgodbe** [comment]
I believe this has been fixed
