### ISSUE TITLE
Customise blazor-error-ui at runtime

### ISSUE THREAD

**Issue by philiphendry** [dotnet/aspnetcore#43318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When we make a call to a service from blazor web assembly the server may error and return a http status code of 500 along with a correlation id. The error is treated as unhandled and propagates up through the components. We can customise the blazor-error-ui message but only at design time and therefore we cannot modify this to display the correlation id.

This is one example of when we would like to be able to interpret the exception that occurred and display a message based on that exception. Another example would be if the error message contains a user friendly message that should be displayed.

The issue #24108 mentions adding more detail to the message but doesn't offer developer customisation.

We have tried using the ErrorBoundary wrapping the application in App.razor but having the entire application disappear and be replaced with an error dialog isn't a good user experience. We have also tried to create a custom component from ErrorBoundaryBase that displays our own error content but sets ShouldRender to false so the client application remains. However, this results in all content being removed and leaving a blank browser window and was feeling very 'hacky'.

### Describe the solution you'd like

We would like to have an extension point that allows us to interpret the exception being raised and change the UI rendered by blazor-error-ui based on the content of that exception.  This extension could be javascript only or it could be an adaptation of the ErrorBoundary?

For example the [showErrorNotification](https://github.com/dotnet/aspnetcore/blob/a4906cd3e44136bd210bd522ff61eadba3f84a86/src/Components/Web.JS/src/BootErrors.ts#L6) function could take the error exception and call an extensible point we provide? In addition if our extension "handles" the error and returns true that would suppress the blazor-error-ui being shown.

Ultimately we are looking for a similar experience to the [Application.DispatcherUnhandledException](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.dispatcherunhandledexception?redirectedfrom=MSDN&view=windowsdesktop-6.0) event in WPF.

**Comment by javiercn** [comment]
@philiphendry thanks for contacting us.

The `blazor-error-ui` is to display unhandled exceptions that happen in the app, it is not meant to be a general and extensible error notification for the user.

Our recommendation would be that you build a component, place it in your layout and dispatch whatever error you want to display to it with a service.

```mermaid
flowchart LR
subgraph App
   Component
   ErrorDisplay
end
Component--"Dispatch"-->ErrorService
ErrorService--"Notify"-->ErrorDisplay
```

**Comment by Skintkingle** [comment]
I'm interested in this feature request, as have the same situation. I've been looking for a parallel to `Application.DispatcherUnhandledException` for a long time in Blazor. Being provided an Exception and given the opportunity to pull useful information off domain specific Exceptions on our way out to aid support calls.

Is the suggestion here to add try catch code around every service call, handle it there to get our domain specific exception information, and then rethrow? that seems wildly inefficient for a "system down" error where we're trying to be helpful for the subsequent telephone call. That feels like we're going to be adding a lot of the same code all over our components.

**Comment by philiphendry** [comment]
@javiercn Dispatching an error has never been the problem to be honest and the model you describe is fine. However, it's the capturing of the error that is the major problem. ErrorBoundaryBase can do this because it has access to the internal interface IErrorBoundary.HandleException but I can't derive from ErrorBoundaryBase because it calls StateHasChanged and this causes the whole app to re-render. ErrorBoundary solves that problem by hiding all ChildContent but that's not the user experience we want.

I thought there was a simply solution to this by "monkey-patching" window.Module.printErr with my own function that calls console.err() and then display our own message but the parameter 'e' passed to printErr is the exception string and not a JSON serialised version of the exception I had hoped for as that would have contained the CorrelationId property I needed.

I'm reminded again why I need this as my server was stopped and all our client is able to say is "Unexpected error". Also, I've had server side exception which will capture and throw SOAP faults but still can't extract the correlation id from the fault to display to the user for quoting to support.
