### ISSUE TITLE
Create Angular/React 7.0/6.0 project and use the command line to run project, the browser page always displays "Launching the spa proxy...“.

### ISSUE THREAD

**Issue by v-zhenxue** [dotnet/aspnetcore#43335]
**Azure DevOps work item:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1589160?src=WorkItemMention&src-action=artifact_link

**INSTALL STEPS**
Install 7.0 RC1 x64 from: [Pipelines - Run 20220815.1-7.0.100-rc.1.22415.4-144791 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D1944579%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-zhajin%40microsoft.com%7Ca870737322bc438bf74d08da7fb2d4a0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962703570098544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YFtyzqvwReflhtKN3k96C%2FIyrSJaQC%2BXr9DGk6cs5QQ%3D&reserved=0)
7.0 feed using: [https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-rc.1.22415.4-shipping/nuget/v3/index.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkgs.dev.azure.com%2Fdnceng%2Fpublic%2F_packaging%2F7.0.100-preview.7.22377.5-shipping%2Fnuget%2Fv3%2Findex.json&data=05%7C01%7Cv-zhajin%40microsoft.com%7Ca870737322bc438bf74d08da7fb2d4a0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962703569942334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YyUlEHGhVoCGL2zdFGLn6zS93FPwfJ78Dp08XFAVDCA%3D&reserved=0)

**Testcases Affected**
[[7.0/6.0]SimpleWebAppWithAngularIndAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore60/6x_SimpleWebAppWithAngularInd_Mac.md)
[[7.0/6.0]SimpleWebAppWithAngularNoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore60/6x_SimpleWebAppWithAngular_Mac.md)
[[7.0/6.0]SimpleWebAppWithReactIndAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore60/6x_SimpleWebAppWithReactInd_Mac.md)
[[7.0/6.0]SimpleWebAppWithReactNoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore60/6x_SimpleWebAppWithReact_Mac.md)

**Platform**
- [ ] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
create and run project using command-line.
Note: Install the LTS version of [Node.js](https://nodejs.org/en/) which is recommended for most users.
1. dotnet new angular --auth Individual -f net7.0 -o test11
2. cd test11
3. dotnet build
4. dotnet run

**Actual Result**
Using the command "dotnet run", the browser page always displays "Launching the spa proxy...“,when copy url to the browser page, terminal display error:
![image](https://user-images.githubusercontent.com/85606986/185023455-abeca310-4a03-4826-a62f-79b31596957b.png)
![image](https://user-images.githubusercontent.com/85606986/185023918-ba990c24-b8ef-4758-bef5-c9591fc6a7e5.png)

**EXPECTED**
Run the project and load the page successfully.
![image](https://user-images.githubusercontent.com/85606986/185024237-16b6a858-f6eb-4820-8854-293faad40dfa.png)

**Comment by adityamandaleeka** [comment]
The issue here was a bug in the macOS dev-certs changes that broke the PEM export scenario that the angular/react workflows use (e.g. https://github.com/dotnet/spa-templates/blob/main/src/content/React-CSharp/ClientApp/aspnetcore-https.js#L23).

I have a fix in PR here: https://github.com/dotnet/aspnetcore/pull/43358

**Comment by adityamandaleeka** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/43358
