### ISSUE TITLE
Visual Studio/ Blazor - resx files improperly nested under razor.cs

### ISSUE THREAD

**Issue by paulguz-datapa** [dotnet/aspnetcore#43342]
If I create a component resx file named "MyComponent.razor.resx", so as to nest it under the component, Visual Studio nests the resx file under the razor.cs file, rather than under the razor file.

![image](https://user-images.githubusercontent.com/86300100/185077078-637a791a-1ed1-4c06-930d-c1c7c41bd440.png)

**Comment by javiercn** [comment]
@paulguz-datapa thanks for contacting us.

This repo deals with runtime concerns only, for you to get a better and faster answer, we recommend you file the issue via the report a problem dialog in Visual Studio as depicted [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
