### ISSUE TITLE
Make "NonDisposableStream" as public.

### ISSUE THREAD

**Issue by himenkumars** [dotnet/aspnetcore#43362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying upgrade .NET core 2.1 Application to .NET 6, Application was using "NonDisposableStream" class from Microsoft.AspNetCore.Mvc.Core.Internal.
As per the [announcement  ](https://github.com/dotnet/docs/issues/14950) "NonDisposableStream" class is marked as internal, (and also moved to Microsoft.AspNetCore.Mvc.Core.Infrastructure namespace) which is not accessible to mvc controller.

I was not able to find any alternative for the same, hence I would like to request you to make it public.

Similar Issue : https://github.com/dotnet/aspnetcore/issues/14512

### Describe the solution you'd like

Make Microsoft.AspNetCore.Mvc.Core.Infrastructure.NonDisposableStream to public.

**Comment by javiercn** [comment]
@himenkumars thanks for contacting us.

Infrastructure types are not something we are keen on making public unless we have a compelling reason to. We recommend you author a similar type or put it in your project from [here](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/NonDisposableStream.cs) but we do not plan to make this public as it prevents us from making changes in the future and adds little value to people.

**Comment by davidfowl** [comment]
You should file an issue on https://github.com/dotnet/runtime requesting this kind of stream be public. It shouldn't be exposed from ASP.NET Core.
