### ISSUE TITLE
Calling Blazor functions from javascript does not work as expected

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#43367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to create a text editor which operates on contenteditable div. As it requires some events cancelled based on certain keystrokes etc, I cannot use Blazor. So instead I am using JavaScript that invokes Blazor  functions as necessary.

The guidance given on the official documentation does not properly create this scenario. Every example given on that page requires a call to the JavaScript function to pass `dotNetHelper`  and that `dotNetHelper` instance is used to invoke method on the Blazor component.

This is the reference doc https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#class-instance-examples

It does not help if JavaScript needs to trigger an event independently. The documentation does not cover the scenario at all.  

It seems that there is no way for JavaScript to cleanly invoke a component's function (maintaining a static dictionary of {component id, dotNetHelper} comes to mind, but it sounds messy.

### Expected Behavior

A clear example of .net functions being triggered independently from JavaScript, if it is possible at all.  

### .NET Version

6.0.5

**Comment by javiercn** [comment]
@mayur-ekbote thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project as a public github repository that illustrates the problem?

It is not clear to us from your description what the problem you seem to be facing is.

**Comment by mayur-ekbote** [comment]
Created a github project here https://github.com/mayur-ekbote/EditableContentDivDemo

The crux of the problem is this:
1. To invoke a .net method, JS requires an instance of the `DotNetObjectReference<>` 
2. One example given in the doc saves the object reference in the javascript file as static member of a class. This approach is not  useful since there could be multiple instances of the component on a page (the github repo demonstrates the problem).

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#pass-a-dotnetobjectreference-to-a-class-with-multiple-javascript-functions

3. Other examples involve some event raised from the Blazor component which  passes the instance of the `DotNetObjectReference<>`  to a javascript  function. The javascript  function then uses the instance to call a method of the component. This approach is not useful because it does not allow javascript to initiate a call on a Blazor component!

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#class-instance-examples

In all, there is no way specified in the docs for JS to invoke a method on a component _instance_  . 
There is a way though - save the  `DotNetObjectReference<>`  in a Map with html **id** as a key. Then every time identify the `caller `element and use `caller.id` to get the reference. But it is not documented anywhere. Making it harder to understand the potential drawback.

**Comment by javiercn** [comment]
@mayur-ekbote thanks for the additional details.

I am not sure I am fully grasping your goal, but I do think I see enough to give you some pointers. If I were to implement something like what you are trying, I would do as follows:
* Capture an element reference for the widget that I am rendering.
* Inside OnAfterRender, invoke a JS function passing the element reference and the component instance (this) as a JSObjectReference.
* Inside the JS function implementation, attach the JS Object reference to the element in a property, for example element.component = componentRef;
* When you raise an event in JS and need to call the corresponding JS interop code, grab the event target, pick the object reference from the `component` property and invoke the method you want.

**Comment by mayur-ekbote** [comment]
Thanks @javiercn 
Yes, it does solve the problem. Your example is, AFAIK, the first one I have come across where a Blazor reference to an element is saved with its corresponding JavaScript element - I don't know if it creates circular references. 
It would be great if it is documented in the official documentation.

**Comment by javiercn** [comment]
@guardrex can you add a section for this scenario?

**Comment by guardrex** [comment]
@mayur-ekbote ... You said that this scenario isn't covered ...

> there is no way specified in the docs for JS to invoke a method on a component instance

It should be covered by ...

**Component instance .NET method helper class**
https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript#component-instance-net-method-helper-class

Of course, the exact objects and UI behaviors/gestures are different, but the purposes (per that section's stated goals) are to deal with  ...

* When several components of the same type are rendered on the same page.
* In Blazor Server apps with multiple users concurrently using the same component.

That's a shared list item component that needs to make a .NET method in the component invokable.

```razor
<li>
    @message
    <button @onclick="InteropCall" style="display:@display">InteropCall</button>
</li>

...

@code {
    ...
    private void UpdateMessage()
    {
        message = "UpdateMessage Called!";
        display = "none";
        StateHasChanged();
    }
    ...
}
```

Use of the helper class with its `Action` specified when instantiated with the method `UpdateMessage` makes it possible for each list item to call its own `UpdateMessage` ...

```razor
<ul>
    <ListItem />
    <ListItem />
    <ListItem />
    <ListItem />
</ul>
```

![image](https://user-images.githubusercontent.com/1622880/186145164-de074246-de24-4c64-ab19-7e72f33ec226.png)

Of course, I can't say at a glance 🏃‍♂️ **_how_** it would compose exactly for your specific editable `<div>` goals. However, I think that the pattern of implementation is the same. It would be helpful if you and/or Javier would explain why that section doesn't cover this scenario.

**Comment by javiercn** [comment]
@guardrex I think users fail to connect the dots on how to use JS interop and element reference to achieve the scenario.

**Comment by guardrex** [comment]
@javiercn ... The following doesn't match your description exactly, but I was seeing if there's an list item scenario similar to the topic's current example but without the helper class and that crudely follows your concept. The following seems to work ...

```html
<script>
  window.setup = (element, dotNetHelper) => {
    element.dotNetHelper = dotNetHelper;
  }

  window.interopCall = async (element) => {
    await element.dotNetHelper.invokeMethodAsync('UpdateUI');
  }
</script>
```

`Shared/ListItem2.razor`:

```razor
@inject IJSRuntime JS

<li>
    <span @ref="spanRef" onclick="interopCall(this)">Select one of these list item buttons.</span>
    <span style="display:@display">Not Updated Yet!</span>
</li>

@code {
    private ElementReference spanRef;
    private string display = "inline-block";
    private DotNetObjectReference<ListItem2>? objRef;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            objRef = DotNetObjectReference.Create(this);
            await JS.InvokeVoidAsync("setup", spanRef, objRef);
        }
    }

    [JSInvokable]
    public void UpdateUI()
    {
        display = "none";
        StateHasChanged();
    }
}
```

`Pages/Example.razor`:

```razor
@page "/example"

<h1>Call .NET Example 2</h1>

<ul>
    <ListItem2 />
    <ListItem2 />
    <ListItem2 />
    <ListItem2 />
</ul>
```

That doesn't match the "**_JSObjectReference_**" part, as I'm passing a `DotNetObjectReference` and attaching it to the element for use later to invoke a .NET method. Could you comment on this relative to your original concept?

**Comment by mayur-ekbote** [comment]
> * When several components of the same type are rendered on the same page.
> * In Blazor Server apps with multiple users concurrently using the same component.

While it covers these two aspects, it does not cover the case where JavaScript is initiates the call to a Blazor function. 
In all the examples given in that section: 
1. A Blazor event is triggered (in this case a button click)
2. The Blazor event handler calls the the JS function. Since the event handler is within Blazor boundaries, it has access to the `DotNetObjectReference`  instance. This `DotNetObjectReference` instance is passed to JS script function.
3. The JS function then uses the same `DotNetObjectReference` and calls Blazor instance function.
4. Effectively, it does not illustrate the situation where a JS function _initiates_ a call to Blazor instance. In that scenario, a `DotNetObjectReference` needs to have been stored already somewhere within JS boundaries.

**Comment by guardrex** [comment]
Thanks @mayur-ekbote. I'll see if @javiercn has remarks on my ☝️ **_hacks_** 🙈 relative to his concept approach, especially to resolve the "**JSObjectReference**" delta, and then work up a new section for the doc. I'll ping u on the docs PR later for a look.
