### ISSUE TITLE
EndpointFilter better handling for IActionResult

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#43369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to implement a filter for the controllers and minimal API, but it seemed the endpoint filter not handling the `IActionResult` properly

For example, I had a filter likes follows:

``` c#
public class ConditionalFilter: IAsyncResourceFilter
#if NET7_0_OR_GREATER
    , IEndpointFilter
#endif

{
    public Func<HttpContext, bool> ConditionFunc { get; init; } = _ => true;
    public Func<HttpContext, object> ResultFactory { get; init; } = _ => new NotFoundResult();

    public virtual async Task OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next)
    {
        var condition = ConditionFunc.Invoke(context.HttpContext);
        if (condition)
        {
            await next();
        }
        else
        {
            var result = ResultFactory.Invoke(context.HttpContext);
            context.Result =  result as IActionResult ?? new OkObjectResult(result);
        }
    }
#if NET7_0_OR_GREATER
    public virtual async ValueTask<object> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {
        var result = ConditionFunc.Invoke(context.HttpContext);
        if (result)
        {
            return await next(context);
        }
        return ResultFactory.Invoke(context.HttpContext);
    }
#endif
```

When I returned a `NotFoundResult`, it would respond likes follows:

![image](https://user-images.githubusercontent.com/7604648/185431655-38c10669-4080-44c2-9430-0cd0fdaaa874.png)

While what I expect should be a `404` response and without a response body

### Describe the solution you'd like

If the object returned is `IActionResult`, could we do some convention so that it would be handled like `IResult`.

For example, treat `Microsoft.AspNetCore.Mvc.NotFoundResult` as `Microsoft.AspNetCore.Http.HttpResults.NotFound`, or let `NotFoundResult` implement `IResult` or something else

### Additional context

.NET 7 Preview 7

**Comment by davidfowl** [comment]
In the latest preview of .NET 7 it should be possible to write an endpoint filter that runs for both mvc and minimal endpoints so you don't need this switch.

That said, IActionResult will not work for minimal endpoints, so it's better to unify to IResult if you want to write something that runs everywhere.

**Comment by davidfowl** [comment]
```
    public Func<HttpContext, object> ResultFactory { get; init; } = 
#if NET7_0_OR_GREATER
_ => Results.NotFound();
#else
_ => new NotFoundResult();
#endif
```
