### ISSUE TITLE
Error MSB6006: "dotnet.exe" exited with code 1

### ISSUE THREAD

**Issue by AlbertoPa** [dotnet/aspnetcore#43366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When publishing a Blazor WASM app in Net 7 Preview, the error ``Error MSB6006: "dotnet.exe" exited with code 1`` is shown. This would seem a regression already experienced in previous versions: https://github.com/dotnet/aspnetcore/issues/42262

### .NET Version

7.0.100-preview.7.22377.5

**Comment by javiercn** [comment]
@AlbertoPa thanks for contacting us.

Do you have spaces or any other special character in your path?

**Comment by AlbertoPa** [comment]
Hi @javiercn 

> Do you have spaces or any other special character in your path?

Yes, spaces only.

**Comment by javiercn** [comment]
@AlbertoPa thanks, I am going to dupe this with https://github.com/dotnet/sdk/issues/26026 which is tracking the fix.
