### ISSUE TITLE
Errors when add "Razor Class Library" reference to .NET6 Blazor Webassembly

### ISSUE THREAD

**Issue by ArnoSlabbinck** [dotnet/aspnetcore#43377]
I have a new" blazor webassembly" and a "Razor Class Library" for components. But I get an the following error. I don't know what is meant by the warning and error since I  can't understand the file itself (Server or Client even Shared)

warning: Warning RAZORSDK1007 Reference assembly C:\Users\ArnoS Es\source\repos\Issuetracker\Bugtracker\Client\bin\Debug\net6.0\Bugracker.Client.dll could not be found. This is typically caused by build errors in referenced projects.

The error:  Metadata file 'C\Users\ArnoS\Source\Repos\Issuetracker\Bugtracker\Client\bin\Debug\net6.0\Bugtracker.Client.dll' could not be found

![image](https://user-images.githubusercontent.com/19469941/159882912-42817e26-9a87-4dd8-a113-e12620e8df0a.png)

**Comment by javiercn** [comment]
@ArnoSlabbinck thanks for contacting us.

Could you provide a minimal repro project that illustrates the problem as a public github repository?
