### ISSUE TITLE
w3wp.exe Faulting Application Exception Code 0xc0000409

### ISSUE THREAD

**Issue by jacseychell** [dotnet/aspnetcore#43378]
We are having an issue with our application when it is installed within an environment and it is displaying unusual behavior we have not experienced before. 

The application will run successfully on initial load and successfully poll to an external site when someone is logged onto the server where the application is running from. But when you log off the server and let it poll on it's own, it will throw an application error, and the only information it provides is w3wp.exe Faulting Application Exception Code 0xc0000409. 

No logs are logged by the application to say something has occurred, the application simply just stops it's process, then will restart it's polling at it's next scheduled time. And after it throws this fault once, it will continue to fault each round of polling. 

We have taken the crash dumps from the process, and ran the dumps within DebugDiag but need some help decoding what might be faulting within the application / or environment to prevent the polling service from continuing. 

We are also receiving an error from the ucrtbase.dll, but that is also not providing any additional information regarding what's faulting, see below 
 
![image](https://user-images.githubusercontent.com/55416852/140665385-978e6d01-a4b8-4175-9b92-d4b57e543aec.png)

We have tried:
* Setting the application on its own app pool
* Updated and installed the latest C++ Redistributables 
* Re-registering the urctbas.dll using Regsver32
* Copy the OCX into SystWow64 folder 
* Updated the Windows 10 SDK to the latest version 

Attached is the debugdiag file that was generated from the crash dumps
[MultipleDumps_MultipleRules.zip](https://github.com/dotnet/standard/files/7493398/MultipleDumps_MultipleRules.zip)

**Comment by adityamandaleeka** [comment]
@jacseychell Are you still running into this issue?
