### ISSUE TITLE
Grpc.JsonTranscoding requires manually copying annotations.proto and http.proto into projects

### ISSUE THREAD

**Issue by rars** [dotnet/aspnetcore#43376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using AspNetCore.Grpc.JsonTranscoding I have to manually copy Google API annotations.proto and http.proto into my projects so that they can e.g. `import "google/api/annotations.proto";`.

### Describe the solution you'd like

A NuGet package that I can reference that contains the correct version of these files compatible with the version of AspNetCore.Grpc.JsonTranscoding I'm using and will make these files available in the build process so that e.g. `import "google/api/annotations.proto";` works.

### Additional context

An alternative solution might be to contain these files in another existing package e.g. discussed in https://github.com/grpc/grpc/issues/18214. Maybe the landscape has changed and they would reconsider including in Grpc.Tools.

I've made a suggestion as to how this might be achieved in https://github.com/grpc/grpc-dotnet/issues/167#issuecomment-1214192168. Example here: https://github.com/rars/JsonTranscodingDemo
This uses GeneratePathProperty="true" on the PackageReference and then AdditionalImportDirs="$(PkgJsonTranscoding_Protos)\content" on the relevant Protobuf elements that need to import google/api/annotations.proto.

Thanks.

**Comment by halter73** [comment]
Triage decision:

This looks like something we should consider for .NET 8.

**Comment by JamesNK** [comment]
I think I found a way to make this idea work without the developer having to do anything by including some msbuild with the package. No need to add `GeneratePathProperty="true"` or `AdditionalImportDirs="$(PkgJsonTranscoding_Protos)\content"` to csproj.

See https://github.com/dotnet/aspnetcore/pull/44999
