### ISSUE TITLE
Reload Blazor UI

### ISSUE THREAD

**Issue by Terricide** [dotnet/aspnetcore#43370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to integrate Blazor into an existing SPA application called Wisej, what I would like to do is be able to run Blazor.start multiple times or force Blazor to re-render.

I've add blazor webassembly  autostart=false
On my left hand navigation menu I click a button which adds a div with the id of app and calls Blazor.start and Blazor is kind of working.
However once I close that section the div is removed
When I navigate back to that section it says Blazor is already started.

If I use an iframe then it works exactly how I want however I lose debugging capability.

### Describe the solution you'd like

What I would like to do is force blazor to re-render the ui

### Additional context

Mixing Wisej and Blazor in a single project

**Comment by javiercn** [comment]
@Terricide thanks for contacting us.

I think what you might be looking for is JS root components. https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#render-razor-components-from-javascript

Start Blazor once, and render the components as you need.

**Comment by Terricide** [comment]
Cool, Is that Server side only? Or wasm too?

**Comment by Terricide** [comment]
Cool thanks, I think that's exactly what I was looking for. I had thought I read about doing it a long time ago but my keyword search must have been wrong because I couldn't find it.

**Comment by Terricide** [comment]
I'm working on getting the two frameworks to talk to each other. Is there a way to do something like this?

var component = await Blazor.rootComponents.add(this.container, "counter", {});
component.invokeMethodAsync("jsinvokeabledotnetfunction");

Thanks

**Comment by javiercn** [comment]
@Terricide The component will need to give you back an IJSObjectReference of itself you can call methods on, and those methods will need to be marked as `JSInvokable`

**Comment by Terricide** [comment]
What comes back from Blazor.rootComponents.add is an object that looks like this.

_componentId: 0
_jsEventCallbackWrappers: Map(0) {size: 0}
[[Prototype]]: Object

and I get this error if I try to invoke a method
component.invokeMethodAsync is not a function

**Comment by Terricide** [comment]
Okay thanks, that is what I ended up doing I was confused that maybe I was missing something.

I'm trying to mix WiseJ and Blazor Wasm into a single project and the when I JS.InvokeAsync and pass  DotNetObjectReference.Create(componentRef) the object in javascript is correct outside of Wisej, but when running inside of wisej the object is created incorrectly somehow. I'm working with the devs at WiseJ to see if it is something they can fix. I can use setParameters to pass data in as a workaround.

**Comment by Terricide** [comment]
Is there an easy way to get an unminified version of _framework/blazor.webassembly.js?

When I host a blazor app inside Wisej I can get a simple control like counter to work, however any control using DotNetObjectReference.Create(this); to pass the object back isn't working correctly.

The object returned to javascript is different only inside Wisej. Outside it is working fine and I can't seem to find how it is getting messed up.

[BlazorApp1.TwoWay.zip](https://github.com/dotnet/aspnetcore/files/9416072/BlazorApp1.TwoWay.zip)
