### ISSUE TITLE
[Blazor] HttpPost with StreamContent reads whole file into memory

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#43388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using StreamContent with HttpClient.PostAsync in Blazor WASM, the whole file is loaded into memory before initiating the HTTP call

### Expected Behavior

The HTTP call should be made immediately, and the data in the stream should be read in chunks.

### Steps To Reproduce

1: Create a hosted Blazor WASM app
2: Add the following to WeatherForecast controller

```c#
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = long.MaxValue)]
        [RequestSizeLimit(long.MaxValue)]
        public IActionResult Upload()
        {
            Console.Beep();
            IFormFile file = Request.Form.Files[0];
            if (file.Length == 0)
                return BadRequest();
            Console.Beep();
            return Ok();
        }
```

Now try running the following code in both a console app with FileStream as the source for StreamContent, and then inside a Blazor WASM app with IBrowserFile.Open.OpenReadStream as the source

```c#
// Console
// using var theSourceStream = new FileStream("c:\\temp\\500MB.zip", FileMode.Open);

// WASM
// var theSourceStream = SomeIBrowserFile.OpenReadStream(long.MaxValue);

var streamContent = new StreamContent(theSourceStream, 4069);
httpContent.Add(streamContent, name: "file", fileName: "somefile.bin");

HttpResponseMessage response = await httpClient.PostAsync("https://localhost:7057/weatherforecast", httpContent);
response.EnsureSuccessStatusCode();

```

# Results
## Console app
1. HttpClient.PostAsync is called
2. Transfer starts
3. Server beeps to indicate start of controller code
4. Data continues to transfer until end  (e.g. 10 seconds)
5. Server beeps to indicate end of controller code
6. The end

## Blazor WASM
1. HttpClient.PoastAsync is called
2. Whole file contents are (very slowly) loaded into memory
3. Transfer starts
4. Server beeps to indicate start of controller code
5. Data continues to transfer until end  (e.g. 10 seconds)
5. Server beeps to indicate end of controller code
6. The end

### .NET Version

6.0.303

### Anything else?

# WASM
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.8" />

# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.303
 Commit:    7494fee64a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.303\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by campersau** [comment]
Related: https://github.com/dotnet/runtime/issues/36634

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

Unfortunately, `fetch` does not support HTTP request body streaming (only supported in Chrome for the time being) so the client needs to buffer. Lets use https://github.com/dotnet/runtime/issues/36634 to track it.

**Comment by davidfowl** [comment]
Fetch sucks 😢. I've been lobbying the w3c to add this for ages (for different reasons).

**Comment by mrpmorris** [comment]
I'm writing some code to bypass Blazor and upload forms straight from JS.  It seems to be working quite nicely so far.

**Comment by mrpmorris** [comment]
> Fetch sucks 😢. I've been lobbying the w3c to add this for ages (for different reasons).

Is there a good reason to use fetch instead of  `XMLHttpRequest`?

**Comment by javiercn** [comment]
@mrpmorris you can't stream the request with XMLHttpRequest either. It's not a problem with the API but a missing capability in the browser.

**Comment by davidfowl** [comment]
https://github.com/whatwg/fetch/issues/1438

**Comment by mrpmorris** [comment]
@javiercn XMLHttpRequest does stream it. I just uploaded a 1GB file without the memory usage going through the roof.

https://twitter.com/MrPeterLMorris/status/1561650669584621568?s=20&t=svki19salJp9qnOvc_So9A
