### ISSUE TITLE
Have a parameter to make NavigationManager navigate in a way similar to  JavaScript location.replace method

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/aspnetcore#43381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Is there a way to have a parameter to make `NavigationManager` navigate in a way similar to  JavaScript location.replace method?
(to go to a URL without adding the current URL to the browsing history)

### Additional context

I have a page that uses `NavigationManager` to go to a intermediary second page, then this page redirects to a third page.

When user is on third page and hits back button, it should go to the first page.

I ended up implementing a call to  JavaScript location.replace  and wondered if `NavigationManager.NavigateTo` **could have a boolean parameter to indicate ReplaceUrl**: 

// Navigates to a URL without adding the current URL to the navigation history. 
This is like `window.location.replace('https://example.com');` 
`NavigationManager.NavigateTo("https://example.com", forceLoad: false, replaceUrl:true);`

The current behaviour is like:
// Navigates to a URL adding the current URL to the navigation history. 
This is like `window.location='https://example.com';` 
`NavigationManager.NavigateTo("https://example.com", forceLoad: false, replaceUrl:false);`

**Comment by javiercn** [comment]
@TonyHenrique thanks for contacting us.

This is already available:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager.navigateto?view=aspnetcore-6.0#microsoft-aspnetcore-components-navigationmanager-navigateto(system-string-system-boolean-system-boolean)
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager.navigateto?view=aspnetcore-6.0#microsoft-aspnetcore-components-navigationmanager-navigateto(system-string-microsoft-aspnetcore-components-navigationoptions)

**Comment by TonyHenrique** [comment]
That is awesome! I did not see that. 
OK:
I updated my code to call this, instead of having to call my own javascript (and happening the reload of the whole Host).
Now it works smoothly!

Thank you!
