### ISSUE TITLE
Configure parameter binding

### ISSUE THREAD

**Issue by JTKAcies** [dotnet/aspnetcore#43386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have to create a delegate for each endpoint to bind parameter name even though they have the same code. It ends up being a lot of redundant boilerplate code just to bind a custom route name.

```csharp
Delegate petDelegate = ([FromRoute(Name = "petId")] string id) =>
{
    return id;
};

Delegate userDelegate = ([FromRoute(Name = "userId")] string id) =>
{
    return id;
};
app.MapGet("/pets/{petId}", petDelegate )
app.MapGet("/users/{userId}", userDelegate)
```

### Describe the solution you'd like

Any solution where i dont have to use attributes to bind route name to parameter name. 🙌

```csharp
Delegate userDelegate = (string id) =>
{
    return id;
};
app.MapGet("/pets/{petId=id}", petDelegate )
app.MapGet("/users/{userId=id}", userDelegate)
```

or

```csharp
Delegate userDelegate = (string id) =>
{
    return id;
};
app.MapGet("/pets/{petId}", petDelegate ).Bind("petId", "id")
app.MapGet("/users/{userId}", userDelegate).Bind("userId", "id")
```

**Comment by captainsafia** [comment]
Triage: @JTKAcies Is there a reason that you're not doing the following?

```csharp
Delegate userDelegate = (string id) =>
{
    return id;
};
app.MapGet("/pets/{id}", userDelegate )
app.MapGet("/users/{id}", userDelegate)
```

**Comment by JTKAcies** [comment]
Delegate subSubDelegate= (string parentParentId, string parentId, string id) =>
{
    return id;
};

Delegate subDelegate= (string parentId, string id) =>
{
    return id;
};

Delegate userDelegate = (string id) =>
{
    return id;
};

app.MapGet("/pets/{parentParentId}/keys/{parentId}/otherOwners/{ownerId}", subSubDelegate);
app.MapGet("/pets/{parentId}/keys/{id}", subDelegate);
app.MapGet("/users/{parentId}/keys/{id}", subDelegate);
app.MapGet("/users/{id}", userDelegate);

Most endpoints also have sub endpoints which is where it becomes a problem to use a generic id name 
since the id of pets/users/etc. changes name depending on which endpoint is used.

**Comment by davidfowl** [comment]
I feel like I'm missing something. Is the logic all the same in these methods?

**Comment by JTKAcies** [comment]
```csharp
// oneDelegate fetches one type of entity
app.MapGet("/users/{userId}", oneDelegate);
app.MapGet("/pets/{petId}", oneDelegate);
//etc.

// twoDelegate fetches another type of entity
app.MapGet("/pets/{petId}/keys/{keyId}", twoDelegate);
app.MapGet("/users/{userId}/keys/{keyId}", twoDelegate);
//etc.

// threeDelegate fetches another type of entity
app.MapGet("/pets/{petId}/keys/{keyId}/otherOwners/{ownerId}", threeDelegate);
app.MapGet("/users/{userId}/keys/{keyId}/otherOwners/{ownerId}", threeDelegate);
//etc.
```

Each delegate has unique logic and every parameter is used. However i can't reuse the same delegate since you have to use attributes to bind route name and parameter name.

**Comment by davidfowl** [comment]
Got it, so you have delegates with the same number of arguments but different names of parameters and they happen to be treated the exact same way. To help me visualize this a bit more, I'd love to understand what the logic looks like and how you are sharing it across those calls (I'm having a hard time understanding how the logic is sharable). How do you query for both a userId and a petId with the same delegate? Is it parameterized somehow?

**Comment by JTKAcies** [comment]
```csharp
object Get<T>(string userId, string keyId) where T : class
{
    return userId + " " + keyId + typeof(T).Name;
}
app.MapGet("/users/{userId}/keys/{keyId}", Get<User>)
```

Using generics but i guess it can also be done through inheritance

**Comment by davidfowl** [comment]
There's currently no way to do this with minimal APIs. The parameter name can't be overridden from the outside. In the above example, you'd need to use the same name for the key id as a workaround.

```C#

T GetById<T>(string id) where T : class
{
    return $"{id} {typeof(T).Name}";
}

app.MapGet("/users/{id}", GetById<User>);
app.MapGet("/pets/{id}", GetById<Pet>);
```

**Comment by JTKAcies** [comment]
Exactly which is why i suggest a way to bind parameter&route name through other means than attribute

```csharp
T GetById<T>(string id) where T : class
{
    return $"{id} {typeof(T).Name}";
}

app.MapGet("/users/{userId=id}", GetById<User>);
//or 
app.MapGet("/pets/{petId}", GetById<Pet>).Bind("petId", "id");
```
