### ISSUE TITLE
What is the application that I have to allow in the firewall for a gRPC hosted in an ASP Core application?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/aspnetcore#43393]
I have an gRPC ASP application and I am trying to connect from a remote computer with grpcui.

If i disable the firewall in the server computer i can connect, but if I enable it, I get the error context deadline exceeded, because the connection is blocked.

In the firewall, I have added a new incomming boud to allow the .exe file of my ASP application, and also the same rule for the outcomming bound, but still I have the same problem.

Which should be the rules in the firewall to can connect to the service from a remote computer?

Thanks.

**Comment by Tratcher** [comment]
Which server are you using, IIS, HttpSys, or Kestrel? Of the three, only Kestrel directly opens a socket in process. Most firewalls also allow you to open a port without specifying the process.

**Comment by ComptonAlvaro** [comment]
I am using Kestrel.

It is true that I could open the port, I didn't considerate this option at first, but I would like to know how to specify the process to learn and also because I think it is safer than open the port.

**Comment by sebastienros** [comment]
On a server or a physical firewall you usually don't care about the app itself, but you usually configure the port(s) and the protocol(s). You should start by that. In the case of GRPC you should open HTTP, HTTP2 and ports like 80 and 443 for instance. (it all depends on your application).

**Comment by ComptonAlvaro** [comment]
@sebastienros I have try to open the port that is used for the https connection of grpc for all protocols (instead of only for TCP) and still I don't have access.
