### ISSUE TITLE
Blazor WebAssembly App with user accounts won't run in IIS

### ISSUE THREAD

**Issue by chrisusername32** [dotnet/aspnetcore#43399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As the title says the project template can't be run in IIS and provides no feedback on how to make it do so. The issue can be consistently reproduced by simply creating a Net 5.0 Blazor Web Assembly App with Core Hosting enabled and individual user accounts. After that you can immediately publish to a folder and create an IIS website for it and you will see the issue when you browse to that web site. It will just say the site isn't working.

Note that it does work fine when run in IIS Express from visual studio. However if you configure a debug profile using IIS and run from visual studio it does not work. 

If you replace env.IsDevelopment() with true in startup.cs you can see a detailed error message related to a null reference in dependency injection. You can get the app to at least load by commenting the line app.UseIdentityServer();

At this rate I seem to either have to remove identity server entirely or try hosting the app in a windows service. (Which does seem to work). But I think the project template should work in IIS and I would prefer to deploy using IIS.

### Expected Behavior

I expected to be able to publish my app to IIS and have it run by following the steps in https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio

### Steps To Reproduce

The issue can be consistently reproduced by simply creating a Net 5.0 Blazor Web Assembly App with Core Hosting enabled and individual user accounts. After that you can immediately publish to a folder and create an IIS website for it and you will see the issue when you browse to that web site. 

These steps work just fine if the app doesn't have individual user accounts selected. Or if you do have individual user accounts selected but not core hosted.

### .NET Version

5.0

**Comment by TanayParikh** [comment]
Hello, thanks for getting in touch with us. Please note, .NET 5 is now out of support. Does this issue also reproduce in .NET 6 or .NET 7?
