### ISSUE TITLE
Set Default Page not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43401]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Set-Default-Page-not-working/10116456)._

---
[severity:I'm unable to use this version]
Visual Studio 2019 SetDefaultPage(); not working page keep reverting back to startup page hello world

---
#### Feedback Bot on 8/10/2022, 11:31 PM: 

(private comment, text removed)
#### Feedback Bot on 8/15/2022, 01:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment]
Screenshot available in the [VSTS comment.](https://dev.azure.com/devdiv/DevDiv/_search?type=workitem&lp=workitems-Project&text=DeveloperCommunityId:10116456&filters=Projects{DevDiv}&_a=search#3199657)

**Comment by adityamandaleeka** [comment]
We looked at this and it appeared not to be a product issue. Assigning to @BrennanConroy to respond on the public ticket.

**Comment by BrennanConroy** [comment]
You can use `UseFileServer` to serve different pages for different routes.
```
var fileServerOptions = new FileServerOptions()
{
    RequestPath = "/page2",
};
fileServerOptions.DefaultFilesOptions.DefaultFileNames.Add("index2.html");
app.UseFileServer(fileServerOptions);
```

https://docs.microsoft.com/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#usefileserver-for-default-documents
