### ISSUE TITLE
When I use EditForm with a model in a .NET MAUI Blazor, I get an error stating "EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these."

### ISSUE THREAD

**Issue by mokshsinghji** [dotnet/aspnetcore#43400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I have a .NET MAUI Blazor app, in which I am using an EditForm, and I have that EditForm linked with my model. However, even with the model on the EditForm, it raises the error, "EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these."

### Expected Behavior

 It should link the model to the EditForm and use it within the form.

### Steps To Reproduce

[Link for the line where the EditForm is defined](https://github.com/mokshsinghji/hangman-blazor-maui/blob/main/hangman-blazor-maui/Pages/Start.razor#L24)

Just open it in Visual Studio and run it on your machine.

### Exceptions (if any)

EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.
   at Microsoft.AspNetCore.Components.Forms.EditForm.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
NotifyUnhandledException @ blazor.webview.js:1

### .NET Version

6.0.400

### Anything else?

**** OUTPUT OF dotnet --info ****

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I am using Visual Studio 2022 v17.3.0 on Windows.

**Comment by TanayParikh** [comment]
Hey thanks for reaching out. I believe you're missing the `@` prefix when specifying the model.

Instead of:

```razor
            <EditForm Model="GuessedLetter" OnValidSubmit="HandleValidSubmit">
```

can you please try:

```razor
            <EditForm Model="@GuessedLetter" OnValidSubmit="HandleValidSubmit">
```

Please let us know if this resolves your issue. More info on model binding can be found [here](https://docs.microsoft.com/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-6.0).

**Comment by mokshsinghji** [comment]
I did try it however the same issue remains. Video is attached below.

https://user-images.githubusercontent.com/77796854/185729990-a2512e99-c482-4cc1-9392-03c45f385e13.mp4

**Comment by TanayParikh** [comment]
Hmm doesn't look like you're initializing the model anywhere:


```csharp
public GuessALetterModel GuessedLetter { get; set; }
```

needs to be:

```csharp
public GuessALetterModel GuessedLetter { get; set; } = new();
```

[here](https://github.com/mokshsinghji/hangman-blazor-maui/blob/f58e69d13348cdef8a1e12fd5bdb3f36341311bb/hangman-blazor-maui/Pages/Start.razor.cs#L51).

**Comment by mokshsinghji** [comment]
Ah, yes, it worked, don't know how I missed that 😅. Thanks anyways for the help 😃! I will be closing this issue with this comment.
