### ISSUE TITLE
Allow endpoint filter attribute 

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#43421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to add an endpoint filter via an attribute, for example:

``` c#
var envGroup = app.MapGroup("/env-test");
envGroup.Map("/dev", () => "env-test")
    .AddEndpointFilter(new EnvironmentFilter(Environments.Development));
envGroup.Map("/prod", () => "env-test")
    .AddEndpointFilter(new EnvironmentFilter(Environments.Production));
envGroup.Map("/stage", [EnvironmentFilter("Staging")]() => "env-test");
```

The `EnvironmentFilter` is an attribute that implements the `IEndpointFilter`.

It would only work with `AddEndpointFilter`, the attribute is not working now, not sure if it's acceptable to allow attribute

### Describe the solution you'd like

Maybe we could get the attribute defined, if it's an endpoint filter then register it.

### Additional context

For the endpoint filter order, maybe we could place it after the `AddEndpointFIlter`

**Comment by davidfowl** [comment]
Why?

**Comment by WeihanLi** [comment]
> Why?

Just likes the `[Authorize]`, it would keep the same behavior likes the MVC filter attribute

**Comment by davidfowl** [comment]
Because MVC is declarative, there’s no other option other than using an attribute. We have no plans to enable filters via attributes with minimal APIs, at least not in .NET 7

**Comment by WeihanLi** [comment]
@davidfowl  get it thanks
