### ISSUE TITLE
I am getting a System.NullReferenceError when I am using a .NET MAUI Blazor app

### ISSUE THREAD

**Issue by mokshsinghji** [dotnet/aspnetcore#43448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, this is a similar issue to #38945, however that issue did not fully answer the query and the solution doesn't apply to .NET MAUI Blazor, as it does not contain the _Host.cshtml file. Anyways, I have an app, in which the index page has two input fields and a button. When I try to run it now, it gives me a System.NullReferenceError in the webview:

blazor.webview.js:1 
        
       Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)

This stack trace is not involving any of my code, and therefore, I do not know from which point the error is being raised.

### Expected Behavior

I expect the code to run and to show a title, two inputs and a button.

### Steps To Reproduce

https://github.com/mokshsinghji/hangman-blazor-maui

This is the link to the project ⬆️ 

### Exceptions (if any)

blazor.webview.js:1 
        
       Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)

### .NET Version

6.0.400

### Anything else?

The output of dotnet --info:

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

I am using Visual Studio 2022 v17.3.0

**Comment by javiercn** [comment]
This was fixed in .NET 7.0. https://github.com/dotnet/aspnetcore/pull/39833
