### ISSUE TITLE
[Blazor] how to disable the [parameter] feature inherit from component?

### ISSUE THREAD

**Issue by capdiem** [dotnet/aspnetcore#43486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

``` c#
public class A : ComponentBase {
    [Parameter]
    public List<T> Items { get; set; }
}

public class B : A {
    // disable the parameter feature
    public List<T> Items { get; set; }
}
```

I have tried this:

```c#
public class A : ComponentBase {
    [Parameter]
    public virtual List<T> Items { get; set; }
}

public class B : A {
    public override List<T> Items { get; set; }
}
```

but still can access the Items paramter:
``` razor
<B Items="" />
```

### .NET Version

6.0.400

**Comment by javiercn** [comment]
@capdiem thanks for contacting us.

There is no way to do this other than not extending ComponentBase or overriding SetParametersAsync and not calling base, which will turn off the feature for all properties
