### ISSUE TITLE
Publishing a Standalone to linux server with new base path, unable to make it work

### ISSUE THREAD

**Issue by DanielViberg** [dotnet/aspnetcore#43487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
I'm trying to publish my standalone blazor wasm to a linux server. The app should run under a new base path, lets call it "app1". I've added `    <StaticWebAssetBasePath>app1</StaticWebAssetBasePath>`
and `<base href="/app1/" />`
with the following nginx config:
`
include mime.types;
    types {
        application/wasm wasm;
    }

server {
        server_name <name>;

        location /app1 {
            root /var/www/html/app1/wwwroot/;
            try_files $uri $uri/ /index.html =404;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<name>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<name>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
`

Running this locally with dotnet run --pathbase=/app1 works as expected. But running it from the server using nginx i get a bunch of:

`The stylesheet https://<name>/app1/css/blazor/blazor.css was not loaded because its MIME type, “text/html”, is not “text/css”.`

My question is, how am i supposed to configure nginx to route to the standalone app?

Thanks in advance for any input!

### Expected Behavior

Work equally as to when run locally using kestrel. 

### Steps To Reproduce

Will upload repo if necessary.

### .NET Version

6.0.108

**Comment by DanielViberg** [comment]
Never mind, figured it out. 
For other with the same issue. Look at the deployment fine structure. In nginx, set location / and root to your wwwroot folder where you have the output folders for each published app :)

**Comment by gtejeda** [comment]
Greetings @DanielViberg I have a very similar code to yours, but i still can't get it to work. 
would you be so kind as to post your new nginx working code please?

thanks man, would really help me out.
Geo

**Comment by DanielViberg** [comment]
When you publish (dotnet publish -c Release) your wasm >app< with a basepath it will land under bin/Release/net6.0/publish/wwwroot/>app<. This wwwroot folder is your nginx root: 
`        root /var/www/html/itrera/wwwroot;
        try_files $uri $uri/ /index.html =404;
`
My >app< folder is in wwwroot on my server. 
This will load the wasm app, but I've yet to solve opening the app with other directories. For example uri/>app</login results in 404. So my config might be wrong/lacking :)

**Comment by DanielViberg** [comment]
An update on this. Using alias instead of root seems to work better: 
`location /platform 
    {
        alias /var/www/html/wwwroot/>app<;
        try_files $uri $uri/ /index.html =404;
    }
`
