### ISSUE TITLE
Change argument null exceptions to use ArgumentNullException.ThrowIfNull

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#43482]
ASP.NET Core checks and throws for null all over the place. e.g.

https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/HttpClientFactory/Polly/src/DependencyInjection/PollyHttpClientBuilderExtensions.cs#L33-L41

`ArgumentNullException.ThrowIfNull` is used in modern code, but we should go through existing code to use `ArgumentNullException.ThrowIfNull`.

Pros: less code, small potential perf gains from inlining (exception moved into another method), consistency.

**Comment by JamesNK** [comment]
@stephentoub You're the author of many of the PRs in dotnet/runtime that switch code to use ArgumentNullException.ThrowIfNull. Is there a way to automate this, or did you update it manually?

**Comment by stephentoub** [comment]
When `!!` was a thing, there was an auto-fixer in VS that would use it.  I employed that to roll out `!!` throughout dotnet/runtime.  Then `!!` went away, and I primarily used regexes and other simple console-based tools to rewrite those `!!` into ThrowIfNull calls.

**Comment by JamesNK** [comment]
@stephentoub Do you know what happened to the fixer when `!!` was removed?

A fixer that converts from `if (x == null) throw new ArgumentNullException(nameof(x))` to `ArgumentNullException.ThrowIfNull` seems like it would still be valuable.

**Comment by stephentoub** [comment]
> A fixer that converts from if (x == null) throw new ArgumentNullException(nameof(x)) to ArgumentNullException.ThrowIfNull seems like it would still be valuable.

It would be. https://github.com/dotnet/runtime/issues/68326 tracks it. @RikkiGibson wrote the initial analyzer/fixer and I believe was looking into revamping it for ThrowIfNull.

**Comment by JamesNK** [comment]
Ok!

FYI @rafikiassumani-msft @mkArtakMSFT @adityamandaleeka This has the area-runtime label, but changes apply in web frameworks and blazor areas as well.

Could delay doing anything here until an updated analyzer+fixer is ready and then change all null tests automatically.

**Comment by adityamandaleeka** [comment]
You mean I wrote a sweet regex for nothing? 😄

**Comment by adityamandaleeka** [comment]
src/Servers was done in https://github.com/dotnet/aspnetcore/pull/43502

**Comment by danmoseley** [comment]
We can use this analyzer https://github.com/dotnet/roslyn-analyzers/pull/6293
