### ISSUE TITLE
Blazor Server - NotAuthorized content is shown before Authorization is finished

### ISSUE THREAD

**Issue by human705** [dotnet/aspnetcore#43492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When loading Blazor Server with an authenticated user, the contents of NotAuthorized is briefly shown before the content switches over to Authorized. I've tested that with both <AuthorizeView> and @attribute [Authorize].

### Expected Behavior

The contents of Authorizing should be shown before the authentication of the user can be verified. 

### Steps To Reproduce

I created a [small project ](https://github.com/human705/BlazorServerIssues) with 2 test files, test and test2. After authenticating, credentials are in MockUserRepository.cs, the user will be redirected to /test. This page is using the "@attribute [Authorize] to secure the content. "If you refresh the page, you can briefly see the contents of the App.razor displayed before the page is rendered. 

Click the menu option for test2 to see the issue when using "<AuthorizeView>" . If you refresh the page after authenticating, you will again see the contents of "<NotAuthorized>" before the page shows the "<Authorized>" content.

### Exceptions (if any)

None at this time.

### .NET Version

C:\Users\peter>dotnet --version 6.0.400

**Comment by human705** [comment]
It appears that some info is missing from the test2 menu steps to reproduce the issue. In this case, i'm using AuthorizeView and the contents of NotAuthorized are briefly shown when a page is reloaded before the contents of Authorized are shown.

**Comment by javiercn** [comment]
@human705 thanks for contacting us.

That's happening because you are prerendering and your custom AuthenticationStateProvider does not handle it correctly.
https://github.com/human705/BlazorServerIssues/blob/master/BlazorServerAuthIssue/Pages/_Host.cshtml#L8
