### ISSUE TITLE
[Feature] Blazor QuickGrid add the ability to be able to export all data or filtered data to a pdf , csv, html

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#43499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In Many of our front-line mvc apps  in blazor quick grid would be awesome to have the ability to export the data contained within the grid to a csv or pdf.  The issue is most grids don't do filtered data. So if you search for DB1234 and 25 records are come back you have pagination set to 10 I would expect a pdf or csv with all entries that match DB1234

### Describe the solution you'd like

I would expect options such as the following.

You will see in the below code a new field lets call it 

bool IsExportable;

This will detimine if the column data should appear in the exported csv or pdf file

`    @inject DataSource Data

    <div class="grid">
     <QuickGrid Items="@Data.People" ExportOptions"pdf,csv,xml">
        <PropertyColumn Property="@(c => c.PersonId)" Sortable="true" IsExportable="true" />
        <PropertyColumn Property="@(c => c.FirstName)" Sortable="true"  IsExportable="true"/>
        <PropertyColumn Property="@(c => c.LastName)" Sortable="true" IsExportable="false"/>

        
        <PropertyColumn Property="@(c => c.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />

        
        <PropertyColumn Title="Age in years" Property="@(c => ComputeAge(c.BirthDate))" 
       Sortable="true" Align="Align.Right" />

      <ExportButton Text="PDF" Image="pdf.png" class="css-icon-pdf">
     <ExportButton Text="CSV" Image="csv.png" class="css-icon-csv">
    <ExportButton Text="XML" Image="xml.png" class="css-icon-xml">

    </QuickGrid>
    </div>`

You will see above two buttons that can be styled any way the author so likes with additional icons or an image source.

Once the pdf or csv buttons it will check what filters our applied to the data and ensure that all exported data is accounted for in the pdf and csv that matches any and all applied filters over the span of pagination

Possible add a handler to allow a custom save event in case they need to do additional formatting on the outputted file.

### Additional context

NONE

**Comment by TanayParikh** [comment]
Please note, quick grid is not an official part of the Blazor framework. It has currently been released under ASPNET Labs as an experimental feature. 

cc/ @danroth27

**Comment by javiercn** [comment]
@davidbuckleyni thanks for contacting us.

We do not have plans to extend the grid with functionality such as the one you described. It is up to you to extend it for your needs or find a community package or third-party library that offers you this functionality.

Our goal with the component grid is to demonstrate how to author a high performant grid implementation within Blazor that can support common functionality, but we do not have plans to extend it to include more advanced features like the one you described for the time being.

**Comment by davidbuckleyni** [comment]
@javiercn is their any examples of how I could hook into the grid to do a export libary nuget possibly ??
