### ISSUE TITLE
FileStreamResult results in sensitive data being logged

### ISSUE THREAD

**Issue by lorddev** [dotnet/aspnetcore#43495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

```csharp
        [LoggerMessage(2, LogLevel.Information, "Executing {FileResultType}, sending file with download name '{FileDownloadName}' ...", EventName = "ExecutingFileResultWithNoFileName", SkipEnabledCheck = true)]
        private static partial void ExecutingFileResultWithNoFileName(ILogger logger, string fileResultType, string fileDownloadName);
```
This log ends up in our log sink with a filename that could potentially be user-entered data.

### Describe the solution you'd like

Perhaps the log could be set to debug?

**Comment by lorddev** [comment]
It's also curious that it's called "FileResultWithNoFileName" when it's actually logging the filename.

**Comment by halter73** [comment]
> This log ends up in our log sink with a filename that could potentially be user-entered data.

Then how are you serving this user-entered data? Does the filename end up showing up in the path? What filename is sensitive? If it is sensitive, can you rename the file before serving so the sensitive name doesn't get logged? @blowdart what are your thoughts?

**Comment by blowdart** [comment]
What a weird function

So it is [this](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/FileContentResultExecutor.cs) right?

And `fileDownloadName` comes from the name property of the FileResult that's passed into `ExecutingFileResult(ILogger logger, FileResult fileResult)`?

How is FileResult getting a name from user-controlled data? That's not an MVC permission as far as I can see, it's an app decision. And even if it was user-controlled data, why is that a concern for a log sink, unless you're concerned about PII here?

**Comment by lorddev** [comment]
Issue is PII. Consider a legal document where the file is called "So-and-so v. You-know-who.pdf". Someone looking at the logs might be able to infer certain things from the file name. As far as renaming, re @halter73 when an authorized user downloads the file, we want them to be able to view the file with the original name on their file system without having to rename it manually.

**Comment by lorddev** [comment]
(We will workaround by leaving out the `fileName` param since it's optional; the front-end will use the response from a separate API call to set the file name when it saves the blob.)

**Comment by blowdart** [comment]
In general, while we try to sanitize logs for PII there are always going to be things that is PII for one application, that another application considers vital information for logs. There's a balance here that's a tightrope for us to walk.

The securing of logs, and servers, and everything else falls to the application/infrastructure admin. Depending on your logging system you may be able to filter/delete during ingest into whatever backend it eventually ends up in.

**Comment by lorddev** [comment]
Got it, thank you Barry.
