### ISSUE TITLE
[Question] Wrapping Blazor Input components in a custom component

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#43509]
I could not find the forum section any more to ask a question, so I'm doing it with this blank issue.

I want to remove many duplicated code from my forms within a Blazor server app. For example: every Input consists of a label, a few divs and a validation message. Multiple this code by n properties and your file gets really large pretty quickly. So I thought to create a custom component which can be used to reduce the lines to just one line of code.

Also I don't want to create a custom component which inherits from either InputText or InputBase. I just want to use the built in components and just wrap some HTML around it.

This is my current approach of it:
```
<div class="@ColSize">
    <label>@Label</label>
    <InputText @bind-Value="Value" class="form-control" />
    <ValidationMessage For="() => Value" />
</div>

@code {
    public string ColSize { get; set; } = "col-md-12";
    [Parameter] public string Label { get; set; } = string.Empty;
    [Parameter] public string? Value { get; set; }
    [Parameter] public EventCallback<string?> ValueChanged { get; set; }
}
```

In my Index.razor I have this small dmeo form:
```
<EditForm Model="Input" OnValidSubmit="Submit">
    <DataAnnotationsValidator />
    <ValidationSummary />
    <MyInput @bind-Value="Input.Name" />
    
    <button type="submit" class="d-block mt-3">Save</button>
</EditForm>

@code {
    public MyModel Input { get; set; } = new();
    private void Submit()
    {

    }
    public class MyModel
    {
        [MinLength(10)]
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }
}
```

~~The binding works fine~~ EDIT: The binding does not work either.. Also the validation works. However, the `<ValidationMessage />` within my custom component does not work. I only get the validation messages through the `ValidationSummary` component. 

Is there any easy way to achive this? This would reduce our code by a few hundreds of lines.

I'm pinging you @danroth27 because I saw the latest ASP.NET Standup and saw that you did a binding example with a custom component for a basic input html. Perhaps you can help me out with it.

Thanks!

**Comment by javiercn** [comment]
@MarvinKlein1508 your binding implementation is not correct.

Check https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-6.0#bind-across-more-than-two-components for details on how to do this.

In general, you should not modify component parameter values as that produces in issues when diffing the component to determine if it needs to re-render.
