### ISSUE TITLE
Add HttpConnectAttribute

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#43501]
## Background and Motivation

We recently added WebSockets over HTTP/2 support to Kestrel. By default this lights up automatically if your app supports HTTP/2 and you use the browser. One potential problem is that using WebSockets with controllers could potentially stop working because WebSockets over HTTP/2 now uses a CONNECT request instead of a GET request.

[Our docs](https://docs.microsoft.com/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0#accept-websocket-requests-1) even show using WebSockets from a controller and are now broken in this specific scenario.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Mvc;

+ public class HttpConnectAttribute : HttpMethodAttribute
+ {
+    public HttpConnectAttribute();

+    public HttpConnectAttribute([StringSyntax("Route")] string template);
+ }
```

## Usage Examples

```csharp
public class WebSocketController : ControllerBase
{
    [HttpGet("/ws")]
    [HttpConnect("/ws")]
    public async Task Get()
    {
        if (HttpContext.WebSockets.IsWebSocketRequest)
        {
            using var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
            await Echo(webSocket);
        }
        else
        {
            HttpContext.Response.StatusCode = StatusCodes.Status400BadRequest;
        }
    }
}
```

## Alternative Designs

```csharp
public class WebSocketController : ControllerBase
{
    [WebSocket("/ws")]
    public async Task Get()
    {
        using var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
        await Echo(webSocket);
    }
}
```

Don't add a new API and add docs to show using a custom `HttpMethodAttribute`.

**Comment by davidfowl** [comment]
Oh very interesting. We should do this for rc2.

**Comment by captainsafia** [comment]
Triage: at minimum, we'll try to document the workaround. We'll also do the additive API change for RC2.

Note: we'll also need to file a breaking change announcement with this.

**Comment by halter73** [comment]
I don't see this as critical for .NET 7 considering that it is quite easy to work around this issue by accepting all HTTP methods and checking `HttpContext.Request.Method` in the action. But if we do this, I think we also need to make sure we've finished the last checkbox on https://github.com/dotnet/aspnetcore/issues/42101#issuecomment-1161982675. Thankfully, it looks like that's also slated for rc2. @Tratcher

**Comment by captainsafia** [comment]
> I don't see this as critical for .NET 7 considering that it is quite easy to work around this issue by accepting all HTTP methods and checking HttpContext.Request.Method in the action

During triage, we had discussed that we would need to document this at a minimum. And if we're going to document the issue and provide a workaround, we might as well make the workaround something a little more bullet-proof/accessible.

It's fair to say this isn't critical but I wanted to provide some context into why this was the case.

> But if we do this, I think we also need to make sure we've finished the last checkbox on https://github.com/dotnet/aspnetcore/issues/42101#issuecomment-1161982675.

How is that item related to this?

**Comment by BrennanConroy** [comment]
Documentation is already occurring in https://github.com/dotnet/AspNetCore.Docs/pull/26768. We also need to make a breaking change announcement regardless of the outcome of this issue.

> How is that item related to this?

I don't think it changes anything. Maybe just the priority for that item is higher in Stephen's mind?

**Comment by Tratcher** [comment]
That item is also H2 WebSocket related, but not directly connected to this ask. He just wants to make sure we tie up loose ends before making the feature broadly available.

**Comment by halter73** [comment]
API review notes:

1. Can we use `[Route("/ws")]` today to accept all HTTP verbs and rely on the IsWebSocket check to reject other verbs? Yes.
2. Is the alternative `[WebSocket]` attribute easier? Yes.
3. Would we want both `[WebSocket]` and `[HttpConnect]`? Probably not.

API rejected because of the `[Route("/ws")]` workaround. Let's update the docs though.

**Comment by davidfowl** [comment]
What is this websocket attribute? An MVC filter?

**Comment by Tratcher** [comment]
> What is this websocket attribute? An MVC filter?

It would either check both GET and CONNECT, or it would check HttpContext.WebSockets.IsWebSocketRequest. Implementation TBD. But it's moot since Route works.

**Comment by BrennanConroy** [comment]
Docs updated in https://github.com/dotnet/AspNetCore.Docs/pull/27565
