### ISSUE TITLE
jwt authentication not working on .net 6

### ISSUE THREAD

**Issue by muchirajunior** [dotnet/aspnetcore#43504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i tried adding jwt authentication on ASP.NET 6 and the code is not even resolving the namespace
`using Microsoft.AspNetCore.Authentication.JwtBearer;`
on .csproj file i added 
`<PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.2"/>`
and on the project.cs
`builder. Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(option => {
                option.TokenValidationParameters = new TokenValidationParameters(){
                    ValidateIssuer = false, //set it to false if you want often change dormain names    
                    ValidateAudience = true,    
                    ValidateLifetime = true,    
                    ValidateIssuerSigningKey = true,    
                    ValidIssuer = Configuration["Jwt:validIssuer"],    
                    ValidAudience = Configuration["Jwt:ValidAudience"],    
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Jwt:secretKey"]))
                };
            }); 
`

**Comment by davidfowl** [comment]
Did you add a reference to this package https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/?

**Comment by muchirajunior** [comment]
no i didn't add that was it required since on earlier version of dotnet it
was not required

**Comment by muchirajunior** [comment]
I added the ` <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.3"/>` to my project file and it worked thank you
