### ISSUE TITLE
Change disposed exceptions to use ObjectDisposedException.ThrowIf

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#43503]
Similar to https://github.com/dotnet/aspnetcore/issues/43482

APIs are available to simplify throwing `ObjectDisposedException`:
https://github.com/dotnet/runtime/blob/a54a823ece1094dd05b7380614bd43566834a8f9/src/libraries/System.Private.CoreLib/src/System/ObjectDisposedException.cs#L49-L73

Consider updating code to use `ObjectDisposedException.ThrowIf`.

**Comment by danmoseley** [comment]
We can use this analyzer https://github.com/dotnet/roslyn-analyzers/pull/6293
