### ISSUE TITLE
Blazor WASM web app doesn't work properly in Firefox

### ISSUE THREAD

**Issue by Phoenixkaze** [dotnet/aspnetcore#43516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Building a simple Blazor WASM web app. I added a css lib in wwwroot's css folder and wanted to see how it looks like.

Then I found the style had not been applied on the elements. Some errors appeared in the console.

![image](https://user-images.githubusercontent.com/28686529/186446765-43d45aa5-f5cd-43c0-9770-cebccd464038.png)
---

Same code works well in Edge:

---
![image](https://user-images.githubusercontent.com/28686529/186447082-21215308-7f70-4252-859f-5cdbfc0feb16.png)

### .NET Version

6.0.400

### Anything else?

Firefox Developer Edition Version 105.0b2

**Comment by javiercn** [comment]
@Phoenixkaze thanks for contacting us.

It seems that Firefox is blocking some script loading in localhost, so hot reload is not working.

**Comment by Phoenixkaze** [comment]
It seems related to my proxy settings which somehow made Firefox failed to do that. I just closed the proxy client and it works.
