### ISSUE TITLE
CORS policy per request

### ISSUE THREAD

**Issue by krispenner** [dotnet/aspnetcore#43526]
I am trying to set the allowed origins to be based on the tenant of the request. Since the `CorsPolicy` does not have scoped access to the `HttpContext`, I'm looking at injecting my own custom [CorsPolicyProvider](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/CORS/src/Infrastructure/DefaultCorsPolicyProvider.cs) which is given the `HttpContext` and can then return a custom built `CorsPolicy` which includes only the tenant's allowed origins.

However, I noticed that the `CorsService` accesses the defined policies directly from the `CorsOptions` and bypasses the `ICorsPolicyProvider`. I feel this may be wrong and that the `CorsService` should have a `ICorsPolicyProvider` injected into it instead of the `CorsOptions` and then the Evaluate methods should become async and retrieve the policy from the provider.

https://github.com/dotnet/aspnetcore/blob/0eaabe0fe5d714753f58ba84c9880403977a7f82/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L58

1. Does injecting my own `ICorsPolicyProvider` make sense for what I'm trying to achieve?
2. Should the `CorsService` not instead use the `ICorsPolicyProvider` for access policies? Otherwise I may need to inject my own `ICorsService` implementation as well.

Thanks

**Comment by BrennanConroy** [comment]
The CORS middleware does use the provided `ICorsPolicyProvider` https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L176
And it calls the other overload of `EvaluatePolicy` that uses the `CorsPolicy` instead of options.
https://github.com/dotnet/aspnetcore/blob/0eaabe0fe5d714753f58ba84c9880403977a7f82/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L68

**Comment by krispenner** [comment]
Thanks @BrennanConroy, do you happen to know what calls the Evaluate() method on the `ICorsService` that accesses the options internally. It still concerns me as I don't know what may be calling that elsewhere and would be ignoring my `ICorsPolicyProvider` if that was to happen. Obviously the method was added for a reason, and why would it not just use the registered `ICorsPolicyProvider` instead?

**Comment by BrennanConroy** [comment]
That would happen if you called `UseCors` with a specific policy
https://github.com/dotnet/aspnetcore/blob/0eaabe0fe5d714753f58ba84c9880403977a7f82/src/Middleware/CORS/src/Infrastructure/CorsMiddlewareExtensions.cs#L50-L52

**Comment by krispenner** [comment]
Well in that case it seems to call
https://github.com/dotnet/aspnetcore/blob/0eaabe0fe5d714753f58ba84c9880403977a7f82/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L68
with the single configured policy, but I'm referring to
https://github.com/dotnet/aspnetcore/blob/0eaabe0fe5d714753f58ba84c9880403977a7f82/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L51
which takes a policyName and looks up the policy in the _options object, when maybe it should be using the CorsPolicyProvider.

From my limited quick search, I don't see this method being called internally.
https://github.com/dotnet/aspnetcore/search?q=EvaluatePolicy%28

**Comment by BrennanConroy** [comment]
> From my limited quick search, I don't see this method being called internally.
> https://github.com/dotnet/aspnetcore/search?q=EvaluatePolicy%28

Great, so the middleware doesn't call that function which means you won't have any issues with your `ICorsPolicyProvider` not being called.

**Comment by krispenner** [comment]
Right, but I don't know how the CORS system works, does anything other than middleware access the policies which may call the wrong method then?

I'd really like to know why that method was added and maybe it should be marked it as deprecated if no longer needed, or if needed, it could be converted it to async and call the `ICorsPolicyProvider` from within it instead? But maybe that is asking too much.

I will create my tenant/request based `ICorsPolicyProvider` and see how I go. Thanks for your help.
