### ISSUE TITLE
`launchUrl` and `launchBrowser` settings not respected

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#43531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Invoking `dotnet run` on an application with `launchBrowser` set to true and the `launchUrl` provided doesn't automatically open the desired route.

### Expected Behavior

Invoking `dotnet run` on an application with the following launch profile will open the browser to the `/swagger` path on the app.

```json
{
  "commandName": "Project",
  "dotnetRunMessages": true,
  "launchBrowser": true,
  "launchUrl": "swagger",
  "applicationUrl": "http://localhost:5276",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
  }
}
```

### .NET Version

7.0.100-rc.1.22422.8

### Anything else?

Default browser: Chrome

**Comment by feiyun0112** [comment]
please try to use `dotnet watch run`

more details in https://github.com/dotnet/sdk/issues/9038

**Comment by captainsafia** [comment]
Closing in favor of referenced issue.
