### ISSUE TITLE
When I install the ASP Core as windows service I can't connect to my gRPC service

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/aspnetcore#43547]
Well, I have a gRPC service that is hosted in a ASP Core .NET 6 application.

When I debug the ASP project or run the .exe directly, I can connect with the gRPC service, but if I install the ASP Core as a windows service, i get a error: connection refused. SocketException: connection refused. DebugException: System.Net.Http.HttpRequest exception.

This error is when I have disabled the firewall in the server, because if I have enabled it, I get a timeout error, that it is the expected result because I don't have created the rules in the firewall.

I am using certificates, but I am not sure if this is the possible cause, because if I run the application when it is not a service, it works as expected.

The code of my ASP Core application is this:

```c#
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.WindowsServices;
using System.IO.Compression;
using System.Security.Cryptography.X509Certificates;

using GestorOrdenadores.Service.Server.Grpc;


WebApplicationOptions options = new WebApplicationOptions
{
    Args = args,
    ContentRootPath = WindowsServiceHelpers.IsWindowsService() ? AppContext.BaseDirectory : default
};

WebApplicationBuilder builder = WebApplication.CreateBuilder(options);



builder.WebHost.ConfigureKestrel((context, options) =>
{
    string miStrCertificado = File.ReadAllText("certificados/server.crt");
    string miStrKey = File.ReadAllText("certificados/server.key");
    X509Certificate2 miCertficadoX509 = X509Certificate2.CreateFromPem(miStrCertificado, miStrKey);
    X509Certificate2 miCertificado2 = new X509Certificate2(miCertficadoX509.Export(X509ContentType.Pkcs12));

    miCertficadoX509.Dispose();

    options.ListenAnyIP(5001, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
        listenOptions.UseHttps(miCertificado2);
    });
});

builder.Services.AddGrpc();

builder.Host.UseWindowsService();





WebApplication app = builder.Build();

app.MapGrpcService<GestorOrdenadoresService>();

app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");





await app.RunAsync();
```

Thanks.

**Comment by adityamandaleeka** [comment]
@ComptonAlvaro Can you enable logging for the server and see if anything appears there?

**Comment by ComptonAlvaro** [comment]
@ComptonAlvaro Well, really it is what I was trying, to enalbe logging to can write in a text file to see what is happening, but I don't know how to write to a file the log of ASP.

I can't see the log of ASP when it is running as the same way than when I run it directly.

When I have the log, I will share.

**Comment by davidfowl** [comment]
Check the event log.

**Comment by ComptonAlvaro** [comment]
Then system event log show this:

```
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-08-28T11:43:30.1456718Z" /> 
  <EventRecordID>87817</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="1272" ThreadID="22624" /> 
  <Channel>System</Channel> 
  <Computer>GTS-AGarcia</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">Gestor de ordenadores</Data> 
  <Data Name="param2">2</Data> 
  <Binary>47006500730074006F0072004F007200640065006E00610064006F007200650073000000</Binary> 
  </EventData>
  </Event>
```

**Comment by davidfowl** [comment]
Are those the only logs? That doesn't look like the right category. If there were any errors it would show up under application e.g.:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/95136/187087905-d3fbed52-6d71-45c6-9309-4c75a072d737.png">

**Comment by ComptonAlvaro** [comment]
@davidfowl In the application section I don't have any event related with the application. Just I have a system event with the error 1067.

I have try to write in a text file in the first line of program.cs, and it doesn't start, so I guess it is a problem about the way I create the service, the code, perhaps UseWindwService() or perhaps that I have to implement something related with some interface of services.

**Comment by ComptonAlvaro** [comment]
I oculd solve it if in the first line of my pogram.cs I set the CurrentDirectory of the enviroment:

Environment.CurrentDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

It is because the user that run the service, System, doesn't have permissions to write in c:\windows\system32, that is the default directory of the services.

**Comment by adityamandaleeka** [comment]
@ComptonAlvaro Glad you were able to figure this out.

We've improved this behavior in 7, and there's a comment about this in the docs here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio#current-directory-and-content-root-1

**Comment by wtgodbe** [comment]
Closing this as resolved, @ComptonAlvaro feel free to re-open if you have further issues here.
