### ISSUE TITLE
Hot reload no longer works in dotnet CLI

### ISSUE THREAD

**Issue by mvandoff** [dotnet/aspnetcore#43540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running `dotnet watch --verbose`  the first messaged returned is:

`dotnet watch ⌚ Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.`

As you can see, I am not using any non-default commands. 

My launchSettings.json file:

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:54659/",
      "sslPort": 44373
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "ProjectService": {
      "commandName": "Project",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:44373",
      "hotReloadProfile": "aspnetcore"
    }
  }
}
```

### Expected Behavior

Dotnet is launched with hot reload enabled

### Steps To Reproduce

1. Copy the launchSettings.json file above
2. Enter  `dotnet watch`  from the CLI

### .NET Version

6.0.400

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@mvandoff thanks for contacting us.

Could you compare your `launchSettings.json` file with the launchSettings.json from a new project to see if there are any significant differences?

If not, here are some things to try and some info to collect to help us troubleshoot the issue

* Use the `--verbose` flag watch provides and capture the output.
* Turn `Microsoft.AspNetCore.Watch.BrowserRefresh` logs to Debug level on the app in appsettings.development.json. (If Blazor standalone, you might need to do it on the dev-server settings)
* Check for errors on the browser console, like files files failing to load.

**Comment by mvandoff** [comment]
@javiercn 

Here is the default `launchSettings.json` when I run `dotnet new webapp`

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:22618",
      "sslPort": 44304
    }
  },
  "profiles": {
    "test": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:7194;http://localhost:5157",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

The differences are: 
- Different `applicationUrl`
- `hotReloadProfile` is missing (I never used to have to use this, I added it for debugging)
- `launchBrowser` set to true
- `dotnetRunMessages`

My `dotnet watch --verbose` output:
```
dotnet watch ⌚ Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.
dotnet watch ⌚ Evaluating dotnet-watch file set.
dotnet watch ⌚ Running MSBuild target 'GenerateWatchList' on 'C:\...\ProjectService\ProjectService\ProjectService.csproj'
dotnet watch 🚀 Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 10772
dotnet watch ⌚ Process id 10772 ran for 622ms
dotnet watch ⌚ Watching 588 file(s) for changes
dotnet watch ⌚ Watch command can be configured to use --no-restore.
dotnet watch ⌚ No restore arguments: run --no-restore
dotnet watch ⌚ launchSettings does not allow launching browsers.
dotnet watch ⌚ Configuring the app to use browser-refresh middleware.
dotnet watch ⌚ Refresh server running at wss://localhost:52656,ws://localhost:52657.
dotnet watch 🚀 Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 19772
dotnet watch ⌚ Running dotnet with the following arguments: run
dotnet watch 🚀 Started
```

I did update that log setting and didn't notice anything in the browser or server logs on launch or when making an edit to the file. Here's what the log shows when I make a change to a file:

```
dotnet watch ⌚ Killing process 2376
dotnet watch ⌚ Process id 2376 ran for 170020ms
dotnet watch ⌚ Exited
dotnet watch ⌚ File changed: C:\...
dotnet watch ⌚ Modifying command to use --no-restore
dotnet watch 🚀 Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 16156
dotnet watch ⌚ Running dotnet with the following arguments: run --no-restore
dotnet watch 🚀 Started
```

**Comment by javiercn** [comment]
@mvandoff does the problem reproduce if you update launchSettings.json to more clearly align with the default version? The applicationUrl does not matter, but the `"hotReloadProfile": "aspnetcore"` might be interfering.

Also, are you able to get hot reload to work with an out of the box project?

**Comment by mvandoff** [comment]
@javiercn I tried to run the project with that default launchSettings.json and it didn't work. Tried with and without the `"hotReloadProfile"` setting and no luck. 

Yes, when launching the out of the box `dotnet new webapp` project I get the success message when running `dotnet watch`:

```
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
```

**Comment by mvandoff** [comment]
Aha, so the TargetFramework for our app is net5.0. When I change it to 6.0 I get the Hot reload enabled message.

**Comment by javiercn** [comment]
@mvandoff thanks for the additional details.

I did not realize you had a 5.0 app. Unfortunately, .NET 5.0 is out of support so as per our support policy we ask that you update to .NET 6.0 as a first step.
