### ISSUE TITLE
Authorize attribute with AllowAnonymous attribute always anonymous.

### ISSUE THREAD

**Issue by johnwc** [dotnet/aspnetcore#43550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having a method as such, the User property of the controller is never assigned the user from the bearer token from the header when `AllowAnonymous` is added. Docs states that if you add `AllowAnonymous` along with `Authorize`, it will allow anonymous when no authentication is present, and authenticate and set User property of controller when authentication is present

```CSharp
[AllowAnonymous]
[Authorize]
[HttpGet("test1", Name = "Test1")]
public async Task<ActionResult<TestResponse>> Test()
{
     this.User <-- always no claims
     ...
}
```

### Expected Behavior

If auth header is present it should verify it and set User property of controller.

### Steps To Reproduce

StartUp
```CSharp
      ...
      builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
          .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));
      ...
      var app = builder.Build();
      if (app.Environment.IsProduction())
        app.UsePathBase("/api/v2");

      if (app.Environment.IsDevelopment())
      {
        app.UseServerTiming();
        app.UseSwagger();
        app.UseSwaggerUI();
      }

      app.UseForwardedHeaders(new ForwardedHeadersOptions
      {
        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost
      });

      app.UseHttpsRedirection();
      app.UseRouting();
      app.UseCors();
      app.UseAuthentication();
      app.UseAuthorization();
      app.MapControllers();
      app.Run();

```
Controller
```CSharp
  [Route("account")]
  [ApiController]
  [Authorize]
  [Produces("application/json")]
  public class AccountController : BaseController
  {
  
    [AllowAnonymous]
    [Authorize] <-- tried adding it here as well in case it needed it here
    [HttpGet("test1", Name = "Test1")]
    public async Task<ActionResult<TestResponse>> Test()
    {
      this.User <-- always no claims
      ...
    }
  }
```

### .NET Version

6.0

**Comment by davidfowl** [comment]
Where is the rest of your code? Where is the middleware pipeline and setup?

**Comment by johnwc** [comment]
Using the out of the box standard Microsoft identity code to add it to the startup, literally single line of code with b2c client settings in app settings. I'm out to dinner at the moment, if you need exact copy of code I can share it when I get back home in about 30 minutes.

**Comment by johnwc** [comment]
@davidfowl I updated the original question with more code

**Comment by blowdart** [comment]
[Authorize] checks if the resource is marked by [AllowAnonymous] and skips authorization in this case.

Where do the docs say otherwise? If I look at the [main authorization doc](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-6.0) page it has a nice warning,

> [AllowAnonymous] bypasses all authorization statements. If you combine [AllowAnonymous] and any [Authorize] attribute, the [Authorize] attributes are ignored. For example if you apply [AllowAnonymous] at the controller level, any [Authorize] attributes on the same controller (or on any action within it) is ignored.

**Comment by davidfowl** [comment]
The user should still be available for authorized users.

**Comment by johnwc** [comment]
@blowdart authorized and authenticated are two different things. In this case, we don't need anyone to be "authorized" to use this api method, but they should be able to authenticate if they do have valid credentials. The api method has different flows depending if they are authenticated.

@davidfowl any idea where I need to look to find out why it's not working?

**Comment by johnwc** [comment]
@blowdart Here is where it states it. Not in the docs maybe, but documented within the code itself.
[AuthorizationMiddleware.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L126)

**Comment by johnwc** [comment]
@davidfowl I was able to get this to work today. I had to add a default scheme policy or assign a policy to the Authorize attribute. Just adding schemes was not enough.

**Comment by davidfowl** [comment]
@johnwc do you want to contribute to the docs to help the next person that runs into this 😃 ?

**Comment by johnwc** [comment]
@davidfowl sure, it may take me a few or two though to find some time. What page exactly do you think it should be updated on, and would example config be ok?

**Comment by halter73** [comment]
We are looking at changing the behavior for, or at least warning for, instances of the following where `[Authorize]` is "closer" to the endpoint than `[AllowAnonymous]`, yet `[AllowAnonymous]` still wins. While `[AllowAnonymous]` always winning is simple to explain, it's unintuitive and likely unexpected by many developers.

```csharp
namespace AspNetAuthz
{
    [AllowAnonymous]
    public class OAuthControllerAnon : ControllerBase
    {
    }
 
    [Authorize]
    public class OAuthControllerAuthz : ControllerBase
    {
    }
 
    [Authorize] // BUG
    public class OAuthControllerInherited : OAuthControllerAnon
    {
    }
 
    public class OAuthControllerInherited2 : OAuthControllerAnon
    {
        [Authorize] // BUG
        public IActionResult Privacy()
        {
            return null;
        }
    }
 
    [Authorize]
    [AllowAnonymous] // BUG
    public class OAuthControllerMultiple : ControllerBase
    {
    }
 
    [AllowAnonymous]
    public class OAuthControllerInherited3 : ControllerBase
    {
        [Authorize] // BUG
        public IActionResult Privacy()
        {
            return null;
        }
    }
}
```

**Comment by johnwc** [comment]
@halter73 @mkArtakMSFT do these new introductions that are being added into .Net 9 change how this works now? Where we have an api endpoint that can be anonymous as well as authenticated. If an anonymous request comes in, it returns a filtered response; if an authenticated request comes in, it returns response based on user's access.

**Comment by halter73** [comment]
No. We're only adding a compile-time analyzer that warns you when you have an `[Authorize]` attribute that might unintentionally overridden by `[AllowAnonymous]`. Any working code you have should continue to work.

> I was able to get this to work today. I had to add a default scheme policy or assign a policy to the Authorize attribute. Just adding schemes was not enough.

Worst case is you might get a warning you have to suppress the warning, but we tried to design the analyzer so you could continue to do anything you were doing before without suppressing warnings by moving attributes. So, in your case, you might have to put `[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]` before `[AllowAnonymous]` which puts `[AllowAnonymous]` "closer" to the action method and hopefully indicates you understand `[AllowAnonymous]` is not overridden.

However, if the authentication scheme you want to use is not endpoint specific, your call `AddAuthentication(JwtBearerDefaults.AuthenticationScheme)` should have been sufficient to set the default authentication scheme for all endpoints. Neither `[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]` nor `[AllowAnonymous]` should be necessary anywhere. I wonder if something else is changing `AuthenticationOptions.DefaultScheme` or `DefaultAuthenticateScheme`.

It should be easy to find out what's going on by calling `HttpContext.AuthenticateAsync()` and stepping into the framework code with F11. There's a lot of indirection, so it could be a number of things like custom `IAuthenticationService` or `IAuthenticationSchemeProvider` registered with DI that's causing the weird behavior, but stepping into the code should tell you what's going on whatever the case. If you still have trouble figuring it out, you should file a new issue, but please include a complete repro project.

**Comment by johnwc** [comment]
Oh, I have everything already working as expected. I just wanted to know if it would break when moving to .Net 9. We already have the `[Authorize]` set high, and `[AllowAnonymous]` set at individual endpoints to only poke holes that need to be.
