### ISSUE TITLE
using the blazorwebview control to load a local and external plugin of blazor webassembly program in the Maui blazor program does not work

### ISSUE THREAD

**Issue by 835718973** [dotnet/aspnetcore#43565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to use the blazorwebview control to load a local and external plugin of blazor webassembly program in the Maui blazor program. When I run on the windows platform, everything is normal. When I switch to the Android platform,i got an error "[chromium] [INFO:CONSOLE(1)] "Streaming compilation failed. Falling back to ArrayBuffer instantiation.  TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.", source: https://0.0.0.0/_framework/blazor.webassembly.js (1)".But When I use the chrome://inspect/#devices to inspect the  program and click the reload button,it just work well.
before inspect
![image](https://user-images.githubusercontent.com/20808204/186856628-476dd88a-fecb-4e95-a662-633a22da2d37.png)
![image](https://user-images.githubusercontent.com/20808204/186905023-b9d24281-9700-4c13-a55e-1eb3cfd96c99.png)

after inspect
![image](https://user-images.githubusercontent.com/20808204/186856837-0b2d4bf9-fa5d-4ba5-849a-b2550ac3c49e.png)

### .NET Version

6.0.400

**Comment by javiercn** [comment]
@835718973 thanks for contacting us.

This is not a scenario that we support, the Blazor Webview is designed (for the time being) to only run Blazor Desktop applications, you can't mix and match with Webassembly. 

If you want to host a Blazor webassembly app inside a regular webview, that is not something we support nor plan to provide guidance for.
