### ISSUE TITLE
[SignalR-Client-Cpp] cmake build for MSYS/Mingw64 on windows failed

### ISSUE THREAD

**Issue by Wasenshi123** [dotnet/aspnetcore#43560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I follow the instruction on github, modifying cmake command as followed:
`cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE="../submodules/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DUSE_CPPRESTSDK=false`

Then, when I build with `cmake --build . --config Release` the error occurred about **unknown conversion type character** 

Here is some part of the log:
```
D:/msys64/opt/SignalR-Client-Cpp/src/signalrclient/logger.cpp: In member function 'void signalr::logger::log(signalr::trace_level, const char*, size_t) const':
D:/msys64/opt/SignalR-Client-Cpp/src/signalrclient/logger.cpp:49:65: error: unknown conversion type character 'F' in format [-Werror=format=]
   49 |                 std::strftime(timeString, sizeof(timeString), "%FT%T.000Z", &time);
      |                                                                 ^
D:/msys64/opt/SignalR-Client-Cpp/src/signalrclient/logger.cpp:49:68: error: unknown conversion type character 'T' in format [-Werror=format=]
   49 |                 std::strftime(timeString, sizeof(timeString), "%FT%T.000Z", &time);
      |                                                                    ^
cc1plus.exe: all warnings being treated as errors

```

I'm not sure this is a bug or not, but I don't know how to fix this.  Please enlighten me.

Thank you

### Expected Behavior

The signalr-client-cpp should build successfully.

**Comment by BrennanConroy** [comment]
`%F` and `%T` are standard format specifiers: https://en.cppreference.com/w/cpp/chrono/c/strftime
Are you using an old or unusual compiler? You need one that supports C++11 at a minimum.

**Comment by Wasenshi123** [comment]
> `%F` and `%T` are standard format specifiers: https://en.cppreference.com/w/cpp/chrono/c/strftime Are you using an old or unusual compiler? You need one that supports C++11 at a minimum.

This is what I used
```
g++ --version
g++.exe (Rev5, Built by MSYS2 project) 10.3.0

gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 10.3.0

```

**Comment by BrennanConroy** [comment]
I'm not familiar with MSYS2, but looking at the docs, they do mention some issues with format specifiers: https://www.msys2.org/wiki/Porting/#c-printf-format-specifier-issues

**Comment by Wasenshi123** [comment]
> 

Perhaps that is the case.

The doc (from your link) says to pass this flag to compiler
`-D__USE_MINGW_ANSI_STDIO=1`

```
MinGW-w64 works around this by providing their own implementation. To enable this you should pass -D__USE_MINGW_ANSI_STDIO=1 to the MinGW-w64 C and C++ compilers. All of our C/C++ packages are built with this flag.
```
Could you guide me to how can I do this? (what or where should I modify in the source code before I try building it again?)

**Comment by BrennanConroy** [comment]
Just pass that flag when you build
`cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE=... -D__USE_MINGW_ANSI_STDIO=1`
You might need to clear the cmake cache first

**Comment by Wasenshi123** [comment]
> Just pass that flag when you build `cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE=... -D__USE_MINGW_ANSI_STDIO=1` You might need to clear the cmake cache first

Well, doing that I get this

```
CMake Warning:
  Manually-specified variables were not used by the project:

    __USE_MINGW_ANSI_STDIO
```
(and still not success)

**Comment by BrennanConroy** [comment]
Hmm, don't know how to fix it.

You should be able to workaround the issue by passing `-DWERROR=false`. Or even modifying the logger.cpp code to use `%Y-%m-%d` for `%F` and `%H:%M:%S` for `%T`

**Comment by Wasenshi123** [comment]
I tried adding `-DWERROR=false` and the build went through 100% but got error at the end

```
[100%] Linking CXX executable ..\..\bin\signalrclienttests.exe
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [test\signalrclienttests\CMakeFiles\signalrclienttests.dir\build.make:865: bin/signalrclienttests.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:1071: test/signalrclienttests/CMakeFiles/signalrclienttests.dir/all] Error 2
mingw32-make: *** [Makefile:145: all] Error 2
```

**Comment by BrennanConroy** [comment]
You can also skip building the test project `-DBUILD_TESTING=false`.

**Comment by Wasenshi123** [comment]
Ok. Thank you for you help. Now I can have the `libmicrosoft-signalr.dll` lib built successfully (at least haha).

If I have further question from here, where should I get help though?

**Comment by Wasenshi123** [comment]
I will close this now and will open new issue if I stuck somewhere.

Thank you again for your help. May you have great days for the whole next month :)
