### ISSUE TITLE
asp.net core identity two factor remember me cookie being overwritten

### ISSUE THREAD

**Issue by datalims** [dotnet/aspnetcore#43577]
I have an asp.net core standard 6 MVC application that utilizes Identity for Authentication. For 2fa I am using sms or email for verification - I don't want to use authenticator apps.  I am able to go through the login process and verify a user with two factor authentication. A 2fa cookie is saved in the users browser for the next login. However, when the next person signs in with two factor the previous 2fa cookie gets replaced. It seems like I can only keep one 2fa cookie at a time. I have followed the code from textbooks as well as code repositories and nothing seems to work.

**Comment by blowdart** [comment]
Yes. That's by design. The "Don't prompt again" cookie is for the machine, not the user.
