### ISSUE TITLE
[Feature Request]: Make LinkGenerator support complex objects

### ISSUE THREAD

**Issue by mariusz96** [dotnet/aspnetcore#43572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Since at least couple versions it is possible to model bind GET requests' query parameters to complex objects, however `LinkGenerator` does not support destructuring them and requires passing each complex object's property separately.

So, for example, this controller:
```cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TestController : ControllerBase
    {
        private readonly LinkGenerator _linkGenerator;

        public TestController(LinkGenerator linkGenerator)
        {
            _linkGenerator = linkGenerator;
        }

        [HttpGet]
        public string? Get([FromQuery] DateFilters dateFilters, [FromQuery] ProductFilters productFilters)
        {
            return _linkGenerator.GetUriByAction(
                HttpContext,
                nameof(Get),
                nameof(TestController).Replace("Controller", ""),
                new { dateFilters = dateFilters, productFilters = productFilters });
        }
    }

    public class DateFilters
    {
        public DateTime? From { get; set; }
        public DateTime? To { get; set; }
    }

    public class ProductFilters
    {
        public string? Product { get; set; }
    }
}

```

when I go to `https://localhost:7078/api/Test?from=2022-08-01&to=2022-08-26&product=aspnetcore`,
 outputs `https://localhost:7078/api/Test?dateFilters=WebApplication2.Controllers.DateFilters&productFilters=WebApplication2.Controllers.ProductFilters`.

It works correctly when I destructure by hand:
```cs
            return _linkGenerator.GetUriByAction(
                HttpContext,
                nameof(Get),
                nameof(TestController).Replace("Controller", ""),
                new { from = dateFilters.From, to = dateFilters.To, product = productFilters.Product });
```
however, this is very unintuitive and a bit awkward and requires each client to come up with new destructuring. It also always requires keeping destructuring up-to-date with new properties that get added to the original complex objects.

This obviously gets multiplied when someone does this in multiple places ie trying to implement HATEOAS-style navigation links.

### Describe the solution you'd like

I would like `LinkGenerator` to destructure complex objects for me, in the exact same way that the model binding constructed them.

### Additional context

The other, admittedly selfish, motivation is that it would allow my own nuget library that uses `LinkGenerator` to be used with far better and more immediate syntax :bowtie:

**Comment by javiercn** [comment]
@mariusz96 thanks for contacting us.

Model binding works at a different layer than LinkGenerator. LinkGenerator only understands about route-values and we do not have plans to build more complex functionality like the one you are describing into it.

You can build this yourself as an extension method, but this is an opinion that we do not think we want to bake into routing.

**Comment by mariusz96** [comment]
> @mariusz96 thanks for contacting us.
> 
> Model binding works at a different layer than LinkGenerator. LinkGenerator only understands about route-values and we do not have plans to build more complex functionality like the one you are describing into it.
> 
> You can build this yourself as an extension method, but this is an opinion that we do not think we want to bake into routing.

Thank you for your answer, I understand where you're coming from.

However reverse engineering framework's internal model binding (that is subject to change) in the external code does not seem like a viable option either.

I see that for manual model binding there is `TryUpdateModelAsync` method on a controller - is s there a counterpart in the framework that would allow me to do `bool TryGetRouteValues<TModel>(model, out RouteValueDictionary values)`?

**Comment by javiercn** [comment]
@mariusz96 no, there is not.

In general, what you are asking for is not a routing feature, it's a "something else" feature. Routing does not understand about the query string, it understands "route values" only.

Modelbinding is highly customizable, and the process is in general not something that roundtrips (can be reversed). If you want some syntactic sugar, I suggest that you create a tag helper or extension method to make simple conversions from an object to the list of route values you care about. You don't need to support arbitrary complexity here.

**Comment by mariusz96** [comment]
Ok, thank you for your answers.
