### ISSUE TITLE
CookieOptions - Domain property not leading to expected behavior

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Executing

```cs
            CookieOptions options = new CookieOptions() { SameSite = SameSiteMode.None, Secure = true, Domain = "domain.net", Expires = ofx };

            Response.Cookies.Append("lti_security_token", tokenstring, options);

            return Redirect("https://www.google.com");  // this is just example, in reality we redirect to one of our subdomains.
```
Does not _reliably_ lead to a cookie being saved in user's browser.

The documentation strongly implies that if we set `Domain` to say `domain.com` (or `.domain.com`) then any requests to any subdomain like `services.domain.com` or `applications.domain.com` and so on, will, when received by ASP.NET code, contain the cookie "lti_security_token" (in this examples).

What I'm seeing is that if we leave `Domain` _unset_ in the options, then the cookie is created for the current domain and can be seen in the browser, for example when executed in server code at `services.domain.com` the cookie is created for that domain. Any subsequent requests received at the domain `services.domain.com` will contain the cookie.

But setting `Domain` leads to no cookie being created, even setting `Domain` to the full domain `services.domain.com` still leads to no cookie being created. So it seems that setting `Domain` to _any value_ whatsoever breaks cookie creation.

### Expected Behavior

The cookie should be created when `Domain` is set to a proper subdomain or even the exact same domain and the cookie should be present in any received request where the domain of the request "matches" the subdomain.

### Steps To Reproduce

I don't have a runnable repro. The code involved is a service and a webapp each hosted in a dev Azure account under two different domains each ending in `azurewebsites.net`. When the service is hit and `Domain` is not set in `CookieOptions`, then the cookie gets created under the full domain of the service (`services.azurewebsites.net`) and is only ever seen in code running at that exact same domain, requests sent to _other subdomains_ - ending in `.azurewebsites.net` - **do not contain** the cookie, nor would I expect them to, since the browser has failed to create such cookie!

### .NET Version

6.0.400

### Anything else?

This is the [documentation ](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2#share-cookies-across-subdomains-1) that I was studying.

**Comment by Tratcher** [comment]
If you look in the developer tools at the response headers, do you see the Set-Cookie header created with the expected field? Then compare to the browser tools that list cookies for the current page/app. If the Set-Cookie header is present, then everything else is about correctly understanding the browser rules. That is out of scope for this repo.

**Comment by Korporal** [comment]
@Tratcher - Thanks, give me some time and I'll try to get this info.

**Comment by Korporal** [comment]
@Tratcher - I haven't had the time to explore this yet, but wanted to ask, is my interpretation of the documentation reasonable? Would you regard my expectation as reasonable? (browser issues aside).

**Comment by Tratcher** [comment]
Honestly I don't know the browser handling details well. CookieOptions is a very simple component, it puts the value you give it into the Set-Cookie header. Understanding which value to give it is a different matter.
