### ISSUE TITLE
Remove temporary workaround to not use msbuild server

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#43581]
https://github.com/dotnet/aspnetcore/pull/43028 is adding `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER` to build YAML to workaround SDK update issue.

This is a temporary fix and should be removed when no longer needed.

Example,

```
# !temporary! Remove as soon as .NET SDK includes a new-enough `msbuild` to make this hack unnecessary
DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER: true
```

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/44808
