### ISSUE TITLE
Blazor WASM - TypeError: Window.fetch: HEAD or GET Request cannot have a body.

### ISSUE THREAD

**Issue by TehGM** [dotnet/aspnetcore#43602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to send a GET request with included body from Blazor WASM client (using a `HttpClient` instance), the request doesn't get sent and `System.Net.Http.HttpRequestException` exception is output in browser console instead.

This seems to be caused by JS fetch polyfill not supporting this kind of requests, even though they're allowed by HTTP spec since 2014 ([RFC-7231](https://www.rfc-editor.org/rfc/rfc7231#page-24)).

### Expected Behavior

A HTTP GET request with body should be able to be sent when using HttpClient in Blazor WASM.

### Steps To Reproduce

1. Create a HttpClient instance in a Blazor WebAssembly project.
2. Attempt to send a GET request with any type of body content.
3. Observe browser's console output.

Repro code: https://github.com/TehGM/BlazorHttpGetExceptionRepro
In the repro project, Index.razor page has a simple button that sends a sample GET Request on click. Upon clicking, an exception should be logged in console.

.NET Fiddle with the code from method - runs just fine: https://dotnetfiddle.net/DlwZvA

### Exceptions (if any)

Unhandled exception rendering component:  TypeError: Window.fetch: HEAD or GET Request cannot have a body. 
 System.Net.Http.HttpRequestException: TypeError: Window.fetch: HEAD or GET Request cannot have a body.
 ---> System.Runtime.InteropServices.JavaScript.JSException: TypeError: Window.fetch: HEAD or GET Request cannot have a body.
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

### .NET Version

6.0.400

### Anything else?

Tested using:
- Firefox 105.0b3
- Google Chrome 104.0.5112.102

**Comment by javiercn** [comment]
@TehGM thanks for contacting us.

We do not use a fetch polyfill. The browser does not allow you to send GET requests with a body in them. The behavior here is correct and by design, its a browser limitation that we can't lift.
