### ISSUE TITLE
Render image for static files logged in console browser 404

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#43613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want work with **Blazor** with **ASP.NET MVC Core**.
I want to display an **image** on the site using **StaticFiles**. Everything is fine, and the image doesn't read first, but the background of the `OnInitializedAsync `section runs and displays the image

### Component.razor 
`<img src="images/attach-file.png" class="mb-4" width="100" height="100" />`

### Browser Console 
`Failed to load resource: the server responded with a status of 404 ()        attach-file.png:1 `

### First time 
![image](https://user-images.githubusercontent.com/45498591/187134910-55ddcbf1-693b-4a63-9bcf-03456e45c7f9.png)

### After completed OnInitializedAsync 
![image](https://user-images.githubusercontent.com/45498591/187135044-2a437a98-e03e-4d8f-b7f6-7d76abdacfc1.png)

### .NET Version

.NET 6

### Anything else?

PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by javiercn** [comment]
@zanyar3 thanks for contacting us.

It is not clear to us what is going on here, but it is very likely a problem specific to your app. We would suggest you try several things:
* Request the image on the browser directly to see if it is being served.
* Temporarily comment out the blazor script in _Host.cshtml to prevent Blazor from starting and check that you are generating the correct markup.
* Check on the network section of the developer tools that the URL is correct.

**Comment by zanyar3** [comment]
@javiercn Thanks for response.

I want to be clear, when you want to work with images before the page loaded, that is, before the `OnInitializedAsync `or `OnInitialized ` run, images determine that there is a problem so it does not find, but after the `OnInitializedAsync `or `OnInitialized `images read.

Actually this is not a problem because it reads the pictures but I wonder why !!!?

 If use below code, not happened this problem 
```
@if(isPageLoaded)
{
   <img src="images/attach-file.png" class="mb-4" width="100" height="100" />
}

@code {
    bool isPageLoaded = false;
    protected override void OnInitialized()
    {
         isPageLoaded  = true;
    }
}
```

I hope clear

**Comment by javiercn** [comment]
@zanyar3 is this blazor server or webassembly, are you prerendering?

**Comment by zanyar3** [comment]
> @zanyar3 is this blazor server or webassembly, are you prerendering?

I am work with **ServerSideBlazor**.

**Comment by javiercn** [comment]
@zanyar3 Are you using `render-mode="Sever" or "ServerPrerendered"

**Comment by zanyar3** [comment]
> @zanyar3 Are you using `render-mode="Sever" or "ServerPrerendered"

I was used `RenderMode.ServerPrerendered` 

For render component use below code

 ```
@(await Html.RenderComponentAsync<Components.MyComponent>(RenderMode.ServerPrerendered))
```

**Comment by javiercn** [comment]
@zanyar3 comment out the `blazor.server.js` script and check if the problem happens. Look at the network tab in the dev tools and check the request for the image.

**Comment by zanyar3** [comment]
@javiercn I am sure problem with render **Blazor**,

Because when I adding condition for `OnInitialized `not happened.

### Request 
```
Request URL: https://localhost:7240/Incoming/images/attach-file.png
Request Method: GET
Status Code: 404 
Remote Address: [::1]:7240
Referrer Policy: strict-origin-when-cross-origin
```
### Response 
This request has not response data available

**Comment by javiercn** [comment]
@zanyar3 can you provide a minimal repro project as a public github repository so that we can take a look?

**Comment by zanyar3** [comment]
Sorry can't shared my repo because include our business  logic and pattern, but I can explain you by below codes.

### Index.cshtml

`@(await Html.RenderComponentAsync<Components.MyComponent>(RenderMode.ServerPrerendered))`

### MyComponent.razor

```
<img src="images/attach-file.png" class="mb-4" width="100" height="100" />

@code {
    
    protected override void OnInitialized()
    {
    }
}
```

I hope I was able to explain it to you in a good way

Regards

**Comment by javiercn** [comment]
@zanyar3 we are not asking you to share your project, but to create a new from the template and put code in that project that reproduces your issues.

Unfortunately, we do not have enough information to make progress here. With the data that we currently have, we believe it is unlikely that this is a framework problem, so unless we get more information, we won't be able to help here.
