### ISSUE TITLE
SignalR C++ Client read access violation from signalr_client_config destructor

### ISSUE THREAD

**Issue by ChrisHawkridge** [dotnet/aspnetcore#43617]
Hi there,

I am getting a read access violation as soon as an instance of signalr_client_config goes out of scope.
I pulled the microsoft-signalr package from vcpkg and I am using Visual Studio 2022.

### To Reproduce
I created a blank windows console app with the following code.
```
#include <iostream>
#include "signalrclient/hub_connection.h"

int main()
{
    std::cout << "Hello World!\n";

    {
        std::map<std::string, std::string> http_headers;
        http_headers.insert({ "Authorization", "" });

        signalr::signalr_client_config config;
        config.set_http_headers(http_headers);
    }

    std::cout << "finished.\n";
}
```

**Comment by BrennanConroy** [comment]
These kinds of issues can occur if you use different compilers/compiler versions for different parts of your application.

What compiler did you use via vcpkg to build microsoft-signalr? And what compiler are you using with VS 2022?

**Comment by BrennanConroy** [comment]
Ah, the issue is that your application needs to define USE_CPPRESTSDK, that requirement will go away in the future.

**Comment by ChrisHawkridge** [comment]
Thanks, all looks good now.
