### ISSUE TITLE
Unified Build control update

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#43637]
### Description

**This issue is dependent on https://github.com/dotnet/source-build/issues/2974 and is a placeholder for .NET 8 required work in product repositories.**

Instructions for implementation will be updated once https://github.com/dotnet/source-build/issues/2974 but will likely be a mechanical shift of properties in this repo. In a general sense, this is scaffolding work for expanding the set of source-built platforms beyond Linux.

**Comment by mmitche** [comment]
This is .NET 8 work

**Comment by mkArtakMSFT** [comment]
Marked this as `blocked` for now given we have no much context about the work.

**Comment by wtgodbe** [comment]
@mmitche does this still need to be open?

**Comment by mmitche** [comment]
Yeah this hasn't been done for aspnetcore yet. I am looking into it today. May need your help on enabling aspnetcore

**Comment by mmitche** [comment]
Completed with aspnetcore enabledment
