### ISSUE TITLE
Add equivalent of HttpRuntime.AppDomainAppId available at all times when hosted in IIS

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/aspnetcore#43631]
## Summary

When an ASP.NET Core application is hosted in IIS, IIS gives it an application ID, the same way it gives every other application an application ID. This contains the site ID (numeric) and virtual directory path, and is already used in ASP.NET Core.

In .NET Framework / ASP.NET applications, this value is available via `HttpRuntime.AppDomainAppId` which reads it from the current AppDomain's data. In ASP.NET Core, this value is only available during the lifetime of a request via `IServerVariablesFeature`, but outside of a single request there is no API for it. 

The value is, however, already known internally to the ASP.NET Core Module and can be reached via reflection and pointer arithmetic. Making it available to the rest of the application is a question of "how", not "if".

## Motivation and goals

Applications that are hosted in IIS and rely on this value outside of a request lifetime (e.g. during startup or during background work) can be ported from ASP.NET / .NET Framework to ASP.NET Core on modern .NET without needing to completely rework any logic that uses the `AppDomainAppId`.

The particular scenario I have at the moment is a web application that runs multiple instances on different domains from the same physical path on disk. The only way the application can differentiate between instances e.g. for additional config or cache directories) is the IIS site ID.

## In scope

ASP.NET Core user code can resolve the IIS application ID if hosted in IIS.

Unit tests for the above user code can easily mock or stub this interface so that code under test can be provided with a fake IIS application ID.

## Out of scope

ASP.NET applications not running in IIS, or on non-Windows platforms, do not need to be able to resolve any such value.

The Site ID can be provided as a string in the same manner that `HttpRuntime.AppDomainAppId` does, it does not need to be parsed or otherwise split into individual components. That can be left up to the consumer.

## Risks / unknowns

This will require changes to ANCM, and I do not know what the fowards-compatibility and backwards-compatibility concerns here are and how to mitigate them.

## Examples

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile(..., $"Config-{GetSiteIDSomehow()}.json");
builder.Services.AddSomeModule(options => options.Category = $"MyCategory-{GetSiteIDSomehow()}");
var app = builder.Build();
app.UseSomeModule();
app.Run();
```

```csharp
class MyDependencyInjectedClass
{
    public MyDependencyInjectedClass(ISiteIDProviderOfSomeVariety provider)
    {
        cacheDirectory = Path.Combine(Path.GetTempPath(), "MyApplication", provider.SiteID);
    }

    readonly string cacheDirectory;
}
```

## Notes

This can be done already, albeit extremely hackily, by reflection and pointer arithmetic to access values stored within the IIS integration memory:

```csharp
var builder = WebApplication.CreateBuilder(args);
var nativeApplicationType = Type.GetType("Microsoft.AspNetCore.Server.IIS.Core.IISNativeApplication, Microsoft.AspNetCore.Server.IIS");
var iisNativeApplication = builder.Services.Where(s => s.ServiceType == nativeApplicationType)
    .Select(x => x.ImplementationInstance)
    .FirstOrDefault();

if (nativeApplicationType?.GetField("_nativeApplication", BindingFlags.NonPublic | BindingFlags.Instance) is { } field &&
    field.GetValue(iisNativeApplication) is SafeHandle nativeApplicationHandle)
{
    var nativeApplicationPointer = nativeApplicationHandle.DangerousGetHandle();

    var objectPointer = IntPtr.Add(nativeApplicationPointer, 136); // Assuming x64, recalculate for x86
    var configPathPointer = Marshal.ReadIntPtr(objectPointer);

    // Got the config path!
    var configPath = Marshal.PtrToStringUni(configPathPointer);
}
```

I would much rather this be exposed as an API as this relies heavily on not just ASP.NET internals but also the memory layout of underlying native types.

I am happy to drive the implementation myself with a PR, once a design is negotiated and approved.

**Comment by davidfowl** [comment]
Can you change this to an [API proposal?](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=)

**Comment by yaakov-h** [comment]
@davidfowl I'm not sure exactly what the API should look like, specifically for the first example I posted where there's no IServiceProvider yet. Can I start an API proposal without a proposed API shape yet?

**Comment by davidfowl** [comment]
> @davidfowl I'm not sure exactly what the API should look like, specifically for the first example I posted where there's no IServiceProvider yet. Can I start an API proposal without a proposed API shape yet?

Looking at this a bit more, how about we make this a hosting configuration variable that is set here https://github.com/dotnet/aspnetcore/blob/318e16b6ac3a9644b266a463c8db47d6a24cad0d/src/Servers/IIS/IIS/src/WebHostBuilderIISExtensions.cs#L30.

We can give it a well known name with a prefix that won't collide with typical configuration keys:
- iis:siteid
- iis:virtualpath

```C#
var builder = WebApplication.CreateBuilder(args);
var siteId = builder.Configuration["iis:siteid"];
builder.Configuration.AddJsonFile(..., $"Config-{siteId}.json");
builder.Services.AddSomeModule(options => options.Category = $"MyCategory-{siteId}");
var app = builder.Build();
app.UseSomeModule();
app.Run();
```

**Comment by yaakov-h** [comment]
haha, I just came to the same conclusion and was literally just writing that up now, though with a slightly different value (I was thinking of a new WebHostDefaults string constant).

I'll open a new Issue and link them.

**Comment by davidfowl** [comment]
> haha, I just came to the same conclusion and was literally just writing that up now, though with a slightly different value (I was thinking of a new WebHostDefaults string constant).

Don't want anything IIS specific on there, so it would need to be an IISWebHostDefaults* type.
