### ISSUE TITLE
Default Templates with scoped css are not actually applied

### ISSUE THREAD

**Issue by Jeanot-Zubler** [dotnet/aspnetcore#43659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When generating a new ASP.NET Core Web App, the styles defined in `Pages/Shared/_Layout.cshtml.css` are for the most part not actually applied to the corresponding elements, because the default Layout uses Taghelpers for the navigation links.

For example, the following styles are not applied: 
```
a.navbar-brand{
  white-space: normal;
  text-align: center;
  word-break: break-all;
}
```

This was introduced in issue #31030 / merge request  #35658

### Expected Behavior

Default project Templates should not have examples that don't actually work. It should use a structure so the scoped css can actually be applied.

### Steps To Reproduce

- Create a new ASP.NET Core Web App
- Run
- in browser, check developer tools
- see that css properties for links (`a`) are not applied

### .NET Version

6.0.8

**Comment by javiercn** [comment]
@Jeanot-Zubler thanks for contacting us.

Dupe of https://github.com/dotnet/aspnetcore/issues/30213 this is currently by design, as scoped CSS applies to HTML in the file, not to the tag helpers or components.

**Comment by Jeanot-Zubler** [comment]
I know that this is by design. But then please change the templates, so that they don't contain css, that by design can never be applied.
