### ISSUE TITLE
User.Identity.IsAuthenticated.IsAuthenticated returns true when action method is decorated with [AllowAnonymous] attribute

### ISSUE THREAD

**Issue by omid-ahmadpour** [dotnet/aspnetcore#43653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .Net core web api, action method which decorated with [AllowAnonymous] attribute, when you pass the jwt token to these api, the property User.Identity.IsAuthenticated.IsAuthenticated, returns true, since it is a free authentication action method, but when call action method without jwt token it returns false.

// decorated action method with [AllowAnonymous] attribute
`
[AllowAnonymous]
`
`
public async Task<ActionResult<LoginResponse>> Login(UserLoginRequest request)
{
	return this.Ok();
}
`

// call User.Identity.IsAuthenticated to find user is authenticated or not
`
User.Identity.context.User.Identity.IsAuthenticated
`

### Expected Behavior

This User.Identity.IsAuthenticated.IsAuthenticated should return false in any cases like when the action method is decorated with [AllowAnonymous] attribute, because it's a free authentication action method.

### .NET Version

net6.0

**Comment by javiercn** [comment]
> This User.Identity.IsAuthenticated.IsAuthenticated should return false in any cases like when the action method is decorated with [AllowAnonymous] attribute, because it's a free authentication action method.

That's not how it works. AllowAnonymous means let the user go in whether it has credentials or not. Authenticating the user is different than authorizing the user, and the principal reflects that. You might want to display information specific to the user even if you allow guest users to get in.

**Comment by omid-ahmadpour** [comment]
I'm talking about authentication, not authorization. when we decorate an action method, it means that doesn't need any authentication, but the User.Identity.context.User.Identity.IsAuthenticated return true is some cases (if we pass jwt token to apis that work with any authentication), my idea is, this property ( User.Identity.IsAuthenticated.IsAuthenticated  ) should return false in any cases when the action methods have [AllowAnonymous] attribute.

**Comment by javiercn** [comment]
> when we decorate an action method, it means that doesn't need any authentication

That's not the case. `AllowAnonymous` means let this user in even if it is not authenticated, it does not mean "do not authenticate this user".

**Comment by omid-ahmadpour** [comment]
Ok, could you tell me what is the meaning of User.Identity.context.User.Identity.IsAuthenticated? What does it show?

**Comment by javiercn** [comment]
@omid-ahmadpour it shows if the user is authenticated according to the authentication scheme for the endpoint, which in your case is JWT (since the request contains a token)

**Comment by Tratcher** [comment]
This likely happens because you have enabled JWT as your default auth scheme for all requests. It reads the JWT and sets the user before it looks at the endpoint to decide if authorization is needed.
