### ISSUE TITLE
Is it possible to use PKCE - Proof Key for Code Exchange on Azure AD App Registration + Blazor Server ? How to do it?

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/aspnetcore#43668]
I configured my Azure App registration and configured Web Redirect URI for Blazor Server App published on Azure and it runs as expected.

But I would like to use Proof Key for Code Exchange on this App, then I put the Redirect URI under Single-page application, but then this error appears:

`AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.`

Is it possible to use PKCE - Proof Key for Code Exchange on Azure AD + Blazor Server ?  
How to configure this on Azure Portal and How configure it on my .NET 6 Blazor Application?

**Comment by javiercn** [comment]
@TonyHenrique thanks for contacting us.

You should configure Blazor Server as a Web Application registration, not a SPA, as Blazor Server apps typically use OAuth+Cookie to set the auth context on the server before the Blazor Server app starts.

You should be able to configure the openid connect handler to use PKCE, you shouldn't need to configure that on the portal.
