### ISSUE TITLE
ASP.NET Core v6.0.8    source  build sucessed   and installed  ,but  enter f11   can't  view source code

### ISSUE THREAD

**Issue by yanghuawen** [dotnet/aspnetcore#43673]
1, installed " aspnetcore-runtime-6.0.8-dev-win-x64.msi "   package

**2, already add nuget.config  to the project** 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		`<clear` />
		<add key="MyBuildOfAspNetCore" value="E:\core3\AspNetCore\artifacts\packages\Debug\Shipping\" />
		<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
	</packageSources>
`</configuration>``

**3  use vs 2022   create a mvc project ,enter f11  view souce code,  but  failed**
[https://images.cnblogs.com/cnblogs_com/blogs/729358/galleries/2211331/o_220901004234_2.png](url)
remark(operate system is win10)

who can help me ,thanks very much !

**Comment by Pilchie** [comment]
Hi - take a look at https://docs.microsoft.com/aspnet/core/test/debug-aspnetcore-source for some instructions on how to debug aspnetcore source code.
