### ISSUE TITLE
Concurrency issue with UserManager

### ISSUE THREAD

**Issue by KurtP20** [dotnet/aspnetcore#43687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I ran into a concurrency issue with `UserManager` in a Blazor server side app, and after some discussions with Luke at [#26874](https://github.com/dotnet/AspNetCore.Docs/pull/26874#issuecomment-1233040627), he recommended to raise this issue here. As described in detail [here](https://stackoverflow.com/questions/73498604) and in #26873, I strongly believe that every `UserManager` obtained with dependency injection uses the same `DbContext`, which can lead to concurrency issues. This concurrency issue is likely related to other issues here, namely #18340 and [#16745](https://github.com/dotnet/aspnetcore/issues/16745#issuecomment-549505605).

So here are the details, I try to be as brief as possible:

When I changed to EF Core 5.0, I started to use the `AddDbContextFactory` to get the `DbContext` in my classes. This change broke Identity, and I had to follow [this advice](https://stackoverflow.com/a/64185721/645282) to make the `DbContext` available to Identity. This strongly indicates, that Identity uses the `DbContext` directly, and not the factory as recommended since EF Core 5.0 [here](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#dbcontextfactory) and [here](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor).

In my app, I inject `UserManager` in differnet Razor pages, in the NavMenu, LoginDisplay and some service classes to obtain the Identity user from a `ClaimsPrincipleUser`. In some Razor components, I inject `UserManager` to find the role of the user (see [here](https://github.com/dotnet/AspNetCore.Docs/pull/26874#issuecomment-1232926029) for code examples). When I started using `UserManager` in the components, I bumped into a concurrency issue, but as I describe below, this concurrency issue isn't restricted to components, but can also happen in other code.

So there are actually two aspects to the issue:

### 1. Using `UserManager` in a Razor component
The [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0) states *not* to use `UserManager` in Razor components

> ASP.NET Core abstractions, such as [SignInManager<TUser>](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1) and [UserManager<TUser>](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1), aren't supported in Razor components. 

From my experience, I *can* inject `UserManager` into Razor components and use it to find the role of the user. So wouldn't it be better to clearly state under which conditions it is save to use `UserManager` in Razor components instead of recommending not to use it at all?

### 2. An injected `UserManager` should use `DbContextFactory`
IMHO I think that the concurrency issue that I discoverd when using components can also occur in other parts of the code, e. g. in my service classes, because all `UserManager`s injected into the different service classes use the same `DbContext` (I checked it in my app). I think it is save to assume that, in general, the service classes run in different threads, so it can happen that service classes in different threads try to access the database via `UserManager` at the same time, which raises the concurrency issue.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/pull/26874

### For part 1.
The documentation should be clear when it is save to use `UserManager` in a Razor component.

### For part 2.
Identity should check if a `DbContextFactory` (or a pooled factory) is registered and use the factory to inject a `UserManager` with a fresh `DbContext` each time to avoid any concurrency issues. If no factory is defined, the existing `DbContext` can be used as a fallback solution. This change would be in line with the EF Core >5.0 recommendations.

### Steps To Reproduce

It is very hard for me to provide a minimalistic sample. I can try making one if it is really necessary.

### Exceptions (if any)

Unhandled exception rendering component: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable'1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable'1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable'1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.IsInRoleAsync(TUser user, String normalizedRoleName, CancellationToken cancellationToken)
         **at Microsoft.AspNetCore.Identity.UserManager'1.IsInRoleAsync(TUser user, String role)**
         at xxx.Pages.Components.NumericExerciseCard.OnParametersSetAsync() in /src/xxx/Pages/Components/xxxCard.razor.cs:line 480
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### .NET Version

6.0.400

**Comment by javiercn** [comment]
> From my experience, I _can_ inject `UserManager` into Razor components and use it to find the role of the user. So wouldn't it be better to clearly state under which conditions it is save to use `UserManager` in Razor components instead of recommending not to use it at all?

It is not trivial to state this. It is very context dependent, hence why we tell you not to use it, because while you **can** inject it, it is not going to work well in that context.

> I think it is save to assume that, in general, the service classes run in different threads, so it can happen that service classes in different threads try to access the database via `UserManager` at the same time, which raises the concurrency issue.

The problem here is that you initiate multiple queries on the underlying db context, which is not supported. Unlike in ASP.NET Core, in Blazor components can render at the same time, meaning not that they literally are running concurrently but that the framework doesn't wait for asynchronous components to finish rendering before continuing rendering other components.

This is not something ASP.NET Core Identity was designed for and that is why we recommend you avoid it.

**Comment by javiercn** [comment]
I'll let the folks on identity comment on whether they would be willing to change to `DbContextFactory` but I believe it will be a breaking change

**Comment by javiercn** [comment]
If you want a solution that works better with Blazor, you can try to create your own DI scope and resolve the UserManager from that scope. It might make it work for your use case

**Comment by KurtP20** [comment]
Thanks for looking into this. I hope it's not a breaking change.

Instantiating a UserManager myself is scary 😨 , so many parameters to pass to the constructor means long hours figuring out how to do that properly. My solution would have been to wrap UserManager in a DI scope and use a semaphore to exclude concurrent DB access. I use a simpler version with a semaphore now and it seems to work.

**Comment by KurtP20** [comment]
Could you please remove the answered tag, this issue is still open.

**Comment by KurtP20** [comment]
May I please ask if you consider to re-open this case? `UserManager` is not thread safe and should, IMHO, not be used in e.g. Blazor apps without further precaution. At least mention this in the documentation.

In my understanding, I don't see how getting `DbContext` from a factory in `UserManager` should be a breaking change, maybe you can elaborate? I assume that there is no necessity to track changes on a single DbContext across multiple instances of UserManager, so using a new DbContext for every unit-of-work should not break anything.

Regarding your suggestion to instantiate UserManager myself: Maybe you could provide a method to set a new DbContext in UserManager? Or could you please point me to the source code which instantiates UserManger so I can copy it?

I really think this is a bug which should be fixed. Would by nice if you could give it some more consideration.

**Comment by sergekoval** [comment]
Yeah I did rely on injecting  UserManager<T> from my DI container as well. And now after extensive testing I'm getting exceptions like "Invalid operation. The connection is closed".  Have to go back to previous solution creating new one per each operation. Would be nice to have some service factory for it, otherwise too much code to maintain such a basic user management functionality.
