### ISSUE TITLE
Microsoft.AspNetCore.Identity.UserManager.FindByIdAsync is nullable but doc says it is not

### ISSUE THREAD

**Issue by AlessandroMartinelli** [dotnet/aspnetcore#43694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure where I should be reporting this, however I noticed that method 
`Microsoft.AspNetCore.Identity.UserManager.FindByIdAsync()` returns null if no such user is found, and this is coeherent with the return type being `Task<TUser?>` as shown [here](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/UserManager.cs#L532).
Howerver, [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.findbyidasync?view=aspnetcore-6.0#microsoft-aspnetcore-identity-usermanager-1-findbyidasync(system-string)) says return type is `Task<TUser>`, and the same goes the suggestions inside the IDE (I'm using Visual Studio), thus no nullable warning is generated and you may end up raising a NullReferenceException.

I think the documentation should be fixed, but since I'm new to this I'm not sure what I'm saying is correct and I don't dare to correct it myself.

Thanks

### Expected Behavior

code and doc should be coherent

### Steps To Reproduce

Just use the mentioned method giving it as input an id you know no user has. You'll see a null value being returned. Howerver you can notice that Visual Studio says nothing about the return value of this method being nullable.

### .NET Version

7.0.100-preview.6.22352.1

**Comment by adityamandaleeka** [comment]
@AlessandroMartinelli I think you were looking at the docs for 6.0. The 7.0 version of that page shows the `TUser?` as expected: https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.findbyidasync?view=aspnetcore-7.0#microsoft-aspnetcore-identity-usermanager-1-findbyidasync(system-string)

**Comment by AlessandroMartinelli** [comment]
My mistake since in .NET version I've put the output of "dotnet --version", while I've encountered the issue in a project of mine having as target platform .NET 6 with NuGet packges having version 6.0.x as well. I other words, `Microsoft.AspNetCore.Identity.UserManager.FindByIdAsync()` returns `Task<TUser?>` even in .NET 6. Thus, shouldn't also version 6 documentation state this?
