### ISSUE TITLE
Using app.Urls.Add in a hosted Blazor WASM project breaks WebAssembly debugging

### ISSUE THREAD

**Issue by Webreaper** [dotnet/aspnetcore#43703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I converted my project from Blazor Server to Blazor Wasm, but couldn't get WASM debugging to work - it would never hit a breakpoint. I read Khalid's [blog post](https://khalidabuhakmeh.com/troubleshooting-dotnet-blazor-wasm-debugging) on troubleshooting debugging issues, but to no avail. 

He kindly took a look at it and figured out the problem - it seems that my code:
```
            app.Urls.Add($"http://+:{cmdLineOptions.Port}");
```
causes the debugging tooling to break. I changed the code to only use `app.Urls.Add(...)` in a non-dev environment, and added the `[inspectUrl]` setting in the launchsettings.json file, and WASM debugging works, and I can step through the code. Here's the exact commit that fixed it:

https://github.com/Webreaper/Damselfly/commit/419095cae247f4ec1b4aa3ce60e9414cba132294

This problem occurred for me on Visual Studio for Mac v17.3.3, and Khalid also repro'd it on Jetbrains Rider.

### Expected Behavior

I would either expect that:

- `app.Urls.Add` doesn't break WASM debugging or
- A warning is displayed that indicates that it's not compatible.

### Steps To Reproduce

It's reproducible in my app, it is probably reproducible in a simple templated Blazor project.

### Exceptions (if any)

N/A

### .NET Version

7.0.100-preview.7.22377.5

**Comment by Webreaper** [comment]
Quick update to this: if I use the following to set the port, it works fine and does not disrupt WASM debugging:

```
        builder.WebHost.UseKestrel(serverOptions =>  {
            serverOptions.ListenAnyIP(cmdLineOptions.Port);
        });
```

**Comment by javiercn** [comment]
@Webreaper thanks for contacting us.

Seems that your custom configuration breaks the link between the chrome debugger and the server. Unfortunately, it is hard/impossible for us to improve the diagnostics here as we do not get a chance to see that the debugger is not working, since it is the browser the one that initiates the connection, I believe.

It might be that the debugger code running in the browser might produce some messages in the console to indicate this fact.

@Tratcher is there any meaningful difference between the two approaches suggested when configuring Kestrel?

**Comment by Webreaper** [comment]
Yeah, I wasn't sure how easy it would be - as presumably some changes might not break it, depending on the url etc.

I was more thinking that you could just log a warning linking to a KB article that gives people hints as to what best practice might be for debugging - because I'd never have found this solution without Khalid's help!

**Comment by Tratcher** [comment]
The two samples you've given above should behave the same.

@javiercn how does the debugger connect to the server? How does it know which protocol and port to use?
