### ISSUE TITLE
Validation Summary Tag Helper renders style attribute which conflicts with Content Security Policy (CSP) 

### ISSUE THREAD

**Issue by kiwiant** [dotnet/aspnetcore#43714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Validation Summary Tag Helper renders CSS in the style attribute and this is incompatible with Content Security Policy (CSP) unless the 'unsafe-inline' source is used. We all want to be good developers with a security first mindset.

https://github.com/dotnet/aspnetcore/blob/d97ff686a281bcc3fd72a04a3139d97b8285d72e/src/Mvc/Mvc.ViewFeatures/src/DefaultHtmlGenerator.cs
`private const string HiddenListItem = @"<li style=""display:none""></li>";`

Perhaps a design change to remove the hidden element, or allow developers to provide our own classes on the tag helper.

### Expected Behavior

For this to work we would need to add/remove CSS classes from the class attribute (eg, Bootstrap's 'd-none').

### Steps To Reproduce

Create a new Razor view with the Validation Summary tag helper to a page:
`<div asp-validation-summary="All"></div>`

and add the Content-Security-Policy header as follows:
`Response.Headers.Add("Content-Security-Policy", "style-src 'self' 'nonce-xRM/QGGq6lY0/zdMmb6X/C2K4O5vXj+uKtxwDwmpRCs=';");
`
Rendered content looks like this (not the style attribute style="display:none")

```
<div class="validation-summary-valid" data-valmsg-summary="true"><ul><li style="display:none"></li>
</ul></div>

```

Microsoft Edge and other browsers will show this error or similar on the browser console:
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-xRM/QGGq6lY0/zdMmb6X/C2K4O5vXj+uKtxwDwmpRCs='". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
`

### .NET Version

6

**Comment by javiercn** [comment]
@kiwiant thanks for contacting us.

Many of the work we did in tag helpers predates CSP, we will need to think we can do to address this in the future, as it might break existing customers.

**Comment by kiwiant** [comment]
@javiercn agreed hence my suggestion "allow developers to provide our own classes on the tag helper". This would allow a new feature to override the existing behaviour preventing the existing solutions from breaking.

I'm pretty sure one cannot use a nonce or hash when manipulating the style attribute directly. It would need to be part of a script or style with a nonce.

**Comment by mkArtakMSFT** [comment]
Closing this as it will be covered as part of https://github.com/dotnet/aspnetcore/issues/8573
