### ISSUE TITLE
`dotnet user-jwts create` throws exception in rc.1 builds

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#43726]
Can't get `dotnet user-jwts create` to work on latest rc.1 builds.

SDK build: ` 7.0.100-rc.1.22425.9`
Platform: Windows 11 x64

```
> dotnet user-jwts create
Could not load file or assembly 'Microsoft.Extensions.Configuration.Binder, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

The tools install directory indeed doesn't contain the assembly the error message is complaining about:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/249088/188247318-ab3627e0-7481-4f75-8f3b-7f0a9ac924d9.png">

**Comment by DamianEdwards** [comment]
Updated to latest public rc.1 build (`7.0.100-rc.1.22431.11`) and it still repros.

**Comment by davidfowl** [comment]
I can reproduce this as well.

**Comment by davidfowl** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/95136/188733466-2cd343dc-35f6-4f3c-859a-fff837eb058d.png">

**Comment by DamianEdwards** [comment]
Throwing at `SigningKeysHandler.GetOrCreateSigningKeyMaterial`, which uses the [`Get<T>` extension method](https://source.dot.net/#Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs,b4d3072eff1d97dc) out of the binding assembly, but for some reason that project isn't a dependency.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/249088/188736756-46aa075f-a5b3-4788-abe5-6491d4377733.png">

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/43784
