### ISSUE TITLE
NavigationLock with ConfirmExternalNavigation throws exception when prerendering

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#43724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I add a NavigationLock component with ConfirmExternalNavigations to a BlazorServer app I get an exception during prerendering.

### Expected Behavior

Prerendering works when using NavigationLock with ConfirmExternalNavigations.

### Steps To Reproduce

- Create a new Blazor Server app
- Add `<NavigationLock ConfirmExternalNavigations />` to Index.razor
- Run the app

### Exceptions (if any)

InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

### .NET Version

7.0.100-rc.1.22429.3

**Comment by MackinnonBuck** [comment]
Done in #43785
