### ISSUE TITLE
Publish Blazor wasm hosted with x64 Platform on the server results in RuntimeIdentifier compatibility exception

### ISSUE THREAD

**Issue by AB017JH** [dotnet/aspnetcore#43749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys,

The server for the Blazor wasm needs to be published with the x64 Platform due to some dependencies on third-party nuget which is available only with the x64 platform (a condition in its target file)

`dotnet publish .\Test.Server.csproj --configuration Release --framework net6.0 --self-contained True --runtime win-x64 --force /property:Platform=x64`

when running this command I get the result

```
Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(193,5): error NETSDK1032: The RuntimeId
entifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible.
```

All the related issues I found do not provide a solution.

### Expected Behavior

Since it is valid to run this application I would expect that it is valid to deploy it as well.

### .NET Version

6.0.300

**Comment by javiercn** [comment]
@AB017JH thanks for contacting us.

You need to specify the RID as a property in MSBuild `/p:RuntimeIdentifier=win-x64"` as unfortunately, doing so from the CLI overrides the RID in the wasm project and there is nothing we can do so far about it.

**Comment by AB017JH** [comment]
Thank you for the help, the proposed solution results in the same problem. If there is nothing that can be done right now I am satisfied that it gets considered in future planning.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
