### ISSUE TITLE
Summary of FileStreamHttpResult.cs is incorrect.

### ISSUE THREAD

**Issue by ryancronrath** [dotnet/aspnetcore#43744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The FileStream property is a "get" only property yet the summary states "Gets or sets"

```csharp
    /// <summary>
    /// Gets or sets the stream with the file that will be sent back as the response.
    /// </summary>
    public Stream FileStream { get; }
```
Shouldn't the summary state: "Gets the stream with the file that will be sent back as the response." instead?  This way no one thinks they can set this property because of the displayed summary.

File found at:
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Results/src/FileStreamHttpResult.cs

### Expected Behavior

```csharp
    /// <summary>
    /// Gets the stream with the file that will be sent back as the response.
    /// </summary>
    public Stream FileStream { get; }
```

**Comment by javiercn** [comment]
@ryancronrath thanks for contacting us.

This is very likely an oversight on our part. Feel free to send us a PR if you want to contribute a fix.

**Comment by ryancronrath** [comment]
I'd love to create a PR but I need permissions to create a branch in order to submit the PR.  Is this something you can help with @javiercn ?
