### ISSUE TITLE
.Net 7 ApiAuthorization compatibility with Identity Server 6.1.x

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#43741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.net 7 preview 7 ApiAuthorization for Blazor (.AddApiAuthorization() ) isn't compatible with Identity Server 6.1.x

I Needed to rollbaclk to 6.0.4 to make it work.

### .NET Version

.net 7 preview 7

**Comment by javiercn** [comment]
@Julien-Marpault could you give us more details?

What is exactly not working for you?

**Comment by Julien-Marpault** [comment]
Here's a good description of the issue from another one:
https://github.com/DuendeSoftware/Support/issues/203

**Comment by mkArtakMSFT** [comment]
Seems like this is something the Duende Identity Server folks plan to address. We'll close this issue as we don't support the referred version of the identity server yet.
