### ISSUE TITLE
Support F# in blazor projects

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#43771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

FSharp is one supported language of .NET with C# VB

It has its brightness, while blazor is currently interwinding its advantage mixing with front-end and back-end code, it occurs to me that the natural approach to create UI components in object oriented way that everyone agrees combined with the needs for high-quality domain modeling & robust type checking makes Blazor and F# very good friends

Directly referencing F# in blazor currently has difficulties, I don't see why we can't use razor syntax with F# because they are very different

### Describe the solution you'd like

Fsharp finding a way into blazor

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

Razor is highly tied to C# and as a result Blazor is tied too. We do not have plans to add F# support to Razor and as a result we do not plan to do the same for Blazor. There are already other community projects that leverage Blazor within F# like https://fsbolero.io/ which we would recommend you consider using instead.

**Comment by Xyncgas** [comment]
thanks

**Comment by Xyncgas** [comment]
The current way I go for is simply creating an F# project to reduce f# code to something that's friendly for c#
