### ISSUE TITLE
Blazor inherited CssClass property is interpreted as an attribute

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#43779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#inputtext-based-on-the-input-event-3), the following example code for CustomInputText.razor is provided:

```
@inherits InputText

<input @attributes="AdditionalAttributes" 
       class="@CssClass" 
       @bind="CurrentValueAsString" 
       @bind:event="oninput" />
```

When using this code in a fresh app, the `CssClass` property inherited from `InputText` is not processed as expected.

```razor
<CustomInputText @bind-Value="text" CssClass="w-75" />
```

Instead of rendering:

```
<input class="w-75">
```

It renders:

```
<input cssclass="w-75" class="">
```

### Expected Behavior

The example code should render:

```
<input class="w-75">
```

### Steps To Reproduce

Please see [this repo](https://github.com/mrlife/CssClassTest) for a project showing the issue.

### .NET Version

7.0.100-preview.6.22352.1

### Anything else?

.NET SDK:
 Version:   7.0.100-preview.6.22352.1
 Commit:    492644e08e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.6.22352.1/

Host:
  Version:      7.0.0-preview.6.22324.4
  Architecture: arm64
  Commit:       d3fa592f6d

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.400-preview.22330.6 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]
  7.0.100-preview.6.22352.1 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.6.22330.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22324.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by danroth27** [comment]
@mrlife In your project you're trying to use CssClass as a component parameter, but this property is not defined as a component parameter. The `InputText` component does have a protected `CssClass` property that should be used to populate the `class` attribute, but it is not a component parameter, so you can't specify a value for it using the `CssClass` attribute. Instead just use the normal `class` attribute, which will get captured by the `CssClass` property. Like this: `<CustomInputText @bind-Value="text" class="w-75" />`

**Comment by mrlife** [comment]
@danroth27 Thanks so much! That wasn't coming across in what I read in the docs, so I really appreciate the explanation.
