### ISSUE TITLE
Support not starting the SPA dev server when launching the backend

### ISSUE THREAD

**Issue by jesperkristensen** [dotnet/aspnetcore#43795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When I launch a project based on the `dotnet new angular` template it will start the Angular dev server in the background if it is not already running. Angular is very slow to start, so it is annoying to have to restart angular every time I have to restart the backend. Another problem is if there are typescript compile errors, then the Angular dev server will fail to start and the error is not visible anywhere (except when running non-remote on Windows).

If the Angular dev server is already running, then starting the dotnet project will not start the Angular dev server. However the Angular dev server is slow to start, so I have to wait some time after running `npm start` before I can launch the .NET backend, or it will start another Angular dev server in parallel that will compete for the same port depending on which of the two instances finishes starting first.

### Describe the solution you'd like

Make it possible to configure a launch configuration so that dotnet will not run the `SpaProxyLaunchCommand` no matter if it is already running or not. Then some developers can use the default launch setting that starts everything at once, while others can choose the launch configuration where the frontend and backend is launched separately. It could for example be an environment variable that when set disables the `SpaProxyLaunchCommand`.

**Comment by javiercn** [comment]
@jesperkristensen thanks for contacting us.

We are not sure what you are asking for. The behavior that we have today is:
* If the server is running we do nothing.
* If the server is not running we launch it, when the backend stops, the SPA proxy process is also stopped.

On windows we are able to create a new window, unfortunately on other OSes this is not possible. 

How would your solution be different than what we currently have?

**Comment by jesperkristensen** [comment]
The behavior that we have today is:
* If the server is running we do nothing.
* If the server is not running we launch it, when the backend stops, the SPA proxy process is also stopped.
* If the server is starting up we launch it, causing two instances of the server to start (one of them will fail because the port number is already taken).

The behavior that I would like instead is:
* If the server is running we do nothing.
* If the server is not running we launch it, when the backend stops, the SPA proxy process is also stopped.
* If the server is starting up we do nothing.

**Comment by javiercn** [comment]
@jesperkristensen ok, so I think I get it now.

You are starting the spa frontend manually, running the backend and the problem is that we try to launch the frontend again? If you are doing this, you can change launchsettings.json to remove the ASPNETCORE_HOSTING_ASSEMBLIES and that will prevent the backend from trying to launch the SPA server.

Unfortunately, there is not much we can do in this scenario, since we do not have a way (other than probing the URL) to know that the SPA frontend is running, so in these cases the best you can do is what I suggested above I think.

**Comment by jesperkristensen** [comment]
Thanks, that was not easy to find. Adding the following environment variable to my launch settings seems to work:
```
"ASPNETCORE_HOSTINGSTARTUPEXCLUDEASSEMBLIES": "Microsoft.AspNetCore.SpaProxy"
```
