### ISSUE TITLE
Cannot get endpoint metadata from `IApiDescriptionGroupCollectionProvider` which added by `MapXXX().Add(...)`

### ISSUE THREAD

**Issue by wu-yafeng** [dotnet/aspnetcore#43792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Program.cs

``` csharp
// ...
app.MapControllers().RequireAuthorization("api_scope");
// ...
```

WeatherForecastController.cs

``` csharp

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApiExplorer;

namespace DemoApp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
       

        private readonly ILogger<WeatherForecastController> _logger;
        private readonly IApiDescriptionGroupCollectionProvider _provider;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IApiDescriptionGroupCollectionProvider provider)
        {
            _logger = logger;
            _provider = provider;
        }

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            var thisApiDescriptor = _provider.ApiDescriptionGroups.Items.SelectMany(i => i.Items)
                .First(x => x.ActionDescriptor.AttributeRouteInfo.Name == "GetWeatherForecast");


            var metadata = thisApiDescriptor.ActionDescriptor.EndpointMetadata.OfType<AuthorizeAttribute>()
                .ToList();
            // metadata is empty
            return null;
        }

        [HttpGet("2", Name = "GetWeatherForecast2")]
        [Authorize]
        public IEnumerable<WeatherForecast> Get2()
        {
            var thisApiDescriptor = _provider.ApiDescriptionGroups.Items.SelectMany(i => i.Items)
                .First(x => x.ActionDescriptor.AttributeRouteInfo.Name == "GetWeatherForecast2");

            var metadata = thisApiDescriptor.ActionDescriptor.EndpointMetadata.OfType<AuthorizeAttribute>()
                .ToList();
            // metadata is not empty
            return null;
        }
    }
}

```

### Expected Behavior

AuthorizeAttribute should be retived from IApiDescriptionGroupCollectionProvider.Items[x].Items[x].ActionDescriptor.EndpointMetadata;

### .NET Version

6.0.400-preview.22330.6

**Comment by captainsafia** [comment]
@wu-yafeng What are you trying to accomplish by examining the metadata on an action from inside the action method?

**Comment by wu-yafeng** [comment]
> @wu-yafeng What are you trying to accomplish by examining the metadata on an action from inside the action method? It'll help triangulate what the best approach here is.

I'm using a swagger authorize operationfilter:

see [SecurityOperationFilter](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/SecurityRequirementsOperationFilter/SecurityRequirementsOperationFilterT.cs)

**Comment by captainsafia** [comment]
@wu-yafeng Thanks for clarifying!

Also, aha! I see something that I missed in your code sample. You've noted that when the `Authorize` attribute is local to the action, then you are able to inspect it in metadata. However, you are not able to observe the metadata that is added via the `RequireAuthorization` extension method.

The core of this issue is related to the fact that the ApiExplorer APIs are not particularly routing-aware, and as such, they cannot examine any metadata registered on the controller endpoint.

Trying to see if there's a possible workaround here and will update the issue accordingly...

**Comment by wu-yafeng** [comment]
> @wu-yafeng Thanks for clarifying!
> 
> Also, aha! I see something that I missed in your code sample. You've noted that when the `Authorize` attribute is local to the action, then you are able to inspect it in metadata. However, you are not able to observe the metadata that is added via the `RequireAuthorization` extension method.
> 
> The core of this issue is related to the fact that the ApiExplorer APIs are not particularly routing-aware, and as such, they cannot examine any metadata registered on the controller endpoint.
> 
> Trying to see if there's a possible workaround here and will update the issue accordingly...

I have an idea:
https://github.com/dotnet/aspnetcore/blob/991728c729ab6d67e1eb1b5de4329d116b5a83bb/src/Mvc/Mvc.Core/src/Routing/ActionEndpointFactory.cs#L108

``` csharp

var builder = new RouteEndpointBuilder(requestDelegate, updatedRoutePattern, route.Order)
                {
                    DisplayName = action.DisplayName,
                    ApplicationServices = _serviceProvider,
                    Metadata = action.EndpointMetadata
                };

```
