### ISSUE TITLE
Question - Blazor - Best way to narrowly scope ErrorBoundary

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43798]
I've read several [articles ](https://code-maze.com/blazor-webassembly-exception-handling-error-boundaries/)about the scoping of `ErrorBoundary` and I have a question.

If we have a page that could throw an (otherwise unhandled) exception then we can create a _second_ page that "wraps" the first in an `ErrorBoundary` and then only ever render that second page.

The first page is then never _explicitly_ navigated too, only the wrapper is navigated to by the rest of the app.

This is crude, minimal example:

```
@page "/counterwrapper"
<ErrorBoundary>
    <Counter />
</ErrorBoundary>

```
This is a narrow scoping but we'd need a "wrapper" page for every app page that we want to protect with an `ErrorBoundary`.

Is there any other way to structure this idea? to protect each individual page with an `ErrorBoundary' but not have to create a wrapper page for each one?

**Comment by Korporal** [comment]
@javiercn - HI, yes I have tried that and as some of the articles point out though, when we do that the alert is then visible on all pages the user might navigate to. The per-page wrapping solves that but requires a "wrapper" for each page we have. This isn't a huge burden I wanted to check though that there isn't some slicker way.

**Comment by javiercn** [comment]
@Korporal You could have a Layout that provides the error boundary only on the pages that you select.

So you would could have a _Layout.razor layout and a MainLayoutWithErrorHandling.razor layout and the one with error handling itself has a `MainLayout.razor` as the layout. Then on your page you either do not set the layout or set the layout to `MainLayoutWithErrorHandling` using `@layout`. For more info, see https://docs.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0#layout-components

I am not sure I fully grasp your scenario, but hopefully digging through the docs will help you. If you still have issues, please provide a detailed "repro" of what you are trying to achieve.

**Comment by Korporal** [comment]
> @Korporal You could have a Layout that provides the error boundary only on the pages that you select.
> 
> So you would could have a _Layout.razor layout and a MainLayoutWithErrorHandling.razor layout and the one with error handling itself has a `MainLayout.razor` as the layout. Then on your page you either do not set the layout or set the layout to `MainLayoutWithErrorHandling` using `@layout`. For more info, see https://docs.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0#layout-components
> 
> I am not sure I fully grasp your scenario, but hopefully digging through the docs will help you. If you still have issues, please provide a detailed "repro" of what you are trying to achieve.

Thanks, this does sound promising, much appreciated!

**Comment by Korporal** [comment]
Hi, OK thanks I experimented with layouts and needed to understand them anyway, so this was very helpful. We can close this I think.
