### ISSUE TITLE
Question - Blazor - Not all unhandled exceptions lead to developer stack trace page.

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43804]
In a simple Blazor Server project, if an unhandled exception is thrown from say a button click handler, then we get the yellow status bar with "Reload" option. 

![image](https://user-images.githubusercontent.com/12262952/188950146-5703b0ef-cec7-4131-81ec-f270be00f654.png)

But clicking reload does not cause the detailed exception page to render. all that happens is the app seems to reset.

But if an exception is thrown in `OnParametersSet` for example, then again we get the yellow status bar but when we click "Reload" we do get the detailed stack trace!

How can we ensure that **all unhandled exceptions** work the same way, so that we can always get the stack trace no matter where in the component the exception is thrown?

This might be complicating what I see in this related issue: https://github.com/dotnet/aspnetcore/issues/43800

**Comment by javiercn** [comment]
@Korporal thanks for contacting us.

That's by design. Blazor does not run in the context of a request/response, so we can't show the error page with the exception details.

**Comment by Korporal** [comment]
> @Korporal thanks for contacting us.
> 
> That's by design. Blazor does not run in the context of a request/response, so we can't show the error page with the exception details.

Hi @javiercn - I don't fully understand.

Do you mean that unhandled exceptions thrown during rendering can have the stack trace shown, but exceptions thrown after being already rendered (like in button click) are "too late" the response has already been sent?
