### ISSUE TITLE
Question - Blazor - Why is a rethrown exception not causing the developer exception stack trace page to be shown?

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43800]
### This is all Blazor Server.

First I doubt this is a bug, much more likely ignorance on my part!

In a simple app, if we have code that throws an unhandled exception we get the yellow panel shown at bottom of page. In dev mode, clicking "Reload" shows the detailed stack trace page.

But if the exception is thrown within a component that's wrapped by an ErrorBoundary then things seem to break. Consider this code:

```html
@page "/counterwrapper"
<ErrorBoundary Context=ex @ref="errorBoundary">
    <ChildContent>
        <Counter/>
    </ChildContent>
    <ErrorContent>
        <div class="blazor-error-boundary">
            <h5>Exception Alert</h5>
            <h6>On @DateTime.Now.ToLongDateString();</h6>
            <h6>At @DateTime.Now.ToLongTimeString();</h6>
            We're sorry but an unexpected problem arose while preparing to dispaly this page.
            <div >
                <div>@ex.Message</div>
                <div>@ex.GetType().Name</div>
            </div>
        </div>
        <button class="btn btn-warning" @onclick="ResetError">Reset</button>
        <button class="btn btn-danger" @onclick="() => RethrowError(ex)">Rethrow</button>
    </ErrorContent>
</ErrorBoundary>

@code {
    private ErrorBoundary? errorBoundary;

    private void ResetError()
    {
        errorBoundary?.Recover();
    }

    private void RethrowError(Exception ex)
    {
        throw ex; 
    }
}
```

We want to always render a simple panel (which is crude in this test code) that summarizes the exception, date and time and so on. This works, if an exception is thrown inside <Counter> we get this, as expected:

![image](https://user-images.githubusercontent.com/12262952/188923376-de118e49-957b-4d27-a978-cabadee6c8d8.png)

We want this shown irrespective of dev/prod mode, all users will see this production, QA etc, so far so good.

But we also want to enable developers to still see the detailed stack trace if they want, so to get that we rethrow the exception, this also seems to work and we get this:

![image](https://user-images.githubusercontent.com/12262952/188923800-1a709a30-1281-4a30-a5fa-6c178c7f5ccb.png)

But oddly, clicking "Reload" seems to just reset the page, it does not force the detailed stack trace page to be shown. In another page - not wrapped by ErrorBoundary - we get what we expect when we click "Reload":

![image](https://user-images.githubusercontent.com/12262952/188924171-d3da036a-2818-4985-9763-4d65295d4ff8.png)

I want to understand this better and ideally be able to show that detailed page if the developer so chooses.

The app's output when debugged _kind of suggests_ that the circuit is being destroyed when the exception is rethrown:

```
System.DivideByZeroException: Attempted to divide by zero.
   at BlazorApp2.Pages.CounterWrapper.RethrowError(Exception ex) in D:\Git\GitHub\NcuGit\applications\sandbox\Hugh\BlazorApp2\BlazorApp2\Pages\CounterWrapper.razor:line 32
   at BlazorApp2.Pages.CounterWrapper.<>c__DisplayClass0_0.<BuildRenderTree>b__4() in D:\Git\GitHub\NcuGit\applications\sandbox\Hugh\BlazorApp2\BlazorApp2\Pages\CounterWrapper.razor:line 18
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'ZLVdDu3TJNJI5pmCPaPWncfxWHmM7J4c765XWn592Bk'.
```

Thanks!

**Comment by javiercn** [comment]
@Korporal thanks for contacting us.

If you throw an exception from the error boundary handling code, it is "equivalent" as if you throw an exception within a catch block. It does not get caught by the same block.

What is happening in your app is as follows:
* Your app is using ServerPrerrendered.
* The component that has the ErrorBoundary around it, captures the exception and renders the error content. This happened statically on the server.
* Your app connects to the server and becomes interactive. You click on the button and the exception is thrown from the error handling code, resulting in the prompt.
* The page that does not have the error boundary does not catch the exception. Since it is prerendered, the exception flows from MVC (which is handling the prerrendering) to the error page middleware and that is what you get to that page.

**Comment by Korporal** [comment]
OK this now makes sense (yesterday I knew less!) so I think we can close this, many thanks for helping out.
