### ISSUE TITLE
Model-only validation not rendered in absence of model-only errors

### ISSUE THREAD

**Issue by pm64** [dotnet/aspnetcore#43808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue was documented by @bradlis7 in April 2020 (https://github.com/dotnet/aspnetcore/issues/20822), but the issue was closed without being investigated, and is now "locked as resolved and limited conversation to collaborators".

[MS documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0#the-validation-summary-tag-helper) ("Tag Helpers in forms in ASP.NET Core") states that, with respect to a posted model, "when the model is valid", the following CSHTML markup:

```
    <div asp-validation-summary="ModelOnly"></div>
```

is replaced by "the generated HTML":

```
<div class="validation-summary-valid" data-valmsg-summary="true">
  <ul><li style="display:none"></li></ul></div>
```

In reality, at least in frameworks dating back at least to 4/2020, the asp-validation-summary div is actually **removed** from the DOM in the generated HTML. The div with `class="validation-summary-valid"` referenced in the documentation is not present in the generated HTML.

If this is intended, the documentation should be updated. If this isn't intended, it should be fixed.

### Expected Behavior

The documentation should reflect the fact that divs with `asp-validation-summary="ModelOnly"` in CSHTML markup will not be rendered in the absence of model-only errors. Or the framework should render this div in accordance with the documentation.

### Steps To Reproduce

1. Create a new ASP.Net Core Razor Pages project
2. Add a form such as the following to a CSHTML page:

```
<form method="post">
        <div id="generated-HTML-should-be-inside">
                <div asp-validation-summary="ModelOnly"></div>
        </div>
        <input type="submit" />
</form>
```

3. Add a method such as the following to step 2's codebehind:

```
        public async Task<IActionResult> OnPostAsync()
        {
                return Page();
        }
```

4. Run the project. When the form appears in the browser, submit it.
5. Use browser developer tools to inspect div#generated-HTML-should-be-inside
6. Observe that div#generated-HTML-should-be-inside is empty

### .NET Version

3.1-6.0 (7?)

**Comment by mkArtakMSFT** [comment]
This does seem to be something we may have forgotten to update docs with. But leaving here as an `investigation` to validate that before actually doing that.
