### ISSUE TITLE
Security team claims .NET 6 deleted app pools in IIS

### ISSUE THREAD

**Issue by h5aaimtron** [dotnet/aspnetcore#43819]
We installed .NET 6 onto some Windows Servers running IIS as part of our upgrade to some applications. About 2-3 weeks later, the servers (2 of them) both had their application pools deleted. Our security team is claiming it was the .NET 6 install from a few weeks back, we're skeptical.  Even more so as other servers have not had this issue and we cannot find any issues regarding such an incident happening anywhere else. We'd love to get a comment from the dev team on this.

**Comment by davidfowl** [comment]
We're also skeptical 😄, I'm not sure how this would happen.

cc @joeloff @jamshedd @adityamandaleeka

**Comment by h5aaimtron** [comment]
@danmoseley @davidfowl thank you both. I figured I'd ask. Due diligence and all, but I don't buy their explanation, just needed to make sure I wasn't missing something.

**Comment by wtgodbe** [comment]
We're not aware of any way this could be related to the install of the Hosting Bundle.
