### ISSUE TITLE
Make ReactDevelopmentServerMiddleware a more general-purpose middleware

### ISSUE THREAD

**Issue by nandin-borjigin** [dotnet/aspnetcore#43826]
## Summary

Make `ReactDevelopmentServerMiddleware` a more general-purpose middleware instead of working only for `create-react-app` projects.

## Motivation and goals

What `ReactDevelopmentServerMiddleware` are doing are merely:
1. run a npm script (default `npm start`) while providing environment variables PORT and BROWSER
2. wait until "Starting the development server" in the standard output.

However, there are many other SPA tools other than `create-react-app` and we could support them very easily without breaking any backward compatibility.

## In scope

- Abstract existing logics in `ReactDevelopmentServerMiddleware` to a general-purpose development server middleware which is compatible with most state of the art SPA tools.
- Keep the behavior of `ReactDevelopmentServerMiddleware` unchanged to support backward compatibility.

## Out of scope

N/A

## Risks / unknowns

N/A

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

```csharp
in Startup.cs

app.UseSpa(spa =>
{
  spa.Options.SourcePath = "frontend";

  if (env.IsDevelopment())
  {
    spa.UseDevelopmentServer(
      npmScript: "start", 
      envVars: new() 
      {
        { "BROWSER", "none" }
      },
      new Regex("Starting the development server")
    );
  }
});
```

# Detailed design

1. Abstract away the [regex matching](https://github.com/dotnet/aspnetcore/blob/5eabf199fc656ef8613c906d09c1f842cad95e4a/src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L92) and [environment variables](https://github.com/dotnet/aspnetcore/blob/5eabf199fc656ef8613c906d09c1f842cad95e4a/src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L77) (other than PORT). Instead of hardcoding them, receive them as method arguments. In that way `ReactDevelopmentServerMiddleware` doesn't depend on any `create-react-app` specific knowledge and can be general-purpose. 
2. Rename the modified `ReactDevelopmentServerMiddleware` to `SpaDevelopmentServerMiddleware`
3. Create a new `ReactDevelopmentServerMiddleware` that utilizes `SpaDevelopmentServerMiddleware` by providing `create-react-app` specific parameters. (Backward compatibility achieved)

**Comment by javiercn** [comment]
@nandin-borjigin thanks for contacting us.

This is not a direction we plan to move in. We have changed the approach we use for SPAs to avoid requiring framework specific middleware or having to build our own generic middleware to support this scenario.
