### ISSUE TITLE
HAML support

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#43823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to import Haml within Blazor but I couldn't find any documentation how to do such a thing. 

I apologize if there is already a solution for that.

Thanks.

### Describe the solution you'd like

Provide documentation how to integrate haml in Blazor.

**Comment by javiercn** [comment]
@Laftek thanks for contacting us.

There is no official Haml support for Blazor. Blazor uses the Razor syntax and we do not plan to ship alternative rendering engines for the time being. There might be third-party libraries/products that do this; however, we are unaware that such things exist.
