### ISSUE TITLE
Typescript SignalR Client: Reduce error logging for failed connection.

### ISSUE THREAD

**Issue by JeremyMahieu** [dotnet/aspnetcore#43822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm creating my hub connection like this:
```
    const connection = new HubConnectionBuilder()
      .withUrl(`${stuff}`, {
        accessTokenFactory: () => this.token,
        skipNegotiation: true,
        transport: HttpTransportType.WebSockets
      })
      .configureLogging(LogLevel.None)
      .build();
```

It's expected in my application that certain hub don't work at times. However I don't want it to spam the console if it fails to connect. I defined no logging, yet the browser still throws exceptions here and there.

![image](https://user-images.githubusercontent.com/23409814/189078997-84ad1d4c-5ee1-485e-a066-6a84f3e79692.png)

### Describe the solution you'd like

A way to catch and ignore exceptions thrown during connection attempts.

**Comment by javiercn** [comment]
@JeremyMahieu thanks for contacting us.

I'll let the signalr folks chime in, but that is not something logging controls. That is an exception thrown by the client that the browser surfaces in the console. It is not something related to logging, and it is very unlikely that we would change the behavior to avoid throwing exceptions when you have logging set to minimum.

I would further ask, why do you want to have this behavior?

**Comment by JeremyMahieu** [comment]
I don't want the console to be spammed with a giant stacktrace when a hub connection is expected to fail anyway. I agree it's it has nothing to do with logging. But there should be a way to catch these exceptions. There is nothing stopping you from making this exception user handle-able some why.
The exception happens in the `class WebSocketTransport line 49` and not somwhere deep in the browser.

**Comment by javiercn** [comment]
@JeremyMahieu thanks for the additional details.

So, the request seems to be "having some sort of 'global exception handler'" that you can configure to deal with the exception yourself?

Is there a reason why something like this does not work for you?

```js
window.addEventListener('error', (event) => {
    if(event.type === '...' && ...){
        event.preventDefault();
    }
});
```

**Comment by JeremyMahieu** [comment]
First of all this seems very dirty to me to catch every event of the application and then filter out some of them. I tested it and it doesn't seem to catch it with this event, even if I don't put the `if`, it doesn't trigger for these errors.

Also this error event is not cancelable so you can't do `preventDefault`.
https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event

**Comment by BrennanConroy** [comment]
Isn't that error thrown from `await hubConnection.start()`? You should be able to catch it in your code and ignore it if you don't want it shown in the console.

**Comment by JeremyMahieu** [comment]
You're right this gets rid of the second of the errors, thanks you. Any idea about the first one?

```Typescript
this.hubConnection.start().catch(() => {
  console.log('Hubconnection failed to connect.');
});
```

**Comment by BrennanConroy** [comment]
What's the first one?

**Comment by JeremyMahieu** [comment]
This one, most of it is a long url because there's an access token in there.
![image](https://user-images.githubusercontent.com/23409814/189200877-450659b4-fddd-484c-9c2f-2bb46a11d9de.png)
![image](https://user-images.githubusercontent.com/23409814/189201551-de2bacf7-ee07-4cbb-830e-ccc60c254422.png)

**Comment by BrennanConroy** [comment]
Is the websocket constructor throwing? That's annoying if it is... should only throw for url syntax errors according to the docs. But maybe the underlying library has custom behavior.

**Comment by JeremyMahieu** [comment]
It looks like it. Can I do anything to diagnose further?

**Comment by BrennanConroy** [comment]
Add a try catch around the ctor and double check that it's throwing? Also, a stack trace for the error would be nice, I'd like to know what library and where it's throwing.

**Comment by JeremyMahieu** [comment]
I can't seem to get rid of it even if I do a try..catch
```Typescript
if (!webSocket) {
    // Chrome is not happy with passing 'undefined' as protocol
    try {
      webSocket = new this._webSocketConstructor(url);
    }
    catch (e) {}
}
```
![image](https://user-images.githubusercontent.com/23409814/189216846-c56a0171-2711-4e9c-8332-eaa4c6935c17.png)

stacktrace:
![image](https://user-images.githubusercontent.com/23409814/189210685-4f79fc16-3021-43c4-8058-5bcaa496e119.png)

**Comment by BrennanConroy** [comment]
Ok, looking at it more, I believe the error is coming from the browser and isn't something we can influence or catch. It's the same as if you return a 500 or 404 from a GET or POST request.
Firefox:
![image](https://user-images.githubusercontent.com/7574801/189220153-36336b21-a55f-4f8c-abb7-eb50a5486a17.png)
Edge:
![image](https://user-images.githubusercontent.com/7574801/189220281-50cef40b-46b4-4f5a-94cc-3a1b7085fce3.png)

**Comment by JeremyMahieu** [comment]
Ok, thanks for all the help.
