### ISSUE TITLE
Http1AndHttp2 should warn if Tls is disabled

### ISSUE THREAD

**Issue by arontsang** [dotnet/aspnetcore#43837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When TLS is off and Http1AndHttp2 is set in protocol, the developer should be notified that Http/2 will be disabled.

### Expected Behavior

Possibly add a log warning in this section of code telling me that Http/2 was disabled because TLS was switched off, instead of having me run in circles trying to fix my SSL ALPN implementation.

See https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:167

**Comment by Tratcher** [comment]
Note we do not log a warning for this today because Http1AndHttp2 is the default setting, it would cause this warning in most apps on their non-TLS endpoints.

**Comment by wtgodbe** [comment]
Seems reasonable/easy enough to add a Info-level log here: https://github.com/dotnet/aspnetcore/blob/349ddc9b8bf8255166f87899d7905510f362a5d5/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs#L157-L163

**Comment by adityamandaleeka** [comment]
We should only warn if the user has _specified_ HTTP/2 and TLS is off. We don't want the warning in the default case.

**Comment by japui-coder** [comment]
Http1AndHttp2 should warn if Tls is disabled #43837

**Comment by adityamandaleeka** [comment]
@amcasey Can you look into this one? @Tratcher can help get you up to speed.

**Comment by amcasey** [comment]
Hey @arontsang, can you give me a little more context on why you closed this issue?  Is it working as expected now?
