### ISSUE TITLE
`dotnet new blazor` should be an alias for creating a Blazor Server template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#43832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If a user tried `dotnet new blazor` then they get an error, because the actual Blazor template names are blazorserver and blazorwasm.

### Describe the solution you'd like

Make `blazor` and alias for the Blazor Server template.

**Comment by javiercn** [comment]
@danroth27 why blazor server and not wasm?

**Comment by danroth27** [comment]
> @danroth27 why blazor server and not wasm?

For all the normal reasons that make Blazor Server a simpler model to get started with:

- Better .NET compatibility
- Full .NET debugging experience
- Direct access to server resources, like data
- Better runtime performance

These are the same reasons why the Blazor onboarding tutorial on https://blazor.net is based on Blazor Server instead of Blazor WebAssembly.
