### ISSUE TITLE
ControllerLinkGeneratorExtensions throw ArgumentException

### ISSUE THREAD

**Issue by mariusz96** [dotnet/aspnetcore#43845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I think [here](https://github.com/dotnet/aspnetcore/blob/v6.0.8/src/Mvc/Mvc.Core/src/Routing/ControllerLinkGeneratorExtensions.cs#L219) the scheme parameter should be non-nullable.

It throws with `ArgumentException: A scheme must be provided. (Parameter 'scheme')` when I pass null and all the other `LinkGenerator`'s overloads without `HttpContext` require a non-nullable scheme.

### Steps To Reproduce

- create new asp net core web api solution without Swagger
- replace WeatherForecastController with
```cs
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private readonly LinkGenerator _linkGenerator;

        public WeatherForecastController(LinkGenerator linkGenerator)
        {
            _linkGenerator = linkGenerator;
        }

        [HttpGet]
        public string? Get()
        {
            return _linkGenerator.GetUriByAction(
                nameof(Get), 
                nameof(WeatherForecastController).Replace("Controller", ""), 
                null, 
                null, 
                new("localhost"));
        }
    }
```

**Comment by javiercn** [comment]
@mariusz96 thanks for contacting us.

That looks like a bug if it is not consistent with the rest of the overloads.
