### ISSUE TITLE
Configure certificate by thumbprint

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4385]
Would be nice if we could configure server certificates via thumbprint + store name.

Example usage in appsettings.json:

```json
{
  "Kestrel": {
    "Endpoints": {
      "Myendpoint2": {
        "Url": "https://+:443",
        "Certificate": {
          "Store": "CurrentUser/My",
          "Thumbprint": "52A477BBEDE8DFDEB699106D5FFB8FE89F9BF790"
        }
      }
    }
  }
}
```

**Comment by blowdart** [comment]
The problem with thumbprints is it'll allow you to choose an expired certificate. Using subject names is better because it will pull a valid one (assuming it exists), with the longest validity period. Thumbprint selection should die.

**Comment by natemcmaster** [comment]
So, close as wontfix?

**Comment by blowdart** [comment]
I wouldn't go that far, but I wouldn't view this as blocking as you can always resolve the cert yourself before binding kestrel

**Comment by gogroups** [comment]
no matter a good or bad practice , the option to configure using thumbprint should be there !! just a suggestion.

**Comment by Looooooka** [comment]
ok this really should be added. configuring with subject is a pain especially in azure scenarios where again thumbprint is shown...
in fact add Thumbprint and certificateserialnumber because having these options in code and config files has pretty much been "normal" in all net framework options.

**Comment by davidfowl** [comment]
It's @blowdart's call. This is bad practice within Microsoft and you can already do this today with code. The question is should we make it easier via configuration and currently, that answer is no.
