### ISSUE TITLE
How to User Razor in a winform applications

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/aspnetcore#43856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to use RazorEngine in `winform` , `console` and `web` applications to render view to html string。
I found  [Mvc.RenderViewToString](https://github.com/aspnet/Entropy/tree/master/samples/Mvc.RenderViewToString) repo，It only work in `web` application

so，wo should i do ？

### Describe the solution you'd like

Use RazorEngine in `winform` , `console` and `web` applications to render view to html string

**Comment by javiercn** [comment]
@SpringHgui thanks for contacting us.

This is not something we currently support. We have an item in our backlog to productionize this [here](https://github.com/dotnet/aspnetcore/issues/38114)
