### ISSUE TITLE
Application parts manager can't ingest hubs

### ISSUE THREAD

**Issue by Cpt-Falcon** [dotnet/aspnetcore#43859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The application parts manager is only capable of ingesting controllers for shared external assemblies. It should be able to ingest shared hubs as well.

### Describe the solution you'd like

Be able to ingest hubs like controllers

**Comment by javiercn** [comment]
@Cpt-Falcon thanks for contacting us.

ApplicationParts is an MVC feature, not a SignalR feature (if you are referring to SignalR hubs) and there should be no relationship between the two frameworks.

**Comment by Cpt-Falcon** [comment]
> @Cpt-Falcon thanks for contacting us.
> 
> ApplicationParts is an MVC feature, not a SignalR feature (if you are referring to SignalR hubs) and there should be no relationship between the two frameworks.

Why shouldn't there be a relationship? How would you be able to ingest hubs, say, through some kind of plugin system? Right now you can ingest controllers no problem but hubs are not supported. There should be some mechanism to be able to incorporate existing hubs from a plugin.

**Comment by javiercn** [comment]
@Cpt-Falcon because we do not want to couple MVC to SignalR or viceversa, they are different products/parts of ASP.NET Core.

**Comment by Cpt-Falcon** [comment]
> @Cpt-Falcon because we do not want to couple MVC to SignalR or viceversa, they are different products/parts of ASP.NET Core.

How about just not coupling it then? The infrastructure already exists to deal with this exact problem. That's how the application parts manager and feature provider system was designed in the first place, so you don't have to couple.

Create a feature provider in signal R that implements the interface. When the add signal R middleware occurs, it can add to the list of feature providers. Or just force the user to add the feature provider themselves. Then MVC doesn't know anything about SignalR.

**Comment by javiercn** [comment]
@Cpt-Falcon SignalR would still need to reference MVCs dlls, which is not something we want to do.

**Comment by davidfowl** [comment]
We have no plans to decouple application parts from MVC, but I can sympathize with the sentiment that it would be nice to have something that can scan assemblies and find hubs (though it would need to be opt-in). The pattern for SignalR and gRPC is to add hub via a manual call to MapHub\<T\> and MapGrpcServoce\<T\>. We actually prefer that pattern because it solves trimming issues as well (MVC isn't trimmable for several reasons but this is one of them). Assembly scanning isn't something we want to bring to these frameworks.

**Comment by Cpt-Falcon** [comment]
> We have no plans to decouple application parts from MVC, but I can sympathize with the sentiment that it would be nice to have something that can scan assemblies and find hubs (though it would need to be opt-in). The pattern for SignalR and gRPC is to add hub via a manual call to MapHub<T> and MapGrpcServoce<T>. We actually prefer that pattern because it solves trimming issues as well (MVC isn't trimmable for several reasons but this is one of them). Assembly scanning isn't something we want to bring to these frameworks.

Thanks yeah it would be nice to have that. What about something that would enable external plugins to call MapHubs somehow? As an example this is what I have currently:

`        private void LoadPlugins(ApplicationPartManager apm, IServiceCollection isc)
        {
            Type interfaceType = typeof(IPluginBase);
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    Type pluginBaseType = assembly.GetTypes().FirstOrDefault(x =>
                        interfaceType.IsAssignableFrom(x) && !x.IsInterface && !x.IsAbstract);
                    if (pluginBaseType != null)
                    {
                        IPluginBase pluginBaseObj = Activator.CreateInstance(pluginBaseType) as IPluginBase;
                        IDatabaseInitializer dbInitializer = pluginBaseObj?.LoadPlugin(apm, isc);
                        if (dbInitializer != null)
                        {
                            Program.DbInitializers.Add(dbInitializer);
                        }
                    }
                }
                catch (Exception)
                {

                }
            }

        }`

So if I could somehow call MapHub from one of these external plugins, that would also be great, I could get over not having automatic scanning.

**Comment by Cpt-Falcon** [comment]
```
            app.UseEndpoints(x =>
            {
                foreach (IPluginBase plugin in _plugins)
                {
                    plugin.MapHubs(x);
                }
                x.MapControllers();
            });

```

In case anyone else runs into this issue, here is a really ugly solution that works. Save the plugin objects to a local list, then call and loop through them passing through the IEndpointRouter variable. There's no other option available, but this enables the decoupling of hubs at the very least.

**Comment by davidfowl** [comment]
Just copy the pattern that MVC uses,  AddXX() does the scanning and add services that MapXX() can use to locate and use in various ways. I can think of lots of ways to encapsulate it cleanly...

**Comment by Cpt-Falcon** [comment]
> Just copy the pattern that MVC uses, AddXX() does the scanning and add services that MapXX() can use to locate and use in various ways. I can think of lots of ways to encapsulate it cleanly...

I'm not sure what you mean. The application parts manager doesn't do any scanning nor am I aware of any way to do scanning for hubs. Are you suggesting making my own feature provider for application parts to do the scanning? I'd have to investigate because there's no thorough documentation anywhere about making a custom feature provider.

Also MapHub requires a type and a pattern defined, there's no way to dynamically add hubs as far as I'm aware.

Its MapHub<PredefinedType>("pattern"), you couldn't do something like MapHub<variable1>(variable2), since variable 1 would be a compile time error.

**Comment by Cpt-Falcon** [comment]
> Just copy the pattern that MVC uses, AddXX() does the scanning and add services that MapXX() can use to locate and use in various ways. I can think of lots of ways to encapsulate it cleanly...

I'm not sure what you mean. As far as I'm aware there's no way to dynamically add hubs. You first need the IEndpointRouter variable to call MapHub. There's no way to dynamically add hubs either. Its `MapHub<PredefinedType>("pattern")`. If you did MapHub<variable1>(variable2", then it would be a compile error. The plugin must call MapHub itself in order for it to properly register, and that means it needs the IEndpointRouter variable. I don't see how the MVC pattern resolves these issues. Perhaps you can clarify.

**Comment by davidfowl** [comment]
What you say is true but you can clean up the code quite a bit so that it doesn’t need to be expressed in the application that ways. Each “module” can be given access to the IEndpointRouteBuilder instead of calling it directly.

**Comment by davidfowl** [comment]
I nerd sniped myself and wrote this https://github.com/davidfowl/WebApplicationPlugins

**Comment by Cpt-Falcon** [comment]
> I nerd sniped myself and wrote this https://github.com/davidfowl/WebApplicationPlugins

Hey very cool thanks for this, I'm impressed. This is a great reference in general for people looking to incorporate plugins or just decouple parts of the application to prevent a single assembly from getting unwieldy.
