### ISSUE TITLE
Viewing the entire list of registered middleware for the ASP.NET pipeline

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#43871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Now that ASP.NET magically opts in to various middleware (like the developer exception page during development, and stuff registered by `Microsoft.AspNetCore.SpaProxy` when `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` is set), explicitness has been taken away.  You used to be able to examine the `IApplicationBuilder` during startup to actually see what was registered in the pipeline.  Now you can't see these other things that have been injected.

### Describe the solution you'd like

There should be a way to view all middleware that has been registered in the ASP.NET pipline, by whatever means, to get a picture of exactly what will run on each request and in what order.  As not everything is being explicitly registered in a `Startup` class now, there should also probably be a way of removing stuff from the pipeline that you don't want, since you can no longer just remove it from being registered in the first place.

**Comment by Tratcher** [comment]
The explicitness is still available using the old APIs, you're welcome to keep using them if you want low level control of the pipeline.

Have you tried [AddMiddlewareAnalysis](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.analysisservicecollectionextensions.addmiddlewareanalysis?view=aspnetcore-6.0)? This lets you collect details about each middleware a request passes through.

It's true that IApplicationBuilder is not designed for introspection or removal. Middleware pipelines can be constructed in many ways from different kinds of components, it's not just a flat list of uniform modules, so giving visibility and mutability to that is challenging.

**Comment by jez9999** [comment]
@Tratcher Yeah, is that a good direction to be moving in, though?  Formerly I had one place I could look (and debug) to determine all my middleware, and the exact order it was being registered.  I could examine one `IApplicationBuilder` to see all the middleware that was registered and in what order.  I found that very clear and explicit.  I like clear and explicit.  Seems ASP.NET is moving towards lots of automatic middleware injection behind the scenes for the sake of reducing lines of code, a tradeoff I think is not at all worth it.

**Comment by davidfowl** [comment]
Yes it's a good tradeoff, experts can always get to the lower layers of the stack with more advanced APIs as @Tratcher mentions. We've slowly been defaulting a couple of middleware with the ability to turn them off for the most part (with advanced flags). There's a middle ground between too implicit and too explicit that we're trying to balance and I don't think we've done a bad job.

Are you building tooling to inspect the pipeline? It would be nice to get a better understanding of what you are trying to do so we can see if the appropriate feature already exists, or if we need to build one.

**Comment by jez9999** [comment]
OK, well if you can always get to the lower layers of the stack then good, but I wouldn't really call it a tradeoff.  The pipeline can still be fully configured manually.  It's more like you're adding convenience classes on top of that for common use case bundles, which I wouldn't describe as ".NET 6 always opting in to X", because you can write .NET 6 apps that don't opt in.  Perhaps it's a question of terminology.

As for why I prefer not to have the helper classes, well I just have a bunch of complex existing setups that work fine and I don't want the hassle of worrying about whether magically-injected middleware will affect anything.  It may be handy for new projects but it's totally unnecessary for existing ones that work well.

**Comment by davidfowl** [comment]
>As for why I prefer not to have the helper classes, well I just have a bunch of complex existing setups that work fine and I don't want the hassle of worrying about whether magically-injected middleware will affect anything. It may be handy for new projects but it's totally unnecessary for existing ones that work well.

Then use the existing host builder APIs which let you control everything.
