### ISSUE TITLE
Data Annotations Localization does not inherits the resource from base class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43885]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Data-Annotations-Localization-does-not-i/10128842)._

---
I'm currently working with localization and I found that inherited class loses the Data Annotations Localization done on its base class. For example,

```
namespace WebApplication1.Models
{
    public class People
    {
        [Display(Name = "FullName")]
        public string FullName { get; set; }
    }

    public class Librarian : People
    {
        [Display(Name = "Role")]
        public string LibrarianRole { get; set; }
    }
}
```

I have their resources set up as below,
![image.png](https://aka.ms/dc/image?name=Bca70bff241eb4ed1935e1db05a79d260637969040772797095_20220824-101436-image.png&tid=ca70bff241eb4ed1935e1db05a79d260637969040772797095)

![image.png](https://aka.ms/dc/image?name=Bf18c79f59fbc484e99869d29b194ca30637969043820551195_20220824-101941-image.png&tid=f18c79f59fbc484e99869d29b194ca30637969043820551195)

![image.png](https://aka.ms/dc/image?name=B2a019aa21bd741f0a685a4929dd8d04e637969043979778346_20220824-101955-image.png&tid=2a019aa21bd741f0a685a4929dd8d04e637969043979778346)

The property ```FullName``` should be localized to ```Full Name``` while ```LibrarianRole``` should be localized to ```Librarian Role```.

However, when viewing Librarian, only its immediate properties are localized as can be seen in the screenshot below,
![image.png](https://aka.ms/dc/image?name=Be71688cfb0ee4083b298a969e053c67e637969042252781036_20220824-101705-image.png&tid=e71688cfb0ee4083b298a969e053c67e637969042252781036)

I attached the sample project.
[WebApplication1.zip](https://aka.ms/dc/file?name=Bf42d265e6a5b4324ba30f12e817c739e637969042710941107_WebApplication1.zip&tid=f42d265e6a5b4324ba30f12e817c739e637969042710941107)

I found a workaround on this issue at https://cklutz.github.io/2019/01/06/inheritable-string-localizers/. It would be great if ASP.NET Core somehow resolve this internally?

---
#### Feedback Bot on 8/23/2022, 11:03 PM: 

(private comment, text removed)
#### Feedback Bot on 8/24/2022, 03:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hishamco** [comment]
@vsfeedback please create a minimalistic repo (.NET 7) to reproduce the issue

**Comment by hishamco** [comment]
Closing this while there's no respond from the author, feel free to open if you have an update
