### ISSUE TITLE
"IISExpress LaunchUrl" is not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43886]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IISExpress-LaunchUrl-is-not-working/10111713)._

---
[severity:It bothers me. A fix would be nice]
I set in launchUrl the relative page 'game'.

In the appllication profile, it works as expected, showing the 'game' page at https://localhost:44358/game

Doing the same for iisexpress, it loads the index page at https://localhost:44358/game and clicking a link i have there to the same page, goes to https://localhost:44358/game/game showing the 'game' page.

---
#### Feedback Bot on 8/4/2022, 06:33 PM: 

(private comment, text removed)
#### Feedback Bot on 8/5/2022, 02:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
