### ISSUE TITLE
Generic Layout Attribute

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have a component (we've named it `ErrorBarrier`) that is custom implementation of an `ErrorBoundary`. We use an accompanying layout that enables consumers to simply refer to that layout inside their own components and their component then gets "wrapped" within in the `ChildContent` of our `ErrorBarrier`, this enables us to catch and log exceptions and render a UI for the fault and so on.

This works fine but there's no way for a consumer to "tell" our layout to use a further, "outer" layout unless we hard code that inside our layout which makes it impossible to reuse.

So a typical user's component might begin with:

![image](https://user-images.githubusercontent.com/12262952/189434210-2456391a-e141-444e-8f4f-2345ed80b2ce.png)

where that layout might be:

![image](https://user-images.githubusercontent.com/12262952/189434371-1c770c7a-e2bd-424b-b19b-efc319250c34.png)

But we want our component and that layout to be part of our nuget package, but as you can see in this example our layout includes:

```cs
@layout MainLayout
```

But that outer layout is specific to the app, users are free to use any outer layout that they want or not even use any layout - we can't restrict this to something named 'MainLayout'.

### Describe the solution you'd like

With the advent of generic attributes we'd like consumers of our layout to be able to write:

![image](https://user-images.githubusercontent.com/12262952/189435273-d1aeb856-e282-4692-b3bf-6ca312c81e36.png)

This is "telling" the `ErrorBarrierLayout` to use `MasterLayout` without us needing to code that _inside_ `ErrorBarrierLayout`.

I did attempt to craft a new attribute and leverage C#11 generic attributes as a test, but `LayoutAttribute` is sealed so that was a non-starter.

We also want to merge our component and the layout into a single layout component but of course we'll then have the same problem, the component won't be able to be packaged into a nuget package because there's no way to propagate something like `MasterLayout` into that.

We really don't want to share the component as source code for a host of reasons.

### Additional context

Today the only way to express a layout hierarchy is through a set layouts that are chained on to one another, other options might be helpful. Allowing a component to specify a layout with an option to also specify a parent layout solves problems like the one we are facing. Leveraging a generic attribute for this seems ideal, a component could then:

```cs
@layout ThisComponentLayout
```

and

```cs
@layout ComponentLayout<ParentLayout>
```

This would be an alternative to having specify `ParentLayout` _inside_ `ComponentLayout`.

Another possibility is that since a folder, containing a file `_Imports.razor` can include layout directives that are applied to all items in the folder, one could use a folder hierarchy to represent the layout hierarchy.

![image](https://user-images.githubusercontent.com/12262952/189454567-c12d38d0-062a-4645-8cf9-9381bbc8660c.png)

So here the layout specified in the innermost `_Imports.razor` file is applied to `Counter` and `FetchData` but then these in turn have the layout that's defined in the outer `_Imports.razor` file. I tried this and it didn't work but might have some potential as a solution to this problem...

**Comment by javiercn** [comment]
@Korporal thanks for contacting us.

I am not 100% sure, but this might already be possible. 

Do you have an issue making a layout generic with `@typeparam`?

In general, as long as you can close the generic type definition, it should be possible for you to do this. If you are asking to do something like `@layout MainLayout<TSomething>` that is not going to be possible because the type is not closed.

**Comment by Korporal** [comment]
> @Korporal thanks for contacting us.
> 
> I am not 100% sure, but this might already be possible.
> 
> Do you have an issue making a layout generic with `@typeparam`?
> 
> In general, as long as you can close the generic type definition, it should be possible for you to do this. If you are asking to do something like `@layout MainLayout<TSomething>` that is not going to be possible because the type is not closed.

@javiercn - This seemed promising initially but alas not. The type parameter _is closed_ at the time we compile the _app_, but within the nuget package where the ErrorBarrierLayout is defined the type isn't (yet) known so that code will not compile.


![image](https://user-images.githubusercontent.com/12262952/189547700-af39b360-b4c3-451f-8cd7-f0688d777e55.png)

Unless I have misunderstood, this doesn't help us.

**Comment by javiercn** [comment]
@Korporal That is precisely what I was referring to below.

> In general, as long as you can close the generic type definition, it should be possible for you to do this

You could have a type `Layout<T>` and then use `@layout Layout<ConcreteLayout>` but `Layout<TOuterLayout>` is not something you can put in an attribute in C#
