### ISSUE TITLE
Provide accurate message for bad type assignment

### ISSUE THREAD

**Issue by BretMishler** [dotnet/aspnetcore#43898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When trying to bind a controller-returned boolean to a client-side Blazor variable:

```
<EditForm Model="@exampleModel" OnValidSubmit="@HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText id="name" @bind-Value="exampleModel.Name" />

    <button type="submit">Submit</button>
</EditForm>

<li><code>Guess result</code>: @correctGuess</li>

@code {
    private bool? correctGuess { get; set; }

    private async Task HandleValidSubmit()
    {
        Logger.LogInformation("HandleValidSubmit called");

        // Process the valid form

        correctGuess = await Http.GetFromJsonAsync<bool>("GameGuess");
    }
}
```

the value will not bind and the following error is logged to the console.  **Note: does not happen locally. Only running on a dev server does this error occur and the bool value not bind**

> blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> System.Text.Json.JsonException: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, < LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
>    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte )
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
>    Exception_EndOfInnerExceptionStack
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
>    at System.Text.Json.Serialization.JsonConverter`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
>    at System.Text.Json.JsonSerializer.ReadCore[Boolean](JsonConverter , Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
>    at System.Text.Json.JsonSerializer.ReadCore[Boolean](JsonReaderState& , Boolean , ReadOnlySpan`1 , JsonSerializerOptions , ReadStack& , JsonConverter )
>    at System.Text.Json.JsonSerializer.ContinueDeserialize[Boolean](ReadBufferState& , JsonReaderState& , ReadStack& , JsonConverter , JsonSerializerOptions )
>    at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
>    at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__4`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
>    at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
>    at [solutionName].Client.Pages.Index.HandleValidSubmit()
>    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>    at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
>    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

### Describe the solution you'd like

When I update

```
private bool? correctGuess { get; set; }
...
correctGuess = await Http.GetFromJsonAsync<bool>("GameGuess");
```

to

```
private string? correctGuess { get; set; }
...
var result = await Http.GetFromJsonAsync<bool>("GameGuess");
correctGuess = result.ToString();
```

everything worked as expected, with no errors.

If the problem was simply down to bad typing of the correctGuess variable, it'd be really great to have an error message that can communicate that.

### Additional context

Blazor, client-side, running in Azure Linux host

**Comment by javiercn** [comment]
@BretMishler thanks for contacting us.

Unfortunately, this is not something that we control. The exception is happening inside `System.Text.Json`. We would suggest you file an issue in `dotnet/runtime` as they might be able to help.

What are you expecting to happen here? What additional information would be useful to you?
