### ISSUE TITLE
Layouts nested using a folder hierarchy and _Imports files, not working as expected.

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#43906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

This _might_ be related https://github.com/dotnet/aspnetcore/issues/5509

### Describe the bug

Consider the following folder hierarchy, in a Blazor Server project:

![image](https://user-images.githubusercontent.com/12262952/189488974-5d3b2630-7418-43dc-8d4f-492c2b5b70ac.png)

As you can see there are two `_Imports.razor` files, one in the folder `MainLayout` and the other in the folder `Barrier`.

The one in `Barrier` looks like this:

![image](https://user-images.githubusercontent.com/12262952/189489092-7178032f-e446-4187-853a-f1f58c130276.png)

and the one in `MainLayout` looks like this:

![image](https://user-images.githubusercontent.com/12262952/189489130-8c89fd4b-4035-4a1f-8f1c-722d6b621fc7.png)

By _intent_, no layout has an explicit reference to another layout.

### Expected Behavior

My expectation is that the components in the folder `Barrier` would be rendered within a `ErrorBarrierLayout` and then that would be rendered within a `MainLayout`.

That is, I expect the result to be the same as if each component referenced `ErrorBarrierLayout` and then `ErrorBarrierLayout` itself, referenced `MainLayout`.

Instead the components are rendered in the `ErrorBarrierLayout` only, nothing gets nested within `MainLayout`. 

It seems natural to expect this, the documentation for `_Imports.razor` says:

`
Every folder of an app can optionally contain a template file named _Imports.razor. The compiler includes the directives specified in the imports file in all of the Razor templates in the same folder and recursively in all of its subfolders.
`

This seems to imply that we can establish a layout hierarchy using folders just as we can by having layouts refer to other layouts. 

### Steps To Reproduce

The problem is demonstrated in [this public repository](https://github.com/Steadsoft/Blazor).

Run the app and on the left click "Counter" you'll see it is not rendered within the nested layouts implied by the nested folders.

### .NET Version

6.0.400

### Anything else?

If this is not regarded as a bug then perhaps it can be considered as an enhancement. Adding support for this _might_ be a breaking change for some existing projects where `_Imports.razor` files higher up the tree are - effectively - ignored today (by lower components) but would begin to render things as nested if there were `_Imports` files setup appropriately.

The root of the problem is that there seems to be no way to establish layout nesting unless we have layouts _explicitly reference_ other layouts which then makes it very hard to create _reusable_ layouts in nuget packages where we might want to nest _those_ layouts within _other_ layouts that are defined within a (consuming) application project.

_For example in the sample, imagine `InnerLayout` was from a nuget package, how could we nest that inside an `OuterLayout` defined within the application?_

This behavior might be related to this too https://github.com/dotnet/aspnetcore/issues/5509

**Comment by javiercn** [comment]
@Korporal thanks for contacting us.

Unfortunately `_Import.razor` files work at the file hierarchy level. The compiler does not have semantic knowledge of the layouts. (It just converts the thing into an attribute). What you are trying to achieve might work if you do it in the same folder hierarchy, but it won't work if your layout is inside a different folder outside of the hierarchy.
