### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'  bilgiislem.Models.Hesap.Role.get returned null.

### ISSUE THREAD

**Issue by kaanyd** [dotnet/aspnetcore#43911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have correctly established the connection between the account and the Role. I define a role for the account by typing the Id of the Role. But when I try to login to the account I get this error. I could not solve the problem. The code causing the error is:
`claims.Add(new Claim(ClaimTypes.Role, account.Role.Name));`

The error I get is this System.NullReferenceException: 'Object reference not set to an instance of an object.'

bilgiislem.Models.Hesap.Role.get returned null.

Please help me

### .NET Version

.NET 6

**Comment by davidfowl** [comment]
Do you have the entire call stack of the exception message?

**Comment by kaanyd** [comment]
> Do you have the entire call stack of the exception message?

Yes i have. But normally my tables are full. Not null.

**Comment by davidfowl** [comment]
Can you paste it?
