### ISSUE TITLE
I want to perform an optimal search on my database using Tempdata to move the list of search request to the view 

### ISSUE THREAD

**Issue by Damilare1212** [dotnet/aspnetcore#43920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use as key word in my controller but i encouter an error  which i need to build an extension method on Tempdata.

  public static class TempDataExtension
    {
        
            public static void Put<T>(this ITempDataDictionary tempData, string key, T value) where T : class
            {
                tempData[key] = JsonSerializer.Serialize(value);
            }

            public static T Get<T>(this ITempDataDictionary tempData, string key) where T : class
            {
                object o;
                tempData.TryGetValue(key, out o);
                return o == null ? null : JsonSerializer.Deserialize<T>((string)o);
            }
        
    }
// my contoller
public class HealthcenterController : Controller
    {
        private readonly IHealthCenerService _healhCenterService;
        private readonly ApplicationContext _Conext;
        private  readonly ITempDataDictionary _tempDataDictionary;
       

        public HealthcenterController(ITempDataDictionaryFactory fac,   IHealthCenerService healhCenterService, ApplicationContext conext, ITempDataDictionary tempDataDictionary)
        {
            _healhCenterService = healhCenterService;
            _Conext = conext;
            _tempDataDictionary = tempDataDictionary;
        
             
        }

        //        [HttpGet]
        //        public IActionResult Search()
        //        {
        //              var query = from s in _Conext.healthCenters
        //                 where EF.Functions.Like(s.Country, "%Nigeria%")
        //                 select s;

        //                   return View(query.ToList());
        //                    // return View(query );
        //        }

        //   public IActionResult Error()
        //    {
        //         return View(new ErrorViewModel { RequestId = Activity.Current?.Id 
        //         ?? HttpContext.TraceIdentifier });

        //    }
        

        // private  static ITempDataDictionary _tempDataDictionary{get; set;}
        
            
        [HttpGet]
        public IActionResult SearchHealthCentres(   )
        {
            return View();
        }

    

        [HttpPost]
        public IActionResult SearchHealthCentres (string text)
        {
            
          
            
            var searchResults = _healhCenterService.Search(text);
             TempDataExtension.Put<IEnumerable<HealthCenterDto>>(_tempDataDictionary,"searchResults",searchResults.Data.ToList());
            return RedirectToAction("SearchResultsDisplay");
        }

        [HttpGet]
        public IActionResult SearchResultsDisplay()
        {
            var searchResults = TempDataExtension.Get<IEnumerable<HealthCenterDto>>(_tempDataDictionary,"searchResults");
            return View(searchResults);

        }

//my repository
 public IList<HealthCenterDto> Search(string Text)
        {
            return _Context.healthCenters.Where(L => EF.Functions.Like(L.
            Country, $"% {Text} %") )
            .Select(healthCente => new HealthCenterDto 
            {
                      Id = healthCente.Id,
                  Country = healthCente.Country,
                  LocalGovernmentArea = healthCente.LocalGovernmentArea,
                  PostalCode = healthCente.PostalCode,
                  City = healthCente.City,
                  StreetAddress = healthCente.StreetAddress,
                  State = healthCente.State,

                HealthCenterName = healthCente.HealthCenterName,
                Category = healthCente.Category,
                HoursOfWork = healthCente.HoursOfWork,
                healthCenterServices = healthCente.healthCenterServices,
                Email = healthCente.Email,
                WebsiteUrl = healthCente.WebsiteUrl,
                Description = healthCente.Description,
              
                PhoneNumber = healthCente.PhoneNumber ,
            }).ToList();
        }
//my service
  public BaseResponseModel<IEnumerable<HealthCenterDto>> Search(string Search)
        {
           var repo  = _HealhCenterRepo.Search(Search);

           if (repo == null)
           {
              return new BaseResponseModel<IEnumerable<HealthCenterDto>>
              {
                    Measage = "Not Found",
                    Status = false,
              };

           }
           else
           {
              return new BaseResponseModel<IEnumerable<HealthCenterDto>>
              {
                    Data = repo,
              };
           }
           

### Expected Behavior

The Application should run as expected while i perform my search to query my Database 

### Exceptions (if any)

Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataDictionary Lifetime: Scoped VViewFeatures.TempDataDictionary'. ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.HttpContext' while attempting to activate 'Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)

### .NET Version

5.0

### Anything else?

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.10+MySQL8.0.28" />
  </ItemGroup>
// my IDe
vs Code

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
