### ISSUE TITLE
Blazor InputText bind to int

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#43924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The overall idea is to build a inherited component from InputText for autocomplete-
-User searching text, dropdown strings, bind Integer (also nullable)

To encabsulate the issue simple bind a int? to Inputtext
Compiler errror 
CS1503	Argument "2": Konvertierung von `Microsoft.AspNetCore.Components.EventCallback<int>` in `Microsoft.AspNetCore.Components.EventCallback` ..

### Describe the solution you'd like

In any case -it should be possible to bind a number without spinner, as input type text

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by hannespreishuber** [comment]
<EditForm Model="@test" OnSubmit="Save">
    <InputText @bind-Value="test"></InputText>
...
       int test;

**Comment by SteveSandersonMS** [comment]
@hannespreishuber Thanks for clarifying. I appreciate the compiler error is unclear in this case.

There is an input component for numeric types. Please use `<InputNumber>` instead of `<InputText>` in this case.

`<InputText>` supplies strings, so you could alternatively bind to a `string` if you want and then do your own parsing.

**Comment by hannespreishuber** [comment]
at the moment I am working with following idea
`@inherits InputBase<int?>

    <input class="form-control @CssClass"  @bind="@CurrentValue" />

@code {


    protected override bool TryParseValueFromString(string value, out int? result, out string validationErrorMessage)
    {
        int i;
        if (int.TryParse( value,out i))
        {
            result = i;
        }
        else
        {
            result = null;
        }
        validationErrorMessage = null;
        return true;
    }
}`
