### ISSUE TITLE
Blazor wasm application's Hot Reload fails when SignalR is enabled

### ISSUE THREAD

**Issue by cnp5** [dotnet/aspnetcore#43939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whenever I try to enable a SignalR hub on my web api server, blazor wasm application is not able to hot reload.
Visual Studio Hot Reload output shows:

11:44 31.60 Starting session.
11:44 33.27 BlazorWebAssemblySignalRApp.Server (Web server): Hot reload session started
11:44 41.11 BlazorWebAssemblySignalRApp.Server (Web assembly): Hot reload session started
11:45 05.07 Checking for updates...
11:45 05.17 Applying updates...
11:45 05.17 BlazorWebAssemblySignalRApp.Server (Web assembly): Sending updates to running application
11:45 05.17 BlazorWebAssemblySignalRApp.Server (Web assembly): [Error] Applying updates failed: The connection to the web browser was lost.
11:45 05.17 An unexpected error has occurred, any pending updates have been discarded.

As soon as I remove SignalR references from Server's Program.cs and restart the application, Hot Reload works again with no issues.

### Expected Behavior

Should be able to use hot reload and signalr in blazor wasm applications.

### Steps To Reproduce

- Clone\download sample project from dotnet blazor [samples](https://github.com/dotnet/blazor-samples).
- Open solution file BlazorWebAssemblySignalRApp.sln in BlazorWebAssemblySignalRApp folder of version 6.0 samples.
- Run the application and as soon as it loads, make a change on Index.razor page, try to hot reload (if not enabled on file save).
- Hot reload will popup an error saying that it needs to restart the application and the Hot Reload log should say that an error occured and it has lost connection with the web browser.

Now, stop the application and comment out the OnInitializedAsync function in Index.razor of blazor wasm application.
Next open file Program.cs of Server application and comment out the following lines (9, 10-14, 20 and 40):

> builder.Services.AddSignalR();
> builder.Services.AddResponseCompression(opts =>
> {
>     opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
>         new[] { "application/octet-stream" });
> });
>...
> app.UseResponseCompression();
>...
> app.MapHub<ChatHub>("/chathub");

Restart the application and perform a change in Index.html, it should work without issues, in case it does not try to force reload the application with Ctrl-F5 or open the inspect app of chrome/edge and delete the wasm application and retry to load, again hot reload should work just fine.

### .NET Version

6.0.400

### Anything else?

ASP.NET Core version: 6.0.8

Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.3.3

Browser Microsoft Edge: Version 105.0.1343.33 (Official build) (64-bit)

**dotnet --info output:**
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by javiercn** [comment]
@cnp5 thanks for contacting us.

Could you provide more information to help us make progress on the issue?
* Use the --verbose flag watch provides and include the additional logs.
* Turn Microsoft.AspNetCore.Watch.BrowserRefresh logs to Debug level (in appsettings.development.json) on the Server project and include the logs.

**Comment by cnp5** [comment]
@javiercn enabled the Microsoft.AspNetCore.Watch.BrowserRefresh on server project
Hot Reload output is the same (from VS)

> 12:53 58.66 Starting session.
> 12:54 00.27 BlazorWebAssemblySignalRApp.Server (Web server): Hot reload session started
> 12:54 08.15 BlazorWebAssemblySignalRApp.Server (Web assembly): Hot reload session started
> 12:54 29.47 Checking for updates...
> 12:54 29.52 Applying updates...
> 12:54 29.52 BlazorWebAssemblySignalRApp.Server (Web assembly): Sending updates to running application
> 12:54 29.56 BlazorWebAssemblySignalRApp.Server (Web assembly): [Error] Applying updates failed: The connection to the web browser was lost.
> 12:54 29.56 An unexpected error has occurred, any pending updates have been discarded.

Attaching the debug output from the server [Debug.log](https://github.com/dotnet/aspnetcore/files/9555877/Debug.log)

![image](https://user-images.githubusercontent.com/4385232/189873018-8082b3af-5407-439b-b6a2-079f0cd479d6.png)
The image shows the Network connections the application has established, missing both dotnet, hot reload and .net websockets and only having the chathub websocket (this was after a refresh of the page, dlls where already installed).

Also attatching the log when I run the application using dotnet watch --verbose
The application detects the change (see line 234) but does nothing else... just stops and lines 235 and bellow are after 1 minute of wait when I pressed Ctrl-C to stop the process.
[dotnet-watch.log](https://github.com/dotnet/aspnetcore/files/9555945/dotnet-watch.log)

**Comment by cnp5** [comment]
I am not sure how the whole process is working but after experimentation I managed to get Hot Reload working again.
I had to remove the AddResponseCompression and UseResponseCompression parts and after starting the application, I need only to refresh once (Ctrl-F5) in order to get hot reload working again. If I don't full refresh, I get the dirty edit warning.
In my case adding UseResponseComprassion, always breaks hot reload.

**Comment by javiercn** [comment]
@cnp5 it's the `UseResponseCompression`. It prevents us from injecting the script.

We improved this in .NET 7.0 to give a warning when this happens.

**Comment by cnp5** [comment]
If that is the case and UseResponseCompression is not "compatible" with blazor's injection scripts, then the documentation and aspnet samples should change.

Currently, both .net 6 & 7 documentation, states that we should use response compression, at least that's what I understand reading them.
[Use ASP.NET Core SignalR with Blazor(.net 6)](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly)
[Use ASP.NET Core SignalR with Blazor(.net 7)](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=webassembly)

**Comment by javiercn** [comment]
> If that is the case and UseResponseCompression is not "compatible" with blazor's injection scripts, then the documentation and aspnet samples should change.

We just recently discovered this a couple of weeks ago. It's not Blazor injection scripts, it's the infrastructure we have to support HotReload. You can put UseResponseCompression inside an `if(!env.IsDevelopment())` block.

@guardrex can you add a note to the docs for this?
