### ISSUE TITLE
Blazor Input Type Password Password Reveal

### ISSUE THREAD

**Issue by CLX-BDeaton** [dotnet/aspnetcore#43945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a blazor web assembly app, the input type password is not letting the browser show the eye. I have confirmed it works on other sites and is not a permission issue. The issue is also seen here [Similar Issue](https://github.com/dotnet/aspnetcore/issues/24474)

This is based on the following feature [Edge Browser Reveal](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)

This was done in a blazor, web assembly, .net core hosted, http app.

Note: If you put the input in the body (outside of the div id="app") then it will work. It is only appears to be an issue on razor components.

### Steps To Reproduce

Create a new blazor web assembly, .net core hosted web application. (.net 6)
Add <input type="password" id="pwd" name="pwd" minlength="8"> to the index.razor component
Notice the eye reveal button does not show when a user starts typing.

### .NET Version

.net 5 & .net 6

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
