### ISSUE TITLE
The scoped css file 'Views\Shared\_Layout.cshtml.css' was defined but no associated razor component or view was found for it.	Fake.Web	D:\dotNet\FakeMelySite\Fake.Web\Views\Shared\_Layout.cshtml.css	1	

### ISSUE THREAD

**Issue by althepal78** [dotnet/aspnetcore#43967]
I am not using blazor at all. I basically copied over a project to work on getting rid of scaffolding to razor pages because to me they are so many that it is not worth using them. I only really need login and register, for now, All these Identity pages are useless as of right now. I also prefer using controllers vs a page and a controller for each page that is stupid as hell IMO but Microsoft must have good reasons for this. My layout was made in MVC project and the copied version is also an MVC project I don't get the issue

**Comment by javiercn** [comment]
@althepal78 thanks for contacting us.

There is a bug in the error code as the feature was originally introduced for Blazor, but the feature is available for MVC and Razor Pages too since 6.0. We might have just missed updating the error code.

Do you not have a _Layout.cshtml inside Views\Shared\?

**Comment by javiercn** [comment]
@althepal78 thanks for the additional details.

Just to make sure that we understand, you are no longer seeing the issue after you cleaned/rebuild/redid the project, are you?

**Comment by althepal78** [comment]
No I didn’t clean or rebuilt the project. I totally deleted it and created a whole new project copied and pasted the code from a different project. I’m trying to use a few controllers vs having 29 razor pages with 29 controllers in the bg

**Comment by mkArtakMSFT** [comment]
@althepal78 it's not clear if you're still facing this issue. Did it go away after you've removed the offending content, or is it still there?

**Comment by althepal78** [comment]
> @althepal78 it's not clear if you're still facing this issue. Did it go away after you've removed the offending content, or is it still there?

I literally deleted it I said that already and redid it

**Comment by MackinnonBuck** [comment]
@althepal78 It's not clear what the current issue you're facing is. If the issue is with the footer positioning, this sounds like a CSS problem. If you're experiencing some other issue, could you please describe what it is and provide us with a minimal repro project, hosted as a public GitHub repository? Thanks.
