### ISSUE TITLE
Live preview Blazor

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/aspnetcore#43963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

live inspect for tracking CSS changes in browser and set there in visual studio
but usually we don't want all of changes in browser for this problem we can to take inspect element and live preview window in visual studio that is written in MAUI and have webView2 and tracking any changes and apply to code and have state manager(something like vue dev tools)

**Comment by javiercn** [comment]
@sajjadarashhh thanks for contacting us.

We would recommend you file this issue through the [Suggest a feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022) dialog in Visual Studio to get a better and faster answer.
