### ISSUE TITLE
Blazor CultureInfo.CurrentCulture Always Returning en-US

### ISSUE THREAD

**Issue by legistek** [dotnet/aspnetcore#43977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm attempting to test my application's localization for international users and as such attempted to change all my (Windows 11) computer and browser settings to UK language, region, etc. (I am physically in the US).

Nonetheless, `CultureInfo.CurrentCulture` is always returning `en-US` and formatting dates accordingly.

I note that the Javascript `Date.toLocaleString` function returns dd/mm/yyyy formatted dates. I would have thought that Blazor would use the same culture as Javascript, since of course Blazor doesn't have access to OS settings.

I also note that I explicitly set `InvariantGlobalization` to `false` in the project settings.

If others do not have this problem, perhaps someone could kindly confirm exactly which Windows and/or browser settings are needed for the Blazor C# runtime to return the correct culture?

Thanks!

### Expected Behavior

I would expect that `CultureInfo.CurrentCulture` would return `en-GB`.

### Steps To Reproduce

`Console.WriteLine($"Current Culture: {CultureInfo.CurrentCulture.Name}");`

### .NET Version

6.0.300

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've just confirmed that `CultureInfo.CurrentCulture` returns the culture on a machine on a non-english machine. Have you followed the guidance provided in our docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0?

If you still believe that you're doing everything right and you are still facing the issue, please share a minimal repro project hosted as a public GitHub repo.

**Comment by legistek** [comment]
Thanks @mkArtakMSFT, I did review that documentation. As I mentioned I even explicitly set `InvariantGlobalization` to `false` even though that shouldn't be needed.

I can post a project but in the meantime can someone confirm what machine setting(s) are being used by the runtime to determine what constitutes a "non-english" machine? I've changed the Language and Culture settings in Windows 11 in every place I could find them, and changed my preferred browser language to English UK. What else needs to be changed on the machine for the Blazor runtime to return a different culture value?

**Comment by legistek** [comment]
I can't reproduce this in the skeleton project. 
I did, however, discover that in my project it only occurs when the debugger is attached. When I run without debugging it shows en-GB.
Can anyone offer any ideas why having the debugger attached would change the culture value being returned by `CurrentCulture`?

**Comment by legistek** [comment]
Ok it turns out (at least for Chrome) the browser language setting is the only thing that matters. In this case the language has to be installed and then you have to select "Display Google Chrome in this Language". The operating system language settings appear to have no effect.
