### ISSUE TITLE
[Blazor] localStorage.getItem errors with complex objects

### ISSUE THREAD

**Issue by JonathanShrek** [dotnet/aspnetcore#43974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a fairly complex object that I want to store in local storage. The object gets set in local storage, but when I go to get the item from local storage I get a pretty generic error and the server hangs and dies.

"Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'."

### Expected Behavior

To be able hold more complex objects in local storage and retrieve them without an error.

### Steps To Reproduce

https://github.com/kobrien603/BlazoredLocalStorageErrorExample

### .NET Version

6.0.101

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Maybe you're exceeding the SignalR message size limit? Here is a relevant issue with a proposed solution: https://github.com/Blazored/SessionStorage/issues/51

**Comment by JonathanShrek** [comment]
Thanks for the quick response! The proposed solution actually resolved my issue. Is there Microsoft documentation anywhere that talks about adjusting the SignalR message size limit? I feel like I have looked high and low trying to fix this issue and didn't see this as a source of my problem.

**Comment by guardrex** [comment]
The Blazor docs cross-link to the SignalR docs for `MaximumReceiveMessageSize` ...

https://docs.microsoft.com/aspnet/core/signalr/configuration#configure-server-options

**Comment by TanayParikh** [comment]
Thanks @guardrex for providing the link.

@JonathanShrek please note, for security reasons, it's recommended to keep the max message size small. 

@guardrex @BrennanConroy  should we add some documentation in https://docs.microsoft.com/aspnet/core/signalr/configuration#configure-server-options / https://docs.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-6.0 about avoiding large `MaximumReceiveMessageSize`s?

**Comment by guardrex** [comment]
Blazor docs only cross-link to SignalR docs for it, merely showing it in a code example. I can't speak to the SignalR side; but if some Blazor coverage is best for this, I can add something like the following. It turns out that Steve's Blazor threat mitigation guidance already lists the setting in its DOS section, so I can cross-link that, too.

> [!WARNING]
> We recommend setting \<xref:Microsoft.AspNetCore.SignalR.HubOptions.MaximumReceiveMessageSize> to a small value in order to limit the risk of \[Denial of service (DoS) attacks](xref:blazor/security/server/threat-mitigation#denial-of-service-dos-attacks). The default value is 32 KB (32,768 bytes).

... under the example code at the end of the section ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#circuit-handler-options-for-blazor-server-apps

**Comment by TanayParikh** [comment]
> You can let me know here if you agree with the update 👂. 

Taking a look...
