### ISSUE TITLE
Angular universal with .net 6 

### ISSUE THREAD

**Issue by Eslam-95** [dotnet/aspnetcore#43970]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

Hello , I have created .net 6 project with angular and it was all working fine till i had to make the angular app run as SSR so i installed required package and setup everything put when i try to run it from microsoft visual it's not working ,  tried to change startup command and fallback file path and the build command and everything possible but nothing seems to work , so i was wondering if there is something i had to do inside the .net to compile the angular ssr or what is the required steps for it keeping in mind that i am trying to deploy it on azure and on azure it doesn't recogize it at all either . thanks in advance

### Expected Behavior

i expected that when i install angular universal the app will get same behavior or i get the option to run both whether it's ssr or aot , but when i did it doesn't recognize the angular universal at all 

### .NET Version

6

**Comment by javiercn** [comment]
@Eslam-95 thanks for contacting us.

We do not have SSR support in the templates. That requires running node inside of the .NET process which we stopped supporting a few releases ago. See https://github.com/dotnet/docs/issues/14958. 

There are third-party community packages that fill this gap that you can use.

**Comment by hanykamel** [comment]
@javiercn , what is the third party package that fixes this issue

**Comment by Eslam-95** [comment]
@javiercn  thanks for your response , but i have one more question regarding the third party package , i have tried this article [https://pieterjandeclippel.medium.com/server-side-rendering-in-asp-net-core-angular-2022-version-7aaed8157976](url) followed its steps cautionly and it lead to nothing , it didn't work locally either on azure so any advice or recommendation about any other thing i can use to get them owrking together , thanks in advance
