### ISSUE TITLE
FindByEmailAsync in the UserOnlyStore is not actually an Async call

### ISSUE THREAD

**Issue by conrad-roux** [dotnet/aspnetcore#43973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The call made in the [UserOnlyStore](https://github.com/dotnet/aspnetcore/blob/05b2afb73b55b11d8cb3691dedfebba1f0285332/src/Identity/EntityFrameworkCore/src/UserOnlyStore.cs) for the method [FindByEmailAsync](https://github.com/dotnet/aspnetcore/blob/05b2afb73b55b11d8cb3691dedfebba1f0285332/src/Identity/EntityFrameworkCore/src/UserOnlyStore.cs#L498) is not implementing an async method, but the method does in fact have an Async post-fix to the name so I would expect the method to implement an async task.

### Expected Behavior

I would expect to see a `SingleOrDefaultAsync` instead of the used `SingleOrDefault` similar to what was done in the [UserStore](https://github.com/dotnet/aspnetcore/blob/05b2afb73b55b11d8cb3691dedfebba1f0285332/src/Identity/EntityFrameworkCore/src/UserStore.cs#L630) with the same method name

**Comment by WingZer0123** [comment]
@conrad-roux I am not a member of the .NET team. However, this method as you can tell uses Task.FromResult so the operation still runs in a Task that the consumer can use a GetAwaiter on higher in the call stack.

**Comment by springy76** [comment]
this method blocks threadpool threads when the IQueryable tries to talk to a busy database server or the connection has problems and it takes 2 seconds to fix the code. What are you waiting for??

**Comment by cremor** [comment]
I've also noticed this. Seems like it was initially changed to a sync call as a workaround in #10660 by @ajcvickers. A part of the workaround was later removed in #11336 (again by @ajcvickers), but it stayed a sync call. Even later `UserStore.FindByEmailAsync` was made async again in #24116 (for #24113) by @HaoK, but the `UserOnlyStore` was not fixed.
