### ISSUE TITLE
Debug blazor server/wasm 

### ISSUE THREAD

**Issue by bryp** [dotnet/aspnetcore#43989]
Hello aspnetcore,

When I debug blazor server project, new browser window opens with chrome bookmarks bar, login avatar, dev tools settings, etc. intact as show in the screen cap below.
![image](https://user-images.githubusercontent.com/141313/190246863-98aa8c93-bba3-426d-98fb-fd15f3e1db31.png)

But when I debug blazor wasm, new browser opens yet chrome bookmarks bar, login avatar, dev tools settings, etc are lost and not available as shown in the screen cap below.
![image](https://user-images.githubusercontent.com/141313/190247689-a7b46dca-2a83-4f30-8533-d5b542b09a2f.png)

How can I configure wasm debugging such that chrome login, settings, etc are available like as in blazor server debugging.

Thank you.

**Comment by TanayParikh** [comment]
Hey, thanks for reaching out. Please follow the guidance in the "Visual Studio" section of the following documentation page:

https://docs.microsoft.com/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio

More details are also available in https://github.com/dotnet/aspnetcore/issues/20915#issuecomment-614933322.

**Comment by bryp** [comment]
Sounds good. Thank you for the quick response!
