### ISSUE TITLE
Support for pagination

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#44008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's quite common to have applications, which present lists of records in one or another way.
The examples in real life are endless - spanning from showing grid of images to a list of flat data records.

Many times, those records are much more than it makes sense to show on a single page. Some developers choose to have paged solutions, while others support infinite-scrolling, which behind the scenes would work in a similar fasion.

Currently, there is no native / standard way of supporting pagination, so every application developer will need to come up with their own solution. It would be great to provide a standard mechanism for doing this.

### Describe the solution you'd like

While this doesn't seem to be a big issue, and is relatively easy for developers to do, standardization would help as it hopefully will be utilized with other Microsoft services too.
The simplest form I can think of is introduction of these two APIs:

```csharp
public class PageRequest
{
  public int StartIndex {get;set;}
  public int Count {get;set;}
}

public class PagedResponse<T>
{
  public List<T> PageResults {get;set;}
  public bool MoreRecordsExist {get;set;}
}
```

The two simple types would allow developers to now standardize their APIs as follows:
(I assume even this could be optimized and made even nicer :) )
```csharp
public Task<PageResponse<T>> RetrieveResults(CustomRequest request, PageRequest request)
{
 // ...
}
```

### Additional context

As I've mentioned above, I don't have any specific proposal, this was just an example. But I want this issue to serve as a seed for thinking about standardizing the notation of exposing data paging capabilities through APIs.

**Comment by TanvirArjel** [comment]
This should not be part of ASP.NET Core anyway. Let it belong to the developers.

**Comment by rafikiassumani-msft** [comment]
Triage: @mkArtakMSFT Should this be an ef core feature and not aspnet core?

**Comment by mkArtakMSFT** [comment]
I'm not sure. I think we should backlog this for now to accumulate more feedback. When / if we get enough signal indicating that this would indeed be valuable, then we can decide where this belongs. For now, I think it's safe to keep it here.

**Comment by davidfowl** [comment]
High level questions on scope (I mentioned these to @mkArtakMSFT):

- Are we going to own the protocol? What's the request and response format for requested paged data and paged results? (like odata)
- Do we expose a public API for input and output?
- Have you looked at what other services do today? I know the Azure and the Azure SDK has a solution to this problem as they have written generic clients that support paging, but what about other apps/services?
- Do you expect this to be client and server work?
    - Do we build an API on top of fetch or axios (JavaScript client)
    - Do we build an API on top of HttpClient

**Comment by pinkfloydx33** [comment]
FWIW I don't think this should be owned here. I think there's enough variations of this pattern out in the wild which warrants keeping it seperate. 

For example, we use page-size (count) + page-number in the inbound query string. Of course index and page-num can be expressed in terms of each other so not too different. But we also let endpoints enforce a max-page-size using Data Annotations where necessary. 

On the response-side however, we:
- don't add an envelope/wrapper around the list
- return "total pages" via a header 
- return "total count" via a header
- return the urls of first/next/prev/last page via `Link` header

We're not going to update all our existing apps/endpoints to change any of that, nor would we use different formats across services (so new apps would still need to use the "old" style). We also use an interface for pagination that we stick on our query parameter types; we can then use that in conjunction with paging helpers we have for EF/LINQ. If this is brought in box we'd have nowhere to add that interface. I certainly don't want to bring in a reference to aspnetcore in my data libraries for the proposed PageRequest type (they're used outside of asp) so I'd likely need to do some mapping between framework types and my own types. 

My point is that there are certainly many variations of paging out in the wild. It's not a one size fits all pattern. Sure, folks can opt to *not* use the built-in tools, but I believe it's wrong for ASP to become opinionated on the matter--especially when there's no "right way" or RFC I'm aware of. It's simple enough for a user to implement on their own.
