### ISSUE TITLE
This is by design. `FromBody` uses serializers such as Newtonsoft.Json which have a different feature set compared to model binding. Model binding - indicated by `FromQuery`, `FromRoute` etc, requires that complex types have a parameterless constructor.

### ISSUE THREAD

**Issue by MrAntix** [dotnet/aspnetcore#44006]
This is by design. `FromBody` uses serializers such as Newtonsoft.Json which have a different feature set compared to model binding. Model binding - indicated by `FromQuery`, `FromRoute` etc, requires that complex types have a parameterless constructor.

_Originally posted by @pranavkm in https://github.com/dotnet/aspnetcore/issues/9781#issuecomment-488288308_

**Comment by MrAntix** [comment]
Hello, is this still the case?
If so, would you expand the explanation so we can understand why [FromQuery] has this limitation and [FromBody] does not?

Thank you

**Comment by davidfowl** [comment]
Model binding supports record types now but not models shaped like the issue you've linked to. The reasons `[FromBody]` is different because it delegates to output formatters and does not use the rest of the model binding system.

You should now be able to do this:

```c#
[HttpGet("fancy")]
public async Task<IActionResult> Find([FromQuery] FancyQuery query)
{
   // TODO: add some action
   return Ok();
}

// DTO
public record FancyQuery(int UserId, int DumbValue);
```

**Comment by MrAntix** [comment]
Thanks for that.

Unfortunately we need to support .NET Standard 2.0, and get a compiler error when trying to use records. I understand there is a work around, but haven't tried that.

So supporting immutables via constructor parameters in [FromQuery] is coming, and/or I shouldn't hold my breath, or not going to be implemented?

Also, query string data is pretty similar to form encoding, does the [FromBody] handle immutable objects here? 

Would it be possible to use that code for a binding the query string data (with encoding tweekage)?

Ta
