### ISSUE TITLE
What is the difference between AddHttpClientInstrumentation and AddAspNetCoreInstrumentation

### ISSUE THREAD

**Issue by candrewtemenoscom** [dotnet/aspnetcore#44033]
To support OpenTelemetry tracing, in asp.net core, to provide auto trace instrumentation, we can do the followings.

services.AddOpenTelemetryTracing(providerBuilder =>
{
providerBuilder
.AddSource("TemenosInsightDataService")
.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("InsightDataService"))
.AddHttpClientInstrumentation()
.AddAspNetCoreInstrumentation()
.AddSqlClientInstrumentation()
.AddConsoleExporter()});

After reading the limited documentation on github, I still quite understand the purpose and difference between them. It seems to me their main purpose is to allow Enrich function to be called to add additional information to activity. I can do that on both AddHttpClientInstrumentation() and AddAspNetCoreInstrumentation() which will both add to trace context. How to choose which one to use?

**Comment by BrennanConroy** [comment]
Shouldn't this question be posted at https://github.com/open-telemetry/opentelemetry-dotnet where these methods are implemented?

**Comment by davidfowl** [comment]
Agree with @BrennanConroy, these are open telemetry APIs and the issue should be filed on that repository. 

cc @noahfalk
