### ISSUE TITLE
Blazor @key not working when inside RenderFragment or Repeater like component

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#44039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've made a minimal demo with explanation here: https://blazorfiddle.com/s/36l3slbr
there are 2 issues:
1) I'm modifying the order of divs with js and invoking server method to do the same to the corresponding server items, after `StateHasChanged` the items get into an unexplainable order. 
The **fix** is to give these divs an `@key`.
2) The `@key` fix works, but if the div with key is inside a `RenderFragment`/ChildContent (in my real case was a Repeater like component) than it doesn't work anymore

### Expected Behavior

I was hoping that the `@key` fix would work even when it inside other components.
I was also hoping that the key would not be necessary, but I suppose you have to sync/merge somehow the server and js dom changes.

### .NET Version

6

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us.

You should bear in mind that `@key` is scoped, so it's only relevant among direct siblings in your element/component hierarchy. If you wrap each list item in some intermediate element, then those list items are *not* direct siblings and so the `@key` values cease to have any effect. So it sounds like things are behaving as expected.

As a solution, I would recommend **not** mutating the DOM using JS as you have described. Doing that is unsupported and can lead to any number of problems.

If you were doing this DOM mutation as a way of implementing drag-and-drop, I would recommend setting up your drag-and-drop system to avoid auto-changing the DOM and instead just notify you what reordering the user has requested. At that point you can change the underlying .NET object model and Blazor will take care of updating the DOM in a supported way.

**Comment by omuleanu** [comment]
@SteveSandersonMS I wanted to confirm if it's not a bug,
I can revert DOM changes (remove drag placeholder, unhide dragged obj) before calling server and it works without `@key`,
but I get a *Blink* effect (unhide() => dragged obj shows up back; after render where it was placed),

The `@key` works much nicer.
