### ISSUE TITLE
Receive an error alert pop when I debug a fresh BlazorWasm app in VS Code

### ISSUE THREAD

**Issue by jammerware** [dotnet/aspnetcore#44057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I attempt to debug a freshly-created BlazorWasm app, the debug browser appears, but my app is not loaded, and I get the alert shown below.

### Expected Behavior

Expect no error alert after the debug browser is open and my app to be loaded by the browser for debugging.

### Steps To Reproduce

1. Install the version of .NET Core described below.
2. Install Visual Studio Code in user setup configuration.
3. Run `dotnet new blazorwasm -o SomeDirectory`
4. Open VS Code in SomeDirectory
5. Press F5.

### Exceptions (if any)

Excuse the screenshot, but I can't seem to get this text from anywhere else when the problem occurs:

![image](https://user-images.githubusercontent.com/296034/191036072-e4372503-e1a4-4498-bec2-9959b247a739.png)

### .NET Version

6.0.401

## IDE
Visual Studio Code 1.71.2 (user setup)

## `dotnet --info`

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

## My `properties/launchSettings.json`

```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:45599",
      "sslPort": 44323
    }
  },
  "profiles": {
    "HiBlazor": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:7258;http://localhost:5178",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

## My `.vscode/launch.json`

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

**Comment by TanayParikh** [comment]
Hey @jammerware, just to confirm, have you gone through the additional documentation available here: https://learn.microsoft.com/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio-code

**Comment by jammerware** [comment]
@TanayParikh I'm so sorry. I couldn't find this documentation, but once I followed it, everything was good. Thanks for your help!
