### ISSUE TITLE
.NET 7 RC1 blazor WASM size regression

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#44060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to update .NET 6 prototype to .NET 7 RC1 and i notice significant size increase is that expected with .NET 7?

dotnet.wasm.br went from ~786.9 KiB to ~952.9 KiB
System.Private.CoreLib.dll.br 403.9 KiB -> 510.6 KiB
_framework/icudt_EFIGS.dat.br 145.7 KiB -> 194.6 KiB

Overall increase from 3,672 KiB -> 4,325 KiB

<img width="349" alt="image" src="https://user-images.githubusercontent.com/7279825/191059436-47670df9-b6b1-4b00-ae2c-21c50881d871.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/7279825/191059475-c5cd8457-47a1-4dbf-8a08-a890f56c53db.png">

Also I notice that `--blazor-load-percentage` is added to HTML tag and it seems base on build in browser profiler that is cause "Recalculate style" several times during loading. This isnt issue when it is standard WASM app but with prerendering enable its add some delay (correct me if I am wrong).

<img width="560" alt="image" src="https://user-images.githubusercontent.com/7279825/191058599-e7862483-7988-45a7-b1fd-f32f97c6c023.png">

### Expected Behavior

I expect that new version of .NET improve both performance and size of the app.

### .NET Version

7.0.100-rc.1.22431.12

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There are two things involved here.
For the size regression that you mentioned, we are aware of an issue causing it and it's being worked on already: https://github.com/dotnet/sdk/pull/27659

As for the load percentage, it is expected for the styles to be recalculated. We think 17ms is an acceptable time. If we get more customer feedback about this being an issue, we will consider doing something about it.

**Comment by jirisykora83** [comment]
Thank you for more information about size regression I glad it will be solved.

For style recalculations it is not 17ms it is 17ms for each time the property is updated what is in my (still "smaller" app 12x times).

Also that time is with last desktop i7 with older laptop its seems as it take 2x more (still with compounding of 12 calls during cold startup). And also with relatively small DOM (just ~280 elements). I expect it will be more for more common bigger page.

I am not frontend dev so I do not know if this is actually count as part of "Total Blocking Time" or "Time to Interactive".

![image](https://user-images.githubusercontent.com/7279825/191117535-ee4cf728-9883-4e24-aac4-25227e78f1e5.png)

![image](https://user-images.githubusercontent.com/7279825/191117610-b2fac4b9-a81c-4679-8ebd-e5e1aeca5ae7.png)

this is from run on laptop (8550u). from that 270ms is about 200ms updating `--blazor-load-percentage` with small DOM and okish laptop for older phone it should be more in absolute term (in percentage still about ~5%).
