### ISSUE TITLE
WebApplication.RunAsync does not accept a cancellation token

### ISSUE THREAD

**Issue by alex-ht-work** [dotnet/aspnetcore#44083]
The documentation says: "Runs an application and returns a Task that only completes when the token is triggered or shutdown is triggered", But the token is not in the method parameters.

The underlying `HostingAbstractionsHostExtensions.RunAsync` accepts a token, so it is not a problem to pass it, it was probably just  forgotten.

**Comment by adityamandaleeka** [comment]
Triage: this is an interesting idea. You can work around this by calling [`IHostApplicationLifetime.StopApplication`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime.stopapplication?view=dotnet-plat-ext-6.0#microsoft-extensions-hosting-ihostapplicationlifetime-stopapplication).

We could probably do what you're suggesting, and internally call `WaitForShutdownAsync` in response to a cancellation.

**Comment by alex-ht-work** [comment]
> this is an interesting idea

I would not call it an "idea". It is more like a 2-lines quick non-breaking bugfix. Look:

Instead of 

https://github.com/dotnet/aspnetcore/blob/e13e3facfb26643fe580be56f2d3f466cd5ee009/src/DefaultBuilder/src/WebApplication.cs#L145-L149

We put
```
    public Task RunAsync(string? url = null,  CancellationToken token = default)
    {
        Listen(url);
        return HostingAbstractionsHostExtensions.RunAsync(this, token);
    }
```

I really don't think it has to wait until .NET 8... Or am I oversimplifying? 

Also, about a workaround: I used `Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync`, which is an extension method on `IHost`, and it works on `WebApplication` because `WebApplication` implements `IHost`. Sadly, I can not pass the URL to listen on this way, but there are other ways to set it.

**Comment by adityamandaleeka** [comment]
@alex-ht-work Yes, it's not necessarily a complex change. However, we're not taking any more changes into .NET 7 at this point unless they are critical bug fixes, which is why I put it in the .NET 8 milestone.

**Comment by davidfowl** [comment]
This should be converted to an [API proposal](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=&template=20_feature_request.yml)

**Comment by freddyrios** [comment]
as an outsider that just ran into this, it is a bit surprising this would be an API proposal / not taking a token when calling into an API that takes a token seems like a mistake in the first place.

**Comment by mitchdenny** [comment]
Closing this issue in favor of #50042 which is in the form of an API proposal.
