### ISSUE TITLE
JavaScript to C# argument passing achieves a whopping 235 kb/s of throughput

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [dotnet/aspnetcore#44088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We create and prime a 1M entry array of floats (`Float32Array`) in JavaScript.

We pass this via `invokeMethod` as the only argument (`float[]`) to a C# object method. 

A single invocation of the method takes 17 seconds, most of it before we even enter the C# method.

### Expected Behavior

We would like to be somewhere close to Emscripten's C++ performance which is 2250x faster (all while using `Array`).

First of all making Float32Array JSON serializable would probably help (but ofc not ideal).

235kb/s is less than:
- my 30 year old OG PCI slot running at 33Mhz
- almost less than USB 1.1
- a floppy disk
- my first ADSL internet connection when I moved to the UK

#### Insights

The `converter_ssss` munches through about 40MB of temporary memory allocations to serialize our 4MB of floats and pass them to emscripten.

### Steps To Reproduce

Detailed benchmark and writeup is here:
https://github.com/Devsh-Graphics-Programming/JS-WASM-interop-benchmark

### Exceptions (if any)

None

### .NET Version

6.0

### Anything else?

Reopens #26287

This guy https://www.meziantou.net/optimizing-js-interop-in-a-blazor-webassembly-application.htm has a 100ms overhead on passing a small string around, I guess the issue has been around before but no one noticed how bad it is till now.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
Your current repro project contains much more than the minimum required content, hence the ask.

**Comment by devshgraphicsprogramming** [comment]
Client agreed to make the repro public, here you go:
https://github.com/Devsh-Graphics-Programming/JS-WASM-interop-benchmark

**Comment by devshgraphicsprogramming** [comment]
@mkArtakMSFT can you reopen the issue?

**Comment by mkArtakMSFT** [comment]
Per @javiercn 's comment [here](https://github.com/dotnet/aspnetcore/issues/45107#issuecomment-1315533208), please try the alternative JS interop mechanism and see if that avoids the performance problems that you're experiencing.

**Comment by SteveSandersonMS** [comment]
> We pass this via invokeMethod as the only argument (float[]) to a C# object method.

That's probably the issue. If you pass a `float[]`, it will be JSON-serialized, which has a vast overhead compared with what you're doing in C.

I'd recommend you try a similar comparison but passing a `byte[]` instead of a `float[]`. Note that you can reinterpret a float array as a byte array on the .NET side using some logic like `MemoryMarshal.Cast<float, byte>(myFloats)`.

If you need lower-level control still, then I would definitely recommend what @javiercn suggests above.
