### ISSUE TITLE
[NetSDKE2E]With NET7 RC2 installed, a duplicate template display in dotnet new --list

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#44095]
Environment: 7.0.100-rc.2.22466.28(runtime-7.0.0-rc.2.22464.1)
Repro steps:
1.Install 7.0.100-rc.2.22466.28(runtime-7.0.0-rc.2.22464.1) on Loc OS
2. dotnet new --list in CLI.
3. check the template displaying

Actual Result:
a duplicate template display in dotnet new --list

EN:
![image](https://user-images.githubusercontent.com/65637796/191227682-8639014e-d16d-4210-9c0b-7a245d5e4966.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/191227821-c385ef87-d338-46ef-8e1f-a94b40bdd2db.png)

JP:
![image](https://user-images.githubusercontent.com/65637796/191228002-fa44e26a-d987-42a2-b135-2a62836af67b.png)

**Comment by dougbu** [comment]
I note a number of strings have changed fairly significantly between 6.0.x and 7.0.x in their English forms. Probably best to fix the `groupIdentity` of the `protobuf` item template and make the `identity` and `precedence` settings unique everywhere. Doesn't sound like it'll hurt to err on the side of caution.

@captainsafia do you want to take updating the `groupIdentity`, `precedence`, and `identity` settings in the templates where that hasn't been done yet?

**Comment by phenning** [comment]
It also looks like the CLI list command is de-duping the list on ENU, since the names of the templates match. On non-ENU, the 6.0 template still has english strings, so the names are distinct.

@vlada-shubina is the CLI template list supposed to de-dupe template that have the same name, but different group identities, or is this behavior between 6.0/7.0 protobuf template a bug?

**Comment by vdanche** [comment]
Below two templates area also dup.
e.g (JP)
![image](https://user-images.githubusercontent.com/65637796/191395536-6578ddb8-d39e-4479-a7e7-4348ebe544a6.png)
EN:
![image](https://user-images.githubusercontent.com/65637796/191395577-101169cd-ee3f-4bc9-b8a5-02fd8834b86f.png)

**Comment by vlada-shubina** [comment]
> @vlada-shubina is the CLI template list supposed to de-dupe template that have the same name, but different group identities, or is this behavior between 6.0/7.0 protobuf template a bug?

That's correct behavior. One line in the table corresponds to unique `groupIdenity`. We don't group the template from different group identities.

**Comment by dougbu** [comment]
> Ideally, the 7.0 template identities should be updated to 7.0 along with updating the precedence, however, this isn't strictly necessary if the templates don't have different breaking content per TFM. (They currently don't AFAIK)

What change to `precedence` values are you suggesting @phenning❔ It's easy enough to backport #37919 and make sure all `identity` values end w/ `.7.0`. But I'm not understanding the `precedence` part.

The `precedence` value in our project templates went from `8000` to `9000` between 6.0.x and 7.0.x but the item templates stayed at `100` for Web.Client.ItemTemplates.csproj and `600` for Web.ItemTemplates.csproj`. Is that fine as-is❔ (Not worried about making changes in 'main' yet.)

**Comment by vdanche** [comment]
> 

Got it, Thanks dougbu. filed a new bug([#10251](https://github.com/dotnet/maui/issues/10251)) for maui-dict-xaml duplication.

**Comment by dougbu** [comment]
Resolved by #44120 in 7.0-rc2

**Comment by vdanche** [comment]
The issue not repro on Version 17.4.0 Preview 3.0 [33011.327.d17.4] + 7.0.100-rtm.22511.20 SDK
![image](https://user-images.githubusercontent.com/65637796/195290500-6c3d3d05-bffc-4a9e-93b3-42ae52fb8df2.png)
