### ISSUE TITLE
Opensource but why has not source?

### ISSUE THREAD

**Issue by thanhnghiacntt** [dotnet/aspnetcore#44101]
https://github.com/dotnet/aspnetcore/blob/ce2db7ea0b161fc5eb35710fca6feeafeeac37bc/src/Mvc/Mvc.Core/src/Filters/ActionFilterAttribute.cs#L54

**Comment by davidfowl** [comment]
This is the default implementation of the action filter. If you're looking for the piece of code that executes filters then you need to look elsewhere:

https://github.com/dotnet/aspnetcore/blob/ce2db7ea0b161fc5eb35710fca6feeafeeac37bc/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs
