### ISSUE TITLE
[NetSDKE2E][Loc]With VS 17.4 preview 3 + NET7 RC2 installed on Local OS, the template "ASP.NET Core with React.js and Redux" is inconsistent with EN's template in dotnet new --list.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#44104]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Environment: 17.4.0 Preview 3 [32920.363.main] + 7.0.100-rc.2.22466.28(runtime-7.0.0-rc.2.22464.1) on Loc OS and EN OS
Repro steps:
1. dotnet new --list in CLI.
2. check the template displaying

we found the template ""ASP.NET Core with React.js and Redux"" display in Loc OS, not EN
EN:
![image](https://user-images.githubusercontent.com/65637796/191470844-3f0ddcd1-af4d-4169-b6f7-48390db8fdd6.png)
e.g DE:
![image](https://user-images.githubusercontent.com/65637796/191470911-40791338-805f-4fc2-af8b-836257d43107.png)
SC:
![image](https://user-images.githubusercontent.com/65637796/191471900-c4b611ea-024c-4673-ab6f-9841fa4b580f.png)

### Expected Behavior

The template should be consistent with EN.

**Comment by dougbu** [comment]
I see the `reactredux` template on my English machine. It's surprising to hear you're seeing an inconsistency between languages on yours.

I'm also surprised to see English text for the name of this template in the German list. The translation exists and is included in the Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0 package.

This template was completely removed before 6.0.0 was released. What you're seeing is a 5.0.x or older template that may contain bugs, but those bugs are really old, and no customer has reported them. I suggest we ignore the problem.

Thoughts @mkArtakMSFT @TanayParikh❔

**Comment by vdanche** [comment]
> I see the `reactredux` template on my English machine. It's surprising to hear you're seeing an inconsistency between languages on yours.
> 
> I'm also surprised to see English text for the name of this template in the German list. The translation exists and is included in the Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0 package.
> 
> This template was completely removed before 6.0.0 was released. What you're seeing is a 5.0.x or older template that may contain bugs, but those bugs are really old, and no customer has reported them. I suggest we ignore the problem.
> 
> Thoughts @mkArtakMSFT @TanayParikh❔

Yes, so weired. My test config is VS 17.4 preview 3 which carry net7 RC 1 by default + NET7 RC2 SDK,  reactredux template not displays in EN, but displays in Loc OS and template is not localized.

**Comment by mkArtakMSFT** [comment]
@dougbu is right, this template is not shipped any more nor we plan to address this issue given that we've deprecated the template.

@vdanche how did you get that package installed though, is the question. Do you have 5.0 or 3.1 on your machine?

**Comment by mkArtakMSFT** [comment]
Also, please share the output of `dotnet new -u` here. That may also help.

**Comment by vdanche** [comment]
> 

@mkArtakMSFT Do you have 5.0 or 3.1 on your machine? we re-check this and install 5.0 or 3.1 via VS, the template "ASP.NET Core with React.js and Redux" is consistent in EN and Loc. Thank you.
![image](https://user-images.githubusercontent.com/65637796/192181876-9076033d-d407-493f-ab3c-0e5c98f95ed3.png)

**Comment by MackinnonBuck** [comment]
Hi @vdanche, that looks like the output of `dotnet new list` - could you please try `dotnet new -u` and reply with your output? Thanks.

**Comment by vdanche** [comment]
@MackinnonBuck @mkArtakMSFT the output is displayed as below for dotnet new -u
EN
![image](https://user-images.githubusercontent.com/65637796/193235092-be9f2108-1550-4c2c-aa8f-03bd0e957a0d.png)

German
![image](https://user-images.githubusercontent.com/65637796/193235010-57bdc219-6ae1-4046-a589-5d4f9829bf44.png)

**Comment by mkArtakMSFT** [comment]
After some further discussion we think this is a very low priority work. For 3.1 we're only addressing critical issues (which this is not) and 5.0 is out of support already.
