### ISSUE TITLE
Using Lottie in Blazor

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#44109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to use Lottie in Blazor and it should be straightforward but I guess I am doing something wrong.

I followed this:
https://lottiefiles.com/blog/working-with-lottie/how-to-add-lottie-animation-in-web-page-html/

Using <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> in _Layout throws error because of "@" character -> I put one more to escape it -> but result is empty lottie player with yellow warning triangle instead of animation.

I thought its maybe because of double @ character so I just copied whole script locally to scripts.js and import it in _Layout but the same result -> empty lottie player with yellow warning triangle instead of animation.

Is there any known workaround or guide what should I do?

### Expected Behavior

To display lottie animation.

### Steps To Reproduce

Create blazor project and folow https://lottiefiles.com/blog/working-with-lottie/how-to-add-lottie-animation-in-web-page-html/

### .NET Version

7.0.100-rc.1.22431.12

**Comment by TanayParikh** [comment]
Hey @Laftek, thanks for reaching out. Are you seeing any errors in the developer tools console? Based on what you describe this appears to be a Lottie issue than Blazor.

**Comment by migueln1** [comment]
It worked for me with the double @. Probably is a problem with your animation's JSON.

![image](https://user-images.githubusercontent.com/3620634/191657389-48a7e2cd-0b5c-4571-8957-c9e2e5b37ad6.png)

![image](https://user-images.githubusercontent.com/3620634/191657498-9bc9f1f0-21f6-4438-9e0c-cdfed81ec1f4.png)

![image](https://user-images.githubusercontent.com/3620634/191657561-98a85ed1-e710-4e75-8aad-f81ec8ba81cf.png)

**Comment by Laftek** [comment]
You are right, I messed up 2 characters in the link. Now its working! Thank you!
Also its working with WASM/MAUI (dont forget to call script OnAfterRenderAsync)

**Comment by Ekkohng** [comment]
> You are right, I messed up 2 characters in the link. Now its working! Thank you! Also its working with WASM/MAUI (dont forget to call script OnAfterRenderAsync)

Can you show an Example, I'm trying to unsuccessfully replicate it.
