### ISSUE TITLE
Blazor Wasm ASP.NET Core Hosted IWebHostEnvironment.WebRootPath null when debugging

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#44110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The IWebHostEnvironment.WebRootPath is null when debugging an ASP.NET Core hosted Blazor wasm application. This makes it very difficult to wire up an logic such as additional static file handlers for sub folders of wwwroot. The value is present in a published build.

### Expected Behavior

IWebHostEnvironment.WebRootPath should contain be patched through to the wwwroot directory of the client project.

### Steps To Reproduce

1. Create an ASP.NET Core Hosted Blazor Wasm project using the default template.
2. Add a breakpoint after line 15 in Program.cs of the Server project.
3. The app.Envionrment.WebRootPath is null.

Publish the application and run the same procedure and the directory is not null.

### .NET Version

6.0.401

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This looks like a by-design behavior.
Here is an explanation for what's happening and why: https://github.com/dotnet/aspnetcore/issues/41929#issuecomment-1152664535
