### ISSUE TITLE
TR @onclick only after tabbed

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#44112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can not click with mouse but tab with finger to fire SetBinding

following code
```razor
 <div class="dropdown-menu show" style="position: absolute; ">
        <table class="table table-hover">
            <tbody>
            @foreach (var item in Liste)
            {
                <tr class="hover-overlay" 
                @onclick="()=>SetBinding(item.Key)">
                    @foreach (var td in item.Value.Split("|"))
                    {
                        <td>@td</td>
                    }
                </tr>

            }
            </tbody>
        </table>

```

After ontime finger tab. also mouse click works

### Expected Behavior

mouse click should fire @onclick event 

### Steps To Reproduce

question - how to investigate in bound JavaScript bridged events?

### .NET Version

net 6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please clarify what does `ontime finger tab` mean?

**Comment by mkArtakMSFT** [comment]
Also, could you please create a repro using https://blazorrepl.telerik.com/ and share it with us, so that we can observe the behavior too. Thanks!
