### ISSUE TITLE
Blazor template first link fills whole horizontal space inside top-row

### ISSUE THREAD

**Issue by Jimmys20** [dotnet/aspnetcore#44133]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In Blazor templates with authentication enabled the whole top-row is clickable because the first anchor element fills the entire horizontal space.

![2sulr](https://user-images.githubusercontent.com/34100964/191862680-bcbcc8f9-17c8-46f6-9703-9d6185cf13ce.jpg)

This happens because of this style: https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/MainLayout.razor.css#L72

### Expected Behavior

Anchor tag should not be clickable outside its text.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We'll consider this as part of #40935, if we get to it earlier. Otherwise, feel free to send us a PR with a fix, and we'll take it earlier.

**Comment by mkArtakMSFT** [comment]
Closing as we plan to update the templates in .NET 8 and this will change too.
