### ISSUE TITLE
Blazor Css Sandboxing Error with current VS version 17.3.4

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44149]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Css-Sandboxing-Error-with-current/10154243)._

---
I have a Blazor project with dots in its name, GRP.Commercial.MyWebApp. At least with the latest update of VisualStudio to 17.3.4, I now observe that the sandboxed css-file GRP.Commercial.MyWebApp.styles.css is built correctly (as before), but now the runtime is looking for the file MyWebApp.styles.css, which does not exist.

If it's not a bug, there should be a command setting to control the name of the sandboxed file to be loaded.

---
#### Feedback Bot on 9/21/2022, 08:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Did you happen to rename the project after creation?
The CSS bundle file is linked from the default project template when the project is created: https://github.com/dotnet/aspnetcore/blob/b02a2f1c88bdd752cc7d5de3b7af941c6eee5976/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/_Host.cshtml#L14

So it maybe that you've renamed the project and forgot to rename the filename. Can you please confirm?
