### ISSUE TITLE
`[directory]` not shown in installation bundle help

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#44167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Help for the Shared Framework and Windows Hosting bundles shows two spaces after `/layout` rather than `/layout [directory]`. This happens because Wix interprets `[directory]` as a template string and substitutes nothing because a corresponding variable is not set.

### Expected Behavior

`/layout [directory]` shown in the help UI.

### Steps To Reproduce

For example, `.\dotnet-hosting-7.0.0-rc.1.22427.2-win.exe /help` and observe the UI.

### Anything else?

Current UI:
![image](https://user-images.githubusercontent.com/6431421/192117902-c5588d48-5845-4179-865c-691910850241.png)

**Comment by dougbu** [comment]
@dotnet/aspnet-admins
1. What area label is appropriate for these bundle installers are they included in `area-commandlinetools`❔
2. The fix for this is dead easy. Should we backport it to at least 7.0.0 or earlier❔ Note that, as far as I know, no customer has reported the problem. I just noticed it while working on locking some of the installer strings from localization.

**Comment by wtgodbe** [comment]
> What area label is appropriate for these bundle installers are they included in area-commandlinetools❔

`area-installers`


> The fix for this is dead easy. Should we backport it to at least 7.0.0 or earlier❔ Note that, as far as I know, no customer has reported the problem. I just noticed it while working on locking some of the installer strings from localization.

I think we should backport to all servicing branches, seems low-risk & it's an improvement on the experience.
