### ISSUE TITLE
Get child tag by name

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#44163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a tag helper with 2 child 

```
- ParentTag
    - Child1Tag => <h1> I am child 1 </h1>
    - Child2Tag => <h1> I am child 2 </h1>
```
 
I want get content Child1Tag but haven't any function for this task.   
Only we can use `await output.GetChildContentAsync();` 
This function only return all content root parent . 

### Explain by code:

**ParentTag output**
```
<div>
    <h1> I am child 1 </h1>
    <h1> I am child 2 </h1>
</div>
```
 
I want get only output **Child1Tag**
 
 
   

### Describe the solution you'd like

We must create a function work like [querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll)

Example: 
```
 - output.QuerySelectorAll('.your-css-class')
 - output.QuerySelectorAll('your-id-tag')
 - output.QuerySelectorAll('tag-name')
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
