### ISSUE TITLE
ContentRangeHeaderValue "to" must always be less than "length"

### ISSUE THREAD

**Issue by Mertsch** [dotnet/aspnetcore#44166]
## Summary
The `ContentRangeHeaderValue` constructor allows the creation of an invalid (range) instance.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range
`<range-start>` and `<range-end>` are *zero-indexed & inclusive*
This means that `to` must always be a maximum of `length - 1`

## Motivation and goals
Prevent people (like me) to create invalid content range headers.

## In scope
None.

## Out of scope
None.

## Risks / unknowns
People sending invalid requests to forgiving servers might be broken.

## Examples

I think this line https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Http/Headers/src/ContentRangeHeaderValue.cs#L41
Should be changed from
`if ((to < 0) || (to > length))`
to
`if ((to < 0) || (to > Math.Max(0, length-1)))`

**Comment by Tratcher** [comment]
Would you like to submit a PR for this?

**Comment by ilmalte** [comment]
If @Mertsch doesn't want to work on this, I would be happy to! 😄

**Comment by Mertsch** [comment]
@ilmalte Go for it :-)

**Comment by ilmalte** [comment]
May you provide me the test case that is failing for you so I can implement it in the tests? @Mertsch

Also, if I look at the code I see the function expects long parameters.
https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Http/Headers/src/ContentRangeHeaderValue.cs#L33

An [Int64](https://msdn.microsoft.com/en-us/library/system.int64(v=vs.110).aspx) (aka [long](https://msdn.microsoft.com/en-us/library/ctetwysk.aspx)) is a signed integer with 64 bits (8 bytes) of space available, this means no floating point.

If we only have an integer value and there is a "guard" on the variable _length_  for values less than zero, 
the `Math.Max(0, length - 1)` proposed should not be required and `length - 1` should be enough, right?

The actual code for reference:
https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Http/Headers/src/ContentRangeHeaderValue.cs#L37-L48

**Comment by Mertsch** [comment]
Since `length`,`from`,`to` can be 0 I think we need to guard against that special case. A 0 request is probably senseless, but 🤔

I can not give you an easy test case, as I was working with the Graph API https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#step-2-use-the-upload-session-to-upload-a-range-of-bytes-of-the-file and you would not have access to my tenant 😄

**Comment by WingZer0123** [comment]
@Mertsch I made a branch for this here [#44166](https://github.com/WingZer0123/aspnetcore/tree/%2344166-contentrangeheadervalue-always-less-than-length). Working on the test case within that same folder, seems there is no Test project associated with the entire `Microsoft.Net.Http.Headers` project. Anything else comes up we can place tests here.

**Comment by WingZer0123** [comment]
@Mertsch I made a branch for this here [#44166](https://github.com/WingZer0123/aspnetcore/tree/%2344166-contentrangeheadervalue-always-less-than-length). Working on the test case.

**Comment by Mertsch** [comment]
Cool. I guess a pure Unit Test that checks the constructor exceptions with different input combinations should be sufficient?!
Note: I am just a normal contributor I have no special knowledge about the framework or how to contribute :-)

**Comment by WingZer0123** [comment]
There are some Unit tests that are existing already, I have to examine them to make sure that they would compensate for the change. 

I have no special knowledge either, I use the framework and I have been digging through source to contribute. Thanks for collaborating :)

**Comment by tmricardo7** [comment]
I was checking the file and it looks like we have the same validation here
https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Http/Headers/src/ContentRangeHeaderValue.cs#L421-L425

It will be useful to have a special scenario where this issue is triggered.

**Comment by adityamandaleeka** [comment]
Looks like this discussion has been quiet for a while, so I'm going to go ahead and open a PR.
