### ISSUE TITLE
Blazor: remove all jQuery events when DOM is removed

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#44176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

when going from Page1 blazor to Page2 , 
the DOM is replaced, 
if on Page1 I called jQuery `$(div1).on('event',...` 
and I go to Page2, I think that the event handler might remain orphaned in memory.

Does Blazor have any automatic way to remove all events (and jquery events, maybe a hook) when removing/ DOM ?

### Describe the solution you'd like

for example `jQuery.remove/empty` does this automatically, 
maybe a hook where I could call 
`blazor.globals.cleanElem = (elm) => $(elm).off()`
or perhaps you're already doing this

**Comment by Liero** [comment]
> if on Page1 I called jQuery $(div1).on('event',...
> and I go to Page2, I think that the event handler might remain orphaned in memory.

if div1 is removed from DOM, the $(div1).on('event',...) does not keep reference, so it will not cause it to remain orphaned in memory. 

> Does Blazor have any automatic way to remove all events (and jquery events, maybe a hook) when removing/ DOM?
No.

**Comment by omuleanu** [comment]
> if div1 is removed from DOM, the $(div1).on('event',...) does not keep reference, so it will not cause it to remain orphaned in memory.

@Liero are you sure, I think this is only true if you remove it using jQuery ( `remove`, `empty`, etc. )

**Comment by Liero** [comment]
Yes

**Comment by mkArtakMSFT** [comment]
Thanks for answering this, @Liero.

@omuleanu if you still want to observe DOM related events (like unloading) you can use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) for that.
