### ISSUE TITLE
Change docs.microsoft.com links to learn.microsoft.com

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

docs.microsoft.com now redirects to learn.microsoft.com. We should update to the new URL in ASP.NET Core:

* Update aka.ms redirects to learn.microsoft.com
* Consider updating docs.microsoft.com links in dotnet/aspnetcore source code to learn.microsoft.com - https://cs.github.com/dotnet/aspnetcore?q=docs.microsoft.com

@Rick-Anderson Do you have any background information on the change from docs.microsoft.com to learn.microsoft.com.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Do you have any background information on the change from docs.microsoft.com to learn.microsoft.com.

@alexbuckgit is leading the effort for Microsoft.

**Comment by alexbuckgit** [comment]
Hi @JamesNK - Here's the announcement for the Microsoft Learn brand changes.

https://techcommunity.microsoft.com/t5/microsoft-learn-blog/build-skills-that-open-doors-with-microsoft-learn/ba-p/3614011

**Comment by wtgodbe** [comment]
@JamesNK do you mean we should do this for all instances of docs.microsoft.com links (including hyperlinks), or just visible ones? Is this part of the branding effort?

**Comment by wtgodbe** [comment]
Also do we know if a find/replace will work, or could that lead to dead links?

**Comment by wtgodbe** [comment]
CC @mkArtakMSFT do you own our aka.ms links?

**Comment by Rick-Anderson** [comment]
> Also do we know if a find/replace will work, or could that lead to dead links?

find/replace should work.

**Comment by abc516** [comment]
Hi @JamesNK @Rick-Anderson , can I take on this issue please?

**Comment by mkArtakMSFT** [comment]
> Hi @JamesNK @Rick-Anderson , can I take on this issue please?

Thanks for your willingness to help, @abc516. Feel free to send us a PR.
