### ISSUE TITLE
Quarantine `ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit`

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#44185]
## Failing Test(s)

`Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit()`

This test has been passing only about 55% of the time over the last two weeks.

## Error Message

```text
Error message
Assert.True() Failure
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs:line 71
--- End of stack trace from previous location ---
```
</details>

## Logs

[Microsoft.AspNetCore.Components.E2ETests.zip](https://github.com/dotnet/aspnetcore/files/9648229/Microsoft.AspNetCore.Components.E2ETests.zip)

## Build

For example, [build #20220923.29](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28394&view=results)

**Comment by dougbu** [comment]
Note #44186 will quarantine this test in the release/7.0 branch.

**Comment by MackinnonBuck** [comment]
I've found that when running locally with headless mode disabled, this test succeeds consistently. It appears that the `unload` event is flaky in headless mode specifically, causing the `_blazor/disconnect` request to never get sent, resulting in the test failure.

There is also the question of how much value this test is really adding - especially in non-desktop scenarios, the `unload` event is [highly unreliable](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes), so graceful termination of the circuit on tab/window close is more of an exception than the rule.

**Comment by MackinnonBuck** [comment]
We should address this after we implement https://github.com/dotnet/aspnetcore/issues/39409.
