### ISSUE TITLE
DotNetObjectReference in docs multiple instances created, only last one disposed

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#44189]
I see in docs you have code that only disposes the last instance of DotNetObjectReference

```
@page "/call-dotnet-example-2"
...
    <button @onclick="TriggerDotNetInstanceMethod">
        Trigger .NET instance method
...
@code {
  ...
    public async Task TriggerDotNetInstanceMethod()
    {
        objRef = DotNetObjectReference.Create(this);
        result = await JS.InvokeAsync<string>("sayHello1", objRef);
    }
    public void Dispose()
    {
        objRef?.Dispose();
    }
}
```

**You're calling DotNetObjectReference.Create on each button click, so Dispose will only execute on the last created instance.
Is that an issue ?**

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27036
this was already asked here: https://github.com/dotnet/aspnetcore/issues/44064 but it got closed, because it contained 2 questions and the 2nd one was answered.

### .NET Version
.net 6

**Comment by TanayParikh** [comment]
Reopened the original issue as it has more context. Closing this out
