### ISSUE TITLE
[SignalR] constantly reconnecting, timeout setting issue

### ISSUE THREAD

**Issue by Wasenshi123** [dotnet/aspnetcore#44197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently have a use case where I want to identify disconnection of clients quickly because of it's real-time functionality.

So to detect lost of connection more quickly, I set the signalr setting on my server as follows:
_ASP net core 3.1_
```
services.AddSignalR(c => { 
                c.ClientTimeoutInterval = TimeSpan.FromSeconds(5);
                c.KeepAliveInterval = TimeSpan.FromSeconds(12);
            })
```

But turned out, this causes the clients to be constantly reconnecting.

So the question is:

- What happens if you try to set keep alive interval or timeout window to a low number like above? **Is it bad practice**?
- How to make it works and solve this issue of client constantly reconnecting?
- If this is considered a bad way, what are alternative ways you would suggest to detect lost of connection quickly?

### Expected Behavior

Client shouldn't be forced to disconnect

### .NET Version

3.1

### Anything else?

I found a comment on client side 'keepAlive..' setting (Javascript) which say
```
The default value is 15,000 milliseconds (15 seconds). Allows the server to detect hard disconnects (like when a client unplugs their computer). The ping will happen at most as often as the server pings. If the server pings every 5 seconds, a value lower than 5 will ping every 5 seconds.
```
What does this actually mean? and why is it that way? (especially the part that say 'The ping will happen at most as often as the server pings.') 

And on [SignalR-Client-Cpp], it doesn't have corresponding 'keepAlive..' setting or such on the hub_connection, why? Update: found the settings, it's on the '[signalr_client_config](https://github.com/aspnet/SignalR-Client-Cpp/blob/main/include/signalrclient/signalr_client_config.h)'

**Comment by BrennanConroy** [comment]
> What does this actually mean? and why is it that way? (especially the part that say 'The ping will happen at most as often as the server pings.')

This is because browsers implement this "cool" feature to mark tabs as idle which throttles javascript timers. Client-side pings have to use a timer (otherwise how can they send a ping at regular intervals?) and because of this the connection will go idle and be closed. So we had to fix that by making the client ping when the server pings (roughly, a bit more complicated).

If you change the `ClientTimeoutInterval` you also need to update how often the client sends pings, otherwise the server will close the connection like you're seeing.

**Comment by Wasenshi123** [comment]
> > What does this actually mean? and why is it that way? (especially the part that say 'The ping will happen at most as often as the server pings.')
> 
> This is because browsers implement this "cool" feature to mark tabs as idle which throttles javascript timers. Client-side pings have to use a timer (otherwise how can they send a ping at regular intervals?) and because of this the connection will go idle and be closed. So we had to fix that by making the client ping when the server pings (roughly, a bit more complicated).

So it means this is only applied to JavaScript client which run on browser platform?

> 
> If you change the `ClientTimeoutInterval` you also need to update how often the client sends pings, otherwise the server will close the connection like you're seeing.

I see, so client's keepalive setting is paired with server's ClientTimeoutInterval, and server's keepalive setting is paired with client's ServerTimeout.

**Comment by Wasenshi123** [comment]
I'm not so familiar and not that expert with WebSocket, so another side question:
Frequently ping server/client (low interval keepalive) will have any side effect or downside? Any thing I should concern?

**Comment by BrennanConroy** [comment]
> So it means this is only applied to JavaScript client which run on browser platform?

Yes.

> Frequently ping server/client (low interval keepalive) will have any side effect or downside? Any thing I should concern?

There will be more bandwidth used (could be problematic for bandwidth limited users, or slower networks like cell phones) and slightly more CPU needed on the server. The CPU shouldn't be an issue unless you have many thousands of clients.
