### ISSUE TITLE
HTTPClient does not enclose name value in quotes when using Multipart form

### ISSUE THREAD

**Issue by Appelg** [dotnet/aspnetcore#44200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I post a `MultipartFormDataContent` with HttpClient, the name-parameter is not enclosed in quotes (").
This makes the WAF (Web Application Firewall) we use reject this post.
![image](https://user-images.githubusercontent.com/50763504/192455560-76a6e45e-3f5d-45a8-91c5-3151518443b0.png)

The supplier of the WAF argues that this does not conform to the RFC.
This is the part of the RFC they use to assume that the value of the name parameter should be enclosed in quotes:
![image](https://user-images.githubusercontent.com/50763504/192456116-93bf6911-deac-4fbd-9b11-2ec3ae2edb4a.png)

When I instead use Postman, it does enclose the parameter in quotes.
![image](https://user-images.githubusercontent.com/50763504/192454603-bf681b93-8061-4929-b8fd-f53e2bc07292.png)

### Expected Behavior

I would like to hear your input on this. In my opinion it would be best if the framework took care of adding and stripping the quotes. I can of course solve this by adding the quotes myself, but then I also need to take care of stripping them on the receiver side.

Also, this could be a problem when coding just a server where I doesn't have control of the client, I then have to assume that quotes might come in. **Update**: This might be fixed, see my comment below.

### Steps To Reproduce

```
static void Main(string[] args)
        {
            var httpClient = new HttpClient();
            var content = new MultipartFormDataContent();

            var stringContent = new StringContent("2021-12-01");
            stringContent.Headers.ContentType = new MediaTypeHeaderValue("application/text");

            
            // OK
            //content.Add(stringContent, @"""fromDate""");
            // FAIL
            content.Add(stringContent, "fromDate");

            var response = httpClient.PostAsync(Url, content).Result;
            var result = response.Content.ReadAsStringAsync().Result;
            Console.WriteLine(result);
         }
```

### .NET Version

6.0.302

### Anything else?
Update:
I started to dig around the code. It seems like the quotes actually are removed here:
https://github.com/dotnet/aspnetcore/blob/7a1a1ebf86fb24d84cefd45e05534c79708c7947/src/Http/WebUtilities/src/FormMultipartSection.cs#L39

As I said above, I'm not sure about if this is a bug or not, I just need your input on the RFC vs .NET implementation so I know how to solve this problem on my end.

**Comment by Tratcher** [comment]
RFC 2388, 7578, and 2231 don't specify if the name must be quoted, but they do so in the examples.

The clearest statement I see is the following, which says HttpClient is correct in not quoting a simple value like `fromDate`.

https://www.rfc-editor.org/rfc/rfc2183#section-2
> NOTE ON PARAMETER VALUE LENGHTS: A short (length <= 78 characters)
   parameter value containing only non-`tspecials' characters SHOULD be
   represented as a single `token'.  A short parameter value containing
   only ASCII characters, but including `tspecials' characters, SHOULD
   be represented as `quoted-string'.  Parameter values longer than 78
   characters, or which contain non-ASCII characters, MUST be encoded as
   specified in [[RFC 2184](https://www.rfc-editor.org/rfc/rfc2184)].

The FormMultipartSection code you linked is on the receiving side, removing the optional quotes from the value, if any. This isn't code used by HttpClient when creating requests.

**Comment by Appelg** [comment]
@Tratcher hello!

I agree with you. I will have to run this another round with the WAF creator.

I understand it was server side, I just missed the corresponding HttpClient code (or at least a switch to enable it) but I guess I have to add them manually.

Thanks for the quick feedback!

**Comment by Appelg** [comment]
Ok, more feedback:
![image](https://user-images.githubusercontent.com/50763504/192732746-6245c4a5-caee-42bc-b5ce-7d8f247cfa08.png)

I have not had time to go thru the code for HttpClient, sorry, but it seems that it correctly adds quotes when there are "tspecials" present.

**Comment by Appelg** [comment]
> @Appelg see https://github.com/dotnet/runtime/blob/a7d80c177a7ea412fb00867ccc4f4b2c44c9e030/src/libraries/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs#L372-L441

Thanks, just what I was looking for, really appreciate it!
