### ISSUE TITLE
Virtualize component: Add a method to scroll to an item

### ISSUE THREAD

**Issue by bernhard-dwe** [dotnet/aspnetcore#44219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When loading a page with a virtualised list of items, I cannot tell the virtualized component to scroll to a particular `StartIndex` or item.

### Describe the solution you'd like

I'd like to be able to call a method on the reference to the component so that it scrolls to the index I'd like to have presented.

e.g. `_virtualizeContainer.SetStartIndex(12);`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a duplicate of https://github.com/dotnet/aspnetcore/issues/26943
