### ISSUE TITLE
Option to have area views without an areas folder

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#44223]
There was a way to previously enable this before .NET 6. Click https://github.com/aspnet/Razor/issues/2425 to view the original issue. However this no longer works as now Razor views are compiled using source generators.

I have upgraded the samples to show a working ASP.NET Core 5 application and an almost identical app targetting ASP.NET Core 6 which does not work. To test run the applications and click on the "MyLibrary" link.

[AspNetCore5.zip](https://github.com/dotnet/aspnetcore/files/9665019/AspNetCore5.zip)
[AspNetCore6.zip](https://github.com/dotnet/aspnetcore/files/9665020/AspNetCore6.zip)

When I compare .NET 5 which produces the following attribute (with the MSBuild metadata fix in the original issue):

```cs
[RazorSourceChecksum("SHA1", "xxx", "/MyLibrary/Views/Home/Index.cshtml")]
```

However in .NET 6 it produces:

```cs
[RazorCompiledItemMetadata("Identifier", "/Areas/MyLibrary/Views/Home/Index.cshtml")]
```

Therefore from my understanding I need to override the identifier produced in the `RazorCompiledItemMetadataAttribute`. Searching for that led me to the [CreateNewOnMetadataUpdateAttributePass](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/CreateNewOnMetadataUpdateAttributePass.cs) class. It seems the indentifier's value is generated by the following code:

```cs
var identifierFeature = Engine.Features.OfType<IMetadataIdentifierFeature>().First();
var identifier = identifierFeature.GetIdentifier(codeDocument, codeDocument.Source);
```

I'm guessing I need to implement my own `IMetadataIdentifierFeature` and register it first in the list of features. This is where I got lost as I can't see how I can inject my own feature. I'll keep looking but if you could help point me in the right direction or let me know if I'm going down the wrong path that would be appreciated.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn do you know if we have a way to allow a custom IMetadataIdentifierFeature to be provided?

**Comment by javiercn** [comment]
@mkArtakMSFT This would need design.

**Comment by javiercn** [comment]
I do not believe the Razor compiler has specific knowledge about areas and I do not believe that you need to do anything in the compiler to support this scenario.

Areas are metadata at runtime and you should be able to write an `IPageRouteModelProvider` to fully control how pages are mapped.

Even simpler, you are likely able to achieve this by registering your own `PageRouteModel` convention inside `RazorPagesOptions.Conventions`

See https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-6.0 for more details

**Comment by nfplee** [comment]
Thanks @javiercn but I don’t think that will work. If you refer to the original issue (link above) then you will see the issue relates to the path for the views. If they are placed within the route of a project then they will always have the same path.

**Comment by javiercn** [comment]
@nfplee Thanks I did not realize that this was MVC, not Razor Pages. Let me take another look and I'll update this.

**Comment by nfplee** [comment]
Oddly I just ran the ASP.NET 6 sample project above and it worked. Has support for the MS Build "UpdateTargetPath" target been added in a newer version of the .NET 6 Razor SDK? I've been trying to search for it but can't see anything.

**Comment by javiercn** [comment]
@nfplee I am not sure about that. But for what you are trying to accomplish, I would avoid the compiler route and go through the "reinterpret the metadata at runtime" route.

**Comment by nfplee** [comment]
I guess the question is, has support for the following been added to the razor source generator since .NET 6 was released?

```xml
<Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
  <ItemGroup>
    <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
  </ItemGroup>
</Target>
```

My original fix was to disable `UseRazorSourceGenerator` by setting it to `false`.
