### ISSUE TITLE
Assumption about relative path for project files

### ISSUE THREAD

**Issue by sisomvanshi** [dotnet/aspnetcore#44224]
Hi we're running into errors in building our Razor class library, related to scp.css files. We think it's related to the part highlighted below that assumes a relative path for the file during build. Can the code be updated to better accommodate use cases with absolute paths for files in the .csproj?

https://github.com/dotnet/sdk/blob/7cc72cc116dc1fc8483076606fd79e78e1829116/src/RazorSdk/Tasks/ComputeCssScope.cs#L31

**Comment by sisomvanshi** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

I will try to create one and submit.

**Comment by sisomvanshi** [comment]
Hello again, please find attached a sample project that demonstrates the issue if you drop the contents on C:\ - 

> System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "C:\RootFolder\Build\SampleRCL\pc64-vc-dll-release\build\SampleRCL\vnet\scopedcss\C:\RootFolder\Code\Packages\SampleRCL\Component1.razor.rz.scp.css". The given path's format is not supported.
>    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
>    at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath)
>    at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath)
>    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name)
>    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
>    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
>    at Microsoft.AspNetCore.Razor.Tasks.DefineStaticWebAssets.ComputeCandidateIdentity(ITaskItem candidate, String contentRoot, String relativePath, Matcher matcher)
>    at Microsoft.AspNetCore.Razor.Tasks.DefineStaticWebAssets.Execute()	SampleRCL	C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.ScopedCss.targets	309

[ReproProject.zip](https://github.com/dotnet/aspnetcore/files/9767842/ReproProject.zip)

**Comment by javiercn** [comment]
@sisomvanshi thanks for the additional details.

```xml
</Content>
        <Content Include="C:\RootFolder\Code\Packages\SampleRCL\wwwroot\background.png">
      <Link>background.png</Link>
    </Content>
```

Absolute paths in this way is not something we support. Is there any issue specifying the code path as a relative path instead?

**Comment by sisomvanshi** [comment]
@javiercn Our project files get "generated" with these absolute paths using an internal system and reside in a different folder than source files from our repo. This is primarily done so we can separate any generated files, to make it easier for devs to clean their workspace if required.
