### ISSUE TITLE
Blazor - Title attribute in SVG is picked up by HeadOutlet

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#44231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SVG's `<title>` is reflected in the page's title

### Expected Behavior

Only `<title>` in `<head>` should be used for page's title.

refs: https://github.com/dotnet/aspnetcore/pull/37019 and https://github.com/dotnet/aspnetcore/pull/37009

### Steps To Reproduce

1. Create a new Blazor Server app with .NET 6
2. Comment out the `<PageTitle>` tags in MainLayout.razor and Index.razor
3. Add the following to the end of index.razor

```svg
<svg viewBox="0 0 20 10" xmlns="http://www.w3.org/2000/svg">
    <circle cx="5" cy="5" r="4">
        <title>I'm a circle</title>
    </circle>
</svg>
```

4. Run the project and note the title in the browser tab is "I'm a circle"

Here is a repro project: https://github.com/mrlife/HeadTitleTestNet6

**Comment by MackinnonBuck** [comment]
Looks like this is already fixed in 7.0 via #37009. I'm guessing that since the original issue comment references that PR, @mrlife already knew about the 7.0 fix, so this issue is specifically requesting that same fix be applied for 6.0

@mkArtakMSFT Would we consider backporting this to 6.0?

**Comment by mrlife** [comment]
> Looks like this is already fixed in 7.0 via #37009. I'm guessing that since the original issue comment references that PR, @mrlife already knew about the 7.0 fix, so this issue is specifically requesting that same fix be applied for 6.0
> 
> @mkArtakMSFT Would we consider backporting this to 6.0?

I kind of thought the backport was done in 6.0 based on this comment: https://github.com/dotnet/aspnetcore/pull/37019#issuecomment-929555175... maybe didn't make it in since that PR was closed instead of merged?

**Comment by MackinnonBuck** [comment]
Hm, interesting.

@SteveSandersonMS do you happen to remember why https://github.com/dotnet/aspnetcore/pull/37019 was closed?

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck Great question, but I'm afraid I don't know. Searching back through correspondence about it, there doesn't seem to be any mention. There must have been some verbal discussion that concluded with not backporting but unfortunately without leaving a record. My only guess is perhaps we ran out of time before the GA build occurred.

It looks like we *could* still backport to 6.0 now if we wanted - it's very low risk as far as I know.

**Comment by mkArtak** [comment]
@MackinnonBuck please prepare the backport PR and fill in the ask mode template. We'll take it to Tactics. Also, to make sure we don't lose track of this, can you please add this to the project board? Thanks!
