### ISSUE TITLE
SecurityTokenInvalidAudienceException: IDX10206: Unable to validate audience. The 'audiences' parameter is empty. Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable<string> audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)

### ISSUE THREAD

**Issue by AnnaLizzy** [dotnet/aspnetcore#44240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a problem for use cookie authentication without ASP.NET Core Identity. 

### Expected Behavior

![image](https://user-images.githubusercontent.com/70207000/192920223-80badc56-bd73-4900-9361-9e44e99dda6c.png)
![image](https://user-images.githubusercontent.com/70207000/192920284-3badb4ce-ba71-4255-b3d4-0663e9eda695.png)
![image](https://user-images.githubusercontent.com/70207000/192920346-5d15ab19-1aa1-4a28-aa30-7e920ffb9a83.png)

### .NET Version

.net core 3.1

**Comment by Tratcher** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/52c196b38e2ec2c06da8934bac7165108f2797af/src/Microsoft.IdentityModel.Tokens/Validators.cs#L90-L93
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/52c196b38e2ec2c06da8934bac7165108f2797af/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1106

That means the token doesn't contain an audience. Try using https://jwt.ms/ to examine the token.

**Comment by AnnaLizzy** [comment]
> https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/52c196b38e2ec2c06da8934bac7165108f2797af/src/Microsoft.IdentityModel.Tokens/Validators.cs#L90-L93 https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/52c196b38e2ec2c06da8934bac7165108f2797af/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L1106
> 
> That means the token doesn't contain an audience. Try using https://jwt.ms/ to examine the token.
