### ISSUE TITLE
Blazor Wasm authentication with identity provider behind reverse proxy using http

### ISSUE THREAD

**Issue by DomienVDH** [dotnet/aspnetcore#44248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor wasm application. I use KeyCloak as an identityProvider. This all runs in containers in docker behind a reverse proxy (traefik). We use subpaths, the blazor wasm uses https://mainlink/blazorwasm and when logging in it redirects to https://mainlink/auth. Everything behind the proxy uses http.

As a test when i'm not running in a container and using HTTPS everything works fine, i get redirected to the identity provider, can log in there, get the accesstoken and end up with a cookie in the browser. (i'm using the bff patern).

But when running in the container and use http, I get redirected to the application but lose all data so in the end i'm just redirected  without being logged in.

There is hardly any logging to see what problems i'm facing.

I'm using forwarded headers.

I'm not sure what other info would be usefull to you so feel free to ask any additional info that you would require.

### .NET Version

6.0.401

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to me more like an ask for help with configuration / setup, rather than an issue report.

@Tratcher, @HaoK do you guys have any suggestions for @DomienVDH?

@DomienVDH have you posted this on [StackOverflow](https://stackoverflow.com). I think you may be able to get faster response there.

**Comment by Tratcher** [comment]
Try the troubleshooting steps to see if the forwarders are being applied correctly.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0#troubleshoot
