### ISSUE TITLE
[Analyzer] Verify Blazor route type constraints are specified with all lower-case letters

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspnetcore#44252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If one specifies Blazor @page routing constraint types inadvertently with capital letters, at runtime, they will encounter an exception in _Host.cshtml on the <component> reading "System.NullReferenceException: 'Object reference not set to an instance of an object. Microsoft.AspNetCore.Components.Routing.Router.Refresh(bool isNavigationIntercepted)". This happens, for example, if a @page value reads like the following:

```csharp
@page "/entities/{Id:Guid}"
```

This should instead be written as (note the "g" in Guid) and will then work fine:

```csharp
@page "/entities/{Id:guid}"
```

As the error message is less than forthcoming about what exactly the issue is and the stack trace only shows that something is wrong in the rendering pipeline, this seems like an ideal candidate to get caught during build by an analyzer that can evaluate the constraints of the string attached to the @page attribute.

### Describe the solution you'd like

Ideally there would be an analyzer that can evaluate the route constraints on each page, if any, and validate that the name of the type constraint is presented as a string in full lowercase per the requirements [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#route-constraints).

### Additional context

I encountered this on Blazor server-side - no idea if it affects WASM Blazor or not or even if it's applicable to non-Blazor projects.

I'd be happy to contribute this, but I have no idea where to start as I've never written a Roslyn analyzer before. All the existing analyzers look more at handling middleware and startup configuration, but if someone can build out one example showing how an analyzer might be applied to Blazor attributes in pages/components, I'd be more than happy to run with that and contribute additional analyzers as well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We shouldn't throw `NullReferenceException` for sure, so we'll make sure the error is more useful.
@JamesNK how can we benefit here from the work that you've done with route syntax highlighting?

**Comment by JamesNK** [comment]
@mkArtakMSFT Can custom Blazor routes be registered? If so, then you can't assume someone hasn't registered there own route with a different case. If not, then sure, this is something that could be checked.

The code I wrote to parse the route pattern can definitely be reused. In fact, a lot of the route pattern validation can be reused, so you can provide warnings about all invalid route syntax.

The blocking issue with Blazor routes is they're specified in a page directive in a Razor file. As far as I know, analyzers haven't run against directives before. I logged an issue with Razor to annotate the string as a route - https://github.com/dotnet/razor-compiler/issues/352 - and that would hopefully provide a hook for us to see that the page argument is a route and apply syntax highlighting and validation.

**Comment by mkArtakMSFT** [comment]
Thanks @JamesNK.
Will keep this in mind and bring discuss this with the compiler team when we will be working with them on .NET 8 planning. Hopefully that ask can get prioritized.
