### ISSUE TITLE
Problem with slow loading of static files such as js in .NET 6.0.8 and IIS 10 web application

### ISSUE THREAD

**Issue by PlotnikovAlexandr** [dotnet/aspnetcore#44255]
The application is experiencing the issues shown in the image below. In particular, a long wait for loading static application data (js)

![browser_profiler](https://user-images.githubusercontent.com/95532977/192988396-fd869847-e32f-41ac-8082-fb74babaf81b.png)

I am also attaching a code snippet startup.cs
![code_example](https://user-images.githubusercontent.com/95532977/192989036-3493a57a-8c62-4cac-a195-d9b0b6828dfb.png)

The issue is reproduced in an application using .NET runtime 6.0.8 but not in the same application with NET Framework version 4.7.2

**Comment by Tratcher** [comment]
I see UseStaticFiles set up for /Content and that looks fast, but what's handling requests for /js and /css?

What is your UseIIS method for? That doesn't look like the built in one.

**Comment by PlotnikovAlexandr** [comment]
> I see UseStaticFiles set up for /Content and that looks fast, but what's handling requests for /js and /css?
> 
> What is your UseIIS method for? That doesn't look like the built in one.

We use the approach described here https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0 in paragraph "Serve files outside of web root".

app.UseIIS(Env) - a stub in which nothing happens for the production environment (but it was deleted just in case - the problem was not solved after that)

The problem is that the case is not reproduced on other environments.

**Comment by Tratcher** [comment]
You still need an instance of UseStaticFiles to serve those. Right now I can't tell what's servicing the content of /js and /css. I suggest adding a second `UseStaticFiles()` next to the first one. This will use the modified WebRootPath.

**Comment by PlotnikovAlexandr** [comment]
The problem with long loading of js files was solved by recreating the application pool in IIS. Why this helped, I can't figure out. Perhaps someone has come across something similar?

**Comment by adityamandaleeka** [comment]
@PlotnikovAlexandr Glad it's solved. Perhaps there were settings on the old application pool that caused it. You could try comparing all the settings on each to see which one could have affected it.

I'll close this issue for now since it sounds like it doesn't happen with a fresh pool.
