### ISSUE TITLE
Docs - Minimal APIs - Dealing with responses

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#44258]
## Basics

- [X] Creating responses (Serialization, File, Text, Stream, IResults, etc) (https://github.com/dotnet/AspNetCore.Docs/pull/27263)
- [X] Error handling (Problem details, exception middleware, etc.) (https://github.com/dotnet/AspNetCore.Docs/pull/27400)

## Advanced

- [ ] Dependency Injection for services, configurations, etc.

**Comment by brunolins16** [comment]
> [ ] Dependency Injection for services, configurations, etc.

Added as part of WebApplication documentations:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0#access-the-dependency-injection-di-container

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0#configuration

We can decide in the future if a dedicated page will be needed.
