### ISSUE TITLE
Docs - Minimal API - Document your APIs

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#44257]
## Documenting your API

- [x] Introduction to OpenAPI
- [x] Annotating your operations
- [x] Adding operation IDs, tags, descriptions
- [x] Exclude from API description
- [x] Mark as obsolete
- [x] Annotating responses
- [x] Produces extension method
- [x] Produces attribute
- [x] Default response type inference
- [x] Annotating requests
- [x] Accepts metadata
- [x] Default request metadata inference
- [x] API Versioning

## Working with client generation

- [ ] https://github.com/dotnet/AspNetCore.Docs/issues/22176

## Basics

- [x] Endpoint filters
- [x] Endpoint filters on MVC

## Security

- [x] Protecting your endpoints
- [x] Jwt tooling for local development scenarios

**Comment by captainsafia** [comment]
All of the items are documented under this except the client generation stuff.

@JeremyLikness I think we should get a better understanding of the space/scenarios before we right documentation on this front.

**Comment by JeremyLikness** [comment]
I concur.
