### ISSUE TITLE
Docs - Minimal API  Basics

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/aspnetcore#44256]
- [ ] Routing (Basic routing, route parameters route groups, fallback)
- [ ] Route handlers
- [ ] Parameter Binding (Explicit vs implicit, route, query, header, body, services, bind failures)

## Advanced
- [ ] Advanced Parameter Binding (BindAsync, TryParse)
- [ ] Host (Generic Host, WebAppicationBuilder, grpc integration, SignalR Integration, Orleans Integration)

**Comment by captainsafia** [comment]
I think we can close this issue out. We have docs on [route handlers](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/route-handlers?view=aspnetcore-7.0), [parameter binding](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0), [advanced parameter binding scenarios](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#custom-binding), and [the WebApplication constructs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0).

Also, the SignalR and gRPC docs have been updated to use the minimal host in their samples, which I think is sufficient for showcasing the integration.
