### ISSUE TITLE
Best practice to use IResult in a class library

### ISSUE THREAD

**Issue by gerjandev** [dotnet/aspnetcore#44250]
What is the best way to use the new `IResult` type in a class library?

I did abstract / port some code to a shared library (2 edge api's, one shared api lib) but I really struggled to get the `IResult` type and `Results` factory in the lib. 

My first reaction was to find it in nuget packages like `Microsoft.AspNetCore.Http`, `Microsoft.AspNetCore.Http.Extensions` or `Microsoft.AspNetCore.Http.Abstractions` but no success.

Then I remembered that the whole distribution of frameworks did change. In the old days everything was distributed via NuGet but now the frameworks/app models are distributed as SDK that you install on your machine. So the dlls are right there but how to reference it?

I think the Nuget packages above are not updated anymore, thats correct? 

One way to fix it, is to change the csproject to `<Project Sdk="Microsoft.NET.Sdk.Web">` and then it works.

But it does feel a bit 'heavy', only when you want to reference 1 type and access one factory. 

So whats best practice on this?

**Comment by BrennanConroy** [comment]
You need to tell your class library that you're referencing the ASP.NET Core shared framework.
https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

**Comment by gerjandev** [comment]
@BrennanConroy Thanks! Does Visual Studio have support for this? I will edit csproj now and its fine but I'm curious whether VS support this feature.

**Comment by BrennanConroy** [comment]
What do you mean does VS support this? Via a right-click add framework reference? No idea.

**Comment by adityamandaleeka** [comment]
Seems like this is resolved for now but @vijayrkn this may be an interesting VS feature suggestion (right click, add framework reference). Maybe even autodetecting that the user is trying to use types from ASP.NET Core and prompting that the reference should be added) if that's possible?

**Comment by vijayrkn** [comment]
If such a support were to exist, I would assume it needs to be more generic than just for Web projects. May be something for the project system backlog - https://github.com/dotnet/project-system?

**Comment by DamianEdwards** [comment]
https://github.com/dotnet/project-system/issues/8558

**Comment by adityamandaleeka** [comment]
Thanks @DamianEdwards. Closing this issue.
