### ISSUE TITLE
kestrel web api causes its client app failure of An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by swuqi** [dotnet/aspnetcore#44261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a .Net 5 Web API application for uploading large files (>6GB). If this App is running from Visual Studio 2022's debugging mode with Kestrel, it can accept any size of files. The client App using HttpClient can upload large files. But if I start the .Net 5 Web API App from a command line or start by "dotnet run" command, it can only accept small files (<6KB) and the Client App can upload small files successfully. If the client App tries to upload a large file (>3GB), the client App will show the following errors that I believe it is caused by the Kestrel web server side.

{"Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.."}
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error while copying content to a stream.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at UploadFile.Program.Main(String[] args) in H:\Dev\DevProj\UploadFile\Program.cs:line 26
Inner Exception 1:
HttpRequestException: Error while copying content to a stream.
Inner Exception 2:
IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
Inner Exception 3:
SocketException: An existing connection was forcibly closed by the remote host.
Overriding address(es) 'https://localhost:8001, http://localhost:8000'. Binding to endpoints defined in UseKestrel() instead.

I can host this web API application in IIS environment and it can accept large files less than 4GB.

This might be a bug of Kestrel web server.

### Expected Behavior

When the .Net 5 web application runs as Kestrel web server without Visual Studio, it should be able to accept large files uploaded. 

### .NET Version

.NET 5

**Comment by Tratcher** [comment]
Note .NET 5 is out of support, please update to .NET 6 or 7.

Can you please give repro code for the client and server? Running in or out of VS shouldn't change anything.

Can you enable debug level logging on the server and share the output that includes the failure?

**Comment by swuqi** [comment]
Thanks Chris for your response. I realized that Visual Studio 2022 may cause the problem. Since our Intranet environment is still using Visual Studio 2019, I have to stay with .Net 5 and VS 2019 currently. This VS 2022 is only installed on a test machine with Internet access.
After I build the web service code from VS 2019, it is working perfectly without using VS debugging.
