### ISSUE TITLE
Blazor WASM Redirection after Authenticating

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#44264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After Authenticating we're redirected to the root of the Blazor App instead of the page we came from.

This issue is reproductible with Blazor WASM Template.

We aren't redirected to fetch data page avec authentication.

### .NET Version

.Net 7 RC1

**Comment by TanayParikh** [comment]
@Julien-Marpault just to clarify, are you saying this is a regression from past versions of .NET? Or is this a feature request?

**Comment by Julien-Marpault** [comment]
yes it's a regression. It works as expected with .Net 6

**Comment by javiercn** [comment]
@Julien-Marpault thanks for contacting us.

Sorry, we changed this in .NET 7.0. We need an announcement for it. You need to change the code in the RedirectToLogin component to use `Navigation.NavigateToLogin("authentication/login");` and add `@using Microsoft.AspNetCore.Components.WebAssembly.Authentication`

We stopped passing data through the query string to the authentication components as it simplified the implementation and reduced the attack surface area.

We need an announcement for this.

**Comment by javiercn** [comment]
Moved to 7.0 as this only needs an announcement.

**Comment by javiercn** [comment]
Announcement published https://github.com/aspnet/Announcements/issues/497
