### ISSUE TITLE
[Analyzer] Verify no two or more pages are using the same @page path

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspnetcore#44266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If one creates two separate Blazor (server-side, at least) pages that each use the same @page value, at runtime they will encounter an exception in _Host.cshtml reading "System.NullReferenceException: 'Object reference not set to an instance of an object. Microsoft.AspNetCore.Components.Routing.Router.Refresh(bool isNavigationIntercepted)". This happens, for example, if a @page value reads like the following across two or more different Razor pages:

```csharp
@* Home.razor *@
@page "/"
```

```csharp
@* About.razor *@
@page "/"
```

Rather, each page should use a different @page value.

As the error message is less than shortcoming about what exactly the issue is and the stack trace only shows that something is wrong in the rendering pipeline, I'd like to see an analyzer catch this at build time to evaluate the @page values specified across all such resources and look for duplicates.

### Describe the solution you'd like

Ideally there should be an analyzer that can evaluate the @page path on each page and look for any duplicates ahead of encountering the runtime failure.

Short of that, the error message should be improved.

### Additional context

I encountered this on Blazor server-side - no idea if it affects WASM Blazor or not or even if it's applicable to non-Blazor projects.

**Comment by martincostello** [comment]
This could be useful for Razor Pages too.

**Comment by javiercn** [comment]
@WhitWaldo thanks for contacting us.

>  _Host.cshtml reading "System.NullReferenceException: 'Object reference not set to an instance of an object.

This was a bug in our router implementation we addressed in .NET 7.0.

As for an analyzer, we do not have plans to do that. An analyzer would preclude us from making routes configurable at runtime like in ASP.NET Core and for ASP.NET Core the routes are configured at runtime, so an analyzer won't work.
