### ISSUE TITLE
[release/8.0] Update Roslyn Versions for .NET 8

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#44265]
This is a routine change we complete every release to update the Roslyn version used by the [Razor Runtime Compilation NuGet package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Razor). This issue tracks making this update ahead of the .NET 8 release. 

The Razor Runtime Compilation NuGet package needs to reference a version of Roslyn that ships as a NuGet package. However, as Roslyn doesn't follow the runtime ship schedule, ASP.NET Core manually updates this package version.

## Customer Impact

This change ensures the version of Roslyn used by the Razor Runtime Compilation NuGet package is synchronized with the version of Roslyn used by the Razor Compiler (which ships as part of the SDK). Without synchronized Roslyn versions, we could have undefined behavior in our published packages.

---

References:
- https://github.com/dotnet/aspnetcore/issues/39387
- https://github.com/dotnet/aspnetcore/pull/44072#discussion_r978887076
- https://github.com/dotnet/aspnetcore/pull/44148
- https://github.com/dotnet/aspnetcore/pull/28125
- https://github.com/dotnet/aspnetcore/pull/37764
- https://github.com/dotnet/aspnetcore/pull/44072

**Comment by TanayParikh** [comment]
@mkArtakMSFT I believe we'll want to hold off on this till the 8.0 RCs? If you agree, should we reset the milestone to something else?

**Comment by surayya-MS** [comment]
Looks like the version in [runtime](https://github.com/dotnet/runtime/blob/ef6283ac0a14c78d9e9fef4841545099bd7ad12b/eng/Versions.props#L47) and [sdk](https://github.com/dotnet/sdk/blob/release/8.0.1xx/eng/Versions.props#L141) are the same `4.8.0-3.23501.1` for `release/8.0`.

I'm going to update the version in aspnetcore repo version from `4.7.0-3.23314.3` to `4.8.0-3.23501.1`.

https://github.com/dotnet/aspnetcore/blob/c046946464f132fc3f32ac0a02c54ac3d29ac1d7/eng/Versions.props#L153C1-L157C5

@jaredpar could you please confirm if `4.8.0-3.23501.1` is the right one for release/8.0?

**Comment by surayya-MS** [comment]
>That is the right one at the moment, it will change as we approach RTM

Thanks! Then I'll wait and update the version closer to RTM.
