### ISSUE TITLE
Blazor CSS Isolation Issue only on certain pages

### ISSUE THREAD

**Issue by mickeyjazz** [dotnet/aspnetcore#44267]
I have a Blazor Server app that has been working fine (.net 6). All of a sudden css isolation is not working on just a few pages. All other css isolation pages are working fine. This is in the development environment. I don't want to publish this version of course.

I tried deleting the css isolation file and recreating. I tried deleting the main page and css file and adding back in. Doesn't work. The only thing that works is deleting the page and adding back in with a different name than the original. The original name is somehow corrupted for future use.

I can do this for the few files I know about, but I might not find all the pages that don't work anymore. I tried rebooting my computer, made sure to update to the latest version of Visual Studio.

Anyone have any ideas?

**Comment by javiercn** [comment]
@mickeyjazz thanks for contacting us.

Unfortunately we do not have enough information to make progress on this issue. We would need a minimal repro project with steps on how to trigger the issue hosted as a public github repository for us to try and understand what is happening.

We would suggest you clean the bin/obj folders of your projects to see if that makes the issues go away.
