### ISSUE TITLE
Blazor InputFile read updated file stream will throw InvalidOperationException

### ISSUE THREAD

**Issue by jeffgoku** [dotnet/aspnetcore#44277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

* click the InputFile to select a file to trigger OnChange event, and store the IBrowserFile instance to a variable
* edit the selected file out of the browser to make it updated
* then read the IBrowserFile will throw InvalidOperationException

### Expected Behavior

Read the file without throw

### Steps To Reproduce

* click the InputFile to select a file to trigger OnChange event, and store the IBrowserFile instance to a variable
* edit the selected file out of the browser to make it updated
* then read the IBrowserFile will throw InvalidOperationException

### Exceptions (if any)

System.InvalidOperationException: An error occurred while reading the remote stream: NotReadableError

### .NET Version

6.0.401

**Comment by TanayParikh** [comment]
Hey @jeffgoku, this sounds very much like a browser or OS limitation. Are you able to successfully complete the scenario you described using the standard html input element?

**Comment by jeffgoku** [comment]
> Hey @jeffgoku, this sounds very much like a browser or OS limitation. Are you able to successfully complete the scenario you described using the standard html input element?

Hi, I tried using the standard html input element, it also threw exception, It's indeed a browser limitation
