### ISSUE TITLE
Performance issue with PersistentComponentState

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#44271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I used the solution as per the documentation:
https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-6.0

With this application, the page load time takes:
![image](https://user-images.githubusercontent.com/42449535/193169395-fb312b50-3377-4ec5-9fed-02fda6ba427a.png)

Without this application:
![image](https://user-images.githubusercontent.com/42449535/193169480-e4d8d884-3d01-44da-83a5-6665c274ab18.png)

As can be seen in the attachments above, the efficiency drops four times

I used EF Core to retrieve a query from a database.

It seems to me that the first page loading is blocked waiting for everything to load.
This solves the flashing page problem but creates a longer first load problem.

My code:
```cs
    Models.Article Test;

    protected async override Task OnInitializedAsync()
    {
        persistingSubscription = ApplicationState.RegisterOnPersisting(Task () => { ApplicationState.PersistAsJson("article", Test); return Task.CompletedTask; });

        if (!ApplicationState.TryTakeFromJson<Models.Article>(
            "article", out var restored))
        {
            var article = await _article.GetAsync(this.Name);
            Test = article.Get();
        }
        else
        {
            Test = restored!;
        }

        _details = new Modules.Details(Test);
    }
```

### .NET Version

.net core 7 rc 1

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

I suspect that you might want to move the persist state taghelper below the blazor server script. What I suspect is happening is that you are on a slow network and the extra data is delaying the load of the rest of the elements. Serializing the data at the end of the document should address that.
