### ISSUE TITLE
Changing the date / time format reflect to the CurrentCulture all the time

### ISSUE THREAD

**Issue by hishamco** [dotnet/aspnetcore#44286]
## Background and Motivation

Changing the culture date/time format reflect to the default culture, there's no way in the current APIs to allow the user doesn't rely on the system settings

## Proposed API

```diff
+ private readonly bool _useUserOverride;
+
    private RequestCulture _defaultRequestCulture =
        new RequestCulture(CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture);

- public RequestLocalizationOptions()
+ public RequestLocalizationOptions() : this(useUserOverride: true)
{
-    RequestCultureProviders = new List<IRequestCultureProvider>
-    {
-        new QueryStringRequestCultureProvider { Options = this },
-        new CookieRequestCultureProvider { Options = this },
-        new AcceptLanguageHeaderRequestCultureProvider { Options = this }
-    };
}

+ public RequestLocalizationOptions(bool useUserOverride)
+{
+    _useUserOverride = useUserOverride;
+    RequestCultureProviders = new List<IRequestCultureProvider>
+    {
+        new QueryStringRequestCultureProvider { Options = this },
+        new CookieRequestCultureProvider { Options = this },
+        new AcceptLanguageHeaderRequestCultureProvider { Options = this }
+    };
```

## Usage Examples

```csharp
var options = new RequestLocalizationOptions(useUserOverride: true);

app.UseRequestLocalization(options);
```

**Comment by adityamandaleeka** [comment]
@hishamco Can you please add a comment with the API proposal to this issue so that it can go through the API review process? More info here: https://github.com/dotnet/aspnetcore/blob/main/docs/APIReviewProcess.md

**Comment by hishamco** [comment]
I didn't understand what kind of comment should I add? Where?

**Comment by BrennanConroy** [comment]
See the issue template: https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=
Either edit the top comment or make a new one.
See example: https://github.com/dotnet/aspnetcore/issues/42725

**Comment by halter73** [comment]
API review notes:

1. Orchard could use this, so it seems useful to add.
2. We want to make this non-breaking
3. Let's make it a settable property like we do for most bool configurable via the [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0).
4. Are there other things that we might want to configure on the `CultureInfo`? No.

```diff
namespace Microsoft.AspNetCore.Builder;

public class RequestLocalizationOptions
{
+    public bool CultureInfoUseUserOverride { get; set; }
}
```

API Approved!

**Comment by hishamco** [comment]
> We want to make this non-breaking

There's no breaking-changes here

> Let's make it a settable property like we do for most bool configurable via the [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0).

LGTM

> Are there other things that we might want to configure on the CultureInfo?

For now, nope

> UseUserOverride? CultureInfoUseUserOverride? Something else? Let's go with CultureInfoUseUserOverride because the relationship to CultureInfo isn't as obvious otherwise

`CultureInfoUseUserOverride` is weird little bit ;) it's not necessary that we make it obvious, can we use `UseUserOverrideCulture` or `UseSystemCulture`?

**Comment by halter73** [comment]
> it's not necessary that we make it obvious

We don't expect this to show up in a lot of code, so I think clarity trumps terseness. We agree that `CultureInfoUseUserOverride` quite the mouthful and nongrammatical, but at least if you search "CultureInfoUseUserOverride", you already get some useful documentation.

**Comment by hishamco** [comment]
We already use `SupportedCultures`, `SupportedUICultures` same thing we could use `UseSystemCultureSettings` or `UseUserOverrideCulture` which clear IMHO, unless you are already agreed with the naming

**Comment by halter73** [comment]
@hishamco It wasn't just me that decided on `CultureInfoUseUserOverride`. Members of @dotnet/aspnet-api-review had a vote and approved it. We discussed your `UseSystemCultureSettings` and `UseUserOverrideCulture` naming suggestions, but we still prefer `CultureInfoUseUserOverride`. If you want us to merge your PR, it must match the approved API.

**Comment by hishamco** [comment]
No problem, but if you could fix the APIs base fix I will be thankful, because I tried at my side but it didn't work
