### ISSUE TITLE
ASP.NET Core with Angular projec type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44289]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNET-Core-with-Angular-projec-type/10146312)._

---
It would be helpful to include a Post that does anti forgery token processing in the sample project.  It only has a Get.

---
#### Feedback Bot on 9/13/2022, 11:43 PM: 

(private comment, text removed)

**Comment by abc516** [comment]
Hi @MackinnonBuck , can I take on this issue please?

**Comment by javiercn** [comment]
We do not recommend using cookies with SPA our recommended approach is to use token-based authentication for SPA, so we do not want to invest/document this approach as it is not something we recommend.
