### ISSUE TITLE
StartupAnalyzerTest tests are not running and all have test failures

### ISSUE THREAD

**Issue by david-acker** [dotnet/aspnetcore#44306]
### Background

While working on #41362, I noticed that [`StartupAnalyzerTest`](https://github.com/dotnet/aspnetcore/blob/main/src/Analyzers/Analyzers/test/StartupAnalyzerTest.cs) is not being run since the test class is incorrectly marked abstract and is not inherited by any other test classes.

After removing the abstract modifier from `StartupAnalyzerTest`, the tests did run as expected but all 17 currently show test failures.

It appears that this test class was erroneously marked as abstract when it was updated in PR #37934.

### Solution
- Remove the abstract modified from `StartupAnalyzerTest`.
- Fix the pre-existing issues that are causing these tests to fail.

**Comment by adityamandaleeka** [comment]
Good catch @david-acker!
