### ISSUE TITLE
Blazor WASM : IServiceProvider Reflection based Property Getter Exception

### ISSUE THREAD

**Issue by David-Moreira** [dotnet/aspnetcore#44301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On a WASM application, with a ScopedService injected on a component. 
When getting some property (Disposables for example) from `IServiceProvider` with reflection it works on Debug / Release modes.
![image](https://user-images.githubusercontent.com/22283161/193406250-f8b43d55-4f93-49ae-a7d2-7a7624655c98.png)
![image](https://user-images.githubusercontent.com/22283161/193406241-bfdce1a9-fdc9-40f0-a2f6-051455fcf5a7.png)

When published and served in IIS for examples, the following exception is thrown:

**Expression:**
![ServiceProviderExpression](https://user-images.githubusercontent.com/22283161/193406263-08cf6e25-7603-46f1-a1e6-8f0eafa7110f.png)
**Regular Reflection:**
![ServiceProviderReflection](https://user-images.githubusercontent.com/22283161/193406274-29d02648-2285-4f4d-80e7-dc6df92f13a3.png)

### Expected Behavior

Same behaviour across different configurations? Should it not always be accessible?

### Steps To Reproduce

- Clone Repro https://github.com/David-Moreira/BlazorGetTypePublish
- Publish app, I used this configuration
![image](https://user-images.githubusercontent.com/22283161/193406338-e73ba8d5-bc8e-4f4d-afba-1b4a2dfe0a70.png)
- I served it under IIS
![image](https://user-images.githubusercontent.com/22283161/193406375-5dc516d7-f7ad-4ba5-8b55-211498b24cb2.png)
- Visit the home page, the error is thrown.

### Exceptions (if any)

When published and served in IIS for examples, the following exception is thrown:

**Expression:**
![ServiceProviderExpression](https://user-images.githubusercontent.com/22283161/193406263-08cf6e25-7603-46f1-a1e6-8f0eafa7110f.png)
**Regular Reflection:**
![ServiceProviderReflection](https://user-images.githubusercontent.com/22283161/193406274-29d02648-2285-4f4d-80e7-dc6df92f13a3.png)

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

NET6
VS 2022 Preview
![image](https://user-images.githubusercontent.com/22283161/193406461-9d0aa610-c58d-4872-abe8-09b84365f93f.png)

**Comment by javiercn** [comment]
@David-Moreira thanks for contacting us.

The app is being linked when you publish and given you are accessing things through reflection, the linker is not able to see the usages and removes members. Check https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-6-0 and https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming for more details on how to correctly configure the linker for your scenario.

**Comment by David-Moreira** [comment]
Hello @javiercn
I will be closing this issue as you've pointed me in the right direction. I will do some reading up on the articles you've posted.

Hopefully as a Library Author you can configure your project to make it so you disable trimming for the certain parts you need to actually not be trimmed, so the Library/original code can work for the end consumers who publish the library as part of their app.

I will do the reading, Thank you for your help/availability.
