### ISSUE TITLE
[Analyzer] Unused route parameter detection and fixer

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44319]
## Background and Motivation

When adding a route parameter to a minimal API or action:
1. The route parameter needs to be added to the route
2. .NET parameter needs to be added to the lambda/method.

An analyzer and fixer can automate step 2.

## Proposed API

An analyzer inspects the route for route parameters and the lambda/action parameters. If the route has a parameter that isn't present in the lambda/action then the analyzer will suggest a fix.

* Suggestion level (it's valid to have a route parameter that's not used so this isn't a warning)
* Optional route parameter = nullable argument
* Route parameter constraint is used to infer the .NET type. e.g. int constraint = int method parameter. Same with guid, int, long, double, float, datetime, decimal, etc. No route parameter means the new parameter type is string.
* Put the new parameter in the method based on its position in the route.

## Usage Examples

![MicrosoftTeams-image](https://user-images.githubusercontent.com/303201/193487633-266e3766-39b1-48c9-ac36-1e5efac689b6.png)

**Comment by halter73** [comment]
API Review Notes:

- This especially important since this isn't caught at runtime and is likely misusage.

Category: Usage
Severity: Warning

**Comment by JamesNK** [comment]
Double check it works with RequestDelegate overload.

**Comment by halter73** [comment]
API Review Notes:

- It does seem unusual to define a route value and not take it as a parameter to your delegate.
- This will file a lot on older code using the RequestDelegate overload, but maybe that's okay.
- This will recommend changing to an API that is less trim safe in some cases.

Category: Usage
Severity: Info
