### ISSUE TITLE
Considerable overhead in middleware pipeline

### ISSUE THREAD

**Issue by avandych** [dotnet/aspnetcore#44311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NewRelic monitoring showed that a considerable amount of time is spent in **Middleware Pipeline**
[](url)
<img width="940" alt="Screenshot 2022-10-02 at 11 18 33" src="https://user-images.githubusercontent.com/4070081/193444976-5db852f3-67c4-435a-be6e-01e5f32ea102.png">

Traces consistently show a delay between request starting and request arriving at the controller action(**measure-http-metrics** is custom middleware that only wraps request delegate with a stopwatch for tracing, it's placed after routing)
<img width="1045" alt="Screenshot 2022-10-02 at 11 42 22" src="https://user-images.githubusercontent.com/4070081/193445782-95c578f1-acee-4360-9ba2-e0ce31432453.png">

We removed from the pipeline everything except UseRouting and UseEndpoints, after turning on Debug logs we can see that controller action execution takes around 8 ms from an overall 21 ms, which doesn't seem ok.

A request is very small JSON with only 2 properties, the response is relatively big JSON - around 5 KB.

Service is hosted in k8s, uses alpine image

> [2022-10-01 13:29:59.589 PM] info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://services.local/api/verification/getstatus application/json 68
[2022-10-01 13:29:59.590 PM] dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[1]
      POST requests are not supported
[2022-10-01 13:29:59.590 PM] dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/api/verification/getstatus'
[2022-10-01 13:29:59.590 PM] dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'Services.Controllers.VerificationController.GetStatus (Services)' with route pattern 'api/Verification/GetStatus' is valid for the request path '/api/verification/getstatus'
[2022-10-01 13:29:59.590 PM] dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'Services.Controllers.VerificationController.GetStatus (Services)'
[2022-10-01 13:29:59.590 PM] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Services.Controllers.VerificationController.GetStatus (Services)'
[2022-10-01 13:29:59.591 PM] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetStatus", controller = "Verification"}. Executing controller action with signature System.Threading.Tasks.Task`1[Services.Contracts.Responses.Verification.VerificationApiResponse] GetStatus(Services.Contracts.Requests.Verification.GetStatusApiRequest) on controller Services.Controllers.VerificationController (Services).
[2022-10-01 13:29:59.591 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
[2022-10-01 13:29:59.591 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
[2022-10-01 13:29:59.591 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
[2022-10-01 13:29:59.591 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
[2022-10-01 13:29:59.591 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter, Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
[2022-10-01 13:29:59.594 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing controller factory for controller Services.Controllers.VerificationController (Services)
[2022-10-01 13:29:59.594 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed controller factory for controller Services.Controllers.VerificationController (Services)
[2022-10-01 13:29:59.594 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]
      Attempting to bind parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest' ...
[2022-10-01 13:29:59.595 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[44]
      Attempting to bind parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest' using the name '' in request data ...
[2022-10-01 13:29:59.595 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[1]
      Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter' for content type 'application/json'.
[2022-10-01 13:29:59.595 PM] dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HML3M35S3U4L", Request id "0HML3M35S3U4L:00000205": started reading request body.
[2022-10-01 13:29:59.595 PM] dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HML3M35S3U4L", Request id "0HML3M35S3U4L:00000205": done reading request body.
[2022-10-01 13:29:59.596 PM] dbug: Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter[2]
      JSON input formatter succeeded, deserializing to type 'Services.Contracts.Requests.Verification.GetStatusApiRequest'
[2022-10-01 13:29:59.596 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[45]
      Done attempting to bind parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest'.
[2022-10-01 13:29:59.596 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[23]
      Done attempting to bind parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest'.
[2022-10-01 13:29:59.596 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[26]
      Attempting to validate the bound parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest' ...
[2022-10-01 13:29:59.597 PM] dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[27]
      Done attempting to validate the bound parameter 'request' of type 'Services.Contracts.Requests.Verification.GetStatusApiRequest'.
[2022-10-01 13:29:59.598 PM] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Services.Controllers.VerificationController.GetStatus (Services) - Validation state: Valid
[2022-10-01 13:29:59.606 PM] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method Services.Controllers.VerificationController.GetStatus (Services), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 7.9254ms.
[2022-10-01 13:29:59.607 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]
      List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter
[2022-10-01 13:29:59.607 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[4]
      No information found on request to perform content negotiation.
[2022-10-01 13:29:59.608 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[8]
      Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
[2022-10-01 13:29:59.608 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[10]
      Attempting to select the first formatter in the output formatters list which can write the result.
[2022-10-01 13:29:59.608 PM] dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[2]
      Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter' and content type 'application/json' to write the response.
[2022-10-01 13:29:59.608 PM] info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Services.Contracts.Responses.Verification.VerificationApiResponse'.
[2022-10-01 13:29:59.609 PM] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Services.Controllers.VerificationController.GetStatus (Services) in 17.3468ms
[2022-10-01 13:29:59.610 PM] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Services.Controllers.VerificationController.GetStatus (Services)'
[2022-10-01 13:29:59.610 PM] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://services.local/api/verification/getstatus application/json 68 - 200 - application/json;+charset=utf-8 21.4094ms

### Expected Behavior

What can be possible reasons for such behavior? Can somebody point me in the right direction? From logs, it doesn't seem that problem is in network/serialization.

### .NET Version

6.0.302

### Anything else?

~ $ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by davidfowl** [comment]
What does `GetStatusApiRequest` look like? Can you share it here?

**Comment by avandych** [comment]
Sure, no sync calls - fetch from Redis, if successful, another call to DB to validate the checksum - that's the happy path, it's not compute intensive, mainly I/O stuff. There are no locks in the codebase too. The log in an initial topic is from purely synthetic load too, not other calls to service are made, just happy path requests. 

<img width="805" alt="Screenshot 2022-10-02 at 23 49 05" src="https://user-images.githubusercontent.com/4070081/193475657-2b7cc3a1-9b82-4bd1-a62f-7839f73cd94c.png">

**Comment by davidfowl** [comment]
Sorry I meant the model being bound. I'm wondering if more time is being spent in validation than expected.

**Comment by avandych** [comment]
Something like this

```

public class GetStatusApiRequest
{
    [Required]
    [DefaultValue(6)]
    [DataMember(Order = 1)]
    public long Property1 { get; set; }

    [Required]
    [DefaultValue("acd73472-db80-4a68-9510-3af4814091cc")]
    [DataMember(Order = 2)]
    public string Property2 { get; set; }

    [DefaultValue(false)]
    [DataMember(Order = 3)]
    public bool Property3 { get; set; }

    [DataMember(Order = 4)]
    public bool Property4 { get; set; } = true;

    [IgnoreDataMember]
    [JsonIgnore]
    public string CacheKey => $"{nameof(GetStatusApiRequest)}_{this.Property1}_{this.Property2}";
}
```

**Comment by adityamandaleeka** [comment]
@avandych Have you tried measuring this without Debug logs enabled? Debug logging will add a non-trivial amount of performance overhead.

**Comment by avandych** [comment]
> @avandych Have you tried measuring this without Debug logs enabled? Debug logging will add a non-trivial amount of performance overhead.

On production, logging severity is higher and we don't use the default console logger.
We have a new theory that we plan to verify.

From the logs that I included here, it's not clear where the problem is and overhead may actually come from logging in these synthetic tests. On production, we found a client that is built on .net framework 4.8 and has Nagle algorithm enabled for service endpoints used to call the service in question, requests are mainly small POST's. We think though the problem during the test and in production manifests the same way(extended time in the pipeline) the reasons may be logging and using the different client to create load in a test environment and clients with Nagle algorithm enabled on production environment

**Comment by adityamandaleeka** [comment]
@avandych Let us know if you found out any more information about your hypothesis based on your testing.

**Comment by avandych** [comment]
@adityamandaleeka validated, after disabling nagle's algorithm on the client applications that produced majority of traffic, overhead in the middleware pipeline dropped under 1ms. Seems like our initial approach for reproducing the behavior wasn't correct from the start and the overhead that we received while testing was really from verbose logging, which created confusion.
Thanks for your help!
