### ISSUE TITLE
[Analyzer] RequestDelegate return value detection

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44316]
## Background and Motivation

`RequestDelegate` can be used with methods/lambdas that return a value that is then ignored.

Delegate signature:
https://github.com/dotnet/aspnetcore/blob/86c7e0100ab40a19fcccf6ee80550b44e8e62444/src/Http/Http.Abstractions/src/RequestDelegate.cs#L6-L11

Because `Task` is the base type of `Task<T>`, generic variance means it's possible to return `Task<T>` from a method that's used with `RequestDelegate`. The caller of the delegate never sees the value and it is ignored.

Example: https://github.com/dotnet/aspnetcore/issues/39956

## Proposed API

An analyzer that detects using a method or lambda that returns `Task<T>` with `RequestDelegate` and warns the user.

## Usage Examples

```cs
Task<string> HelloWorld(HttpContext c) => Task.FromResult("Hello " + c.Request.RouteValues["name"]);

endpoints.MapGet("/", HelloWorld); // <- detect bad method

endpoints.MapGet("/", (HttpContext c) => Task.FromResult("Hello " + c.Request.RouteValues["name"])); // <- detect bad lambda
```

Note that an async lambda can't get in this situation and doesn't need to be checked. The compiler detects a return value and prevents the lambda being converted to `RequestDelegate`:

```cs
RequestDelegate d = new RequestDelegate(async Task<string> (HttpContext context) =>
{
    await Task.Yield();
    return "hello world"; // <- compiler error
});
```

**Comment by davidfowl** [comment]
What does a "bad method" mean? We fixed this in .NET 7.

**Comment by davidfowl** [comment]
That works now. This is why the issue is closed.

**Comment by JamesNK** [comment]
The change was reverted later - https://github.com/dotnet/aspnetcore/pull/42519

**Comment by davidfowl** [comment]
So is this about trimming or something else?

**Comment by halter73** [comment]
API Review Notes:

- This especially important since this isn't caught at runtime and is likely misusage.

Category: Usage
Severity: Warning
