### ISSUE TITLE
ASP.Net Core 6 integration tests with WebApplicationFactory<TStartup>: How to pass program args?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#44321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a `public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup> where TStartup : class` and I need to pass command line arguments to `Progam.cs`. How to achieve that?

### Expected Behavior

Have a clear documentation and API how to pass command line arguments to `Program.cs` when doing integration tests with `WebApplicationFactory`

### .NET Version

6.0.109

**Comment by davidfowl** [comment]
What args are you trying to pass? Something tied to the WebApplicationBuilder hosting configuration or completely custom args?

**Comment by khteh** [comment]
Custom: `/inmemorydb` and `/seed`

**Comment by captainsafia** [comment]
@khteh Have you tried something like the following?

```csharp
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup> where TStartup : class
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseSettings("inmemorydb", "true");
        builder.UseSettings("seed", "2");
    }
}
```

**Comment by khteh** [comment]
```
error CS1061: 'IWebHostBuilder' does not contain a definition for 'UseSettings' and no accessible extension method 'UseSettings' accepting a first argument of type 'IWebHostBuilder' could be found
```

**Comment by davidfowl** [comment]
It's UseSetting* I fixed the post
