### ISSUE TITLE
[Analyzer] Add route constraint based on parameter type

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44320]
## Background and Motivation

Route parameters support type constraints. Constraints can be used to quickly reject URLs that don't match the constraint check.

The type constraints available to use aren't easily discoverable without looking up the list from documentation - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#route-constraints

## Proposed API

An analyzer that looks at route parameters and lambda/action parameters and suggests adding a constraint when:

* The parameter matches a route parameter by name.
* No type constraint is present on the route parameter.
* The .NET type has a matching route constraint, e.g. `int` type -> `int` constraint, `Guid` type -> `guid` constraint.

The analyzer message should mention that route constraints aren't a good solution for input validation. e.g.

> Don't use constraints for input validation. If constraints are used for input validation, invalid input results in a 404 Not Found response. Invalid input should produce a 400 Bad Request with an appropriate error message. Route constraints are used to disambiguate similar routes, not to validate the inputs for a particular route.

## Usage Examples

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/303201/193492271-6ba98955-4f57-409e-9e86-299cbb5491cd.png)

**Comment by halter73** [comment]
API Review Notes:

1. I think most of the time you do not want to do this. Most of the time a 400 is preferable to a 404.
2. This makes code more verbose for little benefit unless there would otherwise be a conflicting route.

API rejected.
