### ISSUE TITLE
Worker Service template project does not run as a windows service without additional steps

### ISSUE THREAD

**Issue by DanielRBowen** [dotnet/aspnetcore#44323]
### Describe the bug
The Worker Service template project does not run as a windows service without additional steps.

### To Reproduce
Create a new "Worker Service" project using a template with Visual Studio or CLI.
Publish the project and create the service using ```sc create [service name] binpath="[worker service exe path]"```
Start the service using ```sc start [service name]```

I have the steps to run it successfully background service at this [repo](https://github.com/DanielRBowen/WorkerService1).

Also, if changing the Host to a WebHost, the service will not run successfully. Unless, passing the WebHost into a WebHostService and passing that into the array of ServiceBases in ServiceBase.Run
```
var isService = !(Debugger.IsAttached || args.Contains("--console"));

if (isService)
{
    var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
    var pathToContentRoot = Path.GetDirectoryName(pathToExe);
    Directory.SetCurrentDirectory(pathToContentRoot);
}

if (isService)
{
    var webHostService = new WebHostService(webHost.Build());
    ServiceBase.Run(new ServiceBase[] { webHostService });
}
else
{
    await webHost.Build().RunAsync();
}
```

I wish to run the background service as a WebHost instead of just a Host so I can use a SignalR Hub on localhost to send service status updates to a Wpf application as a SignalR client. To make this work, the worker background service is used as a SignalR client as well.

### Exceptions (if any)
```
C:\Windows\system32>sc start Worker1
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.
```

**Comment by vlada-shubina** [comment]
Transferred to dotnet/aspnetcore, as it is related to `Worker Service` template.

**Comment by davidfowl** [comment]
@DanielRBowen the worker service project not meant to work out of the box with windows services. The sample code you have in the project seems to conflate lots of different scenarios making it hard to understand what you are trying to achieve. There are 2 documents that might be relevant to what you are trying to do:

- https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service
- https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio

Give those a read and see if they work for you.
