### ISSUE TITLE
GenerateWatchList fails in .NET 7.0 rc1 

### ISSUE THREAD

**Issue by JBergbom1** [dotnet/aspnetcore#44324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just updated our Blazor WASM project from .NET 6 to .NET 7 rc1 and I am running into issues when trying to run the project with `dotnet watch` on macOS. This has worked without issues previously, for several months on .NET 6.0.2.

The build fails immediately with the following errors:

```Error(s) finding watch items project file 'MainClient.csproj'
MSBuild output from target 'GenerateWatchList':

Build started 2022-10-03 12:19:59.
Build FAILED.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:00.00
```

Similarly, `dotnet run` fails with the only error being: `The build failed. Fix the build errors and run again.`

Restarting my computer allows `dotnet watch` to work again temporarily, but it seems that as soon as I pull something from the project repo it breaks again.

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

I found a similar but closed issue at https://github.com/dotnet/aspnetcore/issues/12700. But was not able to solve my problem from that.

The following is the content of the project's .csproj file:

```<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="$(Configuration) == 'Debug'" Command="cd JS &amp;&amp; npm run build" />
  </Target>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" Version="1.54.9" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.2.0" />
    <PackageReference Include="BlazorIntersectionObserver" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0-rc.1.22427.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0-rc.1.22427.2" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="7.0.0-rc.1.22426.10" />
    <PackageReference Include="System.Text.Json" Version="7.0.0-rc.1.22426.10" />
  </ItemGroup>

</Project>
```

**Comment by optimizasean** [comment]
I would like to add to that, `dotnet build` and `dotnet restore` also fail.

`dotnet build` failure:
```
MSBuild version 17.4.0-preview-22428-01+14c24b2d3 for .NET

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.00
```

`dotnet restore` fails without any output whatsoever.
Can't figure out how to move forward with this.
Reinstalled dotnet (after deleting all sdk and runtime) and no luck.

**Comment by tylermichael** [comment]
I think this might be related to https://github.com/dotnet/core/issues/7840

**Comment by tmat** [comment]
@JBergbom1 Is this still an issue with .NET 8 SDK? If so, would you mind running with `dotnet build -bl` and share the generated log (`msbuild.binlog`)?
