### ISSUE TITLE
Empty Blazor WebAssembly template should have a <title> in index.html

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#44335]
Being empty is great, but we shouldn't make it so empty that it lacks a [required](https://html.spec.whatwg.org/#the-title-element) HTML element.

**Comment by TanayParikh** [comment]
Looks like the empty blazor server template would benefit from the same change: https://github.com/dotnet/aspnetcore/blob/ba2d05c8d0214ee86d1d49467890f9279d43389e/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyBlazorServerWeb-CSharp/Pages/_Host.cshtml#L8-L13
