### ISSUE TITLE
does Blazor support  Multi Page Applications (MPA)?

### ISSUE THREAD

**Issue by sgf** [dotnet/aspnetcore#44338]
i want use C#  as client script in Multi Page Applications (MPA) .

but the documentation less information about MPA.

if support,how to do ?

`I've looked into existing issues, but there is no clear answer. Almost all previous issues were closed with no clear results, so I had to open a new one.`

**Comment by javiercn** [comment]
@sgf thanks for contacting us.

You can render components statically from MVC/Razor pages (if by MPA you mean traditionally server rendered applications). However, we do not have concrete components to deal with forms like we do for MVC/Web API, so you would need to create those yourself.

When rendering static markup, you won't get access to common Blazor functionality like event handlers or `@bind`

**Comment by sgf** [comment]
> @sgf thanks for contacting us.
> 
> You can render components statically from MVC/Razor pages (if by MPA you mean traditionally server rendered applications). However, we do not have concrete components to deal with forms like we do for MVC/Web API, so you would need to create those yourself.
> 
> When rendering static markup, you won't get access to common Blazor functionality like event handlers or `@bind` but you can render a form statically and post the data to a controller in the same way MVC does it.

Thanks, So the conclusion is that MPA is not currently supported.
