### ISSUE TITLE
ASP.NET core hybrid solution for SPA or PWA apps

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/aspnetcore#44331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I develop asp.net and asp.net core web sites for long times, asp.net is very good for backend but not have solution for new technology such as SPA or PWA for frontend developing and need use Reactjs, Vuejs and others JavaScript frameworks for client side. but these frameworks have some limitation and not integrated with asp.net. for example, just can user asp.net for backend and  JavaScript frameworks for frontend or cannot use Razor rendering or server side rendering is slow.

### Describe the solution you'd like

I like asp.net core have hybrid solution for SPA or PWA apps not need JavaScript frameworks but have such [this](https://dev.to/dcodeyt/building-a-single-page-app-without-frameworks-hl9) solution for client side and can use Razor for SSG and SSR rending and asp.net core instead of node.js for rendering performance. 

### Additional context

Mybe your suggestion that user Blazor or [reactjs.net](https://reactjs.net/) but l think if have JavaScript micro framework better reception with developers and no need use Reactjs, Vuejs  frameworks for many scenarios

**Comment by javiercn** [comment]
@mojtabakaviani thanks for contacting us.

Our solution for SPA and PWAs is Blazor. You can use Blazor Server which does all the rendering server-side. We also have this issue https://github.com/dotnet/aspnetcore/issues/38114 which would enable static site generation if that's what you are looking for.

We do not plan to create any micro-JS framework or similar solution.

**Comment by mojtabakaviani** [comment]
@javiercn thanks for reply.

I think just see count of developed frontend with popular javascript frameworks vs Blazor, Asp.net core have potential to more favorites if have own javascript solution for SPA and PWAs, because is more usable to full stack developers.

**Comment by javiercn** [comment]
@mojtabakaviani I am not sure I am following through, but I would say that most people use an existing framework like React/Angular/Vue. We already have integration with Angular and React in ASP.NET Core out of the box and we've shown how to integrate other frameworks like Vue or Svelte with ASP.NET Core in a similar way.

At this point we do not plan to offer further integration in this area.
