### ISSUE TITLE
Server Variables and Request Headers mutually exclusive in ASP.NET Core+

### ISSUE THREAD

**Issue by jaredtait** [dotnet/aspnetcore#44330]
In legacy .NET Framework apps, some authentication providers (questionably) set request headers, while others set server variables.  Our consuming code didn't mind in .NET Framework because they all found their way into Server Variables.

In ASP.NET Core+ it looks like Request Headers and Server Variables have become mutually exclusive.  Server Variables seem tucked away from the HTTPContext so that while debugging, they are a few steps further away to interrogate.  

What is the reasoning behind this direction?  Is it to better protect the security around Server Variables? Is this to break away from Server Variables/IIS?  The attitude seems to support Server Variables at arms length, but we are curious on the ASP.NET Core teams attitude and motivations are in moving Server Variables out of immediate grasp.

**Comment by davidfowl** [comment]
Merging server variables, form, headers, etc into a single collection was always really bad idea from a security POV. Most of that was a hold over from classic ASP which bled into ASP.NET. Server variables is an IIS concept (and I guess a php concept) that we expose in a read only way to access that state put in there by IIS and maybe IIS modules. It isn't something ASP.NET Core itself populates or uses for anything.

**Comment by davidfowl** [comment]
@twsouthwick this might be something to add as an option to the [System.Web adapters](https://github.com/dotnet/systemweb-adapters)

**Comment by Tratcher** [comment]
AspNetCore is designed to be portable with HTTP features as first class and server specific features as second class. Server Variables are IIS specific so they don't get the same level of exposure as the standard HTTP features.

**Comment by twsouthwick** [comment]
AFAIK, ASP.NET kept them separate unless you're using the `HttpRequest.Params` property. This was a collection of all headers, server variables, forms, and query values. The adapters does support this just as in the System.Web world, although it's index only (i.e. you can't iterate through it as server variables don't have a way to do list available entries).

@jaredtait Is the authentication provider you are using something you own or is it a 3rd party component. As @davidfowl alluded to, we have a set of [adapters](https://github.com/dotnet/systemweb-adapters) we've been working on to enable some ASP.NET Framework behaviors in ASP.NET Core. Depending on what your requirements are, they may be helpful.

**Comment by blowdart** [comment]
Plus, just to pile on, Server Variables aren't http request specific, so why would they be on the http context? :)

**Comment by adityamandaleeka** [comment]
> @jaredtait Is the authentication provider you are using something you own or is it a 3rd party component. As @davidfowl alluded to, we have a set of [adapters](https://github.com/dotnet/systemweb-adapters) we've been working on to enable some ASP.NET Framework behaviors in ASP.NET Core. Depending on what your requirements are, they may be helpful.

Yea this would be interesting to find out.

**Comment by jaredtait** [comment]
Thanks for the feedback, all.  

@twsouthwick, Our authentication providers are third party and operating with ISAPI modules that set Server Variables.  Moving everything to OIDC is the eventual goal so I hesitate to drive a requirement to the ASPNET Core team.  In the mean time we are using HttpContext.GetServerVariable() to ensure authentication is happening.

We have typically discouraged our devs from using Request.Params, but are discovering more recently is that the request headers seem to be copied into the Server Variables in .NET Framework only. We only discovered this when one authentication provider inserted a Server Variable and a Request Header, while the other only feeds a Request Header, but was still "working" in .NET Framework.

@blowdart, I don't disagree.  If there is another extension method to use for Server Variables on another object, I am interested, but that is not where modern solutions are going.

**Comment by adityamandaleeka** [comment]
Thanks for sharing the extra context @jaredtait. I'll close this issue for now. Feel free to open another issue if you run into more issues during migration (and be sure to check out the [migration work we've been doing](https://github.com/dotnet/systemweb-adapters) if you haven't already).
