### ISSUE TITLE
Auto CSRF token triggers a warning in the HTML validator

### ISSUE THREAD

**Issue by tmatt95** [dotnet/aspnetcore#44341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The automatically added CSRF token is failing the HTML validator.

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/1253138/193665520-40f2c9ac-efca-45f5-8bf4-dc3180e006dc.png">

### Expected Behavior

I would expect this to pass the validation as long as there was not any invalid HTML added by myself.

### Steps To Reproduce

1. Create a new dotnet core website.
2. Add a form to it.
3. Alter the program so it automatically adds the CSRF token.
4. Run the web page and look at the page source.
5. Copy the page source into the validator: [https://validator.w3.org/#validate_by_input](https://validator.w3.org/#validate_by_input ).

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: arm64
  Commit:       06aceb7015

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.400-preview.22330.6 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]
  6.0.401 [/usr/local/share/dotnet/sdk]
  7.0.100-rc.1.22431.12 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by javiercn** [comment]
@tmatt95 thanks for contacting us.

I am not sure why the validator is complaining but that is not invalid syntax. We do not think this is a problem in the framework nor the way we generate code, but an issue with either the document you are feeding to the validator or with the validator itself.

We had this behavior for many years without having any issue, so we are unlikely to change it unless we see compelling evidence that it creates a problem.

**Comment by tmatt95** [comment]
> @tmatt95 thanks for contacting us.
> 
> I am not sure why the validator is complaining but that is not invalid syntax. We do not think this is a problem in the framework nor the way we generate code, but an issue with either the document you are feeding to the validator or with the validator itself.
> 
> We had this behavior for many years without having any issue, so we are unlikely to change it unless we see compelling evidence that it creates a problem.

Thanks for getting back in touch. I had run the validator against the code previously and it had passed without an issue. 

I have had a look through the validators issue tracker and can find a number of issues related to this:
https://github.com/validator/validator/issues/1433
https://github.com/validator/validator/issues/1430

The change was made 6 days ago:
https://github.com/validator/validator/issues/1430#issuecomment-1260341084

It is currently only down as a warning and not an error.
