### ISSUE TITLE
AuthenticationSchemeOptions delegates don't have an async compatible alternative

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#44355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the AuthenticationSchemeOptions, I've found myself wanting to write a response to the `HttpContext` but you get an exception when using `Write(...)` as ASP NET Core doesn't allow synchronous operations by default. The ovious fix for this is to make your code asynchronous via `WriteAsync(...)` and await the `Task`, however, the AuthenticationSchemeOptions delegates cannot be async as none of them have `Task<T>` overloads.

### Expected Behavior

```cs
authBuilder.AddPolicyScheme("SomeScheme", "SomeScheme", x =>
{
    x.ForwardDefaultSelector = async (httpContext) => // <-- Current problem: ForwardDefaultSelector does not have Func<HttpContext, Task<string>> overload.
    {
        async Task WriteResponse(HttpStatusCode statusCode, string message)
        {
            httpContext.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
            await httpContext.Response.BodyWriter.WriteAsync(Encoding.UTF8.GetBytes(message))
            httpContext.Response.BodyWriter.Complete();
        }

        var headers = httpContext.Request.Headers;
        if (!headers.ContainsKey("x-header"))
        {
            await WriteResponse(HttpStatusCode.Unauthorized, "Missing header");
            return Task.FromResult(string.Empty); // <-- Current problem: delegate does not accept Task<string>
        }
    }
}
```

### .NET Version

.NET 6

**Comment by Tratcher** [comment]
Producing a response from these delegates would almost always be incorrect. This is called from other code that's trying to decide how to produce a response. You'd likely cause secondary exceptions like unable to modify the status code after the response has started.
