### ISSUE TITLE
View in Area missing imports from Views/Shared/_ViewImports.cshtml

### ISSUE THREAD

**Issue by cthompson92** [dotnet/aspnetcore#44356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I previously asked a [question on the Docs repo](https://github.com/dotnet/AspNetCore.Docs/issues/27031).

The answer there pointed to [this article](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0#area-folder-structure).

Based on that article, I attempted to delete the various extra ViewImports files in a repo, and created a single `Views/Shared/_ViewImports.cshtml`. However, this has introduced lots of build errors for missing namespaces, whereas the solution built successfully previously.

For full clarity, I went from this:
```
.
+-- Views
|   +-- _ViewImports.cshtml
+-- Areas
|   +-- Area1
|       +-- Views
|           +-- MyView.cshtml
|           +-- _ViewImports.cshtml
```

To
```
.
+-- Views
|   +-- Shared
|       +-- _ViewImports.cshtml
|   +-- _ViewImports.cshtml
+-- Areas
|   +-- Area1
|       +-- Views
|           +-- MyView.cshtml
```

And now `Areas/Area1/Views/MyView.cshtml` has build errors for missing namespaces.

### Expected Behavior

The views inside of my Areas should have the namespaces from 'Views/Shared/_ViewImports.cshtml` available, and neither `Areas/Area1/Views/_ViewImports.cshtml` nor `Areas/Area1/Views/Shared/_ViewImports.cshtml` need to exist.

### Steps To Reproduce

In a fresh ASP.NET6 MVC project:
1. Scaffold out new Area
2. Add an `@using` directive to `Views/Shared/_ViewImports.cshtml`
3. Add a view in the new Area which requires the `@using` directive defined in step 2
4. Build the project and receive build errors in this new View

Below is a reproduction via the above steps:
[ViewImporst.zip](https://github.com/dotnet/aspnetcore/files/9708134/ViewImporst.zip)

### .NET Version

6.0.400

### Anything else?

I previously asked a [question on the Docs repo](https://github.com/dotnet/AspNetCore.Docs/issues/27031).

The answer there pointed to [this article](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0#area-folder-structure).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The discovery of  ViewImports is not the same as the discovery of Views. Hence, the shared folder is not relevant for them. You can learn more about it from this specific section in the docs: [aren't following the same discov](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0#_viewimportscshtml)

Closing as by-design.
