### ISSUE TITLE
.NET 7 RC1 "dotnet new grpc" creates a project that references a package which is not compatible with .NET 7

### ISSUE THREAD

**Issue by nslusher-sf** [dotnet/aspnetcore#44367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Install .NET 7 RC1 SDK
2. Run `dotnet new grpc`
3. Observe that the .csproj file created references Grpc.AspNetCore version 2.45.0 which is not listed as being compatible with .NET 7:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.45.0" />
  </ItemGroup>

</Project>
```

### Expected Behavior

The Grpc.AspNetCore version in the .csproj file created should be 2.49.0 which is the first version to list support for .NET 7.

### Steps To Reproduce

See description of bug.

### .NET Version

7.0.100-rc.1.22431.12

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
Already done: https://github.com/dotnet/aspnetcore/pull/43709

References are updated in .NET 7 RTM.
