### ISSUE TITLE
[Blazor] Isolated CSS is not entirely isolated

### ISSUE THREAD

**Issue by WesThompson** [dotnet/aspnetcore#44387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using CSS Isolation, if...

1. Two components (A and B) use the same CSS class name
2. B is a child component of A
3. B is setting styles for child elements of that class

...then the CSS from A is also applied to the child elements in B.

I am not sure if this is truly a bug or just a limitation of CSS, but I didn't see anything in the [CSS Isolation docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0) about this specifically. Although, the section at the top states:

> Isolate CSS styles to individual pages, views, and components to reduce or avoid:
> - Style conflicts in nested content.

So, I guess you could read that as "reduce conflicts" and not assume there will never be any. If it is indeed expected behavior, then a highlighted warning or something in the docs stating that it's not always _entirely_ isolated would be appreciated.

### Expected Behavior

CSS is completely isolated to its own component/scope and has no conflicts with nested content.

### Steps To Reproduce

1. Create Blazor project (Server or WASM)
2. Create two components with isolated CSS
3. Add one component to the other component's DOM
4. Add CSS class to container element of child component
5. Add same CSS class to element in child component
6. Add child element to element from step 5
7. Add CSS rule to element from step 6 using the identical class name and child selector syntax

Repo demonstrating the issue: https://github.com/WesThompson/CSS_Isolation_Issue

### .NET Version

6.0/7.0

### Anything else?

As you can see if you run the project, the style for the child element looks something like:
````css
div span[b-ikhpxwtf7b] {
    text-decoration: underline;
}
````
However, the element is also showing up red from the parent component's scoped `div` style. If you add the scope attribute to all selectors it seems to fix the scopes. For example:
````css
div[b-ikhpxwtf7b] span[b-ikhpxwtf7b] {
    text-decoration: underline;
}
````
However, I know this would prevent you from using a common CSS file unless you did something like [Customize scope identifier format](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#customize-scope-identifier-format).

**Comment by javiercn** [comment]
@WesThompson thanks for contacting us.

CSS isolation is working correctly here. The issue with your sample is that color is an inherited property, which means that children element get their value automatically when set on a parent node in the hierarchy. See https://developer.mozilla.org/en-US/docs/Web/CSS/color#formal_definition for more details.

CSS isolation works at the rule level, the rule in Index.razor.css is not being applied to the div in the Component.razor file. CSS isolation aims to prevent conflicts on rule application but does not change the behavior around CSS inheritance rules.
