### ISSUE TITLE
Remove ResponseCookies._enableCookieNameEncoding compat switch

### ISSUE THREAD

**Issue by vonzshik** [dotnet/aspnetcore#44396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

https://github.com/dotnet/aspnetcore/blob/ce60f0d10c0adb79b2b824f5da05e41e1199f6cf/src/Http/Http/src/Internal/ResponseCookies.cs#L17-L18

Right now every time a new `ResponseCookies` instance is created, it's going to attempt to get the switch, which can lead to [lock contentions](https://github.com/dotnet/runtime/blob/8eb413818f5b95e750be5cf4148a3a9714ddc331/src/libraries/System.Private.CoreLib/src/System/AppContext.cs#L100-L107). AppContext switches are supposed to be set only once at the start of the app, so the field can be marked as static (as it's not going to change). This can also help `RequestCookieCollection`, which also attempts to get the exact same switch every time it parses cookies:

https://github.com/dotnet/aspnetcore/blob/ce60f0d10c0adb79b2b824f5da05e41e1199f6cf/src/Http/Http/src/Internal/RequestCookieCollection.cs#L61-L62

### Describe the solution you'd like

Change `ResponseCookies._enableCookieNameEncoding` to be a static field.

**Comment by Tratcher** [comment]
This was a temporary compat switch, it should just be removed for 8.0.
