### ISSUE TITLE
Invalid redirect to RedirectUrl on error during 2FA

### ISSUE THREAD

**Issue by vladdy-moses** [dotnet/aspnetcore#44395]
## Summary

[CookieAuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L367) redirects user to ReturnUrl path after successful sign-in event.
But it is not appropriate for [TwoFactorUserIdCookie](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityCookiesBuilderExtensions.cs#L98).

## Motivation and goals

Sometimes something goes wrong after `SignInManager<T>.PasswordSignInAsync` with `RequiresTwoFactor` result.
And we want to render page with invalid ModelState, but ASP.NET Core redirects user to RedirectUri path.

Now in our projects we disable `OnRedirectToReturnUrl` event for `IdentityConstants.TwoFactorUserIdScheme`, but it looks like a crutch.

## In scope

There is default ASP.NET Core app with Identity and enabled authentication and authorization.
The main page has `[AuthorizeAttribute]`.
Also there is `/Account/Login` page (ex. Razor Page is used) with `[AllowAnonymousAttribute]`.

If anonymous user opens our app, it will be redirected to '/Account/Login?RedirectUri=/` path.

After signing in by using `SignInManager<T>.PasswordSignInAsync` app is handling IdentityResult.
If result is `RequiresTwoFactor` our app make some logic (ex. form and send email for 2FA).
And if error is happened we should display it by using ModelState, for example.

But if path of sign-in page is default ([defined here](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationDefaults.cs#L27) and [here](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/PostConfigureCookieAuthenticationOptions.cs#L55)) default cookie authentication handler ([here](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L367)) make `Context.Redirect` to ReturnUrl.

It happens because SignInManager actually signed in IdentityConstants.TwoFactorUserIdScheme [here](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L792) and cookie authentication handler runs for that scheme.

I think default cookie config [here](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L72) and [here](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityCookiesBuilderExtensions.cs#L98) should be changed.
For example we can make `o.Events.OnRedirectToReturnUrl = _ => Task.CompletedTask;` for disable redirection for 2fa auth scheme.

## Out of scope

This proposal covers only default asp.net identity config.

## Risks / unknowns

Perhaps in some applications such a redirection is valid.

## Examples

Sample asp.net core 6 for minimal APIs was created [here](https://github.com/vladdy-moses/aspnetcore-2fa-redirect/blob/main/Program.cs#L50).
This app creates sample user with 2FA and tries to sign-in.
Also there are some workarounds for now.

**Comment by adityamandaleeka** [comment]
Thanks for filing a detailed issue @vladdy-moses.

**Comment by HaoK** [comment]
This indeed looks like a bug, and your suggested fix of explicitly doing `o.Events.OnRedirectToReturnUrl = _ => Task.CompletedTask` for the two factor cookie looks reasonable.

We'll fix this in 8.0, are you interested in contributing a PR with this fix?

**Comment by vladdy-moses** [comment]
> are you interested in contributing a PR with this fix?

I'm very appreciate your offer and already made PR #44435.

All tests are passed, but also I'd like to write new test for reproduce this issue problem.
Should I open a new issue for that?

**Comment by HaoK** [comment]
You can just add the test for this issue in that PR
