### ISSUE TITLE
[Analyzer] Warn about `HttpRequest.Form`

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

`HttpRequest.Form` reads the request body and can cause performance issues. See https://learn.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0#prefer-readformasync-over-requestform

### Describe the solution you'd like

An analyzer that detects `HttpRequest.Form` and recommends `HttpRequest.ReadFormAsync`.

**Comment by davidfowl** [comment]
On by default? In some cases the form was already read. Can we only do this in async contexts?

**Comment by JamesNK** [comment]
> On by default?

Yes, but we can change what level. e.g. warning vs suggestion.

> In some cases the form was already read.

We can't figure that out from an analyzer. If it was a warning, then people could suppress it in that method. We need to way up the pain of people getting unnecessary warnings vs the pain of blocking on `Request.Form`.

> Can we only do this in async contexts?

Yeah, we can detect where it is used and if it's in an async method.

**Comment by Tratcher** [comment]
Since the results are cached, ReadFormAsync is only necessary the first time. E.g. you could do ReadFormAsync followed by From in the same method and we shouldn't flag that.
MVC will also usually read the form for you before calling your controller so Form is fine there too.
This shouldn't be a warning.

**Comment by JamesNK** [comment]
Replaced by https://github.com/dotnet/aspnetcore/issues/47460 which uses the template
