### ISSUE TITLE
Override `ToString` on the `Microsoft.AspNetCore.Http.CookieOptions` class.

### ISSUE THREAD

**Issue by Korporal** [dotnet/aspnetcore#44401]
## Background and Motivation

The `CookieOptions` class represents the various options that can appear in a cookie header attribute string or in a `javascript` call, to set or update a cookie. The format of the string is defined [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#syntax).  Since the format is formally defined, making `ToString` implement that format would be a help as it would reduce the risk of incorrect formats in code that needs to "manually" build the cookie settings string, for example using javascript interop in Blazor to create a cookie. Also for any arbitrary example of a `CookieOptions` there is always one and only one correct string representation.

## Proposed API

```cs
public override ToString()
{
            StringBuilder builder = new();

            string format = "ddd, dd MMM yyyy HH:mm:ss 'GMT'";

            // SEE: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#syntax

            if (Expires.HasValue)
                builder.Append(@$"; Expires={Expires.Value.ToUniversalTime().ToString(format)}");

            if (MaxAge.HasValue)
                builder.Append($"; Max-Age={MaxAge.Value.TotalSeconds}");

            if (Domain != null)
                builder.Append($"; Domain={Domain}");

            if (Path != null)
                builder.Append($"; Path={Path}");
            else
                builder.Append($"; Path=/");

            if (Secure)
                builder.Append("; Secure");

            if (HttpOnly)
                builder.Append($"; HttpOnly");

            builder.Append($"; SameSite={Enum.GetName(SameSite)}");

            builder.Append('"');
            builder.Append(';');

            return builder.ToString();

}

```
## Usage Examples

We can use javascript interop in Blazor, to create a cookie for the current browser session, doing this from .Net requires us to carefully craft the cookie options string which can be error prone.

## Alternative Designs

The code isn't too hard but could easily contain subtle errors if written by customers.

## Risks

I think risks are very low since `CookieOptions` currently does not override `ToString`.

**Comment by Tratcher** [comment]
There's actually a new API for this in 7.0: CookieOptions.CreateCookieHeader(name, value).
https://github.com/dotnet/aspnetcore/pull/42119
This formats the whole cookie, not just the options part.

**Comment by Korporal** [comment]
@Tratcher  - Hi, that's great, I will take a look at this certinaly. May I ask, could I use that to populate a string that I can then use in Javascript's `eval` function? I have C# code that builds this string for example:

`document.cookie="lti.1.1.blazor-server-app=testdata; Path=/; Secure; HttpOnly; SameSite=None";`

To build that we need to construct the trailing `"lti.1.1.blazor-server-app=testdata; Path=/; Secure; HttpOnly; SameSite=None";` string, that is, just the options are used to build that part.

**Comment by Tratcher** [comment]
Yes, this produces the full `<name>=<value>; <options>`, which looks like what you need?

**Comment by Korporal** [comment]
> Yes, this produces the full `<name>=<value>; <options>`, which looks like what you need?

Yes, this sounds exactly what I was seeking!
