### ISSUE TITLE
Blazor inserted HTML comment tags cause layout issues

### ISSUE THREAD

**Issue by robmilton** [dotnet/aspnetcore#44404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The HTML comment tags (`<!--!-->`) appear to cause layout issues in some cases.  There are many issues/questions about this topic, and the response has been that these tags are necessary.  In most cases these tags don't cause layout issues, but in some cases it appears they do.

Blazor injects HTML comment tags between several of the buttons in the page generated from the code below.  And these comment tags cause spacing issues (additional horizontal space) between the buttons.  If we remove the `<!--!-->` from the page the spacing issue goes away.

```
<div class="container" style="margin-top:20px;">
    <div class="row justify-content-center">
        <div class="col-sm-10 text-center">
            @if (isSysAdmin)
            {
                <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.Users))" @onclick="@(e => SetView(AdminViews.Users))">Users / Index</button>
            }
            <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.ProgramProject))" @onclick="@(e => SetView(AdminViews.ProgramProject))">Programs / Projects</button>
            <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.KeywordsOPR))" @onclick="@(e => SetView(AdminViews.KeywordsOPR))">Keywords / OPRs</button>
            <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.LocationCopyrights))" @onclick="@(e => SetView(AdminViews.LocationCopyrights))">Locations / Copyrights</button>
            <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.Companies))" @onclick="@(e => SetView(AdminViews.Companies))">Companies</button>
            @if (isSysAdmin)
            {
                <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.ConsolidateUsers))" @onclick="@(e => SetView(AdminViews.ConsolidateUsers))">Consolidate Users</button>
                <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.DataMigration))" @onclick="@(e => SetView(AdminViews.DataMigration))">Data Migration</button>
            }
            <button type="button" class="btn btn-secondary btn-sm mb-1 mr-1 @(IsViewActive(AdminViews.SearchIndex))" @onclick="@(e => SetView(AdminViews.SearchIndex))">Search Indexing</button>
            <button type="button" id="btnClose" class="btn btn-primary btn-sm mb-1 ml-1" @onclick="@(e => Close())">Exit</button>
        </div>
    </div>
...
```

### Expected Behavior

HTML comment tags (`<!--!-->`) shouldn't cause layout issues.

### Steps To Reproduce

Easy to reproduce as this is a well-known issue.  As for the spacing issues see the "Describe the bug" section above.

### Exceptions (if any)

None

### .NET Version

6.0.401

### Anything else?

![image](https://user-images.githubusercontent.com/94461/194431167-a779462d-827a-490b-a41c-a44aacd1e8c0.png)

**Comment by javiercn** [comment]
@robmilton thanks for contacting us.

Whitespace between the tags should collapse, the comments should not prevent that. I think if that's the case, it is a browser bug. 
It is very likely that this might be caused by the CRLF at the end of your button tags. See this answer for more details: https://stackoverflow.com/a/43164752

Unfortunately, inserting marker comments in the DOM is a fundamental Blazor behavior, so we are unlikely to change this area.

**Comment by robmilton** [comment]
@javiercn thanks for the response.  You were right about the CRLF at the end of the button tags.  I should have tested that.  However, why is this causing a layout problem working with Blazor when it doesn't seem happen in general with HTML?

Thanks again for the response!

**Comment by robmilton** [comment]
I wish this wouldn't be closed until someone answers my last questions.  

1. Is Blazor inserting the comment tags (`<!--!-->`) because of the CRLFs?
2. If so, why?  And why only some places where there are CRLFs?

**Comment by javiercn** [comment]
> just noticed something interesting. When I remove the CRLF in the code the comment tags (`<!--!-->`) are also removed. Why would these comment tags be inserted when the CRLFs are present and removed when the CRLFs are removed?

I am not sure how you are removing them, but I suspect it is through the developer tools, so that would be a question for the browser vendors.

**Comment by javiercn** [comment]
> 1. Is Blazor inserting the comment tags (`<!--!-->`) because of the CRLFs?

We would need to look at the exact blazor code and dig into the renderer code to fully confirm, but Blazor inserts comments to delimitate where a component starts and ends. Otherwise, you can't have components with multiple top-level elements.

**Comment by javiercn** [comment]
> 2\. If so, why?  And why only some places where there are CRLFs?

I do not think Blazor places any CLRF, this is likely in your code or in something that the browser introduces.
