### ISSUE TITLE
Port tunneling doesn't work with Blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44414]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Port-tunneling-doesnt-work-with-Blazor/10162604)._

---
Like the title says. Normal sites work fine, but a client side Blazor app will not open up the page. The address bar remains with "about:blank" and never does anything. Eventually VS returns the following:

Version 17.4.0 Preview 2.1

![image](https://user-images.githubusercontent.com/1821173/194627811-450ed279-d95d-41e9-a475-e82131664d4c.png)

---
#### Feedback Bot on 10/3/2022, 02:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
That URL appears to have a host and colon, but no port? That's not a valid url. Do we know what component generates this and how it's expected to be used?
`wss://938921tg-7172.use.rel.tunnels.api.visualstuido.com:/`

**Comment by tbasallo** [comment]
Just to be clear, this is part of the VS Port Tunneling Preview:

https://devblogs.microsoft.com/visualstudio/introducing-private-preview-port-tunneling-visual-studio-for-asp-net-core-projects/

**Comment by Tratcher** [comment]
@sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks, I have reactivated the original Dev Com issue https://developercommunity.visualstudio.com/t/Port-tunneling-doesnt-work-with-Blazor/10162604. We will take a look.

cc @vijayrkn @BillHiebert

**Comment by tbasallo** [comment]
@TanayParikh can you please provide some context for closing this. Is it not possible to EVER make this work or not right now? 
As far as use case, looking to test client side Blazor on actual devices (the use case for Port Tunneling feature).

**Comment by TanayParikh** [comment]
This issue was closed out here as it's being tracked using the developer community ticket: https://developercommunity.visualstudio.com/t/Port-tunneling-doesnt-work-with-Blazor/10162604
