### ISSUE TITLE
Refreshing Cookie Authentication Cookie Issue with HttpClient Causes Weird Caching Issue

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#44427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have been spending the past day tracking a very tricky issue in a very involved scenario with my solution.  I finally landed on a viable diagnosis this morning and determined a workaround.  I debated whether I should have created this issue here as I have spent a considerable amount of time on this already.  However, I cannot help but to think I have landed on a weird bug here and wanted to start the conversation to be sure, or maybe to augment my understanding, 

Unfortunately, this is an incredibly involved scenario and I cannot think of any way to quickly reproduce it for you with a code sample which I know you ask for and I acknowledge that I will be failing you here in that regard up front (I will continue to see if there's a way to do this, if absolutely necessary, however).

Some context:

**Applications:**
Application A is a Blazor Server-side application
Application B is a WebAPI content application which accepts calls from Application A via `HttpClient` POST calls

Notes:
- Both applications are using the same application name for authentication ticket data protection so cookies made from Application A can be read by Application B and vice versa
- In much the same way as #20850 (which I thought might be related upon searching but is not), I assign the `.Identity.Application` cookie to the `HttpClient` POST message request and make the call.

**Browsers:**
Browser A is Chrome and is connected to Application A via Blazor Server-side circuit and is signed in with Oauth2 Identity A
Browser B is Edge and is connected to Application A via Blazor Server-side circuit and is signed in with Oauth2 Identity B

**Process:**
Upon a particular view/control load in Application A, a call is made from Application A to Application B via `HttpClient` POST to produce content that is subsequently displayed in Application A.  This is where this problem arises.

From the outset, interspersing and alternating calls between Browser A and B to Application A (and subsequently Application B) work perfectly and as expected.  Identities are reported as expected and everything works well.  I can go back and forth between both browsers ad infinitum and everything works as expected and state is reflected perfectly.  

The issue occurs when the cookie authentication ticket is determined to need a refresh either by checking its sliding expiration or validating the principal during the `HttpClient` POST on Application B.  

If a new cookie authentication ticket is refreshed during this call in Application B, _things start to get weird_.  Namely, the identity of subsequent calls via `HttpClient` from Application A starts to reflect the identity of the last saved authentication ticket in Application B.

So:

1. Browser A loads view from Application A which generates `HttpClient` POST call to Application B, passing Identity A cookie
2. Application B determines a new authentication ticket is required and creates a new ticket under the identity of Identity A
3. Browser B loads view from Application A which generates `HttpClient` POST call to Application B, passing along Browser B's cookie (which describes Identity B)
4. During this request originated by Browser B which has the identity of Identity B, Application B _reports the identity to be **Identity A**_

_The particularly weird part is that step four occurs even if I do not assign cookies to Application A's request during step three._

I have been able to work around this in the meantime by using the following post-configure configuration in Application B:

```
public class PostConfigureCookieAuthenticationOptions : IPostConfigureOptions<CookieAuthenticationOptions>
{
	public void PostConfigure(string name, CookieAuthenticationOptions options)
	{
		options.Events.OnCheckSlidingExpiration = x =>
		                                          {
			                                          x.ShouldRenew = false;
			                                          return Task.CompletedTask;
		                                          };
		options.Events.OnValidatePrincipal = x =>
		                                     {
			                                     x.ShouldRenew = false;
			                                     return Task.CompletedTask;
		                                     };
	}
}
```

Also, it is worth noting that this issue also does not occur if I instantiate `HttpClient` directly and dispose it immediately after the call.  As such, this seems to be related to `IHttpClientFactory` as well.

Again I am not sure if there's something I am overlooking in my configuration here.  I am looking for a "did you turn it off and turn it back on again" or hopefully some other "duh" guidance that will alleviate my concern.

Thank you for any consideration, suggestions, clarification you can provide.

### Exceptions (if any)

NA

### .NET Version

It is reporting `7.0.100-rc.1.22431.12` but all my projects are `net6.0`

### Anything else?

You all are great and do excellent work out there :)  Thank you so much for being the giant whose shoulders we stand on.  Proudly. <3

**Comment by javiercn** [comment]
@Mike-E-angelo thanks for contacting us.

Unfortunately, the scenario you are describing is outside of the scope that we can deal with here. 

My "money" is in your usage of `IHttpClientFactory` as per
> Also, it is worth noting that this issue also does not occur if I instantiate HttpClient directly and dispose it immediately after the call. As such, this seems to be related to IHttpClientFactory as well.

Very likely you are not accounting for the fact that IHttpClientFactory creates its own DI scopes and reuses them, which in your case if you are passing user info is leading to that info leaking across user requests (assuming you are capturing the cookie from one request and sending it on another request through HttpClient).

I am sure you likely have reasons to have chosen this approach, but I would encourage you to think of potential alternatives, as what you have described in the issue seems complicated and prone to security issues.

**Comment by Mike-E-angelo** [comment]
Thank you for your reply here @javiercn.  Your time and assistance is appreciated.

> which in your case if you are passing user info is leading to that info leaking across user requests (assuming you are capturing the cookie from one request and sending it on another request through HttpClient).

I wanted be sure I understood what you mean here before agreeing with you and letting this go.  As far as I understand, I am using my own form of what is known [as header propagation](https://medium.com/@no0law1/propagate-headers-with-net-core-web-api-4d72cb3b2876) which is an offered feature of ASP.NET Core.

(I couldn't get this to work using your package so maybe I have this misunderstood -- it is also unclear to me if this is supposed to work for Blazor server-side applications)

To be certain, I am not attaching user info to the `HttpClient` but to `HttpRequestMessage`s which are newed up for a request and then left for garbage collection.  It is unclear to me how this would leak across requests as the message is a transient component, correct?  Here's a bit of pertinent code I use to create the `HttpMessageRequest` (note that `ClientState` gets the cookie value from the Blazor browser host but as I note this issue occurs even if I do not apply the header and only occurs after the authentication ticket is rewritten):

```
sealed class Message : IResult<HttpRequestMessage>
{
	readonly string     _address;
	readonly ApplyState _state;

	public Message(ApplyState state) : this("preview/generate", state) {}

	public Message(string address, ApplyState state)
	{
		_address = address;
		_state   = state;
	}

	public HttpRequestMessage Get()
	{
		var result = new HttpRequestMessage(HttpMethod.Post, _address);
		_state.Execute(result.Headers); // The issue will even occur if i skip this line on multiple requests
		return result;
	}
}

public sealed class ApplyState : ICommand<HttpRequestHeaders>
{
	readonly ClientState _state;
	readonly string      _name;

	public ApplyState(ClientState state) : this(state, CookieHeaderName.Default) {}

	public ApplyState(ClientState state, string name)
	{
		_state = state;
		_name  = name;
		_state = state;
		_name  = name;
	}

	public void Execute(HttpRequestHeaders parameter)
	{
		var state = _state.Get();
		if (state.Success && state.Value is not null)
		{
			parameter.Add(_name, state.Value);
		}
	}
}
```

Are you able to tell me how the above would leak user information across requests?  Any resources/links you can provide would be greatly appreciated.  Thank you again for your time.

**Comment by javiercn** [comment]
> (I couldn't get this to work using your package so maybe I have this misunderstood -- it is also unclear to me if this is supposed to work for Blazor server-side applications)

No it is not. Blazor applications do not run in the context of an HttpRequest.

It is impossible for us to tell you what is going on here due to the complexity of what you are trying to do. There are many things that can go wrong and too many details missing for us to be accurate as to what is happening/not happening.

In general, header propagation works because things execute in the same logical call context. Which I do not know if it's the case in your situation.

**Comment by Mike-E-angelo** [comment]
OK @javiercn thank you.  Unfortunately, I am really finding it difficult to brave through a "simple" repro for you.  The repro would be simple, but getting there would be not.  It's easily a day or so of work.

The problem occurs when two services share the same data application name and one application rewrites a ticket authentication under an HttpClient call.  Maybe I am not processing the response headers and that could be part of it.  In any case, I am OK with my workaround for now and will explore further if I encounter this area again.

Thank you again for your time.
