### ISSUE TITLE
Fine-grained override of `OAuthHandler.HandleRemoteAuthenticateAsync`

### ISSUE THREAD

**Issue by LeaFrock** [dotnet/aspnetcore#44424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A standard URL of `signin-oauth` is like `mydomain/signin-oauth?code=xxx&state=xxx&...`. But in the real world, there're still some providers not strictly under the rule.

For example, 

WeChat limit the length of `state` so [here](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/rel/6.0.11/src/AspNet.Security.OAuth.Weixin/WeixinAuthenticationHandler.cs#L165) does a state-move trick to avoid `state too long` error. The side effect is that, the sign-in URL will be like `mydomain/signin-oauth?code=xxx&state=<non-sense value>&_oauthstate=<actual state>&...`. 

Alipay uses the name `auth_code` instead of `code`, so the sign-in URL will be like `mydomain/signin-oauth?auth_code=xxx&state=xxx&...`.

Of course, we can override the whole `HandleRemoteAuthenticateAsync`. But it would be better to reuse codes of base method, as the difference is very small actually. Also, reusing codes of the base method can enjoy the maintenance benefits by future package upgrade.

And currently the workaround (or trick) is similar to the following,

```csharp
 protected override Task<HandleRequestResult> HandleRemoteAuthenticateAsync()
    {
        var query = Request.Query;
        if (query.TryGetValue("auth_code", out var authCode))
        {
            // The base `HandleRemoteAuthenticateAsync` requires that `Request.Query` must contain the key called `code`,
            // which is actually the same as `auth_code` by Alipay's design, but `Request.Query` does not have `Add` operation.
            // So here is a trick to get the private `Store` dictionary of `QueryCollection`.
            var queryStore = query.ToDictionary(c => c.Key, c => c.Value, StringComparer.OrdinalIgnoreCase);
            queryStore["code"] = authCode;
            Request.QueryString = QueryString.Create(queryStore);
        }

        return base.HandleRemoteAuthenticateAsync();
    }
```

It depends on the concrete implement of `Request.Query` and produces extra allocations.

### Describe the solution you'd like

Could it be possible providing a partial override for `state` and `code` instead of hard coding?

```csharp

protected override async Task<HandleRequestResult> HandleRemoteAuthenticateAsync()
{
            var query = Request.Query;

            var state = query["state"];  // ResolveState()
            var properties = Options.StateDataFormat.Unprotect(state);

            //....

            var code = query["code"];  // ResolveCode()

            if (StringValues.IsNullOrEmpty(code))
            {
                return HandleRequestResult.Fail("Code was not found.", properties);
            }
            //...
}

protected virtual string ResolveState() => Request.Query["state"];

protected virtual string ResolveCode() => Request.Query["code"];

```

Or other ideas which provide a fine-grained override.

**Comment by martincostello** [comment]
Similar to #26540 in terms of having to override wholesale to tweak a detail. Again though this seems to be tempered by the fact the overrides are to deal with off-spec implementations.

**Comment by LeaFrock** [comment]
> having to override wholesale to tweak a detail

😿

**Comment by blowdart** [comment]
As in the previous issue, 2, or 3 provides isn't enough for us to add a lot of tweak points, even if one is LinkedIn :) 

So I'm afraid I'm going to close this.
