### ISSUE TITLE
QuickGrid Template Column with button click refreshes from database on every click when filtered.

### ISSUE THREAD

**Issue by marqdouj** [dotnet/aspnetcore#44432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wanted to capture a click event when the user clicks on the ID row/column.

I could not find anywhere in the QuickGrid docs (https://aspnet.github.io/quickgridsamples/datasources/) on how to accomplish this
so I tried to do this using a TemplateColumn with a button. 

	<TemplateColumn Title="ID">
		<button type="button" class="btn btn-link" @onclick="@(() => ColumnClick(context))">@context.ID</button>
	</TemplateColumn>
    
    private void ColumnClick(GROUP_MASTER item)
    {
        Console.WriteLine(item.NAME);
    }

I would expect that when I click on the button the only thing that would happen is that the NAME should be written to the console. 
If I was using an EF InMemoryDatabase then eveything works as expected. 
If I was using an SQL Server database (in this case, localdb) then I had these issues:

When clicking on the button for the first time that data is refreshed from the database. Then every click after that works as expected.
Filtered. When a filter is applied to the IQueryable then the data is refershed from the database every time a button is clicked.

### Expected Behavior

I would expect that when I click on the button the only thing that would happen is that the NAME should be written to the console.

### Steps To Reproduce

https://github.com/marqdouj/QuickGridIssues

**Comment by javiercn** [comment]
@marqdouj thanks for contacting us.

This behavior is expected and by design. When you handle an event Blazor will automatically trigger a re-render to refresh the UI. You can control this behavior by overriding `ShouldRender()` on your component.

```code
protected override bool ShouldRender()
{
    if(!_shouldRender){
      _shouldRender = true;
      return false;
    }
    return base.ShouldRender();       
}

And on your handler you set _shouldRender = false;
```

**Comment by marqdouj** [comment]
Thanks, javiercn - worked like a charm!

This leads me to a related question then - is there a way to tell the grid to not reload the items when being refreshed (by blazor) but just use the items it has already loaded?
Say for example, I just want to update a label but there is no need to refresh the items from the database?

**Comment by marqdouj** [comment]
thanks, appreciate it.

**Comment by SteveSandersonMS** [comment]
@marqdouj I'd recommend that, if you need to limit the number of times a query runs, that you don't execute the query as part of the rendering flow.

If you have code like this:

```razor
<QuickGrid Items="@MyDbContext.Documents.Where(d => d.CategoryId == currentCategoryId)">
```

... then you're performing the query on every render. Instead you might consider defining an `IQueryable<T>` field on your component and replacing it only when the filter condition changes. For example,

```razor
<QuickGrid Items="@myFilteredItems">
    ....
</QuickGrid>

@code {
    IQueryable<Document> myFilteredItems;

    protected override void OnInitialized()
    {
        SetFilter(0);
    }

    // You should also call this whenever you want to change the filter, so that's the only time that myFilteredItems is recreated
    void SetFilter(int categoryId)
    {
        myFilteredItems = categoryId == 0
            ? MyDbContext.Documents
            : MyDbContext.Documents.Where(d => d.CategoryId == categoryId);
    }
}
```

**Comment by marqdouj-spartan** [comment]
Thanks [Steve](https://github.com/SteveSandersonMS)
