### ISSUE TITLE
URL based localization in Blazor application

### ISSUE THREAD

**Issue by neetutanwar** [dotnet/aspnetcore#44438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to implement the custom localization layer based on the requested Url.  something like {{Mysite}}/{{locale}}/page1 e.g. https:/mysite.dev.com/en-us/page1 , https:/mysite.dev.com/fr-fr/page1 etc.

Currently, I have used the "AddInitialRequestCultureProvider" for enabling the URL-based routing and it seems to be working fine. But for the URL resolutions, if the user types a URL without any locale the site should automatically resolve the localized URL and redirects the user to their locale-specific page. 

for example, If I am a user who enters the site URL as "https:/mysite.dev.com/page1" - it should automatically resolve to "https:/mysite.dev.com/en-us/page1" 

We can refer to the Microsoft.com site as well where if you enter https://www.microsoft.com/ but it redirects you to the localized Url. in my case https://www.microsoft.com/en-in

I have tried changing the page URL after checking if it doesn't contain the locale on "OnAfterRenderAsync" and "OnInitialized". It is working fine but it is causing flickering on the UI i.e. page tries to load then stops and then loads again, which is not a good user experience.

Is there any way of adding the {culture} specific by default in all the routes?

### Describe the solution you'd like

We should have a culture-based localization option available out of the box just like we have in MVC asp.net. Even the MS site has the Url based culture configured https://www.microsoft.com/en-in/

**Comment by javiercn** [comment]
@neetutanwar thanks for contacting us.

This is not a feature we currently support.

**Comment by SteveSandersonMS** [comment]
> Is there any way I can map all the requests without the locale to locale specific route?

Yes, you can do things like that.

* If you're using ASP.NET Core as a host server, you'll probably want to implement some middleware that looks at incoming URLs and performs a redirection. Also see the general server-side routing docs at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0
* If you're building a standalone Blazor WebAssembly app without any host server, you will be a bit more limited but might be able to use JavaScript to call [`History.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) to change the URL before Blazor even starts up the .NET runtime. That will allow you to map `/page1` to `/en-US/page1` as part of the page load process.
  * You can also use JavaScript to set the .NET default thread culture before the .NET runtime starts. See docs at https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=webassembly#statically-set-the-culture
