### ISSUE TITLE
Blazor server doesn't render pages properly with custom WebApplicationOptions

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#44439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I use the following code snippet in `Program.cs`:
```
    var builder = WebApplication.CreateBuilder(new WebApplicationOptions
    {
        ApplicationName = typeof(Program).Assembly.FullName,
        ContentRootPath = Path.GetFullPath(Directory.GetCurrentDirectory()),
        WebRootPath = "wwwroot",
        Args = args
    });
```
Blazor server doesn't show the web page properly.

### Expected Behavior

Blazor server renders the pages properly with custom `WebApplicationOptions`.

### .NET Version

6.0.9, 6.0.109

**Comment by javiercn** [comment]
@khteh thanks for contacting us.

What issue are you facing?

**Comment by javiercn** [comment]
@khteh thanks for the additional details.

Are there any errors in the devtools console?

**Comment by khteh** [comment]
![image](https://user-images.githubusercontent.com/3871483/194843314-6187590a-fcba-4049-9553-9be28d743270.png)
![image](https://user-images.githubusercontent.com/3871483/194843375-250001f1-9d30-472d-be88-f6c42cc25b98.png)

**Comment by javiercn** [comment]
@khteh thanks for the additional details.

`ContentRootPath = Path.GetFullPath(Directory.GetCurrentDirectory()),` is likely interfering with the configuration for static web assets, but I am not sure why.

**Comment by khteh** [comment]
So what should I do now if I want to use `WebApplicationOptions`?

**Comment by javiercn** [comment]
@khteh It's not obvious to us what is going on here (hence why we marked the issue as investigate).

We will schedule the issue to be looked at in a future milestone based on our triage (To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md).) and will provide an update at that point.

A repro project would help to make sure that we can reproduce your exact issue and determine if there is a bug in the framework or a configuration error in the application.

**Comment by MackinnonBuck** [comment]
@khteh Thanks for contacting us. Could you please provide a minimal repro project that demonstrates your issue, hosted as a public GitHub repository? This will help us investigate the problem and make a determination about where the issue lies.

**Comment by khteh** [comment]
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio

Change `var builder = WebApplication.CreateBuilder(args);` to use `WebApplicationOptions`

**Comment by MackinnonBuck** [comment]
@khteh `typeof(Program).Assembly.FullName` will give you the display name, which looks something like `"BlazorServerProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"`. You probably want to use `typeof(Program).Assembly.GetName().Name` instead. Could you try that and see if it resolves your issue? Thanks.

**Comment by khteh** [comment]
Yes, that works. What happens? How does that affect the application's CSS?

**Comment by MackinnonBuck** [comment]
@khteh Glad your issue was resolved!

> How does that affect the application's CSS?

By default, `ApplicationName` is used to resolve the static web assets manifest file, i.e. `<ApplicationName>.staticwebassets.runtime.json`. So, using `typeof(Program).Assembly.FullName` effectively causes the manifest file name to be resolved to something like `<assembly name>, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.staticwebassets.runtime.json`, which is incorrect. This will cause all requests to static web assets to 404, including CSS files.

Closing this as by-design.
