### ISSUE TITLE
QuickGrid documentation insufficiency 

### ISSUE THREAD

**Issue by NikolayRenziglov** [dotnet/aspnetcore#44446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The QuickGrid documentation has no info about adding the dynamic column from the C# code.

### Describe the solution you'd like

Please add the documentation or provide a link if it exists to the way one can add the dynamic Template or Property column to the QuickGrid.

**Comment by guardrex** [comment]
This content is currently located at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#quickgrid-component

**Comment by NikolayRenziglov** [comment]
Hi there. Thanks for a prompt postback. The reason I posed that question is the lack of documentation on how to add a dynamic fields in C# code. Should it be something like
`RenderFragment columns = b =>
            {
                b.OpenComponent(1, typeof(TemplateColumn<MyItemType>));
                b.AddMarkupContent(1,"<p>YOYOY</p>");
                b.CloseComponent();
            };` ?
Any brief example would be helpful. Sincerely

**Comment by mkArtakMSFT** [comment]
@guardrex we're trying to bring the QuickGrid productization work to 8.0-preview2. As soon as that's done, I'll ping you here to finish the documentation work for it.

**Comment by mkArtakMSFT** [comment]
@guardrex the change just got merged to preview2. Feel free to publish your docs when preview2 ships.

**Comment by guardrex** [comment]
Thanks @mkArtakMSFT ... I'll create a docs issue for it by EOD and get it done for preview2's release.

**Comment by guardrex** [comment]
@mkArtakMSFT ... We still don't have the 8.0 docs in the doc version selector. I can address the content now for the preview 2 release, but nobody will ever see it until "8.0" is activated for view. @Rick-Anderson ... About when does that happen each year? I don't pay too much attention to when it happens ... I 🎷🎶 jam along until it just ✨ ***Magically Appears***&trade; ✨😄. 

Also, @mkArtakMSFT ... The ask here is for updated docs on features of `QuickGrid` ...

> no info about adding the dynamic column from the C# code

... not just about it rolling into the framework for 8.0. It looks like from the blog post at https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/ that new features weren't added for preview 1. Am I merely to change the language to indicate that the package is in the framework for 8.0, or should I do that ***AND*** look at any PU PRs that have touched it for updates to its features that need to be added to the text, too?

**Comment by Rick-Anderson** [comment]
> @mkArtakMSFT ... We still don't have the 8.0 docs in the doc version selector. 

Publish some 8.0 content and if it's not activated I'll get that fixed. It's supposed to be active but I'm skeptical as I don't see in on the live site, but it's visible on the internal build site.

**Comment by guardrex** [comment]
I put some up three weeks ago in a Blazor Hybrid doc ...

https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/blazor/hybrid/routing.md#L228

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0

[Internal work item URL](https://ceapex.visualstudio.com/Onboarding/_workitems/edit/793441)

Hopefully this will be fixed in a few days. I gave them [your 8.0 content](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0&pivots=maui) to test. BTW, you can see the 8.0 content by hacking the URL like I did, but then you can't select other versions.

**Comment by Rick-Anderson** [comment]
@guardrex production is working now.

**Comment by mkArtakMSFT** [comment]
> 1. Merely update the language to indicate that the package is in the framework for 8.0.

This @guardrex !
You're right, we haven't added new features yet.

**Comment by guardrex** [comment]
Thanks @mkArtakMSFT ... I'll take care of it by EOD.

**Comment by mkArtakMSFT** [comment]
@guardrex should this be closed now?

**Comment by guardrex** [comment]
Yes, I'll track on QuickGrid feature updates separately on my docs tracking issue. The coverage on it being in the package is live now at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#quickgrid-component
