### ISSUE TITLE
Please release new version of Microsoft.AspNetCore.Http.Abstraction

### ISSUE THREAD

**Issue by lAnubisl** [dotnet/aspnetcore#44457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The latest version of Microsoft.AspNetCore.Http.Abstraction available is 2.2.0 (https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/#dependencies-body-tab) from 12/3/**2018**.
This package version has a dependency [System.Text.Encodings.Web](https://www.nuget.org/packages/System.Text.Encodings.Web/) (>= 4.5.0) which has security issues:

- https://github.com/advisories/GHSA-ghhp-997w-qr28
- https://github.com/dotnet/announcements/issues/178

### Describe the solution you'd like

Looks like the current source code does not have the dependency of System.Text.Encodings.Web
Can we please just release the new version of Microsoft.AspNetCore.Http.Abstraction?

**Comment by ArminShoeibi** [comment]
Hi @lAnubisl You shouldn't use that package, please delete it from your package references.
Please consider using new methods.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

**Comment by lAnubisl** [comment]
@ArminShoeibi Thank you for your reply. The package is not referenced directly by me. It is an indirect reference
![image](https://user-images.githubusercontent.com/1249671/195025055-65830990-fbe2-43a3-9481-e4d1322e45be.png)

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi Thank you for your reply. The package is not referenced directly by me. It is an indirect reference ![image](https://user-images.githubusercontent.com/1249671/195025055-65830990-fbe2-43a3-9481-e4d1322e45be.png)

Oh yes, you are right.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/68565441/195082920-72be2a64-3ead-4d43-ab8d-864fafc31940.png">

**Comment by BrennanConroy** [comment]
You will need to manually add a newer version of `System.Text.Encodings.Web` to your project.

`Microsoft.AspNetCore.Http.Abstraction` version 2.2.0 has been [out of support for over two years](https://devblogs.microsoft.com/dotnet/net-core-2-2-will-reach-end-of-life-on-december-23-2019/). As have most (all?) `Microsoft.AspNetCore.*` 2.2.x packages.

**Comment by lAnubisl** [comment]
@BrennanConroy There is no message "This package is deprecated" anywhere here: https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions . The source code of the package is available on GitHub. It is not gone. What is the problem of releasing the new package version?
