### ISSUE TITLE
in Blazor wasm iframe not load the LocalStorage or IndexedDB

### ISSUE THREAD

**Issue by sepehrland** [dotnet/aspnetcore#44468]
I want to use cross domain indexddb and I know the solution is using iframe and postMessage, it works in Blazor Server app, but in blazor wasm, the indexeddb of the iframe source is empty and not load its data.

**Comment by javiercn** [comment]
@sepehrland thanks for contacting us.

There is nothing special about Blazor Webassembly in this regard. I would check the differences between your working solution and your non-working solution to understand what is different and determine the changes that you need to do.

**Comment by sepehrland** [comment]
I'm attaching the working projects here if it's help, it is on blazor server app, (in this case i'm using localstorage, but no difference between localstorage and indexeddb in this case, I've tested both)
**Details:**

**- BlazorAppServer Project:** : it has _parent.js_ file, which is listening for a message from the other domain to read or write the data from indexeddb and send back the result
**- BlazorAppClient Project:** : it has _library.js_ file which postMessage to the iframe in _TestDB.Razor_ page when _get_ button clicked

but, if you do it exactly in blazor wasm, it does not work.

[Working.zip](https://github.com/dotnet/aspnetcore/files/9755202/Working.zip)

**Comment by sepehrland** [comment]
It is not resolved yet.
