### ISSUE TITLE
blazor-hotreload.js breaks offline service worker when running from visual studio.

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#44487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to run a blazor application with a service worker which was started from visual studio I get the following error.

```
System.AggregateException: One or more errors occurred. (Failed to fetch dynamically imported module: https://localhost:51992/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: https://localhost:51992/_framework/blazor-hotreload.js)
 ---> Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:51992/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: https://localhost:51992/_framework/blazor-hotreload.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.InitializeAsync()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken, WebAssemblyCultureProvider cultureProvider)
   at MyBlazorClient.Program.Main(String[] args) in C:\MyBlazorClient\Program.cs:line 44
   --- End of inner exception stack trace ---
```

I have attempted to turn hot reload off but still get this error.

![image](https://user-images.githubusercontent.com/1992395/195240769-203a9074-54ce-4236-b258-982404596faf.png)

### Expected Behavior

There should be a way to prevent the hot reload functionality when starting the application from visual studio or the hot reload script should be included in the generated asset manifest.

### Steps To Reproduce

1. Create a blazor wasm application with a service worker.
2. Remove the debug service worker
3. Run without debugging in visual studio
4. In chrome or edge dev tools disable the network.
5. Refresh the page.

### .NET Version

6.0.402

**Comment by javiercn** [comment]
@groogiam thanks for contacting us.

> 2\. Remove the debug service worker

The debug service worker is there to avoid failures and NOOP during development. If you want to use the production service worker for development alongside hot reload, you will have to modify it accordingly to make sure it avoids handling the script paths required for hot reload.

**Comment by groogiam** [comment]
@javiercn It really seems like there should be a way to debug and test the service worker in Visual Studio. The script paths that break this scenario seem to be injected by Blazor and there does not appear to be any documented way to turn them off to support a reasonable  development workflow. Hence the reason for me posting the bug.

**Comment by javiercn** [comment]
@groogiam you can turn off hot reload.

https://learn.microsoft.com/sk-sk/aspnet/core/test/hot-reload?view=aspnetcore-6.0#disable-hot-reload
