### ISSUE TITLE
Add support for new dialog form method in FormMethod enum

### ISSUE THREAD

**Issue by Ducki** [dotnet/aspnetcore#44499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, the [FormMethod](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/Rendering/FormMethod.cs) enum only contains the GET and POST form methods.

However, the new <dialog> element also introduced a [new form method](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fs-formmethod) `dialog` (its use case is to close the dialog).

Currently, IDEs are showing a squiggle when using the <form> tag helper with this form method, probably because they rely on the content of this enum for that attribute.

### Describe the solution you'd like

Add `Dialog` to FormMethod.

**Comment by Ducki** [comment]
If it helps, I [created a PR](https://github.com/dotnet/aspnetcore/pull/44500) for that change.

**Comment by javiercn** [comment]
@Ducki thanks for contacting us.

I think we will accept a contribution for this, although it seems that the public API baseline needs to be updated in the PR. If you open the solution in Visual Studio, there should be an analyzer that helps you fix the issue.

**Comment by javiercn** [comment]
For triage, support for `<Dialog>` is good in the latest browsers https://caniuse.com/?search=dialog (IE being the only one that does not support it, but that is expected).

It will be better if we can have confirmation that this is part of the actual standard and not just the living standard before we merge, as things tend to change there.

**Comment by Ducki** [comment]
> If you open the solution in Visual Studio, there should be an analyzer that helps you fix the issue.

I have tried for literally hours to get this single line in the Public API file.

Since I'm on a Mac, I tried running VS in a VM, which is practically with the ASP.NET project because it just chokes with errors and crashes (after trying to index and analyze for an hour (!)). Codespaces similar.
Running the dotnet format analyzers cli tool is throwing errors as well and not finding some obscure files.

I'm really sorry. I really want to contribute, but it is borderline impossible to do so outside Windows/Visual Studio.

**Comment by javiercn** [comment]
@Ducki I am really sorry you run into issues with this. I'll try to get someone on the team to fix it and get it merged.

From what I understand this can be fixed running dotnet format in the project, but seems like we do not have this correctly documented. We have a separate issue tracking this [here](https://github.com/dotnet/aspnetcore/issues/27605)

**Comment by Ducki** [comment]
Never mind, I got it in now :)

**Comment by WingZer0123** [comment]
@Ducki @javiercn I don't mean to come in here, I was looking at good first issues this one seemed like an appropriate one but it seems it has been taken care of. Is the addition to Public API text file a way to track changes that have not been released into production directly to the users? I see those files in almost every single individual project.

**Comment by javiercn** [comment]
@WingZer0123 we track public API changes across versions using a set of Roslyn analyzers. You can see the details [here](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

That way we know explicitly when we are removing APIs and can have a discussion about it.

**Comment by javiercn** [comment]
@Ducki thanks for the contribution!
