### ISSUE TITLE
Blazor WebAssembly - Single Sign Out not working

### ISSUE THREAD

**Issue by Mabion** [dotnet/aspnetcore#44495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a Blazor WebAssembly application created, on which our exisiting Azure AD user can logon to. For this we have used the Microsoft.Authentication.WebAssembly.Msal package (6.0.5). These users also use this account to login to Office365. And with this setup our users can experience the Single Sign On functionality, without having to provide their credentials multiple times.

But we also want that they are being Signed Out if they logout on one of the Azure AD linked applications. We have 2 scenario's:
* If an user log out the Blazor WASM application, they should also be logged out on their Office365 session.
* But also when they log out the Office365 session, then the Blazor WASM session should be signed out.

For this 2nd scenario we have configured the Front-Channel Logout URL (in the App Registration of Azure), so that this URL ({blazorwasm-domain}/authentication/logout-callback) is being triggered on LOGOUT via Office365.com (which is triggered when we use the developer toolbar). But eventually nothing happens happens, and the session in the Blazor WASM application remains valid.

We have searched for an walkthrough or setup for Single Sign Out behaviour with the MSAL package, but haven't found any.

This is how we have configured the MSAL setup for our Blazor WASM application:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/4067489/195364224-265ccc95-65bf-4b34-8851-8c0513f18075.png">

And we have setup an Authentication.razor file, which will receive the Front-Channel Logout URL:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4067489/195364420-49147dee-71d7-43fe-853f-9b597689f86c.png">

At this point we have no idea why this isn't working and how we can get logging in the WASM application to see if it is handling the request as expected or if an expection is thrown.

So the question is: why is this not working? 

### Expected Behavior

When the user logs out for OFFICE365.COM, it also invalidates the session of our Blazor WASM application.

### Steps To Reproduce

* Setup App Registration in Azure
* Setup Blazor WASM application with MSAL
* Configure Front-Channel logout URL
* Login to office365.com with the Azure AD account in which the App Registration lives
* Navigate to the Blazor WASM application, to see if the session has been invoked.

### .NET Version

6.0

### Anything else?

Blazor WASM 6.0

**Comment by javiercn** [comment]
@Mabion thanks for contacting us.

I do not believe we support front-channel logout. The logout callback is for the logout redirect, not for the front-channel logout.

**Comment by Mabion** [comment]
> @Mabion thanks for contacting us.
> 
> I do not believe we support front-channel logout. The logout callback is for the logout redirect, not for the front-channel logout.

Hi @javiercn, thank you for the response - do you mean that both actions "logout" and "logout-callback" are not supported for specifically Blazor WASM? 
Should we then make our own implementation for this? Since the URL is being triggered, as we can see in the developer toolbar. 

Or do you have another suggestion?

**Comment by javiercn** [comment]
> do you mean that both actions "logout" and "logout-callback" are not supported

I mean that they are for logging out from the app, not to be used as the front-channel logout. 

Front-channel logout is when you have a separate app and that app logs out. During the logout process the IdP opens an iframe to other apps the user is signed in to trigger the signout process in those apps.

That is functionality we do not support out of the box (you can implement it yourself if you get the msal client we create inside `window.AuthenticationService` (although this mechanism might change in the future).

logout and logout-callback are to perform logout redirect from within the app, not initiated from outside.

Hope that helps clarify things.

**Comment by Mabion** [comment]
> > do you mean that both actions "logout" and "logout-callback" are not supported
> 
> I mean that they are for logging out from the app, not to be used as the front-channel logout.
> 
> Front-channel logout is when you have a separate app and that app logs out. During the logout process the IdP opens an iframe to other apps the user is signed in to trigger the signout process in those apps.
> 
> That is functionality we do not support out of the box (you can implement it yourself if you get the msal client we create inside `window.AuthenticationService` (although this mechanism might change in the future).
> 
> logout and logout-callback are to perform logout redirect from within the app, not initiated from outside.
> 
> Hope that helps clarify things.

Thank you for clarifying - then we should look into implementing it ourselves. 
Do you maybe have documenation on where this can be found? So that this is currently not supported.
