### ISSUE TITLE
UseEndpoints behaves differently in Development and Production env

### ISSUE THREAD

**Issue by PeterDraex** [dotnet/aspnetcore#44491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'd like to use `app.UseEndpoints` for routing. It works correctly in Development environment, but not in Production environment.

### Expected Behavior

For request to `/`, `index.html` is returned both in Development and in Production environment.

### Steps To Reproduce

1. Create a new project, use hosted Blazor WebAssembly template
2. In Program.cs, replace the following lines:
```csharp
app.MapRazorPages();
app.MapControllers();
app.MapFallbackToFile("index.html");
```
with
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllers();
    endpoints.MapFallbackToFile("index.html");
});
```
3. Run the app - everything works correctly
4. Change the `ASPNETCORE_ENVIRONMENT` environment variable to `Production`
5. Run the app - instead of loading the page, 404 is returned

### .NET Version

6.0.400

### Anything else?

- I'm using Visual Studio 2022 version 17.3.3
- [`dotnet --info` output](https://pastebin.com/dDPHJa76)

**Comment by javiercn** [comment]
@PeterDraex thanks for contacting us.

Is this a Blazor Webassembly application?

**Comment by PeterDraex** [comment]
> @PeterDraex thanks for contacting us.
> 
> Is this a Blazor Webassembly application?

Yes, Blazor WebAssembly.

**Comment by javiercn** [comment]
@PeterDraex thanks for contacting us.

Endpoint routing is working fine, but static web assets are only enabled by default in Development for security reasons, since the runtime support serves files from other paths in the machine outside the solution. If you want to enable them in production you can do so explicitly like this:

```csharp
.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder.UseStaticWebAssets();
});
```

**Comment by PeterDraex** [comment]
Could you elaborate on what's happening? Why does the runtime serve files from paths outside the solution (wwwroot is inside the solution)?  What are the security consequences of enabling this? Is it safe to enable in production? I see that [Static files in non-Development environments for Blazor Server apps](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?source=recommendations&view=aspnetcore-6.0#static-files-in-non-development-environments-for-blazor-server-apps) advises against enabling this in production for Blazor Server apps.

Thanks @javiercn
