### ISSUE TITLE
src/Identity/Extensions.Stores/src/IdentityRole.cs Name Should be required and not nullable

### ISSUE THREAD

**Issue by luizfbicalho** [dotnet/aspnetcore#44497]
## Summary

I didn't understand why IdentityRole.Name, IdentityRole.NormalizedName , IdentityUser.UserName  and IdentityUser.NormalizedUserName  are nullable, this are required properties and should be required 

## Motivation and goals

The major problem that I see is that i every place that I use the IdentityRole and IdentityUser I'll need to test if the name is null, and doesn't seem to be a reason for that.

The issue is in the #40007  change

**Comment by HaoK** [comment]
We have a constructor that leaves UserName null for example here https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Stores/src/IdentityUser.cs#L19

**Comment by luizfbicalho** [comment]
Couldn't this constructor leave it as string.empty?

this will make every part of the code to check this properties if they are null

**Comment by davidkarlsson** [comment]
I don't understand why you made these properties nullable either. These properties should not be nullable for us and making these changes at this late stage seems rather reckless in my opinion considering they are used for database entities. 

Is there even any user cases where it makes sense that these properties are nullable? What good is a role without a name here for instance?

Now we have a mismatch between the nullability of the columns in our users and roles tables and our ef core entities and it's incorrect for us to change the nullability of the columns.

**Comment by LeeMustache** [comment]
I agree that it seems like an unnecessary change especially for a property such as the username.

I can't think of much use cases where you don't have a username for your user so to me it seems like this way you're forcing 95% of projects to put null forgiving operators everywhere where this property is used because it'll never be null.

I guess the workaround would be to do something like this to silence all warnings
```cs
public class MyUserClass : IdentityUser
{
  [AllowNull]
  public override string UserName { get; set; }
}
````

**Comment by luizfbicalho** [comment]
I still don't get it, I mean, is there a scenario where username should be null?
