### ISSUE TITLE
PageModel IUrlHelper DI for integration tests?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#44518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My ASP.Net Core 6 Identity uses `Url` object. While everything works fine with the application, I need to be able to test the model. How to DI `PageModel.IUrlHelper`?

### Exceptions (if any)

null reference exception.

### .NET Version

6.0.10

**Comment by javiercn** [comment]
@khteh thanks for contacting us.

If this is a unit test, you don't DI the UrlHelper, you create a mock and assign it to the property in your page model.

**Comment by khteh** [comment]
ok
