### ISSUE TITLE
'dotnet publish' does not publish wwwroot when Blazor project is a dependency

### ISSUE THREAD

**Issue by chylex** [dotnet/aspnetcore#44519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I've been trying to publish a Blazor project with `dotnet publish`, and none of the wwwroot assets were being published. I tried adding the folder manually, but then of course there were no CSS isolation files, so `<Project>.styles.css` was returning a 404.

Turns out this happened because I was using:
```
dotnet publish Server/Phantom.Server/Phantom.Server.csproj -c Release -o /app/out
```
where `Phantom.Server` project is a console application, which has a dependency on the Blazor project named `Phantom.Server.Web`. Despite the Blazor project being a dependency, publishing the project did not publish the `wwwroot` folder so the deployed website didn't have any assets.

My solution right now is to publish like this:
```
dotnet publish Server/Phantom.Server.Web/Phantom.Server.Web.csproj -c Release -o /app/out
dotnet publish Server/Phantom.Server/Phantom.Server.csproj -c Release -o /app/out
```
which seems like it shouldn't be necessary, but that's the only way I can get the `wwwroot` folder published with all assets.

Another possibility is to omit the `.csproj` path and publish the whole solution, but my solution contains 2 distinct applications that run on separate machines, so there is no reason to build them together and waste time building projects and dependencies that are not going to be used.

### Expected Behavior

I think it would make much more sense if publishing a project, which has a Blazor project as a dependency, also published the `wwwroot` folder and everything else Blazor needs. The way it works now is really confusing and I spent almost a whole day trying to figure out why my assets weren't loading.

### Steps To Reproduce

I created a branch in my repo with only the two projects and almost no code, so it's as minimal as possible.

1. Checkout the repro branch: https://github.com/chylex/Minecraft-Phantom-Panel/tree/wip-publish-repro
2. Open the solution folder in a terminal
3. Run `dotnet publish Server/Phantom.Server/Phantom.Server.csproj -c Release -o out`
4. In the `out` folder, there is a `Phantom.Server.Web.dll` and related files, but no `wwwroot` or `web.config`
5. Run `dotnet publish Server/Phantom.Server.Web/Phantom.Server.Web.csproj -c Release -o out`
6. Now there is a `wwwroot` folder and `web.config`

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

The .NET version I listed is on my local machine which has the same issue, but for the deployment I'm using the `mcr.microsoft.com/dotnet/sdk:7.0` Docker image which I think has .NET 7 RC 2.

**Comment by javiercn** [comment]
@chylex thanks for contacting us.

Referencing a web app from a console app is not something we support. Web apps or Blazor standalone apps are not libraries that can be consumed by other projects.

**Comment by chylex** [comment]
May I ask why it's not supported? My use case is that my application contains a web server (Blazor) and an RPC server. They're both in separate projects and don't need to know about each other. The main application project has them as dependencies, and on startup it configures and lauches them.

It doesn't really make sense architecturally to force the web server project to do startup configuration and depend on something it has nothing to do with.
