### ISSUE TITLE
Re-enable blazor tests in 6.0 after 17.4 msbuild fix is in

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/aspnetcore#44526]
https://github.com/dotnet/sdk/pull/28322#issuecomment-1273685282

**Comment by MattGal** [comment]
> I think it needs to be in the helix images the tests run in. It kind of looks like from the history that [this ](https://github.com/dotnet/msbuild/pull/8002) probably made it in for preview 3 of 17.4 but isn't in RC2 of the SDK. Since this issue broke because of the helix images, I think getting them updated to preview 3 may be sufficient.
> 
> @MattGal might know the schedule but I think it usually takes ~2 weeks from release to being adopted in the helix queues.

I missed this one back when I was originally tagged, but I would point out that the "regular" VS 2022 images are now at  version 17.4.3, and you can see our upgrade schedule [here](https://dnceng.visualstudio.com/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule)

**Comment by javiercn** [comment]
Done as part of https://github.com/dotnet/sdk/pull/38261
