### ISSUE TITLE
ASP.NET HTTPS request "hangs" when reading request stream on certain requests

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/aspnetcore#44525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In testing a custom input/output formatter that I've developed I encountered what I believe might be a bug in ASP.NET.
Request processing hangs when reading from the request stream (`Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsync`). This happens when a custom TextInputFormatter binds the request body to an `IAsyncEnumerable` controller action argument, which causes the reading of the request and the writing of the response to overlap (which is probably unusual). This only happens when the request exceeds a certain size. (NOT the asp.net request size limit).

The issue is best understood with a minimal repro, which is available in this repository: https://github.com/MarkPflug/HttpStreamMinRepro

The repository also includes more detailed description of the issue. 

### Expected Behavior

The request proceeds without hanging regardless of the request size, assuming it doesn't exceed the asp.net request size limit. Alternately, an exception is thrown informing me that I've done something silly.

### Steps To Reproduce

See the minimal repro in the linked repository: https://github.com/MarkPflug/HttpStreamMinRepro

Run the web app, then the ReproClient to generate a large request.

### Exceptions (if any)

There isn't really an exception thrown, other than the exception thrown when the client disconnects due to timeout, but that exception isn't an issue.

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

This repros on .net 6 as well. Repros on both kestrel and iisexpress. This only seems to happen on HTTPS requests. Over HTTP, the response is properly received. The PlainTextOutputFormatter isn't critical to the repro, it also hangs with the standard JSON output. However, I don't see the server unwind in the debugger when the JSON formatter is used (I can't explain this either).

**Comment by Tratcher** [comment]
The bottleneck you're hitting here is on the client. You're doing bidirectional streaming, but the client isn't actually consuming the response until the request finishes uploading, so all the network buffers fill up and the response stalls. I don't know why that would be different without TLS, but it's likely just that the buffer boundary is different.

I was able to get it working with the following tweaks.

```diff
     var req = new HttpRequestMessage()
     {
+        VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher,
         RequestUri = new Uri("Echo/Post", UriKind.Relative),
         Method = HttpMethod.Post,
     };

-    req.Content = new StringContent(requestString, Encoding.UTF8, "text/plain");
+    // req.Content = new StringContent(requestString, Encoding.UTF8, "text/plain");
+    req.Content = new CustomContent(requestString, "text/plain");

-        resp = await client.SendAsync(req);
+        resp = await client.SendAsync(req, HttpCompletionOption.ResponseHeadersRead);

+public class CustomContent : HttpContent
+{
+    string _requestString;
+
+    public CustomContent(string requestString, string contentType)
+    {
+        _requestString = requestString;
+        Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(contentType);
+        Headers.ContentLength = _requestString.Length;
+    }
+
+    protected override async Task SerializeToStreamAsync(Stream stream, TransportContext? context)
+    {
+        var bytes = Encoding.UTF8.GetBytes(_requestString);
+        await stream.WriteAsync(bytes);
+    }
+
+    protected override bool TryComputeLength(out long length)
+    {
+        length = 0;
+        return false;
+    }
 }
```
https://github.com/dotnet/runtime/blob/3968ceb4297d87109ea32401da02fe4432188a4a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1968
https://github.com/dotnet/runtime/blob/9768606ea1f0aa1be6098143ded330dadac8cf91/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L349

**Comment by Tratcher** [comment]
Note the S.T.Json doesn't buffer the whole body all at once, it's a streaming parser that buffers the next segment and then parses it. The end result is a full S.T.Json model, but you never had a byte[] containing all the raw data at once.
