### ISSUE TITLE
blazor server signalr JsonReaderException

### ISSUE THREAD

**Issue by csandoy** [dotnet/aspnetcore#44520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The issue described here is not resolved for me
https://github.com/dotnet/aspnetcore/issues/34419
I have tried using .net 7 rc2
same problem
I created a Blazor Server app
added Azure AD authentication
test it is working
added a chat page and hub from here https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-build-blazor-server-chat-app
when this line is execute it failes
await _hubConnection.StartAsync();

### Steps To Reproduce

I created a Blazor Server app
added Azure AD authentication
test it is working
added a chat page and hub from here https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-build-blazor-server-chat-app
when this line is execute it failes
await _hubConnection.StartAsync();

### .NET Version

7 rc2

**Comment by javiercn** [comment]
@csandoy thanks for contacting us.

Are you trying to connect to a SignalR hub from a Blazor Server app?

What is the error you receive?

**Comment by csandoy** [comment]
InnerException = {"'<' is an invalid start of a value. LineNumber: 2 | BytePositionInLine: 0."}
Message = "Invalid negotiation response received."
Source = "Microsoft.AspNetCore.Http.Connections.Common"
StackTrace = "   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)\r\n   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<NegotiateAsync>d__45.MoveNext()\r\n   at Microsoft.AspNetCore.Http.Connections.Client....
TargetSite = {Microsoft.AspNetCore.Http.Connections.NegotiationResponse ParseResponse(System.ReadOnlySpan`1[System.Byte])}

**Comment by csandoy** [comment]
I am trying to convert an asp.net intranet site to Blazor Server
I need to send update from server to client, like when a user open the intranet site a count is updated with how many active user ther is on the site

**Comment by javiercn** [comment]
@csandoy what is happening is that when you try to connect from Blazor server to the other hub in your app, your hub client is not properly authorized. This is a description of what is likely happening so that you can get an idea:
```mermaid
flowchart TB
subgraph Server
subgraph Circuit ["Circuit #40;secured by cookie#41;"]
end
subgraph OtherHub ["Other SignalR Hub #40;secured by cookie#41;"]
end
end
subgraph Browser
BlazorServerClient
end
BlazorServerClient -- Cookie --> Circuit
Circuit --> BlazorServerClient
Circuit -- Your component tries to create a Hub client to talk to other hub:\n HubClient sends an HTTP Request without the cookie --> OtherHub
OtherHub -- 401 Unauthorized --> Circuit
```

You have two options:
* You flow the cookie to your HubClient somehow.
* You use a different mechanism to authenticate between the client running inside Blazor Server and the other hub.

**Comment by csandoy** [comment]
Do you have example of how to flow the cookie to HubClient?
