### ISSUE TITLE
coverlet.msbuild not working on .net 7

### ISSUE THREAD

**Issue by maricomic** [dotnet/aspnetcore#44553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Coverlet.msbuild (3.1.2) not working on .net 7

dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:MergeWith="../CoverageResults/coverage.json"

![image](https://user-images.githubusercontent.com/22876505/195913993-fa805a39-226f-4c88-8918-4e6afa052bdc.png)

### .NET Version

7.0.100-rc.2.22477.23

**Comment by BrennanConroy** [comment]
File this on the projects repo: https://github.com/coverlet-coverage/coverlet

**Comment by maricomic** [comment]
Thank you @BrennanConroy !
