### ISSUE TITLE
AuthZ: Add IAuthorizationRequirementData

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#44551]
## Background and Motivation

We want to make it easier to attribute endpoints to add additional requirements for authorization.  This interface will help by letting metadata or custom attributes specify requirements which will automatically get combined with other existing authorization mechanisms.  Note the presence of IAuthorizationRequirementData metadata will be treated similar to IAuthorizeData, meaning its considered opting in for authorization (but it does not automatically bring in the default policy, see examples)

## Proposed API

```diff
namespace Microsoft.AspNetCore.Authorization;

+ public interface IAuthorizationRequirementData
{
+    IEnumerable<IAuthorizationRequirement> GetRequirements();
}
```

## Usage Examples

Example 1: Derive from Authorize attribute without specifying a policy to customize the default policy by adding arbitrary requirements, i.e.
```csharp
internal class MinimumAgeAuthorizeAttribute : AuthorizeAttribute, IAuthorizationRequirementData
{
    public MinimumAgeAuthorizeAttribute(int age) => Age = age;

    public int Age { get; }

    IEnumerable<IAuthorizationRequirement> GetRequirements() => new[] { 
        new MinimumAgeRequirement(Age)
    };
}
    
    [MinimumAgeAuthorize(21)]
    public void NoKidsControllerMethod { ... }
```

Example 2: Fully specify the requirements without interacting with default policy (no authorize attribute), i.e. only allow authorization on Tuesdays

```csharp
internal class OnlyTuesdayAttribute : Attribute, IAuthorizationRequirementData
{
    IEnumerable<IAuthorizationRequirement> GetRequirements() => new[] { 
        new OnlyTuesdayRequirement()
    };
}
    
    [OnlyTuesday]
    public void TacoTuesdayMethod { ... }
```

## Alternative Designs

Decided against allowing specification of a fully policy to minimize the complexity of how it combines with existing methods of producing policies, as its trivial to combine additional requirements (always safe to combine)

## Risks

New way to opt into authorization where before only [Authorize]/`IAuthorizeData` was used to require authorization.

**Comment by HaoK** [comment]
PR: https://github.com/dotnet/aspnetcore/pull/44342

**Comment by HaoK** [comment]
@asp-net-api-reviews this is ready for review

**Comment by halter73** [comment]
API Review Notes:

1. The motivation is that writing code to add new auth requirements to an endpoint (e.g. min age) requires writing a lot of code today in many classes.
2. Discussed how the `IAuthorizationRequirement` marker interface works. All existing logic.
3. Are we okay with logic in attributes? Yes. It's super convenient.
4. Method vs property. We fee that a method better matches expectations. We don't know much about what the implementation could be. It's probably usually cached by our built-in policy providers, so we don't really require this is inexpensive.

API Approved!

```diff
namespace Microsoft.AspNetCore.Authorization;

+ public interface IAuthorizationRequirementData
{
+    IEnumerable<IAuthorizationRequirement> GetRequirements();
}
```
