### ISSUE TITLE
In custom middleware, there are no route data values

### ISSUE THREAD

**Issue by gurutcr** [dotnet/aspnetcore#44554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following code in startup.cs (.net core 3.1)

        app.UseRouting();
        app.UseCors("CorsPolicy");
        app.UseSession();
        app.UseAuthentication();
        app.UseHttpsRedirection();
        app.UsePreAuthorizationMiddleware(); //<---
        app.UseAuthorization();

Extension method for custom middleware

    public static class CustomMiddlewareExtensions
    {
       public static IApplicationBuilder UsePreAuthorizationMiddleware(this IApplicationBuilder builder)
       {
           return builder.UseMiddleware<PreAuthorizationMiddleware>();
       }
    }

In the middleware the routedata has no values (length is 0)

```
 public async Task InvokeAsync(HttpContext httpContext)
    {
        var rv = httpContext.GetRouteData();
```

I also have a custom authorization handler that fires right after this middleware, there it correctly has the expected route data. The expected Url/Page loads successfully, but I need the route data in the custom middleware. Anyone can tell me what I am missing? BTW, I also tried the httpcontextaccessor in the middleware with same result.

### Expected Behavior

I expect the variable rv to have 5 items in the values.

### .NET Version

3.1

**Comment by davidfowl** [comment]
Can you make a minimal repro as a github repo for this issue?

**Comment by gurutcr** [comment]
Isn't the httpContext.GetRouteData(); call in the custom middleware defined between UseRouting and UseMvc/UseEndpoints supposed to give me the route data based on the matched route? Also, are you asking me to create a bare minimum project to re-produce this?

**Comment by davidfowl** [comment]
Did you try, context.Request.RouteValues?

**Comment by gurutcr** [comment]
Yes, that was my original code.

        public async Task InvokeAsync(HttpContext httpContext)
        {
            var rv = httpContext.GetRouteData();
            var routeValues = httpContext.GetRouteData().Values;

            //var routeValues = httpContext.Request.RouteValues;

**Comment by javiercn** [comment]
@gurutcr thanks for contacting us.

In order for us to make progress we would need a minimal repro project that demonstrates the issue as a public github repository.
