### ISSUE TITLE
@microsoft/signalr - HubConnection onclose event causing app crash on iOS devices.

### ISSUE THREAD

**Issue by tbhalke** [dotnet/aspnetcore#44564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using Expo Go classic build for react-native.

on disconnecting to internet connection real-time connection gets disconnected after 15 seconds, onclose event gets called. I'm trying to start the connection to server hub in onclose event, and it gets crashed.

onclose event throws Error "Server timeout elapsed without receiving a message" while calling the invoke method of signalr hubconnection error.

The issue is seen only in production mode, in development mode not reproducible.

### Expected Behavior

App should not get crashed.

### Steps To Reproduce

1. start the hub connection from the client.
2. disconnect the internet connection on iOS devices wait for 15 seconds.
3. app crashes.

Issue seen on React-Native Expo Go classic build production mode.

### Exceptions (if any)

Error "Server timeout elapsed without receiving a message" while calling the invoke.

### .NET Version

3.1 

### Anything else?
```
import React, { useEffect } from 'react';
import {
    Text, ScrollView,
} from 'react-native';
import { useSelector } from 'react-redux';
import { HttpTransportType, HubConnectionBuilder, LogLevel } from '@microsoft/signalr';

function DeviceStatus() {
    const { deviceId } = useSelector(state => state.devices);
    const { token } = useSelector(state => state.auth);

    useEffect(() => {
        const connection = new HubConnectionBuilder()
            .withUrl('URL', {
                accessTokenFactory: () => { return token; },
                skipNegotiation: true,
                transport: HttpTransportType.WebSockets,
                withCredentials: false
            })
            .configureLogging(LogLevel.Debug)
            .build();

        connection?.on('ReceiveUpdate', updateDeviceStatus);
        connection?.onclose((err) => {
            console.log(err);
        });

        try {
            await connection?.start()
            await connection?.invoke('SetDevice', deviceId);
        }
        catch (err) {
            console.log(err, 'Error 1');
        }
    }, []);

    const updateDeviceStatus = (update) => {
        console.log(JSON.stringify(update));
    }

    return (
        <ScrollView>
        <Text>
        Device Status
        </Text>           
        </ScrollView>
    );
}

export default DeviceStatus;
```

**Comment by BrennanConroy** [comment]
Remove
```
connection?.on('ReceiveUpdate', updateDeviceStatus);
connection?.onclose(async (err) => {
    if (isDisconnected.current) return;
    await startConnection();
});
```
from `startConnection`. You only need to register them once per `HubConnectionBuilder.build()`, what's likely happening is you're updating the `onclose` array while it's being iterated over since you're currently in your `onclose` handler.

**Comment by tbhalke** [comment]
@BrennanConroy as you suggested removed code and added to useEffect hook as seen in the above-mentioned code. The issue is still reproducible.

**Comment by tbhalke** [comment]
@BrennanConroy updated the code in the issue removed all other stuff kept only necessary code, still reproducible.

**Comment by BrennanConroy** [comment]
Can you try a newer version of the client? Preferably 7.0.0-rc.2.22476.2. 3.1 is going out of support soon and we've made many changes since 3.1.

Also, please enable logging https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#javascript-client-logging

**Comment by tbhalke** [comment]
I used logging, unfortunately I can't see the logs with Expo, I'll try to use latest version of the client.

**Comment by tbhalke** [comment]
@BrennanConroy Tried latest version of client still the issue reproducible.

**Comment by rafikiassumani-msft** [comment]
@tbhalke, are you able to reproduce this issue outside of expo go ? Also, I think the `.connection?.onclose()` callback should be run in a cleanup function for your `useEffect()`. Below is an example that you can use to model your case: 

```Javascript

  useEffect(() => {

      signalRConnection?.on("ReceiveComment", (commentData) => {
          console.log(commentsRef.current);
          const allComments = [...commentsRef.current, commentData]
          setComments(allComments)
      }); 
     
     //UseEffect clean up function
      return () => {
          console.log("cleaning signalr handlers");

        //Run your finall event 
          connection?.onclose((data) => {
              console.log(data);
          });
    
      //remove all the connection handlers
          signalRConnection?.off(); 
      };

  }, []);


```

**Comment by tbhalke** [comment]
@rafikiassumani-msft Issue is reproducible only in Expo Go production mode not reproducible in development mode, also tried your approach of cleaning handlers, still reproducible, it's difficult to find the issue in production mode as it won't log any errors.

**Comment by adityamandaleeka** [comment]
@tbhalke If you could narrow this down to a simple reproducer that doesn't involve running another development platform, we can help investigate this. We're a small team and cannot spend the time to set up something like this for an investigation.

**Comment by tbhalke** [comment]
@adityamandaleeka you can close this issue. migrated the expo classic build eas-cli build. issue not reproducible after migration.
