### ISSUE TITLE
Why the constructor access level of "Microsoft.AspNetCore.TestHost.ClientHandler" is "internal"?

### ISSUE THREAD

**Issue by code-jar** [dotnet/aspnetcore#44589]
This makes it impossible for me to customize the "Send" method behavior

[The synchronous method is not supported](https://github.com/dotnet/aspnetcore/issues/44464)
[Override Send in TestHost.ClientHandler](https://github.com/dotnet/aspnetcore/pull/44550)

**Comment by code-jar** [comment]
> Why do you need to call Send? If you really need to block on Send call `SendAsync(...).GetAwaiter().GetResult()`

An RPC framework relies on HttpClient to send requests。on the DotNet6.0，Synchronous call will call the Send method。
When I execute the test, use "TestServer. CreateHandler()" to replace the default HttpClientHandler。
This problem arises

**Comment by Tratcher** [comment]
Does the RPC framework have async APIs? I'd hope so. Trying to do sync calls in this context is at high risk of causing threadpool starvation.

I suggest the following workaround:
```

var client  = new HttpClient(new SyncHandler(TestServer.CreateHandler()));

public class SyncHandler : DelegatingHandler
{
    public SyncHandler(HttpMessageHandler innerHandler) : base(innerHandler)
    {
    }

    protected override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        return base.SendAsync(request, cancellationToken).GetAwaiter().GetResult();
    }
}
```

Because of the risks of deadlocks I don't think we should support Send natively.

**Comment by code-jar** [comment]
> 

Thank you very much for your advice,This helped me solve the problem
