### ISSUE TITLE
Blazor WASM not load LocalStorage or IndexedDB from IFrame

### ISSUE THREAD

**Issue by sepehrland** [dotnet/aspnetcore#44587]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I want to use cross domain localstorage or indexeddb and I know the solution is using iframe and postMessage, in works perfectly in blazor server, but in blazor WASM the iframe not load the localstorage or indexeddb from its source,

I did not just check the browser storage, I also check the postMessage method with javascript and again, it works on blazor Server and did not work on blazor WASM,

Note that, it works if we set the Item on Main project runtime, it is not working when the data saved on it already or set after loading like click on a button,

Also, I should mention that, when I try to set the item with postMessage with iframe in blazor WASM, it set, but it is temporarily, and if I refresh the main domain localStorage, there is nothing. **but in Blazor server it works!**

**Main:**

![Main](https://user-images.githubusercontent.com/52125793/196115261-75f248a5-9b37-42a3-88a3-ad7b88860275.jpg)

**Blazor Server with IFrame which load the Main:**

![Blazor server iframe](https://user-images.githubusercontent.com/52125793/196115152-2183eb18-3d68-4781-a0e1-7eb8f1fa4426.jpg)

**Blazor WASM with IFrame which load the Main:**

![Blazor WASM IFrame](https://user-images.githubusercontent.com/52125793/196115206-aa433f09-e036-4b66-b141-e58a2fa9ed04.jpg)

_I have created this issue already but Microsoft Bot closed it as resolved!, so I'm creating it again with more details._

### Expected Behavior

Read and Write Data in LocalStorage or IndexedDb with Iframe and PostMessage for cross domain in Blazor WASM

### .NET Version

Tested on 3.1 and 5 and 6

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Also, can you check if the behavior is different when you don't use Blazor and use a clean javascript-based webpage ?

**Comment by sepehrland** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

I have created 3 repos,

- The first one is the Main domain, please click on "save local storage" button for set the item at the first time or update the item after that:

   [https://github.com/sepehrland/MainLocalStorage](https://github.com/sepehrland/MainLocalStorage)
------------------------------------------------------------------------------------------------------------------

- The second one is the **Blazor Server** which load the Main domain in iframe and you can see the "mytime" item in Devtools/Application/LocalStorage/https://localhost:44359 (ifram source):

   [https://github.com/sepehrland/BlazorServerClient](https://github.com/sepehrland/BlazorServerClient)
------------------------------------------------------------------------------------------------------------------

- The third one is the **Blazor WASM** which should load the Main domain localStorage from iframe in Devtools/Application/LocalStorage/https://localhost:44359 (ifram source)  **but it does not load** :

   [https://github.com/sepehrland/BlazorWASMClient](https://github.com/sepehrland/BlazorWASMClient)
------------------------------------------------------------------------------------------------------------------

I also created a MVC Project which works too:
https://github.com/sepehrland/MVCLocalStorageIframe

_LocalStorage and IndexedDB are the same in this case._

**Comment by surayya-MS** [comment]
Thanks for contacting us.

What is happening is that Visual Studio launched a separate instance of the browser using a special profile for debugging. As a result the instance for debugging does not share any data with other instances on the machine.

If you manually open the apps in same instance of the browser, you should see it work. Same if you open the original app in the webassembly debugging instance. Finally, you can run without debugging and that should also allow you to share the state.

Note that this behavior is by design as Webassembly debugging requires a special setup in the browser to support debugging the .NET code

**Comment by sepehrland** [comment]
You are right, Thank you so much.
