### ISSUE TITLE
Replace outdated dependencies in Blazor Server project template

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#44606]
Blazor Server project template uses openiconic dependency, which is not maintained any more.
This issue tracks the work for choosing a new open-source icons library and moving to it:
https://github.com/dotnet/aspnetcore/blob/274c32e63a9df1979175c4e7c9adffdabc182e96/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/wwwroot/css/site.css#L1

Here are some other places, where openiconic dependency exists:
- [x] dotnet/maui: https://github.com/dotnet/maui/pull/10749
- [ ] dotnet/samples
- [ ] dotnet/maui-samples
- [ ] dotnet/blazor-samples
- [ ] dotnet/aspnetcore.docs

**Comment by TanayParikh** [comment]
This should be covered via https://github.com/dotnet/aspnetcore/issues/40935. Not sure if we need a separate top-level issue in planning.
