### ISSUE TITLE
[NETE2ESDK]The hotkey "a" for "I agree to the license..." on NET 7.0.0 windows server hosting installer UI doesn't work.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#44616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The hotkey "a" for "I agree to the license..."on windows server hosting installer UI doesn't work.

### Expected Behavior

The hotkey "a" for "I agree to the license..." works normally.

### Steps To Reproduce

Double-click on NET 7.0.0 dotne-hosting installer .exe
Press "Alt" keyboard, observe the hotkey and then check if hotkey works

Actual Result:
The hotkey "a" for "I agree to the license..." doesn't work.
![image](https://user-images.githubusercontent.com/65637796/196364817-8c34941d-affb-422e-a6d1-299ba9527a5f.png)

**Comment by dougbu** [comment]
This duplicates part of what I reported in #44582. It is also not a new problem.

**Comment by wtgodbe** [comment]
This is a known bug in the WiX 3.9 toolset: https://github.com/wixtoolset/issues/issues/5927. Closing as an external bug. There is a fix in the 4.0 version of the WiX toolset, but that is still in an early preview.

**Comment by dougbu** [comment]
Do we have an issue reminding us to transition to WiX 4.0 when it's released❔

Side question, likely for @joeloff: Does WiX 4.0 have any of the signing issues we worked around w/ Microsoft.Signed.Wix❔
