### ISSUE TITLE
[NETE2ESDK][Loc]In NET 7.0.0 installation bundle help, there are a few truncated strings. 

### ISSUE THREAD

**Issue by v-jiexu1** [dotnet/aspnetcore#44618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 There are a few truncated strings in installation bundle help.

### Expected Behavior

 Enter .\dotnet-hosting-7.0.0-win.exe /help and observe the UI.
Actual Result:
EN(not repro):
![EN_Help](https://user-images.githubusercontent.com/113498399/196375459-07aaa1ae-e30b-486a-a4b2-29181cea2f65.png)

e.g FR:
<img width="370" alt="fr-help" src="https://user-images.githubusercontent.com/113498399/196373353-66c33193-b86b-441f-9573-faa02ed4fe0c.png">
e.g IT:
<img width="235" alt="it-help" src="https://user-images.githubusercontent.com/113498399/196373800-bc95f05e-66fc-4982-b82c-1512949e6fbb.png">
e.g RU:
![RU_Help_Trunc](https://user-images.githubusercontent.com/113498399/196374033-83ed4bc4-3af6-4829-a9d0-5cbc40f23a9b.png)

**Comment by dougbu** [comment]
This is definitely worth tracking and covers more than the truncation in the English installers mentioned in #44582. Note however that these are existing issues. Recent changes in 7.0.0 have not changed dimensions of anything in the installers. Nor have the translated strings gotten significantly longer.

**Comment by mkArtakMSFT** [comment]
@dougbu can you please clarify the issue here? Is it that the text goes beyond the window and part of it is not visible?

**Comment by dougbu** [comment]
> Is it that the text goes beyond the window and part of it is not visible?

Yes. There are a few parts contributing to this and they overlap:

- The dimensions of the installers and included fields are too small in some cases, even for our English strings
- Some translated strings take up significantly more room than is available with the current dimensions
- We put extra text (e.g. `Build alpha.1.22514.10`) into some WiX variables and that makes the visible strings hard to read and extra-long

**Comment by mkArtakMSFT** [comment]
I wonder if the solution would be to change the font size or to reduce the text then?

@joeloff will it be possible to potentially expand the size of these UI screens, and avoid this problem all together?

**Comment by dougbu** [comment]
I've got a plan and will get to it before we ship preview1 or 2. Basically, align the two bundle installer sizes, avoid `Build alpha.1.22514.10` in some of the tighter fields, then see whether `Release Candidate 1` fits correctly in both bundles. At that point, if necessary, we can choose between embiggening the installer and smallerizing the text.

**Comment by joeloff** [comment]
> I wonder if the solution would be to change the font size or to reduce the text then?
> 
> @joeloff will it be possible to potentially expand the size of these UI screens, and avoid this problem all together?

You can customize the UI, but window sizes are absolutes and do not dynamically grow/shrink.

**Comment by mkArtakMSFT** [comment]
Closing as a dupe https://github.com/dotnet/aspnetcore/issues/44582
