### ISSUE TITLE
Blazor WebAssembly client app - enable CORS

### ISSUE THREAD

**Issue by axenteoctavian** [dotnet/aspnetcore#44625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I cannot find support to enable CORS on a **Blazor WebAssembly client app**.
I understand that one solution is to have a **Blazor WebAssembly hosted app** and enable CORS on server app which is called from client. But **I need to http request directly from client application** for numerous reasons.

It is possible to enable CORS for client application?

### Describe the solution you'd like

Enable CORS directly in Blazor WebAssembly client app without needing a server app

**Comment by javiercn** [comment]
@axenteoctavian thanks for contacting us.

You should not need to do anything if you are using a standalone Blazor webassembly app. You only need to do something on the server if you want to allow apps from other origins to call into your API.

You can control CORS settings in HttpClient on Webassembly using https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions?view=aspnetcore-6.0

**Comment by axenteoctavian** [comment]
Thank you for your response @javiercn!

The API is not mine. I only develop the client application and fetch the data from an API.

I tried using WebAssemblyHttpRequestMessageExtensions Class in client app but without success.
```
var payload = new StringContent(myJson, Encoding.UTF8, "application/json");
var request = new HttpRequestMessage(HttpMethod.Post, "https://API_ADDRESS");
request.Content = payload;
request.SetBrowserRequestMode(BrowserRequestMode.Cors);           
using (var httpClient = new HttpClient())
{
	var response = await httpClient.SendAsync(request);
	var content = await response.Content.ReadAsStringAsync();
	...
}
```

I get the following error:
![image](https://user-images.githubusercontent.com/45915201/196523426-6817c9d8-0af7-4d15-b49f-bd6e6af142c7.png)

And if I move the same code on a WebAssembly server app it's working.

**Comment by javiercn** [comment]
@axenteoctavian thanks for the additional details.

Your server needs to return the correct CORS headers. There is nothing Blazor can do here. It is something you need to configure on your API.
