### ISSUE TITLE
HttpSys request headers Keys and Count both allocate

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#44627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Offline report:

Found a strange allocation stack. Source code:
```
        public static bool TryExtractSingleValueHeader(
            IHeaderDictionary requestHeaders,
            string headerName,
            out string headerValue)
        {
            headerValue = string.Empty; 

            if (requestHeaders == null || requestHeaders.Keys.Count == 0)
            {
                return false;
            }

            var incomingHeaderValues = requestHeaders[headerName];

            // There may be multiple values, we will pick the first one.
            if (incomingHeaderValues.Count > 0)
            {
                headerValue = incomingHeaderValues[0];
                return true;
            }
            return false;
        }
```
So where is the LINQ expression? It’s here:
 
```
// Microsoft.AspNetCore.HttpSys.Internal.RequestHeaders
public ICollection<string> Keys
{
    get
    {
        return this.PropertiesKeys().Concat(this.Extra.Keys).ToArray<string>();
    }
}
```
 
For classes like Dictionary<K, V>, getting key collection is cheap because you because you just need to pay for a small key collection object once per dictionary (it will be reused forever). But this here has a super expensive implementation, so do not call it unless you’re willing and able to pay for it.

The strange thing is string allocation is the biggest here:

![image](https://user-images.githubusercontent.com/1821173/196524709-2b8cea7b-dc2b-4621-83bd-0ba3bc157103.png)

We do not need to get into the details why strings need to be allocated, because we can just remove the check.

It’s worse than that, the entire Extra headers collection is lazily loaded.
https://github.com/dotnet/aspnetcore/blob/14dc33c0a203b010ef0a8eb01a5f638199571728/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L33-L39

IDictionary.Count is also bad
https://github.com/dotnet/aspnetcore/blob/14dc33c0a203b010ef0a8eb01a5f638199571728/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L93-L96

**Comment by ladeak** [comment]
The idea would be to return only the keys without populating the actual values for both Known and Unknown keys, and I assume count the same. That seems like a good approach with the code sample above.

However, we would also need to cache the keys and the values separatly for the `Extra`s.

I am thinking about the use-case when someone enumerates all the Values based on the Keys (as opposed to only access a single key as in the above example).

**Comment by Tratcher** [comment]
Count could avoid populating anything, but I think it's OK for keys to populate most things, especially if the pattern is to enumerate values by key.

**Comment by ladeak** [comment]
I'll take a look as dotnetconf gets over.

**Comment by ladeak** [comment]
I am working on this.
