### ISSUE TITLE
[Blazor] Unexpected navigation behavior

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#44626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I'm trying to find a solution for unexpected behavior related to Blazor navigation.

I have a spinner component residing in ``MainLayout.razor`` file that is shown when a web api call is issued and then hidden when the call finishes. It provides some basic animation indicating to the user that there is a long running operation. I created a base page that handles the web api call and toggles the state of the spinner component. All my pages inherit from this class. This works great until the user decides to navigate to the previous page using the browser's back button while the spinner is still shown.

I implemented ``IAsyncDisposable`` interface in the base class to hide the spinner when the component is disposed of (i.e. when user navigates to a different page).

Component A
```csharp
       public virtual async ValueTask DisposeAsync()
        {
            m_isDisposed = true;
            await ToolsService.ResetSpinner(); // this hides the spinner
        }
````

This seems to be working in many cases, however most of my pages start loading data as soon as the component is created inside ``OnInitializedAsync`` method and apparently ``OnInitializedAsync`` of component B (the page being navigated to) is called before ``DisposeAsync`` of component A (the page being navigated from) is finished!

Component B
```csharp
        protected override async Task OnInitializedAsync()
        {
            await ToolsService.ShowSpinner();
            ...
        }
```

This causes a problem because component A will show the spinner in ``OnInitializedAsync `` which is then immedietly hidden by component B's ``DisposeAsync`` method. I anticipated that component B is not going to be instantiated until component A is disposed of. Is this a bug? If not, how do you suggest I resolve this problem? Is there a way to at least intercept the navigation and defer it until component A is fully disposed of?

Thank you!

### .NET Version

.NET 6

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

We do not wait for the previous page to de disposed before rendering the new page. That, as you can imagine has the potential to greatly slowdown navigation. In general apps shouldn't rely on the order in which components render except in concrete scenarios (parent children relationship) it makes reasoning about the app correctness really hard.

As for your case, you could change your spinner to do something like this:
`_subscription = await ToolsService.ShowSpinner();`

`_subscription.ResetSpinner()`

With the idea that if another component calls `ShowSpinner` they are the only ones that can call `ResetSpinner` and calls to `ResetSpinner` from a previous component get ignored.

**Comment by daniel-p-tech** [comment]
Thank you for the response, makes sense!
