### ISSUE TITLE
Peformance Issue with dotnet core webapi in micro service acrchitecture on Ubuntu Server

### ISSUE THREAD

**Issue by PKYADAV** [dotnet/aspnetcore#44640]
Dear Team,

I am developing one solution for warehouse automation where response time is very critical i.e. response must be received in 500ms and I am able to achieve in dotnet core application with micro-service architectue.

My issue is when I have deployed the same on my Laptop (Windows 11, i5, 8GB RAM) then it's giving response in 600ms but when deployed on Ubuntu Server of below configuration then response time is going more than 1 second:

```
LENOVO TOWER SERVER ST 550

Intel Xeon Silver 4210 10C 85W 2.2GHz Processor , 1 x 16GB Ram , Open Bay , 2.5" SAS/SATA 8 -Bay Backplane , ThinkSystem RAID 530 -8i PCIe 12Gb Adapter , Lenovo Xclarity Enterprise , 2 x 1G Port , 1 x 750w PSU , 3 Years 24x7 4Hr Response + KYD
ThinkSystem 16GB TruDDR4 2933MHz (2Rx8 1.2V) RDIMM---1QTY
ThinkSystem 2.5" 600GB 10K SAS 12Gb Hot Swap 512e HDD---3QTY
ThinkSystem 750W (230/115V) Platinum Hot-Swap Power Supply
```

Can someone help on this?

Also, please note, it's running fine on Dell R340 with response time with 150ms.

**Comment by davidfowl** [comment]
Hard to know why that is, what did you do to narrow it down so far?

**Comment by javiercn** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
