### ISSUE TITLE
RC2 has different behavior using developer certificates compared to RC1 and earlier

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#44651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an existing application that was running under RC1 and previous previews.

Upon upgrading to RC2 my SSL call to a REST service results in a certificate rejection.

```
[2022-10-19T21:34:53.688Z] Error: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid, UntrustedRoot
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

### Expected Behavior

I expected that the REST call would continue to function after applying RC2

### Steps To Reproduce

I have the following code in this repository: https://github.com/MarkStega/ICEBG

The REST client side (the error is on the client.SendAsync call:
```
       public async Task<WeatherForecast[]?> GetForecastAsync()
        {
            using (var client = new System.Net.Http.HttpClient())
            {
                var request = new System.Net.Http.HttpRequestMessage();
                request.RequestUri = new Uri(ApplicationConfiguration.pWeatherEndpoint);
                var response = await client.SendAsync(request);
                var forecasts = await response.Content.ReadFromJsonAsync<WeatherForecast[]>();
                return forecasts;
            }
        }
    }
}
```
 and the REST controller is:
```
namespace ICEBG.Web.DataServices.Controllers;

[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

    private readonly ILogger<WeatherForecastController> _logger;

    public WeatherForecastController(ILogger<WeatherForecastController> logger)
    {
        _logger = logger;
    }

    [HttpGet (Name = "GetWeatherForecast")]
    public IEnumerable<WeatherForecast> Get()
    {
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = Summaries[Random.Shared.Next(Summaries.Length)]
        })
        .ToArray();
    }
}
```

### Exceptions (if any)

The exception is shown above in 'Describe the bug'

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Solutions\OHI\ICEBG\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

----
C:\Solutions\OHI\ICEBG>dotnet dev-certs https
A valid HTTPS certificate is already present.

C:\Solutions\OHI\ICEBG>

**Comment by javiercn** [comment]
@MarkStega thanks for contacting us.

Is the API running on HTTPS? We did change the defaults so that when you do `dotnet run` it only runs in HTTP (no HTTPS)

**Comment by adityamandaleeka** [comment]
@MarkStega Can you try to delete and re-create the cert ([using the --clean and --trust options](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#all-platforms---certificate-not-trusted))? Looks like it may have expired based on the `NotTimeValid` part of the error.

**Comment by MarkStega** [comment]
@javiercn @adityamandaleeka 

The first thing I did when I encountered the error was to clean out my developer certs (they went back to 2015) and generated a new certificate. Same error.

I think that Javier has probably diagnosed the issue. I am starting the data services & user interface projects using F5 from Visual Studio. They each have a default web page and Chrome is showing the 'https:' prefix with a strikethrough for each. I didn't see anything in the .Net/ASP.Net announcements about the change. Nor do I know how to re-enable https when starting with F5, guidance would be appreciated.

**Comment by javiercn** [comment]
@MarkStega you need to select the HTTPS profile in Visual studio when you launch the backend process. Try to launch just that.

/cc: @DamianEdwards FYI

**Comment by javiercn** [comment]
@MarkStega what version of chrome are you using?
Are you using docker?

I am not able to reproduce this with Chrome 106

**Comment by MarkStega** [comment]
@javiercn @adityamandaleeka

I did another cert first doing a clean, then the recreate, then the trust. This time VS asked if I wanted to install the certificate and I said yes. I cleared all cache from Edge and it still shows a certificate error with an expiry of Sep 15, 2022.

The clean of the certificates only showed the certificate that I created yesterday.

I am using Chrome 106.

I am not using docker (except when I deploy to Azure, and that is done from github actions with a publish step).

How do I find the errant certificate that isn't being shown when I do a clean?

**Comment by javiercn** [comment]
@MarkStega clean anything inside `%APPDATA%\ASP.NET\https`

**Comment by MarkStega** [comment]
@javiercn 

>>>clean anything inside %APPDATA%\ASP.NET\https

That worked -- There were a bunch of .pfx files including two that had names corresponding to the profile names of my two apps. They were dated June 3rd of this year. If I restore the pfx files then the call breaks (as expected).

Am I right in presuming that the content of those files was somehow adversely affecting the RC2 network stack?

In any case, thanks very much for the help.
