### ISSUE TITLE
.Net 7 Razor Class Library Localization

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#44655]
I have  a project with Controllers, Views etc. in a separate Razor Class Library.
![image](https://user-images.githubusercontent.com/23618436/196821241-9dd4c489-ba1c-4e4b-9390-6683d9c1317e.png)

In the application project I added in Program.cs
````csharp
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");

builder.Services
    .AddControllersWithViews()
    .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
    .AddDataAnnotationsLocalization();
````

and

````csharp
WebApplication app = builder.Build();

string[] supportedCultures = new[] { "fr" };
RequestLocalizationOptions localizationOptions = new();
localizationOptions.SetDefaultCulture(supportedCultures[0])
    .AddSupportedCultures(supportedCultures)
    .AddSupportedUICultures(supportedCultures);

app.UseRequestLocalization(localizationOptions);

.........
````

In my Login View I Added the ViewLocalizer

````csharp
@inject IViewLocalizer Localizer
@model LoginViewModel
@{
    ViewData["Title"] = Localizer["Title"];
    ViewData["Greetings"] = Localizer["Greetings"];
}

<form method="post" asp-route-returnUrl="@Model.ReturnUrl">
    @Html.AntiForgeryToken()
    <section>
        <div class="input-group">
            <div asp-validation-summary="All" class="text-validation"></div>
        </div>
        <div class="input-group">
            <input asp-for="@Model.Email" class="border-bottom-dark" autofocus required autocomplete="off" />
            <label asp-for="@Model.Email">@Localizer["Model_Email"]</label>
        </div>
    </section>
    <footer>
        <button class="btn btn-full-width btn-ok">@Localizer["Button_Validate"]</button>
    </footer>
</form>
````

login.fr.resx file contains this:

Button_Validate	        Valider	
Greetings	                        Bienvenue !	
Model_Email	                Email	
Model_Email_Address	E-mail invalide	
Model_Email_Required	E-mail requis	
Title	                                Connectez-vous ou créez un compte	

But there's no way to have my string localized.

If I move the resource folder to the application project, it's working, but I want to distribute a default Localization with the Library

I read documentation an stackoverflow, but I've already done what is explained.

Thanks for your help.

**Comment by Julien-Marpault** [comment]
I tried but it doesn't work.

I made a custom implementation of IViewLocalizer with this method changing:

````csharp
 public void Contextualize(ViewContext viewContext)
    {
        if (viewContext == null)
        {
            throw new ArgumentNullException(nameof(viewContext));
        }

        // Given a view path "/Views/Home/Index.cshtml" we want a baseName like "MyApplication.Views.Home.Index"
        string? path = viewContext.ExecutingFilePath;

        if (string.IsNullOrEmpty(path))
        {
            path = viewContext.View.Path;
        }

        Debug.Assert(!string.IsNullOrEmpty(path), "Couldn't determine a path for the view");

        if (viewContext.ActionDescriptor is ControllerActionDescriptor controllerActionDescriptor)
        {
            string? currentApplicationName = new AssemblyName(controllerActionDescriptor.ControllerTypeInfo.Assembly.FullName ?? string.Empty).Name;
            _applicationName = currentApplicationName ?? _hostingEnvironment.ApplicationName; ;
        }

        string baseName = BuildBaseName(path);
        _localizer = _localizerFactory.Create(baseName, _applicationName);
    }
````

but it doesn't work.

**Comment by Julien-Marpault** [comment]
I moved y resources files to my main project to keep going on.
But I face another issue with DataAnnotation Localization.
As explained in the documentation
I created resource files like
Resources/ViewModels/LoginViewModels.resx

LoginViewModel:
````csharp
public class LoginViewModel
{
    [Required(ErrorMessage = "Required")]
    [EmailAddress(ErrorMessage = "EmailAddress")]
    public string Email { get; set; }

    public string? ReturnUrl { get; set; }
}
````


Program.cs
````csharp
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");

builder.Services
    .AddControllersWithViews()
    .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
    .AddDataAnnotationsLocalization();
````

But... It doesn't work :)

**Comment by MackinnonBuck** [comment]
@Julien-Marpault It looks like the name of that .resx file doesn't match the name of the model (see the extra "s" at the end). Could you try following the naming conventions suggested [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0#dataannotations-localization) to see if it resolves your issue?

**Comment by Julien-Marpault** [comment]
It was a mistake when I wrote the ticket.
I found the solution in the meantime.

IViewLocalizer custom implementation plus assembly decorators.
I'll write a blog post about it and link it here.

**Comment by MackinnonBuck** [comment]
Glad you were able to resolve the issue, @Julien-Marpault! I'm going to close this issue out, but please feel free to comment with your blog post link for others who run into this.
