### ISSUE TITLE
Enable CodeQL3000 pipelines across our repos

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#44662]
Need pipeline YAML like https://github.com/dotnet/arcade/blob/main/azure-pipelines-codeql.yml in release/2.1 (for a few), release/6.0, release/7.0, and main branches of the following repos. Then, create internal pipelines to build on a regular basis.

Or, update an existing unscheduled pipeline to include a schedule and run little else but the CodeQL3000 tasks when a scheduled run occurs.

- [x] aspnet-AspLabs
- [x] aspnet-AspNetKatana
- [x] aspnet-AspNetWebHooks
- [x] aspnet-AspNetWebStack
- [x] aspnet-BuildTools
- [x] aspnet-jquery-validation-unobtrusive
- [x] aspnet-SignalR-Client-Cpp
- [x] dotnet-aspnetcore
- [x] dotnet-ef6
- [x] dotnet-efcore
- [x] dotnet-extensions (just the release/2.1 branch)
- [x] dotnet-orleans
- [x] microsoft-reverse-proxy
- [x] SignalR-SignalR

Wherever we have release/3.1 or old release/5.0 branches in our repos, need to get exceptions for them. In particular, go through the Tools Exception Process at outlined on the [Automated Compliance Tools - Overview (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/2700/Automated-Compliance-Tools?anchor=tool-execution-exceptions) wiki for those specific cases. The list below is just a starting point for where we need those exceptions. Extend the checklist as we find older branches in the above repos.

Also, get exemptions for template-only and test-only repos, including benchmarking code.

- [x] aspnet-AspNetWebHooks-Signed (default branch)
- [x] dotnet-aspnetcore (release/3.1 and older release/5.0 branches)
- [x] aspnet-Benchmarks (default branch)
- [x] dotnet-crank (default branch)
- [x] dotnet-ef6 (release/6.4)
- [x] dotnet-efcore (release/3.1 and older release/5.0 branches)
- [x] dotnet-extensions (release3.1)
- [x] dotnet-razor-tooling (release/3.1)
- [x] dotent-spa-templates (default branch)

Believe our area path is `internal\ASP.NET Core` but am not positive _all_ of our repos use that area. @danmoseley how would you suggest we handle this part of the work❔ I'm not positive it's best for @wtgodbe or I to file the bugs and drive the exemption process for our team.

**Comment by wtgodbe** [comment]
May be able to request exemptions on benchmarks, crank, and spa-templates since they don't contain production code

**Comment by wtgodbe** [comment]
webhooks-signed can probably be exempted to, it's just tools for signing/running analyzers on the build output of aspnetwebhooks

**Comment by dougbu** [comment]
Get an exemption for dotnet/ef6's release/6.4 branch too. Updating the exemptions list to include that one as well as benchmarks, crank, spa-templates, and aspnetwebhooks-signed&hellip;

**Comment by BrennanConroy** [comment]
signalr-client-cpp should be done?
https://dev.azure.com/dnceng-public/public/_build/results?buildId=65511&view=logs&j=bbc1cd3d-a354-5dde-2dd0-80d464a23c62&t=50be9449-fa7f-5647-1928-dcee7e4b9f37

**Comment by wtgodbe** [comment]
That's CodeQL, we're "upgrading" to CodeQL3000

**Comment by BrennanConroy** [comment]
😠

**Comment by wtgodbe** [comment]
Oh, I'm wrong, I was looking at a build from July because that was the last green one. I forgot you submitted https://github.com/aspnet/SignalR-Client-Cpp/pull/89 - thanks!

**Comment by dougbu** [comment]
We should follow up on that PR to use the same patterns we've established elsewhere.

For one thing, `CodeQL3000` tasks are expensive and shouldn't run in every build. We've been scheduling the additions to the pipelines and, when the schedule runs, skipping as many non-compile operations as we can.

For another, we want to have TSA reports of problems the analysis turns up.l

**Comment by BrennanConroy** [comment]
> shouldn't run in every build

This is already automatic as part of the task.

**Comment by dougbu** [comment]
Sorry, I'm confused. The task automates a schedule of runs how❔

I see https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines#additional-options mentions `Codeql.Cadence` but that defaults to 3 days and focuses on "database recreation". Elsewhere we've used a weekly schedule that has no impact on official builds and never runs in public. (Just turning on `CodeQL3000` can blow timeouts out of the water. That's probably not a SignalR-Client-Cpp issue however.)

**Comment by wtgodbe** [comment]
@dougbu anything left to do from your perspective?

**Comment by dougbu** [comment]
> @dougbu anything left to do from your perspective?

Nope 😁
