### ISSUE TITLE
Compression error in br encoding depending on razor cshtml format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Compression-error-in-br-encoding-dependi/10175071)._

---
[regression] [worked-in:17.2]
Formatting a div to a newline causes a compression error in the response. See attached recording.

This seems to be a recent issue with newer visual studio versions

---
#### Feedback Bot on 10/17/2022, 08:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
Thanks for contacting us. Does this issue occur on other browsers besides Firefox? What exactly is it that you're adding that makes the response break?
