### ISSUE TITLE
Enhance Blazor.reconnect to state whether failures are due to circuit not existing so we can auto-reload page

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#44669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I created a connection support. If it is broken, a message pops up and then every 30 seconds the system tries to establish a connection.

```js
        let network = document.getElementById("network");
        let offline = document.getElementById("offline");
        let online = document.getElementById("online");

        let connect = true; @* Connection life status *@
        let reconnectId = null;     @* Clock ID to reconnect *@

        Blazor.start({
            reconnectionHandler: {

                @* Disconnect *@
                onConnectionDown: (options, error) => {
                    connect = false;
                    network.classList.remove("hidden");
                    offline.classList.remove("hidden");

                    @* First connect *@
                    window.Blazor.reconnect();

                    @* trying to establish a connection *@
                    reconnectId = setInterval(() => { 
                        if(connect == true){
                            console.log("Close timer...");
                            clearInterval(reconnectId);
                        }
                        console.log("Reconnect in progress...");
                        window.Blazor.reconnect();
                    }, 1000 * 30);
                },

                @* Connect *@
                onConnectionUp: () => {
                    connect = true;
                    offline.classList.add("hidden");
                    online.classList.remove("hidden");

                    setTimeout(() => {
                        network.classList.add("hidden");
                        online.classList.add("hidden");
                    }, 3000);
                }
            }
        });
```

Everything works fine until the server loses sessions.
This causes an error that requires the entire page to be reloaded.

I need a function in javascript to check the state if there is a connection to blazor, if it has been broken, if there is any error.
An event like ``onError:``

Example:
```
onError: () => {
 location.reload()
}
```

### Describe the solution you'd like

```
    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
```
Currently, the only option is to manually click or call the meta tag refres, it is not a professional solution.

By the way, why are broken connections by the server not handled? This can be done without reloading the page ...

Also, better handling of the call, more automatic than manual, would be useful. People who see the default messages are scared and leave the site, which results in a drop in impressions.

**Comment by Alerinos** [comment]
I was wondering. We can not store sessions, e.g. for a week? If the client frequently visits the website, why drop him or her? Each entry extends life by 7 days. I understand that for websites with a lot of hits, it can draw a lot of resources, although it seems to me that up to 100k unique users per month it will not be a big problem. I haven't looked in source, what data is stored? They shouldn't weigh much.

**Comment by SteveSandersonMS** [comment]
The team discussed this and we agree with the suggestion. That is, when calling `Blazor.reconnect()` there should be either a return value or an exception or something to indicate if the server is saying "No, that circuit ID is unknown". That would allow developers to react by reloading the page or even changing the UI to say "Sorry, your session has expired - please click here to reload".

Otherwise the developer can't differentiate between this scenario and something like *the internet connection is temporarily down so it's worth retrying the reconnection later*.

**Comment by camistein** [comment]
> The team discussed this and we agree with the suggestion. That is, when calling `Blazor.reconnect()` there should be either a return value or an exception or something to indicate if the server is saying "No, that circuit ID is unknown". That would allow developers to react by reloading the page or even changing the UI to say "Sorry, your session has expired - please click here to reload".
> 
> Otherwise the developer can't differentiate between this scenario and something like _the internet connection is temporarily down so it's worth retrying the reconnection later_.

Any possibility this could be available in a minor version instead of waiting for next major version ?

**Comment by MackinnonBuck** [comment]
@Alerinos, `Blazor.reconnect()` will return a promise that either:
* Rejects if the server could not be reached
* Resolves to `false` if the circuit ID was invalid
* Resolves to `true` if the reconnection was successful

See [this example]( https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md#automatically-refresh-the-page-when-reconnection-fails-blazor-server) that shows how to define custom reconnection behavior. It can be tweaked to handle the two error cases differently.

I'm going to close this as "answered", but please feel free to reopen if you disagree that the existing functionality addresses this issue. Thanks!
