### ISSUE TITLE
Have chunk size as parameter for `DotNetStreamReference`.

### ISSUE THREAD

**Issue by KristofferStrube** [dotnet/aspnetcore#44673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use the [DotNetStreamReference](https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetstreamreference?view=aspnetcore-6.0) available as a part of `JSInterop` in Blazor to create a [ReadableStream](https://streams.spec.whatwg.org/#rs-class-definition) available in JS and I can do this successfully.
A `ReadableStream` has a constructor which I assume .NET invokes somehow which takes a [QueuingStrategy](https://streams.spec.whatwg.org/#dictdef-queuingstrategy). Using the `QueuingStrategy` we can normally define the chunk size of the stream (equivalent to the the buffer size in a .NET `Stream`). Currently it seams that the chunk size is always `2^15=32768`

### Describe the solution you'd like

I would like the constructor of `DotNetStreamReference` to have an optional parameter `ulong chunkSize` (or maybe `long`) so that the chunk size can be configured.

### Additional context

This is related to my work on wrapping the `Streams` browser API in Blazor: https://github.com/KristofferStrube/Blazor.Streams

**Comment by MackinnonBuck** [comment]
@KristofferStrube Thanks for contacting us. Could you please clarify why you want to vary the chunk size? What is it that's not possible to do without changing the chunk size?

**Comment by KristofferStrube** [comment]
Hey @MackinnonBuck thanks for the question. I actually found that the chunk size is a function returning a size which was a misread on my side. That behaviour could be used to have a changing chunk size in scenarios like streaming over the web where larger packets could be tried as long as they are supported and then scrolled back once the limit is reached.
That said I don't think the more advanced function which returns a chunk size would fit into the existing design so I'm closing this issue.
