### ISSUE TITLE
Use additional metadata alongside modified date when determining whether to update compressed assets

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#44671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor publish sometimes does not update compressed versions of linked files.

build log says:
```
Using "GZipCompress" task from assembly "C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\..\tools\net472\Microsoft.NET.Sdk.BlazorWebAssembly.Tasks.dll".
...
Skipping '...\obj\Release\net7.0\linked\Microsoft.AspNetCore.Http.Connections.Client.dll' because 'obj\Release\net7.0\compress\n+2YGD1h.gz' is newer than '...\obj\Release\net7.0\linked\Microsoft.AspNetCore.Http.Connections.Client.dll'.
```

obj\Release\net7.0\linked\Microsoft.AspNetCore.Http.Connections.Client.dll is 7.0.22.47602, 115,328 bytes, Modified: Monday, ‎September ‎26, ‎2022, ‏‎10:17:52 PM. Created ‎Wednesday, ‎October ‎19, ‎2022, ‏‎12:07:04 PM

obj\Release\net7.0\compress\n+2YGD1h.gz decompresses to 7.0.22.42702, 114,320 bytes. gz files is modified: Wednesday, ‎October ‎12, ‎2022, ‏‎4:01:38 PM. Created: same time

This ofcourse causes the 

Firefox: None of the “sha256” hashes in the integrity attribute match the content of the subresource.

Chrome: Failed to find a valid digest in the 'integrity' attribute for resource 'https://.../UI/_framework/Microsoft.AspNetCore.Http.Connections.Client.dll' with computed SHA-256 integrity 'LOc2k+BVbTuiWh3DBAt5ylfaQmPXsR6zyEyLZeOHmHE='. The resource has been blocked.

### Expected Behavior

A better metric than just the modified date is used to ensure proper builds, which causes the files to get updated down the pipeline.

### Steps To Reproduce

1. Build.
2. Upgrade any component in the blazor build
3. Build again -> compressed version not updating

### Exceptions (if any)

no

### .NET Version

6+

**Comment by TanayParikh** [comment]
Hey @davhdavh, thanks for reaching out. I just tried reproducing the issue, however I'm not seeing the same error. Can you please provide a minimal, public, GitHub repository which reproduces this issue?

**Comment by TanayParikh** [comment]
@davhdavh are you seeing the same thing as https://github.com/dotnet/aspnetcore/issues/38552?

**Comment by davhdavh** [comment]
Very similar problem at the very least.
I do see some comments there about stale hash calculations in the
service-worker-assets.js file, which is not related to this problem.

**Comment by davhdavh** [comment]
Because it requires updates across different version while having previous publish build, it is quite difficult to share a repro.

**Comment by TanayParikh** [comment]
> A better metric than just the modified date is used to ensure proper builds, which causes the files to get updated down the pipeline.

Why do you believe the modified date is the issue?

Is it because:

> Modified: Monday, ‎September ‎26, ‎2022, ‏‎10:17:52 PM. Created ‎Wednesday, ‎October ‎19, ‎2022, ‏‎12:07:04 PM

Which raises concern given `modified date < created date`?

**Comment by davhdavh** [comment]
Because thats what msbuild says

Skipping
'...\obj\Release\net7.0\linked\Microsoft.AspNetCore.Http.Connections.Client.dll'
because 'obj\Release\net7.0\compress\n+2YGD1h.gz' is newer than
'...\obj\Release\net7.0\linked\Microsoft.AspNetCore.Http.Connections.Client.dll'.

**Comment by TanayParikh** [comment]
Unasigning as investigation is complete.
