### ISSUE TITLE
Kestrel picks a docker generated certificate 'in front' of a generated developer certificate

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#44685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently filed an issue (https://github.com/dotnet/aspnetcore/issues/44651) wherein the certificate chosen by Kestrel was an expired certificate generated from previous use of Docker for the project in question.

Deleting the content of %APPDATA%\ASP.NET\https resolved the issue per the help provided by @javiercn and the issue was closed.

After further research trying to understand why Kestrel was picking that certificate over a developer cert I discovered that I am not the only one who has run afoul of this issue. The closed issue https://github.com/dotnet/aspnetcore/issues/26536 describes exactly the same issue & resolution.

I believe that Kestrel needs documentation of the search path for certificates at a minimum but prefer that Kestrel would  choose the developer certificate over the Docker certificate.

### Expected Behavior

I really would expect the developer cert should be chosen over the Docker cert.

### Steps To Reproduce

Create and trust a developer certificate

Place the attached pfx file in %APPDATA%\ASP.NET\https

Create a project with a REST endpoint

Create a project invoking the REST endpoint over SSL

With the Docker cert in place the REST call will fail

Instead of building the two apps you can use the project at https://github.com/MarkStega/ICEBG

### Exceptions (if any)

See https://github.com/dotnet/aspnetcore/issues/44651 for the exception

### .NET Version

Same as #44651

### Anything else?

[Https.zip](https://github.com/dotnet/aspnetcore/files/9840641/Https.zip)

**Comment by Tratcher** [comment]
This is controlled by tooling, not kestrel. Kestrel only tries to find the dev cert when it's not told which cert to use. I also don't think the dev cert is available in a docker container. To make containers work the tooling puts the dev cert in that %APPDATA% file and sets config to tell kestrel to use that specific cert, disabling any search logic.

It sounds like the root bug here is not kestrel's cert locating logic, but rather that the tooling should be checking that the certificate is still valid and updating it if not.

**Comment by adityamandaleeka** [comment]
It sounds like (based on the discussion in #26536), the docker tooling created a certificate, then after that certificate expired, non-docker scenarios try to use the expired cert and fail.

We should check if there's a clear warning/error when this happens (and improve it as necessary).

Also, on Windows, should we be using an on-disk cert over what's in the cert store in non-Docker scenarios? cc: @javiercn

**Comment by javiercn** [comment]
@adityamandaleeka An explicit gesture is required to load the certificate from disk. Typically, docker sets this up via an environment variable. If no environment variable is setup, Kestrel won't load anything from disk. So there must be something in @MarkStega that was triggering the certificate load. 

For context, the way this is intended to work is that tooling should always run the command to export the cert, as that ensures its always "fresh" and up to date, but seems that is not happening. There are two things we can do:
* Talk to the docker tools folks to see if they can change that behavior.
* Update `dotnet dev-certs` to clean the `%APPDATA%\ASP.NET\https` (and equivalent on Linux/OSX) folder when you run `--clean`.
  * It is desirable that the tool is decoupled from the tooling, so it would be better if tooling can check the file on disk to be appropriate, but if not, I think cleaning things up in dev-certs is a reasonable compromise.

**Comment by MarkStega** [comment]
@javiercn 

Thanks for the update, I agree that the 'clean' should go to all locations. Another useful addition would have been a way to list the available certs.

Do you know what environment setting that Docker is setting which causes the certificate searh to use APPDATA? I looked at the output of a 'set' command and all I can find that references  'Appdata\Roaming' is the definitions of "APPDATA". I assume that the behavior in #26536 was triggered by the same issue/setting.

**Comment by javiercn** [comment]
@MarkStega this is all documented https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-2.2#running-pre-built-container-images-with-https and https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio

For some reason I do not know why the actual tooling mechanism is not described. But in essence, we look for a key "Development" inside kestrel's certificate config, so if you have a key in your config like
`Kestrel:Certificates:Development:Path` we will try to load it.

The relevant code is below if you care about it.

https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs#L422-L451

**Comment by adityamandaleeka** [comment]
@MarkStega Can you try removing the user secret `Kestrel:Certificates:Development:Password` which should prevent your app from trying to load the cert from disk?

@pratiksanglikar Is there any guidance for people who want to run apps which were formerly in Docker outside of Docker? Seems like this is a common issue those folks will hit if the tooling automatically set these things up for them.

**Comment by MarkStega** [comment]
@adityamanddaleeka

Yes, removing the secret allows the application to run even with the pfx file present. But this is no more a solution then removing the pfx file as both were created by docker & it isn't evident that they are present.

I'd suggest that 'dotnet dev-certs clean' needs to include "%APPDATA%\ASP.NET\https" and having a new switch "dev-certs list" which listed all certificates and pertinent details in the order that they are presented to Kestrel would also help,

**Comment by adityamandaleeka** [comment]
> I'd suggest that 'dotnet dev-certs clean' needs to include "%APPDATA%\ASP.NET\https"

This seems like a reasonable suggestion.

cc: @vijayrkn Does your team own the Docker tooling? Do you know why we would need the user secret at all?

**Comment by vijayrkn** [comment]
@Ncarlsonmsft - Is there a GH repo to transfer this to or would you require a devcomm issue to track this?

**Comment by NCarlsonMSFT** [comment]
@vijayrkn https://github.com/microsoft/DockerTools

**Comment by adityamandaleeka** [comment]
Filed https://github.com/microsoft/DockerTools/issues/362
