### ISSUE TITLE
CORS error when deploying Net 6 API on docker

### ISSUE THREAD

**Issue by Hyphaed** [dotnet/aspnetcore#44694]
Hi people

I'm on Ubuntu 22.04 LTS

I do have CORS problems when packing Net6 API into Docker image and using it

yet if I do dotnet run, the API works fine

what should I do to solve it?

I haven't found documentation about this issue on official Microsoft Documentation neither Docker Documentation

**Comment by blowdart** [comment]
What is the actual problem? What error messages do you see? How are you using it?
