### ISSUE TITLE
Update the documentation about the templates on learn.microsoft.com for .NET 7

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/aspnetcore#44712]
learn.microsoft.com features 2 articles where the templates are mentioned:
- https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new#arguments - list of the available templates
- https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates - the documentation on the templates available with .NET SDK, including specific options.

Consider updating the articles for .NET 7:
- in case new templates were added, please them add them to the table list
- in case the template options were added, modified or removed, please adapt the description accordingly

Note that for many cases, the EOL frameworks are present: `netcoreapp3.0`, `net5.0` etc. Consider removing them.

The source code is here:
- https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md
- https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-sdk-templates.md

**Comment by javiercn** [comment]
@vlada-shubina thanks for letting us know.

Folks from each team, consider whether you added templates and untag your area accordingly.

**Comment by mkArtakMSFT** [comment]
We've added only Empty Blazor Project templates, which do show up in one of the links provided here. Will look into adding these to the other page too.

**Comment by mkArtakMSFT** [comment]
Filed a separate issue for Blazor.

**Comment by adityamandaleeka** [comment]
I don't think we (runtime) own any templates.

**Comment by captainsafia** [comment]
@DamianEdwards Can you share if we need to do anything for the web frameworks templates here?
