### ISSUE TITLE
Document how to automatically refresh the browser when the Blazor Server connection is lost

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#44715]
We should provide guidance on how to create a Blazor Server app that auto refreshes the browser if the connection gets lost. Should this be done by [customizing the reconnection handler](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr#modify-the-reconnection-handler-blazor-server)?

**Comment by brockallen** [comment]
I've been wondering how long it'd take you to think about this problem :)

**Comment by danroth27** [comment]
I mean triggering an auto browser refresh if the circuit gets lost. I thought for sure we already had this documented already, but then I went looking for it and couldn't find it 😳.
