### ISSUE TITLE
Optimize ASP.NET Core publish size

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#44721]
We should investigate what we can do to reduce the publish size of ASP.NET Core apps when trimming or AOT is enabled.

Feature level:
For example, if an app isn't using TLS, then ensure its types, such as HTTPS middleware and SslStream, aren't included. Or if an app isn't using HTTP/3, then QUIC + HTTP/3 types aren't included. etc. Excluding these high-level features might be difficult because they're enabled by config.

Dependencies:
Also, analyze dependencies that ASP.NET Core is using in dotnet/runtime. e.g. switch from using immutable collections to standard collections so immutable collections aren't included in publish.

**Comment by alc-aardvark** [comment]
Hi.  Is there an article that shows what limitations prevent just having a .wasm file without loading dll's.  i.e. what stops a pure wasm blazor exe using NativeAOT.   I understand reflection, but I have heard about things like try/catch being a problem.  I am sure more people would love to understand what the problem areas are just so we can get some understanding.  Maybe it shows what is a WASM limitation vs what is just a .Net limitation.  Thanks

**Comment by adityamandaleeka** [comment]
@JamesNK I think this can be closed now? We can open new issues for any specific work we want to do in the future.
