### ISSUE TITLE
.NET Core 7 Output Cache does not work with app.UseEndpoints() properly

### ISSUE THREAD

**Issue by Gebov** [dotnet/aspnetcore#44739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When configuring the endpoints using **app.Map** everything works as expected. But when the endpoints belong to a controller that is configured with **app.UseEndpoints()** the cache does not ignore one of  the paths to the controller.

I am using a call to UseEndpoints to configure a controller with two methods, both of which have the OutputCache attribute set to a preconfigured policy based on a dynamic condition (in this case it just checks the URL. My real case scenario is somewhat different and checks for a flag in the HttpContext.Items collection). 

Here are the tested URLS  (test app is attached):

// expected to be cached, works, uses **app.Map**
/TimeCached

// expected to be not cached, works, uses **app.Map**
/TimeNotCached

// expected to be cached, works, uses **app.UseEndpoints()**
/Home/TimeCached

// expected not to be cached, **does not work** , uses **app.UseEndpoints()**
/Home/TimeNotCached

### Expected Behavior

I would expect that the call to app.UseEndpoints() would behave the same way as app.Map() and respectively **cache** and **not cache** depending on a dynamic condition within the configured policy.

### Steps To Reproduce

Just run the code sample and browse the following URLS:

// expected to be cached, works, uses **app.Map**
/TimeCached

// expected to be not cached, works, uses **app.Map**
/TimeNotCached

// expected to be cached, works, uses **app.UseEndpoints()**
/Home/TimeCached

// expected not to be cached, **does not work** , uses **app.UseEndpoints()**
/Home/TimeNotCached

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

[output-cache-tests.zip](https://github.com/dotnet/aspnetcore/files/9868168/output-cache-tests.zip)

**Comment by adityamandaleeka** [comment]
@Gebov can you please share the repro as a public GitHub repo instead of a zip? Our policy is not to accept repros shared as zip files.

**Comment by Gebov** [comment]
@adityamandaleeka Here it is:

https://github.com/Gebov/aspnetcore-7-cache-issue

**Comment by Gebov** [comment]
The same behaviour is visible if instead of UseEndpoints I use:

app.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");

**Comment by sebastienros** [comment]
Issue isolated and fix provided. I will ask to backport the fix for the next service release once it's merged.

**Comment by martonx** [comment]
Hi,

Output cache doesn't work even with app.MapControllers();
Could you check that fix will work with this way of routing?

**Comment by sebastienros** [comment]
> Output cache doesn't work even with app.MapControllers();

do you mean "at all" or this specific bug?

**Comment by martonx** [comment]
ah I found it. Output cache is working only without Authorization. But why?

In this case:
[Authorize(Roles = "Administrator")]
[OutputCache(Duration = 3600)]

cache doesn't work.

In this case:
[AllowAnonymous]
[OutputCache(Duration = 3600)]

cache works

**Comment by Gebov** [comment]
@martonx This should be by design. Since the cache caches everything (including cookies) you should not be able to cache the cookies of the authenticated user. That would mean the anonymous users would have access to those cookies as well.
