### ISSUE TITLE
Swashbuckle and also NSwag error with "no operations defined in spec" in a complex application

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/aspnetcore#44733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've also reported an issue at: 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2525

But as I've searched, is ApiExplorer used by Swashbuckle to find controlers?

I've copied the code from a workin sample application, in a dynamicly loaded assembly in a complex app, wich creates an host for the api itself, but then it does not find any of the controllers.

### Expected Behavior

Controlers should be found

### Steps To Reproduce

It's not easy to reproduce, as it only happens in our big application.

### .NET Version

6

**Comment by captainsafia** [comment]
> But as I've searched, is ApiExplorer used by Swashbuckle to find controlers?

Yes, ApiExplorer is used to discover controllers in a target application.

> I've copied the code from a workin sample application, in a dynamicly loaded assembly in a complex app, wich creates an host for the api itself, but then it does not find any of the controllers.

Am I understanding correctly that your controllers are defined in another assembly that is dynamically loaded at startup into the application where Swashbuckle is registered? If so, that would explain why you are not seeing the controllers. Swashbuckle evaluates the operations to populate by looking for the ApiExplorer descriptions in DI. It's likely that the DI for the target application doesn't contain the controllers you defined in the externally loaded assembly.

How are you loading the assembly with controllers?

**Comment by jogibear9988** [comment]
> > But as I've searched, is ApiExplorer used by Swashbuckle to find controlers?
> 
> Yes, ApiExplorer is used to discover controllers in a target application.
> 
> > I've copied the code from a workin sample application, in a dynamicly loaded assembly in a complex app, wich creates an host for the api itself, but then it does not find any of the controllers.
> 
> Am I understanding correctly that your controllers are defined in another assembly that is dynamically loaded at startup into the application where Swashbuckle is registered? If so, that would explain why you are not seeing the controllers. Swashbuckle evaluates the operations to populate by looking for the ApiExplorer descriptions in DI. It's likely that the DI for the target application doesn't contain the controllers you defined in the externally loaded assembly.
> 
> How are you loading the assembly with controllers?

No, the Controllers are in the same assembly wich also starts the swashbuckle asp service. But this assembly is loaded into a complex application.
Wich Setup call looks for the Controllers? And can I print out wich ones are found? And where can I specify the Assemblies to search for?

**Comment by jogibear9988** [comment]
We solved it, thanks for the help.

We now used this calll:

      builder.Services.AddControllers().AddApplicationPart(typeof(RestConnectorService).Assembly).AddControllersAsServices();

even if the assembly from wich the server is run was the one with the controlers, we need to specify it in AddAppilcationPart
