### ISSUE TITLE
Run Debugger on WebApi project which is stored within WSL2

### ISSUE THREAD

**Issue by Baklap4** [dotnet/aspnetcore#44751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We can't run a default WebApi project (which is stored in the ubuntu distro) and debug through it running from VS2022.

### Expected Behavior

To be able to host and run my C# solution within a wsl ext4 partition instead of having to use the slower NTFS which is mounted on /mnt/c/somepath.

### Steps To Reproduce

1. Open up wsl2 and go to your home folder
2. Create a webapi project
3. Open the webapi project in VS2022 through the explorer: \\wsl$\<yourdistro>\home\<user>\webapi\webapi.sln
4. Change F5 behavior to run the WSL launch profile
5. Invalid 'cwd' value '/mnt/\//home/johndoe/webapi/WebApi'. The system cannot find the path specified.

### Exceptions (if any)

none

### .NET Version

6.0.110

### Anything else?

Stackoverflow questions:
https://stackoverflow.com/questions/71767208/unable-to-debug-wsl2-with-vs-2022-invalid-cwd-value
https://stackoverflow.com/questions/71793535/issues-visual-studio-with-wsl-debugging-for-c-sharp-asp-net-core-web-api?noredirect=1&lq=1

Devblogs Microsoft comments (2020):
https://devblogs.microsoft.com/dotnet/debug-your-net-core-apps-in-wsl-2-with-visual-studio/#comment-7947

**Comment by davidfowl** [comment]
cc @vijayrkn

**Comment by vijayrkn** [comment]
Adding @dbreshears & @NCarlsonMSFT since this is related to wsl2 debugging.

**Comment by NCarlsonMSFT** [comment]
@Baklap4 I just verified, the fix for this is available in 17.4 Preview 5.0.

**Comment by Baklap4** [comment]
@NCarlsonMSFT Any chance i can already try out 17.4 preview 5.0?

**Comment by NCarlsonMSFT** [comment]
@Baklap4 
17.4 should release in the next few weeks
For Edit 2: A mapped network path is not currently supported for the WSL Debugging feature, the best place to file that suggestion would be: https://developercommunity.visualstudio.com/VisualStudio/suggest
For Edit 4: I recommend using the "report a problem" button in VS to log an issue:
![image](https://user-images.githubusercontent.com/14239288/198734923-a3886a28-2ff9-4827-8b6d-c5563d2cd9e8.png) using that you can capture the repro and it can get triaged to correct team.

For my own interest, do you have the issue from Edit 4 when using a mapped drive for the share?

**Comment by NCarlsonMSFT** [comment]
@Baklap4 Update on using the mapped drive approach, while the auto path mapping doesn't support this, you can work around it by manually setting the working directory and arguments in the launch profile. For example:
```JSON
"WSL-Custom": {
  "commandName": "WSL2",
  "launchBrowser": true,
  "launchUrl": "https://localhost:7090",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development",
    "ASPNETCORE_URLS": "https://localhost:7090;http://localhost:5194"
  },
  "distributionName": "Ubuntu",
  "workingDirectory": "/root/TestProject",
  "executablePath": "dotnet",
  "commandLineArgs": "bin/Debug/net6.0/TestProject.dll"
}
```

The obvious downside is that there is an absolute path for the working directory, which is inconvenient across multiple machines.

**Comment by Baklap4** [comment]
@NCarlsonMSFT 
> 17.4 should release in the next few weeks

Very nice, this solves a couple of issues i'm currently having so looking forward to it!

> For Edit 2: A mapped network path is not currently supported for the WSL Debugging feature, the best place to file that suggestion would be: https://developercommunity.visualstudio.com/VisualStudio/suggest

I'll add a suggestion to there 👍 

> For my own interest, do you have the issue from Edit 4 when using a mapped drive for the share?

The issue is not there when you load the sln from a mapped drive. Also renaming the file triggering the `MoveTypeCodeRefactoringProvider` works!

> Update on using the mapped drive approach, while the auto path mapping doesn't support this, you can work around it by manually setting the working directory and arguments in the launch profile

This seemed to work and will be my go to workflow for now 👍 

I think all of my problems have been solved. Thanks a lot for the fast feedback :)
