### ISSUE TITLE
Blazor / SEO / index in search engines

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#44750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

blazor webassembly is not recognizable by indexing robots

### Describe the solution you'd like

from my searches, I understood that only the host version of WASM made it possible to be recognizable by search robots. but I saw that a private component had a hack to make it work.

so, I wanted to suggest that some component or service be made that answers the necessary data for a search robot without having to download everything from the blazor project (which clearly doesn't work)

### Additional context

I know theoretically if it was a server it would work. but I'm using a pure webassembly precisely because I don't want to have server costs.

**Comment by TanayParikh** [comment]
Do you have prerendering enabled in your app? https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?pivots=webassembly

**Comment by drma-dev** [comment]
@TanayParikh no, because you are required to pay for a server. everything I'm avoiding. Or did I understand something wrong about the host option?

**Comment by javiercn** [comment]
@drma-dev what you are describing likely involves static prerendering, which is something we want to cover as part of https://github.com/dotnet/aspnetcore/issues/38114

**Comment by javiercn** [comment]
@drma-dev I am going to mark this as a dupe and I suggest you upvote the other issue instead so that we can keep track of the feedback.

**Comment by drma-dev** [comment]
I didn't see anything there that made it clear that this functionality is expected, but ok.
