### ISSUE TITLE
Monitor HTTP response buffer to detect lagging

### ISSUE THREAD

**Issue by Mazaaap** [dotnet/aspnetcore#44761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to implement a MJPEG generator/proxy with ASP.NET 6 to display realtime frames without any lag. It works fine except when the network starts to congest (eg via mobile connection) and then the stream starts lagging.

I would like to have some interface to monitor response buffer so that I could stop sending new frames when it starts to congest. Or any other nice way to achieve the same.

### Describe the solution you'd like

```
        while (true)
        {
            var timeStamp = _jpegGeneratorService.GetTimeStamp().ToString("o");
            var image = _jpegGeneratorService.GetImage();
            Console.WriteLine("Length: " + image.Length +"  TimeStamp: " + timeStamp);

            if (image.Length > 0)
            {
                try
                {
                    await bodyStream.WriteAsync(image, cancellationToken);
                    await bodyStream.FlushAsync();

                    // TODO: WAIT HERE WHEN THE STREAM IS REALLY FLUSHED
                }
                catch (Exception e)
                {
                    Console.WriteLine("HTTP write error:\n" + e);
                    break;
                }
            }
            await Task.Delay(delayMs);

        }
```

Full source code here: https://github.com/Mazaaap/SimpleMjpegGenerator

**Comment by adityamandaleeka** [comment]
@Mazaaap Are you trying to drop frames when there's congestion? If so, TCP isn't a great system unless you have extra application layer logic on top. The code you already have will wait, but by then there are buffers in place at virtually every part of the stack so it won't give you the level of control you seem to be looking for.

For instance, using WebSockets with application-level ACKs will allow you to have finer control over the buffering and what data gets to the client.
