### ISSUE TITLE
Return enumerable as json lines

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#44778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Returning a big list of objects takes a long time to assemble (i.e. load from EF) and the na long time to process in the frontend again.

Concrete use case would be a flight comparison like skyscanner, returning multiple results as they come in from the airlines, showing them to the customer as soon as they arrive and updating some stats like "cheapest"/"shortest".

### Describe the solution you'd like

I'd like to return the list as json lines instead of a json array, written into the response as the objects come in (i.e. as an IAsyncEnumerable is enumerated), so the caller can start processing it.

The only alternative I see, provided we stay with a Rest call and not use SignalR or some other stateful connection, is to return a stream and manually feed the objects into that as they manifest.

### Additional context

After thinking the whole format through for myself, I went to the internet and realised that somebody already had the idea before me (who'd've thunk?) and called it json lines: https://jsonlines.org/

**Comment by davidfowl** [comment]
You can do this today manually, I'm not sure overloading the behavior based on return type is wise. It should be a new type or this should be done manually.

> After thinking the whole format through for myself, I went to the internet and realised that somebody already had the idea before me (who'd've thunk?) and called it json lines: https://jsonlines.org/

This is good, but not something that we would add to the framework natively, that requires it to be ubiquitous.

**Comment by Regenhardt** [comment]
Is there a way to write my own attribute then, to receive a returned IAsyncEnumerable or IEnumerable from a method and do the serializing into the http response there?

**Comment by davidfowl** [comment]
Yes, you can write your own [OutputFormatter](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.formatters.outputformatter?view=aspnetcore-6.0)
