### ISSUE TITLE
[Blazor] CustomElement affects the results of MarkupString

### ISSUE THREAD

**Issue by capdiem** [dotnet/aspnetcore#44785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

added the package **Microsoft.AspNetCore.Components.CustomElements** 7.0.0-rc.2.22476.2

```c#
@((MarkupString)str)

@code {
    string str = @"
    <div>there is the origin markup</div>
    <custom-element />
    <div>other content</div> 
    ";
}
```

The content after `<custom-element />` will not be displayed.

### Expected Behavior

The content after `<custom-element />` should be displayed.

### .NET Version

7.0.100-rc.2.22477.23

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
CustomElement-s cannot be self-closing. Please change that usage to `<custom-element></custom-element>` and let us know if you are still observing the reported behavior.

**Comment by capdiem** [comment]
@mkArtakMSFT it works, thanks!
