### ISSUE TITLE
Blazor WASM integrity check failed behind corporate proxy (Zscaller)

### ISSUE THREAD

**Issue by fdonnet** [dotnet/aspnetcore#44782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi,

It seems Zscaller(proxy) does something on the _framework dll of my Blazor wasm app.
I checked the sha256 hash on the server and on a personal machine in local cache, and it fits, same result, and it works without issue.

But on a corporate machine behind Zscaller (proxy) I have a complete different hash result and the integrity check failed (403 on the framework dlls). Cannot use the app.

I tried to rename the dlls into bin and tried the new experimental nugget to publish with the new rename option etc (BlazorWasmAntivirusProtection nugget) wihtout success.

No need to run the powershell script to check integrity because I can confirm the issue is not linked to the publish method or bad assembly history during the build.

For info, i use AOT.

### Describe the solution you'd like

Do I have any workaround for this kind of behaviors. Corporates are using that kind of grrrr a lot and at the end, we cannot change any policy or even request something about it.

I don't know why this proxy is modifying the files it delivers....

Maybe someone found a solution for this kind of specific issues ?

**Comment by fdonnet** [comment]
Maybe the proxy is not changing the files but it doesn't want to load the _framework dlls even with the new/experimental "BlazorWasmAntivirusProtection" nugget enable... I don't know if the 403 is more important than the integrity check failed, But it is sad because the app is so lovely ;)

**Comment by TanayParikh** [comment]
Hey, thanks for reaching out.

Have you had a chance to check out: https://devblogs.microsoft.com/dotnet/custom-deployment-layout-for-blazor-webassembly-apps/? It contains some tips which may be helpful in your scenario.

**Comment by fdonnet** [comment]
I will try to [BlazorWasmAntivirusProtection](https://github.com/stavroskasidis/BlazorWasmAntivirusProtection) again with other file extensions (next week). But without much hope. Zscaller home page quote "The Zero Trust Leader" hahaha ;)

**Comment by fdonnet** [comment]
Tried this morning with .dat extension................... and it works. Thanks a lot to https://github.com/stavroskasidis/BlazorWasmAntivirusProtection ... it works. Happy. I will inform @stavroskasidis

**Comment by fdonnet** [comment]
solved with external BlazorWasmAntivirusProtection package.
