### ISSUE TITLE
dynamic endpoint in controller

### ISSUE THREAD

**Issue by sofu456** [dotnet/aspnetcore#44790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

client send a endpoint to server,if i want receive it and create a new endpoint in the controller, i found it is impossible. 

i try use UseEndpoints twice, but only the first one will active.

help me, please.

### Describe the solution you'd like

dotnet core asp,get a endpoint and new it in the controller or any other way

### Additional context

nothing

**Comment by davidfowl** [comment]
It's not clear what you want to do from this description. Can you show a code sample? What is the dynamic endpoint in this situation? What causes it to be added? Where is the code for this endpoint and how does it get loaded into the application?
