### ISSUE TITLE
Binding to input datetime-local deletes day when entering 0 first

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#44796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Binding to an input of type datetime-local behaves different from the default HTML behaviour.

Take a look on this:
![blazor-bind](https://user-images.githubusercontent.com/32510006/199046014-cc599a5f-010b-455a-a5b2-4d6015c1081a.gif)

As you can see when I enter "0" for month it resets the input to a default datetime. When I press only the corresponding number of the month it works as expected. This also happens when you enter a 0 first on day.

The code for this is:
```
<div class="form-floating mb-3">
    <input type="datetime-local" @bind="Input.Von" @bind:format="yyyy-MM-ddTHH:mm:ss" class="form-control" id="besuch-anmelden-von" placeholder="Von" />
    <label for="besuch-anmelden-von">Von</label>
    <ValidationMessage For="() => Input.Von" />
</div>
```

Now lets compare it to blank HTML:
![blank-html](https://user-images.githubusercontent.com/32510006/199046586-ecf4d081-4677-4519-bd02-76449963fb85.gif)

As you can see in plain HTML the input does not reset when typing a 0 first.

`<input type="datetime-local" />`

### Expected Behavior

It should work just like in HTML. Most people will type 08 to enter the month, not just 8. However both options should be possible.

### .NET Version

dotnet --info .NET SDK:  Version:   6.0.402  Commit:    6862418796  Laufzeitumgebung:  OS Name:     Windows  OS Version:  10.0.19044  OS Platform: Windows  RID:         win10-x64  Base Path:   C:\Program Files\dotnet\sdk\6.0.402\  global.json file:   Not found  Host:   Version:      6.0.10   Architecture: x64   Commit:       5a400c212a  .NET SDKs installed:   6.0.402 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Download .NET:   https://aka.ms/dotnet-download  Learn about .NET Runtimes and SDKs:   https://aka.ms/dotnet/runtimes-sdk-info

### Anything else?

This might be connected with #40660

**Comment by MarvinKlein1508** [comment]
There is a workaround to prevent this behaviour. Preventing the property from being set to the default value. It works but now you won't be able to set it to the default value of datetime at all. Luckily I can ignore this in my case.
```

public DateTime Von
{
    get => _von; 
    set
    {
        if(value == new DateTime())
        {
            return;
        }

        _von = value;
    }
}
```

**Comment by mkArtakMSFT** [comment]
Tanks for contacting us. This seems to be the same #43824
