### ISSUE TITLE
ERROR java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by ritika-becker** [dotnet/aspnetcore#44837]
Hi

Am using this library in my android app.
implementation 'com.microsoft.signalr:signalr:6.0.5'

Actually we are trying to connect android app with our local server using SignalR. We don't want to use some another hubconnectionbuilder methods. On live server everything is working fine. But on local server hub connection throws an exception.
Local server URL: https://192.168.1.150/axle-api

Here is my code snippet:

var mHubConnection = HubConnectionBuilder.create("[https://192.168.1.150/axle-api/chatconnection?LoginId=80560&Contacts=[1](https://192.168.1.150/axle-api/chatconnection?LoginId=80560&Contacts=%5B1), 60576, 70559, 70560, 80556]").build()

    if (mHubConnection.connectionState == HubConnectionState.DISCONNECTED) {
        try {
            mHubConnection.start().doOnComplete {
                Log.e("TestingSignalR", "CONNECTED")                  
            }.doOnError {
                Log.e("TestingSignalR", "ERROR $it")
            }.onErrorComplete {
                Log.e("TestingSignalR_Exp", "ERROR $it")
                true
            }.subscribe()
        }
        catch (e: Exception){
            Log.e("TestingSignalR_Exp", e.printStackTrace().toString())
        }
Please check the screenshot of error. And Please help me to resolve this issue as soon as possible.
https://prnt.sc/ZgmovYT-7EZW.

Thanks in Advance

**Comment by javiercn** [comment]
@ritika-becker thanks for contacting us.

Very likely what is happening here is that Java does not consider the certificate you are using on the server to be valid. If you are using the asp.net core dev-cert, it won't work with anything other than `localhost`. In this case, you'll have to create your own cert, configure kestrel to use it and configure java to trust it.
