### ISSUE TITLE
React/Redux/ASP.Net Core templates for .Net 6.0

### ISSUE THREAD

**Issue by sahgilbert** [dotnet/aspnetcore#44830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

As per [#465](https://github.com/aspnet/Announcements/issues/465), you stated that you would be dropping support for the React/Redux/ASP.Net Core template in .Net 6.0.

As per [#27887](https://github.com/dotnet/aspnetcore/issues/27887), you stated that you would be implementing a new method for creating React/Redux/ASP.Net Core templates for .Net 6.0.

Both of these issues are locked, so please can you provide an update on how we implement the aforementioned SPAs in .Net 6.0?

Thank you

**Comment by javiercn** [comment]
@sahgilbert thanks for contacting us.

We do not plan to continue including a react-redux template inbox. As for the future, we are still working on separating the JavaScript bits of the template into their own project.

So far, what we did in 6.0 was to decouple ASP.NET Core of the frontend used for developing the SPA. You should be able to use whatever frontend you want following the guidance of the chosen framework to integrate with a given backend.
