### ISSUE TITLE
Mainlayout Page prevents the responsive table rendering when element has 100% width

### ISSUE THREAD

**Issue by Venkat-Ayothi** [dotnet/aspnetcore#44840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have created the Blazor application using the [Blazor project template](https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-6.0), so the **MainLayout** component is the app's [default layout](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0#apply-a-default-layout-to-an-app).

Now, we have tried to render the table as responsive on the page and we set the parent element width as 100%. Please refer to the following code example screenshot,

![image](https://user-images.githubusercontent.com/92902915/199493258-eb398bda-53e7-44c1-9f0d-0633bb207ce1.png)

We have more columns and the column's width exceeds the browser window width. So, we expected a native horizontal scrollbar will be rendered. But, the browser scrollbar was rendered and the above div element exceeded the browser window width as like in the following screenshot,
![image](https://user-images.githubusercontent.com/92902915/199483339-d6409d8c-d98e-43d4-85c0-cc06f71d6102.png)

Furthermore, we have found the issue when we render the above code within the <Main> tag, if we define the code in before <Main> tag then it's works as expected. 

Could you please refer the following code example and screenshot for your reference?

Rendering the same code in MainLayout page before <Main> tag as like as follows,

![image](https://user-images.githubusercontent.com/92902915/199493476-581f59d4-2f5e-4e2b-8ca1-00078b449701.png)

Screenshot:
![image](https://user-images.githubusercontent.com/92902915/199484694-cf544582-605b-4527-9b8d-fab697a492ec.png)

In the above screenshot, the horizontal scrollbar is rendered properly rather than the browser scrollbar. 

Please refer following Gif image too,

Issue Gif:
![Issue](https://user-images.githubusercontent.com/92902915/199487154-760ead51-2ccc-4f51-9ef1-f303813e0c3e.gif)

Expected Gif: 
![Scroller](https://user-images.githubusercontent.com/92902915/199487061-874f2d48-4e6a-43e5-8a21-c0029facca77.gif)

### Expected Behavior

A native scroller should render rather than a browser scroller.

![Scroller](https://user-images.githubusercontent.com/92902915/199487469-a63e20a7-c715-40f2-a3f5-341c1a345867.gif)

### Steps To Reproduce

Simple steps
1. run the sample 
2. Browser scrollbar will be rendered
3. Now, you can clear/comment on the index component code
4. Go to the MainLayout page which is under the Shared folder
5. Now, you can see the commented code. 
6. Uncomment it and run the sample again
7. Now, the native scroller will be rendered properly as expected

[Project Repo](https://github.com/Venkat4655/BlazorIssue)

### Exceptions (if any)

NA

### .NET Version

6.0.305

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

Please note, that we encourage customers to customize their styling as they wish after project creation.
