### ISSUE TITLE
Using SignalR Clients.All.SendAsync in a registered Middlware without disconnecting when making a request to trigger middleware.

### ISSUE THREAD

**Issue by WingZer0123** [dotnet/aspnetcore#44858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a middleware that looks like this. Logs all requests coming into an application into MongoDB for historical data purposes. I want to push these new logs to a SignalR Hub to all clients connected before it is saved to MongoDB. SignalR gets disconnected when doing a `Clients.All.SendAsync` in a middleware in a NET Core 3.1 when making a post request. 

![image](https://user-images.githubusercontent.com/114699222/199632117-fca6de1c-6f5f-45a7-a0cc-8352a7d99aa2.png)

Is it possible to use SignalR like this in a middleware as opposed to the same functionality over and over directly in the controller? Or am I missing a detail of the Request Pipeline when using Middleware that is causing the websocket connnection to disconnect within the middleware?  

### Expected Behavior

![image](https://user-images.githubusercontent.com/114699222/199632480-145ccae8-6a54-48a2-b26c-bcb7eb0b90ee.png)

Same behavior of pushing the data to all clients if I was to register this class as a Singleton and use it above this method or any method in a Controller.

![image](https://user-images.githubusercontent.com/114699222/199632401-d2cb79d1-4011-4eaa-89ac-fe3898e92a21.png)
 

### Steps To Reproduce

Create a SignalR Hub.
Connect to Hub via React or Angular.
Send to all client connected to hub in Middleware that shown above.

### Exceptions (if any)

N/A

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

.NET Core 3.1 issue.

**Comment by davidfowl** [comment]
I'm confused by the question, are you asking how to inject the `LogRequestService` into middleware? 

> SignalR gets disconnected when doing a Clients.All.SendAsync in a middleware in a NET Core 3.1.

What does this mean? Are you saying that refreshing the page kills the websocket connection? If so, that's normal, expected and by design. You need a different URL that is the logviewer that can watch incoming requests.

**Comment by WingZer0123** [comment]
I apologize for not being as descriptive as I should have been. This is definitely more of a by design or not question. No, the websocket connection is established with no problem having the the service injected into the middleware and registered as a singleton and the method in place to being called.

When I perform a POST request through postman to attempt to send out a comet push within the middleware before it is being logged in the database (this is the first middleware within the pipeline) that websocket connection disconnects.  

I can just make a controller if it is by design. Thanks for the response.

**Comment by BrennanConroy** [comment]
Is LogRequest serializable? Is there an exception from `Clients.All.SendAsync`? Are there any logs/errors on the client side when it's disconnected?

**Comment by WingZer0123** [comment]
Let me troubleshoot this a little further on my end and get back to you, there was a very non-descriptive error I can reproduce on the client side but no, execution of the call stack continued on the server side I will try again. No rush.

**Comment by WingZer0123** [comment]
![image](https://user-images.githubusercontent.com/114699222/199796549-03a1730a-b543-4572-9bdf-b5e3af948b65.png)
![image](https://user-images.githubusercontent.com/114699222/199796660-2ee5f1a9-8cb5-4456-b353-43ba3257d381.png)
![image](https://user-images.githubusercontent.com/114699222/199796747-654c850d-275c-49e9-a67e-3fe05f3539c8.png)

**Comment by BrennanConroy** [comment]
Any server side logs? Turn on debug at least.

**Comment by WingZer0123** [comment]
Here is a copy of the server logs from application start to a request coming through the pipeline, no expectations are hit and execution continues. Thank you!

`Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.30\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Net.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.30\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\MongoDB.Driver.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\MongoDB.Driver.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\MongoDB.Bson.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\DnsClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Net.NetworkInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\runtimes\win\lib\netstandard2.0\Microsoft.Win32.Registry.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Net.Sockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\MongoDB.Libmongocrypt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Net.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Diagnostics.TextWriterTraceListener.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x2cc4 has exited with code 0 (0x0).
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\runtimes\win\lib\netcoreapp2.1\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x24e4 has exited with code 0 (0x0).
The thread 0x46f0 has exited with code 0 (0x0).
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\Microsoft.IdentityModel.Tokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\BCrypt.Net-Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\Microsoft.IdentityModel.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Code\Encryption-API-Services\NETCore-API\UsersAPI\bin\Debug\netcoreapp3.1\Microsoft.IdentityModel.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.30\System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x5cd0 has exited with code 0 (0x0).
The thread 0x5570 has exited with code 0 (0x0).
The thread 0x1768 has exited with code 0 (0x0).`

**Comment by BrennanConroy** [comment]
Those aren't debug logs, see https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging for details on how to enable logging.

**Comment by WingZer0123** [comment]
`Starting IIS Express ...
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[1]
      Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
Starting IIS Express ...
Successfully registered URL "http://localhost:53775/" for site "UsersAPI" application "/"
Successfully registered URL "https://localhost:44380/" for site "UsersAPI" application "/"
Registration completed for site "UsersAPI"
IIS Express is running.
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[1]
      Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI`

**Comment by BrennanConroy** [comment]
Ok, that's progress, but where is the request?

**Comment by WingZer0123** [comment]
I put the additional settings into appsettings.json, I am not seeing anything related to SignalR or even the HTTP request in general for that matter.

**Comment by BrennanConroy** [comment]
You should change the other logging sections to Debug as well.

**Comment by WingZer0123** [comment]
With everything changed to Debug.

`Registration completed for site "UsersAPI"
IIS Express is running.
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[1]
      Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly UsersAPI
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly Microsoft.WebTools.BrowserLink.Net
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Code\Encryption-API-Services\NETCore-API\UsersAPI
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:44380/api/UserLogin/ application/json 79
dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      Wildcard detected, all requests with hosts will be allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
      No candidates found for the request path '/api/UserLogin/'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
      Request did not match any endpoints`

**Comment by BrennanConroy** [comment]
The SignalR connection isn't showing up, are you running the scenario that isn't working?

Can you provide a minimal repro app as a github project so we can speed up this process?

**Comment by WingZer0123** [comment]
I got it to error out after a reboot and stepping away for a moment. 

`System.Net.Sockets.SocketException (10045): The attempted operation is not supported for the type of object referenced.
   at System.Net.IPAddress.get_Address()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Failed writing message. Aborting connection.

System.Net.Sockets.SocketException (10045): The attempted operation is not supported for the type of object referenced.
   at System.Net.IPAddress.get_Address()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
`

**Comment by WingZer0123** [comment]
Attempting to serialize the object produces this exception.

`{"Error getting value from 'Address' on 'System.Net.IPAddress'."}`

**Comment by BrennanConroy** [comment]
Ok, there's your issue, IPAddress isn't serializable. Either change what you're serializing, or provide a custom IPAddress serializer.

**Comment by WingZer0123** [comment]
I see, is that something that would be included in the serializer built into SignalR once SendCoreAsync

**Comment by BrennanConroy** [comment]
No, this is not something that will be supported in-box. Also, it's not SignalR specific, this is System.Text.Json behavior.

**Comment by WingZer0123** [comment]
I was able to successfully run .\restore.cmd on the entire project, I have 24 errors left to get the entire project running is their any suggestions on this all 24 are related just in different libraries associated with the entire solution. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\Code\dotnet\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.props" was not found. Confirm that the expression in the Import declaration "artifacts\bin\GenerateFiles\Directory.Build.props" is correct, and that the file exists on disk.	Microsoft.AspNetCore.Authorization.Policy	C:\Code\dotnet\aspnetcore\Directory.Build.props	244

**Comment by WingZer0123** [comment]
Was able to get this to function the way that I wanted too by doing by doing some custom checking on the IP address and changing the type within the model to a string. This is no longer an issue for me, I've left the code here for reference. Feel free to close. 
![image](https://user-images.githubusercontent.com/114699222/199861071-67708c0c-1602-4d80-aa49-e743bd6c5ac5.png)
![image](https://user-images.githubusercontent.com/114699222/199861103-20b5bf99-6fd7-47d9-8021-96ecc2f04b4f.png)

**Comment by davidfowl** [comment]
You can also write a [JSON converter](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-6-0) that can handle IPAddresses

**Comment by WingZer0123** [comment]
I have never had the need to write one, will look into it tomorrow. I am in-between an offer and interviewing ATM. :)

**Comment by WingZer0123** [comment]
After reading about the performance hits and the complexity of writing a custom converter for one field that I just needed a string from. I decided to stick with my solution that I came up. I might be using that class that I created, I may extend it to support CIDR blocks as per my project that would be an internal dashboard sitting along side Application Insights.
