### ISSUE TITLE
QuickGrid Sorting - JSON Parsing Error

### ISSUE THREAD

**Issue by BigMac0069** [dotnet/aspnetcore#44851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I'm tried to use the Microsoft.AspNetCore.Components.QuickGrid in my project but i have a trouble with the blazor.server.js.
I always get this error in the navigator : Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON.
And i think it's the reason why the QuickGrid.razor.js is not loaded.
So the sorting of my grid does't work.
Do you know this issue?

Regards,

### Expected Behavior

QuickGrid sorting

### .NET Version

dotnet 6.0

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
