### ISSUE TITLE
Grpc issue in native build of aspnetcore on ppc64le

### ISSUE THREAD

**Issue by Amit-Sirohi** [dotnet/aspnetcore#44859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Tried to do native build of aspnetcore on ppc64le using dotnet 7.0.100-rc.2.22477.23
Get error - 
```
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropClient/InteropClient.csproj]
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64|arm64} to try the closest match to your system. 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropClient/InteropClient.csproj]
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropClient/InteropClient.csproj]
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropWebsite/InteropWebsite.csproj]
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64|arm64} to try the closest match to your system. 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropWebsite/InteropWebsite.csproj]
/home/ubuntu/.nuget/packages/grpc.tools/2.45.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). 
[/home/ubuntu/amit/rc2_dotnet/aspnetcore/src/Grpc/Interop/test/testassets/InteropWebsite/InteropWebsite.csproj] 
```

Is there any way to disable Grpc in native build of aspnetcore on ppc64le ?. 

### Steps To Reproduce

cd aspnetcore
./eng/build.sh 

### .NET Version

7.0.100-rc.2.22477.23

### Anything else?

aspnetcore v7.0.0-rc.2.22476.2

ubuntu@dotnet2--1:~$ dotnet --info
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-ppc64le
 Base Path:   /home/ubuntu/amit/new_rc2_dotnet/output/.dotnet/sdk/7.0.100-rc.2.22477.23/

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: ppc64le
  Commit:       N/A

.NET SDKs installed:
  7.0.100-rc.2.22477.23 [/home/ubuntu/amit/new_rc2_dotnet/output/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/home/ubuntu/amit/new_rc2_dotnet/output/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/home/ubuntu/amit/new_rc2_dotnet/output/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/ubuntu/amit/new_rc2_dotnet/output/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by rafikiassumani-msft** [comment]
Triage: @Amit-Sirohi can you try the workaround in the following issue? https://github.com/grpc/grpc/issues/18428#issuecomment-535041155
