### ISSUE TITLE
SystemTextJsonOutputFormatter calls the serializer with unexpected Type

### ISSUE THREAD

**Issue by akurone** [dotnet/aspnetcore#44852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hi there,
after a short talk with lovely people on runtime team (#dotnet/runtime/issues/77532); i think the issue below needs to be resolved here:
i want to utilize the new [json polymorphism features](dotnet/runtime/issues/63747): 
```csharp
[JsonPolymorphic]
[JsonDerivedType(typeof(TheDerivedType), nameof(TheDerivedType))]
public class TheBaseType { public int Prop1 { get; set; } = 1; }

public class TheDerivedType: TheBaseType { public int Prop2 { get; set; } = 2; }

//and in the controller:
[HttpGet] public TheBaseType A() => new TheDerivedType();
// call to this endpoint produces:
// {"prop2":2,"prop1":1}
```
what i expect to get is:
```console
{"$type":"TheDerivedType","prop2":2,"prop1":1}
```
but as discussed in #41399 [SystemTextJsonOutputFormatter](https://github.com/dotnet/aspnetcore/blob/f9ae0f5d30be2de3c0de61b5673bd8873231d70a/src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs#L73-L77) calls the serializer in a very specific way. this call practically hides all the new metadata from the serializer and produces json without discriminator info. without discriminator, the receiving party fails to deserialize this json.

### Expected Behavior

SystemTextJsonOutputFormatter and other json returning types (like JO result etc.) rendering with STJ should respect the polymorphic serialization metadata provided.

current:
```console
{"prop2":2,"prop1":1}
```
expected:
```console
{"$type":"TheDerivedType","prop2":2,"prop1":1}
```

### Steps To Reproduce

clone the [repo](https://github.com/akurone/STJPolyWebapi/) and make the get reqs below:
- test/a
- test/b

### .NET Version

7.0.100-rc.2.22477.23

**Comment by marcelbarner** [comment]
I have the same problem and I created a repo/package to solve the problem for me.

[Repo: marcelbarner/AspNetCore.Json.SinglePolymorphicResponse](https://github.com/marcelbarner/AspNetCore.Json.SinglePolymorphicResponse)

[Package: AspNetCore.Json.SinglePolymorphicResponse](https://www.nuget.org/packages/AspNetCore.Json.SinglePolymorphicResponse)

**Comment by stephenwelsh** [comment]
In my scenario (bi directional polymorphic events using SignalR with .Net client) it is not possible to specify a base class and normally a custom JsonConverter is used to manually add the type discriminators.
Looking to use the new Net7 support for polymorphic types exposed this differentiated behaviour when in some SignalR calling directions the base type is not known.

After further research I found that duplicating the JsonDerivedType attribute on the corresponding Derived class enables the non generic call to JsonSerializer.Serialize to add the type discriminator.

This restriction and work around may be worth adding to the [Serialize properties of derived classes](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#serialize-properties-of-derived-classes) documentation.

```csharp
var test = new TestA{ Id="123", Name="TestA"}
var nonGenericCall = JsonSerializer.Serialize(test, test.GetType());
var genericCall = JsonSerializer.Serialize<TestBase>(test);

[JsonDerivedType(typeof(TestBase), typeDiscriminator: nameof(TestBase))]
[JsonDerivedType(typeof(TestA), typeDiscriminator: nameof(TestA))]
public class TestBase
{
    public string Id { get; set; }
}
[JsonDerivedType(typeof(TestA), typeDiscriminator: nameof(TestA))]
public class TestA : TestBase
{
    public string Name { get; set; }
}
```

I now get the desired output as follows:

nonGenericCall = "{"id"="123", "name"="TestA", $type="TestA"}"
genericCall = "{"id"="123", "name"="TestA", $type="TestA"}"

**Comment by brunolins16** [comment]
> This restriction and work around may be worth adding to the [Serialize properties of derived classes](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#serialize-properties-of-derived-classes) documentation.

cc @dotnet/area-system-text-json

**Comment by eiriktsarpalis** [comment]
> > After further research I found that duplicating the JsonDerivedType attribute on the corresponding Derived class enables the non generic call to JsonSerializer.Serialize to add the type discriminator.
> >
> > This restriction and work around may be worth adding to the [Serialize properties of derived classes](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#serialize-properties-of-derived-classes) documentation.
> 
> cc @dotnet/area-system-text-json

I don't think this will be necessary once #46008 has been merged, no?

**Comment by brunolins16** [comment]
> I don't think this will be necessary once #46008 has been merged, no?

Exactly, we are adding additional code to fix this behavior in ASP.NET Core. However, I believe the question is about how the Serializer polymorphism work in general, @stephenwelsh is that right?

**Comment by eiriktsarpalis** [comment]
I see. @stephenwelsh you might want to check https://github.com/dotnet/runtime/issues/77532 which tracks this issue in the STJ repo, in particular I've included a [workaround](https://github.com/dotnet/runtime/issues/77532#issuecomment-1300541631) that lets you achieve the semantics you desire without the need to duplicate any annotations.
