### ISSUE TITLE
A question about closures and render fragments.

### ISSUE THREAD

**Issue by En3Tho** [dotnet/aspnetcore#44867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to poke around blazor and I'm curious how RenderFragment's delegate/closure mechanics work:
``` razor
<div>
    @RenderRadio();
</div>

@code {

    private RenderFragment RenderRadio()
    {
        var isChecked = false;
        void Check()
        {
            isChecked = !isChecked;
        }

        return @<label>
                   <input type="radio" class="peer absolute w-0 h-0" @onclick="Check"/>
                   <span class="w-4 h-4 inline-block bg-white border-black border border-solid rounded-[50%]
                                @If(isChecked, "border-red-900 border-[5px]")">
                   </span>
               </label>;
    }
}
```

Even though in debug isChecked is mutated to true/false, markup is never updated. Is this because component get's rerendered and RenderRadio() get's called again?

I'm curious what is the way to kind of create a markup from render fragment and just "let it live".
For example, this works in React via hooks like useState. I'm wondering if I can do this in Blazor too.

Caching RenderFragment in a field works (component gets updated), but to me personally this is not really ideal.
``` razor
<div>
    @SingleRadioCachedInField
</div>

@code {

    private RenderFragment SingleRadioCachedInField = null!;

    protected override void OnParametersSet()
    {
        SingleRadioCachedInField = RenderRadio();
    }

    private RenderFragment RenderRadio()
    {
        var isChecked = false;
        void Check()
        {
            isChecked = !isChecked;
        }

        return @<label>
                   <input type="radio" class="peer absolute w-0 h-0" @onclick="Check"/>
                   <span class="w-4 h-4 inline-block bg-white border-black border border-solid rounded-[50%]
                                @If(isChecked, "border-red-900 border-[5px]")">
                   </span>
               </label>;
    }
}
```

Moving this code to real component works too.

What didn't work: 
``` razor
<div>
    @RenderRadio()
    @RenderRadio()
</div>

@code {

    private RenderFragment RenderRadio()
    {
        return @<label>
                   @code {
                       bool isChecked = false;
                       void Check()
                       {
                           isChecked = !isChecked;
                       }
                   }
                   <input type="radio" class="peer absolute w-0 h-0" @onclick="Check"/>
                   <span class="w-4 h-4 inline-block bg-white border-black border border-solid rounded-[50%]
                            @If(isChecked, "border-red-900 border-[5px]")">
                   </span>
               </label>;
    }
}
```

This just reuses fields from parent component so isn't really useful

### Describe the solution you'd like

I'd like to understand if I can use closures to create an inline micro components that persist state (like full fledged components) instead of creating new classes.

Maybe a some kind of trick can be used like a custom component + custom delegate combo or something like that?

**Comment by En3Tho** [comment]
I guess I can rephase it like "can there be functional components"?

Like smaller ones within one file. Sometimes  you really don't want to have bunch of files with super small stuff inside.

**Comment by TanayParikh** [comment]
Two things of note here would be you aren't calling `StateHasChanged`, and you'd be creating a new closure on every re-render. We aren't sure if what you're trying to achieve here would directly work. You'd have to dig deeper into closure mechanics in C# to come up with a solution.
