### ISSUE TITLE
Error handling from non-Blazor events (e.g. Timer)

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/aspnetcore#44871]
### Is your feature request related to a problem? Please describe the problem.

There seems to be no way to invoke non-Blazor event handlers with Blazor error handling. Let's say I have an ErrorBoundary wrapping some component. This component uses System.Timers.Timer class to refresh the data once a certain period. It uses InvokeAsync method (as suggested [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#invoke-component-methods-externally-to-update-state)). The problem, however, is that all the errors happening within those event handlers are not handled neither by ErrorBoundary, nor by Blazor's Renderer in general. The exception is simply lost, not even logged anywhere.

You can take a look this this sample project https://github.com/Dreamescaper/BlazorRepro44871. It has two buttons. The first one throws an exception after awating a delay (it is handled by ErrorBoudary successfully). Second one throws Exceptions in Timer's events (exceptions are ignored).

![chrome_z8wiiaTFS9](https://user-images.githubusercontent.com/17177729/199859659-21df7f3c-1c33-43e5-9a5b-85c7054713ac.gif)

### Describe the solution you'd like

Ideally, ComponentBase.InvokeAsync method should handle exceptions, and push them through Blazor's error pipeline (probably catch the exception and pass it to Renderer.HandleExceptionViaErrorBoundary  method).

If that's an unacceptable breaking change, a separate method or method overload should be added to handle this case.

The other option would be to make a public method on Renderer to handle the exception (similar to HandleExceptionViaErrorBoundary) so the user would be able to invoke it manually.

### Additional context

This issue is quite similar to this closed item https://github.com/dotnet/aspnetcore/issues/27716, but with additional use case regarding ErrorBoundary.

**Comment by SteveSandersonMS** [comment]
Thanks! I've filed https://github.com/dotnet/aspnetcore/issues/27716 to track this. I agree we should create a suitable API for this.

Closing in favour of #27716
