### ISSUE TITLE
Kestrel: Connection id "XXX" application never completed.

### ISSUE THREAD

**Issue by somaraj** [dotnet/aspnetcore#44870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting this error very often not even able to debug, it's crashing the application
Framework .Net 6

### Exceptions (if any)

Microsoft.AspNetCore.Server.Kestrel[23] Connection id "0HMLT85PF7Q92" application never completed.

### .NET Version

6.0.400

**Comment by davidfowl** [comment]
What does your application do?

**Comment by Tratcher** [comment]
This happens if you write middleware or endpoints that return a task, never complete it, and then get GC'd. You'll need to audit your returned tasks.

**Comment by somaraj** [comment]
I am using generic repository pattern approach with async/await. Posting the screenshots of sample action & service which is implemented. Please let me know if more details required..

**Controller**

![image](https://user-images.githubusercontent.com/17797942/199921063-810e1f08-b86a-4262-be2a-e73d819a851d.png)

**Service Layer**

![image](https://user-images.githubusercontent.com/17797942/199921128-d72743ee-bda9-49ee-9b57-5d4a6e7e2dfa.png)

**Comment by davidfowl** [comment]
@somaraj it's hard to tell from this code where the issue might be. If you can reproduce the problem locally, remove pieces of the code until you no longer see that log to narrow down where it might be coming from.

**Comment by somaraj** [comment]
I have already tried removing all possible piece of code but no luck. the crash this is totally random! this is what I am getting in VS

![image](https://user-images.githubusercontent.com/17797942/200187071-d5298048-effe-4b52-92c5-d2acb26735f3.png)

**Comment by davidfowl** [comment]
@somaraj you're going to have to do things the hard way then. Load the symbols and see where the null reference exception is coming from.

Another tool you might use to debug (if you can reproduce this locally) is "parallel stacks". That will show hanging tasks that may not be associated with a thread.
