### ISSUE TITLE
regular problems of MapFallbackToFile method for help

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44881]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/regular-problems-of-MapFallbackToFile-me/10185719)._

---
Previously, we had a SPA program module in wwwroot with the folder name of react001. According to the prompts in the official document, we made the following processing in the program to be compatible with the HISOTRY mode of SAP:

app.MapFallbackToFile($"react001/{*path:nonfile}", "react001/index.html");

With the increase of demand, there are more and more SPA program modules in wwwroot. We have to add similar processing for each SPA folder:

app.MapFallbackToFile("react001/{*path:nonfile}","react001/index.html");

app. MapFallbackToFile("react002/{*path:nonfile}", "react002/index.html");

app. MapFallbackToFile("react003/{*path:nonfile}", $"react003/index.html");

...

This leads to code changes and website publishing every time SPA modules are added. Is there a generic route? I need help.

---
#### Feedback Bot on 10/31/2022, 01:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

You can use `MapFallback` instead to more flexibly map your app to the target file. You can see the implementation of MapFallbackToFile [here](https://github.com/dotnet/aspnetcore/blob/991728c729ab6d67e1eb1b5de4329d116b5a83bb/src/Middleware/StaticFiles/src/StaticFilesEndpointRouteBuilderExtensions.cs#L165) which uses MapFallback under the hood. It should be reasonable for you to adapt it to suit your needs.
