### ISSUE TITLE
Blazor - Binding Blazor Component or workaround [ask from WPF guy]

### ISSUE THREAD

**Issue by DOWSCZ** [dotnet/aspnetcore#44897]
I am looking for something like this in the WPF for Blazor, if is it possible:

```  
 <ContentPresenter Content="{Binding LicensesText}" />
```

```
    public LicensesText LicensesText { get; set; }

    ctor()
    {
        LicensesText licensesText = new LicensesText();
        licensesText.ClickedShowComparision += () => { Licenses = new Licences(); };
        LicensesText = licensesText;

        //Sleep for 5 seconds
        List<LicensesText> list = new ();
        list.Add(licensesText);

        LicensesText licensesText1 = new LicensesText();
        licensesText1.ClickedShowComparision += () => { Licenses = new Licences(); };
        LicensesText = licensesText1;

        //Sleep for 5 seconds
        LicensesText = list.First();}
    }
```

The Best would be something like this:

SaySomething.razor
```

    <h3>@Label</h3>
    
    
    @code {
    
        public string Label { get; set; } = "Default Label";
    
        public void SetLabel(string label)
        {
            Label = label;
            StateHasChanged();
        }
    }
```

Index.razor

```
    @SaySometing
    
    @code
    {
        public SaySometing SaySometing { get; set; } = new SaySometing();
    }
```

But for sure it doesn't work like it.

I come to some solution but all of them are imperfect. And I dont know how to visualize for example already created ComponentBase element, if is it possible.

 ```
   @page "/"
    
    @DynamicRender
    <SaySometing @ref="SaySometing" />
    <DynamicComponent Type="typeof(SaySometing)" @ref="DynamicComponent"></DynamicComponent>
    
    
    <button @onclick="args => ChangeText(args)">Click Me!</button>
    
    @code
    {
    
    
        public SaySometing SaySometing { get; set; } = new SaySometing();
    
        public SaySometing SaySometing1 { get; set; } = new SaySometing();
    
        public DynamicComponent DynamicComponent { get; set; } = new DynamicComponent();
    
        private RenderFragment DynamicRender { get; set; }
    
    
        protected override Task OnInitializedAsync()
        {
    
            DynamicRender = CreateComponent();
            
            return base.OnInitializedAsync();
        }
    
    
        private RenderFragment CreateComponent() => builder =>
        {
            builder.OpenComponent(0, typeof(SaySometing));
            builder.AddComponentReferenceCapture(1, obj =>
            {
                SaySometing1 = (SaySometing) obj;
            });
            builder.CloseComponent();
        };
    
        private void ChangeText(MouseEventArgs args)
        {
            SaySometing.SetLabel("Hello From SaySomething!");
            SaySometing1.SetLabel("Gutten Tag From SaySomething1!");
            ((SaySometing?)DynamicComponent?.Instance)?.SetLabel("Dobrý den from DynamicComponent");
            StateHasChanged();
        }
    
    }
```

All three works properly and switch text to the right SaySomething.Label. But what if i want to change the SaySometing1 to new instance and keep the old instance for later and then again render it? Or how is it solved in the Blazor. As i told, I was the WPF guy and it is a new jungle for me. Or the best workaround in this technology.

**Comment by SteveSandersonMS** [comment]
@DOWSCZ It looks like you might only just be getting started with Blazor and might find it productive to work through some tutorials to get more of a sense of how things fit together. For example, consider working through [the Blazing Pizza workshop](https://github.com/dotnet-presentations/blazor-workshop). It will take a day or two but then this will be a lot clearer, especially if you can disregard how things worked in WPF.

In the code sample you've provided, your `SaySomething.razor` component should use a parameter, e.g., called `Message`, and then it should be rendered as `<SaySomething Message="@someMessage" />`. Then it will update automatically. This will hopefully start to feel quite natural once you've worked through a tutorial or two. Best of luck :)

**Comment by DOWSCZ** [comment]
Hi Steve, first of all I want to thank you for your great work for .Net. But unfortunately you didn't answer my question at all. My question was if there is something like ContentPresenter in WPF where we can bind the whole instance in case of WPF Page based class in case of Blazor ComponentBase based class. I'm on mobile but I'll try to approximate it with code. 

RazorParent.razor:
. 
. 
<DoesExistComponentLikeThis Content="@RazChild" />
...
Button what calls DisplayRazChild() 
... 
RazorParent.razor@code:

RazorChildren RazChild {get;set;} = null;

void DisplayRazChild() 
{
      RazorChildren razChild = new RazorChildren();
      RazChild = razChild;
      StateHasChanged();
} 

I know I can create RazorChildren in RazorParent.razor and pass parameters there, there are classes like renderfragment or dynamiccomponent. But I haven't figured out how to achieve the example above, or at least get close to it. 


Thanks a lot.

**Comment by SteveSandersonMS** [comment]
Sorry @DOWSCZ, I don't understand at all what you're trying to do. It looks like you're not following the Blazor programming model (for example, trying to `new` a component is not the way it works). I'd definitely still recommend going through Blazor tutorials if you haven't already done so. Alternatively you might get better answers from StackOverflow as that's intended as a place for usage questions.
