### ISSUE TITLE
Web.config property not working with iOS 16.0+

### ISSUE THREAD

**Issue by axenteoctavian** [dotnet/aspnetcore#44908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I implemented a Blazor WASM Hosted app and I need POST/PUT to my API. 
I'm using the code below in web.config file (this is what I found so the POST/PUT will working)
```
<modules runAllManagedModulesForAllRequests="true">
  <remove name="WebDAVModule" />
</modules>
```

But with this the website is not loading on iOS mobile devices with iOS version 16.0+. The website is loading on two iOS mobile devices with iOS version 15.X.

Can you help me please with this issue? Are there other setting so I can enable the POST/PUT operations without modifying the web.config file?

Thank you!

### .NET Version

6.0

**Comment by axenteoctavian** [comment]
Also I found out that for some Android users the website is not loading.

Also I'm sometimes getting this error when I'm loading the website: _Failed to find a valid digest in the 'integrity' attribute for resource 'https://remarkable.tools/_framework/dotnet.6.0.10.vqr4q5ensf.js' with computed SHA-256 integrity '4W91HI4pZ7hzjLoBhPzxdWM7VhQhQuyjDv//v8RWe48='. The resource has been blocked._

And I fresh install Brave and enter the website and got the error above. So I'm guessing this is the error users get and the website is not working for them.
Any solution for the error above, please? :D

**Comment by davidfowl** [comment]
There's a bunch of environmental information missing. What operating system? It seems like you are hosting on IIS as well. There's no code so its unclear if your application is a problem or if it's just your server setup. Try deploying a new project without *any* modifications to the same server and see if it also has problems.

**Comment by axenteoctavian** [comment]
@davidfowl thank you for your response. I deployed the Bazor wasm hosted fresh template to server and the error is still there.

**Comment by javiercn** [comment]
@axenteoctavian can you detail the exact steps that you took to deploy the app as well as the IIS config?

Can you open the Safari dev tools and collect any logs in the console?

**Comment by axenteoctavian** [comment]
Thank you for your response @javiercn.

I was remote debugging my Android phone and also saw the error above about integrity of files.

I believe the error is because of Cloudflare caching services. So I stopped the caching totally and now it seems it's working on all devices.
