### ISSUE TITLE
Blazor Webassembly is broken out of the box

### ISSUE THREAD

**Issue by calnastic0** [dotnet/aspnetcore#44902]
Not sure if this is the right place to ask.

This afternoon I have reset my computer 3 times and it doesn't seem to resolve the problem. 

Basically, on a freshly reset windows 10 computer, Visual Studio 2022 (17.3.6) was installed, along with required runtime environment (.Net 6 etc.). 

Then created a asp.net core hosted blazor webassembly solution. The wasm client code is broken right away:

![image](https://user-images.githubusercontent.com/58486299/200147396-a696230a-9dcd-4e91-8844-ffe3d3de0bb4.png)

Been researching this problem for 2 days and reset the computer 3 times. Can't resolve it.

Any help is appreciated.

**Comment by TanayParikh** [comment]
To confirm, do you have the ASP.NET Core VS workload installed?

Does this work on the command line with dotnet build?

**Comment by calnastic0** [comment]
> To confirm, do you have the ASP.NET Core VS workload installed?
> 
> Does this work on the command line with dotnet build?

I had "ASP.NET and web development" box checked on the VS installer workloads section. It installs several components.

dotnet build didn't work either.

Early this week I found .net 6.0.11 was available. So I upgraded several nuget packages. And in the meantime I manually deleted nuget folders, also deleted obj and bin folders in both server and client projects. It eventually worked. I don't know which step was the key.

The nuget folders I cleared are:
- C:\Users\user\\.nuget\packages
- C:\Program Files (x86)\Microsoft SDKs\NuGetPackages

But I still intermittently ran into sevaral implicit errors such as this one:
`Error	MSB4018	The "GenerateBlazorWebAssemblyBootJson" task failed unexpectedly.
System.BadImageFormatException: Could not load file or assembly 'MyApp.WASM.Client.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'MyApp.WASM.Client.dll' ---> System.BadImageFormatException: Could not load file or assembly 'MyApp.WASM.Client.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'MyApp.WASM.Client.dll' `

And this one:
`Error NETSDK1032  The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible. `

**Comment by javiercn** [comment]
@calnastic0 thanks for the additional details.

Let's see if we can sort this out. To clean nuget packages we recommend you do
`dotnet nuget locals --clear all` as it knows all the locations for potential caches

Then, for your project, remove all the `bin` and `ojb` folders to ensure there is no leftover state.

run `dotnet --info` to make sure that you have the right versions on the path.
You can use a global.json to enforce a specific runtime version. The latest .NET SDK available is 6.0.404

Then first try do to a `dotnet restore --verbose` from the command line and see if that succeeds.

If it does not, check from your project root all the way to your drive, folder if there is a `nuget.config` that might be causing the packages not to be correctly restored.

**Comment by calnastic0** [comment]
> @calnastic0 thanks for the additional details.
> 
> Let's see if we can sort this out. To clean nuget packages we recommend you do `dotnet nuget locals --clear all` as it knows all the locations for potential caches
> 
> Then, for your project, remove all the `bin` and `ojb` folders to ensure there is no leftover state.
> 
> run `dotnet --info` to make sure that you have the right versions on the path. You can use a global.json to enforce a specific runtime version. The latest .NET SDK available is 6.0.404
> 
> Then first try do to a `dotnet restore --verbose` from the command line and see if that succeeds.
> 
> If it does not, check from your project root all the way to your drive, folder if there is a `nuget.config` that might be causing the packages not to be correctly restored.
> 
> Nuget should list all the nuget config files it is using.
> 
> If restoring from the command line works, then try to build next with dotnet build.

Thank you, I appreciate all the information. I have taken note and will try it if some errors occur again.

**Comment by TanayParikh** [comment]
> I have taken note and will try it if some errors occur again.

@calnastic0 does that mean your issue is resolved for now? If so, will close out this issue.
