### ISSUE TITLE
Accessing `CascadingValue` from component rendered inside `SectionOutlet`

### ISSUE THREAD

**Issue by alfattack** [dotnet/aspnetcore#44912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to access a `CascadingValue` from inside a component that has been rendered in a `SectionOutlet`. This component is unable to access this value unless it's cascaded inside the `SectionContent`.

### Describe the solution you'd like

If `SectionContent` could be supplied the same cascading parameters which were available to whatever rendered it.

### Additional context

Here is an example to show this behaviour. This specific sample is a bit superfluous but it demonstrates the sort of issues we have come accross while using our own section implementation (which is heavily inspired by [blazor's internal section components](https://github.com/dotnet/aspnetcore/tree/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/Components/src/Sections))

`MainLayout.razor`

``` razor
@inherits LayoutComponentBase

<CascadingValue Value="siteMetaData">
    <div class="page">
        <main>
            <article class="content px-4">
                @Body
            </article>
        </main>
    </div>
</CascadingValue>

@code {
    public class SiteMetaData
    {
        public string? Organisation { get; set; }
    }

    private SiteMetaData siteMetaData = new SiteMetaData
    {
        Organisation = "Company A"
    };
}
```

`Index.razor`

``` razor
@page "/"

<PageTitle>
    <!-- This won't be able to access the cascaded value from layout !-->
    <MyPageTitle Title="Dashboard"></MyPageTitle>
</PageTitle>

<h1><MyPageTitle Title="Dashboard" /></h1>
```

`MyPageTitle.razor`
``` razor
@using static HeadContentCascadingValue.Shared.MainLayout
@MetaData?.Organisation - @Title

@code {
    [Parameter] public string Title { get; set; }

    [CascadingParameter] public SiteMetaData MetaData { get; set; }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The `PageTitle` component is not being rendered in the body of the HTML document, so the Cascading value is not available to anything rendered within it. In other words, the behavior with Cascading parameters is by-design in this particular case.
What you can do in this particular case, is utilize a new scoped service registered in the DI, which will expose the property you're interested in and inject it into the component wherever you need it.
