### ISSUE TITLE
Blazor server .net template not work on ios safari

### ISSUE THREAD

**Issue by HSHUNION** [dotnet/aspnetcore#44914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I just create a blazor server-side project from the vs 2022 blazor server template. I add nearly no codes.

And then I published it on my win-x64 server( win server 2019) by IIS.

All computers browsers are ok(I just tested the counter page.)
but when I open the website with safari on 2 IPADs (IOS 11.3  and IOS 15.7)
the default counter doesn't work.

it seems that nothing triggered.

What should I do in order to make the project work on safari?

many thanks.

### Expected Behavior

What should I do in order to make the project work on safari?

### Steps To Reproduce

just create new blazor server template project with vs 2022 and then publish with IIS.

### .NET Version

NET6

**Comment by javiercn** [comment]
@HSHUNION thanks for contacting us.

Can you check the logs on the server/browser to see if anything is mentioned there? does it work with other browsers?
