### ISSUE TITLE
GeneratePackageOnBuild with TypeScript throws error

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/aspnetcore#44911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Creating a razor class library with `GeneratePackageOnBuild` enabled as well as TypeScript will cause ` Two assets found targeting the same path with incompatible asset kinds` error on all subsequent executions of `dotnet build`.

There was a previous issue #42110 that discussed the assets not being included in the resulting nuget, but this is about the error that occurs on dotnet build on subsequent attempts.

### Expected Behavior

no error when building project

### Steps To Reproduce

I have created simple repo to reproduce along with detailed reproduction steps here.
https://github.com/StevenTCramer/typescript-nuget-bug

### Exceptions (if any)

 Two assets found targeting the same path with incompatible asset kinds

### .NET Version

6.0.402

### Anything else?

https://github.com/StevenTCramer/typescript-nuget-bug

**Comment by javiercn** [comment]
@StevenTCramer thanks for contacting us.

https://github.com/StevenTCramer/typescript-nuget-bug/blob/main/Bug/Bug.csproj#L8

You are placing your outputs in a location considered for inputs. what happens is:
* First time you build there are no outputs, so it works.
* Second time you build: Your output from the previous build is present in the wwwroot, so it is considered an input.
* Your typescript file builds and adds the built file as content
* The content got added twice hence why you see the error.

You can remove the content with `<Content Remove="wwwroot\hello.js" />` and that should get rid of the issue.

**Comment by StevenTCramer** [comment]
@javiercn  Thanks for taking the time to assist.

I have tried 

`<Content Remove="wwwroot\hello.js" />`

and also

`<TypeScriptCompile Remove="wwwroot\hello.js" />`

neither of which work.

I added video here.

https://www.youtube.com/watch?v=b8sREZNo7NQ

**Comment by javiercn** [comment]
@StevenTCramer I downloaded the project into a container and changed the csproj file.

The problem is as I mentioned that the build outputs from typescript are placed on the same location as other inputs, so on successive builds there is a duplication between the existing content items and the ones that typescript adds.

Adding the following code to the project avoids that problem:

```csharp
  <ItemGroup>
    <Content Remove="wwwroot\hello.*" />
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/6995051/200643473-6210ba0a-067f-4de9-ba18-b20962468986.png)

**Comment by StevenTCramer** [comment]
Wow `<Content Remove="wwwroot\hello.*" />` does work and yet `<Content Remove="wwwroot\hello.js" />` this didn't.  

Oh I guess, had I read the error, I would have seen it complaining about the `js.map` sorry.

Thanks much!
