### ISSUE TITLE
API for dispatching to renderer sync context and capturing exceptions

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#44920]
Currently if you have an exception that occurs off the Blazor sync context, there isn't a good way to marshal it onto the sync context. In our internal code we've sometimes do a weird trick of performing a fake render that throws.

We should have some new API that's like `InvokeAsync` but instead of returning a `Task`, it returns `void` and handles any errors by dispatching them to the renderer. Maybe it could be called `Dispatch` or similar.

Note that it somehow needs to execute in the context of a particular component, so the error can hit the right error boundary. Ideally it would *not* be possible to pretend to be some other component - maybe it should rely on having access to a particular component's `RenderHandle`.

**Comment by SteveSandersonMS** [comment]
Example use cases:

 * https://github.com/dotnet/aspnetcore/issues/44871
 * https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L266

**Comment by SteveSandersonMS** [comment]
Previous incarnation of this request: https://github.com/dotnet/aspnetcore/issues/27716

**Comment by Dreamescaper** [comment]
Why non-async though? Why not Task?

**Comment by SteveSandersonMS** [comment]
> I am not 100% sure how the Task -> void conversion works as I think they are separate concerns.

No conversion. I was just proposing some way to run code (which may be async, but not value-returning) within the context of a component. The reason for returning `void` is because the framework would be handling any exceptions.

Your more constrained proposal of `DispatchError` might be better. We'd need to think through if there are any legit scenarios where people would want to combine this with `InvokeAsync`, and in that case what sort of usage patterns would make sense and whether it's better to mix `InvokeAsync` and `DispatchError` manually, or whether a single `Dispatch` would be sufficient and easier to use.

> Would it work if we had a DispatchError function on ComponentBase/RenderHandle?

Yeah, pretty sure it would end up being *some* function on `RenderHandle` that also gets wrapped by `ComponentBase`.

**Comment by Nick-Stanton** [comment]
@javiercn @SteveSandersonMS while looking into this I think it makes sense to have this in `RenderHandle` even though there isn't any existing invocation logic there (just access to the `Dispatcher`). This way, `_renderer.HandleExceptionViaErrorBoundary()` could be leveraged and its call from `ComponentBase` follows the inline style with the asynchronous invocations. What are your thoughts on this?

**Comment by SteveSandersonMS** [comment]
> while looking into this I think it makes sense to have this in RenderHandle

Sounds about right.

> EDIT: There isn't correct access for _renderer.HandleExceptionViaErrorBoundary() from the RenderHandle

It looks like we could add an `internal` method on `Renderer` like:

```
internal void HandleComponentException(Exception exception, int componentId)
    => HandleExceptionViaErrorBoundary(exception, GetRequiredComponentState(componentId));
```

... and call that from the `RenderHandle`, though I haven't actually tried this to verify.

**Comment by javiercn** [comment]
This sounds reasonable.

We might want to put the functionality in the RenderHandle (which internally delegates to the renderer) and expose a helper method on ComponentBase to let people easily raise them.

**Comment by Nick-Stanton** [comment]
Using @SteveSandersonMS's internal method, I get this code block in `RenderHandle`:

```cs
    public void Dispatch (Action workItem)
    {
        if (_renderer == null)
        {
            ThrowNotInitialized();
        }

        try
        {
            Dispatcher.InvokeAsync(workItem);
        }
        catch (Exception e)
        {
            _renderer.HandleComponentException(e, _componentId);
        }
    }
```

Am I understanding the ask correctly?

**Comment by Nick-Stanton** [comment]
> The code that people want to dispatch might itself be async, so the parameter type needs to be `Func<Task>`.

For sure, I think that similar to how `InvokeAsync` is used in `ComponentBase`, it would be good to have an `Action` and `Func<Task>` overload.

I'm torn but think the second approach may be better since the result still comes back. Is there a way you're leaning with this?

**Comment by SteveSandersonMS** [comment]
Yes, I would lean towards the second (`DispatchExceptionAsync`) approach.

**Comment by Nick-Stanton** [comment]
> `return Dispatcher.InvokeAsync(() => _renderer.HandleComponentException(e, _componentId));`

Hmm, this lambda expression throws [CS1673](https://learn.microsoft.com/dotnet/csharp/misc/cs1673). Do you know a workaround to this?

**Comment by javiercn** [comment]
@Nick-Stanton copy the _renderer into a local variable.
