### ISSUE TITLE
No cleanup of rootcomponent

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#44928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/issues/20855 clearly says it is supported to have multiple rootcomponents.

There is however no clear way to remove a rootcomponent.

Removing the parent DOM element works as expected, except the blazor runtime is actually still running, which may cause race conditions, such as the one described here: https://www.telerik.com/account/support-center/view-ticket/1586114

[BlazorApp3.zip](https://github.com/dotnet/aspnetcore/files/9957296/BlazorApp3.zip)

Also, making the page IDisposable does not trigger, even after removing the parent DOM element, which I assume is resulting in a memory leak.

Please add `async Blazor.rootComponents.remove(DOMElement)` to get a cleanup point that can be called when expecting to remove a domelement that contains a blazor rootcomponent.

### Expected Behavior

No race condition.
No memory leaks.
Blazor component stopped/disposed when parent element removed from DOM.

### Steps To Reproduce

See repro attached

### .NET Version

7rc2

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

If you render the root components statically, they can't be removed. You have to render dynamically using the JSRootComponents feature.

**Comment by javiercn** [comment]
@davhdavh I have filed a separate issue to track improvements in this area https://github.com/dotnet/aspnetcore/issues/44937

In the mean time, this is the approach you can take: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#render-razor-components-from-javascript

**Comment by davhdavh** [comment]
Yes. That is exactly what i do in the repro i attached

**Comment by davhdavh** [comment]
Completed?

**Comment by javiercn** [comment]
@davhdavh I misunderstood your issue.

`await window.Blazor.rootComponents.add(newDiv, 'blazor-grid', params)`

`rootComponents.add` returns an instance of the component. you can call `dispose` on it to release it.

**Comment by javiercn** [comment]
@guardrex can you improve the sample here? It is misleading and can result in confusions like the one @davhdavh ran into.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#render-razor-components-from-javascript

We should include information about how to pass new parameters to the component as well as how to destroy the components.

**Comment by davhdavh** [comment]
Very happy this was just a documentation problem :D Thanks
