### ISSUE TITLE
Blazor JS Interop is bugged in an hard to reproduce scenario.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/aspnetcore#44927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On firefox, my odd setup (vite.js serving blazor and ts files), sometimes trigger an error.
While I have not pinpointed the cause, it trigger a bug here:  

https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L74  

here `document.baseURI` can return an URI with a hash, making the concatenation on the hash instead of the path part of the URI. When importing files, the hash is truncated.
This lead to this:
![image](https://user-images.githubusercontent.com/18743295/200427175-6814e9ab-03e0-4ee4-8e99-3534e116ae98.png)

### Expected Behavior

The concatenation works and this function successfuly import the file.

### Steps To Reproduce

N/A don't know how to reproduce, happens randomly

**Comment by javiercn** [comment]
@Kuinox thanks for contacting us.

How are you getting a hash in the document.baseURI?

**Comment by Kuinox** [comment]
> @Kuinox thanks for contacting us.
> 
> How are you getting a hash in the document.baseURI?

Yes, you can see it in the image, the file script is concatenated to the hash.

**Comment by javiercn** [comment]
@Kuinox I am asking what is your app doing to cause that.

The document base is typically set in the `base` element on the head.

**Comment by Kuinox** [comment]
I'm serving my app with the Vite.js dev server, which is probably the thing causing this behavior.

**Comment by Kuinox** [comment]
Note: I'm no longer using Vite but the regular blazor devserver and the issue happen as soon as I hit the page with an hash. (I use the same mechanism than sharplab to save data in the URL).

**Comment by javiercn** [comment]
@Kuinox thanks for the additional details.

Would you be willing to contribute a change? We would need a clear repro to better understand the scenario, but I am in general supportive of a fix for this.

**Comment by Kuinox** [comment]
I already posted a fix that got merged ^^'.
I was just saying that it is not happening in a particular setup.  

I simply posted more information in case some else had the same issue, since the fix will ship with .NET 8.

**Comment by javiercn** [comment]
@Kuinox lol, that was fast 😄 

Thanks for the contribution.
