### ISSUE TITLE
PersistentComponentState: persist state outside OnPersisting callback

### ISSUE THREAD

**Issue by Bouke** [dotnet/aspnetcore#44936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have various components that I'd like to preserve the state for, but the API provided by PersistentComponentState is cumbersome to work with for some components. These components load some data and display them, and the data (model) doesn't change after initial render. However the API requires me to: implement `IDisposable`, create a subscription with a callback and dispose of this subscription.

```cs
@implements IDisposable
private PersistingComponentStateSubscription persistingSubscription;

protected override async Task OnInitializedAsync()
{
    persistingSubscription = 
        ApplicationState.RegisterOnPersisting(PersistForecasts);

    if (!ApplicationState.TryTakeFromJson<WeatherForecast[]>(
        "fetchdata", out var restored))
    {
        forecasts = 
            await WeatherForecastService.GetForecastAsync(DateTime.Now);
    }
    else
    {
        forecasts = restored!;
    }
}

private Task PersistForecasts()
{
    ApplicationState.PersistAsJson("fetchdata", forecasts);

    return Task.CompletedTask;
}

void IDisposable.Dispose()
{
    persistingSubscription.Dispose();
}
```

### Describe the solution you'd like

The API should allow me to write something like this instead:

```cs
protected override async Task OnInitializedAsync()
{
    if (!ApplicationState.TryTakeFromJson<WeatherForecast[]>(
        "fetchdata", out var restored))
    {
        forecasts = 
            await WeatherForecastService.GetForecastAsync(DateTime.Now);
        ApplicationState.PersistAsJson("fetchdata", forecasts);
    }
    else
    {
        forecasts = restored!;
    }
}
```

This currently fails with the following error:

> InvalidOperationException: Persisting state is only allowed during an OnPersisting callback.

### Additional context

dotnet 6.0.402

**Comment by javiercn** [comment]
@Bouke thanks for contacting us.

This is by design as we are "taking a snapshot" of the current state of the app at a specific point in time. We do not want to have an API where we are forced to hold on to memory for a potentially long time either serialized or non-serialized, which in your case we would need to.

You can extend `ComponentBase` to add the logic required to implement the code to save the state and provide a method that implementors can override to implement the state persistence and use that class in your components.

**Comment by Alerinos** [comment]
@javiercn I have a similar problem.
If we use PersistentComponentState in e.g. index.razor and then we want to create a component e.g. <Hello /> and also create another PersistentComponentState, unfortunately two calls will not work. You can only use this once per page load.
Do you have any solution?

**Comment by javiercn** [comment]
@Alerinos I am not sure I understand what you mean.
