### ISSUE TITLE
Make StaticFileOptions.OnPrepareResponse async

### ISSUE THREAD

**Issue by gdoron** [dotnet/aspnetcore#44932]
## Background and Motivation

I have a use case where I need to add a header to static file based on an async operation.
Currently it's not quite possible with asp.net core, since the OnPrepareResponse is `Action<StaticFileResponseContext>`

## Proposed API
```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.AspNetCore.StaticFiles.Infrastructure;

namespace Microsoft.AspNetCore.Builder;

/// <summary>
/// Options for serving static files
/// </summary>
public class StaticFileOptions : SharedOptionsBase
{
    internal static readonly Action<StaticFileResponseContext> _defaultOnPrepareResponse = _ => { };
    internal static readonly Action<StaticFileResponseContext> _defaultOnPrepareResponseAsync = _ => Task.CompletedTask;

    /// <summary>
    /// Defaults to all request paths
    /// </summary>
    /// <param name="sharedOptions"></param>
    public StaticFileOptions(SharedOptions sharedOptions) : base(sharedOptions)
    {
        OnPrepareResponse = _defaultOnPrepareResponse;
        OnPrepareResponseAsync = _defaultOnPrepareResponseAsync;
    }

    public Action<StaticFileResponseContext> OnPrepareResponse { get; set; }
    public Func<StaticFileResponseContext, Task> OnPrepareResponseAsync { get; set; }
}

```
And in `Microsoft.AspNetCore.StaticFiles.StaticFileContext`, change `ApplyResponseHeaders` to async:

```cs
public async Task ApplyResponseHeadersAsync(int statusCode)
{
    if (_options.OnPrepareResponse != StaticFileOptions._defaultOnPrepareResponse)
    {
        _options.OnPrepareResponse(new StaticFileResponseContext(_context, _fileInfo));
    }

    if (_options.OnPrepareResponseAsync != StaticFileOptions._defaultOnPrepareResponseAsync)
    {
        await _options.OnPrepareResponseAsync(new StaticFileResponseContext(_context, _fileInfo));
    }
}
```

### Additional context

I'll gladly do the work myself and open a PR if you think it's a good proposal, just hint me how you want to maintain (if needed) backward compatibility. 
Have both `OnPrepareResponse` and `OnPrepareResponseAsync` and call the sync method before the async one? and deprecate it?

Or can we just make that tiny breaking change, and existing code would need to `return Task.CompletedTask`.

**Comment by davidfowl** [comment]
> I have a use case where I need to add a header to static file based on an async operation.

What's the async operation?

> Or can we just make that tiny breaking change, and existing code would need to return Task.CompletedTask.

Nope.

@gdoron can you use the [API Proposal](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=) template?

**Comment by gdoron** [comment]
@davidfowl I've updated the template.

The async operation is going to a different micro service and check who the user and company is that is requesting the specific page.
Where if it's specific page and user\company we'll add a cookie.

**Comment by mitchdenny** [comment]
What you could do in this particular case is use ```OnPrepareResponse``` in conjunction with some middleware. For example you could add a header to mark the request being a static file, and then in the middleware do your processing (which is an async function). It isn't elegant but it would work.

**Comment by gdoron** [comment]
@mitchdenny It believe it's not possible here:

```cs
        var staticFilesOptions = new StaticFileOptions {
            OnPrepareResponse = context => {
                // ...
            }
        };
        
        app.UseDefaultFiles();
        app.UseStaticFiles(staticFilesOptions);

        app.UseEndpoints(endpoints => {
            endpoints.MapDefaultControllerRoute();
            endpoints.MapFallbackToFile("index.html", staticFilesOptions);
        });
```

Only this seem to know it's going to handle a static files (index.html):
`endpoints.MapFallbackToFile("index.html", staticFilesOptions);`

**Comment by Tratcher** [comment]
Workaround:
In OnPrepareResponse register a callback with HttpResponse.OnStarting which will execute async and allow you to modify headers.
https://github.com/dotnet/aspnetcore/blob/4c300ec6db7117a05b7c79cf6f617e9d498212b6/src/Http/Http.Abstractions/src/HttpResponse.cs#L98

**Comment by gdoron** [comment]
@Tratcher do you have a short example, I'm not sure I understand what you suggested.
Thanks!

**Comment by Tratcher** [comment]
```C#
using Microsoft.AspNetCore.StaticFiles;

var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<StaticFileOptions>(o =>
{
    o.OnPrepareResponse = c =>
    {
        c.Context.Response.OnStarting(async state =>
        {
            var staticFileContext = state as StaticFileResponseContext;
            await MyAsyncCheck(staticFileContext);
        }, c);
    };
});

Task MyAsyncCheck(StaticFileResponseContext staticFileContext)
{
    throw new NotImplementedException();
}
```

**Comment by davidfowl** [comment]
We should investigate adding this API. That seems a little convoluted. It's a fine workaround though.

**Comment by gdoron** [comment]
@davidfowl LMK if you want me to contribute the API.
Should be really easy.

**Comment by halter73** [comment]
API Review Notes:

1. Do we like events? No. 😆 
2. How about a method to taking the func that returns an IDisposable? Too complicated.
3. Do we want to back both `OnPrepareResponse` and `OnPrepareResponseAsync` with the same field? Maybe if we would obsolete one, but we're not. While it'd be weird to set both, it's arguably weirder to have one overwrite the other.

API Approved!

```diff
namespace Microsoft.AspNetCore.Builder;

public class StaticFileOptions : SharedOptionsBase
{
    public Action<StaticFileResponseContext> OnPrepareResponse { get; set; }
+    public Func<StaticFileResponseContext, Task> OnPrepareResponseAsync { get; set; }
}

**Comment by davidfowl** [comment]
> Do we want to back both OnPrepareResponse and OnPrepareResponseAsync with the same field? Maybe if we would obsolete one, but we're not. While it'd be weird to set both, it's arguably weirder to have one overwrite the other.

What's the behavior if both are set? They both run right?

**Comment by Tratcher** [comment]
Yes, the first the sync one and then the async one.

**Comment by Tratcher** [comment]
@gdoron yes please work on this when you're ready.

To limit allocations of the context, how about this:
```
public Task ApplyResponseHeadersAsync(int statusCode)
{
    if (_options.OnPrepareResponse != StaticFileOptions._defaultOnPrepareResponse
       || _options.OnPrepareResponseAsync != StaticFileOptions._defaultOnPrepareResponseAsync)
    {
        var context = new StaticFileResponseContext(_context, _fileInfo);
        _options.OnPrepareResponse(context);
        return _options.OnPrepareResponseAsync(context);
    }
    return Task.CompletedTask;
}
```

**Comment by davidfowl** [comment]
Reducing allocations, makes me so happy 😄

**Comment by mitchdenny** [comment]
> 3. Do we want to back both `OnPrepareResponse` and `OnPrepareResponseAsync` with the same field? Maybe if we would obsolete one, but we're not. While it'd be weird to set both, it's arguably weirder to have one overwrite the other.

What if we obsoleted OnPrepareResponse but didn't share the same backing field. My thinking is that you've got two properties which allow you to do the same thing, but the only difference is the synchronicity. Over time wouldn't it be better to push people towards using the async version so that you could deprecate the old one down the line?

**Comment by Kahbazi** [comment]
> Yes, first the sync one and then the async one.

@Tratcher How about only calling the async one and the default value for `OnPrepareResponseAsync` is a delegate calling `OnPrepareResponse`. I think I saw the same behavior in MVC action filters before.

**Comment by Tratcher** [comment]
@mitchdenny we try to only obsolete things that are strictly worse that the new one, but there's nothing wrong with the sync version in this case. People updating version-to-version don't like being forced to make code changes that don't benefit them.

**Comment by gdoron** [comment]
Sorry for the noob question, but... how do I start developing with asp.net core repo?
I wrote the entire code (minus a UT) with a text editor, because I couldn't even open it with rider or build it with the CLI.

> dotnet restore
/usr/local/share/dotnet/sdk/8.0.100-alpha.1.22570.9/NuGet.targets(399,5): error MSB3202: The project file "/Users/dorongrinzaig/repos/aspnetcore/src/submodules/spa-templates/src/Microsoft.DotNet.Web.Spa.ProjectTemplates.csproj" was not found. [/Users/dorongrinzaig/repos/aspnetcore/AspNetCore.sln]
