### ISSUE TITLE
Visual Studio Application Insights (Visual Studio only) feature not working at all

### ISSUE THREAD

**Issue by filipbekic01** [dotnet/aspnetcore#44938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no way nor workaround to configure Application Insights to collect data from debug session, without Azure.

### Expected Behavior

I want to be able to collect metris from debug session in Visual Studio without Azure account at all.

### Steps To Reproduce

Just initialize the project.

### .NET Version

6.0.100

**Comment by javiercn** [comment]
@filipbekic01 thanks for contacting us.

In order for you to get a better and faster answer we recommend that you file this issue via the Visual studio report a problem: [Report a problem with Visual Studio - Visual Studio (Windows) | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) dialog.

Or at https://github.com/microsoft/ApplicationInsights-dotnet
