### ISSUE TITLE
Invoking AddMvcCore 2x results in a "An item with the same key has already been added. Key: exists"

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/aspnetcore#44945]
```
Autofac.Core.DependencyResolutionException: 'An exception was thrown while activating Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionEndpointDataSourceFactory -> Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory -> Microsoft.AspNetCore.Routing.Patterns.DefaultRoutePatternTransformer -> Microsoft.AspNetCore.Routing.DefaultParameterPolicyFactory.'
```

Looks like this is due to [MvcCoreRouteOptionsSetup](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreRouteOptionsSetup.cs) adding to the dicitonary instead of just setting.

Optionally, we can tweak [MvcCoreServiceCollectionExtensions](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs) to not TryAddEnumerable for MvcCoreRouteOptionsSetup and just TryAdd

This is important for library authors to be able to invoke AddMvcCore to have access to the MvCoreBuilder to add additional services, like Odata, etc.

**Comment by brunolins16** [comment]
@cmeyertons Can you share your repro application? I don't see any issue using the default DI container.
