### ISSUE TITLE
ASP0014: Suggest using top level route registrations

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#44959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following code to register my controller routes:

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
```

But it shows the following warning:

>ASP0014: Suggest using top level route registrations

What does it mean? Is there any other new way of registering the controller routes?

### .NET Version

7.0.0

**Comment by davidfowl** [comment]
```C#
app.MapControllers();
```

**Comment by TanvirArjel** [comment]
@davidfowl Thanks for the quick response!

**Comment by Rick-Anderson** [comment]
> We should really have ad associated code fix for this.
> 
> ```cs
> app.MapControllers();
> ```

@davidfowl @captainsafia  do you want to keep this open?
