### ISSUE TITLE
Request features for request and response byte sizes

### ISSUE THREAD

**Issue by timmydo** [dotnet/aspnetcore#44953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have code that is iterating through all the request headers and trying to calculate the byte size. These sorts of things get logged in metrics/logs.

```
       private static int ReadHeadersSize(NameValueCollection headers)
        {
            int headerSize = 0;
            for (int i = 0; i < headers.Count; i++)
            {
                var key = headers.GetKey(i);
                var val = headers.Get(i);
                var headerKeyLength = !string.IsNullOrEmpty(key) ? key.Length : 0;
                var headerValueLength = !string.IsNullOrEmpty(val) ? val.Length : 0;
                headerSize += ((headerKeyLength + 2) + headerValueLength) + 2;
            }


           return headerSize;
        }
```

The code also will calculate request and response sizes by looking at the content length, etc.
I want to migrate this project to ASP.NET Core. (Let's gloss over how accurate this method is)

### Describe the solution you'd like

I don't think we should have code that manually counts it, instead we inject the feature into the logger:

```
IHttpRequestSizeFeature
{
long RequestLineSize { get; }
long HeaderSize { get; }
long? BodySize { get; } // find appropriate optimization based on buffering/content-length?
long TotalRequestSize { get; }
}

IHttpResponseSizeFeature
{
// similar to above
}
```

**Comment by Tratcher** [comment]
Ah, found it: https://github.com/dotnet/aspnetcore/issues/38918. https://github.com/dotnet/aspnetcore/issues/38919
