### ISSUE TITLE
Blazor WASM app fails to launch with 7.0 runtime and 6.0.10 packages

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#44963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to VS17.4 and setting `<TargetFramework>net7.0</TargetFramework>` I was just a little to eager to start my project, my Blazor WASM app failed to launch in Edge 107 with the console error message: 'Cannot use 'import.meta' outside a module'

![image](https://user-images.githubusercontent.com/4984486/200766406-3ddaff96-da8e-4b86-8f6f-67f47583d552.png)

```
var createDotnetRuntime = (()=>{
    var _scriptDir = import.meta.url;

    return (function(createDotnetRuntime) {
        createDotnetRuntime = createDotnetRuntime || {};
...
```

After upgrading all packages (`Microsoft.AspNetCore.Components.WebAssembly` and friends) 7.0 things worked fine

### Expected Behavior

It runs fine or should give a better error message

### Steps To Reproduce

1. File new app with 6.0 template
2. Upgrade target framework to 7.0
3. Run

### .NET Version

7.0.100

### Anything else?

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

**Comment by javiercn** [comment]
@rogihee thanks for contacting us.

Did you clean your bin and obj folders after updating the TFM? Incremental TFM updates are tricky for us to test, and we often miss things. We always recommend making sure you have a "clean slate" after a big update like this.

In addition to that, we normally expect that you update the TFM and the packages that we ship together. We do not test mix-and-match scenarios.

**Comment by rogihee** [comment]
Yes, I did a full clean. It's fine not to mix-match.

**Comment by GiffenGood** [comment]
Getting the same error.  Did a checkout into a clean directory.  Project was upgraded from 6.0

**Comment by GiffenGood** [comment]
My mistake.  I had missed updating a framework package reference from 6 to 7.

**Comment by fabiansanchez18** [comment]
> 



> As a note for others. I followed this and was still getting the error. It wasn't until I did a hard refresh in the browser that it worked. Maybe having blazor tag a ?v=7.0 on the framework JS uri paths would be nice for cache busting.

Thank you. It happened to me today. I have to clean the site cache on my browser. Blazor must do something with this, because it may brake the site on the clients browsers, and that is dangerous. How can we tell to costumers to refresh the browser cache doe to our framework update.

**Comment by jon001** [comment]
> I'm getting this error in a freshly created .NET7 Blazor WASM project in VS2022 (v.17.4.0).
> 
> All relevant MS assemblies are v7.0.0.0. I've cleared the browser cache in Chrome using Developer tools in Application / Storage / Clear site data, and also by manually deleting assemblies from Application / Cache / Cache Storage (which afaics does the same thing). I've cleaned the project in VS, and deleted the /bin and /obj directories from the output.
> 
> I wondered if the Microsoft.EntityFrameworkCore.Sqlite v7.0.0.0 package was involved somehow, since adding that to the project appears to do something odd to the" /_framework/dotnet.[version, random chars].js" file in which the import.meta.url line appears, but after removing the Sqlite package the problem persists.
> 
> In case it's relevant somehow, the odd thing is that without the Sqlite package the filename is "dotnet.7.0.0.amub20uvka.js" but with the package it's "dotnet..m1qm36j7cw.js" - i.e. it's lost the version number. The content of the file still seems ok to me but I'm far from comfortable diagnosing stuff like this.

Update: I created a fresh.NET7 WASM project and copied all the assets across and was initially seeing the same error. Appeared to be able to resolve this by removing certain nuget packages (Syncfusion controls), but having re-added those packages I'm still not seeing the error despite cleaning the project, clearing browser cache etc. 
There's another possible aggravating factor: I had earlier manually installed "Microsoft .NET SDK 7.0.100 (x64)" which I recently found was duplicated by the automatically installed "Microsoft .NET SDK 7.0.100 (x64) from Visual Studio". I've uninstalled the non-Visual Studio version and that might be the actual fix for this issue.
