### ISSUE TITLE
DefaultAuthenticationConfigurationProvider has new dependency on IConfiguration

### ISSUE THREAD

**Issue by ly29** [dotnet/aspnetcore#44966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Breaking change by dependendecy injection. This change is not documented

### Expected Behavior

Do not break things

### Steps To Reproduce

Upgrade to dotnet 7, call working dotnet6 code with minimal dependency injection. 

### Exceptions (if any)

System.InvalidOperationException : Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Microsoft.AspNetCore.Authentication.DefaultAuthenticationConfigurationProvider'.

### .NET Version

7.0.100

**Comment by davidfowl** [comment]
What does your old code do?

**Comment by ly29** [comment]
Yeah that explains it. For test case we try to use a little as possible to so we had to add configuration that did nothing in this case.

**Comment by ly29** [comment]
Updating with `WebApplication.CreateBuilder().Services` instead of `ServiceCollection()` solved the issue.
