### ISSUE TITLE
UseHttpsRedirection: A post request on http redirects to get

### ISSUE THREAD

**Issue by iduras3** [dotnet/aspnetcore#44967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The wrong Method is called, when a GET and POST Method exists, under the same path. 
The http post on an Endpoint calls the Method for get. 

This does not happen, when UseHttpsRedirection is not used. 

### Expected Behavior

The correct Action is done. 

### Steps To Reproduce

1. Create a Controller with a POST and GET Method, which use the same path.
2. Activate UseHttpsRedirection
3. Call the post with http

### .NET Version

6.0.402

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

**Comment by Tratcher** [comment]
UseHttpsRedirection uses the 307 status code by default, which instructs the client to preserve the method (POST) when redirecting. If the client isn't honoring that then it's a bug in the client. What client are you using?
https://github.com/dotnet/aspnetcore/blob/c3438e04bbee1fb7890381113c8fbc810bcbeb35/src/Middleware/HttpsPolicy/src/HttpsRedirectionOptions.cs#L16
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
