### ISSUE TITLE
Cannot receive push data from API when build app release with proguard android 

### ISSUE THREAD

**Issue by nvmabc** [dotnet/aspnetcore#44993]
I have issue with build release app when push data to receiver SignalR error cannot receive that data. 
The API pushed already. 
to be easy to understand about that error I would like to invite to see this link on stackoverflow.

[https://stackoverflow.com/questions/74219130/build-release-app-cannot-receive-push-on-client-with-proguard-android-kotlin-wit]

I cannot resolve that issue because I test maybe accept proguard but still cannot. 

for run or build debug is work normal.

I hope everyone can help me this case. Thanks.

**Comment by BrennanConroy** [comment]
You are using signalr-client-sdk.jar and signalr-client-sdk-android.jar which are not supported.
https://github.com/SignalR/java-client
