### ISSUE TITLE
dotnet 6 app stopped working after update to VS 2022 17.4

### ISSUE THREAD

**Issue by anirugu** [dotnet/aspnetcore#44991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sun is shining, Birds are chirping. Air quality is scoring bad but still breathing the air. 

I create a stupid app that I consume myself. I run it from the terminal and it's run well. It was developed using .net 6. Now after I update to the latest VS 2022 17.4 it's have updated the VS tooling to .net 7.

sadly it broke the app. 

![image](https://user-images.githubusercontent.com/35772421/200992209-cf0f8d2b-500e-419f-a5a4-3cc315d7a6b2.png)

FYI, I didn't change it to 7.0 and didn't change anything. An app that is working earlier is now broken.  If you want to test, take a clone of master branch https://github.com/anirugu/proxy

### Expected Behavior

It should run, no problem if run at the speed of a tortoise or ant. But it's failed to run at any speed.

### Steps To Reproduce

take a clone and run

### Exceptions (if any)

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()

### .NET Version

6.0

### Anything else?

It failed after upgrade to VS 2022 17.4.  Having 7.0 in my PC might be reason I am writing this issue.

**Comment by anirugu** [comment]
failing to work if not have wwwroot folder 
![image](https://user-images.githubusercontent.com/35772421/200997352-3a548851-3615-42ea-b98c-409801d8e4ff.png)

**Comment by pmccloghrylaing** [comment]
I've run into the same issue where `dotnet watch` fails. It runs fine using `dotnet run` or running from Visual Studio. I've tried adding a `global.json` file to specify the sdk version, but without success.

**Comment by anirugu** [comment]
@pmccloghrylaing for me my code was on 6.0 and nothing special is added except swagger which I believe is very common. The code is failing till I make the 7.0 and update the swagger nuget package.

pointed to be noted that it's still failing until I create the wwwroot folder.

**Comment by pmccloghrylaing** [comment]
@anirugu - looks like the same issue, my project is aspnetcore, targeting net 6.0, with swagger. And this happens since installing the latest visual studio which updated dotnet to 7.0.100. The exception I'm getting is identical.

**Comment by pmccloghrylaing** [comment]
Looks like this is the same error as posted here: https://github.com/dotnet/sdk/issues/28942

**Comment by anirugu** [comment]
@pmccloghrylaing  the error mention in https://github.com/dotnet/sdk/issues/28942 is exactly same as what I am facing + wwwroot not found issue.

**Comment by jquery2005** [comment]
Nothing to change, just use "dotnet watch run 【Project Name】" continue to running.

**Comment by jesselawson** [comment]
Using `net6.0`, I was running into the following issue, even after restarting, `dotnet clean`, etc:

```
dotnet watch 🚀 Started
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()

dotnet watch ❌ Exited with error code 134
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

Using `dotnet watch run .` solved by issue. (including the `.` in the command seems to matter).

**Comment by davidfowl** [comment]
That error looks like a startup hook compiled against .NET 7 but running in a .NET 6 application...

**Comment by mkArtakMSFT** [comment]
Can somebody please confirm if this has been resolved already?
Given that there has been no recent feedback here I assume that's the case, but would like to get confirmation.
