### ISSUE TITLE
Blazor Hybrid + Web

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#45004]
Blazor Hybrid enables you to build native client apps using Blazor components for the UI. You can then share the UI implementation between your native clients and web apps. The [.NET Podcasts sample app](https://aka.ms/dotnet-podcasts) does this.

However, [it's a bit manual and clunky to set this up](https://learn.microsoft.com/aspnet/core/blazor/hybrid/reuse-razor-components). You have to pull out your components into a Razor class library that you then share with a .NET MAUI project and a Blazor web project. Could we create a more unified developer experience for building these sorts of apps that target web, mobile, and desktop via the web platform?

**Comment by danroth27** [comment]
@BethMassi

**Comment by mkArtakMSFT** [comment]
We'll use https://github.com/dotnet/maui/issues/1069 to track this work.
