### ISSUE TITLE
ASP.NET Core Module v2 17.0.22292.0 Very serious bug

### ISSUE THREAD

**Issue by xgbzsc** [dotnet/aspnetcore#45006]
Direct memory exhaustion in Windows server 2008R2

**Comment by xgbzsc** [comment]
These problems do not exist in versions higher than Windows Server 2008 R2

**Comment by xgbzsc** [comment]
It may be a conflict with a lower version of netcore. One or two Windows Server 2008 R2 servers are OK. Most other servers will run out of resources. The rule has not been completely found. Finally, the server system has been upgraded to a higher version to solve the problem.

**Comment by adityamandaleeka** [comment]
@xgbzsc Unfortunately, there is not enough information in this issue for it to be actionable.

For what it's worth, Windows Server 2008 R2 is well out of support: https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2
