### ISSUE TITLE
Upgrading from 6.0.11 to Microsoft.Aspnetcore.Signalr.Client 7.0 introduced System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by DP-Technology-LLC** [dotnet/aspnetcore#45012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the RelayCommand attribute as part of Community.Toolkit.Mvvm in a .NET Maui app.  I get this exception when the client method that the server calls updates and then calls the NotifyCanExecuteChanged() on a command.  In version 6.11 this isn't a problem, just in 7.0.

Client Method
`_ = base.HubConnection.On<JsonElement>("Authorized", async (authorizedUser) =>
            {
                base.AuthorizedUser = authorizedUser;
                base.ToggleAdminIsVisibleCommand.NotifyCanExecuteChanged();
            });`

Relay Command
`[RelayCommand(CanExecute = nameof(IsAdmin))]
        protected void ToggleAdminIsVisible() { this.AdminIsVisible = !this.AdminIsVisible; }`

IsAdmin Variable
`bool IsAdmin => AuthorizedUser != null ? AuthorizedUser.IsAdmin : false;`

The exception
`System.Runtime.InteropServices.COMException: 'The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))'
`

I also update a label with the User's name from the AuthorizedUser object in the same method and have no problems there.  That label utilizes ObservableProperty from the same Toolkit.

### Expected Behavior

The same behavior in 6.11.  No exception thrown.

### Steps To Reproduce

See snippets in Description.

### Exceptions (if any)

System.Runtime.InteropServices.COMException

### .NET Version

7.0.100

**Comment by BrennanConroy** [comment]
@Eilon No clue what these concepts are, should this be moved to Maui?

**Comment by Eilon** [comment]
I'm guessing this is an issue for https://github.com/CommunityToolkit/dotnet/. @DP-Technology-LLC are you using this NuGet package: https://www.nuget.org/packages/CommunityToolkit.Mvvm/ ?

**Comment by DP-Technology-LLC** [comment]
Correct, I am using version 8.0.0...and had used 8.0.0 when using Microsoft.Aspnetcore.Signalr.Client 6.0.11 as well.

**Comment by BrennanConroy** [comment]
Maui is a UI programming model, so you might need to use 
```
MainThread.BeginInvokeOnMainThread(() =>
{
    // Code to run on the main thread
});
```

in the SignalR client callback.
Docs: https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/main-thread?view=net-maui-7.0#run-code-on-the-ui-thread

**Comment by DP-Technology-LLC** [comment]
Yeah, I am doing this for places where I am deliberately creating other threads that update the UI.  

Had I started this app using SignalR 7.0 I wouldn't have batted an eye on that exception and just done as you suggested, but since 6.11 behaves differently than 7.0, I figure I reach out to verify that the expectation from this point forward is that all SignalR callbacks need to jump on the main thread to update the UI (I don't think I have a SignalR callback that doesn't impact the UIm in some fashion).

**Comment by BrennanConroy** [comment]
> but since 6.11 behaves differently than 7.0, I figure I reach out to verify that the expectation from this point forward is that all SignalR callbacks need to jump on the main thread to update the UI

Yes this is the expectation. The callbacks come from a random thread since they can occur at any time. One reason 6.0.X is different from 7.0 is that we changed to use `.ConfigureAwait(false)` everywhere in 7.0 (which is what we should have been doing from the start).

**Comment by DP-Technology-LLC** [comment]
Thanks so much for this info, from this point forward I will treat SignalR callbacks the same as spawned threads.
