### ISSUE TITLE
Blazor User Blocked from Downloading DLL Files

### ISSUE THREAD

**Issue by D-McInnes8** [dotnet/aspnetcore#45018]
Currently we are experiencing an issue where some of our users of our Blazor Web Assembly app are being blocked from executing the downloaded dll files.

![image](https://user-images.githubusercontent.com/96274982/201274621-b1982092-8360-4285-b3e0-5f42652acae5.png)

Looking at existing issues it looks like the best solution is to rename the .dll files as .bin files, as per the documentation below:

https://github.com/dotnet/aspnetcore/issues/5477#issuecomment-599148931
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#change-the-filename-extension-of-dll-files-1

We've created a PowerShell script that runs as part of our Azure DevOps build pipeline that renames the files to the .bin extension, and looking at the build artifacts from the pipeline confirms that the files have been renamed to .bin files.

However when the build artifact is deployed to an Azure app service the .bin files are either replaced with .dll files to renamed back to .dll files.

**Comment by javiercn** [comment]
@D-McInnes8 thanks for contacting us.

Could you give us more details? Is this an anti-virus or another enterprise firewall that is doing this? Is this a firewall (or similar rule) that your IT has set up?

The best way to address this is to customize the the deployment layout for your app. We have docs on how you can do this [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-deployment-layout?view=aspnetcore-7.0)

and some people in the community has built turn-key solutions like https://www.nuget.org/packages/BlazorWasmAntivirusProtection which will address these issues.

We have a tracking issue https://github.com/dotnet/aspnetcore/issues/36978 for improvements in this area here.

**Comment by D-McInnes8** [comment]
Hi Javier, thanks for the reply.

Unfortunately this is an external user, so we don't have any details on exactly what security has been set up on their system. The users were able to access the site when using their phones, but received the above error when trying to access it using their work desktops.

Thanks for the links, I'll have through them and see if I can resolve the issue using those solutions.
