### ISSUE TITLE
Continue reducing the size of Blazor WebAssembly apps

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#45010]
We should continue to look at reducing the download size of Blazor WebAssembly apps to remove any remaining dead weight code.

Related runtime issues:

- https://github.com/dotnet/runtime/issues/43778
- https://github.com/dotnet/runtime/issues/44530 (see the "Future release" list)
- https://github.com/dotnet/aspnetcore/issues/49409

On the Blazor side, we could look at enabling more of System.Text.Json by using a source generator.

**Comment by TanayParikh** [comment]
Related to https://github.com/dotnet/aspnetcore/issues/42284 ?

**Comment by danmoseley** [comment]
cc @eerhardt fyi

**Comment by StephenEhlers** [comment]
@danroth27 @mkArtakMSFT Is there a sample client webassembly project that has all the best settings for getting the project down to the 1.5mb size or maybe less now in .net 7.0? I have applied all the settings I can find and removed everything except for the most basic components to load blazor up but I am still riding at 3.1mb.

I got the 1.5mb number from this video: 

[https://www.youtube.com/watch?v=Jte_VwsSazs](url)

Thanks for the help!

**Comment by eerhardt** [comment]
@StephenEhlers - have you also installed the `.NET WebAssembly build tools`?

![image](https://user-images.githubusercontent.com/8291187/202727696-671f34ac-fe83-4a76-9f55-0a96a70d5a86.png)

If you install that, the `dotnet.wasm` file gets even smaller after publish, because it is "re-linked" with only the code your app needs.

**Comment by mkArtakMSFT** [comment]
Closing as the remaining work is already tracked with issues in the runtime repo. That said, this is an effort we're not going to stop and will be looking for new ways to reduce the size as we move forward.
