### ISSUE TITLE
MicrosoftIdentityOption.ReturnUrlParameter does not appear to work

### ISSUE THREAD

**Issue by ShaunCurtis** [dotnet/aspnetcore#45024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Most likely a documentation problem on how it works]

Context: Blazor Server Template with Authentication in VS2022.  Application running in debug mode.

Relevant AppSettings section:

```
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
      ... relevant Domain, Secret and ID parameters to make it work
    "ReturnUrlParameter": "custompath",
    "AccessDeniedPath": "/",
  },
```

Relevant Program Section:

```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                   .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                        .AddInMemoryTokenCaches();

            services.AddAuthorization();
```

Run up the app and manually call 
```
https://localhost:5001/MicrosoftIdentity/account/signin?custompath=%2fcounter
```

### Expected Behavior

It should, if I understand the documentation correctly, run through the login process and then take me back to the counter page.

It doesn't, it returns to `/`.  What am I missing from the documentation?

### Steps To Reproduce

See the decription

### .NET Version

7.0.100

### Anything else?

VS2022 Community
Net6.0
Windows10
Blazor server template with Azure ADB2C Authentication.

**Comment by javiercn** [comment]
@ShaunCurtis thanks for contacting us.

/cc @jmprieur

**Comment by javiercn** [comment]
This issue was moved to AzureAD/microsoft-identity-web#1968
