### ISSUE TITLE
HostingStartup failed to execute after updating to .net 7/asp.core 7 on Azure App Service

### ISSUE THREAD

**Issue by ChristophHornung** [dotnet/aspnetcore#45022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating my asp.net core project to .net 7 (all nugets are up to date on the latest 7 releases) I get the following error in the logs on startup

```
Category: Microsoft.AspNetCore.Hosting.Diagnostics
EventId: 11

Hosting startup assembly exception

Exception: 
System.InvalidOperationException: Startup assembly DiagnosticServices.HostingStartup failed to execute. See the inner exception for more details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|47_0(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Int32 throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
   --- End of inner exception stack trace ---
```

The startup still continues and the application is responsive afterwards.

### Expected Behavior

I expect the hosting startup to not fail on startup.

### Exceptions (if any)

System.InvalidOperationException: Startup assembly DiagnosticServices.HostingStartup failed to execute. See the inner exception for more details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|47_0(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Int32 throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
   --- End of inner exception stack trace ---

### .NET Version

dotnet 7 on AzureAppService

### Anything else?

ASP.net core 7 (assemblies involved are `Microsoft.AspNetCore.Hosting, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` and `System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e`)

**Comment by TuroczyX** [comment]
Hi,

I have similar issue with my application and seems this is a bug on Azure App Service Side. After you deploy a .net 7 app into app service and even the app service framework was set up for .net 7 (STS) for some reason it goes back .net 6, and get this issue.  You need to set it up again manually and restart the service. 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/7687174/201532420-5f47a7ee-ab31-4398-bb5a-d7ae7247cff6.png">

PS: No my deployment script does not contains this step to set it back to .net 6.

**Comment by adityamandaleeka** [comment]
@reyang

**Comment by Dave-Bronson-Greystone** [comment]
Am seeing the same issue.  Except that in my instance it's a brand new .NET 7 ASP.NET MVC app being deployed into an app service slot that was previously .NET 4.8.  It's a ground-up/fresh rewrite of the app.

I did change the app service configuration to specify .NET 7, and also checked the 'Remove additional files at destination' option when publishing from VS2022.  Lastly, I did fully stop and restart the Azure slot.

Other than the exception being logged, the web app seems to run fine from the Azure slot.

**Comment by adityamandaleeka** [comment]
The team is aware of this issue and working on fixing .NET 7 support. cc: @pharring

**Comment by beevik** [comment]
I'm seeing a similar issue after upgrading an ASP.NET Core application from .NET 6 to .NET 7.

My application also generates a FileNotFoundException, except it is for the Assembly that's actually running.  It is triggered by a call in my code to `MvcServiceCollectionExtensions.AddControllers`.

This is the Json-ified stack trace of the exception:

```json
{
    "Type": "System.IO.FileNotFoundException",
    "Message": "Could not load file or assembly 'Auth, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.",
    "StackTrace": [
        {
            "Func": "System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)"
        },
        {
            "Func": "System.Reflection.Assembly.Load(AssemblyName assemblyRef)"
        },
        {
            "Func": "Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.GetApplicationPartAssemblies(String entryAssemblyName)"
        },
        {
            "Func": "Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)"
        },
        {
            "Func": "Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services, IWebHostEnvironment environment)"
        },
        {
            "Func": "Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)"
        },
        {
            "Func": "Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)"
        },
        {
            "Func": "Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services, Action`1 configure)"
        },
        {
            "Func": "Foo.Core.Web.Mvc.MvcModule.ConfigureServices(FrameworkServicesBuilder builder)",
            "File": "C:/Git/foo/Server/Libraries/Core.Web/src/Mvc/MvcModule.cs",
            "Line": 64
        },
        {
            "Func": "Foo.Core.Framework.FrameworkApplicationStartup.ConfigureServices(IServiceCollection services)",
            "File": "C:/Git/foo/Server/Libraries/Core.Framework/src/FrameworkApplicationStartup.cs",
            "Line": 90
        }
    ],
    "InnerException": null
}
```

The name of the running assembly (the one the error claims couldn't be found) is `Foo.Servers.Auth`.  (I have replaced personally identifying information with the word `Foo`).

**Comment by adityamandaleeka** [comment]
@beevik your error seems to be unrelated to the DiagnosticServices issue being tracked here.

@brunolins16 Any advice for @beevik to debug this?

**Comment by beevik** [comment]
Apologies, I can open a new issue if that helps.

**Comment by brunolins16** [comment]
@beevik Glad you have fixed your issue, however, there is no change between .NET 6 and .NET 7 related how we are detecting the entry assembly. The only thing related was the addition of logs https://github.com/dotnet/aspnetcore/issues/39126.

Feel free to open another issue in case you still have problems.

**Comment by BrennanConroy** [comment]
@pharring Should this issue be moved to https://github.com/microsoft/ApplicationInsights-dotnet/issues?

**Comment by ChristophHornung** [comment]
> The team is aware of this issue and working on fixing .NET 7 support. cc: @pharring

@adityamandaleeka Can you or the team elaborate on what the consequences of this issue are? The app seems to be responsive so far. Is there any workaround for that problem?

**Comment by pharring** [comment]
@BrennanConroy,
> Should this issue be moved [...]?

No, I don't think so. It's not an App Insights SDK issue. The DiagnosticServices component isn't open sourced, but we're tracking this internally.

@ChristophHornung,
> Can you or the team elaborate on what the consequences of this issue are? 

There are two consequences:
1. An annoying exception in the startup logs.
2. The Snapshot Debugger feature is broken.

As you say, the app is otherwise unharmed.

**Comment by ChristophHornung** [comment]
@pharring What is the state of this issue? I am still seeing this error in the logs, shouldn't this issue be kept open until it is resolved?

**Comment by alalloo** [comment]
@BrennanConroy FWIW, the workaround in #17370 - removing three config variables - removed the exception for us. The conditions in that bug were not same as ours (not using NLog for example), but the symptoms were.

**Comment by pharring** [comment]
@ChristophHornung sorry for the delayed reply. An update to Azure App Service with the fix is currently being rolled out worldwide. Some regions have already been updated. If you have the fix, the environment variable WEBSITE_PLATFORM_VERSION will be 100.0.7.49

**Comment by ChristophHornung** [comment]
@pharring Good to know, thank you for the update.

**Comment by ChristophHornung** [comment]
@pharring I am still seeing App Services with WEBSITE_PLATFORM_VERSION on 99.x on my existing and even newly created App Services (in the West Europe and Germany West Central regions). Is there a timeline on when the rollout is complete?
