### ISSUE TITLE
Results.File and Results.Stream consume large amount of Memory, don't stream file directly anymore

### ISSUE THREAD

**Issue by davepermen** [dotnet/aspnetcore#45037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

using MapGet("/", () => Results.File("bigfile.bin")) causes huge amount of memory consumption, and multiple seconds of delay till the download starts.

In .net6, download started instantly and used up no memory.

Same Issue on Results.Stream

Bug with screenshots for comparison visible here:

![image](https://user-images.githubusercontent.com/1953296/201438046-ef526207-e3f6-47dd-9778-e24c94641fba.png)
![image](https://user-images.githubusercontent.com/1953296/201438069-f6d381ae-5615-4f08-8368-3fb3a1dc6cef.png)

### Expected Behavior

Results.File and Results.Stream should directly stream the file download without loading it first into ram.

### Steps To Reproduce

I created a repo here, needs a big file in wwwroot/1gb.bin

https://github.com/davepermen/ResultsFileBug

to create file quickly (on windows): open cmd in wwwroot and run "fsutil file createnew 1gb.bin 1073741824" but any file works.

switch project between net6 and net7 to see the effect.

### .NET Version

7.0.100

**Comment by davidfowl** [comment]
@davepermen Are you seeing this with HTTP/2? I assume you are using the browser to download the file?

**Comment by davepermen** [comment]
Yes, both cases the browser responds with "h2" (i assume it's short for HTTP/2).

i the browser network tools, it states on net6: timing: it starts after 4.8ms. in net7, 3.2s. transfer itself is a bit above 3seconds in both.

**Comment by davidfowl** [comment]
I can reproduce the issue, looking into it.

**Comment by davidfowl** [comment]
OK this seems to be a bug in the BrowserLink middleware (something visual studio installs to do refreshing of HTML). 

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/95136/201508092-f9d17594-806d-4add-ba05-c4d9d39ce4ba.png">

Seems like there's a large allocation happening.

@davepermen You can turn off it off with this feature in visual studio:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/95136/201508222-7f2e19ef-c256-4aca-978e-1fe44bb581ed.png">

Can you also confirm that this does not repro from the command line?

cc @vijayrkn @jodavis

**Comment by davidfowl** [comment]
OK it's not the browser link middleware but it seems like the BrowserRefresh middleware is also to blame here 😄. (sorry @vijayrkn and @jodavis).

@MackinnonBuck it looks like [this change]( https://github.com/dotnet/sdk/commit/7d4ae9a8a2f401681e3c169b1e1fcc854a545d59) might be the problem. We're using a memory stream to buffer the entire response body instead of the passthrough we had before.

**Comment by davepermen** [comment]
I can confirm, "dotnet run" from the commandline works as expected, and disabling CSS Hot Reload solves the issue in Visual Studio for now, till a proper fix is back 👍

**Comment by MackinnonBuck** [comment]
Yep, we changed the BrowserRefresh middleware to buffer the entire response to improve the reliability of hot reload script injection. We could fix the memory usage problem by checking earlier whether we're working with an HTML response so we can switch back to a passthrough.

Possible servicing candidate?

cc @mkArtakMSFT. Note that this issue only affects development scenarios with hot reload enabled.

**Comment by davidfowl** [comment]
@mkArtakMSFT @MackinnonBuck yes we need to service this.

**Comment by davidfowl** [comment]
> Yep, we changed the BrowserRefresh middleware to buffer the entire response to improve the reliability of hot reload script injection. We could fix the memory usage problem by checking earlier whether we're working with an HTML response so we can switch back to a passthrough in cases where we know script injection can't be performed.

I think we should revert the fix and work on a more reliable solution that includes more fixes to the implementation during buffering. We need to get rid of the buffering. Developers doing performance testing while running visual studio are going to see huge problems with that.

**Comment by KSemenenko** [comment]
@davidfowl What is the right way to handle large files?
If I need to transfer it.

I have so far come to the solution that I open the stream from the disk and write the data into HttpResponce, but still for a 250mb file it is a problem.

I also tried to do when I receive a file from a user, first write it to disk, and then take action.

I also have a http stream in memory anyway.

Do you have any examples?

**Comment by davidfowl** [comment]
The sample here is fine. The problem is our middleware that is buffering the response (as described in the replies above).

**Comment by Spirch** [comment]
I have spend multiple hours trying to figure out why this simple code wasnt working

`        public async Task<FileStreamResult> Test()
        {
            //random big file found online

            //const string url = "http://ipv4.download.thinkbroadband.com/512MB.zip";
            const string url = "https://speed.hetzner.de/1GB.bin";

            var client = new HttpClient();
            var stream = await client.GetStreamAsync(url);
            return File(stream, "application/zip");
        }`

it always load everything in memory before sending it

I tried disabling the CSS Hot Reload, **it doesnt work**

it **only work** when i do a **dotnet run**
