### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#45031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to add a blazor wasm project to am existing solution.

I am getting an error of "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'." I understand what the issue is that causes the error, but have yet to find the problematic package reference.

I don't want help finding the underlying error other than to have a proper error message generated. According to #28478 this was fixed in .Net 5 yet I am now seeing this same message with a .Net 7.0 solution.

### Expected Behavior

I expect a useful error message that gives some clue as to what project & reference is causing the problem.

### Steps To Reproduce

A repo project is https://github.com/MarkStega/ICEBG

You don't really need to understand anything in the repo, just do a 'dotnet build icebg.sln' from the root directory.

### .NET Version

7.0.100

**Comment by MarkStega** [comment]
The branch in the repo that exhibits the issue is vNext; I attempted to edit the original issue but the editor cuts off after 'Expected Behavior'

**Comment by javiercn** [comment]
https://github.com/MarkStega/ICEBG/blob/7e1db395bdab665638df2018717e0bbf52cc01b4/ICEBG.Client/ICEBG.Client.csproj#L28-L33

Very likely is:
```
  <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
or 
  <PackageReference Include="Grpc.Net.Client" Version="2.49.0" />
  <PackageReference Include="Grpc.Net.Client.Web" Version="2.49.0" />
```

It's not really up to us to provide a better message here. I would suggest you file the issue on the runtime repo, SDK or nuget (not sure what the right place for it is).

As to finding out the offending reference, open `obj\project.assets.json` and perform a search, that'll give you the dependency chain.
