### ISSUE TITLE
Blazor WASM stuck in infinite Http Request Loop

### ISSUE THREAD

**Issue by Will-Kerwin** [dotnet/aspnetcore#45032]
I have a dotnet 6 blazor wasm application. I have various pages which call certain services in my applicaiton through a httpclient with a authorization message handler. For some reason one of these http requests is stuck in an 'infinite loop' where the http client instantiated by IHttpClientFactory.CreateClient method will do the following steps:

1. make the request.
2. recieve a response in the network tab in chrome
3. make the request again

this leads to an infinite loop of sorts where GetFromJsonAsync will be repeatedly called a valid response from the api is sent but dotnet does not register and retries. I have put breakpoints directly after GetFromJsonAsync which are never hit however, ones direclty before that line do. I hope i have explained this clearly but i have attached relevant code below.

Component:

```
        protected override async Task OnParametersSetAsync()
	{
		_isLoading = true;

		Plans = await PlanService.Get(0, _recordsToTake);
		TotalPlans = Plans.Count();

		_isLoading = false;
	}
```

Service:

```
        try
        {
            var client = _clientFactory.CreateClient("TLP");
            var res = await client.GetFromJsonAsync<IEnumerable<FlightPlanSection>>($"{_configuration.GetConnectionString("PlansAPI")}/flightPlans/{planId}/sections");
            if (res is null) return Enumerable.Empty<FlightPlanSection>();
            return res;
        }
        catch (HttpRequestException httpE)
        {
            _logger.LogError(httpE, "An Error Occured when connecting to the server");
            _snackbar.Add("An Error Occured when connecting to the server", Severity.Error);
            return Enumerable.Empty<FlightPlanSection>();
        }
        catch (Exception e)
        {
            _logger.LogError(e, "An Unexpected Error Occured");
            _snackbar.Add("An Unexpected Error Occured", Severity.Error);
            return Enumerable.Empty<FlightPlanSection>();
        }
```
Dev Tools Network Tab:

![Screenshot 2022-11-11 194809](https://user-images.githubusercontent.com/10259319/201420124-5aa17297-4b79-42c3-8363-ecc14ef35fdd.png)

**Comment by javiercn** [comment]
@Will-Kerwin thanks for contacting us.

Do you have a minimal repro so that we can take a look?
