### ISSUE TITLE
How remove a configuration provider in ASP.NET 6 minimap api?

### ISSUE THREAD

**Issue by abatishchev** [dotnet/aspnetcore#45043]
Previously, I would do this (per #40172):

```c#
config.Sources.Clear();
```

Because `config` was of type [IConfigurationBuilder ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationbuilder?view=dotnet-plat-ext-6.0) which exposes `Sources`.

However now it's of type [ConfigurationManager ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationmanager?view=dotnet-plat-ext-6.0) which does not.

**Comment by davidfowl** [comment]
In .NET it's a bit cumbersome:

```C#
((IConfigurationBuilder)builder.Configuration).Sources.Clear();
```

FWIW this was improved in .NET 7:

```C#
builder.Configuration.Sources.Clear();
```

**Comment by abatishchev** [comment]
Asked a question and only then updated to 7. Works nicely, indeed. Thanks, David!
