### ISSUE TITLE
Blazor WebAssembly KeyboardEventArgs keys Unidentified on mobile browsers

### ISSUE THREAD

**Issue by francescocristallo** [dotnet/aspnetcore#45046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor WebAssembly hosted, dotnet 7.0.100
On mobile browsers (Edge, Chrome, Brave), the KeyboardEventArgs key is Unidentified.

This happens only on mobile, not on desktop browsers

![Test](https://user-images.githubusercontent.com/9793825/201457659-da49309d-7261-45f6-a6c5-fb0e371581a5.png)

### Expected Behavior

Typed key should be identified as it happens on desktop browsers.

### Steps To Reproduce

I put a live site to test it since it has to be tested on mobile browsers:

https://blazortestf.azurewebsites.net/

Repo is empty template:

https://github.com/francescocristallo/BlazorAppemptytestkeyup/tree/master/BlazorApp-empty-testkeyup/Client/Pages

### .NET Version

7.0.100

**Comment by campersau** [comment]
I think that this is a general mobile browser issue with keyboard events as you can observe the same behavior with pure javascript:
https://jsfiddle.net/tzg24erw/show
Here is a good video which shows how unreliable keyboard events are on the web: https://www.youtube.com/watch?v=jLqTXkFtEH0

**Comment by MackinnonBuck** [comment]
To read keystrokes on mobile devices, you can use an invisible `<input type="text" />` and add an `@oninput` handler to react to changes to its value. You would need a similar workaround for non-Blazor scenarios, as @campersau pointed out.
