### ISSUE TITLE
Invoking endpoint filter but not handler on argument error causes VoidTaskResult to be written to the response body

### ISSUE THREAD

**Issue by Oskarsson** [dotnet/aspnetcore#45040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A serialized VoidTaskResult is written to the _HttpResponse.Body_ when an endpoint filter is used and the endpoint fails argument validation.

**Reason behind the issue**
The reasons this occurs is because the pipeline will return a _ValueTask.FromResult\<object\>(Task.CompletedTask)_ when the HttpContext.Response.StatusCode is 400 as seen below, this will then be serialized to Json when _AddResponseWritingToMethodCall_ detects that the return type is _ValueTask\<object\>_ and call the method chain _ExecuteValueTaskOfObject_ > _ExecuteAwaitedReturn_ > _WriteJsonResponse_

```C#
var filteredInvocation = Expression.Lambda<EndpointFilterDelegate>(
            Expression.Condition(
                Expression.GreaterThanOrEqual(FilterContextHttpContextStatusCodeExpr, Expression.Constant(400)),
                CompletedValueTaskExpr,
                handlerInvocation),
            FilterContextExpr).Compile();
```

An existing unit test (_RequestDelegateFactory_InvokesFiltersButNotHandler_OnArgumentError_) would catch this issue if it checked that the _HttpContext.Response.Body_ should be empty at the end of the test.

**Possible solution**
The easiest solution I have found is just to check if the value in _ExecuteAwaitedReturn_ is of type Task.Completed as seen in the last else if statement below, and skip the JSON serialization.

Thoughts?

```C#
private static Task ExecuteAwaitedReturn(object obj, HttpContext httpContext)
{
    // Terminal built ins
    if (obj is IResult result)
    {
        return ExecuteResultWriteResponse(result, httpContext);
    }
    else if (obj is string stringValue)
    {
        SetPlaintextContentType(httpContext);
        return httpContext.Response.WriteAsync(stringValue);
    }
    else if (obj != Task.CompletedTask)
    {
        // Otherwise, we JSON serialize when we reach the terminal state
        return WriteJsonResponse(httpContext.Response, obj);
    }
    return Task.CompletedTask;
}
```

### Expected Behavior

I would expect to get a 400 status code without a response body, this is the behavior you get when no endpoint filter is defined.

### Steps To Reproduce

1. Create the application described below
2. Go to the endpoint without defining the query parameter (e.g., http://localhost:5001)
3. The following result should be observed:
```JSON
{"result":{},"id":41,"exception":null,"status":5,"isCanceled":false,"isCompleted":true,"isCompletedSuccessfully":true,"creationOptions":0,"asyncState":null,"isFaulted":false}
```

**Application**
```C#
var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<RouteHandlerOptions>(o => o.ThrowOnBadRequest = false);
var app = builder.Build();
app.MapGet("/", (string name) => $"Hello, {name}!")
   .AddEndpointFilter(async (context, next) =>
   {
       return await next(context);
   });
app.Run();
```

### .NET Version

7.0.100

**Comment by davidfowl** [comment]
@halter73 side effect of https://github.com/dotnet/aspnetcore/pull/41719/files?

**Comment by captainsafia** [comment]
I think the best way to fix this is to figure out a way to update the generated code. At the moment, we're emitting:

```csharp
if (httpContext.Response.StatusCode >= 400)
{
  return new ValueTask<object>(Task.CompletedTask);
}
```

So, we end up serializing the `ValueTask` object. We could probably emit:

```csharp
if (httpContext.Response.StatusCode >= 400)
{
  return (ValueTask<object>)ValueTask.Completed;
}
```

**Comment by Oskarsson** [comment]
@captainsafia 

Since _ValueTask_ cannot be casted to _ValueTask_<object_>_ can I instead suggest changing it to return an EmptyHttpResult? It's used on some other places in the _RequestDelegateFactory_ like when an endpoint returns a _ValueTask_ or _Task_.

```C#
if (httpContext.Response.StatusCode >= 400)
{
  return new ValueTask(EmptyHttpResult.Instance)
}
```

**Comment by davidfowl** [comment]
We need to backport this to 7.0

**Comment by captainsafia** [comment]
> We need to backport this to 7.0

Agree, put this in servicing earlier. I can open a backport PR...
