### ISSUE TITLE
UserManager.ResetPasswordAsync causes entity to be tracked a second time

### ISSUE THREAD

**Issue by ancailliau** [dotnet/aspnetcore#45048]
My code to reset the password of a user was failing due to a entity being tracked twice by EFCore. My code was getting the user only once, as seen in the code excerpt below. I'm pretty confident that my code was an issue in the past because this code was not changed for a few years. However, I could not pin down when it was introduced. 

Tracking down the issue revealed that the method `ValidateUserName(UserManager<TUser> manager, TUser user)` in the class `UserValidator<TUser>` is indeed causing the second database query to retrieve the entity, causing the duplicate tracking. Disabling the tracking for the entity within my code, did not solve the issue as I suspect that UserManager re-attach the entity for tracking.

As an example, consider the following code

```csharp
var _userManager = host.Services.GetRequiredService<UserManager<AppUser>>();

var userName = "admin";
var password = "testPassword123!!";
          
var dbContextOptions = host.Services.GetRequiredService<DbContextOptions<DocIntelContext>>();
var dbContextLogger = host.Services.GetRequiredService<ILogger<DocIntelContext>>();
var dbContext = new DocIntelContext(dbContextOptions, dbContextLogger);

// Same issue with AsNoTracking, or without AsNoTrackingWithIdentityResolution
var user = await dbContext.Users.AsNoTrackingWithIdentityResolution().SingleOrDefaultAsync(_ =>
    _.NormalizedUserName == userName.ToUpperInvariant()); 

var token = await _userManager.GeneratePasswordResetTokenAsync(user);
var passwordChangeResult = await _userManager.ResetPasswordAsync(user,
      token,
      password);
```

This fragment of code fails to execute properly, due to the following error

```
Unhandled exception. System.InvalidOperationException: The instance of entity type 'AppUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
```

In particular, the code following code is causing the user entity to be fetched and tracked a second time:
 https://github.com/dotnet/aspnetcore/blob/c5ee07392f0b5bb2ccbfd2ee38d484724ad5bbf3/src/Identity/Extensions.Core/src/UserValidator.cs#L74

As see in the logs

```
Started Thread 274650
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (36ms) [Parameters=[@__normalizedUserName_0='ADMIN'], CommandType='Text', CommandTimeout='30']
SELECT a."Id", a."AccessFailedCount", a."Bot", a."ConcurrencyStamp", a."Email", a."EmailConfirmed", a."Enabled", a."FirstName", a."Function", a."LastActivity", a."LastLogin", a."LastName", a."LockoutEnabled", a."LockoutEnd", a."NormalizedEmail", a."NormalizedUserName", a."PasswordHash", a."PhoneNumber", a."PhoneNumberConfirmed", a."Preferences", a."ProfilePicture", a."RegistrationDate", a."SecurityStamp", a."TwoFactorEnabled", a."UserName"
FROM "AspNetUsers" AS a
WHERE a."NormalizedUserName" = @__normalizedUserName_0
LIMIT 1
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'DocIntelContext' started tracking 'AppUser' entity with key '{Id: 7888660f-ae50-43a1-976e-b8aabd7c00d5}'.
```

Using the `UserManager<AppUser>` to get an instance of the user solves the issue. 

```csharp
var _userManager = host.Services.GetRequiredService<UserManager<AppUser>>();

var userName = "admin";
var password = "testPassword123!!";
          
var dbContextOptions = host.Services.GetRequiredService<DbContextOptions<DocIntelContext>>();
var dbContextLogger = host.Services.GetRequiredService<ILogger<DocIntelContext>>();
var dbContext = new DocIntelContext(dbContextOptions, dbContextLogger);

var user = await _userManager.FindByNameAsync(userName);

var token = await _userManager.GeneratePasswordResetTokenAsync(user);
var passwordChangeResult = await _userManager.ResetPasswordAsync(user,
      token,
      password);
```

My code however is embedded in a larger codebase that is not using `UserManager<AppUser>` to get users, which might be an issue. If so, could you point me to the right documentation? Is that an anti-pattern?

**Comment by FM1973** [comment]
The same for i.e. CheckPasswordAsync

**Comment by ancailliau** [comment]
Indeed, although my code was using the `UserManager` there to get the user.

**Comment by FM1973** [comment]
Well, I solved this by using
` var user = await _userManager.FindByNameAsync(model.UserName);//`
instead of my own UserService.
But I think the behavior of usermanager is wrong or at least it hasen´t been like this in .net 6.

**Comment by HaoK** [comment]
That is the expected pattern, you should always use one of the FindXyz apis to get the user from identity before calling into any of the other operations.  Otherwise the tracking might get messed up.
