### ISSUE TITLE
HttpResponse Doesn't Allow Negative Value for Cookie Max-Age

### ISSUE THREAD

**Issue by samueleaton** [dotnet/aspnetcore#45045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to the [IETF HTTP Working Group RFC 6265](https://httpwg.org/specs/rfc6265.html#max-age-attribute), the Max-Age cookie attribute can be negative.

[Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#max-agenumber) says that if Max-Age is zero or negative, then the cookie should be expire immediately.

It appears [the code](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Headers/src/SetCookieHeaderValue.cs#L203) is enforcing a non-negative number: `maxAge = HeaderUtilities.FormatNonNegativeInt64(...)`. 

(That may not be the right code)

### Expected Behavior

It should not raise an exception for negative Max-Age values, which would normally expire the cookie on the client (useful for deleting a cookie).

### Steps To Reproduce

Happens when doing:

`ctx.Response.Cookies.Append(cookie.Name, cookie.Value, setCookieOpts)`

where `ctx` is an `HttpContext` object and `Cookies` is an `IResponseCookies` interface.

[Documentation here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iresponsecookies.append?view=aspnetcore-7.0#microsoft-aspnetcore-http-iresponsecookies-append(system-string-system-string-microsoft-aspnetcore-http-cookieoptions)).

### Exceptions (if any)

When trying to set a negative Max-Age value (for an immediately expired cookie) I get the following error:

```
System.ArgumentOutOfRangeException: The value to be formatted must be non-negative. (Parameter 'value')
Actual value was -36000.
   at Microsoft.Net.Http.Headers.HeaderUtilities.FormatNonNegativeInt64(Int64 value)
   at Microsoft.Net.Http.Headers.SetCookieHeaderValue.ToString()
   at Microsoft.AspNetCore.Http.ResponseCookies.Append(String key, String value, CookieOptions options)
```

### .NET Version

6.0.302

**Comment by adityamandaleeka** [comment]
Thanks @samueleaton. We'd take a PR for addressing this if you're interested.

**Comment by samueleaton** [comment]
Hey @adityamandaleeka I would but I'm an F# guy with little C# experience. I can see how difficult it'd be to try setting up the env.

**Comment by Tratcher** [comment]
No worries @samueleaton, someone already took care of it.
