### ISSUE TITLE
QuickGrid: when navigating from the page hosting the grid , it calls grid Items , casing "A second operation was started on this context instance before ..." 

### ISSUE THREAD

**Issue by Hanisafa** [dotnet/aspnetcore#45059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i have a QuickGrid that is using QuickGridEntityFrameworkAdapter , 

`<QuickGrid Items="FilteredPrintOrders" Class="table mt-3"
           ResizableColumns="true"`

```csharp
    IQueryable<PrintOrder> FilteredPrintOrders
    {
        get
        {
            //if (DontFilter)
            //{
            //    return null;

            //}

            IQueryable<PrintOrder> q = _db.PrintOrderSet?.Include(c => c.Customar).Include(c => c.PrintShop);

            if (!string.IsNullOrEmpty(OrderNumberFilter))
            {
                q = q.Where(c => c.Number.Contains(OrderNumberFilter));
            }

            if (FromFilter != null)
            {
                q = q.Where(p => p.Date.Value.Date >= FromFilter.Value.Date);
            }
            if (ToFilter != null)
            {
                q = q.Where(p => p.Date.Value.Date <= ToFilter.Value.Date);
            }
            return q;
        }
    }

```

when navigating to new page , the QuickGrid call FilteredPrintOrders , casing an exception on the second page that i navigate to 
"A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext."

the second page has a call to EF in the onIntilize event 

### Expected Behavior

dont call its items when page is navigating or a way to stop it

AS A work around , i had to add a switch 

` if (DontFilter)
 {
            return null;
}`

that i set before i navigate 

### .NET Version

6

**Comment by TanayParikh** [comment]
The following guidance may help resolve your issue. Please feel free to re-open this issue if you're still running into this problem.

https://learn.microsoft.com/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0#scope-to-the-component-lifetime
