### ISSUE TITLE
[BUG] Quick grid does not render in .net 7 blazor server project.

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#45061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I create a brand new balzor server side project and add the quick grid and the data is not getting populated in the grid the formatting two is wrong on the columns its not reconising the lambada in the Field name.

![image](https://user-images.githubusercontent.com/5619229/201521698-b7d0beb2-fe41-457d-a8af-1a41d6e14cac.png)

My Class
 
     public class Players
     {   
        public int Id { get; set; }
        public int? Type { get; set; }
        public int? OrginizationId { get; set; }
    
        public int? PersonId { get; set; }
        public int? CoachId { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? TeamId { get; set; }
        public string? PlayerLevel { get; set; }
        public string? FullName
        {
            get { return FirstName + " " + Surname; }
        } 
     }

You will see here is my methods

     <QuickGrid Items="@playersList">  
       <PropertyColumn    Property="@nameof(c => c.)" Sortable="true"  />         
     </QuickGrid>
    @code {
  
      public IQueryable<Players> playersList { get; set; }
  
      protected override async Task OnInitializedAsync()
      {
          TheHockeyLabMnHttpApi api;
          ThehockeylABSqlLiteDB db;
          db = new ThehockeylABSqlLiteDB();
          api = new TheHockeyLabMnHttpApi();
          User myuser = new User();
          myuser.Username = "davidbuckleyweb@outlook.com";
          myuser.Password = "Test12345!";
  
          api.AuthenicateUser(myuser);
          Authentication auth = new Authentication();
          auth.Email = myuser.Username;
          myuser.Password = myuser.Password;
          string jwtTown =await  api.GenerateBarrerToken(myuser);
          auth.JWTToken = jwtTown;
          db.SaveAutheneticationAysnc(auth);
  
          playersList = await api.GetALLPlayersQueryable();
  
      }

My Api Call is follows

        public async Task<IQueryable<Players>> GetALLPlayersQueryable()
        {
            List<Players> _result = new List<Players>();
            EnsureHttpClientCreated();
            var uri = new Uri(string.Format(Constants.BaseUrl + Constants.ApiSegmant + Constants.GetAllPlayers, string.Empty));
            AddAuthenicationHeader();

            var response = await httpClient.GetAsync(uri);

            if (response.IsSuccessStatusCode)
            {
                var byteArray = await response.Content.ReadAsByteArrayAsync();

                var content = Encoding.UTF8.GetString(byteArray, 0, byteArray.Length);
                _result = JsonConvert.DeserializeObject<List<Players>>(content);
            }

            return _result.AsQueryable();

        }

I do not no what is wrong as it brings back loads of records as follows

![image](https://user-images.githubusercontent.com/5619229/201521756-3b99d351-7968-4344-a253-69f9f870effd.png)

Visual Studio version is 

![image](https://user-images.githubusercontent.com/5619229/201521772-302992d6-3f58-4f2d-9485-f8888073f39e.png)

CS Project

    <Project Sdk="Microsoft.NET.Sdk.Web">

      <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="0.1.0-alpha.22351.1" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
	      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.0" />
	      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="7.0.0" />
	      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.0" />
	      <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.1" />
	      <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.2" />
	      <PackageReference Include="Syncfusion.Blazor.Core" Version="20.3.0.56" />
	      <PackageReference Include="Syncfusion.Blazor.Grid" Version="20.3.0.56" />
      </ItemGroup>

      <ItemGroup>
        <ProjectReference Include="..\TheHockeyLabMn.Bal\TheHockeyLabMn.Bal.csproj" />
        <ProjectReference Include="..\TheHockeyLabMn.Dal\TheHockeyLabMn.Dal.csproj" />
        <ProjectReference Include="..\TheHockeyLabMn.Models\TheHockeyLabMn.Models.csproj" />
        <ProjectReference Include="..\TheHockeyLabMn.Services\TheHockeyLabMn.Services.csproj" />
      </ItemGroup>
	
    </Project>

### Expected Behavior

The grid should appear and create a grid with the column FullName instead the grid remains not showing on the screen.
There is data in my list

### Steps To Reproduce

Create a brand new Balzor server project
Add the quick grid
Create an api call to some fake data
run grid will be empty

**Comment by thekim1** [comment]
You need to add: @using Microsoft.AspNetCore.Components.QuickGrid to the razorcomponent if it's not set as a global using.
In the PropertyColumn you dont need nameof. If you want to change the title for the field you can use Title="Example Title"

**Comment by TanayParikh** [comment]
Thanks for reaching out. We recommend following the guidance available at https://aspnet.github.io/quickgridsamples/getstarted/ for further details. The usage of a lambda with `nameof` also seems potentially problematic.

**Comment by danroth27** [comment]
The `Property` parameter of `PropertyColumn` doesn't take a string. It take an expression to identify the property it handles. No need to use `nameof`. Something like this:

```razor
 <QuickGrid Items="playersList">  
   <PropertyColumn Property="player => player.FullName" Sortable="true"  />         
 </QuickGrid>
````
