### ISSUE TITLE
IHttpContextAccessor.HttContext Session throws Exception when not enabled 

### ISSUE THREAD

**Issue by fireholster** [dotnet/aspnetcore#45067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

** This looks like a Bug But you guys can confirm**

Issue: When session is not enabled the IHttpContextAccessor.HttContext.Session throws and exception instead of simply returning 'null' 
Why we are looking for it: We have a net 6 class lib and an auth handler that utilizes session (if it is enabled) to save some details. Now with this exception, api's that choose to not use session fails as this spits out an exception instead of staying null. 

### Expected Behavior

I think the expected behavior should be

Session and Context Accessor is not enabled in middleware and app is not using session
Return the session as 'null' instead of it throwing exception.

### Steps To Reproduce

Create a Net 6 Web API 
  - No AddSession in Services
  - No AddHttpContextAccessor in Services
  - No UseSession in app
 
Create a Net 6 Class Lib

  Create a Custom Auth Attribute and using a requirement.
  Inject IHttpContextAccessor in the handler
  Try Accessing accessor.HttpContext.Session

### Exceptions (if any)

returning a 500 

### .NET Version

6

### Anything else?

If we access the HttpContext in Debug the session does get initialized as null..Which tells me that is the intended behavior. So please correct this.

**Comment by Tratcher** [comment]
This exception? That's by design.
https://github.com/dotnet/aspnetcore/blob/85f5fe5dbfc3769449b551e9b23450acb2fda25a/src/Http/Http/src/DefaultHttpContext.cs#L200-L201

If you want to conditionally access session then check for HttpContext.Features.Get<ISessionFeature>().
