### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#45078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@javiercn I believe that closing #45031 is an inappropriate close.

1) The three project references that are mentioned are all in another WASM project that is successfully built/run

2) The reference to obj\project.assets.json is not particularly useful. It is a a 2600 line file. If I knew what to search for it might be useful but the reference to the failing project ICEBG.Blazor shows nothing extraordinary.

3) I think you should consider conferring with @mkArtakMSFT who opened #28478 for this very issue which went on to be resolved. If it was resolved then the behavior that I am seeing is a regression. I can see that @pranavkm did the original work.

4) Since the issue is with dotnet tooling I would think you could do the research as to where the issue needs to get moved. You can't possibly expect someone outside of Microsoft to know how things are structured.

5) And it is absolutely the responsibility of the tooling to provide adequate error messages. Right now it is showing the equivalent of 'build broken -- good luck"

Needless to say I am very disappointed in  how this issue has been handled.

### Expected Behavior

See #45031

### Steps To Reproduce

See #45031

**Comment by javiercn** [comment]
@MarkStega thanks for contacting us.

> Needless to say, I am very disappointed in how this issue has been handled.

I apologize, we normally go through a lot of issues and sometimes we miss things as we try to give people a fast response.

> I think you should consider conferring with @mkArtakMSFT who opened https://github.com/dotnet/aspnetcore/issues/28478 for this very issue which went on to be resolved. If it was resolved, then the behavior that I am seeing is a regression. I can see that @pranavkm did the original work.

 I took a second look and from what I can tell, we had a check at some point, but we removed it, although I am not sure if accidentally or intentionally. That said, this should in any case be a nuget/runtime feature, not something we us in Blazor do. They are the only ones that can trace the dependency chain.

> 5\. And it is absolutely the responsibility of the tooling to provide adequate error messages. Right now it is showing the equivalent of 'build broken -- good luck"

The framework does its best to give you a good error message, but there is a limit of what it reasonably can do.

> 2\. The reference to obj\project.assets.json is not particularly useful. It is a 2600-line file. If I knew what to search for it might be useful but the reference to the failing project ICEBG.Blazor shows nothing extraordinary.

Your issue comes from your reference to `SystemFramework/1.0.0`. As to how I found out, I opened your file, searched for `Microsoft.AspNetCore.App`, that pointed me to `Microsoft.AspNetCore.Components.WebAssembly.Server`, searched for that and that turned to be

![image](https://user-images.githubusercontent.com/6995051/201703610-583ec1ba-8d66-4ce4-a477-4abc1f3de8bd.png)

> 4\. Since the issue is with dotnet tooling I would think you could do the research as to where the issue needs to get moved. You can't possibly expect someone outside of Microsoft to know how things are structured.

I was giving you alternative forums you could query to get a faster and better answer.

Hope this helps.

**Comment by MarkStega** [comment]
@javiercn Thanks for the additional help & second look. I actually found a second reference to ...WebAssembly.Server. When I removed that reference the build still failed with the same error. I followed the 'standard' option of deleting all bin & obj directories and then the build worked. So something was cached.

If it turns out that the tooling does not get upgraded to help more with the error it would be useful if there was documentation on your technique of using project.assets.json.

**Comment by imprathamesh** [comment]
i m getting this same issue. i bought new laptop, the projects that are work in my previous laptop are not working in new laptop.
i tried to delete this bin vs and obj folder also ran dotnet restore command on all project and did repair visual studio 2022 but this still not working. 

VS version 17.4.1 
sdk : net 6.0.11 and 7

**Comment by MarkStega** [comment]
@imprathamesh If you follow the advice of @javiercn in the second reply it is relatively easy to track the issue down. As I said, not as helpful as an improved error message, but straightforward and it works.

**Comment by dougbu** [comment]
@javiercn I'm assigning to you since this has been sitting w/o an owner and not on (say) the DoI dashboard for a few days.

**Comment by MarkStega** [comment]
@javiercn  I'd still like to have this forwarded to the appropriate team for consideration. But as an issue your methodology worked fine and I have no need of further help.

**Comment by mkArtakMSFT** [comment]
@javiercn are there any specific actions on us here (including infrastructure related)?

**Comment by javiercn** [comment]
@mkArtakMSFT I don't think so. At best we could ask nuget or VS to build a feature, but it's not something we should be handling at our layer.
