### ISSUE TITLE
CSS Isolation: ability to use root scope

### ISSUE THREAD

**Issue by valentynpopov** [dotnet/aspnetcore#45072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to leverage bundling & minification capabilities of CSS Isolation feature, as well as use nested CSS (*.cshtml.css) files to organize my project.

However, I don't need to actually use the CSS scope, i.e. ideally I'd like to get rid of the custom HTML attribute (like b-3xxtam6d07) being added by CSS Isolation.   I know it's possible to customize this attribute by using config like this:

```
<ItemGroup>
  <None Update="Pages/BaseComponent.razor.css" CssScope="custom-scope-identifier" />
</ItemGroup>
```

But it doesn't seem to be possible to get rid of the attribute altogether. When I try specifying an empty CssScope, it falls back to an automatically generated attribute like like b-3xxtam6d07.

### Describe the solution you'd like

Perhaps it would be possible to use a new configuration setting, something like  UseRootCssScope or DisableCssScope? See example below:

```
<ItemGroup>
  <None Update="Pages/BaseComponent.razor.css" DisableCssScope="true" />
</ItemGroup>
```

That would mean that the content of such CSS file is still bundled and minified, but without amending a custom HTML attribute to each CSS rule.

An alternative, but less flexible solution would be to add a new global setting similar to the existing ScopedCssEnabled. Instead of disabling the whole feature completely it would only disable the custom HTML attribute bit.

**Comment by valentynpopov** [comment]
I've found a workaround: instead using an empty CSS scope `<None Update="Views/*/*.cshtml.css" CssScope=" " />` I can use a whitespace: `<None Update="Views/*/*.cshtml.css" CssScope=" " />`

That keep HTML output clean, i.e. no custom HTML attribute is being added to tags. There a couple of issues with this using the whitespace though:
- Although the generated HTML output is clean now, the generated CSS is not: CSS selectors now contain 'empty attributes' like `a[ ] { color: #0077cc; }`
- More importantly, this is an undocumented behaviour, and I am worried that future versions might start treating the whitespace in the same way as an empty setting, i.e. will start falling back to automatically generated "b-..." HTML attribute

**Comment by javiercn** [comment]
@valentynpopov thanks for contacting us.

It's not clear what you are trying to achieve. If you want to, you can disable the feature altogether like this https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0#disable-css-isolation

Then you can do your own bundling and minification of the CSS files.

> I am trying to leverage bundling & minification capabilities of CSS Isolation feature, as well as use nested CSS (*.cshtml.css) files to organize my project.

This is not something that we support, nor we plan to support in the future. We are able to bundle the files because each file is guaranteed to be scoped to the associated razor file. If that is not the case, you are going to get unexpected results, as the order we bundle the files is nondeterministic and might change in the future.

**Comment by valentynpopov** [comment]
@javiercn Yeah, you're right. The fact that the bundling order is non-deterministic makes it dangerous to add such a feature.

In this case you should probably make it impossible using a whitespace as CssScope: either raise a compiler error, or fall back to the default "b-..." scope (as you do with an empty CssScope). At the moment using the whitespace stops custom HTML attribute from being added to the tags..

**Comment by javiercn** [comment]
> In this case you should probably make it impossible using a whitespace as CssScope: either raise a compiler error, or fall back to the default "b-..." scope (as you do with an empty CssScope). At the moment using the whitespace stops custom HTML attribute from being added to the tags..

That is fair, but using a custom defined scope is already somewhat of a niche scenario that I am not sure it is worth the trouble.
