### ISSUE TITLE
Allow QuickGrid columns to be put in user-defined razor components.

### ISSUE THREAD

**Issue by Mike-Wodarczyk** [dotnet/aspnetcore#45088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to put a PropertyColumn in a user-defined razor component where I can define formatting, filtering, and custom header settings for re-use across multiple columns.  When I do this, the code compiles and runs, but the column does not show up in the QuickGrid as it should.  The column is silently removed from the table.

The problem is that the ColumnBase's razor code is nested too many levels deep.  It looks like Blazor does a breath first build of the render tree and if the <table> element is started before the ColumnBase code to AddColumn() is reached, then the column is not rendered.  The <Defer> element in QuickGrid.razor is used so that the build in PropertyColumn works, but <Defer> only allows ColumnBase sub-classes to be 1 level below the <QuickGrid> component.

I have a Blazor Web assembly project to demonstrate the problem.   https://github.com/Mike-Wodarczyk/QuickGridDepthTest
It contains a 3 column table on the main page.  One column "Last Name 0 Depth" is directly below the <QuickGrid> element and it renders correctly.  There are 2 more columns, "First Name 1 Deep" and "Middle Name 2 Deep", nested below 1 and 2 levels of user-defined razor.  Neither of these columns appear under the current QuickGrid code.

The problem also happens if you sub-class PropertyColumn and don't directly call "base.BuildRenderTree(__builder); " from the sub-class's razor code.  

### Describe the solution you'd like

I would like QuickGrid to <Defer> rendering the table until all user columns nested under 1, 2, or more levels of user-defined razor code are added to the table so that they show up.

I have a branch of the QuickGrid code at:  https://github.com/Mike-Wodarczyk/AspLabs/tree/main/src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid
which demonstrates that increasing the <Defer> depth can fix the issue.

The code adds a render tree depth counter to count the depth of columns added up to a configurable max (default 5) levels of nesting.   Then the <Defer> element is added with that level of nesting so that the columns appear in the table.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
