### ISSUE TITLE
.Net 7 - Json Serialization Case issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#45094]
I have this dto:
````csharp
public class Filter
{
    //[JsonPropertyName("Id")]
    public string Id { get; set; } = default!;

    //[JsonPropertyName("Name")]
    public string Name { get; set; }

    //[JsonPropertyName("order")]
    //public int Order { get; set; }

    [JsonPropertyName("DataType")]
    public PropertyDataType DataType { get; set; }

    [JsonPropertyName("Unit")]
    public PropertyUnit Unit { get; set; }

    [JsonPropertyName("Values")]
    public ICollection<FilterValue> Values { get; set; } = Array.Empty<FilterValue>();

    public string UnitToString() => Unit switch
    {
        PropertyUnit.Centimeter => "cm",
        PropertyUnit.Kilogram => "kg",
        _ => string.Empty,
    };
}
````
Producing this json:

````json
{
    "id": "Gender",
    "name": "Sexe",
    "DataType": 1,
    "Unit": 0,
    "Values": []
````

All properties should have PascalCase, but as you can see all properties without [JsonPropertyName] have camelCase.

**Comment by martincostello** [comment]
The ASP.NET Core defaults for JSON use camel case, so the behaviour you are seeing is by design: https://github.com/dotnet/aspnetcore/blob/2e1ddec4d727360746937e7a18a856ceb90e8b05/src/Mvc/Mvc.Core/src/JsonOptions.cs#L34

You need to configure the options yourself if you want to default to Pascal case.

**Comment by davidfowl** [comment]
This is by design as @martincostello said, if you want control it, you can set the global json options.

**Comment by ravi-kakadiya** [comment]
@Julien-Marpault You can set your own naming convention by override `JsonNamingPolicy.ConvertName(string name)` method
