### ISSUE TITLE
NET 6 Blazor WASM Hosted - Query diminishing performance

### ISSUE THREAD

**Issue by ddfxraven** [dotnet/aspnetcore#45100]
ASP.NET 6 Blazor WASM Hosted model on an Azure Linux B2 instance. The database is Azure SQL DTU50.

We having an issue where over time the product search returns slower and slower results until it eventually just times out (can take just a day or 2 for the performance drop). It is currently using OData controller (before we had a ApiController with the issue and tried OData to see if there was a difference) to call a SQL query which uses catalog index to return ranked results (the SQL call is using dapper). 

In general in a week there's around 2000 searches. On the SQL server directly we can run this 20000 times in a row and have fast responses. We created a test case in VS to loop 20000 times using mock controller and the query also does not take longer than 100ms to return. But when the site is hosted the performance to that specific query gets slower, but all the other queries are fine and then rest of the webapplication works.

We investigated the SQL heavily and have routine Index and Statistics scripts to ensure everything is up to date, so our only area is pointing to the WASM Hosted somehow being the issue.

**If we drop and create or even just run Alter on the stored procedure (without changing anything) the application comes right and the speed of the search returns to normal.** 

The SQL connection is in a using block, and we manually called Dispose to see if it was holding the connections. Application Insights on both the App service and SQL hasn't shown any issues.

Is there any known issue that would cause this?

**Comment by ddfxraven** [comment]
Hi @javiercn Its Blazor WASM Hosted, so the API is coupled with the application in Azure app service. The query runs fine in the database directly. We've done extensive testing on the database side, the issue only occurs from the published application.

As I said above we've run a mock controller call from a unit test to try simulate it the same but hitting it with many more calls than users would do (with the database still being in Azure SQL) and the issue doesn't occur.

**Comment by javiercn** [comment]
> As I said above we've run a mock controller call from a unit test to try simulate it the same but hitting it with many more calls than users would do (with the database still being in Azure SQL) and the issue doesn't occur.

Instead of the unit test, stand up the real server and test against that from the API. Collect a trace with perfview/VS and measure where the time is being spent.

**Comment by houbi56** [comment]
I would investigate the sql query plan cache. Altering the procedure would through the query plan out of the cache. 
https://www.sommarskog.se/query-plan-mysteries.html
