### ISSUE TITLE
Lazy loaded `BlazorCustomElements.js` file does not adhere to the `loadBootResource` configuration

### ISSUE THREAD

**Issue by martinlingstuyl** [dotnet/aspnetcore#45104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys,

Since .NET 7 is out, I've been test driving Blazor WASM to see how to use it in combination with other frameworks.

I've configured the following to be able to point the loading of resources to a specific server.
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources

Which works nicely.

I'm now using the `Microsoft.AspNetCore.Components.CustomElements` nuget package to get CustomElements to work.
Initially you had to reference the script manually:

```html
<script src="_content/Microsoft.AspNetCore.Components.CustomElements/BlazorCustomElements.js"></script>
```

But since .NET 7 has been released it's lazy loaded by ASP.NET. Which is awesome. The only problem is: it uses the URL of the server you are on, to lazy load the file, while it should be respecting the `loadBootResource` configuration.

Which is a problem for me, as I'm depending on the `loadBootResource` function to get the WASM files from another server, for example a CDN.

Is that something you guys can fix? 

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27638

### Expected Behavior

Loading the JS for CustomElements should respect the `loadBootResource` configuration.

### Steps To Reproduce

1. Create a Blazor WASM client app
2. Create a simple webserver that loads the Blazor script with `autostart="false"` and add the following bootstrapping lines:

```javascript
Blazor.start({
        loadBootResource: function (type, name, defaultUri, integrity) {
          return 'https://localhost:8088/' + defaultUri`;
        }
      });
```

3. Install the CustomElements nuget and implement a basic customelement. 
4. Try loading the basic webserver with the customelement and blazor script.

### .NET Version

7

**Comment by SteveSandersonMS** [comment]
I understand why it might be confusing, but JavaScript files loaded via dynamic import (i.e., invoking `import` in a JS interop call) are **not** Blazor boot resources, so their loading process will not be affected by `loadBootResource` customization. That's not a bug, it's just that `loadBootResource` doesn't get to control anything other than boot resources whose loading is triggered by Blazor itself.

We could theoretically add an extensibility point that overrides what a JS interop call to `invokeAsync('import', 'some/url')` does, but there isn't any such extensibility point today. If that sounds like what you'd want, please consider filing an issue to request that as a more general feature.

Note that you would have the same issue if you were using any JavaScript library that did dynamic imports - you wouldn't have a way to change the URL it imports from.

**Comment by martinlingstuyl** [comment]
Hi @SteveSandersonMS, 

Ok, so you're saying it's not literally a boot resource and that this just is how dynamic imports work.

It is a dependency that blazor needs though. And a quite fundamental one as well. You probably see my point, that it is a bit odd how it currently works. 
It's not just odd, it's blocking the use of the feature. CustomElements are (how I see it) specifically useful in integration scenarios with other applications.

If dynamic imports will not fix this, I'd say: let me be in control and allow me to disable loading the scriptfile dynamically. I'm perfectly fine with loading it from the proper place myself, that would be an acceptable workaround for me as well.

**Comment by martinlingstuyl** [comment]
Hi @SteveSandersonMS,

The bot closed the issue. But it's a bit unclear to me now as to what the follow-up action is. 
If it's on the backlog, should the issue not remain open till it's fixed?

**Comment by SteveSandersonMS** [comment]
I've filed an issue describing this as a general feature request: https://github.com/dotnet/aspnetcore/issues/45148

A more practical solution for you in the short term would be to implement a service worker that will let you override how all static resources are fetched.

**Comment by martinlingstuyl** [comment]
Thanks!
