### ISSUE TITLE
Give support of writing typescript instead just JavaScript in inline script for .cshtml pages. Also allow to have inheritance there as code can be re-used in all pages.

### ISSUE THREAD

**Issue by ranjit-singh-eva-bbsr** [dotnet/aspnetcore#45103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I often write JavaScript code for my .cshtml pages and sometime even a minor mistake of missing ;(terminator) confuse as what has really wrong and kills time. Even console of browser does not help to know the issues.

I think if we could use typescript as an substitute of JavaScript, our life would have been easy to use not just intellisens but to avoid issues we often face to due to no datatype there.

I managed to write it separately but as it does not support inheritance, code is required to be copy and page each time and its getting huge in size.  The project size is huge, and I cannot convert it to Blazor so please think about it.

### Describe the solution you'd like

Give support of typescript instead of just JavaScript in .cshtml to deal client side changes.

### Additional context

Having typescript, we can utilize the power of OOPS in real mean if it starts helping to code re-use like we see node people do for their project.

**Comment by javiercn** [comment]
@ranjit-singh-eva-bbsr thanks for contacting us.

Unfortunately, this is not something that we plan to do. Adding support for typescript inline requires integrating the Razor compiler with the Typescript compiler which would require a large number of resources and maintenance for limited value.

> I managed to write it separately but as it does not support inheritance, code is required to be copy and page each time and its getting huge in size. The project size is huge, and I cannot convert it to Blazor so please think about it.

I am not sure what you mean by this, but we would recommend you put the code in a separate file, compile it, and load it where you need it.
