### ISSUE TITLE
BuildFromSource Windows Activate for VS

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#45119]
https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#visual-studio-on-windows

The Windows VS instructions don't require `. ./activate.ps1`. Is that intentional? cc/ @captainsafia

**Comment by captainsafia** [comment]
Yes, `startvs.cmd` takes care of both activating the local .NET install and launching VS.
