### ISSUE TITLE
Updated packages for 'Microsoft.AspNetCore.Authentication.*'

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/aspnetcore#45128]
Team,
Really confused with this one. If you look at the current packages on NuGet for `Microsoft.AspNetCore.Authentication.*`, you will notice that while a large number of packages are versioned for 6.x and even 7.x, there are still quite a few (like [Microsoft.AspNetCore.Authentication.Cookies](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Cookies) ) that are still versioned 2.x and report .NET Standard 2.0. Even their "built from" source tree link on NuGet points to now-archived repos here on Github.

However, the commit history for those source trees on **this** repo have commits as new as in the recent 2-3 months. So where are the packages for these?

- Microsoft.AspNetCore.Authentication.Core
- Microsoft.AspNetCore.Authentication
- Microsoft.AspNetCore.Authentication.Cookies

Thanks!

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-7.0&tabs=visual-studio#remove-obsolete-package-references

**Comment by sujayvsarma** [comment]
Thank you @Tratcher ! I found that solution separately and thats what I ended up doing.
