### ISSUE TITLE
Running dotnet watch fails due to System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#45129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running `dotnet watch` fails due to System.IO.FileNotFoundException in ASP.NET Core 6.0.10 project

### Expected Behavior

`dotnet watch` should start successfully

### Steps To Reproduce

1. Open terminal
2. Go to project directory
3. Execute `dotnet watch` command
4. Receive error

### Exceptions (if any)

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
dotnet watch ❌ Exited with error code 134

### .NET Version

7.0.100

### Anything else?

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by mkArtakMSFT** [comment]
@mrlife I believe you can pin the SDK using global.json and that will unblock you for now.

**Comment by tmat** [comment]
Yup. Dup of https://github.com/aspnet/AspNetCore-ManualTests/issues/1635.

**Comment by mrlife** [comment]
@mkArtakMSFT Thank you for the workaround.

@tmat Is that a private repo?

**Comment by tmat** [comment]
Oh, I did not notice. Let's link this issue as well instead.
