### ISSUE TITLE
ExceptionHandlerMiddleware should be able to include HTTP Headers from original requests

### ISSUE THREAD

**Issue by yanxiaodi** [dotnet/aspnetcore#45137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The current `ExceptionHandlerMiddleware` allows us to get some information of the HttpContext by using `IExceptionHandlerFeature`, such as `Path`, `RouteValues`, etc. However, it does not include the HttpHeaders of the original request.

In my app, I have a middleware to check the `correlation-id` header from the inbound request. If any exception occurs during the request, I can use the `ExceptionHandlerMiddleware` to return a `ProblemDetails` response. But the `correlation-id` is lost. I would like to know which request caused the exception. Even I can get the exception detail from the `ExceptionHandlerMiddleware` response, but I cannot get the original HttpHeaders. I want to include the `correlation-id` (and some other headers) in the logs.

A similar issue: https://github.com/dotnet/aspnetcore/issues/26574

### Describe the solution you'd like

The `IExceptionHandlerFeature` instance can include the HttpHeaders of the original request (and response?) Or provide another class where we can find the original HttpHeaders.

I think it can be added here: https://github.com/dotnet/aspnetcore/blob/442ca2f02e5bfa9b8e5b09de6d088de5ed9e1dc5/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L130

I'm happy to discuss more if the request is not clear and contribute to the feature if possible.

**Comment by Tratcher** [comment]
Where are you accessing the IExceptionHandlerFeature? It should only be accessible from places where you also have access to the original HttpContext and HttpRequest. Copying the request headers to the error feature would be redundant.

**Comment by yanxiaodi** [comment]
Oh yes. Found it. Thanks @Tratcher !
