### ISSUE TITLE
.NET 7 Blazor WASM authentication back button history issue #45097 re-open request

### ISSUE THREAD

**Issue by mikequ-taggysoft** [dotnet/aspnetcore#45132]
@javiercn It looks the bot marked that the issue  #45097 was marked resolved before I replied to your comment and then it got closed by bot. But unfortunately, the code you provided didn't work for me as I mentioned in my last response there (the `ToState()` method being internal). Can you kindly take another look for me in that issue and possibly re-open it? Thanks!

**Comment by javiercn** [comment]
@mikequ-taggysoft thanks for the additional details.

I did not realize the method is internal. You can instead call `JsonSerializer.Serialize(interactiverequestoptions);` and should do the same.
