### ISSUE TITLE
Enable JSON format output for `user-jwts list`

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#45141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to retrieve a list of known jwt tokens created via `user-jwts` for my project. This is helpful for integration testing but also to create some better tooling around this type of information in certain experiences.  The current `list` output is readable in terminal but is not easy to parse programmatically.

### Describe the solution you'd like

The `create` has an `-o json` option and I simply would like to do `user-jwts list -o json` (and variant so `user-jwts list --show-tokens -o json`)

**Comment by BrennanConroy** [comment]
Similar to how we added support for json output when creating a token in https://github.com/dotnet/aspnetcore/pull/42249

**Comment by timheuer** [comment]
@rafikiassumani-msft -- any reason why we have to wait for 8 for this?

**Comment by captainsafia** [comment]
> @rafikiassumani-msft -- any reason why we have to wait for 8 for this?

We discussed backporting this. Our standard approach at the moment is to add a feature in 8.0 and backport to 7.0 when servicing branches open.

**Comment by timheuer** [comment]
Excellent. I had thought we already had branch for SDK for 7.0.200 (I assume this doesn’t need runtime servicing)

**Comment by captainsafia** [comment]
Closing as completed.
