### ISSUE TITLE
Web Finger (RFC7033) middleware

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#45143]
## Summary

Proposal to add middleware to support for the Web Finger protocol ([RFC7033](https://www.rfc-editor.org/rfc/rfc7033)). Web Finger is a _well-known_ endpoint on a HTTP server that returns a JSON Resource Descriptor ([RFC6415](https://www.rfc-editor.org/rfc/rfc6415)) with information about resources on that server.

## Motivation and goals

Web Finger is a foundational technology in emerging social media platforms (such as [Mastodon](https://docs.joinmastodon.org/spec/webfinger/)). One canonical example of use of Web Finger is discovery of Open ID Connect issuer information as part of modern authentication flows ([Open ID Provider Issuer Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery)).

Whilst not limited to authentication scenarios Web Finger is an important step in supporting modern decentralized authentication methods and would likely be used not only for initial issuer discovery but also supporting mechanisms like key change to remove the need for out-of-band app registration for ad-hoc authentication scenarios.

The goal of adding this middleware would be to create some baseline plumbing on which can support future authentication standards work and also facilitate building social experiences on top of ASP.NET Core.

## In scope

The scope of this design proposal is to implement the middleware to expose the well-known Web Finger endpoint (e.g. ```/.well-known/webfinger```) which exposes links which are contributed by resolvers which are executed upon each request to the endpoint.

## Out of scope

This proposal does not include work to extend our existing authentication middleware or identity implementation. It simply builds the base plumbing that these services might contribute metadata to in the future.

## Risks / unknowns

There are a few risks that adopters of web finger need to consider, such as inadvertently leaking sensitive information. It's very much focused on open web principles which won't be appropriate in every application.

In the context of modern authentication standards, some of the problem space still doesn't have solutions. For example, it isn't clear if there is a standardized key exchange mechanism that OIDC relying parties and IdPs can use to avoid the need for every IdP and RP to pre-share registration information.

## Examples

Here is an example of what wiring up web finger support in an ASP.NET Core application might look like:

```csharp
using Microsoft.AspNetCore.WebFinger;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddWebFinger(options => {
  options.RegisterResolver<MyWebFingerResolver>()
});

var app = builder.Build();
app.UseWebFinger(); // Add web finger middleware.

// Map endpoints.

app.Run();
```

A resolver would be an interface that defines a method, something like this:

```csharp
public interface IWebFingerResolver
{
    Task ResolveAsync(WebFingerResolutionContext context, CancellationToken cancellationToken)
}
```

The idea here is that the resolver is ultimately added to DI as a scoped service and when a request comes it the resolves can make use of other services to do their work. The ```WebFingerResolutionContext``` would expose the resource name and relation type that is being resolved if they are supplied, and also provide a method to register links/aliases which are put into the response. An example implementation might look like this:

```csharp
public class MyWebFingerResolver : IWebFingerResolver
{
    private IRepository<Organization> _organizations;

    public MyWebFingerResolver(IRepository<Organization> organizations)
    {
        _organizations = organizations;
    }

    public async Task ResolveAsync(WebFingerResolutionContext context, CancellationToken cancellationToken)
    {
        var organization = await organizations.FindAsync(context.Resource);
        context.AddAlias(organization.LegalName);
        context.AddAlias(organization.Abn);
        context.AddLink("https://schemas.ato.gov.au/organization", "text/html", "https://ato.gov.au/organizations/abn123");
    }
}
```

Other middlewares could internally register their own resolvers too (a good example would be auth and identity) but you'd almost certainly want it to be opt-in using their respective configuration methods. For example, a developer could expose a property on their user identity which opts them into web-finger:

```csharp
builder.Services.AddIdentity<MyUser, MyRole>(options =>
{
    options.WebFinger.OptIn = async (user) => user.IsDiscoverable;
});
```

**Comment by vanillajonathan** [comment]
Good proposal!
If not more than one resolver is needed, then maybe it could be added like:
```cs
builder.Services.AddWebFinger<MyWebFingerResolver>();
```

Since there is no WebFinger implementation yet, here is one if anyone needs one:
<details>
    <summary>Click here to expand code</summary>

File `WebfingerController.cs`:

```cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using PostHat.Data;
using System.Text.Json.Serialization;

namespace Example.Controllers;

/// <summary>
/// WebFinger can be used to discover information about people or other entities.
/// </summary>
/// <remarks>https://datatracker.ietf.org/doc/html/rfc7033</remarks>
[Route("/.well-known/webfinger")]
[ApiController]
[RequireHttps]
public class WebfingerController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly ApplicationOptions _options;

    public WebfingerController(ApplicationDbContext context, IOptions<ApplicationOptions> options)
    {
        _context = context;
        _options = options.Value;
    }

    // GET: .well-known/webfinger?resource=acct:alice@example.com
    [EnableCors("Webfinger")]
    [HttpGet]
    [Produces("application/jrd+json")]
    public async Task<ActionResult<WebfingerResponse>> Get(Uri resource, [FromQuery] IEnumerable<string> rel)
    {
        if (!resource.IsAbsoluteUri || resource.Scheme != "acct")
            return NotFound();

        var account = new Uri($"https://{resource.AbsolutePath}");

        if (!account.Host.Equals(_options.ServerName.Host, StringComparison.InvariantCultureIgnoreCase))
            return NotFound();

        var user = await _context.Users.FirstOrDefaultAsync(x => x.UserName == account.UserInfo);
        if (user == null)
            return NotFound();

        var links = GetLinks(user);

        if (rel.Any())
        {
            var filteredLinks = new List<Link>();

            foreach (var item in rel)
            {
                filteredLinks.AddRange(links.Where(x => x.Rel == item));
            }

            links = filteredLinks;
        }

        var response = new WebfingerResponse
        {
            Aliases = new List<Uri>
            {
                new Uri(_options.ServerName, $"/@{user.UserName}")
            },
            Subject = resource,
            Links = links,
        };

        return Ok(response);
    }

    private ICollection<Link> GetLinks(User user)
    {
        var links = new List<Link>
        {
            new Link("http://webfinger.net/rel/avatar")
            {
                Href = new Uri(_options.ServerName, "/img/" + user.UserName + ".webp"),
                Type = "image/webp"
            },

            new Link("http://webfinger.net/rel/profile-page")
            {
                Href = new Uri(_options.ServerName, "/users/" + user.UserName),
                Type = "text/html"
            },

            new Link("self")
            {
                Href = new Uri(_options.ServerName, user.UserName),
                Type = "application/activity+json"
            },

            new Link("self")
            {
                Href = new Uri(_options.ServerName, $"/users/{user.UserName}"),
                Type = "text/html"
            }
        };

        return links;
    }

    public record WebfingerResponse
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public Uri? Subject { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public ICollection<Uri>? Aliases { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IDictionary<Uri, string>? Properties { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public ICollection<Link>? Links { get; set; }
    }

    public record Link(string Rel)
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public Uri? Href { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Type { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IDictionary<string, string>? Titles { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public IDictionary<Uri, string>? Properties { get; set; }
    }
}
```

File `ApplicationOptions`:
```cs
public class ApplicationOptions
{
    public Uri ServerName { get; set; } = null!;
}
```

You also need a CORS policy and `app.UseCors();`.
```cs
builder.Services.Configure<ApplicationOptions>(builder.Configuration);
builder.Services.AddCors(options =>
{
    options.AddPolicy("Webfinger", policy => policy.AllowAnyOrigin());
});

// ...

app.UseCors();
```
</details>

**Comment by mitchdenny** [comment]
Thanks for sharing your controller code. Curious, are you using WebFinger already in your scenarios?

**Comment by vanillajonathan** [comment]
No, nothing deployed. Just something I wrote a few months ago out of curiosity.
