### ISSUE TITLE
GenerateClaimsAsync method in UserClaimsPrincipalFactory getting called after every 30 minutes in Blazor Server

### ISSUE THREAD

**Issue by saadsaeed01** [dotnet/aspnetcore#45147]
Hello

I am implementing UserClaimsPrincipalFactor to add custom claims in Blazor Server

![image](https://user-images.githubusercontent.com/33133831/202393159-d3f03e12-3809-4625-819d-6e9ba68e4521.png)

Its method GenerateClaimsAsync automatically gets called after every 30 minutes, if I hard refresh the page on which I am on. Can anyone please tell me what is the reason behind it?

Regards
Saad

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please confirm if you project contains `RevalidatingIdentityAuthenticationStateProvider`? If that's the case, that type is setup to refresh your authentication state every 30 minutes.

**Comment by saadsaeed01** [comment]
Hi @mkArtakMSFT 

Yes, I am using `RevalidatingIdentityAuthenticationStateProvider`. The question is how can we set it up so that it refreshes the authentication state after a given time?
