### ISSUE TITLE
In ASP.NET 7, IEnumerable<> controller parameters do not bind from request body by default

### ISSUE THREAD

**Issue by 0x03BB** [dotnet/aspnetcore#45162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In ASP.NET 7, a controller with an `IEnumerable<>` parameter is not bound from the body of the request by default. An empty array is seen by the controller. This worked in ASP.NET 6.

```csharp 
[HttpPost]
public IActionResult Post(IEnumerable<WeatherForecast> forecasts)
{
}
```

If the `[FromBody]` attribute is added to the parameter or `List<>` is used instead, the binding works. The linked GitHub project demonstrates this.

### Expected Behavior

An `IEnumerable<>` parameter should be bound from the body by default, as it was in ASP.NET 6.

### Steps To Reproduce

https://github.com/0x03BB/ParameterBindingIssue

### .NET Version

7.0.100

### Anything else?

Using Visual Studio 17.4.1
[dotnet info.txt](https://github.com/dotnet/aspnetcore/files/10037450/dotnet.info.txt)

**Comment by davidfowl** [comment]
@brunolins16 This might have to do with the change around inferring services implicitly.

**Comment by brunolins16** [comment]
> @brunolins16 This _might_ have to do with the change around inferring services implicitly.

Ohh! Let me take a look.

**Comment by brunolins16** [comment]
Sadly ☹️, you are right, the call to `IServiceProviderIsService.IsService` return `true` for `IEnumerable<>` types.

https://github.com/dotnet/runtime/blob/d15a19fd4a9dd21fb768b6de4870a2d80acb3669/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs#L555
