### ISSUE TITLE
Why isn't the http logging middleware logging form data?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#45161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Why isn't the http logging middleware logging form data

### Expected Behavior

logging form data

**Comment by adityamandaleeka** [comment]
Triage: let's document this in the conceptual doc (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-7.0#mediatypeoptions)
