### ISSUE TITLE
Semingly random CorrelationCookieNotFound issues

### ISSUE THREAD

**Issue by jenspettersson** [dotnet/aspnetcore#45166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are a few other issues close to this one, but not exactly, and we really would like to have some pointers in how we can at least reproduce this issue so we can try to fix it.

We are using OpenIdConnect with a remote identity provider as one of our authentication mechanism. This works good in 99% of the cases. However, we're seeing exceptions/warnings at (semingly) random in around 1% of the authentications with warnings about the correlation cookie not being found. We've tried "everything" (that we know of) to try to reproduce this ourselves, but to no luck. It always works for us when logging in to the same system and environment as where we see errors.

We're collecting logs to see that the cookie is actually being set in the "Challenge":

```
2022-11-18T12:11:08.7172573Z
HandleChallenge with Location: "(not set)"; and Set-Cookie: "
.AspNetCore.OpenIdConnect.Nonce.CfDJ8PVZ...DT3CMjs=N; expires=Fri, 18 Nov 2022 12:26:08 GMT; path=/signin-custom; secure; samesite=none; httponly,
.AspNetCore.Correlation.vNOjmVsOoiGEPlIp...cMVfDv4=N; expires=Fri, 18 Nov 2022 12:26:08 GMT; path=/signin-custom; secure; samesite=none; httponly".

[user is at external identity provider and comes back after 22 seconds]

2022-11-18T12:11:30.3436902Z
'".AspNetCore.Correlation.vNOjmVsOoiGEPlIp...cMVfDv4"' cookie not found.
```

_(sometimes the cookie not found error is just a second after the challenge, when the user is already logged in to the external idp)_

The exact same procedure works for the majority of cases, but not always which makes us a bit worried. We're tracking the UserAgent to see if there's something going on with a specific device/browser and even though the majority of errors seems to happen on mobile devices (iPhone but with both the latest and greatest iOS/Safari versions to older ones) it's by no means exclusive to one particular device...

Sometimes we see multiple "Correlation cookie not found" with the same cookie name following each other by a couple of seconds.

We don't think there's an actual bug here, but something else that we just can't seem to figure out so we would be forever greatful for some pointers in how we can debug this in order to try to find the issue.

And lastly, even though we see this error we can often associate a login flow where an error occured to an actual user logging into our system and doing work, so we're unsure that the errors we see actually affects anyone... We're awaiting some feedback here from users we've contacted. But, we're still concerned...

### Expected Behavior

No random Correlation Cookie not found warnings.

### Exceptions (if any)

Just a generic `System.Exception`

`An error was encountered while handling the remote login. Correlation failed.`

### .NET Version

6.0.403

### Anything else?

If there's of any help, this is using **Identity Server 4** with a remote identity provider, but I'm not sure idsrv is responsible for this behavior.

It's deployed to an Azure App Service, one instance.

It uses DataProtection with keys from Azure Key Vault

It stores the keys in a SQL Database.

https always

**Comment by Tratcher** [comment]
There are two common causes here. 1) the cookie attributes are set wrong, that doesn't seem to be the case in your example, or 2) there's a client incompatibility. SameSite went through several incompatible iterations before it finalized and there are still clients out there stuck on old versions.

If you see a pattern of specific outdated user agents then here is some guidance to address them:
https://learn.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-7.0#supporting-older-browsers

Other weird causes:
- users hitting the back button
- users hitting the refresh button after hitting another error
- links from Word https://github.com/dotnet/aspnetcore/issues/8396

**Comment by blowdart** [comment]
Also private mode in Chrome now has even stricter rules than normal on same site cookies, might your users be using that?

**Comment by jenspettersson** [comment]
We're seeing this with both latest Chrome (107) and latest Safari as well as older browsers. We've implemented handling SameSite cookies for unsupported browsers. 

We've tested Chrome in private without any luck reproducing it. 

Do you know of more browser settings that might affect the correlation cookie? Not to be prejudiced but our user base isn't perhaps the most tech savvy so we don't _think_ they’re doing things to block cookies. We might be wrong, however.

**Comment by adityamandaleeka** [comment]
@jenspettersson Thanks for following up. Unfortunately, we can't investigate this without a repro... please let us know if you are able to reproduce the behavior.

**Comment by jenspettersson** [comment]
After @Tratcher's comment, we started to test different way of navigating backwards in the browser after the login was made and we're now beliving that is what's causing these exceptions. 

So no bug, we just need to figure out how to handle a user navigating back and forth between many oauth2/openid-connect redirects.

Thanks for the suggestions, will close this now.
