### ISSUE TITLE
Publishing the default React template results in a 404

### ISSUE THREAD

**Issue by julesrx** [dotnet/aspnetcore#45165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After creating a new AspNetCore app using the "react" template, publishing it results in a blank screen and a 404 error.
The files inside wwwroot seems to be ignored.

### Expected Behavior

Starting the published app should display the react app.

### Steps To Reproduce

1. `dotnet new react -o my-app`
1. `cd my-app`
1. disable the https redirection (for local startup) : `// app.UseHttpsRedirection();`
1. `dotnet publish -c Release`
1. `dotnet .\bin\Release\net7.0\publish\my-app.dll`

### .NET Version

7.0.100

### Anything else?

One thing to note is that if I add an index.html in a manually created wwwroot, then disabling the csproj target that publish the spa app, the app was able to start correctly.

```
.NET SDK:
	Version:   7.0.100
	Commit:    e12b7af219
 
Runtime Environment:
	OS Name:     Windows
	OS Version:  10.0.19045
	OS Platform: Windows
	RID:         win10-x64
	Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
 
Host:
	Version:      7.0.0
	Architecture: x64
	Commit:       d099f075e4
```

**Comment by javiercn** [comment]
@julesrx thanks for contacting us.

@MackinnonBuck can you take a look?

**Comment by javiercn** [comment]
@julesrx we are not able to reproduce this issue.

![image](https://user-images.githubusercontent.com/6995051/202694525-e42e9f3d-6522-4ccb-9b5d-6999bcb263ee.png)

Make sure you clear your browser cache to avoid any potential issue

**Comment by julesrx** [comment]
I am still getting the issue, even in incognito mode, and on an other browser.

I created a repository : https://github.com/julesrx/aspnetcore-issue-45165
I will try to setup a more reproducible environment.

**Comment by julesrx** [comment]
This solved the issue, thanks 👌.

I am having this issue with the IIS hosting model, still need to figure out how to set the content root path on this...
