### ISSUE TITLE
EndpointMiddleware should not catch exceptions

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#45180]
The endpoint execution middleware [catches exceptions to log the executed endpoint](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/EndpointMiddleware.cs#L63-L66). We should just do this in a finally block and make sure the exception is processed once. Usually, the piece of the stack that caches the exception is the one that logs and reports the exception as handled.

**Comment by davidfowl** [comment]
I'm beginning to wonder how much this matters in practice. I'll play around with it.

**Comment by javiercn** [comment]
@davidfowl I am going to backlog it for now.

**Comment by singh733** [comment]
@davidfowl  @Tratcher  I dig into the code.  Below is the proposal. Please share your views:

```cs
if (endpoint.RequestDelegate is not null)
            {
                Log.ExecutingEndpoint(_logger, endpoint);

                try
                {
                    var requestTask = endpoint.RequestDelegate(httpContext);
                    if (!requestTask.IsCompletedSuccessfully)
                    {
                        return AwaitRequestTask(endpoint, requestTask, _logger);
                    }
                }              

               finally
                {
                    Log.ExecutedEndpoint(_logger, endpoint);
                }
                return Task.CompletedTask;
            }
```

**Comment by Tratcher** [comment]
Wouldn't that end up logging ExecutedEndpoint twice? Once for the finally and once inside AwaitRequestTask?

@davidfowl I think it needs to be more like:
```C#
if (endpoint.RequestDelegate is not null)
            {
                Log.ExecutingEndpoint(_logger, endpoint);

                try
                {
                    var requestTask = endpoint.RequestDelegate(httpContext);
                    if (!requestTask.IsCompletedSuccessfully)
                    {
                        return AwaitRequestTask(endpoint, requestTask, _logger);
                    }
                }              
               catch
                {
                    Log.ExecutedEndpoint(_logger, endpoint);
                    throw;
                }
                Log.ExecutedEndpoint(_logger, endpoint);
                return Task.CompletedTask;
            }
```

**Comment by singh733** [comment]
@Tratcher  should I go ahead and implement this ? Please suggest.

**Comment by Tratcher** [comment]
Yes, and please at least manually test that the expected logs happen without duplicates.

**Comment by singh733** [comment]
> Yes, and please at least manually test that the expected logs happen without duplicates.

Yes I checked Manually
