### ISSUE TITLE
[OIDC] - Failed to authenticate - Regression after upgrading to .NET 7

### ISSUE THREAD

**Issue by kbeaugrand** [dotnet/aspnetcore#45187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My application is a Blazor WebAssembly that is hosted by an ASP.Net server.

I configured my app to get access token for my backend with: 
```cs
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.Authority = settings.Authority;
    options.ProviderOptions.MetadataUrl = settings.MetadataUrl.ToString();
    options.ProviderOptions.ClientId = settings.ClientId;
    options.ProviderOptions.ResponseType = "code";

    options.ProviderOptions.DefaultScopes.Add(settings.Scope);
});

builder.Services.AddApiAuthorization();

builder.Services.AddHttpClient("api", (sp, client) =>
{
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
    client.DefaultRequestHeaders.Add("X-Version", "1.0");
}).AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("api"));
```

It is working fine with this authentication and authorization flow running in .NET 6. 

But after upgrading to .NET 7, I observe that the app fails to authenticate the user. 
I receive the auth_code from the IDP and the client request after the token as expected: 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/9513635/202869096-5c9e0522-b307-4f74-8239-e99af1f4552f.png">

N.B: if I disable the additional scope from the configuration. I can see that I have the ID_token, handled by the application, but failed to get token for requesting my backend (obviously)

### Expected Behavior

My user should be authenticated. aht the access token handled by the app (as for .NET 6).

### Steps To Reproduce

Configure the OIDC With adding an additional scope to the request and specify the authorization code flow: 
```
    options.ProviderOptions.ResponseType = "code";
    options.ProviderOptions.DefaultScopes.Add(settings.Scope);
```

### .NET Version

7.0.100

**Comment by javiercn** [comment]
@kbeaugrand thanks for contacting us.

Can you give us more details? Is this happening in development or after publish?

**Comment by kbeaugrand** [comment]
> @kbeaugrand thanks for contacting us.
> 
> 
> 
> Can you give us more details? Is this happening in development or after publish?
> 
> 
> 
> Are there any errors on the console?
> 
> 
> 
> Can you tell us exactly what the error is? Is there anything on the screen?
> 
> 
> 
> Could you set the login level to debug in Microsoft.AspNetCore.Components.WebAssembly.Authentication?  It will print additional information on the console to help troubleshoot the issue.

This is happening during the development

**Comment by javiercn** [comment]
> Can you tell us exactly what the error is? Is there anything on the screen?
> 
> Could you set the login level to debug in Microsoft.AspNetCore.Components.WebAssembly.Authentication? It will print additional information on the console to help troubleshoot the issue.

We still need info on these two questions

**Comment by kbeaugrand** [comment]
> > Can you tell us exactly what the error is? Is there anything on the screen?

No error on the screen. No error on the browser console.

> > Could you set the login level to debug in Microsoft.AspNetCore.Components.WebAssembly.Authentication? It will print additional information on the console to help troubleshoot the issue.

I put these settings to the web assembly `appsettings.json file: 
```json
{
  "Logging": {
    "LogLevel": {
      "Microsoft.AspNetCore.Components.WebAssembly.Authentication": "Debug"
    }
  }
}
```

On the browser I still not have enough information to diagnose. Please see here the console output I have: 
![image](https://user-images.githubusercontent.com/9513635/203105733-1a4d4baf-7ce9-4a4c-bdb7-fad35b22ebfd.png)

**Comment by javiercn** [comment]
@kbeaugrand thanks for the additional details.

Could you do it like this? 
https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Program.cs#L15

This should do it, and you should be able to filter then

**Comment by kbeaugrand** [comment]
Unfortunatly, not more: 

![image](https://user-images.githubusercontent.com/9513635/203109679-f717085f-43ae-4d23-bce6-23b7182c3cd6.png)

**Comment by javiercn** [comment]
@kbeaugrand thanks for the additional details.

I think something might be missing between the .NET 6.0 and .NET 7.0 update. Did you update the webassembly.authentication package?

Did you clean the bin and obj folders after the update?

**Comment by kbeaugrand** [comment]
> @kbeaugrand thanks for the additional details.
> 
> I think something might be missing between the .NET 6.0 and .NET 7.0 update. Did you update the webassembly.authentication package?
> 
> Did you clean the bin and obj folders after the update?

All packages are up to date: 
```xml
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
```

I do not need to clean bin and obj since the whole project will be running on docker and build from a fresh environnement...

**Comment by javiercn** [comment]
@kbeaugrand thanks for the additional details.

I did spot something. At the very least is making it to:
https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L256

Could you open `AuthenticationService.js` put a breakpoint on the method above?
* It seems like either https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L263 or https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L270 is being taken.

**Comment by kbeaugrand** [comment]
@javiercn, How am I supposed to add a break point to the file you mentionned ? I'm using the build package. So I have only the .js file and it is minified... ,)

**Comment by javiercn** [comment]
@kbeaugrand It's a bit tricky, but you can find the file in the sources (`AuthenticationService.js`). 

Click the unminify button in Edge
![image](https://user-images.githubusercontent.com/6995051/203135533-9083e1cb-dce2-4ff1-802f-edd8efaabe7a.png)
And then search for completeSignIn or for `completeSignIn-result` inside the file.

**Comment by kbeaugrand** [comment]
@javiercn , I have the error : 

![image](https://user-images.githubusercontent.com/9513635/203146307-603d7e1b-c439-44b1-98b4-3e57768f6801.png)

The exception is: 
```
Metadata does not contain property userinfo_endpoint
```

I already know this issue (because I was facing this issue with java spring security that needs also the userinfo_endpoint to be provided. This is because I'm using Azure AD B2C as the OIDC provider and ADB2C doesn't have the userinfo endpoint in its implementation... 
This is quite strange because regarding the OIDC, this endpoint should not be mandatory since, we could use the id_token ...

Do you think I can bypass this issue ?

**Comment by javiercn** [comment]
> I already know this issue (because I was facing this issue with java spring security that needs also the userinfo_endpoint to be provided. This is because I'm using Azure AD B2C as the OIDC provider and ADB2C doesn't have the userinfo endpoint in its implementation... This is quite strange because regarding the OIDC, this endpoint should not be mandatory since, we could use the id_token ...
> 
> Do you think I can bypass this issue ?

Thanks for the additional details. Let me make sure I understood. Are you using `Microsoft.AspNetCore.Components.WebAssembly.Authentication` to talk to an Azure AD B2C instance?

**Comment by kbeaugrand** [comment]
Thank you for this sample @javiercn . 

I think I will add my own javascript client (using the oidc-client-ts) as a workaround for this issue.
I saw that you added a new issue regarding the missing logs, good idea, this will help for the future ;)

Since the original issue wasn't due to this project, you might close this issue. 

Many thanks @javiercn for your help...

**Comment by javiercn** [comment]
@kbeaugrand No problem.

It was good for us to dig into this as we found a gap in our logging, that's something we made emphasis to improve on .NET 7.0 as it was one of the biggest issues when trying to troubleshoot problems like this, so this is hopefully a gap we can close.

**Comment by javiercn** [comment]
Closing since we have a separate issue for the follow-up work.
