### ISSUE TITLE
Create a field for @ref like x:Name in xaml

### ISSUE THREAD

**Issue by wolfgangschneider** [dotnet/aspnetcore#45181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

currently I have to create an ElementReference by myselve
```
@page "/"
@inject IJSRuntime JSRuntime
Enter your name
<input @ref=ReferenceToInputControl />

@code
{
    **ElementReference ReferenceToInputControl;**
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
            await JSRuntime.InvokeVoidAsync("BlazorUniversity.setFocus", ReferenceToInputControl);
    }
} 
```

it would be nice when razor compiler can do it for me if no field was defined

```
@page "/"
@inject IJSRuntime JSRuntime
Enter your name
<input @ref=ReferenceToInputControl />

@code
{
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
            await JSRuntime.InvokeVoidAsync("BlazorUniversity.setFocus", ReferenceToInputControl);
    }
}
```

### Additional context

see xaml x:name 
https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-name-attribute

**Comment by javiercn** [comment]
@wolfgangschneider thanks for contacting us.

Unfortunately, this is not something we plan to do for the reasons outlined [here](https://github.com/aspnet/Announcements/issues/381)
