### ISSUE TITLE
Blazor WASM net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by dajma00** [dotnet/aspnetcore#45199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor wasm site: https://ims.kfacon.com. When I load it first time, I get this error in console:
net::ERR_HTTP2_PROTOCOL_ERROR on several files.

However, when I refresh the same browser, everything runs smooth and site loads.

### Expected Behavior

Site should load without the net::ERR_HTTP2_PROTOCOL_ERROR.

### Steps To Reproduce

Open Edge browser and navigate to https://ims.kfacon.com
If this is the first time, you will get the error.
If you will refresh, the error will go away.
If you will open in InPrivate windows, you will see the error again. 

The behavior is consistent in Edge and Chrome.
It does not occur in Firefox.

### Exceptions (if any)

Does not happen in Firefox.

### .NET Version

.NET 7

**Comment by javiercn** [comment]
@dajma00 thanks for contacting us.

> I have a Blazor wasm site: https://ims.kfacon.com. When I load it first time, I get this error in console:
> net::ERR_HTTP2_PROTOCOL_ERROR on several files.

This seems like some type of issue with your network. Can you give us more details about your deployment? As well as any other software that you might have between your machine and the server? (Enterprise proxy, web application firewall, etc.)

**Comment by Tratcher** [comment]
Can you capture a decrypted wireshark trace?

**Comment by dajma00** [comment]
> @dajma00 thanks for contacting us.
> 
> > I have a Blazor wasm site: https://ims.kfacon.com. When I load it first time, I get this error in console:
> > net::ERR_HTTP2_PROTOCOL_ERROR on several files.
> 
> This seems like some type of issue with your network. Can you give us more details about your deployment? As well as any other software that you might have between your machine and the server? (Enterprise proxy, web application firewall, etc.)

The site is hosted on Digital Ocean and is served via Nginx server. I need to dig further to get a Wireshark trace.

**Comment by mkArtakMSFT** [comment]
@dajma00 can you try to share the compressed trace here as an attachment in a comment?

**Comment by dajma00** [comment]
Trace.

> @dajma00 can you try to share the compressed trace here as an attachment in a comment?

[Trace.zip](https://github.com/dotnet/aspnetcore/files/10072569/Trace.zip)

**Comment by Tratcher** [comment]
@dajma00 you'll also need to include the keys file:
https://resources.infosecinstitute.com/topic/decrypting-ssl-tls-traffic-with-wireshark/
