### ISSUE TITLE
CLI Hot reload for Blazor wasm still doesn't work in .NET 7

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/aspnetcore#45190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

#40587 was supposed to be fixed in .NET 7 with https://github.com/dotnet/sdk/pull/27699. But there is still the same problem. Blazor wasm hot reload still breaks all the time

### .NET Version

7.0.100

**Comment by mkArtakMSFT** [comment]
@tmat can you please look into this? Thanks!

**Comment by jinzhao1127** [comment]
@mkArtakMSFT this issue looks like same as https://github.com/aspnet/AspNetCore-ManualTests/issues/885, it only reproes on the first time to execute `dotnet watch`

**Comment by ziaulhasanhamim** [comment]
In my case, it happens whenever the build takes a long to complete.

**Comment by wocar** [comment]
It is still broken for me as well...

**Comment by wocar** [comment]
@tmat 

Some race conditions were fixed, at least my browser launches now and the hot-reload capabilities verbose message seems correct, however:



![image](https://user-images.githubusercontent.com/9215073/214142984-b1337baf-2e2e-4c66-a23d-b8acdd3c12d9.png)

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/9215073/214143019-545362de-60a3-4a63-8b0d-12370182d7ac.png">

```
└─$ dotnet --version      
7.0.102

		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.2" />

```
