### ISSUE TITLE
`GetExternalLoginInfoAsync` should work even when `MapInboundClaims` is `false`

### ISSUE THREAD

**Issue by FranklinWhale** [dotnet/aspnetcore#45197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

`GetExternalLoginInfoAsync` currently use `ClaimTypes.NameIdentifier` to find a claim for `providerKey`. This only works when `MapInboundClaims` is `true` or a claim mapping of `sub` to `ClaimTypes.NameIdentifier` exists.

### Describe the solution you'd like

Instead of finding `ClaimTypes.NameIdentifier` only, `GetExternalLoginInfoAsync` should also look for `sub`.

Alternatively, `GetExternalLoginInfoAsync` may accept `IEnumerable<string>` for a list of claims that may be used as `providerKey`.

**Comment by adityamandaleeka** [comment]
@blowdart @haok PTAL
