### ISSUE TITLE
Error when trying to use compression (Brotli) in Blazor WASM: "Uncaught (in promise) Corrupted padding bits "

### ISSUE THREAD

**Issue by sturlath** [dotnet/aspnetcore#45191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have been trying to get my Blazor WASM project to compress to avoid the 100 MB over 30-50 sec load time I´m currently having and have been trying to compress the files and serve Brotli (.br) files to my client. I have gone over the [documentation ](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression-1) and tried all I can think of ([see what I have now](https://github.com/abpframework/abp/pull/13772#issuecomment-1320867846)).

![image](https://user-images.githubusercontent.com/2386572/202898689-43265c79-a2ad-43c5-9cdd-05bde7423486.png)

I´m using the abp.io framework and thought that they were [missing something](https://github.com/abpframework/abp/pull/13772#issuecomment-1320867846) but they have managed to get the[ same error from an file-new-Blazor-WASM-project](https://github.com/abpframework/abp/pull/13772#issuecomment-1321023913) 

### Expected Behavior

Blazor WASM client/browser gets served only .br files (not 100MB of .dll´s) and loads without any console errors in faster time rate than 30-50 sec

### Steps To Reproduce

Here is my [file-new-project-code-example](https://github.com/sturlath/BlazorBrotli) (I tried min and max version of the decode.js file) and[ here is the code pushed to Azure](https://blazorbrotli20221120112426.azurewebsites.net/).

For some reason I´m getting a different error than @realLiangshiwei is getting [here ](https://github.com/abpframework/abp/pull/13772#issuecomment-1321023913)
![image](https://user-images.githubusercontent.com/2386572/202900207-00cdf441-7390-477c-b9f1-1723da6731c0.png)

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/2386572/202899003-14e7e632-1793-420d-ae05-9031df4bc8bb.png)

### .NET Version

6.0.302

### Anything else?

Locally I run on Windows and Visual Studio latest preview version. The app in Azure is just AppService. I have been [struggling to get my Blazor WASM to perform since summer](https://github.com/abpframework/abp/issues/13114) without any luck and am hoping we can figure out this compression issue.

**Comment by javiercn** [comment]
@sturlath thanks for contacting us.

The repro is not accessible.

**Comment by sturlath** [comment]
Sorry @javiercn its open now!

**Comment by javiercn** [comment]
@sturlath Seems like you are using a custom library to decompress the brotli stream and the error is coming from it.

Could you try using the `BrotliStream` class from .NET to decompress the stream to see if you happen to have the same issue with the file that fails?

From what I can tell, it is likely an issue in the library you are using.

**Comment by MackinnonBuck** [comment]
@sturlath Could you please try following the approach that https://github.com/aspnet/quickgridsamples/tree/main/src/QuickGridDemos uses? Thanks.

**Comment by sturlath** [comment]
@javiercn are you talking about the code in the decode.min.js? 

That code comes from **[your docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression-1)** where it points to these files [here](https://github.com/google/brotli/tree/master/js).

That is the only "custom" library I have added. 

Btw I just took the none-minified code and inserted it into the decode.min.js file after seeing this here
![image](https://user-images.githubusercontent.com/2386572/203119368-fa517529-00a1-481c-b766-67b9118467eb.png)

**But** as you can see now (I just updated it) and it still has the same issue.

-----------------------

> Could you try using the BrotliStream class from .NET to decompress the stream to see if you happen to have the same issue with the file that fails?

Any change you can point me to some code that I can work with to change the current implementation with?

**Comment by sturlath** [comment]
Sorry @MackinnonBuck I didn´t see your comment until now. 

But I get this
![image](https://user-images.githubusercontent.com/2386572/203125847-6a56b723-eb3b-459e-b7de-1d04b8cde77f.png)

But I found this here but can´t find any compression code...

![image](https://user-images.githubusercontent.com/2386572/203126701-6141651c-1785-46ee-8cda-9e6667de3689.png)

**Comment by sturlath** [comment]
Not sure how I can check the stream since I just hit errors and don´t see anything in the console. This is the url https://blazorbrotli20221120112426.azurewebsites.net

I just pushed it to azure (this time) with Visual Studio (default.. no extra settings)

![image](https://user-images.githubusercontent.com/2386572/203138061-c4d5eda8-46bc-4114-aa30-403e475f8083.png)

you can see some .br files there

![image](https://user-images.githubusercontent.com/2386572/203138207-5a55b79f-d313-421c-bf11-aa63ebafbfa1.png)

**Comment by javiercn** [comment]
@sturlath I was suggesting you put a log statement here. To see what exact file is causing problems:
https://github.com/sturlath/BlazorBrotli/blob/master/BlazorBrotli/wwwroot/index.html#L26

Maybe update the code to put it inside a try-catch and log the name/url of the resource it was trying to decode.

**Comment by sturlath** [comment]
@javiercn I added the logs. Does this help? Anything else I can try out? Isn´t there a Blazor WASM compression example I can try out and publish to see how that works out?

![image](https://user-images.githubusercontent.com/2386572/203359774-12745094-f923-4851-ac4f-72191052e420.png)

**Comment by sturlath** [comment]
@javiercn is that a server setting (I havent read anything on that) or something I can influence in code? And how? Do you know of any docs that might help?

**Comment by mkArtakMSFT** [comment]
Looks like the issue is because the `.br` files aren't accessible on your server. If they're not there, they should have been deployed too. If they are present on the server, then the server should be configured to make them accessible.
We'll keep this issue around to address any gaps in our docs to cover this.

**Comment by SteveSandersonMS** [comment]
@sturlath Yes, it probably is a server setting. Azure hosted apps may return 404 for unconfigured file extensions, such as `.br`, so you likely need to configure it to serve those files. I think it's equivalent to this StackOverflow question where somebody wants to make the server return `.woff` files:  https://stackoverflow.com/questions/29334564/getting-404-error-for-font-files-with-azure-hosted-app-tried-adding-mime-type

**Comment by sturlath** [comment]
Thank you @SteveSandersonMS! That fixed the issue with the example. It now fetches the .br files. 

![image](https://user-images.githubusercontent.com/2386572/203486177-93f03fa0-f360-4f2f-b560-e42a6eedd84c.png)

I will now check if this fixes my original issue with my product. I´ll report back.
