### ISSUE TITLE
Incorrect OpenApi documentation in Minimal API when using WithOpenApi extension method

### ISSUE THREAD

**Issue by marcominerva** [dotnet/aspnetcore#45192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using .NET 7.0. I have created a Minimal API with the following endpoint:

```
app.MapDelete("api/people/{id:int}", Results<NoContent, NotFound> (int id) =>
{
    return id > 0 ? TypedResults.NoContent() : TypedResults.NotFound();
});
```

This produces the following page in Swagger:

![image](https://user-images.githubusercontent.com/3522534/202900465-20813c39-34dd-4e76-8098-55aa89a495bf.png)

In particular, the description of the 404 response is correctly "Not Found".

However, if I add the `WithOpenApi` extension method to the endpoint, like this:

```
app.MapDelete("api/people/{id:int}", Results<NoContent, NotFound> (int id) =>
{
    return id > 0 ? TypedResults.NoContent() : TypedResults.NotFound();
})
.WithOpenApi(operation =>
{
    operation.Summary = "Deletes a person given the ID";
    operation.Description = "If the person does not exist, a 404 response is returned";
    return operation;
});
```

I obtain this:

![image](https://user-images.githubusercontent.com/3522534/202900490-d0feb03e-620e-4f17-b12f-f0a9b96d974c.png)

So, the 404 response now has the description "Client error", which is incorrect.

### Expected Behavior

The description of 404 response should be "Not Found" even when I use the `WithOpenApi` extension method.

### Steps To Reproduce

Minimal repro here:  https://github.com/marcominerva/OpenApiIssue.

### .NET Version

7.0.100

### Anything else?

Visual Studio 2022 17.4.1

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by captainsafia** [comment]
@marcominerva Thanks for filing this issue! Good spot.

The reason that his happens is that when calling the `WithOpenApi` method, the generated status code descriptions are produced from this codepath.

https://github.com/dotnet/aspnetcore/blob/51e43829e26da9c2a182fa99fc3c3b249fe19a9d/src/OpenApi/src/OpenApiGenerator.cs#L215-L231

Whereas the default scenario goes through the generator in whatever package you are using (usually Swashbuckle or NSwag).

Would you be interested in updating the code above to include handling for 404?

**Comment by captainsafia** [comment]
> Yes, I will be happy to contribute! What do you think about just returning the reason phrase that corresponds to the status code? It could be a good solution?

Great! The reason code sounds good. The one small challenge we ran into when implementing this is exactly which status codes to support. 404 is an obvious miss but I think giving more specific status codes for the most common status codes (`401` as unauthorized) is sensible.

BTW, as a workaround for the original issue, you can set the status code yourself via:

```csharp
app.MapGet("/", () => ...)
  .WithOpenApi(o => new(o)
  {
    o.Responses["404"].Description = "Not found";
  })
```

**Comment by captainsafia** [comment]
@marcominerva Thank you for reporting the issue and submitting a PR! I've opened a backport to .NET 7 so we can fix it there too. 🙇🏽
