### ISSUE TITLE
Website Import - blazor (wasm) web view not displayed correctly

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#45195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I exported framer website and tried to import it to Blazor. When its imported in index.html everything works of course. When I try to import the <body> part to Index.razor -> its working first second but then the page is missing interactive parameters. I am getting uncaught error: Minified React error #418, Minified React error #423.

What am I doing wrong?

Thank you.

### Expected Behavior

To display website correctly also in Blazor view.

### Steps To Reproduce

Minimal Repo:
https://github.com/Laftek/HTMLImport.git

"/" (index) -> displayed correctly 
"/blazor" -> not displayed correctly

### .NET Version

7.0.100

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. It looks like this is a question about how to use Blazor with a particular 3rd party technology. We recommend asking this question on StackOverflow to get help from the community. If you think this is a bug, please provide a minimal repro project with steps describing how to reproduce the bug.
