### ISSUE TITLE
Blazor WASM Not Downloading Azure Blob SAS URL

### ISSUE THREAD

**Issue by senorezi** [dotnet/aspnetcore#45209]
I have a Blazor WASM application that has a button to make a GET request to a SAS Blob URL. However, I get this error when I click the button. 

I tested this SAS Blob URL and it is downloading when I paste it into my browser and Postman... not sure why it is not downloading in Blazor. 

I have read permissions in the generated SAS Blob URL and my Cors is enabled with the origins being my local host and storage account that contains the azure blob

Error Log:
`Access to fetch at '{SAS BLOB URL}' from origin '[https://localhost:{](https://localhost:7167/)myport}' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
My method in the Client side code that gets called when this button is clicked is very simple
```
    private async void Download()
    {
        using (var client = new HttpClient())
        {
            var result = await client.GetAsync({foo\sasBlobUrl});
        }
    }
```
My BlazorApp.Server\Program.cs code is as follows:
```
string[] origins = { "foo\myLocalHost", "bar\storageAccountUrl.net" };

builder.Services.AddCors(policy =>
{
    policy.AddPolicy("_myAllowSpecificOrigins", builder => builder.WithOrigins(origins)
         .AllowAnyMethod()
         .AllowAnyHeader()
         .AllowCredentials());
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseCors("_myAllowSpecificOrigins");

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();


app.MapRazorPages();
app.MapControllers();
app.MapFallbackToFile("index.html");

app.Run();

```
BlazorApp.Client\Program.cs
```
using BlazorApp2.Client;
using Microsoft.AspNetCore.Components.Web;
using [Microsoft.AspNetCore.Components.WebAssembly.Hosting](https://microsoft.aspnetcore.components.webassembly.hosting/);

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builde
```r.HostEnvironment.BaseAddress) });
await [builder.Build](https://builder.build/)().RunAsync();

**Comment by MackinnonBuck** [comment]
Thanks for contacting us. Could you please take a look at [this guidance](https://learn.microsoft.com/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services) and see if you are able to resolve the issue?
