### ISSUE TITLE
Enable customization of responce_type for OAuth Authentication

### ISSUE THREAD

**Issue by Deph0** [dotnet/aspnetcore#45207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use an enterprise OAuth (Not an OpenIDConnect / OAuth2.0) service which does not allow me to set "code" responsee type, hence this issue. 

I've searched the web and tried different things without success and arrived at the conclusion that there is a need for change in dotnet in order for this to work.

### Describe the solution you'd like

I'd Like it if response_type could be made configurable using optioins.ResponseType. If not provided, it should default back to "code" as written currently.

### Additional context

[OAuthHandler.cs#L300](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L300) ([perma](https://github.com/dotnet/aspnetcore/blob/1549377232cb2ed3f7e92b5b09a7b21445536bb7/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L300))

**Comment by Tratcher** [comment]
What do you need to change it to? Changing the type is more than changing this string, we'd also have to implement the other possible flows to handle that response.

**Comment by Deph0** [comment]
I would like support for Token

**Comment by Deph0** [comment]
I found that you could change the redirect uri in such a way, but have not been able to test it yet fully.

```
 services.AddAuthentication() .AddOAuth("MyOAuthService", "Enterprise OAuth", options => {
     /* Other Options Omitted for Bravery */
     options.Events.OnRedirectToAuthorizationEndpoint = context =>
      {
            context.Response.Redirect(context.RedirectUri.Replace("response_type=code", "response_type=token"));
            return Task.CompletedTask;
      }
});
```

**Comment by Tratcher** [comment]
> I found that you could change the redirect uri in such a way, but have not been able to test it yet fully.

It's not enough to change the response_type, the reset of the handler would also have to be updated to look for the token instead. 
https://github.com/dotnet/aspnetcore/blob/bc9255b509c4b51d9bbbea7b15ddafe482784699/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L117-L121

We're also unlikely to do so because that flow is more dangerous.
https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/

> You can see that this is much more dangerous than issuing a temporary one-time-use authorization code. ... For these reasons as well as more documented in [OAuth 2.0 for Browser-Based Apps](https://oauth.net/2/browser-based-apps/), it is recommended that the Implicit flow no longer be used.

What identity provider are you working with that requires the token/implicit flow?

**Comment by Deph0** [comment]
Ah ok- Like i said, I did not test that "idea" yet.
I'm working with a off the shelves Manufacturing Execution Systems (MES) platform, targeted towards Enterprises, so it's not that accessible and lacks documentation on the topic of OAuth.

I understand that it could be a dangerous flow, although i don't believe it should prevent implementation. It should be clear or perhaps a feature flag or other kind of "Yes, I am sure and I know what I'm doing" mechanism.

**Comment by Tratcher** [comment]
The current recommendation is to make your own copy of the OAuthHandler.

**Comment by adityamandaleeka** [comment]
cc @blowdart

**Comment by blowdart** [comment]
Yea, given the oauth documentation of how dangerous it is, and that it seems specialized this isn't something we'd generally support, forking the handler and changing it around is the route here
