### ISSUE TITLE
[Analyzer/Codefixer] Recommend using `AddAuthorizationBuilder` for configuring global policies

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#45219]
## Background and Motivation

In .NET 7, we introduced an `AddAuthorizationBuilder` extension method on `IServiceCollection` that would register authorization-related services and provide an `AuthorizationBuilder` for constructing policies. This is an abbreviated syntax that allows reduces nesting in the original pattern of calling `AddAuthorization` and providing a policy construct as a callback. 

### Analyzer Behavior and Message

When the user provides code where `AddAuthorizationBuilder` would provide a more abbreviated style, recommend a codefix with the following message:

> Use `AddAuthorizationBuilder` to register authorization services and construct policies.

### Category

- [ ] Design
- [ ] Documentation
- [ ] Globalization
- [ ] Interoperability
- [ ] Maintainability
- [ ] Naming
- [ ] Performance
- [ ] Reliability
- [ ] Security
- [ ] Style
- [X] Usage

### Severity Level

- [ ] Error
- [ ] Warning
- [X] Info
- [ ] Hidden

## Usage Scenarios
**Before**
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AtLeast21", policy =>
        policy.Requirements.Add(new MinimumAgeRequirement(21)));
});

var app = builder.Build();

app.UseAuthorization();

app.Run();
```
**After**
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthorizationBuilder()
  .AddPolicy("AtLeast21", policy =>
  {
        policy.Requirements.Add(new MinimumAgeRequirement(21)));
  });

var app = builder.Build();

app.UseAuthorization();

app.Run();
```

## Risks

Marking this as an info-only analyzer strikes a good balance between informing the user of this feature without being too presumptuous (via a warning). A refactoring would not have been good at educating the user about the functionality.

**Comment by halter73** [comment]
API Review Notes:

1. Is the message to passive? Starting with "Recommend using" seems wrong.
2. Can you use `AddAuthorization` and `AddAuthorizationBuilder` together? Do the policies just merge?

**Comment by captainsafia** [comment]
> Can you use AddAuthorization and AddAuthorizationBuilder together? Do the policies just merge?

I tried this out. You can use them together and the policies end up being merged with a last-in wins strategy for policies with the same name.

```csharp
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;

var builder = WebApplication.CreateBuilder();

builder.Services.AddAuthentication().AddJwtBearer();
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AtLeast21", policy => policy.RequireClaim("foo", "bar"));
    options.AddPolicy("OtherThing", policy => policy.RequireClaim("one", "two"));
});

builder.Services.AddAuthorizationBuilder()
  .AddPolicy("AtLeast21", policy => policy.RequireClaim("other", "claim"));


var app = builder.Build();

app.MapGet("/", () => "Hello world!")
    .RequireAuthorization("AtLeast21", "OtherThing");

app.Run();
```

That being said, I'm not sure how likely this is to occur in user code. Considering the merge strategy, calling both is equivalent to calling one with the policies registered in the same order. It would be helpful to provide another analyzer that recommended people unify under one invocation.

**Comment by captainsafia** [comment]
> Is the message to passive? Starting with "Recommend using" seems wrong.

With regard to this, it seems like the general convention is to start with "Use ..." so I've updated the description to mimick this.

**Comment by halter73** [comment]
Given that combining multiple calls of `AddAuthorization` and `AddAuthorizationBuilder` allows merging policies, it sounds like the fixer would be very unlikely to break people. So, I think the fixer makes sense. I agree this is probably pretty rare to do both too, so doubt there's much value in a refactoring that unifies multiple calls, but maybe.

**Comment by david-acker** [comment]
I'm interested in helping out with this. Should the analyzer + codefix should be added to `Framework/AspNetCoreAnalyzers`?

**Comment by captainsafia** [comment]
> I'm interested in helping out with this. Should the analyzer + codefix be added to `Framework/AspNetCoreAnalyzers`?

Yes please and thank you! 🙏🏽

**Comment by halter73** [comment]
I see that the `api-needs-work` label got removed but we never explicitly approved it. I don't forsee any problems, but we can confirm we're good with the title and message on Thursday in our next meeting.

```
Title: Use AddAuthorizationBuilder
Message: Use AddAuthorizationBuilder to register authorization services and construct policies.
Category: Usage
Severity Level: Info
```
