### ISSUE TITLE
DataProtectionBuilder API enhancement

### ISSUE THREAD

**Issue by jeremy-morren** [dotnet/aspnetcore#45228]
## Background and Motivation

Currently adding certificate(s) for Encryption/Decryption require you to have the details at startup, rather than a `configureOptions` type signature.  Having a public API with a `Func` parameter would be good.

Currently, the function at https://github.com/dotnet/aspnetcore/blob/main/src/DataProtection/DataProtection/src/DataProtectionBuilderExtensions.cs#L258 only takes the certificate, not a function/action to provide one.

This would be a help in a microservices architecture, where the encryption certificate(s) may be stored elsewhere and not available at startup.  Loading them lazily would allow for more flexibility. The problem is that the user cannot add these functions themselves because `XmlKeyDecryptionOptions` is an internal class.

What would be good are the following functions (or at least the ability to add these yourself):

```c#

public static class DataProtectionBuilderExtensions
{
    public static IDataProtectionBuilder ProtectKeysWithCertificate(this IDataProtectionBuilder builder, Func<X509Certificate2> getCertificate)
    {
        if (builder == null)
        {
            throw new ArgumentNullException(nameof(builder));
        }

        if (getCertificate == null)
        {
            throw new ArgumentNullException(nameof(getCertificate));
        }
        
        //We use a lazy for efficiency & to ensure we only get 1 certificate
        var certificate = new Lazy<X509Certificate2>(getCertificate, LazyThreadSafetyMode.ExecutionAndPublication);

        builder.Services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(services =>
        {
            var loggerFactory = services.GetService<ILoggerFactory>() ?? NullLoggerFactory.Instance;
            return new ConfigureOptions<KeyManagementOptions>(options =>
            {
                options.XmlEncryptor = new CertificateXmlEncryptor(certificate.Value, loggerFactory);
            });
        });

        builder.Services.Configure<XmlKeyDecryptionOptions>(o => o.AddKeyDecryptionCertificate(certificate.Value));

        return builder;
    }

    //And friends: use Lazy<> for all
    
    public static IDataProtectionBuilder ProtectKeysWithCertificate(this IDataProtectionBuilder builder,
        Func<string> thumbprint) {}

    public static IDataProtectionBuilder UnprotectKeysWithAnyCertificate(this IDataProtectionBuilder builder,
        Func<X509Certificate2>[] certificates) {}
}

```

**Comment by blowdart** [comment]
What would you expect to happen if the delayed load fails?

**Comment by jeremy-morren** [comment]
> What would you expect to happen if the delayed load fails?

I would assume pass the error through (i.e. result in a `500` error).  It would occur during service construction (i.e. as part of constructing `IOptions<KeyManagementOptions>`.

**Comment by captainsafia** [comment]
Triage: @jeremy-morren Thanks for filing this issue. Could you update the issue text with the signature of the new APIs to be added for review? Some example code would be helpful as well. You can view the full template at https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=

**Comment by amcasey** [comment]
I think this would best be tracked as part of https://github.com/dotnet/aspnetcore/issues/23033.
