### ISSUE TITLE
Blazor WASM: Can't pass WebAuthn PublicKeyCredential from JS to .NET

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#45236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When returning a `PublicKeyCredential` from JS to a C#-Call (return value set as \<dynamic>), nothing is returned.

### Expected Behavior

A json object representing a `PublicKeyCredential` is returned, looking like this:
![grafik](https://user-images.githubusercontent.com/10476293/203308594-62f5284a-ad42-4ff4-ae09-c77b29cdb3e3.png)

### Steps To Reproduce

In a Blazor WASM project, call a JS function that calls `await navigator.credentials.create`, then return the result of that.  
In C#, call it using `var creds = js.InvokeAsync<dynamic>` to just accept whatever comes back.

I can clean up and push a minimal demo project here if that makes it easier.

### .NET Version

6.0

### Anything else?

I typed the input in C#, that one works fine. Passing it to js works:

```
    public class PublicKeyCredentialCreationOptions
    {
        public byte[] challenge { get; set; } = DateTime.Now.ToString().Select(c => (byte)c).ToArray(); // Just random stuff here I think?
        public RelyingParty rp { get; set; } = new ("WebAuthnExample"); // If I understand correctly, id will be auto filled with the current domain
        public User user { get; set; } = 
            new("metallkiller".Select(c => (byte)c).ToArray(), "metallkiller", "Metallkiller");
        public PublicKeyCredentialParameters[] pubKeyCredParams { get; set; } = Algs.Select(Alg).ToArray();
        public long timeout { get; set; } = 60000; // Not entirely sure what this does - docs has more info
        public string attestation { get; set; } = "direct"; // No idea I just copied this

        public record RelyingParty(string name);

        public record User(byte[] id, string name, string displayName);

        public record PublicKeyCredentialParameters(string type, int alg);
    }
```

I tried to make a type accepting the response, but had several problems, the latest being not getting an `ArrayBuffer` returned into my byte[] or string (only tried those two for the id - rawId arrives empty too):

```
    public record PublicKeyCredential(string id, string type, byte[] rawId, AuthenticatorResponse response);

    public record AuthenticatorResponse(string clientDataJSON);
```

Edit: I also changed PublicKeyCredential to a class instead of a record, but still no data in the fields.

**Comment by javiercn** [comment]
@Regenhardt thanks for contacting us.

You need to use an `IJSObjectReference` as the return value. Otherwise, the result will be JSON serialized to be marshalled to the .NET side and I do not believe `PublicKeyCredential` is serializable.

**Comment by Regenhardt** [comment]
Then how can I get an actual .NET object from that? Do I call `InvokeAsync` for each property?

**Comment by javiercn** [comment]
@Regenhardt JS interop does not support retrieving properties directly (yet). So you would need to wrap it on a custom JS object with methods to get the data you want.

**Comment by Regenhardt** [comment]
Ah that one worked, I can transfer the Credential now, thanks for the help!
