### ISSUE TITLE
Consider adding id property to the Blazor WASM manifest.json file

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspnetcore#45239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When creating a Blazor WASM project the `manifest.json` file doesn't have an `id` property. To learn more, take a look at https://developer.mozilla.org/en-US/docs/Web/Manifest/id. I think we can just set the value to the same thing that `start_url` has.

### Describe the solution you'd like

`id` property in the `manifset.json` for Blazor WASM projects.

**Comment by javiercn** [comment]
Thanks @sayedihashimi 

Is there a concrete scenario where having the defined in the manifest makes a difference? I suspect our manifest does not have one because from what I can tell in the documentation it is not needed unless you want to uniquely identify the app separately from the URL?

**Comment by sayedihashimi** [comment]
@javiercn from my understanding it's not required today, but it may be required in the future. It seems like it's a best practice to now set `id` as well as `start_url`.

> Today, there is nothing you need to do, and nothing will break if you don't add an id to your web app manifest (as long as the start_url and the manifest path remains the same). To future-proof your PWA, you can add an id property to your web app manifest.

https://developer.chrome.com/blog/pwa-manifest-id/

> The id property allows you to explicitly define the identifier used for your application. Adding the id property to the manifest removes the dependency on the start_url or the location of the manifest, and makes it possible for them to be updated in the future. For more information, see [Uniquely identifying PWAs with the web app manifest id property](https://developer.chrome.com/blog/pwa-manifest-id/).

https://web.dev/add-manifest/
