### ISSUE TITLE
[Feature Request] Merging splatted attributes in Blazor

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#45230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Very often I have to do this:
````xml
<MyComponent class="foo bar baz" />
````
But that custom component also defines a `class` attribute with its own classes. So I need to jump through some hoops to merge them.

This happens enough times in custom components, that I put the common stuff in a base class, as I wrote on [SO, here](https://stackoverflow.com/a/74403144/9971404). That SO post has 12k views, so this is something people struggle with.

### Describe the solution you'd like

I do something like this:

`ChildComponent.razor`
````cs
<div @attributes=_additionalAttributes></div>

@code {

  [Parameter(CaptureUnmatchedValues = true)]
  public IReadOnlyDictionary<string, object> AdditionalAttributes { get; set; }
    = new Dictionary<string, object>();

  private IReadOnlyDictionary<string, object>? _additionalAttributes;

  protected override void OnParametersSet()
  {
    base.OnParametersSet();

    var parentClasses = AdditionalAttributes.GetValueOrDefault("class", "");
    var classes       = $"foo {parentClasses}".Trim();

    _additionalAttributes = 
      AdditionalAttributes.Where(x => x.Key != "class")
      .Append(KeyValuePair.Create("class", (object)classes))
      .ToDictionary(x => x.Key, x => x.Value);
  }

}
````

`ParentComponent.razor` is now clean, with the normal name `class`:
````cs
<ChildComponent class="bar baz" />

@code {
}
````

Which renders:
````cs
<div class="foo bar baz"></div>
````

It would be nice if all that were built in. Maybe it could be:
````cs
Parameter(CaptureUnmatchedValues = true, MergeAttributes = true)]            // <--- note MergeAttributes
public IReadOnlyDictionary<string, object> AdditionalAttributes { get; set; }
  = new Dictionary<string, object>();
````
...and we could use that during attribute splatting.

### Additional context

No.

**Comment by SteveSandersonMS** [comment]
Consider using this kind of approach to merge CSS class names from dictionaries with other fixed class names:

https://blazorfiddle.com/s/znwm2e6t

**Comment by SteveSandersonMS** [comment]
Since this is achievable either by using `.Concat` inside component code, or by making a component base class to encapsulate such behaviors, we'll consider this supported already and close.

Thanks for confirming you have a good solution!
