### ISSUE TITLE
Is there a way to increase the time to refresh the authentication state if RevalidatingIdentityAuthenticationStateProvider is being used?

### ISSUE THREAD

**Issue by saadsaeed01** [dotnet/aspnetcore#45245]
Hello

I am using `RevalidatingIdentityAuthenticationStateProvider ` in my Blazor Application. It automatically refreshes the authentication state after every 30 minutes. Is there a way to increase this time?

**Comment by Youssef1313** [comment]
Isn't this class part of the application and you can just go into it and modify `RevalidationInterval`?

**Comment by SteveSandersonMS** [comment]
Yes, @Youssef1313 is correct. This is just a file in the project template. It contains the following line which you can edit:

```cs
protected override TimeSpan RevalidationInterval => TimeSpan.FromMinutes(30);
```
