### ISSUE TITLE
Question : Should Microsoft.AspNetCore.Diagnostics.HealthChecks extension respond success to HTTP PUT/POST/DELETE methods ?

### ISSUE THREAD

**Issue by madhub** [dotnet/aspnetcore#45258]
Question : Should Microsoft.AspNetCore.Diagnostics.HealthChecks respond success to HTTP PUT/POST/DELETE methods ?
Below sample responds success for all of the HTTP methods
```csharp

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddHealthChecks();
var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseAuthorization();

app.MapControllers();
app.MapHealthChecks("/healthz");
app.Run();


```
All of the below requests , responds success , is this right ?
```shell
curl -v -d "a=b" -X POST http://localhost:5162/healthz
curl -v -d "a=b" -X PUT http://localhost:5162/healthz
curl -v -d "a=b" -X DELETE http://localhost:5162/healthz
```
![image](https://user-images.githubusercontent.com/8907962/203715968-ea19479c-9454-4b7f-a5b8-74c2a63d1034.png)

**Comment by adityamandaleeka** [comment]
Is this affecting any use cases for you? If you'd like, you could configure your health check endpoint like this: 

```c#
.WithMetadata(new HttpMethodMetadata(new[] { "GET" })
```

which will only allow GETs.

**Comment by madhub** [comment]
> Is this affecting any use cases for you? If you'd like, you could configure your health check endpoint like this:
> 
Our internal security testing raised this has issue and also it strange to see **POST/PUT/DELETE** on the health check API. 
> ```cs
> app.MapHealthChecks("/healthz").WithMetadata(new HttpMethodMetadata(new[] { "GET" }, acceptCorsPreflight: true)
> ```
Yes, that is what I did , I would have expected this to be default behavior.
> which will only allow GETs.

**Comment by adityamandaleeka** [comment]
@madhub Is there a security concern or was it just found during the security testing? If you're using a public tool, can you let us know which one it is that flagged this issue?

And just to confirm, after you set the Metadata to only allow GETs you're no longer seeing the other types of requests accepted right?

**Comment by madhub** [comment]
> @madhub Is there a security concern or was it just found during the security testing? If you're using a public tool, can you let us know which one it is that flagged this issue?

Its not a public tool, internally developed. Intent is to limit the API surface , In this health check meant be accessed only vi HTTTP GET , 
> And just to confirm, after you set the Metadata to only allow GETs you're no longer seeing the other types of requests accepted right?

Yes

**Comment by adityamandaleeka** [comment]
Got it, thank you. We don't believe there's a security issue here in allowing the other methods, and since there's a way to configure the endpoint with the behavior you are looking for, I think we can close this issue.

**Comment by adityamandaleeka** [comment]
Triage: we don't believe this meets the bar to change at this point, given that there's no security (or other) concern and it's technically a breaking change.

If we get more feedback from people who want to see this changed, we may consider it in the future.
