### ISSUE TITLE
Blazor HtmlRenderer: Use ReadOnlySpan instead of ArrayRange

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/aspnetcore#45259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This is not a feature request per se. The current [HtmlRenderer](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/RazorComponents/HtmlRenderer.cs) is using `ArrayRange` as its collection type for passing around `RenderTreeFrame`s.

### Describe the solution you'd like

In bUnit, we have a mirror of that renderer in our code (more or less). We saw smaller performance gains in switching to `ReadOnlySpan<RenderTreeFrame>` as well as a slight improvement in readability. This would remove also code like `ref var frame = ref frames.Array[position]`. That's why I thought to push this change "upstream".

### Additional context

The change from bUnit: https://github.com/bUnit-dev/bUnit/pull/708/commits/d65dbb183f25a54aaca25aa96733ee4c3b7468da

I can also provide a PR.

**Comment by javiercn** [comment]
@linkdotnet thanks for contacting us.

Do you happen to have some numbers collected for this? We are definitely happy about taking perf improvements provided that the numbers back up the claims :). We need to be very careful not to regress things here.

**Comment by linkdotnet** [comment]
> @linkdotnet thanks for contacting us.
> 
> Do you happen to have some numbers collected for this? We are definitely happy about taking perf improvements provided that the numbers back up the claims :). We need to be very careful not to regress things here.

Let me (re)create a benchmark for that with .NET7 to drive the discussion a bit further.

**Comment by linkdotnet** [comment]
Good input @javiercn . I specifically checked for smaller to medium-sized components and surprisingly `ReadOnlySpan` is slower in those scenarios (the smaller the more overhead ROS produces). That said ROS is **not** a suitable replacement. Therefore I'll close the ticket. If I do find other areas of improvement I will try to grab some numbers first.

Cheers Steven
