### ISSUE TITLE
Rare "The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by websolut** [dotnet/aspnetcore#45266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Our service fabric application (dotnet core 6) occasionally throws this error 
`The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host. `

when uploading a blob to a storage account. We checked all the infra requirements and limits - no concerns there (probably 5-10 rps per service)

Implemenation:
```
    public async Task Upload(
        string sasUri,
        string mediaType, 
        Stream mediaStream,
        CancellationToken cancellationToken = default)
    {
        HttpClient client = HttpClientFactory.CreateClient();

        mediaStream.Position = 0;

        HttpContent content = new StreamContent(mediaStream);

        content.Headers.Add("x-ms-blob-type", "BlockBlob");
        content.Headers.ContentType = MediaTypeHeaderValue.Parse(mediaType);

        HttpResponseMessage message = await client.PutAsync(sasUri, content).ConfigureAwait(false);

        if (!message.IsSuccessStatusCode)
        {
            var msg = await message.Content?.ReadAsStringAsync();
            throw new Exception("Upload failed: " + msg);
        }
    }
```

### Expected Behavior

There should be no such errors

### .NET Version

6

**Comment by Tratcher** [comment]
This is usually an external networking issue. Your best option is to add some retry handling for resilience.

**Comment by websolut** [comment]
> This is usually an external networking issue. Your best option is to add some retry handling for resilience.

Yes, this is a bit tricky part to explain since it is an azure service fabric app trying (windows) to upload a blob to the azure storage account in the same region.

**Comment by websolut** [comment]
I am not sure why it was closed since I am sure there was no connectivity issues between 2 azure services.
