### ISSUE TITLE
Caching: Microsoft.Extensions.Caching.StackExchangeRedis doesn't provide createifnotexist method

### ISSUE THREAD

**Issue by dewanymca** [dotnet/aspnetcore#45268]
Microsoft.Extensions.Caching.StackExchangeRedis doesn't have a method which support createifnotexist method while base package of stackexchangeredis provide that. How can I use createifnotexist while using extension nuget

**Comment by Tratcher** [comment]
Microsoft.Extensions.Caching.StackExchangeRedis implementes the IDistributedCache abstraction. If you need redis specific features you should use the base stackexchangeredis package directly.
