### ISSUE TITLE
Add SkipStatusCodePages flag to ApiBehaviorOptions

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#45260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When mixing MVC Controllers with Api Controllers in an application, there should be a global setting to turn off the [IStatusCodePagesFeature](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Middleware/Diagnostics.Abstractions/src/IStatusCodePagesFeature.cs) for Api Controllers to avoid overriding the raw api response with an MVC view/html based  status code page implementation.

### Describe the solution you'd like

Add the SkipStatusCodePages flag to the Microsoft.AspNetCore.Mvc.ApiBehaviorOptions class and add a new `SkipStatusCodePagesConvention` in [ApiBehaviorApplicationModelProvider](https://github.com/dotnet/aspnetcore/blob/6fb2218c945e5fb2a4c4fb95df916fbb0f23b863/src/Mvc/Mvc.Core/src/ApplicationModels/ApiBehaviorApplicationModelProvider.cs).

As a workaround I've extended the [ApiControllerAttribute](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Mvc/Mvc.Core/src/ApiControllerAttribute.cs) (implementation from [SkipStatusCodePagesAttribute](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Mvc/Mvc.ViewFeatures/src/SkipStatusCodePagesAttribute.cs).

```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public class ApiControllerAttribute : Microsoft.AspNetCore.Mvc.ApiControllerAttribute, IResourceFilter, ISkipStatusCodePagesMetadata
{
    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var statusCodeFeature = context.HttpContext.Features.Get<IStatusCodePagesFeature>();
        if (statusCodeFeature != null)
        {
            // Turn off the StatusCodePages feature.
            statusCodeFeature.Enabled = false;
        }
    }

    public void OnResourceExecuted(ResourceExecutedContext context)
    {
    }
}
```

**Comment by alienwareone** [comment]
There is actually a cleaner "workaround" but a built-in global switch would be even cleaner ;-)
```
public static class SkipStatusCodePagesMetadataExtensions
{
    public static IEndpointConventionBuilder SkipStatusCodePagesForApiControllers(this IEndpointConventionBuilder builder)
    {
        builder.Add(endpointBuilder =>
        {
            var apiControllerAttribute = endpointBuilder.Metadata.FirstOrDefault(m => m.GetType() == typeof(ApiControllerAttribute)) as ApiControllerAttribute;

            if (apiControllerAttribute == null)
            {
                return;
            }

            endpointBuilder.Metadata.Add(new SkipStatusCodePagesMetadata());

            endpointBuilder.FilterFactories.Add((context, next) =>
            {
                return async context =>
                {
                    var statusCodeFeature = context.HttpContext.Features.Get<IStatusCodePagesFeature>();

                    if (statusCodeFeature != null)
                    {
                        // Turn off the StatusCodePages feature.
                        statusCodeFeature.Enabled = false;
                    }

                    return await next(context);
                };
            });
        });

        return builder;
    }
}

 // Marker metadata class
file class SkipStatusCodePagesMetadata : ISkipStatusCodePagesMetadata
{
}
```

**Comment by captainsafia** [comment]
Triage: @alienwareone Would you be interested in filling out an API proposal for the the addition of a new property to to the `ApiBehaviorOptions` for this feature?

We can implement runtime behavior that would add the SkipStatusCodePageAttribute by default if the option was enabled.

You can view the API proposal template [here](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=).

**Comment by alienwareone** [comment]
[[API Proposal]: Add SkipStatusCodePages property to ApiBehaviorOptions](https://github.com/dotnet/aspnetcore/issues/45369#top)

**Comment by captainsafia** [comment]
Thanks! Closing this one and we'll track the other issue in our API review process.
