### ISSUE TITLE
Browser print RenderFragment performance issue

### ISSUE THREAD

**Issue by Owenll66** [dotnet/aspnetcore#45272]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Printing a razor component as below with no parameter set on a page by `ctrl` + `p` will cause the print window to load forever and memory to surge.

```csharp
<div style="display: flex;gap: 0.5rem;">
    @TestParameter
</div>

@code {
    [Parameter]
    public RenderFragment? TestParameter { get; set; }
}
```

### Expected Behavior

`ctrl` + `p` to print the page should work as expected without stuck on the loading screen. The process memory/CPU consumption should stay stable without surging.

### Steps To Reproduce

I have a razor component named `TestComponent` defined as:
```csharp
<div style="display: flex;gap: 0.5rem;">
    @TestParameter
</div>

@code {
    [Parameter]
    public RenderFragment? TestParameter { get; set; }
}
```
And I added this component to a blank page with no parameter defined:
```csharp
<TestComponent/>
```

When I go to the page in a browser and press `ctrl` + `p` to print the page. The print window is loading forever and with an unreasonable number of sheets shown and the process memory usage starts to surge:

![image](https://user-images.githubusercontent.com/37032357/203886210-fc10885d-d2cc-49e4-b5a3-dde29b212605.png)

Alternatively, I have created a github repro: https://github.com/Owenll66/AspNetCoreRenderFragmentPrintIssue.
It is a blazor wasm project. And the bug can be reproduced by running this project and press `ctrl` + `p` on the index page.

### .NET Version

net6.0

**Comment by javiercn** [comment]
@Owenll66 thanks for contacting us.

This seems to be an issue on the actual HTML for the page. Not sure exactly why, but seems that your component is introducing it, as it does not repro on a page without your component.

It likely means that you need to troubleshoot the styles used when printing. It might also be a bug in Chrome with regards to print and `display:flex`. Do you have the same issue on a page that is not rendered by Blazor? (Same markup, just blazor is not involved).

**Comment by Owenll66** [comment]
@javiercn Thanks for your comment. I did find it can be reproduced just by html below without the `RenderFragment` in chrome - Version 107.0.5304.122 (Official Build) (64-bit) and Edge - Version 107.0.1418.56 (Official build) (64-bit). But not in Firefox. I believe it is an issue in Chrome and Edge. Happy to have this issue closed. Thanks.

```html
<div style="display: flex;gap: 0.5rem;">
</div>
```
