### ISSUE TITLE
`Microsoft.AspNetCore.RateLimiting` latest package is `7.0.0-rc.2.22476.2`

### ISSUE THREAD

**Issue by eduherminio** [dotnet/aspnetcore#45283]
### Describe the bug

Latest `Microsoft.AspNetCore.RateLimiting` package [in NuGet](https://www.nuget.org/packages/Microsoft.AspNetCore.RateLimiting) is `7.0.0-rc.2.22476.2`.

### Expected Behavior

I was expecting Microsoft.AspNetCore.RateLimiting v7.0.0 to exist.

Are there plans to release a stable version for it?

**Comment by davidfowl** [comment]
@eduherminio No, it's part of the shared framework in ASP.NET Core. There's no longer a package for it.

**Comment by eduherminio** [comment]
Understood, thanks @davidfowl !
