### ISSUE TITLE
Change ASP.NET Core Identity incorrect password logging level

### ISSUE THREAD

**Issue by Eirenarch** [dotnet/aspnetcore#45296]
## Summary

Currently ASP.NET Core Identity produces a warning every time a user enters a wrong password. As it stands this log item is not only useless but problematic. I propose that this log item is either removed or its log level is reduced to Debug

## Motivation and goals

ASP.NET Core Identity on a wrong password which fills the log with useless events. The log event is of a relatively high "Warning" level so it is impractical to simply increase the log level as useful items will be missed. On top of it the event does not provide a user id or any meaningful information so it depends on additional correlated logging or enriched context implemented by the developer to have any chance of being useful.

**Comment by captainsafia** [comment]
Triage: @Eirenarch Would you be interested in opening a PR to update the log level for these warning message?

**Comment by Eirenarch** [comment]
Hmmm it seems to me that someone has already done so - https://github.com/dotnet/aspnetcore/commit/cd678f8a792f0bf31b7b769aa6c3ddf192ff7ba6

Interesting... It says it was done in February and I did check the source before opening the issue. Maybe I was looking at an old branch or something.

**Comment by captainsafia** [comment]
@Eirenarch Good find! This should have shipped in .NET 7 if you want to give those bits a try.

**Comment by Eirenarch** [comment]
I guess this is resolved. It was a duplicate issue but we now know others found it problematic too so it must be a good change :)
