### ISSUE TITLE
NavigationLock not working

### ISSUE THREAD

**Issue by digitalsigi** [dotnet/aspnetcore#45316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am testing new component NavigationLock following this video https://www.youtube.com/watch?v=akffcwNpJiY and built my own Component around NavigationLock:
```c#
   public partial class ConfirmNavigation : BaseComponent<ConfirmNavigation>
    {
        [Parameter] public bool IsModified { get; set; }  

        public async Task OnConfirmNavigation(LocationChangingContext context) 
        {
            var confirm = await JSRuntime.InvokeAsync<bool>("window.confirm", "Es gibt nicht gespeicherte Daten. Wollen Sie die Seite wirklich verlassen?");
            Logger.LogInformation(LogEventIdEnum.Navigation.ToEventId(), "Navigation confirmed: {Confirm}, {TargetLocation}", confirm, context.TargetLocation);
            if (!confirm)
            {
                context.PreventNavigation();
            }
        }
    }
```
and 
```html

@inherits BaseComponent<ConfirmNavigation>

    @if (IsModified)
    {
        <NavigationLock OnBeforeInternalNavigation="@OnConfirmNavigation" ConfirmExternalNavigation />
    }
```
IsModified ist set the following way:
```C#
            DtoContext.OnFieldChanged += (sender, e) =>
            {
                var CanSave = DtoContext.Validate();
                IsModified = true;
                StateHasChanged();
            };

```
Now I enter only one char in input field which is recognised in OnFieldChanged Event. But when I press another link or page reload in browser, NavigationLock is not triggered. With some logging I could verify that IsModified is set to true.

### Expected Behavior

NavogationLock Event OnConfirmNavigation ist called and user gets prompted.

### Steps To Reproduce

See Bug description

### .NET Version

7.0.100

### Anything else?

It looks like that it works in Debug, and sometimes I observed that it works when Component has been triggered at once, or by just enter a char and then hit \<TAB\>. Browser is actual version of edge

asp net core 7.0
Visual Studio Version 17.4.1

**Comment by digitalsigi** [comment]
One more thing:

When modifying properties belonging to EditContext it looks like that they not triggering NavigationLock as well. For example I implemented a ToggleButton Component based on Radio Buttons.  This code does not trigger NavigationLock but toggles the Button:

```html
                                       <ToggleButton Value="@EditVm.IstDZAVerwaltet"
                                                      LabelOn="Ja"
                                                      LabelOff="Nein"
                                                      Disabled="true"
                                                      ShowButtonWhenDisabled="false"
                                                      OnToggle="@((ToggleButtonEventArgs args) =>
                                                              {
                                                                  EditVm.IstDZAVerwaltet = args.NewState;
                                                              })"
                                                      class="form-control" />
                                        <ValidationMessage For="@(() => EditVm.IstDZAVerwaltet)" />

```

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @digitalsigi.

In order for us to investigate this issue, would you please provide a minimal repro project hosted in a public GitHub repository?

**Comment by digitalsigi** [comment]
Ok, the issue is within large project. I will try to extract the necessary parts. Please give me some time to do that.

L.G.
Josef Bogad
Von meinem iPhone gesendet

Am 28.11.2022 um 18:39 schrieb msftbot[bot] ***@***.***>:

﻿

Hi @digitalsigi<https://github.com/digitalsigi>. We have added the "Needs: Author Feedback" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.
