### ISSUE TITLE
ReturnUrl not working on Blazor WASM after OIDC login

### ISSUE THREAD

**Issue by tbone95** [dotnet/aspnetcore#45321]
### Description

We are using Blazor as the Client and Component Space OpenId Connect as the Auth server, the issue we are facing is after logging in successfully instead of being redirected back to the accessed page (prior to authenticating), we are getting redirected back to the "/" root directory.

The problem has been tested on a Blazor WASM client running .NET 6.0 and was working as expected. Once we upgraded that to .NET 7.0, the problem started.

The expected behaviour would be to be redirected back to the correct page instead of the root directory.

### Configuration

* Which version of .NET is the code running on?
.NET 7.0
* What OS and version, and for Linux, what distro?
Windows 10 - 10.0.19044 Build 19044
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
It is not, as we have tested using our current Blazor WASM app and a fresh barebones Blazor WASM app.
* If you're using Blazor, which web browser(s) do you see this issue in?
Chrome

**Comment by javiercn** [comment]
@tbone95 thanks for contacting us.

This is a known change we did as part of .NET 7.0.

See https://github.com/aspnet/Announcements/issues/497 for details. Please let us know if this solves your problem.

**Comment by tbone95** [comment]
Thanks @javiercn, problem has been solved.
