### ISSUE TITLE
Quickgrid Virtualize=true using Memory data not displaying entire data

### ISSUE THREAD

**Issue by EmilAlipiev** [dotnet/aspnetcore#45326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Virtualize=true with  more than 100 rows as AsQuerable, so the data in the memory, Quickgrid is not displaying often all the available data. Same ui with same data is displaying fine setting Virtualize=false.

### Expected Behavior

that all data is displayed on scrolling to the buttom, to the last item.

### Steps To Reproduce

```
  <QuickGrid  Theme="default" Class="table table-striped table-bordered table-responsive" Items="@_bookings?.AsQueryable()" Virtualize="true">
  <PropertyColumn Property="@(c => c.Code)" Sortable=true Title=@Localize["Code"] />
   <PropertyColumn Property="@(c => c.FromTime)" Sortable=true Title=@Localize["Start"] />
 </QuickGrid>
```

Nothing special here, simply usage can be reproduced

### .NET Version

6.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we've experienced even though we've used the QuickGrid many times before. So most probably this is due to your custom code. Here is a working example of it. You can see how it's done and what's different about your application logic, that results in such a behavior: https://aspnet.github.io/quickgridsamples/virtualizing/

**Comment by EmilAlipiev** [comment]
@mkArtakMSFT your example is based on GridItemsProvider, but what i report here is[ In-memory IQueryable data](https://aspnet.github.io/quickgridsamples/datasources/). I do an api call and fetch all data into memory and try to bind as `AsQueryable ` 
In the docu was mentioned as "with small amounts of data, up to a few hundred items."  even I have 90 rows with 7 columns, it only renders like 70 rows. Setting `Virtualize=false` will show all 90 rows.
