### ISSUE TITLE
Extend Quickgrid with Id and Style Properties

### ISSUE THREAD

**Issue by EmilAlipiev** [dotnet/aspnetcore#45327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

yes, id property is important to set for automated-testing like bunit test or cypress/playwright/seleniu, etc.

### Describe the solution you'd like

it is not possible to set id and style for quickgrid table from outside. I would like to see an **id** for quickgrid that can be used for automated-testing
There is **Class** property however **Style** would be also useful in order to use it in-style css directly without using a css-class

**Comment by korteksz** [comment]
Hello,

I created a PR in the mentioned repository for this issue, can I request a review for it?

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/50051
