### ISSUE TITLE
Create 7.0 project using terminal and run the project using https, the url can't opened.

### ISSUE THREAD

**Issue by lemon0213** [dotnet/aspnetcore#45336]
**REPRO MACHINE**: MacOS Monterey (12.6.1)
**REPRO Configuration**: 

+ SDK 7.0.101

**.NET Core SDK:** 7.0.101

**.NET Core Runtime:** 7.0.1

**INSTALL STEPS**

1. Install .NET 7.0.101 from [Pipelines - Run 20221122.3-7.0.101-servicing.22572.4-157743 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2051306%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-wajian%40microsoft.com%7C101e64e2fea1418faaf908daccf219d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638047637581532771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZH3ZhzH8Dfgwqpi6dgKqGiFM92%2FFBa52KP88oyDdDBs%3D&reserved=0)
2. Add feed to ~/.nuget/NuGet/NuGet.Config
Feed using: 
[https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.101-servicing.22572.4-shipping/nuget/v3/index.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkgs.dev.azure.com%2Fdnceng%2Finternal%2F_packaging%2F7.0.100-rtm.22521.12-shipping%2Fnuget%2Fv3%2Findex.json&data=05%7C01%7Cv-wajian%40microsoft.com%7C101e64e2fea1418faaf908daccf219d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638047637581532771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JcLc3X%2By8LuZid26dIvJ0wSJBItdZukkBl6%2Bh0%2By7VQ%3D&reserved=0)

**REPRO STEPS**
1. Create an empty solution using Terminal
> mkdir CommandLineProjects
> cd CommandLineProjects
> dotnet new sln

2. Create web application using Terminal
> mkdir WebApp
> cd WebApp
> dotnet new mvc -f net7.0

3. Using https to run the project, open browser and go the localhost URL. Can successfully open the url.
> dotnet run -lp https

4. Create class library.
> cd ..
> mkdir ClassLibrary
> cd ClassLibrary
> dotnet new classlib -f net7.0

5. Add reference from web app to class library.
> cd ../WebApp
> dotnet add reference ../ClassLibrary/ClassLibrary.csproj

6. Add WebApp and ClassLibrary to the solution.
> cd ..
> dotnet sln add WebApp/WebApp.csproj
> dotnet sln add ClassLibrary/ClassLibrary.csproj

7. Build and run project using https.
> dotnet build
> cd WebApp
> dotnet run -lp https

**ACTUAL**
Run the project using https, the url can't opened.
![image](https://user-images.githubusercontent.com/66412274/204245928-1e0ae5ca-ee78-43a5-854d-175ea7c241e5.png)

**NOTE**:

1. This issue only repro with MacOS Monterey (12.6.1), MacOS Monterey (12.5) and MacOS Ventura(13.1) doesn't repro this issue.
2. this issue only repro with terminal, open the Webapp project using VS Mac, this issue doesn't repro.
3. this issue only repro with `dotnet run -lp https`, using `dotnet run`, it doesn't repro.
4. This issue doesn't repro with step3, only repro with step7.
5. This issue doesn't repro with 7.0.100.

**EXPECTED**
Run the project using https, the url can open successfully.

**Comment by mkArtakMSFT** [comment]
I'm reposting my comment here from the linked issue:
> Something seems off here. Simply creating a class library and referencing it from the project shouldn't have an effect (not from the ASP.NET Core side at least).

@javiercn do you have any thoughts about what can cause this?

**Comment by javiercn** [comment]
@mkArtakMSFT nope. 

Any errors on the console or anywhere? Any logs captured?

**Comment by javiercn** [comment]
@mkArtakMSFT I am following up over email, but I can't repro this bug on the MacOS version they mention.

**Comment by v-zhenxue** [comment]
This issue still repro on 17.6 Preview 1 (without 7.0.102 SDK) on MacOS Monterey, but the 17.6 P1 + 7.0.102 SDK on MacOS Monterey doesn't repro.
