### ISSUE TITLE
Unable to read request body after request.EnableBuffering

### ISSUE THREAD

**Issue by ruslanfedoseenko** [dotnet/aspnetcore#45340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When accessing http request of a POST request and enabling buffring request body is empty

### Expected Behavior

I expect to be able to read body of a POST reques

### Steps To Reproduce

https://github.com/ruslanfedoseenko/dotnet-bug-repo

### .NET Version

6.0.110

**Comment by Tratcher** [comment]
You're enabling buffering too late.

You enable it here:
https://github.com/ruslanfedoseenko/dotnet-bug-repo/blob/803ac4119a2e642c895c4562f26334b35bbe0510/WebApplication2/Controllers/WeatherForecastController.cs#L28

But the body was already consumed by model binding to create the WeatherForecast parameter.
https://github.com/ruslanfedoseenko/dotnet-bug-repo/blob/803ac4119a2e642c895c4562f26334b35bbe0510/WebApplication2/Controllers/WeatherForecastController.cs#L25

You need to enable buffering before model binding, such as in a middleware in program.cs:
```c#
app.Use((context, next) =>
{
  context.Request.EnableBuffering();
  return next();
});
```
