### ISSUE TITLE
.NET 8 Feature Request:  Ability to scope CSS styles to a specific instance of a component

### ISSUE THREAD

**Issue by RChrisCoble** [dotnet/aspnetcore#45347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello @danroth27,

Quick background refresher on our software and the relevant UC's we're looking to support with Blazor.

Our software has a "Design Time" build environment and a "Runtime" environment which is presenting what was built in design time. C#/WPF is the technology used in both stacks, and we're presenting moving the Runtime portion of the environment to Blazor WASM which will be consumed from Azure as a SaaS offer. After this is completed, we'll move to porting the design time tooling to Blazor WASM as well. This is a multi-year strategy as we transition the entire business to subscription.

Our design time tooling allows the user to compose an HMI (Human Machine Interface) by assembling individual components together on a screen and binding them together with business logic. A component in this case was historically just a basic WPF control that provided some widget of functionality. Once the user placed a WPF component on the screen, the exposed properties of that WPF control can be configured, bound to live values, etc. Some of those exposed properties are common things like Background Color, Foreground Color, Font, Font Color, etc., standard exposed properties one would expect to see on a UI component. The user can configure whatever colors/fonts/etc. on these individual components and in Runtime they would present themselves as configured.

We're porting this Runtime framework to Blazor, along with the WPF components we own. Our Design time tooling allows the import and configuration of three types of controls:

Controls we internally compile ourselves and deliver with our design time tooling. "Out of the box content" so to speak.
Controls customers build for our environment that often utilize our Runtime SDK.
3rd party controls. These could be any WPF control. Telerik, Infragistics, built yourself without using our SDK, etc.
We're trying to support the same styling behavior with Blazor with the assumption that all these controls specified in 1-3 above become Blazor Controls instead of WPF controls. Essentially we're moving from XAML styling to CSS styling in this transition.

In our workflow we allowing importing any of these types of controls, and the user can drag/drop them then configure using our tooling. In Runtime, we're setting these styles dynamically as opposed to knowing all the styles at code compile time.

Each control on the screen may need a unique style configured specifically to that control, even if the same control is used multiple times on the screen. For UC 1 above, we can use a unique CSS class style for that control instance. For 2, we can recommended our customers follow the best practice for their Blazor controls and support a unique CSS class style as well. For 3 though, we don't have a good solution as a configured style would apply to all usages of that control as it's coming from the master CSS configuration.

One possible solution to this is having Blazor support the browser concept of a Shadow DOM, which functionally isolates the CSS styles leaking into the master CSS list, allowing the styles to stay local to the control in the Shadow DOM. Another solution is an iFrame wrapper, but you can't host Blazor in an internal iFrame. The iFrame has other issues as well.

### Describe the solution you'd like

[danroth27](https://github.com/danroth27) commented [on Sep 30](https://github.com/dotnet/aspnetcore/issues/34641#issuecomment-1263948974)

@RChrisCoble Thanks for the explanation! It sounds like you basically need a way to scope CSS styles to a specific instance of a component, not just a component type, correct? If you had some way to tack IDs on to component instances would that work too for your scenarios?

**[Yes]**

One of the key point here in "dynamic" is the ability to set the value of the css property dynamically in our runtime.

for Instance:

```
{
    color: @Foreground;
    font-size: @FontSize;
    font-family: @FontFamily;
}
```

@Foreground, @FontSize, @FontFamily are Blazor component's properties and can be changed at runtime. When a new value comes in, we refresh the Blazor component's UI.

I keep using the "dynamic" word here as another UC we need to support is dynamically re-theming the HMI on demand. This UC looks like "Employees on a day shift might use the light theme and Employees on the night shift switch to the dark theme." of the HMI...Or one of the more interesting UC's that always stuck in my head was our software being used on submarines in a European country's navy fleet and switching to "battle stations" changed the UX of the HMI to ensure everyone understood.

### Additional context

@danroth27 we originally covered this conversation under issue #34641, and you suggested a more appropriate solution I copied into the "Describe the solution you like" field.

**Comment by SteveSandersonMS** [comment]
Thanks for the info. I might be missing something, but it sounds like this would be achievable using normal CSS patterns. If not, perhaps it would help to clarify why not.

As long as the components you render can have a CSS class name, or ID, or a parent element with a class/ID, this can indicate which subset of CSS rules should apply to that specific instance. If that's not viable, could you clarify why?

**Comment by RChrisCoble** [comment]
Thanks for the reply @SteveSandersonMS.  After a lengthy discussion with the Dev's on my side, we're going to use your suggestion.  We can consider this issue resolved and closed.

The TL;DR version is in our solution we load 3rd party Blazor components not in our control.  We have a design time interface that allows the user to compose the eventual UI themselves.  To a certain degree we wanted to protect the CSS definitions from those 3rd party libraries from polluting the global CSS namespace, causing unintended side effects when a CSS name collision occurs.  We're going to see how bad this situation is via experimentation over the course of 2023 here and hope to keep things simple in the implementation.  Thanks again for the fast response!
