### ISSUE TITLE
Remove IISAuthenticationHandler as suggested by existing comments

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/aspnetcore#45355]
## Background and Motivation

I was digging through the IIS code and came across this:

https://github.com/dotnet/aspnetcore/blob/bc4fd75e5ff4d51fbc5f7cf1452164a03573adab/src/Servers/IIS/IIS/src/Core/IISServerAuthenticationHandler.cs#L14

Since it is now after .NET 6, should this be removed?

## Proposed API

```diff
namespace Microsoft.AspNetCore.Server.IIS.Core;

-public class IISServerAuthenticationHandler : IAuthenticationHandler
-{
-    public Task<AuthenticateResult> AuthenticateAsync();
-    public Task ChallengeAsync(AuthenticationProperties? properties);
-    public Task ForbidAsync(AuthenticationProperties? properties);
-    public Task InitializeAsync(AuthenticationScheme scheme, HttpContext context);
-}
```

## Usage Examples

N/A

## Alternative Designs

N/A

## Risks

Somebody might still be using it, I guess?

**Comment by halter73** [comment]
API Review Notes:

- #27441 Also obsoleted `ThrowingWasUpgradedWriteOnlyStream` and `WriteOnlyStream`. Let's remove those too.

```diff
namespace Microsoft.AspNetCore.Server.IIS.Core;

- public class IISServerAuthenticationHandler : IAuthenticationHandler
- public class ThrowingWasUpgradedWriteOnlyStream : WriteOnlyStream
- public abstract class WriteOnlyStream : Stream
```

API Approved!
