### ISSUE TITLE
Add option to RedisCache to pass which field to save data in redis.

### ISSUE THREAD

**Issue by Luizfelipefm** [dotnet/aspnetcore#45350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Currently, RedisCache saves the data in the "data" field inside redis, I would like to be able to change that field.

### Additional context

I work in the transcription of a legacy code and in this code I use a library that saves the data in the "value" field, being able to change this field in RedisCache I would be able to use both codes.

One way to solve this would be:

1. Add property FieldName into RedisOption.
2. Change the const SetScript to:`private const string SetScript = (@"
                redis.call('HSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], '{0}', ARGV[4])
                if ARGV[3] ~= '-1' then
                  redis.call('EXPIRE', KEYS[1], ARGV[3])
                end
                return 1");`
3. Add in constructor: ``internal RedisCache(IOptions<RedisCacheOptions> optionsAccessor, ILogger logger)
    {
        ...
        _setScript = string.Format(CultureInfo.InvariantCulture, _setScript, _options.FieldName ?? "data");
    }``
4. Change in initialize: ` services.AddStackExchangeRedisCache(options =>
            {
                options.FieldName = "value";
            });`

**Comment by adityamandaleeka** [comment]
cc: @mgravell

**Comment by mgravell** [comment]
Interesting. I guess what gives me pause here is that if you're using some other library historically (or concurrently?), how confident can we be that the meaning (or presence / absence) of the other fields: is compatible with the meanings here. If they're not: the behaviour could be unpredictable. Is this coming from an alternative public/commercial library that I could validate for compatibility, or is it 100% bespoke. If the latter: I wonder about the wisdom of changing the code to support an extremely niche use-case. Perhaps you could help me understand the impact / scale here, for prioritisation / impact purposes?

**Comment by Luizfelipefm** [comment]
I'm currently using the library in legacy code, this one here https://cachemanager.michaco.net/ .
The legacy code is quite extensive and we are going to continue using it for a while, and we are already using some functions from the code migrated to .net 6, so we need both working and saving the cache in the same field.

**Comment by mgravell** [comment]
This seems to be a very niche scenario, that depends on two implementations happening to be hash-based, while using different hash-names. Currently, we don't expose any of those implementation details, and adding an option here would effectively tie us *into* an implementation. Also, the two implementations *aren't directly compatible* - the MichaCo version has versioning, multiple expiration modes, etc - the two would *not* play nicely side-by-side, as missing version/expiration values could cause unanticipated results, and if failing to change the version (comparable to put/update) could again cause unusual results.

My advice here would be to *not* attempt to treat the two cache implementations as compatible, but instead to migrate between them cleanly - assuming that an empty cache scenario is recoverable, even if increasing load for a period while it rebuilds; this can be done by changing the key-prefix or DB number (non-cluster only), or wiping the DB entirely when migrating (if this is possible, i.e. the database *only* has cache entries).

Honestly, I can't see this feature being useful to many other parties, to warrant the risks and complexity it would introduce. Another option would be to fork the caching layer, and use that forked version with whichever implementation details you need.

Closing as "will not implement"; happy to keep the conversation going, but: I don't think this is an obvious "just do it" scenario.
