### ISSUE TITLE
Typed results (such as Created<T>) do not emit type discriminator from attribute-based polymorphic serialization introduced in .NET 7

### ISSUE THREAD

**Issue by dkokotov** [dotnet/aspnetcore#45357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I have a type hierarchy with two classes `A` and `B`, where `B` is derived from `A` and `A` contains `JsonPolymorphic` and `JsonDerivedType` annotations, and I then have a request delegate that returned `Created<A>`, the serialized response does not contain the type discriminator property.

### Expected Behavior

I would expect the response to include the type discriminator property as described in the docs for [polymorphic serialization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#polymorphic-type-discriminators).

However, it does not.

### Steps To Reproduce

```
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(B), typeDiscriminator: "b")]
[JsonDerivedType(typeof(A), typeDiscriminator: "a")]
public record A {
    public string SomeProp { get; init; }
}

public record B {
    public string SomeOtherProp { get; init; }
}

// in Program.cs
builder.Map("/try", () => return TypedResults.Created<A>("/newone", new B { SomeProp = "foo", SomeOtherProp = "bar" }));
// this will serialize to { "SomeProp": "foo", "SomeOtherProp": "bar" } 
// but I would expect it to be { "type": "b", "SomeProp": "foo", "SomeOtherProp": "bar" } 
```

### .NET Version

7.0.100

### Anything else?

I believe this is caused by the considerations discussed in https://github.com/dotnet/aspnetcore/issues/43894 and https://github.com/dotnet/aspnetcore/issues/41724 to support backwards-compatible polymorphic serialization. Presumably due to those changes, ultimately the serialization code from `Created<T>` calls `JsonSerializer.Serialize` explicitly with the runtime type of the value passed to `Created<T>`. but the documentation for the type discriminator feature explicitly requires the base type to be used.

**Comment by dkokotov** [comment]
I think this issue got closed accidentally because I mentioned it in a PR where I implemented a workaround (in a private repo). It looks like when that PR got merged Github for some reason decided to close this issue as well.

**Comment by captainsafia** [comment]
@brunolins16 has been doing some investigation in this area after reviewing issue https://github.com/dotnet/aspnetcore/issues/44852.
