### ISSUE TITLE
[signalr-client-c++] Client  send access_token in Qtcreator

### ISSUE THREAD

**Issue by hexback** [dotnet/aspnetcore#45363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using
```
signalr::hub_connection connection = signalr::hub_connection_builder::create(url)
            .with_logging(std::make_shared <logger>(), signalr::trace_level::verbose)
            .build();

    **auto nativeConfig = signalr_client_config();
    nativeConfig.get_http_headers().emplace( "Authorization", alltoken);
    connection.set_client_config( nativeConfig );**

    connection.on("ReceiveMessage", [=](const std::vector<signalr::value>& m)
    {
        std::cout << "cmd"<< m[0].as_string() << std::endl;
    });

    std::promise<void> startTask;
    connection.start([&connection, &startTask](std::exception_ptr exception)
    {
        if (exception)
        {
            try
            {
                std::rethrow_exception(exception);
            }
            catch (const std::exception & ex)
            {
                std::cout << "exception when starting connection: " << ex.what() << std::endl;
            }
        }
        startTask.set_value();
    });
    startTask.get_future().get();
```
 to set permissions in Qt, compile with debug can be used smoothly, compile with release will crash

### Expected Behavior

get the correct reply when ues siganlr  send access_token in Qtcreator

### Steps To Reproduce

1.using debug to compile can get correct reply（Sometimes the following error occurs）
2.using release to compile show error
Logger2022-11-30T08:30:02.824Z [verbose  ] acquired lock in start()
Logger2022-11-30T08:30:02.824Z [verbose  ] disconnected -> connecting
Logger2022-11-30T08:30:02.824Z [verbose  ] released lock in start()
Logger2022-11-30T08:30:03.038Z [error    ] connection could not be started due to: The server does not support WebSockets which is currently the only transport supported by this client.
Logger2022-11-30T08:30:03.038Z [verbose  ] connecting -> disconnected

**Comment by BrennanConroy** [comment]
Capture a network trace and look at what the negotiate response to the client is.
https://learn.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-7.0#network-traces

**Comment by hexback** [comment]
file:///home/heyt/.cache/.fr-k5cBVM/_index.htm
this is the response of debug
release no trace

**Comment by hexback** [comment]
I can't get the trace when debugging and releasing.

**Comment by amcasey** [comment]
Triage: @hexback what issue are you running into that's preventing you from getting traces?

**Comment by halter73** [comment]
> Logger2022-11-30T08:30:03.038Z [error ] connection could not be started due to: The server does not support WebSockets which is currently the only transport supported by this client.

What server are you using? The above log indicates that the server does not support WebSockets. Take a look at the WebSocket prerequisites here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#prerequisites You might also need to enable WebSockets in the portal if you're on app service: https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-general-settings

SignalR fails to negotiate a transport and therefore never even tries to connect with an access_token in the Authorization header. That said, we'd be more sure about what's going on if we could get a network trace.
