### ISSUE TITLE
SIGTERM signal in .NET 6 app deployed in azure Kubernetes service is not triggered

### ISSUE THREAD

**Issue by Ghyath-Serhal** [dotnet/aspnetcore#45366]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

1

I have a .NET 6 application. This application contains a BackgroundService that is used to handler background jobs. These jobs are fired on a certain time based on different schedules.

I need to implement graceful shutdown when the application is stopping, because there might be some running jobs and I want to complete the jobs before stopping the application.

The app is deployed in Azure Kubernetes Service, when running this command kubectl delete pod {podname} to delete a certain pod, I am not able to handle the sigterm and write my logic to handle graceful shutdown.

I am using the IHostApplicationLifetime and registering on the ApplicationStopping event.

`IHostApplicationLifetime _applicationLifetime; _applicationLifetime.ApplicationStopping.Register(OnAppStopping);`

In the docker file I added the below line

`STOPSIGNAL SIGTERM`

The OnAppStopping is never fired on AKS.

### Expected Behavior

The ApplicationStopping event should be triggered in order to handle graceful stop of the application

### .NET Version

6

**Comment by davidfowl** [comment]
Can you make a full minimal repro and provide instructions for how we can see the issue in k8s? I haven't seen the same behavior so its hard to know if it's something in your setup or something in the framework.

**Comment by Tratcher** [comment]
cc @bradygaster who is tracking several reports like this.

**Comment by bradygaster** [comment]
these seem related: #22272 and #39139

**Comment by davidfowl** [comment]
Similar but app service is different to AKS.

**Comment by Ghyath-Serhal** [comment]
Find below the repo. It is very simple, it contains an IHostedService.

[https://github.com/Ghyath-Serhal/SigTermKuber.git](url)

When hosting on Kubernetes, the OnApplicationStopping is not fired.

**Comment by davidfowl** [comment]
@Ghyath-Serhal can you include the k8s manifest and instructions used to reproduce the issue?

**Comment by Ghyath-Serhal** [comment]
Find the attached k8s manifest [k8s.txt](https://github.com/dotnet/aspnetcore/files/10152020/k8s.txt)
The command used is **kubectl delete pod {podname}**

Note that I reproduced the same scenario on docker Linux.
I sent a SIGTERM signal to the container using the below cammand.
**docker kill --signal="SIGTERM" container-id/name**

The OnApplicationStopping is never fired.

**Comment by davidfowl** [comment]
> Note that I reproduced the same scenario on docker Linux.
> I sent a SIGTERM signal to the container using the below cammand.
> docker kill --signal="SIGTERM" container-id/name

This is the sort of information we need to reproduce the issue (see the "steps to reproduce" part of the issue above).

> Find the attached k8s manifest [k8s.txt](https://github.com/dotnet/aspnetcore/files/10152020/k8s.txt)

This isn't a k8s manifest, but it seems like you can reproduce the issue on with docker kill so that will be the repro.

I have 2 more questions:
1. https://github.com/Ghyath-Serhal/SigTermKuber/blob/main/SigTermKubernetes/Dockerfile#L5-L6 - Why does your docker file expose ports even though this application isn't exposing any?
2. How are you observing with docker that OnApplicationStopping isn't firing? Are you using docker logs?

**Comment by davidfowl** [comment]
@Ghyath-Serhal were you using the docker support in visual studio and trying to hit break points in the callback?

**Comment by Ghyath-Serhal** [comment]
Yes, that is right, when using docker support from visual studio, It deploys to docker and attach and debugger.
The ApplicationStarted event is firing normally, however the ApplicationStopping is not.

**Comment by davidfowl** [comment]
Did you run docker logs to see if the statement you printed in application stopping fired?

**Comment by Ghyath-Serhal** [comment]
Yes I am running docker logs to see if the statement is printed.

**Comment by karimMogh** [comment]
same here, any update on this?

**Comment by davidfowl** [comment]
We're all on vacation. Expect updates in a couple of weeks.

**Comment by amcasey** [comment]
> Yes, that is right, when using docker support from visual studio, It deploys to docker and attach and debugger. The ApplicationStarted event is firing normally, however the ApplicationStopping is not.

Due to the way VS runs docker containers, your app will never get SIGTERM if the container is run from VS (even if you're not debugging).  I understand this is part of optimizing the inner dev loop to not require restarting the container every launch.

However, if you run the container another way, e.g. by right clicking on the dockerfile and selecting "Build docker image" and then running the resulting image (e.g. in Docker Desktop), you should see logger and/or console output when you send SIGTERM to the container.

Sorry this is such a gotcha - I spent a while scratching my head over it myself.

**Comment by amcasey** [comment]
VS debugging issues aside, I tested a simple worker on Windows, WLS, local linux docker, and AKS and saw the SIGTERM events in all scenarios.  I tested AKS with both .net 6 and .net 7, but did all my local testing with just .net 7.  Can you please confirm that you're not seeing the logging output in non-VS scenarios?

FYI @Ghyath-Serhal since it's been a while.

**Comment by amcasey** [comment]
This is what I see for [your repro](https://github.com/Ghyath-Serhal/SigTermKuber) with either `docker stop` or `docker kill -s TERM` (I did fix the copy-paste error in StopAsync).

```
2023-01-20 15:02:26 In the StartAsync of TestBackgroundService
2023-01-20 15:02:26 info: Microsoft.Hosting.Lifetime[0]
2023-01-20 15:02:26       Application started. Press Ctrl+C to shut down.
2023-01-20 15:02:26 info: Microsoft.Hosting.Lifetime[0]
2023-01-20 15:02:26       Hosting environment: Production
2023-01-20 15:02:26 info: Microsoft.Hosting.Lifetime[0]
2023-01-20 15:02:26       Content root path: /app
2023-01-20 15:02:38 In the OnApplicationStopping
2023-01-20 15:02:38 info: Microsoft.Hosting.Lifetime[0]
2023-01-20 15:02:38       Application is shutting down...
2023-01-20 15:02:38 In the StopAsync of TestBackgroundService
2023-01-20 15:02:38 In the OnApplicationStopped
```

**Comment by amcasey** [comment]
And from AKS
```
2023-01-20T23:12:27.931498547Z In the StartAsync of TestBackgroundService
2023-01-20T23:12:27.936843273Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-01-20T23:12:27.936857574Z       Application started. Press Ctrl+C to shut down.
2023-01-20T23:12:27.937568377Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-01-20T23:12:27.937578877Z       Hosting environment: Production
2023-01-20T23:12:27.937685178Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-01-20T23:12:27.937692778Z       Content root path: /app
2023-01-20T23:13:12.235031704Z In the OnApplicationStopping
2023-01-20T23:13:12.235188805Z [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
2023-01-20T23:13:12.235218305Z       Application is shutting down...
2023-01-20T23:13:12.242233053Z In the StopAsync of TestBackgroundService
2023-01-20T23:13:12.242326854Z In the OnApplicationStopped
```

(The color markers appear to have been cleaned up in .net core 7)

**Comment by amcasey** [comment]
I used a minimal k8s config - please let me know if you're doing something different.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gh45801pod
spec:
  containers:
  - name: gh45801container
    image: aspnetacr.azurecr.io/gh45801test:latest
```

**Comment by richlander** [comment]
I am using this pattern.


```bash
CancellationTokenSource cancellation = new();
app.Lifetime.ApplicationStopping.Register( () =>
{
    cancellation.Cancel();
});

// This API demonstrates how to integrade cancellation
// to support graceful container shutdown via SIGTERM.
// The implementation itself is an analog for a real method.
app.MapGet("/Delay/{value}", async (int value) =>
{
    try
    {
        await Task.Delay(value, cancellation.Token);
    }
    catch(TaskCanceledException)
    {
    }
    
    return new DelayValue(value);
});
```

If I call `kubectl delete po blah-pod`, it deletes within ~1s.

**Comment by Ghyath-Serhal** [comment]
@amcasey, I built the image from visual studio and tried it on docker. It is working correctly as you have mentioned.
I still need to test it on AKS.

Thank you

**Comment by Ghyath-Serhal** [comment]
@amcasey It is working fine on AKS also.
There problem is with the existing solution that I already have it was not working. It will recheck the code.
Thank you.
