### ISSUE TITLE
SignalR Client Windows Authentication returning 401Unautorized (update 6.0.11 -> 7.0.0)

### ISSUE THREAD

**Issue by LH-EA** [dotnet/aspnetcore#45371]
### Description

After updating the version of Microsoft.AspNetCore.SignalR.Client from 6.0.11 to 7.0.0 I receive a 401 (Unauthorized) when trying to start the connection using default credentials. I couldn't find any information about potential breaking changes.

```
  connection = new HubConnectionBuilder()
  .WithUrl(hubUrl, options => {
      options.UseDefaultCredentials = true;
  }).WithAutomaticReconnect().Build();
    
   await connection.StartAsync(); ---> Response status code does not indicate success: 401 (Unauthorized).
```

### Configuration
VS2022
.NET 7
Windows 10
x64
All Browsers

**Comment by BrennanConroy** [comment]
We didn't change much on the client side from 6.0 to 7.0, did you update the server at the same time? Can you try only updating one side at a time and seeing what combo creates the issue?

**Comment by LH-EA** [comment]
I upgraded server-side from 6.0.11. ---> 7.0.0 too. I downgraded the server, keeping client version at 7.0.0. The issue persisted. Now, with SignalR-Server version 7.0.0 and Client version 6.0.11 it is working, so I assumed the problem was in the new version of the client lib

**Comment by BrennanConroy** [comment]
Oh I have an idea of what's happening. I don't think Windows Auth works over HTTP2, but because the HttpClient is trying HTTP2 by default now it will successfully connect but fail any requests that require windows auth.

Try:
```csharp
private class Http11Handler : DelegatingHandler
{
    public Http11Handler(HttpMessageHandler handler)
        : base(handler)
    { }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Version = HttpVersion.Version11;
        return base.SendAsync(request, cancellationToken);
    }
}

HubConnection CreateConnection()
{
    return new HubConnectionBuilder().WithUrl(url, options =>
    {
        options.UseDefaultCredentials = true;
        options.HttpMessageHandlerFactory = handler =>
        {
            return new Http11Handler((HttpClientHandler)handler);
        };
    }).Build();
}
```

**Comment by adityamandaleeka** [comment]
Triage: We could consider servicing this in 7.0 by looking for `UseDefaultCredentials = true` and then forcing the protocol back down to 1.1.

**Comment by LH-EA** [comment]
Yes this worked. Thanks for the workaround!
