### ISSUE TITLE
OpenIdConnect in version 7.0.0 is targeting only .net core 7.0

### ISSUE THREAD

**Issue by ibe-SAG** [dotnet/aspnetcore#45370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/7.0.0/
has dependency only on net7.0.
Is it on purpose?
This leads to the fact that if we require to use LTS net6.0 we are unable to upgrade the component.

**Comment by davidfowl** [comment]
This is by design. All of the ASP.NET Core packages follow the .NET version and only target a single version. You're supposed to use the version of the package that aligns with your .NET version. So 6.0.x if you're using the current LTS.

**Comment by davidfowl** [comment]
FWIW this is the latest 6.0 version https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/6.0.11

**Comment by ibe-SAG** [comment]
> This is by design. All of the ASP.NET Core packages follow the .NET version and only target a single version. You're supposed to use the version of the package that aligns with your .NET version. So 6.0.x if you're using the current LTS.

I can understand why it is done this way, 
but it does not explain why it is not possible to use this component (OpenIdConnect) for previous versions of the framework.
Look on dependencies of for example 
https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.Abstractions
.NETFramework 4.6.2                                               No dependencies.
.NETStandard 2.0                                                     No dependencies.
net7.0                                                                      No dependencies.

Here we see relation to .NETStandard  2.0 - means we will be still able to use "DataProtection.Abstraction" in a .NET6.0 project.

OpenIdConnect miss references to other frameworks - and it leads to the issue [Package applicability in NuGet package manager](https://github.com/NuGet/Home/issues/5725) (But this is possibly another issue)

**Comment by davidfowl** [comment]
This one is special because it's a way to also use the new crypto stack on .NET Framework so that you can share cookies between the 2 applications.
