### ISSUE TITLE
Force HTTPS Redirect URIs for all Oauth flows

### ISSUE THREAD

**Issue by EdSF** [dotnet/aspnetcore#45374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The redirect uri created for External login flows _can_ have `http` as its protocol/scheme instead of (required) `https`. This will always fail...

### Expected Behavior

Ideally, the redirect uri for OAuth flows should _always_ be `https` . I haven't seen the source code of how this is evaluated but I'm _guessing_ it is evaluated based on the current request scheme (aka `Request.IsSecure`)

### Steps To Reproduce

- Fire up a new ASP.Net app with Logins.
- Add/configure and External login provider (Google, etc)
- All this works fine in local/dev
- Now publish your app to a hosting provider 
  - depending on your hosting provider's infrastructure (which you likely have no control over), your redirect uri can be `http` (not `https`). This is more likely if your provider offloads SSL instead of installing a cert on (each of your servers/apps).  This is the likely culprit since the application is running on a server without SSL configured. SSL is offloaded to some other service/appliance/concentrator, etc (very common in hosting environments). If the application tries to evaluate a connection to determine if it is secure (SSL) or not, this will likely fail (unless you do extra work with headers, etc).

### Exceptions (if any)

External login providers will now allow `http` redirect uris in OAuth flows

### .NET Version

6

### Anything else?

The issue in one image (actual production screenshot):
- the origin is `https`
- the constructed return url for external login is `http`
   - this will always fail
   - there is no custom code that overrides any of this, this occurs by default (hence I'm looking for an override just like it was in .Net Framework/MVC here: https://stackoverflow.com/questions/74630363/asp-net-identity-login-redirect-enforce-protocol-https-part-2-net-6 by overriding `OnApplyRedirect` (I can't seem to find that event specifically in .Net 6)...
![image](https://user-images.githubusercontent.com/636166/204887639-fa015ce9-d87d-440d-a1e8-3f3023a84566.png)

**Comment by Tratcher** [comment]
See our guidance for dealing with these kinds of issues when behind a reverse proxy:
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

**Comment by EdSF** [comment]
> See our guidance for dealing with these kinds of issues when behind a reverse proxy: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

Thank you! The option that got it to work was manually setting the scheme:
```
app.Use((context, next) =>
{
    context.Request.Scheme = "https";
    return next(context);
});
```
