### ISSUE TITLE
Cannot set conventions in Asp.Versioning.Mvc

### ISSUE THREAD

**Issue by sqlop** [dotnet/aspnetcore#45384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, 
I have used an old version library (Microsoft.AspNetCore.Mvc.Versioning 5.0.0). I want to migrate to Asp.Versioning.Mvc but I have a problem with Conventions.
Cannot set convention as before 
![image](https://user-images.githubusercontent.com/31932723/205003972-240ae3aa-fdb7-43ed-aac4-cd2400290e5b.png)

It seems there is no list of conventions in options anymore.
How can I set up conventions in the new library?

I have installed 
- "Asp.Versioning.Mvc" Version="6.3.1"
- "Asp.Versioning.Mvc.ApiExplorer" Version="6.3.1" 

### .NET Version

6.0.302

**Comment by javiercn** [comment]
This issue was moved to dotnet/aspnet-api-versioning#929
