### ISSUE TITLE
Analyzer to detect greater than 1 [FromBody] usage

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#45382]
## Background and Motivation

When wiring up an endpoint using minimal API, the following code compiles, but results in a runtime error:

```csharp
app.MapGet("/", ([FromBody]MyType t1, [FromBody] MyType t2) => {});
```

Currently the runtime error is:

```
InvalidOperationException: Failure to infer one or more parameters.
Below is the list of parameters that we found:

Parameter | Source
---------------------------------------------------------------------------------
t1 | Body (Attribute)
t2 | UNKNOWN


Did you mean to register the "UNKNOWN" parameters as a Service?
```

It would be better to analyze the parameters of the handler delegate during compilation and raise and error in this particular case.

### Analyzer Behavior and Message

When the analyzer encounters a ```MapXXX``` endpoint builder method with a handler delegate with more than one [FromBody] attribute it raises an error.

### Category

- [ ] Design
- [ ] Documentation
- [ ] Globalization
- [ ] Interoperability
- [ ] Maintainability
- [ ] Naming
- [ ] Performance
- [ ] Reliability
- [ ] Security
- [ ] Style
- [x] Usage

### Severity Level

- [x] Error
- [ ] Warning
- [ ] Info
- [ ] Hidden

## Usage Scenarios

In the example below both t1 and t2 parameters would be highlighted.

```csharp
app.MapGet("/", ([FromBody]MyType t1, [FromBody] MyType t2) => {});
```

## Risks

I don't think there will be any risks with this as currently doing this results in a runtime error.

**Comment by halter73** [comment]
API Review Notes:

- Usage category and error level makes sense.
- We think the message should be "At most one parameter can have a [FromBody] attribute."

API Approved!

```
Category: Usage
Level: Error
Message: At most one parameter can have a [FromBody] attribute.
```

**Comment by mitchdenny** [comment]
Merged. Tweaked the analyzer to handle the AsParameters scenario as well and tweaked the description to accomoodate.
