### ISSUE TITLE
CascadingTypeParameter not working as expected

### ISSUE THREAD

**Issue by jmezach** [dotnet/aspnetcore#45415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a bunch of components that expect an object of type `TEntity` as well as an `Expression<Func<TEntity, TProp>>` which is used to determine the name and value of a property on `TEntity` which is then subsequently used to render some HTML. This has been working fine, but right now I'm passing the instance of `TEntity` to every instance of those components and since I have a bunch of them on the same page this feels redundant.

So I thought of using `CascadingValue` at the top of the page so that I can pass down the `TEntity` instance to the components by using `CascadingParameter`. Obviously that didn't work because now the component instances don't know the type of `TEntity`. So that is when I found out about `CascadingTypeParameter`, although I couldn't find a lot of information on it. But I made a component which essentially wraps a `CascadingValue` component (which doesn't have a `CascadingTypeParameter` attribute for some reason) and now the IntelliSense is working fine. Unfortunately I'm getting an error when I try to build my project.

### Expected Behavior

I was expecting that by using `CascadingTypeParameter` the type of `TEntity` can be inferred for the components that I wrap inside of my component that has this attribute. And although that seems to work for IntelliSense, I'm not able to build the project.

### Steps To Reproduce

I've created the following `EntityProvider` component:

```razor
@typeparam TEntity
@attribute [CascadingTypeParameter(nameof(TEntity))]

<CascadingValue IsFixed="true" Value="Value">@ChildContent</CascadingValue>

@code {
    [Parameter] public TEntity Value { get; set; } = default!;
    [Parameter] public RenderFragment<TEntity> ChildContent { get; set; } = default!;
}
```

And I have the following base class for a bunch of components (only relevant pieces):

```csharp
public abstract class FieldBase<TEntity, TProp> : ComponentBase
{
        [CascadingParameter, EditorRequired]
        public TEntity Entity { get; set; } = default!;

        [Parameter, EditorRequired] public Expression<Func<TEntity, TProp>> Property { get; set; } = default!;

        protected override void OnParametersSet()
        {
            ...
        }
}
```

As well as a component that inherits the above base class, such as this `TextField` one:

```razor
@typeparam TEntity;
@typeparam TProp;
@inherits FieldBase<TEntity, TProp>;

<div class="mb-3">
    <label for="@PropertyName" class="form-label">@DisplayName</label>
    <input type="text" class="form-control" id="@PropertyName" value="@PropertyValue" readonly>
</div>
```

Now I'm trying to use these components together on a page like this:

```razor
<EntityProvider Value="@SelectedApiScope">
    <TextField Property="a => a.Name" DisplayName="Name" />
</EntityProvider>

@code {
  public ApiScope? SelectedApiScope { get; private set; }
}
```

### Exceptions (if any)

When I build my project I'm getting the following error:

```
E:\sc-demo\IdentityServerConfig\IdentityServerConfig\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_ClientDetails_razor.g.cs(117,85,117,102): error CS0411: The type arguments for method 'TypeInference.CreateTextField_0<TEntity, TProp>(RenderTreeBuilder, int, int, object, int, Expression<Func<TEntity, TProp>>, int, string)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

### .NET Version

7.0.100

### Anything else?

As I mentioned the IntelliSense is working fine, so for example if I remove the `.Name` in the `Property` attribute on the `TextField` and type a new dot I do get the available fields on a `TEntity`.

**Comment by petr-horny-bsshop** [comment]
We're having a similar problem.
Consider these two simple components:
**Parent.razor**
```razor
@typeparam TArgument1
@attribute [CascadingTypeParameter(nameof(TArgument1))]

@ChildContent

@code {
    [Parameter] public RenderFragment ChildContent { get; set; }
}
```

**Child.razor**
```razor
@typeparam TArgument1
@typeparam TArgument2
@code {
}
```

**Index.razor**
```razor
<Parent TArgument1="string">
    <Child TArgument2="int" />
</Parent>
```

TArgument1 should be inferred from CascadingTypeParameter from Parent.razor. But we are getting compile time error: 
`RZ10000	The component 'Child' is missing required type arguments. Specify the missing types using the attributes: 'TArgument1'.`

**Comment by SteveSandersonMS** [comment]
@jmezach Your code worked OK when I tried it: https://blazorrepl.telerik.com/GdYvEnPH43lp234X18. If you can figure out what's different in your scenario, and post an updated version (e.g., to that REPL), please let me know.

@petr-horny-bsshop It's because no inference is taking place in your example. You're specifying the argument explicitly. If you changed it to use inference (e.g., add `[Parameter] public TArgument2 Arg2 { get; set; }` into `Child.razor` and pass some value instead of setting the generic type explicitly - `<Child Arg2="123" />`) then it would work. We probably **could** extend the type inference code generator to work with partial explicit generic types like in your case, but it's more complexity in the compiler and that usage pattern isn't common so it would be a relatively low priority.

**Comment by jmezach** [comment]
@SteveSandersonMS Thanks for your reply. I figured out where things were going wrong. First of all it turned out that I got the errors on the other pages that used the same existing `FieldBase` derived components, but without the `EntityProvider` component wrapping it, instead of the page on which I had actually made the change to wrap everything in the `EntityProvider`. I guess I was expecting the `FieldBase` components to continue to work if I would specify the `Entity` property directly. I guess it makes sense since I changed that property to be a `CascadingParameter` instead of just a `Parameter`, but it wasn't immediately apparent. Perhaps the error messages could be improved here. For example, I couldn't double click on the error message to go to the actual place where the issue occurs. Perhaps if that would have worked I would probably have noticed that the error was in fact on the other pages that I hadn't changed yet.

Second of all I seemed to be missing the `Value` argument to the `ChildContent` on the `EntityProvider` component. Without that it would just render the type name of `ChildContent`. Again, this makes sense, but some documentation on this feature would definitely help here.

**Comment by petr-horny-bsshop** [comment]
@SteveSandersonMS Here's a more specific example, which I don't think is that unusual.
**DataGrid.razor**
```razor
@typeparam TEntity
@attribute [CascadingTypeParameter(nameof(TEntity))]

<CascadingValue Value="Entity">
    @ChildContent(Entity)
</CascadingValue>

@code {
    [Parameter] public RenderFragment<TEntity> ChildContent { get; set; }
    [Parameter] public TEntity Entity { get; set; }
}
```

**Column.razor**
```razor
@typeparam TEntity
@typeparam TProperty
@code {
    [CascadingParameter] public TEntity Entity { get; set; }
    [Parameter] public TProperty Value { get; set; }
    [Parameter] public EventCallback<TProperty> ValueChanged { get; set; }
    [Parameter] public EventCallback<ValidationEventArgs<TEntity, TProperty>> Validate { get; set; }
}
```

**ValidationEventArgs.cs**
```cs
public record ValidationEventArgs<TEntity, TProperty>(TEntity Entity, TProperty Value)
{
     public bool IsValid { get; set; }
}
```

**Index.razor**
```razor
<DataGrid TEntity="Person" Entity="person">
    @* OK *@
    <Column @bind-Value="context.Name" />
    
    @* Error CS1503	Argument 2: cannot convert from 'method group' to 'EventCallback'  *@
    <Column @bind-Value="context.Name" Validate="ValidateName" />

    @* OK - but we have to explicitly set both type arguments :-( *@
    <Column TEntity="Person" TProperty="string" @bind-Value="context.Name" Validate="ValidateName" />        
    
    @* Error RZ10000	The component 'Column' is missing required type arguments. Specify the missing types using the attributes: 'TEntity'. *@
    <Column TProperty="string" @bind-Value="context.Name" Validate="ValidateName" />

</DataGrid>
@code
{
    private Person person = new ();

    private void ValidateName(ValidationEventArgs<Person, string> args)
    {
    }

    class Person
    {
        public string Name { get; set; }
    }
}
```
