### ISSUE TITLE
Dotnet 7 Javascript API : pass ElementReference as parameter

### ISSUE THREAD

**Issue by Timonney** [dotnet/aspnetcore#45416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In the previous IJSRuntime, it was possible to send an HTML element reference to a JS function by using ElementReference.

I didn't find a way to do it in the new Javascript API with [JSImport/JSExport]. 

Something like this :
```
[JSImport("GetWidth", ModuleName)]  
internal static partial int GetWidth(ElementReference element);
```

for now, it give the following error :
The type 'Microsoft.AspNetCore.Components.ElementReference' is not supported by source-generated JavaScript interop. The generated source will not handle marshalling of parameter 'element'.

### Describe the solution you'd like

I would like to know if there is a way to send an ElementReference that I just didn't find ?

If no, if it's something that will come later or a final design decision ?

If we can't use the ElementReference, it would require us to generate unique Ids for each element that we want to use in a JS function.

In either case, I think it should be something that appears in the documentation.

**Comment by javiercn** [comment]
@Timonney thanks for contacting us.

The `JSImport` is specific to .NET on WebAssembly which can only be leveraged inside Blazor Wasm. With that in mind, JSImport is at a lower level on the stack and does not know about Blazor Abstractions. I am not sure if there is a way to teach it about how to serialize/deserialize custom data structures.

That said, unless you have a very specific need, you should use the regular Blazor JS interop mechanism as that's what guarantees that all higher-level concepts like ElementReference and JSObjectReference are supported.

**Comment by Timonney** [comment]
@javiercn thank you for the answer

I though that JSImport would become the new way to do Interop in Blazor WASM. So, if you say that the regular IJSRuntime is still the way to go in dotnet 7 I will go with that
