### ISSUE TITLE
Blazor Webassembly standalone deployments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#45428]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Webassembly-standalone-deployment/10214878)._

---
When you add a new publish profile, the app is setup as framework-dependent in the publish profile.
When you deploy, it fails to load the app as Blazor Web assembly apps must be self-contained.
When you click to Edit the configuration on the UI, the values automatically update.
Saving the changes and publishing again results in success.

---
#### Feedback Bot on 11/28/2022, 06:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Closed and reopened the AzDO ticket instead as this is a tooling issue.
