### ISSUE TITLE
Blazor Server Get Cookie before the first render

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#45435]
### Is your feature request related to a problem? Please describe the problem.

I need to get a cookie before the first render, so I can't use JSInterop because that only works after render.

### Describe the solution you'd like

I was doing this in a component:
```
[Inject] private IHttpContextAccessor acc { get; set; }
protected override void OnInitialized()
{
    var cookies  = acc.HttpContext.Request.Cookies;
```
and it was working using IISExpress (VS Ctrl+F5), but when published on local IIS, the `HttpContext` is null

**Comment by javiercn** [comment]
@omuleanu thanks for contacting us.

You can't access the HTTP Context in Blazor. See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0#blazor-and-shared-state for details.

You need to capture the data you need when rendering the root component from `_Host.cshtml` and pass it as a parameter.

**Comment by omuleanu** [comment]
@javiercn there's no example in that link, 
in `_Host.cshtml` I can simply call `Request.Cookies`  there's no need for `IHttpContextAccessor`, 
**but how do I pass the value to:**
`<component type="typeof(App)" render-mode="ServerPrerendered"  />`

I tried: 
`@(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered, new { Theme = theme }))`
and I've added the `Parameter` to App.razor but I can't find a way to Cascade its value (CascadingValue around Router doesn't seem to do anything)
