### ISSUE TITLE
Allow acr_values to be sent when client application sends code to authorization server using asp.net core OpenIdConnectHandler

### ISSUE THREAD

**Issue by adrian-mustelier** [dotnet/aspnetcore#45443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

  I am implementing authentication using the grant_type hybrid and the OpenIdConnectHandler handler. When I make the call to the authorization endpoint, I can add the value of acr_values in the OnRedirectToIdentityProvider event. When I try to do the same in the OnAuthorizationCodeReceived event, the value of acr_values is not sent to the authorization server. I would need to be able to send this parameter when requesting the token to the token endpoint

### Describe the solution you'd like

Make it possible to send the value of acr_values when the token is requested from the authorization server

**Comment by Tratcher** [comment]
https://twitter.com/datalnet/status/1599776833012056064
![FjOYkjQWIAAj-vQ](https://user-images.githubusercontent.com/1821173/205731274-1034c3e2-bd5b-4c50-a578-fb116ee76507.jpg)

**Comment by Tratcher** [comment]
Oh, I see the confusion:
https://github.com/dotnet/aspnetcore/blob/9767efb81faaa3562841c9192e00a4c8f94a4a48/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L676-L686

ProtocolMessage in the second event is the incoming message with the code. TokenEndpointRequest is the outgoing message to the code endpoint that you need to add parameters to.

**Comment by adrian-mustelier** [comment]
Thanks a lot. Working now. My bad I forgot to check the sources!!!!.
