### ISSUE TITLE
HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#45447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.Net Core 6.0.11 application deployed to AWS EKS with ALB bumps into this error `HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.` I have configured `Kestrel.EndpointDefaults.Protocols = HTTP2`  and AWS ALB ingress with `alb.ingress.kubernetes.io/backend-protocol-version: HTTP2` but to no avail.

### .NET Version

6.0.11

**Comment by davidfowl** [comment]
Can you show your application setup?

**Comment by khteh** [comment]
What do you mean? Be more specific.

**Comment by khteh** [comment]
`"Protocols": "Http1AndHttp2AndHttp3",` does the trick. I have other applications in the cluster which are not HTTP/2 ready.

**Comment by davidfowl** [comment]
> Can you show your application setup?

Startup code and configuration.

> "Protocols": "Http1AndHttp2AndHttp3", does the trick. I have other applications in the cluster which are not HTTP/2 ready.


Glad you figured it out.
