### ISSUE TITLE
Authentication Builder Update

### ISSUE THREAD

**Issue by Folasayo-Samuel** [dotnet/aspnetcore#45452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error CS1061 'AuthenticationBuilder' does not contain a definition for 'AddGoogle' and no accessible extension method 'AddGoogle' accepting a first argument of type 'AuthenticationBuilder' could be found (are you missing a using directive or an assembly reference?)

**I already fix the bug, but I've to drop this message here for those facing the same issue.
I solved this issue by just adding: Microsoft.AspNetCore.Authentication && Microsoft.AspNetCore.Authentication.Google**

### .NET Version

6.0

### Anything else?

**VS Code**

**Comment by davidfowl** [comment]
This is expected. AddGoogle exists in a package (Microsoft.AspNetCore.Authentication.Google), see https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-7.0&tabs=visual-studio
