### ISSUE TITLE
ASP.Net Core 7.0.100 Identity Sticky session not working

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#45453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See this error from browser debug console when running ASP.Net Core 6.0.11 in AWS EKS behind ALB ingress:
```
Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
```
The ALB ingress has the following annotation:
```
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
```
and the following kubernetes `Service`:
```
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
```

### .NET Version

7.0.100

**Comment by amcasey** [comment]
Triage: @khteh Have you tried [skipping](https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-7.0&tabs=javascript#configure-additional-options-6) negotiation?  "skipNegotation" negates the need for sticky sessions if you do not need to fall back to non-websocket transports

**Comment by khteh** [comment]
Why do I need to configure this for something that I don't need / use in my application - SignalR?

**Comment by halter73** [comment]
> Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

The error comes from the SignalR JS/TS client. Are you using Blazor Server? This SO answer explains how to configure the SignalR connection Blazor Server uses for its "Circuits" to skip negotiation: https://stackoverflow.com/questions/66661507/how-to-enable-skipnegotiation-setting-in-blazor-server

And here are the docs: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#circuit-handler-options-for-blazor-server-apps

**Comment by khteh** [comment]
![Screenshot from 2022-12-14 11-17-44](https://user-images.githubusercontent.com/3871483/207496907-e02fa3f5-7f4c-4b5a-92b0-02e523728418.png)

**Comment by khteh** [comment]
Tracing the AWS ALB logs show that the requests are served from the same pod. So sticky session does work.

**Comment by khteh** [comment]
Why does it change to `wss://` scheme? Is that the root cause?

**Comment by khteh** [comment]
Secure websocket needs HTTP/1.1 to establish connection.
