### ISSUE TITLE
Angular/React .NET 6.0.404 project template.json ids match those in .NET 7

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#45462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .NET 6.0.404 SDK the Angular and React project templates use the same id in the template.json file as those project templates installed by the .NET 7.0 SDK. This prevents Visual Studio for Mac being able to use these .NET 6 project templates.

Environment: macOS 12.6.1

/usr/local/share/dotnet/templates/6.0.12/microsoft.dotnet.web.spa.projecttemplates.6.0.6.0.12.nupkg

![image](https://user-images.githubusercontent.com/372361/205677868-c712f24c-022b-47c4-8ac4-0fdef78bc79f.png)

```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Microsoft",
  "classifications": [
    "Web",
    "MVC",
    "SPA"
  ],
  "description": "A project template for creating an ASP.NET Core application with Angular",
  "groupIdentity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.Angular",
  "precedence": "9000",
  "identity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.Angular.CSharp.7.0",
  "name": "ASP.NET Core with Angular",
  "preferNameDirectory": true,
  "primaryOutputs": [
    {
      "path": "Company.WebApplication1.csproj"

```

```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Microsoft",
  "classifications": [
    "Web",
    "MVC",
    "SPA"
  ],
  "description": "A project template for creating an ASP.NET Core application with React.js",
  "groupIdentity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.React",
  "precedence": "9000",
  "identity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.React.CSharp.7.0",
  "name": "ASP.NET Core with React.js",

```

### Expected Behavior

The template.json files for the .NET 6 project templates should have an id that ends with "6.0"

Angular:
    "identity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.Angular.CSharp.6.0",

React:
    "identity": "Microsoft.DotNet.Web.Spa.ProjectTemplates.React.CSharp.6.0",

### .NET Version

7.0.101

### Anything else?

IDE: VS Mac 17.5

dotnet --info:

```
 dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
We looked this up and the template identities are actually different. So we're going to close this given that there has been no further complaints from the community.
