### ISSUE TITLE
I want to send a domain_hint from Blazor Web Assembly (using Microsoft.Extensions.DependencyInjection.MsalWebAssemblyServiceCollectionExtensions.AddMsalAuthentication ) #29440 

### ISSUE THREAD

**Issue by szalapski** [dotnet/aspnetcore#45468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Issue reference: https://stackoverflow.com/questions/63605653/is-there-a-way-to-supply-a-domain-hint-for-single-sign-on-using-msal-net-on-a-bl

domain_hint is a AuthenticationParameter of MSAL, which does not appear to be supported/exposed by the Microsoft.Authentication.WebAssembly.Msal package

Here are related issues for other Authentication parameters:
extraQueryParameter: https://github.com/dotnet/aspnetcore/issues/25391 (https://github.com/dotnet/aspnetcore/issues/25391)
loginHint: https://github.com/dotnet/aspnetcore/issues/19877 (https://github.com/dotnet/aspnetcore/issues/19925)

I believe [this issue](https://github.com/dotnet/aspnetcore/issues/29440) was unfairly closed with the suggestion that we could customize our own msal.js library.  This is not the case; msal.js supports domain hints, it is the .NET MSAL library that doesn't pass it through.

### Describe the solution you'd like

I would hope that simply adding support for additional parameters, which will be passed through to MSAL.JS, would be easy to implement, test, and support.  So in my client Program.cs, I could do:
```
WebAssemblyHostBuilder builder = WebAssemblyHostBuilder.CreateDefault(args);
...
builder.Services.AddMsalAuthentication(options =>{
    ...
    options.ProviderOptions.AddAdditionalProviderParameter("domain_hint","mydomain.com");
});
```

Alternatively, it would be acceptable to add explicit parameters for DomainHint and LoginHint.

```
    ...
    options.ProviderOptions.DomainHint = "mydomain.com";
```

Or is there some other way to do this that I am missing?

**Comment by TanayParikh** [comment]
Hey @szalapski, thanks for reaching out. This may be related to https://github.com/dotnet/aspnetcore/issues/44973 / https://github.com/dotnet/aspnetcore/issues/44854.

Can you please try out https://github.com/dotnet/aspnetcore/issues/44854#issuecomment-1311984774?

**Comment by szalapski** [comment]
@TanayParikh, thanks for the response.  AS instructed, I have added the TrimmerRootDescriptor.xml to the root of my Client project, and added the `TrimmerRootDescriptor` inside a new ItemGroup in my client's .csproj file.  I then call this to start sign-in:

```
    private void NavigateToLogin()
  {

      var requestOptions = new InteractiveRequestOptions()
      {
          Interaction = InteractionType.SignIn,
          ReturnUrl =  Navigation.Uri
      };

      requestOptions.TryAddAdditionalParameter("domain_hint", "mydomain.com");
      Navigation.NavigateToLogin(Options.Get(DefaultOptionName).AuthenticationPaths.LogInPath, requestOptions);
  }
```
No change: still asked to "Pick an account" when signing in via OIDC to Active Directory, even though the only account it knows about is the one that matches mydomain.com.

**Comment by javiercn** [comment]
@szalapski can you turn on the logs to trace level on your webassembly app? You should be able to see the exact request object being passed down to msal-browser.

**Comment by szalapski** [comment]
I got this. Is there anything wrong with it?  If not, any idea why Azure AD's login doesn't take the hint?

```
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      signIn: {"url":null,"state":{"returnUrl":"/"},"interactiveRequest":{"returnUrl":"/","scopes":null,"interaction":"SignIn","additionalRequestParameters":{"domain_hint":"genmills.com"}}} [AuthenticationService.js:2:310560](https://localhost:5008/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js)
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      signIn-Request: {"redirectUri":"https://localhost:5008/authentication/login-callback","state":"d7221a02-3cbc-4f38-a7d1-022bf21ed19e","domain_hint":"genmills.com","scopes":["9e32b5ae-f519-4632-850e-guidredacted/user_impersonation"]} [AuthenticationService.js:2:310560](https://localhost:5008/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      Starting sign-in pop-up

**Comment by javiercn** [comment]
@szalapski I am not sure about the specific way to achieve this in MSAL, my guess is that you are likely not passing the correct parameter downstream. If you want to know for sure, you can put a breakpoint on the JS right before the call to sign-in in MSAL and inspect that the values are what you expect.

What you see in the trace is literally what gets passed to msal-browser [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts#L264)

**Comment by javiercn** [comment]
@szalapski I took another look, I think you should use "domainHint" and not "domain_hint" as per https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest

**Comment by szalapski** [comment]
That's the ticket.  Wow, what a surprise.  Every other document refers to "domain_hint".
