### ISSUE TITLE
Output Caching Does not work if Authorization Header is Present

### ISSUE THREAD

**Issue by rcreynolds53** [dotnet/aspnetcore#45469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently output caching does not work if the Authorization header is present in the request. This is tough for data intensive api to api communication using Bearer Tokens. Just because the authorization header is present it does not mean that their is an active user session, a service could obtain an access token and make requests to protected endpoints. 

It does look like this was a feature that was going to be included but does not seem to have shipped. Based on the screenshot below taken for #27387
![image](https://user-images.githubusercontent.com/26964362/205751070-61486269-ed1e-4a1b-94ca-f66da7e71dd4.png)

### Expected Behavior

I would expect to be able to control if authenticated content should be cached. Does not currently behave this way.

### Steps To Reproduce

Make a request to an api with OutputCache configured that has the Authorization header present. Observe that the response is not cached. 

Make the same request to the same endpoint without the Authorization header present. Observe that it will be cached. 

### .NET Version

7

**Comment by rcreynolds53** [comment]
@sebastienros 

One of the things I tried to do was to make my own custom policy and set it as the base policy for the output cache.

Here is my custom policy, it is basically the Deffault policy but without the check on the authorization. 

`public class OutputCachePolicy : IOutputCachePolicy
    {
        public static readonly OutputCachePolicy Instance = new();

        private OutputCachePolicy()
        {
        }

        ValueTask IOutputCachePolicy.CacheRequestAsync(OutputCacheContext context, CancellationToken cancellationToken)
        {
            var attemptOutputCaching = AttemptOutputCaching(context);
            context.EnableOutputCaching = true;
            context.AllowCacheLookup = attemptOutputCaching;
            context.AllowCacheStorage = attemptOutputCaching;
            context.AllowLocking = true;

            // Vary by any query by default
            context.CacheVaryByRules.QueryKeys = "*";
            return ValueTask.CompletedTask;
        }
       // this never gets hit when Authorization is present
        ValueTask IOutputCachePolicy.ServeFromCacheAsync(OutputCacheContext context, CancellationToken cancellationToken)
        {
            return ValueTask.CompletedTask;
        }

        ValueTask IOutputCachePolicy.ServeResponseAsync(OutputCacheContext context, CancellationToken cancellationToken)
        {
            var response = context.HttpContext.Response;
            context.AllowCacheStorage = true;

            return ValueTask.CompletedTask;
        }

        private static bool AttemptOutputCaching(OutputCacheContext context)
        {
            // Check if the current request fulfills the requirements to be cached

            var request = context.HttpContext.Request;

            // Verify the method
            if (!HttpMethods.IsGet(request.Method) && !HttpMethods.IsHead(request.Method))
            {
                return false;
            }

            // Verify existence of authorization headers
            //if (!StringValues.IsNullOrEmpty(request.Headers.Authorization) || request.HttpContext.User?.Identity?.IsAuthenticated == true)
            //{
            //    return false;
            //}
            return true;
        }
    }`


Here is the setting of the policy `builder.Services.AddOutputCache(opts =>
{
    opts.AddBasePolicy(OutputCachePolicy.Instance);
});`

I notice that `ServeFromCacheAsync` never gets hit when Authorization header is present, but when I remove it from the call, it does. Is there something else in the `OutputCacheMiddleware` causing this behavior?

**Comment by sebastienros** [comment]
Did you remove the calls to `.OutputCache()` on your endpoints? If not then it's also adding the Default policy on these endpoints and it will prevent the authenticated requests from being cached, or served from cache.

**Comment by rcreynolds53** [comment]
@sebastienros 

Yep, that’s was it I had to remove the `[OutputCache]` attribute. 

Thanks for the information!

**Comment by harindaka** [comment]
Can someone link the documentation mentioned [above](https://github.com/dotnet/aspnetcore/issues/45469#issuecomment-1338323610)

**Comment by facundoLecuna** [comment]
> Can @sebastienros or someone link the documentation mentioned [above](https://github.com/dotnet/aspnetcore/issues/45469#issuecomment-1338323610). Is there no way to get builder methods to make the base policy include/cache authenticated responses?

I'm expecting the same
