### ISSUE TITLE
Force use of https on NavigationManager

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#45483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If we use nginx and proxy, we need to set the website address to http://localhost:port
https://learn.microsoft.com/pl-pl/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0#configure-nginx

```cs
.ConfigureWebHostDefaults(webBuilder =>
{
  webBuilder.UseUrls("http://127.0.0.1:5000");
  webBuilder.UseStartup<Startup>();
})
```

If we do this, at this point NavigationManager detects that we are using HTTP when Nginx is using HTTPS.

``MyNavigationManager.Uri`` then it returns us "http" instead of "https"

I was looking for a solution, unfortunately I did not find it. It's worth taking a look to see if everything is all right.
Currently, I use it on every subpage, e.g. for OG meta tag, everywhere I have http instead of https

### .NET Version

.net core 8 alpha

**Comment by Alerinos** [comment]
I noticed that server side generates http and then blazor changes us to https

I press F5 on the recording
https://gyazo.com/485bce6cbd1f2ed1ad4415a0d628a1eb

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
It looks like you may be missing a middleware in your startup. Please follow the documentation here for details: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0

**Comment by Alerinos** [comment]
@mkArtakMSFT Before writing this topic, I checked everything, I even sent a link above to the same one you just sent me.
The error still occurs, if I'm doing something wrong or I'm missing something from this documentation, please point it out. Thank you.
