### ISSUE TITLE
_blazor websocket error

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#45484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.Net Core 6 Scaffold Identity blazor application bumps into websocket error. Firstly, why `websocket` when my application doesn't need it at all!?! Where is the root cause of this error?

https://github.com/dotnet/aspnetcore/issues/45453

### Exceptions (if any)

![Screenshot from 2022-12-07 14-17-20](https://user-images.githubusercontent.com/3871483/206104531-f10ea0b6-304f-4768-916b-5d96ab1699bb.png)

### .NET Version

7.0.101

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.

**Comment by khteh** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro

**Comment by khteh** [comment]
> @khteh your app looks like a Blazor Server app. Blazor Server relies on a websocket connection to work, and that's where you get the `WebSocket` related messages. If this wasn't intentional, maybe your goal was to start from a Blazor WebAssembly-based application, which would have no requirement for websocket.
> 
> As for the error, do you get the same error when you debug / run the application locally? If not, then it's most probably the host that you're using doesn't support websockets.

Running from my local development host does not see this error at all. Only from the same app running in AWS EKS. Is there any specific setup / configuration that needs to be done?

**Comment by javiercn** [comment]
> Running from my local development host does not see this error at all. Only from the same app running in AWS EKS. Is there any specific setup / configuration that needs to be done?

You need to enable sticky sessions on your load balancer. Can you try that and let us know?

**Comment by khteh** [comment]
> > Running from my local development host does not see this error at all. Only from the same app running in AWS EKS. Is there any specific setup / configuration that needs to be done?
> 
> You need to enable sticky sessions on your load balancer. Can you try that and let us know?

Yes I do! https://github.com/dotnet/aspnetcore/issues/45453

**Comment by javiercn** [comment]
@khteh have you tried turning logging to debug level on the server and the browser to see if there are more detailed errors?

I am not sure based on your reference if you are suggesting that you tried to enable sticky sessions but were not able to do so or that you are seeing this error even after you have successfully enabled sticky sessions.

Can you provide more details?

**Comment by khteh** [comment]
Same errors after applying sticky sessions.

**Comment by javiercn** [comment]
> Firstly, why `websocket` when my application doesn't need it at all!?!

Blazor Server uses SignalR which uses websockets as a transport.

Could you please capture the server and client logs to see if that sheds some light into what is going on in your app?

Turn on the logs on the browser to debug as follows:
```html
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
    Blazor.start({
        logLevel: 1, // Debug
        configureSignalR: function (builder) {
            builder.configureLogging("debug");
        }
    });
</script>
```

Capture logs and detailed errors from the server by updating appsettings.development.json as follows:

```json
{
    "DetailedErrors": true,
    "Logging": {
      "LogLevel": {
        // …
        "Microsoft.AspNetCore.Components.Server": "Debug"
        // Also include this if you do not have enough info with the one above
        //"Microsoft.AspNetCore.Components": "Debug"
      }
    }
}
```

**Comment by khteh** [comment]
![Screenshot from 2022-12-20 11-17-40](https://user-images.githubusercontent.com/3871483/208573453-6ff9515d-4c3a-40e6-9db1-74702a446b7b.png)

Is there anything that I should look out for from the server logs? I don't find any anomaly there.

**Comment by javiercn** [comment]
@khteh the error is that in production it can't connect to the blazor endpoint. See 
![image](https://user-images.githubusercontent.com/6995051/208638712-f111dd4f-86f9-44c0-a471-fcf3f2434b95.png)

I would suggest you check the network tab for `_blazor` and see what is happening there, but somehow something is wrong in that part of the app.

**Comment by khteh** [comment]
![Screenshot from 2022-12-21 08-49-07](https://user-images.githubusercontent.com/3871483/208794655-28d84b36-d13f-4fe9-b668-442f385d98ae.png)

**Comment by javiercn** [comment]
@khteh thanks for the additional details.

I think that what is happening here is that the Login page (from what I can tell) is including the Blazor server script. It's probably being added in the layout. It is likely that scaffolding dropped a `_ViewStart.cshtml` inside `Areas/Identity`.

If you compare this against a new solution with individual auth, I think the `_ViewStart.cshtml` will not be there and identity will default to its own layout.

Removing the file should make identity fallback into its own default layout. Could you give that a try?

**Comment by khteh** [comment]
![Screenshot from 2022-12-21 18-03-37](https://user-images.githubusercontent.com/3871483/208878224-160e5e54-0306-4058-90ee-69bd7f34230e.png)

**Comment by khteh** [comment]
> @khteh thanks for the additional details.
> 
> I think that what is happening here is that the Login page (from what I can tell) is including the Blazor server script. It's probably being added in the layout. It is likely that scaffolding dropped a `_ViewStart.cshtml` inside `Areas/Identity`.
> 
> If you compare this against a new solution with individual auth, I think the `_ViewStart.cshtml` will not be there and identity will default to its own layout.
> 
> Removing the file should make identity fallback into its own default layout. Could you give that a try?

No, doesn't work!

**Comment by javiercn** [comment]
@khteh do you have a repro as a public GitHub repository we can use to take a look? We want to make sure we do not miss anything.

**Comment by khteh** [comment]
> @khteh do you have a repro as a public GitHub repository we can use to take a look? We want to make sure we do not miss anything.

Private repo

**Comment by javiercn** [comment]
> Private repo

Could you create a minimal repro project and add it to a public github repository instead?

**Comment by khteh** [comment]
@javiercn I can temporarily add you as external collaborator in our private repo.

**Comment by javiercn** [comment]
@khteh thank you, however unfortunately that won't work. We can't look at private repos due to policies we must follow, hence why we ask for a public Github repo that contains a minimal repro.

**Comment by khteh** [comment]
> 

What's the reason Blazor needs SignalR? Would it work without SignalR? Is this needed for Identity to work?

**Comment by khteh** [comment]
![Screenshot from 2022-12-28 10-53-14](https://user-images.githubusercontent.com/3871483/209749862-4e159cf2-eca7-4e04-b91c-728ec82349ca.png)

**Comment by khteh** [comment]
Why does it change to `wss://` scheme? Is that the root cause?

**Comment by javiercn** [comment]
@khteh that's how signalr works.

Something in your app is causing Identity to use the app layout instead of the built-in one, which includes the blazor server script. Blazor uses SignalR, which uses websockets. It initially negotiates the transport and then switches to it. The `wss://` scheme is for websockets.

**Comment by khteh** [comment]
Secure websocket needs HTTP/1.1 to establish connection.
