### ISSUE TITLE
Hosting bundle downgrade error when 6.0.11 exists

### ISSUE THREAD

**Issue by applemuffinironman** [dotnet/aspnetcore#45491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On a machine having hosting bundle 6.0.11 already installed, an attempt to install 6.0.10 fails with:

Error 0x80070666: Cannot install a product when a newer version is installed.

Log file attached.
[dd_dd_DotNetCoreWinSvrHosting__20221207140129.log](https://github.com/dotnet/aspnetcore/files/10179676/dd_dd_DotNetCoreWinSvrHosting__20221207140129.log)

### Expected Behavior

According to other issues, I believe downgrade failure suppression should be present that will prevent installer failure.  I think these are relevant:

https://github.com/dotnet/aspnetcore/issues/42764
https://github.com/dotnet/aspnetcore/issues/43790

Pretty sure there's also one I can't find at the moment that discusses the issue in the 5.0.x series and that it would not be fixed there.  Perhaps not important to this discussion, but it's one of the reasons we bumped our installer requirement to 6.0.10 just a few weeks ago - because the same downgrade errors happen in 5.0.x pairs.

As in the issues where this has been seen in earlier versions, we want to include hosting bundle installation as part of our own product's installer and have our installer _not_ stop with an error if a newer hosting bundle version exists on the target system.  If we need to rather monitor hosting bundle versions and always issue a new release to match, an official word to indicate this would be helpful so we'll know we need to do something different on our side.

### Steps To Reproduce

1. Install 6.0.11 hosting bundle.
2. Run 6.0.10 hosting bundle installer.
3. Observe setup failure with downgrade error.

**Comment by adityamandaleeka** [comment]
@wtgodbe PTAL. Did the downgrade failure suppression make it to 6.0.10?

cc: @NikolaMilosavljevic

**Comment by wtgodbe** [comment]
Yeah, the fix for this went into 6.0.9. Assigning to myself to investigate why it isn't working.

@applemuffinironman for now you can manually uninstall 6.0.11 before running the 6.0.10 installer.

**Comment by applemuffinironman** [comment]
@wtgodbe Acknowledged.  Our people are, unfortunately, already familiar with the workaround being required for hosting bundle, so we'll continue that for now.

Since I'm hacking on our installers at the moment anyway, I might just attempt to wrap this in a minimum version checker to mitigate the manual intervention.

**Comment by dpadilla1** [comment]
Chiming in here to say I am seeing this issue as well.
> On a machine having hosting bundle 6.0.11 already installed, an attempt to install 6.0.10 fails with:
> 
> Error 0x80070666: Cannot install a product when a newer version is installed.

Log file attached:
[netcore_bundle_in.txt](https://github.com/dotnet/aspnetcore/files/10454159/netcore_bundle_in.txt)

As per issue https://github.com/dotnet/aspnetcore/issues/43790 , this was expected to be fixed in 6.0.9. 

Has there been an update on this?

**Comment by wtgodbe** [comment]
It looks like we may have missed backporting a component of the fix - https://github.com/dotnet/arcade/pull/12277. If that does the trick, this should be fixed in the March release of 6.0.

**Comment by anujgoelmsft** [comment]
This is a blocker for some of our scenarios. Would love to see if the fix can be shipped in the February release.

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/arcade/pull/12277
