### ISSUE TITLE
RFC - add a way to specify/configure which static assets get published from an RCL

### ISSUE THREAD

**Issue by vnbaaij** [dotnet/aspnetcore#45498]
Say I have an RCL that contains a very large number of static asses (think ~20k `.svg` files for icons/emojis). I would like to offer the developers using my RCL to be able to select/configure which of the assets would get published. For instance, just publish 'color emojis' or 'icons with a size of 24x24'.
There are a couple of reasons for wanting to do this:
- It decreased deployment time
- It reduces storage needs on the hosting environment 
- It allows developers to precisely determine what their users can use
- It doesn't blow up the service workers size when creating a PWA

**Comment by mkArtakMSFT** [comment]
@javiercn do you know if there is an existing way to achieve this today?

**Comment by javiercn** [comment]
There is already a way to achieve this through MSBuild extensibility. 
Identity does this by providing its own MSBuild targets. See https://github.com/dotnet/aspnetcore/tree/main/src/Identity/UI/src/build

**Comment by vnbaaij** [comment]
We have built a mechanism for this in the [Fluent UI Blazor library] (https://github.com/microsoft/fluentui-blazor) based on what @javiercn mentioned earlier.
