### ISSUE TITLE
POST without Content-Length - 411 Length required

### ISSUE THREAD

**Issue by dantesg** [dotnet/aspnetcore#45495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's not possible to accept POST requests without Content-Length header.
Due to a third-party integration I need to accept POST requests regardless of Content-Length Header.

I found an issue where this is discussed but I can't continue discussion there for HTTP 1.1 #29398

It seems to be a bug because the client application already works as-is and connects to another server (another company, so no context) but when I target .net7 it doesn't work.

I've even tried implementing a middleware to try to capture the request and add the required Header but it fails before the middleware:
```
app.Use(async (context, next) =>
{
    if (context.Request.Method == "POST")
    {
        context.Request.Headers.ContentLength ??= 0;
    }
    await next.Invoke();
});
```

### Expected Behavior

It's expected that I could accept POST requests without Content-Length Header or to be able to configure to bypass current restriction

### Steps To Reproduce

I've put together an example of the third-party calling the net7.0 minimal API request [here](https://github.com/dantesg/NetHttpClientIssue)
To run the example just change the address on the Client consuming the .net7 to whatever address:port you're running on.

### .NET Version

7.0

**Comment by adityamandaleeka** [comment]
@dantesg I'm not able to reproduce this issue... it looks like the POSTs without Content-Length are working fine?

I first tried with your server app and curl as the client, e.g.

`curl -v localhost:5284 -d 'aa' -H Content-Length: -H "Content-Type: application/json" -H "Accept: application/json"`

which worked, and then for good measure I also tried making a `HttpWebRequest` similar to how your client code does it, and that worked as well. Here's what that looked like (and you can see the `retValue`):

<img width="825" alt="image" src="https://user-images.githubusercontent.com/219224/206336729-77a52e32-848b-4674-ba2f-5de8bb50bf56.png">


What do you see when you run the curl command I ran?

**Comment by adityamandaleeka** [comment]
The fact that it's working is what I'd expect by the way, given that the original issue you linked was fixed in .NET 6.

**Comment by dantesg** [comment]
@adityamandaleeka I've tried with the curl command above and it didn't work for me as well. Here's the response:

```
*   Trying 127.0.0.1:54539...
* Connected to localhost (127.0.0.1) port 54539 (#0)
> POST / HTTP/1.1
> Host: localhost:54539
> User-Agent: curl/7.83.1
> Content-Type: application/json
> Accept: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 411 Length Required
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< Date: Thu, 08 Dec 2022 02:18:51 GMT
< Connection: close
< Content-Length: 344
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
* Closing connection 0
```

I'm running the `ServerApiNet7/MinimalApi` on .net 7.0.100 and the curl command
Is there anything I can try or provide you with in order to get this to work?

**Comment by dantesg** [comment]
btw, just to clarify I understand it's an easy fix: just adding the Header `Content-Length: 0` (or any number) solves the issue but the context is that I can't change the code making the request

**Comment by adityamandaleeka** [comment]
@dantesg I see the problem. It looks like you're running your server on IIS Express and not Kestrel. If you run it with Kestrel instead (which is our recommendation), you'll be able to do POSTs without Content-Length.

**Comment by dantesg** [comment]
@adityamandaleeka I didn't know that. Thanks for your help, it solved my issue.

**Comment by Tratcher** [comment]
Server: Microsoft-HTTPAPI/2.0 is HttpSys.
