### ISSUE TITLE
Update TFM to net8.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#45492]
Runtime has updated their TFM, so we need to do ours too. Ongoing work in https://github.com/dotnet/aspnetcore/pull/45475

Todo - 

- [x] Update branding & template precendence in spa-templates
- [x] Update template precedence in aspnetcore
- [x] Get a net8.0 SDK & do https://github.com/dotnet/aspnetcore/blob/main/docs/UpdatingMajorVersionAndTFM.md
- [x] Update https://github.com/dotnet/aspnetcore/blob/main/docs/UpdatingMajorVersionAndTFM.md as discussed in https://github.com/dotnet/spa-templates/pull/105#discussion_r1051486776. That is, we'll use `9{major}00` for 8.0 and 9.0, then `{major}000` (aka `{major} x 1000`) forever after. If we did 8.1, the `precedence` should be `9810`. If we did 10.1, `11000`.
- [x] Mark API from 7 as shipped
- [x] Unskip Microbenchmark validation in `Microsoft.AspNetCore.Server.HttpSys.Microbenchmarks`

**Comment by radical** [comment]
What's the next step here?

**Comment by wtgodbe** [comment]
The TFM is already updated, I'm going to work on ingesting a net8.0 SDK today so we can get the last few things done. But for those who are ingesting new aspnetcore bits, everything should already be on net8.0.

**Comment by dougbu** [comment]
One bullet down but I also added a bullet covering our conversation in https://github.com/dotnet/spa-templates/pull/105#discussion_r1051486776
