### ISSUE TITLE
Add asterisks for required input fields 

### ISSUE THREAD

**Issue by MarisaDe** [dotnet/aspnetcore#45505]
**Is your feature request related to a problem? Please describe.**
Hi all! I attended the Blazor workshop at DEVIntersection where we went over how to build the pizza app from this repo: https://github.com/dotnet-presentations/blazor-workshop.

For Session 5, we added an address form and showed validation messages after the user attempts to submit the form. I inquired if there was a way (out of the box) to show the user which fields are required before they submit the form. (Perhaps by showing red asterisks). From what I understand, there isn't a way to do this without manually adding it yourself. 

**Describe the solution you'd like**
It would be awesome to show asterisks on required fields so the user knows which fields are required prior to submitting a form.

**Additional context**
I spoke with @csharpfritz at the DEVIntersection conference about this and he suggested I create this feature request. Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
