### ISSUE TITLE
Missing JWT token with Safari (macOS and iOS)

### ISSUE THREAD

**Issue by erossini** [dotnet/aspnetcore#45501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had this behaviour roughly a year ago. Now, in my new application, I'm facing the same issue, but the old solution didn't work. So, I have a Blazor application with NET6. When the application calls the API, I add the user token in the `Header`. 

```csharp
request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
```

To retrieve the user token, I have a function that read the token from the cache or from `IAccessTokenProvider`.

```csharp
IAccessTokenProvider _accessToken;
private async Task<AccessToken> RequestUserToken()
{
    try
    {
        var tokenResult = await _accessToken.RequestAccessToken();
        tokenResult.TryGetToken(out var token);

        Console.WriteLine(token);

        return token;
    }
    catch (AccessTokenNotAvailableException aex)
    {
        throw new ApplicationException($"Exception {aex}");
    }
    catch (Exception ex)
    {
        throw new ApplicationException(
            $"AccessTokenNotAvailable Exception Exception {ex}");
    }
}
```

The application sends successfully requests to the API from Windows and Android. When I run the application on macOS and iOS devices, the token is not found and then there is an error.

![image](https://user-images.githubusercontent.com/9497415/206483416-b401c6f1-3726-40ce-aec3-391d300fb6f7.png)

To debug this issue, I run the web application on a Mac. On the Mac, the application is working fine with Microsoft Edge and Chrome but not with Safari.

On iPhone and iPad, this issue is present on Safari and Chrome. It works fine on Microsoft Edge.

Previously, I checked that on macOS and iOS the token could be read only once and then the browser forgets it.

I received a suggestion from the [Microsoft Forum](https://learn.microsoft.com/en-us/answers/questions/1120050/send-a-request-to-an-api-with-jwt-token-from-ios-w.html?childToView=1121287#comment-1121287) to add in the `ws:` and `wss:` like that

```csharp
app.Use((context, next) =>
{
    context.Response.GetTypedHeaders().CacheControl =
        new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
        {
            MustRevalidate = true,
            NoCache = true,
            NoStore = true,
        };

    string oidcAuthority = builder.Configuration.GetValue(typeof(string), "oidc:Authority").ToString();
    string mainUrl = "https://*.mydomain.com/";

    context.Response.Headers.Add("X-Content-Type-Options", "nosniff");
    context.Response.Headers.Add("Content-Security-Policy",
        $"default-src 'self' {mainUrl} {oidcAuthority} 'ws:' 'wss:' " +
            "https://code.cdn.mozilla.net " +
#if DEBUG
            "https://dc.services.visualstudio.com " +
#endif
            "https://api.mydomain.com " +
            "'unsafe-inline' 'unsafe-eval'; " +
        $"script-src 'self' {mainUrl} 'unsafe-inline' 'unsafe-eval'; " +
        $"connect-src 'self' {oidcAuthority} https://code.cdn.mozilla.net https://api.mydomain.com;" +
        $"img-src 'self' {mainUrl} data:; " +
        $"style-src 'unsafe-inline' {mainUrl} " +
            "https://code.cdn.mozilla.net " +
            ";" +
        "base-uri 'self'; " +
        "form-action 'self'; " +
        "frame-ancestors 'self';");
    context.Response.Headers.Add("Referrer-Policy", "same-origin");
    context.Response.Headers.Add("Permissions-Policy", "geolocation=(), microphone=()");
    context.Response.Headers.Add("X-XSS-Protection", "1; mode=block");
    context.Response.Headers.Add("X-Frame-Options", "SAMEORIGIN");
    context.Response.Headers.Add("SameSite", "Strict");

    return next.Invoke();
});
```

###  Add more details

I'm creating application with Blazor in NET6. To call the API via an Azure API Management, I have to pass a token in the request adding

```csharp
    request.Headers.Authorization = 
        new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
```

In this request, I have to pass the token that comes from an `Identity Server`. So, first, the user has to authenticate to the identity server and then receives the JWT token.

The configuration is 

```csharp
    builder.Services.AddOidcAuthentication(options =>
    {
        builder.Configuration.Bind("oidc", options.ProviderOptions);
        options.UserOptions.RoleClaim = "role";
    })
    .AddAccountClaimsPrincipalFactory<MultipleRoleClaimsPrincipalFactory<RemoteUserAccount>>();
    
    builder.Services.AddAuthorizationCore();
```

Also, to apply the security, I add in the _Program.cs_ this lines

```csharp
    app.Use((context, next) =>
    {
        context.Response.GetTypedHeaders().CacheControl =
            new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
            {
                MustRevalidate = true,
                NoCache = true,
                NoStore = true,
            };

        string oidcAuthority = builder.Configuration.GetValue(typeof(string), "oidc:Authority").ToString();
        string mainUrl = "https://test.mywebsite.com/";
    #if DEBUG
        mainUrl = "https://localhost:7040";
    #endif

        context.Response.Headers.Add("X-Content-Type-Options", "nosniff");
        context.Response.Headers.Add("Content-Security-Policy",
            $"default-src 'self' {mainUrl} {oidcAuthority} " +
                "https://code.cdn.mozilla.net " +
    #if DEBUG
                "https://dc.services.visualstudio.com " +
    #endif
                "https://api.myapi.com " +
                "'unsafe-inline' 'unsafe-eval'; " +
            $"script-src 'self' {mainUrl} 'unsafe-inline' 'unsafe-eval'; " +
            $"connect-src 'self' {oidcAuthority} https://code.cdn.mozilla.net https://api.myapi.com;" +
            $"img-src 'self' {mainUrl} data:; " +
            $"style-src 'unsafe-inline' {mainUrl} " +
                "https://code.cdn.mozilla.net " +
                ";" +
            "base-uri 'self'; " +
            "form-action 'self'; " +
            "frame-ancestors 'self';");
        context.Response.Headers.Add("Referrer-Policy", "same-origin");
        context.Response.Headers.Add("Permissions-Policy", "geolocation=(), microphone=()");
        context.Response.Headers.Add("X-XSS-Protection", "1; mode=block");
        context.Response.Headers.Add("X-Frame-Options", "SAMEORIGIN");
        context.Response.Headers.Add("SameSite", "Strict");

        return next.Invoke();
    });
```

So, after that I can read the JWT token with this code:

```csharp
    IAccessTokenProvider _accessToken;
    private async Task<AccessToken> RequestUserToken()
    {
        try
        {
            var tokenResult = await _accessToken.RequestAccessToken();
            tokenResult.TryGetToken(out var token);
    
            Console.WriteLine(token);
    
            return token;
        }
        catch (AccessTokenNotAvailableException aex)
        {
            throw new ApplicationException($"Exception {aex}");
        }
        catch (Exception ex)
        {
            throw new ApplicationException(
                $"AccessTokenNotAvailable Exception Exception {ex}");
        }
    }
```

The application is working on Windows for any browser. On iOS and macOS I can read the token if I use Safari. It is working if I use Microsoft Edge and Chrome.

Do you have any idea how can I fix it?

**Comment by erossini** [comment]
Hi guys,
do you have any update for it? Can I do anything to help you?

**Comment by javiercn** [comment]
@erossini thanks for contacting us.

I am not 100% sure of what/how you are using the auth bits. Could you create a minimal repro project as a public github repository so that we can take a look?

**Comment by erossini** [comment]
Hi @javiercn, I have just came back from holiday. I'll create a project asap.

**Comment by erossini** [comment]
I have just created this repo [here](https://github.com/erossini/BlazorJWTTest) (sorry the project is very basic without CSS).

When you run the application, click on *Log in*. Then, you will redirect to the Identity Server when you can use the following credentials:

Username: MSTest
Password: MSTest!2023

Then, you can see a new link called *Simulation*. The *Simulation* calls the API using the user token.

For your convenient, I deployed the test website [here](https://azuks-chi-220156-app-wa-d2.azurewebsites.net/) 

When you run the app on Windows with Edge, for example, you can see that the call to the API is working.

![image](https://user-images.githubusercontent.com/9497415/210386441-81c09fdf-5bd2-4b91-a7c0-2c2b10600b93.png)

But when you run the website on an iPhone you get an error.

![image](https://user-images.githubusercontent.com/9497415/210387252-93633ad0-b148-49d4-862c-343127aaaa37.png)

**Comment by erossini** [comment]
HI @javiercn @mkArtakMSFT @blowdart @radical 
Happy New Year all!

Did you have a chance to see my demo?

**Comment by javiercn** [comment]
@erossini we are coming back from the holidays, it'll take a bit until we catch up.

**Comment by IvanJosipovic** [comment]
I am also seeing this problem in Blazor in .Net 7. 95% of the exceptions are from Macs.

NuGet Packages = 7.0.2
SDKversion = 7.0.102

![image](https://user-images.githubusercontent.com/9521987/215165644-808baf96-e94d-4cfc-a282-88f4bd096d46.png)

**Comment by surayya-MS** [comment]
@erossini, thank you for providing a demo. I was able o reproduce the bug on a Mac using Safari.

**Comment by surayya-MS** [comment]
I did some more digging and seems like it is not a Blazor bug.

@erossini, in the demo you provided [token](https://github.com/erossini/BlazorJWTTest/blob/main/Conjoint/Client/Services/ApiTokenCacheService.cs#L55) is null and the reason is that Safari is no longer sending cross-site cookies. 
The only fix for this that I could find is:
allow sending cross-site cookies, Go to Safari > Preferences > Privacy and uncheck Prevent cross-site tracking.
 
You could maybe show these instructions on Home page for Safari users so they could use your app.

**Comment by erossini** [comment]
OK, I can add an alert for the user. What I don't understand is the token has a value and the user is recognized across the application for all the time the user is using the website.

In fact, the user is logged and I can get its details like email reading the claims. The token is null only when I read it in the function where I call the APIs.

Generally speaking, if I have a website like an e-commerce, it is very unlike that users change the Privacy settings only for my website, I'm not Microsoft. So, it could be big loss of users.

Could you recommend a workaround?

**Comment by erossini** [comment]
@javiercn do you have any update about it?
Thank you in advance.

**Comment by javiercn** [comment]
@erossini I have been out for a couple of weeks.

I believe I chatted with @surayya-MS that was looking into it, but I don't remember the exact conclusions. Let me check with her again.

**Comment by erossini** [comment]
In attachment 2 files: one is the logging client side on macOS from Safari, the other one on Windows 10 on Microsoft Edge.

[Cosole-Windows-Edge.log](https://github.com/dotnet/aspnetcore/files/10754125/Cosole-Windows-Edge.log)
[Console macOS.txt](https://github.com/dotnet/aspnetcore/files/10754126/Console.macOS.txt)

**Comment by javiercn** [comment]
@erossini this is not using .NET 7.0, isn't it? The improved logging is only available in .NET 7.0

**Comment by erossini** [comment]
Sorry, my bad. Here the new logs

[Console-macOS-Safari.txt](https://github.com/dotnet/aspnetcore/files/10754881/Console-macOS-Safari.txt)
[Console-Windows-Edge.log](https://github.com/dotnet/aspnetcore/files/10754882/Console-Windows-Edge.log)

**Comment by javiercn** [comment]
@erossini I see now what is happening.

There is an error in your app in the line that I pointed you to. `RequestAccessToken` only deals with provisioning a token without user interaction. In OIDC this is done via a hidden iframe that gets rendered on to the page. Safari Intelligent Tracking Prevention is blocking the cookie from being sent on the hidden iframe, which is why Surayya's suggestion works, as it disables that mechanism.

On your app, you are failing to check for the result of `AccessTokenResult` if you do, you'll see that it has an error status on it, hence why `TryGetToken` returns false. This is all expected so far, and the way to deal with it, is by performing the authentication flow interactively.

I am not sure what provider you are using, but the way this works in AAD is that the flow is code+PKCE and a refresh_token with a duration of 24h is emitted, which the app then uses to refresh the access tokens when needed.

This is also why our built-in handler throws an exception when it can't provision the token, so that you can perform an interactive flow and provision the token that way.

**Comment by erossini** [comment]
@javiercn thank you so much for your message. I use the Identity Server implemented by Skoruba (https://github.com/skoruba/Duende.IdentityServer.Admin). The connection is via `AddOidcAuthentication`. You can see my settings in the demo project.

The flow is that the user has to login against the Identity Server and then the Identity Server redirects the user to the `Authentication` page ([here the code](https://github.com/erossini/BlazorJWTTest/blob/main/Conjoint/Client/Pages/Authentication.razor)).

How can I fix my project then?

**Comment by javiercn** [comment]
@erossini unfortunately, that type of guidance is outside of the scope that we can provide in this repo. If you are using a third-party identity provider, you need to check in their docs how to configure the flow.

**Comment by erossini** [comment]
OK. What is the best practice/recommendation for working with OIDC? What is the best practice/recommendation for protecting the APIs based on OIDC?

Thank you in advance.

**Comment by javiercn** [comment]
> OK. What is the best practice/recommendation for working with OIDC? What is the best practice/recommendation for protecting the APIs based on OIDC?

There are multiple options and each one has different trade-offs, what I can tell you is that `Code+PKCE` is what AAD and AAD B2C use, and it is a generally accepted solution for SPAs.
