### ISSUE TITLE
Nullable `[FromQuery]` primitive says "The value 'null' is not valid"

### ISSUE THREAD

**Issue by snebjorn** [dotnet/aspnetcore#45500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`null` cannot be sent to a query parameter.

Given this ApiController
```cs
[ApiController]
[Route("/api/[controller]")]
public class FoosController : ControllerBase
{
    [HttpGet]
    // note the default value is just to help see if null was passed or the parameter was omitted
    public IActionResult Get([FromQuery] int? foo = 42) 
    {
        return Ok(foo);
    }
}
```
**Note:** *the default value is just to help see if null was passed or the parameter was omitted*.

This is the result:

- `GET /api/foos?foo=null` -> The value 'null' is not valid.
- `GET /api/foos?foo=` -> 42
- `GET /api/foos?foo` -> 42
- `GET /api/foos?` -> 42

This is unfortunate as there's a difference between omitting the `foo` param and setting it to `null`

### Expected Behavior

- `GET /api/foos?foo=null` -> null
- `GET /api/foos?foo=` -> 42
- `GET /api/foos?foo` -> 42
- `GET /api/foos?` -> 42

### Steps To Reproduce

1. Call  `GET /api/foos?foo=null`
2. Observe this error

```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-52ecb8b97f812e46240c706a0a1b1d8a-1d9f488b55aaca74-00",
    "errors": {
        "foo": [
            "The value 'null' is not valid."
        ]
    }
}
```

### .NET Version

7.0.100

### Anything else?

This is somewhat related https://github.com/dotnet/aspnetcore/issues/40415 though it's for POST requests.
There's an interesting discussion about how to set query params to null. Examples: `?key`, `?key=` or `?key=null`. 
My vote is on `?key=null`.

dotnet --info
> .NET SDK:
>  Version:   7.0.100
>  Commit:    e12b7af219
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
> 
> Host:
>   Version:      7.0.0
>   Architecture: x64
>   Commit:       d099f075e4
> 
> .NET SDKs installed:
>   5.0.408 [C:\Program Files\dotnet\sdk]
>   6.0.403 [C:\Program Files\dotnet\sdk]
>   7.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download

**Comment by captainsafia** [comment]
Triage: The reason this is happening is because the query parameter `?foo=null` is being interpreted as a `foo` key with the value being the string "null". When the model binding layer of MVC attempts to bind this "null" (string) to an integer the binding fails because it is not parseable.

You can consider leveraging a [resource filter](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0#resource-filters) to preprocess the parameter yourself before model-binding kicks in.

**Comment by snebjorn** [comment]
Hmm perhaps I can use the resource filter. But I cannot figure out how to do it :(
The parameters appear to be `readonly`.

```cs
public class TestFilter : IResourceFilter
{
    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        context.HttpContext.Request.Query["foo"] = 123; // this is readonly
    }
}
```

**Comment by captainsafia** [comment]
> The parameters appear to be readonly.

Yes, in this case you would have to override the `Query` collection in this case.

> Also how am I supposed to fix it :) Given that the foo is already parsed as null and the Query type is KeyValuePair<string, StringValues> where StringValues being only strings. So the string "null" is the only possibility.

Indeed, you may to implement a custom value provider.

@snebjorn By the way, is there a particular reason that you want this behavior?

**Comment by halter73** [comment]
> I "solved" this by treating -1 as null. It works but it feels very old and is less intuitive than sending null to turn off the limit.

Another option is to leave out the query string parameter when it's unspecified.
