### ISSUE TITLE
[Question] Trigger async Event in blazor server side app 

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#45510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to raise an event within my service to check something within a blazor server app. 

Lets consider this service for example:

    public class TestService
    {
        public static event AsyncEventHandler<EventArgs> OnTest;
    
        public async Task DoSomethingAsync()
        {
    
            // DO SOMETHING
            Console.WriteLine("Test");
            await Task.Delay(50);
    
            await OnTest.Invoke(this, EventArgs.Empty);
        }
    }
    
    public Task AsyncEventHandler<TEventArgs>(object sender, TEventArgs e) where TEventArgs : EventArgs;

It has a method `DoSomethingAsync` which invokes my `AsyncEventHandler`.

When the page loads, it registers itself to the event like this:

    protected override Task OnInitializedAsync()
    {
        TestService.OnTest += TestService_OnTest;
        return base.OnInitializedAsync();
    }
    
    private async Task TestService_OnTest(object sender, EventArgs e)
    {
        throw new Exception();
    }
    
    public ValueTask DisposeAsync()
    {
        TestService.OnTest -= TestService_OnTest;
    
        return ValueTask.CompletedTask;
    }

The `AsyncEventHandler` allows me to `await` the `Invoke` method of my event. This results in the user who instanciated the event to crash as expected.

With my approach above User2 gets the exception as expected. But the Exception for User1 will be thrown but isn't visible anywhere. His page is still fully working without any yellow banner of death.

What I want to do is this:

- User1 is on Page a and selects some elements
- User2 is on the same page as User1 and selects some elements and he/she is pressing save before User1
- I want the page of User1 to revalidate his selects based on the selects that User2 did (so he can't select what User2 has already selected)
- If the code raises any exception, I don't want it to be fire and forget for either User2 and User1.

How can I achive this?

### .NET Version

7.0.100

**Comment by Nick-Stanton** [comment]
Hi @MarvinKlein1508, while this specific example does not currently exist in Blazor, it is possible to externally trigger a render on a component which updates the state. Please see https://learn.microsoft.com/aspnet/core/blazor/components/rendering?view=aspnetcore-7.0#receiving-a-call-from-something-external-to-the-blazor-rendering-and-event-handling-system for more information regarding external triggers.
