### ISSUE TITLE
Start tracking "Stage 1" app in performance lab/infrastructure

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#45523]
We should add a simple minimal API application to our performance lab. For now we can start with a templated app:

`dotnet new webapi --use-minimal-apis --no-openapi --no-https`

and publish it:

`dotnet publish -c Release -p:PublishAot=true -p:TrimMode=full -p:StripSymbols=true`

Measuring the following metrics:
- RPS and latency
- Publish size/container size
- Working Set (before and after load)
- Startup time

We should also consider what other runtime app models we want to measure. We should also measure combinations of:

* PublishTrimmed
* PublishSingleFile
* PublishReadyToRun
* EnableCompressionInSingleFile

**Comment by mitchdenny** [comment]
Just getting our first results through now, there was initially an error (JSON serialization) which was causing problems, but here is the RPS and latency for the Goldilocks scenario (AOT vs non-AOT): 



![Image](https://user-images.githubusercontent.com/513398/207982162-9da65069-1ef1-4a2d-89a7-9deb6eb392cd.png)

**Comment by mitchdenny** [comment]
Looks like the RPS is lower for AOT (surprising to me). Latency is about the same.
