### ISSUE TITLE
Add Project Template for an API application with minimal dependencies

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#45526]
Related to https://github.com/dotnet/aspnetcore/issues/32485

We should have a template that produces an API application, but is very bare-bones, can be published using `PublishAot=true` with no warnings, and produces a minimally sized executable.

This template would:

* Take advantage of the API proposed in #32485 
* Have an endpoint that returns an `application/json` response using JSON source generation
* Have `TrimMode=full` by default
* Optionally have `PublishAot=true|false`
* Configure any source generators needed for trim/AOT safety.
    - https://github.com/dotnet/aspnetcore/issues/45524

cc @DamianEdwards

**Comment by DamianEdwards** [comment]
More strawman details. These will likely evolve during .NET 8:

```shell
> dotnet new api -aot
```

- Has a template option `--publish-aot` with alias `-aot` that writes the property `<PublishAOT>true</PublishAOT>` to the .csproj file
- Has no template option to control use of HTTPS and does **not** have HTTPS configured (in code or `launchSettings.json` launch profiles)
- Is configured to use workstation GC via property `<ServerGarbageCollection>false</ServerGarbageCollection>` in the .csproj file
- Does **not** have `appsettings.json` file (the empty/slim host does not have the settings files config provider added)
- Has single `MapGet` call that declares a JSON-returning endpoint
- No option for using `ApiControllers` (can change in the future as NativeAOT support expands)

**Comment by DamianEdwards** [comment]
Completed in #43756
