### ISSUE TITLE
Is it possible to start an Blazor project with custom headers?

### ISSUE THREAD

**Issue by paule96** [dotnet/aspnetcore#45533]
I'm currently working on an upgrade of the project [CZ.Azure.FileExchange](https://github.com/codez-one/CZ.Azure.FileExchange) to dotnet 7.
And one of the main benefits I was seeing is the support for multithreading in dotnet 7. 
But this requires some custom headers to be set, so the browser accepts this workflow. It is described in [this blog post](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/#webassembly-multithreading-experimental).

There is also mentioned that you can just publish your blazor project and serve it with `dotnet-serve`.

But that is a bit far away from a visual studio workflow, where we developers are very glad that we have almost always an F5 experience.

So the question is, is there some ability for simply `dotnet run` or other tools to add headers to the local development server?
And if so how to configure that?

I guess I would expect something like that in the `launchsettings.json` file. But I already search for it, and can't find usefull information

**Comment by MackinnonBuck** [comment]
We will look at enabling all of these scenarios in .NET 8: https://github.com/dotnet/aspnetcore/issues/17730.

You can work around this today by running as an ASP.NET Core hosted app and setting the headers in the server project.

**Comment by paule96** [comment]
thank you for the clarification. And thanks for the Tipp.
