### ISSUE TITLE
SignalR role base authorization not working

### ISSUE THREAD

**Issue by co-dax** [dotnet/aspnetcore#45530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had impemented role based authorization with the following pattern and it works for rest API:

`
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public class CustomAuthorizeAttribute : AuthorizeAttribute, IAuthorizationFilter
{
    private readonly string _someFilterParameter;

    public CustomAuthorizeAttribute(string someFilterParameter)
    {
        _someFilterParameter = someFilterParameter;
    }

    public void OnAuthorization(AuthorizationFilterContext context)
    {....}
}
`

...now in the context of SignalR I have applied that same attribute to both Hub class and its methods but the OnAuthorization method from above never gets called when a method in a Hub is invoked from the client by calling HubConnection.invoike(...). 
OnAuthorization(...) method from above does get called in context of rest API calls but it does not seem to be working in the context of SignalR

Am I missing something?

### .NET Version

6.0

**Comment by BrennanConroy** [comment]
`IAuthorizationFilter`, which lights up `OnAuthorization`, is an MVC only concept thus does not work with SignalR.

If you want to do role based authorization that isn't MVC specific check out the docs:
https://learn.microsoft.com/aspnet/core/security/authorization/roles?view=aspnetcore-7.0

**Comment by co-dax** [comment]
@BrennanConroy Great, it works.

Thanks for instant response and help!
