### ISSUE TITLE
404 with _content/Microsoft.AspNetCore.Components.CustomElements/BlazorCustomElements.js

### ISSUE THREAD

**Issue by tstockwell** [dotnet/aspnetcore#45558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the package Microsoft.AspNetCore.Components.CustomElements we are supposed to reference the script _content/Microsoft.AspNetCore.Components.CustomElements/BlazorCustomElements.js (as explained [here](https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements)) but this ends up with a 404 error on that file because it is not available in the binaries nor in the published folder.

It looks like in release 7.0.0 the correct script should now be ...  
_content/Microsoft.AspNetCore.Components.CustomElements/Microsoft.AspNetCore.Components.CustomElements.lib.module.js

See [previous related issue](https://github.com/dotnet/aspnetcore/issues/36539).

**Comment by javiercn** [comment]
@tstockwell thanks for contacting us.

You no longer need to do that, the required javascript gets automatically imported on to the page via a JS initializer.

**Comment by tstockwell** [comment]
@javiercn I'm still educating myself about js initializers and boot loading, but I took a quick look at your [design for blazor js initialization](https://github.com/dotnet/aspnetcore/issues/32353) and have a question...

I'm trying to create a Razor Pages application that hosts custom elements created with Blazor.
Looking over your design doc I see this...
```
MVC and Razor pages applications won't do anything by default with the manifest, and it is up to developers to provide a small snippet to perform the loading whenver and however they see fit.
```
So, right now I'm putting this into my _Layout.cshtm in my Razor Pages app...
```
<script src="_content/Microsoft.AspNetCore.Components.CustomElements/Microsoft.AspNetCore.Components.CustomElements.lib.module.js"></script>
<script src="_framework/blazor.webassembly.js"></script>
```

Is there now a better way for Razor Pages applications to boot CustomElements and Blazor in the browser?

**Comment by javiercn** [comment]
@tstockwell you do not need to do that. `<script src="_framework/blazor.webassembly.js"></script>` will automatically import them.

**Comment by mkArtakMSFT** [comment]
We have documented this in here: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements

We'll make sure to remove the content that you referenced.
