### ISSUE TITLE
QuickGrid: Full support for localization

### ISSUE THREAD

**Issue by fjallemark** [dotnet/aspnetcore#45556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

For example the Paginator component has hard coded labels, which makes localization impossible. 

### Describe the solution you'd like

By adding the option to set these labels for the component, for example with [Parameter]s, I can use IStringLocalizer to set the labels I want. This problem may exist in other components as well.

### Additional context

Note that localization works fine for the different type of columns.

**Comment by fjallemark** [comment]
Hi, I have made a pull request to solve this issue:
https://github.com/aspnet/AspLabs/pull/566

**Comment by Nick-Stanton** [comment]
Hi @fjallemark, thank you for your contribution! QuickGrid has now been productized in #46317 and will no longer receive changes in AspLabs. When convenient, please open a new PR against the version in the ASP.NET Core repository.
