### ISSUE TITLE
Add ASPNETCORE_URLS_GRPC change

### ISSUE THREAD

**Issue by Mr0N** [dotnet/aspnetcore#45563]
I suggest to add a change of environment for grpc services, to set the address of the service, the logic should be done as in ASPNETCORE_URLS, only for GRPC, with setting the protocol.

**Comment by halter73** [comment]
I'm not sure the host or server should have any awareness of gRPC. That seems to high-level. I think it's better to treat gRPC endpoints like any other HTTP/2 endpoint at this layer.

Am I correct that you want the gRPC endpoint to accept HTTP/2 requests only? You can already do this using [Kestrel configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#configureiconfiguration) which can be [read from environment variables](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#non-prefixed-environment-variables) by default, not just appsettings.json.

So you could make Kestrel bind to an HTTP/2-only endpoint for gRPC by setting environment variables like the following before starting your app.

```
export Kestrel__Endpoints__gRPC__Url=https://*:$PORT
export Kestrel__Endpoints__gRPC__Protocols=Http2
```

Kestrel-specific config [overrides "urls"-based configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#kestrel-endpoint-configuration), so if you're using `ASPNETCORE_URLS` for your primary endpoint, you should configure that using `Kestrel__Endpoints__...` as well so it gets merged.

Does this meet your needs?

**Comment by Mr0N** [comment]
> I'm not sure the host or server should have any awareness of gRPC. That seems to high-level. I think it's better to treat gRPC endpoints like any other HTTP/2 endpoint at this layer.
> 
> Am I correct that you want the gRPC endpoint to accept HTTP/2 requests only? You can already do this using [Kestrel configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#configureiconfiguration) which can be [read from environment variables](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#non-prefixed-environment-variables) by default, not just appsettings.json.
> 
> So you could make Kestrel bind to an HTTP/2-only endpoint for gRPC by setting environment variables like the following before starting your app.
> 
> ```
> export Kestrel__Endpoints__gRPC__Url=https://*:$PORT
> export Kestrel__Endpoints__gRPC__Protocols=Http2
> ```
> 
> Kestrel-specific config [overrides "urls"-based configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#kestrel-endpoint-configuration), so if you're using `ASPNETCORE_URLS` for your primary endpoint, you should configure that using `Kestrel__Endpoints__...` as well so it gets merged.
> 
> Does this meet your needs?

it is not particularly clear why you have different behavior of programs on different platforms (Windows, Linux).
