### ISSUE TITLE
Enable ALPN tests/features on MAC

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#45569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

- https://github.com/dotnet/runtime/issues/27727
This feature is now available from the runtime so we should consume it in Kestrel.

### Describe the solution you'd like

Areas of interest:
- Kestrel HTTP/2 tests
- Kestrel Mac specific error messages
- gRPC tests
- gRPC template
- Kestrel docs
- gRPC docs

**Comment by JamesNK** [comment]
> gRPC template?

Yes. There is at least a comment about macOS to remove.

There are also a lot of docs that need to be updated. Let's focus on making sure this technically works first before thinking about them.

**Comment by halter73** [comment]
We probably want to remove this check which preemptively stops you from binding to HTTP/2-only TLS endpoint on macOS at application startup. We already have logic in Kestrel's HttpConnection to fail at connection start if h2 isn't negotiate via ALPN on a HTTP/2-only TLS endpoint.

https://github.com/dotnet/aspnetcore/blob/53124ab8cbf152f59120982f1c74e802e7970845/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L466-L472

@JamesNK suggests it might make sense to ask for something along the lines of a static IsAlpnSupported property on SslStream to support this use case.

**Comment by JamesNK** [comment]
Consider waiting for https://github.com/dotnet/runtime/issues/79687 before looking at this.

**Comment by adityamandaleeka** [comment]
@JamesNK Is this issue at this point just to track using the new proposed runtime API? Should it be remilestoned?

**Comment by JamesNK** [comment]
Updating docs for .NET 8 can happen in preview 1.
