### ISSUE TITLE
Adding Http(Request/Response) extension methods overloads accepting non-generic JsonTypeInfo

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#45568]
## Background and Motivation

STJ introduced new overloads (https://github.com/dotnet/runtime/issues/77051) with untyped `JsonTypeInfo`, however, `HttpResponse` and `HttpRequest` extension methods only support `JsonTypeInfo<T>`.

As part of the work to make ASP.NET Core AOT-friendly, we have a need of those methods available. As an example, RDF needs to write the JSON response based on the runtime type and cannot create a typed `JsonTypeInfo<T>`.

https://github.com/dotnet/aspnetcore/blob/63d2fb07e93007af1f016d447a904ce187256881/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L2261

Same for the `uController` source generator rely on the `HttpResponse` extensions to write a JSON content and might not be able to have a generic `JsonTypeInfo`.

https://github.com/davidfowl/uController/blob/86fe16e634bdc34e641c3d983a3f26bba80ccebe/GeneratedOutput/RouteBuilderExtensions.g.cs#L504

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public static class HttpResponseJsonExtensions
{
+        public static Task WriteAsJsonAsync(
+                          this HttpResponse response, 
+                          object? value, 
+                          JsonTypeInfo jsonTypeInfo, 
+                          string? contentType = default, 
+                          CancellationToken cancellationToken = default);
}
```

```diff
namespace Microsoft.AspNetCore.Http;

public static class HttpRequestJsonExtensions
{
+        public static ValueTask<object?> ReadFromJsonAsync(
+                          this HttpRequest request,
+                          JsonTypeInfo jsonTypeInfo, 
+                          CancellationToken cancellationToken = default);
}
```

## Usage Examples

``` c#

ValueTask<object?>  ReadBody(HttpContext context, Type bodyType,  JsonSerializerOptions  jsonSerializerOptions)
{
     var bodyJsonTypeInfo = jsonSerializerOptions.GetTypeInfo(bodyType);
     return httpContext.Request.ReadFromJsonAsync(bodyJsonTypeInfo);
}

Task WriteResponse(HttpContext context, object? value, JsonSerializerOptions  jsonSerializerOptions)
{
     var runtimeType = value is null ? typeof(object) : value.GetType();
     var runtimeTypeInfo = jsonSerializerOptions.GetTypeInfo(runtimeType);
     return httpContext.Response.WriteAsJsonAsync(value, runtimeTypeInfo );
}
```

## Alternative Designs

No response

## Risks

No response

cc @eiriktsarpalis

**Comment by halter73** [comment]
API Review Notes:

1. This matches the pattern used by JsonSerializer.DeserializeAsync/SerializeAsync
2. We're curious how JsonSerializer handles null, but we figure it just treats the type as `object`.

API Approved as proposed!

**Comment by eiriktsarpalis** [comment]
> We're curious how JsonSerializer handles null, but we figure it just treats the type as object

It throws, which is consistent with the generic overloads and how null arguments are treated in non-nullable parameter types. Generally speaking, a source generated context might not include metadata for `object` serialization.
