### ISSUE TITLE
After upgrade from .NET6 To .NET 7 (AddScoped IHostEnvironmentAuthenticationStateProvider) lifetime loading without ending

### ISSUE THREAD

**Issue by HashemGo** [dotnet/aspnetcore#45583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi 
this code working fine on .NET 6 but after upgrade to .NET 7 The project not working without showing any error just loading without ending time

```
            services.AddScoped<AuthenticationStateProvider, AccessClass>();

            services.AddScoped<IHostEnvironmentAuthenticationStateProvider>(sp =>
            {
                var provider = (ServerAuthenticationStateProvider)sp.GetRequiredService<AuthenticationStateProvider>();
                return provider;
            });
```
4 days to find this code make my project loading lifetime without any alert (make me crazy -_-)

### .NET Version

.NET 7

**Comment by javiercn** [comment]
@HashemGo thanks for contacting us.

Did you get a call stack for where the code is stuck?
