### ISSUE TITLE
Using SignalR in Unity - The method or operation is not implemented

### ISSUE THREAD

**Issue by arsi0001** [dotnet/aspnetcore#45586]
### Describe the bug

I want to use SignalR in a UWP project on HoloLens. Some posts here, have helped me a lot and my application is partially running.

It does not run, when I have HTTPS-Redirection on my main server enabled and try to ignore it via those lines in Unity:
```
...
.WithUrl("http://192.168.178.41:5266/Signaler", (opts) =>
{
    opts.HttpMessageHandlerFactory = (message) =>
    {
        // bypass SSL certificate
        if (message is HttpClientHandler clientHandler)
        {
            clientHandler.ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
        }
        return message;
    };
})
...
```
The error (shorted text) I get:
```
System.NotImplementedException: The method or operation is not implemented.
  at XXXXX.Network.MySignalRClient+<>c.<Start>b__1_1 (System.Net.Http.HttpMessageHandler message) [0x0000a] in D:\Repositories\XXXXX\Unity\XXXXX\Assets\Scripts\NetworkClients\MySignalRClient.cs:31 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.CreateHttpClient () [0x00118] in <d4f814eb48994df3870fe7c8338cc73a>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection..ctor (Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions httpConnectionOptions, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory) [0x0009f] in <d4f814eb48994df3870fe7c8338cc73a>:0 
```

Further explanation:
The mentioned line 31 is the line with the `ServerCertificateCustomValidationCallback`.

**How does the application work?**
If I  disable the HTTPS-Redirection and remove lines with the callback:
```
_hubConnection = new HubConnectionBuilder()
    .WithUrl("http://192.168.178.41:5266/Signaler")
    .WithAutomaticReconnect()
    .Build();
```

### Expected Behavior

HTTPS redirection should not be disabled extra on the server side, but the line with the callback on unity side should be enough.

### Steps To Reproduce

**Setup when the application is not running:**
.Net 6-Project:
- `app.UseHttpsRedirection();` is active

Unity:
```
private void Start()
{
    _hubConnection = new HubConnectionBuilder()
    .WithUrl("http://192.168.178.41:5266/Signaler", (opts) =>
    {
        opts.HttpMessageHandlerFactory = (message) =>
        {
             // bypass SSL certificate
             if (message is HttpClientHandler clientHandler)
             {
                  clientHandler.ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
             }
            return message;
     };})
     .WithAutomaticReconnect()
     .Build();

     Connect();
}

private async Task Connect()
{
    _hubConnection.On<string>("SomeKey", (key) =>
    {
        Debug.Log($"New Key: {key}");
    });

   try
   {
       await _hubConnection.StartAsync(tokenSource.Token);
   }
   catch (Exception ex)
    { ... }
}
```

### SignalR Version

Microsoft.AspNetCore.SignalR.Client.7.0.0 and all needed referenced Libraries for .Net Standard 2.0

### Anything else?

Typical Setup:
![grafik](https://user-images.githubusercontent.com/15002527/207563017-b69b54b1-8124-4882-a8a0-07b94d18a367.png)

--EDIT--
Some DLLs are missing in the screenshot, because they are already included by other plugins that I use in Unity. The following packages are not shown: `System.Buffers, System.Memory, System.Numerics.Vectors, System.Runtime.CompilerServices.Unsafe`

**Comment by BrennanConroy** [comment]
I don't see System.Net.Http in your list of dlls. That's where the method you're missing is defined.

Also, can you try running just:
```csharp
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
var httpClient = new HttpClient(httpMessageHandler);

using (var request = new HttpRequestMessage(HttpMethod.Post, "http://192.168.178.41:5266/Signaler"))
{
    await httpClient.SendAsync(request);
}
```
And see if the issue reproduces.

**Comment by BrennanConroy** [comment]
Oh I misread, this is a `NotImplementedException`. Looks like the environment you're in doesn't support that callback which isn't something we can resolve.

Not sure where the code for this environments implementation of HttpClient lives, but that's where you would ask about this.

**Comment by arsi0001** [comment]
@BrennanConroy 
Thanks for your answers. Maye I will try an older version of this. Otherwise, as you say, I'll have to contact the developers of SystemNetHttp then.

SystemNetHttp is supported out of the box in Unity because of .NET Standard 2.0. I guess I also gonna post this in a unity forum.

Thanks!
