### ISSUE TITLE
"Standalone" Blazor custom elements

### ISSUE THREAD

**Issue by jmezach** [dotnet/aspnetcore#45588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

During yesterdays Blazor community stand-up I asked the question of whether "standalone" custom elements are something that is being considered for .NET 8. From what I understood from @danroth27 that isn't the case, and there wasn't an issue for it either, so I figured I might as well make one.

With "standalone" Blazor custom elements I guess what I really mean is self-contained custom elements. Blazor already has the ability to register components as a custom element, but that requires all of Blazor to be bootstrapped on the page, which typically isn't the case when you have an existing application and you want to add new pieces of functionality to it, but build those in Blazor.

### Describe the solution you'd like

Ideally I would like to be able to essentially bundle one or more Blazor (or I guess Razor) components into a custom element, then point any webpage at that bundle and then being able to use the custom element on the page without any other dependencies.

Obviously that does pose some challenges as well. For example, does every custom element then ship with its own .NET WebAssembly runtime? If yes, then what does that mean for size, download time, etc.? If not, then what happens if two separate custom elements use different versions of .NET? And there are probably other things to consider here that I think are worth discussing.

### Additional context

I got this idea mainly from [this article](https://micro-frontends.org/) which proposes composing an application together through the use of custom elements, where a team can have ownership of one or more of those custom elements. I feel that this can be a really powerful approach to building scalable applications and I would love to see Blazor and .NET in that world.

**Comment by javiercn** [comment]
> Ideally I would like to be able to essentially bundle one or more Blazor (or I guess Razor) components into a custom element, then point any webpage at that bundle and then being able to use the custom element on the page without any other dependencies.
> 
> Obviously that does pose some challenges as well. For example, does every custom element then ship with its own .NET WebAssembly runtime? If yes, then what does that mean for size, download time, etc.? If not, then what happens if two separate custom elements use different versions of .NET? And there are probably other things to consider here that I think are worth discussing.

You should already be able to do this with the custom elements support we offer. Referencing the blazor webassembly script from your index page will bootstrap Blazor and from there on, you can use defined custom elements in your app to render razor components.

**Comment by jmezach** [comment]
@javiercn Hmm, not entirely sure that I follow. From what I've seen so far the Blazor webassembly script is an artifact generated from the build of a Blazor WebAssembly project which is tied to that particular project, so it will not just load Blazor but also bootstrap the application, right?

**Comment by javiercn** [comment]
@jmezach the script will download and start the runtime, however you can use `autostart=false` to avoid the automatic start. You can decide when you want to start the runtime and render elements afterwards, but there is going to be a .NET runtime running at that point. Is that not what you are looking for?

**Comment by jmezach** [comment]
So can I then just load one or more assemblies and have them register custom elements? How do I run those assemblies?

**Comment by javiercn** [comment]
@jmezach you can download and load any assembly you want in Program.cs and once you have loaded the assembly you can do something to register whatever component type you want from that assembly as a custom element. This would likely be very similar to building your own plugin system. An example (on the server) would be for example, ApplicationParts in MVC.

**Comment by jmezach** [comment]
But then I'd still need a "host" application that has the `Program.cs` right? Which then needs to know about all the custom elements that need to be registered. So everytime a team adds a new component I need to update the `Program.cs` and deploy it?

**Comment by javiercn** [comment]
> But then I'd still need a "host" application that has the `Program.cs` right? Which then needs to know about all the custom elements that need to be registered. So everytime a team adds a new component I need to update the `Program.cs` and deploy it?

I am not sure why you need to update Program.cs. Can you not provide the list of assemblies your app needs to load and have some logic in Program.cs to find an interface on those assemblies and call a method to register the custom elements?

**Comment by javiercn** [comment]
@jmezach https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-7.0

Serving the .dll from somewhere in your app, downloading it as a byte array and calling `Assembly.Load` should work. 

An alternative would be to make these assemblies lazy loaded, which has the advantage that the build gets to see the .dlls at link time and can account for that.

With the original approach, you might have issues if you link the app, since it won't have visibility into assemblies you bring on your own.
