### ISSUE TITLE
ResultContext<TOptions>.Result missing nullable annotation

### ISSUE THREAD

**Issue by victor-borges** [dotnet/aspnetcore#45594]
## Background and Motivation

`ResultContext<TOptions>.Result` could be null when instantiating a type derived from `ResultContext<TOptions>`, but the property is declared as non-nullable.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Authentication;

public abstract class ResultContext<TOptions> : BaseContext<TOptions> where TOptions : AuthenticationSchemeOptions
{
-    public AuthenticateResult Result { get; private set; } = default!;
+    public AuthenticateResult? Result { get; private set; }
}
```

## Usage Examples

```csharp
var messageReceivedContext = new MessageReceivedContext(Context, Scheme, Options);

// Expression is always true according to nullable reference types' annotations,
// but in practice it is always false as the Result property is never actually set (at least in the case of MessageReceivedContext)
if (messageReceivedContext.Result != null) 
{
    // Use messageReceivedContext.Result in some way
}
```

## Risks
Might show a NRT warning for consumers expecting it to always be non-null, no breaking change as far as I'm aware (?).

**Comment by mitchdenny** [comment]
A framework dependent application that was not rebuilt after a runtime update would crash in this scenario with a `MethodNotFoundException`.

**Comment by halter73** [comment]
Good suggestion. Thanks!

I think `messageReceivedContext.Result` is normally null in `JwtBearerEvents.OnMessageReceived`. We could consider using `new` to "override" the nullability in just the derived classes that call the protected `ResultContext` ctor, but that wouldn't fix any derived types outside of the framework. I think we should just update it to be nullable.
