### ISSUE TITLE
Case insensitivity in enum route binding

### ISSUE THREAD

**Issue by timgabrhel** [dotnet/aspnetcore#45590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to use enums as a route parameter in my .net 7 minimal api, with the flexibility to have case insensitivity in the parameter binding. I've done this in .NET 6 controller based APIs which worked with identical configuration (seen below), but the behavior doesn't match here. 

I am avoiding trying to write a custom parameter binding as I wish to let Swagger auto-discover the enum parameter and hydrate the enum options properly. This API spec is shared outside of my team and the documentation built in with the enums is incredibly valuable.

### Expected Behavior

`POST /optiona` resolves the endpoint and returns the string `OptionA`

### Steps To Reproduce

`dotnet new webapi -minimal`

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(o =>
{
    o.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    o.SerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    o.SerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");
app.MapGet("/{myenum}", ([FromRoute] MyEnum myenum) =>
{
    return Results.Ok(myenum.ToString());
});

app.Run();

public enum MyEnum
{
    OptionA,
    OptionB
}
```

1. Navigate to `/optiona` and be shown an error 
> BadHttpRequestException: Failed to bind parameter "MyEnum myenum" from "optiona".
2. Navigate to `/OptionA` and see `"OptionA"` in the response body of the browser.

### .NET Version

7.0.100

### Anything else?

VS Code

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by captainsafia** [comment]
Triage: JSON options affect the way the enum is parsed if it is present in a JSON payload to the request. Since your enum is provided as a route parameter, these JSON options won't take affect.

This behavior is dictated by the logic in our parameter binding, which uses the `Enum.TryParse` overload that does not enable case-insensitivity.

You might want to consider implementing your own `TryParse` implementation on a wrapper for your `MyEnum` type that is case-insensitive. See more info at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#tryparse
