### ISSUE TITLE
Blazor doesn't render components inside `template` tags

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#45605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To create a markup template for scripts, we could do this:
````html
<template id="foo">
  <p>Hello</p>
</template>
````

But this isn't rendered properly:
````html
<template id="bar">
  <MyComponent />
</template>
````

That will render an empty template tag.

### Expected Behavior

For the template tag to be rendered properly.

### Steps To Reproduce

As above.

### .NET Version

6

### Anything else?

I have the same problem with this older format:
````html
<script type="text/template" id="foo" suppress-error="BL9992">
  <MyComponent />
</script>
````

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

Templates are an HTML feature, so there is no direct integration with Blazor or any other SPA framework for that matter. If you want to support that type of functionality, we recommend you wrap your component inside a custom element and render that from within your template.

**Comment by javiercn** [comment]
I mean https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements

**Comment by javiercn** [comment]
> Unless I'm mistaken, or misunderstanding you, that is for integrating components of other SPAs. I'm referring to simple templates a blazor component creates for its own javascript.

That's not for integrating with other SPA frameworks. It's for integrating with anything external to Blazor. 

If you instantiate a template using JS there is no way for Blazor to know that you have done that. We would need to have code for monitoring when you instantiate templates and insert them into the DOM. And HTML already has a feature for that which is custom elements. No other SPA framework does this either as far as I know.
