### ISSUE TITLE
Blazor Server - Html Source Blazor Info

### ISSUE THREAD

**Issue by Taiizor** [dotnet/aspnetcore#45607]
I am using Blazor Server. It shows the following information in each html output. Can I turn this display of information on or off?

`<!--Blazor:{"sequence":1,"type":"server","prerenderId":"27a768f8d34b40efaa24370d7e4146ad","descriptor":"CfDJ8A5VzMEeZxVNtV1i8tox076ysU67NXXehnicXlH5TEeVv0iEJP32/AiNvDJqOgroXtAxzk1Rju1ub0J3ovn68kgyB8rxLXQ\u002BO4uOqAcLYKRZGC30V7okM9Ty3FYGIcYsX3gXhCCdzSwd6WA8RO7RN/d4\u002B1rGF9dxJeyLIsn5o8NB46ZXHoD3EQJjUiXW0BdGl9zyTFhqeUaBV12mgOvill72AbP\u002BJBzMy1GlET/bW4qVYDJT3Xobok/gXlgNP3SsKo/MD2YxtArQJx/dQjab8T6FEaw1Ap2sE6nvgk3nQ24bberWWsDXHRmyHNzKtfa2l0YcYUYdoNRdEZACpEOarPgGJC81cdBE3ioENQhddnf\u002BseH4XTAcvrdT58gXgigPCISeB9pKqIMBrYvNyV\u002Bi8qUd82LhhKdjpTyf51fKXAZm"}-->`

**Comment by javiercn** [comment]
@Taiizor thanks for contacting us.

That's the marker we use to identify where we need to render the components within the page, without it, we can't render a Blazor component on to the page.

**Comment by Taiizor** [comment]
> @Taiizor thanks for contacting us.
> 
> That's the marker we use to identify where we need to render the components within the page, without it, we can't render a Blazor component on to the page.

Yes, I know that, but I don't want it to appear only in the source code (html source).

**Comment by javiercn** [comment]
@Taiizor no, it is not possible.

**Comment by Taiizor** [comment]
> @Taiizor no, it is not possible.

Oh, got it. thx for everything..
