### ISSUE TITLE
Blazor wasm debugging SSL problem

### ISSUE THREAD

**Issue by seriouz** [dotnet/aspnetcore#45625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am running a Blazor WASM app as hosted app through a WebApi project.
Everything is smooth but the debugging experience of the Blazor app.

When i am running Chrome with `chrome --remote-debugging-port=9222 --ignore-certificate-errors --ignore-ssl-errors --enable-logging --disable-extensions --user-data-dir="C:\Users\serio\AppData\Local\Temp\blazor-chrome-debug" https://localhost:7081/`

I get this output (the Blazor app runs but no debugging / breakpoint will be hit):
```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/8decada6-eb5e-43fe-ac0f-9552a2f614d3
[22776:10556:1216/151153.567:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[22776:10556:1216/151153.573:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[22776:10556:1216/151203.797:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[22776:10556:1216/151214.159:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -101
[16232:20740:1216/151346.074:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```

I've added the `app.UseWebAssemblyDebugging();` on the WebApi host and added the package `Microsoft.AspNetCore.Components.WebAssembly.DevServer` in both projects.

### .NET Version

7.0.1

**Comment by TanayParikh** [comment]
@thaystg is this a scenario we support?

**Comment by thaystg** [comment]
I think I need more information to understand it.
@seriouz can you provide us a simple project that reproduces this issue?

**Comment by seriouz** [comment]
@thaystg Sure here you go. Run the HostApi project: 
[WebApiHostsBlazorWasm.zip](https://github.com/dotnet/aspnetcore/files/10249991/WebApiHostsBlazorWasm.zip)

**Comment by TanayParikh** [comment]
Just to clarify, we definitely support debugging hosted Blazor WASM apps, however that's usually through VS/VSCode debugging extensions. I wasn't sure if the Chrome CLI command was supported.

More info: https://learn.microsoft.com/aspnet/core/blazor/debug

Also, could you please provide the repro as a publicly hosted github project?

**Comment by seriouz** [comment]
@TanayParikh Sure, i pushed the folder as a repo: https://github.com/seriouz/WebApiHostsBlazorWasm

**Comment by seriouz** [comment]
Note: I tried to set the breakpoints in VS 2022 and in Rider 2022.3 both did not hit nor load the breakpoints.

**Comment by thaystg** [comment]
@seriouz in which source you are trying to add the breakpoint that is not working?

**Comment by seriouz** [comment]
@thaystg This line: https://github.com/seriouz/WebApiHostsBlazorWasm/blob/main/src/DebugTest.BlazorWasm/Pages/Counter.razor#L16

**Comment by thaystg** [comment]
I'm sorry, I think I don't understand, you have two projects, DebugTest.HostApi, this should be the one to be started from VS right?
Then I see this page:
![image](https://user-images.githubusercontent.com/4503299/208431586-35422a4a-226b-41cd-adcd-b89bac7b1145.png)

Where should I click to run the Counter.razor code?

**Comment by thaystg** [comment]
Oh , okay, I can change the URL to go to the blazor app:
![image](https://user-images.githubusercontent.com/4503299/208432579-8cb8335a-2465-4401-b0f6-0d8e15c1d376.png)

Thanks.

**Comment by thaystg** [comment]
![image](https://user-images.githubusercontent.com/4503299/208433345-f4d72c3d-c962-4ade-83b2-f5ccd610cab4.png)

**Comment by seriouz** [comment]
Thanks this works! I don't know in my "not demo project" the `inspectUri` attribute was declared as an error because it was not known. In this demo project it works flawlessly. I think i have to inspect why this prop does not work on my original project.
I'll reopen this issue, when i find a traceable problem.
Thanks!
