### ISSUE TITLE
Using browserlink causes a 500 instead of a 404 response when an exception handling middleware is used

### ISSUE THREAD

**Issue by stambunan** [dotnet/aspnetcore#45622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Browserlink in Visual Studio 2022 will cause any 404s returned by an ExceptionHandler to be a 500 error code, if the request header contains `Accept: text/html`.

This seems to happen because of this line: https://github.com/dotnet/aspnetcore/blob/1eb9766a25b81c9ffedc181aeba884c27335a639/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L160

With browserlink turned off, https://stackoverflow.com/questions/69952420/how-to-disable-browser-link-in-asp-net-core-net-6-vs-2022,  the exception handler will start writing to the stream as soon as possible since an `HttpResponseStream` is used. With browserlink enabled, a `ScriptInjectionFilterStream` is used instead and `context.Response.HasStarted`, will always be false which will lead to the original exception being thrown at https://github.com/dotnet/aspnetcore/blob/1eb9766a25b81c9ffedc181aeba884c27335a639/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L185

Perhaps .NET can start writing to the stream earlier to ensure `context.Response.HasStarted` will be true? 

This will have been introduced by https://github.com/dotnet/aspnetcore/issues/25288 I believe.

### Expected Behavior

I'm expecting a 404 to be returned instead of a 500 error thrown by .NET Core. 

### Steps To Reproduce

To replicate: 
1) set up a custom exception handler, something similar to https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#produce-a-problemdetails-payload-for-exceptions. 
2) Instead of `StatusCodes.Status500InternalServerError`, use a 404 status code
3) Throw an exception on a controller that's uncaught which will force the exception handler to run
4) Use Postman or any tool to do a request with a request header `Accept: text/html`. This will force browserlink to work and use a `ScriptInjectionFilterStream`.
5) An error is now returned instead of the expected 404. 
6) Turn off browserlink completely and a 404 will be returned as expected

### .NET Version

.NET 6 and .NET 7

**Comment by javiercn** [comment]
@stambunan thanks for contacting us.

In order for you to get a faster and better answer, could you please file the issue directly through the [Report a problem with Visual Studio - Visual Studio (Windows) | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)

**Comment by javiercn** [comment]
I have reached out to the appropriate folks to take a look.
