### ISSUE TITLE
Edit Form Loses Focus with authorize view policy

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#45632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Edit-Form-Loses-Focus-with-authorize-vie/10228347)._

---
[severity:It's more difficult to complete my work]
When I run the code below and input any value into the setting text box and then click the value text box it loses focus. If i replace the authorizeview policy with just authorize view it works as expected and the cursor moves to the value text box. However, the authorize view without the policy is undesirable as i want to use the policy to regulate access. 

    
        
            
            
            
            
        
    
    
        <p> Not Authorized </p>
    

@code {
    private displayAppSettings _displayAppSettings = new();

    private async void CreateUpdateRec()
    {
    }
}

---
#### Feedback Bot on 12/12/2022, 07:25 PM: 

(private comment, text removed)
#### Philip Wang [MSFT] on 12/12/2022, 10:02 PM: 

(private comment, text removed)
#### Billy Grage on 12/13/2022, 09:43 AM: 

(private comment, text removed)
#### Billy Grage on 12/13/2022, 02:11 PM: 

(private comment, text removed)
#### Feedback Bot on 12/13/2022, 05:34 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

Could you please provide us with a minimal repro project hosted as a public GitHub repository? This will allow us to investigate the issue further. Thanks!
