### ISSUE TITLE
Please reopen https://github.com/dotnet/aspnetcore/issues/45182#issue-1456298401

### ISSUE THREAD

**Issue by wolfgangschneider** [dotnet/aspnetcore#45643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I add requested feedback. maybe in a wrong way and to late. But I don’t know how to reopen it.

please reopen  https://github.com/dotnet/aspnetcore/issues/45182#issue-1456298401 . Or give advice how to do it.

tanks wolfgang

### Describe the solution you'd like

See original issue

**Comment by javiercn** [comment]
I've reopened the original issue.
