### ISSUE TITLE
Documentation comments Typo in Twitter Authentication Extensions file

### ISSUE THREAD

**Issue by AhmedZAE** [dotnet/aspnetcore#45640]
Facebook is mentioned instead of Twitter in the documentation comments for Twitter Authentication, in [TwitterExtensions.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Twitter/src/TwitterExtensions.cs) file.

Typos are located at:
[Line#20](https://github.com/dotnet/aspnetcore/blob/8f995a0b4eb13f435181ea29b27322ec848a6337/src/Security/Authentication/Twitter/src/TwitterExtensions.cs#L20)
[Line#32](https://github.com/dotnet/aspnetcore/blob/8f995a0b4eb13f435181ea29b27322ec848a6337/src/Security/Authentication/Twitter/src/TwitterExtensions.cs#L32)
[Line#45](https://github.com/dotnet/aspnetcore/blob/8f995a0b4eb13f435181ea29b27322ec848a6337/src/Security/Authentication/Twitter/src/TwitterExtensions.cs#L45)
[Line#59](https://github.com/dotnet/aspnetcore/blob/8f995a0b4eb13f435181ea29b27322ec848a6337/src/Security/Authentication/Twitter/src/TwitterExtensions.cs#L59)

Example:
```
/// <para>
/// Facebook authentication allows application users to sign in with their Facebook account.
/// </para>
```
Should be:
```
/// <para>
/// Twitter authentication allows application users to sign in with their Twitter account.
/// </para>
```

**Comment by danmoseley** [comment]
I think you're right. Do you want to offer a PR?

**Comment by AhmedZAE** [comment]
Yeah sure
