### ISSUE TITLE
Linux: RBAC claims resolution fails if user has group with comma in name

### ISSUE THREAD

**Issue by teh13th** [dotnet/aspnetcore#45648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Real-world AD deployments can have groups with comma in name (example: `Testing group, City`). In this case, when nested claims resolution is enabled, Linux clients will get exception on resolving this kind of group, because group Common Name parsed from Distinguished Name (`CN=Testing group\,City,OU=Department,DC=contoso,DC=com`) incorrectly (`Testing group,`).

### Expected Behavior

In case, when nested claims resolution is enabled, expected that Common Name of each user's group will parse correctly, even if it contains comma.

### Steps To Reproduce

1. Set up any AD server (contoso.com in the example).
2. Add AD group with comma in name (`Testing group, City`).
3. Add user to that group.
4. Create a simple API project, set up RBAC claims resolution:

```
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate(options =>
{
    if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        return;
    }
    
    options.EnableLdap(settings =>
    {
        settings.Domain = "contoso.com";
        settings.MachineAccountName = "someuser";
        settings.MachineAccountPassword = "somepassword";
    });
});

services.AddAuthorization();
```

```
[ApiController]
[Route("api/[controller]")]
[Authorize(Roles = "GroupA")]
public class SomeController : Controller
{
    [HttpGet]
    [Route("someMethod")]
    public async Task<ActionResult<int>> SomeMethod()
    {
        return 1;
    }
 }
```

### Exceptions (if any)

System.DirectoryServices.Protocols.LdapException: The search filter is invalid.

### .NET Version

6.0.11

### Anything else?

- ASP.NET Core 6.0, via docker dotnet/aspnet:6.0
- Visual Studio 2022

**Comment by captainsafia** [comment]
Triage: Sticking this into .NET 8 since there is a PR out. We may want to backport this to .NET 6 and 7 as well.
