### ISSUE TITLE
Allow middleware routing manipulation in blazor

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#45653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wrote a routing middleware for a culture.
```cs
        app.Use(async (context, next) => {

            /*
             * If routing does not exist
             */
            if (context.Request.Path.Value is null)
            {
                await next();
                return;
            }

            var regex = new Regex(@"^/(?<culture>[a-z]{2}(-[a-z]{2})?)/(?<url>.+)", RegexOptions.Compiled | RegexOptions.IgnoreCase, TimeSpan.FromSeconds(1));
            var match = regex.Match(context.Request.Path.Value);

            /*
             * If path resembles a culture structure
             */
            if (match.Success is true)
            {
                var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
                var culture = match.Groups["culture"].Value.ToLower(); //?? "pl-pl"

                /*
                 * If the culture is correct, protection against malicious attack.
                 */
                if (cultures.Any(x => x.Name.ToLower() == culture) is true)
                {
                    /*
                     * If you are currently using a different culture than the url enforces
                     */
                    if (CultureInfo.CurrentCulture.Name != culture)
                    {
                        context.Response.Cookies.Append("Culture", culture, new CookieOptions { Expires = DateTime.UtcNow.AddYears(1) });
                        //context.Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture, culture)));

                        CultureInfo.CurrentCulture = new CultureInfo(culture);
                        CultureInfo.CurrentUICulture = new CultureInfo(culture);
                    }
                    
                    /*
                     * Continues to routing
                     */
                    context.Request.Path = $"/{match.Groups["url"].Value}";
                }
            }
            
            await next();
        });
```

Everything works fine, the server side renders the page correctly, unfortunately, after entering via the link, blazor immediately calls ``<Route><NotFound>``

The only solution is to add another @page in the subpage:
```razor
@page "/HelloWorld"
@page "/{culture}/HelloWorld"
```

Unfortunately, it is cumbersome, you have to handle regex separately on each subpage and remember about double routing.

Such a function is in MVC and razor. I think this is a big overdue, many people have also posted here and asked to add culture support in the URL and prefix/custom links.

### Expected Behavior

 Let me know what you think about it.

### .NET Version

.net 7

**Comment by Alerinos** [comment]
I looked a bit in the code, the only way to achieve a change of route is to rewrite the entire router.

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/Components/src/IComponent.cs#L1-L28

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/Components/src/IHandleAfterRender.cs#L1-L16

The problem is that if we want to have an advanced router as it is now, assembly, handling of page attributes and other things, we really have to write everything ourselves.
You need the ability to extend your current router and the ability to create your own routes and their providers.

**Comment by Alerinos** [comment]
@danroth27 I saw that you introduced changes to routing in RC1. It's worth taking a look at it, I think the community is really looking forward to this feature and culture routing in the URL.

**Comment by mkArtakMSFT** [comment]
We think this is addressed in .NET 8. Closing it for now.
