### ISSUE TITLE
SignalR with MessagePack: different MessagePackSerializerOptions per hub

### ISSUE THREAD

**Issue by jozseffa** [dotnet/aspnetcore#45660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to use different MessagePackSerializerOptions for each hub type.
For example, Hub1 should use NativeDateTimeFormatter (preseving DateTimeKind) and Hub2 should use DateTimeFormatter.

It is impossible to inject different IFormatterResolver or IMessagePackFormatter sets per hub type.
Each hub share the MessagePackHubProtocolOptions.SerializerOptions, so we need to collect all IMessagePackFormatter used by all hubs.

### Expected Behavior

e.g. Hub1 should use NativeDateTimeFormatter (serialized as Int64, preseving DateTimeKind)
e.g. Hub2 should use DateTimeFormatter (serialized as MessagePackExtension)

If Hub1 API use Message1 class, and has a IMessagePackFormatter&lt;Message1&gt;, then Hub2 should not be able to use that formatter.

Expected extension methods like this:
```
services.AddSignalR()
.AddMessagePackSerializerOptions<Hub1>(options => ...)
.AddMessagePackSerializerOptions<Hub2>(options => ...)
```

### .NET Version

Microsoft.NETCore.App 6.0.12

**Comment by davidfowl** [comment]
Why is this a hub option and not configured per type?

**Comment by jozseffa** [comment]
updated to clarify

**Comment by davidfowl** [comment]
The IHubProtocol is decoupled from the hub and can be different per client (the client indicates what protocol they want to use on the server). This isn't something we can easily support given the current architecture, so looking for a workaround for your scenario would be ideal.
