### ISSUE TITLE
ErrorBoundary is not catching exceptions raised in async methods returning a Task

### ISSUE THREAD

**Issue by velmohan** [dotnet/aspnetcore#45676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I understand Blazor does not track void returning async methods. But I am noticing exceptions raised in methods returning Task are not caught by `ErrorBoundary`. 

In `MainLayout` I have added `ErrorBoundary` for the entire `@Body`. Now, in the VS project template, I am changing `Counter.razor`  to the following.

```
private void IncrementCount()
    {
        currentCount += IncrementAmount;

        ThrowException();
    }

    public async Task ThrowException()
    {
        await Task.Delay(100);
        throw new InvalidOperationException("Testing..");
    }

```

The above exception is not shown by `ErrorBoundary` or even in the browser yellow bar.

Making the following change makes the browser's light yellow bar to appear.

```
private async void IncrementCount()
    {
        currentCount += IncrementAmount;

        await ThrowException();
    }

```

Finally only the following makes the `ErrorBoundary` to work.

```
private async Task IncrementCount()
    {
        currentCount += IncrementAmount;

        await ThrowException();
    }

```

Does this mean the method at the bottom of stack has to be an `async` method returing a `Task` to be able to use `ErrorBoundary`? In my case I need to call an `async` method from a `NavigationManager.LocationChanged` handler which is a non-`async` method returning `void`.

I have tried the following in the handler. That does not work. 

```
private void HandleLocationChanted(object? sender, LocationChantgedEventArgs eventArgs)
{
              base.InvokeAsync(async() => await MyAsyncTaskMethod()
}

```

### Expected Behavior

Exceptions raised by  the following method should be caught by `ErrorBoundary`.

`base.InvokeAsync(async() => await MyAsyncTaskMethod()`

### Steps To Reproduce

Try adding the following in the counter page:

```
private void IncrementCount()
    {
        currentCount += IncrementAmount;

        base.InokeAsync(async() => await ThrowException());
    }

    public async Task ThrowException()
    {
        await Task.Delay(100);
        throw new InvalidOperationException("Testing..");
    }

```

### .NET Version

.NET6

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @velmohan.

The code that throws the exception is not being awaited, so it is not observed. You should change your first code snippet to the following:

```csharp
private async Task IncrementCount()
{
    currentCount += IncrementAmount;

    await ThrowException(); // Note the 'await'
}

public async Task ThrowException()
{
    await Task.Delay(100);
    throw new InvalidOperationException("Testing..");
}
```

**Comment by velmohan** [comment]
Thank you @MackinnonBuck. As I mentioned that did work for me but thanks for confirming this is expected.

In fact, my original problem is that I need to call an `async` method in the handler of the event: `NavigationManager.LocationChanged`. The exceptions thrown in that methods are not caught. 
I have tried the following but it did not work. Is there any workaround for this? 

```
NavManager.LocationChanted += HandleLocationChanted;

private async void HandleLocationChanted(object? sender, LocationChantgedEventArgs eventArgs)
{
              await MyAsyncTaskMethodWhichThrowsException();
}

```

**Comment by MackinnonBuck** [comment]
@velmohan If upgrading to .NET 7 is an option for you, I would recommend using the new feature enabling asynchronous handling of location changes. See https://learn.microsoft.com/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#handleprevent-location-changes.

Otherwise, you will have to wrap your asynchronous code in a `try`/`catch` and handle the error case manually. Something like this:

```csharp
protected override void OnInitialized()
{
    NavigationManager.LocationChanged += OnLocationChanged;
}

private void OnLocationChanged(object? sender, LocationChangedEventArgs args)
{
    _ = HandleLocationChangedAsync(args);
}

private async Task HandleLocationChangedAsync(LocationChangedEventArgs args)
{
    try
    {
        await MyAsyncTaskMethodWhichThrowsException();
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine(ex);
    }
}
```

**Comment by velmohan** [comment]
Thank you @MackinnonBuck. We are planning to upgrade to .NET 7 and see.

**Comment by velmohan** [comment]
@MackinnonBuck  I am experimenting with .NET 7 to see if I can get my code working. Did you mean `NavigationManager.RegisterLocationChangingHandler'? This does not seem to work for me as this method expects methods to return `ValueTask`. I notice that method returning `ValueTask` are not observed and caught in `ErrorBoundary`? For example, in the following, the third button does not show any error in ErrorBoundary. Is this expected or am I missing something here?

```CSharp

<b>
 <button @onclick="@(() => ThrowException())"> Sync Exception (Caught by ErrorBoundary) </button>
 <button @onclick="@(() => ThrowExceptionAsyncTask())"> Async Exception with Task  (Caught by ErrorBoundary)</button>
 <button @onclick="@(() => ThrowExceptionAsyncValueTask())"> Async Exception with ValueTask  (Not caught by ErrorBoundary)</button>
</b>

@code{
private void ThrowException()
{
         throw new ApplicationException("Test1");
}
private async Task ThrowExceptionAsyncTask()
{
        await Task.Delay(100);
         throw new ApplicationException("Test2");
}

private async Task ThrowExceptionAsyncValueTask()
{
        await Task.Delay(100);
         throw new ApplicationException("Test3");
}
}
```
