### ISSUE TITLE
Azure ASP.NET Core Logging Integration Site Extension 7.0.1 Causes 500.30 ANCM Startup Crash

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/aspnetcore#45673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
An AspNetCoreModule 500.30 error is thrown on startup when the logging site extension is installed in Azure.

This is a project using TargetFramework netcoreapp6.0 and the site in Azure is set to .Net 6

### Expected Behavior

The site extension should work without crashing.

The site does load fine if I remove the site extension in Azure.

### Steps To Reproduce

This isn't about a project, it's about an Azure site extension.

Azure says the extension was updated today so it seems like that's the issue - this did work previously.

### Exceptions (if any)

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=6.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.AzureAppServices, Version=6.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Hosting.AppServicesWebHostBuilderExtensions.<>c.<UseAzureAppServices>b__0_0(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
```

### .NET Version

6

**Comment by Tratcher** [comment]
Hmm, the contents of the site extension package look correct. We'll have to investigate.

https://www.nuget.org/packages/Microsoft.AspNetCore.AzureAppServices.SiteExtension/7.0.1 (updated 6 days ago)

**Comment by DanielStout5** [comment]
Another site also is also using ASP.NET Core Logging Integration 7.0.1 and that site is working, but isn't actually sending logs to Azure Blob Storage anymore.

**Comment by Tratcher** [comment]
@DanielStout5 is that site also targeting .NET 6?

**Comment by DanielStout5** [comment]
Yes.

I found what seems to have been making it crash that first site - it had the library included as a dependency:

`<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="6.0.8" />`

Removing that dll from the server fixed the startup crash, but now this site is also not sending logs to Azure Storage.

**Comment by BrennanConroy** [comment]
> but now this site is also not sending logs to Azure Storage.

Have you enabled log storage for your app?
I just tried it with a net6.0 app and it's working.

![image](https://user-images.githubusercontent.com/7574801/212212688-9e7b4f39-b6a9-47c8-8e97-bd23d302d317.png)

**Comment by BrennanConroy** [comment]
Since we can't repro "this site is also not sending logs to Azure Storage", given the above screenshot settings, but you can, we'll have to redirect you to Azure support since they'll be able to help you with your specific setup.
http://support.microsoft.com/supportforbusiness/productselection?sapId=ef53b119-5f8c-7343-2a0f-f5008a1399b9
