### ISSUE TITLE
Swagger syntax too verbose in MinAPI

### ISSUE THREAD

**Issue by jxwaters** [dotnet/aspnetcore#45683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

To get the schema information for my minAPI method I have to write this boilerplate style Produces code:

```
        group.MapGet("/{id:int}", async (int id, IMediator mediatR) =>
                (await mediatR.Send(new GetByIdQuery<ApplicationUser, UserDTO>(id))).ToIResult())
            .Produces<UserDTO>()
            .WithName("Fetch one user");
```

In contrast, using ApiController, I get this for free 

    public override async Task<ActionResult<UserDTO>> GetById(int id)
        => await base.GetById(id);

### Describe the solution you'd like

I would really MinAPI to be more compact, less code, mode.. minimal! Compared to ApiControllers!
The compiler knows the return type of my method.

**Comment by davidfowl** [comment]
You can do this in .NET 7 with [TypedResults](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0#describe-response-types).

E.g.

```C#
group.MapGet("/{id:int}", async Task<Ok<UserDTO>> (int id, IMediator mediatR) =>
                (await mediatR.Send(new GetByIdQuery<ApplicationUser, UserDTO>(id))).ToIResult())
            .WithName("Fetch one user");
```

Your ToIResult metho would return `Ok<T>` instead of IResult.

**Comment by jxwaters** [comment]
@davidfowl I ran into one issue trying to convert my codebase over to use Result... I want to return a 403 Forbid error code using the new Result class - but Forbid doesn't let me return a string. How do I accomplish that?
