### ISSUE TITLE
Allow modifying certain files post-build without forcing `BlazorCacheBootResources=false`

### ISSUE THREAD

**Issue by igotinfected** [dotnet/aspnetcore#45687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi! I've been following [this issue](https://github.com/dotnet/runtime/issues/53239) to allow us to easily use the `lb_LU` date format, month/day names and so on. Given that the language isn't used very much, it does not seem like it'll be included by default anytime soon, so [the proposed solution](https://github.com/dotnet/runtime/issues/53239#issuecomment-1358010791) for my case was to use our custom `icudt.dat` file that does include the complete `lb_LU` locale.

After messing around a little I found that I could replace the icu files with the following afterbuild target:

```csharp
<Target Name="CopyLocalizationFiles" AfterTargets="AfterBuild">
    <Message Text="Copying localization files to output folder..." Importance="High" />

    <Copy SourceFiles="Localization\icudt.dat" DestinationFolder="$(OutputPath)" ContinueOnError="false" />
    <Copy SourceFiles="Localization\icudt.dat" DestinationFolder="$(OutputPath)\wwwroot\_framework" ContinueOnError="false" />
    <Copy SourceFiles="Localization\icudt.dat.gz" DestinationFolder="$(OutputPath)\wwwroot\_framework" ContinueOnError="false" />

    <Message Text="Localization files copied!" Importance="High" />
</Target>
  ```
  
  This seems like it works post-**publish**, as I assume the integrity hash is recalculated with the new icu files somewhere along the `Publish` flow? But this doesn't work if I run the project locally, the usual integrity-check failure occurs on the `icudt.dat` file.

### Describe the solution you'd like

An ideal solution would be something that doesn't require me to lose the benefits of `BlazorCacheBootResource` and no need for custom `icudt.dat` versions & copy targets. Maybe a way to exclude files from integrity checks? I don't know enough about the Build/Publish + integrity hash generation process to propose something more in-depth.

### Additional context

I'd like to be able to fully use the `lb_LU` locale with Blazor as I have the requirement to support 4 languages (English, French, German, and Luxembourgish). Currently if I use the `lb_LU` locale it defaults to `en_US` values (I suppose, it's the US date format e.g.).

**Comment by ilonatommy** [comment]
Can be reproduced using manual compression in a Blazor template. Error screenshot:
![image](https://user-images.githubusercontent.com/32700855/208638859-6fdc1e53-9162-439e-8a37-faf3c810a098.png)

**Comment by ilonatommy** [comment]
@TanayParikh, could you help here?

**Comment by javiercn** [comment]
@igotinfected thanks for contacting us.

The right way to approach this is to integrate the custom `icudt` file in the build pipeline. It likely involves replacing the file on the `ReferenceCopyLocalPaths` or `WasmNativeAsset` itemgroup after the target where they are defined (which I do not know exactly which is).

You can figure out the target to attach to, by capturing a binary log and using msbuild structured log viewer. You also likely have to intercept the publish process and do something similar to replace the file inside `ResolvedFileToPublish`

**Comment by igotinfected** [comment]
Makes sense to me! Thanks for the swift response 😊 I'll try getting this to work tonight and update in the previously mentioned issue for future generations.
