### ISSUE TITLE
Blazor Wasm] not updating after new deploy linux

### ISSUE THREAD

**Issue by mdfathi99** [dotnet/aspnetcore#45689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have hosted a Blazor APP in Ubuntu 20.4 with Dot net and Nginx. Recently I has new changes in the APP, I have tested it in locally and it's working.  I replaced the published folder in my ubuntu server then I have restarted the `.service` file and nginx. 

`sudo systemctl restart blazor.service`
&
`sudo systemctl restart nginx` 

It should change the app. But it's not changing. The old version is still visible. 
I have changed the PWD and the root directory also stopped the service and start it again. Even cleared cache in Cloudflare and it's not updating.  How can I fix it? For other dot net application it was changing to new version after replacing the publish files and the service. 
Here is my nginx config

```
server {
        listen 443 ssl;
        ssl_certificate /home/ubuntu/ssl/example.com.pem;
        ssl_certificate_key /home/ubuntu/ssl/example.com.key;

	  root /var/www/html/example/wwwroot;
        server_name example.com;

        #add_header X-Frame-Options DENY;
        #add_header X-Content-Type-Options nosniff;

 location / {
        #try_files $uri $uri/ =404;
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
	  #proxy_set_header Connection $http_connection;
 }
location ~ ^/(css/|lib/|js/|favicon.ico){
	root /var/www/html/example/wwwroot;
	access_log off;
	expires max;
}
}
    server {

        if ($host = example.com) {
            return 301 https://$host$request_uri;
        } 


            listen 80;
            listen [::]:80;

            server_name example.com;
        return 404; 
    }
```

### .NET Version

6.0.404

**Comment by javiercn** [comment]
@mdfathi99 thanks for contacting us.

This is likely an issue in your deployment. There are a few things to try for validation:
* Is the app updated when you navigate to it in incognito mode?
* Are you using a service worker?
* Have you ensured the dlls contain your changes? (For example, opening them with ILSpy).

It is very likely a caching issue at some point in your deployment, a hard refresh should get the bits updated (ctrl+shift+F5) on the browser, and similarly, incognito mode should bypass any caching on the browser.

**Comment by mdfathi99** [comment]
@javiercn Thanks for the reply. 
1. No the app is not updating in incognito mode. Even doesn't change after a hard refresh. 
2. Yes I am using a service worker. 
3. I compared the previous .dll and the new .dll and both are the same. 

Here is the DLL file

```
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(/*Could not decode attribute arguments.*/)]
[assembly: TargetFramework(".NETCoreApp,Version=v6.0", FrameworkDisplayName = ".NET 6.0")]
[assembly: AssemblyCompany("ePaperAdminProject")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("ePaperAdminProject")]
[assembly: AssemblyTitle("ePaperAdminProject")]
[assembly: ProvideApplicationPartFactory("Microsoft.AspNetCore.Mvc.ApplicationParts.ConsolidatedAssemblyApplicationPartFactory, Microsoft.AspNetCore.Mvc.Razor")]
[assembly: RazorCompiledItem(typeof(Pages_Error), "mvc.1.0.razor-page", "/Pages/Error.cshtml")]
[assembly: RazorCompiledItem(typeof(Pages__Host), "mvc.1.0.razor-page", "/Pages/_Host.cshtml")]
[assembly: RazorCompiledItem(typeof(Pages__Layout), "mvc.1.0.view", "/Pages/_Layout.cshtml")]
[assembly: AssemblyVersion("1.0.0.0")]

```

*But in windows when I am seeing it in localhost using the `.exe` it shows the new one.

**Comment by mdfathi99** [comment]
After checking, I realized that I had an issue with root folder permission. Thanks.
