### ISSUE TITLE
who know to get abpuser list?

### ISSUE THREAD

**Issue by xiaoyuer1015** [dotnet/aspnetcore#45693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

who know to get abpuser list?

**Comment by davidfowl** [comment]
Maybe a question for https://github.com/abpframework/abp?

**Comment by javiercn** [comment]
@xiaoyuer1015 thanks for contacting us.

As @davidfowl suggested, could you please at that question in the abp repo? They'll be able to give you a better and faster answer.

**Comment by xiaoyuer1015** [comment]
> Maybe a question for https://github.com/abpframework/abp?

Thanks

**Comment by xiaoyuer1015** [comment]
> @xiaoyuer1015 thanks for contacting us.
> 
> As @davidfowl suggested, could you please at that question in the abp repo? They'll be able to give you a better and faster answer.

Thanks！
