### ISSUE TITLE
[Blazor] Blazor Custom Elements tags evidently require a '-' 

### ISSUE THREAD

**Issue by Olivercomputing** [dotnet/aspnetcore#45701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I found that a hyphen ('-') must evidently be included in a Blazor Custom Element to work. I haven't found anything in the documentation that states this as a requirement, nor does it seem to be a reasonable one. I did notice that existing code samples did use tags with hyphens. Internet searches return ambiguous answers to the question of the *requirement* of a hyphen in custom tags - some say yes, others no. If it is required, then at least this should be openly documented. If it is not required, then a hyphenless custom tag should work.

### Expected Behavior

That a custom tag without a hyphen works properly.

### Steps To Reproduce

Simply use a custom tag without a hyphen in an appropriate code sample using Blazor Custom Elements.

### .NET Version

7

**Comment by campersau** [comment]
The HTML spec requires a `-` for custom element names, this is not blazor specific.

> They contain a hyphen, used for namespacing and to ensure forward compatibility (since no elements will be added to HTML, SVG, or MathML with hyphen-containing local names in the future).

https://html.spec.whatwg.org/#valid-custom-element-name
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by javiercn** [comment]
@Olivercomputing thanks for contacting us.

What @campersau mentions is correct. This is mandated by the spec.

@guardrex can you make a reference on the docs to the `-` requirement?
