### ISSUE TITLE
publish folder recursively

### ISSUE THREAD

**Issue by ganiyevtemur1** [dotnet/aspnetcore#45708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i publish asp.net core mvc 6.0 app in Ubuntu 21.04 like this
dotnet publish -c Relese -o ./Publish 
and every publish recursivly folders creted
for exmple ./Publish/Publish/Publish/....

**Comment by javiercn** [comment]
@ganiyevtemur1 thanks for contacting us.

If you publish you use `dotnet publish -c Relese -o ./Publish` the content is placed in a Publish folder inside the application folder. The next time you call Publish that folder and its contents will be part of the build input, hence why you get the "recursive publish".

If you want to publish outside of the bin folder you need to modify your project to ignore any content from your desired publish folder. `<Content Remove="Publish/**" /> and `<None Remove="Publish/**" />` will likely do the trick, but I would suggest avoiding that by not publishing inside the project structure.
