### ISSUE TITLE
Blazor Server App integrated with Azure AD: Public/Anonymous pages not working

### ISSUE THREAD

**Issue by blk99cobra18103** [dotnet/aspnetcore#45711]
I have a blazor app integrated with azure ad/sso.  When the app was registered in azure, the whole site at the root was to be protected.  So when setting up the app in azure I set the end point to be https://localhost or https://mysite.com.  There was a requirement for me to have a publicly available page or an anonymous page.  I setup a 'public' folder in my solution and made the necessary changes related to the new public area.  I created a _PublicHost.cshtml (under Pages directory), _PublicLayout.cshtml (under Pages directory), PublicLayout.razor (under Shared directory), _imports.razor (under Public directory) and a PublicApp.razor.  All these files I have the [AllowAnonymous] attribute at the top.

![image](https://user-images.githubusercontent.com/52298993/208908673-53197d69-94cc-4a74-bf88-6eb495d4d3e8.png)

Here is my application structure.

![image](https://user-images.githubusercontent.com/52298993/208909216-32f14c68-197b-4553-b9ce-a8487ed88fc0.png)

My Program.cs file looks like this.

![image](https://user-images.githubusercontent.com/52298993/208909579-7e93d660-f98a-4260-9e61-a909458c0924.png)

When I run the solution, I get prompted to login using microsoft's typical login window.  If I navigate to my public page, the page displays but any type of button or clickable element on the page doesn't work because in developer tools there are a bunch of errors related to the microsoft login stuff.

![publicerror](https://user-images.githubusercontent.com/52298993/208914341-1ec3c811-8b0b-4309-a9d8-bae4d756097c.jpg)

If I remove the azure ad sso info from my program.cs file the page works as it should.  Any idea how to get a public page or public area of blazor site working if the root of the site was to be protected when setting up the azure app?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
