### ISSUE TITLE
WebApplicationFactory CreateClient throws DirectoryNotFound if solution and project in same directory

### ISSUE THREAD

**Issue by kfollstad** [dotnet/aspnetcore#45717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you create a project using the wizard and check the box "Place project and solution in same directory," calling CreateClient on factory produced from a new WebApplicationFactory<Program> will throw a DirectoryNotFound exception.

### Expected Behavior

What happens if you don't check the project/solution checkbox (it works fine then!); it should not throw an exception.

### Steps To Reproduce

Create a new project. Check the box in the wizard to place the project and solution in same folder. Then write and run a test similar to:

<! -- Test.cs -->
```
using NUnit.Framework;
using Microsoft.AspNetCore.Mvc.Testing;

namespace MinimalTests
{
    [TestFixture]
    public class WebApplicationFactoryTests
    {
        [Test]
        public async Task TestWebApplicationFactoryWillThrowException()
        {
            var factory = new WebApplicationFactory<Program>();
            using (var client = factory.CreateClient())
            {
                var response = await client.GetAsync("");
            }
        }
    }
}
```

### Exceptions (if any)

```
  Message: 
System.IO.DirectoryNotFoundException : C:\Users\Kevin.Follstad\Documents\Software\C#\ElectricalTester\ElectricalTester\
```
**Note that it is looking for the nested directory structure which does not exist if you check the box on the project wizard to "Place solution and project in the same directory."**

 ```
 Stack Trace: 
PhysicalFileProvider.ctor(String root, ExclusionFilters filters)
PhysicalFileProvider.ctor(String root)
BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
WebApplicationBuilder.ctor(WebApplicationOptions options, Action`1 configureDefaults)
WebApplication.CreateBuilder(String[] args)
Program.<Main>$(String[] args) line 1
--- End of stack trace from previous location ---
HostingListener.CreateHost()
<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
DeferredHostBuilder.Build()
<4 more frames...>
WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
WebApplicationFactory`1.CreateClient()
HTTPFactoryTests.TestHTTPGetStatusOK() line 73
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

### .NET Version

7.0.100

### Anything else?

Microsoft.AspNetCore.Mvc.Testing 6.0.12

**Comment by davidfowl** [comment]
Yea the exception message here is terrible

**Comment by halter73** [comment]
@kfollstad I have a repository where I unsuccessfully tried to repro this at https://github.com/halter73/SlnAndProjectSameDir. Can you please indicate what needs to change to reproduce this issue? Was the test project inside the web project directory or something like that? If you could submit a PR to my repo that makes the test fail, that would be great. Thanks!
