### ISSUE TITLE
.NET 7 ErrorBoundary is not catching exceptions raised in async methods returning a ValueTask

### ISSUE THREAD

**Issue by velmohan** [dotnet/aspnetcore#45724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a follow up from the issue discussed in https://github.com/dotnet/aspnetcore/issues/45676.

I have an async method that needs to be called from LocationChanged event handlers. I tried using the new .NET 7 `NavigationManager.RegisterLocationChangingHandler`.  The exception raised in async handlers are not caught. 

### Expected Behavior

I would have thought the exceptions raised in async handlers are observed and handled by ErrorBoundary. I see the error in browser's devtools console but web UI does not show anything.

### Steps To Reproduce

Define an `ErrorBoundary` in your layout like

```CSharp

<main>
    <article class="content px-4">
        <ErrorBoundary>
            @Body
        </ErrorBoundary>
    </article>
</main>
```

Now, add another page with these  buttons. Clicking on 3rd button does not show the error raised (in the default `ErrorContent` in `ErrorBoundary`) whereas clicking on the other 2 buttons show these errors.

```CSharp

<b>
 <button @onclick="@(() => ThrowException())"> Sync Exception (Caught by ErrorBoundary) </button>
 <button @onclick="@(() => ThrowExceptionAsyncTask())"> Async Exception with Task  (Caught by ErrorBoundary)</button>
 <button @onclick="@(() => ThrowExceptionAsyncValueTask())"> Async Exception with ValueTask  (Not caught by ErrorBoundary)</button>
</b>

@code{
private void ThrowException()
{
         throw new ApplicationException("Test1");
}
private async Task ThrowExceptionAsyncTask()
{
        await Task.Delay(100);
         throw new ApplicationException("Test2");
}

private async ValueTask ThrowExceptionAsyncValueTask()
{
        await Task.Delay(100);
         throw new ApplicationException("Test3");
}
}
```

### .NET Version

7.0.101

### Anything else?

ASP.NET Core Version: 7.0.1

IDE: VS 2022

**Comment by javiercn** [comment]
@velmohan thanks for contacting us.

I believe `ValueTask` is not supported for `EventCallback` so `private async ValueTask ThrowExceptionAsyncValueTask()` is being mapped to an `Action` delegate and the result is being ignored.

If you check with a regular handler, you'll see that it only gets rendered once.

In general, you need to use Task when dealing with Blazor as we need to be able to potentially check and await the result multiple times, which is not supported by ValueTask.

**Comment by velmohan** [comment]
Thanks @javiercn. Is there any way to register async handlers returning Task? I only found `NavigationManager.RegisterLocationChangingHandler` which expects `ValueTask`?

**Comment by javiercn** [comment]
@velmohan the comment I made applies only to event handlers associated with components.

`NavigationManager.RegisterLocationChangingHandler` does support ValueTask

**Comment by velmohan** [comment]
@javiercn  the exception raised by the handlers registered in `NavigationManager.RegisterLocationChangingHandler` are not caught by `ErrorBoundary`. Is this expected? Is there any way I can register an async handler and exceptions thrown from this handler needs to be handled by `ErrorBoundary`?

**Comment by javiercn** [comment]
@velmohan thanks for the additional details.

I will defer to @MackinnonBuck on it, but if I remember correctly, they do not get currently caught because we do not want to wait until all of them finish, I can't remember the details, but there was a concrete trade-off we made about it.

I would suggest that you wrap your handlers inside a `try..,catch` and decide whether to cancel or let the navigation continue in case of an exception.
