### ISSUE TITLE
Define Content-Length for Range Normalization in FileStreamResultExecutor.cs

### ISSUE THREAD

**Issue by cjhillbrand** [dotnet/aspnetcore#45734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to author a proxy that downloads blobs from Azure storage and returns the blob to the caller of the API. I am trying to use the FileStreamResult to return chunks of the blob with a status code of 206 (which is working as expected for a few ranges). 

The issue I am coming across is that the API I am authoring does not download the entirety of the blob into memory, but leverages the Azure Storage API Range headers, to only bring down a subset of bytes from the blob. When the caller of the proxy offers a range of say, bytes=20-30, the length of the content returned from Azure Storage is only 10 bytes long, when the FileStreamExecutor executes, the [Range Normalization](https://github.com/dotnet/aspnetcore/blob/main/src/Shared/RangeHelper/RangeHelper.cs#:~:text=internal%20static%20RangeItemHeaderValue%3F%20NormalizeRange(RangeItemHeaderValue%20range%2C%20long%20length)) is called and asserts the length of the file is greater than or equal to the "From" and "To" properties on the Range Headers provided by the client.

In the scenario above the file length (10 bytes) is much shorter than the ranges provided (20/30), so this is what kicks off the chain to ultimately return the 416, but this is all correct information - its just the chunking is being done downstream. (i.e. let azure storage do the chunking on its side and not in the API that I am writing)

### Describe the solution you'd like

I understand the purpose of the normalization is to return the Content-Range header correctly, but I am curious does the HTTP spec define this as a required header. If not, would it be "ok" to make this configurable? (Either at FileStreamResult construction time, or at startup.... not sure...)

I am having to hand roll my own IActionResult that exhibits this exact behavior - as this is an internal API, the "correct" headers are nice to haves, but not strictly necessary.

**Comment by cjhillbrand** [comment]
I actually figured I could just set the `FileStreamResult` property `EnableRangeProcessing` to false and circumvent all of the Range Headers, which is ok for now, but not ideal.

**Comment by cjhillbrand** [comment]
did not mean to close the issue. my bad.

**Comment by halter73** [comment]
@Tratcher Can you quickly say whether MVC is being to strict with the Range request headers in this case?

**Comment by Tratcher** [comment]
FileStreamResult is working as intended, but isn't being given the expected inputs. It's expecting to receive the entire FileStream, from which it checks the length and does range processing.
https://github.com/dotnet/aspnetcore/blob/5b43ed1b8355c9fdebb44b0035d215a563435562/src/Mvc/Mvc.Core/src/Infrastructure/FileStreamResultExecutor.cs#L43-L51

It wasn't designed to work with subsegments segments like this. Since you don't want normal range handling, disabling EnableRangeProcessing is the correct approach for now. 

@cjhillbrand what is the ideal you'd want? There may be a different type that better suits your needs.

**Comment by cjhillbrand** [comment]
At a higher level, the hope is to be able to use the Framework to elicit a 206 response without bringing the entire file into the application at once.

**Comment by Tratcher** [comment]
> and still enable range processing

Can you break down what range processing you'd want?
- Set the status code to 206
- Set the Content-Range header
- ?

Since you're doing the range processing in the backend, why not set these fields yourself?

**Comment by cjhillbrand** [comment]
I suppose the only range processing I would need is the status code being set to 206, which I can do ad-hoc. I try my hardest to stay away from editing the http context directly as the framework tends to set properties on it better than I usually do :) 

Anyways, it seems that there are suitable work arounds for what I am looking for, and this is more of a feature request than an issue. I will search around to see where I can submit this as a feature request and close the comment. 

Thanks for taking the time to entertain my questions.

**Comment by Tratcher** [comment]
This is a fine place for a feature request, we just need to clarify what the feature would be.

**Comment by cjhillbrand** [comment]
Gotcha, then w/o trying to get too deep into implementation details. I think it would be sufficient to have some way to communicate to the `FileStreamResult` that the range processing is being done on a segment of a larger whole, and some additional contextual information (i.e. range start/range end). 

The behavior would hopefully be the same as it is currently when `enableRangeProcessing: true` except that the Range Normalization would not take place which may result in the `Content-Range` header not being set (as there may or may not be insufficient information. 

I would imagine something like: 
```
RangeProcessingOptions rangeOptions = new RangeProcessingOptions(isSegment: true, startRange: 10, endRange: 30, contentLength: 1024 /*<-- (nullable) The size of the entire file*/)
return new FileStreamResult(myStream, myContentType, rangeOptions));
```

**Comment by Tratcher** [comment]
The Content-Range header is required for clients to process the response correctly.

https://www.rfc-editor.org/rfc/rfc7233#section-4.1

>    If a single part is being transferred, the server generating the 206
   response MUST generate a Content-Range header field, describing what
   range of the selected representation is enclosed, and a payload
   consisting of the range

The length can be ommited if it's not known.

`Content-Range: bytes 10-20/*`
