### ISSUE TITLE
ASP.Net Razor Pages -> Cross Page Posting

### ISSUE THREAD

**Issue by himanshukodwani** [dotnet/aspnetcore#45733]
I am using ASP.Net Razor Pages in one of my projects. I need to verify user data submitted through a form and then again post the same data to the payment provider. Somehow, I cannot find a way to do it, and redirecting is not an option that I have. The payment provider needs the data posted.

**Describe the solution you'd like**
I need a simple method that I can use to post to another page or site.

**Describe alternatives you've considered**
I have tried to encapsulate data into a generated HTML page. Set its forms handler to the payment provider URL and run auto submit through Javascipt upon page load.  Then I do something like this: "return Content(htmlTextGenerated);" But it's just a hack and I need a cleaner way to do it.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
