### ISSUE TITLE
3rd party notices link does not work

### ISSUE THREAD

**Issue by talanc** [dotnet/aspnetcore#45745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"dotnet new webapp ..." displays the following output:

The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Going to the aka.ms link goes to https://github.com/dotnet/aspnetcore/blob/release/7.0-preview1/THIRD-PARTY-NOTICES.txt which does not exist.

### Expected Behavior

Update aka.ms link to go to https://github.com/dotnet/aspnetcore/blob/release/7.0/THIRD-PARTY-NOTICES.txt instead

**Comment by TanayParikh** [comment]
@mkArtakMSFT @danmoseley looks like we need to update the aka.ms redirection. I believe you may have the perms.

**Comment by mkArtakMSFT** [comment]
I'll tackle this. Thanks!

**Comment by mkArtakMSFT** [comment]
Just fixed this!
