### ISSUE TITLE
Custom model binding in Blazor's SupplyParameterFromQueryAttribute

### ISSUE THREAD

**Issue by Bouke** [dotnet/aspnetcore#45747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to bind a query parameter to a non-supported parameter type in Blazor using `SupplyParameterFromQueryAttribute`. This results in an exception like this: `NotSupportedException: Querystring values cannot be parsed as type 'MyType'.`.

### Describe the solution you'd like

ASP.NET Webforms has supported custom model binding for as long as I've been using the framework. This has been supported in ASP.NET MVC later on and was also ported over to ASP.NET Core with [IValueProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.ivalueprovider?view=aspnetcore-1.0) and [IValueProviderFactory](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.ivalueproviderfactory?view=aspnetcore-1.0). I would like an extensible  solution to be able to provide my custom value providers.

For scalar types the workaround is to accept a string value and have the property's setter do the conversion. For complex types I don't think there's a nice solution.

**Comment by javiercn** [comment]
@Bouke thanks for contacting us.

This is not a feature Blazor support. It brings quite a good amount of complexity, and it is not something people regularly rely on in Blazor applications.

This is also something that you can implement yourself, it is not something we plan to provide.
