### ISSUE TITLE
Latest supported version on .NET Framework

### ISSUE THREAD

**Issue by nitramavfank** [dotnet/aspnetcore#45743]
I use ASP.NET Core 2.0 on .NET Framework and wants to upgrade to the latest supported ASP.NET Core-version on .NET Framework. 

On https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet, it says:

> To help facilitate migrating applications to ASP.NET Core on .NET Core, the following ASP.NET Core 2.1 (latest patched version only) [packages](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1) will be supported on the .NET Framework and follow the [support cycle](https://support.microsoft.com/en-us/lifecycle/search?alpha=.net%20framework) for those .NET Framework versions.

On NuGet, the [latest stable version](https://www.nuget.org/packages/Microsoft.AspNetCore/) of the package `Microsoft.AspNetCore` is 2.2.0. In the [migration documentation](https://learn.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-7.0&tabs=visual-studio), there are also instructions on how to upgrade from 2.1 to 2.2 when using .NET Framework.

Is the policy page above really correct that the latest supported version of ASP.NET Core on .NET Framework is latest 2.1.x-patch, considering 2.2 has been released and is compatible with .NET Framework?

**Comment by javiercn** [comment]
@nitramavfank thanks for contacting us.

ASP.NET Core 2.2 was a "Current" release and it is out of support. The latest supported version on .NET Framework is ASP.NET Core 2.1
