### ISSUE TITLE
PageTitle Headoutlet + Changing layouts causes rendering to fail

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#45752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the _Host.cshtml has a html `<title>` defined in the `<head>` and dynamic layouts are used with the `<PageTitle>` component, rendering fails when the layout is changed. Maybe related to this issue? https://github.com/dotnet/aspnetcore/issues/42902

### Expected Behavior

HeadOutlet should handle title updates properly when switching layouts. If `<head>` isn't permitted to have a <title> then a more meaningful error/exception should be provided. This took a long time to debug.

### Steps To Reproduce

Reproduction: https://github.com/vflame/BlazorPageTitleLayoutError

![pagetitleerror](https://user-images.githubusercontent.com/12207061/209449489-dde691c8-6df4-410d-b4a4-fa6a2c8b014d.gif)

### .NET Version

.net 7

**Comment by vflame** [comment]
Another thing I wanted to add--any usage of `<PageTitle>` with dynamic layouts is very flaky and causes desyncs during DOM updates based on timing/rendering speed/user iteractions:
`
One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vflame.
@MackinnonBuck can you please investigate this when you're back? Thanks!

**Comment by MackinnonBuck** [comment]
Hi @vflame,

I tried you repro and I wasn't able to reproduce the bug:

https://user-images.githubusercontent.com/10456961/210618275-02441293-8f97-4a54-bbfb-d8b8670febf7.mp4

Could you delete the bin and obj folders, clear browser cache, and run using `dotnet run` to see if you still experience the issue? Thanks.

**Comment by vflame** [comment]
> Hi @vflame,
> 
> I tried you repro and I wasn't able to reproduce the bug:
> 
>  repro_works.mp4 
> Could you delete the bin and obj folders, clear browser cache, and run using `dotnet run` to see if you still experience the issue? Thanks.

I cleared the bin/obj and ran with dotnet and see the following in the console output below.

I did some more testing and found that it errors out on Chrome (Version 108.0.5359.125 (Official Build) (64-bit)), but is fine on Firefox (Version 108.0.1 (64-bit)). 

Out of curiosity, I re-tested the issue I opened here: https://github.com/dotnet/aspnetcore/issues/40056 and found that it's only impacted by Chrome as well (works fine in Firefox). 

![pagetitleerror2](https://user-images.githubusercontent.com/12207061/210664403-f47c2f14-652f-424e-ae04-27cadd51f2a0.gif)

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'insertBefore')
      System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9y2yAhQ18o55BX0Hy0oexn-PxyrKK_oTLYUW4-Hz1QI'.
      System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
       ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---
```

**Comment by MackinnonBuck** [comment]
@vflame Thanks, that helps. Did clearing browser cache make a difference at all? I also see that there are some extensions active in Chrome - does disabling those make a difference? What happens in Edge?

Thanks!

**Comment by MackinnonBuck** [comment]
Thanks for confirming the cause of the issue, @vflame.

> As an enhancement, is it possible to return to Blazor what the offending DOM update/element was?

It might be possible for Blazor to somehow provide some info about the location in the DOM tree where the rendering error occurred. However, catching invalid DOM mutations proactively could end up being a nontrivial task, because the distinction needs to be made between mutations made by Blazor vs. external, "invalid" DOM mutations.

This issue has been moved to the "Discussions" milestone so we can gather more feedback from the community and measure the impact of this issue.

Thanks again!
