### ISSUE TITLE
EventCallback<Action<T>> Does not invoke delegate / How to convert Func<T> to EventCallback?

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#45754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Given the 3 razor components below, `EventCallback<Action<ReportComponent>>` does not invoke delegate properly, whereas `Func<ReportComponent>` does. 

IReportable.cs
```c#
public interface IReportable
{
    public void Display(string str);
}
```

ReportComponent.razor

```c# 
<span>@_display</span>

@code {
    private string _display;
    public void Display(string str)
    {
        _display = str;
        StateHasChanged();
    }
}

```

Index.razor
```c#
@page "/"

<ChildComponent OnEventCallback="() => GetIReportable()" OnFunc="() => GetIReportable()"></ChildComponent>
<ReportComponent @ref="_report" />

@code
{   
    ReportComponent? _report;

    public IReportable? GetIReportable()
    {
        return _report;
    }
}
```

ChildComponent.razor:
```c#
@using System.Diagnostics;

<button @onclick="TriggerFunc">Trigger Func</button>
<button @onclick="TriggerEventCallback">Trigger Event</button>

@code {

    [Parameter] public EventCallback<Action<IReportable>> OnEventCallback { get; set; }
    [Parameter] public Func<IReportable> OnFunc { get; set; }

    public async Task TriggerFunc()
    {
        OnFunc()?.Display("from func");
    }

    public Task TriggerEventCallback()
    {
        return OnEventCallback.InvokeAsync((reportable) =>
                    {
                        Debugger.Break(); //never breaks
                        reportable.Display("from callback");
                    });
    }
}

```

### Expected Behavior

I would expect `EventCallback<Action<IReportable>>` to invoke `ReportComponent.Display(string str)` and update the UI, just like `Func<IReportable>` does. If this behavior is intended, I couldn't find best practices/guidance on it.

### .NET Version

.net 7

**Comment by javiercn** [comment]
@vflame thanks for contacting us.

Your event callback is only passing a function as an argument, not invoking it. It is the function that subscribes to the event the one that needs to receive the callback and can choose to invoke it. In your case, you are ignoring the argument.

```csharp
  return OnEventCallback.InvokeAsync((reportable) =>
              {
                  Debugger.Break(); //never breaks
                  reportable.Display("from callback");
              });
```

For example:

```csharp
<ChildComponent OnEventCallback="(action) => action(GetIReportable())"
```

**Comment by vflame** [comment]
Makes perfect sense. Thanks for the clarification.
