### ISSUE TITLE
Improvements to null state analysis on AuthorizationResult

### ISSUE THREAD

**Issue by Kairarara** [dotnet/aspnetcore#45751]
## Summary

Static analysis should mark the the property "Failure" as not null when the property "Succeeded" is false

## Motivation and goals

Reduce the number of unnecessary warnings

## Risks / unknowns

A user may ignore all warnings and call AuthorizationResult.Failed(null) resulting in an AuthorizationResult with Failure = null and Succeeded = false, handling this could result in breaking changes

**Comment by captainsafia** [comment]
> A user may ignore all warnings and call AuthorizationResult.Failed(null) resulting in an AuthorizationResult with Failure = null and Succeeded = false, handling this could result in breaking changes

Triage: We had a conversation around whether or not this assumption is correct. At the moment, we feel that it is probably a guarantee that when `Succeeded` is `false` then there will be an `AuthorizationFailure` set.

@Kairarara Would you be interested in submitting a PR for this? You can do so by adding a `Nullable` attribute here:

https://github.com/dotnet/aspnetcore/blob/97e26bd40c52d82afca150f65f1ee948336a18d3/src/Security/Authorization/Core/src/AuthorizationResult.cs#L27

**Comment by frederikrosenberg** [comment]
Is this being work on, otherwise I would like to pick it up.

**Comment by captainsafia** [comment]
> Is this being work on, otherwise I would like to pick it up.

No one is working on this. We've applied the `help wanted` label so you're welcome to open a PR if interested. Thanks in advance!
