### ISSUE TITLE
Arabic text get reversed in <pre> tag in MVC app

### ISSUE THREAD

**Issue by medmor** [dotnet/aspnetcore#45757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am having real problem with Arabic text in `<pre>` tag.
For example if I put this code in a page view.
```
    <pre>
        &lt;html>
        &lt;head>
            &lt;title>First HTML Page&lt;/title>
        &lt;/head>
        &lt;body>
            &lt;h1><span>اول صفحة ويب</span>&lt;/h1>
            &lt;p>هذه أول فقرة ننشؤها في أول صفحة&lt;/p>
        &lt;/body>
        &lt;/html>
     </pre>
```
I get this display in browser
![image](https://user-images.githubusercontent.com/35731087/209463121-a95357ee-9638-464c-ae71-57854e34a240.png)
Here you can see that the arabic text is reversed
This happens just in ASP.NET Core MVC. In other frameworks, the text is displayed correctly.
I've tried to change the `dir` and the `lang` attributes but it does not help.

### Expected Behavior

The text must not be reversed

### Steps To Reproduce

Create a new mvc project.
Copy the code bellow and past it in a .cshtml file
```
    <pre>
        &lt;html>
        &lt;head>
            &lt;title>First HTML Page&lt;/title>
        &lt;/head>
        &lt;body>
            &lt;h1><span>اول صفحة ويب</span>&lt;/h1>
            &lt;p>هذه أول فقرة ننشؤها في أول صفحة&lt;/p>
        &lt;/body>
        &lt;/html>
     </pre>
```
Open the page with a browser.
You will notice the Arabic text reversed.

### .NET Version

dotnet 7

**Comment by javiercn** [comment]
@medmor thanks for contacting us.

Can you capture the output from the page (from the browser). Put it on an HTML file in the wwwroot folder and see if you get the same result? 

It is very likely that bootstrap or other CSS in your app is causing this and not MVC specifically. That will help confirm it.

**Comment by medmor** [comment]
@javiercn Thank you for answring and for guiding me to check bootstrap.
I was using and older version of bootstrab theme and when I changed it, the problem was resolved.
