### ISSUE TITLE
gRPC Transcoding KnownTypes.FieldMask as query parameter

### ISSUE THREAD

**Issue by Oskarsson** [dotnet/aspnetcore#45753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not entirely sure if this is a bug or if it should be a feature request. Currently it is not possible to use a _FieldMask_ field as a query parameter for GET calls, even if it shows up in the swagger UI. The field value will also always be null regardless of what value you provide.

The swagger UI input field also appears be inconsistent with how the input value is expected when using FieldMask in a POST call. When using a _FieldMask_ field in a POST call the expected JSON is `{"fieldName": "a,b,c"}` while in a GET call the swagger UI shows the query parameter `fieldName.paths`, I would expect these two to have the same name.

![image](https://user-images.githubusercontent.com/5382351/209454825-7527de98-ea0e-411a-964e-4ecb247efd90.png)

VS
![image](https://user-images.githubusercontent.com/5382351/209454842-2ebb5509-4a20-4e25-b6a8-ac4cd7469f19.png)

### Expected Behavior

- The FieldMask field should be populated with the input value in the query parameter.
- The FieldMask query parameter name should be _readMask_ and not _readMask.paths_

### Steps To Reproduce

1. Create a server using the following proto file:

```Proto
syntax = "proto3";

package grpc.transcoding.test;

import "google/protobuf/field_mask.proto";
import "google/api/annotations.proto";

service Greeter {
  rpc Get(GetRequest) returns (GetResponse) {
    option (google.api.http) = {
      get: "/api/v1/greeter"
    };
  }
}

message GetRequest {
  google.protobuf.FieldMask read_mask = 1;
  string query = 2;
}

message GetResponse {
}
```
2. Enable Swagger UI / GRPC Transcoding
3. Set a breakpoint in the GET method to inspect the incoming fields.
4. **ERROR 1:** The Swagger UI will show a query parameter for : _readMask.paths_ instead of expected _readMask_
5. Send a GET call throught the Swagger UI OR any other rest tool. The endpoint should be similar to this according to the swagger UI: _http://localhost:5251/api/v1/greeter?readMask.paths=a&readMask.paths=b&query=query-value_
6. **ERROR 2:** The ReadMask field is null.
7. Try the following variations, none of them will work:
  GET: _http://localhost:5251/api/v1/greeter?readMask=a&readMask=b&query=query-value_
  GET: _http://localhost:5251/api/v1/greeter?readMask=a,b&query=query-value_

### .NET Version

7.0.0

### Anything else?

Merry Christmas!

**Comment by vahpetr** [comment]
Hello, i have similar problems:
1/ `google.protobuf.StringValue q = 1;` converted to `q.value` parameter, must be `q`
2/ `google.protobuf.Timestamp after_created_at = 2;` converted to `afterCreatedAt.seconds` and `afterCreatedAt.nanos` parameter, must be `afterCreatedAt`

PS
`google.protobuf.FieldMask read_mask = 1;` is reference type = nullable type, i think needs to be added `[(google.api.field_behavior) = REQUIRED]` to make it mandatory. This is how grpc-gateway works

**Comment by JamesNK** [comment]
This will be fixed in a .NET 7 servicing release. Probably 7.0.5.
