### ISSUE TITLE
Unable to UnProtect payloads protected with a key which is still not expired

### ISSUE THREAD

**Issue by MandeepShahi** [dotnet/aspnetcore#45763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We use Data Protection apis integrated with MSAL to store encrypted tokens on Cosmos Db. The keys used for encryption are also stored on Cosmos Db. The keys themselves are encrypted using some certificate. 

We have set the key lifetime as 1 year. Every thing was going smooth but a month into this feature, we saw that new key was written to the key ring repository in Cosmos Db. The earlier key wasn't expired yet (10 months of lifetime still remains). I didn't understand why would this happen! To make matters worse, the payloads protected with earlier key failed to be decrypted despite the earlier key being present in the key ring resource. This would mean that the previous key would have been revoked. We don't call RevokeKey in our system anywhere. Is there some default construct by which keys get revoked?

The below link shows the current state of key ring repository in Cosmos Db. It should be noted that the first key is still not expired and yet a new key got added. 

In which all cases does a key get revoked? Is revocation in any way dependent on Expiry time?

[DataProtectionKeys](https://docs.google.com/document/d/1OqEj5vexzAg2j5gb0xYappJ4YnJqdTiF5i2jlaLO2nc/edit?usp=sharing)

**Comment by blowdart** [comment]
While there is a revocation api, it's not actually wired up to anything, it's meant for folks writing utilities, and revocation marks a key in a very particular.

We don't provide a CosmosDB provider, and I don't know how MSAL uses data protection. Keys expire naturally after their expiry date but they never get deleted specifically so you can continue to unprotect things using that key, expiry only means it's not used for encrypting new payloads.

So this is weird.

Can you show us your configuration / startup code as a starting point?

**Comment by MandeepShahi** [comment]
This is what I found odd as well. The key is not expired. It is not deleted as well, I have written the CosmosDb provider in a manner that new keys being used are appended to already present list of keys. The seemingly revoked key is present as well and I can see that the payload was protected with that key but unprotecting isn't working on it. 

Here's the configuration snippets

This is how we register MSAL token caching services along with dataprotection ones in ConfidentialClientApplication objects
![image](https://user-images.githubusercontent.com/44645800/210623685-fc4ba061-0239-4f43-8938-3b404c39c9d0.png)

Here's how each of the extensions get added
![image](https://user-images.githubusercontent.com/44645800/210623876-2dcd1a83-0b4b-42ff-9908-5c7b04d520ea.png)

Finally, here's the CosmosdbProvider registration in DataProtection services
![image](https://user-images.githubusercontent.com/44645800/210624103-89f6a880-060c-47a3-ad71-b08e6dd9cfe8.png)

**Comment by MandeepShahi** [comment]
@blowdart Any update on this? I'm experiencing the above issue in almost all instances using this data protection layer!

**Comment by blowdart** [comment]
I think we're going to need a repro, including the code of your cosmos db provider before we can investigate
