### ISSUE TITLE
[Blazor Wasm, JsInterop] JsRuntime.InvokeAsync finishes too soon, returning null

### ISSUE THREAD

**Issue by jasonswearingen** [dotnet/aspnetcore#45770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor WASAM

the following code is in my `OnAfterRenderAsync()` call

```cs
_routeMapModule = await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/BlazingTrails.Shared/Components/Map/RouteMap.razor.js");
```

However this task completes successfully, returning `null` fairly quickly.   I tried passing a CancelationToken and 30 sec Timeout but it still exits with `null` after less than a second.

the workaround is to wrap it in a while loop:

```cs
			while (_routeMapModule is null)
			{
				_routeMapModule = await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/BlazingTrails.Shared/Components/Map/RouteMap.razor.js");
				await Task.Delay(30);
			}
```

This will loop 2 or 3 times before completing successfully.  I verified that the loaded `RouteMap.razor.js` is only loaded once by adding a `console.warn()` at the bottom of it.

This `.js` file exports some async functions, not doing any other work upon load.

### Expected Behavior

it should return the jsObject successfully or throw because of timeout or whatever.

### Steps To Reproduce

sorry I don't have a simple repro.   let me know if you really need one to triage, and if so I will try to find time to make a new proj doing so.

### .NET Version

7.0.101

### Anything else?

win10 using vs2022 community.

**Comment by javiercn** [comment]
@jasonswearingen thanks for contacting us.

Can you turn on first-chance exceptions? I suspect that what is happening is not that it is returning null, but that a `TaskCancelledException` is being thrown and Blazor automatically catches those.

Putting some code after the assignment will validate this theory (that code will not run) or wrapping the assignment inside a try catch would do the same thing.

I took a quick look at the codebase and I can't see any place where we would just return null. Are there any errors in the developer tools console?

**Comment by jasonswearingen** [comment]
Hi, I turned on my computer this morning and tried reproing again...   and now it all works fine (InvokeAsync completes successfully on the first call)

I didn't do anything besides reboot my computer.

Sorry, please leave this open for a few days and I don't see it repro again, I'll go ahead and close it.
