### ISSUE TITLE
Why should a principal be recreated?

### ISSUE THREAD

**Issue by Sensarg22** [dotnet/aspnetcore#45776]
Why recreate a principal if we know that nothing important has changed. There is some side effect here.

https://github.com/dotnet/aspnetcore/blob/84c0baa9a57bd6448cd1bf78b64d2c1658bf5ef6/src/Identity/Core/src/SecurityStampValidator.cs#L73

**Comment by captainsafia** [comment]
Triage: @HaoK Do you have any insights on this?

**Comment by HaoK** [comment]
Because the claims in the cookie are cached and when we check the stamp, that's also the time we regenerate the claims for the user from the database.  Otherwise only security stamp changes would cause claim updates which isn't the intent

**Comment by Sensarg22** [comment]
@HaoK, Thanks for the answer. I think it's worth separating these processes. So that the Security Stump validation is only a validation, and a scheduled cookie update is a scheduled cookie update. Now reducing the security stamp check interval will lead to unnecessary cookie updates when nothing has changed.
