### ISSUE TITLE
Microsoft.aspnetcore.identity.ui v 7.01 will not run.

### ISSUE THREAD

**Issue by jasonleach** [dotnet/aspnetcore#45773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Install the nuget package for Microsoft.AspNetCore.Identity.Ui v7.01. In my case i just updated from v7.0.0
watch it fail on run.
first line of program.cs is var builder = WebApplication.CreateBuilder(args); 
breaks on this line with "DirectoryNotFound" exception C:\Users\[MyUserName]\.nuget\packages\microsoft.aspnetcore.identity.ui\7.0.1\staticwebassets\V5\
and the debug session crashes.

I went looking for that directory. found it.  right where it should be. contains similar data to ...\V4\.
i downgraded to v7.0.0 and it works again.
I just like to be current with nuget packages as i always assume the later version fixes something. (not so much this time...)

### Expected Behavior

it just runs like it did before the "upgrade"

### Steps To Reproduce

update Microsoft.AspNetCore.Identity.Ui to v7.0.1 from v7.0.0 
using asp.net core in a web app targetting .net framework 7.
using Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.4.3

### Exceptions (if any)

 "DirectoryNotFound" exception C:\Users\[MyUserName]\.nuget\packages\microsoft.aspnetcore.identity.ui\7.0.1\staticwebassets\V5\

### .NET Version

.net framework 7

**Comment by javiercn** [comment]
@jasonleach thanks for contacting us.

That sounds a bit strange, but there was recently an MSBuild issue that affected this area. Can you try cleaning the bin and obj folders and running the app from the command line with dotnet run?

**Comment by jasonleach** [comment]
Thanks, @javiercn 
I tried your suggestion: deleted bin and obj. ran from command line.  it worked, and subsequently i can run from the IDE.
woohoo!
