### ISSUE TITLE
Add keys to OIDC state and retrieve at callback

### ISSUE THREAD

**Issue by qui8t** [dotnet/aspnetcore#45785]
Implementing login with Google in an ASP.NET Core app, I would like to add key-value pairs (kvp) to the OIDC `state` and retrieve them at the callback. If I understand it correct, I should add the KVP to `AuthenticationProperties`; however, at the callback, this property does not contain the KVP I set.

```csharp
private string _key = "come-back safe";

[AllowAnonymous]
[HttpGet]
public IActionResult Signin()
{
    var props = _signInManager.ConfigureExternalAuthenticationProperties(
        provider: GoogleDefaults.AuthenticationScheme,
        redirectUrl: "account/callback");

    props.Parameters.Add(_key, "sure!");
    return new ChallengeResult(GoogleDefaults.AuthenticationScheme, props);
}

[AllowAnonymous]
[HttpPost]
public async Task<IActionResult> Callback()
{
    var info = await _signInManager.GetExternalLoginInfoAsync();
    var props = info.AuthenticationProperties;
    var contains = props.Parameters.TryGetValue(_key, out object value);

    // contains is always false.
}
```

**Comment by captainsafia** [comment]
Triage: The properties are sent to the OIDC provider but there is no guarantee that the OIDC provider will send those back for processing in the callback. Per the documentation, you'll probably want to leverage the `AuthenticationProperties.Items` property.

**Comment by qui8t** [comment]
thank you @captainsafia! I was able to use `Items` successfully.
