### ISSUE TITLE
BlazorServer.styles.css

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#45787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Where is `<link href="BlazorServer.styles.css" rel="stylesheet" />`? I don't find it anywhere in the bootstrapped application! https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

```
Refused to apply style from 'https://myapp/BlazorServer.styles.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### .NET Version

7.0.101

**Comment by ConnerOrth** [comment]
From memory this should be in the index.html file of the blazor project.

**Comment by javiercn** [comment]
@khteh thanks for contacting us.

The file is autogenerated and served via static web assets during development. It is copied into the wwwroot folder of the published app during publish. The file follows the naming convention `<<appName>>.styles.css`. If you want to inspect it, is inside the obj folder.

**Comment by khteh** [comment]
Why the runtime console error?

**Comment by javiercn** [comment]
@khteh if you look at the network tab, it is likely that something else is being served instead.

**Comment by khteh** [comment]
![Screenshot from 2022-12-28 17-51-07](https://user-images.githubusercontent.com/3871483/209793279-3b4e96dd-12f5-447c-ad6c-10c16a51db21.png)

**Comment by javiercn** [comment]
@khteh The response coming from the server is a 404, so that is why you are seeing that error in the browser console.

That can be because the name of the file in the link does not match the naming convention, because you have disabled scoped CSS, or because you removed all the scoped CSS files.
