### ISSUE TITLE
[Blazor WASM] An exception occurs while rendering multiple components that use IJSStreamReference 

### ISSUE THREAD

**Issue by capdiem** [dotnet/aspnetcore#45799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a component, TestComponent, which needs to read bytes from JS, using `IJSStreamReference`. It is normal when I render only one TestComponent on the page. But when I render multiple TestComponents, it throws an exception:
```
Unhandled exception rendering component: An exception occurred executing JS interop: JSON serialization is attempting to deserialize an unexpected byte array.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: JSON serialization is attempting to deserialize an unexpected byte array.. See InnerException for more details.
```

### Steps To Reproduce

there is a [repro project](https://github.com/capdiem/StreamWasmTestApp).

### .NET Version

7.0.100

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @capdiem.
@TanayParikh can you please investigate this? Thanks!

**Comment by TanayParikh** [comment]
Hello @capdiem, thanks for reaching out. This is due to a known issue with multiple simultaneous streams. We'll be tracking the fix for this issue in https://github.com/dotnet/aspnetcore/issues/38842. As such, closing this issue out as a duplicate.
