### ISSUE TITLE
 IFormFileCollection doesn't bind 

### ISSUE THREAD

**Issue by clleker** [dotnet/aspnetcore#45794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a nested object and except IFormFileCollection others binded. I have tried all combinations but I didn't be a success

----my object-----
 public class ProductCardAddInDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ProductDetail { get; set; }
        public string AdditionalInfo { get; set; }
        public ProductCardAttributesGroupAddInDto[] ProductCardAttributesGroup { get; set; }
    }

    public class ProductCardAttributesGroupAddInDto
    {
        public int ProductId { get; set; }
        public int AttributeGroupId { get; set; }
        public ProductCardAttributesAddInDto[] ProductCardAttributes { get; set; }
    }

    public class ProductCardAttributesAddInDto
    {
        public int AttributeId { get; set; }
        public int ProductAttributeGroupId { get; set; }
        public int ParentId { get; set; }
        public ProductCardItemAddInDto ProductCardItem{ get; set; }
    }

    public class ProductCardItemAddInDto
    {
        public string Sku { get; set; }
        public string Barcode { get; set; }
        public ProductCardPriceAddInDto productCardPrice { get; set; }
        public ProductCardPictureAddInDto ProductCardPicture{ get; set; }
    }

    public class ProductCardPriceAddInDto
    {
        public decimal SalesPrice { get; set; }
        public decimal IncludingVatPrice { get; set; }
        public decimal PurePrice { get; set; }
        public decimal ProductCost { get; set; }
    }

    public class ProductCardPictureAddInDto
    {
        public string Dummy { get; set; }
        public IFormFileCollection Pictures { get; set; }
    }

![image](https://user-images.githubusercontent.com/35314341/209866233-92261472-65da-4840-ae2a-4bfd7905e9bf.png)

![image](https://user-images.githubusercontent.com/35314341/209866283-e86f24a0-a51e-474c-b57e-05b5ba31f61c.png)

![image](https://user-images.githubusercontent.com/35314341/209866339-f0313b1d-b509-4cbd-88b3-0921163fc07b.png)

### .NET Version

6.0.100

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Out of curiosity, does it work if you move your mapped property to the top-level? In other words, define ` public IFormFileCollection Pictures { get; set; }` on the `ProductCardAddInDto` type?

@dougbu do you happen to remember if there was some kind of unique behavior around files? I vaguely remember something (maybe I'm wrong) that files specifically can bind if they're top-level parameters.

**Comment by clleker** [comment]
Step 1
![image](https://user-images.githubusercontent.com/35314341/209992120-695d83fa-f03f-474a-8122-8c3553feb4fb.png)
Step 2
![image](https://user-images.githubusercontent.com/35314341/209992161-0f1aedb3-df5a-4800-b295-1f42b997ce7e.png)
Step 3
Axios converts automatically to FormData . I haven't touched converting operation
![image](https://user-images.githubusercontent.com/35314341/209992133-2ec5acf6-093d-4cb5-be92-4e69fbad5563.png)

---My new classes ---
 public class ProductCardAddInDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ProductDetail { get; set; }
        public string AdditionalInfo { get; set; }
        public IFormFileCollection Test { get; set; }
        public ProductCardAttributesGroupAddInDto[] ProductCardAttributesGroup { get; set; }
    }

    public class ProductCardAttributesGroupAddInDto
    {
        public int ProductId { get; set; }
        public int AttributeGroupId { get; set; }
        public ProductCardAttributesAddInDto[] ProductCardAttributes { get; set; }
    }

    public class ProductCardAttributesAddInDto
    {
        public int AttributeId { get; set; }
        public int ProductAttributeGroupId { get; set; }
        public int ParentId { get; set; }
        public ProductCardItemAddInDto ProductCardItem{ get; set; }
    }

    public class ProductCardItemAddInDto
    {
        public string Sku { get; set; }
        public string Barcode { get; set; }
        public ProductCardPriceAddInDto ProductCardPrice { get; set; }
        public IFormFileCollection ProductCardPictures  {get; set; }
    }


public class ProductCardPriceAddInDto
    {
        public decimal SalesPrice { get; set; }
        public decimal IncludingVatPrice { get; set; }
        public decimal PurePrice { get; set; }
        public decimal ProductCost { get; set; }
    }
Result
![image](https://user-images.githubusercontent.com/35314341/209992661-d6267cf2-abdc-4a23-b3db-255b459a3023.png)
![image](https://user-images.githubusercontent.com/35314341/209992771-d1f21c1c-32f4-4299-b403-af6d40ab7686.png)
 it  really  made me so tired

**Comment by dougbu** [comment]
> Thanks for contacting us. Out of curiosity, does it work if you move your mapped property to the top-level? In other words, define ` public IFormFileCollection Pictures { get; set; }` on the `ProductCardAddInDto` type?
> 
> @dougbu do you happen to remember if there was some kind of unique behavior around files? I vaguely remember something (maybe I'm wrong) that files specifically can bind if they're top-level parameters.

The `IFormFileCollection` is used to retrieve _all_ files attached to a request.

Other than https://github.com/dotnet/aspnetcore/blob/ee2cf073d1d030473a96f0d677e5a927cce02943/src/Mvc/test/WebSites/HtmlGenerationWebSite/Views/HtmlGeneration_Home/Input.cshtml and https://github.com/dotnet/aspnetcore/blob/ee2cf073d1d030473a96f0d677e5a927cce02943/src/Mvc/test/WebSites/HtmlGenerationWebSite/Models/Folder.cs, I've never seen it used other than for an `Action` parameter. And, in the case of those files, nothing attempts to bind the `Folder` type (it's used only in the View)).

@clleker, make the `IFormFileCollection` a top-level parameter of your `Action`. I doubt it will work as part of the `ProductCardAddInDto` type.

**Comment by clleker** [comment]
this is really a problem for Asp.net core because my database hierarchy doesn't acknowledge making the IFormFileCollection  as, a top-level parameter as, the Ids of models haven't create yet on database. Anyway, I have divided my operations in two that is. At first, I added products to DB  then their pictures
