### ISSUE TITLE
Server-side WPF causes build failure

### ISSUE THREAD

**Issue by kwon0408** [dotnet/aspnetcore#45802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An ASP.NET Core MVC project does not build if:
 * `<UseWPF>` in `*.csproj` is set to `true` and 
 * the project contains a WPF XAML file (such as `UserControl`) or a link to it. (If there is no such file, build starts normally.)

After the build process starts, an error message shows like below before it is terminated.
> C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5): error : Missing required metadata 'FusionName' for 'C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\7.0.1\ref\net7.0\Accessibility.dll.

### Expected Behavior

Build starts, and if the code has any syntax error, they show up.

### Steps To Reproduce

https://github.com/kwon0408/ServerSideWpfTest

### .NET Version

7.0.101

### Anything else?

* ASP.NET Core version: 7.0.1
* The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022 v17.4.3
* Include the output of dotnet --info:

```
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

런타임 환경:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.307 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  6.0.404 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by javiercn** [comment]
@kwon0408 thanks for contacting us.

I suspect this has to do with the double compilation that WPF does to process the XAML where it first compiles a temporary assembly and then does the actual compilation as part of the build.

You'll have to figure out how, but you can set `GenerateMvcApplicationPartsAssemblyAttributes` in your project file to false and that should prevent the code that is failing to run in that situation.

**Comment by kwon0408** [comment]
I tried the solution. Build was successful, but some of NuGet packages are now getting messed up.

For example, `using Microsoft.EntityFrameworkCore;` shows with a red wavy underline under `EntityFrameworkCore` and `CS0234` error.

In NuGet Package Manager, a warning message shows up at the top of the screen.
> Some NuGet packages are missing from this solution. Click to restore from your online package sources.

but clicking `Restore` results in this message:
> All packages are already installed and there is nothing to restore.

Additionally, I have found that an ASP.NET Core **Razor Pages** project also fails to build under the original conditions satisfied. (Repros are in [the same repo](https://github.com/kwon0408/ServerSideWpfTest) but it contains a 2-project solution instead of a single project)

**Comment by javiercn** [comment]
@kwon0408 thanks for the additional details.

I am not sure what might be going on. Hosting WPF inside a web application is not something that we support nor test for, so I imagine there are a few roadblocks along the way that you'll have to figure out.

Looking at the Blazor Webview support for WPF (which is the most similar thing to what you are trying to do) might help as that does work to "play nice" between both SDKs and might give you a clue of what is happening https://github.com/dotnet/maui/tree/main/src/BlazorWebView/src/Wpf

Other than that, neither the Razor SDK nor the Web SDK can or will take a dependency on WPF, so this is not something that is going to work out of the box.
