### ISSUE TITLE
Allow passing the "ui_locales" parameters for Azure AD B2C flows in Blazor WebAssembly with MSAL

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#45832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In FairPlaySocial we are using Azure AD B2C Flows with MSAL for Authentication, the system already has implemented Culture/Language selection, so we need to be able to pass the "ui_locales" parameter to the Azure AD B2C flow, so that the external page is displayed in the user's selected culture.

We tried to use the Interactive Request Options approach describe in the link below, but the parameter never made it to the external url
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.interactiverequestoptions

### Describe the solution you'd like

We would like to have the Interactive Request Options sending the required parameters to the Azure AD B2C flow
```
public void BeginLogIn()
    {
        InteractiveRequestOptions requestOptions =
            new()
            {
                Interaction = InteractionType.SignIn,
                ReturnUrl = Navigation.Uri,
            };

        requestOptions.TryAddAdditionalParameter("ui_locales", "es-CR");
        Navigation.NavigateToLogin("authentication/login", requestOptions);
    }
```

Alternatively, another possible solution, which may be better is to allow the use of events like this
<img width="554" alt="image" src="https://user-images.githubusercontent.com/3481899/210251500-3865235e-b8da-4156-8447-4f23fb09784d.png">

**Comment by javiercn** [comment]
@efonsecab thanks for contacting us.

If you turn the logs to Trace in your webassembly app, you'll be able to see the exact parameters being passed to the underlying msal-browser request. 

Very likely you need to pass them through `extraQueryParameters` and not directly. Check https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest for reference on the parameter names and values.

In general, if you have issues, try to make it work first on msal directly.

**Comment by efonsecab** [comment]
> @efonsecab thanks for contacting us.
> 
> If you turn the logs to Trace in your webassembly app, you'll be able to see the exact parameters being passed to the underlying msal-browser request.
> 
> Very likely you need to pass them through `extraQueryParameters` and not directly. Check https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest for reference on the parameter names and values.
> 
> In general, if you have issues, try to make it work first on msal directly.

Thaks @javiercn that helped a lot, it is now working for me.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/3481899/210272322-6e047e5f-a4ab-462b-b8c1-3627c81d3013.png">
