### ISSUE TITLE
SignalR Websocket Is Never Closed

### ISSUE THREAD

**Issue by ByronAP** [dotnet/aspnetcore#45834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When only websocket connections are enabled protocol negotiation is disabled thus any websocket client can connect (which is fine).

However, the connection should get disconnected in a timely manner since the handshake is never completed. With the bad client not getting disconnected a server is vulnerable to connection flooding.

To show this simply run a signalr app that only supports websockets and create a generic websocket connection to it.
You will notice the connection stays connected regardless of any timeouts.

### Result

You will notice you never get disconnected and can open as many additional connections as you desire, even to the point of system exhaustion.

### Expected Behavior

The connection should be terminated due to timeout/inactivity.

### Steps To Reproduce

1. Run example app [github.com/ByronAP/SignalR_Connection_Issue](https://github.com/ByronAP/SignalR_Connection_Issue)
2. Connect to it with DWST (or whatever client you prefer) [dwst.github.io](https://dwst.github.io) using the command "/connect ws://localhost:9042/ws"

### Exceptions (if any)

No exceptions have been observed

### .NET Version

7

**Comment by davidfowl** [comment]
Out of curiosity, do you have the debugger attached when running the application? The handshake will timeout the connection after 5 seconds **IFF* the debugger isn't attached the process.

**Comment by ByronAP** [comment]
DAMN IT! closing lol
