### ISSUE TITLE
`Microsoft.AspNetCore.ClientAssets` has a check for .NET6 so it fails on .NET7

### ISSUE THREAD

**Issue by JohnKiller** [dotnet/aspnetcore#45849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Line 50 and 61 of the `targets` file:

https://github.com/aspnet/AspLabs/blob/86eedec8a2f26ce0a32eb5f9fe94492a211c4a33/src/ClientAssets/Microsoft.AspNetCore.ClientAssets/build/netstandard2.0/Microsoft.AspNetCore.ClientAssets.targets#L50

https://github.com/aspnet/AspLabs/blob/86eedec8a2f26ce0a32eb5f9fe94492a211c4a33/src/ClientAssets/Microsoft.AspNetCore.ClientAssets/build/netstandard2.0/Microsoft.AspNetCore.ClientAssets.targets#L61

It checks for older .NET core by just comparing it with the string `.net6.0` so it treats `.net7.0` with the old behaviour, and it breaks.

### Anything else?

I know this package is being reworked as part of #38445 however it would be nice if in the meantime this package could continue to work so we can update to .NET 7.

I can contribute a pull request if it can be merged. Thanks

**Comment by JohnKiller** [comment]
As a workaround, how can I copy the `Microsoft.AspNetCore.ClientAssets.Custom.targets` into my project to make this simple fix? What do I need to put in my `csproj` file?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is going to be covered as part of https://github.com/dotnet/aspnetcore/issues/38445
