### ISSUE TITLE
How to paramterise a partial containing 'expression names'?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/aspnetcore#45845]
The Razor documentation describes how the `asp-for` attribute of a `label` or `input` tag helper is used to specify an 'expression name' which is the property of the model that the server should use to generate the appropriate `label` or `input` markup, i.e. label display name and input validation as specified by the model property's attributes.

What it doesn't explain is how do you specify this expression name via an expression as opposed to hard-coding it. If for example you are using the tag helper in a partial then having a hard coded expression name is not going to be very useful, since your partial is likely to want to target different properties at each place where the partial is used.

Here is a concrete example

I have a form in a Razor page containing loads of fields, all with identical markup.

    @page "{id:int}"
    @model RazorPagesMovie.Pages.Movies.EditModel
    
    <form method="post">
       <div class="form-group">
          <label asp-for="Movie.Title" class="control-label"></label>
          <input asp-for="Movie.Title" class="form-control" />
          <span asp-validation-for="Movie.Title" class="text-danger"></span>
       </div>
       <div class="form-group">
          <label asp-for="Movie.ReleaseDate" class="control-label"></label>
          <input asp-for="Movie.ReleaseDate" class="form-control" />
          <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
       </div>
       <div class="form-group">
          <label asp-for="Movie.Genre" class="control-label"></label>
          <input asp-for="Movie.Genre" class="form-control" />
          <span asp-validation-for="Movie.Genre" class="text-danger"></span>
       </div>
    </form>

Rather than my page file being stuffed with all this copy/paste I decide to eliminate the code duplication using the feature the ASP documentation says I should be using for this, namely a partial.

So I create a partial

    @model object
    
    <div class="form-group">
       <label asp-for="@Model" class="control-label"></label>
       <input asp-for="@Model" class="form-control" />
       <span asp-validation-for="@Model" class="text-danger"></span>
    </div>

...and reference that from my page file using

    <partial name="_MovieField" for="Movie.Title" />

Only problem, nothing works. The `asp-for="@Model"` in the label doesn't resolve the display name for the property so the label is blank, and none of the validation works either.

I've tried passing the desired property in ViewData and accessing that in the partial, but that doesn't work.

    <label asp-for="@(ViewData["PropertyName"])" class="control-label"></label>

I've even tried reflection, but that doesn't work either.

    <label asp-for="@(Model.GetType().GetProperty("Title"))" class="control-label"></label>

Is there any way to get this to work? If not and you simply can't use tag helpers that expect expression names in partials, then that would seem to make partials pretty useless.

Simple project demonstrating the issue here
https://github.com/Neutrino-Sunset/RazorPartialExpressionTest1

Link to original documentation issue here
https://github.com/dotnet/AspNetCore.Docs/issues/25531

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @Neutrino-Sunset.

The reason you're seeing this behavior is because the value of the `asp-for` attribute is interpreted as a `System.Linq.Expression`. The conversion to a `ModelExpression` is done by the Razor compiler. So, what's getting used is the expression as it appears in code, not its evaluated value. You might be able to achieve something similar using a custom tag helper (e.g., a modified version of this [old stackoverflow answer](https://stackoverflow.com/questions/34282640/how-can-i-pass-string-value-for-asp-for-in-asp-net-5)).

**Comment by Neutrino-Sunset** [comment]
That solution (which even the author describes as a dubious hack) is over 7 years old and seems hopelessly out of date.

Specifically `modelExProp.Metadata.EditFormatString` does not currently resolve to any kind of format string for any property with any validation attributes. After much searching I don't see anywhere else to get the format string from in the context of the TagHelper, and without the format string this approach is a dead end.

**Comment by Neutrino-Sunset** [comment]
Interestingly I have discovered that `asp-for` behaves completely differently in the context of an editor template. In that case an editor template defined thus

```
<div class="form-group mt-2">
   <label asp-for="@Model" class="control-label"></label>
   <input asp-for="@Model" class="form-control" />
   <span asp-validation-for="@Model" class="text-danger"></span>
</div>
```

Can then be called as follows

```
@Html.EditorFor(model => model.Movie.Title, "TemplateName")
```

And in this case it actually works as you woud expect. The Razor syntax appears to behave completely differently in the context of a template to a partial.

However display and editor templates seem designed to serve a slightly different purpose, that is projecting a type to a view similar to a WPF data template. They also seem to be built on Html Helpers which are completely undocumented in the current ASP Core documentation. So although this seems to work it's not at all clear whether the different behaviour of templates is due to a rational design decision that can be relied on, or whether it's an implementation oddity that might function differently (or not at all) in the next release.

Personally I find the plethora of different UI reuse technologies in Razor - partials, display templates, editor templates, templated delegates, tag helpers, html helpers, view components, Razor components (Blazor), combined with subtle differences in how the Razor syntax works in some of them, plus in some cases scant or non-existant documentation, is a major frustration with ASP for me. A single consistent UI reuse technology that worked consistently in all cases would be very welcome.

**Comment by javiercn** [comment]
@Neutrino-Sunset partial views do not have "nesting" semantics by default because most of the time, they are not rendering a subset of a form.

That's what the original templated HTML helpers are/where for. If you want to have a partials with that behavior, you can extend the existing PartialTagHelper, copy the `ViewContext` (has a copy constructor) from the ViewContext property, change the `TemplateInfo.HtmlFieldPrefix` based on the `For` property using `ExpressionHelper.GetExpressionText` and you should get something more or less what you are looking for (you might need to play a bit with it, but essentially, you can replicate the code in the `Editor` tag helper to achieve it.

**Comment by javiercn** [comment]
Or you can use https://www.nuget.org/packages/TagHelperPack which contains ready to use editor and display tag-helpers
