### ISSUE TITLE
Log message on logout success incorrectly states "Login completed successfully." (Blazor WASM)

### ISSUE THREAD

**Issue by mmacy** [dotnet/aspnetcore#45846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The debug log message for a successful _logout_ in Blazor WebAssembly incorrectly states that a successful _login_ has occurred.

Looks like maybe a bit of copypasta made its way into _RemoteAuthenticatorViewCore.Log.cs_ - note name of the method the attribute decorates:

https://github.com/dotnet/aspnetcore/blob/45fcfb75dd7ca6c548200dde4f7374a9a451039b/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.Log.cs#L40-L41

### Expected Behavior

Upon successful logout in a Blazor WASM project with logging enabled, the log entry should refer to logout instead of login as it does currently.

Essentially, the first line in this snippet:

https://github.com/dotnet/aspnetcore/blob/45fcfb75dd7ca6c548200dde4f7374a9a451039b/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.Log.cs#L40-L41

Should instead refer to _logout_, as shown here:

```csharp
[LoggerMessage(10, LogLevel.Debug, "Logout completed successfully.", EventName = nameof(LogoutCompletedSuccessfully))]
public static partial void LogoutCompletedSuccessfully(ILogger logger);
```

### Steps To Reproduce

1. Follow the steps for Visual Studio Code in the Microsoft Learn article [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-7.0&tabs=visual-studio-code#authentication-component) to create a Blazor WASM app by using the `dotnet` CLI and the `Individual Authentication` template.
1. Add support for successfully logging the user out of your app.
1. Enable logging as described in the Learn article section, [Logging in Blazor WebAssembly apps](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-7.0#logging-in-blazor-webassembly-apps).
1. In _Program.cs_, set the log level to "trace":

    ```csharp
    builder.Logging.SetMinimumLevel(LogLevel.Trace);
    ```
1. Enable debugging in Visual Studio Code as described in [Debug a standalone Blazor WebAssembly app](https://learn.microsoft.com/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio-code#debug-a-standalone-blazor-webassembly-app).
1. Run with debugging in Visual Studio Code.
1. Sign in to your app with a valid user account.
1. Sign out of your app.
1. View the log output in the **DEBUG CONSOLE** pane in Visual Studio Code (you might need to select **Debug Blazor WebAssembly in Browser** by using the drop-down).

In the log output, you'll see output similar to the following showing the logout operation being logged as a log**in** operation (the `Login completed successfully.` line).

```bash
dbug: Microsoft.AspNetCore.Components.Routing.Router[2]
      Navigating to component MyAwesomeBlazorWASMApp.Pages.Authentication in response to path 'authentication/logout' with base URI 'https://localhost:7007/'
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 4 of type Microsoft.AspNetCore.Components.Authorization.AuthorizeRouteView
# ...several render events omitted for brevity...
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 8 of type MyAwesomeBlazorWASMApp.Shared.MainLayout
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[10]
      Login completed successfully.
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[12]
      Raising LogoutCompleted event.
```

### .NET Version

8.0.100-alpha.1.22531.1

### Anything else?

~I'll submit a PR with the fix shortly.~ 🙂 

Draft PR building now: #45847

**Comment by javiercn** [comment]
@mmacy thanks for contacting us.

Yes. This indeed looks like a bug. We'll gladly take the PR with your fix.

**Comment by mmacy** [comment]
> @mmacy thanks for contacting us.
> 
> Yes. This indeed looks like a bug. We'll gladly take the PR with your fix. Thanks for the contribution.

Thanks, @javiercn - PR is ready to go:

#45847
