### ISSUE TITLE
Add tag trough OutputCacheAttribute

### ISSUE THREAD

**Issue by kellberg** [dotnet/aspnetcore#45842]
**NOTE**: Commandeering @kellberg's original issue to turn it into an API proposal since folks are already engaged here.

## Background and Motivation

Output Caching can be controlled via various APIs including via policy setup in DI, extension methods on the endpoint builder, and attributes on MVC actions and endpoint handler delegates. Cache entries can also be "tagged" which makes it possible to evict sets of cache entries. Unfortunately, the tagging mechanism is not exposed when configuring output caching via attributes.

The proposal is that we fix this short coming with the `[OutputCache]` attritribute by allowing the following usage:

```csharp
app.MapGet("/api/points-of-interest", [OutputCache(Tags = new [] { "geospatial" })]() => {});
```

## Proposed API

```diff
namespace Microsoft.AspNetCore.OutputCaching;

public sealed class OutputCacheAttribute : Attribute
{
+    public string[]? Tags { get; init; }
}
```

### Minimal APIs
```csharp
app.MapGet("/api/points-of-interest", [OutputCache(Tags = new [] { "geospatial" })]() => { ... });
```

### MVC
```csharp
[OutputCache(Tags = new [] { "geospatial" })]
public PointOfInterest[] GetPointsOfInterest() { }
```

## Alternative Designs

We already have multiple ways of setting output cache values, this just adds a missing one to the `[OutputCache(...)]` attribute. However I did consider whether we should use the singular `Tag` as the property, however other properties on the attribute are already pluralized.

## Risks

None that I can think of.

# Original issue content from OP.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to add an output cache tag for cache eviction but the OutputCacheAttribute doesn't have that option.

### Describe the solution you'd like

Add a Tag parameter to OutputCacheAttribute and update BuildPolicy to add the tag to the IOutputCachePolicy.

Then you can add the tag through the attribute:
[OutputCache(Tags = "test")]

**Comment by mitchdenny** [comment]
This sounds like a good idea for the sake of consistency.

**Comment by mitchdenny** [comment]
@captainsafia do you know if small changes like this need to use the formal API review template?

**Comment by captainsafia** [comment]
> @captainsafia do you know if small changes like this need to use the formal API review template?

@halter73 can provide the conclusive decision but I believe that adding a parameter to an existing API _does_ require API review.

**Comment by mitchdenny** [comment]
@halter73 missed your comment, I updated the initial issue content in this instance ;)

**Comment by halter73** [comment]
API Review Notes:

1. This follows a very similar pattern to other `string[]?` properties on the `OutputCacheAttribute`.
2. @sebastienros omitted this originally because tag data is often dynamic, but even in our samples, we sometimes use static sets of tags for a given endpoint.

API approved as proposed!

**Comment by mitchdenny** [comment]
Closing this issue now since the code has been added to main, it will appear in .NET 8.0.
