### ISSUE TITLE
Remove the Blazor survey link from the project templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#45854]
We currently include a survey link in the Blazor project templates which we use to get feedback from users on their getting started experience with Blazor. I think it's time to remove the SurveyPrompt component and instead use VS integration to collect this sort of feedback, similar to how VS handles its HaTS survey.

This has a couple of advantages:

- Less clutter in the Blazor templates
- Better control over when users are offered the survey link.

**Comment by TanayParikh** [comment]
Fairly simple change; but I kind of like how we have a component in `Index.razor` to showcase what's possible. Should we perhaps replace it with another sample component?

https://github.com/dotnet/aspnetcore/blob/97e26bd40c52d82afca150f65f1ee948336a18d3/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/Index.razor#L9

**Comment by SteveSandersonMS** [comment]
>  I kind of like how we have a component in Index.razor to showcase what's possible. Should we perhaps replace it with another sample component?

Interesting thought. The team discussed this and we decided just to remove it - we no longer thing the educational value of that component is warranted, now people can so easily find tutorials etc.
