### ISSUE TITLE
Reduce record usage in published aspnetcore projects

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45859]
records have a slim syntax and provide many features, but they also generate a lot of code. And much of that code can't be trimmed. A record can bloat app publish size.

See https://github.com/dotnet/aspnetcore/pull/45604#discussion_r1061055000 for an example.

- [x] Audit published aspnetcore projects for record usage. records in test projects is fine.
- [ ] See if there is an analyzer that we can enable to warn about record use, and enable.

**Comment by JamesNK** [comment]
@eerhardt Part of publish size effort.

**Comment by brunolins16** [comment]
Those are all place where `record` is used in our repo, not including tests and analyzers.

`MVC.Core`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Mvc/Mvc.Core/src/ModelBinding/Binders/CollectionModelBinder.cs#L405

`Kestrel`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/HttpUtilities.cs#L601
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Servers/Kestrel/shared/KnownHeaders.cs#L50
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.FeatureCollection.cs#L18

`Routing`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Http/Routing/src/Matching/DfaMatcherBuilder.cs#L943

`Components`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L258
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Components/WebView/WebView/src/Services/WebViewRenderer.cs#L79
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs#L118

`Http.Extensions`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/StaticRouteHandlerModel.cs#L17
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/StaticRouteHandlerModel.cs#L18
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/StaticRouteHandlerModel.cs#L19
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/StaticRouteHandlerModel.cs#L20

`Grpc`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Grpc/JsonTranscoding/src/Shared/ServiceDescriptorHelpers.cs#L447
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Grpc/JsonTranscoding/src/Shared/ServiceDescriptorHelpers.cs#L511

`Shared`
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Shared/BrowserTesting/src/BrowserManagerConfiguration.cs#L357
https://github.com/dotnet/aspnetcore/blob/493407b5a2783a7dbae18e43a04b6a5513a9ece5/src/Shared/BrowserTesting/src/PageInformation.cs#L119

**Comment by mitchdenny** [comment]
@eerhardt @captainsafia  where do you think this sits in terms of priority right now. I think the work is still valid, but perhaps a lower priority for now?

**Comment by eerhardt** [comment]
Yeah, it's pretty low on the priority list IMO. The only case that I would think is high priority is to ensure we don't ship any "new" public record types in .NET 8. If there are ones we added in 8, making them normal classes would be important.

**Comment by danmoseley** [comment]
would we take community changes for it - should it be 'help wanted' - or not a good candidate?

**Comment by captainsafia** [comment]
Agree that this is a good candidate for help wanted!

I've gone ahead and updated @brunolins16's comment to reflect the the fact that records were removed from RDG so the listi s more accurate for contributors.

**Comment by david-acker** [comment]
Here are some other `record` types that I found in the project (excluding those in analyzer, test, and tools code):

`Microsoft.AspNetCore.Components`

https://github.com/dotnet/aspnetcore/blob/e1f66845c0c65b7ed8413cf75656762dd2698f40/src/Components/Components/src/ComponentFactory.cs#L123-L125

https://github.com/dotnet/aspnetcore/blob/e1f66845c0c65b7ed8413cf75656762dd2698f40/src/Components/Endpoints/src/Binding/Factories/ComplexType/ComplexTypeExpressionConverterFactoryOfT.cs#L159-L164

https://github.com/dotnet/aspnetcore/blob/e1f66845c0c65b7ed8413cf75656762dd2698f40/src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Streaming.cs#L248-L248

https://github.com/dotnet/aspnetcore/blob/e1f66845c0c65b7ed8413cf75656762dd2698f40/src/Components/Web/src/Forms/ExpressionFormatting/ExpressionFormatter.cs#L266

https://github.com/dotnet/aspnetcore/blob/e1f66845c0c65b7ed8413cf75656762dd2698f40/src/Components/WebAssembly/Server/src/TargetPickerUi.cs#L428-L436
