### ISSUE TITLE
[AOT] ProblemDetails and Extension values

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45862]
Problem Details is an internet standard - https://www.rfc-editor.org/rfc/rfc7807

In ASP.NET Core, `ProblemDetails` is serialized with `IProblemDetailsWriter`. The default implementation is `DefaultProblemDetailsWriter`.

One of the concepts of problem details is [extension data](https://www.rfc-editor.org/rfc/rfc7807#section-3.2). These are arbitrary values that can be added to the payload. This is difficult with AOT because it's represented on `ProblemsDetails` as `IDictionary<string, object>`. Serializing problem details successfully (don't worry about deserializing, aspnetcore doesn't do that) means all the values in the directory must have generated code registered with the serializer.

**Comment by JamesNK** [comment]
`ProblemDetails.Extensions` is annotated to warn that types set in it are serialized, and that there maybe problems with serializing because values aren't able to be statically analyzed.

If there are changes to remove `ProblemDetails.Extensions` warning, then make sure to remove suppressions that come from using it. Right now, that is `DeveloperExceptionPageMiddlewareImpl`.

**Comment by halter73** [comment]
Triage: We want to try to remove the annotations ProblemsDetails.Extensions possibly by flowing the user's JsonTypeInfo registrations when serializing ProblemDetails.

**Comment by brunolins16** [comment]
@JamesNK  I believe this issue was fixed by https://github.com/dotnet/aspnetcore/pull/45886 as https://github.com/dotnet/aspnetcore/pull/45906, right?

**Comment by JamesNK** [comment]
Yup
