### ISSUE TITLE
[AOT] Improve suppressions on RouteEndpointDataSource

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45863]
Doing API work in the Map* handlers to remove suppressions in the RouteEndpointDataSource.

**Comment by halter73** [comment]
Triage: We want to make sure that filtering a `RequestDelegate` works so `AddFilter` doesn't need to require dynamic/unreferenced code.

**Comment by captainsafia** [comment]
Triage: Verify if this work has been completed by James' work and if anything needs to be done.

**Comment by captainsafia** [comment]
Synced with @JamesNK  and this can be closed.
