### ISSUE TITLE
Endpoint calling middlewares defined after IEndpointRouteBuilder.CreateApplicationBuilder() call

### ISSUE THREAD

**Issue by mhartkorn** [dotnet/aspnetcore#45868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to create an endpoint that terminates requests early without executing some middlewares because it's either causing unnecessary computations or requires handling of routing in these following middlewares by calling `next(context)` based on endpoint metadata.

For this I looked into the docs and the `Microsoft.AspNetCore.Diagnostics.HealthChecks` package, specifically `HealthCheckEndpointRouteBuilderExtensions.MapHealthChecks()`. When executing, I noticed that middlewares defined after the call to `MapHealthChecks()` are also being executed.

I attached a small demo below. All requests should get a string response (`"Reached endpoint middleware"`), instead they throw a exception in the `DoNotRunMiddleware`. The same is also happening with the Healthcheck library.

### Expected Behavior

Don't call middlewares defined after a call to `MapHealthChecks()` or any other code that uses the `IEndpointRouteBuilder.CreateApplicationBuilder()` API.

### Steps To Reproduce

Execute the following ASP.NET Core file. I chose a custom middleware to make it as small as possible and to highlight it's not just a bug in `MapHealthChecks()`. All requests are caught by the endpoint.

```csharp
var app = WebApplication.CreateBuilder(args).Build();

app.MapDemoEndpoint("/{**catchAll}");

app.UseMiddleware<DoNotRunMiddleware>();
app.Run();

public static class Ext
{
    public static IEndpointConventionBuilder MapDemoEndpoint(this IEndpointRouteBuilder app, string pattern)
    {
        var requestDelegate = app.CreateApplicationBuilder().UseMiddleware<DemoEndpointMiddleware>().Build();
        return app.Map(pattern, requestDelegate);
    }
}

public class DemoEndpointMiddleware
{
    public DemoEndpointMiddleware(RequestDelegate _) { }
    public async Task InvokeAsync(HttpContext ctx) => await ctx.Response.WriteAsync("Reached endpoint middleware");
}

public class DoNotRunMiddleware
{
    public DoNotRunMiddleware(RequestDelegate _) { }
    public Task InvokeAsync(HttpContext ctx) => throw new InvalidOperationException("Should not run!");
}
```

### .NET Version

7.0.101

**Comment by davidfowl** [comment]
Calls to Map are not ordered in relation to middleware. The selected endpoint by default will run at the end of the pipeline:

Route march -> Middleware -> Endpoint middleware

**Comment by mhartkorn** [comment]
Thank you both for the explanations. I will then will call `.WithMetadata()` von all `Map*` methods and short-circuit all my middlewares.

If others have this problem, here is my current solution using endpoint metadata:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks();
var app = builder.Build();
app.UseRouting();
app.MapHealthChecks("/health").WithMetadata(new ShortCircuitRoutingMarker());

app.UseMiddleware<DoNotRunMiddleware>();

app.UseEndpoints(_ => { });
app.Run();

public static class Ext
{
    public static IEndpointConventionBuilder MapDemoEndpoint(this IEndpointRouteBuilder app, string pattern)
    {
        var requestDelegate = app.CreateApplicationBuilder()
            .UseMiddleware<DemoEndpointMiddleware>()
            .Build();
        return app.Map(pattern, requestDelegate);
    }
}

public class DemoEndpointMiddleware
{
    public DemoEndpointMiddleware(RequestDelegate _) { }
    public async Task InvokeAsync(HttpContext ctx) => await ctx.Response.WriteAsync("Reached endpoint middleware");
}

public class DoNotRunMiddleware
{
    private readonly RequestDelegate _next;
    public DoNotRunMiddleware(RequestDelegate next)
    {
        _next = next;
    }
    
    public Task InvokeAsync(HttpContext ctx)
    {
        if (ctx.GetEndpoint()?.Metadata.GetMetadata<ShortCircuitRoutingMarker>() is not null)
        {
            return _next(ctx);
        }
        
        throw new InvalidOperationException("Should not run!");
    }
}

public class ShortCircuitRoutingMarker
{
}
```
