### ISSUE TITLE
IsTfaEnabled

### ISSUE THREAD

**Issue by cheng93** [dotnet/aspnetcore#45874]
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L765

Any reason why this is private? Could it be made protected?

Use case is I want to override methods that calls it, however as it's private, I have no access

**Comment by captainsafia** [comment]
Triage: It looks like the link that you pasted might be incorrect. Can you clarify what property/method you are wanting to make `protected` and why?

I assume that you are referring to https://source.dot.net/#Microsoft.AspNetCore.Identity/SignInManager.cs,744.

If so, a PR is welcome.

**Comment by cheng93** [comment]
## Summary

Change accessibility of `IsTfaEnabled` in SignInManager

## Motivation and goals

`IsTfaEnabled` to be public

## In scope

* Overriding methods that depend on `IsTfaEnabled` will not be able to call it due to it being private, such as `TwoFactorAuthenticatorSignInAsync`
* May want to check explicitly where `IsTfaEnabled` for a user in a controller/service

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

```csharp
// overriding
public override async Task<SignInResult> TwoFactorAuthenticatorSignInAsync(string code, bool isPersistent, bool rememberClient)
{
    var user = GetUser()
    if (IsTfaEnabled(user)) // here it is called
    {
    }  
}
```

```csharp
// publicly used
public async Task<IActionResult> OnGet()
{
    var user = GetUser();
    if (!await signInManager.IsTfaEnabled(user))
    {
        return RedirectToSetupTwoFactor()
    }
}
```

**Comment by HaoK** [comment]
So if we are going to make this public, it probably should be a spelled out i.e. `IsTwoFactorEnabledAsync(TUser)`

**Comment by cheng93** [comment]
I can submit PR if given the green light :)

**Comment by HaoK** [comment]
Sure submit a PR and I'll review it

**Comment by captainsafia** [comment]
I updated the [API issue comment](https://github.com/dotnet/aspnetcore/issues/45874#issuecomment-1381548108) and added the label so we can review this while the PR comes in.

**Comment by halter73** [comment]
API Review Notes:

- Could this API be protected instead of public? Public usage is demonstrated in the example, so it looks like yes.
- Does this support more than two factors? Should it be called `IsMultiFactorEnabledAsync`? No. `TwoFactor` is already used in other APIs, so let's stick with that.

API Approved!

```diff
namespace Microsoft.AspNetCore.Identity;

public class SignInManager<TUser> where TUser : class
{
-     private async Task<bool> IsTfaEnabled(TUser user) {}
+     public virtual async Task<bool> IsTwoFactorEnabled(TUser user) {}
}
```
