### ISSUE TITLE
In Dot Net 6 Getting this error in log file - The response headers cannot be modified because the response has already started.

### ISSUE THREAD

**Issue by ssplyuvrajsingh** [dotnet/aspnetcore#45889]
![image_2023_01_05T05_39_26_693Z](https://user-images.githubusercontent.com/58556669/210711607-a1965847-8988-4fca-937b-cb6ef8c37f9b.png)
![image_2023_01_05T05_40_03_153Z](https://user-images.githubusercontent.com/58556669/210711625-bd8bb0f4-c992-430c-80f7-23821c3efb9d.png)

In the dot net 6, When I execute this function all works fine without throwing in exception but I get an error log saying - "The response headers cannot be modified because the response has already started."

**Comment by adityamandaleeka** [comment]
@ssplyuvrajsingh Can you check the call stack for this exception? That might provide some clue as to when/why it's happening.
