### ISSUE TITLE
[Blazor] Added list item gets nested elements from other list item

### ISSUE THREAD

**Issue by MS699** [dotnet/aspnetcore#45919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Situation
I have a nested list of different objects (e.g. Customer > Order > Item) and show them in a self made treeview. This treeview is made by using list items (with the name for the object (Customer/Order/Item) and add/edit/delete buttons), which also contains a nested list with the component of the child list (e.g. CustomerList has OrderList as nested list component). All the levels of the tree have the same razor layout, I used the CustomerList as a example below. I used Mudblazor components.

**CustomerList.razor**
```
@foreach (var customer in Customers.OrderBy(c => c.Name))
{
  <MudListItem Text="@customer.Name">
	  <ChildContent>
		  <div class="d-flex flex-row">
			  <MudText Class="flex-grow-1">@customer.Name</MudText>
			  <MudIconButton Icon="@Icons.Material.Filled.Add" Size="Size.Small" Color="Color.Primary" OnClick="@(() => Add(customer))" />
			  <MudIconButton Icon="@Icons.Material.Filled.Edit" Size="Size.Small" Color="Color.Info" OnClick="@(() => Edit(customer))" />
			  <MudIconButton Icon="@Icons.Material.Filled.Delete" Size="Size.Small" Color="Color.Error" OnClick="@(() => Delete(customer))" />
		  </div>
	  </ChildContent>
	  <NestedList>
		  <CascadingValue Value="@customer" IsFixed="true">
			  <OrderList />
		  </CascadingValue>
	  </NestedList>
  </MudListItem>
}
```

**CustomerList.razor.cs**
```
public List<CustomerModel> Customers { get; set; }

private async Task Add()
{
  // add dialog
  var result = await dialog.Result;
  
  // check if result valid
  Customers.Add(result.customer);
}

private async Task AddOrder()
{
  // add dialog
  var result = await dialog.Result;
  
  // check if result valid
  Customers.Orders.Add(result.order);
}
```

The Customer/Order/Item lists are all ordered by Name, so when I add a second Order it can come before the first Order in the list. 

### Issue
When I have an Order with nested Items, and then I add a second order, which comes first alphabetically and thus also first in the list, this second Order is added with the same Items as the first order. Only after refreshing the page the Order is correctly displayed without any Items. If I then delete the second Order (without Items, first in the list), the first one is then displayed back in first place, but now it doesn't display the Items it has. Somehow it seems that when I add or delete Orders, and the Orders are switching place on screen, they receive the Items of the Order that was in that place before.

The expanded property also seems to be transferred. When an Order is expanded and I add an item right above it (and thus it will take the screen place of this Order) it is also expanded, while the first Order is not expanded anymore.

When adding/deleting Customers this is not an issue, only when adding/deleting Orders.

### Tried solutions
I already tried to use StateHasChanged() in the CustomerList.razor.cs when adding the Order.
I also tried to give the OrderList another CascadingValue with a notifier, and then call StateHasChanged() in OrderList when an Order is added: 

**OrderList.razor.cs**
```
[CascadingParameter]
public ChangedNotifier ChangedNotifier { get; set; }

protected override void OnInitialized()
{
	ChangedNotifier.Changed += Changed;
}

public void Changed()
{
	StateHasChanged();
}

public void Dispose()
{
	ChangedNotifier.Changed -= Changed;
}
```

### Expected Behavior

When I add a new Order I expect it to not have nested Items displayed, and when I delete an Order I expect it to still have all of its Items displayed.

### .NET Version

.NET 7.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Try to add `@key=customer` directive to the MudListItem declaration and see if that helps:

```razor
@foreach (var customer in Customers.OrderBy(c => c.Name))
{
  <MudListItem Text="@customer.Name" @key=customer>
```

**Comment by MS699** [comment]
Thank you @mkArtakMSFT, adding the @key in the OrderList did the trick, it works now as expected!
