### ISSUE TITLE
IAsyncEnumerable buffer the results and not yield it as stream. 

### ISSUE THREAD

**Issue by aristotelis79** [dotnet/aspnetcore#45916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In this demo value controller the browser buffer and return all the result at 5sec and not every 500ms.

`[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{
    [HttpGet]
    public IAsyncEnumerable<int> Get()
    {
        return FetchItems();
    }
    static async IAsyncEnumerable<int> FetchItems()
    {
        for (int i = 1; i <= 10; i++)
        {
            await Task.Delay(500);
            yield return i;
        }
    }
}`

### Expected Behavior

Expected to get one integer every 500ms and not all at the end of 5sec as doing on .net 6

### Steps To Reproduce

New WebApi project and add the above Get endpoint to test it

### .NET Version

.net 7.0

### Anything else?

ASP.NET Core version: .net 7.0

**Comment by brunolins16** [comment]
@aristotelis79 I believe it is related to https://github.com/dotnet/sdk/pull/29152. Can you please confirm if the issue does not reproduce when `dotnet run`?

**Comment by aristotelis79** [comment]
Hi @brunolins16,
You are right. The bug has to be with the visual studio. I try it with dotnet run and I can't reproduce it.
