### ISSUE TITLE
net7.0 101 file upload crashes stackoverflow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#45928]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net70-101-file-upload-crashes-stackover/10243448)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.5]
after update net7.0 to net 7.0 101 i had crash if using file upload component in blazor, after i'm delete net7.0 101 after all works good

---
#### Feedback Bot on 1/3/2023, 06:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Nick-Stanton** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem. Does it matter what type of file you select?
