### ISSUE TITLE
[Blazor] PersistentComponentState with Newtonsoft JSON

### ISSUE THREAD

**Issue by TehGM** [dotnet/aspnetcore#45925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I use Newtonsoft JSON for my APIs, and the attributes allow me to greatly and easily customize the response model. However `PersistentComponentState` uses System.Text.Json for state serialization. These libraries often differ in behaviour.

While property names usually don't matter for prerendering, these differences can often lead to issues that need to be worked around by duplicating constructors and/or custom serializers in order to address the differences.

I came across when trying to support prerendering of a class like this:
```csharp
public ICollection<string> Foos { get; }

public FoosContainer(IEnumerable<string> foos)
{
    Foos = foos?.ToList();
}
```

JSON.NET (and web API) is absolutely happy with it, but when I try to read pre-rendered state, Blazor code throws an exception due to mismatch of parameter types.

This example is of course simplified - real world scenarios tend to get more complex than this. A separate constructor could be used in this case, but in more complex scenarios this can quickly become daunting. And this of course doesn't even tackle the potential issues with custom JSON Converters.

### Describe the solution you'd like

I imagine this could be solved by making the members of `PersistentComponentState` virtual.

Or an even better scenario - calls to serialize and deserialize the object could be moved to their own methods that are virtual. For example, a call (as of .NET 7):
```csharp
_currentState.Add(key, JsonSerializer.SerializeToUtf8Bytes(instance, JsonSerializerOptionsProvider.Options));
```
Could become something along the lines of:
```csharp
_currentState.Add(key, SerializeInstance(instance));

protected virtual byte[] SerializeInstance(object instance)
    => JsonSerializer.SerializeToUtf8Bytes(instance, JsonSerializerOptionsProvider.Options);
```

And similar equivalent could be done for deserializing.

This way, if the application requires any kind of custom serialization, or simply wants to have behaviour consistent with JSON.NET, would just need to create a class inheriting from `PersistentComponentState` and override the virtual methods.

**Comment by javiercn** [comment]
@TehGM thanks for contacting us.

We were originally going to add support for this, but we ran out of time on 6.0. We might bring this back, in a future version if we receive enough feedback about it.

Since you are serializing your types, would it work if you write a JsonConverter for `System.Text.Json` and inside it you use `Newtonsoft.Json` to serialize and deserialize the instance?

**Comment by TehGM** [comment]
> @TehGM thanks for contacting us.
> 
> We were originally going to add support for this, but we ran out of time on 6.0. We might bring this back, in a future version if we receive enough feedback about it.
> 
> Since you are serializing your types, would it work if you write a JsonConverter for `System.Text.Json` and inside it you use `Newtonsoft.Json` to serialize and deserialize the instance?

Hey @javiercn 
I gave your suggestion a quick shot:
```csharp
public class GuideInfoJsonConverter : System.Text.Json.Serialization.JsonConverter<GuideInfo>
{
    public override GuideInfo Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using JsonDocument jsonDocument = JsonDocument.ParseValue(ref reader);
        string json = jsonDocument.RootElement.GetRawText();
        JToken token = JToken.Parse(json);
        return token.ToObject<GuideInfo>();
    }

    public override void Write(Utf8JsonWriter writer, GuideInfo value, JsonSerializerOptions options)
    {
        writer.WriteRawValue(JsonConvert.SerializeObject(value, Formatting.None));
    }
}
```

It appears to work, but it's definitely not ideal. I am no STJ expert, but at glance it seems like I'd need to do it for each type. It's also an additional hoop to take.

As a workaround, it is an idea and I might use it later in more extreme cases - but I don't think it's a great end solution.

**Comment by javiercn** [comment]
@TehGM thanks for the additional details.

You could write a generic base class for this, couldn't you? Or even better (I am not sure if it's possible) a generic attribute that you can just stamp in your types. You would only need to do this for the top-level types you want to serialize with newtonsoft.json

**Comment by danroth27** [comment]
We're going to track this as part of #45574. Closing this one as a duplicate.
