### ISSUE TITLE
Route Matching mismatching

### ISSUE THREAD

**Issue by Beth-F-C** [dotnet/aspnetcore#45922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Receiving 405 when expecting 404's when route matching occurs. Only defined pattern is a single route with a complex segment.

Using a basic ASP.NET Core Web Api (use visual studios out of the box "Weather Forecast") and change the controllers route to `foo` and the only endpoint to be a GET with a template of `{id}:bar`

Ergo there is only one endpoint defined within the whole project: `POST /foo/{id}:bar`

Now, when I run the above api locally and use Postman to hit it with different requests varying only the verb and route I get the returned status';

|       | /foo/123:bar  | /foo/literal  |
| ------| --------      | ------------  |
| GET   | 405 (expected)| 405 (why?)    |
| POST  | 200 (expected)| 404 (expected)|
| DELETE| 405 (expected)| 405 (why?)    |

### Expected Behavior

I expected all verbs for /foo/literal to return a 404 because the only route that can be matched is one that has two segments: `foo` and `{id}:bar` and the latter segment is a complex segment with a parameter part followed by a literal part. Said literal part is not suffixed to this route, ergo, it should not be a match and surely 404's should be returned?

### Steps To Reproduce

1. Create a new project in visual studio and select the C# template "ASP.NET Core Web API"
2.  Change the controller file in two places:
    - controller to have route `foo`
    - the single http route attribute to: `[HttpPost("{id}:bar")]`
3. Use Postman (or equivilent) and hit the routes with the verbs in the below table:

|       | /foo/123:bar  | /foo/literal  |
| ------| --------      | ------------  |
| GET   | 405 (expected)| 405 (why?)    |
| POST  | 200 (expected)| 404 (expected)|
| DELETE| 405 (expected)| 405 (why?)    |

The "why?" indicates those that I think should be returning 404's.

Below is the only file I changed from the example project, it is the file "WeatherForecastController"
```
using Microsoft.AspNetCore.Mvc;

namespace SpikeExample.Controllers
{
    [ApiController]
    [Route("foo")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpPost("{id}:bar")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}
```

### .NET Version

7.0.100

Targetting .net6 also yields the same results BAR a 500 instead of a 200 for `PUT /foo/123:bar` but that is only because `System.DataOnly` is not implemented in .net6. So the same issue can be seen when switching the project from targeting .net7 back to .net6

**Comment by javiercn** [comment]
@Beth-F-C thanks for contacting us.

I believe this happens because we consider the `HttpMethod` before we evaluate the constraint and as a result, we produce a 405, since for us complex segments are just parameters with constraints.

I believe this is very much by design as we try to delay evaluating constraints as much as possible as they are expensive.

In this case, our `HttpMethodMatcherPolicy` sees the endpoint candidate and determines that it can't satisfy the methods but that there are other endpoints for other methods and that's why you see the 405
