### ISSUE TITLE
Dotnet runtime 6.0.12 not getting updated in Azure App Service

### ISSUE THREAD

**Issue by ZenwalkerD** [dotnet/aspnetcore#45923]
Hello All,

Not sure if this is the right place to place this issue.

But on my app service; i have configured the extension to have runtime 6.0.12 as shown:
![image](https://user-images.githubusercontent.com/869964/210798409-07927b8a-c183-4d5d-8179-e9bfb9a258fa.png)

However; after restarting/stopping-starting the appservice the dotnet runtime dont seem to get updated at all. In my application; csproj; targetframework is mentioned as net60.

After updating the extensions; the dotnet command does not list 6.0.12 at all as shown.
![image](https://user-images.githubusercontent.com/869964/210799146-a06833f9-bd29-4bce-a6df-dd8e775dea7d.png)

Thanks

**Comment by BrennanConroy** [comment]
The site extension doesn't install the runtime in a location that will show up when running `dotnet --info`. Instead it modifies your web.config file to point to a new runtime location so when your app runs it loads the runtime brought in by the site extension. To see what version it's using, you have to **look at the running apps loaded dlls**.

**Comment by adityamandaleeka** [comment]
Looks like this has been answered weeks ago; closing the issue.
