### ISSUE TITLE
UserName and Email in Identity core

### ISSUE THREAD

**Issue by codelovercc** [dotnet/aspnetcore#45938]
Thanks anyone who build and support this great project!
Why does username must be an email in Identity core default UI? UserName is user's name and it doesn't matter if it's a email or not. Since I don't want use the email as the UserName, I can't not log in with default Identity core UI.

I found this source code in `Microsoft.AspNetCore.Identity.SignInManager<TUser>.PasswordSignInAsync`

```C#
public virtual async Task<SignInResult> PasswordSignInAsync(
      string userName,
      string password,
      bool isPersistent,
      bool lockoutOnFailure)
    {
      TUser byNameAsync = await this.UserManager.FindByNameAsync(userName);
      return (object) byNameAsync == null ? SignInResult.Failed : await this.PasswordSignInAsync(byNameAsync, password, isPersistent, lockoutOnFailure);
    }
```

and about this line `TUser byNameAsync = await this.UserManager.FindByNameAsync(userName);` , I think it should call `await this.UserManager.FindByEmailAsync(userEmail)` because of the UI Login form shows a Email input tag. Other ways it should take normal UserName as login model, UserName can be any thing and it can be a email too.

**Comment by codelovercc** [comment]
Or it should be like this
```C#
public virtual async Task<SignInResult> PasswordSignInAsync(
      string userNameOrEmail,
      string password,
      bool isPersistent,
      bool lockoutOnFailure)
    {
      TUser byNameOrEmailAsync = IsEmail(userNameOrEmail) ? await this.UserManager.FindByEmailAsync(userNameOrEmail) : await this.UserManager.FindByNameAsync(userNameOrEmail);
      return (object) byNameOrEmail == null ? SignInResult.Failed : await this.PasswordSignInAsync(byNameOrEmail, password, isPersistent, lockoutOnFailure);
    }
```
Using FindByEmailAsync or FindByNameAsync to find a TUser.

**Comment by captainsafia** [comment]
Triage: The two are conflated for historical reasons. If you want the two to be separate, you'd have to produce a scaffold with username and email as separate fields.

> I found this source code in Microsoft.AspNetCore.Identity.SignInManager<TUser>.PasswordSignInAsync

To resolve this, you'd have to find the username by the email before invoking the `PasswordSignInAsync`. There's no API to do this currently.
