### ISSUE TITLE
Not able to asign a role to a newly created user (ASP.NET Identity)

### ISSUE THREAD

**Issue by taibu** [dotnet/aspnetcore#45941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On Creating a new user using Asp.NetCore Identity, I want to assign a role to the newly created user.  When i pass the user objec and role to _userManager.AddToRoleAsync(), it throws a System.NullReferenceException as shown.

![image](https://user-images.githubusercontent.com/30900557/211157928-f413313c-1244-4b63-ab57-2d7d6ed1bfbf.png)

Code sinipet

        public async Task<ActionResult<User>> PostUser(User user)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            SystemUser newuser = new SystemUser()
            {
                UserName = user.UserName,
                Email = user.Email,
                Approved = false
            };
            var result = await _userManager.CreateAsync(
               newuser,
                user.Password
            );

            if (!result.Succeeded)
            {
                return BadRequest(result.Errors);
            }
            else
            {
                var getrole = await _roleManager.FindByNameAsync("Admin");
                if (getrole != null)
                {
                    await _userManager.AddToRoleAsync(newuser, getrole.Name);
                }
                
            }
            

            user.Password = null;
            return CreatedAtAction("GetUser", new { username = user.UserName }, user);
        }

### Exceptions (if any)

System.NullReferenceException

### .NET Version

6.0

**Comment by mitchdenny** [comment]
Could you provide the full stack trace just so we can better understand what is going on here?

**Comment by captainsafia** [comment]
Triage: Following investigation, we probably want to add guards against the NRE here.
