### ISSUE TITLE
Duplicate SegmentWriteStream

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#45957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Copies exist in:

* OutputCaching - https://github.com/dotnet/aspnetcore/blob/cefc6ccf4b23ac9f07418cd10e374cf533276eee/src/Middleware/OutputCaching/src/Streams/SegmentWriteStream.cs
* ResponseCaching - https://github.com/dotnet/aspnetcore/blob/cefc6ccf4b23ac9f07418cd10e374cf533276eee/src/Middleware/ResponseCaching/src/Streams/SegmentWriteStream.cs

### Expected Behavior

One copy, in shared source.

**Comment by JamesNK** [comment]
Good external contribution and first issue.

Should wait until after https://github.com/dotnet/aspnetcore/pull/45954 is done to avoid conflicts.

**Comment by JamesNK** [comment]
Also, check if there is anything else that can be shared between the two projects.

**Comment by Hellevar** [comment]
Hi, @JamesNK !
I'd like to grab this work, but I'm wondering - how to properly de-duplicate such things? If I put into Shared folder and reference the same way as it's done for TaskToApm helper file - there still will be duplicated tests.
Is it expected that new 'shared' project will be created just for these two projects?

**Comment by JamesNK** [comment]
There is a project for shared tests at https://github.com/dotnet/aspnetcore/tree/main/src/Shared/test/Shared.Tests
