### ISSUE TITLE
Apreciation for the empty templates that are now offered for blzor

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [dotnet/aspnetcore#45955]
Thank you, Thank you Thank you.

For giving us empty blazor templates. I wish there was a way to do this in .net 6 LTS, because our company is still migrating just now to .net 6.

https://github.com/dotnet/aspnetcore/issues/32832

**Comment by javiercn** [comment]
@dhaanpaa-lab0 thanks for contacting us.

We are happy that you like the new templates. If you want to use them in .NET 6.0, we are not planning to provide anything outside of the box for it, however you might be able to create a .NET 7.0 empty template and change the TFM to .NET 6.0.

It is also possible to create your own version of the template using ours as a starting point, if this is something that you think will be valuable to you.
