### ISSUE TITLE
CSS Isolation tags mismatch

### ISSUE THREAD

**Issue by Luk164** [dotnet/aspnetcore#45958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My website layout has been broken and after some debugging I found that the tags generated for CSS isolation are mismatched, which is causing the CSS to not be applied. I have recreated the solution from scratch with identical code (verified by comparing the two directories via total commander) and the new solution works fine. This means that between two identical solutions, one compiles fine and one has some sort of bug in it.

P.S.: Reverting to older commit did not help either.

### Expected Behavior

Solution should compile fine and the CSS isolation should work as intended. Two solutions with identical code should not have any differences in compilation results.

### Steps To Reproduce

Here is the broken repo: https://github.com/Luk164/TOPIC-Resume Unfortunately I have not been able to replicate the issue with a smaller one.

Steps:
1. Clone the repo
2. Launch
3. See the broken UI and mismatched tags via developer tools

### .NET Version

7.0.101

### Anything else?

VS2022 17.4.3 (latest at the time of writing)
dotnet info output:
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us.

> I have recreated the solution from scratch with identical code (verified by comparing the two directories via total commander) and the new solution works fine. This means that between two identical solutions, one compiles fine and one has some sort of bug in it.

That doesn't really make sense to me. If your solutions were truly identical, they would produce the same output since the compiler would have no way to distinguish between them. There must be something that distinguishes them.

It's *possible* that there's some kind of transient issue with corrupted state in your `bin`/`obj` dirs, so you could try deleting those to clean up the project. However if that doesn't fix it, there has to be a source code difference. If you can track that down and find out what causes the unwanted output, we can certainly look into whether or not the behavior is expected. Hope that's OK!

**Comment by javiercn** [comment]
@Luk164 thanks for contacting us.

Can you clean the bin and obj folders and see if that resolves the issue?

**Comment by Luk164** [comment]
Sorry, too much work so I did not have time to play with the repository, will post as soon as I can.

**Comment by Luk164** [comment]
I have tried again and this time the bug also manifested in new solution. I have a feeling it has to do with a few inconsistent uses os _ and - characters, but I am not sure. Maybe focusing on why the mismatch happens in the first place would be more effective?

**Comment by SteveSandersonMS** [comment]
@Luk164 If you provide a minimal repro I'll be happy to take a look (note: the repro linked above is not minimal).

**Comment by Luk164** [comment]
> @Luk164 If you provide a minimal repro I'll be happy to take a look (note: the repro linked above is not minimal).

I will try to remove most of the stuff, will notify once I push the changes.
