### ISSUE TITLE
Electron will be disconnected frequently when using signlar

### ISSUE THREAD

**Issue by Cricle** [dotnet/aspnetcore#45990]
### Description

I use signalr in electron, hang up without operation for a long time, will be disconnected frequently.
![1673337595191](https://user-images.githubusercontent.com/26201412/211494193-b56d0800-ccd8-401d-953d-a46e82565819.png)

And the client is always in the foreground.

### Reproduction Steps

```javascript
 let connection = new signalR.HubConnectionBuilder()
    .withUrl(`${baseURL}/hubs/v1/variables`)
    .configureLogging(signalR.LogLevel.Information)
    .build()
  window.connection = connection

  async function start() {
    if (connection.state !== 'Disconnected') return
    try {
      await connection.start()
    } catch (err) {
      setTimeout(() => start(true), 5000)
    }
  }

  connection.onclose(async () => {
    await start()
  })
  await start()

```

### Expected behavior

Open continuously for a long time or after reconnection for a long time.

### Actual behavior

Disconnected frequently, and it will take him a long time to reconnect

### Configuration

|Quest|x|
|:-|:-:|
|Which version of .NET is the code running on?|6.0.400|
|What OS and version, and what distro if applicable?|win10|
|What is the architecture (x64, x86, ARM, ARM64)?|x64|
|Do you know whether it is specific to that configuration?|In below|
|If you're using Blazor, which web browser(s) do you see this issue in?|No|

```cmd
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
Chrome version
```cmd
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) cms2.0/2.0.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36
```

package.json
```json
"dependencies": {
    "@microsoft/signalr": "^6.0.6
  }
```

**Comment by BrennanConroy** [comment]
`{"type":7,"allowReconnect":true}` indicates that the server is gracefully closing the connection. You should look at what the server is doing to figure out why it's closing the connection.

**Comment by Cricle** [comment]
I don't think this is the problem of library
