### ISSUE TITLE
Cannot debug Chrome with Microsoft.AspNetCore.Components.WebAssembly.DevServer 7.0.2

### ISSUE THREAD

**Issue by soenneker** [dotnet/aspnetcore#45992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Updated .NET 7 Blazor WASM project to 7.0.2 and immediately started getting this error when trying to debug the project:

![image](https://user-images.githubusercontent.com/4441470/211598209-f437e546-d792-47f0-940e-9f241e0aa9cc.png)

The debugging session closes after that.

Reverting package Microsoft.AspNetCore.Components.WebAssembly.DevServer to 7.0.1 fixes it.

Environment:
Chrome 108.0.5359.125 (Official Build) (64-bit)
Visual Studio Enterprise 2022 17.5.0. Preview 2.0

If I just need to wait until VS is updated, I apologize for the early bug report.

**Comment by mkArtakMSFT** [comment]
This sounds like a regression. Looking at the history for the DevServer, there doesn't seem to be any changes except for dependency updates: https://github.com/dotnet/aspnetcore/commits/main/src/Components/WebAssembly/DevServer/src

@TanayParikh can you please look into this and see what may have caused this? Thanks!

/cc @thaystg, in case you have thoughts about what may have caused this in 7.0.2.

**Comment by thaystg** [comment]
This is the error message:
You must install or update .NET to run this application.

App: C:\Users\thays\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\7.0.2\tools\blazor-devserver.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '7.0.2' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  6.0.8 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  6.0.11 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  6.0.12 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  7.0.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  7.0.1 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=7.0.2&arch=x64&rid=win10-x64

C:\Program Files\dotnet\dotnet.exe (process 3792) exited with code -2147450730.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .


The Microsoft.AspNetCore.App 7.02 is not available yet, right?

**Comment by TanayParikh** [comment]
This may just be some funky behavior as we're currently in the process of releasing. I expect this to be automatically resolved in the next few hours.

**Comment by soenneker** [comment]
> The Microsoft.AspNetCore.App 7.02 is not available yet, right?

Correct. @thaystg How did you get this output you posted? Would be nice if this was part of what VS said in the error dialogue.

> This may just be some funky behavior as we're currently in the process of releasing. I expect this to be automatically resolved in the next few hours.

Sorry for the early bug report. 

Thanks all. Will close later today when resolved.

**Comment by thaystg** [comment]
I saw it in the console that is opened when I run the app:
![image](https://user-images.githubusercontent.com/4503299/211618188-1169d319-241f-45e8-af43-db2b82c383c9.png)

**Comment by soenneker** [comment]
This is all I see, granted it is VS Debug Console is wrapped in MS Terminal:

![image](https://user-images.githubusercontent.com/4441470/211618565-fbebbca2-5a06-45de-a1c0-426ce178e884.png)

Any options come to mind that I need to change? I appreciate your help

**Comment by soenneker** [comment]
Got it now. VS will close the console window as soon as the error occurs. However 'dotnet run' within the project directory it won't close and then this error will present itself. I have dual startup configured so was looking at the wrong project. Thanks @thaystg

**Comment by IDGC-ESC** [comment]
I am seeing the same results from console `dotnet run`, so I guess I'll check again later today to see if the issue auto-resolves itself, and will just revert to 7.0.1 in the meantime.

**Comment by soenneker** [comment]
Confirmed upgrading .NET SDK works. Thanks all
