### ISSUE TITLE
PasswordHasher CompatibilityMode IdentityV2 not working in .NET 6.0

### ISSUE THREAD

**Issue by AchimStuy** [dotnet/aspnetcore#45994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am migrating an Application from ASP.NET MVC to ASP.NET Core MVC, including Identity. I followed the steps required for migrating the database at https://learn.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/identity-differences.

Regarding the password hashes I did not implement my own `PasswordHasher` but set `PasswordHasherOptions.CompatibilyMode` to `IdentityV2`. This is working fine in .NET 5.0 but not in .NET 6.0.

### Expected Behavior

Log in with legacy ASP.NET passwords should work in .NET 6.0 with `PasswordHasherCompatibilityMode` set.

### Steps To Reproduce

* Create ASP.NET Identity project and create user.
* Create ASP.NET Core Identity project and create user.
* Copy password from ASP.NET database to ASP.NET Core database
* Set ASP.NET Core's PasswordHasherCompatibilityMode to IdentityV2
* Try to log in.

### .NET Version

6.0

### Anything else?

If required, I could setup a sample repo.

**Comment by blowdart** [comment]
A sample repo would be wonderful
