### ISSUE TITLE
No warning / error message when ASP.Net Core 7 containerized application used the wrong Kestrel endpoint cert password 

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The application, when deployed to k8s, silently fails readiness check and restarts without any warning / error message at all  and no exception is thrown when Kestrel configuration in appsettings uses the wrong password. Took a fxxking long time to figure out what was wrong!

### Expected Behavior

Emits `IHostApplicationLifetime` events when the TLS cert password is wrong.

### .NET Version

7.0.101

### Anything else?

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mitchdenny** [comment]
Based on your observations, is the process not outputting anything at all (you can use `kubectl logs` against the container to get this). I'm wondering whether the dotnet.exe process is crashing or whether k8s is killing it because the liveness/readiness check is failing (in that case you'd see that when you use `kubectl describe` on the pod).

**Comment by khteh** [comment]
(1) k8s restart the pod due to failed readiness check.
(2) No log to give any clue about what happens!

**Comment by mitchdenny** [comment]
Under Docker I am seeing output: An unhandled exception of type 'System.Security.Cryptography.CryptographicException' occurred in System.Private.CoreLib.dll: 'The certificate data cannot be read with the provided password, the password may be incorrect.'
Stack trace:
 >   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
 >   at System.Security.Cryptography.X509Certificates.OpenSslPkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts)
 >   at System.Security.Cryptography.X509Certificates.OpenSslPkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
 >   at System.Security.Cryptography.X509Certificates.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
 >   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
 >   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
 >   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
 >   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
 >   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<BindAsync>d__33.MoveNext()
 >   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__30`1.MoveNext()
 >   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
 >   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
 >   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
 >   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
 >   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
 >   at Program.<Main>$(String[] args)

To me it looks like k8s might be killing the pod before it even gets a chance to output the stack trace above. If that is the case you might want to adjust the readiness check to give the process a grace period for startup.

**Comment by khteh** [comment]
Adjusted to 60 seconds still no `Exception` from console log. Pod stuck in `CrashLoopBackOff` cycles. The only output I get is from `describe pod` wihtout any helpful reason:
```
  Warning  BackOff    3m33s (x5 over 4m9s)   kubelet            Back-off restarting failed container
```

**Comment by mitchdenny** [comment]
Can you add a few Console.WriteLine(...) prior to spinning up the ASP.NET web host followed by a pause to give kubectl time to capture it (if that is even needed)?

There could be too issues here - the first one which you have resolved (password being incorrect for cert) and another impacting console output from your apps.

**Comment by khteh** [comment]
There are log outputs. Just no log for that exception or any warning/error for that matter. Hosted service `StartupBackgroundService.ExecuteAsync` was the last log output observed before it is restarted by k8s.

**Comment by mitchdenny** [comment]
As a diagnostic, could you wrap ```app.RunAsync()``` in an exception handler and make sure the exception is being caught (and write it out via ```Console.WriteLine(...)``` before exiting?

**Comment by khteh** [comment]
Already did!

**Comment by mitchdenny** [comment]
... and the output went into the k8s logs or not?

**Comment by khteh** [comment]
There are log outputs. Just no log for that exception or any warning/error for that matter. Hosted service `StartupBackgroundService.ExecuteAsync` was the last log output observed before it is restarted by k8s.

**Comment by mitchdenny** [comment]
OK so if you have code that effectively looks like this:

```csharp
try
{
  app.RunAsync();
  Console.WriteLine("Exited cleanly!");
}
catch (Exception ex)
{
  Console.WriteLine("Exited with exception!");
  Console.WriteLine(ex);
}
```

... and it doesn't output anything from those Console.WriteLine(...) calls? This is smelling like some kind of environmental issue. Do you have any exotic logging infrastructure running?

**Comment by mitchdenny** [comment]
I've just spent some time trying to reproduce this in a local K8S cluster running on my machine and haven't had any luck. It would be great if you could provide a minimal reproduction of this issue in the form of a GitHub repo with an ASP.NET Core app and associated Dockerfile and Kubernetes deployment YAML that I could spin up to see the problem you are seeing.

I'm running Docker Desktop locally with K8S support turned on - when I spin up a container with a cert configured with an invalid password, this is what I see: 

```
PS C:\Code\Trash\WebApplication51\WebApplication51> kubectl logs wa51-deployment-7756779596-s25vv -n foo
Unhandled exception. System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   at System.Security.Cryptography.X509Certificates.OpenSslPkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts)
   at System.Security.Cryptography.X509Certificates.OpenSslPkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
   at System.Security.Cryptography.X509Certificates.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /src/WebApplication51/Program.cs:line 8
```

... which is what I would expect. If you can provide any more relevant details about your K8S environment that would be helpful also (e.g. self-hosted, cloud, K8S version etc).

**Comment by khteh** [comment]
```
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();
try
{
<snip>
    app.Run();
}
catch (Exception ex) when (ex.GetType().Name is not "StopTheHostException") // https://github.com/dotnet/runtime/issues/60600
{
    Log.Fatal($"Exception: {ex.Message}");
}
finally
{
    Log.Information("Shut down complete");
    Log.CloseAndFlush();
}
```

**Comment by mitchdenny** [comment]
Do you happen to have colored console output setup for Serilog?

**Comment by khteh** [comment]
```
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();
try
{
<snip>
    LoggerConfiguration logConfig = new LoggerConfiguration().ReadFrom.Configuration(builder.Configuration);
    logConfig.WriteTo.Console(LogEventLevel.Verbose, "{NewLine}{Timestamp:HH:mm:ss} [{Level}] ({CorrelationToken}) {Message}{NewLine}{Exception}");
    Log.Logger = logConfig.CreateLogger();
    app.Run();
}
catch (Exception ex) when (ex.GetType().Name is not "StopTheHostException") // https://github.com/dotnet/runtime/issues/60600
{
    Log.Fatal($"Exception: {ex.Message}");
}
finally
{
    Log.Information("Shut down complete");
    Log.CloseAndFlush();
}
```
appSettings.Development.json:
```
    "Serilog": {
        "Using": [
            "Serilog.Sinks.Console"
        ],
        "MinimumLevel": {
            "Default": "Debug",
            "Override": {
                "Microsoft": "Debug",
                "System": "Debug",
                "Grpc": "Debug",
                "Microsoft.Hosting.Lifetime": "Debug"
            }
        },
        "Enrich": [
            "FromLogContext",
            "WithMachineName",
            "WithThreadId"
        ],
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "Args": {
                        "outputTemplate": "{Timestamp} {Level} {EventId} {Message:j} {Properties}{NewLine}{Exception}{NewLine}"
                    },
                    "Enrich": [
                        "FromLogContext"
                    ],
                    "rollingInterval": "Day",
                    "retainedFileCountLimit": 3,
                    "formatter": "Serilog.Formatting.Elasticsearch.ElasticsearchJsonFormatter, Serilog.Formatting.Elasticsearch, Version=0.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10"
                }
            }
        ]
    }
```

**Comment by mitchdenny** [comment]
@khteh I have a sneaking suspicion that something in your Serilog setup may be an issue here. Try doing a new project with the same certificate configuration (invalid password) but don't include Serilog. If the repro works (produces the exception message in K8s logs) then you can probably speculate that something with the way that Serilog is interacting with stdout is contributing here (but I can't be sure since I don't know how Serilog is put together).

A bit of a shot in the dark - but try adding the tty: setting to your container spec in k8s (set it to true).

**Comment by khteh** [comment]
Not the log. I see:
```
02:52:25 [Information] () Starting app...
```
just before `app.Run();`

**Comment by mitchdenny** [comment]
At this point we are at a loss to figure out what is causing this and am unable to reproduce it. It would be good if you could come up with a repro for your scenario minus Serilog like I have mentioned above so that we can try and eliminate the potential causes for this problem.

We are trying to determine whether there is a fundamental issue here with ASP.NET Core and/or the .NET runtime, or whether this is an issue that is introduced through a third-party library such as Serilog or some other environmental factor specific to your environment (at which point you could follow up with those projects).
