### ISSUE TITLE
Question: Does Blazor Identity work inside an iframe?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a web application works perfectly well inside an iframe. Does blazor Identity work inside the same iframe if I were to redirect the Auth to it?

### .NET Version

7.0.101

**Comment by javiercn** [comment]
@khteh thanks for contacting us.

What flavor of Blazor are you using? In general, auth needs to happen in the top-level browsing context for security reasons.

**Comment by khteh** [comment]
Blazer server

**Comment by khteh** [comment]
Any update?

**Comment by HaoK** [comment]
Its not clear what you are asking specifically here @khteh
