### ISSUE TITLE
HTTP Error 500.31 is rather unhelpful 

### ISSUE THREAD

**Issue by Montago** [dotnet/aspnetcore#46021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been developing a .NET 6/7 WebAPI site and ran into a HTTP Error 500.31 error when hosting the site in IIS. 

more specifically IIS reports this error page: 

> **HTTP Error 500.31 - Failed to load ASP.NET Core runtime**
> Common solutions to this issue:
> The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.

The ACTUAL problem i had, was that the Web.Config was referencing an incorrect DLL :

> <aspNetCore processPath="dotnet" arguments="DLL-PATH">

the 500.31 error suggest that the framework installation on the host machine is to blame, which sends the developer out on the wrong direction of problem solving. 

### Expected Behavior

I would expect a better error message, that the Path of the DLL (the argument) is incorrect. 

It shouldn't be that hard for dotnet.exe to tell me that the argument is wrong. 

### Steps To Reproduce

- Spin up a new .NET 6 WebAPI site in Visual Studio 2022
- Add Web.Config: 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>

<location path="." inheritInChildApplications="false">
	<system.webServer>
		<handlers>
			<add name="aspNetCore"
				 path="*"
				 verb="*"
				 modules="AspNetCoreModuleV2"
				 resourceType="Unspecified" />
		</handlers>
		<aspNetCore processPath="dotnet"
					arguments=".\INCORRECT-NAME-OF-DLL.dll"
					stdoutLogEnabled="true"
					stdoutLogFile=".\logs\stdout"
					hostingModel="inprocess" />
	</system.webServer>
</location>
</configuration>
```

- Add new Site in IIS 
- Point to the /Bin/Debug/.NET6.0/ folder
- Start up the site 
- Access the /Swagger page 
- Be met with a HTTP 500.31 error 

### .NET Version

6 or 7

**Comment by BrennanConroy** [comment]
The error has improved to point you at the application name likely being wrong now.
