### ISSUE TITLE
Incorrect target framework for Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore

### ISSUE THREAD

**Issue by dozer75** [dotnet/aspnetcore#46030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently upgrading all of our NuGet packages to latest version including `Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore`.

While the package upgrade works for all packages, the `Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore` fails since it has target framework .NET 7 and we're committed to use target framework .NET 6 since it is LTS.

Is there any (good) reason why this package is .NET 7? This is the only package I have problems with, all other NuGet packages from dotnet, efcore and aspnetcore projects that is 7.x.x works since these targets .NET 6.

### Expected Behavior

Since none of the packages that `Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore` depends on requires .NET 7, so I have a hard time seeing that this package should require .NET 7, so it would be nice if the package has .NET 6 as target framework as well.

### Steps To Reproduce

1. Create a project with .NET 6 as target framework
2. Try to add 7.0.3 (or other 7.0.x) packages to the project

**Comment by Tratcher** [comment]
The 7.0 version of this package only targets .NET 7 and can only be used there. For .NET 6 use 6.0.13.

You should also be using the 6.0 version of all other nuget packages. Some may happen to install using a different target like netstandard, but none of the 7.0 packages are tested or supported for use with .NET 6.
