### ISSUE TITLE
Design proposal: Localization with multiple assemblies at the same time

### ISSUE THREAD

**Issue by KeyserDSoze** [dotnet/aspnetcore#46034]
Hi everyone,

now it's not possible to use the localization library to create resources in two libraries and install all of 2 in an application. One of those libraries always overrides the second one. If you have for example any resx in a razor library and some resx in your app, you have to choose which assembly should be correct to use. Furthermore, in my opinion, during the configuration of a service in dependency injection a change of position should not provide a change in app behavior, let me do an example.
I have this situation, an app with two extension methods that setup from two different assemblies the IStringLocalizer service.

![image](https://user-images.githubusercontent.com/40713438/211886011-f759c5cc-180e-43e9-b732-7a1986c91387.png)

Razor library

![image](https://user-images.githubusercontent.com/40713438/211886626-15fbe71f-d7ab-4946-a9e7-afd321fe2e41.png)

and App

![image](https://user-images.githubusercontent.com/40713438/211886840-7d9ff34d-2863-4c4e-93a5-3fd75a9c216a.png)

In index of the app

![image](https://user-images.githubusercontent.com/40713438/211889561-bafd150d-621d-407f-a4fc-ae8df98a72a7.png)

So, if I start the app I have only one string correctly translated.

![image](https://user-images.githubusercontent.com/40713438/211889772-51540de5-8a7a-4f67-adbf-9776d4deeaf7.png)

So, if I change the position between razor library and app extension method.

![image](https://user-images.githubusercontent.com/40713438/211890027-6467646b-ac1f-4398-8da7-d7047f02fd8a.png)

Now AddInAppLocalization comes before the AddLibraryLocalization, and I obtain a change in the output

![image](https://user-images.githubusercontent.com/40713438/211890233-22e5178d-3ba7-454c-b963-8b0834dffa83.png)

In my opinion a library in DI must respect the [https://en.wikipedia.org/wiki/Abelian_group](abelian group)  properties and changing in position doesn't have effect in output, otherwise could rise an error on startup.
You can find the whole code [https://github.com/KeyserDSoze/Study.Localization](here).

In this repository of mine I create a [https://github.com/KeyserDSoze/Study.Localization/tree/master/src/NewVersion/Localization.Multiple](library) that solves the issue and improve the usability of the Localization. Now it would be possibile to have multiple sources.

I'm already using my library in my projects to have the chance to use multiple sources. For instance, in a razor library from my [https://github.com/KeyserDSoze/RepositoryFramework/tree/master/src/RepositoryFramework.Web](repository framework library).

Therefore, do you think it's correct what I said and would be it useful to integrate the solution directly in the code of Localization?

**Comment by mitchdenny** [comment]
The behaviour around DI generally is by-design.

Regarding localization specifically, your extension methods are calling AddLocalization once each and specifying a path which is presumably different for each one. Why not consolidate the resource files into the same path. Presumably the resx files are targeting different classes?

**Comment by KeyserDSoze** [comment]
I can consolidate in one location but I don't think it's correct. For instance, I have a razor library with some standard razor components like a table, or something else and I would provide some localization resources for these components, if someone who's using this library would like to use his localization resources for other components from other sources or inside another his library he cannot do it now or he has to know the resources path that I configured. I think that every setup of localization has to have the chance to have a different configurable path. In this case all resources in all assemblies must have the same path. With my idea, during configuration, passing a class of the assembly we could set a path for each assembly and noone could destroy with another setup that setup.

![image](https://user-images.githubusercontent.com/40713438/212009955-631a8693-343b-4366-9d34-1fe5b0f6bd36.png)

**Comment by hishamco** [comment]
@KeyserDSoze could please let me know what the use case that allows you to look into two different paths?

**Comment by KeyserDSoze** [comment]
I could try to explain with an example. If I create a library with inside a localization, and someone uses this library and for any reason he has to setup another localization, now the second localization overrides the first one. In this scenario I never can create a library with internal default localization.

**Comment by hishamco** [comment]
So the issue with providing multiple paths or localization providers to make it clear

**Comment by hishamco** [comment]
Closing this because there's no respond from author, feel free to reopen if you have any update

**Comment by gumbarros** [comment]
> Closing this because there's no respond from author, feel free to reopen if you have any update

Please reconsider re-opening the issue, this is a huge deal for me.

Imagine the following scenario:

- You developed a RCL (Razor Class Library) with Views and Models to be re-utilized in many websites
- The `Display = Name `labels are stored in a specific assembly
- When you reference the RCL in a website, how do you tell ASP.NET to find the `Display = Name` labels of the RCL in the RCL assembly, and the `Display = Name` of the main site at the main assembly?

**Comment by hishamco** [comment]
@gumbarros please file a new issue describing the case, then ping me there I might help
