### ISSUE TITLE
[AOT] Clean up AOT warnings in the SPA Proxy project

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#46036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Split out from #45473 - #45604 suppressed AOT checking of the SPA Proxy project:

https://github.com/dotnet/aspnetcore/blob/f766c4a9bc1f2b6c8162953a4a910cefddde4c8e/src/Middleware/Spa/SpaProxy/src/Microsoft.AspNetCore.SpaProxy.csproj#L7

### Describe the solution you'd like

Enable AOT checking and address all warnings.

**Comment by javiercn** [comment]
@amcasey I'm not sure we need to do anything since this is a dev-only feature.

Spa proxy is a development only feature that is not used during deployment/aot. So, I do not think we need to do anything here? If there is a way we can configure this project to trim the reference as part of the app publishing, that would work great.

**Comment by mkArtakMSFT** [comment]
Closing based on @javiercn 's comment above as it seems there is no real value due to these warnings are specific only to dev-time enabled feature.

**Comment by amcasey** [comment]
@mkArtakMSFT I had a quick call with @javiercn about this and it sounded like there was still a bit of work.  I haven't checked it out yet, but it sounds like maybe this project is unnecessarily included as a runtime dependency and prevents some trimming that would otherwise happen.  Or possibly he just wanted to confirm that that wasn't the case.

**Comment by amcasey** [comment]
Okay, some notes from poking around:

- The user's code does not declare a dependency on `Microsoft.AspNetCore.SpaProxy` - it's pulled in using [`ASPNETCORE_HOSTINGSTARTUPASSEMBLIES`](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-7.0)
- The `IHostingStartup` for the proxy [does nothing](https://github.com/dotnet/aspnetcore/blob/9ffffa45789328985d43cc70a378fd8570988f27/src/Middleware/Spa/SpaProxy/src/SpaHostingStartup.cs) unless `spa.proxy.json` is present
- `spa.proxy.json` is [not published](https://github.com/dotnet/aspnetcore/blob/9ffffa45789328985d43cc70a378fd8570988f27/src/Middleware/Spa/SpaProxy/src/build/Microsoft.AspNetCore.SpaProxy.targets#L23)

So, (1) the SPA proxy won't be used by the published app and (2) it's not referenced in a way that should affect trimming.

As a hygiene improvement, we could refrain from publishing the DLL but, AFAICT, that would actually require deleting it after publishing (since there's no built-in facility for controlling the publication of nuget references) and putting that code in the template seems kind of ugly.

**Comment by amcasey** [comment]
If @javiercn agrees, I think we can just close this.

**Comment by amcasey** [comment]
Neat: https://github.com/dotnet/sdk/blob/77cb43cab0a8d7ce648c9ce3d9f191b2411a00ac/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Shared.targets#L58
