### ISSUE TITLE
Put the query parameters into RouteData.RouteValues

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#46047]
Current the querystring parsing logic is in `RouteView` and  pass directly to the render tree

https://github.com/dotnet/aspnetcore/blob/d194f5091ffa2ebd450845edf30721d623d848dd/src/Components/Components/src/RouteView.cs#L98-L112

I think it's better to parse them in the Router and pass it to RouteView via RouteData.

**Comment by javiercn** [comment]
@ElderJames that's by design.

Query parameters are not part of the route data. This is consistent with ASP.NET Core server-side routing and not something we want to change.

**Comment by ElderJames** [comment]
Thank you for explanation @javiercn . I'm working on a component `ReuseTabs` that need to reconstruct the content of the page component, I can pass RouteData to the child component through CascadingValue, but I cannot pass Query Parameter Values, resulting in the QueryParameters of the page not binding.

Do I have to copy a lot of the source code from this repo if I want to implement the QueryParameters binding?

**Comment by javiercn** [comment]
@ElderJames for the time being yes.

We decided to make that an internal implementation initially until we decide whether it is worth exposing it and in which way.
