### ISSUE TITLE
Browser is flooded with Correlation and Nonce cookies after logging into Azure.

### ISSUE THREAD

**Issue by mschaefer-gresham** [dotnet/aspnetcore#46053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using Microsoft.AspNetCore.Authentication.OpenIDConnect to authenticate against Azure. My frontend is a React SPA. I have no tokens in the browser. My backend returns a cookie to the SPA.

When the cookie expires the SPA is redirected to Azure B2C and the user is forced to login. This normally works fine. But occasionally after the user logs into Azure and is returned to the SPA, the SPA fails to load the callback path and I see this in the app's cookies:

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/94627216/212059415-318219a1-c535-4d5e-8e3c-5a1dbdfcefda.png">

I've configured the Session, Cookie, and DistributedCache timeouts to be the same:

```
builder.Services.AddSession(options =>
{
            options.IdleTimeout = TimeSpan.FromMinutes(cookieTimeoutInMin);
});
```
```
.AddCookie(setup =>
{
            setup.ExpireTimeSpan = TimeSpan.FromMinutes(cookieTimeoutInMin);
            setup.SlidingExpiration = true;
            setup.EventsType = typeof(GatewayCookieAuthenticationEvents);
)
```
```
builder.Services.AddDistributedSqlServerCache(options =>
 {
            options.ConnectionString = builder.Configuration.GetConnectionString("MyConnectionString");
            options.SchemaName = builder.Configuration["TokenCache:SchemaName"];
            options.TableName = builder.Configuration["TokenCache:TableName"];
            options.DefaultSlidingExpiration = TimeSpan.FromMinutes(cookieTimeoutInMin);
});
```
I'm also using the prompt=login query paramters on my authority endpoint.
```
options.Events.OnRedirectToIdentityProvider = (context) =>
{
                context.ProtocolMessage.SetParameter("prompt", "login");
                return Task.FromResult(0);
};
```

I don't know what causes this so I can't readily reproduce it. 

Can you please tell me what might be causing this? I would like to know how to prevent this and/or how to recover from it. Once this occurs the app can no longer be accessed unless all the cookies are deleted.

One thing to note is that the SPA uses React Query which has a retry feature. So once the cookie expires the front end keeps sending lots of requests to the backend until it gets redirected.

### Expected Behavior

Expected behavior is to not get all extra cookies.

### .NET Version

.net 7.0.100

**Comment by captainsafia** [comment]
Triage: This nonce cookies are populated every time a login invocation is issued. You might be seeing this because your application is stuck in a redirect loop when "So once the cookie expires the front end keeps sending lots of requests to the backend until it gets redirected." occurs.

You can find more information on this at https://github.com/dotnet/aspnetcore/issues/42740. This is expected behavior.

**Comment by mschaefer-gresham** [comment]
@captainsafia Thank you for this. I'm experiencing the following behavior which I can't figure out. When I log into Azure B2C for the first time everything work fine.  The login endpoint in the server performs the challenge and in the frontend I see that the authorize endpoint is called:

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/94627216/212338397-8069959c-f3ad-43c0-8785-0f3a5a608754.png">

However, if the cookie expires or if I pre-emptively sign the user out from the backend with something like this:

```
wait ctx.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
```

Then I get CORS errors for all the authorize redirects in the frontend:

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/94627216/212344193-53497173-9722-4c6e-aa05-daa20a594dce.png">

I tried what was mentioned in [issue 42740](https://github.com/dotnet/aspnetcore/issues/42740) but it didn't help. 

The only thing that kind of "worked" was to sign the user out from the back using the oidc policy (not the cookie policy). This resulted in 401 errors for the api calls in the frontend, but no redirect to Azure. I could then catch a 401 and navigate to my login endpoint in the server. There were no CORS issues here and the login process worked as expected. But the UI shouldn't be involved, this was just a test.

I saw many posts about solving this CORS issue, but I don't have this CORS issue on the initial login, just when the cookie expires or I pre-emptively sign the user out before the cookie expires. So I don't know if any of these even apply. 

[Use Platform SPA, not Web](https://stackoverflow.com/questions/59844516/how-to-enable-cors-in-an-azure-app-registration-when-used-in-an-oauth-authorizat)

[Proxy CORS issues](https://learn.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-understand-cors-issues)

[Adding CORS orgins to the server](https://github.com/AzureAD/microsoft-identity-web/issues/581)

[Enabling CORS origins in the Azure app](https://learn.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api#enable-cors) Is this the same as adding a Redirect URI?

I could really use some help on how to solve this issue. I'm just guessing at this point.

As mentioned, my server is issuing a cookie to the front end React SPA. There is no token in the browser, just the cookie. 

The server config looks like this:

```
`builder.Services.AddAuthentication(options` =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie(setup =>
        {
            setup.ExpireTimeSpan = TimeSpan.FromMinutes(60);
            setup.SlidingExpiration = true;
            setup.Cookie.MaxAge = setup.ExpireTimeSpan;
            setup.Cookie.SameSite = SameSiteMode.Strict;
            setup.EventsType = typeof(GatewayCookieAuthenticationEvents);
        })
        .AddOpenIdConnect(options =>
        {
            options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.Authority = config.Authority;
            options.ClientId = config.ClientId;
            options.UsePkce = true;
            options.ClientSecret = config.ClientSecret;
            options.ResponseType = OpenIdConnectResponseType.Code;
            options.SaveTokens = false;
            options.GetClaimsFromUserInfoEndpoint = config.QueryUserInfoEndpoint;
            options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;
            options.NonceCookie.SecurePolicy = CookieSecurePolicy.Always;
            options.RequireHttpsMetadata = false;
            options.CallbackPath = "/signin-oidc";
            options.SignedOutCallbackPath = "/signout-callback-oidc";
            // options.MaxAge = TimeSpan.FromSeconds(900);
            var scopes = config.Scopes;
            var scopeArray = scopes.Split(" ");
            foreach (var scope in scopeArray)
            {
                options.Scope.Add(scope);
            }
            options.Events.OnTokenValidated = (context) =>
            {
                var tokenHandler = context.HttpContext.RequestServices.GetRequiredService<TokenHandler>();
                tokenHandler.HandleToken(context);
                return Task.FromResult(0);
            };
            
            options.Events.OnRedirectToIdentityProvider = (context) =>
            {
                context.ProtocolMessage.SetParameter("prompt", "login");
                return Task.FromResult(0);
            };
            
            options.Events.OnRedirectToIdentityProviderForSignOut = (context) =>
            {
                context.ProtocolMessage.MaxAge = "0";
                LogoutHandler.HandleLogout(context, config);
                return Task.CompletedTask;
            };

builder.Services.AddCors(options =>
        {
            options.AddPolicy(name: "MyAllowSpecificOrigins",
                policy  =>
                {
                    policy.WithOrigins("https://localhost:8080",
                        "https://mycompany.b2clogin.com");
                });
        });

```

My Azure B2C app looks like this:

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/94627216/212341007-5aaac51a-6ae3-435e-b415-d9e4b13d10ad.png">
