### ISSUE TITLE
HttpContext property of HttpContextAccessor is null in the ClientCertificateValidation callback of HttpsConnectionAdapterOptions

### ISSUE THREAD

**Issue by abrasat** [dotnet/aspnetcore#46052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My application tries to get the HttpContext when the certificate validation fails in the Microsoft CertificateAuthenticationHandler. The HttpContext property of HttpContextAccessor is null when the ClientCertificateValidation callback is triggered

### Expected Behavior

The HttpContext property of HttpContextAccessor is set when the ClientCertificateValidation callback is triggered

### Steps To Reproduce

The wrapper class to access the HttpContextAccessor from the ClientCertificateValidation callback
```
public interface IHttpContextWrapper
{
    HttpContext GetHttpContext();
}

public class HttpContextWrapper: IHttpContextWrapper
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public HttpContextWrapper(IHttpContextAccessor httpContextAccessor, ILoggerFactory LoggerFactory)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    public HttpContext GetHttpContext()
    {
        return httpContextAccessor.HttpContext;
    }
}
```

The class registration at startup:
```
...
// Add services to the container
services.AddHttpContextAccessor();
services.AddSingleton<IHttpContextWrapper, HttpContextWrapper>();
...
```

The ClientCertificateValidation callback of HttpsConnectionAdapterOptions (the HttpContextWrapper gets the HttpContextAccessor correctly, but the HttpContext property is null)
```
...
webBuilder.UseKestrel(o =>
{
    o.Listen(IPAddress.Parse(hostSettings.HttpsEndPoint.IpAddr), hostSettings.HttpsEndPoint.Port,
        listenOptions =>
        {
	    HttpsConnectionAdapterOptions httpsConnectionAdapterOptions = new HttpsConnectionAdapterOptions()
            {
                ClientCertificateMode = ClientCertificateMode.RequireCertificate,
                SslProtocols = System.Security.Authentication.SslProtocols.None,
                ServerCertificate = rootCert,
                ClientCertificateValidation = (x509Cert, x509Chain, sslErrors) =>
                {
                    var ret = true;

                    if (sslErrors == SslPolicyErrors.None)
                    {
                        ret = true;
                    }
                    else
                    {
		        ...
                        var httpContext = webApp.Services.GetRequiredService<IHttpContextWrapper>().GetHttpContext();
                        // httpContext is null here !
                        ...
                    }
                    return ret;
                }
            };
            listenOptions.UseHttps(httpsConnectionAdapterOptions);
        });
    o.Listen(IPAddress.Parse(hostSettings.HttpEndPoint.IpAddr), hostSettings.HttpEndPoint.Port);
});
...
```

### .NET Version

7.0.102

**Comment by Tratcher** [comment]
When using RequireCertificate the client certificate is received at the start of the connection before any HTTP requests, it's not possible to get an HttpContext. What did you want from the context?

**Comment by abrasat** [comment]
@Tratcher   Actually I need to generate raise an event on application level that a client certificate validation failed and why, together with the information about which endpoint was called. I needed the HttpContext to extract the information (the HttpRequestPath, the ConnectionInfo etc) about which rest api call failed because of the client certificate validation error. From the x509Chain I extract the details about why the certificate validation failed (UntrustedRoot, expired certificate etc). So basically I need to be able to put together the information described above.
Another possibility would be to add some code in the OnAuthenticationFailed event triggered by the certificate authentication handler. The HttpContext is available in the event, but unfortunately there is no way to get here the information about why the client certificate validation has failed....
```
builder.Services.AddAuthentication(
        CertificateAuthenticationDefaults.AuthenticationScheme)
    .AddCertificate(options =>
    {
        options.Events = new CertificateAuthenticationEvents
        {
            OnAuthenticationFailed = context =>
            {
....
```

**Comment by Tratcher** [comment]
What you're asking for isn't possible with the HTTPS/TLS protocol and RequireCertificate. The TLS handshake only tells you the host name (SNI) that the client is trying to connect to. The client does not send the HTTP request (path, query, headers, etc.) until after he TLS handshake. 

You _might_ be able to make this work with DelayCertificate, but that mode should be avoided for many other reasons.

Another way you can try is with the `UseHttps(this ListenOptions listenOptions, TlsHandshakeCallbackOptions callbackOptions)` overload. It gives you a more detailed callback, including the ConnectionContext.Features where you could stash error details for later retrieval by OnAuthenticationFailed (from HttpContext.Features).

**Comment by abrasat** [comment]
Thanks for the reply. Is there any code sample available about using TlsHandshakeCallbackOptions?
The official documentation page does not contain any code samples:
[TlsHandshakeCallbackOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.https.tlshandshakecallbackoptions?view=aspnetcore-7.0)

**Comment by Tratcher** [comment]
Here's a basic one:
https://github.com/dotnet/aspnetcore/blob/ce05ffddcbbbaf58714d9ad949b706f618073a4c/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs#L632-L639
