### ISSUE TITLE
[Blazor] Allow component resx files to be named razor.resx to allow nesting

### ISSUE THREAD

**Issue by paulguz-datapa** [dotnet/aspnetcore#46051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Blazor component-specific resx files are named Component.resx.  This is not in keeping with component-specific CS, JS and CSS files, which are named Component.razor.*, therefore the resx file is not nested accordingly.

Have Visual Studio nest the razor.resx file under the razor component as it does with CS, JS and CSS (currently Visual Studio would nest a file named razor.resx under the razor.cs file!)

**Comment by javiercn** [comment]
@paulguz-datapa thanks for contacting us.

You can already customize how file nesting works in Visual Studio. Check the following doc [here](https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022) for reference.

**Comment by paulguz-datapa** [comment]
@msftbot This issue is not resolved.  It is an open feature request.  It is not resolved simply because someone responded to it once!

**Comment by javiercn** [comment]
@paulguz-datapa thanks for the additional details.

This forum is for runtime/framework issues only. If you want to make a feature request for Visual Studio, please do so via the suggest a feature dialog [here](https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022) as that will make sure that the right teams get to see it and prioritize it accordingly.

**Comment by paulguz-datapa** [comment]
@javiercn This is a feature request for the ASP.Net Core/Blazor framework in the first instance -  ASP.Net Core would need to support resx files being named razor.resx.  Such nesting is not currently natively supported, and that is what this feature request is.

**Comment by javiercn** [comment]
@paulguz-datapa correct me if I am missing something, but it is not this just a regular `resx` file?

What type of support you expect from the runtime/framework?

Our understanding is that you are asking about file nesting in VS, and that is a tooling feature, not a framework feature. We do not deal with these requests in this repo.

**Comment by paulguz-datapa** [comment]
@javiercn Resx files must be named <Component>.resx, not <Component>.razor.resx. 

I am asking for resx files to be included in the Blazor .razor nesting as per the CS, JS and CSS files. This would be consisent and intuitive.
