### ISSUE TITLE
Better way to override default RoleValidator 

### ISSUE THREAD

**Issue by nrmohan** [dotnet/aspnetcore#46066]
In order to override existing RoleManager validation we had to remove it from the DI like this

```
var defaultRoleValidator = builder.Services.FirstOrDefault(descriptor => descriptor.ImplementationType == typeof(RoleValidator<IdentityRole>));
if (defaultRoleValidator != null)
    builder.Services.Remove(defaultRoleValidator);
```

is there a better way to do this?  maybe adding a custom Validator should remove the default one? 
```
builder.Services.AddIdentityCore<IdentityUser>()
.AddRoles<IdentityRole>()
.AddRoleValidator<CustomRoleValidator>();
```

https://github.com/dotnet/aspnetcore/issues/22044
[#14010](https://github.com/dotnet/aspnetcore/issues/14010)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
You will need to remove the service registration and register the new one that you need, and the code that you've got in your description seems reasonable.
