### ISSUE TITLE
`Challenge` vs `ChallengeResult`

### ISSUE THREAD

**Issue by qui8t** [dotnet/aspnetcore#46076]
_My apologies in advance if this is explained before, but I could not find any topic on this Github repo, SO, or learn.microsoft.com that explains it._

I am wondering what are the differences between the following two calls when authenticating with an external identity provider, and when each is recommended over the other? 

```csharp
[HttpPost]
[AllowAnonymous]
public IActionResult ExternalLogin()
{
    return Challenge(_getProps(), GoogleDefaults.AuthenticationScheme);
}

[HttpPost]
[AllowAnonymous]
public IActionResult ExternalLogin()
{
    return new ChallengeResult(GoogleDefaults.AuthenticationScheme, _getProps());
}
```

**Comment by Tratcher** [comment]
Challenge is just shorthand for ChallengeResult:
https://github.com/dotnet/aspnetcore/blob/a527ac581f36dbb74967af20f6d04bb3eee748a1/src/Mvc/Mvc.Core/src/ControllerBase.cs#L2327-L2331

**Comment by qui8t** [comment]
That makes sense, thank you!!
