### ISSUE TITLE
Decide if duplicate EventNames in LoggerMessage is appropriate

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#46072]
We have a couple cases caught by the new LoggerMessage analyzer in https://github.com/dotnet/runtime/issues/64667.

Two duplicates here: `InvokeDotNetMethodException` and `InvokeDotNetMethodSuccess`
https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L199-L209

And a duplicate `LocationChangeFailed` between:

https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/CircuitHost.cs#L761-L762
https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/CircuitHost.cs#L812-L813

I've suppressed these warnings in #46055 for now. But we should make a conscious decision if we really want/need these EventNames to be the same, or if we should change them. My understanding is changing them is technically a breaking change, so we should be sure that they need changing if we do.

**Comment by javiercn** [comment]
@eerhardt thanks for raising this up.

I believe this is a copy/paste type of error. We should change the event names to be unique

**Comment by javiercn** [comment]
We probably want the name to be `InvokeInstanceDotNetMethodSuccess`

**Comment by JamesNK** [comment]
@javiercn What is going on with `LocationChangeFailed` and `LocationChangeFailedInCircuit`? The log messages are identical apart from the logging level.

The easy fix is changing `LocationChangeFailedInCircuit`'s log name to `LocationChangeFailedInCircuit`, but what was the idea behind adding it? Why identical logs but different levels?

**Comment by JamesNK** [comment]
> We probably want the name to be `InvokeInstanceDotNetMethodSuccess`

`InvokeInstanceDotNetMethodException` and `InvokeStaticDotNetMethodException`

`InvokeInstanceDotNetMethodSuccess` and `InvokeStaticDotNetMethodSuccess`

**Comment by JamesNK** [comment]
By the way, logging ID and name changes are considered breaking changes and should be added at https://github.com/aspnet/Announcements and friends. e.g. https://github.com/aspnet/Announcements

e.g. https://github.com/aspnet/Announcements/issues/447

**Comment by eerhardt** [comment]
Note that in https://github.com/dotnet/aspnetcore/pull/46055/, @SteveSandersonMS and I updated the event names that were obviously wrong. We should include them as well in any announcement of event name changes:

* ResponseCaching: `ExpirationExpiresExceeded` => `NotModifiedIfNoneMatchStar`
* RedisLog: `Connected` => `NotConnected`
* Components CircuitRegistry: `FailedToReconnectToCircuit` => `ReconnectionSucceeded`
* Components CircuitHost: `BeginInvokeDotNetFailed` => `BeginInvokeDotNetStaticFailed` (to align with `BeginInvokeDotNetStatic`)

**Comment by shiladitya-mukerji-22** [comment]
Hey @javiercn, is this issue still open? If yes I would like to work on it.

**Comment by javiercn** [comment]
@shiladitya-mukerji-22 Yes, if nobody yet has addressed the issue, I think we would accept a change for this.

**Comment by shiladitya-mukerji-22** [comment]
@javiercn Under the task it shows that no one has been assigned yet. So, could you please assign the task to me.

**Comment by javiercn** [comment]
@shiladitya-mukerji-22 go for it.

**Comment by shiladitya-mukerji-22** [comment]
@javiercn Thank you.
