### ISSUE TITLE
Pseudo loc menu item appearing on project context menu (view in browser)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#46089]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pseudo-loc-menu-item-appearing-on-projec/10247542)._

---
1. Create a Blazor Server application
2. Right-click on the pre-created Pages folder

Result:

First item in context menu shows 'View in Browser', but it's pseudo-loc'd, so has random characters before and after

---
#### Feedback Bot on 1/8/2023, 08:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Nick-Stanton** [comment]
@dougbu do you know where this needs to be routed? It looks like it may be a template localization issue. Thanks.

**Comment by mkArtakMSFT** [comment]
This was a VS issue. The WebTools team will be taking care of the internal ticket. Closing this one.

**Comment by dougbu** [comment]
@Nick-Stanton sorry for not responding earlier. I forgot your question when I got back from my extra-long long weekend.

I'm the right contact for loc issues these days. Feel free to tag all of @dotnet/aspnet-build instead of just me because I'm not always around.
