### ISSUE TITLE
Access-Control-Allow-Origin not added to response header

### ISSUE THREAD

**Issue by csklm** [dotnet/aspnetcore#46083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My web API is registered on the Azure AD as described [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration). I have also [registered](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-registration) a web app that calls my API and handles the authentication. I can get the Bearer token and then use it in Postman to send requests to my API.

Now there is a React app (developed by another team) that should be the frontend of my API. I'm trying to setup the whole application locally, my API is listening on localhost:5220 while the React app is running on localhost:3001. When I try to send a request I get the following error:
![image](https://user-images.githubusercontent.com/114993647/212337426-66ac807d-134f-4e39-b9c3-07733db1ecae.png)

The error message:

> Access to fetch at 'http://localhost:5220/api/job/all' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> GET http://localhost:5220/api/job/all net::ERR_FAILED 307

Here are my headers:
![image](https://user-images.githubusercontent.com/114993647/212337522-1c2e9756-5daa-4be7-b50d-d9f9a283cc47.png)

My Program.cs:
`if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseRequestLocalization(localizationOptions);

app.UseCors(options => options.WithOrigins("http://localhost:3001").AllowAnyHeader().AllowAnyMethod().AllowCredentials());

app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.Run();`

I see that this is the required order of the middlewares, if I remove the UseHttpsRedirection or put it after UseCors I get a 401 error, but then the Access-Control-Allow-Origin header appears in the response. I've installed the Microsoft.AspNetCore.Cors NuGet package but it's using directive grayed out.
Here is my applicationUrl from launchSettings.json:
`"applicationUrl": "https://localhost:7220;http://localhost:5220",`

What am I doing wrong? How should I configure my API to send the correct headers back? Why is the `using Microsoft.AspNetCore.Cors` not used by my code?

EDIT: Turned out, the frontend app wasn't sending the access_token, but now it's updated so I receive the token with every request (and the token is working in Postman) but I still face the same issues as described above. When I remove the HttpsRedirection and the localhost:7220 from the launchSettings I still get the 401 Unauthorized error, but I also get this message in the log:

> [2023-01-19 13:02:24.112 +02:00 INF] Authorization failed. These requirements were not met:
> DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
> ScopeAuthorizationRequirement:Scope=
> [2023-01-19 13:02:24.114 +02:00 INF] AuthenticationScheme: Bearer was challenged.

Can someone tell me why isn't this working?

### Expected Behavior

I'd like the correct headers attached to the response and the requested data to appear in the frontend app.

### .NET Version

7.0.100

**Comment by rafikiassumani-msft** [comment]
@csklm When you have the ` app.UseHttpsRedirection();` enabled, can you ensure that your react (fetch) app is calling the `https` and not `http` url of your backend ( `https://localhost:5220/api/job/all`). Sorry for the trouble with CORS.

**Comment by csklm** [comment]
@rafikiassumani-msft I've enabled the `UseHttpsRedirection` and changed my applicationUrl to `"applicationUrl": "https://localhost:5220"` and I still get a 401 Unauthorized error with the same message:

> [2023-01-20 10:11:15.576 +02:00  INF]  Authorization failed. These requirements were not met:
> DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
> ScopeAuthorizationRequirement:Scope=
> [2023-01-20 10:11:15.589 +02:00  INF]  AuthenticationScheme: Bearer was challenged.

I've decoded the token and agin, it contains the scope from the AAD API.

**Comment by csklm** [comment]
Turned out, it was the frontend app again. It was sending the correct token but with Authentication header instead of Authorization. Once I figured it out, the whole problem disappeared, so everything was working correctly on the backend. Thanks for the response, I'm closing the issue.
