### ISSUE TITLE
.Net Core Signal R Chat Client UI Options

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/aspnetcore#46093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Cannot seem to find a current .Net Core Signal R Chat Client UI - Open Source or Pay For.

### Describe the solution you'd like

Suggestions for .Net Core Signal R Chat Client UI libraries.

Thanks!

**Comment by davidfowl** [comment]
This isn't really the place to ask this question, I would head to https://stackoverflow.com/questions/tagged/asp.net-core-signalr for these types of questions.
