### ISSUE TITLE
Blazor User.Identity seems to be null

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#46102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

a Server Blazor app. Every writing to sql database with ef is tracking usernamen
Auth via AzureAD

Code
```context.User.Identity?.Name;```

I can not see any problem in debugging. But running the blazor project on iis, username fields in SQL Tables are randomly null 

program.cs
```builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
.AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));

builder.Services.AddControllersWithViews()
.AddMicrosoftIdentityUI();

builder.Services.AddAuthorization(options =>

{
    options.FallbackPolicy = options.DefaultPolicy;
});
``````

and

```
builder.Services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<IdentityUser>>();
```

Blazor components

````
  @inject AuthenticationStateProvider AuthenticationStateProvider
``````

and

``` 
 AuthenticationState context;
    protected override async Task OnInitializedAsync()
    {
        context = await AuthenticationStateProvider.GetAuthenticationStateAsync();

```

seems or could be related to somehow url changes by user oder code driven- Changing the Blazor View and go back (just a guess)

### Expected Behavior

Username must be present

### Steps To Reproduce

can not but found others facing same issue
https://stackoverflow.com/questions/67566446/user-name-property-is-null-in-blazor-server-authenticationstateprovider

### .NET Version

6

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

We would suggest that you add logging around `RevalidatingIdentityAuthenticationStateProvider` as a first step to determine what might be going on.

Since you are suggesting that it is not obvious when this problem happens, it is going to be impossible for us to investigate this issue without a clear repro, so the best we can do is try and help your identity what might be going on.

There might be legitimate cases for the user becoming null, like the cookie expiring and the circuit reconnecting after the connection to the circuit is lost.

**Comment by hannespreishuber** [comment]
"We would suggest that you add logging around RevalidatingIdentityAuthenticationStateProvider as a first step to determine what might be going on."
can you give me a advice, link, code- how to accomplish this (best)?

**Comment by javiercn** [comment]
@hannespreishuber I actually realized that there is already logging in this area. 

In that case capture the logs at debug level for `Microsoft.AspNetCore.Components.Server` (fallback to `Microsoft.AspNetCore.Components` if you do not get enough info) to try and determine when the user you are receiving is null.

You might also want to write a `CircuitHandler` https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#blazor-server-circuit-handler to collect data about what is happening when the user is null.

**Comment by hannespreishuber** [comment]
I have never ever done that on a production IIS machine under user load 
"In that case capture the logs at debug level for Microsoft.AspNetCore.Components.Server"

honestly no idea where to start

**Comment by javiercn** [comment]
@hannespreishuber It depends highly on your environment.

There are docs for logging, here:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0

We ship several providers https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#built-in-logging-providers

And there are a few third-party ones you can setup https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#third-party-logging-providers

Given that this is happening seldomly to you in a production environment, you'll have to capture the logs until you see the issue happen, and then hopefully with the logs figure out why.
