### ISSUE TITLE
avoid to render whole application in startup

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/aspnetcore#46101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

whole application is on razor files in .dll files we can compile them to html in compile time and store them in html file's
and that's can improved startup performance

### Describe the solution you'd like

compile razor components to html components
and make them two part
1. html side
2. programatically side
we can avoid to compile whole component in runtime and startup time for webapplication and improve that performance

**Comment by javiercn** [comment]
@sajjadarashhh thanks for contacting us.

This is not something we are planning to do. The scope of your idea is to broad and not actionable for us.

If you are talking about static site generation, that's something that we are exploring, but it does not match in our view the description from your ask.
