### ISSUE TITLE
custom inspect element for blazor

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/aspnetcore#46107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

do a something like vue.js do but with another feature that make this more useful and likable
that's new tab in edge chromium devtools for manage state's and component style's
view and edit components styles and types in browser and sync changes to visual can be very useful and helpful
we're change most styles in browser and test them then when we give stable solution apply changes in code mannually
when we can automate this in .net is very is easier to use than apply manually

### Describe the solution you'd like

create an extension to integrate with roslyn and visual studio to apply manually changes from browser to visual studio
when we want to create this most be consider somethings:
1. user don't want to apply some changes thats dont helpful
2. we can't to access directly to component from html tag that rendered in browser and we need to have hierarchy of components that's help our to know which components rendered this and where to apply changes
3. all changes is not from user codes and maybe user changed third party libraries that we need to apply changes ISOLATED just for that's component used this third party component.

**Comment by javiercn** [comment]
@sajjadarashhh thanks for contacting us.

We suggest you file this issue through the visual studio suggest a feature dialog to get a better and faster answer. This issue tracker is dedicated to the runtime and framework themselves.

**Comment by sajjadarashhh** [comment]
@javiercn but we need to implement some thing in .net for that
And if we implement this in .net we can use that in vs code
