### ISSUE TITLE
[Question] interoperability of Redis backplane, with Microsoft.AspNet.SignalR

### ISSUE THREAD

**Issue by rayao** [dotnet/aspnetcore#46105]
I'm migrating a net472 project to net6, the project doesn't serve SignalR request, but it publishes SignalR messages through Redis backplane. I see this in original project:
`    GlobalHost.DependencyResolver.UseStackExchangeRedis(new RedisScaleoutConfiguration(connectionString, "EventKey"));`
I think I need this in new project:
`    opt.Configuration = ConfigurationOptions.Parse(connectionString);`
`    opt.Configuration.ChannelPrefix = "EventKey";`
I just want to confirm, is this really equivalent to the original configuration? Specifically, is RedisScaleoutConfiguration.EventKey equivalent to ConfigurationOptions.ChannelPrefix?
If not, how to make the interop work? Since I don't want to change the SignalR host service, not for now at least.

Thanks.

**Comment by davidfowl** [comment]
No this will not work. The 2 frameworks are incompatible. 

> If not, how to make the interop work? Since I don't want to change the SignalR host service, not for now at least.

If this component is just publishing, then it might be easy to port a subset of [this code](https://github.com/SignalR/SignalR/tree/main/src/Microsoft.AspNet.SignalR.Redis) to .NET 6.


cc @halter73 @BrennanConroy

**Comment by rayao** [comment]
Thank you @davidfowl
Do you mean I can implement a class like RedisHubLifetimeManager<> and override all those Send* methods to publish messages in the way that Microsoft.AspNet.SignalR.Redis does?
The serialized message byte[] from these 2 frameworks are identical? Or I have to change message protocol part also?

**Comment by davidfowl** [comment]
I'm not sure you want to treat them as related. I you want to port the minimum set of APIs required to interoperate with the old protocol via publishes only (assuming that's what you're doing). I wouldn't even try to implement a HubLifetimeManager\<\> or use the new SignalR APIs. All you're doing here is writing a publish API for redis, that uses a compatible wire format for old SignalR invocations. 

Your .NET Core based application shouldn't even reference SignalR to do this work. You just need the stack exchange redis client and some of the code from the older repo.

Can you share which APIs you are using in the publisher?

**Comment by rayao** [comment]
Sure, we use following code to get the IHubConnectionContext
```
        private IHubConnectionContext<dynamic> TableActivityHubClients
        {
            get
            {
                return GlobalHost.ConnectionManager.GetHubContext<TableActivityHub>().Clients;
            }
        }
```
and then publish messages with
```
            case NotificationType.UserConnected:
                ret = TableActivityHubClients.Group(group).userConnected(convertedContext, convertedPayload);
                break;
            case NotificationType.UserDisconnected:
                ret = TableActivityHubClients.Group(group).userDisconnected(convertedContext, convertedPayload);
                break;
```
So what I should do is:
- Port Microsoft.AspNet.SignalR.Redis message publishing related code.
- Port Microsoft.AspNet.SignalR message formatting related code.
Is my understanding correct?

**Comment by davidfowl** [comment]
That's right!

**Comment by rayao** [comment]
Thank you very much! I'll follow your suggestions.

**Comment by davidfowl** [comment]
@rayao When you make your solution, can you post it here? That might help other customers in the future.

**Comment by rayao** [comment]
@davidfowl That's for sure, I promise! :)
But our migration is still in planning phase, we have 3 options for this message publishing feature, so whether I can post a working code base here totally depends on if at last this approach is chosen.

**Comment by BrennanConroy** [comment]
Customers solution posted in https://github.com/dotnet/aspnetcore/issues/46958
