### ISSUE TITLE
Azure B2C logout endpoint does not redirect to the post_logout_redirect_uri when logout performed in YARP middleware

### ISSUE THREAD

**Issue by mschaefer-gresham** [dotnet/aspnetcore#46104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Approach 1: Signout User From YARP MIddleware
I'm having an issue with logging out when it's initiated from the server. My server is acting as a Backend-For-Front-End Gateway. It handles the cookie and token management for logging in using Microsoft.AspNetCore.Authentication.OpenIdConnect. And it proxies API requests using YARP. 

The frontend is a React SPA. There is no javascript library and no tokens in the browser. Only the cookie from the server.

The initial login to Azure B2C, which is initiated from the frontend, works fine. And once the user has logged in, the user can click a Logout button in the frontend which navigates to an /auth/logout endpoint in the server that does the following:

```
app.MapGet("/auth/logout", (string? redirectUrl, HttpContext ctx) =>
        {
            if (string.IsNullOrEmpty(redirectUrl))
            {
                redirectUrl = "/";
            }

            ctx.Session.Clear();

            var authProps = new AuthenticationProperties
            {
                RedirectUri = redirectUrl
            };

            var authSchemes = new string[] {
                CookieAuthenticationDefaults.AuthenticationScheme,
                OpenIdConnectDefaults.AuthenticationScheme
            };

            return Results.SignOut(authProps, authSchemes);
        });
```

This navigates to the Azure B2C end session (logout) endpoint. The GET request is successful and I am successully redirected back to the post_logout_redirect_uri in my frontend.

So this all works as expected.

The issue occurs when I pre-emptively log the user out when the HttpContext session expires (if the value for key SessionKeys.EXPIRES_AT doesn't exist I know the session has expired bc the data is deleted). Only the session has expired - the cookies and tokens are still valid. To do this I am using the YARP pipeline middleware per the [documenation](https://microsoft.github.io/reverse-proxy/articles/middleware.html). I've tried three different logout strategies:

```
public static void UseGatewayPipeline(this IReverseProxyApplicationBuilder pipeline)
    {
        var gatewayService = pipeline.ApplicationServices.GetRequiredService<GatewayService>();

        pipeline.Use(async (ctx, next) =>
        {
            var expiry = ctx.Session.GetString(SessionKeys.EXPIRES_AT);
            if (expiry.IsNullOrEmpty())
            {
                 // session has expired so log user out of Azure B2C
                 < signout strategy here (see below) >
            }
            else
            {
                // add access token to request before processing
                await gatewayService.AddToken(ctx);
                await next().ConfigureAwait(false);
            }
        });
```

I've tried the following signout strategies:

SignOutAsync async 
```
var authProps = new AuthenticationProperties
{
       RedirectUri = "/"
 };
await ctx.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
await ctx.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme, authProps);
```

Redirect Response
```
var logoutEndpoint = "https://<registry>.b2clogin.com/<registry>.onmicrosoft.com/b2c_1a_signin-controlim-oidc-local-withexpiry-dev/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A8080%2Fsignout-callback-oidc&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.15.1.0&max_age=0";
ctx.Response.Redirect(logout);
```

Results.SignOut
```
var authSchemes = new string[]
{
    CookieAuthenticationDefaults.AuthenticationScheme,
    OpenIdConnectDefaults.AuthenticationScheme
};
await Results.SignOut(authProps, authSchemes).ExecuteAsync(ctx);
```

In each case the result is the exactly same. The GET request to the logout endpoint is successfull, but I am not redirected to the post_logout_redirect_uri. So the frontend is effectively stuck in this state. As there is no post logout redirect the frontend is effectively stuck in this state.

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/94627216/212474856-befdace5-b81c-4b01-8747-37189237066f.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/94627216/212475962-be4b0d18-7ef6-4e2c-b9c8-7278bf2098a7.png">

Why am I not redirected to the post_logout_redirect_uri? Is it possible to initiate the call to the logout endpoint from the server? I've tried to initiate it a couple other ways from the server and have never gotten it to work. It only works when I initiate it from the frontend. The only way to make this work is to abort the request instead, handle the error in the frontend, and then navigate to the logout endpoint. 

## Approach 2: Use MaxAge
As an alternative approach (no YARP involved) I tried using the [suggestion](https://github.com/dotnet/aspnetcore/issues/10281#issuecomment-493126485) of @Tratcher by setting my session idleTimeout, cookie timeout, and oidc MaxAge to be the same. On the first API call after the session timeout the server ends up in the OnRedirectToIdentityProvider event handler which I assume is the result of the server initiating a call to the authorize endpoint that I see in the browser. But this always results in a CORS error:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/94627216/212531656-a778b8ba-e32b-4ef0-aeb6-c86c265a621d.png">

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/94627216/212531695-21c040e4-d1cd-4cd0-86b3-43d4569381b7.png">

My app's Redirect URIs look like this in Azure B2C:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/94627216/212631133-d72a1c4c-31b5-44d1-a9c1-7de1491d712e.png">

Why does this result in a CORS error? When login or logout is initiated from the frontend I don't get these CORS errors - only in this case when it's initiated from the server. To handle the scenario above I need to catch the failed API request in the frontend, check my userinfo endpoint in the server to see if the ClaimsPrincipal is authenticated (it never is), and if not initiate the login process from the frontend. Then it works fine. As an alternative, I could also use this [approach](https://stackoverflow.com/questions/48214686/trying-to-change-oidc-onredirecttoidentityprovider-from-302-to-401) and return a 401 from OnRedirectToIdentityProvider. This prevents to call to the authorize endpoint. And again, once the 401 is handled in the frontend, then everything works fine.

Using the same approach I also tried setting my cookie timeout later than the session timeout. In this case there is no call to authorize endpoint - it just results in a 401 on the first API call after the session timeout. However, my userinfo endpoint in the server returns that the ClaimsPrincipal is still authenticated. As before, if I initiate a logout from the frontend when I get the 401, then the process works fine.

Nevertheless, both outcomes depend on the frontend initiating the logout/login process.

Is this by design? Does the frontend always need to initiate the login/logout process?

### Expected Behavior

I am redirected to the post_logout_redirect_uri after initiating the logout from the server. Or if the server initiates a login when the session and cookie expire, then the request to the authorize endpoint does not result in a CORS error. Basically, initiating log out or log in from server works. 

### .NET Version

7.0.100

**Comment by rafikiassumani-msft** [comment]
@karelz We think this is related to YARP. Can you look into this issue ?

**Comment by Tratcher** [comment]
Why are you linking auth lifetime to session lifetime? If you're trying to manage auth lifetime you should do that directly.

**Comment by Tratcher** [comment]
@rafikiassumani-msft, I don't see any YARP specific concerns here, everything they're trying to do takes place before requests are passed to YARP for forwarding. This is more likely an issue for @blowdart to follow up on.

**Comment by mschaefer-gresham** [comment]
@Tratcher could we just focus on my second approach above based on MaxAge which you suggested [here](https://github.com/dotnet/aspnetcore/issues/10281#issuecomment-493126485) since this is what I've settled on. When MaxAge, session idle time, and cookie expiry are all the same, the first API call that arrives after the timeout results in a call to the authorize endpoint orginating from the server. It always fails with a CORS error:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/94627216/212531656-a778b8ba-e32b-4ef0-aeb6-c86c265a621d.png">

Why does this CORS error occur? Is it expected? 

My solution was to simply prevent the call to authorize by returning a 401 from the OnRedirectToIdentityProvider event handler. I handle the 401 in the frontend and ask the user to Login again. From there it all works fine.

```
options.Events.OnRedirectToIdentityProvider = (context) =>
            {
                if (config.ApiPaths.Any(path => context.Request.Path.StartsWithSegments(path)))
                {
                    if (context.Response.StatusCode == (int)HttpStatusCode.OK)
                    {
                        context.Response.StatusCode = 401;
                    }
                    context.HandleResponse();
                } 
                context.ProtocolMessage.SetParameter("prompt", "login");
                return Task.CompletedTask;
            };
```

In general, how is this situation suppose to work? Should the server's call to authorize work? Or is it up to the frontend to handle the 401 and re-intiate the login process? Regardless of my approach, I can only make login and and logout work from the front end. I just want to know if this is by design.

**Comment by mschaefer-gresham** [comment]
Variations of this CORS question have been raised multiple times [1](https://stackoverflow.com/questions/56971492/identityserver-4-asp-net-core-mvc-ajax-call-redirects-to-authorize-endpoint-if), [2](https://stackoverflow.com/questions/69661356/when-calling-a-net-core-controller-action-with-the-authorize-attribute-client-s), [3](https://stackoverflow.com/questions/72256123/okta-the-authorize-endoint-blocked-by-cors), [4](https://stackoverflow.com/questions/74095132/cors-error-appears-after-adding-react-build-to-wwwroot-folder), [5](https://stackoverflow.com/questions/41143322/angular2-cors-error-when-being-redirected-from-api-to-identityserver), and [6](https://stackoverflow.com/questions/75113042/how-do-you-handle-authentication-and-token-refresh-with-microsoft-identity-and-a) but none have a satisfactory answer.

The CORS error is [mentioned](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#ajax-calls-can-now-participate-in-incremental-consent-and-conditional-access) in the Identity Web documentation. This section indicates that the CORS error used to be an expected issue, but now has a remedy. What about the Microsoft.AspNetCore.Authentication.OpenIdConnect framework?

It would be extremely helpful to get an explanation for why this CORS errors is happening, whether it's expected or not in the context of the Microsoft.AspNetCore.Authentication.OpenIdConnect framework, and what the recommended solutuon is.

**Comment by blowdart** [comment]
Nice try, but not it. This looks like MSAL from the version header. 

@mschaefer-gresham Please open an issue in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet - we can't transfer to there unfortunately

**Comment by mschaefer-gresham** [comment]
Hi @blowdart, thank you for taking a look. But I'm not using MSAL.  I'm using Microsoft.AspNetCore.Authentication.OpenIdConnect.

**Comment by blowdart** [comment]
Which uses MSAL underneath (it's just not obvious) 

I don't think it's us here, the msal folks live in AAD org, so they'll have a better idea why it's not working.

**Comment by mschaefer-gresham** [comment]
Thank you.

**Comment by mschaefer-gresham** [comment]
@blowdart 

I raised this issue with the MSAL team and they [say](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3917#issuecomment-1404398457) that Microsoft.AspNetCore.Authentication.OpenIdConnect does not use MSAL.

If you or anyone else on the team could tell me whether the CORS error that occurs after the session and cookie expire is expected or not, it would be extememly helpful. And if it's not expected, an explanation as to why it occurs and how to avoid it would be much appreciated.

Thank you.

**Comment by blowdart** [comment]
I wouldn't have thought it was expected, otherwise logout wouldn't work, but you are doing your own thing here (auth is deliberately separated from session state in asp.net)

The authorize endpoint, is it yours or B2Cs?

**Comment by mschaefer-gresham** [comment]
It's B2Cs.

**Comment by blowdart** [comment]
So it seems "weird" to me that you're using the front end to login and the back end to logout, rather than doing it in the same place for both, where it would be consistent, but I don't know enough about B2C to know what their expectations are for this.

@rafikiassumani-msft you should assign a dev to investigate.

**Comment by mschaefer-gresham** [comment]
@blowdart 

Ahh I see now what you were saying. 

I'm not using the backend to log out now. Maybe my first comment was too long. 

Orginally, I was trying two different approaches. I have abandoned the first approach and I am now focused only on the second approach. In this case I am logging in and logging out the front end.  But when the cookie expires the server tries to call the /authorize endpoint.

But to your point, both approaches are indeed consistent. In the first approach intentionally logging out from the server **did not** work. So either way, the behavior is consistent. Log in and log out from the server **does not** work. 

Both only work from the front end.

**Comment by rob-king-volpara** [comment]
I had a simiklar problem just now and it turned out I was setting the PostLogoutRedirectUri in the wrong place with Microsoft.Identity.Web 1.25.10

It needs to be set in options.Events.OnRedirectToIdentityProviderForSignOut

`options.Events.OnRedirectToIdentityProviderForSignOut = ctx =>
{
  ctx.ProtocolMessage.PostLogoutRedirectUri = "https://yarp-url";
  return Task.CompletedTask;
};`

**Comment by Tratcher** [comment]
You shouldn't ever have to specify the url prefix directly. If you have forwarders configured they should enable OIDC to generate the correct redirect urls.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

**Comment by mschaefer-gresham** [comment]
In my YARP example I had forward headers configured. The redirect still did not work.

**Comment by Tratcher** [comment]
Did you try the troubleshooting steps for the destination app to make sure the forwarders are working as expected?
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0#troubleshoot

**Comment by mschaefer-gresham** [comment]
I'm closing this issue and will reopen another which only deals with the CORS issue related to the call to /authorize when the cookie expires. I am no longer pursuing the approach of logging out within YARP middleware.
