### ISSUE TITLE
[Kestrel] Count all traffic per request, including headers

### ISSUE THREAD

**Issue by WhitePhoera** [dotnet/aspnetcore#46118]
May be that must be feature request, but i hope it's possible to do that now as well.

I can count body, by replacing Request.Body and Response.Body with my own proxy.

But it is possible to count bytes for in/out for whole request?
in single request per connection that kinda possible via replacing transport.

But that will not work with keep-alive and http2 connections.

Any options exists?

**Comment by Tratcher** [comment]
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/38918 and https://github.com/dotnet/aspnetcore/issues/38919.
