### ISSUE TITLE
AntiforgeryValidationException

### ISSUE THREAD

**Issue by Nelo-cool** [dotnet/aspnetcore#46124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys! Help me please. I I read up and down https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0 and a I always thought I understood why AntiForgeryToken. But now I'm confused.

In my asp.net core application (hosted on multi-servers IIS) about 5000 users per day and a small part of them has an error:
```
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {5626ee7c-f8da-455e-b993-46b7b979ec71} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
the most interesting thing is that the error occurs in GET requests and GUID never changes, even on the first visit. I can't replicate this behavior. Any ideas? Please :"(

Configuration:
```
 services.AddDataProtection()
             .PersistKeysToSqlServer() //Save to MS SQL Server
             .SetApplicationName(DebugExtension.CodeName); //Same name
```

### Expected Behavior

I want to understand why she appears and how to catch her

### .NET Version

7

**Comment by davidfowl** [comment]
Where does the implementation of PersistKeysToSqlServer come from?

**Comment by blowdart** [comment]
Is this error reported by your users, or is it just in the logs?
Does that key identifier exist in your database?
If your users are reporting it, what happens if they clear their browser cache?

**Comment by Nelo-cool** [comment]
> Is this error reported by your users, or is it just in the logs? Does that key identifier exist in your database? If your users are reporting it, what happens if they clear their browser cache?

1. Only my logs. Most likely these are bots, according to them UserAgent and IPs. 
2. There is no such key in the database
3. Unfortunately, I can't contact them to ask them to clear the cache or something else :(

But this is the correct behavior on [GET] requests to check antiforgery? So intended?
How would I catch this exception and redirect them to a 404 page for example...

**Comment by blowdart** [comment]
If it's only your logs, and there's no user complaints I'd tend to dismiss this as internet background noise, with bots trying to load your page with invalid CSRF tokens. While it fills your logs it's not a real concern, especially if that key doesn't exist at all.

**Comment by Nelo-cool** [comment]
I think it is. Thank you for your time! I'll hide them in the logs.
