### ISSUE TITLE
Can we refer an external script in Blazor server application?

### ISSUE THREAD

**Issue by neetutanwar** [dotnet/aspnetcore#46136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How can we use an external script in the Blazor server application? for example, jquery, bootstrap.js, or any other Js library exposed via a CDN URL?

### .NET Version

6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You would link (using a script tag) the script from the `_Host.cshtml` file (in the head usually).
