### ISSUE TITLE
The heartbeat has been running for ... which is longer than "00:00:01". ...

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/aspnetcore#46135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Previously raised here: https://github.com/dotnet/aspnetcore/issues/4760
I have a Windows service running on a Windows Server 2022 VM, which hosts a Kestrel web server, in addition to other workers. These messages show up at random points through-out the day, usually dozens of time every day. The actual middleware which serves HTTP requests is a simple "deserialize JSON and add an item to a ConcurrentQueue" operation, which takes about 15ms on average. Whenever I attach to the process with VS, it shows about 20 threadpool threads created (as expected, I have 20 workers processing the work items), but they are all at the threadpool work queue wait stage and not blocked by anything. The actual work item processing uses async API to send data to a 3rd party web service and has no blocking calls. I get these messages even when I know for a fact the Windows service is idling, such as, at 6am, way before the business working hours.

### Expected Behavior

These messages are not raised.

### Exceptions (if any)

As of "01/17/2023 10:36:12 +00:00", the heartbeat has been running for "00:00:26.6776915" which is longer than "00:00:01". This could be caused by thread pool starvation.

The timestamp is in UTC, and this is running in EST, meaning it's actually 5:36am.

### .NET Version

.NET 6

### Anything else?

I have 2 such Windows services with a Kestrel web server, and both have these symptoms. One has 10 regular workers, and the other 20 workers. The one with 10 workers only had 2 such messages today, whereas the one with 20 workers had 68 such messages today (as of 10:35am local time).

**Comment by adityamandaleeka** [comment]
Unfortunately, there's not a lot we can suggest with the information provided. There's a chance it could be something else running on the machine(s) that is causing resources to be exhausted (e.g. AV software).

**Comment by adityamandaleeka** [comment]
Please let us know if you find any clues or actionable info that we can look into for this.

**Comment by TahirAhmadov** [comment]
Hi @adityamandaleeka, thanks for taking a look at this. How can I gather more information? Is there a diagnostic/debugging tool I can use to collect data of some sort? Or perhaps I can add some code to output stuff when this message is raised, by temporarily adding a "watcher" to the logging sub-system?

**Comment by TahirAhmadov** [comment]
I'll try to put together a simple re-pro project which exhibits these behaviors and post it here.

**Comment by adityamandaleeka** [comment]
Here's a few starting points that may be useful:

- Is there anything interesting shown in the Windows Event Viewer around the time these hiccups happen?

- Using a collection tool like Windows Performance Monitor, you can set up a trace session that will collect diagnostic data (e.g. using the 'System Performance' data collection template in Performance Monitor) which will give you a report on things like CPU, I/O, memory usage over time, which can then be correlated to your time periods of interest.

**Comment by samsp-msft** [comment]
If the events are really unpredictable, then being able to capture trace information can be complicated as you don't know when they are going to happen. However, you are on windows, so the infrastructure is in the OS to be able to capture this information, but it's going to take a little work.
The windows performance toolkit has two main components, windows performance recorder and windows performance analyzer. These use the ETW capabilities of the OS to collect trace data and events.
- Setup WPR to collect the CPU and any IIS events in a memory buffer. https://learn.microsoft.com/en-us/windows-hardware/test/wpt/wpr-command-line-options
- Create a little console app that will continuously read the log entries looking for the `"the heartbeat has been running for"` string, and to then stop recording the log. As long as the log buffer is long enough, it should have captured the start of the duration for the heartbeat issues.
- You can use WPA, perfview or I believe Visual Studio to analyze the recording. Zoom/filter to the period of the heartbeat and look at the CPU time/stacks for your process.
- In a long trace, it can often be hard to know what you are looking at in terms of the timeline. It can be valuable to add signposts by writing custom events that you can then use to know what specific time segments represent.
  - you can write those using the WPR command with the -marker option
  - You can write them using code with a custom eventsource, but note you'll need to include that provider in the trace xml config file
  - You can configure the logging to also emit ETW events - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0

[this](https://gist.github.com/javiercn/eefa37fd9e557bc69f5eb4273c95939c) gist showed up as I was pulling links, that may have  some of the what you need in terms of config for WPR.

**Comment by TahirAhmadov** [comment]
Please see the log file as output by the WinSvc:
[2023-01-18.log](https://github.com/dotnet/aspnetcore/files/10453380/2023-01-18.log)

And the Windows events extract, filtered to this WinSvc (name redacted):
[Events.csv](https://github.com/dotnet/aspnetcore/files/10453366/Events.csv)

I'll run WPR tomorrow to try and get more information.

**Comment by halter73** [comment]
Those logs don't seem very helpful.

If you can collect a memory dump while these heartbeat logs are being emitted, it could point to what stacks are causing the presumed threadpool starvation. While less likely, it could also be a noisy neighbor. Do you know the number of active threads in all processes? Could other VMs be stealing resources?

While a memory dump is more likely to help find the root cause, it might also be interesting to know Kestrel's "current-connections" number. What the log is saying is that it took over 1 second for Kestrel "heartbeat" to complete. The heartbeat enumerates all Kestrel connections on a single non-async, non-blocking thread.

The heartbeat normally extremely fast though, so in every case so far that this has been logged and root-caused, it's been threadpool starvation. At any rate, it should never take anywhere close to 26 seconds on a healthy system. https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters

**Comment by TahirAhmadov** [comment]
@halter73 I tried a few things. Running WPR generated very large files (>12GB during only a few hours) and as it happened, not a single message was logged during the time WPR ran. It then stopped running on its own for some reason. (There was disk space remaining.)
Then I tried the `dotnet-counters` command, but it only shows `System.Runtime` metrics, not Kestrel metrics. I couldn't find any info on whether Kestrel metrics need to be enabled specifically or not. I found these pages:
https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#kestrel-configuration
https://github.com/dotnet/dotnet-monitor/issues/464
But I have a feeling this is a different mechanism from the `dotnet-counters` one. 
If you could provide a little info, it would be awesome. Thanks in advance.

**Comment by halter73** [comment]
> Then I tried the `dotnet-counters` command, but it only shows `System.Runtime` metrics, not Kestrel metrics. I couldn't find any info on whether Kestrel metrics need to be enabled specifically or not.

You should see "Microsoft-AspNetCore-Server-Kestrel" listed if you run `dotnet-counters list`. The `dotnet-counters collect/monitor --counters` flag should allow you to specify providers. https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#dotnet-counters-collect

Like I said earlier, I don't think the counters are going to be that enlightening. What we really want is a memory dump showing what stacks are causing the presumed threadpool starvation. WPR might be able to help, but if you can find a way to reproduce the issue without WPR and collect a memory dump manually, by all means do that.

**Comment by TahirAhmadov** [comment]
> You should see "Microsoft-AspNetCore-Server-Kestrel" listed if you run `dotnet-counters list`. 

I saw it when I specified `-r 5.0`.

> The `dotnet-counters collect/monitor --counters` flag should allow you to specify providers. https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#dotnet-counters-collect

Then I ran: `dotnet-counters monitor --process-id 5620 --counters Microsoft-AspNetCore-Server-Kestrel`
And it's stuck on this:
![image](https://user-images.githubusercontent.com/16783987/214287792-f221fb84-f795-48bb-aa66-18d338eff838.png)
Please note that the application is built with .NET 6.

> Like I said earlier, I don't think the counters are going to be that enlightening. What we really want is a memory dump showing what stacks are causing the presumed threadpool starvation. WPR might be able to help, but if you can find a way to reproduce the issue without WPR and collect a memory dump manually, by all means do that.

Should I write a "hook" which dumps the memory right after a heartbeat message is logged? I found this page:
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak
Should I use that tool?

**Comment by adityamandaleeka** [comment]
Tagging @samsp-msft for dotnet-counters help

**Comment by halter73** [comment]
I opened an issue about `dotnet counters list` still defaulting to `--runtime-version 3.1` at https://github.com/dotnet/diagnostics/issues/3622. It's probably time to update that considering it's out of support.

5.0 is the latest runtime version supported by the `list` subcommand, but you can still monitor/collect newer counters described in https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters if you reference them by name. For example, `dotnet counters monitor -n Kestrel.SampleApp --counters Microsoft-AspNetCore-Server-Kestrel` works if you run [Kestrel's sample app](https://github.com/dotnet/aspnetcore/tree/1bb3bca3187d8327ee288088c1d46727c90d5f04/src/Servers/Kestrel/samples/SampleApp).

As for the "Status: Waiting for initial payload", are you sure you have the right PID and not the PID of the `dotnet run` parent process or something? What if you use `-n MyProcessName` instead of `--processs-id <PID>`?

If you are unable to force a repro yourself by using something like bombardier as recommended in https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation and you want to automatically collect dumps, `dotnet monitor` might be another option. It lets you set triggers before taking actions like collecting a dump or stack traces. There's no trigger for a specific log, but the [ThreadpoolQueueLength trigger shortcut](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/collectionrules/triggershortcuts.md#threadpoolqueuelength-trigger-shortcut) might fire around the same time if our suspicion about threadpool starvation is correct.

https://devblogs.microsoft.com/dotnet/announcing-dotnet-monitor-in-net-6/#triggers
[Diagnosing .NET 6 issues from sidecar containers using dotnet-monitor (YouTube)](https://www.youtube.com/watch?v=oCY9BsAw5oU)

The ThreadpoolQueueLength trigger shortcut might not work if the issue is that the other workers or something other than the same process is a noisy neighbor. If you're comfortable writing an application that monitors the log output for the heartbeat log and manually shelling out to `dotnet stack` or `dotnet dump` when that happens, that's also an option. Make sure you have the right PID though! Are you still seeing this log around 68 times a day in production?

**Comment by TahirAhmadov** [comment]
> As for the "Status: Waiting for initial payload", are you sure you have the right PID and not the PID of the `dotnet run` parent process or something? What if you use `-n MyProcessName` instead of `--processs-id <PID>`?

I checked, I did use the right PID and the same thing happens when using process name. 
I tried again when I started typing this comment, and it "waiting" again, and I was typing about the way I'm initing the WinSvc and Kestrel and all that, but then the results showed up a few minutes after I ran the `dotnet-counters ...` command.
```
Press p to pause, r to resume, q to quit.
    Status: Running

[Microsoft-AspNetCore-Server-Kestrel]
    Connection Queue Length                                                0
    Connection Rate (Count / 1 sec)                                        2
    Current Connections                                                    0
    Current TLS Handshakes                                                 0
    Current Upgraded Requests (WebSockets)                                 0
    Failed TLS Handshakes                                                  0
    Request Queue Length                                                   0
    TLS Handshake Rate (Count / 1 sec)                                     0
    Total Connections                                                 38,789
    Total TLS Handshakes                                                   0
```

> If you are unable to force a repro yourself by using something like bombardier as recommended in https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation and you want to automatically collect dumps, `dotnet monitor` might be another option. It lets you set triggers before taking actions like collecting a dump or stack traces. There's no trigger for a specific log, but the [ThreadpoolQueueLength trigger shortcut](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/collectionrules/triggershortcuts.md#threadpoolqueuelength-trigger-shortcut) might fire around the same time if our suspicion about threadpool starvation is correct.
> 
> https://devblogs.microsoft.com/dotnet/announcing-dotnet-monitor-in-net-6/#triggers [Diagnosing .NET 6 issues from sidecar containers using dotnet-monitor (YouTube)](https://www.youtube.com/watch?v=oCY9BsAw5oU)
> 
> The ThreadpoolQueueLength trigger shortcut might not work if the issue is that the other workers or something other than the same process is a noisy neighbor. If you're comfortable writing an application that monitors the log output for the heartbeat log and manually shelling out to `dotnet stack` or `dotnet dump` when that happens, that's also an option. Make sure you have the right PID though! 

I will try these - before I do that, can you advise whether the above info from `dotnet-counters` is helpful?

> Are you still seeing this log around 68 times a day in production?

Here are the stats: 2/1 - 49 (as of 10:24 am); 1/31 - 1; 1/30 - 146; 1/29 - 145; 1/28 - 98; 1/27 - 37; 1/26 - 3; 1/25 - 10; 1/24 - 18; 1/23 - 144; 1/22 - 139; 1/21 - 60
I restarted the server in the evening of 1/30, and these messages stopped, and only reappeared on 1/31 at 23:58, which was the only message that day; today, on 2/1, it's back to business as usual.

**Comment by TahirAhmadov** [comment]
Another update: I think I may have found the issue, but want to wait for a couple of days to confirm, and if it's fixed, I will share my findings and the resolution and will close the issue.

**Comment by halter73** [comment]
> I will try these - before I do that, can you advise whether the above info from dotnet-counters is helpful?

It's hard to say. 46,574 is a lot of connections. If those are all from one client, you might be running out of ephemeral ports. That wouldn't explain the heartbeat warning though. The heartbeat does loop over all of the connections, but 1 second is a long time for the server to do this.

> Another update: I think I may have found the issue, but want to wait for a couple of days to confirm, and if it's fixed, I will share my findings and the resolution and will close the issue.

Any updates?

**Comment by TahirAhmadov** [comment]
@halter73 
> It's hard to say. 46,574 is a lot of connections. If those are all from one client, you might be running out of ephemeral ports. That wouldn't explain the heartbeat warning though. The heartbeat does loop over all of the connections, but 1 second is a long time for the server to do this.

I just tried again and now I get this:
```
Press p to pause, r to resume, q to quit.
    Status: Running

[Microsoft-AspNetCore-Server-Kestrel]
    Connection Queue Length                                                0
    Connection Rate (Count / 1 sec)                                        0
    Current Connections                                                    0
    Current TLS Handshakes                                                 0
    Current Upgraded Requests (WebSockets)                                 0
    Failed TLS Handshakes                                                  0
    Request Queue Length                                                   0
    TLS Handshake Rate (Count / 1 sec)                                     0
    Total Connections                                                 87,009
    Total TLS Handshakes                                                   0
```
But the problem has been solved - please see below.

> Any updates?

It turned out I had a "memory leak" - I had a faulty implementation of a class. I found out by analyzing a memory dump, which showed a **_very_** large count of `Task<bool>` and `TaskCompletionSource<bool>` instances. It must have been interfering with GC in a serious way and causing delays, which in turn affected the heartbeat, but I'm not sure 100% sure what exactly the problem was.

<details><summary>Old code</summary>
<p>

```cs
public class AsyncAutoResetEvent
{
	/// <summary>
	/// Creates an async-compatible auto-reset event.
	/// </summary>
	/// <param name="set">Whether the auto-reset event is initially set or unset.</param>
	public AsyncAutoResetEvent(bool set = false)
	{
		this._set = set;
	}


	/// <summary>
	/// Asynchronously waits for this event to be set. If the event is set, this method will auto-reset it and return immediately, even if the cancellation token is already signalled. If the wait is canceled, then it will not auto-reset this event.
	/// </summary>
	/// <param name="timeout"></param>
	/// <param name="cancellationToken">The cancellation token used to cancel this wait.</param>
	public Task<bool> WaitAsync(TimeSpan? timeout = null, CancellationToken cancellationToken = default)
	{
		lock (this._queue)
		{
			if (this._set)
			{
				this._set = false;
				return Task.FromResult(true);
			}
			else
			{
				var tcs = new TaskCompletionSource<bool>();
				cancellationToken.Register(static tcs => { tcs!.CastTo<TaskCompletionSource<bool>>().SetCanceled(); }, tcs);
				this._queue.Enqueue(tcs);
				if (timeout != null)
					_ = Task.Delay(timeout.Value, cancellationToken).ContinueWith(TimeoutCallback, (this, tcs), TaskScheduler.Default);
				return tcs.Task;
			}
		}
	}

#pragma warning disable CA1200 // Avoid using cref tags with a prefix
	/// <summary>
	/// Sets the event, atomically completing a task returned by <see cref="o:WaitAsync"/>. If the event is already set, this method does nothing.
	/// </summary>
	public void Set()
#pragma warning restore CA1200 // Avoid using cref tags with a prefix
	{
		lock (this._queue)
		{
			while (this._queue.TryDequeue(out var tcs))
			{
				if (!tcs.Task.IsCompleted)
				{
					tcs.SetResult(true);
					return;
				}
			}
			this._set = true;
		}
	}

	readonly Queue<TaskCompletionSource<bool>> _queue = new();
	/// <summary>
	/// The current state of the event.
	/// </summary>
	private bool _set;

	static void TimeoutCallback(Task task, object? state)
	{
		var (aaev, tcs) = ((AsyncAutoResetEvent, TaskCompletionSource<bool>))state!;
		lock (aaev._queue)
		{
			if (!tcs.Task.IsCompleted) tcs.SetResult(false);
		}
	}
}
```

</p>
</details>

<details><summary>New code</summary>
<p>

```cs
public class AsyncAutoResetEvent
{
	/// <summary>
	/// Creates an async-compatible auto-reset event.
	/// </summary>
	/// <param name="set">Whether the auto-reset event is initially set or unset.</param>
	public AsyncAutoResetEvent(bool set = false)
	{
		this._set = set;
	}

	/// <summary>
	/// Asynchronously waits for this event to be set. If the event is set, this method will auto-reset it and return immediately, even if the cancellation token is already signalled. If the wait is canceled, then it will not auto-reset this event.
	/// </summary>
	/// <param name="timeout"></param>
	/// <param name="cancellationToken">The cancellation token used to cancel this wait.</param>
	public Task<bool> WaitAsync(TimeSpan? timeout = null, CancellationToken cancellationToken = default)
	{
		lock (this._taskCompletionSources)
		{
			if (this._set)
			{
				this._set = false;
				return Task.FromResult(true);
			}
			else
			{
				var tcs = new TaskCompletionSource<bool>();
				cancellationToken.Register(CancellationTokenCallback, (this, tcs));
				this._taskCompletionSources.Add(tcs);
				if (timeout != null)
					_ = Task.Delay(timeout.Value, cancellationToken).ContinueWith(TimeoutCallback, (this, tcs), TaskScheduler.Default);
				return tcs.Task;
			}
		}
	}

#pragma warning disable CA1200 // Avoid using cref tags with a prefix
	/// <summary>
	/// Sets the event, atomically completing a task returned by <see cref="o:WaitAsync"/>. If the event is already set, this method does nothing.
	/// </summary>
	public void Set()
#pragma warning restore CA1200 // Avoid using cref tags with a prefix
	{
		lock (this._taskCompletionSources)
		{
			if (this._taskCompletionSources.Count > 0)
			{
				var tcs = this._taskCompletionSources[0];
				this._taskCompletionSources.RemoveAt(0);
				tcs.SetResult(true);
				return;
			}
			this._set = true;
		}
	}

	//readonly object _locker
	readonly List<TaskCompletionSource<bool>> _taskCompletionSources = new();
	/// <summary>
	/// The current state of the event.
	/// </summary>
	bool _set;

	static void CancellationTokenCallback(object? state)
	{
		var (aaev, tcs) = ((AsyncAutoResetEvent, TaskCompletionSource<bool>))state!;
		lock (aaev._taskCompletionSources)
		{
			if (!tcs.Task.IsCompleted)
			{
				tcs.CastTo<TaskCompletionSource<bool>>().SetCanceled();
				aaev._taskCompletionSources.Remove(tcs);
			}
		}
	}
	static void TimeoutCallback(Task task, object? state)
	{
		var (aaev, tcs) = ((AsyncAutoResetEvent, TaskCompletionSource<bool>))state!;
		lock (aaev._taskCompletionSources)
		{
			if (!tcs.Task.IsCompleted)
			{
				tcs.SetResult(false);
				aaev._taskCompletionSources.Remove(tcs);
			}
		}
	}
}
```

</p>
</details>
