### ISSUE TITLE
Use Microsoft.AspNetCore.Identity instead of Duende.IdentityServer for Blazor WebAssembly App and ASP.NET Core Web API with Individual Accounts that is ASP.NET Core Hosted

### ISSUE THREAD

**Issue by Ogglas** [dotnet/aspnetcore#46131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This has been partially discussed in the thread below but it was locked on Jul 8, 2021 and given that we have entered 2023 I think a new thread has viability.

> For .NET 7 we will investigate if we can build tooling to allow development and testing of OIDC (OpenID Connect) enabled applications when disconnected from the internet. 

https://github.com/dotnet/aspnetcore/issues/32494

Link with similar issues:

https://github.com/dotnet/aspnetcore/issues/32494#issuecomment-834628458

Since `Microsoft.AspNetCore.Identity` is used for a new `ASP.NET Core Web App` in `.NET 7` I think the same identity solution should be used for Blazor. By doing this `ASP.NET Core Web API` template could also get the option with Individual Accounts back. 

### Describe the solution you'd like

Replace `Duende.IdentityServer` with `Microsoft.AspNetCore.Identity` or a similar library created/maintained by Microsoft. I know you are not authentication experts and have no expertise in writing or maintaining an authentication server but everyone does not want to use AAD. I think Microsoft should provide their own library for these situations. 

https://github.com/dotnet/aspnetcore/issues/32494#issuecomment-834666754

**Comment by Ogglas** [comment]
It seems this will be implemented now:

> * **Modernize existing identity to support token-based auth.** Although our existing cookie-based solution works for SPA apps, the industry has evolved and token-based auth solutions are far more flexible and common. We plan to extend the existing identity platform to enable token-based authentication out-of-the-box. This would mostly mirror the capabilities and functionality of the existing cookie-based solution and encapsulate the auth data in a token rather than a cookie and enable it to work in scenarios where cookies are not optimal or appropriate.
> * **Remove the dependency on Duende's IdentityServer from our SPA templates.** This is a common request and it makes sense given there are more options out there and the licensing changed after it was first included in our templates. IdentityServer remains a great option for self-hosting a standards-compliant Open ID Connect and OAuth 2.0 solution. Duende provides their own template to integrate with ASP.NET Core Identity.



https://github.com/dotnet/aspnetcore/issues/42158#issuecomment-1481742187

https://github.com/dotnet/aspnetcore/issues/47226

**Comment by mkArtakMSFT** [comment]
@halter73 I think this should be closed now, or is there anything left?

**Comment by halter73** [comment]
We still need to remove the Microsoft.AspNetCore.ApiAuthorization.IdentityServer project from the repo.
