### ISSUE TITLE
FileStreamResultExecutor does not write Content-Length, also when Length is known

### ISSUE THREAD

**Issue by pfeigl** [dotnet/aspnetcore#46149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`FileStreamResultExecutor` only writes the `Content-Length` for seekable streams.

See this short code segment
https://github.com/dotnet/aspnetcore/blob/d8f7f80ecc6d8d27c92b1cae7c9b3a0afb4b0e20/src/Mvc/Mvc.Core/src/Infrastructure/FileStreamResultExecutor.cs#L36

However there is definately the option for streams which do have a `Length` defined but are still not seekable.
Examples are streams from HTTP Requests, where the Content-Length is known but you can't seek on the HTTP stream.

We realized this problem as kind of a breaking change when migrating a old .NET Framework WebAPI to net6.0.
We kind of proxied a file download from an internal system and now in net6.0 the `Content-Length` is `0`, even though the Stream which is passed into the `FileStreamResult` has a length defined.	

### Expected Behavior

When the underlying stream within `FileStreamResult` does have a non-zero length defined, it should be returned as the Content-Length, no matter whether the result stream is seekable or not.

### .NET Version

net6.0

**Comment by davidfowl** [comment]
> When the underlying stream within FileStreamResult does have a non-zero length defined, it should be returned as the Content-Length, no matter whether the result stream is seekable or not.

How do you suggest we determine whether we can check the length property or not? We use CanSeek to detect this today AFAIK, there's no away to know if Length will throw a NotSupportedException.

**Comment by pfeigl** [comment]
Hmm, I guess that's a fair point. I kind of still stand with my expectation but see, that there is no feasable way to actually achieve it.

It really seems to be tightly coupled together, even the method documentation of `Stream` says the following
```csharp
/// <exception cref="T:System.NotSupportedException">A class derived from <see langword="Stream" /> does not support seeking.</exception>
```

In a smaller code-base I'd probably go with something like `public virtual bool HasLength => CanSeek` to have a good default but allow to override, but that's probably not a change one would do in the runtime here, it has just too many implications.

I guess one thing that would help the situation a little would be to put the following code into something like `protected virtual GetLength(FileStreamResult result)` method
```csharp
            long? fileLength = null;
            if (result.FileStream.CanSeek)
            {
                fileLength = result.FileStream.Length;
            }
```

This would atleast allow overriding it with an implementation that detects support by simple type checks.
If this is something thats feasable I can happily provide a PR. If you would not consider such a change, you can probably close the issue.

**Comment by davidfowl** [comment]
> Another approach is to add a ContentLength property to FileResult.

This seems like the most direct way to communicate the intent.

**Comment by pfeigl** [comment]
I also like this approach. For now we manually set the `Response.ContentType` in the Controller, which works.

> The HTTP implementations I'm aware of in AspNetCore and System.Net do not report the Content-Length in the Stream.Length.
This is true, we built a delegate stream with a backing property for the length and allowed to call `SetLength`. So we are probably really in a very niche usecase here.

Still, beeing able to set the Content-Length on the FileResult sounds like a great addition.

> Type checks aren't a very flexible system for this, especially when the specific types aren't public.
Also true, but works within a project - obvisouly not in library code.

So, all in all you got me full on your side already!

**Comment by rafikiassumani-msft** [comment]
@pfeigl Can you fill out the the api proposal (https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=) template if you'd like us to add the property to the `FileStreamResultExecutor`
