### ISSUE TITLE
Blazor WASM deployed to Cloudfront on url downloads 70 dlls, but Cloudfront url only downloads 20

### ISSUE THREAD

**Issue by mtrtm** [dotnet/aspnetcore#46152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't find anything like this in issues, so hopefully this is new.

I deployed my MudBlazor wasm app to AWS Cloudfront.  I am still on dotnet6 at the moment, and found that AOT made both desktop and mobile VERY slow (45-60 second load time on mobile, about half that time on desktop) so I shut that off for now.

What is weird is that if I use browser tools and disable cache, when loading locally my app is less than 2 mb and loads blazingly fast.  When I deploy to cloudfront, if I go to the cloudfront url, it's a lot bigger and slower.  When I point my A/AAAA records to cloudfront, I get even more files still.  

I was quite pleased by local performance - I thought that a debug build with less than 2 mb would be even faster when deployed - can someone help me troubleshoot?
![image](https://user-images.githubusercontent.com/8888546/213204591-cf5a0529-71ed-45f6-983f-46cd2f34d2e9.png)

### Expected Behavior

I would expect a deployment (with and without AOT compile) to be smaller and faster than running locally

### Steps To Reproduce

Create Mudblazor project/sln using cli:
`dotnet new --install MudBlazor.Templates`
`dotnet new mudblazor --host wasm --name MyApplication`

Deploy to AWS using https://aws.github.io/aws-dotnet-deploy/ - so from your blazor folder in the cli> `dotnet aws deploy`

Add A/AAAA records to point to the cloudfront distro

1. Locally: view very small and fast (full production app < 2 mb for me)
2. Cloudfront url: about the same number of files, but twice as large (still decently fast, though)
3. Actual url pointing to cloudfront: 70 files, 50 mb

### .NET Version

dotnet6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Disabling cache is a little bit different than having cached cleared. Please make sure you either clear the caches or open your browser in an `In-Private` mode. Hopefully this will show the real list of files that are being requested even locally.

**Comment by danroth27** [comment]
Some potential issues are that the app might not be trimmed or compressed. When you browse to the deployed app do you see any messages in the browser console? If the app isn't trimmed you should see a message there saying so. Also check if the responses are compressed using the browser networking tab.

Another thing you can try is publishing to Azure Static Web Apps. Azure Static Web Apps has [built in support for Blazor WebAssembly apps](https://learn.microsoft.com/azure/static-web-apps/deploy-blazor), including handling fallback routing for deep links and serving the precompressed files that the .NET SDK produces when the Blazor app is published.

**Comment by mtrtm** [comment]
OK, I have done a lot more tests and am now confused.  In private looks better than dev, and nearly identical (why 1 more file?).
I have seen a couple times in a regular chrome browser the production url load 70 and the cloudfront url load 18, but so far I can't reproduce it consistently.  

I don't have any console errors.

**Comment by mtrtm** [comment]
I still can't reproduce what I was seeing. Closing
