### ISSUE TITLE
Blazor webassembly not reloading

### ISSUE THREAD

**Issue by garzatech** [dotnet/aspnetcore#46159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a blazor webassebly app hosted on an IIS site.  When I deploy a new version it does update the browser with a new client.  If I run in incognito mode the version is loaded.
I have tried added const variable with version number into the service-worker.js file namedj "const CACHE_VERSION = 0.23"  I have also tried to manully reload using javascript command "windows.reload(true).
All options have not worked.

### .NET Version

netcore 6.0

**Comment by javiercn** [comment]
@garzatech thanks for contacting us.

When a page uses a service worker, the service worker gets updated in the background and it is not until the next visit that the new service worker takes effect.

See https://learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-7.0&tabs=visual-studio#caveats-for-offline-pwas for details.

**Comment by javiercn** [comment]
@garzatech you might want to check the caching headers on some of the files you are serving or alternatively pass options to the service worker registration as described https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register. Specifically the updateViaCache

**Comment by garzatech** [comment]
I was finally able to make it work by registering like this in my index.html.
    <script>navigator.serviceWorker.register('/***.js', { scope: '/' });</script>
I added a version.js with a version number and now the browsers are updating after a refresh after I changed the version number in that file.
