### ISSUE TITLE
`ResponseCookies.Delete(key)` not deleting when website is not in root path 

### ISSUE THREAD

**Issue by Rickedb** [dotnet/aspnetcore#46158]
If you're hosting your application in a different base path from `/`, it just won't delete the cookie:

https://github.com/dotnet/aspnetcore/blob/83d6c56ab616709ec66381def032ffca0065c0ee/src/Http/Http/src/Internal/ResponseCookies.cs#L108

Shouldn't it delete based on current request base path (`HttpContext.Request.PathBase`) ?

Workaround for this issue: 
`Response.Cookies.Delete(item, new CookieOptions() { Path = Request.PathBase });`

**Comment by Tratcher** [comment]
This mirrors append:
https://github.com/dotnet/aspnetcore/blob/83d6c56ab616709ec66381def032ffca0065c0ee/src/Http/Http/src/Internal/ResponseCookies.cs#L34-L37
Given there are parts of the framework like Map that edit the PathBase, I'd hesitate to guess that is what you want for your cookies by default. It would also be a significant breaking change, this has been the behavior since 1.0 (and Katana).

**Comment by Rickedb** [comment]
In my case, I have an [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) application for authentication. Which nowadays still run under IIS Server inside a WebApplication and under a WebSite. e.g.: `https://myhost.com.br/identityserver`.
When generating cookies it goes under `/identityserver` path, which caused malfunction when trying to logout because of the `Delete(string key)` defaulting `/`.

However, by reading your reply, at first it doubts me if it's wrong emitting cookies under the path other than `/`, is it?

And well, I could solve this by mentioning the BasePath of the request as mentioned by you before.

Maybe you should consider if it worth causing a breaking change just for it.

**Comment by Tratcher** [comment]
You're trying to delete IdentityServer's cookies from a separate app? You should only be deleting cookies you create. You should redirect to IdentityServer to ask it to delete it's own cookies.

**Comment by Rickedb** [comment]
No, when I logout at my app I need to revoke my own cookie or local storage when SPA, but I need to call logout endpoint at IdentityServer as well.
However if IdentityServer does not exclude cookies, it stays "Logged at IdentityServer" but not at my own application.

Which causes to log in automatically when I retry to login at my app (because Identity relies at it own's cookie to ensure single sign own).

**Comment by Tratcher** [comment]
Are you saying that IdentityServer is unable to delete its own cookie from its logout endpoint? Or that you're unable to delete IdentityServer's cookie from elsewhere?

**Comment by Rickedb** [comment]
IdentityServer was unable to

**Comment by Tratcher** [comment]
That's something that should be addressed in IdentityServer then. To end up in that state it would have to create the cookie with the path set to /IdentityServer, but then try to delete it with the path set to /.

**Comment by Rickedb** [comment]
Still seems kinda strange to me that it enforces cookie creation at `/` path.

This means, for example, that if I have a WebApplication inside IIS it will always create the cookie at the root path which will also be visible to my root WebSite and any of my WebApplications? Looks unusual.

**Comment by Tratcher** [comment]
It's up to the component issuing the cookie to decide what the appropriate path scope is. If it doesn't specify then yes, the default is for the whole domain. There's no plan to change ResponseCookies to use a different default.
