### ISSUE TITLE
Add `Map` implementation with overload for `InferMetadata` and `CreateRequestDelegate`

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#46163]
## Background and Motivation

For the purposes of the request delegate generator, we want to be able to invoke the logic in the `RouteEndpointDataSource` but provide a custom implementation of a `Map` method that will allow the user to pass custom delegates for inferring metadata and producing a request delegate. The source generator will call this overload with implementations generated at compile time to circumvent calling APIs that use runtime code generation.

## Proposed API

```csharp
public static class GeneratedRouteEndpointBuilderExtensions
{
  public static Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map(
    this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes,
    string pattern,
    System.Delegate handler,
    IEnumerable<string> httpMethods,
    Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult> populateMetadata,
    Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createRequestDelegate)
  {
    return routes
      .GetOrAddRouteEndpointDataSource()
      .AddRouteHandler(RoutePatternFactory.Parse(pattern),
                       handler,
                       httpMethods,
                       isFallback: false,
                       populateMetadata,
                       createRequestDelegate);
}
```

## Usage Examples

```csharp
[GeneratedCode]
internal static Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut(
  this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints,
  [System.Diagnostics.CodeAnalysis.StringSyntax("Route")] string pattern, 
  Delegate handler)
{
  var populateMetadata = (methodInfo, options) => {
    var metadata = new List<object>();
    // ...
    return new RequestDelegateMetadataResult { EndpointMetadata = AsReadOnlyList(metadata) };
  };
  var createRequestDelegate = (del, options, requestDelegateMetadataResult) => {
    // ...
    return new RequestDelegateResult(finalRequestDelegate, requestDelegateMetadataResult.Metadata);
  };
  return Map(endpoints, pattern, handler, GetVerb, populateMetadata, createRequestDelegate);
}
```

**Comment by halter73** [comment]
API Review Notes:

- What about the assembly and namespace?
    - The assembly probably needs to be in Microsoft.AspNetCore.Routing.dll to reference `RouteHandlerBuilder`.
    - The most obvious namespaces are `Microsoft.AspNetCore.Builder` and `Microsoft.AspNetCore.Routing`. We don't need to use the `Builder` namespace if it's not an extension method. All of these are a default global usings in the Web SDK, so it's not a great place to "hide" code only called from code generators.
    - Let's go with the `Microsoft.AspNetCore.Routing` namespace and hide it with attributes.
- What about using context options so we can add parameters in the future without creating new overloads?
    - We could always add stuff to `RequestDelegateFactoryOptions`.
    - Any change would probably require new overloads to RDF.InferMetadat
    - Create.
    - We also plan to hide this as it's only intended to be called from generated code.
- `[EditorBrowsable(EditorBrowsableState.Never)]`?
    - We think so. It's a signal to customers that they're not intended to use it directly. @davidfowl
- Should it be an extension method?
    - No. We should hide it.
- Can the funcs be an interface? We don't want to introduce unnecessary types, and it's cleaner from the callsite to define two funcs rather than an interface implementation.
- What do we think about `GeneratedRouteEndpointExtensions` as a name?
    - "Extensions" doesn't make sense any more.
    - S.T.J uses "Services" for some things called only by the source generator. This is a little overloaded in ASP.NET Core, but if it's hidden it might be fine.
    - We have `RouteEndpointDataSource` already exists. A "RouteEndpoint" prefix might make sense. It's also related to RequestDelegateFactory.
    - Do we like "Generated" in the name? No.
    - `RouteEndpointBuildServices`?
    - `RouteEndpointGeneratorServices`?
    - `RouteHandlerServices`? No one seems to excited, but this was the last suggestion and we plan to hide it.

API Approved!

```diff
// Microsoft.AspNetCore.Routing.dll

namespace Microsoft.AspNetCore.Routing;

+ [EditorBrowsable(EditorBrowsableState.Never)]
+ public static class RouteHandlerServices
+ {
+  public static Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map(
+    Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes,
+    string pattern,
+    System.Delegate handler,
+    IEnumerable<string> httpMethods,
+    Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult> populateMetadata,
+    Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createRequestDelegate);
+ }
```

**Comment by davidfowl** [comment]
Marking this `[EditorBrowsable(EditorBrowsableState.Never)]` is absolutely unnecessary.

**Comment by captainsafia** [comment]
The deed is done.
