### ISSUE TITLE
SignalR android SDK Release note

### ISSUE THREAD

**Issue by cliffgr** [dotnet/aspnetcore#46168]
Hello is there any place where I can find the release notes on every version of SignarR Android sdk?

**Comment by BrennanConroy** [comment]
Nope, sorry. It's a downside of having everything in one repository, there are too many unrelated changes so we can't automatically generate release notes.

The closest you can get is to look at the history of that section of the repo: https://github.com/dotnet/aspnetcore/commits/main/src/SignalR/clients/java/signalr

Are you looking for any specific change(s)?

**Comment by cliffgr** [comment]
Hello @BrennanConroy  for the fast response..

We are using 6.0.1 version on our product in production mode and I am wondering if there any break changes on 7.X.X version or major improvements. 

Lets close the ticket

Thanks

**Comment by BrennanConroy** [comment]
We generally don't make breaking changes.
The main thing added to the client in 7.X.X is [Client Results](https://learn.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-7.0#client-results).

Looks like we need to add a Java example to the docs 😄
