### ISSUE TITLE
aspnetcore-browser-refresh.js:234 WebSocket connection error when running Blazor WASM project

### ISSUE THREAD

**Issue by isxpjm** [dotnet/aspnetcore#46167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Open Visual Studio 2022
2. Create a new project
3. Select Blazor WebAssembly App
4. Use default values for Project name and Solution name
6. Framework: .NET 7.0 (Standard Term Support)
7. Authentication type: None
8. Configure for HTTPS: checked
9. ASP.NET Core Hosted: checked
10. Progressive Web Application: unchecked
11. Do not use top-level statements: unchecked
12. Create
13. Build and run the application
14. Open your browser debug window
15. Observe there is an error saying:

aspnetcore-browser-refresh.js:234 WebSocket connection to 'wss://localhost:44327/BlazorApp1.Server/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

System information:
Microsoft Visual Studio Enterprise 2022 (64-bit)
Version 17.4.4
ASP.NET and Web Tools = 14.4.326.54890
Web Compiler 1.14.10

Nuget package versions:
Microsoft.AspNetCore.Components.WebAssembly 7.0.2
Microsoft.AspNetCore.Components.WebAssembly.DevServer 7.0.2
Microsoft.AspNetCore.Components.WebAssembly.Server 7.0.2

Browser version:
Chrome 109.0.5414.75

There are multiple reports about this, for example:

https://developercommunity.visualstudio.com/t/net-60-blazor-server-app-websocket-connection-to-w/1596975

But they allude to this being a problem with VS2022 version 17.1, that was fixed with 17.2.  I am using 17.4.4 so has this problem been inadvertently re-introduced?

### Expected Behavior

The application runs without the browser error.

### .NET Version

7.0.102

**Comment by Nick-Stanton** [comment]
Hi @isxpjm, thank you for your verbose repro steps and system info. Unfortunately, I could not reproduce this error in either Edge or Chrome. My configuration (VS version, package versions, etc.) is the exact same as yours with the exception of the following in case it helps.

> .NET Version
7.0.102

I'm on 7.0.2

>Browser version:
Chrome 109.0.5414.75

I was on Chrome Version 109.0.5414.76
