### ISSUE TITLE
Upgraded to net6.0 recently and noticing references of packages like Microsoft.VisualBasic in the using statements

### ISSUE THREAD

**Issue by rohytsinha** [dotnet/aspnetcore#46175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We just upgraded from .net core 3.1 to .net 6.0 and below is the Proj file. we have been using C# 9.0 from long time and we never encountered this before. Recently, while developing code, we are noticing weird references of unwanted DLLs/packages like Microsoft VisualBasic and Office2010.Excel in the using statements which are not even needed. 

using Microsoft.VisualBasic;
using DocumentFormat.OpenXml.Office2010.Excel; 

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UserSecretsId>959a09bd</UserSecretsId>
	</PropertyGroup>

### Expected Behavior

Since we are not using those old packages it should not show in the code. When we explicitly remove it, the code runs fine with or without it so it is unnecessarily added by Visual Studio 2022 or the framework we don't know.

### .NET Version

6.0.100

### Anything else?

![image](https://user-images.githubusercontent.com/39806598/213543200-18e2884f-a29b-4847-8b07-13860db931be.png)

**Comment by BrennanConroy** [comment]
Are you writing code and accidentally accepting the wrong intellisense suggested types? 

![image](https://user-images.githubusercontent.com/7574801/213579592-712d6049-8992-4ca0-9bc0-6598ca35c9eb.png)

VS will add the using for you if you accept the suggestion, but then if you realize that's the wrong type and delete the code/statement the `using` will still be there.

**Comment by rohytsinha** [comment]
No, Surprisingly these are getting added on the top and developers are not even noticing these because they add code at the bottom of the file. This was found during the code review process and developers were surprised when this came up. So this is something Visual Studio or .NET framework is adding automatically maybe the new AI functionality is trying to inject these 🤷‍♂️

**Comment by ShreyasJejurkar** [comment]
@rohytsinha If you see those `using` statements are not getting used (as they are greyed out). I don't think VS inject them automatically unless the types from that namespace are getting used. I would suggest just removing them and seeing if you get any errors, ideally, you should not!

**Comment by rohytsinha** [comment]
@ShreyasJejurkar - Yes we don't get any errors when we remove them. Visual Studio shows them greyed out which is fine but when we open these files in our source code repository Bitbucket during code review sessions for comparison with previous code then it looks like our developers are adding them which is not correct. 

Our Developers are now going back and removing them which is an overhead for us.

![image](https://user-images.githubusercontent.com/39806598/213744898-deecd114-3a6b-4003-b9a3-8d7f061c0617.png)

**Comment by ShreyasJejurkar** [comment]
@rohytsinha instead of fixing file by file. You can apply the code fix at solution level. The yellow light bulb 💡 would give option in VS, to remove unwanted namespace from solution. That way it would be easier.


That being said, it's hard to believe for me that VS is automatically adding this namespace at the top. If possible can you share the small screen recording where you show this behavior as that will help to understand more of it.

**Comment by BrennanConroy** [comment]
I still think your devs are accidentally adding the usings (well VS is, but based on devs using types in that namespace accidentally).

Regardless, this isn't an ASP.NET issue, it would be a VS issue. If you still think it's a bug you can use the feedback/report a problem button in the top right of VS.
