### ISSUE TITLE
Get an error NETSDK1082 "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'." when referencing a Razor Class Library from Blazor Web Assembly App: 

### ISSUE THREAD

**Issue by saif-mazhar** [dotnet/aspnetcore#46171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get the error below when I reference a blank Razor Class Library (RCL) from a blank Blazor Web Assembly App

NETSDK1082 | There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'

### Expected Behavior

Not to get the error

### Steps To Reproduce

https://github.com/saif-mazhar/BlazorWebAssemblyApp-Refrencing-RazorClassLibrary

Did the following then committed to that repo
1. Created a Blazor Web Assembly App
2. Created a new RazorClassLibrary with "Support pages and views" checkbox checked (this issue doesn't occur if it's not checked)
3. Followed [these](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-7.0&tabs=visual-studio#consume-a-razor-component-from-an-rcl) instructions in the section, "If the Support pages and views checkbox, ..."
4. Referenced the RazorClassLibrary

### .NET Version

7.0.102

**Comment by javiercn** [comment]
@saif-mazhar thanks for contacting us.

You have a dependency that is bringing a framework reference to Microsoft.AspNetCore.App, which is not compatible with wasm. You need to factor that out into a separate library.

You can find out which dependency is by looking at your dependencies in the dependencies node in Visual Studio or looking at project.json inside the obj folder.

**Comment by saif-mazhar** [comment]
Thanks @javiercn for the quick response. It appears checking the "Support pages and views" checkbox during RCL project creation creates that dependency. I recreated the project with it unchecked and that resolved the issue.

Perhaps this documentation can be updated to note that since it makes it sound like you can check that checkbox and consume the RCL project from a Blazor Web Assembly project, and if my assumptions are correct, that checkbox is what creates the issue.
