### ISSUE TITLE
Use specific profile in launchsettings with running dotnet run

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnetcore#46184]
Hi,
I want to use specific profile in `launchSettings.json` for running .net core app, but when I run app with `dotnet run`, as default it picks first profile automatically, here `http` profile. How can I use `https` profile with `dotnet run`?

``` json
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:36580",
      "sslPort": 44382
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5208",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7106;http://localhost:5208",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by javiercn** [comment]
@mehdihadeli thanks for contacting us.

I believe you can use the `-lp` or `--launch-profile` parameter.

/cc: @DamianEdwards

**Comment by DamianEdwards** [comment]
Yep, from https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run:

> --launch-profile <NAME>

> The name of the launch profile (if any) to use when launching the application. Launch profiles are defined in the launchSettings.json file and are typically called Development, Staging, and Production. For more information, see [Working with multiple environments](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments).

**Comment by mehdihadeli** [comment]
Thanks.
