### ISSUE TITLE
AmazonDynamoDBClient fails in Blazor Webassembly

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#46204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Attempting to access DynamoDB from Blazor WebAssembly results in an exception:

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

The same code works in Blazor non WASM.

### Expected Behavior

Cloud AWS Services should be available in Blazor Webassembly

### Steps To Reproduce

```c#
    public async Task<bool> CheckDynamoDB()
    {
        Dictionary<string, AttributeValue> key = new Dictionary<string, AttributeValue>
        {
            { "id", new AttributeValue { N = "1" } },
        };

        var ddbRequest = new GetItemRequest
        {
            TableName = "my_table",
            Key = key
        };

        try
        {
            IAmazonDynamoDB _ddbClient = new AmazonDynamoDBClient(aws_access_key, aws_secret_key, RegionEndpoint.USEast1);
            var x = await _ddbClient.GetItemAsync(ddbRequest);
            return true;
        }
        catch (Exception ex)
        {
            string msg = ex.Message;
            return false;
        }
    }
```

### Exceptions (if any)

"'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'"

This is a generic AWS error for something unexpected.

### .NET Version

7.0.102

**Comment by javiercn** [comment]
@genifycom thanks for contacting us.

Not sure what you are doing but based on the context of the error message. Seems that you are using a package that you shouldn't use in webassembly. You should not distribute shared secrets to the browser.

The problem likely is with the package that you are using not being compatible with webassembly, so we suggest you check with the package authors for guidance on how to best support this scenario.
