### ISSUE TITLE
Links in yml file to https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema lead to a 404 error

### ISSUE THREAD

**Issue by atossell91** [dotnet/aspnetcore#46205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Links to,

[https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema](https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema)

are found in several yaml files, but they lead to a 404 error when followed.

This behaviour is the same if learn.microsoft.com instead of docs.microsoft.com

### Expected Behavior

Upon following the links in the files, a web page containing information should open.

### Steps To Reproduce

Just follow the links to,
[https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema](https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema)
in the yml files in aspnetcore/.azure/pipelines

**Comment by danmoseley** [comment]
Probably should be

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

**Comment by atossell91** [comment]
> 

Sure, I'll take a look now. Should I commit it to my current PR?

**Comment by danmoseley** [comment]
Sure if you like.

**Comment by mkArtakMSFT** [comment]
Thanks for resolving this, @atossell91: https://github.com/dotnet/aspnetcore/pull/46206/files
