### ISSUE TITLE
Add chrome.identity support for WebAssembly auth

### ISSUE THREAD

**Issue by johnW-ret** [dotnet/aspnetcore#46203]
I did not see the feature request template when making this issue, so I have updated my initial comment with the feature request template.

## Summary

You can use [Blazor.BrowserExtension](https://github.com/mingyaulee/Blazor.BrowserExtension) to build Chromium browser extensions with Blazor WASM. Most APIs do not accept schemes from extension:// or chrome-extension://, so you must use the [chrome.identity API](https://developer.chrome.com/docs/extensions/reference/identity/#method-launchWebAuthFlow) to make calls with a redirect uri aliased to ``https://[extension-id].chromiumapp.org/authentication/example-login-callback``.

## Motivation and goals

Alternatively, one could write a wrapper around MSAL.js such as in [this MSAL.js Chromium sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/926f1c2ba0598575e23dfd8cdd8b79fa3a3d19ff/samples/msal-browser-samples/ChromiumExtensionSample/auth.js). However, writing a separate wrapper means that a Chrome extension app would have a harder time sharing logic with hosted Blazor WASM app. This is a particular pain point in my case.

Because this requires modifying AuthenticationService.ts to call an additional JavaScript API, I have not found a namespace where this logic could be easily separated into an optional package for distribution separate from this repo. It is not impossible that it could be done.

## In scope

Calling MSAL from a Blazor WASM browser extension.

## Out of scope

Referencing chrome APIs from a non-browser extension.

## Risks / unknowns

Developers configuring their app to call a chrome API when their app is not a browser extension. Adding a reference to the chrome type in package.json adds an unnecessary references for a uncommon use case.

## Examples

```
builder.Services.AddMsalAuthentication(options =>
{
        options.ProviderOptions.UseChromeWebAuthFlow = true;
        options.ProviderOptions.LoginMode = "redirect";
        // ...
});
```

# Proposed design
I have a working implementation of this feature as shown above in a fork, as can be seen [here](https://github.com/johnW-ret/aspnetcore/commit/94ff7ccc44616546b25043f690195f63ba324458). I have not created a PR as I have not done a thorough review, and I believe my design should go under review before I spend too much time on implementation. I would appreciate if someone would take a look at this issue and add design-proposal or api-ready-for-review / api-needs-work.

**Comment by javiercn** [comment]
@johnW-ret thanks for contacting us.

This is not a scenario in the scope of this package. For this type of custom implementation, we would suggest you create your own wrapper.
