### ISSUE TITLE
Polly: consider WebException transient 

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/aspnetcore#46209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On `net7.0-android`, A lot of the errors come through `WebException` instead of `HttpResponseMessage`.

![image](https://user-images.githubusercontent.com/1633368/175824866-c4f08b84-2d1f-4756-b140-314921634431.png)

![image](https://user-images.githubusercontent.com/1633368/175824880-1a1bfb15-ac3f-44f1-ba8f-6ec2f94e1848.png)

Originally raised [here](https://github.com/App-vNext/Polly.Extensions.Http/pull/33).

### Expected Behavior

Treat `WebException` as transient to `HttpPolicyExtensions.HandleTransientHttpError()`

### Worked around:

```csharp
                        HttpPolicyExtensions.HandleTransientHttpError()
                            .Or<IOException>(e => messages.Any(m => e.Message.Contains(m)))
                            .Or<WebException>(e => messages.Any(m => e.Message.Contains(m)))
```

**Comment by davidfowl** [comment]
Isn't this a polly issue?

**Comment by bruno-garcia** [comment]
Ah my bad. Thanks @davidfowl
