### ISSUE TITLE
Project option not working correctly for the `user-jwts` command

### ISSUE THREAD

**Issue by glen-84** [dotnet/aspnetcore#46218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running `dotnet user-jwts list --project src/Api/` returns:

> The project file 'src/Api/src/Api/' does not exist.

### Expected Behavior

No error. The equivalent `user-secrets` command works fine.

`dotnet user-secrets list --project src/Api/`

### .NET Version

7.0.102

### Anything else?

WSL, Debian GNU/Linux 11 (bullseye).

**Comment by captainsafia** [comment]
Looks like a bug here: https://github.com/dotnet/aspnetcore/blob/main/src/Tools/dotnet-user-jwts/src/Helpers/DevJwtCliHelpers.cs#L35-L37.

@glen-84 Any interest in submitting a pull request contributing a fix to the above?

**Comment by glen-84** [comment]
> @glen-84 Any interest in submitting a pull request contributing a fix to the above?

I'm not sure when I'd have the time, and it looks like a proper fix might be more involved (factoring out common code between the JWT and secrets tools):

https://github.com/dotnet/aspnetcore/blob/166593fa00d1b81e994787589cb0d024fc24596d/src/Tools/dotnet-user-jwts/src/Helpers/DevJwtCliHelpers.cs#L28-L43

https://github.com/dotnet/aspnetcore/blob/166593fa00d1b81e994787589cb0d024fc24596d/src/Tools/Shared/SecretsHelpers/MsBuildProjectFinder.cs#L19-L53

**Comment by glen-84** [comment]
@captainsafia Wouldn't a bug like this be fixed in a patch release? It seems quite bizarre to wait 12 months for a fix. 🙂

Maybe I'll find time in the next month or two to put a fix in place, but I also wouldn't want to do so if it meant waiting another 10 months for release. 🚀

The same is even more true for https://github.com/dotnet/aspnetcore/issues/44869, which literally results in corrupted files (imagine someone not using a VCS).

**Comment by captainsafia** [comment]
> @captainsafia Wouldn't a bug like this be fixed in a patch release? It seems quite bizarre to wait 12 months for a fix. 🙂
> 
> The same is even more true for #44869, which literally results in corrupted files (imagine someone not using a VCS).

Yep! Something like this would be serviced. Typically, the process is to land it in a 8.0 preview release, validate the fix, then backport it to 7.0. The bar for these backports is a little higher (see [https://github.com/dotnet/aspnetcore/blob/cb780bea7a9dcb73be6750c615869bf64c30c5f2/docs/Servicing.md](this doc)) so hence the need for some bake time.

> Maybe I'll find time in the next month or two to put a fix in place, but I also wouldn't want to do so if it meant waiting another 10 months for release. 🚀

Next month or two is where I was feeling it depending on some other items. Happy to review a PR if you get to it before then but otherwise no worries.

**Comment by captainsafia** [comment]
Closed in https://github.com/dotnet/aspnetcore/pull/48385 for 8.0-preview6.
