### ISSUE TITLE
Importing Framer website to Blazor is not successfull

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#46211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I already issued the ticket before #45195 but didnt have time to do some more tests. 

So basically I am trying to import framer site to Blazor. If I copy paste whole framer site (which was exported only by saving HTML -> framer recommendation) to index.html its working. When I try to split it (head, scripts -> index.html and body -> Index.razor) to add some logic the UI is all messed up. Also I am getting this error: `Uncaught TypeError: Cannot read properties of null (reading 'dataset')`. I dont know how to deal with this or why its not working if its all working in index.html but not if its split. Is it something I am doing wrong or just Blazor somehow does not support it?

One more thing is if I Save page as webpage complete I also got folder. This scenario has better UI if I split it to index.html and index.razor but it has the same messed UI if I move whole file to index.html.

Second scenario is download page as HTML only (1 file, no folder or additional files) -> this scenario works really bad with "splitting" method (much worse than scenario 1) and page is almost blank but if I import whole file to index.html is working exactly as original one. So I went with scenario 2 because I believe if index.html can display website correctly it will be possible to do it also with splitting the code and adding logic somehow.

**LONG STORY SHORT:**

If I try import framer website to blazor and split it so I can add some logic the UI is messed up completely.
If I try to import framer website to blazor but only to index.html file -> everything is working perfectly. 
Q: Am I doing something wrong or Blazor does not support this kind of action?

Please see ->

**Repo + webapp with framer imported and split to index.html and to Index.razor:**

https://github.com/Laftek/FramerTest2

https://laftek.github.io/FramerTest2/

Repo + webapp with framer imported as whole to index.html:

https://github.com/Laftek/FramerTest3

https://laftek.github.io/FramerTest3/

Original published website that I copied HTML from:

https://founders-make-357512.framer.app/

Thank you.

### Steps To Reproduce

1. Create Blazor WASM.
2. Create framer website and save it as HTML only or webpage complete.
3. Import framer website to Blazor.

### .NET Version

7.0.100

**Comment by Nick-Stanton** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the **blazor** tag.
