### ISSUE TITLE
Custom RemoteAuthenticationHandler Exceptions

### ISSUE THREAD

**Issue by nquandt** [dotnet/aspnetcore#46212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to be able to handle exceptions thrown by AuthenticationHandlers, specifically RemoteAuthenticationHandlers. Generic example. Say something when wrong with authentication and I'd like to clear cookies.

https://github.com/dotnet/aspnetcore/blob/b6bd3236cda202c27f0f8b40900ba49aa725519e/src/Security/Authentication/Core/src/HandleRequestResult.cs#L68

https://github.com/dotnet/aspnetcore/blob/b6bd3236cda202c27f0f8b40900ba49aa725519e/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L130

### Describe the solution you'd like

Either a custom exception type so that we can create middleware to catch 
```csharp
try {
    await next()
catch (AuthenticationHandlerException ex) {
    Do stuff
}
```
or some way of plugging into the handling of errors.

**Comment by Tratcher** [comment]
See here:
https://github.com/dotnet/aspnetcore/blob/b6bd3236cda202c27f0f8b40900ba49aa725519e/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L106-L110
https://github.com/dotnet/aspnetcore/blob/b6bd3236cda202c27f0f8b40900ba49aa725519e/src/Security/Authentication/Core/src/Events/RemoteAuthenticationEvents.cs#L34
https://github.com/dotnet/aspnetcore/blob/b6bd3236cda202c27f0f8b40900ba49aa725519e/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L122

**Comment by nquandt** [comment]
Thanks @Tratcher! This was exactly what I was looking for, I totally missed that.
