### ISSUE TITLE
Server-side Blazor: render loop and update stops responding

### ISSUE THREAD

**Issue by xsIceman** [dotnet/aspnetcore#46217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I'm working on a server-side Blazor application. sometimes while the application is running i get a situation where the application stops responding to gui events. Have enabled logging on web side and can see that websocket is still alive. But when i am in this situation i only get ping data from server.
`
blazor.server.js:1 [2023-01-23T14:45:51.786Z] Trace: (WebSockets transport) data received. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:05.753Z] Trace: (WebSockets transport) sending data. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:06.793Z] Trace: (WebSockets transport) data received. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:21.761Z] Trace: (WebSockets transport) sending data. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:22.786Z] Trace: (WebSockets transport) data received. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:37.767Z] Trace: (WebSockets transport) sending data. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:38.790Z] Trace: (WebSockets transport) data received. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:53.756Z] Trace: (WebSockets transport) sending data. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:46:54.784Z] Trace: (WebSockets transport) data received. Binary data of length 3.
blazor.server.js:1 [2023-01-23T14:47:03.768Z] Trace: (WebSockets transport) sending data. Binary data of length 373.
blazor.server.js:1 [2023-01-23T14:47:04.454Z] Trace: (WebSockets transport) sending data. Binary data of length 373.
blazor.server.js:1 [2023-01-23T14:47:04.870Z] Trace: (WebSockets transport) sending data. Binary data of length 373.
blazor.server.js:1 [2023-01-23T14:47:05.255Z] Trace: (WebSockets transport) sending data. Binary data of length 373.
blazor.server.js:1 [2023-01-23T14:47:09.790Z] Trace: (WebSockets transport) data received. Binary data of length 3.`

Have enabled logging on server side and get the following when i click and events:

`VRB 15:47:03:770] [WebSocketsTransport] Message received. Type: Binary, size: 373, EndOfMessage: True.
[DBG 15:47:03:771] [DefaultHubDispatcher] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS", Arguments: [ 48, , DispatchEventAsync, 1, [{"eventHandlerId":522,"eventName":"click","eventFieldInfo":null},{"detail":1,"screenX":647,"screenY":764,"clientX":646,"clientY":684,"offsetX":64,"offsetY":13,"pageX":646,"pageY":684,"movementX":0,"movementY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":"click"}] ], StreamIds: [  ] }.
[VRB 15:47:03:772] [DefaultHubDispatcher] InvocationId null: Sending result of type 'System.Void'.
[VRB 15:47:04:455] [WebSocketsTransport] Message received. Type: Binary, size: 373, EndOfMessage: True.
[DBG 15:47:04:457] [DefaultHubDispatcher] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS", Arguments: [ 49, , DispatchEventAsync, 1, [{"eventHandlerId":522,"eventName":"click","eventFieldInfo":null},{"detail":1,"screenX":620,"screenY":770,"clientX":620,"clientY":690,"offsetX":37,"offsetY":19,"pageX":620,"pageY":690,"movementX":0,"movementY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":"click"}] ], StreamIds: [  ] }.
[VRB 15:47:04:458] [DefaultHubDispatcher] InvocationId null: Sending result of type 'System.Void'.
[VRB 15:47:04:871] [WebSocketsTransport] Message received. Type: Binary, size: 373, EndOfMessage: True.
[DBG 15:47:04:871] [DefaultHubDispatcher] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS", Arguments: [ 50, , DispatchEventAsync, 1, [{"eventHandlerId":522,"eventName":"click","eventFieldInfo":null},{"detail":2,"screenX":620,"screenY":770,"clientX":620,"clientY":690,"offsetX":37,"offsetY":19,"pageX":620,"pageY":690,"movementX":0,"movementY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":"click"}] ], StreamIds: [  ] }.
[VRB 15:47:04:872] [DefaultHubDispatcher] InvocationId null: Sending result of type 'System.Void'.
[VRB 15:47:05:256] [WebSocketsTransport] Message received. Type: Binary, size: 373, EndOfMessage: True.
[DBG 15:47:05:257] [DefaultHubDispatcher] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS", Arguments: [ 51, , DispatchEventAsync, 1, [{"eventHandlerId":522,"eventName":"click","eventFieldInfo":null},{"detail":3,"screenX":619,"screenY":767,"clientX":618,"clientY":687,"offsetX":36,"offsetY":16,"pageX":618,"pageY":687,"movementX":0,"movementY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":"click"}] ], StreamIds: [  ] }.
[VRB 15:47:05:259] [DefaultHubDispatcher] InvocationId null: Sending result of type 'System.Void'.
[VRB 15:47:09:790] [HubConnectionContext] Sent a ping message to the client.
[VRB 15:47:09:790] [WebSocketsTransport] Sending payload: 3 bytes.
[VRB 15:47:10:768] [WebSocketsTransport] Message received. Type: Binary, size: 3, EndOfMessage: True.
[VRB 15:47:12:792] [HubConnectionContext] Sent a ping message to the client.
[VRB 15:47:12:792] [WebSocketsTransport] Sending payload: 3 bytes.`

I have the rest of the log files, can upload if needed

### Expected Behavior

Render loop should not stop.

### .NET Version

7.0.100

**Comment by xsIceman** [comment]
I am struggling to create a simple application that reproduces the bug. @Tratcher is there someone that could give some hits to what i should try from looking at the logs?

**Comment by Nick-Stanton** [comment]
Hi @xsIceman, when you set a breakpoint in the C# code in your component, how far along do you get?

**Comment by xsIceman** [comment]
thanks for feedback @Nick-Stanton 
When I get into this situation I do not get any of my code to execute. None of my component code looks to execute. In the server side logs I see that I get a message over signalR:
`[VRB 20:32:55:743] [WebSocketsTransport] Message received. Type: Binary, size: 736, EndOfMessage: True.
[DBG 20:32:55:744] [DefaultHubDispatcher] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS", Arguments: [ 53, , DispatchEventAsync, 1, [{"eventHandlerId":375,"eventName":"click","eventFieldInfo":null},{"detail":1,"screenX":73,"screenY":301,"clientX":73,"clientY":230,"offsetX":3,"offsetY":19,"pageX":73,"pageY":230,"movementX":0,"movementY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":"click"}] ], StreamIds: [  ] }.
[VRB 20:32:55:745] [DefaultHubDispatcher] InvocationId null: Sending result of type 'System.Void'.`
But it does not look like the hubdispatcher forwards this to my code.

earlier in the logs before this happens i get a number of sockets and connections stopped/disconnecting:
`[VRB 20:30:19:024] [WebSocketsTransport] Message received. Type: Binary, size: 3, EndOfMessage: True.
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L8" received FIN.
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L5" received FIN.
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L7" received FIN.
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L2" received FIN.
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L6" received FIN.
[DBG 20:30:20:024] [Connections] Connection id "0HMNVQE3HB0L8" disconnecting.
[DBG 20:30:20:024] [Connections] Connection id "0HMNVQE3HB0L7" disconnecting.
[DBG 20:30:20:025] [Sockets] Connection id "0HMNVQE3HB0L8" sending FIN because: "The client closed the connection."
[DBG 20:30:20:024] [Sockets] Connection id "0HMNVQE3HB0L5" sending FIN because: "The client closed the connection."
[DBG 20:30:20:023] [Sockets] Connection id "0HMNVQE3HB0L4" received FIN.
[DBG 20:30:20:025] [Sockets] Connection id "0HMNVQE3HB0L7" sending FIN because: "The client closed the connection."
[DBG 20:30:20:026] [Connections] Connection id "0HMNVQE3HB0L6" disconnecting.
[DBG 20:30:20:024] [Connections] Connection id "0HMNVQE3HB0L2" disconnecting.
[DBG 20:30:20:026] [Connections] Connection id "0HMNVQE3HB0L5" disconnecting.
[DBG 20:30:20:026] [Sockets] Connection id "0HMNVQE3HB0L2" sending FIN because: "The client closed the connection."
[DBG 20:30:20:026] [Connections] Connection id "0HMNVQE3HB0L4" disconnecting.
[DBG 20:30:20:029] [Connections] Connection id "0HMNVQE3HB0L4" stopped.
[DBG 20:30:20:029] [Connections] Connection id "0HMNVQE3HB0L5" stopped.
[DBG 20:30:20:029] [Connections] Connection id "0HMNVQE3HB0L7" stopped.
[DBG 20:30:20:026] [Sockets] Connection id "0HMNVQE3HB0L6" sending FIN because: "The client closed the connection."
[DBG 20:30:20:029] [Connections] Connection id "0HMNVQE3HB0L8" stopped.
[DBG 20:30:20:030] [Sockets] Connection id "0HMNVQE3HB0L4" sending FIN because: "The Socket transport's send loop completed gracefully."
[DBG 20:30:20:035] [Connections] Connection id "0HMNVQE3HB0L6" stopped.
[DBG 20:30:20:035] [Connections] Connection id "0HMNVQE3HB0L2" stopped.
[VRB 20:30:20:559] [WebSocketsTransport] Message received. Type: Binary, size: 736, EndOfMessage: True.`

**Comment by xsIceman** [comment]
have enabled .NET Framework source stepping. And i look to get stuck somewhere in RendereSynchronizationContext:
![image](https://user-images.githubusercontent.com/681524/214945903-f22f1ef9-be37-49af-989c-325576684267.png)
![image](https://user-images.githubusercontent.com/681524/214945988-5e99b4d2-f099-43cf-bd44-318013931d58.png)

**Comment by mkArtakMSFT** [comment]
@xsIceman as much as we want to, we won't be able to investigate this any further.
We think one way you can run into this issue is if you have a component which causes an infinite rendering (by rendering itself). Maybe this can be a hint to what is going on in your application to case this.
