### ISSUE TITLE
Make HttpsConnectionFilter more configurable

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#4622]
- Support multiple certificates
  - Allow certs to be specified for a given port and/or IP address
  - Allow certs to be specified for a given hostname once SNI is supported
- ~~Make allowed [SslProtocols](https://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols%28v=vs.110%29.aspx) configurable~~
- Use the options pattern (e.g. [Facebook Middleware](https://github.com/aspnet/Security/blob/6ed7d1f3c09c065c8e2c09f1cd09389947451746/src/Microsoft.AspNet.Authentication.Facebook/FacebookAppBuilderExtensions.cs)) which takes a `configureOptions` Action.

**Comment by jkotalik** [comment]
I believe this isn't relevant anymore.
