### ISSUE TITLE
Posibility to Customize Model Binding errors Key

### ISSUE THREAD

**Issue by jgarciadelanoceda** [dotnet/aspnetcore#46238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am using SuppressInferBindingSourcesForParameters for all the EP of an API.
And all the request that have a Body are defined this way:
```
[HttpPost("{Id}/MyMethod"]
public async Task<IActionResult> MyMethod(MyMethodRequest myMethodRequest)
```
The class is defined here:
```
public class MyMethodRequest
{
                [FromRoute]
		public int Id { get; set; }
		[FromBody]
		public Body BodyRequest { get; set; }
}
public class BodyRequest
{
                 public bool? Default { get; set; }
}
```

The response that ASP.NET when passing in the Body a Default that is not a bool is: 
```
{
    "errors": {
        "body.Default": [
            "Could not convert string to boolean: *. Path 'Default', line 8, position 19."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|7da03779-4ff981248d9543e6."
}
```
I have FluentValidation also applied to all the request and I am using OverridePropertyName to take out the Body part.
In FluentValidation for these cases we have to deal with Model Binding errors, the Body is null for this scenario and we have to override the PreValidate.
### Describe the solution you'd like

I just want that the response that ASP.Net gives back would be

```
{
    "errors": {
        "Default": [
            "Could not convert string to boolean: *. Path 'Default', line 8, position 19."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|7da03779-4ff981248d9543e6."
}
```

**Comment by brunolins16** [comment]
@jgarciadelanoceda I have trying to repro your scenario and I am getting something different

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-8d1838ff7a6b74a9f98cbeae3c265450-f785a7e78c580fed-00",
  "errors": {
    "BodyRequest": [
      "The BodyRequest field is required."
    ],
    "$.default": [
      "'a' is an invalid start of a value. Path: $.default | LineNumber: 1 | BytePositionInLine: 13."
    ]
  }
}
```

I believe it is something related to `FluentValidation` but I am not sure.

**Comment by brunolins16** [comment]
> I am using SuppressInferBindingSourcesForParameters for all the EP of an API.
> And all the request that have a Body are defined this way:

Just to let you know, we are working on a fix for that, so, you don't have to set `SuppressInferBindingSourcesForParameters` to `false` https://github.com/dotnet/aspnetcore/issues/46140

**Comment by jgarciadelanoceda** [comment]
Hi @brunolins16,

Thank you for your support, I have just created a new repository that is public to show this issue https://github.com/jgarciadelanoceda/WebApplication1

Please take a look that I tried to use NewtonsoftJsonValidationMetadataProvider but it does not work as I expected. I Put JsonProperty with empty value for Body and when Body.Default is not a bool value then it shows Body.Value instead of just Value

**Comment by brunolins16** [comment]
Ok, I understood what is happening and, unfortunately, I have to say it is by design ☹️.

The `Newtonsoft input formatter` will create the `ModelState` key using a combination of `ModelName + member`.

https://github.com/dotnet/aspnetcore/blob/cb780bea7a9dcb73be6750c615869bf64c30c5f2/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L303

The problem is when you are binding `FromBody` a non-top-level objects (that is your case, since you have a composite class that includes properties with different sources) the binding context will set the ModelName as your property name.

https://github.com/dotnet/aspnetcore/blob/cb780bea7a9dcb73be6750c615869bf64c30c5f2/src/Mvc/Mvc.Core/src/ModelBinding/Binders/BodyModelBinder.cs#L103

This is a behavior that have been here for years, and I am not sure if we have enough to justify a change right now.

**Comment by brunolins16** [comment]
If you really want this behavior, you might have different options, however, the easiest one is moving your `BodyRequest` property outside of the class, as a parameter.

**Comment by jgarciadelanoceda** [comment]
Thank you very much @brunolins16
I think that the solution you are proposing could be an option, but if we want all the validation of the incoming request to live within a Validator for me is better.

I do not know what to do with this issue because, I could do a very easy Work Around so it is up to you to keep this issue or just close it

**Comment by brunolins16** [comment]
I'll close for now and monitor if we have more engagements related to this. Thanks. Feel free to reopen or file another issue if you need.
