### ISSUE TITLE
Disable named pipes transport on non-Windows platforms

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#46231]
Kestrel now supports a named pipes transport. However, the .NET named pipes API supports Windows and Unix/macOS. On those platforms, the win32 named pipes API is replaced with Unix domain sockets. There are subtle behavior differences.

For simplicity, I think we should disable named pipes transport on non-Windows platforms. Someone who wants to be cross-platform can use UDS directly with `ListenUnixSocket`.

* Don't add named pipe transport or service if not on Windows. Either throw an error or write a log message. Probably throw an error.
* Place the OS-supported attribute with Windows on `KestrelServerOptions.ListenNamedPipe` API?
* Skip all existing named pipe transport tests
* Add test that verifies that adding a named pipe transport fails on non-Windows platforms.

**Comment by adityamandaleeka** [comment]
This makes sense to me.

**Comment by halter73** [comment]
We should also add `[SupportedOSPlatform("windows")]` to the related APIs.
