### ISSUE TITLE
Blazor - correct approach for two-way data binding is not correct according to Visual Studio

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#46237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Modern razor editor for blazor files red underlines the correct element parameters and a hint contains the warning:

CS1502: Argument 3: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<string>' to <System.Action<string?>'

### Expected Behavior

Modern razor editor for blazor files accepts correct element parameters.

### Steps To Reproduce

Create empty blazor server project. Add this component:

```
<input type="text"
       class="form-control"
       @bind:get="Value"
       @bind:set="OnInput"
       @bind:event="oninput" />


@code {
    [Parameter]
    public string Value { get; set; } = "";

    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }


    void OnInput(string aValue)
    {
        ValueChanged.InvokeAsync(aValue);
    }
}

```

### .NET Version

7.0.102

### Anything else?

Correct two-way data binding is described [in documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0#use-bindgetbindset-modifiers-and-avoid-event-handlers-for-two-way-data-binding).

Compiler error:

![image](https://user-images.githubusercontent.com/10242002/214282385-0fb95c65-bb1a-44ac-a7f8-b558f04e8e00.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known VS issue for which a fix has been merged already and it's going to ship as part of the upcoming VS 17.4.5 release.

**Comment by mkArtakMSFT** [comment]
To add to this, if you try to build the project from CLI (dotnet build) it will succeed.
