### ISSUE TITLE
Need to pass state about rejected requests for W3C logging in Hosting

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#4624]
https://github.com/aspnet/Hosting/issues/1013 will implement W3C logging on the hosting layer.  For most requests, this is fine, though for rejected/failed requests, Kestrel will need to pass the data.

Simple implementation would be just passing a string with the log value, or we can consider passing list of key/value pairs if we want to do the formatting at the Hosting layer.

cc @Tratcher @davidfowl

**Comment by jkotalik** [comment]
@shirhatti do you have more context on this and whether it can be closed?

**Comment by shirhatti** [comment]
It is currently impossible to implement W3C access logs as a middleware since certain requests are rejected at the server layer.

**Comment by davidfowl** [comment]
I think if we do this, it's gonna be a kestrel feature. We need to decide if we want to implement it as structured logging. Like a specific log category that logs each of these fields as separate column.
