### ISSUE TITLE
Received unexpected acknowledgement for render batch

### ISSUE THREAD

**Issue by yeganehaym** [dotnet/aspnetcore#46242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i'm using stimulsoft blazor server
when I click on print and choose print in print dialog
give me this error
Received unexpected acknowledgement for render batch ….
but it's not just about stimulsoft reporter
i get that sometimes suddenly when i working with app

### .NET Version

6

**Comment by yeganehaym** [comment]
I need to mention my app is hybrid with windows form, on web version is ok

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of https://github.com/dotnet/maui/issues/12761
