### ISSUE TITLE
Allow abbreviated namespaces in components

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#46254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

This is my main component, it is a table
```cs
namespace Stand.Libraries.Website.Components;

public partial class Table<TItem> : ComponentBase
{
    [Parameter]
    public RenderFragment? TableHeader { get; set; }

    [Parameter]
    public RenderFragment<TItem>? TableRow { get; set; }

    [Parameter, AllowNull]
    public IReadOnlyList<TItem> Items { get; set; }
}
```
I'm creating a sub component now, I want it to be only for Table
```cs
namespace Stand.Libraries.Website.Components.Table;

public partial class Tr : ComponentBase
{
    
}
```

I came up with an idea that I can trigger my component like this:
```razor
<Table.Tr>
  Bla bla
</Table.Tr>
```
Unfortunately it doesn't work so I have to do this:
```razor
<Stand.Libraries.Website.Components.Table.Tr>
  Bla bla
</Stand.Libraries.Website.Components.Table.Tr>
```

I know that I can name TableTr but having many such components it looks ugly, example:
```razor
<Table>
  <TableRow>
   <TableRowTr>
    <TableRowTrTd>
    </TableRowTrTd>
   </TableRowTr>
  </TableRow>
</Table>
```
Wouldn't it be smoother like this?:
```razor
<Table>
  <Table.Row>
   <Table.Row.Tr>
    <Table.Row.Tr.Td>
    </Table.Row.Tr.Td>
   </Table.Row.Tr>
  </Table.Row>
</Table>
```
OR:
```razor
<Table>
  <Table.Row>
   <Table.Tr>
    <Table.Td>
    </Table.Td>
   </Table.Tr>
  </Table.Row>
</Table>
```

This gives us nicely structured data in autocomplete and less clutter in the code. What do you think about this? I think there should be some isolation in the components, with larger projects it gets messy in the names.

**Comment by Nick-Stanton** [comment]
Thanks for reporting this issue. We'll consider your feedback as part of an existing issue [here](https://github.com/dotnet/razor/issues/7670).
