### ISSUE TITLE
Google authentication not working

### ISSUE THREAD

**Issue by Chandrasiris** [dotnet/aspnetcore#46256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using .Net Core 3.1

I am trying to make enable Google authentication for my web app. It raised several issues

1. It works fine for https://localhost:41514/signin-google. 

but if I change Authorized redirect URIs  with my real domain "https://kl.ewisdom.lk/signin-google" it raises "Error 400: redirect_uri_mismatch" with the message "Request details: redirect_uri=http://kl.ewisdom.lk/signin-google"

2. Then I added an extra url to Authorized redirect URIs as "http://kl.ewisdom.lk/signin-google" and now it prompts the Google sign In window as I wish. 
But after signed in it raises this error " No webpage was found for the web address: https://kl.ewisdom.lk/signin-google? ". Actually in my project I don't have a such a page and I need to redirect it to the "https://kl.ewisdom.lk/Account/Callback".

I checked  my startup.cs and I can find  "app.UseAuthentication();" 

I am trying to resolve it from 3 days but still I can't figure out why is this happening. If you can please help me on this issue. It is a great help.

### Expected Behavior

I expect to redirect the user into the right page ( https://kl.ewisdom.lk/Account/Callback ) after the successful Google Sign In.

### .NET Version

3.1

**Comment by Tratcher** [comment]
> "Request details: redirect_uri=http://kl.ewisdom.lk/signin-google"

The generated url is using http, not HTTPS. Did you access the site using HTTP? Or is it behind a TLS terminating proxy? Google auth will only work over HTTPS.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

`/signin-google` is a path handled by the auth components. It will redirect back to the app endpoint afterwards.

**Comment by Chandrasiris** [comment]
Thank you very much for considering my issue. I am using https and my home page is " https://kl.ewisdom.lk/ "

**Comment by Chandrasiris** [comment]
Please refer to the screen shots of my issue and my settings.
[https://prnt.sc/cNlJUxcQ8a55](url)

[https://prnt.sc/xxAgGbttx4wj](url)

**Comment by Tratcher** [comment]
Please share your startup.cs so we can see how this is configured.

**Comment by Chandrasiris** [comment]
Ok. 
[startup.txt](https://github.com/dotnet/aspnetcore/files/10528533/startup.txt)

**Comment by Tratcher** [comment]
Unrelated, but avoid this:
```
            services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue; // In case of multipart
            });
```
https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-7.0

**Comment by Tratcher** [comment]
Ok, I don't see any config that would affect this. The redirect from HTTPS to HTTP normally happens when you're behind a reverse proxy and not fixing up the request fields accordingly. 

The following gives some advice about this scenario. I especially recommend the troubleshooting section at the bottom.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0
