### ISSUE TITLE
Add NamedPipeTransportOptions.ListenerQueueCount property

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#46268]
## Background and Motivation

There are performance benefits of multiple listen queues with named pipes. This property allows someone to customize the number.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes;

public sealed class NamedPipeTransportOptions
{
+    public int ListenerQueueCount { get; set; } = Math.Min(Environment.ProcessorCount, 16);
}
```

## Usage Examples

```csharp
services.Configure<NamedPipeTransportOptions>(o =>
{
    o.ListenerQueueCount = 2;
});
```

**Comment by halter73** [comment]
API Review Notes

- This is similar to `SocketTransportOptions.IOQueueCount`. Do we have any better naming suggestions? `ListenerLoopCount`? `AcceptLoopCount`? No.
- Namespace looks good.

API Approved as proposed!

```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes;

public sealed class NamedPipeTransportOptions
{
+    public int ListenerQueueCount { get; set; } = Math.Min(Environment.ProcessorCount, 16);
}
```

**Comment by adityamandaleeka** [comment]
Looks like this was merged in preview 2. Closing this issue.
