### ISSUE TITLE
ArgumentException in Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer

### ISSUE THREAD

**Issue by cincuranet** [dotnet/aspnetcore#46261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`RouteHandlerAnalyzer` throws exception when using methods from class from different namespace in minimal API.

Similar to #41794, but still happening.

### Expected Behavior

No errors/warnings.

### Steps To Reproduce

_csproj_:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

_Program.cs_:
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Test.Handlers;
using System.Threading.Tasks;

namespace Test
{
    public class Program
    {
        public static async Task Main()
        {
            var builder = WebApplication.CreateBuilder();
            using var app = builder.Build();
            app.MapGet("/foo", Foo.FooBar);
            await app.RunAsync("http://*:6006");
        }
    }
}
```

_Foo.cs_:
```
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace Test.Handlers
{
    public sealed class Foo
    {
        public static Task<IResult> FooBar() => Task.FromResult(Results.Content(string.Empty, "text/plain"));
    }
}
```

Doing `dotnet clean` and then `dotnet publish` results in:
```
MSBuild version 17.5.0-preview-22620-02+a6f6699d1 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NET
SDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\repos\XXX\XXX\XXX.csproj]
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.ArgumentException
' with message 'Syntax node is not within syntax tree'. [D:\repos\XXX\XXX\XXX.csproj]
  XXX -> D:\repos\XXX\XXX\bin\Debug\net6.0\XXX.dll
  XXX -> D:\repos\XXX\XXX\bin\Debug\net6.0\publish\
```

### Exceptions (if any)

System.ArgumentException

### .NET Version

7.0.200-preview.22628.1, 7.0.100

**Comment by captainsafia** [comment]
@cincuranet Our analyzers ship as part of the ASP.NET runtime. That means that in order to take advantage of the bug fix, you're application will need to be targeting the net7.0 target framework. Try updating this and let me know if that removes the issue.

If there is enough interest in backporting this fix, we can backport it to the 6.0 runtime.

**Comment by cincuranet** [comment]
@captainsafia Using `net7.0` solves the issue. Having it in `net6.0` would be nice to have, especially because it's LTS. But given it's "just a warning" I would not cry if it's not backported. ;)

**Comment by captainsafia** [comment]
> @captainsafia Using `net7.0` solves the issue. Having it in `net6.0` would be nice to have, especially because it's LTS. But given it's "just a warning" I would not cry if it's not backported. ;)

Great! I'll move this to the backlog for now. Anyone who runs into the issue can give it a thumbs up to indicate this is worthwhile to backport.

One of the challanges with backporting is the analyzer codebase has chagned a fair bit between 6.0 and 8.0 so their might be some spelunking to do to find the actual item.
