### ISSUE TITLE
Issue with building and publishing Asp.Net 4 website in docker file

### ISSUE THREAD

**Issue by jsurana** [dotnet/aspnetcore#46264]
I have Asp.Net 4 website which does not have .sln and .csproj file but I have website.publishproj file. Can I build and publish files in IIS using website.publishproj file? I tried below docker file but when I use msbuild command with .publishproj file it is not generating published files at /out directory.

Can anyone help me if that's correct approach?

![image](https://user-images.githubusercontent.com/31936315/214333501-0344f90b-0930-4449-b44e-be28d4f1e048.png)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net** tag.
