### ISSUE TITLE
HTTP/1.1 Allow Response Trailer Headers

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#4627]
Now (shortly?) reading request header trailers #619; ability to add them to chunked encoding responses?

~~Currently supported by [`System.Web`](https://msdn.microsoft.com/sr-latn-rs/library/system.net.http.headers.httpresponseheaders.trailer%28v=vs.110%29.aspx)~~ (Misleading)

Don't think browsers pay attention to them; but some discussion on https://github.com/whatwg/fetch/issues/34 as to their importance for CDNs etc; and whether to include them in the fetchapi

**Comment by NickCraver** [comment]
Is there any update in the plans for this? I'm just curious if `http/1.1` support is planned. I was trying to get them to work in MiniProfiler which is an awesome use case, but the default experience for devs locally is http/1.1 and http/2 is broken in the current preview (see https://github.com/aspnet/AspNetCore/issues/8952).

**Comment by davidfowl** [comment]
This is done
