### ISSUE TITLE
Support simple parameter-binding scenarios in RequestDelegateGenerator

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#46275]
- [x] Support parameter binding for well-known types (HttpContext, ClaimsUser, etc)
- [x] Support parameter binding for simple types derived from the Route (`FromRoute`)/Query/Header (work in progress #46545 )
- [x] Support parameter binding for parameters inferred from a route name

**Comment by JamesNK** [comment]
Remember to take into account `AsParametersAttribute`.

Also, `FromRouteAttribute` can override the name.

**Comment by captainsafia** [comment]
> Remember to take into account AsParametersAttribute.

Yep! It's tracked in https://github.com/dotnet/aspnetcore/issues/46336 since it supersedes some associated with this.

> Also, FromRouteAttribute and friends can override the name.

👍🏽

**Comment by captainsafia** [comment]
Update: Support for special types is merged in. @mitchdenny will take a look at the second task item as a pre-req for supporting `TryParse`.
