### ISSUE TITLE
Add JwtBearerOptions to achieve Multi-Tanency in .NET 6 During Runtime

### ISSUE THREAD

**Issue by AdeelAhmad01** [dotnet/aspnetcore#46281]
I am trying to achieve multi-tenancy in  **AspNetCore 6** application during runtime.

I am adding schema information by using **AddJwtBearer** method of **AuthenticationBuilder** class. Everything work perfect if I add that schema from appsettings.json, but issue came up when I try to register that schema while application is in running state. I try to add **JwtBearerOptions** on the fly but unable to detect that schema inside **AuthorizationHandlerContext** 

I have a use case in which we register tenants dynamically, without restarting the application. 
I followed following links
[Policy-based authorization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0)
[ASP.Net Core & Angular OpenID Connect using Keycloak](https://medium.com/@xavier.hahn/asp-net-core-angular-openid-connect-using-keycloak-6437948c008)

The code looks like this: 

```csharp
builder.Services.AddAuthentication(options => {
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(o => {
    o.Authority = Environment.GetEnvironmentVariable("OID_ISSUER") ?? builder.Configuration["Jwt:Authority"];
    o.Audience = builder.Configuration["Jwt:Audience"];
    o.RequireHttpsMetadata = false;
});
```

**Is there anyway to add multi tenancy support on the fly, without restarting application? Please advise**

@jeffhandley @Tratcher

**Comment by captainsafia** [comment]
Triage: Can you share a full repro of the problem? It's unclear what the issue is from the sample that you provided.

> I try to add JwtBearerOptions on the fly but unable to detect that schema inside AuthorizationHandlerContext

Do you have a stack trace that you are receiving here?

**Comment by AdeelAhmad01** [comment]
Hi @captainsafia , I do not have stack trace for that, as it is not giving any error but also not working as expected.
As I have scenario of **multi-tenant** Auth, and I need to Scheme dynamically based on tenant and every tenant have its own options.

As mentioned in this  [Dynamic Scheme Example](https://github.com/aspnet/AuthSamples/blob/master/samples/DynamicSchemes/Controllers/AuthController.cs)

They resolved `IAuthenticationSchemeProvider ` through constructor and add the scheme dynamically by using **AddScheme** method.
Like this :
`_schemeProvider.AddScheme(new AuthenticationScheme(scheme, scheme, typeof(SimpleAuthHandler)));`,

Problem is, by using using **AddScheme** method, I am unable to pass options of that scheme. Is there any way to add scheme with options the same way we use **AddJwtScheme** extended by **AuthenticationBuilder** class.

I am implementing this code, which could solve my problem, but **IAuthenticationBuilder** is deprecated for .NET 6
`    public async Task<IActionResult> Authenticate()
    {
        using (var scope = _serviceScopeFactory.CreateScope())
        {
            var authenticationBuilder = scope.ServiceProvider.GetRequiredService<IAuthenticationBuilder>();
            authenticationBuilder.AddJwtBearer("Bearer", options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = Configuration.GetValue<string>("Jwt:Issuer"),
                    ValidAudience = Configuration.GetValue<string>("Jwt:Audience"),
                };
            });
        }
        return OK("OK")
    }`

**Comment by captainsafia** [comment]
> I am implementing this code, which could solve my problem, but IAuthenticationBuilder is deprecated for .NET 6

Triage: The `IAuthenticationBuilder` is not a public interface that exists in the ASP.NET Core API. @HaoK Can provide more insights here and link to a prior issue.

**Comment by HaoK** [comment]
Duping this against https://github.com/dotnet/aspnetcore/issues/44804 which was filed earlier so we'll use the earlier one for tracking
