### ISSUE TITLE
Update CreateSlimBuilder for Microsoft.Extensions.Hosting.Host.CreateEmptyApplicationBuilder

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#46293]
Once https://github.com/dotnet/runtime/issues/81280 is implemented, we should take advantage of this new API in CreateSlimBuilder:

https://github.com/dotnet/aspnetcore/blob/4d75ee9a7fbad112e29b8a1d77c7d96965f62b40/src/DefaultBuilder/src/WebApplicationBuilder.cs#L105-L113

This should cut about **1.3 MB** of a NativeAOT published Windows x64 app. Prototyping this change on my machine results the [Benchmark app](https://github.com/aspnet/Benchmarks/tree/main/src/Goldilocks):

**Before**
15.2 MB (16,007,168 bytes)

**After**
13.9 MB (14,593,024 bytes)

And **1.4MB** on Linux x64:

**Before**
18.6 MB (19,601,424 bytes)

**After**
17.2 MB (18,132,768 bytes)

**Comment by adityamandaleeka** [comment]
Marking this blocked until the runtime API is ready
