### ISSUE TITLE
Inconsistent translation of template strings

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#46301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As described in [Bug 1719748, [DevExE2E] [Loc] 'ASP.NET Core Web App' and 'ASP.NET Core Razor Pages' aren't localized.](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1719748>), some strings in the German `RazorPagesWeb-CSharp` template are shown in English. The problem is actually inconsistent use and capitalization of "Web App", "Razor Pages", and "razor pages" in our English sources and inconsistent translations from the loc team.

### Expected Behavior

These terms should be consistently capitalized and translated (or not). I asked the "translated (or not)" question in [LOC QUESTIONS 771866, [SW] How to handle translation of "Razor Pages" and "Web App"?](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/771866/).

### Steps To Reproduce

1. Prepare DE OS, install VS language packs and apply.
2. Install ASP.NET and web development workload
3. Open VS -> Create a new project -> Search 'asp'

## Note:

1.It isn't a regression issue, also repro on Version 17.4.4.
2.Repro VM: 172.16.195.94.

## Expected result:

All Strings should be localized.

## Actual result:

'ASP.NET Core Web App' and 'ASP.NET Core Razor Pages' aren't localized.

![image](https://user-images.githubusercontent.com/6431421/215203323-db76b3ee-cb2b-4438-a63d-0acda74f2bac.png)

### Exceptions (if any)

n/a

### .NET Version

8.0.0-alpha1

### Anything else?

n/a

**Comment by dougbu** [comment]
This bug is primarily about tracking [LOC QUESTIONS 771866, [SW] How to handle translation of "Razor Pages" and "Web App"?](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/771866/) for now. Consistently capitalizing "Razor Pages" can wait until we understand whether the term should be translated for example.

**Comment by dougbu** [comment]
Guidance so far is that `"Razor Pages"` is a term and therefore we should capitalize it when referring to the framework feature. We should also lock it (prevent translation) using loc comments.

Question on "web app" remains open.

**Comment by dougbu** [comment]
Guidance from the loc team is to capitalize "Progressive Web App" or "Progressive Web Application" and to lock the entire term (keeping it in English in all translations).

When we mean "web app" in the generic sense i.e., when it's _not_ a proper noun, do not capitalize it or lock the term. We may need loc comments for this case to let translators know the term should be translated in full.

**Comment by dougbu** [comment]
Over to you @wtgodbe. I didn't add the loc comments for this. See https://aka.ms/commenting and samples already in our templates e.g. search for `\.comment":` in the `*.json` files. While it may be sufficient to capitalize these words as described in comments above, locking the "this is a term" ones will help the loc team. Making it explicit that "web app" lowercase using `"_{some name}.comment": "'web app' should be translated in every language"` will also help.

(There are more loc comments either using the `Locked` keywords or plain English in the `*.wxl` files too.)

/cc @mkArtakMSFT

**Comment by hishamco** [comment]
@dougbu is this still a valid bug?

**Comment by dougbu** [comment]
> @dougbu is this still a valid bug?

The linked loc work item has been closed for ages. So, probably not valid to leave this open. I defer to @wtgodbe because I don't know what may have happened in the loc space over the last year.

Suggesting you close this @wtgodbe unless there's something you need this issue to track.
