### ISSUE TITLE
When session and cookie timeout call to Azure B2C authorize endpoint fails with CORS error.

### ISSUE THREAD

**Issue by mschaefer-gresham** [dotnet/aspnetcore#46305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to implement the [BFF Pattern](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3917). My frontend is a React SPA. Per the BFF pattern, there is no javascript library (e.g. MSAL.js) for auth and no tokens in the browser - only the cookie from the server. My server is acting as a Backend-For-Front-End Gateway. It handles the cookie and token management. I'm using Microsoft.AspNetCore.Authentication.OpenIdConnect. And it proxies API requests using YARP. 

The server is configure using:

```
builder.Services.Configure<ForwardedHeadersOptions>(options =>
        {
            options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
        });
       
        builder.Services.AddHttpLogging(options =>
        {
            options.LoggingFields = HttpLoggingFields.RequestPropertiesAndHeaders;
        });
        
        // Configure Session
        builder.Services.AddSession(options =>
        {
            options.IdleTimeout = TimeSpan.FromMinutes(config.SessionTimeoutInMin);
        });
        
        // Configure XSRF Token
        builder.Services.AddAntiforgery(setup =>
        {
            setup.HeaderName = "X-XSRF-TOKEN";
        });
        
        // Configure Distributed Sql Cache
        builder.Services.AddDistributedSqlServerCache(options =>
        {
            options.ConnectionString = builder.Configuration.GetConnectionString("MyServer");
            options.SchemaName = builder.Configuration["TokenCache:SchemaName"];
            options.TableName = builder.Configuration["TokenCache:TableName"];
            options.DefaultSlidingExpiration = TimeSpan.FromMinutes(config.CookieTimeoutInMin);
        });
        
        // Configure Authorization
        builder.Services.AddAuthorization(options =>
        {
            options.AddPolicy("AuthenticatedUserPolicy", policy =>
            {
                policy.RequireAuthenticatedUser();
            });
        });
       
        // Configure Authentication
        builder.Services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie(options =>
        {
            options.ExpireTimeSpan = TimeSpan.FromMinutes(config.CookieTimeoutInMin);
            options.SlidingExpiration = true;
            options.Cookie.MaxAge = options.ExpireTimeSpan;
            options.Cookie.SameSite = SameSiteMode.Strict;
            options.EventsType = typeof(GatewayCookieAuthenticationEvents);
        })
        .AddOpenIdConnect(options =>
        {
            options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.Authority = config.Authority;
            options.ClientId = config.ClientId;
            options.UsePkce = true;
            options.ClientSecret = config.ClientSecret;
            options.ResponseType = OpenIdConnectResponseType.Code;
            options.SaveTokens = false;
            options.GetClaimsFromUserInfoEndpoint = config.QueryUserInfoEndpoint;
            options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;
            options.NonceCookie.SecurePolicy = CookieSecurePolicy.Always;
            options.RequireHttpsMetadata = false;
            options.CallbackPath = "/signin-oidc";
            options.SignedOutCallbackPath = "/signout-callback-oidc";
            // https://github.com/dotnet/aspnetcore/issues/10281
            options.MaxAge = TimeSpan.FromMinutes(config.SessionTimeoutInMin);
            var scopes = config.Scopes;
            var scopeArray = scopes.Split(" ");
            foreach (var scope in scopeArray)
            {
                options.Scope.Add(scope);
            }
            options.Events.OnTokenValidated = (context) =>
            {
                var tokenHandler = context.HttpContext.RequestServices.GetRequiredService<TokenHandler>();
                tokenHandler.HandleToken(context);
                return Task.FromResult(0);
            };
            options.Events.OnRedirectToIdentityProvider = (context) =>
            {
                // // workaround for CORS error commented out                
                // // https://stackoverflow.com/questions/48214686/trying-to-change-oidc-onredirecttoidentityprovider-from-302-to-401
                // if (config.ApiPaths.Any(path => context.Request.Path.StartsWithSegments(path)))
                // {
                //     if (context.Response.StatusCode == (int)HttpStatusCode.OK)
                //     {
                //         context.Response.StatusCode = 401;
                //     }
                //     context.HandleResponse();
                // } 
                context.ProtocolMessage.SetParameter("prompt", "login");
                return Task.CompletedTask;
            };
```

Logging in and logging out from the SPA work just fine. The issue occurs when the cookie and session timeout (they are set to be the same). On the first API call after the session timeout the server ends up in the OnRedirectToIdentityProvider event handler which I assume is the result of the server initiating a call to the authorize endpoint that I see in the browser. But this always results in a CORS error:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/94627216/212531656-a778b8ba-e32b-4ef0-aeb6-c86c265a621d.png">

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/94627216/212531695-21c040e4-d1cd-4cd0-86b3-43d4569381b7.png">

When login or logout is initiated from the frontend I don't get these CORS errors - only in this case when the call to /authorize is initiated from the server. To handle the scenario I return a 401 from OnRedirectToIdentityProvider (see commented out workaround above). This prevents the call to the authorize endpoint. I then handle the 401 in the frontend, redirect the browser to the login endpoint, and everything works fine.

I have forward header configured. Here is the http logging that occurs from the beginning of the first API call that occurs after the cookie expires:

```[08:15:44 INF] Request starting HTTP/1.1 GET https://localhost:8080/api/smart-search-filters/r/preferences - -
[08:15:44 INF] Request:
Protocol: HTTP/1.1
Method: GET
Scheme: https
PathBase: 
Path: /api/smart-search-filters/r/preferences
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Connection: keep-alive
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: [Redacted]
Upgrade-Insecure-Requests: [Redacted]
sec-fetch-dest: [Redacted]
sec-fetch-user: [Redacted]
sec-fetch-mode: [Redacted]
sec-fetch-site: [Redacted]
sec-ch-ua-platform: [Redacted]
sec-ch-ua-mobile: [Redacted]
sec-ch-ua: [Redacted]
[08:15:44 INF] Request RemoteIp: ::1
[08:15:44 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[08:15:44 INF] AuthenticationScheme: OpenIdConnect was challenged.
[08:15:44 INF] Request finished HTTP/1.1 GET https://localhost:8080/api/smart-search-filters/r/preferences - - - 302 0 - 2.8930ms
```

Why am I getting this CORS error when it is initiated from the server? If implement the workaround above and return a 401 instead, and then redirect the browser to login, everything works fine.

### Expected Behavior

If the server initiates a call to the authorize endpoint when a request arrives after the session and cookie expire, then the call to the authorize endpoint does not result in a CORS error. 

### .NET Version

.NET 7

**Comment by mschaefer-gresham** [comment]
Any update on this?

**Comment by mschaefer-gresham** [comment]
Any update on this?

**Comment by mschaefer-gresham** [comment]
Following up on this again. Will someone be able to look at this?

**Comment by mschaefer-gresham** [comment]
Following up on this yet again. An update would be appreciated.

**Comment by sejlermonster** [comment]
Kinda related to: https://github.com/dotnet/aspnetcore/issues/9039
Though in 9039 it is not wanted behavior for an ApiController to return a redirect which i actually agree with.

So to sum up your issue:
- You call "/preferences" endpoint but with no valid cookie
- Cookie authentication middleware returns 302 and redirects to your loginpath
- Your get CORS error

My guess is this issue is caused by a fetch call from your react SPA app which is then redirected to a GET on your login path? CORS rules for your AD does not allow GET request (and it also wouldn't really make sense). Wouldn't you need to make your SPA application navigate to the login page not just make a fetch request towards the login endpoint.  
Generally it would say that a 401 response (as is your work around now) would make the most sense. Then navigate to your login path on your backend if you get a 401 response.

If this is not the case, can you give more details on your React apps behavior? For example the request made against the /preferences endpoint.

**Comment by mschaefer-gresham** [comment]
@simonmoriat thank you for the response. When the react app loads for the first time we are careful not to make an api call until our route guard checks our auth/user endpoint in the server where we validate if the user is authenticated using `user.Identity.IsAuthenticated` in the controller. We check the response of auth/user in the React app. If the user is not authenticated then we navigate to the login endpoint:

```
public static login(returnUrl: string) {
        window.location.href = 'auth/login';
}
```

The scenario in which we have the problem is when you leave the app idle until the cookie times out and then makes an api call. In this case we don't check the auth/user endpoint since our route guard is not invokved. We don't validate auth/user before every api call - only in the route guard. In this case, a request is made to the /preferences endpoint and there is not a valid cookie. This causes the server to fall into the OnRedirectToIdentityProvider handler, then then tries to reach the /authorize endpoint. This results in a CORS error. As far as I can tell this redirect is being initiated by the server and is part of the /preferences request. 

Is this the same as [9039](https://github.com/dotnet/aspnetcore/issues/9039). Looks like I'm using the same workaround that was proposed there. 

Why does this result in a CORS error? Is it expected?

**Comment by simonmoriat** [comment]
So when you first enter your page, you navigate to the URL of your identity provider using window.location.href. This works.

Later when the token lifetime is up your make a API call to /preferences. The library then returns a redirect (302 found) for your login path because you were not authenticated. But here you are not navigating to the URL of your identitiy provider your are making a API request, maybe using fetch or axios? This would then result in an API request (not a navigation to the site) towards your login path. 
The CORS error is caused by missing cors response header from your AD. Also it would make no sense to make the API request, because you need to navigate to the path to actually login.  (maybe read about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS if this concept is new to you)

So returning af 302 found from your API controller is generally not wanted. Here you want to receive a 401 unauthorized and then your client SPA app can navigate to the identity provider, for example using  window.location.href = 'auth/login';

**Comment by mschaefer-gresham** [comment]
@simonmoriat if read you correctly, then the "workaround" I'm using (shown below) to return a 401 in this case is the recommended way to deal with this issue?

```
options.Events.OnRedirectToIdentityProvider = (context) =>
            {
                if (config.ApiPaths.Any(path => context.Request.Path.StartsWithSegments(path)))
                {
                     if (context.Response.StatusCode == (int)HttpStatusCode.OK)
                     {
                         context.Response.StatusCode = 401;
                     }
                     context.HandleResponse();
                } 
                context.ProtocolMessage.SetParameter("prompt", "login");
                return Task.CompletedTask;
            };
```
