### ISSUE TITLE
Cannot build ASP.NET Core 7 app for Raspberry Pi 4

### ISSUE THREAD

**Issue by mu88** [dotnet/aspnetcore#46306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey 👋🏻

I’ve been using the Docker image `mu88/shopandeat:latest` (an ASP.NET Core app) for years on my Raspberry Pi 4. One month ago, I switched to ASP NET Core 7.0 and everything worked smoothly.

Last week I made a little fix in the app and created a new version of `mu88/shopandeat:latest`. When trying to pull this image on my Raspi via docker pull mu88/shopandeat:latest, this fails with:
```
latest: Pulling from mu88/shopandeat
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Which is strange because when logging into Docker Hub it seems to be okay:
![image](https://user-images.githubusercontent.com/4560672/215259657-88e22531-cf62-4eeb-afdc-52b512993f4c.png)

I'm building my app via GitHub Actions:
- [`CI.yml`](https://github.com/mu88/ShopAndEat/blob/main/.github/workflows/CI.yml)
- [`Release.yml`](https://github.com/mu88/ShopAndEat/blob/main/.github/workflows/Release.yml)
- [`Dockerfile`](https://github.com/mu88/ShopAndEat/blob/main/ShopAndEat/Dockerfile)

So I've opened [this issue](https://forums.docker.com/t/cannot-pull-latest-image-on-raspberry-pi-4/134188) in the Docker community forum. After some back and forth we discovered that when setting the [`platform`](https://docs.docker.com/engine/reference/commandline/buildx_build/#platform) parameter for `docker build` to `linux/arm64` or `linux/arm64/v8`, `dotnet build` fails with cryptic errors in the .NET compilation part of my `Dockerfile`:
```
#18 [build 12/12] RUN dotnet build "ShopAndEat.csproj" -c Release -o /app/build
#18 5.256 MSBuild version 17.4.1+9a89d02ff for .NET
#18 14.52   Determining projects to restore...
#18 27.92   All projects are up-to-date for restore.
#18 32.74 /usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(120,5): error MSB4018: The "AllowEmptyTelemetry" task failed unexpectedly. [/src/BizLogic/BizLogic.csproj]
#18 32.74 /usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(120,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/src/BizLogic/BizLogic.csproj]
#18 32.75 /usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(120,5): error MSB4018:    at InvokeStub_AllowEmptyTelemetry.set_EventData(Object, Object, IntPtr*) [/src/BizLogic/BizLogic.csproj]
#18 32.75 /usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(120,5): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/src/BizLogic/BizLogic.csproj]
#18 32.75 /usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(120,58): error MSB4026: The "EventData=TargetFrameworkVersion=$([MSBuild]::Escape('$(TargetFrameworkMoniker)'));RuntimeIdentifier=$(RuntimeIdentifier);SelfContained=$(SelfContained);UseApphost=$(UseApphost);OutputType=$(OutputType)" parameter for the "AllowEmptyTelemetry" task is invalid. [/src/BizLogic/BizLogic.csproj]
```

I've attached the [GitHub Actions build log](https://github.com/dotnet/aspnetcore/files/10526973/1_build-ci.txt).

### Expected Behavior

I can build my ASP.NET Core app on GitHub Actions, set the `latest` tag on Docker Hub, pull it onto my Raspberry Pi 4 and successfully start the app.

### Steps To Reproduce

- Create an environment similar to GitHub Actions
- Run the CI pipeline `CI.yml`

### Exceptions (if any)

The following error occurs when build the Docker image via GitHub Actions with `--platform linux/arm64`:
```
#15 20.77 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1179,7): error MSB4018: The "MSBuild" task failed unexpectedly. [/src/DataLayer/DataLayer.csproj]
#15 20.77 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1179,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/src/DataLayer/DataLayer.csproj]
#15 20.77 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1179,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [/src/DataLayer/DataLayer.csproj]
#15 20.77 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1179,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/src/DataLayer/DataLayer.csproj]
```

### .NET Version

7.0.102

### Anything else?

- Platform information:
  - Hardware: Raspberry Pi 4
  - OS: Raspberry Pi OS / x64 / 11 (bullseye)
  - Docker version 20.10.23, build 7155243
- ASP.NET Core 7

**Comment by adityamandaleeka** [comment]
cc @richlander @MichaelSimons

**Comment by richlander** [comment]
I took a look at the images and your CI log. Is there a reason why your CI needs to run in QEMU. .NET doesn't work well in QEMU.

Can you build the image cleanly on raw metal, for both x64 and Arm64? Also, in most cases, you can build .NET images for other architectures w/o using QEMU.

**Comment by mu88** [comment]
Thank you for taking a look into my issue, @richlander ! So I've disabled the QEMU step in my GitHub Actions, but the build still fails with exactly the same MSBuild errors

**Comment by richlander** [comment]
Can you validate that it all
Works if you use a 7.0.0 or 7.0.1 SDK image?

**Comment by mu88** [comment]
|         Version of `dotnet/aspnet` | Version of `dotnet/sdk`              | QEMU enabled | GitHub Action result |
|-----------------------------------:|--------------------------------------|--------------|----------------------|
| `7.0.0-rc.2-bullseye-slim-arm64v8` | `7.0.100-rc.2-bullseye-slim-arm64v8` | No           | Failure              |
| `7.0.0-rc.2-bullseye-slim-arm64v8` | `7.0.100-rc.2-bullseye-slim-arm64v8` | Yes          | Failure              |
| `7.0.1-bullseye-slim-arm64v8`      | `7.0.101-bullseye-slim-arm64v8`      | No           | Failure              |

**Comment by richlander** [comment]
Does your code build correctly on your local machine (at the same commit)?

**Comment by mu88** [comment]
Yes, on my local Win11 machine everything is working smoothly

**Comment by richlander** [comment]
https://github.com/mu88/ShopAndEat/pull/36

**Comment by mu88** [comment]
The build is still failing on GitHub Actions with:
```
#15 [build  9/12] RUN dotnet restore "ShopAndEat/ShopAndEat.csproj"
#15 13.30   Determining projects to restore...
#15 20.14 /usr/share/dotnet/sdk/7.0.101/NuGet.targets(1179,7): error MSB4018: The "MSBuild" task failed unexpectedly. [/src/DataLayer/DataLayer.csproj]
#15 20.14 /usr/share/dotnet/sdk/7.0.101/NuGet.targets(1179,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/src/DataLayer/DataLayer.csproj]
#15 20.15 /usr/share/dotnet/sdk/7.0.101/NuGet.targets(1179,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [/src/DataLayer/DataLayer.csproj]
#15 20.15 /usr/share/dotnet/sdk/7.0.101/NuGet.targets(1179,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/src/DataLayer/DataLayer.csproj]
```

**Comment by richlander** [comment]
Remove the `platform` arg at this line: https://github.com/mu88/ShopAndEat/actions/runs/4081823724/jobs/7035554846#step:11:114

**Comment by richlander** [comment]
I made another PR for you. A colleague pointed out that my first one wasn't correct.

https://github.com/mu88/ShopAndEat/pull/37

**Comment by mu88** [comment]
Thank you @richlander for spending your precious time with my little project! I really appreciate it.

You'll notice that I've closed your PR and here's why: two days ago, I made a little fix in one of my other apps which has exactly the same setting like this one. And know what? I was able build and push it via GitHub Actions and pull and run it on my Raspi - without any issues at all.  
That's why I decided to go back to my very first `Dockerfile`'s/GitHub Action's draft and delete all existing Docker tags of `mu88/shopandeat`. And now I can build, push, pull and run this app as well again 🥳

So I don't know what happened to `mu88/shopandeat:latest`, but it somehow became corrupt 🤷🏻‍♂️

So once again a big thank you for your help!

**Comment by richlander** [comment]
No worries. All good. I really appreciate you reporting the issue. I think our guidance is actually a bit wrong so I'm going to work on that now, so thanks for the insight on that.

**Comment by richlander** [comment]
FYI: https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1470996533

**Comment by richlander** [comment]
FYI: https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/
