### ISSUE TITLE
When will be implemented injecting to class/viewModel in Blazor? 

### ISSUE THREAD

**Issue by DOWSCZ** [dotnet/aspnetcore#46311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When will be implemented injecting to class/viewModel in Blazor? It s extremely impractical to pass it to every constructor.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/18088
