### ISSUE TITLE
HubConnectionBuilder Connection to UDS (Unix Domain Socket)

### ISSUE THREAD

**Issue by DJGosnell** [dotnet/aspnetcore#46334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

SignalR can be bound to a Unix Domain Socket Via Kestrel's `ListenUnixSocket` option but it appears there is no method to connect to it with the `HubConnectionBuilder`.  I've searched up and down the documentation and not found any documented methods to connect to Kestrel in this mannor.  

The closest thing I can find is creating a custom `IConnectionFactory` and passing it to the `HubConnection` constructor along with all the other required interfaces. The interesting part is that I see there is already a `Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionFactory` but it is marked internal.

### Describe the solution you'd like

A method on the HubConnectionBuilder which accepts the a UDS endpoint or allowing to bind with a `http://unix:/` in the URL.

**Comment by DJGosnell** [comment]
The big thing I need to know: Is there is currently any documented method of connecting SignalR over a UDS?  If not, I will move onto other means, if yes, I just need to know a path forward for that.

**Comment by BrennanConroy** [comment]
> Is there is currently any documented method of connecting SignalR over a UDS

No. The extensibility is there, but of course requires a lot of custom code, and is not documented.

**Comment by DJGosnell** [comment]
That's what I really needed to know.  Should I expect any movement in this area or is it too niche a problem?

**Comment by BrennanConroy** [comment]
I think it's a bit niche for us to do too much right now. But definitely an interesting area. It'd be interesting to see what you do to make it work, if you post your steps on this issue it could be an informal documentation on how to get it to work.

You can also take a look at https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/samples/ClientSample/Tcp for an example of a custom transport.

**Comment by Alexr03** [comment]
This would definitely be a nice to have for official support for this.
In my situation, we are using SignalR for IPC, rather than our 2 apps connecting via tcp or named pipes (https://github.com/wegylexy/SignalRTunnel), we'd prefer giving them a common UDS to connect to so we can take advantage of file system permissions to secure this connection. 🥺🙏🏼

**Comment by adityamandaleeka** [comment]
> It'd be interesting to see what you do to make it work, if you post your steps on this issue it could be an informal documentation on how to get it to work.

@DJGosnell were you able to get this working, and if so, could you share your steps?

**Comment by DJGosnell** [comment]
@adityamandaleeka I ended up going in an [entirely different direction](https://github.com/Dtronix/NexNet) with this and made my own library so as to remove ASP from my dependency requirements.

**Comment by DJGosnell** [comment]
Going to close this issue as I have solved my original problem this by going another direction.
