### ISSUE TITLE
ConfigurationBuilder not support record type 

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#46345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want get section by using `GetSection` but already return null value.

### appsettings.json
```
{
   "MyData": {
         "Value1" "value1",
         "Value2" "value2",
    }
}
```

### Implement
```
var configuration = new ConfigurationBuilder()
            .SetBasePath("myBasePath")
            .AddJsonFile("appsettings.json", true, true)
            .AddEnvironmentVariables()
            .Build(); 
```

### use record for map

`public record MyData(string Value1, string Value2)`

### Access
```
var myData = _configuration.GetSection("MyData").Get<MyData>();
// my data value is null
```

### Expected Behavior

When use Class instead of record return value success.

```
public class MyData
{
    public string Value1 { get; set; }
    public string Value2 { get; set; }
}
```

### .NET Version

6.11

**Comment by mitchdenny** [comment]
This is by design. When you declare a record type, the compiler creates a constructor that takes just the arguments specified on the record and the default public constructor is removed.

**Comment by captainsafia** [comment]
@zanyar3 @mitchdenny's answer will apply to the .NET version that you're currently using. If you're willing and able to upgrade to .NET 7, the feature was added (see https://github.com/dotnet/runtime/issues/43662) there.

**Comment by zanyar3** [comment]
@captainsafia Thanks for reply,
But .NET 6 not out of support, you must fix problem on .net 6

**Comment by mitchdenny** [comment]
The behavior you are describing is by design for .NET 6.0. An additional feature was added in .NET 7.0 to support this. Even though .NET 6.0 is still in support, it's in support for the set of features it actually ships with :)

Occasionally we do back-port features to earlier releases of .NET, but I'm not sure this would meet that bar.
