### ISSUE TITLE
API for registering endpoints that render Razor components.

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46350]
This issue is part of https://github.com/dotnet/aspnetcore/issues/46393

* Provide a primitive inside Microsoft.AspNetCore.Components.Web for rendering output to HTML.
  * This is in charge of writing the output from a component into a stream/pipewriter.
* Refactor component rendering on MVC to depend on the `Microsoft.AspNetCore.Components.Endpoints` implementation.

**Comment by montyclt** [comment]
I'm not sure if it is the correct issue to ask about this, but what is the team opinion about providing a mechanism to limit the components that are registered into the endpoint for the components that are inside a directory, namespace or assembly?

For example, this allow us to register some components inside a route group and other components inside other route group:

```
builder.MapComponents(inDirectory: "/Pages");

builder.MapGroup("/Private")
    .MapComponents(inDirectory: "PrivateArea")
    .RequireAuthorization();
```

Other example is register components only in some environments:

```
builder.MapComponents(inDirectory: "/Pages");

if (env.IsDevelopment())
{
    builder.MapComponents(inDirectory: "/DebugComponents");
}
```
