### ISSUE TITLE
Render a server component into the page

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46353]
https://github.com/dotnet/aspnetcore/issues/46704 describes the general approaches.

The work in this issue covers creating a handler that can be passed in to the HtmlRenderer we plan to provide inside `Microsoft.AspNetCore.Components.Web` and registering it in DI to handle server components.

We also need to register the Blazor Server endpoints on to the page inside the ComponentEndpointsDataSource

**Comment by SteveSandersonMS** [comment]
When implementing this, make sure `RazorComponentResultExecutor` is updated to support it.

**Comment by Xyncgas** [comment]
Microservice + iframe sounds reasonable? Or mixed UI inside MAUI allows putting the server component in another webview which can be scrolled with MAUI UI
