### ISSUE TITLE
route with product/detail/{id?}-{persionKey?}-{sex?}-{price?} not work

### ISSUE THREAD

**Issue by lmxin123** [dotnet/aspnetcore#46359]
The route of my razor page project is written as product/detail/{id?} - {persionKey?} - {sex?} - {price?}, which will report that the optional parameter must end with "/"

I get error like this:

RoutePatternException: An optional parameter must be at the end of the segment. In the segment '{id?}-{persionKey?}-{sex?}-{price?}', optional parameter 'id' is followed by '-'.

Is there any way to rewrite the route and write "/" as "-"?

My razor page version is .net 6.0

**Comment by javiercn** [comment]
@lmxin123 thanks for contacting us.

Optional parameters are not supported in complex segments.
