### ISSUE TITLE
Blazor JSInterop gives me a different value between Visual Studio and deployed site on Azure VM

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/aspnetcore#46364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently my Azure VM subscription expired, so I upgraded to a newer Windows Server 2022 Datacenter Azure Edition.

My Blazor project figures out the pixel clicked by calling JSInterop:

    // get the size of the rectangle for the Canvas (button)
    var rectangle = await BlazorJSBridge.GetElementSize(JSRuntime, "CanvasButton");

    public async static Task<System.Drawing.Rectangle> GetElementSize(IJSRuntime jsRuntime, string name)
    {
        // initial value
        Rectangle rectangle = new Rectangle();

        try
        {
            // get the height and width
            int height = await jsRuntime.InvokeAsync<int>("BlazorJSFunctions.GetElementHeight", name);
            int width = await jsRuntime.InvokeAsync<int>("BlazorJSFunctions.GetElementWidth", name);
              
            // set the size of the rectangle
            rectangle = new Rectangle(0, 0, width, height);
         }
         catch (Exception error)
         {
             // Log the error
             ErrorLog errorLog = new ErrorLog();
             errorLog.ErrorText = error.ToString();
             errorLog.Method = "GetElementSize";
             errorLog.Timestamp = DateTime.Now;
             bool saved = await ErrorLogService.SaveErrorLog(ref errorLog);
         }

         // return value
         return rectangle;
     }

JavaScript code:

    GetElementHeight: function (name)
    {
        return document.getElementById(name).offsetHeight;
    },
    GetElementWidth: function (name)
    {
        return document.getElementById(name).offsetWidth;
    },

I then figure out the pixel clicked by calculating the size of the Canvas:

```html
<Styled @bind-Classname="CanvasStyle">
    position: fixed;
    top: 20vh;
    left: 5%;
    width: 60%;
    height: 64vh;    
</Styled>
```

And I am able to determine the pixel clicked by using:

                    // locals
                    int width = rectangle.Width;
                    int height = rectangle.Height;

                    // I save this to SQL and get different values between Visual Studio and IIS.
                    LogMethodCall("Canvas_Click", "Index.razor.cs - Screen Measure", width, height);

                    double widthDouble = (double) width;
                    double heightDouble = (double) height;

                    // set the screensize
                    double screenWidth = heightDouble / 64 * 100;
                    double screenHeight = widthDouble / 60 * 100;

                    // top must be reduced by 20% of the total height
                    // left must be reduced by 5% of the total width
                    int top = (int) (screenWidth * .20);
                    int left = (int) (screenHeight * .05);

                    // Set the ScreenSize so it can be used by the ColorPicker component
                    this.ScreenSize = new Rectangle(0, 0, (int) screenWidth, (int) screenHeight);

                    // local
                    Bitmap bitmap = null;

                    // get the value of x
                    int x = (int) e.ClientX - left;
                    int y = (int) e.ClientY - top;

                    // if the value for HasBrowser is true and the PixelDatabase exists
                    if (HasPixelDatabase)
                    {
                        // set the bitmap
                        bitmap = PixelDatabase.DirectBitmap.Bitmap;

                        //// x & y must now be scaled
                        double canvasWidth = (double) width;
                        double canvasHeight = (double) height;
                        double bitmapWidth = bitmap.Width;
                        double bitmapHeight = bitmap.Height;

                        // get the xScale and the yScale
                        double scaleX = bitmapWidth / canvasWidth;
                        double scaleY = bitmapHeight / canvasHeight;
                        double doubleX = (double)x;
                        double doubleY = (double)y;

                        // reset the values
                        x = (int)(doubleX * scaleX);
                        y = (int)(doubleY * scaleY);

                        // Ensure x is in range
                        x = NumericHelper.EnsureInRange(x, 1, bitmap.Width -1);

                        // Ensure y is in range
                        y = NumericHelper.EnsureInRange(y, 1, bitmap.Height -1);

                        // get the information about this pixel
                        Color color = bitmap.GetPixel(x, y);

                        // if the color exists
                        if (color != Color.Empty)
                        {
                            // Set the values
                            // Create a new instance of a 'PixelInformation' object.
                            PixelInformation pixel = new PixelInformation();

                            // set the information on the pixel
                            pixel.Color = color;
                            pixel.X = x;
                            pixel.Y = y;

                            // Send the Pixel to the ColorPicker and Show the Color picker 
                            HandleSetupColorPicker(pixel);

                            // Update
                            Refresh();
                        }
                    }

This works in Visual Studio on my machine, it works on my VM via Visual Studio and used to work on my old VM on the deployed site.

For some reason, the call to JSInterop on the deployed site now returns a different value for offsetWidth and offsetHeight.

I am kind of at a loss on how to solve this, since it worked on my previous server and still works via Visual Studio on the same server. As a test, I cranked up the memory on the server temporarily to see if that had any effect and it didn't (luckily, Azure memory is too expensive for what you get in my opinion).

Have you ever encountered wrong values via JS Interop being returned for offsetWidth or offsetHeight, or any idea why it would return different values compared to Visual Studio?

Second question, is there a C# way of getting the size of an element? There wasn't when I first wrote this code a couple years ago.

It's strange that even on the same VM I get a different value in Visual Studio.

Any guidance is appreciated, else I will just scrap the VM if I can't get it to work.

Thanks

### Expected Behavior

I would expect the call to return the same size for the HTML element rather run via Visual Studio or a deployed site.

### Steps To Reproduce

I can share the code with you, but it is a private repo. Not sure how to tell you to test this.

1. Create a Blazor project.
2.  Make a call to JS Interop to get the the size of an element.
3.  Deploy the site to a VM - IIS. Do you get the same value for offsetWidth or offsetHeight?

Thanks, I know this is kind of vague, but the error is strange since it worked on a previous server.

### Exceptions (if any)

I do not get any exceptions.

### .NET Version

.NET 7

### Anything else?

Works fine in Visual Studio 2022. It is the deployed site that returns a different value when this is called via Visual Studio versus live site on IIS.

```js
window.BlazorJSFunctions =
{
    ShowPrompt: function (message)
    {
        return prompt(message, 'Type anything here');
    },
    GetElementHeight: function (name)
    {
        return document.getElementById(name).offsetHeight;
    },
    GetElementWidth: function (name)
    {
        return document.getElementById(name).offsetWidth;
    },
    CopyText: function (text)
    {
        // original value
        var returnValue = 0;

        try
        {
            navigator.clipboard.writeText(text);

            // set to 1;
            returnValue = 1;
        }
        catch (err)
        {
            returnValue = -2;
        }  

        // return value
        return returnValue;
    }
};
```

**Comment by mkArtakMSFT** [comment]
We can't think of a way this can be caused by Blazor. It may be some browser behavior - we're not sure. We suggest posting your question to [StackOverflow](https://stackoverflow.com) forum to get help on finding the root cause of this.

**Comment by DataJuggler** [comment]
I am barred from stackoverflow for the crime of telling someone whose question I answered, which project the answer came from.

Thanks anyway.
