### ISSUE TITLE
ILogger.LogInformation write to console has miss some charactor

### ISSUE THREAD

**Issue by liugt34** [dotnet/aspnetcore#46382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
the complete message json serialized by Newtonsoft

![image](https://user-images.githubusercontent.com/8056013/215989624-95451cd0-8624-41b0-bed1-bb009ff37185.png)

but when i use  ILogger<AuditLogFilterAttribute>.LogInformation method ,it has missed the right brace

![image](https://user-images.githubusercontent.com/8056013/215989358-51f4222e-ddcb-4518-95aa-e04188fe22d0.png)

### Expected Behavior

console write complete string message

### .NET Version

 5.0.8

**Comment by liugt34** [comment]
the complete json string 
`{
    "traceIdentifier": "0HMO45HGLUH99:00000003",
    "method": "POST",
    "controller": "SpreadsheetSeal",
    "action": "Add",
    "requestBody": {
        "input": {
            "spreadsheetId": "5115faf4-4670-4a4d-821b-97ffd8baa53d",
            "formId": "0be291ec-cb7c-4539-b5c5-a5982a5c17ad",
            "jobId": null,
            "options": [{
                    "pageNumber": 1,
                    "sheetName": "string",
                    "cellKey": "string",
                    "sealType": 0,
                    "left": 0.0,
                    "top": 0.0,
                    "width": 0.0,
                    "height": 0.0,
                    "sealId": "fc710e8c-a88d-43c6-81fe-cd2278e0f740",
                    "signImageBase64": null,
                    "remark": "string"
                }
            ]
        }
    },
    "path": "/fullprocess/api/SpreadsheetSeal/Add",
    "query": "",
    "address": {
        "remoteIP": "::1",
        "realIP": null,
        "forwardedFor": null,
        "proxyIP": null
    },
    "responseBody": "{\"success\":true,\"code\":0,\"errors\":null}",
    "statusCode": 200,
    "creatorId": "9e1fda21-69db-47b4-ba42-9cd8a4495cc0",
    "creator": "汤姆.刘",
    "creationTime": "2023-02-01T16:15:23.7591442+08:00"
}
`

**Comment by mkArtakMSFT** [comment]
@adityamandaleeka moved this to your area path, but this may very well be a runtime issue too - I'm not sure.

**Comment by adityamandaleeka** [comment]
@liugt34 It looks like the `}}` is turning into a `}`, which is consistent with how braces are escaped in string.Format.

It looks like you have some custom log formatting enabled. I'd start by looking there to see how you can fix this problem.

**Comment by liugt34** [comment]
@adityamandaleeka  you are right, i removed the Serilog, it works well!

**Comment by adityamandaleeka** [comment]
Glad you found the problem. Closing this issue.
