### ISSUE TITLE
name claim does not seem to be full qualified 

### ISSUE THREAD

**Issue by marcels2204** [dotnet/aspnetcore#46388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After migration to .net 7 the  name claim does not seem to be fully qualified anymore?

this code does not work anymore. the ClaimTypes.Name contains namespace. Claims returned from User.Claims
does not anymore contain the namespace in the ClaimType

```csharp
var userName = User.Claims.FirstOrDefault(claim => claim.Type == ClaimTypes.Name)?.Value;
```

workaround

```csharp
var userName = User.Claims.FirstOrDefault(claim => claim.Type == "name")?.Value; 
```

### Expected Behavior

Claim with type name could be found with comparision of ClaimTypes.Name

### .NET Version

7

**Comment by captainsafia** [comment]
> After migration to .net 7 the name claim does not seem to be fully qualified anymore?

What code path is creating the ClaimsUser that you are analyzing here? That'll provide a pointer to anything that might be pre-processsing the claim names before we hit this comparison.

**Comment by marcels2204** [comment]
The claims are taken from ControllerBase::User

` public class UploadController : ControllerBase
    {
        private readonly IMediator _mediator;

        public UploadController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Authorize]
        [HttpPost]
        public async Task<ApiResult> Upload(IFormCollection collection)
        {
            var userName = User.Claims.FirstOrDefault(claim => claim.Type == "name")?.Value;

            Type type = Type.GM;

            ICollection<string> keys = collection.Keys;

            if (keys.Contains("type"))
            {
                Enum.TryParse(collection["type"], out type);
            }

            foreach (var formFile in collection.Files)
            {
                if (formFile.Length > 0)
                {
                    return await _mediator.Send(new UploadBatchFileCommand(formFile, type, userName));
                }
            }

            return new ApiResult();
        }
    }`

**Comment by captainsafia** [comment]
@marcels2204 The code you shared is the code that consumes the ClaimsUser. To identify what is creating it, can you share your `Startup.cs` or `Program.cs` where you are configuring your authentication providers?

**Comment by marcels2204** [comment]
`using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Nord.CPQ.Api;
using Nord.NORDCalc.API;
using Nord.NORDCalc.API.BackgroundServices;
using Nord.NORDCalc.Application.PublishMessages;
using Nord.NORDCalc.Application.Services;
using Nord.NORDCalc.Infrastructure;
using Nord.Shared.Healthchecks;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((ctx, lc) => lc.ReadFrom.Configuration(ctx.Configuration));

builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory())
    .ConfigureContainer<ContainerBuilder>(builder => builder.RegisterModule(new MediatorModule()));

builder.Host.ConfigureServices(services =>
{
    services.AddHostedService<CalculationStatusConsumer>();
});

// Add services to the container.
builder.Services.SetupApi(builder.Configuration);
builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddScoped<IMessageBuilder, MessageBuilder>();
builder.Services.AddScoped<IBatchInformationService, BatchInformationService>();
builder.Services.AddScoped<IParser, Parser>();

builder.Services.SetupInfrastructure(builder.Configuration);

var app = builder.Build();

var provider = app.Services.GetRequiredService<IApiVersionDescriptionProvider>();

app.UseCors("CorsPolicy");

app.UseHeaderPropagation();

app.UseSwagger();

app.UseSwaggerUI(
           options =>
           {
               foreach (var description in provider.ApiVersionDescriptions)
               {
                   options.SwaggerEndpoint($"{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());
               }
           });

app.UseHttpsRedirection();

app.UseAuthentication();

app.UseAuthorization();

app.MapControllers();

app.UseHealthChecks("/ready", builder.Configuration["ManagementPort"], new HealthCheckOptions
{
    ResponseWriter = ResponseWriter.WriteHealthResponse
});

app.UseHealthChecks("/live", builder.Configuration["ManagementPort"], new HealthCheckOptions
{
    Predicate = hc => false
});

app.UseOpenTelemetryPrometheusScrapingEndpoint();

app.Run();
`
`using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Nord.NORDCalc.API;
using Nord.Shared.Authorization;
using Nord.Shared.MVC.Extensions;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Nord.CPQ.Api
{
    public static class ServiceCollectionExtensions
    {
        public static void SetupApi(this IServiceCollection services, IConfiguration Configuration)
        {
            services.AddHeaderPropagation(o =>
            {
                string[] headers = Configuration.GetSection("HeaderPropagation").Get<string[]>();
                if (headers != null)
                {
                    foreach (string header in headers)
                    {
                        o.Headers.Add(header);
                    }
                }
            });

            services.AddHealthChecks();

            services.AddHttpContextAccessor();

            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder
                    .SetIsOriginAllowed((host) => true)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials());
            });

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(o =>
            {
                o.Authority = Configuration["Jwt:Authority"];
                string audience = Configuration["Jwt:Audience"];
                if (!string.IsNullOrEmpty(audience))
                {
                    o.Audience = audience;
                }
                else
                {
                    o.TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidateAudience = false
                    };
                }
                o.Events = new JwtBearerEvents()
                {
                    OnAuthenticationFailed = c =>
                    {
                        c.NoResult();
                        c.Response.StatusCode = 401;
                        c.Response.ContentType = "text/plain";
                        return c.Response.WriteAsync("An error occured");
                    }
                };
            });

            services.AddUserRights(Configuration);

            services.AddApiVersioning(config =>
            {
                config.DefaultApiVersion = new ApiVersion(1, 0);
                config.AssumeDefaultVersionWhenUnspecified = true;
                config.ReportApiVersions = true;
            });

            services.AddVersionedApiExplorer(
              options =>
              {
                  options.GroupNameFormat = "'v'VVV";
                  options.SubstituteApiVersionInUrl = true;
              });


            services.AddSwagger(Configuration);
            services.AddTracing(Configuration);
        }


        private static void AddSwagger(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddSwaggerGen(c =>
            {
                c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "Bearer"
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            },
                        },
                        new string[]{ }
                    }
                });

                c.AddSecurityDefinition("Oauth2", new OpenApiSecurityScheme
                {
                    Description = "Oauth2 with Keycloak",
                    Name = "Authorization",
                    Type = SecuritySchemeType.OpenIdConnect,
                    Scheme = "Oauth2",
                    OpenIdConnectUrl = new Uri($"{configuration["Jwt:Authority"]}/.well-known/openid-configuration"),
                    Flows = new OpenApiOAuthFlows
                    {
                        AuthorizationCode = new OpenApiOAuthFlow()
                        {
                            Scopes = new Dictionary<string, string>
                            {
                                {"openid", "openid"},
                                {"profile", "profile"},
                                {"email", "email"},
                                {"roles", "roles"}
                            }
                        }
                    }
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Oauth2"
                            },
                        },
                        new string[]{ }
                    }
                });

                c.CustomSchemaIds(type => type.ToString());

            });

            services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();
        }
    }
}
`

**Comment by captainsafia** [comment]
Triage: It looks like you're using JWT-bearer based authentication here. You'd want to make sure that whatever backend services is issuing the token has the correct claim mappings configured in your `AddJwtBearer` configuration.
