### ISSUE TITLE
Blazor - Items within the Virtualize component are not fully keyboard accessible

### ISSUE THREAD

**Issue by mooski** [dotnet/aspnetcore#46385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the tab key to traverse items inside a Virtualize component doesn't work correctly once you reach the spacer element. It looks like the Virtualize component doesn't render additional elements as you'd expect as you tab through beyond the visible elements.

The documentation implies this should work here: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#keyboard-scroll-support

### Expected Behavior

It should be possible to use the tab key to traverse through all items within the Virtualize component - whether or not they're visible when you start pressing the tab key.

### Steps To Reproduce

The following has been tested in Chrome and Firefox in Windows - both with the same results.

1. Clone https://github.com/mooski/blazor-virtualize, open the solution and start the application, OR visit this demo page: https://try.mudblazor.com/snippet/cumdOcYvoaAQJsjk
2. Set the focus on any of the elements rendered in the list in the browser.
3. Press the tab key multiple times.
4. Note that initially it appears to work correctly. Focus moves from one element to the next as expected.
5. Note that when you get to about the 11th item the focus shifts somewhere else (it's not clear where).

### .NET Version

7.0.100

**Comment by mkArtakMSFT** [comment]
This may potentially be addressed by https://github.com/dotnet/AspNetCore.Docs/pull/24199/files

**Comment by SteveSandersonMS** [comment]
The issue is that you don't have `@key` on your items, so the DOM elements aren't preserved. If you change your sample code to use this:

```
<div class="item" tabindex="1" @key="@item">@item</div>
```

... then it appears to work fine.

**Comment by mooski** [comment]
Thanks, that solves the problem!

I wonder if it would be worth stressing this in the documentation. Looking back at it now, I can see that `@key` is used in some examples but not others, and the consequences of omitting it are not necessarily clear. https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0

Thanks again, I really appreciate you looking in to this.
