### ISSUE TITLE
item position changed while scrolling in blazor virtualize with multiple items in row.

### ISSUE THREAD

**Issue by kmkrish001** [dotnet/aspnetcore#46383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

item position changed while scrolling in blazor virtualize with multiple items in row.

### Expected Behavior

Need to maintain the same position and scroll will works to load the row of items.

### Steps To Reproduce

> <div class="container" style="width:700px">
    <ul style="height:400px;overflow-y:scroll">
        <Virtualize Items="ListItems" Context="item">
                    <ItemContent>
                            <li class="li-item">
                                <span>@item</span>
                            </li>
                    </ItemContent>
        </Virtualize>
    </ul>
</div>

`@code {
    public List<string> ListItems = new List<string>();
    protected override void OnInitialized()
    {
        for (int i = 0; i < 1000; i++)
        {
            ListItems.Add("Item " + i);
        }
    }
}
`

> <style>
    .container {
        border: 1px solid gray;
    }

    .li-item {
        float: left;
        border: 1px solid red;
        height: 80px;
        width: 80px;
    }

    .li-item {
        float: none;
        display: inline-block;
    }
</style>

### .NET Version

7.0

### Anything else?

screenshot,
![image](https://user-images.githubusercontent.com/92425146/216011257-d3b01f48-52f3-46cb-b763-a6ee07767ba0.png)

![image](https://user-images.githubusercontent.com/92425146/216011350-e88569ad-aae5-4562-bed1-b2b9af009466.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is currently not supported and the work to add support for it is tracked by https://github.com/dotnet/aspnetcore/issues/28821
