### ISSUE TITLE
We have a project template where we can add support for Server and Webassembly

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46395]
* We need to decide whether we want a single template, a new separate template, or multiple templates.
* We want to keep supporting scenarios where your whole app is webassembly/server and you do not care about adding "islands" of interactivity into the page.
* We want whole server/webassembly apps to leverage the improvements in server side rendering even if they aren't using an "islands" architecture.

**Comment by nakamacchi** [comment]
I want to vote a new seperate template for Blazor United, i.e., keep the existing templates (Blazor Server and Blazor WebAssmbly) and add the new Blazor United template. The reasons are below.

- Developing Blazor apps which can work both in SSR/CSR mode would require additional efforts and careful development.
- To use the static web hosting model, Blazor WebAssembly model will be required.
- Single template will cause application migration effort from .NET 7 or earlier.

**Comment by sab39** [comment]
My suggestion would be to keep the existing templates and add a new separate template for Blazor United, but also provide a clear and discoverable migration path to turn existing Blazor Server or Blazor WASM projects (whether created before United was an option, or created with the new version) into United projects.
