### ISSUE TITLE
Auto switching for interactive components

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46397]
In scope:

 * Use Server by default while loading WebAssembly runtime in the background
 * If WebAssembly files are cached, use WebAssembly mode

Out of scope:

 * Customizing how the auto mode makes its decision (#48756)
 * Shutting down Server circuits eagerly once WebAssembly files are downloaded (instead, just let them shut down naturally as the user navigates around)

**Comment by juepiezhongren** [comment]
Does auto mode support automatic switch besides re-ender switch?
