### ISSUE TITLE
Add $schema to launchSettings.json for all project templates

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspnetcore#46416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a project is created that contains a `launchSettings.json` file it doesn't have the `$schema` declaration.

The schema declaration that should be added is `"$schema": "http://json.schemastore.org/launchsettings.json"`.

This will improve the editing experience for users working with `launchSettings.json` outside of Visual Studio. Visual Studio has special support to enable full support for this file without the `$schema` declaration, but other editors do not have that. I believe that there is no drawback from adding this declaration to the file.

### Expected Behavior

Having the $schema declaration

### Steps To Reproduce

dotnet new webapp

### .NET Version

all

### Anything else?

Nothing else

**Comment by mkArtakMSFT** [comment]
@sayedihashimi I assume you want us to do this for only the latest .NET 8 templates, or do you actually want us to apply this for all ASP.NET Core versions which are in support?

**Comment by sayedihashimi** [comment]
For the latest templates only. Thank you.

**Comment by alessiotm** [comment]
Hi everyone, can I grab this issue?
I would like to give it a try, first contribution for me.

**Comment by rhires** [comment]
@alessiotm - you don't need permission. Go for it. The permission part is when you do a pull request, and then the maintainers decide if the work you've done is good enough to merge, or if it needs additional work, and you iterate a few times until it is good enough :-)

**Comment by sayedihashimi** [comment]
Thanks @alessiotm for the PR, and congrats on your first contribution!
