### ISSUE TITLE
Improve testing experience for identity

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnetcore#46415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When unit testing with Moq and XUnit, it seems near impossible to write tests, because there are no interfaces for the concrete classes.

### Expected Behavior

I'm able to get unit tests to pass.

### Steps To Reproduce

Write a unit test for SignInManager, UserManager, RoleManager using EntityFrameworkCore.

### .NET Version

7.0.102

### Anything else?

No.

**Comment by captainsafia** [comment]
Triage: At the moment, we do not plan on refactoring the Identity implementation to introduce interfaces for testing. The current design does not lend itself to this sort of refactor. Furthermore, the framework tests in Identity provide test coverage for this area so there is little value in integrating additional testing at the consumption layer.

**Comment by chris-briddock** [comment]
I disagree, this is hurting my unit tests code coverage by around 40%. Therefore it looks like my code not testing correctly. Adding a interfaces will improve testing from a developer consuming the library's point of view.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is a lot of history here and it's not easy to go back and change most of this. Especially given that this hasn't really been a big pain point for our customers. Hence, closing this.
