### ISSUE TITLE
Files not found/ failed integrity check when deploying Hosted Blazor WASM app to IIS Express 

### ISSUE THREAD

**Issue by RisbergMats** [dotnet/aspnetcore#46410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to publish a Blazor hosted WASM app to a local folder and for hosting with IIS Express.
The app fails to load a because the files _framework/icudt_no_CJK.dat and _framework/dotnet.timezones.blat fails integrity check and are blocked.

Editing blazor.boot.json with the correct hash values for the files will make the integrity check pass, but it will still not load the files.

I have tried claening the solution (including obj and bin folder) and cleared the browser cash with no improvement.
The problem is present in both net 6.0 and net 7.0 frameworks.
Visual studio version Version is 17.4.4

### Expected Behavior

I expect the app to load without errors.

### Steps To Reproduce

- Create a new project with the Blazor WebAssembly template, use default settings with ASP.NET core hosting
- Publish the server project in a folder on disk (C:\test) in this example

- Add the site on iis express by using a command like this:
appcmd add site /name:"test" /id:"2" /bindings:"http/*:80:" /physicalPath:"C:\test\wwwroot"

- Start the site by running:
iisexpress /site:test

- Start a browser and browse to http://localhost:80
integrity check will failk for files  _framework/icudt_no_CJK.dat and _framework/dotnet.timezones.blat 

- Copy the expected hash strings from the console to the corresponding files in blazor.boot.json

- Reload the page
the files files _framework/icudt_no_CJK.dat and _framework/dotnet.timezones.blat fails to load and an exeption is thrown from blazor.webassembly.js

### Exceptions (if any)

  | (anonymous) | @ | blazor.webassembly.js:1
-- | -- | -- | --
  | await in (anonymous) (async) |   |  
  | preRun | @ | blazor.webassembly.js:1
  | (anonymous) | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | wc | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | await in wc (async) |   |  
  | e.preRun | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | callRuntimeCallbacks | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | preRun | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | run | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | runCaller | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | removeRunDependency | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | receiveInstance | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | (anonymous) | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | (anonymous) | @ | blazor.webassembly.js:1
  | await in (anonymous) (async) |   |  
  | instantiateWasm | @ | blazor.webassembly.js:1
  | mc | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | e.instantiateWasm | @ | dotnet.7.0.2.lw9rcxnj3f.js:5
  | createWasm | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | (anonymous) | @ | dotnet.7.0.2.lw9rcxnj3f.js:14
  | (anonymous) | @ | blazor.webassembly.js:1
  | await in (anonymous) (async) |   |  
  | start | @ | blazor.webassembly.js:1
  | Vt | @ | blazor.webassembly.js:1
  | await in Vt (async) |   |  
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1

### .NET Version

7.0.102

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is most probably due to the IIS configuration which prevents these files from being served. You should try to configure mime types on the server (IIS Express in this case) to enable serving these files.
Maybe this will be useful: https://stackoverflow.com/questions/9021946/add-mime-mapping-in-web-config-for-iis-express

**Comment by RisbergMats** [comment]
Thanks!
It seems to be the configuration of IIS Express that is the problem. 
I added the lines:
```
<mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
<mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
```
in applicationhost.config and the page loads without problems.
