### ISSUE TITLE
Switch Debian11 Amd64 helix queue to Debian12 once msquic is available

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#46418]
Do a follow-up to https://github.com/dotnet/aspnetcore/pull/46419 once https://github.com/microsoft/msquic/issues/2039 is resolved.

**Comment by dougbu** [comment]
I disagree w/ this idea if it's true we need to support Debian 11 in .NET 8

**Comment by Nick-Stanton** [comment]
The linked test needs to be unskipped once msquic is available on Debian12 - https://github.com/dotnet/aspnetcore/pull/46615
