### ISSUE TITLE
"ENOENT: no such file or directory" on VS Code Blazor Debug

### ISSUE THREAD

**Issue by JorgePinetta** [dotnet/aspnetcore#46429]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When I try to debug a blazor project that is part of a solution with the following folder structure:
* **Solution-Folder**
  * **.vscode**
    * launch.json
  * **Project-Folder**
    * **Properties**
      * launchSettings.json
    * Project.csproj

the session fails with the following message:
`ENOENT: no such file or directory, open 'd:\DEV\Trash\SolutionBlazorApp\Properties\launchSettings.json'`

### Expected Behavior

Expect the browser to launch and the debug environment to work in the VS Code IDE.

### Steps To Reproduce

[Reproduce this issue repro](https://github.com/JorgePinetta/Blazor4Issue)

### Exceptions (if any)

`2023-02-03 00:01:52.843 [error] Error: ENOENT: no such file or directory, open 'd:\DEV\Trash\Blazor4Issue\Properties\launchSettings.json'
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at readFileSync (node:fs:453:35)
	at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at c:\Users\JorgeP\.vscode\extensions\ms-dotnettools.blazorwasm-companion-1.1.3\dist\extension.js:25:69
	at Generator.next (<anonymous>)
	at c:\Users\JorgeP\.vscode\extensions\ms-dotnettools.blazorwasm-companion-1.1.3\dist\extension.js:12:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\JorgeP\.vscode\extensions\ms-dotnettools.blazorwasm-companion-1.1.3\dist\extension.js:8:12)
	at c:\Users\JorgeP\.vscode\extensions\ms-dotnettools.blazorwasm-companion-1.1.3\dist\extension.js:23:119
	at s.h (c:\Users\JorgeP\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108016)
	at s.g (c:\Users\JorgeP\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106906)
	at s.g (c:\Users\JorgeP\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107596) blazorwasm-companion.launchDebugProxy {"value":"ms-dotnettools.blazorwasm-companion","c":"ms-dotnettools.blazorwasm-companion"}`

### .NET Version

7.0.102

### Anything else?

**IDE: VS Code**
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

---
**Extension**
Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.1.3

---
**dotnet --info**
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by JorgePinetta** [comment]
Commenting these lines in the extension.js file is my current workaround:
![Clipboard01](https://user-images.githubusercontent.com/86976958/216505054-03736b74-c059-49fb-91ea-93b6f78f1861.jpg)

**Comment by pettijohn** [comment]
Experiencing this too. I upgraded the C# and BlazorWasm extensions this morning to 1.25.4 and 1.1.3, respectively. In `.vscode/launch.json` I have `cwd` set and it does not seem to honor it like it did yesterday. Instead of loading `${workspaceFolder}/src/Client.Web/Properties/launchSettings.json` it is failing to load `${workspaceFolder}/Properties/launchSettings.json`

```
{
    "name": "Attach Client.Web",
    "type": "blazorwasm",
    "request": "attach",
    "cwd": "${workspaceFolder}/src/Client.Web/",
    "browser": "edge",
    "url": "https://localhost:7260",
    "timeout": 120000, // Allows time for the site to launch
},
```

**Comment by mkArtakMSFT** [comment]
@Nick-Stanton is this something to be addressed with your changes on the extension?

**Comment by pettijohn** [comment]
Thanks @JorgePinetta for the workaround - if anyone else encounters this that file is `%userprofile%\.vscode\extensions\ms-dotnettools.blazorwasm-companion-1.1.3\dist\extension.js`

**Comment by Nick-Stanton** [comment]
> @Nick-Stanton is this something to be addressed with your changes on the extension?

@thaystg is there a chance that dotnet/razor#7929 introduced a breaking change?

**Comment by thaystg** [comment]
I don't think so. Is this the only change between 1.1.0 and 1.1.3?

**Comment by Nick-Stanton** [comment]
@JorgePinetta @pettijohn if the previous version was working for you, then another alternative is to go to the BlazorWasmDebuggingExtension under your installed VSCode extensions and under the Install/Unistall dropdown select `Install another version` to revert to the older version. Thanks for your patience while we troubleshoot this.

**Comment by thaystg** [comment]
Ohhh, now that I saw that commenting some lines it worked, let me check

**Comment by JorgePinetta** [comment]
> @JorgePinetta @pettijohn if the previous version was working for you, then another alternative is to go to the BlazorWasmDebuggingExtension under your installed VSCode extensions and under the Install/Unistall dropdown select `Install another version` to revert to the older version. Thanks for your patience while we troubleshoot this.

Hi @Nick-Stanton, The earlier version (1.1.0) did not function properly. I had been awaiting this upgrade.
The most recent version (1.1.3) corrects issues with the prior version, such as https://github.com/dotnet/aspnetcore/issues/45257.

I only encountered this one issue, which I was able to temporarily fix using a workaround.

**Comment by xevoryn** [comment]
> Hi @Nick-Stanton, The earlier version (1.1.0) did not function properly.

There is also this already closed issue #46222 which still persists after updating to 1.1.3.
Also now having trouble with this behaviour in another project (previously only problem with #46222)

**Comment by Nick-Stanton** [comment]
Reopening since we're waiting on build before publishing the fix

**Comment by Nick-Stanton** [comment]
1.1.4 released this morning 😄 thanks for your patience
