### ISSUE TITLE
Describe Microsoft.AspNetCore.Identity.UserOptions.RequireUniqueMail behaviour in documentation comments

### ISSUE THREAD

**Issue by KamilRaszkiewicz** [dotnet/aspnetcore#46435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Current description of  **Microsoft.AspNetCore.Identity.UserOptions.RequireUniqueMail** does not describe, that if we set it **true**, we can't create user with _null_ email (i.e. model validation fails), even tho we still have nullable Email field in dbo.AspNetUsers table, and user with _null_ email does not exist in our database. 

### Describe the solution you'd like

Describe the behaviour in documentation comments or make the option impact database scheme so Email field is not nullable anymore if set true.

**Comment by captainsafia** [comment]
@KamilRaszkiewicz Would you be interested in contributing a PR with an update to the XML docs on this property?

**Comment by KamilRaszkiewicz** [comment]
> @KamilRaszkiewicz Would you be interested in contributing a PR with an update to the XML docs on this property?

Sure
