### ISSUE TITLE
ANCM Out-Of-Process random port range causes collision

### ISSUE THREAD

**Issue by yanxurui** [dotnet/aspnetcore#46431]
## Summary

ANCM out of process will start kestrel that listens on a random port from 10025 to 48000. This can occupy the port used by other services that use static ports on the same machine. Bumping up the MIN port for ANCM can alleviate this problem.

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?
### Pain point:
Recently we had an incident where our grpc service can not start up because the static port we use for grpc is being occupied by some other service that is hosted using ANCM out of process model. Quite a few . This collision could happen if any services that is using a port between 10025 and 48000 and starts after the ANCM out of process is started up.

### What evidence shows it's valuable to solve this?
1. assign a port out of the range to our grpc service is not safe because windows' socket api may allocate a random port between [49152 and 65535](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang) unless we use a port between 48001 and 49151
2. There is no need for ANCM out of process to use such a big range

## In scope
N/A

## Out of scope
N/A

## Risks / unknowns

I didn't see any potential risk for this change.

## Examples

No change is needed in the client code.

**Comment by Tratcher** [comment]
10025 seems pretty arbitrary? 1025 was used because ports lower than that are reserved and require admin access.

Can you clarify why you're still using out-of-process? We've recommended (and defaulted to) in-process since 3.0.

**Comment by yanxurui** [comment]
Thanks @Tratcher  Yes. 10025 is arbitrary. The idea here is to use a port that is much larger than 1025 to avoid collision.
I am from m365 team. One of OWA’s component has been using outofprocess model for years. We own a grpc service whose port is occupied by them sometimes. Other services could have the same problem. I don’t think they would like to move to in process model to fix this minor problem.

**Comment by HamsterExAstris** [comment]
> Can you clarify why you're still using out-of-process? We've recommended (and defaulted to) in-process since 3.0.

We're still using out-of-process for one of our applications because Windows Defender [ignores activity by IIS worker processes](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus?view=o365-worldwide#web-server-exclusions); using out-of-process ensures that file uploads from users are scanned for viruses/malware.

**Comment by adityamandaleeka** [comment]
@yanxurui It looks like the port is already configurable: https://github.com/dotnet/aspnetcore/blob/55d8fe39928b81108965059b2625c7e5b76603f9/src/Servers/IIS/AspNetCoreModuleV2/OutOfProcessRequestHandler/serverprocess.h#L15

Is that sufficient for your needs or do you need the port number to be selected from a range?

**Comment by yanxurui** [comment]
Regardless of our specific scenario, that is not sufficient if we want to run a variable number of services. In the ANCM out-of-process model, the IIS server starts a specific service using kestrel in a separate process. In this case, we don't care which port the kestrel server is using because all requests will be routed by IIS server to the proper kestrel instances. It's better to use random ports from the dynamic range instead of pre-allocated fixed ports.

**Comment by yanxurui** [comment]
Since ports <= 1024 are reserved, people tend to pick a port starting from 1025 for their services. It's likely that the random port selected by ANCM out-of-process model collides with the fixed one we choose for other services. Therefore, I believe it's better to avoid using a port range starting from 1025.

**Comment by adityamandaleeka** [comment]
We normally don't take this sort of change (especially in out-of-process hosting which is not something we recommend people use), but in this case, it seems like it can reduce the chances of collision without having any negative impact, so we'll accept it.

I've left some comments on your PR.

**Comment by yanxurui** [comment]
Thank you @adityamandaleeka!! I have updated my PR.

**Comment by BrennanConroy** [comment]
Final change: Changed the random port range to start at 10,000 instead of 1025. But still allow users to use the `ASPNETCORE_PORT` environment variable to set ports lower than 10,000 and higher than 1025.
