### ISSUE TITLE
System.ArgumentException: 'overlapped' was not allocated by this ThreadPoolBoundHandle instance.

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#46439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Reported offline by an internal partner. They see this error show up frequently and randomly.
![bd189623-4f90-4dc8-88c7-8da7502f6101](https://user-images.githubusercontent.com/1821173/216673646-af7f6a0b-ac31-4a1e-a8f9-fe39239c0877.jpg)

The relevant code is here:
https://github.com/dotnet/aspnetcore/blob/6a547f269de700cfe333946e1fd744e4332a904a/src/Servers/HttpSys/src/AsyncAcceptContext.cs#L161-L174

### Exceptions (if any)

System.ArgumentException: 'overlapped' was not allocated by this ThreadPoolBoundHandle instance. (Parameter 'overlapped') at System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(NativeOverlapped* overlapped) at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.AllocateNativeRequest(Nullable`1 size, UInt64 requestId) at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.AcceptAsync() at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestsWorker()

### .NET Version

(need to verify with the customer)

### Anything else?

The only similar report I see is https://github.com/dotnet/runtime/issues/48402 on the client side.

**Comment by davidfowl** [comment]
I'm sure there's an issue here. That code is called from 3 places in a non-linear flow.  Lets try to get a repro from the customer.

**Comment by Tratcher** [comment]
Hitting that specific error is weird though, there's only one BoundHandle for the entire server. I don't know how you'd ever end up with a different one in that field.

https://github.com/dotnet/runtime/blob/3ced9681d9eda35cee4c580066ecb3c10a569a1f/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.cs#L226-L229
https://github.com/dotnet/runtime/blob/3ced9681d9eda35cee4c580066ecb3c10a569a1f/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.cs#L272-L273
https://github.com/dotnet/runtime/blob/3ced9681d9eda35cee4c580066ecb3c10a569a1f/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandleOverlapped.cs#L48-L49

Maybe it's null due to a double free?

**Comment by davidfowl** [comment]
> Maybe it's null due to a double free?

That's what I was thinking.

**Comment by adityamandaleeka** [comment]
We should see if we can reproduce this. I'm assuming this is a first-chance exception?

**Comment by adityamandaleeka** [comment]
@mgravell Can you please look into this when you have some time?

**Comment by mgravell** [comment]
agree that `null` seems the most credible scenario; the *only* thing that assigns `null` (or indeed any value other than `this`) is `PreAllocatedOverlapped.OnFinalRelease`, via `PreAllocatedOverlapped.Release` thru `DeferredDisposableLifetime<PreAllocatedOverlapped>`, and that path is called only from:

1. `FreeNativeOverlapped`
2. `AllocateNativeOverlapped` in the exception case (to compensate for the earlier `AddRef`)

Hypothesis: in `AllocateNativeRequest` (via `AsyncAcceptContext.AcceptAsync` via `HttpSysListener.AcceptAsync`) we currently aren't setting `_overlapped` to `null` after freeing it and before creating a new request ; if anything faults and we retry, we'll *do that again next time*, causing this scenario.

Checking `MessagePump.AcceptLoop.ExecuteAsync`, we do indeed `catch` and `continue` (retry) in the fault scenario, which means this is a possible cause.

I'm not sure if we will manage to repro (I'll see what I can do), but my strong suggestion:

``` c#
167        if (_overlapped != null)
168        {
169            boundHandle.FreeNativeOverlapped(_overlapped);
+++            _overlapped = null;
170        }
```

Thoughts?

**Comment by mgravell** [comment]
PR with proposed tweak; I'll see if I can think of any way to prove it!

**Comment by mgravell** [comment]
The more I think about this, the more I'm thinking "concurrency, overlapped accepts". I'll try to run some overlapped scenarios through. It is sort of weird that we free something simply because we're about to start a new one, rather than because the old one reached a closing state, but that might just be my learning curve!

**Comment by Tratcher** [comment]
I think the issue there is that the Accept object is using a buffer that then gets handed off to the request, or wasn't big enough so we need to try again with a bigger one.

**Comment by ms-ruochenyu** [comment]
@mgravell @Tratcher is there update on this issue? We are seeing continuous repro'es in our internal service.

**Comment by mgravell** [comment]
Possibly. This may be related to (or identical to) a similar glitch/symptom that we have been investigating internally, and hope to have a resolution in place soon.

**Comment by BrennanConroy** [comment]
This should be fixed now.

**Comment by ms-ruochenyu** [comment]
> This should be fixed now.

Thanks @BrennanConroy! Would you mind tagging in what release it has been fixed?
