### ISSUE TITLE
Using minimal APIs source generator results in null dereference warnings (CS8602)

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#46446]
The minimal APIs source generator is generating code that results in a null dereference warning (CS8602).

The app's *Program.cs*:

```csharp
var builder = WebApplication.CreateSlimBuilder(args);
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

await app.StartApp();
```

The generated *GeneratedRouteBuilderExtensions.g.cs* with the warnings on lines 14 and 22 (of this snippet), when accessing `options.EndpointBuilder`:

```csharp
...
file static class GeneratedRouteBuilderExtensionsCore
{

    private static readonly Dictionary<(string, int), (MetadataPopulator, RequestDelegateFactoryFunc)> map = new()
    {
        [(@"~\MyWebApp\src\HelloWorld.Web\Program.cs", 4)] = (
       (methodInfo, options) =>
        {
            if (options == null)
            {
                return new RequestDelegateMetadataResult { EndpointMetadata = ReadOnlyCollection<object>.Empty };
            }
            options.EndpointBuilder.Metadata.Add(new SourceKey(@"~\MyWebApp\src\HelloWorld.Web\Program.cs", 4));
            return new RequestDelegateMetadataResult { EndpointMetadata = options.EndpointBuilder.Metadata.AsReadOnly() };
        },
        (del, options, inferredMetadataResult) =>
        {
            var handler = (System.Func<string>)del;
            EndpointFilterDelegate? filteredInvocation = null;

            if (options.EndpointBuilder.FilterFactories.Count > 0)
            {
                filteredInvocation = GeneratedRouteBuilderExtensionsCore.BuildFilterDelegate(ic =>
...
```

Warnings from build output:

```shell
~\MyWebApp\src\HelloWorld.Web\Microsoft.AspNetCore.Http.Generators\Microsoft.AspNetCore.Http.Generators
.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(88,17): warning CS8602: Dereference of a possibly null reference. [~\MyWebApp\src\HelloWorld.Web\HelloWorld.Web.csproj]
~\MyWebApp\src\HelloWorld.Web\Microsoft.AspNetCore.Http.Generators\Microsoft.AspNetCore.Http.Generators
.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(96,21): warning CS8602: Dereference of a possibly null reference. [~\MyWebApp\src\HelloWorld.Web\HelloWorld.Web.csproj]
```

**Comment by halter73** [comment]
This should be fixed by @captainsafia's latest response writing PR (#46291). The generated code now emits `Debug.Assert(options?.EndpointBuilder != null, "EndpointBuilder not found.");` before doing `options.EndpointBuilder.Metadata.AsReadOnly()`.

RequestDelegateGeneratorTestBase was also updated in that PR so most tests will fail given any nullablity errors, so I think we can close this.

**Comment by DamianEdwards** [comment]
Thanks @halter73. I'll wait for the bits to flow to the installer so I can verify then I'll close this out.

**Comment by captainsafia** [comment]
> This should be fixed by @captainsafia's latest response writing PR (https://github.com/dotnet/aspnetcore/pull/46291). The generated code now emits Debug.Assert(options?.EndpointBuilder != null, "EndpointBuilder not found."); before doing options.EndpointBuilder.Metadata.AsReadOnly().

Correct!

> RequestDelegateGeneratorTestBase was also updated in that PR so most tests will fail given any nullablity errors, so I think we can close this.

Not correct! I had some struggles while trying to get this working with the same setup I've used in generator tests elsewhere but didn't have any luck so I filed https://github.com/dotnet/aspnetcore/issues/46331.

_But_ as I'm typing this out, I'm wondering if the fact that we disable nullability in our test projects in the repo might've interfered in some weird way with the setup on the test projects. Let me try and see...

**Comment by DamianEdwards** [comment]
The good news is, once the api template is updated to use the source generator, the template tests will fail if there's warnings :smile:

**Comment by captainsafia** [comment]
> The good news is, once the api template is updated to use the source generator, the template tests will fail if there's warnings 😄

Yep! We also have the generator enabled on the `MinimalSample` in the repo now so that's another checkpoint for this.

Having it in the tests provides another layer of validation for code samples we don't have in the sample or the template. I was able to get it working on the tests and opened a PR

**Comment by halter73** [comment]
> Not correct! I had some struggles while trying to get this working with the same setup I've used in generator tests elsewhere but didn't have any luck so I filed https://github.com/dotnet/aspnetcore/issues/46331.

Huh. I checked that before writing my comment because I wasn't sure what part of your PR caused nullability warnings to surface in the tests, but I remembered you mentioning you wanted to do that. When I removed the Debug.Assert from the source generator, I saw most of the tests did fail with nullability warnings.

**Comment by captainsafia** [comment]
Closing as there are no warnings as of 8.0.100-preview.2.23116.17.
