### ISSUE TITLE
Expose the cipher suite and SslStream

### ISSUE THREAD

**Issue by xiaoyangwang-geotab** [dotnet/aspnetcore#46442]
Hello .NET Core Team,

I hope this message finds you well. I am reaching out to request assistance in retrieving the cipher suite of each connection in my application.

I understand that this information is important for ensuring the security of the connection and I would like to know the steps to retrieve it using .NET Core. 

I tried to use ITlsHandshakeFeature retrieved from HttpContext, but I could only get the CipherAlgorithm, and both HashAlgorithm and KeyExchangeAlgorithm get None. Also, when I debug, I found a private field _sslSream  in the ITlsHandshakeFeature which gave me the cipher suite value from its property NegotiatedCipherSuite. But unfortunately, I couldn't find a way to access the sslStream. 

If there are any classes, methods or resources that you can recommend or provide, I would be grateful. I would also appreciate any additional information or guidance that you can offer on this matter.

Thank you for your time and assistance. I look forward to your response.

Best regards,
Xiaoyang

**Comment by davidfowl** [comment]
Where are you trying to get this information and what do you want to do with it?

**Comment by xiaoyangwang-geotab** [comment]
I tried get it from HttpContext after the connection build. 
We would like to monitor the usage of SSL ciphers, in particular to know when customers are using an insecure cipher, and so we could know when support for it can be safely removed.

**Comment by Tratcher** [comment]
Hmm, why didn't we include the NegotiatedCipherSuite?

The other ITlsHandshakeFeature fields give you most of the same information, just decomposed.

`Try HttpContext.Features.Get<SslStream>();`
https://github.com/dotnet/aspnetcore/blob/7d0b688e7b2241290346a98901708ea574db7f69/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L419

**Comment by xiaoyangwang-geotab** [comment]
Thanks Chris. I had tried HttpContext.Features.Get<SslStream>() too but it returned null for me.

**Comment by xiaoyangwang-geotab** [comment]
Additionally, here are the other fields I got: 
   CipherAlgorithm: Aes256
    CipherStrength: 256
    HashAlgorithm: None
    HashStrength: 0
    KeyExchangeAlgorithm: None
    KeyExchangeStrength: 0
    Protocol: Tls13
As I said HashAlgorithm and KeyExchangeAlgorithm are None, but from debug, I could see _sslStream.NegotiatedCipherSuite is TLS_AES_256_GCM_SHA384.
I don't understand why I kept getting None for the HashAlgorithm and KeyExchangeAlgorithm. 
Thanks again for helping me with it!

**Comment by Tratcher** [comment]
Those values match the properties from SslStream, right? We can only report what it does.

You may need to use reflection to get the SslStream for now. We can look at exposing the cipher suite in the future.

**Comment by xiaoyangwang-geotab** [comment]
Yes, those values match the properties from SslStream. 
Also, using reflection to get SslStream, you mean I could iterate all the HttpContext.Features and use reflection get SslStream, right? Thanks!

**Comment by Tratcher** [comment]
I meant you could use reflection to get the field from the type instance that implements ITlsHandshakeFeature.

**Comment by xiaoyangwang-geotab** [comment]
I see. Cool! I'll try to see if I could get it this way and will update the result later. Thanks

**Comment by xiaoyangwang-geotab** [comment]
Using reflection worked for now. But still hope the cipher suite will be exposed in the future to reduce overhead. Thanks!

**Comment by davidfowl** [comment]
I just took a look at this and it seems like an oversight. We only add the SSL Stream as a feature when you hook the certificate selector in the https options. I think we should just expose the SSLStream on a feature (either an existing one or a new one) like we do the socket.

**Comment by xiaoyangwang-geotab** [comment]
Thanks David! I have tried setting up ServerCertificateSelector in the https options, and got the SSL Stream from features eventually.

**Comment by halter73** [comment]
> You may need to use reflection to get the SslStream for now.

I don't think so. `context.Features.Get<SslStream>()` should work.

**Comment by BrennanConroy** [comment]
Triage: We should make sure SslStream is consistently available in the feature collection, folks are saying it's only added in one overload.

Add a property to the TlsFeature for the cipher suite.

**Comment by xiaoyangwang-geotab** [comment]
> > You may need to use reflection to get the SslStream for now.
> 
> I don't think so. `context.Features.Get<SslStream>()` should work.

Thanks @halter73  It returned null when I assigned my server certificate to ServerCertificate in http options. But it did work when I used ServerCertificateSelector, which like @davidfowl mentioned above.

**Comment by amcasey** [comment]
This appears to be where we need to pull the cipher suite from in win32 scenarios (e.g. http.sys): https://learn.microsoft.com/en-us/windows/win32/api/schannel/ns-schannel-secpkgcontext_cipherinfo

**Comment by davidfowl** [comment]
> This appears to be where we need to pull the cipher suite from in win32 scenarios (e.g. http.sys): https://learn.microsoft.com/en-us/windows/win32/api/schannel/ns-schannel-secpkgcontext_cipherinfo

Is this http.sys specific?

**Comment by amcasey** [comment]
> > This appears to be where we need to pull the cipher suite from in win32 scenarios (e.g. http.sys): https://learn.microsoft.com/en-us/windows/win32/api/schannel/ns-schannel-secpkgcontext_cipherinfo
> 
> Is this http.sys specific?

I'm not sure which "this" you're referring to, but that was a note in case we wanted to expose the cipher suite on the IIS/http.sys [implementation](https://github.com/dotnet/aspnetcore/blob/e6553945e9f4dc4cb15693dbb241df1b04cb709a/src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs#L26) of `ITlsHandshakeFeature`.

**Comment by davidfowl** [comment]
>I'm not sure which "this" you're referring to, but that was a note in case we wanted to expose the cipher suite on the IIS/http.sys implementation of ITlsHandshakeFeature.

Yes, I was asking if your comment was referring to the HTTP.sys implementation of this feature, seems like yes.

**Comment by Tratcher** [comment]
Yes, we should implement it everywhere possible.

**Comment by davidfowl** [comment]
Don't stall on kestrel because of IIS HTTP.sys though.
