### ISSUE TITLE
Any guide about SignalR client npm package upgrade?

### ISSUE THREAD

**Issue by ian90911** [dotnet/aspnetcore#46448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to upgrade an old project that use Signalr client npm package `@microsoft/signalr` version 6.0.9 to latest version cause the security issue, what I do first is to search release note or an upgrade guide, but I can't find any docs, is there any reference ? I'm confused.

### Describe the solution you'd like

- Maybe there has a document link about upgrade
- Maybe there's no need to check, just do `npm install` to latest version

**Comment by BrennanConroy** [comment]
> the security issue

What security issue?

> * Maybe there's no need to check, just do `npm install` to latest version

Yes.

**Comment by ian90911** [comment]
@BrennanConroy 
Thanks for reply, it's about `eventsource` dependency [#41728](https://github.com/dotnet/aspnetcore/issues/41728), now I can go upgrade with no worry 👍
