### ISSUE TITLE
Visual studio analyzer error for  bang bang operator

### ISSUE THREAD

**Issue by YasinAllahverdi** [dotnet/aspnetcore#46453]
### I want to develop an application and implement domain argument validation but i can't use bang bang operator  for arguments . When use bang bang operator i have an error like this .
`The parameter null checking is not supported`

### Category

 - [ ] Design
- [ ] Documentation
- [ ] Globalization
- [ ] Interoperability
- [ ] Maintainability
- [ ] Naming
- [ ] Performance
- [ ] Reliability
- [ ] Security
- [ ] Style
- [x] Usage

### Severity Level

- [x] Error
- [ ] Warning
- [ ] Info
- [ ] Hidden

## Usage Scenarios

I'm using visual studio professional 2022 with version 17.4.3

**Comment by gfoidl** [comment]
The `!!` got dropped from C# 11 (comes maybe later).
It was available in early previews, but didn't made it to later ones and the final product. Thus you get that error.
