### ISSUE TITLE
Update `<ValidationSummary />` to add `CssClass` and pass additional attributes to the generated DOM element

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/aspnetcore#46461]
## Background and Motivation
Currently, when using `<ValidationSummary />` it is not possible to pass additional css classes and have them appended to the generated `ul` element. While most of the styling for this component is done directly on the `validation-summary` css class, there are times when it is useful to simply use a utility class (i.e. `pt-2` to apply `8px` of top padding) to the element directly. The only way to do this right now is to wrap the component in another html element and apply the styles to the wrapper element.

For example:
```html
<div class="pt-2">
  <ValidationSummary />
</div>
```

Additionally, a common pattern when creating UI automation tests is to use the `data-test` attribute to make it easier for the test to locate the element. The current version of `<ValidationSummary />` does not apply additional properties to the generated DOM element.

## Proposed API
To simplify these scenarios, `<ValidationSummary />` should pass unmatched attributes (via splatting) to the generated root `ul` element and a new property `CssClass` attribute should be added which appends the passed in css classes to the generated DOM element. This is the same pattern used in other built-in form components.

```diff
namespace Microsoft.AspNetCore.Components.Forms;

public class ValidationSummary
{
+    /// <summary>
+    /// Gets or sets the computed CSS class to be appended to the <c>ul</c> element.
+    /// </summary>
+    protected string? CssClass { get; set; }
}
```

See this open pull request: https://github.com/dotnet/aspnetcore/pull/43928

## Usage Examples
The following razor code:
```html
<ValidationSummary CssClass="pt-2" data-test="xyz-errors" />
```

Currently results in the following generated html:
```html
<ul class="validation-errors">
  <!-- Validation Errors -->
</ul>
```

After my proposal, it should result in the following generated html:
```html
<ul class="validation-errors pt-2" data-test="xyz-errors">
  <!-- Validation Errors -->
</ul>
```

## Alternative Designs
See https://github.com/dotnet/aspnetcore/issues/43860 for the full discussion.

## Risks
This is a breaking change because `ValidationSummary` is not sealed so any class that inherits it could potentially have added their own property named `CssClass`. 

This breaking change is aligning this component with other built-in components.

**Comment by mkArtakMSFT** [comment]
Closing as this is already supported.
