### ISSUE TITLE
Blazor Server fails to upgrade to .net7 (Invocation provides 4 argument(s) but target expects 0)

### ISSUE THREAD

**Issue by shiomax** [dotnet/aspnetcore#46471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When upgrading to .net 7 (from .net 6) our blazor server project breaks. In the browser console it prints the following

```
Uncaught (in promise) Error: Failed to invoke 'StartCircuit' due to an error on the server.
    at _callbacks.<computed> (blazor.server.js:1:71746)
    at Ft._processIncomingData (blazor.server.js:1:72877)
    at Ft.connection.onreceive (blazor.server.js:1:67009)
    at i.onmessage (blazor.server.js:1:51322)
```

There are many issues with this error, but I can find none for .net 7 and I can find none with an actual solution other than "I tried again and it worked". Removing all obj and bin folders in the solution does not fix it either. I tried once when .net 7 was released and it did not work back then, figured Id give it some time back then. But looking at the same error now.

On the server after enabling detailed logs it logs the following

```
[23:02:12 DBG] Parameters to hub method 'StartCircuit' are incorrect.
System.IO.InvalidDataException: Invocation provides 4 argument(s) but target expects 0.
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.CreateInvocationMessage(MessagePackReader& reader, IInvocationBinder binder, Int32 itemCount)
```

However looking into the code of ComponentHub the method seems to have 4 parameters suggesting that the invokation should be correct.

```
public async ValueTask<string> StartCircuit(string baseUri, string uri, string serializedComponentRecords, string applicationState)
```

Enabling ```DetailedErrors``` in``` AddCircuitOptions``` reveils no additional information.

Not sure what is going on. At this point I cannot provide a project to reproduce this as new .net 7 blazor server projects work. Copying all the code over to a new project would take quite some time.

### .NET Version

7.0.200-preview.22628.1

**Comment by BrennanConroy** [comment]
> Enabling `DetailedErrors` in` AddCircuitOptions` reveils no additional information.

Set `EnableDetailedErrors` in `AddHubOptions`.

Also, the only way I can think of this happening is if you have `string` in your DI container. You can also set `DisableImplicitFromServicesParameters` to `false` in `AddHubOptions` to test that.

**Comment by shiomax** [comment]
> Also, the only way I can think of this happening is if you have `string` in your DI container. You can also set `DisableImplicitFromServicesParameters` to `false` in `AddHubOptions` to test that.

Oh.... yes that fixed it. Thank for the quick response! :) 

It appears we did accidentally added not just one, but 37 strings into the service collection while registering configs. There is no point to them being there just reflection gone wrong. Gonna remove them.
