### ISSUE TITLE
Install the BlazorWasmDebugging VS Code extension with the C# extension

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#46485]
The BlazorWasmDebugging extension for VS Code provides functionality for debugging Blazor WebAssembly apps. Currently it has to be installed separately from the C# extension. This functionality should be included with the rest of the .NET development experience that is enabled by the C# extension.

**Comment by Nick-Stanton** [comment]
can be closed following the merge of https://github.com/OmniSharp/omnisharp-vscode/pull/5579
