### ISSUE TITLE
Use SearchValues throughout dotnet/aspnetcore

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/aspnetcore#46484]
Akin to https://github.com/dotnet/runtime/issues/78204

Some uses have already been replaced in #45300, but there are more cases where using `IndexOfAnyValues` can speed things up or simplify the implementation. From a few grep searches:
- [x]  [`PathString.ToUriComponent`](https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Http.Abstractions/src/PathString.cs#L67) can be rewritten along the lines of [`UriHelper.EscapeString`](https://github.com/dotnet/runtime/blob/167112574ebfcfcddfc23267e1ba93eebdcdeaf1/src/libraries/System.Private.Uri/src/System/UriHelper.cs#L110-L219)
- [x]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Http.Abstractions/src/HostString.cs#L120
- [x]  ~~https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/FileProviders/Embedded/src/Manifest/EmbeddedFilesManifest.cs#L87~~ Targets old TFMs
- [x]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Shared/MediaType/HttpTokenParsingRule.cs#L69
- [x]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Shared/HttpRuleParser.cs#L94 (which looks like a copy of the one in Runtime, so could just copy https://github.com/dotnet/runtime/pull/78660)
- [x]  All the checks in https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs
- [ ]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Headers/src/ContentDispositionHeaderValue.cs#L613 (also already done in runtime in https://github.com/dotnet/runtime/pull/78660)
- [ ]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Shared/CookieHeaderParserShared.cs#L238
- [ ]  https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Mvc/Mvc.ViewFeatures/src/Rendering/TagBuilder.cs#L428
- [ ] https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Mvc/Mvc.Razor/src/TagHelpers/UrlResolutionTagHelper.cs#L52

**Comment by adityamandaleeka** [comment]
Some of this was done. Moving to preview 4 to continue chipping away.

**Comment by gfoidl** [comment]
Nit: should the title of this issue be updated to use `SearchValues` (as _IndexOfAnyValues_ got renamed)?

**Comment by madhub** [comment]
Should `SearchValues `also be used in [MultipartReaderStream ](https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/MultipartReaderStream.cs) to find the [boundary](https://github.com/dotnet/aspnetcore/blob/662795d5aa2d4608e33a972415c81699e8af5736/src/Http/WebUtilities/src/MultipartReaderStream.cs#L194) in the multipart parser

**Comment by ladeak** [comment]
I'd be interested in picking up a few items in the coming weeks.

**Comment by ladeak** [comment]
I think with the last PR everything outlined above is covered., hence the lát PR closed this issue.

**Comment by amcasey** [comment]
> I think with the last PR everything outlined above is covered., hence the lát PR closed this issue.

Works for me.  Any remaining concerns @MihaZupan?

**Comment by MihaZupan** [comment]
https://github.com/dotnet/aspnetcore/blob/79ef5e329b1e31c3775a1977798253cc8f7da6cc/src/Http/Headers/src/ContentDispositionHeaderValue.cs#L618 (see [similar code in dotnet/runtime](https://github.com/dotnet/runtime/blob/c1a4c9c48f215547679b49f8e2fce5077a63f945/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderUtilities.cs#L68)) looks like the only remaining place from my initial list, but I don't think we need to keep the issue open for that.

Thank you for the help @ladeak

**Comment by ladeak** [comment]
Ah, I missed that. I will do the final PR.
