### ISSUE TITLE
Adding AddDefaultHttpJsonOptions extension method

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#46490]
## Background and Motivation

Recently, ASP.NET Core (MVC and Minimal APIs) were updated to use AOT/Trimmer-safe json serializer overloads. As part of this work a `JsonOptions` is pre-configured with a reflection-based resolver `DefaultJsonTypeInfoResolver`

https://github.com/dotnet/aspnetcore/blob/249dfcb2bc5dd30152ce10c47e8c77f2cc95ca81/src/Http/Http.Extensions/src/JsonOptions.cs#L30

https://github.com/dotnet/aspnetcore/blob/249dfcb2bc5dd30152ce10c47e8c77f2cc95ca81/src/Mvc/Mvc.Core/src/JsonOptions.cs#L46

While this change was correct, when it was applied, after the introduction of a new behavior to `AddContext` (https://github.com/dotnet/runtime/issues/80527) all applications where `TrimmingAppContextSwitches.EnsureJsonTrimmability` is `false` won't use a source-gen context when calling `AddContext` since the `DefaultJsonTypeInfoResolver` was first added and the reflection-based resolver will be able to resolve any requested `JsonTypeInfo`.

## Proposed API

My proposal is an introduction of a new `IServiceCollection` extension method `AddDefaultHttpJsonOptions` that will be responsible for make sure the right default configurations for `Microsoft.AspNetCore.Http.Json.JsonOptions` are set and in the appropriated order, eg.: `PostConfiguration responsible for configure reflection-based resolver`.

Also, to keep the behavior consistent I'm proposing an introduction of a new `static getter` `Default` that returns a cached/pre-configured default instance of `Microsoft.AspNetCore.Http.Json.JsonOptions`.

```diff
namespace Microsoft.Extensions.DependencyInjection;

public static class HttpJsonServiceExtensions
{
+    public static IServiceCollection AddDefaultHttpJsonOptions(this IServiceCollection services) {}
}

namespace Microsoft.AspNetCore.Http.Json;

public class JsonOptions
{
+    public static JsonSerializerOptions DefaultSerializerOptions  { get; }
}
```

#### AddDefaultHttpJsonOptions
``` c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDefaultHttpJsonOptions();
var app = builder.Build();
app.Run();
```

#### Static default property
``` c#
var typeInfo = JsonOptions.DefaultSerializerOptions.GetTypeInfo(typeof(string));
var json = JsonSerializer.Serialize("test", typeInfo);
```

## Risks

N/A

**Comment by eiriktsarpalis** [comment]
> public static JsonSerializerOptions DefaultSerializerOptions  { get; }

Why not just use `JsonSerializerOptions.Default` here?

**Comment by eerhardt** [comment]
Closing as this is no longer relevant. `AddContext` is being obsoleted in https://github.com/dotnet/runtime/pull/84022. The current strategy is:

1. JsonOptions sets the `TypeInfoResolver` to `DefaultJsonTypeInfoResolver` at construction-time based on the [System.Text.Json feature switch](https://github.com/dotnet/runtime/issues/83279) allowing Reflection or not. If Reflection isn't allowed, it leaves it `null`.
2. From there, the app, and libraries who need to add their own `JsonTypeInfoResolver`, should add their resolvers to the beginning of the chain. The app developer can ultimately reorder, insert, remove, etc the resolvers as needed with the [TypeInfoResolverChain API](https://github.com/dotnet/runtime/pull/83358).

With this strategy, we no longer need this API.
