### ISSUE TITLE
Move generating IIS profiles in launchSettings.json from template to VS

### ISSUE THREAD

**Issue by maartenba** [dotnet/aspnetcore#46501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Currently, web templates generate IIS profiles in all `launchSettings.json` files. Not every dev team is using IIS, and for folks exclusively using macOS or Linux in their teams it's just noise and potential frustration when accidentally running the IIS launch profile.

Can a switch be added to the templates to skip generating the IIS profiles?

**Comment by mkArtakMSFT** [comment]
@DamianEdwards what do you think about this ask?

**Comment by Tratcher** [comment]
Here's a prior copy (maybe not the latest):
```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:54273/",
      "sslPort": 44367
    }
  },
  "profiles": {
    "Cookies": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
This is harmless and easily to delete, but noisy.

It could be trimmed down to:
```json
{
  "profiles": {
    "Cookies": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```

**Comment by captainsafia** [comment]
Triage: We want to be careful about having too many options in the `dotnet new` prompt.

The added complexity to the user experience introduced by another flag doesn't seem worth the benefit.

The one-time cost of removing the settings after creating the template is also pretty low.

**Comment by maartenba** [comment]
Given the number of parameters in e.g. https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/.template.config/template.json, I would think one more wouldn't hurt 😅

I appreciate the team may not have the bandwidth to look into this for now, but would a PR be considered for this?

**Comment by DamianEdwards** [comment]
Given we changed the default launch profile from IIS to Kestrel a few versions back now, another approach we could consider here is to remove the IIS profile from the template completely. We could then look at changing VS to add it on-demand if a user selects IIS from the launch/debug drop-down (i.e. always show an entry for IIS Express even if a profile isn't defined, and then if it's selected, add the profile JIT).

@sayedihashimi

**Comment by sayedihashimi** [comment]
I like the idea of adding an IIS Express entry and creating that “on the fly”, Bill is OOF so I can’t get his take on this but let’s see if @vijayrkn has any thoughts.

**Comment by DamianEdwards** [comment]
I believe we already have logic in VS to automatically create a `launchSettings.json` on launch if one isn't present in the project so this feels like a reasonable extension of that.

**Comment by vijayrkn** [comment]
We already have the notion of "dynamic profile" and that is used by WSL profiles in VS. They are only persisted to launchSettings.json when the option is selected. I believe we should be able to extend this to other profile types as well. 

I am assuming that this would be a .NET8.0+ only change right?

**Comment by SimonGeering** [comment]
If the decision to add the IIS entry on the fly is to be taken, then please don't assume everyone is using visual studio, there are many folks on the CLI, and in other tools who still need to add IIS.

Not withstanding the fact that one place it would be handy to generate IIS compatible configuration from IIS express is on servers with no IDE.

To be clear I delete it straight away in most cases too, but if we are going to consider replacing functionality for alternatives when the existing works in CLI then please let's not repeat the whole hot reload is VS only debacle 😁

**Comment by DamianEdwards** [comment]
@SimonGeering launching via IIS or IIS Express is only supported in Visual Studio. It's a development-time only feature and doesn't impact where the app is deployed to for production.

**Comment by DamianEdwards** [comment]
@vijayrkn That's good news! Yes this would be a change in the templates targeting net8.0 but the VS behavior wouldn't have to be limited to that I think. The dynamic profile could work exactly like the WSL profile you mention and will not impact any existing launchSettings.json file unless selected.

**Comment by sayedihashimi** [comment]
@DamianEdwards we have made the change in Visual Studio 2022 17.10 to show IIS Express as an option even if it's not in `launchSettings.json`. When the user selects IIS Express we will then add the entry into launchSettings.json.

Please proceed with making the template change to remove IIS Express from `launchSettings.json`.

cc @vijayrkn @BillHiebert

**Comment by DamianEdwards** [comment]
@sayedihashimi hmm I'm not seeing it? 
![image](https://github.com/dotnet/aspnetcore/assets/249088/932f16a2-e6de-4e9a-b3e5-99e8f15824cd)

**Comment by sayedihashimi** [comment]
@vijayrkn or @BillHiebert  do you know what version of VS the change is in?

**Comment by DamianEdwards** [comment]
@sayedihashimi I see it on internal preview builds only: 
![image](https://github.com/dotnet/aspnetcore/assets/249088/29e5f076-b64c-46d9-8cc5-82980337e409)

**Comment by sayedihashimi** [comment]
Yes, it hasn't been released publicly yet. Just giving you an early heads up that you can make the template change.
