### ISSUE TITLE
HTTP/3: Verify HTTP/3 works on expected platforms

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#46500]
Today all of aspnetcore's HTTP/3 tests are conditional [on whether HTTP/3 is supported](https://github.com/dotnet/aspnetcore/blob/20c7ae1791f8ee01de42c7ad6568f7c611c6ec43/src/Shared/TransportTestHelpers/MsQuicSupportedAttribute.cs).

To ensure that HTTP/3 works where we expect it to (Linux with the required package installed, Win11 or later) we should have smoke tests that assert `QuicConnection.IsSupported` is true and a basic HTTP request can be made over HTTP/3 to Kestrel.

**Comment by Tratcher** [comment]
Make it an interop test with HttpClient.
