### ISSUE TITLE
How to setup Blazor custom elements in a WordPress website

### ISSUE THREAD

**Issue by aryehsilver** [dotnet/aspnetcore#46516]
@SteveSandersonMS showed in [What's new for Blazor in .NET 7 | .NET Conf 2022](https://youtu.be/evW4Gj4sHsk?t=992) setting up custom elements with Blazor Server to be used within a WordPress site.

I'm trying to use this, but getting stuck with a severe lack of documentation in this regard. How do I need to setup the Blazor site? I have installed the WordPress and is running correctly. If I add the published files from Blazor into the same root as the WordPress it doesn't startup. I get a 404 on the `_framework/blazor.server.js` file.

Do I need to edit the `web.config` file to allow both to run?

It is also confusing about whether they both need to be running on the same domain or just the same host. Different ports?

**Comment by SteveSandersonMS** [comment]
> It is also confusing about whether they both need to be running on the same domain or just the same host. Different ports?

You would ideally want them to be running on the same origin (same domain and port). For the demo, I used nginx as a reverse proxy in front of both .NET and Wordpress applications, so the nginx origin was serving both of them.

In case it helps to clarify, here's the nginx config I used. Note that some of it is specific to running inside Docker, so you'd likely want to edit that if you're not using Docker.

```
server {
  listen 80;
  listen [::]:80;
  server_name localhost;
  proxy_ssl_verify off;

  location / {
    proxy_pass http://host.docker.internal:8000;
  }

  # Proxy to Blazor Server
  location /_framework {
    proxy_pass https://host.docker.internal:7246/_framework;
  }
  location /_blazor {
    proxy_pass https://host.docker.internal:7246/_blazor;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location /_content {
    proxy_pass https://host.docker.internal:7246/_content;
  }
  location /edit {
    return 301 https://localhost:7246$uri;
  }
}
```

Also I should be clear that we don't specifically own support for Nginx or Wordpress, so if you have issues with those we probably couldn't answer detailed questions about them here. I'm just providing the config same above in the hope that it helps, but for any Nginx questions please consult their docs/support :)

**Comment by MrYossu** [comment]
@SteveSandersonMS I had been wondering the same thing as @aryehsilver, but am not much clearer having read your reply. 

Are you saying the only way we can do this is by using Nginx? If so, please can you be a little more specific about which Nginx product or service you're using. I understand you're not offering Nginx support, but having looked at their web site, I have no idea where I would even start, so whilst I appreciate you sharing your config file, it doesn't help without knowing what you're doing.

Thanks

**Comment by aryehsilver** [comment]
@SteveSandersonMS thanks for your reply.
Just to clarify, you always need to have something interfacing between the end user and the apps running. In your case you used a reverse proxy. Each app must run independently, then you can have something calling specifics from each app.

[@MrYossu Nginx do have many options but you can use the open source which also supports reverse prox. [See here for more info](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).]

**Comment by aryehsilver** [comment]
I have setup the Blazor Server app as a virtual app in a sub directory of the main site so that they are both running on the same domain, host and port.
Blazor throws an error though 404 for _blazor/initializers this I presume is due to it looking for this location in the top level domain and not the sub.
I have set the base to the sub as seen here:
![image](https://user-images.githubusercontent.com/55258552/217972005-f9627f83-33d2-4dff-a7f0-e0b04678114c.png)
The _framework/blazor.server.js loads fine but it throws an error trying to get the initializers.

**Comment by MrYossu** [comment]
And why hasn't there been any activity? Because he's waiting for YOU to respond! So am I by the way.

Instead of ignoring issues and then closing them, how about answering them?

**Comment by SteveSandersonMS** [comment]
@aryehsilver The code shown above looks incorrect to me:

```html
<base href="/cel">
```

... should be:

```html
<base href="/cel/">
```

Because without the trailing slash, the browser will consider `/cel` to be a page, not a directory, and so it would have no effect on the base href.

**Comment by aryehsilver** [comment]
@SteveSandersonMS I tried that too but it still threw an error. Same 404 as without the slash.
