### ISSUE TITLE
Limitation with using Multiple Cookie Authentications

### ISSUE THREAD

**Issue by jamezamm** [dotnet/aspnetcore#46528]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi,

As a simple example, I am declaring two cookie authentication schemes in **Program.cs**:

`builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)`
`          .AddCookie(options => {`
`               options.ExpireTimeSpan = TimeSpan.FromMinutes(45);`
`               options.SlidingExpiration = true; })`
`          .AddCookie("Cookie2", options => {`
`               options.ExpireTimeSpan = TimeSpan.FromDays(14); });`

Then I sign in to both cookie authentication schemes. P.s I can confirm that a cookie is created for each scheme, two in total.

`await _context.HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,`
`       new ClaimsPrincipal(new ClaimsIdentity(new List<Claim> { new Claim(ClaimTypes.Name, username) })));`
`await _context.HttpContext.SignInAsync("Cookie2",`
`       new ClaimsPrincipal(new ClaimsIdentity(new List<Claim> { new Claim(ClaimTypes.Name, "TEST123") })));`

To access the name claim of the default authentication scheme:

`HttpContext.User.Identity.Name`

To check whether the cookie that has been created by the default authentication scheme, is still alive:

`HttpContext.User.Identity.IsAuthenticated`

There seems to be no way to access the claims of the "Cookie2" authentication scheme and to check whether the cookie is still alive. 

### Expected Behavior

I would expect such information to be available within HttpContext.User but under different identities.

### Default Authentication Scheme

**To access name claim:**

`HttpContext.User.Identity.Name`

**To check whether the cookie is still alive:**

`HttpContext.User.Identity.IsAuthenticated`

### "Cookie2" Authentication Scheme

**To access name claim:**

`HttpContext.User.Identities.First(x => x.AuthenticationType == "Cookie2").Name;`

**To check whether the cookie is still alive:**

`HttpContext.User.Identities.First(x => x.AuthenticationType == "Cookie2").IsAuthenticated;`

### .NET Version

7

**Comment by Tratcher** [comment]
Only the default cookie as specified by `AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)` is used to populate HttpContext.User. The others are accessible by calling ` await HttpContext.AuthenticateAsync("Cookie2");` If you tell a controller or authorization policy to check both auth types then you should get a combine result.

**Comment by jamezamm** [comment]
Thanks. I can work with `await HttpContext.AuthenticateAsync("Cookie2");`
