### ISSUE TITLE
DOTNET_ROOT while running tests

### ISSUE THREAD

**Issue by tmds** [dotnet/aspnetcore#46524]
`DOTNET_ROOT` is used to resolve ASP.NET Core folders in two places:

https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/src/Framework/test/TargetingPackTests.cs#L28-L32

https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/src/Framework/test/SharedFxTests.cs#L27-L31

What is `DOTNET_ROOT` supposed to be set to?
Can it be the root of the the dotnet installation that is used for the build?
Or should it be set to something that contains the ASP.NET Core bits that got build? To what?

I've currently set it to the first (`<repo>/.dotnet`), and I get test failures for:
```
Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsExpectedFiles
Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsListedAssemblies
Microsoft.AspNetCore.SharedFxTests.RuntimeListContainsCorrectEntries
Microsoft.AspNetCore.TargetingPackTests.PlatformManifestListsAllFiles
```
which look like:
```
Xunit.Sdk.EmptyException: Assert.Empty() Failure\nExpected: <empty>\nActual:   [\"System.Diagnostics.EventLog.Messages\"]
at Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsExpectedFiles() in /_/src/Framework/test/SharedFxTests.cs:line 81
```

My build uses these two commands:
```
eng/build.sh --ci --arch x64 -c Release --restore --build --pack
eng/build.sh --ci --arch x64 -c Release --test
```

@dougbu am I using the proper value for `DOTNET_ROOT`?

cc @omajid

**Comment by dougbu** [comment]
The easiest thing to do is to do what you're doing (except _don't_ set `DOTNET_ROOT` manually) I think. Not sure what's going South unless the tests no longer run correctly except on Helix agents.

One thing to try would be `. activate.sh` in the root of the repo, then `dotnet test --no-build` in the Framework tests folder.

Another option would be to check the Arcade repo and see if something there is _supposed_ to set the environment variable or recently stopped setting it. That might be confusing however because it includes some of the Helix support code.

**Comment by tmds** [comment]
`activate` will set it to the same value as I have:
https://github.com/dotnet/aspnetcore/blob/287d7eab1c644bce2d4c96751bc3d323362b1bb7/activate.sh#L69

I don't know why this test is looking at the ASP.NET Core framework that is with the build SDK, rather than the one that got built. I haven't tried to understand what the test is trying to verify.

Because I seem to be setting it to the proper value, it may be indicating an issue with my build or build configuration.

**Comment by tmds** [comment]
@JunTaoLuo I'm trying to understand why the tests you've added in https://github.com/dotnet/aspnetcore/pull/23045 are failing for me.

I'm using the `activate` script as described in https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md.
This sets `DOTNET_ROOT` (which is used by the test to locate ASP.NET Core directories) to `<repo>/.dotnet`.

I wonder if this is the right location, since that is not something that got built, but it is the sdk that that was used to perform the build.

Can you provide some insights?

**Comment by tmds** [comment]
I took a closer look at this.
The most interesting find was that the `DOTNET_ROOT` gets updated by the ASP.NET Core build.
And what got added then gets checked by these tests.

The test expects to find `System.Diagnostics.EventLog.Messages`, but it is missing.

It seems there is something special about this assembly:

https://github.com/dotnet/aspnetcore/blob/cf45172b7d025fa71803b39c6d454cc3a3d9b6bd/src/Framework/test/Microsoft.AspNetCore.App.UnitTests.csproj#L21-L25

@dougbu should the test be updated to no longer expect this assembly?

**Comment by dougbu** [comment]
> @dougbu should the test be updated to no longer expect this assembly?

No, it _should_ come from the System.Diagnostics.EventLog package. What's "special" is this is one of the few non-tool non-sharedFx packages dotnet/runtime produces containing more than one assembly.

**Comment by tmds** [comment]
There is another test that fails for me in this suite, I had not looked at it further.

I have now, and it is hard coded for Windows:

https://github.com/dotnet/aspnetcore/blob/ac542f4916b26fde739fd146511be70898af233a/src/Framework/test/SharedFxTests.cs#L329

The test passes when I update it to find the proper file on the Linux build.

This probably means that these tests don't run on Linux in CI.

I closely followed the steps from https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md by executing the following commands.

```
git clone --recursive https://github.com/dotnet/aspnetcore
cd aspnetcore/
./restore.sh
source activate.sh
cd src/Framework/test/
dotnet build
dotnet test
```

With these commands, the tests still fail.
They report that `System.Diagnostics.EventLog.Messages` is missing in the ASP.NET Core shared folder that was built.

When I look for this assembly in the source-built release of .NET 7 on Fedora, it is not there either.
Same thing on Microsoft's Linux build for .NET 7.
On Microsoft's Windows build the file exist. So on Windows, these tests will pass.

So either this file should not be there in the Linux build, and we can update the test for that.
Or it should be there, and this is a product bug.

**Comment by tmds** [comment]
> So either this file should not be there in the Linux build, and we can update the test for that.
Or it should be there, and this is a product bug.

I assume it's the first because the EventLog is a Windows thing.

**Comment by dougbu** [comment]
> > So either this file should not be there in the Linux build, and we can update the test for that.
> > Or it should be there, and this is a product bug.
> 
> I assume it's the first because the EventLog is a Windows thing.

Agreed. Comparing the 7.0.2 packages at <https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.win-x64> and <https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.linux-x64>, one main difference is the lack of System.Diagnostics.EventLog.Messages.dll in the second. I thought the tests already accounted for System.Diagnostics.EventLog.Messages being Windows-only&hellip;

Oh, I see: The tests _run_ on macOS, Linux, and Windows but using only the Windows-_built_ shared framework package in Helix. That is, the Helix testing expects jobs submitted from a Windows build agent. Probably worth fixing.

![image](https://user-images.githubusercontent.com/6431421/218285834-c9f2ca10-dc9b-40f6-955f-d82af2dcbd61.png)

Separately, what does this have to do with `DOTNET_ROOT`❔

**Comment by tmds** [comment]
> Separately, what does this have to do with DOTNET_ROOT

These tests look for the ASP.NET framework at DOTNET_ROOT. The issue might have been it was not set to the right location. While debugging I learned the build SDK (that it points to) actually gets updated with the built framework.

> The tests run on macOS, Linux, and Windows but using only the Windows-built shared framework package in Helix. That is, the Helix testing expects jobs submitted from a Windows build agent. Probably worth fixing.

Yes, if we update the test so it works on Linux, the ci job will fail when it is given the Windows artifacts.

How do we change this?
Is it helpful if I make a PR with the test changes?

**Comment by dougbu** [comment]
> How do we change this?

Keep looking in `DOTNET_ROOT` but, if not running on Windows and `$env:HELIX_WORKITEM_ROOT` is empty i.e., the tests are running locally (and using a locally-built shared framework), don't expect `System.Diagnostics.Eventlog.Messages.dll` in the shared framework directory. Change the expectations of the affected test or tests for this case.

> Is it helpful if I make a PR with the test changes?

A PR would be much appreciated @tmds❕
