### ISSUE TITLE
Would be nice if Virtualized blazor component keeps a head and a tail of objects

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#46526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Sometimes, stuff changes therefore we need to re-render the content.

In spirit of minimizing our efforts, I am not going to build the new content immediately because for example, 10k log messages that's newly discovered and needed to be sorted and joined with my original messages, that's copying and sorting an array, I am going to use a link list so I am not copying everything I've cached in memory, and I am not going to join all the new messages, but only ones that are *in range of client window*, so you get the most up to date information and I can incrementally build and update my model as user scroll.

It would be easier to implement, if the ```Virtualized``` blazor component keeps track of the head and the tail of the object currently in view, so I can just do a comparison with them, see if a new message has a time stamp between them for example. I can do this myself by giving id to all the objects being rendered and use javascript to get the first and last element that's in view with their id, then relate it back to my objects but this doesn't feel like my language but rather since it involves the browser and fit the theme of the Virtualized component of making things more efficient I would say please can you implement it

### Describe the solution you'd like

One :
Whenever virtualized decides to render something from a bunch of objects, because they are requested and in view, keep two reference (head, tail)
Exposing these reference inside property

Two (Alternatively) :
Have two method (head, tail), that finds the first and last object in view

### Additional context

Because Virtualized component is doing the rendering, it knows what it's putting on the screen, therefore it's actually doable without JSInterop which is great

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It seems it would be quite simple to implement a custom ItemsProvider and expose those two references to fit your needs, and later use them as you wish. To learn more about ItemsProvider please look at our documentation here: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#item-provider-delegate
