### ISSUE TITLE
String array queries do not use commas to separate each element

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/aspnetcore#46530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Arrays or enumerables of `string` are incorrectly serialized when using them as a query parameter inside a controller method. For example, the input array `string letters = { "d", "g", "o" };` gets serialized to the query string `"?letters=d&letters=g&letters=o"`.

The reason why I'm making an issue here is because someone made a very similar issue on the [Swashbuckle repository](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1394) and they believe it is an upstream issue in the .NET implementation.

### Expected Behavior

The query string should be simplified to `"?letters=d,g,o"` in situations where the [OpenAPI style specifications](https://spec.openapis.org/oas/latest.html#style-examples) allow it (such as this one).

### Steps To Reproduce

1. Make a new ASP.NET Core 7 Web API named MyApi (`dotnet new webapi -f net7.0 -o MyApi`)
2. Add the following `CombinationsController`

```cs
[ApiController]
[Route("api/v1/[controller]")]
public class CombinationsController : Controllerbase
{
    [HttpGet]
    public async Task<IActionResult> Get([FromQuery] string[] letters)
    {
        return NoContent();
    }
}
```

3. Make sure Swagger is enabled
4. Run (or debug) the API and go to the Swagger index page
5. Try out the `api/v1/combinations` route on the `Combinations` controller
6. Add `d`, `g` and `o` as the input characters and execute

The resulting request URL contains the query `?letters=d&letters=g&letters=o` instead of `?letters=d,g,o`.

### .NET Version

7.0.101

### Anything else?

I'm using ASP.NET Core 7 with Visual Studio Code 1.75.0 as my editor
```bash
$ dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by javiercn** [comment]
@JansthcirlU thanks for contacting us.

I believe this is by design. Arrays are serialized in that fashion for historical reasons and backwards compatibility with older versions of MVC as well as the model binding system.

**Comment by javiercn** [comment]
@JansthcirlU if I understood correctly, the issue you are having is that `?letters=a,b,c` is not binding correctly to an array with three elements, is that the case?

**Comment by JansthcirlU** [comment]
@javiercn correct, using `?letters=a,b,c` creates an array with a single element `"a,b,c"` rather than three elements for each letter.

**Comment by javiercn** [comment]
@JansthcirlU You can author a custom model binder for the parameter and apply it with an attribute.

**Comment by JansthcirlU** [comment]
@javiercn okay, I'll investigate that approach!
