### ISSUE TITLE
Different implementations of `GenerateRadioButton()` and `GenerateCheckBox()` in `DefaultHtmlGenerator.cs`

### ISSUE THREAD

**Issue by ChrisxHart** [dotnet/aspnetcore#46535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `IHtmlGenerator` method `GenerateRadioButton()` with a `null` `modelExplorer.Model` value, an added `checked` attribute will be removed from the attribute output, whereas `GenerateCheckbox()` allows a `checked` attribute to be passed in with a `null` `modelExplorer.Model` value.

Snippet from `GenerateRadioButton()`:
```CSharp
if (modelExplorer == null)
{
    //... 
}
else
{
    // RadioButtonFor() case. That API does not support passing isChecked directly.
    Debug.Assert(!isChecked.HasValue);

    // Need a value to determine isChecked.
    Debug.Assert(value != null);

    var model = modelExplorer.Model;
    var valueString = Convert.ToString(value, CultureInfo.CurrentCulture);
    isChecked = model != null &&
        string.Equals(model.ToString(), valueString, StringComparison.OrdinalIgnoreCase);
}

if (isChecked.HasValue && htmlAttributeDictionary != null)
{
    // Explicit isChecked value must override "checked" in dictionary.
    htmlAttributeDictionary.Remove("checked");
}
```

Snippet from `GenerateCheckBox()`:
```CSharp
if (modelExplorer != null)
{
    // CheckBoxFor() case. That API does not support passing isChecked directly.
    Debug.Assert(!isChecked.HasValue);

    if (modelExplorer.Model != null)
    {
        if (bool.TryParse(modelExplorer.Model.ToString(), out var modelChecked))
        {
            isChecked = modelChecked;
        }
    }
}

var htmlAttributeDictionary = GetHtmlAttributeDictionaryOrNull(htmlAttributes);
if (isChecked.HasValue && htmlAttributeDictionary != null)
{
    // Explicit isChecked value must override "checked" in dictionary.
    htmlAttributeDictionary.Remove("checked");
}
```

As shown above, `isChecked` is set to false if `model` is `null` in `GenerateRadioButton()`, which removes any added `checked` attribute. 

In the case of `GenerateCheckBox()`, it allows passing in a `checked` attribute if `null` `model`.

### Expected Behavior

If a `null` `modelExplorer.Model` value is passed to `GenerateRadioButton()`, an additional `checked` attribute should not be stripped from the output, which would match the behavior of `GenerateCheckBox()`.

### .NET Version

6.0.200

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
These are two different APIs and yes, they do behave slightly differently. Given that changes in this area will be breaking in nature and there is no real problem here we're closing this issue.
