### ISSUE TITLE
Expose the original status code in StatusCodeReExecuteFeature

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#46538]
## Background and Motivation

Motivated by #40518: when the `UseStatusCodePagesWithReExecute` middleware requests a page handled by the `UseStaticFiles` middleware, the status code is clobbered and replaced with 200.  Retaining and exposing it on `StatusCodeReExecuteFeature` makes it possible for users to restore it.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Diagnostics;

public interface IStatusCodeReExecuteFeature
{
+    /// <summary>
+    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
+    /// </summary>
+    int OriginalStatusCode { get; set; }
}

public class StatusCodeReExecuteFeature : IStatusCodeReExecuteFeature
{
+    /// <inheritdoc/>
+    int OriginalStatusCode { get; set; }
}
```

## Usage Examples

```csharp
app.UseStaticFiles(new StaticFileOptions
{
    OnPrepareResponse = responseContext =>
    {
        var context = responseContext.Context;
        if (context.Response.StatusCode == StatusCodes.Status200OK &&
            context.Features[typeof(IStatusCodeReExecuteFeature)] is IStatusCodeReExecuteFeature statusCodeFeature)
        {
            context.Response.StatusCode = statusCodeFeature.OriginalStatusCode;
        }
    }
});
```

## Alternative Designs

```csharp
    /// <summary>
    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
    /// Returns 0 if the concrete type does not provide its own implementation.
    /// </summary>
    int OriginalStatusCode
    {
        get => 0;
        set => throw new NotSupportedException();
    }
```

This version won't break existing implementors of `IStatusCodeReExecuteFeature`, but it has the downside that the caller needs to know to check for `0` (or `null` if we prefer that as a sentinel value).

We could also drop the setter entirely, since there's no real justification for having one, other than that the other interface properties do.

## Risks

This is the first member of `IStatusCodeReExecuteFeature` populated from the response, rather than the request, which might make it surprising to consumers.

**Comment by amcasey** [comment]
In fairness, I should say that most of the ~blame~ credit for this should go to @Tratcher for his comments on #40518.

**Comment by halter73** [comment]
API Review Notes:

- Do we want a setter? The other later additions to `IStatusCodeReExecuteFeature` like `Endpoint` and `RouteValues` don't have it.
- What should the default implementation of the getter do? Should we make `OriginalStatusCode` nullable? Or is 0 sufficient for unset? Or can it throw? `Endpoint` and `RouteValues` return null, but we think only new code with an updated implementation will call this, so let's throw a `new NotImplementedException()`.

Api Approved!

```diff
namespace Microsoft.AspNetCore.Diagnostics;

public interface IStatusCodeReExecuteFeature
{
+    /// <summary>
+    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
+    /// </summary>
+    int OriginalStatusCode => throw new NotImplementedException();
}

public class StatusCodeReExecuteFeature : IStatusCodeReExecuteFeature
{
+    /// <inheritdoc/>
+    int OriginalStatusCode { get; private set; }
}
```

**Comment by amcasey** [comment]
```diff
- int OriginalStatusCode { get; private set; }
+ int OriginalStatusCode { get; set; }
```

...to match the other properties on the concrete type and make it settable from `StatusCodePagesExtensions`.

**Comment by BrennanConroy** [comment]
Should probably be `internal set;`, the original properties were all from a time when we didn't do API reviews and sort of did whatever we felt like.
