### ISSUE TITLE
Problem with conuming blazor server custom element through another webApp!

### ISSUE THREAD

**Issue by hdv212** [dotnet/aspnetcore#46531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi everyone!!
To reproduce problem, Please follow [this link](https://learn.microsoft.com/en-us/answers/questions/1168557/problem-with-conuming-blazor-custom-element-throug?comment=question#newest-question-comment) & steps!
Thanks in advance

### .NET Version

7.0

**Comment by hdv212** [comment]
Hi again
Sure!
Please download my sample projects from this [repo](https://github.com/hdv212/BlazorServerCustomElementProblem/blob/main/ReproSample.zip). Then follow this steps to reproduce the problem :

1. Open 'CustomEelementSample01' project via vs2022 and publish it to iis (give a path in iis something like this : http://localhost/CustomElements/)
2. The folder with name 'CustomElementConsumer' is just a simple html file with some code & assets. Open it via notepad (or any code editor) and replace css & script path with the correct website url that created in previous step. Then publish this simple static site in iis.
3. Now you can should open your static webSite which created in previous step and see the problem (custom element in blazor-server not showing).
4. Also you can use console to show more more info about the problem(s) ...

Thanks in advance

**Comment by Nick-Stanton** [comment]
Hi @hdv212, it appears from my understanding that you are trying to:

1. Publish a Blazor server application with your custom element components to IIS, but without starting `blazor.server.js` (using `autostart="false"`).
2. Publish a new, separate HTML file as a different IIS site that references your Blazor server app's `blazor.server.js` as well as where your custom elements are published.
3. Start your Blazor server app's `blazor.server.js` from your second, separate IIS site and use that to render your custom element components.

Am I understanding your goal correctly? I can summarize briefly where and why your error is occurring, but I do not think this is a supported scenario. When Blazor server starts, the path for the `fetch()` request that grabs the initializers uses the `baseURI` of the document calling the script - in this case, your second IIS site. It makes sense that an error happens here, as all of the necessary Blazor server pieces are in your first application. Is there a specific reason that you're trying to render Blazor components outside of Blazor server? Clarification might help find either a workaround or a definitive answer on whether this is/isn't supported.

**Comment by hdv212** [comment]
Hi [Nick-Stanton](https://github.com/Nick-Stanton)

> Is there a specific reason that you're trying to render Blazor components outside of Blazor server?

Based on blazor 7 new features, a new feature is custom elements that means you can call blazor components outside of it (for example wordpress site). The specific component should labeled as custom element.
Now, based on the given new feature, i want to call blazor server components (as custom element) in other website.
Hope this clarify my goal.
Thanks in advance

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can't host Blazor Components which require Blazor Server for interactivity, in a static website. You will still need to have the host for the Blazor Server to enable interactivity the component requires.
The only option for static site hosting would be Blazor WebAssembly.

**Comment by hdv212** [comment]
Thanks for reply
Can u give me a sample that use blazor server components as custom element (both blazor server app & consumer website)?
thanks in advance
