### ISSUE TITLE
Session getting null when trafic increase on site

### ISSUE THREAD

**Issue by shailesh64** [dotnet/aspnetcore#46547]
I have hosted the .net 6.0 application on iis. This application build on asp.net mvc . Recently I have converted to .net 6.0 
I face the issue when traffic increase the it clear the session so user redirected to login again.
Our application fully dependent on session it's a flight and hotel booking portal.  
Please suggest me the solution.

**Comment by Tratcher** [comment]
You're mixing concepts of user session (auth) and browser session (state). The two should be used independently. Which session is being disrupted?

Can you share the setup code you used to add and configure these components?

**Comment by shailesh64** [comment]
Browser session state is disrupted.I have set some session i.e HttpContext.Session.SetString(key,value);
When load increase on site at that time this session becomes null .

![image](https://user-images.githubusercontent.com/13448285/218003105-57f9ab4a-a352-4d45-96cc-3bb9da55b39c.png)

**Comment by Tratcher** [comment]
Session is stored in a memory cache that has a 200mb size limit by default. See AddDistributedMemoryCache to update that. When the limit is exceeded then old entries are dropped.
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryDistributedCacheOptions.cs#L12

How much RAM are you willing to let it consume? If you need more space consider moving to an external store:
https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-7.0#establish-distributed-caching-services
