### ISSUE TITLE
Can we use a BlazorApp without having the "_framework/blazor.server.js" reference added?

### ISSUE THREAD

**Issue by neetutanwar** [dotnet/aspnetcore#46554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team,

We want to use Blazor Appliation for our website, and want to leverage the reusable components features. But we don't want to make the site stateful as we cannot enable the ARR affinity and Websocket for our hosting app service which is the mandatory requirements for publishing a blazor application to azure app service. 

**Referenced  Links:** https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1
https://learn.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-3.1

We don't have the SPA requirement and the controls interaction (like click event, onchange event etc.), we will handle through javascript code only. 

The main feature that we would like to use, is the Reusable components (.razor components). We have explored different ways to use the .razor(Blazor) components in a normal .Net core/MVC app, there are many options but they don't seem to be worked in a fully reusable manner e.g. we won't be able to use the nested components etc.

The only option we can think of is: We  create a Blazor server app and remove the reference of the "**_framework/blazor.server.js**" JS  as that JS is what makes the blazer components interactive and also create the signalR connection. 

We are seeking some guidance if we can go with this approach, will there be any downsides of removing the "**_framework/blazor.server.js**" JS reference? Please advise. 

Thanks in advance!

**Comment by javiercn** [comment]
@neetutanwar thanks for contacting us.

Are you trying to build a purely server rendered app with Razor Components or are you trying to reuse components inside an MVC/Razor pages app.

**Comment by neetutanwar** [comment]
> @neetutanwar thanks for contacting us.
> 
> Are you trying to build a purely server rendered app with Razor Components or are you trying to reuse components inside an MVC/Razor pages app.

Hi @javiercn We are trying to reuse the components inside an asp.net core MVC app

**Comment by javiercn** [comment]
@neetutanwar as long as you are rendering static components only, you'll be able to use them.

Keep in mind though that once you render a component you can't render a tag helper inside it and we do not have integrations for forms with MVC/Razor pages, so you won't have that type of functionality.

If all you care about is rendering component from MVC/Razor pages, you should be able to do so by just rendering the components statically using the component tag helper, but that's as far as our support currently goes.

**Comment by neetutanwar** [comment]
> @neetutanwar as long as you are rendering static components only, you'll be able to use them.
> 
> Keep in mind though that once you render a component you can't render a tag helper inside it and we do not have integrations for forms with MVC/Razor pages, so you won't have that type of functionality.
> 
> If all you care about is rendering components from MVC/Razor pages, you should be able to do so by just rendering the components statically using the component tag helper, but that's as far as our support currently goes.

Hi @javiercn,

Thanks for replying!

We need interactive components, mainly the parameter thing that we have in Blazor components. Is there any way of using the same in any regular net core app e.g. .Net core web app or .Net core MVC app (without Blazor app)

In short, we don't want the event handling (element's click event, etc.) and SPA feature of Blazor components just the reusable components with the parameters exposed and other features that can work without **_framework.js** dependency.

**Comment by danroth27** [comment]
Using Blazor components for server-side rendering is supported using the ComponentTagHelper. You'll want to change the render mode from ServerPrerendered to Static. Interactive features like click handlers and so on won't work, but you'll be able to pass component parameters and render the components to the page. No blazor.server.js script required. We are also tracking on our backlog enabling Blazor style syntax in .cshtml files (#38112), so give that issue a :+1: if that's interesting to you.
