### ISSUE TITLE
Regression - ASP Net Core 7 project when deployed on Azure fails to bind model properly.

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#46550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have a controller decorated with the `ApiControllerAttribute` and then have an action that accepts `IEnumerable<SomeComplexType>`, like the following:

```
public Task ExampleAsync(IEnumerable<SomeComplexType> example)
{
    ...
}
```

For some reason, model binding fails to work and the collection is always empty. When you send the same request, the same payload to a local instance of the project - it works, be it in Release or Debug configuration.

Adding `[FromBody]` to the parameter fixes the problem. The moment this is deployed to Azure - things change for whatever reason.

### Expected Behavior

For the above code to work as expected and not require a `FromBodyAttribute` to "patch" it up.

### .NET Version

7.0.102

### Anything else?

Output of dotnet --info on the build server.
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\
Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb
```

**Comment by kikaragyozov** [comment]
This is an assumption, but this issue did not persist previously when the application was on .NET 6. We haven't tested this out, but we never encountered it back then.

**Comment by brunolins16** [comment]
@kikaragyozov Thanks for contacting us.

This issue should've been fixed already in 7.0.102 (https://github.com/dotnet/aspnetcore/pull/45256). Is the version reported is from your local machine?

> The moment this is deployed to Azure - things change for whatever reason.

Which service are you deploying to?

**Comment by kikaragyozov** [comment]
> @kikaragyozov Thanks for contacting us.
> 
> This issue should've been fixed already in 7.0.102 (#45256). Is the version reported from your local machine?
> 
> > The moment this is deployed to Azure - things change for whatever reason.
> 
> Which service are you deploying to?

We're deploying to Azure App Service. The version I've shared is the one on the build server and on our local machines. Perhaps the machine running the actual application on Azure has a different version?

**Comment by brunolins16** [comment]
> Perhaps the machine running the actual application on Azure has a different version?

Can you share the runtime version following this guide https://learn.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-windows#show-supported-net-core-runtime-versions?

**Comment by kikaragyozov** [comment]
> > Perhaps the machine running the actual application on Azure has a different version?
> 
> Can you share the runtime version following this guide https://learn.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-windows#show-supported-net-core-runtime-versions?

The version we get is `7.0.101`.

After discussing this with our DevOps engineer, it appears that the runtime on azure is automatically updated on a monthly basis, unless deployed as a self-contained application. if this is indeed the case - when will this automatic update be enrolled?

**Comment by brunolins16** [comment]
@kikaragyozov I just checked, and I got the `7.0.102` version in my App Service already. Based on the information published here, App Service indeed roll-out new version monthly (https://learn.microsoft.com/en-us/azure/app-service/overview-patch-os-runtime#how-and-when-are-os-updates-applied) and your app should have it available very soon.

Redeploying or rebooting your app might speed things up.

**Comment by kikaragyozov** [comment]
> @kikaragyozov I just checked, and I got the `7.0.102` version in my App Service already. Based on the information published here, App Service indeed roll-out new version monthly (https://learn.microsoft.com/en-us/azure/app-service/overview-patch-os-runtime#how-and-when-are-os-updates-applied) and your app should have it available very soon.
> 
> Redeploying or rebooting your app might speed things up.

Thank you for clearing this up! If in the future another such bug is encountered, it would be great if you guys could expediate the version update to all App Services. I understand the general idea of why that might be a bad idea - continuous uptime is important, but proper behavior I believe tops that.
