### ISSUE TITLE
Provide a way for ByPassing Authentication & Authorization with Server token

### ISSUE THREAD

**Issue by Lonli-Lokli** [dotnet/aspnetcore#46569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Sometimes you would like to test API and UI in cooperation, but it's too difficult because of infrastructure - database setup, auth setup, etc. It will be useful to have a method that will add static or factory-based tokens as your token for any incoming requests.

### Describe the solution you'd like

I see it as a middleware which might be enabled for Development environment only, and will bypass usual auth mechanism

**Comment by javiercn** [comment]
@Lonli-Lokli thanks for contacting us.

You might be looking for something like https://learn.microsoft.com/es-es/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-7.0&tabs=windows
