### ISSUE TITLE
Net 6.0 Razor Pages basic nagivation problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#46572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-60-Razor-Pages-basic-nagivation-pro/10270460)._

---
[severity:It's more difficult to complete my work]
I have a Solution (MSV) with 2 Razor Pages projects (MSV and Video), sharing SQL database and Identity. All CRUD models are in MSV project. Video project has only few models, to show specific views to customers. I have created few folders inside Identity / Pages folders (Person/WART/Clipes folders), to put my view pages. Now I am facing the following problem in Video project: when I am using  RedirectToPage or LocalRedirect("Identity/Person/WART/Clipes/Index")  I can reach the Index page, but when I am using RedirectToPage or LocalRedirect("Identity/Person/WART/Clipes/ClipesView") I cannot reach the ClipesView page. But everything works in MSV project, where I have the CRUD pages inside each folder. Is it a Razor routing problem or something like "by definition"? Thanks.

---
#### Feedback Bot on 2/5/2023, 07:14 PM: 

(private comment, text removed)
#### Mário Sérgio Veríssimo on 2/6/2023, 02:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by GitCurtir** [comment]
Please, create a new Net 6.0 Web ASP.NET Core with Razor Pages and add Identity. Inside Identity / Pages folder, add 3 Razor Pages - Index, IndexTest and Test. From home or login page, try to navigate to these pages, using RedirectToPage or LocalRedirect. You cannot reach Test page. This is the problem. This smells like a bug.

**Comment by javiercn** [comment]
@GitCurtir unfortunately we require a repro project that is in a runnable state, otherwise we run the risk of missing details that are important and makes potential issues much harder to investigate.
