### ISSUE TITLE
HttpContext not working in Kestrel in Visual Studio Code

### ISSUE THREAD

**Issue by Ninja4Code** [dotnet/aspnetcore#46586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have set up Windows authentication with the Negotiate package but in Kestrel I am noticing that the HttpContext gets dropped after the initial ClaimsTransformation works.  It's later down the pipeline where I'm not getting the context.User in the AuthorizationRoleHandler.  This worked in ASP.NET Core 5/IIS with essentially the same code, except Program was split into Startup, etc.

**I'm noticing that the AuthenticationType is showing as NTLM.  My understanding is that Kerberos will try Negotiate first and will fall back to NTLM.  This seems to be occuring as I see NTLM listed as the AuthenticationType when I'm debugging.**

`builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();`

I'm also wiring up a Claims Transformer.

`builder.Services.AddSingleton<IClaimsTransformation, MyClaimsTransformer>();`

Within the Claims transformer everything is working fine.  It picks up the user identity and assigns the claims;

```
public class MyClaimsTransformer : IClaimsTransformation
{
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
         ClaimsIdentity identity = principal.Identity as ClaimsIdentity;
         //add claims
        return Task.FromResult(principal);
    }
}
```

I've also wired up an HttpContextAccessor

`builder.Services.AddHttpContextAccessor();`

```
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = options.DefaultPolicy;
    options.AddPolicy("AuthenticatedOnly", policy => {
          policy.Requirements.Add(new AuthenticatedRequirement(true));
    ]);
]);
```

builder.Services.AddSingleton<IAuthorizationHandler,AuthenticatedRoleHandler>();`

The problem comes in where I'm using Policies with Requirements.  The AuthorizationRoleHandler is not picking up the user from the context.  This behavior I notice in Visual Studio Code with ASP.NET Core 6.  In a similar project in Visual Studio 2019, ASP.NET Core 5 the basically same code works as expected.  I'm also noticing this behavior when I deploy the application in a Docker container with Kestrel.

```
public class AuthenticatedRoleHandler:AuthorizationHandler<AuthenticatedRequirement>
{
     protected override Task HandleRequirementAsync(AuthorizationContext context, AuthenticatedRequirement requirement)
    {
             **ClaimsPrincipal user = context.User;//Here it is null**
             // other code
     }
}
```

### Expected Behavior

The role handler should be picking up the AuthorizationHandlerContext user, but it is null.

```
public class AuthenticatedRoleHandler:AuthorizationHandler<AuthenticatedRequirement>
{
     protected override Task HandleRequirementAsync(AuthorizationContext context, AuthenticatedRequirement requirement)
    {
             **ClaimsPrincipal user = context.User;//Here it is null**
             // other code
     }
}
```

### Exceptions (if any)

I get a 401 status code Unauthorized on an annotated controller method.

### Anything else?

6.0.13 runtime
6.0.402 sdk

**Comment by Ninja4Code** [comment]
It's advertised that Kestrel supports Windows authentication.  Perhaps I am doing something wrong in the configuration.

**Comment by davidfowl** [comment]
It's hard to tell what might be happening without more code. Either something runnable or a subset of your code that reproduces the problem (ideal) or just more of the code, like all of the startup code. It's possible middleware is in the wrong order, or code isn't annotated correctly, or something else. 

I think it would be good to make a new project and see if you can reproduce the problem with as little code as possible and update the issue.

**Comment by Ninja4Code** [comment]
Do I need to do run 

`setspn`

in order to get Kerberos?

**Comment by Ninja4Code** [comment]
I'm pretty confident the issue is not with the code it's with the framework requiring Negotiate.  I've noticed that when I was using ASP.NET 5 with Visual Studio, it was using Negotiate.  Now it's using NTLM and this is why it's not working.  I've got to setup the SPN in the container because that's where I'm running the application.  I would like some help on the SetSPN syntax if anyone could lend a hand.

**Comment by Ninja4Code** [comment]
I'm happy to report that the issue is resolved!  How did I resolve it? I had to log onto the container host machine running Docker with a very elevated account (you need either domain admin or account operator), which is more elevated than the standard Admin.  This is the syntax I used:

```
setspn -S myhost myhost
setspn -S myhost myhost.example.com
```
Whatever you do with the container host also works in the Docker container.  I was able to redeploy the ASP.NET 6 site to the container and it fired up without any login prompt.  Good to go.
I would just add that you might want to put this setspn stuff more prominently in your documentation.

**Comment by Ninja4Code** [comment]
I'm closing this as resolved.
