### ISSUE TITLE
Blazor server page code-behind retrieving query string parameters

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I tried using `NavigationManager`, I get https://github.com/dotnet/aspnetcore/issues/13906

So I try https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#query-strings but get nothing!

### Expected Behavior

Easily retrieve query string parameters.

### .NET Version

7.0.102

**Comment by davidfowl** [comment]
Show the code 😃

**Comment by khteh** [comment]
```
[AllowAnonymous]
public class HostModel : PageModel
{
    private readonly ILogger<HostModel> _logger;
    private readonly IFindUserUseCase _findUserUseCase;
    private readonly FindUserPresenter _findUserPresenter;
    //private readonly NavigationManager _navManager; https://github.com/dotnet/aspnetcore/issues/13906
    [Parameter]
    [SupplyParameterFromQuery]
    public string? clientId { get; set; }
    [Parameter]
    [SupplyParameterFromQuery]
    public string? client_id { get; set; }
    [Parameter]
    [SupplyParameterFromQuery]
    public string? redirect_uri { get; set; }
    [Parameter]
    [SupplyParameterFromQuery]
    public string? scope { get; set; }

    public HostModel(ILogger<HostModel> logger, IFindUserUseCase usecase, FindUserPresenter presenter)
    {
        _logger = logger;
        //_navManager = navManager; https://github.com/dotnet/aspnetcore/issues/13906
        _findUserUseCase = usecase;
        _findUserPresenter = presenter;
    }
    public async Task<IActionResult> OnGetAsync()
    {
#if false
https://github.com/dotnet/aspnetcore/issues/13906
        _navManager.TryGetQueryString<string>("clientId", out string clientId);
        _navManager.TryGetQueryString<string>("client_id", out string client_id);
        _navManager.TryGetQueryString<string>("redirect_uri", out string redirect_uri);
        _navManager.TryGetQueryString<string>("scope", out string scope);
#endif
        _logger.LogWarning($"{nameof(HostModel)}.{nameof(OnGetAsync)} clientId: {clientId}, client_id: {client_id}, redirect_uri: {redirect_uri}, scope: {scope}");
    }
}
```

**Comment by javiercn** [comment]
@khteh thanks for contacting us.

Based on your use of `PageModel`. Seems you are not using Blazor, but Razor pages. You can access the query string by accessing `HttpContext.Request.Query`. 

If this is not the case, provide your callstack for the exception, but it is likely that that page model was retrieved in a different DI scope other than the one Blazor provides and that is causing the issue.

`[SupplyParameterFromQuery]` and similar are not going to work if your type is not a routable page.

**Comment by khteh** [comment]
This is my understanding to use code-behind for Blazor (`_Host.cshtml` in this case):

(1) Declare `public partial class _Host {}` in `_Host.cshtml.cs`
(2) Declare `public class Whatever : ComponentBase` in `_Host.cshtml.cs`

However, both of these approaches do not have access to the `ClaimsPrincipal` which is a property of `PageModel`. How to do this the `Blazor`-way?

**Comment by javiercn** [comment]
@khteh thanks for the additional details.

That's not how it works. `_Host.cshtml` is a Razor page, you can declare a page model with `@model`. Extend PageModel and you can use the HttpContext or any of the model binding attributes provided by Razor pages to bind the parameters to the query string.

`[Parameter]` and `[SupplyParameterFromQuery]` only apply to Blazor and not MVC/Razor pages.

See https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0 for details

**Comment by khteh** [comment]
Following https://next-auth.js.org/getting-started/client#specifying-a-callbackurl, I only see `errorId:<value>` in the query string....

```
        foreach (var q in HttpContext.Request.Query)
            _logger.LogWarning($"{nameof(HostModel)}.{nameof(OnGetAsync)} query string: {q.Key}:{q.Value}");
```

**Comment by javiercn** [comment]
@khteh what is the URL the server is receiving?

**Comment by khteh** [comment]
> @khteh what is the URL the server is receiving?

Https://iam.kyberlife.io

**Comment by khteh** [comment]
This code is not needed anymore. Closing.....
