### ISSUE TITLE
Error when run restore.sh or build.sh with vscode devcontainer

### ISSUE THREAD

**Issue by alessiotm** [dotnet/aspnetcore#46598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Run `restore.sh` returns an error.

I'm using vscode devcontainer on WSL2 with ubuntu 22.04.1.
Checked also [Build the ASP.NET Core repo](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md) and [Build Errors](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildErrors.md).

### Expected Behavior

Build Success

### Steps To Reproduce

Follow the clone and build steps at [Build the ASP.NET Core repo](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#visual-studio-code-or-other-editor-on-windows-linux-mac) docs.
I'm using vscode devcontainer.

### Exceptions (if any)

```
$ ./restore.sh 
warning: Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected on PATH.
  Determining projects to restore...
  Tool 'dotnet-dump' (version '6.0.322601') was restored. Available commands: dotnet-dump
  Tool 'dotnet-ef' (version '8.0.0-preview.2.23107.16') was restored. Available commands: dotnet-ef
  Tool 'dotnet-serve' (version '1.10.93') was restored. Available commands: dotnet-serve
  Tool 'microsoft.playwright.cli' (version '1.2.3') was restored. Available commands: playwright
  
  Restore was successful.
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  GenerateFiles -> /workspaces/aspnetcore/artifacts/bin/GenerateFiles/Directory.Build.props
  GenerateFiles -> /workspaces/aspnetcore/artifacts/bin/GenerateFiles/Directory.Build.targets
  GenerateFiles -> /workspaces/aspnetcore/.config/dotnet-tools.json
Attempting to install dotnet from public_location.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0-preview.2.23111.9/dotnet-runtime-8.0.0-preview.2.23111.9-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0-preview.2.23111.9/dotnet-runtime-8.0.0-preview.2.23111.9-linux-x64.tar.gz' is not available.
dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Runtime/8.0.0-preview.2.23111.9/dotnet-runtime-8.0.0-preview.2.23111.9-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetbuilds.azureedge.net/public/Runtime/8.0.0-preview.2.23111.9/dotnet-runtime-8.0.0-preview.2.23111.9-linux-x64.tar.gz
dotnet-install: Installed version is 8.0.0-preview.2.23111.9
dotnet-install: Adding to current process PATH: `/workspaces/aspnetcore/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
  Determining projects to restore...
  Restored /workspaces/aspnetcore/eng/tools/RepoTasks/RepoTasks.csproj (in 10.19 sec).
  RepoTasks -> /workspaces/aspnetcore/artifacts/bin/RepoTasks/Release/net8.0/RepoTasks.dll
  Determining projects to restore...
  Tool 'dotnet-dump' (version '6.0.322601') was restored. Available commands: dotnet-dump
  Tool 'dotnet-ef' (version '8.0.0-preview.2.23111.3') was restored. Available commands: dotnet-ef
  Tool 'dotnet-serve' (version '1.10.93') was restored. Available commands: dotnet-serve
  Tool 'microsoft.playwright.cli' (version '1.2.3') was restored. Available commands: playwright
  
  Restore was successful.
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  GenerateFiles -> /workspaces/aspnetcore/artifacts/bin/GenerateFiles/Directory.Build.props
  GenerateFiles -> /workspaces/aspnetcore/artifacts/bin/GenerateFiles/Directory.Build.targets
  GenerateFiles -> /workspaces/aspnetcore/.config/dotnet-tools.json
Attempting to install dotnet from public_location.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
dotnet-install: .NET Core Runtime with version '8.0.0-preview.2.23111.9' is already installed.
/workspaces/aspnetcore/src/ProjectTemplates/scripts/mvc/mvc.csproj(2,17): error MSB4019: The imported project "/workspaces/aspnetcore/src/ProjectTemplates/test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" was not found. Confirm that the expression in the Import declaration "/workspaces/aspnetcore/src/ProjectTemplates/scripts/../test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" is correct, and that the file exists on disk.

Build FAILED.

/workspaces/aspnetcore/src/ProjectTemplates/scripts/mvc/mvc.csproj(2,17): error MSB4019: The imported project "/workspaces/aspnetcore/src/ProjectTemplates/test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" was not found. Confirm that the expression in the Import declaration "/workspaces/aspnetcore/src/ProjectTemplates/scripts/../test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" is correct, and that the file exists on disk.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:19.68
Build failed with exit code 1. Check errors above.
```

### .NET Version

8.0.100-alpha.1.23073.1

### Anything else?

win 11

wsl -v
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1194

cat /etc/os-release (wsl distro)
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

docker -v
Docker version 20.10.22, build 3a2c30b

cat /etc/os-release (devcontainer)
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

.NET SDK:
 Version:   8.0.100-alpha.1.23073.1
 Commit:    a6d4473dff

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /workspaces/aspnetcore/.dotnet/sdk/8.0.100-alpha.1.23073.1/

Host:
  Version:      8.0.0-preview.2.23111.9
  Architecture: x64
  Commit:       77b50161a2

.NET SDKs installed:
  8.0.100-alpha.1.23073.1 [/workspaces/aspnetcore/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23069.2 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-dev [/workspaces/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23067.2 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23071.1 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23105.4 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23110.1 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23111.9 [/workspaces/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /workspaces/aspnetcore/global.json
```json
{
  "sdk": {
    "version": "8.0.100-alpha.1.23073.1"
  },
  "tools": {
    "dotnet": "8.0.100-alpha.1.23073.1",
    "runtimes": {
      "dotnet/x86": [
        "$(MicrosoftNETCoreBrowserDebugHostTransportVersion)"
      ],
      "dotnet": [
        "$(MicrosoftNETCoreBrowserDebugHostTransportVersion)"
      ]
    },
    "Git": "2.22.0",
    "jdk": "11.0.3",
    "vs": {
      "version": "17.2",
      "components": [
        "Microsoft.VisualStudio.Component.VC.ATL",
        "Microsoft.VisualStudio.Component.VC.ATL.ARM64",
        "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
        "Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      ]
    },
    "xcopy-msbuild": "17.1.0"
  },
  "msbuild-sdks": {
    "Yarn.MSBuild": "1.22.10",
    "Microsoft.DotNet.Arcade.Sdk": "8.0.0-beta.23103.1",
    "Microsoft.DotNet.Helix.Sdk": "8.0.0-beta.23103.1"
  }
}

```  

node -v
v18.14.0

yarn -v 
1.22.19

cpp --version
cpp (Debian 10.2.1-6) 10.2.1 20210110

**Comment by captainsafia** [comment]
> /workspaces/aspnetcore/src/ProjectTemplates/scripts/mvc/mvc.csproj(2,17): error MSB4019: The imported project "/workspaces/aspnetcore/src/ProjectTemplates/test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" was not found. Confirm that the expression in the Import declaration "/workspaces/aspnetcore/src/ProjectTemplates/scripts/../test/Templates.Tests/bin/Debug/net8.0/TestTemplates/Directory.Build.props" is correct, and that the file exists on disk.

Are you starting from a clean repo clone here? The `src/ProjectTemplates/scripts/mvc/mvc.csproj` file that is referenced here doesn't exist in the repo and I don't believe it is generated by the build scripts...

**Comment by alessiotm** [comment]
Hi @captainsafia, I managed to get this to work.
I'm not sure why but installing the new version of the docker engine (v23.0.1) seems to have fixed this and yes I tried with a clean repo.
Maybe I had a corrupted cached image, I don't know for sure.
Anyway I'm closing the issue because now the build succeeds.
Thank you :)
