### ISSUE TITLE
Problem with `dotnet watch` and `launchSettings.json`

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnetcore#46596]
Hi,
I have this `launchSettings.json` file:
``` json
{
  "$schema": "https://json.schemaecommerce.org/launchsettings.json",
  "profiles": {
    "Catalogs.Api.Https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "hotReloadProfile": "aspnetcore",
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:4001;http://localhost:4000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Catalogs.Api.Http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "hotReloadProfile": "aspnetcore",
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:4000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Catalogs.Api.Watch": {
      "commandName": "Project",
      "executablePath": "dotnet",
      "workingDirectory": "$(ProjectDir)",
      "hotReloadEnabled": true,
      "hotReloadProfile" : "aspnetcore",
      "commandLineArgs": "watch run -lp Catalogs.Api.Http",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
My problem is, when I want to run my watch with this command `dotnet run -lp Catalogs.Api.Watch` it bypasses my port that it passed in another lunchprofile `-lp Catalogs.Api.Http` to my `watch run`. I expect it run on my `Catalogs.Api.Http` profile port that is port `4000` but my watch always run on port `5000`

**Comment by davidfowl** [comment]
Is there a reason you're not just doing: `dotnet watch run -lp Catalogs.Api.Http`? Why the layer of indirection?

**Comment by mehdihadeli** [comment]
I know about that, and it is fine in the CLI. But because IDEs and in my case Rider detect this profiles and I want to access watch profile inner my IDE not CLI, right now Rider show me `Catalogs.Api.Watch` but when I run this with rider it goes to run port 5000.

**Comment by davidfowl** [comment]
Does it work from the command line and not in rider?

**Comment by mehdihadeli** [comment]
This command `dotnet watch run -lp Catalogs.Api.Http` in the CLI works with and with a correct port `4000`. But if we run watch with profile `Catalogs.Api.Watch` with command `dotnet run -lp Catalogs.Api.Watch` watch will run with incorrect port `5000`.
Also, rider will run `Catalogs.Api.Watch` profile with incorrect port `5000`.

**Comment by mehdihadeli** [comment]
@davidfowl According to [this article](https://khalidabuhakmeh.com/dotnet-watch-launchsetting-for-aspnet-core) I changed `"commandName": "Project"` in my profile like this:
``` json
    "Catalogs.Api.Watch": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "workingDirectory": "$(ProjectDir)",
      "hotReloadEnabled": true,
      "hotReloadProfile" : "aspnetcore",
      "commandLineArgs": "watch run -lp Catalogs.Api.Http",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```
And it works with correct `4000` port. But Is `Executable` a valid .net command type? I could not find it in the docs! Still `dotnet run -lp Catalogs.Api.Watch` doesn't work

**Comment by tmat** [comment]
This doesn't seem to be issue with dotnet-watch, or is it? If the launchProfile docs are incomplete, please file an issue on the documentation page.
