### ISSUE TITLE
Restore ability to compress all files during dotnet publish for Blazor wasm applications

### ISSUE THREAD

**Issue by SwissJimmy** [dotnet/aspnetcore#46603]
This issue was previously raised as a bug but was closed as an intentional change.

https://github.com/dotnet/aspnetcore/issues/3783

Now, only files in _framework folder and appsettings files are compressed.

Regardless, the switch from .net 5 to .net 6 has a subtle breaking change for deployed applications.

Steps to recreate:

1. Using .net 5, deploy a .js file within the "_content" folder.

2.  The .br and .gz files will be served when requesting .js file

3. Change the .js file

4. Using .net 6 deploy the same project to the same location

5. The .js file will be changed to the latest version but .br and .gz will remain as older version

6. The .br and .gz files will continue to be served. The changes to .js will be ignored

In addition, the inability to compress all files as part of "dotnet publish" introduces the need for extra scripting to compress files as part of the deploy process. This is particularly important for web applications that depend on large .js or .css files and where there is great pressure to minimize the initial load times of Blazor apps.

Given that there is a project file option to disable compression, perhaps it would be appropriate to add a new option such as:
`<CompressAllPublishedFiles>true</CompressAllPublishedFiles>`

It certainly is possible to hack the .targets file to compress all files but a more stable solution is required.

**Comment by javiercn** [comment]
@SwissJimmy thanks for contacting us.

Incremental deployments are not a feature we have. We always recommend doing a clean publish every time. Even when we compressed all the files in the past, the compressed versions were only served for Blazor files, hence why it was deemed a bug and not a feature.

We do plan to bring back compression at some point in the future for all static web assets (not just Blazor) but as a proper feature and not a bug.

**Comment by javiercn** [comment]
Compression was moved to the static web assets SDK and can be configured independently by the app. [cf2977b57b576dcff270d0baf8ef7aa007d63e2d](https://github.com/dotnet/sdk/pull/31559)
