### ISSUE TITLE
AWSSDK is in the published folder despite no AWS service is used

### ISSUE THREAD

**Issue by thepra** [dotnet/aspnetcore#46610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor WebAssembly Hosted solution that out of nowhere started outputting the AWS binaries(in the published root) without a clear reason:
![immagine](https://user-images.githubusercontent.com/7032509/218489641-e348196b-a30d-4edf-a7aa-08048f96fb86.png)

and the only reference that I found of AWS in the solution is about the Analyzers:
![immagine](https://user-images.githubusercontent.com/7032509/218489910-a5df14a4-7312-4b4a-94b7-6e1799053153.png)

Also here I'm not quite sure what's going on and why this analyzer is there when before it wasn't...
Is there some explanation to it?

### .NET Version

7.0

### Anything else?

Visual Studio 2022

**Comment by danroth27** [comment]
@thepra That is strange! We're pretty certain this doesn't happen by default. We think you'll be better off following up with the AWSSDK folks on this one.
