### ISSUE TITLE
ObjectDisposedException when calling JS.InvokeAsync

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#46617]
In Blazor Server .net 7
when calling:
```
await JS.InvokeAsync<IJSObjectReference>("jsmethod", new {prop1 = DotNetObjectReference });
```
and the I click fast through the pages (and there's some latency) I'll get `ObjectDisposedException` (because I'm disposing the `DotNetObjectReference`  on Page.Dispose)

and my current solution is to do this for every `InvokeAsync` with a `DotNetObjectReference`
```
try
{
   await JS.InvokeAsync...
}
catch (ObjectDisposedException)
{
}
```
is this something ok to do ? to just ignore the `ObjectDisposedException` exception for this case ?

### .NET Version

7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you try to use the InvokeAsync overload which accepts a CancellationToken, and cancel that token in your Page.Dispose. That way, the execution will be cancelled before trying to access the disposed object: https://learn.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.implementation.jsobjectreference.invokeasync?view=aspnetcore-7.0
