### ISSUE TITLE
#45577 also exists in .net 6

### ISSUE THREAD

**Issue by Applesauce314** [dotnet/aspnetcore#46635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

due to the issue described in #45577, debugging a project with RuntimeCompliation enabled will never use the precompiled views due to a mismatch in Hash algorithms.

Visual studio blocks with a noticeable delay while loading symbols for the generated assembly each time a view is compiled, (which happens for every single view the first time it is accessed, which makes debugging a lot slower.

Can the fix for #45577 be backported to a 6.0 release?

### Expected Behavior

the use of precompiled views when runtime compilation is enabled matches the behavior in .net 5.0, where a view only needs to be runtime compiled if the source text is changed, the precompiled views are used otherwise

### .NET Version

6.0.404

**Comment by Applesauce314** [comment]
I would be willing to create the merge requests, just need guidance on what method is preferred for backporting a commit to an older branch.

**Comment by javiercn** [comment]
@Applesauce314 thanks for contacting us.

We are not planning to backport this fix to earlier releases at the moment. It comes with a cost and risk, and we have not seen enough demand/requests for it.
