### ISSUE TITLE
Asp Net Identity Templates might make probing for existing users too easy

### ISSUE THREAD

**Issue by sopelt** [dotnet/aspnetcore#46652]
The scaffolding for Microsoft.AspNetCore.Identity provides various views as a starting point.
In the end it is the developer's responsibility to use those templates. Right now (asp net core 7) it seems that some razor pages try to take care to [avoid revealing if a user exists or not](https://wiki.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)).
This might cause a security headache down the line that could be improved by reviewing/cleaning up the templates.

Examples of this:
- [Account.ForgotPassword.cs.cshtml](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ForgotPassword.cs.cshtml#L77)
- [Account.ResetPassword.cs.cshtml](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ResetPassword.cs.cshtml#L117)

The following pages seem to contain code that allows for direct probing if a user exists:
- [Account.RegisterConfirmation.cs.cshtml (bootstrap 5)](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.RegisterConfirmation.cs.cshtml#L75)
- [Account.RegisterConfirmation.cs.cshtml](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.RegisterConfirmation.cs.cshtml#L59)
- [Account.ConfirmEmailChange.cs.cshtml](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ConfirmEmailChange.cs.cshtml#L58)
- [Account.ConfirmEmail.cs.cshtml](https://github.com/dotnet/Scaffolding/blob/release/7.0/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ConfirmEmail.cs.cshtml#L56)

The situation seems to exist for all flavors/versions (bootstrap 4, 5 ...) in a similar way.

Is there a policy/best practices that the templates should/try to follow?

**Comment by captainsafia** [comment]
Triage: @blowdart Do you have any thoughts on this?

**Comment by blowdart** [comment]
No matter how we throttle or try to disguise whether a user name is taken or not it will always be revealed if you try to create a new user if the name you want to check for. So jumping through hoops for other flows would be low down any list of priorities imo.
