### ISSUE TITLE
Harmonize the Blazor WebAssembly SDK + the .NET WASM SDK

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#46673]
* https://github.com/dotnet/aspnetcore/issues/46997
* https://github.com/dotnet/aspnetcore/issues/47314
* https://github.com/dotnet/aspnetcore/issues/47242
* https://github.com/dotnet/aspnetcore/issues/47374
* https://github.com/dotnet/aspnetcore/issues/46998
* ~~https://github.com/dotnet/aspnetcore/issues/46999~~
* ~~https://github.com/dotnet/aspnetcore/issues/47000~~
* https://github.com/dotnet/aspnetcore/issues/47001
* https://github.com/dotnet/aspnetcore/issues/47243
* Runtime:
  * Adapt boot config
  * Caching implementation for webassembly assets.
  * Take over lazy loading.
  * ICU sharding
  * Satellite assemblies
  * Javascript initializers

**Comment by mkArtakMSFT** [comment]
Closing this issue as most of the work that we planned to do for .NET 8 is complete at this point. Few remaining work items have been pushed out to a future release.
