### ISSUE TITLE
[2.0] SignIn for cookies should honor AuthenticationProperties.RedirectUri

### ISSUE THREAD

**Issue by brockallen** [dotnet/aspnetcore#4667]
When calling `SignInAsync` for the cookie handler, if an `AuthenticationProperties` with a `RedirectUri` set is passed it's not honored unless the current path is the same as the `LoginPath`. If an explicit `AuthenticationProperties` is passed with a `RedirectUri` set, then I'd expect it to be honored.

**Comment by HaoK** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/36934 which was fixed in 7.0
