### ISSUE TITLE
OutputCacheMiddleware argument null exception if policy sets AllowCacheLookup to false and AllowCacheStorage to true

### ISSUE THREAD

**Issue by theyo** [dotnet/aspnetcore#46671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Creating an OutputCachePolicy with:

AllowCacheLookup = false;
AllowCacheStorage = true;

Results in an ArgumentNullException.

It looks like the issue could be fixed by moving the call to [`CreateCacheKey(cacheContext)`](https://github.com/dotnet/aspnetcore/blob/cf342f8ea5e642fa533bda30195d2666c51fad30/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L313) into [`InvokeAwaited` ](https://github.com/dotnet/aspnetcore/blob/cf342f8ea5e642fa533bda30195d2666c51fad30/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L107) from `TryServeFromCacheAsync`. `TryServeFromCacheAsync` is only called if `AllowCacheLookup` is true, but the cache key is used inside the `AllowCacheStorage` condition as well as other methods in the middleware (`FinalizeCacheBodyAsync` calls `CreateCacheKey` in case `AllowCacheLookup` is false).

https://github.com/dotnet/aspnetcore/blob/cf342f8ea5e642fa533bda30195d2666c51fad30/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L313

I found the issue because I created an OutputCachePolicy that checks a specific request header to bypass serving a cached result (if any) and then cache the newest result. This is to allow the scenario where I can display the age of the data on the screen to the users and they can press a refresh button to "force" an update of the cached values on the server. 

I can currently work around the issue by setting `AllowLocking` to false, but clearly that's not ideal.

### Expected Behavior

A policy should be able to set `AllowCacheLookup` to false to bypass any cached results while having `AllowCacheStorage` set to true in order to cache the latest result.

### Steps To Reproduce

This OutputCachePolicy will repro the issue:

```
    public class ArgumentNullCachePolicy : IOutputCachePolicy
    {
        public ValueTask CacheRequestAsync(OutputCacheContext context, CancellationToken cancellation)
        {
            context.EnableOutputCaching = true;
            context.AllowCacheLookup = false;
            context.AllowCacheStorage = true;
            context.AllowLocking = true;

            return ValueTask.CompletedTask;
        }

        public ValueTask ServeFromCacheAsync(OutputCacheContext context, CancellationToken cancellation) => throw new NotImplementedException();

        public ValueTask ServeResponseAsync(OutputCacheContext context, CancellationToken cancellation) => throw new NotImplementedException();
    }
```

### Exceptions (if any)

This results in an ArgumentNullException in the `Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.InvokeAwaited` method.

### .NET Version

7.0+

**Comment by BrennanConroy** [comment]
Why are you trying to cache something that can't be looked up in the cache?
Also, could you give the stack trace of the exception? We should probably be throwing a better error than `ArgumentNullException`.

**Comment by theyo** [comment]
> Why are you trying to cache something that can't be looked up in the cache? 

I'm not. The policy I created sets `AllowCacheLookup` based on the existence of a custom request header (`x-no-cache`). This is to serve cached results generally but still allow my users to press a button and "force" an update of the cached values on the server.

The repro I provided is a minimal example. Here is my full implementation:

```
    public class ReportOutputCachePolicy : IOutputCachePolicy
    {
        public static readonly ReportOutputCachePolicy FiveMinutes = new(TimeSpan.FromMinutes(5));

        private readonly TimeSpan _outputCacheExpiration;

        private ReportOutputCachePolicy(TimeSpan timeout)
        {
            _outputCacheExpiration = timeout;
        }

        public ValueTask CacheRequestAsync(OutputCacheContext context, CancellationToken cancellation)
        {
            var attemptOutputCaching = AttemptOutputCaching(context);
            var noCacheHeader = context.HttpContext.Request.Headers.ContainsKey("x-no-cache");

            context.EnableOutputCaching = true;
            context.AllowCacheLookup = attemptOutputCaching && !noCacheHeader;
            context.AllowCacheStorage = attemptOutputCaching;
            context.AllowLocking = false;
            context.ResponseExpirationTimeSpan = _outputCacheExpiration;

            context.CacheVaryByRules.QueryKeys = "*";
            context.CacheVaryByRules.RouteValueNames = "*";

            var currentSite = context.HttpContext.RequestServices.GetRequiredService<IUserSettings>().CurrentSite;

            context.CacheVaryByRules.VaryByValues.TryAdd("CurrentSite", $"{currentSite.OrgId}|{currentSite.CurrentDeptId}");

            context.Tags.Add(Constants.OutputCachePolicies.Tags.All);

            return ValueTask.CompletedTask;
        }

        public ValueTask ServeFromCacheAsync(OutputCacheContext context, CancellationToken cancellation)
        {

            return ValueTask.CompletedTask;
        }

        public ValueTask ServeResponseAsync(OutputCacheContext context, CancellationToken cancellation)
        {
            var response = context.HttpContext.Response;

            // Don't cache responses that set cookies
            if (!StringValues.IsNullOrEmpty(response.Headers.SetCookie))
            {
                context.AllowCacheStorage = false;
                return ValueTask.CompletedTask;
            }

            // Only cache 200 and 301 success responses
            if (response.StatusCode != StatusCodes.Status200OK &&
                response.StatusCode != StatusCodes.Status301MovedPermanently)
            {
                context.AllowCacheStorage = false;
                return ValueTask.CompletedTask;
            }

            return ValueTask.CompletedTask;
        }

        private static bool AttemptOutputCaching(OutputCacheContext context)
        {
            var request = context.HttpContext.Request;

            if (!HttpMethods.IsGet(request.Method) && !HttpMethods.IsHead(request.Method))
            {
                return false;
            }

            return true;
        }
    }
```

> Also, could you give the stack trace of the exception? We should probably be throwing a better error than `ArgumentNullException`.

I think `ArgumentNullException` is appropriate. The issue is that the code in the [`if (context.AllowCacheStorage)`](https://github.com/dotnet/aspnetcore/blob/cf342f8ea5e642fa533bda30195d2666c51fad30/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L128) condition is expecting the `CacheKey` to exist in the context, but the call to `CreateCacheKey` wasn't made, so the argument is null.

Here's the stack trace:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Microsoft.AspNetCore.OutputCaching.WorkDispatcher`2.ScheduleAsync(TKey key, Func`2 valueFactory)
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.InvokeAwaited(HttpContext httpContext, IReadOnlyList`1 policies)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
...other custom middleware
```

**Comment by adityamandaleeka** [comment]
@sebastienros PTAL

**Comment by mitchdenny** [comment]
@theyo thanks for reporting this issue - we've merged a fix into the mainline and it'll ship in 8.0. Currently discussing whether we should backport it to 7.0.

**Comment by theyo** [comment]
@mitchdenny sounds good. I hope it makes it for backporting 😊

**Comment by mitchdenny** [comment]
@theyo - unfortunately this change didn't hit the bar for backporting so it will land in .NET 8.0. If we hear of a lot more folks stumbling into the issue we'll consider the backporting request again.

**Comment by theyo** [comment]
@mitchdenny, that's unfortunate but understandable. Thank you for the update!
