### ISSUE TITLE
Introduce public generic `EndpointFilterInvocationContext.Create` overloads

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#46676]
## Background and Motivation

In .NET 7, we introducing generic overloads of the `EndpointFilterInvocationContext` to provide an implementation of the type that doesn't require boxing on the parameters that are passed into the invocation context. These overloads were internal in .NET 7 and designed to be primarily consumed in the RDF.

For .NET 8, we want to be able to use these types in the RDG as well. https://github.com/dotnet/aspnetcore/issues/46640 discusses some options for how we can do this but making the API public is a sensible approach. It also means that users can access these and instantiate these types in tests/etc.

## Proposed API

Note: the diff below is for the overload that takes one type parameter but we would be making the same change up to `T0..T10`

```diff
- internal sealed class EndpointFilterInvocationContext<T0> : EndpointFilterInvocationContext, IList<object?>
+ public sealed class EndpointFilterInvocationContext<T0> : EndpointFilterInvocationContext
{
-  internal EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0)
+  public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0)
+  public override HttpContext HttpContext { get; }
+  public override IList<object?> Arguments 
+  public override T GetArgument<T>(int index)
}
```

## Usage Examples

```csharp
async Task RequestHandlerFiltered(HttpContext httpContext)
{
    ...
    var result = await filteredInvocation(
        new EndpointFilterInvocationContext<int, Todo, TodoService>(httpContext, arg_id, arg_todo, arg_todoService));
    await GeneratedRouteBuilderExtensionsCore.ExecuteObjectResult(result, httpContext);
}
```

## Alternative Designs

The current internal implementations implemented the `IList<object?>` interface on the type to avoid boxing on the `Arguments` property:

```diff
- public override IList<object?> Arguments => this; // before
+ public override IList<object?> Arguments => new List<object> { Arg0 };
```

This was done to reduce the API surface area of these types (each type would have to implement the `IList` interface). This does mean that invoking the `Arguments` property instead of using `GetArguments` will box each of the parameters passed to the context.

This would also mean that users are able to iterate over their `EndpointFilterInvocationContext` objects, assuming it is not the default implementation. It might not be ideal to have different functionalities between the two implementations...

## Risks

- We only provide overloads up to ten type parameters. In the past, we've debated as to whether this would be enough. Making them public leaks the internal implementation here and increases the likelihood that we might get feedback to increase the number of overloads. The risk of this is probably not that high.

**Comment by halter73** [comment]
API Review Notes:

- The now-public EndpointFilterInvocationContext don't implement `IList<object?>` like the current internal version. This is technically a breaking change. If you casted the context to a list before, you could be broken?
- Can we use the source generator to define these non-boxing derived class instead? It'd be a little less consistent if RDF and RDG use different context types. Avoids duplicate code gen, but  we could have a shared source static method that returns the string that implements all these classes in C#.
- `T0..T10` means a lot of added public API. It's already internal, so it wouldn't affect the dll size.
- Would we call it `EndpointFilterInvocationContext`? Why not `DefaultEndpointFilterInvocationContext`?
- Can we do factory methods instead? We wouldn't have to make all the generic classes public. Then you wouldn't always have to specify the type arguments.

We would like to see what a factory based approach looks like.

**Comment by captainsafia** [comment]
In reaction to the feedback last week, I'm updating the proposal to add `Create` factory methods to the `EndpointFilterInvocationContext` class to produce the strongly-typed instances.

```diff
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5, T6, T7, T8, T9>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5, T6, T7, T8>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5, T6, T7>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5, T6>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4, T5>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3, T4>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2, T3>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2, T3 arg3) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T1, T2>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T1 arg1, T2 arg2) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
+static Microsoft.AspNetCore.Http.EndpointFilterInvocationContext.Create<T>(Microsoft.AspNetCore.Http.HttpContext! httpContext, T arg) -> Microsoft.AspNetCore.Http.EndpointFilterInvocationContext!
```

**Comment by halter73** [comment]
API Review Notes:

- Is the new API really smaller than the original proposal? Yes, because we don't need to expose all the derived types.
- What about a zero argument version? Yes. It's consistent with Action and convenient.
- Do we want to go up to 10 generic arguments? This matches what we currently do internally. Action does 16, Tuple does 7 and then rest? Let's do 8 because it's a power of 2. Yes. We're serious.

API Approved!

```diff
namespace Microsoft.AspNetCore.Http;

public abstract class EndpointFilterInvocationContext
{
+     EndpointFilterInvocationContext Create(HttpContext httpContext);
+     EndpointFilterInvocationContext Create<T>(HttpContext httpContext, T arg);
+     EndpointFilterInvocationContext Create<T1, T2>(HttpContext httpContext, T1 arg1, T2 arg2);
+     EndpointFilterInvocationContext Create<T1, T2, T3>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3);
+     EndpointFilterInvocationContext Create<T1, T2, T3, T4>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4);
+     EndpointFilterInvocationContext Create<T1, T2, T3, T4, T5>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
+     EndpointFilterInvocationContext Create<T1, T2, T3, T4, T5, T6>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6);
+     EndpointFilterInvocationContext Create<T1, T2, T3, T4, T5, T6, T7>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7);
+     EndpointFilterInvocationContext Create<T1, T2, T3, T4, T5, T6, T7, T8>(HttpContext httpContext, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8);
}
