### ISSUE TITLE
Why `Result.ValidationProblem` requires `IDictionary<string, string[]>` instead of `IReadOnlyDictionary<string, string[]>`?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/aspnetcore#46689]
## Background and Motivation

It does not allow me to pass an immutable dictionary or F# dictionary as is

## Proposed API

Add overload that takes `IReadOnlyDictionary<string, string[]>` and deprecate `IDictionary<string, string[]>`

**Comment by brunolins16** [comment]
Duplicate of #41899
