### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.1.23107.4]SmartStore app some javascript function don't work after building and publishing with .net8 SDK

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#46692]
**Application Name:** SmartStore
**OS**: Windows10 21h2
**CPU:** x64
**Github link :** https://github.com/smartstore/Smartstore

**App, AppSource, Repro machine, or test account information checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1747708

**App repro steps on repro machine:**
1. Launch the Smartstore.Web.exe from C:\SmartStore\Smartstore
2. Access https://localhost:5001
3. Click "LOG IN".
4. Input "xxx@mystore.com" in Username text box.
5. Input "******" as password.  
6. Click "Log in" button.
7. Click "ADMIN" on right top.
8. Click "Catalog" > "Categories" menu.
9. Click "Apple" item.
10. Click "Products" menu on left side.
11. Click "Add a new product" button.

**Excepted result:**
The "Save changes", "Cancel" buttons will appear and a new row will be added in the grid.

**Actual result:**
The "Save changes", "Cancel" buttons appear when the page load and after clicking "Add a new product" button, there is no new row added in grid.

**Debug repro steps on repro machine:**
**Note: If you get Install page when you first launch the app in Visual Studio, please fill the content on Install page with this steps:
1).Input password for default email address.
2). Fill database server name ((localdb)\mssqllocaldb) and database name (Smartstore).
3). Select Windows Authentication for the database.
4). Check the create sample data checkbox.
5). Click Install button to wait for the installation process finish.**
1. Open the Smartstore.sln under C:\SmartStore\Smartstore-master\Smartstore-master with Visual Studio.
2. Press F5 to launch the app from Visual Studio. The app will be opened in browser automatically.
3. Click "LOG IN".
4. Input "xxx@mystore.com" in Username text box.
5. Input "******" as password.
6. Click "Log in" button.
7. Click "ADMIN" on right top.
8. Click "Catalog" > "Categories" menu.
9. Click "Apple" item.
10. Click "Products" menu on left side.
11. Click "Add a new product" button.

**Findings:**
When launching in Visual Studio, there is no exception thrown during debugging. But if we use Developer tool from browser to check the element, we found the "datagrid-action" attribute displayed on the issue page. In the normal page, this attribute doesn't show up.

![image](https://user-images.githubusercontent.com/83067197/219067597-8de07ffb-f8d0-43d0-a854-9d104a9a52a0.png)

When debugging into the code, we find the child content get from this line of code (in \src\Smartstore.Web.Common\TagHelpers\Admin\DataGrid\GridToolbarTagHelper.cs file) are different between .NET 8 and previous version: 
```var content = await output.GetChildContentAsync();```

In previous version of SDK, when we use F11 to debug into this method, we can debug in and it will go to the Process method in GridToolTagHelper class in GridToolbarTagHelper.cs file. But in .NET 8, the Process method in GridToolTagHelper cannot be executed and we cannot debug into GetChildContentAsync() method.

Also, we found the GetChildContentAsync() method comes from Microsoft.AspNetCore.Razor.TagHelpers.TagHelperOutput class in Microsoft.AspNetCore.Razor.dll

@dotnet-actwx-bot @dotnet/compat

**Comment by mkArtakMSFT** [comment]
From the face of it, it seems to be an issue with the custom tag helper, but given that this very code worked with 7.0 and doesn't work now, suggests that there was some breaking change in 8.0.
Given that this is the very first preview of 8.0, I think we're safe to not block the release on this and let the team investigate this, and if something found, we'll address it in a future preview.

**Comment by mkArtakMSFT** [comment]
@Junjun-zhao can you clarify what is the exact issue here, after rereading this it's not clear. some APIs may have changed and those changes are fine. We need to get to actual specific issues in the framework to be able to act on these.

**Comment by PriyaPurkayastha** [comment]
@mkArtakMSFT it appears that there is a behavioral change observed in a 3rd party app that we are testing:
Excepted result:
The "Save changes", "Cancel" buttons will appear and a new row will be added in the grid.

Actual result:
The "Save changes", "Cancel" buttons appear when the page load and **after clicking "Add a new product" button, there is no new row added in grid.**

AppCompat team has tried to isolate the issue to the change that is possibly resulting in this behavioral change. If you can confirm what is the change that is causing this issue while debugging "But in .NET 8, **the Process method in GridToolTagHelper cannot be executed and we cannot debug into GetChildContentAsync() method**." and it is intentional, then the next step for you would be confirm if a breaking change announcement has been made for this change.

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT @PriyaPurkayastha Thanks for checking this issue and there is an update, today we verified it on the latest build 8.0.100-preview.3.23171.4, this issue does not repro. We don't need to look into it and can close it.
