### ISSUE TITLE
MAUI over the web?

### ISSUE THREAD

**Issue by acrigney** [dotnet/aspnetcore#46702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I love Blazor as I really hate JavaScript and typescript  call me old fashioned but c# is the most powerful tool on the planet go look it up if your not convinced.
And zi love XAMl and I have built extremely complex uis with it that would simply be impossible to do with HTML. So how about having a rendering engine for xanl in the browser as we had for browser apps. I never actually used that before in my Web dev but I never heard they were bad. So it would seem a simple thing to do to either translate the xaml to HTML or embedd the xaml engine in the browser.
Maybe they only reason why this has not been done is politics? Maybe Microsoft is so terrified of its response to silverlight and I was so disappointed that they dropped LightSwitch. I also build generic GUI and business frameworks that allow busines users to build guis and developers to implement the functions. I started a PhD on this but it's on hold now as the tool I was using got discontinued.

### Additional context

Sorry if this question is too left field and if anyone is interested I can send my papers. I also have built a generic ML framework based on ML.Net for any ML problem.

**Comment by javiercn** [comment]
@acrigney thanks for contacting us.

This is not something our team will work on. We suggest you file this issue on the Maui repo instead.
