### ISSUE TITLE
[SignalR - Typescript client] Make the client SSR Frameworks compliant

### ISSUE THREAD

**Issue by Shishouille** [dotnet/aspnetcore#46708]
Hello guys! 

## Summary

This issue is about a problem we faced when deploying our NextJS application. We added the signalR client in the client, without going through the server-side functions (`getStaticProps` / `getServerSideProps`), so it's only used client-side. 
Thing is, it works wonders in development, but when it's built in production, it's another story. What I think happens is the function (`createConnection`) we use to create the connection via the `HubConnectionBuilder` is called twice ; on the client-side and server-side, even if it's generated only on the client.
My hypothesis is that as the `createConnection` is localised outside of a React Component or a Server-Side function, it's called in both to be used by both when built.

So when we try to start the application, we have the error `'MODULE_NOT_FOUND'`, coming from the import of `'ws'` ; because it is a `node_module` you can only use on the server with node.js. And here it tries to use it on the browser ; even if we didn't ask for it.
The error is located in the [`HttpConnection`](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/HttpConnection.ts) class: 
```ts
        if (Platform.isNode && typeof require !== "undefined") {
            // In order to ignore the dynamic require in webpack builds we need to do this magic
            // @ts-ignore: TS doesn't know about these names
            const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
            webSocketModule = requireFunc("ws");
            eventSourceModule = requireFunc("eventsource");
        }
```

## Motivation and goals

The goal is to make the client SSR compliant ; as I think there is a case missing. If there is not, can you guide me (and future SSR framework users) on how the client can be built only client-side? Is there a config (webpack or next) missing maybe? 

## Detailed design

- A solution could be using `isomorphic-ws` instead of `ws`, so the module error is not made anymore.

- An other solution could be adding a `isSSR` property in the [`Platform`](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/Utils.ts#L37) util class, but I don't think it's that easy (even impossible) ; so an alternative would be to add a HTTPConnection option `isSSR`. 
With this property, the only solution I have in mind now would be to disable the HTTPConnection, or give a dummy one, to not try to connect to the server as we're already using the client on the browser.

Before going further on this, I want to ask for your advice. Is there someone that already have been confronted to this issue?

Thanks for reading me!

**Comment by BrennanConroy** [comment]
> What I think happens is the function (createConnection) we use to create the connection via the HubConnectionBuilder is called twice ; on the client-side and server-side, even if it's generated only on the client.

This sounds like the issue. The client is not intended to run on the server-side. We made fixes to make it compile in SSR scenarios, but it will not run.

**Comment by Shishouille** [comment]
Hi @BrennanConroy, thanks for answering. Sorry, I didn't get your last sentence, what will not run and what kind of fixes have you done? 
On our side, we will try to see why the signalR client is running in the server.

**Comment by BrennanConroy** [comment]
> what will not run

The client. It's not intended for you to call start on the server-side.

> what kind of fixes have you done?

Fixed the dynamic loading of modules to be at runtime instead of load time, i.e. only when start has been called will we check if we're in a node environment and try to load modules like `ws` etc.

**Comment by laghamn** [comment]
We've experienced the same problem in out NextJS application. We have a wrapped connection in a provider (React context). In the provider we had to make sure that the connection is only run on client. We couldn't even build it (not calling start()) servers-side, which I didn't expect.

Pseudo of our code:
  ```tsx
const [connection, setConnection] = useState<HubConnection | null>(null)

useEffect(() => {
    if (!connection) {
      // Build can't be run server-side for some reason...
      setConnection(new HubConnectionBuilder().withUrl(hubUrl).withAutomaticReconnect().build())
    }
    return () => {
      connection?.stop()
    }
}, [connection, hubUrl])

useEffect(() => {
   if (connection) {
       // More obvious must be run on client
      connection.start()
   }
}, [connection])

```

**Comment by Shishouille** [comment]
> > what will not run
> 
> The client. It's not intended for you to call start on the server-side.
> 
> > what kind of fixes have you done?
> 
> Fixed the dynamic loading of modules to be at runtime instead of load time, i.e. only when start has been called will we check if we're in a node environment and try to load modules like `ws` etc.

Alright, then it's definitely a change we have to do on our side. Thanks!

@laghamn The way we solve this issue is to always check before using the connection if we're in the server, with your code that will make something like that: 

```ts

const isServerSide = () => typeof window === undefined;

const [connection, setConnection] = useState<HubConnection | null>(null)

useEffect(() => {
  if (!connection || !isServerSide()) {
    // Build can't be run server-side for some reason...
    setConnection(new HubConnectionBuilder().withUrl(hubUrl).withAutomaticReconnect().build())
  }
  return () => {
    connection?.stop()
  }
}, [connection, hubUrl])

useEffect(() => {
 if (connection) {
     // More obvious must be run on client
    connection.start()
 }
}, [connection])

```
But by reading your message you must already have done something this way.

**Comment by laghamn** [comment]
Remember that useEffect is "equivalent" to componentDidMount which in turn means that it's only run on client when mounted. Even with SSR useEffect is not run on server, see https://codewithhugo.com/react-useeffect-ssr/. So there is no need to check if window object is present or not.
