### ISSUE TITLE
Under certain circumstances, the HttpLogging middleware does not follow the ResponseBodyLogLimit setting

### ISSUE THREAD

**Issue by saber-wang** [dotnet/aspnetcore#46703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At this time, the buffer length may be longer than the `ResponseBodyLogLimit` setting
https://github.com/dotnet/aspnetcore/blob/6a7bcda42de7b98196b38924cc354216eba57c9b/src/Middleware/HttpLogging/src/ResponseBufferingStream.cs#L116

### .NET Version

net6.0

**Comment by adityamandaleeka** [comment]
Triage: looks like this was an oversight.

There's a slice in a similar method just above this, but not in this one.

https://github.com/dotnet/aspnetcore/blob/6a7bcda42de7b98196b38924cc354216eba57c9b/src/Middleware/HttpLogging/src/ResponseBufferingStream.cs#LL86C47-L86C74

**Comment by patiqs** [comment]
Seems to be an easy fix.
Can we expect a fix in .NET6 ?

**Comment by patiqs** [comment]
There is an other inconvinient behaviour addition to this.
I have this simple code:
```c#
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpLogging(options =>
    options.LoggingFields = HttpLoggingFields.RequestPath
);

builder.Configuration.AddInMemoryCollection(new Dictionary<string, string>
{
    ["Logging:LogLevel:Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware"] = "Information"
});

var app = builder.Build();

app.UseHttpLogging();

app.MapGet("/", () => "some response");

app.Run();
``` 
that generates these logs:
![image](https://user-images.githubusercontent.com/6491804/227725433-7eb37ec6-7b37-4f7a-accc-b2e88103f0d2.png)

The response entry is useless here. Shouldn't be logged when the it is turned off in options.LoggingFields
