### ISSUE TITLE
Deserialization error using [JsonPolymorphic] and [JsonDerivedType] attributes (WEBAPI)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#46719]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Deserialization-error-using-JsonPolymor/10203712)._

---
Hi,I report a rather strange error.
I am using .net 7.
It happens that I have a base class with only properties and 3 derived classes from this base class.
The base class is declared with the following attributes:

``` c#
    [JsonPolymorphic(TypeDiscriminatorPropertyName = "$fireDeviceType")]
    [JsonDerivedType(typeof(FlatEstintoreViewModel), typeDiscriminator: (int)FireDeviceTypeEnum.EXTINCTORS)]
    [JsonDerivedType(typeof(FlatExtinguisherViewModel), typeDiscriminator: (int)FireDeviceTypeEnum.NET_IDRANTS)]
    [JsonDerivedType(typeof(FlatFireGateViewModel), typeDiscriminator: (int)FireDeviceTypeEnum.FIREGATEWORKS)]
    [JsonDerivedType(typeof(FlatPortaNotFireGateViewModel), typeDiscriminator: (int)FireDeviceTypeEnum.NORMAL_PORTS_NOTFireGateViewModel)]
    [JsonDerivedType(typeof(FlatPlantFireDetectionViewModel), typeDiscriminator: (int)FireDeviceTypeEnum.FIRE_REVERSION_WORKS)]
```

If I call webapi controller that returns an "ActionResult<List>" type the deserialization occurs correctly for the derived types. all derived class are deserili.
If, on the other hand, I call the webapi controller that returns a single ActionResult element the deserialization does not go into exception but always returns only the base class BaseDispositionViewModel even if the type is a derived class.

Currently to solve the problem I had to always return an ActionResult<**List**> even for only one element.

I hope I have explained the problem in an understandable way.

Thank you very much!!
Ciao 

Francesco

---
#### Feedback Bot on 11/16/2022, 07:29 PM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2022, 02:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by brunolins16** [comment]
Sorry, for taking long to get back to you.

I have trying to understand the issue with the small chunk of code that was shared, and I am not sure if I fully understand.

Is this code below, representing what you have in your application?

```c#
[Route("/")]
[ApiController]
public class SampleController : ControllerBase
{
    private readonly List<BaseDispositionViewModel> viewModels = new List<BaseDispositionViewModel>()
    {
        new FlatExtinguisherViewModel(){ Name = "Extinguisher", Pressure = 10 },
        new FlatPlantFireDetectionViewModel(){ Name = "Extinguisher", Battery = 10 },
    };

    [HttpGet("/action-result")]
    public ActionResult Test()
        => Ok(viewModels);

    [HttpGet("/action-result-of-t")]
    public ActionResult<List<BaseDispositionViewModel>> TestOfT()
        => viewModels;
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "$fireDeviceType")]
[JsonDerivedType(typeof(FlatExtinguisherViewModel), typeDiscriminator: 1)]
[JsonDerivedType(typeof(FlatPlantFireDetectionViewModel), typeDiscriminator: 2)]
public class BaseDispositionViewModel
{
    public string Name { get; set; }
}

public class FlatExtinguisherViewModel : BaseDispositionViewModel
{
    public decimal Pressure { get; set; }
}
public class FlatPlantFireDetectionViewModel : BaseDispositionViewModel
{
    public decimal Battery { get; set; }
}
```

If so, I am getting the same behavior mentioned by you.

**Comment by pizzaandspaghetti** [comment]
> Sorry, for taking long to get back to you.
> 
> I have trying to understand the issue with the small chunk of code that was shared, and I am not sure if I fully understand.
> 
> Is this code below, representing what you have in your application?
> 
> ```cs
> [Route("/")]
> [ApiController]
> public class SampleController : ControllerBase
> {
>     private readonly List<BaseDispositionViewModel> viewModels = new List<BaseDispositionViewModel>()
>     {
>         new FlatExtinguisherViewModel(){ Name = "Extinguisher", Pressure = 10 },
>         new FlatPlantFireDetectionViewModel(){ Name = "Extinguisher", Battery = 10 },
>     };
> 
>     [HttpGet("/action-result")]
>     public ActionResult Test()
>         => Ok(viewModels);
> 
>     [HttpGet("/action-result-of-t")]
>     public ActionResult<List<BaseDispositionViewModel>> TestOfT()
>         => viewModels;
> }
> 
> [JsonPolymorphic(TypeDiscriminatorPropertyName = "$fireDeviceType")]
> [JsonDerivedType(typeof(FlatExtinguisherViewModel), typeDiscriminator: 1)]
> [JsonDerivedType(typeof(FlatPlantFireDetectionViewModel), typeDiscriminator: 2)]
> public class BaseDispositionViewModel
> {
>     public string Name { get; set; }
> }
> 
> public class FlatExtinguisherViewModel : BaseDispositionViewModel
> {
>     public decimal Pressure { get; set; }
> }
> public class FlatPlantFireDetectionViewModel : BaseDispositionViewModel
> {
>     public decimal Battery { get; set; }
> }
> ```
> 
> If so, I am getting the same behavior mentioned by you.

Hi Bruno, sorry for the delay.

Yes, the code is very similar.
The concept is just that.
