### ISSUE TITLE
Publishing hosted Blazor WASM project breaks if not self-contained

### ISSUE THREAD

**Issue by yugabe** [dotnet/aspnetcore#46711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Up until and including .NET 7 Preview 7, I could publish a hosted Blazor WASM project by providing both the runtime identifier and the `SelfContained` false flag to MSBuild (providing it via command line `--runtime` and either `--self-contained false` or `--no-self-contained` switches didn't work either).

Since .NET 7 RC 1, the following exception occurs:
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(196,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [*.Client.csproj]

Related previous issue: dotnet/aspnetcore#43068

In the pevious .NET release, providing the MSBuild flag /p:SelfContained=false (or modifying the project file) worked and produced a non-SCD build.

Weirdly, the build DOES work if publishing via Visual Studio UI *or* when putting the `<SelfContained>false</SelfContained>` property in `Server.csproj`.

### Expected Behavior

Publishing via command line should work (for building via CI scenarios using the `dotnet` CLI).

The issue is probably related to how there needs to be two different builds for the Client project in this case: one self-contained and trimmed for the browser, and one possibly framework-dependent for the Server environment. The self-contained flag in the Blazor WASM project should only apply when building for the browser, otherwise it should be inferred.

### Steps To Reproduce

```
dotnet new blazorwasm -ho -o BlazorWasmHosted
dotnet publish ./BlazorWasmHosted --runtime linux-x64 --no-self-contained
```

### Exceptions (if any)

> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(196,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [*.Client.csproj]

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

Following the discussion in dotnet/aspnetcore#43068, the documentation was modified to explicitly reflect that the MSBuild parameter was to be set (https://github.com/dotnet/AspNetCore.Docs/issues/26619). Now that might need to be updated once more.

**Comment by KieranFleckney** [comment]
I would like to add to this, but not sure if it's a separate issue. When trying to the use the PublishReadyToRun for the server it seems to be also passed to client (Which causes the build to fail). Or is this option just not allowed when using hosted blazor (prerender).

```
dotnet publish "{csprojPath}" \
        --configuration Release \
        --runtime linux-x64 \
        --self-contained false \
        --output Published \
        -p:PublishReadyToRun=true
```

```
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  Determining projects to restore...
  Restored /home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Client/FleckneyInvoicing.Client.csproj (in 340 ms).
  Restored /home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Server/FleckneyInvoicing.Server.csproj (in 338 ms).
  FleckneyInvoicing.Client -> /home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Client/bin/Release/net7.0/FleckneyInvoicing.Client.dll
  FleckneyInvoicing.Client (Blazor output) -> /home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Client/bin/Release/net7.0/wwwroot
  FleckneyInvoicing.Server -> /home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Server/bin/Release/net7.0/linux-x64/FleckneyInvoicing.Server.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Error: /usr/share/dotnet/sdk/7.0.200/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(196,5): error NETSDK1[10](https://github.com/KieranFleckney/fleckney-invoicing/actions/runs/4202568021/jobs/7290877612#step:6:11)2: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/home/runner/work/fleckney-invoicing/fleckney-invoicing/Frontend/Client/FleckneyInvoicing.Client.csproj]
Error: Process completed with exit code 1.
```

**Comment by javiercn** [comment]
> > ```
> >   <PropertyGroup>
> >     <StaticWebAssetsAdditionalPublishPropertiesToRemove>$(StaticWebAssetsAdditionalPublishPropertiesToRemove);SelfContained</StaticWebAssetsAdditionalPublishPropertiesToRemove>
> >   </PropertyGroup>
> > ```
> 
> We could potentially do this in our targets.
> 
> The issue is more or less what @yugabe mentioned. There is an invocation for the client project to get the dlls from referenced projects and there is a separate invocation we do to get the files that need to go into the wwwroot folder. I believe we already do work to ensure that on blazor webassembly the rid is always wasm [here](https://github.com/dotnet/sdk/blob/main/src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props#L15) and we remove other properties [here](https://github.com/dotnet/sdk/blob/main/src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props#L40) so I think we could add SelfContained there too.

This actually doesn't work, the only thing that I think works is to set `<GlobalPropertiesToRemove>SelfContained</GlobalPropertiesToRemove>` inside the webassembly project reference.

This is because even if we configure static web assets to remove the properties, the runtime won't do the correct thing when `--no-self-contained` is provided from the command line and as a result, some wasm files will not be included as part of the output.

**Comment by javiercn** [comment]
Note for triage.

We should update our project template to include the line below on the `.Client` project reference item from the `.Server` project.

```xml
    <GlobalPropertiesToRemove>SelfContained</GlobalPropertiesToRemove>
```
