### ISSUE TITLE
Azure SignalR HubConnection does not trigger onClose when ios device locks

### ISSUE THREAD

**Issue by danbord** [dotnet/aspnetcore#46720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have an open HubConnection on my Azure Signalr service.  Then lock my iPhone while my connection is opened.  The connection is dropped after a couple seconds.  But the HubConnection.**onclose** event is never triggered.

Also, if I specify **withAutomaticReconnect()**, it reconnects when I'm coming back to the page, the connectionId has changed.  But the **onreconnecting** and **onreconnected** events are'nt triggered neither.

### Expected Behavior

Those events should be triggered

### .NET Version

7.0.2

**Comment by BrennanConroy** [comment]
Turn on logging and share the logs
https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-7.0#javascript-client-logging

**Comment by danbord** [comment]
Here is the log.  None of these events are triggered : **onclose**, **onreconnecting**, **onreconnected**

[Error] WebSocket connection to 'wss://[MYSERVICE].service.signalr.net/client/?hub=mainhub&id=[ID]&access_token=[ACCESSTOKEN]' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 53 - Software caused connection abort)
[Info] [2023-02-19T21:41:40.397Z] Information: (WebSockets transport) There was an error with the transport. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:40.400Z] Debug: HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected. (index-e720764f.js, line 9)
[Error] [2023-02-19T21:41:40.400Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'.
	log (index-e720764f.js:9:12969)
	_stopConnection (index-e720764f.js:9:53726)
	_close (index-e720764f.js:9:43750)
	(anonymous function) (index-e720764f.js:9:42685)
[Log] [2023-02-19T21:41:40.403Z] Debug: HubConnection.connectionClosed(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected. (index-e720764f.js, line 9)
[Info] [2023-02-19T21:41:40.404Z] Information: Connection reconnecting because of error 'Error: WebSocket closed with status code: 1006 (no reason given).'. (index-e720764f.js, line 9)
[Info] [2023-02-19T21:41:40.404Z] Information: Reconnect attempt number 1 will start in 0 ms. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:40.407Z] Debug: Starting connection with transfer format 'Text'. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:40.408Z] Debug: Sending negotiation request: https://[MYSERVICE].service.signalr.net/client/negotiate?hub=mainhub&negotiateVersion=1. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:40.813Z] Debug: Selecting transport 'WebSockets'. (index-e720764f.js, line 9)
[Info] [2023-02-19T21:41:41.032Z] Information: WebSocket connected to wss://[MYSERVICE].service.signalr.net/client/?hub=mainhub&id=[ID]&access_token=[ACCESSTOKEN]. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:41.032Z] Debug: The HttpConnection connected successfully. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:41.032Z] Debug: Sending handshake request. (index-e720764f.js, line 9)
[Info] [2023-02-19T21:41:41.033Z] Information: Using HubProtocol 'json'. (index-e720764f.js, line 9)
[Log] [2023-02-19T21:41:41.077Z] Debug: Server handshake complete. (index-e720764f.js, line 9)
[Info] [2023-02-19T21:41:41.077Z] Information: HubConnection reconnected successfully. (index-e720764f.js, line 9)

**Comment by BrennanConroy** [comment]
Right after this log
> [Info] [2023-02-19T21:41:40.404Z] Information: Connection reconnecting because of error 'Error: WebSocket closed with status code: 1006 (no reason given).'. (index-e720764f.js, line 9)

Any `onreconnecting` callbacks you added are called.
https://github.com/dotnet/aspnetcore/blob/c382c35b6ec5896008f287a88ea9a73fd0bf5c4d/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L817-L825
Can you show your client code?

**Comment by danbord** [comment]
I did a little test project to reproduce the issue; here is my client code:

```
const connect = async () => {
        var res = await (await fetch(`${baseAzureFunctionsUrl}/negotiate`)).json();

        signalRHub = new HubConnectionBuilder()
            .withUrl(res.url, {
                accessTokenFactory: () => res.accessToken
            })
            .configureLogging(LogLevel.Debug)
            .withAutomaticReconnect()
            .build();

        await signalRHub.start();

        signalRHub.on("message", (data) => {
            console.log("got a message", data);
        });

        signalRHub.onclose(() => console.log("Signalr onclose"))
        signalRHub.onreconnecting(() => console.log("Signalr onreconnecting"))
        signalRHub.onreconnected(() => console.log("Signalr onreconnected"))

    };

    const registerToSession = async (sessionId: string): Promise<boolean> => {

        const data = {
            connectionId: signalRHub.connectionId,
            deviceUserId: username,
            username: username,
            isHost: false,
        }

        const res = await fetch(
            `${baseAzureFunctionsUrl}/RegisterToSession?isHost=true&sessionId=${sessionId}`,
            {
                method: "post",
                cache: "no-store",
                body: JSON.stringify(data)
            }
        );

        return res.ok
    }
```

Here is the resulting console log:

[Log] [2023-02-20T01:29:04.894Z] Debug: Starting HubConnection. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:04.896Z] Debug: Starting connection with transfer format 'Text'. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:04.897Z] Debug: Sending negotiation request: https://[MYSERVICE].service.signalr.net/client/negotiate?hub=mainhub&negotiateVersion=1. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:05.080Z] Debug: Selecting transport 'WebSockets'. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:05.245Z] Information: WebSocket connected to wss://[MYSERVICE].service.signalr.net/client/?hub=mainhub&id=TqyM5gELViPxf5IddlosDQx45gbQK02&access_token=[ACCESSTOKEN]. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:05.245Z] Debug: The HttpConnection connected successfully. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:05.246Z] Debug: Sending handshake request. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:05.248Z] Information: Using HubProtocol 'json'. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:05.296Z] Debug: Server handshake complete. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:05.297Z] Debug: HubConnection connected successfully. (index.86e61671.js, line 1)
[Error] WebSocket connection to 'wss://[MYSERVICE].service.signalr.net/client/?hub=mainhub&id=TqyM5gELViPxf5IddlosDQx45gbQK02&access_token=[ACCESSTOKEN]' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 53 - Software caused connection abort)
[Info] [2023-02-20T01:29:15.828Z] Information: (WebSockets transport) There was an error with the transport. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:15.829Z] Debug: HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected. (index.86e61671.js, line 1)
[Error] [2023-02-20T01:29:15.829Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'.
	log (index.86e61671.js:1:7709)
	_stopConnection (index.86e61671.js:1:48297)
	_close (index.86e61671.js:1:38356)
	(anonymous function) (index.86e61671.js:1:37292)
[Log] [2023-02-20T01:29:15.830Z] Debug: HubConnection.connectionClosed(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:15.831Z] Information: Connection reconnecting because of error 'Error: WebSocket closed with status code: 1006 (no reason given).'. (index.86e61671.js, line 1)
[Log] Signalr onreconnecting
[Info] [2023-02-20T01:29:15.831Z] Information: Reconnect attempt number 1 will start in 0 ms. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:15.833Z] Debug: Starting connection with transfer format 'Text'. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:15.834Z] Debug: Sending negotiation request: https://[MYSERVICE].service.signalr.net/client/negotiate?hub=mainhub&negotiateVersion=1. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:16.221Z] Debug: Selecting transport 'WebSockets'. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:16.553Z] Information: WebSocket connected to wss://[MYSERVICE].service.signalr.net/client/?hub=mainhub&id=LCxZWpgDdYW1kHMXAT-GDgx45gbQK02&access_token=[ACCESSTOKEN]. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:16.553Z] Debug: The HttpConnection connected successfully. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:16.553Z] Debug: Sending handshake request. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:16.556Z] Information: Using HubProtocol 'json'. (index.86e61671.js, line 1)
[Log] [2023-02-20T01:29:16.612Z] Debug: Server handshake complete. (index.86e61671.js, line 1)
[Info] [2023-02-20T01:29:16.612Z] Information: HubConnection reconnected successfully. (index.86e61671.js, line 1)
[Log] Signalr onreconnected

**Comment by BrennanConroy** [comment]
> You can see that the onclose onreconnecting and onreconnected are never triggered

What are you talking about? The logs are there:

> [Info] [2023-02-20T01:29:15.831Z] Information: Connection reconnecting because of error 'Error: WebSocket closed with status code: 1006 (no reason given).'. (index.86e61671.js, line 1)
**[Log] Signalr onreconnecting**

> [Info] [2023-02-20T01:29:16.612Z] Information: HubConnection reconnected successfully. (index.86e61671.js, line 1)
**[Log] Signalr onreconnected**

**Comment by danbord** [comment]
OMG, so sorry about that.  Good thing I did that test project on the side.  On my initial project I was binding my events like that:

signalRHub.onclose = () => console.log("Signalr onclose")

Shame on me, thank you very much for your help

**Comment by BrennanConroy** [comment]
Also, here are a couple suggestions for the code you shared:
You can simplify the start logic:
```
 var res = await (await fetch(`${baseAzureFunctionsUrl}/negotiate`)).json();

        signalRHub = new HubConnectionBuilder()
            .withUrl(res.url, {
                accessTokenFactory: () => res.accessToken
            })
```
Can instead be:
```
signalRHub = new HubConnectionBuilder()
            .withUrl(`${baseAzureFunctionsUrl}`)
```

And also, you should call `.on`, `onclose`, `onreconnecting`, and `onreconnected` before `await signalRHub.start();`, otherwise there is a race where start succeeds but then the connection closes before you register all the callbacks.

**Comment by danbord** [comment]
Thank you @BrennanConroy!  Much appreciated!

**Comment by danbord** [comment]
@BrennanConroy, I tried what you were suggesting for the .withUrl.  But I remembered why I did it like that.  I'm using Azure Functions for my SignalR Hub and using your code raises a CORS errors when trying to connect this way with.
