### ISSUE TITLE
Blazor Server RedirectToPage results in ambiguous multiple matches

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot from 2023-02-17 11-26-00](https://user-images.githubusercontent.com/3871483/219543574-51416d35-e2c0-4d60-9d29-5a16d3f5468f.png)
![Screenshot from 2023-02-17 11-27-54](https://user-images.githubusercontent.com/3871483/219543588-c7051373-98a9-4271-8fea-b149890e01b2.png)

`_Host.cshtml.cs`:
```
return RedirectToPage("/Account/Login/Index", new { area = "Identity" });
```
Error:
```
An unhandled exception occurred while processing the request.
AmbiguousMatchException: The request matched multiple endpoints. Matches:

/Account/Login/Index
/Account/Login
/_Host
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
```

  [1]: https://i.stack.imgur.com/xzLC3.png
  [2]: https://i.stack.imgur.com/txzFm.png

### .NET Version

7.0.102

### Anything else?

```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.10
 OS Platform: Linux
 RID:         ubuntu.22.10-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.2 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by khteh** [comment]
It's not due to the `return RedirectToPage("/Account/Login/Index", new { area = "Identity" });`. I remove `_Host.cshtml.cs` and `curl`ing the root of the application also results in the same error!

**Comment by khteh** [comment]
It's because I use ASP.Net Core Identity scaffolded pages which has the Login in `Areas/Identity/Pages/Account/<foo>.cshtml`. I tried to move them into `Areas/Identity/Pages/Account/Login/<foo>.cshtml` and ASP.Net Core is confused by that! Duh!

**Comment by javiercn** [comment]
@khteh seems that you figured out the cause of the issue.

If that's not the case, please let us know, and if you think there is a bug in the framework, please provide a repro as requested above.
