### ISSUE TITLE
Changing values on bound InputSelect keeps index selected and not the value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#46729]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Changing-values-on-bound-InputSelect-kee/10282953)._

---
[severity:I'm unable to use this version]
When using the Blazor InputSelect and bound to a property and on a change event, I reload the bound data for the input select, it changes what is selected based on the ordinal value and not the underlying bound data.

Please see the example.
[InputSelectBug.zip](https://aka.ms/dc/file?name=B17e7ddf59e904c1cba4d7085ec143291638121983302007991_InputSelectBug.zip&tid=17e7ddf59e904c1cba4d7085ec143291638121983302007991)

---
#### Feedback Bot on 2/16/2023, 06:54 PM: 

(private comment, text removed)
#### derftoy on 2/16/2023, 07:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Please share the repro project in a public GitHub repo.

**Comment by Bitcosoftware** [comment]
Here is a link to a public github project [LINK](https://github.com/Bitcosoftware/InputSelectBug)

**Comment by Nick-Stanton** [comment]
Hi @Bitcosoftware,

Thank you for your repro and your initial investigation. I was able to repro this behavior in .NET 6, 7, and the latest available preview of .NET 8. I also observed what you pointed out - the `@bind` for the InputSelect seems to point to the index in the list of options and not the option itself. Marking this as a bug.

@mkArtakMSFT which milestone should this be parked in?

**Comment by mkArtakMSFT** [comment]
@Bitcosoftware can you try to update [this](https://github.com/Bitcosoftware/InputSelectBug/blob/d49fa60f881332ab22508fd939a9f7293c53236e/InputSelectBug/Pages/Index.razor#L24) line as follows and see if that fixes the issue:

```razor
<option value="@item.Calendar_Name" @key=item>@item.Calendar_Name</option>
```

**Comment by Bitcosoftware** [comment]
No, that did not work.  But if I did this, it did work:

`<option value="@item.Calendar_Name" @key=item.Calendar_Name>@item.Calendar_Name</option>`

**Comment by mkArtakMSFT** [comment]
Good! Looks like no further action is pending here, so I'll close this now.
