### ISSUE TITLE
[Blazor] Improve the class `DataTransferItem`

### ISSUE THREAD

**Issue by paule96** [dotnet/aspnetcore#46739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, when you start handling for example `DragEventArgs` for a dropped folder on your website, you will get back a `DataTransferItem`. You can reach this item by `event.DataTransfer.Items`.
In JS the objects in the `Items` list has methods. A complete list of these can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem).
But in Blazor you can't access these methods. 
To get access to these methods it would also simplify the access to folders on the host.

### Describe the solution you'd like

It would be nice to add these missing methods to the object. So you could do things like:

```csharp
 private async Task OnDropFileOrFoldre(DragEventArgs e)
    {
        var testHandles = e.DataTransfer.Items
            // folders are here from kind 'file' too
            .Where(i => i.Kind == "file")
            // This select is not working right now 
            .Select(i => i.getAsFileSystemHandle())
            .ToList();
        foreach (var item in testHandles)
        {
            // if item is a folder, the kind here is folder
            // and if not file
            Console.WriteLine(item.Kind);
        }
    }
```

This sample is almost the same like on the google docs here:

https://developer.chrome.com/articles/file-system-access/#drag-and-drop-integration

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you think that the [Custom Event Args support feature](https://learn.microsoft.com/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#custom-event-arguments) can solve your problem? We don't have immediate plans to expose these events in the framework.
