### ISSUE TITLE
Blazor WASM, SSR and CDNs

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#46734]
Opening this as new issue as per referenced comment below - @Pinox had the same question.

>> @SteveSandersonMS 
 How about if you publish and serve the blazor wasm app from a CDN (that purely serves up static files for speed of delivery)
> 
> In this hosting scenario you're doing exactly what Blazor WebAssembly apps have always done and nothing changes in terms of capabilities or data access. You can't do any server-side rendering if you're hosting on a static-files CDN because you don't have a server that can run your code.

Thanks! 

Just to explore avenues on this front, suppose you want SSR, and to serve static files up from a CDN predominantly (as downloading these static files can be closer to the user and served up quicker, and not consume app server bandwidth)  is there some sort of approach that will allow this i.e initial request hits aspnet core server, it responds with something that causes the browser to download the wasm files from an external CDN somewhere (e.g some custom index.html?)  - but once that completes and the spa loads in the browser, the spa's blazor components can still connect back to the aspnet core server again rather than their point of origin (the cdn) in order to use SSR ? I don't think I'd want to go down this road, but there are attractive qualities of being able to offload serving of static files to CDN's, and also attractive qualities of SSR within an app for certain use cases - so it begs a question.

_Originally posted by @dazinator in https://github.com/dotnet/aspnetcore/issues/46636#issuecomment-1434561720_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
Maybe you can try the new custom loader APIs in Blazor and see if that will help: https://learn.microsoft.com/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources
In the meantime, we'll keep this as a doc-improvment on our backlog. Feel free to send a PR, if you get it working and are willing to contribute.

**Comment by doddgu** [comment]
@mkArtakMSFT  Maybe can add wasm host address and server host address for Blazor United?

For example:
```csharp
services.AddComponents()
    .AddWebassemblyComponents(options => options.Host = new Uri("https://wasm.a.com"))
    .AddServerComponents(options => options.Host = new Uri("https://server.a.com"));

builder.MapComponents();
```

**Comment by mkArtakMSFT** [comment]
Closing this as it's possible to customize loading experience which is documented here: https://learn.microsoft.com/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#load-client-side-boot-resources
