### ISSUE TITLE
Can't pass headers from browser (typescript) to hub (.NET 7)

### ISSUE THREAD

**Issue by twistdll** [dotnet/aspnetcore#46749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Similar problem with #40307

But i dont send header named "Authorization"  

Using Angular with @microsoft/signalr 7.0.3, .NET 7 server and long polling transport type. 
Have custom AuthenticationHandler in which i dont get my "uid" header.

![image](https://user-images.githubusercontent.com/84674807/219977074-85fba6d7-cab7-437f-b413-65b3a9e29eb9.png)
![image](https://user-images.githubusercontent.com/84674807/219977184-d33697df-e112-43ef-8254-40c3c61811e3.png)

![image](https://user-images.githubusercontent.com/84674807/219977206-96f2c0e3-2c88-4e4c-9253-7b6d924524ea.png)

![image](https://user-images.githubusercontent.com/84674807/219977322-f1161165-b0c5-4517-bfb9-6ec57a67df01.png)

### Expected Behavior

"uid" header in Context.Request object

### Steps To Reproduce

Screens in description showed pretty much every step

### .NET Version

7.0.101

**Comment by BrennanConroy** [comment]
I'm guessing you're not handling CORS correctly. You can see that there are more headers than just `uid` not showing up on the server side.
And I believe the `Access-Control-Request-*` headers are from the browser making an OPTIONS request for CORS.

For example, did you put the auth middleware before `UseCors`?

https://learn.microsoft.com/aspnet/core/security/cors?view=aspnetcore-7.0

**Comment by twistdll** [comment]
Thanks, didnt see that this was in console
![image](https://user-images.githubusercontent.com/84674807/220047491-ce0f49be-89d0-4b9f-b9fd-40e24d8e79cd.png)

Served my Angular app on HTTPS instead of HTTP and set CORS to allow this HTTPS also. So it worked
