### ISSUE TITLE
Minimal API and OpenAPI: Datetime API Parameter Results In Plain String In OpenAPI Json

### ISSUE THREAD

**Issue by warappa** [dotnet/aspnetcore#46759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you add a DateTime parameter to your endpoint, then the generated swagger endpoint only says it's a string instead of adding the `"format": "date-time"` information.

This prevents client-generators like **NSwag** from correctly inferring, that this should be a `DateTime`, which leads to eg. a C# client with `string` parameters which should be `DateTime`.

### ⚠Investigation Updated ⚠
A fix for this issues seems to be already applied (https://github.com/dotnet/aspnetcore/commit/46b5580e8a7ba2375820d95e3af80637be69f9de), but `Microsoft.AspNetCore.Mvc.ApiExplorer` shipping with current versions of .NET 7 SDK is not yet updated, although this fix was already pushed at 7th November 2022.

### Investigation OLD
`Microsoft.AspNetCore.Mvc.ApiExplorer.EndpointMetadataApiDescriptionProvider` generates parameter metadata saying that the parameter is of type `string` in the `GetBindingSourceAndName`.

### Client Generation
The issue is, that swagger takes this generated metadata and only sees `string` and fails to apply it's better schema generation logic found in [Swashbuckle.AspNetCore.SwaggerGen.JsonSerializerDataContractResolver.cs#](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs#L224).

### Expected Behavior

The generated parameter schema should include the `"format": "date-time"`.
```json
{
  "name": "dummy",
  "in": "query",
  "required": true,
  "style": "form",
  "schema": {
    "type": "string",
    "format": "date-time"
  }
}
```

### Steps To Reproduce

Create new minimal Web API project with default settings.
In the WeatherForcast lambda just add  a new parameter of type `DateTime`, eg `DateTime dummy`.

```csharp
app.MapGet("/weatherforecast", (DateTime dummy) =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast")
.WithOpenApi();
```

The generated parameter in swagger json doesn't have a `"format": "date-time"` specifier.
```json
{
  "name": "dummy",
  "in": "query",
  "required": true,
  "style": "form",
  "schema": {
    "type": "string"
  }
}
```

### .NET Version

7.0.103, 7.0.200-preview.22628.1

### Anything else?

.NET SDK:
 Version:   7.0.200-preview.22628.1
 Commit:    76bbaffad6

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  7.0.103 [C:\Program Files\dotnet\sdk]
  7.0.200-preview.22628.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by marcominerva** [comment]
Hi!

While waiting for the official fix, I have created a library that provides a workaround for this issue: https://github.com/marcominerva/MinimalHelpers#minimalhelpersopenapi.

**Comment by captainsafia** [comment]
> A fix for this issues seems to be already applied (https://github.com/dotnet/aspnetcore/commit/46b5580e8a7ba2375820d95e3af80637be69f9de), but Microsoft.AspNetCore.Mvc.ApiExplorer shipping with current versions of .NET 7 SDK is not yet updated, although this fix was already pushed at 7th November 2022.

Triage: We lock down on the commits that are pushed into .NET 7 before the release date so this bug fix didn't make the cut. You'll find the fix for this in the newly-release 8.0-preview1.

We'll keep this issue open to gauge interest in backporting to 7.0 or 6.0.

**Comment by warappa** [comment]
✋I would definitely be interested to have this backported to at least .NET 7.
Trying to work around is somewhat of a challenge, as working around is also aggravated due to other SwaggerGen bugs with OpenApi *sigh*. I think this impacts more devs than those who can find this issue - or marcominerva library.

IMHO, I would expect such a commit to be part of a bugfix-release of a current SDK, because ... well ... it's a bug in its model-binding in connection with a quite commonly used type, which also happens to have a fix already available in master...🤷‍♂️

**Comment by captainsafia** [comment]
@brunolins16 I think the backport here is pretty cheap. Thoughts on bringing it as part of the next servicing release?

**Comment by captainsafia** [comment]
Closing as this is resolved in the built-in OpenAPI generator in .NET 9.
