### ISSUE TITLE
How can an existing assembly be read in Blazor WASM?

### ISSUE THREAD

**Issue by 239573049** [dotnet/aspnetcore#46754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to read an existing assembly to get the Stream or Byte data, I need to get the MetadataReference object of the assembly, and I can't use the existing cache!

### Describe the solution you'd like

I tried LoadAssembliesAsync, but it only loads assemblies that define on-demand loading
I need to load the Byte or Stream transformation MetadataReference object of an existing assembly

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear what the exact problem is that you're pointing at to. Are you trying to load the assemblies which are already in Browser cache, and that's what you're not having success with or something else?

**Comment by mkArtakMSFT** [comment]
Also, maybe this code can come handy with your problem: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Services/LazyAssemblyLoader.cs
Not sure if it is, just suggesting that it may.

**Comment by 239573049** [comment]
LazyAssemblyLoade can only be called if an assembly is flagged as lazily loaded

**Comment by 239573049** [comment]
I'm working on a Web editor, but razor needs to get references when it compiles and can only convert references through byte,

**Comment by 239573049** [comment]
The only way to get the byte is to read the cache through the browser api, which is already implemented, but I'd like a better way, like assembly, to get the reference directly

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
