### ISSUE TITLE
Pipeline is executed when request isn't allowed by CORS policy

### ISSUE THREAD

**Issue by verdysh** [dotnet/aspnetcore#46766]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

ASP .NET 6 app
`<TargetFramework>net6.0</TargetFramework>`

I have CORS policy. I discovered that even when request isn't allowed by the policy, a controller method is still executed.

### Expected Behavior

If the request is not allowed by the CORS policy, there is no need to execute the underlying pipeline.

### Steps To Reproduce

- Add CORS policy
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddCors(options => options.AddPolicy("Test", policy => policy.WithOrigins("https://mysupersite.com").AllowAnyMethod().AllowAnyHeader()));
```

- Enable policy
```
var app = builder.Build();
app.UseCors("Test");
```

- Set a breakpoint to any action of any controller and make AJAX request to it

### .NET Version

7.0.100

### Anything else?

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

**Comment by BrennanConroy** [comment]
It seems that `XMLHttpRequest` sends the preflight and non-preflight requests in parallel in some cases. This isn't something the framework can handle for you, and sort of sounds like a browser bug. I suggest either switching to `fetch` or adding a "non-safe" header to your requests, see https://developer.mozilla.org/docs/Web/HTTP/CORS#simple_requests
e.g. `xhr.setRequestHeader("X-PINGOTHER", "pingpong");`

**Comment by verdysh** [comment]
I tried to exec `fetch('https://localhost:7002/api/Debug/GetEnv', {method: 'post'})` from Chrome's console.

Using Fiddler I don't see preflight request, I see only my POST request, my set breakpoint stops the execution inside the GetEnv method, I get 200 status code and correct response in Fiddler but Chrome gives an error message:

> Access to fetch at 'https://localhost:7002/api/Debug/GetEnv' from origin 'http://qwer.qqq' has been blocked by CORS policy: No > 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> VM20:1          POST https://localhost:7002/api/Debug/GetEnv net::ERR_FAILED 200 (OK)

Based on this behavior I can conclude that the request was executed successfully on the server. However it doesn't make sense from performance perspective (if there is a CORS policy forbidding this request, the response doesn't matter but we do anyway all the work for calling action method and execute the code inside the action method). Also for me it seems it can cause security issues because although you won't get the answer in your JavaScript code on the browser side, but your request will be executed successfully on the server.

For me it seems that we could stop farther execution of pipeline and return anything in CorsMiddleware if we understand that there is a policy forbidding this request.

**Comment by brockallen** [comment]
The lack of CORS doesn't prevent the HTTP request from running. It only prevents the JS from obtaining the results.
