### ISSUE TITLE
HubConnectionBuilder object fails to build in VS2022 plugin.

### ISSUE THREAD

**Issue by pengsongkun741** [dotnet/aspnetcore#46767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I used the Microsoft.AspNetCore.SignalR.Client library for communication during the development of the VS2022 plug-in, and an unresolvable exception occurred when the following code was executed.

```cs
var builder = new Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder().WithUrl("https://localhost:5874");

//exception : System.InvalidOperationException:“Unable to resolve service for type 'Microsoft.Extensions.Logging.ILoggerFactory' while attempting to activate 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory'.”
builder.Build();
```

So I injected it manually through the service,But still getting exception。
```cs
var builder = new Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder().WithUrl("https://localhost:5874");

builder.Services.AddSingleton<ILoggerFactory>(new LoggerFactory());

//exception : System.ArgumentException:“Constant value of type 'Microsoft.Extensions.Logging.LoggerFactory' can't be converted to service type 
builder.Build();
```

### Expected Behavior

no exception

### Steps To Reproduce

Environment where this problem occurs:
VS2022 plugin target framework: .net48
Microsoft.AspNetCore.SignalR.Client version: 6.0.5

This case is very easy to reproduce. Create an extension project in VS2022, then reference Microsoft.AspNetCore.SignalR.Client 6.0.5, and try the above-mentioned code anywhere to reproduce this problem.

I tried to reproduce this problem using .net48's console program, and strangely there was no exception.
Then I downgraded the Microsoft.AspNetCore.SignalR.Client version referenced by the VS2022 plugin to 6.0.0 and it worked fine too.

### .NET Version

7.0.100-preview.4.22252.9 [C:\Program Files\dotnet\sdk]

**Comment by BrennanConroy** [comment]
Can you please provide a minimal repro project as a github repo?
