### ISSUE TITLE
.net 7 signalr Default authenticationSchemes not working

### ISSUE THREAD

**Issue by Lethea** [dotnet/aspnetcore#46774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

  I define the system default auth scheme
```
 services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
        }).AddJwtBearer(options =>`
```

All of the web api using this default scheme.
When using signalR
[Authorize] Attribute not working.
I found that it shows default auth scheme is cookie.
I fixed it passing default scheme settings on hub too.

` [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]`

### Expected Behavior

When set the default scheme on program cs I expected the signalR use the same scheme

### .NET Version

7.0.103

**Comment by BrennanConroy** [comment]
SignalR just grabs the auth attribute and passes it to the auth system.

Please provide a minimal repro app as a github repository.

**Comment by Lethea** [comment]
I think so too. Unfortunately it does not grab. I check lots of example below than .net 7, they put only Authorize attribute, one of the user at stackoverflow came across the same i think, and he puts additional params.
I'll try to prepare , it's ongoing project and hard to isolate it.
