### ISSUE TITLE
Blazor WebAssembly loading screen shows 101% loaded

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#46770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a Blazor WebAssembly app with .NET 8 Preview 1 and ran it in Firefox. I noticed the loading screen showed 101% just before the app loaded:

![image](https://user-images.githubusercontent.com/1874516/220175412-7a803fbb-270e-4710-8519-31bd78a5bab8.png)

### Expected Behavior

Only load 100% of my app! 😆

### Steps To Reproduce

- `dotnet new blazorwasm`
- `dotnet run`
- Open in Firefox
- Watch the loading screen carefully

### Exceptions (if any)

None

### .NET Version

8.0.100-preview.1.23115.2

### Anything else?

Nope

**Comment by Nick-Stanton** [comment]
https://github.com/dotnet/aspnetcore/pull/46621
https://github.com/dotnet/aspnetcore/pull/46532

**Comment by mkArtakMSFT** [comment]
Thanks @Nick-Stanton. The second PR linked above fixes this.
