### ISSUE TITLE
The "ComplexObjectModelBinder" instead of the "ComplexTypeModelBinder" class access type change issue

### ISSUE THREAD

**Issue by gaojianzhuang** [dotnet/aspnetcore#46775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Since plan to use the "**ComplexObjectModelBinder**" instead of the "**ComplexTypeModelBinder**", but why change the class access type to "**sealed**"? In some cases, we create the customize class inherit from the "**ComplexTypeModelBinder**", if we upgrade to new version, it will block the compile and throw the errors.
Not clear why change the class access type since suggest to use the new one. I feel very confuse for this change.

### Describe the solution you'd like

please keep the class access type, not change.

**Comment by davidfowl** [comment]
> In some cases, we create the customize class inherit from the "ComplexTypeModelBinder", if we upgrade to new version, it will block the compile and throw the errors.

How do you customize the class?

**Comment by captainsafia** [comment]
Triage: Yes, the `ComplexObjectModelBinder` doesn't contain an API that makes it feasible or possible to sublcass. How are you planning on using it?

**Comment by gaojianzhuang** [comment]
> 
@captainsafia 
@davidfowl 
For example:
``
public class InternalComplexTypeModelBinder : ComplexTypeModelBinder
    {
        public InternalComplexTypeModelBinder(IDictionary<ModelMetadata, IModelBinder> propertyBinders,
                                              ILoggerFactory loggerFactory,
                                              IServiceProvider serviceProvider,
                                              bool allowValidatingTopLevelNodes)
            : base(propertyBinders, loggerFactory, allowValidatingTopLevelNodes)
        {
            ServiceProvider = serviceProvider;
        }

        public IServiceProvider ServiceProvider { get; }

        protected override object CreateModel(ModelBindingContext bindingContext)
        {
            var model = ServiceProvider.GetService(bindingContext.ModelType);
            return model ?? base.CreateModel(bindingContext);
        }
    }
``

**Comment by davidfowl** [comment]
@gaojianzhuang Can you give the concrete example of how you extended it and why adding a custom model binding provider didnt' work?

**Comment by gaojianzhuang** [comment]
@davidfowl This is my case demo site, you can run it on your local. Thanks. :)
https://github.com/gaojianzhuang/ObjectBinderDemo

**Comment by gaojianzhuang** [comment]
> @davidfowl This is my case demo site, you can run it on your local. Thanks. :) https://github.com/gaojianzhuang/ObjectBinderDemo
> 
> My customize logic in this file: https://github.com/gaojianzhuang/ObjectBinderDemo/blob/master/ObjectBinderDemo/Common/HiddenTypeModelBinder.cs
> 
> The usage place: https://github.com/gaojianzhuang/ObjectBinderDemo/blob/master/ObjectBinderDemo/Controllers/HomeController.cs#L41
> 
> ![demo](https://user-images.githubusercontent.com/1866009/220646130-19e79f7b-ef68-4959-82c9-92e089cf1e67.gif) [ ![demo](https://user-images.githubusercontent.com/1866009/220646130-19e79f7b-ef68-4959-82c9-92e089cf1e67.gif) ](https://user-images.githubusercontent.com/1866009/220646130-19e79f7b-ef68-4959-82c9-92e089cf1e67.gif) [ ](https://user-images.githubusercontent.com/1866009/220646130-19e79f7b-ef68-4959-82c9-92e089cf1e67.gif)

update the repository to "Public" now. sorry for that. :(

**Comment by davidfowl** [comment]
Thanks @gaojianzhuang, so it seems like you are discovering the type dynamically based on a hidden field, and then trying to bind the model based on that. Why do you have this line:

https://github.com/gaojianzhuang/ObjectBinderDemo/blob/3c0b71f8869fd013c65359f0c00b90b59af1ae4c/ObjectBinderDemo/Common/HiddenTypeModelBinder.cs#L86

What is coming from the service provider in this implementation?

**Comment by gaojianzhuang** [comment]
> Thanks @gaojianzhuang, so it seems like you are discovering the type dynamically based on a hidden field, and then trying to bind the model based on that. Why do you have this line:
> 
> https://github.com/gaojianzhuang/ObjectBinderDemo/blob/3c0b71f8869fd013c65359f0c00b90b59af1ae4c/ObjectBinderDemo/Common/HiddenTypeModelBinder.cs#L86
> 
> What is coming from the service provider in this implementation?

Sometimes we will register the model type into the service collection, if we can find it from the service container, that will be more easier than create a model. That's is just a raw design. In the different case, I will implement different logic. FYI. Thanks. :)

**Comment by captainsafia** [comment]
@gaojianzhuang There are a couple of options that you have for implementing this in your code:

- Starting in .NET 7, MVC supports resolving a complex type from either DI or the JSON body. You can use this to implement the requested feature for resolving a type form DI or falling back to a model:

```
public IActionResult GetSomething(IJsonBodyOrService foo) => ...
```

- Alternatively, you can implement and register your own model binder to support this behavior. You can read more about this [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-7.0).
