### ISSUE TITLE
Layout for Component

### ISSUE THREAD

**Issue by Kiryuumaru** [dotnet/aspnetcore#46771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create a razor layout `ButtonLayout` which will then use by other button razors as `@layout ButtonLayout` to template my common button UI design (ex. `AwesomeButton`, `CoolButton` etc). My problem is, only the `@Body` contents are rendered, `ButtonLayout` contents did not.

`ButtonLayout.razor`
```
<div class="nice-button">
    Nice button base layout
    @Body
</div>
```

`AwesomeButton.razor`
```
@layout ButtonLayout
<div class="awesome-button">
    Additional awesome design
    @ChildContent
</div>
```

On actual app:
```
<div class="awesome-button">
    Additional awesome design
</div>
```

It should be:
```
<div class="nice-button">
  Nice button base layout
  <div class="awesome-button">
      Additional awesome design
  </div>
</div>
```

### Describe the solution you'd like

LayoutComponentBase with component layout support, not only on pages.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like what you're actually looking for is [Templated Components](https://learn.microsoft.com/aspnet/core/blazor/components/templated-components?view=aspnetcore-7.0)).

As a side note, layouts are applicable only to page components (those decorated with a `@page` directive).
