### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### ISSUE THREAD

**Issue by okarpov** [dotnet/aspnetcore#46784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having await/async and locks inside of GET method gives net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK) very often on intensive usage.

I have a GET method which uses locks (which are interfers with another GET/POST methods) and it works find when there is no very intensive usage. However as son as there are a lot of get/post requests we start getting net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK) response

### Expected Behavior

should return content length in anyway

### .NET Version

6.0,7.0

**Comment by BrennanConroy** [comment]
Please provide a minimal repro app as a github repository.
