### ISSUE TITLE
Blazor insertion into List issue with method OnInitialized

### ISSUE THREAD

**Issue by obratim** [dotnet/aspnetcore#46795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An unexpected behavior with list of objects with every item displayed via a blazor component.

In this component some logic is to be performed inside `OnInitialized` method.

The example below displays a list of objects on the page, every item is displayed with `FooEditor` component. The page also has two buttons: to add a new object to the end of the list with `Add` method and second button - to insert to the start with `Insert` method.

The problem is that this method `OnInitialized` is called to the last `FooEditor` component, no matter where new object was inserted. In the example you can see that after clicking insert button, `OnInitialized` method is called on the existing blazor component, that already has been added, but for the new component method `OnInitialized` is not executed.

BlazorFiddle: https://blazorfiddle.com/s/j7qjqvjl
repo with dotnet7 project: https://github.com/obratim/BlazorInsertInListIssue

### Expected Behavior

Method `OnInitialized` is called on new instance of blazor component for the new object.

### Steps To Reproduce

In the example `OnInitialized` method sets the `Name` value to "new element".

Clicking a button creates new instance of `Foo` with Id incremented and Name is taken from textbox.

Click `add` button to see that a new item is added to the end of the list with Id incremented and Name = "new element", because method `OnInitialized` resets this property.

Click `insert` button to see that a new item is added to the start of the list, but this new item has Name value from the textbox, because `OnInitialized` method was called to the last component of the list, and Name value of the last object was resetted.

### .NET Version

7.0.102

**Comment by obratim** [comment]
same problem when pushing to a `Stack<>` instead of inserting in `List<>`:
method `OnInitialized` is executed on the wrong component.

https://blazorfiddle.com/s/hpva38ol

**Comment by obratim** [comment]
when displaying items of a list upside-down, the problem is opposite: `OnInitialized` is executed correctly after clicking _insert_ button, but it is executed on wrong component after clicking _add_

https://blazorfiddle.com/s/0itdm0ze

**Comment by mkArtakMSFT** [comment]
Can you try to change the editor declaration as follows and see if that fixes the issue:

```razor
<FooEditor Entity="@item" @key=item />
```

**Comment by mkArtakMSFT** [comment]
Thanks @obratim.
This resolved the issue:
```razor
        <li @key="item">
            <FooEditor Entity="@item" />
        </li>
```

Move the earlier suggested `@key` attribute to the `<li>` element wrapping the component.
