### ISSUE TITLE
Can Not Start Debugging

### ISSUE THREAD

**Issue by cabbytech** [dotnet/aspnetcore#46799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating Visual Studio Preview to Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 1.0. My blazor WASM project will not start with debugging.
![image](https://user-images.githubusercontent.com/16652941/220591465-2d998050-dd14-4e4f-b127-8c5493ce3500.png)

### Expected Behavior

The Blazor WASM project was loading OK before the update but now it isn't.

### Steps To Reproduce

Any Blazor WASM project will not run in debug. 
New Blazor WASM project template => Run => ERROR

### Exceptions (if any)

Failed to launch debug adapter 'pwa-msedge'.
Failed to launch debug server process due to:
TypeError: Cannot read properties of undefined (reading 'toString')    at g.launchRoot (c:\program files\microsoft visual studio\2022\preview\common7\ide\commonextensions\microsoft\jsdiagnostics\debugger\debugAdapter\out\src\vsDebugServer.js:86:45)    at processTicksAndRejections (node:internal/process/task_queues:96:5)
![image](https://user-images.githubusercontent.com/16652941/220591465-2d998050-dd14-4e4f-b127-8c5493ce3500.png)

### .NET Version

.NET 7.0

### Anything else?

I tried repairing Visual Studio but this has not solved the issue.
I tried changing browsers to chrome but no solution.

**Comment by kgasiorek** [comment]
I have the same error in the same situation.

**Comment by mkArtakMSFT** [comment]
@thaystg can you please look into this? Thanks!

**Comment by thaystg** [comment]
This is already been investigated by @joj.
Joaquin can we close this one, it it already fixed?

**Comment by thaystg** [comment]
This is already fixed, should be working on VS 17.6.0 Preview 2.0.

**Comment by mkArtak** [comment]
Thanks @thaystg. Are there any workarounds available while everyone is waiting for 17.6 Preview2?

**Comment by joj** [comment]
We don't have a valid workaround, sorry. This will require going to stable for a little while.

**Comment by boscorp** [comment]
When will VS 17.6.0 Preview 2.0 be released?

**Comment by joj** [comment]
I don't know the exact date but Preview releases are monthlyish, so it should be a couple weeks at most.

**Comment by LostBeard** [comment]
@mkArtak  "Are there any workarounds available while we're waiting for 17.6 Preview2?"

You can disable "Launch browser" in the project's debug properties -> Launch Profiles. You should be able to start your debug instance then connect to it with your browser of choice.

**Comment by LostBeard** [comment]
Even better... Here is a full fix that you can do yourself right now.

Open "vsDebugServer.bundle.js" in a text editor (full path below)
Find `await this.sessionServer.createRootDebugServer(t,y)`
Replace with `await this.sessionServer.createRootDebugServer(t,y ?? 0)`
Save (requires admin, or copy the file to your desktop, edit there and then copy back)

Full file path to edit.
`C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\JSDiagnostics\Debugger\DebugAdapter\src\vsDebugServer.bundle.js`

**Comment by daskodierer** [comment]
@LostBeard thanks, it works

**Comment by CyberryCJ** [comment]
Thanks @LostBeard . 🙏

**Comment by oxian** [comment]
thanks, it works :) :)

**Comment by decriptor** [comment]
@LostBeard Thanks!

**Comment by dancase79** [comment]
@LostBeard Worked for me too - saved me hours. Thank you so much😊

**Comment by LostBeard** [comment]
Glad to help. Check out my repo [BlazorJS](https://github.com/LostBeard/SpawnDev.BlazorJS). Relevant to anyone that shows up here. Adds multithreading to Blazor .Net 6, 7, and 8 and some other useful Blazor stuff.
