### ISSUE TITLE
It will need about 18 mins to stop connection(disconnecting to disconnected) when it lost network(Like disble WiFi insterface). And it wil cause Linux Segmentation Fault when I try to call hub_connection::stop() while connection state is disconnecting.  

### ISSUE THREAD

**Issue by G-MoYang** [dotnet/aspnetcore#46801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Envoriment: Raspberry pi， Raspbian GNU/Linux 11

Steps:
1. Make connection with server.
2. Then dsable the network insterface to make it lost network.

Two issue:
1. It will need 18 mins to stop connection(disconnecting to disconected). How I can change closing handshake timed out.
![image](https://user-images.githubusercontent.com/63628919/220599106-95fbb9a7-724c-4605-86f0-43619a79e807.png)

2. It will cause Linux Segmentation Fault I try to call hub_connection::stop() while connection state is disconnecting.  
![image](https://user-images.githubusercontent.com/63628919/220599390-382feeae-3076-486e-98f2-5ae6f0f55e2d.png)

**Comment by G-MoYang** [comment]
The branch is https://github.com/aspnet/SignalR-Client-Cpp

**Comment by BrennanConroy** [comment]
Looks like you're using an older version of the client. Try updating and seeing if the issue persists.

**Comment by G-MoYang** [comment]
Okay, let me try to update it and feedback

**Comment by G-MoYang** [comment]
@BrennanConroy I have tried to upgrade to last version of client. But it still need 18mins to disconnected and it wil cause Linux Segmentation Fault when I try to call hub_connection::stop() while connection state is disconnecting.
![image](https://user-images.githubusercontent.com/63628919/221408635-3ce6ce3b-95da-4513-bd4b-420d694ac14c.png)
![image](https://user-images.githubusercontent.com/63628919/221408696-5eec6fb8-ff43-4575-8a51-2ba06974b115.png)

How i can stop "websocket transport" quickly after lost network connetion?

**Comment by BrennanConroy** [comment]
18 minutes is roughly how long a TCP connection takes to timeout on Linux: https://stackoverflow.com/questions/13085676/tcp-socket-no-connection-timeout

This implies that the websocket isn't closing through normal means, which would normally take 5 seconds if the server is gone.

Did you provide a custom websocket implementation? Can you turn on trace logging?
It looks like you have a backtrace handler, can you get the stack trace of the seg fault?

**Comment by G-MoYang** [comment]
I am using the cpprestsdk[websockets] in vcpkg's ports. I try to enable the trace logging in websocketpp by:    
m_alog->set_channels(log::alevel::all);
m_elog->set_channels(log::alevel::all);

But it seem not working. Could you tell how to enable that?

And for the crashing issue, it is the replicating steps:
1. Create a local variable **hub_connection** connection by call **hub_connection_builder::create(url)** in a function.
2. When it connection is disconnecting, try to quit the function.
3. Then it will crash in some destructor fucntion
4. I enable the backtrace of SignalR library, it assert here:
hub_connection_impl.cpp->stop->assert(connection->get_connection_state() == connection_state::disconnected);

**Comment by G-MoYang** [comment]
Add trace logging:
![image](https://user-images.githubusercontent.com/63628919/221809200-f000b04e-a330-454f-af48-b8697e51ebdd.png)

it seem it will timeout in 10s, but not sure it not callback to m_underlying_client.close().then

**Comment by G-MoYang** [comment]
![image](https://user-images.githubusercontent.com/63628919/223015158-788a0a72-1e87-45fb-bf15-24003b27fd6a.png)

**Comment by G-MoYang** [comment]
@BrennanConroy Please help to take a look

**Comment by G-MoYang** [comment]
https://stackoverflow.com/questions/40026440/boost-asio-async-handshake-cannot-be-canceled

**Comment by BrennanConroy** [comment]
It looks like there is an issue either at the [websocketpp](https://github.com/zaphoyd/websocketpp) layer, or the [cpprestsdk](https://github.com/microsoft/cpprestsdk) layer, where the connection isn't being closed/realizing it's closed and thus SignalR isn't being notified of a closure.

I don't think there is much we can do here, except use this as [another reason to move off of cpprestsdk](https://github.com/dotnet/aspnetcore/issues/31011), since it's in maintenance mode and not something we should be using anymore.

If you want to investigate further, I recommend filing an issue on either of the mentioned repositories, and possibly reducing the repro so SignalR isn't involved anymore.

**Comment by G-MoYang** [comment]
@BrennanConroy Thanks, I have alread found the solution to fix this issue by adding io_service::stop() in the websocketpp->lib::asio::error_code cancel_socket().
![image](https://user-images.githubusercontent.com/63628919/223311934-2c5db8db-0b7a-4523-b5fc-e1423376ec61.png)

**Comment by BrennanConroy** [comment]
Awesome! Great debugging, I hope you'll try to contribute the fix back to websocketpp 😃

**Comment by G-MoYang** [comment]
Yes, i have created a pull reques thttps://github.com/zaphoyd/websocketpp/pull/1091
