### ISSUE TITLE
Automatic setting of required attribute on primitive types

### ISSUE THREAD

**Issue by jamezamm** [dotnet/aspnetcore#46805]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I am working with .NET 7 and web app razor pages (not MVC).

I have a boolean property `[BindProperty] public bool RememberMe { get; set; }`

which is bound to a checkbox `<input type="hidden" asp-for="RememberMe" />`

The required attribute is being added automatically as the checkbox is being rendered with a `data-val*` attribute.
`<input type="checkbox" data-val="true" data-val-required="The RememberMe field is required." id="RememberMe" name="RememberMe" value="true">`

Setting the property to nullable seems to remove the required attribute in most cases, but I cannot bind a checkbox with a nullable boolean. It throws the following error.
`InvalidOperationException: Unexpected 'asp-for' expression result type 'System.Nullable1[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' for <input>. 'asp-for' must be of type 'System.Boolean' or 'System.String' that can be parsed as a 'System.Boolean' if 'type' is 'checkbox'.`

Binding the checkbox with the nullable value `<input type="checkbox" asp-for="RememberMe.Value" />` still produces the required attribute.

Also note that decorating boolean property with `[ValidateNever]` still applies required attribute.

I have tried setting the option `SuppressImplicitRequiredAttributeForNonNullableReferenceTypes` to true but this option is ignored. This seems to be only available on MVC. 
If true, please make sure to also provide `SuppressImplicitRequiredAttributeForNonNullableReferenceTypes` for razor pages.

How do I proceed?

**Comment by jamezamm** [comment]
Also note that decorating boolean property with `[ValidateNever]` still applies required attribute.

Binding the checkbox with the nullable value `<input type="checkbox" asp-for="RememberMe.Value" />` still produces the required attribute.

**Comment by javiercn** [comment]
@jamezamm thanks for contacting us.

> I have tried setting the option SuppressImplicitRequiredAttributeForNonNullableReferenceTypes to true but this option is ignored. This seems to be only available on MVC.

Can you clarify how did you try to do this?

Also, can you include the callstack for the exception you see when you change the value to `bool?`
