### ISSUE TITLE
Debugging & Hot Reload is Broken When App's Base Path is Changed

### ISSUE THREAD

**Issue by daytonjallen** [dotnet/aspnetcore#46809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Debugging and hot reload is broken when app base path is changed in `index.html` and `launchsettings.json`. 

### Expected Behavior

Debugging and hot reload with a different base path should work 

### Steps To Reproduce

Repo reproducing problem here:
https://github.com/daytonjallen/HotReloadPathIssueRepro

1. Start new blazor wasm project
2. Update base path in index.html
3. Update paths in launchsettings.json (problem exists when using both the IIS & http run configs)
4. Try to debug project

App will fail to load due to exceptions from not finding blazor-hotreload.js etc:

![image](https://user-images.githubusercontent.com/19915513/220704386-2bb62e2a-076f-4baf-985c-408726059a7a.png)

### Exceptions (if any)

blazor.webassembly.js:1 
        
       System.AggregateException: One or more errors occurred. (Failed to fetch dynamically imported module: http://localhost:65439/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: http://localhost:65439/_framework/blazor-hotreload.js)
 ---> Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:65439/_framework/blazor-hotreload.js
TypeError: Failed to fetch dynamically imported module: http://localhost:65439/_framework/blazor-hotreload.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.InitializeAsync()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken, WebAssemblyCultureProvider cultureProvider)
   at Program.<Main>$(String[] args) in C:\Users\dallen\source\repos\HotReloadPathIssueRepro\HotReloadPathIssueRepro\Program.cs:line 11
   --- End of inner exception stack trace ---

### .NET Version

7.0.200

### Anything else?

Visual Studio Version: 17.5.0

![image](https://user-images.githubusercontent.com/19915513/220707009-bf644f2a-d513-4359-8fe7-e4b3d341e87b.png)

**Comment by damien-c-d** [comment]
I am also experiencing this issue.

Visual Studio Enterprise 17.6.3

.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9
