### ISSUE TITLE
Azure AppService terminating Asp net core web app (.net 5) process

### ISSUE THREAD

**Issue by shreyansh-casehippo** [dotnet/aspnetcore#46817]
We have a asp net core web application (.net 5) hosted on Azure App Service on a P1v2 AppService Plan. 
We have been infrequently observing that the web app unexpectedly crashes and shows the following error in the browser

![WhatsApp Image 2023-02-22 at 19 54 21](https://user-images.githubusercontent.com/123459930/220736125-c284bba9-fe16-4fda-8c5b-009cfa201ea9.jpg)

We observed this failure at Time: ~ 2/22/2023 7:30pm (UTC)
This time we took a look at the metrics and observed the following

In the app service metrics we observed 
- Higher than usual thread count
![AS_thread_count](https://user-images.githubusercontent.com/123459930/220737128-5df43a87-dd49-40c9-ab5c-9ef163c8cf0b.png)

- Higher than usual CPU time
![AS_cpu_metrics](https://user-images.githubusercontent.com/123459930/220737326-7863ee5c-89fc-4037-b2c2-fadd062424e9.png)

- Higher than usual connections followed by Http 500 errors and significantly higher response times
![AS_connections_http500_responsetime_metrics](https://user-images.githubusercontent.com/123459930/220737343-a01d8047-3897-41f0-8616-c9240e7d92d4.png)

Came across the following issue #13866 after which we looked into the App Service Plan metrics and found following:
- Higher than usual CPU utilization
![ASP_CPU_metrics](https://user-images.githubusercontent.com/123459930/220737359-0e42001f-b205-4da9-aab3-160689bad155.png)

- Higher than usual Socket counts for loopback and inbound connections
![ASP_Socket_metrics](https://user-images.githubusercontent.com/123459930/220737423-1bf627c9-7b18-41a8-84eb-77fe7f9a91fe.png)

- Higher than usual TCP Close, Closing and Established metrics
![ASP_TCP_metrics](https://user-images.githubusercontent.com/123459930/220737523-53583535-be73-4994-98c3-a4164c45faba.png)

In addition the AppServicePlan was configured to scale instances out when CPU utilization reached above a threshold value, which it did twice from 1 instance to 2 instances, after the first scale out the webapp was still down and only after the second scale out the webapp was functional
![image](https://user-images.githubusercontent.com/123459930/220740358-a5371633-1c80-4159-8c5c-971265546617.png)

The AppService connects to a SQL Database, Cosmos Database and has Signal R integrated. We did not observe any unusual metrics in these resources.

Since this involves Azure AppService kindly let me know if this is the right place for this issue or should I create issue somewhere else

Thank You

**Comment by BrennanConroy** [comment]
Use a supported version:
https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle
.NET 5 has been out of support for almost 1 year now.

**Comment by shreyansh-casehippo** [comment]
Thank you. Closing this for now will re-open if we encounter this after upgrading
