### ISSUE TITLE
Examine the performance of AdditionalAssemblies in Router

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#46820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

 
```
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.routing.router.additionalassemblies?view=aspnetcore-7.0
```
While researching my problem recently, I came across a performance drop using ``AdditionalAssemblies``, my site on localhost takes 30ms to load, while using additional resources the performance drops to 40-50ms which gives us a performance drop of around 25%. I think it's worth looking into.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Using AdditionalAssemblies is expected to add some overhead and impact the performance. That's because those assemblies are being searched through at runtime for routable components within them. Hence, the time will be longer the larger is the list of additional assemblies.

**Comment by Alerinos** [comment]
@mkArtakMSFT 
Performance drops even when loading a single item. I did tests only on one additional subpage, I understand if it was a problem with 1000 pages.

Is there any solution to speed up this list?
My system consists of modules/plugins. Many subpages are in other projects, thanks to which I have order and independent modules.

Any idea how to benchmark this feature? In my free time, I will try to investigate this problem myself and possibly find a solution to speed up performance.

**Comment by Alerinos** [comment]
@mkArtakMSFT 
https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Components/Components/src/Routing/RouteTableFactory.cs#L35-L67

Can't we do it once when the app is launched? Why keep searching sets? Additionally, instead of searching the entire namesapce, can't we do it directly to one page?

I made a solution that I extend each page with IAreaWeb, thanks to which it is added to the Router, why create searches of entire sets when the programmer can make a direct reference to the file, thanks to which it will work faster. I think this function needs to be rebuilt, I can help to do it. Let me know what you think.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing additional findings, @Alerinos.
@surayya-MS what do you think about the above?

**Comment by javiercn** [comment]
@mkArtakMSFT @surayya-MS we will handle this differently in .NET 8.0 I believe.

**Comment by javiercn** [comment]
> Can't we do it once when the app is launched? Why keep searching sets? 

This happens once and then gets cached unless you change the set of assemblies that are passed to the router.

> Additionally, instead of searching the entire namespace, can't we do it directly to one page?

That code you referenced is discovering the pages in the assembly, so it needs to scan the assembly.

**Comment by mkArtakMSFT** [comment]
This will be addressed by https://github.com/dotnet/aspnetcore/issues/46980
