### ISSUE TITLE
ASP.Net Core 7 Email confirmation code is not persisted to Redis

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Token generation:
```
string code = await _userManager.GenerateEmailConfirmationTokenAsync(appUser);
code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
```
Email confirmation:
```
code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
IdentityResult identityResult = await _userManager.ConfirmEmailAsync(appUser, code);
```
Infrastructure:
```
service.AddDataProtection().PersistKeysToStackExchangeRedis(redis, "SomeString");

    builder.Services.AddIdentity<AppUser, IdentityRole>(o =>
    {
        // configure identity options
        o.SignIn.RequireConfirmedAccount = true;
        o.Password.RequireDigit = false;
        o.Password.RequireLowercase = false;
        o.Password.RequireUppercase = false;
        o.Password.RequireNonAlphanumeric = false;
        o.Password.RequiredLength = 6;
    })
        .AddEntityFrameworkStores<AppDbContext>()
        .AddDefaultTokenProviders();//.AddDefaultUI();
```
I don't see the email confirmation code persisted to the Redis:
```
lrange SomeString 0 -1
```

### .NET Version

7.0.102

**Comment by captainsafia** [comment]
The `PersistKeysToStackExchangeRedis` method is used to persist the DataProtection keys that are used to generate the confirmation codes to Redis, they don't persist the actually confirmation codes to Redis. That feature isn't supported in the framework at the moment so you'd have to implement this within your app code.

**Comment by khteh** [comment]
Any reference implementation? How to connect the storage with the `UserManager`?

**Comment by khteh** [comment]
How does this work out-of-box without any custom implementation of persistence storage?
