### ISSUE TITLE
SignalR send can take minutes to complete the task

### ISSUE THREAD

**Issue by josh-cooley** [dotnet/aspnetcore#46847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When sending a message to multiple groups, occasionally one of the sends will take minutes to complete.  If the update is sent to multiple groups in a loop then later messages are delayed by the same amount even if those complete promptly. 

### Expected Behavior

The Task returned from SendAsync should complete promptly or throw an exception.  Logging should be available to diagnose issues sending messages to clients.

### Steps To Reproduce

The code sends to multiple groups based on externally provided input.  An example based on the chat sample shows the send in a loop.
```
public async Task SendMessage(string[] rooms, string user, string message)
{
    foreach (var room in rooms)
    {
        await Clients.Group(room).SendAsync("ReceiveMessage", user, message);
    }
}
```
The actual code does this outside of the Hub and uses the `IHubContext<THub,T>` interface.  This is an intermittent problem with no discernable cause.

### .NET Version

6.0.401

**Comment by josh-cooley** [comment]
In the problem area, the application is getting vehicle updates about location, status, etc.  This vehicle information is being fed browser based clients through signalr groups.  A single vehicle update will be delivered to multiple groups.  Application logging shows that the server delivering the signalr messages to the client will have a pause in delivering updates for a one of the vehicles.  That client and subsequent clients in the groups will experience this as a pause in updating the vehicle location.

The pause in updates can take as long as 4-5 minutes before the task for sending the message to one group completes.  We can stop waiting on this task to avoid blocking other clients from getting updates, but we need to understand what circumstances can lead to a 4-5 minute pause on that task.

The application that sends the signalr updates is primarily a signalr based service that sends notifications to clients.  Other applications are responsible for providing http endpoints and distributing updates to the signalr application.  The applications use RabbitMQ to distribute updates that  are used to drive the notifications sent over signalr.  As the updates come in, tasks are run to find the right groups that should receive the updates.  The message is built, and then sent to all the groups (currently in sequence, but soon in batch).

We have tried network drops as well as network quality simulators between the browsers and the server to reproduce this issue, but have not been able to reproduce this either under controlled testing or under load in our test environments.

**Comment by davidfowl** [comment]
4-5 minute pause is *VERY* long. How much data is being sent to these groups?

**Comment by josh-cooley** [comment]
Our update reports are 2k-5k depending on how much changed.

**Comment by davidfowl** [comment]
At what rate? Is this data server driven or client driven?

**Comment by josh-cooley** [comment]
The rate is driven by a data server.  Vehicle location updates are processed by one service.  The location data is checked to see if an update is needed, and then broadcast at a predetermined rate.  In this case, we do not send individual location updates more frequent than every 5 seconds.

We have a multiplier effect with the number of groups and the number of vehicles.  In counting the messages sent out in an arbitrary minute, I found just over 19000 messages sent.  Even when there's a pause for one group, other message updates come in and are processed at a similar rate.  In a case containing a pause, a 5 minute block contains 176511 group messages with just one group pausing during that time.  Subsequent groups that were sent that message sent quickly after that group completed message completed.  Other messages do not encounter a pause and continue getting sent to other groups (not the one included in this pause).

Not all of the messages are location updates.  Some of the vehicle updates are user driven status updates that are sent out as a direct result of the user action.  The frequency of the location updates are what seem to trigger this pause though.  It can occur if just one vehicle drives down the freeway at 70 mph triggering the maximum update rate while others are not updating as quickly.

**Comment by davidfowl** [comment]
Take a look at this issue https://github.com/dotnet/aspnetcore/issues/43093, I wonder if it's similar to what you're seeing.

**Comment by josh-cooley** [comment]
This looks promising.  I will look to see if we have buffers filling up as well.  When looking for delays, I followed what looked like a flush being awaited.  Using the information in that issue, we hopefully can reproduce the issue in our test environment.
