### ISSUE TITLE
SignalR - OnConnectedAsync not triggered if utilized in partial class

### ISSUE THREAD

**Issue by shyamal890** [dotnet/aspnetcore#46841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For better maintainability we divided a Hub class into multiple partial classes. One of the partial class contains `OnConnectedAsync` and `OnDisconnectedAsync`.

These functions are not triggered when there are multiple partial class files. Removing multiple partial class files solves the issue. 

### Expected Behavior

The system should have been able to identify which partial class file contains `OnConnectedAsync` and `OnDisconnectedAsync` and trigger it

### .NET Version

7

**Comment by BrennanConroy** [comment]
That doesn't make any sense. Partial is just synatic sugar at the programming layer. At compile time it all becomes the same class as if you wrote it in the same file.

**Comment by shyamal890** [comment]
@BrennanConroy try it out, its not working with partial class

**Comment by BrennanConroy** [comment]
I did, and it works. So you're likely doing something wrong. e.g. Manually adding .cs files to your project in msbuild and forgetting to include the file with OnConnectedAsync.

If you're still convinced this is actually an issue, then provide a minimal repro app as a github project.

**Comment by shyamal890** [comment]
Seems like it was a faulty Azure Signalr app. Created a new one and it solved the issue
