### ISSUE TITLE
Blazor WASM Standalone

### ISSUE THREAD

**Issue by dkboon01** [dotnet/aspnetcore#46846]
In the release .net 8 preview 1 , is the multi threading in a browser been addressed so that we can try to use? We have a blazor wasm standalone application that has a grid that we believe could use the "loading of the data " in another thread

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There have been no major changes in multi-threading support for WebAssembly runtime in .NET 8 (yet). The experimental support for it has shipped in .NET 7 and you can read more about it from https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/#webassembly-multithreading-experimental
