### ISSUE TITLE
WebAuthn API Support

### ISSUE THREAD

**Issue by justinasmussen** [dotnet/aspnetcore#46858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

As part of the efforts to improve authentication & authorization experience, are there any plans to implement the new [WebAuthn API](https://w3c.github.io/webauthn/) in AspNetCore and Blazor? I would like to see a checkbox when setting up new project to scaffold Passwordless Auth e.g. WebAuthn in the Authentication/Authorization template in VS.

[webauthn.me](https://webauthn.me/)

Thanks, Justin.

**Comment by Tratcher** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/4657

**Comment by captainsafia** [comment]
Triage: Closing as a dupe of #4657. This needs more design and considerable work.
