### ISSUE TITLE
DeveloperExceptionPage showing and disappearing fast 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#46859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Today I've faced a strange issue, where my ASP.net Razor Pages app was starting (iisexpress F5 debug) showing the developer error page for less than 1 second and after showing blank page.

I had to use a screen recorder to be able to see the error.

The error was "file not found, could not load file or assembly 'Newtonsoft.json Version=13.0'
(I'm referencing a dll which uses it, and my current project is referencing Newtonsoft.json version 12)

### Expected Behavior

See the error at build time or at least on the developer exception page, without it showing for only 10ms.
(I was getting a warning mentioning the version conflict)

### .NET Version

was 6, tried with 7 as well

**Comment by Tratcher** [comment]
What shows up in the logs/console?

What shows up in the browser dev tools?

Does it do the same thing if you switch to Kestrel?

**Comment by omuleanu** [comment]
@Tratcher I deleted everything in Layout.cshtml but head/body tags and `@RenderBody`, 
and I do see the error, the whole disappearing thing was because of my code, and it was present in the console (failed request 500)

**Comment by omuleanu** [comment]
@Tratcher the DeveloperException Page has these divs (tabs) with `class="page"` (Stack, Query, Cookies, Headers, Routing)
and there's some js that hides them;
and my html also had a div with class `page` around the `@RenderBody`, so that was the reason for the hiding.
```
<div class="page">
        @RenderBody()
</div>
```
I'm reopening, it's up to you now, if it's an issue or not.

**Comment by Tratcher** [comment]
The Developer Exception Page shouldn't be producing a body if you already did. Are you buffering the response?

**Comment by omuleanu** [comment]
@Tratcher not exactly sure how would I do that, so I presume not.
It basically goes to my `Index.cshtml` renders
```
<h1> Hi </h1>
```
and after it hits:
```
@Html.HelperFromLibThatUsesDifferentVersionJson
```
and in the resulting html after the render `<h1> Hi </h1>`, it renders this:
```
<meta charset="utf-8">
<title>Internal Server Error</title>
<style>...
...
```

**Comment by Tratcher** [comment]
Hmm, writing `<h1> Hi </h1>` to the response should have changed HasStarted, which is what the middleware uses to avoid mixed responses. To avoid HasStarted, the write would have had to go into a buffer and not get flushed to the server. I wonder if that buffer is the HttpResponse.BodyWriter, or if some middleware has enabled buffering, like app insights. We'll need to investigate.

https://github.com/dotnet/aspnetcore/blob/e73199f585a8a69c02eab3c2819e9b88e1e30ee4/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L118-L122

**Comment by omuleanu** [comment]
@Tratcher here's an isolated demo:
https://drive.google.com/file/d/1fzb2IKL-viJ7kpURQjp8rG8PZ9eF05_6/view?usp=sharing

unzip, open sln, ctrl+f5, note the blank page, look at the source

**Comment by adityamandaleeka** [comment]
@omuleanu It looks like this is specific to the third-party library you're using (AwesomeMVC). If, in your code, you replace the call after your "hi message" to call a method in your own code that just throws, you should see the correct behavior (only the exception page content will appear and not anything else before it).

If you're not able to reproduce this issue without using AwesomeMVC, perhaps you could report this to the AwesomeMVC developers to investigate.

**Comment by omuleanu** [comment]
@adityamandaleeka @Tratcher I can reproduce it without the lib.
1) have this in a separate Class Library (with Newtonsoft.Json 13)
```
    public class MyList : IHtmlContent
    {
        string render()
        {
            var res = JsonConvert.SerializeObject(new { Item1 = "abc" });
            return "list";
        }

        public void WriteTo(TextWriter writer, HtmlEncoder encoder)
        {
            writer.Write(render());
        }
    }

    public static class Helpers
    {
        public static MyList MyList1(this IHtmlHelper helper)
        {
            return new MyList();
        }
    }
```
2) In an ASP.net core  app with Newtonsoft.Json 12 reference the dll (you won't be able to build if you reference project directly).

3) call the helper in Index.cshtml `Html.MyList1()` and `Ctrl+F5`

**Comment by adityamandaleeka** [comment]
Thanks @omuleanu, will take a look.

**Comment by adityamandaleeka** [comment]
Hmm... I followed those steps and don't see this issue. Can you share your repro project as a public github repo?

**Comment by omuleanu** [comment]
@adityamandaleeka 
seems that it only happens on Razor Pages,
you can try it here: 
https://github.com/omuleanu/RazorPagesDevPageBug
in this case the error is a missing dependency,
but it can be anything, you can replace my `JsonConvert.SerializeObject` with a simple `throw new Exception`

**Comment by adityamandaleeka** [comment]
Thanks for the new repro @omuleanu, I can see the issue. We'll need to investigate.

cc @MackinnonBuck, not sure yet if this bug is in Razor or in server code.

**Comment by adityamandaleeka** [comment]
@vijayrkn Can you help route this?

**Comment by tlmii** [comment]
@vijayrkn It's in the injection layer. The response is buffered back to VS and the core browserlink logic for the script injection, and then written back out as we get the response back from VS. Doesn't look like there's a clean way to call Response.StartAsync at the moment, so it'll take some refactoring. But seems doable.

**Comment by Tratcher** [comment]
@tlmii the other way to trigger StartAsync is to call Flush/Async on the inner stream when ScriptInjectionFilterStream intercepts its first write. (make sure you edit any headers you need to first, like removing Content-Length). This causes the headers to be sent to the client and for Response.HasStarted to be set. That should disable any further exception handling logic and avoid mixed responses like this.

**Comment by tlmii** [comment]
@Tratcher Thanks for the tip. That made it a lot easier. I've sent out a PR in WebTools and added you as a reviewer if you want to take a look. The developer experience isn't necessarily great in this particular scenario (it shows a blank page instead of the developer exception page) but it's certainly more correct and likely unblocks other scenarios that were broken by this behavior.

**Comment by tlmii** [comment]
PR has been completed. It'll be a little while before it flows to customers though.

cc @Tratcher for whatever housekeeping needs to be done on this issue.

**Comment by omuleanu** [comment]
@tlmii so in razor pages when getting a similar error, we'll get a completely empty result (blank page) without any idea of what happened ?

**Comment by tlmii** [comment]
@omuleanu The DeveloperExceptionPageMiddleware will [log an error](https://github.com/dotnet/aspnetcore/blob/d4be4957c24c7c8b745ade4cbaf290ad9cad1ad2/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L120) about what happened. But visually, yes, the page will be blank. We're looking at how we can unblock this a different way but don't have a great solution at the moment.

**Comment by omuleanu** [comment]
@tlmii think until you have a solution it will be better to leave it the way it was

**Comment by Tratcher** [comment]
@tlmii let's leave this open until you can give us details about what version will contain the fix.

**Comment by Tratcher** [comment]
> @tlmii Tim Mulholland FTE think until you have a solution it will be better to leave it the way it was.
> 
> You could change the `.page` css class used by the dev error page to something more unique, so it won't hide content on the exiting page (since it has `display:none` )

It was a bit of a fluke that you could see any content at all in this scenario. Writing a second response in the middle of the first one is usually going to break. Once the first response has started, there's very little the server can do to indicate an error to the client, server logs are the only reliable mechanism.

**Comment by tlmii** [comment]
@Tratcher It'll be in 17.6 Preview 3 and later.
