### ISSUE TITLE
iisexpresstray crashes when starting a site from visual studio 2022 17.5.0

### ISSUE THREAD

**Issue by equirev73** [dotnet/aspnetcore#46851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi. I am a VS2022 user. I updated it to version 17.5.0. Every time I try to view in the browser, the iisexpresstray (IIS Express) appears. But when you pass the mouse disappears. An error appears in Event Viewer. IIS Express is still working.

I have "Reset this PC" three times and reinstalled Win11 and visual studio each time. I also tested on a virtual machine, Win11. Same error.
[Windows 11 - 12400 - 16gb - M2 TB]

Any idea ?. Thanks a lot.-

pd: my Thinkpad X1 Win10 VS2022 updated to 17.5.0 works fine!

### Steps To Reproduce

Visual Studio > New project > ASP.NET Core (Model - View - Controller), Blazor App Wasm.
View > Edge or Chrome ...

### .NET Version

5.0 and 6.0

### Anything else?

![IISExpress3](https://user-images.githubusercontent.com/58412457/221049184-5d27fbc3-d39b-4fdf-850a-eedc7105861a.gif)
![image](https://user-images.githubusercontent.com/58412457/221049265-0f4435ab-216e-4e57-bd29-528703a0e182.png)

**Comment by Wael3bbas** [comment]
I am having the same issue after updating VS to 17.5.0

**Comment by equirev73** [comment]
Hi Wael3bbas. I hope they fix it soon...

https://developercommunity.visualstudio.com/t/iisexpress-crashes-in-ntdlldll/10290067

Meanwhile....

"I found that manually launching the x86 version of IIS Express Tray seems to work (VS launches the x64 version and that one is the one that crashes). Try that as a temporary workaround? – Euro Micelli"

https://stackoverflow.com/questions/75550968/iisexpresstray-crashes-when-starting-a-site-from-visual-studio

I hope it helps you.

**Comment by adityamandaleeka** [comment]
iisexpresstray isn't part of ASP.NET Core (and our code doesn't run there) so we can't do anything here unfortunately.

Your feedback ticket on Developer Community should get routed to the correct team though.

**Comment by equirev73** [comment]
As Michael Bursill says:
"Help/Privacy/Privacy Settings… and switched "Yes, I am willing to participate" off and the crash went away."

Thanks Michael Bursill.

https://developercommunity.visualstudio.com/t/iisexpress-crashes-in-ntdlldll/10290067
