### ISSUE TITLE
Blazor Routes API Request to Page

### ISSUE THREAD

**Issue by kakins** [dotnet/aspnetcore#46850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Server + WASM app, with two nearly identical components with a layout like the following:

#### Pages\Configuration\SiteList.razor
- Page Route: `/sites` 
- API call made on page load: `/api/configuration/sites`
- This API succeeds and loads the `SiteList` page successfully.  ✔️ 

#### Pages\Configuration\IntegrationList.razor
- Page Route: `/integrations`
- API call made on page load: `/api/configuration/integrations`
- This API call **returns a response with the contents of the Blazor page at "/integrations" instead of the API endpoint "/api/configuration/integrations"**.  ❌ 

### Expected Behavior

I would expect both of these components to behave exactly the same, since their folder structures, controller conventions, and behaviors are nearly identical. 

#### Pages\Configuration\IntegrationList.razor
```csharp
@page "/integrations"
@inject HttpClient Http

@code {
    protected override async Task OnInitializedAsync()
    {
        var result = await Http.GetFromJsonAsync<string>("api/configuration/integrations");
    }
}
```
#### Pages\Configuration\SiteList.razor
```csharp
@page "/sites"
@inject HttpClient Http

@code {
    protected override async Task OnInitializedAsync()
    {
        var result = await Http.GetFromJsonAsync<string>("api/configuration/sites");
    }
}
```
#### IntegrationsController
```csharp
    [ApiController]
    [Route("api/configuration/integrations")]
    public class IntegrationsController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            return "OK"
        }
    }
```

#### SitesController
```csharp
    [ApiController]
    [Route("api/configuration/sites")]
    public class SitesController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            return "OK"
        }
    }
```

### Exceptions (if any)

Because the HttpClient request is returning the Blazor page response

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.IEnumerable`1[[KitchenIntegrations.Monitoring.Shared.Domain.Configuration.Integration, KitchenIntegrations.Monitoring.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
```

### .NET Version

6.0

### Anything else?

When I change the API route from `/configuration/integrations` to `/configuration/integrationz` it works.

**Comment by kakins** [comment]
Yeah I don't have much time to put together a separate repo for this, other than the code I gave above.  Seeing that I'm just experimenting/evaluating Blazor.  But it seems to clearly be a thing and a bug.  Hopefully someone else will encounter it and have time to give more info.  For the time being I'll just work around it I guess.

**Comment by javiercn** [comment]
@kakins thanks for contacting us.

Very likely this is a bug in your app. If you look at the network tab you'll see that the request is not going to `api/configuration/sites`. Put a `/` and see if that addresses the issue.

What's happening here is that the code is failing to hit the controller for some reason and is falling back to the Blazor fallback route that returns the main document.

You can get more details about what is going on by turning the logs for routing to Debug.

**Comment by kakins** [comment]
This is still a problem.  I've been struggling to see why these routes don't match...

![image](https://user-images.githubusercontent.com/14915247/227312724-6f6d41fc-f3f8-4ccc-a454-d3afe873ac03.png)

I've also tried HttpGet("/") and HttpGet("")

**Comment by kakins** [comment]
Ok, so it seems to have been at least in part a browser caching issue.  I guess perhaps some Blazor routes were cached with a routing scheme which was not updated, even after multiple restarts of the blazor app.

**Comment by kakins** [comment]
This is so bizarre.  I've opened a browser in a new incognito window, and executed the same API request from blazor, which succeeds.  Trying from the original window fails.  I've tried clearing cookies and cache, doesn't seem to help.
