### ISSUE TITLE
JsonSubkeyClaimAction arrays

### ISSUE THREAD

**Issue by miloush** [dotnet/aspnetcore#46864]
`JsonKeyClaimAction` seems to support arrays:

https://github.com/dotnet/aspnetcore/blob/2374b45dea7fef3dfeed7eebb5d09ef8757fd14f/src/Security/Authentication/OAuth/src/JsonKeyClaimAction.cs#L39-L45

Can we have the same for `JsonSubkeyClaimAction`?

**Comment by Tratcher** [comment]
Ok, want to send a PR?

**Comment by miloush** [comment]
@Tratcher sure here you go
