### ISSUE TITLE
Identity: Adding user to role gives an Invalid Username error (UserManager.cs).

### ISSUE THREAD

**Issue by isahin1997** [dotnet/aspnetcore#46860]
Its possible to create users with Turkish characters like ı or even with whitespaces. But when assigning a role through the UserManager returns an identityerror with Invalid Username.

Example:
create user with username: Yazıcı .
-> user created.
assign role to user with UserManager
> returns identity error with the following info:
Code: InvalidUserName.
Description: Username 'Yazıcı ' is invalid, can only contain letters or digits.

**Comment by captainsafia** [comment]
Triage: @isahin1997 Have you tried using the `NormalizedUsername` on the user for this?

**Comment by isahin1997** [comment]
Not sure what you mean as the UserManager.AddToRoleAsync() Expects a Tuser (the user) and string (rolename).

**Comment by captainsafia** [comment]
@isahin1997 Correct! Do you happen to have a stacktrace for the exception? We have some assumptions about where the bug might be coming from but a stacktrace would help track the exact codepath.
