### ISSUE TITLE
[SignalR] Server doesn't stop streaming after cancellation on client

### ISSUE THREAD

**Issue by AndreiGorlov** [dotnet/aspnetcore#46861]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

While experimenting with SignalR server-to-client streaming, I noticed that the server does not stop streaming if it was canceled on the client side.
The client continue to receive stream items and just ignore it (https://gist.github.com/AndreiGorlov/6925f610f880ff212bf146f6b85e965d#file-client-log-L119-L128)
The server receives an unexpected CancelInvocationMessage after the stream has been completely transferred (https://gist.github.com/AndreiGorlov/7710d3a590eb55295e9912bf830bdc39#file-server-log-L47-L48)

### Expected Behavior

Server stops streaming after cancellation.

### Steps To Reproduce

repro: https://github.com/AndreiGorlov/SignalRStreamSandbox
server.log: https://gist.github.com/AndreiGorlov/7710d3a590eb55295e9912bf830bdc39
client.log: https://gist.github.com/AndreiGorlov/6925f610f880ff212bf146f6b85e965d

### .NET Version

7.0.200

**Comment by BrennanConroy** [comment]
Good find, I think this got broken by https://github.com/dotnet/aspnetcore/pull/41180, where we now pass the cancellation token to FlushAsync, which is what writes the message to the network, and now the cancel invocation message won't be written until the next write, e.g. a ping.
