### ISSUE TITLE
ASP.Net Core 7 Identity Email Confirmation "Invalid token" Error.

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#46875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/issues/46827

Using GMail for `IEmailSender`, I receive the email confirmation but when I click the URL, it hits the "Invalid token" error at `UserManager.ConfirmEmailAsync()`. How to properly implement this without using the scaffolded pages? How do I store and retrieve the generated email confirmation code that's usable by `UserManager`?

### Expected Behavior

Email confirmation should work

### .NET Version

7.0.102

**Comment by captainsafia** [comment]
Triage:

> How to properly implement this without using the scaffolded pages? How do I store and retrieve the generated email confirmation code that's usable by UserManager?

Have you tried mimicking the flow that is in the scaffolded pages? You can view an example of this code [here](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml).

In particular, you'll want to take advantage of the [GenerateEmailConfirmationTokenAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.generateemailconfirmationtokenasync?view=aspnetcore-7.0) method.

**Comment by khteh** [comment]
> Triage:
> 
> > How to properly implement this without using the scaffolded pages? How do I store and retrieve the generated email confirmation code that's usable by UserManager?
> 
> Have you tried mimicking the flow that is in the scaffolded pages? You can view an example of this code [here](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml).
> 
> In particular, you'll want to take advantage of the [GenerateEmailConfirmationTokenAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.generateemailconfirmationtokenasync?view=aspnetcore-7.0) method.

Please read and understand the issue carefully, at least 3 times, before you answer! This is the second post of the underlying problems behind not being able to validate the generated confirmation code.

**Comment by khteh** [comment]
Does `_userManager.GenerateEmailConfirmationTokenAsync(user);` store the generated code anywhere for later retrieval by `_userManager.ConfirmEmailAsync(appUser, code);`? If yes, which table? If no, how does this work across restart of the identity server?

**Comment by captainsafia** [comment]
> If yes, which table? If no, how does this work across restart of the identity server?

It's not stored in a table. The confirmation code is generated by the data protection APIs. If the server reboots and data protection keys are not persisted, then the confirmation code will be lost since you can't validate against the data protection key it was validated with.

**Comment by khteh** [comment]
I generated the code on user RegisterConfirmation page:
```
                code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
```
And when user clicks the URL from received email:
```
IdentityResult identityResult = await _userManager.ConfirmEmailAsync(appUser, code);
```
`Invalid Token` error. I use Redis for data protection key and can see the key in the redis cluster.
