### ISSUE TITLE
Dynamically change user roles/authentication state in blazor server for logged in user upon user action

### ISSUE THREAD

**Issue by ahvvt** [dotnet/aspnetcore#46881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am unable to change user roles/claims based on the user's action after they are logged in. The authentication state seems to be set only once when they log in but cannot be changed after that.

Please see the details here: 
[Stackoverflow question](https://stackoverflow.com/questions/75561815/dynamically-change-user-roles-authentication-state-blazor-server)

### Expected Behavior

Ability to change the authentication state for logged in user.

### .NET Version

.net7

**Comment by brockallen** [comment]
Related? https://github.com/dotnet/aspnetcore/issues/46396#issuecomment-1414054414

**Comment by ahvvt** [comment]
I am only using Blazor Server. 
For my use case, the user is part of two organizations and the user's roles and claims need to be updated based on whichever organization they choose from a dropdown.
