### ISSUE TITLE
ASP.NET Identity token provider clarifications

### ISSUE THREAD

**Issue by jtheisen** [dotnet/aspnetcore#46892]
I want to use token providers for allowing to give a user a time-limited "login token" within a Blazor app and then redirect him to an endpoint that can actually do the login with a `SigninManager`, not requiring credentials but instead validating the token. There may be other cases where I also want to use this token providers. So I dug around Identity's sources a bit and some questions came up.

Have a look at [`TokenOptions.cs`](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/TokenOptions.cs).

The value `DefaultEmailProvider` appears not to be used at all, and the more specific email cases such as `EmailConfirmationTokenProvider` are all set to `DefaultProvider `.

That's unlike `DefaultPhoneProvider `, which is used by `ChangePhoneNumberTokenProvider `.

What this means when using [`AddDefaultTokenProviders`](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityBuilderExtensions.cs) is that for email, a `DataProtectorTokenProvider<>` provider is used, not the `EmailTokenProvider<>` (which is a `TotpSecurityStampBasedTokenProvider<>`).

Also strange is that `TotpSecurityStampBasedTokenProvider<>` says it's using the security stamp, but `DataProtectorTokenProvider<>` does that too (if possible). The former appears to have an expiration though.

My questions are:

* Why isn't the `EmailConfirmationTokenProvider<>` used at all?
* Why are there two basic token implementation providers `TotpSecurityStampBasedTokenProvider<>` and `DataProtectorTokenProvider<>`? When should I use which?
* Which should I use for the specific case of issuing a token from within Blazor to allow a credential-less login for the next 10 seconds? Is it safe to use a `DataProtectorTokenProvider<>` for this or am I not understanding something here?

**Comment by captainsafia** [comment]
Triage: It sounds like you're trying to implement a "magic link" style login experience for your application. At the moment, this isn't supported by token APIs that you've identified here.

**Comment by jtheisen** [comment]
Can you say something about the first two questions?
