### ISSUE TITLE
InputSelect doesn't honor the required attribute

### ISSUE THREAD

**Issue by giarico** [dotnet/aspnetcore#46890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i submit the form, if I don't change the value of the select, I have no validation error.
If I change value and go back to the empty choice, the error is shown.

It works correctly with a nullable int, but i can't modify the model.

```
public class MyModel
{
    [Required]
    public int MyProperty { get; set; }
}

```
```
<EditForm Model="model" OnValidSubmit="HandleValidSubmit">

    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputSelect @bind-Value="model.MyProperty">
        <option></option>
        <option value="1">1</option>
        <option value="2">2</option>
    </InputSelect>

    <button type="submit">Save</button>
</EditForm>

@code 
{
    MyModel model = new();

    void HandleValidSubmit()
    {
        
    }
}
```

### Expected Behavior

The validation should trigger also when I don't modify the choice

### Steps To Reproduce

Just push the submit button without doing anything first

### .NET Version

7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Because your model type is `int` it always has a value. Whereas your `select` element has an empty option, which is not mappable to an integer value. So either you should change to an `int?` model (use a wrapper if you don't control the actual type) or you remove the `empty` option from the select.

**Comment by giarico** [comment]
Sorry but how can you say this is solved?
The validation is working also with int, but only when you change the option and you go back to the empty choice.

**Comment by giarico** [comment]
This is when you click insert without changing option
![first](https://user-images.githubusercontent.com/22771799/221937159-9eea24db-4530-4b52-8bde-075635e72cbe.jpg)

This is when you click insert changing option and going back to the empty choice
![second](https://user-images.githubusercontent.com/22771799/221937179-c6e46aa5-8eb6-477f-8b6d-a74485576893.jpg)

Can you see the bug now?
