### ISSUE TITLE
publish Microsoft.AspNetCore.App as nuget again? Issues in dontet interactive and fsharp scripts

### ISSUE THREAD

**Issue by jkone27** [dotnet/aspnetcore#46891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

at the moment is not possible to use aspnetcore in F# .fsx script, or other interactive environments, i tried aspnet interactive 

https://www.nuget.org/packages/Microsoft.DotNet.Interactive.AspNetCore/

also some issues was opened in fsharp but didnt see any recent development yet

https://github.com/dotnet/fsharp/issues/8688
https://github.com/dotnet/interactive/issues/861
https://github.com/dotnet/fsharp/issues/8688

but didnt work / didnt expose the apis needed to build usual aspnet app..

```fsharp
//somefile.fsx in vscode with ionide (or visual studio or rider..)

#r "nuget: Microsoft.AspNetCore.App" // or proposed alternatives see above github issues
open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Mvc
open Microsoft.AspNetCore.Builder // ..etc..

//rest of the script ...
app.Run()


```

to be able to run aspnet core apps in 1 single file (a bit like python)

```
dotnet fsi myApp.fsx
```

### Describe the solution you'd like

to be able to run aspnet core apps in 1 single file (a bit like python)

```
dotnet fsi myApp.fsx
```

### Additional context

not clear how to handle framework references as indipendent "assets" in interactive scripts which do not have projects (or have projects but just behind the scenes...)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. That package is old, and we don't plan to ship an updated version of it.
What is the target framework that you're publishing with your application? Can you not use a more recent version of .NET (6 or 7)?
