### ISSUE TITLE
Add parameterless overload for `RequireCors` API

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#46922]
## Background and Motivation

The `RequireCors` extension method is an imperative style API designed to be used in conjunction with endpoints as an alternative to the `EnableCors` attribute.

At the moment, the `RequireCors` method provides two overloads:

- One that takes a policy name as a string parameter
- One that takes a policy builder as a parameter

At the moment, there is no way to invoke `RequireCors` with the default behavior that is available in the `EnableCors` attribute as mentioned [here](https://github.com/dotnet/AspNetCore.Docs/issues/28420#issuecomment-1433625745) since the invocation would be ambiguous between the two overloads:

```csharp
app.MapGet("/", () => "Hello world!")
  .RequireCors(null); // Ambiguous between string or Action overload
```

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

public static class CorsEndpointConventionBuilderExtensions
{
+  public static TBuilder RequireCors<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
}
```

## Usage Examples

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddCors();

var app = builder.Build();
app.UseCors();

app.MapGet("/", () => "Hello world!")
  .RequireCors(); // Uses CorsOptions.DefaultPolicyName

app.Run();
```

## Alternative Designs

- Require users to use the pre-existing `EnableCors` attributes on endpoints to get the desired behavior

**Comment by BrennanConroy** [comment]
API Review Notes:
* Makes sense, I have no concerns/questions

API Approved!

```diff
namespace Microsoft.AspNetCore.Builder;

public static class CorsEndpointConventionBuilderExtensions
{
+  public static TBuilder RequireCors<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
}
```
