### ISSUE TITLE
Blazor @Key parameter causes control focus to be lost on mobile / touch devices

### ISSUE THREAD

**Issue by mruch2** [dotnet/aspnetcore#46924]
Using a foreach loop to render controls on the UI that have the same model. I generate several child components dynamically. When I do this without the `@key` parameter the controls do not lose focus but they persist the data when I do not wish them to. This does not happen while using a mouse. This only happens on touch devices.

Blazor WASM
.Net 7

Here is my code:

```
@foreach (DimensionValue item in BasicDimensions)
   {
        <TBNumericTextBoxdbl @key=item.Id dimMgr=DimMgr Dimension="@item" UOMText="@DimMgr.UOM.Name"
                          @bind-Locked="@item.Locked"
                         @bind-ControlValue="@item.Value"
                         @bind-OrbColor="@item.OrbColor"
                         OrbClicked=@(() => OrbClicked(item.NotificationInfo))>
        </TBNumericTextBoxdbl>

    }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please share more details about the scenario? Also, please provide a minimalistic repro project, where all the unnecessary code is stripped out.

**Comment by mruch2** [comment]
@mkArtakMSFT go ahead and close the issue, building the mini project helped me figure out I need to handle validation for resize events when it comes to soft keyboards on android.
