### ISSUE TITLE
SignalR - Connect - Response 404 No Connection with that ID - No Scaling

### ISSUE THREAD

**Issue by leaders-mindes** [dotnet/aspnetcore#46929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I have a project with the following components: 
1- .NET core Web API application (.net 6) with one SignalR hub endpoint using the framework reference (no deprecated package used).
2- Angular frontend application.
3- SQL Server DB.

This project is intended to be deployed once per customer, so 2 customers will result in 2 separate deployments (API, Web and DB), so nothing will be shared between multiple customers.

We have one server and one shared DB Engine on it.

When I deploy the project on the server I use one port for each customer, so if I have two deployments on the server (IP: 1.2.3.4) the application will be accessible like this for example:
Customer A: 1.2.3.4:9000
Customer B: 1.2.3.4:9002
and so on, currently I'm testing on 2 only.

No need to any interaction between the deployments, each deployment should have it's own SignalR handling, I'm not talking about scaling out one application here, it's totally different scenario, it's two separate deployments on separate server ports.

When I deploy the first one it works fine, SignalR connection is working using web socket and everything is okay.
But when the second deployment on the same server on other port is up, it works but SignalR connection on that deployment doesn't work at all and keeps returning 404 (No Connection with that ID) while still everything is fine on the first deployment.

I traced the traffic and made sure that every deployment have it's endpoints configured correctly and the failing SignalR is going to the right place.

Notes:
- No cloud server used, it's a local server (Linux).
- No scaling out used.
- No clustering or load balancing used.
- No shared services between the deployments
- The DB engine is shared but each customer has it's own database.
- My web server is Nginx (Direct to Web and proxy to Kestrel for the API) => one for each deployment.
- I followed all Microsoft Nginx deployment guidelines for the API and SignalR.
- I'm using docker.
- I tried enabling Sticky Sessions and it didn't solve the issue, I know it's not for this case but I just tried it using SQL Server backplane.

Please advice.

### Expected Behavior

SignalR should work normally for each deployment sparately if I have the same application deployed twice on the same server but on different ports, because this is a case of two applications and shouldn't need Sticky Sessions or anything else.

### Steps To Reproduce

- Create a .NET Core Web API with SignalR hub ("/api/hub")
- Deploy twice on same server on different ports
- Try to connect to the hub  web client for each deployment.

### Exceptions (if any)

Http 404

Unable to connect to the server with any of the available transports. WebSockets failed: Error: There was an error with the transport. ServerSentEvents failed: Error: Error occurred LongPolling failed: Error: Not Found

### .NET Version

6.0

**Comment by BrennanConroy** [comment]
Enable client and server logging to see if that provides any hints about what might be wrong.
https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-7.0

**Comment by davidfowl** [comment]
> No clustering or load balancing used.

> I followed all Microsoft Nginx deployment guidelines for the API and SignalR.

So you're using nginx or not using nginx? 

As @BrennanConroy said, logging is the way to go.

**Comment by leaders-mindes** [comment]
> > No clustering or load balancing used.
> 
> > I followed all Microsoft Nginx deployment guidelines for the API and SignalR.
> 
> So you're using nginx or not using nginx?
> 
> As @BrennanConroy said, logging is the way to go.

Yes I'm using NginX as a web server, I have a docker-compose for the project which have backend service and frontend service, the backend service is to run the web API using .net core image with the default Kestrel, the frontend service is Nginx image hosting the Angular app and acting as a proxy to the web API, so API request goes to Nginx first then Nginx forwarding it to the backend service where Kestrel will continue.

The above docker compose can be used for multiple deployments as you know using different configs for each one.

**Comment by leaders-mindes** [comment]
> Enable client and server logging to see if that provides any hints about what might be wrong. https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-7.0

Sure, I'll try and check.

**Comment by leaders-mindes** [comment]
I enabled the Debug log level on both server and client and redeployed locally, seems nothing wrong on the server side, but on the client side I got more details:

1. First instance (Customer A) => success
![image](https://user-images.githubusercontent.com/112489364/222133171-3a22b38e-1bc1-4bea-be5f-87ed704780e0.png)

2. Second instance (Customer B) => fail
![image](https://user-images.githubusercontent.com/112489364/222133554-d33a5356-9e67-4b12-9073-697b677be271.png)

Please check and advice @BrennanConroy @davidfowl

**Comment by BrennanConroy** [comment]
Those server logs aren't useful, you're hiding other requests that we want to make sure are there, and also ideally you'd remove auth so it doesn't pollute the logs so much (plus auth tokens could have PII).

**Comment by leaders-mindes** [comment]
> Those server logs aren't useful, you're hiding other requests that we want to make sure are there, and also ideally you'd remove auth so it doesn't pollute the logs so much (plus auth tokens could have PII).
> 
> Specifically what we're looking for is an `api/signalr/hub/negotiate` request followed by the `api/signalr/hub` request that you showed above. If you don't see both of those from the same client within 15 seconds of each other, then you're hitting an issue with the proxy.

Thanks for your support @BrennanConroy , I checked the above, the `api/signalr/hub/negotiate` call is executed successfully with 200 response, I watched the time span between `api/signalr/hub/negotiate` and `api/signalr/hub` requests from the server logs and from Network in Dev Tools and it's very short (same second).

Let's remember that the first deployment also has the proxy and SignalR working fine on it, and if I dropped it (compose down) SignalR in the second deployment works!!

When the two instances are up, the first being up has it's SignalR working fine, the second being up has the negotiate working fine but the hub calls are not working so no connection.

**Comment by davidfowl** [comment]
The primary reason you'd get a 404 is because the negotiate request and connection request landed on the different instances. I know you said it's single instance but give the above information, it's not clear to me that things are working the way you describe.

It might help if you draw out each component as a box and run through how requests make it to each of the instances. That might help us help you diagnose the problem.

**Comment by leaders-mindes** [comment]
Thanks for your kind collaboration guys.
I would like to inform you that I tried forcing the websocket protocol only without fallbacks by setting the following in Angular client:

```
transport: signalR.HttpTransportType.WebSockets,
        skipNegotiation: true
```


and on server hub:
```
endpoints.MapHub<AppHub>("/api/signalr/hub", (options) =>
                {
                    options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
                });
```

and it worked correctly on two instances and without any interceptions, this is strange because nothing was blocking the websocket to work so I don't know why the fallbacks were causing the issue.

I'm not sure if this is the right solution but at least it worked.

I'll try to illustrate my structure when I have some extra time if this will help you to find out the root cause of this issue.

**Comment by BrennanConroy** [comment]
That convinces me even more that you're hitting two different servers, the /negotiate hitting one, then the websocket hitting a different one.

I would grab [network logs](https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-8.0#network-traces) so we can see the flow of both the negotiate and the websocket request.

**Comment by leaders-mindes** [comment]
> I enabled the Debug log level on both server and client and redeployed locally, seems nothing wrong on the server side, but on the client side I got more details:
> 
> 1. First instance (Customer A) => success
>    ![image](https://user-images.githubusercontent.com/112489364/222133171-3a22b38e-1bc1-4bea-be5f-87ed704780e0.png)
> 2. Second instance (Customer B) => fail
>    ![image](https://user-images.githubusercontent.com/112489364/222133554-d33a5356-9e67-4b12-9073-697b677be271.png)
> 3. Server logs:
>    ![image](https://user-images.githubusercontent.com/112489364/222134858-1f9f8f7a-3966-49d1-9d66-b577f77044be.png)
> 
> Please check and advice @BrennanConroy @davidfowl

You can observe the URLs in the browser log images in the above post, it goes to the same endpoint for sure.
Customer A goes to instance on port 9000 both /negotiate and /hub, 
Customer B goes to instance 9002 both /negotiate and /hub

**Comment by BrennanConroy** [comment]
> You can observe the URLs in the browser log images (1 and 2) in the above post, it goes to the same endpoint for sure.

Those urls don't really matter when you have a proxy that could be doing anything to the requests.

1. You should try removing nginx, hosting both servers on the same machine, and hitting them manually with the browser client.

2. If you're still seeing the same problem, then one server at a time; look at the browser network traces, find the negotiate response, see the `connectionToken`, and check the server logs to see if the negotiate request hit the same server as the `/web-api/api/signalr/hub?id=<connectionToken>` request.
![image](https://user-images.githubusercontent.com/7574801/223581240-b975b9f3-2f82-4745-937e-101bb4201b8a.png)
