### ISSUE TITLE
Consume SequenceReader from CoreFX

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/aspnetcore#4693]
`SequenceReader<T>` is the CoreFX implementation of `BufferReader<T>`.  Any drop of CoreFX past https://github.com/dotnet/corefx/commit/9ae14ba629e7547b2d27180431cfd7f5a3c14709 will have this type.

https://github.com/aspnet/KestrelHttpServer/pull/3068 implements changes that are based on an API compatible `BufferReader<T>` that `SequenceReader<T>` should just drop in and replace.

**Comment by JeremyKuhne** [comment]
@davidfowl I just put up the PR to consume the CoreFX type without changing the parser. I'll port the change on top of that.

**Comment by anurse** [comment]
@JeremyKuhne is there something left to do here after your earlier PR?

**Comment by JeremyKuhne** [comment]
I didn't port my header parsing rearchitecture as it collided with other changes. It had significant improvements in microbenchmarks but it would need to be redone and reevaluated.

https://github.com/aspnet/KestrelHttpServer/pull/3068

It would be worth examining again, but I don't think there is any need to do it for a given milestone.

**Comment by anurse** [comment]
Gotcha, thanks for helping to catch me up!

**Comment by jkotalik** [comment]
I believe this is mostly done and the rest is covered by https://github.com/dotnet/aspnetcore/issues/4720.
