### ISSUE TITLE
FeatureCollection can throw NRE with structs

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#46939]
This code is not supposed to throw an exception but return `null`. However, when the type is a struct then it will throw an NRE.

https://github.com/dotnet/aspnetcore/blob/6647d80ab886b8616e5b34812853e00358c93ce5/src/Extensions/Features/src/FeatureCollection.cs#L118-L121

The compiler calls [UnBox](https://source.dot.net/#System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs,525) which shouldn't be invoked with a `null` object.

Should the type have the `class` constraint? 
Should this case be handled? 
An analyzer limitation?

**Comment by adityamandaleeka** [comment]
Triage: we should check if TFeature is a struct type and if it's null, just return default (don't try to unbox it).

**Comment by BrennanConroy** [comment]
> check if TFeature is a struct type and if it's null, just return default

We shouldn't return `default` for struct types, that would break user assumptions that the feature is present. Instead we should return null when `TFeature?` and throw an `InvalidOperationException` for `TFeature` when the result is null, instead of the current NRE.
