### ISSUE TITLE
Blazor Server Web Application performance issue

### ISSUE THREAD

**Issue by neozhu** [dotnet/aspnetcore#46950]
Dear dotnet/aspnetcore team,

I would like to raise an issue regarding the performance of Blazor Server Application in low bandwidth network conditions. Specifically, when accessing a Blazor Page, the response time is very slow and the latency is very high, especially when compared to ASP.NET Core Razor Pages.

It appears that Blazor Server Application has higher requirements for network bandwidth and lower latency than MVC or Razor Pages, possibly due to the large amount of data that needs to be exchanged via the WebSocket protocol to ensure synchronous page refreshing.

I would like to emphasize that this is not a bug, but rather an observation that I hope will be given attention and consideration for optimization.

Thank you for your time and attention.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Blazor Server application, by nature, rely on an active connection between the client and the server. That, as you would expect, would behave not ideally in a high latency connection situation.
Usually for these scenarios we would recommend using Blazor WebAssembly, which has its own pros and cons.
Going forward, however, we plan to bring together the best of both hosting models into what we call a single `Blazor United` model, which will hopefully address these concerns. You can learn more about our plans around Blazor United by looking at the [.NET 8 Roadmap](https://aka.ms/aspnet/roadmap) that we've published.
