### ISSUE TITLE
A very simple project to publish SignalR message to Microsoft.AspNet.SignalR.Redis

### ISSUE THREAD

**Issue by rayao** [dotnet/aspnetcore#46958]
@davidfowl 
If you still remember this: https://github.com/dotnet/aspnetcore/issues/46105, I can't comment the original issue now.
I created a project [here](https://github.com/rayao/Microsoft.AspNet.SignalR.MessagePublish) to publish message to AspNet Redis backplane.
It's very simple because what I need is quite limited, I'm not sure how useful it is to others.
And I have a concern about [this](https://github.com/rayao/Microsoft.AspNet.SignalR.MessagePublish/blob/19d26a5028ccf7b95e9f5a7e581255a0fc13d805/Microsoft.AspNet.SignalR.MessagePublish/Redis/RedisConnection.cs#L118), is it safe to skip restoring latestMessageId?
Thanks.

**Comment by mitchdenny** [comment]
@rayao - opened the original issue so you can post your links there so people can find it easily from the original issue.

**Comment by mitchdenny** [comment]
I'll close this issue :)

**Comment by rayao** [comment]
hi @mitchdenny the original issue is still locked to me, not sure what's wrong.
![image](https://user-images.githubusercontent.com/9673549/228151567-7a15d700-f5cf-4271-9253-1719c6124a88.png)
