### ISSUE TITLE
Events do not work in shadow dom

### ISSUE THREAD

**Issue by POnakS** [dotnet/aspnetcore#46961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Very simple databinding like
```
<input @bind="data" />

@code {
    string data { get; set; } = "";
}
```
does not work when element is embedded in shadow dom - this happens because "change" event is not composed (is swallowed by shadow host). Databinding does not work, and any attached handlers won't be triggered.

### Expected Behavior

Binding does not work, and event handlers are triggered

### Steps To Reproduce

1. Create html input tag, and bind it to property, like that:
    ```
    <input @bind="data" />

    @code {
        string data { get; set; } = "";
    }
    ```
2. Wrap it in shadow dom
    ```
        const shadow = element.attachShadow({mode: 'open'});
        shadow.appendChild(template.content.cloneNode(true));
    ```
3. Run

Expected outcome:
Binding works

Actual outcome:
Nothing happens

Here is example project:
https://github.com/POnakS/blazor_onchange

This example project uses component ```<app-element></app-element>``` twice - once inside shadow root, and once outside. Component in shadow root does not raise onchange events (it does raise on clicks though).

### .NET Version

7.0.103

### Anything else?

```
.NET SDK:
 Version:   7.0.103
 Commit:    276c71d299

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.103\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8
```

**Comment by POnakS** [comment]
This may be related to onchange being composed event, and a way in which blazor handles events:
https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

I.e. blazor app won't work inside closed dom (it will render, but won't handle any events).

**Comment by MackinnonBuck** [comment]
> This may be related to onchange being composed event, and a way in which blazor handles events

Blazor observes events by attaching event listeners to the `document` node. This does mean that any events dispatched from a shadow DOM with `composed: false` will not be observed. This behavior is expected.

**Comment by POnakS** [comment]
@MackinnonBuck are there any plans to support this in future, or it will stay like that?
