### ISSUE TITLE
Edge Enhanced Security mode is not easily detectable in Blazor

### ISSUE THREAD

**Issue by begerard** [dotnet/aspnetcore#46976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With the Edge Enhanced Security mode activated ("Security Added" flag visible) the performance is heavily impacted, as stated in https://github.com/dotnet/aspnetcore/issues/42641 (it have been closed by the bot). I have observed a +1200% performance hit precisely, both for CPU and memory intensive tasks. It make the applications painful to use, no matter how lightweight they are.

AFAIK, I don't have anything to programmatically detect it so I can't warn the user about this problem, I only have "performance" (or "It don't work"...) report if they use Edge and, for example, their IT team have activated the ESM with GPO. It took me a long time to diagnostic the problem initially as we have absolutely no clue about the source of this client slow down (nothing in the log). It is also very possible that some are evaluating Blazor and rejecting it for bad performance because of ESM, not because of the real (and much smaller) performance disadvantage against native JS apps. People have no way to know they are hit by this Edge mode, and we can't blindly disagree as Blazor do have a performance penalty.

I understand that the performance hit by itself could only be fixed by the Edge team, but I, as a Blazor developer, need the tools to deal with it, as it exists, it's out of beta, and Admins are activating it on their companies' computers.

Is their any API that I can use to detect it and display a message? Any log in the browser console so I can see the switch to DrumBrake? If not, I'd say we need both, and the API usage should be included in the default template.

I know there is a lot of pressing issues on Blazor but this one is very silly as one MS team is silently killing the work of another one as it can make Blazor apps unreliable or hard to sell.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This feedback will be actionable for the Edge team. We will try to reach out to them internally and let them know about it. But it would be more useful for you to report it through Edge feedback channels so that they get the direct feedback.
