### ISSUE TITLE
Blazor JS script section

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#46973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to point out that blazor does require JS for a lot of things, so it would be good to be able to add a JS script within a component, but in a special way, basically, you would have a `@scripts` section, and then all the scripts within that get compiled to a `.js` file that is included in the `wwwroot`. 
That way we don't have to create scripts outside of components and importing them in `index.html` while keeping the DOM/JS runtime happy.

### Describe the solution you'd like

Have a `@scripts` section, example:

```cs
@code {
async Task InvokeSomeJS()
{
    await JsRuntime.InvokeVoidAsync("registerElementHandler");
}
}

@scripts {
function registerElementHandler() {
    $("#elementId").doSomething();
}
}
```

### Additional context

I'm tired of working with JS files in wwwroot, either they get huge or there is a lot of files, I would love to be able to split a "master" script across components

**Comment by javiercn** [comment]
@ctigrisht thanks for contacting us.

There is a similar feature for this. You can read more about it [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-isolation-in-javascript-modules)

You can co-locate a JS ES6 module with your .razor file and we will automatically put it in the wwwroot folder.

We do not have at the moment plans for offering a special syntax within the razor language.
