### ISSUE TITLE
Allow elapsed time in HttpLogging

### ISSUE THREAD

**Issue by Martinn2** [dotnet/aspnetcore#46979]
I need a way to log time it took to execute endpoint using HttpLogging.  In production I need to log single line per request containing elapsed time.

In HttpLoggingOptions i would like to specify if elapse time should be logged. Like this: 
`builder.Services.AddHttpLogging(options =>
{
    options.LogElapsedTime = false;
});`

**Comment by Tratcher** [comment]
Elapsed time is available with the W3C logger.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/w3c-logger/?view=aspnetcore-7.0
The Hosting logs also provides elapsed time.
