### ISSUE TITLE
[Blazor] Action result for rendering a component

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#46990]
* Provide a mechanism to allow rendering a component from MVC and minimal APIs

**Comment by SteveSandersonMS** [comment]
Consider allowing the developer to provide the actual component instance like https://github.com/SteveSandersonMS/blazor-united/pull/12

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/47023
