### ISSUE TITLE
Consume wasm targets and metadata from the .NET Wasm SDK

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47001]
* We need to consume a target that does all the work to compute the list of files for the app.
  * During build
  * During publish
  * Independent of the gesture the user did (native compilation, linking enabled/disabled, etc.)
* We need to change the file names, paths, etc. to make them suitable to our layout.
* We need to add any information we want to include in mono-config.json
  * During build
  * During publish
* We need to implement our customizations for the deployment layout on top of the Webassembly provided extensibility points.

**Comment by mkArtakMSFT** [comment]
Closing as the Runtime team has handled this already.
