### ISSUE TITLE
@onkeydown:preventDefault doesn't work since SDK .NET 7.0.200

### ISSUE THREAD

**Issue by Bananamafia** [dotnet/aspnetcore#47016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Till the SDK .NET Version 7.0.103 i was able to add the `@onkeydown:preventDefault="true"` attribute to an element of type `<EditForm>` or Input. 
This enabled me to prevent submitting the form with my Enter key.

Since Version 7.0.200 and above this doesn't work anymore and Enter is submitting the form again.

### Expected Behavior

If I am understanding the [Docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#prevent-default-actions) right, I should be able to to prevent submitting my form by adding the `@onkeydown:preventDefault="true"` attribute.

If it was never the intention to prevent submitting a form, I apologize for this issue.

### .NET Version

> 7.0.200

**Comment by SteveSandersonMS** [comment]
Could you provide a complete repro? I tried the following with SDK 7.0.103, 7.0.201, and 8.0.0...preview and in all cases it works the same and correctly:

```razor
@* See https://github.com/dotnet/aspnetcore/issues/18449 *@
<h1 @onkeydown="@(() => {})">Hello, world!</h1>

Welcome to your new app.

<h2>HTML</h2>
<form onsubmit="alert(1)" @onkeydown:preventDefault="true">
    <input />
</form>

<h2>Components</h2>
<EditForm Model=@this OnSubmit="@(() => submitted = true)" @onkeydown:preventDefault="true">
    <InputText @bind-Value="@someString" />
</EditForm>

@if (submitted) {
    <h3>Submitted</h3>
}

@code {
    bool submitted;
    string someString = "hey";
}
```

The behavior, as expected, is that **all keystrokes on both textboxes are rejected** (i.e., pressing enter will not submit, nor will other characters be typed) since this is unconditionally preventing all keydown events.

**Comment by Bananamafia** [comment]
@SteveSandersonMS thank you for your reply. Your code example does exactly like you said: input aswell as submitting with enter doesn't have any affect.

However with the following code in SDK 7.0.201 I can make inputs as well as the `HandleValidSubmit` method gets invoked when I press enter.

`<EditForm Model="exampleModel" OnValidSubmit="HandleValidSubmit" @onkeydown:preventDefault="true">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText @bind-Value="exampleModel.Name" />

    <button type="submit">Submit</button>
</EditForm>

<div>@message</div>

@code {
    public string message { get; set; } = string.Empty;

    public SampleClass exampleModel { get; set; } = new SampleClass();

    public void HandleValidSubmit()
    {
        message = "Hello";
    }

    public class SampleClass
    {
        public string Name { get; set; } = string.Empty;
    }
}`

If required I can do additional testing later, but now I have to go to a business meeting.

**Comment by SteveSandersonMS** [comment]
@Bananamafia Your example code works identically for me on the 7.0.103 and 7.0.201 SDKs. In both cases:

 * If you add the workaround for https://github.com/dotnet/aspnetcore/issues/18449 as I did in my example, it prevents all keystrokes
 * If you don't, it doesn't prevent any keystrokes and "enter" will submit the form

If you're still able to reproduce a difference between 103 and 201 please let us know how. Thanks!

**Comment by Bananamafia** [comment]
@SteveSandersonMS you are right, it seems I oversaw something in my code, I apologize very much for your efforts.

The following is the abstracted code which worked for me... in both SDKs. 
Due to a current issue with the `@bind:after` I blindly commented out the part with `@onkeypress`, that's why I thought it would work in 7.0.103.  I am very sorry and thank you for your help!

```razor
<EditForm Model="@this" OnValidSubmit="@(() => ValueToShow = ValueToBind)" @onkeypress:preventDefault="preventDefault">
    <InputText @bind-Value="ValueToBind" @onkeypress="@(e => preventDefault = e.Key == "Enter")" />
    <button type="submit">submit</button>
</EditForm>

<div>@ValueToShow</div>

@code {
    public bool preventDefault { get; set; } = false;

    public string ValueToBind { get; set; } = string.Empty;
    public string ValueToShow { get; set; } = string.Empty;
}
```
