### ISSUE TITLE
Heartbeat.TimerLoop is consuming 5% of CPU usage in Thread.Sleep

### ISSUE THREAD

**Issue by yungjenhung** [dotnet/aspnetcore#47014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Microsoft.AspNetCore.Server.Kestrel.Core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop() is consuming >5% of CPU time in Thread.Sleep() from one of the workload. Are there any issues with the configuration? 

![image](https://user-images.githubusercontent.com/122310320/222609164-cb06732b-e558-4b66-bc8d-b076c0f25745.png)

### Expected Behavior

Can Heartbeat.TimerLoop() be configured? We anticipate decreased CPU usage from this function.

### Exceptions (if any)

N/A

### .NET Version

V 7.0.122.56804

**Comment by MarcPow** [comment]
Adding @mangod9 / @Maoni0

**Comment by mangod9** [comment]
Adding @kouvel. @yungjenhung, could you please clarify your scenario where you are seeing this behavior? Are you noticing this when the service is under load or when its idle?

**Comment by davidfowl** [comment]
This is inside of Kestrel itself. We should probably switch it back to a Timer now since thread pool blocking detection is better than it was. Still, I'm surprised we're seeing this thread which spends most of its time sleeping causing issues.

How many connections does this service have running?

**Comment by mangod9** [comment]
assume the heartbeat thread is sleeping for a constant time? Looking like the time is mostly spent in spinwaits in native code.

**Comment by davidfowl** [comment]
1 second

**Comment by yungjenhung** [comment]
@mangod9 It's under load. The process shows high resource usage and consumes 4 cores and 6GB memory during the peak hour. We’re investigating the root cause of this high CPU usage by collecting the dotnet traces.

**Comment by adityamandaleeka** [comment]
@yungjenhung The CPU time you're seeing in that tool is actually somewhat misleading, since it includes time that the thread was waiting as well.

For more info, see: https://github.com/dotnet/diagnostics/issues/3554#issuecomment-1355595312

You can use a tool like [PerfView](https://github.com/microsoft/perfview) to collect a CPU sampling trace which should give you a more accurate picture of the actual CPU time.

**Comment by yungjenhung** [comment]
@adityamandaleeka the issue is happening on Linux node. Do you have a recommended profiling tool for Linux?

**Comment by adityamandaleeka** [comment]
Here is a doc about how to collect a trace on Linux using perfcollect: https://github.com/dotnet/runtime/blob/main/docs/project/linux-performance-tracing.md#performance-tracing-on-linux

**Comment by davidfowl** [comment]
cc @noahfalk @brianrob

**Comment by noahfalk** [comment]
@adityamandaleeka has it right. I expect a CPU trace is going to show that this thread uses neglible CPU, < 0.1%. The 5% number that you see here is a measurement of wallclock time, not time on CPU. Every X milliseconds each thread in the process is stopped and a callstack is collected, regardless whether these threads are currently assigned a CPU core or not. If you have 20 threads in the app and one of them is spending all of its time in Thread.Sleep() that means at least 5% (1/20th) of all collected samples will be in Thread.Sleep().

**Comment by yungjenhung** [comment]
Thanks for the explanation. The CBL-Mariner 1.0 OS doesn't support `perfcollect` and `perf` well. We will move to Mariner 2.0 and revisit this issue again.
