### ISSUE TITLE
[Blazor] ComponentStatePersistenceManager needs to ensure the app has finished rendering

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47025]
We did this implicitly in the past because when rendering components from MVC/Razor pages, we would wait until they completely finished rendering and captured the HTML output.

Since we introduced some changes for how components rendered from within MVC/Razor pages, we broke the scenario for persisting state for async components.

The issue is that the state might get persisted before the component has reached quiescence and generated its final state.

Persisting the state is the last thing that should happen in the lifecycle of a Renderer, as it takes a "snapshot" of the world.

**Comment by SteveSandersonMS** [comment]
@javiercn and I discussed this a lot and one approach we could consider is moving the "persistence" operation into `HtmlRenderer` so it can access the underlying renderer directly. An example implementation is at https://github.com/dotnet/aspnetcore/commit/c345f0522256b6943a0ec9de61b73c4269d4ca8c (note: this commit was not merged into `main` and is provided here just for reference).

**Comment by javiercn** [comment]
Done when we implemented the feature for blazor web
