### ISSUE TITLE
App without a default CORS policy doesn't apply custom CORS policies

### ISSUE THREAD

**Issue by andrea60** [dotnet/aspnetcore#47022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When configuring an ASP NET 6 Web API app using only explicitly defined CORS policy (no default policy is defined as there are multiple services\policies in the same app and no one is "default"), the `RequireCors(MyPolicyName);` doesn't apply the specified CORS policy to all controllers.

I have made a small repro project where I followed the startup code recommended by the [official doc](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0#enable-cors-with-endpoint-routing). 
- Explicitly not configured a default policy.
- Defined a custom named policy.
- Mapped all controllers with `.MapControllers()` and applied a custom policy to them with `.RequireCors(MyAllowSpecificOrigins)`.

If I set the `DefaultPolicyName` on the `CorsOptions`, everything works as expected.

If I send an OPTIONS request to the server, I always get back a `405 Method Now Allowed`, not matter what CORS header I use.

When looking at the logs, it explicitly states `No CORS policy found for the specified request.` as if no CORS policy was in place.

### Expected Behavior

When calling .RequireCors() when mapping controllers, it should apply the specified CORS policy regardless of the default policy being set or not.

### Steps To Reproduce

1. Configure a custom CORS policy 
2. Do not configure any default policy for the app
3. MapControllers and enable the custom CORS policy using the `RequireCors` method
4. Start the app
5. Perform an OPTIONS request to a mapped controller, specifying the relevant CORS headers 

I made a reproduction repo which is made using the code example from the [official docs](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0#enable-cors-with-endpoint-routing):

https://github.com/andrea60/aspnet-cors-bug-repro

### .NET Version

6

### Anything else?

To give some context, I'm trying to do this because in the real world, I have an application that exposes two different services (HTTP and gRPC Web) which have two different CORS policies, so I can't really pick a default policy as there is no "default service" in that application.

Using the `[EnableCors]` attribute on each controller is not ideal as it's something someone can easily forget.

**Comment by captainsafia** [comment]
> If I send an OPTIONS request to the server, I always get back a 405 Method Now Allowed, not matter what CORS header I use.

Support for the OPTIONS preflight request isn't supported in .NET 6 when you use the`RequireCors` extension method exclusively. It is supported in .NET 7 if you are able to try it there.
