### ISSUE TITLE
Blazor : nested @for loop increment the counter incorrectly

### ISSUE THREAD

**Issue by indieza** [dotnet/aspnetcore#47034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have nested FOR loop in a .razor component

![image](https://user-images.githubusercontent.com/11813571/222892359-5bba614d-de45-42b1-9d0a-fae3516ff0d4.png)

when I receive all Users from the back-end and update the current component state, somehow the "row" value becomes 1, not 0.

API Call

![image](https://user-images.githubusercontent.com/11813571/222893809-223ddc60-7e59-4e66-9aba-9d9538cef39d.png)

Component code

![image](https://user-images.githubusercontent.com/11813571/222893829-c40802a6-647e-4d5b-86b5-4cb4e45100e5.png)

Row result

![image](https://user-images.githubusercontent.com/11813571/222893571-61b4c44c-fb06-4327-9098-53569e4b1d59.png)

### Expected Behavior

I expect when we are in the second loop, the row value to be 0, not 1

### Exceptions (if any)

No any exceptions such as IndexOutOfRange

### .NET Version

latest

### Anything else?

I found very similar issue to mine but I guess the bug is still not resolved
[Issue/Bug](https://github.com/dotnet/aspnetcore/issues/16809)
[Verified comment, but still not working](https://github.com/dotnet/aspnetcore/issues/16860#issuecomment-550354874)

**Comment by javiercn** [comment]
@indieza thanks for contacting us.

This is likely not a bug, but a well-known by design behavior. What likely is happening in your code is an artifact of how Blazor compiles the code. We cover this in our docs [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#child-content-render-fragments)

See the fragment:
> Due to the way that Blazor renders child content, rendering components inside a [for](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/for) loop requires a local index variable if the incrementing loop variable is used in the RenderFragmentChild component's content. The following example can be added to the preceding RenderFragmentParent component:

You need to declare a local variable inside the loop braces and use that instead of referring to the loop variable directly. The same behavior happens in plain C# and that's why `foreach` is recommended to iterate over collections as it does not present that issue.

**Comment by indieza** [comment]
@javiercn hey, I got the point, but not I receive index out of range exception and it is not regariding to the issue. Thaks for the support I will close it

**Comment by indieza** [comment]
hello, I guss it is still regarding to the issue, because when I simulate the same situation in a simple console application, I didn't get the IndexOutOfRange Exception

As you can see here, we have 2 elements in the List

![image](https://user-images.githubusercontent.com/11813571/222895341-5b12aa53-a311-4935-80f9-26f96f34880c.png)

I update the Razor component with this

![image](https://user-images.githubusercontent.com/11813571/222895366-d7e8c858-c854-4f87-9075-cb74c4f3c3be.png)

**Comment by indieza** [comment]
Okay, the same think 

> Due to the way that Blazor renders child content, rendering components inside a [for](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/for) loop requires a local index variable if the incrementing loop variable is used in the RenderFragmentChild component's content. The following example can be added to the preceding RenderFragmentParent component:

should be made also into the second for loop, now it works and definatly will close the isssue 😄 , I apply the solution image
![image](https://user-images.githubusercontent.com/11813571/222895838-1c3aed67-fb08-40e4-9818-53d522228e85.png)
