### ISSUE TITLE
[Proposal] Leverage Sqlite for Desktop https developer-certificates.

### ISSUE THREAD

**Issue by djgalvan** [dotnet/aspnetcore#47042]
## Summary

Leveraging Sqlite, trusting developer certificates on Linux/Unix Desktop Environments may be accomplished through the User's Public Key Infrastructure (PKI) Directories. Using a database will increase the data integrity and security of these certificates.

Related #32842 

## Motivation and goals

The current state of Linux/Unix Desktop Environment certificates has fallen behind. NET 6.0 created the certificate and did not trust it. NET 7.0 seems to have dropped support for HTTPS altogether.

## In scope

1. Bare (non-containerized) Chromium-based Browsers (Chromium, Google Chrome, Microsoft Edge, etc.) ~/.pki/nssdb
2. Bare (non-containerized) Firefox (Profile1, Profile2, Profile3, etc.) ~/.mozilla/firefox/$ProfileDirectory

## Out of scope

1. NA

## Risks / Unknowns

1. As far as Desktop Environments go, there shouldn't be any major issues, at least not that I can think of. Preserving the initial certificate stored in ~/.{dotnet,aspnet}/**/*.pfx should maintain other uses of the certificate. The regeneration/deletion of the certificate can be accomplished using the usual `dotnet https` commands.
2. Browsers/Utilities could drop support for PKI database. 

## Examples

The `dotnet https` command is a CLI utility. Utilizing the PKI databases would fix many issues revolving around `dotnet https --trust` usage.

[Experimentation](https://github.com/djgalvan/CertificateManager.git)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
