### ISSUE TITLE
ProblemHttpResult should use custom defaults

### ISSUE THREAD

**Issue by dnperfors** [dotnet/aspnetcore#47045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In my minimal endpoint, I use the `TypedResults.Problem()` method to create a `ProblemDetail`. This way I can handle endpoint specific exception in a readable way.
We have some conventions that we apply to ProblemDetails, for example we want to have a generic `Detail` message and we don't want to show the `Type` URL. The only way to do this in the endpoint is by doing:
```csharp
var problem = TypedResults.Problem(detail: "Some internal problem, please contact us.");
problem.Type = null;
return problem;
```

This is annoying, since when I just throw an exception and let the `ExceptionHandlerMiddleware` handle this using the `IProblemDetailsService` I can easily override these properties in a single place (`AddProblemDetails(options => options.CustomizeProblemDetails = ...)`).

### Describe the solution you'd like

I would like to see the `IProblemDetailsService` or the `ProblemDetailsOptions` being used by the `ProblemHttpResult` so that I can override the defaults that are set by the `ProblemHttpResult` constructor (or technically by the `ProblemDetailsDefaults.Apply()` method).

### Additional context

There are probably some work arounds, including:
- a custom `Problem()` method
- an endpoint filter that modifies the result, although this isn't as straightforward since the return type could be anything.

**Comment by captainsafia** [comment]
Triage: Thanks for filing this issue, @dnperfors! We don't support this at the moment but think it would be something worthwhile to explore. Would you be interested in submitting a PR?

**Comment by dnperfors** [comment]
> Triage: Thanks for filing this issue, @dnperfors! We don't support this at the moment but think it would be something worthwhile to explore. Would you be interested in submitting a PR?

Yes, I think I can submit a PR for this.
