### ISSUE TITLE
IHttpContextAccessor, HttpContext and other related classes not working as expected.

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnetcore#47041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently trying to get the currently logged in user by either email or username via the HttpContext class or IHttpContextAccessor. I've also tried through the User class within the ControllerBase within the web api project to get the email or username of the logged in user to no avail.

I've noticed that HttpContext was previously a static class where now it is an abstract class.

Thanks

### Expected Behavior

To be able to use HttpContext, IHttpContextAccesor or User object within the controller base to get the username or email address of the currently logged in user.

### Steps To Reproduce

Make a basic ASP.NET Identity Login method within a web api project. 

Create a method which can get the currently logged in user.

### .NET Version

7.0.3 (7.0.200)

**Comment by davidfowl** [comment]
@chris-briddock can you make a repro project, put it on github and share instructions on exactly what is not working properly?

**Comment by chris-briddock** [comment]
@davidfowl I will let you know when I have reproduced this.
Would you have to add claims to the user for the username to be within the ClaimsPrinciple object? It could be something simple like that, and user error in fact, just want to rule that out.

Thanks
