### ISSUE TITLE
Global exception handling

### ISSUE THREAD

**Issue by uacaman** [dotnet/aspnetcore#47052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

From the IErrorBoundary :

```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.AspNetCore.Components;

// Purpose of this interface, instead of just using ErrorBoundaryBase directly:
//
// [1] It keeps clear what is fundamental to an error boundary from the Renderer's perspective.
//     Anything more specific than this is just a useful pattern inside ErrorBoundaryBase.
// [2] It improves linkability. If an application isn't using error boundaries, then all of
//     ErrorBoundaryBase and its dependencies can be linked out, leaving only this interface.
//
// If we wanted, we could make this public, but it could lead to common antipatterns such as
// routinely marking all components as error boundaries (e.g., in a common base class) in an
// attempt to create "On Error Resume Next"-type behaviors.

internal interface IErrorBoundary
{
    void HandleException(Exception error);
}
```
This interface should be public, I should be able to determine what works and what does not work for my project. 

Only someone who works on the project can say what works for the team. I pretty sure is best to having  "On Error Resume Next"-type behaviors as a last resort instead of showing a reload button because some new developer  forgot to add a try catch 

### Describe the solution you'd like

make the IErrorBoundary public 

### Additional context

it is a easy fix

**Comment by javiercn** [comment]
@uacaman thanks for contacting us.

There are other ways to do this if you want. Like using an error boundary component at the root of your app. 
This is not something we plan to do.

**Comment by uacaman** [comment]
It does not have to be at the root, right now, error boundary  is not flexible enough, for example you can't recover from a error without forcing a re render. The class ErrorBoundaryBase always call StateHasChanged, since there is no way to override this behavior it is not possible to use error boundary to actually recover from the error. Right now error boundary can be used to log and stop flow of the user UI and notify anything like a logger about the error. If is not possible to to make error boundary more flexible, at least change it is name to something like ErrorBoundaryLogger.
