### ISSUE TITLE
AJAX progress not triggering when using file uploader component in Blazor WebAssembly hosted on IIS

### ISSUE THREAD

**Issue by mohanrajsf3477** [dotnet/aspnetcore#47053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using a file uploader component in Blazor WebAssembly and I've implemented the upload action in JavaScript. The file upload works fine when I run the sample locally, but when I host the sample in IIS, the ajax Upload Progress event function doesn't trigger and I don't get the progress bar. I've checked the console and there are no errors.

Here's the code snippet I'm using in my JavaScript:
// JavaScript code for file upload
function uploadFile() {
  var xhr = new XMLHttpRequest();
  xhr.open("POST", "/api/upload", true);

  xhr.upload.onprogress = function(event) {
    if (event.lengthComputable) {
      var percentComplete = (event.loaded / event.total) * 100;
      console.log(percentComplete + '% uploaded');
    }
  };

  xhr.onload = function() {
    if (this.status === 200) {
      console.log('Upload completed successfully');
    }
    else {
      console.log('Upload failed');
    }
  };

  xhr.send(formData);
}
I've also checked my server configuration and made sure that the maximum allowed file size is greater than the file I'm trying to upload.

What could be causing the onUploadProgress function to not trigger when the sample is hosted in IIS?

### Expected Behavior

The expected behavior is that the onUploadProgress event should be triggered when using the file uploader component in Blazor WebAssembly and hosting the sample in IIS. This should allow for the progress bar to update during the file upload process.

### Steps To Reproduce

- Use the file uploader component in a Blazor WebAssembly project.
- Host the sample in IIS.
- Attempt to upload a file.
- Observe that the onUploadProgress event is not triggered and the progress bar does not update. This issue only occurs when hosting the sample in IIS, while it works fine when running the sample locally.

**Comment by javiercn** [comment]
@mohanrajsf3477 thanks for contacting us.

* Does your issue reproduce in an app where Blazor is not involved?
* Does it reproduce across different browsers?

**Comment by mohanrajsf3477** [comment]
Hi @javiercn ,
Actually, I checked with a Blazor server app and found that the issue was not reproduced. This issue only occurs on Blazor wasm, and we can reproduce it in other browsers such as Firefox and Microsoft Edge.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be something specific to Blazor. We recommend posting this question to [StackOverflow](https://stackoverflow.com) forum to get some help from there. Also, it looks like you may have some issue in your JavaScript code. Here is a relevant thread to help you get started: https://stackoverflow.com/questions/43345271/xmlhttprequest-event-onprogress-is-being-fired-only-when-file-has-finished-uploa
