### ISSUE TITLE
HelixPlatform_QuickListenerIsSupported fails on win11.arm64 in Helix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#47065]
The following test has been failing since Thursday on the win11.arm64 helix queue.

https://github.com/dotnet/aspnetcore/blob/46a3d2ba55e6f6d9accc3ede92f9231d27a4c10b/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs#L23-L37

It last passed on Thu at 6AM in [this build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=190852).

Then it started failing on Thu at 6PM in [this build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=191741).

```
Error message
QuicListener.IsSupported should be true.
Expected: True
Actual:   False


Stack trace
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.HelixPlatform_QuickListenerIsSupported() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Looking through the changes that went into the repo in between those 2 builds, nothing jumps out as something that could have broken this. So maybe the Helix win11 arm64 machines changed?

cc @JamesNK @Tratcher

**Comment by eerhardt** [comment]
> Looking through the changes that went into the repo in between those 2 builds, nothing jumps out as something that could have broken this.

Looking again, I see that the dotnet/runtime was updated in between those 2 builds.

@wfurt @ManickaP - I see https://github.com/dotnet/runtime/pull/81742 is in the commit change list of the new dotnet/runtime. I also see https://github.com/dotnet/runtime/pull/82780 disabled a QUIC test on arm.

Should I disable this test? Is this a known issue in Quic?

**Comment by wfurt** [comment]
https://github.com/dotnet/runtime/pull/81742 missed arm binary @eerhardt. It should be fixed once https://github.com/dotnet/msquic/pull/131 floats to runtime (and eventually ASP.NET)
So probably yes, disable the test for now.

**Comment by JamesNK** [comment]
Add a skip for that queue and link to this issue to track

**Comment by JamesNK** [comment]
This looks like it was fixed with https://github.com/dotnet/aspnetcore/pull/50279 but wasn't closed. @mitchdenny did you intent to close this?
