### ISSUE TITLE
Add support for PEM format SSL certificates

### ISSUE THREAD

**Issue by Praveen-Rai** [dotnet/aspnetcore#4706]
Presently, Kestrel configuration supports only the PKCS12 ( *.pfx ) format certificates. Whereas, PEM seems to be much more widely used format ( Public and Private keys are stored in two different files ) and most often one needs to convert the certificate format using OpenSSL before they can be used with Kestrel. 

Referring to : https://github.com/dotnet/corefx/issues/32367#issuecomment-423671246
It looks like that the core already has api's to load public and private keys from two different files. Can we leverage them and add the support for the PEM certificate formats ?

**Comment by Praveen-Rai** [comment]
@Tratcher Now that we have .Net Core 3.0 preview 1 released, can you please re-look into this issue ?

**Comment by Tratcher** [comment]
This is on our backlog, we don't plan to investigate it for 3.0. It's marked as up-for-grabs as a likely candidate for community involvement.

**Comment by Tratcher** [comment]
That would be almost the same work and is triaged with the same result. We'll review anything the community comes up with here but don't plan to investigate it ourselves right now.

**Comment by ianpowell2017** [comment]
Any plans for this available in .net core 2.2 and below?

**Comment by Tratcher** [comment]
> Any plans for this available in .net core 2.2 and below?

No, as a rule we do not backport new features or API. We haven't even scheduled this for a future release yet. That said, you should already be able to write app code for this in 3.0. If somebody works out a sample we'd be happy to add it to the docs.

**Comment by brzezinol** [comment]
I have a question about using pem as is.
Today letsencrypt renew certificate for every 3 months.
So I need another schedule for convert pem file to pfx file and copy to net.core app.
Do yo know any other way to use let'sencrypt with net.core ?

**Comment by Brymastr** [comment]
@brzezinol 
My current workaround is to use `openssl` to convert the pem from letsencrypt to a pfx as a --deploy-hook in certbot. Example:

```console
$ sudo certbot certonly \
    -d <DOMAIN NAME> \
    --deploy-hook cert-renew-hook
```

Where `cert-renew-hook` is something like:
```bash
#!/usr/bin/env bash
openssl pkcs12 \
  -inkey /path/to/privkey.pem \
  -in /path/to/cert.pem \
  -export -out /etc/letsencrypt/live/<DOMAIN NAME>/cert_pfx.pfx \
  -passout pass:
```

This may be a bit naive as pfx requires a password but this example sets a blank string.

**Comment by rynowak** [comment]
@Tratcher  - based on where we are now - what's the right fix for this look like? Is this something we'd want an API from CoreFx for? An API in ASP.NET? It seems like the approach that's obvious is a way to load a `.pem` as an `X509Certificate`.

**Comment by qJake** [comment]
Would really like to see support for this - since Let's Encrypt is quickly gaining traction, it is becoming increasingly common to have a `fullchain.pem` file that looks like this:

```
-----BEGIN CERTIFICATE-----
[Base64 of Cert]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[Base64 of Cert]
-----END CERTIFICATE-----
```

And a `privkey.pem` that looks like this:

````
-----BEGIN PRIVATE KEY-----
[Base64 of Private Key]
-----END PRIVATE KEY-----
```

Kestrel should support these formats natively, especially if it just means concatenating the files or something trivial like that.

**Comment by rynowak** [comment]
Some updates on the status here. 

---

dotnet/runtime is tracking an issue for .NET 5.0 to expose a simple API for creating a cert from these file kinds - https://github.com/dotnet/runtime/issues/31944 Feedback is definitely encouraged from the community on whether that meets the goals.

This would allow you to pass in a certificate to the overloads of `UseHttps` that accept one. One possible problem is what to do with `UseHttps(string)`, and whether it can support this format (probably, unless you have a separate key file). `UseHttps(string, string)` already exists and it does something different.

---

Additionally, we want to make it possible to pass in a certificate via configuration. Straw man proposal from @Tratcher 

```js
"Kestrel": {
    "Endpoints": {
      "HttpsPemCertFile": {
        "Url": "https://localhost:5002",
        "Certificate": {
          "Path": "<path to .pem file>",
          "PemKey": "<path to key file>"
         }
      },
}
```

`Path` would be able to accept a `.pfx` or a `.pem`. `PemKey` would specifically accept a private key - via file. 

Personal note: I like the better the idea of `KeyPath` or something like that as a configuration key since that will reflect the fact that it's a file, not an inline value.
----

**Comment by Tratcher** [comment]
> One possible problem is what to do with `UseHttps(string)`

If you're already doing code based config then you can call the new CreateFromPemFile API and pass in the cert. I'm not concerned about one extra line.

**Comment by rynowak** [comment]
> > One possible problem is what to do with `UseHttps(string)`
> 
> If you're already doing code based config then you can call the new CreateFromPemFile API and pass in the cert. I'm not concerned about one extra line.

Right, but we still have to think about how `UseHttps(string)` will behave because lots of folks will try that and expect it to do what they want.

**Comment by qJake** [comment]
I'd like to think people are smarter than passing actual certificate data into a [parameter called `fileName`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.kestrelserveroptionshttpsextensions.usehttps?view=aspnetcore-1.1#Microsoft_AspNetCore_Hosting_KestrelServerOptionsHttpsExtensions_UseHttps_Microsoft_AspNetCore_Server_Kestrel_KestrelServerOptions_System_String_), but hey, maybe I give people too much credit. 😉

**Comment by rynowak** [comment]
> I'd like to think people are smarter than passing actual certificate data into a [parameter called `fileName`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.kestrelserveroptionshttpsextensions.usehttps?view=aspnetcore-1.1#Microsoft_AspNetCore_Hosting_KestrelServerOptionsHttpsExtensions_UseHttps_Microsoft_AspNetCore_Server_Kestrel_KestrelServerOptions_System_String_), but hey, maybe I give people too much credit. 😉

I meant for people passing the filePath of ` .pem` certificate rather than a `.pfx` certificate.

**Comment by qJake** [comment]
Ah, hmm... would it be too difficult to auto-detect the file type and use it (given some list of known supported types), or create an overload that takes an enum that specifies the type (e.g. `UseHttps("mycert.pem", X509CertificateType.Pem` or similar)?

**Comment by codyja** [comment]
Any ideas on when a solution would happen here? PEM cert reads would be ideal. Thank you!

**Comment by davidfowl** [comment]
Moving this out of backlog into 5.0.0 

cc @anurse @shirhatti

**Comment by davidfowl** [comment]
Dependent on https://github.com/dotnet/runtime/issues/31944

**Comment by javiercn** [comment]
This is now merged into master and will be available in preview8
