### ISSUE TITLE
IExceptionHandlerFeature is not available in CustomizeProblemDetails when using UseDeveloperExceptionPage

### ISSUE THREAD

**Issue by bjornen77** [dotnet/aspnetcore#47060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The IExceptionHandlerFeature is not available in CustomizeProblemDetails when using "UseDeveloperExceptionPage". It is, however, available when using "UseExceptionHandler()". Is there a reason for this? It would be good to be able to customize the problem details also when using the DeveloperExceptionPage.

### Expected Behavior

The IExceptionHandlerFeature is available when using DeveloperExceptionPage

### Steps To Reproduce
Try the "/" endpoint from swagger.

```
using Microsoft.AspNetCore.Diagnostics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddProblemDetails(configure =>
    configure.CustomizeProblemDetails = (context) =>
    {
        if (context.HttpContext.Features.Get<IExceptionHandlerFeature>() is IExceptionHandlerFeature exceptionHandlerFeature)
        {
            Console.WriteLine("This will not print when using UseDeveloperExceptionPage()");
        }
    }
);

var app = builder.Build();

app.UseDeveloperExceptionPage();

app.UseSwagger();
app.UseSwaggerUI();

app.MapGet("/", () =>
{
    throw new Exception();
});

app.Run();
```

### .NET Version

7.0.201

**Comment by captainsafia** [comment]
> The IExceptionHandlerFeature is not available in CustomizeProblemDetails when using "UseDeveloperExceptionPage". It is, however, available when using "UseExceptionHandler()". Is there a reason for this? 

The exception handling middleware has the potential to re-execute the middleware pipeline so the `IExceptionHandlerFeature` is used to store details that need to be persisted across re-executions. We could definitely set it in the developer-exception page but there isn't a strong technically requirement to.

**Question:** Is there a particular reason you are wanting to use the `IExceptionHandlerFeature`?

The only info that you can get in the `IExceptionHandlerFeature` that isn't already in the `ProblemDetailsContext` is the original `Exception` that you access via `IExceptionHandlerFeature.Error`.

**Comment by bjornen77** [comment]
I want to be able to customize the problem details extensions property with information from the original exception. The reason it that a receiving application always should be able read the customized information in the problem details response.

I know that i can create a custom exeption handler also for development purposes, but it would be nice to use the built in one. Also, it would also be more consistent(when CustomizeProblemDetails is called in both cases)

I think that it might be easy to set the IExceptionHandlerFeature in the developer-exception-page. I could try to make a PR for it if wanted.

**Comment by captainsafia** [comment]
@bjornen77 Thanks! A PR is definitely welcome. It helps to reuse the existing feature here.
