### ISSUE TITLE
DbContextHealthCheck does not handle exceptions

### ISSUE THREAD

**Issue by matthewethomas** [dotnet/aspnetcore#47074]
in DBContextHealthCheck, if the testQuery func throws an exception, there will be an error in generating the overall health report.

Please consider wrapping this if statement in a try/catch block, and returning unhealthy if an exception is thrown. https://github.com/dotnet/aspnetcore/blob/2b04b019f81acfb6ed909f7634746170381c0150/src/Middleware/HealthChecks.EntityFrameworkCore/src/DbContextHealthCheck.cs#L35-L38

**Comment by captainsafia** [comment]
Triage: Thanks for the issue, @matthewethomas! We believe that there is a legitimate bug here and would welcome a PR form you if you are up for it.

The ideal approach would be to add a `try/catch` here and return an Unhealthy status code in the exception handling.

Alternatively, you can configure CustomTestQuery and add `try/catch` within your query function.
