### ISSUE TITLE
Components E2E consistently timing out in 7.0 and 6.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#47080]
7.0: https://dev.azure.com/dnceng-public/public/_build/results?buildId=195061&view=results
6.0: https://dev.azure.com/dnceng-public/public/_build/results?buildId=194827&view=results

CC @MackinnonBuck @javiercn @captainsafia

**Comment by MackinnonBuck** [comment]
This was fixed by #47082 and #47084
