### ISSUE TITLE
InputSelect with empty option doesn't validate int

### ISSUE THREAD

**Issue by giarico** [dotnet/aspnetcore#47088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i submit the form, if I don't change the value of the select, I have no validation error.
If I change value and go back to the empty choice, the error is shown.

```
public class MyModel
{
    [Required]
    public int MyProperty { get; set; }
}
```

```
<EditForm Model="model" OnValidSubmit="HandleValidSubmit">

    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputSelect @bind-Value="model.MyProperty">
        <option></option>
        <option value="1">1</option>
        <option value="2">2</option>
    </InputSelect>

    <button type="submit">Save</button>
</EditForm>

@code 
{
    MyModel model = new();

    void HandleValidSubmit()
    {
        
    }
}
```

This is when you click insert without changing option
![first](https://user-images.githubusercontent.com/22771799/223651822-111c9396-382e-4683-892c-d9167b98bf1d.jpg)

This is when you click insert changing option and going back to the empty choice
![second](https://user-images.githubusercontent.com/22771799/223651861-28f3cb24-6600-40f1-97af-2d536590aa21.jpg)

### Expected Behavior

The validation should trigger also when I don't modify the choice

### .NET Version

7

**Comment by javiercn** [comment]
@giarico thanks for contacting us.

Validation works in terms of the value in C# and not the value in the form. Since an int is a value type, it always has a value and hence `Required` validation always passes. You need to use `int?` to model that behavior, otherwise the absence of a value can't be distinguished from a valid value.
