### ISSUE TITLE
@onclick not invoked on <a> tags when in disabled fieldset

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#47090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There was a breaking change after Chrome upgrade to v111.0.5563.65

`@onclick` directive on `fieldset[disabled] a` tags does not work anymore:

```razor
<fieldset disabled>
   <a @onclick="Click">click</a>
</fieldset>
```

This could be a bug/feature in Chromium, but I report it here just to be sure.

### Expected Behavior

I haven't found any documentation in HTML/CSS specs, that `<a>` tags should be affected by `<fieldset disabled>`.

I expect that @onclick would work just like regular onclick attribute.

### Steps To Reproduce

1. Open chrome (windows 11)
2. Make sure you have lastest version (111.0.5563.65 as of 2023-3-8)
3. Go to REPL: https://blazorrepl.telerik.com/mHYHYWlY46DrXgy652
4. Click the `@onclick="Click" ` anchor - nothing should happend, which is a bug

### .NET Version

7.0.103

**Comment by javiercn** [comment]
@Liero thanks for contacting us.

Very likely this is an HTML behavior and not Blazor is causing. 

Does it work on an HTML document that doesn't involve Blazor where you register an `onclick` handler?

**Comment by Liero** [comment]
@javiercn:
Here is pure HTML/JS demo: https://jsfiddle.net/vxr45h3c/

As you can see, 'onclick' attribute works, but `document.AddEventListener` doesn't, because the fieldset probably stops propagation.

I wonder, whether this is expected behavior. If yes, this is quite problematic, because blazor relies on events being propagated to the root element (or document), doesn't it?

**Comment by javiercn** [comment]
It's not trivial because it can be potentially breaking in many subtle ways.

**Comment by Liero** [comment]
Maybe there could be API, which I would use to register an html element - the fieldset in this case - on which blazor would listen to events.

**Comment by javiercn** [comment]
@Liero we wouldn't do something like that, it would be an approach "too unique" to Blazor.

I suspect at best we would remove `event delegation` in favor of registering the event directly on the element and we would do it progressively through various releases, making it opt-in, opt-out, and then deprecating it.

But so far, this is not something that we've decided to tackle as we've only seen a few edge cases where it potentially matters, and other frontend frameworks use the same approach as us, so it's not in general a big issue for people.

**Comment by SteveSandersonMS** [comment]
Thanks @Liero for the report and the really clear repro cases.

The exact same issue occurs with other frameworks. For example, here's React's built-in `onClick` attributes being affected in the same way: https://jsfiddle.net/ry9t4hzu/

It would be great to know what the underlying Chromium change was that caused this, and whether they would count it as an unintentional bug that they will fix. But as @javiercn says, I'm not sure we'd try to work around this in a unique way, since it's not really Blazor-specific and the new rules apply to other frameworks too.

**Comment by MackinnonBuck** [comment]
Closing this out since it doesn't look like there's any action we'll be taking in the framework.
