### ISSUE TITLE
[Blazor] Using event callbacks in backing classes

### ISSUE THREAD

**Issue by LisavB** [dotnet/aspnetcore#47098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

(Apologies if this question is already covered, I have searched but I am sure I could have missed something obvious.)

We are developing a Blazor hosted web assembly application and some of our razor pages have become so large that we are creating backing services to manage their state. These services are singletons that will be injected into a razor page or component. We were wondering if we should use EventCallback to notify the razor pages when the state in the service has updated. However, all of the documentation I could find explicitly discussed the EventCallbacks being used when a child component needs a parent components method to be executed.

We have considered using the standard EventHandler instead of an EventCallback, however we would prefer to use the EventCallback if possible due to the benefits that they provide when working with razor pages.

### Describe the solution you'd like

We would like to know if it goes against best practices to use EventCallback to notify a razor component or page of changes in a service that is injected into the component or page.

**Comment by javiercn** [comment]
@LisavB thanks for contacting us.

The main benefit of an `EventCallback` over a plain delegate is that if the target of the delegate implements `IHandleEvent` we will call `HandleEventAsync` which, in the common case, with `ComponentBase` will result in between 1 or 2 renders depending on whether the handler completes synchronously or asynchronously.

It is hard to give guidance without a concrete scenario, but I would say at least that if your communication were between types that are not components, there is not value in using `EventCallback`.

In general, we are not prescriptive about these matters, as long as you understand the impact and the benefits/drawbacks that you get, and decide it works for you/your team, that is enough.

**Comment by LisavB** [comment]
Thanks for the answer @javiercn, I'll take this back to my team to discuss.
