### ISSUE TITLE
APP_POOL_ID environmental variable is null before app.Run() runs for some time.

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/aspnetcore#47093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor application which runs under IIS on Windows Server 2019 and reads APP_POOL_ID environmental variable at start to figure out what pool is it running under.
On my local machine it reads it every time. but on one server it does not. The  `Environment.GetEnvironmentVariable("APP_POOL_ID", EnvironmentVariableTarget.Process)` call returns proper value only within Blazor application or after few seconds after `app.Run()` was called, but not within Main() method. If it tries to read the variable before `app.Run()` is called, it will be always null no matter how much time waits.
It does not matter whether app is self contained or not.
Furthermore, app was reading the value correctly not so long ago but it stopped recently.
It's really odd as this is an environmental variable tied to process that should exist before .NET app even runs (set by IIS).
Any idea why it might be happening?

### Expected Behavior

`Environment.GetEnvironmentVariable("APP_POOL_ID", EnvironmentVariableTarget.Process)` returns proper value always.

### Steps To Reproduce

Call `Environment.GetEnvironmentVariable("APP_POOL_ID", EnvironmentVariableTarget.Process)` before `app.Run()`, but I happens only on a single Windows Server, not on others AFAIK.

### .NET Version

7.0.201 (dev) 7.0.x (server)

**Comment by davidfowl** [comment]
> On my local machine it reads it every time. but on one server it does not. 

How does your local machine differ from your server environment?

**Comment by MihaMarkic** [comment]
Hi David,

Hard to say as I have only an indirect contact with problematic server. On my workstation (Windows 10, VS2022 17.5.1) and on my local Windows Server 2019 Standard build 17763 running within Hyper-V it works. Problematic server is also Windows Server 2019 build 17763 hosted under VMWare something I think. My server has .NET 7.0.2 - Windows Server Hosting, Runtime, problematic had 7.0.2 and now has 7.0.3. (both not working)

Do you have any suggestion on what to look for in first place?

I'm also attaching my test application
[TestPoolId.zip](https://github.com/dotnet/aspnetcore/files/10932197/TestPoolId.zip)

If you check program.cs, I'm retrieving APP_POOL_ID before app.Run() (it's always null) and after app.Run() - it's not null when I wait enough time, like 5_000_000 spins, not sure how many) while the value retrieved in Index.razor is always valid.

**Comment by adityamandaleeka** [comment]
That environment variable should be set by IIS and it's not something we control. It's unusual that it doesn't appear on just one server. Are there issues setting and reading other environment variables on that machine?

**Comment by MihaMarkic** [comment]
> That environment variable should be set by IIS and it's not something we control. It's unusual that it doesn't appear on just one server.

Agree on both counts. Even more odd is that once app.Run() is called, the variable appears.

> Are there issues setting and reading other environment variables on that machine?

Will check.

**Comment by adityamandaleeka** [comment]
Hmm, I don't know if that's possible... normally a process's env block can't be modified by another process after creation (setting aside debuggers and such). That said, I haven't looked into how the preload setting actually works, so maybe I'm missing something.

cc @John-Hart @ning51 in case this rings a bell

**Comment by MihaMarkic** [comment]
From what I'm seeing, yes. If preload is turned off, it works as expected - environmental variable APP_POOL_ID is available from application start.

**Comment by adityamandaleeka** [comment]
I see, thanks for confirming that. Is that a suitable workaround for you? I don't think there's anything we can do here to affect this behavior.

**Comment by MihaMarkic** [comment]
Probably not, but I still wonder how do we get to APP_POOL_ID environmental variable when preload is turned on (after app.Run() that is). Anyway, feel free to close the issue. Do you know where to post "why is IIS/w3wp.exe not settings APP_POOL_ID environmental variable when preload is turned on" question?

**Comment by adityamandaleeka** [comment]
@MihaMarkic You can ask that IIS question at https://support.microsoft.com/
