### ISSUE TITLE
Receiving r.arrayBuffer is not a function with InputFile component on iOS 12.5.6

### ISSUE THREAD

**Issue by ramseytm** [dotnet/aspnetcore#47116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have an application built on Blazor Web Assembly .NET 6.0.406. We are seeing an exception thrown on specific iOS devices (iOS 12.5.6 and a few iOS13+ ipad devices) when attempting to utilize the `InputFile` component to upload images within our application. When attempting to handle the `OnInputFileChangeAsync` on the `InputFile` component we receive the following error from blazor web assembly when reading from the file stream provided by the `IBrowserFile.OpenReadStream`:

An exception of type Microsoft.JSInterop.JSException was thrown.
Message: r.arrayBuffer is not a function. (In 'r.arrayBuffer()', 'r.arrayBuffer' is undefined)

### Expected Behavior

The stream should be successfully ready as demonstrated on other devices. We've determined it works on iOS16+ devices.

### Steps To Reproduce

Basic implementation that demonstrates the issue:

```c#
    private async Task OnInputFileChangeAsync(InputFileChangeEventArgs e)
    {
        var files = e.GetMultipleFiles(MaxAllowedFiles);
        foreach (var file in files)
        {
            var buffer = new byte[file.Size];
            _ = await file.OpenReadStream(MaxAllowedSize).ReadAsync(buffer);
        }
    }
```

### Exceptions (if any)

```
r.arrayBuffer is not a function. (In 'r.arrayBuffer()', 'r.arrayBuffer' is undefined)
promiseReactionJob@[native code]
StackTrace:    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.AspNetCore.Components.PullFromJSDataStream.RequestDataFromJSAsync(Int32 )
   at Microsoft.AspNetCore.Components.PullFromJSDataStream.ReadAsync(Memory`1 , CancellationToken )
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.CopyFileDataIntoBuffer(Int64 , Memory`1 , CancellationToken )
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 , CancellationToken )
```

### .NET Version

6.0.406

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. We only support the latest versions of each browser, so we won't be addressing issues that only affect older browser versions.

You could try using a polyfill for the `arrayBuffer` function to see if it resolves your issue.
