### ISSUE TITLE
Add ControllerNameAttribute

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#47112]
I had the same [issue ](https://github.com/dotnet/aspnetcore/issues/31026#issue-834927901)with people thinking it was from. Net team, can the.Net team add a ControllerNameAttribute to match the placeholder in the routing template

**Comment by javiercn** [comment]
@Varorbc not built-in if that's what you are asking. 

The system provides extensibility for users to do so as mentioned in the [referenced](https://github.com/dotnet/aspnetcore/issues/31026#issuecomment-802130157) issue
