### ISSUE TITLE
[Blazor] Microsoft Edge translation causes crash because of DOM manipulation

### ISSUE THREAD

**Issue by scandler** [dotnet/aspnetcore#47111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create new project in Visual Studio from Blazor WASM App template with authentication.
Run in Edge. On my machine, Edge translates English to Dutch which results in console errors:

blazor.webassembly.js:1 
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'removeChild')
      TypeError: Cannot read properties of null (reading 'removeChild')

and application is stuck on "Authenticating..." (or "Machtigen" translated by Edge)

![image](https://user-images.githubusercontent.com/2410501/224035409-cd166ccb-6a9f-4f29-814a-a913bfdd8803.png)

### Expected Behavior

Translation will work or translation blocked by default, preventing DOM manipulations

### Steps To Reproduce

I think to reproduce it on a machine with an English Edge and Windows etc: the best way is to force the page into another language is by changing <html lang="en"> to <html lang="nl"> in the wwwroot/index.html

### .NET Version

7.0.103

**Comment by javiercn** [comment]
@scandler thanks for contacting us.

This is something that you should be able to control in your markup with [`<html translate="no" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate)

**Comment by javiercn** [comment]
@scandler that's likely the case because:
1) It's based on `chromium`.
2) Edge wants to understand the same web idioms.

**Comment by driesbolsZF** [comment]
Same issue occurs when a user translates the page in chrome

**Comment by mkArtakMSFT** [comment]
We'll try to see how some other frameworks behave here and go from there.

**Comment by MarcoTheFirst** [comment]
I ran into this problem in a production system, and it took us 4 days to figure out what the heck was going on. Here's how we fixed and prevented it for good:

`<html translate="no">`

`<meta name="google" content="notranslate">`

`<body class="notranslate">`

And if you want to go the extra mile, you can watch a div for undesired inner structural changes, thereby catching any undesired auto-translator action. Add the following div to the static part of your html body:

```
<div id="google-translate-trap">
    <p>This text is being watched for automatic translation.</p>
</div>
```

add the following css:
```
#google-translate-trap {
    opacity: 0.1; /* Makes the element fully transparent */
    position: absolute; /* Takes the element out of the normal document flow */
    width: 1px; /* Minimal width */
    height: 1px; /* Minimal height */
    overflow: hidden; /* Ensures no content spills out */
    pointer-events: none; /* Prevents interaction */
    user-select: none; /* Prevents text selection */
}
```

And finally, add the following JS code to your html page, or to an external script file:

```
<script type="text/javascript">
    function observeChanges(elementId, onchange) {
        var targetNode = document.getElementById(elementId);
        if (!targetNode) {
            return;
        }

        var config = { childList: true, subtree: true, characterData: true };

        var callback = function (mutationsList, observer) {
            for (let mutation of mutationsList) {
                if (mutation.type === 'childList' || mutation.type === 'characterData') {
                    onchange();
                    break;
                }
            }
        };

        var observer = new MutationObserver(callback);
        observer.observe(targetNode, config);

        return {
            disconnect: function () {
                observer.disconnect();
            }
        };
    }

    function autoTranslateDetected() {
        window.alert("You are using an automatic translator, like google chrome translator. This will cause unexpected errors on this site. Please deactivate all translators and other plugins which may directly modify the content of the page.");
    }
</script>
```

You may want to make the message prettier, maybe even calling Blazor via JS interop. But remember that Blazor may already be "dead" once the translator has changed the DOM. So I opted for a plain JS alert box.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by Mike-E-angelo** [comment]
Dang, I just ran into this issue.  Thank you @MarcoTheFirst for the workaround, or at least what is required to stop the errors.  There's still the major problem that non-English speakers will not be able to understand the rendered language of the application. 😞  I have been thinking that Chrome's translation feature was a huge feature for Blazor applications due to removing the need to localize assets like Maui requires, but now this seems not to be the case. 💥

I have been seeing this error for many months now, and did not know what was causing it.  A good deal of my customers are in Europe and use English as a second language.  This will really suck to remove the translation.  I am surprised that this is not considered a priority feature, given how... international... the world is.

**Comment by ghost** [comment]
@Mike-E-angelo yeah I know it's annoying. But it's also partly the fault of Google translator, since it doesn't just translate the inner texts but instead wraps them in additional spans / divs. I believe that's what really breaks Blazor's shadow DOM. I'm surprised other SPA frameworks like angular / react don't have the same problem.
