### ISSUE TITLE
.net 7 JwtBearerDefaults.AuthenticationScheme not work with Entity framework core Identity

### ISSUE THREAD

**Issue by amrmostafa800** [dotnet/aspnetcore#47119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

# Asp.NetCoreApi_Identity_bug
bug in asp.net core WebApi with Entity framework core
when test with ``` JwtBearerDefaults.AuthenticationScheme ``` get this
![image](https://user-images.githubusercontent.com/20041519/224171999-c8cf04d8-7cf7-4c32-a9d6-06cf8a7817c8.png)

when test with
```
options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}
```
work normal
![image](https://user-images.githubusercontent.com/20041519/224172334-3f6d1190-e014-435f-8f74-82e6dbc09a68.png)

and if test with ``` JwtBearerDefaults.AuthenticationScheme ``` but remove this
```
builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();
```
work normal
![image](https://user-images.githubusercontent.com/20041519/224172677-19989253-f695-486f-96d9-6c5a92e860de.png)

i create repo with code i test https://github.com/amrmostafa800/Asp.NetCoreApi_Identity_bug

### .NET Version

7.0.200

### Anything else?

i found issue similar to it but it closed https://github.com/dotnet/aspnetcore/issues/46774

**Comment by mitchdenny** [comment]
Triage: @halter73 this is probably your area?

**Comment by mitchdenny** [comment]
Try wiring up to the OnAuthenticationFailed event (e.g.):

```csharp
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(jwtOptions => {

    jwtOptions.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = async (AuthenticationFailedContext context) =>
        {
            // Your breakpoint here.
        }
    };
});
```

**Comment by amrmostafa800** [comment]
> Try wiring up to the OnAuthenticationFailed event (e.g.):
> 
> ```cs
> builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(jwtOptions => {
> 
>     jwtOptions.Events = new JwtBearerEvents
>     {
>         OnAuthenticationFailed = async (AuthenticationFailedContext context) =>
>         {
>             // Your breakpoint here.
>         }
>     };
> });
> ```

get
![image](https://user-images.githubusercontent.com/20041519/224339873-c44ef89e-78e9-41ab-baac-7c5ac7ed94db.png)
and breakpoint not catched + if you put normal JWT code (without OnTokenValidated) error will happen too

**Comment by mitchdenny** [comment]
So I think what is happening here is that AddIdentity is setting up the cookie auth scheme (thats fine, you should expect). However your `[Authorize]` attribute on your `TestAuth` action method isn't being specific in which authentication scheme that you want o use. Try setting this on your `TestAuth` action method:

```csharp
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
```

**Comment by amrmostafa800** [comment]
> So I think what is happening here is that AddIdentity is setting up the cookie auth scheme (thats fine, you should expect). However your `[Authorize]` attribute on your `TestAuth` action method isn't being specific in which authentication scheme that you want o use. Try setting this on your `TestAuth` action method:
> 
> ```cs
>         [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
> ```

work now thanks for help
![image](https://user-images.githubusercontent.com/20041519/225648477-aacb540a-aa00-4026-ac92-31cee9baf19d.png)
