### ISSUE TITLE
Add option to refresh the claims of a logged in user from UserInfo endpoint

### ISSUE THREAD

**Issue by xabikos** [dotnet/aspnetcore#47125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Given we have the scenario when the user is authenticated through cookie authentication and uses a third party identity provider e.g. Duende Identity server.

We have the option to automatically map the data we get from user info endpoint (`connect/userinfo`) as claims after a successful log in. These claims are stored in the session and the cookie. 

It's very likely part of this claims to be user's first and last name. In the scenario that we allow the user to change either of these values then the claims still include the old values unless the user log out and log back in. Except this example we could also have a need to store something additional like accepting terms and conditions of our service before proceeding to a purchase of a service.

### Describe the solution you'd like

I am not sure what is the best approach to refresh the claims and have this reflected in the cookie as well. 

The only idea that I can think of is to provide some extension point to the OpenIdConnect handler or to a different component that will trigger explicitly a request to userinfo endpoint map the new values and replace the existing ones for the current user. 

During reading on the subject I found some alternative solutions like adding logic to [CustomAuthenticationCookieEvents](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-6.0#react-to-back-end-changes) but as mentioned there I would prefer to avoid going this route as it would have a negative impact on the performance.

So I am thinking for an extension point that we can call from the code that triggers the same set of actions as when the user authenticates successfully.

**Comment by Tratcher** [comment]
This might be similar to some prior experiments I did around refresh tokens.
https://github.com/dotnet/aspnetcore/blob/06f1d1de4ff60e88ee0134fc827a7703ba739325/src/Security/Authentication/samples/SocialSample/Startup.cs#L272-L273
