### ISSUE TITLE
dotnet watch epic fail on Ubuntu

### ISSUE THREAD

**Issue by pjpmccarthy** [dotnet/aspnetcore#47122]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/run
Operating System: Linux

dotnet watch
The command did not respond and crashed the OS so I have to reboot.

**Comment by thecsharper** [comment]
![Output](https://github.com/dotnet/aspnetcore/assets/6189760/f964c5c0-7a2d-40e3-9a08-af50244515a4)
![Environment](https://github.com/dotnet/aspnetcore/assets/6189760/2c3d7971-6273-4bda-ae04-734d73d9c2b6)
Can't replicate on Ubuntu 22.04 - any chance you can provide more details @pjpmccarthy - thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be an issue with dotnet watch.
