### ISSUE TITLE
HttpContext.Response.ContentLength return null (with System.Text.Json)

### ISSUE THREAD

**Issue by SaleCar** [dotnet/aspnetcore#47127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I want to catch response **ContentLength** from filter or middleware but it's always null.

Simplified example (middleware):

```
public async Task InvokeAsync(HttpContext context) {
    await _next(context);
    Console.WriteLine(context.Response.ContentLength);
}
```

Same thing when using filters. This code is started after endpoint but no ContentLength (?!).

When I switch to **Microsoft.AspNetCore.Mvc.NewtonsoftJson**, same code, ContentLength is calculated and shown!

Is this a bug in **System.Text.Json** or I'm missing something to configure differently? How it works when using **NewtonsoftJson**?

Thanks

### .NET Version

7.0.3

### Screenshot

![Screenshot](https://user-images.githubusercontent.com/39879027/224476388-9d852929-7bff-4440-a353-71a349d44630.png)

**Comment by Tratcher** [comment]
The Content-Length is an optional header. Calculating it requires buffering the full response, which we don't do by default because it consumes extra resources and adds latency. NewtonsoftJson buffers because it doesn't support async IO.

**Comment by SaleCar** [comment]
@Tratcher Thanks for your reply. How can this be enabled? I need it for logging and performance is not that important to me for now. But it is nice that we know about this so that everyone can configure it as they like.

**Comment by Tratcher** [comment]
Ideally you'd do it at the point of content creation.

See how we do it with Newtonsoft (because it doesn't support async IO) https://github.com/dotnet/aspnetcore/blob/4d2071ee4b95d0b90d6538defb420c44b23b16e6/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonOutputFormatter.cs#L145-L181

Otherwise you have to do something like this but also replace the response body Stream.
