### ISSUE TITLE
ApiConventionNameMatch doesn't work as expected

### ISSUE THREAD

**Issue by francotiveron** [dotnet/aspnetcore#47120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ApiConventionNameMatch doesn't work as expected:
F#
```
type YatpApiConventions = 
..
    [<ProducesResponseType(StatusCodes.Status200OK)>]
    [<ProducesResponseType(StatusCodes.Status404NotFound)>]
    [<ProducesResponseType(typeof<Dto.Exception>, StatusCodes.Status500InternalServerError)>]
    [<ApiConventionNameMatch(ApiConventionNameMatchBehavior.Suffix)>]
    static member _200404500([<ApiConventionNameMatch(ApiConventionNameMatchBehavior.Suffix)>] Id: string) = ()
```
```
[<ApiController>]
[<ApiConventionType(typeof<YatpApiConventions>)>]
[<Authorize>]
type YatpApiController(...) = 
...
    [<HttpGet("find-product-a")>]
    [<AllowAnonymous>]
    member this.FindProductA_200404500([<Required>] productId: string) = Market.Product.withName_ productId |> Async.map (Option.map Dto.Of >> Option.toObj) |> this.Http

    [<HttpGet("find-product-b")>]
    [<AllowAnonymous>]
    member this.FindProductB_200404500([<Required>] productId: string) = Market.Product.withName_ productId|> Async.map (Option.map Dto.Of >> Option.toObj) |> this.Http
```

API conventions are not applied:

![image](https://user-images.githubusercontent.com/8280970/224199568-85b2428e-2279-4a48-a4d2-e464e1472189.png)
![image](https://user-images.githubusercontent.com/8280970/224199636-a8b34e9d-dc5d-4959-8bf9-218fdcaa62de.png)

### Expected Behavior

API Convention should apply. Note that

1) If I change the name of the method to FindProduct_200404500 (instead of FindProductA_200404500 or FindProductB_200404500), or
2) I explicitly apply the convention as in

```
    [<HttpGet("find-product-b")>]
    [<ApiConventionMethod(typeof<YatpApiConventions>, nameof YatpApiConventions._200404500)>]
    [<AllowAnonymous>]
    member this.FindProductB_200404500([<Required>] productId: string) = Market.Product.withName_ productId|> Async.map (Option.map Dto.Of >> Option.toObj) |> this.Http
```

conventions are applied successfully

![image](https://user-images.githubusercontent.com/8280970/224200149-d899bac9-b688-48b8-b903-1c99ee8efb3d.png)

### .NET Version

7.0.201

### Anything else?

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by captainsafia** [comment]
@francotiveron The [ApiConventionNameMatchBehavior.Suffix](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apiexplorer.apiconventionnamematchbehavior?view=aspnetcore-7.0) assumes that the letter before the suffix is lowercase ([ref](https://github.com/dotnet/aspnetcore/blob/63642be229e26f4a766bc1cb7a7c3fc5f72eecdb/src/Mvc/Mvc.Core/src/ApiExplorer/ApiConventionMatcher.cs#L150-L154)) which is why things work when you change the name to `FindProduct_200404500`.

Applying the convention directly via the `ApiConventionMethod` attribute surpasses the matching check which is why you also see things working when that attribute is used.

I'm hesitant to change the behavior here since it's been longstanding and will likely be a breaking change. The alternatives that you've described should work for this and this explanation should hopefully clarify why this happens.

**Comment by francotiveron** [comment]
Good to know. I can change my method names. I recommend writing this detail in the docs if not already done
