### ISSUE TITLE
Having parity between IParsable support in RDF and RDG

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#47134]
RDF does not currently support invoking explicit interface implementations of IParsable types (see https://github.com/dotnet/aspnetcore/issues/43546), but RDG does. We should consider adding support for this in RDF.

Also, taking a note here to make sure the experience is the same in both places.

**Comment by captainsafia** [comment]
@mitchdenny Good candidate for preview5?

**Comment by mitchdenny** [comment]
Yep

**Comment by captainsafia** [comment]
@mitchdenny I think we can close this?

**Comment by mitchdenny** [comment]
Yep.
