### ISSUE TITLE
[QuickGrid] Miscellaneous TODOs

### ISSUE THREAD

**Issue by Nick-Stanton** [dotnet/aspnetcore#47137]
## Miscellaneous TODOs

Following the productization of QuickGrid in #46317, there are still a few TODO comments that explore potential design improvements. Resolving these may result in improved performance and/or behavior. These are a subset of the list of [potential QuickGrid improvements](https://github.com/dotnet/aspnetcore/labels/feature-blazor-quickgrid).

### QuickGrid.razor.cs

- [ ] #47138
- [x] #47139

### QuickGrid.razor.css

- [x] #47140

### PropertyColumn.cs

- [x] #47141

**Comment by mkArtakMSFT** [comment]
Thanks @Nick-Stanton.
Looks like there is only one remaining item left here which is tracked already with a separate task. So closing this at this point.
