### ISSUE TITLE
[QuickGrid] Don't use scoped CSS for QuickGrid.razor

### ISSUE THREAD

**Issue by Nick-Stanton** [dotnet/aspnetcore#47140]
https://github.com/dotnet/aspnetcore/blob/42905b0edce0f5f1e3c69b628874216d5fc36925/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor.css#L1-L5

**Comment by MackinnonBuck** [comment]
Closing this out because this improvement won't impact public API, and it currently works well enough. We can make this change at any time in the future.
