### ISSUE TITLE
Refreshing a page (F5) Fails to load when using URL with Guid & double data type

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#47149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Blazor Server (.net 7)
When I have URL with Parameter of datatype  guid or double, the page Refresh using F5 fails to reload the page.
The internal navigation from the Code works fine, but fails for the following conditions
1) When refreshing page (F5)
2) Typing the for URL in the new window also results into same error as in #1

### Expected Behavior

It should reload the Page without any error in both scenario

### Steps To Reproduce

Link to Repo.
https://github.com/nssidhu/BlazorAppGuidInURL

Try navigating to the page using left menu for counter
It will successfully navigate,
Now Reload the Page using F5 or browser's reload button

Also look at the .gif to see the scenarios where it fails

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/3267605/224463980-deb0c095-81e3-4c40-a743-5cbeb23f424a.png)

![2023-03-10_22-12-47](https://user-images.githubusercontent.com/3267605/224464270-14463e45-d57a-4c3a-b1c9-f31158840cca.gif)

### .NET Version

.net 7

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. It looks like the URL is being identified as potentially having a file extension in the name, which causes it to not match the desired route. You can fix this by using `app.MapFallbackToPage("{**path}", "/_Host")`.
