### ISSUE TITLE
cant get windows authentication credentials via defaultcredentials

### ISSUE THREAD

**Issue by markat1** [dotnet/aspnetcore#47143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to somehow pass the windows authenticated users credentials into get request in blazor (using IhttpRequestFactory), but it doesnt seem  to work:

- setting UseDefaultCredentials  to true
- grabbing user authentication via DefaultNetworkCredentials or defaultcredentials
- using environment.UserName and domainname.

```

            var config = configuration.GetSection("ApiConfiguration:config").Get<ApiConfiguration>();


            services.AddHttpClient(config.Api, options =>
            {
                options.BaseAddress = new Uri(config.RequestUri);
            })
          
            .ConfigurePrimaryHttpMessageHandler(() =>
            {
                //ICredentials credentials = CredentialCache.DefaultNetworkCredentials;
                //ICredentials credentials2 = CredentialCache.DefaultCredentials;

                var t = configuration;
                var tq = services;

                //var handler = new HttpClientHandler();
                //handler.Credentials = new NetworkCredential(Environment.UserName, string.Empty, Environment.UserDomainName);

                return new HttpClientHandler
                {
                    //UseDefaultCredentials = true,
                     
                    AllowAutoRedirect = true,
                    UseProxy = false,
                    PreAuthenticate = true,
                    //Credentials = credentials,
                    //SslProtocols = System.Security.Authentication.SslProtocols.None,
                    //PreAuthenticate = true
                    //Credentials = new NetworkCredential("test", "test2")
                    //DefaultProxyCredentials = CredentialCache.DefaultCredentials
                };
            });
```

This is where I use the client factory

```
   private readonly IHttpClientFactory _clientFactory;

        public test(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        public async Task<HttpResponseMessage?> ConfirmContact(int? contactId)
        {

            var client = _clientFactory.CreateClient("test");

            CancellationToken cancellationToken = new();

            return await client.GetAsync(client.BaseAddress, cancellationToken);
        }
```

### Expected Behavior

should post and send a message back that it has passed.

### Exceptions (if any)

blazor.server.js:1 [2023-03-10T20:21:45.720Z] Error: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

### .NET Version

6

### Anything else?

what kinda application? blazor server application.

in visual studio: Seems like ConfigurePrimaryHttpMessageHandler  uses the default credentials from the person who's logged in.

in production: user default credentials not set (doesn't seem to try get the person who's accessing the system from the domain with their windows authentication credentials when they access the site) 

When I send the request from my local enviroment it takes the default credentials from the person who is logged into the system on the computer.  I know that because I have tried making other people log into my blazor site via firefox with their credentials from the same computer and same local development environment spinned up via visual studio. It still takes users who is logged into the systems credentials, and not the one who logged in via firefox.  It might not know the person who's logged in on the production IIS (but weird enough it actually does know that person from every other aspect of the site, but not during http calls).

![image](https://user-images.githubusercontent.com/8057282/224978404-cb124c65-6c84-45be-be54-ff1d49acef32.png)

application uses http 1.1

**Comment by markat1** [comment]
I added following, but does seem to get the windows credentials when I run the project via visual studio , but it still doesnt work on my IIS server in production. Is there any settings missing?

```
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();

```

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-7.0&tabs=visual-studio#impersonation

**Comment by markat1** [comment]
Hi @Tratcher - how do I use impersonation in with my Ihttpfactory? 

anyway, in my blazor app I can get users information during initialization of my app. This is from my _host.cshtml.
maybe I can somehow fetch users credentials here? but how.

@{
    Layout = "_Layout";

    var userconfig = new InitialApplicationState
    {
        UserName = HttpContext?.User?.Identity?.Name ?? string.Empty,
    };
}

<component type="typeof(App)" param-InitialState="userconfig" render-mode="Server" />

**Comment by markat1** [comment]
I also tried the following, but still didnt work in production (only works in visual studio)


    ```
    [HttpGet]
        //[Authorize(AuthenticationSchemes = NegotiateDefaults.AuthenticationScheme)]
        [Route("contact/confirm/{contactId}")]
        public async Task<string> ConfirmContact(int contactId)
        {

            var user = (WindowsIdentity)HttpContext.User.Identity!;

            var t = await WindowsIdentity.RunImpersonatedAsync(user.AccessToken, async () =>
            {

                var client = _clientFactory.CreateClient("test");
                var response = await client.GetAsync($"{client.BaseAddress}{contactId}");
                var confirmationStatus = await response.Content.ReadAsStringAsync();

                return confirmationStatus;

            });

            return t;
        }
```

**Comment by markat1** [comment]
Third try is is following, but that gives me a "not authroized" error:

I use AuthenticationState  from blazor so I can receive the user
`
        [CascadingParameter] private Task<AuthenticationState>? AuthenticationState { get; set; }`

Then I pass users accces token into WindowsIdentity.RunImpersonateAsync:

```
  var authState = await AuthenticationState;
                    var user = (WindowsIdentity)authState?.User.Identity!;

          
                    await WindowsIdentity.RunImpersonatedAsync(user.AccessToken, async () =>
                    {

                        var client = HttpClientFactory.CreateClient("test");

                        HttpResponseMessage httpResponseMessage = await client.GetAsync($"{client.BaseAddress}{38066}");

                        var confirmationStatus = await httpResponseMessage.Content.ReadAsStringAsync();

                    });
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

As a side note, this thread may be relevant and may be useful: https://stackoverflow.com/questions/61955768/how-do-i-use-httpclientfactory-with-impersonation-or-find-another-way-to-get-a/61980188#61980188

**Comment by markat1** [comment]
I totally disagree -  I ask how I can send windows credentials via a httprequest in a blazor server applikation (NOT asp.net core), when I already have the user logged in via windows authentication .  Clearly there's no documentation saying anything about how this other than 5 lines about impersonation that I can't figure how that would help in a blazor server application.  The only solution seems to be that I should prompt the user for a windows password eventhough person is already logged in with windows auth, which I don't find.
