### ISSUE TITLE
Can't serve valid blazor webassembly from Docker

### ISSUE THREAD

**Issue by sajjadsaharkhan** [dotnet/aspnetcore#47167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

my problem is similar to [#22392](https://github.com/dotnet/aspnetcore/issues/22392) but don't fix with this issue solutions.

I try to deploy my blazor web assembly project with docker. but the docker version and local IIS (debug/development mode) version of the project have behavioral differences. some routing and js activities not working in docker mode.
It seems some files are not loaded or served in docker version

it's my Dockerfile

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY AdminPanel/AdminPanel.csproj .
RUN dotnet restore AdminPanel.csproj
COPY . .
RUN dotnet build AdminPanel/AdminPanel.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish AdminPanel/AdminPanel.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app .
COPY nginx.conf /etc/nginx/nginx.conf
```

and this is my `nginx.conf`:

``` nginx
events { }
http {
    include mime.types;
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html/publish/wwwroot;
            try_files $uri $uri/ /index.html =404;
        }
    }
}

```

it's my `csproj` file : [gist link](https://gist.github.com/sajjadsaharkhan/462dba077c73d76b18a3633b55ff353c)

in debug mode my `console` tab is:
![image](https://user-images.githubusercontent.com/31157619/224575118-5651714e-d940-4209-b1a3-816da9705a1b.png)

and in my docker container mode `console` tab is:
![image](https://user-images.githubusercontent.com/31157619/224575257-3ba92e06-fc5d-4e1b-bb34-5922e7870328.png)

### Expected Behavior

I expect my docker env and my development env have same behavior!

### .NET Version

6

**Comment by javiercn** [comment]
@sajjadsaharkhan thanks for contacting us.

That seems to be an issue with your nginx configuration. Unfortunately, that's not something we can help with as we are not experts in `nginx` or other third-party web servers.

We suggest you create a hosted application, publish it, run it and observe the results in the network tab to understand what you need to replicate in your nginx configuration.

From what we can tell from the error, you are not serving some files correctly.
