### ISSUE TITLE
In the core, why is there only ActionNameAttribute and no ControlNameAttribute

### ISSUE THREAD

**Issue by RoderickIveans** [dotnet/aspnetcore#47171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In the core, why is there only [ActionNameAttribute ](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ActionNameAttribute.cs) and not `ControlNameAttribute`

### Describe the solution you'd like

add `ControlNameAttribute`

**Comment by javiercn** [comment]
@RoderickIveans thanks for contacting us.

ActionName is there for back compatibility with old ASP.NET MVC versions. The system in ASP.NET Core avoids baking in these types of attributes as it is trivial to build one for yourself if you want to. There is no ControllerName attribute in old MVC, hence why we did not add one in the new version.

It is trivial for you to write one if you choose to do so:

```csharp
public class ControllerNameAttribute(string controllerName) : Attribute, IControllerModelConvention
{
    public void Apply(ControllerModel model) => model.ControllerName = controllerName;
}
```
