### ISSUE TITLE
Allow rendering components to specific DOM node outside DOM hierarchy like React.createPortal

### ISSUE THREAD

**Issue by ferraridavide** [dotnet/aspnetcore#47178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to render a Razor component in an external browser popup window, i would like to be able to do this without restarting the whole WASM app inside the popup, the popup should be controlled by the main WASM app

Experimenting with this idea, i though i could (somehow) instantiate WebAssemblyRenderer and point it to a specific DOM node, unfortunately the class is internal and also any extension of RenderTree types are discouraged by a warning

### Describe the solution you'd like

Something similar to ReactDOM.createPortal, where i can render a component to a specific DOM node

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not a supported scenario, but you may be able to proceed (to some extent) by utilizing https://learn.microsoft.com/aspnet/core/blazor/components/js-spa-frameworks?view=aspnetcore-7.0.
Please note, that event handling won't work, as Blazor listens for events only when they propagate to the top of the DOM hierarchy.
