### ISSUE TITLE
Asp.net core mvc read request body is very slow

### ISSUE THREAD

**Issue by hjatms** [dotnet/aspnetcore#47182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our PROD env, we found if the request from upstream service is from localhost, the `request.Body.CopyToAsync()` normally took <1ms to finish, but if it's from non-localhost, the time can take up to several hundred ms.

In our TEST TDS env, I found a related repro (maybe not the same thing): I wrote a simplest controller, withoput any middlewares, using HttpSys:

```c#
        [Route("test")]
        [HttpPost]
        public async Task<IActionResult> Foo()
        {
            var stream = new MemoryStream();

            var timer = Stopwatch.StartNew();
            await this.Request.Body.CopyToAsync(stream);
            timer.Stop();
            Console.WriteLine($"CopyToAsync: {timer.ElapsedMilliseconds} ms, {timer.ElapsedTicks} ticks");

            return new OkObjectResult("hello");
        }
```

I also wrote a client which just simply send some payload to the controller, it's built on net472 and Netcore, the behavior is:

1. If I send request via net472 client binary, from my dev box to my test server, `request.Body.CopyToAsync()` always took 300ms to finish
2. If I send request via net core client binary, from my dev box to my test server, `request.Body.CopyToAsync()` always took <1ms to finish
3. If I copy the net472 client binary to test server, and run it in test server, now it's localhost, `request.Body.CopyToAsync()` always took <1ms to finish

![image](https://user-images.githubusercontent.com/127810692/224882747-cc26fbd1-9d9d-4d60-a9bb-f8356d64c672.png)

I've found a similar case: https://github.com/dotnet/aspnetcore/issues/21502, the triggering condition is same, but outcome is not same.

### Expected Behavior

`request.Body.CopyToAsync()` should not took so long time

### Steps To Reproduce

described above.

### Exceptions (if any)

None

### .NET Version

6.0.301

**Comment by hjatms** [comment]
captured the traffic, it seems for Netcore client, the payload is sent without receiving ack from server, but for net framework client, it sends a payload, then receive ack, then send next payload, and somehow the time is longer

![image](https://user-images.githubusercontent.com/127810692/224967033-a51f11f8-0c50-4530-8d0b-d5fe416d3575.png)

**Comment by BrennanConroy** [comment]
Try setting `ServicePointManager.Expect100Continue = false;` in your NetFx client.

**Comment by hjatms** [comment]
> Try setting `ServicePointManager.Expect100Continue = false;` in your NetFx client.

Already tried this but it did not work
