### ISSUE TITLE
Client.Client(connectionId) returing incorrect proxy connection

### ISSUE THREAD

**Issue by BobbyCannon** [dotnet/aspnetcore#47189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The issue only happens on OnConnectedAsync. The issue does not happen on OnDisconnectedAsync and will work as expected.

![image](https://user-images.githubusercontent.com/840590/225073898-ebf046bf-a476-4f57-bc1f-382920b83afd.png)

### Expected Behavior

When calling Clients.Client with a Connection Id, I would expect the correct client proxy to be returned.

### Steps To Reproduce

Create a notification hub 

`public class NotificationHub : Hub, INotificationHub`

Try to call another connected client when a different client is connecting.

`public override async Task OnConnectedAsync()`

When the first client is connecting in "OnConnectedAsync()", try to get the proxy of an existing connection via the Clients.Client(otherId). The current connecting connection proxy will be returned instead of the one requested.

```
var client = Clients.Client(connectionId);
await client.SendCoreAsync(nameof(SendSingleNotification), new object[] { message });
```

### .NET Version

7.0.201

**Comment by BobbyCannon** [comment]
I was able to get around the problem by doing very bad things... but I wanted to see if I could hack around it. Here is what I did.

```
public async void SendSingleNotification(string connectionId, NotificationMessage message)
{
	// todo: replace this with code below when it gets fixed
	var hubClients = Clients.GetMemberValue("_hubClients");
	var lifetimeManager = (HubLifetimeManager<NotificationHub>) hubClients.GetMemberValue("_lifetimeManager");
	var connections = (HubConnectionStore) lifetimeManager.GetMemberValue("_connections");
	var connectionContext = connections[connectionId];
	if (connectionContext == null)
	{
		return;
	}

	var iMessage = new InvocationMessage(nameof(SendSingleNotification), new object[] { message });
	await connectionContext.WriteAsync(iMessage, CancellationToken.None);

	// The code below does not work, had to fix with hack above
	//var client = Clients.Client(connectionId);
	//await client.SendCoreAsync(nameof(SendSingleNotification), new object[] { message });
}
```

The code above reaches into the Clients and grabs the connection manually.  I'm not sure why this works...

**Comment by BrennanConroy** [comment]
Nice find, the bug is from a copy-paste error looks like, single character fix 😄 
`_connectionId` -> `connectionId`
https://github.com/dotnet/aspnetcore/blob/dca54bec0016f11adc671d2f53fcb3ffc5378fca/src/SignalR/server/Core/src/Internal/HubCallerClients.cs#L53
