### ISSUE TITLE
Why is Blazor deploying Microsoft.CodeAnalysis?

### ISSUE THREAD

**Issue by ivancavlek** [dotnet/aspnetcore#47215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Blazor on ASP.NET 7.0.3 that is deployed to Azure Static Web Apps. I am currently trying to optimize the app. In doing so I find it really interesting that Blazor is deploying _Microsoft.CodeAnalysis_ DLLs as it is seen in blazor.boot.json "satelliteResources".

![image](https://user-images.githubusercontent.com/16662190/225296330-8c10b9d4-43e9-415b-83cb-62f28d3d75ed.png)
and what's worse, I am not using most of the languages that are there.

This DLLs take a lot of space, among the most in my app.
![image](https://user-images.githubusercontent.com/16662190/225296939-2b7f377f-b7dc-475d-93ea-ffe4a4a36f5f.png)

Are _Microsoft.CodeAnalysis_ DLLs really needed and if not, how to get rid of them?
I am using RESX files and I have `BlazorWebAssemblyLoadAllGlobalizationData` enabled. I require globalization and localization.

**Comment by javiercn** [comment]
@ivancavlek thanks for contacting us.

Is this happening with a new template?

You can check the project.json in your `obj` folder to track the dependency chain and determine where it is coming from.

**Comment by ivancavlek** [comment]
@javiercn, I have to admit that I have this template since the preview version 😓, but I've been updating it regularly:

![image](https://user-images.githubusercontent.com/16662190/225303819-dedc48b9-9975-4f48-a715-85c3609649d1.png)

Things that are not visible are ProjectReferences and Usings.

**Comment by ivancavlek** [comment]
I can confirm that I found a relic NuGet Package from the past. Once deleted, _Microsoft.CodeAnalysis_ is gone.

Thank you, @javiercn 😊!
