### ISSUE TITLE
ValidationProblemDetails does not deserialize as expected

### ISSUE THREAD

**Issue by jander-msft** [dotnet/aspnetcore#47223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The dotnet-monitor tool produces HTTP response bodies that have the shape of `ValidationProblemDetails` when bad request occurs; in fact, it instantiates this class, fills it out, and sends it back as a `BadRequestObjectResult`. The response body typically looks like `{\"status\":400,\"detail\":\"HTTP egress is not enabled.\"}`.

We have tests that validate that dotnet-monitor is producing the expected responses. For bad requests, it deserializes the response body to validate the appropriate error information is produced. Starting in .NET 8.0 Preview 2, deserialization of the response body using `JsonSerializer.DeserializeAsync<ValidationProblemDetails>` no longer fills out the object as expected. The `status` and `detail` values from the JSON end up in the `Extensions` property rather than the `Status` and `Detail` properties.

### Expected Behavior

When deserializing JSON content in the shape of a `application/problem+json` content type, the `ValidationProblemDetails` object should be filled in correctly.

### Steps To Reproduce

The Status and Details property assertions fail with ASP.NET Core 8.0 Preview 2 whereas they've worked on all prior versions.

```cs
string content = "{\"status\":400,\"detail\":\"HTTP egress is not enabled.\"}";
using MemoryStream stream = new();
using StreamWriter writer = new(stream);
writer.Write(content);
writer.Flush();
stream.Position = 0;

JsonSerializerOptions options = new();
options.Converters.Add(new JsonStringEnumConverter());

ValidationProblemDetails details = await JsonSerializer.DeserializeAsync<ValidationProblemDetails>(stream, options);
Assert.Equal(400, details.Status);
Assert.Equal("HTTP egress is not enabled.", details.Detail);
```

### .NET Version

8.0.100-preview.2.23157.25

### Anything else?

Likely caused by https://github.com/dotnet/aspnetcore/commit/330d24666867205a973ff382d070e570feca8280

**Comment by jander-msft** [comment]
Sure, we ended up fixing it by customizing the JSON serialization options further like you said in the second resolution: https://github.com/dotnet/dotnet-monitor/commit/1460a44953a32ef868d7a69e17b96eb62d26292a

However, this is a breaking change for any client that is migrating from say .NET 7 to .NET 8. The default deserialization behavior has changed for `ValidationProblemDetails` (and related classes); it's now expecting property names to be capitalized (only in .NET 8 Preview 2 and forward) whereas ASP.NET servers are producing the content with lowercase property names (all versions of .NET).

If you take this code:
```cs
[ApiController]
    [Route("")]
    public class MyController : ControllerBase
    {
        [HttpGet("makeproblem")]
        public ActionResult MakeProblem()
        {
            return new BadRequestObjectResult(new ProblemDetails() {
                Detail = "HTTP egress is not enabled.",
                Status = (int)HttpStatusCode.BadRequest
            });
        }

        [HttpGet("getproblem")]
        public async Task<ActionResult> GetProblem()
        {
            UriBuilder builder = new();
            builder.Scheme = "http";
            builder.Host = HttpContext.Request.Host.Host;
            builder.Port = HttpContext.Request.Host.Port.GetValueOrDefault(80);

            using HttpClient client = new HttpClient();
            client.BaseAddress = builder.Uri;

            using HttpRequestMessage request = new(HttpMethod.Get, "makeproblem");
            using HttpResponseMessage response = await client.SendAsync(request);

            using Stream stream = response.Content.ReadAsStream();

            using StreamReader reader = new(stream, leaveOpen: true);
            string content = reader.ReadToEnd();
            stream.Position = 0;

            ValidationProblemDetails details = (await JsonSerializer.DeserializeAsync<ValidationProblemDetails>(stream))!;
            if (string.IsNullOrEmpty(details.Detail) || !details.Status.HasValue)
                
                return BadRequest();
            else
                return Ok();
        }
    }
```

And GET the `/getproblem` route, it will return HTTP 200 on .NET 7 and prior whereas upgrading to .NET 8 will cause it to return HTTP 400. That's a breaking behavioral change.

I'm expecting either that to be corrected or a breaking change to be announced.

**Comment by captainsafia** [comment]
@jander-msft Yep, I'll move forward with filing a breaking change for this.

The previous behavior was buggy and inconsistent with the semantics of System.Text.Json. I don't see a way to maintain the behavior moving forward (and don't think we should).

Thanks for trying out the preview and helping us identify things like this early on in the development cycle. 😃

**Comment by captainsafia** [comment]
Closing via https://github.com/aspnet/Announcements/issues/504.
