### ISSUE TITLE
Update Identity UI to use Blazor Components

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#47233]

**Comment by DamianEdwards** [comment]
FYI the results of an investigation into this I did last year: https://github.com/DamianEdwards/BlazorIdentity

**Comment by mkArtakMSFT** [comment]
Closing this as we aren't going to replace the Default Identity UI. Instead, we will have a new Blazor Components-based UI

**Comment by DamianEdwards** [comment]
@mkArtakMSFT is there an issue tracking adding Identity Razor Components?

**Comment by mkArtakMSFT** [comment]
I thought we did have one, but turned out not yet. So here is the new one: https://github.com/dotnet/aspnetcore/issues/48786
