### ISSUE TITLE
Embed mono-config.json inside blazor.boot.json

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#47243]

**Comment by javiercn** [comment]
@MackinnonBuck I think @maraf is taking care of this part. Can you folks sync to make sure we don't duplicate work?

**Comment by maraf** [comment]
I'll take care of the boot config

**Comment by mkArtakMSFT** [comment]
@maraf can this be closed, if you have another tracking issue for this?
