### ISSUE TITLE
Remove duplicate tests from RDFTests for testing array binding support

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#47245]
As part of the RDG tests the parameter array binding tests were moved into the common test infrastructure so we can test the same set of tests across RDF and RDG. That means that he old tests in RDF are now redundant, this is a reminder to go clean them up once the RDG change goes in (don't want to make it the same PR to make revert a bit easier if we need to).

**Comment by captainsafia** [comment]
@mitchdenny Is it fair to close this in favor of https://github.com/dotnet/aspnetcore/issues/47345?
