### ISSUE TITLE
Utilize new StaticWebAssets SDK

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#47242]
Splitting out some items from #46997 as follow-up items after the changes in https://github.com/dotnet/sdk/pull/31079:
- [ ] Removing the Razor SDK and related files from the SDK repo, since they ship from dotnet/razor now.
- [ ] Removing Static Web Assets related files from the Razor SDK repo, since they'll ship from the SDK repo.
- [ ] Updating the Razor SDK repo to consume the static web assets SDK repo.

**Comment by mkArtakMSFT** [comment]
This issue was created with the assumption that all the Static Assets code lives in the dotnet/razor repo, but it's not the case. Hence, there is no work to be done here.
