### ISSUE TITLE
Theme: Cloud Native

### ISSUE THREAD

**Issue by glennc** [dotnet/aspnetcore#47240]
One of our ongoing themes of .NET is to make it as easy as possible to build applications for the cloud, whether you are building small microservices, serverless functions, monolith, or anything else designed to be deployed in a cloud environment. In .NET 8 we have a few workstreams that are helping us make progress on that.

### Performance and Fundamentals

We want to continue our performance progress making sure that .NET is as fast as it can be when building services, and in particular improve our AOT experiences to provide a default performance profile that gives you a compelling mix of size on disk, startup time, memory consumption, and memory usage.

  - [x] https://github.com/dotnet/aspnetcore/issues/45910
  - [x] https://github.com/dotnet/runtime/issues/69739
  - [x] https://github.com/dotnet/dotnet-docker/issues/4343
  - [x] https://github.com/dotnet/dotnet-docker/pull/4397
  - [x] https://github.com/dotnet/dotnet-docker/issues/4388
  - [x] https://github.com/dotnet/dotnet-docker/issues/4322
 
###  Diagnostics on Linux

For diagnostics, we are specifically looking at Linux and how .NET shows up in the tools that are natural to use when diagnosing problems on Linux and in environments like containers and Kubernetes.

- [ ] https://github.com/dotnet/diagnostics/issues/3756
- [x] https://github.com/dotnet/dotnet-docker/pull/4352

### Libraries improvements

Evolve the capabilities of core libraries to support Cloud Native and Native AOT scenarios.

  - [x] https://github.com/dotnet/runtime/issues/78518

### Tooling and SDK improvements

- [x] https://github.com/dotnet/sdk/issues/31281

### Reference Apps/Guidance improvements

- [ ] https://github.com/dotnet-architecture/eShopOnContainers/issues/2070

**Comment by amcasey** [comment]
@glennc Do we want to close this and make a new one for 9.0?
