### ISSUE TITLE
Any plans to add Token generation back into ASP.NET Core

### ISSUE THREAD

**Issue by cyclr-adrian** [dotnet/aspnetcore#47256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to migrate from an existing .NET Framework 4.8 MVC project and Web API to .NET 6.

The current .NET Framework implementation uses the built-in OWIN Auth to generate access tokens for the `client_credential` flow, to allow access to the API using custom providers.

There is currently no built-in solution in .NET 6 to generate tokens, see: [https://developer.okta.com/blog/2018/03/23/token-authentication-aspnetcore-complete-guide#generate-tokens-for-authentication-in-aspnet-core](https://developer.okta.com/blog/2018/03/23/token-authentication-aspnetcore-complete-guide#generate-tokens-for-authentication-in-aspnet-core) 

At the moment the only solution(s) is to use a third party like: 

* Duende Identity Server (too expensive)
* OpenIddict (too complicated to implement, lack of support and documentation, in my opinion)

### Describe the solution you'd like

Are there any plans to add Token generation back into ASP.NET Core in .NET 8?

**Comment by davidfowl** [comment]
Your best option for a straight migration using the oauth2 is using one of the 2 options you mentioned above.
