### ISSUE TITLE
Theme:  JS Frontends with .NET Backends 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/aspnetcore#47254]
A continued theme in .NET is to enable developers' smooth integration points between their .NET backend APIs and JavaScript SPA frontend. In .NET 8, we plan to improve in the following areas. 
:wrench: - tooling   :construction: - engineering   :notebook: - documentation

_**Note**: If you are looking for anything Blazor united, we have another [issue](https://github.com/dotnet/aspnetcore/issues/46636) documenting our .NET 8 plans in that area.

### Identity, Authentication and Authorization :construction:
In .NET 8 we want to improve our current auth experience by providing a simpler and well documented experience for building secure web applications. Our goal during .NET 8 is to make progress on some of the [ASP.NET Core SPA with Authentication issue](https://github.com/dotnet/aspnetcore/issues/42158) 

- [x] https://github.com/dotnet/aspnetcore/issues/47286

### Intergration with 3rd party asset management solutions. :construction: :wrench:
Simplify the integration of 3rd party tooling for static web assets. There are number of challenges that our developers experience when integrating third-party tools that produce or transform web assets as part of the build process. Client web assets often need to be built or processed using tools like npm and webpack. But integrating a client web asset build pipeline into the build process of a Razor Class Library can be challenging. In .NET 8 we want to improve this experience by productizing the ASP.NET Core Client Asset library.

- [ ] https://github.com/dotnet/aspnetcore/issues/38445

### Documentation and Samples :notebook:

- [ ]  [.NET backends with popular JS SPA frameworks:  React, Vue, and Angular](https://learn.microsoft.com/en-us/visualstudio/javascript/quickstart-ide-orientation-js)
- [ ]  [Configuring your Auth in your application](https://github.com/dotnet/AspNetCore.Docs/issues/29452).
- [ ]  Leveraging modern API architecture with GraphQL

**Comment by mkArtakMSFT** [comment]
@LadyNaggaga I think we should close this already. @danroth27 FYI
