### ISSUE TITLE
Refer `ActionResult` and `ActionResult<T>` from Blazor WebAssemly projects

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [dotnet/aspnetcore#47252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm writing a function to dynamically build the route for my controller's action in a Blazor WebAssembly application and also get strong typed controllers / actions method names in my development experience.
I already can do this, except if I try to return `ActionResult` in my controllers.

For example: This is the controller in the `Server` project:
```cs
[ApiController]
[Route("[controller]/[action]")]
public class WeatherForecastController : ControllerBase, IWeatherForecastController
{
    public ActionResult<List<string>> GetList()
    {
        return new List<string>();
    }
}
```

This is the interface in the `Shared` project:
```cs
public interface IWeatherForecastController
{
    ActionResult<List<string>> GetList();
}
```

According to this and [this](https://github.com/dotnet/aspnetcore/issues/26724), and [this](https://github.com/dotnet/aspnetcore/issues/27373), this is not possible because I can't refer MVC binaries from a Blazor WebAssembly.

The current workaround I'm using is that my controllers return my own specific implementation of `ActionResult`.

### Describe the solution you'd like

To create a library like `Microsoft.AspNetCore.Mvc.Abstractions` that can be referenced by both Blazor WebAssembly and by the Hosted Server.

**Comment by javiercn** [comment]
@FelipeCostaGualberto thanks for contacting us.

Is there a particular reason for you to reference the action result in your interface? 

Would it work if instead of implementing the interface on your controller directly, you created a separate service and implemented the interface there, without having to reference the action result and just use that from your controller instead?

**Comment by FelipeCostaGualberto** [comment]
Thanks for the answer, @javiercn 

That could be done, but it means writing more code to achieve the various possibile `ActionResult` outcomes - `Ok`, `NotFound`, `Created`, etc. I wish controller's `ActionResult` return methods could be "seen" by my client via interface, so in addition to the benefits above, I could refactor, strong type, dynamically build url's.
Of course, you also could point that trying to use the controllers as services is anti-pattern.

This is what I currently do in my Blazor WebAssembly components - with my own "FelipeResult" implementation:
```cs
[Inject] FelipeService<IWeatherForecastController> Service { get; set; }

protected override async Task OnInitializedAsync()
{
    var result = await Service.Post(x => x.GetList()); // result is FelipeResult<List<string>>
    if(!result.Success) { ... };

    var list = result.Value; // list is a List<string>
}
```

I can use this kind of code only if the method in `IWeatherForecastController` is declared like `FelipeResult<List<string>>> GetList()`, but I can't use it if it is declared like `ActionResult<List<string>> GetList()`.

**Comment by FelipeCostaGualberto** [comment]
Hi @javiercn , thanks for your time analyzing this thread.

I didn't know about the `IActionResultTypeMapper` interface. I will give it a try.

For now, I kindly ask to close this thread.
