### ISSUE TITLE
How to configure specific paths for an endpoint different from others?

### ISSUE THREAD

**Issue by jtheisen** [dotnet/aspnetcore#47257]
This is a question about endpoint routing.

I have a catch-all endpoint (in my case it's the Blazor Server endpoint) and want it generally to require authorization:

```c#
app.MapFallbackToPage("/_Host").RequireAuthorization();
```

That works, but there is one special page inside the Blazor Server app that should be public (and that won't link to the rest). I now tried to map part of the paths as a different endpoint:

```c#
app.Map("/public", app2 => app.MapFallbackToPage("/_Host"));

app.MapFallbackToPage("/_Host").RequireAuthorization();
```

That gives me an exception:

```
InvalidOperationException: Using ExpandEndpoint requires that the replaced endpoint have a unique priority. The following endpoints were found with the same priority: ...
```

I'm asking this question also to more generally understand this endpoint routing, specifically how I can fork a given endpoint. I'm not just looking for a workaround, such as allowing the Blazor Server app always unauthenticated and redirect from there if no user is present.

**Comment by Tratcher** [comment]
> app.Map("/public", app2 => app.MapFallbackToPage("/_Host"));

Shouldn't that be app2?

> app.Map("/public", app2 => app2.MapFallbackToPage("/_Host"));

**Comment by jtheisen** [comment]
Uh, yes. However, that doesn't quite compile as `MapFallbackToPage` in on `IEndpointRouteBuilder`.

I just tried

```c#
app.Map("/public", app2 => app2.UseEndpoints(e => e.MapFallbackToPage("/_Host")));
```

but that gives me the exact same exception.

**Comment by javiercn** [comment]
@jtheisen thanks for contacting us.

`MapFallback...` APIs use dynamic routing. That means that there is a "stub" endpoint defined that gets replaced dynamically during the request via a MatcherPolicy for an actual real endpoint. `MapFallbackToPage` runs code to select the page dynamically and replaces the endpoint for the endpoint that renders the page.

You could write a MatcherPolicy that runs after the dynamic endpoint selection, checks the request path, the selected endpoint and adds the metadata to the Endpoint.

Check how MatcherPolicy is defined [here](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.RazorPages/src/Infrastructure/DynamicPageEndpointMatcherPolicy.cs)

**Comment by jtheisen** [comment]
@javiercn Is this really no simpler way to map a certain path to a page? It seems like something that should be trivial.

**Comment by javiercn** [comment]
@jtheisen unfortunately, ASP.NET Core has no special knowledge of the Blazor server routes. That's something we are potentially changing in .NET 8.0

**Comment by jtheisen** [comment]
@javiercn That's ok, I'm not enquiring about anything about Blazor particularly.

I just want to manually map certain paths to a page without authorization and the rest to the same page with authorization.

I'm fine with having to duplicate the paths.

I'm sure this general problem will come up in other contexts, and I know this would have been simple in the pre-endpoint-routing world.

**Comment by javiercn** [comment]
@jtheisen I am a bit confused. Why are you using MapFallback for then? It's meant to be used to catch any unmatched route.

**Comment by jtheisen** [comment]
@javiercn Because that's the only way I know how to force the forked pipeline to route to a specific page.

I just want to fork the routing pipeline into two, one for specific paths not using authentication and the rest, but both ending at the same page `/_Host`.

**Comment by jtheisen** [comment]
I'm a bit confused and sad about the reform to endpoint routing. In the pre-endpoint-routing world, I could have configured a request pipeline conceptually like this:

- if path "/public"
  - then
    - route to page "/_Host"
  - else
    - authenticate
    - route to page "/_Host"

This worked because the request pipeline was entirely in my hands. Now there is "endpoint routing" that apparently works only on a single, global list of endpoints where each endpoint wants to know things like authentication for all cases.

The request pipeline can still be forked, but since all endpoints must be in the single, global list, that's no longer all that useful.

It seems to me that all flexibility is now lost. Or am I not getting something here?

**Comment by jtheisen** [comment]
Ah, that's promising; there's not just one global collection of endpoints after all.

I tried something like this but I always had a "/_Host" endpoint globally as well - I think that's why it didn't work, the forked paths still inherit endpoints in some way.

So I still haven't really a clear picture of in what way those endpoints are inherited in the forks, but it's probably best I brood on this myself first for now.

Thanks for the help, this was a particularly good experience here.
