### ISSUE TITLE
SignalR - Clients Not Receiving Messages in Integration Tests

### ISSUE THREAD

**Issue by hkashif** [dotnet/aspnetcore#47260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Normal Operation:** When running the project, and connecting an external SignalR client, the client receives messages as expected.

**Tests - API Call:** When running an integration test, and connecting a client for testing, it doesn't work. I can see during debugging that `_proxy._lifetimeManager._connections` is empty in the controller (what sends the signalHub message to clients).

**Tests - Direct Service Call:** Interestingly, I created another test where I get an instance of the HubContext directly from the Test Web Application Factory. Sending a message through this HubContext instance works, and the message is received by the test client.

### Expected Behavior

**Tests - API Call:** When running an integration test, and connecting a client for testing, after I trigger the API that sends a signalR message to connected clients, I expect the clients to receive the message. And I, accordingly, expect to see the right number of connections in `_proxy._lifetimeManager._connections`  when debugging.

### Steps To Reproduce

Here is a minimal project that reproduces the issue: [https://github.com/hkashif/signalr-integration-tests](https://github.com/hkashif/signalr-integration-tests)

There are two tests as described earlier:
- DirectContextCallTest: Gets HubContext from factory -- Passes
- ApiTest: Fails

### .NET Version

6.0.400

### Anything else?

**Target Framework:** net6.0
**IDE:** VS Code

`dotnet --info`: 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by BrennanConroy** [comment]
Is this because you're actually creating a new test factory in
```
factory
.WithWebHostBuilder(builder =>
{
    builder.ConfigureTestServices(services =>
    {
        services.AddMvc().AddApplicationPart(typeof(Startup).Assembly);
    });
})
.CreateClient();
```

So the controller endpoint is a different server instance than the signalr endpoing?

**Comment by hkashif** [comment]
Yes. I just realized that. Thanks!
