### ISSUE TITLE
Blazor Custom Elements Documentation Vanished

### ISSUE THREAD

**Issue by Aeroverra** [dotnet/aspnetcore#47273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documentation for .Net 7 Blazor Custom Elements went missing.  Searched for a good hour and could not find the official documentation. Finally found this link https://devblogs.microsoft.com/dotnet/announcing-asp-net-core-in-dotnet-7/ that refrenced it and was able to do a archive lookup. 

Here is the original version. It appears this is not the only thing that disappeared. 
https://web.archive.org/web/20221110164254/https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements

Here is the official link
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements

### Expected Behavior

Steps outlining how to use blazor custom elements.

### Steps To Reproduce

https://web.archive.org/web/20221110164254/https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements

### .NET Version

7

**Comment by javiercn** [comment]
@Aeroverra thanks for contacting us.

@guardrex can you take a look at figure out what happened here?

**Comment by guardrex** [comment]
Moved to a new topic because we had negative reader feedback on the length of the *Components* overview. It grows and grows ... ***and GROWS*** 👺 ... eventually, we need to carve pieces out into new topics to address it.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?view=aspnetcore-7.0#blazor-custom-elements

**Comment by guardrex** [comment]
I would attempt to get a redirect in place, but I don't think that redirecting for a section is a docs build system feature. Our redirects work ***for articles*** that change location, not sections. I'll inquire with docs management to see if it's even possible, but I've never seen it even attempted in the last five years.

**Comment by mkArtakMSFT** [comment]
Thanks for confirming this, @guardrex.
It makes sense for this to be a separate article. People hopefully will start finding the new page more often. And we should try to use the new link from wherever we used it. Perhaps adding the link (only) from the previous article would help.

**Comment by Aeroverra** [comment]
Thanks for the information, I definitely think a redirect would help a lot especially as Google search seems to get more and more flaky as time goes on. Usually my natural instinct is to avoid the on site search as they are usually worse but Ill give it a try on the docs website the next time I run into this.

**Comment by guardrex** [comment]
@mkArtakMSFT ... This one can be closed as resolved. We're unable at this time to redirect from sections to new articles, as that's not a docs build system/DocFX feature.
