### ISSUE TITLE
Consider in-repo documentation for diagnostic codes used in repo

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#47287]
Follow-up from https://github.com/dotnet/aspnetcore/pull/47118#discussion_r1131714773.

The runtime repo documents diagnostic codes used by their libraries in: https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md

We currently use diagnostic codes in several places in the repo:

- Source generators
- MVC analyzers
- Framework analyzers

But don't have a central location that documents all of them.

**Comment by mkArtakMSFT** [comment]
@captainsafia I think this would be a backlog candidate

**Comment by captainsafia** [comment]
> @captainsafia if someone wanted to take this on, is the list exactly what is in the various files named DiagnosticDescriptors.cs ? or other things?

The best way to do this would be to do a lookup for everywhere the type `DiagnosticDescriptors` is used in the repo and capture the codes and messages into a list.

> @captainsafia I think this would be a backlog candidate.
I even wonder if this would be a good fit for a community to help with. If you agree, feel free to add the help-wanted label.

Backlog + `help-wanted` seems fine.

**Comment by divyeshio** [comment]
I would like to work on this, can you please assign it to me?

**Comment by captainsafia** [comment]
@divyeshio You may want to get started with the diagnostic IDs that we use in the analyzers that are shipped as part of the targeting pack. You can find those in [this source file](https://github.com/dotnet/aspnetcore/blob/main/src/Framework/AspNetCoreAnalyzers/src/Analyzers/DiagnosticDescriptors.cs). The Markdown file will live in our docs directory [here](https://github.com/dotnet/aspnetcore/tree/main/docs).
