### ISSUE TITLE
QuickGrid responsive table support

### ISSUE THREAD

**Issue by mehmet-erdogdu** [dotnet/aspnetcore#47294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I want to use horizontal scroll bar. Can you add table-responsive feature like in bootstrap

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

This can be achieved today using CSS. If you take a look at [this example](https://aspnet.github.io/quickgridsamples/virtualizing/) and resize your browser window to be very small, a horizontal scrollbar appears.
