### ISSUE TITLE
Unable to use SpaProxy inside Codespaces

### ISSUE THREAD

**Issue by ejsmith** [dotnet/aspnetcore#47299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to get Codespaces to work with my application that uses SpaProxy, but it does not work due to the local dev server url being different from where the middleware needs to redirect my application since Codespaces creates port forwarded urls for your application.

### .NET Version

7.0.202

**Comment by javiercn** [comment]
@ejsmith thanks for contacting us.

We see that you've sent us a PR. Is there a reason why this needs a separate property instead of changing the ServerUrl property already available?

**Comment by ejsmith** [comment]
Yes, I stated the reason in the issue. When running in codespaces, the local dev server runs at https://localhost:7153, but codespaces does port forwarding so you can access your app from outside of the codespace and that is the URL that the app needs to redirect to. It needs to have both so it can start and check locally that the server is running and then the browser needs to redirect to the https://{codespace-name}.preview.app.github.dev site.
