### ISSUE TITLE
Respect client's header table size settings

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#4729]
Follow-up to https://github.com/aspnet/KestrelHttpServer/issues/2816. 

Currently our encoder does not do any header compression. If we decide to do response header compression, we will need to take into account the client's settings for header table size.

**Comment by JamesNK** [comment]
I'm doing this with https://github.com/dotnet/aspnetcore/issues/4715

**Comment by JamesNK** [comment]
I believe this has been done here: https://github.com/dotnet/aspnetcore/pull/20058/files#diff-259f4a7dbb73dd85ca5799a61ac2754fR753

@Tratcher @halter73
