### ISSUE TITLE
ASP.NET Core does not respect caching headers for images

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/aspnetcore#47303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have added this middleware:

```
app.Use(async (context, next) =>
{
    if (context.Request.Path.ToString().Contains("image/resize"))
    {
        context.Response.Headers["Cache-Control"] = "max-age=31536000";
    }
    else
    {
        context.Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
        context.Response.Headers["Pragma"] = "no-cache";
        context.Response.Headers["Expires"] = "0";
    }
    await next.Invoke();
});
```

It works for the `else` block. But for the `if` block it does not work. The default `cache-control: public,max-age=30` is seen only.

### Expected Behavior

I expect the cache control specified to be applied. Or at least I should see a warning on why it's discarted.

### Steps To Reproduce

Reproduction repo:

https://github.com/Nefcanto/ApiNotCachingImages

- On Ubuntu 22.04)
- `git clone`
- `cd ApiNotCachingImages`
- `dotnet restore`
- `sudo dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary`
- Go to the browser
- Go to this link
  - `/image/resize/container/9f59284a-7c61-41c2-9999-691fb4d96e13`
- See the Network tab in DevTools
- Refresh the page, cache control is not applied.

### .NET Version

7.0.201

**Comment by mitchdenny** [comment]
Hi @Nefcanto, this doesn't match what I'm seeing, I used postman and this is what I see in my response:

![image](https://user-images.githubusercontent.com/513398/226179073-159fa008-7d9f-47a3-ab2a-6f8eff360722.png)

Here is the code I used based on the middleware code you shared:

```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.Use(async (context, next) =>
{
    if (context.Request.Path.ToString().Contains("image/resize"))
    {
        context.Response.Headers["Cache-Control"] = "max-age=31536000";
    }
    else
    {
        context.Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
        context.Response.Headers["Pragma"] = "no-cache";
        context.Response.Headers["Expires"] = "0";
    }
    await next.Invoke();
});

app.MapGet("/", () => "Hello World!");
app.MapGet("/image/resize", () => $"{DateTime.Now}");

app.Run();
```

I used Postman to hit the endpoint and observed the correct response in the header as you can see from the screenshot above.

**Comment by Nefcanto** [comment]
@mitchdenny thank you. So the code works. But not in my project. Something must have overriden it. Is there a way for me to debug it?

I mean, I have changed the middleware position many times and I see no success. I have no idea how can I debug it.

**Comment by Nefcanto** [comment]
@mitchdenny, I realized that you have not returned an actual image in the `image/resize`. Maybe that causes the issue. Can you please test with the repo I have shared? I would make it as simple as you want.

**Comment by mitchdenny** [comment]
Thanks for posting that repo and the instructions however it isn't really usable as a minimal reproduction of the error. There are several issues:

1. Requires someone to do a restore with `sudo` which would require a more extensive review of your code before anyone would be willing to run it on their machine.
2. Has a bunch of hard coded paths to directories that do not exists.
3. Depends on `convert` utility program being present on machine in order to work.

Ideally a minimal repro should be something we can just clone down and run and has just the code needed to illustrate the problem (this helps demonstrate that you've eliminated all other possible causes of the issue and you know that the issue is in the ASP.NET runtime code itself).

Happy to continue debugging the issue with you if you can post a **minimal** repro.

**Comment by mitchdenny** [comment]
@Nefcanto - I just noticed on your MVC action method that you set `[ResponseCache(Duration = 30)]`. What is happening here is that the middleware you are injecting here is setting the CacheControl headers before the MVC action and associated filters are executed. By putting that attribute on the action method you are replacing the cache control header you placed on it.

Remove it and bingo - you get the expected cache control header.

**Comment by Nefcanto** [comment]
@mitchdenny thank you so much. I was trying to create a minimal reproducible example as you have described above, but they all would work.

However, I still think that we should have a way to debug this. If I had a way to troubleshoot this, I would find the issue myself.

For example, how about a CSS-like graph or indented report of why these headers are there, by using `dotnet run --verbose`:

```
Cache-Control
    Middleware.cs => max-age: 31536000
    ImageController.cs => max-age: 30
```

If I could have this report, I would have immediately found the issue of course.

Is it possible to suggest this as a new feature?

**Comment by Nefcanto** [comment]
@mitchdenny thank you so much. I was trying to create a minimal reproducible example as you have described above, but they all would work.

However, I still think that we should have a way to debug this. If I had a way to troubleshoot this, I would find the issue myself.

For example, how about a CSS-like graph or indented report of why these headers are there, by using `dotnet run --verbose`:

```
Cache-Control
    Middleware.cs => max-age: 31536000
    ImageController.cs => max-age: 30
```

If I could have this report, I would have immediately found the issue of course.

Is it possible to suggest this as a new feature?

**Comment by mitchdenny** [comment]
Sure - if you would like to create a feature request for something like this you can use the following template:

https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=&template=20_feature_request.yml

**Comment by Nefcanto** [comment]
@mitchdenny I'm so grateful for your help. I created the feature-request issue.
