### ISSUE TITLE
Static web assets SDK depends on targets defined in Razor SDK

### ISSUE THREAD

**Issue by maraf** [dotnet/aspnetcore#47314]
The static web assets SDK depends on `ResolveRazorComponentInputs` and `ResolveRazorGenerateInputs` defined in Razor SDK

https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets#L125

```
Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(125,113): error MSB4057: The target "ResolveRazorComponentInputs"
```

**Comment by javiercn** [comment]
@maraf good catch. I think Mackinnon is already aware of it. We can probably change this to enable scoped css conditionally on `<UsingMicrosoftNETSdkRazor>true</UsingMicrosoftNETSdkRazor>`
