### ISSUE TITLE
Asset size limit warnings when building in CodeSpaces

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#47324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create a new CodeSpace for this repo and run `eng/build.sh - configuration release`.  You get errors like

```
/workspaces/aspnetcore/eng/targets/Npm.Common.targets(92,5): error : in asset size limit: The following asset(s) exceed the recommended size limit (120 KiB). [/workspaces/aspnetcore/src/Components/Web.JS/Microsoft.AspNetCore.Components.Web.JS.npmproj]
This can impact web performance.
Assets:
   blazor.server.js (133 KiB)

/workspaces/aspnetcore/src/Components/WebAssembly/WebAssembly.Authentication/src/Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj(78,5): error : in asset size limit: The following asset(s) exceed the recommended size limit (120 KiB).
This can impact web performance.
Assets:
   AuthenticationService.js (285 KiB)
```

### Expected Behavior

No errors from yarn.

### Steps To Reproduce

Create a new CodeSpace for this repo and run `eng/build.sh - configuration release`.  Mitigation: `/p:IgnoreYarnWarnings=true`

### Anything else?

You might also get errors about `microsoft.internal.runtime.aspnetcore.transport` not having xml files - they're unrelated.

**Comment by amcasey** [comment]
FYI @javiercn

**Comment by javiercn** [comment]
@amcasey we are aware of these. I think we are using the default values on our build and never bothered to change them ¯\_(ツ)_/¯

That normally is a warning and should not impact the build. Is it giving you problems?

**Comment by amcasey** [comment]
@javiercn I'm pretty sure it failed my build or I would have just ignored it.

**Comment by wtgodbe** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/37398, https://github.com/dotnet/aspnetcore/issues/11592

**Comment by mkArtakMSFT** [comment]
Parking it in 9 to spend a few hours to see if we can come up with a good solution. If not, we'll deprioritize then.

**Comment by mkArtakMSFT** [comment]
Closing as we've switched bundlers and this was coming from the old bundler.
