### ISSUE TITLE
RequestDelegateFactoryTests migration

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#47345]
As part of the implementation work for Request Delegate Generator (RDG) we want to make sure that we achieve the same test coverage as Request Delegate Factory (RDF). Below is a tick-box list of all the unit tests (`[Fact]` and `[Theory]`) in the `RequestDelegateFactoryTests.cs` source file that we need to evaluate for migration. As we work through these migrating them over to `RequestDelegateCreationTests.cs` we'll be improving out RDG test coverage and ensuring consistency between the RDG and RDF approaches.

# Pending migration

- [ ] RequestDelegateHandlesDoesNotHandleArraysFromQueryStringWhenBodyIsInferred
- [ ] RequestDelegateHandlesOptionalArraysFromNullQueryString
- [ ] RequestDelegateHandlesNullableStringValuesFromExplicitQueryStringSource
- [ ] RequestDelegateHandlesNullableStringValuesFromExplicitQueryStringSourceForUnpresentedValues
- [ ] RequestDelegateCanAwaitValueTasksThatAreNotImmediatelyCompleted
- [ ] RequestDelegateThrowsForTryParsableFailuresIfThrowOnBadRequestWithNonOptionalArrays
- [ ] RequestDelegateRejectsEmptyBodyGivenExplicitFromBodyParameter
- [ ] Create_CombinesDefaultMetadata_AndMetadataFromReturnTypesImplementingIEndpointMetadataProvider
- [ ] Create_CombinesDefaultMetadata_AndMetadataFromTaskWrappedReturnTypesImplementingIEndpointMetadataProvider
- [ ] Create_CombinesDefaultMetadata_AndMetadataFromValueTaskWrappedReturnTypesImplementingIEndpointMetadataProvider
- [ ] Create_CombinesDefaultMetadata_AndMetadataFromParameterTypesImplementingIEndpointParameterMetadataProvider
- [ ] Create_CombinesDefaultMetadata_AndMetadataFromParameterTypesImplementingIEndpointMetadataProvider
- [ ] Create_CombinesPropertiesAsParameterMetadata_AndTopLevelParameter
- [ ] RequestDelegatePopulatesFromBodyParameter
- [ ] RequestDelegateAllowsEmptyBodyStructGivenCorrectyConfiguredFromBodyParameter
- [ ] RequestDelegateRequiresServiceForAllImplicitFromServiceParameters
- [ ] RequestDelegateWithExplicitFromServiceParameters
- [ ] RequestDelegatePopulatesParametersFromServiceWithAndWithoutAttribute
- [ ] RequestDelegateUsesCustomIResult
- [ ] RequestDelegateThrowsInvalidOperationExceptionOnNullDelegate
- [ ] RequestDelegateHandlesRouteParamOptionality
- [ ] RequestDelegateHandlesBindAsyncOptionality
- [ ] RequestDelegateHandlesServiceParamOptionality
- [ ] CanSetParseableStringParamAsOptionalWithNullabilityDisability
- [ ] TreatsUnknownNullabilityAsOptionalForReferenceType
- [ ] CanExecuteRequestDelegateWithResultsExtension
- [ ] RequestDelegateCanProcessUriValues
- [ ] RequestDelegatePopulatesFromParameterListRecordUsesDefaultValue
- [ ] RequestDelegateFactory_AsParameters_SupportsNullableRequiredMember
- [ ] RequestDelegateFactory_AsParameters_SupportsRequiredMember_NullabilityDisabled
- [ ] BuildRequestDelegateThrowsArgumentNullExceptions
- [ ] SpecifiedEmptyRouteParametersThrowIfRouteParameterDoesNotExist
- [ ] CreateThrowsInvalidOperationExceptionWhenAttributeRequiresTryParseMethodThatDoesNotExist
- [ ] CreateThrowsInvalidOperationExceptionGivenUnnamedArgument
- [ ] RequestDelegateFactoryThrowsForByRefReturnTypes
- [ ] BuildRequestDelegateThrowsInvalidOperationExceptionGivenFromBodyOnMultipleParameters
- [ ] BuildRequestDelegateThrowsInvalidOperationExceptionForInvalidTryParse
- [ ] BuildRequestDelegateThrowsInvalidOperationExceptionForInvalidBindAsync
- [ ] BuildRequestDelegateThrowsInvalidOperationExceptionForInvalidParameterListConstructor
- [ ] BuildRequestDelegateThrowsNotSupportedExceptionForNestedParametersList
- [ ] BuildRequestDelegateThrowsNotSupportedExceptionForByRefParameters
- [ ] CreateDelegateThrows_WhenGetJsonTypeInfoFail
- [ ] BuildRequestDelegateThrowsInvalidOperationExceptionBodyAndFormParameters
- [ ] CreateThrowsNotSupportedExceptionIfIFormFileCollectionHasMetadataParameterName
- [ ] CreateThrowsNotSupportedExceptionIfIFormCollectionHasMetadataParameterName
- [ ] RequestDelegateThrowsWhenNullableParameterList
- [ ] RequestDelegateThrowsWhenParameterNameConflicts
- [ ] Create_DoesNotAddDelegateMethodInfo_AsMetadata
- [ ] RDF_CanAssertOnEmptyResult
- [ ] Create_DoesNotAddAnythingBefore_ThePassedInEndpointMetadata
- [ ] Create_DoesNotAddDelegateAttributes_AsMetadata

# Already migrated

- [x] RequestDelegatePopulatesFromRouteParameterBasedOnParameterName (see: https://github.com/dotnet/aspnetcore/pull/47347)
- [x] RequestDelegatePopulatesFromRouteParameterBased_FromParameterList
- [x] CreatingDelegateWithInstanceMethodInfoCreatesInstancePerCall (no migration: RDF specific test)
- [x] Returns400IfNoMatchingRouteValueForRequiredParam
- [x] RequestDelegatePopulatesUnattributedTryParsableParametersFromRouteValue (see: https://github.com/dotnet/aspnetcore/pull/47347)
- [x] RequestDelegateHandlesArraysFromQueryString
- [x] RequestDelegateHandlesArraysFromExplicitQueryStringSource
- [x] RequestDelegateHandlesStringValuesFromExplicitQueryStringSource
- [x] RequestDelegateLogsStringValuesFromExplicitQueryStringSourceForUnpresentedValuesFailuresAsDebugAndSets400Response
- [x] RequestDelegateUsesTryParseOverBindAsyncGivenExplicitAttribute
- [x] RequestDelegateUsesBindAsyncFromImplementedInterface
- [x] RequestDelegateLogsTryParsableFailuresAsDebugAndSets400Response
- [x] RequestDelegateThrowsForTryParsableFailuresIfThrowOnBadRequest
- [x] RequestDelegateThrowsForTryParsableFailuresIfThrowOnBadRequestWithArrays
- [x] RequestDelegateLogsBindAsyncFailuresAndSets400Response
- [x] RequestDelegateThrowsForBindAsyncFailuresIfThrowOnBadRequest
- [x] RequestDelegateLogsSingleArgBindAsyncFailuresAndSets400Response
- [x] RequestDelegateThrowsForSingleArgBindAsyncFailuresIfThrowOnBadRequest
- [x] BindAsyncWithBodyArgument
- [x] BindAsyncRunsBeforeBodyBinding
- [x] RequestDelegatePopulatesFromQueryParameter_FromParameterList
- [x] RequestDelegatePopulatesFromHeaderParameter_FromParameterList
- [x] RequestDelegatePopulatesFromImplicitRawBodyParameter (https://github.com/dotnet/aspnetcore/pull/47377)
- [x] RequestDelegatePopulatesFromExplicitRawBodyParameter (https://github.com/dotnet/aspnetcore/pull/47377)
- [x] RequestDelegatePopulatesFromImplicitRawBodyParameterPipeReader (https://github.com/dotnet/aspnetcore/pull/47377)
- [x] RequestDelegatePopulatesFromExplicitRawBodyParameterPipeReader (https://github.com/dotnet/aspnetcore/pull/47377)
- [x] InferMetadata_ThenCreate_CombinesAllMetadata_InCorrectOrder
- [x] InferMetadata_PopulatesAcceptsMetadata_WhenReadFromForm
- [x] #48630
- [x] Create_AllowsRemovalOfDefaultMetadata_ByReturnTypesImplementingIEndpointMetadataProvider
- [x] Create_AllowsRemovalOfDefaultMetadata_ByTaskWrappedReturnTypesImplementingIEndpointMetadataProvider
- [x] Create_AllowsRemovalOfDefaultMetadata_ByValueTaskWrappedReturnTypesImplementingIEndpointMetadataProvider
- [x] Create_AllowsRemovalOfDefaultMetadata_ByParameterTypesImplementingIEndpointParameterMetadataProvider
- [x] Create_AllowsRemovalOfDefaultMetadata_ByParameterTypesImplementingIEndpointMetadataProvider
- [x] Create_SetsApplicationServices_OnEndpointMetadataContext
- [x] Create_SetsApplicationServices_OnEndpointParameterMetadataContext
- [x] Create_DiscoversMetadata_FromParametersImplementingIEndpointParameterMetadataProvider
- [x] Create_DiscoversMetadata_FromParametersImplementingIEndpointMetadataProvider
- [x] Create_DiscoversEndpointMetadata_FromReturnTypeImplementingIEndpointMetadataProvider
- [x] Create_DiscoversEndpointMetadata_FromTaskWrappedReturnTypeImplementingIEndpointMetadataProvider
- [x] Create_DiscoversEndpointMetadata_FromValueTaskWrappedReturnTypeImplementingIEndpointMetadataProvider
- [x] RequestDelegateRejectsEmptyBodyGivenImplicitFromBodyParameter
- [x] RequestDelegateLogsIOExceptionsAsDebugDoesNotAbortAndNeverThrows
- [x] RequestDelegateLogsJsonExceptionsAsDebugAndSets400Response
- [x] RequestDelegateThrowsForJsonExceptionsIfThrowOnBadRequest
- [x] RequestDelegateLogsMalformedJsonAsDebugAndSets400Response
- [x] RequestDelegateThrowsForMalformedJsonIfThrowOnBadRequest
- [x] RequestDelegatePopulatesHttpContextParameterWithoutAttribute
- [x] RequestDelegatePopulatesHttpContextParameterWithoutAttribute_FromParameterList
- [x] RequestDelegatePassHttpContextRequestAbortedAsCancellationToken
- [x] RequestDelegatePassHttpContextUserAsClaimsPrincipal
- [x] RequestDelegatePassHttpContextUserAsClaimsPrincipal_FromParameterList
- [x] RequestDelegatePassHttpContextRequestAsHttpRequest
- [x] RequestDelegatePassHttpContextRequestAsHttpRequest_FromParameterList
- [x] RequestDelegatePassesHttpContextRresponseAsHttpResponse
- [x] RequestDelegatePassesHttpContextRresponseAsHttpResponse_FromParameterList
- [x] RequestDelegateWritesComplexReturnValueAsJsonResponseBody
- [x] RequestDelegateWritesComplexStructReturnValueAsJsonResponseBody
- [x] RequestDelegateWritesMembersFromChildTypesToJsonResponseBody
- [x] RequestDelegateWritesMembersFromChildTypesToJsonResponseBody_WithJsonPolymorphicOptions
- [x] RequestDelegateWritesMembersFromChildTypesToJsonResponseBody_WithJsonPolymorphicOptionsAndConfiguredJsonOptions
- [x] RequestDelegateWritesJsonTypeDiscriminatorToJsonResponseBody_WithJsonPolymorphicOptions
- [x] RequestDelegateWritesAsJsonResponseBody_WithJsonSerializerContext
- [x] RequestDelegateWritesStringReturnValueAndSetContentTypeWhenNull
- [x] RequestDelegateWritesStringReturnDoNotChangeContentType
- [x] RequestDelegateWritesIntReturnValue
- [x] RequestDelegateWritesBoolReturnValue
- [x] RequestDelegateWritesNullReturnNullValue
- [x] RequestDelegateHandlesQueryParamOptionality
- [x] RequestDelegateHandlesBodyParamOptionality
- [x] AllowEmptyOverridesOptionality
- [x] RequestDelegateRejectsNonJsonContent
- [x] RequestDelegateWithBindAndImplicitBodyRejectsNonJsonContent
- [x] RequestDelegateLogsIOExceptionsForFormAsDebugDoesNotAbortAndNeverThrows
- [x] RequestDelegateLogsMalformedFormAsDebugAndSets400Response
- [x] RequestDelegateThrowsForMalformedFormIfThrowOnBadRequest
- [x] RequestDelegatePopulatesFromIFormFileCollectionParameter
- [x] RequestDelegatePopulatesFromIFormFileCollectionParameterWithAttribute
- [x] RequestDelegatePopulatesFromIFormFileParameter
- [x] RequestDelegatePopulatesFromOptionalIFormFileParameter
- [x] RequestDelegatePopulatesFromMultipleRequiredIFormFileParameters
- [x] RequestDelegatePopulatesFromOptionalMissingIFormFileParameter
- [x] RequestDelegatePopulatesFromIFormFileParameterWithMetadata
- [x] RequestDelegatePopulatesFromIFormFileAndBoundParameter
- [x] RequestDelegateRejectsNonFormContent
- [x] RequestDelegateSets400ResponseIfRequiredFileNotSpecified
- [x] RequestDelegatePopulatesFromBothFormFileCollectionAndFormFileParameters
- [x] RequestDelegatePopulatesFromIFormFileParameterIfRequestContainsSecureHeader
- [x] RequestDelegatePopulatesFromIFormFileParameterIfRequestHasClientCertificate
- [x] RequestDelegatePopulatesFromIFormCollectionParameter
- [x] RequestDelegatePopulatesFromIFormCollectionParameterWithAttribute
- [x] RequestDelegatePopulatesFromOptionalFormParameter
- [x] RequestDelegatePopulatesFromMultipleRequiredFormParameters
- [x] RequestDelegatePopulatesFromOptionalMissingFormParameter
- [x] RequestDelegatePopulatesFromFormParameterWithMetadata
- [x] RequestDelegatePopulatesFromFormAndBoundParameter
- [x] RequestDelegatePopulatesFromBothIFormCollectionAndIFormFileParameters
- [x] RequestDelegateSets400ResponseIfRequiredFormItemNotSpecified
- [x] RequestDelegatePopulatesTryParsableParametersFromForm
- [x] RequestDelegatePopulatesFromParameterList
- [x] RequestDelegatePopulatesFromMultipleParameterLists
- [x] RequestDelegatePopulatesFromParameterListAndSkipReadOnlyProperties
- [x] RequestDelegatePopulatesFromParameterListUsesDefaultValue
- [x] RequestDelegateFactory_InvokesFiltersButNotHandler_OnArgumentError
- [x] RequestDelegateFactory_InvokesFilters_OnDelegateWithTarget
- [x] RequestDelegateFactory_CanInvokeSingleEndpointFilter_ThatProvidesCustomErrorMessage
- [x] RequestDelegateFactory_CanInvokeMultipleEndpointFilters_ThatTouchArguments
- [x] RequestDelegateFactory_CanInvokeEndpointFilter_ThatUsesMethodInfo
- [x] RequestDelegateFactory_CanInvokeEndpointFilter_ThatReadsEndpointMetadata
- [x] RequestDelegateFactory_CanInvokeSingleEndpointFilter_ThatModifiesBodyParameter
- [x] RequestDelegateFactory_CanInvokeSingleEndpointFilter_ThatModifiesResult
- [x] RequestDelegateFactory_CanInvokeMultipleEndpointFilters_ThatModifyArgumentsAndResult
- [x] CanInvokeFilter_OnTaskOfTReturningHandler
- [x] CanInvokeFilter_OnValueTaskOfTReturningHandler
- [x] CanInvokeFilter_OnVoidReturningHandler
- [x] CanInvokeFilter_OnHandlerReturningTasksOfStruct
- [x] RequestDelegateFactory_AsParameters_SupportsRequiredMember
- [x] Create_AddJsonResponseType_AsMetadata
- [x] Create_AddPlaintextResponseType_AsMetadata

# Not being migrated

- [x] ~~RequestDelegateInvokesAction~~ (no migration: RDF specific test)
- [x] ~~StaticMethodInfoOverloadWorksWithBasicReflection~~ (no migration: RDF specific test)
- [x] ~~NonStaticMethodInfoOverloadWorksWithBasicReflection~~ (no migration: RDF specific test)
- [x] ~~NullRouteParametersPrefersRouteOverQueryString~~ (no migration: RDF specific test)
- [X] ~~RequestDelegateFactory_InvokesFilters_OnMethodInfoWithNullTargetFactory~~ (no migration: RDF specific test)
- [X] ~~RequestDelegateFactory_InvokesFilters_OnMethodInfoWithProvidedTargetFactory~~ (no migration: RDF specific test)
- [X] ~~CanInvokeFilter_OnTaskModifyingHttpContext~~ (Test doesn't touch code gen and hard to migrate to shared infra)
- [x] ~~Create_CombinesAllMetadata_InCorrectOrder~~
- [x] ~~Create_FlowsRoutePattern_ToMetadataProvider~~
- [x] ~~Create_DoesNotInferMetadata_GivenManuallyConstructedMetadataResult~~
- [X] ~~Create_ReturnsSameRequestDelegatePassedIn_IfNotModifiedByFilters~~ (no migration: RDF specific test)
- [x] ~~Create_Populates_EndpointBuilderWithRequestDelegateAndMetadata~~

**Comment by mitchdenny** [comment]
@captainsafia as discussed.

**Comment by adityamandaleeka** [comment]
Closing; we believe the value of the remaining tests is fairly low. We'll instead file separate issues for any more issues discovered.
