### ISSUE TITLE
Consider using response headers & data padding

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#4735]
https://tools.ietf.org/html/rfc7540#section-6.1
"   DATA frames MAY also contain padding.  Padding can be added to DATA
   frames to obscure the size of messages.  Padding is a security
   feature; see Section 10.7."

"The HEADERS frame can include padding. "

https://tools.ietf.org/html/rfc7540#section-10.7
"   Padding can be used to obscure the exact size of frame content and is
   provided to mitigate specific attacks within HTTP, for example,
   attacks where compressed content includes both attacker-controlled
   plaintext and secret data (e.g., [BREACH])."

@blowdart

**Comment by davidfowl** [comment]
Should we close this?

cc @JamesNK
