### ISSUE TITLE
Gets the authorization attribute that has a higher priority on the Action

### ISSUE THREAD

**Issue by Uchiha-Peng** [dotnet/aspnetcore#47361]
In ASP.NET Core, when both the Controller and Action are marked with authorization attributes, the authorization attribute on the Action takes precedence. For example, if the Controller is marked with [Authorize] and the Action is marked with [AllowAnonymous], the request will be allowed even if the [Authorize] attribute on the Controller requires authentication. Similarly, if the Controller is marked with [AllowAnonymous] and the Action is marked with [Authorize], the request will require authentication.

However, when using a custom AuthenticationHandler or AuthorizationFilter, there is no convenient way to get the higher-priority attribute for the current request endpoint to determine whether it requires authentication. Currently, I use the following method, which works but looks clumsy. I wonder if there is a better way to do this. Thank you.

```
var currentEndpoint = Context.GetEndpoint();
            if (currentEndpoint == null)
                return AuthenticateResult.NoResult();
var authorizationAttribute = currentEndpoint.Metadata.Where(n => n.GetType().Namespace.Contains("Authorization")).LastOrDefault();
            if (authorizationAttribute == null || typeof(AllowAnonymousAttribute) == authorizationAttribute.GetType())
                return AuthenticateResult.NoResult();
... ... 

```

### Describe the solution you'd like

Provides an implementation idea for a method or specification

**Comment by davidfowl** [comment]
Why is your authentication handler looking at the authorization attribute? What are you trying to accomplish?

**Comment by Uchiha-Peng** [comment]
> Why is your authentication handler looking at the authorization attribute? What are you trying to accomplish?

In a custom AuthenticationHandler, validate the current request's endpoint. When the Controller is marked with [AllowAnonymous] and the Action is marked with [Authorize], the Endpoint requires identity authentication. When the Controller is marked with [Authorize] and the Action is marked with [AllowAnonymous], the Endpoint allows anonymous access. However, currently, the Controller's mark will be passed down to the Action, and I have to judge the priority myself, which is not very convenient.

**Comment by davidfowl** [comment]
The `AuthentictionHandler`'s job is to interact with the http request the manifest a ClaimsPrincipal. It's not supposed to look at the authorization attributes. The authorization attributes are then processed by the authorization system (or middleware which uses this system).

It sounds like you want to change how authorization is handled, not authentication.
