### ISSUE TITLE
ActionMethod URL generation creates invalid URLs when POST action has a different route template

### ISSUE THREAD

**Issue by mdzieg** [dotnet/aspnetcore#47375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think there is a problem with URL generation.

Assuming that we have the following controller:

    [Route("[action]")]
    public class Home : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
    
        [HttpGet]
        [Route("{number}")]
        public IActionResult Edit(int number)
        {
            
            return View();
        }
        
        [HttpPost]
        public IActionResult Edit()
        {
            return View();
        }
    }

The index view generated correct link to Edit action:

    <a asp-action="Edit" asp-all-route-data='new Dictionary<string, string>{{"number", "11"}}'>GO TO EDIT</a>

Which is `/Edit/11`.

But then in the edit view I am trying to create a form that should post to the same action, but there is no route parameter. So, the URL should be just `/Edit`. Instead, I get `/Edit/11` which does not reach appropriate action on the controller. I am generating forms in two ways and the result is the same:

    <div>
        <form asp-action="Edit" method="post">
            <button type="submit">submit</button>
        </form>
        
        @using (Html.BeginForm("Edit", "Home", FormMethod.Post))
        {
            <button type="submit">submit</button>
        }
    </div>

What is more, changing POST route template to:

        [HttpPost]
        [Route("something")]
        public IActionResult Edit()
        {
            return View();
        }

Causes link generated for GET to be `http://localhost:5253/Edit/something?number=11` which is wrong.

To me, it looks like a bug, but I might have overlooked something.

Please find the project under this link: [https://blindsend.io#5m4QCCyXKdchLEos4M1ang;GnFBHbs2xAap6QzxJadwFw==][1]

  [1]: https://blindsend.io#5m4QCCyXKdchLEos4M1ang;GnFBHbs2xAap6QzxJadwFw==

### Expected Behavior

Either links are generated correctly, that is (GET `/Edit/11` and POST `/Edit`) or if this routing setup is not correct (GET and POST route templates for the same action are meant to be the same), then there should be an exception thrown during app startup.

### Steps To Reproduce

Run the sample project, click the link on the root page to navigate to the Edit page and then view source to see generated URLs for forms on the page.

### .NET Version

7.0.202

### Anything else?

Sample project demonstrating issue: https://blindsend.io/#5m4QCCyXKdchLEos4M1ang;GnFBHbs2xAap6QzxJadwFw==

**Comment by javiercn** [comment]
@mdzieg thanks for contacting us.

Link generation will pick the first route that matches with the given set of values (ambient + provided). Templates have a "stable" order for link generation, but in general you should always provide a unique combination of route values for a given destination.

The correct thing to do in your case, is to use `Html.BeginForm("Edit", "Home", FormMethod.Post, new { number = "null"})` as that invalidates the existing ambient value and prevents "/Edit/{number}" from matching".

As to why you see different behaviors when you add "something" is because we internally need to have a stable order so that we can ensure that for a given configuration we always produce the same result when there are ambiguities.

As to why we do this instead of throwing, it is because it is better to get an incorrect link in your app at runtime than throw an exception that can prevent your app from working at all.

When in doubt, it's best to specify route values explicitly.

**Comment by mdzieg** [comment]
@javiercn Thank you for your answer.

I tried to use '@using (Html.BeginForm("Edit", "Home", FormMethod.Post, new { number = "null" }))' but it generates for me the same URL for action and adds extra attribute on the form tag which does not solve the problem.

`<form action="/Edit/11" method="post" number="null"> `

Regarding the second part of my question - adding "something" alone kind of works, so GET request is handled properly and post as well.

But I wanted to force aspnet to generate proper URL and added constraint:

```
[HttpGet]
    [Route("{number:int}")]
    public IActionResult Edit(int number)
    {
        
        return View();
    }
    
    [HttpPost]
    [Route("something")]
    public IActionResult Edit()
    {
        return BadRequest();
    }
```


This did not change how the URL is generated, so it was still '/Edit/something?number=11' but this time clicking the link resulted in 405 error. Generated URL should be '/Edit/11' and navigating there manually works just fine. And on that page POST links are generated correctly.

I am still not fully convinced it is a consistent behavior.

**Comment by javiercn** [comment]
@mdzieg thanks for the additional details.

There are "a million" overloads for BeginForm and my response was a bit ambiguous. Make sure you pass in the object to the one that accepts `routeValues`. I believe what's happening is that it picked the one that accepts htmlAttributes, which also takes an object.

**Comment by mdzieg** [comment]
@javiercn my apologies, I was too fast before and indeed that override was for html attributes. The correct one looks like this:

`@using (Html.BeginForm("Edit", "Home",new { number = (int?)null}, FormMethod.Post ))`

This part is more or less clear now for me. IMO there should be a way to be able to explicitly state what HTTP verb we generate URL for, so it would be more clear and we would not have to override context values.

But the other part of my question remains open. Is there a route template precedence taking part? So the POST route template is more concrete, thus selected first. But here as well, being able to state what verb I want to use would allow for precise URL generation. It should be optional and with GET as a default value.
