### ISSUE TITLE
Blazor Hybrid wrapper for hls.js fails to play hls media served on local LAN

### ISSUE THREAD

**Issue by phollida** [dotnet/aspnetcore#47379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an interesting bug with a Blazor Hybrid app that wraps the hls.js library.

My set up is this:

  ` 192.168.0.54                        192.168.1.16`
 `Test media sever>----------------------<Dev Machine`

On the Test media server, I have a Docker httpd:latest container running with _Header set Access-Control-Allow-Origin "*"_ enabled in httpd.conf.  No Firewall.  CORS is not the problem.  It is serving a sample hls video stream on `http://192.168.0.54:8080/video/out.m3u8`

On the dev machine I have another Docker httpd:latest serving up this simple html page straight from hls.js demo:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hls.js demo - basic usage</title>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script>

    <center>
      <h1>Hls.js demo - basic usage</h1>
      <video height="600" id="video" controls></video>
    </center>

    <script>
      var video = document.getElementById('video');
      if (Hls.isSupported()) {
        var hls = new Hls({
          debug: true,
        });
        hls.loadSource('http://192.168.0.54:8080/video/out.m3u8');
        hls.attachMedia(video);
        hls.on(Hls.Events.MEDIA_ATTACHED, function () {
          video.muted = true;
          video.play();
        });
      }
      // hls.js is not supported on platforms that do not have Media Source Extensions (MSE) enabled.
      // When the browser has built-in HLS support (check using `canPlayType`), we can provide an HLS manifest (i.e. .m3u8 URL) directly to the video element through the `src` property.
      // This is using the built-in support of the plain video element, without using hls.js.
      else if (video.canPlayType('application/vnd.apple.mpegurl')) {
        video.src = 'http://192.168.0.54:8080/video/out.m3u8';
        video.addEventListener('canplay', function () {
          video.play();
        });
      }
    </script>
  </body>
</html>
```

**This simple page works as expected and plays the sample HLS video from the media server**.

Next, I created a Blazor hybrid WinForms app to wrap this code [here ](https://github.com/phollida/HlsWinForm)

Essentially putting the JS in the index.html file (I added Hls Error Events for debugging):
```
<body>
<script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script>

<div id="app">Loading...</div>

<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>

<script src="_framework/blazor.webview.js"></script>
<script>
    function playVideo(source) {
        var video = document.getElementById('video');
        if (video.canPlayType('application/vnd.apple.mpegurl')) {
            video.src = source;
            video.play();
        } else
        if (Hls.isSupported()) {
            var hls = new Hls({
                debug: true,
            });
            hls.loadSource(source);
            hls.attachMedia(video);

            hls.on(Hls.Events.ERROR, function (event, data) {
                if (data.fatal) {
                    switch (data.type) {
                        case Hls.ErrorTypes.NETWORK_ERROR:
                            // try to recover network error
                            alert('fatal network error encountered, try to recover ' );
                            hls.startLoad();
                            break;
                        case Hls.ErrorTypes.MEDIA_ERROR:
                            alert('fatal media error encountered, try to recover');
                            hls.recoverMediaError();
                            break;
                        default:
                            // cannot recover
                            alert('fatal error encountered, cannot recover');
                            hls.destroy();
                            break;
                    }
                }
            });
            hls.on(Hls.Events.MEDIA_ATTACHED, function () {
                video.muted = true;
                video.play();
            });
        }
    }
</script>
</body>
```

And in the razor page I invoke this function using JSInterop

```
@inject IJSRuntime JSRuntime

<div class="container" style="alignment: center">
    <h1>Hls.js demo - basic usage @source</h1>
    <video height="600" id="video" controls></video>
    <button id="play" @onclick="PlayVideo">Play</button>
</div>

@code {
    string source = "http://192.168.0.54:8080/video/out.m3u8";
    private  void PlayVideo(object? state)
    {
        JSRuntime.InvokeVoidAsync("playVideo",  source);
        StateHasChanged();
    }
}
```

Upon clicking the Play button, HLS throws a NETWORK ERROR without putting a single packet on the wire (confirmed with wireshark), so something is going wrong internally between Blazor and JS.  The JS function is getting the correct source and ID, but it seems like there's a lower level issue that causes JS to throw a Network Error before getting to a HTTP request.  It feels like in internal host not found being thrown or an internal Blazor CORS check that fails for some reason.

It's not a server CORS issue because the HTML based page works fine and I can see the HTTP GET request on the wire.

It's not a firewall issue because I can play the media file no problems with _ffplay_ and _VLC_ form the Dev machine.  Have tried with firewalls off on the dev machine.

### Weird Behavior
This is where it gets weird. 

- If I use any other media address outside my dev LAN the Blazor app works fine.  So if I use the source address of  `https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8`  the Blazor wrapper will play the stream no problems. 
- If I serve the media files locally from the Dev machine (from the Docker httpd container) the Blazor wrapper works fine - so `http://localhost:8080/video/out.m3u8` and `http://127.0.0.1:8080/video/out.m3u8`work
- If I try and serve the media files from any other address on the LAN I get a NETOWRK ERROR caused by something internal to Blazor and JS.  I have tried a few addresses with the same result.

### Expected Behavior

The Blazor HLS wrapped code should function exactly the same as the HTML code and not only for some cases.

### Steps To Reproduce

https://github.com/phollida/HlsWinForm

provides the winform code.  Sorry that you'll need to set up another machine to reproduce the fault.

### Exceptions (if any)

- If I use any other media address outside my dev LAN the Blazor app works fine.  So if I use the source address of  `https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8`  the Blazor wrapper will play the stream no problems. 
- If I serve the media files locally from the Dev machine (from the Docker httpd container) the Blazor wrapper works fine - so `http://localhost:8080/video/out.m3u8` and `http://127.0.0.1:8080/video/out.m3u8`work
- If I try and serve the media files from any other address on the LAN I get a NETOWRK ERROR caused by something internal to Blazor and JS.  I have tried a few addresses with the same result.

### .NET Version

7.0.201  (also tried on 6.0.15 with same result)

### Anything else?

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.310 [C:\Program Files\dotnet\sdk]
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@phollida thanks for contacting us.

Does this issue reproduce on an app that uses the Webview directly? (Without Blazor)

**Comment by phollida** [comment]
Yes it looks that way - I updated [the test repo](https://github.com/phollida/HlsWinForm) to include the video tag and boiler plate js on index.html and it also fails to play.

So the new index.html body is now:
```
body>
<script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script>
<center>
    <h1>Hls.js demo - with static files</h1>
    <video height="600" id="staticvideo" controls></video>
</center>
<div id="app">Loading...</div>

<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>

<script src="_framework/blazor.webview.js"></script>
<script>
    var video = document.getElementById('staticvideo');
    if (Hls.isSupported()) {
        var hls = new Hls({
            debug: true,
        });
        hls.loadSource('http://192.168.0.54:8080/video/out.m3u8');
        hls.attachMedia(video);
        hls.on(Hls.Events.MEDIA_ATTACHED, function () {
            video.muted = true;
            video.play();
        });
    }
        // hls.js is not supported on platforms that do not have Media Source Extensions (MSE) enabled.
        // When the browser has built-in HLS support (check using `canPlayType`), we can provide an HLS manifest (i.e. .m3u8 URL) directly to the video element through the `src` property.
    // This is using the built-in support of the plain video element, without using hls.js.
    else if (video.canPlayType('application/vnd.apple.mpegurl')) {
        video.src = 'http://192.168.0.54:8080/video/out.m3u8';
        video.addEventListener('canplay', function () {
            video.play();
        });
    }
</script>
<script>
    function playVideo(source) {
        var video = document.getElementById('video');
        if (video.canPlayType('application/vnd.apple.mpegurl')) {
            video.src = source;
            video.play();
        } else
        if (Hls.isSupported()) {
            var hls = new Hls({
                debug: true,
            });
            hls.loadSource(source);
            hls.attachMedia(video);

            hls.on(Hls.Events.ERROR, function (event, data) {
                if (data.fatal) {
                    switch (data.type) {
                        case Hls.ErrorTypes.NETWORK_ERROR:
                            // try to recover network error
                            alert('fatal network error encountered, try to recover '+source );
                            hls.startLoad();
                            break;
                        case Hls.ErrorTypes.MEDIA_ERROR:
                            alert('fatal media error encountered, try to recover');
                            hls.recoverMediaError();
                            break;
                        default:
                            // cannot recover
                            alert('fatal error encountered, cannot recover');
                            hls.destroy();
                            break;
                    }
                }
            });
            hls.on(Hls.Events.MEDIA_ATTACHED, function () {
                video.muted = true;
                video.play();
            });
        }
    }
</script>
</body>
```

I would expect the static js code to start playing the video immediately but it hangs as well - so it looks like something is happening in WebView.

**Comment by phollida** [comment]
It looks like the underlying CoreWebView2 is doing its job correctly.

I've added a win forms WebView2 project to [the demo repo](https://github.com/phollida/HlsWinForm) that lets you switch between the raw HLS demo HTML and using a local web server to access the media server and in both cases it works fine.
**WebView2 App Screen Capture playing media via local web server:**
![image](https://user-images.githubusercontent.com/22928467/227392136-be83d7c7-de88-4934-bb2e-5dea9e1e5bab.png)
**WebView2 App Screen Capture playing media via using raw HTML string (NavigateToString):**
![image](https://user-images.githubusercontent.com/22928467/227392250-2a8fdf45-2653-4634-99f4-8bf42cb12d28.png)


I have also added the static javascript to the Blazor index.html as well as the wrapped blazor control.  Neither of these work with essentially the same code, so it is pointing to how Blazor interacts with CoreWebView2.

**Blazor app Screen capture trying to play media directly:**
![image](https://user-images.githubusercontent.com/22928467/227392669-459396b4-6eba-480a-bea0-118952f1f43f.png)

**Blazor app Screen capture trying to play media via local web server:**
![image](https://user-images.githubusercontent.com/22928467/227394138-8e88967e-243f-4428-abb7-cb17ad2a1066.png)


At least this has given me a work around for the time being - I can use a WebView2 control to play the video.

**Comment by javiercn** [comment]
@phollida thanks for the additional details. Is there something you had to specifically configure on the webview2 instance?

If you open the developer tools, are there any errors in the console?

**Comment by phollida** [comment]
No, for WebView2 I simply set the Source parameter for the local host case, and set the NavigateToString parameter for the static HTML case.  

I'm not getting any errors in console.
