### ISSUE TITLE
Dictionary<string, object> in Form has null value

### ISSUE THREAD

**Issue by federicocodo** [dotnet/aspnetcore#47383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During my tests at my service I noticed how, retriving the data using the `[FromForm]` attribute with the reference class for deserialization, the `Dictionary<string, object>` field had only the valid keys and the values ​​corresponding to null although them I had sent by Postman.
I know for sure that a `Dictionary<string, object>` works if I use the `[FromBody] ` attribute, with the form instead I would like to understand why the keys are not valued and if this problem could be solved.
I can't use other types like `string` because in this dictionary i can receive `string`, `int`, `double`, `long`, ecc..
The same problem comes using `dynamic`.

The controller method is structured just like this:
```csharp
public class TestController : BaseController
    {
        private readonly ILogger<TestController> _logger;
        private readonly IConfiguration _configuration;
        
        public TestController(
            ILogger<TestController> logger,
            IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        public async Task<IActionResult> Put(string id, [FromForm] PutRequest updateRequest, CancellationToken cancellationToken)
        {
            ...
        }
    }
```
The request class:
```csharp
    public class PutRequest
    {
        [Required]
        public string Name { get; set; }
        public string? Description { get; set; }
        public Dictionary<string, object>? Command { get; set; } = new Dictionary<string, object>();
        public IFormFile? Image { get; set; }
    }
```

The strange fact is that in the request, when a message arrives in the `Program.cs` still to be deserialized, I see the keys with their values. When they are set in the dictionary I see the values ​​to null.

When arrive the message:
![image](https://user-images.githubusercontent.com/62144863/227190827-65f3d514-c95a-4936-841a-a09cb7328f7f.png)

After setting in dictionary:
![image](https://user-images.githubusercontent.com/62144863/227190854-663acac1-9a8d-4a63-9a55-06f71969c925.png)

### Expected Behavior

I expect that in addition to the keys there are values ​​that are set

### .NET Version

7.0.201

**Comment by javiercn** [comment]
@federicocodo thanks for contacting us.

The form data model binder does not support binding `Dictionary<string,object>` as unlike other formats (like JSON) there is no way to represent an untyped value.

**Comment by federicocodo** [comment]
@javiercn 
Is there a workaround for that?
