### ISSUE TITLE
question about blazor United?

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/aspnetcore#47390]
Hello 👋
i have question about blazor United.
if blazer United project have database like mysql or sql server to make some crud operations...etc
,if i change the render mode from server to auto and the website in next few visiting well running in wasm is the website still can call the database ??

**Comment by javiercn** [comment]
@Ali1Jamal thanks for contacting us.

We are actively exploring this area, but it is too early to tell. That said, our goal is to reduce the boilerplate as much as possible. I want to be clear, however, that you'll never run the server code that calls the database from the browser. At best, the call will be handled in the server automatically in a transparent way.
