### ISSUE TITLE
SignalR: Missing Accept-Header

### ISSUE THREAD

**Issue by ThomasVandenbon** [dotnet/aspnetcore#47398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The Azure WAF is reporting an anomaly when negotiating a SignalR connection from a Console app to the Azure SignalR Service.

The anomaly that is being reported:
- Microsoft_DefaultRuleSet-2.0-PROTOCOL-ENFORCEMENT-920300
- https://xxx:xxx/xxx/negotiate?negotiateVersion=1
- "matchVariableName": "HeaderValue:user-agent", 
   "matchVariableValue": "Microsoft SignalR/6.0 (6.0.5+e5f183b656a0e8bc087108130a5a9b54ae94494e; Windows NT; .NET; .NET 6.0.3)"
- **Request Missing an Accept Header**

### Describe the solution you'd like

In `Microsoft.AspNetCore.SignalR.Client` an Accept Header should be added to the negotiating requests.

### Additional context

I'm running version 6.0.5 of the SignalR Client, as I'm unable to upgrade to 7.0.4 at the moment.
I cannot find the release notes for `Microsoft.AspNetCore.SignalR.Client` to check if the Accept Header hasn't been added, but since I cannot find an issue about this (open or closed), I would assume it hasn't been fixed yet.

**Comment by captainsafia** [comment]
@BrennanConroy Although the issue title cites Swagger this doesn't seem to be OpenAPI related. Any hunch as to what is going on here?

**Comment by MattyLeslie** [comment]
@BrennanConroy Might the following changes within `HttpConnection.cs` be a viable solution to this ?

1) Adding `httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));` to `CreateHttpClient()` 
``` 
var httpClient = new HttpClient(httpMessageHandler);
httpClient.Timeout = HttpClientTimeout;
httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
```
2) Ensuring the Accept header is present in `NegotiateAsync()`
```
 // Set the Accept header to "*/*"
request.Headers.Accept.Clear();
request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
```

**Comment by BrennanConroy** [comment]
In negotiate yes (although `Clear` seems unnecessary).
Does having default headers on `HttpClient` also add them to requests if the `HttpRequestMessage` added a specific value for the header already? Might want to just set `Accept` on all call sites where we send requests if `DefaultRequestHeaders` appends.

**Comment by MattyLeslie** [comment]
@BrennanConroy I believe the `HttpRequestMessage` header value would override the `DefaultRequestHeaders` header value. So, I agree that we might want to just ensure all call sites set `Accept` to the appropriate value when sending requests.  I'll look into submitting a PR if we're in agreeance.
