### ISSUE TITLE
Allow configuration of request/response buffer limits for TestServer

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/aspnetcore#47401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am currently building a ASP.NET 6 API which uses the power of `IAsyncEnumerable` and a Client which uses `JsonSerializer.DeserializeAsyncEnumerable`. Also I have some integration tests which use the `TestServer` implementation.

Now I want to make sure my implementation is correct when it comes to testing cancellation. The problem is that I can reduce the buffer size of the JsonSerializer but cannot reduce the buffer size of the TestServer response. So my whole response gets buffered at once and I cannot really test my implementation without producing a test response larger than the default buffer size (64kb I believe).

### Describe the solution you'd like

You should be able to configure request and response buffer sizes like you can do when using the Kestrel server implementation.

**Comment by DavidVollmers** [comment]
After some playing around it seems to me that the TestServer doesn't use a buffer internally. At least I could not produce a response larger enough to get buffered.

**Comment by Tratcher** [comment]
Can you show how you're calling it? TestServer does use a Pipe to do some buffering in both directions, but that data may be actively consumed from the other end.

**Comment by DavidVollmers** [comment]
So I built this test repository here:
https://github.com/DavidVollmers/IAsyncEnumerable-JSON-Example/blob/main/Example/TestProject/UnitTest1.cs

And of course now I could make it work as expected. This means there is something wrong with my implementation and I have to dig deeper. 

Sorry for the inconvenience...
