### ISSUE TITLE
Blazor WASM OIDC Token Response doesn't save custom properties from Token Response

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#47417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are using the Blazor WASM OIDC with an implementation of Duende Server. We assign some custom properties to the Token Response endpoint using the "Custom" Property highlighted in the screenshot below.
![image](https://user-images.githubusercontent.com/45796558/227713418-043ee155-d313-44d6-8277-2d9a779c0238.png)

Blazor WASM token response is available through the session state through the key - $"oidc.user:{authority}:{clientId}". However, it seems it only saves the accesstoken and the identitytoken and any custom properties are lost. Is there any way to access those custom properties?

### Expected Behavior

When I accessed the $"oidc.user:{authority}:{clientId}" property from the session state, I expected to have the additional properties also available there that were included from the OIDC Provider's token response.

### Steps To Reproduce

I am using an OOB implementation of WASM OIDC as outlined in docs. I am not sure if there is an option to pass a custom object to use when deserializing the response from the token endpoint

### Exceptions (if any)

None

### .NET Version

7

### Anything else?

NA

**Comment by javiercn** [comment]
@darena-pjindal thanks for contacting us.

We don't expose additional properties to the .NET side. You can grab them via JS interop if you need them by reading the storage directly and parsing the data yourself.

**Comment by darena-pjindal** [comment]
@javiercn - Thanks for the quick response. I was trying to access it from the storage directly. However, it doesn't seem that the default WASM OIDC response saves them. Is there a method that I can override before the token response is saved to storage?

**Comment by javiercn** [comment]
@darena-pjindal no, you can check the oidc-client options to see if there is something that you can set so that it saves it.

Otherwise, the only way is to provide your own `AuthenticationService.js`

**Comment by darena-pjindal** [comment]
Thanks @javiercn . That is the route we took, and we were able to make it work.
