### ISSUE TITLE
why fetch api  can't get valid response when asp.net core return 401 status

### ISSUE THREAD

**Issue by coader** [dotnet/aspnetcore#47425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

fetch(url).then(res=>{
}).catch(err=>{
})

as web design, 401 is also a valid response, and not throw exception,
but when fetch asp.net core api with JWT and if it's unauthenticated,
always run into catch process

### Expected Behavior

should return a valid response 

### .NET Version

6

**Comment by davidfowl** [comment]
Can you provide more details? Like a runnable application that demonstrates the problem?

**Comment by coader** [comment]
maybe it's problem of fetch implement in chrome, but I can't locate it

**Comment by davidfowl** [comment]
I don't fully understand the problem so I can't help. If you can provide something more complete, we may be able to point you in the right direction.

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/227827161-062a1882-f980-4e49-9aac-c6d58844c7a7.png)

![image](https://user-images.githubusercontent.com/3700498/227827194-a17eaeef-d9e1-476c-817a-f5bd183d1272.png)

it should run into line 58 but now is 72
so I can't get response and it's status code

**Comment by mitchdenny** [comment]
The first screenshot indicates that the authentication provider & middleware is saying that your JWT bearer token is invalid. However, there isn't really enough information here for us to diagnose the problem. We really require a small **self-contained** repro in the form of a GitHub repro which we can clone and run which illustrates the problem.

**Comment by coader** [comment]
the problem is not why asp.net core return 401, but why  401 make fetch api into catch function?

**Comment by mitchdenny** [comment]
Based on the code you've got there, the catch function should be getting called. Inside the then(...) following the fetch you are checking whether the response code is greater than 400 and then throwing - that means the catch should be invoked.
