### ISSUE TITLE
IJSObjectReference module import path error

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#47430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the Blazor Server app runs in two diffrent enviroments (dev and production). I have a component which must use some JS - no library

`           module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./scripts/bankeinzugrazor.js");
`
make wring path in production (url site/pp/)

https://...site/pp/ppscripts/bankeinzugrazor.js

JavaScript can not be load. 404 as path should be pp/scripts

Other ./ path issues are solved by
`    <base href="~/pp" />
`
or in more generic way by 
```
    <environment include="Development">  
            <base href="~/" />   
    </environment>   
    <environment exclude="Development">  
        <base href="~/pp" />  
    </environment>
````

also tried to use app.UsePathBase, but docu says obsolete in 6?

### Expected Behavior

korrekt path to js 

### Steps To Reproduce

Visual Studio Blazor Server projekt
place Js in wwwroot scripts
load Module from .razor OnAfterRenderAsync 

### .NET Version

7.0.202 /6

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

Your base path is incorrect. It needs to end with `/` as in `<base href="~/pp/" />`. Otherwise, the browser interprets it as `~/` (removes the last segment as its considered "a file").
