### ISSUE TITLE
"Blazor Server with Auth=B2C" template not correctly populating Identity Options.

### ISSUE THREAD

**Issue by MSFTJim** [dotnet/aspnetcore#47447]
The "Blazor Server with Auth=B2C" template is using a line of code that is not populating the Identity Options.  Changing to the line of code used in other templates (Ex. WebApp) fixes the issue and provides access to the different B2C options, such as EditProfilePolicyId.
 
- Incorrect line of code:
   - var options = microsoftIdentityOptions.CurrentValue;
      - Generated from the default template
 
- Correct line of code:
   - var options = microsoftIdentityOptions.Get(OpenIdConnectDefaults.AuthenticationScheme);

**Comment by danroth27** [comment]
@jmprieur Any concerns here with the proposed change to the Azure AD B2C template?

**Comment by jmprieur** [comment]
@danroth27 : this is indeed the thing to do!
Thanks!

**Comment by MSFTJim** [comment]
Great!  I'll go ahead and make a PR for the change!!

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/47654
