### ISSUE TITLE
Blazor wasm client fails to start when PublishTrimmed=true and built using 7.0.201 and above

### ISSUE THREAD

**Issue by markphillips100** [dotnet/aspnetcore#47442]
### Describe the bug
I have a Blazor WASM hosted 7.0 project with the following settings:
```
<PublishTrimmed>true</PublishTrimmed> 
<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
<TrimMode>partial</TrimMode>
```

There is code that likely cannot be trimmed I'm sure, reflection, dynamic components, etc, however, when the client (and host) app is built using 7.0.103 sdk the app exhibits no runtime issue with these trim settings.

I build and deploy using a dockerfile with a base sdk image.  SDKs 7.0.104 and 7.0.200 did not get docker image releases so cannot try those versions.  Using SDK 7.0.201 and the recent 7.0.202 causes the exception below in the browser when the app starts up.

If I set `PublishTrimmed=false` then no trimming occurs of course but the app also works normally, so this appears to be some trim behaviour introduced in 7.0.201 (and perhaps 7.0.200 but I cannot test for that).  Are there any things trim-wise that could be affecting the app at startup in these new versions, or is their even some diagnostics I can setup to try and get to the bottom of what might be the issue?

### To Reproduce
Unfortunately I cannot create a repro.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/6239029/225791795-df73227f-4b41-48da-97b6-eb8d09a49208.png)

**Comment by markphillips100** [comment]
@javiercn it is indeed a blazor webassembly hosted project.

My solution was to just not supply the PublishSelfContained at all when building in my dockerfile for the use case where I don't want it self contained.  I'm happy with that as it does work but just wanted to know if the behaviour of this particular property had been changed as my previous setup with the 103 patch worked fine setting it to false explicitly.

**Comment by markphillips100** [comment]
That's okay @javiercn.  There's probably more changes over the horizon too at a guess :-).  Self contained is always the goal for me but had problems with v7 due to some partial trim mode performance issues hence needing to turn it off.  The linker team worked wonders and brought forward fixes from v8 into 7.0.300 so should be good to go self-contained (partial trim mode) when that is released.  

Happy to close the issue.

**Comment by javiercn** [comment]
@markphillips100 if setting `<GlobalPropertiesToRemove>SelfContained</GlobalPropertiesToRemove>` in the project reference does not work with what you are passing via command-line, please let us know.

**Comment by markphillips100** [comment]
@javiercn I added the MSBuild property to the project reference in the host csproj like so, I assume this is correct?
```
    <ProjectReference Include="..\MySample.Client\MySample.Client.csproj" >
      <GlobalPropertiesToRemove>SelfContained</GlobalPropertiesToRemove>
    </ProjectReference>
```

Switching my dockerfile back to the original `RUN dotnet publish ... /p:PublishSelfContained=false ...` and I get the same client-side exception as before.

Did I add the GlobalPropertiesToRemove correctly?

**Comment by javiercn** [comment]
@markphillips100 you did.

Can you capture a binlog with the `/bl` flag? Be careful to inspect it in case you have secrets in environment variables or similar, as they might appear on the build log.

**Comment by javiercn** [comment]
@markphillips100 can you try this?

```
    <ProjectReference Include="..\MySample.Client\MySample.Client.csproj">
	  <GlobalPropertiesToRemove>SelfContained;RuntimeIdentifier;PublishSelfContained</GlobalPropertiesToRemove>
    </ProjectReference>
```

Might also need to add the following inside a propertygroup
```
<StaticWebAssetsAdditionalBuildPropertiesToRemove>$(StaticWebAssetsAdditionalBuildPropertiesToRemove);RuntimeIdentifier;SelfContained;PublishSelfContained</StaticWebAssetsAdditionalBuildPropertiesToRemove>
```

**Comment by markphillips100** [comment]
So tried both changes together but it doesn't get past the `RUN dotnet build` step due to an error (shown below).

Thought I'd try one change at a time.

|GlobalPropertiesToRemove|StaticWebAssetsAdditionalBuildPropertiesToRemove|Builds|Runtime error|
|-|-|-|-|
|`SelfContained`|Not specified|Yes|Yes|
|`SelfContained;RuntimeIdentifier`|Not specified|Yes|Yes|
|`SelfContained;RuntimeIdentifier;PublishSelfContained`|Not specified|No|Not possible|

The build error from the last set of properties used is:
`/usr/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(238,5): error : The process cannot access the file '/src/src/EziEventShop.SampleWeb.Client/obj/Release/net7.0/build-gz/tx8NU7vJ.gz' because it is being used by another process. [/src/src/EziEventShop.SampleWeb.Client/EziEventShop.SampleWeb.Client.csproj]`

I then tried adding the `StaticWebAssetsAdditionalBuildPropertiesToRemove` iteratively adding the same respective combination of the delimited property values but experienced the same outcomes:

|GlobalPropertiesToRemove|StaticWebAssetsAdditionalBuildPropertiesToRemove|Builds|Runtime error|
|-|-|-|-|
|`SelfContained`|`SelfContained`|Yes|Yes|
|`SelfContained;RuntimeIdentifier`|`SelfContained;RuntimeIdentifier`|Yes|Yes|
|`SelfContained;RuntimeIdentifier;PublishSelfContained`|`SelfContained;RuntimeIdentifier;PublishSelfContained`|No|Not possible|

I tried just specifying `PublishSelfContained` alone but got this error during `RUN dotnet build` step:
```
 /usr/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(319,5): error MSB4018: System.IO.IOException: The process cannot access the file '/src/src/EziEventShop.SampleWeb.Client/obj/Release/net7.0/blazor.boot.json' because it is being used by another process. [/src/src/EziEventShop.SampleWeb.Client/EziEventShop.SampleWeb.Client.csproj]
```

**Comment by MackinnonBuck** [comment]
@markphillips100, we think we might have fixed this in .NET 8. Could you please try using .NET 8 and see if it resolves the problem?

**Comment by markphillips100** [comment]
Sorry I should have commented earlier. It's been working great with 8.0.100.

Thanks for everyone's efforts.
