### ISSUE TITLE
"Blazor Server with Auth=B2C" template sets policy requiring all request to be authorized.

### ISSUE THREAD

**Issue by MSFTJim** [dotnet/aspnetcore#47448]
"Blazor Server with Auth=B2C" template sets the FallbackPolicy to the DefaultPolicy which then results in every request requiring authorization.

A typical scenario is to have an anonymous page that describes the site and then provides a button for the user to sign-in if so desired.

Removing this policy results in that behavior, which I believe is a more appropriate scenario for B2C.

**Comment by mkArtakMSFT** [comment]
Closing as the Blazor Server project template has been removed from .NET 8 in favor of Blazor Web App template.
