### ISSUE TITLE
img decoding="async" with blazor

### ISSUE THREAD

**Issue by wrharper-AASP** [dotnet/aspnetcore#47449]
When doing async with img src for a base64 string I get a deadlock. I have to use configureawait(false) on all tasks and according to sourceforge and sites like it, everyone is doing this to get around it.

I have recently learned about (decoding="async") inside of the img html object. Is it possible to use this in some way so that you can truly get images with async? this would be a huge performance increase for the project I am doing.

I use a custom REST API I have created to get the images and they come in as base64 strings.

**Comment by javiercn** [comment]
@wrharper-AASP thanks for contacting us.

> I am a bit confused about who supports what. This project says asp.net core does Blazor, when going to asp.net core, it links to this. There appears to be a loop on who does what? If this is the wrong place, let me know.

This repo is for Blazor, which is part of ASP.NET Core. Hope that helps clarify things.

>When doing async with img src for a base64 string I get a deadlock. I have to use configureawait(false) on all tasks and according to sourceforge and sites like it, everyone is doing this to get around it.
>
>I have recently learned about (decoding="async") inside of the img html object. Is it possible to use this in some way so that you can truly get images with async? this would be a huge performance increase for the project I am doing.
>
>I use a custom REST API I have created to get the images and they come in as base64 strings.

I imagine you are doing something like `<img src="{{base64Url}}" />`?

First of all, we recommend against that. You are allocating very large strings that the system needs to hold on to, and that is going to perform badly.

If you already have data on an API, we suggest you avoid base64 URL encoding the image altogether and serve the bits raw from the endpoint.

**Comment by wrharper-AASP** [comment]
> @wrharper-AASP thanks for contacting us.
> 
> > I am a bit confused about who supports what. This project says asp.net core does Blazor, when going to asp.net core, it links to this. There appears to be a loop on who does what? If this is the wrong place, let me know.
> 
> This repo is for Blazor, which is part of ASP.NET Core. Hope that helps clarify things.
> 
> > When doing async with img src for a base64 string I get a deadlock. I have to use configureawait(false) on all tasks and according to sourceforge and sites like it, everyone is doing this to get around it.
> > I have recently learned about (decoding="async") inside of the img html object. Is it possible to use this in some way so that you can truly get images with async? this would be a huge performance increase for the project I am doing.
> > I use a custom REST API I have created to get the images and they come in as base64 strings.
> 
> I imagine you are doing something like `<img src="{{base64Url}}" />`?
> 
> First of all, we recommend against that. You are allocating very large strings that the system needs to hold on to, and that is going to perform badly.
> 
> If you already have data on an API, we suggest you avoid base64 URL encoding the image altogether, serve the bits raw from the endpoint and reference the endpoint in the link tag.

I actually can't in my case. I can't really explain why without exposing too much of my goals, but it comes down to the useragent. The images have to be a specific useragent to be viewed by the URL so that is why they are converted to base64.

**Comment by wrharper-AASP** [comment]
The other Idea I have had has been creating a List, Stack, or Queue cache, but that would increase memory usage tremendously if tons of people use the site. It can't be stored on the client for compliance reasons either.

**Comment by wrharper-AASP** [comment]
ok, the last thing I can think of is adding the useragent somehow to all clients. Is that possible?

**Comment by javiercn** [comment]
@wrharper-AASP thanks for the additional details.

Rendering in Blazor is synchronous, it does not work because the result from your task is being ignored (It's really hard to tell what you are exactly doing without the concrete snippets).

You need to load any data you need within `OnInitializedAsync`. It will render twice, the first time before any async work happens, and a second time after it has completed, and at that point you can use the data to render

```
foreach(var image in Images)
{
   <img src="" ... />
}

override OnInitializedAsync()
{
    Images = await LoadImages();
}
```

**Comment by wrharper-AASP** [comment]
I have been using .Result to bypass these problems for many things and it works great, but for some reason it deadlocks with the solution you mentioned.

**Comment by wrharper-AASP** [comment]
> @wrharper-AASP You can't do that within Blazor.
> 
> Blazor uses a synchronizationcontext and by doing `.ConfigureAwait` your callbacks won't run within it, which is sure to cause problems. `ConfigureAwait` is for libraries, not for app code.

https://stackoverflow.com/questions/67516887/blazor-server-side-async-deadlock

**Comment by javiercn** [comment]
@wrharper-AASP that question/answer is wrong. 

Not sure what you are trying to imply with that stackoverflow question/response, but the only comment from Stephen Cleary is correct. Do not block on async code.

The way you are trying to approach a solution is in direct conflict with how the framework works.

Rendering is synchronous, and if you want to do async work, you need to use a lifecycle method and do it there. Blocking the rendering threads will cause deadlocks at worst and thread starvation at best.

**Comment by wrharper-AASP** [comment]
the solution you have:
```
window.setImage = async (imageElementId, imageStream) => {
            const arrayBuffer = await imageStream.arrayBuffer();
            const blob = new Blob([arrayBuffer]);
            const url = URL.createObjectURL(blob);
            const image = document.getElementById(imageElementId);
            image.onload = () => {
                URL.revokeObjectURL(url);
            }
            image.src = url;
        }
```
Is it possible to do bytes instead of a stream?
C# is my main language.

**Comment by wrharper-AASP** [comment]
Ok I did the proper lifecycle, but it will not work due to the useragent issue. The blob just shows up as broken images.

I do OnParam set to set the values (before the render) for the HTML and then OnAfterRedner without first render so it keeps happening for setting the ID (after the render).

**Comment by javiercn** [comment]
@wrharper-AASP there is a complete sample in the link I provided https://learn.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-7.0#stream-image-data

The only thing you need to do is define the `setImage` function within your app, so that it's reachable via JS interop

**Comment by wrharper-AASP** [comment]
It isn't valid because you don't use an async button push. It should be happening on load and update on changes. No buttons.

**Comment by wrharper-AASP** [comment]
also, i have it working by doing what i mentioned, but the images are still broken:
![image](https://user-images.githubusercontent.com/117128832/228325418-f1376714-836f-40d4-a293-65f9da66da7d.png)

**Comment by javiercn** [comment]
@wrharper-AASP change `SetImageAsync` and instead override OnInitializedAsync() to load the data and then do the JS interop call after the data has arrived.

You can use a boolean flag to know when the data is ready, and have a check on the render to avoid rendering anything until all the data is there

**Comment by javiercn** [comment]
That `src` attribute looks wrong. How did you create that

**Comment by wrharper-AASP** [comment]
With the solution you gave, it creates that.

**Comment by javiercn** [comment]
@wrharper-AASP what do the browser console logs say?

**Comment by wrharper-AASP** [comment]
The HTML is just `<img id=@images[i] />` which is basically the same thing as the example setting an id. The src is generated from `await JsRuntime.InvokeVoidAsync("setImage", SelectedI.ToString() + "_" + i.ToString(), dotnetImageStream);`

**Comment by wrharper-AASP** [comment]
> @wrharper-AASP what do the browser console logs say?

nothing because there is actually no errors.

**Comment by wrharper-AASP** [comment]
I think this comes down to an auth issue. Because I cannot get that image without also doing Auth, I can't do Auth without exposing a key that the client side should never see. This is another reason why I used base64.

**Comment by wrharper-AASP** [comment]
Again, with OnInitialized, this cannot be used because it only runs once. These values and this component will change constantly, it cannot be used do to update changes.

![image](https://user-images.githubusercontent.com/117128832/228329985-90e21522-e69d-4e0b-a5f1-4ae255e090f0.png)

**Comment by wrharper-AASP** [comment]
What really needs to exist is a proper before and after. That doesn't seem to be possible in blazor. What I used was OnParametersSet and then OnAfterRender

![image](https://user-images.githubusercontent.com/117128832/228333573-9bf1e6fd-8567-4722-a7a4-bb69a98051e6.png)
![image](https://user-images.githubusercontent.com/117128832/228333857-01bab98e-242d-4bed-a253-4a6f42b28f3e.png)

**Comment by javiercn** [comment]
@wrharper-AASP here is a working sample https://github.com/javiercn/ImageBlobSample

**Comment by wrharper-AASP** [comment]
You can't use the direct https:// without exposing the key. That was the whole point of base64 to begin with. Too much security is exposed. Your examples involves commonly exposed public images. That isn't the case...

**Comment by wrharper-AASP** [comment]
No, not without the client seeing this:
```
private async Task<DotNetStreamReference> GetImage(int i)
    {
        var client = new HttpClient();
client.DefaultRequestHeaders.Add("Authorization", SHOULDNOTBESEEN);
        var stream = await client.GetStreamAsync($"https://dummyimage.com/450x2{i}0/f00/fff");
        return new DotNetStreamReference(stream);
    }
```

**Comment by javiercn** [comment]
@wrharper-AASP the c# code in Blazor Server runs on the server. Only the JS code runs on the browser.

**Comment by javiercn** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0

**Comment by wrharper-AASP** [comment]
it is more complicated than that. I can't explain. I cannot hide that key if that is on the server. We are working backwards further and further; this will not be a solution.

**Comment by javiercn** [comment]
@wrharper-AASP there doesn't seem to be a framework issue here.

It's not clear to us what problem you have, and we do not have enough details to offer a meaningful suggestion beyond the sample we provided.

Unless you want to provide a publicly available minimal repro project (not your codebase, something equivalent that replicates the problem) we can't be of further assistance.

While we try our best to help everyone that comes with questions, this tracker is dedicated to product issues and it seems you have an architectural/layering problem to solve. We recommend you post a question on `Stackoverflow` with the aspnetcore-blazor tag to see if other members on the community can step up to give you guidance.

**Comment by wrharper-AASP** [comment]
I have had to create a custom REST API for many reasons, and this is one of them. The images cannot be stored anywhere else due to compliance, and they cannot be seen with a specific key and that key needs to be dynamically distributed if it's on the server. It is more complicated than what is being shown. It is clear that is just isn't possible at this point and base64 is the only option.

**Comment by wrharper-AASP** [comment]
I have found a way to make the reference in a way that works by converting the base64 and using your solution. Will this help performance?
DotNetStreamReference dotnetstream = new DotNetStreamReference(new MemoryStream(Convert.FromBase64String(base64string));

**Comment by wrharper-AASP** [comment]
Thank you, it does look like this is actually resolved with the resolution you provided now. It was just a matter of going about it a different way for the stream.

**Comment by wrharper-AASP** [comment]
I recommend doing ID instead of SRC like the original solution shows with a JS invoke:
https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0
His concept/idea is right though.
