### ISSUE TITLE
AzureADB2C.UI v7 release

### ISSUE THREAD

**Issue by johnwc** [dotnet/aspnetcore#47458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are upgrading our projects to .Net 7 and noticed Microsoft.AspNetCore.Authentication.AzureADB2C.UI package is not published yet for .Net 7. The last prerelease update was 9 months ago. Is there still a plan to release a v7 to coincide with .Net 7, or did this just slip through the cracks for being released?

### Expected Behavior

v7 release of package to coincide with the rest of the ASP.Net packages released for .Net 7.

### .NET Version

7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't plan to publish this package anymore. Instead, customers should use https://www.nuget.org/packages/Microsoft.Identity.Web package instead.

**Comment by johnwc** [comment]
Should the packages then be deprecated then?
