### ISSUE TITLE
Rate Limiting - Ability to consume a variable amount of tokens per request

### ISSUE THREAD

**Issue by scottt13** [dotnet/aspnetcore#47456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am looking at implementing rate limiting in a .Net core project and the TokenBucket approach with partitioning per user works really nicely for our use case. There is one thing I don't seem to be able to do with it that would really complete the feature which is to adjust the number of tokens removed from the bucket by a request based on information we have _after_ completion of the request.

For example, if a request takes 5 seconds to process it should consume more tokens from the bucket than a request that takes 100ms. Similarly, based on internal performance metrics that we collect for each request, if we determine that a request is using a lot of resources it should consumer more tokens from the bucket.

### Describe the solution you'd like

An additional callback in RateLimiterOptions that is invoked after a request has been processed, and access to the RateLimiter that was used with the ability to consume/acquire additional tokens.

```
services.AddRateLimiter(options =>
         {
            options.OnComplete = (context) =>
            {
               // Do some work to determine performance impact of request
               var tokenCount = SomePerformaneCalculation();
               // if this is determined to be an impactful request, consume additional tokens (new method may be necessary, this is just for illustrating the concept)
               using var lease = context.RateLimiter.AttemptAcquire(HttpContext, tokenCount);
            };
```

### Additional context

Its possible a request may initially acquire a single token allowing it to be processed, but then after completion require more tokens than what remains in the bucket. In this case the bucket should be drained preventing anymore requests until it is replenished, but allowing the current request to complete (similar to consuming the last token in the bucket)

**Comment by mitchdenny** [comment]
This is an interesting idea. I think that there are a few different places people might want to request additional/apply additional tokens - so I wonder if having an OnComplete callback arbitrarily limits you here. It might make more sense to define an `IRateLimitingFeature` which carries the current lease and rate limiting instance for the request.

This could then be requested and interacted with in middleware or anywhere a feature can be resolved.

**Comment by mitchdenny** [comment]
@wtgodbe and @BrennanConroy - can you think of any other existing mechanism that could be used here to get access to the rate limiter as part of processing the request for the purpose of draining additional tokens?

**Comment by scottt13** [comment]
There feature idea might be a sensible solution. I found a somewhat related discussion along those lines on this ticket: #45658 and a little bit of discussion about whether this sort of use case exists so it may help with fleshing out the API they are discussing there.

**Comment by mitchdenny** [comment]
Ah good find. Yes, there is a related conversation there.

**Comment by mitchdenny** [comment]
Closing this issue in favor of the linked issue since I think that if we are going to implement it we'll probably do it as part of that proposal.
