### ISSUE TITLE
Decreasing the window size below the amount of data sent can prematurely abort the connection

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#47452]
The following error can occur in specific scenarios if the server has sent some data on a stream and the client updates the window size to some value below the amount already sent
```
Microsoft.AspNetCore.Server.Kestrel.Http2 Critical: The event loop in connection 0HMP8EQDO1NJO failed unexpectedly.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
    at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
    at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2FrameWriter.WriteToOutputPipe() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:line 139
```

### Method 1
For example, if the server sends 2 bytes with an initial window size of 3, then the client updates the window to be 1. The server will successfully have scheduled a new item to the output loop for processing:
https://github.com/dotnet/aspnetcore/blob/7aca30363667b13f80aae816dc9924de54284569/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L312-L314
But before it starts processing the item in
https://github.com/dotnet/aspnetcore/blob/c93d0d013b8f9e7baf2ae03fcc2fcade78687385/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L111-L117
The updated Window can be processed:
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L891-L897
Which will decrease the `_streamWindow` to a negative value, which will then fail the buffer slice at
https://github.com/dotnet/aspnetcore/blob/c93d0d013b8f9e7baf2ae03fcc2fcade78687385/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L131-L139

--------

### Method 2
Another way this can be hit is if `Stop` is called once the `_streamWindow` is negative, even if nothing has been scheduled yet, because it will call `Schedule` itself without any checks for `_streamWindow`
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L566-L583

--------

### Method 3
Doing multiple writes can also cause this, if the window update happens after the first write, but before the second one (or if it happens during the race between starting to process the second write and reading the settings as described in method 1).
This path also calls `Schedule` without a check for `_streamWindow`.
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L388-L407

---------

This following test will hit the issue in either the `Stop` path described in method 2 or the multi write path described in method 3.
```csharp
[Fact]
public async Task DecreaseWindowBelowCurrentSentAmount()
{
    const int windowSize = 3;
    _clientSettings.InitialWindowSize = windowSize;

    var tcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

    await InitializeConnectionAsync(async context =>
    {
        var bodyControlFeature = context.Features.Get<IHttpBodyControlFeature>();
        bodyControlFeature.AllowSynchronousIO = true;
        await context.Response.Body.WriteAsync(new byte[windowSize - 1], 0, windowSize - 1);
        await tcs.Task;
        context.Response.Body.Write(new byte[windowSize], 0, windowSize);
    });

    await StartStreamAsync(1, _browserRequestHeaders, endStream: true);

    await ExpectAsync(Http2FrameType.HEADERS,
        withLength: 32,
        withFlags: (byte)Http2HeadersFrameFlags.END_HEADERS,
        withStreamId: 1);

    // Decrease window size after server has already sent the current window - 1 size of data
    _clientSettings.InitialWindowSize = windowSize - 2;
    await SendSettingsAsync();

    await ExpectAsync(Http2FrameType.DATA,
        withLength: windowSize - 1,
        withFlags: (byte)Http2DataFrameFlags.NONE,
        withStreamId: 1);

    await ExpectAsync(Http2FrameType.SETTINGS,
        withLength: 0,
        withFlags: (byte)Http2DataFrameFlags.END_STREAM,
        withStreamId: 0);

    tcs.SetResult();

    await StopConnectionAsync(expectedLastStreamId: 1, ignoreNonGoAwayFrames: false);
}
```

**Comment by BrennanConroy** [comment]
Moving to backlog. This is a low-pri bug, only affects an edge case in the HTTP/2 spec and only sometimes since it's a race.

**Comment by bhaskarqlik** [comment]
We are encountering this issue intermittently after we upgraded our service from .NET 6 to 8.
```
crit: Microsoft.AspNetCore.Server.Kestrel.Http2[63]
      The event loop in connection 0HN3R40QVJ560 failed unexpectedly.
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
         at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
         at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2FrameWriter.WriteToOutputPipe()
```
Our service is a grpc server that provides streaming calls to transfer large volumes of data. The grpc client in our case is written in C++. After the error, the grpc client is not notified of any errors, and it remains waiting for a response.
