### ISSUE TITLE
Build error when using RDG with a route handler that returns a type explicitly implementing IResult

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#47462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the request delegate generator (RDG) is enabled, and the app contains a route handler that returns a type that explicitly implements `IResult`, the build fails with the following error:

```error CS1501: No overload for method 'ExecuteAsync' takes 1 argument```

### Expected Behavior

The RDG should work with endpoints that return types that explicitly implement `IResult`.

### Steps To Reproduce

1. In a Minimal APIs project with the RDG enabled, add an endpoint that returns a type that explicitly implements `IResult`, e.g.
    ```csharp
    app.MapGet("/test", () => new TeapotResult());

    public class TeapotResult : IResult
    {
        Task IResult.ExecuteAsync(HttpContext httpContext)
        {
            httpContext.Response.StatusCode = StatusCodes.Status418ImATeapot;
        }
    }
    ```
1. Build the project

### Exceptions (if any)

```error CS1501: No overload for method 'ExecuteAsync' takes 1 argument```

### .NET Version

8.0.100-preview.4.23173.7

**Comment by davidfowl** [comment]
Nice find. More efficient to solve this with a generic constraint than a cast to the interface. Similar to how to handle TryParse.

**Comment by captainsafia** [comment]
Yeah, we'll need to implement the same strategy that we used for invoking explicit implementations of `IParsable.TryParse`.

https://github.com/dotnet/aspnetcore/blob/138388372bb7c6e35fdfa679da740fabc275a688/src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs#L63-L66
