### ISSUE TITLE
Blazor - JavaScript interop returns the wrong values for some types in production builds

### ISSUE THREAD

**Issue by mooski** [dotnet/aspnetcore#47468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using JavaScript interop to call a JavaScript function which returns a _certain type_ of object doesn't work as expected in production builds of a Blazor WASM project.

For example, a JavaScript function which is returns an array of `RectangleF`s will always return empty objects (with zero positions and dimensions) rather than the expected values. I'm not sure which other types of object are also affected.

This only seems to affect production builds - development builds seem to behave correctly.

### Expected Behavior

JavaScript interop functions should return the correct expected values regardless of whether the build is production or development.

### Steps To Reproduce

This has been tested in Chrome and Firefox in Windows 11 - both with the same results.

**This requires Docker to be installed** so that we can run a production build (as opposed to a development build which doesn't seem to be affected by this issue). There might be some way to run in production without the need to build like this that I'm not aware of.

1. Clone this repository: https://github.com/mooski/blazor-js-test

    _This is just the 'Blazor WebAssembly App Empty' project template with small changes to the following files: `Client/Pages/Index.razor`; `Client/wwwroot/index.html`; `Dockerfile`; `nginx.conf`._
    
2. Open a terminal in the root folder and run this command:

    `docker build -t blazor-js-test .`
    
3. Assuming the project builds successfully, run this command:

    `docker run -p 8080:80 blazor-js-test`
    
4. Visit http://localhost:8080/ in a browser.

5. Open developer tools.

6. Click the 'Print window width to console' button.

7. Note that there's a discrepancy in the values printed in the console. The correct window width is printed from the JavaScript code, but the value printed from the Blazor code is always zero.

To see the application behaving how we'd expect instead, we can use this workaround:

1. Uncomment line 22 in `Client/Pages/Index.razor`.

2. Build and run the Docker image again.

3. Back in the browser, refresh the page and click the 'Print window width to console' button again.

4. Note that the correct values are now printed in the console (and this is despite the fact that the uncommented code doesn't even get touched).

### .NET Version

7.0.202

**Comment by mkArtakMSFT** [comment]
This looks like a Linker issue. To confirm this, you can try to disable the linker following guidance here: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-7.0

If that fixes the problem, you can then annotate the offending type to avoid trimming only that one and that should be it.

**Comment by mooski** [comment]
Thanks, I think I understand the issue now.

I'm not completely sure why this type is being trimmed when it's used explicitly in the code (as opposed to via reflection), but I'm willing to accept this is a very complex functionality and I'm sure there's good reason for this behaviour!

I wasn't entirely sure how best to fix this, but I've decorated the method like this and it now seems to behave correctly, so I guess this is the best solution:

```
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(RectangleF))]
```

Thanks again for your help.
