### ISSUE TITLE
Please consider Extensions to Blazor WASM elements?

### ISSUE THREAD

**Issue by BrownishMonster** [dotnet/aspnetcore#47466]
I would like to propose adding extensions to Blazor WASM elements, which will pass in an element reference to the implementation.

The extension will implement an interface, named for example `IElementExtension`, and will accept the Element Reference. This could allow us to invoke JS without the overhead of having a full component.

```cs
interface IElementExtension
{
    Task Extend(ElementReference reference);
}

```

The implementations would be decorated with an attribute,  `ElementExtensionInvokeAttribute` in the examples below for lack of a better name, which would tell the renderer when to call the extension class, for example once after it has initialized or after each render. The extension could be added onto the element using `@@`, followed by the class name.

# Example
For example, suppose our razor page contains the following:
```html
<div>
    <input type="text" @@AlwaysFocus />

    <div class="scrollable" @@Scrollable>
        <a>Item 1</a>
        <a>Item 2</a>
        <a>...</a>
        <a>Item N</a>
    </div>
</div>
```

An example extension would be:
```cs
[ElementExtensionInvoke(InvokeKind.OnAfterRender)]
public class AlwaysFocus : IElementExtension
{
    public async Task Extend(ElementReference reference)
    {
        await reference.FocusAsync();
    }
}
```

This class will be called after each time the parent component is rendered, and will call the web application to focus the input field.

Another extension would be:
```cs
[ElementExtensionInvoke(InvokeKind.OnInitialized)]
public class Scrollable : IElementExtension
{
    private readonly IJSRuntime _js;

    public Scrollable(IJSRuntime js)
    {
        _js = js;
    }

    public async Task Extend(ElementReference reference)
    {
        await js.InvokeVoidAsync("MakeScrollableWithMouse", reference);
    }
}
```

This would invoke a method using the JS Runtime, and would only be called once when the parent is initialized.

# Benefits
Blazor Components have overhead and sometimes we find ourselves doing the same thing a few times on difference components. This extension method would allow us to follow the DRY principle.

# Downsides
My proposal does not allow changing the rendering on the element itself. I do not know how this could be implemented, but I believe a blazor component is better suited for this.

# Real-life example
Our Blazor application is used on touch screen monitors. Some of these are _really_ old and use mouse events, which means when the LeftButton is pressed and there is a mouse move event, the user might want to scroll a list. We have these in a few places and, for right or wrong, a component was not used. We use ElementReference in our code-behind and then invoke a JS method passing the reference in. A lot of this code is similar with slight variations, on different components. Extension method would simplify the code, without having to create a whole new component.

**Comment by javiercn** [comment]
@BrownishMonster thanks for contacting us.

We don't think we will be providing functionality like this in the immediate future, especially as proposed, as it will result in a lot of back-and-forth JS interop.

At best, we might provide the option to declare that a JS function needs to be called for an element in the markup after it has rendered, but definitely not with any new syntax or C# APIs for it, as we would want to run these functions within the client directly.

That's said, this is not something that we are prioritizing right now. There are already ways to achieve this, like using a `MutationObserver`, which is what we would recommend.
