### ISSUE TITLE
[Blazor] DotnetStreams bug

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47473]
https://github.com/javiercn/ImageBlobSample/blob/main/ImageBlobSample/Pages/_Host.cshtml#L35

When passing a stream down to the client, we pass in a promise, not the actual stream to the function. Users should not need to await that promise.

**Comment by SteveSandersonMS** [comment]
This didn't repro when I tried it. Here's a REPL in which the stream object is transferred as expected, and doesn't show up as a promise first: https://blazorrepl.telerik.com/cnYRHuaW08MF1P7U11

This also appears to be running .NET 7 so I'm unsure why the behavior would be different from in your example.

**Comment by javiercn** [comment]
@SteveSandersonMS that's fair. I gave it another try, it seems that it has been a fluke on my side. (This is what I get for coding late)

I am going to close this then.
