### ISSUE TITLE
Ensure ability to customize the HtmlEncoder used for the RazorComponentEndpoint

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#47477]
For reasons like this (thanks @DamianEdwards)

> The default encoder settings are pretty aggressive/conservative, encoding anything above standard ASCII despite the response encoding generally being UTF8, so it's not unusual for folks to customize the encoder to be more lenient, for example allowing Katakana/Hiragana characters through without HTML encoding

**Comment by DamianEdwards** [comment]
Turns out we already have mechanisms for this in ASP.NET Core via `IServiceCollection.AddWebEncoders()` so fixing this should just be a case of ensuring `AddRazorComponents()` calls that and that the component renderer resolves `HtmlEncoder` from DI.

**Comment by DamianEdwards** [comment]
@SteveSandersonMS @mkArtakMSFT @danroth27 why was this moved to the backlog? We have a long-established pattern of enabling customization of the HTML encoding in ASP.NET Core via the registered `HtmlEncoder` instance and Razor Components needs to honor that.
