### ISSUE TITLE
[ASPNET Core 2.1] src\SignalR\clients\csharp\Http.Connections.Client\src\HttpConnection.cs should null check logging scope before disposing

### ISSUE THREAD

**Issue by arianmotamedi** [dotnet/aspnetcore#47470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[HttpConnection.cs](https://github.com/dotnet/aspnetcore/blob/release/2.1/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs) in SignalR client (aspnet core 2.1) is disposing its ILogger.Scope object [without doing a null check](https://github.com/dotnet/aspnetcore/blob/release/2.1/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs#L277). [LoggerExtensions.BeginScope<>() documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.beginscope?view=dotnet-plat-ext-2.2#returns) says this method may return null, so it needs to be properly null checked before calling `.Dispose()` on it otherwise it throws a null ref exception at runtime.

### Expected Behavior

`_scopeDisposable` should be null-checked before disposing.

### Steps To Reproduce

For whatever reason, the scope isn't null in Microsoft.Extensions.Logging 2.2 even though the docs say this version [could still return null](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.beginscope?view=dotnet-plat-ext-2.2#returns). We can see this when running Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests+Negotiate.NegotiateReturnedConenctionIdIsSetOnConnection test - as it's using [LogSinkLogger](https://github.com/dotnet/aspnetcore/blob/release/2.1/src/SignalR/common/testassets/Tests.Utils/ServerFixture.cs#L214), which returns null in its BeginScope() override.

Upgrading Microsoft.Extensions.Logging references and its dependencies to 3.1 is correctly calling the override and returning null, but that dispose method above throws a null ref exception at runtime.

### .NET Version

4.6.2

### Anything else?

ASPNET Core 2.1

**Comment by mgravell** [comment]
This appears to not be a problem in the current code - [fixed here](https://github.com/dotnet/aspnetcore/commit/4f85ca2b1df78e4b821f6ee3456e3f0d2cd5ef70); I agree that this is technically in error, and the fix is pretty trivial (` _scopeDisposable?.Dispose();`) - but: I'm not sure we're still issuing updates to 2.1, so I'm not sure this would be a useful change - I'll check my understanding there.

**Comment by arianmotamedi** [comment]
Thanks @mgravell. Stephen has the same sentiment on the open PR for the fix: https://github.com/dotnet/aspnetcore/pull/47471. I didn't realize aspnet core 2.1 is strictly in servicing mode - makes sense to not want to release a patch for this change.
