### ISSUE TITLE
net core 7 razor pages release ViewData  page garbled on docker 

### ISSUE THREAD

**Issue by QQ1756455668** [dotnet/aspnetcore#47479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Razor pages appear garbled under docker in release mode

### Steps To Reproduce

1 Create a new project in vs2022，select  “asp.net core web app” template and .net 7.0
2 create a new "razor pages - empty" 
3 page code (index1.cshtml):
```
@page
@model WebApplication6.Pages.Index1Model
@{
}
@ViewData["test"]
4 page code (index1.cshtml.cs):
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
            ViewData["test"] = "测试";
        }
    }
```
5 add a default dockerfile
6 run in docker in release mode
7 page garbled

![2](https://user-images.githubusercontent.com/103493005/228504188-fa208173-163c-4dca-ab08-da86c218ac81.png)
![3](https://user-images.githubusercontent.com/103493005/228504216-6f9373a0-fe6c-45c8-8ce8-794d967676ab.png)

### .NET Version

7.0 or 3.1or maybe more

**Comment by javiercn** [comment]
@QQ1756455668 thanks for contacting us.

Does it reproduce when you are rendering outside docker?
Can you check the browser console for errors? Can you also make sure that the response has the right content-encoding?

**Comment by QQ1756455668** [comment]
There is an interesting phenomenon in local development，Problem only in release mode，

![1](https://user-images.githubusercontent.com/103493005/228558447-d5403aab-b80b-46df-8286-80a7913a078e.png)
![2](https://user-images.githubusercontent.com/103493005/228558461-c9286275-6713-43a7-bb02-9b6861fa28df.png)

**Comment by QQ1756455668** [comment]
Publish to the server, both modes have problems

**Comment by QQ1756455668** [comment]
I can reproduce this problems 100% on vs2022, vs2019, net core 7, net core 3.1，and other computers

**Comment by QQ1756455668** [comment]
> @QQ1756455668 thanks for contacting us.
> 
> Does it reproduce when you are rendering outside docker? Can you check the browser console for errors? Can you also make sure that the response has the right content-encoding?

This problem only exists in docker

**Comment by javiercn** [comment]
@QQ1756455668 Are you running in development when you don't see the encoding issues?

There might be differences with the default encoder across the Operating System. Seems that the Unicode characters are being encoded when running inside the container.

You can register a custom HtmlEncoder instance on the DI container and we will use that.

https://learn.microsoft.com/es-es/dotnet/api/system.text.encodings.web.htmlencoder.create?view=net-7.0#system-text-encodings-web-htmlencoder-create(system-text-unicode-unicoderange())

@GrabYourPitchforks do you have thoughts?

**Comment by javiercn** [comment]
@QQ1756455668 can you include the dockerfile here?

**Comment by QQ1756455668** [comment]
> @QQ1756455668 can you include the dockerfile here?

default docker file

`FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["WebApplication6/WebApplication6.csproj", "WebApplication6/"]
RUN dotnet restore "WebApplication6/WebApplication6.csproj"
COPY . .
WORKDIR "/src/WebApplication6"
RUN dotnet build "WebApplication6.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApplication6.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplication6.dll"]`

**Comment by QQ1756455668** [comment]
![1](https://user-images.githubusercontent.com/103493005/228800222-9c0980a0-d52d-4dd5-9694-abb0781fff6f.png)

**Comment by mkArtakMSFT** [comment]
> Forgot to tell you a detail, You have to create a new page, the default page will have no problem

This is interesting. Can you double check if the encoding of an existing page file is the same as for a newly-created page?

**Comment by QQ1756455668** [comment]
@mkArtakMSFT , @javiercn 
![1](https://user-images.githubusercontent.com/103493005/229676049-032bbc30-532d-423d-b9ae-cbcc6d79e6fa.png)
![2](https://user-images.githubusercontent.com/103493005/229676058-8160e56f-6d6a-47b7-b00c-2e705d1bef71.png)
![3](https://user-images.githubusercontent.com/103493005/229676064-9c1aa905-0bea-4a5c-8ea0-b16f6a7f84f9.png)
![4](https://user-images.githubusercontent.com/103493005/229676071-f3758ed6-14c3-4b0e-bfd5-81c9ceeac934.png)

**Comment by mitchdenny** [comment]
I had a go at reproducing this and couldn't do it. Do you think you could post a minimal repro in a GitHub repository so we can take a look at your exact files? It would also be good to take a look at the request headers that your browser is sending just in case it is some quirk of browser language settings.

**Comment by QQ1756455668** [comment]
> I had a go at reproducing this and couldn't do it. Do you think you could post a minimal repro in a GitHub repository so we can take a look at your exact files? It would also be good to take a look at the request headers that your browser is sending just in case it is some quirk of browser language settings.

OK，I will make a sample update to github，Unrelated to browser settings，Because it is normal in the windows and linux environment, it is not normal in the docker environment。

**Comment by QQ1756455668** [comment]
@mkArtakMSFT  
thanks , you are right, 
I found the answer when I recreated a new solution，I didn't check carefully enough。
Two new files are generated when you create a new page，For example: Index2.cshtml and Index2.cshtml.cs

![1](https://user-images.githubusercontent.com/103493005/230522931-b4a5f9e0-5a14-4cd7-9da0-869a965810c8.png)
![2](https://user-images.githubusercontent.com/103493005/230522939-6d962bb1-05e1-48a8-9cd9-9ed86435081e.png)

when i reset it's page encoding to utf-8 everything works fine

**Comment by QQ1756455668** [comment]
> @mkArtakMSFT , @javiercn ![1](https://user-images.githubusercontent.com/103493005/229676049-032bbc30-532d-423d-b9ae-cbcc6d79e6fa.png) ![2](https://user-images.githubusercontent.com/103493005/229676058-8160e56f-6d6a-47b7-b00c-2e705d1bef71.png) ![3](https://user-images.githubusercontent.com/103493005/229676064-9c1aa905-0bea-4a5c-8ea0-b16f6a7f84f9.png) ![4](https://user-images.githubusercontent.com/103493005/229676071-f3758ed6-14c3-4b0e-bfd5-81c9ceeac934.png)

I have deleted this solution ，so I can't check why
