### ISSUE TITLE
HttpContext.Session.GetString is Always Return Null in .NET Core 6

### ISSUE THREAD

**Issue by memoony** [dotnet/aspnetcore#47476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I'm working on ASP.NET Core 6 and what I am trying to do is: Set my list to session then get session info. But although there is no problem when setting it to session. When I try to get from session with GetString it always returns null.

My Startup.cs:

1. ConfigureServices
![carbon](https://user-images.githubusercontent.com/102434916/228369265-f09d12ed-36b8-40b9-aa4c-1f1c6b9e010d.png)

2. Configure
![carbon (1)](https://user-images.githubusercontent.com/102434916/228369526-7f3eb1b5-f455-4557-a0f4-d3d6d6ec8f53.png)

My UserRepository.cs:
![carbon (2)](https://user-images.githubusercontent.com/102434916/228371192-b9b69f8f-a294-4ea3-a243-b92962b9a88e.png)

Code block in the UserService.cs that I set session and then try to get:
![carbon (3)](https://user-images.githubusercontent.com/102434916/228372864-eae1da47-9c17-4ed7-934a-baa855ca37e4.png)

**Comment by mgravell** [comment]
Is there anywhere where you're *setting* the value as a string? the only place I can see it being set, you're setting a `byte[]`, so I wouldn't *expect* it to fetch as a string - have I misunderstood? also: it looks like you try to fetch as a `string`, and then only if that **succeeds**: fetch it as a `byte[]` - that seems: unusual - is that deliberate?

**Comment by memoony** [comment]
No, you're right. I am setting the value as a list. So, should i use like `httpContextAccessor.HttpContext.Session.Get` (not GetString) when trying to reach session or different way?

**Comment by memoony** [comment]
> Is there anywhere where you're _setting_ the value as a string? the only place I can see it being set, you're setting a `byte[]`, so I wouldn't _expect_ it to fetch as a string - have I misunderstood? also: it looks like you try to fetch as a `string`, and then only if that **succeeds**: fetch it as a `byte[]` using the same key - that seems: unusual, as I wouldn't expect both to succeed - is that deliberate?

No, you're right. I am setting the value as a list. So, should i use like httpContextAccessor.HttpContext.Session.Get (not GetString) when trying to reach session or different way?

**Comment by mitchdenny** [comment]
It probably doesn't matter in this context, here is the code for the `GetString(...)` extension method:

https://github.com/dotnet/aspnetcore/blob/83728cac8c2feb5b81f2402c3d83c32f9239c22c/src/Http/Http.Extensions/src/SessionExtensions.cs#LL62C24-L62C24

It would be good to get a minimal repro in a GitHub repository that strips out anything that isn't pertinent to the issue being reported (for example the user repository and database probably aren't relevant).
