### ISSUE TITLE
Add NativeAOT support for JwtBearer Authentication

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#47487]
The following program produces AOT warnings and doesn't work after being published to NativeAOT:

```C#
using System.Security.Claims;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication().AddJwtBearer();
builder.Services.AddAuthorization();

var app = builder.Build();

app.MapGet("/", () => "Hello, World!");
app.MapGet("/secret", (ClaimsPrincipal user) => $"Hello {user.Identity?.Name}. My secret")
    .RequireAuthorization();

app.Run();
```

We should enable this to work in ASP.NET 8 with NativeAOT.

Underlying issues:

- [x] https://github.com/dotnet/aspnetcore/issues/47410
- [ ] https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2035

**Comment by eerhardt** [comment]
> https://github.com/dotnet/aspnetcore/issues/47410

We don't need to fix #47410 issue to enable this scenario. The app will be larger than it needs to be, but it will still work once https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2035 is implemented.

**Comment by halter73** [comment]
This now works with the latest rc1 SDKs and `Microsoft.AspNetCore.Authentication.JwtBearer`.

```csharp
using System.Security.Claims;
using System.Text.Json.Serialization.Metadata;

var builder = WebApplication.CreateBuilder(args);

builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine();
});

builder.Services.AddAuthentication().AddJwtBearer();
builder.Services.AddAuthorization();

var app = builder.Build();

app.MapGet("/", () => "Hello, World!");
app.MapGet("/secret", (ClaimsPrincipal user) => $"Hello {user.Identity?.Name}. My secret")
    .RequireAuthorization();

app.Run();
```

You do need to configure the `TypeInfoResolver` even though there's no JSON, but that appears to be a different issue #49855.

**Comment by eerhardt** [comment]
We need the app to be able to be published with no warnings in order to officially support this scenario. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2035 will allow for no warnings.

**Comment by eerhardt** [comment]
This is now complete and works with NativeAOT. We have https://github.com/aspnet/Benchmarks/blob/5ea00ac8d1471088ff96831156f7c8533da8f514/src/BenchmarksApps/TodosApi/TodosApi.csproj#L19 which uses this in a benchmark app.
