### ISSUE TITLE
[Signalr-Cpp-Client] Having trouble referencing and using the lib when cross-compiling for target linux-arm (RPi4)

### ISSUE THREAD

**Issue by Wasenshi123** [dotnet/aspnetcore#47495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to build on the board itself, my app works fine on RPi4.

But when I try to cross-compile my app from Ubuntu to RPi4 (arm-linux-gnueabihf), the app's broken and crashes. (cannot connect to server, random crashes on startup, or some time shortly after)

### Steps To Reproduce

- Use crosstool-ng to build a toolchain for RPi4
- Reference and use signalr in your app
- Complie & Build the app using cmake with the toolchain
- Run the app on RPi4 board
- Try to connect to server and make the code use the lib

### Exceptions (if any)

segmentation fault / malloc() ... / Bus error

### Note
- I use Ubuntu 20 distro on WSL2 , window 11(x64) as a Host machine.
- I've manually compiled the signalr lib on the RPi4 by myself.
- I use the default cpprest package that comes with the distro (sudo apt-get install libcpprest-dev)

(and my app use thread a lot, if that helps)

**Comment by BrennanConroy** [comment]
Looks like you figured it out, closing.
