### ISSUE TITLE
In Blazor's EditContext class, why is there no MarkAsModified method?

### ISSUE THREAD

**Issue by acamlibe** [dotnet/aspnetcore#47497]
I have an issue where I have an EditForm, and within that EditForm, a custom grid component that modifies a collection within my model class that the EditForm's EditContext tracks. When items are added, removed, or updated within this custom grid component, it does not set the EditContext's state as modified. 

One solution would be to explicitly state the EditContext to be modified, but there doesn't seem to be method for that. Is there any solution I can use to set it?

**Comment by linkdotnet** [comment]
Hey @acamlibe,

couldn't you use something like [`EditContext.NotifyFieldChanged`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.editcontext.notifyfieldchanged?view=aspnetcore-7.0) method?

So something like this should work: `editContext.NotifyFieldChanged(new FieldIdentifier(YourModel, nameof(YourModel.Collection))));`
