### ISSUE TITLE
Errors CS0115, CS0117 and CS0103 in razor.cs partials and hot reload fails.

### ISSUE THREAD

**Issue by jburman** [dotnet/aspnetcore#47498]
**Scenario:**

1) Blazor hybrid app hosted in WinForms.
2) Run the app with: dotnet watch run
3) Hot reload was working for a short time
4) Now, when making a change in a razor page, dotnet watch spams out a bunch of errors that looks like the code from all of the razor.cs partials in my project are no longer associated with the corresponding .razor code.  

Here are some examples of different errors...

- error CS0117: 'object' does not contain a definition for 'OnInitializedAsync'
- error CS0117: 'object' does not contain a definition for 'OnParametersSet'
- error CS0117: 'object' does not contain a definition for 'OnAfterRenderAsync'
- error CS0103: The name 'InvokeAsync' does not exist in the current context
- error CS0103: The name 'StateHasChanged' does not exist in the current context
- error CS0115: 'PasswordChange.OnInitializedAsync()': no suitable method found to override
etc. etc.
Pretty much any symbol defined in the .razor markup is not resolved, and this occurs for every single component in the project.

**====================================
Project Information
====================================**
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;Debug_CORECLR;Release_CORECLR</Configurations>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

**====================================
System Information
====================================**
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.403\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

**Comment by frownieebrownie** [comment]
bump - I'm getting CS0103 errors for every razor.cs file in my Blazor server app when dotnet watch attempts to hot reload. Application runs just fine initially.

**Comment by garrettlondon1** [comment]
^ bump I am getting the same CS0246, CS0115, RZ10012, in a lot of .razor files.

**Comment by tmat** [comment]
@jburman Is this still an issue with .NET 8 SDK? If so, please share your project and steps to reproduce the issues (exact changes made).
