### ISSUE TITLE
Should razor support syntax for call child component method from parent component?

### ISSUE THREAD

**Issue by SparrowWithBrokenWing** [dotnet/aspnetcore#47500]
I have an issue when writing this code for a carousel component: 
```
@code{
private IList<RenderFragment> _items = new List<RenderFragment>();

public RenderFragment AddNewItem {
set{
_items.Add(value);
}
}
}

@foreach (var item in _items){
@item
}
```

(Demo.razor)
In parent component, if I called:

```
<Demo>
<AddNewItem>1<br></AddNewItem>
<AddNewItem>1<br></AddNewItem>
<AddNewItem>1<br></AddNewItem>
</Demo>

```
this code would work as expected (sr because my english)

But what if i want instead of render all item in _items, the item is rendered base on current item index? I mean, instead of foreach loop like above, we have something like this?

```
@code{
private int _currentItemIndex = 0;
}
@_items[_currentItemIndex]

```
It will work as expected too. But what i want is something ... crazier? Should item is being showed know it is showing? I mean, when render the item, should something like OnShowed function called?

```
@code{
private class DemoItem {
public RenderFragment Content {get;set;}
public Action OnShowed {get;set;}
}
private IList<DemoItem> _items = new List<DemoItem>();


[Parameter]
public RenderFragment AddNewItem {
set{
_items.Add(new DemoItem(value, /*need Action instance here*/));
}
}
```
The problem is there is no way i can pass an action instance include with render fragment instance to child component at same time. So what i suggest is, can blazor support same syntax of render fragment parameter for child component method? So it will look like this:

```
<Demo>
<AddNewItem OnShowed="@(()=>{})">1<br></AddNewItem>
<AddNewItem>2<br></AddNewItem>
</Demo>

```
The add new item can be a method that take render fragment and action instance as parameter, or i don't know, some how that i can include an action when define a render fragment parameter. I don't know what should it be yet, but in parent component, it need to be something that i can pass other information to child component.

So, what do you think? Can blazor support this? Hope you answer me soon.
(AspNetCore 3.1)

**Comment by javiercn** [comment]
@SparrowWithBrokenWing thanks for contacting us.

I think you can use `RenderFragment<T>` for your use case. See [templated components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-7.0) the T can be an object where you pass all the data you need.

Another option is to use `@ref` to capture a reference to the component and call methods on it within `OnAfterRender` (firstRender).

If you are asking to provide a way for you to instantiate components and have Razor render them, we are not planning to support that ever, as it goes against the core framework rendering model that are fundamental for correctness and performance.

**Comment by SparrowWithBrokenWing** [comment]
Hi @javiercn, thanks for your respond.
Please tell me if you think i wrong some where. When i read about template component, what i feel is that the child component need to provide value for context variable to let it can be used in parent component, and that is not the true way to provide data to child component. I'm just not sure about this, so feel free to let me know that i'm wrong.
Also, writing child component as a .cs file is other solution. But it seem unconvenient to write like html in c sharp code. That's why i want some way to do it in razor code.
And you mention about @ref too. Yes, this could be solution. But as i mention above, it's hard to go for html in c sharp code. Also, when i want to pass a renderfragment for my child component, if i need a function from my child component to provide addtion data, i also need to provide something that can recall back the render fragment. Should we need to do that?
I know that you won't support. So what can i do to make something like my own rendering engine? Something that extend the availiable ability of Razor?
Hope you don't wait too long for my respond.
Hope you have a good day.
Also, sorry for my terrible English. I hope you can understand what i'm trying to say.

**Comment by MackinnonBuck** [comment]
We don't plan on changing the product to accommodate this specific suggestion, but if you provide an example justified in terms of the user experience, we may consider it. We currently recommend taking the previously-suggested approaches to solve your problem. Thanks!
