### ISSUE TITLE
Grpc transcoding in .net 7 - cannot post repeated field

### ISSUE THREAD

**Issue by victorsauter** [dotnet/aspnetcore#47510]
Hi, 

I'm trying to use the new great feature "grpc json transcoding", but I'm getting an error when I try to pass to the body a repeated field. 

My proto : 
```
syntax = "proto3";

import "Protos/google/api/annotations.proto";

option csharp_namespace = "GrpcGreeter";

package greet;

// The greeting service definition.
service Greeter {
  rpc AddGreeting (AddRequest) returns (AddReply){
    option (google.api.http) = {
      post: "/greet"
      body: "greetings"
    };
  }
}

message AddRequest {
  repeated Greeting greetings = 1;
}

message AddReply {
  repeated Greeting greetings = 1;
}

message Greeting {
  string name = 1;
  string level = 2;
  string comment = 3;
}
```

The error :
![image](https://user-images.githubusercontent.com/57530727/228871853-771069c2-41b4-4586-adb1-6c6bc6d1bcb6.png)

So, if i understand correctly, it's not supported yet, am I right ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2deac78a-8c57-7891-4bd0-8842f5e2af07
* Version Independent ID: 2deac78a-8c57-7891-4bd0-8842f5e2af07
* Content: [Configure HTTP and JSON for gRPC JSON transcoding ASP.NET Core apps](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/json-transcoding-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/json-transcoding-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
I think this is an issue in gRPC JSON transcoding. Transferred to dotnet/aspnetcore repo.

**Comment by JamesNK** [comment]
A bug prevents binding a JSON body to a repeating collection of messages. It was tested with primitive values (i.e. a collection of strings) but not a collection of messages.

This will be fixed in .NET 8. Will look to see if it can be also fixed in a .NET 7 servicing release.

**Comment by victorsauter** [comment]
Okay great ! Thanks a lot :)
