### ISSUE TITLE
Windows Authentication For Kestrel: The name NegotiateDefaults does not exists in the current context.

### ISSUE THREAD

**Issue by Octania** [dotnet/aspnetcore#47520]
Using the below article.
I am Attempting to implement Windows Authentication for Kestrel for ASPNET Core API NET7.
[174873](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-7.0&tabs=visual-studio#kestrel)

In the AddAuthentication  extension method I get the following error.
_The name NegotiateDefaults does not exists in the current context._

There are no documentation in the article about this error.

`
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();`

**Comment by Tratcher** [comment]
NegotiateDefaults is here:
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Negotiate/src/NegotiateDefaults.cs
Ensure you have a using statement for the namespace, as well as a package dependency.
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Negotiate/
