### ISSUE TITLE
Blazor United: Auto Generate API Layer and Frontend actions, so that a single component can work in both server and client render modes

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#47529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I added a comment about this, but just re-iterating it here for more visibility: https://github.com/dotnet/aspnetcore/issues/46636#issuecomment-1487692388

Hey All! Not sure if this is discussed / requested anywhere, but is it possible to have both the API layer and the frontend glue code calling the API layer auto generated?

What I am thinking here is to have methods defined with data attributes like: "[ServerOnly] [API]" or something which will ensure these methods are only run on the server and the framework can auto generate the API layer for these methods and also generate the frontend glue code ( potentially using source generators? )

This way we can have a single component work in both server render mode ( any action calls the method directly ) and client render mode ( any action calls the auto generated API client )

**Comment by MackinnonBuck** [comment]
Thanks for reaching out! This is something we're considering and tracking in https://github.com/dotnet/aspnetcore/issues/46400. Going to close this issue as a duplicate.
