### ISSUE TITLE
Sunset Microsoft.AspNetCore.ConcurrencyLimiter

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#47532]
ConcurrencyLimiter has
* [No docs](https://learn.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-7.0&terms=ConcurrencyLimiter&category=Documentation)
* A [small web presence](https://www.google.com/search?q=%22Microsoft.AspNetCore.ConcurrencyLimiter%22)
* Looks obsolete with the [new rate limiting middleware](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0) in .NET 7.

Can we mark `Microsoft.AspNetCore.ConcurrencyLimiter` obsolete and/or stop publishing the https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/ package in .NET 8?

**Comment by Tratcher** [comment]
Standard procedure would be to obsolete Warning the APIs in 8, and remove the package in 9.

**Comment by mitchdenny** [comment]
Merged. Breaking change announcement put out.
