### ISSUE TITLE
Dotnet hosting bundle 6.0.15 fails with error: 0x80070643, AspNetCoreModuleV2_x64

### ISSUE THREAD

**Issue by dariobratic** [dotnet/aspnetcore#47534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On server I have installed dotnet hosting bundle 2.2.8 and if I want to install 6.0.15 I am getting:
Error 0x80070643: Failed to install MSI package.

If I try to Repair:
Error 0x80070002: Failed to cache payload: AspNetCoreModuleV2_x64

Full logs for both cases are attached.
[dd_dd_DotNetCoreWinSvrHosting__20230402175744_000_WindowsServerHostingBundleOptions.msi.log](https://github.com/dotnet/aspnetcore/files/11132718/dd_dd_DotNetCoreWinSvrHosting__20230402175744_000_WindowsServerHostingBundleOptions.msi.log)
[Repair - dd_dd_DotNetCoreWinSvrHosting__20230402181307.log](https://github.com/dotnet/aspnetcore/files/11132719/Repair.-.dd_dd_DotNetCoreWinSvrHosting__20230402181307.log)
[Repair - dd_dd_DotNetCoreWinSvrHosting__20230402181307_001_AspNetCoreModuleV2_x64.log](https://github.com/dotnet/aspnetcore/files/11132720/Repair.-.dd_dd_DotNetCoreWinSvrHosting__20230402181307_001_AspNetCoreModuleV2_x64.log)
[Repair - dd_dd_DotNetCoreWinSvrHosting__20230402181307_000_WindowsServerHostingBundleOptions.msi.log](https://github.com/dotnet/aspnetcore/files/11132721/Repair.-.dd_dd_DotNetCoreWinSvrHosting__20230402181307_000_WindowsServerHostingBundleOptions.msi.log)
![Screenshot_3](https://user-images.githubusercontent.com/40833249/229365448-5bcf78a5-4289-43c7-a54e-8ff81d92a400.png)
[dd_dd_DotNetCoreWinSvrHosting__20230402175744.log](https://github.com/dotnet/aspnetcore/files/11132722/dd_dd_DotNetCoreWinSvrHosting__20230402175744.log)
[dd_dd_DotNetCoreWinSvrHosting__20230402175744_001_AspNetCoreModuleV2_x64.log](https://github.com/dotnet/aspnetcore/files/11132723/dd_dd_DotNetCoreWinSvrHosting__20230402175744_001_AspNetCoreModuleV2_x64.log)

Might be related to:
https://github.com/dotnet/aspnetcore/issues/19536
https://github.com/dotnet/runtime/issues/517
https://github.com/dotnet/aspnetcore/issues/28029

### Exceptions (if any)

Error 0x80070643: Failed to install MSI package.
Error 0x80070002: Failed to cache payload: AspNetCoreModuleV2_x64

### .NET Version

6.0.407

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. ASP.NET Core 2.2 is out of support at this point. So even if this is a bug related to it, we won't be servicing it. Hence, the best path forward would be to uninstall it manually and install the 6.0 afterwards.
