### ISSUE TITLE
Stop Calling JSON GetTypeInfo with the runtime type

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#47548]
In both the RDF and RDG we have code like the following:

https://github.com/dotnet/aspnetcore/blob/0b10e1349063b1b5b39dd0435509abb52cc81d90/src/Shared/RouteHandlers/ExecuteHandlerHelper.cs#L36-L53

This doesn't work with the unspeakable types behavior that was added to System.Text.Json - https://github.com/dotnet/runtime/pull/83631. In particular, `GetTypeInfo(runtimeType)` doesn't work when using unspeakable types.

We started using the "runtimeType" back in .NET Core 3.0 (https://github.com/dotnet/aspnetcore/commit/bed3542a9ba7b1504882e7d34e2b3d6af63afdb5) when we switched from Json.Net to System.Text.Json and wanted to maintain the polymorphic serialization behavior of Json.Net (ex. if the "declared type" was a base type, and the endpoint returned a derived type, we want to serialize all the derived properties). This strategy was adopted by Minimal APIs as well, when they were introduced.

This approach was then changed early in .NET 8 in order to support "System.Text.Json Polymorphism" features that were added in .NET 7. (See https://github.com/dotnet/aspnetcore/pull/45405). The strategy used by that PR was: "when a `JsonPolymorphismOptions` is detected, uses the declared type's JsonTypeInfo to call the serializer." When it isn't detected, use the "runtimeType"'s `JsonTypeInfo` to maintain the above polymorphic serialization behavior to not break backwards compatibility.

In order to support all these scenarios, we need to tweak our JSON serialization strategy. After consulting with @brunolins16 and @eiriktsarpalis, the strategy we have settled on is:

1. When a `JsonPolymorphismOptions` is detected (or when polymorphism is not possible - ex. ValueType, sealed, etc), use the declared type's `JsonTypeInfo` to call the serializer.
    - This is no change to what we do today in .NET 8.
2. When the above rule doesn't work, instead of using the "runtimeType", we will serialize the value "as object" - i.e. `JsonSerializer.Serialize<object>(value, options)`.
    - This will allow System.Text.Json to control the behavior of serialization. It will allow to fix issues like:
        - "unspeakable type support" https://github.com/dotnet/runtime/issues/82457
        - Polymorphic Type Resolving https://github.com/dotnet/runtime/issues/77532
        - Along with keeping the above behavior consistent with Json.Net before .NET Core 3.0.

A drawback to this strategy is that `JsonSerializer.Serialize<object>(value, options)` is not guaranteed to be trim/AOT-compatible, and thus it is annotated as incompatible. We will need to suppress these warnings in ASP.NET, which is OK because of the other mechanisms we are adding to support trimming/AOT - https://github.com/dotnet/runtime/issues/83279.

However, we can't do this until the [JSON Trimming feature switch](https://github.com/dotnet/runtime/pull/83844) is merged, or we will regress the AOT size and warnings. We may also need to wait for [System.Text.Json Polymorphic Type Resolving Issue](https://github.com/dotnet/runtime/issues/77532).

**Comment by brunolins16** [comment]
If the polymorphism behavior is now cover inside STJ and the call to the `GetTypeInfo` is not needed anymore, should this also be removed?

https://github.com/dotnet/aspnetcore/blob/c6c2d95d8eb337289848ca575144439ad2ac8cf7/src/Http/Http.Extensions/src/JsonOptions.cs#L28

**Comment by eerhardt** [comment]
> If the polymorphism behavior is now cover inside STJ and the call to the GetTypeInfo is not needed anymore, should this also be removed?

We will still have other calls to `GetTypeInfo`, which I believe are still needed. For example:

https://github.com/dotnet/aspnetcore/blob/0b10e1349063b1b5b39dd0435509abb52cc81d90/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1141

**Comment by eerhardt** [comment]
@captainsafia - I can take this. I have a handful (3 maybe?) JSON changes in the works:

1. react to https://github.com/dotnet/runtime/pull/84411#discussion_r1160476006
2. Remove our feature switch and instead use https://github.com/dotnet/runtime/pull/83844#event-8939016164
3. This change.

**Comment by captainsafia** [comment]
@eerhardt Awesome! Is it OK to put this in the preview4 milestone?

**Comment by eerhardt** [comment]
Done.
