### ISSUE TITLE
Need a secure way to do client cache storage with ServerPrerendered

### ISSUE THREAD

**Issue by wrharper-AASP** [dotnet/aspnetcore#47556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If this is not possible and the feature cannot be implemented, what is the suggested way to have client-side cache for potential PII exposed information? Over time, my system will have extremely large amounts of data displayed per a user. This will need to be cached in some way in order to stay in a usable state.

### Describe the solution you'd like

Need a way to securely store client-side with possible PII for large data caches to cut down on server overhead.

**Comment by wrharper-AASP** [comment]
The app needs to be able to check if there is a client cache first and just use it and the server will detect any changes and add in a additive way or download everything if it is first time use. It would also need version checking so it re-downloads in case core server-side parts change.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Maybe the [ProtectedBrowserStorage](https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-7.0&pivots=server#aspnet-core-protected-browser-storage) is a good fit for your scenario?
As a general note, you should be very careful about storing PII data on the client.
