### ISSUE TITLE
Blazor Sections don't handle SectionName correctly

### ISSUE THREAD

**Issue by Flachdachs** [dotnet/aspnetcore#47552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sections in Blazor were first designed with a `SectionId` as a way to declare which `SectionContent` should be rendered in which `SectionOutlet`. Then a `SectionName` was introduced as a second way. Both SectionContent and SectionOutlet have an internal field `_registeredIdentifier` respectively `_subscribedIdentifier`. In the method `IComponent.SetParametersAsync(...)` a local variable `identifier` holds either SectionName or SectionId after deciding which on is used. But then `_registeredIdentifier` and also `_subscribedIdentifier` is assigned with `SectionId`, which was correct as SectionId was the only way. This should now be `identifier` instead. Otherwise these components can't Unsubscribe/RemoveProvider correctly from the `SectionRegistry` when one uses `SectionName` instead of `SectionId`. You can also see undesired behavior when using SectionName. When a component that uses a SectionContent with SectionName is removed the content in the corresponding SectionOutlet isn't cleared as it is the case when using SectionId instead.

These two lines are affected:
https://github.com/dotnet/aspnetcore/blob/cb71b0015bca4c3f50bb58ffe7fc48075faa9bea/src/Components/Components/src/Sections/SectionContent.cs#L78

https://github.com/dotnet/aspnetcore/blob/cb71b0015bca4c3f50bb58ffe7fc48075faa9bea/src/Components/Components/src/Sections/SectionOutlet.cs#L67

### Expected Behavior

When both of the code lines above are changed to `identifier` instead of `SectionId` the behavior is correct.

### .NET Version

current preview of .NET 8

**Comment by surayya-MS** [comment]
Thanks for catching this bug @Flachdachs !

**Comment by seyfeb** [comment]
This is probably the reason why hot reloading fails with

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: There is already a subscriber to the content with the given section ID 'MySection'.
System.InvalidOperationException: There is already a subscriber to the content with the given section ID 'MySection'.
   at Microsoft.AspNetCore.Components.Sections.SectionRegistry.Subscribe(Object identifier, ISectionContentSubscriber subscriber)
   at Microsoft.AspNetCore.Components.Sections.SectionOutlet.Microsoft.AspNetCore.Components.IComponent.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

when using `SectionName` for identifying the sections. Can anyone confirm this?

**Comment by Flachdachs** [comment]
@seyfeb When using the SectionName the components can't unregister correctly, so another registration with the same name has to fail. But you can use the SectionId without any problems, it's even better than using magic strings.

**Comment by seyfeb** [comment]
I figured that out from your opening post in this issue and it works without problems. I just wanted to make sure that the error message is a consequence so I do not accidentally open a duplicate issue. 👍
