### ISSUE TITLE
[Route Tooling] Versioned Routes

### ISSUE THREAD

**Issue by commonsensesoftware** [dotnet/aspnetcore#47564]
## Background

Per the [Route Tooling Enhancments](https://devblogs.microsoft.com/dotnet/aspnet-core-route-tooling-dotnet-8/#ambiguous-minimal-api-and-web-api-route-analyzer) announcement for .NET 8, a new analyzer will provide a warning for an ambiguous route whenever it is detected; for example:

```c#
app.MapGet("/product/{name}", (string name) => ...);
app.MapGet("/product/{id}", (int id) => ...);
```

The details of this issue were discussed in #45223 and the current implementation was merged as part of #45582.

## Versioned Routes

Versioned endpoints will often use duplicate route templates. Under the default configuration, these would result in ambiguous matches; however, once API versioning is applied, the endpoints are no longer ambiguous. Otherwise _duplicate_ route templates and endpoints are disambiguated by one or more API versions.

**Minimal API**

```c#
var app = builder.Build();
var products = app.NewVersionedApi();
var v1 = products.MapGroup("/product").HasApiVersion(1.0);
var v2 = products.MapGroup("/product").HasApiVersion(2.0);

// ~/product/{name}?api-version=1.0
v1.MapGet("/{name}", (string name) => new Product());

// ~/product/{id}?api-version=2.0
v2.MapGet("/{id}", (string id) => new Product());
```

**Controller-based API**

```c#
[assembly: ApiController]

namespace Controllers.V1
{
    [ApiVersion(1.0)]
    [Route("[controller]")]
    public class ProductController : ControllerBase
    {
        // ~/product/{name}?api-version=1.0
        [HttpGet("{name}")]
        public IActionResult Get(string name) => Ok(new Product());
    }
}

namespace Controllers.V2
{
    [ApiVersion(2.0)]
    [Route("[controller]")]
    public class ProductController : ControllerBase
    {
        // ~/product/{id}?api-version=2.0
        [HttpGet("{id}")]
        public IActionResult Get(string id) => Ok(new Product());
    }
}
```

Despite having the same route template, these endpoints are not ambiguous. A duplicate combination of route template and API version will yield an ambiguous match the same as the default behavior. An endpoint can also be API _version-neutral_, which means it accepts any and all API versions for a particular route template, including no API version at all. An API _version-neutral_ endpoint combined with any other endpoint with the same route template will also result in an ambiguous match.

## Conundrum

The current rules indicate that the analysis level will be a warning, but it has been proposed that the level be an error. Using this rule set will result in false positives for properly versioned, unambiguous route templates. It would appear that the only possible, current solution is to:

- Ignore the warnings
- Disable the analysis rule

Both of these options seem subpar and contrary to the goals of identifying ambiguous route templates. What is the expected approach for extenders to perform in order to provide additional or custom disambiguation logic?

-----

cc: @captainsafia , @halter73, @JamesNK

**Comment by halter73** [comment]
> ```csharp
> // ~/product/{name}?api-version=1.0
v1.MapGet("/{name}", (string name) => new Product());
>
> // ~/product/{id}?api-version=2.0
v2.MapGet("/{id}", (string id) => new Product());
> ```

This wouldn't fire the analyzer because `v1` is different from `v2`, right? I thought we were pretty conservative with it.

I could see this being an issue if someone used the `IEndpointConventiomBuilder` to add additional constraints, but I thought we wouldn't fire the analyzer given any extension methods either.

That said, I don't think it would be the end of the world to remove the analyzer if we find it does produce false positives.

**Comment by commonsensesoftware** [comment]
To be fully transparent, I haven't tried executing it - yet. Are all the necessary bits out in a preview release? I can formally try it out and report back.

Based on my understanding of the rule, I _would_ expect it to fire. Consider a vanilla out-of-the-box scenario:

```c#
var product = app.MapGroup("/product");

// ~/product/{name}
product.MapGet("/{name", (string name) => new Product());

// ut-oh! duplicate
// ~/product/{id}
app.MapGet("/product/{id}", (string id) => new Product());
```

The grouping constructs are just a convenience to avoid repeating a bunch of steps. You can't fully validate for ambiguous route templates until they are expanded and compared. If the validation will only occur at a specific level of grouping, then I think we are covered; however, that would mean there are some edge cases that are missed. Is such an edge case expected to be caveat emptor? The overall experience is still _better_. I also suspect if that is the case, it is only a matter of time before the community asks to call out the edge scenarios; however, addressing them could be punted to a future timeline.

**Comment by JamesNK** [comment]
I suggest you try it. The analyzer is very conservative. It only warns in some situations to avoid the possibility of false positives. Any difference in metadata or route group stops the route from being flagged.

**Comment by commonsensesoftware** [comment]
I set everything up and it generally appears to behave as expected/described. 🎉 I did notice a discrepancy that I thought I would share. Let's assume you have:

```c#
var app = builder.Build();
var orders = app.NewVersionedApi( "Orders" );

// 1.0
var ordersV1 = orders.MapGroup( "/api/orders" )
                     .HasDeprecatedApiVersion( 0.9 )
                     .HasApiVersion( 1.0 );
```

Adding the exact same versioned routes under the same group is correctly flagged as expected:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/11765008/230483275-db76e97a-102c-4477-9f30-0dfd32691444.png">

However, using the same variation as demonstrated with `/product/{id}` vs `/product/{name}`, no warning is triggered:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/11765008/230483543-97211319-2ddd-4ec9-afc8-75432e91a0d7.png">

That does not seem correct. The example presented is based on [this API Versioning example](https://github.com/dotnet/aspnet-api-versioning/blob/2487953bce4368f02e3ae69e29e86c33c037e9b2/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs#L58).

Once controllers are supported, I'm happy to test out that behavior as well.

**Comment by cataggar** [comment]
I create a mock API for our Azure Resource Provider (RP) using Rocket in Rust a couple of years ago (MS internal [link](https://msazure.visualstudio.com/One/_git/Azure-Dedicated-AVS?path=/src/fct/mock_api/src/v2022_05_01/routes.rs)). It supports routing with query params like `?api-version=2022-05-01`. I'm interested in making a similar tool in C# using this feature. In the examples above, it does not appear that the version is a string. How will Azure versions like `2022-05-01` work?

For tests, would it be possible to get both the matched route name and api version? Right now, I could use some help just getting the route name back.
https://stackoverflow.com/questions/76153365/in-asp-net-core-minimal-api-how-can-you-get-the-route-name

**Comment by commonsensesoftware** [comment]
@cataggar this question _might_ be better suited for the [API Versioning repo](https://github.com/dotnet/aspnet-api-versioning/discussions) directly. In accordance with the Microsoft REST Guidelines and the [API Versioning documentation](https://github.com/dotnet/aspnet-api-versioning/wiki/Version-Format), a date only API version, like those used by Azure, are fully supported.

Route names are internal to the server and not known to clients; it's an implementation detail. While it _might_ be possible to get for a unit test, I don't know that it's all that useful. You should also know that the route table and entry names are **not** _API version aware_. This means that the `"HelloWorld"` route name will typically only work for a single API version. If you expect to pair an API version and route name, then you will likely have to create your own route naming convention such as `"HelloWorldV1"` and `"HelloWorldV2"` or `"HelloWorld20220501"` and `"HelloWorld20230501"`.
