### ISSUE TITLE
Run ASP.Net Core on Mobile OSs like Ionic capacitor

### ISSUE THREAD

**Issue by reader-man** [dotnet/aspnetcore#47565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It would be fantastic if you could make ASP.Net Core Run on Mobile OSs, like ionic capacitor:
https://capacitorjs.com/

### Describe the solution you'd like

It would be fantastic if you could make ASP.Net Core Run on Mobile OSs, like ionic capacitor:
https://capacitorjs.com/

**Comment by danroth27** [comment]
We support building native hybrid apps with Blazor & .NET in .NET MAUI. We call this pattern [Blazor Hybrid](https://aka.ms/blazor/hybrid), where your Blazor components run natively in the app and then render to a local web view control. This is very similar to how frameworks like Capacitor work. Let us know if this meets your needs!

Supporting ASP.NET Core in native mobile apps is being tracked separately by https://github.com/dotnet/aspnetcore/issues/35077.
