### ISSUE TITLE
Microsoft.Authentication.WebAssembly.Msal: Trigger AuthenticationStateChanged event when initialized from browser cache

### ISSUE THREAD

**Issue by chandra-rayaprol** [dotnet/aspnetcore#47574]
In the Blazor WebAssembly Project, I'd like to add some initialisation code based on authentication status. Currently, the event 'AuthenticationStateProvider.AuthenticationStateChanged' is only triggered  when the user explicitly logs in or logs out programmatically, and not  when the authentication is initialised from the browser cache. 

Is it possible to implement this enhancment to trigger this event when authentication information is retrieved from the browser cache? or could you please recommend another way to initialize  any auth dependent services?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you have some custom code which is used to initialize the auth state from the browser cache?
If you do it form within your custom AuthenticationStateProvider implementation, you can call the [NotifyAuthenticationStateChanged](https://github.com/dotnet/aspnetcore/blob/ff2241b006bbe28d2b8f642028fca3ba18e8ec1a/src/Components/Authorization/src/AuthenticationStateProvider.cs#L27) method to inform about it and the change will propagate throughout your application properly.

**Comment by Raysapps** [comment]
I have initialized the required options in the method "AddMsalAuthentication" to cache the authstate. Please refer to the sample at https://github.com/Raysapps/B2CCacheAuth.git. This sample displays the claims in the MainLayout when the user has logged in successfully. The authstate field is initialized in the OnAuthenticationStateChanged handler in the MainLayout.

Please note the following observations:

When a user logs in by signing in the browser, OnAuthenticationStateChanged is triggered and the claims are displayed in the MainLayout.
After closing the browser and restarting the application, the application is still in the logged-in state, but the authstate is not initialized, and no claims are displayed on the MainLayout.
I just want to know if it is possible to trigger the OnAuthenticationStateChanged handler at least once when the authstate is initialized from the browser cache, not necessarily in the MainLayout, but while the application is loading?

**Comment by mkArtakMSFT** [comment]
Looks like the problem here is in your own code. Instead of trying to get the authentication state from within the handler, you should call a service that is passed in through the DI (AuthenticationStateProvider) and query it for an updated state in the `OnInitializedAsync` handler.
