### ISSUE TITLE
Setting route order imperatively

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#47579]
## Background and Motivation

People frequently ask how to change a route's order. Today this is only easy with attribute routing, not minimal APIs.

The workaround is: `app.Map("/api/v1/users", emptyDelegate).Add(static builder => ((RouteEndpointBuilder)builder).Order = 1);`

This comes up in YARP, migrations, internal customers, and external: https://github.com/dotnet/aspnetcore/issues/39241.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

public static class RoutingEndpointConventionBuilderExtensions
{
+    public static TBuilder WithOrder<TBuilder>(this TBuilder builder, int order) where TBuilder : IEndpointConventionBuilder;
}
```

## Usage Examples

```csharp
app.Map("/api/v1/users", ignoredDelegate);
app.Map("/api/v1/users", emptyDelegate).WithOrder(-1);
```

## Risks

Not all routes support order. This would throw when used on a builder that didn't cast to RouteEndpointBuilder.

@danroth27

**Comment by Kahbazi** [comment]
@Tratcher Could I send a PR for this when the API got approved?

**Comment by halter73** [comment]
It's very evident from reading the code that they went out of their way not to expose `Order` outside of MVC. I wonder if @JamesNK @davidfowl or @rynowak have context on the reasoning.

Personally, I like making it easy to override endpoints if you want to using order. I've written the workaround code a number of times myself, but maybe it's a footgun.

**Comment by davidfowl** [comment]
I don't see an issue with this API.

**Comment by rynowak** [comment]
> It's very evident from reading the code that they went out of their way not to expose `Order` outside of MVC. I wonder if @JamesNK @davidfowl or @rynowak have context on the reasoning.

Aside from being a footgun (it definitely is), order can have a surprising impact on performance for a really big route table. Those are some of the reasons why didn't make it **obvious** how to use order. You shouldn't need it that often.

No concerns here, if the question comes up often then it should be made easier.

**Comment by JamesNK** [comment]
What are scenarios where this would be used? In this issue - https://github.com/dotnet/aspnetcore/issues/39241 - there are two ambiguous routes, and setting the order means one will never be called. I wonder why someone would want to do that.

Could `MapFallback` be used instead? That sets order to the lowest possible value.

**Comment by Tratcher** [comment]
@Kahbazi This is ready, want to send a PR now?

**Comment by Kahbazi** [comment]
> @Kahbazi This is ready, want to send a PR now?

@Tratcher I will send a PR next week if it's not too late.

**Comment by Kahbazi** [comment]
> > @Kahbazi This is ready, want to send a PR now?
> 
> @Tratcher I will send a PR next week if it's not too late.

@Tratcher I finally send a PR for this. What a long weeeek! 😅
