### ISSUE TITLE
add database and table by wizard in blazor united

### ISSUE THREAD

**Issue by sardar97** [dotnet/aspnetcore#47592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

add models by wizard from database 

### Describe the solution you'd like

add database and tables by wizard i mean 
add models by wizard in blazor like .Net MVC or 
like java jmix .

### Additional context

please look up java jmix way to add table and page and form by wizard. and make blazor work like it

**Comment by javiercn** [comment]
@sardar97 thanks for contacting us.

This is a tooling request, so you'll get a better and faster answer if you file this issue through the [Visual Studio suggest a feature dialog](https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022) 

This issue tracker is focused on the runtime and framework, which is not something impacted by this.
