### ISSUE TITLE
Add JSON file and UserSecrets configuration providers, and console logging w/ configuration to CreateSlimBuilder

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#47598]
Measurements on Windows x64 show that adding back JSON file configuration providers for *appsettings.json* and *appsettings.{EnvironmentName}.json*, UserSecrets, along with console logging and logging configuration, will cost ~790KB. Given our great progress on our file size targets for the native AOT effort, it feels worthwhile to "spend" that much to get back the utility provided by the JSON configuration files and the ability to configure logging from them, i.e. equivalent to:

```csharp
var settingsFiles = new[] { "appsettings.json", $"appsettings.{builder.Environment.EnvironmentName}.json" };
foreach (var settingsFile in settingsFiles)
{
    builder.Configuration.AddJsonFile(settingsFile, optional: true, reloadOnChange: true);
}

if (builder.Environment.IsDevelopment())
{
    builder.Configuration.AddUserSecrets<Program>();
}

builder.Logging
    .AddConfiguration(builder.Configuration.GetSection("Logging"))
    .AddConsole();
```

- [ ] Update slim builder to include:
  -  JSON file configuration for *appsettings.json* and *appsettings.{EnvironmentName}.json*
  - UserSecrets configuration
  - Console logging
  - Logging configuration
- [ ] Update API project template to include *appsettings.json* and *appsettings.Development.json* configuration files

**Comment by eerhardt** [comment]
FYI - with the latest builds, here are the numbers I'm seeing with this proposed change:

### Windows 
**Current:**  7.46 MB (7,832,576 bytes)
**Proposed:** 8.53 MB (8,946,688 bytes)

### Linux
**Current:**  8.01 MB (8,406,520 bytes)
**Proposed:** 9.20 MB (9,657,968 bytes)

So this change will add back ~1.1-1.2 MB of app size. I still think it is worth the tradeoff, but just wanted to list it here.
