### ISSUE TITLE
Google auth sign in without User becoming authenticated

### ISSUE THREAD

**Issue by valoghia** [dotnet/aspnetcore#47590]
I am doing Google OAuth v2 sign in, but the first time the user signs in I need him to check a box, choose name,  before `HttpContext.User.Identity.IsAuthenticated` becoming `true`.

The way I'm doing the sign in ( and that's the only I know, found code on SO):
```
[HttpPost]
public IActionResult ExternalLogin(string provider, string returnUrl)
{                    
    return new ChallengeResult(
        GoogleDefaults.AuthenticationScheme,
        new AuthenticationProperties
        {
            RedirectUri = Url.Action(nameof(ExternalSign), new { returnUrl })
        });
}

public async Task<ActionResult> ExternalSign(string returnUrl)
{            
    var res = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);            
    // await HttpContext.SignOutAsync(); // current workaround

    if (res == null || !res.Succeeded)
    {
        TempData["Error"] = "Sorry, please try again later";
        return RedirectToAction("SignIn");
    }

    var name = res.Principal.FindFirst(ClaimTypes.Name).Value;
    var email = res.Principal.FindFirst(ClaimTypes.Email).Value;
    var provider = res.Principal.Claims.First().Issuer;
```
### Describe the solution you'd like

Is it possible to read the google response without signing in the user in case of success, I'm calling `HttpContext.SignInAsync` myself later.

### Additional context

.net 7
Google OAuth v2

**Comment by Tratcher** [comment]
To do this you should use two different auth cookies. One that tracks the external google id, and a second one that tracks the local application id. The external one should only be used temporarily during login, while the other one should be used by the rest of the app.

**Comment by valoghia** [comment]
@Tratcher how do I do that ?

More exactly how do I make that the call to: 
`HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);`
doesn't affect:
`HttpContext.User.Identity`

**Comment by Tratcher** [comment]
> @Tratcher how do I do that ?
> 
> More exactly how do I make that the call to: `HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);` doesn't affect: `HttpContext.User.Identity`
> 
> (or is it easier to stick to my immediate call to `HttpContext.SignOutAsync()` workaround)

HttpContext.AuthenticateAsync doesn't set HttpContext.User, only the AuthenticationMiddleware does that, and it does that with the configured default scheme name.
https://github.com/dotnet/aspnetcore/blob/0899b0aab473d3138ae4c024f4fa484a829217f0/src/Http/Authentication.Core/src/AuthenticationService.cs#L59
https://github.com/dotnet/aspnetcore/blob/0899b0aab473d3138ae4c024f4fa484a829217f0/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L65

Overall the flow is something like this:
```c#
AddAuthentication(options =>
{
    DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme,
    DefaultSignInScheme = "External",
});
.AddCookie("External")
.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
.AddGoogle(...)

[HttpPost]
public IActionResult ExternalLogin(string provider, string returnUrl)
{                    
    return new ChallengeResult(
        GoogleDefaults.AuthenticationScheme,
        new AuthenticationProperties
        {
            RedirectUri = Url.Action(nameof(ExternalSign), new { returnUrl })
        });
}

public async Task<ActionResult> ExternalSign(string returnUrl)
{            
    var res = await HttpContext.AuthenticateAsync("External");

    if (res == null || !res.Succeeded)
    {
        TempData["Error"] = "Sorry, please try again later";
        return RedirectToAction("SignIn");
    }

    var name = res.Principal.FindFirst(ClaimTypes.Name).Value;
    var email = res.Principal.FindFirst(ClaimTypes.Email).Value;
    var provider = res.Principal.Claims.First().Issuer;

....
    await HttpContext.SignOutAsync("External");
    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user, ...);
```
