### ISSUE TITLE
add user role permissions for blazor united

### ISSUE THREAD

**Issue by sardar97** [dotnet/aspnetcore#47591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

add user role permissions 

### Describe the solution you'd like

add user role permissions. you have already user login . so if you create user role permissions blazor would be perfect 

### Additional context

please look up jmix user role permissions and create something like that

**Comment by JeremyLikness** [comment]
This is not a direction we plan to take the product.
