### ISSUE TITLE
Allow to install BlazorWASM debug extension on VS Code on remote

### ISSUE THREAD

**Issue by viethung9at1** [dotnet/aspnetcore#47617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Allow to install BlazorWASM debug extension on VS Code on remote. I can't debug Blazor in VS Code and WSL2 now.

### Describe the solution you'd like

Allow to install BlazorWASM debug extension on VS Code on remote.

**Comment by mkArtakMSFT** [comment]
That's correct. The extension is no longer required for debugging Blazor WebAssembly projects.
