### ISSUE TITLE
Replace internal Microsoft.Extensions.Metrics with package

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#47618]
https://github.com/dotnet/aspnetcore/pull/46834 adds an internal prototype version of Microsoft.Extensions.Metrics. The types are shared throughout ASP.NET Core with `InternalsVisibleTo`.

Replace with Microsoft.Extensions.Metrics when available. This work is happening in https://github.com/dotnet/runtime/issues/77514

**Comment by JamesNK** [comment]
Blocked, waiting on https://github.com/dotnet/runtime/issues/77514 to be completed.

**Comment by eerhardt** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/48407.

**Comment by JamesNK** [comment]
@eerhardt Thanks for shepherding this through for preview 5! I was planning to wait for 6, but I didn't think about type name conflicts showing up when the real version was merged.
