### ISSUE TITLE
Remove HardCoded string in Identity EF Tables Name

### ISSUE THREAD

**Issue by msmaldi** [dotnet/aspnetcore#47615]
Problem: If you are using a database like Postgres that uses snake_case instead of PascalCase, you will have problem with the names of the Identity tables, since the strings are HardCoded, the problem is solved removing ToTable and HasDatabaseName in files IdentityDbContext.cs and IdentityUserContext.cs

When using EF we can switch to snake_base using project like https://github.com/efcore/EFCore.NamingConventions

**Comment by msschl** [comment]
You can override all the names in your dbcontext `OnModelCreating` method:

```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IdentityUser>()
            .ToTable(„your favorite name“);

        …
    }
```

**Comment by msmaldi** [comment]
I currenty using another workaround, but is not ideal.

**Comment by MackinnonBuck** [comment]
Looks like this was answered by @msschl. Closing this out.

**Comment by msschl** [comment]
You can always go ahead and override any db configuration for Identity

Here is a simple sample to override the table name and index
```cs
namespace Your.Namespace;

internal sealed class ApplicationDbContext : IdentityDbContext 
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
        { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IdentityUser>(builder =>
        {
            builder.HasKey(x => x.Id)
                .HasName("your favorite primary key name");

            builder.HasIndex(x => x.NormalizedUserName)
                .HasDatabaseName("your index name")
                .IsUnique();

            builder.HasIndex(x => x.NormalizedEmail)
                .HasDatabaseName("your index name");

            builder.ToTable(„your favorite name“);

            // Anything else you want to override
        });
    }
}
```
