### ISSUE TITLE
Question about Microsoft.AspNetCore nuget versions

### ISSUE THREAD

**Issue by podprad** [dotnet/aspnetcore#47612]
I see that some of the Microsoft.AspNetCore.* packages on nuget.org are in relatively new versions like 6.0.0 or newer. However, another like Kestrel or HttpSys are in version 2.*.*.
Shouldn't all the components be push to nuget.org as single software product line? So the packages like Kestrel should be available in latest versions.

Little background:

> In our project we started migrating from .NET Framework to the .NET6+. In the first step we would like to replace the legacy WCF by CoreWCF but still running on .NET Framework. I managed to run it successfuly, because most of aspnetcore nugets are compatible with .netstandard2.0. I have one smart flag allowing customers to switch back to legacy WCF if they meet any critical problem.

**Comment by Tratcher** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-7.0&tabs=visual-studio#remove-obsolete-package-references
