### ISSUE TITLE
The Input Tag Helper renders DateOnly properties with an invalid date format

### ISSUE THREAD

**Issue by dougwaldron** [dotnet/aspnetcore#47628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In HTML, the date value for an `<input type="date">` element (which generally triggers a date picker in the browser), [must be formatted as `yyyy-MM-dd`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value). 

In ASP.NET, an Input Tag Helper for a `DateTime` property (with a `DataType.Date` attribute) renders the date value correctly. But a `DateOnly` property used the same way gets its date value formatted as `d-M-yyyy`, which breaks the functionality of the date-picker widget, resulting in data loss after a round trip to the server.

### Expected Behavior

The date value of a `DateOnly` property should be rendered by an Input Tag Helper in `yyyy-MM-dd` format.

### Steps To Reproduce

Use a `DateOnly` property in a Razor page model (with the correct `DataType` annotation):

```csharp
public class MyPageModel : PageModel
{
    [DataType(DataType.Date)]
    public DateTime? MyDateTime { get; set; }

    [DataType(DataType.Date)]
    public DateOnly? MyDateOnly { get; set; }

    public void OnGet()
    {
        MyDateTime = DateTime.Today;
        MyDateOnly = DateOnly.FromDateTime(DateTime.Today);
    }
}
```

Add the property to the page using an Input Tag Helper:

```html
@page
@model MyPageModel

<form>
    <label asp-for="MyDateTime"></label>
    <input asp-for="MyDateTime" />

    <label asp-for="MyDateOnly"></label>
    <input asp-for="MyDateOnly" />
</form>
```

The rendered HTML uses an invalid date format, which prevents correct date picker functionality:

![image](https://user-images.githubusercontent.com/737326/230959172-b44b5d06-2f29-4d8a-a1b6-2f257b40decd.png)

### .NET Version

7.0.202

### Anything else?

Please note that you can work around the issue by specifying the date format using the attribute `[DisplayFormat(DataFormatString = "{0:O}", ApplyFormatInEditMode = true)]`, but this shouldn't be necessary. The correct date format should be rendered by default.

**Comment by dougwaldron** [comment]
Invalid data sent to the browser seems like a worthy bug to fix, IMO, and this wouldn't be a breaking change as far as I can see.

Would it be okay if I submit a PR for this?

**Comment by mustafasalahuldin** [comment]
I'm facing the same issue here, and it seems like .Net doesn't follow the user defined format rather it follows the system format, I tested this in different environments and whatever I do to change the format, it is always ignored as long as it is not same as system format.
