### ISSUE TITLE
Create Blazor server-side rendering guidance for Blazor component library owners

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#47624]
Everyone who owns a Blazor component library (e.g., vendors or OSS projects) will have roughly the same questions about what they are supposed to do for Blazor server-side rendering in .NET 8. We should provide some written guidance about:

 * Figuring out what your component is supposed to do in SSR mode
 * Techniques you can use to make some of the interactive features still work (e.g., form post)
 * Anything you should think about relating to streaming rendering
 * Should you mark components as interactive?

**Comment by SteveSandersonMS** [comment]
cc @danroth27

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS would you be able to handle this ? If not, please unassign yourself and we'll reassign.
