### ISSUE TITLE
Blazor static file url is incorrect when Blazor is running in a virtual app

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#47627]
I am running a blazor app on a virtual application on my Azure Web App (virtual path = /blazor, Type = Application).

Base is as follows in index.html:

	<base href="/blazor/" />
	
	
The url to access the app is https://mydomain/blazor
	
The blazor app runs fine - the problem is that I need to use a javascript file.  The .js file is located in wwwroot folder of the app.

When a request is made for the file this error is received:

> Loading failed for the module with source “https://mydomain/_content/myapp/scripts.js”. 

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]  Unhandled exception rendering component: error loading dynamically imported module
      
> Microsoft.JSInterop.JSException: error loading dynamically imported module

> at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
> at LeaderAnalytics.LeaderPivot.Blazor.MeasureContainer`1.<ShowDimension>d__74[[LeaderAnalytics.LeaderPivot.TestData.SalesData, LeaderAnalytics.LeaderPivot.TestData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
> at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
> at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

My first thought was that this was a CORS issue however it looks like the url is just incorrect.

Actual url - does not work:

    https://mydomain/_content/myapp/scripts.js

Below is what I think the url should be.  This works - file is received and visible in the browser:

    https://mydomain/blazor/_content/myapp/scripts.js

I believe `<StaticWebAssetBasePath>blazor</StaticWebAssetBasePath>` will give me the following which does not work:

    https://mydomain/_content/blazor/myapp/scripts.js

I have seen [this documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-7.0) - not sure how to use it for this problem.

Reference also:
https://stackoverflow.com/questions/51610513/can-razor-class-library-pack-static-files-js-css-etc-too

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Please check out [this sample](https://github.com/javiercn/BlazorMultipleApps) that involves hosting different apps in a subpath.

**Comment by sam-wheat** [comment]
Thank you @MackinnonBuck  for the sample app.  Unfortunately I am not able to make the sample work when a javascript file is requested.

Steps to reproduce:

In SecondBlazorApp.Client project:

Add a file named scripts.js to wwwroot folder with this content:

    export function hello() {
        alert('hello');
    }

Add the following to Index.razor

	@code
	{
		[Inject] IJSRuntime JSRuntime { get; set; }
		private Lazy<Task<IJSObjectReference>> moduleTask;

		protected override async Task OnAfterRenderAsync(bool firstRender)
		{
			if (firstRender)
			{
				moduleTask = new(() => JSRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/SecondBlazorApp.Client/scripts.js").AsTask());
				var module = await moduleTask.Value;
				await module.InvokeVoidAsync("hello");
			}
		}
	}

Run the app and note the error when the script file is requested.

**Comment by sam-wheat** [comment]
@javiercn 

I think I am able to articulate what the issue is.  Blazor is not respecting the `base href` setting in index.html.

In my case it is set as follows:

	<base href="/blazor/" />

In code I am specifying the url of my js file like this:

		moduleTask = new(() => JSRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/myapp/scripts.js").AsTask());

If the `base` value is respected the following url should be constructed by Blazor and it will work:

    https://mydomain/blazor/_content/myapp/scripts.js

However `base` is not respected which results in the following url which does not work:

    https://mydomain/_content/myapp/scripts.js

**Comment by sam-wheat** [comment]
Workaround until this is fixed or otherwise resolved or documented:


	@code {

		[Inject] IJSRuntime JSRuntime { get; set; }
		[Inject] NavigationManager NavManager { get; set; }

		protected override async Task OnInitializedAsync()
		{
			string path = new Uri(NavManager.BaseUri).AbsolutePath + "scripts.js";
			
			// if page is in a component library use this:
			// string path = new Uri(NavManager.BaseUri).AbsolutePath + "_content/Your.App.Name/scripts.js";
			
			
			IJSObjectReference JSObj = await JSRuntime.InvokeAsync<IJSObjectReference>("import", path);
			await JSObj.InvokeVoidAsync("hello");
		}
	}

**Comment by javiercn** [comment]
@sam-wheat I've updated my sample to show how to do this.

**Comment by leaderanalytics** [comment]
Thank you @javiercn  - the sample is very useful.  

I think that `UseStaticFiles` (or at least the part of it that causes Blazor to look at the absolute base path) should always be called since the probability of a static file failing to load is 100% if that method is not called.

In what cases would a user not want to call `app.UseStaticFiles()`?  For example if that method were called inside `WebAssemblyHostBuilder.Build()` would it break anything?

**Comment by leaderanalytics** [comment]
@javiercn  If my server serves html (base path is `/`) and only my virtual app serves blazor (base path is `/blazor/`) where do I call `UseStaticFiles`?

**Comment by javiercn** [comment]
@leaderanalytics There's not wright or wrong. It depends on how are you referring to the files.

Instead of that, make sure that the file appears on the paths you care about. Visit the path on the browser to make sure the file is served from there.

Then make sure that the location in which you are referring to the file has the right path.
