### ISSUE TITLE
Use IProblemDetailsService in ValidationProblem

### ISSUE THREAD

**Issue by bjornen77** [dotnet/aspnetcore#47631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Validation problem should use IProblemDetailsService in the same way as #47045 

### Describe the solution you'd like

I think that ValidationProblem (Microsoft.AspNetCore.Http.HttpResults) should also use the IProblemDetailsService in the same way as #47045 to be able to customize the validation problem in one place.

**Comment by dnperfors** [comment]
I just created a PR for this. I guess this will be to late for .NET 8 or can it be sneaked in for consistency reasons?

**Comment by martincostello** [comment]
At this point, I believe .NET 8 is "done" - there's no such thing as _"sneaking it in"_ once they lock down the branches, which typically happens once they permanently branch off of `main` before the first release candidate.

**Comment by dnperfors** [comment]
Technically .NET 8 is still a release candidate and this is an oversight, but probably not severe enough to warrant including it in the upcoming release...
