### ISSUE TITLE
dotnet application crash with segfault libcoreclr.so UBUNTU 22.04

### ISSUE THREAD

**Issue by GUSTAVPEREIRA** [dotnet/aspnetcore#47636]
### Description
When I run my application build in dotnet 6 using razor he throw "The futex facility returned an unexpected error code." after I call render view.

Apr  9 13:10:57 pereira-workstation kernel: [86494.804653] FileLogEventLis[66689]: segfault at 7f7e60b4d890 ip 00007f7e60b4d890 sp 00007f7e809fb728 error 14 in System.Security.Cryptography.dll[7f7e60c00000+211000]
Apr  9 13:11:33 pereira-workstation kernel: [86530.923631] .NET ThreadPool[67801]: segfault at 8 ip 00007fc68829f01b sp 00007fb85c9fd1c0 error 6 in libcoreclr.so[7fc68816a000+1ae000]
Apr  9 13:47:23 pereira-workstation kernel: [88681.565196] .NET ThreadPool[79321]: segfault at 8 ip 00007f4fa569f01b sp 00007f41589f9480 error 6
Apr  9 16:37:22 pereira-workstation kernel: [98880.182611] GpuWatchdog[95332]: segfault at 0 ip 00007f2fbb992336 sp 00007f2fb1666370 error 6 in libcef.so[7f2fb74ef000+776f000]
Apr  9 16:37:52 pereira-workstation kernel: [98910.721218] GpuWatchdog[111728]: segfault at 0 ip 00007f2fbb992336 sp 00007f2fb1666370 error 6 in libcef.so[7f2fb74ef000+776f000]
Apr  9 16:38:08 pereira-workstation kernel: [98926.509062] GpuWatchdog[111808]: segfault at 0 ip 00007f2fbb992336 sp 00007f2fb1666370 error 6 in libcef.so[7f2fb74ef000+776f000]
Apr  9 16:54:50 pereira-workstation kernel: [99928.080013] dota2[96746]: segfault at 55dc31e12724 ip 00007fd9cc5101d4 sp 00007fff85fca608 error 4 in libX11.so.6.4.0[7fd9cc4d9000+8c000]
Apr  9 18:03:06 pereira-workstation kernel: [104024.079455] .NET ThreadPool[126160]: segfault at 8 ip 00007f920589f01b sp 00007f83d61fc480 error 6 in libcoreclr.so[7f920576a000+1ae000]
Apr  9 18:03:54 pereira-workstation kernel: [104072.268766] .NET ThreadPool[126783]: segfault at 8 ip 00007f47c109f01b sp 00007f399d9fc480 error 6 in libcoreclr.so[7f47c0f6a000+1ae000]
Apr  9 18:12:28 pereira-workstation kernel: [104586.530411] .NET ThreadPool[129515]: segfault at 8 ip 00007f09d6c9f01b sp 00007efba7ffe480 error 6 in libcoreclr.so[7f09d6b6a000+1ae000]
Apr  9 18:26:41 pereira-workstation kernel: [105439.658758] .NET ThreadPool[132586]: segfault at 8 ip 00007fc026a9f01b sp 00007fb9f29fd480 error 6 in libcoreclr.so[7fc02696a000+1ae000]
Apr  9 18:42:02 pereira-workstation kernel: [106359.989779] .NET ThreadPool[135791]: segfault at 8 ip 00007f6c4789f01b sp 00007f5e0f1fe480 error 6 in libcoreclr.so[7f6c4776a000+1ae000]
Apr  9 18:58:13 pereira-workstation kernel: [107331.125206] .NET ThreadPool[139031]: segfault at 8 ip 00007f39e309f01b sp 00007f2bb3ffe480 error 6 in libcoreclr.so[7f39e2f6a000+1ae000]

### Configuration
DOTNET 6.0.133
UBUNTU 22.04 x64
Processor AMD® Ryzen 5 3400g with radeon vega graphics × 8
Memory 16 GB

**Comment by mitchdenny** [comment]
@GUSTAVPEREIRA could you please put together a repro repository for this so that we can take a look. The repro should contain just the code required to reproduce the issue you are seeing. At this point the details you've provided don't give us enough to go on.

**Comment by GUSTAVPEREIRA** [comment]
I'll make an environment in the weekend, because I don't can share the actual code, because is not mine.
