### ISSUE TITLE
I configure the server to requiere client certificate but it accepts the request when client doesn't add a certificate

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/aspnetcore#47638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would like to implement mTLS in a service, but when create the client without adding the certificate, the server accepts the request.

This is the code of my server, in the program.cs file of my ASP Core 7 application:

```
try
{

    var builder = WebApplication.CreateBuilder(args);



    builder.WebHost.ConfigureKestrel((context, options) =>
    {
        string miStrCertificado = File.ReadAllText("certificados/server.crt");
        string miStrKey = File.ReadAllText("certificados/server.key");
        X509Certificate2 miCertficadoX509 = X509Certificate2.CreateFromPem(miStrCertificado, miStrKey);

        X509Certificate2 miCertificado2 = new X509Certificate2(miCertficadoX509.Export(X509ContentType.Pkcs12));

        miCertficadoX509.Dispose();

        options.ListenAnyIP(5001, listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http2;
            listenOptions.UseHttps(miCertificado2);
        });

        options.ConfigureHttpsDefaults(miHttpsOptions =>
        {
            miHttpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
            miHttpsOptions.ServerCertificate = miCertificado2;
        });
    });


    builder.Services.AddHttpContextAccessor();


    




    builder.Services.AddGrpc();
    builder.Services.AddCodeFirstGrpc();



    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddJwtBearer(options =>
        {
            options.TokenValidationParameters = new TokenValidationParameters
            {
                //@#ESTUDIAR: ¿el string utilizado tiene que tener 64 caracteres? No parece pero parece ser que no
                //vale cualquier longitud. Igual tiene que ser un string que codifique datos binarios en base 4.
                IssuerSigningKey = new SymmetricSecurityKey(System.Text.Encoding.Default.GetBytes("ABCD")),
                RequireExpirationTime = true,
                RequireSignedTokens = true,
                ClockSkew = TimeSpan.FromSeconds(10),

                ValidateIssuer = false,
                ValidateAudience = false,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true,
            };
        });
    builder.Services.AddAuthorization();





    var app = builder.Build();



    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.MapGrpcService<MyServiceLogin>();
    app.MapGrpcService<MyMainService>();




    await app.RunAsync();
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

This is how I create my client:

```
private ChannelCredentials CrearCredencialesDelCanal()
{
    CallCredentials misCredencialesDeLlamada = CallCredentials.FromInterceptor((c, m) =>
    {
        m.Add(HeaderNames.Authorization, $"Bearer {_tokenJwt}");
        return Task.CompletedTask;
    });


    return ChannelCredentials.Create(new SslCredentials(), misCredencialesDeLlamada);
}



private GrpcChannelOptions CrearOpcionesDelCanal()
{
    HttpClientHandler miHttpHandler = new HttpClientHandler();
    //Always return true
    miHttpHandler.ServerCertificateCustomValidationCallback = ValidateServerCertificate;



    HttpClient httpClient = new HttpClient(miHttpHandler);

    GrpcChannelOptions misOpcionesDelCanal = new GrpcChannelOptions()
    {
        MaxReceiveMessageSize = 62914560,
        MaxSendMessageSize = 62914560,
        HttpClient = httpClient,
    };


    misOpcionesDelCanal.Credentials = CrearCredencialesDelCanal();


    return misOpcionesDelCanal;
}



private GrpcChannel CrearCanal(string paramStrDireccion, int paramIntPuerto)
{
    GrpcChannelOptions misOpciones = CrearOpcionesDelCanal();



    try
    {
        Uri miUri = new Uri(paramStrDireccion + ":" + paramIntPuerto.ToString());
        GrpcChannel miCanalGrpc = GrpcChannel.ForAddress(miUri, misOpciones);

        OnCanalGrpcActualizado(miCanalGrpc);
        return miCanalGrpc;
    }
    catch
    {
        throw new ArgumentException("Los datos del servidor no son correctos.");
    }
}

```
In this example, when I create the HttClientHandler, I don't set the client certificate, but the server accepts the request and replies.

How could I set the server to requiere a client certificate and if it is not add or it is not a valid certificate, refuse the request?

Thanks.

### Expected Behavior

The server should to denied or not reply to a client when it doesn't add a valid certificate.

**Comment by mitchdenny** [comment]
It looks like you are configuring the JWT authentication scheme in the code above instead of certificate authentication, check out the following page for how to do client cert auth in ASP.NET:

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-7.0

Here is a really quick little sample using minimal API that I put together based on that:

```csharp
using Microsoft.AspNetCore.Authentication.Certificate;
using Microsoft.AspNetCore.Connections;
using Microsoft.AspNetCore.Server.Kestrel.Https;
using System.Security.Claims;

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel((context, options) =>
{
    options.ConfigureHttpsDefaults(httpsOptions =>
    {
        httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
    });
});

builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme).AddCertificate(options =>
{
    options.Events = new CertificateAuthenticationEvents
    {
        OnCertificateValidated = context =>
        {
            var claims = new[]
            {
                    new Claim(
                        ClaimTypes.NameIdentifier,
                        context.ClientCertificate.Subject,
                        ClaimValueTypes.String, context.Options.ClaimsIssuer),
                    new Claim(
                        ClaimTypes.Name,
                        context.ClientCertificate.Subject,
                        ClaimValueTypes.String, context.Options.ClaimsIssuer)
                };

            context.Principal = new ClaimsPrincipal(
                new ClaimsIdentity(claims, context.Scheme.Name));
            context.Success();

            return Task.CompletedTask;
        }
    };
});

builder.Services.AddAuthorization();

var app = builder.Build();
app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/", () => "Hello World!").RequireAuthorization();

app.Run();
```

When you run this and hit the URL with your browser your browser should prompt  you to select a certificate to use. The auth middleware is what maps the certificate onto a claims principal for you, and from there you can start to make authorization decisions.

Depending on your scenario you may need to do more verification of the certificate chain etc.

**Comment by ComptonAlvaro** [comment]
Thanks for your help.

Yes, I am using JWT authentication, but I would like to add certificate autentication two. Is it possible to use both ways to authenticate at the same time?

My idea was to include a certificate for the client application, so only the applications that have this certificate will can use the service. In practice, I want to avoid someone could develop its own application to can use the service.

But I would like to use JWT to authenticate the users of the application, so I can know which user is are doing a request to the service.



Thanks.

**Comment by mitchdenny** [comment]
OK, in that case you might want to look at the `ClientCertificateValidation` (not shown) property on the `httpsOptions` instance from my example above. It allows you to client certificate validation and you can then leave the JWT auth in place.

**Comment by ComptonAlvaro** [comment]
If I understand correctly, i have to implement in the server side the hanlder for ClientCertificateValidation with the logic to validate the certificate that is received from the client.

if this is correct, which is the, which is the useful of this line code?

`httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;`

Because in the documentation it is said that with RquiereCertificate, I am telling that the client has to include a valide certificate and if not, it is refused. It seems it would be the work of validating the certificate. Is this correct? If this is correct, is there some way that I could use this option instead to implement the ClientCertificateValidation logic?



Thanks.

**Comment by mitchdenny** [comment]
That property will require the certificate - but the whole point in the scenario you outlined above is that you want to validate not merely that a certificate is being used, but that a specific certificate is being used. So the `ClientCertificateValidation` property allows you to inspect the cert.

**Comment by ComptonAlvaro** [comment]
Then I need both, set required certificate to force to a client to use a certificate and ClientCertificateValidation to validate the certificate that I get from the client.

My problem is that if I set requiered certificate in the server and I don't add a certificate in the client, the server replies to the client. At first, I guess the server should not reply if the client dones't add a certificate. But why does the server reply if it forces to use certificate and the client doesn't add it?

**Comment by ComptonAlvaro** [comment]
The issue is closed but i am not sure if the answer is what I was looking for.

I understand that it seems i should to implement the ClientCertificateValidation, but I was asking why if I set in the server that the client certificate is requiered, why the server responses to the client.

I would like to get the exception, to be sure the server refuse any call from clients that doesn't include a certificate.

So I still have the doubt, why the server doesn't refuse the call from the client?



Thanks.

**Comment by mitchdenny** [comment]
In the code sample I provided above, the `OnCertificateValidated` method is fired after the framework has validated that the client provided a certificate. If the client does not provide a certificate then it will fail to establish the underlying TLS certificate (because `ClientCertificateMode =ClientCertificateMode.RequireCertificate`.

In my sample implementation of `OnCertificateValidated` I simply copy the details from the client certficate to create the claims principal. If you want to do further validation beyond that and fail the request you would do that - then call `context.Fail()` to reject the request if the certificate is not among the ones that you accept.

**Comment by mitchdenny** [comment]
It would be great to consolidate the other issues that you've posted as well since they all seem to be related.
