### ISSUE TITLE
Allow ProblemDetails property to be settable in ProblemDetailsContext

### ISSUE THREAD

**Issue by bjornen77** [dotnet/aspnetcore#47633]
## Background and Motivation

Currently the ProblemDetail property in ProblemDetailsContext is init only, which makes it impossible to change the ProblemDetails instance to another type if wanted when customizing the problem details. 

For example, when sending invalid JSON to an API controller a validation problem is returned. If I would like to change this to another problem details type, the property needs to be settable.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public class ProblemDetailsContext
{
-   public ProblemDetails ProblemDetails { get; init; }
+   public ProblemDetails ProblemDetails { get; set; }
}
```

## Usage Examples

```
builder.Services.AddProblemDetails(options =>
{
    options.CustomizeProblemDetails = (context) => 
    {
        if (context.ProblemDetails is HttpValidationProblemDetails)
        {
            // change to another problem details type because the HttpValidationProblemDetails contains
            // an Errors property that might not be wanted in some cases.
            context.ProblemDetails = new ProblemDetails() { .... }
        }
    };
});
```

## Alternative Designs
N/A

## Risks
Investigate so it has no side effect of substituting the problem details instance here,

**Comment by mitchdenny** [comment]
The structure of the problem type is largely dictated by RFC7807. Even though the `ProblemDetails` field is init only, nothing stops you adding information to the Extensions property which is the intended extensibility point.

**Comment by mitchdenny** [comment]
@bjornen77 could you update this issue to use the API proposal template and we can try to get some collective input on whether we want to make this change.

I'm not sure if there would be a side effect of substituting the problem details instance here, but it is worth considering.

Template: https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=

Tag me when you've got this updated, I'll happily float this for your at our next API review.

**Comment by bjornen77** [comment]
@mitchdenny Sure, no problem! The issue is now updated with the API proposal template.

**Comment by bjornen77** [comment]
Thank you for taking this through API review @mitchdenny. Should this issue be labled with api ready for review?

**Comment by halter73** [comment]
API Review Notes:

- Did this already ship?
  - Yes. In .NET 7. `ProblemDetailsContext.Exception` is new, but not `ProblemDetailsContext.ProblemDetails`.
  - Fortunately, changing `init` to `set` is less restrictive and should be a non-breaking at both a binary and source level.
  - It's possible that a source generator or reflection could get thrown off by this, but we're not too worried about it.

API Approved!

```diff
namespace Microsoft.AspNetCore.Http;

public class ProblemDetailsContext
{
-   public ProblemDetails ProblemDetails { get; init; }
+   public ProblemDetails ProblemDetails { get; set; }
}
```
