### ISSUE TITLE
WithOpenApi adds Empty requestBody when parameter is of type string[] or StringValues

### ISSUE THREAD

**Issue by cleftheris** [dotnet/aspnetcore#47644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When mapping any operation that has no actual body and one of the method argumets is of type `string[]?` or `StringValues` according to the documentation the api should infer that to be from query string unless explicitly configured otherwise. 

Although this actually works fine for calling the endpoint, when generating documentation an empty body appears. 
This happens by simply using the `WithOpenApi` extension method. When I debug  I find that the operation.RequestBody parameter is populated (should be null if you check with other operations). 

### The operation
```csharp
// Bind to a string array.
// GET /tags2?names=john&names=jack&names=jane
app.MapGet("/tags2", (string[] names) =>
            $"tag1: {names[0]} , tag2: {names[1]}, tag3: {names[2]}").WithOpenApi();

```
### The generated swagger json
```json

{
  "openapi": "3.0.1",
  "info": {
    "title": "WebApplication1",
    "version": "1.0"
  },
  "paths": {
    "/tags2": {
      "get": {
        "tags": [
          "WebApplication1"
        ],
        "parameters": [
          {
            "name": "names",
            "in": "query",
            "required": true,
            "style": "form",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": { }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": { }
}
```

[Link to the documentation](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#bind-arrays-and-string-values-from-headers-and-query-strings) 

### Expected Behavior

There should not be a requestBody at all there.
```json

{
  "openapi": "3.0.1",
  "info": {
    "title": "WebApplication1",
    "version": "1.0"
  },
  "paths": {
    "/tags2": {
      "get": {
        "tags": [
          "WebApplication1"
        ],
        "parameters": [
          {
            "name": "names",
            "in": "query",
            "required": true,
            "style": "form",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": { }
}
```

### Steps To Reproduce

I have prepared a project here https://github.com/cleftheris/WithOpenApiBug 

It is just the default aspnet 7 template with the below code added to the Project.cs

```csharp
// Bind to a string array.
// GET /tags2?names=john&names=jack&names=jane
app.MapGet("/tags2", (string[] names) =>
            $"tag1: {names[0]} , tag2: {names[1]}, tag3: {names[2]}").WithOpenApi();

```

### .NET Version

7.0.4

### Anything else?

.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe
<img width="1186" alt="Screenshot 2023-04-11 161249" src="https://user-images.githubusercontent.com/1777633/231173850-c302c371-fbeb-4fa6-92c1-f4db09466170.png">

**Comment by captainsafia** [comment]
@cleftheris Thanks for the bug report! I tracked it down to this line of code:

https://github.com/dotnet/dotnet/blob/8d5c52c5dd54417a2071c196663bb29ab1ee2442/src/aspnetcore/src/OpenApi/src/OpenApiGenerator.cs#L262

Fix incoming...

**Comment by cleftheris** [comment]
Wow thanks @captainsafia you are very quick! Can we expect this to land on dotnet7.0 as a hot fix or I have to wait for dotnet8? 

I got a couple more issues to report on OpenAPI since we migrated a large code base to minimal APIs and have had the time to check things out.

Thanks again for your work

**Comment by captainsafia** [comment]
> I got a couple more issues to report on OpenAPI since we migrated a large code base to minimal APIs and have had the time to check things out.

Don't hesitate to report issues here! I look forward to polishing up this area.

>  Do you believe this fix can be included in a minor or patch release of the Microsoft.AspNetCore.OpenApi package? 

We can push a hotfix for this. I'll re-open the issue to track backporting to the next servicing release for 7.0.

**Comment by giorgos07** [comment]
@captainsafia that sound perfect. Thanks again for your immediate action!

**Comment by captainsafia** [comment]
PR to backport to .NET 7: https://github.com/dotnet/aspnetcore/pull/47807

**Comment by captainsafia** [comment]
Closing since backport has been merged.
