### ISSUE TITLE
Provide out of the box Identity Manager UI

### ISSUE THREAD

**Issue by utilsites** [dotnet/aspnetcore#47648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can asp.net core project template have a out of the box Identity Manager UI? 
Without need to scafold and adapt.
Something like this (works well):
https://github.com/mguinness/IdentityManagerUI

### Describe the solution you'd like

Something like this (works well):
https://github.com/mguinness/IdentityManagerUI
But out of the box, with a option to generate this when creating the project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
