### ISSUE TITLE
Make successful authentication scheme available from HttpContext object

### ISSUE THREAD

**Issue by ntyrrell** [dotnet/aspnetcore#47646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to get the name of the authenticated scheme for a user after they have successfully been authenticated, as I have multiple authentication schemes. However, at present, this data is not currently available.

At present, I am using a dirty hack to be able to figure out my scheme programmatically (taking a lot of inspiration from `AuthenticationService`;
```csharp
internal sealed class AuthenticationSchemeClaimsTransformation : IClaimsTransformation {
    private const string ClaimType = "authScheme";

    private readonly IAuthenticationSchemeProvider authenticationSchemeProvider;
    private readonly IAuthenticationHandlerProvider authenticationHandlerProvider;
    private readonly IHttpContextAccessor httpContextAccessor;
    public AuthenticationSchemeClaimsTransformation(IAuthenticationSchemeProvider authenticationSchemeProvider, IAuthenticationHandlerProvider authenticationHandlerProvider, IHttpContextAccessor httpContextAccessor) {
        this.authenticationSchemeProvider = authenticationSchemeProvider;
        this.authenticationHandlerProvider = authenticationHandlerProvider;
        this.httpContextAccessor = httpContextAccessor;
    }
    public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal) {
        if (principal.HasClaim(claim => claim.Type == ClaimType)) {
            return principal;
        }
        var httpContext = httpContextAccessor.HttpContext;
        if (httpContext == null) {
            return principal;
        }
        var schemes = await authenticationSchemeProvider.GetAllSchemesAsync();
        string? authenticatedScheme = null;
        foreach (var scheme in schemes) {
            var handler = await authenticationHandlerProvider.GetHandlerAsync(httpContext, scheme.Name);
            if (handler == null) {
                continue;
            }
            // Handlers should not return null, but we'll be tolerant of null values for legacy reasons.
            var result = (await handler.AuthenticateAsync()) ?? AuthenticateResult.NoResult();
            if (result.Succeeded) {
                authenticatedScheme = scheme.Name;
                break;
            }
        }
        if (string.IsNullOrWhiteSpace(authenticatedScheme)) {
            return principal;
        }
        var claimsIdentity = new ClaimsIdentity();
        claimsIdentity.AddClaim(new Claim(ClaimType, authenticatedScheme));
        principal.AddIdentity(claimsIdentity);
        return principal;
    }
}
```
This is not an ideal solution however, as we end up authenticating up to `n` times where `n` is the number of schemes after a successful authentication.

### Describe the solution you'd like

Ideally, we should have the name authentication scheme that we authenticated with available within the `HttpContext` object. This could potentially be available via `HttpContext.User.Claims`, but this could be prone to conflicts if a customer has, for whatever reason, already created a claim with that name. A better candidate might be to add a `string` property of `AuthenticationScheme` to the `IIdentity` interface, but this would be a breaking change.

**Comment by Tratcher** [comment]
From a design perspective, what we should be making available is the whole [AuthenticationTicket](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Authentication.Abstractions/src/AuthenticationTicket.cs) which would include the scheme name, principal, and the auth properties. It's unfortunate that you need to know the scheme (or assume the default) and call AuthenticateAsync to get the full ticket.

**Comment by ntyrrell** [comment]
> Where in the app do you need to know the scheme? The scheme should be deterministic based on your route. E.g. if your route specifies a scheme then that's the one that should have been used. If it didn't, then the default scheme was used.

I can provide some specific context for my example.

In our application, we have two means of authentication; an older identity provider that was rolled out by another team in the company that we plan on deprecating, and a newer identity provider. At the moment, we're caught between the two.

However, there is a bit of a "gotcha" - the application also supports multitenancy. This presents a problem because the identifier of the tenant differs depending on which authentication scheme we're using. We have an internal `Tenant` object that maps to these external IDs (and a tenant is capable of mapping to one or the other or both), i.e.
```csharp
public sealed record Tenant(Guid Id, string? OldExternalId, string? NewExternalId);
```
Ideally, if a tenant is configured to work with either authentication system, then we don't care which one they use, only that they are authenticated and accessing only their tenant's data.

This presents a problem when performing authorization. For the sake of safety, we cannot simply have two different `AuthorizationHandler` classes where one handles the old scheme and the other handles the new scheme and we naively use the respective external ID to fetch our internal Tenant object, because we cannot guarantee that an external ID in the old identity provider does not refer to a different tenant in the new identity provider.

We also have created some custom middleware where we populate a class that holds strongly typed data regarding the current user's tenant and other information rather than referring to the `User` property in `HttpContext` all the time, again because how this data is mapped depends on the authentication scheme being provided.

**Comment by ntyrrell** [comment]
Closing this issue - I've just discovered that `IAuthenticateResultFeature` returns the `AuthenticationTicket` that I was looking for. Thank you for pointing me in the right direction!
