### ISSUE TITLE
GetApplicationPartManager uses environment variable ApplicationName to get entryAssemblyName is that the expected behavior? If we override ApplicationName, app crashes 

### ISSUE THREAD

**Issue by modios** [dotnet/aspnetcore#47643]
## Summary

GetApplicationPartManager  does  var entryAssemblyName = environment?.ApplicationName; and hence 
taking the entryAssemblyName from the environment variable ApplicationName.
But the environment variable ApplicationName  can be overridden.

For existing application that override the ApplicationName, which indeed by default holds the assembly name, this will cause the app to crash.

Is there another way to set the entryAssemblyName  in the code that does not depend on an environment variables?

## Motivation and goals

Change  the existing logic for setting entryAssemblyName  to something that doesn't depend on environment variables.
Hence existing applications that override ApplicationName default value will not crash and new applications will have the 
ability to set ApplicationName to something other than the default value if needed.

## Examples
Adding for example

```
.AddApiExplorer(options =>
                 {
                     options.GroupNameFormat = "'v'VVV";
                     options.SubstituteApiVersionInUrl = true;
                 });
```

in our application will fail in case the ApplicationName has been overridden and doesn't hold the default assembly name.

**Comment by captainsafia** [comment]
@modios Is there a chance you can provide a complete repro here?

> in our application will fail in case the ApplicationName has been overridden and doesn't hold the default assembly name. 

Based on the example that you provided here, it appears that you are using the ApiVersioning library?

A stacktrace and repro would be helpful here...

**Comment by davidfowl** [comment]
Yes it’s by design. The application name on the hosting environment should be a valid assembly name.

**Comment by modios** [comment]
@captainsafia and @davidfowl thank you very much for your quick response. Helped me a lot to clarify things.
Realized that  the issue only arises when running integration tests using WebApplicationFactory and which was able to solve using details from https://github.com/dotnet/aspnetcore/issues/7315.

yes @captainsafia this appeared when using ApiVersioning. It's a little bit complicated to provide a repo with an example. 
I think I can close the issue, so will do.

Thank you again.
