### ISSUE TITLE
Add exception property to the problem details context

### ISSUE THREAD

**Issue by bjornen77** [dotnet/aspnetcore#47651]
## Background and Motivation

If an application is configured to generate problem details it would be good, if an exception occurs in the application, that the original exception can be retreived directly on the problem details context. The exception information can be used to customize the problem details when using the CustomizeProblemDetails functionality. The original exception can already be retreived using the IExceptionHandlerFeature, but having the exception directly on the context will be easier and more straight forward to use.

The exception property should be set when the problem details context is written from the built-in exception handler middlewares.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public class ProblemDetailsContext
{
+   public Exception? Exception { get; init; }
}

```

## Usage Examples

```csharp
builder.Services.AddProblemDetails(configure =>
    configure.CustomizeProblemDetails = (context) =>
    {
        if (context.Exception is not null)
        {
            // Customize problem details with information from exception.
        }
    }
);
```

## Alternative Designs

N/A

## Risks

None that I am aware of.

**Comment by bjornen77** [comment]
https://github.com/dotnet/aspnetcore/pull/47554#pullrequestreview-1379576310

@captainsafia @JamesNK

**Comment by captainsafia** [comment]
Thanks! This will go through API review before implementation.

@brunolins16 Do you have any insights that might guide the implementation?

**Comment by BrennanConroy** [comment]
API Review Notes:
* Who is setting the exception?
  - We would be in DeveloperException page etc.
* The Exception won't be written by our implementations of `IProblemDetailsWriter`
  - Would be up to the user to put the exception in Extensions in CustomizeProblemDetails if they want that

API Approved!

```diff
namespace Microsoft.AspNetCore.Http;

public sealed class ProblemDetailsContext
{
+   public Exception? Exception { get; init; }
}
```

**Comment by brunolins16** [comment]
> Thanks! This will go through API review before implementation.
> 
> @brunolins16 Do you have any insights that might guide the implementation/API review?

Sorry for late response.I like the idea and I am glad that the api is already approved. This will also useful for IProblemDetailsWrtier implementation.
