### ISSUE TITLE
How to get the razor code from a RenderFragment?

### ISSUE THREAD

**Issue by mueller-marcel** [dotnet/aspnetcore#47665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have the following exemplary blazor RenderFragment, built using the RenderTreeBuilder:
```
    private RenderFragment _Example = new RenderFragment(builder =>
    {
        builder.OpenComponent<MudButton>(0);
        builder.AddAttribute(1, nameof(MudButton.Color), Color.Error);
        builder.AddAttribute(2, nameof(MudButton.ChildContent), (global::Microsoft.AspNetCore.Components.RenderFragment)((builder2) =>
        {
            builder2.AddContent(3, "Test");
        }));
        builder.AddAttribute(4, nameof(MudButton.Variant), Variant.Outlined);
        builder.CloseComponent();
    });
```
Rendering this component using `@_Example` I get the following output:

<img width="58" alt="image" src="https://user-images.githubusercontent.com/48565242/231453626-6248e260-9cc9-4e1d-8135-9128af579315.png">

I am missing an opportunity to get the razor code from the RenderFragment as string like following

`<MudButton Color="Color.Success" Variant="Variant.Outlined">Test</MudButton>`

### Describe the solution you'd like

I would like to request to add a new Property called "RawContent" or "RazorCode" to the RenderFragment that returns the Razor code as described above as string. 

This way `_Example.RawContent` would return `<MudButton Color="Color.Success" Variant="Variant.Outlined">Test</MudButton>` as string.

### Additional context

This would be an useful feature to create documentations in order to render the RenderFragment and additionally to that showing the code of the RenderFragment

**Comment by javiercn** [comment]
@mueller-marcel thanks for contacting us.

That would require runtime compilation and building an AST for the markup, which is not something we have plans to support.

In addition to that, RenderFragment is a delegate type, so it can't be extended in the way you are asking.
