### ISSUE TITLE
.NET Core 2.0 Azure Web App. The specified CGI application encountered an error and the server terminated the process

### ISSUE THREAD

**Issue by andrei-m-code** [dotnet/aspnetcore#4766]
My app works well locally but I've got an error when I deployed it on Azure Web App:

`The specified CGI application encountered an error and the server terminated the process.`

My app is a .NET Core 2.0 Web API with no wwwroot folder. It creates instance of X509Certificate2 from byte array, I am pretty sure it fails here. I need to dynamically manage X509Certificates - uploading certificate to Web App is not an option.

I found this in [Microsoft Docs](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-availability-performance-application-issues-faq):

> A known issue with an earlier Kestrel version might cause an ASP.NET Core 1.0 app that's hosted in App Service to intermittently stop responding. You also might see this message: "The specified CGI Application encountered an error and the server terminated the process."
> 
> This issue is fixed in Kestrel version 1.0.2. This version is included in the ASP.NET Core 1.0.3 update. To resolve this issue, make sure you update your app dependencies to use Kestrel 1.0.2. Alternatively, you can use one of two workarounds that are described in the blog post ASP.NET Core 1.0 slow perf issues in App Service web apps.

I believe I use latest version of Kestrel dependencies from nuget package:

`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />`

I also tried to re-create Web App to make sure there is no junk left and I use everything latest. How can I fix it? Any ideas?

[Stackoverflow question here](https://stackoverflow.com/questions/47621285/net-core-2-0-azure-web-app-the-specified-cgi-application-encountered-an-error)

**Comment by jkotalik** [comment]
Closing as 2.0 is out of support and we haven't received reports of this issue for quite a while. Feel free to reopen or file a new issue if you continue to see this error.
