### ISSUE TITLE
Performance degradation in PersistingComponentStateSubscription

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#47669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently, I have noticed a drop in my site's performance by up to 100%. While searching for the problem, I probably came across an issue with Performance degradation in ``PersistingComponentStateSubscription`` and ``PersistentComponentState``.

In the example below if I don't use ``ApplicationState`` my page loads from 80 to 100ms, when using ApplicationState the page loads from 100/105 to even 140ms.

<details>
<summary>Page 1</summary>

```cs
namespace Stand.Plugins.Articles.Presentation.Areas.Web.Pages;

[Route("article/{name}")]
[Route("pl/article/{name}")]
[Route("pl-pl/article/{name}")]
public partial class Article : ComponentBase, IAreaWeb, IDisposable
{
    [Parameter] 
    public string Name { get; set; } = string.Empty;

    [Inject]
    PersistentComponentState ApplicationState { get; set; } = null!;

    [Inject]
    IArticleReadService ArticleReadService { get; set; } = null!;

    [Inject]
    ISearchService SearchService { get; set; } = null!;

    [Inject] 
    Culture Culture { get; set; } = null!;

    PersistingComponentStateSubscription persistingSubscription;
    Model? model { get; set; }

    protected override void OnInitialized()
        => Culture.OnChange += StateHasChanged;
    protected void Dispose()
        => Culture.OnChange -= StateHasChanged;
    void IDisposable.Dispose()
        => persistingSubscription.Dispose();

    protected override async Task OnParametersSetAsync()
    {
        persistingSubscription = ApplicationState.RegisterOnPersisting(Task () => { ApplicationState.PersistAsJson($"article-{Name}", model); return Task.CompletedTask; });
        if (!ApplicationState.TryTakeFromJson<Model>($"article-{Name}", out var dto))
        {
            var article = await ArticleReadService.GetAsync(Name);

            if (article is not null)
            {
                var tags = article.HashTags.Select(x => x.Tag).ToList();
                tags.Add("popular");
                tags.Add("hot");

                var articles = await SearchService
                    .Where(x =>
                        x.Status == Domain.Entities.Article.StatusType.Show &&
                        x.Id != article.Id)
                    .OrderByDescending(x => x.Details.Created)
                    .Take(6)
                    .ByTagsAsync(tags);

                model = new()
                {
                    Article = new ArticleDto(article),
                    Articles = articles.Select(x => new ArticleDto(x)).ToList()
                };
            }
        }
        else
        {
            model = dto!;
        }
    }

    class Model
    {
        public ArticleDto? Article { get; set; }
        public List<ArticleDto>? Articles { get; set; }
    }
}
```

</details>

The performance drop is not that strong, I did another test.

In the example below I had 100ms of page loading without ``PersistentComponentState``, if I used it it increased to 200-240.

<details>
<summary>Page 2</summary>

```cs
namespace Stand.Plugins.Articles.Presentation.Areas.Web.Pages;

[Route("/article")]
[Route("/pl/article")]
[Route("/pl-pl/article")]
public partial class Articles : ComponentBase, IAreaWeb, IDisposable
{
    //[Parameter]
    //public string? Tag { get; set; }
    
    [Inject] 
    PersistentComponentState ApplicationState { get; set; } = null!;

    [Inject]
    ISearchServiceFactory SearchServiceFactory { get; set; } = null!;

    [Inject]
    Culture Culture { get; set; } = null!;

    PersistingComponentStateSubscription persistingSubscription;
    Model? model { get; set; }

    protected override void OnInitialized()
        => Culture.OnChange += StateHasChanged;
    protected void Dispose()
        => Culture.OnChange -= StateHasChanged;
    void IDisposable.Dispose()
        => persistingSubscription.Dispose();

    protected override async Task OnInitializedAsync()
    {
        persistingSubscription = ApplicationState.RegisterOnPersisting(Task () => { ApplicationState.PersistAsJson($"articles", model); return Task.CompletedTask; });
        if (!ApplicationState.TryTakeFromJson<Model>($"articles", out var dto))
        {
            var hot = await SearchServiceFactory.Create()
                .Where(x => x.Status == Domain.Entities.Article.StatusType.Show)
                .OrderByDescending(x => x.Details.Created)
                .Take(6)
                .ByTagsAsync(new List<string> { "hot" });

            var popular = await SearchServiceFactory.Create()
                .Where(x => x.Status == Domain.Entities.Article.StatusType.Show)
                .OrderByDescending(x => x.Details.Created)
                .Take(6)
                .ByTagsAsync(new List<string> { "popular" });

            var hotIds = hot.Select(x => x?.Id);
            var popularIds = popular.Select(x => x?.Id);

            var recommendation = await SearchServiceFactory.Create()
                .Where(x => x.Status == Domain.Entities.Article.StatusType.Show && !hotIds.Contains(x.Id) && !popularIds.Contains(x.Id))
                .OrderByDescending(x => x.Details.Created)
                .Take(15)
                .AllAsync();

            model = new Model
            {
                Hot = hot.Select(x => new ArticleDto(x)).ToList(),
                Popular = popular.Select(x => new ArticleDto(x)).ToList(),
                Recommendation = recommendation.Select(x => new ArticleDto(x)).ToList(),
            };
        }
        else
        {
            model = dto!;
        }
    }

    class Model
    {
        public List<ArticleDto>? Recommendation { get; set; }
        public List<ArticleDto>? Hot { get; set; }
        public List<ArticleDto>? Popular { get; set; }
    }
}
```

</details>

I believe that this should be investigated and a test conducted. It also seems to me that the problem may have occurred in .net 8, as I remember correctly in .net 7 I did not have such problems.

If possibly I am doing something wrong then let me know but I consider this problem to be serious, my two subsites are not advanced. What if there was more content?

### .NET Version

.net 8 preview 3

**Comment by javiercn** [comment]
@Alerinos What's the size in bytes of the state you are serializing. Can you measure how much your Json serialization is taking?

**Comment by Alerinos** [comment]
@javiercn 
Test Page 2:
```cs
    var json = JsonSerializer.Serialize<Model>(model);
    var size = System.Text.Encoding.UTF8.GetBytes(json).Length;
    Console.WriteLine($"Size of JSON serialization: {size} bytes.");
```
Size of JSON serialization: 151609 bytes.

There is a little bit of ahowever, it seems to me that with this amount there should not be such a drop in performance.

**Comment by javiercn** [comment]
@Alerinos I am not sure how you are getting those numbers, so I can't tell if it's just anecdotical or an actual problem, and even in that case, it's not clear that the potential slowdown comes from the `PersistentComponentState` bits of from something else.

Note that in your case, you are serializing about ~ 200KB of data into the page, which is likely incurring into LOH allocations and might be causing extra GC pressure. Keep in mind, that we've designed this feature to serialize a moderate amount of state, like everything, it has its limits, and dozens of KB is likely ok, over 85KB will likely start to become slower.

For those cases, it's best if you can retrieve the state during app initialization via an API call, before a render has happened, and make it available via a service.

We are bound to do work in .NET 8.0 in this area, so it's likely going to be covered as part of that, but for us to motivate an investigation we need more concrete proof that there is a problem.

**Comment by javiercn** [comment]
> The times are very different, the other problem I see is when using PersistentComponentState is sent all to the client which I think is very bad.

PersistentComponentState sends the data to the client because it has to. Prerendering is "stateless" and we can't hold to the memory after the initial request to prerender is done for availability and security reasons.

It's the same reason why we serialize the parameters from the root components and send them back when we establish a circuit connection.

If you want to avoid the roundtrip, you can save an identifier in prerendered component state and cache the state you want based on that identifier, with all the implications that has for DoS, functionality of your app, etc.

It's the same reason why we didn't do stateful prerendering.

**Comment by Alerinos** [comment]
@javiercn 
I understand, yet sending everything to the client creates a risk of vulnerability to attack. The programmer may not be aware that he just sent data he shouldn't. E.g. a list of users and in it an encrypted password.
It should be included in the documentation that everything we send using ``PersistentComponentState`` is available at the client.
https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-7.0

**Comment by Alerinos** [comment]
@javiercn 
Now I got the idea that we should inform the programmers about the problem. You can set some json size limit. After exceeding it, it will return warning information about the decrease in performance. This will keep the developer aware of the problem. You can also return a link to the documentation in which we inform about it.
