### ISSUE TITLE
What's considered not cacheable re: `AllowsCachingPolicies`

### ISSUE THREAD

**Issue by pinkfloydx33** [dotnet/aspnetcore#47677]
I am wondering what is/isn't considered a "cacheable" authorization policy in terms of `IAuthorizationPolicyProvider.AllowsCachingPolicies`

We have a custom authorization policy provider that turns policy names of a specific form into policies with various requirements on them. For example `MyPolicy::SomeResource::Read|Update` might get turned into a policy with a requirement that the user has permissions to either read or update `SomeResource`. For anything we cannot handle, we fall back to the default provider. These are mostly configuration driven (mainly yarp) but some via MVC attributes. 

My feeling is that our provider _can_ indicate that policies are cacheable. However [a comment on the original issue](https://github.com/dotnet/aspnetcore/issues/43227#issuecomment-1222734882) has me concerned:

> Why not cache all policies?
The policy might look at the HttpContext and vary based on the request. 

The _requirements_ on the policy might look at information about the request/user. But I feel like all requirements do. So is this comment strictly about the provider itself using the request (via context accessor, etc.) when determining what requirements to add to the policy builder? 

What would be an example of something not safe for caching?

**Comment by pinkfloydx33** [comment]
Also I guess let me follow up with this: does policy caching actually get triggered? Or rather, how do you add the `AuthorizationMiddleware` such that [the constructor](https://github.com/dotnet/aspnetcore/blob/68ae6b0d8aa2f4a0ff189d5cedc741e32cc643d2/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L65-L76) which takes the `IServiceProvider` and sets the `_canCache` flag based on the policy provider is called?

In all my debugging/step-through this morning, I could only get the [2-arg constructor](https://github.com/dotnet/aspnetcore/blob/68ae6b0d8aa2f4a0ff189d5cedc741e32cc643d2/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L36-L42) to invoke (both with my current app and a brand new minimal API project). The only way I was able to trigger it was to manually add the `AuthorizationMiddleware`, passing `ApplicationServices` to  `UseMiddleware`

```csharp 
app.UseMiddleware<AuthorizationMiddleware>(app.ApplicationServices);
```
Obviously that's just for testing/debugging purposes. But
searching through the repo, there doesn't seem to be any gesture that enables that constructor. Am I missing something?

**Comment by halter73** [comment]
> I am wondering what is/isn't considered a "cacheable" authorization policy in terms of `IAuthorizationPolicyProvider.AllowsCachingPolicies`

The cached policy is keyed on the [Endpoint](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0#endpoints) being matched.

> What would be an example of something not safe for caching?

If the custom `IAuthorizationPolicyProvider` needs to return a different `AuthorizationPolicy` instance for requests matching the same `Endpoint`, it would not be safe. The `DefaultAuthorizationPolicyProvider` will always return the same policy for a given endpoint, so it `AllowsCachingPolicies`.

> Obviously that's just for testing/debugging purposes. But searching through the repo, there doesn't seem to be any gesture that enables that constructor. Am I missing something?

This seems like a real issue. I see the same thing just calling `UseAuthorization()`. This looks like https://github.com/dotnet/aspnetcore/issues/2871 come again. I wonder if we need to add the `[ActivatorUtilitiesConstructor]` attribute to the longest constructor.

Better yet would probably be to switch `UseMiddleware` from using [aspnetcore's shared ActivatorUtilities class](https://github.com/dotnet/aspnetcore/blob/542da423ff3394e86fd7608fc425fadd33ba3fd9/src/Shared/ActivatorUtilities/ActivatorUtilities.cs) to [the one we ship publicly from DI](https://github.com/dotnet/runtime/blob/5318f75f9040726f6d86fa35778df86b109f9658/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs) that uses `IServiceProviderIsService` to select the "longest" satisfiable constructor. Although that might be a little riskier @adityamandaleeka @Tratcher @davidfowl

**Comment by pinkfloydx33** [comment]
I believe #49593 fixes the bug part of this

**Comment by mkArtakMSFT** [comment]
Closing as there is no remaining action pending here.
