### ISSUE TITLE
RequestAborted should not be fired for disconnects after the request and response have completed

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#4767]
_From @tcuk on November 30, 2017 16:11_

Session state does not persist in Redis when the client has HTTP keep-alives *disabled* (i.e. rather than specifying HTTP header *connection: keep-alive*, the client specifies *connection: close*).

OS: Ubuntu 16.04 LTS
ASP.NET Core version: 2.0.3

Startup used to configure session:

```
using System;
using System.Net;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

namespace Woo.Website
{
	public class Startup
	{
		public Startup(IHostingEnvironment env)
		{
			string hostname = Dns.GetHostName();

			var builder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.AddJsonFile("appsettings.json")
				.AddEnvironmentVariables();

			Configuration = builder.Build();

			HostingEnvironment = env;
		}

		public IConfigurationRoot Configuration { get; set; }

		public IHostingEnvironment HostingEnvironment { get; set; }

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddMvc();

			services.AddDistributedRedisCache(options =>
			{
				options.Configuration = Configuration["redis:server"] + ":" + Configuration["redis:port"];
				options.InstanceName = Configuration["redis:instance"];
			});
			
			services.AddSession();
		}

		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			app.UseDeveloperExceptionPage();

			app.UseForwardedHeaders();
			app.UseSession();
			app.UseMvc();
		}
	}
}
```

I discovered this when using nginx as a reverse proxy to Kestral. Using nginx as a reverse proxy it is easy to enable/disable HTTP keep-alives to reproduce the problem. My proxy config for nginx is:

server {
	listen 80;
	
	gzip on;
	gzip_proxied	no-cache no-store private expired auth;
	gzip_types
		text/plain
		text/css
		text/js
		text/xml
		text/javascript
		application/javascript
		application/x-javascript
		application/json
		application/xml
		application/rss+xml
		image/svg+xml;
	gzip_disable "MSIE [1-6]\.";
	gzip_vary on;

	location / {
		proxy_pass			http://aspnet_server;
		proxy_redirect		off;
		proxy_http_version	1.1;
		proxy_buffering		off;
		proxy_cache_bypass	$http_upgrade;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection keep-alive;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Host $host;
		proxy_set_header	X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	X-Forwarded-Host $server_name;
		proxy_set_header	X-Forwarded-Proto $scheme;

	}

	location ~ /.well-known {
		alias /etc/letsencrypt/html/.well-known/$1;
		allow all;
	}

	rewrite ^/(.*)/$ /$1 permanent;
}

Changing the line *proxy_set_header Connection keep-alive* to *proxy_set_header Connection close* disables keep-alives and session state stops working.

I was using the latest nginx package for Ubuntu 16.04 LTS and ASP.NET Core 2.0.3 on Ubuntu 16.04 LTS. These instances were run as containers within docker.

_Copied from original issue: aspnet/Session#201_

**Comment by brechtvhb** [comment]
I "fixed" this by manualy commiting my session. I spent hours finding out what the problem was ..
HttpContext.Session.CommitAsync();

**Comment by kieranbenton** [comment]
I've just run into this as well - setting a session key that would not get persisted but only in Edge! Lucky I found this relatively quickly... Whats the eventual resolution plan for this? I'd suggest that it would be preferable for the distributed cache to never commit itself automatically than leave it inconsistent.

**Comment by davidfowl** [comment]
@Tratcher  @halter73 isn't this fixed?

**Comment by jkotalik** [comment]
Repinging @Tratcher @halter73 , I don't have much context here, can this be closed?

**Comment by halter73** [comment]
Yes. https://github.com/aspnet/KestrelHttpServer/pull/2977
