### ISSUE TITLE
CA1512 build error when building aspnetcore with latest SDK version

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#47673]
The following build error was encountered when building aspnetcore with the latest SDK which is a required scenario for source-build. This occurs when building the aspnetcore repo using the latest build of .NET 8 Preview 4.

```
/vmr/src/aspnetcore/artifacts/source-build/self/src/src/SignalR/common/Http.Connections/src/HttpConnectionDispatcherOptions.cs(111,13): error CA1512: Use 'ArgumentOutOfRangeException.ThrowIfEqual' instead of explicitly throwing a new exception instance [/vmr/src/aspnetcore/artifacts/source-build/self/src/src/SignalR/common/Http.Connections/src/Microsoft.AspNetCore.Http.Connections.csproj]
```

Related: https://github.com/dotnet/source-build/issues/3374

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/47540

**Comment by adityamandaleeka** [comment]
This can be closed since the SDK update was merged right?

@mthalman Should the NoWarn you added be removed as well?
