### ISSUE TITLE
Google oauth2 An error was encountered while handling the remote login.

### ISSUE THREAD

**Issue by McFly2017** [dotnet/aspnetcore#47689]
I follow this https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-6.0
My index page can show Goole Login button,then click my account, makes some error like this:
when I remove app.UseAuthentication();,it can hit my breakpoint

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: The oauth state was missing or invalid.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by javiercn** [comment]
Thanks for contacting us.

When the app navigates to Google ASP.NET Core sets a cookie, it seems that for some reason ASP.NET Core is not able to see the cookie when the app returns via the callback URL. Could you check 1) That the cookie is being set in the initial, and 2, that the cookie is being sent on the callback?

**Comment by Tratcher** [comment]
Sharing a decrypted Fiddler trace would be helpful.

**Comment by McFly2017** [comment]
StartUp.cs Code
`.AddGoogle(options =>
    {
        options.ClientId = "xxxxxxxxxxxxxxxx.apps.googleusercontent.com";
        options.ClientSecret = "xxxxxxxxxxxxx";
        options.CallbackPath = "/sssss";
    });`
This is controller code:
`[Route("/")]
    public class GoogleSignController : Controller
    {

        [HttpPost("signin-google")]
        public async Task<IActionResult> SigninGoogle([FromForm] GoogleAuth googleAuth)
        {
             await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity));
             return Redirect("/");
        }
}`
I give the callback path a wrong path, then write a controller with route signin-goole.
Fortunately, it can hit my breakpoint, and I parse the credential by myself, now the login is success.
But I don't know why it is work normal

**Comment by Tratcher** [comment]
It sounds like you're doing Google OpenIdConect (using POST), not OAuth2 (GET). Try using the OpenIdConect handler instead.

**Comment by McFly2017** [comment]
> It sounds like you're doing Google OpenIdConect (using POST), not OAuth2 (GET). Try using the AddOpenIdConect handler instead.

I click the Google Login button,then open the select user page.
like this: https://accounts.google.com/gsi/select?client_id=xxxxxxxxxx.apps.googleusercontent.com&ux_mode=popup&ui_mode=card&context=signin&as=xxxxx&channel_id=xxxxxxxxxxxx&origin=https%3A%2F%2Flocalhost%3A6200
when I click my account,it's callback url is setting url in Google cloud credentials, 
I follow this page: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token?hl=zh-cn
and verify the credential by myself 
so, it's oauth or openidconnect?
Can u show me a simple oauth2 demo, thank you very much
