### ISSUE TITLE
[Question/Issue?] Blazor Server CORS ?

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#47690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a Blazor Server application running on Azure.
The app uses B2C login.

Blazor Server app/pages are only accessible for signed in and approved users.
In a few cases we need public anonymous accessible pages (accessible for guest users).

It took already an effort to realize this but we succeeded in showing some pages (accessible for guests) in the app, in the same Blazor server app.

However we are facing an issue, what we believe has to do with blazor javascript file and CORS.

If we use a browser where we have never logged in to our application (tested Edge and Firefox) as a result, the part of the form we display is not visible (while the HTML itself is produced if we look in F12-developer tools html source code).

We sent an email with a link to our Blazor app, (specific page with some parameters) which is accessible for guest users.
When we click that link, a webbrowser opens (we are NOT signed-in in the app in that browser) and tries to load Blazor server javascript, but this fails due to CORS. In our F12-develpment tools of Edge we see:

access to fetch at 'https://<ourname>.b2clogin.com/<ourname>.onmicrosoft.com/b2c_1_signin_signup/oauth2/v2.0/authorize?...' (redirected from 'https://[our url]/_blazor/initializers') from origin 'https://[our url]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

If I understand the error, it seems that '_blazor/initializers' is a controller with authorize attribute, but we need to have blazor as anonymous for certain pages. How can this be done?

Any suggestions? 

Is this a bug or can CORS be changed at .onmicrosoft.com ?

### Expected Behavior

no CORS error

### Steps To Reproduce

see description (can't add a minimal repro solution... it is in our production environment)

### .NET Version

7.x

### Anything else?

VS2022 
Win10x64 - Win11x64
.net 7
Edge/FireFox

**Comment by wstaelens** [comment]
@javiercn you mean MapBlazorHub() instead of MapcomponentHub? 

Any examples how to allow this only for a specific url/route for anonymous access?

**Comment by wstaelens** [comment]
Guess we are not the only one strugling with this:

- https://stackoverflow.com/questions/63722949/blazor-server-app-cannot-access-the-static-content-of-the-subproject
- https://stackoverflow.com/questions/70138880/anonymous-endpoint-redirects-to-login-screen-in-secured-asp-net-core-web-applica
- https://stackoverflow.com/questions/60768399/blazor-using-azure-ad-authentication-allowing-anonymous-access
- https://stackoverflow.com/questions/72487140/allow-anonymous-access-to-index-authorize-everything-else
- https://stackoverflow.com/questions/64853618/oidc-authentication-in-server-side-blazor
- ...

**Comment by davidfowl** [comment]
It's unclear exactly what the issue is, but with Blazor server you have to make sure a connection can be made to the hub if you want a subset of the components to be anonymous. Or maybe those parts of the application can be razor pages. It's hard to tell what the cors issue might be without a sample or errors or more details.

**Comment by wstaelens** [comment]
Blazor Server app is hosted as Azure App Service, uses Azure B2C. 
Customers need to log in, in order to work with the application.

However, there is functionality where a unique, dynamic URL is being emailed to e.g. a customer. (e.g. something like https://app.site.com/Module/Foo?x=45454-5667-q856qd-566887/ ) 

This url should be accessible anonymously.  But this is where we have the problem (or maybe need more documentation/examples).

The razor page (using Blazor Server) is displayed but clicking something doesn't do anything as the SignalR communication to the server is broken, making it unusable.

As a quick fix we had to use Asp.net core mvc forms on the page, because that doesn't use SignalR and everything works fine.

For us it is unclear either what is causing it. Any samples how this could/should be configured?
