### ISSUE TITLE
[Blazor-wasm] Smoother page navigation

### ISSUE THREAD

**Issue by r-work** [dotnet/aspnetcore#47691]
When navigating to a page with a "hevy" third party component, the app freezes for about a second or two, then shows the page.
This is especially noticeable when navigating to the page first time. The page has other basic elements (like page title), it seems to be all or nothing.

Is it possible to show a skeleton/loading content while that component is loading?

**Comment by javiercn** [comment]
@r-work thanks for contacting us.

It's not clear what you mean by this.
> When navigating to a page with a "hevy" third party component, the app freezes for about a second or two

Does this mean that the page takes time to load, or that it becomes completely unresponsive (in the browser).

In general, if a component is "hogging" the main thread for a couple of seconds, there's nothing we can do about it. The component author is the one responsible for ensuring that their component is responsive.

If what the component is doing is performing some async work, then it's also up to them to display a skeleton in the meantime. There's really nothing you can do externally.

**Comment by r-work** [comment]
@javiercn thanks for the quick response.
Sorry if I didn't make myself clear, the app appears to be freezing while the page is loading, as you can move the mouse over other elements in the main layout and not see the usual hover effect for example.

I understand what you're saying, I thought there would've been a way to show something while the page is getting loaded/rendered.
