### ISSUE TITLE
AspNetCore.SignalR is reconnecting from client (angular 7) and then unable to receive latest message

### ISSUE THREAD

**Issue by shripadgodse** [dotnet/aspnetcore#47694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have .Net Core 3.1 API application with client side technology as Angular 7 and i am trying to use SignalR with Redis setup like mentioned below
![image](https://user-images.githubusercontent.com/36620801/231807896-35bd7679-c665-4933-9d6c-4d118418cb5f.png)
Angular side
![image](https://user-images.githubusercontent.com/36620801/231808130-1c43fe3c-d63a-45c6-b082-5931606b1bf5.png)
And i am using Group at backend to hold the logged in user like below also i am using the Group for holding users against the some Id
![image](https://user-images.githubusercontent.com/36620801/231808488-af06394f-0989-4292-8cdf-dab7814dc906.png)
With above setup everything is working fine though when client side tries to reconnect with signalr it gets failed and we are not able to receive any kind of message from backend not sure why. Any help regarding the same is appreciated.
Client side is trying to reconnect with signalr after some time with negotiate call and gets new connection and thats when it starts failing to receive/send message over signalr. We have disabled stickiness for load balancer and target group as well though its not working for single server also. Below is the screenshot showing how signalr is reconnecting and unable to receive message
![image](https://user-images.githubusercontent.com/36620801/231808631-16cef134-23c9-40fc-b752-aa7981685137.png)

### Expected Behavior

I am expecting to receive/send the messages from/over signalr even after reconnection of signalr

### .NET Version

.NET Core 3.1 and .NET 6

**Comment by BrennanConroy** [comment]
> I am expecting to receive/send the messages from/over signalr even after reconnection of signalr

Nothing above shows that you aren't able to send/receive after reconnect. If anything, your screenshot shows the connection **is working** after reconnect. (assuming the network calls are in oldest to newest order)

If I had to guess from the incomplete example shown above, you are likely calling `CreateOrJoinLogOutUser` when you first create the connection, but not when the connection reconnects. Which means it won't be part of the group on reconnect.

P.S. Please don't paste code as a screenshot. We can't copy-paste from it if we want to reference a method or try out your code in a more complete example. Use [githubs markdown](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by shripadgodse** [comment]
@BrennanConroy  Thank you very much for quick response. In above example the key is UserId so the group will only be one just there will be multiple connectionId's as per my understanding, isn't it? And if this is the case then i should receive message for previous connection also i i publish message for respective group.

**Comment by shripadgodse** [comment]
@BrennanConroy  Thank you for the help! i was not registering to the server events and adding user to group after the reconnection and now i am able to send/receive messages to/from server by registering to server event and adding user to group.
