### ISSUE TITLE
Respond to IL2026 warnings in DataProtection originating from EncryptedXml

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#47695]
With https://github.com/dotnet/runtime/pull/84468, `EncryptedXml` is now marked as `RequiresUnreferencedCode`. This is because

```
The algorithm implementations referenced in the XML payload might be removed. Ensure the required algorithm implementations are preserved in your application.
```

From discussion in https://github.com/dotnet/aspnetcore/issues/47410#issuecomment-1497423603, we should:

1. Figure out the list of commonly used crypto algorithms used by DataProtection, and add `[DynamicDependency]` attributes for them.
2. We also add some trimming/aot tests to ensure DataProtection works correctly when trimmed.
3. DataProtection then suppresses the warnings coming from `System.Security.Cryptography.Xml`

**Comment by blowdart** [comment]
Good luck :)

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-7.0

So the defaults are AES-256-CBC and HMACSHA256 however EncryptedXml is nicely flexible, so any hmac and any symmetric key algorithm is possible.

What you probably want as a starting point is anything that can be configured with the easy access settings,

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#changing-algorithms-with-usecryptographicalgorithms

Which ends up being https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.authenticatedencryption.configurationmodel.authenticatedencryptorconfiguration?view=aspnetcore-7.0

For encryption it's only AES without a bunch of work,

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.authenticatedencryption.encryptionalgorithm?view=aspnetcore-7.0

For validation it's only HMAC256 and HMAC512

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.authenticatedencryption.validationalgorithm?view=aspnetcore-7.0

**Comment by eerhardt** [comment]
Note: when doing this work, we should remove the RequiresUnreferencedCode attribute that was added to AddAuthentication() in https://github.com/dotnet/aspnetcore/pull/47663.

https://github.com/dotnet/aspnetcore/blob/58074006cbf5a6583c561306821b287423c8012e/src/Security/Authentication/Core/src/AuthenticationServiceCollectionExtensions.cs#L20-L21
