### ISSUE TITLE
Any update on when the Authorization Server enhancements will ship?

### ISSUE THREAD

**Issue by dario-l** [dotnet/aspnetcore#47699]
Any update on when the Authorization Server enhancements will ship?

_Originally posted by @jculverwell in https://github.com/dotnet/aspnetcore/issues/3265#issuecomment-463059472_

**Comment by danroth27** [comment]
Hi @dario-l. We don't have any plans to include a full OAuth 2.0 compliant authorization server in ASP.NET Core. We do plan in .NET 8 to add support in ASP.NET Core identity for token based authentication. For details on these plans, see https://devblogs.microsoft.com/dotnet/improvements-auth-identity-aspnetcore-8/.
