### ISSUE TITLE
Async resource filter AfterOnResourceExecution diagnostic event only emitted on short-circuit

### ISSUE THREAD

**Issue by mitchvm** [dotnet/aspnetcore#47698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `AfterOnResourceExecution` diagnostic event is only emitted if the resource filter short-circuits the request. The analogous action filter event, `AfterOnActionExecution`, is emitted regardless if the request is short-circuited or not.

### Expected Behavior

The `AfterOnResourceExecution` diagnostic event is emitted upon completion of all async resource filters, regardless if the request was short-circuited or not.

### Steps To Reproduce

https://github.com/mitchvm/AfterOnResourceExecutionEventBug

This code provides a unit test project that uses the ASP.NET Core test host to reproduce the issue.

Steps to run:

1. Build the project.
2. Run the unit tests.

Expected results: all test cases pass - the `AfterOnResourceExecution` diagnostic event is emitted in all cases

Actual results: the test cases in which the Async resource filter does not short-circuit the request fail because the `AfterOnResourceExecution` event was not emitted

### .NET Version

7.0.100

### Anything else?

* The [line of code](https://github.com/dotnet/aspnetcore/blob/e53379914e7ed68eab66f5dac5c8682ac6f3545e/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs#L508) that emits the `AfterOnResourceExecution` event. It is within an `if (_resourceExecutedContext == null)` block, but that block should likely end prior to the event being emitted.
* The corresponding [line of code](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs#L160) that emits the `AfterOnActionExecution` event, for comparison.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. If you are willing to contribute a fix, we'll be happy to take it.

**Comment by smnsht** [comment]
Hello,

My branch has passed all checks.

Should I convert my draft to PR?
