### ISSUE TITLE
Avoid CA2201 (Generic Exception) Violations

### ISSUE THREAD

**Issue by dahlbyk** [dotnet/aspnetcore#47708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

#46212 was closed by a [comment](https://github.com/dotnet/aspnetcore/issues/46212#issuecomment-1400621532) describing ways to override how `RemoteAuthenticationHandler` handles remote failure, but this doesn't help from an observability/telemetry standpoint. I imagine many teams consider any thrown `System.Exception` to be a critical error. We could work around it for `RemoteAuthenticationHandler`, but it would be better if the platform avoided `new Exception()`.

### Describe the solution you'd like

Resolve all [CA2201](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201) violations, or at least those related to `System.Exception`, in non-test/benchmark code by throwing a more specific exception.

### Additional context

This feels like it could be up-for-grabs if there's project guidance on scoping custom exceptions.

**Comment by MackinnonBuck** [comment]
Can you please describe a specific scenario that would be affected by this? This will help us determine how to prioritize the issue. Thanks!

**Comment by dahlbyk** [comment]
> Can you please describe a specific scenario that would be affected by this?

We're observing "Correlation mismatch." and related errors when a user messed with their token or let it expire. Since these aren't errors we can take action on, we'd like to suppress alerts. We normally filter by exception type, but suppressing `System.Exception` for specific message matches is not ideal.

**Comment by dahlbyk** [comment]
Started writing up some proposed types and realized a PR would be easier: #47873.

Not sure how you generated your list, @danmoseley, but I don't think it found everything:
- https://github.com/dotnet/aspnetcore/blob/ae54fe016e11fc88ed8e4a57f904a35d60cc80be/src/SignalR/common/Shared/ClientResultsManager.cs#L30
- https://github.com/dotnet/aspnetcore/blob/ae54fe016e11fc88ed8e4a57f904a35d60cc80be/src/SignalR/server/Core/src/StreamTracker.cs#L73

-----------------------------

> Changing IndexOutOfRangeException and NullReferenceException would potentially be breaking if they're exposed publicly, so they'd need analysis.

All the `IndexOutOfRangeException` map directly to `ArgumentOutOfRangeException`. Folks _should_ be checking their bounds instead of catching anyway. 😁 

The NRE is arguably an `ArgumentException` or `InvalidOperationException`.
https://github.com/dotnet/aspnetcore/blob/ae54fe016e11fc88ed8e4a57f904a35d60cc80be/src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs#L98-L104

**Comment by dahlbyk** [comment]
Per @halter73 in https://github.com/dotnet/aspnetcore/pull/47873#discussion_r1176801784, here's a proposal for an `AuthenticationException`:

## Proposed API

Included in #47873:
```csharp
namespace Microsoft.AspNetCore.Authentication;

public sealed class AuthenticationException : Exception
{
    public AuthenticationException(string? message) : base(message) { }

    public AuthenticationException(string? message, Exception? innerException) : base(message, innerException) { }
}
```

## Usage Examples

A few are included in #47873, e.g.
```diff
     public static AuthenticateResult Fail(string failureMessage)
-        => Fail(new Exception(failureMessage));
+        => Fail(new AuthenticationException(failureMessage));
```

## Alternative Designs

- Reuse [System.Security.Authentication.AuthenticationException](https://learn.microsoft.com/en-us/dotnet/api/system.security.authentication.authenticationexception) instead? Semantics for that exception seem different, e.g. https://github.com/dotnet/aspnetcore/pull/47873#discussion_r1176017093.
- My initial implementation was `sealed`, like most custom exceptions I found in the project, but I could imagine user scenarios where it would be handy for this to be inheritable as a base class for custom auth exceptions. I don't expect the framework to ever `catch (AuthenticationException)` directly.

## Risks

- Name conflict with `System.Security.Authentication.AuthenticationException` could be confusing.
- As discussed [here](https://github.com/dotnet/aspnetcore/pull/47873#discussion_r1176006433), I think a slightly breaking change is warranted so `NegotiateState` can use the new exception: https://github.com/dotnet/aspnetcore/blob/47d07849445e218b0c4097feaffad224eb1a8d47/src/Security/Authentication/Negotiate/src/Internal/NegotiateState.cs#L33

**Comment by dahlbyk** [comment]
> * Name conflict with `System.Security.Authentication.AuthenticationException` could be confusing.

@Tratcher [suggests](https://github.com/dotnet/aspnetcore/pull/47873#discussion_r1176966608) `AuthenticationFailureException`, which seems perfectly reasonable to me. Will wait for guidance out of API review.

**Comment by danmoseley** [comment]
Agreed it is almost surely acceptable to change the NRE as it's so unlikely anyone is catching it. We have replaced those in numerous public API lower down the stack without incident.

WRT how I generated the list - I added the code to the root editorconfig (where it should go long term) and ran eng\build.cmd. Perhaps that doesn't build everything.

**Comment by halter73** [comment]
Thanks for the API proposal @dahlbyk. We'll try to review this Monday

I agree that this risk of having the same name as `System.Security.Authentication.AuthenticationException`. I'm leaning towards reusing that even if it's slightly beyond the documented usage. We already do this in some of Kestrel's SNI logic and in a few other places that would probably be considered off label. System.Net.Quic also uses it. We can look into updating the docs.

https://source.dot.net/#System.Net.Security/System/Security/Authentication/AuthenticationException.cs,6749b117ae40d22c,references

**Comment by Tratcher** [comment]
Don't re-use it, that's already an exception that could happen in this code path, such as from providers that make external requests to retrieve or verify tokens (OAuth, OIDC). Getting this exception type for a different reason would be confusing. While I like re-using exceptions, this one is too specific to `System.Security.Authentication` components. I think we're better off with our own uniquely named exception here.

**Comment by dahlbyk** [comment]
I've started chipping away at the `IndexOutOfRangeException`s, too. Should I just push everything into https://github.com/dotnet/aspnetcore/pull/47873 for a mega-review that ends with warnings as error? I was thinking I'd break the changes down by exception type, but it's easier find them all together.

**Comment by dahlbyk** [comment]
@halter73 please note https://github.com/dotnet/aspnetcore/issues/47708#issuecomment-1522276638 has been updated slightly to align with current implementation.
