### ISSUE TITLE
Add support for binding to MarkupString values

### ISSUE THREAD

**Issue by kzu** [dotnet/aspnetcore#47718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's not possible to bind components to properties of type `MarkupString` out of the box.

This can be quite convenient when you have fragments of HTML that can be directly bound, although not typically in a bi-directional way?

### Describe the solution you'd like

Add a `[TypeConverter(typeof(MarkupStringTypeConverter))]` to the `MarkupString` type so that things Just Work.

**Comment by javiercn** [comment]
@kzu thanks for contacting us.

Unfortunately, I don't think this is a change we want to take in. MarkupString is considered an "escape hatch" to render markup without HTML encoding it.

As such, we don't think it should be easy to bind inputs into it, as that creates a pit of failure for developers where they can easily introduce XSS vulnerabilities in their app.

**Comment by kzu** [comment]
Oh well, I guess my blog post will just get popular then :). For folks coming across this, head over to https://www.cazzulino.com/blazor-markupstring.html

I see your point though.
