### ISSUE TITLE
Allow/support route grouping for third-party controllers

### ISSUE THREAD

**Issue by QuantumToasted** [dotnet/aspnetcore#47724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello there. I am consuming the library [Estranged.Lfs](https://github.com/alanedwardes/Estranged.Lfs), which includes a package which maps the [git-lfs API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md). This package bundles its own API controllers, of which the ones I am using map to `/objects/batch`.

While attempting to add a "global" route prefix `/api` to all routes, I stumbled upon `UsePathBase()` and later, #45076 mentioning that while `UsePathBase("/api")` would allow me to map these to `/api/objects/batch`, the original `/objects/batch` endpoint would remain. [this comment](https://github.com/dotnet/aspnetcore/issues/45076#issuecomment-1314450118) states:
> If you only want to match requests with this prefix then you should include it in the routes, or use the new 7.0 route groups feature.

To my understanding, **neither** of the proposed solutions apply to third-party controllers. I can't include it in the routes - the routes are defined in third-party code. And I can't use route groups, because from what I've read, those are a feature exclusive to the new "minimal API" paradigm, of which controllers are not applicable to be part of.

### Describe the solution you'd like

Either of these would be fine, and of course of there are other more elegant solutions, they would be even more fine:
- A way to configure `UsePathBase()` to completely erase the original route definitions, leaving the "prefixed" ones intact.
- A way to utilize minimal APIs with existing third-party controllers in some way (if it's not already possible)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. It sounds like [these docs](https://learn.microsoft.com/aspnet/core/mvc/controllers/application-model?view=aspnetcore-7.0#custom-routing-convention) might help provide a solution to your situation.
