### ISSUE TITLE
Deploy Blazor WASM on Linux Azure App Service

### ISSUE THREAD

**Issue by tbasallo** [dotnet/aspnetcore#47737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A Blazor WASM project cannot be deployed to Azure App Service on a Linux plan (in VS2022). However, a Blazor Server project CAN be deployed to a Linux plan.

Additionally, there is an option for Linux containers, but that's a whole other set of dependencies I rather avoid.

### Describe the solution you'd like

Enable Azure App Service Linux deployment option (in addition to the current Windows option).

**Comment by javiercn** [comment]
@tbasallo thanks for contacting us.

Are you talking about a Blazor Webassembly standalone project?

**Comment by tbasallo** [comment]
In this case I am speaking about ASP.NET Core Hosted Blazor WASM project.

**Comment by tbasallo** [comment]
For reference, this is the publish screen after selecting Azure in VS2022 Preview 17.6.0 4.0

![image](https://user-images.githubusercontent.com/270673/232905260-06f26744-0443-46b9-8524-a448f95a71a0.png)

**Comment by mkArtakMSFT** [comment]
@vijayrkn is this something you plan to do? How would you like to track this? Should the customer file a new request through VS Feedback?

**Comment by tbasallo** [comment]
For others:

There was a [VS feedback](https://developercommunity.visualstudio.com/t/Publish-Blazor-WASM-to-App-Service-Linux/1002767?q=deploy+blazor+to+app+service+linux) by Jeff Fritz that got sent back to this repo #28611 which discusses the issue and feature request.

The good news is that it works...

You must host the site in ASP.NET Core (this is the template with three projects: shared, client and server). You can publish the Server project (right-click) and the Linux App Service will now appear and you can publish to it and host your Blazor WASM project.

FYI: I was right-clicking the client project.
