### ISSUE TITLE
SignalR client side taking too long to connect, Using Latest Angular .Net Template on Visual Studio

### ISSUE THREAD

**Issue by le0maxx** [dotnet/aspnetcore#47732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the latest Angular with .Net 6 template on visual studio.

I don't quite understand why it takes 4mins to connect to the SignalR websockets.

This was taking too long:
![image](https://user-images.githubusercontent.com/49972225/232246566-be63da9b-8986-4f4c-b8d7-2746b53b2fbf.png)

It took 4mins to connect
![image](https://user-images.githubusercontent.com/49972225/232246607-9997e8db-b00a-43a6-82bd-5cf5a8776514.png)

Heres my code

HubClient.cs

        `
            using Microsoft.AspNetCore.SignalR;
            
            namespace Base64Converter.Hub
            {
                public class HubClient : Hub<IHubClient>
                {
            
                    public async Task SendDecodedText(string text)
                    {
                        await Clients.All.SendDecodedText(text);
            
                    }
            
              
            
                }
            }
        `

program.cs

          `using Base64Converter.Hub;
          
          var builder = WebApplication.CreateBuilder(args);
          
          // Add services to the container.
          
          builder.Services.AddControllersWithViews();
          
          
          builder.Services.AddSignalR();
          builder.Services.AddCors(options =>
          {
              options.AddPolicy("CORSPolicy",
                  builder => builder
                  .AllowAnyMethod()
                  .AllowAnyHeader()
                  .AllowCredentials()
                  .SetIsOriginAllowed((hosts) => true));
          });
          
          
          
          
          builder.Services.AddControllers();
          builder.Services.AddEndpointsApiExplorer();
          
          var app = builder.Build();
          
          // Configure the HTTP request pipeline.
          if (!app.Environment.IsDevelopment())
          {
              // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
              app.UseHsts();
          }
          
          app.UseCors("CORSPolicy");
          app.UseHttpsRedirection();
          app.UseStaticFiles();
          app.UseRouting();
          app.UseAuthorization();
          app.UseEndpoints(endpoints =>
          {
              endpoints.MapControllers();
              endpoints.MapHub<HubClient>("encoderhub");
          });
          
          
          
          app.MapControllerRoute(
              name: "default",
              pattern: "{controller}/{action=Index}/{id?}");
          
          //app.MapHub<HubClient>("encoderhub");
          app.MapFallbackToFile("index.html"); ;
          
          app.Run();
          `

Angular component.ts

            `
              ngOnInit(): void {
                console.log("On Init");
            
                let accessToken = "3076a225-f2f6-4c68-b894-08accb62bb90";
            
            
                try {
                  this.hubConnectionBuilder = new HubConnectionBuilder()
                    .withUrl('http://localhost:44455/encoderhub')
                    // .withUrl('http://localhost:44455/encoderhub', { accessTokenFactory: () => accessToken })
                  .configureLogging(LogLevel.Information)
                  .build();
            
                this.hubConnectionBuilder
                  .start()
                  .then(() => console.log('Connection started.......!'))
                  .catch(err => console.log('Error while connect with server'));
                  
                this.hubConnectionBuilder.on('SendDecodedText', (result: any) => {
                  console.log("Result:",result)
                  this.result = this.result.concat(this.result,result)
                });
                } catch (error) {
                  console.log("ERROR")
                }
            
               
            }`

proxy.conf.js

    `const { env } = require('process');
    
    const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
      env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:37105';
    
    const PROXY_CONFIG = [
      {
        context: [
          "/weatherforecast",
          "/encoder",
          "/encodetext",
          "/encoderhub"
       ],
        target: target,
        secure: false,
        headers: {
          Connection: 'Keep-Alive'
        }
      }
    ]
    
    module.exports = PROXY_CONFIG;
    `

### .NET Version

.Net 6

**Comment by mitchdenny** [comment]
@le0maxx I hope that isn't a real access token in your code. To help us reproduce this issue can you create a public GitHub repro with just the minimal code required to reproduce the issue that you are seeing. We can then download it and take a look.

**Comment by le0maxx** [comment]
Hi Dotnet/Aspnetcore,

Sorry for the late reply.
Yes, that is not a real access token.

Here's my repository: https://github.com/le0maxx/Base64Converter

Thank you
Leo

**Comment by mitchdenny** [comment]
@le0maxx I think that is could be an issue with the webdev server proxying the websockets connection. My current hypothesis is that the browser attempts to initiate a WebSocket request via the webpack-dev-server and it basically just sits there - eventually it would timeout and then the SignalR client-side library would transition to trying SSE for communication.

You can enable WebSockets on the webpack-dev-server by updating the proxy config with ```ws: true```:

```js
const { env } = require('process');

const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:37105';

const PROXY_CONFIG = [
  {
    context: [
      "/weatherforecast",
      "/encoder",
      "/encodetext",
      "/encoderhub"
   ],
    target: target,
    secure: false,
    headers: {
      Connection: 'Keep-Alive'
    },
    ws: true
  }
]

module.exports = PROXY_CONFIG;
```

Unfortunately the websocket connection fails (still looking into this) ... but it fails fast back to SSE which should get things moving for you. I'll post back here if I figure out how to get actual websockets working via the proxy. I did find this related issue which might be useful.

https://github.com/dotnet/aspnetcore/issues/35155

**Comment by mitchdenny** [comment]
@le0maxx I think I've got this working. It seems that the webpack-dev-server didn't like the way the config was set up for WSS purposes. I changed the structure of the `PROXY_CONFIG` object to this:

```js
const PROXY_CONFIG = {
  '/weatherforecast': {
    target: target,
    secure: false
  },
  '/chatHub/negotiate': {
    target: target,
    secure: false
  },
  '/chatHub': {
    target: "wss://localhost:7056", // This is from my local environment, yours will be different.
    secure: false,
    ws: true
  }
}
```

Hope this helps.

**Comment by le0maxx** [comment]
Hi

It works now. Thank you so much :)
