### ISSUE TITLE
Documentation problem and/or API problem

### ISSUE THREAD

**Issue by EricOuellet2** [dotnet/aspnetcore#47749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, first it seems the current version is a remake of an older version. It appears to me really confusing for many peoples including me. 
I read [https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0) many times but I can't figure out 2 things:
- How to get my MyHub or an IHubContex<MyHub> from anywhere in code. The sample require a context but nowhere it is mentionned where does it came from. There is no complete sample, nowhere.
- How to send specific notification to specific client when we can't iterate clients?

I also have some other questions (lot less important):
- At the same time, why there is client and connection? What is the differences between the 2?
- How to be notify when there a connection is lost (closed, abandonned, etc)?

### Expected Behavior

- being able to get a hub very easily from anywhere in code?
- being able to send specific notification to specific client (re: iterate client with their specific identification)?

### Steps To Reproduce

None. I'm totally enable to find how to do that, either in the documentation.

### .NET Version

7.0.202

**Comment by BrennanConroy** [comment]
> How to get my MyHub or an IHubContex from anywhere in code. The sample require a context but nowhere it is mentionned where does it came from. There is no complete sample, nowhere.

The sample is linked at the very top of the page [View or download sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/signalr/hubcontext/sample/)

The docs mention exactly where and how to get `IHubContext`.
> In ASP.NET Core SignalR, you can access an instance of IHubContext via dependency injection.

They then show how to get it in a Controller or via Middleware as examples:
```c#
public class HomeController : Controller
{
    private readonly IHubContext<NotificationHub> _hubContext;

    public HomeController(IHubContext<NotificationHub> hubContext)
    {
        _hubContext = hubContext;
    }
}
```

```c#
app.Use(async (context, next) =>
{
    var hubContext = context.RequestServices
                            .GetRequiredService<IHubContext<ChatHub>>();
    //...
    
    if (next != null)
    {
        await next.Invoke();
    }
});
```

-------

> being able to get a hub very easily from anywhere in code?

You cannot get a `Hub` in your code, the `Hub` is closely controlled by SignalR and is only used when a client invokes a method on the server. You're supposed to get `IHubContext<YourHub>` if you want to interact with the client in arbitrary code.

> being able to send specific notification to specific client (re: iterate client with their specific identification)?

You can send to a specific client via `IHubContext<YourHub>.Clients.Client("id").SendAsync("method", args);`

**Comment by EricOuellet2** [comment]
@BrennanConroy, thanks for your answer. Most of it, 95% is already in the documentation and I read it many times. But you add one great thing : You can **send to a specific client via IHubContext<YourHub>.Clients.Client("id").SendAsync("method", args);**. That help. Reagrding the rest, when you sample code (from the doc) require a "context" to get an IHubContext but you don't say how to get the context, it's like having no answer because we can't go further. The documentation seems incomplete to me. Also, how can we iterate all Clients? The Hub infrastructure (framework) should have that information but seems to hide it to the programmer, how to get a list of all connections(clients - are they the same)?

**Comment by EricOuellet2** [comment]
Also, the sample does not answer any of my questions.

**Comment by BrennanConroy** [comment]
> require a "context" to get an IHubContext but you don't say how to get the context

I think you're missing a fundamental concept. [DI (Dependency Injection)](https://learn.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0) is how most services are resolved in ASP.NET Core. Including how `IHubContext<THub>` is resolved. It can look like magic, but is very useful once you understand it.

> Also, how can we iterate all Clients?

You can't. Why do you need this? If you want to send to all clients you can use `IHubContext.Clients.All.SendAsync("method", args);`. If you want to [send to a group of clients](https://learn.microsoft.com/aspnet/core/signalr/groups?view=aspnetcore-7.0) use `IHubContext.Clients.Group("groupName").SendAsync("method", args);`, assuming you've already added client(s) to the group.

**Comment by wadepickett** [comment]
Related doc issue created:  dotnet/AspNetCore.Docs#29045

The following is a topic that currently defines Client and Connection which will be reviewed to see if it needs an update and review how to make that information best discoverable:

[Training > What is ASP.NET Core SignalR?](https://learn.microsoft.com/en-us/training/modules/aspnet-core-signalr/2-what-is-signalr)

**Comment by EricOuellet2** [comment]
Why having a Hub<T> if we can't call it from anywhere in code? Why this huge constraint? Why the IHubContext  is templated to a Hub when we can't use that Hub? How to get IHubContext from anywhere in the code? Did I miss something?
