### ISSUE TITLE
Blazor: Apply Theme from Local Storage or User Storage will Meet Flicker

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspnetcore#47746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

```razor
//MainLayout
@using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage
@inherits LayoutComponentBase
@inject ProtectedLocalStorage ProtectedLocalStorage

<CascadingValue Value="@_theme">
    @Body
</CascadingValue>

@code {
    //default theme
    private const string _defaultTheme = "black";
    //another is white
    private string _theme = "black";

    protected override async Task OnInitializedAsync()
    {
        //Render!!!
        ProtectedBrowserStorageResult<string> result = await ProtectedLocalStorage.GetAsync<string>("UserThemeSetting");
    //Simulate get white situation
        if (result.Success is false)
        {
            _theme = "orange";
        }
    }
    //Render!!!
}

//Page
@page "/"

<div style="Height: 100vh; width: 100vw; background-color: @Theme"></div>

@code
{
    [CascadingParameter]
    public string? Theme { get; set; }
}
```
The render mode of the above code is `Server`. So we can get access to `ProtectedLocalStorage` within `OnInitializedAsync`.

The code simulates the situation where the default theme is different from the user's preference. The default is black, while user's is white. **_When we need to get the user preference from an asynchronous task, it will cause two times of render (see comments which mark the render timing). And the first uses the default black, the second uses the white, which causes a flicker_**. Another similar scenario is asynchronous data load which is described in the [Official Doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&pivots=server#persist-prerendered-state).

Hope I'm not wrong, the above two scenarios are not all the same. Theme one may load different data, while data one needs to load the same data as the first-time load. So, the Theme one can't use `Persist Prerendered State` solution described in doc.

`ServerPrerendered` mode has the same problem , which needs a little code change. Move the access to `ProtectedLocalStorage` into `OnAfterRenderAsync`. This seems more reasonable since the theme is updated **AfterRender**. 

```razor
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        _isDarkMode = await _mudThemeProvider!.GetSystemPreference();
        StateHasChanged();
    }
}
```

`WASM` application does have the same behavior. I've explored the related issues such as #42561, #45131. I'm not quit sure if they are related. I also saw a comment which suggested to implement myself `IComponent`, to control render behavior for asynchronous initialized. But I haven't tried, since I don't think I have to do in such advanced way.

The temporary way I use is just to provide the default(dark) theme for users, which does not need to load settings.

### Describe the solution you'd like

Please provide the right way if I'm doing wrong. Or make me confirm this is a feature or defect.

The expectation is there is no flicker when loading the page when meeting the similar scenario.

**Comment by javiercn** [comment]
@Kumima thanks for contacting us.

PersistedComponentState is the way to do this. See [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-7.0#persist-state-for-prerendered-components) for details.

If you need to remember the session between sessions, then the recommendation is to either use a cookie or some server-side storage.

**Comment by Kumima** [comment]
@javiercn Thanks for quick response.

It does fulfill part of the requirement. But I still can't retrieve user preference from `LocalStorage` right? When prerendering, LocalStorage is not available within `OnInitializeAsync`. So, I have to use another storage, like database for user?
