### ISSUE TITLE
How do I get the Vite dev server to work with the Azure AD authentication?

### ISSUE THREAD

**Issue by mrakgr** [dotnet/aspnetcore#47763]
Link: https://github.com/vitejs/vite/discussions/12898

My work is completely stuck until I can get through this challenge, so I am posting it here as well for visibility.

**Comment by blowdart** [comment]
That would be a question for the AAD folks, rather than us. 

Their javascript library (as it seems you're doing this within react) is [here](https://github.com/AzureAD/microsoft-authentication-library-for-js)

**Comment by mrakgr** [comment]
No, actually, I am sending a challenge request to the user from the server. [See here.](https://github.com/mrakgr/MIP-And-Giraffe/blob/971316550953cc5f76fd93d140b7119782a58d58/SAFE%20Stack%20Login/src/Server/Server.fs#L70).

The two problems that I have is that it is getting blocked (when using Vite dev server) and that it is using the wrong return URI (also only when using the Vite dev server.) The later problem will definitely require resolving on the .NET side.

**Comment by mrakgr** [comment]
Passing the redirect URI into challenge async doesn't actually seem to have any effect.

**Comment by mrakgr** [comment]
In production mode, the client files get served from the `public` folder so they are on the same domain (on port 5000) and everything works.

In dev mode, I have the client Vite server on port 8080 and it is proxying the requests to the server which is on port 5000. When I do a challenge async, the redirect URI has the server port which is 5000 instead of 8080. That is the second issue that I'll have to resolve on the .NET side somehow.

The first problem is that the redirect to the Azure AD login gets blocked by the browser. It says it is a CORS error in the console, but the redirect doesn't work even with the Chrome browser security turned off, so I am not sure about that.

**Comment by mrakgr** [comment]
Basically, in dev mode I have two projects, client and server that are run on two separate processes. The client is run on the Vite server, and this is good as it has hot module reloading and doesn't take 30s to compile. When I build it in production, it puts the server into the `deploy` folder and the client into `deploy/public` so it gets served as static files.

**Comment by blowdart** [comment]
Ah there's a proxy in the way.

Ok that one at least I can answer, if the Vite Server is well behaved and is passing the X- headers proxies to then [wiring up the forwarded headers middleware](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0) will take of that.

Turning chrome security off won't affect CORS afaik. If the login is via server side redirect CORS shouldn't come into it, but if you're doing it browser side, then the AAD js client is probably the better way to go, but you'll need to ask them about.

**Comment by mrakgr** [comment]
I see. I'll study it and try to get it to work tomorrow. Thank you.

**Comment by blowdart** [comment]
If you don't let us know, we'll try to help further

**Comment by mrakgr** [comment]
No, unfortunately there aren't any X- headers in the request.

![Screenshot (174)](https://user-images.githubusercontent.com/6266635/233004079-28e5b62e-0f06-4bf0-9d59-6febccbd2c9f.png)

Any ideas what I could try out next? Also, I really want to understand why redirection isn't working when going through the Vite proxy server, but I have no leads on where to look.

**Comment by mrakgr** [comment]
Actually, there is a `x-remoting-proxy` field in header. Can anything be done using it?

**Comment by mrakgr** [comment]
https://ruslan.rocks/posts/vite-proxy-how-to-setup

I just found this and there are a whole bunch of options like...

> xfwd: true/false, adds x-forward headers
> autoRewrite: rewrites the location host/port on (201/301/302/307/308) redirects based on requested host/port. Default: false.
> followRedirects: true/false, Default: false - specify whether you want to follow redirects

It wasn't in the main Vite docs so I missed it.

**Comment by javiercn** [comment]
@mrakgr have you configured the vite proxy to forward the appropriate data to ASP.NET Core?

See [here](https://vitejs.dev/config/server-options.html#server-proxy)

**Comment by mrakgr** [comment]
Yes. It works unless the response tries to redirect it.

![Screenshot (177)](https://user-images.githubusercontent.com/6266635/233029103-d536c8d8-a026-446b-b499-337c1289bedf.png)

**Comment by javiercn** [comment]
@mrakgr why is your request method options in the last screenshot.

Are you doing the challenge on the server, from an endpoint that is called from an API?

**Comment by mrakgr** [comment]
Yes. See that challenge async in middle.

![Screenshot (178)](https://user-images.githubusercontent.com/6266635/233037792-101323a8-db68-4497-964d-0d83b42d4482.png)

**Comment by javiercn** [comment]
@mrakgr thanks for the additional details.

You can't do the challenge as a response to an API call from the server. You need to start the navigation from the browser.

If you are using `fetch` redirects are opaque, to the browser, at most you can ask `fetch not to follow the redirects, but I believe you can't extract the response yourself.

The problem I don't think is in your proxy/server code, but in the way you are triggering the flow from an API request.

**Comment by mrakgr** [comment]
Most likely `Fable.Remoting` is using fetch under the hood. I do not understand why it would be opaque, it does show up in the Networks tab. Also it does work on production mode when the frontend and the backend are on the same domain.

But I do believe you when you say it can't be done. What should I do here?

Can I have the server send the URL somehow as a string, and have the backend redirect to it manually? I think that would be as far as I'd want to go, I do not want to implement anything complicated just for the dev server.

A workaround that I've found is to double click on the request on the networks tab. That will have the browser go to the Azure AD login and give me back a cookie on the original domain.

**Comment by mrakgr** [comment]
Would moving all of the authentication to the client work? If I authenticated the user using the [AAD library](https://github.com/AzureAD/microsoft-authentication-library-for-js), would the cookie be valid with the server which is using `Microsoft.Identity.Web`?

**Comment by mrakgr** [comment]
Here is [the video](https://youtu.be/lNYZi9v9QoA) I made. I'll try to get authentication to work directly on the client for my next one, so I'll close this here. If it is actually possible to make the redirects work with the Vite server, somebody please inform me, but otherwise I'll go with the assumption that they can't be done.
