### ISSUE TITLE
Unable to restore on Windows

### ISSUE THREAD

**Issue by jaredpar** [dotnet/aspnetcore#47781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running restore.cmd I get the following errors: 

> 
C:\Users\jaredpar\code\aspnetcore\src\Servers\IIS\build\Build.Common.Settings(12,3): error MSB4019: The imported proje
ct "C:\Users\jaredpar\code\aspnetcore\.tools\msbuild\17.1.0\tools\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.prop
s" was not found. Confirm that the expression in the Import declaration "C:\Users\jaredpar\code\aspnetcore\.tools\msbu
ild\17.1.0\tools\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
 [C:\Users\jaredpar\code\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]

Ther are roughly ~5 instances of this. All the same error for a variety of .vcxproj. I checked my Visual Studio installations to ensure they had the C++ workload installed but that did not fix the issue. 

How can I fix this? 

### Expected Behavior

I can restore

### Steps To Reproduce

Clone on Windows and run `restore.cmd`.

**Comment by danmoseley** [comment]
the path above btw should be `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props" ... so the question is why `$(VCTargetsPath)` is not set there .. and how that is set is quite convoluted. Better to just update VS as suggested.

**Comment by jaredpar** [comment]
Yep once I got `InstallVisualStudio.ps1` to run that fixed my restore error.

Note: make sure you close all existing VS installers before running that script.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/issues/47783 to track improving the script for this scenario
