### ISSUE TITLE
Write Windows RIO transport

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#4780]

**Comment by samsosa** [comment]
From [here](https://github.com/dotnet/runtime/issues/14101#issuecomment-611905387).

@nxrighthere:
> It's really sad that this API is not available in .NET today for UDP. If you need a high-performance UDP implementation that can be easily wrapped in C#, see [RioSockets](https://github.com/nxrighthere/RioSockets), it's a single-header C library.
> 
> We achieved [1 Gbps throughput](https://i.imgur.com/GOfYaSg.png) (don't have a faster NIC for tests) without any external effort transmitting up to [1.142 million packets per second](https://i.imgur.com/x3DxSHB.png) from Netherlands to Germany and vise versa.

Maybe RIO is valuable for the upcoming UDP based QUIC protocol?

**Comment by sgf** [comment]
> Might be able to use https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines.Networking.Windows.RIO as a starting point.
> 
> Is the plan to have it all internal to kestrel or to share the rio implementation for "just" pipelines?

the link is 404

**Comment by davidfowl** [comment]
Not happening
