### ISSUE TITLE
Allow to define variable within Virtualize component

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#47818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Let's consider this code:
```csharp
<Virtualize Items="Data" Context="item">
    <tr>
        <td>@item.Id</td>
        <td>@item.GetLocalization(CultureInfo.CurrentCulture).Name</td>
        <td>@item.GetLocalization(CultureInfo.CurrentCulture).Description</td>
        <td class="text-right">
            <span class="aktion-icon" role="button" @onclick="async () => await EditAsync(item)">
                <i class="fa-solid fa-pen-to-square"></i>
            </span>
        </td>
    </tr>
</Virtualize>
```

As you can see I'm calling the method `.GetLocalization()` twice to display both name and description. I want do this only once. To save some performance. However, I cannot define `var description = item.GetLocalization(CultureInfo.CurrentCulture);` within the `Virtualize` component.

As a workaround I can do something like this:

```csharp
<Virtualize Items="Data" Context="item">
    @if (true)
    {
        var description = item.GetLocalization(CultureInfo.CurrentCulture);

        <tr>
            <td>@item.Id</td>
            <td>@description.Name</td>
            <td>@description.Description</td>
            <td class="text-right">
                <span class="aktion-icon" role="button" @onclick="async () => await EditAsync(item)">
                    <i class="fa-solid fa-pen-to-square"></i>
                </span>
            </td>
        </tr>
    }
</Virtualize>
```

Defining a `@code` block within the `Virtualize` component does not work.

### Describe the solution you'd like

It should be possible to do this with `@code` or some kind of `@` block besides `@if`

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

Does it not work to do 
```
@{
    var description = item.GetLocalization(CultureInfo.CurrentCulture);
}
```

**Comment by MarvinKlein1508** [comment]
@javiercn 😵 yes this works. I wasn't aware of the `@{}` syntax even existing. Never needed it before. Thanks for your help!
