### ISSUE TITLE
Older versions of nuget packages for Blazor Webassembly hosted project 

### ISSUE THREAD

**Issue by strada360** [dotnet/aspnetcore#47823]
When creating a new Blazor Webassembly application with authentication.  The nuget package for Microsoft.Identity.Web and Microsoft.Identify.Web.UI  added with version 1.16.0 when the current version stands at 2.7.0. 

Any reasons for being that far behind? 

To replicate the issue: 

`dotnet new blazorwasm -au SingleOrg -ho --pwa -o testapp`

Check the testapp.Server.csproj  file, following references added.

`<PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="1.16.0" />`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@wtgodbe can you please look into this and see if we have mistakenly hardcoded the version in the project? Thanks!

**Comment by mkArtakMSFT** [comment]
@halter73 just confirmed that it's properly versioned and wired up in versions.props but the version was never updated.

We should update the version.
