### ISSUE TITLE
Make ProblemDetailsDefaults public

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/aspnetcore#47822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create ProblemDetails, e.g.ValidationProblemDetails outside of a normal Http Request.
The rather nice default values, e.g.Type String, which is according to the RFC the correct way to identify it, are applied via 
https://github.com/dotnet/aspnetcore/blob/900660b60c3816c10e1094b7d0587dc110c6b9be/src/Shared/ProblemDetails/ProblemDetailsDefaults.cs#L110-L115

Unfortunately the type is not public, but internal.

### Describe the solution you'd like

It would be rather useful, as ProblemDetails is public, to make that one public too, so I don't need to copy the logic around.

### Additional context

Alternatively a new method could be added to ``IProblemDetailsService`` to allow access to the defaults.

**Comment by halter73** [comment]
@Tornhoof @campbellwray would either of you be interested in filling out an [API proposal for this](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=)? You can file a new issue or just use the template in a new comment here. We could make the proposal just to make the internal type public. e.g.

```diff
// Microsoft.AspNetCore.Http.Extensions.dll (ProblemDetailsDefaults is currently in multiple assemblies, but they all depend on Http.Extensions)

namespace Microsoft.AspNetCore.Http;
 
+ public static class ProblemDetailsDefaults
+ {
+     public static void Apply(ProblemDetails problemDetails, int? statusCode);
+ }
```

I'm not sure `Apply` is a descriptive enough name though. Maybe we could just add a method directly to `ProblemDetails`.

```diff
// Microsoft.AspNetCore.Http.Abstractions.dll

namespace Microsoft.AspNetCore.Mvc;
 
public class ProblemDetails
{
+     public static void ApplyStatusCodeDefaults(int? statusCode);
}
```

**Comment by Tornhoof** [comment]
Yeah, I will do so.

**Comment by Tornhoof** [comment]
I'll close this in favor of #47978
