### ISSUE TITLE
Kestrel connection metrics - add protocol and TLS info?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#47831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Kestrel has a `connection-duration` counter. Today it just records the local endpoint as a dimension.

### Describe the solution you'd like

`connection-duration` could add additional information that is negotiated after the connection starts.

For example, the connection's:
* HTTP protocol (HTTP/1.1, HTTP/2, HTTP/3)
* TLS protocol (Tls10, Tls11, Tls12, Tls13)

Is this valuable?

**Comment by gfoidl** [comment]
For me:
HTTP protocol: yes
TLS protocol: not needed

Also need to consider that the curse of dimensionality doesn't start to account 😉.

**Comment by amcasey** [comment]
How is the data structured?  Is there a side table for tracking metadata about each endpoint or does everything go on every event?
