### ISSUE TITLE
Dev cert issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#47834]
.Net 8 preview 3 - Windows 11 x64

I just tried Asp Net 8 preview 3 and I get an issue with dev cert.
Edge doesn't want to use the cert.

I tried 
```
dotnet dev-certs https --clean
```
then
```
dotnet dev-certs https --trust
```

the issue remains.

![image](https://user-images.githubusercontent.com/23618436/233775260-c66c873f-205c-444e-9d3f-4bb190afa8c3.png)

.Net 7 projects works fine with the same certificate and the same browser

**Comment by adityamandaleeka** [comment]
cc @amcasey

**Comment by amcasey** [comment]
@Julien-Marpault Thanks for the report!  Are you able to share the non-working cert?  Failing that, how did you create the project that you're running and how did you create the cert?
