### ISSUE TITLE
Add TryAddPolicyRegistry extension methods for IPolicyRegistry

### ISSUE THREAD

**Issue by Arclight3** [dotnet/aspnetcore#47842]
## Background and Motivation
The existing ```AddPolicyRegistry()``` extension methods are registering the ```IPolicyRegistry``` as singleton to the ```IServiceCollection```. Any subsequent invocation of ```AddPolicyRegistry()``` will replace the already registered instance.

The goal of the proposed extension methods: ```TryAddPolicyRegistry()``` is to make sure the ```IPolicyRegistry``` is registered only once.
Any subsequent attempt to add it to DI will not replace the already registered instance. With this idempotent API it will be a bit easier to add policies to the same policy registry. The client code will still have to get the current instance from the ```IServiceCollection``` or create a new instance, but after that will be able to safely attempt to add it back to ```IServiceCollection```.

## Proposed API

The proposal is to add "TryAdd" alternatives to the existing ```AddPolicyRegistry``` APIs.
The implementation logic should not be changed, except for the usage of ```TryAddSingleton``` instead of ```AddSingleton```.

```diff
namespace Microsoft.Extensions.DependencyInjection;

public static class PollyServiceCollectionExtensions
{
+    public static IPolicyRegistry<string> TryAddPolicyRegistry(this IServiceCollection services);
+    public static IPolicyRegistry<string> TryAddPolicyRegistry(this IServiceCollection services, IPolicyRegistry<string> registry);
+    public static IServiceCollection TryAddPolicyRegistry(this IServiceCollection services, Action<IServiceProvider, IPolicyRegistry<string>> configureRegistry);
}
```

## Usage Examples

We have a client code method that registers HTTP clients in the ```IServiceCollection```:
```C#
public static IHttpClientBuilder AddHttpClientWithFaultHandling<TInterface, TImplementation>(this IServiceCollection services);
```
This method adds a set of policies (fallback, wait and retry, circuit breaker, timeout, logging, etc.) to the newly registered HTTP client.
This method will potentially be invoked multiple times in an application (once per HTTP client type).

The circuit breaker policy is tricky. It needs to be put in a ```PolicyRegistry```. Therefore the client code gets an instance of the ```PolicyRegistry``` from the ```IServiceCollection``` if it was already registered, or it creates a new instance:
```C#
private static IConcurrentPolicyRegistry<string> GetExistingOrNewPolicyRegistry(IServiceCollection services) =>
        services.BuildServiceProvider().GetService<IConcurrentPolicyRegistry<string>>() ?? new PolicyRegistry();
```

After getting the ```PolicyRegistry``` instance, this client code adds a new instance of the circuit breaker policy into the Policy Registry. It is assumed that each circuit breaker policy is different per HTTP client registration, therefore it can't be reused.
```C#
policyRegistry.AddOrUpdate($"{typeof(TImplementation).FullName}__CircuitBreakerPolicy", circuitBreakerPolicy, (x, y) => circuitBreakerPolicy);
```

With the help of the proposed APIs, the client code safely tries to add the ```PolicyRegistry``` to the ```IServiceCollection```. It should only be added on the 1st invocation. All subsequent invocations should recognize that the ```PolicyRegistry``` singleton is already registered and skip the action.

After the HTTP client is registered, the client code chains a set of policies to it. The circuit breaker policy is added using the ```AddPolicyHandlerFromRegistry``` method:
```C#
.AddPolicyHandlerFromRegistry($"{typeof(TImplementation).FullName}__CircuitBreakerPolicy")
```

**Comment by bhehe** [comment]
This is exactly what I just ran into and was looking for a version of a 'TryAddPolicyRegistry'.

We build our own internal NuGet packages where we usually attempt to provide a single DI helper method to register things and in this case, that would include the specific policies this sub-component/package uses.  

When I tweaked my test harness to mimic what would happen if 2 different packages/sub-components were to attempt to handle the policy registration as part of their main DI helper methods - I ran in to the scenario described here where previously registered policies are lost.

**Comment by halter73** [comment]
API Review Notes:

- Let's make the existing non-`Try` `AddPolicyRegistry` extension methods use `TryAdd` or `TryAddEnumerable` for the services where it makes sense to do so. We don't have `TryAddMvc`, yet `AddMvc` `TryAdd`'s many things.
- This could technically be a breaking change, but all bug fixes are. If we think there's a high chance of breakage, we could consider new API, but we'd prefer not to make any API changes and just do the right thing.

API rejected, but we like using `TryAdd` and `TryAddEnumerable` in the existing methods.
