### ISSUE TITLE
SignalR android SDK add option to turn off the logs

### ISSUE THREAD

**Issue by cliffgr** [dotnet/aspnetcore#47850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello ,

I am wondering if we could disable the logging that are printed in our logcat.  A possible solution is to add a flag "isDebuggable" in case that I want to disable it on production mode or enabled again on debug mode while i am developing new features.

### Describe the solution you'd like

Based on Documentation in java you are using builder pattern to initialize HubConnection . So,

```
HubConnection hubConnection = HubConnectionBuilder
                  .create(input).isDebuggable(true)
                  .build();
```

**Comment by BrennanConroy** [comment]
SignalR uses slf4j which, depending on your app setup/infrastructure, should be configurable to disable logging entirely, or per category.

By default slf4j should be using a noop logger unless you added something to your app. So you've likely added logging and just need to configure it.
