### ISSUE TITLE
API Proposal RoutingStateProvider; RouteData breaking change

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/aspnetcore#47854]
## Background and Motivation

As part of Blazor United we want to make Static, Server, and Webassembly app models similar to each other. As part of that, Blazor United will always render the root component you specify in `MapRazorComponents<App>()`. Your `App` component needs to have a `Router` component to ensure the appropriate page is rendered. 

For static rendering we want to add a scoped service `RoutingStateProvider` that holds `RouteData` from httpContext. With this `RouteData` we already know what page to render. This way we will avoid routing twice in `Router` component. The `Router` component will check `RouteData` to render the appropriate page.

```csharp
namespace Microsoft.AspNetCore.Components.Routing;

public class RoutingStateProvider
{
    public virtual RouteData? RouteData { get; }
}
```

We also want to change [RouteData](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/RouteData.cs). 

```diff
public sealed class RouteData
{
-   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object> routeValues) {}
+   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object?> routeValues) {}

    [DynamicallyAccessedMembers(Component)]
    public Type PageType { get; }

-    public IReadOnlyDictionary<string, object> RouteValues { get; }
+   public IReadOnlyDictionary<string, object?> RouteValues { get; }
}
```
The reason for this is when creating `RouteData` for `routeValues` parameter we provide `httpContext.GetRouteData().Values` of type `RouteValueDictionary :  IReadOnlyDictionary<string, object?>`. There is [CS8620](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8620)).

## Proposed API

```csharp
namespace Microsoft.AspNetCore.Components.Routing;

public class RoutingStateProvider
{
    public virtual RouteData? RouteData { get; }
}
```

```diff
public sealed class RouteData
{
-   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object> routeValues) {}
+   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object?> routeValues) {}

    [DynamicallyAccessedMembers(Component)]
    public Type PageType { get; }

-    public IReadOnlyDictionary<string, object> RouteValues { get; }
+   public IReadOnlyDictionary<string, object?> RouteValues { get; }
}
```

## Usage Examples

`Router` component will check if `RoutingStateProvider` `RouteData` is not null and render the page. If it is null then it will work as usual (try to match current url to a page and then render that page).

```csharp
if (RoutingStateProvider.RouteData != null)
{
     _renderHandle.Render(Found(RoutingStateProvider.RouteData));
     return;
}
```

RouteData

```csharp
new RouteData(componentType, httpContext.GetRouteData().Values)
```

## Alternative Designs

Suppress CS8620.

**Comment by halter73** [comment]
API Review Notes:

- Is `RouteData.RouteValues` currently populated from `HttpContext.GetRouteData()`?
  - No.  This means that there could theoretically be conflicts with existing keys and new ones added from the HttpContext. We think that the routevalues from endpoint routing will end up matching what the components logic had before. This is just removing duplication.
- Where is `RoutingStateProvider` exposed?
  - It's injected into the component with code like `[Inject] private RoutingStateProvider RoutingStateProvider { get; set; }`
  - It will be a scoped service.
- Will `Microsoft.AspNetCore.Components.Routing` be the namespace for `RoutingStateProvider`? Yes.

```diff
+ namespace Microsoft.AspNetCore.Components.Routing;
+
+ public class RoutingStateProvider
+ {
+    public virtual RouteData? RouteData { get; }
+ }

public sealed class RouteData
{
-   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object> routeValues) {}
+   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object?> routeValues) {}

    [DynamicallyAccessedMembers(Component)]
    public Type PageType { get; }

-    public IReadOnlyDictionary<string, object> RouteValues { get; }
+   public IReadOnlyDictionary<string, object?> RouteValues { get; }
}
```


This API looks good as proposed. We should ask blazor experts if this warrants breaking change announcements.

**Comment by surayya-MS** [comment]
Thanks @halter73 for the review! As we discussed, I'm changing the API. It will be interface `IRoutingStateProvider` instead of class `RoutingStateProvider`.

Also I'm including `RootComponentMetadata`.

```diff
+ namespace Microsoft.AspNetCore.Components.Routing;
+
+ public class RoutingStateProvider
+ {
+    public virtual RouteData? RouteData { get; }
+ }

public sealed class RouteData
{
-   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object> routeValues) {}
+   public RouteData([DynamicallyAccessedMembers(Component)] Type pageType, IReadOnlyDictionary<string, object?> routeValues) {}

    [DynamicallyAccessedMembers(Component)]
    public Type PageType { get; }

-    public IReadOnlyDictionary<string, object> RouteValues { get; }
+   public IReadOnlyDictionary<string, object?> RouteValues { get; }
}


+  namespace Microsoft.AspNetCore.Builder;

+  public class RootComponentMetadata
+  {
+      public RootComponentMetadata(Type rootComponentType)
+      { }
+  
+      public Type Type { get; }
+  }
```

**Comment by halter73** [comment]
Reopening for API review.

Thanks for the updated proposal. Can you update the latest comment to show `interface IRoutingStateProvider` instead of `class RoutingStateProvider`? It looks like there was a copy-paste issue. 

Can you also provide usage examples for `RootComponentMetadata` since that's new?

I also wonder if we should put `RootComponentMetadata` in the `Microsoft.AspNetCore.Components.Endpoints` rather than the `Microsoft.AspNetCore.Builder` namespace. `Microsoft.AspNetCore.Builder` is consistent with `ComponentTypeMetadata`, but I'm not sure this type will be commonly used enough to warrant including in a namespace that's a default global using.

**Comment by surayya-MS** [comment]
Thanks @halter73 ! Yes, that was a copy-paste issue.

`RootComponentMetadata` should be in the same namespace as `ComponentTypeMetadata`. @javiercn , please correct me if I'm mistaken.

**Comment by halter73** [comment]
API Review Notes for `RootComponentMetadata` (we already approved the rest of the proposal):

- This helps distinguish between multiple invocations of `MapRazorComponents<TRootComponent>()` where `RootComponentMetata.Type` is `typeof(TRootComponent)`.
- Typical users would read it via `httpContext.GetEndpoint().Metadata.Get<RootComponentMetata>()`.
- What do we think about the `Microsoft.AspNetCore.Builder` namespace?
  - It seems to niche to be in a default global using namespace.
  - It does match `ComponentTypeMetadata`, but that's also new in .NET 8 and can be moved.
  - `Microsoft.AspNetCore.Components.Endpoints`. It's a new dll, but the namespace has already been used for some stuff: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.endpoints?view=aspnetcore-8.0

API Approved! Make sure we update the namespace for both `RootComponentMetadata` and `RootComponentMetadata`.

```diff
- namespace Microsoft.AspNetCore.Builder;
+ namespace Microsoft.AspNetCore.Components.Endpoints;

public class ComponentTypeMetadata
{
    public ComponentTypeMetadata(Type componentType);
    public Type Type { get; }
}

+  public class RootComponentMetadata
+  {
+      public RootComponentMetadata(Type rootComponentType);
+      public Type Type { get; }
+  }
```
