### ISSUE TITLE
Should AllowedHosts be in the template appsettings.json?

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#47862]
By default the appsettings.json file in the templates have `"AllowedHosts": "*"`.

From everything I can tell from the code, this appears to be used for "host filtering":

https://github.com/dotnet/aspnetcore/blob/d07f377b6c4c72f44a0eb2810c8abf1ae3fabd40/src/DefaultBuilder/src/WebHost.cs#L253-L268

https://github.com/dotnet/aspnetcore/blob/d07f377b6c4c72f44a0eb2810c8abf1ae3fabd40/src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs#L63-L70

However, as you can see above the default value, if not configured, is `*`. So there might not be value in putting this configuration value in appsettings for all the templates.

We should consider removing this config value from the templates if it doesn't add value.

See the discussion [here](https://github.com/dotnet/aspnetcore/pull/47797#discussion_r1173099075).

**Comment by Tratcher** [comment]
cc @blowdart 
It was put there for discoverability since it's a setting we encourage users to set.

**Comment by blowdart** [comment]
I said that in a PR :)

It should stay

**Comment by amcasey** [comment]
Any final thoughts, @eerhardt?
