### ISSUE TITLE
[Blazor] SetUpdatesAttributeName

### ISSUE THREAD

**Issue by eyalalonn** [dotnet/aspnetcore#47877]
I'm writing a UI library based on Blazor and I wonder whether I should I call `RenderTreeBuilder.SetUpdatesAttributeName` on custom components? I'm not deriving from `InputBase<TValue>` and have my own abstraction for convenience for all of my components and inputs but I'm not sure I understand what `SetUpdatesAttributeName` does exactly. I'm using .NET 7.

Currently on my `WebInput<TValue>` component I have something like the code below but my question is whether I need to call `SetUpdatesAttributeName("value")` anywhere? I've seen what the compiler generates when using the Razor syntax and it does seems to call it and this is the reason I'm asking.
```csharp
protected override void SetElementAttributes(AttributesBuilder builder)
{
    base.SetElementAttributes(builder);

    builder.Set("type", _type)
            .Set("value", CurrentValueAsString, true)
            .Set("name", Name)
            .Set("form", Form)
            .Set("title", Title)
            .Set("disabled", Disabled)
            .SetEvent("oninvalid", this, InvalidHandler)
            .SetEvent("onactivate", this, ActivateHandler)
            .SetEvent("onbeforeactivate", this, ActivateHandler)
            .SetEvent("ondeactivate", this, DeactivateHandler)
            .SetEvent("onbeforedeactivate", this, DeactivateHandler)
            .SetEvent<FocusEventArgs>("onfocus", this, FocusHandler)
            .SetEvent<FocusEventArgs>("onfocusin", this, FocusHandler)
            .SetEvent<FocusEventArgs>("onfocusout", this, FocusHandler)
            .SetEvent<FocusEventArgs>("onblur", this, BlurHandler);

    if (OnChange.HasDelegate)
    {
        builder.SetEvent<ChangeEventArgs>("onchange", this, ChangeHandler);
    }
    else if (ValueChanged.HasDelegate)
    {
        builder.SetBind("onchange", this, value => CurrentValueAsString = value, CurrentValueAsString ?? "");
    }

    if (OnInput.HasDelegate)
    {
        builder.SetEvent<ChangeEventArgs>("oninput", this, InputHandler);
    }
}
```

**Comment by javiercn** [comment]
@eyalalonn it's for `@bind` support. To keep the DOM in sync.

It's most important in Blazor Server where there might be latency between the user input and the event firing on the server. For example, imagine you have an input value and you type in "hello", but the property you bind to, is set to capitalize all the letters. SetUpdatesEventName makes sure that the right thing happens when multiple updates are queued up simultaeously.

You can give this a try yourself by using an event handler directly and using `@bind` instead to see the differences.

**Comment by javiercn** [comment]
@eyalalonn @bind to DOM elements, since those are the ones that can have state in the browser.
