### ISSUE TITLE
Blazor InputFile component does not work when registering AutofacServiceProviderFactory

### ISSUE THREAD

**Issue by mohanrajsf3477** [dotnet/aspnetcore#47875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

we can't able to upload the file in InputFile component when registering custom dependencies injection AutofacServiceProviderFactory. find the below code on Program.cs file.
`builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());` 

please find the sample code below for your reference.
`
@using System
@using System.IO
@using Microsoft.AspNetCore.Hosting
@using Microsoft.Extensions.Logging

<h3>Upload Files</h3>

<p>
    <label>
        Max file size:
        <input type="number" @bind="maxFileSize" />
    </label>
</p>

<p>
    <label>
        Max allowed files:
        <input type="number" @bind="maxAllowedFiles" />
    </label>
</p>

<p>
    <label>
        Upload up to @maxAllowedFiles of up to @maxFileSize bytes:
        <InputFile OnChange="@LoadFiles" multiple />
    </label>
</p>

@if (isLoading)
{
    <p>Uploading...</p>
}
else
{
    <ul>
        @foreach (var file in loadedFiles)
        {
            <li>
                <ul>
                    <li>Name: @file.Name</li>
                    <li>Last modified: @file.LastModified.ToString()</li>
                    <li>Size (bytes): @file.Size</li>
                    <li>Content type: @file.ContentType</li>
                </ul>
            </li>
        }
    </ul>
}

@code {
    private List<IBrowserFile> loadedFiles = new();
    private long maxFileSize = 1024 * 15;
    private int maxAllowedFiles = 3;
    private bool isLoading;

    private async Task LoadFiles(InputFileChangeEventArgs e)
    {
        isLoading = true;
        loadedFiles.Clear();

        foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
        {
            try
            {
                loadedFiles.Add(file);

                var trustedFileNameForFileStorage = Path.GetRandomFileName();
                var path = @"D:\" + file.Name;

                await using FileStream fs = new(path, FileMode.Create);
                await file.OpenReadStream(maxFileSize).CopyToAsync(fs);
            }
            catch (Exception ex)
            {
                Console.WriteLine("File: {Filename} Error: {Error}",
                    file.Name, ex.Message);
            }
        }

        isLoading = false;
    }
}

`

### Expected Behavior

Need to upload the file successfully.

### Steps To Reproduce

- run the sample with AutofacServiceProviderFactory
- upload the file
- see the issue.

### .NET Version

6 and 7

### Anything else?

can you please provide solution for this issue ?

**Comment by SteveSandersonMS** [comment]
See https://github.com/dotnet/aspnetcore/issues/38842#issuecomment-1342540950

It's possible there are some subtleties I have missed, but at least superficially it seems like this is an issue in Autofac. Overriding the behavior of something as basic as a `byte[]` parameter seems dubious. But if I'm misjudging this and there's something different we should be doing in the framework, please let us know.

I'll close this as an external issue, but could reopen it if anyone has a good justification of this being a framework bug and has a proposal for fixing it.
