### ISSUE TITLE
[Blazor web assembly] On page reload for a deployed app, set environment (environment's appsettings file) not being picked

### ISSUE THREAD

**Issue by kyandaks** [dotnet/aspnetcore#47881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following the setup of multiple environments via startup configuration as specified here in this documentation - https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-7.0#set-the-environment-via-startup-configuration 
Below is the configuration set in the index.html file
```
<script>
        document.addEventListener("DOMContentLoaded", function () {
            if (window.location.hostname.includes("localhost")) {
                Blazor.start(); //ensures that @localhost, the default debugging flow can be used.
            } else if (window.location.hostname.includes("test")) {
                Blazor.start({
                    environment: "Test"
                });
            } else if (window.location.hostname.includes("demo")) {
                Blazor.start({
                    environment: "Demo"
                });
            } else {
                Blazor.start({
                    environment: "Production"
                });
            }
        });
    </script>
```
A standalone wasm app deployed to use an environment like demo works well upon visiting the root domain eg https://example-demo.com. If one navigates to a page like https://example-demo.com/votes, votes page will load as expected. 
Issue arises when you reload the page. Blazor seems to default to using appsetting.Production.json instead of reloading using appsettings.Demo.json 
Strangely this works well for test. 
NB: Deployment is being done by deploying the published assets to object storage or a similar approach to GitHub pages

### Expected Behavior

If on the votes page - https://example-demo.com/votes and you reload, blazor is supposed to use the appsettings.Demo.json

### Steps To Reproduce

Have in place appsettings for development, test, demo, production. Add a the code snippet above mentioned in the describe bug section to your index.html file. while executing dotnet publish command, specify environment name accordingly using /p:EnvironmentName 

### .NET Version

.NET 7

**Comment by kyandaks** [comment]
Hello @mkArtakMSFT 
The appsettings files contain API URLs for the different environments as such most errors are CORs errors. 
But below are some of the logs shown in console:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage , CancellationToken , Nullable`1 )
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage , CancellationToken , Nullable`1 )
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )


ThreadPool Callback threw an unhandled exception of type System.Net.Http.HttpRequestException
blazor.webassembly.js
```

**Comment by javiercn** [comment]
@kyandaks are there any errors loading any framework file, like blazor.boot.json?

**Comment by kyandaks** [comment]
@javiercn 
Currently, there are logs shown but I think we have been able to narrow down a possible explanation.

From our investigations, we have found out that on some environments the script on index.html page is not run when an absolute + relative URL such as example.com/vote is run directly through the browser. However, if you ran example.com in the same environment, this script does run successfully. Same case if one is clicking the routes in the application to go to different pages. 

In another environment, the behaviour is as expected, that is, regardless of the page accessed, the relevant appsettings are set accordingly.

NB: Our deployment approached is the assets from the dotnet publish command are packaged and uploaded to an AWS bucket with static web hosting enabled and these assets are served using AWS CloudFront

**Comment by mkArtakMSFT** [comment]
Can you please answer the question from @javiercn above ?
Also, please share the screenshot of the Network tab in browser dev tools - both for working as well as for non-working scenarios.

**Comment by kyandaks** [comment]
@javiercn @mkArtakMSFT 
blazor.boot.json throws no error logs. 
The only error logs are CORS errors since wrong Base URLs are loaded and these API URLs are defined in appsettings for different environments. 
Below is a screenshot of the network tab in developer tools:
![blazor-error](https://user-images.githubusercontent.com/45067380/234644115-6be6a912-a0bb-4af4-838c-80933c5a02eb.png)

NB: BTW Our experiments with docker as a deployment option have this working well.

**Comment by mkArtakMSFT** [comment]
Can you share the URLs of the two failed requests?

**Comment by kyandaks** [comment]
Hello
We decided to host and deploy the blazor application using Docker.
This approach has proven to be more stable and for the past days, we have not experienced any issues. 

Different issues kept coming up while serving the blazor app using S3 + CloudFront.

**Comment by mkArtakMSFT** [comment]
Sounds good. Closing as there is not enough information for us to investigate this further. Glad that you have found a solution anyway.
