### ISSUE TITLE
IWebHostEnvironment does not return the appropriate physical path when debugging

### ISSUE THREAD

**Issue by ThatMouse** [dotnet/aspnetcore#47909]
IWebHostEnvironment does not return the appropriate physical path when debugging:
WebRootPath = "c:\Dev\MyProject\wwwroot"
ContentRootPath = "c:\Dev\MyProject"

So I'm having to resort to using:
AppDomain.CurrentDomain.BaseDirectory = "c:\Dev\MyProject\bin\Debug\net7.0"

My use case is a Blazor Server .NET 7 app where I have a Razor Class Library that needs to read in a data file.

**Comment by halter73** [comment]
Are you using `WebApplicationBuilder`? The content root path defaults to the CWD, but you can change it using `WebApplicationOptions`.'

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0#change-the-content-root-application-name-and-environment

**Comment by ThatMouse** [comment]
@halter73 Yes I am, but changing the ContentRootPath to "c:\Dev\MyProject\bin\Debug\net7.0" just for debugging would probably not be desirable.

The problem is when debugging in Visual Studio, the root is the bin folder, at least in Blazor. Therefore, the case I'm trying to make is that  IWebHostEnvironment is not correct or not consistent. Blazor may be different as it splits the files between directories to support hot reloading presumably.

When debugging:
IWebHostEnvironment.ContentRootPath = "c:\Dev\MyProject"    (wrong)
AppDomain.CurrentDomain.BaseDirectory = "c:\Dev\MyProject\bin\Debug\net7.0"    (correct)
