### ISSUE TITLE
[Question] How to find problem in our code leading to concurrent usage of HttpContext ?

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/aspnetcore#47900]
I saw that there is an [issue 42040](https://github.com/dotnet/aspnetcore/issues/42040) already for this, but was not able to find some algorithm in the attached issues for finding this concurrent access. We have Azure App service on .NET7 and I can find following exception in AppInsights:
![image](https://user-images.githubusercontent.com/12857389/234540449-d292b9d1-09e4-4cff-bcd0-c2c395f1a649.png)

Looks like the problematic code is here: https://github.com/dotnet/aspnetcore/blob/726f467f4c0d23b40a937edab56430c3861e73b9/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L65

I've checked all our code and we have no background threads which works with HttpContext.
Can you give me some hints how to continue?

**Comment by Tratcher** [comment]
I'd start with the EtwLoggingMiddleware in that call stack. Does it have any un-awaited tasks or background tasks? Does the issue go away if you remove it?

**Comment by Tratcher** [comment]
Also, which type of authentication are you using? There could be an issue with your auth handler.

**Comment by Tratcher** [comment]
I made a tool that might be helpful for detecting these issues. You can try copying this into your project, but I wouldn't recommend pushing it to production 😁. 
https://github.com/Tratcher/ConcurrencyAlert/blob/315c3e714691c2b6531e70078295cfe8a25dffb8/ConcurrencyAlert/Program.cs#L5

**Comment by TrayanZapryanov** [comment]
> I'd start with the EtwLoggingMiddleware in that call stack. Does it have any un-awaited tasks or background tasks? Does the issue go away if you remove it?

This is quite old code. Here it is almost real version. It works since several years(in .NET6).
`public class EtwLoggingMiddleware
	{
		private readonly RequestDelegate _next;
		private readonly ILogger<EtwLoggingMiddleware> _logger;

		public EtwLoggingMiddleware(RequestDelegate next, ILogger<EtwLoggingMiddleware> logger)
		{
			_next = next;
			_logger = logger;
		}

		public async Task InvokeAsync(HttpContext context)
		{
			context.Items["ContextId"] = 123;

			try
			{
				await _next(context).ConfigureAwait(true); //true as all MS samples are without ConfigureAwait.
			}
			catch (CustomException xxxx)
			{
				try
				{
					context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
					var responseFeature = context.Features.Get<IHttpResponseFeature>();
					if (responseFeature != null)
						responseFeature.ReasonPhrase = xxxx.Message;
				}
				catch (Exception e)
				{
					_logger.LogError(e, "Exception while modifying response!");
					throw xxxx;
				}
			}
		}
	}`

**Comment by TrayanZapryanov** [comment]
> 

**There is something new in the code connected with authentication and this might be the key for the problem.
I have to support 3 different authentication schemas and here it is an example of how I am doing it. It is almost 100 % like the code in production:**
`
var builder = services
				.AddAuthentication(options =>
				{
					options.DefaultScheme = "JWT_OR_COOKIE_OR_PERMANENT_LINK";
					options.DefaultChallengeScheme = "JWT_OR_COOKIE_OR_PERMANENT_LINK";
				});
//JWT
builder.AddJwtBearer(options =>
			{
				options.Authority = XXX;
				//options.Audience = "docuware.workflow.service";
				options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
				{
					ValidateIssuer = true,
					ValidAudiences = new List<string>
					{
						"XXX"
					},
					IssuerValidator = XXX
				};
				options.RequireHttpsMetadata = true;
				options.IncludeErrorDetails = true;
			});
//Forms
builder.AddCookie(FormsDefaults.FormsScheme, options =>
			{
				options.Cookie.Name = XXX;
				options.AccessDeniedPath = "/Login/";
				options.LoginPath = "/Login/";
				options.ReturnUrlParameter = "returnurl";
				options.SlidingExpiration = false;

				options.Events.OnRedirectToAccessDenied = XXX
				options.Events.OnRedirectToLogin = XXXX
			});
			
//Permanent
builder
				.AddScheme<PermalinkAuthenticationSchemeOptions, PermanentLinkAuthenticationHandler>(PermalinkDefaults.PermanentLinkScheme, o =>
				{
					o.XXX = XXXX
				});
`

**And finally I have selector of the scheme based on some criteria found in context :**
`
builder.AddPolicyScheme("JWT_OR_COOKIE_OR_PERMANENT_LINK", "JWT_OR_COOKIE_OR_PERMANENT_LINK", options =>
			{
				options.ForwardDefaultSelector = context =>
				{
					if (context.Request.Headers[HeaderNames.Authorization] == XXX)
						return JwtBearerDefaults.AuthenticationScheme;

					if (context.Request.Cookies[XXX] != null)
						return FormsDefaults.FormsScheme;

					if (context.Request.Headers[XXX] == XXX)
						return PermalinkDefaults.PermanentLinkScheme;

					//fallback to JWT
					return JwtBearerDefaults.AuthenticationScheme;
				};
			});
`

**Comment by TrayanZapryanov** [comment]
> I made a tool that might be helpful for detecting these issues. You can try copying this into your project, but I wouldn't recommend pushing it to production 😁. https://github.com/Tratcher/ConcurrencyAlert/blob/315c3e714691c2b6531e70078295cfe8a25dffb8/ConcurrencyAlert/Program.cs#L5

Unfortunately this happens only in a production.
I can use it optionally over a small set of our customers if you say that it will not break a lot of things and can see the results.

**Comment by TrayanZapryanov** [comment]
> I made a tool that might be helpful for detecting these issues. You can try copying this into your project, but I wouldn't recommend pushing it to production 😁. https://github.com/Tratcher/ConcurrencyAlert/blob/315c3e714691c2b6531e70078295cfe8a25dffb8/ConcurrencyAlert/Program.cs#L5

When I plug your sample there is an exception : Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__5.MoveNext()
   at PlatformHost.Controllers.EtwLoggingMiddleware.<InvokeAsync>d__3.MoveNext() in C:\Work\Git\WFService\src\PlatformHost\Controllers\EtwLoggingMiddleware.cs:line 38

**Comment by Tratcher** [comment]
Ah, my context factory wasn't filling in the request services. Updated.
https://github.com/Tratcher/ConcurrencyAlert/blob/master/ConcurrencyAlert/Program.cs

**Comment by Tratcher** [comment]
Even if you can't run this in production, it should make the issue much easier to find in development.

**Comment by TrayanZapryanov** [comment]
@Tratcher Unfortunately your code doesn't reveal any other exception.
I've experimented also with removing our custom middleware, but the exception doesn't change:
![image](https://user-images.githubusercontent.com/12857389/235998519-a3af798b-1989-46c6-90d5-ee4cb79ac491.png)
Any other ideas?

**Comment by TrayanZapryanov** [comment]
I've checked AppInsights logs again and looks like there are 2 parallel calls from same session and one of them succeeds, but the other fails. 
Is it possible that there is concurrency usage of **context** in ForwardDefaultSelector ?
Here it is my code again:

builder.AddPolicyScheme("JWT_OR_COOKIE_OR_PERMANENT_LINK", "JWT_OR_COOKIE_OR_PERMANENT_LINK", options =>
{
    options.ForwardDefaultSelector = context =>
    {
	if (context.TryGetJwtAuthorizationScheme(out string scheme))
		return scheme;

	if (context.TryGetFormsAuthorizationScheme(out scheme))
		return scheme;

	if (context.TryGetPermanentLinkAuthorizationScheme(out scheme))
		return scheme;

	//fallback to JWT
	return JwtBearerDefaults.AuthenticationScheme;
};
});

Also for every request this code is executed twice - maybe there is some concurrency here too(or at least is not optimal).

**Comment by En3Tho** [comment]
I wonder if you can create your own decorator class over HttpContext, decorate it's method with simple

``` if Interlocked.Increment != 1 then throw``` on method enter and
 ```if Interlocked.Decrement != 0``` on exit

Then just use aliases in suspicious places to use this one without changing much code

**Comment by TrayanZapryanov** [comment]
Hmm, 
Is it possible that double enters are due to misconfiguration?
I have 

```var defaultSchemes = new[] {"JWT_OR_COOKIE_OR_PERMANENT_LINK"};
			var defaultPolicy = new AuthorizationPolicyBuilder(defaultSchemes)
				.RequireAuthenticatedUser()
				.Build();

			return services.AddMvc(x => x.Filters.Add(new AuthorizeFilter(defaultPolicy)))```

and

```builder.AddPolicyScheme("JWT_OR_COOKIE_OR_PERMANENT_LINK", "JWT_OR_COOKIE_OR_PERMANENT_LINK", options =>
			{
				options.ForwardDefaultSelector = context =>
				{
					if(context == null)
						throw new ArgumentOutOfRangeException();
					if (context.TryGetJwtAuthorizationScheme(out string scheme))
						return scheme;

					if (context.TryGetFormsAuthorizationScheme(out scheme))
						return scheme;

					if (context.TryGetPermanentLinkAuthorizationScheme(out scheme))
						return scheme;

					//fallback to JWT
					return JwtBearerDefaults.AuthenticationScheme;
				};
			});```

**Comment by Tratcher** [comment]
Yes, both exceptions are being thrown from line 139 within that AddPolicyScheme callback. What code is on that line? And what's the actual exception type and message? The ArgumentOutOfRangeException seems like the only thing that could throw, but that seems unlikely.

**Comment by TrayanZapryanov** [comment]
@Tratcher There is small misunderstanding.
I changed my code in **ForwardDefaultSelector ** callback to throw ArgumentOutOfRangeException, so I can capture both calls to it per request. And callstacks are for this. My suggestion is that NRE might happen due to double call to the callback code, but maybe this is not right.

**Comment by Tratcher** [comment]
Ah. No, there's nothing wrong with ForwardDefaultSelector being called multiple times per request, the results aren't cached. The first time is called by the auth middleware to set HttpContext.User. The second time is called by the authz policy to check for permissions. The underlying AuthenticateAsync result is cached and re-used, but the selection of which scheme to check isn't.

These call stacks also shouldn't be happening in parallel unless something earlier in the pipeline is dispatching the request to two different threads.

**Comment by Tratcher** [comment]
Since this is an async race condition there's no way of knowing when it will be hit or how to recover from it. The concurrency has to be found and squashed like a bug 😁.

**Comment by adityamandaleeka** [comment]
Closing this issue since it looks like there's no further discussion.

**Comment by TrayanZapryanov** [comment]
Some feedback:
Without any touch in our codebase - exception disappear for almost 10 days.
No matter that we almost double the requests to our services.
Here it is what can I see from AppInsight logs
![image](https://github.com/dotnet/aspnetcore/assets/12857389/19dd6795-3fa1-4b64-9403-f0675329ab79)

Let's hope that "bug" will not return again :).
