### ISSUE TITLE
RDG file name mismatch between SyntaxTree.FilePath and [CallerFilePath] causes runtime KeyNotFoundException 

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#47918]
`SyntaxTree.FilePath` and `[CallerFilePath]` can give different filenames for the same compilation on our own public AzDO PR build pipeline which ultimately causes runtime KeyNotFoundExceptions in code relying on RDG.

Example runtime stack trace:

```
System.Collections.Generic.KeyNotFoundException : The given key '(/_/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs, 38)' was not present in the dictionary.
Stack trace
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.AspNetCore.Http.Generated.&lt;GeneratedRouteBuilderExtensions_g&gt;F69328E0708B4B584C5AACA22FE2C51A1CF192D6622828F613FC57C583CA77B63__GeneratedRouteBuilderExtensionsCore.MapCore(IEndpointRouteBuilder routes, String pattern, Delegate handler, IEnumerable`1 httpMethods, String filePath, Int32 lineNumber) in /_/src/Identity/Core/src/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 306
   at Microsoft.AspNetCore.Builder.GenerateRouteBuilderEndpoints.MapPost(IEndpointRouteBuilder endpoints, String pattern, Func`3 handler, String filePath, Int32 lineNumber) in /_/src/Identity/Core/src/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 47
   at Microsoft.AspNetCore.Routing.IdentityApiEndpointRouteBuilderExtensions.MapIdentityApi[TUser](IEndpointRouteBuilder endpoints) in /_/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs:line 38
   at Microsoft.AspNetCore.Identity.FunctionalTests.MapIdentityTests.CreateAppAsync[TUser,TContext](Action`1 configureServices) in /_/src/Identity/test/Identity.FunctionalTests/MapIdentityTests.cs:line 216
   at Microsoft.AspNetCore.Identity.FunctionalTests.MapIdentityTests.CanReadBearerTokenFromQueryString() in /_/src/Identity/test/Identity.FunctionalTests/MapIdentityTests.cs:line 155
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=253772&view=ms.vss-test-web.build-test-results-tab&runId=4932292&resultId=111661&paneView=debug

The disassembly of Microsoft.AspNetCore.Identity.dll from the PR shows RDG used "D:\a\_work\1\s\src\Identity\Core\src\IdentityApiEndpointRouteBuilderExtensions.cs" from `SyntaxTree.FilePath` as the filename for the source key:

```csharp
    file static class GeneratedRouteBuilderExtensionsCore
    {
        private static readonly Dictionary<(string, int), (MetadataPopulator, RequestDelegateFactoryFunc)> map = new()
        {
            [(@"D:\a\_work\1\s\src\Identity\Core\src\IdentityApiEndpointRouteBuilderExtensions.cs", 38)] = (
                (methodInfo, options) =>
```

https://github.com/dotnet/aspnetcore/blob/58940e3aebf6ae2d857ce00638520ebe7bb7c6eb/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Endpoint.cs#L164-L170

But Roslyn used a different filename at the call site of the generated `MapPost` method for its `[CallerFilePath]` parameter. It used "/_/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs" instead inside the same assembly:

```csharp
    public static IEndpointConventionBuilder MapIdentityApi<TUser>(this IEndpointRouteBuilder endpoints) where TUser : class, new()
    {
        ArgumentNullException.ThrowIfNull(endpoints);
        var routeGroup = endpoints.MapGroup("");
        routeGroup.MapPost("/register",
            new Func<RegisterRequest, IServiceProvider, System.Threading.Tasks.Task<Results<Ok, ValidationProblem>>>(<>c__0<TUser>.<>9.<MapIdentityApi>b__0_0),
            "/_/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs", 38);
```

**Comment by mitchdenny** [comment]
It looks to me like one was generated on a Linux machine, and the other was generated on a Windows machine. This might be a hole in our lookup strategy for interception. In the case o MapIdentityApi(...), its producing a DLL which is built on Linux and we are using it in a test which is presumably being built on Windows.

At this point I would say that our approach can't support what you are trying to do here with MapIdentityApi.

/cc @captainsafia

**Comment by halter73** [comment]
> It looks to me like one was generated on a Linux machine, and the other was generated on a Windows machine. This might be a hole in our lookup strategy for interception. In the case o MapIdentityApi(...), its producing a DLL which is built on Linux and we are using it in a test which is presumably being built on Windows.

I don't think this is a Windows vs Linux thing. That's why I made such a big point in the issue about how both file paths strings are being compiled into the same into the same Microsoft.AspNetCore.Identity.dll assembly. This is all being built on our Windows CI machine. The test project is not referencing RDG at all. It's simply using the endpoints defined by MapIdentityApi(...) using RDG that have already been compiled into the non-test Microsoft.AspNetCore.Identity.dll assembly.

This is not just a test issue. This breaks anyone trying to call `MapIdentityApi(...)` using the build produced by our CI. It's true that the path originating because of the `[CallerFilePath]` looks like a Linux path in this case because of the forward slashes, but I'm thinking something else must be causing this. Locally when I build with Windows, I see two Windows-looking paths with drive letters and backslashes.

@jaredpar @cston Do you have any idea why `SyntaxTree.FilePath` and `[CallerFilePath]` could give different filenames for the same compilation ?

**Comment by jaredpar** [comment]
> Do you have any idea why SyntaxTree.FilePath and [CallerFilePath] could give different filenames for the same compilation ?

This can happen with `/pathmap` is in play. The purpose of that argument is to allow builds to normalize build paths between machines. It changes the paths we emit into binaries:

- `SyntaxTree.FilePath`: this is always the physical file path (assuming there was one). It doesn't respect path map as it's telling the tooling where the file exists on disk. It's not directly emitted to the binary or PDB. 
- `[CallerFilePath]`: this is directly part of the binary and hence respects path map.

**Comment by halter73** [comment]
Is there a way to reliably get something that matches what the `[CallerFilePath]` from the `SyntaxTree` or another API in an analyzer?

**Comment by jaredpar** [comment]
There is not a public API for this. 😦 

Short term you can either reflect into `PathUtilities.NormalizePathPrefix` or just copy / paste the code into your generator. It's a fairly trivial function. Longer term we should get this added to the public API surface area. It's a very reasonable API to want. 

@RikkiGibson can you get a bug filed for that + track it through API review?

**Comment by RikkiGibson** [comment]
> * `SyntaxTree.FilePath`: this is always the physical file path (assuming there was one). It doesn't respect path map as it's telling the tooling where the file exists on disk. It's not directly emitted to the binary or PDB.

Whyyyyy did I convince myself that SyntaxTree.FilePath have already applied `/pathmap` when they are created 🙂
