### ISSUE TITLE
Replace BearerTokenOptions.ExtractBearerToken with Event

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#47937]
Based on the "Consider moving ExtractBearerToken to Options.Events" feedback to use `Events` from the earlier API review for adding `MapIdentityApi<TUser>()` (https://github.com/dotnet/aspnetcore/issues/47227#issuecomment-1520632789), I've updated the approved API for `BearerTokenOptions`

## Background and Motivation

We want to follow the pattern for options and events followed by other authentication handlers. This mainly took inspiration from `JwtBearerOptions`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Authentication.BearerToken;

public sealed class BearerTokenOptions : AuthenticationSchemeOptions
{
    public TimeSpan BearerTokenExpiration { get; set; } = TimeSpan.FromHours(1);

    public ISecureDataFormat<AuthenticationTicket>? BearerTokenProtector { get; set; }

-    public Func<HttpContext, ValueTask<string?>>? ExtractBearerToken { get; set; }
+    public new BearerTokenEvents Events { get; set; }
}

+ public class BearerTokenEvents
+ {
+    public Func<MessageReceivedContext, Task> OnMessageReceived { get; set; } = context => Task.CompletedTask;
+    public virtual Task MessageReceived(MessageReceivedContext context) => OnMessageReceived(context);
+ }

+ public class MessageReceivedContext : ResultContext<BearerTokenOptions>
+ {
+    public MessageReceivedContext(HttpContext context, AuthenticationScheme scheme, BearerTokenOptions options);
+    public string? Token { get; set; }
+ }
```

## Usage Examples

```csharp
authBuilder.AddBearerToken(options =>
{
    // Events is marked non-nullable but is appears to be null here.
    options.Events.OnMessageReceived = context =>
    {
        var accessToken = context.HttpContext.Request.Query["access_token"];

        // If the request is for our hub...
        var path = context.HttpContext.Request.Path;
        if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments("/hubs/chat"))
        {
            // Read the token out of the query string
            context.Token = accessToken;
        }
        return Task.CompletedTask;
    };
});
```

## Alternative Designs

- Keep `ExtractBearerToken`
- Make `BearerTokenOptions.Events` null initially like `JwtBearerOptions.Events`

## Risks

- This is new API in .NET 8 preview4, so the risk is pretty low.

**Comment by danirzv** [comment]
I'm interested in this issue, may I send a PR when the API got approved?

**Comment by mitchdenny** [comment]
I like the consistency with with OAuth.

**Comment by halter73** [comment]
API Review Notes:

- What do we think about making `Events` non-nullable? This matches the API signature of other auth options, but other auth options can actually be null during configuration callbacks.
  - Keep BearerTokenOptions non-nullable since it's new and it's more convenient that way.
  - Look at updating the nullability of the existing options types to be correct.
- Should `MessageReceived` be called `MessageReceivedAsync` to be more consistent with the rest of the dotnet framework? Or should we be more consistent with other auth handlers.
  - Let's give it an `Async` suffic.
- What about the `OnMessageReceived` callback?
  - We do rarely use the `Async` suffix for `Func` properties even if they are task returning. A property with a setter isn't exactly the same semantically as a method, so we think not using the suffix is fine.
- Should `BearerTokenEvents` or `MessageReceivedContext` be sealed?
  - `Events` is expected to be extensible and has a virtual method so should stay unsealed.
  - We can seal the `MessageReceivedContext` for now though. It would not be breaking to unseal.
- Should we use `ValueTask`?
  - Maybe. Getting the token from something like the query string can often be done synchronously.
  - But now we're not returning the token as part of the task so you can use `Task.CompletedTask` in this case.
  - The general guidance is to use `Task` over `ValueTask` unless you have a good reason for `ValueTask`.
- When does `OnMessageReceived` actually need to be async?
  - Maybe a db lookup for revocation checks.
  - In general, we've gotten feedback that all auth events should be async. This wasn't the case originally. 

Approved as proposed except that `MessageReceived` is now `MessageReceivedAsync`.

```diff
namespace Microsoft.AspNetCore.Authentication.BearerToken;

public sealed class BearerTokenOptions : AuthenticationSchemeOptions
{
    public TimeSpan BearerTokenExpiration { get; set; } = TimeSpan.FromHours(1);

    public ISecureDataFormat<AuthenticationTicket>? BearerTokenProtector { get; set; }

-    public Func<HttpContext, ValueTask<string?>>? ExtractBearerToken { get; set; }
+    public new BearerTokenEvents Events { get; set; }
}

+ public class BearerTokenEvents
+ {
+    public Func<MessageReceivedContext, Task> OnMessageReceived { get; set; } = context => Task.CompletedTask;
+    public virtual Task MessageReceivedAsync(MessageReceivedContext context) => OnMessageReceived(context);
+ }

+ public class MessageReceivedContext : ResultContext<BearerTokenOptions>
+ {
+    public MessageReceivedContext(HttpContext context, AuthenticationScheme scheme, BearerTokenOptions options);
+    public string? Token { get; set; }
+ }
```

**Comment by halter73** [comment]
> I'm interested in this issue, may I send a PR when the API got approved?

@danirzv I missed this during the API review. I don't think a PR is necessary. Most of the approved API is already checked into `main`.

The only remaining part of the approved API that hasn't been checked in is the change from `MessageReceived` to `MessageReceivedAsync` and updating the nullability of existing `public new {DerivedOptionsTypeName} Events` properties of `AuthenticationSchemeOptions`-derived types to be nullable.

If you want to try those two things though, feel free to take it.
