### ISSUE TITLE
ProtectedBrowserStorage can't load more than 25kb

### ISSUE THREAD

**Issue by tossnet** [dotnet/aspnetcore#47945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on a simple Blazor Server .NET 7 project for example, if I store a 25kb value, I can't read it back

### Steps To Reproduce

Create a new projet Blazor Server .NET 7 and paste this on Index.razor : 
```
@page "/"
@inject ProtectedSessionStorage sessionStorage

<button @onclick="ReadSave">Test</button>

@avatar

@code {
    string avatar;

    private async Task ReadSave()
    {
        // Create a long string
        int max = 24445; // ok with 24445
                         // change to 24446 it stop when reading

        System.Text.StringBuilder sb = new(max);
        for (int i = 0; i < max; i++)
        {
            sb.Append('a');
        }
        avatar = sb.ToString();

        // save
        await sessionStorage.SetAsync("avatar", avatar);

        // load it
        var data = await sessionStorage.GetAsync<string>("avatar");
        if (data.Success)
        {
            avatar = data.Value;
        }
    }
}
```

I tested and found that if I save a string larger than 24445, the program freezes when reading the session variable

### .NET Version

7

**Comment by Oguidan** [comment]
don't have the same same problem. Create a new one project.

**Comment by Oguidan** [comment]
What is funny

**Comment by tossnet** [comment]
> What is funny

you can imagine that I tested this directly in a new project before coming to ask my problem ;)
