### ISSUE TITLE
No XML encryptor configured

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#47959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using claims based authentication & authorization in my Blazor server app which has been configured like this:

```csharp
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, configureOptions =>
    {
    });

builder.Services.AddAuthorization(options =>
{

});
```

In my `Login.cshtml` I'm checking against LDAP and sign the user in like this:
```csharp
await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
```

Login and everything works, however I get three warnings within the EventViewer where our App is hosted on IIS Server.

### Expected Behavior

I'm not expecting any warnings. Can I ignore them? How do I get rid of them? Within the docs I didn't read anything relating an XML encryptor.

### Steps To Reproduce

---

### Exceptions (if any)

Category: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository
EventId: 50

Using an in-memory repository. Keys will not be persisted to storage.

Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 59

Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 35

No XML encryptor configured. Key {305054c8-fab1-44e7-8024-2d6cfb2471cb} may be persisted to storage in unencrypted form.

### .NET Version

.NET 7.0.5

**Comment by danroth27** [comment]
@blowdart Is there some configuration that need to be done here to enable the keys to be persisted?

**Comment by halter73** [comment]
Is the user profile loaded by the application pool? https://stackoverflow.com/a/37159978/719967

**Comment by blowdart** [comment]
Yea, no profile is loaded, so you'd need to configure a directory to store the keyring in, then set dpapi as the protector

Something like 

builder.Services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(@"\\server\share\directory\"));
