### ISSUE TITLE
Should MapShortCircuit matches for all methods or only GET?

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#47981]
I just noticed that `MapShortCircuit` API doc is different than its behavior. The docs says that it matches the GET request
https://github.com/dotnet/aspnetcore/blob/f62f12357c49c4f1cca502e8f4cf57353f0b320f/src/Http/Routing/src/ShortCircuit/RouteShortCircuitEndpointRouteBuilderExtensions.cs#L16

but the implementation matches all the methods
https://github.com/dotnet/aspnetcore/blob/f62f12357c49c4f1cca502e8f4cf57353f0b320f/src/Http/Routing/src/ShortCircuit/RouteShortCircuitEndpointRouteBuilderExtensions.cs#L37

I can't remember which one was the requirement but one of them has to be changed!

@Tratcher

**Comment by mitchdenny** [comment]
https://github.com/dotnet/aspnetcore/issues/46071

Original discussion appears to be silent. That said I think it makes sense to cover all HTTP methods rather than just GET when we consider the original goals of the extension.

**Comment by davidfowl** [comment]
I agree with @mitchdenny

**Comment by Tratcher** [comment]
The design was intended to cover all methods, but you could constrain it by adding method metadata. (Hmm, there's no WithMethods extension to add constraints, everything else assumes you do methods first?). `app.MapGet(pattern, delegate).ShortCircuit();` also works.
