### ISSUE TITLE
How to add a client certificate in a SocketsHttpHandler?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/aspnetcore#47988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a client gRPC service, and i would like to implement mTLS, so I would like to add the client certificate to the gRPC channel.

To create the gRPC channel, I am using this code:

```
X509Certificate2 miCertificadoCliente = X509Certificate2.CreateFromPem(paramStrCertificadoCliente);


SslClientAuthenticationOptions misOpcionesDeAutenticacion = new SslClientAuthenticationOptions();
misOpcionesDeAutenticacion.RemoteCertificateValidationCallback = ValidateServerCertificate;
misOpcionesDeAutenticacion.ClientCertificates = new X509CertificateCollection();
misOpcionesDeAutenticacion.ClientCertificates.Add(miCertificadoCliente);

SocketsHttpHandler miHttpHandler = new SocketsHttpHandler();
miHttpHandler.SslOptions = misOpcionesDeAutenticacion;


HttpClient httpClient = new HttpClient(miHttpHandler);

GrpcChannelOptions misOpcionesDelCanal = new GrpcChannelOptions()
{
    MaxReceiveMessageSize = 62914560,
    MaxSendMessageSize = 62914560,
    HttpClient = httpClient,
};



CallCredentials misCredencialesDeLlamada = CallCredentials.FromInterceptor((c, m) =>
{
    m.Add(HeaderNames.Authorization, $"Bearer {_tokenJwt}");
    return Task.CompletedTask;
});


var misCredencialesdelCanal = ChannelCredentials.Create(new SslCredentials(), misCredencialesDeLlamada);

misOpcionesDelCanal.Credentials = myChannelCredentials;


GrpcChannel miCanalGrpc = GrpcChannel.ForAddress("https://localhost:5001", misOpcionesDelCanal);
```

Btu the problem is that when the client makes a request to the server, I get an error in the handshake because the server requieres a client certificate, but it seems that the client add correctly the certificate.

If I configure the server to don't need client certificate, the server replies to the client.

So I guess the problem is that I am not adding the certificate in the correct way. How should I do it?

Thanks.

EDIT 01:

I have tried with this code (from documentation: https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/channel-credentials):

```
X509Certificate2 cert = X509Certificate2.CreateFromPem(paramStrCertificadoCliente, paramStrKeyCliente);
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    var originalCert = cert;
    cert = new X509Certificate2(cert.Export(X509ContentType.Pkcs12));
    originalCert.Dispose();
}


var handler = new HttpClientHandler();
handler.ClientCertificates.Add(cert);

var httpClient = new HttpClient(handler);


var callCredentials = CallCredentials.FromInterceptor(((context, metadata) =>
{
    metadata.Add("Authorization", $"Bearer {_tokenJwt}");
    return Task.CompletedTask;
}));

var channelCredentials = ChannelCredentials.Create(new SslCredentials(), callCredentials);

var channel = GrpcChannel.ForAddress("https://localhost:5002/", new GrpcChannelOptions
{
    HttpClient = httpClient,
    Credentials = channelCredentials
});
```

Perhaps the problem is that I want to use a self signed certificate that is not isntalled in the certificates store, but I don't want to have to install it, I would like to can use the certificate provided as a local file.

**Comment by amcasey** [comment]
This code does appear to match the public docs, so we might need some input from @JamesNK.

**Comment by ComptonAlvaro** [comment]
yes, the code is just a copy from the documentation. Just I have added a line of code to correct an error:

```
var callCredentials = CallCredentials.FromInterceptor(((context, metadata) =>
{
    metadata.Add("Authorization", $"Bearer {_tokenJwt}");
    return Task.CompletedTask;
}));
```
Here I have to add the line return Task.CompletedTask, becaues if not, I get a compile error because not all paths of the code return a value.

The rest of the code is a copy of the code that it can be found in the link of the documentation.

**Comment by JamesNK** [comment]
mTLS is configured on the `SocketsHttpHandler` or `HttpClientHandler`. I'm not an expert in mTLS, and I can't offer useful suggestions about why mTLS might not work.

**Comment by wfurt** [comment]
yes, the export/import is one way how to fix the ephemeral keys. If you use the X509Certificate2 contractor & pfx you can specify the X509KeyStorageFlags explicitly. But it is essentially same at the end.

While this is annoying it comes from limitations of schannel in Windows.

**Comment by ComptonAlvaro** [comment]
How could I set the flag X509KeyStorageFlags when I create the certificate? Is it possible if I use .crt and .key files or I need to create the X509Certificate2 instance from a pfx file?

**Comment by wfurt** [comment]
You can use [Contructor](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.-ctor?view=net-6.0#system-security-cryptography-x509certificates-x509certificate2-ctor(system-string-system-string-system-security-cryptography-x509certificates-x509keystorageflags)) or [Import](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.import?view=net-6.0#system-security-cryptography-x509certificates-x509certificate2-import(system-byte()-system-security-securestring-system-security-cryptography-x509certificates-x509keystorageflags)). 

Perhaps @vcsjones remembers why the PEM functions do not have the options.

**Comment by amcasey** [comment]
@wfurt The docs actually specifically call out https://github.com/dotnet/runtime/issues/23749 and the workaround seems to have been incorporated into the code in this issue.
https://stackoverflow.com/questions/62201695/best-practices-for-swagger-ui-in-production

**Comment by amcasey** [comment]
@ComptonAlvaro In the future, it might be clearer to create a standalone repo or gist containing your code so you don't have to paste it over and over and you can modify it as you apply various suggestions.

**Comment by vcsjones** [comment]
> Perhaps @vcsjones remembers why the PEM functions do not have the options.

We discussed this in the initial API proposal over at https://github.com/dotnet/runtime/issues/31944#issuecomment-639759842, the general conclusion there wasn't a clear need for it. The other reason is because it's non-trivial to implement - much of the existing logic for key storage flags is specific for PFX.

> You can use Contructor or Import.

`Import` is obsolete. The constructor is the right way to go.

```C#
X509Certificate2 loaded = X509Certificate2.CreateFromPem("foo.pem");
X509Certificate2 cert = new X509Certificate2(loaded.Export(X509ContentType.Pfx, null), null, X509KeyStorageFlags.PersistKeySet);
```

**Comment by ComptonAlvaro** [comment]
Well, finally I could add the certificate to the socket in this way:

```
//Craete the certificate from the PEM files
X509Certificate2 miCertificadoCliente = X509Certificate2.CreateFromPem(paramStrCertificadoCliente, paramStrKeyCliente);
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    var originalCert = miCertificadoCliente;
    miCertificadoCliente = new X509Certificate2(miCertificadoCliente.Export(X509ContentType.Pkcs12));
    originalCert.Dispose();
}


//Create the authentication options for the socket
SslClientAuthenticationOptions misOpcionesDeAutenticacion = new SslClientAuthenticationOptions();
misOpcionesDeAutenticacion.RemoteCertificateValidationCallback = ValidarCertificadoServidor;
misOpcionesDeAutenticacion.ClientCertificates = new X509CertificateCollection();
misOpcionesDeAutenticacion.ClientCertificates!.Add(miCertificadoCliente);


//Create the socket and assign the authentication options.
SocketsHttpHandler miHttpHandler = new SocketsHttpHandler();
miHttpHandler.SslOptions = misOpcionesDeAutenticacion;
```

The certificate is received by the server, that can be validate if it is needed, for mutual authentication, for example.

**Comment by wfurt** [comment]
yes, the fragment looks reasonable.

**Comment by adityamandaleeka** [comment]
Closing this issue since it looks like @ComptonAlvaro figured it out. @wfurt feel free to reopen and/or transfer if this could be a potential doc improvement.
