### ISSUE TITLE
ControllerBase Route attribute is ignored in dynamically loaded AssemblyParts

### ISSUE THREAD

**Issue by eusebiu** [dotnet/aspnetcore#47980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Route attribute of ControllerBase is ignored when an AssemblyPart is dynamically loaded (built using a separate C# project that uses nuget Microsoft.AspNetCore.Mvc.Core.dll). 

I am loading a dynamic library (Assembly.Load) and then I add AsseblyParts to the IServiceCollection.AddControllers.
Controller - in the other library (not referenced by the main Web project):
```
    [ApiController]
    [Route("api/[controller]")]
    [AllowAnonymous]
    public class AsopController : ControllerBase
    {
        public AsopController()
        {
        }

        [HttpGet()]
        public IActionResult Get()
        {
            return Ok(new { text = "OK" });
        }
    }
```
Startup.cs - ConfigureDevelopmentServices(IServiceCollection serviceCollection)

```
var pluginsPath = Path.Combine(AppContext.BaseDirectory, @".\Plugins");
string[] pluginPaths = Directory.GetFiles(pluginsPath, "*.Plugin.dll", SearchOption.AllDirectories);

            foreach (var pluginPath in pluginPaths)
            {
                Assembly pluginAssembly = pluginPath.LoadAssembly(); // this is just Assembly.Load

                IMvcBuilder mvcBuilder = serviceCollection.AddControllers();
                mvcBuilder.ConfigureApplicationPartManager(pm =>
                {
                    pm.ApplicationParts.Add(new AssemblyPart(pluginAssembly));
                });
            }
```
In ConfigureDevelopment(IApplicationBuilder app):
```
 app.UseRouting();
...
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
```

The endpoints are now populated with the MVC style routes: controller=Home/action=Index/... so, the initial route is ignored.

### Expected Behavior

The request route should be found according to the definition in controller Route attribute.

### Steps To Reproduce

See code above.

### .NET Version

6

**Comment by davidfowl** [comment]
Can you make a runnable example?

**Comment by eusebiu** [comment]
Sure. Attached here - https://1drv.ms/u/s!Aq1jgNgVNaunlDwYgRUlSd6Gy386?e=2tTnQl
First, rebuild the TEST.API.ASOP.Plugin so it can copy itself to the WebApi project bin/Plugins folder and make sure you have the latest version (it is loaded in Startup.cs - RegisterPlugins method).
To reproduce - run the WebApi:
1. go to https://localhost:44380/api/version - works fine as this is a local controller
2. go to https://localhost:44380/api/asop - does not work 404 (this is the bug)
3. go to https://localhost:44380/asop/get - works to some extent - it finds the controller but breaks at return - I think this is another bug

**Comment by davidfowl** [comment]
@eusebiu can you make this a GitHub repository? As you can imagine the risk is downloading source in a zip from GitHub that we’d like to avoid. Making it a repository means we can at least browse the code before downloading/cloning it.

**Comment by eusebiu** [comment]
Here you go: https://github.com/eusebiu/AspNetCore-Router-Bug

**Comment by davidfowl** [comment]
Is there a reason you're not calling MapControllers [here](https://github.com/eusebiu/AspNetCore-Router-Bug/blob/23e41c22d8409ca33c21ffc36e9203f2007fa71e/TEST.API.WebApi/Startup.cs#L207)

**Comment by eusebiu** [comment]
No, but the issue persists with MapControllers, too (and I think this will also break the MVC routes - in the case the project would need it)...

**Comment by davidfowl** [comment]
I get this when I run the application and hit

![image](https://user-images.githubusercontent.com/95136/235372815-d222e9f8-4d4a-4091-abaa-3f958d53a43c.png)

**Comment by eusebiu** [comment]
Strange... I get this:
![image](https://user-images.githubusercontent.com/414589/235372936-30e563a4-4a63-4659-ad98-b278101f187e.png)

I am using these sdks - now 6...
PS C:\Users\E617108> dotnet --list-sdks
3.1.415 [C:\Program Files\dotnet\sdk]
6.0.401 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]

**Comment by davidfowl** [comment]
I also don't have the call to MapControllers the app. Will try to narrow down the differences. Your application worked on my box without changes.

**Comment by eusebiu** [comment]
It seems to work fine with .net7, so I guess it's .net 6 issue...

**Comment by davidfowl** [comment]
The projects you sent me were .NET 6 based right?

**Comment by davidfowl** [comment]
```
➜ dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.311 [C:\Program Files\dotnet\sdk]
7.0.300-preview.23179.2 [C:\Program Files\dotnet\sdk]
8.0.100-preview.4.23205.4 [C:\Program Files\dotnet\sdk]
```

**Comment by davidfowl** [comment]
Why do you have this package reference?

```
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
```

This shouldn't be part of the project.

**Comment by eusebiu** [comment]
> <FrameworkReference Include="Microsoft.AspNetCore.App" />

Yes, the projects were .net6. 

Changed the reference and still not found.

The only thing that works is .net7.

**Comment by mkArtakMSFT** [comment]
@davidfowl is there enough evidence that there is a bug here?
Assuming there is, is there a workaround we can suggest?

**Comment by davidfowl** [comment]
Not sure, I'd like one other person to try to repro with the above repository and see if they can see what @eusebiu is seeing.

**Comment by halter73** [comment]
I see the same thing @davidfowl sees. Both the initial commit and the update to use the FrameworkReference worked for me with zero modifications. https://localhost:44380/api/asop returns `{"result":"OK"} and https://localhost:44380/asop/get returns a 404.

@eusebiu Are you reproducing this from a clean clone of your repo? If so, the other thing I might try is reinstalling your [.NET 6.0 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). I'm using 6.0.407, but David is using and older SDK than you are, so I don't think it's anything we patched.

**Comment by eusebiu** [comment]
Then we can close the issue.
