### ISSUE TITLE
`IHttpContextScopedAccessor` for accessing `HttpContext` from request scoped DI components

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/aspnetcore#47996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

```CSharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddScoped<MyComponent>();

// !!!!!!!!!!
// RUNTIME Error:
// MyComponent ->Resolve Problem-> HttpContext - not registered as Scoped service
// !!!!!!!!!!
var app = builder.Build(); 


app.MapGet("/weatherforecast", (MyComponent c) =>
{
    return c.GetWeatherData();
});

app.Run();

public class MyComponent
{
    private readonly HttpContext _httpContext;

    public MyComponent(HttpContext httpContext)
    {
        _httpContext = httpContext;
    }

    public string GetWeatherData()
    {
        if (_httpContext.Request.Headers["x-units"] == "F")
        {
            return $"{20 * 9 / 5} + 32";
        }
        return "20 C";
    }
}
```

### Describe the solution you'd like

All scoped DI components should be able to directly resolve `HttpContext` or at least through `IHttpContextScopedAccessor`

It's already suggested in this StackOverflow question:
https://stackoverflow.com/questions/49966858/scoped-service-access-http-context-without-ihttpcontextaccessor

A middleware should setup `HttpContext` to some scoped DI placeholder, and then all Scoped components should be able to access  `HttpContext`.

### Additional context

The lack of suggested `IHttpContextScopedAccessor` forces developers who needs `HttpContext` in 100% Scoped component chains to use `IHttpContextAccessor` as the only out-of-the box workaround.

But this is wrong!
`IHttpContextAccessor` is a workaround for a case where you have no way to pass the HttpContext through parameters to  singleton components.

**Comment by davidfowl** [comment]
The HttpContext isn't a service, this is why the IHttpContextAccessor exists, and you should use it. There's really no other way to make this work.

**Comment by dmitriyse** [comment]
Ok, I understood, may be it's not a good idea to pass HttpContext itself.

But having only IHttpContextAccessor for all cases it's not an ideal scenario.
In this issue I suggest to have two services:
 - IHttpContextAccessor (Registered as Singleton) - to pass HttpContext to the Singleton components over the AsyncLocal
 - IHttpContextScopedAccessor  (Registered as Scoped) - to pass HttpContext directly through DI to the Scoped only components.
 
 Using the only `IHttpContextAccessor` each time makes developer to thing about the AsyncLocal and details of how it works.
 And it feels non-natural to inject a Singleton component to a Scoped component and then rely on ambient infrastructure to obtain the HttpContext from the Request Scope which has 100% the same lifetime as the HttpContext.

**Comment by davidfowl** [comment]
If you feel that strongly about making sure it's only ever scoped to make sure it can't be injected into a singleton then I'd suggest doing what I suggested in that issue. Build a middleware that exposes the data as a scoped service that gets set by a middleware. I don't think it makes sense to add another service that gives access to the `HttpContext` the same way the IHttpContextAccessor does.

**Comment by ShreyasJejurkar** [comment]
I agree with what @davidfowl is saying, `HttpContext` is not a service, it's the representation of the current HTTP request! 

And also @dmitriyse what is the problem with injecting `IHttpContextAccessor` to the components? The sole purpose of that service is to give access to HttpContext itself, where you don't have direct access to current request data!

**Comment by dmitriyse** [comment]
The problem are conceptual and performance.
IHttpContextAccessor.HttpContext implementation based on AsyncLocal (as it's a singleton)

1) AsyncLocal is a potential perf leak, even if it's a minor, it hits your brain. Most probably it's minor, but you do not have numbers.
2) IHttpContextAccessor.HttpContext should be used from the right execution context, you have more chances to introduce a hidden bug.
4) IHttpContextAccessor.HttpContext is nullable, but in a case of request scoped component it's not a clean design, as it never be null as a request DI scope always bound to a request HttpContext.
5) IHttpContextAccessor being singleton do not help to enforce a strict design.  If you register a component as a Scoped your forces all it's consumers (other DI components) to be scoped/transient. IHttpContextAccessor do not help here. It's easy to create more singletons which can provides an API that would hiddenly expect to be called from the Execution context.
6) There are lot's of documents where IHttpContextAccessor is discouraged to be used (https://github.com/dotnet/aspnetcore/issues/27392)
7) People who remember IIS know about it's complicated threading model and issues of maintenance of the correct ExecutionContext, remember tons of problems with HttpContext.Current (and yes IHttpContextAccessor is exactly the same API but for AspNetCore). 

From the very beginning IHttpContextAccessor was the workaround for the cases where you have no option to access the request scope and the only way is to obtain the HttpContext from is the ExecutionContext. Suggesting to re-use this workaround instead of a dedicated API for request-scoped DI components is limiting future maneuvers maintain totally different use cases of accessing HttpContext.

If you try to review this class:
```CSharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.AspNetCore.Http;

/// <summary>
/// Provides an implementation of <see cref="IHttpContextAccessor" /> based on the current execution context.
/// </summary>
public class HttpContextAccessor : IHttpContextAccessor
{
    private static readonly AsyncLocal<HttpContextHolder> _httpContextCurrent = new AsyncLocal<HttpContextHolder>();

    /// <inheritdoc/>
    public HttpContext? HttpContext
    {
        get
        {
            return _httpContextCurrent.Value?.Context;
        }
        set
        {
            var holder = _httpContextCurrent.Value;
            if (holder != null)
            {
                // Clear current HttpContext trapped in the AsyncLocals, as its done.
                holder.Context = null;
            }

            if (value != null)
            {
                // Use an object indirection to hold the HttpContext in the AsyncLocal,
                // so it can be cleared in all ExecutionContexts when its cleared.
                _httpContextCurrent.Value = new HttpContextHolder { Context = value };
            }
        }
    }

    private sealed class HttpContextHolder
    {
        public HttpContext? Context;
    }
}
```

Then you immediately ask another question:
```CSharp

// Why do we use static here ? 
// It's not so clean. 
// Different instances of AspNetCore app should have it's own AsyncLocal instance and be independent from each other.
private static readonly AsyncLocal<HttpContextHolder> _httpContextCurrent;

// Ok, If we use static, then why we unable to use just this:
[ThreadStatic]
private static HttpContextHolder _httpContextCurrent;
```

# Alternative
The alternative looks many times more robust and guarantee the 100% of possible performance and zero side effects.
```CSharp
public class HttpContextScopedAccessor: IHttpContextScopedAccessor
{
    ...
    public HttpContext HttpContext 
    {
        get
        {
             return _currentHttpContext ?? throw new InvalidOperationException("Middleware that setup HttpContext hasn't been executed");
        }
        ...
    }
}
```

**Comment by dmitriyse** [comment]
Some proofs from the official docs:
![image](https://user-images.githubusercontent.com/10322215/235442272-f58c013c-f1df-4755-b309-4803092806ba.png)

**Comment by davidfowl** [comment]
> AsyncLocal is a potential perf leak, even if it's a minor, it hits your brain. Most probably it's minor, but you do not have numbers.

It is but it's not significant enough to affect any real application, mostly microbenchmarks and our crazy benchmarks that eek every ounce of performance out of the stack.

> IHttpContextAccessor.HttpContext should be used from the right execution context, you have more chances to introduce a hidden bug.

Yes, async locals are indeed evil but necessary in many contexts (not just in the case where you need to access it from a singleton).

> IHttpContextAccessor.HttpContext is nullable, but in a case of request scoped component it's not a clean design, as it never be null as a request DI scope always bound to a request HttpContext.

This doesn't change the nullability of the property. It has to be set by another component and if that component hasn't run yet, it'll be null. 

> People who remember IIS know about it's complicated threading model and issues of maintenance of the correct ExecutionContext, remember tons of problems with HttpContext.Current (and yes IHttpContextAccessor is exactly the same API but for AspNetCore).

Sure, but ASP.NET Core (even on IIS) works *very* differently to .NET Framework.


Still, I'm not convinced we should have another way to access the HttpContext from the DI container that only works in some cases.

**Comment by amcasey** [comment]
If I understand the thread correctly, This might make things a little simpler and could even be a perf win (I'd need to see numbers), but there's somewhat limited demand for the feature and it's something people who feel strongly about it can implement themselves.  Assuming that's all correct, my inclination is to close the issue - we can always revisit it later.

**Comment by dmitriyse** [comment]
External demand is not measured well, as using the existing IHttpContextAccessor is always recommended. While internally, many MS teams are trying to refrain from using IHttpContextAccessor.
I going to implement the proposed IHttpContextScopedAccessor in a Nuget package. It's not too big a deal.

But it reduces my productivity and put a bad impression on a .Net/AspNetCore as a stack. 
1) I spend time understanding the problem
2) Propose a solution
3) Finally implement things myself.

There are lots of great things in .Net/AspNeteCore and it's an amazing product. But it can be improved to be more friendly to reduce engineering costs 

At some point in time, I will link the NuGet with the IHttpContextScopedAccessor to this issue.

The ticket can be closed, I don't know how I can convince you and what proof to provide to support the priority of this demand.

**Comment by dmitriyse** [comment]
Forcing people to use an "Ambient state" where it can be easily avoided is not a clean design. Keeping this order of things erodes the entire AspNetCore product and ecosystem around it. IHttpContextAccessor infects more and more code.
IMHO: Too small efforts saving (avoiding one more abstraction) compared to negative impact in the long run.

**Comment by davidfowl** [comment]
We're not going to implement this feature, and though I agree with most of what you say, I'm not convinced of the benefits offering another approach. Feel free to implement this in your own code.

**Comment by dmitriyse** [comment]
We may still not be on the same page.
I propose to have two:
IHttpContextAccessor - ideally fits a use case where you really need an ambient state
IHttpContextScopedAccessor - ideally fits the places where it can be avoided (request DI scopes)

I don't propose to replace anything.

We just lack a second abstraction and try to adapt one badly to both scenarios, which brings lots of unwanted side effects to the second one.
I strongly believe, that if the two abstractions would exist from the beginning, they would be equally popular in the codebases.

In this particular problem, it's not too late to correct the situation. It's not as hard as "Nullable reference types".

**Comment by davidfowl** [comment]
We're on the same page, I just don't want to introduce another abstraction.

**Comment by dmitriyse** [comment]
@davidfowl, thanks for your feedback. It might be a good option to keep such abstraction in a dedicated nuget package and see if it receives a real demand before introducing a new abstraction right in the framework.

**Comment by davidfowl** [comment]
Agree with that.
