### ISSUE TITLE
Cookie accidentally shared between subdomains of my application?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#47998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have 2 React.JS / Next.JS applications running in 2 different subdomains. The apps are using Identity server. It appears that when one of the application logs in the user, the second application automatically logs in with the same user credential in a different browser tab. The browser debugger shows they have different cookies with different `Domain`s. I don't have the chance to capture the cookie of Identity server as it disappears after the login.

Identity server logs shows that the second app running in the second browser tab does make a request back to the server and it immediately, falsely identify with the first login in the first app.

How to fix this?

### Expected Behavior

2 different web applications at different subdomains should not share the server cookie.

### .NET Version

7.0.105

### Anything else?

```
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.105 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by danroth27** [comment]
Are you unintentionally configuring the cookies to be shared across subdomains? Specifically do you have something like this in your app?: https://learn.microsoft.com/aspnet/core/security/cookie-sharing#share-cookies-across-subdomains

**Comment by khteh** [comment]
> you should update the cookie domain and/or path for each app's authentication cookie so that they are unique to each app

How to achieve that?

**Comment by khteh** [comment]
> Are you unintentionally configuring the cookies to be shared across subdomains? Specifically do you have something like this in your app?: https://learn.microsoft.com/aspnet/core/security/cookie-sharing#share-cookies-across-subdomains

No.

**Comment by mitchdenny** [comment]
@khteh I'm assuming that identity server is on a different subdomain? So you've probably got something like this:

login.mycompany.com (identity server)
app1.mycompany.com
app2.mycomany.com

When a user opens a browser to app1.mycompany.com it would redirect to login.mycompany.com (identity server) to do auth. Identity server itself would store a cookie in the browser so that it knows that it has previously identified this user. Then when a user goes to app2 it also redirects to identity server which then detects that the user is logged in and then redirects to app2 with the appropriate tokens it can use to validate that the user is authenticated.

Note, I'm just deducing this from the limited description above so I could be way off. But on the surface this seems like the correct behavior for an SSO solution like identity server.

**Comment by khteh** [comment]
I don't want SSO! These 2 independent applications should not automatically sign in with each other's user credentials although they use the same Identity server.

**Comment by khteh** [comment]
> you should update the cookie domain and/or path for each app's authentication cookie so that they are unique to each app

If you refer to the client applications, this is already done and evidenced from the browser debugger. I am not sure if this needs to be done at the Identity server and if so, how?

**Comment by mitchdenny** [comment]
You would need to follow up with Duende on whether this is something that Identity Server can support.

**Comment by khteh** [comment]
What if I don't use Duende but only with ASP.Net Core Identity?

**Comment by mitchdenny** [comment]
if you have two applications and they both have ASP.NET Core identity configured separately they they shouldn't interact at all (unless you go out of your way to make them interact).

**Comment by khteh** [comment]
> ASP.NET Core identity configured separately

What do you mean? How different is this from IdentityServer?

**Comment by khteh** [comment]
> Then when a user goes to app2 it also redirects to identity server which then detects that the user is logged in and then redirects to app2 with the appropriate tokens it can use to validate that the user is authenticated.

When you say "the user", which user and why? It's a totally different application and the user is required to have the specific role to authenticate with the IdentityServer from the different apps.

**Comment by mkArtakMSFT** [comment]
@blowdart what do you think about this one?

**Comment by blowdart** [comment]
SSO, and the saving of creds on an identity server instance is rather the point of identity server (and AAD, and Auth0 etc)

If a login cookie is dropped on identity server, then it's going to use that to continue to authenticate for all apps so as not to force users to reauthenticate. Duende are best placed here to advise.

**Comment by mitchdenny** [comment]
Thanks @blowdart.

@khteh it doesn't look like there is an ASP.NET bug here. This looks like more of an architectural decision that you are trying to work out with how your application(s) handle authentication. Given this I'm inclined to close an issue unless we can confirm a bug here.
