### ISSUE TITLE
Output Cache doesn't work when user has Cookie Authentication cookies

### ISSUE THREAD

**Issue by offirpeer** [dotnet/aspnetcore#48025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

After a user logs in to my website using Google/Facebook the output cache doesn't work anymore due to **.AspNetCore.Cookies**.

Please change the default policy so **only** for action/controller that has `Authorize` on it the output cache will be ignored instead when the user is logged in.

The current behavior is not correct because logged in user views static content that should come from output cache.

### Describe the solution you'd like

Change the behavior of the default policy to ignore output only when action/controller has `Authorize` attribute.

**Comment by mkArtakMSFT** [comment]
@sebastienros is this behavior by design?

**Comment by sebastienros** [comment]
By design and documented, when a user is authenticated output caching is disabled for the request.

Custom routes or actions can use a custom policy that will enable caching even for authenticated requests. Documentation is here: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-7.0

**Comment by offirpeer** [comment]
@sebastienros I don't know what lead it to be by design, there is no reason an authenticated user should be "punished" and get the page from Database and not from the output cache.

The fact a user is authenticated has no meaning when viewing a static page like https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-7.0 for example.

The default behavior should be output cache for every user and when "Authorize" attribute is present above action/controller it should be disabled.

**Comment by sebastienros** [comment]
> there is no reason an authenticated user should be "punished"

There is a huge security risk with that, if this was enabled by default someone would potentially get private information from other users' pages. And if you stored the content for each different user by default then your memory/storage usage would jump unexpectedly.

This is why this is not on by default. But you can do it yourself once you understand the risks or known how to mitigate it. Some people for instance "know" that they don't render private information in specific pages and then decide to cache these. Then rely on non-cached endpoints to render private information (shopping carts, personal info, ...). 

The same way all pages are not cached when a cookie is set. So if you are generating an auth cookie this will happen too. Also configurable with a custom policy.

The default policy should work fine for everyone and not introduce bugs. Then developers have the tools to configure it for their custom needs.

**Comment by adityamandaleeka** [comment]
@offirpeer As @sebastienros mentioned above, the caching policy can be overridden to modify the behavior (including allowing you to enable caching on authenticated requests).

As a platform we try to choose safe defaults where possible to minimize the chance of accidental misuse, so it's unlikely that we will change the default behavior here.
