### ISSUE TITLE
Fix System.Security.Cryptography.Xml dependency

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#48033]
https://github.com/dotnet/aspnetcore/pull/47894 did some infrastructure changes that broke source build when trying to insert into the installer https://github.com/dotnet/installer/pull/16275.
```
error NU1605: Warning As Error: Detected package downgrade: System.Security.Cryptography.Xml from 8.0.0-preview.5.23228.8 to 6.0.1. Reference the package directly from the project to select a different version.
```

We reverted part of the change here (https://github.com/dotnet/aspnetcore/pull/48029) to unblock the insertion. What's the correct fix?

**Comment by wtgodbe** [comment]
Nothing more is needed here as far as I know
