### ISSUE TITLE
asp.net mvc An unhandled exception occurred while processing the reques

### ISSUE THREAD

**Issue by josepereira1988** [dotnet/aspnetcore#48046]
Projeto é em asp.net mvc.
Estou criando um projeto que carrega módulos utilizando o caminho
ele carrega a controller mas não carrega as Views

---- Esse apresentado 
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Teste/Index.cshtml
/Views/Shared/Index.cshtml

----- Metodo que carrega o modulo
        public static void Modulos(string path, IServiceCollection services)
        {

            var context = new AssemblyLoadContext(null, true);
            var assemblya = context.LoadFromAssemblyPath(path);
            services.AddControllersWithViews().AddApplicationPart(assemblya).AddControllersAsServices();          

        }

---- Controller
    [Route("[controller]")]
    public class TesteController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
			return View();
		}
    }

--- View
@page
<h1>aqui</h1>

**Comment by javiercn** [comment]
@josepereira1988 thanks for contacting us.

Does the assembly contain the view? Is it coming from a Razor Class Library?
