### ISSUE TITLE
Blazor WebAssembly build error

### ISSUE THREAD

**Issue by kouroshsalahshoor** [dotnet/aspnetcore#48044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi dotnet,

Blazor WebAssembly template does not build with individual account.
After creating wasm with individual account and hosted template, I get these 2 errors:

1)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\kousal2\Desktop\BlazorApp4\BlazorApp4\Client\obj\Debug\net6.0\ref\BlazorApp4.Client.dll' could not be found	BlazorApp4.Server	C:\Users\kousal2\Desktop\BlazorApp4\BlazorApp4\Server\CSC	1	Active

2)
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find file 'C:\Users\kousal2\Desktop\BlazorApp4\BlazorApp4\Client\obj\Debug\net6.0\BlazorApp4.Client.dll'.	BlazorApp4.Client	C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets	238	

Please examin

BR
kourosh

### .NET Version

6

### Anything else?

![image](https://user-images.githubusercontent.com/8199414/235914535-bf311f99-bbee-4418-a731-ce531024f920.png)

**Comment by Xyncgas** [comment]
A friendly reminder, you should redact your computer's user name when posting debug information

**Comment by Xyncgas** [comment]
might be related
https://github.com/dotnet/maui/issues/8613
https://github.com/dotnet/runtime/issues/76554

**Comment by mkArtakMSFT** [comment]
Can you try to build from the command line (not from VS) and share the output?
Also, what if you pin the SDK to 6.0 [using global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json)? Does it fix it?

**Comment by kouroshsalahshoor** [comment]
Hi,
Thank you so much for your answer.
I am using VS 2022
[cid:d5b6ed1e-2031-469a-bdf3-16414b5f6ce4]

What I want to do is to create blazor wasm with
[cid:35018b41-e683-46c5-be06-18e53c409ec7]

VS creates the solution and 3 projects fine
but when I build the solution I get following 2 errors:
1)
Severity    Code  Description Project     File  Line  Suppression State
Error CS0006      Metadata file 'C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\obj\Debug\net6.0\ref\BlazorApp1.Client.dll' could not be found BlazorApp1.Server C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Server\CSC   1     Active
2)
Severity    Code  Description Project     File  Line  Suppression State
Error       The asset 'C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\bin\Debug\net6.0\wwwroot\_framework\BlazorApp1.Client.dll' can not be found at any of the searched locations 'C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\bin\Debug\net6.0\wwwroot\_framework\BlazorApp1.Client.dll' and 'obj\Debug\net6.0\BlazorApp1.Client.dll'    BlazorApp1.Client C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets      234   

[cid:105d1d86-444f-44c9-86f8-7aa9a406892b]

As you see both of these errors are outside of the solution, that is from CSC file and
C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets

Then I did as you said and built by cli. The output is:

C:\Users\kousal2\Desktop\BlazorApp1>dotnet build
MSBuild version 17.6.0-preview-23174-01+e7de13307 for .NET
  Determining projects to restore...
  Restored C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Shared\BlazorApp1.Shared.csproj (in 200 ms).
  Restored C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj (in 430 ms).
  Restored C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Server\BlazorApp1.Server.csproj (in 431 ms).
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInf
erence.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-
policy [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Shared\BlazorApp1.Shared.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInf
erence.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-
policy [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInf
erence.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-
policy [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Server\BlazorApp1.Server.csproj]
  BlazorApp1.Shared -> C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Shared\bin\Debug\net6.0\BlazorApp1.Shared.dll
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: The "GenerateBlazorWebAssemblyBootJson" task failed unexpectedly
. [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\k
ousal2\Desktop\BlazorApp1\BlazorApp1\Client\obj\Debug\net6.0\BlazorApp1.Client.dll'. [C:\Users\kousal2\Desktop\BlazorAp
p1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: File name: 'C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Clien
t\obj\Debug\net6.0\BlazorApp1.Client.dll' [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.cspr
oj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(Stri
ng fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [C:\Users\kousal2\Desktop\BlazorAp
p1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String ful
lPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unix
CreateMode) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String pat
h, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCrea
teMode) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at System.Reflection.Metadata.MetadataReader.GetAssemblyName(
String assemblyFile) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateBlazorWebAssem
blyBootJson.Execute() [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.
BackEnd.ITaskExecutionHost.Execute() [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTas
k(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, Ta
skExecutionMode howToExecuteTask) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: The "GenerateBlazorWebAssemblyBootJson" task failed unexpectedly
. [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\k
ousal2\Desktop\BlazorApp1\BlazorApp1\Client\obj\Debug\net6.0\BlazorApp1.Client.dll'. [C:\Users\kousal2\Desktop\BlazorAp
p1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018: File name: 'C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Clien
t\obj\Debug\net6.0\BlazorApp1.Client.dll' [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.cspr
oj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(Stri
ng fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [C:\Users\kousal2\Desktop\BlazorAp
p1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String ful
lPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unix
CreateMode) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String pat
h, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCrea
teMode) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at System.Reflection.Metadata.MetadataReader.GetAssemblyName(
String assemblyFile) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateBlazorWebAssem
blyBootJson.Execute() [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.
BackEnd.ITaskExecutionHost.Execute() [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sd
k.BlazorWebAssembly.6_0.targets(322,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTas
k(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, Ta
skExecutionMode howToExecuteTask) [C:\Users\kousal2\Desktop\BlazorApp1\BlazorApp1\Client\BlazorApp1.Client.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:12.03

I hope these helps. Please let me know if you need something more 🙂

Thank you

Best regard
kourosh
________________________________

**Comment by kouroshsalahshoor** [comment]
This is the build result a little bit cleaned up 🙂

[cid:5d2d514f-06a0-42dc-b000-9a2a787c7fbd]
________________________________

**Comment by kouroshsalahshoor** [comment]
One last thing 🙂
when I do not choose Authentication, everything works fine
________________________________

**Comment by kouroshsalahshoor** [comment]
build with global.json

[cid:c0b34168-1ae3-49a4-af5d-46e3fcec2f84]
________________________________

**Comment by kouroshsalahshoor** [comment]
At last the problem was solved! :) Based on this article:
https://forums.servicestack.net/t/client-dll-not-found-error-when-building-blazor-wasm-template-with-visual-studio-2022/10447/3
and
https://docs.servicestack.net/myget#clear-nuget-package-cache

Problem was my nuget packages as it says

**Comment by kouroshsalahshoor** [comment]
The project was built once and I could run the application
But the error came back again as soon as I build the solution again!!!
