### ISSUE TITLE
Exception: Correlation failed. Unknown location

### ISSUE THREAD

**Issue by amulani2023** [dotnet/aspnetcore#48041]
I am getting below error after authenticating to AAD. Could you please help me to resolve this issue. 

Exception: An error was encountered while handling the remote login

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext 
```

Here is the details about my Application:

We have an .Net 7 App working good with Azure AD with App Service url. However, when we setup a Application Gateway infront of App Service, we are getting corelation failed- unknown location.

We have registered the app on the Gateway, and, once logged in with Azure AD, we are getting corelation failed- unknown location.
In the AAD app registration we tried with both redirct url : (app service.microsoft.net/signin-oidc and applicationgateway.microsoftdomain.net/signin-oidc)

We are using MSAL for authentication with below code:

```
builder.Services.AddMicrosoftIdentityWebAppAuthentication(configuration:builder.Configuration, "AzureAD",
    OpenIdConnectDefaults.AuthenticationScheme
    )
    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddInMemoryTokenCaches();
```

Also we have added the cookies before authentication code:

```
builder.Services.Configure<CookiePolicyOptions>(options =>
{
    options.Secure = CookieSecurePolicy.Always;
});
```

also added the cookies setting before routing:

```
app.UseCookiePolicy(new CookiePolicyOptions()
{
    MinimumSameSitePolicy = SameSiteMode.None
});
```

Authentication is done via client secret and application gateway has certificate.

Could you please help us to resolve this issue.

**Comment by Tratcher** [comment]
This is usually a problem with cookies flowing correctly. See these troubleshooting steps about getting the app configured to run behind a proxy/gateway:
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0#troubleshoot
In this case, you'll want to make sure the request scheme is updated correctly.
