### ISSUE TITLE
[blazor][wasm] Remaining legacy interop

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/aspnetcore#48042]
Below is list of usages of legacy interop.

- [x] Usage of `BINDING.call_assembly_entry_point`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68
   - this one is most problematic because it uses `eval()` which is [CSP blocker](https://github.com/dotnet/aspnetcore/issues/37787)
- [ ] Usage of `BINDING.js_string_to_mono_string` in `invokeJSFromDotNet`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Boot.WebAssembly.ts#L124
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Boot.WebAssembly.ts#L138
   - this is potentially just dead code, if the user code doesn't use the obsolete `IJSUnmarshalledRuntime`
   - but I don't fully understand `jsCallDispatcher` and `invokeJSJson` use-cases
- [ ] usage of `BINDING.unbox_mono_obj` and `BINDING.conv_string` in `readStringField` which is part of `renderBatch`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L127
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L138
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L142
   - this is problematic from GC safety, for which we do have stop-gap solution.
   - this is probably not a problem for CSP as there is no bind/invoke and no `eval()`
- [x] `MonoHeapLock.stringCache` is pointer hazard
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L139
   - because `BINDING.conv_string` is already caching interned strings by their pointer (because they never move on GC)
   - any other strings do move and could be even collected, so the pointer could be pointing at different object and produce a) invalid value or b) crash even in single threaded app
   - this is problematic from MT GC safety, for which we do have stop-gap solution.

All of the uses prevent users trimming legacy interop dead code with `<WasmEnableLegacyJsInterop>false</WasmEnableLegacyJsInterop>`

**Comment by javiercn** [comment]
There seems to be some work to be done still here, is that correct @pavelsavara?

/cc: @maraf (in case you know)

**Comment by pavelsavara** [comment]
Yes, there is. 
`renderBatch` part of it could be related to how we solve [multi-threading](https://github.com/dotnet/designs/pull/301).
