### ISSUE TITLE
SignalR.Npm.FunctionalTests.npmproj fail on Fedora 37+

### ISSUE THREAD

**Issue by tmds** [dotnet/aspnetcore#48040]
This test project fails when I run it on Fedora. At the end of the build log I see this:
```
Build FAILED.

(node : 134897) error : Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
(node : 134897) error : Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
(node : 134898) error : Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
(node : 134898) error : Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
*** SPEC STARTED : connection with FetchHttpClient contains server response in error [2023-05-03T07: 48:22.050Z] *** [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
*** SPEC DONE : connection with FetchHttpClient contains server response in error [2023-05-03T07: 48:22.059Z; Duration: 9ms] *** [/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj]
/home/tmds/repos/aspnetcore/src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj(24,5): error : Command failed with exit code 1.
/home/tmds/repos/aspnetcore/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23226.4/tools/Build.proj(267,5): error MSB4181: The "MSBuild" task returned false but did not log an error.

```

Because of the `NODE_TLS_REJECT_UNAUTHORIZED` mention, it could be related to:
https://github.com/dotnet/aspnetcore/blob/9c38b3749a69050e0670b8750d9828cf47a19b41/src/SignalR/clients/ts/FunctionalTests/scripts/run-tests.ts#L216-L229

As part of the test log I also see:
```
FAIL ts/HubConnectionTests.ts (8.189 s)
...
  Test Suites: 1 failed, 3 passed, 4 total
  Tests:       3 failed, 5 skipped, 152 passed, 160 total
```

This is the full test log: [test.log](https://github.com/dotnet/aspnetcore/files/11380556/test.log)

@BrennanConroy can you help me figure out what the issue is?

**Comment by tmds** [comment]
cc @omajid

**Comment by BrennanConroy** [comment]
You can ignore the TLS warning, they are just warnings, but show up annoyingly when an error occurs.

The real failures are at the bottom, all three are mostly the same test:
```
hubConnection › over WebSockets transport › preserves cookies between requests
expect(received).toEqual(expected) // deep equality
  
      Expected: "testValue"
      Received: null
  
        678 |                     const cookieValue = await hubConnection.invoke<string>("GetCookie", "testCookie");
        679 |                     const cookieValue2 = await hubConnection.invoke<string>("GetCookie", "testCookie2");
      > 680 |                     expect(cookieValue).toEqual("testValue");
            |                                         ^
        681 |                     expect(cookieValue2).toEqual("testValue2");
        682 |                     await hubConnection.stop();
        683 |                 });
  
        at Object.toEqual (ts/HubConnectionTests.ts:680:41)
```

These are tests that make sure we handle cookies correctly in Node. Generally if they failed I would have expected there to be a browser update that broke a subtle behavior with cookies like has happened in the past... not sure why they would fail on Node though.

**Comment by tmds** [comment]
> These are tests that make sure we handle cookies correctly in Node. Generally if they failed I would have expected there to be a browser update that broke a subtle behavior with cookies like has happened in the past... not sure why they would fail on Node though.

It may have regressed in Node 18.
I don't see a failure with Node 16 on RHEL 9.

@BrennanConroy can you debug this further?

**Comment by BrennanConroy** [comment]
Not without a repro environment

**Comment by tmds** [comment]
Can you try if it reproduces for you if you install node 18?

**Comment by BrennanConroy** [comment]
Looks like in Node 18 they added `fetch` to the global scope by default:
https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental

In non-browser environments we explicitly add a cookie jar to fetch since we need to be able to forward the cookies to websocket requests, but our detection logic relied on `fetch` not being defined, so we need to update it to check for being in a node environment as well.

**Comment by omajid** [comment]
Hey folks. Is nodejs 18 an environment that's being used/tested/validated/suggested for aspnetcore? Would you encourage users to be using that? I ask because [16 reaches EOL later this year](https://nodejs.org/en/blog/announcements/nodejs16-eol) and 18 is listed the current LTS version at https://nodejs.org/en/download

**Comment by BrennanConroy** [comment]
> Is nodejs 18 an environment that's being used/tested/validated/suggested for aspnetcore?

Done via https://github.com/dotnet/aspnetcore/pull/48087
