### ISSUE TITLE
Add ability to Set the Log Level on an ErrorBoundary

### ISSUE THREAD

**Issue by mtavares628** [dotnet/aspnetcore#48048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, when using an ErrorBoundary in Blazor Server, the exeption is sent to the IErrorBoundaryLogger interface which is different based on the client.  Blazor Server uses RemoteErrorBoundaryLogger to log the exception.  The LogAsync call actually logs the exception as a warning instead of an error:

```c#
public ValueTask LogErrorAsync(Exception exception)
    {
        // We always log detailed information to the server-side log
        Log.ExceptionCaughtByErrorBoundary(_logger, exception.Message, exception);

        // We log to the client only if the browser is connected interactively, and even then
        // we may suppress the details
        var shouldLogToClient = (_jsRuntime as RemoteJSRuntime)?.IsInitialized == true;
        if (shouldLogToClient)
        {
            var message = _options.DetailedErrors
                ? exception.ToString()
                : $"For more details turn on detailed exceptions in '{nameof(CircuitOptions)}.{nameof(CircuitOptions.DetailedErrors)}'";
            return _jsRuntime.InvokeVoidAsync("console.error", message);
        }
        else
        {
            return ValueTask.CompletedTask;
        }
    }

    private static partial class Log
    {
        [LoggerMessage(100, LogLevel.Warning, "Unhandled exception rendering component: {Message}", EventName = "ExceptionCaughtByErrorBoundary")]
        public static partial void ExceptionCaughtByErrorBoundary(ILogger logger, string message, Exception exception);
    }
```

  This is actually inconsistent from the WebAssemblyErrorBoundaryLogger which logs the exception as an error:

```c#
public ValueTask LogErrorAsync(Exception exception)
    {
        // For, client-side code, all internal state is visible to the end user. We can just
        // log directly to the console.
        _errorBoundaryLogger.LogError(exception, exception.ToString());
        return ValueTask.CompletedTask;
    }
```

Personally, to me it makes more sense that every unhandled exception should be considered an error and not a warning, and it is causing my logger to have to filter at the Warning level instead of at the Error level. As a result, I end up logging a bunch of extraneous warnings that I don't want logged.
 
Further, because that class is internal, I can't subclass it to change the LogLevel

### Describe the solution you'd like

A quick fix would be to change all IErrorBoundaryLogger implementations to log as an error, and not a warning (It is called an ErrorBoundary after all).  

A more involved option would be to add a parameter to the ErrorBoundary to set the LogLevel for any exceptions that it handles.  Then the developer can determine how the exceptions should be logged.

I would also be interested in a work around that doesn't involve recreating the RemoteErrorBoundaryLogger from scratch.

**Comment by mkArtakMSFT** [comment]
After discussing this with the team we think that the major concern here is around the inconsistency of the log levels between server and client. We will move this to the backlog and come back to this in the future to decide how to move forward.

**Comment by SteveSandersonMS** [comment]
There are a couple of workaround options for you:

 * You can implement your own `IErrorBoundaryLogger` DI service, to receive the exception and implement any logging logic that you prefer
 * You can subclass `ErrorBoundary` and override its `OnErrorAsync` virtual method to implement any logging logic that you prefer

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
