### ISSUE TITLE
OnSubmit function on Form not working as expected

### ISSUE THREAD

**Issue by Edstub207** [dotnet/aspnetcore#48050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've tried various methods to try and get this to work and I'm stumped - All of them should have worked as far as I can tell and based on past experience too! I have a form in a .cshtml file, for website I've been working on, I expect the OnSubmit function to call SubmitForm. 

Whenever the form is submitted (No matter the code) it never calls the function SubmitForm, even though it exists and is referenced. This includes with.without the method=post etc.... 

My goal is to use the data from the form and creating a booking system from it. 

The form code is as follows (Screenshot as formatting broke when pasted)
![image](https://user-images.githubusercontent.com/13305475/235991983-940137dd-ba76-401a-b797-885d9f627d3d.png)

And the function SubmitForm() is the following at the moment (Just trying to get the form to work before I go further)

`    public void SubmitForm()
    {
        Console.Write("Blah");
        <h4>Hrrr</h4>
    }`

### Expected Behavior

When submitting the form, the form calls the SubmitForm() action 

### Steps To Reproduce

Create a form and notice the OnSubmit function never calls the C# function it references 

### .NET Version

6.0.408

### Anything else?

Rider 2023.1.1 and Windows.

**Comment by Flachdachs** [comment]
`onsubmit` is an event for `form`s, not for `button`s.

**Comment by Flachdachs** [comment]
Pressing the Enter key while an `input type=text` has the focus is also a valid way to submit a form.

The `submit` event is fired on the `form` element.  The `button` only fires a `click` event (simplified said). There are rules in HTML that certain actions will fire the submit event on the form. Clicking a `button type="submit"` that is located inside of a `form` is one of this actions. So you don't need an event handler on the button, but on the form.

Alternatively place a click event handler on the button. But that is a bad solution compared to the submit event handler on the form, because it restricts users to this button, excluding the other ways to submit the form.

**Comment by javiercn** [comment]
@Edstub207 thanks for contacting us.

That's not how Razor pages work. You need to create an `OnPost` method on your razor page to support the form. There is no magic way to bind the form from the page to a method that you define (as you seem to be doing)

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#write-a-basic-form

**Comment by Flachdachs** [comment]
It depends on what you want to do. Forms can be handled in basically two ways. The first is without Javascript. The browser creates a GET or POST request when the user does certain actions, like clicking a <button type=submit> (or the very old way <input type=submit>) or pressing enter key when an <input type=text> has the focus. In this case you only need a server-side handler that does something with the request. This is the straightforward way of handling forms.

If you want to achieve something more then you need Javascript. For instance you may want to have an additional client-side validation of the values before sending them to the server. (This is only to give the user immediately feedback, not as the only method to check validity. You need a server-side validation too in case Javascript is not enabled or not used (like bots)). You can intercept the submit procedure with an onsubmit handler attached to the form element. If you use eventObject.preventDefault() you can stop the browsers default behavior of submitting the form to the server.

> Do I specifically need to be in a .Razor file?

.Razor files are used in Blazor projects. Razor Pages projects use .cshtml files to do their stuff. .cshtml files are also used for the views of MVC projects.
