### ISSUE TITLE
Update AuthenticationService.js to refresh Blazor WASM user interface when user is logged out via check_session_iframe

### ISSUE THREAD

**Issue by acasciani** [dotnet/aspnetcore#48058]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using Blazor WASM, OAuth session logout notifications can be handled using `check_session_iframe` as supported by oidc-client and supported Identity Providers like [Identity Server](https://docs.duendesoftware.com/identityserver/v5/ui/logout/notification/#browser-based-javascript-clients). This OAuth functionality allows WASM tabs to be notified when the remote session at the Identity Provider is terminated and allows the WASM to log the user out. The default AuthenticationService.js implementation in asp.net core supports this functionality and the check session iFrame is working as expected. However, when the AuthenticationService.js notices that the session has been terminated through the JS interop, it does not update the UI. Instead the user is still shown an interface that appears as if they are logged in.

### Describe the solution you'd like

An ideal solution would be to support the native oidc-client events like `userUnloaded` with the `addUserUnloaded(...)` function. Doing this would allow us to redirect the user as the WASM application deems necessary. We cannot use back channel notifications at this time so having the ability to use the check session front channel is the only path forward. We are also open to other approaches to achieve this if you have any suggestions.

We are also open to contributing to the asp.net core AuthenticationService.ts to support specifying custom callbacks on the native oidc-client events. If we wrote this feature and opened a PR, would asp.net core be open to  merge that into the code base?

### Additional context

I'm attaching a video screenshot of the current series of calls as well as one solution we used by adding the `userUnloaded` call. If you would be open to accepting a PR for this, we could look to make this more generic to use callbacks.

This screenshot has a demo Blazor WASM app, an IdentityServer Identity Provider, and a second client. The user is logged into the WASM and the second client through the IdP. The user then logs out of the second client which triggers the WASM to log the user out and update the user interface, given the new code that we have added to AuthenticationService.js. We'd like to see something like this functionality introduced into the asp.net core code base.

And to clarify, at the 0:44 mark in the video, without our code changes to redirect, the WASM app still shows the user as being logged in on the UI.

https://user-images.githubusercontent.com/839122/236086271-7172bd00-8bd4-4b45-b4e9-5ac51c5bc484.mp4

**Comment by mkArtakMSFT** [comment]
@halter73 I think this is something we should treat as an enhancement instead of a bug. What do you think?

**Comment by SteveSandersonMS** [comment]
@halter73 plans to investigate before we triage this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
