### ISSUE TITLE
can i set logger file encoding when stdoutLogEnabled="true"

### ISSUE THREAD

**Issue by coader** [dotnet/aspnetcore#48069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

when output message with unicode to logger file, will show ??????

### Describe the solution you'd like

stdoutLogEncoding="utf-8"

**Comment by amcasey** [comment]
@coader Thanks for reaching out!  The stdout log is intended for only the most basic debugging scenarios.  For anything fancier, you'll want to use a [logging provider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#third-party-logging-providers).
