### ISSUE TITLE
Memory leak when using RenderFragment in Blazor component

### ISSUE THREAD

**Issue by alansangeeths** [dotnet/aspnetcore#48063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Create a razor component with RenderFragment ChildContent.

// Component1.razor
<div>

    @ChildContent
    HelloThis
</div>

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}

2. Use this component in another simple one.
//Component2.razor

<Component1>
    Main Parent
</Component1>

3. Now when i use this Component2 in my sample, memory snapshot shows as static variable retained in memory after navigated away to another page.

![image](https://user-images.githubusercontent.com/92983079/236135778-0354fe96-a737-42cc-92e8-c8ef2b7cce8b.png)

### Steps To Reproduce

1. Create a razor component with RenderFragment ChildContent.

// Component1.razor
<div>

    @ChildContent
    HelloThis
</div>

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}

2. Use this component in another simple one.
//Component2.razor

<Component1>
    Main Parent
</Component1>

3. Now when i use this Component2 in my sample, memory snapshot shows as static variable retained in memory after navigated away to another page.

![image](https://user-images.githubusercontent.com/92983079/236135778-0354fe96-a737-42cc-92e8-c8ef2b7cce8b.png)

### .NET Version

7.0.202

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

Can you please look through this comment and its references and see if addresses your concerns: https://github.com/dotnet/aspnetcore/issues/47351#issuecomment-1479163436
