### ISSUE TITLE
High number of SignalR requests compared with rest of application

### ISSUE THREAD

**Issue by simongoldstone** [dotnet/aspnetcore#48080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have an ASP.NET MVC .NET 7 app running on Azure App Services. The app supports around 50-60 concurrent users in a typical day. Users will stay logged in for hours, as this is a line-of-business application.

The application is scaled out to two instances and we use Redis as the backplane for SignalR.

In Application Insights, we're seeing a huge number of requests for SignalR compared with the rest of our app. For example, in a 10 minute period today, we saw over 21,000 requests compared with just 4-500 requests for normal MVC actions.

Is this normal? Seems very wrong to us.

I should add that we're not even very SignalR heavy, we just use it for Toasts and a few basic UI updates.

See screenshot:

![image](https://user-images.githubusercontent.com/5681879/236329126-6d4dfe0e-5249-4828-a827-738478b2433a.png)

If this is normal, please explain. We may have 50-60 users, and they may have a couple of tabs open, so I supposed you might argue there are, say, 150 connections at any one time. But the number of requests still seems ridiculous.

If this is not normal, what can be causing this level? What's the best way to diagnose/trace this traffic to see where it's coming from?

Original StackOverflow report is here: 
https://stackoverflow.com/questions/76175415/high-number-of-signalr-requests-compared-to-rest-of-application

### Expected Behavior

I would expect considerably less requests that the number I'm experiencing in my app.

### .NET Version

7.0.203

### Anything else?

.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.116 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by BrennanConroy** [comment]
Looks like you aren't using WebSockets. If you were the /hubs/global/negotiate and /hubs/global endpoints would have roughly the same number of requests.

**Comment by simongoldstone** [comment]
> Looks like you aren't using WebSockets. If you were the /hubs/global/negotiate and /hubs/global endpoints would have roughly the same number of requests.

Thanks. I have `app.UseWebSockets();` in my Startup.cs. What am I missing? Is there some specific SignalR config I need?

**Comment by BrennanConroy** [comment]
If you're using Azure App Service you need to turn on websockets
https://learn.microsoft.com/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-7.0#configure-the-app-in-azure-app-service

If you're using IIS you also need to turn on websockets
https://learn.microsoft.com/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#enabling-websockets-on-iis

If you use nginx
https://learn.microsoft.com/aspnet/core/signalr/scale?view=aspnetcore-7.0#linux-with-nginx

**Comment by simongoldstone** [comment]
Ok, done that thanks. Never spotted that on App Service, good shout. However, with regards to the large number of requests in comparison to the rest of the app, is this normal behavio(u)r?

**Comment by BrennanConroy** [comment]
Depends on how you wrote your app. Can't really answer given the info above.
If the users connection closes and starts whenever they go to new pages in your site, then they can potentially create a lot of requests.

**Comment by simongoldstone** [comment]
Yes, it's a standard controller-action app, not an SPA. So it does need to re-establish the connection on each page. It's just that when the user navigates to, say, /routeabc I see that in application insights as a single request, but the signalr connection requests are like 50:1. But if that's normal then fair enough. Thanks for your assistance.
