### ISSUE TITLE
ANCM 2.2 In-Process Restart Issue

### ISSUE THREAD

**Issue by rockerinthelocker** [dotnet/aspnetcore#4808]
Adding/Removing an application to/from ```<fastCgi>``` (applicationHost.config) restarts ASP.NET Core applications.

**Comment by anurse** [comment]
Possibly related to https://github.com/aspnet/AspNetCore/issues/8775

**Comment by anurse** [comment]
We did add a hook to reload on global config changes. We'll look at what we can do to improve this.

**Comment by jkotalik** [comment]
I don't think is something we are going to change at this point, based on customer feedback. Closing; feel free to reopen if you are blocked by this or want this feature.
