### ISSUE TITLE
Prevent onkeydown event with condition.

### ISSUE THREAD

**Issue by Planit-Scheduler-Solutions** [dotnet/aspnetcore#48113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HI I need be possible to block the browser CTRL+F default event, and run some my custom logic instead.
My Code:
```
<div  @onkeydown="(args) => KeyHandle(args)"
         @onkeydown:preventDefault="PreventKeyDown">

          Some elements...
</div>
 ````
Razor File:

CS File:

  ```
public bool PreventKeyDown { get; set; } = false;
      
        private void KeyHandle(KeyboardEventArgs keyboardEvent)
        {
            PreventKeyDown = false;

            if (!keyboardEvent.Repeat)
            {
 if (keyboardEvent.CtrlKey && keyboardEvent.Code == "KeyF")
                {
                    PreventKeyDown = true;
                    Some logic...
                }
            }
}
```
        

This block is not working but if I not use the prevent with parameter like this:
 
  ```<div class="planit-table-wrapper"
         @onkeydown="(args) => KeyHandle(args)"
         @onkeydown:preventDefault="true">

Some elements...
</div>```

It works and block the event but in this way blocks all event and I want to block only the CTRL+F.

How can I solve that issue(prevent only CTRL+F event)?

### Expected Behavior

If you press CTLS+F search should not become visible.

### Steps To Reproduce

Enter the code as in the description and press CTRL+F.

### Exceptions (if any)

_No response_

### .NET Version

6.0.401

### Anything else?

_No response_

**Comment by Flachdachs** [comment]
I just found https://github.com/dotnet/aspnetcore/issues/45949 that explains why this is not possible. Event handling in Javascript is synchronous. When using await in a JS event handler the rest of the handler function is executed later, but the event continues in the meantime.

**Comment by SteveSandersonMS** [comment]
If your goal is just to block certain keystrokes, it's much easier than the list of steps above. You can just reference a JS event handler directly from your element - it's very straightforwards.

Here's a runnable example: https://blazorrepl.telerik.com/QnuzOtFr04ZL1crR57

**Comment by Flachdachs** [comment]
My goal is not to just block, but to react on certain keys and prevent the default behavior. In particular changing to the previous or next tab of a tab panel using the cursor keys, but prevent that the browser scrolls on cursor up and down keys.

**Comment by Planit-Scheduler-Solutions** [comment]
My goal is also not only block the browser default behavior, In my case CTRL+F open dialog with my custom search component with custom behavior.

**Comment by SteveSandersonMS** [comment]
It sounds like you can do that using the techniques described here. You can use a JS event handler to block arbitrary events and optionally use a separate .NET event handler to implement custom behavior.

**Comment by Planit-Scheduler-Solutions** [comment]
Thanks, works great for me. (I apply as in the example).

**Comment by mkArtakMSFT** [comment]
Closing, as it seems the provided suggestion by @SteveSandersonMS was good enough to address the immediate concern, and the remaining work is already tracked by https://github.com/dotnet/aspnetcore/issues/45949
