### ISSUE TITLE
Better story for multiple instance of dependency injection

### ISSUE THREAD

**Issue by abratvisma** [dotnet/aspnetcore#48110]
## Summary

Dependency injection in asp.net core only work for one type of instance.

## Motivation and goals

Bitten by this issue https://github.com/dotnet/extensions/issues/2802
I would like to be able to have multiple IDistributedCache

My own repo use IDistributedCache
Third party library also use IDistributedCache
Boom conflict

The workaround is to create interface and class that inherit IDistributedCache which become annoying

## Examples
```
[DependencyInjectionResolver(InstanceName="01")]
private readonly IDistributedCache cache01;

[DependencyInjectionResolver(InstanceName="02")]
private readonly IDistributedCache cache02;

//not to be confused with InstanceName in RedisOption
builder.Services.AddStackExchangeRedisCache(new(){},new DependencyInjectionResolver(){ InstanceName="01"});
builder.Services.AddStackExchangeRedisCache(new(){},new DependencyInjectionResolver(){ InstanceName="02"});

builder.Services.AddTransient<IABC, ABC>(o=>new ABC(),new DependencyInjectionResolver(){ InstanceName=nameof(ABC)});
builder.Services.AddTransient<IABC, ABC2>(o=>new ABC2(),new DependencyInjectionResolver(){ InstanceName=nameof(ABC2)});

[DependencyInjectionResolver(InstanceName=nameof(ABC))]
private readonly IABC abc1;

[DependencyInjectionResolver(InstanceName=nameof(ABC2))]
private readonly IABC abc2;
```

**Comment by abratvisma** [comment]
Sample over here https://www.infoworld.com/article/3597989/use-multiple-implementations-of-an-interface-in-aspnet-core.html will only work for different type same interface

what i need is same type same interface different configuration
Its the same RedisCache but different InstanceName

```
builder.Services.AddTransient<IABC, ABC>(o=>new ABC("Config01"),new DependencyInjectionResolver(){ InstanceName="ABC1"});
builder.Services.AddTransient<IABC, ABC>(o=>new ABC("Config02"),new DependencyInjectionResolver(){ InstanceName="ABC2"});

[DependencyInjectionResolver(InstanceName="ABC1")]
private readonly IABC abc1;

[DependencyInjectionResolver(InstanceName="ABC2")]
private readonly IABC abc2;
```

**Comment by davidfowl** [comment]
See https://github.com/dotnet/runtime/issues/64427, closing this as a duplicate
