### ISSUE TITLE
Custom InputText has a null ElementReference

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#48115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If one creates a Custom EditText like this (called InputTextUppercase.razor)

`@inherits InputText

<input @attributes="AdditionalAttributes"
       class="@CssClass"
       value="@CurrentValue"
       @oninput="EventCallback.Factory.CreateBinder<string>(
        this, __value => CurrentValueAsString = __value?.ToUpper(), CurrentValueAsString?.ToUpper())" />`

then use it like this:

                        <InputTextUppercase class="form-control defaultFocus" @bind-Value="_find_customer.initials" style="text-transform:uppercase" placeholder="INITIALS" @ref=inputTextForFocus />

then the Element field (of type ElementReference) will be null in OnAfterRenderAsync meaning that FocusAsync() fails in:

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
            if (inputTextForFocus.Element.HasValue)
                await inputTextForFocus.Element.Value.FocusAsync();
    }

How do we get the inherited component to set the ElementReference to that FocusAsync wil work like it does in InputText?

Thanks

### Expected Behavior

An Inherited Control should be setting the ElementReference so that behaviors are the for the child

### Steps To Reproduce

See the description above

### .NET Version

7.0

**Comment by Flachdachs** [comment]
You need to add a `@ref="Element"` to your `<input...>` element. The interited InputText isn't able to set this, because it has no access to your implementation. InputText initializes `Element`  in `BuildRenderTree`, which is overriden with your Razor code.
