### ISSUE TITLE
Crash issue with SignalR-Client-CPP  ， Help me

### ISSUE THREAD

**Issue by walmt** [dotnet/aspnetcore#48139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using SignalR client library in C++ with Qt to communicate with our company's C# server. I encounter a segmentation fault in some cases when using the following code:

Code:

```
auto nativeConfig = signalr::signalr_client_config();
signalr::signalr_client_config nativeConfig;
alltoken="Bearer "+token;
nativeConfig.get_http_headers().emplace( "Authorization", alltoken);
connection->set_client_config( nativeConfig );
```

When I run the code in debug mode on Linux x86, there is no problem, but once I switch to release mode, it crashes after the segmentation fault occurs in set_client_config. I disabled compiler optimization and then it runs normally in release mode.

However, now I compile this code on ARM, and regardless of whether it's in debug or release mode and whether the compiler optimization is disabled, it still results in a segmentation fault. That is why I am requesting your help!

### Expected Behavior

I want to be able to run this code without any issues and maintain a stable long connection.

**Comment by walmt** [comment]
> Does it still seg fault if you remove
> 
> ```
> alltoken="Bearer "+token;
> nativeConfig.get_http_headers().emplace( "Authorization", alltoken);
> ```
> 
> Have you made sure you build the SignalR library with the same compiler version as your project that uses the library?


"You're right, once I deleted those, he should be able to work normally. But why was this happening? I didn't have this issue on my previous device. How should I proceed to perform the same actions as when I deleted the code?"

**Comment by BrennanConroy** [comment]
> But why was this happening?

That usually means you built SignalR with a different compiler than you used to build your library. This can result in a different memory layout of objects like `std::string`, so when you pass a string created from your library (the `"Bearer " + token` code) to the SignalR library, it can result in undefined behavior.

**Comment by walmt** [comment]
> > But why was this happening?
> 
> That usually means you built SignalR with a different compiler than you used to build your library. This can result in a different memory layout of objects like `std::string`, so when you pass a string created from your library (the `"Bearer " + token` code) to the SignalR library, it can result in undefined behavior.

"Thank you!! I tried the code below and had no issues. I think the problem with this code was caused by the difference in compilers.

auto& headers = nativeConfig.get_http_headers();
headers.emplace("Authorization", alltoken);"

**Comment by walmt** [comment]
"I think it might be an issue with compiler optimization. What do you think?

Previously, this line of code had no problem running on debug in X86. However, when it was run on Release, it caused issues because the compiler optimization was turned off. But on ARM platform, even with optimization turned off, it still couldn't run. When I separated this line of code into its own operation, it finally ran successfully."
