### ISSUE TITLE
Adding Blazor WebAssembly project reference breaks Hot Reloading for Razor pages

### ISSUE THREAD

**Issue by jsheely** [dotnet/aspnetcore#48132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Simply adding a reference from a Razor pages project to a blazor wasm project will break razor pages ability to hot reload the page. 

It appears that the `Microsoft.NET.Sdk.BlazorWebAssembly` project reference is doing something that hijacks the hot reloading

Two notable differences
- When project reference is added you can see the blazor checkmark icon appears in the upper right that was not there before adding the project reference. Likely caused by something in the `_framework/aspnetcore-browser-refresh.js` code but there does not appear to be an easy way to override this logic and keep hot reloading working. See: https://github.com/dotnet/aspnetcore/issues/44805
- The `dotnet watch` terminal output changes

**Before**
```
dotnet watch ⌚ File changed: ./Pages/Index.cshtml.
dotnet watch 🔥 Hot reload of changes succeeded.
```
**After**
```
dotnet watch ⌚ File changed: ./Pages/Index.cshtml.
dotnet watch ⌚ No hot reload changes to apply.
```

I've created a demo repo. Simply add the un-comment the project reference in the `RazorPages1.csproj` for the `wasm.csproj` and change something in the Razor Index.cshtml before and after the reference change

Using `dotnet watch` and I also tried `dotnet watch --project .` because I saw that somewhere during debugging

### Expected Behavior

I expect that changing the Razor Index.cshtml would hot reload the page just as it did before the web assembly project reference was added.

### Steps To Reproduce

- Clone Repo https://github.com/jsheely/HotReloading-Razor-Blazor
- Run `dotnet watch` in the Server folder
- Change title in Index.cshtml
- (See hot reloading working)
- Add project reference to wasm.csproj in the Server csproj
- Change title in Index.cshtml
- (See hot reload NOT working)

### Exceptions (if any)

No exceptions

### .NET Version

8.0.100-preview.3.23178.7

### Anything else?

I've tried this with .net 7 with the same result.

The goal of this is to create a template that has support for Server side static rendering with "Blazor Pockets" of interactivity for either the Blazor Server or Blazor Wasm in any pocket chosen. Both environments supporting hot reloading.

**Comment by mkArtakMSFT** [comment]
@tmat can you please investigate this? Seems like a regression.

**Comment by jsheely** [comment]
While I still think this may be important to have this option for folks migrating from Razor to Blazor. 

I believe the roadmap plan that @danroth27 has illustrated in the [Blazor Community Standup .net 8 updates](https://www.youtube.com/watch?v=MaLjiR9YSbs) solves my end goals.

I just want to mix server and client components using the same programming model

**Comment by tmat** [comment]
@jsheely What do you mean by Hot Reload "not working" in the last step?

I tried to repro updating the project to include the project reference while `dotnet watch` was running and it requested app restart:

```
dotnet watch ⌚ File changed: .\RazorPages1.csproj.
  ❔ Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
  ❔ y
```

After restarting changes I made to Index.cshtml were applied correctly.

Do you mean that Hot Reload shouldn't restart the app when project changes?
