### ISSUE TITLE
IJSObjectReference.InvokeAsync crashes when returning large data

### ISSUE THREAD

**Issue by SviatoslavRazmyslov** [dotnet/aspnetcore#48142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AspNetCore 7.0.5
Blazor Server App

Here is small C# class:

```
public partial class Index
{
    [Inject]
    public IJSRuntime JSRuntime { get; set; } = default!;
    public IJSObjectReference JSModule { get; set; } = default!;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            JSModule = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./Pages/Index.razor.js");
        }
    }

    private async void Foo()
    {
        try
        {
            var t = await JSModule.InvokeAsync<object>("returnValue", null);
            Debugger.Break();
        }
        catch (JSException ex)
        {
            Debugger.Break();
        }
        catch (Exception ex)
        {
            Debugger.Break();
        }
    }
}
```

and JS functions:

```
function makeid(length) {
    let result = '';
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const charactersLength = characters.length;
    let counter = 0;
    while (counter < length) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
        counter += 1;
    }
    return result;
}

export async function returnValue() {

    return makeid(50000);
}
```

`JSModule.InvokeAsync` can't return string longer than about 30000 characters. JS works fine with long strings, but `JSModule.InvokeAsync` throws exception "A task was canceled." when returning that.

### Steps To Reproduce

Run the code above in Blazor Server App.

### Exceptions (if any)

"A task was canceled."
"   at System.Threading.Tasks.ValueTask`1.get_Result()\n   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()\n   at System.Threading.Tasks.ValueTask`1.get_Result()\n   at PServer.Pages.Index.<InsertParagraph>d__9.MoveNext() in /.../Dev/PServer/PServer/Pages/Index.razor.cs:line 37"

### .NET Version

7.0.203

### Anything else?

NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

**Comment by Flachdachs** [comment]
See

[Call JS from .NET -> Size limits on JavaScript interop calls](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#size-limits-on-javascript-interop-calls)

or

[Call .NET from JS -> Size limits on JavaScript interop calls](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0#size-limits-on-javascript-interop-calls)

**Comment by SviatoslavRazmyslov** [comment]
@Flachdachs, @javiercn,

Thank you for the good advices!
