### ISSUE TITLE
Build fails with node 20

### ISSUE THREAD

**Issue by tmds** [dotnet/aspnetcore#48146]
```
error eslint-plugin-jsdoc@39.9.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.1.0"
```

Node 20 is supported from eslint-plugin-jsdoc 43.0.5+.

cc @BrennanConroy

**Comment by wtgodbe** [comment]
@tmds is this just building from the command line w/ node 20 installed? The current LTS is 18, could you try using that version? It will take us a bit of time to get everything working w/ `20`.

**Comment by tmds** [comment]
@wtgodbe yes, this is for building with Node 20. Node 20 is used in our CI job for the upcoming Fedora 39.
Fedora 39 is planned for October 23. This isn't urgent.

**Comment by tmds** [comment]
cc @omajid

**Comment by amcasey** [comment]
@wtgodbe @BrennanConroy Where are we on node 20?  It's past Oct 23.

**Comment by wtgodbe** [comment]
I haven't had time to work on that yet, @BrennanConroy have you looked at it at all?

**Comment by javiercn** [comment]
I also ran into this and fixed it a few weeks ago.

I'm using node 20.10.0 and I'm able to build just fine 

https://github.com/dotnet/aspnetcore/commit/f913eac8f3d6082f45dffe0d5caa5f5f723ab90a
