### ISSUE TITLE
AddSignalR ClientTimeoutInterval doesn't work

### ISSUE THREAD

**Issue by devsienko** [dotnet/aspnetcore#48147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an Asp.Net Core 6 Web Api project. I add SignalR middleware:

`builder.Services.AddSignalR(options =>
{
    options.ClientTimeoutInterval = TimeSpan.FromSeconds(7);
});
`

I add a handler:

`app.MapConnectionHandler<SocialWeatherConnectionHandler>("/weather");
`

When I turn off client internet connection I don't get any notifications/exceptions. It seem I don't have any way to know whether my client is alive or not.

P.S. When I just close an mobile app or a browser tab I can track it.

### Expected Behavior

To get an expection or something like that.

### Steps To Reproduce

1. Create a simple Asp.Net Core 6 Web Api application.
2. Add the SignalR middleware:

`builder.Services.AddSignalR(options =>
{
    options.ClientTimeoutInterval = TimeSpan.FromSeconds(7);
});
`

3. Add a simple handler:

`app.MapConnectionHandler<SocialWeatherConnectionHandler>("/weather");`

4. Use any web client to connect to the server application by WebSocket on a different machine. After you connect to the server turn off internet connectoin on the client machine.

5. Nothing happens on the server side.

You can use client from https://github.com/aspnet/SignalR/tree/master/samples/SocialWeather/wwwroot/index.html as well as SocialWeatherConnectionHandler.

### .NET Version

net6.0

**Comment by BrennanConroy** [comment]
ConnectionHandlers are at a layer beneath SignalR. In other words, any SignalR feature (e.g. `AddSignalR`) will not apply to `ConnectionHandler` usage.

**Comment by BrennanConroy** [comment]
> So does it mean that if we use SignalR with bare WebSocket we don't have built in way to detect that client lost internet connection?

I think you misspoke. If you **don't** use SignalR you don't have a built in way to detect lost connections.
