### ISSUE TITLE
Aspnet core webhook

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/aspnetcore#48153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there any plans to have stable version of webhook implementation targeting dotnet core. I'm seeing a release candidate version published some time back but no stable version or recent updates available. Not sure if I'm missing anything.

### Describe the solution you'd like

If there are plans to support webhook in dotnet core then can we have stable versions available.

**Comment by davidfowl** [comment]
> Is there any plans to have stable version of webhook implementation targeting dotnet core. I'm seeing a release candidate version published some time back but no stable version or recent updates available. Not sure if I'm missing anything.


No there are no plans to bring back the web hooks framework. It's currently part of the labs repository https://github.com/aspnet/AspLabs/tree/main/src/WebHooks.
