### ISSUE TITLE
Manual output cache busting?

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#4815]
_From @SimonOrdo on February 19, 2016 15:47_

Is there any way to clear/flush/remove OutputCache? 

I have html fragments in a partial view that uses the output cache like so

```
 <cache vary-by="@Util.SomeID" expires-after="@TimeSpan.FromHours(1)">
     <div>some content</div>
 </cache>
```

In the event that I need the content to be updated before the expiration of the cache, how do I go about busting the cache for that particular fragment (or the entire cache, if necessary) ?

_Copied from original issue: aspnet/Caching#154_

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
