### ISSUE TITLE
SignalR Onconnected when using Hubs with Websockets

### ISSUE THREAD

**Issue by TristanBoland** [dotnet/aspnetcore#48158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have the following architecture:

1. AspNetCore (.NET6) service with a hub. This hub can receive messages and sends messages to the client.
2. Client, an embedded device that uses plain websockets to connect to our hub. (A third party implemented the SignalR protocol on the embedded device)

What we notice is, when setting up the connection. The Onconnected method in our hub triggers, messages can be delivered and received realtime just fine.

But in some occasions when a reconnect or connect occurs we do not receive the OnConnected event. 
(We have tried to reproduce this issue by connecting the embedded device to a local machine running the service locally. But this has so far not yielded any results).

We can see the connection is still online because we are still receiving a message every 10 seconds on the Metrics hub method from the device.
But the onconnected method hasn't run, so our application does not consider it "Connected" in our cache.

### Expected Behavior

We expect the OnConnected method to be called when a Client reconnects / connects to our hub.

### Exceptions (if any)

We are not seeing any Exceptions in our Application Insights instance.

### .NET Version

6

**Comment by BrennanConroy** [comment]
> in some occasions when a reconnect or connect occurs we do not receive the OnConnected event.

I will be blunt and say, this is not possible. The code in SignalR is effectively:
```c#
try
{
    list.Add(connection); // now connection can recieve messages
    await Hub.OnConnectedAsync();
    // ...
}
catch
{
    list.Remove(connection);
}
```
The only way you could look connected and not have `OnConnectedAsync` called is in that small window between the connection being added to the list and `OnConnectedAsync` being called. Having said that, if you have slow/long-running code in a [Hub filter](https://learn.microsoft.com/aspnet/core/signalr/hub-filters?view=aspnetcore-7.0#create-hub-filters) or in your `OnConnectedAsync` method then you can increase the duration of that window.

Additionally, the server wont process messages from the client during that time, only after `OnConnectedAsync` returns will the server start reading from the client.

There is one case I know of where `OnConnectedAsync` might intermittently be called. See https://github.com/dotnet/aspnetcore/issues/40465, it involves using the Azure SignalR Service and an obsoleted mode.

If you are scaled out to multiple app instances you might also have the client connect to a new instance on reconnect, so if you're only monitoring one app and expected the client to show up there it might not.
