### ISSUE TITLE
Blazor WASM memory keep on increasing, GC not working as expected

### ISSUE THREAD

**Issue by harshbhadoria011** [dotnet/aspnetcore#48166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi All,

I've created a Blazor WASM application where I'm reading a file on the client and after processing the data, I'm populating data in data grid.

I'm reading file in memory stream, converted into byte array 

`byte[] byteArray = new byte[file.Size];`
`using (MemoryStream ms = new MemoryStream(byteArray, true))
{
await file.OpenReadStream(file.Size).CopyToAsync(ms); 
}
`

I took Memory Snapshot in Chrome and saw that 402 MB is consumed.

After processing of byteArray, I set it to NULL
`byteArray=null`

Question 1: Is GC supposed to release unused memory? even after calling GC.collect, nothing seems to be working/
Question 2: Why after 2GB+ memory consumption, my app is crashing?
Question 3: Is there any memory consumption limit in blazor wasm? if yes then what is the limit?

### Expected Behavior

I was expecting that GC to release memory held by byteArray and MemoryStream, but it keeps on growing.

### .NET Version

dotnet --version: 7

**Comment by javiercn** [comment]
@harshbhadoria011 thanks for contacting us.

Memory in webassembly applications can't shrink, otherwise it breaks the memory safety guarantees webassembly offers. The recommendation is that you avoid allocating large objects, since, the moment the memory grows, it can't shrink back (the runtime will use the memory when it becomes free, it just can't release it back)

**Comment by harshbhadoria011** [comment]
Hi @javiercn thanks for your reply.

I see that memory becomes free when I reload the page. 

You said, **(the runtime will use the memory when it becomes free, it just can't release it back)**. 
So, reloading the page is the only way of releasing the memory?

Also please provide your thoughts in below questions.

Question 1: Why after 2GB+ memory consumption, my app is crashing?
Question 2: Is there any memory consumption limit in blazor wasm? if yes then what is the limit?
Question 3: Does GC works in Blazor WASM? 

Regards, 
Harsh

**Comment by javiercn** [comment]
> Question 1: Why after 2GB+ memory consumption, my app is crashing?
Webassembly is 32 bit, so the max memory is 4GB, until new functionality in the spec removes the limitation.

>Question 2: Is there any memory consumption limit in blazor wasm? if yes then what is the limit?
The theoretical limit is 4GB, but practically it might be a bit less. The browser might decide to limit the amount of memory you are able to get, but I am not 100% sure on that.

> Question 3: Does GC works in Blazor WASM?
Yes, but GC means that the .NET runtime is able to reuse the memory once you have no references to an object, not "release it" back to the OS. This is a webassembly constraint, not a .NET constraint.
