### ISSUE TITLE
If InvariantGlobalization is enabled by default, SqlClient will throw an exception

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#48186]
Most applications will use EFCore or SqlCilent, and if `InvariantGlobalization` is enabled by default, SqlClient will throw an [exception](https://github.com/dotnet/SqlClient/issues/1913), although it is easy to remove `InvariantGlobalization`, But it always leaves users wondering

_Originally posted by @Varorbc in https://github.com/dotnet/aspnetcore/issues/47066#issuecomment-1543253995_

**Comment by mitchdenny** [comment]
What is the exception that is being thrown?

**Comment by mitchdenny** [comment]
OK, there isn't really anything for us to do here since this behavior in SqlClient appears to be by design.

**Comment by mitchdenny** [comment]
OK, I think the compromise position here could be to disable invariant mode when the project is created with out the ```--aot``` switch. The recent change we made here was really targeting native AOT scenarios where we might be willing to have people have to opt themselves out of invariant culture if they want to use SqlClient.
