### ISSUE TITLE
Use ArgumentException.ThrowIfNullOrWhitespace

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspnetcore#48185]
implemented in https://github.com/dotnet/runtime/pull/86007 and should flow here in a few days.

similar effort for ThrowIfNull https://github.com/dotnet/aspnetcore/issues/43482

there have been several of these throw helpers added in the core libraries this release, maybe there's others that are relevant to us. perhaps someone would like to take a look?

**Comment by amcasey** [comment]
We ended up concluding that was out of scope for our initial clean-up push since it required more coordination.  My personal feeling is that that probably wouldn't be an "area-" since (I understand) those labels are applied automatically.  I _have_ seen issues tagged with more than one area.  Alternatively, some cross-team pushes get prefix-less labels.

**Comment by danmoseley** [comment]
>  that probably wouldn't be an "area-" since (I understand) those labels are applied automatically

I have no opinion but FYI, that isn't a problem. dotnet/runtime has area-meta and it's predicted (probably with lower accuracy). @jeffhandley how well do you think that works -- thoughts about pros/cons of multiple area labels (which is forbidden in dotnet/runtime)?

**Comment by jeffhandley** [comment]
In dotnet/runtime, `area-meta` label works _okay_. It ends up being a "junk drawer" label to catch all things that span multiple areas, represent cross-area/cross-team epics, as well as epics and stories that span multiple repos.

Where its value surfaces is that it makes accountability clearer: No individual area owners are expected to track the `area-meta` issues; instead, the leads follow up on them. Getting those issues _out of the way_ for typical area ownership responsibilities helped the team.

**Comment by wcontayon** [comment]
@danmoseley can I submit a PR on that issue 🙂 ?

**Comment by danmoseley** [comment]
@wcontayon Go for it

**Comment by divyeshio** [comment]
Hi, I would like to work on this
