### ISSUE TITLE
add HelpUriLinks for generator errors

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspnetcore#48184]
https://github.com/dotnet/runtime/issues/85181 has details.

Might be easiest to do with a DiagnosticDescriptorHelper but need not. Agree with @gewarren what the URL format should be.

**Comment by danmoseley** [comment]
@captainsafia

**Comment by captainsafia** [comment]
Closing this. All links have been updated in the help messages and docs have been added to docs.microsoft.com.
