### ISSUE TITLE
Updating dotnet from 7.0.102 to 7.0.203 causes user creation failure looking for a non-existent package

### ISSUE THREAD

**Issue by dallas1287** [dotnet/aspnetcore#48199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When updating from dotnet 7.0.102 to 7.0.203 started getting this error when using the Identity.UserManager to create new users.
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.AspNetCore.Cryptography.KeyDerivation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'

very similar to this issue https://github.com/dotnet/aspnetcore/issues/41368 but this was supposedly fixed in 6.0.4 but this occurs when going to the very latest in dotnet 7

**Comment by Rick-Anderson** [comment]
Clear the NuGet package cache to ensure that you get the latest version of the packages. 

`dotnet nuget locals all --clear`

What do `dotnet --info` and `dotnet --list-sdks` show?

try reinstalling the `Microsoft.AspNetCore.Cryptography.KeyDerivation` . Remove the package from your project and then add it again.

**Comment by mkArtakMSFT** [comment]
@wtgodbe is this something you're ware of?
@marcpopMSFT in case you've heard of similar behaviors after the recent release.

**Comment by mkArtakMSFT** [comment]
@dallas1287 can you share the deps.json file from the obj directory?
