### ISSUE TITLE
Make Blazor Wasm SubDomain Routing Internal 

### ISSUE THREAD

**Issue by bo-bac** [dotnet/aspnetcore#48197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm working on an application with subdomain routing.
exectly the same case is described here #44089 
but the case was closed without any comments

### Describe the solution you'd like

I would like to navigate from one subdomain to another without application reloaing

**Comment by javiercn** [comment]
@bo-bac thanks for contacting us.

Client side navigations are not possible across subdomains.
