### ISSUE TITLE
Microsoft.Authentication.WebAssembly.Msal triggering SSO redirect to AAD three times in rapid sequence

### ISSUE THREAD

**Issue by andrea-migliaccio** [dotnet/aspnetcore#48196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

we have two indepedent but quite simila Blazor WASM applications where the authentication process (despite being it with redirect or popup loginmode) is always triggered three times in rapid sequence when the refresh token is expired. 

This is happening in our deployed application while not happening in the local development environment in visual studio 2022. 

BTW, the development environment and deployment environment share the same AAD App Registration Client-ID and a basically identical configuration of the MSAL library.

From the browser network we can see this sequence of events

- GET /token --> 400 bad request for refresh token expiration
- First auth popup open
- we receive the /login-callback
- the first back end API call is executed successfully...
- PROBLEM: while executing further API calls we can see further GET /token and other two authentication popup are opened and quickly closed
- We can't see any meaning log from MSAL in the browser console.

What can we do to get more meaningfull traces to better address this weird behaviour?

The attached screenshot shows the bootstrap of the blazor wasm application. Please keep in mind that we have configure popup login mode, thus some of the request are not traced in this sequence.

<img width="292" alt="image" src="https://github.com/dotnet/aspnetcore/assets/97603234/f8674234-8ab2-46fe-b5ba-5e2759661e26">

Thanks!
Andrea

### .NET Version

6.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not an easy one to provide quick guidance. We have added logging in .NET 7. If you could move to .NET 7 even for the sake of this investigation, that may help with diagnosis. Otherwise, we will need a reliable repro project.

**Comment by andrea-migliaccio** [comment]
Ok, we'll move our FE application to .net 7 and try to collect some log from that version. Thank for the advice, I'll come back with further info as soon as we'll be able to complete the porting and deploy it in our runtime environments.
