### ISSUE TITLE
VariableLengthIntegerHelper returns incorrect value on consumed parameter

### ISSUE THREAD

**Issue by ladeak** [dotnet/aspnetcore#48203]
### Description

VariableLengthIntegerHelper.GetInteger seems to return an incorrect value on the consumed SequencePosition parameter. It seems to return a relative position to the original ReadOnlySequence<T> instead of the sliced one.

### Reproduction Steps

```csharp
long Foo(ref ReadOnlySequence<byte> buffer)
{
    var innerBuffer = buffer. Slice(1L);
    VariableLengthIntegerHelper.GetInteger(innerBuffer, out SequencePosition consumed, out SequencePosition examined);
    return innerBuffer.GetOffset(consumed);
}
```

### Expected behavior

I would expect a position returned relative to the sliced innerBuffer. Especially because Foo method might already get a sliced ReadOnlySequence, so in that case the `SequencePosition` returned might be actually higher to the length of the `ReadOnlySequence` itself.

### Actual behavior

It returns a SequencePosition relative to the input parameter `buffer`.

### Known Workarounds

I use `TryRead` method that returns a byteCount.

**Comment by amcasey** [comment]
@ladeak I feel like I'm missing something obvious, but `VariableLengthIntegerHelper` doesn't appear to be a public API.  Can you tell us more about your use case?

**Comment by ladeak** [comment]
This blog post: https://devblogs.microsoft.com/dotnet/dotnet-7-networking-improvements/#future by @CarnaViire encouraged me to try the new bits and pieces and give feedback.

I used the APIs the same way as .NET and ASP.NET Core shares it among each other. I am trying to send H/3 requests with the QUIC API.

**Comment by ladeak** [comment]
I have the `VariableLengthIntegerHelper` "synced" to my repo the same way ASP.NET Core and dotnet runtime share the implementation. For using QUIC (likely for HTTP), it could make sense to have it as a public type, otherwise people would need reimplement it.

**Comment by amcasey** [comment]
This appears to be unrelated to `VariableLengthIntegerHelper`:
```csharp
ReadOnlySequence<byte> sequence = new ReadOnlySequence<byte>(new byte[] { 128, 0, 0, 2 });
ReadOnlySequence<byte> slice = sequence.Slice(1);
SequencePosition slicePos = slice.GetPosition(1);
long sliceOffset = slice.GetOffset(slicePos); //2
```

I have to admit I find this behavior surprising.  Even if this is user error (i.e. don't do that), it seems like there's enough information to throw an exception (specifically, `!slicePos.GetObject().Equals(slice)`).

**Comment by amcasey** [comment]
I was mistaken - the object is not sufficient because it's not directly tied to the sequence.  Unfortunately, I believe this is a case where we sacrificed user experience for perf.  If you're interested in pursuing the matter further (and it sounds like you're happy to tweak your local copy, so I'm guessing not), the next step would be to file an issue on https://github.com/dotnet/runtime with a simpler repro like the one above.

**Comment by ladeak** [comment]
THank you I will do so.
