### ISSUE TITLE
Passing IServiceProvider to AddTransientHttpErrorPolicy like AddPolicyHandler

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnetcore#48200]
Hi,
Could we have `IServiceProvider` as one of the parameters in [`AddTransientHttpErrorPolicy`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.pollyhttpclientbuilderextensions.addtransienthttperrorpolicy) lambda expression, like something we have in `AddPolicyHandler`?

**Comment by amcasey** [comment]
@mehdihadeli Thanks for the suggestion!  This would require a change to the public API (probably a new overload), so can you please fill out the API request [template](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=).

Closing in anticipation of a replacement issue for the API request.
