### ISSUE TITLE
Add endpoint metadata to developer exception page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#48208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Today the developer exception page includes some information about the endpoint, such as its name, route and order.

It's useful to know the metadata on the endpoint. Issues such as https://github.com/dotnet/aspnetcore/issues/39792 are adding useful string representations of metadata.

### Describe the solution you'd like

The `Route` tab on the developer exception page includes a list of the endpoint's metadata. On the server, it would be gathered by simply calling `ToString` on the contents on the metadata collection.

This information could be collapsed initially on the webpage, and clicking a button expands the metadata list. Note that metadata could be very log (e.g. a generated type with a long name that doesn't have a useful ToString) so there should be a maximum length displayable that is truncated by an ellipsis.

**Comment by Kahbazi** [comment]
I would like to send a PR for this one.

**Comment by JamesNK** [comment]
Great. Go ahead.
