### ISSUE TITLE
Asp.Net core takes 12 minutes for initial page load

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#48215]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/AspNet-core-takes-12-minutes-for-initia/10356917)._

---
[severity:It's more difficult to complete my work]
The solution build is quick, taking less than a minute, often just 10-20 seconds as indicated by the Output window, but following that it takes another 12 minutes for the first page to load launching from VS. It makes no difference whether it is launched with or without debugging. It makes no difference whether running IISExpress or the Kestrel web server. While waiting for the application to become responsive, all the output window shows are periodic "thread has exited" messages every couple of minutes or so. The Windows Event Viewer is of no use. I don't know how to get more information on what is happening between build and loading the site, but something is clearly very wrong. 

This is VS2022 running on Windows 11. The startup project is asp.net core, net 6.0. The views are razor pages, approximately 600 - 700 in number. The projects are on net 6.0  The development laptop has 64 GB RAM and 12th Gen Intel(R) Core(TM) i7-12700H   2.70 GHz processor, so is not short of resources or power. 

I've added exclusions in Windows Security for the Visual Studio development directories and program directories and for processes devenv.exe, msbuild.exe. I disabled all extensions at one point. Even deleted the suo file, which seems to be common advice. None of it makes any difference. CPU is not high and the development machine memory is nowhere near exhausted. Although VS is consuming nearly 6GB in total when running the solution (Task Manager reports: VS2022: 2,767.6MB; Microsoft.ServiceHub.Controller: 1,361.5MB; ServiceHub.RoslynCodeAnalysisService.exe: 895.1MB ). 

This greatly hampers development.

---
### Original Comments

We have found the cause and can now start our application from VS2022 in around 20 seconds.
Configuration of app routing in the Startup.cs Configure method turned out to be responsible:

```c#
app.UseEndpoints(endpoints =>
{
endpoints.MapControllerRoute(
name: “areas”,
pattern: “{area:exists}/{controller}/{action=Index}/{id?}”);
endpoints.MapControllerRoute(
name: “default”,
pattern: “{controller=Landing}/{action=Index}/{id?}”);
endpoints.MapRazorPages();
});
```

By removing the “exists” check, i.e. changing the areas’ routing pattern to: “{area}/{controller}/{action=Index}/{id?}”, the time to load the Landing page when launched from VS debug went from >12 minutes to approx. 20 seconds.

**Comment by javiercn** [comment]
Thanks for contacting us.

Does the same issue happen if you run the code from the command-line?

**Comment by st100953** [comment]
The same delay in first page load occurs when started using "dotnet run" from the VS PowerShell. The application is built and the first request to load the landing paging or any page takes a very long time.
