### ISSUE TITLE
Use versioned python3 command in scripts

### ISSUE THREAD

**Issue by sbomer** [dotnet/aspnetcore#48221]
We would like to establish a simplified and generalized pattern for defining helix container images in our infrastructure, and reduce the number of workarounds required to satisfy specific test scenarios, such as https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/e2ac99efb806885c8c253fa80aa65ca98e4ac3bb/src/almalinux/8/helix/amd64/Dockerfile#L22-L23.

To this end, aspnetcore should replace uses of unversioned `python` with the specific versioned executable (`python3` unless there are python2 uses not covered by the test runs that I switched over to this image in https://github.com/dotnet/aspnetcore/pull/47970). This is in line with the best practice advice in https://developers.redhat.com/blog/2018/08/13/install-python3-rhel#python-tips.

cc @richlander

**Comment by richlander** [comment]
We're in the process of updating our helix Dockerfiles for .NET 8. We are revisiting all the patterns, particularly the anti-patterns.
