### ISSUE TITLE
[ResponseCachingAttribute] Over-caching on proxies when using `VaryByQueryKeys`

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#4823]
Currently, if the response caching middleware is added, the ResponseCacheAttribute can use the `VaryByQueryKeys` of the ResponseCachingFeature. However, this is only used by the middleware on the server and can lead to over-caching in the cache on proxies and the client since they won't vary by query keys.

In ASP.NET this was handled by using separate cache locations `Server`, `ServerAndNoCache` and `ServerAndPrivate` which sends either `no-cache` or `private` cache directives to prevent caching on the client and intermediate proxies but enables caching on the server. We may need to do something similar here.

**Comment by pranavkm** [comment]
Closing this as we haven't really seen a lot of feedback in this area.
