### ISSUE TITLE
Signalr: Request for Optimized Client-Server Communication

### ISSUE THREAD

**Issue by akash159chauhan** [dotnet/aspnetcore#48239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, the client-server connection in our system remains open at all times, leading to unnecessary resource consumption and potential security vulnerabilities. We need to implement a more efficient approach where the client initiates a connection with the server only when there is a message to be sent from the server side.

### Describe the solution you'd like

I am able to think of a solution that client will disconnect from hub if it is not able to get any message from a particular period of time, and after some it will trigger an event to again connect with hub to check if there is any message to be receive from the server side but it is not an efficient solution as notification will come in a bulk so I need a solution where if any message server want to send, it is able to make client gets connected and then got disconnected.

So any recommendation for any best approach or any feature which SignalR already have please suggest it will be very helpful..

**Comment by davidfowl** [comment]
SignalR isn't fit for occasional connections. The architecture is optimized for long running, real time connections to an open client. Maybe there's another framework here, but at the moment, it isn't SignalR.
