### ISSUE TITLE
TextAreaTagHelper ignores default value within textarea tags

### ISSUE THREAD

**Issue by ZacMillionaire** [dotnet/aspnetcore#4824]
### Title
When using `asp-for` on a `textarea` tag, all contents between the opening and closing `textarea` tags are discarded

### Functional impact
Prevents setting a default value for `textarea` when the view is rendered.

### Minimal repro steps
1. Create a new ASP.NET Core Web Application (.NET Framework) Web Application project
2. Create a new model with a single string property
3. Add this model to a new view, or edit one of the pre-existing Views such as Home>Index.cshtml
4. Add a `form` with a single `<textarea asp-for="<model string property>">Inner Value</textarea>`
5. Run
6. Browse to view

### Expected result
The page should display a textarea on the page with the content of "Inner Value", with it's `id` and `name` attributes from the model

### Actual result
Attributes are correctly set, default value is blank

### Possible Cause
Within Microsoft.AspNetCore.Mvc.TagHelpers/TextAreaTagHelper.cs, the value of `output.Content` is set to the value of `tagBuilder.InnerHtml`. This value appearsto default to `\r\n` which is then reduced to nothing as TagHelperOutput checks `IsEmptyOrWhiteSpace` on this and sets it to true, resulting in an empty `textarea` tag being rendered.

### Workaround
Changing `output.Content.SetHtmlContent(tagBuilder.InnerHtml);` on line 77 to `output.Content.SetHtmlContent(output.GetChildContentAsync().Result.GetContent());` correctly retrieves the given content of the `textarea`, but seems unlikely to be the correct fix.

### packages.json
Default from package creation, persists on package update.
```
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  }
```

**Comment by stefanjm** [comment]
Running into the same problem with SDK 2.2.401.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
