### ISSUE TITLE
Optimize DefaultHubLifetimeManager.OnDisconnectedAsync when there are thousands of unsubscribed groups

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#48249]
Some apps can manage thousands of SignalR groups in-memory while any given connection is only a member of a few of them. In this case, `HubGroupList.RemoveDisconnectedConnection` is very inefficient because it has to scan every group in the application, even those that the disconnecting connection is not a member of:

https://github.com/dotnet/aspnetcore/blob/142e078e3b524cf9f41f694bc7b3b8b5d25b3dda/src/SignalR/server/Core/src/Internal/HubGroupList.cs#L46-L53

We can optimize this by having each connection track the groups it's a member of as suggested by the internal report.

> ## High CPU from SignalR OnDisconnectedAsync
> This happens because in SignalR Core whenever a connection is disconnected we iterate over the entire concurrent dictionary of groups to find all the groups this connection Id needs to be removed from. In our example, a typical machine load has 100k connections with 40k groups (average of 2.5 connections per group).  In my quick benchmark I found that this iteration over the group dictionary takes 20ms with 40k groups and 2 connections per group. With 100k connections, and with typical users behavior patterns, a common disconnect rate is about 100 per second. Since each disconnect needs to iterate the groups, we need 2000ms of CPU time per 1 second. With 16 cores machines, it means 12% of the entire machine CPU is constantly spent only on this group removal, and it doesn’t take much to bring the total machine CPU to 100% with some temporary bursts of disconnects.
>
> I think in Asp.Net SignalR this was not an issue because in Asp.Net SignalR each connection keeps track of its own group memberships, so when it gets disconnected we don’t scan all the groups in the application.
>
> To workaround this issue, I’m removing the connection from the group myself upon disconnect, instead of having SignalR do that - I updated our code to keep track of each connection’s group membership in its Context.Items, and then call this.Groups.RemoveFromGroupAsync() in the Hub’s OnDisconnectedAsync event.
> I then created a custom HubLifetimeManager (instead of DefaultHubLifetimeManager) that overrides the OnDisconnectedAsync method, and doesn’t call _groups.RemoveDisconnectedConnection.
>
> This fixed the CPU issue.

We already do something similar for redis via `IRedisFeature.Groups`:

https://github.com/dotnet/aspnetcore/blob/142e078e3b524cf9f41f694bc7b3b8b5d25b3dda/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs#L128-L141

**Comment by davidfowl** [comment]
Thanks for filing this @halter73

**Comment by alex-jitbit** [comment]
I just submitted a PR that is supposed to fix this. It does modify any public APIs, just adds a tiny `Feature` that tracks groups per connection, just like what Redis-manager *already does*.
