### ISSUE TITLE
Memory leak in Health Checks

### ISSUE THREAD

**Issue by henridd** [dotnet/aspnetcore#48240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every single request to health checks leaks a bit of memory. Eventually, if the application is ran 24/7 with multiple applications constantly requesting health checks, the memory consumption can get very high.

### Expected Behavior

The memory should be freed after the resources have been used.

### Steps To Reproduce

1. Download the sample from https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/host-and-deploy/health-checks/samples. You can also use https://github.com/henridd/health-check-mem-leaking, which leaks faster.
2. Edit Program.cs to look like the following:
```c#
using HealthChecksSample.HealthChecks;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHealthChecks()
    .AddCheck<SampleHealthCheck>("Sample");

var app = builder.Build();

app.MapHealthChecks("/healthz");

app.Run();

```
3. Run the application
4. Open a tool to monitor the application's memory usage. Can be accomplished through the Process Manager.
5. Wait some seconds for the application to stabilize its memory usage.
6. Issue multiple requests to the healthcheck endpoint (https://localhost:1482/healthz). In my case, I've used Postman to request 500 times.

### .NET Version

7.0.100

### Anything else?

The initial memory consumption was 20 684 K. After 2000 requests made via Postman, it was 35 412 K. Forcing a GC didn't clear up any memory. 
You can find the memory dump below. The first snapshot was taken after a a few dozen requests, and the second after 2000. I forgot to take a snapshot immediately before starting the requests, so if needed I can run another profile.
[Attach to HealthChecksSample.zip](https://github.com/dotnet/aspnetcore/files/11484497/Attach.to.HealthChecksSample.zip)

.NETCore.App 7.0.0
AspNetCore.App 7.0.0

**Comment by davidfowl** [comment]
What does it leak? Where's the memory profile? What is it leaking? Did the garbage collector run?

**Comment by henridd** [comment]
I have edited the ticket with the profile file.

What do you mean by "what does it leak"/"what is it leaking"? I do not have much experience troubleshooting memory leak problems, sorry. If you would have an article to point me to, I would appreciate it.

The GC did run. I tried 2 different tests with a similar code that might give some insight.

```csharp
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.Extensions.Diagnostics.HealthChecks;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
AddAppHealthChecks(builder.Services);

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

UseAppHealthChecks(app);

app.Run();

void AddAppHealthChecks(IServiceCollection services)
{
    _ = services.AddHealthChecks()
        .AddCheck<TestHealthCheck>(nameof(TestHealthCheck), HealthStatus.Unhealthy, new List<string>()
        {
                    nameof(TestHealthCheck)
        });
}

void UseAppHealthChecks(WebApplication webApplication)
{
    webApplication.MapHealthChecks("/health/test", new HealthCheckOptions
    {
        Predicate = healthCheck => healthCheck.Tags.Contains(nameof(TestHealthCheck)),
    });
}

public class TestHealthCheck : IHealthCheck
{
    public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
    {
        //GC.Collect();       
        return HealthCheckResult.Healthy();
    }
}
```

If you uncomment the GC.Collect() call in the CheckHealthAsync method, the memory consumption becomes way more stable, it doesn't increase for every call to the healthcheck endpoint. It seems almost that the memory leak is gone.
But if you would comment that line again, and add a Timer which calls GC.Collect() every 30s, for example, the problem persists.

**Comment by davidfowl** [comment]
This doesn't sound like a leak then. Please refer to this https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md to get a better idea of what might be happening.

**Comment by henridd** [comment]
Thanks for the great article. I'll take a look into it and update the ticket when I'm done with it

**Comment by henridd** [comment]
It seems that the bigger the response, the bigger the leak. After making the changes below, it took less than 60 requests for the memory consumption to double.
```csharp
void UseAppHealthChecks(WebApplication webApplication)
{
    webApplication.MapHealthChecks("/healthz", new HealthCheckOptions
    {
        Predicate = healthCheck => healthCheck.Tags.Contains(nameof(TestHealthCheck)),
        ResponseWriter = ResponseWriter
    });
}

Task ResponseWriter(HttpContext context, HealthReport healthReport)
{
    var lengthyString = "";
    for (int i = 0; i < 100; i++)
    {
        lengthyString += Guid.NewGuid().ToString();
    }

    return context.Response.WriteAsync(lengthyString);
}
```
I've downloaded Deleaker, and it seems that this MetaDataGetDispenser is mentioned several types
![image](https://github.com/dotnet/aspnetcore/assets/11314496/abb0f325-f1d4-41c2-92a4-95e79aa114c1)

When comparing the first snapshot with the last one, it shows up again
![image](https://github.com/dotnet/aspnetcore/assets/11314496/77b79852-9e49-442f-9452-d307b80e235b)

I'm not sure where I should go from here. Is there a cleanup method that I'm missing?

**Comment by mitchdenny** [comment]
I'm not seeing evidence of a managed or unmanaged memory leak here. If there was I would expect that as you executed more requests that the amount of memory consumed would balloon and eventually the process would crash (assuming you kept firing load into it).

Using your repro I used Postman to fire 3000+ requests to the health-check endpoint and memory utilization didn't go above 60MB.

We'll probably need to see stronger evidence of an issue here to keep investigating.

**Comment by henridd** [comment]
> I'm not seeing evidence of a managed or unmanaged memory leak here. If there was I would expect that as you executed more requests that the amount of memory consumed would balloon and eventually the process would crash (assuming you kept firing load into it).
> 
> Using your repro I used Postman to fire 3000+ requests to the health-check endpoint and memory utilization didn't go above 60MB.
> 
> We'll probably need to see stronger evidence of an issue here to keep investigating.

Hey @mitchdenny thanks for looking into this.
That's precisely what happens here. Did you try my latest example, where the health check writes a bunch of GUIDs in the Response? That caused the memory consumption to raise super fast. I've set up a git repository with the code: https://github.com/henridd/health-check-mem-leaking.

I thought that it could be somehow something faulty on my machine, but we began this investigation after finding a leak on the server.

[Video.webm](https://github.com/dotnet/aspnetcore/assets/11314496/6bc66f9a-908c-46eb-b449-c6c262e4fed9)

I've attached a video which shows the memory consumption increasing. It does seem to somehow stabilize once it reaches 200mb though, but I suppose it shouldn't increase that much.

**Comment by mitchdenny** [comment]
That isn't surprising in your example because you are allocating a bunch of strings every time you do a health check so there will be more memory being consumed. Each iteration of your string generation logic in is going to generate > 300kb of memory usage (that is a very wasteful way to generate a long string by the way - but that may have been intentional).

Do a hundred requests and you've allocated > 30MB of just strings and that is before we get to any specific .NET or ASP.NET overheads.

You might like to read a bit more background on the different GC modes we have in .NET and how they impact when memory is collected:

https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc

**Comment by henridd** [comment]
I see. I assumed that the memory consumption shouldn't exceed the initial amount of consumed memory, as nothing is being stored, but I probably should investigate this further in order to understand it better.
To be fair, from the beginning it sounded strange to me that there would be a leak in something so used, in a normal scenario.

I will keep investigating and researching about memory and try to reduce the memory consumption.

Thanks @davidfowl and @mitchdenny for your inputs
