### ISSUE TITLE
Default EventSourceSupport to true in ASP.NET Native AOT apps

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#48247]
EventSource wasn't supported when publishing an app for NativeAOT in .NET 7. This led to the `EventSourceSupport` feature switch to being [disabled by default in AOT](https://github.com/dotnet/runtime/pull/76000).

In .NET 8 we are getting EventSource to work in Native AOT apps - https://github.com/dotnet/runtime/issues/79241. However, the `EventSourceSupport` feature switch is still disabled, so users won't be able to use things like `dotnet monitor` or `dotnet counters` unless they explicitly opt-in.

We should default `EventSourceSupport=true` in ASP.NET Native AOT'd applications.

This will add size to the default apps (the estimate is around 1 MB), however the tradeoff is worth it, since EventSource is a very common mechanism used for getting information about a running app.

cc @DamianEdwards @davidfowl @noahfalk @agocke @LakshanF @jkotas @MichalStrehovsky

**Comment by davidfowl** [comment]
Agree

**Comment by agocke** [comment]
No argument from me for ASP.NET. For hello, world I think it would ~double the app size, so there seems like a good reason to leave it out there.
