### ISSUE TITLE
we can't upload the directory(folder) in InputFile component

### ISSUE THREAD

**Issue by mohanrajsf3477** [dotnet/aspnetcore#48257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

we cant upload the directory(folder) in InputFile component. while drag and drop the folder we get the folder name only in OnChange event, while upload the folder, sub files which is present in the folder need to upload

<InputFile OnChange="@LoadFiles" multiple directory="true" />

### Expected Behavior

while upload the folder, sub files are need to upload

### Steps To Reproduce

1. try to upload the folder or drag and drop the folder on InputFile component

### .NET Version

6 and 7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like html requires specifying `directory` attribute on an input, but that's not standardized yet. You can try to pass that in the `InputFile` declaration and see if that works.
