### ISSUE TITLE
Random slow response time when application low load

### ISSUE THREAD

**Issue by andrew-vdb** [dotnet/aspnetcore#48262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have very strange problem and looking to pin point the issue. The api use ef core for data access and return dictionary  simple api.

The api hosted in kubernetes, i port forward to my local.

I used postman, run 50 requests without delay, all api call return with 25ms response time. Looks nice.

But when i put 10 seconds delay and run 50 requests, there is always a request which has slow response time to 1 second or 2 seconds.

In my local, this does not happen.

I already remove cpu limit to avoid cpu throttle, i even test api to run in new node. But that random slow keep coming back.

I can only think its garbage collector issue? I used gc server=0 which means it use workstation gc, it run in standard d2v2, 2 vcpu, 7GB memory.

Installed grafana, no cpu throttle, there is spike in cpu usage, which i dont understand as we are calling same api, same parameters.

So i have awesome benchmark with very poor real ux due random slow call to api when system is not heavily used.

Is there anyway i can see that gc is running? Like the yellow arrow in visual studio but kubernetes. When i run it locally, targeting same db, i dont see gc running at all, but thats because my laptop has 32GB memory i think.

### Expected Behavior

Consistent performance when application under very low load, funny because normally response time goes higher when application under heavy load.

### .NET Version

7.0

**Comment by danmoseley** [comment]
Presumably Linux?

Have you tried dotnet-counters?

https://learn.microsoft.com/en-us/dotnet/core/diagnostics/

**Comment by andrew-vdb** [comment]
Yes linux.
I will wait another people that has same performance characteristics. For now ill close this issue.
