### ISSUE TITLE
Minimal API - improve Parameter Binding, allow validation of query parameters

### ISSUE THREAD

**Issue by AdisonCavani** [dotnet/aspnetcore#48261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to have query parameters in GET endpoint. Given the code:
```cs
app.MapGet("/", (int pageSize, string? pageKey, IValidator<PaginatedReq> validator) =>
{
    var validation = validator.Validate(request);

    if (!validation.IsValid)
        return Results.BadRequest(validation.Errors);

    return Results.Ok();
});
```

or using `[AsParameters]` attribute:

```cs
// PaginatedReq.cs
public class PaginatedReq
{
    public string? PageKey { get; set; }
    public int PageSize { get; set; }
}

// Program.cs
app.MapGet("/", ([AsParameters] PaginatedReq request, IValidator<PaginatedReq> validator) =>
{
    var validation = validator.Validate(request);

    if (!validation.IsValid)
        return Results.BadRequest(validation.Errors);
    
    return Results.Ok();
});
```

When making a HTTP GET request, and not providing `pageSize` as query parameter, throws this exception:
```
An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Http.BadHttpRequestException: Required parameter "int pageSize" was not provided from query string.
```

This exception is thrown **before** `Filter` and `IValidator`, which makes validation (with FluentValidation filter or injected IValidator) impossible.

Validating request is a essential requirement of any Web Api.
It is possible with traditional Controllers, but this functionality is missing in Minimal API.

### Describe the solution you'd like

Provide new attribute for query string parameters, that allows validation and does not throw exception.
or:
"Fix" current implementation of `[AsParameters]` attribute.

### Additional context

Documentation for Parameter Binding: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0

**Comment by BrennanConroy** [comment]
Sounds like you want a filter
https://learn.microsoft.com/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-8.0

**Comment by captainsafia** [comment]
@AdisonCavani There's a couple of things going on here:

- The exception that you're seeing thrown is a Development-time behavior as part of the requiredness checks in minimal APIs. When you're in production, this will manifest as a 400 status response code without an exception.
- What is the `IValidator` API that you are using? If it is invoked _inside_ your handler, it will run after the requiredness checks mentioned in the bullet above. You'll probably want to integrate this into a filter.
- What issues are you running into with `[AsParameters]`. It's not clear from the issue?

**Comment by aradalvand** [comment]
It seems like you're using FluentValidation. So just use a filter as a validator, like this:
```csharp
public static class AddValidationFilterExtension
{
    public static TBuilder AddValidationFilter<TBuilder>(
        this TBuilder builder
    ) where TBuilder : IEndpointConventionBuilder
    {
        return builder.AddEndpointFilterFactory((factoryCtx, next) =>
        {
            var sp = factoryCtx.ApplicationServices.GetRequiredService<IServiceProviderIsService>();
            var validatableParameters = factoryCtx.MethodInfo.GetParameters()
                .Select(p => new
                {
                    p.Position,
                    ValidatorType = typeof(IValidator<>).MakeGenericType(p.ParameterType),
                })
                .Where(p => sp.IsService(p.ValidatorType))
                .ToList();

            if (!validatableParameters.Any())
                throw new InvalidOperationException($"No validatable parameters on '{factoryCtx.MethodInfo.Name}'.");

            return async ctx =>
            {
                var validationResults = await Task.WhenAll( // NOTE: The use of `WhenAll` along with LINQ here effectively means the arguments will be validated in parallel, which obviously makes it more efficient. This technique is appropriate when the tasks that need to be awaited don't depend on one another's value, so they don't have to be run sequentially. See https://www.youtube.com/watch?v=gW19LaAYczI and also https://stackoverflow.com/a/40132240
                    validatableParameters.Select(p =>
                    {
                        var validator = (IValidator)ctx.HttpContext.RequestServices
                            .GetRequiredService(p.ValidatorType);

                        var objToValidate = ctx.Arguments[p.Position];

                        return validator.ValidateAsync(
                            new ValidationContext<object?>(objToValidate),
                            ctx.HttpContext.RequestAborted
                        );
                    })
                );

                if (validationResults.Any(r => !r.IsValid))
                {
                    return Results.BadRequest(new
                    {
                        Errors = validationResults
                            .SelectMany(r => r.Errors)
                            .Select(e => e.ErrorMessage),
                    });
                }

                return await next(ctx);
            };
        });
    }
}
```

Usage:

```csharp
app.MapGet("/", ([AsParameters] PaginatedReq request) => Results.Ok())
    .AddValidationFilter();
```

**Comment by AdisonCavani** [comment]
Ok. As per @captainsafia answer:

I thought this will also throw in Production, because in development I was receiving 500 internal server error response, even tho I was using a IEndpointFilter that validates the requests.

@BrennanConroy I'm using a Filter, but in development it's not working, because of the exception (Microsoft.AspNetCore.Http.BadHttpRequestException)

@aradalvand I already have similar FluentValidation Filter.

**Comment by davidfowl** [comment]
@AdisonCavani https://github.com/benfoster/o9d-aspnet this validation library is pretty solid
