### ISSUE TITLE
We should add a method to stringify a TagHelperAttribute's value.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#4827]
With the addition of `TagHelperComponent`s you don't get property binding of attribute values so you're forced to introspect on `context.AllAttributes`/`output.Attributes`. If you want to look at an attributes value you then have to write a boat load of complex code to accurately retrieve the value. We should add a method somewhere to enable you to retrieve the string format of a `TagHelperAttribute`.

Could be an extension method on `TagHelperAttribute` (`GetStringValue()`), could be a protected method on the `TagHelperComponent` base type, could be a static method somewhere. Any of those i'd be fine with.

/cc @Eilon @DamianEdwards

**Comment by pranavkm** [comment]
Closing this. We haven't heard customer ask for this and the sample that was listed in the earlier comment should help.
