### ISSUE TITLE
Allow creating Razor class libraries with `Microsoft.AspNetCore.Components.Server.Circuits` namespace

### ISSUE THREAD

**Issue by Mr-Technician** [dotnet/aspnetcore#48290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am creating an RCL to aid in tracking active circuits on internal web applications. At present, I have no way of tracking who is actively using a site or not. While I could create my own singleton, the existing `CircuitHandler` class already accomplishes this goal in a single project. The problem arises when using this class in an RCL. The namespace `Microsoft.AspNetCore.Components.Server.Circuits` is not available in an RCL and Microsoft does not provide a nuget package that provides this functionality, so I have no way of bunding my logic into a reusable RCL.

### Describe the solution you'd like

A nuget package that provides these classes, or some other means of accessing server-side circuit tracking logic from an RCL.

### Additional context

This question has also been asked on [StackOverflow](https://stackoverflow.com/questions/72252888/accessing-microsoft-aspnetcore-components-server-circuits-from-inside-razor-clas).

**Comment by javiercn** [comment]
@Mr-Technician thanks for contacting us.

You need to bring the reference to asp.net core using `<FrameworkReference Include="Microsoft.AspNetCore.App" />` and that will make them available to you.

**Comment by Mr-Technician** [comment]
Thank you @javiercn, this takes care of my issue!
