### ISSUE TITLE
Quick grid does not render in .net 7 blazor server project

### ISSUE THREAD

**Issue by martinRocks** [dotnet/aspnetcore#48292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a client side blazor app and install the quick grid from Nuget.  I then added the using statement and it has no idea what I'm talking about.  I copied the rest of the demo code, but I seem to be stuck on step 1.  In the image below you can see my version of everything and the using statement that is unhappy.  I'm using VS2022, version 17.6.  What am I missing?

![Screenshot 2023-05-17 184738](https://github.com/dotnet/aspnetcore/assets/10621557/54467f13-a842-42f7-a78b-4b2f9a8126e0)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Looks like you're mixing packages with conflicting TFMs. Try to reference the `https://www.nuget.org/packages/Microsoft.AspNetCore.Components.QuickGrid/0.1.0-alpha.22351.1` version of the QuickGrid package and that should fix it.
