### ISSUE TITLE
Identity cookie is not removed from browser after removing unwanted scheme

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspnetcore#48297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```cs
public static IdentityBuilder AddAppIdentity<TUser, TRole>(this IServiceCollection services,
        Action<IdentityOptions> setupAction) where TUser : IdentityUser where TRole : IdentityRole
    {
        services.TryAddEnumerable(
            ServiceDescriptor
                .Singleton<IPostConfigureOptions<CookieAuthenticationOptions>,
                    PostConfigureCookieAuthenticationOptions>());
        services.AddOptions<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme)
            .Validate(o => o.Cookie.Expiration == null, "Cookie.Expiration is ignored, use ExpireTimeSpan instead.");
        services.AddAuthentication(
                options => options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme)
            .AddScheme<CookieAuthenticationOptions, AppCookieAuthenticationHandler>(
                IdentityConstants.ApplicationScheme, IdentityConstants.ApplicationScheme,
                options => { options.Cookie.Name = ".App.Identity"; });
            //.AddCookie(
            //    IdentityConstants.ExternalScheme,
            //    options =>
            //    {
            //        options.Cookie.Name = IdentityConstants.ExternalScheme;
            //        options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
            //    })
            //.AddCookie(
            //    IdentityConstants.TwoFactorRememberMeScheme,
            //    options =>
            //    {
            //        options.Cookie.Name = IdentityConstants.TwoFactorRememberMeScheme;
            //        options.Events = new CookieAuthenticationEvents
            //        {
            //            OnValidatePrincipal = SecurityStampValidator.ValidateAsync<ITwoFactorSecurityStampValidator>
            //        };
            //    })
            //.AddCookie(
            //    IdentityConstants.TwoFactorUserIdScheme,
            //    options =>
            //    {
            //        options.Cookie.Name = IdentityConstants.TwoFactorUserIdScheme;
            //        options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
            //    });


       //Service Register Omitted
       ..................................

        return new IdentityBuilder(typeof(TUser), typeof(TRole), services);
    }
```
If I remove `AddCookie` like above, it will not remove the cookie from browser after signing out. I want to remove above annotated code, cause I don't really need those schemes. And to be honest, I don't understand what they are doing. The official doc about identity is like a disaster, tried to find clue from aspnetcore source. But I still can't figure it out. What I found out is that `IdentityConstants.TwoFactorUserIdScheme` may be the reason. But I still want to remove those.

I'm not sure if you need `AppCookieAuthenticationHandler` code, this is a custom `CookieAuthenticationHandler` which handle the sign-out by post request to sign-out api endpoint. The handler simply call `await signInManager.SignOutAsync();` Since if I keep the annotated code, it will work. I think I don't need to provide the `AppCookieAuthenticationHandler` code.

### Expected Behavior

The Identity should work without unwanted schemes and the cookie should be removed when signing out.

### .NET Version

.NET 7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

By removing the `.AddCookie` call, you essentially make the server be unaware of the fact that such cookie exists. So you will have to write a custom (one-time) migration logic (via custom middleware for example) which will remove the unnecessary cookies.

**Comment by Kumima** [comment]
@mkArtakMSFT Not the answer I want, I do add the cookie stuff, just added by the code above `.AddCookie`. I've read the source, the `.AddCookie` just does the same as what I do. And it does recognize the cookie, since if I refresh the page with browser, it will make me sign-in. The problem is I don't need unwanted schemes.

**Comment by Kumima** [comment]
I may get the answer. https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#LL243C23-L243C35. If not call `AddCookie` for IdentityConstants.ExternalScheme, IdentityConstants.TwoFactorUserIdScheme. It will throw. I think I have to override the `SignInManager.SignOutAsync()`
