### ISSUE TITLE
Inconsistent HTML Encoding of Validation Message

### ISSUE THREAD

**Issue by dennismsmith** [dotnet/aspnetcore#4830]
### Functional impact
When using data annotations to configure validation, the message does not get HTML encoded when it is rendered client side for unobtrusive validation, but it does get HTML encoded when rendered in response to server side validation.  As a result, any error message that contains characters that need to be HTML encoded cannot be reliably used for both client and server side validation.

### Minimal repro steps
1. Use the attached sample application with JavaScript enabled in the browser [ValidationEncodingTest.zip](https://github.com/aspnet/Mvc/files/900195/ValidationEncodingTest.zip)
2. Enter a string with three or more characters in the input box
3. Click Submit
3. Note that client side validation fails (expected, as the validation rule has been violated)
4. Note that the message is displayed in bold ![validation-clientside](https://cloud.githubusercontent.com/assets/2591590/24717397/5145e4b8-1a00-11e7-92cb-d6ce7c05bbca.PNG)
5. Load the page from the sample application again
6. Disable JavaScript in the browser
7. Enter a string with three or more characters in the input box
8. Click Submit
9. Note that client side validation is skipped (expected) and server side validation fails (expected, as the validation rule has been violated)
10. Note that the error message is not bold and the literal `<b>` content is displayed
![validation-serverside](https://cloud.githubusercontent.com/assets/2591590/24717437/77c1a960-1a00-11e7-8117-fdd19c665283.PNG)

### Expected result
I don't have a strong opinion about whether the messages should be automatically HTML encoded or not, but I would expect that the messages from step 4 and step 10 would be the same.  Whether the user has enabled JavaScript or not should have no impact on whether the message is HTML encoded or not.

From a security standpoint, it would probably be safer to ensure that the contents are HTML encoded in all scenarios.

### Actual result
The messages from steps 4 and 10 are different.

### Further technical details
In the `onErrors` method in `jquery.validate.unobtrusive.js` we can see that unobtrusive expects that the message has already been HTML encoded because it uses `$("<li />").html(this.message).appendTo(list);` but we can see from the HTML that is generated is only attribute encoded ( `data-val-length="Property1: &lt;b> Length must be 2 or less"`) so when it is added to the validation summary control, the HTML is parsed.

By comparison, when the validation summary control renders error messages server side, it HTML encodes all of its contents.

 I'm not familiar with the internal architecture of the relationship between MVC and unobtrusive, but there seem to be two obvious ways to address this problem:
1. Change unobtrusive to use `.text(this.message)` rather than `.html(this.message)`
2. Change MVC to automatically HTML encode the attributes when they are written out to the client

Unfortunately, both of these options would be breaking changes for any applications that expect to be able to write HTML into error messages.

I don't know of any workarounds for this problem, but one would be appreciated. 

Tested with the following configuration:
- ASP.Net 4.6.2
- MVC 5.2.3
- Razor 3.2.3
- Unobtrusive Validation 3.2.3

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
