### ISSUE TITLE
EF7 override Identity nullable columns.

### ISSUE THREAD

**Issue by urielzen** [dotnet/aspnetcore#48325]
We have a project with nullable errors enabled, and we just recently upgraded from EF6 to EF7 and that uncovered some nullable errors in our code around Identity properties. Email for example is nullable in the `Microsoft.AspNetCore.Identity.IdentityUser` class

```csharp
public class IdentityUser<TKey> where TKey : IEquatable<TKey>
{
    /// <summary>
    /// Gets or sets the email address for this user.
    /// </summary>
    [ProtectedPersonalData]
    public virtual string? Email { get; set; }

```

We would like to keep the email required/not nullable, so we don't have to refactor the thousand places in our code that are giving us errors because Email now is suddenly nullable. But if I try to override the nullability for the property in my ApplicationUser class, I get an error
```csharp
public partial class ApplicationUser : IdentityUser<string>
{
    public override string Email { get; set; } = null!;

```

```
CS8765 - Nullability of type of parameter 'value' doesn't match overridden member (possibly because of nullability attributes).
```

I guess we can add the thousand null checks in our code where we have the errors, but we would very much like another easier to implement approach if possible.

Thanks

**Comment by urielzen** [comment]
@ajcvickers @roji  Thanks for moving to the correct repo, and thanks for the insight, yes I agree it wasn't EFCore7 what introduced the new error, but instead some new nullability error check in NET7 that wasn't in NET6.

NET6 didn't warn/error about overridden properties with different nullability, but NET7 does.

Our existing code, in NET6, used to think that the email property (and others) was not nullable so the code around that was written that way. We can use Fluent API to change the db, but that won't help with the many errors that now we have in the code, because the properties were actually nullable all this time. Checking for nulls or adding bangs is precisely the refactoring that we are trying to avoid.

Shadowing the properties as noted in my second comment above actually fixed it for us, without the need to do the full refactor.

Closing this as we are good with this solution. But I'm still open to hear from someone that can suggest a different approach.
Thanks!

**Comment by roji** [comment]
.NET 6.0 certainly did warn about overriding properties with different nullability - it's just that the identity types weren't yet annotated in ASP.NET 7.0 (this happened for 7.0 in #40007). Before 7.0, Email (and everything else) was simply oblivious, so the compiler didn't generate any warnings either way.
