### ISSUE TITLE
install .net8.0 but csproject use .net7.0 'Swashbuckle.AspNetCore.Filters.AddResponseHeadersFilter' could not be located

### ISSUE THREAD

**Issue by qssq1** [dotnet/aspnetcore#48347]
### Description

My computer has .NET 8.0 installed but my project is configured with .NET 7.0 using ASP .NET Core Swagger, this project used to work correctly, I did some version upgrades to these libraries later, and I reinstalled my computer, resulting in these headaches
```
System.InvalidOperationException: A suitable constructor for type 'Swashbuckle.AspNetCore.Filters.AddResponseHeadersFilter' 
```
I have configured both the rd.xml and source generation related to AOT, but these issues have occurred due to the computer being reinstalled

### Reproduction Steps

```
<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Condition="$(DefineConstants.Contains('PUSH'))" Version="1.1.0" />
	
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.6" />
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
		
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
		<!--<PackageReference Include="System.Data.SqlClient" Version="4.8.5" />-->
		<!--<PackageReference Include="System.Private.ServiceModel" Version="4.10.2" />-->
		<PackageReference Include="Dapper" Version="2.0.123" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
		<PackageReference Include="System.ServiceModel.Duplex" Version="4.8.*" />
		<PackageReference Include="System.ServiceModel.Federation" Version="4.8.*" />
		<PackageReference Include="System.ServiceModel.Http" Version="4.8.*" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.*" />
		<PackageReference Include="System.ServiceModel.Security" Version="4.8.*" />

	</ItemGroup>
```

```
	<PropertyGroup>
		<PublishAot>true</PublishAot>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<Platforms>AnyCPU;x64</Platforms>
		<UserSecretsId>37c2da8e-4c70-4b1a-b525-dc02325e9e4c</UserSecretsId>
		<OutputType>Exe</OutputType>
		<DebugType>embedded</DebugType>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<ErrorReport>send</ErrorReport>
		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<NoWin32Manifest>true</NoWin32Manifest>
```

### Expected behavior

open url display web  

### Actual behavior

thro exception

```
```
System.InvalidOperationException: A suitable constructor for type 'Swashbuckle.AspNetCore.Filters.AddResponseHeadersFilter' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider, Type, Object[]) + 0x209
         at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.CreateFilter[TFilter](FilterDescriptor) + 0x1e
         at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.<>c__DisplayClass4_0.<Configure>b__2(FilterDescriptor filterDescriptor) + 0x20
         at System.Collections.Generic.List`1.ForEach(Action`1) + 0x3a
         at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.Configure(SwaggerGeneratorOptions) + 0xd6         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String) + 0x92
         at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value() + 0xa1
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSiSite, RSiSite, RuntimeRSite, RuntSitSite,SiSite,Site, SSite, RuntimeResolverContext) + 0x1d
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) + 0x110
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext) + 0x7f
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite, RuntimeResolverContext) + 0x1d
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) + 0x110
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite, ServiceProviderEngineScope) + 0x3e
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type, ServiceProviderEngineScope) + 0x69         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware) + 0x1a
         at webapi_mes!<BaseAddress>+0x160d34d
         at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x150
      --- End of stack trace from previous location ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
         at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(TargetInvocationException) + 0x17
         at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame) + 0x17a
         at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame) + 0x2d
         at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments) + 0x81
         at webapi_mes!<BaseAddress>+0x13c089a
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) + 0x102
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) + 0x102
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) + 0x102
         at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context) + 0x11a
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__238`1.MoveNext() + 0x3c2

```


### Regression?

_No response_

### Known Workarounds

use old version   uninstall .net8.0

### Configuration

asp.net core  run .net 7.0
but computer .net 8.0 in install
opera system:window11

x64
use aot compile  
google chrome 

log

D:\dev\company_project\XXX_webapi\webapi_mes>dotnet publish  -r win-x64 -c YTLSX_R
MSBuild version 17.7.0-preview-23251-02+59879b095 for .NET
  正在确定要还原的项目…
  已还原 D:\dev\XXX_project\sotrun_webapi\webapi_mes\webapi_mes.csproj (用时 6.07 sec)。
C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInf
erence.targets(287,5): message NETSDK1057: 你正在使用 .NET 的预览版。请参阅 https://aka.ms/dotnet-support-policy [D:\dev\company_pro
ject\XX_webapi\webapi_mes\webapi_mes.csproj]

project\xxx_webapi\webapi_mes\webapi_mes.csproj]
    正在创建库 bin\xx_R\net7.0\win-x64\native\webapi_mes.lib 和对象 bin\YTLSX_R\net7.0\win-x64\native\webapi_mes.exp
  webapi_mes -> D:\dev\company_project\xxx_webapi\webapi_mes\bin\xx_R\net7.0\win-x64\publish\

### Other information

Because the computer has .NET 8.0 installed, AOT automatically uses 8.0 when compiling, but I specify 7.0 in the configuration file

How can I fix this error?



```
D:\dev\company_project\sotrun_webapi\webapi_mes>dotnet --info
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.306 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\dev\company_project\sotrun_webapi\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

D:\dev\company_project\sotrun_webapi\webapi_mes>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\

.NET workloads installed:
没有要显示的已安装工作负载。

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: x64
  Commit:       84a3d0e37e

.NET SDKs installed:
  6.0.306 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\dev\company_project\xxx_webapi\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

rd.xml

```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
	<Application>
		<Assembly Name="System.Linq" Dynamic="Required All">
			<Type Name="System.Linq.Enumerable" Dynamic="Required All">
				<Method Name="ToArray" Dynamic="Required">
					<GenericArgument Name="System.Int32,System.Private.CoreLib" />
				</Method>
			</Type>
		</Assembly>
		<Assembly Name="System.Private.ServiceModel" Serialize="Required All" Dynamic="Required All" Activate="Required All">
		</Assembly>
		<Assembly Name="Swashbuckle.AspNetCore.SwaggerUI" Serialize="Required All" Dynamic="Required All" Activate="Required All" DataContractSerializer="Required All" DataContractJsonSerializer="Required All"  MarshalObject="Required All">
			
			<Type Name="Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor" Dynamic="Required All"/>

		</Assembly>

		<Assembly Name="System.Text.Json">
			<Type Name="System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2[[System.Collections.Generic.IEnumerable`1[[Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor,Swashbuckle.AspNetCore.SwaggerUI]],mscorlib],[Swashbuckle.AspNetCore.SwaggerUI.UrlDescriptor,Swashbuckle.AspNetCore.SwaggerUI]]"  Dynamic="Required All" />

			<Type Name="System.Text.Json.Serialization.Converters.EnumConverter`1[[Swashbuckle.AspNetCore.SwaggerUI.ModelRendering,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Swashbuckle.AspNetCore.SwaggerUI.DocExpansion,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Nullable`1[[System.Int32,mscorlib]],mscorlib]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Converters.NullableConverter`1[[System.Int32,mscorlib]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Converters.EnumConverter`1[[Swashbuckle.AspNetCore.SwaggerUI.DocExpansion,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Converters.EnumConverter`1[[Swashbuckle.AspNetCore.SwaggerUI.DocExpansion,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2[[System.Collections.Generic.IEnumerable`1[[Swashbuckle.AspNetCore.SwaggerUI.SubmitMethod,Swashbuckle.AspNetCore.SwaggerUI]],mscorlib],[Swashbuckle.AspNetCore.SwaggerUI.SubmitMethod,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />
			<Type Name="System.Text.Json.Serialization.Converters.EnumConverter`1[[Swashbuckle.AspNetCore.SwaggerUI.SubmitMethod,Swashbuckle.AspNetCore.SwaggerUI]]" Dynamic="Required All" />

			<Type Name="System.Text.Json.Serialization.JsonSerializerContext" Dynamic="Required All">
			</Type>
		</Assembly>

			<Assembly Name="System.ComponentModel.TypeConverter">
				<Type Name="System.ComponentModel.TypeConverter" Dynamic="Required All" />
				<Type Name="System.ComponentModel.StringConverter" Dynamic="Required All" />
				<Type Name="System.ComponentModel.Int32Converter" Dynamic="Required All" />
			</Assembly>
			<Assembly Name="Microsoft.Extensions.Configuration.Json">
				<Type Name="Microsoft.Extensions.Configuration.Json.JsonConfigurationSource" Dynamic="Required All" />
			</Assembly>
			<Assembly Name="Newtonsoft.Json">
				<Type Name="Newtonsoft.Json.Serialization.ObjectConstructor`1[[System.Object,System.Private.CoreLib]]" Dynamic="Required All" />
			</Assembly>

		
</Application>
</Directives>

```

source generate
```

namespace webapi_mes.api.aot
{
    //https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-7-0#source-generation-support-in-aspnet-core
    [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(JSONResultInfo))]
    [JsonSerializable(typeof(System.Object))]
    [JsonSerializable(typeof(Newtonsoft.Json.Linq.JObject))]
    [JsonSerializable(typeof(System.Boolean))]
    [JsonSerializable(typeof(VersionModel))]
    [JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, System.String>))]
    internal partial class MyJsonContext : JsonSerializerContext
    {
    }

}
```

**Comment by captainsafia** [comment]
@qssq1 Can you share the contents of your Swashbuckle configuration in your `Program.cs` or `Startup.cs`? It's not clear that the issue you've described is directly related to AoT behavior as opposed to the way that your app is configured.

Also you might have some luck filing this issue in the https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters repo.
