### ISSUE TITLE
BlazorApp build errors using Visual Studio Code

### ISSUE THREAD

**Issue by danbro-ok** [dotnet/aspnetcore#48372]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

BlazorApp created by dotnet, builds correctly (and runs) with dotnet, will not build using Visual Studio Code:
_Imports.razor(10,17): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'BlazorApp'
![Screenshot from 2023-05-13 20-01-16](https://github.com/dotnet/core/assets/133549018/b0f5f1db-56cf-423d-854e-6e777f59404f)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you try to run the same command the VSCode runs (the first line in the log, after the "Executing task") and see if you get the same output. You probably will. And then, can you try to remove the parameters passed to it and just run "dotnet build ...` part from CLI and see if it behaves same way?

If there is still an error, can you share the output from `dotnet --info` from command prompt as well as from VS Code terminal?
