### ISSUE TITLE
Add a PreLoadSession Attribute/Filter with a timeout parameter

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#4837]
Session is assumed to be stored as a distributed resource so loading it should be done asynchronously. ISession has a LoadAsync API but nobody calls it today. If you access the values then it loads synchronously inline.

Proposal: Add a PreLoadSession Attribute/Filter with an optional timeout, and perhaps an option to continue or fail if session is unavailable. This could be applied per action, controller, or globally. When run this filter would call ISession.LoadAsync.

RE: https://github.com/aspnet/Session/issues/158

**Comment by Rick-Anderson** [comment]
Ping me when this is closed with a sample and I'll add it to [Load session state asynchronously](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.

**Comment by Tratcher** [comment]
@DamianEdwards this was your request, right?

**Comment by MV10** [comment]
What's the status on this? I see early preview tags, is it in RC1? 

How does distributed caching usage change versus what is currently documented?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.0#load-session-state-asynchronously

**Comment by pranavkm** [comment]
@MV10 this is sitting in backlog and wasn't resolved in the 3.0 release.

**Comment by ericsampson** [comment]
@DamianEdwards @Tratcher it would indeed be handy to have what you stated originally:
"PreLoadSession Attribute/Filter with an optional timeout, and perhaps an option to continue or fail if session is unavailable. This could be applied per action, controller, or globally. When run this filter would call ISession.LoadAsync"

**Comment by Tratcher** [comment]
@ericsampson @MV10 would one of you like to attempt implementing this?

**Comment by MV10** [comment]
No, we're getting away from the use of session. I was led here when we got caught out by the LoadAsync thing and also the fact that session internally requires the non-async methods from `IDistributedCache` (as I recall, checking whether it's loaded triggers a synchronous call to do a load -- seems like a bad/unexpected side-effect from an innocent-looking flag-style property check).

**Comment by pranavkm** [comment]
@Tratcher do you think it's still valuable for us to pursue work here?

**Comment by Tratcher** [comment]
It would be a useful addition, but there's not a lot of demand for it. Closing.
