### ISSUE TITLE
[Blazor] Discourage use of `DotNet.invokeMethod` and `DotNet.invokeMethodAsync`

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#48396]
The `DotNet.invokeMethod` and `DotNet.invokeMethodAsync` APIs currently throw when more than one interactive runtime is present. We should be encouraging developers to replace usage of these methods with `DotNetObjectReference` method invocations so that JS->.NET interop works regardless of which combination of .NET runtimes are available.

We should consider logging a warning during development if we detect usage of `DotNet.invokeMethod` or `DotNet.invokeMethodAsync`.

**Comment by ghd258** [comment]
这些什么时候能处理完成

**Comment by mkArtakMSFT** [comment]
Closing as we don't think we'll do this.
