### ISSUE TITLE
model binding to one class doesn't work as expected and documented

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/aspnetcore#48391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to model bind all parameters (body, path, query, header, custom model bound) into one flat class.  Simple reduced example:  
```
public record ArtistRequestFlat
{
    [FromBody]
    public string? Name { get; init; }

    [FromBody]
    public string? StageName { get; init; }

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }
}
```
Using this model in a controller method...
```
[Route("one-class")]
[HttpPost
public ActionResult<ArtistRequest> PostOneClass(ArtistRequest artistRequest)
{
    return Ok(artistRequest);
}
```
...doesn't fill the query and header parameter, because even there is no explicit `[FromBody]` before the method parameter it is added by ApiExplorer by convention and then everything is treated as from body. It doesn't make sense by the interface and the result is not expected, but this is how it is documented. 

The stated solution is to use an (unintuitive) `[FromQuery]` attribute:
```
[Route("one-class-fromquery")]
[HttpPost]
public ActionResult<ArtistRequest> PostOneClassFromQuery([FromQuery] ArtistRequest artistRequest)
{
    return Ok(artistRequest);
}
```
This still doesn't work. It produces an error:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-466102e0747df4fc2cc15e4d265456f2-813ed2b8da192054-00",
    "errors": {
        "Accept-Language": [
            "The PreferredLanguages field is required."
        ]
    }
}
```
The same error occurs even when there is only one parameter attributes with `[FromBody]`.

A similar example with two ´[FromBody]` attributes has been posted in a swashbuckle issue:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2315
The dotnet version was net6.0 and it apparently worked there. Did something change for NET 7?

The example from https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#sources also shows an example, with a `[FromQuery]` attribute in the Instructor class. but it doesn't work, as I explained above. See also: https://github.com/dotnet/AspNetCore.Docs/issues/29295

The only working solution that I found was to use a separate class for the body:
```
public record Artist
{
    public string? Name { get; init; }

    public string? StageName { get; init; }
}

public record ArtistRequest
{
    [FromBody]
    public Artist Artist { get; init; }

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }
}
```
This requires two DTO classes. Is there any other working solution with just one flat class?

### Expected Behavior

**1. )** It is expected that the model binding works flawless with one class:
```
[Route("one-class")]
[HttpPost
public ActionResult<ArtistRequest> PostOneClass(ArtistRequest artistRequest)
{
    return Ok(artistRequest);
}

public record ArtistRequestFlat
{
    [FromPath]
    public guid Id { get; init; }

    [FromBody]
    public string? Name { get; init; }

    [FromBody]
    public string? StageName { get; init; }

    [FromBody]
    public date? Age{ get; init; }

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }

    public IPAddress IpAddress  { get; init; } //from custom model binder factory
}
```
ApiExplorer should **honor the attributes in the class**!

**2.)** The current way to add `[FromQuery]' is unintuitive. More clear would be to have an attribute like `[FromMixedSources]`
```
`public ActionResult<ArtistRequest> PostOneClass([FromMixedSources] ArtistRequest artistRequest)`
```
**3.)** Even with the current solution to use '[FromQuery]' in the controller method the model should be bound correctly using a flat model class.

**4.)** If the method parameter has a `[From Body]` attribute or it is added by convention specific parameters should still be honored. The current behavior to treat all properties as `[From Body}` is documented, but completely unintuitive and not an expected behavior. More specific settings should have precedence over more general settings.

This should work and **all properties should be filled from the respective source**. If body parameters are read first the other parameters can be added without complications.

So if a `[FromBody]` is set, it should be used only for properties that don't have a attribute or are handled by a custom model binder.

```
[Route("one-class")]
[HttpPost
public ActionResult<ArtistRequestFlat> PostOneClassFromQuery([FromBody] ArtistRequestFlat artistRequest)
{
    return Ok(artistRequest);
}

public record ArtistRequestFlat
{
    [FromPath]
    public guid Id { get; init; }

    public string? Name { get; init; } //[FromBody]

    public string? StageName { get; init; } //[FromBody]

    public date? Age{ get; init; } //[FromBody]

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }

    //if necessary [FromCustomBinder]
    public IPAddress IpAddress  { get; init; } //from custom model binder factory
}
**6.)** The ApiExplorer should provide corrrect information for Swashbuckle to create a correct SwaggerUI, which is not working right now either.
```

### Steps To Reproduce

```
[ApiController]
[Route("[controller]")]
public class BasicModelBindController : ControllerBase
{
    public BasicModelBindController()
    {

    }

    [HttpPost]
    public ActionResult<ArtistRequestFlat> PostOneClassFromQuery([FromQuery] ArtistRequestFlat artistRequest)
    {
        return Ok(artistRequest);
    }
    
    public record ArtistRequestFlat
    {
        [FromBody]
        public string? Name { get; init; }
    
        [FromHeader(Name = "Accept-Language")]
        public List<string> PreferredLanguages { get; init; }
    
        [FromQuery]
        public string? SelectedLanguage { get; init; }
    }
}
```

### Exceptions (if any)

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-107df00d5fa547d3ee67848839a3c1b8-b3356ad94f9df0f3-00",
  "errors": {
    "$": [
      "The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.",
      "The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
    ]
  }
}
```

### .NET Version

.net 7.0.202

**Comment by mitchdenny** [comment]
In your sample you define `ArtistRequestFlat` and in the controller action you use `ArtistRequest`. Could you check your repro? It would be good if you could post a minimal repro into a GitHub repo that we can just clone down and run so we can look into this.

**Comment by davidfowl** [comment]
This is by design. You can't have multiple [FromBody] attributes. When you add [FromBody] that instructs the model binding system to go into "formatter mode" and deserializes the body as a single unit. In essence, the model binding system does not want to "see through" formatters and instead, it delegates to them to handle processing the entire payload.

**Comment by KillerBoogie** [comment]
> This is by design. You can't have multiple [FromBody] attributes. When you add [FromBody] that instructs the model binding system to go into "formatter mode" and deserializes the body as a single unit.

I don't see that deserializing the body as a single unit is the problem, if other attributes would be honored after [FromBody] and just write to the same class. The current design is not what one expects. 

Does this mean it is not possible at all to bind all parameters to one class? It seems that it is possible with a custom model binder: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2315. If it is possible with a custom model binder why is the framework model binder not able to do this?

**Comment by davidfowl** [comment]
Think of a single [FromBody] like a call to Deserialize the entire body as a single payload into whatever the attribute points to. That's the reason this works:

```C#
public record Artist
{
    public string? Name { get; init; }

    public string? StageName { get; init; }
}

public record ArtistRequest
{
    [FromBody]
    public Artist Artist { get; init; }

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }
}
```

SelectedLanguage comes from the query string, PreferredLanguages is a header, and the body is deserialized as an Artist. 

In the above example, Artist can't be split into individual properties inline:

```
public record ArtistRequest
{
    [FromBody]
    public string? Name { get; init; }

    [FromBody]
    public string? StageName { get; init; }

    [FromHeader(Name = "Accept-Language")]
    public List<string> PreferredLanguages { get; init; }

    [FromQuery]
    public string? SelectedLanguage { get; init; }
}
```

This doesn't work.

> If it is possible with a custom model binder why is the framework model binder not able to do this?

Custom model binders can write whatever logic they want. You can invent your own de-serializer in there. The framework treats bodies as a single payload and we don't break it down into key value pairs that can be bound further.

**Comment by KillerBoogie** [comment]
Thanks David for the extra information! So there is no way to achieve a flat model with mixed binding!? 

A flat model seems like a natural requirement. If the id comes from the route and another property comes from a query shouldn't affect the design of my model. I shouldn't be forced to change the design of my model and make it more complicated and harder to use, just because of artificial limitations of the model binder. 

Shall I propose a feature request or is it not worth the effort, because it will be anyway tagged as "not planned"?

**Comment by davidfowl** [comment]
> Thanks David for the extra information! So there is no way to achieve a flat model with mixed binding!?

You can write a JsonValueProviderFactory and explode the body into name values pairs and it should work like you want it to. It would be inefficient if your JSON payloads are of any significant size.

> A flat model seems like a natural requirement. If the id comes from the route and another property comes from a query it shouldn't affect the design of my model. I shouldn't be forced to change the design of my model and make it more complicated and harder to use, just because of artificial limitations of the model binder.

I can see why you'd say that but in practice the body is different. Binding parts of the body into the model is a piece meal way would be very inefficient. It requires turning the body into key value pairs and binding them.

> In the meanwhile I found a lot of posts and issues where people try to achive the same thing and fail. Shall I propose a feature request or is it not worth the effort, because it will be anyway tagged as "not planned"?

No, we have no plans to implement this.

**Comment by KillerBoogie** [comment]
> You can write a JsonValueProviderFactory and explode the body into name values pairs and it should work like you want it to. It would be inefficient if your JSON payloads are of any significant size.

sorry, I don't understand why I have to explode the body into key value pairs. https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2315 achieved to set route and body attributes into one flat class. 

> I can see why you'd say that but in practice the body is different. Binding parts of the body into the model is a piece meal way would be very inefficient. 

That is exactly what I mean. A technical concern drives the design, which is not good.

**Comment by davidfowl** [comment]
The model binder implementation in that issue is really using the model binding system. It’s hard coding looking at  attributes *after* assuming the entire model is being deserialized from JSON.
