### ISSUE TITLE
Future Investments: Model Binding

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#4839]
This is a place for tracking feedback and related bugs for scoping future investments in Model Binding.

### Related Issues
#6109 Question: call ModelBinding manually?
#4437 Using validation without model state and controller
#6014 Using DI as a factory and **then** model binding the object
#4718 Add a secure binding option to model binders
#1786 Support binding immutable types by binding to the constructor

**Comment by KrzysztofBranicki** [comment]
@rynowak I think that your link to issue about support of binding immutable types is pointing to something unrelated. Anyway this feature would be highly appreciated especially when you design CQRS style API where commands and queries by definition should be immutable. BTW even EntityFramework supports deserializing entity via constructor nowadays so why MVC model binders still require public setters and by doing so discourage good practices like immutable messages/DTOs.

**Comment by msschl** [comment]
#1786 Support binding immutable types by binding to the constructor

I would very much appreciate this feature. 😍  Now that `System.Text.Json` supports `JsonConstructor` in .net 5.0, it feels incomplete not having the ability for immutable complex types in asp net core.

**Comment by msschl** [comment]
@rynowak It looks like #1786 `Support binding immutable types by binding to the constructor` links to the wrong issue

**Comment by msschl** [comment]
Is this issue relevant for .net 6 planning?
