### ISSUE TITLE
Blazor WebAssembly integration with Msal.js fails fatally when changing Authority URL

### ISSUE THREAD

**Issue by richardhauer** [dotnet/aspnetcore#48404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `Microsoft.AspNetCore.Components.WebAssembly.Authentication` library packages a JS file - `AuthenticationService.ts` that is a shim between the library code and MSAL.js.  This service makes assumptions about the number of accounts cached by the MSAL.js service and their validity with the currently configured authority.  For example, https://github.com/dotnet/aspnetcore/blob/b300006bf317461d026c73a7775f7ae06e1a2ca8/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts#LL152C55-L152C55

The `getAccount()` method linked above is used during the login process and when the Authority is changed between app releases,  anyone with existing cached authentication details will get stuck in an infinite login loop.

The behaviour experienced in `net 6` vs `net 7` are slightly different. In net 6, the application seems to loop indefinitely - being unable to complete a code grant flow, failing on the step where the token is retrieved from the "/token" endpoint. In net 7 the system seems to get past this point, but the result is that two sets of credentials are cached in the browser `localStorage`. Using `IAccessTokenProvider` to retrieve a token for use with downstream APIs always returns "RedirectRequired" so the token is unreachable from the app code.

### Expected Behavior

MSAL interop services should be able to correctly navigate circumstances where there are cached credentials that are out of context for the current login process, rather than assuming if there are "any accounts available, we can just use the first one".

### Steps To Reproduce

- Configure an AAD B2C tenant in the normal way.
- Add Front Door with and configure 2 custom domain names
- Update AAD to support access from the new custom domain names

You will now have 3 valid "authority" names to use when accessing B2C.

- Using the standard Blazor WASM template, connect to B2C and use the default B2C authority urls
- Login normally, close the browser
- Update the Authority in the settings file to use the custom domain name
- Start up the WASM app again and you will no longer be able to log in (net6) or you will be constantly directed to re-login by the IAccessTokenProvider (net7)

Logging out removes all items from the cache (which is also a bug) which does resolve the issue, but only because all the cache is dumped. It's not reasonable to expect everyday users of websites to know how to clear localStorage. Even clearing the browser cache does not resolve the problem.

### .NET Version

net6 and net7

### Anything else?

We have some workarounds in place where we check the currently configured authorities and programatically cleanup the localStorage. This permanently resolves the issue but also does not provide for the support of multiple logins in localStorage or multiple Authorities.

Whether it's reasonable for multiple identities to be cached at the same time is a matter for debate. If it's not reasonable then the MSAL.js should take steps to remove accounts from the wrong Authority from the cache rather than blindly loading them. If it is reasonable then "Authentication.MSAL" should provide the necessary overloads to handle this situation gracefully. Either way there is a bug that needs to be fixed here, IMHO.

**Comment by javiercn** [comment]
@richardhauer thanks for contacting us.

This is not a scenario that we currently handle. You can provide your own AuthenticationService implementation as described [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#replace-the-microsoft-authentication-library-for-javascript-msaljs) to customize it to your needs.

**Comment by richardhauer** [comment]
Well, I am surprised that changing from one Authority to another would be considered "not supported". It seems like a pretty common thing to need to do.

The scenario we find ourselves in is that we are using the OOTB User Flow in B2C and we are being attacked. The B2C team has suggested we need a custom solution involving IEF custom flows and Front Door WAF for bot protection. But we can't transition to Front Door because this bug means our users get stuck in a login loop.
