### ISSUE TITLE
EnableRequestDelegateGenerator by default for PublishTrimmed apps

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#48416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently ASP.NET apps have the following source generators enabled by default when `PublishAot=true`:

* EnableRequestDelegateGenerator 
* EnableConfigurationBindingGenerator

These source generators are also valuable for `PublishTrimmed=true` apps that don't use Native AOT because they eliminate trim warnings in your app.

### Describe the solution you'd like

We should enable these source generators by default when `PublishTrimmed=true`. Just like we do for PublishAot.

**Comment by davidfowl** [comment]
YESSSS

**Comment by mitchdenny** [comment]
This is a pretty big step. We'll probably want to look at this after the following edge cases:  #47339

**Comment by davidfowl** [comment]
Agreed. It might be worth comparing what breaks outright today without the source generator with trimming on.

@eerhardt does ASP.NET Core do aggressive trimming by default now in .NET 8? (Not partial)

**Comment by davidfowl** [comment]
We should do this only if TrimMode is full.
