### ISSUE TITLE
./restore.cmd problem 

### ISSUE THREAD

**Issue by chenzongyuanczy** [dotnet/aspnetcore#48420]
After executing ./restore.cmd
error : Sequence contains no matching element

PS E:\学习文件夹\sourceCode\aspnetcore> ./restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in E:\Program Files.
Detected JDK in E:\Program Files\Java\jdk-11 (via JAVA_HOME)
Attempting to install dotnet from public location.
dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "E:\学习文件夹\sourceCode\aspnetcore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 6.0.401
dotnet-install: Installation finished

欢迎使用 .NET 6.0!
---------------------
SDK 版本: 6.0.401

遥测
---------
.NET 工具会收集用法数据，帮助我们改善你的体验。它由 Microsoft 收集并与社区共享。你可通过使用喜欢的 shell 将 DOTNET_CLI_TELEMETRY_OPTOUT 环境变量设置为 "1" 或 "true" 来选择退出遥测。

阅读有关 .NET CLI 工具遥测的更多信息: https://aka.ms/dotnet-cli-telemetry

----------------
已安装 ASP.NET Core HTTPS 开发证书。
若要信任该证书，请运行 "dotnet dev-certs https --trust" (仅限 Windows 和 macOS)。
了解 HTTPS: https://aka.ms/dotnet-https
----------------
编写你的第一个应用: https://aka.ms/dotnet-hello-world
查找新增功能: https://aka.ms/dotnet-whats-new
浏览文档: https://aka.ms/dotnet-docs
在 GitHub 上报告问题和查找源: https://github.com/dotnet/core
使用 "dotnet --help" 查看可用命令或访问: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

  正在确定要还原的项目…
  工具“dotnet-serve”(版本“1.7.139”)已还原。可用的命令: dotnet-serve
  工具“playwright-sharp-tool”(版本“0.170.2”)已还原。可用的命令: playwright-sharp

  还原成功。
  已还原 C:\Users\肥肠\.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.23060.6\tools\Tools.proj (用时 131 ms)。
  正在确定要还原的项目…
  已还原 E:\学习文件夹\sourceCode\aspnetcore\eng\tools\GenerateFiles\GenerateFiles.csproj (用时 30 ms)。
  GenerateFiles -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.props
  GenerateFiles -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.targets
Attempting to install dotnet from public location.
dotnet-install: .NET Core Runtime with version '2.1.30' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
dotnet-install: Adding to current process PATH: "E:\学习文件夹\sourceCode\aspnetcore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
Attempting to install dotnet from public location.
dotnet-install: ASP.NET Core Runtime with version '3.1.32' is already installed.
  正在确定要还原的项目…
  已还原 E:\学习文件夹\sourceCode\aspnetcore\eng\tools\RepoTasks\RepoTasks.csproj (用时 109 ms)。
  RepoTasks -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\RepoTasks\Release\net472\RepoTasks.dll
  RepoTasks -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\RepoTasks\Release\net6.0\RepoTasks.dll

  正在确定要还原的项目…
  工具“dotnet-serve”(版本“1.7.139”)已还原。可用的命令: dotnet-serve
  工具“playwright-sharp-tool”(版本“0.170.2”)已还原。可用的命令: playwright-sharp

  还原成功。
  所有项目均是最新的，无法还原。
Attempting to install dotnet from public location.
dotnet-install: .NET Core Runtime with version '2.1.30' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
dotnet-install: Adding to current process PATH: "E:\学习文件夹\sourceCode\aspnetcore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
Attempting to install dotnet from public location.
dotnet-install: ASP.NET Core Runtime with version '3.1.32' is already installed.
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:14.34

  正在确定要还原的项目…
  工具“dotnet-serve”(版本“1.7.139”)已还原。可用的命令: dotnet-serve
  工具“playwright-sharp-tool”(版本“0.170.2”)已还原。可用的命令: playwright-sharp

  还原成功。
  所有项目均是最新的，无法还原。
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
  GenerateFiles -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.props
  GenerateFiles -> E:\学习文件夹\sourceCode\aspnetcore\artifacts\bin\GenerateFiles\Directory.Build.targets
Attempting to install dotnet from public location.
dotnet-install: .NET Core Runtime with version '2.1.30' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
Attempting to install dotnet from public location.
dotnet-install: Using alternate version 6.0.9 found in https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.9-servicing.22419.5/runtime-productVersion.txt
dotnet-install: .NET Core Runtime with version '6.0.9' is already installed.
dotnet-install: Adding to current process PATH: "E:\学习文件夹\sourceCode\aspnetcore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
Attempting to install dotnet from public location.
dotnet-install: ASP.NET Core Runtime with version '3.1.32' is already installed.
  正在确定要还原的项目…
E:\学习文件夹\sourceCode\aspnetcore\.dotnet\sdk\6.0.401\NuGet.targets(132,5): error : Sequence contains no matching element

生成失败。

E:\学习文件夹\sourceCode\aspnetcore\.dotnet\sdk\6.0.401\NuGet.targets(132,5): error : Sequence contains no matching element
    0 个警告
    1 个错误

已用时间 00:00:28.49
Build failed with exit code 1. Check errors above.

**Comment by chenzongyuanczy** [comment]
![1684998516849](https://github.com/dotnet/aspnetcore/assets/18733759/cac0c685-420e-484a-b48f-f9f94bacf08b)


If I annotate this paragraph, there's no problem

**Comment by mkArtakMSFT** [comment]
Also, can you please clarify which branch you've tried to build from?

**Comment by chenzongyuanczy** [comment]
resolved,The path cannot contain a Chinese name

**Comment by chenzongyuanczy** [comment]
The path cannot contain a Chinese name
