### ISSUE TITLE
Cookie name are case-sensitive

### ISSUE THREAD

**Issue by Maximys** [dotnet/aspnetcore#48421]
## Background and Motivation

ASP.NET Core compare name with OrdinalIgnoreCase.
But no RFC specify case-insensitive and all browser are case-sensitive.

These issue linked with [issue 62778 from .NET Runtime](https://github.com/dotnet/runtime/issues/62778)

## Proposed API

```diff
namespace Microsoft.Extensions.DependencyInjection;

public static class MvcCoreMvcCoreBuilderExtensions
{
+    public static IMvcCoreBuilder ConfigureRequestOptions(this IMvcCoreBuilder builder, Action<RequestOptions> setupAction)
}
```

## Usage Examples

```csharp
services
    .AddControllers()
    .ConfigureRequestOptions(o => {
        o.CookiesSettings.IsNameCaseInsensitive = false;
    })
```

I already implement required changes. You can view it [here](https://github.com/Maximys/aspnetcore/tree/feature/add-possibility-for-enable-case-insensitive-cookie). If it is normal for ASP.NET Core Team, I'll create relevant PR to current repository and then I'll fix [CookieCollection](https://github.com/dotnet/runtime/blob/7cf329b773fa5ed544a9377587018713751c73e3/src/libraries/System.Net.Primitives/src/System/Net/CookieCollection.cs#L15) inside .NET Runtime

**Comment by javiercn** [comment]
@Maximys thanks for contacting us.

Can you provide a more detailed explanation about the scenarios you are trying to enable and why are they important? What impact does this change has on a concrete scenario.

There are some aspects where the framework makes a different decision for usability criteria, like it looks in this case, or for example with paths in URLs, which are also case sensitive but that we treat as case-insensitive to avoid situations where a typed-in URL leads to a 404.

**Comment by Maximys** [comment]
@javiercn , just image, you have old PHP application, which used by a lot of clients. These application use case-sensitive cookie and each of them itrepretes by different scenarios. Now you want to replace this PHP application by ASP.NET Core, because .NET have better perfomance, maintainability, etc, but you can not change client applications, you can not say: _"Guys now you should change url's, which you use for access to us, because we'll overwrite our application to .NET and .NET does not support case-sensitive cookies"_.
I think, [JsonSerializer Options.PropertyNameCaseInsensitive](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.jsonoptions.jsonserializeroptions?view=aspnetcore-7.0) was added for simplify migration from Newtonsoft to [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json?view=net-7.0). My suggestion solves the similar problem for migration from some (programming language)/(framework) to C#/.NET

**Comment by Tratcher** [comment]
Is that old app intentionally using cookie names that differ only by case ("MyCookie" and "mycookiE")? That seems problematic, and uncommon enough that I don't think providing a first class option is necessary. A workaround would be to supply your own IRequestCookiesFeature with the changes via middleware.

API note: This wouldn't be an MVC extension, it would be its own top level IServiceCollection extension.
