### ISSUE TITLE
When I set builder.Logging.ClearProviders();, dotnet run stuck in building

### ISSUE THREAD

**Issue by lawsonli00** [dotnet/aspnetcore#48437]
I create an Asp.Net Core Web Api 7.0 project and use `Serilog`. After I setting `builder.Logging.ClearProviders();` in `Program.cs`, I can run my project with Visual Studio, but when I use CLI: `dotnet run` or `dotnet watch run`, my project stuck in `Building`. When I remove it, I can use `dotnet run` normally.

Below is my Program.cs:
```
var logger = new LoggerConfiguration().ReadFrom
.Configuration(builder.Configuration)
.Enrich
.FromLogContext()
.CreateLogger();

builder.Logging.ClearProviders();
builder.Logging.AddSerilog(logger);
```
My appsetting.json:
```
"Serilog": {
    "Using": [ "Serilog.Sinks.File" ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "../logs/webapi-.log",
          "rollingInterval": "Day",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {Level:u3} {Username} {Message:lj}{Exception}{NewLine}"
        }
      }
    ]
  }
```
And Nuget Packages:
```
<PackageReference Include="Serilog" Version="2.12.0" />
<PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
```
When I run `dotnet run`:
![image](https://github.com/dotnet/aspnetcore/assets/100395363/5628d763-2bba-4bcf-ac4f-424de8063a97)

Has anyone encountered this kind of problem and can explain it?

**Comment by GicaGashy** [comment]
I'm having the same issue. Could not find any answer yet.

**Comment by amcasey** [comment]
That's very weird, but it does repro for me.  You're also seeing `dotnet build` complete normally?  It's just `dotnet run` that hangs?

**Comment by lawsonli00** [comment]
@amcasey Yes, just `dotnet run`.

**Comment by amcasey** [comment]
@lawsonli00 Thanks for confirming.  But are you _also_ seeing the problem when you run `dotnet build`?

**Comment by amcasey** [comment]
What happens if you hit the API while it's hanging?  Assuming you're working from the template, it would be something like http://localhost:5092/weatherforecast.

**Comment by lawsonli00** [comment]
Hi @amcasey, When running `dotnet build`, there is no problem. When running `dotnet run`, it will always be stuck in `Building...` just like the picture in my question, nothing else is displayed.

**Comment by GicaGashy** [comment]
No, it basically hangs on `dotnet run` ... however the weird part is that the application actually runs normally.

**Comment by GicaGashy** [comment]
I'm not having that issue :/ .

**Comment by davidfowl** [comment]
I don't believe there's a hang, it just that nothing is logged. 

This is the output with logging on:

```C#
PS C:\Users\davifowl\source\repos\WebApplication2\WebApplication2> dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5236
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\davifowl\source\repos\WebApplication2\WebApplication2
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

This is what happens when you clear the loggers:

```
PS C:\Users\davifowl\source\repos\WebApplication2\WebApplication2> dotnet run
Building...
```

There's no "Build succeeded" log in either case, the application just runs.

**Comment by amcasey** [comment]
> @GicaGashy, I can't access my website. It doesn't automatically wake up the browser when it hangs, neither does typing a url.

@lawsonli00 Are you seeing serilog logs?

**Comment by lawsonli00** [comment]
@GicaGashy, did you use `builder.Logging.ClearProviders();`?

**Comment by GicaGashy** [comment]
I did, it made no difference.

**Comment by davidfowl** [comment]
Can the issue be closed?

**Comment by GicaGashy** [comment]
I don't know, maybe we have different issues to @lawsonli00 , I can log, I just have to specifically create a console sink while using Serilog in order to see logs on the console. For myself, I got it sorted out that way.

**Comment by lawsonli00** [comment]
@davidfowl I don't think this has anything to do with Serilog, as it only happens to me when I add `builder.Logging.ClearProviders();`.

**Comment by davidfowl** [comment]
@lawsonli00 did you read [my comment here](https://github.com/dotnet/aspnetcore/issues/48437#issuecomment-1572327910)?

**Comment by lawsonli00** [comment]
Yes @davidfowl, but why I can not access my application?

**Comment by davidfowl** [comment]
Thats' not logging's fault. Are you sure you're hitting the right URL?
