### ISSUE TITLE
Component inheritance seems to be broken

### ISSUE THREAD

**Issue by bfonde** [dotnet/aspnetcore#48447]
I am having problems with component inheritance after the latest VS update (17.6.1).  For example:

**Foo.razor:**

```
@inherits Bar

<div id="fooDiv">
    <button id="@Id" class="@Class" type="submit">Submit</button>
</div>
```

**Bar.razor:**

```
@code {
    [Parameter]
    public string? Id{ get; set; }
    [Parameter]
    public string? Class{ get; set; }
}
```

The above doesn't actually render the component.  It renders as:
`<foo id="foo" class="btn btn-secondary"></foo>`

When I take away the inheritance and put everything in Foo.razor it renders properly.  

The inheritance also did not work when deployed to Windows Server 2019, but it did work in the local dev environment prior to the latest VS update.

**Comment by Flachdachs** [comment]
I can reproduce the problem. Just create a project from standard template, e.g. `blazorserver`. Add the two files with the content from the opening posting to the `Shared` folder. Add `<Foo Id="x" Class="y"/>` to the file `Pages/Index.razor`. Build the project/solution. This gives you already a warning:
```
Index.razor(11, 1): [RZ10012] Found markup element with unexpected name 'Foo'.
If this is intended to be a component, add a @using directive for its namespace.
```
There is a `@using` directive for `Shared` in the global `_Imports.razor`. Adding a new one (to Index or Foo) creates another warning that it already exists. Foo is rendered as it is written in the Index.razor, not as the content of the component.

---
Add a `Qux.cs` with a content like so:

```
using Microsoft.AspNetCore.Components;
namespace BlazorApp1.Shared;
public class Qux : ComponentBase {
    [Parameter] public string? Id { get; set; }
    [Parameter] public string? Class { get; set; }
}
```
... and let Foo inherit from Qux, everything works fine.

**Comment by ScarletKuro** [comment]
> I am having problems with component inheritance after the latest VS update (17.6.1). For example:
> When I take away the inheritance and put everything in Foo.razor it renders properly.

The issues you referred to, along with the accompanying code snippet, point to the problem described here: https://github.com/dotnet/aspnetcore/issues/48281

Currently there is a regression in the new SDK version 7.0.302 that is documented here https://github.com/dotnet/razor/issues/8718

To address the problems, it's recommended to pin the SDK version to 7.0.203 using the `global.json` file.

You can also find this information in the Visual Studio 17.6.1 release notes: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.6.1 in section "Known Issues"
