### ISSUE TITLE
sourcelink dependency is out of date

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#48455]
We're 30 commits behind on our source link dependency as of 05/26/2023.

<img width="334" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1857993/e55a3052-ccd8-4993-bbf0-b0222b624c16">

**Comment by Tratcher** [comment]
I thought this was being removed?

**Comment by mitchdenny** [comment]
Apparently when this merges in it'll disappear automatically?

https://github.com/dotnet/arcade/pull/13260

**Comment by captainsafia** [comment]
> I thought this was being removed?

Correct, as @mitchdenny referenced, this will be resolved once that PR is merged. There isn't anything on our end tracking this though so I opened this issue per our build ops protocol.

**Comment by Tratcher** [comment]
Resolved? We now appear to be 13 days out of date.

**Comment by wtgodbe** [comment]
The Arcade change got reverted & can't go back in until after preview6 is released, so we can't remove the dependency until then.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/arcade/pull/13892 should allow us to remove the dependency entirely
