### ISSUE TITLE
Don't support async void as page handlers in razor pages 

### ISSUE THREAD

**Issue by blowdart** [dotnet/aspnetcore#4845]
And an exception should be thrown. So says @DamianEdwards.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
