### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by blake-fm** [dotnet/aspnetcore#48468]
https://github.com/dotnet/aspnetcore/blob/2a709351416d0ad85011805787dbdeaecb251b8f/CONTRIBUTING.md?plain=1#L94

cla.dotnetfoundation.org does not resolve.  Confirmed on a few unrelated DNS servers.

https://cla.azurewebsites.net/ works fine (DNS history says above domain was CNAME'd there).

**Comment by captainsafia** [comment]
Thanks for reporting this issue! It's being tracked at https://github.com/dotnet-foundation/wg-maintainers/issues/91. I'll kep this open in case we need to react to anything.

**Comment by captainsafia** [comment]
The link is fixed now.
