### ISSUE TITLE
Use of compounding bitwise |= true

### ISSUE THREAD

**Issue by blake-fm** [dotnet/aspnetcore#48464]
Hi, really minor, but there's a `|= true` in the `ComponentBase.cs` that should probably get cleaned up at some point.

https://github.com/dotnet/aspnetcore/blame/2a709351416d0ad85011805787dbdeaecb251b8f/src/Components/Components/src/ComponentBase.cs#L330

**Comment by danmoseley** [comment]
Do you want to offer a PR?

**Comment by blake-fm** [comment]
Sure!  First aspnetcore PR: _literally_ one character.  #48466
