### ISSUE TITLE
textarea binding does not work in Blazor Server when pasting long text

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#48505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

GIVEN I run a Blazor Server app
WHEN I paste long text into databound textarea
THEN the bound property's setter is never called.

In Blazor webassembly this works just fine: https://blazorrepl.telerik.com/mHEzQjbd07ANTmjy05

The text I try to paste is cca 15 characters x 1000 rows = 15kB.

### Expected Behavior

The databound property should be updated

### Steps To Reproduce

1. Create Blazor Server app using default template
2. Replace Index.razor with following code:
    
    ```razor
    @page "/"
    <PageTitle>Index</PageTitle>

    <p>Copy following text:</p>
    <textarea disabled rows="2">
        @string.Join('\n', Enumerable.Range(0, 1000).Select(i => $"Lorem ipsum dolor sit amet {i}"))
    </textarea>
    
    <p>to this textbox</p>
    <textarea @bind="StringProperty" placeholder="Enter long text (20 000 characters)" />
    
    <p>Length of entered text @StringProperty.Length</p>
    
    
    @code {
        public string StringProperty { get; set; } = string.Empty;
    
        public int StringPropertyLength => StringProperty.Length;
    }
    ```
3. Run and copy content of the first textarea into the second textarea. The last paragraph indicates that the property has never been set

An overlay "Attempting to reconnect"  appears for a second or two, which is acceptable
![image](https://github.com/dotnet/aspnetcore/assets/3494407/c1f2b019-65f6-4359-b55b-7fd6268bc700)

but the property is never updated:
![image](https://github.com/dotnet/aspnetcore/assets/3494407/da411a89-fc0b-46c7-9134-7de1869f5f1d)

### .NET Version
```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe
```

**Comment by javiercn** [comment]
@Liero thanks for contacting us.

You are hitting the max SignalR message size. See https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/InputLargeTextArea for how to work with large text areas in Blazor.

**Comment by Liero** [comment]
> You are hitting the max SignalR message size. 

But still, it is unacceptable to just silently swallow the error without any chance tell the user somethings wrong.

My customers are now submitting forms with values different from what they've typed. What can be more serious?

If there's a limit, then allow us to react when the limit is reached, please
