### ISSUE TITLE
ASP.NET Identity cookie value set to blank.

### ISSUE THREAD

**Issue by selectmarketingllc** [dotnet/aspnetcore#48529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an MVC Web App running at Azure, under .NET 7.  I am using ASP.NET Identity (v 7.0.5) with the following code.

`
builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<SmApplicationDbContext>()
    .AddRoleManager<RoleManager<IdentityRole>>()
    .AddDefaultTokenProviders();

builder.Services.ConfigureApplicationCookie(options =>
{
    options.ExpireTimeSpan = TimeSpan.FromDays(1);
    options.Cookie.MaxAge = TimeSpan.FromDays(1);
    options.SlidingExpiration = true;
});

builder.Services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(@"keys\"));
`

After 30 minutes, the value of .AspNetCore.Identity.Application cookie is set to blank.

In this image, I authenticated and the cookie was created at 23:53 on May 30, with at expiration of 23:53 on May 31, and a valid value.
![New](https://github.com/dotnet/aspnetcore/assets/107013798/50fe7ce9-6f9e-442e-b8f5-8c623d72e792)

In this image, I refreshed the page.  The Created date/time is the same.  Last Accessed is 00:36 on May 31, with an expiration of 00:36 on Jun 1.  However, the value is blank.
![Blank](https://github.com/dotnet/aspnetcore/assets/107013798/0c9e74d3-3e43-4101-9f48-06d0757851a4)

### .NET Version

.NET 7

**Comment by Tratcher** [comment]
Can you repro this and capture the response Set-Cookie headers? 
Debug level server logs might help too.

It's common to set the value to blank when deleting the cookie, but the expires is also set to be in the past in that case so the cookie is immediately removed from the client, it wouldn't show up as blank.

**Comment by selectmarketingllc** [comment]
For completeness, I will post all of the cookies, both screenshots from the browser dev tools, and captured in Fiddler.  The short answer appears to be that the Set-Cookie is setting the value to blank and the expiration to 1/1/1970.  However, Firefox still sees the expected expiration.


![New](https://github.com/dotnet/aspnetcore/assets/107013798/f988b203-e224-47e3-9d5a-65cbda30c67d)

##### GET /Account/Login HTTP/1.1 - RESPONSE 200
Set-Cookie: .AspNetCore.Antiforgery.cdV5uW_Ejgc=CfDJ8PllvhU4h2ROsOg2N9I0i4jxk-tPysIQQaL4dZ2N_2NcGOw6uLDuhOQxw8va0fswQiyDcrz6th-FkOmMJbNvrANRjz2R-qvf4JsxY5lfAXi_Scg1r8LXvT8ATvNKfGtzoQvGOSaj3icFKWtw_zAQ_vI; path=/; samesite=strict; httponly

Set-Cookie: .AspNetCore.Mvc.CookieTempDataProvider=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly

Set-Cookie: ARRAffinity=bdf441fc9168c6f52a0e4c935e07cfae5bf5a21df1f2d89706485427839659a3;Path=/;HttpOnly;Domain=test.selectmarketingllc.com

Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly

##### POST /Account/Login HTTP/1.1 - RESPONSE 302
Set-Cookie: .AspNetCore.Identity.Application=CfDJ8PllvhU4h2ROsOg2N9I0i4gZo7SmT5kLcjLwuhhZ2UorSVBRT0LjeeNlDSVRqerhyztsdVpw5cnnc5wBxBjOOqejDhbKKYjW4Zbhn9XlEFju5avGEeuWcNF3FU92kvQpmTEoo-fsJaivM3h3ZVeRySghr3Wmlv79fsDcEEQiKKFlUM45jvgdK7SmNSw5xCvBMznkafKHtmuI18ikVvYecl1rwJ3g4UdzTvtDZ12Vlm7xrLXoBQISdg9vaG02mq4_o8QGbTGUHiaiVCwOZzq7LKibzJB5eRe7sOTD4RmpEsFkDoRJZtghwXIZZ3faaAGqhjC2P3L0l2lrFU4ScOv0Wyxd2IBvJ2bWPbxcRHru7XkPW6SpAdS16rC4mBeRMfSm7PbUUkmI55HlAEhTztLIeq0E1-dgxSX08UoMhxHVyzuYPoM9WZnptvDbN9SbzwThBS8uzMs4YwyN-McV589XEszJ-D13suaEV7txunqKVvltMIwqfoolpODm_MXoRxT8e1k8lB78K1uDsSXflUhxoI1e9-6vCJ1VuQZkUmNpBY9jJyWcUNkKDPNH2l_3mM3MUeE0dNiuw3y32EQKQ8lM_flZ4JBIxUusH2ForvGt7ZD8GEsdVKfQU9lAuLJHBnRs5GGN3lXUDoLThIxvSc8r0u3RAAnGpNQz0inYmZkwQpidTIx2HCRLQByWHMQS0f1HAJJpacecwP9_Cr9x9zt4o_1vKs351eI-RTwRJf_qog5_AFNo5epWuUfRG6BiOVPVLc_fVFPzcKJw4ghNFEaD3dgqFFnW3UoO59FBYy_gzLQP8ze9gFXL45AHTdxXdnh0NnxgKyIo2l9RhP9asV0kJ9-SBVDqzwXEWn02TU9D7qoD-7wNS-zPif5xCrXFkzFsUg; expires=Thu, 01 Jun 2023 22:23:33 GMT; max-age=86400; path=/; samesite=lax; httponly

Set-Cookie: .AspNetCore.Mvc.CookieTempDataProvider=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly

![Blank](https://github.com/dotnet/aspnetcore/assets/107013798/3558abb8-604d-49b9-9d7c-1089d741176a)

##### GET / HTTP/1.1
Set-Cookie: .AspNetCore.Identity.Application=; expires=Thu, 01 Jan 1970 00:00:00 GMT; max-age=86400; path=/; samesite=lax; httponly

Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly

Set-Cookie: Identity.TwoFactorRememberMe=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly

Set-Cookie: Identity.TwoFactorUserId=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly


From logging, it appears that after 30 minutes (regardless of what timeout I specify), Identity queries the AspNetUser table.  However, it is querying the wrong table and using the wrong DbContext.  The database supports multiple applications.  I extended Identity with multiple sets of custom tables.  The Web app has multiple DbContexts, for migration purposes only.

When I authenticate the user, the app uses the expected DbContext and ApplicationUser, as specified in
`builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<SmApplicationDbContext>()
    .AddRoleManager<RoleManager<IdentityRole>>()
    .AddDefaultTokenProviders();`

However, when Identity queries that database, it uses a different DbContext and ApplicationUser.

Here, it is using SupplierApplicationDbContext:
`Entity Framework Core 7.0.5 initialized 'SupplierApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:7.0.5' with options: None`

This is the query that it executes, querying SmSuppliersAspNetUser
`Executing DbCommand [Parameters=[@__p_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']  SELECT TOP(1) [s].[Id], [s].[AccessFailedCount], [s].[ConcurrencyStamp], [s].[Email], [s].[EmailConfirmed], [s].[LockoutEnabled], [s].[LockoutEnd], [s].[NormalizedEmail], [s].[NormalizedUserName], [s].[PasswordHash], [s].[PhoneNumber], [s].[PhoneNumberConfirmed], [s].[SecurityStamp], [s].[SupplierID], [s].[TwoFactorEnabled], [s].[UserName]  FROM [security].[SmSuppliersAspNetUser] AS [s]  WHERE [s].[Id] = @__p_0`

I am not registering Identity with that DbContext or that ApplicationUser.

**Comment by Tratcher** [comment]
Hitting the database after 30 is expected, it's verifying the 'sign-out-everywhere' security stamp. Using the wrong dbcontext would certainly explain why that's not working. 

How is SupplierApplicationDbContext registered?

**Comment by Tratcher** [comment]
Register this one last:
`builder.Services.AddDbContext<SmApplicationDbContext>(options => options.UseSqlServer(connectionString));`

Does SmApplicationDbContext derive from any of the other types?

**Comment by selectmarketingllc** [comment]
Actually, I mispoke.  SmApplicationDbContext is only used for Identity.  SmContext is also used and is used for all non-Identity entities.  I inject SmContext into my controllers.

`public class SmApplicationDbContext : IdentityDbContext<ApplicationUser>`

Your comments about the registration order and the sign-out everywhere lead me to the answer.  As I said, I have three sets of Identity tables, used by different applications.  I was making three calls to builder.Services.AddIdentity(), even though I only need one of them.  My AccountController injects the SignInManager and UserManager; so, it authenticates properly.  When it does the sign-out everywhere check, it was just using the last DbContext registered with Identity.  I removed the two that I don't need here and it seems to work properly.

Thanks.

**Comment by selectmarketingllc** [comment]
Actually, I mispoke. SmApplicationDbContext is only used for Identity. SmContext is also used and is used for all non-Identity entities. I inject SmContext into my controllers.

public class SmApplicationDbContext : IdentityDbContext<ApplicationUser>

Your comments about the registration order and the sign-out everywhere lead me to the answer. As I said, I have three sets of Identity tables, used by different applications. I am making three calls to builder.Services.AddIdentity(), to manage users across all three, from this one application. My AccountController injects the SignInManager and UserManager; so, it authenticates properly. When it does the sign-out everywhere check, there is nothing to specify which DbContext to use. I changed the order in which I register Identity, registering SmApplicationDbContext last, and still doesn't work.  Is there a way to specify which Identity registration / DbContext to use?

**Comment by Tratcher** [comment]
It wires in through here:
https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Core/src/IdentityCookiesBuilderExtensions.cs#L54
https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Core/src/SecurityStampValidator.cs#L178-L198
It's just resolving the last registered ISecurityStampValidator. You could try to modify that event to direct it to a specific sign-in manager. That's all it does anyways: 
https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Core/src/SecurityStampValidator.cs#L127

**Comment by Tratcher** [comment]
Triage: There's a real bug here where you can't have multiple AddIdentity's with different user types because ISecurityStampValidator user type specific.

**Comment by selectmarketingllc** [comment]
I only need one User table for authentication.  The other two are just to create and delete user accounts.  I see that SecurityStampValidator injects a SignInManager.  Is it possible to register the SignInManager that is injected, so that I can get the correct ApplicationUser and the correct DbContext?

**Comment by Tratcher** [comment]
SignInManager is registered in DI with the right type, the trouble is that we're resolving the last ISecurityStampValidator. So if you put the right AddIdentity last it should be OK. Otherwise you'd need to create the SecurityStampValidator yourself and pass in the correctly resolved types.

**Comment by selectmarketingllc** [comment]
Simply moving the AddIdentity() call didn't work, but doing that along with instantiating an IdentityBuilder did the trick.

`IdentityBuilder builderSelect = builder.Services.AddIdentityCore<ApplicationUser>();`
`builderSelect = new IdentityBuilder(builderSelect.UserType, typeof(IdentityRole), builderSelect.Services).AddDefaultTokenProviders();`
`builderSelect.AddSignInManager<SignInManager<ApplicationUser>>();`
`builderSelect.AddRoleValidator<RoleValidator<IdentityRole>>();`
`builderSelect.AddRoleManager<RoleManager<IdentityRole>>();`
`builderSelect.AddEntityFrameworkStores<SmApplicationDbContext>();`
`builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<SmApplicationDbContext>()
    .AddRoleManager<RoleManager<IdentityRole>>()
    .AddDefaultTokenProviders();`
