### ISSUE TITLE
Textarea tagHelper is not rendering the contents of the element correctly. 

### ISSUE THREAD

**Issue by colhountech** [dotnet/aspnetcore#4852]
The `<textarea>` tag helper is not rendering the content of the element correctly for a Razor Page.

If a Model property called `Messages` is modified in the OnPost, this update is visible in the view by using the razor  directive `@Model.Messages`, but the `<textarea>` element does not display the correct innerHtml content.

This issue has been previously raised and closed because it could not be replicated.
https://github.com/aspnet/Mvc/issues/3964

This  example reproduces the issue:
https://github.com/colhountech/TextAreaDemo

Here is my attempt that fixes the scenario. I have not looked at regression so don't know yet if it 
affects any other tests.

https://github.com/colhountech/Mvc/pull/1/files

basically it comes down to the following code segment in the  

```
            ModelStateEntry entry;
            viewContext.ViewData.ModelState.TryGetValue(fullName, out entry);

            var value = string.Empty;
            if (entry != null && entry.AttemptedValue != null)
            {
                value = entry.AttemptedValue;
            }
            else if (modelExplorer.Model != null)
            {
                value = modelExplorer.Model.ToString();
            }
```

The issue seems to be related to both the `ViewData` and the `modelExplorer` returning a valid value, however the `modelExplorer` has the correct value, and this condition is never satisfied because the preceding condition is always true.

My fix for this issue is to remove the else, and allow the `Model` to take precedence over the `ViewData` ( I'm not sure if this effects regression), as follows:

```
             ModelStateEntry entry;
            viewContext.ViewData.ModelState.TryGetValue(fullName, out entry);

            var value = string.Empty;
            if (entry != null && entry.AttemptedValue != null)
            {
                value = entry.AttemptedValue;
            }
            // should the convention be that the Model override an ViewData for Razor Pages?
            if (modelExplorer.Model != null)
            {
                value = modelExplorer.Model.ToString();
            }
```
Hope this is an accurate understanding of the issue, if not please feel free to close.

**Comment by Ponant** [comment]
The following 
             `   <textarea asp-for="Input.Message" class="form-control" rows="5" cols="33">Hello there</textarea>`
will not render the text "Hello there".
But the following will work
`<textarea class="form-control" rows="5" cols="33">Hello there</textarea>`
It is odd indeed it shows that `asp-for` is somewhat limiting the use of the `textarea`

**Comment by ysiivan** [comment]
I don't often work with Razor, but there seem to be a rather misleading promise re: bound properties.

If a bound property is modified on a _GET_, then the new value are showing on screen.
 
However, if a bound property **is modified  in a _POST_** handler, the new value does **NOT** make it to screen, _regardless_ of whether the type of control is a textarea or an input box (or other).

The solution is to clear the model state, before returning from the post handler.
Doesn't feel like a complete "binding" solution.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
