### ISSUE TITLE
Add RateLimiterServiceCollectionExtensions.AddRateLimiter

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#48531]
## Background and Motivation

Rate limiting now requires `AddRateLimiter` to be called to add required DI types. See https://github.com/aspnet/Announcements/issues/506

However, only an overload for `AddRateLimiter` takes configuration options is currently available:

https://github.com/dotnet/aspnetcore/blob/4eae56d8f7315cbd49fcbd760341940e3d087aa5/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L10-L31

Someone can use rate-limiting middleware without config options. We shouldn't force them to provide an empty delegate when adding services. For example:

```cs
services.AddRateLimiter(options => {});
```

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

public static class RateLimiterServiceCollectionExtensions
{
+    public static IServiceCollection AddRateLimiter(this IServiceCollection services);
}
```

## Usage Examples

```cs
services.AddRateLimiter();
```

**Comment by BrennanConroy** [comment]
> Someone can use rate-limiting middleware without config options.

You mean if they used `Services.Configure<RateLimiterOptions>(...)` themselves? There really isn't a point in using the middleware unless options are set. I'm not sure we should add an overload that doesn't configure options just because `Configure<TOptions>` exists. Do we have prior-art for a similar middleware?

Here is prior-art for not adding another overload:
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs#L19

**Comment by halter73** [comment]
API Review Notes:

- Given that `UseRateLimiter(this IApplicationBuilder app, RateLimiterOptions options)` exists, it does seem plausible there's people who want this non-configuring `AddRateLimiter` overload.
- It doesn't really complicate things. It follows the standard pattern for adding services without configuring custom options.

API Approved!

```diff
namespace Microsoft.AspNetCore.Builder;

public static class RateLimiterServiceCollectionExtensions
{
+    public static IServiceCollection AddRateLimiter(this IServiceCollection services);
}
```

**Comment by KonH** [comment]
@JamesNK @halter73 @amcasey could you please take a look at related PR with proposed changes?
https://github.com/dotnet/aspnetcore/pull/51298
