### ISSUE TITLE
Review types passed to metrics tags

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#48530]
Metrics tags sometimes have enum and integer values. Value types always box because tags are stored as `KeyValuePair<string, object?>`. In some places, we avoid boxing with a [cached collection of boxed values](https://github.com/dotnet/aspnetcore/blob/4eae56d8f7315cbd49fcbd760341940e3d087aa5/src/Hosting/Hosting/src/Internal/HostingMetrics.cs#L110-L190).

Note that OTel semantic conventions specify the tag type in some places, such as the [HTTP status code is an integer](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#metric-httpserverduration).

Review with metrics experts to ensure we're doing the right thing.

Options

* Keep passing value types and cache value types on hot path metrics.
* Convert values to a string before passing to metrics, and rely on built-in caching. For example, `Int32.ToString()` and `Enum.ToString()` have some level of caching. The downside is that listeners may need to convert the string value back to its original type to use it.

**Comment by joperezr** [comment]
@JamesNK is there anything left we have to do here?
