### ISSUE TITLE
Blazor Style files for default project templates are not loaded correctly when using custom environment variables

### ISSUE THREAD

**Issue by wangyimingok** [dotnet/aspnetcore#48541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Style files for default project templates are not loaded correctly when using custom environment variables，When I am using a custom environment variable, the CSS style file generated by the template cannot be loaded

### Describe the solution you'd like

Allows the use of custom environment variables，Works just as well as the three environment variables allowed by the framework

### Additional context

https://github.com/wangyimingok/BlazorTemp

**Comment by javiercn** [comment]
@wangyimingok thanks for contacting us.

Static web assets is only plugged in automatically on the "Development" environment. If you are using a different environment, you need to plug in static web assets yourself by calling [`UseStaticWebAssets`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.staticwebassets.staticwebassetsloader.usestaticwebassets?view=aspnetcore-7.0) explicitly
