### ISSUE TITLE
Duplicate click events

### ISSUE THREAD

**Issue by HackerBaloo** [dotnet/aspnetcore#48542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I run a Blazor server app.
I have buttons on each row in a data grid, 10 rows in the test setup. 
The click event from the button is logged and handled in the event handler.
It almost always works as expected. But sometimes I get two very quick events. One time I checked I got these events 53 ms apart. 
When I try to reproduce it, I click once on the button on each row, On time I got three consecutive double events. The first three buttons gave double events the rest worked as expected.
This led me to believ that this could be a temporary SignalR communication glitch. 
Perhaps SignalR sometimes doesn't get the expected ack, or gets an error, so it retries, but the first message did arrive.

### Expected Behavior

Perhaps this is the expected behavior? My app just have to deal with this behavior?
Are there any logs to turn on? Are there any settings to tune?

### Steps To Reproduce

When I try to reproduce it, I click once on the button on each row, On time I got three consecutive double events. The first three buttons gave double events the rest worked as expected.
This led me to believ that this could be a temporary SignalR communication glitch. 
Perhaps SignalR sometimes doesn't get the expected ack, or gets an error, so it retries, but the first message did arrive.

### .NET Version

7.0.105

### Anything else?

.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.105 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by javiercn** [comment]
@HackerBaloo thanks for contacting us.

Have you turned on the logs to debug level on the browser and the server? That will produce the exact trace of what messages appear on the server and the browser and might shed some clarity on what might be going on.

We are not aware of bugs in this area (we would expect to see more users run into something like this) so we would suggest to first check the logs for anything that your app might be doing, or even better, try to recreate the behavior in a separate repro app as simple as possible.
