### ISSUE TITLE
QuickGrid Link Value

### ISSUE THREAD

**Issue by silentdevnull** [dotnet/aspnetcore#48552]
How can we link a value to open in another page in with quickgrid's? 

I'm using quickgrid to list all the Depatments in my organization and would like to link the name of the department to the department page. I have the link in the data set so I just don't know how to do it in the properties. 

Thank you

**Comment by mkArtakMSFT** [comment]
As @davidwengier already suggested defining a template column and adding an `<a href="..." target="_blank">` should do it.
