### ISSUE TITLE
 Application startup exception

### ISSUE THREAD

**Issue by itkm** [dotnet/aspnetcore#48578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I write a ms in asp.net core 8.0 p4.0, but  I get a issue when run this app.
The startup code like this:
app.UseCookiePolicy();
            app.UseSession();

            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                Console.WriteLine(endpoints.DataSources.Count);
                endpoints.MapControllerRoute(
                   name: "default",
                   pattern: "{controller=News}/{action=Index}/{id?}");
                #region Area Route
                endpoints.MapControllerRoute(
                   name: "Admin",
                   pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                   name: "Shop",
                   pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                   name: "Content",
                   pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                   name: "CallCenter",
                   pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Tracing",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Bidding",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Customers",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "DataCenter",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Delivery",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Ecommerce",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Finance",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Logistics",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Marketing",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Orders",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Podcast",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                  name: "Store",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                #endregion
            });

The Errors like this

An error occurred while starting the application.
ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)

ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)
System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
System.Reflection.CustomAttribute.AddCustomAttributes(ref ListBuilder<object> attributes, RuntimeModule decoratedModule, int decoratedMetadataToken, RuntimeType attributeFilterType, bool mustBeInheritable, ListBuilder<object> derivedAttributes)
System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, bool inherit)
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.CreateActionModel(TypeInfo typeInfo, MethodInfo methodInfo)
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable<TypeInfo> controllerTypes)
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func<IChangeToken> changeTokenProducer, Action changeTokenConsumer)
Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, string name, string pattern, object defaults, object constraints, object dataTokens)
Itkm_CoreManegeSystem.Startup+<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in Startup.cs
+
                endpoints.MapControllerRoute(
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
Itkm_CoreManegeSystem.Startup.Configure(IApplicationBuilder app) in Startup.cs
+
            app.UseEndpoints(endpoints =>
System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature sig, bool isConstructor)
System.Reflection.MethodInvoker.Invoke(object obj, IntPtr* args, BindingFlags invokeAttr)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.WebTools.BrowserLink.Net.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Program.Main(string[] args) in Program.cs
+
        CreateHostBuilder(args).Build().Run();

### Expected Behavior

no

### Steps To Reproduce

no

### Exceptions (if any)

no

### .NET Version

8.0

### Anything else?

An error occurred while starting the application.
ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)

ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)
System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
System.Reflection.CustomAttribute.AddCustomAttributes(ref ListBuilder<object> attributes, RuntimeModule decoratedModule, int decoratedMetadataToken, RuntimeType attributeFilterType, bool mustBeInheritable, ListBuilder<object> derivedAttributes)
System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, bool inherit)
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.CreateActionModel(TypeInfo typeInfo, MethodInfo methodInfo)
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable<TypeInfo> controllerTypes)
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func<IChangeToken> changeTokenProducer, Action changeTokenConsumer)
Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, string name, string pattern, object defaults, object constraints, object dataTokens)
Itkm_CoreManegeSystem.Startup+<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in Startup.cs
+
                endpoints.MapControllerRoute(
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
Itkm_CoreManegeSystem.Startup.Configure(IApplicationBuilder app) in Startup.cs
+
            app.UseEndpoints(endpoints =>
System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature sig, bool isConstructor)
System.Reflection.MethodInvoker.Invoke(object obj, IntPtr* args, BindingFlags invokeAttr)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.WebTools.BrowserLink.Net.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Program.Main(string[] args) in Program.cs
+
        CreateHostBuilder(args).Build().Run();

**Comment by itkm** [comment]
I hope everyone can help me, I really can't help it anymore!!!!

**Comment by davidfowl** [comment]
```
ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)
```

From the top of the exception it looks like you have an area attribute somewhere with an empty string or null for the area name.

It could be a bug, but it's unclear where and how to reproduce the problem. We won't be able to help without more application details. Can you narrow down the application to something small that still reproduces the problem? That might help shed more light on what could be happening.

**Comment by itkm** [comment]
> ```
> ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
> Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)
> ```
> 
> From the top of the exception it looks like you have an area attribute somewhere with an empty string or null for the area name.
> 
> It could be a bug, but it's unclear where and how to reproduce the problem. We won't be able to help without more application details. Can you narrow down the application to something small that still reproduces the problem? That might help shed more light on what could be happening.

Thanks,but,this bug not fixed when moved code to new solution.
I don't kn this issue in? 
When create a new solution not contain the bus code, Run normal.

**Comment by itkm** [comment]
> ```
> ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
> Microsoft.AspNetCore.Mvc.AreaAttribute..ctor(string areaName)
> ```
> 
> From the top of the exception it looks like you have an area attribute somewhere with an empty string or null for the area name.
> 
> It could be a bug, but it's unclear where and how to reproduce the problem. We won't be able to help without more application details. Can you narrow down the application to something small that still reproduces the problem? That might help shed more light on what could be happening.

Thank you very much! I had issue my problem. Thank ,Thanks!
