### ISSUE TITLE
Add EventSource/EventCounter tracing and metrics for MVC

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#4858]
Some events listed below. The goal is to add events that will help users solve problems so if these aren't going to do that job, feel free to suggest/discuss others!

* `Microsoft-AspNetCore-Mvc` EventSource (does not exist)
    * For each `x` in `Action`, `ActionResult`, `ViewExecution`, `ViewCompilation`, `ModelBinding`
        * `xStart` event - Triggered when invocation of an Action begins.
        * `xStop` event - Triggered when invocation of an Action completes.
        * `xFailure` event and counter - Triggered when an exception escapes from invoking an Action.
        * `xDuration` counter - Measures the duration of action invocation
    * ~~There are probably more things to do in Model Binding around specific value providers and binding individual values.~~ Split off to #7021 

See https://gist.github.com/anurse/af1859663ac91c6cf69c820cebe92303 for some guidance on adding EventSources and EventCounters to ASP.NET projects.

**Comment by pranavkm** [comment]
Closing this for the time being. We'll reopen if there's interest in this area.
