### ISSUE TITLE
Component containing modal not rendering

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#48588]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Component-containing-modal-not-rendering/10380164)._

---
[regression] [worked-in:17.6.1]
Yesterday I reported that I was having trouble since I updated to the newest version of Visual Studio (17.6.2), this is still the case, but I have since then discovered some other irregularities, which narrows down the issue.  The issue I reported yesterday, was that in my Blazor server app project, I have a component that consists of a modal that is used either to add or edit existing sections/fields.  Currently the modal does not popup when the onclick event is triggered, but the component seems to render as it shows up in the Elements section when the page is inspected.  I have since then discovered that my badges are not displaying anymore either, which leads me to believe that the issue is related to the bootstrap library and how it is initiated within the Blazor server app project.  As I have also worked on projects using MVC, where modals were used, I then checked if the issue consists there as well, but it does not, the modals and badges still work there.  This seems to indicate that the issue has to do with the relation between bootstrap and Blazor and something that changed it, in the Visual Studio update, although I can't seem to find anything in the release notes that indicates that such a change occurred. If someone could please look into this and provide a solution. Thank you.

---
#### Fredré Fourie on 5/31/2023, 03:19 AM: 

(private comment, text removed)
#### Feedback Bot on 5/31/2023, 07:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SteveSandersonMS** [comment]
Thanks for the report. Are you able to supply a minimal repro project, ideally as a GitHub issue? We will then investigate.
