### ISSUE TITLE
System.IO.IOException: ' Received an unexpected EOF or 0 bytes from the transport stream.'

### ISSUE THREAD

**Issue by DisparueStrix** [dotnet/aspnetcore#48587]
Hi

This error happens regardless of Blazor project, if I create a new Blazor Webassembly app the problem persists. I have repaired VS twice, reinstalled and installed once, reinstalled node.js and yet the problem occurs, even after I turn off all firewall settings. I want to stress this happens with the default Blazor Webassembly template so it is fair to say it isnt a user issue.

If I launch the project with BlazorApp1.Server or choose to debug BlazorApp1.Client directly, most of the time it doesnt even launch and when it does it crashes quickly with the exception even without any interaction. If the error happens before launch I dont even get to see "Loading...". This is also the case for my own apps. HOWEVER, if I use IISExpress to launch the app, it launches fine without any issues BUT I want to stress earlier this wasnt the case and the exception was thrown with IISExpress too. I dont want to assume this is a MS Edge problem either, as it is working fine for IISExpress atm. However, I have noticed a new heart icon on MS Edge and I am going to assume it has been updated recently despite the last update being recorded as May 25th.

A file, "visualstudio-js-debugger.txt", is produced but I cant make any sense of it. 
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/11636632/visualstudio-js-debugger.txt)

I am using the following version of VS "Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.6.2" and MS Edge "Version 113.0.1774.57 (Official build) (64-bit)". 

I am really not sure what to do. Everything has been working fine without any issues until today.

Regards.

PS. Let me know if you need any more information.

Edit: Forgot to mention this is for .NET 6, .NET 7 works fine, at the moment.

**Comment by thaystg** [comment]
@DisparueStrix , one question, if you disable all the exception breakpoints, then the app is started correctly?

**Comment by thaystg** [comment]
Also, @joj, it looks like it's debugging the server side and not the webassembly side, so we should ping someone like @gregg-miskelly , I think.

![image](https://github.com/dotnet/aspnetcore/assets/4503299/0cef94ff-c619-41eb-9d70-94210941592a)

**Comment by DisparueStrix** [comment]
> @DisparueStrix , one question, if you disable all the exception breakpoints, then the app is started correctly?

Nope, this is reproduced through templates with zero modifications or breakpoints, pretty much creating a new project and pressing run on the server produces the error.

I should probably mention this happens regardless of project creation setting, so with and without HTTPS or with and without ASP.NET Hosted and the results are the same. 

Since this thread I have reluctantly moved on to .NET 7, for most of the part it worked well, yesterday I had an issue with hot reload and the error above returned. However, unlike the projects created in .NET 6 deleting .vs and rebuilding fixed the issues in the .NET 7 project. It is possible seeing as the issue only appeared in the .NET 7 project when hot reload bugged that it might be that which is causing issues, the only problem with this assumption is I never had hot reload issues when I did things in .NET 6.

**Comment by thaystg** [comment]
@javiercn can you help us?

**Comment by DisparueStrix** [comment]
Update: If I change 'launchbrowser' in launchsettings.json to false, run BlazorApp1.Server and manually enter the web address it opens and works fine. Again this was done on the WebAssembly template project with no modifications except to 'launchbroswer'.

**Comment by mkArtakMSFT** [comment]
This looks like a tooling issue, rather than runtime, given that the app starts successfully and listens to the port. @BillHiebert do you know if there have been recent changes in the VS debugger side that may impact this? Note, that this only impacts .NET 6 apps per customer.

**Comment by vijayrkn** [comment]
@DisparueStrix - Since this looks like a VS tooling issue, can you please follow the instructions here to log a VS feedback issue?
https://developercommunity.visualstudio.com/VisualStudio/report

This will guide you to upload the relevant VS log information for the team to debug and find the cause of the issue. Thank you for being a Visual Studio customer!

**Comment by DisparueStrix** [comment]
Feedback thread: https://developercommunity.visualstudio.com/t/SystemIOIOException:--Received-an-une/10387581

I have sent feedback but for the sake of things in case someone comes across this thread with the same issue, I am unable to reproduce the problem any more and all projects created via templates run fine. All that has changed on my side was installing CCleaner, for unrelated reasons, and performing a standard cleaning which cleared internet folders (which sadly MS Edge's clear did not). I cant say for certain the problem stems from there but I included this information in the feedback and anyone having this issue in the future may want to clear via CCleaner.

Regards.

PS. If the problem returns I will just update that thread
