### ISSUE TITLE
PasswordValidator - why does IsUpper and IsLower methods checks only latin characters

### ISSUE THREAD

**Issue by Bykiev** [dotnet/aspnetcore#48583]
## Summary

When checking if password contains upper/lower characters it only checks for ['A-Z'/'a-z'](https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Extensions.Core/src/PasswordValidator.cs#LL107C25-L107C32). It's not useful as other non-latin characters can be used in password.

## Motivation and goals

Imporve PasswordValidator usage with non-latin symbols

## Risks / unknowns

It's a breaking change

# Detailed design

`IsUpper` method should use `Char.IsUpper` method, and IsLower should use `Char.IsLower` methods

**Comment by martincostello** [comment]
The methods you point to are declared as `virtual`, so you should be able to provide your own custom password validator implementation that behaves in the manner you wish.

```csharp
public class CustomPasswordValidator<TUser> : PasswordValidator<TUser> where TUser : class
{
    public CustomPasswordValidator(IdentityErrorDescriber? errors = null)
        : base(errors)
    {
    }

    public override bool IsLower(char c) => char.IsLower(c);

    public override bool IsUpper(char c) =>  => char.IsUpper(c);
}
```

You can then register it using the [`IdentityBuilder.AddPasswordValidator<T>()`](https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Extensions.Core/src/IdentityBuilder.cs#L116) method to replace the built-in version.

As you mentioned, changing the default would likely be a breaking change, so I think the built-in extensibility is intended way for you to include non-ASCII characters in the password validator.

**Comment by Bykiev** [comment]
Thank you, of course it can be easily overridden, if you think the current design suits framework's ideology, I'll override it.

**Comment by Bykiev** [comment]
I've tried your code, and it's not working for some reason, the method is called but still throws error

**Comment by martincostello** [comment]
Do you have a stack trace of where the error is being thrown from? Maybe there's code elsewhere that also needs to be modified for the actual insert of the record containing the hashed password into the data store?

**Comment by Bykiev** [comment]
In console I see this error:

```
warn: Microsoft.AspNetCore.Identity.UserManager[14]
      User password validation failed: PasswordRequiresLower.
```

**Comment by martincostello** [comment]
Looks like that would come from the error returned here:

https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Extensions.Core/src/PasswordValidator.cs#L61-L65

Assuming your code is wired-up correctly, then it should be calling your custom validator.

If you test `char.IsLower()` separately with the password you used, does it return `true` for at least one of those characters? If it doesn't then maybe `char.IsLower()` doesn't work as you expected and the implementation needs tweaking to account for those non-ASCII characters?

**Comment by Bykiev** [comment]
`char.IsLower('й')` returns true, so, it's not the issue. Overridden method `IsLower `is called and returns correct values for all symbols

**Comment by Bykiev** [comment]
If'll override `ValidateAsync` method it returns Succeeded response, but the result of `UserManager.ChangePasswordAsync` is `Passwords must have at least one lowercase ('a'-'z').`

**Comment by martincostello** [comment]
Looking at the code a bit more, it looks like there can be multiple password validators:

https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Extensions.Core/src/UserManager.cs#L158

And they are all checked:

https://github.com/dotnet/aspnetcore/blob/d919168952ac4da33be8532c6980547a783a7389/src/Identity/Extensions.Core/src/UserManager.cs#L2337-L2350

If you update your code to remove the original validator, does it work then?

**Comment by Bykiev** [comment]
Thanks, but what is the best place to remove default implementation, except controller/service? It seems I can't get Usermanager instance while adding my custom password validator?

**Comment by martincostello** [comment]
I think you'd need to use something like [this](https://stackoverflow.com/a/43591075) to replace the service instead of add it.

**Comment by Bykiev** [comment]
I found this [SO](https://stackoverflow.com/questions/63958652/remove-default-passwordvalidator-from-asp-net-core) answer and it's working fine

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @martincostello 👍
