### ISSUE TITLE
WebHostOptions default ShutdownTimeout does not match HostOptions default ShutdownTimeout

### ISSUE THREAD

**Issue by hwoodiwiss** [dotnet/aspnetcore#48605]
### Describe the bug

The default value for `ShutdownTimeout` in `Microsoft.Extensions.Hosting.HostOptions` was updated to 30 seconds as part of https://github.com/dotnet/runtime/issues/63709

The default value for `ShutdownTimeout` in `WebHostOptions` should be made consistent with this so that the default shutdown behaviour is consistent for services using `GenericWebHostService` and `WebHost`.

### Expected Behavior

Default values for `HostOptions.ShutdownTimeout` and `WebHostOptions.ShutdownTimeout` should match for consistent stopping behaviour across both when `ShutdownTimeout` has not been set via configuration (Config for key: `shutdownTimeoutSeconds`)

**Comment by amcasey** [comment]
@ReubenBond Does it make sense to propagate this change?  I like consistency, but I'd like to confirm there isn't a reason to keep them independent.

**Comment by ReubenBond** [comment]
Yes, it makes sense. They should all have the same default values

**Comment by amcasey** [comment]
Sounds like we're on board with the suggestion.  @hwoodiwiss, would you like to submit a PR for this?

**Comment by hwoodiwiss** [comment]
I've got a PR open for this here https://github.com/dotnet/aspnetcore/pull/48606

**Comment by amcasey** [comment]
🤦 So you do
