### ISSUE TITLE
Blazor Server app with many requests make website unstable

### ISSUE THREAD

**Issue by Tem0B** [dotnet/aspnetcore#48602]
I created Blazor server web app and I deployed on Azure App Service, and in Network tab I see a lot of handshake requests, 3-4 for one click. application is unstable, works very slow and on loading refreshing couple of times, goes onto footer of page and gets back and somethings like that, only on production, not in localhost. on localhost working fine. Cant find any valid resources to solve this problem. does anyone have a idea what should I do?

**Comment by javiercn** [comment]
@Tem0B thanks for contacting us.

We do not have enough information to make progress on this issue. Please provide:
1) A minimal repro app.
2) Concrete details on the environment you are deploying to, including Hosting plan, and the Azure region, the more detailed the better.
3) Concrete details on the browser you are using to test the app as well as the region the client is connecting from.
4) Concrete quantitative metrics about what you mean by this:
    * application is unstable
    * works very slow and on loading refreshing couple of times

Also, check our guide on deploying Blazor Server apps to ensure that you are following our recommended best practices:
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-7.0
