### ISSUE TITLE
dotnet watch - force use "Ctrl+R" to restart after static class change

### ISSUE THREAD

**Issue by DmitryLoktionov** [dotnet/aspnetcore#48618]
### Description
Perhaps this behavior is correct, but using `dotnet watch` in webapi I expect the results to be updated immediately after changing the file, but I am forced to use `Ctrl + R` to actually restart after changing the static class. Is there some key to restart (rebuild) the application every time after any file change?

##### Create and run application in watch mode ✅ 
```sh
dotnet new webapi --output TestApi --no-openapi
cd TestApi
dotnet build
dotnet watch
```

##### View logs and test API ✅
```sh
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  TestApi -> /Users/user/Downloads/TestApi/bin/Debug/net7.0/TestApi.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5243
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/user/Downloads/TestApi
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

##### Change file `Controllers/WeatherForecastController.cs` ✅
```csharp
private static readonly string[] Summaries = new[]
{
    "Freezing1 ", "Bracing1 ", "Chilly1 ", "Cool1 ", "Mild1 ", "Warm1 ", "Balmy1 ", "Hot1 ", "Sweltering1 ", "Scorching"
};
```

##### View logs ✅
```sh
dotnet watch ⌚ File changed: ./Controllers/WeatherForecastController.cs.
dotnet watch 🔥 Hot reload of changes succeeded.
```

##### Test API ❌❌❌❌❌
See old values

##### Restart manually ✅
Press "Ctrl + R" in console

##### View logs ✅
```sh
dotnet watch 🔥 Hot reload of changes succeeded.
dotnet watch 🔧 Building...

  TestApi -> /Users/user/Downloads/TestApi/bin/Debug/net7.0/TestApi.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5243
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/user/Downloads/TestApi
```

##### Test API ✅✅✅✅✅
See new values

### Configuration
.NET SDK: 7.0.302
.NET Runtime: 7.0.5
OS: macOS Ventura 13.4 ARM64

### Regression?
Tried with net6.0 - same result:
.NET SDK: 6.0.408
.NET Runtime: 6.0.16
`dotnet new webapi --output TestApi6 --no-openapi --framework net6.0`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This behavior is by design. Updating static fields is not supported by hot reload. However, if you'd like to automatically restart the app without hot reload, you can pass additional `--no-hotreload` parameter to the dotnwatch.
