### ISSUE TITLE
More detailed metrics around the ExceptionHandler middleware

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#48625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Follow up to https://github.com/dotnet/aspnetcore/issues/46280 which added IExceptionHandler to support addressing various kinds of app exceptions in a centralized way. The partner that made this request also has observability requirements. There's already a .NET counter for the number of exceptions being thrown, but what's missing is how they were handled.

The current logic uses the new tag feature to flow the exception down to the host.
https://github.com/dotnet/aspnetcore/blob/c2488eead6ead7208f543d0a57104b5d167b93f9/src/Middleware/Diagnostics/src/DiagnosticsTelemetry.cs#L18

### Describe the solution you'd like

A metric that indicates which of these three things happened:
- An exception handler handled the exception. (which?)
- Exception handling was skipped because the response was already started.
- No exception handlers were able to handle the exception. (Unhandled).

This likely needs a new metric rather than contributing to an existing one (hosting), there are limits to the number of dimensions you should add to a metric (25?).

### Additional context

CC: @JamesNK

**Comment by JamesNK** [comment]
Is this counter specific to ExceptionHandler middleware or should it include the developer exception middleware as well?
