### ISSUE TITLE
Blazor NavLink component is active on wrong path

### ISSUE THREAD

**Issue by Flachdachs** [dotnet/aspnetcore#48627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`NavLink` components add their `ActiveClass` to `class` when `Match` equals `NavLinkMatch.Prefix` and the current path starts with `href`, but there is a restriction in the code comment `"/abc" is treated as a prefix of "/abc/def" but not "/abcdef"`. So far so good. But if you have a path like `/abc-def`, then `/abc` is also considered as a valid prefix. Instead of the `-` also any valid URL character that is not a letter or digit has the same problem.

### Expected Behavior

NavLinks with hrefs like `abc` should only be active when the path is like `/abc/def` but not `/abc-def` .

### Steps To Reproduce

- create a project from blazorserver template.
- change in `FetchData.razor` the `@page "/fetchdata"` to `@page "/fetch-data"`
- change in `Counter.razor` the `@page "/counter"` to `@page "/fetch"`
- adjust the `href`s of the `NavLink`s in `NavMenu.razor` accordingly
- start the app and navigate to `/fetch-data`, i.e. click the "Fetch data" menu item
- both "Fetch data" and "Counter" are "active"

### .NET Version

7.0.5

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this, @Flachdachs.
This is indeed something not great and we will try to fix this in the future. For now, however, you may want to copy the code of the NavLink component and update it as necessary to fit your needs.
