### ISSUE TITLE
[SSR] Route parameter not working with page directive

### ISSUE THREAD

**Issue by geertdoornbos** [dotnet/aspnetcore#48649]
With Blazor Components (server side rendering) the route parameter is not (yet?) working. Maybe it's not implemented...

```
@page "/route-parameter/{text?}"

<h1>Blazor is @Text!</h1>

@code {
    [Parameter]
    public string? Text { get; set; }

    protected override void OnInitialized()
    {
        Text = Text ?? "fantastic";
    }
}
```
example from [documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#route-parameters)

If I remove the page directive and add a route like this:
```
app.Map("route-parameter/{text}", (string text) => new RazorComponentResult<RouteParameter>(new { Text = text }));
```
it works.

Or will there be another attribute like SupplyParameterFromRouteAttribute (related to SupplyParameterFromQueryAttribute and SupplyParameterFromFormAttribute)?

**Comment by javiercn** [comment]
@geertdoornbos thanks for contacting us.

Could you either:
1) Create a minimal repro with your current bits.
2) Use the template from the nightly bits (preview5) and try out there?

**Comment by geertdoornbos** [comment]
Minimal repro: https://github.com/geertdoornbos/BlazorRouteParameterSSR

Using preview 4, don't know exactly how to get preview5. Console logs the used version.

Starting the sample shows it's not working.
Adding the route and removing the page directive shows a way that is does work.

I assume both methods should work.

**Comment by javiercn** [comment]
@geertdoornbos thanks for the additional details.

That's likely not working on preview4 because we were using an internal component that just rendered the layout and the page, but did nothing with the route data, but should work in preview5.
