### ISSUE TITLE
Website times out...startup.config is never called

### ISSUE THREAD

**Issue by bwcadave** [dotnet/aspnetcore#48665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a really weird scenario on 1 server, that I cannot figure out why the site won't run (runs fine on 2 other servers). On this one server, .netcore 6 does NOT get to startup.configure. The site times out before calling it.  

The site errors out with the normal:
`HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit `

my web.config looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore 
processPath="dotnet" 
arguments=".\acme.dll" 
stdoutLogEnabled="true" 
stdoutLogFile=".\logs\stdout" 
hostingModel="InProcess"
startupTimeLimit="240"
	>
  <handlerSettings>
    <handlerSetting name="debugLevel" value="trace,file" />
    <handlerSetting name="debugFile" value="C:\inetpub\acme\logs\acme.log" />
  </handlerSettings>
</aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

in my log file...everything starts correctly (just like the other servers), but then it just times out.  Here are the last few lines of the log:
```
[2023-06-08T02:17:22.243Z, PID: 5968] [aspnetcorev2_inprocess.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\6.0.16\hostfxr.dll
[2023-06-08T02:17:22.245Z, PID: 5968] [aspnetcorev2_inprocess.dll] Initial Dll directory: '', current directory: 'c:\windows\system32\inetsrv'
[2023-06-08T02:17:22.246Z, PID: 5968] [aspnetcorev2_inprocess.dll] Setting dll directory to c:\windows\system32\inetsrv
[2023-06-08T02:17:22.248Z, PID: 5968] [aspnetcorev2_inprocess.dll] Setting current directory to C:\inetpub\acme\
-----nothing for the 4min while the site starts to load ------
[2023-06-08T02:21:22.235Z, PID: 5968] [aspnetcorev2_inprocess.dll] Stopping file watching.

```

Event log is clean. Just that the website times out.

One thing I've tried, is I've added logging to my startup 

`        public void Configure(IApplicationBuilder app, IWebHostEnvironment environment ) 
`
method, but, the log entries never get created. So, it's like Startup.Configure(..) is never called.
(I've verified the log entries are created on the server that works)

a)What else can I look at for logging?
b)Is there a different way I can have the framework manually call startup.configure(...)?  currently my program.cs files is pretty standard:
```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {

                webBuilder.UseStartup<Startup>()
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddNLog(hostingContext.Configuration.GetSection("Logging"));
                });
            });
    }
```

**Comment by Tratcher** [comment]
Can you attach a debugger and break in when it seems stuck?

**Comment by bwcadave** [comment]
Unfortunately, Visual Studio is not installed on the server.

**Comment by bwcadave** [comment]
ok, idiot question: How do I do that?

Do you have a link?

Thanks!

**Comment by Tratcher** [comment]
https://stackoverflow.com/questions/34252338/what-is-a-dump-file-in-windows-task-manager

**Comment by bwcadave** [comment]
So, I have the dump file (actually ran the acme.exe directly, as it also stalls in the same spot).

What do I do now? I've opened it in VS. But, since there isn't an exception being thrown, I'm at a loss as to what to look for.  

Thanks a bunch!

**Comment by bwcadave** [comment]
Ok, this helped a bunch. Turned out to be a sql server issue. For some reason, rather than throwing the normal "cannot connect to sql server"  error message I would expect to see, instead it just timed out connecting.  This put me on the right track. Thanks a bunch!
