### ISSUE TITLE
Handle dotnet/extensions scenarios in ASP.NET metrics middleware

### ISSUE THREAD

**Issue by noahfalk** [dotnet/aspnetcore#48666]
We recently added metrics middleware support to ASP.NET, and dotnet/extensions also introduced alternative middleware. Ideally we handle that in a way that feels like customization or composition, not just picking between multiple alternative implementations that differ along multiple dimensions.

The important things dotnet/extensions wants to support:
- Enriching the metrics with additional custom tags
- Changing the metric name and tag names to support alternate naming schemas
- dotnet/extensions wants to combine method and route. Can we do that by default or does that need to be a customization? Their telemetry PM asserts queries on just one isn’t very useful.

The output here would be some prototype, sample, or doc that demonstrates how we plan to handle this and what the experience is for users. There may or may not be runtime changes needed.

cc @geeknoid @dpk83 @JamesNK @antonfirsov

**Comment by JamesNK** [comment]
I've written an internal doc that merges ASP.NET Core changes with dotnet/extensions functionality. All required changes in ASP.NET Core for metrics have been made.

The next step is updating dotnet/extensions. I've created an issue there: https://github.com/dotnet/extensions/issues/4154
