### ISSUE TITLE
Blazor dotnet.wasm compression/decompression doesn't round-trip

### ISSUE THREAD

**Issue by sake402** [dotnet/aspnetcore#48674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since dotnet 7.0.203, we started getting 
``
Failed to find valid digest in the 'integrity' attribute for resource '_framework/dotnet.wasm' with computed SHA-256 integrity 'DL4j2DpxtpVPYKs+s2MEt5FbF/1BGHDewGhsBC8M7as='. The resource has been blocked.
``
We have been using brotli compressed versions of all dll's and wasm file, so we have the brotli decompressor in place and this works for all other files except dotnet.wasm.

After investigating the published files dotnet.wasm and dotnet.wasm.br, we realized that.
1. The original size of the dotnet.wasm is 2,509,675 bytes
2. The dotnet.wasm.br is 868,195 bytes long

![image](https://github.com/dotnet/aspnetcore/assets/20999608/03bf6ad3-ce14-4a92-985f-a8f6fd200519)

After decompressing in browser however, the decompressed file size is 2,509,604.
We also used a tool to decompress on windows giving a file size of 2,509,604.

![image](https://github.com/dotnet/aspnetcore/assets/20999608/05603369-49b0-44cb-bf1f-804991c6ec82)

If my understanding Brotli is correct, it is a lossless compression and the compression and decompression should round trip, but it seems the dotnet.wasm.br file was not generated from the published  dotnet.wasm

Finally using a diff tool to compare the decompressed file to dotnet.wasm revealed a lot of diff between this two files.

![image](https://github.com/dotnet/aspnetcore/assets/20999608/fd41ad33-c70a-4840-b0cb-3989b6aacbc7)

### Expected Behavior

Since the sha signature in blazor.boot.json were generated from dotnet.wasm, the decompressed file ought to result in exactly the same dotnet.wasm for the integrity to pass

### .NET Version

7.0.203

**Comment by javiercn** [comment]
@sake402 thanks for contacting us.

Can you create a minimal repro project for the issue?
