### ISSUE TITLE
Not able to skip aspnetcore testcases with Mono runtime 

### ISSUE THREAD

**Issue by ashutoshjadhav9** [dotnet/aspnetcore#48688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We were trying to skip the aspnetcore testcases with Mono runtime using FrameworkSkipCondition attribute like below

[ConditionalFact]
[FrameworkSkipCondition(RuntimeFrameworks.Mono)]
public async Task StartupAnalyzer_AuthNoRouting()
{

}

The testcase gets skipped when we use CoreCLR in FrameworkSkipCondition attribute instead of Mono

### Expected Behavior

The testcase should get skipped with Mono when used in FrameworkSkipCondition attribute

Linking to issue https://github.com/dotnet/runtime/issues/69823

**Comment by wtgodbe** [comment]
Looks like we only honor the skip attribute on Mono for NetFramework: https://github.com/dotnet/aspnetcore/blob/4f0174b2ef184a9448d24f57394046b4699528de/src/Testing/src/xunit/FrameworkSkipConditionAttribute.cs#L35-L40

This is in our backlog right now so we won't get to it for a while, but if you want to open a PR to modify the code in the above file, it should be pretty trivial to fix it so we skip on mono for non-NetFramework tests as well.

**Comment by ivanpovazan** [comment]
@wtgodbe @tmds 

If I understood correctly the test cases in question got disabled because of: https://github.com/dotnet/runtime/issues/60650
The issue has been fixed via: https://github.com/dotnet/runtime/pull/87406 
So I think the tests can be enabled again.

Let me know if I can help in regard to that.

**Comment by tmds** [comment]
@ivanpovazan yes, the tests can be enabled again. To do that, the `ActiveIssue` attributes with the url `https://github.com/dotnet/runtime/issues/60650` must be removed from the tests. Do you want to do that? Or should I look into it?

**Comment by ivanpovazan** [comment]
> @ivanpovazan yes, the tests can be enabled again. To do that, the `ActiveIssue` attributes with the url `https://github.com/dotnet/runtime/issues/60650` must be removed from the tests. Do you want to do that? Or should I look into it?

@tmds thank you, I have opened a PR: https://github.com/dotnet/runtime/pull/88322

Is there anything that needs to be done on aspnetcore side?

**Comment by Sapana-Khemkar** [comment]
We have verified aspnetcore tests and now they are passing on mono. Thanks @ivanpovazan. I think we donot have to do anything on mono.
