### ISSUE TITLE
Blazor: Allow specifying JsonSerializerOptions in PersistentComponentState

### ISSUE THREAD

**Issue by tylermercer** [dotnet/aspnetcore#48697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to serialize a state object that has circular references. Removing the circular references is difficult, because they are EF navigation properties that are currently marked as required, so they can't be nulled out prior to serialization. There may be a way to transform the structure into a DTO tree without circular references, and then transform it back after deserializing, but that would be a lot of work and would likely be fragile.

System.Text.Json [can handle circular references already](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/preserve-references?pivots=dotnet-7-0). That would work here _if_ `PersistentComponentState` allowed you to set the serialization options.

### Describe the solution you'd like

Allow a component that uses `PersistentComponentState` to specify `JsonSerializerOptions` for it to use under the hood.

This could be done either on a per-usage basis, like with an `options` parameter on `PersistAsJson` and `TryTakeFromJson`, or project wide via a `AddJsonOptions` method on the `IServerSideBlazorBuilder` interface (similar to what is provided on the `IMvcBuilder` interface).

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. [This issue](https://github.com/dotnet/aspnetcore/issues/45574) is tracking enabling this scenario. We're going to close this out as a duplicate.
