### ISSUE TITLE
Clean up naming and layout for the new Blazor weather page

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#48706]
Here's where things stand with the new Blazor weather page:

- Component name: *ShowData.razor*
- Page heading & title: `<h1>Weather forecast</h1>`
- Nav bar text: "Fetch data"

To clean this up, how about this?:

- Component name: *Weather.razor*
- Page heading & title: `<h1>Weather</h1>`
- Nav bar text: "Weather"

**Comment by danroth27** [comment]
Also, should we rename the *Index.razor* to  *Home.razor*?:

So instead of this:

- Component name: *Index.razor*
- Page heading & title: `<h1>Index</h1>`
- Nav bar text: "Home"

We could do this:

- Component name: *Home.razor*
- Page heading & title: `<h1>Home</h1>`
- Nav bar text: "Home"

I know there's some history around the name "index" being special in web app development, but it's a weird name to put in front of the end user. I could also live with this:

- Component name: *Index.razor*
- Page heading & title: `<h1>Home</h1>`
- Nav bar text: "Home"

**Comment by javiercn** [comment]
@danroth27 have you tried implementing your suggestions in a sample project?

**Comment by danroth27** [comment]
> @danroth27 have you tried implementing your suggestions in a sample project?

Yup, they work fine. No conflicts.

**Comment by surayya-MS** [comment]
Should @page also change for Weather.razor to @page "/weather"?
