### ISSUE TITLE
Microsoft.Azure.Storage.StorageException - System.Security.Cryptography.Algorithms is not supported on this platform

### ISSUE THREAD

**Issue by misterraj7** [dotnet/aspnetcore#48726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to send a storage queue message in azure from blazor wasm.(6.0)

The same code works from a console application but not from the blazor wasm project.

### Expected Behavior

message must be sent to azure storage queue

### Steps To Reproduce

 public static class QueueExtensions
    {
        public  static async Task SendQueue(this QueueObject Q)
        {
            try
            {

              QString ="azure connection string"
                QName = "testq";
               
                string json = JsonConvert.SerializeObject(Q);
                byte[] messageBytes = Encoding.UTF8.GetBytes(json);

                CloudQueue queue = GetCloudQueue(QString, QName);
                CloudQueueMessage queueMessage = new CloudQueueMessage(messageBytes);
               

                await queue.AddMessageAsync(queueMessage);
                
            }
            catch(Exception ex)
            {

            }
           

        }

        static CloudQueue GetCloudQueue(string storageConnectionString, string queueName)
        {

            try
            {
                // Parse the storage account connection string
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageConnectionString);

                // Create a CloudQueueClient object
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

                // Get a reference to the queue
                CloudQueue queue = queueClient.GetQueueReference(queueName);

                // Create the queue if it doesn't exist
                //queue.creCreateIfNotExists();

                return queue;
            }

            catch(Exception ex)
            {
                return null;
            }
        }
    }

### .NET Version

6.0

**Comment by martincostello** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/87214.
