### ISSUE TITLE
Update Third Party Notices if needed

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/aspnetcore#48727]
We need to check if Third Party Notices need to be updated.

https://github.com/dotnet/aspnetcore/blob/main/THIRD-PARTY-NOTICES.txt 
https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES
https://github.com/dotnet/aspnetcore/blob/main/src/Components/THIRD-PARTY-NOTICES.txt

**Comment by danmoseley** [comment]
is src/Components/THIRD-PARTY-NOTICES.txt also blazor?

**Comment by surayya-MS** [comment]
> is src/Components/THIRD-PARTY-NOTICES.txt also blazor?

Looks like it is. Thanks!
