### ISSUE TITLE
Http2WebSocketTests.HEADERS_Received_SecondRequest_ConnectProtocolReset is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#48737]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2WebSocketTests.HEADERS_Received_SecondRequest_ConnectProtocolReset

## Error Message

```text
Assert.Equal() Failure
Expected: 1
Actual:   0
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2WebSocketTests.HEADERS_Received_SecondRequest_ConnectProtocolReset() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:line 648
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=301580&view=results

**Comment by amcasey** [comment]
@BrennanConroy says
> I figured out the test failure in [Retry failing helix test by amcasey · Pull Request #48694 · dotnet/aspnetcore (github.com)](https://github.com/dotnet/aspnetcore/pull/48694)
> Was kind of interesting. It's a test issue not a product issue, and the root cause is present in other test(s) as well. See [Quarantine Http2WebSocketTests.HEADERS_Received_SecondRequest_Accepted · Issue #42133 · dotnet/aspnetcore (github.com)](https://github.com/dotnet/aspnetcore/issues/42133) for another issue with the same assert.

**Comment by mitchdenny** [comment]
Looks like this was already unquarantined.
