### ISSUE TITLE
Proposal: expand anchor tag helper to make single-parameter changes easier

### ISSUE THREAD

**Issue by NickCraver** [dotnet/aspnetcore#4874]
A common scenario I run into is needing to use the current query string (action parameters) and change 1 for the purposes of sorting or filtering (e.g. a search query against the current other filters). Let's take an example:
```
/path/page?minRuns=20&filter=someText&database=PRIZM&sort=RunsPerSecond&order=Asc
```
In the view, I have a table with columns with headers that are sorting links.  Let's say I have 3 columns so the headers look like this:
```html
<th><a href="/path/page?minRuns=20&amp;filter=someText&amp;database=PRIZM&amp;sort=Runs">Runs</a></th>
<th><a href="/path/page?minRuns=20&amp;filter=someText&amp;database=PRIZM&amp;sort=Duration">Duration</a></th>
<!-- repeat 8 times... -->
```
Currently, generating the query string of a thing that *differs by one* is something users have to do very manually, generally with a builder or making a collection to serialize per link in a helper. I think this could be made much cleaner as something the framework provides. You can *almost* do this today with [`asp-all-route-data` via tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper#asp-all-route-data), but it could be improved.

Here's the most succinct way I can find to do this today (note this is just query params, but you get the idea):
```html
@{ var routeDict = Context.Request.Query.ToDictionary(q => q.Key, q => q.Value.ToString()); }
<th><a asp-all-route-data="routeDict" asp-route-sort="@Sorts.Runs">Runs</a></th>
<th><a asp-all-route-data="routeDict" asp-route-sort="@Sorts.Duration">Duration</a></th>
```

## Proposal
What if the anchor tag helper allowed `asp-all-route-data` without a value? The default would be the current route data. Since this already works in combination with `asp-route-{key}="value"`, the combination becomes simply:
```html
<th><a asp-all-route-data asp-route-sort="@Sorts.Runs">Runs</a></th>
<th><a asp-all-route-data asp-route-sort="@Sorts.Duration">Duration</a></th>
```

Perhaps there's a simpler and/or different way to achieve this (e.g. a new attribute), I was just thinking minimal changes would save code and open up use cases here. Thoughts?

/cc @DamianEdwards

**Comment by captainsafia** [comment]
Hi. We're closing this issue as there has not been any community feedback in quite sometime. Please open a new issue if necessary.
