### ISSUE TITLE
Blazor WebAssembly not caching in browser

### ISSUE THREAD

**Issue by ns6000** [dotnet/aspnetcore#48748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor WebAssembly is caching libraries to browser's Cache Storage only on localhost access.

When i was starting to develop WASM project, i've inspected browser cache to make sure that dotnet and other libraries are cached and next startups are faster (sha checks, returned statuses 204, cache is used). This works well. But after publishing the project to IIS hosting and accessing the page over the internet, libraries are never stored in browser cache. So effectively, libraries are always downloaded. Running browser on the same machine where the IIS is located works and libraries are cached (same as running browser directly from VS in development). I've tried this on default projects in .net6 and .net7 and the behaviour is the same.

I must be missing something basic here...

### Expected Behavior

Libraries are cached to browser regardless if the page is accessed localy or remotely over the internet.

### Steps To Reproduce

In VS:

- create new "Blazor WebAssembly App"
- check off "Configure for HTTPS"
- publish (i'm using just the directory publish with manual copy of files to created web page on iis)

### .NET Version

7.0.302

**Comment by javiercn** [comment]
@ns6000 thanks for contacting us.

Caching depends on the caching APIs that are only available in secure context. We don't do caching over HTTP because the APIs are not available.
