### ISSUE TITLE
Unified project template conventions and mitigating accidental inclusion in WebAssembly build

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#48758]
We need to update the new project template and SDK rules so that:

 * There are good conventions for including/excluding things in the Server and WebAssembly builds based on:
   * Directory
   * Filename
   * `#if`
 * We help developers not to include code or other assets like config in the WebAssembly compilation by mistake
   * For example, we might *only* include `.cs` files from a `WebAssembly` or `Shared` directory
   * For project/package references, we might have special metadata for "server", "webassembly", and "shared". Then if you add any project/package reference and it doesn't have this metadata (which is the case by default) then:
     * During development this logs a warning
     * During publish it's an error
     * ... so that developers aren't prevented from following existing tutorials (especially important for learners) but they do get a reasonable warning that they have to take some action before publishing to express a clear intent

**Comment by danroth27** [comment]
Is this a duplicate of #46398?

**Comment by SteveSandersonMS** [comment]
Yes, closing as duplicate of that.
