### ISSUE TITLE
Blazor SSR APIs for accessing HttpContext without IHttpContextAccessor

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#48769]
Ideally we'd support things like:

```cs
[FromHttpContext] public HttpRequest Request { get; set; }
[FromHttpContext] public HttpResponse Response { get; set; }
```

This is useful for things like:

 * Reading the HTTP method
 * Reading and writing cookies
 * Setting arbitrary response headers

**Comment by DamianEdwards** [comment]
Some concrete examples where I hit needing this when porting an app from Razor Pages to Blazor SSR:

- Setting HTTP response caching headers
- Getting `HttpContext.TraceIdentifier` for the app's *Error.razor* page

**Comment by danroth27** [comment]
@mkArtakMSFT I think we're going to need this one for .NET 8. We should discuss adding this to rc1.

**Comment by SteveSandersonMS** [comment]
@danroth27 The rationale we give for not using `IHttpContextAccessor` in Blazor doesn't apply in SSR. Is the reason for wanting an alternative way to reach `HttpContext` purely to keep the guidance easy to understand, or is there some other objective problem we're trying to avoid?

Anything we implement to reach `HttpContext` is internally going to be exactly equivalent to `IHttpContextAccessor`. If you're aware of some subtleties I'm missing please let me know.

**Comment by danroth27** [comment]
> The rationale we give for not using IHttpContextAccessor in Blazor doesn't apply in SSR

What about [the rationale we give for not using IHttpContextAccess in general](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor#remarks)?:

> This interface should be used with caution. It relies on [AsyncLocal<T>](https://learn.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1) which can have a negative performance impact on async calls. It also creates a dependency on "ambient state" which can make testing more difficult.

@davidfowl @DamianEdwards

**Comment by SteveSandersonMS** [comment]
I guess it uses the AsyncLocal trick because it's registered as a singleton. TBH I don't know why `IHttpContextAccessor` is registered as singleton and not scoped, but perhaps it's for back compat reasons. We wouldn't need to do the same here.

If anyone knows of reasons why we shouldn't have `HttpContext` accessible through a scoped service, please say so!

**Comment by halter73** [comment]
> TBH I don't know why IHttpContextAccessor is registered as singleton and not scoped, but perhaps it's for back compat reasons.

I remember this conversation back when we added `IHttpContextAccessor`. IIRC, the primary example given was a singleton logging provider that enriched logs with details from the `HttpContext`.

**Comment by SteveSandersonMS** [comment]
@davidfowl @DamianEdwards Pinging the two of you as we just about have time for taking one last action here.

There will definitely be cases where people want to access `Request`/`Response` in Blazor SSR, e.g., for reading/writing headers/etc. As of right now people would have to use `IHttpContextAccessor`, which we don't love because **even though it would be technically safe in the Blazor SSR case, people may later add `@rendermode Server` and make it unsafe, or they might just get into the habit of using it everywhere** and there is [a claim that it could adversely affect perf](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-7.0#remarks).

If it's true that we really should be pushing people away from `IHttpContextAccessor`, then our best option would be something like:

 * In Blazor SSR, support parameters like the following (probably supporting just these three):
   * `[SupplyParameterFromHttpContext] public HttpContext Context { get; set; }`
   * `[SupplyParameterFromHttpContext] public HttpRequest Req { get; set; }`
   * `[SupplyParameterFromHttpContext] public HttpResponse Resp { get; set; }`
 * In other Blazor hosting models (e.g., interactive Server/WebAssembly rendering, or MAUI), no values would be supplied for those parameters and hence they would be left as `null`. Developers will have to avoid reliance on those parameters in non-SSR cases.

I think we could still justify doing that if the desire to avoid `IHttpContextAccessor` is strong enough. However if we believe `IHttpContextAccessor` is acceptable to use in edge cases then perhaps this is unnecessary.

**Comment by SteveSandersonMS** [comment]
That sounds fine to me. So it would probably look like:

```cs
[SupplyParameterFromHttpContext] public HttpContext? Context { get; set; }
```

... unless anyone has a different specific naming suggestion. The lengthy "supply parameter from" prefix is for alignment with `SupplyParameterFromForm`/`SupplyParameterFromQuery`.

**Comment by DamianEdwards** [comment]
I think consistency wins here so sticking with the longer form name until such time we decide to support terser names for all the parameter-source attributes.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT @danroth27 Based on the discussion here (and the reason why we started it), I've filed this in `8.0-rc2` with the "1 - Important" priority, assigned to myself. I think it will be a reasonably small amount of work.

If you disagree with this filing/prioritisation please let me know.

**Comment by SteveSandersonMS** [comment]
Implemented in https://github.com/dotnet/aspnetcore/pull/50253. See updated usage info there.

**Comment by davidfowl** [comment]
Agree with the solution here, we shouldn't rely in IHttpContextAccesor by default. I'm wondering what it means for cascading values that need the http context in the SSR case and the AuthenticationStateProvider for Blazor SSR apps.

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/50253

**Comment by jchannon** [comment]
I have `8.0.100-rc.2.23469.4` installed on MacOS, in my `Foo.razor` file I have:

`[CascadingParameter] public HttpContext? Context { get; set; }`

I have debugged the app and in `OnInitialized` and in my own method invoked when I have a HTML button submit a form, in both scenarios Context is null. 

Have I misssed something? Thanks
