### ISSUE TITLE
Integrate with WebAssembly multithreading

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#48768]
As multithreading is added to the core .NET WebAssembly runtime, we need to ensure this doesn't lead to invalid/dangerous scenarios for Blazor components.

 * Min bar: if the renderer is accessed from the wrong thread, throw
 * Ideal: sync context with semantics equivalent to Blazor Server or WebView, so `InvokeAsync` works

This is going to come in late so we should take a risk-averse position on how much we attempt to implement here.

**Comment by pavelsavara** [comment]
Related https://github.com/dotnet/runtime/pull/86759

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck, @pavelsavara is there any remaining work here for our team, or should this be closed already?

**Comment by pavelsavara** [comment]
this needs core review https://github.com/dotnet/aspnetcore/pull/48991

**Comment by mkArtakMSFT** [comment]
@lewing, @pavelsavara, @maraf at this point, given all the other other critical issues on our plate, I've moved this out of .NET 8 release.
