### ISSUE TITLE
Debug the ASP.NET Core API project with IIS Express profile, the web page keeps loading.

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/aspnetcore#48774]
Azure DevOps work item: [[1791953](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1791953)][WebToolsE2E]F5 to debug the ASP.NET Core API project with IIS Express profile, the web page keeps loading.

### To Reproduce

1. Install latest Dev17.7 Preview 2([d17.7-33808.371](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7892833&view=results)).

>  - Check .NET SDK (Preview) in the installation wizard to install .NET 8.0 Preview 5.

2. Apply feeds: https://pkgs.dev.azure.com/dnceng/public/_packaging/8.0.100-preview.5.23303.2-shipping/nuget/v3/index.json

1. After VS installed, open VS, and create ASP.NET Core API project.
1. Build and F5 to run the project with IIS Express.

### Actual behavior
The web page keeps loading.
![image](https://github.com/dotnet/runtime/assets/35762055/fc2c83ca-a67a-478c-8c8d-3c9342b7c363)

### Regression
ASP.NET Core API is new project template in .NET 8.0, it's not a regression

**Comment by mitchdenny** [comment]
This is by design. The the _ASP.NET Core API_ template is designed to be used by Kestrel only. We should fine type what we emit in ```launchSettings.json``` to make this more obvious. If you want to use the project template with IIS you could always replace this line:

```csharp
var builder = WebApplication.CreateSlimBuilder(args);
```

with this:

```csharp
var builder = WebApplication.CreateBuilder(args);
```

This will bring in the infrastructure that will support hosting with IIS.

**Comment by mitchdenny** [comment]
Actually it looks like @DamianEdwards already made changes to the ```launchSettings.json``` file a few months ago - so I'm wondering why it isn't working.

**Comment by mitchdenny** [comment]
These IIS settings have been removed from the template since it isn't compatible.
