### ISSUE TITLE
The Blazor Server application runs significantly slower when using the HttpSys server

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#48799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Blazor Server application can use either the Kestrel, IIS, or HttpSys server.

When the Blazor Server application is used locally, there is no noticeable difference in data transmission time between the HttpSys server and the Kestrel or IIS servers.

However, when the Blazor Server application is accessed over the Internet or through a VPN, the data transmission is 3x to 4x slower when the application uses the HttpSys server.

Data transmission refers to the transfer of new page elements via WebSocket.

HttpSys - 2s:

![image](https://github.com/dotnet/aspnetcore/assets/10242002/cb589ac6-3c43-4050-9935-94daf21247a6)

IIS - 0.5s:

![image](https://github.com/dotnet/aspnetcore/assets/10242002/b36e4310-04a0-4e6b-90be-1239ed8d068f)

### Expected Behavior

The Blazor Server application, when using the HttpSys web server, runs at the same speed as when using the Kestrel or IIS web servers.

### Steps To Reproduce

Test  application public repo: [SlowHttpSys](https://github.com/Jarek300/SlowHttpSys).

The "http" and "https" profiles run the application using the Kestrel web server. The "httpsys" profile runs the application using HttpSys web server.

After launching the application, press the "Show palette" button. This action causes the transmission of 170kB of data through WebSocket.  

If the application uses HttpSys server and is accessed via VPN, transmission takes about 2 seconds. 

If the application is accessed via VPN but it uses the IIS server or Kestrel Web server, transmission takes about 0.5 second.

If the application is running locally, the difference is negligible and not noticeable.

### .NET Version

7.0.7

**Comment by amcasey** [comment]
Thoughts, @mgravell?

**Comment by JarJasAskom** [comment]
Something new?

**Comment by mgravell** [comment]
I haven't had chance to investigate yet, but: one thing to try here would be enabling kernel buffering, to see whether it is latency / small write related (which kernel buffering helps significantly with). I'll pull down the repro tomorrow and see if it is a match.

**Comment by mgravell** [comment]
Looking at this, the mention of "local fine, VPN bad" (I'm paraphrasing, obviously) makes me suspicious that this is indeed the latency issue with the http.sys implementation; the good news is: it is pretty easy to validate this locally:

If you're on .NET 8 (preview 6 or later), then when calling `UseHttpSys(...)`, set the

``` c#
options.EnableKernelResponseBuffering = true;
```

flag; if you're on **up to date** .NET 6 or .NET 7, the same feature has been backported via an app-context switch, and can be enabled via (before calling `UseHttpSys`):

``` c#
AppContext.SetSwitch("Microsoft.AspNetCore.Server.HttpSys.EnableKernelResponseBuffering", true);
```

Please could you try this and let me know if it helps?

**Comment by JarJasAskom** [comment]
Do you mean option EnableResponseCaching added in one of updates of NET 7?. Using this option does not help. Test program has turned on EnableResponseCaching.


    // Summary:
    //     Attempts kernel mode caching for responses with eligible headers. The response
    //     may not include Set-Cookie, Vary, or Pragma headers. It must include a Cache-Control
    //     header with Public and either a Shared-Max-Age or Max-Age value, or an Expires
    //     header.
    public bool EnableResponseCaching { get; set; }

**Comment by mgravell** [comment]
No, I don't; this is a new and separate feature, activated in the ways listed above.

**Comment by mgravell** [comment]
(specifically, response *caching* relates to behavior between different requests, and does not really apply to web-sockets AFAIK, because it has transitioned protocol via a 101 response; response *buffering* relates to how data in a single response is written to the output device)

**Comment by JarJasAskom** [comment]
Thank you! Adding 

AppContext.SetSwitch("Microsoft.AspNetCore.Server.HttpSys.EnableKernelResponseBuffering", true);

solves the problem!

**Comment by mgravell** [comment]
/ping @SteveSandersonMS for visibility, in case there's any benefit in adding any new guidance

**Comment by SteveSandersonMS** [comment]
Thanks @mgravell. Are there any drawbacks to doing this? Any reason we shouldn't advise everyone deploying to HttpSys to do this? Just so we can judge whether it's appropriate to add this to the docs.

Also I'd be interested to know why this setting isn't the default, if that's something you know about.

**Comment by mgravell** [comment]
(we did try it on-by-default; CI was fine with it: https://github.com/dotnet/aspnetcore/pull/47958)
