### ISSUE TITLE
ProblemDetails are not returned when an application is started via a WebApplicationFactory (i.e in an integration test)

### ISSUE THREAD

**Issue by domholmes** [dotnet/aspnetcore#48809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An application that is correctly returning problem details when unhandled exceptions occur fails to do so when the same application is started in an integration test via a `WebApplicationFactory`.

### Expected Behavior

Problem details appear in a response from an application running in an integration test in the same way they appear in an application running normally.

### Steps To Reproduce

1. Create a basic application with problem details enabled in Program.cs
2. Throw an exception in a controller action
3. Call the endpoint and observe a HTTP 500 response with problem details present in the body
4. Create an integration test that starts the application via a `WebApplicationFactory<Program>` and hits the same endpoint
5. Observe a HTTP 500 response but with an _empty_ body

This can easily be replicated in the [sample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/test/integration-tests/IntegrationTestsSample) by simply adding the following in Program.cs, inserting a thrown exception into one of the pages and then running a relevant test and inspecting the response body.

services.AddProblemDetails();
app.UseExceptionHandler();

### .NET Version

SDK 7.0.302

**Comment by captainsafia** [comment]
Thanks for filing this issue, @domholmes! Following some debugging, I believe that this issue has been resolved following some changes we made the ProblemDetails API in .NET 8. I'm able to repro the bug in 7.0 but not 8.0. Can you verify the same on your end?

**Comment by domholmes** [comment]
> Thanks for filing this issue, @domholmes! Following some debugging, I believe that this issue has been resolved following some changes we made the ProblemDetails API in .NET 8. I'm able to repro the bug in 7.0 but not 8.0. Can you verify the same on your end?

That's interesting, thanks. I'll give it a try with 8.0.

**Comment by domholmes** [comment]
Apologies for the delay, I can confirm this is fixed in .NET 8.

**Comment by MariuszMielcarski** [comment]
Is there any workaround for this issue in 7.0?
