### ISSUE TITLE
How to override `UserManager` `GetUserIdAsync` and `FindByIdAsync` method?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#48825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would like to use custom `User.Id` as `sub` claim instead of `AspNetUser.Id`. How to achieve that?

### .NET Version

7.0.107

**Comment by martincostello** [comment]
You should be able to create your own derived class, override the methods you're interested in changing, and then register that with the service collection as your `UserManager` implementation.

Custom implementation:

```csharp
public class MyUserManager : UserManager<AspNetUser>
{
    // Constructor omitted for brevity

    public override async Task<string> GetUserIdAsync(AspNetUser user)
    {
        // Your custom code
    }

    public override Task<TUser?> FindByIdAsync(string userId)
    {
        // Your custom code
    }
}
```

Service registration:

```csharp
services.AddIdentity<AspNetUser, AspNetRole>((p) => { /* Configure */ })
        .AddUserManager<MyUserManager>();
```
