### ISSUE TITLE
dotnet watch not detecting changes to Razor Class Library

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#48835]
### Description

When I run `dotnet watch --project .\MyWasmApp\MyWasmApp.csproj` that consumes a Razor Class Library in `.\MyClassLibrary\MyClassLibrary.csproj`, then no changes made to components in the class library are reflected in the browser.

Note that this works fine in VS 2022 17.7 Preview 1 when running the app with hot reload.

### Configuration

* Which version of .NET is the code running on? 8.0.100-preview.4.23260.5
* What OS and version, and for Linux, what distro? Windows 11 Professional
* What is the architecture (x64, x86, ARM, ARM64)? X64
* Do you know whether it is specific to that configuration? No
* If you're using Blazor, which web browser(s) do you see this issue in? Edge

1. Create new Blazor WASM app
2. Create new Razor class lib
3. Add a reference from the WASM app to the library
4. Add an instance of `Component1` in the class library to the main page of the WASM app
5. `dotnet watch --project .\MyWasmApp\MyWasmApp.csproj`
6. Change the markup in `Component1.razor`

Expected: The browser contents should hot reload
Actual: Nothing happens

Now try running in VS 2022 17.7 preview 1 with hot-reload enabled.  You'll see the contents update when `Component1` is altered.

**Comment by mkArtakMSFT** [comment]
@mrpmorris thanks for reporting this.
Can you please try the latest RC2 release and see if this is already fixed?
If not, could you please share the logs from the console window after adding the `--verbose` parameter to the command line.

**Comment by mrpmorris** [comment]
This works now, thank you!
