### ISSUE TITLE
_From @mikaelm12 on Thursday, 03 January 2019 20:00:41_

### ISSUE THREAD

**Issue by VenkataRaoBorra** [dotnet/aspnetcore#48850]
_From @mikaelm12 on Thursday, 03 January 2019 20:00:41_

Sorry it's a bit unclear to me. Are you saying that you're trying to mix using classic asp.net and asp.net core on the server and client, because that will not work.
Or are you just saying that in the past you have used SignalR on asp.net?

_Originally posted by @muratg in https://github.com/dotnet/aspnetcore/issues/6923#issuecomment-456457777_

**Comment by danmoseley** [comment]
this does not appear to be an issue, but a copy paste.

**Comment by VenkataRaoBorra** [comment]
Actually this is an issue which I am facing now and old threads doesn't provide the solution.

Can you please check the old threads for better understanding
