### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by TonyHCIR** [dotnet/aspnetcore#48870]
**Issue description**

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

_Originally posted by @TonyHCIR in https://github.com/dotnet/docs/issues/35863_

**Comment by gfoidl** [comment]
No details provided. Closing.
