### ISSUE TITLE
cannot route url - AdditionalAssemblies in app.razor - blazor web app

### ISSUE THREAD

**Issue by tinikook** [dotnet/aspnetcore#48875]
blazor web App
in .net 8 review 5 i can't use AdditionalAssemblies in app.razor file.
specifically :
Router AppAssembly="@typeof(App).Assembly" PreferExactMatches="@true" AdditionalAssemblies=new[] {assembly}.
the router doesn't seem to find the site in RCL

**Comment by javiercn** [comment]
@tinikook thanks for contacting us.

There are APIs to manually register additional endpoints when calling MapRazorComponents, and we will be automatically discovering pages from referenced assemblies in a future preview.

**Comment by mkArtakMSFT** [comment]
Thanks @javiercn.
Here is the issue tracking the remaining work here: https://github.com/dotnet/aspnetcore/issues/48767

**Comment by danroth27** [comment]
> There are APIs to manually register additional endpoints when calling MapRazorComponents

@javiercn What are these APIs? How do you register additional endpoints from other assemblies when calling `MapRazorComponents`?
