### ISSUE TITLE
[Consumes] and CORS together doesn't work without a spooky workaround

### ISSUE THREAD

**Issue by plutext** [dotnet/aspnetcore#4887]
#### Is this a Bug or Feature request?:
feature request

#### Description of the problem:

I'd like to be able to consume either posted JSON or form data at the same endpoint.  As things stand, I get:

```
fail: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[1]
      Request matched multiple actions resulting in ambiguity. Matching actions: 
:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLDLB0LJCPJ4", Request id "0HLDLB0LJCPJ4:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

```

https://andrewlock.net/model-binding-json-posts-in-asp-net-core/ suggests using different endpoints, but I can't do that on this occasion

https://massivescale.com/web-api-routing-by-content-type/ suggests a way to do it for asp.net; is something like this available in core mvc?

His solution looks like:

```
[ContentTypeRoute("api/test/bytype", "application/json")]

or

[ContentTypeRoute("api/test/bytype", "application/x-www-form-urlencoded")]

```
 in Java's JAX-RS for example, there is @Consumes

**Comment by rafikiassumani-msft** [comment]
@plutext  I was not able to reproduce this issue with .NET6.  Below is the code: 

1. CORS config

```C#
   app.UseCors(opts => {
        opts.AllowAnyOrigin();
        opts.AllowAnyMethod();
        opts.AllowAnyHeader();
  });
```

2. Controller

```C#
[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{

    [HttpPost("test")]
    [Consumes("application/json")]
    public IActionResult ActionForJson(Person person) => Ok(person.Name);

    [HttpPost("test")]
    [Consumes("application/x-www-form-urlencoded")]
    public IActionResult ActionForForm([FromForm] string name) => Ok(name);

}

public class Person
{
    public string Name { get; set; }    
}

```

After using `fetch` with `application/json` header in the browser, I was able to get the 204 status code for the pre-flight request as shown in the below: 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/87031580/150444433-f0d1a70e-9f3b-4818-bae4-349ffed8c156.png">

The `application/x-www-form-urlencoded` content type does not trigger a pre-flight request as you may know. 
From my quick reproduction, this is not an issue anymore.  Let us know if you are still experiencing this and we can further investigate.
