### ISSUE TITLE
How to update authorization policy requirement after the app has started?

### ISSUE THREAD

**Issue by askids** [dotnet/aspnetcore#48874]
hi,

I am using .Net 6 WebApi, in which I have my custom authorization policy handler, which is applying the rules based on the registered policy requirement. When I am registering the policy, I passing custom config data which will be used by the custom policy provider to validate and apply the authorization.

```
public class AuthPolicyConfig 
{
    public string PolicyName {get; set;}
    public string Property1 {get; set;}
    public string Property2 {get; set;}
    public List<string> Property3 {get; set;}
}

public class AuthPolicyRequirementsReq1 :  IAuthorizationRequirement
{
    public AuthPolicyConfig Policy {get; }
    
    public AuthPolicyRequirementsReq1(AuthPolicyConfig policy)
    {
        Policy = policy;
    }
}
```

Currently, when I am registering the policy at application startup, the policy config data is coming from a external provider using custom configuration provider, which also support refresh of config data.

```
foreach(var authPolicyConfig in authPolicyConfiguration)
{
    options.AddPolicy(authPolicyConfig.PolicyName, policy => {
        policy.AddAuthenticationSchemes(new strin[]{"scheme1","scheme2"});
        policy.RequireAuthenticatedUser();
        policy.Requirements.Add(new AuthPolicyRequirementsReq1(authPolicyConfig));
    });
}
```

In the HandleRequirementAsync method of my custom policy handler, along with the AuthorizationHandlerContext, I also get the requirement.
```
public class AuthPolicyHandlerReq1 : AuthorizationHandler<AuthPolicyRequirementsReq1>
{
    private readonly IAuthPolicyProviderReq1 _policyProvider;
    public AuthPolicyHandlerReq1(IAuthPolicyProviderReq1 policyProvider)
    {
        _policyProvider = policyProvider;
    }
    
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, AuthPolicyRequirementsReq1 requirement)
    {
        var someUserClaim = context.GetSomeUserClaim();
        if(policyProvider.ValidatePolicy(someUserClaim, requirement.Policy))
        {
            context.Succeed();
        }
        return Task.CompleteTask;
    }
}    
```

Now I am trying to figure out, how do I update the requirement on existing policy, if my config provider provides me with updated requirement, when the application has already started? 

Thanks!

**Comment by davidfowl** [comment]
What does your policy in config represent? What data is in there and how does it map to the policy defined?

**Comment by askids** [comment]
> What does your policy in config represent? What data is in there and how does it map to the policy defined in startup?

There are different type of policies that I am implementing as custom policy that can be leveraged by different routes within the APIs. One of the policy configuration properties is policy type. Based on policy type, I register different type of policy requirement for that policy. Other properties within the policy config represents below combination of data.
Few examples, 
a) could be list of OAuth2 client ids 
b) could be list of roles
c) combination of above
d) roles with wild card rules like mylobname1*, mylobname1_support*
e) bypass route - routes on which I would want to skip authorization check.
f) fallback policy indicator - will be used to register the policy as default fallback policy

I have different policy handlers, providers, requirement classes to support these different type of policies based on policy type.

**Comment by askids** [comment]
@javiercn any suggestions?

**Comment by davidfowl** [comment]
You can implement a custom [iauthorizationpolicyprovider](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-7.0#custom-iauthorizationpolicyprovider)

**Comment by brockallen** [comment]
Why not simply have the authorization handler query out to the external system that has those requirements that change over time? That's the reason the handler is in DI -- so it can take dependencies (like a DbContext, HttpClient, etc).

**Comment by davidfowl** [comment]
Agreed, if that were indeed possible it would be a better approach. Hard to tell without looking at the data that's coming from the requirement.

**Comment by askids** [comment]
> You can implement a custom [IAuthorizationPolicyProvider ](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-7.0#custom-iauthorizationpolicyprovider)

Currently I do use Custom AuthPolicyProvider which has a validatePolicy method that gets a copy of policy requirement from the Authorization handler (policy requirement is AuthPolicyConfig registered during startup). This policy requirement is then used to validate claim against it. However, this is not implementing [IAuthorizationPolicyProvider](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-7.0#custom-iauthorizationpolicyprovider). Also since policy is registered using options.AddPolicy, it would be using DefaultAuthorizationPolicyProvider. 

```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, AuthPolicyRequirementsReq1 requirement)
    {
        var someUserClaim = context.GetSomeUserClaim();
        if(policyProvider.ValidatePolicy(someUserClaim, requirement.Policy))
        {
            context.Succeed();
        }
        return Task.CompleteTask;
    }
```

But like @brockallen suggested, what I could potentially do is inject IOptionsMonitor in my existing custom AuthPolicyProvider to get a new overall poliicy configuration (external provider will take care of updating it). Then using the incoming policy requirement (passed to my ValidatePolicy method), take the policy name and just get the new copy from options.CurrentValue instead of using the requirement value from parameter passed.

Once this is fully working, I can even look at simplifying the AuthPolicyRequirementsReq1 to just have policy name and type. Since I will anyway get the actual requirement from Options, I no longer need to register all remaining values upfront as part of the policy configuration during application startup. All I need to register is policy name and policy type.

I will give this a try. Thanks a lot to both of you for your inputs.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
