### ISSUE TITLE
Blazor Server hosted behind Azure Frontdoor wrong BaseUri

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#48909]
### Describe the bug

Situation:
- Blazor Server (AspNetCore 7) running in an app service hosted on linux
- Azure AD B2C used for authentication
- Azure Frontdoor is used to map custom domain to app service, provide WAF policies etc

Problem:
- Authentication not working because wrong redirect url is being constructed https://myapp.azurewebsites.net/ instead of https://myapp.mydomain.com/
- Various other features are not working because `NavigationManager.BaseUri` is also pointing to the wrong url instead of my own domain

So the solution is not only rewrite the redirect-url when authentication, because also other constructed url's are not working due to containing the wrong url.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please follow the guidance here to configure the request forward middleware: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0#forwarded-headers-middleware-order
