### ISSUE TITLE
Blazor SSR forms redirect and antiforgery tokens?

### ISSUE THREAD

**Issue by Markz878** [dotnet/aspnetcore#48903]
Could Blazor team give some insights for these questions our team has been wondering related to Blazor SSR in preview 5?

Q1. How do we do a redirect after a form post? I tried using NavigationManager but it throws a NavigationException. In Razor Pages we return a Redirect IActionResult, is there some corresponding method here?

Q2. Will antiforgery tokens be automatically handled by the framework in form posts? And if not, how should they be handled since there is no @Html.AntiForgeryToken() taghelper?

**Comment by javiercn** [comment]
> Q1. How do we do a redirect after a form post? I tried using NavigationManager but it throws a NavigationException. In Razor Pages we return a Redirect IActionResult, is there some corresponding method here?

You can use navigation manager to perform the redirect.

> Q2. Will antiforgery tokens be automatically handled by the framework in form posts? And if not, how should they be handled since there is no @Html.AntiForgeryToken() taghelper?

Antiforgery validation will be built-in. It's not there yet.
