### ISSUE TITLE
Included .resx file throws error when containing project is referenced from other project (.NET 6)

### ISSUE THREAD

**Issue by FredMar** [dotnet/aspnetcore#48916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two projects: Project A (ASP.NET Core web app) and Project B (Console app).

In project A I have a .resx file with translated strings I want the data annotations to use (like Required etc.). When I try to reference project A from other projects (in this case I tried with project B as a test), I get the error System.InvalidOperationException: 'Invalid manifest format. 'ResourcePath' must contain a text value.

Error:

![image](https://github.com/dotnet/aspnetcore/assets/16269671/9d4a0516-81b3-424a-9c6c-bd701c47c73a)

### Expected Behavior

That I can reference the project in other projects.

### Steps To Reproduce

https://github.com/FredMar/ResxErrorTest

### Exceptions (if any)

System.InvalidOperationException: 'Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'ProjectAWeb'.'

![image](https://github.com/dotnet/aspnetcore/assets/16269671/8f81ae3f-eaf7-491d-9fc0-6ad0887799f6)

### .NET Version

.NET 6.0

### Anything else?

See included link to GitHub for project/code

**Comment by danmoseley** [comment]
```
>	Microsoft.Extensions.FileProviders.Embedded.dll!Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestParser.Parse(System.Reflection.Assembly assembly, string name) Line 38	C#
 	Microsoft.Extensions.FileProviders.Embedded.dll!Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider.ManifestEmbeddedFileProvider(System.Reflection.Assembly assembly) Line 26	C#
 	ProjectBConsole.dll!ProjectBConsole.Program.Main(string[] args) Line 10	C#

```

**Comment by javiercn** [comment]
@FredMar thanks for contacting us.

Why are you using the ManifestEmbeddedFileProvider at all? It doesn't seem that your repro includes its usage.

**Comment by FredMar** [comment]
@javiercn Thank you for taking the time to look at my issue.

You are right - the provided code is just an example of what we are trying to do. Basically we have a base ASP Core web-app with translations to the default strings for the data annotations like Required etc. We are then trying to make another customized ASP Core web-app on top of the base app with customized translations of the data annotation strings - it's this step that fails with the error "Invalid manifest format. 'ResourcePath' must contain a text value."

Hope this helps.
