### ISSUE TITLE
Add empty option for the Blazor Web App template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#48913]
The Blazor Web App template currently contains sample content including sample pages and Bootstrap. We need to have a way to create an empty Blazor Web App template that doesn't have this sample content.

Previously we've done this by having separate empty Blazor templates. Can we instead have an option on the Blazor Web App template for adding sample content that you can unselect?

**Comment by danroth27** [comment]
Looking at how our existing templates are used, it appears that the empty templates are not used as much as the ones with sample content. So, it looks like the default should be to include the sample content and then have an `--empty` option to generate an empty template. This option would surface in VS and would be sticky. One benefit of this approach is all the other template options wouldn't need to be duplicated.

The empty version of the template would have a basic Home page, but no Counter or Weather pages. It would include a simple MainLayout without a NavMenu. It wouldn't include Bootstrap. Just like the existing empty templates. 

We'd need to figure out how this would interact with the authentication options, like the proposed Blazor default identity UI (#48786). Since the Bootstrap styling wouldn't be available, users would need to style the Identity UI along with the rest of the app. @halter73 Do you foresee any problems with this?

**Comment by danroth27** [comment]
I discussed the following options with @halter73 for how to handle --empty with individual user accounts:

1. We could author the template to remove any Bootstrap specific stuff from the default identity UI if you specify --empty
1. We could generate the identity UI with the Bootstrap classes, which will just get ignored. 
1. We could add Bootstrap if you add the auth UI
1. We could not support the default identity UI with --empty

I think we should go with the third option, which basically says that our default identity comes with styling that depends on Bootstrap.

@mkArtakMSFT If there are no additional questions, I think this is ready to assign to engineering.

**Comment by SteveSandersonMS** [comment]
This was done a while ago
