### ISSUE TITLE
Surface option in the Blazor Web App template for WebAssembly interactivity

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#48912]
Once we're ready for WebAssembly based interactivity and figured out the multitargeted single project model, we should surface the option in the Blazor Web App template to enable WebAssembly interactivity.

**Comment by danroth27** [comment]
Surfacing the Server interactivity option is tracked by https://github.com/dotnet/aspnetcore/issues/48626.

**Comment by danroth27** [comment]
@mkArtakMSFT Now that we've decide to not go with a multitargeting approach for .NET 8, this is no longer blocked, correct?

**Comment by surayya-MS** [comment]
This is done with https://github.com/dotnet/aspnetcore/pull/49801
