### ISSUE TITLE
In blazor SSR, when setting @attribute [RenderModeServer], cascading parameter Task<AuthenticationState> always is null

### ISSUE THREAD

**Issue by germansak** [dotnet/aspnetcore#48927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wanted to try the new Blazor SSR template with authentication, so I created a new project with blazorserver (with auth and 
 individual accounts) and modified it with settings and code from a blazor (SSR, the new template from net8) and created this component from MS docs

```csharp
@page "/AuthStatus"
@attribute [RenderModeServer]

<h3>AuthStatus</h3>
<p>@authMessage</p>

@code {
    private string authMessage = "The user is NOT authenticated.";

    [CascadingParameter]
    private Task<AuthenticationState>? authenticationState { get; set; }

    protected override async Task OnInitializedAsync()
    {
        if (authenticationState is not null)
        {
            var authState = await authenticationState;
            var user = authState?.User;

            if (user?.Identity is not null && user.Identity.IsAuthenticated)
            {
                authMessage = $"{user.Identity.Name} is authenticated.";
            }
        }
        else
        {
            authMessage = "authenticationState is null";
        }
    }
}

```

this returns always "authenticationState is null" unless I comment the line with RenderModeServer

I know this is a work in progress, but is this by design? 

Thanks
German

### Expected Behavior

I should be able to access authenticationState so I can handle logic using logged user?

### .NET Version

8.0.100-preview.5.23303.2

**Comment by SteveSandersonMS** [comment]
An initial idea for how to handle this is related to something I was considering we should add anyway to simplify form handling. 

If it was possible to configure in code a set of cascading values that would be exposed at the root level by the renderer, this could be an alternative way to register "cascading authentication state" that would work in this case, as well as any other scenario where the framework or applications want root-level cascading values that have to be available even when you're not rendering the `App` component.

Another way to think of this is that it would be like middleware. In `Program.cs`, you would be able to attach a set of cascaded values, like you can attach a set of ASP.NET Core request-handling pipeline steps, and the framework might have some built-in ones.

If we were able to turn on the cascading authentication state value by default, it would then be back-compatible even for people who have `<CascadingAuthenticationState>` (as that would become a no-op).

**Comment by germansak** [comment]
What I've found is that this happens because of the double execution of methods. So, for example, when I reload the page, the first execution brings _authenticationState_ ok, but on the second execution it is null.

The other thing I noticed is that when I put `<CascadingAuthenticationState>` on `App.razor` it doesn't work, but if I put it on the page (with _@attribute [RenderModeServer]_), then it works.

Like this:
```
@page "/sampleauthorizeview"
@attribute [RenderModeServer]

<PageTitle>SampleAuthorizeView</PageTitle>

    <CascadingAuthenticationState>
        <AuthorizeView>
            <Authorized>
                <div>Logged user: <strong>@context.User.Identity?.Name</strong></div>
            </Authorized>
        </AuthorizeView>
    </CascadingAuthenticationState>

</div>
```

this page works as expected.

The other thing that worked was injecting `AuthenticationStateProvider` as any other service

```
@page "/AuthState"
@attribute [RenderModeServer]
@inject AuthenticationStateProvider authInjected

<p>AuthState injected: @authInjectedMessage</p>

@code {
    private string authInjectedMessage = "The user is NOT authenticated.";

    protected override async Task OnInitializedAsync()
    {
        if(authInjected is not null)
        {
            var aiState = await authInjected.GetAuthenticationStateAsync();
            var aiUser = aiState.User;
            if (aiUser is not null)
            {
                authInjectedMessage = $"User {aiUser.Identity.Name} is logged in";
            }
            else
            {
                authInjectedMessage = "authInjected IS NULL";
            }

        }
    }
}
```

I've made other tests, but the relevant ones are this. If you need more information or any other test, I gladly upload them to github or where you need them.

Thanks and sorry for my english.

**Comment by SteveSandersonMS** [comment]
Thanks @germansak - that all makes sense and matches with what I'd expect.

**Comment by SteveSandersonMS** [comment]
Addressed in https://github.com/dotnet/aspnetcore/pull/49204, via the new `services.AddCascadingAuthenticationState` API.

**Comment by germansak** [comment]
Excelent! I'll definitely give it a try. Thank you!
