### ISSUE TITLE
Implicit binding of parameters from DI services is not working with RDG

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#48928]
In latest SDK builds, implicit binding of parameters to request handlers (minimal APIs) when using the Request Delegate Generator (RDG), e.g. with `<PublishAot>true</PublishAot>`, doesn't seem to be working. Parameters typed for services in DI are attempted to be deserialized at runtime, resulting in an exception about missing `JsonTypeInfo` metadata.

Workaround is to decorate parameters with `[FromServices]` explicitly.

**Comment by DamianEdwards** [comment]
FYI @captainsafia @mitchdenny

**Comment by mitchdenny** [comment]
Will take a look.
