### ISSUE TITLE
Microsoft.AspNetCore.Mvc is getting depreciated but what would be workaround?

### ISSUE THREAD

**Issue by bhrugen** [dotnet/aspnetcore#48920]
### Description
I am trying to use [ValidateNever] attribute but it is in package Microsoft.AspNetCore.Mvc which is depreciated.

So what should we rather use?

I do not see anything on what should we use for ValidateNever

**Comment by captainsafia** [comment]
@bhrugen What version of the runtime are you currently using? The `Microsoft.AspNetCore.Mvc` _packages_ are deprecated now that APIs are published in the shared framework.

**Comment by bhrugen** [comment]
@captainsafia so i am using .NET 8 preview 5 but i have entities in a separate class library project where i am storing all the Models for Entity framework core. Because of that in the class project if i want to use [validatenever] how would i do that if that will only be available in the shared framework?

Please let me know if I am not making myself clear.

**Comment by martincostello** [comment]
You should reference the shared framework [as documented here](https://learn.microsoft.comaspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework) in your library project(s) instead. The individual packages have not been shipped to NuGet.org since .NET Core 3.0.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
```

**Comment by bhrugen** [comment]
thank you!
