### ISSUE TITLE
macOS uses port 5000

### ISSUE THREAD

**Issue by richlander** [dotnet/aspnetcore#48932]
A user reported to me that he couldn't use ASP.NET Core while also using AirPlay.

Context: https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/

**Comment by mitchdenny** [comment]
Is it worth changing our default here across the board to reduce friction on macOS.

**Comment by Tratcher** [comment]
It's pretty easy for a developer to change which port Kestrel is using.
https://github.com/dotnet/aspnetcore/blob/e1c4295531b5529aa1462ae5ea620f04a099f54d/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Properties/launchSettings.json#L25

I thought we were going to start randomizing the ports in the launchSettings.json when a project was created?

**Comment by coolcsh** [comment]
https://github.com/dotnet/aspnetcore/issues/48932

**Comment by Tratcher** [comment]
https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel/endpoints
> ASP.NET Core projects are configured to bind to a random HTTP port between 5000-5300 and a random HTTPS port between 7000-7300. This default configuration is specified in the generated Properties/launchSettings.json file and can be overridden. If no ports are specified, Kestrel binds to http://localhost:5000.

**Comment by mitchdenny** [comment]
Yeah I think the only time this will come up is if someone takes the build output without the config file and runs it. Probably not going to be a super common scenario. @richlander how did the person that ran into problems launch their app?

**Comment by coolcsh** [comment]
Ends up that ASP.NET in older versions defaults to 5001, @bradygaster subtracted 1 for his backend which is how he ended up on 5000 which does not work on a Mac. So I think we are good here.
