### ISSUE TITLE
Misleading documentation for UseBlazorFrameworkFiles("path")

### ISSUE THREAD

**Issue by POnakS** [dotnet/aspnetcore#48950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `UseBlazorFrameworkFiles(path)`, it does not configure hosting properly, blazor.webassembly.js is not served from `path`. It expectes wasm app to use `StaticWebAssetBasePath`.

There is additional dependency on basePath (i.e. blazor.boot.json and javascript initializers are loaded from basePath + `/_framework/blazor.boot.json`).

### Expected Behavior

After calling `app.UseBlazorFrameworkFiles(path)` following document can be resolved: `path/_framework/blazor.webassembly.js` (but this probably breaks lots of things) OR documentation is updated that `StaticWebAssetBasePath` needs to be configured in csproj file.

### Steps To Reproduce

https://github.com/POnakS/blazor-webassembly-repro

1. Create new aspnet core hosted blazor wasm app
2. In server's `Program.cs` change `app.UseBlazorFrameworkFiles();` to `app.UseBlazorFrameworkFiles("/my-product");`
3. In client's index.html change `<script src="_framework/blazor.webassembly.js"></script>` to `<script src="my-product/_framework/blazor.webassembly.js"></script>`
4. Start server application
5. Open developer tools and observe 404 error

### .NET Version

7.0.202

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Looks like you've forgot to set the basebath in the index.html: https://github.com/POnakS/blazor-webassembly-repro/blob/99a81966ebe5a6b0e8002efeac28df59d50d9c11/BlazorApp1/Client/wwwroot/index.html#LL8C4-L8C22
Here are the docs on how to configure this and why it matters: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#configure-the-app-base-path

**Comment by POnakS** [comment]
Hi @mkArtakMSFT, thanks for reply.

I've modified path to script instead of base url, so effect should be the same as updating base. Anyway I've updated repro and effect is the same.

This is backend issue, file is not configured to be served from /my-product. Even if I directly type into browser `https://localhost:7000/my-product/_framework/blazor.webassembly.js` it will fail because backend is configured to serve this file from `https://localhost:7000/_framework/blazor.webassembly.js`.

Take a look at screenshot from published application:
![image](https://github.com/dotnet/aspnetcore/assets/90155580/234a63cb-f881-4258-a418-52fb9f09fec9)
_framework directory sits directly in wwwroot. 

I need to configure `<StaticWebAssetBasePath>MyProduct</StaticWebAssetBasePath>` , so all files are moved into `/my-product` directory, then `blazor.webassembly.js` will be loaded.

**Comment by mkArtakMSFT** [comment]
@POnakS just to be clear did you not update the `<basepath>` tag in index.html?

**Comment by MackinnonBuck** [comment]
@POnakS Could you please clarify which documentation is misleading?

Our docs for configuring the base path on a WebAssembly hosted app can be found here: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#hosted-blazor-webassembly. It does explicitly state the need to specify a `<StaticWebAssetBasePath>`. Is there something else you think should be called out here?

Or are you referring to the inline XML documentation for the `UseBlazorFrameworkFiles(PathString pathPrefix)` method?
