### ISSUE TITLE
Give error if a component is rendermode boundary and has parameter of type RenderFragment or RenderFragment<T>

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#48968]
If a component is a rendermode boundary, we have to serialize its parameters.

 * We would like to support `RenderFragment` by prerendering it and supplying static content. But until that's implemented, we should give a clear error.
 * We don't expect ever to support `RenderFragment<T>` because it doesn't make sense - it would imply an interactive recipient can call back into the SSR renderer to evaluate a fragment for arbitrary interactive runtime values, but SSR has already finished.

We should give clear errors because the Razor syntax makes it look a *lot* like you can put a rendermode wherever you want, and people won't easily understand why it's invalid to do:

```razor
<SomeComponent>
    Hello @context!
</SomeComponent>
```

... if `SomeComponent` is on the other side of a rendermode boundary.

Note that we can only apply this rule at runtime, not at compile time. At compile time, we don't know whether a given component will be exactly at a rendermode *boundary* as opposed to just having a rendermode (which is fine).

**Comment by SteveSandersonMS** [comment]
Note that, as a special case, this explains why it would not make sense to do:

```
<Router @rendermode="RenderMode.Server">
    <FoundContent Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </FoundContent>
</Router>
```

... even though it feels desirable.

**Comment by SteveSandersonMS** [comment]
This is implemented now - see `SSRRenderModeBoundary.cs`.

**Comment by danroth27** [comment]
> We would like to support RenderFragment by prerendering it and supplying static content. But until that's implemented, we should give a clear error.

This work is tracked by #46991
