### ISSUE TITLE
NTLM Support in Linux Containers

### ISSUE THREAD

**Issue by DovydasAL** [dotnet/aspnetcore#48971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am currently running an Ubuntu Container with .NET 6. In my attempts to get Windows Authentication working, I have managed to get everything setup for Kerberos Authentication using a custom authentication handler. However, I am still unable to directly support clients using NTLM instead of Kerberos.

I have recently started looking into using https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.negotiate?view=aspnetcore-7.0

Kerberos authentication seems to work with this package as well, but NTLM is not functional. As per the documentation [here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio#kerberos-vs-ntlm), I should be able to use NTLM if a client provides NTLM credentials.

### Describe the solution you'd like

When using the package above, NTLM should be supported out of the box.

### Additional context

One additional thing to add is that NTLM tokens should be sent with the Negotiate prefix according to the documentation. To ensure that all NTLM requests are sent properly, I have a middleware component to convert NTLM <token> to Negotiate <token> in the authorization header. With this in place, I see a message of "Inccomplete Negotiate handshake, sending an additional 401 negotiate challenge"

EDIT:

I have managed to get some sort of flow working with NTLM using that package. But I am now seeing a GSS failure: Feature not available.

**Comment by halter73** [comment]
> I have managed to get some sort of flow working with NTLM using that package. But I am now seeing a GSS failure: Feature not available.

Where is "GSS failure: Feature not available." coming from? Do you have ASP.NET Core logging available? For this type of debugging, I recommend using the Trace or Debug log levels for both "Microsoft.AspNetCore" and "Default" categories.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#configure-logging

**Comment by DovydasAL** [comment]
> > I have managed to get some sort of flow working with NTLM using that package. But I am now seeing a GSS failure: Feature not available.
> 
> Where is "GSS failure: Feature not available." coming from? Do you have ASP.NET Core logging available? For this type of debugging, I recommend using the Trace or Debug log levels for both "Microsoft.AspNetCore" and "Default" categories.
> 
> https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#configure-logging

I'm a bit unsure what you mean by where this error is coming from. The originating class is the Microsoft.AspNetCore.Authentication.Negotiate.NeogitateHandler in the HandleRequestAsync method. This is with Trace enabled for both log settings you mentioned
