### ISSUE TITLE
Make `ComponentState` methods `public`

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/aspnetcore#48980]
## Background and Motivation

Since .NET 8 the [`ComponentState`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Rendering/ComponentState.cs) class is `public` but many of the functions are "still" internal. Imagine you have a custom Blazor Renderer that derives from the [`Renderer`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs), you might run into situations where you want to set parameters of a Blazor component. The `ComponentState` itself has the following comment:
```csharp
// Note: We should be careful to ensure that the framework never calls
// IComponent.SetParametersAsync directly elsewhere. We should only call it
// via ComponentState.SetDirectParameters (or NotifyCascadingValueChanged below).
// If we bypass this, the component won't receive the cascading parameters nor
// will it update its snapshot of direct parameters.
```

Hinting towards the fact that anyone that wants to call `SetParametersAsync` of a component should do this via the `SetDirectParameters` method. That is somewhat possible with .NET 8, as the `Renderer` exposes `GetComponentState` method.

## Proposed API

For libraries, like `bUnit`, it would be very helpful to have such methods `public`.

```diff
- internal void SetDirectParameters(ParameterView parameters)
+ public void SetDirectParameters(ParameterView parameters)
}
```

## Usage Examples

-

## Alternative Designs

-

## Risks

From an user's point of view, that does not interact directly with the `Renderer`, nothing really changes. The change would make it easier for library maintainers.

**Comment by egil** [comment]
A more high-level alternative that could be more relevant is to expose a method directly on the `Renderer` type (protected or public) that allows setting parameters directly on a component, based on a component id and a ParameterView.

Currently, in bUnit, we are considering adding the following method to our Renderer, but it does depend on reflection, which is not ideal.

```c#
internal void SetDirectParameters(int componentId, ParameterView parameters)
{
	var isBatchInProgressField = RendererType.GetField("_isBatchInProgress", BindingFlags.Instance | BindingFlags.NonPublic);
	var getRequiredComponentStateMethod = RendererType.GetMethod("GetRequiredComponentState", BindingFlags.Instance | BindingFlags.NonPublic);

	isBatchInProgressField.SetValue(this, true);
	var componentState = getRequiredComponentStateMethod.Invoke(this, new object[] { componentId });
	var setDirectParametersMethod = componentState.GetType().GetMethod("SetDirectParameters", BindingFlags.Public | BindingFlags.Instance);

	try
	{
		setDirectParametersMethod.Invoke(componentState, new object[] { parameters });
	}
	catch (TargetInvocationException ex)
	{
		throw ex.InnerException;
	}

	isBatchInProgressField.SetValue(this, false);

	ProcessPendingRender();

	AssertNoUnhandledExceptions();
}
```

We toggle the `_isBatchInProgress` field in the Renderer because we want to emulate the rendering behavior that happens when a parent component passes new parameters to a child component. In our case, however, it is the test user that is passing in new parameters to a component, and calling the component's public `SetParametersAsync` method directly does not exhibit this behavior, and as @linkdotnet points out, there are comments that indicate that is not the right approach either.

**Comment by javiercn** [comment]
@linkdotnet while it might be useful for some libraries, exposing the guts greatly limit us in terms of making changes to how the renderer works. It's not something that I am keen on us doing unless we really, really, really, have a good reason for.

The more we expose from the renderer, the more constrained we are in the future to implement features.

**Comment by linkdotnet** [comment]
@javiercn I do understand the reasoning to some extend. In .NET 8 the ConponentState was made public - but it is not really useful for 3rd party libraries in the current state. So it is in a weird state where the container is public but can’t really be used.

EF Core has also some public APIs that is somewhat internal and are subject to regular change. The same could apply here. Many types in Blazor evolved over time.

**Comment by javiercn** [comment]
@linkdotnet it's public just as an artifact of layering, but we do not intend to make it useable outside of the framework.

**Comment by linkdotnet** [comment]
That is very unfortunate as it makes it difficult for 3rd party libraries to somewhat have the same behavior as Blazor itself. 
Thanks for the explanation @javiercn 

If this is a set decision, we can close the ticket from my side.

**Comment by egil** [comment]
@javiercn iff the expectation from the Blazor renderer/core libraries in .NET 8 is that `IComponent.SetParametersAsync` should not be called directly (anymore?), then libraries like bUnit really needs an alternative.

My proposed method in the comment above would also be even better in our scenario.

If calling `IComponent.SetParametersAsync` is allowed under some circumstances, it would be great if we can get a do's and dont's regarding that.

**Comment by javiercn** [comment]
@egil if you are referring to the comment above, that has been the case since the initial Blazor release, it's nothing new made possible by this API.

**Comment by egil** [comment]
I see, we have been doing that up until now in bUnit, but there are definitely edge cases we are fighting on this.

Should I create a separate issue with my suggestion for a `protected void SetDirectParameters(int componentId, ParameterView parameters)` method on `Renderer`?

**Comment by javiercn** [comment]
@egil that would be best, with sample scenarios so that we can understand the context.
