### ISSUE TITLE
Blazor: IJSObjectReference does not seem to support js min files?

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#49003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sorry in advance if this has already been reported or if it is just not supported. It seems IJSObjectReference cannot fetch js min files or I have just not configured something correctly. I added some sample code below. If I target my non-minified js file all seems fine. If I target the min file, I get the error:

`Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7100/Pages/Index.razor.min.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7100/Pages/Index.razor.min.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorwebAppJsTest.Pages.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\charl\source\repos\BlazorJsTest\BlazorwebAppJsTest\Pages\Index.razor:line 28
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

I did check that the min file is on disk, and it is.

If not supported this would be very nice to have if possible.

### Expected Behavior

I would hope the min file would be picked up just like the un-minified file.

### Steps To Reproduce

Setup a .net 8 Blazor Web Project (new with dotnet 8)

### _**Program.cs**_

```c#
using BlazorwebAppJsTest;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
        .AddServerComponents(options => {
            options.DetailedErrors = true;
        }); ;

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.MapRazorComponents<App>();

app.Run();
```

### _**Index.razor**_

```c#
@page "/"

@inject IJSRuntime JsRuntime

@attribute [RenderModeServer]

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@code{

    private IJSObjectReference _module = null!;
    private IJSObjectReference _objectInstance = null!;

    protected override Task OnInitializedAsync()
    {
        return base.OnInitializedAsync();
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if(firstRender)
        {
            _module = await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./Pages/Index.razor.min.js");

            //_objectInstance = await _module.InvokeAsync<IJSObjectReference>("factoryCall");
            //await _objectInstance.InvokeAsync<object>("alertMe");

            await _module.InvokeAsync<object>("alertMe");
        }
    }
}
```

### _**Index.razor.js**_

```ts
//export function factoryCall() {
//    return new objInstance();
//};

//export function objInstance() {

//    this.alertMe = function () {

//        alert("Alert Me");
//    };

//};

export function alertMe() {
    alert("Alert Me");
};
```

### _**Index.razor.min.js**_

```ts
export function alertMe(){alert("Alert Me")}`
```

### Exceptions (if any)

```
blazor.web.js:1  [2023-06-24T11:14:56.087Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7100/Pages/Index.razor.min.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7100/Pages/Index.razor.min.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorwebAppJsTest.Pages.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\charl\source\repos\BlazorJsTest\BlazorwebAppJsTest\Pages\Index.razor:line 28
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### .NET Version

8 

### Anything else?

Windows 11 (latest patches) 

Microsoft Visual Studio Enterprise 2022
Version 17.7.0 Preview 2.0
VisualStudio.17.Preview/17.7.0-pre.2.0+33808.371
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA741
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.160.18752
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.160.18752
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.160.18752
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.9.9
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   4.7.0-2.23280.4+66772aff549b2981094175a6f2f69600596c1913
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.33 (main@eea8cc7)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.20 (81efaa2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.2.2330502+e0cf0b1121019f24d79b73d6d30f5870ca83c81d
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.1.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20531.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-2.23280.4+66772aff549b2981094175a6f2f69600596c1913
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23272.3+96bfa24a5fee6722ed3e2b280d37e80b594bbcf4
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.135 (main@f75253e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.2.4 (remotes/origin/d17-7@105126fbf4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.17 (95eb8d3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.13 (d17-5/3f21639)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 73df89a
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.5 (191fe02ea)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by chassq** [comment]
Can this be explained as to why this has to wait? Is there some complexity to using min files not mentioned above so as we could better understand this?

**Comment by KristofferStrube** [comment]
Hey @chassq just wanted to return to you to make it clear that there has yet to be moved on this issue as it is not a currently supported feature. You can read about what is supported on this page in the Docs: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component

I guess the `Docs` label has been added to clarify that it is not supported.

Another clarification is that it is possible to use JSInterop to import minified JS files. The thing that is not supported is to have files that end with `.min.js` automatically added to the published resources. If you wish to learn more about this, you can search for "Blazor Javascript Isolation" (a parallel to CSS Isolation).

To include a minified JS file in general through import, you must move your minified file to the `wwwroot/` folder and then point the import argument to that address. In your case, you could rename the minified script to `ìndex.min.js`, move it to `wwwroot/js/`, and then import it with the following method invocation:
```csharp
_module = await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./js/index.min.js");
```

**Comment by chassq** [comment]
Thank you for the reply! That helps.
