### ISSUE TITLE
Blazor Inheritance Not Working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#49008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a simple repository where I have a base class and have an inherited class.
When I use the inherited class, the screen shows as blank.

### Expected Behavior

What should happen is show the text "Improved Display"

### Steps To Reproduce

The project is here.
https://github.com/musictopia2/InheritancePossibleProblem 

When you run it, you will see its blank.
There are many cases where inheritance is required.  Especially with generic components.

Can have a case where the base case uses the generic but then a component will use inherit and do the generic part.

### Exceptions (if any)

There are no runtime errors.  Instead of a runtime error, it shows blank screen.

### .NET Version

7

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

You don't have `@page` in your components. We have automation covering this area, so this is likely a bug in your app.

**Comment by musictopia2** [comment]
This is intended to be a component and not a page though.
When I did not use inheritance and used the component, then no problem.

**Comment by musictopia2** [comment]
There was no errors either.  Just blank screen.
