### ISSUE TITLE
Issue with Parameter Transformers in combination with Area Routing in ASP.NET Core MVC

### ISSUE THREAD

**Issue by jzs11** [dotnet/aspnetcore#49041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I encountered an issue with the parameter transformers when used in combination with Area Routing in ASP.NET Core MVC. The specific scenario is as follows:

I have configured the parameter transformer using the following code:
```
builder.Services.AddRouting(options =>
{
   options.ConstraintMap["slugify"] = typeof(SlugifyParameterTransformer);
   options.LowercaseUrls = true;
});
```

And I have set up a controller route using the app.MapControllerRoute method with the following parameters:
```
app.MapControllerRoute(
   name: "area",
   pattern: "{area:slugify}/{controller:slugify}/{action=Index}/{id?}");
```

The controller code looks like:
```
using Microsoft.AspNetCore.Mvc;

namespace Eshop.Controllers;

[Area("ABC")]
public class MoneyMarketController : Controller
{
   public ActionResult Index()
   {
      return View();
   }
}
```

### Expected Behavior

I expected to be able to navigate to the MoneyMarketController located in the "ABC" area using the following link
**abc/money-market**

### Steps To Reproduce

Here is the repo to reproduce this problem:
https://github.com/jzs11/Eshop.git

### .NET Version

7.0.304

**Comment by captainsafia** [comment]
@jzs11 How are you constructing the link to your area? You should be able to construct something via link generation by using the `ActionLink` helper documented [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-7.0#link-generation-with-mvc-areas) like so:

```razor
<li class="nav-item">
    @Html.ActionLink("Money Market", "Index", "MoneyMarket", new { area = "ABC" })
</li>
```

**Comment by jzs11** [comment]
> @jzs11 How are you constructing the link to your area? You should be able to construct something via link generation by using the `ActionLink` helper documented [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-7.0#link-generation-with-mvc-areas) like so:
> 
> ```
> <li class="nav-item">
>     @Html.ActionLink("Money Market", "Index", "MoneyMarket", new { area = "ABC" })
> </li>
> ```

@captainsafia with the code you provide it will generate the following link
`<a href="/MoneyMarket?area=ABC">Money Market</a>`

After clicking on that page, it won't navigate to the moneymarket page :( 
https://localhost:7090/MoneyMarket?area=ABC

Also, I am expecting the link should be like the following.
https://localhost:7090/ABC/MoneyMarket

**Comment by jzs11** [comment]
> @jzs11 How are you constructing the link to your area? You should be able to construct something via link generation by using the `ActionLink` helper documented [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-7.0#link-generation-with-mvc-areas) like so:
> 
> ```
> <li class="nav-item">
>     @Html.ActionLink("Money Market", "Index", "MoneyMarket", new { area = "ABC" })
> </li>
> ```

It seems to work fine.
![image](https://github.com/dotnet/aspnetcore/assets/2770401/b136f612-419a-408a-85b1-9da190b35fe0)

Another question, is there a way I can access the page via the original controller's name like the following?
https://localhost:7191/abc/moneymarket

**Comment by captainsafia** [comment]
@jzs11 I suppose you could map another route that doesn't slugify the controller name?

```csharp
app.MapControllerRoute(
            name: "ABC-no-slug",
            pattern: "{area:slugify}/{controller}/{action=Index}");
```

**Comment by jzs11** [comment]
I must make some mistakes while constructing the link. 

Thanks @captainsafia !! Thanks for your help!
