### ISSUE TITLE
Multiple API template entry points should be reconciled

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#49047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the VS new project dialog there is now multiple 'API' template options.  The descriptions do not disambiguate enough IMO of what they are and the one with a more complete description and tags seems to be the one I want and not the new one from .NET 8 SDK.  These should be reconciled with better descriptions:

![image](https://github.com/dotnet/aspnetcore/assets/4821/ee8ad46d-5f65-42fa-9e3e-b683f2e59bee)

Similarly:
![image](https://github.com/dotnet/aspnetcore/assets/4821/478fc0b4-4711-490e-a591-dc06d50a24bc)

### Expected Behavior

Better descriptions between the two and proper ordering to where you want them positioned in the dialog/search.

### Steps To Reproduce

1) Install latest .NET 8 SDK in an installation of VS
2) File...New Project

**Comment by davidfowl** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Let's update the descriptions to better reflect the goals of these templates moving forward. @JeremyLikness we should agree on how we want to position these (i.e. wording and literal position in the VS dialog).

**Comment by JeremyLikness** [comment]
> @JeremyLikness we should agree on how we want to position these (i.e. wording and literal position in the VS dialog).

Ack.
