### ISSUE TITLE
[Blazor] Remove `suppress-error` from script

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/aspnetcore#49053]
Remove suppress-error from https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/Components-CSharp/App.razor#L52

- [ ] https://github.com/dotnet/razor/pull/8743

**Comment by danroth27** [comment]
[Remove blazor script check - dotnet/razor#8744](https://github.com/dotnet/razor/pull/8743)

**Comment by danroth27** [comment]
@mkArtakMSFT I believe this is now unblocked, correct?
