### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.DevServer 7.0.8 introduces error

### ISSUE THREAD

**Issue by Sean4572435243** [dotnet/aspnetcore#49064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upgrading NuGet package for Microsoft.AspNetCore.Components.WebAssembly.DevServer from 7.0.7 to 7.0.8 introduces bug when attempting to debug Blazor app, preventing the app from starting

"Web server failed to listen on port 7083"

Code was executing correctly on version 7.0.7.  All other nuget packages are updated to the latest versions

### Expected Behavior

App should start.

### Steps To Reproduce

All I did was upgrade to 7.0.8 from 7.0.7 and then attempted to debug my Blazor project that was working fine in 7.0.7

### Exceptions (if any)

"Web server failed to listen on port 7083"

### .NET Version

7.0.304

### Anything else?

ASPNetCore.Components.Web and .WebAssembly are 7.0.8.  Regressing to 7.0.7 is a workaround (which I was able to easily accomplish because I snapshotted my VM prior to the update and just reverted).  Downversioning from 7.0.8 to 7.0.7 apparently doesn't work.

**Comment by danieldsmith** [comment]
I hit this issue as well when updating from 7.0.7 to 7.0.8.  Does the 7.0.8 NuGet package make global changes?  I suspect it might because it broke all my other projects in totally separate solutions.  I ended up having to do a Visual Studio repair to fix it.

**Comment by SimonJWales** [comment]
Same problem. Though I get Process with an id of xxxxx is not running, Alert box.

**Comment by dev-jlb** [comment]
Same issue here w/ "process with an ID of xxxx is not running" in an alert box.  Confirmed issue starts in 7.0.8.  Present in 7.0.10.  We are not able to upgrade to .NET 7 w/ Blazor because of very slow debugger performance (#88602), and cannot test the fix provided until this issue is resolved.  Are there workarounds for this?

**Comment by dev-jlb** [comment]
FWIW, I had the "process with an id of xxxx is not running" when I tried to update to 7.0.8 (or 7.0.10).  I updated Visual Studio to the latest version and that resolved the issue.

**Comment by mkArtakMSFT** [comment]
@Sean4572435243 can you try to update to the latest VS version and see if it resolves your issue? Thanks!

**Comment by Sean4572435243** [comment]
Updating to 7.0.10 worked.  Thank you!
