### ISSUE TITLE
HTTPS certificate exact match using Issuer's SimpleName instead of Certificate's

### ISSUE THREAD

**Issue by dan-olsen** [dotnet/aspnetcore#49062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have 2 certificates `NAME` and `NAMEB` (actual cert names changed for obvious reasons). I am trying to configure Kestrel to use the `NAMEB` cert but the `NAME` cert is always being chosen. These certs are not self-signed.

As part of #34582 the `Microsoft.AspNetCore.Server.Kestrel.Https.CertificateLoader` was changed to support exact subject name match but it appears the certificate's issuer SimpleName is being used instead of the certificate's SimpleName. The `certificate.GetNameInfo(X509NameType.SimpleName, true)` should be `certificate.GetNameInfo(X509NameType.SimpleName, false)`

It should be noted that the `NAME` cert expires after the `NAMEB` cert which is why it is being chosen as the the first found cert.

### Expected Behavior

I would expect the exact match logic to work and the `NAME` cert is chosen.

### Steps To Reproduce

Kestrel config:
```
"Kestrel": {
    "Endpoints": {
      "HttpsInlineCertStore": {
        "Url": "https://NAME:7286",
        "Certificate": {
          "Subject": "NAME",
          "Store": "MY",
          "Location": "LocalMachine"
        }
      }
    }
  }
```

With the following 2 certs in the cert store:
* `NAME`
    * Expires after `NAMEB` 
* `NAMEB`

### .NET Version

7.0.304

**Comment by simon-curtis** [comment]
We've just descovered this issue too. After digging through the code. It appears as though they:

1. Do a partial string match on all certificates in that store, this will enumerate `NAME` and `NAMEB` like you have described. 

```c#
foreach (var certificate in storeCertificates.Find(X509FindType.FindBySubjectName, subject, !allowInvalid)...)
```

2. They order by expiry date and then set the first one as the fallback value, in case an exact subject name is not matched.

```c#
[].OrderByDescending(certificate => certificate.NotAfter)
```

3. _This is the failure_ they then attempt to check an exact match against the subject name, except they have accidentally match on the issuer name using `certificate.GetNameInfo(X509NameType.SimpleName, true)`. 

```c#
if (certificate.GetNameInfo(X509NameType.SimpleName, true).Equals(subject, StringComparison.InvariantCultureIgnoreCase))
{
    foundCertificate = certificate;
    break;
}
```

This means that it will never exact match the subject name and return the first in the list.

I will create a pull request and hopefully they can pull it in quickly.

For now, create a copy of [https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/CertificateLoader.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/CertificateLoader.cs) and modify it to your needs and use `builder.WebHost.ConfigureKestrel(...)` to configure the certificate yourself:

```c#
using System.Security.Cryptography.X509Certificates;

builder.WebHost.ConfigureKestrel(options =>
{
    if (builder.Configuration.GetSection("Kestrel").Get<KestrelOptions>() is
        { Endpoints.Https: { Url: { } url, Certificate: { } cert } })
    {
        options.ListenAnyIP(url.Port, listenOptions =>
        {
            var (subject, store, location, allowInvalid) = cert;
            var certificate = CertificateLoader.LoadFromStoreCert(subject, store.ToString(), location, allowInvalid);
            listenOptions.UseHttps(certificate);
        });
    }
});

[Serializable]
public record KestrelOptions(EndpointsOptions Endpoints);

[Serializable]
public record EndpointsOptions(HttpsOptions Https);

[Serializable]
public record HttpsOptions(Uri Url, CertificateOptions Certificate);

[Serializable]
public record CertificateOptions(string Subject, StoreName Store, StoreLocation Location, bool AllowInvalid = false);
```
