### ISSUE TITLE
Minimal API with authorization policy throws 'Unable to find the required 'IAuthenticationService' service' when policy fails

### ISSUE THREAD

**Issue by Snijderman** [dotnet/aspnetcore#49073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To be honest, probably it's me missing something and this not being a bug, but I don't understand the following behavior:

I've setup a very simple minimal API, that can be accessed anonymously, but requires a value in a header to make sure only services that know how to call it will get some response.
For this, I added an authorization policy, based on the default 'ASP..NET Core Web API'-template, it looks something like this

```
      var builder = WebApplication.CreateBuilder(args);

      // Add services to the container.
      // add authorization policy
      builder.Services.AddAuthorization(options =>
      {
         options.AddPolicy(Constants.RequireApiHeaderPolicyKey, policy =>
         {
            policy.RequireHeader(Constants.ApiHeaderKey);
         });
      });


      var app = builder.Build();

      // Configure the HTTP request pipeline.

      app.UseHttpsRedirection();

      app.UseAuthorization();

      var summaries = new[]
      {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

      app.MapGet("/weatherforecast", (HttpContext httpContext) =>
      {
         var forecast = Enumerable.Range(1, 5).Select(index =>
               new WeatherForecast
              {
                 Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                 TemperatureC = Random.Shared.Next(-20, 55),
                 Summary = summaries[Random.Shared.Next(summaries.Length)]
              })
               .ToArray();
         return forecast;
      }).RequireAuthorization(Constants.RequireApiHeaderPolicyKey);

      app.Run();

```

This all works OK as long as the policy succeeds, but as soon as it fails, this error is returned (status 500):

```
System.InvalidOperationException: Unable to find the required 'IAuthenticationService' service. Please add all the required services by calling 'IServiceCollection.AddAuthentication' in the application startup code.
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.GetAuthenticationService(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.ChallengeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

I would expect to get an unauthorized status or something like that, indicating the request is rejected, instead of a 500.

Also I wouldn't expect the need to add authentication, since a successful policy validation makes the request work like a charm.
If it was as simple as adding 

`builder.Services.AddAuthentication();`
and
`app.UseAuthentication();`

that still would not be my preferred way, but doing that causes other issues, like having to specify a schema, something that's not needed for this simple API.

### Steps To Reproduce

Repo to reproduce this issue: https://github.com/Snijderman/ReproAuthorizationIssue

### .NET Version

7.0.304

**Comment by halter73** [comment]
> Also I wouldn't expect the need to add authentication, since a successful policy validation makes the request work like a charm.
If it was as simple as adding

If you want to use the authorization middleware, you must use an authentication handler.

> Authorization is orthogonal and independent from authentication. However, authorization requires an authentication mechanism. Authentication is the process of ascertaining who a user is. Authentication may create one or more identities for the current user.

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-7.0

Simply requiring `Constants.ApiHeaderKey` header to be defined as shown in the example `AddPolicy` callback sounds crazy insecure. Even if it was doing something more secure, the job of determining whether the request is authenticated belongs in an authentication handler, not an authorization policy.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-7.0

> that still would not be my preferred way, but doing that causes other issues, like having to specify a schema, something that's not needed for this simple API.

You don't have to specify an authentication schema if you only have one, but you need at least one authentication scheme. Something like cookies, JwtBearer, Basic auth, etc... It could even be a custom scheme that adds a custom authentication handler that just checks for the presence of a certain header, but I wouldn't recommend it.

> Starting in ASP.NET Core 7.0, if (and only if) a single scheme is registered in an application, that scheme is treated as the default.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/default-authentication-scheme#new-behavior

**Comment by Snijderman** [comment]
Hi Stephen,

Thanks for your reply 👍🏼

IRL, this API is meant to be anonymous, so I would like to skip the authentication part, since it's not really needed.
The check on the authentication header is solely to make (more) sure that we only process calls from services that at least know they have to provide a certain header.

I thought this perhaps would be a bug, since processing is working fine when the middleware check is successful, it only crashes when it doesn't succeed.
But if you say this is the expected way of working, then who am I to disagree 😊
