### ISSUE TITLE
Test failure: CacheTagHelper_AllowsVaryingByUICulture and CacheTagHelper_VaryByCultureComposesWithOtherVaryByOptions

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#4907]
This test [fails](http://aspnetci/viewLog.html?buildId=532556&buildTypeId=Releases_22xPublic_OsxUniverse) occasionally with the following error:
```
Assert.Equal() Failure
           ↓ (pos 1)
Expected: 10
Actual:   14
           ↑ (pos 1)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationWithCultureTest.CacheTagHelper_VaryByCultureComposesWithOtherVaryByOptions() in /_/test/Microsoft.AspNetCore.Mvc.FunctionalTests/HtmlGenerationWithCultureTest.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, is this test still failing?

**Comment by NTaylorMullen** [comment]
Last failure was a while ago but I wrote some code in MVC to make it possible to diagnose why it's failing. I've seen it fail twice but it is uncommon. My bet is that it's still flakey, just not as flakey as some of our other flakey tests that we've seen in the past. I'd vote for leaving this open a while longer

**Comment by NTaylorMullen** [comment]
Ah, actually this is a duplicate. Tracking this here: https://github.com/aspnet/AspNetCore-Internal/issues/1337

**Comment by halter73** [comment]
We got a new test failure here:

Error message:

```
Unexpected correlation Id, reading values from document:


<html><head></head><body>
fr-FR

fr-FR

14
<span id="cached-correlation-id">14</span>

</body></html>
```

Stack trace:

```
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationWithCultureTest.CacheTagHelper_VaryByCultureComposesWithOtherVaryByOptions() in /_/src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationWithCultureTest.cs:line 171
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=655364&view=ms.vss-test-web.build-test-results-tab&runId=16222964&resultId=124372&paneView=debug

**Comment by halter73** [comment]
See #55930 for more details on the very similar `CacheTagHelper_AllowsVaryingByUICulture` failure.
