### ISSUE TITLE
`dotnet new --update-apply` thinks 1.0.0-beta9 is newer than 1.0.0-beta10 and above

### ISSUE THREAD

**Issue by rexebin** [dotnet/aspnetcore#49077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`dotnet new --update-apply` thinks 1.0.0-beta9 is newer than 1.0.0-beta10 and above

### Expected Behavior

dotnet should update to the latest version even when the beta version is greater than 9

### .NET Version

6.0.401

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions
https://semver.org/spec/v2.0.0.html#spec-item-11

> NuGet 4.3.0+ supports [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html), which supports pre-release numbers with dot notation, as in 1.0.1-build.23.

beta9 and beta10 are sorted alphabetically. If you use beta.9 and beta.10 they will be sorted numerically.
