### ISSUE TITLE
Css Isolation Configuration

### ISSUE THREAD

**Issue by PowerCreek** [dotnet/aspnetcore#49081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to programmatically generate components with the RenderTreeBuilder, but when it comes to css using the `Sample.razor.css` approach, and I don't place a `<htmlElementTag></htmlElementTag>`, my components won't have the css isolation key, and therefore, the css won't be applied to the component which I want to build programmatically instead of having to define html elements around the content in the markup file to get the css isolation key to appear.

### Describe the solution you'd like

I would like to be able to leverage the css isolation implementation so that I may be able to have the css rules apply under the scope of the RenderFragment, but I want to be able to do it without the codegen relying on the existence of the razor file source.

Or, I would like to be able to turn off the css isolation and have `sample.razor.css` picked up by the system so that it compiles into the bulk css rules when served to the browser.

### Additional context

Here is what I have to do to grab the css isolation key if I'm using a programmatically generated component:

```
public string? GetCssKey(RenderTreeFrame[] frames)
        {
        //Grabbing frames is looked down upon by the annotation in the source, but it's the only way to do this.
        //sure is nifty tho, since it works.
            RenderTreeFrame? result = frames.Reverse().SkipWhile(e => e.FrameType is not RenderTreeFrameType.Attribute).FirstOrDefault(e =>
               e!.AttributeName is string s and ['b','-',..]
            );
            return result?.AttributeName as string;
        }

        public RenderFragment GetRenderFragment 
        {
            get
            {
                var contents = Contents?.ToArray() ?? Array.Empty<RenderItem>();
                (var open, var close) = GetOpenCloseActions;
                return b =>
                {
                        int seq = 0;
                    switch (Tag)
                    {
                        case { Tag: { Length: > 0 } t }:
                            var cssKey = GetCssKey(b.GetFrames().Array);
                            CssKey = cssKey ?? CssKey;
                            open(seq++, t, b);
                            
                            break;
                        case { Component: { } t }:
                            open(seq++, t, b);
                            break;
                        case { Tag: null, Component: null}:
                            open(seq++, null!, b);
                            break;
                    }
                    
                    if(Key is not null)
                        b.SetKey(Key);

                    foreach(var v in GetAttributes())
                        v.Invoke(seq++, b);

                    if(Tag is { Tag: { Length: > 0} } && CssKey is { Length: > 0 })
                            b.AddAttribute(seq++, CssKey, true);

                    foreach (var v in contents)
                    {
                        var result = v.Value switch
                        {
                            ElementCondition e => e.Invoke(),
                            ValueCondition e => e.Invoke(),
                            Func<object> e => e.Invoke(),
                            RenderFragment e => e,
                            RenderFragmentGen e => e.GetRenderFragment,
                            object e => e
                        };

                        switch (result)
                        {
                            case IEnumerable<RenderFragmentGen> a:
                                foreach (var f in a)
                                {
                                    b.AddContent(seq++, f.GetRenderFragment);
                                }
                                break;
                            case RenderFragment a:
                                b.AddContent(seq++, a);
                                break;
                            case object a:
                                b.AddContent(seq++, a);
                                break;
                            case null:
                                break;
                        }
                    }

                    close(b);
                };
            }
        }
    }
```
And I am required to do:
    

    @inherits ComponentSource<ShowHideButton>
    
 this div will have the css isolation key, but if I don't use this to surround @RenderSelf, we don't have a way to get the isolation 
key that would be used for this because the system isn't aware it needs one for this component before runtime.

    <div class="showhide">
        @RenderSelf
    </div>
    
   But would rather create less work by overriding `BuildRenderTree` and not have to have a razor file associated with the type that I am implementing, which doesn't need a razor file, except for the fact that the css isolation system would inhibit me from associating with the child html elements generated by the type.

  ```
  public abstract class ComponentSource<T> : ComponentBase
    {
        public ComponentSource()
        {
            Initialize?.Invoke();    
        }

        [Parameter]
        public ComponentData<T>? Data { get; set; }

        protected RenderFragmentGen? _self;

        public virtual Action? Initialize { get; }

        protected virtual RenderFragmentGen Self { get;  } = null!;
        protected RenderFragment RenderSelf => b => (_self ??= Self)?.GetRenderFragment(b);

        protected override void BuildRenderTree(RenderTreeBuilder builder) => RenderSelf(builder);
        ...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Scoped CSS is a Razor Compiler feature and we don't have plans to support it outside of the Razor compiler.

**Comment by PowerCreek** [comment]
I would agree, except we could expose the css isolation attribute in the RenderTreeBuilder pipeline, as it is provided to the underlying blazor framework as it translates to wasm

**Comment by PowerCreek** [comment]
SampleComponent.razor
`<div> <-- this is where the attribute is exposed.
    @RenderSelf
</div>`

SampleComponent.razor (2)
`@RenderSelf`
Without the div tags is still within the RenderBuilderTree pipeline where the data does exist, it is being overloaded by a custom render fragment delegate, which is why the isolation attribute won't exist, but it *could*, and that's the possible feature I would ask for if the underlying scoped css system is a razor implementation.
