### ISSUE TITLE
WASM Cors fails despite allowing everything

### ISSUE THREAD

**Issue by wrharper-AASP** [dotnet/aspnetcore#49094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to access a KeyVault secret it comes back with an error on builder.Configuration.AddAzureKeyVault saying fetch failed due to Cors. As you can see, it is enabled everywhere. I even tried a publish with Cors in Azure adding * aka allowing everything.

### Expected Behavior

Log into the Key Vault client side.
When testing locally, it should do interactivebrowser. When deployed, it should do managedidentity.

### Steps To Reproduce

```
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using WebAssemblyAuthTest.Client;
using Azure.Extensions.AspNetCore.Configuration.Secrets;
using Azure.Identity;
using Microsoft.AspNetCore.Cors;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddHttpClient("WebAssemblyAuthTest.ServerAPI", client => {
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
    client.DefaultRequestHeaders.Add("Access-Control-Allow-Origin", "*");
    client.DefaultRequestHeaders.Add("Access-Control-Allow-Methods", "GET, POST, PATCH, PUT, DELETE, OPTIONS");
    client.DefaultRequestHeaders.Add("Access-Control-Allow-Headers", "Origin, Content-Type, X-Auth-Token, x-ms-*");
})
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

// Supply HttpClient instances that include access tokens when making requests to the server project
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("WebAssemblyAuthTest.ServerAPI"));

builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("api://yourapi/yourscope");
});

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.WithOrigins().AllowAnyOrigin()
                            .AllowAnyHeader()
                            .AllowAnyMethod()
                            .AllowCredentials();
    });
});

builder.Configuration.AddAzureKeyVault(new Uri($"https://yourvault.vault.azure.net/"),
                    new DefaultAzureCredential(),
                    new AzureKeyVaultConfigurationOptions()
                    {
                        Manager = new KeyVaultSecretManager(),
                        ReloadInterval = TimeSpan.FromSeconds(15)
                    }
                 );

var app = builder.Build();
Console.WriteLine(app.Configuration["yoursecret"]);
await app.RunAsync();
```

### .NET Version

7

### Anything else?

I'm not seeing a root cause as to why this won't work at this point?
Everything online says to do these steps from the info I have gathered so far, still getting an error though.

**Comment by Markz878** [comment]
I have no idea what you are actually trying to do here, but here are some errors you have:

1. Allowing CORS always happens at the server, so that code makes no sense in the WASM client. Just in theory, it would work if you could somehow allow CORS on the Azure Keyvault servers that you call, but that is of course not possible.
2. You are using DefaultAzureCredential and hoping that once deployed to Azure, it would use Managed Identity. But your client code runs on the users browser, and there is no Azure services there to handle Managed Identity. This will never work in production.

So all in all, if you want to access a Key vault secret from a client, you have to do that by calling an API endpoint on your server project.

**Comment by SteveSandersonMS** [comment]
Thanks for the response @Markz878 - that's very helpful.

**Comment by wrharper-AASP** [comment]
1. Yes, that is the issue, I need to find a way to make it possible to get to the Vault without this happening. I mean, you can do it with a Desktop Application, why not with a client-side browser? This restriction doesn't make much sense.
2. I just switch to managed identity when i'm done testing, so the default azure is a troubleshooting step. you can ignore that :)

**Comment by wrharper-AASP** [comment]
The catch 22 is the public keyvault has the information on what the website is to begin with. So, I can't do it this way because of dynamic distribution.

**Comment by wrharper-AASP** [comment]
this isn't resolved. msftbot is auto closing on the weekends.

**Comment by SteveSandersonMS** [comment]
@wrharper-AASP Unfortunately I'm not aware of any other action that could be taken here. If the Azure Key Vault service chooses not to return CORS headers, then it can't be accessed from a web client, whether that's with .NET on WebAssembly or with JavaScript. This isn't something Blazor controls.

As far as I know the advice given by @Markz878 is correct, which is:

> So all in all, if you want to access a Key vault secret from a client, you have to do that by calling an API endpoint on your server project.
