### ISSUE TITLE
ClientAssets release for dotnet 7

### ISSUE THREAD

**Issue by austinmcdaniel** [dotnet/aspnetcore#49092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

this isn't really a bug, but I wasn't sure where to place it. Is there anyway we could get a nuget release for the ClientAssets package for dotnet 7? The fix is already in-place for ClientAssets to work with dotnet7 we just need an updated nuget package.
See here for the change and discussion around it: https://github.com/aspnet/AspLabs/pull/572

**Comment by mkArtakMSFT** [comment]
Just published an updated package: https://www.nuget.org/packages/Microsoft.AspNetCore.ClientAssets/0.1.0-alpha.23330.1

It will get listed soon.
