### ISSUE TITLE
Post SendAsync() doesn't return anything (Blazor WASM)

### ISSUE THREAD

**Issue by SjamesE** [dotnet/aspnetcore#49102]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using SendAsync() to post data to a server, the response of the Method will always have the default values. Also I am using NoCors. I am not sure if that changes anything.
I have tested it with my private server, and ptsv3.com. After sending the request I used the DevTools in Chrome to confirm the reqest succeeding and returning data.
Below is the code I used to reproduce the issue. It is also available on my GitHub.

```
// Index.razor
@page "/"
@inject HttpClient http

<PageTitle>Index</PageTitle>

<h1>@Status</h1>

<button @onclick="@SendData">Send</button>


@code {
    public string Status { get; set; } = "null";

    public async Task SendData()
    {
        var url = "https://ptsv3.com/t/testBlazorSendAsync/post/";
        var data = "dataDataDataData";

        var request = new HttpRequestMessage(HttpMethod.Post, url);
        request.Content = new StringContent(data);
        request.SetBrowserRequestMode(BrowserRequestMode.NoCors);

        var response = await http.SendAsync(request);
        Status = await response.Content.ReadAsStringAsync();
    }
}
```

### Steps To Reproduce

https://github.com/SjamesE/SendAsync-BugReport/tree/master

### .NET Version

7.0.100

### Anything else?

I used Blazor WebApp (Client without Host/Server)

![image](https://github.com/dotnet/aspnetcore/assets/46400628/f0f630ca-71d5-4073-bca9-c0931fc10777)

**Comment by SteveSandersonMS** [comment]
Apologies if I'm misreading the scenario, but I thought the `NoCors` request mode explicitly means the response will not be readable by your code, so it's expected to be empty. See the MDN docs at https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#value 

If you want to be able to access the response, you have to return CORS headers from your server - that's a rule enforced by the browser, which Blazor can't override.

**Comment by SjamesE** [comment]
I am sadly not able to change any headers on the Server-side. The browser gets the response. I can see it in the DevTools menu. Why wouldn't I be able to get it in the code as well?

**Comment by SteveSandersonMS** [comment]
I'm afraid this is how browser same-origin security works. This is a core feature of web development no matter what UI technology you use. Blazor can't control or override this as it is enforced by the browser, because it's a security feature to stop cross-origin data stealing.

**Comment by SjamesE** [comment]
So what are my options? Do I have to use a Host/Server to add the origins? Or is there a way to achieve it using only WebAssemblyApp?

**Comment by SteveSandersonMS** [comment]
Your idea is correct: the normal way to avoid this restriction is to have your client-side code make a request to your own server (either in the same origin, or in some other origin but returning CORS headers), and have your *server* make the request to the 3rd-party origin.

The reason this approach is not a security risk is that when your server makes a request to the 3rd-party origin, it can't supply any 3rd-party origin cookies from the browser since your code can't read the cookies from a 3rd-party origin.

**Comment by SjamesE** [comment]
Okay, thanks for the explaination!
