### ISSUE TITLE
Add debugging when running in WSL for Blazor WebAssembly

### ISSUE THREAD

**Issue by viethung9at1** [dotnet/aspnetcore#49119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to debug my Blazor WebAssembly when running it on WSL2 but the docs and the reality tell that I can't do that. I install all the languages compiler in WSL and none of them exists on Windows for convenient.

### Describe the solution you'd like

Add the ability to debug Blazor WebAssembly when it run in WSL and I can debug the app using Edge or Chrome running on Windows (not WSL)

**Comment by mkArtakMSFT** [comment]
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/37565
