### ISSUE TITLE
Allow validation attributes on `PageModel` itself

### ISSUE THREAD

**Issue by Yaevh** [dotnet/aspnetcore#4911]
#### Description of the problem:
As of 2.1.0, validation attributes are allowed on controller parameters, bound controller parameters, page model properties and handler method parameters. They are however not allowed on page models themselves, which makes it impossible to implement complex, multi-property validation in Razor Pages declaratively. Right now one must either invoke such validation manually, or encapsulate all properties in a custom viewmodel and decorate that viewmodel with a validation attribute, which is rather awkward considering that `PageModel` is the actual viewmodel for the page.
Are there any plans to allow validation of whole `PageModel`s in Razor Pages?

**Comment by pranavkm** [comment]
In general, MVC's model binding is geared towards validating entire object graphs. This works fairly well when you have models that were created from data over the wire. A `PageModel` instance has several properties that are produced from arbitrary inputs that the user is responsible for setting (think injected values or random properties that were read in the constructor). 

This makes it a bit tricky to make this work without the risk of unintentionally validating a deeply nested object that does not need to be validated. We could have an opt-in mechanism here, but given the security implications with validating inputs, we prefer to keep the expectations easy to reason about. If your app has specific requirements that require validating the page model itself, our guidance would be to move it to a separate type that appears as a bound property and validate that. The experience is only marginally poorer.

Given the complexity involved in solving this, and how little feedback we've heard in this area, I'm closing this issue. Thank you again for your feedback.
