### ISSUE TITLE
Blazor Web App template includes icon-192.png file that doesn't appear to be used

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49129]
When I create a new Blazor Web App project with .NET 8 Preview 6 the project contains an icon-192.png file in the wwwroot folder that doesn't appear to be used.

![image](https://github.com/dotnet/aspnetcore/assets/1874516/ca8145ca-88c5-435c-bab8-0851f5d10109)

**Comment by surayya-MS** [comment]
This is done with https://github.com/dotnet/aspnetcore/pull/49801
