### ISSUE TITLE
ViewData / ViewBag equivalent for Blazor server side rendering

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49131]
What's the equivalent for `ViewData` or `ViewBag` when doing Blazor server-side rendering (SSR)? How do you flow data from components back up to the layout with SSR?

**Comment by danroth27** [comment]
Related issues for days past:
- https://github.com/dotnet/aspnetcore/issues/7641
- https://github.com/dotnet/aspnetcore/issues/16009

**Comment by javiercn** [comment]
@danroth27 the answer for this would be a cascading value.

> How do you flow data from components back up to the layout with SSR?

The flow in Blazor is different, the Layout renders before the component inside the layout. So the flow is:
* Render layout
* Render body
* Re-render layout/body, if necessary, until quiesce.
