### ISSUE TITLE
Blazor substitute for the input tag helper

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49132]
MVC & Razor pages offer an [input tag helper](https://learn.microsoft.com/aspnet/core/mvc/views/working-with-forms#the-input-tag-helper) that can be used to bind an input element to a model expression. The tag helper does a number of things, one of which is pick the input type based on the type of the model expression. This is useful for scaffolding based on a data model. 

```cshtml
<div class="form-group">
    <label asp-for="Movie.Title" class="control-label"></label>
    <input asp-for="Movie.Title" class="form-control" />
    <span asp-validation-for="Movie.Title" class="text-danger"></span>
</div>
```

This issue proposes to have a substitute for the input tag helper that can be used when authoring forms with Blazor, like an `InputFor` component or something similar.

**Comment by javiercn** [comment]
@danroth27 this is already covered by InputText/Number, etc. 

Is there something we are missing here?

**Comment by danroth27** [comment]
The Razor pages scaffolder always uses the input tag helper to let the runtime design what input type to render:

```cshtml
<div class="form-group">
    <label asp-for="Movie.Title" class="control-label"></label>
    <input asp-for="Movie.Title" class="form-control" />
    <span asp-validation-for="Movie.Title" class="text-danger"></span>
</div>
```

With Blazor we'd need some logic in the scaffolder to look at the model type and determine which input component to use. So, the first question is to decide if that's how we'd want the Blazor scaffolder to work.

This is also a change in general usability. If an MVC or Razor Pages user wants to add a form input, they can just use the input tag helper and let the framework decide what input type to use. With Blazor the user has to always pick the right input component. Granted, MVC & Razor Pages also have a full editor and display template system. Maybe we decide that we don't want to bring all that forward. But we'll still need to decide how we want scaffolding to work.

**Comment by javiercn** [comment]
@danroth27 InputText/Number, etc. have all the same functionality, is there anything else? Feel free to reopen if you have thoughts.

**Comment by danroth27** [comment]
I chatted with @javiercn about how we want to handle inputs in [Blazor scaffolding](https://github.com/dotnet/Scaffolding/issues/2473). We're going to try out selecting the right Blazor input components based on the model type in the scaffolder.
