### ISSUE TITLE
PaginationState.CurrentPageIndex is read-only

### ISSUE THREAD

**Issue by TPSDrummer** [dotnet/aspnetcore#49149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

PaginationState.CurrentPageIndex is read-only but I can set it if I set a breakpoint and change it in the Intermediate Window.  I want to be able to set it when returning from another page.

### Expected Behavior

PaginationState.CurrentPageIndex should be read-write.

Thank you!

### .NET Version

.NET 8 Preview 5

**Comment by Kahbazi** [comment]
@TPSDrummer Have you tried using the [`PaginationState.SetCurrentPageIndexAsync(int pageIndex)`](https://github.com/dotnet/aspnetcore/blob/9da617793b3b387fd16bbc3e0ec06337569ca6ac/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/Pagination/PaginationState.cs#L52C1-L53C1) method?
