### ISSUE TITLE
Add tests of client code generation components

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#4914]
#### Is this a Bug or Feature request?
Enhancement that's part of #4896

#### Description of the problem
Have previously been manually testing the client code generation feature. Need to automate this, including tests of the tasks, the generic document tool, and the MSBuild targets.

Tasks should be relatively simple to unit test. But, the remainder will likely need functional tests that (unfortunately) write to disk. Will have a look at aspnet/DotNetTools, aspnet/EntityFrameworkCore, and aspnet/websdk to see how those repos test tools and MSBuild targets. May also discuss potential MSBuild and tool testing approaches with @pranavkm and @ryanbrandenburg.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
See the [features/client.code.generation branch](https://github.com/aspnet/Mvc/tree/feature/client.code.generation) branch. That work is intended for the 2.2 Preview 3 milestone.

**Comment by dougbu** [comment]
Part 1 in 04b1adbc2e49

**Comment by Pilchie** [comment]
@dougbu I'm assuming any further tests coming wouldn't be in the Preview 9 branch, right?  Can we update the milestone for this?

**Comment by dougbu** [comment]
@Pilchie your assumption was correct 😺

**Comment by dougbu** [comment]
More added in 24fc9c000865
