### ISSUE TITLE
Hot reload doesn't refresh the page in a Blazor Web App

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49144]
Repro steps:

- Create a new Blazor Web App with .NET 8 Preview 6
- Run the app (with or without debugging, doesn't matter)
- Make a change to Index.razor and apply the change to the running app

Expected result: Change applies successfully and the UI updates with the change.
Actual result: Change applies successfully, but the UI doesn't update. You have to manually refresh the page.

**Comment by danroth27** [comment]
It looks like the change does apply, but server-side rendered pages don't refresh automatically. Interactive pages, like the counter page, seem to update fine.

**Comment by ynnob** [comment]
This issue persists in **Preview 6**.

Hot Reload only works if the razor page is in server render mode.
`@attribute [RenderModeServer]`

**Comment by captainsafia** [comment]
This is the same as https://github.com/dotnet/aspnetcore/issues/47026.

I'll track progress in that issue but use this one to validate once the change is in. 🙇🏽

**Comment by captainsafia** [comment]
Re-opening this since we still need to consume the API on the SDK end.
