### ISSUE TITLE
Type conversions of component route parameters

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49141]
The [Blazor docs](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/routing#route-constraints) suggest that you can define component parameters that bind to route values with support for type conversions. And I've verified this works with a .NET 7 Blazor Server app. But when I try to do this in .NET 8 with a Blazor Web App, I get a type conversion exception: "Unable to cast object of type 'System.String' to type 'System.Int32'."

Repro steps:

- Create a new Blazor Web App with .NET 8 Preview 6
- Add the following component:

    *Pages/Test.razor*
    ```razor
    @page "/test/{id:int}"
    <p>Id = @Id
    @code {
        [Parameter]
        public int Id { get; set; }
    }
    ```

- Run the app and browse to /test/123.

Excepted result: `Id` parameter is bound to 123
Actual result:  System.InvalidOperationException: Unable to set property 'id' on object of type 'BlazorMovie.Pages.Movies.Delete'. The error was: Unable to cast object of type 'System.String' to type 'System.Int32'.

**Comment by javiercn** [comment]
Covered by https://github.com/dotnet/aspnetcore/issues/48866

**Comment by mkArtakMSFT** [comment]
Closing as it seems to be addressed already in preview 7.
