### ISSUE TITLE
Post docker compose and starting the microservice , service url comes back ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by soumya-ghosh-wdc** [dotnet/aspnetcore#49182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The service is already running as shown in the following snapshot :
<img width="661" alt="relevant-snapshot-01" src="https://github.com/dotnet/aspnetcore/assets/131948372/f0a7b7c8-b103-45bd-8a91-a25ced4b6c7a">

**But when I test the url in the browser as shown below 

http://localhost:63781/ there is no response.** Please see below.
![image](https://github.com/dotnet/aspnetcore/assets/131948372/543079c9-24b4-428d-b1e5-7bfd891c20f2)

Final API url : http://localhost:63781/api/Product

Build output 

1>docker-compose  -f "C:\Microservice\ProductMicroService\docker-compose.yml" -f "C:\Microservice\ProductMicroService\docker-compose.override.yml" -f "C:\Microservice\ProductMicroService\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose12200649739767505237 --ansi never up -d
1> Container ProductMicroService  Running
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Build started at 6:54 PM and took 03.530 seconds ==========

Container tools output -

========== Launching ==========
========== Debugging ==========
========== Debugging ==========
========== Launching ==========
========== Launching ==========
========== Launching ==========
========== Launching ==========
========== Launching ==========
========== Launching ==========
========== Debugging ==========

IDE used: Visual Studio 2022 Professional

### .NET Version

7.0.304

**Comment by mitchdenny** [comment]
Which template did you use in Visual Studio?

**Comment by soumya-ghosh-wdc** [comment]
I have used ASP.NET Core  WebAPI .Please note when I run via IISExpress with Swagger there is no issue.

This url is accessible :

http://localhost:51530/swagger/index.html
![image](https://github.com/dotnet/aspnetcore/assets/131948372/43c6034f-5548-4708-bedf-78df99aa970e)

**Comment by soumya-ghosh-wdc** [comment]
Any update ?

**Comment by mitchdenny** [comment]
I was not able to reproduce this issue. I suspect there might be something environmental on your machine causing this. Couple of things to try to debug the issue. Try doing a ```curl``` of the endpoint from your terminal. If that fails. See if the endpoint is listening inside the container. Exec into the running container and see what processes are running and if they are responsive:

```sh
docker exec -it [container id] /bin/sh
$ apt-get update -y
$ apt-get install -y wget
$ wget --no-check-certificate https://localhost/weatherforecast # I'm just using the template API surface in this example
```

**Comment by soumya-ghosh-wdc** [comment]
Thanks for those commands.I executed those as suggested but this is what I get:

C:\Microservice\ProductMicroService>**docker exec -it b4ab5bd0fb6c /bin/sh**
# **apt-get update -y**
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [252 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.8 kB]
Fetched 8658 kB in 3s (2511 kB/s)
Reading package lists... Done
# **apt-get install -y wget**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpsl5 publicsuffix
The following NEW packages will be installed:
  libpsl5 publicsuffix wget
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1149 kB of archives.
After this operation, 4001 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libpsl5 amd64 0.21.0-1.2 [57.3 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 wget amd64 1.21-1+deb11u1 [964 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 publicsuffix all 20220811.1734-0+deb11u1 [127 kB]
Fetched 1149 kB in 1s (2211 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libpsl5:amd64.
(Reading database ... 6988 files and directories currently installed.)
Preparing to unpack .../libpsl5_0.21.0-1.2_amd64.deb ...
Unpacking libpsl5:amd64 (0.21.0-1.2) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.21-1+deb11u1_amd64.deb ...
Unpacking wget (1.21-1+deb11u1) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../publicsuffix_20220811.1734-0+deb11u1_all.deb ...
Unpacking publicsuffix (20220811.1734-0+deb11u1) ...
Setting up libpsl5:amd64 (0.21.0-1.2) ...
Setting up wget (1.21-1+deb11u1) ...
Setting up publicsuffix (20220811.1734-0+deb11u1) ...
Processing triggers for libc-bin (2.31-13+deb11u6) ...
# **wget --no-check-certificate http://localhost:64404/api/Product**
--2023-07-05 05:26:08--  http://localhost:64404/api/Product
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:09--  (try: 2)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:11--  (try: 3)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:14--  (try: 4)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:18--  (try: 5)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:23--  (try: 6)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:29--  (try: 7)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:36--  (try: 8)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:44--  (try: 9)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:26:53--  (try:10)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:27:03--  (try:11)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:27:13--  (try:12)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:27:23--  (try:13)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

--2023-07-05 05:27:33--  (try:14)  http://localhost:64404/api/Product
Connecting to localhost (localhost)|127.0.0.1|:64404... failed: Connection refused.
Connecting to localhost (localhost)|::1|:64404... failed: Cannot assign requested address.
Retrying.

**Comment by mitchdenny** [comment]
Using ```wget``` again, use port 80 (or 443 if you have HTTPS configured). Inside the container, the app is running on port 80 from what I can tell from your ***docker ps*** screenshot above.

**Comment by soumya-ghosh-wdc** [comment]
I get the same error, please see below -

**# wget --no-check-certificate http://localhost:80/api/Product**
--2023-07-05 06:06:53--  http://localhost/api/Product
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
Connecting to localhost (localhost)|::1|:80... failed: Cannot assign requested address.
Retrying.

--2023-07-05 06:06:54--  (try: 2)  http://localhost/api/Product
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
Connecting to localhost (localhost)|::1|:80... failed: Cannot assign requested address.
Retrying.

--2023-07-05 06:06:56--  (try: 3)  http://localhost/api/Product
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
Connecting to localhost (localhost)|::1|:80... failed: Cannot assign requested address.
Retrying.

--2023-07-05 06:06:59--  (try: 4)  http://localhost/api/Product
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
Connecting to localhost (localhost)|::1|:80... failed: Cannot assign requested address.
Retrying.

**Comment by soumya-ghosh-wdc** [comment]
Any update ?

**Comment by soumya-ghosh-wdc** [comment]
Any update ? Awaiting inputs.

**Comment by soumya-ghosh-wdc** [comment]
One observation using curl -
**Invoking service url using docker container:**
---------------------------------------------------------------------------------------------------------------------
C:\Microservice\ProductMicroService>curl -v -L http://localhost:51594/ProductMicroService/api/Product
*   Trying 127.0.0.1:51594...
* **Connected to localhost (127.0.0.1) port 51594 (#0)**            Connection is established.
> GET /ProductMicroService/api/Product HTTP/1.1
> Host: localhost:51594
> User-Agent: curl/8.0.1
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

-----------------------------------------------------------------------------------------------------------------
**Invoking service url using IIS Express**
C:\Microservice\ProductMicroService>curl -v -L http://localhost:51530/api/Product
*   Trying 127.0.0.1:51530...
* Connected to localhost (127.0.0.1) port 51530 (#0)
> GET /api/Product HTTP/1.1
> Host: localhost:51530
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
< Date: Thu, 06 Jul 2023 09:10:20 GMT
<
**[{"id":1,"name":"Note5","description":"Samsung Mobile Phone-5","price":45000.00,"categoryId":1}]*** Connection #0 to host localhost left intact

In the second method it returns the expected .json output

**Comment by mitchdenny** [comment]
Those URLs are different?

**Comment by soumya-ghosh-wdc** [comment]
Yes.The docker url needs to be prefixed with the name of the container.

Please find below the snapshot taken from DockerDesktop
![image](https://github.com/dotnet/aspnetcore/assets/131948372/ae83963f-4f52-4e26-9cf6-4ca988056f42)

**Comment by soumya-ghosh-wdc** [comment]
Shall I share the source -as it is just a sample example I am  trying out..

**Comment by mitchdenny** [comment]
@soumya-ghosh-wdc based on the details provided I have not been able to reproduce the issue that you are experiencing. Without that I can't confirm whether or not this is an issue with ASP.NET Core, or the VS tooling vs. a local issue impacting only your machine.

What I'm asking for is for you to push some code to a public GitHub repo which is based on the Web API template that for you fails with this issue. Then I can double check that what I was reproducing locally is the same as what you have.

**Comment by soumya-ghosh-wdc** [comment]
Here is the repo details :
https://github.com/soumya-ghosh-wdc/sample-microservice-with-docker
https://github.com/soumya-ghosh-wdc/sample-microservice-with-docker.git

**Comment by soumya-ghosh-wdc** [comment]
I have SQLExpress as the database and Docker Desktop v 4.21  as local docker container.

**Comment by mitchdenny** [comment]
Worked fine for me with Docker: 

![image](https://github.com/dotnet/aspnetcore/assets/513398/c0c3bd5b-fcfa-4a35-859a-85f52ba67653)

I'm using Docker Desktop 4.21.1

**Comment by soumya-ghosh-wdc** [comment]
Can you provide me the steps to create a Grafana container ?

**Comment by soumya-ghosh-wdc** [comment]
I did run some docker network commands -
Here is the output :
C:\Microservice\ProductMicroService>docker network ls
NETWORK ID     NAME                                        DRIVER    SCOPE
fd6398eae165   bridge                                      bridge    local
1bdf5beea7d4   dockercompose12200649739767505237_default   bridge    local
08b0293e58bb   host                                        host      local
8992f1755bc3   none                                        null      local

Here is the inspection command 

C:\Microservice\ProductMicroService>docker network inspect dockercompose12200649739767505237_default
[
    {
        "Name": "dockercompose12200649739767505237_default",
        "Id": "1bdf5beea7d42846890359c7eb6af671955d85f576c2271dbf456d5ecfa5d5ca",
        "Created": "2023-07-10T05:42:46.806523819Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "c13f1cdac41dd5e5b8e09779aa59688577065264a0d2714aa120f9fbd1006761": {
                "Name": "ProductMicroService",
                "EndpointID": "6e9c69a631be1b547d42ef46c66d69ccf3e21b570a828b43236896f5ffb1a366",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "dockercompose12200649739767505237",
            "com.docker.compose.version": "2.19.0"
        }
    }
]

**Comment by soumya-ghosh-wdc** [comment]
Do you anything obvious that needs to be fixed from the above inspection.

**Comment by mitchdenny** [comment]
Here is a command you can run to spin up a Grafana container (from any command-line that Docker is available on):

```
docker run -it -p 3000:3000 grafana/grafana
```

Once that is running, open a web browser at http://localhost:3000 and you should see the Grafana login screen. If that works then it means the basic mechanics of your Docker networking is OK.

For the repro you provided (which didn't repro) - this is the URL I was able to hit: https://localhost:32772/swagger/index.html

This is the output of ```docker ps```:

```
PS C:\Users\midenn> docker ps
CONTAINER ID   IMAGE                     COMMAND               CREATED          STATUS          PORTS                                           NAMES
851f72d0bb73   productmicroservice:dev   "tail -f /dev/null"   51 seconds ago   Up 50 seconds   0.0.0.0:32773->80/tcp, 0.0.0.0:32772->443/tcp   ProductMicroService
```

You can see that port (32773) is mapped through to the code running into the container.

**Comment by mitchdenny** [comment]
Nothing is standing out for me from that output above. Out of interest when you are in VS how are you actually launching your project? Are you hitting F5 whilst the launch settings is pointing to ```Docker``` - or are you running ```docker-compose up```. Either should work but I'm just trying to figure out where you might be stumbling here.

**Comment by soumya-ghosh-wdc** [comment]
Finally I got it working.

Key learnings:

- Windows defender firewall may block docker backend service.It typically prompts while docker compose.Use the correct option to allow access to domain / private network.
- Modify the database connection string wherever applicable with **_Data Source= IpAddress,1433_**
- Make sure you make the following config using SQL Configuration manager
![image](https://github.com/dotnet/aspnetcore/assets/131948372/3801502c-674c-4933-94e5-05cf1be944bd)

![image](https://github.com/dotnet/aspnetcore/assets/131948372/e61c1bab-a7ea-45ee-b24a-f9e50111eadd)
