### ISSUE TITLE
[gRPC] How to correctly transmit error details to client with gRPC-JSON transcoding?

### ISSUE THREAD

**Issue by Sayan751** [dotnet/aspnetcore#49196]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/49179

<div type='discussions-op-text'>

<sup>Originally posted by **Sayan751** July  3, 2023</sup>
I have a gRPC service with JSON transcoding enabled. An endpoint of the service throws `RpcException` with same status code but different metadata. Examples:

```csharp
throw new RpcException(new Status(StatusCode.InvalidArgument, "Whatever1"), new Metadata
{
    { "Code", Errors.Error1.ToString() }
});

throw new RpcException(new Status(StatusCode.InvalidArgument, "Whatever2"), new Metadata
{
    { "Code", Errors.Error2.ToString() }
});
```

Whoever, when I am making an HTTP call to the service, then I am getting the following:

```json
{
  "code": 3,
  "message": "Whatever1",
  "details": []
}
```

I expected the trailers to appear in the `details` array. Am I missing something here? At the end, I need a way to differentiate between the two errors with the same status code. Is that possible? </div>

**Comment by Sayan751** [comment]
Sorry for the tag @JamesNK, but can you please shade some light into this?

**Comment by adityamandaleeka** [comment]
cc @mgravell

**Comment by contione** [comment]
Is there a solution currently available?

**Comment by alrz** [comment]
If the key `"grpc-status-details-bin"` is present in the trailers, the response should serialize that instead which will include the `Details` collection.

```cs
        static Google.Rpc.Status GetStatusDetailsFromTrailers(Metadata trailers)
        {
            const string GrpcStatusDetailsHeader = "grpc-status-details-bin";
            var statusDetails = trailers.Get(GrpcStatusDetailsHeader);
            if (statusDetails != null && statusDetails.IsBinary)
            {
                return Status.Parser.ParseFrom(statusDetails.ValueBytes);
            }

            return null;
        }
```
This is the key defined in [dotnet-gax](https://github.com/googleapis/gax-dotnet)

**Comment by chris-crucible** [comment]
I am having the same issue and searching around led me here. Any chance of this making it in soon?
