### ISSUE TITLE
Razor Pages post to incorrect handler with "OnPost" and "OnPostXxx"

### ISSUE THREAD

**Issue by xccu** [dotnet/aspnetcore#49194]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

A Razor Page will post to incorrect handler with OnPost and OnPostXxx handler  if doesn't set  **asp-page-handler** for OnPost request.
Once we posted to the **OnPostXxx** handler and post to **OnPost**  again. will always post to **OnPostXxx** handler .

### Expected Behavior

post to the **OnPost** handler correctly without  **asp-page-handler** property in **form** tag when have OnPostXxx handler in Razor Page

### Steps To Reproduce

I have a Razor Page like this:
Forms.cshtml.cs
```csharp
public class FormsModel : PageModel
{
    public string Message { get; set; }

    public void OnGet()
    {
        Message = "On Get";
    }

    public void OnPost()
    {
        Message = "On Post";
    }

    public void OnPostTest()
    {
        Message = $"On Post Test";
    }
}
```
Form.cshtml
```html
@page
@model RazorPage.Web.Pages.Test.FormsModel
@{
}

<h3>@Model.Message</h3>

<a asp-page="/Test/Forms"> Forms</a>

<form method="post">
    <button type="submit">Post</button>
</form>

<form asp-page-handler="Test" method="post" >
    <button>Post test</button>
</form>
```
First click **Post**  will  post to**OnPost** handler, and click **"Post  Test** will post to **OnPostTest** handler. Then click  **Post** again will always post to **OnPostTest** handler. 
To solve the issue ,I have to set  **asp-page-handler=""** to post **OnPost** handler

### .NET Version

6.0

**Comment by javiercn** [comment]
@xccu thanks for contacting us.

This is happening due to how link generation works in ASP.NET Core. It's by design and the correct way to deal with it is to do exactly what you did and explicitly indicate that you don't want any handler associated with the form post.
