### ISSUE TITLE
Checkbox Tag-Helper ignores form attribute when hidden input is generated

### ISSUE THREAD

**Issue by m0ddixx** [dotnet/aspnetcore#49201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following code:
```html
<label form="document-generator-single-form" asp-for="DeadlineToResubmissionDate" class="form-label"></label>
<input form="document-generator-single-form" asp-for="DeadlineToResubmissionDate" type="checkbox" class="form-check"/>
<span form="document-generator-single-form" asp-validation-for="DeadlineToResubmissionDate" class="invalid-feedback"></span>
```
This code generates a hidden field, which i suppose should represent the payload for this input field when it's not selected:
```html
<input name="DeadlineToResubmissionDate" type="hidden" value="false">
```

However the form attribute, which should point to the id of the submission form is missing here.
I also conducted the Request-Payload and the DeadlineToResubmissionDate property is missing from the request completely.

### Expected Behavior

Either the hidden input should respect the given form from the Tag-Helper, or something is happening inside here, I am missing: https://github.com/dotnet/aspnetcore/blob/53aad9807f89c57c48b164adcecdb9010f09f8cf/src/Mvc/Mvc.TagHelpers/src/InputTagHelper.cs#L317-L338

### .NET Version

6.0.411

**Comment by m0ddixx** [comment]
I'm trying something like the follwoing inside the if statement https://github.com/dotnet/aspnetcore/blob/53aad9807f89c57c48b164adcecdb9010f09f8cf/src/Mvc/Mvc.TagHelpers/src/InputTagHelper.cs#L313
```csharp
if (htmlAttributes.ContainsKey("form"))
{
    // If the original checkbox has a form attribute, the hidden field should respect it and the
    // attribute should be passed on
    htmlAttributes.TryGetValue("form", out var formAttribute);
    if (formAttribute is string formAttributeString)
    {
        hiddenForCheckboxTag.MergeAttribute("form", formAttributeString);
    }
}
```

I think I'm missing something while constructing the tests, because I can't get the form attribute into htmlAttributes.

**Comment by javiercn** [comment]
@m0ddixx thanks for contacting us.

It's very likely the tag helper doesn't account for the form parameter when emitting the hidden field. It was not a commonly supported browser feature at the time this was implemented.

We would be happy to accept a PR if you want to provide a simple fix for it.
