### ISSUE TITLE
Identity is not null-checked

### ISSUE THREAD

**Issue by uecasm** [dotnet/aspnetcore#49211]
https://github.com/dotnet/aspnetcore/blob/69254997c002a06cc5e772f35052040ce7568dbf/src/Components/Server/src/Circuits/RevalidatingServerAuthenticationStateProvider.cs#L64

`ClaimsPrincipal.Identity` is a nullable property, which is not checked here; as such if it is actually null at this point then it will throw a `NullReferenceException`.  For example, if `ClaimsPrincipal` was default-constructed.

This should probably be `authenticationState.User.Identity?.IsAuthenticated ?? false` instead.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this, @uecasm.
Would you like to submit a PR to address this?
