### ISSUE TITLE
[Blazor] Enhance navigation different interaction behavior

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#49210]
Possibly related to https://github.com/dotnet/aspnetcore/issues/49207

When enhanced navigation is enabled, interacting fast enough with the page can cause errors. That does not happen when interacting with the page (as fast as humanly possible) without enhanced navigation turned on.

It looks like the browser might be doing something to sequence the interactions that we might not be doing in the enhanced navigation mode, and that might be leading to race conditions and other similar problems.

It seems that the browser is sequencing the events, so we should probably do the same. Keep track of what element triggered an action, and don't trigger the next one until we've received the response and the element is still on the page.

**Comment by SteveSandersonMS** [comment]
Do you have repro steps? I tried the sample from https://github.com/dotnet/aspnetcore/issues/49207 and hackishly modified it not to emit the invalid attribute so that it worked, and then I clicked the buttons as fast as I could and didn't get errors.

**Comment by javiercn** [comment]
I'll try again once they are addressed.

**Comment by mkArtakMSFT** [comment]
@javiercn are we good to close this, given we've seen nobody else from the community hit this already?

**Comment by mkArtakMSFT** [comment]
Closing. Please reopen if you believe this is still happening, @javiercn.
