### ISSUE TITLE
Consider removing RazorComponentResult

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#49227]
We aren't 100% clear on the use cases for it, since it would only work if the component you're rendering works in a standalone way, without a `Router` or any other ancestor components outside the layout. That is:

 * You can render a component inside a layout
 * But you can't have a `Router` involved in this because (1) in our default app structure, the router contains the layout, rather than the layout containing the router, and (2) even if you're willing to restructure your app, there's no good way to supply a `RouteData`.

If there are legit use cases for `RazorComponentResult` then we'd keep it but it would be good to validate this!

**Comment by SteveSandersonMS** [comment]
Note that the more obviously-useful alternatives are:

 * `MapRazorComponents`, which works with a `Router` component
 * A new "map dynamic Razor Component" endpoint that @javiercn is working on

**Comment by DamianEdwards** [comment]
I think the scenario should absolutely be supported, e.g. to enable serving dynamic HTML as results from minimal APIs. In addition, the performance characteristics of directly returning/rendering a component are attractive for certain scenarios.

**Comment by danroth27** [comment]
> A new "map dynamic Razor Component" endpoint that @javiercn is working on

Details?

**Comment by mkArtakMSFT** [comment]
Have decided to keep this.
