### ISSUE TITLE
Explore switching MultipartReaderStream to use IndexOf

### ISSUE THREAD

**Issue by stephentoub** [dotnet/aspnetcore#49223]
MultipartReaderStream currently uses a Boyer-Moore substring search implementation as part of finding the next boundary:
https://github.com/dotnet/aspnetcore/blob/53aad9807f89c57c48b164adcecdb9010f09f8cf/src/Http/WebUtilities/src/MultipartReaderStream.cs#L279-L294

We should check to see whether this is still more beneficial than just using the vectorized:
https://github.com/dotnet/runtime/blob/7b91fd42a64732681472afc8d5a52c5bc5eb0c8a/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.cs#L1694

Regex used to use Boyer-Moore as well, and in .NET 7 deleted its use of Boyer-Moore entirely, instead just using IndexOf, for significant gains in most cases.  See https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#leading-vectorization for details.

**Comment by sebastienros** [comment]
@BrennanConroy close?

**Comment by BrennanConroy** [comment]
No, we still fallback to Boyer-Moore for substring matching if needed.
We can look into vectorized substring matching to replace Boyer-Moore. But that requires more work since there isn't an API in the runtime for this that I'm aware of.

**Comment by stephentoub** [comment]
> We can look into vectorized substring matching to replace Boyer-Moore. But that requires more work since there isn't an API in the runtime for this that I'm aware of.

`str.IndexOf(substr)` is vectorized.  What are you referring to?

**Comment by BrennanConroy** [comment]
Substring matching. Given "abcd" as the input and we're searching for "abcde", we want to match on "abcd".

**Comment by stephentoub** [comment]
> Partial substring matching. Given "abcd" as the input and we're searching for "cde", we want to match on "cd".

Why is that needed? Just for when the substring is straddling segments so you want to match "cd" at the end of one and "e" at the beginning of the next?

**Comment by BrennanConroy** [comment]
Because we're reading off the network and can have part of the payload available. That way we can give the user the maximum available data that can't match the boundary we're looking for. We could possibly just not do that part which would let us get rid of the boyer-moore code. Idk how important it is. That's also part of what should be evaluated for finishing this issue.

https://github.com/dotnet/aspnetcore/blob/53aad9807f89c57c48b164adcecdb9010f09f8cf/src/Http/WebUtilities/src/MultipartReaderStream.cs#L297C67-L297C67
You left off case 2

**Comment by stephentoub** [comment]
> Edit: But I guess at a minimum we can remove case 1 now?

That's what I'm saying, yes.

**Comment by BrennanConroy** [comment]
> > Edit: But I guess at a minimum we can remove case 1 now?
> 
> That's what I'm saying, yes.

Ok sure :) but it'd be nice if we can remove all of boyer-moore too. Gets rid of an array alloc and populating the array in the ctor, plus should be faster due to vectorization.

**Comment by stephentoub** [comment]
What does case 2 require Boyer-Moore?

**Comment by BrennanConroy** [comment]
Honestly, I never actually looked at what the code was doing in `SubMatch`, I just read the comments to see what it was intending to do. I just assumed it was all part of the boyer-moore algorithm. But looks like case 2 is just normal character comparisons in a double loop.

**Comment by stephentoub** [comment]
Right.
