### ISSUE TITLE
.net core 7 AddProblemDetails only show Response Header

### ISSUE THREAD

**Issue by andynguyen129** [dotnet/aspnetcore#49239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using AddProblemDetails however if I set my environment is Development. Swagger return Response Body error detail but if I set it is not Development, it only show response Header. Anyone know how to config it to always show response body my Program.cs

```
        var builder = WebApplication.CreateBuilder(args);

        builder.Host.UseSerilog((context, config) => config.ReadFrom.Configuration(context.Configuration));
        builder.Services.AddCustomCors()
                        .AddAuthSupport(builder.Configuration)
                        .AddCustomJson()
                        .AddHttpClient()
                        .AddProblemDetails();

        builder.Services.AddDatabase(builder.Configuration)
                        .AddCustomFluentValidation()
                        .AddOpenAPISupport();

        var app = builder.Build();

        app.UseCors()
           .UseFullSwaggerUI()
           .UseHttpsRedirection()
           .UseAuthentication()
           .UseAuthorization();

        app.MapEndpoints();

        app.Run();
    }
```
This is Production env: [production only response header](https://i.stack.imgur.com/rnbII.png) This is Development env [development response body](https://i.stack.imgur.com/gyQrh.png)

I tried to find any special setting in all config files but nothing special. So could it be an issue with AddProblemDetails?

### Expected Behavior

Different response in deferent environment  ProblemDetails

### .NET Version

7.0

**Comment by mitchdenny** [comment]
There are a few extensions that I don't recognize there. Is it possible for you to push a self-contained repro of the issue to a public GitHub repo that we can download and build and inspect to figure out what is going on here.
