### ISSUE TITLE
Add support for anti-forgery middleware

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#49237]
## Background and Motivation

MVC currently supports anti-forgery token validation via an endpoint filter. Similar constructs do not exist for minimal APIs. This proposal outlines support for an anti-forgery middleware, similar to CORS or authorization middleware, that will run anti-forgery token checks on endpoints with the appropriate metadata.

## Proposed API

All APIs are net new.

```csharp
// Assembly: Microsoft.AspNetCore.Antiforgery
namespace Microsoft.AspNetCore.Builder;

public static class AntiforgeryApplicationBuilderExtensions
{
  public static IApplicationBuilder UseAntiforgery(this IApplicationBuilder builder) { }
}
```

Note: The `IAntiforgeryMetadata` interface needs to reside in the Http.Abstractions assembly so that it can be consumed by the RequestDelegateFactory, the endpoint middleware, and Blazor SSR components.

```csharp
// Assembly: Microsoft.AspNetCore.Http.Abstractions
namespace Microsoft.AspNetCore.Antiforgery;

public interface IAntiforgeryMetadata
{
  public bool Required { get; }
}
```

```csharp
// Assembly: Microsoft.AspNetCore.Antiforgery
namespace Microsoft.AspNetCore.Antiforgery;

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
public class RequireAntiforgeryTokenAttribute(bool required = true) : Attribute, IAntiforgeryMetadata
{
  public bool Required { get; }
}
```

```csharp
// Assembly: Microsoft.AspNetCore.Antiforgery
namespace Microsoft.AspNetCore.Antiforgery;

public interface IAntiforgeryValidationFeature
{
    public bool IsValid { get; }
    public AntiforgeryValidationException? Exception { get; }
}
```

## Usage Examples

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAntiforgery();

var app = builder.Build();

app.UseAntiforgery();

// Anti-forgery token validation happens for this endpoint
app.MapPost("/todo", ([FromForm] Todo todo) => Results.Ok(todo));

app.Run();
```

## Alternative Designs

This API proposal does not include public default implementations of antiforgery metadata types (e.g. `AntiforgeryMetadata : IAntiforgeryMetadata`) or extension methods for disabling anti-forgery.

Anti-forgery metadata with anti-forgery enabled is automatically added for endpoints that contain a source coming from a form. We anticipate that users will implement their own extension methods for disabling anti-forgery on a given endpoint.

```csharp
public static RouteHandlerBuilder DisableAntiforgery(this RouteHandlerBuilder builder)
{
  builder.WithMetadata(new RequireAntiforgeryTokenAttribute(false));
  return builder;
}
```

## Risks

 Nothing ventured, nothing gained.

**Comment by halter73** [comment]
What's the plan for getting the antiforgery token to the client? I realize that for minimal APIs in particular, this will probably need to be done with custom logic in the app, but `IAntiForgeryTokenSet.GetAndStoreTokens(HttpContext)` isn't exactly the most convenient API to use. Have we looked at improving that at all?

> Anti-forgery metadata with anti-forgery enabled is automatically added for endpoints that contain a source coming from a form.

Will we throw at startup if there's anti-forgery metadata without any call to `UseAntiforgery()`? It seems like the right thing to do, but minimal added `IFromFormMetadata` in .NET 7, so it could be a big break.

**Comment by captainsafia** [comment]
> What's the plan for getting the antiforgery token to the client? 

Blazor forms support this via https://github.com/dotnet/aspnetcore/commit/78bec183dcbc19601a8046b0e0c3bd93890c4e53. MVC has the existing infrastructure via `@Html.BeginForm` and `@AntiforgeryToken`.

> Have we looked at improving that at all?

Not in the currently open PR, but I don't believe the changeset to support this will require API review so it should be feasible to add it later on.

> Will we throw at startup if there's anti-forgery metadata without any call to UseAntiforgery()? I

Yes, similar to other security-related middlewares like CORS and auth.

**Comment by halter73** [comment]
API Review Notes:

- What about `[ValidateAntiForgeryToken]`?
  - We're still designing MVC integration.
  - There's no current plan to implement `IAntiforgeryMetadata`.
- What if I add `[RequireAntiforgeryToken]` to an MVC action or controller?
  - Like any other endpoint, it just works if you add the middleware which we'll validate.
- What if `[ValidateAntiForgeryToken]` to a minimal endpoint?
  - It doesn't work today, but it could be more surprising in the future.
  - We plan to throw at startup if this attribute is detected on a non-MVC endpoint.
    - This might also be hard to detect if `[ValidateAntiForgeryToken]` is added if it doesn't implement `IAntiforgeryMetadata`, but we could detect it at startup.
- "Validate" is more accurate the "Require" but we've burned the first name.
  - Could we re-use `[ValidateAntiForgeryToken]`? Are people going to actually write out this attribute much in practice? If not, we can just do the metadata interface with internal implementations. @javiercn Are you okay with keeping the attribute internal?
- Do we need to ensure that the `IAntiforgeryValidationFeature` is actually looked validate?
  - It could be bad if people incorrectly thought UseAntiforgery prevented invalid request from continuing at all.
  - Most endpoints would respect the feature, but what if you used `MapPost(RequestDelegate)`?
    - Documentation should make it clear you need to look at the feature
  - As a comparison, we'll yell at you if you call `UseAuthentciation()` without `UseAuthorization()`
  - **We should ensure the form is poisoned for endpoints that require antiforgery tokens which are either not present or invalid**
- Do we want an extension method for `HttpContext` or `HttpRequest` that allows you to check `IAntiforgeryValidationFeature.IsValid`
  - This could also be a non-extension method
  - We could add it later if we find consumers are need to resolve this feature a lot.
- `IAntiforgeryMetadata` could go in `Microsoft.AspNetCore.Http.Metadata` like some of the `IFrom*` metadata, but we think this is more similar to `IAuthorizeData` and belongs in a feature-specific namespace.
- Would we consider just adding the `DisableAntiforgery()` extension method?
  - If you're just doing bearer token auth or something like that, antiforgery isn't really necessary.
  - People with only non-browser clients could get really annoyed that the workaround requires implementing `IAntiforgeryMetadata` yourself and adding it to the endpoint metadata. @martincostello What do you think?

We're happy with the following, but we want more feedback if we also need the attribute and the extension method to disable it.

```csharp
// Assembly: Microsoft.AspNetCore.Http.Abstractions
namespace Microsoft.AspNetCore.Antiforgery;

public interface IAntiforgeryMetadata
{
  public bool Required { get; }
}

// Assembly: Microsoft.AspNetCore.Antiforgery
namespace Microsoft.AspNetCore.Antiforgery;

public interface IAntiforgeryValidationFeature
{
    public bool IsValid { get; }
    public AntiforgeryValidationException? Exception { get; }
}
```

**Comment by martincostello** [comment]
> People with only non-browser clients could get really annoyed that the workaround requires implementing IAntiforgeryMetadata yourself and adding it to the endpoint metadata. @martincostello What do you think?

Having a way to disable the antiforgery where you **know** it isn't a problem with a method that does it for you without having to implement an interface yourself sounds a good idea to me. I guess a middleground would be exposing a public type with that interface that you can use to do that but I think that would look a bit _"ick"_.

```csharp
app.MapPost("whatever", () => { }).DisableAntiforgery(); // 👍
app.MapPost("whatever", () => { }).AddMetadata(new DisableAntiforgeryAttribute()); // 👎
```

**Comment by captainsafia** [comment]
> I guess a middleground would be exposing a public type with that interface that you can use to do that but I think that would look a bit "ick".

Interesting feedback because that's what I outlined as a note in the [alternative designs section](https://github.com/dotnet/aspnetcore/issues/49237#issue-1790480850) here.

I have no strong opposition to exposing a public method, other than the reservations I have about them in general after adding too many extension methods too soon for OpenAPI support 😅 .

It's a fairly cheap and non-consequential API to add so I don't see a harm in providing an extension method (and no public implementation of the interface).

**Comment by martincostello** [comment]
Just to clarify, I think that would only be _"ick"_ if that's in the _user's_ application code and they're implementing it themselves as they define their endpoints. I don't have a problem with that how it being implemented under the hood in the runtime 😄

**Comment by captainsafia** [comment]
Some updates to this API proposal:

1. To support being able to check the `IAntiforgeryValidationFeature` automatically when reading forms for minimal APIs, we need to move this from the `Microsoft.AspNetCore.Antiforgery`assembly to the `Microsoft.AspNetCore.Http.Features` assembly. To avoid cyclic dependencies, the type of the `Exception` property needs to be changed.

```diff
-// Assembly: Microsoft.AspNetCore.Antiforgery
+ // Assembly: Microsoft.AspNetCore.Http.Features
namespace Microsoft.AspNetCore.Antiforgery;

public interface IAntiforgeryValidationFeature
{
    public bool IsValid { get; }
-    public AntiforgeryValidationException? Exception { get; }
+    public Exception? Exception { get; }
}
```

2. Removing the `RequireAntiforgeryTokenAttribute` and updating the existing MVC attributes to implement the `IAntiforgeryMetadata` interface makes it a lot more starightforward to integrate the new middleware with existing MVC patterns.

```diff
-public class AutoValidateAntiforgeryTokenAttribute : Attribute, IFilterFactory, IOrderedFilter
+public class AutoValidateAntiforgeryTokenAttribute : Attribute, IFilterFactory, IOrderedFilter, IAntiforgeryMetadata
{
+    public bool Required;
}
```

```diff
-public class AutoValidateAntiforgeryTokenAttribute : Attribute, IFilterFactory, IOrderedFilter
+public class ValidateAntiForgeryTokenAttribute : Attribute, IFilterFactory, IOrderedFilter, IAntiforgeryMetadata
{
+    public bool Required;
}
```

3. Add support for a `DisableAntiforgery` extension method to support opting out of the on-by-default antiforgery token check for certain endpoints.

```csharp
namespace Microsoft.AspNetCore.Builder;

public static class RoutingEndpointConventionBuilderExtensions
{
    public static TBuilder DisableAntiforgery<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
}
```

**Comment by mitchdenny** [comment]
nit: AntiForgery inconsistent capitalization on ```ValidateAntiForgeryTokenAttribute```.

**Comment by javiercn** [comment]
> Could we re-use [ValidateAntiForgeryToken]? Are people going to actually write out this attribute much in practice? If not, we can just do the metadata interface with internal implementations. @javiercn Are you okay with keeping the attribute internal?

This is for Blazor customers, they need to be able to enable/disable it on a per page basis.

**Comment by javiercn** [comment]
> Do we need to ensure that the IAntiforgeryValidationFeature is actually looked validate?
> * It could be bad if people incorrectly thought UseAntiforgery prevented invalid request from continuing at all.
>    * Most endpoints would respect the feature, but what if you used MapPost(RequestDelegate)?
>    * Documentation should make it clear you need to look at the feature
>    * As a comparison, we'll yell at you if you call UseAuthentciation() without UseAuthorization()
> * We should ensure the form is poisoned for endpoints that require antiforgery tokens which are either not present or invalid

I think the challenge here is with semantics. 
* MVC does not automatically validate antiforgery.
* Razor pages does, with the option to disable it on a granular level.
* Blazor does too, with the same approach (you can disable it on a per-page level).

In the context of an app, what does `app.UseAntiforgery()` mean? It can mean two things:
* Validate Antiforgery always (Which is the safe bet, but is highly breaking and forces Antiforgery to be configured on any endpoint (at least those that accept form data / multipart content))
* Validate Antiforgery only if an endpoint contains metadata indicating so. This is challenging because it surprises customers, who would expect Antiforgery to be validated at that point in the pipeline, but in fact, it doesn't happen because the metadata needs to be added to the endpoint.

* If we look at other middleware:
  * CORS: It's not representative, since it's not a security middleware. The only thing CORS does is to open the door to let things that were blocked possible.
  * Authorization: The moment it's enabled, it will use the default policy and combine that with the individual policy from the endpoint. If you don't specify `[Authorize]` in your endpoint, you'll get the default policy (which might be to require the user to be authenticated).

We can potentially do the same with the AntiforgeryMiddleware. There is a per middleware policy (passed down to the middleware instance via an options callback in the middleware) `app.UseAntiforgery(options => ...)`, a global policy, configured by the AntiforgeryOptions, and a per endpoint policy configured by metadata, with the idea that the most specific policy wins
Endpoint -> Middleware -> Global

As for Antiforgery validation, I would prefer if the middleware can collaborate with the individual frameworks. Antiforgery is a concept that is tightly coupled with the UI framework, and it's something that the framework can manage by itself without introducing the concept to users.

Relying exclusively on the middleware complicates the experience for core scenarios (like Blazor) by introducing an extra concept in the user face when the framework is perfectly capable of managing it under the hood.

I agree that we need the middleware because I can't think any other way minimal APIs can do this, but if we look at other frameworks, I don't recall any of them exposing them in the pipeline.

It might be interesting to explore a different alternative for minimal APIs here, like an endpoint that wires it up right before the endpoint gets called.

**Comment by captainsafia** [comment]
> As for Antiforgery validation, I would prefer if the middleware can collaborate with the individual frameworks. Antiforgery is a concept that is tightly coupled with the UI framework, and it's something that the framework can manage by itself without introducing the concept to users.

Yep, this is the current approach in the draft PR. The middleware itself doesn't short-circuit but sets an HTTP feature that it expects each framework to handle. Blazor and minimal APIs can read from this feature and react accordingly.

Your comment in another thread about how we might approach this for MVC presents an option that doesn't require us to update the existing attributes to implement the new metadata interface.

> Validate Antiforgery always (Which is the safe bet, but is highly breaking and forces Antiforgery to be configured on any endpoint (at least those that accept form data / multipart content))
> 
> Validate Antiforgery only if an endpoint contains metadata indicating so. This is challenging because it surprises customers, who would expect Antiforgery to be validated at that point in the pipeline, but in fact, it doesn't happen because the metadata needs to be added to the endpoint.

The current approach is somewhere in between. Antiforgery is only validating on endpoint that contain the metadata to indicate so _but_ each framework (minimal and Blazor) sets the metadata on-by-default for form-consuming endpoints. MVC might be the only area where users have to explicit set the metadata and the framework won't automatically set the endpoint metadata for form-consuming endpoints.

> Relying exclusively on the middleware complicates the experience for core scenarios (like Blazor) by introducing an extra concept in the user face when the framework is perfectly capable of managing it under the hood.

My current approach is that frameworks like MVC and Blazor will continue to function _without_ the middleware but respect the HTTP feature the middleware sets (and not run validation again) if the middleware gets registered.

> This is for Blazor customers, they need to be able to enable/disable it on a per page basis.

Per offline discussion, let's bring up the attribute in a separate API review. Since it's already in the codebase, I'll avoid removing it in my anti-forgery PR.
