### ISSUE TITLE
Unexpected RST after client FIN for non-chunked responses

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#49236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Requests from curl sometimes receive `RST`, rather than `FIN`, after curl sends `FIN`.  This seems to happen when setting `HttpContext.Response.ContentLength` and writing to `HttpContext.Response.Body` (and possibly `BodyWriter`).  This is unexpected in a success scenario.

### Expected Behavior

In the absence of a fault, the appropriate response to a client `FIN` is a server `FIN`.

### Steps To Reproduce

My client is `curl 7.81.0 (x86_64-pc-linux-gnu)` on `Ubuntu 22.04.1 LTS`.
My server is `dotnet 8.0.100-preview.7.23355.1` on `Win11 22H2`.

To create the server, run `dotnet new api` and re place the contexts of Program.cs:
```csharp
using System.Text;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseKestrel(serverOptions => {
    serverOptions.ListenAnyIP(5293);
});

var app = builder.Build();

app.UseRouting();

const string payloadText = """
html {
  font-size: 14px;
}

@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}

.btn:focus, .btn:active:focus, .btn-link.nav-link:focus, .form-control:focus, .form-check-input:focus {
  box-shadow: 0 0 0 0.1rem white, 0 0 0 0.25rem #258cfb;
}

html {
  position: relative;
  min-height: 100%;
}

body {
  margin-bottom: 60px;
}
""";

var payloadBytes = Encoding.UTF8.GetBytes(payloadText);

app.Map("rst1", async (HttpContext context) => {
    context.Response.ContentLength = payloadBytes.Length;
    await context.Response.Body.WriteAsync(payloadBytes);
});

app.Map("fin1", async (HttpContext context) => {
    // context.Response.ContentLength = payloadBytes.Length;
    await context.Response.Body.WriteAsync(payloadBytes);

});

app.Map("rst2", async (HttpContext context) => {
    context.Response.ContentLength = payloadBytes.Length;
    await context.Response.BodyWriter.WriteAsync(payloadBytes);
    await context.Response.BodyWriter.FlushAsync();
});

app.Map("fin2", async (HttpContext context) => {
    // context.Response.ContentLength = payloadBytes.Length;
    await context.Response.BodyWriter.WriteAsync(payloadBytes);
    await context.Response.BodyWriter.FlushAsync();

});

app.Run();
```

In WireShark, observe the conversations for a curl request to each route.

Expected: No `RST`s.
Actual: `RST`s for `rst1` (content-length / Body) and `rst2` (content-length / BodyWriter), but not for `fin1` (chunked / Body) or `fin2` (chunked / BodyWriter).

### .NET Version

8.0.100-preview.7.23355.1

**Comment by amcasey** [comment]
@Tratcher and I were seeing slightly different behavior in 7.0 - BodyWriter didn't (consistently?) send `RST` and Body seemed to (sometimes?) send both `FIN` and `RST`.

**Comment by Tratcher** [comment]
Variants to test:
- Content-Length vs Chunked: we know the response is finished sooner when we know the expected length, we may receive a FIN after the response but before the middleware exits.
- BodyWriter.CompleteAsync() vs FlushAsync()

**Comment by amcasey** [comment]
https://github.com/dotnet/aspnetcore/issues/17840 seems tangentially related.

**Comment by Tratcher** [comment]
I'm not able to reproduce this issue. @amcasey let's go over it again together when we get a chance.

**Comment by amcasey** [comment]
No one else has seen this.  I'm going to consider it an artifact of my WSL setup.
