### ISSUE TITLE
Blazor .NET to JS interop never returning data back

### ISSUE THREAD

**Issue by jonmill** [dotnet/aspnetcore#49230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm attempting to write a Blazor Server app to use Fido2 authentication. I have C# code (provided below) to create the Fido2 challenge, send to the JS front-end, and then JS code to call the correct `navigator.credentials` call (also below). When attempting to return the results of the call back to .NET, I see the websocket call go out on the network but the server never reacts. I have enabled `break on all exceptions` and put the code in try-catch with no exceptions, nothing. 

The C# code requires the following packages
```XML
<PackageReference Include="Fido2" Version="3.0.1" />
<PackageReference Include="Fido2.AspNet" Version="3.0.1" />
<PackageReference Include="Fido2.Models" Version="3.0.1" />
```

The JS requires a page with two textboxes and submit button to put into the `GetUserRegistrationChallengeRequest` model.

```C#
public record GetUserRegistrationChallengeRequest
{
     public string Email { get; set; }
     public string DisplayName { get; set; }
}

public async Task GetUserRegistrationChallenge(GetUserRegistrationChallengeRequest request)
{
        string normalized = request.Email.ToLowerInvariant();

        try
        {
            Fido2User fidoUser = new Fido2User()
            {
                DisplayName = request.DisplayName,
                Name = normalized,
                Id = System.Text.Encoding.UTF8.GetBytes(normalized),
            };
            AuthenticationExtensionsClientInputs exts = new AuthenticationExtensionsClientInputs();
            CredentialCreateOptions options = fido.RequestNewCredential(fidoUser, new List<PublicKeyCredentialDescriptor>(), exts);
            string challenge = Convert.ToBase64String(options.Challenge);
            _options = options;

            string obj;
                IEnumerable<int> algs = options.PubKeyCredParams.Select(a => (int)a.Alg);
                obj = await JS.InvokeAsync<string>(
                    "registerFido",
                    TimeSpan.FromMinutes(1),
                    algs,
                    challenge,
                    options.Rp.Name,
                    normalized,
                    options.Rp.Id,
                    options.Timeout);
                Console.WriteLine($"{obj}");
        }
        catch (Exception ex)
        {
             Console.WriteLine($"{ex}");
        }
}
```

```JS
<script>
        window.bytesToBase64 = (bytes) => {
            const binString = Array.from(bytes, (x) => String.fromCodePoint(x)).join("");
            return btoa(binString);
        };
        window.registerFido = async (alg, challenge, name, email, id, timeout) => {
            const enc = new TextEncoder();
            const arr = new Uint8Array(challenge);
            const algs = alg.map(a => {
                return { alg: a, type: 'public-key' };
            });
            const opts = {
                publicKey: {
                    challenge: arr,
                    pubKeyCredParams: algs,
                    attestation: 'indirect',
                    timeout: timeout,
                    rp: { id: id, name: name },
                    user: {
                        displayName: name,
                        name: name,
                        id: enc.encode(email),
                    }
                }
            };
            const res = await navigator.credentials.create(opts).then(creds => creds, regErr => {
                console.error(regErr);
                return regErr;
            });

            return {
                email: email,
                id: res?.id ?? '',
                rawId: window.bytesToBase64(new Uint8Array(res?.rawId)) ?? '',
                attestation: window.bytesToBase64(new Uint8Array(res?.response?.attestationObject)) ?? '',
                clientData: window.bytesToBase64(new Uint8Array(res?.response?.clientDataJSON)) ?? '',
            };
        };
    </script>
```

### Expected Behavior

The expected behavior is the JS function will return the serialized object back to the .NET code for use, per [the documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0)

### Steps To Reproduce

Repro: https://github.com/jonmill/blazor_test

### .NET Version

7.0.107

### Anything else?

.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.107 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by ScarletKuro** [comment]
Hello!

I believe the issue lies with the usage of `GetAwaiter().GetResult()`, specifically in this code snippet:

```csharp
private void OnFinish(EditContext editContext)
{
    GetUserRegistrationChallengeResponse response = GetUserRegistrationChallenge(new GetUserRegistrationChallengeRequest()
    {
        Email = loginModel.Email,
        DisplayName = "Bob",
    }).GetAwaiter().GetResult();

    Console.WriteLine("Done Finish func");
}
```

Is there a specific reason you are using `GetAwaiter().GetResult()` instead of using `await` properly? Since `OnFinish` is an `EventCallback<EditContext>` that supports `Task`, you can modify your code as follows:

```csharp
private async Task OnFinish(EditContext editContext)
{
    GetUserRegistrationChallengeResponse response = await GetUserRegistrationChallenge(new GetUserRegistrationChallengeRequest()
    {
        Email = loginModel.Email,
        DisplayName = "Bob",
    });

    Console.WriteLine(response);
}
```

With this change, I'm receiving the response just as expected:

```
GetUserRegistrationChallengeResponse { AttestationType = 0, PartyId = , Name = , Algorithm = 0, Timeout = 0, Challenge =  }
```

**Comment by jonmill** [comment]
Ah that was it, fascinating! Thank you! I didn't know I could make OnFinished async, so I was using the awaiter. Thanks for the info, that fixed it!
