### ISSUE TITLE
GET request with Content-Type multipart/form-data causes validation error

### ISSUE THREAD

**Issue by sipsorcery** [dotnet/aspnetcore#49252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This error occurred in a production environment when a customer started getting 400 error responses to one of our web api methods after swtiching to a different host with an updated asp.net version.

The web api method being called was a simple anonymous GET method and the problem occurred because it was being called with the `Content-Type` header set to `multipart/form-data`. If the header is not present the web api call works correctly.

### Expected Behavior

The Content-Type header should be ignored for GET requests and the request processing should make it beyond the asp.net middleware to the applciation logic.

### Steps To Reproduce

Create a GET web api method that takes a parameter:

```
[HttpGet("echo/{name}")]
public JsonResult Echo(string name)
{
	return new JsonResult(name);
}
```

Attempt to call them the Content-Type header set.

```
curl https://localhost:44323/api/v1/metadata/echo/alice --header "Content-Type: multipart/form-data"
{"errors":{"":["Failed to read the request form. Missing content-type boundary."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-0ff750e47f23450212b41c6dfa578e10-d228484cb14a1852-00"}
```

### .NET Version

7.0.101

**Comment by Tratcher** [comment]
The request really is invalid, it said it had a multipart form and it didn't.

We don't special case things like GET because there are many methods to consider and the spec is super ambiguous about if some of them can have a body. E.g. it says that the semantics of a GET request with a body are undefined, not that it must not have one.

A more graceful solution in this case would be for the multipart reader to allow an empty body and return an empty form.

**Comment by sipsorcery** [comment]
I tend to agree that the problem is the incorrect use of the header the more concerning issue is why the behaviour changed.

I haven't tracked down exactly which version the change happened but now we're in the position of not knowing which customer API calls are going to break because they are inadvertently setting a Content-Type header on a GET.

It seems like an easy solution for us would be to use a middleware step to strip out any Content-Type headers for GETs.
