### ISSUE TITLE
Incorrect Resolution of Query Parameter in ASP.NET Core (.NET 7)

### ISSUE THREAD

**Issue by dpozimski** [dotnet/aspnetcore#49255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dear ASP.NET Core Team,

I would like to report a bug related to the resolution of query parameters in ASP.NET Core (.NET 7). When calling the app using a GET request with a specific URL, the query parameter some_id is being resolved incorrectly, resulting in unexpected behavior.

### Expected Behavior

The some_id query parameter value should be resolved to "somevalue" by default model binder.

### Steps To Reproduce

1. Clone repo https://github.com/dpozimski/model-binder-aspnet7-issue
2. Run the app.
3. Call the api through web browser using GET request & URL:
http://localhost:5047/WeatherForecast/test/extraroutevalue?some%5fid=somevalue%26otherParam=otherParamValue
4. Application returns "somevalue&otherParam=otherParamValue". The expected response content is "somevalue".

### .NET Version

7.0.302

**Comment by dpozimski** [comment]
I resolved the issue by decoding the incoming request as soon as possible using middleware.

`public class UrlDecodeMiddleware
{
    private readonly RequestDelegate _next;

    public UrlDecodeMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        context.Request.Path = WebUtility.UrlDecode(context.Request.Path);
        context.Request.QueryString = new QueryString(WebUtility.UrlDecode(context.Request.QueryString.Value));
        await _next(context);
    }
}`

**Comment by Tratcher** [comment]
This is behaving as expected, `&` should only be escaped in the query when it's part of a value. Unilaterally un-escaping everything creates ambiguity about escaped separators used within values and makes you subject to normalization attacks.
