### ISSUE TITLE
[Discussion] 3.0 - Removing Microsoft.AspNetCore.Mvc.WebApiCompatShim

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#4926]
The Microsoft.AspNetCore.Mvc.WebApiCompatShim (WebApiCompatShim) package provides partial compatibility in ASP.NET Core with ASP.NET Web API 2 to simplify migrating existing Web API implementations to ASP.NET Core. However, apps using the WebApiCompatShim do not benefit from the API related features shipping in recent ASP.NET Core releases, such as improved Open API Spec genertaion, standardized error handling, and client code generation. To better focus our API efforts in 3.0, we plan to remove WebApiCompatShim. We recommend that existing applications using the WebApiCompatShim migrate to the newer `[ApiController]` model.

**Comment by synesthesia** [comment]
At present AFAIK  the DurableOrchestrationClient in Azure Durable Functions needs to take an HttpRequestMessage, so when writing in Functions v 2 you need the shim:

```
[FunctionName("MyStarter")]
public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequest req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            ILogger log)
{
    // Function input comes from the request content.

    string name = req.Query["name"];
    var requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    string instanceId = await starter.StartNewAsync("MyOrchestration", name);

    log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

    var shim = new HttpRequestMessageFeature(req.HttpContext);
    var httpRequestMessage = shim.HttpRequestMessage;
    return starter.CreateCheckStatusResponse(httpRequestMessage, instanceId);
}
```

So please at the very least co-ordinate this change with other Microsoft teams :)

**Comment by pranavkm** [comment]
@synesthesia WebJobs is not built on ASP.NET Core Mvc, consequently removing this shim should not affect Durable Functions. Are you seeing otherwise?

**Comment by synesthesia** [comment]
@pranavkm apologies for late reply. What I have since realised is that regardless of the starter code created by VS, we can choose for the function to take either a `HttpRequestMessage` or  a `HttpRequest` and the runtime injects the correct object...

**Comment by deckertron9000** [comment]
@pranavkm A project I'm working on is currently using WebApiOverloadingApplicationModelConvention and WebApiParameterConventionsApplicationModelConvention as MVC options. Are those options supported in any way by AspNetCore.MVC without the use of the compat shim? If so is it documented somewhere?

**Comment by pranavkm** [comment]
@deckertron9000 for 3.0 the actual types aren't available. However we very rarely changed these types. You could very well copy the code from our 2.2 branches in to your application and they should work:

* https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.WebApiCompatShim/src/Conventions/WebApiOverloadingApplicationModelConvention.cs
* https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.WebApiCompatShim/src/Conventions/WebApiParameterConventionsApplicationModelConvention.cs

Feel free to open a new issue if you have run in to issues with these conventions, we'd be happy to help.

**Comment by ericsampson** [comment]
@pranavkm or anyone have an update on the status/plans for this?

**Comment by rynowak** [comment]
> @pranavkm or anyone have an update on the status/plans for this?

There's no real update other than to say that we stopped shipping this package as of 3.0 as planned and discussed here. (2.2 is the last version)

We didn't get significant demand to mainline any of the features from the shim, and so nothing was done.
