### ISSUE TITLE
[Blazor] Have a way to configure dotnet runtime for blazor apps

### ISSUE THREAD

**Issue by maraf** [dotnet/aspnetcore#49264]
Current JavaScript runtime API allows to configure various parameters. We should have a way to allow Blazor users to leverage them.

Some of the features are currently configurable through MSBuild (and boot config).

Should we allow Blazor users to interact with JavaScript runtime API directly? aka make `dotnet` builder visible on Blazor JavaScript api?
Should we have MSBuild (and boot config) alternative for every configuration that is possible in JavaScript api?

**Comment by maraf** [comment]
cc @MackinnonBuck @javiercn @pavelsavara

**Comment by pavelsavara** [comment]
I prefer JS API

**Comment by javiercn** [comment]
@maraf do we have a list?

**Comment by pavelsavara** [comment]
We have the API, I don't want to duplicate that API as msbuild properties.

**Comment by maraf** [comment]
> @maraf do we have a list?

It's not a complete list, but it includes. For some of them we already have MSBuild properties/items.

- startupMemoryCache (MSBuild property)
- workingDirectory
- environmentVariables
- diagnosticTracing
- debugLevel (MSBuild property for Blazor case)
- applicationArguments
- runtimeOptions (MSBuild items)
  - mostly jiterpreter https://github.com/dotnet/runtime/blob/main/src/mono/mono/utils/options-def.h
- browserProfilerOptions
  - enable browser profiler
- aotProfilerOptions
  - where to store AOT profile data
- pthreadPoolSize

> We have the API, I don't want to duplicate that API as msbuild properties.

I think that for vanilla wasm app, it's okay to configure the runtime in JS, because you have to deal with the runtime JS anyway. In Blazor, users typically don't have deal with the platform startup. In general I would say that having an MSBuild way to define "everything" that is in the MonoConfig/MonoConfigInternal is benefitial.

**Comment by maraf** [comment]
@javiercn Yes, to modifying runtime options

```diff
export interface WebAssemblyStartOptions {
  loadBootResource(type: WebAssemblyBootResourceType, name: string, defaultUri: string, integrity: string): string | Promise<Response> | null | undefined;
  environment?: string;
  applicationCulture?: string;
+  configureRuntime(builder: DotnetHostBuilder): void;
}
```

Second part to that is exposing running instance API, so that users can call `setModuleImports`, `getAssemblyExports`, etc

```diff
export const Blazor: IBlazor = {
  navigateTo,
  registerCustomEventType,
  rootComponents: RootComponentsFunctions,
+  runtime: RuntimeAPI,

  _internal: {
    navigationManager: navigationManagerInternalFunctions,
    domWrapper: domFunctions,
    Virtualize,
    PageTitle,
    InputFile,
    NavigationLock,
    getJSDataStreamChunk: getNextChunk,
    attachWebRendererInterop,
  },
};
```

@pavelsavara Blazor users can't use JSImport/JSExport currently, because there is not way to set imports or get exports, right?

**Comment by pavelsavara** [comment]
they could use JSImport with ES6 module. 

They could also obtain the runtime by `globalThis.getDotnetRuntime(0)` for both export/import, that's what we [documented](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0#call-net-from-javascript).

Adding `runtime` to `IBlazor` is better. 👍 

Note: `globalThis.Blazor` is singleton. Meaning you can't have multiple runtimes/blazors right now.

**Comment by mkArtakMSFT** [comment]
@maraf , @pavelsavara leaving this in RC1 for you guys to handle.

**Comment by mkArtakMSFT** [comment]
@maraf is this resolved by https://github.com/dotnet/aspnetcore/pull/49385 ?

**Comment by maraf** [comment]
No, I'll file a separate PR
