### ISSUE TITLE
IActionResult and IAsyncDisposable

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/aspnetcore#49266]
I came across this nasty problem in our codebase involving WebSocket code and am cleaning it up.

The cleanup would be easy if this works:

````
public class MyCustomAction : IActionResult, IAsyncDisposable {
     public MyCustomAction(...) { /* a few lines of code */

    public Task ExecuteAsync(ActionContext context) {
        /* ten thousand lines of code */
    }

    public ValueTask DisposeAsync() {
        /* One line of code */
    }
}
````

The documentation is not clear and normal descent through the codebase doesn't work because of heavy use of reflection.

I suppose I could do:

````
public class MyActionWrapper : IActionResult {
    private IActionResult result;
    public MyActionWrapper(IActionResult result) { this.result = result; }
    public async Task ExecuteAsync(ActionContext context) {
        try { return await result.ExecutAsync(context); }
        finally { await ((IAsyncDisposable)result).DisposeAsync(); }
    }
}
````

But again it's not clear if this works or not because it's impossible to tell if an IActionResult returned to asp.net core executes immediately or if there's a case where it does not execute.

**Comment by mitchdenny** [comment]
I'm not entirely sure what the issue is that you are describing?

**Comment by mitchdenny** [comment]
Are you asking whether we call `Dispose(...)` or `DisposeAsync(...)` on your custom defined `IActionResult` - the answer is no.

**Comment by jhudsoncedaron** [comment]
@mitchdenny : Probing determined it does not. It's not really clear if this is an oversight or design choice. Either way, an `IActionResult` that needs to ensure cleanup happens (in order to unroot other objects) seems to be a hard problem.

**Comment by javiercn** [comment]
@jhudsoncedaron thanks for contacting us.

You can use `httpContext.Response.RegisterForDispose(Async)` to make sure anything you use in the result implementation is disposed at the end of the request.

**Comment by jhudsoncedaron** [comment]
I can't tell if I should have found it from the docs or if I need to refile as a docs issue. Any guesses?
