### ISSUE TITLE
StreamRendering(true) isn't working w/default Blazor Web App template

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#49283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having the latest .NET 8 (Preview 5), updated latest VS Preview, and choosing Blazor Web App template, and run without debugging with no changes to the template, and going to /showdata page, it doesn't display Loading... and nothing shows up(white blank page), just browser-loading spinner on chrome tab for a second (the await Task.Delay(1000)).

### Expected Behavior

I expect the attribute StreamRendering(true) to be able to render the HTML immediately, and not have to wait for the data (here the task.delay) to load.

### Steps To Reproduce

https://github.com/DM-98/BlazorApp2

1. Choose template "Blazor Web App"
2. CTRL + F5
3. Click on navigation "Fetch data" - also here it takes 1 second to even load the html 

### .NET Version

8.0.100-preview.5.23303.2

### Anything else?

Visual Studio Community 64-bit Preview (Version 17.7.0 Preview 2.0).

dotnet info output:
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d

.NET SDKs installed:
  7.0.304 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by davidfowl** [comment]
Does it work from the command line?

**Comment by DM-98** [comment]
@davidfowl No, same issue

**Comment by DM-98** [comment]
@davidfowl Wait, I thought you meant "dotnet new blazor" in commandline, but I also then just tried "dotnet run" and it works as expected, from commandline.

**Comment by davidfowl** [comment]
Yep! This is a known issue with browser link and streaming rendering

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @DM-98. Until this is resolved, you'll have to disable CSS hot reload for this feature to work correctly.

**Comment by ynnob** [comment]
Just a little note:
Deactivating hot reload in the VS IDE (Settings) did not work for me. 
Starting the Blazor App via CLI however seems to work:
`dotnet watch --no-hot-reload`

**Comment by DM-98** [comment]
> Thanks for reaching out, @DM-98. Until this is resolved, you'll have to disable CSS hot reload for this feature to work correctly.

Disabling CSS Hot Reload works, thanks.

**Comment by crazedVic** [comment]
on preview 6, works fine in Edge, have to disable hot reload for Chrome to work.
