### ISSUE TITLE
Getting routevalues for any url

### ISSUE THREAD

**Issue by albert1355** [dotnet/aspnetcore#49290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have a big problem that should be very common actually: We have an URL like /en/hellofriend/123?bla=strs1 that we receive from an external API or customer or user. This URL is on our server but how are we supposed to figure out which controller, action and language or params are actually responsible for handling this url? We would have to reverse engineer the entire aspnet core routing algorithm just to know what route values would generate this url. It gets worse, we have custom IActionModelConvention implementations that generate urls in a non-standard way. All supported by the aspnet core framework of course but this means that we are very far from being able to simply say "well /hellofriend/ is the controller because it's the first path segment" or "well, just regex parse the url and kinda reimplement the query param parsing that the framework is doing. But of course that wouldn't be enough either because we have custom model binders that transform and change params before they arrive in an actionmethod.

The LinkGenerator/UrlHelper allow us to generate text urls from routevalues, we just really need the opposite as well: Generating routevalues from text urls. Often urls arrive on our server and we want to change some parts of the url and regenerate e.g with a different language but the different language url is not just a /en/ -> /pr/ switch, no the routing framework and aspnet core's rich featureset allows us to generate entirely different urls just because one routevalue is different. 

### Describe the solution you'd like

A simple to use class called something like RouteValuesGenerator and then it has a method .GetValuesByUrl(string url), directly analogous to the LinkGenerator.

### Additional context

[This issue](https://github.com/dotnet/aspnetcore/issues/34916) is related but we don't need these exact classes to be public. You can keep them private, it's not a problem for us. But we do need some kind of solution for generating routevalues for urls. 

Why is this issue a big problem? Because we currently use reflection to get to these private classes and that's very easy to break in any kind of update that you do in the aspnet core framework.

**Comment by javiercn** [comment]
@albert1355 thanks for contacting us.

> A simple to use class called something like RouteValuesGenerator and then it has a method .GetValuesByUrl(string url), directly analogous to the LinkGenerator.

You are describing route matching.

There are several challenges with this. 
* To start with, route matching and link generation don't have to be symmetrical. That is, the route that matches a URL does not need to be (and in many cases isn't) the one that generates links for it. 
* Multiple routes might produce the same string as part of generating a link, with different values.

The answer that you are trying to produce (what route values are for this URL) is ambiguous in general, and its not something we are planning to provide out of the box.

If you want to implement your own logic, there are several places you might look:
* Endpoints are generally `RouteEndpoint` instances, and those expose a `RoutePattern` which has all the info from a parsed route as Routing understands it.
* You can get to the list of endpoints for the app by injecting an `EndpointDataSource` instance.
* There is also `TemplateMatcher` which you can then use to provide a path and extract route values from it.

With those things, I believe you should be able to implement whatever you are looking for. Now it's up to you to decide how do you disambiguate between routes.

**Comment by iwibrunnbauer** [comment]
@javiercn I tried the TemplateMatcher and it doesn't do everything that the aspnet core routing framework does, therefore we can never be sure which of the many matching routes we should pick. It does not apply all of: IActionConstraint, IRouteConstraint and  IActionModelConvention and then give a best match back via the DfaMatcher same as aspnetcore.  It has to be exactly the same as what aspnet core does or the user will land on an entirely different url. Therefore it will never be good enough to do our own thing.

>The answer that you are trying to produce (what route values are for this URL) is ambiguous in general, and its not something we are planning to provide out of the box.

RouteValuesGenerator.GetValuesByUrl() was just a suggestion, if it's ever ambiguous then you can give us all the matches back and report back that it was ambiguous. We really just need what aspnetcore already internally exposed to us publically. This isn't even necessarily for us specifically, everyone is going to need this. There are many stackoverflow questions about this exact need and they never had an actual solution:

https://stackoverflow.com/questions/45045745/how-to-get-route-values-for-any-url-in-asp-net-core
https://stackoverflow.com/questions/40125980/path-to-routevaluedictionary-in-asp-net-core

^
as you can see, the commentator complains about the exact same thing as I do, this is not just a problem for us. This has been a problem for many years.
> "This would not work with attribute based routing and would require to somehow get a hold of all currently active routing template deep in your codebase"

I really tried it with the TemplateMatcher approach, I copied all the internal classes like InternalRoutePatternMatcher, LinkParser, DataSourceDependentCache and many more and debugged through what the TemplateMatcher does and tried to find the right route match for our application urls but it just doesn't work. It ignores too many features of the aspnet core routing. We will always get ambiguous results that way. The extra work that the DfaMatcher stuff does significantly changes which route gets picked and therefore which route values should be generated.

**Comment by albert1355** [comment]
@javiercn I tried the TemplateMatcher and it doesn't do everything that the aspnet core routing framework does, therefore we can never be sure which of the many matching routes we should pick. It does not apply all of: IActionConstraint, IRouteConstraint and IActionModelConvention and then give a best match back via the DfaMatcher same as aspnetcore. It has to be exactly the same as what aspnet core does or the user will land on an entirely different url. Therefore it will never be good enough to do our own thing.

>The answer that you are trying to produce (what route values are for this URL) is ambiguous in general, and its not something we are planning to provide out of the box.

RouteValuesGenerator.GetValuesByUrl() was just a suggestion, if it's ever ambiguous then you can give us all the matches back and report back that it was ambiguous. We really just need what aspnetcore already internally exposed to us publically. This isn't even necessarily for us specifically, everyone is going to need this. There are many stackoverflow questions about this exact need and they never had an actual solution:

https://stackoverflow.com/questions/45045745/how-to-get-route-values-for-any-url-in-asp-net-core
https://stackoverflow.com/questions/40125980/path-to-routevaluedictionary-in-asp-net-core

^
as you can see, the commentator complains about the exact same thing as I do, this is not just a problem for us. This has been a problem for many years.

"This would not work with attribute based routing and would require to somehow get a hold of all currently active routing template deep in your codebase"

I really tried it with the TemplateMatcher approach, I copied all the internal classes like InternalRoutePatternMatcher, LinkParser, DataSourceDependentCache and many more and debugged through what the TemplateMatcher does and tried to find the right route match for our application urls but it just doesn't work. It ignores too many features of the aspnet core routing. We will always get ambiguous results that way. The extra work that the DfaMatcher stuff does significantly changes which route gets picked and therefore which route values should be generated.
