### ISSUE TITLE
Can't configure HubOptions when calling IRazorComponentBuilder.AddServerComponents()

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#49300]
Prior to Blazor SSR, in my Blazor Server app's *Program.cs* I had a call like this that enabled me to customize the `HubOptions` instance associated with the circuit:

```csharp
services.AddServerSideBlazor()
    .AddHubOptions(options =>
    {
        options.MaximumReceiveMessageSize = 1048576;
    });
```

When using the new Blazor SSR model though, there doesn't appear to be a convenient way to do the same thing when adding support for server components:

```csharp
services.AddRazorComponents()
    .AddServerComponents(options =>
    {
        // options is CircuitOptions, not HubOptions, and there isn't a way to get to HubOptions from here
    });
```

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/49300
