### ISSUE TITLE
Inconsistent Result | [.Net Framework vs .Net Core] | Comparer<DateTime>.Default.Compare(DateTime.UtcNow, DateTime.UtcNow)

### ISSUE THREAD

**Issue by raziahmadansari** [dotnet/aspnetcore#49326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have recently migrated the code base from .Net Framework to .Net Core as a result I came across an issue wherein I was passing predicate to LINQ query which compares the date and if the date is null then it fallbacks to DateTime.UtcNow.

`
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{    
    public static void Main()
    {
        var list = new List<Structure>() { new Structure(new DateTime(2024,7,1)), new Structure(new DateTime(2023,7,1)), new Structure(new DateTime(2022,7,1)) };
        var preProcessedList = list.OrderByDescending(o => o.ProcessedFrom ?? DateTime.UtcNow);
		foreach (var structure in preProcessedList)
		{
			Console.WriteLine(structure.EffectiveFrom);
		}
    }
}

public class Structure {
    public DateTime? ProcessedFrom { get; set; }
    public DateTime EffectiveFrom { get; set; }
    public Structure(DateTime effectiveFrom){
        this.EffectiveFrom = effectiveFrom;
    }
}
` 

The same code reproduces different result in .Net FrameWork and .Net Core

Result in .Net Framework
![image](https://github.com/dotnet/aspnetcore/assets/48851944/6fcb6a18-9533-46e6-b70f-f7b63997dce5)

Result in .Net Core
![image](https://github.com/dotnet/aspnetcore/assets/48851944/5bc302e6-a7e3-4fb7-b5d1-ae9db3318ec5)

When I looked in the LINQ OrderByDescending source code found that it is using the Default Comparator of type <T>, which in this case becomes **Comparator<DateTime>.Default**

Which internally uses **Ticks** for comparison and in .Net FrameWork those _Ticks_ are getting cached but not in .Net Core as a result it is reproducing different result in both the environments.

[Sample - .Net Framework]
![image](https://github.com/dotnet/aspnetcore/assets/48851944/8a577a45-caa6-4a8b-b7b2-dc84f330fbd6)

[Sample - .Net Core]
![image](https://github.com/dotnet/aspnetcore/assets/48851944/12a2725c-c3ad-4bec-9b6d-0b876d624162)

From the attached images, we can see that in case of
.Net Framework - it is giving 0
where in case of
.Net Core - it is giving -1

And also the values against _Ticks_ are different in .Net Core.

-----------------------------------------------------------------------------------------------------------------------

Just as a HOT-FIX
If you write it like this in .Net Core it'll give the same result.
![image](https://github.com/dotnet/aspnetcore/assets/48851944/d3433835-5310-4ea3-a774-6faa01f92ffd)

**Ticks** for both the dates will become same as a result it'll produce the same result as of .Net Framwork.

### Expected Behavior

In **.Net Core** while using _DateTime.UtcNow_ in LINQ queries or inside any loop it should be consistent.

### .NET Version

.Net 6 and .Net Framework 4.7.2

**Comment by martincostello** [comment]
This issue should be filed in the dotnet/runtime repository as it is not related to ASP.NET Core.

**Comment by raziahmadansari** [comment]
> This issue should be filed in the dotnet/runtime repository as it is not related to ASP.NET Core.

Hi @martincostello , have raised the issue in _dotnet/runtime_ as mentioned.
[Inconsistent Result | [.Net Framework vs .Net Core] | Comparer<DateTime>.Default.Compare(DateTime.UtcNow, DateTime.UtcNow)](https://github.com/dotnet/runtime/issues/88654)
