### ISSUE TITLE
HttpContext.Features.Get<IFormFeature>() returns null unless HttpContext.Request.HasFormContentType is called first

### ISSUE THREAD

**Issue by reinux** [dotnet/aspnetcore#49325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`HttpContext.Features.Get<IFormFeature>` returns `null` unless `HttpContext.Request.HasFormContentType` is called first.

Someone on StackOverflow apparently noticed this two years ago as well.

### Expected Behavior

`HttpContext.Features.Get<IFormFeature>()` returns the form regardless of whether check is called first or not.

### Steps To Reproduce

Call `HttpContext.Features.Get<IFormFeature>()` without having called the check first, but in response to a valid request containing a valid form.

### Exceptions (if any)

None

### .NET Version

7.0.203

### Anything else?

https://stackoverflow.com/a/68615388

**Comment by Tratcher** [comment]
This is intentional. Answered on SO https://stackoverflow.com/a/76666158/2588374

**Comment by reinux** [comment]
Are there other problems I should be aware of if I do use Features.Get? Because the F#/Giraffe community uses it primarily, and aside from this confusion, there don't seem to be any downsides.

It's not as though Features.Get is undocumented or hidden either (aside from this strange behavior of requiring a property read first), as far as I know, so this would seem to have a tendency to mislead.

[C# guidelines](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1024-use-properties-where-appropriate?view=vs-2015&redirectedfrom=MSDN) would also suggest that properties don't have any side effects as well:

> A method is a good candidate to become a property if one of these conditions is present:
> ...
> The Get method has an observable side effect. Retrieving the value of a field does not produce any side effects.

**Comment by Tratcher** [comment]
IFormFeature is not the only lazily allocated feature. Note some of these are fallbacks in case the server does not provide an implementation.
https://github.com/dotnet/aspnetcore/blob/00fa5e14fc69294c82d8b37468f54ba92efe364c/src/Http/Http/src/Internal/DefaultHttpRequest.cs#L17-L21
https://github.com/dotnet/aspnetcore/blob/00fa5e14fc69294c82d8b37468f54ba92efe364c/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L19
https://github.com/dotnet/aspnetcore/blob/00fa5e14fc69294c82d8b37468f54ba92efe364c/src/Http/Http/src/Internal/DefaultConnectionInfo.cs#L14-L16
https://github.com/dotnet/aspnetcore/blob/00fa5e14fc69294c82d8b37468f54ba92efe364c/src/Http/Http/src/DefaultHttpContext.cs#L28-L34

Features is a simple collection of types, no brains. HttpContext is the UI on top of that used to make everything friendly. Any feature may be absent (or replaced) in the feature collection.

> also suggest that properties don't have any side effects

It's common for properties to compute values on first access and cache the result. The difference here is that you can see into the cache. While I understand the confusion that can cause, it was a specific choice to make the system more performant in cases where those features weren't used.

**Comment by reinux** [comment]
Got it. Thanks!
