### ISSUE TITLE
Generic Host Building is the complete opposite of clean code 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#49366]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generic-Host-Building-is-the-complete-op/10401682)._

---
I have this code
```
>Host.CreateDefaultBuilder(args)
>                .ConfigureAppConfiguration(configurationBuilder =>
>                {
>                    var builtConfig = configurationBuilder.Build();
>                    var azureKeyVaultUri = builtConfig["KEYVAULT_URL"];

>                    if (!string.IsNullOrEmpty(azureKeyVaultUri))
>                    {
>                        var clientId = builtConfig["CLIENT_ID"];
>                        var credential = string.IsNullOrWhiteSpace(clientId)
>                            ? (TokenCredential) new VisualStudioCredential(new VisualStudioCredentialOptions { TenantId = builtConfig["AzureTenantId"]}) 
>                            : new ManagedIdentityCredential(clientId);

>                        configurationBuilder.AddAzureKeyVault(
>                            new SecretClient(
>                                new Uri(azureKeyVaultUri),
>                                credential
>                            ),
>                            new AzureKeyVaultConfigurationOptions()
>                            {
>                                ReloadInterval = TimeSpan.FromSeconds(3000)
>                            }
>                        );
>                    }
>                })
>                .ConfigureWebHostDefaults(webBuilder =>
>                {
>                    webBuilder.UseStartup<Startup>();
>                })
>                .ConfigureLogging(logging =>
>                {
>                    logging.AddConsole();
>                    logging.AddAzureWebAppDiagnostics();
>                }
```
an it is even not possible to debug into this [Redacted](sry i am emotional).
This is not good code but really bad design and written.

How the f... i can see what is going on there?

Were does the "configurationBuilder" comes from? Were do i find the implementation of it? How do i debug to see how our configuration files (json) are read...

Never saw such a bad undreadable and obfuscated peace of code.

Kind regards Michael

---
#### Feedback Bot on 6/27/2023, 05:41 PM: 

(private comment, text removed)
#### Feedback Bot on 6/28/2023, 01:02 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mitchdenny** [comment]
Thanks for the feedback Michael. There have been a few recent evolutions to the API surface for configuring your web application which you might find quite a bit friendlier to work with. Wiring up services is a lot flatter now:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSomeServices();

var app = builder.Build();
app.MapGet("/", () => "Hello World");
```

In this case I am using minimal APIs, but you can continue to use MVC etc. Is there a reason you are using generic host?
