### ISSUE TITLE
Exception filters with ordering executing decending.

### ISSUE THREAD

**Issue by AndreyKrivcov** [dotnet/aspnetcore#49372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to the [article on microsoft](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.typefilterattribute.order?view=aspnetcore-7.0&viewFallbackFrom=net-6.0#:~:text=Gets%20the%20order%20value%20for%20determining%20the%20order%20of%20execution%20of%20filters.%20Filters%20execute%20in%20ascending%20numeric%20value%20of%20the), the filters must be executed in accending order.

When I add 3 error filters:

 ```
builder.Services.AddControllers((options) =>
            {
                options.Filters.Add(typeof(ValidationExceptionFilter), 1);
                options.Filters.Add(typeof(InvalidOperationExceptionFilter), 2);
                options.Filters.Add(typeof(CustomExceptionFilter), 3);
                options.Filters.Add(typeof(DefaultExceptionFilter), 4);
            })
```
I see that this filers executing in decending order 

- DefaultExceptionFilter - first
- CustomExceptionFilter - second
- InvalidOperationExceptionFilter - third
- ValidationExceptionFilter - the last one.

Tested on ASP dotnet core 6 and 7 

### Expected Behavior

I expect that this filers will be executed in ascending order, according to the given order: 

- ValidationExceptionFilter - first
- InvalidOperationExceptionFilter - second
- CustomExceptionFilter - third
- DefaultExceptionFilter - the last one.

### Steps To Reproduce

1. Create .net Asp .net core blank app. 
2. Create 2 or more error filters
```
class Ex1 : Exception
{
}
class Ex2 : Exception
{
}

public class ExceptionFilter1 : IExceptionFilter
{
        public void OnException(ExceptionContext context)
    {
        if (context.Exception is not Ex1 exception) return;

        var error = new ProblemDetails
        {
            Status = 400
            Title = "Filter 1",
        };

        context.Result = new BadRequestObjectResult(error)
        {
            StatusCode = error.Status
        };
        context.ExceptionHandled = true;
    }
}

public class ExceptionFilter2 : IExceptionFilter
{
        public void OnException(ExceptionContext context)
    {
        if (context.Exception is not Ex2 exception) return;

        var error = new ProblemDetails
        {
            Status = 400
            Title = "Filter 2",
        };

        context.Result = new BadRequestObjectResult(error)
        {
            StatusCode = error.Status
        };
        context.ExceptionHandled = true;
    }
}

public class DefaultExceptionFilter : IExceptionFilter
{
        public void OnException(ExceptionContext context)
    {
        var error = new ProblemDetails
        {
            Status = 400
            Title = "Default filter",
        };

        context.Result = new BadRequestObjectResult(error)
        {
            StatusCode = error.Status
        };
        context.ExceptionHandled = true;
    }
}
```
3. Add controllers and specify filers in Program.cs.
 ```
builder.Services.AddControllers((options) =>
            {
                options.Filters.Add(typeof(ExceptionFilter1), 1);
                options.Filters.Add(typeof(ExceptionFilter2), 2);
                options.Filters.Add(typeof(DefaultExceptionFilter), 3);
            })
```
4. Try to throw any error (or Ex1 or Ex2) from test endpoint, and you will see that you will always get message with Title = "Default filter".
5. Change order in the filters:
 ```
builder.Services.AddControllers((options) =>
            {
                options.Filters.Add(typeof(ExceptionFilter1), 3);
                options.Filters.Add(typeof(ExceptionFilter2), 2);
                options.Filters.Add(typeof(DefaultExceptionFilter), 1);
            })
```
6. Now repeat step 4 again and you wil see correct message in response 

- When you will throw Ex1, message will be "Filter 1" 
- When you will throw Ex2, message will be "Filter 2".

So the filters works not Accending (like it is written in documentation (https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.typefilterattribute.order?view=aspnetcore-7.0&viewFallbackFrom=net-6.0)) but Decending.

### Exceptions (if any)

-

### .NET Version

6, 7

### Anything else?

-

**Comment by AndreyKrivcov** [comment]
Forgot to add, tested on Linux Debian 11, windows not tested.

**Comment by martincostello** [comment]
I believe what might be happening here is that you're encountering the behaviour that exception filters run in reverse order due to the way they wrap the execution in the request pipeline.

There's more details about how ordering is determined here: https://learn.microsoft.com/aspnet/core/mvc/controllers/filters #filter-scopes-and-order-of-execution

The documentation you linked to was specific to TypeFilter so might not apply to an exception filter.
