### ISSUE TITLE
Request Delegate Generator fails to compile code with CS8601 warning for required non-nullable record parameters

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#49381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Where a Minimal API endpoint uses a type that uses the `ValueTask<T> BindAsync(HttpContext)` pattern to resolve an `[AsParameters]` parameter that uses a non-nullable type, the compilation fails with `CS8601: Possible null reference assignment`.

That might not be _quite_ the pattern of things that trigger this bug, but it's the thing that's "different" about this application's use of Minimal APIs compared to others where I've tested RDG so far.

### Expected Behavior

The application compiles and the endpoint behaves as if it were compiled at runtime.

### Steps To Reproduce

1. Clone https://github.com/martincostello/dotnet-minimal-api-integration-testing/commit/b0030a8a58a8b45586c744eae065da3d67505c96
2. Run `build.ps1`

### .NET Version

8.0.100-preview.6.23330.14

**Comment by mitchdenny** [comment]
Thanks Martin - will take a look at this!

**Comment by mitchdenny** [comment]
Possibly but I haven't had a chance to check.
