### ISSUE TITLE
Add an API to tell you the current render mode

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#49401]
There are multiple rendering platforms/environments:

 * WebAssembly
 * Server
 * SSR/prerendering
 * WebView
 * Anything else (bUnit, custom renderers, etc.)

We've resisted having an API that literally just tells you which one is currently in effect, reasoning that components should be agnostic to this and only vary their behavior indirectly, e.g.:

 * Is an HTTP context available? Find out by calling `serviceProvider.GetService<IHttpContextAccessor>()`
 * Is a JavaScript runtime reachable? Only do JS interop inside `OnAfterRenderAsync`, and then it won't execute if not.

### What's changing?

With .NET 8, people will be writing a lot more code that's specialized to SSR. The actual UX of a component may frequently vary based on this. For example, you might choose to render some buttons in a greyed-out way for SSR/prerendering, and then light up if the component becomes interactive. Or you might render completely different UI given the restrictions of noninteractivity (reducing something to a basic HTML form that can be posted). There isn't currently a sensible way to vary UX based on whether interactivity is available; you just have to somehow know.

In the framework we also have reasons to distinguish. For example, `InputBase` wants to emit field names in SSR cases and not otherwise. Currently we distinguish based on the presence of a `FormMappingContext`, but that's a weak approximation and sometimes incorrect, since a `FormMappingContext` could also be present in interactive components if the developer has put one there to make a form also work in SSR mode.

### Proposal

I'd recommend something modelled on how .NET reports the current OS platform as a string (making it extensible) and has helpful extension methods to identify specific ones in a strongly-typed way. The main difference though is we can't have a `static` API for this since it may vary within a single process. So:

 * There would be a type like `class M.A.Components.ComponentPlatform(string PlatformName, bool Interactive)`
 * `Renderer` would have `ComponentPlatform Platform { get; }` configured during the hosting environment startup
 * `RenderHandle` would have `ComponentPlatform Platform => _renderer.Platform`
 * `ComponentBase` would have `ComponentPlatform Platform => _renderHandle.Platform`
 * There would be extension methods like `Platform.IsStaticServer()`,  `Platform.IsInteractiveServer()`, `Platform.IsWebAssembly()`,  `Platform.IsWebView()`, `Platform.IsInteractive()`, ....
   * These could be defined within libraries that know about specific platform name strings (e.g., the WebView one can go in `M.A.C.WebView`, likewise for any custom hosting platforms).

I specifically do **not** propose we solve this with some kind of cascading parameter. We have to be careful about overusing them because they impose a cost of `O(component depth)` to every `[CascadingParameter]` declaration. In particular, adding these to `InputBase` is not good given how apps may have UI with many hundreds of input fields at once (e.g., in an editable grid). We should try to reserve use of `[CascadingParameter]` for application code and only use it in the framework in situations where we think only a small number of instances of the consumer will make sense to be used.

Likewise, I don't propose we solve this with a DI service. That again comes at a per-consumption cost. It's likely somewhat cheaper than `CascadingParameter` (should be pretty much a single dictionary lookup) but still is a lot more machinery than we need for this.

### Update: Also offer a way to find the rendermode

Besides knowing the current environment, it may be desirable to know the rendermode. That way even if you're currently prerendering (e.g., `Platform.IsStaticServer()`), you can find out whether the component is scheduled to become interactive later, because it has a nonnull rendermode or is inheriting one from further up the hierarchy. You might want to change the actual shape of the render output based on whether you expect interactive buttons to light up in a moment.

### Alternatives

Haven't really thought through the pros/cons, but instead of the platform being defined through a string name with extension methods to identify it, it could potentially be a type hierarchy. That would allow subclasses to provide extra custom information, while still adding extension methods on the root type that would try downcasting to the subclass they know about.

Not sure whether this is desirable or would even practically be useful. We don't consider "custom hosting models" to be a common use case, and the hosting model would be the thing constructing the instance, so it wouldn't really be very extensible anyway.

I was just trying to imagine scenarios like if M.A.C.WebView wants to be able to have `platform.HasWebViewFlag(FlagName ...)` which it could do by subclassing `ComponentPlatform` and then defining its own extension methods that read info from the subclass. Another possible approach would be putting a loosely-typed property bag on `ComponentPlatform`.

**Comment by marinasundstrom** [comment]
There should be APIs to determine at least what context a component is rendering in.

I have created my own ``RenderingContext`` class with properties ``IsServer``, ``IsClient``, and ``IsPrerendering``. That serves the purpose well for me since I'm not running anywhere else than in the browsers.

https://github.com/marinasundstrom/Blazor8Test/blob/main/src/Shared/RenderingContext.cs

Besides this, I'm also looking for a way to determine whether or not an interactive component has been mounted and activated in the browser so that I know when to execute the Javascript.

https://github.com/dotnet/aspnetcore/issues/49497

**Comment by SteveSandersonMS** [comment]
> I have created my own RenderingContext class with properties IsServer, IsClient, and IsPrerendering. That serves the purpose well for me since I'm not running anywhere else than in the browsers.

Sounds good! Glad to hear this is a generally useful concept.

> Besides this, I'm also looking for a way to determine whether or not an interactive component has been mounted and activated in the browser so that I know when to execute the Javascript.

Hopefully `OnAfterRenderedAsync` is suitable for that requirement.

**Comment by ladeak** [comment]
Another approach could be something like `RenderModeSelector` provided:

```xml
<RenderModeSelector>
    <PreRender>
          <MyPlaceholderComponentA>
   </PreRender>
    <WebAssembly>
          <MyComponentA>
   </WebAssembly>
</RenderModeSelector>
```
where PreRender == SSR.

**Comment by marinasundstrom** [comment]
@ladeak In my own experience, I don't see a use for this type of component. To me, it just makes the markup harder to read. 

This kind of component pattern is OK for the router, and perhaps ``ErrorBoundary``, but I wouldn't like people to abuse this component.

I'd rather see that people learn about how pre-rendering works, than for Blazor to to hide the details for them in some React-like pattern.

**Comment by ladeak** [comment]
> ```cs
> RenderingEnvironment renderingEnvironment;
> var servicesProvider = builder.Services.BuildServiceProvider();
> var isSSR = servicesProvider.GetService<IComponentPrerenderer>() is not null;
> var jsRuntime = servicesProvider.GetRequiredService<IJSRuntime>();
> ...
>```

The above suggested solution does not seem to work when I navigate with links on the page.

**Comment by danielgreen** [comment]
> For example, you might choose to render some buttons in a greyed-out way for SSR/prerendering, and then light up if the component becomes interactive.

Until this ability is available, prerendering offers a poor user experience. Even in the Counter.razor component that ships with the .NET 8 Blazor Web App template, the "Click me" button does nothing when initially prerendered, for a second or two until Web Assembly interactivity kicks in.

Is there no recommended way to mitigate it for the time being, other than disabling prerendering on the component?

**Comment by bcheung4589** [comment]
Just wanna say my RenderContext was heavily inspired by marinasundstrom. Some months ago I went through multiple public repo's to look for inspiration on how people work and to learn about Blazor 8. So credit where credit is due, @marinasundstrom <3

**Comment by AmerBakeer** [comment]
> We're moving this issue to the `.NET 9 Planning` milestone for future evaluation / consideration. 

Do we really have to wait a whole year just to determine the RenderMode that we are using in our code?

**Comment by javiercn** [comment]
```diff
namespace Microsoft.AspNetCore.Components;

public class ComponentBase
{
+  public IComponentRenderMode GetRenderMode();
+  public ComponentPlatform Platform { get; }
}

public struct RenderHandle
{
+  public IComponentRenderMode GetRenderMode();
+  public ComponentPlatform Platform { get; }
}

+public class ComponentPlatform(string platformName, bool isInteractive, IComponentRenderMode? renderMode)
+{
+   public string PlatformName { get; }
+   public bool IsInteractive { get; }
+}
```

**Comment by amcasey** [comment]
[API Review]

- Why isn't GetRenderMode a property?
    - We think it would create ambiguity with the RenderMode type, but we should confirm
    - In particular, static imports can make property names conflict with type names
    - It does do more work than one might expect a property to do
    - Could change the name
        - CurrentRenderMode (misleading)
        - TargetRenderMode (since it may not be in effect yet)
        - ComponentRenderMode
        - AssignedRenderMode (since it may not be in effect yet)
    - Resolved: make it a property - RenderMode if possible; AssignedRenderMode otherwise
- Why are we using runtime type checks, rather than an enum?
    - The RenderMode object is userful in its own right
- ComponentPlatform should be sealed
- We're not convinced the render mode has to be passed to the ComponentPlatform ctor
- RenderMode and platform are exposed separately since render mode is per-component and platform is shared
    - if (Platform.IsInteractive) { do JS interop }
- PlatformName seems redundant - could just call it Name
- Could the platform be an enum, rather than a string
    - We don't allow user extensibility
    - We do have some internal extensibility (bUnit, custom renderers, etc)
    - We could add extension methods (in the future)

**Comment by amcasey** [comment]
```diff
namespace Microsoft.AspNetCore.Components;

public class ComponentBase
{
+  public IComponentRenderMode RenderMode { get; } // Or AssignedRenderMode
+  public ComponentPlatform Platform { get; }
}

public struct RenderHandle
{
+  public IComponentRenderMode RenderMode { readonly get; } // Or AssignedRenderMode
+  public ComponentPlatform Platform { readonly get; }
}

+public sealed class ComponentPlatform(string name, bool isInteractive)
+{
+   public string Name { get; }
+   public bool IsInteractive { get; }
+}
```
