### ISSUE TITLE
Ability to programmatically perform an "enhanced page refresh"

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#49414]
_Details to be added later_

**Comment by SteveSandersonMS** [comment]
We need to consider:

 * Some extra `NavigationOptions` flag to `navigationManager.NavigateTo` that means "do a full page reload but using progressively-enhanced nav"
 * Doing a "refresh" on the current location (arguably just a special case of the one above)

**Comment by MackinnonBuck** [comment]
We should decide whether we need to introduce new APIs for this. https://github.com/dotnet/aspnetcore/pull/49768 makes it possible to do this by calling:

```csharp
NavigationManager.NavigateTo(NavigationManager.Uri, replace: true);
```

However, there still might be reasons why we need a new API:
* Simplify the line above to something less verbose, like `NavigationManager.EnhancedRefresh()`
* Trigger an enhanced page refresh even if an interactive router is present

Maybe we could add a new flag to `NavigationOptions` like `ForceEnhancedNavigation`?
