### ISSUE TITLE
Incorrect docuemntation for Html.HiddenFor: `Html.HiddenFor` will never use `value` property from `htmlAttributes` to assign value

### ISSUE THREAD

**Issue by alowdon** [dotnet/aspnetcore#49415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Re-opening https://github.com/dotnet/aspnetcore/issues/21314 as it was not resolved but is now closed for comment.

The documentation for [`Html.HelperFor`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.htmlhelper-1.hiddenfor?view=aspnetcore-6.0) explicitly states that the helper will

> add a "value" attribute to the element containing the first non-`null` value found in: the [ModelState](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actioncontext.modelstate?view=aspnetcore-6.0#microsoft-aspnetcore-mvc-actioncontext-modelstate) entry with full name, the `expression` evaluated against [Model](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.viewdatadictionary.model?view=aspnetcore-6.0#microsoft-aspnetcore-mvc-viewfeatures-viewdatadictionary-model), or the `htmlAttributes` dictionary entry with key "value".

However this is not the behaviour seen when using `Html.HelperFor` in .NET 6 (the latest LTS at time of writing). Either the behaviour should be fixed, or the documentation should be updated to avoid misleading people.

### Expected Behavior

With a model 

```csharp
public class Model
{
    public string Foo { get; set; }
}
```

calling the following in a Razor template

`Html.HelperFor(m => m.Foo, new { value = "bar" })`

should result in

`<input id="Foo" name="Foo" type="hidden" value="bar">`

### Steps To Reproduce

- Create a new ASP.NET Core MVC project
- Create a model as shown above
- Create a view using the model, including `Html.HelperFor(m => m.Foo, new { value = "bar" })`
- Return the view from a controller

The generated HTML will be

`<input id="Foo" name="Foo" type="hidden" value="">`

Note that `value=""`, but the `ModelState` and model itself should both provide `null` values, so the value should instead be taken from the `htmlAttributes` (as detailed in the documentation), but is not.

### .NET Version

6.0

**Comment by ddjerqq** [comment]
Is this being worked on? I could work on it

**Comment by bseptember** [comment]
I'd like to help correcting the documentation, @mkArtakMSFT please review.
