### ISSUE TITLE
How does 'System.Web.Http' Compiles in .NET 7 Blazor server Application

### ISSUE THREAD

**Issue by NavinAT** [dotnet/aspnetcore#49411]
`System.Web.Http` DLL compiles in .NET 7 application. I have Used `RoutePrefixAttribute` class in .NET 7 App and the solution compiled successfully, There is no warnings in the Dependencies section. Couldn't find any proper explanation of how that dll compiles. Help me to understand how it works in .NET 7 App. So can we use `System.Web` dll in .NET 7?.

![image](https://github.com/dotnet/runtime/assets/45414603/3389d632-7b9f-465b-a062-5280dfdfa0da)

![image](https://github.com/dotnet/runtime/assets/45414603/b6af4f13-286b-4152-9cc1-275ded13d812)

Reference Link: [Here..](https://learn.microsoft.com/en-us/dotnet/api/system.web?view=net-7.0)

**Comment by SteveSandersonMS** [comment]
Sorry, I don't really understand your question. It sounds like you're saying you added a reference and it compiled successfully.

Are you saying something *doesn't* work? Can you express this in a form like the following?

 * What you did
 * What you think should have happened
 * What happened instead

Thanks!

**Comment by NavinAT** [comment]
Hai @SteveSandersonMS 

We are migrating from ASP.NET Web Form to Blazor Server.
We are using this System.Web.Http (.NET Framework 4.8) Dll for REST Service in our old APP (v4.8).
After migrating to .NET 7, this dll compiles with our existing .NET Framework code.
We thought after the migration it doesn't compile with .NET 7, we would like to know the reason why it is compiled.

Please let me know, if you need more information.

**FYI:**
We referred MSDN .NET porting, [Link](https://learn.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)

![image](https://github.com/dotnet/aspnetcore/assets/45414603/9a046eaf-8fdd-482a-9611-1d2208b02faa)

https://learn.microsoft.com/en-us/dotnet/core/porting/#net-framework-compatibility-mode

![image](https://github.com/dotnet/aspnetcore/assets/45414603/1c4c840c-5062-4781-ad9f-2b22d0454dd2)

Also, we could not find this Dll in unsupported API lists

https://learn.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis

We are not Sure that we can use this Dll in .NET 7.

**Comment by SteveSandersonMS** [comment]
It sounds like you're using `System.Web.dll` via the .NET Framework compatibility mode. That may work to some extent but you should be prepared for limitations in that support. As per the [compatibility mode docs](https://learn.microsoft.com/en-us/dotnet/core/porting/#net-framework-compatibility-mode):

> Referencing .NET Framework libraries doesn't work in all cases, as it depends on which .NET Framework APIs were used and whether or not these APIs are supported by the project's target framework. Also, some of the .NET Framework APIs will only work on Windows. The .NET Framework compatibility mode unblocks many porting scenarios but you should test your projects to ensure that they also work at runtime.
