### ISSUE TITLE
Design proposal for a new QuickGridC component

### ISSUE THREAD

**Issue by Eleve2023** [dotnet/aspnetcore#49426]
##Description: 
We propose to add a new QuickGridC component to QuickGrid. This component would accept ICollection and could be bound with any provider (Linq, Entity Framework, Simple.Client.Odata) in short, any provider that accepts System.Linq.Expressions. Pagination would be independent of QuickGridC.

![Capture](https://github.com/dotnet/aspnetcore/assets/126790154/87904e34-8459-4ba9-9b2f-9d30b1f09b87)

We also propose to add options such as:
- Multi-sorting
- A native filter for the column
- An advanced native filter for the column
- Events when selecting a row in the table
- The ability to change CSS classes and CSS styles using GridHtmlCssManager that could be put in the parameter of QuickGridC (parameter name would be CssClassAndStyle)

We have deposited an  [example of code and usage](https://github.com/Eleve2023/QuickGrid/tree/example-for-aspnetcore)  on GitHub

**Comment by SteveSandersonMS** [comment]
Thanks for proposing this. This looks like it would be a great thing to publish as a NuGet package, if you're interested in owning and maintaining such a package.

**Comment by Eleve2023** [comment]
@SteveSandersonMS 
Thank you for proposing this. I am delighted that you find the concept of my project interesting.
I am thrilled to be part of the maintenance team for this package, but I would prefer that ownership of NuGet remains with the .Net platform. 
I am willing to spend my time following all the suggestions from the team and the community until the project matures. 
In the draft I submitted in #49427 in the BasicTestApp project, I added “QuickGridC Example” to see the potential of my project.

**Comment by danroth27** [comment]
We'd be willing to consider the proposed features individually for QuickGrid. If you're interested in this please open individual issues for them with proposed designs. But we don't plan to add an additional grid component alternative. We think a new component is best handled outside of the framework by the community.
