### ISSUE TITLE
Stop setting name attribute in DefaultHtmlGenerator.GenerateHiddenForCheckbox

### ISSUE THREAD

**Issue by CXuesong** [dotnet/aspnetcore#4942]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
See https://github.com/CXuesong/AspNetCoreAppTest2/blob/master/WebApplication2/Pages/Test.cshtml .

#### Description of the problem:

If I specify the `name` for `<checkbox>`, like [this](https://github.com/CXuesong/AspNetCoreAppTest2/blob/b4a609e43009c414c4a0a404b2b27d3c2f605d91/WebApplication2/Pages/Test.cshtml#L17)
```cshtml
<input type="checkbox" asp-for="Input.CheckBox" name="check" />
```
The generated hidden will still keep the default field name, i.e. `Input.CheckBox`, like this
```html
<input type="checkbox" name="check" data-val="true" data-val-required="The CheckBox field is required." id="Input_CheckBox" value="true">
...
...
<input name="Input.CheckBox" type="hidden" value="false">
```

I think the reason why a hidden is here, is to [provide "false" value for unchecked checkbox](https://stackoverflow.com/questions/2697299/asp-net-mvc-why-is-html-checkbox-generating-an-additional-hidden-input). Thus it's nonsense to generate a hidden with default field name, while we have already overridden the checkbox's `name` in razor code.

It seems that in [`InputTagHelper.GenerateCheckBox`](https://github.com/aspnet/Mvc/blob/7c6823312540c72a0579f4a4b2e8357b1df42de8/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L313), it's assumed that `GenerateHiddenForCheckbox` will return a hidden without `name` attribute, if the `Generator` won't bother to provide a non-empty fallback name. However, in [`DefaultHtmlGenerator.GenerateHiddenForCheckbox`](https://github.com/aspnet/Mvc/blob/7c6823312540c72a0579f4a4b2e8357b1df42de8/src/Microsoft.AspNetCore.Mvc.ViewFeatures/DefaultHtmlGenerator.cs#L278), the generated hidden's `name` is set to the default model name explicitly. Perhaps we need to remove this statement so that InputTagHelper.GenerateCheckBox will use the `Name` specified by the razor code.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by chrisketelaar** [comment]
This is my first ever issue so please bear with me.

I've taken a look and I see two possible options to fix this:

**First option** is to change the InputTagHelper to consider the name attribute of the checkbox as the "primary" name and not as the fallback name as the code comment suggests.

Original code
```
// hiddenForCheckboxTag always rendered after the returned element
var hiddenForCheckboxTag = Generator.GenerateHiddenForCheckbox(ViewContext, modelExplorer, For.Name);
if (hiddenForCheckboxTag != null)
{
    var renderingMode =
        output.TagMode == TagMode.SelfClosing ? TagRenderMode.SelfClosing : TagRenderMode.StartTag;
    hiddenForCheckboxTag.TagRenderMode = renderingMode;
    if (!hiddenForCheckboxTag.Attributes.ContainsKey("name") &&
        !string.IsNullOrEmpty(Name))
    {
        // The checkbox and hidden elements should have the same name attribute value. Attributes will
        // match if both are present because both have a generated value. Reach here in the special case
        // where user provided a non-empty fallback name.
        hiddenForCheckboxTag.MergeAttribute("name", Name);
    }

    if (ViewContext.FormContext.CanRenderAtEndOfForm)
    {
        ViewContext.FormContext.EndOfFormContent.Add(hiddenForCheckboxTag);
    }
    else
    {
        output.PostElement.AppendHtml(hiddenForCheckboxTag);
    }
}
``` 

Changed code
```
// hiddenForCheckboxTag always rendered after the returned element
var hiddenForCheckboxTag = Generator.GenerateHiddenForCheckbox(ViewContext, modelExplorer, For.Name);
if (hiddenForCheckboxTag != null)
{
    var renderingMode =
        output.TagMode == TagMode.SelfClosing ? TagRenderMode.SelfClosing : TagRenderMode.StartTag;
    hiddenForCheckboxTag.TagRenderMode = renderingMode;
    if (!string.IsNullOrEmpty(Name))
    {
        //The checkbox and hidden elements should have the same name attribute value.
        //Reach here in the special case where user provided a non-empty name.
        hiddenForCheckboxTag.MergeAttribute("name", Name, replaceExisting: true );
    }

    if (ViewContext.FormContext.CanRenderAtEndOfForm)
    {
        ViewContext.FormContext.EndOfFormContent.Add(hiddenForCheckboxTag);
    }
    else
    {
        output.PostElement.AppendHtml(hiddenForCheckboxTag);
    }
}
```

**Second option** is to supply, next to the expression, the name of the checkbox to the GenerateHiddenForCheckbox method and let this decide what the name is going to be.

Original code
```
public virtual TagBuilder GenerateHiddenForCheckbox(
	ViewContext viewContext,
	ModelExplorer modelExplorer,
	string expression)
{
	if (viewContext == null)
	{
		throw new ArgumentNullException(nameof(viewContext));
	}

	var tagBuilder = new TagBuilder("input");
	tagBuilder.MergeAttribute("type", GetInputTypeString(InputType.Hidden));
	tagBuilder.MergeAttribute("value", "false");
	tagBuilder.TagRenderMode = TagRenderMode.SelfClosing;

	var fullName = NameAndIdProvider.GetFullHtmlFieldName(viewContext, expression);
	if (!string.IsNullOrEmpty(fullName))
	{
		tagBuilder.MergeAttribute("name", fullName);
	}

	return tagBuilder;
}
```


Changed code
```
public virtual TagBuilder GenerateHiddenForCheckbox(
    ViewContext viewContext,
    ModelExplorer modelExplorer,
    string expression,
    string name = null)
{
    if (viewContext == null)
    {
        throw new ArgumentNullException(nameof(viewContext));
    }

    var tagBuilder = new TagBuilder("input");
    tagBuilder.MergeAttribute("type", GetInputTypeString(InputType.Hidden));
    tagBuilder.MergeAttribute("value", "false");
    tagBuilder.TagRenderMode = TagRenderMode.SelfClosing;

    if (!string.IsNullOrWhiteSpace(name))
    {
        tagBuilder.MergeAttribute("name", name);
    }
    else
    {
        var fullName = NameAndIdProvider.GetFullHtmlFieldName(viewContext, expression);
        if (!string.IsNullOrEmpty(fullName))
        {
            tagBuilder.MergeAttribute("name", fullName);
        }
    }
}    
```

**Pro's and Con's**

First options:

**Pro** is that we don't need to change the IHtmlGenerator
**Con** The GenerateHiddenForCheckbox is now (as far is I could tell) used in two places and both are applying the same logic for setting the name after the hidden checkbox is generated. Both need to be changed and kept in sync in the future (?)
(https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.TagHelpers/src/InputTagHelper.cs#L313)
(https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/HtmlHelper.cs#L724)

Of course pro's and con's for the second option are the pro's and con's for the first option, only the other way around.

@dougbu can I tag you for this?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
