### ISSUE TITLE
Leading @ should not be required in attribute value when specifying render mode using @rendermode

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49443]
Blazor doesn't require a leading `@` for attribute values if the value is already a C# context, like a component parameter. But we currently require a leading `@` when specifying a render mode using `@rendermode`, which is inconsistent.

This works: `@rendermode="@RenderMode.Server"`

This doesn't work, but it should: `@rendermode="RenderMode.Server"`

**Comment by javiercn** [comment]
@danroth27 that's just because there's no directive for it.

**Comment by mkArtakMSFT** [comment]
I believe this will be addressed by https://github.com/dotnet/razor/pull/9117
