### ISSUE TITLE
SignalR working even with API down WFT?????

### ISSUE THREAD

**Issue by Porkechebure** [dotnet/aspnetcore#49453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an angular app with signalr:
`import { Injectable } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';
import { Subject } from 'rxjs';
@Injectable({
  providedIn: 'root'
})
export class SomeAppSignalRService {
  public hubConnection: HubConnection;
  public SomeAppNotification$ = new Subject<string>();

  constructor() { }

  public startConnection = () => {
    if (!this.hubConnection) {
      this.hubConnection = new HubConnectionBuilder().withUrl('http://localhost:5215/SomeAppNotificationsHub').build();
      this.hubConnection.on('SomeAppNotification', (msg: string) => {
        this.SomeAppNotification$.next(msg);
      });
      this.hubConnection
        .start()
        .then(() => console.log('Connection started'))
        .catch(err => console.log('Error while starting connection: ' + err))
    }
  }

  public sendSomeAppNotification = (message: string) => {
    this.hubConnection.invoke('SendSomeAppNotification', message)
      .catch(err => console.error(err));
  }
}
`

I configured SignalR on .net 6 web API:

`app.MapHub<SomeAppHub>("/SomeAppNotificationsHub");`

`using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;

namespace SomeApp.SignalR
{
    [AllowAnonymous]
    public class SomeAppHub : Hub
    {
        public async Task SendSomeAppNotification(string message)
        {
            await Clients.All.SendAsync("SomeAppNotification", message);
        }
    }
}
`
and WHEN API IS OFF (closed and not running from visual studio)
SIGNALR STILL WORKS... WTF:
![image](https://github.com/dotnet/aspnetcore/assets/3466040/bc6ff1b9-dc29-44b8-8920-27c0d7d9dbfa)

WTF LOL

**Comment by davidfowl** [comment]
Resilience 😬

**Comment by Porkechebure** [comment]
> Resilience 😬

Well, since the dev itself proves not useful, lets give a sense to this thread.
You seem to be part of the new wave of devs who release relentless spaghetti code tools that don't handle exceptions properly.

Document and catch and log as exception everything.
WHen you use signalR it's a 50/50 of guess and luck to understand what the heck is going on and why this tool is not working.

It's a wave that have been propagating since the explosion of all these crappy js frameworks alla round (Angular, which sadly I'm using) being the first of all.

They just get put out with the intention of "we're experimental, we are fresh, please report bugs" and all the bad stuff is left on the users who are expected to debug for you.

Damn, while adding it I had troubles it just says "hey I can't connect to websocket, bye bye fucker, solve it by yourself".

Same thing if I purposely put the configuration url ("withUrl") on the builder HubBuilder in http instead of https to purposefully produce an error and see what it says. It's the same. Says either "Hey idiot i can't connect" or "response is empty"

Do some thoroughly testing and error catching ffs... the current state of developement world is just depressing

**Comment by martincostello** [comment]
While this might be a topic you have some passionate opinions on, please be respectful of [the code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct).

**Comment by Porkechebure** [comment]
> While this might be a topic you have some passionate opinions on, please be respectful of [the code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct).

Well, ok, but it's a fact, not a passionate opinion.
For example now I placed (following your (your as microsoft) example on MSDN here:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio

Step by step and tadahhh it doesn't work and doesn't say anything.
The web api just pass in the sendasync method and does nothing.

**Comment by Porkechebure** [comment]
@davidfowl 
Now explain this ridiculous shit (don't even tell me to behave this is straight up ridiculous).
I managed to make this thing work.
Angular frontend (not .NET angular template, a separate web app) and .NET web API

Web API:

Strongly typed hub:
`using Microsoft.AspNetCore.SignalR;

namespace SomeApp.SignalR
{
    public class SomeAppHub : Hub<ISomeAppHub>
    {
        public async Task SendSomeAppNotification(string message)
        {
            await Clients.All.SomeAppNotification(message);
        }
    }
}
`

Already configured program.cs with:
AddSignalR() and MapHub<SomeAppHub>(url)

Did a controller to test it:
`using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SomeApp.SignalR;

namespace SomeApp.Controllers
{
    [Route("api/[controller]")]
    public class SignalRTestController : Controller
    {
        private IHubContext<SomeAppHub, ISomeAppHub> _signalRService;
        public SignalRTestController(IHubContext<SomeAppHub, ISomeAppHub> signalRService)
        {
            _signalRService = signalRService;
        }

        [HttpPost]
        public async Task<IActionResult> Index(string message)
        {
            await _signalRService.Clients.All.SomeAppNotification("THIS MESSAGE COMES FROM .NET WEB API: " + message);
            return Ok();
        }
    }
}

Then I run the angular app that connects successfully to the hub and receives the message successfully whjen launched from swagger

WHY THE RANT THEN?

1. Spent hours understanding why the heck the strongly typed hub wasn't working (it was never passing from SendSomeAppNotification hub message not even with strongly typed hub or using SendAsync

Turns out that this little nasty spaghetti code needs  works only in Post???? I had [HttpGet] on  public async Task<IActionResult> Index(string message)  and replaced with [HttpPost] and  worked.

WHY? but most important of all: WHY THE FUCK YOU DON'T GIVE ANY WARNING? one spends hour trying, clueless because you didn't even put some sort of logging. The whole thing worked from angular to web api except it silently was not passing from the hub and gave no idea at all why it wasn't working.

2. Even if now it's working, it's still not passing into the SendSomeAppNotification hub method!!!!!!!!!!!!!! What the actual heck?
Why? Why? it works but hub method can't be debugged (looks like it's not even passing there)?
`

**Comment by davidfowl** [comment]
What am I explaining? Can you produce a repository with the broken code and I can take a look?

**Comment by Porkechebure** [comment]
> What am I explaining? Can you produce a repository with the broken app and I can take a look?

Lol either you have text comprehension problems or you're doing it on purpose.
THere is clearly 2 points in there in a ordered list and both of them are reproducible without any "broken app" which doesn't exist since it works, but apparently signalR has some hidden constraints and it does forces them on you without helping you understanding them with meaningful errors

**Comment by KennethHoff** [comment]
(just for future reference, please use 3 ``` ` ``` to create a code block):

```c#
public static void Log()`
```
Appending `c#` also gives syntax highlighting:

```md
```c#
public static void Log()
`` ` // remove the space.. writing Markdown in Markdown is awkward 😬
```

**Comment by danmoseley** [comment]
@Porkechebure 

> You seem to be part of the new wave of devs who release relentless spaghetti code tools that don't handle exceptions properly.
> Lol either you have text comprehension problems or you're doing it on purpose.

These comments breach our code of conduct, which amongst other things requires we treat each other with respect. We want to help you. I know it can be frustrating when something isn't working. But it's not acceptable to question the competence or motivation of others here.

**Comment by richlander** [comment]
Feel free to start a new issue with more professional language. This issue has far too much offensive language to continue.
