### ISSUE TITLE
Blazor EventCallback not being considered immutable thus making child components to be rendered again

### ISSUE THREAD

**Issue by arielmoraes** [dotnet/aspnetcore#49476]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

As stated in the comments in the `ChangeDetection` method here https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ChangeDetection.cs, the `EventCallback` should be treated as a known immutable type.

But as seen in the mentioned demo, as the parent renders (expected as it handles the event) it calls the child `SetParameters` again.

IMHO, that is a bug; in theory, the EventCallback points to the same method of the same parent instance.

Am I missing something?

### Expected Behavior

The parent component should not call SetParameters again on the child.

### Steps To Reproduce

1. Clone the repo from: https://github.com/arielmoraes/BlazorServerEventCallbackRenderDemo
2. Run the project.
3. Click the 'Child Button'
4. Watch the console for the events. The child's OnParametersSet shouldn't be called after the OnClick EventCallback was invoked.

### .NET Version

8.0 last preview

**Comment by arielmoraes** [comment]
My mistake, prior to the .net 8 the KnownTypes do not include the EventCallback check. Looking forward to the new release.

**Comment by arielmoraes** [comment]
Did a quick test using .net 8 and even with the IEventCallback check the parent is still calling SetParameters on the children. Reopening for now.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something that we've attempted in the past but it turned out to be too problematic.

You can always use the `ShouldRender` override to provide your own logic to decide if the render should happen or not.

**Comment by SteveSandersonMS** [comment]
For more info about the history here, please see https://github.com/dotnet/aspnetcore/pull/31756 and where it ran into trouble. If there was a sufficiently simple and performant solution we would consider it.

**Comment by SteveSandersonMS** [comment]
Also note that if the `EventCallback` parameter value actually remains the same object instance, it will be not cause the child to re-render. So if you changed `Index.razor` to look like the following, you'd get the behavior you want:

```razor
<ChildComponent OnClick="@myHandler"></ChildComponent>
<ChildComponent OnClick="@myHandler"></ChildComponent>

@code {
    EventCallback myHandler;

    public Index()
    {
        myHandler = new EventCallback(this, () =>
        {
            Console.WriteLine("Child Click Handled");
        });
    }

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine("Parent rendered");
    }
}
```

I know that's less convenient but is what it takes to retain the `EventCallback` instance.

**Comment by arielmoraes** [comment]
By following the issue you provided I managed to understand the root cause. 

I suppose the solution you proposed is more convenient than handling if the child component should render or not. In my case, the code became very cumbersome as I have several child components and each one has a couple of events.

In the end, I have two questions:

1. Thinking about the legion of components out there and how we normally create the handlers (by creating a method), wouldn't it be a problem if we have a relatively large render tree?
2. Why have the KnownImmutableTypes been changed to accommodate the IEventCallback interface? Was that change an attempt to solve the aforementioned problem?

Thank you.

**Comment by SteveSandersonMS** [comment]
> Thinking about the legion of components out there and how we normally create the handlers (by creating a method), wouldn't it be a problem if we have a relatively large render tree?

Each event only triggers a render in the subtree where the event is received, so even with a massive app, it would not normally be a problem. If you are going to re-render the root component in a massive hierarchy, it can be worth having subtrees that don't re-render, which happens whenever those subtrees only take parameters we can confirm as definitely immutable and the values are unchanged. If you want an EventCallback parameter to be seen as unchanged, you will have to take the extra steps shown here. But it's a relatively uncommon case.

> Why have the KnownImmutableTypes been changed to accommodate the IEventCallback interface? Was that change an attempt to solve the aforementioned problem?

Yes. If we hadn't done this, then even if you retained an `EventCallback` instance, the system would still think it might have internal mutations and hence would re-render the subtree. The change makes the system understand that if you do retain the `EventCallback` instance, it can't mutate internally and hence is safe not to force a re-render for that parameter alone.
