### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.7.23364.32] MVCBlog is crashed with exception "Unable to resolve service for type 'XXX' while attempting to activate 'xxxController'

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#49485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When run MVCBlog application with latest .NET 8 SDK build dotnet-sdk-8.0.100-preview.7.23364.32, it crashes with "```Unable to resolve service for type 'MVCBlog.Business.ICommandHandler`1[MVCBlog.Business.Commands.AddBlogEntryCommentCommand]' while attempting to activate 'MVCBlog.Web.Controllers.BlogController```" exception.

**Application Name:** MVCBlog
**OS：** Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.7.23364.32
**App Github Link**: https://github.com/danielpalme/MVCBlog
**App & Source Location checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1852273

**Verify Scenarios:**
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23364.32: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23361.1: Pass
3. Windows10 21h2 x64 + dotnet-sdk-7.0.107(default): Pass

### Expected Behavior

Application could be launched successfully.

### Steps To Reproduce

**Minimal Repro steps (Demo attached):**  
[WebApplication1 (1).zip](https://github.com/dotnet/aspnetcore/files/12236232/WebApplication1.1.zip)

1. Create .NET 7.0 MVC project.
2. Install Scrutor nuget package.
3. Add AddBlogEntryCommentCommand.cs file with follow code:
```
public class AddBlogEntryCommentCommand
{ }
```
4. Add  AddBlogEntryCommentCommandHandler.cs file with following code:
```
public class AddBlogEntryCommentCommandHandler : ICommandHandler<AddBlogEntryCommentCommand>
{
    public Task HandleAsync(AddBlogEntryCommentCommand command)
    {
        throw new NotImplementedException();
    }
}
```
5. Add CommandLoggingDecorator.cs file with following code:
```
internal class CommandLoggingDecorator<TCommand> : ICommandHandler<TCommand>
{
    private readonly ICommandHandler<TCommand> handler;
    private readonly ILogger<CommandLoggingDecorator<TCommand>> logger;
    public CommandLoggingDecorator(
        ICommandHandler<TCommand> handler,
        ILogger<CommandLoggingDecorator<TCommand>> logger)
    {
    }
    public Task HandleAsync(TCommand command)
    {
        throw new NotImplementedException();
    }
}
```
6. Add ICommandHandler.cs file with following code:
```
public interface ICommandHandler<TCommand>
{
    System.Threading.Tasks.Task HandleAsync(TCommand command);
}
```
7. Add below hightlighted code in Program.cs:
```
 builder.Services.AddControllersWithViews();
 builder.Services.AddScoped<ICommandHandler<AddBlogEntryCommentCommand>, AddBlogEntryCommentCommandHandler>();
 builder.Services.Decorate(typeof(ICommandHandler<>), typeof(CommandLoggingDecorator<>));
 var app = builder.Build();
```
8. Add a parameter for HomeController construct function:
 ```
public HomeController(ILogger<HomeController> logger, ICommandHandler<AddBlogEntryCommentCommand> addBlogEntryCommentCommandHandler)
 {
     _logger = logger;
 }
```
9. Build the app.
10. Change the runtime in the WebApplication1.runtimeconfig.json.
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.7.23364.3"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0-preview.7.23364.1"
      }
    ],
```
11. Launch the app.

### Exceptions (if any)

App launch failed with following error:
```
InvalidOperationException: Unable to resolve service for type 'WebApplication1.ICommandHandler`1[WebApplication1.AddBlogEntryCommentCommand]' while attempting to activate 'WebApplication1.Controllers.HomeController'.
lambda_method2(Closure , IServiceProvider , object[] )
Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.100-preview.7.23364.32

### Anything else?

**Findings**

1. If remove this line of code, the issue will go:

```builder.Services.Decorate(typeof(ICommandHandler<>), typeof(CommandLoggingDecorator<>));```

2. When debugging in Visual Studio, in Program.cs, after executing the line we set breakpoint with default7.0 and dotnet-sdk-8.0.100-preview.7.23361.1:
![image](https://github.com/dotnet/aspnetcore/assets/83067197/bca2b88b-bfc8-4e7c-bbf8-c8aa0cb9711e)

  The service object is shown in the following figure with default 7.0
  and dotnet-sdk-8.0.100-preview.7.23361.1:
![image](https://github.com/dotnet/aspnetcore/assets/83067197/a95d7407-0e21-4103-9e45-fd070e7fe07d)
But from dotnet-sdk-8.0.100-preview.7.23364.32, there are three new properties added and show with error:
![image](https://github.com/dotnet/aspnetcore/assets/83067197/4dbccf78-4d87-4de9-8ef2-1c534000e9aa)

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT This bug was found in .NET 8 Preview 7 validation, could you please help check whether it is a blocker for Preview 7. Thanks.

**Comment by mkArtakMSFT** [comment]
> If remove this line of code, the issue will go:
> builder.Services.Decorate(typeof(ICommandHandler<>), typeof(CommandLoggingDecorator<>));

@adityamandaleeka can you get somebody to look into this? Looks like potentially a DI-related issue.

**Comment by Junjun-zhao** [comment]
@adityamandaleeka is there any update for this issue？

**Comment by mkArtakMSFT** [comment]
I am unable to reproduce this error given the repro project. I've installed the latest preview7 SDK and the project started successfully for me and I could navigate through the pages.

**Comment by mkArtakMSFT** [comment]
There were, however, some warnings related to nullable annotations, but those are I assume expected

**Comment by adityamandaleeka** [comment]
@benjaminpetit Can you please take a look?

**Comment by adityamandaleeka** [comment]
@benjaminpetit Artak mentioned that he couldn't repro this issue but please just double check the experience since we made DI changes in this timeframe.

**Comment by Junjun-zhao** [comment]
Thank you @mkArtakMSFT @adityamandaleeka @benjaminpetit  to look into this issue.  We checked it on the Preview 7 build 
8.0.100-preview.7.23376.3 and latest SDK build dotnet-sdk-8.0.100-rc.1.23381.3 today, it is still repro. It was not repro probably because the repro code ```builder.Services.Decorate(typeof(ICommandHandler<>), typeof(CommandLoggingDecorator<>)); ``` was commented out in the attached demo.  We have updated this, please check.

**Comment by benjaminpetit** [comment]
I do repro the issue.

I am not familiar with Scrutor, but it seems it doesn't like the keyed property that we added in preview 7 (it is expected to see theses exceptions that you mentioned in the first post).

**Comment by Junjun-zhao** [comment]
Thank you @benjaminpetit for looking into this issue.   The exceptions were some of our findings when comparing the difference of the builds and shared them for the reference. The main issue is app will crash with code ```builder.Services.Decorate(typeof(ICommandHandler<>), typeof(CommandLoggingDecorator<>));```

@adityamandaleeka Could you double check if this issue is related to DI changes? 

@mkArtakMSFT Could you help reopen this bug for our tracking? Thanks.

**Comment by mkArtakMSFT** [comment]
@adityamandaleeka assigning this to you to prioritize as needed.

**Comment by adityamandaleeka** [comment]
@benjaminpetit, can you please investigate and reassign as needed? I assume only you and @steveharter have touched this area recently.

**Comment by benjaminpetit** [comment]
It seems that the regression started with 138cb59.

Working on it.

**Comment by hankovich** [comment]
I opened [an issue](https://github.com/khellang/Scrutor/issues/208) in Scrutor repo with a tiniest repro, may by helpful

**Comment by Junjun-zhao** [comment]
Verified this issue with dotnet-sdk-8.0.100-rc.1.23421.2, it has been fixed. Thank you.
