### ISSUE TITLE
Order of action filters is not respected when using synchronous and asynchronous filters

### ISSUE THREAD

**Issue by ithline** [dotnet/aspnetcore#49488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an `ApiController` with an `IAsyncActionFilter` that does some validation and adds errors to `ModelStateDictionary`. When executing the action I have noticed that the action is executed even when the `ModelState` has errors. 
After a lot of digging i noticed that the in-box `ModelStateInvalidFilter` executes before my async filter even when it should be executed after based on `IOrderedFilter.Order` property.

### Expected Behavior

One would expect that the filters execute according to their order, so that they could be combined to extend default pipeline without having to copy all the synchronous filters' functionality.

### Steps To Reproduce

Adding these filters to pipeline results in 
```
Sync before
Async before
Async after
Sync after
```
which is clearly wrong.

```c#
internal sealed class SyncFilter : IActionFilter, IOrderedFilter
{
    public int Order => 0;

    public void OnActionExecuted(ActionExecutedContext context)
    {
        Console.WriteLine("Sync after");
    }

    public void OnActionExecuting(ActionExecutingContext context)
    {
        Console.WriteLine("Sync before");
    }
}

internal sealed class AsyncFilter : IAsyncActionFilter, IOrderedFilter
{
    public int Order => -1;

    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        Console.WriteLine("Async before");
        await next();
        Console.WriteLine("Async after");
    }
}
```

**Comment by javiercn** [comment]
@ithline thanks for contacting us.

Filters are nested within each other like onion layers, so filters with higher priority (smaller order) execute closer to the action than those with a higher order.

From the description you are providing, everything is working as expected and the behavior is by design.
