### ISSUE TITLE
Identity APIs return plain text response instead of Problem Details for missing fields

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#49483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Identity APIs currently do not return responses in the standardized `Problem Details` format when a required field is missing. Instead, a plain text response is returned with an exception in the response body. This behaviour makes it challenging for consumers of the API to handle errors consistently and results in a lack of uniformity in error handling.

### Expected Behavior

When a required field is missing from the request, the API should respond with an HTTP status code `400 Bad Request` and return a response body in the standardized `Problem Details` format. The response should contain information about the missing field.

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddAuthentication()
    .AddIdentityBearerToken<IdentityUser>();

builder.Services
    .AddIdentity<IdentityUser, IdentityRole>()
    .AddApiEndpoints()
    .AddEntityFrameworkStores<IdentityDbContext>();

builder.Services.AddDbContext<IdentityDbContext>(options =>
{
    options.UseSqlServer("Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog=Identity;Integrated Security=SSPI;", b => b.MigrationsAssembly("WebApplication1"));
});

var app = builder.Build();

app.MapIdentityApi<IdentityUser>();

app.Run();
```

Try to call the register endpoint without password 
```curl
curl --location 'https://localhost:7042/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "john@domain.net"
}'
```

HTTP response body:
```plain
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to read parameter "RegisterRequest registration" from the request body as JSON.
 ---> System.Text.Json.JsonException: JSON deserialization for type 'Microsoft.AspNetCore.Identity.DTO.RegisterRequest' was missing required properties, including the following: password
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   // end of stack trace omitted for brevity
```

### .NET Version

8.0.100-preview.6.23330.14

**Comment by SeanFarrow** [comment]
I'd like to work on this, but given it's slated for the .Net 9 time-frame, should I wait until .Net 8 has been released?

Thanks,
Sean.
