### ISSUE TITLE
Render issue when mixing render modes in server-rendered page

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#49490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This bug is regarding 2 instances of the Counter component on the same SSR page, each with different render modes, in the particular order: 1) Server and 2) WebAssembly.

It doesn't look right in prerendering:
<img width="501" alt="Screenshot 2023-07-18 at 15 08 15" src="https://github.com/dotnet/aspnetcore/assets/919580/1e80df9a-add8-4770-8530-e10ef04a8c54">

And when the interactivity kicks in the components get displaced:

<img width="448" alt="Screenshot 2023-07-18 at 14 58 26" src="https://github.com/dotnet/aspnetcore/assets/919580/ea9f2ef5-2896-4932-a287-cbcf0d3a5e44">

### Expected Behavior

Here is when the components order is reversed and they are displayed as expected:

<img width="402" alt="Screenshot 2023-07-18 at 14 58 40" src="https://github.com/dotnet/aspnetcore/assets/919580/0c5a6086-6635-418b-a7fc-dfddba264ae4">

### Steps To Reproduce

Here is the page component: https://github.com/marinasundstrom/Blazor8Test/blob/bug/src/Server/Pages/CounterPage2.razor

### .NET Version

8.0.100-preview.6.23330.14

**Comment by MackinnonBuck** [comment]
Thanks for the issue report, @marinasundstrom! This was fixed in https://github.com/dotnet/aspnetcore/pull/49238
