### ISSUE TITLE
Use of proprietary license in AspNetCoreModule-Setup

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/aspnetcore#49512]
The license currently present in `AspNetCoreModule-Setup` restricts redistribution of covered software ([source](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55)):

```
You may not
...
- publish the software for others to copy
```

This is problematic in VMR context as this package is included there with `aspnetcore`, making the license part of the VMR. Proprietary license itself is a show-stopper for various .NET source-build partners.

From the `git` history it seems that the license was part of the once separate project that was later on merged into `aspnetcore`. Would it be possible to alter / remove the license so the project can be used in the VMR?

Thank you

**Comment by MichaelSimons** [comment]
Closing as fixed by https://github.com/dotnet/installer/pull/17046 and https://github.com/dotnet/dotnet/pull/34
