### ISSUE TITLE
WebApiAot project template ApiApplication words not updated

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#49529]
@DamianEdwards  there are still a lot of ApiApplication words in the template, for example, The default project name when creating the project and the. http file name, along with the phrase ApiApplication, These should be updated to be WebApplication, consistent with the WebApplication template.

https://github.com/dotnet/aspnetcore/blob/279d15c3868d914ff41353dcb0b666271abcd342/src/ProjectTemplates/Web.ProjectTemplates/content/WebApiAot-CSharp/.template.config/template.json#L140

https://github.com/dotnet/aspnetcore/blob/279d15c3868d914ff41353dcb0b666271abcd342/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/.template.config/template.json#L424

**Comment by DamianEdwards** [comment]
That gets replaced by whatever the project is called when the template is run, so this has no functional impact that I'm aware of.

**Comment by DamianEdwards** [comment]
Right, but to my knowledge it doesn't actually have any impact here as the name specified `sourceName` matches what's used in the template source files. This value is used by the template engine to replace any instance of it in the template files with the project name:

<img width="482" alt="image" src="https://github.com/dotnet/aspnetcore/assets/249088/1e50120a-c26e-4621-a667-8c648d77ef2a">

**Comment by DamianEdwards** [comment]
Everything derives from the project name, so the only thing this actually impacts as far as I understand is the default project name shown in VS. But I agree it's good to be consistent. Would you like to send a PR?

**Comment by adityamandaleeka** [comment]
Thanks @Varorbc
