### ISSUE TITLE
How to get http request headers accept value?

### ISSUE THREAD

**Issue by xy109** [dotnet/aspnetcore#49535]
### Description

in ModelBinder the System.Web.Http.Controllers.HttpActionContext.Request.Headers.Accept has value,but count is 0?
<img width="461" alt="net_20230720095147" src="https://github.com/dotnet/runtime/assets/10088401/1d54b18f-49fa-4e1a-8375-1ab4f903b976">

### Reproduction Steps

```c#
public class DemoModelBinder:IModelBinder    {
        public bool BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
        {
            Console.WriteLine(actionContext.Request.Headers.GetValues("Accept").FirstOrDefault());
            //multipart/related; type=application/octet-stream
            Console.WriteLine(actionContext.Request.Headers.Accept.Count);
           //0
            return false;
        }
}
```

```c#
public ActionResult Index([ModelBinder(typeof(DemoModelBinder))]DemoRequest request )
  {
      return View();
  }
```

```
curl http://127.0.0.1/ -H "Accept: multipart/related; type=application/octet-stream"
```

### Expected behavior

//multipart/related; type=application/octet-stream
//1

### Actual behavior

//multipart/related; type=application/octet-stream
//0

**Comment by javiercn** [comment]
@xy109 thanks for contacting us.

This repository is for ASP.NET Core related issues. We recommend you post a question on stackoverflow or a similar site to get answers about old ASP.NET
