### ISSUE TITLE
app.use(xxxx) will not make project return 405 error in Asp.Net Core Middle ware.

### ISSUE THREAD

**Issue by sxr1999** [dotnet/aspnetcore#49536]
I have these middle wares in my project:

```
            app.UseRouting();

            app.Use(async (context, next) =>
            {
                await context.Response.WriteAsync("hello");
                await next();
               
            });

            app.UseEndpoints(endpoint =>
            {
                endpoint.MapGet("map1", async (context) =>
                {

                    await context.Response.WriteAsync("In Map 1");
                });

                endpoint.MapPost("map2", async (context) =>
                {

                    await context.Response.WriteAsync("In Map 2");
                });
            });
```

When the request url is Post "/map2", everything works as expected, It returns `hello In Map 2`.  But when I send request in Get method, It will not response anything even the state code, If i remove ` app.Use(xxxxxx)` and send get request again, The project return 405 error normally, I am not sure why ` app.Use(xxxxxx)` will not make project return 405 error.
Thanks in advance.

**Comment by Tratcher** [comment]
A middleware should _not_ write to the response and then call next. Downstream components expect to be able to produce a whole response including status code and headers, but when you write to the response it locks those and causes internal errors that you'd see in the logs.

**Comment by sxr1999** [comment]
Thank you so much for explaining this.
