### ISSUE TITLE
Revamping form-binding in minimal APIs and MVC

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#49543]
This is a meta issue to track follow-up items in the work to add complex form binding support with anti-forgery token validation enabled for MVC and minimal APIs.

- [x] API review for `RequestTokenValidationAttribute`
- [x] Add support for modify `FormOptions` via metadata
- [x] Add support for modifying `FormDataMapperOptions` via metadata
- [x] Add support for `DisableRequestSizeLimits`
- [x] Perf analyzer for anti-forgery middleware checks in endpoint routing
- [x] Anti-forgery threat model
- [ ] Add tests for expanded form-binding scenarios
  - [x] Recursive values
  - [ ] Enum values
  - [ ] Attributes for modifying binding (Ignore, DataMember)

**Comment by Tratcher** [comment]
> * Add support for modify `FormOptions` via metadata

See MVC's RequestFormLimitsAttribute. These limits need to be applied when AntiForgery reads the form.

**Comment by captainsafia** [comment]
Closing this for now as I think the test cover in [this test file](https://github.com/dotnet/aspnetcore/blob/4115298514ef44f2b4ab501d3e37fca068c51e20/src/Components/Endpoints/test/Binding/FormDataMapperTests.cs) provide good coverage here.
