### ISSUE TITLE
Blazor template with 3 projects : Client , Server , Shared in .net 8 Preview 6

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/aspnetcore#49540]
Hello , We can't create a blazor project with 3 projects : Client , Server , Shared that is in Visual Studio in Visual Studio Preview Version 17.7.0 Preview 4.0 and .net 8 Preview 6
Please add that template
I test all 5 template in Visual Studio Preview but there is not "asp.net hosted" checkbox.
Also the "Use interactive server components" do not add 3 projects : Client , Server , Shared !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The Blazor WebAssembly Hosted project template has been removed. Customers will need to use the new Blazor Web template instead going forward, with client-interactivity enabled as needed. Please note, that the new Blazor Web template will be updated in RC1 release to include two projects, and users will be free to add any other projects to their solution, as needed.  That work is tracked by #49412

**Comment by mammadkoma** [comment]
How we can create and add these 3 project and connect default configs for client and server for example cors and ...

**Comment by revbones-dev** [comment]
Great choice removing it before the alternative is added.  Kudos.  Nothing like making it worse/harder before it gets close to what we had.  Two steps back and one step forward!
