### ISSUE TITLE
Blazor Server: Read image saved as blob as base 64 string

### ISSUE THREAD

**Issue by saadsaeed01** [dotnet/aspnetcore#49552]
I am creating an application in Blazor Server Net 6

I was able to save the image as a blob on the local browser by going through the documentation

https://learn.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-7.0#stream-image-data

The images are rendering perfectly in the browser
![image](https://github.com/dotnet/razor/assets/33133831/26f73c8c-ef1e-4cb3-9b7b-c537aeb497b5)

The Blob URL looks something like this

blob:https://localhost:7066/94065f17-5b19-47e4-9256-59f3e237a662

Now, I need to read the blob as a base 64 string. I tried to use IHTTPClient as mentioned below

`var result=await httpClient.GetStreamAsync(_card.LogoImageDetails.ActualImage);`

But, it throws an exception given below
![image](https://github.com/dotnet/razor/assets/33133831/4bf5f98f-cc92-49d6-ad85-6099f94bed4c)

Looking forward to your input and how can I read the blob using C#

Regards 
Saad

**Comment by saadsaeed01** [comment]
Hi @javiercn 

Thank you very much!

The reason I am trying to save the image in the local blob is that I am using Blazor Server. In Blazor Server it is not recommended to save the files directly into the memory stream

See link
https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=server
Reference
![image](https://github.com/dotnet/aspnetcore/assets/33133831/6ba7ba7c-1961-4de4-9b5c-e30f08fc9571)


To overcome this issue, I have created the following solution
https://stackoverflow.com/a/76737811/2666133

Please check it out and tell me what you think.

Regards
S

**Comment by danroth27** [comment]
Looks like you've found a reasonable solution for this.
