### ISSUE TITLE
Localised decimal type value cannot be set on input type number

### ISSUE THREAD

**Issue by muhlisatac** [dotnet/aspnetcore#49564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Current culture: tr
Decimal point is comma. 

If I try to set the value of a input type number as explained below then entered value is not visible. 

With asp-for pattern it renders value as "2496.4400" and show as "2496,4400"

### Expected Behavior

It should show the entered value.

### Steps To Reproduce

Html :
```
<input` value="@((decimal)ViewBag.DecimalValue)" type="number" step="0.0001">
```
Rendered Html : 
```
<input value="2496,4400" type="number" step="0.0001">
```
View : Shows nothing!
![image](https://github.com/dotnet/aspnetcore/assets/8949037/f3bb944d-557e-4c36-8957-998b56ea10cf)

### Exceptions (if any)

Jquery warning on console: The specified value "2496,4400" cannot be parsed, or is out of range.

### .NET Version

7.0.306

**Comment by javiercn** [comment]
@muhlisatac thanks for contacting us.

I believe that `asp-for` does the right thing to adapt the value to the input type (it needs to be formatted as culture invariant). In your case you are writing out the value directly, which depending on how your server is configured, it's likely rendering with the current request culture (which I am going to assume is Turkish).

As you are writing the value directly into the attribute, you are responsible for its format. In this case, you probably need to call `ToString(CultureInfo.InvariantCulture)` to achieve the correct results.

**Comment by muhlisatac** [comment]
Thanks for the quick response @javiercn.
Yes `asp-for` does the right thing. With `ToString(CultureInfo.InvariantCulture)` it works as expected. But is there any elegant way to adapt the value as `asp-for` does?
