### ISSUE TITLE
Incorrect placement of identifiers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#49573]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-placement-of-identifiers/10413703)._

---
[severity:It's more difficult to complete my work]
The code `<div>@((MarkupString)("<span> Lorem ipsum dolor sit amet</span>"))</div>` results in
```
<div b-fygjere2p9>
  <!--!-->
  <span> Lorem ipsum dolor sit amet</span>
</div>
```

My CSS is
```
div > span {
    color: red
}

```
 
The text is not red, because in the resulting CSS file foo.styles.css, the identifier "b-fygjere2p9" is at the wrong position:
```
div > span[b-fygjere2p9] {
    color: red
}
```

Deleting "[b-fygjere2p9]" in foo.styles.css as well as moving it to the div results in red text.

---
#### Feedback Bot on 7/12/2023, 07:46 PM: 

(private comment, text removed)
#### Feedback Bot on 7/13/2023, 00:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment]
@mkArtak mentioned this might be related to https://github.com/dotnet/razor/issues/9034 in triage. I'm not sure it's the same thing, but both deal with CSS isolation.

**Comment by PhilippJR** [comment]
> Is this MVC or is it Blazor.

Blazor

**Comment by SteveSandersonMS** [comment]
I'm afraid this is a limitation in how CSS scoping works. The scopes are only applied to actual real elements in your Razor source code, and markup strings are not real elements in this sense. We can't apply scoping to markup strings without parsing and rewriting them which would be terrible for performance, so we don't.

To fix this in your case, you should use the `::deep` combinator, e.g.:

```css
div ::deep > span {
    color: red
}
```

**Comment by PhilippJR** [comment]
OK, thanks.
