### ISSUE TITLE
TagHelpers don't render content in .NET7

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#49574]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TagHelpers-dont-render-content-in-NET7/10408304)._

---
[severity:I'm unable to use this version]
Hi, I've been struggling with this for 4 hours. And I must say that TagHelpers just don't work.

I have created WebApp from VS template.
My simple TagHelper looks like that:

```
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace TagHelperTest.TagHelpers
{
    [HtmlTargetElement("pagination")]
    public class PaginationTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output. TagName = "div";
            output. Content.SetContent("Hello");
        }
    }
}
```

I have imported it in _ViewImports.cshtml:

```
@using TagHelperTest
@using TagHelperTest.TagHelpers
@namespace TagHelperTest.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, TagHelperTest
```

And use it in Index.cshtml:

```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

<pagination />
</div>
```

Output of my TagHelper is just:

```
<div> </div>
```

instead of:

```
<div>Hello</div>
```

What's more, if I don't set TagHelper name in attribute, so instead of:

```
[HtmlTargetElement("pagination")]
public class PaginationTagHelper : TagHelper
```

I will just:

```
[HtmlTargetElement(TagStructure = TagStructure.WithoutEndTag)]
public class PaginationTagHelper : TagHelper
```

then something really bad happens - all, I mean ALL html tags become somehow my tag helper. It's hard to explain. Image will be better:

![image.png](https://aka.ms/dc/image?name=B9d2a2427e57441b2ab64e41711bb4143638241567139080798_20230705-142523-image.png&tid=9d2a2427e57441b2ab64e41711bb4143638241567139080798)

Look at `<div>, <h1>, <p>` and `<a>` tags - they somehow became my tag. And now the site looks like that:

![image.png](https://aka.ms/dc/image?name=B7200ed3bcf9e4a9d8d1846c5e856498a638241567777132662_20230705-142628-image.png&tid=7200ed3bcf9e4a9d8d1846c5e856498a638241567777132662)

instead of it's normal look:

![image.png](https://aka.ms/dc/image?name=Bf4f8f21208d541be827aeee0bad7f2b8638241568279307982_20230705-142716-image.png&tid=f4f8f21208d541be827aeee0bad7f2b8638241568279307982)

---
#### Feedback Bot on 7/5/2023, 07:15 PM: 

(private comment, text removed)
#### Feedback Bot on 7/6/2023, 00:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by danroth27** [comment]
If your tag starts out as self-closing tag then it doesn't have any content to set. Instead, you can do this to update the tag to also have a closing tag and content that you can then set:

```csharp
output.TagName = "div";
output.TagMode = TagMode.StartTagAndEndTag;
output.Content.SetContent("Hello");
```
