### ISSUE TITLE
Using Blazor for the error handling results in "no submit handler was found with that name" error when dealing with post requests

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49576]
The ASP.NET Core project templates include an error page that is used by the exception handling middleware when an exception happens in production. If I try to change the error page to a Blazor component and then trigger an exception in response to a form post from a .cshtml page, then I get the following error with .NET 8 Preview 7:

An exception was thrown attempting to execute the error handler.
      System.InvalidOperationException: Cannot submit the form '' because no submit handler was found with that name. Ensure forms have a unique @onsubmit:name attribute, or pass the FormHandlerName parameter if using EditForm.

Repro steps:

- Create a new Blazor Web App
- Add an error page (Pages/Error.razor):

```razor
@page "/error"
<h3>Error</h3>
```

- Configure Razor Pages in Program.cs (`builder.Services.AddRazorPages()`, `app.MapRazorPages()`) 
- Add a Razor page with form that submits a post request that results in an exception:

```cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model BlazorApp2.Pages.IndexModel

<form method="post">
    <button type="submit">Submit</button>
</form>
```

```csharp
public class IndexModel : PageModel
{
    public void OnGet()
    {
    }

    public void OnPost() {
        throw new InvalidOperationException();
    }
}
```

- Update Program.cs so that the exception handler middleware is always used, not just in the Development environment
- Run the app and submit the exception throwing form on the Razor page

Expected result: Error page is returned
Actual result:

System.InvalidOperationException: Cannot submit the form '' because no submit handler was found with that name. Ensure forms have a unique @onsubmit:name attribute, or pass the FormHandlerName parameter if using EditForm.

**Comment by javiercn** [comment]
@danroth27 does this repro in preview7?

**Comment by danroth27** [comment]
This no longer repros with 8.0.100-preview.7.23375.2.
