### ISSUE TITLE
BWA/WASM templates embrace H1 top-level headers but RC template doesn't

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#49570]
## Summary

The team settled on H1 heading levels in Blazor project template components ...

* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/Components-CSharp/Pages/Counter.razor#L14
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/Components-CSharp/Pages/Index.razor#L5
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/Components-CSharp/Pages/Weather.razor#L6
* Same for the WASM project template components: https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Pages

However, the Razor component template still uses H3 ...

https://github.com/dotnet/aspnetcore/blob/release/8.0-preview7/src/ProjectTemplates/Web.ItemTemplates/content/RazorComponent/Component1.razor

## Motivation and goals

The default of H1 is appropriate for root page components. The dev can change it from there. Guessing H3 seems arbitrary, and it shows new-to-programming devs the wrong level for root-level components.

## In scope

N/A

## Out of scope

N/A

## Risks / unknowns

None. The dev can change the H1 to any heading level after they generate the component from the template.

## Examples

N/A

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex. That is because the H3 is used in an item template, which may be used in a context much smaller than the page (more granular).
