### ISSUE TITLE
BUG ROLES IN RAZOR PAGE (Blazor)

### ISSUE THREAD

**Issue by jamshid-net** [dotnet/aspnetcore#49590]
Bug in razor pages User role.
I added 3 roles when creating jwt , claimtypes. 
Roles looks like that: 
type:http://schemas.microsoft.com/ws/2008/06/identity/claims/role, value: ["Hello"

type:http://schemas.microsoft.com/ws/2008/06/identity/claims/role, value: "Admin"

type:http://schemas.microsoft.com/ws/2008/06/identity/claims/role, value: "SuperAdmin"] 

 `<AuthorizeView Roles='"SuperAdmin"]'>` it works 
but `<AuthorizeView Roles='SuperAdmin'>` it is not working

**Comment by jamshid-net** [comment]
> Moving this to runtime, for a potential issue with the `AuthorizeView` component. The specific attribute formats seem to work fine in other scenarios.

but via [Authorize] attribute same issue

**Comment by javiercn** [comment]
@jamshid-net thanks for contacting us.

When you inspect the principal. What's the value of the `Roles` claim on the principal?

**Comment by jamshid-net** [comment]
> 

![image](https://github.com/dotnet/aspnetcore/assets/39515083/2f36b6df-eb9f-4067-bb15-e078eff4dcc3)
![image](https://github.com/dotnet/aspnetcore/assets/39515083/4a2531e4-7b86-4819-b8a5-5ce314f2055b)
![image](https://github.com/dotnet/aspnetcore/assets/39515083/5788b573-50d3-4651-a048-8a83fa5c7fbe) 

yes I used jwt , but Roles worked properly in ApiController

**Comment by jamshid-net** [comment]
> @jamshid-net It seems that your JWT is being deserialized incorrectly into your principal. What provider are you using?
> 
> You might want to use the custom user creation extension point to fully tweak the code that processes the roles.
> 
> See https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#customize-the-user for details.

Thanks a lot, it works!
