### ISSUE TITLE
SpaProxyMiddleware: Allow custom SPA Loading Page

### ISSUE THREAD

**Issue by EmaGht** [dotnet/aspnetcore#49605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am unable to override the default loading page for my SPA app

### Describe the solution you'd like

I think it would be cool to be able to provide a custom Loading page for our SPA Application. I do realize that's a development-only thing but i want to play a minigame while waiting for my app to start.

In all seriousness, being able to provide my custom waiting page would be cool

Reference to the culprit: https://github.com/dotnet/aspnetcore/blob/c8e2a27c9e00f593d3bccaab2f6958cc0a240284/src/Middleware/Spa/SpaProxy/src/SpaProxyMiddleware.cs#L74

let me know :)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
