### ISSUE TITLE
C# Dev Kit for VS Code missing controller based API project template.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#49617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

C# Dev Kit for Visual Studio code missing the controller-based Web API project while the default one is minimal API which nobody will use in production.

<img width="1497" alt="image" src="https://github.com/dotnet/aspnetcore/assets/14342773/7d2804c1-4479-4703-9175-461657d49d20">

### Expected Behavior

C# Dev Kit should have controller-based Web API project instead of minimal API or both.

### .NET Version

7.0 and 8.0

**Comment by martincostello** [comment]
I believe issues with the C# Dev Kit should be filed in this repo: https://github.com/microsoft/vscode-dotnettools

**Comment by TanvirArjel** [comment]
@martincostello I think it is part of the ASP.NET Core templating.

**Comment by captainsafia** [comment]
@TanvirArjel The `webapi` and `mvc` templates both use controllers depending on whether or not you want views attached as well. Does this not meet your needs?

**Comment by TanvirArjel** [comment]
Hello @captainsafia 

> whether or not you want views attached as well

Didn't understand this. Could you please explain what you mean.

**Comment by davidfowl** [comment]
It seems like the defaults are different in the DevKit and it does indeed select the minimal API variant of the WebAPI project.

cc @timheuer

**Comment by timheuer** [comment]
> It seems like the defaults are different in the DevKit and it does indeed select the minimal API variant of the WebAPI project.
> 
> cc @timheuer

This is correct. We chose modern defaults for now in templates in VSCode. There is an existing issue over there I believe for reconsideration of options choosing in the flow.
