### ISSUE TITLE
Enhanced navigation is not triggered by links in interactive components

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#49614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhanced navigation is not triggered by links in interactive components. Links are not intercepted, and it causes navigation to page.

It might no be a big deal. But should this be consistent across the render modes?

### Steps To Reproduce

Having a page marked with ``@attribute [RenderModeServer]``, with a link to a non-interactive server-side rendered page.

1. Run the app and navigate to the page. 
2. Launch the browser's Dev Tools.
3. Click the link. 

In Dev Tools, you will see that the page was loaded in the "Doc" tab - not in "Fetch/XHR" as with enhanced navigation.

### .NET Version

8.0.100-preview.6.23330.14

**Comment by MackinnonBuck** [comment]
This was fixed by https://github.com/dotnet/aspnetcore/pull/49238
