### ISSUE TITLE
Custom claims lost after sometime in AspNetCore Identity cookie

### ISSUE THREAD

**Issue by affableashish** [dotnet/aspnetcore#49610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I see a [question](https://stackoverflow.com/q/23622047/8644294) that was already asked years ago that explains a problem related to losing custom claims while using AspNet Identity. The solution mentioned there unfortunately doesn't work for me as I'm using AspNet **Core** Identity on a .NET 6 Blazor Server app.

The issue is similar (explained in points below):
1. I add some claims during login (these claims come from some API call and not from Identity db, so I add them during login).

2. I access them from Blazor components just fine.

3. It works fine 30% of the time, but for 70% of the time, the cookie loses custom claims that I added during login and my app runs into issues. I'm not even able to figure out when those claims get lost as that's not happening during `RevalidationInterval` either as I tested it with a TimeSpan of 1 minute and it worked well for at least 5 minutes when I tested it multiple times. Searched up bunch of answers and found no proper answer for AspNet **Core** Identity.

This is how my code looks like:

1. Identity setup in Program.cs
````
    builder.Services
    .AddDefaultIdentity<IdentityUser>(options =>
    {
        options.SignIn.RequireConfirmedAccount = false;
        // Set Password options here if you'd like:
        options.Password.RequiredLength = 6;
    })
    .AddRoles<IdentityRole>()
    .AddUserManager<ADUserManager<IdentityUser>>()
    .AddEntityFrameworkStores<ApplicationDbContext>();

    builder.Services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<ApplicationUser>>();

````

2. Adding claims during Login in Login.cshtml.cs
````
    public async Task<IActionResult> OnPostAsync(string returnUrl = null)
    {
        returnUrl ??= Url.Content("~/");
        if (!ModelState.IsValid) return Page();
    
        try
        {
            var adLoginResult = ADHelper.ADLogin(Input.Username, Input.Password);
    		
    		// Use adLoginResult data to populate custom claims here
            // Set additional info about the user using empTimeId and other custom claims
            var customClaims = new[]
            {
                new Claim("EmployeeTimeId", adLoginResult.TimeId)
            };
    
            // SignIn the user now
            await _signInManager.SignInWithClaimsAsync(user, Input.RememberMe, customClaims);
            return LocalRedirect(returnUrl);
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(string.Empty, $"Login Failed. Error: {ex.Message}.");
            return Page();
        }
    }
````
3. Revalidation method in RevalidatingIdentityAuthenticationStateProvider.cs
````
    public class RevalidatingIdentityAuthenticationStateProvider<TUser>
        : RevalidatingServerAuthenticationStateProvider where TUser : class
    {
        private readonly IServiceScopeFactory _scopeFactory;
        private readonly IdentityOptions _options;
    
        public RevalidatingIdentityAuthenticationStateProvider(
            ILoggerFactory loggerFactory,
            IServiceScopeFactory scopeFactory,
            IOptions<IdentityOptions> optionsAccessor)
            : base(loggerFactory)
        {
            _scopeFactory = scopeFactory;
            _options = optionsAccessor.Value;
        }
    
        protected override TimeSpan RevalidationInterval => TimeSpan.FromMinutes(1); // More frequent for ease of testing
    
        protected override async Task<bool> ValidateAuthenticationStateAsync(AuthenticationState authenticationState, CancellationToken cancellationToken)
        {
            //Get the user manager from a new scope to ensure it fetches fresh data
            var scope = _scopeFactory.CreateScope();
    
            try
            {
                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<TUser>>();
                return await ValidateSecurityTimeStampAsync(userManager, authenticationState.User);
            }
            finally
            {
                if(scope is IAsyncDisposable asyncDisposable)
                {
                    await asyncDisposable.DisposeAsync();
                }
                else
                {
                    scope.Dispose();
                }
            }
        }
    
        private async Task<bool> ValidateSecurityTimeStampAsync(UserManager<TUser> userManager, ClaimsPrincipal principal)
        {
            var user = await userManager.GetUserAsync(principal);
            if(user == null)
            {
                return false;
            }
            else if (!userManager.SupportsUserSecurityStamp)
            {
                return true;
            }
            else
            {
                var principalStamp = principal.FindFirstValue(_options.ClaimsIdentity.SecurityStampClaimType);
                var userStamp = await userManager.GetSecurityStampAsync(user);
                return principalStamp == userStamp;
            }
        }
    }
````
4. Retrieving auth information
````
    public class UserInfoService
    {
        private readonly AuthenticationStateProvider _authenticationStateProvider;
        private readonly IDbContextFactory<ApplicationDbContext> _dbContextFactory;
    
        public UserInfoService(AuthenticationStateProvider authenticationStateProvider, IDbContextFactory<ApplicationDbContext> dbContextFactory)
        {
            _authenticationStateProvider = authenticationStateProvider;
            _dbContextFactory = dbContextFactory;
        }
    
        public async Task<UserInfoFromAuthState?> GetCurrentUserInfoFromAuthStateAsync()
        {
            var userInfo = new UserInfoFromAuthState();
    
            var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
            if (authState == null ||
                authState.User == null ||
                authState.User.Identity == null ||
                !authState.User.Identity.IsAuthenticated)
            {
                return null;
            }
    
            userInfo.UserName = authState.User.Identity.Name!;
    		
            // This comes out to be null after sometime a user has logged in
    		userInfo.EmployeeTimeId = int.TryParse(authState.User.FindFirstValue("EmployeeTimeId", out var timeId) ? timeId : null;
    
            return userInfo;
        }
    }
````
This is where I face problem when I get null on my custom claim: `"EmployeeTimeId"`.

### Expected Behavior

Documented way of how to prevent customs claims from disappearing from the Identity cookie randomly.

**Comment by affableashish** [comment]
@quicksln It's related to a [previous issue](https://github.com/dotnet/aspnetcore/issues/46558) you helped me with; any way you could help me out with this as well?
I'd appreciate any help you could provide. Thank you!

**Comment by halter73** [comment]
Have you checked whether `SecurityStampValidator.SecurityStampVerified` is replacing the principal via `CookieAuthenticationOptions.Events.OnValidatePrincipal`?

https://github.com/dotnet/aspnetcore/blob/775028fdd25256ee7d9e70402dc73744b5977550/src/Identity/Core/src/IdentityCookiesBuilderExtensions.cs#L47-L57

https://github.com/dotnet/aspnetcore/blob/775028fdd25256ee7d9e70402dc73744b5977550/src/Identity/Core/src/SecurityStampValidator.cs#L92-L119

You could try customizing this via [SecurityStampValidatorOptions.OnRefreshingPrincipal](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.securitystampvalidatoroptions.onrefreshingprincipal?view=aspnetcore-7.0).

**Comment by affableashish** [comment]
Thank you for the response @halter73. 
How do I customize this via [SecurityStampValidatorOptions.OnRefreshingPrincipal](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.securitystampvalidatoroptions.onrefreshingprincipal?view=aspnetcore-7.0)? I see no example in the link you provided.
Can you please give an example based on my code? Where to put this, how to put this? I'm kinda lost on this. Your help is much appreciated! Thanks!

**Comment by halter73** [comment]
You can use the [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#use-di-services-to-configure-options). So, the simplest way would be something like thits:

```csharp
builder.Services.Configure<SecurityStampValidatorOptions>(o => 
{
    o.OnRefreshingPrincipal = principalContxt =>
    {
        ClaimsIdentity? newIdentity = principalContxt.NewPrincipal?.Identities.First();
        AddCustomClaims(newIdentity)
        return Task.CompletedTask;
    };
});
```

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-7.0#isecuritystampvalidator-and-signout-everywhere\

And [here's an example usage from Umbraco-CMS.](https://github.com/umbraco/Umbraco-CMS/blob/05b89999afb65caf7e8dd7f17d34edbaa10cc842/src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs)

**Comment by affableashish** [comment]
@halter73 Thank you for your answer and thank you so much for those great links, especially the excellent example in Umbraco-CMS. Learned something new today. 
Just have a question: couldn't this have been put inside `RevalidatingIdentityAuthenticationStateProvider` in some way as that deals with SecurityStamp as well.

**Comment by affableashish** [comment]
Thank you @halter73. This is how I wrote my answer:

Step 1:
---
Add a new class under Identity folder called `ConfigureSecurityStampOptions.cs` (or anywhere you'd like):

<img src="https://i.stack.imgur.com/nnfGo.png/350" width="400" />

Step 2:
---
Content of `ConfigureSecurityStampOptions.cs` should be:

    public class ConfigureSecurityStampOptions : IConfigureOptions<SecurityStampValidatorOptions>
    {
    	public void Configure(SecurityStampValidatorOptions options)
    	{
    		options.ValidationInterval = TimeSpan.FromMinutes(10); // Default interval is 30 minutes
    
    		// When refreshing the principal, ensure custom claims that
    		// might have been set with an external identity continue
    		// to flow through to this new one.
    		options.OnRefreshingPrincipal = refreshingPrincipal =>
    		{
    			ClaimsIdentity? newIdentity = refreshingPrincipal.NewPrincipal?.Identities.First();
    			ClaimsIdentity? currentIdentity = refreshingPrincipal.CurrentPrincipal?.Identities.First();
    
    			if (currentIdentity is not null && newIdentity is not null)
    			{
    				// Since this is refreshing an existing principal, we want to merge all claims.
    				// Only work with claims in current identity that are not already present in the new identity with the same Type and Value.
    				var currentClaimsNotInNewIdentity = currentIdentity.Claims.Where(c => !newIdentity.HasClaim(c.Type, c.Value));
    
    				foreach (Claim claim in currentClaimsNotInNewIdentity)
    				{
    					newIdentity.AddClaim(claim);
    				}
    			}
    
    			return Task.CompletedTask;
    		};
    	}
    }

Step 3:
---
Register it in `Program.cs`

    // To ensure custom claims are added to new identity when principal is refreshed.
    builder.Services.ConfigureOptions<ConfigureSecurityStampOptions>();

Full Source Code
---
https://github.com/affableashish/blazor-server-auth/tree/feature/AddClaimsDuringLogin


Stackoverflow Answer:
---
https://stackoverflow.com/a/76790172/8644294
