### ISSUE TITLE
StreamRendering and RenderModeServer causes OnInitialized to be invoked twice. Second time query parameter not bound.

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#49612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Interactive Server page with attributes ``StreamRendering(true)`` and ``RenderModeServer`` causes ``OnInitialized``/``OnInitializedAsync`` to be invoked twice. 

Taking a normal route parameter and a parameter supplied from query (using ``SupplyParameterFromQuery``).

Invoking the page with fresh navigation using query parameter causes the ``OnInitialized`` method to be invoked twice. The second time the query parameter is not bound. Though the regular route parameter is.

### Expected Behavior

The parameter should be bound from query.

**Question:** <strike>Should ``OnInitialized`` be invoked twice? I thought only ``OnAfterRender`` ran twice while the server component being the same. </strike>

I see, the component object is not being re-used from the pre-render.

### Steps To Reproduce

Doing a fresh navigation to: ``/test/x?queryParam=test``

```razor
@page "/test/{path?}"
@attribute [StreamRendering(true)]
@attribute [RenderModeServer]

@QueryParam

@code 
{
    [Parameter]
    public string? Param { get; set; }

    [SupplyParameterFromQuery]
    public string? QueryParam { get; set; }

    protected override void OnInitialized()
    {
        // Method called twice
        
        // First time the value of QueryParam is set to "test", and Param is "x"
        // The second time the value of QueryParam is null, but Param is "x"
        Console.WriteLine(QueryParam);
    }
}
```

First time hitting break-point:
![Screenshot 2023-07-25 at 13 39 37](https://github.com/dotnet/aspnetcore/assets/919580/bd0174bc-0dde-43cb-8f19-181667dbdf2a)

Second time:
![Screenshot 2023-07-25 at 13 40 00](https://github.com/dotnet/aspnetcore/assets/919580/c6667f2d-24c9-43eb-a290-44e22c6fa9a8)

### .NET Version

8.0.100-preview.6.23330.14

**Comment by marinasundstrom** [comment]
My scenario is a pre-rendered interactive product listing page.

**Comment by marinasundstrom** [comment]
The workaround in my case is to extract the interactive part into its own component.

**Comment by marinasundstrom** [comment]
On a side note: I'm unable to set default values for parameters with [SupplyParameterFromQuery]. They are set but get reset when bound.

```c#
    [SupplyParameterFromQuery]
    public int? PageSize { get; set; } = 1;
```

**Comment by dmm-l-mediehus** [comment]
@marinasundstrom Try @attribute [RenderModeServer(false)]?

Prerendering is on by default for RenderModeServer and RenderModeWebAssembly, which loads OnInit-method twice, and that is on purpose.

**Comment by javiercn** [comment]
@marinasundstrom thanks for contacting us.

`OnInitialized` will execute once during prerendering, and once again when the component becomes interactive. During prerendering a render process starts, and once we are done prerendering, it stops, disposing all the prerendered components.

Then, for components that have either server or webassembly mode, the components are re-created again and produce a new render to become interactive (that's where the OnInitialized runs for the second time).

**Comment by marinasundstrom** [comment]
@javiercn Thanks for responding. Alright.

But what about the issue with the query parameter not being applied once the component gets interactive? Is that something that you already know about?

**Comment by javiercn** [comment]
@marinasundstrom no, that should work.

I am not sure why is not working, but there has been a lot of churn in this area during preview7, so I would suggest you try a nightly build.

**Comment by marinasundstrom** [comment]
@javiercn OK. I'm on Preview 6. It seems that it sometimes work and but mostly not.
Alright. I will either try or wait for the next Preview to be released.

**Comment by mkArtakMSFT** [comment]
> @javiercn OK. I'm on Preview 6. It seems that it sometimes work and but mostly not. Alright. I will either try or wait for the next Preview to be released.

@marinasundstrom did you get a chance to try preview 7 release and see if this is still a problem? If yes, I think it'll be better to close this issue and file a new one for that.

**Comment by ronikurnia1** [comment]
> @marinasundstrom Try @Attribute [RenderModeServer(false)]?
> 
> Prerendering is on by default for RenderModeServer and RenderModeWebAssembly, which loads OnInit-method twice, and that is on purpose.

It seems introduce bad experience: the page blinking (tested using .NET 8 preview 7)
