### ISSUE TITLE
Blazor WebAssembly misinterprets Content-Type on wasm file, uses slow ArrayBuffer instantiation

### ISSUE THREAD

**Issue by sake402** [dotnet/aspnetcore#49621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For some weird unknown reason, the file server for a blazor wasm app is returning double and duplicate ``Content-Type`` on *.wasm request for a blazor wasm file.

![image](https://github.com/dotnet/aspnetcore/assets/20999608/dd0c76ad-3365-4ae1-a77c-269fda9fe961)

But because this ``Content-Type`` is handled literarily by Blazor, it makes it fallback to slow ArrayBuffer instantiation.

![image](https://github.com/dotnet/aspnetcore/assets/20999608/3604b9cc-61c2-421f-a442-08131f7bab3e)

![image](https://github.com/dotnet/aspnetcore/assets/20999608/7aa62c45-715b-4b0a-abe8-1cf4b0acb6fe)

I would assume this double ``'application/wasm'`` is still valid as html standard allows multiple values as header value

### Expected Behavior

WebAssembly.instantiateStreaming should be used despite multiple copies of ``application/wasm`` in ``Content-Type``

**Comment by SteveSandersonMS** [comment]
To clarify, the only thing we need to do here is make sure we don't server this broken content type (`application/wasm, application/wasm`) by default. As long as that doesn't happen normally, there is no problem and can close this.

**Comment by javiercn** [comment]
Can't repro this in RC2
