### ISSUE TITLE
ASP.NET Core 8-p6 Blazor page does not load in new browser window

### ISSUE THREAD

**Issue by ladeak** [dotnet/aspnetcore#49657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WebAssembly application that is being migrated from .NET7 to .NET8 following instructions: 

https://github.com/danroth27/Net8BlazorWebAssembly/blob/main/README.md

When I open a new browser tab and navigate to a razor page it sometimes loads, but most of the times, the request is "pending" in the network tab of the browser. I do see a few System.IO.IOExceptions exceptions:

```
System.IO.IOException: 'Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..'
```

Inner exception:

```
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
```

This is what the logs say: 

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/posts/pooling-bufferwriter - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/posts/{postname} (/posts/{postname})'

I see the InitailzieAsync and OnParametersSetAsync invoked. When I navigate to the same page from the "home page", it loads correctly.

### Expected Behavior

Page would load even when navigating to it from a new tab.

### Exceptions (if any)

I see some IO exceptions.

### .NET Version

8.0.100-preview.6.23330.14

### Anything else?

 Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11
Browser: Edge

**Comment by ladeak** [comment]
Let me I gather more information on the issue.

**Comment by ladeak** [comment]
Apparently I managed to filter down the cause, and I am having problems with this:

```razor
@using Markdig.Syntax.Inlines

@Text

@code {
    [Parameter]
    public LiteralInline Literal { get; set; }

    public string Text { get; set; }

    protected override async Task OnParametersSetAsync()
    {
       // some code here commented out
        Text = "text";
    }
}
```

apparently it loads correctly if I remove the `@Text` tag.

**Comment by ladeak** [comment]
One thing notice as an exception is raised in `WebAssemblyComponentSerializer.SerializeInvocation` in line: `var (definitions, values) = ComponentParameter.FromParameterView(parameters);`

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.
```

**Comment by ladeak** [comment]
The other thing I notice: it hangs silently based on the number of components on the page.

**Comment by mkArtakMSFT** [comment]
> ```
> a
> 
> @code {
> }
> ```

This is being tracked as part of #49172

**Comment by mkArtakMSFT** [comment]
> One thing notice as an exception is raised in `WebAssemblyComponentSerializer.SerializeInvocation` in line: `var (definitions, values) = ComponentParameter.FromParameterView(parameters);`
> 
> ```
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.
> ```

Thanks for additional details. We will need a repro to be able to investigate this further.

**Comment by ladeak** [comment]
> This is being tracked as part of https://github.com/dotnet/aspnetcore/issues/49172

Yes, that was my thinking that probably there is a deadlock, I did not have a chance to further review. Thank you for pointing out the the other issue.


For the Json serialization, I have a set of (larger number) components server rendered, and at the end of the chain a webassembly rendered component.

**Comment by javiercn** [comment]
@ladeak we would appreciate if you could provide a repro, as otherwise it's impossible for us to make progress.

**Comment by ladeak** [comment]
I am on holiday without access to the project, but it was a larger Server rendered component tree with a wasm based component at one of the leaves.

**Comment by danroth27** [comment]
Hi @ladeak. To verify if the JSON serialization issue is a separate from the synchronous writes problem, could you please try out your repro with a nightly build of .NET 8? You can install one from https://github.com/dotnet/installer.

**Comment by ladeak** [comment]
Hi @danroth27 ,

I will give it a go later this week, still on holidays with limited connectivity.

**Comment by ladeak** [comment]
Updated to:

```
.NET SDK:
 Version:   9.0.100-alpha.1.23416.26
 Commit:    39f5eb5ef8
```

and

```
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23414.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23414.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23412.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Updated nuget packages to daily to corresponding:

```xml
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-rc.1.23416.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-rc.1.23416.4" PrivateAssets="all" />
    ...
```

and the server

```xml
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.0-rc.1.23416.4" />
```

Could you confirm these are the right versions and I have not missed updating anything else?

With the above versions, I get the following issue:

```
JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.

....
```

**Comment by halter73** [comment]
Try the latest 8.0-rc1 sdk from [here](https://aka.ms/dotnet/8.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe). Try not to mix the 9.0 SDK with 8.0 packages, but they shouldn't have diverged too much yet.

The cycle issue appears to be a problem with the application code and we did not expect that to be fixed by updating. Are you passing any parameters with a `Parent` property to a component?

**Comment by ladeak** [comment]
Ok, so my first test is to see that there is no freezing when all components are server rendered -> which I do not see happening anymore 👍 
For the serialization, I was a little confused because previously the application "state" was serialized when the app switched over from server pre-render to webassembly mode, and as part of trying migrating to asp.net core 8 now I only set a "leaf" component to be WebAssembly rendered, so I expected the state to be smaller to be serialized.

Now with your pointers @halter73 , the picture is much clearer. I use component parameter typed `FencedCodeBlock` which has a Parent property in it's [base type](https://github.com/xoofx/markdig/blob/5e3416f8b78ea049148667343f44d91cc12f8426/src/Markdig/Syntax/Block.cs#L34). As it is coming from 3rd party library, I was not sure what the "Parent" could refer to. I can easily refactor this to my own type to confirm, which I will do soon / tomorrow and close this issue if that resolves the problem.

**Comment by ladeak** [comment]
With the above suggestion, I manage to resolve the serialization issue.

**Comment by ladeak** [comment]
@danroth27 is there a pattern suggested to define a placeholder for components that are webassembly rendered for the time while the page is server rendered? Is there a way inside the component to tell if it is being webassembly rendered or not / or should 'callsite' decide to render a placeholder or the actual component somehow? (say at the call site having 2 components next to each other, one wa rendered the other server rendered?

Or if a component is auto rendered, the component itself should be able to decide how to render itself not? (ie. it might use some JS interop)
