### ISSUE TITLE
SignalR not working on windows server 2019

### ISSUE THREAD

**Issue by sardar97** [dotnet/aspnetcore#49656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i publish my blazor server app website on iis on windows server 2019 and when i open the website on localhost
i mean the server it works fine but when i open it from client or out side the server it is not working and show this error message :
"No connection could be made because the target machine actively refused it."

### .NET Version

7.0.9

**Comment by sardar97** [comment]
with Blazor web assembly it works fine but with Blazor server app it is not working and has this error :
"No connection could be made because the target machine actively refused it." 
I just forgot this note.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Where do you get that error? Also, how SQL Server is involved here? Seems like the scenario will happen even if you would have no SQL Server involved.

**Comment by tebeco** [comment]
I would press F12 to open Devtool and look at both Network and console tab.
It look like you have a high chance of a bad configuration / certificate etc ...

**Comment by sardar97** [comment]
> I would press F12 to open Devtool and look at both Network and console tab.
> 
> It look like you have a high chance of a bad configuration / certificate etc ...

but i used try catch so the console will not show error however i showed the error message with try catch.
anyway i will take some screenshots with try catch and without it, and i will post it here.

**Comment by sardar97** [comment]
i solved the problem with this code
.WithUrl("http://192.168.1.3:80/ChatHub")
because i used blazor server app.
but now i registered a domain and dns for my website and i used https for it
but i don’t know what should i write in this line .WithUrl("http://192.168.1.3:80/ChatHub") for the https
Because i tried everything but it has same error that before had.
