### ISSUE TITLE
ASP.NET Core Identity Documentation and samples

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#49668]
This issue lists all the scenarios in priority order, that we will need to document:

## Prioritized Scenarios

|  | Sample link or PR | Scenario | Identity Provider host (same=ASP.NET Core Identity, sep. = AAD., Auth0, ...) |
| --- | --- |  --- | --- |
| 1 | [Blazor Web App OIDC](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc)| Web app / API calling other API (on separate hosts) | separate |
| 2 |[Docs](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-identity) | Blazor WASM + API (hosted on the same host) |  same |
| 3 | [Docs](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library) | Blazor WASM + API (hosted on the same host) | separate |
| 4 |  | Microservices scenario: Using existing JWT token for authentication between services | separate |
| 5 | [Angular + Identity sample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/samples/ngIdentity) | SPA + API (hosted on the same host) | same |

<details>
<summary>Topics which have been cut</summary>
|  | Sample link or PR | Scenario | Identity Provider host (same=ASP.NET Core Identity, sep. = AAD., Auth0, ...) | Priority |
| --- | --- |  --- | --- | --- |
| 1 |  | Web app / API (hosted on the same host) | same | 1 |
| 3 |  | Mobile app + API | separate | 7 |
| 4 |  | Web app / API (hosted on the same host) | separate | 10 |
| 7 |  | SPA + API (hosted on the same host) | separate | 16 |
| 9 |  | Mobile app + API | same | 20 |
| 10 |  | SPA + API (hosted on different host) | same | 25 |
| 11 |  | SPA + API (hosted on different host) | separate | 30 |
</details>

## SPA Frameworks
For the scenarios that involve SPA framework, we will try to provide the samples using Angular and SPA frameworks.

**Comment by marzoukali** [comment]
Hi Guys,

Is that `MapIdentityApi(..)` can be used with Azure Functions ?

**Comment by BartoGabriel** [comment]
I believe it would be beneficial to create an example that combines multiple frontends. A classic scenario would involve securing an ASP.NET Core Identity-protected REST API, with two frontends consuming it: a web app (Blazor) and a mobile app (MAUI). This setup reflects a common use case where backend logic resides in a RESTful service, and two distinct application types (web and mobile) interact with it.

**Comment by mkArtakMSFT** [comment]
@halter73 I see that some PRs were merged. Please update the table in the description to reference the updated docs.
