### ISSUE TITLE
Can't run Blazor wasm startproject

### ISSUE THREAD

**Issue by VervaekeSofie** [dotnet/aspnetcore#49661]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/49649

<div type='discussions-op-text'>

<sup>Originally posted by **VervaekeSofie** July 26, 2023</sup>
I'm new with blazor wasm.
I created a project with Visual Studio Community and build it.
Then I want to Run it, but that went wrong. I tried it with Google chrome and Edge, the same error is generated.
The error is: Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at At (https://localhost:7292/_framework/blazor.webassembly.js:1:59617) {stack: 'Error: Failed to start platform. Reason: Type…292/_framework/blazor.webassembly.js:1:59617)', message: 'Failed to start platform. Reason: TypeError: Failed to fetch'}

![image](https://github.com/dotnet/aspnetcore/assets/84907679/cc1b0954-7525-49a8-8400-0d402da076c3)
![image](https://github.com/dotnet/aspnetcore/assets/84907679/5cccfe78-8838-4e17-9bd3-6fa20ad33d87)

I tried it also with Visual Code and the same happend. I work with Windows 11. Is there something not installed?
If I make a Blazor Server app, I can run it.
</div>

**Comment by VervaekeSofie** [comment]
> @VervaekeSofie thanks for contacting us.
> 
> What version of .NET Core are you using and how are you trying to run the app. Is it from within Visual Studio or from the command line, if the latter. Are you using `dotnet run` to run it?

I use version .NET core 6.0 and try to furn in Visual Studio IDE with F5 and Ctrl-F5 and with the terminal. 

The browser (chrome and edge) try to boot the localhost but then i get error. The webpage only says loading...

**Comment by mkArtakMSFT** [comment]
@VervaekeSofie what VS version are you using?

**Comment by VervaekeSofie** [comment]
> @VervaekeSofie what VS version are you using?

![image](https://github.com/dotnet/aspnetcore/assets/84907679/ad9b1e47-5804-446d-8e18-b7bcff6b52be)

**Comment by mkArtakMSFT** [comment]
Thanks. Can you please try to run `dotnet run` in the project directory from the command prompt and see if that works?

**Comment by VervaekeSofie** [comment]
>dotnet run gives the same problem. Loading... with an error remains in the localhost. There are now build errors.

**Comment by VervaekeSofie** [comment]
I published the built version and I got the same error.
![image](https://github.com/dotnet/aspnetcore/assets/84907679/451e5b4d-011d-4c9c-a7ff-316161ed72a2)

**Comment by javiercn** [comment]
@VervaekeSofie thanks for the additional information.

Can you tell us what build errors are you seeing?

Also, could you open the dev tools and indicate the console errors there?

**Comment by VervaekeSofie** [comment]
> @VervaekeSofie thanks for the additional information.
> 
> Can you tell us what build errors are you seeing?
> 
> Also, could you open the dev tools and indicate the console errors there?
> 
> Finally, do you happen to have special characters on the project path?

There are now build-errors, it's just when I want to debug that it doesn't start. The browser is loading... and then there is a error as explained in te topic.

I don't have special characters on the project path.

**Comment by mkArtakMSFT** [comment]
@VervaekeSofie the URL you're trying to access the website through is not localhost. Do you have some DNS routing setup to redirect that hostname to localhost? If so, you will need to configure CORS too.
To confirm this, can you try to access this website through localhost and see if that works?
