### ISSUE TITLE
NavigationManager doesn't navigate relative to the base address when using Blazor SSR

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49670]
According to the [docs](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.components.navigationmanager.navigateto), `NavigationManager.NavigateTo` should treat relative URIs as relative to the base URI, which it how it works with existing Blazor Server and Blazor WebAssembly apps. But with SSR, it seems to navigate relative to the current address instead.

Repro steps:

- Create a Blazor Web App
- Update Index.razor with the following:

```razor
@page "/"
@page "/foo"
@page "/foo/bar"
@inject NavigationManager NavigationManager

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@code {
    protected override void OnInitialized()
    {
        NavigationManager.NavigateTo("weather");
    }
}
```
- Browse to "/foo/bar"

Expected result: Request is redirected to /weather
Actual result: Request is redirected to /foo/weather

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/50261
