### ISSUE TITLE
IEmailSender exists in both 'Microsoft.AspNetCore.Identity.UI' and 'Microsoft.Extensions.Identity.Core'

### ISSUE THREAD

**Issue by rgordey** [dotnet/aspnetcore#49681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to the latest Asp.Net Core Identity packages (8.0.0-rc.1.23377.1) project reports this error.

The type 'IEmailSender' exists in both 'Microsoft.AspNetCore.Identity.UI, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.Identity.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### .NET Version

8.0.100-preview.7.23376.3

**Comment by Tratcher** [comment]
The type was moved and forwarded. Rc.1 packages should only be used with Rc.1 versions of the shared framework.

**Comment by nguyentuananh921** [comment]
I still got this Error.
Please help
![image](https://github.com/dotnet/aspnetcore/assets/18616693/56030e21-5a23-450f-8e9d-e30d01b1df32)

**Comment by DarshilSavaliya999** [comment]
Go to Previous Visual Studio Version.
And Problem Will Solve.

**Comment by ClereLearning** [comment]
Dear Team,
After upgrading the Visual Studio Community 2022 (64bits) Preview to version 17.8.0 Preview 1.0 and I got the same problem.
It was working well with the Visual Studio Community 2022 (64bits) 17.7.0 Preview 4.0 

I need to present this project running next Wednesday (08/16/2023) 
I am CCT College Dublin student and it is my Final Project

My application is Blazor WebAssembly with Identity (Individual account)  authenication, "Configure for HTTPS" and "ASP.NET Core hosted"
I cleaned the folder "C:\Program Files (x86)\Microsoft Visual Studio" and installed again but this version 17.8.0 does not work.
I do not know how to downgrade to 17.7.0 Preview 4.0
Please, could you help me?

![image](https://github.com/dotnet/aspnetcore/assets/100200840/2987c2fa-11f2-4d89-b8dc-8671c5835105)

**Comment by nadavhury** [comment]
> Dear Team, After upgrading the Visual Studio Community 2022 (64bits) Preview to version 17.8.0 Preview 1.0 and I got the same problem. It was working well with the Visual Studio Community 2022 (64bits) 17.7.0 Preview 4.0
> 
> I need to present this project running next Wednesday (08/16/2023) I am CCT College Dublin student and it is my Final Project
> 
> My application is Blazor WebAssembly with Identity (Individual account) authenication, "Configure for HTTPS" and "ASP.NET Core hosted" I cleaned the folder "C:\Program Files (x86)\Microsoft Visual Studio" and installed again but this version 17.8.0 does not work. I do not know how to downgrade to 17.7.0 Preview 4.0 Please, could you help me?
> 
> ![image](https://user-images.githubusercontent.com/100200840/260597126-2987c2fa-11f2-4d89-b8dc-8671c5835105.png)

If you want to solve it quickly, here is what I did,

1. create a IEmailSender inside your project:
2. public interface IEmailSender
{
  /// <summary>
  /// This API supports the ASP.NET Core Identity infrastructure and is not intended to be used as a general purpose
  /// email abstraction. It should be implemented by the application so the Identity infrastructure can send confirmation emails.
  /// </summary>
  /// <param name="email">The recipient's email address.</param>
  /// <param name="subject">The subject of the email.</param>
  /// <param name="htmlMessage">The body of the email which may contain HTML tags. Do not double encode this.</param>
  /// <returns></returns>
  Task SendEmailAsync(string email, string subject, string htmlMessage);
}
3. delete the "using Microsoft.AspNetCore.Identity.UI.Services;"
4. you're good to go :-)

**Comment by ClereLearning** [comment]
Thank you very much for your time. I am going to try.

**Comment by nguyentuananh921** [comment]
> > Dear Team, After upgrading the Visual Studio Community 2022 (64bits) Preview to version 17.8.0 Preview 1.0 and I got the same problem. It was working well with the Visual Studio Community 2022 (64bits) 17.7.0 Preview 4.0
> > I need to present this project running next Wednesday (08/16/2023) I am CCT College Dublin student and it is my Final Project
> > My application is Blazor WebAssembly with Identity (Individual account) authenication, "Configure for HTTPS" and "ASP.NET Core hosted" I cleaned the folder "C:\Program Files (x86)\Microsoft Visual Studio" and installed again but this version 17.8.0 does not work. I do not know how to downgrade to 17.7.0 Preview 4.0 Please, could you help me?
> > ![image](https://user-images.githubusercontent.com/100200840/260597126-2987c2fa-11f2-4d89-b8dc-8671c5835105.png)
> 
> If you want to solve it quickly, here is what I did,
> 
> 1. create a IEmailSender inside your project:
> 
> public interface IEmailSender { Task SendEmailAsync(string email, string subject, string htmlMessage); }
> 
> 2. delete the "using Microsoft.AspNetCore.Identity.UI.Services;"
> 3. you're good to go :-)

Dear Sir.
If you want to implementation of Clean Architecture. Where should you suggest me to put IEmailSender to? Infastructure share or where ever?

**Comment by nadavhury** [comment]
> > > Dear Team, After upgrading the Visual Studio Community 2022 (64bits) Preview to version 17.8.0 Preview 1.0 and I got the same problem. It was working well with the Visual Studio Community 2022 (64bits) 17.7.0 Preview 4.0
> > > I need to present this project running next Wednesday (08/16/2023) I am CCT College Dublin student and it is my Final Project
> > > My application is Blazor WebAssembly with Identity (Individual account) authenication, "Configure for HTTPS" and "ASP.NET Core hosted" I cleaned the folder "C:\Program Files (x86)\Microsoft Visual Studio" and installed again but this version 17.8.0 does not work. I do not know how to downgrade to 17.7.0 Preview 4.0 Please, could you help me?
> > > ![image](https://user-images.githubusercontent.com/100200840/260597126-2987c2fa-11f2-4d89-b8dc-8671c5835105.png)
> > 
> > 
> > If you want to solve it quickly, here is what I did,
> > 
> > 1. create a IEmailSender inside your project:
> > 
> > public interface IEmailSender { Task SendEmailAsync(string email, string subject, string htmlMessage); }
> > 
> > 2. delete the "using Microsoft.AspNetCore.Identity.UI.Services;"
> > 3. you're good to go :-)
> 
> Dear Sir. If you want to implementation of Clean Architecture. Where should you suggest me to put IEmailSender to? Infastructure share or where ever?

Dear Friend, as you can tell this interface exists in two different libraries :) meaning it's the kind of interface you will find at the UI level and also sometimes at the Infrastructure level, it depends on how you use it.
Please note that this is only a patch until things will get fixed by the VS team. 
For everyone that implements this solution, you will need to change the "using Microsoft.AspNetCore.Identity.UI.Services;" to your own implementation in a number of files, depending on the Identity UI pages you have overridden.
