### ISSUE TITLE
Blazor hosted wasm dependent assembly loading issue in 7.0.9

### ISSUE THREAD

**Issue by gilm0079** [dotnet/aspnetcore#49685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I put a SO question out there for this as well with details. Please see [https://stackoverflow.com/questions/76781978/blazor-wasm-failing-to-run-not-finding-dependent-assemblies](https://stackoverflow.com/questions/76781978/blazor-wasm-failing-to-run-not-finding-dependent-assemblies)

I have a hosted wasm app that has been working fine for sometime (client wasm, hosting aspnetcore server, shared project). Only recently has the app failed to start up. I will throw exceptions when running Main that it can't find dependent assemblies. The assembly not found can change. If I look in the chrome browser cache the assembly exists there. The only thing that I've noticed is the assembly that wasm reports not loaded is ALWAYS all uppercased in the browser cache and blazor.boot.json. So 1) not sure why the server project is deciding to turn some assemblies into uppercase names when building the boot manifest and 2) why are the assemblies that were uppercased not being loaded into the wasm app after they are downloaded. 

I have tried directly referencing projects in the main project that failed to load so they are not dependents of dependents. That doesn't seem to help. I have tried using chrome dev tools to clear the entire cache. Doesn't seem to help. I was watching the chrome dev tools app cache window as the app loads and it seems like the dev tools drops in a big chunk of assemblies then 1-2 seconds later another chunk of assemblies. The uppercased assemblies are always in the 2nd UI refresh. Not sure if that is chrome's UI or if there is some delay going on with assembly loading or if there is if that is causing some race condition where wasm is loading assemblies before the browser has all the assemblies in cache.

I know for a long while I was on 7.0.5 with no issues then along with a VS 2022 update I was moved to the SDK that targets 7.0.9. I'd be more than happy to start looking at the webassembly source code if someone can point me to the areas responsible for generating the blazor.boot.json manifest and the webassembly code responsible for the download and integration of the assemblies from the manifest. 

I'm unable to move forward using Blazor at this point since I can't spin it up so hopefully someone can shed some light on what is happening.

### Expected Behavior

Basic functionality of blazor to load assemblies defined by the blazor.boot.json.

### Steps To Reproduce

The app I'm using is a massive enterprise app at this point. I'm not sure if I created a mini sample solution at this point it would act the same way. I'd be more than happy to run tests on my side if you have suggestions or if anyone is interested in screen sharing (unlikely, I know).

### Exceptions (if any)

System.IO.FileNotFoundException: Could not load file or assembly 'Dgc.External.Ui.BlazorWasm.Shared, Version=2023.7.14.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

File name: 'Dgc.External.Ui.BlazorWasm.Shared, Version=2023.7.14.2, Culture=neutral, PublicKeyToken=null'
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<Main>d__1](<Main>d__1& stateMachine)
at Dgc.External.Ui.BlazorWasm.Client.Startup.Program.Main(String[] args)

Error: System.IO.FileNotFoundException: Could not load file or assembly 'Dgc.External.Ui.BlazorWasm.Shared, Version=2023.7.14.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Dgc.External.Ui.BlazorWasm.Shared, Version=2023.7.14.2, Culture=neutral, PublicKeyToken=null'
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<Main>d__1](:44349/<Main>d__1& stateMachine)
   at Dgc.External.Ui.BlazorWasm.Client.Startup.Program.Main(:44349/String[] args)
    at qi (dotnet.7.0.9.spglg51993.js:5:80665)
    at Ji (dotnet.7.0.9.spglg51993.js:5:80549)
    at _Dgc_External_Ui_BlazorWasm_Client__entrypoint (_Dgc_External_Ui_BlazorWasm_Client__entrypoint:27:5)
    at dotnet.7.0.9.spglg51993.js:5:69520
    at Object.ji [as call_assembly_entry_point] (dotnet.7.0.9.spglg51993.js:5:69675)
    at Object.callEntryPoint (blazor.webassembly.js:1:46082)
    at Object.Vt [as start] (blazor.webassembly.js:1:62280)

### .NET Version

SDK 7.0.306 (7.0.9 runtime)

### Anything else?

VS 2022 Pro version 17.6.5
The solution Microsoft.AspNetCore.* packages are targeting 7.0.9

dotnet --info:
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.424 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by gilm0079** [comment]
Update: After going into the client project bin folder the problem assemblies are also uppercase there as well. I don't know what the source of those bad compilations are. If I delete the uppercase assemblies and re-build the project they are normal cased and the project works as expected. I tried building the client project, building/running the server project and changing one of the assembiles while running to see if any of those methods cause a bad compile. Nothing happened so far. If anyone has any ideas on a certain condition that would cause VS/MSBuild to compile incorrectly, lmk and I can test. Thanks.

**Comment by mkArtakMSFT** [comment]
@lewing have you seen an issue like this?

**Comment by mkArtakMSFT** [comment]
Can somebody confirm if this is still an issue for you?

**Comment by gilm0079** [comment]
I haven't had this issue occur as of late. I'm assuming that it was fixed in a release after 7.0.9.
