### ISSUE TITLE
Add a method to efficiently bulk create users in ASP.NET Identity.

### ISSUE THREAD

**Issue by skillmaker-dev** [dotnet/aspnetcore#49701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to create a list of users using an excel file that has more than 2k rows but when I use the already existing method to create a single user it takes a long time to finish. 

### Describe the solution you'd like

It would be nice to add an efficient bulk create users method that can help with these situations.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. How much slow is it?
Can you share some more details about the performance expectations as well as what you observe?
