### ISSUE TITLE
border property for img not working on chrome browser

### ISSUE THREAD

**Issue by soren-sr** [dotnet/aspnetcore#49724]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

border property for img tag not working on chrome
(other properties working!)

for example i have the following code in my index.cshtml
`<img src="/img.png" style="border: 10px solid red">`

asp.net mvc project
framework: net7.0
chrome version: 115.0.5790.110 (latest version)

**Comment by javiercn** [comment]
@soren-sr thanks for contacting us.

This doesn't seem like an asp.net core specific issue, but an issue in your styles. If you grab the markup from the page, add it to a static HTML page, and serve that from the same server. Does it work?
