### ISSUE TITLE
Provide a way to persist prerendered state when using Blazor server-side rendering

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49733]
We provide a `persist-component-state` tag helper for persisting state used during prerendering from an MVC view or Razor Page. We need a way to persist the component state from a Blazor component when using server-side rendering (SSR).

**Comment by Alerinos** [comment]
This is quite problematic, for example if we want to transport cookies then we have to go through "Component"
Example:
```razor
    <component type="typeof(Areas.Web.App)"
               render-mode="ServerPrerendered"
               param-GetIP="@GetIP"
               param-GetAgent="@GetAgent"
               param-GetCookies="@GetCookies"
               param-SessionUser=@SessionStat.User />
 ```
If this is not done, we have this effect.
The first reload (server) is correct, the second reload causes the Scope circuit to disappear.
https://gyazo.com/dcae15aebf6269f1023a8f185920a9e1

**Comment by oliverw** [comment]
So how is this now actually done from an application perspective?

**Comment by marinasundstrom** [comment]
@oliverw It's documented here:

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&pivots=webassembly#persist-prerendered-state

**Comment by oliverw** [comment]
> @oliverw It's documented here:
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&pivots=webassembly#persist-prerendered-state

Thanks. Not sure if that has been updated for Blazor 8 Web Apps.

**Comment by marinasundstrom** [comment]
@oliverw Woops. It was the wrong link: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0#persist-prerendered-state

**Comment by oliverw** [comment]
> @oliverw It's documented here:
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&pivots=webassembly#persist-prerendered-state

Thanks again. Is that supposed to work with `@rendermode InteractiveAuto` ?

**Comment by marinasundstrom** [comment]
@oliverw Yes. Since it works with both ``InteractiveServer`` and ``InteractiveWebAssembly`` when components are prerendered.

**Comment by oliverw** [comment]
> @oliverw Yes. Since it works with both `InteractiveServer` and `InteractiveWebAssembly` when components are prerendered.

Cool. Trying it out 😄

**Comment by marinasundstrom** [comment]
@oliverw 👍🏻 🙂 If you want an example, then there is this: https://github.com/marinasundstrom/Blazor8Test/blob/main/src/Client/Pages/FetchData.razor
