### ISSUE TITLE
Anchor Links Not Working

### ISSUE THREAD

**Issue by techbud** [dotnet/aspnetcore#49737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have an anchor link within a page, the anchor links do not work.

### Expected Behavior

If you have an anchor link it should scroll to the section where the id is a match.

### Steps To Reproduce

https://github.com/techbud/TestAnchor

### Exceptions (if any)

There is no exception thrown

### .NET Version

7.0.304

**Comment by gragra33** [comment]
Appears to be an error in the sample code with the problem.

```html
<p id="#test">Hell, this is some more text</p>
```
should be:
```html
<p id="test">Hell, this is some more text</p>
```

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @gragra33 !

**Comment by techbud** [comment]
Yeah, I whipped it together, but that still doesn't fix the problem, anchor link still doesn't work

**Comment by gragra33** [comment]
@techbud I've installed VS2022 preview with .Net 8 (latest preview), ran your code. with the following modification:
```html
<p id="test">Hell, this is some more text</p>
```

The index.razor page loaded. Then I used the browser navbar with:
```text
https://localhost:7026/#test
```
and it navigated to the element successfully.

I saw that you are **targeting the wrong version of .Net**. Here is your csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```
And here is what you _should be_ using:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```
Next I rebuild the app, with the modified csproj, and run. I click on the `NavLink` in the side menu and navigation works.

**Conclusion:** You need to make the above two modifications and you will find it will correct your issue.

**Side Note:** If you experience compile errors when targeting .Net 8, check that both the x64 & x86 SDKs are installed.

Hope this helps!
