### ISSUE TITLE
OauthMiddleware  contains 'Correlation failed' error;

### ISSUE THREAD

**Issue by misaya** [dotnet/aspnetcore#49741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The issue caused the following code.
The CorrelationCookie in OAuthOptions must be assigned a value, but the CorrelationCookie has already been assigned in the constructor of OAuthOptions' base class RemoteAuthenticationOptions OAuthOptions must call base() when constructing to comply with common sense;

```csharp
// Add services to the container.
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = "OAuthProvider";
    })
    .AddCookie()
    .AddOAuth("OAuthProvider", options =>
    {
        options.ClientId = builder.Configuration["Authentication:OAuth:ClientId"];
        options.ClientSecret = builder.Configuration["Authentication:OAuth:ClientSecret"];
        options.AuthorizationEndpoint = builder.Configuration["Authentication:OAuth:AuthorizationEndpoint"];
        options.TokenEndpoint = builder.Configuration["Authentication:OAuth:TokenEndpoint"];
        options.UserInformationEndpoint = builder.Configuration["Authentication:OAuth:UserInformationEndpoint"];
        options.CallbackPath = new PathString("/payadmin/OAuth/AuthorizationCodeCallback");
        options.SignInScheme = "Cookies";
        options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "workId");
        options.ClaimActions.MapJsonKey(ClaimTypes.Name, "name");
        options.SaveTokens = true;
        options.Scope.Add("read");
        
        //here ,here !!
        options.CorrelationCookie = new RequestPathBaseCookieBuilder();
    });
```

### Expected Behavior

I suggest making the following repairs in OAuthOptions
```
public OAuthOptions() : base()
        {
            Events = new OAuthEvents();
        }
```

just add ```base()``

## An unhandled exception occurred while processing the request.
Exception: Correlation failed.

Unknown location

### Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

### Stack Query Cookies Headers Routing
Exception: Correlation failed.

### Show raw exception details
System.Exception: Correlation failed.
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Show raw exception details
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by misaya** [comment]
I submitted a PR for this:   https://github.com/dotnet/aspnetcore/pull/49742/files

**Comment by Tratcher** [comment]
The PR is based on a missunderstanding of C# and wouldn't have any effect. https://github.com/dotnet/aspnetcore/pull/49742/files#r1279376979

`Correlation failed.` is usually caused by issues with the temporary cookies used during the auth flow. You can collect Debug level server logs and a Fiddler trace to look for more details about the error and the response cookies.
