### ISSUE TITLE
AdditionalAssemblies not working properly in new version of Blazor Web App

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#49759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While migrating to the new version of the Blazor App I encountered a problem, when using AdditionalAssemblies then pages from other solutions do not work.
```razor
<Router AppAssembly="@typeof(App).Assembly"
            AdditionalAssemblies="new[] { typeof(RazorClassLibrary1.Test).Assembly }">
```
Repository:
https://github.com/Alerinos/AdditionalAssembliesBug

### .NET Version

8 preview 6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We think this will be addressed as part of #49756
