### ISSUE TITLE
SaveToken on JwtBearer Authentication Handler doesn't work if TokenValidated Event Sets Result

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#49769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In JwtBearer authentication, `SaveToken` would not work when the `TokenValidated` event sets the result. The reason for this bug is that currently `SaveToken` is checked after firing the `TokenValidated` event and if the event sets a result the code would return it.

https://github.com/dotnet/aspnetcore/blob/c64d745c863088e6bb6390984b7fe93782e686c3/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L162-L174

**Solution:**
Move the `SaveToken` section of the code before calling the event.

**Workaround:**
Set the token in the `TokenValidated` event.

### Expected Behavior

I expect to have the token even if `TokenValidated` events has been set.
```csharp
var token = HttpContext.Features.Get<IAuthenticateResultFeature>().AuthenticateResult.Properties.GetTokenValue("access_token");
```

### Steps To Reproduce

**Startup.cs**
```csharp
services.AddAuthentication()
  .AddJwtBearer(TokenDefaults.OAuthScheme, options =>
  {
      options.SaveToken = true;
      options.Events = new JwtBearerEvents
      {
          OnTokenValidated = context => ..., //This code sets the context result
      };
  })
```

**Controller.cs**
```csharp
var token = HttpContext.Features.Get<IAuthenticateResultFeature>().AuthenticateResult.Properties.GetTokenValue("access_token");
```

The `token` is null!

**Comment by halter73** [comment]
We generally short-circuit when an event handler sets `ResultContext.Result`, so I'm inclined to say it's by design. Why is the `OnTokenValidated` setting the `Result` rather than the `SecurityToken`? I'd expect `SaveToken` to work if you do the latter.

**Comment by Kahbazi** [comment]
@halter73 Oh, you are right. In the success path I just need to set `ClaimsPrincipal` and not call `Success()`. Removing `Success()` solved my problem.
