### ISSUE TITLE
Rename Microsoft.AspNetCore.Testing

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#49776]
Microsoft.AspNetCore.Testing is a non-published project/package with unit testing resources for the repo.

There's a new project with the same name at https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.AspNetCore.Testing that's intended for release as a public package. While we don't expect to immediately consume the new package in AspNetCore, we may someday. Also, having two similar projects with the same name is going to be confusing.

Let's rename the non-published project and namespaces in AspNetCore. Suggestions:
- Microsoft.AspNetCore.TestUtils
- Microsoft.AspNetCore.InternalTesting
- Microsoft.AspNetCore.Testing.Internal

**Comment by RussKie** [comment]
Related https://github.com/dotnet/extensions/issues/4057#issuecomment-1660927215

**Comment by RussKie** [comment]
This work should be prioritised, at least disable publishing of the project to the BAR to avoid issues similar to https://github.com/dotnet/dnceng/issues/174.

**Comment by joperezr** [comment]
@wtgodbe Do we know  if there are any consequences of stopping pushing this particular assembly to BAR? If not, could you work with @RussKie in order to disabling that?

**Comment by wtgodbe** [comment]
Sorry, was OOF. I think that nobody depends on the `Microsoft.Aspnetcore.Testing` package from this repo anymore (it used to be built by dotnet/extensions) - I'll try to confirm that, then just turn off the package build entirely. That should solve the problem for 8. We should probably rename it for either 8 or 9 though, to avoid any confusion.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/49846

**Comment by wtgodbe** [comment]
It's no longer a package as of https://github.com/dotnet/aspnetcore/pull/49846, which should prevent any DARC issues. Next step is to do the rename, which we can take care of after 8 cools down.

**Comment by RussKie** [comment]
> Thanks so much @wtgodbe Will Godbe FTE! @RussKie Igor Velikorossov FTE can we re-enable publishing to DARC for this package in dotnet/extensions? We should do that as well in the preview7 branch if we haven't.

We're already publishing it for the main. I'll publish it for P7 as well.

**Comment by wtgodbe** [comment]
I'd like to leave this open to track renaming the test library in aspnetcore (in .Net 9), to avoid any dev confusion.

**Comment by wtgodbe** [comment]
The rename is done (`Microsoft.AspNetCore.InternalTesting`)
