### ISSUE TITLE
Support for attribute grouping to aid in statement completion in editors

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#4979]
In cases where a Tag Helper has multiple attributes that must be used together to correctly configure and thus enable a particular function, it would be useful to be able to indicate this grouping so that editors could suggest that use of one attribute requires another.

We tend not to throw runtime exceptions in Tag Helpers for these cases so as to not add extra "overhead" to the normal flow of using HTML & C# together, aka normal Razor.

Some suggested approaches:

``` C#
// This approach allows any property to be associated with another (its partners) via an attribute.
// Only one property in any given set needs to be decorated with the attribute, the inverse relationship is implied.
public class MyTagHelper : TagHelper
{
    [PartnerAttributesHint("category")]
    public string Name { get; set; }
    public string Category { get; set; }
    ...
}

// This attribute allows sets of attributes to be declared on the class, with the HTML attribute names passed in.
// Multiple sets would be supported on the class.
[AttributeSetHint("name", "category")]
public class MyTagHelper : TagHelper
{
    public string Name { get; set; }
    public string Category { get; set; }
    ...
}

// This approach allows any property to be added to an arbitrary attribute set by name.
// The name itself isn't important, they just need to be consistent across the properties in that set.
public class MyTagHelper : TagHelper
{
    [AttributeSetHint("set1")]
    public string Name { get; set; }
    [AttributeSetHint("set1")]
    public string Category { get; set; }
    ...
}
```

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
