### ISSUE TITLE
"Adding `@ref` to a RenderFragment in C# - Seeking Guidance"

### ISSUE THREAD

**Issue by anan1213095357** [dotnet/aspnetcore#49839]
I need to include `@ref` in the following code block:

```
RenderFragment renderFragment = (build) =>
{
    build.OpenComponent<PLCInput>(0);
    build.AddAttribute(1, "Style", $"position:absolute;top:{currentControldragY}px;left:{currentControldragX}px;");
    build.CloseComponent();
};
```

What is the correct way to achieve this?

**Comment by gragra33** [comment]
@anan1213095357 When manually generating a `RenderFragment` using the `RenderTreeBuilder`, I let the compiler do the hard work for the more involved code, like yours. Work smart, not hard. 😉

I create a dummy blank project, add the HTML to a test razor page, and any supporting code. Try and keep it to a minimum. Then modify the `.csproj` file with the following:
```xml
<PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
```
Now compile the project, go to the `obj` folder and locate the output. For me it is `\obj\Debug\net7.0\generated\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator`.

If your razor page is file `Test.razor`, look for `Test.razor.g.cs`, then find the required code.

Hope this helps.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @anan1213095357.

I've put the answer below, hidden in case you wanted to follow @gragra33's suggestion and look at the Razor Compiler's output to discover the solution 🙂 

<p>
<details>
<summary>Click to reveal</summary>

[RenderTreeBuilder.AddComponentReferenceCapture](https://source.dot.net/#Microsoft.AspNetCore.Components/Rendering/RenderTreeBuilder.cs,af8100c5dd9e16e3,references)

</details>
</p>
