### ISSUE TITLE
[SignalR-Cpp-Client] Streaming support

### ISSUE THREAD

**Issue by Wasenshi123** [dotnet/aspnetcore#49863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Does SignalR cpp client support streaming, or would it?

I have need to use streaming because some files to send to server might be huge.

### Describe the solution you'd like

Would be nice to support streaming for cpp too.

**Comment by BrennanConroy** [comment]
It does not support streaming today. Tracked via https://github.com/dotnet/aspnetcore/issues/8714
Biggest problem is figuring out what type to use for the streaming abstraction. There isn't anything obvious to use in the STL, so we'd either need to invent a thing, or take a dependency on another library.

**Comment by adityamandaleeka** [comment]
Closing this issue. Let's keep discussion in #8714 so it's all in one place.
