### ISSUE TITLE
Selenium updates are broken

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#49869]
Chrome has recently changed where they put versioned browser downloads. See https://chromedriver.chromium.org/downloads
> If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.

We update the Chrome version in https://github.com/dotnet/aspnetcore/blob/d63989865d30870c7bf0b0b0aa13f6981bd97f22/src/Shared/E2ETesting/selenium-config.json#L4 but the [selenium-standalone](https://www.npmjs.com/package/selenium-standalone) npm package we're using doesn't support version 115+ downloads and looks like it likely never will: https://github.com/webdriverio/selenium-standalone/issues/810

Even if it did add support for v115+, we'd need to update our npm reference which is unlikely, see https://github.com/dotnet/aspnetcore/pull/44834

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/50511

**Comment by surayya-MS** [comment]
Reopenning because the fix was reverted https://github.com/dotnet/aspnetcore/pull/50556

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/51775
