### ISSUE TITLE
Tool for tracking changes by Blazor

### ISSUE THREAD

**Issue by pekspro** [dotnet/aspnetcore#49867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blazor is making changes to the DOM that works most of the time. But sometimes you mess up and do something that triggered thousands of unnecessary changes in the DOM and this could be very hard to detect. 

### Describe the solution you'd like

I would like to have some tooling that makes it easy to see which changes are done in the DOM via Blazor. Both how many changes are done on every update, and some detailed log on exact which changes were made. This would make it easier to troubleshoot and detect any potential performance issues.

### Additional context

I have created a super simple JavaScript tool that logs every change in the DOM. Not perfect, but better than nothing:

```javascript
function startMutationMonitoring(elementId = document, outputId) {
    // Get the target node
    const targetNode = elementId === document ? document : document.getElementById(elementId);

    // Get the element that we'll output the logs to
    const monitorLog = outputId ? document.getElementById(outputId) : null;

    // Options for the observer (which mutations to observe)
    const config = { attributes: true, childList: true, subtree: true, characterData: true };

    // Callback function to execute when mutations are observed
    const callback = function (mutationsList, observer) {
        const timestamp = new Date().toLocaleTimeString();

        for (let mutation of mutationsList) {
            let outputText = `${timestamp} Mutation type: ${mutation.type}`;

            if (mutation.type === 'childList') {
                for (let addedNode of mutation.addedNodes) {
                    outputText += '\nAdded Node id: ' + addedNode.id;
                    outputText += '\nAdded Node HTML: ' + addedNode.outerHTML;
                }

                for (let removedNode of mutation.removedNodes) {
                    outputText += '\nRemoved Node id: ' + removedNode.id;
                    outputText += '\nRemoved Node HTML: ' + removedNode.outerHTML;
                }

            } else if (mutation.type === 'attributes') {
                outputText += ', attribute changed: ' + mutation.attributeName;
                outputText += ', new value: ' + mutation.target.getAttribute(mutation.attributeName);
            } else if (mutation.type === 'characterData') {
                outputText += ', content changed: ' + mutation.target.data;
            }

            outputText += '\n\n';

            if (monitorLog) {
                let textNode = document.createTextNode(outputText);
                monitorLog.appendChild(textNode);
            } else {
                console.log(outputText);
            }
        }
    };

    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(callback);

    // Start observing the target node for configured mutations
    observer.observe(targetNode, config);
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The workaround you've found with using MutationObserver is what we would recommend for now.
We will keep this issue on our backlog to for future consideration to potentially address this in a better way.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
