### ISSUE TITLE
Authentication and Authorization in Blazor Web App for .net 8

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#49870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have an existing blazor application in WASM. We also support a separate version using Blazor Server. Both the version are integrated with an OIDC Auth Provider using the approaches outlined for Blazor WASM and Blazor Server. We would like to move to .net8 to merger these into one project. However, we can't find any guidance on how to use the new AuthenticationStateProvider in .net 8 when we have streamrendering, mixed with server pages as well as WASM.

### Describe the solution you'd like

A guidance or some pointers on how will the security work from current WASM/Server apps to the new model. The demos look really great moving from WASM to Server and server rendering but there is no guidance how to merge authenticated apps across those models? Is there is common authentication state provider? What is the recommended approach.

**Comment by johnpeeke** [comment]
I too have questions regarding this. It seems when using the new blazor template, no AuthenticationStateProvider is registered. For instance, simply adding the required services and middleware for cookie authentication and then using the CascadingAuthenticationState around the App component throws a runtime exception that there is no registered service of Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider. I am forced to create a CustomAuthenticationStateProvider. Any help would be appreciated!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something on our radar and we're trying to address as part of https://github.com/dotnet/aspnetcore/issues/48772
