### ISSUE TITLE
CORS setup not working properly with a fresh Blazor WebAssembly Hosted app

### ISSUE THREAD

**Issue by uhfath** [dotnet/aspnetcore#49871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure where I'm wrong.
After creating a default Blazor WebAssembly ASP.NET Core Hosted app CORS is not configured. As a result any requests from the WebAssembly parts to other origins gets blocked by browser.

Created a project using this template:
![image](https://github.com/dotnet/aspnetcore/assets/14792749/e5f6218b-8a4b-451c-bb5a-2642214a2e12)

This is how my setup looks to overcome this issue:
```c#
public static void Main(string[] args)
{
    var builder = WebApplication.CreateBuilder(args);

    builder.Services.AddControllers();

    builder.Services.AddCors(opts => opts.AddDefaultPolicy(bld => // <-- added this
    {
        bld
            .AllowAnyOrigin()
            .AllowAnyMethod()
            .AllowAnyHeader()
            .WithExposedHeaders("*")
        ;
    }));

    var app = builder.Build();

    if (app.Environment.IsDevelopment())
    {
        app.UseWebAssemblyDebugging();
    }
    else
    {
        app.UseExceptionHandler("/Error");
    }

    app.UseBlazorFrameworkFiles();
    app.UseStaticFiles();

    app.UseRouting();
    app.UseCors(); // <-- and added this

    app.MapControllers();
    app.MapFallbackToFile("index.html");

    app.Run();
}
```

This is done in a server part (the one that hosts the static files for a browser to download).
To test this I've added a simple request in a `FetchData.razor` page:
```c#
protected override async Task OnInitializedAsync()
{
    await Http.GetAsync("https://google.com"); // <-- this line was added
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");
}
```
But I still get CORS error:
> Access to fetch at 'https://google.com/' from origin 'http://localhost:5174' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It seems that CORS headers are not added to request responses (neither for files or controllers) but I'm not sure why:
[![enter image description here][1]][1]

What am I missing?

Tested on a .NET 7.

  [1]: https://i.stack.imgur.com/sTwbh.png

### Expected Behavior

The `HttpClient` requests to other origins should work without CORS errors.

### Steps To Reproduce

1. Create a default Blazor WebAssembly ASP.NET Core Hosted
2. Add CORS setup as described
3. Add simple http request in a `FetchData.razor`
4. Launch and check the console for errors

### Exceptions (if any)

> Access to fetch at 'https://google.com/' from origin 'http://localhost:5174' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### .NET Version

7.0.306

**Comment by BrennanConroy** [comment]
That's expected behavior. You can see this by using fetch yourself in the browser: `await fetch("https://google.com")` will fail with the same CORS error.

If you want to allow an external request to a server you don't control you need to [set the request credentials](https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-7.0&pivots=webassembly#httpclient-and-httprequestmessage-with-fetch-api-request-options) when sending a request:
```
var requestMessage = new HttpRequestMessage(HttpMethod.Get);
requestMessage.SetBrowserRequestCredentials(BrowserRequestCredentials.Omit);
await Http.SendAsync(requestMessage);
```

The server CORS settings you show above aren't relevant here, it's google.com that is denying your http request.

**Comment by uhfath** [comment]
Somehow I thought that CORS headers has to be added by my server with served files (html, js, etc.) and after that they will be used by a browser. Guess I wasn't careful enough when reading the docs. Thanks for the help. It makes sense now. Currently I've setup a proxy that adds appropriate headers to handle my case.
