### ISSUE TITLE
Extended IdentityDbContext doesn't add migration he exception 'Cannot use table 'CFGPerfilClaim' for entity type 'PerfilClaim' since it is being used for entity type 'IdentityRoleClaim<int>' and potentially other entity types

### ISSUE THREAD

**Issue by luizfbicalho** [dotnet/aspnetcore#49878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a dbcontext with the classes that extend the AspnetCore Identity Classes

Then I just added an migration and got this error

```
Add-Migration Base
Build started...
Build succeeded.

    Unable to create a 'DbContext' of type ''. The exception 'Cannot use table 'CFGPerfilClaim' for entity type 'PerfilClaim' since it is being used for entity type 'IdentityRoleClaim<int>' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'PerfilClaim' on the primary key properties and pointing to the primary key on another entity type mapped to 'CFGPerfilClaim'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```
  

### Expected Behavior

I expected the creation of the migration.

Looks like there is something in the 

`base.OnModelCreating(builder);`

that is messing the migration

### Steps To Reproduce

1) clone the https://github.com/luizfbicalho/TesteAspnetIdentityMirgation
2) add migration with command Add-Migration Base
3) see the error

### .NET Version

8.0.100-preview.6.23330.14

### Anything else?

.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

C:\Program Files\Microsoft Visual Studio\2022\Preview>

**Comment by Cassinotte** [comment]
Hello, I am also having a similar problem, I am adding myself in the question for follow-up

**Comment by mkArtakMSFT** [comment]
@luizfbicalho have you tried to follow the suggestion provided by the error message?

/cc @ajcvickers

**Comment by ajcvickers** [comment]
@luizfbicalho Customizing the ASP.NET Core Identify model is very difficult. Make sure to fully understand and follow the instructions here: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-7.0

**Comment by halter73** [comment]
```csharp
    public class ModelContext : IdentityDbContext<Identidade, Perfil, int, IdentidadeClaim, IdentidadePerfil, IdentidadeLogin, PerfilClaim, IdentidadeToken>
    {
        public ModelContext(DbContextOptions<ModelContext> options) : base(options) { }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<Perfil>().ToTable("CFGPerfil");
            builder.Entity<Identidade>().ToTable("CFGIdentidade");
            builder.Entity<IdentityUserClaim<int>>().ToTable("CFGIdentidadeClaim").HasKey(x => new { x.Id });
            builder.Entity<IdentityUserRole<int>>().ToTable("CFGIdentidadePerfil").HasKey(x => new { x.UserId, x.RoleId });
            builder.Entity<IdentityUserLogin<int>>().ToTable("CFGIdentidadeLogin").HasKey(x => new { x.UserId, x.LoginProvider });
            builder.Entity<IdentityUserToken<int>>().ToTable("CFGIdentidadeToken").HasKey(x => new { x.UserId, x.LoginProvider, x.Name });
            builder.Entity<IdentityRoleClaim<int>>().ToTable("CFGPerfilClaim").HasKey(x => new { x.Id });

            builder.Entity<IdentidadeClaim>().ToTable("CFGIdentidadeClaim");
            builder.Entity<IdentidadePerfil>().ToTable("CFGIdentidadePerfil");
            builder.Entity<IdentidadeLogin>().ToTable("CFGIdentidadeLogin");
            builder.Entity<IdentidadeToken>().ToTable("CFGIdentidadeToken");
            builder.Entity<PerfilClaim>().ToTable("CFGPerfilClaim");
        }
    }

    public class IdentidadeToken : IdentityUserToken<int> { }
    public class PerfilClaim : IdentityRoleClaim<int> { }
    public class IdentidadeLogin : IdentityUserLogin<int> { }
    public class IdentidadePerfil : IdentityUserRole<int> { }
    public class IdentidadeClaim : IdentityUserClaim<int> { }
    public class Perfil : IdentityRole<int> { }
    public class Identidade : IdentityUser<int> { }
```

I'm not an EF expert, but `PerfilClaim` is your `IdentityRoleClaim<int>`, so why is there both `builder.Entity<IdentityRoleClaim<int>>().ToTable("CFGPerfilClaim").HasKey(x => new { x.Id });` and `builder.Entity<PerfilClaim>().ToTable("CFGPerfilClaim");`? It seems redundant.

`base.OnModelCreating(builder)` already sets up the foreign key relationships for all of its entities that are configured via generic parameters. If you just want to rename the tables, couldn't you just do that and leave the rest default?

```csharp
base.OnModelCreating(builder);

builder.Entity<Perfil>().ToTable("CFGPerfil");
builder.Entity<Identidade>().ToTable("CFGIdentidade");
builder.Entity<IdentidadeClaim>().ToTable("CFGIdentidadeClaim");
builder.Entity<IdentidadePerfil>().ToTable("CFGIdentidadePerfil");
builder.Entity<IdentidadeLogin>().ToTable("CFGIdentidadeLogin");
builder.Entity<IdentidadeToken>().ToTable("CFGIdentidadeToken");
builder.Entity<PerfilClaim>().ToTable("CFGPerfilClaim");
```

**Comment by luizfbicalho** [comment]
The problem was in another place in reality


```
System.InvalidOperationException

  HResult=0x80131509

  Message=Cannot create a DbSet for 'IdentityUserClaim<int>' because this type is not included in the model for the context.

  Source=Microsoft.EntityFrameworkCore

  StackTrace:

   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType() in /_/src/EFCore/Internal/InternalDbSet.cs:line 84

```

My first idea was to add both DbSets in my dbcontext, but I got this error

To solve my problem I added this code to startup
`
  .AddUserStore<UserStore<Identidade, Perfil, DbContext, int, IdentidadeClaim, IdentidadePerfil, IdentidadeLogin, IdentidadeToken, PerfilClaim>>()`


I have a question for @ajcvickers 

Shoudn't be better in a Object oriented way that the Identity DbContext to have both Base entities and derived entities?

I mean shoudn't be able to get context.Set<IdentityRoleClaim<int>>() and context.Set<PerfilClaim>() pointing to the same table?

**Comment by luizfbicalho** [comment]
Ok, this problem is solved let's see if in the future we have any changes in this project
