### ISSUE TITLE
Async code fails when called from OnInitializedAsync

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#49888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

	public async Task<DataSet> ExecuteDataset(string sql, CommandType commandType, OdbcParameter[] parms)
    {
        using (OdbcConnection con = new OdbcConnection(connectionString))
        {
            using (OdbcDataAdapter da = new OdbcDataAdapter(sql, con))
            {

                da.SelectCommand.CommandType = commandType;
                da.SelectCommand.Parameters.AddRange(parms);
                DataSet ds = new DataSet();
                await Task.Run(() => da.Fill(ds)); 
                return ds;
            }
        }
    }
	
	
I am using a MudBlazor table - when the above code is called from the ServerData event as shown below the above code works fine:

		<MudTable ServerData="@(new Func<TableState, Task<TableData<User>>>(LoadData))" @ref="itemsTable" Dense="true" Hover="true" FixedHeader="true" FixedFooter="true" Height="100%" RowsPerPage="100"

	
However if I call the above code from `OnInitializedAsync` I get the exception shown below (there is no additional stack trace)

	protected override async Task OnInitializedAsync()
		{
			await base.OnInitializedAsync();
			var stuff = await userService.GetAllUsers(); 	// Exception here
	

How can I fix this?  I need to load data before the control is rendered.  I have tried changing `render-mode` from `ServerPrerendered` to `Server` but it does not fix the issue.
Running net 7.

	

### Exceptions (if any)

>System.NullReferenceException
>  HResult=0x80004003
>  Message=Object reference not set to an instance of an object.
>  Source=GunCalibration
>  StackTrace:
>   at MyProject.Pages.Editor.<BuildRenderTree>b__0_3(RenderTreeBuilder __builder4)

### .NET Version

7.0.306

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

The behavior you're observing is by-design. Blazor components don't wait for `OnInitializeAsync` to complete before rendering. This can result in data that gets initialized in OnInitializedAsync() being null on the first render. Your markup code should be updated to account for a null dataset.
When the async code completes (the dataset initialization), the component will be re-rendered and the dataset will be available already.

**Comment by sam-wheat** [comment]
Thank you for the response @mkArtakMSFT 

I understand this behavior is by design.

I recognize this is NOT a bug.

I acknowledge that Blazor is working correctly, and as designed.

Now, with that said, I need to load data asynchronously and render it in my page.  

How do I do that?  

> Your markup code should be updated to account for a null dataset.

My markup code will handle a null dataset:

    var stuff = await userService.GetAllUsers(); 	// Exception here

The more likely story is that this code has no place to return to:

    await Task.Run(() => da.Fill(ds));

**Comment by sam-wheat** [comment]
@sake402 
@mkArtakMSFT 

Gentlemen the code is not failing in the UI it is failing in the call to the database.

using System.Data.Odbc nuget package version 7.0.0

Call this method from 'OnInitializeAsync ' and it will fail.

I am sorry I cannot write a project for you at this moment but I will try to put something together later next week. 


    public async Task<DataSet> ExecuteDataset(string sql, CommandType commandType, OdbcParameter[] parms)
    {
        using (OdbcConnection con = new OdbcConnection(connectionString))
        {
            using (OdbcDataAdapter da = new OdbcDataAdapter(sql, con))
            {

                da.SelectCommand.CommandType = commandType;
                da.SelectCommand.Parameters.AddRange(parms);
                DataSet ds = new DataSet();
                await Task.FromResult(0);
                da.Fill(ds);
                //await Task.Run(() => da.Fill(ds)); FAILS - no exception in Task contionuation - am checking IsFaulted
				return ds;
            }
        }
    }

**Comment by guardrex** [comment]
# :eyes: 🦖 

I'm keeping an eye on this one in case your, @sam-wheat, situation requires further guidance than what we have in the *Lifecycle* article.

**Comment by sam-wheat** [comment]
@guardrex  Very kind of you, thanks much.  I am demoing code to the client tomorrow after which I can hopefully spend some time building out a repro.  Problem in this case is that client is using DB2 via ODBC which may add some complexity.

**Comment by guardrex** [comment]
@sam-wheat ... Based on the types shown, the C# code and the Razor markup don't align. `ExecuteDataset` isn't shown in the Razor markup, and no C# code shows `LoadData`. The concept discussed earlier by Artak and @sake402 is covered at [Handle incomplete async actions at render](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-7.0#handle-incomplete-async-actions-at-render) in the *Lifecycle* article.

When you reach this for further work, confirm that Razor markup checks for null before the object is used. When the Task has returned, the object is no longer `null`, and the component is rerendered, the NRE should go away ... *in theory* 🤞😄 ... and *if that is the problem* 🍀😄.

**Comment by sam-wheat** [comment]
@guardrex 

OK I did spend some on educating myself on this issue.  The fooler was that that `ds.Fill(...)` was not failing because I was just loading a bit of data.  `Task.Run(() => ds.Fill(...))`, however, was failing every time.  

IDK why Blazor does wait on `OnInitializedAsync` or provide a method it will wait on.    In the code below the page is blank for ten seconds so it seems like not awaiting buys me nothing except now I have to wrap my ui in a thousand `if( not null) {...}` statements.  

The blank page can be demonstrated trivially by putting `await Task.Delay(10000);` in `OnInitializedAsync` in `Index.razor` in any Blazor project.  If I was getting any bang for my "not awaiting" buck I should start to see a page render immediately - do you not agree?


 



	@page "/"
	@using System.Data;
	@using System.Data.Odbc;

	<PageTitle>Index</PageTitle>

	<select>
		@if (data is not null)
		{
			@foreach (string s in data)
			{
				<option value="@s">@s</option>
			}
		}
	</select>
	@code{

		private List<string> data;

		protected override async Task OnInitializedAsync()
		{
			await base.OnInitializedAsync();
			data = await LoadData();
		}


		private async Task<List<string>> LoadData()
		{
			DataSet ds = await ExecuteDataset("select id from your.table", CommandType.Text, new OdbcParameter[0]);

			System.Diagnostics.Debug.Assert(ds is not null);
			System.Diagnostics.Debug.Assert(ds.Tables.Count > 0);
			System.Diagnostics.Debug.Assert(ds.Tables[0].Rows.Count > 0);

			List<string> data = new();

			DataRowCollection rows = ds.Tables[0].Rows;

			for (int i = 0; i < rows.Count; i++)
			{
				string field = rows[i]["ID"].ToString().Trim();
				data.Add(field);
			}
			return data;
		}


		protected async Task<DataSet> ExecuteDataset(string sql, CommandType commandType, OdbcParameter[] parms)
		{
			try
			{
				using (OdbcConnection con = new OdbcConnection("your connection string"))
				{
					using (OdbcDataAdapter da = new OdbcDataAdapter(sql, con))
					{

						da.SelectCommand.CommandType = commandType;
						da.SelectCommand.Parameters.AddRange(parms);
						DataSet ds = new DataSet();

						bool taskRun = false;

						if(! taskRun)
						{
							// Blazor does not fail if only a small amount of data is loaded quickly
							await Task.Delay(10000); 
							da.Fill(ds); 
						}
						else
						{
							// Blazor fails every time
							await Task.Run(() => da.Fill(ds)).ContinueWith(t =>
							{
								if (t.IsFaulted)
								{

									string y = t.Exception.ToString();
									Console.WriteLine(y);
								}

							});
						}
						return ds;
					}
				}
			}
			catch (Exception ex)
			{
				string y = ex.Message.ToString();
				Console.WriteLine(y);
				return null;
			}
		}
	}

**Comment by sam-wheat** [comment]
@guardrex 
> As you see in the docs, that's the part that we cover, and I just wanted to make sure that there's nothing else to cover on that point.

Are you saying I don't have to write dozens of null checks?  What do you mean here?

>That's not my experience and doesn't match the guidance provided by engineering,

If you create a brand new blazor app from the VS template and add the delay statement as described above - are you saying the ui renders immediately?

**Comment by guardrex** [comment]
> Are you saying I don't have to write dozens of null checks?

Yes, that's what's called for if you have many objects that might be null when initially rendered and they can't be grouped into one or a few null checks around Razor markup that would render those objects. I can see how if there were a bunch of objects with individual checks that it would seem like a lot of boilerplate; but AFAIK, that's the correct approach to take in that scenario.

> If you create a brand new blazor app from the VS template and add the delay statement as described above - are you saying the ui renders immediately?

Awaiting a `Task` doesn't block the rendering thread in the simplest case AFAIK. You'd need to show a repro of what you mean because I haven't seen such blocking behavior for that simple case.
