### ISSUE TITLE
I'm not sure what you mean by a real world example, but you can look at how the authenticator token provider as an example: https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs

### ISSUE THREAD

**Issue by HAMANZ** [dotnet/aspnetcore#49883]
I'm not sure what you mean by a real world example, but you can look at how the authenticator token provider as an example: https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs

_Originally posted by @HaoK in https://github.com/dotnet/aspnetcore/issues/37555#issuecomment-944457615_

**Comment by HAMANZ** [comment]
can you give more details I use it in startup.cs

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please provide complete details about what this issue is about and what you're trying to achieve.
