### ISSUE TITLE
Add Streaming Rendering &  Enhanced Navigation to Razor Pages & MVC

### ISSUE THREAD

**Issue by meisam-dehghan** [dotnet/aspnetcore#49892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

@danroth27 One of the cool features of Blazor in .Net 8 is Streaming Rendering along with Enhanced Navigation.Since these two things would be available to components rendered server-side with no web-sockets involved,I think they could be added to Razor Pages and MVC applications as well because they are also rendered server-side.I think adding these two features would provide a great user experience to existing MVC and Razor Pages applications.

**Comment by danroth27** [comment]
The current enhanced navigation and streaming rendering functionality is based on Blazor's component model. This isn't something we plan to bring to MVC or Razor Pages. Closing.

**Comment by ctigrisht** [comment]
@danroth27 I'd love to get this feature in MVC, not everybody wants to use "rich" frameworks, I just want to use alpinejs with mvc pages. Keep MVC alive it's good tech.
