### ISSUE TITLE
PasswordValidator shall support "RequiredCharTypes"

### ISSUE THREAD

**Issue by wsy** [dotnet/aspnetcore#49896]
## Background and Motivation

Assume we have this password policy:
> A password must contain at least two of the following character types:
> - upper case letters
> - lower case letters
> - digits
> - non-alphanumeric characters.

This scenario is not covered by the current PasswordValidator implementation.

|Sample Password| Character kinds contained | Character kinds not contained |
|:---|:---|:---|
|`ABC123`| 2 (Upper case letters and digits)| 2 (Lower case letters and non-alphanumeric letters) |
|`abc###`| 2 (Lower case letters and non-alphanumeric letters)| 2 (Upper case letters and digits) |
|`abcabc`| 1 (Lower case letters)| 3 (Upper case letters and digits and non-alphanumeric letters) |

With current PasswordValidator, there's no combination of configuration that can let line 1 and line 2 pass the validation and let line 3 fail the validation.

## Proposed API
```diff
namespace Microsoft.AspNetCore.Identity;
public class PasswordOptions
{
+    public int RequiredCharTypes { get; }
}
```

**Comment by shiladitya-mukerji-22** [comment]
Hello @mkArtakMSFT. I would like to work on this enhancement. Can you assign this issue to me?

**Comment by wsy** [comment]
It seems the dotnet-policy-service is having some kind of bug in its rules. This is an issue with no PR linked to it, and it's being tagged with 'pending-ci-rerun'.

**Comment by wsy** [comment]
Hi @mkArtakMSFT ,

I have re-edited my API proposal according to API-Review-Process.md.
Now my proposed API is written in ref-assembly format.
I think it's now ready for review.

Can you please help labeling this issue as `api-ready-for-review`?

**Comment by wsy** [comment]
Hi @lonix1 ,
I think my proposal covers that scenario partially, but not fully.

According to my proposal, if you set `RequiredCharTypes` to `2`, and set `RequireNonAlphanumeric` to `true`, the behavior would be very similar to the one you mentioned.
In this case, "abc###" and "ABC###" will pass the check. However, "123###" will also pass the check.

**Comment by wsy** [comment]
Hi @amcasey ,
Can you please help labelling this issue as `api-ready-for-review`?
Or is there anything I still need to edit?

**Comment by amcasey** [comment]
@wsy This condition seems nuanced enough to justify registering a custom password validator.  Unfortunately, we can't introduce shorthand for each possible variant without making the API confusing and hard to use.  Thanks anyway!

**Comment by wsy** [comment]
I think this is a very common password policy. If we set default value of new configuration field to zero or one, it will be fully compatible with existing code.
