### ISSUE TITLE
Configuring LogLevel via environment variables in "standard" docker images

### ISSUE THREAD

**Issue by Bjego** [dotnet/aspnetcore#49899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dear .net team,
i'm trying to set the logging options for a namespace via envvariables. It works somothly on the launchsettings on my windows pc and on alpine based .net images, but when I try to set an environment variable like:

LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE.DATAPROTECTION=Error

in the ubuntu and debian based asp.net core images - the environment settings are ignored. 

Is there anyway to use the default containers and override values from the appsettings.json which contain a dot in the key?

like:

```json
{
"abad.key" : "true",
"b": {
"good": {
  "key" : true
}
}
```

How to override abady.key in debian environments?

Cheers

### Expected Behavior

Having a way to set "abad.key" as environmentvariable in ubuntu / debian based containers

### Steps To Reproduce

Create default .net template
Add Docker support
try to change the loglevel of "Microsoft.AspNetCore" via environment

### Exceptions (if any)

no

### .NET Version

6

### Anything else?

no

**Comment by adityamandaleeka** [comment]
Environment variable names are case-sensitive on Linux. Can you try something like the following instead and see if that works?

`Logging__LogLevel__Microsoft.AspNetCore.DataProtection=Error`

**Comment by Bjego** [comment]
Good morning,The problem with the debian based images is, that they swallow environment variables containing a ".". Will send an example yaml later.So the env var won't appear, if you run "printenv" in the container.Sent from Android PhoneAm 07.08.2023 21:05 schrieb Aditya Mandaleeka ***@***.***>:
Environment variable names are case-sensitive on Linux. Can you try something like the following instead and see if that works?
Logging__LogLevel__Microsoft.AspNetCore.DataProtection=Error

**Comment by Bjego** [comment]
Hmm okay - it's not reproducable in aks. Maybe something with the on prem setup here. Will close this issue.
