### ISSUE TITLE
In Blazor wasm, the overriden BuildRenderTree is not hit at all

### ISSUE THREAD

**Issue by wV-software** [dotnet/aspnetcore#49917]
Issure Reproduction steps:
1. Create an empty blazor wasm project on .net 7.0
2.  Add the following CustomBaseClass

```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace PrintCircuitSignatureOnComponent;

public class CustomBaseComponent : ComponentBase
{
    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {

        throw new Exception();
    }
    
        protected override void OnAfterRender(bool firstRender)
    {
        Console.Write("The overriding OnAfterRender invoked");
        base.OnAfterRender(firstRender);
    }
}
```

3.  Add the following Test.razor component

```
@inherits CustomBaseComponent

<h3>TestComponent</h3>

@code {

}
```

4. Include the component in the Index.razor page

```
@page "/"

<PageTitle>Index</PageTitle>

<TestComponent/>
```

5. Run the project

Expected result:
An exception will throw inside the overriding BuildRenderTree

Actual Result:
The component renders normally
override void OnAfterRender is invoked normally
BuildRenderTree wasn't hit at all

[PrintCircuitSignatureOnComponent.zip](https://github.com/dotnet/aspnetcore/files/12289748/PrintCircuitSignatureOnComponent.zip)

**Comment by Flachdachs** [comment]
The source generator of a .razor page creates its own override of BuildRenderTree which never calls the overriden method. And I doubt this is a bug. When should the call happen, at first, at last, somewhere in the middle?

**Comment by sake402** [comment]
If you want the base to be called, youw will have to do this in the TestComponent razor file

```C#
@{
RenderFragment baseView = base.BuildRenderTree;
}
@baseView;
```

This is because the razor file created is actually an implicit override on the base component BuildRenderTree method

**Comment by Flachdachs** [comment]
@sake402 I understand what your solution is trying to do, I wasn't aware of this way. However, there is still something wrong with it, I get an `Unhandled exception rendering component: Exception of type 'System.Exception' was thrown.`

**Comment by sake402** [comment]
@Flachdachs  A StackTrace of the exception will help.

**Comment by sake402** [comment]
@Flachdachs Looking at your OP again, you are deliberately throwing this exception in the base class buildrendertree method

**Comment by wV-software** [comment]
> Thanks for contacting us. This is indeed by-design. The `BuildRenderTree` method isn't expected to be overridden by anything but the RazorSourceGenerator generated code.
> 
> The more interesting question, however, is what @wV-software were you trying to achieve by overriding that method?

Thanks for reply 🙂. Actually I want to add custom html attributes to the root element(s) implicitly by a CustomComponentBase that serves a special need in a library I build. If you tell me an alternative way I'll appreciate it ☺️

**Comment by Flachdachs** [comment]
> @Flachdachs Looking at your OP again, you are deliberately throwing this exception in the base class `CustomBaseComponent .BuildrenderTree` method

Of course, the `throw`, I forgot. It's not my OP, I was just interested in this problem.
