### ISSUE TITLE
Base Href Changing Or Normal Refresh

### ISSUE THREAD

**Issue by Eddie-Hartman** [dotnet/aspnetcore#49931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When initially loading a page, the base href is correct, but once you refresh the page, it changes.

### Expected Behavior

Base href should not be changing depending on how the page is loaded.

### Steps To Reproduce

Navigate here: https://dev.mayvue.com/SNBIPWA/settings
Then refresh the page.

Hard refresh the page and see it loads fine. Check source and see for settings.html base href changes when you refresh the page normally.

### Anything else?

.NET 7.0.10

This is a pretty off the shelf project. It's hosted in a subdirectory and the index.html has been modified to be `<base href="/SNBIPWA/" />`

This is a standalone blazor webassembly app, and therefore, this should be the only change needed as documented here: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=netcore-cli#standalone-blazor-webassembly

I've seen a lot of different approaches on how to properly implement hosting a PWA on non-base path and am looking for guidance on how this should work OR if this is a bug. Since it works when loading normally, but breaks on refresh, I'm leaning towards bug since this is how it was documented to update the path.

I see lots of links and thoughts on this when looking around without a whole lot of answers such as: https://stackoverflow.com/questions/75146385/blazor-pwa-offline-caching-while-deployed-to-a-subdirectory

**Comment by mkArtakMSFT** [comment]
Can you also please clarify the difference between different refreshes that you refer to ? (Hard refresh, full refresh, ...).

**Comment by Eddie-Hartman** [comment]
I'll need some time to get a project together for you. It doesn't work when running the project locally and the repl options also won't replicate it the same way as a hosted environment either.

For clarification on refreshing, I just mean hitting the refresh button normally. That is what breaks. Whereas (in chrome) having dev tools open, and right clicking the refresh icon and hard refreshing will work. (I believe a shift F5 also does this).

I updated my post above to help clarify.

Again, I'd encourage you to just try the link above and see how it changes path if you'd like some type of reproduction sooner. Otherwise, it'll likely take me over the weekend to put together a similar scenario with a write up so it can be properly tested locally (because it can't just be hosted at root or else it won't change anyway, and running with `--pathbase` may actually fix some of the issues for local dev, but that's not specified as necessary for hosted).

**Comment by javiercn** [comment]
@Eddie-Hartman took a look at the page you pointed out. It doesn't seem to load ever with or without hard refresh. We don't interact with the base path on the page. It's a value in the template that needs to be in line with your hosting configuration/options.

In this case, it seems that something in your environment is not correctly configured.
