### ISSUE TITLE
Unify ViewBuffer logic between MVC and Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#49932]
MVC provides a set of APIs in `M.A.Mvc.ViewFeature` for rendering HTML by by buffering and writing to the underlying stream writer. To support rendering larger pieces of static HTML, https://github.com/dotnet/aspnetcore/pull/49860 integrates this logic into Blazor.

To avoid introducing new API, the implementation does this by copying the required APIs into internal implementations with a few targeted modifications to the APIs. See more in the code comments [in the source files](https://github.com/dotnet/aspnetcore/tree/main/src/Components/Endpoints/src/Rendering/ViewBufferTextWriter).

One of the challenges with the implementation is that there is a circular dependency chain between the `M.A.Components.Endpoints` assembly where these APIs are consumed and the `M.A.Mvc.ViewFeatures` assembly where they are defined: `M.A.Components.Endpoints` -> `M.A.Mvc.ViewFeatures` -> `Microsoft.AspNetCore.Components.Endpoints`.

We could possibly move the ViewBuffer-related codepaths to the `Html.Abstractions` since they contain no concrete dependencies on MVC, but we'd have to do some type-forwarding.

**Comment by mkArtakMSFT** [comment]
Discussed this with the team and have decided that we won't be doing this.
