### ISSUE TITLE
[RequestSizeLimit(100_000_000)] not working.

### ISSUE THREAD

**Issue by Pramod-naik47** [dotnet/aspnetcore#49946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am working on .net core 6 api project. I am trying upload 100 file to one of the API. I am trying to increase the limit for the specific API. I tried [RequestSizeLimit(100_000_000)] which I found on Microsoft documentation, doesn't seems to be working. 
I always get 413 Request entity is too large.

I don't want configure this limit in Statup.cs because it will be applicable to all the API's. I want to do this changes specifically to one particular API.

### Expected Behavior

Should be able to upload 100MB file

### .NET Version

6

**Comment by WGroenestein** [comment]
Not sure how your endpoint looks like, but if it is a Form post(e.g. IFormFile) you might want to look into [RequestFormLimitsAttribute.MultipartBodyLengthLimit](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.requestformlimitsattribute.multipartbodylengthlimit?view=aspnetcore-6.0#microsoft-aspnetcore-mvc-requestformlimitsattribute-multipartbodylengthlimit)

**Comment by Pramod-naik47** [comment]
Thanks for the quick response. some how there is a restriction on payload size in gateway  which I was unaware. So request was not even reaching the microservice. after fixing the gateway limit it seems to be working.
