### ISSUE TITLE
OnLocationChanged not fired in .NET 8 Preview 7 Blazor Web App

### ISSUE THREAD

**Issue by KeldJ** [dotnet/aspnetcore#49950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the code below (https://github.com/KeldJ/BlazorApp9) navigation to all urls are Catched and should fire OnLocationChanged which increases ID.

@page "/{*pageRoute}"
@attribute [RenderModeServer(false)]
@inject NavigationManager NavigationManager
@implements IDisposable
<PageTitle>Home</PageTitle>

@ID.ToString()
<br />
PageRoute: @PageRoute

@code {

	private int ID { get; set; } = 0;

	[Parameter]
	public string? PageRoute { get; set; }

	protected override async Task OnInitializedAsync()
	{
		await Task.Delay(1);
		NavigationManager.LocationChanged += OnLocationChanged;
	}

	private async void OnLocationChanged(object? sender, LocationChangedEventArgs e)
	{
		ID++;
		await InvokeAsync(StateHasChanged);
	}

	public void Dispose()
	{
		NavigationManager.LocationChanged -= OnLocationChanged;
	}
}

### Expected Behavior

OnLocationChanged should be fired and ID should be increased.

### Steps To Reproduce

https://github.com/KeldJ/BlazorApp9

### .NET Version

8.0.100-preview.7.23376.3

**Comment by bub-bl** [comment]
When you set a new uri from the address bar, you should lose the state of your app. This is the reason why location changed is never triggered and the **Id** property stay at 0. If you add the following code, you can see, the Id property is now updated when you navigate from the `NavigateTo()` function.

```razor
@page "/{*pageRoute}"
@attribute [RenderModeServer(false)]
@inject NavigationManager NavigationManager
@implements IDisposable

@Id.ToString()
<br/>
PageRoute: @PageRoute

<button @onclick="@(() => NavigateTo("/counter1/1"))">Counter 1</button>
<button @onclick="@(() => NavigateTo("/counter1/2"))">Counter 2</button>
<button @onclick="@(() => NavigateTo("/counter1/3"))">Counter 3</button>

@code {

    private int Id { get; set; }

    [Parameter]
    public string? PageRoute { get; set; }

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(1);
        NavigationManager.LocationChanged += OnLocationChanged;
    }

    private async void OnLocationChanged(object? sender, LocationChangedEventArgs e)
    {
        Id++;
        await InvokeAsync(StateHasChanged);
    }

    private void NavigateTo(string nav)
    {
        NavigationManager.NavigateTo(nav);
    }
    
    public void Dispose()
    {
        NavigationManager.LocationChanged -= OnLocationChanged;
    }

}
```

**Comment by KeldJ** [comment]
in .NET 8 Preview 7 the OnLocationChanged get fired using regular a href links like the attached Git Project

**Comment by bub-bl** [comment]
It seems to be a bug. But yes, NavigationManager seems to have a problem with `LocationChanged`. It's never triggered. I've tried putting them in **App.razor** and **MainLayout.razor** but I always get the same result. `LocationChanged` is only triggered in the page where it was saved and when we use `NavigationManager.NavigateTo()` to change the location.

**Comment by mkArtakMSFT** [comment]
Related and will be partially addressed as part of https://github.com/dotnet/aspnetcore/issues/48766

**Comment by surayya-MS** [comment]
Done in this PR https://github.com/dotnet/aspnetcore/pull/51279
