### ISSUE TITLE
Tag Helper Enum shorthand syntax doesn't work for nullable enums

### ISSUE THREAD

**Issue by NickCraver** [dotnet/aspnetcore#4996]
> Moved from https://github.com/aspnet/Mvc/issues/5881:

I'm working on a project with a nullable enum property in the tag helper, like this:
```c#
[HtmlTargetElement("mini-profiler", TagStructure = TagStructure.WithoutEndTag)]
public class MiniProfilerScriptTagHelper : TagHelper
{
    [HtmlAttributeName("position")]
    public RenderPosition? Position { get; set; }
}
```
Relevant enum: 
```c#
public enum RenderPosition
{
    Left = 0,
    Right = 1,
    BottomLeft = 2,
    BottomRight = 3
}
```
You can pull [the full repo here (specific commit link)](https://github.com/MiniProfiler/dotnet/tree/5c7950d58855e691432c1fa92904248e739f51fc)

I would expect the shorthand syntax to work in razor, like this:
```xml
<mini-profiler position="Right" />
```
However, that only works if `Position` is `RenderPosition` (not-nullable). When it's a nullable (`RenderPosition?`), you get an error:
> The name 'Right' does not exist in the current context.

Instead, you have to use the full version:
```xml
<mini-profiler position="@RenderPosition.Right" />
```

Can we please make this work with nullable enums too?

cc @DamianEdwards @khellang

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
