### ISSUE TITLE
Components E2E failure - error EnableGenerateDocumentationFile

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspnetcore#49960]
Example failing build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=368505&view=logs&j=fe94c0c9-bb8c-5d6f-3b51-887173cc2f5c&t=8f9eb7a9-d7c3-51e4-c6ef-55fd7672acb0

```
CSC : error EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/home/vsts/work/1/s/src/Components/CustomElements/src/Microsoft.AspNetCore.Components.CustomElements.csproj]
CSC : error EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/home/vsts/work/1/s/src/Middleware/OutputCaching/src/Microsoft.AspNetCore.OutputCaching.csproj]
CSC : error EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/home/vsts/work/1/s/src/FileProviders/Manifest.MSBuildTask/src/Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.csproj]
```

**Comment by yves2503** [comment]
After updating to VS 17.7.1 I get the same error message:
`CSC : error EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640)`

Colleagues with 17.6.2 installed can build the same source without any issues.

**Comment by VictorioBerra** [comment]
Same issue with me too.

Is there something I can set in my editoconfig or something to solve this?

**Comment by yves2503** [comment]
For us, it disappeared when setting the analyzer severity level to suggestion (dotnet_diagnostic.IDE0005.severity = suggestion).
Not exactly what we wanted, but our build pipeline works again.

**Comment by wtgodbe** [comment]
Have you seen this again recently @adityamandaleeka? I couldn't find any other builds failing in this way, and it seems odd for this analyzer to only be failing transiently. Was it on a PR build? Maybe something in the PR triggered it?

**Comment by adityamandaleeka** [comment]
I haven't seen it since, no. I don't think it was for a PR but the build is gone so I can't say for sure. Closing this issue since it's not really actionable anymore...
