### ISSUE TITLE
No default interactivity without @rendermode specified in .NET 8 Preview 7

### ISSUE THREAD

**Issue by bub-bl** [dotnet/aspnetcore#49987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we add the **Counter** component in a page without @rendermode specified, the component is rendered without interactivity.

(The Counter component does not have a render target specified in the Counter.razor file).

### Expected Behavior

The component should have a default server interactivity ?

### Steps To Reproduce

- Clone the repo: https://github.com/danroth27/Net8BlazorAuto.git
- Go in the Page.razor located in the Server project.
- Add those lines in the page:
```razor
@*This component does not have any interactivity*@
<Net8BlazorAuto.Client.Pages.Counter/>

@*Those components have interactivity*@
<Net8BlazorAuto.Client.Pages.Counter @rendermode="@RenderMode.Server"/>
<Net8BlazorAuto.Client.Pages.Counter @rendermode="@RenderMode.WebAssembly"/>
<Net8BlazorAuto.Client.Pages.Counter @rendermode="@RenderMode.Auto"/>
```
- Run the project.

___
### Additionnaly
If you create a page on the client side, the page is not reachable from the browser with the error bellow.

- Create a page on the client side named **Test**
- Add the follwing code
```razor
@page "/test"

<h3>Test</h3>

@code {
    
}
```
- Run the project
- Navigate to `/test`

![image](https://github.com/dotnet/aspnetcore/assets/66354328/cb8ef093-ac01-4f91-9b4b-10df00aacb68)

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

C:\Users\bubbl>dotnet --version
8.0.100-preview.7.23376.3

C:\Users\bubbl>dotnet --info
SDK .NET :
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
Il n'y a aucune charge de travail installée à afficher.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This behavior is by-design. The `rendermode` value for a given component, if not specified explicitly, is inherited from its parent component. And when not specified on any of the parent elements, it defaults to static rendering mode, which enables no interactivity.
Also, `@RenderMode.Server` enables server interactivity (through a web-socket connection) rather than a static (state-less) rendering.

**Comment by balenamiaa** [comment]
Besides that, there's no interactivity for the navigation bar in MainLayout.cs.

> Thanks for contacting us. This behavior is by-design. The `rendermode` value for a given component, if not specified explicitly, is inherited from its parent component. And when not specified on any of the parent elements, it defaults to static rendering mode, which enables no interactivity. Also, `@RenderMode.Server` enables server interactivity (through a web-socket connection) rather than a static (state-less) rendering.

#49314 Wasn't it discussed in this issue that the default rendering mode should have server interactivity?
