### ISSUE TITLE
Array of control references is not maintained on page renders after the first

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#49980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://stackoverflow.com/questions/60064510/add-ref-to-a-blazor-component-in-a-loop

https://github.com/dotnet/aspnetcore/issues/17361

In the attached project I build out a table of controls of type `PersonInput`.
I keep a reference to each control that is rendered in an array called `PersonInputs`.

  <td>
      <PersonInput Name="@tmpColIndex.ToString()" @ref="PersonInputs[tmpColIndex]" />
  </td>
  
The first time the page is rendered the `PersonInputs` array is populated correctly - the length of the array matches the number of data objects.

On all subsequent renders, the length of the array is out of sync with number of data elements.  This should never occur.  Each `Person` object must be associated with a related `PersonInput` control.  

Why does this occur?  

I have not yet tried the approaches in the links shown above.  Both are similar to what I am doing (especially the second).  

Reproduce:
Put a breakpoint on the `Debug.Assert` line in `Index.razor`
Run the attached project.
Click Rebuild Table button.
Click Verify Values btton.
Observe that `controlCount` and `peopleCount` have the same number of elements.
Continue debugging.
Click Rebuild Table button again.
Click Verify Values button again.
Observe that `controlCount` and `peopleCount` have a different number of elements.

### .NET Version

7.0.400

### Anything else?

[MatrixTest.zip](https://github.com/dotnet/aspnetcore/files/12308245/MatrixTest.zip)

**Comment by sam-wheat** [comment]
@mkArtakMSFT [Repo here](https://github.com/sam-wheat/MatrixTest.git)

**Comment by sam-wheat** [comment]
This appears to be a regression based on [this issue](https://github.com/dotnet/aspnetcore/issues/17361).

I was able to find a workaround, ugly though it may be:

PersonInput.razor:


	<label>@Name</label>

	@code {
		[Parameter] public string Name { get; set; }
		[Parameter] public Dictionary<string,PersonInput> Ref { get; set; }


		protected override async Task OnParametersSetAsync() => Ref[Name] = this;
	}


Index.razor

	@page "/"
	

	<table style="border:solid 2px black;">
	
	  //...
	
	  <td>
		<PersonInput Name="@people[tmpColIndex].Name" Ref="PersonInputs" /> // not @ref
	  </td>
	  
	  //...
	  
	  
	  @code{

		//...
		private Dictionary<string,PersonInput> PersonInputs;


		// new Dictionary when data changes.

**Comment by gragra33** [comment]
@sam-wheat When working with lists of items, you need to set a unique `key` for each item so Blazor can track. 

The fix is quite simple:
```html
<PersonInput @key='@($"{rowIndex}:{colIndex}")'
             Name="@tmpColIndex.ToString()" @ref="PersonInputs[tmpColIndex]" />
```
Enjoy!

**Comment by MackinnonBuck** [comment]
@sam-wheat Does @gragra33's solution work for you?

**Comment by sam-wheat** [comment]
@MackinnonBuck  I have not tested @gragra33 solution as I have found another workaround which I posted.  If his solution does work I would classify it as a workaround also based on how the expected functionality is described [here](https://github.com/dotnet/aspnetcore/issues/17361).

**Comment by gragra33** [comment]
@MackinnonBuck I did a test before posting. I've posted the reference material link below.

@sam-wheat The method that I posted is the correct way of working with a list of items. Each item in the list should have its own unique key. Please refer to: [Retain element, component, and model relationships in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-7.0).

**Comment by sam-wheat** [comment]
@MackinnonBuck it is not clear from the document you provided that `@key` allows me to use an instance of a control that was rendered.  In my case the control being rendered contains an `input` element.  When user clicks save I need to iterate all the controls that were rendered (not the data elements) and get the values that were input by the user.

**Comment by gragra33** [comment]
@sam-wheat Can you please update your sample project to reflect these new requirements?

**Comment by sam-wheat** [comment]
@gragra33 There are no new requirements.  The project I provided illustrates the problem that is reported in this ticket.  
What do you mean "the model should not hold user-entered data"?  The data input by the user is made available to me by the controls that are rendered i.e. the collection of `PersonInput ` controls.

**Comment by gragra33** [comment]
@sam-wheat You misquoted me. Again, "the model **should hold** user-entered data".

Apply the fix, to your supplied sample app, as I mentioned above and you will find that all of your tests will pass. It did when I ran them.

**Comment by sam-wheat** [comment]
> This is not in the original sample project provided.

Because it's not the problem.  Here is the issue being reported:

> On all subsequent renders, the length of the array is out of sync with number of data elements. This should never occur. Each Person object must be associated with a related PersonInput control.

**Comment by gragra33** [comment]
@sam-wheat Have you tried the solution that I provided? You will find, if you do, it will fix your issue.

**Comment by sam-wheat** [comment]
@gragra33 Yes I will try it - and yes I did ask for help and I appreciate the information you have provided.

**Comment by surayya-MS** [comment]
Glad you have a solution.

**Comment by sam-wheat** [comment]
@surayya-MS - why is this closed?  I don't have a solution I have a workaround.

**Comment by sam-wheat** [comment]
@gragra33 

Looks like this code is sufficient to work around the issue;

    PersonInput[] temp = PersonInputs;
    Array.Resize(ref temp, people.Count);
    PersonInputs = temp;

Using `@key` does not appear to be necessary.

**Comment by sam-wheat** [comment]
@surayya-MS  - why is this issue closed?  I took time out of my (very busy) day to post this question and repro and workaround yet the issue is closed with no comment.  If I'm using it wrong please let me know it won't be the first time.
Thanks
