### ISSUE TITLE
HttpLoggingMiddleware does not log RequestBody when body is consumed by copying to another stream

### ISSUE THREAD

**Issue by olegbaslak** [dotnet/aspnetcore#49989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When `HttpLoggingMiddleware` is enabled and `HttpContext.Request.Body` is consumed by copying to another stream (calling `CopyToAsync`) instead of reading, an empty `RequestBody` is logged after an endpoint is executed.

### Expected Behavior

Not empty request body is logged when calling `CopyToAsync`, e.g. when sending json body
```json
{
    "Response": "Test Response"
}
```
it should be logged as is.

### Steps To Reproduce

1. Simple Program.cs of ASP.NET Core project that copies request into memory stream and writes it back to response:

```csharp
using System.Text;
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpLogging(options => { options.LoggingFields = HttpLoggingFields.RequestBody; });

var app = builder.Build();

app.MapGet("/", async context =>
{
    // context.Request.EnableBuffering(); // Enabling buffering "fixes" the issue

    using var tempStream = new MemoryStream();
    await context.Request.Body.CopyToAsync(tempStream);

    var responseContent = Encoding.Default.GetString(tempStream.ToArray());
    await context.Response.WriteAsync(responseContent);
});

app.UseHttpLogging();
await app.RunAsync();
```

2. Send a request to `/` endpoint with some json body, e.g. `{ "Response": "Test Response" }`
3. Observe logs.

Logs:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:7255/ application/json 37
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody:
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:7255/ application/json 37 - 200 - - 38.6330ms
```

### Exceptions (if any)

Enabling buffering by uncommenting `context.Request.EnableBuffering();` line.

Logs in this case:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:7255/ application/json 37
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody: {
          "Response": "Test Response"
      }
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:7255/ application/json 37 - 200 - - 25.6788ms
```

Probably it happens because `FileBufferingReadStream` calls `ReadAsync` methods on the inner stream (in this case inner is `RequestBufferingStream`) in its `CopyToAsync` implementation. And `RequestBufferingStream`, when not wrapped, does not write anything in its buffer when `CopyToAsync` is called.

### .NET Version

7.0.203

### Anything else?

ASP.NET Core: 7.0.5
IDE: Visual Studio 2022, Rider

Also reproducible for .NET 6

**Comment by BrennanConroy** [comment]
Try using 7.07 or later, we fixed a bug that sounds similar
https://github.com/dotnet/aspnetcore/pull/47811

**Comment by olegbaslak** [comment]
> Try using 7.07 or later, we fixed a bug that sounds similar #47811

Hi, thank you for quick reply! Tried `7.0.10`. No luck, unfortunately. I assume it is not connected to #47811 because calling `CopyToAsync` does not trigger `Read` or `ReadAsync` methods at all.

**Comment by BrennanConroy** [comment]
Ok, thanks for giving it a try 😃

**Comment by Tratcher** [comment]
Ah, 
https://github.com/dotnet/aspnetcore/blob/31a26e080ae5652cd3c9b414078d1b61a0b89010/src/Middleware/HttpLogging/src/RequestBufferingStream.cs#L10
Doesn't override CopyTo/Async from the base stream:
https://github.com/dotnet/aspnetcore/blob/31a26e080ae5652cd3c9b414078d1b61a0b89010/src/Middleware/HttpLogging/src/BufferingStream.cs#L298-L306

So CopyTo/Async skips the logging buffer.

FileBufferingReadStream that's used by EnableBuffering does override CopyTo/Async and calls ReadAsync on the inner logging stream so it's fine.
https://github.com/dotnet/aspnetcore/blob/31a26e080ae5652cd3c9b414078d1b61a0b89010/src/Http/WebUtilities/src/FileBufferingReadStream.cs#L427-L438

Fix: RequestBufferingStream must override CopyTo/Async like FileBufferingReadStream does. Actually, we could put that logic in the base BufferingStream class, having it delegate to Read/Async so the normally buffering could happen.

Side note: Why does your GET request have a body? That's odd.

**Comment by olegbaslak** [comment]
@Tratcher very detailed comment, thanks! So it is exactly how I thought.

Regarding GET... Sometimes, answer is very easy. It is postman default request type for new requests. I just didn't bother changing it 😁
