### ISSUE TITLE
StateHasChanged starts a javascript before it is finished.

### ISSUE THREAD

**Issue by wrharper-AASP** [dotnet/aspnetcore#49994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You can test this with a scroll to bottom after adding something to a message list.

Works:

```
StateHasChanged();
await Task.Delay(10);
await JsRuntime.InvokeVoidAsync("scrollToBottom", scrollContainer);
```

Does not work:

```
StateHasChanged();
await JsRuntime.InvokeVoidAsync("scrollToBottom", scrollContainer);
```

### Expected Behavior

StateHasChanged should not be letting a javascript run before it is even finished rendering...

### Steps To Reproduce

I haven't tested this specifically but something like this should show the problem.

put this in your _layout or wherever your main body is:

```
<script>
        window.scrollToBottom = function (element) {
            element.scrollTop = element.scrollHeight;
        }
</script>
```

make a component like this:

```
 <div class="scrollingArea2" @ref=scrollContainer>
@messages
</div>
<textarea rows=1 type="text" 
                 @bind=messageToSend
                @bind:event="oninput"
                @onkeydown=@((e) => InputMessageUpdateDown(e))
                @onkeyup=@((e) => InputMessageUpdateUp(e))></textarea>

@code {
    ElementReference scrollContainer;
List<string> messages = new();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
for (int i = 0; i < 50; i++)
{
messages.add("newmessage");
}
        }
    }

    public async Task RefreshStateAndScrollToBottom()
    {
messages.add("newmessage");
        StateHasChanged();
        await Task.Delay(10);
        await JsRuntime.InvokeVoidAsync("scrollToBottom", scrollContainer);
    }
    public async Task RefreshStateAndScrollToBottomBroken()
    {
messages.add("newmessage");
        StateHasChanged();
        await JsRuntime.InvokeVoidAsync("scrollToBottom", scrollContainer);
    }
}

    async Task InputMessageUpdateDown(KeyboardEventArgs e)
    {
// just swap these to see the results
//            await RefreshStateAndScrollToBottom();
            await RefreshStateAndScrollToBottomBroken();
    }
```

### Exceptions (if any)

Other code shouldn't be called before statehaschanged has even finished...

### .NET Version

7.0.400-preview.23274.1

### Anything else?

the .net version says it is 7 preview but i am running this as .net 6.

**Comment by wrharper-AASP** [comment]
just in case this matters, here is a situation of when it needs a delay and the 2nd time around it doesn't need the delay:


```
                try
                {
                    messages.Add("asdf");
                    //call happens out of order somehow???
                    await m.RefreshStateAndScrollToBottomWithDelay();
                    //an httpclient call happens here, can't show it in my code
                    messages.Add("asdf");
                    //call happens in order???
                    await m.RefreshStateAndScrollToBottomNoDelay();
                }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The behavior you have observed is by-design.
`StateHasChanged` doesn't call a synchronous render. Instead, it queues up a render request to happen asynchronously.

If you are looking for a way to execute some javascript logic after the content is available in the DOM, you can invoke that in the `OnAfterRender` / `OnAfterREnderAsync` handler.

**Comment by wrharper-AASP** [comment]
> 

it is more complex than the example and states need to be updated during a call.
Like if a person sends a message, you need 1 update for the message you send immediately, and one update after there is a response from the other side. They both happen within 1 http call so the only way to do this is to force updating manually. This is why "stoppropagation" is absolutely required. This will not be an answer in my situation.

**Comment by SteveSandersonMS** [comment]
@wrharper-AASP This is tricky to solve in the way you expected it to work, because `OnAfterRenderAsync` is precisely the lifecycle method that means "we have now updated the DOM". So, if you want to run some code that only makes sense once the DOM has been updated, that lifecycle method really is the place to put it.

There is a difference approach to consider, though. Rather than triggering the JS from .NET, you could trigger it from a JS DOM mutation observer or a custom element. For example, if you want to "scroll to end" after rendering in some situations, you could change your render output so it includes some hint to do that, for example:

```razor
@if (shouldScrollToEnd) {
    <scroll-to-end @key="@Guid.NewGuid()"></scroll-to-end>
}
```

Then, use JS to register `scroll-to-end` as [a custom element](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) whose `connectedCallback` triggers the JS logic you want (scrolling to the end). The use of `@key` above is to guarantee this produces a new element on each render, so it will scroll to end after each render that includes this in the output.

If you don't want to use a custom element, you could use https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver to observe the appearance of certain custom attributes or similar in the DOM and trigger whatever logic you want in response.

I fully appreciate this involves writing more JS than you might want, but is the best suggestion I have for triggering JS actions in response to rendering without using `OnAfterRenderAsync` as you wish.

**Comment by wrharper-AASP** [comment]
> @wrharper-AASP This is tricky to solve in the way you expected it to work, because `OnAfterRenderAsync` is precisely the lifecycle method that means "we have now updated the DOM". So, if you want to run some code that only makes sense once the DOM has been updated, that lifecycle method really is the place to put it.
> 
> There is a different approach to consider, though. Rather than triggering the JS from .NET, you could trigger it from a JS DOM mutation observer or a custom element. For example, if you want to "scroll to end" after rendering in some situations, you could change your render output so it includes some hint to do that, for example:
> 
> ```
> @if (shouldScrollToEnd) {
>     <scroll-to-end @key="@Guid.NewGuid()"></scroll-to-end>
> }
> ```
> 
> Then, use JS to register `scroll-to-end` as [a custom element](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) whose `connectedCallback` triggers the JS logic you want (scrolling to the end). The use of `@key` above is to guarantee this produces a new element on each render, so it will scroll to end after each render that includes this in the output.
> 
> If you don't want to use a custom element, you could use https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver to observe the appearance of certain custom attributes or similar in the DOM and trigger whatever logic you want in response.
> 
> I fully appreciate this involves writing more JS than you might want but is the best suggestion I have for triggering JS actions in response to rendering without using `OnAfterRenderAsync` as you wish.

Is it not possible to just fix the fact that sometimes you need a timer "after" StateHasBeenChanged()? Why can't StateHasBeenChanged finish when it is actually finished?

What I am doing works very well, this is the first time I found a bug with the StateHasBeenChanged object. I stop propagation for eventcallbacks and do it this way. It works great! If this 1 thing could be fixed, I wouldn't need to redesign and entire path just to fix 1 problem. It seems a little much when the fix should be simpler than that. There just shouldn't need to be a timer, that is predictive fixing. Timers in general end up being a bad path. They can cause overflow and so many other issues.

**Comment by SteveSandersonMS** [comment]
What do you mean by `StateHasBeenChanged`? Are you referring to `StateHasChanged`? If so, that's only a hint to the renderer that some state has changed. It is not the thing that actually performs a render, and there is no guarantee that rendering will happen synchronously (or even ever - you can still override `ShouldRender` and return false).

> There just shouldn't need to be a timer

That seems to be restating the opinion that `StateHasChanged` should always synchronously force a render, but that isn't how it's ever worked, and would lead to much more complex situations where rendering can occur while rendering is already happening, violating other guarantees that keep the programming model simpler. I'm afraid we don't plan to change that, hence the suggestion of a different approach that would be more robust than the timer in your case. Sorry that's not what you're hoping to hear but is the tradeoff we've made to simplify other aspects of the programming model.

**Comment by wrharper-AASP** [comment]
I haven't had these issues due to stopping propagation in events. There is no other rendering until I do StateHasChanged. I designed that way so I can update the UI in the middle of things happening. It absolutely works, I have never seen a problem until now and have been using it for months. It is extremely powerful this way and makes amazing things possible that you can't do by just dropping literally everything in an OnAfterRender call. This absolutely won't work. I'll just have to continue with a timer for this 1 and only situation where it was needed.

**Comment by SteveSandersonMS** [comment]
OK. Hopefully if this is the only situation where you have to do this, it won't be a major issue for you. Thanks for all the info!
