### ISSUE TITLE
PageTitle Not Updating

### ISSUE THREAD

**Issue by ericpincus** [dotnet/aspnetcore#50017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From the Counter template, clicking "Click me" increments @currentcount, but the page's title doesn't update:

```
@page "/counter"
@attribute [RenderModeServer]

<PageTitle>Counter @currentCount</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;

//Note: the following line added in an attempt to fix, but no change:
        StateHasChanged();        
    }
}
```
### Expected Behavior

If PageTitle component contains a variable, the page's title should update as the variable changes.

### .NET Version

8.0.100-preview.7.23376.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you confirm if the `<HeadOutlet>` component defined in the `App.razor` has `rendermode` specified?

Please note that the title is not set interactively for the template out of the box and it will be updated only during navigations because of that.

**Comment by ericpincus** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <base href="/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="css/bootstrap-icons/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="css/app.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="BlazorApp1.styles.css" />
    <HeadOutlet />
</head>

<body>

    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <PageTitle>Not found</PageTitle>
            <LayoutView Layout="@typeof(MainLayout)">
                <p role="alert">Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.web.js" suppress-error="BL9992"></script>
</body>
</html>
`

**Comment by ericpincus** [comment]
With a little more research, functionality works with the following in app.razor:

` <HeadOutlet @rendermode="@RenderMode.Server" />`

**Comment by ericpincus** [comment]
Resolved

**Comment by leonardoadame** [comment]
The issue you are facing is that the page title is not updating when you click the “Click me” button to increment the current count.

The reason for this is that the Page Title component is not set interactively for the template out of the box. This means that the title will only be updated when you navigate to the page, not when you change the value of the current count variable.

To fix this, you need to add the `RenderModeServer` attribute to the `HeadOutlet` component in the App. Razor file. This will tell the Razor compiler to render the title of the page server-side, which allows it to be updated dynamically.

Here is the updated code for the App. Razor file:

```
<head>
  <title>My App</title>
  <HeadOutlet @rendermode="@RenderMode.Server" />
</head>
```

Once you have made this change, the page title should update when you click the “Click me” button.

Here are the steps to reproduce the issue:

1. Clone the aspnetcore repository: https://github.com/dotnet/aspnetcore.
2. Open the `Counter` project in Visual Studio.
3. Run the project.
4. Click the “Click me” button.
5. The page title should not update.

To fix the issue, follow the steps above to add the `RenderModeServer` attribute to the `HeadOutlet` component.
