### ISSUE TITLE
Razor Pages routing breaks when creating web host from separate project

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#50024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to create a service which will run two hosts: the main service, and a web interface to go along with it.  They should run concurrently.  As far as I can tell, the pattern I should use for this is to create 3 projects; a bootstrap project, a "main service" one, and a "web interface" one (which is an ASP.NET Razor Pages project).  My bootstrap `Main` looks like:

```
public static async Task Main(string[] args) {
	var botHost = MyBot.Service.HostSetup
		.CreateHost(args, _serviceName, _serviceDescription)
		.RunAsync();
	var webHost = MyBot.Web.WebHostSetup
		.CreateWebHost(args)
		.RunAsync();

	await Task.WhenAll(new Task[] { botHost, webHost });

	Console.WriteLine("All hosts exited.  Exiting program.");
}
```

`CreateHost` and `CreateWebHost` return an `IHost`.

### Expected Behavior

The regular service `IHost` runs fine, and it's created via `Host.CreateDefaultBuilder(args) [...] .Build()`.  However, the Razor Pages web host fails to discover any Razor pages paths, giving the following logs when I try to access the root of the site:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/ - -
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path / does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
      No candidates found for the request path '/'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
      Request did not match any endpoints
```

Apparently something about the Razor Pages project being separate from the project containing `Main` causes the `DfaMatcher` discovery (what does "Dfa" stand for, anyway?) to fail.  `CreateWebHost` looks like:

```
public static IHost CreateWebHost(string[] args) {
	var builder = WebApplication.CreateBuilder(args);

	// Add services to the container.
	builder.Services.AddRazorPages();

	var app = builder.Build();

	// Configure the HTTP request pipeline.
	if (!app.Environment.IsDevelopment()) {
		app.UseExceptionHandler("/Error");
	}

	app.UseHttpsRedirection();
	app.UseStaticFiles();

	app.UseRouting();

	app.UseAuthorization();

	app.MapRazorPages();

	return app;
}
```

### Steps To Reproduce

Create two projects, one for bootstrap and one for the web host.

Turn the web host project into a class library and remove its `Program.cs`, moving the web host creation code into a static class returning an `IHost`.

Call the method from the bootstrap project's `Main` method and `RunAsync` to start the web host.

### .NET Version

6.0

**Comment by javiercn** [comment]
@jez9999 thanks for contacting us.

This is by design as MVC defaults to the entry point assembly as the root for discovery. You can configure it explicitly by calling AddApplicationPart or ConfigureApplicationPartManager to indicate an appropriate entry point.
