### ISSUE TITLE
CascadingValueSource doesn't work with named AddCascadingValue

### ISSUE THREAD

**Issue by dodyg** [dotnet/aspnetcore#50034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```csharp

builder.Services.AddCascadingValue("hello", sp => 
{
    var msg = new MessageCascade("Hello World! " + DateTime.Now);
    var source = new CascadingValueSource<MessageCascade>(msg, isFixed: false);
    return source;
});
```

```html

<h2>Inner Component One</h2>

@HelloMessage.Message

@code {
    [CascadingParameter(Name="hello")]
    protected MessageCascade HelloMessage { get; set; } = default!;
}
```

will generate

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ComponentTwentySix.Pages.InnerComponentOne.BuildRenderTree(RenderTreeBuilder __builder) in D:\GitHub\practical-aspnetcore\projects\.net8\ComponentTwentySix\Pages\InnerComponentOne.razor:line 3
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### Expected Behavior

That named cascading value will just work normally. 

### Steps To Reproduce

https://github.com/dodyg/practical-aspnetcore/blob/net6.0/projects/.net8/ComponentTwentySix/Program.cs

### .NET Version

8.0.100-preview.7.23376.3

**Comment by SteveSandersonMS** [comment]
The overload you're calling here - the one that takes a `name` - does *not* accept a `CascadingValueSource` (or if you supply one, that actually becomes the cascaded value, rather than a source of cascaded values).

Instead if you want to give a name, use the overload that accepts `Func<IServiceProvider, CascadingValueSource>` only, and then put the name on the `CascadingValueSource` that you return.
