### ISSUE TITLE
Conditional css class syntax in blazor

### ISSUE THREAD

**Issue by ShortDevelopment** [dotnet/aspnetcore#50035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm currently investigating in migrating a production app from razor pages (`*.cshtml`) to blazor ssr coming with `net8.0`.
Some pages use a custom tag helper, that allows for conditional css classes [like svelte does](https://svelte.dev/tutorial/classes), but blazor does not allow the use of tag helpers.
#### Svelte
```html
<div class="static-class" class:dynamic-class={useDynamicClass}></div>
```
#### My tag helper
```html
<div class="static-class" class:dynamic-class="@UseDynamicClass"></div>
```

### Describe the solution you'd like

 - Introduce a specific syntax for easy conditional css classes, or...
 - Support a way to customize the compiler behavior (e.g. tag helpers).

**Comment by gragra33** [comment]
The approach with Blazor is a little different. In the code section, declare a string to hold the class(es):
```cs
string? CssClass = null;
```
Now add this nugget package: [BlazorComponentUtilities](https://www.nuget.org/packages/BlazorComponentUtilities), it has a `CssBuilder` helper. You can read more about it in his GitHub Repo: [[EdCharbeneau](https://github.com/EdCharbeneau) / 
[BlazorComponentUtilities](https://github.com/EdCharbeneau/BlazorComponentUtilities)](https://github.com/EdCharbeneau/BlazorComponentUtilities).

Now in your code, before `StateHasChanged` is used, use the `CssBuilder` helper to conditionally build your list of class name, then store the result in your `CssClass` variable.

Then in your HTML markup:
```html
<div class="@CssClass"></div>
```

**Comment by ShortDevelopment** [comment]
Well that would work, but – to me – seems like quite a lot of boilerplate for such a “simple” task.
I personally like to keep logical units as small as possible and contain them in a single place…

**Comment by gragra33** [comment]
@ShortDevelopment Here is an example from a project, it's one line of code, but broken onto multiple lines for readability:
```cs
_inputsContainerCss = new CssBuilder(CssInput)
    .AddClass(CssInputTop, when: !ShowSelectColorPanel && !ShowSliders && ShowInputs)
    .Build();
```

**Comment by ShortDevelopment** [comment]
It’s definitely not horrible … I guess I just don’t really like to have a dedicated variable for this.
This approach might also be not so nice with dynamically generated elements (e.g. `foreach`). 

I just want to request some minimalistic syntactic sugar 😊.

**Comment by gragra33** [comment]
@ShortDevelopment I do not use **Svelte**, however,  `useDynamicClass` looks like a call to a method. If you look at my last example, I have a condition to test if a class is required or not.  How would you do it using **Svelte**?

You can use a method instead of a variable with Blazor too. 😉
