### ISSUE TITLE
Inconsistency behaviour between `app.UseExceptionHandler()` and `app.UseExceptionHandler(_=> { })`

### ISSUE THREAD

**Issue by cakescience** [dotnet/aspnetcore#50049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would like to use the new `IExceptionHandler`. While `app.UseExceptionHandler(_ => { })` works as expected, `app.UseExceptionHandler()` results in a `InvalidOperationException` with the message: `An error occurred when configuring the exception handler middleware. Either the 'ExceptionHandlingPath' or the 'ExceptionHandler' property must be set in 'UseExceptionHandler()'. Alternatively, set one of the aforementioned properties in 'Startup.ConfigureServices' as follows: 'services.AddExceptionHandler(options => { ... });' or configure to generate a 'ProblemDetails' response in 'service.AddProblemDetails()'.`
This is an inconsistency between the behaviours of `app.UseExceptionHandler()` and `app.UseExceptionHandler(_=> { })`. This inconsistency is counterintuitive and might lead to confusion for developers who expect these two invocations to be equivalent.

### Expected Behavior

Both `app.UseExceptionHandler()` and `app.UseExceptionHandler(_ => { })` should result in the same behaviour when configuring the exception handling middleware, with both methods setting up the middleware to handle exceptions gracefully (in this specific case I should not need to configure anything else or any exception handling path as the custom handler should be enough).

### Steps To Reproduce

```cs
using Microsoft.AspNetCore.Diagnostics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddExceptionHandler<DefaultExceptionHandler>();

var app = builder.Build();

app.UseExceptionHandler(); // Throw an IOE
//app.UseExceptionHandler(_ => { }); // Ok

app.Run();

public sealed class DefaultExceptionHandler : IExceptionHandler
{
    public ValueTask<bool> TryHandleAsync(HttpContext httpContext, Exception exception, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}
```

### .NET Version

8.0.100-preview.7.23376.3

**Comment by Tratcher** [comment]
`app.UseExceptionHandler(_ => { })` is likely not doing what you expect. This isn't an overload that takes options and can just no-op, it builds an error handling pipeline. By not doing anything you're not really handling the error (unless it's always handled by your IExceptionHandler?).
https://github.com/dotnet/aspnetcore/blob/10bc40cf7bec57ecf9d2ffd9a7501b34a28d1f18/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerExtensions.cs#L57C5-L57C127

UseExceptionHandler still requires some default exception handler config in case the IExceptionHandler instances return false (can't handle the error).
