### ISSUE TITLE
Log a warning if event callbacks are registered on non-interactive components

### ISSUE THREAD

**Issue by BrienKing** [dotnet/aspnetcore#50047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a brand new project using the Blazor Web App template.  

Preview 8
All Options Checked

I create a Razor Component with the following code:

`
<button class="btn btn-primary" @onclick="Login">Click me< /button>

@code {

	private void Login()
	{
		throw new NotImplementedException();
	}

}
`
I then add the component to the MainLayout.

I have a break-point set at the private void Login().

I run the app and click the button and my breakpoint is never hit.

If I then add
`@attribute [RenderModeServer]`

To the top of the component then my break-point gets hit.

### Expected Behavior

I expect my code to get executed no matter what the mode is, if not give me an error or something useful so I know why it's not working.

### Steps To Reproduce

See the description.  Very simple to reproduce.

### Exceptions (if any)

No errors of any kind.

### .NET Version

8.0 Preview

### Anything else?

Latest VS 17.7

**Comment by SteveSandersonMS** [comment]
We did discuss this and are aware it might not be possible to log warnings, since there are legit cases for doing this. For example, QuickGrid is meant to work in SSR-only mode but also has optional event handlers. Many other components will follow that kind of progressive-enhancement pattern.

**Comment by BrienKing** [comment]
> We did discuss this and are aware it might not be possible to log warnings, since there are legit cases for doing this. For example, QuickGrid is meant to work in SSR-only mode but also has optional event handlers. Many other components will follow that kind of progressive-enhancement pattern.

A warning wouldn't stop it from being used in other scenarios, but it would let people know what it's not working as I would have expected it to work.

**Comment by sake402** [comment]
I vote for at least a warning in client console on this, when such button is eventually clicked.

**Comment by codymullins** [comment]
I would vote for some information around this - I was stumped for a few hours just now until I realized what was missing.

**Comment by mkArtakMSFT** [comment]
It's generally impossible to know the render mode for a component at compile time or at runtime, since that might change across requests at runtime and can't be analyzed.
 
Introducing this would add a lot of noise and false warnings that we don't think will result a good experience
