### ISSUE TITLE
Should this property be removed or marked as Obsolete?

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/aspnetcore#50043]
The `PreferExactMatches` parameter on the `Router` component was made effectively obsolete but not removed or marked as obsolete, so anyone writing code with this parameter would only know it was obsolete if they read the xml comments.

https://github.com/dotnet/aspnetcore/blob/4802de196a70a72017e292fe78f94560972dd4cf/src/Components/Components/src/Routing/Router.cs#L95

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/50545
