### ISSUE TITLE
Method for specifying content-encoding in Microsoft.AspNetCore.OpenApi

### ISSUE THREAD

**Issue by moni-dips** [dotnet/aspnetcore#50056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to configure OpenAPI with Content-Encoding options, but it seems like this is not properly supported by the API in .NET.

Example code:
```C#
    const string bmpSample = "...";
    app.MapPost("/api/v1/convert", APIEndpoints.ImageConverter)
        .WithOpenApi(
            o =>
            {
                o.RequestBody = new OpenApiRequestBody
                {
                    Content =
                    {
                        {
                            "image/bmp",
                            new OpenApiMediaType
                            {
                                Schema = new OpenApiSchema
                                {
                                    // want to set contentEncoding: base64 as per the OpenAPI spec here
                                },
                                Examples =
                                {
                                    { "image/bmp", new OpenApiExample{ Value = new OpenApiString(bmpSample) } }
                                }
                            }
                        }
                    }
                };
```

### Describe the solution you'd like

Adding a ContentEncoding property to OpenApiSchema ought to address my needs

**Comment by Tratcher** [comment]
Remember Transfer-Encoding (e.g. chunked) is not the same as Content-Encoding (e.g. gzip).

**Comment by moni-dips** [comment]
yes, that is indeed correct, I was just being a bit sloppy with my terms.

**Comment by captainsafia** [comment]
The reason this doesn't work in .NET 8 and below is because the schemas that are placed in the `WithOpenApi` call are ultimately overridden by Swashbuckle in its implentation.

Starting in .NET 9, we're adding built-in support for OpenAPI document generation so that these kinds of overrides can be made.

Note: AFAIK, setting the content encoding is only supported in OpenAPI v3.1 and beyond.
