### ISSUE TITLE
Consider moving @section off of extensible directives

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#5006]
Today `@section` expects 1 identifier. We accomplished this by creating an extensible directive that accepts 1 member token. This isn't entirely correct though; it ends up looking like:

![image](https://cloud.githubusercontent.com/assets/2008729/25053925/3e56ea3a-210f-11e7-9ef0-680d3a5bc211.png)

And if you hover over the member you get:

![image](https://cloud.githubusercontent.com/assets/2008729/25053945/5305aa3e-210f-11e7-83c6-e42e890db145.png)

We may want to move section off of the extensible directive infrastructure and have it just be a built-in directive

**Comment by pranavkm** [comment]
Closing this as we haven't heard enough feedback about this being a pain point.
