### ISSUE TITLE
Namespace names are always grayed out in _ViewImports.cshtml

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#5009]
Consider the following in a project's `_ViewImports.cshtml` file:
``` html
@using RazorPagesWebApplication
@using RazorPagesWebApplication.Data
@using Microsoft.AspNetCore.Identity
```

The actual namespaces are all grayed out by the editor suggesting they aren't needed.

**Comment by allisonchou** [comment]
This looks to be resolved in the new Razor editor, will close out.
