### ISSUE TITLE
[Announcement] Preparing for the 8.0 release

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#50091]
Hello all,

As we wind down development on the 8.0.0 release, yesterday we forked [release/8.0](https://github.com/dotnet/aspnetcore/tree/release/8.0) and [release/8.0-rc1](https://github.com/dotnet/aspnetcore/tree/release/8.0-rc1) branches off of `main`, and rebranded `main` to `9.0.0-alpha1`. As such, any further changes in the `main` branch will be targeted towards .NET 9, not .NET 8. Below are some of our key dates as we finalize the RC1, RC2, and RTM releases:

- **8/21**: We lock down the `release/8.0-rc1` branch.
- **9/12**: .NET 8.0-rc1 ships publicly.
- **9/18**: We snap a `release/8.0-rc2` branch off of `release/8.0`.
- **9/24**: We lock down the `release/8.0-rc2` branch.
- **10/10**: .NET 8.0-rc2 ships publicly.
- **10/25**: Last date for check-ins for .NET 8 RTM
- **11/14**: .NET 8 RTM ships publicly.

## What this means for you

If you’re contributing, this likely doesn’t affect you – all year round, the right branch for community PR’s is always `main`. As of now those PR’s will now go into .NET 9. In the rare case where you believe your change in main ought to be ported into .NET 8, please let us know on the PR.

We're looking forward to sharing more updates with you, and to getting .NET 8 into your hands soon!

**Comment by marinasundstrom** [comment]
I'm waiting for a functioning RC1 build. Right now I'm having problems with building Docker images against 8.0-preview. Hopefully, it will be solved once you have locked down RC1.

This is my problem:

```
error CS7069: Reference to type 'IRazorComponentsBuilder' claims it is defined in 'Microsoft.AspNetCore.Components.Endpoints', but it could not be found [
``

Works with a local installation of the nightly "RC2" SDK though.

**Comment by Bartmax** [comment]
me too. `Reference to type 'IRazorComponentsBuilder' claims it is defined in 'Microsoft.AspNetCore.Components.Endpoints', but it could not be found`

**Comment by MariovanZeist** [comment]
Congratulations Team. on bringing us the next evolution of .NET 🎉🎉🎉
