### ISSUE TITLE
support AttributeUsage AttributeTargets.Class for minimal api handlers

### ISSUE THREAD

**Issue by ivanjx** [dotnet/aspnetcore#50101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

i am putting my minimal api handlers/controllers into each classes as demonstrated here:

```
public class AdministratorDeviceController
{
    public static void Map(WebApplication app)
    {
        AdministratorDeviceController controller = new AdministratorDeviceController();
        app.MapGet("/administrator/devices/list", controller.ListAsync);
        app.MapPost("/administrator/devices/deny", controller.DenyAsync);
        app.MapPost("/administrator/devices/approve", controller.ApproveAsync);
    }
...
```

it would be very useful to be able to put my custom attributes in the class level instead of the method level. this is how i define my custom attribute currently:
```
[AttributeUsage(AttributeTargets.Method)]
public class MyCustomAttribute : Attribute
{
}
```

and this is the middleware to detect the attribute:
```
MyCustomAttribute? attribute = context.Features
    .Get<IEndpointFeature>()?
    .Endpoint?
    .Metadata
    .GetMetadata<MyCustomeAttribute>();

if (attribute != null)
{
...
```

### Describe the solution you'd like

so far i am only able to attach the custom attribute in the method level. class level attributes with `AttributeTargets.Class` simply wont get detected in the middleware.

**Comment by captainsafia** [comment]
@ivanjx Have you considered leveraging route groups for this? That way you can create a single group for your `/administrator` endpoints and apply shared metadata to it. You can read more about that feature [in this doc section](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#route-groups).

**Comment by ivanjx** [comment]
sorry for the late response. i will look into the methods you provided instead.
