### ISSUE TITLE
ViewComponentTagHelper: Allow optional parameters

### ISSUE THREAD

**Issue by pawchen** [dotnet/aspnetcore#5011]
Say we have a ViewComponent class

```C#
class MyViewComponent
{
    IViewComponentResult Invoke( bool showSomething = false ) { ... }
}
```

It would be great to just only write `<vc:my />` in Razor if one don't want to show that something. Currently you have to write `<vc:my show-something="false" />`.

**Comment by ASKemp** [comment]
Came here to say same thing after finding this issue and spending some time tracking down why on of my tag helper called VC's wasn't presenting any output.

**Comment by CamiloTerevinto** [comment]
Hey @rynowak:

I thought I would give this a shot and after reading the source code [here](https://github.com/aspnet/AspNetCore-Tooling/tree/master/src/Razor/src) (your link is dead), it seems pretty easy to fix. However, there are at least two ways ( either create a replica of `RequiredAttributeDescriptor` and friends, or move to a base clas/interface) to do this and it's a substantial amount of code changes.

**Comment by emumanu** [comment]
@rynowak and/or @DamianEdwards, please tell something to @CamiloTerevinto as we want to see this improved.

**Comment by Rick-Anderson** [comment]
Updated doc with

## All view component parameters are required

Each parameter in a view component is a required attribute. See [this GitHub issue](https://github.com/aspnet/AspNetCore/issues/5011). If any  parameter is omitted:

* The `InvokeAsync` method signature won't match, therefore the method won't execute.
* The ViewComponent won't render any markup.
* No errors will be thrown.

**Comment by os1r1s110** [comment]
Just got bitten hard by it (the notice was not there at the time I implemented it in my app)

Is there a planned solution or will it stay like this for the foreseeable future? As this can be really dangerous, especially that it fails silently... Could there at least be a warning or something like that at compile time?

**Comment by jerriep** [comment]
Yeah, I agree with the last comment. I also got bitten hard by this recently and the fact that it simply fails silently is not good.

**Comment by Rick-Anderson** [comment]
@rynowak  is it possible to generate an error?

**Comment by staa99** [comment]
@rynowak Will there be any support for this in the future?

It's been over two years, and honestly, it is a pain to have to duplicate default parameters everywhere a view component is used.

**Comment by Rick-Anderson** [comment]
@rynowak  what's the correct line number in
> This seems pretty feasible. We need to teach [this code](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.CodeAnalysis.Razor/ViewComponentTagHelperDescriptorFactory.cs#L62) about default values. Currently it says that each parameter is a _required_ attribute

[this code](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTagHelperDescriptorFactory.cs#L63) updated link but maybe not correct line

**Comment by josephr5000** [comment]
Thanks @Rick-Anderson for updating the docs, but it's ridiculous that you should even have to.  This makes the tag helper UNUSABLE for serious projects.  To have code fail _silently_ when you refactor or add features should be completely unacceptable.  I'm stunned that this is still open almost three years after first being reported.  Is any fix planned?!

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  @rynowak  please review and @rynowak  can you check

@rynowak  what's the correct line number in
> This seems pretty feasible. We need to teach [this code](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.CodeAnalysis.Razor/ViewComponentTagHelperDescriptorFactory.cs#L62) about default values. Currently it says that each parameter is a _required_ attribute

[this code](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTagHelperDescriptorFactory.cs#L63)  : updated link but maybe not correct line

**Comment by brgrz** [comment]
so in 3 years this @rynowak guy didn't come on top of this issue

**Comment by os1r1s110** [comment]
@brgrz have you come up with a solution? Because if "this @rynowak " can't come up with one, maybe you could come and help (trying to be constructive maybe instead of destructive, your comment brings nothing to the table here IMO...) 

I must agree it is sad to realize there's no proposed solution yet and that this problem has been reported a long time ago, but never forget they are not 1000 working on it and they have lots of areas to cover... so I'm not surprised some issues are left unresolved for long periods, it's the same for every open source project out there.... (almost)

**Comment by mkArtakMSFT** [comment]
We'll add support for this in 5.0!

**Comment by brgrz** [comment]
> @brgrz have you come up with a solution? Because if "this @rynowak " can't come up with one, maybe you could come and help (trying to be constructive maybe instead of destructive, your comment brings nothing to the table here IMO...)
> 
> I must agree it is sad to realize there's no proposed solution yet and that this problem has been reported a long time ago, but never forget they are not 1000 working on it and they have lots of areas to cover... so I'm not surprised some issues are left unresolved for long periods, it's the same for every open source project out there.... (almost)

@os1r1s110  Oh, please... cut the contributor bullshit, rynowak posted "This seems pretty feasible" 3 years ago. I bet this single issue cost developers worldwide hundreds of wasted debugging hours and head banging in the meantime. 

Also, ASP.NET Core is not my product nor is it community product, it is MS product. Even if I wanted  I highly doubt they'd accept my solution and MS employees are paid to do it.

**Comment by os1r1s110** [comment]
@brgrz As I said, I was also sad that it was not fixed sooner, but I think there's still a way to present things and not consider everyone working on open source projects owes you something (paid or not). Yes, they are paid to work on asp.net core and related projects, but that doesn't mean they have enough resources to fulfill all the needs in a timely manner (and I'm not even talking specifically about open source projects here, there's a need for qualified staff in every freaking domain nowadays).

Sorry if I offended you by replying to your post, but I still think that's not the way to make things move (and I don't consider it being "contributor bullshit"), even though it looks like it did make things move.... :)

**Comment by mkArtakMSFT** [comment]
Moving back to the `Next sprint planning` as we didn't get to this in this milestone.

**Comment by guitax** [comment]
> We'll add support for this in 5.0!

Is this going to make it in the end?

**Comment by lvmajor** [comment]
@guitax considering the number of times it has been delayed plus the fact that it has been put back on the backlog, I'd say chances are really really low 😕 It seems like the new priority now is blazor.

Let's just hope this will end up being implemented as it's a really irritating problem. 😂

**Comment by dugsteen** [comment]
At the very least it would be nice if this requirement were made much more clear in the documentation. Missing attributes defaulting to a standard value are the norm in HTML; the idea that they would be required for view components did not occur to me until I stumbled upon this thread.

**Comment by jishansiddique** [comment]
This issue exists in **.NET 5** as well as.
Any update?

**Comment by mc0re** [comment]
Also note, that this syntax works fine for tag helpers (as it does in ordinary HTML and in XAML -and I'm probably missing a dozen of other examples). I wanted to switch from a tag helper to a view component, as my HTML grew, and I didn't want to generate it in code. Now I have to add a lot of unnecessary HTML in all the other places :-(

**Comment by Santas** [comment]
Is there a plan to land this in .NET 6? Thanks!

**Comment by jishansiddique** [comment]
Hi @Santas,
As per the blog [Click me](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/),
I've checked but not able to find any optional parameter in the `view component`.

**Comment by OliWald** [comment]
we really need optional parameters support in ViewComonents. please give us this

**Comment by mkArtakMSFT** [comment]
Let's try to time-box this effort. If we can do this in 2 days, we'll do this in current milestone (6.0-preview6)

**Comment by lvmajor** [comment]
> Let's try to time-box this effort. If we can do this in 2 days, we'll do this in current milestone (6.0-preview6)

This would be really awesome!

**Comment by captainsafia** [comment]
Closing as resolved. This will ship in .NET 6 Preview 6. Thanks for the patience folks!

**Comment by tompazourek** [comment]
This is great. Thank you all very much.

I have one a bit related/unrelated question: **How do you update the documentation pages so that they'll reflect the new features and changes?** Should there be a PR in https://github.com/dotnet/AspNetCore.Docs to update the information there?

This part is now no longer true, right?

> All view component parameters are required
> Each parameter in a view component is a required attribute.
> (...)

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components.md#all-view-component-parameters-are-required

**Comment by jishansiddique** [comment]
This is really great. Thank you all very much.

**Comment by captainsafia** [comment]
@tompazourek Good call.

@Rick-Anderson We can update the docs here for .NET 6 on as this feature is now supported. If a default value is passed to a parameter, then that parameter is option.

**Comment by Rick-Anderson** [comment]
>  If a default value is passed to a parameter, then that parameter is option.

then that parameter is ~option~ ***optional***.
