### ISSUE TITLE
UserManager.IsInRoleAsync(appUser, "rolename") and User.IsInrole("rolename") may return different results

### ISSUE THREAD

**Issue by diskb** [dotnet/aspnetcore#50125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the Microsoft.AspNetCore.Identity.EntityFrameworkCore package, the ClaimsPrincipal [Microsoft.AspNetCore.Mvc.ControllerBase.User.IsInrole()](https://github.com/dotnet/runtime/blob/2ed506c010b41c41c01997c81df977831f0fa217/src/libraries/System.Security.Claims/src/System/Security/Claims/ClaimsPrincipal.cs#L486C35-L486C35) and [Microsoft.AspNetCore.Identity.UserManager<IdentityUser>.IsInRoleAsync()](https://github.com/dotnet/aspnetcore/blob/c41d451aa9c40d4a85b9d9ce2c36bb3115831a3c/src/Identity/Extensions.Core/src/UserManager.cs#L1235C11-L1235C11) methods may return different values for the same authorized user and the same IdentityRole name parameter. If the case of the role name string stored in the database (the Name field) is different from the case of the role name string passed as a parameter to the specified methods, the UserManager.IsInRoleAsync(user, "rolename") and User.IsInrole("rolename") methods will return different values.
Thus, `User.IsInRole("rolename") != _userManager.IsInRoleAsync(identityUser, "rolename")`

This is due to the fact that UserManager.IsInRoleAsync() calls the UserStore class method [IsInRoleAsync(normalizedRoleName)](https://github.com/dotnet/aspnetcore/blob/c41d451aa9c40d4a85b9d9ce2c36bb3115831a3c/src/Identity/EntityFrameworkCore/src/UserStore.cs#L388), where the database is searched for a case-insensitive role match against the normalized NormalizedName property without additional checks (see the [FindRoleAsync() method](https://github.com/dotnet/aspnetcore/blob/c41d451aa9c40d4a85b9d9ce2c36bb3115831a3c/src/Identity/EntityFrameworkCore/src/UserStore.cs#L257) in UserStore. cs). Whereas User.IsInrole() calls the [HasClaim(string type, string value) method](https://github.com/dotnet/runtime/blob/2ed506c010b41c41c01997c81df977831f0fa217/src/libraries/System.Security.Claims/src/System/Security/Claims/ClaimsIdentity.cs#L668C55-L668C55) of the ClaimsIdentity class (ClaimsIdentity.cs). There, the value is checked already case-sensitive: string.Equals(claim.Value, value, StringComparison.Ordinal), where a NOT normalized role name is passed as a parameter

### Expected Behavior

`User.IsInRole("rolename") == _userManager.IsInRoleAsync(identityUser, "rolename") //, presumably == False`

### Steps To Reproduce

Add a default Identity with EntityFrameworkStores and IdentityRoles from Microsoft.AspNetCore.Identity.EntityFrameworkCore:
```
services.AddDefaultIdentity<IdentityUser>()
                 .AddRoles<IdentityRole>()
                 .AddEntityFrameworkStores<ApplicationDbContext>();
```
Create role "RoleName" (note the case)
Create user.
Add the role "RoleName" to the user
Log in with this user and get a valid cookie ("".AspNetCore.Identity.Application").
Call the instance methods UserManager.IsInRoleAsync(appUser, "rolename") and User.IsInrole("rolename") in the controller and compare the result.:

Here is Controller sample with the bug reproduction:

```
using _TestIdentyiry.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace _TestIdentyiry.Controllers
{
    public class HomeController : Controller
    {
        const string roleName = "RoleName";
        private const string someUserName = "UserName";
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public HomeController(ApplicationDbContext context
            , UserManager<IdentityUser> userManager
            , SignInManager<IdentityUser> signInManager
            , RoleManager<IdentityRole> roleManage)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManage;
        }

        /// <summary>
        /// Creates a user, a role, adds a role for the user, and logs the user in
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Bug()
        {
            //We need any Identity Role in database...
            await _roleManager.CreateAsync(new IdentityRole(roleName));

            //...and any Identity User...
            var identityUser = new IdentityUser(someUserName);
            await _userManager.CreateAsync(identityUser);

            identityUser = await _userManager.FindByNameAsync(someUserName);
            //...with Role
            await _userManager.AddToRoleAsync(identityUser, roleName);

            //Login any (created) user with any associated role(s)
            await _signInManager.SignInAsync(identityUser, false);

            //We need to update and receive cookies for ClaimsPrincipal User instance of just logged in user
            //Open another page for this to get a new http request:
            return RedirectToAction(nameof(BugResult));
        }

        public async Task<IActionResult> BugResult()
        {
            string roleNameLower = roleName.ToLower(); //<-- Different case (in)sensitive behavior in _userManager.IsInRoleAsync() and User.IsInRole() methods!

            var identityUser = await _userManager.FindByNameAsync(someUserName);

            var userIsInRoleCamel =                                     User.IsInRole(roleName); //True
            var userManIsInRoleCamel = await _userManager.IsInRoleAsync(identityUser, roleName); //True
            
            var userIsInRoleLower =                                     User.IsInRole(roleNameLower); //False !!!
            var userManIsInRoleLower = await _userManager.IsInRoleAsync(identityUser, roleNameLower); //True  !!!

            return Content(
                $"'CamelCase' role name: User.IsInRole(\"{roleName}\") = {userIsInRoleCamel}, " +
                $"_userManager.IsInRoleAsync(identityUser, \"{roleName}\") = {userManIsInRoleCamel}" +
                $"{Environment.NewLine}" +
                $"'lowerCase' role name: User.IsInRole(\"{roleNameLower}\") = {userIsInRoleLower}," +
                $" _userManager.IsInRoleAsync(identityUser, \"{roleNameLower}\") = {userManIsInRoleLower}");

            /*
            OUTPUT:
            'CamelCase' role name: User.IsInRole("RoleName") = True, _userManager.IsInRoleAsync(identityUser, "RoleName") = True
            'lowerCase' role name: User.IsInRole("rolename") = False, _userManager.IsInRoleAsync(identityUser, "rolename") = True
            */

            /*
             *  Expected Behavior:   User.IsInRole("rolename") == _userManager.IsInRoleAsync(identityUser, "rolename"), presumably == False
             *  Unexpected Behavior: User.IsInRole("rolename") != _userManager.IsInRoleAsync(identityUser, "rolename")
             */
        }
    }
}
```
Part of Sturtup.cs:

```
        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));

            services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
            ...
        }
```

ApplicationDbContext.cs:

```
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace _TestIdentyiry.Data
{
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
}



```

### .NET Version

6.0.201

**Comment by SteveSandersonMS** [comment]
Thanks for the report. Are you able to supply a minimal repro project, ideally as a GitHub issue? We will then investigate.
