### ISSUE TITLE
Header and Footer Inconsistencies (scrolling and transparency issues)

### ISSUE THREAD

**Issue by sultan** [dotnet/aspnetcore#50121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[mobile] The Header and Footer do not need to be fixed on small mobile devices. they take up some space.
[desktop] Transparency issues are observed in both the header and footer elements. When scrolling, we can see through them.
[both] Media queries are using inconsistent Bootstrap Breakpoints (small and large)

### Expected Behavior

Sticky Header and Fixed Footer on desktop only.
When scrolling, we should not be able to see through the header and footer.
Media queries should use consistent Bootstrap Breakpoints (either small or large)

### Steps To Reproduce

make a razor view with enough content to make the page scroll in desktop

### Exceptions (if any)

None

### .NET Version

At least versions 6, 7 and 8.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback. We've decided that we will be modernizing the template during .NET 9 and we will incorporate your feedback as part of that work, that we track using https://github.com/dotnet/aspnetcore/issues/53142
