### ISSUE TITLE
NSwag.AspNetCore instead of Swashbuckle.AspNetCore

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#50133]
`Swashbuckle.AspNetCore` is no longer activity, and `NSwag.AspNetCore` instead of `Swashbuckle.AspNetCore`

https://github.com/dotnet/aspnetcore/blob/76d2fda2659928859972211d99b5457180f2a8d8/src/ProjectTemplates/Web.ProjectTemplates/WebApi-CSharp.csproj.in#L22

**Comment by davidfowl** [comment]
What do you mean Swashbuckle.AspNetCore it's no longer active?

**Comment by davidfowl** [comment]
NSwag.AspNetCore supports AOT? Can you point me to this support?

**Comment by marinasundstrom** [comment]
I personally prefer NSwag, but that is a choice based on feature set. 

The C# client generator (NSwag) works best with NSwag's OpenAPI document.

I have been following the NSwag repository, and it is pretty much a one man operation by @RicoSuter. A lot of issues and PRs that never have been closed. So hard to keep track of what is happening.

A major difference between the libraries is that Swashbuckle uses System.Text.Json, while the NSwag toolchain is built on Newtonsoft Json.

Overall, both libraries might be considered stable, so there are no changes unless there are serious issues.

I'm a proponent of making this a choice. 

But as it is now, it is pretty easy switching out Swashbuckle for NSwag.AspNetCore. And the ASP.NET Core documentation mentions them both:

* [Get started with Swashbuckle and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&tabs=visual-studio)
* [Get started with NSwag and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-7.0&tabs=visual-studio)

The purpose of having Swashbuckle is just to have something to start with.
