### ISSUE TITLE
[dotnet-sdk-8.0.100-rc.1.23415.7] Fail to load local css,js with Cofoundry template.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#50141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are testing a web application created with Cofoundry .Net Core CMS framework, when we run on .net8(8.0.100-rc.1.23415.7) runtime, we noticed local css files does not load, so page doesn't show properly. 

**Application Name:** Cofoundry,Cofoundry.Samples.SPASite
**OS：** Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-8.0.100-rc.1.23415.7
**App & Source Location Checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1871585
**App github link:**
https://github.com/cofoundry-cms/cofoundry
https://github.com/cofoundry-cms/Cofoundry.Samples.SPASite

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23415.7: Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.413-win-x64: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23412.1: Pass

### Expected Behavior

Shows setup page

### Steps To Reproduce

Minimal Repro steps (Demo attached): [WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/12369093/WebApplication1.zip)

ref: [Installing | Cofoundry Docs](https://www.cofoundry.org/docs/getting-started/installing)

1) Create ASP.NET Core Web App project(.net6)
2) Install this nuget package : Cofoundry.Web.Admin --version 0.11.4
3) Add this code to program.cs to configure Cofoundry
```
         var builder = WebApplication.CreateBuilder(args);
            builder.Services
                .AddControllersWithViews()
                .AddCofoundry(builder.Configuration);
            var app = builder.Build();
            app.UseHttpsRedirection();
            app.UseCofoundry();
            app.Run();
```
4) Add Db Connection to appsettings.json, MyCofoundrySite is an empty Database
```
  "Cofoundry": {
    "Database": {
      "ConnectionString": "Server=(localdb)\\mssqllocaldb;Database=MyCofoundrySite;Integrated Security=True;MultipleActiveResultSets=True"
    }
  }
```
5. Build and publish and run it with .net8 runtime
6) Go to :  ```http://localhost:5000/```

**Actual Result:**

Empty page with errors :
![image](https://github.com/dotnet/aspnetcore/assets/83067197/2f0da5ce-69a6-40b3-874b-ba43c7528bfc)

### .NET Version

8.0.100-rc.1.23415.7

### Anything else?

**dotnet info:**
```
.NET SDK:
 Version:    8.0.100-rc.1.23415.7
 Commit:    18fe2525ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:    C:\Program Files\dotnet\sdk\8.0.100-rc.1.23415.7\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23370.6
  Architecture: x64
  Commit:       ebd23467f0
  RID:          win-x64

.NET SDKs installed:
  8.0.100-rc.1.23415.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.1.23414.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.NETCore.App 8.0.0-rc.1.23414.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.WindowsDesktop.App 8.0.0-rc.1.23412.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT This issue is found during .NET 8 RC1 validation. Could you please confirm whether it is a blocker for RC1? Thanks.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please give this scenario a try and see if this is an issue with our framework, or with the dependency?

**Comment by Junjun-zhao** [comment]
@javiercn Do you have any update for this issue?  Thanks for helping investigate it.

**Comment by Junjun-zhao** [comment]
@javiercn @mkArtakMSFT Thank you for checking this issue.  Now we are RC2 validation, this issue still repro. Do you have a try for this scenario?  If so, is it an issue for our Framework? If no, do you have any plans for it?

**Comment by PriyaPurkayastha** [comment]
@Junjun-zhao what is the behavior on .NET7? The repro information indicates this was passing in .NET6 and failed in .NET8 RC1. 
Verify Scenarios:
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23415.7: Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.413-win-x64: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23412.1: Pass
Can you check and clarify the behavior with .NET 7 or other .NET 8 Previews? That will help narrow down the release where this change was introduced.

**Comment by mkArtakMSFT** [comment]
> Can you check and clarify the behavior with .NET 7 or other .NET 8 Previews?

No need for verifying other .NET 8 Previews. Just the latest 7.0 and 8.0-rc2 please.

**Comment by Junjun-zhao** [comment]
>  No need for verifying other .NET 8 Previews. Just the latest 7.0 and 8.0-rc2 please.

It works on the latest 7.0, the latest 8.0-rc2 is not working. And it fails starting with 8.0.100-rc.1.23415.7.
I have updated the verification scenario as shown below, please let me know if anything is unclear.

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.413-win-x64: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-7.0.402-win-x64: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23412.1: Pass
4). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23415.7: Fail
5). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.2.23472.8: Fail

**Comment by Junjun-zhao** [comment]
Verified with the latest RC2 coherent build dotnet-sdk-8.0.100-rc.2.23477.19, the issue has fixed and does not repro.
