### ISSUE TITLE
Introduce [OutputAttributeHint] to allow attributes to function as known HTML attributes when used in the editor

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#5014]
_From @stap123 on June 12, 2017 9:13_

When using the <a> tag helper and a target attribute simultaneously VS2017 gives a warning saying "Attribute is allowed only when 'href' is present".  I guess it's pretty obvious why it's happening as it tells us but not sure it's the desired behaviour.

Example of tag:

```
<a class="list-group-item" asp-controller="Home" asp-action="CPDRedirect" asp-route-id="2" target="_blank">View all activities</a>
```

This is obviously not stopping anything working but thought you might like to know (and it's a little annoying to have warnings when there isn't anything wrong).

If this isn't the correct repo, can you let me know the correct one and I will raise there.

_Copied from original issue: aspnet/Mvc#6391_

**Comment by niltor** [comment]
When can we solve this issue?
vs2019 preview2 has the same issue

**Comment by timcromarty** [comment]
Still seeing this in VS2019 RTM

**Comment by TanayParikh** [comment]
Closing this out as it was addressed via https://github.com/dotnet/aspnetcore-tooling/pull/3031.
