### ISSUE TITLE
Baggage not extracted without trace id from the request

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#50158]
The Baggage specification states that the baggage can be used regardless of whether Distributed Tracing is used (at the beginning of https://www.w3.org/TR/baggage).
I wonder why the baggage is not taken into account if we the trace id could not be extracted from the request here:
https://github.com/dotnet/aspnetcore/blob/31a26e080ae5652cd3c9b414078d1b61a0b89010/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L411-L434

**Comment by mkArtakMSFT** [comment]
@amcasey this looks like a OpenTelemetry-related, rather than hosting. Should this be moved back to your area for investigation?

**Comment by amcasey** [comment]
Oops, got confused by the path in the description.
