### ISSUE TITLE
Misaligned breakpoint highlighting

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#5015]
I spoke to @NTaylorMullen about this. Even though there are certain situations where it's not possible to align the breakpoint highlighting, this apparently isn't one of them.

The following would look correct to me if the highlighting was shifted two columns to the right but I'm not sure if the `<p>` tags are meant to be highlighted.

![image](https://user-images.githubusercontent.com/54385/27247611-23fea1ce-52af-11e7-83ad-138ab4d1df57.png)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by NTaylorMullen** [comment]
This is actually fixed via LSPification 😉
