### ISSUE TITLE
EnableRequestDelegateGenerator fails when MapX is on its own line

### ISSUE THREAD

**Issue by jamiewinder** [dotnet/aspnetcore#50164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following code works:

```c#
group.MapGet("/", GetAll)
    .WithDescription("Get all todos");
```

But the following does not (moving `.MapGet` to its own line):
```c#
group
    .MapGet("/", GetAll)
    .WithDescription("Get all todos");
```
With the following error.
```
Error	
CS9143	
The given line is '13' characters long, which is fewer than the provided character number '15'.	
Api	\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs	62	Active
```

### Expected Behavior

It shouldn't make a difference how the code is formatted.

### .NET Version

8.0.100-preview.7.23376.3

**Comment by captainsafia** [comment]
Closed via PR above.
