### ISSUE TITLE
Having breakpoints in cshtml files that are not open in the editor breaks debugging

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#5017]
Steps to reproduce:
- Create a new Web application
- Add a breakpoint in `Index.cshtml`
![image](https://user-images.githubusercontent.com/1579269/27502798-9c4785d4-582b-11e7-969b-2aa2f4bcf016.png)
- Close the file in the editor
- Press F5 to run the app
- Press F5 again when the breakpoint is hit
![image](https://user-images.githubusercontent.com/1579269/27502830-e852308c-582b-11e7-8fc7-220c70d9c12e.png)

I think this is probably a tooling issue but I am not sure.

VS version: 26621.2.d15rel

**Comment by sotoabraham** [comment]
This still lives huh? Been a couple years I think.  Well if it helps, I have this issue whenever I include namespaces and/or add a "addTagHelper" to the _ViewImports.cshtml file in a project.  

When I leave only the "@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers" line in there, I have no issues when I place a breakpoint in a razor file or if I have Exception settings set to "Break When Thrown" and an exception occurs in a razor file.  

But the moment I add a namespace or other tag helper to _ViewImports.cshtml I'm not able to continue debugging, (this may be dependent on the scope of the taghelper or the need of the namespace for that razor file/view).

**Comment by KPatel91** [comment]
@sotoabraham thanks for this - it's a bit strange that this is still an issue but indeed on netcore2.2 my project uses SpaServices tag helper and if I remove it, I have no issues debugging / even having cshtml files open.

It's a weird one that's plagued my new clients project for years but nobody has ever bothered looking into it, their workflow has literally been "place your breakpoint, close the file, and re-start the project" which is a horrible workflow lol.

**Comment by copernicus365** [comment]
I had a `_ViewImports.cshtml` within one View's folder (`Views/Foo`), and in it had a single namespace that had been commented out, making the import not needed. Removing this file fixed the problem. Then re-adding the `_ViewImports.cshtml`, even testing with the same commented out namespace, suddenly couldn't reduplicate the problem. Keep in mind I cleaned the solution, deleted obj / bin, etc, many times over before finding this solution, none of which helped. So ... there is indeed something messed up here, I just wanted to add this little extra bit if it helps to solve the problem.

**Comment by TPucke** [comment]
I am having this issue as well.  It started when I started working on asp.net 3.0 applications and VS 2019.  I can just open a fresh window, go straight to a debug execution, and if I hit a breakpoint I often can't resume.  Same warning ENC0021 in my Error List panel and same dialog box telling to me Edit or Stop.  
Funny thing today, I was staring at the warning in anger and it disappeared.  I hit F5 and could continue no further problem.  Happened once...

**Comment by fleckert** [comment]
Any updates regarding this...?

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb the referenced issue has been resolved. Should this be closed already?

**Comment by ajaybhargavb** [comment]
This has been fixed.
