### ISSUE TITLE
Microsoft.AspNetCore.Grpc.Swagger Package Version

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#50176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Why is the package version 0.8.0 instead of 8.0.0?

![image](https://github.com/dotnet/aspnetcore/assets/5714438/77e5e2c5-557e-4afa-a733-30e683964b1f)

**Comment by martincostello** [comment]
It looks like it's considered to be experimental: https://github.com/dotnet/aspnetcore/pull/43384

**Comment by wtgodbe** [comment]
@JamesNK is it intentional we're still using an experimental version for this package? Is there more info on when we're planning on shipping an "Official" version?

**Comment by JamesNK** [comment]
Yes, it's intentionally experimental.

I wanted to see if there was a way to support this feature without a dependency Swashbuckle.AspNetCore but haven't had time this year.

**Comment by JamesNK** [comment]
If it is updated to be non-experimental, then it will be renamed.
