### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	MSB3027	Could not copy "E:\15. Code Learning\Learning\Core.Application\bin\Debug\net8.0\Core.Application.dll" to "bin\Debug\net8.0\Core.Application.dll". Exceeded retry count of 10. Failed. The file is locked by: ".NET Host (4176)"	Presentation.MVC	d:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4879	

### ISSUE THREAD

**Issue by nguyentuananh921** [dotnet/aspnetcore#50200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't build the project and I got this Error. Hopping that anybody facing the same problem can help me to solve. Thanks.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "E:\15. Code Learning\Learning\Core.Application\bin\Debug\net8.0\Core.Application.dll" to "bin\Debug\net8.0\Core.Application.dll". Exceeded retry count of 10. Failed. The file is locked by: ".NET Host (4176)"	Presentation.MVC	d:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4879	

### Steps To Reproduce

https://github.com/nguyentuananh921/Learning

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

I am not sure it is a bug or not but I can't build my solution. and I got this Error.
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "E:\15. Code Learning\Learning\Core.Application\bin\Debug\net8.0\Core.Application.dll" to "bin\Debug\net8.0\Core.Application.dll". Exceeded retry count of 10. Failed. The file is locked by: ".NET Host (4176)"	Presentation.MVC	d:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4879

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
