### ISSUE TITLE
[.NET 8 Preview 7] PageTitle doesn't update when disabling Prerendering using Blazor Web App

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#50209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The PageTitle component doesn't work when the attribute RenderModeServer/RenderModeAuto/RenderModeWebAssembly has prerendering turned off, i.e. @attribute [RenderModeServer(false)].

### Expected Behavior

Disabling prerendering shouldn't affect PageTitle and users should be able to set it regardless via the PageTitle component.

### Steps To Reproduce

1. Create a new Blazor Web App project
2. Open Counter.razor
3. Change @attribute [RenderModeServer] to @attribute [RenderModeServer(false)]
4. See that PageTitle-component is not working

### .NET Version

8.0.100-preview.7.23376.3

**Comment by marinasundstrom** [comment]
This must be the same:

I have an interactive component with ``@rendermode="@RenderMode.Auto"`` on a SSR page. The page has a ``PageTitle`` component. So does the interactive component. 

I expected the interactive component to update the title.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

The page title doesn't update because the `<HeadOutlet>` component was statically rendered (not interactive). If the `<HeadOutlet>` were made to be interactive, then it should update dynamically. Otherwise, you'll have to ensure that components containing `<PageTitle>` components are prerendered.

**Comment by marinasundstrom** [comment]
Oh! Makes sense to me then, thanks @MackinnonBuck.

**Comment by marinasundstrom** [comment]
@MackinnonBuck It is strange though. If I introduce this to my mixed render mode site:

```razor
<HeadOutlet @rendermode="@RenderMode.Auto" />
```

Then ``<PageTitle>My title</PageTitle>`` will work for dynamic components, but not statically rendered pages. The title will just be "localhost:1234/path" etc.

So mixed mode is not working for ``PageTitle``.
