### ISSUE TITLE
How to get HttpClient BaseAddress in Blazor Server Application from appsetting.json file

### ISSUE THREAD

**Issue by utsabbasyal12** [dotnet/aspnetcore#50223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

//appsetting.json
{
  "BaseUrl": {
    "ApiUrl": "https://localhost:7134/api/",
  },

//program.cs 
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

//UI Manager

public class DepartmentManager : IDepartmentManager
{
    private HttpClient _httpClient = new HttpClient();
    private readonly IConfiguration _configuration;

    public DepartmentManager (IConfiguration configuration)
    {
        _configuration = configuration;
        string authAddress = _configuration.GetSection("BaseUrl")["ApiUrl"];
        _httpClient.BaseAddress = new Uri(authAddress);
    }
    public async Task<List<DepartmentViewModel>> GetAllDepartment()
    {
          await setToken();
          var data = await _httpClient.GetAsync(DepartmentEndPoints.GetAll);
          if (data != null)
          {
              var responseData = await data.Content.ReadAsStringAsync();
              var department = JsonConvert.DeserializeObject<List<DepartmentViewModel>>(responseData);
              return department!;
          }
          else
          {
              return new List<DepartmentViewModel>();
          }
     }
}
Where am i doing wrong, its not working 

### Expected Behavior

If it work, it should hit API controller to get department details.

### .NET Version

6

**Comment by DM-98** [comment]
I don't think this is the place to ask, this bug report section is for bugs. But here:

`builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(configuration["BaseUrl:ApiUrl"] });`

Also, consider using IHttpClientFactory which is the optimal choice for Blazor Server (as well as DbContextFactory if you're using a DbContext):
`builder.Services.AddHttpClient<IDepartmentManager, DepartmentManager>(httpClient => httpClient.BaseAddress = new Uri(builder.Configuration["BaseUrl:ApiUrl"]));`

and constructor inject it by doing: 
```
private readonly HttpClient _httpClient;

public DepartmentManager(HttpClient httpClient)
{
    httpClient = httpClient;
}
```

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

We agree with the advice in @DM-98's comment.

Please also note that for Blazor Server apps, we don't recommend using `HttpClient` to have the server make requests to itself.
