### ISSUE TITLE
Add ProblemDetials.Extensions to ControllerBase.Problem and ControllerBase.ValidationProblem

### ISSUE THREAD

**Issue by mariusz96** [dotnet/aspnetcore#50220]
## Background and Motivation

Currently, there are methods on `ControllerBase` for returning responses in `application\problem+json` format by using `ProblemDetails` and `ValidationProblemDetails` classes.

However, both of this methods lack parameter for `ProblemDetails.Extensions`. This parameter has already been added to `Results` class and can otherwise be modified on `ProblemDetails` object as it is `IDictionary<string, object>`.

But currently developers using the framework don't have a straightforward way to add these extensions to the response in the controller using existing convenience methods.

## Links
The PR:
- https://github.com/dotnet/aspnetcore/pull/50204

Issues:
- https://github.com/dotnet/aspnetcore/issues/43159
- https://github.com/dotnet/aspnetcore/issues/36848 (here the same was added to the `Results` class)
- https://github.com/dotnet/aspnetcore/issues/19873
- https://github.com/dotnet/aspnetcore/pull/47539

## Proposed API

```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract class ControllerBase
{
    public virtual ObjectResult Problem(
        string? detail = null,
        string? instance = null,
        int? statusCode = null,
        string? title = null,
        string? type = null)
        string? type = null,
+       IDictionary<string, object?>? extensions = null);

    public virtual ActionResult ValidationProblem(
        string? detail = null,
        string? instance = null,
        int? statusCode = null,
        string? title = null,
        string? type = null,
        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary = null,
+       IDictionary<string, object?>? extensions = null);
}
```

## Usage Examples

```csharp
return Problem(extensions: new Dictionary<string, object?> { { "ext1", 1 }, { "ext2", 2 } });
```

```csharp
return ValidationProblem(extensions: new Dictionary<string, object?> { { "ext1", 1 }, { "ext2", 2 } });
```

## Alternative Designs

Originally, I thought of adding this:
```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract class ControllerBase
{
+   public virtual ObjectResult Problem(ProblemDetails descriptor);
}
```
to match existing:
```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract class ControllerBase
{
    public virtual ObjectResult ValiadtionProblem([ActionResultObjectValue] ValiadtionProblemDetails descriptor);
}
```
but on further consideration I don't want this as this overload of `ValidationProblem` method does not apply defaults like ie [DefaultApiProblemDetailsWriter does](https://github.com/dotnet/aspnetcore/blob/v8.0.0-preview.7.23375.9/src/Mvc/Mvc.Core/src/Infrastructure/DefaultApiProblemDetailsWriter.cs#L54-L70) and in my experience this is not expected behavior for consumers of this method and will lead them to returning only partially filled `ProblemDetails` objects in API responses.

## Risks

This proposal adds new parameter to two public methods and thus changes methods' signatures.

Source code using this methods should continue to compile fine as new parameters are optional.

**Comment by mitchdenny** [comment]
I think we should add an overload for this rather than modifying the method signature.

**Comment by captainsafia** [comment]
@mariusz96 Thanks for filing this issue, @mariusz96! I cannot recall a specific reason that we omitted Extensions from the ControllerBase types so I think this is worthwhile to bring up.

I'll mark this as api-ready-for-review and bring it up during our next API review meeting. We can discuss feedback like @mitchdenny's [comment here](https://github.com/dotnet/aspnetcore/issues/50220#issuecomment-1687344699) there.

**Comment by halter73** [comment]
API Review Notes:

- We like the parity between IResults and ControllerBase both supporting extensions.
- We need to add new overloads to avoid a binary breaking change.
- The last parameter of the new overload should be non-optional.

API Approved!

```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract class ControllerBase
{
    public virtual ObjectResult Problem(
        string? detail = null,
        string? instance = null,
        int? statusCode = null,
        string? title = null,
        string? type = null);

+    public virtual ObjectResult Problem(
+        string? detail = null,
+        string? instance = null,
+        int? statusCode = null,
+        string? title = null,
+        string? type = null,
+       IDictionary<string, object?>? extensions);

    public virtual ActionResult ValidationProblem(
        string? detail = null,
        string? instance = null,
        int? statusCode = null,
        string? title = null,
        string? type = null,
        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary = null);

+    public virtual ActionResult ValidationProblem(
+        string? detail = null,
+        string? instance = null,
+        int? statusCode = null,
+        string? title = null,
+        string? type = null,
+        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary = null,
+        IDictionary<string, object?>? extensions);
}
```diff

**Comment by mariusz96** [comment]
Thanks!

Unfortunately this:

> * The last parameter of the new overload should be non-optional.

generates a compiler error: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1737.

When I make `extensions` parameter optional though, analyzers point me to this document: https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md.

Would it be a viable alternative?

**Comment by captainsafia** [comment]
@mariusz96 Thanks for pointing this out. It does seem like the code snippet and the bullet are in disagreement about the nullability of the last parameter.

I think it should be sufficient to make the last parameter option and suppress the API warning as we [do this elsewhere in the codebase](https://grep.app/search?q=RS0026&filter[repo][0]=dotnet/aspnetcore).

cc: @halter73 for API review thoughts

**Comment by captainsafia** [comment]
Moving this back to `api-ready-for-review` so that we can reassess the guidance we gave here.

**Comment by halter73** [comment]
API Review Notes:

- The previously approved API doesn't compile. Sorry!
- Let's fix it by following the linked guidance in https://github.com/dotnet/roslyn/blob/91d6bfbcc57f1b355ad0d295d6d4b5b8f85bb1d5/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md

```diff
namespace Microsoft.AspNetCore.Mvc;

public abstract class ControllerBase
{
-    public virtual ObjectResult Problem(
-        string? detail = null,
-        string? instance = null,
-        int? statusCode = null,
-        string? title = null,
-        string? type = null);

+    public virtual ObjectResult Problem(
+        string? detail,
+        string? instance,
+        int? statusCode,
+        string? title,
+        string? type);

+    public virtual ObjectResult Problem(
+        string? detail = null,
+        string? instance = null,
+        int? statusCode = null,
+        string? title = null,
+        string? type = null,
+        IDictionary<string, object?>? extensions = null);

-    public virtual ActionResult ValidationProblem(
-        string? detail = null,
-        string? instance = null,
-        int? statusCode = null,
-        string? title = null,
-        string? type = null,
-        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary = null);

+    public virtual ActionResult ValidationProblem(
+        string? detail,
+        string? instance,
+        int? statusCode,
+        string? title,
+        string? type,
+        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary);

+    public virtual ActionResult ValidationProblem(
+        string? detail = null,
+        string? instance = null,
+        int? statusCode = null,
+        string? title = null,
+        string? type = null,
+        [ActionResultObjectValue] ModelStateDictionary? modelStateDictionary = null,
+        IDictionary<string, object?>? extensions = null);
}
```
