### ISSUE TITLE
OutputCache attribute not working when not mapping controllers directly

### ISSUE THREAD

**Issue by JeremyMahieu** [dotnet/aspnetcore#50226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using a attribute for output cacheing at the method level in the controller. But this does not have any effect.
```
[HttpGet]
[OutputCache (Duration = 2, Tags = new[] { "something" })]
public IEnumerable<WeatherForecast> GetWeatherForecast()
{
    (...)
}
```

Figured out this is because I use routing and endpoints.
```
app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute("default", "{controller=test}/{action=test}/{id?}");
});
```

This might have have an impact on other attributes too. So add `app.MapControllers();` to fix.

### Expected Behavior

I expected OutputCache attributes to work and it didn't. This is a simplified example but actually outputcaching was working because there was a global policy, it was just the duration and tags that were wrong, which made this extra confusing.

### Steps To Reproduce

https://github.com/JeremyMahieu/BugOutputCaching

1) run the project
2) in swagger, trigger do the get request
3) notice the output does not have an `age` header so it's not being cached

4) In `program.cs` uncomment the `app.MapControllers();` line and run again

### Exceptions (if any)

Controller attributes should still work if using the routing and endpointmapping method.

### .NET Version

8.0.100-preview.7.23376.3

**Comment by adityamandaleeka** [comment]
cc @sebastienros

**Comment by Kahbazi** [comment]
@JeremyMahieu It's probably because of the order of the middlewares. Try adding the output cache middleware after routing and before endpoint middleware.
```C#
app.UseRouting();
app.UseOutputCache();
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute("default", "{controller=test}/{action=test}/{id?}");
});
```

**Comment by JeremyMahieu** [comment]
Yeah, probably, thanks.
