### ISSUE TITLE
Remove temporary APIs before .NET 8 ships

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#50225]
When the Razor compiler is updated, we need to remove:

 * Everything in `src\Components\Web\src\RenderMode\TemporaryRenderModeAttributes.cs`, since they will be superseded by types used with the `@rendermode` directive:
   * `RenderModeServerAttribute`
   * `RenderModeWebAssemblyAttribute`
   * `RenderModeAutoAttribute`
 * `RenderTreeBuilder.AddComponentParameter(int, string, IComponentRenderMode)` (since it will be superseded by `AddComponentRenderMode`). Can then also remove `_pendingComponentCallSiteRenderMode`.
 * Logic inside `RenderTreeBuilder.AddAttribute` that specifically checks for the attribute name `"@formname"`, since that will be superseded by `AddNamedEvent`. Can then also remove `_pendingNamedSubmitEvent`.
 * Update the project template, obviously, or it will no longer work
   * Add a `using static` so we don't need the `RenderMode.` prefix

**Comment by SteveSandersonMS** [comment]
I'm moving this to RC2 just to make sure it doesn't get forgotten. I think it actually has to be done for GA, not RC2, but I'm not sure where that shows up in the project boards. We can move it to GA when there's a correct way to do that.

**Comment by danroth27** [comment]
> Everything in src\Components\Web\src\RenderMode\TemporaryRenderModeAttributes.cs, since they will be superseded by types used with the `@rendermode` directive

@SteveSandersonMS  For many of the Razor directives (like `@page` and `@inject`) there are attribute equivalents that can be used when authoring components directly in C#. Do we not still need these attributes for that purpose?

**Comment by SteveSandersonMS** [comment]
@danroth27 People will be able to write code equivalent to what the Razor compiler produces. I'll include examples when implementing the PR for this.
