### ISSUE TITLE
Intellisense for CSS is lost when intermingling razor code in a style tag

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#5023]
When I try to write some CSS inline intermingling razor
```
            <style type="text/css">
                .zone-@i {
                }
            </style>
```

Intellisense for the CSS rules is not being shown.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
