### ISSUE TITLE
SignInManager Namespace Missing on .NET 8 Perview version 

### ISSUE THREAD

**Issue by karthik9728** [dotnet/aspnetcore#50232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using .Net 8 preview version , I installed Microsoft.AspNetCore.Identity.EntityFrameworkCore Version="7.0.10"  but when i try to use SignInManager is give error namespace not found.

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaxiShop.Domain\MaxiShop.Domain.csproj" />
  </ItemGroup>
</Project>

![Screenshot 2023-08-21 190651](https://github.com/dotnet/aspnetcore/assets/56579449/7286b5a3-d1c0-49e2-89fa-b9c8eb8f147a)

### Steps To Reproduce

1. Install .Net 8 SDK and Visual Studio Community Preview Version.
2. Create Class Library Project
3. Install  Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version="7.0.10"
4. Try to use SignInManager

### .NET Version

.Net 8 preview version

**Comment by martincostello** [comment]
You shouldn't use 7.0 NuGet packages for `Microsoft.AspNetCore.*` with ASP.NET Core 8.

You should use the version of the package that matches the .NET preview you're using, such as `8.0.0-preview.7.23375.9]` for the latest preview as ASP.NET Core 8.

**Comment by karthik9728** [comment]
> You shouldn't use 7.0 NuGet packages for `Microsoft.AspNetCore.*` with ASP.NET Core 8.
> 
> You should use the version of the package that matches the .NET preview you're using, such as `8.0.0-preview.7.23375.9]` for the latest preview as ASP.NET Core 8.

Version 8 Package is not released yet.

**Comment by martincostello** [comment]
Yes, but you're using the preview runtime, so you need to use the preview packages that match it.

**Comment by karthik9728** [comment]
> Yes, but you're using the preview runtime, so you need to use the preview packages that match it.

preview packages also not available

**Comment by martincostello** [comment]
They very much are: https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.EntityFrameworkCore/8.0.0-preview.7.23375.9

**Comment by karthik9728** [comment]
> They very much are: https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.EntityFrameworkCore/8.0.0-preview.7.23375.9

Thank you
