### ISSUE TITLE
[Blazor] Make the fallback auto render mode timeout configurable

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#50250]
In .NET 8.0 RC1, we improved the auto mode implementation to detect if WebAssembly resources are cached and use that to decide whether WebAssembly should be used for auto mode components. However, this still relies on `dotnet.js` and `blazor.boot.json` getting fetched unconditionally to compare the newest resource hash to the one cached in local storage. If, for some reason, these prerequisite resources take too long to load, we have a fallback timeout of 3 seconds to use Blazor Server.

We should make this fallback timeout configurable.

**Comment by mkArtakMSFT** [comment]
Closing as thsi is not applicable any more, as the timeout property is now removed.
