### ISSUE TITLE
Make the PageTitle-component able to be set with prerendering turned off

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#50267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to change the PageTitle on my Blazor Web App using .NET 8, but as soon as I turn off prerendering, it won't work. Apparently it's not a bug - stated by [MackinnonBuck](https://github.com/MackinnonBuck) in this bug issue #50209 - so I created this feature request.

### Describe the solution you'd like

I have an website with a cascading authentication state, and I'm storing tokens in the browsers local storage, providing my own implementation of AuthenticationStateProvider that checks for the tokens using ProtectedLocalStorage. 

Because this ProtectedLocalStorage package can't be used during prerendering due to JSInterop issue with prerender enabled, then I can't have my authentication work the way I want it. I know there's alternatives such as checking for state using the AuthenticationStateProvider using the overridden OnAfterRenderAsync, but I'd rather not each time. So I turn prerendering off completely for most of my components. But when I turn it off, the PageTitle becomes the solution namespace, and can't be changed. So I'd like it so we can set it without prerendering.

### Additional context

The previous versions of my applications in .NET 7 using Blazor Server has worked just fine setting the PageTitle without prerendering, but in this Blazor Web App with [RenderModeServer(false)] it just doesn't work.

**Comment by marinasundstrom** [comment]
@DM-98 Would this solve your problem?

```razor
<HeadOutlet @rendermode="@RenderMode.Server" />
```

Otherwise, Blazor will not update the header once the page loads.

**Comment by DM-98** [comment]
@marinasundstrom Doing that causes a big issue with styling of my site - but it did work. Also noticed when I add it, it doesn't look right with the coloring, I thought was supposed to be purple-ish like @onclick etc? 
![image](https://github.com/dotnet/aspnetcore/assets/10290906/38343934-c5fa-4c2c-9801-73784f481ca5)

**Comment by marinasundstrom** [comment]
@DM-98 Ah. OK. There are issues with this approach too. I have a mixed render mode app, and this approach makes page titles on SSR pages not being rendered.

I don't know how your styles are set up.

If it works then it works. It must be an IDE thing.

**Comment by DM-98** [comment]
My styling is broken into multiple custom Layout components, with different HeadContents in them, such as css, meta tags etc. And the App.razor has little amount of css in head that all pages should have. This is for SEO optimization. 

That's unfortunate, we'll have to rethink our approach.

**Comment by mkArtakMSFT** [comment]
The `PageTitle` issue is being tracked by https://github.com/dotnet/aspnetcore/issues/50268 already.
As for the `SectionOutlet` and `SectionContent` components in general (which includes `HeadOutlet` component as a specific case), the behavior observed here is by-design. When an interactively rendered component provides content for a specific section using `SectionContent`, the corresponding `SectionOutlet` component must be rendered within some interactive component. Otherwise, statically rendered `SectionOutlet` will not be updated.
