### ISSUE TITLE
Only use keyed services when keyed service provider is available

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#50277]
We should make sure that our keyed services implementations in the framework (SignalR, minimal APIs, MVC) all check that the target service provider supports keyed DI before resolving a keyed service from it.

**Comment by adityamandaleeka** [comment]
@benjaminpetit Can you look into this in RC2?

**Comment by BrennanConroy** [comment]
SignalR is handling this in https://github.com/dotnet/aspnetcore/pull/50248

**Comment by captainsafia** [comment]
> MVC already do in https://github.com/dotnet/aspnetcore/pull/50145, but there is no clear exception message like for SignalR

How do we do this in MVC currently? I couldn't spot where we are throwing the exception from the changes in [this PR](https://github.com/dotnet/aspnetcore/pull/50145).

In any case, maybe we stick this in 9.0 for now? @benjaminpetit What's the experience for users using a non-keyed service provider with keyed services? `NotImplementedException`?

**Comment by BrennanConroy** [comment]
Isn't it here:
https://github.com/dotnet/aspnetcore/blob/2335aa56f519790c4b4b53b955b26f29f7030d36/src/Mvc/Mvc.Core/src/ModelBinding/Binders/KeyedServicesModelBinder.cs#L25-L27

**Comment by benjaminpetit** [comment]
Yes that's how it is handled. I think it's sufficient, but maybe we should do a check at startup?

**Comment by captainsafia** [comment]
Yeah, that approach is fine. We should probably set an error in the ModelState to indicate _why_ the binding failed but that's fine to do as a follow-up.

It looks like we still need to add this check for minimal APIs. I assume it's not urgent enough for RC2?
