### ISSUE TITLE
AddAuthentication with JwtBearerScheme and IConfigureOptions doesn't work

### ISSUE THREAD

**Issue by eduardscript** [dotnet/aspnetcore#50274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The issue is somewhat peculiar. It has come to my attention that utilizing IConfigureOptions doesn't yield the desired results. However, upon switching to IConfigureNamedOptions<JwtBearerOptions>, the functionality is achieved as intended.

```cs
// This works
public class JwtOptionsSetup : IConfigureNamedOptions<JwtBearerOptions>
{
    private readonly JwtOptions _options;

    public JwtOptionsSetup(IOptions<JwtOptions> options)
    {
        _options = options.Value;
    }

    public void Configure(JwtBearerOptions options)
    {
        options.TokenValidationParameters = new()
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = _options.Issuer,
            ValidAudience = _options.Audience,
            IssuerSigningKey = _options.EncodedSecret,
        };
    }

    public void Configure(string? name, JwtBearerOptions options)
    {
        Configure(options);
    }
}

// This doesn't work
public class JwtOptionsSetup : IConfigureOptions<JwtBearerOptions>
{
    private readonly JwtOptions _options;

    public JwtOptionsSetup(IOptions<JwtOptions> options)
    {
        _options = options.Value;
    }

    public void Configure(JwtBearerOptions options)
    {
        options.TokenValidationParameters = new()
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = _options.Issuer,
            ValidAudience = _options.Audience,
            IssuerSigningKey = _options.EncodedSecret,
        };
    }
}

// Pipeline code
services.AddOptions<JwtOptions>()
            .Bind(configuration.GetRequiredSection(JwtOptions.SectionName))
            .ValidateDataAnnotations()
            .ValidateOnStart();
services.ConfigureOptions<JwtOptionsSetup>();

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
```

After reviewing the source code of the options library for a while, it appears that [this specific line](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L60C33-L60C33) is responsible for the observed behavior. In this case, the name is explicitly configured as "Bearer," causing it to deviate from the default name of string.Empty. Alternatively, using the IConfigureNamedOptions would yield the desired outcome...

Can you help me understand why this happens? It makes sense to be named?

### Expected Behavior

Use the IConfigureOptions as supposed. I think that's not a good use case to use the IConfigureNamedOptions.

### .NET Version

7.0

### Anything else?

I tried running the same code in .NET 5.0 and .NET Core 3.1 which causes the same result.

**Comment by pinkfloydx33** [comment]
The name matches the name you give the authentication scheme. In this case, `AddJwtBearer()` uses `JwtBearerDefaults.AuthenticationScheme` under the hood which is "Bearer". But suppose you had multiple JWT/token schemes with different options (authority, audience, etc), ie. `AddJwtBearer("mycustomscheme")`. How would you configure those independently without named options?
