### ISSUE TITLE
Negotiate auth leads to disconnection when posting large request to a kestrel API

### ISSUE THREAD

**Issue by dco123** [dotnet/aspnetcore#50289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When posting a large request body (> 300MB) to a kestrel based API we almost always get the error "an existing connection was forcibly closed by the remote host", but it only occurs when using negotiate auth and isn't reproducible with anonymous. I eventually found issue #6986 which pointed me to what is happening:

1. Client posts Negotiate request without credentials
2. Server responds with a 401 challenge
3. Kestrel tries to drain the request body, but as it's a lot of data this hits the 5 second timeout and it kills the connection
4. Client can't respond to the challenge because the connection has been killed

I've confirmed the workaround on that issue works, but it isn't really a suitable solution. For obvious reasons we don't want to have to spend resources on consuming the entire content of every unauthenticated request we receive, and it doesn't seem reasonable that we should have to receive the entire content of a request from the client multiple times when we're negotiating authentication.

### Expected Behavior

When responding to a request with a 401 negotiate challenge we shouldn't have to consume the entire request body, and so it shouldn't kill the connection if reading that body takes more than 5 seconds.

### .NET Version

7.0.1

**Comment by Tratcher** [comment]
This is a hard limitation of the HTTP protocol, not an implementation decision on our part (other than the 5s timeout). The client must send all the data it promised, even if the server rejects the request. The server must consume that content or drop the connection. We don't want to wait forever to consume unused content, that's a DOS vector.

Common workarounds for this include:
- Priming the connection using a GET or HEAD request for auth.
- Using Expect: 100-continue to check for rejections. The client may choose to not send the body if rejected, and start the real auth handshake on a new connection.
- Draining the request data at the app layer (with your own timeouts).

**Comment by dco123** [comment]
Thanks, this makes sense. We hit the issue after upgrading the api from .net 471 / http.sys to .net 7 / kestrel, so if it's standard behaviour then I'm not sure why we've started seeing it now (the client is setting Expect100Continue to false). Was the timeout much higher than 5 seconds in asp.net / http.sys?

**Comment by Tratcher** [comment]
Yes, IIS / Http.Sys had a different cutoff policy, but the problem was still there.
