### ISSUE TITLE
[Blazor] Disable enhanced navigation on a per-element basis

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#50290]
* Check for a `data-enhanced-navigation` attribute on the element.
* Skip using enhanced navigation if that's the case and fallback to a traditional reload.

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/50551

The new rules are:

* For forms, enhanced nav is off by default. To turn it on, put `data-enhance` on the form element, or `Enhance` if it's an `EditForm`
* For links, enhanced nav is on by default. Control it by putting `data-enhance-nav="true/false"` either on the `<a>` itself or on any ancestor element. When a link is clicked, we find its closest ancestor with a setting and use that, so you can override in either direction.
