### ISSUE TITLE
Provide APIs related to controlling the TLS handshake process

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/aspnetcore#50291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There is a non-existing standard Https communication scenario in my project, which is mainly reflected in the fact that the SSL protocol version is not 0x0301~0x0303, but 0x0101. And during the negotiation process, two server certificates are used, one for encrypting the symmetric key and one for digital signature.

### Describe the solution you'd like

Allows setting a custom SslProtocal Version, allowing custom handshake process processing.

### Additional context

II found that `SslStream` might be able to meet part of my needs, and I'm learning its usage. But it seems that it cannot be set for custom Ssl protocol version.

**Comment by Tratcher** [comment]
We do not add direct support or targeted extensibility for non-standard protocols. We do offer general extensibility where you can replace larger components.

Kestrel will let you use custom connection middleware. To get that level of customization you'd likely need to replace SslStream and the HttpsConnectionMiddleware.
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs

**Comment by MiyamuraMiyako** [comment]
@Tratcher Thanks for the reply, I will try this method.

**Comment by MiyamuraMiyako** [comment]
@Tratcher `HttpsConnectionMiddleware` is internal class, it doesn't seem to be directly replaceable. Do I have to compile and replace the whole kestrel assembly myself?
