### ISSUE TITLE
Obtaining aspnet parameter binding metadata

### ISSUE THREAD

**Issue by mariusz96** [dotnet/aspnetcore#50300]
Hi,

I'm developing a [library](https://github.com/mariusz96/uri-generation) and I have a question.

A library has a service that extracts arguments from `controller => controller.method(args)` expression and calls `LinkGenerator` to generate URLs.

However, at the moment, it's fairly limited and I was looking into adding features to it.

Assuming a (non-recursive) model like this:
```cs
[ApiController]
[Route("[controller]")]
public class CqrsController : ControllerBase
{
    [HttpGet("{modelName}")]
    public IActionResult Get(
        [FromRoute] string? modelName,
        [FromQuery(Name = "q")] CqrsQuery query)
    {
        return Ok(new { modelName, query });
    }
}

public class CqrsQuery
{
    [FromQuery(Name = "sort_order")]
    public string? SortOrder { get; set; }
    public IEnumerable<string>? Filters { get; set; }
}
```
and that i already have:
- action's `MethodInfo`
- parameter's `ParameterInfo`
- `object` with original argument's value

What would be a good way of obtaining metadata about the given parameter and its' model? I mainly mean for things like: was it renamed or prefixed so I can calculate correct route values' keys and can it be bound at all from query or route.

Could you point me to some service or HttpContext's feature that would be appropriate to use here?

**Comment by javiercn** [comment]
@mariusz96 thanks for contacting us.

`ModelMetadataProvider` is the source for metadata for binding and validation. You might also achieve what you want with the I `IActionDescriptorCollectionProvider`.

**Comment by mariusz96** [comment]
> @mariusz96 thanks for contacting us.
> 
> `ModelMetadataProvider` is the source for metadata for binding and validation. You might also achieve what you want with the I `IActionDescriptorCollectionProvider`.

Many thanks! I was actually exploring `ModelMetadataProvider` earlier this week in the debugger.

One last question: is there any particular reason that `DefaultModelMetadataProvider` is [registered only as its' interface](https://github.com/dotnet/aspnetcore/blob/v8.0.0-preview.7.23375.9/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L208)? Should I perform type checking everytime I want to inject it:
```csharp
sp =>
{
    var provider = sp.GetService<ModelMetadataProvider>();
    if (provider is not null) return provider;

    provider = sp.GetService<IModelMetadataProvider>() as ModelMetadataProvider;
    if (provider is not null) return provider;

    return null;
}
```
?
