### ISSUE TITLE
RFC8998: ShangMi (SM) Cipher Suites for TLS 1.3

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/aspnetcore#50304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Hope to aspnetcore add new cipher suites in rfc8998 spec.

**Comment by Tratcher** [comment]
https://www.rfc-editor.org/rfc/rfc8998

Cipher Suites are implemented by Windows or OpenSsl, not at the AspNetCore layer. 

@wfurt do you know about these specific ciphers?

**Comment by wfurt** [comment]
I don't know. By brief look at the RFC there are other extensions that needs to be added to ClientHello. If that means more work in OpenSSL API than just the CipherSuite than it it probably not working. 
On the other hand, SslStream does not set anything particular unless explicitly done by the caller. So if the cipher suites are supported by the installed libraries and enabled in /etc/ssl/openssl.conf it should just work AFAIK.

There seems to be at least some support in OpenSSL https://www.openssl.org/docs/man1.1.1/man7/SM2.html
