### ISSUE TITLE
Issue rendering IHtmlContent in Razor component

### ISSUE THREAD

**Issue by Fido789** [dotnet/aspnetcore#50334]
I am trying to render Razor components to the string following example here https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0

Unfortunately it seems like expressions evaluated to IHtmlContent are not rendered correctly and IHtmlContent.WriteTo is not called. Is IHtmlContent not supported for this scenario?

**Comment by javiercn** [comment]
@Fido789 thanks for contacting us.

IHtmlContent is not supported in `.razor` files. It is only supported in .cshtml (Razor pages and MVC). For `.razor` you should use `MarkupString` but beware that you are responsible for correctly encoding any HTML that you produce that way.

**Comment by Fido789** [comment]
@javiercn I see, thank you for the explanation.
