### ISSUE TITLE
Change PropertyNameCaseInsensitive's default value to false.

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#50333]
The last discussion I can see regarding this is https://github.com/dotnet/runtime/issues/29869.

There, it's mentioned that the reason for it being set to `true` is to handle cases of serializations done by `PostAsJsonAsync` method, but that method seems to have an overload accepting a `JsonSerializerOptions` object, so I'm not sure *why* the default is `true`?

I had the notion that all defaults in ASP.NET Core are aimed towards performance gains, unless there's a strong reason not to. Could someone point to a strong reason for it staying like that? 

If we do decide to make the default `false`, it will be considered a breaking change for people who relied on its behavior.

**Comment by khellang** [comment]
Isn't it kinda weird to serialize using camelCase (web default), but not accepting camelCase when deserializing? As most idiomatic C# code uses PascalCase properties, you can no longer round-trip a JSON payload using the default settings.

**Comment by kikaragyozov** [comment]
> Isn't it kinda weird to serialize using camelCase (web default), but not accepting camelCase when deserializing? As most idiomatic C# code uses PascalCase properties, you can no longer round-trip a JSON payload using the default settings.
> 
> Performance is nice, but defaults which probably 90%+ of applications rely on shouldn't be broken because of it. If you really care that much about the gained performance at the cost of developer experience and development time, it's totally fine to turn it off 😄

Setting `PropertyNameCaseInsensitive` to `false` does not disable deserialization of objects when they come Camel Cased, if you've set your PropertyNamingPolicy to it. I'm not sure I follow?

**Comment by khellang** [comment]
> Setting `PropertyNameCaseInsensitive` to `false` does not disable deserialization of objects when they come Camel Cased, if you've set your `PropertyNamingPolicy` to it. I'm not sure I follow?

Yes it does. I'm just not sure we're on the same wavelength when it comes to what camelCase and PascalCase means. Let's spell it out. The documentation for `PropertyNameCaseInsensitive` reads

> Gets or sets a value that indicates whether a property's name uses a case-insensitive comparison during deserialization.

If you have the following C# class

```csharp
record Person(string GivenName, string FamilyName);
```

And serialize it using the default settings, you'll end up with the following example JSON payload:

```json
{
  "givenName". "Kristian",
  "familyName", "Hellang"
}
```

As you can see, the property names have been transformed from PascalCase (`GivenName`, `FamilyName`) to camelCase (`givenName`, `familyName`).

If you change `PropertyNameCaseInsensitive` to `false` by default and you try to send this payload back to the server, it would no longer be able to deserialize into the `User` record.

**Comment by kikaragyozov** [comment]
> > Setting `PropertyNameCaseInsensitive` to `false` does not disable deserialization of objects when they come Camel Cased, if you've set your `PropertyNamingPolicy` to it. I'm not sure I follow?
> 
> Yes it does. I'm just not sure we're on the same wavelength when it comes to what camelCase and PascalCase means. Let's spell it out. The documentation for `PropertyNameCaseInsensitive` reads
> 
> > Gets or sets a value that indicates whether a property's name uses a case-insensitive comparison during deserialization.
> 
> If you have the following C# class
> 
> ```cs
> record Person(string GivenName, string FamilyName);
> ```
> 
> And serialize it using the default settings, you'll end up with the following example JSON payload:
> 
> ```json
> {
>   "givenName": "Kristian",
>   "familyName": "Hellang"
> }
> ```
> 
> As you can see, the property names have been transformed from PascalCase (`GivenName`, `FamilyName`) to camelCase (`givenName`, `familyName`).
> 
> If you change `PropertyNameCaseInsensitive` to `false` by default and you try to send this payload back to the server, it would no longer be able to deserialize into the `Person` record.

I've tested this and it appears to work for me. I'm using ASP.NET Core's JsonSerializerOptions, without anything fancy going on?

**Comment by khellang** [comment]
> I've tested this and it appears to work for me. I'm using ASP.NET Core's JsonSerializerOptions, without anything fancy going on?

I'd love to see the code. That's literally the point of the setting 😅

**Comment by kikaragyozov** [comment]
> > I've tested this and it appears to work for me. I'm using ASP.NET Core's JsonSerializerOptions, without anything fancy going on?
> 
> I'd love to see the code. That's literally the point of the setting 😅

Here you go: https://github.com/kikaragyozov/ExampleDeserialization

Just do a POST request to /test with
```
{
    "someProperty": "hello"
}
```

And you'll see it successfully getting deserialized.

**Comment by khellang** [comment]
> Camel Case is honored (as it should be)

But why should it be, though? You've explicitly said that property names is case sensitive. `someProperty` is not the same as `SomeProperty`.

**Comment by kikaragyozov** [comment]
> > Camel Case is honored (as it should be)
> 
> But why should it be, though? You've explicitly said that property names is case sensitive. `someProperty` is not the same as `SomeProperty`.

You're asking the wrong guy. Someone designed it this way, and I'm sure with good reason behind it. For me it makes perfect sense.

**Comment by captainsafia** [comment]
Catching up on this discussion as part of triage.

Considering it's trivial to change the behavior by customizing `JsonOptions` to your preference and the fact that large amounts of the framework take advantage of the `PropertyCaseInsensitive = true` setting, I don't think this is something we'd change for a small perf win.

> And you'll see it successfully getting deserialized.

The reason you are seeing this behavior is because JsonOptions is configured to use the `JsonSerializerOptions.Web` defaults which assumes that property names are `camelCase` by default. If you try other request formats:

```
POST http://localhost:5253/test
Content-Type: application/json

{ "someProperty" : "Ttest" }

###

POST http://localhost:5253/test
Content-Type: application/json

{ "SOMEPROPERTY" : "Ttest" }

###

POST http://localhost:5253/test
Content-Type: application/json

{ "SomeProperty" : "Ttest" }

###
```

You'll observe that they fail.

I'll close this issue as not planned for now considering there hasn't been major interest in this change and it would be a considerable break.
