### ISSUE TITLE
Request Delegate Generator generates incorrect InterceptsLocation attribute when `Map...` call is on a newline relative to route builder

### ISSUE THREAD

**Issue by hwoodiwiss** [dotnet/aspnetcore#50348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a `.Map...()` call is on the next line after the `IEndpointRouteBuilder` that I'm trying to add the route to, the generated `[InterceptsLocation(...)]` tries to point to the line and character position as if the newline wasn't there.

For example:

The attribute generated in `GeneratedRouteBuilderExtensions.g.cs`
```csharp
[InterceptsLocation(@"<Removed for privacy>\HwoodiwissHelper\Features\Surprise\SurpriseEndpoints.cs", 9, 15)]
```

Is generated for this endpoint mapping
(This example has 8 spaces of indentation, and starts on line 9
```csharp
        group
            .MapGet("/next", (IConfiguration configuration)
```

Which puts the interception point 2 characters past the end of line on the line with the `group`.
I've tested this with a `GroupEndpointBuilder` and an `IEndpointBuilder`

### Expected Behavior

I would expect the attribute to generate as
```csharp
[InterceptsLocation(@"<Removed for privacy>\HwoodiwissHelper\Features\Surprise\SurpriseEndpoints.cs", 10, 13)]
```

### Steps To Reproduce

The behaviour can be seen here: https://github.com/hwoodiwiss/HwoodiwissHelper/blob/asp-50348-repro/src/HwoodiwissHelper/Features/Surprise/SurpriseEndpoints.cs#L9

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

ASP.NET Core Version: 8.0.0-preview.7.23375.9+8df730db29a670c853e3cff67fe70eb1cf6e8af7
IDE:  JetBrains Rider 2023.2.1 Build #RD-232.9559.61

This can be worked around by disabling RequestDelegateGenerators or by not having the `.Map...` calls on the following line.

**Comment by BrennanConroy** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/50164, will be fixed in RC2

**Comment by hwoodiwiss** [comment]
Ahhh, sorry, I had a search but couldn't find it, thanks for linking that.
