### ISSUE TITLE
CSS isolation does not work - wrong isolation set

### ISSUE THREAD

**Issue by jaoord** [dotnet/aspnetcore#50356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

given the following cshtml

`
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2 advanced-search-form">
            <h1>Advanced flight search</h1>
            <form action="/advancedsearch">
                
                <div class="row search-group">
                    <div class="col-12">
                        <h5>Airport - enter ICAO code or name</h5>
                    </div>
                    <div class="col-6">
                        <label asp-for="From">From</label>
                        <input type="text" asp-for="From" class="advanced-search-form__input" />
                    </div>

                    <div class="col-6">
                        <label asp-for="To">To</label>
                        <input type="text" asp-for="To" class="advanced-search-form__input" />
                    </div>
                </div>
            
                <div class="row search-group">
                    <div class="col-12">
                        <h5>Flight time in minutes</h5>
                    </div>
                    <div class="col-6">
                        <label asp-for="MinFlightTime">Minimum</label>
                        <input type="text" asp-for="MinFlightTime" class="advanced-search-form__input" />
                    </div>

                    <div class="col-6">
                        <label asp-for="MaxFlightTime">Maximum</label>
                        <input type="text" asp-for="MaxFlightTime" class="advanced-search-form__input" />
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>`

and this css in the cshtml.css file:

`
.advanced-search-form {
    margin-bottom: 48px;
}

.advanced-search-form h5 {
    font-size: 16px;
}
.advanced-search-form label {
    font-family: Inter,sans-serif;
    font-weight: 500;
    font-size: 14px;
    line-height: 16px;
    color: #FFF;
    display: block;
}
.advanced-search-form input {
    border: 0;
    font-size: 18px;
    line-height: 18px;
    width: 100%;
    padding: 16px 24px;
    border-top-left-radius: 3px;
    border-bottom-left-radius: 3px;
}
`

the following html is generaged:

`<div b-sq09e12f42 class="container">
    <div b-sq09e12f42 class="row">
        <div b-sq09e12f42 class="col-12 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2 advanced-search-form">
            <h1 b-sq09e12f42>Advanced flight search</h1>
            <form action="[/advancedsearch](view-source:https://localhost:7296/advancedsearch)">
                
                <div b-sq09e12f42 class="row search-group">
                    <div b-sq09e12f42 class="col-12">
                        <h5 b-sq09e12f42>Airport - enter ICAO code or name</h5>
                    </div>
                    <div b-sq09e12f42 class="col-6">
                        <label for="From">From</label>
                        <input type="text" class="advanced-search-form__input" id="From" name="From" value="" />
                    </div>

                    <div b-sq09e12f42 class="col-6">
                        <label for="To">To</label>
                        <input type="text" class="advanced-search-form__input" id="To" name="To" value="" />
                    </div>
                </div>
            
                <div b-sq09e12f42 class="row search-group">
                    <div b-sq09e12f42 class="col-12">
                        <h5 b-sq09e12f42>Flight time in minutes</h5>
                    </div>
                    <div b-sq09e12f42 class="col-6">
                        <label for="MinFlightTime">Minimum</label>
                        <input type="text" class="advanced-search-form__input" data-val="true" data-val-required="The MinFlightTime field is required." id="MinFlightTime" name="MinFlightTime" value="0" />
                    </div>

                    <div b-sq09e12f42 class="col-6">
                        <label for="MaxFlightTime">Maximum</label>
                        <input type="text" class="advanced-search-form__input" data-val="true" data-val-required="The MaxFlightTime field is required." id="MaxFlightTime" name="MaxFlightTime" value="0" />
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>`

and the following css is generated:

`.advanced-search-form[b-sq09e12f42] {
    margin-bottom: 48px;
}

.advanced-search-form h5[b-sq09e12f42] {
    font-size: 16px;
}

.advanced-search-form label[b-sq09e12f42] {
    font-family: Inter,sans-serif;
    font-weight: 500;
    font-size: 14px;
    line-height: 16px;
    color: #FFF;
    display: block !important;
}
.advanced-search-form input[b-sq09e12f42] {
    border: 0;
    font-size: 18px;
    line-height: 18px;
    width: 100%;
    padding: 16px 24px;
    border-top-left-radius: 3px;
    border-bottom-left-radius: 3px;
}
`

### Expected Behavior

Instead of generating `.advanced-search-form label[b-sq09e12f42] ` it should generate .advanced-search-form[b-sq09e12f42]  label

### Steps To Reproduce

See above for code

### .NET Version

6

**Comment by a44281071** [comment]
WPF hybrid css isolation is not work.

**Comment by gfoidl** [comment]
@jaoord can you please provide a standalone repro for this problem so it's easiert to investigate and to have a common baseline of the problem?

**Comment by jaoord** [comment]
Hi, see repo here: https://github.com/jaoord/demo-issue-50356

**Comment by jaoord** [comment]
seems to only do this to form elements that contain `asp-` attributes, normal form elements seem to work fine (but I don't use those in my project)

**Comment by javiercn** [comment]
@jaoord thanks for contacting us.

CSS isolation only applies to HTML elements, not tag helpers as otherwise, it would break the isolation of those tag helpers. There is an issue that we recommend you upvote if you want to see support for allowing tag helpers (and components) to optionally accept a parent scope.

https://github.com/dotnet/razor/issues/7606
