### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Facebook uses soon-to-be-obsolete Facebook Graph version v11 in .NET 6

### ISSUE THREAD

**Issue by oskrabanek** [dotnet/aspnetcore#50366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [`FacebookDefaults`](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Facebook/src/FacebookDefaults.cs) class uses obsolete v11 Facebook Graph API, which is [planned to be deprecated on the 14.9.2023](https://developers.facebook.com/docs/graph-api/changelog/#available-graph-api-versions). Although the version has been [updated to v14](https://github.com/dotnet/aspnetcore/pull/43982/files#diff-4783d28317aaa3c8ab5bb24d45d47cde3931454c4b1a6ac4efacf2a857418d69), this has been release for .NET8 only which means this will start to fail after 14.9.2023 even though the .NET6 is LTS version.

### Expected Behavior

.NET6 and .NET7 should have updated version of Facebook Graph.

### .NET Version

6

**Comment by martincostello** [comment]
I can't speak to as whether this meets the bar for servicing in .NET 6 and .NET 7, but the Facebook provider can be easily configured in code to use a newer version like in the code snippet below:

```csharp
builder.AddFacebook(options =>
{
    options.AuthorizationEndpoint = "https://www.facebook.com/v14.0/dialog/oauth";
    options.TokenEndpoint = "https://graph.facebook.com/v14.0/oauth/access_token";
    options.UserInformationEndpoint = "https://graph.facebook.com/v14.0/me";
});
```

The diff for #43982 doesn't suggest that any other code changes need to be made that aren't user-configurable.
