### ISSUE TITLE
Blazor localization (translation)  does not work with multiple languages

### ISSUE THREAD

**Issue by sevinul** [dotnet/aspnetcore#50361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is the standard blazor project template expanded by a class library containing four resource files for translation in a localization folder. The file program.cs contains code to add localization.

The index.razor page outputs translated strings in the four languages. The first three language strings are not translated, but the fourth language string shows the correct translation.

![Screenshot 2023-08-27 104015](https://github.com/dotnet/aspnetcore/assets/17502142/7c917a69-26f4-4f20-b08b-2c5400e67191)

The same setup runs fine in another Asp.Net MVC project.

### Expected Behavior

All four languages should translate correctly and output:
- Beispiel Deutsch
- Example English
- Exemple Français
- Örnek Türkçe (this is the only correct one)

### Steps To Reproduce

Rebuild and run the github template project: [https://github.com/sevinul/BlazorApp1](https://github.com/sevinul/BlazorApp1)

### Exceptions (if any)

No exceptions

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

Microsoft Visual Studio Version 17.8.0 Preview 1.0
Windows 11 Version 22H2 (Build 22621.2215)

**Comment by javiercn** [comment]
@ScarletKuro answer is correct here.

I don't believe switching languages without a page reload is supported in Webassembly.

**Comment by ScarletKuro** [comment]
> I don't believe switching languages without a page reload is supported in Webassembly.

It's not supported out of the box, unless you manually provide a list of cultures to load at startup using `INTERNAL.loadSatelliteAssemblies`. In such a case, there's no need to refresh the page when you switch the current culture.

**Comment by ScarletKuro** [comment]
> @ScarletKuro and @javiercn, thank you for your responses. So is it at all possible to dynamically switch languages in .Net 8 Webassembly? Am I missing a part in my small test case?

As I said earlier, native support for this isn't available in Blazor WASM.
However, in theory, you can attempt the following approach:

```C#
private partial class WebAssemblyCultureProviderInterop
{
	[JSImport("INTERNAL.loadSatelliteAssemblies")]
	public static partial Task LoadSatelliteAssemblies(string[] culturesToLoad);
}
```
Then, you should invoke LoadSatelliteAssemblies in the Program.cs file of your WebAssembly before the host starts:
```C#
await WebAssemblyCultureProviderInterop.LoadSatelliteAssemblies(new string[] {"de", "en", "fr", "tr"});
```
BUT this API was fully reworked in .NET8 compared to its version in .NET6/.NET7. As of now, I haven't personally tested this approach, so I cannot confirm its working in NET8

**Comment by sevinul** [comment]
Thanks a lot @ScarletKuro. I tested your code with my test case using .Net8.0.100-preview.7. Unfortunately it doesn't work.

**Comment by ScarletKuro** [comment]
@sevinul 
I managed to make it work, but only when the translations are inside the WASM application, but not in the separate assembly
![works](https://github.com/dotnet/aspnetcore/assets/19953225/6ea63f02-f7bb-453b-b548-b4ee7a25cecf)

I can't really answer why it doesn't work when resources are in different assembly.
Maybe it's how the `loadSatelliteAssemblies` works inside, or we are missing something like
```C#
[assembly: ResourceLocation("xxx")]
[assembly: RootNamespace("xxx")]
```
on the assembly, I sadly don't have much time to investigate this.

The source code if you need them: 
[BlazorApp1-master.zip](https://github.com/dotnet/aspnetcore/files/12479751/BlazorApp1-master.zip)

I used a preview version of my own lib where I added support for .net8, but I used pretty much the same trick that I posted before.

**Comment by sevinul** [comment]
@ScarletKuro, this is a great solution. Thank you for your work. Can you also send me this preview version of your library?

**Comment by ScarletKuro** [comment]
> @ScarletKuro, this is a great solution. Thank you for your work. Can you also send me this preview version of your library?

https://github.com/ScarletKuro/Blazor.WebAssembly.DynamicCulture
https://www.nuget.org/packages/Blazor.WebAssembly.DynamicCulture/3.0.0-preview#readme-body-tab

**Comment by sevinul** [comment]
Many thanks @ScarletKuro :)
