### ISSUE TITLE
Needed guidance for a memory usage 

### ISSUE THREAD

**Issue by k0st1x** [dotnet/aspnetcore#50370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Memory is always grow-up on every post request.
I've send json about 2.5Mb and server memory always grow.
On the Debian OS.

### Expected Behavior

Memory should stay on the base line between restful requsts.

### Steps To Reproduce

aspnetcore program.cs:
```cs
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapPost("/postTest", ([FromBody] JsonRec model, [FromServices]ILogger<Program> logger) =>
{
    var content = model.Data;
    double workingSetMb = Process.GetCurrentProcess().WorkingSet64 / 1024.0 / 1024.0;
    logger.LogInformation("WorkingSet: {workingSetMb} (Mb)", workingSetMb);
    return workingSetMb + " Mb";
});
app.Run();

class JsonRec
{
    public byte[] Data { get; set; } = Array.Empty<byte>();
}
```

then continously send post json file like
```json
{ "data": "MTIz...." }
```

and the server logs writes memory usage
```
WorkingSet: 86.86328125 (Mb)
WorkingSet: 107.68359375 (Mb)
WorkingSet: 116.9453125 (Mb)
WorkingSet: 127.16015625 (Mb)
WorkingSet: 135.0078125 (Mb)
WorkingSet: 136.8125 (Mb)
WorkingSet: 139.01953125 (Mb)
WorkingSet: 140.8203125 (Mb)
WorkingSet: 143.234375 (Mb)
WorkingSet: 152.57421875 (Mb)
WorkingSet: 162.04296875 (Mb)
WorkingSet: 168.1484375 (Mb)
WorkingSet: 173.2109375 (Mb)
WorkingSet: 175.34765625 (Mb)
WorkingSet: 177.41015625 (Mb)
WorkingSet: 183.96875 (Mb)
WorkingSet: 194.6484375 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.1953125 (Mb)
WorkingSet: 196.3828125 (Mb)
WorkingSet: 196.640625 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 196.453125 (Mb)
WorkingSet: 199.52734375 (Mb)
WorkingSet: 199.52734375 (Mb)
WorkingSet: 201.58984375 (Mb)
WorkingSet: 201.33984375 (Mb)
WorkingSet: 205.23046875 (Mb)
WorkingSet: 205.23046875 (Mb)
WorkingSet: 205.23046875 (Mb)
WorkingSet: 209.02734375 (Mb)
WorkingSet: 209.02734375 (Mb)
WorkingSet: 210.83203125 (Mb)
WorkingSet: 212.6328125 (Mb)
WorkingSet: 215.609375 (Mb)
```

As I see on my Debian machine,
The memory is constantly growing and never decreasing.

Can anyone guide me, how to keep memory clean? :)

### .NET Version

7.0.203

**Comment by amcasey** [comment]
I decided to repro this as practice.  The memory usage that's growing request-over-request isn't too surprising:

![image](https://github.com/dotnet/aspnetcore/assets/10508071/cdf6b8bc-6a34-4389-affa-2f39da1a6036)

Similarly, the large object heap is mostly full of byte arrays created for JSON deserialization

![image](https://github.com/dotnet/aspnetcore/assets/10508071/e4f4acf8-37e7-40ae-98e4-98ee47e13535)

Some of the arrays are coming out of a pool, but it looks like others are copied into clean arrays that can be handed back from APIs.  I would guess @Tratcher is correct and it'll hit a steady state at some point, once the GC decides there's too much memory pressure.

**Comment by k0st1x** [comment]
@Tratcher 
>  It looks like the growth is slowing as time goes on?

![image](https://github.com/dotnet/aspnetcore/assets/1209649/dea75dc8-84ee-4907-8e97-c5ae0ffa78df)
Starting with 19th request, the growing slowly, but constantly growing.

> Does it ever reach 1gb?

Why 1Gb? :)

> How many cores does the machine have?

8 cores


> Are you using server (default) or client GC?

server. the default for web sdk.

**Comment by Tratcher** [comment]
A real leak would go until it consumed all machine memory, and you'd need to run 1000+ requests to be sure either way. That leveling out at 200mb looks very normal. Server GC uses more memory per core, switching to client GC would probably level out sooner, but would be a little slower under load.

**Comment by k0st1x** [comment]
@Tratcher thx for explanation. there is not real mem leak and memory stopped the growth.
