### ISSUE TITLE
Debug in Blazor United App

### ISSUE THREAD

**Issue by Kamys85** [dotnet/aspnetcore#50383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is it possible somehow to debug webassembly code in Blazor United App (for example: [https://github.com/dotnet/aspnetcore/tree/danroth27/blazor-united-end/src/Components/Samples/BestForYouRecipes](url))? For asp.net core hosted it is simple: we can set breake points in visual studio and run app in debug mode. Mayby we should edit some config to allow that?

### Describe the solution you'd like

The information that when will be issue resolved or/and possible workaround.

**Comment by mkArtakMSFT** [comment]
This should work. Can you please be more specific about how this doesn't work for you?
Are you setting a breakpoint and it's not being hit? Is the component where the breakpoint is located being rendered in client or server mode?

**Comment by Kamys85** [comment]
Thank you for the aswer. You are right: the debug should work. But I need some modyfication to source project `[BestForYouRecipes]`. 
First in `launchSettings.json`:
`{
(...)
 "https": {
(...)
   "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
(...)
}`
Then in `Program.Server.cs`:
`
(...)
if (app.Environment.IsDevelopment())
{
   app.UseWebAssemblyDebugging();
}
(...)
`

**Comment by javiercn** [comment]
@Kamys85 we believe this works in the template projects, we think this is an issue just on our projects that are not setup for it.

If you find it doesn't work in the template, please let us know.
