### ISSUE TITLE
Custom unhandled exception logging

### ISSUE THREAD

**Issue by ejball** [dotnet/aspnetcore#50385]
## Background and Motivation

The [exception middleware](https://github.com/dotnet/dotnet/tree/main/src/aspnetcore/src/Middleware/Diagnostics/src/ExceptionHandler) logs an error with a [fixed message](https://github.com/dotnet/dotnet/blob/3cc0ca3031ab1253fd14cbd0f95002b98eae7ac8/src/aspnetcore/src/Middleware/Diagnostics/src/DiagnosticsLoggerExtensions.cs#L11-L12): `An unhandled exception has occurred while executing the request.`

I'd like the message to be more useful when scanning through a list of log messages, e.g.: `Unhandled MyNamespace.SomeException: The exception message.`

If options could be used to customize the behavior, the default behavior could remain the same.

## Proposed API

```csharp
namespace Microsoft.AspNetCore.Builder;

public class ExceptionHandlerOptions
{
    // ...

    /// <summary>
    /// Called to report the exception. If this is not explicitly provided, a default message
    /// is written to the error log.
    /// </summary>
    public Action<ExceptionHandlerReportContext>? ReportException { get; set; }
}

public sealed class ExceptionHandlerReportContext
{
    public ILogger Logger { get; }
    
    public HttpContext HttpContext { get; }

    public Exception Exception { get; }

    // internal constructor
}
```

## Usage Examples

```csharp
app.UseExceptionHandler(
    new ExceptionHandlerOptions
    {
        ReportException = context => 
            context.Logger.LogError(
                context.Exception, 
                "Unhandled {0}: {1}", 
                context.Exception.GetType().FullName, 
                context.Exception.Message);
    });
```

**Comment by BrennanConroy** [comment]
The exception is passed to the logger so it already includes the exception information. Your logger might not be displaying the exception so you might want to look into that.

Example output when I throw from an endpoint with the console logger:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: error from endpoint
         at NameSpace.Startup.<Configure>b__2_1(HttpContext context) in Startup.cs:line 52
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger) in EndpointMiddleware.cs:line 95
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in AuthorizationMiddleware.cs:line 149
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) in DeveloperExceptionPageMiddlewareImpl.cs:line 109
```

**Comment by ejball** [comment]
Thanks! Our logger includes the exception information, but lists of log messages (e.g. in Graylog) often just show the message field, which is just `An unhandled exception has occurred while executing the request.` for any exception. It would be nice to be able to distinguish different exceptions by message when looking at a list of them.

**Comment by mkArtakMSFT** [comment]
As per @BrennanConroy 's response, the exception information is being passed to the logger. If your current logger doesn't extract the necessary information from it, then we recommend you consider changing it to one that does (perhaps implementing your own).
