### ISSUE TITLE
it is possible to use the [Authorize] attribute in Blazor controllers

### ISSUE THREAD

**Issue by sivakumars3442** [dotnet/aspnetcore#50392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are trying to authorize the controller response in the **Blazor server** application by using the **[Authorize]** attribute in the Controller based on the Role value.

Also, we have used the **JwtBearerDefaults.AuthenticationScheme** for authentication in the program.cs file.

**Program.cs**

>builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => {
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = "https://localhost:7136",
        ValidAudience = "https://localhost:7136",
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("ACDt1vR3lXToPQ1g3MyN"))
    };
});

**HomeController.cs**

> namespace Blazor_Server.Controllers
{
       [Route("api/[controller]")]
       public class HomeController : Controller
       {
           [HttpGet("GetData")]
           [Authorize]
           public IActionResult GetData()
           {
             string authorizationHeader = HttpContext.Request.Headers["Authorization"];
             // Your logic to fetch data
             return Ok();
           }
       }
}

To authorize the controller response based on the user role, we have passed the generated user token in the HttpClient instance.

**Index.razor**

>private async Task CallApi()
    {
        var authState = await authenticationStateTask;
        var user = authState.User;
        //Generate user token based on the user authenticated state.
        if (user.Identity.IsAuthenticated)
        {
            Token = GenerateToken(user);
            try
            {
                HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
                responseMessage = await HttpClient.GetStringAsync("https://localhost:7136/api/Home/GetData");
            }
            catch (Exception ex)
            {
                responseMessage = "Error: " + ex.Message;
            }
        }
    }
    private string GenerateToken(ClaimsPrincipal user)
    {
        //Assign the security key value
        var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("ACDt1vR3lXToPQ1g3MyN"));
        var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);
        //Assign the user role value of authenticate server response
        var roles = user.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
        roles = new string[] { "Admin" };
        var claims = new[]
        {
                new Claim(ClaimTypes.NameIdentifier,user.Identity.Name),
                new Claim(ClaimTypes.Role,string.Join(",", roles))
        };
        var token = new JwtSecurityToken("https://localhost:7136",
        "https://localhost:7136",
        claims,
        expires: DateTime.Now.AddMinutes(15),
        signingCredentials: credentials);
        return new JwtSecurityTokenHandler().WriteToken(token);
    }

### Expected Behavior

Based on the user role, the Blazor server controller will authorize the response context and return the expected response.

### Steps To Reproduce

Please find the issue replicated GitHub sample from the below link.

https://github.com/sivakumars3442/API-Authorization 

Run the sample and click the **Call API** button to replicate the issue.

**Comment by javiercn** [comment]
@sivakumars3442 thanks for contacting us.

All the code in your case is running on the same server. There is no point on using HttpClient to talk to a controller, that logic can live directly inside the Razor component protected by an AuthorizeView.

If you have access to the token it will work. If you are using something like cookies, it won't. Keep in mind that the HttpClient instance is running on the server, not on the client, and does not have access to the cookies themselves, as they are in the browser.
