### ISSUE TITLE
Dockerise ASP.NET Core app with Alpine image

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#50399]
I originally asked on [SO](https://stackoverflow.com/q/77000895/9971404) without resolution. I assume this is not working as intended.

---

I want my dockerised ASP.NET Core 7 app based on [Alpine](https://hub.docker.com/_/alpine) (not [ASP.NET Core Runtime](https://hub.docker.com/_/microsoft-dotnet-aspnet)).

`MyApp.csproj` contains:
```xml
<PublishSingleFile>true</PublishSingleFile>
<RuntimeIdentifier>linux-musl-x64</RuntimeIdentifier>
<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>  <!-- tried with and without this -->
```

`Dockerfile` contains:
```docker
FROM alpine
```

But when I start a container, I get:
```
Error relocating /dist/MyApp: __cxa_pure_virtual: symbol not found
Error relocating /dist/MyApp: __cxa_pure_virtual: symbol not found
Error relocating /dist/MyApp: __cxa_pure_virtual: symbol not found
Error relocating /dist/MyApp: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
Error relocating /dist/MyApp: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
Error relocating /dist/MyApp: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
```

It works with the normal image (i.e. `FROM mcr.microsoft.com/dotnet/aspnet`).

The [docs](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview) imply that with the correct RID (`linux-musl-x64`), this should work. But obviously the generated binary is missing native dependencies.

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

This is more likely a question for the dotnet/docker repository since they centrally manage all images.

@richlander thoughts?

**Comment by javiercn** [comment]
This issue was moved to dotnet/dotnet-docker#4850
