### ISSUE TITLE
FromQueryAttribute with Name does not work when added to property of an object with AsParametersAttribute 

### ISSUE THREAD

**Issue by esskar** [dotnet/aspnetcore#50408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an endpoint defined as

```csharp
public sealed record SearchRequest([property: FromQuery(Name = "q")] string? Query = null);

app.MapGet("/search", ([AsParameters] SearchRequest request) => new { query = request.Query });

app.MapGet("/search2", ([FromQuery(Name = "q")] string? query) => new { query });
```

the SearchRequest.Query is not filled as expected
 
Here are my requests and the responses
calling /search?q=foo => responses with 200 OK, content: null
calling /search?query=foo  => responses with 200 OK, content: "foo"
calling /search2?q=foo  => responses with 200 OK, content: "foo"

### Expected Behavior

I expected the first request

calling /search?q=foo 

to respond with 200 OK and content: "foo"

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/search", ([AsParameters] SearchRequest request) => new { query = request.Query });
app.MapGet("/search2", ([FromQuery(Name = "q")] string? query) => new { query });

app.Run();

public sealed record SearchRequest([property: FromQuery(Name = "q")] string? Query = null);
```

### .NET Version

8.0.100-preview.7.23376.3

**Comment by captainsafia** [comment]
@esskar Thanks for reporting this issue!

I believe this is related to the logic in `PropertyAsParameterInfo` for mapping `PropertyInfo` and `ParameterInfo` and derving the name. This should be straightforward to address for RC2. 🤞🏽

**Comment by esskar** [comment]
Great. Looking forward to the new version.

**Comment by captainsafia** [comment]
Closed via PR above. Should ship in .NET 8 RC2.
