### ISSUE TITLE
Frequent 502 Bad Gateway responses when making post request to aspnetcore based service.

### ISSUE THREAD

**Issue by tomekpr** [dotnet/aspnetcore#50429]
Hi,

I have a few aspnet core 7 based web services that run in Kubernetes cluster. They expose a single controller (a few GET operations and a single POST method). Calls to the POST method are successful I would say about 80-90% of the time. The remaining times I'm getting 502 Bad Gateway responses.

I did some investigation and below are my findings:

On the receiving side of the POST method we have the following:

* The POST method doesn't report any warnings nor does it report any errors. I even added the following configuration to appsettings.json but no luck:

```json  
"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning",
      "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Warning"
    }
  }
```

* The handler of the above POST method doesn't do much. In fact, I changed the code to act as a pass-through and the errors are still there. In other words, no communication with external endpoints or any crazy threading that would get in the way.

* I doubled resources for that web-api, memory and cpu looks fine. There are a few more metrics that I checked but nothing stands out.

* The web-api is configured as follows (cors to allow everything, no https, no authentication). This is purely for internal purposes, stripped down
```csharp
using System.IO.Compression;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.AspNetCore.HttpLogging;
using Prometheus;

var builder = WebApplication.CreateBuilder(args);

const string defaultCorsPolicyName = "HeartbeatCors";
builder.Services.AddCors(options =>
{
    options.AddPolicy(defaultCorsPolicyName,
        policy =>
        {
            policy.AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod();
        });
});

// Add services to the container.
builder.Services.AddControllers();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddHealthChecks();

builder.Services.Configure<GzipCompressionProviderOptions>(options => options.Level = CompressionLevel.Optimal);
builder.Services.AddResponseCompression(
    options =>
    {
        options.MimeTypes = new[]
        {
            "text/plain",
            "application/json",
            "text/json"
        };
    });

builder.WebHost.UseKestrel((context, options) =>
{
    options.Limits.MaxResponseBufferSize = 512 * 1024; // 512KB
    options.Limits.KeepAliveTimeout = TimeSpan.FromSeconds(15);
});

builder.Services.AddHttpLogging(logging =>
{
    logging.LoggingFields = HttpLoggingFields.All;
    logging.MediaTypeOptions.AddText("application/json");
});

var app = builder.Build();
app.Map("/", () => Results.Redirect("/swagger"));

// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI();

app.UseResponseCompression();
app.UseHttpLogging();

app.UseCors(defaultCorsPolicyName);

app.MapControllers();
app.UseHttpMetrics();
app.MapHealthChecks("/status");
app.MapMetrics();

app.Run();
```

* In front of the web-api we have an instance of traefik 2.8.0. I enabled debug logging on traefik and that didn't offer much except of: 

> 'time="2023-08-30T10:36:00Z" level=debug msg="'502 Bad Gateway' caused by: EOF"'

* On the client / caller side, nothing unusual, simple POST requests. Sample response from http-client is as follows:

```json

{
  "Version": "1.1",
  "Content": {
    "Headers": [
      {
        "Key": "Content-Length",
        "Value": [
          "11"
        ]
      },
      {
        "Key": "Content-Type",
        "Value": [
          "text/plain; charset=utf-8"
        ]
      }
    ]
  },
  "StatusCode": 502,
  "ReasonPhrase": "Bad Gateway",
  "Headers": [
    {
      "Key": "Date",
      "Value": [
        "Wed, 30 Aug 2023 13:03:07 GMT"
      ]
    }
  ],
  "TrailingHeaders": [],
  "RequestMessage": {
    "Version": "1.1",
    "VersionPolicy": 0,
    "Content": {
      "Headers": [
        {
          "Key": "Content-Type",
          "Value": [
            "application/json; charset=utf-8"
          ]
        },
        {
          "Key": "Content-Length",
          "Value": [
            "302"
          ]
        }
      ]
    },
    "Method": {
      "Method": "POST"
    },
    "RequestUri": "<omitted>",
    "Headers": [
      {
        "Key": "traceparent",
        "Value": [
          "00-f91f3762eb57ca37b6d42f6975469575-06725c0de21994b4-00"
        ]
      }
    ],
    "Properties": {},
    "Options": {}
  },
  "IsSuccessStatusCode": false
}

```

This case sounds similar but I failed to identify a root cause: https://github.com/dotnet/aspnetcore/issues/7021
The problem doesn't happen at any specific time intervals. It is not clear at the moment whether this problem is load related. I failed to reproduce this problem locally (i.e. running POST requests from my laptop to that web-api in EKS).

Any hints / suggestions? I'm running out of ideas.

**Comment by tomekpr** [comment]
Hi,
Current thinking is that this line:

```csharp
options.Limits.KeepAliveTimeout = TimeSpan.FromSeconds(15);
```
is the problem. I got rid of it. I think the default is 120seconds. Deployed to 2 test environments. So far the results are promising but too early to tell. I will report tomorrow morning/afternoon with the results.

**Comment by Tratcher** [comment]
Try this for more details:
```
"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Debug",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.AspNetCore.HttpLogging.": "Information"
    }
  }
```

A wireshark trace between the proxy and server might also help you see connection issues.



> ```cs
> options.Limits.KeepAliveTimeout = TimeSpan.FromSeconds(15);
> ```

Yeah, that can cause problems that don't show up in the server logs. The server closes connections and the proxy doesn't notice until it tries to forward a request, which then fails with a 502. You shouldn't need/want a short keep alive timeout between the proxy and server. If anything, you'd want it to be longer.

**Comment by amcasey** [comment]
Did increasing the timeout work, @tomekpr?

**Comment by tomekpr** [comment]
Hi everyone,
apologies for not getting back to you on this earlier! Yeah increasing the timeout fixed the problem immediately. No other changes were needed.


Cheers,
TP
