### ISSUE TITLE
Update jquery-validation dependency in templates to the latest version

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#50421]
jquery-validation dependency is outdated and needs to be updated.
Below is the list of all the versions we need to fix this for:
- https://github.com/dotnet/aspnetcore/pull/50482
- https://github.com/dotnet/aspnetcore/pull/50483
- https://github.com/dotnet/aspnetcore/pull/50484

**Comment by mkArtakMSFT** [comment]
@wtgodbe can you please merge the 6.0 and 7.0 PRs when it's time? Thanks!

**Comment by MackinnonBuck** [comment]
Closing since all associated PRs have been merged.
