### ISSUE TITLE
Form Validation isn't working (doesn't seem to validate anything)

### ISSUE THREAD

**Issue by BrienKing** [dotnet/aspnetcore#50420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a brand new Blazor Web App project and modified Index.razor this way:

```
@page "/"
@using System.ComponentModel.DataAnnotations;

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.
<EditForm Model="@TestObj" OnValidSubmit="@DoSomething">
	<DataAnnotationsValidator />
	<ValidationSummary />
	<InputText @bind-Value="@TestObj.FirstName" />
	<button type="submit">Submit</button>
</EditForm>

@code
{
	public TestObject TestObj { get; set; } = new TestObject();

	public class TestObject
	{
		[Required(ErrorMessage = "First Name is required")]
		public string FirstName { get; set; } = "";
	}

	public void DoSomething()
	{
		Console.WriteLine("Hello");
	}
}
```

### Expected Behavior

If I tab out of the Name Text Box or I hit the Submit button, I would expect it to highlight the Text Box in Red and fill out the ValidationSummary with "First Name is Required".

### Steps To Reproduce

Create a brand new Blazor Web App and modify Index.razor with the code from above.

### Exceptions (if any)

No error messages that I could find.

### .NET Version

8.0 Preview

**Comment by darena-pjindal** [comment]
Hi @BrienKing - I had the same confusion when I first started with the new template. I think the default set up for razor components in the Web template is SSR. So, you will need to add @attribute [RenderModeServer] on any page that you want client side validation. This is assuming you selected the option for interactive server components.

**Comment by BrienKing** [comment]
The default should be RenderModeServer.   I already ran into this with a component, I didn't think it was the same for a Page.
