### ISSUE TITLE
Design time code generation is required to implement IDesignTimeDirectiveTargetExtension and maybe that shouldn't be required

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#5042]
A few facts:
- Our default IR passes always generate a `DesignTimeDirectiveIntermediateNode` - even if there are no directives
- The `DesignTimeDirectiveIntermediateNode` tries to resolve the `IDesignTimeDirectiveTargetExtension` from the code target even when it is empty 
- If you implement your own `CodeTarget` then you have a lot of work to do to get the set of default target extensions to show up
- The extensibility provided [here](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/DocumentClassifierPassBase.cs#L96) isn't quite good enough for some scenarios, which requires you to inherit from `CodeTraget`. 

The result of this is that you get a crash if you replace the code target, and you have to do a fair bit of work to "add back" default behaviors

It seems like we have a good opportunity to improve some of these scenarios with Blazor really putting our extensibility through its paces.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
