### ISSUE TITLE
Redis OutputCache no longer works on rc1

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#50452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `AddStackExchangeRedisOutputCache`, it no longer caches my responses. Every time I hit the endpoint, the code runs without being cached.

### Expected Behavior

The cache should work so the output is cached and reused when the policy is valid.

### Steps To Reproduce

1. Run the app at https://github.com/eerhardt/OutputCacheBug using 8.0-preview7.
    - Note the app's code is copied below for ease of reading.
3. You will see the output being cached for 3 seconds. After 3 seconds a new weatherforecast is displayed.
4. Run the app again using the latest 8.0-rc1 build.
    - note that there is a hard-coded version in the .csproj `<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0-rc.1.23414.10" />`, you can change between each version.
5. When using rc1, the output is never cached and I get new results each time I refresh.

### .NET Version

8.0.100-rc.1.23422.1

### Anything else?

Line 53 appears to be the culprit

https://github.com/dotnet/aspnetcore/blob/a42669be75b26cae0e775fbd984ea53a6a9dbdea/src/Middleware/OutputCaching/src/OutputCacheEntryFormatter.cs#L51-L53

`buffer.GetMemory()` is returning a Memory using its current index. See line 65 below:

https://github.com/dotnet/aspnetcore/blob/a42669be75b26cae0e775fbd984ea53a6a9dbdea/src/Middleware/OutputCaching/src/RecyclableArrayBufferWriter.cs#L61-L66

This means if we've written 50 bytes into a buffer of 1024, when we call `.GetMemory()` here, that returns the buffer, but starting at byte 50, and that's what's passed to the store to write to the cache - all the empty bytes from 50-1024. Instead, this should be doing something like `MemoryStream.GetBuffer()`, which gives you access to the buffer starting at the beginning, because we are done writing, and need to start reading what we just wrote.

cc @mgravell 

_______________

## Repro code

```C#
using Microsoft.AspNetCore.OutputCaching;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddStackExchangeRedisOutputCache(o =>
{
    o.Configuration = "localhost:6379";
});

builder.Services.AddOutputCache(options =>
{
    options.AddBasePolicy(builder =>
        builder.Expire(TimeSpan.FromSeconds(3)));
});

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseOutputCache();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", [OutputCache] () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
});

app.Run();

internal record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

**Comment by adityamandaleeka** [comment]
@mgravell Is there anything left to do on this one (other than adding a note to the RC1 post like we discussed)?

**Comment by mgravell** [comment]
@adityamandaleeka all looks good locally, so I think we're set; but I was doing some final validation on the branch locally.
