### ISSUE TITLE
Make ITagHelperComponent.Init asynchronous

### ISSUE THREAD

**Issue by andriysavin** [dotnet/aspnetcore#5045]
There are cases when I need to have asynchronous code in tag helper's `Init` method. Common example for `Init` usage is when I need to populate `Items` or `ViewData` for child tag helpers **before** they run. Basically, `Init` and `ProcessAsync` are just two steps of processing, which allow to order the logic parts between related tag helpers. So, its barely understandable why its not expected that `Init` can do async stuff in the same way as `ProcessAsync`. For instance, I want to use `IAuthorizationService.AuthorizeAsync` and attribute-provided policies in `Init` to do authorization and put results into ViewData to be used by (non-direct) child tag helpers. In this case I would only run that code once - on the parent tag.
Since this is not possible I have to instead put policies list into ViewData and make each child tag helper call `IAuthorizationService.AuthorizeAsync` in `ProcessAsync` every time its run (actually repeating the same code with same results many times).

**Comment by andriysavin** [comment]
Hello folks, so was this ever really implemented?

**Comment by mkArtakMSFT** [comment]
Closing as this is not a priority.
