### ISSUE TITLE
BlazorEnableCompression flag is ignored when publishing Blazor WASM projects

### ISSUE THREAD

**Issue by LostBeard** [dotnet/aspnetcore#50451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Brotli and Gzip compression cannot be turned off when publishing a Blazor WASM project using ```dotnet publish```. 

[Microsoft reference on how to disable compression in Blazor WASM](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#compression)

### Expected Behavior

I expected compression to be disabled.

### Steps To Reproduce

To reproduce:  
Create a new Blazor WebAssembly project and attempt to publish with BlazorEnableCompression disabled either by setting the flag ```<BlazorEnableCompression>false</BlazorEnableCompression>``` in the project's .csproj file or using the flag ```-p:BlazorEnableCompression=false``` with ```dotnet publish```. Both fail to disable the output of Brotli and Gzip encoded files in the published files (.br and .gz files in _framework folder.)

### .NET Version

8.0.100-preview.7.23376.3

**Comment by LostBeard** [comment]
Thank you for your help. I have submitted a pull request to update the documentation.

**Comment by guardrex** [comment]
@javiercn ... Is the change >=8.0 or for all releases?

**Comment by javiercn** [comment]
@guardrex yes.

**Comment by javiercn** [comment]
@MackinnonBuck we probably want to bring the flag back in the Blazor SDK for backwards compatibility.

**Comment by mkArtakMSFT** [comment]
@javiercn is there any remaining work here?

**Comment by mkArtakMSFT** [comment]
https://github.com/dotnet/announcements/issues/283
