### ISSUE TITLE
Faild to load {Assembly}.styles.css with a specific  route in .net 8 Blazor Web App

### ISSUE THREAD

**Issue by FengRuikai** [dotnet/aspnetcore#50471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I specific the route of the razor componet as `@page "/{optional?}"`，the bundled css won't be load correctly

### Expected Behavior

When I try the same as mentioned  in a .net 7 Blazor Server App,the bundled css file could be load.

### Steps To Reproduce

1,Create  a default Blazor Web App
2,modify the codes in Index.Razor:
```
@page "/{optional?}"

<PageTitle>Home</PageTitle>

<h1>Home</h1>

Welcome to your new app.
@Optional

@code {
    [Parameter]
    public string Optional { get; set; }
}
```
3,Debug,Press F12 and check NetWork 

### .NET Version

8.0.100-preview.7.23376.3

**Comment by javiercn** [comment]
@FengRuikai thanks for contacting us.

That's by design, your route accepts `/appname.styles.css` and matches "/{optional?}". You need to use `optional:nonfile?` to avoid matching file like patterns
