### ISSUE TITLE
Blazor SSR - can't wrap layout Body with interactive component

### ISSUE THREAD

**Issue by konstantin-karpukhin** [dotnet/aspnetcore#50518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error caused by:
-'attribute [RenderModeServer]' in layout razor
or
-'rendermode="RenderMode.Server"' on component with layout Body inside

Component.razor:
```
@ChildContent

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```
MainLayout.razor:
```
<Component @rendermode="@RenderMode.Server">
    @Body
</Component>
```

If you have multiple layouts in your application it would useful to make some of them interactive.

### Steps To Reproduce

https://github.com/konstantin-karpukhin/BlazorSSRInteractiveLayout/tree/main

### Exceptions (if any)

InvalidOperationException: Cannot pass the parameter 'Body' to component 'MainLayout' with rendermode 'ServerRenderMode'. This is because the parameter is of the delegate type 'Microsoft.AspNetCore.Components.RenderFragment', which is arbitrary code and cannot be serialized.
Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.ValidateParameters(IReadOnlyDictionary<string, object> latestParameters)

**Comment by javiercn** [comment]
@konstantin-karpukhin thanks for contacting us.

The issue here is by design. We don't support switching render modes back and forth, as we can't serialize the delegate. Interactive components must have serializable parameters without cycles (which discards the delegate)
