### ISSUE TITLE
Aspnetcore server check websocket connection status wrong.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/aspnetcore#50515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Browser is closed websocket connection, In server side, `ws.CloseStatus` is always null. and `ws.SendAsync` not throw exception

### Expected Behavior

`ws.CloseStatus` is not null and `ws.SendAsync` failed when client closed connection.

### .NET Version

8.0.0-preview.7.23375.6

**Comment by BrennanConroy** [comment]
How are you closing the connection? If you don't close it gracefully then the client might not send a close frame on the websocket and the server won't know the connection is dead. TCP can then take "a long time" to realize the connection is closed.

This is why libraries like SignalR add app level ping messages that will close the connection if a message isn't received within a specified duration.

**Comment by MiyamuraMiyako** [comment]
@BrennanConroy This code print "closing..." and wait a few seconds,then throw error, but in server side, not throw any exception and continue send data.

```js
var socket =new WebSocket(url);
socket.addEventListener("open", function (event) {
  console.log("connected!");
});
socket.addEventListener("message", function (event) {
  console.log("Message from server ", event.data);
});
socket.addEventListener("close", function (event) {
  console.log("closed ");
});
setTimeout(()=>{console.log('closing..');socket.close()},3000); 
```
![图片](https://github.com/dotnet/aspnetcore/assets/10345361/4b1b2704-9b1d-48e7-8001-96832d35b322)

**Comment by MiyamuraMiyako** [comment]
@BrennanConroy And yes, I used app layer ping message now. But I can't understand why the normal close cannot be closed

**Comment by BrennanConroy** [comment]
Websocket close is a handshake process. The client sends the first part saying it wants to close, but if the server doesn't send a close frame the client will wait a little bit before ungracefully closing the connection.

If your server isn't actively reading it won't know the client sent a close frame and so won't be able to send a close response. The server can keep sending until the underlying TCP connection closure is noticed by the server which can take a long time, or until all the OS and server buffers are full and you experience backpressure.

Is your server continually calling `websocket.ReceiveAsync(...)`, looking at the `WebSocketReceiveResult.CloseStatus/WebSocketReceiveResult.MessageType`, and responding with `websocket.CloseAsync(...)`?
