### ISSUE TITLE
Method 'DisposeAsync' in type 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnection' from assembly  'Microsoft.AspNetCore.Http.Connections.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'  does not have an implementation.

### ISSUE THREAD

**Issue by ashuvviet** [dotnet/aspnetcore#50520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

we have build the SignalR server using Asp Net core .net 6.0.

Client side:
we have created new .net client library using .net standard2.0 which use "Microsoft.AspNetCore.SignalR.Client" V6.0.0. and this class library is consumed by main desktop application build on .net framework4.7.1 which runs are windows service.
Due to nature of Legacy application, most of thing work as synchronously and to start the signalR HubConnection, we need to use task.run to start in async way, here is the code.

` var connection = new HubConnectionBuilder()
              .WithUrl(url)
             .WithAutomaticReconnect()
             .Build();`

 `connection.StartAsync().Wait();`
or
`Task.Run(async () =>  await connection.StartAsync());`

none of the way, connection starts and following error is thrown
 Method 'DisposeAsync' in type 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnection' from assembly  'Microsoft.AspNetCore.Http.Connections.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'  does not have an implementation.

### .NET Version

.net standard

**Comment by Tratcher** [comment]
Please share your full project dependencies list and versions. This happens when versions are mismatched.

**Comment by ashuvviet** [comment]
This issue identified and it was due to be mismatch version of "System.Threading.Tasks.Extensions". redirect assembly fixed the issue.
