### ISSUE TITLE
set serialization method for specific controllers

### ISSUE THREAD

**Issue by liuliang-wt** [dotnet/aspnetcore#50540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

my app use the default System.Text.Json to do serialization, now I need to add a third party library which use Newtonsoft, it has some code like this:
services.AddControllers().AddNewtonsoftJson(setupNewtonsoftJson);

so the problem is, if I use this library, my own system will be broken, because I have many custom converters for System.Text.Json. 
Is there a way that I can set System.Text.Json for some controllers and Newtonsoft for others?

### Describe the solution you'd like

maybe a attribute that I can apply to a controller to set its serialization library?

**Comment by javiercn** [comment]
@liuliang-wt thanks for contacting us.

You can set the list of formatters to whatever you want as part of anything that returns an object result. See https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.objectresult.formatters?view=aspnetcore-7.0#microsoft-aspnetcore-mvc-objectresult-formatters for details.
