### ISSUE TITLE
CascadingTypeParameter aliases

### ISSUE THREAD

**Issue by ProH4Ck** [dotnet/aspnetcore#50544]
## Summary

I want to add flexibility to `[CascadingTypeParameter]` allowing one or more alias(es) for generic type.

## Examples

Consider this `EntityHost` component:

```razor
@using QuickGridSample.Models

@typeparam TEntity

@attribute [CascadingTypeParameter(nameof(TEntity))]

<h3>@(typeof(TEntity).Name)</h3>

<EntityStats TEntity="TEntity">
    @StatsContent
</EntityStats>

<QuickGrid TGridItem="TEntity" Items="@GetData()">
    @GridContent
</QuickGrid>

@code {

    [Parameter]
    public RenderFragment GridContent { get; set; }

    [Parameter]
    public RenderFragment StatsContent { get; set; }

    private IQueryable<TEntity>? GetData()
    {
        if (typeof(TEntity) == typeof(Person))
        {
            return new []
            {
                new Person(1, "Mario", new DateOnly(2023, 9, 6)),
                new Person(2, "Luigi", new DateOnly(2023, 9, 6)),
                new Person(3, "Andrea", new DateOnly(2023, 9, 6))
            }.AsQueryable() as IQueryable<TEntity>;
        }

        return Enumerable.Empty<TEntity>().AsQueryable();
    }

}
```

and this page consuming the component:

```razor
<EntityHost TEntity="Person">
    <GridContent>
        <PropertyColumn Property="@(p => p.PersonId)" Sortable="true"/>
        <PropertyColumn Property="@(p => p.Name)" Sortable="true"/>
        <PropertyColumn Property="@(p => p.PromotionDate)" Format="yyyy-MM-dd" Sortable="true"/>
    </GridContent>
    <StatsContent>
        additional stats...
    </StatsContent>
</EntityHost>
```

This produces the following errors on `PropertyColumn`:

```
error CS0411: The type arguments for method 'TypeInference.CreatePropertyColumn_0<TGridItem, TProp>(RenderTreeBuilder, int, int, Expression<Func<TGridItem, TProp>>, int, bool?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
error CS0411: The type arguments for method 'TypeInference.CreatePropertyColumn_1<TGridItem, TProp>(RenderTreeBuilder, int, int, Expression<Func<TGridItem, TProp>>, int, bool?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
error CS0411: The type arguments for method 'TypeInference.CreatePropertyColumn_2<TGridItem, TProp>(RenderTreeBuilder, int, int, Expression<Func<TGridItem, TProp>>, int, string, int, bool?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

To fix the errors I need to manually pass `TGridItem` and `TProp` properties on all `PropertyColumn` tags.

## Proposed solution

To solve this problem in a more elegant way I propose an update to `CascadingTypeParameterAttribute` to allow something like this:

```csharp
[CascadingTypeParameter(nameof(TEntity), "TGridItem")]
```

2nd parameter could be of type `params string[]` to allow more aliases for a single generic type.

What do you think? I can work on the PR to implement this if it's useful!

Thanks.

Emanuele

**Comment by javiercn** [comment]
@ProH4Ck thanks for contacting us.

I'm not sure how you think this solves the problem, and I am not sure we want to add these types of aliases, as they complicate the compiler, don't work across boundaries, and can easily introduce ambiguity.

**Comment by ProH4Ck** [comment]
> @ProH4Ck thanks for contacting us.
> 
> I'm not sure how you think this solves the problem, and I am not sure we want to add these types of aliases, as they complicate the compiler, don't work across boundaries, and can easily introduce ambiguity.

Hi @javiercn ,
I'd like to solve the problem in the sample code uploaded.
I have a component with a generic type parameter called `TEntity`.
I want to pass this generic type parameter to child components so I need to use `[CascadingTypeParameter(nameof(TEntity))]`.
The problem is that `CascadingTypeParameter` binds generic types by name so all child components need to use `TEntity` as generic type name! 
This is an easy task if child component(s) are developed by you... but when they're third-party components (like QuickGrid in the sample) this is a problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The problem you're experiencing here is due to the language (C#) rather than Blazor or even Razor language. @jaredpar FYI in case you 'd like to think about this in the future, but from our point of view this is not something that we'll do in Blazor.

**Comment by jaredpar** [comment]
This is the proposal that tracks adding partial type inference into C# 

https://github.com/dotnet/csharplang/issues/1349
