### ISSUE TITLE
Content Disposition header generate invalid filename when semicolon is present

### ISSUE THREAD

**Issue by IhnatKlimchuk** [dotnet/aspnetcore#50557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create next endpoint:

```
[HttpGet("ics")]
public async Task<ActionResult<string>> GetIcsFile()
{
    return this.File(Encoding.UTF8.GetBytes("test"), "text/calendar", "test ; value");
}
```

Next header is returned:
```
content-disposition: attachment; filename="test ; value"; filename*=UTF-8''test%20%3B%20value 
```

filename attribute value is "quoted-string", but it contains semicolon that is parsed as end symbol. As result, software that don't support UTF-8 will parse it as "token" like `filename="test ;`, resulting in: `_test _` filename.

### Expected Behavior

Next header should be returned:
```
content-disposition: attachment; filename="test _ value"; filename*=UTF-8''test%20%3B%20value 
```

I guess that semicolon is not a valid character in "quoted-string"

### Steps To Reproduce

Create next endpoint:

```
[HttpGet("ics")]
public async Task<ActionResult<string>> GetIcsFile()
{
    return this.File(Encoding.UTF8.GetBytes("test"), "text/calendar", "test ; value");
}
```

Call endpoint

### .NET Version

latest

**Comment by Tratcher** [comment]
https://www.rfc-editor.org/rfc/rfc2616
       quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
       qdtext         = <any TEXT except <">>
       TEXT           = <any OCTET except CTLs,
                        but including LWS>

https://www.rfc-editor.org/rfc/rfc7230#section-3.2.6
     quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
     qdtext         = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text

';' (x3B) is explicitly allowed in the above spec

It seems like your client doesn't correctly handle quoted strings. What client is it?
