### ISSUE TITLE
Introduce a Shared DynamicObject for Cross-Controller Data Exchange

### ISSUE THREAD

**Issue by SaeedMolaiy** [dotnet/aspnetcore#50559]
**Feature Request: Shared DynamicObject for Controllers**

**Description:**
I would like to propose the addition of a feature that allows for the creation of a shared `DynamicObject` that can be accessed across all controllers in an ASP.NET Core application. This shared `DynamicObject` would serve a similar purpose to `ViewBag` but with the key distinction that it can be accessed and updated by all controllers within the application, regardless of the controller where it was initially set.

**Motivation:**
Currently, ASP.NET Core provides the `ViewBag` for passing dynamic data from controllers to views. However, `ViewBag` is limited to the scope of a single controller action and its associated view. This makes it challenging to share data across multiple controllers without resorting to more complex mechanisms like session state or dependency injection.

The proposed shared `DynamicObject` would provide a more convenient and standardized way to share data among controllers without the limitations of the current `ViewBag`.

**Use Cases:**
- Sharing user authentication or authorization information across controllers.
- Storing application-wide configuration settings that need to be accessible across controllers.
- Sharing contextual data, such as localization settings, themes, or user preferences, across controllers.

**Implementation Ideas:**
- Create a new `SharedData` class that derives from `DynamicObject` .
- Controllers can set and retrieve data from the shared `SharedData` instance as needed.
- Provide a clean API for setting and getting data, similar to how `ViewBag` is used.

**Example Usage:**
```csharp
// In a controller
public IActionResult MyAction()
{
    Shared.Message = "This is new feature";

    return View();
}

// In another controller
public IActionResult AnotherAction()
{
    var message = Shared.Message;

    return View();
}
```

**Note:** I would be happy to implement this feature by myself if it's possible. I believe it would be a valuable addition to the ASP.NET Core framework and would contribute to making ASP.NET Core more developer-friendly and expressive.

Thank you for considering this proposal.

**Comment by javiercn** [comment]
@SaeedMolaiy thanks for contacting us.

This is not a feature we plan to include in the framework. This type of sharing is already possible through a singleton service in DI that you inject into all your controllers.

This type of state sharing can also easily produce insecure situations where data from a user leak to a response from another user.

**Comment by SaeedMolaiy** [comment]
> @SaeedMolaiy thanks for contacting us.
> 
> This is not a feature we plan to include in the framework. This type of sharing is already possible through a singleton service in DI that you inject into all your controllers.
> 
> This type of state sharing can also easily produce insecure situations where data from a user leak to a response from another user.

Thank you for your response.

I appreciate your feedback and the suggestion to use a singleton service through Dependency Injection. However, I would like to emphasize that the shared data I am proposing is intended to be generated for each user and scoped to their session or request context.

While a singleton service can be useful for certain scenarios, it does not provide the same level of isolation and scoping required for user-specific data sharing. In a web application, user-specific data often needs to be accessible only within the context of that user's session or request, ensuring data separation and security.

The goal of this feature request is to enable a convenient and secure way to share user-specific dynamic data among controllers during the course of a user's session, without the risk of data leakage between users. It would enhance the developer experience and make it easier to build features that rely on user-specific context.

I understand the concerns about security and data isolation, and I believe that the proposed feature can be designed to address those concerns while providing a valuable tool for developers working on ASP.NET Core applications.

Please reconsider this feature request in light of its potential benefits for developers in creating more dynamic and user-specific applications. If there are any specific security or implementation concerns, I would be happy to discuss and address them in the proposal.

Thank you for your time and consideration.
