### ISSUE TITLE
HttpRequestHeaders Keys.Contains is not case insensitive, whereas HttpDictionary is

### ISSUE THREAD

**Issue by tsollas** [dotnet/aspnetcore#50553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders ` incorrectly returns a case sensitive `List<string>` for the `Keys` implementation, which results in a case sensitive list, which contravenes the HTTP RFC's. Specifically: 

`ICollection<string> IDictionary<string, StringValues>.Keys => ((IDictionary<string, StringValues>)this).Select(pair => pair.Key).ToList();`

should instead should simply return the underlying dictionary's `Keys` implementation. The result is that  `HttpRequestHeaders.Keys.Contains()` is actually a case sensitive contains, rather than a expected case insensitive contains.

### Expected Behavior

`Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders `  is an implementation of `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders`, which implements `IHeaderDictionary`. In a controller method, or in a registered middleware, it's this implementation that is instantiated during an HTTP request. 

You can't instantiate `HttpRequestHeaders` due to it being an internal sealed class, so for unit testing the typical pattern is to use `Microsoft.AspNetCore.Http.HeaderDictionary`, which can be instantiated. However, `HeaderDictionary`'s implementation of `Keys` is different, it instead simply returns the `KeysCollection` of the internal backing dictionary, which is created using a case insensitive comparer.

As noted, `HttpRequestHeaders.Keys.Contains()` should be a case insensitive Contains, rather than case sensitive.

### .NET Version

6.0.20

### Anything else?

$ dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tsollas** [comment]
@En3Tho Yes, I could simply write an extension method to do so, however since header fields are expected to be case insensitive per the RFC, searching for a key in a case insensitive way isn't expected, and the fact that `HeaderDictionary` works this way makes sense. For example, `HttpRequestHeaders.TryGetValue("foo", out headerValue)` does indeed do a case insensitive get (and is in fact what I refactored our validation logic to use). Internally, `HttpRequestHeaders` does something like `.Equals(key, StringComparison.OrdinalIgnoreCase))`.

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/blob/045afcd68e6cab65502fa307e306d967a4d28df6/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.cs#L118C134-L118C140

> I believe this would be a breaking change.

This would be considered a bug because it's inconsistent with other APIs in the same type (and elsewhere).

**Comment by WeihanLi** [comment]
How about changing the `.ToList()` to `.ToHashSet(StringComparer.OrdinalIgnoreCase)`?
