### ISSUE TITLE
Microsoft.ApplicationInsights.AspNetCore used deprecated NuGet packages

### ISSUE THREAD

**Issue by MarcoK80** [dotnet/aspnetcore#50569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Dotnet list package --outdated / --deprecated shows for the packages

Microsoft.ApplicationInsights.AspNetCore 2.21.0
Microsoft.ApplicationInsights.Profiler.AspNetCore 2.5.3
Microsoft.ApplicationInsights.Profiler.Core 2.5.3

outdated and if we update them deprecated packages
Microsoft.AspNetCore.Hosting 
Microsoft.AspNetCore.Http

Is there any plan to migrate these packages to full .net core 7 or .net core 8 support?

### Describe the solution you'd like

Support native .net core 7 and .net core 8

**Comment by martincostello** [comment]
These packages are maintained by the Azure Application Insights team in the https://github.com/Microsoft/ApplicationInsights-dotnet repository.

**Comment by amcasey** [comment]
As far as I know, this can't be transferred to another GH org so, unfortunately, you'll have to file a fresh issue there.
