### ISSUE TITLE
During shutdown of the ASP.NET host, configuration values cannot be resolved anymore

### ISSUE THREAD

**Issue by smintrh78** [dotnet/aspnetcore#50570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When shutting down an ASP.NET host, it seems that IConfiguration providers cannot resolve values anymore.

This means that when, during shutdown, classes are being created by DI, that need IConfiguration, those classes will begin to report missing settings and stuff.

Also, suddenly the log settings vanish, and the logs contain things they shouldnt.

### Expected Behavior

The configurations should be unloaded at the very last before shutting down the process.

### .NET Version

6.0.401

**Comment by Tratcher** [comment]
Please share your Program.cs so we know which hosting APIs you're using.
