### ISSUE TITLE
PreventDefault not working in next 13

### ISSUE THREAD

**Issue by bash-codify** [dotnet/aspnetcore#50581]
When using the e.preventDefault to prevent the default event behavior for a form submit, the page keeps refreshing.
 
 const submitHandler = e => {

     e.preventDefault();    
 }
<img width="454" alt="Screenshot 2023-09-08 025956" src="https://github.com/dotnet/aspnetcore/assets/105221850/9255afbf-8896-4cd7-866b-7a76e8e5a6d4">

**Comment by javiercn** [comment]
@bash-codify thanks for contacting us.

This issue seems completely unrelated to ASP.NET Core, we suggest you file this issue directly against the nextjs repo.
