### ISSUE TITLE
Easy WASM and Web Component modules for Blazor Web

### ISSUE THREAD

**Issue by maloo** [dotnet/aspnetcore#50615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

1) Blazor Web SSR requests full page on navigation which can be quite a lot more data than a SPA requesting some JSON to update a page and render locally
2) Having no Blazor WASM/Server (for various reasons like download, startup, memory performance) might force you to use JS in the SSR rendered page.
3) Blazor WASM is a full .NET runtime and framework, which might not be needed

### Describe the solution you'd like

TL;DR New project type to create C# Web Components module, AOT compiled to WASM.

Add a new project type to build C# for accessing browser APIs and do full AOT WASM compilation of this to get a minimal wasm file to replace any ts/js you would otherwise need. Making it easy to create modules like this and reference them from other Blazor Web projects for inclusion in wwwroot at build w/o having to start using Rust/nodejs.
This would allow C# devs to write less rust/ts/js, while still not be forced to start using Blazor WASM components.
Instead, it would allow creating Web Components in C#, just like you now can do with Rust. Creating Web Components in C# in a separate project is also something that could be useful for a host of other situations (like reuse in React and other frameworks). And Once you can create Web Components in a small WASM modular package. You can use these in Blazor SSR to render a "logical" UI using high level abstraction web components, reducing the amount of html/css you have to send on each SSR render to the client. The data is now very similar to JSON (UI structure and size similar to JSON data structure and size).
So now a Blazor Web page navigation is not getting much more data than a GraphQL request. So you get the speed of SSR with the data load of SPA w/ GraphQL/REST. And page caches have much less data to store.

**Comment by javiercn** [comment]
@maloo thanks for contacting us.

We don't think this is practical. The language and the core runtime are part of the core experience, and we don't think there is room for an experience that involves C# and not the runtime.  The amount of work that this requires for the scenarios that are not already covered by Blazor also doesn't pay off in our view, so this is not a direction we plan to follow.
