### ISSUE TITLE
Add line endings on to RazorCodeGenerationOptions

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#5061]
We have special hooks that we use for testing to mess with line endings for Razor. There's no good reason why we shouldn't just make the line endings configurable.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
