### ISSUE TITLE
[Blazor] SSR security guidance docs

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#50637]
This doc is specifically about security best practices with Server Side rendered Blazor apps, not anything related to authentication.

**Comment by guardrex** [comment]
Side note: The current articles have merely had their language adjusted from "Blazor Server"/"hosting model" phrasing to more generic terminology, primarily *server*/*server-side* phrasing. This avoided requiring a ***massive*** amount of content versioning and duplication across the entire doc set. However, the jury is out on if we'll be able to use the approach. If readers get confused, we might need to move to full content versioning. No other changes were made. No content was added specifically for SSR. Here are the existing 8.0 articles with the new phrasing:

* [Overview](https://learn.microsoft.com/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio)
* [Threat Mitigation](https://learn.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-8.0)
* [Additional scenarios](https://learn.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0)

**Comment by javiercn** [comment]
Reference content: https://github.com/dotnet/aspnetcore/issues/51577#issuecomment-1808400904

**Comment by javiercn** [comment]
@guardrex I've pinged you in the other issue, just in case. I'm going to close that one and use this to track but the content is in the comment.

https://github.com/dotnet/aspnetcore/issues/51577#issuecomment-1808400904

**Comment by guardrex** [comment]
Sure thing ... I'll take care of it *ASAP* ... hopefully by EOD today (Wed) 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️😅 ... but tomorrow at the latest.

**Comment by mkArtakMSFT** [comment]
Thank you for your patience.
Given the number of issues that we have to deal with, we're aggressively closing those that we haven't been able to get to in a reasonable time. This will help us focus on the issues which are more impactful.
