### ISSUE TITLE
Remove workaround from the Blazor Web App template when WebAssembly is enabled

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50646]
The following [workaround](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Pages/Counter.razor#L2-L8) in the Blazor Web App template is no longer needed and should be removed. The Counter page component can now live in the Client project and the Client project can be configured for component discovery as an additional assembly.

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/50684
