### ISSUE TITLE
Metadata to exclude request from http.server.request.duration metric

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#50654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Every request that comes into ASP.NET Core is recorded to the `http.server.request.duration` metric. There are some situations where its desirable to opt out of that behavior:

* Prometheus `/metrics` scraping endpoint
* Healthchecks `/heathz` endpoint

Excluding system endpoints that are regularly requested is useful because they distort results.

### Describe the solution you'd like

Add metadata that can be used to skip recording the request. Then, an app can configure endpoints with the metadata to exclude them from recording the HTTP metric.

It could be an `SuppressHttpMetric()` extension method:

```cs
app.MapPrometheusScrapingEndpoint().SuppressHttpMetric();
```

Or attribute:

```cs
[HttpGet]
[SuppressHttpMetric]
public IActionResult GetHealth()
{
     // ...
}
```

Some libraries might automatically include the metadata, e.g. OTel's `PrometheusScapingEndpoint` internally adds the metadata when it creates the endpoint.

**Comment by Ne4to** [comment]
Is there any workaround?
I tried to find filter options in [HostingMetrics](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingMetrics.cs) with no success.
`MapPrometheusScrapingEndpoint` allows to pass custom `MeterProvider` but it has no methods to override and internally `MeterProvider` is converted to internal `MeterProviderSdk` in [MeterProviderExtensions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1b4f231e2e52b068bc0a88d696cb495ccecd8081/src/OpenTelemetry/Metrics/MeterProviderExtensions.cs#L111)

**Comment by JamesNK** [comment]
Can you provide why you want to disable the metric? It is useful for us to understand why and when a new feature would be used.

**Comment by Ne4to** [comment]
My top three requests now are `/metrics` for Prometheus and two endpoints for Kubernetes liveness and readiness probes. When I open these dashboards https://grafana.com/orgs/dotnetteam the first thing I see is not helpful. Some summary graph   is 99% misleading for a service on a test environment.

BTW: official dashboards use different units than published by ASP.NET 8 and 
`http_server_request_duration_seconds_bucket` should be changed to `http_server_request_duration_s_bucket` in the dashboard to start it working (`s` instead of `seconds`)

![image](https://github.com/dotnet/aspnetcore/assets/827712/6bd20830-5275-423e-8f76-579cbce3c2b8)
![image](https://github.com/dotnet/aspnetcore/assets/827712/0ca61485-4266-4635-aff5-93f656685316)

**Comment by WeihanLi** [comment]
I have similar issues with @Ne4to , some endpoints should be excluded like the Prometheus scraping endpoint and probe endpoints. This should be a high priority I think.

And I tried with the `ShortCircuit()` extension introduced in .NET 8, which would not work for this case, should the metrics be excluded when `ShortCircuit()` is specified?

**Comment by JamesNK** [comment]
`ShortCircuit()` skips middleware, but the counter is recorded at the hosting layer. It won't be skipped.

**Comment by JamesNK** [comment]
To come up with the right improvement for this situation I'm going to reach out to OpenTelemetry team for their advice.

One approach might be to skip recording system endpoints. Another approach would be to still record a value but add a tag to indicate that it's a system endpoint. Then people can choose to use the tag to filter results out.

**Comment by leandrobattochio** [comment]
Just another thumbs up here. I ended up changing asp net core default grafana dashboard to not include endpoints matching "/metrics" from the results.
But then I also noticed some requests from my SignalR are also being recorded and it is messing with my graphs. I think we should be able to choose to exclude some endpoint from metrics. I don't wan't to record calls to "/metrics" endpoint.

I also wouldn't want SignalR handshakes too. I mean, I expect some connections to be opened for a long time. What I'm interested in is if any of my business API is taking too long to execute.

Have any of you experienced something similiar when it comes to metrics and signalr hubs ?

**Comment by vchirikov** [comment]
Same here, it will be nice to have more control on metrics, looks like in net8.0 we can only enrich tags from middleware with `IHttpMetricsTagsFeature`, but not to filter them as it was in net6.0 with otel (`AddAspNetCoreInstrumentation` had an `Filter` option). 

@JamesNK do you have any news about this?

**Comment by JamesNK** [comment]
Not in the last 6 days.

.NET 9 won't come out until November so there is lots of time to improve this scenario.

**Comment by xkursatx** [comment]
by adding OpenTelemetry.Instrumentation.AspNetCore
and

```
builder.Services.AddOpenTelemetry()
    .WithMetrics(builder =>
    {
        builder
            .AddPrometheusExporter()
            .AddMeter("Microsoft.AspNetCore.Hosting", "Microsoft.AspNetCore.Server.Kestrel");

    })
    .WithTracing(builder =>
    {
        builder
            .AddAspNetCoreInstrumentation((options) => options.Filter = httpContext =>
            {
                if (httpContext.Request.Path.Value == "/metrics")
                {
                    return false;
                }
                return true;
            });
    });
```

i think this will resolve my problem. not tested yet on production

**Comment by vishweshbankwar** [comment]
Linking a similar issue from OTel side: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4982

cc: @noahfalk @samsp-msft

**Comment by JamesNK** [comment]
The idea proposed in the original issue text - https://github.com/dotnet/aspnetcore/issues/50654#issue-1892351387 - is to use endpoint metadata to opt out of collecting metrics.

Endpoint metadata is great when you want behavior to be static for an endpoint, for example, the health check API or Prometheus scraping API always never reports a value to `http.server.request.duration`.

```cs
// Yes http.server.request.duration values reported
app.MapGet("/api/person", (int id) => _repo.GetPerson(id));

// No http.server.request.duration values reported
app.MapPrometheusScrapingEndpoint().DisableHttpMetrics();
app.MapHealthChecks().DisableHttpMetrics();
app.MapGet("/live", () => "true").DisableHttpMetrics();
```

That covers what is being discussed in this issue. However, does anyone have a scenario that requires more dynamic behavior is required? For example, a HTTP request decides to not report metrics while it is running?

```cs
app.MapGet("/live", (context) =>
{
    // Disable reporting metric 50% of the time.
    if (Random.Shared.NextInt(0, 1) == 1)
    {
        context.Features.Get<IHttpMetricsDisableFeature>()?.DisableMetrics();
    }

    return "true";
});
