### ISSUE TITLE
AsyncEnumerable response not working as expected

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#50656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I return `IAsyncEnumerable` response, the response is not a valid JSON and data not expected

response likes below

![image](https://github.com/dotnet/aspnetcore/assets/7604648/e8d1876f-bb07-497a-afd3-e28e825d02f0)

Not sure if it's a bug

### Expected Behavior

Should it be a valid json?

### Steps To Reproduce

``` c#

[Route("api/[controller]")]
public class JobsController : ControllerBase
{
    [HttpGet]
    public async IAsyncEnumerable<Jobs> Jobs()
    {
        for (var i = 0; i < 100; i++)
        {
            await Task.Delay(200);
            yield return new Jobs() { Id = i + 1, Title = $"job_{i}" };
        }
    }
}


public class Jobs
{
    public required int Id { get; set; }
    public required string Title { get; set; }
}

```
https://github.com/WeihanLi/SamplesInPractice/blob/8668eb1fd727548c5b53333a2b3636c4be691e94/net8sample/AspNetCore8Sample/JobsController.cs

try to access the API `/api/jobs`

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/7604648/a08fd41d-b997-42e7-8187-2d860de56824)

### .NET Version

8.0.100-preview.7.23376.3

**Comment by BrennanConroy** [comment]
It looks like you're not reading the full response before trying to parse it. Your code is writing 100 `Job` items and they are likely being streamed to the client, but you are trying to parse the data after only 4 items have been sent.

**Comment by WeihanLi** [comment]
Thank you very much for the quick response

I'm trying on the `GetFromJsonAsAsyncEnumerable`extension, while still get an exception 
https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/#system-net-http-json-extensions-for-iasyncenumerable

``` c#
using var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:5297");
var stream = httpClient.GetFromJsonAsAsyncEnumerable<Job>("api/Jobs");
await foreach (var job in stream)
{
    Console.WriteLine(job);
}

file sealed class Job
{
    [JsonPropertyName("id")]
    public required int Id { get; set; }
    [JsonPropertyName("title")]
    public required string Title { get; set; }
    public override string ToString() => $"JobId: {Id}, JobTitle: {Title}";
}

```

here's the test code, and response as follows:

![image](https://github.com/dotnet/aspnetcore/assets/7604648/5745e810-85e2-43ab-b3f6-ab898a8e863c)

**Comment by BrennanConroy** [comment]
I see that you're using the request timeout middleware in the same app to test `IAsyncEnumerable`. You've set up a default of 1 second request timeout, which combined with your 200 millisecond delay while returning items from the controller means only 4 items will be returned by the time the timeout occurs. The reason your client sees a 200 is because HTTP sends headers first then content, and status code is a header. So we need to return a 200 before sending the chunked responses.

**Comment by WeihanLi** [comment]
Oh, that's it, sorry I forgot the request timeout, when I use a basic setup without request timeout, it works, thank you very much @BrennanConroy ❤️
