### ISSUE TITLE
.NET 8 RC1 Blazor Web App: [RenderModeAuto] keeps using the Server implementation then switches to WASM

### ISSUE THREAD

**Issue by dmm-l-mediehus** [dotnet/aspnetcore#50677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a simple Weather app that consists of 3 projects:
* BlazorApp1 (server and API controller for the client)
* BlazorApp1.Client (client)
* ClassLibrary1 (shared lib)

Class Library holds interfaces, and service-implementations.
- In BlazorApp1, I inject the IWeatherService to use WeatherService.cs
- In BlazorApp1.Client, I inject the IWeatherService to use HttpClientWeatherService.cs

in Weather.razor (`BlazorApp1.Client.Components.Weather.razor`), I inject IWeatherService and use GetForecastsAsync()-method to get forecasts.

I noticed the app keeps using Server implementation (WeatherService.cs) at first (both navigating from /counter back to weather and F5 refresh) then switches to WASM implementation (HttpClientWeatherService.cs), even though the app is finished downloaded in the background.

### Expected Behavior

I expect the Web App to **only** use the WASM implementation of the service, when the application is downloaded and cached.

### Steps To Reproduce

1. Clone https://github.com/dmm-l-mediehus/BlazorApp1-RenderModeIssue
2. Run the app with debugging (F5)
3. Set breakpoints at the HttpClientWeatherService.cs line 19, and WeatherService.cs line 22
4. Navigate to /weather and the breakpoint will hit Server at first which is fine initially. But when navigating to another page, and back to /weather - it should hit the WASM breakpoint, but doesn't. Same for F5 - it should use the HttpClientWeatherService.cs implementation

### .NET Version

8.0.100-rc.1.23455.8

**Comment by javiercn** [comment]
@dmm-l-mediehus thanks for contacting us.

That's by design. At least for 8.0, handling the transition between server and webassembly is not trivial, so we require a page refresh (or the next visit) to avoid having to deal with complications derived from the page state.

**Comment by dmm-l-mediehus** [comment]
In best practice, then how should I implement this example of using RenderModeAuto and calls to DB?

**Comment by mkArtakMSFT** [comment]
Components should rely on abstractions when interacting with services which may have client or server implementations. That way, no matter where they get rendered the environment-specific implementation will provide the right functionality.

**Comment by DM-98** [comment]
@mkArtakMSFT That's what I did, right? I have client and server implementations, and it calls the database twice which is a bug. 

I'm using Microsoft's documentation on preserving the state during/after prerendering by using IMemoryCache...But it still calls it twice since there's 2 different implementations and it calls them both.

Having await Task.Delay(1000); for testing, it waits 2 seconds, and I expect it to be 1 second to load /weather

**Comment by ynnob** [comment]
This might be related to issue #50686

**Comment by DM-98** [comment]
@ynnob Sounds like it. Just odd they said that's by design, and said what to do in practice to get it to work... and that's exactly what I am doing.
