### ISSUE TITLE
Breaking change in `Microsoft.AspNetCore.Components.WebAssembly.Server`

### ISSUE THREAD

**Issue by denmaklucky** [dotnet/aspnetcore#50681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Base on this [article ](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-6/#interactive-rendering-with-blazor-webassembly)I also have the following code in an app;

```csharp
builder.Services
    .AddRazorComponents()
    .AddServerComponents()
    .AddWebAssemblyComponents();
```

After updating the package to version `8.0.0-rc.1.23421.29`, the `AddWebAssemblyComponents()` method disappeared, and I could not find any analog of this method.

You can find the error from Visual Studio in the picture below.

![image](https://github.com/dotnet/aspnetcore/assets/8844526/0469d290-5047-4d67-bf61-99109c31b97c)

In version `8.0.0-preview.6.23329.11` or `8.0.0-preview.7.23375.9` it works fine.

### Expected Behavior

The method `AddWebAssemblyComponents()` or any analog will be existing.

### Steps To Reproduce

- create an app by the Blazor Web App template
- add a nuget package `Microsoft.AspNetCore.Components.WebAssembly.Server` with `8.0.0-preview.7.23375.9`
- change a Program.cs like below:
```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services
    .AddRazorComponents()
    .AddServerComponents()
    .AddWebAssemblyComponents();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}

app.UseStaticFiles();

app.MapRazorComponents<App>().AddWebAssemblyRenderMode();

app.Run();

```
- change the version the package to `8.0.0-rc.1.23421.29`

### .NET Version

8.0.100-preview.6.23330.14, 8.0.100-rc.1.23455.8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Try to create a new project using rc1 and see what it does.
