### ISSUE TITLE
Consider not setting PreserveCompilationContext in the RazorSDK when targeting 6.0 or later

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#5068]
Related issue: https://github.com/dotnet/cli/issues/9135. We set PreserveCompilationContext=true for all project types in the Razor.Sdk. This results in an `refs` directory to be created in the build output directory which is undesirable. We should consider setting PreserveCompilationContext=true only if the app's an executable.

**Comment by pranavkm** [comment]
Expanding the scope of this issue. We currently require setting `PreserveCompilationContext = true` since it's essential for MVC's discovery of assemblies to correctly work. Perhaps we can find a way to solve this problem by working with the SDK folks.

**Comment by pranavkm** [comment]
Now that we [changed](https://github.com/aspnet/AspNetCore/pull/10271) the discovery model, this is unblocked and can be changed. Do we want to consider this for a milestone?

**Comment by davidfowl** [comment]
Yes, please, put it on preview8 or 7 if there's time in 7.

**Comment by mkArtakMSFT** [comment]
Moving this to 3.1 as the validation of this change is much bigger than the actual change. Also bumping up the cost to account for validation too.

**Comment by davidfowl** [comment]
Can we actually carve out time to do this?

**Comment by rynowak** [comment]
Do we need it at all outside of runtime compilation?

**Comment by davidfowl** [comment]
No. The original concern was new SDK and old target framework. The switch probably needs to be gated on that and then the package that brings in runtime compilation support would set it.

**Comment by mkArtakMSFT** [comment]
Closing as there is no easy way to handle this quickly.

**Comment by pranavkm** [comment]
Let's try this again 👍🏽

**Comment by DamianEdwards** [comment]
Definitely think it's time to make this change in .NET 6. We should do this as early as possible given it has a small potential to break some folks.

**Comment by rynowak** [comment]
But what if just **really like** the compliation context? Preserves made from the compilation context are one of my favorite things to spread on toast 🍞

**Comment by DamianEdwards** [comment]
You'll still be able to enable it, so for those who enjoy compilation context on toast, they can continue to do so!
