### ISSUE TITLE
Built In Components In Blazor

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#50689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In Flutter There Built In Theme And Components Or Is The Name It Widget

Can Blazor Contains A Default Component Library It Could Be Anything
Just To From Blazor Developers Cause There Know What Make Blazor Slow
And The Will Do It With Design That Will Be Easier

And This Will Make Blazor So Popular
And About Fluent It Not Supporting So Much And It's So Hard To Setup It
And It's Gonna Be Awesome When Be Multi Theme Like

Bootstarp (Default)
Fluent
Material

This Will Make Blazor Better 100 Times
Cause Until Now I'm Not Sure What The Good Blazor Libriary And Fastest

### Describe the solution you'd like

Thanks

**Comment by gragra33** [comment]
Microsoft has the [Microsoft Fluent UI Blazor components](https://github.com/microsoft/fluentui-blazor). This sound like what you are looking for.

**Comment by marinasundstrom** [comment]
@wisamidris7 Have you tried MudBlazor? I have been doing that for many of my projects.

**Comment by wisamidris7** [comment]
> Have you tried MudBlazor? I have been using that for many of my projects.

MudBlazor Is Slow In Big Projects

When Making Admin Dashboard
Like Abp
With Tenants, Users, Roles, etc...

There Blazorrise But It's Paid

**Comment by wisamidris7** [comment]
Radzen Is Faster Than MudBlazor But Also Slow

Also This Will Be Good For Blazor

Flutter Is Popular Framework For All Platforms
Also Blazor With Maui Is Supporting All Platforms
But There No Built In Components

This Will Make Blazor Easy For Begginers And For Experts

**Comment by marinasundstrom** [comment]
@wisamidris7 You want Microsoft/Blazor to ship with its own UI component kit?

As I said, Blazor is just the component model on top of Web technology - a tool.

I can’t speak for Microsoft, but I don’t think that it is the goal of Blazor to build a complete UI component stack. They just produce the tools that enable stuff.

However, there is Microsoft’s Fluent UI components for Blazor.

You said that Blazor is slow when using component frameworks like MudBlazor, and Radzen. Is this a major issue for you? Do others feel the same.

You specifically mentioned complex admin UIs and such.

And for what hosting model Server or WebAssembly?

I do share that it might be hard for beginners to choose what component framework they should use.

**Comment by wisamidris7** [comment]
In Server It's So So Fast
But WebAssembly It's Lag

The Render Take 1s for render

I Maked ShouldRender to false and this things and it's still slow

and fast it's not material theme
my app is management dashboard like abp

https://abp.io/

Make A Demo To See What I'm Making
The Demo Is Angluar So This Is Not Blazor
Ok...

**Comment by wisamidris7** [comment]
Or Can You Give Me A Tool Or A Button In Visual Studio 2022

That Help Me Profiling
Benchmarking

For Blazor

**Comment by marinasundstrom** [comment]
@wisamidris7 Are you just running in Debug configuration? 

Publishing the WebAssembly app will build in Release configuration, and then Ahead-of-time (AOT) compile to WebAssembly. That should decrease the size, and improve speed in production.

You can use the built in profiling tools for Blazor Server. Use the browsers Web tools for Blazor WASM. There might be other ways.

**Comment by wisamidris7** [comment]
Thanks
