### ISSUE TITLE
Blazor AddAdditionalAssemblies does not make endpoints available to new Router component

### ISSUE THREAD

**Issue by johnpeeke** [dotnet/aspnetcore#50683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the new AddAdditionalAssemblies api with the MapRazorComponents<App> api, the endpoints in the scanned assembly are not added to the new Router component in .net 8 rc-1. It is still required to add the AdditionalAssemblies to the router component as well.

### Expected Behavior

When using the AddAdditionalAssemblies extension, the mapped endpoints should be made available to the router automatically. The Router component should know about the endpoints added.
![Screenshot 2023-09-13 111144](https://github.com/dotnet/aspnetcore/assets/8165407/aeb20bba-8020-4694-9e80-abf4b7f5788d)
![Screenshot 2023-09-13 111216](https://github.com/dotnet/aspnetcore/assets/8165407/7a85bff9-96e6-42d6-b8e7-9262f8925bf9)

### Exceptions (if any)

If the assemblies are not added to the router as well, the page loads then immediately navigates to a not found page.

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

This may not be a bug but be normal. However, the AddAdditionalAssemblies api states that it maps any pages found, which does not seem to be the case entirely.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This will still be required in .NET 8 and we will think about ways to make this more seamless in the future.
As a way to simplify the current experience, you can define the assemblies list in a constant and refer to that constant from both places in code.

**Comment by johnpeeke** [comment]
> Thanks for contacting us. This will still be required in .NET 8 and we will think about ways to make this more seamless in the future. As a way to simplify the current experience, you can define the assemblies list in a constant and refer to that constant from both places in code.

Thanks for clarifying! We can close this out.
