### ISSUE TITLE
[SignalR-Client-Cpp] Fails in start() when there is no network connection

### ISSUE THREAD

**Issue by hgbutte** [dotnet/aspnetcore#50698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On some computers we have the issue that we cannot establish the SignalR Connection to a local running Signal R Hub when the computer is not connected to any network. Right now we can reproduce the error on a Windows 11 virtual machine.
When the computer is connected to a network (no internet connection) the SignalR Client can establish the connection.

Log of failed connect:
```
[verbose  ] acquired lock in start()
[verbose  ] disconnected -> connecting
[verbose  ] released lock in start()
[info     ] [websocket transport] connecting to: ws://localhost:5500/hubs/xyz?id=C_ANoM79ljBSj2kfpH8URw
[websocket transport] exception when connecting to the server: set_fail_handler: 2: Underlying Transport Error
[error    ] transport could not connect due to: set_fail_handler: 2: Underlying Transport Error
[error    ] connection could not be started due to: set_fail_handler: 2: Underlying Transport Error
[verbose  ] connecting -> disconnected
```

As mentioned here [](https://github.com/SignalR/SignalR-Client-Cpp/issues/174) installation of the Loopback Adapter fixes the problem, but this does not really seem to be a valid solution to us.

From wireshark logs i can see the that an initial Negotiation "POST" gets send to the Hub and is being responded.
But then the client fails to send the "GET" "ws://localhost:5500/hubs/xyz?id=C_ANoM79ljBSj2kfpH8URw" to the Hub.

Any help would be appreciated to find a solution on this.

### Expected Behavior

SignalR connections should be established to locally running hubs without network connection as well.

**Comment by BrennanConroy** [comment]
Have you tried connecting to 127.0.0.1 instead of localhost?
This looks like it could be https://github.com/zaphoyd/websocketpp/issues/244

**Comment by hgbutte** [comment]
It works. Thank you!
