### ISSUE TITLE
Blazor Web App --> NavigationManager doesn't navigate without `forceLoad`

### ISSUE THREAD

**Issue by denmaklucky** [dotnet/aspnetcore#50691]
### Is there an existing issue for this?
I haven't find the existing issues

### Describe the bug

I have an app that was just created using the `Blazor Web App` template.

![image](https://github.com/dotnet/razor/assets/8844526/7c1a5774-b118-4cf4-a70d-c98f4ddef290)

I injected the **NavigationManager** into `Index.razor` in an attempt to navigate to `Weather.razor.`

Although the URL changes, the content does not change.

https://github.com/dotnet/razor/assets/8844526/96dcdb97-7200-435a-ac40-6fa161e5eb03

By the [link ](https://github.com/denmaklucky/blazor-web-app-errors/tree/main/WebAppNavigationManager) below you can find a sample of the project

### Expected Behavior

The **NavigationManager** works like in `Blazor Server Side App` and `Blazor WebAssembly App`, no `forceLoad` needed

### .NET Version
8.0.100-preview.6.23330.14
8.0.100-rc.1.23455.8

**Comment by SteveSandersonMS** [comment]
I think your app doesn't actually have interactive rendering enabled correctly. Are you getting errors in the browser console?

If you install .NET 8 RC1 and create a new project using the template with the default settings and try again, I think it will work correctly. I just tried it and it did so. Can you let us know? Thanks!

**Comment by denmaklucky** [comment]
@SteveSandersonMS  you were absolutely right, after updating .NET 8 RC1 the problem was resolved. Thanks 🤝
