### ISSUE TITLE
ASP .NET 8 RC1 Routing & UseStaticFiles

### ISSUE THREAD

**Issue by Github-Butler** [dotnet/aspnetcore#50707]
breaking change from preview 7 to RC1:
using the page Weather.razor with route wildcard @page "/{weather?}" worked perfectly and the static file /bootstrap/bootstrap.min.css was delivered as expected.
After upgrade to RC1 the static file route /bootstrap/bootstrap.min.css was ignored.

**Comment by Bartmax** [comment]
catchall routes also looks like are having this problem too.

**Comment by Github-Butler** [comment]
Minimal repro project: https://github.com/Github-Butler/Issue50707

**Comment by krompaco** [comment]
I'm seeing same issue going from Preview 7 to RC 1 with no other code changes.

My controller route with this pattern now catches requests for physical files that I'm certain are in the wwwroot folder.

```
app.MapControllerRoute(
    name: "files",
    pattern: "{**path}",
    defaults: new { controller = "Content", action = "Files" });
```

**Comment by javiercn** [comment]
This seems to be caused by the global implicit router running before the static files middlware.

@captainsafia you did fix something in this area recently, didn't you?

**Comment by captainsafia** [comment]
Yes, this issue was resolved in https://github.com/dotnet/aspnetcore/pull/50864. You can try the .NET 8 nightlies in github.com/dotnet/installers to see if that resolves the issue for your scenarios.

**Comment by Github-Butler** [comment]
Problem resolved in ASP .NET Core 8 RC2

**Comment by captainsafia** [comment]
Thanks for following up! Closing this issue now.
