### ISSUE TITLE
Process finished with exit code 139 - .NET 8 RC1

### ISSUE THREAD

**Issue by Zaneris** [dotnet/aspnetcore#50709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Occurs after reaching `app.Run()` starting with `https` on Apple Silicon.

It may occur on other systems but I haven't tested.
Cleaning/trusting the certs with `dotnet dev-certs https` has no effect.

### Expected Behavior

Web app should run and not exit with an error code.

### Steps To Reproduce

- Install .NET 8 RC1 on an M1/M2 mac.
- Create a new Web API.
- Use a launch profile with https in the applicationUrl.
- Run the application.
- Process finished with exit code 139.

### Exceptions (if any)

None.

### .NET Version

8.0.100-rc.1.23455.8

**Comment by danmoseley** [comment]
hi @zaneris. this just means a segfault -- can you please try to get a stacktrace? eg., configure your machine to collect dumps if necessary (not sure whether this is on by default on mac) and then crack it in a debugger.

**Comment by danmoseley** [comment]
docs in this repo may help
https://github.com/dotnet/diagnostics/blob/main/documentation/debugging-coredump.md

**Comment by danmoseley** [comment]
also, can you confirm whether this works OK on preview 7 and if not, on 7.0 ?

**Comment by Zaneris** [comment]
Confirmed works fine on .NET 7, I'll check the last preview.

**Comment by Zaneris** [comment]
Confirmed works in 8.0.100-preview.7.23376.3

**Comment by amcasey** [comment]
Thanks for validating that!  Any luck with the core dump?

**Comment by Zaneris** [comment]
> Thanks for validating that!  Any luck with the core dump?

Haven't had a chance to spend time on that yet, hopefully by end of day.

**Comment by amcasey** [comment]
I didn't have any luck repro'ing on windows.  Are these the right steps?
```
dotnet new webapi
dotnet run --launch-profile https
curl https://localhost:$PORT/weatherforecast
```

**Comment by Zaneris** [comment]
Interesting, now I'm wondering if it's something Rider specific.

<img width="614" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1270698/5fd0cd2b-666b-4a27-9725-8d611259de3e">
<img width="1062" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1270698/d90006f2-0c8c-4907-be90-f4635c633425">

Because it does work fine launching the project from Terminal.
But then it runs fine in Rider with Preview 7.

**Comment by Zaneris** [comment]
I'll close this for now since it appears to be an issue with Rider 2023.2.1 and .NET 8.0.100-rc.1.23455.8 combined rather than purely an issue with ASP.NET.

**Comment by amcasey** [comment]
Thanks for following up!

**Comment by seclerp** [comment]
Hi folks, we are aware of that issue in Rider, you can find a temporary workaround [here](https://youtrack.jetbrains.com/issue/RIDER-98946/Cannot-run-asp.net-https-launch-profile-from-Rider-with-dotnet-8-rc1#focus=Comments-27-8111952.0-0).

**Comment by FM1973** [comment]
The same problem exists in VS 2022 17.8 when resharper installed and dynamic program analysis is turned on!

**Comment by ForNeVeR** [comment]
@FM1973, in case you use .NET 8 RC1, then I believe DPA may trigger this problem. If you disable it, the problem will stop reproducing.

It is currently assumed to be fixed in .NET 8 RC2.
