### ISSUE TITLE
Was Username field really removed in .Net 8 rc-1?

### ISSUE THREAD

**Issue by AntoninJelinekAbsa** [dotnet/aspnetcore#50702]
There is a note about removing Username field from IdentityUser schema in RC-1 thought when I scaffold new database, I still see that field in place. Also checked https://github.com/dotnet/aspnetcore/blob/release/8.0-rc1/src/Identity/Extensions.Stores/src/IdentityUser.cs and it is still there - am I looking at wrong places?
In addition, are there any other schema changes planned for new Identity in .Net 8?

**Comment by halter73** [comment]
Username was removed from the `MapIdentityApi` endpoint, but not from `IdentityUser`. `MapIdentityApi` effectively uses the `Email` passed in during `/register` for both `IdentityUser.Email` and `IdentityUser.UserName`.

We'll update https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#identity to make this more clear.

**Comment by QINGCHARLES** [comment]
Should update the blog post too:
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/
