### ISSUE TITLE
Razor Class Library not rendering/serving static content  (i.e. "_content/{PACKAGE}/file.js") on MACOS

### ISSUE THREAD

**Issue by bwinklesky** [dotnet/aspnetcore#50715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently when you build and run a website on MacOS that's using an RCL, the static web assets for the RCL are not available to the browser.  

### Expected Behavior

Expected behaviour is to render the static files.  

### Steps To Reproduce

Build any app that has an RCL on a Mac.  

### Anything else?

.NET 7.0
VS4Mac

**Comment by javiercn** [comment]
@bwinklesky thanks for contacting us.

Do you experience the same issue when running from the command line?

**Comment by bwinklesky** [comment]
@javiercn Yes, the issue is still present when running from command line, and environment is set to "Development".

**Comment by javiercn** [comment]
@bwinklesky can you provide a minimal repro project?

**Comment by bwinklesky** [comment]
@javiercn 

[WebApp.zip](https://github.com/dotnet/aspnetcore/files/12752959/WebApp.zip)

**Comment by bwinklesky** [comment]
https://github.com/bwinklesky/WebApp

**Comment by javiercn** [comment]
@bwinklesky thanks for the additional details.

https://github.com/bwinklesky/WebApp/blob/main/WebApp/Views/Shared/_Layout.cshtml#L47

Casing is important here, so it should be `RCL/file.js` not `rcl/file.js`. 

ASP.NET Core respects the underlying OS casing policy.
