### ISSUE TITLE
dotnet publish appears to be using an incorrect base container with DN8RC1

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#50718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am publishing my app directly to an Azure Container Registry. This has resulted in a functional app through the preview process of DN8.

Today, I pushed an update to my app and it is apparent that the app is not starting.

I noticed that the publish is using a container identified as 'preview'
```
Building image 'icebg.web.ui' with tags 2023-09-14--18-04-04--1.0.0-preview.18 on top of base image mcr.microsoft.com/dotnet/aspnet:8.0-preview
```
Changing my publish command from --no-self-contained to --self-contained allowed the DN8-RC1 application to start.

I don't know if the container name is a 'red herring' or not, but something is preventing my DN8RC1 application from starting in that base container...

### Expected Behavior

I'd expect that the container chosen in the publish would support RC1

### Steps To Reproduce

```
    - name: Publish tagged UI image
      run: >
        dotnet publish ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj
        --arch x64
        --os linux
        --configuration Azure
        --no-self-contained
        -p:ContainerImageTag=${{ env.unifiedVersion }}
        -p:ContainerRegistry=${{env.containerRegistry}}
        -p:ContainerRepository=${{env.appNameUI}}
        -p:PublishProfile=DefaultContainer
        -p:Version=${{ env.unifiedVersion }}
```

is my github action publish step that produces the non-working container. As above, making the image self-contained repaired the issue.

### .NET Version

DN8-RC1

**Comment by martinstenhoff** [comment]
The preview tags are no longer maintained and you need to use 8.0 since rc 1.

Extract from [announcing-dotnet-8-rc1](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/):

> Issue: https://github.com/dotnet/dotnet-docker/issues/4772 PR: https://github.com/dotnet/dotnet-docker/pull/4817
> 
> In preparation for the GA release of .NET 8, the .NET container images have switched to a new tagging pattern for RC 1 that removes “preview” from the tag name.
>
> In previous preview releases of .NET 8, floating tags were published with the name of 8.0-preview and 8.0-preview-<OS>. These will no longer be maintained starting with the RC 1 release. Instead, you should migrate your tag references to 8.0 or 8.0-<OS>. Making this change will allow for a seamless transition upon the GA release of .NET 8 as these will be the permanent tags > that will be maintained throughout the lifetime of .NET 8.

**Comment by MarkStega** [comment]
I was aware of the tag change, however, I am not specifying the preview image. The docker commands are getting generated by dotnet. I believe that "dotnet publish" is picking the wrong container even though the SDK is .Net 8 RC1 as shown in the last line of this trace:
```
Run dotnet publish ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj --arch x64 --os linux --configuration Azure --no-self-contained -p:ContainerImageTag=[2](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:2)023-09-15--13-59-07--WIP -p:ContainerRegistry=*** -p:ContainerRepository=icebg.web.ui.wip -p:PublishProfile=DefaultContainer -p:Version=2023-09-15--13-59-07--WIP
  dotnet publish ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj --arch x64 --os linux --configuration Azure --no-self-contained -p:ContainerImageTag=2023-09-15--13-59-07--WIP -p:ContainerRegistry=*** -p:ContainerRepository=icebg.web.ui.wip -p:PublishProfile=DefaultContainer -p:Version=2023-09-15--13-59-07--WIP
  shell: /usr/bin/bash -e {0}
  env:
    appNameDS: icebg.web.ds.wip
    appNameUI: icebg.web.ui.wip
    containerRegistry: ***
    images-to-keep: 10
    unifiedVersion: 202[3](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:3)-09-15--13-59-07--WIP
    DOTNET_ROOT: /usr/share/dotnet
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_169[4](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:4)786373238
MSBuild version 17.8.0-preview-23418-03+012[5](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:5)fc9fb for .NET
  Determining projects to restore...
  Restored /home/runner/work/ICEBG/ICEBG/SystemFramework/SystemFramework.csproj (in 344 ms).
  Restored /home/runner/work/ICEBG/ICEBG/SharedUtilities/SharedUtilities.csproj (in 3 ms).
  Restored /home/runner/work/ICEBG/ICEBG/ICEBG.Client/ICEBG.Client.csproj (in 22.33 sec).
  Restored /home/runner/work/ICEBG/ICEBG/ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj (in 22.12 sec).
  Restored /home/runner/work/ICEBG/ICEBG/ApplicationConfigurationServer/ApplicationConfigurationServer.csproj (in 22 ms).
  Restored /home/runner/work/ICEBG/ICEBG/ApplicationConfiguration/ApplicationConfiguration.csproj (in 8 ms).
  Restored /home/runner/work/ICEBG/ICEBG/DataTier/DataTier.csproj (in 8[7](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:7)2 ms).
/usr/share/dotnet/sdk/[8](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:8).0.[10](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:10)0-rc.1.23455.8/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(3[11](https://github.com/MarkStega/ICEBG/actions/runs/6198986051/job/16830593269#step:6:11),5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/runner/work/ICEBG/ICEBG/ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj]
```

**Comment by MarkStega** [comment]
Thanks - Due to an earlier bug @baronfel had me specify the CBI in the csproj. It was months ago and I totally forgot that it was there. I simply removed it and all is well.
