### ISSUE TITLE
.Net 8 RC1 WASM - compatibility - lack of support for older systems

### ISSUE THREAD

**Issue by KubaGluszkiewicz** [dotnet/aspnetcore#50729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After changing from DotNet 7 to DotNet 8 RC1 for webassembly browser project (not blazor), we are unable to run our application on Tizen (Samsung) and WebOS (LG) devices. 
Those devices are serving host environment based on Chromium. usually those are older versions like 85,
WebAssembly portability is crucial feature for us, as we can ship our application to the users on wide range of systems.

After migrating to DotNet 8 RC1 we are not able to instantinate dotnet runtime at all,
we are getting bunch of errors just at the begining of creating dotnet runtime like this:
```
logging.ts:32 MONO_WASM: TypeError: Cannot read property 'mono_wasm_abort' of undefined
    at Object.Module._mono_wasm_abort [as mono_wasm_abort] (http://127.0.0.1:9000/_framework/dotnet.native.js:8:127389)
    at Object.Ll.l.abort (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:214656)
    at w (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:1229)
    at http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201358
    at async http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201217
```

do you have plans to maintain high compatibility for wasm projects in DotNet 8 or it's designed to work only with newest modern browsers?

Also i'm affraid that SIMD support in WASM will be also problem, hopefully we will be able to rebuild using wasm-tools to disable any SIMD operations as older browser doesn't support them.

### Configuration

Tizen SSSP6.5
Chrome 85

### Expected Behavior

WASM Browser should support also older browser deployed on many devices like TV systems.

### Exceptions (if any)

```
logging.ts:32 MONO_WASM: TypeError: Cannot read property 'mono_wasm_abort' of undefined
    at Object.Module._mono_wasm_abort [as mono_wasm_abort] (http://127.0.0.1:9000/_framework/dotnet.native.js:8:127389)
    at Object.Ll.l.abort (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:214656)
    at w (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:1229)
    at http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201358
    at async http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201217
```

### .NET Version

8 RC1

**Comment by guardrex** [comment]
We cover disabling SIMD at https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows#single-instruction-multiple-data-simd.

**Comment by campersau** [comment]
The same issue was also opened in runtime: https://github.com/dotnet/runtime/issues/92117

**Comment by maraf** [comment]
This issue can be closed, as the feature belongs to runtime
