### ISSUE TITLE
Dictionary model binding behaves different with Enum as Key vs Value

### ISSUE THREAD

**Issue by wadeamaral** [dotnet/aspnetcore#50748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Consider the following example:

```
[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{

    [HttpGet]
    [Route("key")]
    public IActionResult KeyTest([FromQuery] Dictionary<TestEnum, string> prop)
    {
        return Ok();
    }

    [HttpGet]
    [Route("value")]
    public IActionResult ValueTest([FromQuery] Dictionary<string, TestEnum> prop)
    {
        return Ok();
    }
}

public enum TestEnum
{
    EnumVal1,
    EnumVal2
}
```

The following requests produce the 200 response and a populated dictionary:

```
/Test/key?Prop[enumval1]=string
/Test/value?Prop[string]=enumval1
```

The following request produces an invalid modelstate with a 400 response:

`/Test/value?Prop[string]=badEnum`

The following request produces an internal server error:

`/Test/key?Prop[badEnum]=string`

The stack trace shows the following error:

```
System.FormatException: badEnum is not a valid value for TestEnum.
 ---> System.ArgumentException: Requested value 'badEnum' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
```

Is there a reason for the difference in binding behavior? Is it possible to have the `Dictionary<TestEnum, string>` produce a model state error instead of throwing a `FormatException`?

**Comment by captainsafia** [comment]
@wadeamaral Thanks for reporting this issue!

It looks like we use a simple converter when binding to the key in a Dictionary-based type ([ref](https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/DictionaryModelBinder.cs,166)) so the exceptions aren't captured into the ModelBinding context. It seems sensible to me that we should try to populate the model state here.

**Comment by captainsafia** [comment]
Closed via https://github.com/dotnet/aspnetcore/pull/50929. Will ship in .NET 9 Preview 1 😲
