### ISSUE TITLE
[Blazor NET.8] Add global option for disable pre-rendering 

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#50744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We are using Blazor for some few sites in our company where we don't need prerendering.
Previous of .NET 8 it was easy to switch it off in using `render-mode="Server"` but now with the new attributes `RenderModeAuto`, `RenderModeServer`, `RenderModeWebAssembly` I need to use the overload which accepts a boolean to turn it off (and sometimes it can be forgotten).

Could we configure this globaly somewhere else? in configure services, or any other place?

### Describe the solution you'd like

Have a global option for disable prerendering for all the components in the app without using the overload of the new RenderMode attributes.

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

You can extend `InteractiveServerRenderMode` to create your own `NonPrerenderedServerRenderMode` and use that everywhere in your app.
