### ISSUE TITLE
Persisting Data Across SSR and Blazor Server

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#50741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is not a bug. I am hoping there is a best-practice answer for this. We have a scenario where a page loads as SSR, but then the interactive Blazor server component takes over. We need to call an API to a secured endpoint from the interactive component. We already have the access token during the SSR call. We create a scoped service and use that to save the access token when the SSR page loads. Then, we can get the access token back from that service in the interactive component to make the calls to the API. Is it ok to assume that a scoped service will stay between a SSR call and the Signal R session. If not, how do you share data between SSR and Signal R session. We saw that we could use the persist pre-render state but not sure if that is a better way. Thanks in advance for help. 

### .NET Version

dotnet8

**Comment by javiercn** [comment]
@darena-pjindal thanks for contacting us.

No, the scope is not shared between the initial SSR request and Blazor Server. Blazor already has a feature to persist prerendered component state (link below) and we are working to make it work on Blazor Web too (no need for the tag helper, it happens automatically).

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-7.0#persist-state-for-prerendered-components

**Comment by darena-pjindal** [comment]
Hello @javiercn - thanks so much for your response. Could you please clarify where we should add the <persist-component-state /> today for a blazor web app, as the index and host page don't exist? Also, it seems that the docs might not be correct for the Webassembly section. There are referring to the _host page here. 
![image](https://github.com/dotnet/aspnetcore/assets/45796558/b3ff92b7-2cda-4ac0-b026-46ec2f75c027)

**Comment by javiercn** [comment]
@darena-pjindal the feature is expected to land in RC2 for Blazor Web.

Those docs are for the implementation before Blazor Web, where the components were hosted on an MVC/Razor pages page.
