### ISSUE TITLE
Render Mode : Auto and Webassembly shows an  error, render mode server works fine

### ISSUE THREAD

**Issue by changingmission** [dotnet/aspnetcore#50754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i enable auto or webassembly render mode from App.razor to both <HeadOutlet @rendermode="@RenderMode.WebAssembly" /> and <Routes @rendermode="@RenderMode.WebAssembly" />, it throws an error "Error: System.InvalidOperationException: Root component type 'App.Server.Components.Routes' could not be found in the assembly 'App.Server'." 

### .NET Version

8.0.0-rc.1.23421.29

**Comment by javiercn** [comment]
@changingmission thanks for contacting us.

Is all the code that you want to run on webassembly (including the Routes component) part of the webassembly project? Otherwise, it won't work!

**Comment by changingmission** [comment]
> @changingmission thanks for contacting us.
> 
> Is all the code that you want to run on webassembly (including the Routes component) part of the webassembly project? Otherwise, it won't work!

Yes, we want to run the whole app in Auto mode, but it only runs once then when it switches to Wasm mode it shows the error above.

**Comment by javiercn** [comment]
@changingmission can you provide a minimal repro project that demonstrates the issue?

**Comment by changingmission** [comment]
Please check this out: https://github.com/changingmission/BlazorApp5

**Comment by changingmission** [comment]
> Please check this out: https://github.com/changingmission/BlazorApp5
Hello,
Is there any problem or am I doing it wrong?

**Comment by SteveSandersonMS** [comment]
The error is happening because you've marked `<Routes>` with WebAssembly rendermode, but that component isn't in your WebAssembly project. You'll need to move `Routes.razor` into the `BlazorApp5.Client` project, along with other components that it references such as `Layout.razor`.

**Comment by changingmission** [comment]
> The error is happening because you've marked `<Routes>` with WebAssembly rendermode, but that component isn't in your WebAssembly project. You'll need to move `Routes.razor` into the `BlazorApp5.Client` project, along with other components that it references such as `Layout.razor`.

Thank you, it works!
