### ISSUE TITLE
HttpContext.Response.Headers setter changes casing of HTTP header

### ISSUE THREAD

**Issue by johncrim** [dotnet/aspnetcore#50763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The existing issue for this is https://github.com/dotnet/aspnetcore/issues/27419 . I have a new problem related to this, so I think it should be re-evaluated:

The [SourceMap](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/SourceMap) header cannot be added using
```cs
httpContext.Response.Headers.Add("SourceMap", sourceMapPath);
```

Doing so results in a header like:

```
Sourcemap: js/main.js.map
```

which is not understood by browser devtools (Chrome or Chromium Edge). I need a way to use the specific casing.

I understand that the naming of this header is not consistent with most headers - if it were defined as `Source-Map` everything would work fine; also ASP.NET allows `X-SourceMap` but that doesn't appear to work in my tests.

This could be fixed either by:
a. Just allowing `SourceMap` to not be converted - which kicks the issue down the road to the next time it causes a problem.
b. Change ASP.NET behavior to only change casing for standard headers where the format is well known.

### Expected Behavior

```cs
httpContext.Response.Headers.Add("SourceMap", sourceMapPath);
```

results in header:

```
SourceMap: js/main.js.map
```

### .NET Version

7.0.401

### Anything else?

```xml 
<TargetFramework>net6.0</TargetFramework>
```

**Comment by marinasundstrom** [comment]
RFC 7540: Hypertext Transfer Protocol Version 2 (HTTP/2)

```
Just as in HTTP/1.x, header field names are strings of ASCII
characters that are compared in a case-insensitive fashion.  However,
header field names MUST be converted to lowercase prior to their
encoding in HTTP/2.  A request or response containing uppercase
header field names MUST be treated as malformed 

([Section 8.1.2.6](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.6)).
```

So headers should be treated as case insensitive - according to standard - but I get that it can be annoying that ASP.NET Core tries to normalize that name.

BTW. ``X-`` is not longer required for private headers.

https://tonyxu.io/blog/http-deprecate-x-prefix/

**Comment by amcasey** [comment]
> which is not understood by browser devtools (Chrome or Chromium Edge). I need a way to use the specific casing.

Do I understand correctly that Chrome does accept `SourceMap` but does not accept `Sourcemap`?  If so, that sort of sounds like a bug on their end.  (Frankly, they ship more often than we do and their updates are easier to adopt, so a fix on their end would probably save you time as well.)

If they have some solid rationale for requiring this (in opposition to the spec?), then I guess we could consider special-casing this one header to have a specific output name, but I doubt we'd move everything to case-sensitive to address this issue.

**Comment by amcasey** [comment]
As an aside, I understood adding an annotation like `//$ sourceMappingURL=...` to be the most common approach.

**Comment by amcasey** [comment]
I'm not particularly familiar with the chromium code, but this looks relevant: https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/node_modules/source-map-support/source-map-support.js;drc=b693eb34d552b895d48e35e20e34a9998cc59db8;l=159

MDN [claims](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader) `XMLHttpRequest.getResponseHeader` is case-insensitive.

**Comment by amcasey** [comment]
Based on the most superficial reading of this code, the header collection appears to be case-insensitive: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/network/http_header_map.h;l=61;drc=49a952fddb576b129aab7c6b333513b0d9e22adf

**Comment by johncrim** [comment]
Thank you for the comments, @amcasey and @marinasundstrom .

I can confirm that the headers don't work in my testing (eg Chrome and Edge dev tools don't report source maps when I set the `SourceMap` header) but I don't have a simple-enough way to correct the header casing to determine if "fixing" the casing would make the dev tools work. In other words, it's possible that this is an HTTP/2+ issue in the browsers that wasn't caught, or that the header is no longer supported but the docs weren't updated.

The annotation at the end of the js file does work (`//$ sourceMappingURL=...`), and that's what I'm going with - certainly the easiest fix. But I thought I'd report this as an issue for posterity/to be a helpful member of the community; and b/c I couldn't comment on the earlier issue about ASP.NET changing the casing of the header.

**Comment by adityamandaleeka** [comment]
Thanks @johncrim. I'm sure this will be useful to anyone who hits this issue in the future.
