### ISSUE TITLE
[Regression] Error in HtmlRenderer when upgrading to net8 RC1 

### ISSUE THREAD

**Issue by AbstractionsAs** [dotnet/aspnetcore#50783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to net8 RC1, the `Microsoft.AspNetCore.Components.Web.HtmlRenderer` contructor started throwing an exception, stating that no `ICascadingValueSupplier` could be resolved from the container.

The `IServiceProvider` from the containing blazor application is used.

### Expected Behavior

The constructor should not throw an exception

### Steps To Reproduce

- Create a service that accepts an `IServiceProvider`, and an `ILoggerFactory `from dependency injection
- Instantiate `HtmlRenderer `using theese values

```csharp
public class BugExampleService : IDisposable, IAsyncDisposable
{

    private readonly HtmlRenderer renderer;

    public BugExampleService(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
        => renderer = new HtmlRenderer(serviceProvider, loggerFactory);
    
    public void Dispose()
       => renderer?.Dispose();
    public ValueTask DisposeAsync()
        => renderer?.DisposeAsync() ?? ValueTask.CompletedTask;

}
```

### Exceptions (if any)

System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.AspNetCore.Components.ICascadingValueSupplier' from root provider. at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) at Microsoft.AspNetCore.Components.RenderTree.Renderer..ctor(IServiceProvider serviceProvider, ILoggerFactory loggerFactory, IComponentActivator componentActivator) at Microsoft.AspNetCore.Components.Web.HtmlRenderer..ctor(IServiceProvider services, ILoggerFactory loggerFactory)

### .NET Version

8.0.100-rc.1.23463.5

### Anything else?

This worked fine in Preview 7

**Comment by AbstractionsAs** [comment]
Ok, so I figured this one out.
While I'm not sure what changed from preview 7 to RC1, this can be soved by creating a scope from the service provider, and sending _the scopes_ service providerto the renderer, rather than the original service provider

```csharp
public class BugExampleService : IDisposable, IAsyncDisposable
{
    private readonly HtmlRenderer renderer;
    private readonly IServiceScope scope;

    public BugExampleService(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
    { 
          scope = serviceProvider.CreateScope();
          renderer = new HtmlRenderer(scope.ServiceProvider, loggerFactory);
    } 

    public void Dispose()
    {
         renderer?.Dispose();
         scope?.Dispose();
    }

    public ValueTask DisposeAsync()
    {
        await renderer?.DisposeAsync() ?? ValueTask.CompletedTask;
        scope?.Dispose();
    }    
}
```

**Comment by TroelsL** [comment]
@AbstractionsAs: This problem will also occur if you register HtmlRenderer as a Singleton in your service builder. Simply changing to Transient fixed it for me.
