### ISSUE TITLE
Remove usage of InterceptorsPreview feature after updating to 8.0 RC2 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#50798]
Once the aspnetcore repo has been updated to use 8.0 RC2 SDK, the usage of the `InterceptorsPreview` feature can be removed from the Identity project. See the changes in https://github.com/dotnet/aspnetcore/pull/50797 that indicate what needs to be removed.

**Comment by captainsafia** [comment]
The repo has been updated to use `InterceptorsPreviewNamespaces` everywhere.
