### ISSUE TITLE
Hot Reload Support For Blazor

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#50796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In Net8.0

Blazor Should Come Powerfully

So Sometimes The Hot Reload Works And Sometimes Not Working Required Restart

So Can Blazor Support Hot Reload When Editing C#
And Also When Editing Loop Or Switch In Razor Required Restart App

```razor
@foreach (var item in item)
{
...
}
@switch (value)
{
...
}
```
Also When Editing C# Code

```razor
@code{
public void SomeMethod()
{
// SomeCode
}
}
```
Or
SomeCompoent.razor.cs
```c#
public parial class SomeComponent
{
public void SomeMethod()
{
// SomeCode
}
}
```
When I Was Working In MVC The Hot Reload Is Fast The Project Takes 8 seconds To Build

In Mvc Half Second And Reload Done So Can You Use Same Thing In Mvc That Hot Reload Even If I Edit C#

### Describe the solution you'd like

The Soultion Is To Make Blazor Hot Reload Working
Cause Working With Blazor Is Not Quickly I Editied Word In C#

Require Restart

Big Apps Need To Restart Thounds Times In One Day
And When Project Takes 8 seconds To Open
With Webassembly 14 seconds

### Additional context

Thanks For Your Attention

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wisamidris7.
@tmat can you please look into this? Thanks!

**Comment by wisamidris7** [comment]
Are You Sure Hot Reload Will Be Added In Net8.0

Or Not

**Comment by tmat** [comment]
I don't see any issues when editing foreach and switch statements. Please provide a repro project and steps to reproduce the problem.

**Comment by wisamidris7** [comment]
I Mean Why I Restart Application
I Have 5 Assemblies And 287 Component
