### ISSUE TITLE
Missing .NET 8 RC Version for `Microsoft.AspNetCore.App.Runtime.win-arm`

### ISSUE THREAD

**Issue by melotic** [dotnet/aspnetcore#50791]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

It seems that the runtime for win-arm (`Microsoft.AspNetCore.App.Runtime.win-arm`) was not properly released with .NET 8, the latest version for it is [8.0.0-preview.4.23260.4](https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.win-arm/8.0.0-preview.4.23260.4), but other runtimes, like `linux-x84`, have versions [8.0.0-rc.1.23421.29](https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.linux-x64/8.0.0-rc.1.23421.29)

### Expected Behavior

There is a version `8.0.0-rc.1.23421.29` for `Microsoft.AspNetCore.App.Runtime.win-arm`

### .NET Version

8.0.0-rc.1.23421.29

**Comment by BrennanConroy** [comment]
Windows ARM32 support was dropped a while ago, we just hadn't removed it from our build until a recent 8.0 preview.

Windows ARM64 is supported and has the https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.win-arm64/8.0.0-rc.1.23421.29 package.

All I can find in reference to the dropped support is in https://github.com/dotnet/runtime/discussions/71042, maybe there is a post somewhere else though.
