### ISSUE TITLE
Section outlet doesn't update when section content is rendered with streaming rendering

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50804]
Repro steps:

- Install .NET 8 RC1
- Create a Blazor Web App
- In MainLayout.razor add a `SectionOutlet` in the top row: 

```razor
<div class="top-row px-4">
    <SectionOutlet SectionName="top-row" />
    <a href="https://learn.microsoft.com/aspnet/core/" target="_blank">About</a>
</div>
```

- In Weather.razor add a `SectionContent`:

```razor
<SectionContent SectionName="top-row">
    @forecasts?[0].Summary
</SectionContent>
```

- Run the app and browse to the weather page

Expected result: The weather forecast summary for the next day renders in the top row.
Actual result: The top row is empty.
Workaround: Disable streaming rendering on the weather page.

**Comment by SteveSandersonMS** [comment]
Thanks for filing this. We did intend to support this, and have a test implying that we do support it, but the solution we had (and what the test covered) was only if the streaming content came from a child component and wasn't going *directly* into the `SectionContent`.

I've implemented a fix at https://github.com/dotnet/aspnetcore/pull/50843
