### ISSUE TITLE
Blazor Server architectural concerns

### ISSUE THREAD

**Issue by denisbredikhin** [dotnet/aspnetcore#50808]
Hello everyone,

I apologize in advance if this is not the correct place for my question, but I didn't find any better one. Feel free to move this issue if needed.

Or company successfully developing our Supervisor application with Blazor Server.
It is quite a complex application: with real-time updates and customization possibilities. Customization possibilities mean that our partners can add new UI parts into it or even replace existing ones with the customer-specific versions.
And all this is possible with the help of Blazor!

However, we've faces with some conceptual/architectural issues related to Blazor Server, and that's the reason of this issue creating. We would like to know the position of Microsoft Blazor team related to these questions.

1. Unhandled exception in non-main thread 

Currently when we host Blazor Server application in Kestrel webserver and we have code that throws unhandled exception in ~~non-awaited async method~~ code called using `ThreadPool.QueueUserWorkItem` - it crashes the whole webserver.
We think this is fully normal behavior for console and GUI apps, but quite strange for webserver.
As I've mentioned, our application is quite complex and contains a lot of code from 3rd parties and from the partners. 
Our partners often have less experienced developers (more "citizen developers") and they complain that Blazor Server "punishes" them too strongly for the bad code.
As we know, in other development stacks (Java) it is designed differently.

2. JSDisconnectedException

Currently this exception is thrown every time when web socket is already disconnected, by any reason, and when we perform some communication with JS runtime.
This exception is not thrown to end-user, but it clogs log files and hinders debugging.
In a complex application with a lot of third-party components it is almost impossible to know which code will perform communication with JS runtime.
As a result, if we want to avoid this exception, we need to add try..catch to all the places of our code...

3. Unhandled exception in service Dispose prevents other services from disposing 

This issue is already posted to GitHub and it seems it is accepted as a bug:
https://github.com/dotnet/runtime/issues/86426

But I want to mention it here too, because for us it is more a part of more global concerns I'm explaining here.
Because our application is customizable, it means that our partners can add their specific services in their version of the application.
And if they do not add try..catch to all the Dispose methods of all their services, this can prevent the disposal of any of our standard services, which can lead to very difficult to find issues.
For example, we had a service that registers (and unregisters) every user in some kind of "users registry". Because of this issue we had "zombie users" in this registry...
This issue is even more dangerous in combination with the previous one (JSDisconnectedException).
If you dispose any 3rd partly components in your service, you can't know if they do some JS runtime communication.

As a conclusion, each of these issues separately can be not very critical, but in combination they give impression of the certain "fragility" of Blazor Server.

**Comment by denisbredikhin** [comment]
It appears that my description of the 1st issue was not fully correct.
Server crashes when there is exception inside the code, called using ThreadPool.QueueUserWorkItem.
This can happen in some old code.
We had some other situations when server crashes, but for now we can't reproduce them.

**Comment by danroth27** [comment]
> Unhandled exception in non-main thread: Currently when we host Blazor Server application in Kestrel webserver and we have code that throws unhandled exception in code called using `ThreadPool.QueueUserWorkItem` - it crashes the whole webserver.

I believe this is expected behavior. Can you use `Task.Run` instead?

**Comment by davidfowl** [comment]
Right, the behavior is consistent (it doesn't different depending on the type of application).

**Comment by denisbredikhin** [comment]
@danroth27 @davidfowl Thanks for your answers.

Maybe technically it is correct behaviour.
But I'm talking more about the ability of Blazor Server playing a role in the frontend framework.

In any Frontend framework that is executed on client-side any exception crashing the runtime is a problem of one single client.
But in Blazor Server it is not like this - any such exception crashes the whole server.
Because of this, the requirements to the quality of frontend code in Blazor Server is much higher - and this is what I've called "fragility" in my post.

If your application uses a lot of Third-party libraries, you can't know if any of them uses ThreadPool.QueueUserWorkItem (or any other dangerous techniques that I've mentioned). And with a real client-side framework you pay for it with one crashed client, while in Blazor Server - with crashed server (= all clients crashes).

And I'm wondering if there is something that Blazor Server team can improve in this.

**Comment by davidfowl** [comment]
> And I'm wondering if there is something that Blazor Server team can improve in this.

No that I'm aware of. This is a thread pool API.

cc @stephentoub is there anything that controls this behavior runtime wide?

**Comment by stephentoub** [comment]
> is there anything that controls this behavior runtime wide?

https://github.com/dotnet/runtime/issues/42275 tracks adding an API for this.
cc: @jkotas, @agocke

**Comment by davidfowl** [comment]
@denisbredikhin you can follow the tracked issue linked above.

**Comment by danroth27** [comment]
Reopening as I'm still investigating the JSDisconnectedException issue.

**Comment by danroth27** [comment]
I've opened #53571 to track the `JSDisconnectedException` handling issue. Closing this issue as all the subissues are now separately tracked.

**Comment by denisbredikhin** [comment]
> @denisbredikhin you can follow the tracked issue linked above.

As I understand this solution will allow to ignore unhandled exceptions from ThreadPool.QueueUserWorkItem, but won't it leave the runtime in inconsistent state? 
For me the best solution would be to treat such exceptions as all other unhandled exceptions - terminate the circuit where it happened, and keep other circuits untouched. Would it be possible to achieve with the new API? 
@davidfowl

**Comment by davidfowl** [comment]
> Would it be possible to achieve with the new API?

There's no connection between this API and the Blazor circuit.
