### ISSUE TITLE
[Blazor] Please provide/expose current CSS identifier for CSS isolation

### ISSUE THREAD

**Issue by macias** [dotnet/aspnetcore#50820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

CSS isolation is great but even with `::deep` has its limits. First of all `::deep` break component isolation. See: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0#child-component-support

The parent has to know how the child is composed and target specific element, like `<h1>`. This is no good, because now both components have hardcoded dependency.

Currently I am not aware of any method of passing CSS class as parameter to child component **and** preserving child isolation (logic one, not CSS) **and** preventing leaking to any descendants. The only way I know is using global CSS class but this of course is far from CSS isolation.

### Describe the solution you'd like

Please provide CSS identifier provider so parent could pass CSS class like regular parameter. Something like this:

Parent.razor:
```
@page "/parent"

<div>
    <h1>Parent component</h1>

    <Child CssClass='@cssId("primary-text")'/>
</div>
```
Parent.razor.css:
```
.primary-text { 
    color: red;
}
```
Child.razor:
```
<h1 class="@CssClass">Child Component</h1>

@code
{
  [Parameter] public string CssClass{ get; set; } ="";
}
```

There is more code, true, but the class does not leak to descendants, and the fact child component (here) uses "h1" tag is isolated from the parent (i.e. parent does not have to know how the child is built).

**Comment by javiercn** [comment]
@macias our thinking in this area is reflected [here](https://github.com/dotnet/razor/issues/7606)
