### ISSUE TITLE
AspNetCore.App runtime 6.0.21 uninstalls version 6.0.20

### ISSUE THREAD

**Issue by Matheos96** [dotnet/aspnetcore#50827]
### Description

We have just found an issue where installing, in this case, AspNetCore.App runtime 6.0.21 causes the older 6.0.20 to be uninstalled. We were led to believe that runtime versions should be able to live "side by side", independently of each other. This "replacment" has happened twice, once when manually installing AspNetCore.App 6.0.21 through .exe/.msi installer and once when the AspNetCore.App 6.0.21 runtime (annoyingly) has been automatically installed through Microsoft Update (We really don't like that this can even happen)...
Getting a newer version of AspNetCore runtime in itself is not an issue, though the issue is when it replaces the old version, a version which has its dependency of NetCore.App installed, with a newer version which does **not** come with a matching/valid NetCore.App runtime version. 
In this case, we have all three runtimes (NetCore.App, AspNetCore.App, WindowsDesktop.App) all at 6.0.20. Everything works fine until the new AspNetCore.App 6.0.21 runtime is installed (in any way, automatically or manually) and **replaces** the old 6.0.20 runtime. This new version of AspNetCore.App requires a newer version of NetCore.App (>=6.0.21) which we now suddenly don't have installed and it does not come bundles with an automatic update or a manual install (disregarding hosting bundle).

If this issue should start happening to our customers then we would have a bigger issue. We can't expect them to be able to figure out when an automatic MU update has installed and replaced a patch version of a runtime causing this "mismatch" scenario, let alone how to fix it. Because of that we were, this far, planning on forcing our application to use the **specific runtimes** that we **know** should be installed, as we are installing them ourselves through our installer. With this new revelation that our installed runtimes can vanish, that "fix" may no longer be an option.

What is the expected behaviour? Is this a bug? If not, what would be the recommended way of handling this scenario for us? As mentioned, we are installing all three runtimes ourselves in our installer. Our application should be fine running on any 6.0.X runtime as long as all the runtime dependencies are installed for sure. Ideally and for simplicity, we would want to rely on our installed runtimes being present after installation, even if new runtimes were installed automatically/manually.

### Reproduction Steps

Have AspNetCore.App runtime version 6.0.20 installed (and no newer). Install version 6.0.21 through installer. ---> Removes version 6.0.20. 

Installing the old 6.0.20 BACK after the replacement does allow them to work side by side...

### Expected behavior

Both versions should be able to live side by side?

### Actual behavior

The older patch version, 6.0.20, is removed and replaced by 6.0.21.

### Configuration

Windows x64

**Comment by mkArtakMSFT** [comment]
Publishing self-contained for now seems to be the option which will work for you. We do plan to address the other issue that you've mentioned, so hopefully that will help you in the future: https://github.com/dotnet/aspnetcore/issues/49562
