### ISSUE TITLE
URL for "/_framework..." flashes briefly in browser address bar when using streaming rendering & enhanced form handling with redirects in Blazor

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#50822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a Blazor component page with streaming rendering enabled, that contains a component with an HTML form with enhanced form handling enabled via `data-enhance`, that upon handling a POST does a redirect using `NavigationManager.NavigateTo` to the same or another Blazor page in the app, the address bar in the browser briefly displays a "/_framework..." URL during the enhanced navigation/form redirect processing.

### Expected Behavior

No framework URL is displayed in the browser address bar during redirect handling with enhanced navigation and streaming rendering enabled.

### Steps To Reproduce

Create a new Blazor web application with default settings then add a new component *SayHelloForm.razor* to the project with the content below. This is a form with enhanced handling with an async `onsubmit` handler that does a redirect back to the current URL (using query string for state, somewhat classic Post-Redirect-Get pattern). Put an instance of this component in *Home.razor* and run the app.

```razor
@using Microsoft.AspNetCore.WebUtilities

@inject NavigationManager Navigation

@if (!string.IsNullOrEmpty(Message))
{
    <p class="text-success fw-bold">@Message</p>

    <form method="post" data-enhance @formname="sayhello" @onsubmit="HandleFormSubmit">
        <label>
            Name: <input type="text" name="name" />
        </label>
        <button type="submit">Say Hello</button>
        <AntiforgeryToken />
    </form>
}
else
{
    <p>loading...</p>
}

@code {
    [SupplyParameterFromQuery]
    public string? Message { get; set; }

    [SupplyParameterFromForm]
    public string? Name { get; set; }

    protected override async Task OnInitializedAsync()
    {
        // Force streaming
        await Task.Delay(1000);

        Message ??= "Welcome to your new app.";
    }

    private async Task HandleFormSubmit()
    {
        // Force streaming
        await Task.Delay(500);

        var message = "";

        if (!string.IsNullOrWhiteSpace(Name))
        {
            message = $"Welcome to your new app {Name}";
        }

        var uri = new Uri(Navigation.Uri);
        var query = QueryHelpers.ParseQuery(uri.Query);
        if (!string.IsNullOrEmpty(message))
        {
            query[nameof(message)] = message;
        }
        else if (query.ContainsKey(nameof(message)))
        {
            query.Remove(nameof(message));
        }
        var destination = QueryHelpers.AddQueryString(uri.GetLeftPart(UriPartial.Path), query);

        Navigation.NavigateTo(destination);
    }
}
```

### Exceptions (if any)

None

### .NET Version

8.0.100-rc.2.23468.1

### Anything else?

The `opaque-redirect` URL can be seen in the browser tools navigation window below. The actual problematic behavior though is the fact this URL appears in the browser address bar despite this redirecting back to a Blazor page in the same app.

<img width="597" alt="image" src="https://github.com/dotnet/aspnetcore/assets/249088/6f2b2ca8-4d83-4598-8be0-6411a50e7ddc">

**Comment by SteveSandersonMS** [comment]
We discussed in triage. The way the URL changes during this navigation ("flashes") is a consequence of the design we put in for security, i.e., going through an opaque redirect to avoid disclosing extra info to the client. While the URL flashing isn't ideal, it doesn't seem problematic enough to warrant redesigning around this security area. Since there's been no feedback from the community, we're confident it's not really distressing many others so aren't planning to change it. We could reconsider if there's more feedback.
