### ISSUE TITLE
Generate Page classes as sealed

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#5083]
None of the virtual/overriden properties or methods on a Page are inlinable (as they are virtual); if the generated Page was `sealed` they would be.

The non-inlinablity causes crazy call counts for moderate sized pages e.g.

For 9k requests of a Razor Page

![image](https://user-images.githubusercontent.com/1142958/44684663-8f629980-aa41-11e8-9bb7-5ee0387ed2b2.png)

![image](https://user-images.githubusercontent.com/1142958/44684807-eec0a980-aa41-11e8-8dce-36dbd956aa1a.png)

/cc @rynowak @davidfowl

**Comment by pranavkm** [comment]
We got rid of the instrumentation but in a separate PR. My concern with this change is that we might be setting ourselves up for additional work (with either a way to enable or disable this behavior) if this breaks a user scenario. It's an easy cop out, but we do the right thing with the generated types in RazorComponents and perhaps the answer would be to recommend it going forward if perf is a concern. Thoughts @danroth27 \ @rynowak ?

**Comment by Eilon** [comment]
@mkArtakMSFT / @pranavkm - is this a PRI-0 bug? And is it in the correct milestone?

**Comment by benaadams** [comment]
Computer says yes ;)

Breaking change has to be in a major?

**Comment by Eilon** [comment]
Computah sez no 😄 

But yes a breaking change would need to be in 3.0, but probably in a particular preview, not the 3.0.0 RTM milestone.

**Comment by pranavkm** [comment]
cc @NTaylorMullen 

Are there any reasons not to do this? Given that this is a breaking change + a change in rzc, I'd prefer we tackle this sooner (preview6).

**Comment by rynowak** [comment]
I'm ok with us doing this for 3.0 MVC + an Announcement.

**Comment by NTaylorMullen** [comment]
I definitely think this is the right thing to do, and better sooner than later (preview6). That being said, when we do this we'll want to add a parser option to opt-out.

**Comment by rynowak** [comment]
If we add an option it needs to be in the language, not in the compiler.

**Comment by rynowak** [comment]
I'm thinking we can do this without an option if it's limited to MVC's scenarios.

**Comment by benaadams** [comment]
Pages are sort of the final result; does anyone compile the razor and then derive from them?

**Comment by NTaylorMullen** [comment]
> if it's limited to MVC's scenarios.

If it's limited to only MVC scenarios then I'm fine with that as well.

**Comment by rynowak** [comment]
> Pages are sort of the final result; does anyone compile the razor and then derive from them?

If Razor (in general) is involved, then you always have to answer **every** "does someone" question with yes. Folks remix the generated output of Razor in lots of ways that we don't anticipate or document. This is why I want to try and limit this to MVC's scenarios if possible.

**Comment by mkArtakMSFT** [comment]
Closing as we're concerned regarding the breaking change at this point.
