### ISSUE TITLE
Add  data-nosnippet in blazor-error-ui

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#50840]
We are currently working on updating the Blazor template. It is worth adding ``data-nosnippet`` in MainLayout for ``id="blazor-error-ui"`` to prevent robots from indexing the content.

```razor
<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>
```

It should look like this:
```razor
<div id="blazor-error-ui" data-nosnippet>
    An unhandled error has occurred.
    <a href="#" class="reload" rel="nofollow">Reload</a>
    <a href="#" class="dismiss" rel="nofollow">🗙</a>
</div>
```

Doc:
https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag

I can prepare a PR.

**Comment by javiercn** [comment]
@Alerinos thanks for contacting us.

Sounds reasonable I think, but it's not something we are likely to take at this stage for 8.0

**Comment by javiercn** [comment]
I'll let other folks chime in.

**Comment by campersau** [comment]
Reference: https://github.com/dotnet/aspnetcore/issues/46289#issuecomment-1407800063

**Comment by guardrex** [comment]
For now, I'll add a remark on this to our Blazor *Error Handling* article.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/51543
