### ISSUE TITLE
DotNet 8 rc breaks UsePathBase for Blazor Webassembly calling api methods on the server in visual studio

### ISSUE THREAD

**Issue by Mike-Wodarczyk** [dotnet/aspnetcore#50844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the standard blazor app created in Dot Net 7, I changed the URL path by adding UsePathBase("/SomePath") on the server and  <base href="/SomePath/" /> in the blazor client index.html.  That all works fine in Dot Net 7.  I can get to all pages including the "Fetch Data" by adding /SomePath to the end of the URL.

After migrating to Dot Net 8 - preview 6 it also worked.

Updateing to Dot Net 8 RC the "Fetch Data" url stops working when running from Visual Studio.  This is the bug.  An API call that blazor makes back to the server is not routing to the controller anymore.  This code WILL work when I deploy it to production running under IIS.  I think this is because IIS is stripping the "/SomePath" from the URLs before passing them to my project.

There is a "workaround".  If I change the [Route("[controller]")] in the controller to [Route("SomePath/[controller]")] then the api call starts working again in Visual Studio.  This code, however, wont work in production running under IIS.

### Expected Behavior

After changing the base path for an ASP.net project running blazor in the client, an API calls made from blazor back to the server  should route to the controller with just the [Route("[controller]"] defined on the controller

### Steps To Reproduce

This repo: https://github.com/Mike-Wodarczyk/ExampleOfUsePathBase/tree/dotnet_8_rc
has the dot net 8 converted version that shows the bug.  Navigate to the "Fetch data" page to see the issue.

The same code in the dot net 7 master branch: https://github.com/Mike-Wodarczyk/ExampleOfUsePathBase/tree/master
works. 

### .NET Version

8.0-rc

**Comment by captainsafia** [comment]
@Mike-Wodarczyk I believe the isuse you are running into will be resolved via https://github.com/dotnet/aspnetcore/pull/50864.

In the meantime, it should work if you manually call the following middlewares in your app:

```diff
app.UsePathBase("/SomePath");

app.UseHttpsRedirection();

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();

+ app.UseAuthentication();
+ app.UseAuthorization();
+ app.UseAntiforgery();
```
