### ISSUE TITLE
How are we doing in the repo? -- spot check

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspnetcore#50850]
![image](https://github.com/dotnet/runtime/assets/6385855/bd3fe7e2-61e5-477f-af0f-980a62ab3d04)

It's midyear between our surveys and we'd like to hear from you how we're doing.

<edit - removed link>

If you are reading this, we'd welcome your input. There's only one question so it should take just seconds. But we'd also welcome your suggestions in the optional text box as well. 

-- dotnet/aspnetcore maintainers

**Comment by danmoseley** [comment]
As I noted in the runtime repo equivalent of this issue, if you're less than happy we'd particularly appreciate some comments in the box!

For some reason they have far more responses so far than we do in this repo. We'll leave this up for a week or two -- hoping to get enough that it's statistically comparable with the spring. How are we doing in here relative to February?

**Comment by danmoseley** [comment]
cc @dotnet/aspnet-community-triagers in case any of those folks wish to do it and haven't. :)

**Comment by danmoseley** [comment]
for this one

> "I'd like to not feel so stupid when asking a (what seems to others to be an obvious) question. And I'd like to think I'm not wasting their time. "

It's really important to me that we have a community here that doesn't make anyone feel that way. It'd be great if anyone feels comfortable sharing examples of this, either here or to the email in my profile. We'd like to make changes if we can to do better.

**Comment by danmoseley** [comment]
for this one

> "Split Blazor into it's own repo. The number of issues, PRs, and discussions around Blazor drowns out anything else. I think the frontend community could use it's own space."

@mkArtakMSFT what are your thoughts - I'm guessing this came up in the past. Breaking into two repos while it make make communities more cohesive would bring numerous disadvantages as well, such as new codeflow edges.

**Comment by mkArtakMSFT** [comment]
> "Split Blazor into it's own repo. The number of issues, PRs, and discussions around Blazor drowns out anything else. I think the frontend community could use it's own space."

Blazor is part of ASP.NET Core and it's integrated into the framework so much, that it makes no sense (neither its feasible) to move it out into a separate repo.
