### ISSUE TITLE
AuthenticationState should detect changes to cookie states outside Context

### ISSUE THREAD

**Issue by ThinkElevenDave** [dotnet/aspnetcore#50858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

After a user logs in and the respective authentication cookie is set (containing claims, etc.) they can navigate around the Blazor Server app and any cookie claim reads are handled via AuthenticationStateProvider. 

However, if any changes are made to the user's authentication cookie (e.g. deleted via the user (e.g. accidental/deliberate misuse), via the browser, or via a plug-in) then the respective user can still authenticate/navigate around the application until the app is reloaded.

I completely understand that as an SPA, AuthenticateState is hydrated via user context when the Blazor app loads.  However this means that the data held in AuthenticateState is potentially inaccurate if any cookie changes occur.

It appears that multiple devs are encountering similar challenges (via StackOverflow/GH Issues) and are attempting to use workarounds such as:

  1. Implementations of `RevalidatingServerAuthenticationStateProvider` (AFAIK this doesn't help because AuthenticateState inherits from this).
  2. `NavigationManager NavigationOptions.ForceLoad` property set to true on redirects (works but has overhead and slows the app down from a UI/UX perspective).
  3. A "cookie refresh" API controller call on a timer that can return data to trigger a log out page redirect if authentication fails.

### Describe the solution you'd like

Is there any way to enhance AuthenticateStateService to provide a mechanism to automatically/periodically/manually refresh AuthenticationState without having to reload the app/page (reload context)?

**Comment by javiercn** [comment]
> Is this possible without refreshing the app (reloading context) on each check? If so, can Blazor Server update the user's context claim (e.g. cookie) without an app reload/refresh occurring? I am assuming not because [this documentation states](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-7.0):

No, the cookie can't be updated without an HTTP request, for which there isn't any.

> This is the bit I'm least familiar with as I'm new to SPA's. Others report that updates to the context are lost if the application is reloaded because the underlying cookie is not being updated. We've implemented a Blazor timer that repeatedly calls an API endpoint to re-validate the user's context and logs out the user if anything seems amiss. I assume based on your reply that there's nothing in-built that already can provide this type of check?

That is correct. Depending on what auth solution you use you can take different approaches. For example, within identity, you could check the user database to see if the security timestamp has changed and log out the user (that's what our sample does).

If you are using any other form of auth then you can either do something like a request (as you are doing) or store some information somewhere on the server where you can easily update it on a per-request basis and check from Blazor server to detect changes.
