### ISSUE TITLE
Microsoft.AspNetCore.Analyzers.RouteEmbeddedLanguage.RoutePatternAnalyzer warning when .net 8 with framework reference Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by jnormen** [dotnet/aspnetcore#50868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There seams to be the same problem I can find when on older post about 6 to 7 RC1. But now with .net 7 to .net 8 RC1

when I use a frameworkreference in my project file to Microsoft.AspNetCore.App and target .net 8 (using Rc1 latest).
The analyzer gives a warning:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.AspNetCore.Analyzers.RouteEmbeddedLanguage.RoutePatternAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'.'
```

I guess this is something that will be fixed in later on as with .Net 6 to .Net 7 ? So not sure if this is a bug, issue that shall be reported here? 

### Steps To Reproduce

Project with target .net 8

		<LangVersion>preview</LangVersion>
		<TargetFramework>net8.0</TargetFramework>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

### Exceptions (if any)

Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions

### .NET Version

8.0.100-rc.1.23463.5

**Comment by captainsafia** [comment]
Thanks for the bug report, @jnormen! I'm closing this in favor of https://github.com/dotnet/aspnetcore/issues/50881 which was filed first and has enough similarities that it warrants duping.
