### ISSUE TITLE
Minimal API endpoints accepting IFormFile terminating with HTTP 200 for large files

### ISSUE THREAD

**Issue by peterwurzinger** [dotnet/aspnetcore#50871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When uploading large (>MaxRequestBodySize) files to an ASP.NET Core application, one would have to respect the maximum request body size. Nothing new with that.

For controller-hosted endpoints, there is the `[DisableRequestSizeLimit]` attribute that works just great.

For minimal APIs, there is no filter or directive to disable the request size limit for a specific endpoint.
Disabling it manually before the file is read still works, so something like 
```cs
var bodySizeFeature = HttpContext.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;
```
does the trick.
Spoiler: Well, no...

E.g. This endpoint terminates immediately with HTTP 200 (!) for files larger than the MaxRequestBodySize. The attempt to unset this property is never respected.
```cs
app.MapPost("/upload", (IFormFile file, HttpRequest request) =>
  request.HttpContext.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;

  //Do something with the file. Or at least try, for a large file you won't get here.
```

Trying the same while binding the file manually works:
```cs
app.MapPost("uploadButWithRequest", (HttpRequest request, CancellationToken cancellationToken) =>
{
  request.HttpContext.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;

  var file = request.Form.Files.Single();
  //Do something with the file.
```

Please see the reproduction code for some more details.

### Expected Behavior

* Minimal API endpoints binding `IFormFile` should accept the file at first, and throw an exception when the file is accessed or read and its size is bigger than the current MaxRequestBodySize - just as it would happen when it is bound using `HttpRequest.Form`.

* In my opinion it should be considered wrong to terminate with a contentless HTTP 200 in those cases at least.

* If I may add a wish here: There should be a possibility to mark minimal api endpoints as ignoring the request size limit, just like there is an attribute for controller based endpoints. Something like `.Map(...).DisableRequestSizeLimit()`

### Steps To Reproduce

Given this basic example using three minimal api endpoints handing file uploads via multipart/form-data.
- One binding IFormFile (as usual)
- The second one binding manually using `HttpRequest.Form`
- The third one binding manually using `HttpRequest.Form` *and* disabling the MaxRequestBodySize

```cs
using Microsoft.AspNetCore.Http.Features;

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapPost("/upload", (IFormFile file, HttpRequest request) =>
{
  //You won't get here, interestingly the request was already terminated with HTTP 200 (?!)
  request.HttpContext.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;
  return TypedResults.Ok("This worked with IFormFile");
});

app.MapPost("/uploadButWithoutSettingMaxRequestBodySize", (HttpRequest request, CancellationToken cancellationToken) =>
{
  //Throws exception because Kestrel is unhappy with the request size
  var file = request.Form.Files.Single();

  return Results.Ok($"This worked with a upload based on HttpRequest without setting MaxRequestBodySize: {file.FileName}");

});

app.MapPost("/uploadButWithRequestAndSettingMaxRequestBodySize", (HttpRequest request, CancellationToken cancellationToken) =>
{
  request.HttpContext.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;

  var file = request.Form.Files.Single();

  return Results.Ok($"This worked with a upload based on HttpRequest instead of IFormFile: {file.FileName}");

});
app.Run();
```

One could use those curl statements to test those endpoints:
```cmd
curl -X "POST" "http://localhost:{PORT}/upload" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file=@<A LARGE FILE>;type=text/plain" -o -

curl -X "POST" "http://localhost:{PORT}/uploadButWithoutSettingMaxRequestBodySize" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file=@<A LARGE FILE>;type=text/plain" -o -

curl -X "POST" "http://localhost:{PORT}/uploadButWithRequestAndSettingMaxRequestBodySize" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file=@<A LARGE FILE>;type=text/plain" -o -
```

Note that you will need a file larger than the default MaxRequestBodySize, so more than 28.6MB according to [the docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize?view=aspnetcore-7.0)

### .NET Version

7.0.306

**Comment by captainsafia** [comment]
@peterwurzinger Thanks for reporting this issue! We didn't ship support for request size limits with minimal APIs in .NET 7 but this will be rolling out in the upcoming .NET 8 release. 

With .NET 8 RC 1, the following app code:

```csharp
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapPost("/", (IFormFile file) => file.FileName)
    .WithMetadata(new RequestSizeLimitAttribute(200))
    .DisableAntiforgery();

app.Run();
```

should produce this response:

<img width="672" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1857993/abd74d8d-50c1-4e57-8920-ebd5cd29781f">
