### ISSUE TITLE
High Network Usage in Blazor Application

### ISSUE THREAD

**Issue by krishnan-periyasamy** [dotnet/aspnetcore#50872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are currently experiencing a significant increase in network usage when running our Blazor application that involves continuously updating graphics elements with data. Despite the data transfer size being reported as approximately 900 KB/s, the actual network usage spikes to 5 MB/s or even 10 MB/s at times.
<img width="966" alt="image" src="https://github.com/dotnet/aspnetcore/assets/95361480/ec57ecff-766c-47d9-9a4a-ce5b1f686fe3">

**Issue Details:**
- **Application Name:**  Blazor Application .net 7.0
- **Environment:** All
- **Application Version:**  .net 7.0
- **Network Environment:** cloud-hosted.
- **Data Source:** N/A. It's random data and this embed in same razor file.
- **Browser(s) Used:** Edge, Chrome and Firefox

### Steps To Reproduce

1. Download, host and run the attached sample.
2. Please click the start **Start Live Data** button.
3. Check the browser network tab in data transfer size and task manger on network usage.

[NetworkTesting.zip](https://github.com/dotnet/aspnetcore/files/12699995/NetworkTesting.zip)

### .NET Version

7.0

### Anything else?

**Impact:** Business operations.
**Urgency:** critical

**Comment by javiercn** [comment]
@krishnan-periyasamy thanks for contacting us.

We don't think that's the right way to measure the network usage. For a starting point, we would recommend looking at the network tab within the developer tools and looking at the ASP.NET Core logs to get a better understanding of what the size of the data is.
