### ISSUE TITLE
[Blazor] Client diffing bug

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#50877]
When there are two interactive components together and one of them gets removed, there is a bug that causes the update to fail.
```
@if (Wasm)
{
    <WasmComponent />
}
@if (Server)
{
    <ServerComponent />
}
```

Introducing a div worksaround the issue
```
@if (Wasm)
{
    <div>
        <WasmComponent />
    </div>
}
@if (Server)
{
    <div>
        <ServerComponent />
    </div>
}
```

To repro:
* Go to `InitializersNonStreamingRequest.razor` and `InitializersNonStreamingRequest.razor`
* Remove the divs that wrap around WasmComponent and ServerComponent.
* Run the BlazorWebJsInitializersTest

**Comment by vaidyajayesh** [comment]
@javiercn @mkArtakMSFT : If you are ok, I would love to contribute and submit PR.
