### ISSUE TITLE
Blazor SSR Form submit on DOM events

### ISSUE THREAD

**Issue by jonhilt** [dotnet/aspnetcore#50870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Given a Blazor component rendering via SSR in .NET 8.

If that component includes a form:

``` html
<form method="post" @formname="Search" class="d-flex mb-4 gap-2">
    <input type="text" name="searchTerm" value="@SearchTerm" 
           class="form-control"/>
    <button class="btn btn-primary">Search</button>
    <AntiforgeryToken/>
</form>
```

It seems the only way to actually submit the form right now (and have Blazor handle the post) is to click the submit button.

### Describe the solution you'd like

A common requirement is for forms to submit based on another element's DOM events, for example `oninput` or `onblur` for the `searchTerm` input in this example.

Right now it seems this isn't possible with Blazor and SSR.

Presumably the option is to make the component interactive using Server/WASM.

My question is whether this should be supported, as part of .NET 8's enhanced navigation and form handling?

**Comment by javiercn** [comment]
@jonhilt thanks for contacting us.

The recommendation here would be to add some JS to achieve what you want. Enhanced navigation only intercepts links and form submits, but it does not offer alternative ways of triggering those.

**Comment by jonhilt** [comment]
That makes sense. Thanks for the quick response :)

I've spoken to a few Blazor developers this week where this came up, it seems like this might be a common question as people start to use SSR :)

**Comment by guardrex** [comment]
I'll add a remark on this to the documentation.
