### ISSUE TITLE
Build throws a AD0001 Warning

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#50881]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Build-throws-a-AD0001-Warning/10465844)._

---
[severity:It's more difficult to complete my work]
When building two of the projects in my solution they throw an unexpected unclear how to fix analyzer warning:

warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Failed to resolve well-known type 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions'.'.

Found during my first try to migrate a solution from net6 to net8 RC1.
These are the only warnings I could not fix. The rest of the warnings were all expected new nullability warnings which I could easily fix.

---
#### Feedback Bot on 9/14/2023, 01:41 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/50836 which was filed first and looks related.
