### ISSUE TITLE
SVG mouse events not working on Visual Studio 17.8.0 Preview 2.0 (.NET 8)

### ISSUE THREAD

**Issue by ABIOLI-COM** [dotnet/aspnetcore#50896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a Blazor WebAssembly, a piece of code using @onmousemove on an SVG was working in .NET 7, but when trying the same in .NET 8 as in subject, doesn't do anything (the interactive checker also says that @onmousemove is a spelling error).  
Will it be supported again in the production version of .NET 8, or what do we have to expect?  
Thank you.

### Expected Behavior

What was working in .NET 7: be able to intercept in Blazor, without any Javascript, mouse events inside SVGs.

### .NET Version

8.0.100-rc.1.23455.8

**Comment by gragra33** [comment]
@ABIOLI-COM is it just for SVGs or for any element event?

**Comment by ABIOLI-COM** [comment]
True... I didn't check, but now I see that it's in the whole document, that mouse events, and some other, are missing... What does it mean?

**Comment by gragra33** [comment]
@ABIOLI-COM you need to set the render mode for the page or the component. This is new for .Net 8.

**Comment by ABIOLI-COM** [comment]
Right, good to know.  
I checked the documentation, but I'm puzzled: they talk about adding AddWebAssemblyComponents and AddWebAssemblyRenderMode on server and client, but the new template 'Blazor Web App' only created one... I tried inserting both, but with no success.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is indeed most probably due to the fact that you didn't specify any interactivity option when created the template, and it was statically rendered (no interactivity).
Enabling interactivity would result in the events to work again.
