### ISSUE TITLE
Blazor SSR StreamRendering re-renders last few elements.

### ISSUE THREAD

**Issue by jsalichos** [dotnet/aspnetcore#50891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Blazor StreamRendering mode, there is a bug where, when the html part to stream is quite large, the rendering process repeats itself. Render is located  just before reaching the closing body element.

### Expected Behavior

StreamRendering mode should only render the html fragment once.

### Steps To Reproduce

1. Create a new project with the default blazor template and select "Include sample pages".
2. Open Weather.Razor file for edit
3. In line 53 change the count of forcasts range to be produced to 1500 
```
        forecasts = Enumerable.Range(1, 1500).Select(index => new WeatherForecast
        {
            Date = startDate.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = summaries[Random.Shared.Next(summaries.Length)]
        }).ToArray();
```
4. Run the project
5. Notice after the weather forcasts table a subset of the table being rendered again!

### .NET Version

8.0.100-rc.1.23463.5

### Anything else?

dotnet --info
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.305 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marinasundstrom** [comment]
I do a full refresh on the page to trigger stream rendering, this is what the last line looks like:

![Screenshot 2023-09-23 at 17 06 57](https://github.com/dotnet/aspnetcore/assets/919580/97bc11cc-60c9-4999-aa93-fc2b08b87e3e)

The request:

![Screenshot 2023-09-23 at 17 09 25](https://github.com/dotnet/aspnetcore/assets/919580/047eac2c-d8ea-431e-bf99-a6ffce6625ea)

It does not return all the data.

Are there any limitations to request size?

**Comment by marinasundstrom** [comment]
@jsalichos This?

![Screenshot 2023-09-23 at 17 19 07](https://github.com/dotnet/aspnetcore/assets/919580/705be6e1-4e86-4ef3-b75e-806052aa6253)

**Comment by jsalichos** [comment]
@marinasundstrom
Actually is more like this:
![image](https://github.com/dotnet/aspnetcore/assets/1744884/2c2547ff-e8b0-4f42-ac38-9d02604616cf)

Please observe the text immediately preceding the body closing tag </body> in the Chrome Dev Tools window. Additionally, take note of line 497 and how it extends, followed by a continuation from line 399. It is worth mentioning that the line numbers displayed are merely a column I have just included to indicate the order of table rows.

```
    @foreach (var forecast in forecasts)
    {
        counter++;
        <tr>
            <td>@counter</td>
            <td>@forecast.Date.ToShortDateString()</td>
            <td>@forecast.TemperatureC</td>
            <td>@forecast.TemperatureF</td>
            <td>@forecast.Summary</td>
        </tr>
    }
```

**Comment by marinasundstrom** [comment]
@jsalichos Now I see
![Screenshot 2023-09-23 at 19 18 16](https://github.com/dotnet/aspnetcore/assets/919580/a6625a1b-5732-4db4-a8c7-27fb7ac6b131)

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this, @jsalichos and you trying to help, @marinasundstrom.
Can you please try the latest nightly RC2 build and see if this is already fixed or not (because we think it may have been fixed).

**Comment by jsalichos** [comment]
Hi, I can't make any nightly RC2 build to work with VS.

**Comment by marinasundstrom** [comment]
> Hi, I can't make any nightly RC2 build to work with VS.

What about the CLI?

dotnet run

**Comment by jsalichos** [comment]
Thanks @marinasundstrom,

I am pleased to report that the project was successfully executed. Rigorous testing has confirmed that the Bug has been completely eradicated from the system..
