### ISSUE TITLE
SignalR Client client-to-server streaming is memory leaking in ConnectionState.UploadStreamToken

### ISSUE THREAD

**Issue by higor-hernandes** [dotnet/aspnetcore#50913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using ASP.NET Core SignalR Client to stream data from client to server, the HubConnection is memory leaking CancellationToken Callbacks in the CancellationTokenSource of the `ConnectionState.UploadStreamToken`. For each call of `HubConnection.SendAsync` it registers a new CancellationToken Callback in this CancellationTokenSource and does not remove it after completing the upload. I don’t know if it is just a missuse of the SignalR client or it really has a memory leak while uploading streams.

![image](https://github.com/dotnet/aspnetcore/assets/135724753/f8c1d8bd-3216-435a-8f49-daf4148c4a54)
![image](https://github.com/dotnet/aspnetcore/assets/135724753/d12e6c79-2cea-44ce-a694-47405e11d0b0)

### Expected Behavior

Does not indefinitely increase memory usage when sending a ChannelReader in the HubConnection.SendAsync. Unregister the cancellation callbacks after completing each SendAsync request.

### Steps To Reproduce

Keep uploading data using the HubConnection.SendAsync and Channels
For each call of the SendAsync it leaks in the CancellationTokenSource described.

repo: https://github.com/higor-hernandes/signalr-sample-tests
build and run the SignalRHubSample project.
build and run the SignalRHubClientSample project.
In a few seconds is possible to see the CancellationToken Callbacks being register and accumulating in the CancellationTokenSource from `ConnectionState.UploadStreamToken` created in the `HubConnection.ReceiveLoop` method

Client implementation of the how to reproduce:
![image](https://github.com/dotnet/aspnetcore/assets/135724753/6833216c-1370-4054-8e61-ac9912b947b9)

Hub implementation of the how to reproduce:
![image](https://github.com/dotnet/aspnetcore/assets/135724753/307ee96e-9be3-484c-a82c-61b07d002946)

### .NET Version

7.0.202

### Anything else?

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.5.3

.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\
Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe
.NET SDKs installed:
   7.0.202 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
      registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
Environment variables:  
  Not set
global.json file:
  Not found 

Client Sample Packages:
Microsoft.AspNetCore.SignalR.Client      7.0.11 
Hub Sample Packages:
Microsoft.AspNetCore.SignalR.Protocols.Json      7.0.11

Where in SignalR Client the leak might be coming from:
![image](https://github.com/dotnet/aspnetcore/assets/135724753/191cc78e-68b1-4443-846b-3e819af6b687)
![image](https://github.com/dotnet/aspnetcore/assets/135724753/450a1f69-1d8f-40c6-84b1-30f56ca5f2d3)

**Comment by BrennanConroy** [comment]
Nice find! I am curious how you found it though.

**Comment by higor-hernandes** [comment]
Hello Brennan, thanks for looking it.
We have a service that cannot be stopped frequently for maintenance. After a few weeks, we noticed an unusually high memory usage. We took memory snapshots and investigated until we reached the SignalR code.
We are looking forward to having this fixed.
