### ISSUE TITLE
Streaming rendering incompatible with certain hosting environments?

### ISSUE THREAD

**Issue by jonhilt** [dotnet/aspnetcore#50915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there a plan to document the underlying mechanics of how Streaming rendering works?

Specifically I've run into a situation where streaming rendering doesn't appear to work when deployed to my production environment.

I've used Digital Ocean's App Platform for deployment before now, as it provides a convenient (and pretty cost-effective) way to deploy web apps via docker containers.

I created a demo app using the new `blazor` project template, then published it as a docker image using this command:

```powershell
dotnet publish -p:PublishProfile=DefaultContainer -p:ContainerRegistry=registry-1.docker.io -p:ContainerRepository=jonhilt/digitaloceandemo --os linux --arch x64 -c Release
```

But, having deployed this to Digital Ocean's App Platform, it seems streaming rendering isn't kicking in when you navigate to the weather page

https://hammerhead-app-fcvk5.ondigitalocean.app/

I suspect this is due to how DO uses Cloudflare for a few things including auto switching to https…

### Describe the solution you'd like

But I'm aware I don't know enough about how streaming rendering works to properly diagnose this issue, so my thought is that it would be useful if there was some documentation around this.

Perhaps, at least, some outlining of the basic mechanism and any potential hosting environment requirements needed to support streaming rendering?

**Comment by iphdav** [comment]
Hi Jon.  Try navigating to the weather page, then click "refresh/reload (F5)" in your browser.  You should see the streaming rendering works fine, so this isn't anything to do with Digital Ocean's App Platform.

The issue is likely that you have your project configured to be interactive at root (in other words you have it configured to run like a traditional blazor server project).

If you do the interactivity on a per-page basis, you will see the streaming rendering when you click onto the weather page (without needing to refresh your browser).

**Comment by jonhilt** [comment]
Thanks for that update @iphdav.

This is a default new blazor project, so the weather page should work using streaming rendering as you navigate between pages.

I've actually just run another test and deployed the exact same image to another host ([render](https://render.com/)) and you can see it works as expected.

https://blazor-test-w8l8.onrender.com/

Here's the source: https://github.com/jonhilt/DockerTest

**Comment by SteveSandersonMS** [comment]
Streaming rendering does require the server not to buffer the output, but rather to allow the response data to flow to the client as it is generated.

The good news is that this degrades gracefully. As you've seen, even for hosts that do buffer, the page still works. You simply don't see the intermediate stages during loading.

We will mention this in docs.

**Comment by jonhilt** [comment]
Thanks for that clarification @SteveSandersonMS (and always great to see extra detail added to the docs)

**Comment by guardrex** [comment]
I'm tracking this for doc work now on https://github.com/dotnet/AspNetCore.Docs/issues/30504.
