### ISSUE TITLE
feat: using `ProblemDetailsFactory` from DI on exception using Minimal API.

### ISSUE THREAD

**Issue by DES-Destry** [dotnet/aspnetcore#50924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to handle exceptions with minimal API syntax, but this endpoint using default `ProblemDetailsFactory` instead of instance, that I've injected.
So I need to inject `ProblemDetailsFactory` with parameters and implement logic, create `ProblemDetails` by injected factory and only then call `TypedResult.Problem(problemDetails)`. This logic already exists in `ControllerBase` class, where you can just call `Problem()` method.

### Describe the solution you'd like

So, what about new overload of `TypedResult.Problem()`, which accepts `ProblemDetailsFactory` instead of ready `ProblemDetails`?
One more variant: overload of `TypedResult.Problem()` which accepts `HttpContext`, and then from services we can get custom `ProblemDetailsFactory` instance, such as in `ControllerBase.Problem()`, but it's looks overhead and I personally prefer the 1st option.

### Additional context

Now:
![Screenshot 2023-09-26 at 2 09 55 AM](https://github.com/dotnet/aspnetcore/assets/50075282/239fdffe-e985-4083-9cd7-cceaf87f903f)

What I mean:
![Screenshot 2023-09-26 at 2 14 47 AM](https://github.com/dotnet/aspnetcore/assets/50075282/a3a46f9d-ed7b-41f0-8057-a45a1e5bce04)

**Comment by DES-Destry** [comment]
Implementation, that described there is not ideal. This was a fast suggestion. Main feature request: using injected `ProblemDetailsFactory` in open-api, like in classic controllers without actual creating and calling `ProblemDetailsFactory`.

**Comment by DES-Destry** [comment]
Probably, the best way in this case: create method, that will pass as 2nd parameter of `app.MapGet()`. Something like:

```C#
app.MapGet("/error", HandleError);
```

**Comment by captainsafia** [comment]
@DES-Destry Minimal APIs provides standardized support via the problem details service. The `TypedResults.Problem` methods will use this service to construct the problem details object that they return. For more information on this, check out [the docs on ProblemDetails](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errors?view=aspnetcore-8.0#problem-details).
