### ISSUE TITLE
Build time regression for MVC templates

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#50923]
Doesn't repro for API templates. Visible on Linux and Windows.

![image](https://github.com/dotnet/aspnetcore/assets/1165805/3dfbdcb5-056e-4e7a-8d34-66a340d5ac68)

Before

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/BuildPerformance/buildperformance.yml --scenario mvc --profile intel-load2-app --profile intel-db-load --application.framework net8.0 --application.aspNetCoreVersion 8.0.0-rtm.23471.8 --application.runtimeVersion 8.0.0-rc.2.23471.30 --application.sdkVersion 8.0.100-rtm.23471.13
```

After

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/BuildPerformance/buildperformance.yml --scenario mvc --profile intel-load2-app --profile intel-db-load --application.framework net8.0 --application.aspNetCoreVersion 8.0.0-rtm.23471.8 --application.runtimeVersion 8.0.0-rtm.23472.12 --application.sdkVersion 8.0.100-rtm.23472.18
```

**Comment by danmoseley** [comment]
@mkArtakMSFT can we investigate for 8 timeframe?

@sebastienros can you see what change this might align with?

**Comment by sebastienros** [comment]
> can you see what change this might align with?

No, I didn't investigate. The procedure is to first repro the numbers with the command lines I shared, then isolate the problem by varying the runtimes and the sdk (starting with the SDK version). Then check within the commit hashes of the component that has been identified as the reason.
