### ISSUE TITLE
Mvc.Testing.Handlers.RedirectHandler => MaxRedirects does not allow 0

### ISSUE THREAD

**Issue by trynn** [dotnet/aspnetcore#50925]
Unlike in the description of the ctor, the RedirectHandler does not allow 0 as input for MaxRedirects.

https://github.com/dotnet/aspnetcore/blob/70048beee894074e9718206a0017d9b080ee66ff/src/Mvc/Mvc.Testing/src/Handlers/RedirectHandler.cs#L34

--
Noticed when trying to test api controller that does response with `RedirectResult` intentionally, but had an HTTP 404 on the HttpClient.GetAsync because the RedirectHandler tries to resolve the Redirect before returning the result.
Would appreciate the option to disable it :)

**Comment by captainsafia** [comment]
@trynn Thanks for the bug report! Would you like to submit a PR to fix this issue? 

Should be a matter of updating the equality check in the line of code you mentioned and adding a new test [in this file](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/test/Mvc.FunctionalTests/TestingInfrastructureTests.c).

**Comment by trynn** [comment]
@captainsafia sorry i've tried, but not able to get a dev environment for this repo running on my maschine.
And since i cant execute the test, i keep my fingers away now.

Already invested hours in trying get things running, but i think at this point i'll stop.

**Comment by yunsuklee** [comment]
Hey, I'd like to work on this issue. Would you assign it to me?

**Comment by yunsuklee** [comment]
> @trynn Thanks for the bug report! Would you like to submit a PR to fix this issue?
> 
> Should be a matter of updating the equality check in the line of code you mentioned and adding a new test [in this file](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/test/Mvc.FunctionalTests/TestingInfrastructureTests.c).

Could you tell me what sort of test you need? Would it be enough to trying to make the request with 0 and a negative value and asserting the appropriate response?

**Comment by captainsafia** [comment]
@trynn Apologies you ran into issues with this! In the future, feel free to file an issue on the repo if you run into any problems setting up the repo locally and we'll be glad to help you.

I went ahead and opened a PR for this issue in case you'd like to review it. See https://github.com/dotnet/aspnetcore/pull/51245
