### ISSUE TITLE
Blazor javascript isolation in different assembly

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#50939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor server app where the base logic is divided into different projects.

I have the main project which includes all sub projects and maps all of the routable pages in my `App.razor`
![grafik](https://github.com/dotnet/aspnetcore/assets/32510006/33691bc3-bff8-4044-988b-0ed4f4d10444)

`App.razor`
```csharp
<Router AppAssembly="@typeof(App).Assembly"
        AdditionalAssemblies="new[]
{
    typeof(ShowAlertModule.AlertPage).Assembly
}">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

When I visit the page then via URL everything works as expected. 

Now I want to import an isolated javascript file in the sub project called `AlertPage.razor.js`
```csharp
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "./AlertPage.razor.js");
```

However this doesn't work and fails with an exception.

I also tried another sets of combinations but I don't get it to work.
These I've tried:
```csharp
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "./ShowAlertModule/AlertPage.razor.js");
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "/ShowAlertModule/AlertPage.razor.js");
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "~/ShowAlertModule/AlertPage.razor.js");
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "~/AlertPage.razor.js");
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "../AlertPage.razor.js");
```

When I try to import a module from the same project as my base project everythings works just fine.

Isn't JavaScript isolation supported from third assemblies?

### Steps To Reproduce

I've created a small repo to showcase this:
https://github.com/MarvinKlein1508/BlazorModuleDemo

Simply navigate to the `/Alerts` page there.

### Exceptions (if any)

Error: Microsoft.JSInterop.JSException: error loading dynamically imported module: https://localhost:7283/AlertPage.razor.js

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)

   at ShowAlertModule.AlertPage.OnAfterRenderAsync(Boolean firstRender) in C:\Users\mk\source\repos\BlazorModuleDemo\ShowAlertModule\AlertPage.razor:line 13

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### .NET Version

8.0.100-rc.1.23463.5

**Comment by MarvinKlein1508** [comment]
@javiercn I was working with this docs from MSFT. https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0#dom-cleanup-tasks-during-component-disposal

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You should link the resources in a specific way, documented here: https://learn.microsoft.com/aspnet/core/razor-pages/ui-class?tabs=visual-studio#consume-content-from-a-referenced-rcl

**Comment by MarvinKlein1508** [comment]
Hi @mkArtakMSFT 

this doesn't help me in my case, since the javascript file is not in wwwroot of the razor class library. It is a isolated file structured behind my razor file.

Specifiying 
```csharp
module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "_content/ShowAlertModule/AlertPage.razor.js");
```

results in this exception:
```
Error: Microsoft.JSInterop.JSException: The specifier "_content/ShowAlertModule/AlertPage.razor.js" was a blank specifier, but was not remapped to anything. Relative module specifiers must start with "./", "../" or "/".
```

Isn't JavaScript isolation supported for these files? That's the structure.
![grafik](https://github.com/dotnet/aspnetcore/assets/32510006/34f38d00-3cd7-45a1-a0a4-33b6a4593896)

**Comment by MarvinKlein1508** [comment]
When I specify this in my `_Host.cshtml` 
```html
<script src="_content/ShowAlertModule/AlertPage.razor.js"></script>
```

Then I can access it from my host app. But how do I achieve this directly in the module to only load the javascript when needed?

**Comment by gragra33** [comment]
@MarvinKlein1508 Why not just put the script element at the bottom of the razor page where you want to use it?

**Comment by MarvinKlein1508** [comment]
@gragra33 it's not a razor page. It's a razor component.

**Comment by gragra33** [comment]
@MarvinKlein1508 You could look at using the `HeadContent` component to place the script in the header when needed. If duplicates appear when using it, you could create a wrapper component for the `HeadContent` component to track what scripts are loaded and unloaded.
