### ISSUE TITLE
New Blazor Web App fails to compile: Auto, Global, Empty

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50930]
A new Blazor Web App fails to compile when selecting Auto, Global, and Empty. It refers to the non-existent Counter component.

BlazorApp35\Program.cs(32,37,32,44): error CS0246: The type or namespace name 'Counter' could not be found (are you missing a using directive or an assembly reference?)

**Comment by danroth27** [comment]
If you select Auto, Page, and Empty, you get the same error due to the non-existent Counter component and also an error about the BlazorApp.Client.Pages namespace not existing.

**Comment by mkArtakMSFT** [comment]
This has been fixed already as part of the last Blazor Web project template change.
