### ISSUE TITLE
Hot reload doesn't work with the empty Blazor Web App template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50931]
When I create an empty Blazor Web App template, hot reload doesn't seem to work. I tried both Server and Auto interactive render modes.

.NET SDK 8.0.100-rc.2.23472.8

The Hot Reload output window in VS says "No changes were found" when I try to apply a change, so it seems like the change just isn't getting applied to the app.

**Comment by danroth27** [comment]
I restarted VS and now hot reload is working again even with the empty template.

**Comment by mkArtakMSFT** [comment]
@tmat another one for you to look at

**Comment by tmat** [comment]
@danroth27 Does it work with `dotnet watch`?

**Comment by danroth27** [comment]
> @danroth27 Does it work with `dotnet watch`?

I just tried out using `dotnet watch` and it seems to work fine. I haven't seen this particular issue when using `dotnet watch`, but I also don't use `dotnet watch` very often.

**Comment by rogihee** [comment]
If I create a Blazor Web App (RC1 template) with WebAssembly interactivity but without Server and try to run `dotnet watch run`, it can't connect to the site. Site is started but without a port:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/726074c5-4bca-4415-97ea-84a97009ee7f)

**Comment by garrettlondon1** [comment]
https://github.com/dotnet/sdk/issues/35465 related issue

**Comment by garrettlondon1** [comment]
Not related to .NET 8 but @danroth27 is this the correct place for this issue? 

https://github.com/dotnet/sdk/issues/35465

**Comment by mkArtakMSFT** [comment]
@danroth27 should this be closed already then>?

**Comment by mkArtakMSFT** [comment]
@rogihee the issue you've described is a different one, Could you please file a new issue so that we don't mix things up and loose track of it. Thanks!

**Comment by rogihee** [comment]
@mkArtakMSFT I tried to fresh reproduce and somehow it works now. If I can get it to _not_ work I'll file an issue.

**Comment by bub-bl** [comment]
Hi, i have create a new project (Blazor Web Application) from VS Preview 17.8.0 Preview 2 with WebAssembly and Server interactivity. But the hot reload doesn't work. When i add some code in a razor file, i need to refresh the browser manually to see changes

**Comment by danroth27** [comment]
@bub-bl Could you please open a new issue for the problem you're seeing? This issue is already closed.
