### ISSUE TITLE
how to implement external login provders(linkedin) login using .net core with openidconnect?

### ISSUE THREAD

**Issue by PriyankaTalapaneni** [dotnet/aspnetcore#50941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

tried linkedin login in asp.net core.
Added below code in startup

.AddOpenIdConnect(Configuration.GetSection("ExternalLoginConfiguration:LinkedInConfiguration:Scheme").Value, "linkedin", options =>
{
options.SignInScheme = "Identity.External";
options.RequireHttpsMetadata = false;
options.ClientId = Configuration.GetSection("ExternalLoginConfiguration:LinkedInConfiguration:ClientId").Value;
options.ClientSecret = Configuration.GetSection("ExternalLoginConfiguration:LinkedInConfiguration:ClientSecret").Value;
options.CallbackPath = Configuration.GetSection("ExternalLoginConfiguration:LinkedInConfiguration:CallbackPath").Value;
options.Authority = "https://www.linkedin.com/";
options.ResponseType = OpenIdConnectResponseType.Code;
options.Configuration=new OpenIdConnectConfiguration();
options.Configuration.AuthorizationEndpoint="https://www.linkedin.com/oauth/v2/authorization";
options.Configuration.TokenEndpoint="https://www.linkedin.com/oauth/v2/accessToken";
options.Scope.Clear();
options.Scope.Add("openid");
options.Scope.Add("email");
options.Scope.Add("profile");
options.GetClaimsFromUserInfoEndpoint = true;
options.SaveTokens = true;
options.Events = new OpenIdConnectEvents()
{
OnRedirectToIdentityProvider = (ctx) =>
{
// ctx.ProtocolMessage.SetParameter("access_type", "offline");
string username = ctx.Properties.Items["username"];

                                 SetLoginHint(username, ctx);
               return Task.FromResult(0);
           }
       };

   });
and I set IdentityModelEventSource.ShowPII is true.

![image](https://github.com/dotnet/aspnetcore/assets/136562041/dc517c8a-c3d2-4913-b545-0f9230cf5a6c)

### Expected Behavior

Need to login with external provider (Linkedin) using .net core with openidconnect.

### Exceptions (if any)

I am getting logs Message: An error was encountered while handling the remote login. Message contains error: 'invalid_client', error_description: 'Client authentication failed', error_uri: 'error_uri is null'

### .NET Version

Version 3.4.2 and TargetFramework net6.0

**Comment by martincostello** [comment]
> 'invalid_client', error_description: 'Client authentication failed'

This suggests that your Client ID and/or Client Secret is missing or invalid.

**Comment by PriyankaTalapaneni** [comment]
Hi @martincostello 
I provided Client ID and Client Secret and that details are valid only

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
