### ISSUE TITLE
.NET 8 blazor web with RenderModeServer Issues with CascadingAuthenticationState

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/aspnetcore#50951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I have a Blazor server project that uses a Razor class library. The project was initially built with .NET 7 and worked perfectly. However, I’ve recently decided to upgrade it to .NET 8 and have encountered some issues.

In the .NET 7 version of the project, I wrapped the App.razor with CascadingAuthenticationState, and it worked for pages inside the Razor class library. However, after upgrading to .NET 8, CascadingAuthenticationState inside App.razor no longer works for the pages that inside Razor class library. As a result, I have to use CascadingAuthenticationState for every single page.

Additionally, the following code:
`[CascadingParameter]
Task<AuthenticationState>? authenticationState { get; set; }`
also does not work in the Razor class library in .NET 8. Therefore, I had to modify the pages that use this code.

I hope these issues can be resolved before November.

### Expected Behavior

should works just fine and passes the AuthState to razor class lib 

### .NET Version

.Net8

**Comment by javiercn** [comment]
@Ali1Jamal thanks for contacting us.

What version of .NET 8.0 are you using?

Cascading authentication values don't flow across boundaries (from SSR to Interactive Server or WebAssembly for example). We did some work I believe to make the auth bit work, but that's about it.

**Comment by SteveSandersonMS** [comment]
If you do a direct upgrade, i.e., changing the target framework from `net7.0` to `net8.0`, your existing approach to authentication should continue to work fine. If that's not the case, please let us know and provide a minimal repro project as a public GitHub repo so we can investigate. We would look into that urgently since it's definitely not expected to break existing code.

However, if you're upgrading in the sense of starting a new .NET 8 project, then you'll be working with a different rendering convention by default. In that case depending on how you've done the upgrade, the point raised by @javiercn may well explain what you're seeing. Simply adding a `<CascadingAuthenticationState>` at the root of your site won't cause authentication state to flow from SSR to InteractiveServer/InteractiveWebAssembly modes - you would need to see how auth state is handled in the latest RC2 project template.

**Comment by Ali1Jamal** [comment]
Thank you for the quick replies, @javiercn. I use .NET 8 RC1.
 I upgraded the blazor server from .NET 7 to be  (.NET 8 blazor web app with interactive server) component by changing the target framework and App.razor and Routes.razor, etc.
  I saw @SteveSandersonMS’s comment and made a new single project for investigating (blazor web app with interactive server component) and fake auth ,
  If you want the Investigation project, let me know because I think it is simple and easy to understand, so I will explain it in detail in this comment.
  .
 Here is the code for CustomAuthenticationStateProvider.cs:
```csharp
using System.Security.Claims;
using Microsoft.AspNetCore.Components.Authorization
namespace Blazor.Extensions;
public class CustomAuthenticationStateProvider : AuthenticationStateProvider
{
    public override async Task<AuthenticationState>? GetAuthenticationStateAsync()
    {
        return GenerateCustomAuthenticationState();
    }
    private AuthenticationState GenerateCustomAuthenticationState()
    {
        var claimsPrincipal = CreateFakeClaimsPrincipal();
        var authenticationState = new AuthenticationState(claimsPrincipal);
        return authenticationState;
    }
    private ClaimsPrincipal CreateFakeClaimsPrincipal()
    {
        var claims = new List<Claim>
    {
        new Claim(ClaimTypes.NameIdentifier, Guid.NewGuid().ToString()),
        new Claim(ClaimTypes.Name, "FakeUser"),
        new Claim(ClaimTypes.Email, "fakeuser@example.com"),
    };
        var identity = new ClaimsIdentity(claims, "custom");
        return new ClaimsPrincipal(identity);
    }
}
```
Inside Routes.razor, if I wrap it with CascadingAuthenticationState like this:
```csharp
@using Microsoft.AspNetCore.Components.Authorization;
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
    </Router>
</CascadingAuthenticationState>
```

and inside Counter.razor (it have RenderModeServer attribute ):
 ```csharp
 <AuthorizeView>
    <Authorized>
        <p>Hello : @context.User.FindFirstValue(ClaimTypes.Name)</p>
        <p role="status">Current count: @currentCount</p>
        <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
    </Authorized>
    <NotAuthorized>
        <p>You are not Authorized</p>
    </NotAuthorized>
</AuthorizeView>
```
It will give me the name of the user and after half a second, it will give me a warning and fail.
```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
      System.InvalidOperationException: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
         at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'rRzsLwJiIuEqV9EI1gAIXAnsQep6-M3rp92lGjr990Y'.
      System.InvalidOperationException: Authorization requires a cascading parameter of type Task<AuthenticationState>. Consider using CascadingAuthenticationState to supply this.
         at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```   
But if I wrap the Counter.razor with CascadingAuthenticationState, it will work.
```csharp
<CascadingAuthenticationState>
    <AuthorizeView>
        <Authorized>
            <p>Hello : @context.User.FindFirstValue(ClaimTypes.Name)</p>
            <p role="status">Current count: @currentCount</p>
            <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
        </Authorized>
        <NotAuthorized>
            <p>You are not Authorized</p>
        </NotAuthorized>
    </AuthorizeView>
</CascadingAuthenticationState>
```
### The reason for my question
I should write CascadingAuthenticationState once in the Routes.razor and not rewrite it on every page.
This is what I know if this changed with .net8 please let me know.

**Comment by byr0n3** [comment]
I encountered the same issue. After a bit of struggling I noticed [this part](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio#unauthorized-content-display-while-prerendering-with-a-custom-authenticationstateprovider) of the documentation. What fixed it for me specifically was adding `@rendermode="@(new ServerRenderMode(false))"`
to the `<Routes />` and `<HeadOutlet />` components in my `App.razor` file, like so:
```razor
<HeadOutlet @rendermode="@(new ServerRenderMode(false))" />

<Routes @rendermode="@(new ServerRenderMode(false))" />
```
This forces everything that's rendered by these components to be server-side rendered. Which makes sense, the scoped services for authentication are running on the server. 

The downside to this is that you can't have any WebAssembly rendered components anymore. To have WebAssembly rendered components you'll have to remove the `@rendermode` attribute from your `Routes` and `HeadOutlet` components and wrap every component with the `CascadingAuthenticationState` component.

Hopefully we can figure out a way to have the best of both worlds, but currently we'll have to pick one or the other.

**Comment by augustevn** [comment]
@Ali1Jamal I encountered this error before and have it on video, however, for me it was just about registering the `CustomAuthenticationStateProvider`. I do notice, you're not using the `AuthorizeRouteView` on the `App.razor`.
Feel free to watch the video:  [Bearer Token Authentication with Blazor WASM in C# .NET 8](https://youtu.be/7kyIEnQ8kF4?si=GiKwiNIgaJdaTEEN&t=533)

**Comment by SteveSandersonMS** [comment]
Instead of using `<CascadingAuthenticationState>`, please try calling `builder.Services.AddCascadingAuthenticationState();` in your `Program.cs`. That will make the cascading state enabled across all rendermodes.

The reason it's not sufficient to use `<CascadingAuthenticationState>` at the root is that cascading parameters do not cross rendermode boundaries (they can't do, that would mean serializing arbitrary, often unserializable, things).

**Comment by Ali1Jamal** [comment]
@SteveSandersonMS Thank you so much for your suggestion. It worked perfectly and solved the problem. You are awesome. I really appreciate your time.

**Comment by Ali1Jamal** [comment]
@augustevn  
like and subscribe 👏.
And I will also pay attention to the points you mentioned.

**Comment by Ali1Jamal** [comment]
@byr0n3 
I appreciate your time and attention. With the help of @SteveSandersonMS’s suggestion, I was able to solve the problem successfully.
The solution he suggested was very simple but effective.
