### ISSUE TITLE
NETSDK1045 The current .NET SDK does not support targeting .NET 9.0. Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download

### ISSUE THREAD

**Issue by OurIslam** [dotnet/aspnetcore#50960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i am getting this error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download	ConsoleApp1	............................\dotnet\sdk\9.0.100-alpha.1.23474.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	166	

i have place the binary correctly 
9.0.100-alpha.1.23477.3

here is my csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>
```

and here is nuget.config
`
 <add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
`
visual studio version 
17.8.9 preview 2.0

is there anything else to use dotnet 9?

### .NET Version

9.0.100-alpha.1.23474.1

**Comment by wtgodbe** [comment]
Thanks for contacting us, we're currently working on producing an SDK that supports `net9.0` - we're hoping to get there within the next month or so. For now, closing this issue as expected.
