### ISSUE TITLE
.NET Minimal API BadRequest response does not return the body

### ISSUE THREAD

**Issue by KeithBarrows** [dotnet/aspnetcore#50964]
### Description

[StackOverflow](https://stackoverflow.com/questions/77183238/net-minimal-api-badrequest-response-does-not-return-the-body)

Duplicated here...

```
app.MapPost($"{root}/v1/AuthenticateUser"
    , async Task<Results<Ok<GetTokenForResponse>, BadRequest<ErrorModel>>> 
    (HttpContext httpContext, IMediator mediator, AuthenticateBody body) =>
{
    var response = await mediator.Send(new AuthenticateUserHandler.Request(httpContext, body.UserName, body.Password));
    if (response.IsSuccessful)
        return TypedResults.Ok(response.Result);
    return TypedResults.BadRequest(response.Error);
})
.WithTags(root);
```
I am currently running on .NET 7
I am not finding any clues as to why the BadRequest method will NOT return the body
[Results.BadRequest Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.results.badrequest?view=aspnetcore-7.0#BadRequest(Object)) on MS Docs

It appears that this should be returning whatever object is defined at the get go. But, for some reason, it is not. Am I missing something?

```
public record BaseResponse<T>
{
    public HttpContext? HttpContext { get; set; }
    public bool IsSuccessful => Error is null && Result is not null;
    public ErrorModel? Error { get; set; }
    public T? Result { get; set; }
}
```
In this example, T is of a class called GetTokenFor_Response. The Ok path returns a valid body. The BadRequest does not.

NOTE: Adding screenshot of Response object coming back from Mediatr:
![image](https://github.com/dotnet/runtime/assets/3630422/701cdebc-5232-438f-a18f-253b63ab0755)

### Reproduction Steps

```
app.MapPost($"{root}/v1/AuthenticateUser"
    , async Task<Results<Ok<GetTokenForResponse>, BadRequest<ErrorModel>>> 
    (HttpContext httpContext, IMediator mediator, AuthenticateBody body) =>
{
    var response = await mediator.Send(new AuthenticateUserHandler.Request(httpContext, body.UserName, body.Password));
    if (response.IsSuccessful)
        return TypedResults.Ok(response.Result);
    return TypedResults.BadRequest(response.Error);
})
.WithTags(root);
```

### Expected behavior

The body of the 400 response should be populated.  otherwise, why pass in an object for this method?

### Actual behavior

Empty body is returned.

### Regression?

Did not try.

### Known Workarounds

unknown at this time

### Configuration

.NET 7
Windows 10 Professional
x64
Did not try other configurations

**Comment by captainsafia** [comment]
@KeithBarrows Assume I'm understanding correctly, you're observing the behavior where if `response.IsSuccessful == false` then you you're getting a response with a 400 status code but the `ErrorModel` is not populated in the response body as JSON?

Are you able to reproduce this issue if you return the error model directly _without_ using the `BadRequest` result type? This will help isolate if the issue is related to serialization of that type in particular.

**Comment by KeithBarrows** [comment]
Changed the Error object like this and it now works. The error was not in the BadRequest method per se. It was a record that did not have public getters? I think?  I don't 100% understand it - yet!
![image](https://github.com/dotnet/aspnetcore/assets/3630422/8b28958b-d58d-42ec-9a03-a9ffa8a08733)

With this change the schema now shows up in swagger and the BadRequest method does properly display the json results for this object.
