### ISSUE TITLE
Upload files to a minimal API endpoint in .NET 8

### ISSUE THREAD

**Issue by affableashish** [dotnet/aspnetcore#50968]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug
**Edit:** I'm aware that I can simply add `.DisableAntiforgery();` to my API endpoint as explained [here](https://github.com/dotnet/aspnetcore/issues/49929#issuecomment-1670156132), but I'd like to do this the proper way.

---

I'm trying to upload a file from a Blazor component in the client side to a backend Minimal API endpoint using an Http POST call but after many failed attempts, I'm posting this question here.

I first tried this in my backend API as documented [here](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?source=recommendations&view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection):

    app.MapPost("/upload_many", async (IFormFileCollection myFiles) =>
    {
        foreach (var file in myFiles)
        {
            // Do my thing
        }
    });

Sent the request to the backend API using Swagger UI:

<img src="https://i.stack.imgur.com/OfGy2.png/250" width="300" />

I was hit with this error: 😩

    System.InvalidOperationException: Endpoint HTTP: POST /upload_many contains anti-forgery metadata, but a middleware was not found that supports anti-forgery.
    Configure your application startup by adding app.UseAntiforgery() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAntiforgery() must go between them. Calls to app.UseAntiforgery() must be placed after calls to app.UseAuthentication() and app.UseAuthorization().
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAntiforgeryMiddlewareException(Endpoint endpoint)
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
       at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
       at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I then tried [this](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0&preserve-view=true#antiforgery-with-minimal-apis-1).

Created an extension:

    public static TBuilder ValidateAntiforgery<TBuilder>(this TBuilder builder) where TBuilder : IEndpointConventionBuilder
    {
        return builder.AddEndpointFilter(routeHandlerFilter: async (context, next) =>
        {
            try
            {
                var antiForgeryService = context.HttpContext.RequestServices.GetRequiredService<IAntiforgery>();
                await antiForgeryService.ValidateRequestAsync(context.HttpContext);
            }
            catch (AntiforgeryValidationException)
            {
                return Results.BadRequest("Antiforgery token validation failed.");
            }
    
            return await next(context);
        });
    }

And used it in `Program.cs` in my backend API:

    //...
    builder.Services.AddAntiforgery();
    //...
    var app = builder.Build();
    //...
    app.UseAntiforgery();
    app.MapPost("/upload_many", async (IFormFileCollection myFiles) =>
    {
        foreach (var file in myFiles)
        {
            // ...
        }
    }).ValidateAntiforgery();
    //...

I was hit with this error: 😫

    Microsoft.AspNetCore.Http.BadHttpRequestException: Invalid anti-forgery token found when reading parameter "IFormFileCollection myFiles" from the request body as form.
     ---> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.D1Rd6RA9i3g" is not present.
       at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
       at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
       --- End of inner exception stack trace ---
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.InvalidAntiforgeryToken(HttpContext httpContext, String parameterTypeName, String parameterName, Exception exception, Boolean shouldThrow)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForForm>g__TryReadFormAsync|102_0(HttpContext httpContext, String parameterTypeName, String parameterName, Boolean throwOnBadRequest)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
    --- End of stack trace from previous location ---
       at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
       at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I'm beginning to think that I'm not doing this right. And I couldn't find a working example in the documentation.

Is there a simple way to upload files from a client side to a minimal API endpoint in .NET 8?

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

Also asked this question at [StackOverflow](https://stackoverflow.com/q/77189996/8644294).

**Comment by captainsafia** [comment]
> I'm beginning to think that I'm not doing this right. And I couldn't find a working example in the documentation.

We just pushed the docs for this recently. You can find them [in this section](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0#antiforgery-with-minimal-apis).

Some things I am noticing with your code sample:
- You shouldn't need the `ValidateAntiforgery` filter. The framework is doing the anti-forgery token validation automatically for you in the middleware registered via `UseAntiforgery`.

Have you verified that the anti-forgery cookie and token are sent in the payload associated with the request to the API?

**Comment by affableashish** [comment]
Thank you for the response @captainsafia !
I went through the docs you linked but I'm not sure how to pass anti-forgery cookie to my API endpoint during a Swagger call / or from a client project running on a different url than the API which is what I'll be doing after figuring out the Swagger part first.

Can you take a look at my very simple code example and give me some pointers?

Code Repo:
https://github.com/affableashish/fileupload-minimal-api/blob/main/API/Program.cs

The way I'm testing:
1. Launch Swagger UI
<img width="1815" alt="image" src="https://github.com/dotnet/aspnetcore/assets/30603497/c482cefc-d28d-4856-926f-2205ed1c1d13">

2. Upload an image
<img width="933" alt="image" src="https://github.com/dotnet/aspnetcore/assets/30603497/bfe70b93-900b-41e0-9775-5e0c01f180d3">

3. Run into the error
<img width="1750" alt="image" src="https://github.com/dotnet/aspnetcore/assets/30603497/dad47fad-1d66-4008-9dd6-e8c9b9d722e2">

**Comment by affableashish** [comment]
Hi @captainsafia,
I figured this out after going through [this](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0#antiforgery-with-minimal-apis). Thank you for your help. You can close this issue.

Also updated my StackOverflow [answer](https://stackoverflow.com/a/77191406/8644294).
Full source code [here](https://github.com/affableashish/fileupload-minimal-api).

As [per the docs](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?source=recommendations&view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection), to be able to upload files you need an Authorization header, a client certificate, or a cookie header.

To satisfy that requirement, I decided to pass *Antiforgery token* with the file upload POST request.

Now my API endpoints looks like this:

    // Get token
    app.MapGet("antiforgery/token", (IAntiforgery forgeryService, HttpContext context) =>
    {
        var tokens = forgeryService.GetAndStoreTokens(context);
        var xsrfToken = tokens.RequestToken!;
        return TypedResults.Content(xsrfToken, "text/plain");
    });
    //.RequireAuthorization(); // In a real world scenario, you'll only give this token to authorized users
    
    // Add my file upload endpoint
    app.MapPost("/upload_many", async (IFormFileCollection myFiles) =>
    {
        foreach (var file in myFiles)
        {
            // ...
        }
    
        return TypedResults.Ok("Ayo, I got your files!");
    });

So I've got 2 endpoints now:

<img src="https://i.stack.imgur.com/eyJsr.png/150" width="300" />

Upload the file
---

**Step 1:**
Get the token.

<img src="https://i.stack.imgur.com/uvx1k.png/450" width="800" />


**Step 2.1:**
Before making the POST call to Upload endpoint, add the XSRF token you received from Step 1.

<img src="https://i.stack.imgur.com/3oyPX.png/250" width="500" />

**Step 2.1:**
Add the file you want to upload. *pickle.png* in my case.

<img src="https://i.stack.imgur.com/C49zk.png/250" width="400" />

**Step 2.3:**
Hit send. At this point, you'll be able to make a successful call.

<img src="https://i.stack.imgur.com/hYWAR.png/250" width="600" />

Please let me know if this approach can be improved. Thank you!

**Comment by augustevn** [comment]
@affableashish I recently had a similar issue, turns out I just had to remove `app.UseRouting()` to resolve this.
I have it on video, feel free to watch:  [DOTNET 8 Blazor Upgrade!]{https://youtu.be/x56w_VDLFJo?si=HVBphlDz73QVOiqa&t=310}

**Comment by LuisMars** [comment]
Same thing happened to me:

``` 
using Microsoft.AspNetCore.Http.Features;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();

builder.ConfigureSwagger("Audio Converter");
builder.ConfigureAuth();

builder.Services.AddLogging();
var app = builder.Build();

app.MapPost("/convert", (HttpContext context, [Required] IFormFile audioFile, ILogger<Program> logger, [DefaultValue(AudioFormat.Aac)] AudioFormat audioFormat) =>
{
    // do the thing
});

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseCors("AllowBlazorOrigin");

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.Run();
``` 

Version: 8.0.100-rc.1.23455.8
I could not solve it removing routing or others.

It works fine if you use a controller.

**Comment by augustevn** [comment]
@LuisMars Yes, same here.

For now, I'll do it like this:

``` csharp

        routeGroup.MapPost("/", async (HttpContext ctx) =>
        {
            var formFiles = ctx.Request.Form.Files;
            ...
            return Results.Ok();
        });

```

**Comment by captainsafia** [comment]
@LuisMars @augustevn Yes, this is expected behavior now that we've added support for an anti-forgery middleware in minimal APIs. You can read more about this [here](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0#antiforgery-with-minimal-apis).

I think this change might be tripped up folks who are migrating from 6.07.0 so I'll file a breaking change notice.
