### ISSUE TITLE
Enhance Blazor Web .reconnect to state whether failures are due to circuit not existing so we can auto-reload page

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#50979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The custom connection establishment solution is not working in Blazor Web. I discussed a similar problem here https://github.com/dotnet/aspnetcore/issues/44669, it has also been fixed. 

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md#automatically-refresh-the-page-when-reconnection-fails-blazor-server

By the way, you can fix the problem of forcing a refresh of the browser window. It should be possible to establish a connection in the state in which it was interrupted.

**Comment by MackinnonBuck** [comment]
This is probably due to the fact that the shape of the object that gets passed to `Blazor.start()` has a different shape for `blazor.web.js` than it does for `blazor.server.js`.

The example would have to be updated to look like:

```js
Blazor.start({
  circuit: {
    reconnectionHandler: {
      onConnectionDown: () => currentReconnectionProcess ??= startReconnectionProcess(),
      onConnectionUp: () => {
        currentReconnectionProcess?.cancel();
        currentReconnectionProcess = null;
      },
    },
  },
});
```

@guardrex could we update the docs to include this detail? Thanks!

**Comment by mkArtakMSFT** [comment]
Closing as the remaing work is tracked by the issue @guardrex filed and linked above (Thanks).
