### ISSUE TITLE
Make RazorLanguageVersion.Experimental round-trippable

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#5098]
When serializing RazorLanguageVersion we serialize the `ToString()` output of it. However, when reading it back-in via deserialization that the `RazorLanguageVersion.Parse` doesn't understand the version (`1337.1337`).

**Comment by mkArtakMSFT** [comment]
Closing this. If this is important, please reopen and put in appropriate milestone, @NTaylorMullen

**Comment by NTaylorMullen** [comment]
It's important for LiveShare and VSCode scenarios.
