### ISSUE TITLE
Blazor Server not disposing propertychange events.

### ISSUE THREAD

**Issue by Pinox** [dotnet/aspnetcore#50989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Guys,

Please find attached a small repo where the PropertyChanged events are not getting disposed in Blazor Server ( render-mode="Server"  ). So when the user navigates from page to page the PropertyChanged events are continually getting added. In larger apps the view starts freezing up when the user start navigating often in the app.

![image](https://github.com/dotnet/aspnetcore/assets/5297255/277747e8-5cf4-4f2e-a4b6-1d6cdbede330)

To reproduce Load the data, then start the timer.   The date field should continuously increment by 1.  Start navigating to the "other" view and back  and check the output window.  Doing this repetitively result in events only being added and never deleted or disposed off.

![image](https://github.com/dotnet/aspnetcore/assets/5297255/50eb63e6-b62a-40eb-9f8b-336d8b567b17)

Please let me know if I'm doing something silly or if there is a workaround.

### Expected Behavior

Change events should be disposed.

### Steps To Reproduce

[TestEvents_BlazorServer.zip](https://github.com/dotnet/aspnetcore/files/12750160/TestEvents_BlazorServer.zip)

### .NET Version

8.0.100-rc.1.23455.8

**Comment by gragra33** [comment]
@Pinox I made a couple of changes to your code and it resolves your issue.

```cs
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        State.PropertyChanged += OnPropertyChanged;

        // State.PropertyChanged += async (o, e) =>
        // {
        //     await InvokeAsync(StateHasChanged);
        //     Debug.WriteLine("State.PropertyChanged => StateHasChanged : " + DateTime.Now.Second);
        // };
    }

    await base.OnAfterRenderAsync(firstRender);
}

private void OnPropertyChanged(object? sender, PropertyChangedEventArgs args)
{
    Debug.WriteLine("State.PropertyChanged => StateHasChanged : " + DateTime.Now.Second);
    InvokeAsync(StateHasChanged);
}

public void Dispose()
{
    Debug.WriteLine(" Dispose() : " + DateTime.Now.Second);

    State.PropertyChanged -= OnPropertyChanged;

    // State.PropertyChanged -= async (o, e) =>
    //     {
    //         await InvokeAsync(StateHasChanged);
    //     };
}
```

**Comment by Pinox** [comment]
Hi @gragra33 , you're a star !!
