### ISSUE TITLE
Blazor Web App template fails to compile when selecting Auto, Global

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50980]
Repro steps:

- Install .NET 8 RC2 (8.0.100-rc.2.23477.19)
- Create a Blazor Web App template with Auto selected for the interactivity type and Global for the interactivity location
- Build and run

Expected result: App builds
Actual result:

C:\Users\user\source\repos\BlazorApp1Test\BlazorApp1Test.Client\Pages\Error.razor(28,33,28,44): error CS0246: The type or namespace name 'HttpContext' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jinzhao1127** [comment]
This issue also repro when selecting `WebAssembly`, `Global`

**Comment by jinzhao1127** [comment]
Verify this bug was fixed on the latest .NET 8.0-rtm build.

**Comment by Alan-Steadman** [comment]
So cannot use 8 RC2? to trial blazor???  Have to wait for RTM version??

**Comment by danroth27** [comment]
> So cannot use 8 RC2? to trial blazor??? Have to wait for RTM version??

Hi @Alan-Steadman. This compilation error has an easy workaround: just copy the Error.razor file from the client project to the server project.

**Comment by Alan-Steadman** [comment]
Thanks - looks like I've got a similar-looking but different issue then:

Create new "Blazor Web App" (called "ffs", Auth Type = none, Interactivity Type = Auto, Per Page/Component)

Try to build... build fails saying (twice) "error CS0246: The type or namespace name 'ffs' could not be found (are you missing a using directive or an assembly reference?)".  The two errors appear in the error list (program.cs, line 1, "using ffs.Client.Pages" and line 2 "using ffs.Components".  When double clicking the errors, the program.cs file opens with red squiggles on those two lines, which promptly disappear after a few seconds, and disappear from the error list, but any attempt to build or run result in the same build error, but the errors don't then appear in the error list.

I'm using VS 2022 17.7 with the option enabled to use previews of the .Net SDK, I've got .Net SDK 8 RC2 installed and I've restarted, and created three projects and all have the same issue.

Should I log this as a new issue?

**Comment by danroth27** [comment]
> I'm using VS 2022 17.7 with the option enabled to use previews of the .Net SDK

You need to use VS 2022 17.8 with .NET 8. While in some cases using 17.7 may work with .NET 8 projects, there are known incompatibilities. Please try the latest 17.8 preview and verify whether it resolves your issue.

**Comment by Alan-Steadman** [comment]
Thanks @danroth27, much appreciated.  Yes, I've installed VS2022 17.8 Preview following [these steps](https://www.c-sharpcorner.com/article/how-to-enable-preview-version-in-visual-studio-2022/) and it works.  Many thanks for your help!

**Comment by peterhvogel** [comment]
Just used the Blazor Web App template with Visual Studio 17.8.0 Preview 7.0 and ASP.NET and Web Tools 17.8.350.26616 and had this problem.

**Comment by danroth27** [comment]
HI @peterhvogel. This issue is fixed for the upcoming .NET 8 release, but you can work around it with .NET 8 RC2 by moving Pages/Error.razor from the client project to the server project. See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-2#known-issues for details.

**Comment by peterhvogel** [comment]
Did that! Thanks.

Yours truly,

Peter Vogel, MBA
    My mama died and left me
    My papa died and left me
    I ain’t good looking, baby
    But I’m somewhat sweet and kind
        - “Statesboro Blues” by Blind Willie McTell

***@***.***
