### ISSUE TITLE
WPF/Blazor Hybrid - web events not fired when Razor pages are in a separate Razor control library

### ISSUE THREAD

**Issue by deanchalk** [dotnet/aspnetcore#50990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Microsoft example pages for using Blazor Hybrid in a WPF application work perfectly if the razor components are in the same project as the WPF application.
However, if you create a separate Razor control library and put the razor component in that, you can see the HTML render of the component but none of the events work (onclick of button for example)
I have tried shuffling all of the key files around and trying lots of different variations of the setup explained in the Microsoft guidance, but nothing works.
This is important as I am going to be introducing Blazor Hybrid components to a large WPF app, but the razor pages cant live in the same main WPF project - they have to be in a separate project.
I have even tried creating a separate usercontrol project and trying to host the razor components inside usercontrols but that doesnt work on any level.
Any ideas?

### Expected Behavior

Adding razor components that live in a separate project to a WPF application should work the same as if the razor component was in the WPF application itself

### .NET Version

7.0

**Comment by gragra33** [comment]
@deanchalk Hard to tell what issue you are having as no sample project is posted. However, I have a sample project where I have the pages in a separate RCL library (.Core) where the lib is shared between Wasm, Wpf Hybrid, & Avalonia Hybrid projects. Here is a link: [MvvmSampleBlazor](https://github.com/gragra33/MvvmSampleBlazor)

**Comment by deanchalk** [comment]
That’s fantastic, will give it a try - thanks

**Comment by deanchalk** [comment]
I have added a sample project to Github that demonstrates the issue. Run solution and 'click' button for updating counter doesnt work, yet the same razor file in the main WPF project does work
https://github.com/deanchalk/BlazorHybridError

**Comment by gragra33** [comment]
@deanchalk I've had a look at your repo. I can see your issue. 

First thing, you're referencing a .Net 6.0 assembly. Not critical, but this needs to be updated to a .Net 7.0 version:
```xml
<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="6.0.553" />
```

Your `BlazorHybridTest.Razor` project is the issue. To resolve:
1. removed the `BlazorHybridTest.Razor` project reference from `BlazorHybridTest` project
2. added a new `WpfFix.Razor` _**Razor Class Library**_ project
3. removed the unwanted template files
4. added the `CounterControl` component
5. added a reference in `BlazorHybridTest` to the new `WpfFix.Razor` project
6. fixed namespace reference in `MainWindow.xaml`

Now, when I run the project the `CounterControl` component button works.

There was something weird going on in the whole solution with the  `BlazorHybridTest.Razor` project. Removing all `\bin` & `\obj` folders and recompiling did not fix it. So adding a new project, with a different project name  `WpfFix.Razor` fixed the issue.

I don't have the time to dig further into it to identify exactly why. I will leave this to you.

**Comment by deanchalk** [comment]
Wow @gragra33 , I followed your instructions and it worked!!!
No idea what was wrong with my original Razor Class Library, but it works now.
Thanks so much for your efforts - much appreciated

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @gragra33.
Closing as no further action is pending here.
