### ISSUE TITLE
Rename the "ASP.NET Core Web App" template to "ASP.NET Core Razor Pages App"

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#50999]
In .NET 8 we are positioning Blazor as our recommended way to get started with building web UI with .NET and ASP.NET Core. Previously we would direct new users to use Razor Pages. To make it clear that the Razor Pages template was the preferred starting point, we game the Razor Pages template a very generic name: "ASP.NET Core Web App". Now that Razor Pages is no longer the preferred starting point, we should rename the template to be more specific: "ASP.NET Core Razor Pages App"

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Perhaps better to keep with the naming scheme we used for MVC when we added Razor Pages, do we'd end up with:

- ASP.NET Core Web App
    *This uses Blazor*
- ASP.NET Core Web App (Razor Pages)
    *This uses Razor Pages*
- ASP.NET Core Web App (Model-View-Controller)
    *This uses controllers and views*

Of course the challenge then is where does "Blazor App" fit in. Perhaps it's duplicated so that folks can just get to it either way.

**Comment by danroth27** [comment]
Yeah, this raises an interesting set of issues:
- We want to make it clear that the recommended way to build an ASP.NET Core Web App is with Blazor
- We want to make it clear that Blazor app is an ASP.NET Core app
- We don't want the template name to be long and cumbersome

I don't love just taking over the ASP.NET Core Web App name with Blazor because then it's not clear that the template uses Blazor. And having two entries for the same template feels weird 😆

**Comment by DamianEdwards** [comment]
Options:

- ASP.NET Core Web App (Blazor)
- ASP.NET Core Blazor Web App
- Blazor Web App (ASP.NET Core)
- Blazor App (ASP.NET Core)

**Comment by Alerinos** [comment]
How about something like this?

- ASP.NET Blazor Web App
- ASP.NET Blazor WASM App
- ASP.NET Blazor SSR App (In theory, the SSR has been replaced by the Web)
- ASP.NET Razor App
- ASP.NET MVC App

Everyone knows what Razor, Blazor and MVC are, I think that's the easiest way to call templates.
Server side has been replaced by Web but WASM will still be used separately even though it is already Web.

**Comment by danroth27** [comment]
@Alerinos Thanks for the suggestions! 

We need to keep the "Core" in "ASP.NET Core" because we want to avoid confusion with ASP.NET for .NET Framework.

We also don't need a separate Blazor SSR template, because the new Blazor Web App template already has an option for that: `dotnet new blazor -int None`.

We also don't want to assume that everyone knows what these technologies are because we want to be approachable by new users who've potentially never used .NET before.

Lastly, we typically also prefer WebAssembly to WASM in our naming because that's the name from the spec.

I'm currently leaning towards this:
- Blazor Web App
- ASP.NET Core Web App (Razor Pages)
- ASP.NET Core Web App (Model-View-Controller) 

I know "Blazor Web App" doesn't make it clear that it's also an ASP.NET Core app, but I prefer the shorter name and we can clarify the ASP.NET Core relationship in the description. Thoughts?

**Comment by gragra33** [comment]
It makes sense to stick with
* ASP.NET Core Web App (Razor Pages)
* ASP.NET Core Web App (Model-View-Controller)
You also currently have, which I believe will still be supported:
* Blazor Server App
* Blazor WebAssembly App
* Blazor Server App Empty
* Blazor WebAssembly App Empty 

The new "Blazor Web App" is a merge of both `ASP.NET Core Web App (Razor)` and multiple flavours of Blazor. So would it not make sense to use:  `ASP.NET Core Web App (Blazor)`?

The other option is for just a single `ASP.NET Core Web App` and has a selector for:
* Blazor
* Razor
* Model-View-Controller
* Web API
Then each has its own fine-tuning of options for creating the solution.

Lastly, there is one more type overlooked - ASP.NET Web App (Minimal API)...

**Comment by DamianEdwards** [comment]
@gragra33 we've been hesitant to restructure the templates the way you suggest with options that ask the user to choose what stack they want, as it can also impact the CLI experience (CLI and VS share templates).

That said, .NET 9 would be a reasonable time to revisit this and see if some template consolidation could result in a reasonable experience that satisfies most scenarios (new users, existing users, VS, CLI, etc.).

**Comment by DamianEdwards** [comment]
@danroth27 

> I know "Blazor Web App" doesn't make it clear that it's also an ASP.NET Core app, but I prefer the shorter name and we can clarify the ASP.NET Core relationship in the description. Thoughts?

The concern I have with this suggestion is that existing users will be more likely to just select "ASP.NET Core App (Razor Pages)" rather than gravitating towards our intended "new default" of Blazor.

**Comment by gragra33** [comment]
@DamianEdwards I hear what you are saying however there is a large number of templates to choose from and feel that consolidation of some is overdue.

If not consolidation, then suggest keeping the same naming convention to lessen the overload of everything new. `ASP.NET Core Web App (Blazor)` fits but I also understand from a marketing perspective that there is a need to set the new default.

You still have the question of how React and Angular fit into this...

**Comment by filipoff2** [comment]
ASP.NET 2024  is maximum business can understand. 
Although 2025 look more cool,  pushing names as  Silverlight, XAMARIN, Windows Phone/mobile confuzed, MAUI, even Blazor was hard and too abstract thing.

**Comment by csharpfritz** [comment]
I have a concern with changing the framework used in the "Web App" template breaks all documentation and tutorials that have been built on previous versions of ASP.NET Core.  That content expects Razor Pages and would be somewhat forward-compatible without this change

**Comment by jamesmontemagno** [comment]
So many choices! Less is more, it should be really clear. 

I like what Damian had, but if you want could tweak it to add (Blazor) to the first so it is clear. And while it would break how docs expect it, it would still be more obvious.

ASP.NET Core Web App (Blazor)
ASP.NET Core Web App (Razor Pages)
ASP.NET Core Web App (Model-View-Controller)

They should be organized and numbered correct as well.

Although if I am a new developer I still may be confused. With Xamarin.Forms and now .NET MAUI it is pretty simple with 1 template and just does it. With Xamarin.Forms you had different setup styles with or without shell, but just 1 template that asked you want you wanted. I don't think this is possible based on how the templates exist today.

**Comment by Aquaritek** [comment]
A community perspective:

Largely outside this repository Microsoft is regarded as subpar at naming conventions and choices. You will find this idea ubiquitous across almost all forms of media when a name change occurs or is proposed. That being said the larger community rarely pays close enough attention to get involved - where they could have had input.

Since Blazor is now just that "Blazor" but existing legacy web application templates are adorned with ASP.NET Core X - I would argue the convention already exists and should be followed. So, what @jamesmontemagno mentioned is clearly the logical preference and what I believe should be considered here overall.

I would argue that "Model-View-Controller" could for conciseness be changed to "Razor MVC"

With peace, Aqua.
