### ISSUE TITLE
Access an RCL's static assets from an RCL Library in a Blazor WASM

### ISSUE THREAD

**Issue by tlantola** [dotnet/aspnetcore#51002]
# Goal - Access an RCL's static assets from an RCL Library in a Blazor WASM.

**Setup:** I followed the documentation page for [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-7.0&tabs=visual-studio).  I tested static assets in the RCL library as documented here [Create an RCL with static assets in the wwwroot folder](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-7.0&tabs=visual-studio#create-an-rcl-with-static-assets-in-the-wwwroot-folder).

**Expected** When the ComponentLibrary is a project in my solution and I reference its project by adding a Project Referece, everything works as documented.  When I go to the /jeep page, I see the two images of the jeep.  Upon examination of my Blazor WASM project file, I see an ItemGroup that looks like the following:

`<ItemGroup>
  <ProjectReference Include="..\ComponentLibrary.csproj" />
</ItemGroup>`

**Unexpected** When I remove the ComponentLibrary project from my solution, I see the above mentioned ItemGroup removed.  I then add a project reference to the ComponentLibrary.  When I do, I see a new ItemGroup added to my Blazor WASM project file that looks like the following:

`<ItemGroup>
  <Reference Include="MyAssembly">
    <HintPath>..\ComponentLibrary\bin\Debug\net7.0\ComponentLibrary.dll</HintPath>
  </Reference>
</ItemGroup>`

When I debug this from VS 2022 Version 17.7.4 and navigate to the jeep page.  I see the two images of the jeep which I believe are cache from when I ran it with the ComponentLibrary still referenced in my solution.  To confirm it is working with the ComponentLibrary project removed from my solution, I cleared my browser cache and refreshed the page.  ***Now when I debug the Blazor WASM project, the jeep images are missing when I navigate to the /jeep page.***

According to the [Create reusable UI using the Razor class library project in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-7.0&tabs=visual-studio#reference-rcl-content) documentation, this should work as further documented by the line that reads {ProjectName}.csproj. See [dotnet add reference](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference).

The link to the ***dotnet add reference*** page has a section for [Add a reference to an assembly that isn't in a project](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference#add-a-reference-to-an-assembly-that-isnt-in-a-project) which states the second ItemGroup is correct as shown by their example, i.e. `<ItemGroup>
  <Reference Include="MyAssembly">
    <HintPath>".\MyDLLFolder\MyAssembly.dll</HintPath>
  </Reference>
</ItemGroup>`

**Why do I want to do this?**  I am trying to build a Blazor WASM framework for supporting Micro Frontends where I can build each feature of my application in separate solutions and then bring them all together by lazy loading them in a portal that utilizes the Micro Frontend framework I created.

**Comment by javiercn** [comment]
@tlantola thanks for contacting us.

RCLs only work with `ProjectReference`.
