### ISSUE TITLE
.NET 8 RC1 Blazor Web App Deployed to IIS Can't Find Resources

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#51027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-8-RC1-Blazor-Web-App-Deployed-to-II/10474053)._

---
[severity:I'm unable to use this version]
I created a Blazor Web App using the default settings. Then I deployed it to IIS
but it can't find any resources (wwroot).

![image.png](https://aka.ms/dc/image?name=Bcb8894f54d96484f8d1d7d4b7c9b360e638310821338427259_20230923-100853-image.png&tid=cb8894f54d96484f8d1d7d4b7c9b360e638310821338427259)

If I create a Blazor Server App using the default settings and deploy it to ISS it finds all the resources.

![image.png](https://aka.ms/dc/image?name=B73425f995e074600b9fdd3aa60a15b06638310822399311389_20230923-101039-image.png&tid=73425f995e074600b9fdd3aa60a15b06638310822399311389)

For example, say my url = https://MyServer/F1/F2/MyApp

The Blazor Server App uses the full path to look for the resources.
The Balzor Web App looks for the resources at https://MyServer - it misses the 'F1/F2/MyApp' part.

---
#### Feedback Bot on 9/24/2023, 06:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please take a look at https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#virtual-directories and see if that helps solve your issue?

**Comment by halter73** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0#iis might be useful. Specifically this part:

> Configure [StaticWebAssetBasePath](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-7.0#static-web-asset-base-path) in the project file to match the path for serving static web assets (for example, `<StaticWebAssetBasePath>base/path</StaticWebAssetBasePath>`).

**Comment by marqdouj-spartan** [comment]
Well, I see on possible issue right away - 'use tilde-slash (~/) notation'.
The tilde-slash notation does not work in the IDE.

**Comment by marqdouj-spartan** [comment]
Well, I've tried everything I could think of (based on the articles posted) and it still can't find the content/static files.
I logged the locations on the server (IIS) at startup, and they match the physical location of where the files are located on the server:

  ContentRootPath: D:\InetPub\wwwroot\AtlasPortal\Web\Apps\Server
  WebRootPath: D:\InetPub\wwwroot\AtlasPortal\Web\Apps\Server\wwwroot

The app can't find the content or the static files.

Not sure what to try next.
Everything runs fine in IDE using IIS Express.

**Comment by marqdouj-spartan** [comment]
I tried changing the base in the head to the 'tilde notation':  <base href="~/" />

Now the static files are being mapped to:
https://<my server>/AtlasPortal/Web/Apps/~/

For example, the tooltip for bootstrap.min.css shows:  
https://<my server>/AtlasPortal/Web/Apps/~/bootstrap/bootstrap.min.css

It's not finding the "Server/wwwroot" portion of the url but shows "~/" instead.

**Comment by marqdouj-spartan** [comment]
Something went wrong with my last post - it stripped out the <my server> portion of the url and shows //// instead.

**Comment by mkArtakMSFT** [comment]
> I tried changing the base in the head to the 'tilde notation':

Using `~` notation isn't supported in Blazor. Try using `<base href="/mvirtualdir/">` and see if that works.

**Comment by marqdouj-spartan** [comment]
According to this article ~/ is supported in blazor:
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#configure-the-app-base-path

In any case, <base href="/F1/F2/MyApp/"> did work when published to IIS. However, it doesn't work in the IDE. I'll just have to figure out if I can set the base path in program.cs instead; based on IsDevelopment or not.

**Comment by marqdouj-spartan** [comment]
Forgot to mark html so it was stripped out in my last reply.
`<base href="/F1/F2/MyApp/">` did work.

**Comment by marqdouj-spartan** [comment]
I tried `app.UsePathBase("/F1/F2/MyApp");` in program.cs (according to the article) and that did not work.
So for now, I'll just have to remember to uncomment the `<base href="/F1/F2/MyApp/">` when publishing to IIS

**Comment by halter73** [comment]
> According to this article ~/ is supported in blazor:
> [learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#configure-the-app-base-path](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#configure-the-app-base-path)

I think it is for "Blazor Server", but not necessarily with the new Blazor auto/static rendering. @SteveSandersonMS would know better.

It's probably better to look at the 8.0 docs since you're on RC1: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#configure-the-app-base-path

I created a PR at #30632 to fix https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#virtual-directories to link to the Blazor docs.

**Comment by marqdouj-spartan** [comment]
What about getting it to work in the IDE?

**Comment by SteveSandersonMS** [comment]
> I think it is for "Blazor Server", but not necessarily with the new Blazor auto/static rendering. @SteveSandersonMS would know better.

Tilde is supported in `.cshtml` but not in `.razor`.

In .NET 7 the host page was `.cshtml` but in .NET 8 it's `.razor`.

**Comment by halter73** [comment]
> What about getting it to work in the IDE?

If the issue is that you need the `<base href="/F1/F2/MyApp/">` on IIS but not in development, could you do the following?

```
@inject IHostEnvironment Environment

﻿<!DOCTYPE html>
<html lang="en">
<head>
    @if (Environment.IsProduction)
    {
        <base href="/F1/F2/MyApp/">
    }
```

**Comment by marqdouj-spartan** [comment]
That worked, thanks!
Probably should add that scenario to the blazor/IIS docs.

**Comment by marqdouj-spartan** [comment]
Still wondering why App.UseBasePath() didn't work; no matter for me as it's working now.
