### ISSUE TITLE
[Feature] Async version of `IWebHostBuilder.ConfigureServices`

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#51035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Some dependencies require async creation. As a simple example, Playwright is initialised like so:
```cs
public static async Task Main(string[] args) {
  var builder = WebApplication.CreateBuilder(args);
  // ...
  var playwright = await Playwright.CreateAsync();
  var browser = await playwright.Chromium.LaunchAsync();
  var browserContext = await browser.NewContextAsync();
  services.AddSingleton(playwright);
  services.AddSingleton(browser);
  services.AddSingleton(browserContext);
  // ...
  await builder.Build().RunAsync();
}
```
This is possible due to `async Task Main()`.

But when performed in a separate assembly or reusable library, one typically uses the pattern:
```cs
builder.AddFoo();
```
Which internally does this:
```cs
webHostBuilder.ConfigureServices((context, services) => /* ... */);
```
...and that is not async.

### Describe the solution you'd like

Please expose an async version of the above, i.e.:
```cs
await webHostBuilder.ConfigureServicesAsync(/* ... */);
```

**Comment by viliml** [comment]
Why wouldn't you just do this?
```cs
public static async Task<IServiceCollection> AddPlaywright(this IServiceCollection services)
{
  var playwright = await Playwright.CreateAsync();
  var browser = await playwright.Chromium.LaunchAsync();
  var browserContext = await browser.NewContextAsync();
  services.AddSingleton(playwright);
  services.AddSingleton(browser);
  services.AddSingleton(browserContext);
  return services;
}
```

**Comment by viliml** [comment]
With StartupModules, the idiomatic way seems to be to wrap the dependencies that require async creation in a service and instantiate them in an `IApplicationInitializer`.

**Comment by javiercn** [comment]
@lonix1 thanks for contacting us.

This is not something that we plan to do. We suggest something like what @viliml proposed or creating your own solution for it.
