### ISSUE TITLE
Support DateOnly with InputDate

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51045]
According to the docs, `InputDate` currently supports `DateTime` and `DateTimeOffset`. Should it support `DateOnly` as well?

**Comment by campersau** [comment]
According to the source this is already supported:
https://github.com/dotnet/aspnetcore/blob/95b1de9ccf67adbc57919132464dac44c20e92b8/src/Components/Web/src/Forms/InputDate.cs#L98

PR: https://github.com/dotnet/aspnetcore/pull/34594

**Comment by danroth27** [comment]
This might just be a doc issue then. The ref docs for InputDate doesn't mention DateOnly support.

**Comment by mkArtakMSFT** [comment]
https://github.com/dotnet/aspnetcore/blob/cc1b45e50adaa850feac5eaf65807b0570590c6e/src/Components/Web/src/Forms/InputDate.cs#L13
