### ISSUE TITLE
Configure BearerTokenOptions when use AddIdentityApiEndpoints API

### ISSUE THREAD

**Issue by graindt** [dotnet/aspnetcore#51047]
## Background and Motivation

When employing bearer token authentication in applications, the `AddIdentityApiEndpoints` API cannot easily configure the `BearerTokenOptions`.

## Proposed API

```diff
namespace Microsoft.Extensions.DependencyInjection;

public static class IdentityServiceCollectionExtensions
{
+    public static IdentityBuilder AddIdentityApiEndpoints<TUser>(this IServiceCollection services, Action<IdentityOptions> identityConfigure, Action<BearerTokenOptions> bearerTokenConfigure);
}
```

## Usage Examples

Configure IdentityOptions and BearerTokenOptions at the same time.

```csharp
services.AddIdentityApiEndpoints<AppUser>(
    options => { }, // IdentityOptions
    options =>      // BearerTokenOptions
    {
        options.BearerTokenExpiration = TimeSpan.FromSeconds(config.GetValue<int>("BearerToken:BearerTokenExpiration"));
        options.RefreshTokenExpiration = TimeSpan.FromSeconds(config.GetValue<int>("BearerToken:RefreshTokenExpiration"));
    });
```

## Risks

This is low risk since it's entirely new API.

**Comment by halter73** [comment]
`AddIdentityApiEndpoints` adds the cookie handler too. Should we also take an `Action<CookieAuthenticationOptions>`? I think that if you want to configure authentication handler options, you're probably better off doing something like:

```csharp
services.AddIdentityApiEndpoints<AppUser>();
services.AddOptions<BearerTokenOptions>(IdentityConstants.BearerScheme).Configure(options =>
{
    options.BearerTokenExpiration = TimeSpan.FromSeconds(config.GetValue<int>("BearerToken:BearerTokenExpiration"));
    options.RefreshTokenExpiration = TimeSpan.FromSeconds(config.GetValue<int>("BearerToken:RefreshTokenExpiration"));
});
```

I think having too many overloads with various subsets of the possible options callbacks could make things less clear when it comes quickly being able to tell what callback is configuring what.

**Comment by graindt** [comment]
I agree with you. I didn't know about this usage you mentioned before, so we don‘t need to add the new api. I will close this issue.

Thank you.
