### ISSUE TITLE
Pass the circuit from the server to the client in Blazor Web for RenderModeServer

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#51053]
In Blazor Server Side there was an option to pass parameters to the "Client" circuit using parameters in <Component> in _Host.cshtml

``_Host.cshtml``
```razor
    <component type="typeof(Areas.Web.App)"
               render-mode="ServerPrerendered"
               param-GetIP="@GetIP"
               param-GetAgent="@GetAgent"
               param-CultureDefault="@Cookie.Get("Culture")"/>
```

``App.razor``
```razor
    [Parameter]
    public string GetIP { get; set; } = "";
    [Parameter]
    public string GetAgent { get; set; } = "";
    [Parameter]
    public string CultureDefault { get; set; } = string.Empty;

    protected override async Task OnInitializedAsync()
    {
// Inject Culture, set use language
    }
    
```

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.componenttaghelper.parameters?view=aspnetcore-7.0#microsoft-aspnetcore-mvc-taghelpers-componenttaghelper-parameters

Unfortunately, Blazor Web does not have this ability to pass a parameter.
This causes a problem when passing e.g. HTTPContext.
For example, we have cookies "Culture", in it we store the language code. The first SSR rendering is correct, the next one will not pass the state to the client so Blazor does not see what language is used.

Then there is a leap, blazor overwrites the server:
https://gyazo.com/28548884491d2869f4908ff6aec8e8cd

There is probably a way to fix this with ``PersistentComponentState`` but it causes a lot of problems like extra work. 

Is there any other way so as to automatically define a `` scope`` that will remember and store the settings from the server for the client?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. `PersistentComponentState` is indeed the recommended way to pass state from static server rendering to interactive server rendering.

**Comment by SteveSandersonMS** [comment]
> Is there any other way so as to automatically define a  scope that will remember and store the settings from the server for the client?

Yes, that is basically what `PersistentComponentState` is. If you try it out and find it doesn't work for your scenario please let us know.

**Comment by iphdav** [comment]
@Alerinos You will not be able to pass the HttpContext as you might be envisaging.  I don't really see an issue here appropriate to this repo so this should be closed.

In the example you gave in the _Host.cshtml, the static rendering would be the initial HTTP request and have its own HttpContext.  Where you have ```param-GetIP="@GetIP"``` that is just serializing that value into the initial static page content in such a way that it can be sent back to the server when the interactive server (signalr) version starts up.  It includes additional protections to ensure it the value has not been tampered with (which is why it appears obfuscated).

When the traditional (interactive server) mode starts up, this will be on a completely separate Http Connection and thus have a different HttpContext.  It would not make sense to attempt to pass the initial HttpContext through to the Signalr version of your component.

This isn't the forum for it, but there are lots of people who would be happy to assist further if they knew more about what you were trying to achieve.  I think you just need more high level guidance about how to approach whatever specific feature you are trying to implement.

**Comment by iphdav** [comment]
@Alerinos This isn't the forum for it, but I will add a few additional comments that might assist you understand what is happening. 

If Blazor starts in traditional server (Interactive Server) mode, then a HTTP connection will be created which is then "upgraded" to a web socket connection.  You could access the original HttpContext using IHttpContextAccessor (google examples to find out how).  However that original HTTP connection will stay open throughout the session.

If you later attempt to set a Cookie, it will *not* be reflected on that original HttpConnection for reasons you can probably reason about yourself.  In other words, the cookie collection available on the HttpConnection will be the ones that existed when the connection was created (when the original Http Response was received containing the cookie headers)

If you wanted to add new HttpOnly cookies to the context, it needs to be a Http connection (not websocket) with the Set-Cookie header, and future created http connections (and the associated HttpContext) will then have that cookie collection attached.

If you want to set non-HttpOnly cookies you could use javascript interop (or a nuget package that provides a nice API for it).  But it is always best to express what you are trying to achieve at a high level and receive more general guidance.

**Comment by SteveSandersonMS** [comment]
Thanks very much @iphdav - that's very high-quality info and great advice.

**Comment by Alerinos** [comment]
@iphdav Thanks for the big answer. 
I know how the blazor circuit works.
I was more concerned with conveying states such as the current culture language which is in the cookie, whether the style is darktheme, etc.
Without defining e.g. culture language I have a jump effect. For example: I am Polish, in the Cookie I have the Polish language but the default is English, when I enter the page the server reads the cookie and displays the Polish language, then the client circuit does not have this information so it overwrites the data with English which is guessed. It does this because there is no user parameter passed as well as the state between the server and client circuit is different.

Therefore, you need to pass some of the state for the circuit.

**Comment by SteveSandersonMS** [comment]
Understood. `PersistentComponentState` is intended for this case.
