### ISSUE TITLE
OutputCacheMiddleware changes a response behavior of failed bindings issues

### ISSUE THREAD

**Issue by vchirikov** [dotnet/aspnetcore#51050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`OutputCacheMiddleware` changes response code to 200 and returns no content in case of `Microsoft.AspNetCore.Http.BadHttpRequestException` at least. I have a custom type which implements `ISpanParsable`, in case of binding failure (invalid input) minimal apis throws the `Microsoft.AspNetCore.Http.BadHttpRequestException` (it should use 4xx  but it's a separate issue - https://github.com/dotnet/aspnetcore/issues/3959) but I don't get the exception with `.UseOutputCache();`.  Check the repro:

![bug](https://github.com/dotnet/aspnetcore/assets/40987940/e8c59f7b-8db4-4c4e-a3c2-51bdfd5b5b8c)

### Expected Behavior

The behavior of an invalid input shouldn't be changed by `OutputCacheMiddleware` 

### .NET Version

8.0.100-rc.1.23463.5

**Comment by BrennanConroy** [comment]
Can you provider a minimal repro app. Also, does it reproduce if you fully restart the app (don't use hot reload).

**Comment by vchirikov** [comment]
Repro is here - https://github.com/vchirikov/repro_aspnetcore_51050 note that with default `builder.Services.AddOutputCache();` it works fine, but with `builder.Services.AddOutputCache(opt => opt.AddBasePolicy(b => b.Cache()));` it doesn't work well (returns 200 instead of 400)

**Comment by BrennanConroy** [comment]
Outputcaching now swallows the app exception which results in an empty 200.
https://github.com/dotnet/aspnetcore/blob/8ce579fd9a07bd595d635572005e71ebe8c4d7a2/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L199-L203
We should probably rethrow. @mgravell

**Comment by vchirikov** [comment]
Checked on 8.0 seems, like @mgravell (thanks) fixed this with https://github.com/dotnet/aspnetcore/pull/51067 , now the output is correct
