### ISSUE TITLE
Minimal API - IFormCollection, IFormFileCollection and IFormFile throw "Invalid anti-forgery token found when reading parameter..."

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#51052]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a minimal API endpoint, accessing either IFormCollection, IFormFileCollection and IFormFile throws "Invalid anti-forgery token found when reading parameter...".

``` csharp

        routeGroup.MapPost("/", async (IFormCollection form) =>
        {
            var formFiles = form.Files;
            return Results.Ok();
        });

```

Happens for IFormFileCollection and IFormFile as well.

#### Workaround:

``` csharp

        routeGroup.MapPost("/", async (HttpRequest request) =>
        {
            var formFiles = request.Form.Files;
            return Results.Ok();
        });

```

### Expected Behavior

Accessing IFormCollection, IFormFileCollection and IFormFile in a minimal API endpoint shouldn't throw.

### Steps To Reproduce

Try any of the below code snippets in a .NET 8 (rc1) minimal API

``` csharp

        routeGroup.MapPost("/", async (IFormCollection form) =>
        {
            var formFiles = form.Files;
            return Results.Ok();
        });

```

``` csharp

        routeGroup.MapPost("/", async (IFormFileCollection files) =>
        {
            var formFiles = files;
            return Results.Ok();
        });

```

``` csharp

        routeGroup.MapPost("/", async (IFormFile file) =>
        {
            var formFile = file;
            return Results.Ok();
        });

```

### Exceptions (if any)

```

Microsoft.AspNetCore.Http.BadHttpRequestException: Invalid anti-forgery token found when reading parameter "IFormCollection form" from the request body as form.
 ---> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.D1Rd6RA9i3g" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.InvalidAntiforgeryToken(HttpContext httpContext, String parameterTypeName, String parameterName, Exception exception, Boolean shouldThrow)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForForm>g__TryReadFormAsync|102_0(HttpContext httpContext, String parameterTypeName, String parameterName, Boolean throwOnBadRequest)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

### .NET Version

8.0.100-rc.1.23463.5

### Anything else?

There are other issues for this but most people look for the rabbit in the `.AddAntiForgery` rabbit hole.

**Comment by captainsafia** [comment]
@augustevn This is expected behavior in the latest RC1 as we've added support for anti-forgery validation in minimal APIs. It's generally recommended to [enable XSRF token checks](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0) when processing form data. If you'd really like to, you can disable this check by calling the `DisableAntiforgery` method on the endpoint. Check out the [new docs here](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0#antiforgery-with-minimal-apis) for more info.

**Comment by augustevn** [comment]
@captainsafia Okay, I don't really want to have to deal with this. I'm constructing the form data myself in the Blazor WASM project just to upload some files. Should I not use `MultipartFormDataContent`? JSON instead?

**Comment by captainsafia** [comment]
Does the following code not work for you?

```csharp
routeGroup.MapPost("/", async (IFormCollection form) =>
{
    var formFiles = form.Files;
    return Results.Ok();
})
.DisableAntiforgery();
```

**Comment by augustevn** [comment]
> Does the following code not work for you?
> 
> ```cs
> routeGroup.MapPost("/", async (IFormCollection form) =>
> {
>     var formFiles = form.Files;
>     return Results.Ok();
> })
> .DisableAntiforgery();
> ```

**Comment by augustevn** [comment]
@captainsafia Yes it works, thanks!
