### ISSUE TITLE
Changes to AddCascadingValue do not affect Blazor Server Mode

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#51054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have this code:
```cs
public interface ICookie
{
    public string? Get(string key);
    public void Set(string key, string value, int days = 12 * 30);
    public Task SetByJSAsync(string key, string value, int days = 12 * 30);
    public List<CookieModel> GetCookies();
    public void Inicjalize(List<CookieModel> cookies);
}
```
```cs
        services.AddCascadingValue(sp =>
        {
            var httpContextAccessor = sp.GetRequiredService<IHttpContextAccessor>();
            var cookie = sp.GetRequiredService<ICookie>();

            if (httpContextAccessor.HttpContext is not null)
                foreach (var c in httpContextAccessor.HttpContext.Request.Cookies)
                    cookie.Set(c.Key, c.Value);

            return cookie.GetCookies();
        });
```

This is how I displayed Cascade:

```razor

        @foreach(var cookie in Cookies)
        {
            <div>@cookie.Name @cookie.Value</div><br/>
        }

@code{
    [CascadingParameter]
    protected List<CookieModel> Cookies { get; set; } = new();
    }
```

At first glance everything works fine.
Over time the data didn't agree with me, I started debugging more in blazor.
If I set a breakpoint on the loop then the first rendering (server) works great, the next rendering (client) results in old data. The client did not get the new data in Blazor Web, if we navigate through the navigation, change sub-pages then there is an error. If we reload the window and reconnect socket data is updated. 

This doesn't help either:
```cs
return new CascadingValueSource<List<CookieModel>>(cookie.GetCookies(), isFixed: false); // or true
```

### Expected Behavior

When the CascadingValue data is changed then it should be sent to the client via socket.
The client only receives the new data when it reconnects. 

### .NET Version

.net 8 rc1

**Comment by iphdav** [comment]
@Alerinos It might help if you created a public github project we could look at to assist as it isn't clear what type of project you are using (WebAssembly, InteractiveServer, etc)?

If you are adding a CascadingValue on the server, that would not propagate to a web assembly client.

If you are doing everything on the server (InteractiveServer with a signalr connection), do understand that you need to manually notify the framework that the change has occurred when using a global CascadingValue.  

For example, you cannot globally cascade a List<string>, then add an item to the list expecting your component to be notified of the change.  It doesn't work that way.  There is an API you can call to notify of a change in globally registered cascading parameters.

**Comment by iphdav** [comment]
@Alerinos For guidance read the top of Steve Sanderson's comments here:
https://github.com/dotnet/aspnetcore/issues/49104

You will be wanting to create a  CascadingValueSource and then calling the NotifyChanged API.

**Comment by SteveSandersonMS** [comment]
All of @iphdav's comments above are correct.

Remember that SSR and InteractiveServer rendering are happening in different DI scopes. Anything you do in SSR scopes is completely independent of any InteractiveServer scopes. That's because they have different lifetimes and can even run on different servers.

If you could describe your goals a bit more we might be able to suggest a more complete strategy for it. For example, please clarify whether all of your pages are InteractiveServer, or just some of them. And are your cookie updates only happening during interactive rendering (via `SetByJSAsync`) or can they get mutated during SSR loads?
