### ISSUE TITLE
BlazorWeb, require button names to have a matching code-behind variable.

### ISSUE THREAD

**Issue by ssperoniGIT** [dotnet/aspnetcore#51081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I don't know if this is the appropriate place for this suggestion:
I'm using BlazorWeb (SSR) and VS 7.8.0 Preview 2.0.

A Submit button would look like this:
button name="btnName1" value="ok" type="submit">Submit Form 

The problem is: btnName1 does not need to exist in the code, it compiles fine without a variable named 'btnName1'.  So if btnName1 is misspelled in the code such as:
    [SupplyParameterFromForm] public string? btnName1XXX { get; set; } = "";

it would compile, but because of the misspelling, the button doesn't do anything.
I just started a large application using BlazorWeb (RC1) and this has already bit me several times.
What makes it worse, is after you get the code working, then right-click the variable name (btnName1XXX in above exp) and rename it, it doesn't rename the 'name=' in the button, so the button stops working but still compiles OK. It could be days before you realize you have a button that no longer works because you renamed it in the code.

This is a sub optimal coding experience.

### Describe the solution you'd like

My suggestion: The code should not compile if you have a button name that does not exist in code. And should automatically rename if the variable is renamed.

**Comment by javiercn** [comment]
@ssperoniGIT thanks for contacting us.

This is not a requirement that we plan to introduce, as it significantly an unnecessarily means the set of scenarios you can achieve with HTML.

If you want to make sure that you have consistent naming, there is already a compiler feature for it. You can use `@(nameof(field))` to set the button name

**Comment by ssperoniGIT** [comment]
Thank you.
The solution you suggested works perfect and solves the problem.
You just need to changed the html to:  <button name="@(nameof(btnSubmit))"
I'm closing this issue.
