### ISSUE TITLE
Session cookie ITicketStore & ISecureDataFormat

### ISSUE THREAD

**Issue by TheTrigger** [dotnet/aspnetcore#51092]
AFAIK there is no way to use `ITicketStore` and `ISecureDataFormat` with session cookie

example usage with identity cookie:
```diff
services.AddOptions<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme)
           .Configure<ITicketStore, MyCookieDataFormat>((options, store, dataFormat) =>
{
  options.TicketDataFormat = dataFormat;
  options.SessionStore = store;
  // ...
};
```

a similar API for the session cookie would be good

**Comment by Tratcher** [comment]
By session cookie you mean SessionOptions.Cookie?
https://github.com/dotnet/aspnetcore/blob/8ce579fd9a07bd595d635572005e71ebe8c4d7a2/src/Middleware/Session/src/SessionOptions.cs#L28

**Comment by TheTrigger** [comment]
Hello, no you can't do it with the CookieBuilder

It's more of a curiosity than a necessity, I tried to customize the cookie format but I found a barrier

curious that no one has ever customized cookies

**Comment by Tratcher** [comment]
The session cookie is much different, it only stores an identifier, not data, there's not much to customize.

**Comment by TheTrigger** [comment]
Yes but the identifier is generated from ITicketStore and secured by ISecureDataFormat,
the result is stored on the cookie.
There is no way to use my custom implementation of those two interfaces.

**Comment by Tratcher** [comment]
SessionOptions is for browser sessions, not user sessions, it's not associated with auth in any way.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
