### ISSUE TITLE
Consolidate Blazor Web App terminology: "Interactive render mode" vs "Interactivity type" vs "hosting model"

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51108]
In .NET 8 we introduced the concept of interactive render modes in the Blazor framework:
- Interactive Server
- Interactive WebAssembly
- Interactive Auto

In the Blazor Web App project template we refer to "Interactivity type" in the VS UI:

![blazor-web-app-interactivity-type](https://github.com/dotnet/aspnetcore/assets/1874516/bc1ae3bb-607e-4dd6-9c4c-69260a5f6c9e)

And in the command-line help for the Blazor Web App template we refer to "hosting platform":

```
 -int, --interactivity <None|Server|...>  Chooses which hosting platform to use for interactive components
                                           Type: choice
                                             None         No interactivity (static server rendering only)
                                             Server       Runs on the server
                                             WebAssembly  Runs in the browser using WebAssembly
                                             Auto         Uses Server while downloading WebAssembly assets, then uses WebAssembly
```

To consolidate the terminology, I recommend the following:
- Update "Interactivity type" to "Interactive render mode" in the VS UI
- Update the CLI help text to change "hosting platform" to "interactive render mode"

**Comment by marinasundstrom** [comment]
Great!

What people would perceive as the hosting platform for a Web App would probably be Server by default - as the main project is Server. So it's good to get rid of that other usage.

It's the render modes that are different, and the choice is whether the developer wants to include components that demonstrate those render modes, or not.
