### ISSUE TITLE
IIS hosting. AspNetCoreModuleV2. NullReferenceException when SignalR socket disconnected

### ISSUE THREAD

**Issue by Nslookup** [dotnet/aspnetcore#51105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have hosted .net 7 application with SignalR on IIS. 

I've used this handler configuration:
```
<handlers>
    <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
</handlers>
```
      
SignalR works fine, but when I stop the socket (page refresh) the iis pool  crashes with this unhandled exception:

Unexpected exception in IISHttpServer.OnAsyncCompletion.
```
Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOEngine.NotifyCompletion(Int32 hr, Int32 bytes)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.OnAsyncCompletion(IntPtr pvManagedHttpContext, Int32 hr, Int32 bytes)
```

### Exceptions (if any)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOEngine.NotifyCompletion(Int32 hr, Int32 bytes)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.OnAsyncCompletion(IntPtr pvManagedHttpContext, Int32 hr, Int32 bytes)

### .NET Version

7.0.100

**Comment by BrennanConroy** [comment]
How often does this happen?
Are you using in-process or out-of-process?
What is your app doing? Can you provide a small repro app?
If the app is crashing, can you get a dump of the process? e.g. using [WER](https://learn.microsoft.com/windows/win32/wer/collecting-user-mode-dumps)

**Comment by Nslookup** [comment]
1. It happens every time when client refresh a page with SignalR connection (on disconnect)
2. hostingModel="InProcess"
3. Is is apigateway with signalR. It works fine in docker/k8s or locally, but doesn't work in IIS.

**Comment by Nslookup** [comment]
This problem only exist if i publish .net 7 app into iis site with sharepoint as subapplication

**Comment by Nslookup** [comment]
It was configuration problem

**Comment by BrennanConroy** [comment]
Could you explain a little so any future people who have a similar problem can find this issue?
