### ISSUE TITLE
Failed integrity metadata check for Blazor application (NET7)

### ISSUE THREAD

**Issue by erossini** [dotnet/aspnetcore#51104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a project in NET7 and Blazor hosted in an ASP.NET Core web application. The website is hosted on a service provider. When I deploy the application on the server in a hosting provider, I check the application with different browsers.

The application is working for Microsoft Edge on Windows and Mac. On Safari I get a lot of errors related to the integrity check for all the `dll` in the project.

> Failed integrity metadata check. https://languageinuse.com/_framework/System.Security.Cryptography.Cng.dll. Failed integrity metadata check. Content length: 1233, Expected content length: 1233, Expected metadata:

[![enter image description here][1]][1]

I tried to clean the `bin` and `obj` folders before deploying it from my laptop to the server the application and cleaned the solution but with the same result.

Also, I tried to remove the

    app.UseBlazorFrameworkFiles();

but not luck. I read this could be before firewalls and antivirus could block the `.dll` files and in NET8 something will change for it. But for now, I still get the errors.

## Update

This error is present also in Chrome, so it is not only Safari. I checked the [Microsoft documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0&preserve-view=true) but there is not much that I can try. 

## Update/2

In incognito mode on Safari, I still have the issue with the integrity metadata check.

[![enter image description here][2]][2]

if I open the same website not in incognito, there is no issue with the integrity metadata check but all the resources in the components (_css_ and _js_) are not loaded with error 403.

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/8AIAE.jpg
  [2]: https://i.stack.imgur.com/bbCI6.jpg
  [3]: https://i.stack.imgur.com/n8kCc.jpg

### .NET Version

NET7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you try the suggestions documented here and see if that helps: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#resolve-integrity-check-failures
