### ISSUE TITLE
Blazor: Page scroll is incorrectly reset after a page refresh

### ISSUE THREAD

**Issue by lofcz** [dotnet/aspnetcore#51112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![2023-10-03 21-08-04](https://github.com/dotnet/aspnetcore/assets/10260230/bf757771-8b81-42ce-af60-26ea409a9c9e)

Notice that after the user agent refreshes the page, the scroll is reset. This is an extremely bad user experience in the case of reading a blog post for example, if the scroll is reset the user has to find the place where they left off manually. This is very likely to happen on Blazor Server for mobile users where they read an article, lock the phone for a while, the server evicts their circuit and finally, the scroll position is lost. However, a refresh can be triggered by any other reason such as an accidental gesture on mobile, etc. 

### Expected Behavior

The scroll should persist, this behavior is in line with users' expectations.
For example, navigate to StackOverflow / Google search results / YouTube, scroll then refresh. Almost every web application persists the scroll position after refresh. 

### Steps To Reproduce

A modified template where `Pages.Counter` was updated to make a scrolling page.
[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/12796174/BlazorApp1.zip)

1. open the project
2. navigate to /counter
3. scroll
4. refresh the page
5. observe the bug

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

Similar issues:
#19187

**Comment by lofcz** [comment]
MRP [BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/12796174/BlazorApp1.zip)

**Comment by lofcz** [comment]
@mkArtakMSFT the repro label is incorrect, I've provided the demo in the original issue.

**Comment by mkArtakMSFT** [comment]
@lofcz we can't use a `zip` file. Please share your repro as a public GitHub repository.

**Comment by lofcz** [comment]
@mkArtakMSFT 
https://github.com/lofcz/BlazorScrollBug

**Comment by surayya-MS** [comment]
The target framework is `.net 7` in the repro. This has been addressed in `.net 8`

**Comment by lofcz** [comment]
This was addressed only in SSR mode, regardless of .NET 7/8 the issue is unaddressed outside of that. Please reopen the issue.

**Comment by surayya-MS** [comment]
@lofcz  I just tried it out in Blazor Server `.net 8` and it works. If it was broken in rc2 it is now fixed.
