### ISSUE TITLE
.Net8 Identity with ef core

### ISSUE THREAD

**Issue by Kiryuumaru** [dotnet/aspnetcore#51129]
## Ask a question

I am using the latest preview of .Net8 identity with ef core `Microsoft.AspNetCore.Identity.EntityFrameworkCore`. How to add the identity db context if I am using a factory:

```csharp
  services.AddSingleton<ServerDbContextFactory, SqliteServerDbContextFactory>();
  services.AddIdentityApiEndpoints<IdentityUser>()
      .AddEntityFrameworkStores<SqliteServerDbContext>();
```
My factory impl:

```csharp
public class SqliteServerDbContextFactory
{
    public async ValueTask<ServerDbContext> CreateDbContextAsync()
    {
        SqliteServerDbContext dbContext = new();
        await dbContext.Database.EnsureCreatedAsync();
        return dbContext;
    }
}
```

**Comment by marinasundstrom** [comment]
@Kiryuumaru Is all that you do making sure that the database is created?

If so, I would perhaps place that logic in an extension method, and invoke it from ``Program.cs`` before starting the Web application. 

This is how I usually do initialization directly in ``Program.cs``:

```csharp
var builder = WebApplication.CreateBuilder(args);

// Omitted

var app = builder.Build();

// Omitted

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<MyContext>();

    //await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync(); 

    if (args.Contains("--seed"))
    {
        await Seed.SeedData(context);
        return;
    }
}

app.Run();
```

**Comment by Kiryuumaru** [comment]
I'm using a factory to create my database context instead of adding it directly to my service so that I can avoid potential memory accumulation issues. I had a problem where my app was using up a lot of memory and nearly maxing out my RAM after running for a week

**Comment by marinasundstrom** [comment]
@Kiryuumaru I don't see what you get from having your own factory.

In default ASP.NET Core app, the ``DbContext`` instance is scoped, and will persist within a request.

Am I missing something?

You are able to implement ``IDbContextFactory``, or use the ``AddDbContextFactory`` method.

More on DbContext initialization: https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/

**Comment by Kiryuumaru** [comment]
Hi, thank you for this suggestion. i will try the builtin `IDbContextFactory` if i can run it without mem leak

**Comment by codelovercc** [comment]
Does this document help? https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant#managing-state-in-pooled-contexts

Use context pooling and a scoped `IDbContextFactory<TContext>`
```C#
public class WeatherForecastScopedFactory : IDbContextFactory<WeatherForecastContext>
{
    private const int DefaultTenantId = -1;

    private readonly IDbContextFactory<WeatherForecastContext> _pooledFactory;
    private readonly int _tenantId;

    public WeatherForecastScopedFactory(
        IDbContextFactory<WeatherForecastContext> pooledFactory,
        ITenant tenant)
    {
        _pooledFactory = pooledFactory;
        _tenantId = tenant?.TenantId ?? DefaultTenantId;
    }

    public WeatherForecastContext CreateDbContext()
    {
        var context = _pooledFactory.CreateDbContext();
        context.TenantId = _tenantId;
        return context;
    }
}
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
