### ISSUE TITLE
Confirmation email sent after registering user via Identity API has link with relative path, should be only code

### ISSUE THREAD

**Issue by bluedot2** [dotnet/aspnetcore#51146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling the register or resendConfirmationEmail endpoints of the Identity API, the confirmation email sent to the user contains a link with a relative path, so it doesn't work.

However, I think the email should include only a code, similar to what the forgotPassword email supplies, since the point of the API is to handle the UI yourself. I believe this approach would also be a little more secure, as we wouldn't be exposing the user's ID (the ID and the code are currently parameters in the link URL).

As a side note, the codes are currently very long; typically such codes are much shorter (say, a 6-digit number); I worry that users will have trouble cutting and pasting such long codes correctly.

### Steps To Reproduce

You can start with David Fowler's [IdentityEndpointsSample](https://github.com/davidfowl/IdentityEndpointsSample), configure an email provider as explained [here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-7.0&tabs=visual-studio), then call the register endpoint to receive the email.

### .NET Version

8.0.100-rc.1.23455.8

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue.
We've already fixed this as part of https://github.com/dotnet/aspnetcore/pull/50297
