### ISSUE TITLE
Configure Azure Pipelines to run SignalR daily tests on PRs that opt in

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#5114]
See #5056 for context

**Comment by muratg** [comment]
@bradygaster has some ideas around using Logic Apps to accomplish this.

**Comment by davidfowl** [comment]
@BrennanConroy @halter73 this still important?

**Comment by BrennanConroy** [comment]
I don't think so. We don't touch the ts client very often, and we run the tests daily, so any breaks will go unnoticed for a day at most.
