### ISSUE TITLE
Swap the order of the http/https launch profiles?

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#51159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In `launchSettings.json` (since 7.0), the `http` profile is ordered before the `https` profile ...

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Properties/launchSettings.json#L16-L43

When running with the CLI without naming the `https` profile, the default is to use the first profile, so the `http` profile is used.

### Describe the solution you'd like

Should the order of the `http` and `https` profiles be swapped so that the `https` profile is the default for CLI runs?

### Additional context

That's the Blazor template, but it's also the same in the other project templates. The recommendation would be for all templates.

**Comment by javiercn** [comment]
@guardrex the order is by design, it is intended to ease the "https" pain for newcomers to the platform on Linux and Mac.

**Comment by marinasundstrom** [comment]
Normally when you launch an app in the HTTP configuration, you get redirected using HTTPS anyway (Middleware: ``UseHttpsRedirection``)

**Comment by guardrex** [comment]
I'm specifically referring to running with `dotnet run`, which was forcing me to pass `-lp https` or reversing the order in the file. I've added a remark on this to the *Project Structure* article where it speaks to the `launchSettings.json` file. Dan will review the PR. If he's cool with the remark, we'll keep it. He might decide to 🔪 it tho on the grounds that it's too *weedy* to worry about.
