### ISSUE TITLE
DataProtection - PersistKeysToFileSystem is not working properly inside K3S with shared file system

### ISSUE THREAD

**Issue by apetrut** [dotnet/aspnetcore#51165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using 2 pods inside a K3S cluster and when the first pod is started the key-GUID.xml file is generated and stored in a shared drive location.
When the second service gets started it sees the first key file (because it points to the same file storage location) and doesn't create a new one. I checked the logs and no error was logged.

After some while (i.e. 10-15 minutes) of playing with the apps, errors like below started to appear:

> An exception was thrown while deserializing the token.
> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
> ---> System.Security.Cryptography.CryptographicException: The key {669d513e-a172-4851-b160-04b523abbc1e} was not found in the key ring.

Why does this error occur after some while?

### Expected Behavior

I would expect that no errors were thrown.

### Exceptions (if any)

An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
---> System.Security.Cryptography.CryptographicException: The key {669d513e-a172-4851-b160-04b523abbc1e} was not found in the key ring.

### .NET Version

.NET 7

**Comment by amcasey** [comment]
I'm going to close this issue.  Please post additional feedback in #36157 so we can track it centrally and don't drop any.
