### ISSUE TITLE
Blazor Web App: AuthorizeRouteView NotAuthorized

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#51164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a "Blazor Web App" using Visual Studio 2022 17.8 Preview. 

I have added `Microsoft.AspNetCore.Identity` authentication to the generated application. I've changed the default `Routes.blazor` to include `CascadingAuthenticationState` and `AuthorizeRouteView` that references a component forcing a redirect to a login page if the user is not authorized. Apparently this is not necessary because the application does just that without my `RedirectToLogin` component ever getting loaded. But I would like to know how it actually works and why my `AuthorizeRouteView` is doing nothing at all?

Routes.razor:
```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)">
               <NotAuthorized>
                    <RedirectToLogin></RedirectToLogin>
                </NotAuthorized>
            </AuthorizeRouteView>
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
    </Router>
</CascadingAuthenticationState>
```

_Imports.razor:
```
@using System.Net.Http
@using System.Net.Http.Json
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop
@using WebApp
@using WebApp.Components
@attribute [Authorize]
```

### .NET Version

8.0.100-rc.1.23455.8

**Comment by javiercn** [comment]
@oliverw thanks for contacting us.

When the app is using SSR, the authorization step happens automagically via the Challenge that the ASP.NET Core authorization system has in place based on metadata from the page component that was matched via routing.

The redirect component is only necessary for scenarios where a component is interactive and requires a different authorization than the one on the server.

**Comment by oliverw** [comment]
Interesting. Thanks for the clarification.

**Comment by oliverw** [comment]
> @oliverw thanks for contacting us.
> 
> When the app is using SSR, the authorization step happens automagically via the Challenge that the ASP.NET Core authorization system has in place based on metadata from the page component that was matched via routing.
> 
> The redirect component is only necessary for scenarios where a component is interactive and requires a different authorization than the one on the server.

So, can I get rid of the NotAuthorized part if I have `@attribute [Authorize]` in _Imports.razor or do I need to keep it?
