### ISSUE TITLE
NotFound does not work for Blazor Web App

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#51163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a "Blazor Web App" using Visual Studio 2022 17.8 Preview.

I have modified `NavMenu.razor` to have broken link to `Counter.razor` by preprending an underscore to the location:

```
<NavLink class="nav-link" href="_counter">
    <span class="bi bi-plus-square-fill" aria-hidden="true"></span> Counter
</NavLink>
```

Modified `Routes.razor` to include a case for `NotFound`:

```
<Router AppAssembly="@typeof(App).Assembly" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(Layout.MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

Running the application and clicking the "Counter" Link results in standard 404 page rather than the configured LayoutView.

### Expected Behavior

Running the application and clicking the "Counter" Link displays configured LayoutView for the NotFound case.

### Steps To Reproduce

Run the attached project.

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

[BlazorWebApp.zip](https://github.com/dotnet/aspnetcore/files/12818316/BlazorWebApp.zip)

**Comment by jonhilt** [comment]
One workaround (which works in the latest nightly release, but not sure about RC1) is to use `app.UseStatusCodePagesWithRedirects("/StatusCode/{0}");` 

You can create a Blazor component at `StatusCode` (in this example) to handle error codes:

Here's an example: https://jonhilton.net/blazor-net8-migration/#notfound-is-no-longer-relevant

**Comment by mkArtakMSFT** [comment]
Thanks @jonhilt for helping here. This is indeed a dupe.
