### ISSUE TITLE
Blazor Web App and Microsoft.AspNetCore.Identity.UI

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#51161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a "Blazor Web App" using Visual Studio 2022 17.8 Preview. 

I have added Microsoft.AspNetCore.Identity authentication to the generated application. The problem is, as soon as the user navigates to a Blazor Page that requires authentication, the standard Identity UI is loaded which is fine. What is not fine is that the forms and buttons of the UI all get intercepted by the code in `_framework/blazor.web.js` which gets included by `App.razor` after `Routes.blazor`:

![image](https://github.com/dotnet/aspnetcore/assets/51688/e48661dd-60c1-473b-80a6-779ab36a163d)

This causes the form to be submitted via XHR, breaking it. A workaround is to remove  the script reference to `_framework/blazor.web.js` from `App.razor` and included it at the end of `Counter.razor`.

Program.cs:

```
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>();
...
builder.Services.AddRazorPages();
```

__Imports.razor:

```
@using System.Net.Http
@using System.Net.Http.Json
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop
@using WebApp
@using WebApp.Components
@attribute [Authorize]
```

### Expected Behavior

Microsoft.AspNetCore.Identity.UI should work as expected but it doesn't.

### .NET Version

8.0.100-rc.1.23455.8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in the upcoming RC2 release. Also, in RC2 we're providing a set of Blazor components specifically designed for Identity scenarios and are used for handling authentication scenarios.
