### ISSUE TITLE
Applying migrations using db error page fails for Blazor Web App with Identity

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51178]
Repro steps:
- Install .NET 8 RC2
- Create a new Blazor Web App, Individual user accounts, server interactivity mode enabled locally
- Run the app
- Register a new user
- Try to apply migrations using the db error page

Expected result: Applying migrations succeeds
Actual result:
- "An error occurred applying migrations, try applying them from the command line"
- 404 error response in the browser dev console for /ApplyDatabaseMigrations
Workaround: Run migrations from the command line.

**Comment by jinzhao1127** [comment]
Verify this issue has fixed on the latest .NET 8.0-rtm
