### ISSUE TITLE
dotnet watch run with args break hot reload

### ISSUE THREAD

**Issue by inlineHamed** [dotnet/aspnetcore#51171]
### Describe the bug
If you want to run dotnet watch with some dotnet run args like --urls, the hotreload feature breaks and will rebuild the project with each edit.

### To Reproduce
1) `dotnet new console`
2) write this in Program.cs
```
int counter = 0;
while(true)
{
    Console.WriteLine($"Hello {GetName()} {counter++}");
    Thread.Sleep(1000);
}
string GetName() => "hamed!"; 

```
4) run the app with `dotnet watch`
5) change GetName() body and see hot reload working
6) now stop the app and run it again with `dotnet watch run --no-restore` , this time hot reload breaks

We may close this issue if:
hotreload work with run args

### Further technical details
- Include the output of `dotnet --info`
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

- running `dotnet watch -v run --no-restore` show `dotnet watch ⌚ Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.`

**Comment by mkArtakMSFT** [comment]
Thanks for confirming this, @garrettlondon1! Closing as @tmat confirmed that this has been fixed.
