### ISSUE TITLE
Blazor g11n/i18n support

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#51181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I just tried out Blazor in .net 8, and I can see it is still mostly developed by people that live in USA and never has to make multi language apps👎 

1. `dotnet new blazor` => default template hard codes `<html lang=en>`👎 
2. `dotnet new blazor --use-server true --use-wasm true` => Add code Server side to fetch lang from db and set it => wasm reverts to browser language👎 
3. Set `CultureInfo.DefaultThreadCurrentCulture = new("da-DK")` => 
a. `<html lang=en>` still remains👎 
b. `<meta http-equiv="content-language" content="">` not added
c.  `<div id=app>` lang attribute not added
So how is browser/search engine going to figure out I show a different language than en?👎 
4. Want dataannotations translations? Install nuget package with language support for my new language? Ofcourse not 👎 

### Expected Behavior

Out of the box support for the most trivial app that supports a handful of cultures and supports loading that value from somewhere.

IMHO, the default template should support multiple languages and all the default texts using resx files instead of hard coded values.

### Steps To Reproduce

see above

### .NET Version

8.0-rc.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The main thing from this list that we plan to do is already tracked as part of https://github.com/dotnet/aspnetcore/issues/26941. As for the rest, these are not things that we plan to do in the near future.
