### ISSUE TITLE
[NETSDKE2E] Alpine Only, with .NET 8.0 RTM warning: Failed to read or parse localization file when creating new project for the first time.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/aspnetcore#51198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Reproduction Steps**
1. On Linux Apine 3.18 in docker, install 8.0.100-rtm.23506.1
2. In CLI, run "dotnet new webapp"
3. Project can be created successfully, but below warning displays. 
[Output.txt](https://github.com/dotnet/aspnetcore/files/12837269/Output.txt)

```
Warning: Locale 'pt-BR' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.pt-BR.json), it will be skipped from further processing.
Warning: Locale 'ru' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.ru.json), it will be skipped from further processing.
Warning: Locale 'tr' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.tr.json), it will be skipped from further processing.
Warning: Locale 'zh-Hans' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.zh-Hans.json), it will be skipped from further processing.
Warning: Locale 'zh-Hant' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.zh-Hant.json), it will be skipped from further processing.
Warning: Locale 'cs' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.cs.json), it will be skipped from further processing.
Warning: Locale 'de' does not match any known cultures.
Warning: Failed to read or parse localization file /root/mytest/templates/8.0.0-rtm.23502.22/microsoft.dotnet.web.itemtemplates.8.0.8.0.0-rtm.23502.22.nupkg(/content/ApiController/.template.config/localize/templatestrings.de.json), it will be skipped from further processing.
...
Processing post-creation actions...
Restoring /root/myweb/myweb.csproj:
  Determining projects to restore...
  Restored /root/myweb/myweb.csproj (in 351 ms).
Restore succeeded.

```

**Dotnet --info**
.NET SDK:
 Version:           8.0.100-rtm.23506.1
 Commit:            0ffc9fdc93
 Workload version:  8.0.100-manifests.eeb18dd1

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.18
 OS Platform: Linux
 RID:         linux-musl-x64
 Base Path:   /root/mytest/sdk/8.0.100-rtm.23506.1/

.NET workloads installed:
 Workload version: 8.0.100-manifests.eeb18dd1
There are no installed workloads to display.

Host:
  Version:      8.0.0-rtm.23504.8
  Architecture: x64
  Commit:       22b8a5665f

.NET SDKs installed:
  8.0.100-rtm.23506.1 [/root/mytest/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rtm.23502.22 [/root/mytest/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rtm.23504.8 [/root/mytest/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Note:**
1. This issue is only repro on **Alpine Linux** and creating a project for **the first time.**
2. Similar issue was reported on .NET 8.0 RC2 -[https://github.com/dotnet/aspnetcore/issues/51003], and closed as fixed.

### Expected Behavior

Project should be created successfully

**Comment by mkArtakMSFT** [comment]
@wtgodbe I think some of the localization strings have been merged just recently. Can you check and see if there was a problem with these mentioned in the warnings above ?

**Comment by wtgodbe** [comment]
Looks like https://github.com/dotnet/sdk/issues/35768, which they claim has been fixed. I reopened that issue

**Comment by MiYanni** [comment]
@wtgodbe 

I ended up closing the other issue as that had a specific catalyst and symptoms. The previous issue only related to project templates. Looking at the output provided here, this one is for both project and item templates, and both web and common. This one seems to be culture related, so I'm gonna check with my team.

**Comment by wtgodbe** [comment]
Thanks @MiYanni - please let me know if there's anything we need to change in this repo

**Comment by MiYanni** [comment]
@NicoleWang001 
@wtgodbe 

Figured it out. Looking at the code [from here](https://github.com/dotnet/templating/blob/7f810f92886dbbd017e9e0fdda9599ee5de8a646/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/DirectoryBasedTemplate.cs#L141-L152) where the error occurs, you'll see:
```C#
CultureInfo.GetCultures(CultureTypes.AllCultures).FirstOrDefault(c => c.Name.Equals(localeStr, StringComparison.OrdinalIgnoreCase));
```

This is what is causing the issue. Now, since we see the locales in the warning output, that means `localeStr` is a valid value. Next, I took a look at the output text provided and filtered it down to only the unique warnings:
```
Warning: Locale 'cs' does not match any known cultures.
Warning: Locale 'de' does not match any known cultures.
Warning: Locale 'es' does not match any known cultures.
Warning: Locale 'fr' does not match any known cultures.
Warning: Locale 'it' does not match any known cultures.
Warning: Locale 'ja' does not match any known cultures.
Warning: Locale 'ko' does not match any known cultures.
Warning: Locale 'pl' does not match any known cultures.
Warning: Locale 'pt-BR' does not match any known cultures.
Warning: Locale 'ru' does not match any known cultures.
Warning: Locale 'tr' does not match any known cultures.
Warning: Locale 'zh-Hans' does not match any known cultures.
Warning: Locale 'zh-Hant' does not match any known cultures.
```

This is 13 out of the 14 locales. The missing locale is `en`. This means that the code only worked for `en` in this scenario.

Then, I had a hunch that either `CultureInfo.GetCultures` or `CultureTypes.AllCultures` was different on Linux. On Windows, `CultureInfo.GetCultures(CultureTypes.AllCultures)` returns 869 cultures. I looked at the definition for `CultureTypes.AllCultures` and saw:

```C#
// Summary:
//     All cultures that recognized by .NET, including neutral and specific cultures
//     and custom cultures created by the user. On .NET Framework 4 and later versions
//     and .NET Core running on Windows, it includes the culture data available from
//     the Windows operating system. On .NET Core running on Linux and macOS, it includes
//     culture data defined in the ICU libraries. System.Globalization.CultureTypes.AllCultures
//     is a composite field that includes the System.Globalization.CultureTypes.NeutralCultures,
//     System.Globalization.CultureTypes.SpecificCultures, and System.Globalization.CultureTypes.InstalledWin32Cultures
//     values.
AllCultures = 7,
```

You'll see it says:

> On .NET Core running on Linux and macOS, it includes culture data defined in the ICU libraries.

Therefore, the ICU libraries on Alpine Linux were only providing `en`. I did some internet searching, and found this issue: https://github.com/dotnet/dotnet-docker/issues/3844

There is a fix pointed out in that issue. Can you run this and try this scenario again?

```
RUN apk add icu-dev icu-libs icu-data-full
```

**Comment by wtgodbe** [comment]
@NicoleWang001 could you try the workaround Michael suggested above?

**Comment by richaverma1** [comment]
@NicoleWang001 can you try out the workaround and let us know?

**Comment by NicoleWang001** [comment]
After running apk add icu-dev icu-libs icu-data-full , this issue is not repro.
![image](https://github.com/dotnet/aspnetcore/assets/1578239/18b731b9-67b1-41ce-9689-d4f111a1b66d)

**Comment by MiYanni** [comment]
Since this is an issue specific to Alpine and the ICU they use, I'll close this. Happy I could help you figure out the problem. 🙂
