### ISSUE TITLE
DisableAntiforgery has no effect when applied on RouteGroupBuilder

### ISSUE THREAD

**Issue by cakescience** [dotnet/aspnetcore#51194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`RoutingEndpointConventionBuilderExtensions.DisableAntiforgery` has no effect when applied on `RouteGroupBuilder`

### Expected Behavior

The antiforgery validation is disabled for all endpoints in the group.

### Steps To Reproduce

```cs
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

var group = app.MapGroup("/").DisableAntiforgery();
group.MapPost("/hello", ([FromForm] string name) =>
{
    return TypedResults.Ok(name);
});

app.Run();
```

The following exception is thrown if the endpoint is called:

```
System.InvalidOperationException: Endpoint HTTP: POST /hello contains anti-forgery metadata, but a middleware was not found that supports anti-forgery.
Configure your application startup by adding app.UseAntiforgery() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAntiforgery() must go between them. Calls to app.UseAntiforgery() must be placed after calls to app.UseAuthentication() and app.UseAuthorization().
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAntiforgeryMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
```

When `DisableAntiforgery` is applied directly to the endpoint, it works correctly.

### .NET Version

8.0.100-rc.1.23463.5

**Comment by captainsafia** [comment]
@cakescience Thanks for reporting this issue!

We check the metadata on the endpoint using the `GetMetadata` call which typically returns the metadata by order for a given endpoint. The ordering typically flows from least-specific (group-level) to (most-specific (endpoint-level).

I believe we'll have to take advantage of the `Finally` clause here to make sure that the group-level metadata ends up getting applied last (and has a higher specificity than endpoint-level metadata).

I'll debug and see if that is the case...
