### ISSUE TITLE
Unable to configure Data Protection via IOptionsMonitor<DataProtectionOptions>

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/aspnetcore#51190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to configure the data protection discriminator on a per-tenant basis by maintaining a cache per-host.

Unfortunately, I cannot get the data protection configuration separated per-request through the use of an `IOptionsMonitor` however.

```csharp
        services
            .AddSingleton<IOptionsMonitor<DataProtectionOptions>, DataProtectionTenantedOptionsMonitor>()
            .AddSingleton<IConfigureOptions<DataProtectionOptions>, DataProtectionTenantedOptionsInitializer>()
            .AddSingleton<IConfigureOptions<DataProtectionOptions>, DataProtectionTenantedOptionsInitializer>()
        ;
```

```csharp
public class DataProtectionTenantedOptionsMonitor : IOptionsMonitor<DataProtectionOptions>
{
    private readonly IHttpContextAccessor httpContextAccessor;

    private readonly IOptions<CommonConfiguration> commonConfiguration;

    private readonly IOptionsFactory<DataProtectionOptions> factory;

    private readonly ConcurrentDictionary<(string Name, string Host), Lazy<DataProtectionOptions>> cache = new();

    public DataProtectionTenantedOptionsMonitor(
        IHttpContextAccessor httpContextAccessor,
        IOptions<CommonConfiguration> commonConfiguration,
        IOptionsFactory<DataProtectionOptions> factory
    )
    {
        this.httpContextAccessor = httpContextAccessor;
        this.commonConfiguration = commonConfiguration;
        this.factory = factory;
    }

    private string CurrentHost => httpContextAccessor.HttpContext?.Request.Host.Host ?? commonConfiguration.Value.AdminDomain;

    public DataProtectionOptions CurrentValue => Get(Microsoft.Extensions.Options.Options.DefaultName);
    
    public DataProtectionOptions Get(string? name)
    {
        if (name == null)
            throw new ArgumentNullException(nameof(name));

        Lazy<DataProtectionOptions> Create() => new(() => factory.Create(name));

        return cache.GetOrAdd((name, CurrentHost), (_) => Create()).Value;
    }

    public IDisposable OnChange(Action<DataProtectionOptions, string> listener) => throw new NotImplementedException();
}
```

### Expected Behavior

My expectation is that the `Get` method of my monitor would be called on every request and given the opportunity to return a cached instance.

### Steps To Reproduce

See my code shared above, it's everything necessary to see what lifecycle I'm trying to tap into.  It probably won't take a lot of intuition to see if either data protection isn't obtaining its configs correctly, or if I did something wrong....

### .NET Version

7.x

**Comment by amcasey** [comment]
Sorry, I'm not sure I understand your scenario.  I think your server might be receiving requests directed to multiple distinct hosts and you'd like each of these hosts to have its own data protection scope so that no host can unprotect data protected by a different host.  Is that correct?
