### ISSUE TITLE
.NET 7 Cookie  Bad Request not Encoding Value

### ISSUE THREAD

**Issue by MychellSantos** [dotnet/aspnetcore#51192]
### Description
Hello, I am getting issues related to encoding cookie value in .net applications,

When passing values ​​with special characters, even without using a cookie, I am receiving a 400 error.

I tried to customize a modelbinder to get the value and iginoara but it's not enough;

![image](https://github.com/dotnet/core/assets/77808184/415ee41e-843b-406e-a7fa-aca44f702671)

cookie value:
`VALUE={"latency":"Aboço"}`

Apparently the request does not reach any middle or pipeline or filter that can be customized
If my application does not use cookies, how can I skip this validation?
I was unsuccessful implementing a Binder
`x.ModelBinderProviders.Insert(0, new CustomBinder());`

.NET Version
7.0.11

### Configuration
New aplication (WeatherForecast Exemple)
With Controlles 
Run in Windows

**Comment by MychellSantos** [comment]
👀

**Comment by BrennanConroy** [comment]
You likely need to enable Latin1 encoding in the server. Example code:
```csharp
webBuilder.ConfigureKestrel(options =>
{
    options.RequestHeaderEncodingSelector = encoding =>
    {
        return encoding switch
        {
            "Cookie" => System.Text.Encoding.Latin1,
            _ => System.Text.Encoding.UTF8,
        };
    };
});
```

**Comment by MychellSantos** [comment]
@BrennanConroy 

Is it possible to have this validation even if my application does not use cookies?
Is there any way to disable this validation?

I received this case, because my application does not use cookies but safare sends cookies making my application return 400

**Comment by BrennanConroy** [comment]
> Is it possible to have this validation even if my application does not use cookies?

Just return `System.Text.Encoding.Latin1`?

> Is there any way to disable this validation?

Adding your own encoder is how you change the validation.
