### ISSUE TITLE
Hot Reload Support For Blazor

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#51211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I Mean In My Previous Issue
When Editing C# Code It Require To Restart Application

Why I Have To Restart Application
I Have Many Components, Classes And Assemblies

I Restart Application And It Takes

9 to 20 seconds

and there big issue

### Describe the solution you'd like

Why There Not Hot Reload For Blazor Cause It's Being Be Popular And There Many Frameworks Like

Abp
Oqtane
Masa

And Many Boilerplates

Whats Not In Blazor Is Hot Reload

**Comment by wisamidris7** [comment]
There Hot Reload But Rude Edit Is Always 99% Shows Up

**Comment by LuohuaRain** [comment]
Sure, but you can try `dotnet watch`. I am wondering why `dotnet watch` is superfast?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please clarify what specifically doesn't work for you? We're actively addressing issues in Hot Reload area and we're trying to understand what exactly is happening in your case.
To help with this, could you please provide a minimal repro project please? Thanks!

**Comment by Markz878** [comment]
I can provide the steps for a repro:
1. Create new Blazor Web App using Visual Studio, with the WASM and component scoped interactivity
2. Start the app from Visual Studio using F5 or Ctrl+F5.
3. Navigate to Counter component.
4. Try to remove the button classes.
5. You get an error from Visual Studio saying that hot reload failed.
6. Logs say there seems to be an issue with the hot reload websocket connection, and browser network tab shows that it stays in Pending state.

This is quite strange because creating the app with command line and using VS Code with dotnet watch command doesn't have this problem.

**Comment by wisamidris7** [comment]
No He Saying You Have To Rebuild The Program

But When Editing Code Like This It Work

```razor
<button class="hello">hells</button>
to this
<button class="hello">hello</button>
```
hot reload working perfect but in

```razor
@code
{
}
to this
@code
{
public void helloClicked()
{
Snackbar.Show("Hello World");
}
}
```

this is not working

**Comment by garrettlondon1** [comment]
I think the confusing part is if you just run `dotnet watch ` from the cli, hot reloads perfectly. For some reason, when you attach the debugger, unless you catch Visual Studio at the right time, **everything is a rude edit**

**Comment by MackinnonBuck** [comment]
@tmat it looks like the edit here is adding a method to a Blazor component, which I don't believe should be considered a rude edit. Could you please look into this?

**Comment by oiBio** [comment]
we do have the same problem with our code base.
I filed an issue here: https://developercommunity.visualstudio.com/t/Hot-Reload-on-Blazor-takes-several-minut/10484711 
it includes a minified repo.

one criteria for slow hot reload is the number of components. And it does not matter if its inside your main project or a componant library.

**Comment by tmat** [comment]
@Markz878 @wisamidris7 

I have tried the steps your provided but it worked for me. Do you have the latest VS version? If so and it's still a problem, please file a VS feedback as instructed here: https://developercommunity.visualstudio.com/VisualStudio/report

Collect and share detailed logs in the feedback like so:

1) Run the following commands from Developer Command Prompt for Visual Studio:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Preview> set Microsoft_CodeAnalysis_EditAndContinue_LogDir=%temp%\HotReloadLog
C:\Program Files\Microsoft Visual Studio\2022\Preview> devenv
```

2) Reproduce the issue in Visual Studio
3) Zip the directory `%temp%\HotReloadLog` and upload it to this ticket on VS Feedback.

**Comment by tmat** [comment]
@oiBio Thanks for filing a VS ticket. The performance issue with Razor Hot Reload is known and we are actively working on addressing it.
