### ISSUE TITLE
NavigationManager.Uri does not update for interactive components on non-interactive routers

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#51216]
Repro:

* Create a Blazor Web project with the default options (interactivity=server, type=per-page)
* In `Counter.razor`, add `@inject NavigationManager Nav` and in the UI display `@Nav.Uri`
* In `Home.razor`, add `@attribute [RenderModeInteractiveServer]`
* Launch the app so you're first on the home screen, then navigate to counter

Expected: Displays the URL `https://.../counter`

Actual: Displays the URL `https://.../`

If you do an F5 refresh there, it will display the correct URL. But if you then navigate to other interactive pages, they still think the URL is `/counter`.

### Also affects [SupplyParameterFromQuery]

Similarly if you add code like this to `Counter.razor`:

```razor
[SupplyParameterFromQuery] public int? IncrementAmount { get; set; }

private void IncrementCount()
{
    currentCount += IncrementAmount.GetValueOrDefault(1);
}
```

... and change `NavMenu.razor` to contain `<NavLink class="nav-link" href="counter?incrementamount=10">`, then you'll find that:

 * If you start on the home screen and navigate to counter, it only increments in 1s when it should be 10s
 * If you do an F5 refresh while at `/counter?incrementamount=10`, it will then increment in 10s

This also means that if `Counter.razor` contained links to itself but with different `incrementamount` query values (e.g., to let the user change to their preferred amount), the links simply won't have any effect.

I discovered this while trying to implement paging for a grid that should support both static SSR and interactive modes.

**Comment by oliverw** [comment]
I don't think this is fixed in RC2. I can still repro that.

**Comment by SteveSandersonMS** [comment]
@oliverw It was fixed in the final RTM builds, after RC2.
