### ISSUE TITLE
Failed to log out user with error "Uncaught TypeError: Cannot read properties of null (reading 'classList')" after publishing Blazor Web Individual App 

### ISSUE THREAD

**Issue by jinzhao1127** [dotnet/aspnetcore#51215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After publishing the Blazor web individual App, failed to log out the user.

**Note:**
1. This issue also reproduce on 8.0 Blazor Web wasm Individual app. 
1. This issue also reproduce on publish to folder and publish to Azure in VS

### Expected Behavior

The user should be log out successfully.

### Steps To Reproduce

1. File > New Project > Blazor Web App > .NET 8.0 > Choose Individual and Server type> Create
2. Do the workaround `update-database` when you met (https://github.com/dotnet/aspnetcore/issues/51178) issue
3. Publish the project with `dotnet publish`
4. Go to the Publish folder and run `dotnet BlazorApp1.dll`
5. Navigate to the URL on the browser
6. Register a new user and log in
7. Log out

### Exceptions (if any)

Get an error "This page isn't working right now."
On Edge:
![image](https://github.com/dotnet/aspnetcore/assets/55483444/424a5f65-f0cb-48ff-b207-63ab230a0f28)

On Chrome
![image](https://github.com/dotnet/aspnetcore/assets/55483444/8494b5bf-3d8e-412d-9481-fb4e172e40e6)

**Error log:**
```cshtml
Failed to load resource: the server responded with a status of 400 () 

VM9:5  crbug/1173575, non-JS module files deprecated. 

(anonymous) @ VM9:5 

VM6:19  Uncaught TypeError: Cannot read properties of null (reading 'classList') 

    at onResize (VM6:19:38) 

    at HTMLDocument.setupMobileNav (VM6:46:3) 

onResize @ VM6:19 

setupMobileNav @ VM6:46 

VM7:339  Uncaught TypeError: Cannot read properties of null (reading 'classList') 

    at HTMLDocument.onDocumentLoad (VM7:339:19) 

onDocumentLoad @ VM7:339 

25VM6:19  Uncaught TypeError: Cannot read properties of null (reading 'classList') 

    at onResize (VM6:19:38) 

onResize @ VM6:19 
```

### Anything else?

The details build version and other info, please refer to AzDO: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1898346

**Comment by mkArtakMSFT** [comment]
This should be already fixed.

**Comment by jinzhao1127** [comment]
Verify this issue was fixe on the latest 8.0-rtm.
