### ISSUE TITLE
Upgrade Microsoft.Extensions.Http.Polly to support new Polly.Core

### ISSUE THREAD

**Issue by pampua84** [dotnet/aspnetcore#51228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Since the new version of Polly.Core has been released in which the Policy object has been replaced with the new PredicateBuilder object, it would be useful to also have a new version of the library with the new FluentApi to be able to integrate Polly on the HttpClientFactory.

### Describe the solution you'd like

The user should be able to use the AddPolicyHandler method, perhaps renamed to AddPipelineHandler or   to use the new version of Polly.Core as was previously done in the PollyHttpClientBuilderExtensions class

**Comment by martincostello** [comment]
Hey there - as far as I'm aware there are no plans to update the ASP.NET Core wrappers around Polly to support the new v8 API model. This was something that was discussed during the development of Polly b8 itself.

As well as it being a breaking change and too late in the .NET 8 release cycle to do (it would have to wait for .NET 9), the libraries are being superseded as part of the .NET 8 release by the new resilience libraries published from the [dotnet/extensions](https://github.com/dotnet/extensions) repository.

See also https://github.com/App-vNext/Polly/discussions/1657.

**Comment by pampua84** [comment]
Ok, thanks so much for the reply. Sorry if I opened an already existing thread, but it didn't appear in my search.
