### ISSUE TITLE
Change onclick action in navigation for default template

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#51230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, the default blazor template for navigation uses javascript:
```
<div class="top-row ps-3 navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="">MyBlazorWeb</a>
    </div>
</div>

<input type="checkbox" title="Navigation menu" class="navbar-toggler" />

<div class="nav-scrollable" onclick="document.querySelector('.navbar-toggler').click()">
    <nav class="flex-column">
        <div class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="bi bi-house-door-fill" aria-hidden="true"></span> Home
            </NavLink>
        </div>

        <div class="nav-item px-3">
            <NavLink class="nav-link" href="counter">
                <span class="bi bi-plus-square-fill" aria-hidden="true"></span> Counter
            </NavLink>
        </div>

        <div class="nav-item px-3">
            <NavLink class="nav-link" href="weather">
                <span class="bi bi-list-nested" aria-hidden="true"></span> Weather
            </NavLink>
        </div>
    </nav>
</div>
```

Suggest you change it to event blazor and make ``@attribute``. Why? Many people who modify the template get rid of this component by putting the navigation in MainLayout. Unfortunately, Layout is not dynamic by which interactivity does not work. I caught myself in this trap.
Other people also had similar problems https://github.com/dotnet/aspnetcore/issues/50712 https://github.com/dotnet/aspnetcore/issues/50724

For the WebAssembly template, I would put the navigation in Client and do the rendering on the client side. This will be the best example for newbies. Also, in MainLayout you can comment out the link to the documentation that tells us that server-side rendering doesn't work.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The current approach is intentional and it used to be a Blazor event handler in the past.
