### ISSUE TITLE
Request to customize the http request header sent by HttpClient created in Blazor

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/aspnetcore#51247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

By default the http request headers have lots of items added by the built-in framework (message handlers?), and I'd really like an easy way to customize precisely what request headers should be present.

### Describe the solution you'd like

In some way I can clear all default request headers and only add what I want in my own code.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. MessageHandlers should allow you to customize any headers added to the request while the request is being processed on the .NET side. In the end, however, that request is being made as a browser `fetch` request, and if the browser decides to add headers at that point, there is nothing the framework can do.

**Comment by nicholasyin** [comment]
> Thanks for contacting us. MessageHandlers should allow you to customize any headers added to the request while the request is being processed on the .NET side. In the end, however, that request is being made as a browser `fetch` request, and if the browser decides to add headers at that point, there is nothing the framework can do.

How can I opt out the default request headers added by .NET then?
