### ISSUE TITLE
Static routes as string parameters for better SSR (enhancement nav) experience.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#51263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Using SSR, it's very interesting to create a website that handles "state" with url, so we don't need javascript or wasm for many things like "showing a modal".

For example, suppose the following page component:

```C#
@page "/product"
@page "/product/create"

@if (IsCreate) {
   <CreateProductForm/>
}
<ProductList/>

<a href="/product/create">Create</a>

@code {
    [Parameter] public bool IsCreate { get; set; }
}
```

The problem with that is there's no way to know if the page is at `/product` or `/product/create` so we need to use NavigationManager and start working with URI like, 
```c#
if (NavigationManager.Uri.EndsWith("/create"))
{
    isCreate = true;
}
```

which is prone to errors because if you got to `/product/create?broke=true` won't work, so you need to work with segments. (I cannot find a simple way to use segments but to do lot of code with QueryUtils and friends.

### Describe the solution you'd like

What I would like ?

There are many options that I believe are valid:

1. String parameter constrain.

```C#

@page "/product/{action:create|update|delete}"
@page "/product/"

[Parameter] public string Action { get; set; }

bool isCreate = false;

protected override void OnParametersSet() {
    isCreate = Action == "create" // case should be ignored (?)
}

```

2. Having a simple way to get route segments (maybe we already have) (?)
Not sure the proper event, since I believe url change won't trigger OnParameterSet but I'm not sure.
```C#
@page "/product/create"
@page "/product/"

protected override void OnParametersSet() { // Not sure if this is the correct override.
    IsCreate = NavigationManager.GetSegments().Any(s=>s.Equals("create", StringComparison.OrdinalIgnoreCase)
}
```

I would prefer the option 1, but I see how the option2 will work for many other scenarios.

### Additional context

If there's already a mechanism for this, I suggest to document it on [Routing docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0)

I will expect `"/product/somerandomstring"` produces a 404 not found, hence why the `"/product/{action}"` is not a good fit.

**Comment by javiercn** [comment]
@Bartmax thanks for contacting us.

This is possible via a parameter and a regex route constraint `/product/{action:regex(create|update|delete)}` (`/product/{action:regex(^create|update|delete$)}` if you want to be more precise)

**Comment by Bartmax** [comment]
works flawlessly thanks! didn't know about that.
