### ISSUE TITLE
SendPasswordResetLinkAsync Identity RC2 - Not clear

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#51278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While going through the Identity Endpoints RC2 flow, I'm only hitting the `SendPasswordResetCodeAsync` & `SendConfirmationLinkAsync`. Never the `SendPasswordResetLinkAsync`.

What is it for? When is it used? The code comments don't clarify the intent.
I would think it isn't used and someone forgot to take it out?

### Expected Behavior

Clarify its intent, when it's hit.

### Steps To Reproduce

1. Register a user `/register`. Will hit the `SendConfirmationLinkAsync`.
2. Use the `/forgotPassword` endpoint to hit the `SendPasswordResetCodeAsync`.
3. Stare into the void, wonder what the other method is for.

### Exceptions (if any)

None

I did create an API proposal: https://github.com/dotnet/aspnetcore/issues/50904
Currently the setup doesn't feel like it's meant for the Blazor WASM + API setup. Links going to the API instead of the frontend. 
It doesn't feel like it's thoroughly tested for that setup.

### .NET Version

8.0.0-rc.2.23479.6

### Anything else?

I could be missing something.

**Comment by halter73** [comment]
> While going through the Identity Endpoints RC2 flow, I'm only hitting the `SendPasswordResetCodeAsync` & `SendConfirmationLinkAsync`. Never the `SendPasswordResetLinkAsync`.

`SendPasswordResetLinkAsync` is meant for the Identity Razor Pages and Razor Components which unlike APIs are able to render UI for the password reset form with the reset code prefilled. These pages and components are either scaffolded as part of a project template or included as part of `AddDefaultIdentity`/`AddDefaultUI`. You can see example of this usage by searching this repo for `SendPasswordResetLinkAsync`.

https://github.com/search?q=repo%3Adotnet%2Faspnetcore%20SendPasswordResetLinkAsync&type=code

Feel free to submit a PR improving the doc comments for [IEmailSenderOfT](https://github.com/dotnet/aspnetcore/blob/89c2ef34b30fb2e836c198e57a29d4fa309187d6/src/Identity/Core/src/IEmailSenderOfT.cs). It might be nice to better explain exactly what calls the methods as long as it doesn't complicate things too much.
