### ISSUE TITLE
Missing Microsoft.NET.Runtime.Emscripten.3.1.12

### ISSUE THREAD

**Issue by foximoxi** [dotnet/aspnetcore#51273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CLI command dotnet workload install wasm-tools-net7
does not install missing package Missing Microsoft.NET.Runtime.Emscripten.3.1.12

Workload installation failed: One or more errors occurred. (microsoft.net.runtime.emscripten.3.1.12.node.win-x64.msi.x64::7.0.12 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://aka.ms/maui-preview/index.json;c:\projects\CSharp\nuget\".)

### Steps To Reproduce

dotnet workload install wasm-tools-net7

### .NET Version

7.0.12

**Comment by capdiem** [comment]
I have the same issue.

**Comment by S-E-F** [comment]
I have the same issue.

**Comment by SuperNose** [comment]
Same here 😖..

**Comment by nickrandolph** [comment]
Same

**Comment by foximoxi** [comment]
The workaround is to install wasm-tools using Visual Studio.
It offers wasm-tools to install but not for every wasm project.
So the package exists somewhere but does not exist in nuget repo.

**Comment by nickrandolph** [comment]
> The workaround is to install wasm-tools using Visual Studio. It offers wasm-tools to install but not for every wasm project. So the package exists somewhere but does not exist in nuget repo.

This doesn't seem to fix it for me.

**Comment by axylophon** [comment]
Same problem

**Comment by sks-ttaylor** [comment]
@jmang618 
"https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json"
comes from 

https://github.com/dotnet/emsdk/blob/main/NuGet.config

**Comment by omxie** [comment]
What helped me solve this issue was:
- Close VS
- Deleting the bin & obj of the project
- Run in terminal -> `dotnet workload repair`
- Start VS & Run Project
