### ISSUE TITLE
Global option has no effect on the Blazor Web App template when Auth is selected in NET8 RC2.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#51274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/3386797/74627a87-1538-42ac-9cac-a8a6d5123f02)

Using those settings, global is not applied properly, as shown in the following image

![image](https://github.com/dotnet/aspnetcore/assets/3386797/12b7ece6-b5d6-4f33-af10-25cfd7ce2beb)

### Expected Behavior

All pages and components should live on the client project.

### Anything else?

The template works ok if authentication is set to None.

![image](https://github.com/dotnet/aspnetcore/assets/3386797/ee6fdaf9-340d-4301-9d0b-5fc6e75ca32d)

**Comment by mkArtakMSFT** [comment]
This is something we have a pending PR for to address in 8.0 GA.
