### ISSUE TITLE
False positive: ASP0022: Route '/' conflicts with another handler route (.NET 8 RC2)

### ISSUE THREAD

**Issue by EdiWang** [dotnet/aspnetcore#51285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This code produces a build time warning `ASP0022`, inside the `try` block. 

```csharp
async Task FirstRun()
{
    try
    {
        var startUpResut = await app.InitStartUp(dbType);
        switch (startUpResut)
        {
            case StartupInitResult.DatabaseConnectionFail:
                app.MapGet("/", () => Results.Problem(
                    detail: "Database connection test failed, please check your connection string and firewall settings, then RESTART Moonglade manually.",
                    statusCode: 500
                    ));
                app.Run();
                return;
            case StartupInitResult.DatabaseSetupFail:
                app.MapGet("/", () => Results.Problem(
                    detail: "Database setup failed, please check error log, then RESTART Moonglade manually.",
                    statusCode: 500
                ));
                app.Run();
                return;
        }
    }
    catch (Exception e)
    {
        app.MapGet("/", _ => throw new("Start up failed: " + e.Message));
        app.Run();
    }
}
```

```powershell
D:\GitHub\ediwang\Moonglade\src\Moonglade.Web\Program.cs(184,28): warning ASP0022: Route '/' conflicts with another handler route. An HTTP request that matches multiple routes resul 
ts in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints. (https://aka.ms/aspnet/analyzers) [D:\GitHub\ediwang\Moonglade\s 
rc\Moonglade.Web\Moonglade.Web.csproj]
D:\GitHub\ediwang\Moonglade\src\Moonglade.Web\Program.cs(177,28): warning ASP0022: Route '/' conflicts with another handler route. An HTTP request that matches multiple routes resul 
ts in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints. (https://aka.ms/aspnet/analyzers) [D:\GitHub\ediwang\Moonglade\s 
rc\Moonglade.Web\Moonglade.Web.csproj]
```

In reality, the code will run into only one of the two `swich case` statement. There won't be any conflict because these two places can't hit at the same time.

### Expected Behavior

No warning should be displayed.

The aspnet/analyzers should check for `switch` or `if` statements before jump to conclusion that route will conflict.

### Steps To Reproduce

- Setup .NET 8.0 RC2 SDK
- Run `dotnet build` inside `https://github.com/EdiWang/Moonglade/tree/net8/src` (Note the net8 branch may be deleted in the future, I will update this issue if there's any change)

### .NET Version

8.0.100-rc.2.23502.2

**Comment by captainsafia** [comment]
@EdiWang Thanks for reporting this issue!

The analyzers currently only disamgbuate routes by their pattern and the HTTP verb associated with them. They don't possess the capability to analyzer the context of the declaration to rule out routes that are mutually exclusive.

It should be acceptable to silence the warning here.

cc: @JamesNK for his thoughts

**Comment by JamesNK** [comment]
Does the problem continue if you change the switch to an if?

There are tests that duplicate routes don't report if routes are specified in different branches of an if statement. That logic might not work with a switch statement.

**Comment by EdiWang** [comment]
There is no warning message after converting `switch-case` to `if-else`

![image](https://github.com/dotnet/aspnetcore/assets/3304703/4f7c721e-32e6-43be-9b5d-44d468e7dbc5)

Could the analyzer also add `switch-case` check besides `if` statement? Because in many cases they are the same.

**Comment by JamesNK** [comment]
Yes, that's a bug that should be fixed.
