### ISSUE TITLE
NavigationManager.NavigateTo not navigating in specific case (.NET 8 RC2)

### ISSUE THREAD

**Issue by tobiasni** [dotnet/aspnetcore#51288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an issue that the NavigationManager.NavigateTo is not navigating in a certain case. This seems to be a new bug coming with .NET 8 RC2. I tested it with .NET 7, there it works.

To reproduce this issue you can create a new Blazor Web App and add a new page:

```
@page "/test"

@attribute [StreamRendering]

@inject NavigationManager NavigationManager

<h3>Component</h3>

@code {

    protected override async Task OnInitializedAsync()
    {
        await Test();
    }

    private async Task Test()
    {
        await Task.Delay(1000);
        NavigationManager.NavigateTo("/");
    }
}
```

In this case the NavigateTo works. But when I change `OnInitializedAsync` to this, it does not work:

```
protected override async Task OnInitializedAsync()
{
    var task = Test();
    await Task.WhenAny(task);
}
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

Installierte .NET-Workloads:
 [maui-android]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Installationstyp:              Msi

 [maui-windows]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Installationstyp:              Msi

 [android]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    34.0.0-rc.2.468/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.468\WorkloadManifest.json
   Installationstyp:              Msi

 [maui-maccatalyst]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Installationstyp:              Msi

 [maccatalyst]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\16.4.8968-net8-rc2\WorkloadManifest.json
   Installationstyp:              Msi

 [maui-ios]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Installationstyp:              Msi

 [ios]
   Installationsquelle: VS 17.6.33815.320
   Manifestversion:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\16.4.8968-net8-rc2\WorkloadManifest.json
   Installationstyp:              Msi

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  7.0.304 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by surayya-MS** [comment]
Thank you for filing the bug!

I tried it out and the bug reproduced.

Also, I tried same thing but instead of `@attribute [StreamRendering]` added `@rendermode InteractiveServer` and it worked with `Task.WhenAny()`. This also works in blazor server .net 7.

**Comment by surayya-MS** [comment]
The workaround for this is to await `Task<Task> Task.WhenAny` **twice**
```csharp
protected override async Task OnInitializedAsync()
{
    var task = Test();
    await await Task.WhenAny(task);
}
```

**Comment by surayya-MS** [comment]
@mkArtakMSFT this is not resolved yet. This is a bug.

**Comment by surayya-MS** [comment]
I looked into it more to find a solution, but now I don't think it can be fixed. Let me explain. Here is what's happening.

```razor
protected override async Task OnInitializedAsync()
    {
        var task = Test();
        await Task.WhenAny(task);
    }

    private async Task Test()
    {
        await Task.Delay(1000);
        NavigationManager.NavigateTo("/");
    }
```
Navigation doesn't work on the SSR page because we can't catch the `NavigationException`. The issue arises from using `Task.WhenAny` – it prevents us from catching any exceptions. We await `OnInitializedAsync`, but there's no way to grab the completed task of `Task.WhenAny` inside `OnInitializedAsync` and re-throw it. 

The only workaround is to await twice `await await Task.WhenAny` within `OnInitializedAsync` to make sure we catch any exceptions. 

The reason this code works in server render mode is because navigation there doesn't throw a `NavigationException` but invokes the js runtime. 

I suggest documenting this so that people avoid using `Task.WhenAny` inside `OnInitializedAsync`.

@SteveSandersonMS , @javiercn , @MackinnonBuck thoughts?

**Comment by mkArtakMSFT** [comment]
Thanks for additional insights, @surayya-MS.
We've discussed this during planning earlier and have decided that we'd do nothing here due to how Task.WhenAny works. That is, Task.WhenAny returns a `Task<Task>`. Hence, the double await is expected.
