### ISSUE TITLE
.NET 8 RC1 Blazor build suddenly errors. Required parameter 'renderMode' of ...

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#51293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Yes, I'm suddenly getting the error while building RC1 Blazor.
So, I upgraded to RC2 but Azure App Service is missing that SDK.

Conclusion, I can't go back and can't go forward.

### Expected Behavior

Run Blazor either RC1 or RC2 correctly on Azure App Service.

### Steps To Reproduce

Build a Blazor RC1 project.
Or publish an RC2 project to an Azure App Service.

### Exceptions (if any)

There is no argument give that correspons to the required parameter 'renderMode' of 'RenderTreeBuilder.AddComponentRenderMode(int, IComponentRenderMode)'

### .NET Version

8.0.0-rc.1.23421.29

### Anything else?

Could be related to: https://github.com/dotnet/aspnetcore/issues/51170

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe this is due to the fact that .NET 8 RC2 hasn't yet rolled out to Azure App service. As soon as it does you should not see this issue any more.

As for having installed RC2, you can ping the SDK version using a global.json file following [this guidance](https://learn.microsoft.com/dotnet/core/tools/global-json) and that will allow your original project (RC1) to work just fine.

**Comment by augustevn** [comment]
> Thanks for contacting us. We believe this is due to the fact that .NET 8 RC2 hasn't yet rolled out to Azure App service. As soon as it does you should not see this issue any more.
> 
> As for having installed RC2, you can ping the SDK version using a global.json file following [this guidance](https://learn.microsoft.com/dotnet/core/tools/global-json) and that will allow your original project (RC1) to work just fine.

---

Thanks for the suggestion, currently does not make a difference... As I mentioned, RC1 broke over night in the pipeline. I could still build it locally. That was before upgrading to RC2.
Now with global.json, using RC1, it doesn't build locally.

I'll keep you posted.

**Comment by augustevn** [comment]
Update:

Added global.json, removed RC2, some restarts, cleans and rebuilds. Now RC1 builds again. Thanks.
