### ISSUE TITLE
BindAsync doesn't support returning ValidationErrors

### ISSUE THREAD

**Issue by Misiu** [dotnet/aspnetcore#51318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using BindAsync we must return `ValueTask.FromResult<T?>(result)` or `ValueTask.FromResult<T?>(null);`
Returning second causes getting a 400 error:

> Microsoft.AspNetCore.Http.BadHttpRequestException: Required parameter "PagingData data" was not provided from PagingData.BindAsync(HttpContext).
>    at lambda_method12(Closure, Object, HttpContext, Object[])
>    at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass89_0.<<HandleRequestBodyAndCompileRequestDelegate>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

but the end user doesn't get any info about which parameter he passed to our endpoint caused this error.

Endpoint:
```
app.MapGet("/get_users", async Task<Results<Ok<List<string>>, NotFound>> (PagingData model) =>
{
    //endpoint logic
})
```

### Describe the solution you'd like

I want to have the option to return a custom validation error for a specific property that I'm trying to bind in `BindAsync`.

### Additional context

My current approach is to throw a custom error with all the validation errors and then catch that error in a custom exception handler middleware.

**Comment by captainsafia** [comment]
@Misiu The exception that you see here is only thrown in development mode. When in production mode, you can control what exception gets thrown. One approach that you might consider here is to use an endpoint filter to check if the values have been set and return a problem details object if it's not.
