### ISSUE TITLE
blazor web app signalr configuration error

### ISSUE THREAD

**Issue by pigwing** [dotnet/aspnetcore#51312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-8.0#signalr-configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-8.0#signalr-configuration)
![image](https://github.com/dotnet/aspnetcore/assets/8393545/ece54395-c1f7-4bf2-bd8b-bdcdead443a4)
is not working,by debugging the source code,i found that
![image](https://github.com/dotnet/aspnetcore/assets/8393545/b51d9ac1-0914-410d-8768-0fcc9aee252a)
need to add circuit property
![image](https://github.com/dotnet/aspnetcore/assets/8393545/3333712f-67e3-4fff-b3a6-7d821bbec73b)
that is working

https://github.com/dotnet/aspnetcore/blob/9719821d5bb09c7cf75f82a223e8b210da65aaca/src/Components/Web.JS/src/Platform/Circuits/CircuitStartOptions.ts#L14C46-L14C53

### .NET Version

8.0.100-rc.2.23502.2

**Comment by guardrex** [comment]
@MackinnonBuck ... We've only documented `disableDomPreservation` thus far. I'll get this on the tracking issue and take care of it as soon as we get the migration/integration guidance finished, which could be later today.
