### ISSUE TITLE
[Tracking] Remove `Microsoft.NETCore.App.Ref/*8.0*` from SourceBuildPrebuiltBaseline.xml

### ISSUE THREAD

**Issue by RussKie** [dotnet/aspnetcore#51339]
https://github.com/dotnet/aspnetcore/pull/51240 was failing with:
```
.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23463.1/tools/SourceBuild/AfterSourceBuild.proj#L68
.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23463.1/tools/SourceBuild/AfterSourceBuild.proj(68,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) 1 new pre-builts discovered! Detailed usage report can be found at /__w/1/s/artifacts/source-build/self/prebuilt-report/baseline-comparison.xml.
See https://aka.ms/dotnet/prebuilts for guidance on what pre-builts are and how to eliminate them.
Package IDs are:
Microsoft.NETCore.App.Ref.8.0.0-preview.7.23375.6
```

 From @mthalman in https://github.com/dotnet/aspnetcore/pull/51240#issuecomment-1759583805:

> It's because the SDK being used for the build still points to the old 8.0 P7 version in its BundledVersions.props file causing this version to be loaded for net8.0. For now, this can be added to [`main`/eng/SourceBuildPrebuiltBaseline.xml](https://github.com/dotnet/aspnetcore/blob/main/eng/SourceBuildPrebuiltBaseline.xml?rgh-link-date=2023-10-12T13%3A08%3A54Z) as an allowed prebuilt.

**Comment by wtgodbe** [comment]
I think we can do this once dotnet/installer updates to the RTM 8.0 runtime version
