### ISSUE TITLE
Blazor .Net 8 RC2: "catch-all" route intercept files too

### ISSUE THREAD

**Issue by francescocristallo** [dotnet/aspnetcore#51330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using catch-all parameter at root: 

```razor
@page "/{*pageRoute}"
```

The page with catch-all intercept all files as well, including css and javascript isolation files, breaking the application.
The page intercept all files even in subfolders (moving app.css in css/app.css )

This was not happening in .Net 7

### Expected Behavior

If a file is present, it should have priority on "catch-all" route parameter

### Steps To Reproduce

Create new Blazor WebApp with 

-InteractiveAuto
-Interactivity per page/component

In Counter.razor, replace page with:

```razor
@page "/{*pageRoute}"
```

and add 

```csharp
 [Parameter]
 public string PageRoute { get; set; }
 ```

 Launch , the css files are catched by the page

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

**Visual Studio 2022 Version 17.8.0 Preview 3.0**

.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. In .NET 8 Blazor pages register routes and those are equivalent to any other route registered with the router. To address this, you can update your route on the component to `{*path:nonfile}` and that should work. Please let us know if this doesn't work for you.

**Comment by francescocristallo** [comment]
Thanks, it works using 

`@page "/{*pageRoute:nonfile}"`

Would be useful to add it to the documentation (I didn't find it) or evaluate to make it default behavior.
