### ISSUE TITLE
Blazor Auto RC2 is unresponsive in server mode

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/aspnetcore#51356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When loading a new site, the counter is unresponsive while in server mode. Once it is fully downloaded and switches to wasm mode, then it works.

### Expected Behavior

The counter should increment in server mode.

### Steps To Reproduce

1. Create a new Blazor Web App in RC2
2. Choose Auto and Global
3. Open Counter.razor and add this: `<p>Mode: @(OperatingSystem.IsBrowser() ? "Browser" : "Server")</p>`
4. Run the application and go to the counter page and increment the counter
5. Open the Network tab in the dev tools and check "Disable cache" and set throttling to "Fast 5G"
6. Refresh the page

ACTUAL:

You will see that the counter resets and the mode switches to "Server". While in this state, the "Click me" button will not update the counter.

After the WASM files are downloaded, the mode switches to "Browser" and the button now increments the counter.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

I was under the impression that the component would not switch modes but would wait for a page navigation before using WASM.

If I switch to "Slow 3G", it looks like it is downloading the WASM file before trying to set up the web socket.

![image](https://github.com/dotnet/aspnetcore/assets/1784452/90495641-4d47-4258-a0ae-40f83af3d6c2)

**Comment by mahald** [comment]
What you see should be the prerender. A component is rendered three times. Once in prerender then before the  LifeCycle hooks and then after them. I also noticed this but primarily when running with the debugger.
if you want to disable prerender for tests you can add this as code: 
```
@rendermode _rendermode

......


@code 
{
           private static IComponentRenderMode _rendermode = new InteractiveWebAssemblyRenderMode(prerender: false);
}
```

**Comment by mahald** [comment]
P.S.: When conducting performance testing with WASM, ensure you publish the app. This is because Tree Shaking occurs only upon publishing, which will notably reduce the size of the WASM packages.

**Comment by javiercn** [comment]
@MisinformedDNA thanks for contacting us.

Do you see any logs in the browser console indicating that the Blazor Server connection has been established and initialized? Are there any errors on the logs?

Once a component is rendered in a mode, we won't switch to a different mode until the component is removed from the document (as you mentioned) so from what you are describing, it might point out to Blazor Server failing to start in some way in your environment.
