### ISSUE TITLE
Blazor The trust relationship between the primary domain and the trusted domain failed with custom ServerAuthenticationStateProvider class.

### ISSUE THREAD

**Issue by Lmiller1708** [dotnet/aspnetcore#51350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting the "The trust relationship between the primary domain and the trusted domain failed." error when trying to add a custom ServerAuthenticationStateProvider class to be used with the following code: 

```
AuthorizeView Roles=@CustomRoles.User>
        <Authorized>
            yes
            <a id="lblUserName" class="d-block">Authorized *</a>
        </Authorized>
        <NotAuthorized>
            <a id="lblUserName" class="d-block">NotAuthorized</a>
        </NotAuthorized>
        <Authorizing>
            <a id="lblAuthorizing" class="d-block">Authorizing</a>
        </Authorizing>
</AuthorizeView>
```

### Expected Behavior

Return True here:
```
if (user.IsInRole(User))
{

}
```

### Steps To Reproduce

Create a new Blazor server-side app with no authorization.
Add the following class in the app with the following code:
	
	```
        using Microsoft.AspNetCore.Components.Authorization;
	using Microsoft.AspNetCore.Components.Server;
	using System.Security.Claims;

	namespace BlazorApp1.Data
	{
		public class CustomRoles : ServerAuthenticationStateProvider
		{

			public const string User = "USER";
			private const string strRole = "Custom Roles";
			public static ClaimsIdentity UserRole
			{
				get
				{
					var identity = new ClaimsIdentity(new[]
					{
						new Claim(ClaimTypes.Name, "Normal User"),
						new Claim(ClaimTypes.Role, User)
					}, strRole);
					return new ClaimsIdentity(identity);
				}
			}

			public override async Task<AuthenticationState> GetAuthenticationStateAsync()
			{
				var authState = await base.GetAuthenticationStateAsync();
				var user = authState.User;

				// add some new identities to the Claims Principal
				user.AddIdentity(UserRole);

				if (user.IsInRole(User))  //Fail HERE
				{

				}

				// return the modified principal
				return await Task.FromResult(new AuthenticationState(user));
			}

			public void NotifyAuthenticationStateChanged()
			{
				NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());
			}

		}
	}
```

And add the following lines in Program.cs:

```
builder.Services.AddScoped<AuthenticationStateProvider, CustomRoles>();

app.UseAuthentication();
app.UseAuthorization();
```

And in the Configure method add these lines:

 app.UseAuthentication();
 app.UseAuthorization();

### Exceptions (if any)

Message: 
	The trust relationship between the primary domain and the trusted domain failed.

StackTrace: 
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
TargetSite:
	{System.Security.Principal.IdentityReferenceCollection TranslateToSids(System.Security.Principal.IdentityReferenceCollection, Boolean ByRef)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

### .NET Version

7.0

### Anything else?

Including Package System.Security.Principal.Windows Version 5.0.0

**Comment by javiercn** [comment]
@Lmiller1708 thanks for contacting us.

Your issue seems specific to windows authentication. Probably manipulating the claims principal in the way, you are doing is not appropriate.

It might also be that the operation you are trying to perform with the principal is not possible. In the context of a Blazor Server app, the code runs on the server, as opposed to the browser.
