### ISSUE TITLE
Blazor AuthorizeView in latest .Net8.rc-2 Blazor-Web-App template not working reliably

### ISSUE THREAD

**Issue by mahald** [dotnet/aspnetcore#51368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Auth page the AuthorizeView does not work reliably in Blazor-Web-App Template.
Sometimes the "Hello {Username}" inside the AuthorizeView is not displayed (see steps to reproduce)

![image](https://github.com/dotnet/aspnetcore/assets/6714894/c5f20da0-41de-4fa0-8ead-fe03d0cd000b)

### Expected Behavior

The "Hello {Username}" should be displayed always.

### Steps To Reproduce

* Create new "Blazor-Web-App" with the options "Single Accounts / Auto / perPage"
* Start it 
* Create login and Login
* Click on Counter
* Reload Page
* Click on Auth

then "Hello ..." in AuthorizeView  should not be displayed. If you reload again while on the Auth page, it's becoming visible.

PS: if changing it to: 
```
<AuthorizeView>
     <Authorized>
            <p>You are authorized</p>
            Hello @context.User.Identity?.Name!
    </Authorized>
    <NotAuthorized>
            <p>You are not authorized</p>   
    </NotAuthorized>
</AuthorizeView>
```
it shows:  You are not authorized

### .NET Version

8.0.100-rc.2.23502.2

**Comment by mahald** [comment]
Thank you for your guidance. To illustrate the issue:

You can view the behavior in this video: https://clipchamp.com/watch/VIbFXuH2rx8.

The code in question is essentially the default from the Blazor-Web-App Template. You can find it here: https://github.com/mahald/aspnetcore_issue_51368.

I hope this helps with your investigation.

**Comment by halter73** [comment]
Thank you for filing this issue @mahald! We'll probably be able to get this fixed for our final .NET 8 release thanks to your help. In the meantime, you should be able to fix this issue on your end by making the same changes to `PersistentAuthenticationStateProvider` that I made in https://github.com/dotnet/aspnetcore/pull/51497.
