### ISSUE TITLE
Server Layout used by RC2 Blazor Web App page inside Client project

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#51376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With RC2 you can now host actual pages defined inside the Client project of a `Blazor Web App` solution using the new initialization code in the server startup:

```
app.MapRazorComponents<App>()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(BlazorWebApp1.Client.Pages.Test).Assembly);
```

I've tested it and it picked the `MainLayout` of my server project. Which was fine in my particular case. But how would you override that in case you need a different layout?

### .NET Version

8.0.100-rc.2.23502.2

**Comment by mahald** [comment]
you could define the Page in the server and then just use the Component/Page from the. Client project

```
@page "/testLayout"
@layout MainLayoutTopBar
@using BlazorWebApp.Client.Pages
@using BlazorWebApp.Components.Layout

<h3>TestLayout</h3>

<Counter ></Counter>
```

**Comment by oliverw** [comment]
> you could define the Page in the server and then just use the Component/Page from the. Client project
> 
> ```
> @page "/testLayout"
> @layout MainLayoutTopBar
> @using BlazorWebApp.Client.Pages
> @using BlazorWebApp.Components.Layout
> 
> <h3>TestLayout</h3>
> 
> <Counter ></Counter>
> ```

Yes, of course. But it feels weird that a default value is picked with no (obvious) way to override it.

**Comment by oliverw** [comment]
@mkArtakMSFT If you attempt to override the layout on the Client project the page crashes because it attempts to render the layout on the server during pre-render but cannot serialize @body because it is "arbitrary code".

**Comment by oliverw** [comment]
@mkArtakMSFT Any chance for a bit of clarification on this?
