### ISSUE TITLE
Blazor Web App with .net 8 rc2 not working, "App" not found

### ISSUE THREAD

**Issue by CrosRoad95** [dotnet/aspnetcore#51387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'BlazorApp6' could not be found (are you missing a using directive or an assembly reference?)	BlazorApp6	BlazorApp6\Program.cs	1	Active
```

![image](https://github.com/dotnet/aspnetcore/assets/22455534/2d9874ec-fda9-4515-937f-06a604aad19e)

### Expected Behavior

It should just run

### Steps To Reproduce

1. create blazor web app project with default settings
2. press f5

### Exceptions (if any)

If i create file App.razor.cs
```csharp
public partial class App : ComponentBase
{
}
```
it compiles, but doesn't map any page, all of  them are 404

### .NET Version

8.0.100-rc.2.23502.2

**Comment by gragra33** [comment]
@CrosRoad95 Check your error message: `Targeting .Net 8.0 or higher in Visual Studio 2022 17.7 is not supported`. You need to use the `Preview` version of VS 2022.

**Comment by CrosRoad95** [comment]
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
good point, i have seen this message before but it worked fine so i moved on. installed preview version and now it compiles
