### ISSUE TITLE
Failed to load dotnet.js on InteractiveWebAssembly render mode

### ISSUE THREAD

**Issue by TimPurdum** [dotnet/aspnetcore#51384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using `RenderMode.InteractiveWebAssembly` or `InteractiveAuto` at the top level in `App.razor` as described in [Render Modes](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#set-the-render-mode-for-the-entire-app) causes an error in the browser:

`dotnet.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

### Expected Behavior

We should be able to set the default render of the Web App to `Auto` or `WebAssembly`, and let that setting cascade through all pages and components. Without this, developers would need to maintain knowledge of the separate, older Blazor Wasm patterns to develop wasm-first apps.

### Steps To Reproduce

1. Create a new Blazor Web App with `dotnet new blazor -o TestApp`
2. Add nuget reference for WebAssembly:
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.0-rc.2.23480.2" />
</ItemGroup>
```
3. Add `AddInteractiveWebAssemblyComponents()` and `AddInteractiveWebAssemblyRenderMode()` in `Program.cs
```csharp
builder.Services.AddRazorComponents()
    .AddInteractiveWebAssemblyComponents()
    .AddInteractiveServerComponents();
...
app.MapRazorComponents<App>()
    .AddInteractiveWebAssemblyRenderMode()
    .AddInteractiveServerRenderMode();
```
4. Add `@rendermode` to `HeadOutlet` and `Routes` in `App.razor`
```html
    <HeadOutlet @rendermode="InteractiveWebAssembly"/>
</head>

<body>
<Routes @rendermode="InteractiveWebAssembly"/>
```
5. On `Counter.razor`, remove the `@attribute [RenderModeInteractiveServer]`.
6. Run the application. Navigation works, but the `Counter` button does not. Errors in the browser.
![image](https://github.com/dotnet/aspnetcore/assets/17970404/25dafb37-cbf3-42eb-ac74-09dfa1695c11)

### Exceptions (if any)

Exception only in browser dev tools: 

`dotnet.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

### .NET Version

8.0.100-rc.2.23502.2

**Comment by TimPurdum** [comment]
Actually, I'd like to update this. I just tested `RenderModeInteractiveWebAssembly` at the page level in `Counter.razor`, removing the `App.razor` rendermodes, and got the same error. Is Blazor Wasm totally broken in RC2? Or am I missing some key setting that isn't well documented?

**Comment by TimPurdum** [comment]
I'm seeing from [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-8.0#blazor-web-app) that single-project with Wasm rendering isn't actually a supported pattern in .NET 8. This is apparently a major failing of documentation and CLI tooling, that I can spend hours reading and trying things, and only by switching to a VS-generated template can I actually understand the project structure.

**Comment by augustevn** [comment]
1. Does your navigation use @onclick or just simple <a href> tags?
2. You could still use the `blazorwasm` (Blazor WebAssembly Standalone) template.
3. Cleaning and rebuilding your projects can work wonders after upgrading to RC2
     - That worker for me when my InteractiveWebAssembly got treated like static.
     
I'm just someone passing by.

**Comment by TimPurdum** [comment]
> Thanks for contacting us.
> Can you please clarify how did you create your project in the first place? Also, a repro would help us understand the problem better and decide how to move forward.

I created one project with the CLI. The options to add interactivity were not obvious without digging through `--help`. Another project I was updating and refactoring from a Web Api template to add Blazor. These paths should be supported with documentation. I couldn't find anything like "here's how you set up a BWA".

**Comment by mkArtakMSFT** [comment]
@TimPurdum just to confirm our understanding here, are you asking about guidance for how to update your non-Blazor project to .NET 8 and bring Blazor into it?
If so, maybe this documentation can be a good starting point: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0 ?
