### ISSUE TITLE
Blazor template issues with Google Authentication [dotnet 8 rc2]

### ISSUE THREAD

**Issue by sikora507** [dotnet/aspnetcore#51402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are some issues with google authentication when using blazor templates from the dotnet 8 rc2.
* Error when trying to enter my account page (manage) after signing in with google
* For page that requires authenticated user, my first and last name is visible for a second but then swaps with my email address.
* Cannot log out when signing in with google

### Expected Behavior

* There should be no error after entering my account's page
* The page that requires authenticated user should display either my email or first + last name
* I should be able to log out

### Steps To Reproduce

Create new blazor project:
`dotnet new blazor -n AuthTest -au Individual -int Auto -ai`

> After following the link provided in the template to configure external auth:
> https://go.microsoft.com/fwlink/?LinkID=532715

Add the google package:
`dotnet add package Microsoft.AspNetCore.Authentication.Google --version 7.0.12`

Add .AddGoogle() section in Program.cs:
```csharp
builder.Services.AddAuthentication(IdentityConstants.ApplicationScheme)
    .AddGoogle(options =>
    {
        options.ClientId = builder.Configuration["Authentication:Google:ClientId"]!;
        options.ClientSecret = builder.Configuration["Authentication:Google:ClientSecret"]!;
    })
    .AddIdentityCookies();
```
Add your client id and secret to the appsettings.json:
```
  "Authentication": {
    "Google": {
      "ClientID": "<your client id here>",
      "ClientSecret": "<your client secret here>"
    }
  }
```
**The ClientId and ClientSecret are taken from console.cloud.google.com:**
after creating a project, go to
Api & Services -> Credentials
![image](https://github.com/dotnet/aspnetcore/assets/4272052/ba68738f-51b4-4e05-a7f3-50d473c89a78)

Then create new OAuth Client ID
![image](https://github.com/dotnet/aspnetcore/assets/4272052/8aa3de7b-d02c-4159-bb94-3730908e73a9)

Set the type of Web Application
![image](https://github.com/dotnet/aspnetcore/assets/4272052/b8ea3e3d-db8a-4f41-a530-a92dbee6d3bb)

Set redirect uri similar to this, but put there your port that will be probably different than mine
![image](https://github.com/dotnet/aspnetcore/assets/4272052/ca175016-73d2-4e69-9e42-7cb2a3fe35bf)

Once you have client id and secret you will be able to log in with Google.
However when I try to enter the `/account/manage/` endpoint (when I click on the link with my first and last name in the menu) I am redirected to InvalidUser page:
<img width="824" alt="image" src="https://github.com/dotnet/aspnetcore/assets/4272052/66eb832f-b20e-4b67-a611-5ea652b9719a">

There is another thing:
When I try to enter "Auth Required" page, I see my first name and last name for a brief moment, but then I think the web assembly kicks in and swaps it with my email:
<img width="693" alt="image" src="https://github.com/dotnet/aspnetcore/assets/4272052/a68828f1-29a8-4914-baa1-34514a7c68a3">

### .NET Version

8.0.100-rc.2.23502.2

**Comment by halter73** [comment]
Thanks for the report. You should be able to fix the "Unable to load user with ID ..." error by changing

```csharp
builder.Services.AddAuthentication(IdentityConstants.ApplicationScheme)
```

to

```csharp
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
```

This ensures the Google/OAuth [`RemoteAuthenticationHandler` callback handler uses the correct IdentityConstants.ExternalScheme scheme](https://github.com/dotnet/aspnetcore/blob/89c2ef34b30fb2e836c198e57a29d4fa309187d6/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L172) so [SignInManager.GetExternalLoginInfoAsync()](https://github.com/dotnet/aspnetcore/blob/89c2ef34b30fb2e836c198e57a29d4fa309187d6/src/Identity/Core/src/SignInManager.cs#L689-L691) can use that same scheme to read the `LoginProviderKey` set by the `RemoteAuthenticationHandler`.

`Program.cs` templates have already been updated to set the `DefaultSignInScheme` to `IdentityConstants.ExternalScheme` as part of #51134.

> When I try to enter "Auth Required" page, I see my first name and last name for a brief moment, but then I think the web assembly kicks in and swaps it with my email:

I wasn't able to reproduce this even with the older RC2 template after updating the `DefaultSignInScheme`. I see my email address during both the initial static render and the WebAssembly rerender. I'm guessing this has something to do with the wrong `DefaultSignInScheme` leaving you half logged in.

<img width="478" alt="Auth Required page with network logs" src="https://github.com/dotnet/aspnetcore/assets/54385/e67193c5-54ee-43bc-9ffa-35cff8db9e78">

Can you confirm that changing the `DefaultSignInScheme` fixes this issue too?
