### ISSUE TITLE
Using FallbackPolicy significantly increase used memory on Ubuntu in kubernetes

### ISSUE THREAD

**Issue by GabrielMancik** [dotnet/aspnetcore#51416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Application is running in kubernetes on Ubuntu 22.04.2 LTS. 
I have tested in on 6.0 and 8.0 rc 2 versions
![image](https://github.com/dotnet/aspnetcore/assets/12762648/ad1d925a-c1bc-41bc-ad7d-c351d8fea324)
![image](https://github.com/dotnet/aspnetcore/assets/12762648/7b72e1eb-63a4-4405-8018-eeaaab8b3869)

I have a very simple web api project with only one controller and one endpoint in it.

Controller looks like this:

```
[Route("api/[controller]")]
[ApiController]
public class ContentController : ControllerBase
{
  [AllowAnonymous]
  [HttpHead("{businessUnitId}/{contentFileType}/{*fileName}")]
  [HttpGet("{businessUnitId}/{contentFileType}/{*fileName}")]
  public ActionResult Get()
  {
	  return new StatusCodeResult(StatusCodes.Status304NotModified);
  }
}
```

Policy setup: 

```
return services.AddAuthorizationCore(options =>
{
  var defaultPolicy = new CustomPolicyBuilder().Build();
  
  options.DefaultPolicy = defaultPolicy;
  options.FallbackPolicy = defaultPolicy;
});
```

version 8.0 rc 2- When fallback policy is set (top lines) vs without it (botton lines)
I have tested it multiple times so thats why there are more lines in both groups:
![image](https://github.com/dotnet/aspnetcore/assets/12762648/6603e9b3-6adf-443b-a4e6-05dc5b880eec)

version 6.0:
![image](https://github.com/dotnet/aspnetcore/assets/12762648/2ea5e446-fa23-42e4-80b3-7d62781825eb)

Setting default policy has no visible impact on memory usage. 
I am not sure what more info to provide so I will post it as needed.

**Comment by captainsafia** [comment]
Thanks for filing this issue, @GabrielMancik!

Do you repro this behavior locally as well?

cc: @BrennanConroy @halter73
