### ISSUE TITLE
[.NET 8 RC2] HttpContext is null in Login.razor (Identity scaffold) with InteractiveServer globally enabled

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#51422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a template with InteractiveServer globally enabled in the VS Template (with no sample pages) as well as Individual Accounts enabled.

I navigate to /Account/Login with the chrome URL and press Enter. It works, I guess because it's a new request and HttpContext is possible to get this way.

When I create an a href="/Account/Login"-button in Home.razor - and pressing the button... It causes an exception because Login.razor OnInitialized method uses HttpContext without null-checking it (default!). 

Note: Adding data-enhance-nav="false" in my a href in Home.razor doesn't work either.

### Expected Behavior

I expect to navigate to Login with a href button without any exceptions.

### Steps To Reproduce

1. Create Blazor Web App
2. Choose Individual Accounts
3. Choose InteractiveServer
4. Choose Globally
5. Make an a href="/Account/Login"-button in Home.razor
6. Press the button
7. Exception occurs

### Exceptions (if any)

System.NullReferenceException: 'Object reference not set to an instance of an object.'

BlazorApp14.Components.Pages.Account.Login.HttpContext.get returned null.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by DM-98** [comment]
Anothe "Bug" I found, was that creating this template shown in the steps above doesn't make it globally interactive in App.razor... I had to manually add @rendermode="@RenderMode.InteractiveServer" for both HeadOutlet and Routes.

**Comment by DM-98** [comment]
I managed to Null check `if (HttpContext is not null)`...and in StatusMessage.razor component with the HttpContext and continued with the process of pressing the Login button with the correct login-info - it throws an exception like this:
`InvalidOperationException: Headers are read-only, response has already started`

**Comment by javiercn** [comment]
@DM-98 thanks for contacting us.

HttpContext is only available during server-side rendering, when the app becomes fully interactive it uses SignalR and there is no HttpContext available as there is no associated request.

**Comment by DM-98** [comment]
Then the whole Individual Accounts template with interactive server non-functional... Isn't that a bug?

**Comment by Kumima** [comment]
This will be fixed in next GA version. If you enable the Global RenderMode as Server, the project template for now will make all the pages rendered as server, which means there will be no HttpContext. You can check issue https://github.com/dotnet/aspnetcore/pull/51134 to preview the change. The StatusMessage will be unused and the Account pages will be rendered static even if you enable the global rendermode. Account pages rely on SignInManager which needs the HttpContext, so they have to be rendered as Static.

**Comment by efonsecab** [comment]
@Kumima Does that PR also fixes the issue of the HttpContext forgetting the client's current route when the Route component is set to Interactive Server?

**Comment by codemonkey85** [comment]
> This will be fixed in next GA version.

Meaning the release next week?

**Comment by jschilb** [comment]
I'm running into this exact issue trying to convert a .NET 6 Blazor server app to .NET 8. I'd prefer to set RenderMode.InteractiveServer at the global level, but I continue to get null exceptions in Login.razor.
