### ISSUE TITLE
Is {PARAMETER NAME}Expression API in blazor data binding internal only?

### ISSUE THREAD

**Issue by AntMaster7** [dotnet/aspnetcore#51444]
I did open an issue in AspNetCore.Docs regarding an undocumented API / feature in Blazor and was asked to open an issue here regarding the question whether this API / feature is meant to be used by developers or if it is only for internal purposes and therefore undocumented?

The feature in question is the injection of the bound parameter expression in a component if you have a parameter of type Expression with the name {PARAMETER NAME}Expression in a blazor component.

```C#
[Parameter] public string? Text { get; set; }

[Parameter] public EventCallback<string?> TextChanged { get; set; }

// parameter expression of the Text parameter gets injected here, but this feature / API is not documented
[Parameter] public Expression<Func<string?>>? TextExpression { get; set; } 
```

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30656

**Comment by javiercn** [comment]
@AntMaster7 thanks for contacting us.

It's not an internal feature, it's part of the `@bind` support for components. I do not believe it works outside `@bind` but I might be wrong.

**Comment by guardrex** [comment]
We never documented it, and it sounds like we can proceed to do so ... ***but*** it will need to be tabled to 24Q1 (probably) due to the .NET 8 workload.

**Comment by javiercn** [comment]
I would not prioritize it
