### ISSUE TITLE
Blazor Minify, Bundle Static Files - Native Support

### ISSUE THREAD

**Issue by Beblia** [dotnet/aspnetcore#51446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

It would be great if .Net 9 would have native support for Minifying and Bundling Static files. 
Bundle + Minify = CSS
Bundle + Minify = Javascript
Minify = SVG
Minify = Json
Minify = Razor

There are nuget packages that can do some of these things but not all of them. Native support would be a better solution long term. Would be awesome to have this inclusion in the next .Net. Thank you.

**Comment by mkArtakMSFT** [comment]
@javiercn  FYI.
