### ISSUE TITLE
data-enhance-nav=false is ignored on <svg> elements

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#51440]
Inside `NavigationEnhancement.ts`, the logic that decides whether to bypass enhanced nav based on the element clicked looks like:

```ts
  if (event.target instanceof HTMLElement && !enhancedNavigationIsEnabledForElement(event.target)) {
    return;
  }
```

It should say `Element` instead of `HTMLElement`, because `HTMLElement` excludes `SVGElement`. There is no reason why SVG elements should behave differently from HTML elements in this regard.

**Comment by surayya-MS** [comment]
Couldn't repro this bug because of this bug https://github.com/dotnet/aspnetcore/issues/51705
When I fixed that one this one reproed

**Comment by SteveSandersonMS** [comment]
@surayya-MS The repro is a scenario like this. Sorry I should have specified it in the original report.

```razor
<a href="something" data-enhance-nav="false">
    <svg width="400" height="110">
        <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
    </svg>
</a>
```

Expected: If you click on the SVG, it should do regular (non-enhanced) nav because of `data-enhance-nav="false"`
Actual: It will ignore `data-enhance-nav="false"` and do enhanced nav anyway

**Comment by surayya-MS** [comment]
I'll add this test case
