### ISSUE TITLE
UserManager.ChangePasswordAsync doesn't sign out on other devices

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/aspnetcore#51450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling `UserManager.ChangePasswordAsync` to change someone's password, other sessions on other devices/browsers/instances are still valid.

There's no way to change this behavior.

### Expected Behavior

1) Default behavior where cookies are made invalid after calling `UserManager.ChangePasswordAsync`
2) Or an option where we can tailor the behavior of `UserManager.ChangePasswordAsync` to invalidate existing sessions/Identity cookies
3) Could as well be configured in the `IdentityOptions`. I checked those, but there doesn't seem to be a setting for this

### Steps To Reproduce

Sorry 1000 times, but I sadly have no time now to create a minimal repro. [Here's](https://github.com/MintPlayer/MintPlayer/blob/master/MintPlayer.Data/Repositories/AccountRepository.cs#L369) the application code command

ATM there are no overloads for this method, just the single method

    ChangePasswordAsync<TUser>(TUser user, string currentPassword, string newPassword);

### .NET Version

.NET 6

**Comment by halter73** [comment]
The `UserManager` does [update the user's security stamp](https://github.com/dotnet/aspnetcore/blob/d025c79968d63df02830f9b9914707db4d9f02d5/src/Identity/Extensions.Core/src/UserManager.cs#L2415) every time the password is changed. It's up to the `AuthenticationHandler`'s used to authenticate the device to check if the security stamp has changed whenever it authenticates a user using something like the built-in [SecurityStampValidator](https://github.com/dotnet/aspnetcore/blob/d025c79968d63df02830f9b9914707db4d9f02d5/src/Identity/Core/src/SecurityStampValidator.cs#L117). Identity [sets this up for you automatically](https://github.com/dotnet/aspnetcore/blob/d025c79968d63df02830f9b9914707db4d9f02d5/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L56) for `AddIdentityCookies`, so all you should need to do for cookie auth to get it to check the database on every request if the security stamp has not changed, is something like the following:

```csharp
services.Configure<SecurityStampValidatorOptions>(securityStampValidatorOptions =>
{
    securityStampValidatorOptions.ValidationInterval = TimeSpan.Zero;
});
```

Naturally, there's no way to immediately sign out other devices unless those other devices query the database every time they attempt to make an authenticated request which can reduce performance.

For other non-cookie authentication handlers like the `JwtBearerHandler`, you'll need to hook `JwtBearerEvents.OnMessageReceived` yourself to check the security stamp for each authenticated request.
