### ISSUE TITLE
InputRadio didn't accept "checked" attribute

### ISSUE THREAD

**Issue by BigSquareHasNoEdge** [dotnet/aspnetcore#51451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 InputRadio ingnores  "checked" attribute.

### Expected Behavior

It has to work as like:
`<input name="inputGroup" type="radio" checked>.`

### Steps To Reproduce

`<InputRadioGroup @bind-Value="@_selected">`
`  <InputRadio Value="@("Hello")">Hello</InputRadio>`
`  <InputRadio checked Value="@("World")">World</InputRadio>`
`</InputRadioGroup >`

`@code{`
`private string? _selected;`
`}`

### .NET Version

7.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `checked` attribute shouldn't be used with the `InputRadio` component. Instead, use the `Value` property and the `@bind-Value` directive on the InputRadioGroup to specific which option is checked. Here is an example showing how to do it: https://learn.microsoft.com/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#radio-buttons

**Comment by BigSquareHasNoEdge** [comment]
@mkArtakMSFT I know how to use it. However, the problem is InputRadioGroup can't handle null value as an option. 
In result, null value option can't be checked.
So, I need an alternative way to make "null" checkable.
