### ISSUE TITLE
Blazor Identity with Global RenderMode

### ISSUE THREAD

**Issue by IamRewt** [dotnet/aspnetcore#51476]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Making a new Blazor WebApp in RC2, if you select individual accounts and Global Interactive server mode:

1) The template does not automatically add `@rendermode="RenderMode.InteractiveServer"` to the App.razor Routes and Head Outlet components. This only occurs when using the new identity pages, when they are excluded, the rendermode is automatically added.

2) When you manually add the global rendermode in, the identity pages begin giving Null Reference Exceptions in several locations. For example: visiting the Register Page throws a null reference exception in StatusMessage.razor @ line 28: `private string? MessageFromCookie => HttpContext.Request.Cookies[IdentityRedirectManager.StatusCookieName];`

Removing the global rendermode from the Routes component stops the exceptions, but then eliminates the needed functionality.

### Expected Behavior

The expected behavior was to be able to use the Interactive Server Render Mode globally with the new razor identity pages.

### Steps To Reproduce

1. Create a new blazor web app in RC2.
2. Select 'Individual Accounts' for Authentication Type.
3. Select 'Server' for Interactivity Type.
4. Select 'Global' for Interactivity Location.
5. Add `@rendermode="RenderMode.InteractiveServer" ` to the HeadOutlet and Routes components in /Components/App.razor.
6. Run the application.
7. Navigate to Register or Login pages.

### Exceptions (if any)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=BlazorApp1
  StackTrace:
   at BlazorApp1.Components.Identity.StatusMessage.get_MessageFromCookie() in F:\BlazorApp1\BlazorApp1\Components\Identity\StatusMessage.razor:line 28

### .NET Version

.NET8 RC2

**Comment by Kumima** [comment]
This will be fixed in next GA version. If you enable the Global RenderMode as Server, the project template for now will make all the page render as server, which means there will be no HttpContext. You can check issue #51134 to preview the change. The StatusMessage will be unused and the Account pages will be rendered static even if you enable the global rendermode. Account pages rely on SignInManager which needs the HttpContext, so they have to be rendered as Static.

**Comment by javiercn** [comment]
@Kumima answer is correct here.

/cc @halter73

**Comment by cactusoft** [comment]
Found the same issue, good to see it will be fixed in GA. I was having trouble figuring out a workaround.

**Comment by Stonne** [comment]
thanks Mabulla you saved my day thumbs up!!.
However In App.razor I had to add   :  @inject IHttpContextAccessor HttpContextAccessor
and in the code block   : private HttpContext HttpContext => HttpContextAccessor.HttpContext; 
before 
 private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
        ? null
        : InteractiveServer;
