### ISSUE TITLE
Blazor Web Individual Account Template does not have the Logout form handler

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspnetcore#51489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Issue #51134 replace the LogoutForm into a standard post form. This can fix the problem that the LogoutForm won't work when nested in Interactive RenderMode, since it needs the HttpContext. The standard post form needs a form handler, but I did not find the endpoint definition of Account/Logout. Thre will be no handler for the logout form. If I get something wrong?
```diff
- <LogoutForm id="logout-form" />
- <NavLink class="nav-link" href="#" onclick="document.getElementById('logout-form').submit(); return false;">
-     <span class="bi bi-arrow-bar-left-nav-menu" aria-hidden="true"></span> Logout
- </NavLink>
+ <form action="Account/Logout" method="post">
+   <AntiforgeryToken />
+     <input type="hidden" name="ReturnUrl" value="@currentUrl" />
+     <button type="submit" class="nav-link">
+         <span class="bi bi-arrow-bar-left-nav-menu" aria-hidden="true"></span> Logout
+     </button>
+ </form>
```

### Describe the solution you'd like

Add the needed form handler if there is something wrong. If not, point out the existing handler code location.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This has already been fixed for the upcoming RTM release.

**Comment by halter73** [comment]
> The standard post form needs a form handler, but I did not find the endpoint definition of Account/Logout. Thre will be no handler for the logout form. If I get something wrong?

The logout endpoint is defined using `MapPost` ([Minimal APIs](https://learn.microsoft.com/aspnet/core/fundamentals/minimal-apis)) in IdentityComponentsEndpointRouteBuilderExtensions along with a few other endpoints that support the Identity Razor components.

https://github.com/dotnet/aspnetcore/blob/198857c8a2211931739e6e08facfbab52f8dd023/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/IdentityComponentsEndpointRouteBuilderExtensions.cs#L43-L50
