### ISSUE TITLE
[SignalR] When testing end-to-end in Github Workflow, sometimes a client may not receive a message

### ISSUE THREAD

**Issue by aa89227** [dotnet/aspnetcore#51492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This problem is only encountered in github workflow and it's a very small chance, no problem at all in local testing.
I'm doing e2e testing of signalr, and when there are multiple clients connected, sometimes a client fails to receive a message.
I tried to trace it using log, but I don't see any problem, only that the client doesn't receive the message.

### Steps To Reproduce

repo: https://github.com/aa89227/SignalR-E2ETestingExample

failure workflow: [This Job only prints out the client side log, I think the server side log will cause the problem to be impossible to reproduce (see the workflow of the first two commits for details)](https://github.com/aa89227/SignalR-E2ETestingExample/actions/runs/6571809322)

### .NET Version

7.0.402

**Comment by BrennanConroy** [comment]
Add more logging, you don't really have any right now. Also, disable response compression just to minimize the surface area for issues to occur.
