### ISSUE TITLE
RC2 Blazor Web App template nits and inconsistencies

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#51495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A few small nits / inconsistencies after creating a new "Blazor Web App" template with the following options
![image](https://github.com/dotnet/aspnetcore/assets/4984486/835550e5-3984-4fef-961b-fb2318a01177)

1. ``ManageNavMenu.razor`` in ``Components\Layout`` has superfluous ``;`` that can be omitted:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/e4c7b0af-c4f4-474f-9e4d-dfc0901da7f8)

2. In the same file, the private component variable is prefixed with an underscore:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/1ddd7189-3ec4-4a82-87a4-40aa2d6c8ef7)
However, in the Weather.razor the underscore-less convention is used:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/f1cf0ed3-216c-48a9-af71-23280df7e216)
My personal coding style is: If it is used in the razor template, use a private property, else a private variable with underscore. That way I can distinct private vars only for the code section and vars used in the render template.  
RegisterConfirmation.razor is then inconsistent again with no explicit private modifier and no underscore. Same in ResetPassword.razor
![image](https://github.com/dotnet/aspnetcore/assets/4984486/b17519d2-7da2-41d2-8b3c-3b063294002e)

3. ``StatusMessage.razor`` has logic in the razor template. I would avoid doing that and move the code block at the top into OnParametersSet override.
![image](https://github.com/dotnet/aspnetcore/assets/4984486/3dee07af-4757-4b37-a085-1849da52f0d3)

4. In a couple of places OnInitialized sets a Parameter, but OnParametersSet will always override that, I think. 
![image](https://github.com/dotnet/aspnetcore/assets/4984486/d98f869f-ea5f-43f1-98ad-393129f81751)
Also in ExternalLoginPicker.razor, LoginWith2fa.razor, LoginWithRecoveryCode.

5. Unused using and inject in Index.razor in Account/Manage and in PersonalData.razor, Register.razor:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/01829b86-9517-4195-a146-9554612555c3)
As a side note, I usually move all the usings to the _Imports.razor file so the component files are short and concise.

6. Two properties in the Error.razor can be made private:
![image](https://github.com/dotnet/aspnetcore/assets/4984486/24ddcec5-d2b8-4e05-a6ae-c865745245a7)

### Expected Behavior

Running the template produces concise, correct code

### Steps To Reproduce

Run the template as demonstrated above and inspect all the files

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

17.8 Preview 3

**Comment by halter73** [comment]
Thank you for reporting these issues! Between #51134 and #51497, all 6 issues you highlight should be addressed.

**Comment by rogihee** [comment]
Thanks for listening en fixing!
