### ISSUE TITLE
Blazor Server in .NET 8 preview 7 not working when published for Linux

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/aspnetcore#51493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created new Blazor Web App from latest Visual Studio 2022 preview.
I chose Blazor without interactivity.
Only modified two lines:

![image](https://github.com/dotnet/aspnetcore/assets/2196235/dba732d2-b941-4276-a1ba-c4099c8929b4)

I publish new blazor server app for linux with this publish profile:
linux x64, self contained, single file, trimmed
```

<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <DeleteExistingFiles>true</DeleteExistingFiles>
    <ExcludeApp_Data>false</ExcludeApp_Data>
    <LaunchSiteAfterPublish>true</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>bin\Release\net8.0\publish\</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <_TargetId>Folder</_TargetId>
    <SiteUrlToLaunchAfterPublish />
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <ProjectGuid>0bda35d9-884b-4f6e-8aff-a87c44134866</ProjectGuid>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
</Project>
```

I copy the publish result to Ubuntu Server 22.04:
![image](https://github.com/dotnet/aspnetcore/assets/2196235/f4903a2c-40a5-46fe-8fae-85e7d0b48ec4)

Then, every request to blazor pages ends with 404 not found.
However request to "/test" returns HTTP 200 "test ok".

![image](https://github.com/dotnet/aspnetcore/assets/2196235/22d08bf7-39b8-4992-8b4a-f01001a0cecf)

Every request to blazor page ends with 404.

I tried to to the same publish with MVC and API project and they both work just fine.

The only problem is with Blazor. I tried blazor in server interactivity settings, it ends the same way. I tried Blazor Server on .NET 7 it ends with some exception.

### Expected Behavior

Blazor pages returning content.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by LukasKubicek** [comment]
When running from Visual Studio, blazor pages are working ok. The problem is with published app on linux.

**Comment by martincostello** [comment]
Does the issue still replicate with .NET 8 release candidate 2 and the latest Visual Studio preview?

**Comment by javiercn** [comment]
@LukasKubicek does it work if you disable trimming?

**Comment by mkArtakMSFT** [comment]
Thanks for confirmation, @LukasKubicek. Could you also answer @javiercn's question above?

**Comment by javiercn** [comment]
@LukasKubicek thanks for the additional details.

Trimming the ASP.NET app is not supported for Blazor Web payloads, only the web assembly bits.

/cc @SteveSandersonMS in case I am missing something here.

**Comment by LukasKubicek** [comment]
Would it be posible for the dotnet publish process to detect this and produce some error or warning? I didn't really needed trimmed publish, it just seemed nicer to have smaller binary and I had no idea that it is the root of the problem.

**Comment by danmoseley** [comment]
@eerhardt  shouldn't this have warned?

**Comment by eerhardt** [comment]
> @eerhardt shouldn't this have warned?

Yes, it warns. Line 8 above calls this method, which is annotated:

https://github.com/dotnet/aspnetcore/blob/f84e43dc7a6156e63133f9c0346b58db9d62faf2/src/Components/Endpoints/src/DependencyInjection/RazorComponentsServiceCollectionExtensions.cs#L33-L34

**Comment by eerhardt** [comment]
Note that the recommendation is to put `PublishTrimmed` or `PublishAot` in the .csproj directly - not just in a publish profile.

https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#enable-trimming
