### ISSUE TITLE
Blazor add auto generated management screens for Application user role and claim Management pages

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#51503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I just love the new api login end points a great piece of work by the team.  

What a would Love to happen next is the abailty to manage the application user context roles claims and users of a site. 

### Describe the solution you'd like

When a user creates a blazor new project style web app. Have a checkbox to inclunde auth managment pages. 

This would give crud operations gui screens for 
application user plus all custom fields
roles
claims

Id possible if it detected the file TeannantId some way of management of multi teannant applications would be so cool. 

Auth and managment of auth has always been a pain since we lost websat

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
