### ISSUE TITLE
bool IDataProtector.TryUnprotect()

### ISSUE THREAD

**Issue by nquandt** [dotnet/aspnetcore#51508]
## Background and Motivation

Don't want to rely on catching exceptions as control flow. I am encrypting a string and giving to my user client side.. then later on it will come back to the server.. it is not sensitive data.. I just wanted a way of guaranteeing the string originally came from the server, and making sure in horizontal scaling using the ProtectWithKeyVault DataProtection I would be able to guarantee stateless servers.. i.e. any server can handle the value coming back.

If someone sends a bad string(i.e. malicious) Unprotect throws an error.. Catching errors as control flow is antipattern and non-performant in high load situations.

Any recommendations welcome 👍 

## Proposed API
```csharp
interface IDataProtector
{
    bool TryUnprotect(byte[] bytes, [NotNullWhen(true)] out string? result); 
}
```
## Usage Examples

```csharp
if (!_protector.TryUnprotect(bytes, out var result))
{
       //those bytes weren't protected with the protector.. possibly malicious or unintended
       return SomeInvalidResult();
}

//do other stuff
```

## Alternative Designs

Maybe I am using DataProtector for an unintended fashion and should reach for creating my own helper using RSA etc. 

## Risks

Might be alot of touchpoints..

**Comment by adityamandaleeka** [comment]
cc @amcasey

**Comment by amcasey** [comment]
> If someone sends a bad string(i.e. malicious) Unprotect throws an error.. Catching errors as control flow is antipattern and non-performant in high load situations.

But this is, in fact, exceptional, no?  Do you receive a lot of bad strings?

**Comment by nquandt** [comment]
@amcasey you're correct. After doing some more investigation, I believe my use case is outside the scope of the typical use of IDataProtector. Thanks for the comment!
