### ISSUE TITLE
DotNetDispatcher.cs(391,67): error IL2111: Method 'ScanTypeForCallableMethods(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection

### ISSUE THREAD

**Issue by londonjob** [dotnet/aspnetcore#51517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

build failure for dotnet run / build  @ aspnetcore\src\Components\Samples\BlazorServerApp

\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs(391,67): error IL2111: Method 'ScanTypeForCallableMethods(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Microsoft.JSInterop.csproj]

### Expected Behavior

build / run finishes without error

### Steps To Reproduce

run dotnet build for BlazorServerApp

### .NET Version

9.0.100-alpha.1.23519.21

**Comment by javiercn** [comment]
@londonjob thanks for contacting us.

There might be something missing on your environment. Make sure you follow the repo instructions [here](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md)
