### ISSUE TITLE
ClaimsPrincipal on ASP.NET Core v8.0.100-rc.2.23502.2 Doesn't Contain All Claims From The OpenIdConnect Token

### ISSUE THREAD

**Issue by smjxpro** [dotnet/aspnetcore#51538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an existing Blazor project which was in .NET 8 RC1. After upgrading to .NET 8 RC2, authentication and authorization using OIDC (Keycloak) isn't working as expected.

For example, on my **IClaimsTransformation** implementation I could access the **realm_access** property like this:
`        var realmAccessValue = principal.FindFirst("realm_access")?.Value;
`

Also, the **exp**, **email_verified** except for a few is missing on the **ClaimsPrincipal** object.

### Expected Behavior

The **ClaimsPrincipal** object should contain all the token claims.

### Steps To Reproduce

1. Create a new Blazor Web App project without interactivity
2. Add **Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.0-rc.2.23480.2**
3. Configure to use Keycloak or any other OIDC provider
4. Create and register an **IClaimsTransformation** implementation and register it in DI
5. On the _TransformAsync_ method try to access some values which is on the token (jwt.io). For example for Keycloak:  var realmAccessValue = principal.FindFirst("realm_access")?.Value;
6. The value is null

### .NET Version

8.0.100-rc.2.23502.2

**Comment by mschaefer-gresham** [comment]
I have a similar issue. The 'email' claim is not present when attempting to do a claims transformation after upgrading to 8.0.0-rc.2. 

`var email = principal.Claims.FirstOrDefault(c => c.Type == "email")?.Value;`

**Comment by miaooss** [comment]
I was able to make it work by reverting on <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0-rc.1.23421.29" />

But the rc2 8.0.0-rc.2.23480.2 has an issue with the token and now the Release version 8.0.0 since to have the issue as well.

**Comment by miaooss** [comment]
We found the Issue was on our TokenService

We use the identity server and for some reason, our jwt token had an array for the `iat` property

`IDX11020: The JSON value of type: 'StartArray', could not be converted to 'JsonTokenType.Number'. Reading: 'System.IdentityModel.Tokens.Jwt.JwtPayload.iat', Position: '246', CurrentDepth: '1', BytesConsumed: '247'.`

**Comment by josephdecock** [comment]
@miaooss, if necessary, you can also [open an IdentityServer issue](https://github.com/DuendeSoftware/Support/issues/new/choose).

**Comment by mschaefer-gresham** [comment]
@Tratcher any movement on this issue?

**Comment by mschaefer-gresham** [comment]
Are there any plans to address this soon?

**Comment by mayoatte** [comment]
Also facing this problem. Any alternatives or plans to fix?

PS. Happy new year, all!

**Comment by mschaefer-gresham** [comment]
I can confirm this is still an issue in SDK 8.0.101.

**Comment by mschaefer-gresham** [comment]
Because we can't upgrade to 8.0.101 we are now vulnerable to this risk: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/security/advisories/GHSA-8g9c-28fc-mcx2

Why is this issue still not being looked at?

**Comment by oluatte** [comment]
I was able to get the claims i needed (e.g. `exp`) thanks to this helpful [post](https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/).

// keep these claims from the id token when creating the claims identity
options.ClaimActions.Remove("iat");
options.ClaimActions.Remove("exp");

There are default claim actions to remove some of the more estoric claims. You can choose to remove the claim actions to allow those claims to be mapped.

**Comment by mschaefer-gresham** [comment]
Opened new issue [53842](https://github.com/dotnet/aspnetcore/issues/53842).

**Comment by mkArtakMSFT** [comment]
@jennyf19 it looks like there was a breaking change in the IdentityModel update we took for 8.0-rc2. Should this have been documented as a breaking change too in 8.0 or was it not intentional and you can revert that behavior on your end (in IdentityModel)?
It's surprising that the fix from 2017 (from blog post [mentioned earlier](https://github.com/dotnet/aspnetcore/issues/51538#issuecomment-1904670494)) worked.

**Comment by mkArtakMSFT** [comment]
To people who still experience problems here, please try the following:

```csharp
OpenIdConnectOptions.ClaimActions.Clear();
```

**Comment by mschaefer-gresham** [comment]
@mkArtakMSFT can you be more specific about where this should be called? For example. I'm encounter this problem inside TransformAsync in a IClaimsTransformation class. So when/where should this be called?

**Comment by mschaefer-gresham** [comment]
@mkArtakMSFT the email address claim is there, but the type is no longer "email". Now it's "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress".

<img width="861" alt="image" src="https://github.com/dotnet/aspnetcore/assets/94627216/ad8306b8-996f-45d3-b990-4e2fb798452b">

**Comment by mschaefer-gresham** [comment]
If I instead use the type above, then I can get things working:

```
var email = principal.Claims.FirstOrDefault(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")?.Value;
```

But what happened to the claim of type "email"?

**Comment by mschaefer-gresham** [comment]
@mkArtakMSFT Can someone please respond to this issue? It has been open for 5 months now with no resolution.
