### ISSUE TITLE
RequestDelegateGenerator "From" Attributes in AsParameters class produces compile error

### ISSUE THREAD

**Issue by Oskarsson** [dotnet/aspnetcore#51547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `FromRouteAttribute`, `FromQueryAttribute` and `FromHeaderAttribute` combined with `AsParametersAttribute` the generated code does not compile. This is because it will try and set the property using the `FromRouteAttribute.Name` instead of the property name inside the class.

Following the reproduction steps will end with the following code generated:

```C#
var headers_local = new global::ClassName { route = Route_local, header = Header_local, query = Query_local };
```

### Expected Behavior

It should generate the following code
```C#
var headers_local = new global::ClassName { Route = Route_local, Header = Header_local, Query = Query_local };
```

### Steps To Reproduce

```C#
var builder = WebApplication.CreateSlimBuilder(args);
var app = builder.Build();

app.Map("route", ([AsParameters] ClassName headers) => Results.Empty);
app.Run();

internal class ClassName
{
    [FromRoute(Name = "route")]
    public string? Route { get; set; }

    [FromHeader(Name = "header")]
    public string? Header { get; set; }

    [FromQuery(Name = "query")]
    public string? Query { get; set; }
}
```

### .NET Version

8.0.100-rc.2.23502.2

**Comment by Oskarsson** [comment]
Looks like

[`var parameterList = string.Join(", ", EndpointParameters.Select(p => $"{p.LookupName} = {p.EmitHandlerArgument()}"));`](https://github.com/dotnet/aspnetcore/blob/f23bd5ebe09b58f11df14675a9b550315b3d8c3d/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/EndpointParameter.cs#L174C134-L174C134) should be using `p.SymbolName` instead of `p.LookupName`

**Comment by captainsafia** [comment]
@Oskarsson Thanks for reporting this issue! I've opened a PR to fix it over at https://github.com/dotnet/aspnetcore/pull/51582
