### ISSUE TITLE
IEndpointAddressScheme (RouteValuesAddressScheme) FindEndpoints returns incorrect Endpoint in ASP.NET Core MVC (both 6 and 7)

### ISSUE THREAD

**Issue by yankarinRG** [dotnet/aspnetcore#51549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When utilizing `IEndpointAddressScheme` in ASP.NET Core MVC, there is a discrepancy between the expected and actual endpoints when explicitly defining a `RouteValuesAddress`. The `IEndpointAddressScheme` is returning an endpoint that does not match the expected endpoint, even though the defined route values should result in a specific endpoint

### Expected Behavior

When using `IEndpointAddressScheme` in an ASP.NET Core MVC application, and explicitly defining a `RouteValuesAddress` with specific route values, the expected outcome is that `IEndpointAddressScheme` should correctly resolve the endpoint associated with those explicit route values.

In the provided code, the explicit route values are set as follows:

> "controller" = "Home"
> "action" = "Privacy"

The expected behavior is that `IEndpointAddressScheme` should return an endpoint that matches the specified "controller" and "action" values, and this endpoint should be consistent with what is obtained from `EndpointDataSource`.

### Steps To Reproduce

1. Create a new ASP.NET Core MVC web application using either .NET 6 or .NET 7, leaving all default settings intact.
2. In the newly created application, navigate to the `HomeController` class.
3. Modify the `Index` action method of the `HomeController` as follows:
```
public IActionResult Index()
{
    var routeData = new RouteValueDictionary(new Dictionary<string, string?>
    {
        { "controller", "Home" },
        { "action", "Privacy" }
    });
    var address = new RouteValuesAddress
    {
        ExplicitValues = routeData
    };
    var addressingScheme = HttpContext.RequestServices.GetRequiredService<IEndpointAddressScheme<RouteValuesAddress>>();
    var endpoint = addressingScheme.FindEndpoints(address).Single();

    var endpoints = HttpContext.RequestServices.GetRequiredService<EndpointDataSource>();
    var expectedEndpoint = endpoints.Endpoints.Single(e =>
    {
        var descriptor = e.Metadata.GetMetadata<ControllerActionDescriptor>();
        return descriptor?.ControllerName == "Home" && descriptor!.ActionName == "Privacy";
    });

    return View();
}
```

4. Run the application.
5. Manually inspect "endpoint" and "expectedEndpoint" and notice how the found endpoint is not the one we expected.

### .NET Version

7.0.402

### Anything else?

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.7.5

> .NET SDK:
>  Version:   7.0.402
>  Commit:    791db8e2d8
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22621
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\7.0.402\
> 
> Host:
>   Version:      7.0.12
>   Architecture: x64
>   Commit:       4a824ef37c
> 
> .NET SDKs installed:
>   3.1.426 [C:\Program Files\dotnet\sdk]
>   7.0.402 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found

**Comment by captainsafia** [comment]
@yankarinRG Thanks for filing this issue! Apologies for the delay as we work through the triage backlog. It's not clear if you're still running into the issue but I'll post the response here in case it is helpful to someone in the future.

The behavior that you are seeing here is expected based on the behavior of the router in ASP.NET Core.

The `expectedEndpoint` that you resolve by querying the `EndpointDataSource` directly above represents the `ActionEndpoint` that is generated for each controller action in the application. By default, these endpoints are "hidden" from the router implementation because they are annotated with the `ISuppressLinkGenerationMetadata` ([ref](https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/Routing/ActionEndpointFactory.cs,439)). When the router runs, the endpoint it matches against is the top-level endpoint generated by the call to `MapControllerRoute`.
