### ISSUE TITLE
An unhandled exception occurred while processing the request. AmbiguousMatchException: The request matched multiple endpoints. Matches:  FreelanceFusion.Controllers.PostJobController.CreateJob (FreelanceFusion) FreelanceFusion.Controllers.PostJobController.CreateJob (FreelanceFusion) FreelanceFusion.Controllers.PostJobController.CreateJob (FreelanceFusion) FreelanceFusion.Controllers.PostJobController.CreateJob (FreelanceFusion) FreelanceFusion.Controllers.PostJobController.CreateJob (FreelanceFusion)

### ISSUE THREAD

**Issue by lordbinary11** [dotnet/aspnetcore#51542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FreelanceFusion.Models;
using FreelanceFusion.Services;
using System.Data.SqlClient;

namespace FreelanceFusion.Controllers;

public class PostJobController : Controller
{
    
    private readonly CategoryService _categoryService;

    public PostJobController(CategoryService categoryService)
    {
        
        _categoryService = categoryService;
    }

    public IActionResult PostJob()
    {
         List<Category> categories = _categoryService.GetCategories(); // Assuming GetCategories returns a list of Category objects
            ViewBag.Categories = categories; // Pass the categories to the view
            return View();
        
    }

    public IActionResult CreateJob(Job j, string[] skills)
{
    using (var connection = new SqlConnection("Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True"))
    {
        connection.Open();

        // Insert the job into the Job table
        var command = new SqlCommand("INSERT INTO Job (Title, Budget,Deadline, Description, CategoryID) VALUES (@Title, @Budget, @Deadline, @Description, @CategoryID)", connection);
        command.Parameters.AddWithValue("@Title", j.Title);
        command.Parameters.AddWithValue("@Budget", j.Budget);
        command.Parameters.AddWithValue("@Deadline", j.Deadline);
        command.Parameters.AddWithValue("@Description", j.Description);
        command.Parameters.AddWithValue("@CategoryID", j.CategoryID);
        command.ExecuteNonQuery();

        // Fetch the JobID of the newly inserted job
        command = new SqlCommand("SELECT JobID('Job')", connection);
        var fetchedJobID = Convert.ToInt32(command.ExecuteScalar());

        // Insert each skill into the SkillRequired table with the fetched JobID
        foreach (var skill in skills)
        {
            command = new SqlCommand("INSERT INTO JobSkills (JobID,Skill) VALUES (@JobID, @Skill)", connection);
            command.Parameters.AddWithValue("@JobID", fetchedJobID);
            command.Parameters.AddWithValue("@Skill", skill);
            command.ExecuteNonQuery();
        }
    }

    // Redirect to a success page or perform other operations
    return RedirectToAction("Index");
}

   

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

**Comment by mkArtakMSFT** [comment]
Please provide details about your scenario as well as the problem you're facing. Include details like when the error occurs, ...
Also, the DB related logic shouldn't be relevant here. So please simplify your repo to only include the minimum code required to reproduce the issue.

**Comment by feiyun0112** [comment]
There are two controllers with the same name but different namespaces. 
`FreelanceFusion.Controllers.PostJobController`

`FreelanceFusion.Controllers.PostJobControllers.PostJobController`


Search the entire solution for PostJobController
