### ISSUE TITLE
Provide a loadBootResource code example working with Brotoli and taking into account correctly the environment!

### ISSUE THREAD

**Issue by GFlisch** [dotnet/aspnetcore#51552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a K8s pod hosting a Blazor WebAssembly (static file) with a nginx image.
The nginx conf file add a header with the correct Blazor-Environment to use.

When using Blazor WebAssebly and the Brotli compression with Static file, the code provided in the learn page https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0 doesn't take correctly the Blazor-Environment header used to define the environment.

The problem is linked to this code provided in the doc:

<script type="module">
  import { BrotliDecode } from './decode.min.js';
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      if (type !== 'dotnetjs' && location.hostname !== 'localhost' && type !== 'configuration') {
        return (async function () {
          const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });
          if (!response.ok) {
            throw new Error(response.statusText);
          }
          const originalResponseBuffer = await response.arrayBuffer();
          const originalResponseArray = new Int8Array(originalResponseBuffer);
          const decompressedResponseArray = BrotliDecode(originalResponseArray);
          const contentType = type === 
            'dotnetwasm' ? 'application/wasm' : 'application/octet-stream';
          return new Response(decompressedResponseArray, 
            { headers: { 'content-type': contentType } });
        })();
      }
    }
  });
</script>

The script returns the decompressed response with the header but do not set the Blazor-Environment returned from the backend.
Then the applicationsettings.Production.json file is requested whatever environment is...

To work around this I have added in the code the check of the file name blazor.boot.json. By skipping this one the brotli version of the file is not requested and the correct environment is used.

### Expected Behavior

By adding the check on the name of blazor.boot.json file everything is workin well but may be there is a better way to do this!

This is the code I use:

    <script type="module">
        import { BrotliDecode } from './decode.min.js';
        Blazor.start({
            loadBootResource: function (type, name, defaultUri, integrity) {
                if (type !== 'dotnetjs' && location.hostname !== 'localhost' && type !== 'configuration' && name !== 'blazor.boot.json') {
                    return (async function () {
                        const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });
                        if (!response.ok) {
                            throw new Error(response.statusText);
                        }
                        const originalResponseBuffer = await response.arrayBuffer();
                        const originalResponseArray = new Int8Array(originalResponseBuffer);
                        const decompressedResponseArray = BrotliDecode(originalResponseArray);
                        const contentType = type ===
                            'dotnetwasm' ? 'application/wasm' : 'application/octet-stream';
                        return new Response(decompressedResponseArray,
                            { headers: { 'content-type': contentType } });
                    })();
                }
            }
        });
    </script>****

### Steps To Reproduce

Setup a blazor webassembly project.
Publish (Release).
deploy it in a nginz container with the correct  environment header:         add_header Blazor-Environment "%%Environment%%";
In the index html page set the autostart to false and add the standard brotli script provided by the learn page: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0.

The appsettings.Production.json file will be requested even if the environment is set to Staging....

### .NET Version

7, 8

**Comment by MackinnonBuck** [comment]
Thanks for the issue report, @GFlisch!

We should probably update the docs to include a check for `type !== 'manifest'`.

**Comment by MackinnonBuck** [comment]
Completed in https://github.com/dotnet/AspNetCore.Docs/pull/30867
