### ISSUE TITLE
[Blazor web] Introduction article, explanation, and updated view of the app models

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#51569]
We need an introduction that explains what Blazor web is, that focuses on static server-side rendering and that mentions Blazor hybrid and server/webassembly as options to add interactivity, but that doesn't put them in opposing sides as things you need to make a choice between.

**Comment by mkArtakMSFT** [comment]
Thank you for your patience.
Given the number of issues that we have to deal with, we're aggressively closing those that we haven't been able to get to in a reasonable time. This will help us focus on the issues which are more impactful.
