### ISSUE TITLE
[Blazor] Tutorial for Blazor web that introduces the main framework features without going in depth

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#51570]
Similar to https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio but with a focus on core features.
* Rendering pages
* Streaming rendering
* Enhanced navigation
* Form handling
* Validation
* Model binding
* Interactivity

**Comment by danroth27** [comment]
We have content in progress for Microsoft Learn for Blazor that should cover this.
