### ISSUE TITLE
[Blazor] Enhanced navigation in depth doc

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#51573]
* Cover how enhanced navigation works
* Describe important aspects of it
  * Interactions with form handling.
  * Disabling it on a given link.
  * Preserving content across pages.

**Comment by mkArtakMSFT** [comment]
Thank you for your patience.
Given the number of issues that we have to deal with, we're aggressively closing those that we haven't been able to get to in a reasonable time. This will help us focus on the issues which are more impactful.
