### ISSUE TITLE
[Blazor] Form validation

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#51575]
* This might be a pointer to the general Blazor validation docs + some specific server-side topics.

**Comment by pratt33k** [comment]
@javiercn Not sure if this is the right place to ask this but I've a Blazor server project with a Dapper connection to SQL Server, I want to check if a field in my form (using EditForm and DataAnnotations validation) is unique or not.

 - So, I guess I'll have to do some custom validation (attribute or component), I was thinking a validator component would be best in this case but I'm a bit confused for a Blazor server project (without an API), would it be recommended to do such a validation (unique field) using the example similar to [Business logic validation with a validator component ](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-8.0#business-logic-validation-with-a-validator-component) or [Server validation with a validator component](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-8.0#server-validation-with-a-validator-component) 
  
Provided I want to keep doing the Data Annotations validation for common things like required, regex, etc. when the user tabs out but also add this unique field check when the user submits the form (on other successful validation)

**Comment by mkArtakMSFT** [comment]
Thank you for your patience.
Given the number of issues that we have to deal with, we're aggressively closing those that we haven't been able to get to in a reasonable time. This will help us focus on the issues which are more impactful.
