### ISSUE TITLE
Navigation in Interactive Server Components is broken unless Routes are Server Interactive

### ISSUE THREAD

**Issue by mythz** [dotnet/aspnetcore#51594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're trying to find out what's the best way to support our existing [AutoQueryGrid](https://blazor-gallery.jamstacks.net/gallery/autoquerygrid) component in .NET 8 RC2 which currently works as-is in both of .NET 6's Blazor WASM and Blazor Server Interactive modes.

Unfortunately Navigation behavior is broken in .NET 8's default server rendering mode where it doesn't seem possible for InteractiveServer components to be able to preserve its existing behavior of being able to navigate to itself whilst preserving component state even when pages and the component itself are marked to use `[RenderModeInteractiveServer]`.

To test the current behavior I've added a `NavTest.razor` page and a `LogNavigation.razor` to a RC2 `new blazor -au Individual` template. This is also available as a GitHub project at [BlazorNavTest](https://github.com/mythz/BlazorNavTest).

The `NavTest.razor` Page is annotated to render as a InteractiveServer page and just includes a `<LogNavigation>` component:

```csharp
@page "/navtest"
@using MyApp.Components.Test
@attribute [RenderModeInteractiveServer]

<PageTitle>Navigation Test</PageTitle>

<h1>Navigation Test</h1>

<LogNavigation />
```

Which contains several different ways a component can navigate:

//LogNavigation.razor
```csharp
@attribute [RenderModeInteractiveServer]
@using Microsoft.AspNetCore.WebUtilities

<h2>Log Navigation #@Id</h2>

<h3>Links</h3>

<a href="navtest?id=@(Id-1)">prev</a>
<a href="navtest?id=@(Id+1)">next</a>

<h3>NavigateTo</h3>

<button @onclick="() => NavigateTo(Id-1, forceLoad:false)">prev</button>
<button @onclick="() => NavigateTo(Id+1, forceLoad:false)">next</button>

<h3>NavLink</h3>

<NavLink href="@($"navtest?id={Id-1}")">prev</NavLink>
<NavLink href="@($"navtest?id={Id+1}")">next</NavLink>

<hr/>

<h2>Full Page Reloads</h2>

<h3>Links without Enhanced Navigation</h3>

<a href="navtest?id=@(Id-1)" data-enhance-nav="false">prev</a>
<a href="navtest?id=@(Id+1)" data-enhance-nav="false">next</a>

<h3>NavigateTo forceLoad</h3>

<button @onclick="() => NavigateTo(Id-1, forceLoad:true)">prev</button>
<button @onclick="() => NavigateTo(Id+1, forceLoad:true)">next</button>

@code {
    [Inject] ILogger<LogNavigation> Log { get; set; }
    [Inject] public NavigationManager NavigationManager { get; set; }

    private int Id { get; set; }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        Log.LogInformation("OnInitializedAsync: {Uri}", NavigationManager.Uri);
        NavigationManager.LocationChanged += HandleLocationChanged;
    }

    private void HandleLocationChanged(object? sender, LocationChangedEventArgs e)
    {
        Log.LogInformation("HandleLocationChanged: {Location}, Uri= {Uri}", e.Location, NavigationManager.Uri);
        base.InvokeAsync(async () =>
        {
            await OnParametersSetAsync();
        });
    }

    protected override async Task OnParametersSetAsync()
    {
        await base.OnParametersSetAsync();

        Id = QueryHelpers.ParseQuery(new Uri(NavigationManager.Uri).Query).TryGetValue("id", out var id)
            ? int.Parse(id!)
            : 0;

        Log.LogInformation("OnParametersSetAsync: {Uri}, Id={Id}", NavigationManager.Uri, Id);
        StateHasChanged();
    }

    private void NavigateTo(int id, bool forceLoad)
    {
        NavigationManager.NavigateTo($"navtest?id={id}", forceLoad);
    }

    public void Dispose()
    {
        NavigationManager.LocationChanged -= HandleLocationChanged;
    }
}
```

### Default Navigation Behavior

There doesn't appear to be anyway to preserve the existing InteractiveServer Blazor Routing where you can simply navigate with a different queryString and update the component state (i.e `Id`) without doing a full page reload. Also none of these links ever fire the `NavigationManager.LocationChanged` event.

Clicking on **next** link does change the URL and reruns `OnInitializedAsync` and `OnParametersSetAsync` with the new URL:

```csharp
info: MyApp.Components.Test.LogNavigation[0]
      OnInitializedAsync: https://localhost:7185/navtest?id=1
info: MyApp.Components.Test.LogNavigation[0]
      OnParametersSetAsync: https://localhost:7185/navtest?id=1, Id=1
```

However the template doesn't rerender with the updated `Id` so the rendered template doesn't show the updated `Id` and the prev/next links won't work.

### Full Page Behavior

The only way the UI changes to include the updated `Id` is when using the Full Page Reload links, which isn't viable for every navigation in a Interactive Server component to perform a full page reload. Also unexpected is when you click on the sidebar `<NavMenu href="navtest">` and the URL changes back to `/navtest` is that the component still only renders the last full page reloaded state.

### Using Interactive Server `<Routes>`

The only way I've found to preserve the existing InteractiveServer behavior is by changing `Routes.razor` to also be marked as InteractiveServer:

```html
@attribute [RenderModeInteractiveServer]
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
</Router>
```

Where now the `HandleLocationChanged` event callback fires, the state is updated and the template is rendered with the updated state.

But now this breaks most of the template where clicking on most Auth Pages fails with an exception, you can get past it by going directly to the URL and doing a full page reload but then linking to the next Identity Auth page fails.

### What's the solution?

Firstly is this expected behavior or a known issue? as I don't see how the current behavior of including InteractiveServer components in the default Blazor template (with default routing) is possible, since the behavior is unreliable and unpredictable.

Is the only solution to update `Routes.razor` to use InteractiveServer as well? If it is, will the rest of the template be updated to support InteractiveServer Routes as doing this breaks Auth pages in the latest RC2 template.

Ideally we'd like to just specify which pages require InteractiveServer components with  `@attribute [RenderModeInteractiveServer]` or `@rendermode RenderMode.InteractiveServer` and retain the existing InteractiveServer behavior where a component can navigate without full page reloads and rely on `NavigationManager.LocationChanged` to detect URL changes.

### Expected Behavior

Be able to navigate from a InteractiveServer component without doing full page reloads whilst preserving and rendering active state.

### Steps To Reproduce

```bash
$ dotnet new blazor -au Individual
```

Add `NavTest.razor` Razor Page and `LogNavigation.razor` component

Or clone from https://github.com/mythz/BlazorNavTest

### .NET Version

8.0.100-rc.2.23502.2

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @mythz.

Could you please try the latest 8.0 RTM build from [this table](https://github.com/dotnet/installer#table) and see if it fixes the problems you're experiencing? It might specifically address the issues you encountered around `LocationChanged` not firing and the interactive `<Routes>` component causing issues with authentication pages.

**Comment by mythz** [comment]
@MackinnonBuck Thanks for your response. 

I can confirm that upgrading to `8.0.200-preview.23524.7` does resolve this issue and that I only needed to annotate the [NavTest.razor](https://github.com/mythz/BlazorNavTest/blob/main/Components/Pages/NavTest.razor) page to use InteractiveServer for the `<LogNavigation />` component to work as expected where all the non full-reload links are now raising the `LocationChanged` event and the component to be rendered with the active state.

```csharp
@page "/navtest"
@using MyApp.Components.Test
@rendermode RenderMode.InteractiveServer

<PageTitle>Navigation Test</PageTitle>

<h1>Navigation Test</h1>

<LogNavigation />
```
