### ISSUE TITLE
Enable Cors not working as expected

### ISSUE THREAD

**Issue by quintonn** [dotnet/aspnetcore#51599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am testing and playing around with Cors in my .NET 7 app and I'm noticing some strange behaviour.

I am trying to enable/disable specific CORS policies for specific Controllers and routes, but it's not working.

I've created a minimal program where I'm trying to register both a default cors policy and a specific one for my main controller.
Then I'm trying to prevent the GET http method.
This is just a test, in my original app I was trying to stop POST requests, but the same applies.

I'm also seeing some differences between when I use `services.AddMvc()` vs `services.AddMvcCore()`, which is to be expected, but on the CORS part I was a bit surprised. 
This could mean there are some undocumented steps to get CORS working correctly?

### Expected Behavior

I expect to see the request failing with an error relating to the access control allowed methods not allowing GET

### Steps To Reproduce

The following is my web app:

```C-sharp
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;

var builder = new WebHostBuilder();

builder.UseKestrel();

builder.UseStartup<Startup>();
builder.Build().Run();


public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        // This is needed if hosting on Linux environment such as azure
        services.AddLogging(x =>
        {
            x.AddConsole();
            x.AddDebug();

        });

        services.AddCors(o =>
        {
            o.AddPolicy("Default", builder =>
            {
                builder.AllowAnyOrigin()
                       .AllowAnyMethod()
                       .AllowAnyHeader();
            });

            o.AddPolicy("Test", builder =>
            {
                builder.WithOrigins("http://localhost:63380")
                       .AllowAnyHeader()
                       .WithMethods("PUT", "OPTIONS"); // GET is still working?
            });
        });

        // Doesn't work
        //services.AddMvcCore(x =>
        //{
        //    x.EnableEndpointRouting = false;
        //});
        services.AddMvc(x =>
        {
            x.EnableEndpointRouting = false;
        });


    }

    public void Configure(IApplicationBuilder app, IServiceProvider serviceProvider, ILoggerFactory logFactory)
    {
        //app.UseCors("Default"); // if I have this, the [EnableCors] attribute doesn't seem to work
        //app.UseCors("Test");

        app.UseMvc();
    }
}

[Route("api")]
[EnableCors("Test")]
public class TestController : ControllerBase
{
    [HttpGet]
    [Route("test")]
    [EnableCors("Test")]
    public async Task<IActionResult> Test()
    {
        var result = new
        {
            Success = true,
            Message = "well done, it works"
        };
        return new JsonResult(result);
    }
}
```

If I create a web page and try and call `http://localhost:5073/api/test`, I am expecting it to fail because of CORS not allowing it, but currently it's succeeding.

### .NET Version

7.0.402

**Comment by quintonn** [comment]
Originally posted to the dotnet runtime: https://github.com/dotnet/runtime/issues/93910

**Comment by BrennanConroy** [comment]
The browser doesn't send CORS requests for every http request if they meet certain conditions:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests
Double check that the browser is actually sending an OPTIONS request which would indicate it's using CORS.

**Comment by quintonn** [comment]
@BrennanConroy thanks, this is interesting. I think my requests are "simple". I'll do more testing.
