### ISSUE TITLE
I was displaying a bunch large text files inside blazor, this's what's happened

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#51597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was reading a bunch large text files inside browser, this's what's happened

![image](https://github.com/dotnet/aspnetcore/assets/35312807/69ffe44c-81d4-4af6-9f13-3812a4e738d5)

Files are ranging from 5KB to 300KB, got 50 of those for starter wanted to see if I can show these string
I created elements simply by using ```@FileString``` inside div
I am using Visual Studio Version 17.8.0 Preview 4.0

### Expected Behavior

I can display a website today with 10MB plaintext in browser, there is no reason I can't do it in blazor, it should do what's capable in the browser

**Comment by Xyncgas** [comment]
For me Visual Studio debugger didn't say anything

**Comment by Xyncgas** [comment]
https://github.com/dotnet/corefx/pull/40796

**Comment by Xyncgas** [comment]
Well, I am guessing there is reason for a size limit, blazor is for displaying the web though, so if you are visiting anything on the web that has a lot of text I guess it's not going to show anything

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

From what I can tell the limit is 125MB, which means that:
1) It's very hard to hit on regular use cases.
2) It's not clear you would get good peformance out of it.

In the end, this has to do with the serialization mechanism used by webview, and unfortunately, this is not something we have much control over, since the options to communicate between webview and host are pretty limited.

**Comment by gragra33** [comment]
@Xyncgas Are you trying to work with large JSON files? If yes, I have a solution.

**Comment by mkArtakMSFT** [comment]
Looks like this is due to a limitation in the serialization stack. There is an existing issue asking for increasing that limit: https://github.com/dotnet/runtime/issues/61089

**Comment by gragra33** [comment]
Here is my solution to overcome this issue: [BlazorJsonStreamingSample](https://github.com/gragra33/BlazorJsonStreamingSample)
