### ISSUE TITLE
Problems configuring Kestrel in IIS

### ISSUE THREAD

**Issue by gktval** [dotnet/aspnetcore#51608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have previously been hosting a GRPC service using Kestrel in IIS. Last week, the server hosting the service completed a Windows update and I can no longer get the GRPC service to work in IIS. I can get it to work if hosted outside of IIS. 

From the client, I receive a "Bad gRPC response. HTTP status code: 400". In the server itself, the logs show that the service starts and is listening on 192.168.1.30:5001. But there are no further errors when the user tries to connect.

A further difference I see in the stdout logs is that Microsoft.Hosting.Lifetime now shows it is listening on a random port:
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://127.0.0.1:31835
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
```

Last week, when the service was working, stdout did not show it listened on any port:
```
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
```

Running from command prompt outside of IIS (where the service is working). It shows that Microsoft.Hosting.Lifetime is listening on port 5001 instead of a random port.
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://127.0.0.1:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://192.168.1.30:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
```

Not sure if that is something new with the update or what changed.

Here is my code in .Net 7 project from hosting Kestrel.
```
string port = 5001;

builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(IPAddress.Loopback, port, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http2;
        listenOptions.UseConnectionLogging();
        listenOptions.UseHttps(certFile, password);
    }); 
});

builder.WebHost.UseIISIntegration();
```

Is there a way I can log why the client is now receiving a 400 error? Or a way to further diagnose the problem?

### Expected Behavior

Client should be connecting to the GRPC service in IIS.

### .NET Version

7.0.203

**Comment by Tratcher** [comment]
This is confusing, it sounds like you're using IIS in it's out-of-process mode, but that never supported end-to-end HTTP/2 / gRPC.

> Last week, when the service was working, stdout did not show it listened on any port:

This implies you were using IIS in-process and not using kestrel at all. I suggest removing kestrel from your app, replace UseIISIntegration with UseIIS (or CreateDefaultBuilder...). Also check your web.config to make sure in-process is specified.

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-7.0

**Comment by gktval** [comment]
@Tratcher Thank you. You were right. The web config had been changed to outofprocess. Changing it back to inprocess, gives a "Bad gRPC response. HTTP status code: 500" in the client.

**Comment by Tratcher** [comment]
That's a question for the logs.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-7.0

**Comment by gktval** [comment]
Appreciate your help. The app was in x86 instead of x64. Seems to be working now.
