### ISSUE TITLE
AddRoles to a Blazor 8 app throws System.AggregateException

### ISSUE THREAD

**Issue by DWhiteR1** [dotnet/aspnetcore#51638]
Hi.
In trying to add roles to my Blazor app.

```
builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddSignInManager()
    .AddRoles<IdentityRole>()
    .AddDefaultTokenProviders();`
```
    
I added  `.AddRoles<IdentityRole>()` to the "Out of the box" template "dotnet new blazor -au Individual"
    
Exception thrown: 'System.AggregateException' in Microsoft.Extensions.DependencyInjection.dll
    
Am I missing something...
    
Regards,
Dean

**Comment by geraldmaale** [comment]
I have spent several hours going through documentation and devblogs to find possible solution this issue but to no success. What could be missing? 
Creating an out of the box project for blazor with the following details `(.NET 8.0.100-rc.2):`

`dotnet new blazor -int auto -au individual -o IdentityDemo`.

Application runs without any issues until I throw in roles with any of these configurations.

- `builder.Services.AddIdentity<ApplicationUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = true)
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddSignInManager()
            .AddDefaultTokenProviders()
            .AddRoles<IdentityRole>();`


- `builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddSignInManager()
            .AddDefaultTokenProviders()
            .AddRoles<IdentityRole>();`

None of the above configuration works. 
Any directions to resolve this would be appreciated.

**Comment by bcheung4589** [comment]
I can manage users and roles without any issues in my Blazor 8.0.100-rc.2 app.

`
builder.Services.AddCascadingAuthenticationState();
builder.Services.AddScoped<UserAccessor>();
builder.Services.AddScoped<IdentityRedirectManager>();
builder.Services.AddScoped<AuthenticationStateProvider, PersistingRevalidatingAuthenticationStateProvider>();

builder.Services.AddAuthentication(IdentityConstants.ApplicationScheme)
    .AddIdentityCookies();

builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedEmail = true)
    .AddRoles<ApplicationRole>()
    .AddSignInManager()
    .AddDefaultTokenProviders()
    .AddEntityFrameworkStores<DbContext>();
`

**Comment by DWhiteR1** [comment]
Oh my...
Thank you, works as expected. :-)
