### ISSUE TITLE
Error Form Submission in asp.net Core MVC

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#51644]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-Form-Submission-in-aspnet-Core-MV/10489161)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Preview]
On Form Submit using MVC C#, form does not submit to the view but keeps forwarding to controller name and displays: "errors 403, error 404 or display error text on web."
Form Submission used for previous versions than preview 3 and preview 2 was this:
 <form method="post" action="Send" enctype="multipart/form-data">
    @using (Html.BeginForm("Sent", "Home", FormMethod.Post))
And form attributes on preview 2 and preview 3 does not trigger the method used, meanwhile, ModelState.IsValid = true but always return false.
in preview 2 and preview 3, I managed to edit the previously developed project and returned errors while they are published and return true if ModelState is valid.

Also tried to downgrade to preview 2 but issue kept the same. As well as used the for attributes as below:
<form method="post" action="Send">
<form method="post" action="Home/Send">
<form method="post" asp-action="Send" asp-controller="Home">
<input type="submit" asp-action="Send">
All attributes do not work in preview 2 and preview 3 updates. Worked fine on previous updates.
For Controller tried both ways:
[RequireHttps]
[HttpPost]
Used ActionResult and IActionResult
as well as the View page 
[RequireHttps]
[HttpGet]
Model properties tried to set as nullable values and next time not nullable and are required.
and Condition used: if ModelState.IsValid RedirectToAction("Sent") or return View("Sent")
Error Result: in URL "https://localhost:7189/Send"
Using Visual Studio 2022
.Net 7
Faced issues on Version: Preview 3 and Preview 2
Program.cs : route is defined as default
View Page name: Sent

---
#### Feedback Bot on 10/11/2023, 01:43 AM: 

(private comment, text removed)
#### Feedback Bot on 10/11/2023, 07:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by EngSabri** [comment]
Here is the minimal repro project named "Micro".
[appsettings.Development.json](https://github.com/dotnet/aspnetcore/files/13226127/appsettings.Development.json)
[appsettings.json](https://github.com/dotnet/aspnetcore/files/13226128/appsettings.json)
[Micro.deps.json](https://github.com/dotnet/aspnetcore/files/13226129/Micro.deps.json)
[Micro.runtimeconfig.json](https://github.com/dotnet/aspnetcore/files/13226130/Micro.runtimeconfig.json)

**Comment by mkArtakMSFT** [comment]
@EngSabri the links to json files you've linked in your comment are not a repro. Please provide a complete minimal repro project following guidance provided [here](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md).
