### ISSUE TITLE
app.UsePathBase(pathBase) add support to read pathbase from request header to handle multitenant application

### ISSUE THREAD

**Issue by kashifkr** [dotnet/aspnetcore#51669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a multi-tenant application and i would like to set the base path from the request header passed from NGINX, 

### Describe the solution you'd like

something like below
app.UsePathBase(headerKey,Option.ReadFromRequestHeader);

I have one application and being used by multiple tennats i.e
www.myapp.com/client1 (set base path to client1)
www.myapp.com/client2  (set base path to client2)

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/pull/49249 added a solution for this in 8.0-rc1. Give it a try.
