### ISSUE TITLE
Microsoft.Extensions.ApiDescription.Client.targets on Microsoft.Extensions.ApiDescription.Client NuGet package has invalid XML

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspnetcore#51675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to build for multi-targeting, `src/Tools/Extensions.ApiDescription.Client/src/buildMultiTargeting/Microsoft.Extensions.ApiDescription.Client.targets` is used and contains an error at [line  18]:

```xml
      Condition=" ''$(OpenApiGenerateCodeOnBuild)' == 'true' "
```

that causes:

```
`...\.nuget\packages\microsoft.extensions.apidescription.client\6.0.24\buildMultiTargeting\Microsoft.Extensions.ApiDescription.Client.targets(18,7): error MSB4092: An unexpected token "$(OpenApiGenerateCodeOnBuild)" was found at character position 4 in condition " ''$(OpenApiGenerateCodeOnBuild)' == 'true' ".`
```

### Expected Behavior

No syntax errors in published artifacts.

### Steps To Reproduce

Create a project multi-targeting more than one TFM and reference package `Microsoft.Extensions.ApiDescription.Client`.

### Exceptions (if any)

```
`...\.nuget\packages\microsoft.extensions.apidescription.client\6.0.24\buildMultiTargeting\Microsoft.Extensions.ApiDescription.Client.targets(18,7): error MSB4092: An unexpected token "$(OpenApiGenerateCodeOnBuild)" was found at character position 4 in condition " ''$(OpenApiGenerateCodeOnBuild)' == 'true' ".`
```

### .NET Version

Any version of the package I've looked at.

**Comment by martincostello** [comment]
Would you like to submit a PR to fix it? Looks like it's a one-liner to remove the extra `'` on line 18 here:

https://github.com/dotnet/aspnetcore/blob/6c1b3dfb66a1b66cc32ee26bbc23f6472f1dc985/src/Tools/Extensions.ApiDescription.Client/src/buildMultiTargeting/Microsoft.Extensions.ApiDescription.Client.targets#L18

**Comment by paulomorgado** [comment]
> Would you like to submit a PR to fix it? Looks like it's a one-liner to remove the extra `'` on line 18 here:
> 
> https://github.com/dotnet/aspnetcore/blob/6c1b3dfb66a1b66cc32ee26bbc23f6472f1dc985/src/Tools/Extensions.ApiDescription.Client/src/buildMultiTargeting/Microsoft.Extensions.ApiDescription.Client.targets#L18

Done! https://github.com/dotnet/aspnetcore/pull/51685
