### ISSUE TITLE
In .NET 8 Blazor Web App, FontAwsome icons not displayed when navigating to a page

### ISSUE THREAD

**Issue by GerardFR** [dotnet/aspnetcore#51696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FontAwesome icons are not displayed when navigating to a page.

### Expected Behavior

Icons should be displayed, as is the case with the .NET 7 version.

### Steps To Reproduce

Using Visual Studio Community 2022 Preview v 17.8.0 5.0:

- Create new Blazor Web App project keeping all default options (I tried different interactivity modes, same issue).
- In the App.razor file add a line in the <head> section (XXXXXXXXX is the FontAwesome free kit id):
`<script src="https://kit.fontawesome.com/XXXXXXXXX.js" crossorigin="anonymous"></script>`
- In the NavMenu.razor file or the Counter.razor file, add an icon:
`<i class="fa-solid fa-house"></i>`
- Run the application

When the page is initialy displayed or the whole page is refreshed (F5), the icon is displayed.
But when you navigate to a new page, using a nav item for example, FontAwesome icons are not displayed.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by SteveSandersonMS** [comment]
Looking at the [docs for Font Awesome](https://fontawesome.com/v5/docs/apis/javascript/get-started), it seems like there are two different JS files you can use, and only one of them deals with automatically replacing `<i>` with icons during dynamic page updates:

![image](https://github.com/dotnet/aspnetcore/assets/1101362/99b66290-da90-467b-9c6c-0442c4615ebd)

In .NET 8, Blazor has enhanced navigation enabled by default, so your navigations are dynamic page updates. So the fix would be one of the following:

 * You can use the version of the Font Awesome JS library that works with dynamic page updates
 * Or you can disable Blazor's enhanced navigation globally by putting `data-enhance-nav="false"` on your `<html>` or `<body>` element

**Comment by SteveSandersonMS** [comment]
> Icons should be displayed, as is the case with the .NET 7 version.

I think it would be the same in .NET 7 too, if you use either Blazor Server or Blazor WebAssembly.
