### ISSUE TITLE
get InvalidCastException when I use [Inject]IAccessTokenProvider

### ISSUE THREAD

**Issue by MichaelYuAlreadyExists** [dotnet/aspnetcore#51699]
I have a Blazor project.I'm trying to distribute it two ways: as WASM and Blazor server. So in the WASM code, I tried to be compatible with both. This is the code where I found the problem. My version is AspNet core 7.

` [Inject]
 public required IAccessTokenProvider TokenProvider { get; set; }
`

It works fine with Blazor WASM. But when I try to run it as Blazor server, I get an exception.

**_InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider' to type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider'._**

This means that Blazor server injected a ServerAuthenticationStateProvider into this property.According to the documentation below, this class is for server-side Blazor.
[https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.serverauthenticationstateprovider?view=aspnetcore-7.0](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.serverauthenticationstateprovider?view=aspnetcore-7.0)
Since it cannot be converted to an instance of IAccessTokenProvider, how should I handle this error that occurs during IAccessTokenProvider injection?

I also tried searching for ServerAuthenticationStateProvider but found no sample code available. And, the "Microsoft.AspNetCore.App.Ref v7.0.5" Nuget package to which this class belongs cannot be installed into my project.

Does anyone know how to solve this problem? Make the injection of IAccessTokenProvider error-free in server-side Blazor and obtain a usable object instance

**Comment by MichaelYuAlreadyExists** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimal repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem without unnecessary code. Please share with us in a public GitHub repo because we cannot open ZIP attachments, and don't include any confidential content.


thanks
this is  [a minimal repro project] 
https://github.com/MichaelYuAlreadyExists/for-issue-51699

**Comment by MackinnonBuck** [comment]
Thanks for the repro, @MichaelYuAlreadyExists. Using `Microsoft.AspNetCore.Components.WebAssembly.Authentication` isn't supported on Blazor Server.

**Comment by MichaelYuAlreadyExists** [comment]
> Thanks for the repro, @MichaelYuAlreadyExists. Using `Microsoft.AspNetCore.Components.WebAssembly.Authentication` isn't supported on Blazor Server.

Your response is similar to what I estimated. So I attempted to seek an example of using the 'Microsoft. AspNetCore. App. Ref v7.0.5' Nuget package.Or can you provide other ways to obtain an AccessToken on the blazer server?

**Comment by MackinnonBuck** [comment]
@MichaelYuAlreadyExists here are the [docs](https://learn.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0#pass-tokens-to-a-server-side-blazor-app) for passing tokens to a Blazor Server app. Note that [`AccessToken`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.accesstoken?view=aspnetcore-7.0) is also a `Microsoft.AspNetCore.Components.WebAssembly.Authentication` type, so if you want your component to work both on both Blazor Server and Blazor WebAssembly, you'll probably want to expose the access token through your own service abstraction with two separate implementations (one for Server and one for WebAssembly).

**Comment by MichaelYuAlreadyExists** [comment]
> @MichaelYuAlreadyExists here are the [docs](https://learn.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0#pass-tokens-to-a-server-side-blazor-app) for passing tokens to a Blazor Server app. Note that [`AccessToken`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.accesstoken?view=aspnetcore-7.0) is also a `Microsoft.AspNetCore.Components.WebAssembly.Authentication` type, so if you want your component to work both on both Blazor Server and Blazor WebAssembly, you'll probably want to expose the access token through your own service abstraction with two separate implementations (one for Server and one for WebAssembly).

Thanks
