### ISSUE TITLE
When will Blazor have a better debugging method in vscode?

### ISSUE THREAD

**Issue by Edemilorhea** [dotnet/aspnetcore#51693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We already know .Net 8 is comming now, And it is have a huge improvement.

But Is there a better way to debug when using vscode for Blazor project development?

I like VSCode more than Visual Studio, But the experience of using Vscode to debug Blazor is not good enough.

Visual Studio works perfactly for Blazor debugging, e.g. Hotreload, Separation of front and back ends debug.

If use Vscode, the default debug template can't use hotreload. 

if I wna't use hotreload and externalTerminal, I need a lot of additional settings, including changing to using Coreclr to start dotnet watch, then starting blazorwasm debugging so that the client's Page can be debugged, and finally starting coreclr attach to attach to the web page.

### Describe the solution you'd like

I hope that a better debugging solution can be implemented in Vscode, which can be debugged with simple and normal configuration, perfectly debug the interruption points on both sides of wasm and server, and can perform hotreload.

Just like Visual studio.

**Comment by mkArtakMSFT** [comment]
@thaystg, @danroth27 I think this feedback is relevant for the runtime/debugger teams. How would you like to track this / move somewhere?

**Comment by danroth27** [comment]
It sounds like the main ask here is to support hot reload while debugging in Visual Studio Code. I think this feedback is best shared with the C# Dev Kit folks: https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_where-do-i-submit-feedback-and-suggestions. I believe adding hot reload support to C# Dev Kit is something they are already tracking on their backlog. Since this issue is external to ASP.NET Core & Blazor I'm going to go ahead and close it.

**Comment by Edemilorhea** [comment]
> It sounds like the main ask here is to support hot reload while debugging in Visual Studio Code. I think this feedback is best shared with the C# Dev Kit folks: https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_where-do-i-submit-feedback-and-suggestions. I believe adding hot reload support to C# Dev Kit is something they are already tracking on their backlog. Since this issue is external to ASP.NET Core & Blazor I'm going to go ahead and close it.


When I want to use Vscode to develop Blazor now, I have to write the command script myself. I really want Vscode to support hot reloading, but the requirement is very simple, as long as it is as convenient as the working experience of Visual Studio.
