### ISSUE TITLE
Blazor Enhanced Load navigation doesn't replace template elements

### ISSUE THREAD

**Issue by mythz** [dotnet/aspnetcore#51692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Navigating to different pages in Blazor's default server rendering mode doesn't load the `<template>` for the page, instead it inserts the `<template>` contents of the previous page into the pages `<template>` overriding its contents.

Whichever page you navigate to first will insert its `<template>` contents into the `<template>` of the next page you navigate to. 

So whilst `<template id="page2-template">` is correct for **/page2**, its contents have instead been replaced with the `<template id="page1-template">` contents from **/page1** that you navigated from:

<img width="457" alt="image" src="https://github.com/dotnet/aspnetcore/assets/89361/7c4074aa-e9ca-4cd4-8332-4c8c7ae99a13">

If you navigate to a different page, like `/` home, then navigating to one of these pages renders the correct content for the page, but navigating between these 2 pages fails with the unexpected behavior.

### Expected Behavior

Enhanced navigating to a server rendered page, loads the HTML for that page.

### Steps To Reproduce

Also available from [BlazorNavTest](https://github.com/mythz/BlazorNavTest). 

1. Create new Blazor Template

```bash
$ dotnet new blazor -au Individual
```

3. Add Blazor Pages and `app.mjs` below:

**Pages/Page1.razor**
```cshtml
@page "/page1"

<PageTitle>Page 1</PageTitle>

<h1>Page 1</h1>
<div id="page1-content" data-load="#page1-template"></div>

<template id="page1-template">
    <h2 class="text-danger">Page 1 Template</h2>
    <p>
        go to <a href="page2">page 2</a>
    </p>
</template>

<script type="module">
import { load } from "./app.mjs"
load()
</script>
```

**Pages/Page2.razor**
```cshtml
@page "/page2"

<PageTitle>Page 2</PageTitle>

<h1>Page 2</h1>
<div id="page2-content" data-load="#page2-template"></div>

<template id="page2-template">
    <h2 class="text-success">Page 2 Template</h2>
    <p>
        go to <a href="page1">page 1</a>
    </p>
</template>

<script type="module">
import { load } from "./app.mjs"
load()
</script>
```

**wwwroot/app.mjs**
```js
export function load() {
    document.querySelectorAll('[data-load]').forEach(content => {
        const template = document.querySelector(content.getAttribute('data-load'))
        console.log('load', content.id, template?.innerHTML ?? `template missing`)
        if (template) content.innerHTML = template.innerHTML
    })
}

document.addEventListener('DOMContentLoaded', () =>
    Blazor.addEventListener('enhancedload', load))
```

### .NET Version

8.0.200-preview.23524.7

**Comment by Bartmax** [comment]
script tags are not executed on navigation but they will when SSR. Not sure if that's the issue here.

**Comment by SteveSandersonMS** [comment]
This is currently a limitation in how enhanced navigation updated DOM nodes. It walks the old and new DOM trees by recursing into the `childNodes` collection of each node. In the case of `<template>`, this doesn't produce the behavior you want because the  content of the template is *not* located on the element's `childNodes`, but instead is a separate `DocumentFragment` given by the element's `content` property. In short, `<template>` elements are a special case.

@dotnet/aspnet-blazor-eng This is not the only special case. Custom elements can also have a shadow DOM that our syncing logic would not know how to walk into. Altogether I think the right behavior would **not** be to assume there is any general valid way to walk the contents of special-case elements. Instead, for `<template>` and any custom element that we don't know about (not the ones that represent Blazor interactive components), we should simply treat them as `UpdateCost.Infinite` so the syncing logic always removes the old element and adds the new one. That's the only safe rule.

**Comment by SteveSandersonMS** [comment]
@mythz As a workaround, you could hint to the DOM sync logic that the two `<template>` elements are unmergeable by putting two different `data-permanent` attribute values onto them. Then it should remove the old element and add the new one, leaving the document updated in the way you wanted.

**Comment by mythz** [comment]
@SteveSandersonMS Thanks for looking into this. 

> by putting two different data-permanent attribute values onto them.

Do you just mean adding `data-permanent` attributes to the `<template>` elements as done in this commit: https://github.com/mythz/BlazorNavTest/commit/08e514a4402caf0d6f91f70f9d02b2ebda80075b

As that doesn't appear to help resolve the issue:

<img width="419" alt="image" src="https://github.com/dotnet/aspnetcore/assets/89361/feae6d55-b360-45a8-912f-2027c37d7cef">

**Comment by Notallthatevil** [comment]
@mythz What Steve suggested does work. You just need to give data-permanent a value. Something like 
`<template id="page1-template" data-permanent="page1-template">
...`

`<template id="page2-template" data-permanent="page2-template">
...`

**Comment by mythz** [comment]
@Notallthatevil yep can confirm example works when attribute has a value, e.g. `data-permanent="page1-template"`
Updated example in https://github.com/mythz/BlazorNavTest/commit/2b8cbea283e34ba876c6804d6999c359461c7bd6
