### ISSUE TITLE
PageTitle not working in Auth default template page

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#51739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The title is not working in the default template with individual accounts enabled:

![image](https://github.com/dotnet/aspnetcore/assets/4984486/8525421d-624d-4c62-808b-f23f1171e9d8)

![image](https://github.com/dotnet/aspnetcore/assets/4984486/3219d558-8f5e-4948-8ffa-4055bf7f4357)

#50268 is the likely cause. 

But it would be nice if all features work properly in the default templates, with workarounds if necessary. 

### .NET Version

8.0 RC2

**Comment by mkArtakMSFT** [comment]
@halter73  do you remember if we've fixed something similar already for RTM?

**Comment by mkArtakMSFT** [comment]
@rogihee this may be fixed. Could you try your sample using the nightly .NET 8 SDK builds?
