### ISSUE TITLE
Blazor enhanced form handling doesn't honor button formaction attribute

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#51734]
When using Blazor enhanced form handling on a form that contains a `<button type="submit">` element where that element also has a `formaction` attribute that modifies the URL the form should POST to, e.g. to add a querystring value, the value of the `formaction` attribute is ignored and the parent `<form>` element `action` is used instead. Removing `Enhance` from the form makes it behave the expected way.

```razor
@page "/posts"

<EditForm Model="this" FormName="posts" OnValidSubmit="HandleSubmit" Enhance>
    <table>
        <thead>
            <tr><th>Created</th><th>Title</th><th>Action</th></tr>
        </thead>
        <tbody>
        @if (posts.Count == 0)
        {
            <tr><td colspan="3"><button type="submit" formaction="/posts?action=create">Create Posts</button></td></tr>
        }
        else {
            foreach (var p in posts)
            {
                <tr>
                    <td>@p.Created</td>
                    <td>@p.Title</td>
                    <td>
                        <button type="submit" name="PostToDelete" value="@p.Id">delete</button>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</EditForm>

@code {
    [SupplyParameterFromForm]
    [Parameter]
    public int PostToDelete { get; set; }
    
    [SupplyParameterFromQuery]
    [Parameter]
    public string? Action { get; set; }
   ...
}
```

This was found when attempting to emulate what [Razor Pages does to enable support for multiple form handlers](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#multiple-handlers-per-page).

**Comment by AlexKovynev** [comment]
@surayya-MS is any chance to backport to 8.0.x this and [https://github.com/dotnet/aspnetcore/issues/51429](51429) ? cause it both for 8.0.x

**Comment by AlexKovynev** [comment]
@surayya-MS so maybe backport?:)
