### ISSUE TITLE
Merge dotnet/xdt into aspnetcore

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/aspnetcore#51753]
As discussed offline, we want to merge the [`xdt` repository](https://github.com/dotnet/xdt) into aspnetcore. That repository contains a single source and test project. The cost of maintaining the infrastructure is higher than the value we get from that individual repository.

The component is used by at least aspnetcore and sdk, hence why layering this into aspnetcore makes most sense.

Work required:

- [ ] Move xdt sources with history into aspnetcore
- [ ] Disable and delete the AzDO pipelines for xdt
- [ ] After an official build succeeded with these changes, update the Version.Details.xml entry in sdk.
- [ ] Remove the VMR project and dependencies pointing to it: https://github.com/dotnet/dotnet/blob/main/repo-projects/xdt.proj
- [ ] Delete all subscriptions from or to xdt
- [ ] Archive the xdt repository. Migrate the remaining issues over

cc @wtgodbe @danmoseley

**Comment by mkArtakMSFT** [comment]
There are no experts of that codebase in aspnetcore repo, we can't simply take on these things. There may be other small repos that we discover later, are we going to start merging these into other repos too, expanding these? I'm just a bit concerned about the approach in general, especially about moving things around without proper ownership defined. I think this deserves at least a conversation to understand how the ownership is going to work out.
FYI @danmoseley

**Comment by ViktorHofer** [comment]
We talked about this in an offline chat and @wtgodbe mentioned that @vijayrkn owns xdt. I wouldn't expect the ownership to change here.

**Comment by wtgodbe** [comment]
Our concern is that aspnetcore builds will start breaking if something in xdt breaks, at which point it will essentially become our responsibility to fix a component we don't own, in order to unblock the team. How strong is the need for this?

**Comment by ViktorHofer** [comment]
This component hasn't changed for years but needs to be live built as it's part of the build from source graph. Both aspnetcore and sdk depends on it. As aspnetcore sits higher in the stack, we can't move it into sdk.

The xdt repository is de-facto unmaintained and keeping it running for a single project isn't really worth the cost.

**Comment by danmoseley** [comment]
Let's have a convo or mail offline.

**Comment by wtgodbe** [comment]
@ViktorHofer are you still on board to handle this migration?

**Comment by ViktorHofer** [comment]
Sure I can help with that part. I assume mimicing the folder structure of an existing component (i.e. ObjectPool) is fine? https://github.com/dotnet/aspnetcore/tree/main/src/ObjectPool

**Comment by wtgodbe** [comment]
Yes - you can check out https://github.com/dotnet/aspnetcore/blob/main/docs/AddingNewProjects.md for a couple other mechanical things that need to be done when we add a new project as well (namely updating .sln's & running `eng/scripts/GenerateProjectList.ps1`)

**Comment by ViktorHofer** [comment]
I noticed that nuget-client uses xdt as well. Need to see if a live version is used.

**Comment by ViktorHofer** [comment]
So I looked at this again. dotnet/xdt is a product dependency in dotnet/sdk and nuget-client. It's also used in aspnetcore. Hence we can't merge this into aspnetcore and xdt probably needs to stay as a separate repository.
