### ISSUE TITLE
GetEndpoint is always null and RouteValues is always empty in custom exception handler

### ISSUE THREAD

**Issue by wbuck** [dotnet/aspnetcore#51755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm attempting to build up a `ProblemDetails` object within a custom exception handler.
I've noticed that the `RouteValues` is always empty and `GetEnpoint` is always `null` and I'm unsure why.

For reference here is how I'm attempting to access the aforementioned values:

```C#
public static IApplicationBuilder UseExceptionHandlerMiddleware(this IApplicationBuilder app)
    => app.UseExceptionHandler(new ExceptionHandlerOptions
    {
        AllowStatusCode404Response = true,
        ExceptionHandler = async context =>
        {
            var exception = context.Features.Get<IExceptionHandlerFeature>()?.Error;
            
            // The endpoint is always null.
            var endpoint = context.GetEndpoint()?.ToString();

            // Always empty.
            var routeValues = context.Features.Get<IRouteValuesFeature>()?.RouteValues;

            // Other stuff.
        }
    });
```

And here is the request/response pipeline:

```C#
var app = builder.Build();
app.UseCors("OurPolicy");

// Registering the custom exception handler here.
app.UseExceptionHandlerMiddleware();
app.UseStatusCodePages();

// Other middleware registrations.
app.UseAuthentication();
app.UseAuthorization();

// Within this extension method we're mapping our minimal API endpoints.
app.AddPeopleEndpoints();

await app.RunAsync();
```

Again, for reference here is what `AddPeopleEndpoints` looks like.

```C#
public static class AddPeopleEndpoints
{
    public static void AddPeopleEndpoints(this WebApplication app)
    {
        app.MapGet("/people/{id:guid}", GetPerson)
            .WithTags("people")
            .WithName(nameof(GetPerson));

        private static async Task<Results<Ok<Person>, NotFound>> GetPerson(Guid id)
        { /* Some implementation */ }
    }
}
```

I've tried rearranging the order that we're registering our endpoints and the exception handler but the results are always the same.

Is there something we're doing wrong here? 

I took a look at the default implementation of the exception handler which can be viewed [here](https://github.com/dotnet/aspnetcore/blob/12b5fa046bf6578b5429a95cd2cf1b652319658a/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L105C24-L105C24). In terms of how we're attempting to access the values it's the same.

Maybe this isn't possible from a custom exception handler? I'm a little unclear how the default exception handler is able to retrieve those values though.

### Expected Behavior

I expected `GetEndpoint` to return a valid value and `RouteValues` to not be empty.

### Steps To Reproduce

You can see a reproduction here: [Repro](https://github.com/wbuck/Repro)

From Postman you can use the following URI: `http://localhost:5203/weatherforecast/{{$randomUUID}}`

### .NET Version

7.0.401

**Comment by captainsafia** [comment]
@wbuck Can you trying registering the routing middleware (`app.UseRouting()`) before calling `app.UseExceptionHandlerMiddleware`?

**Comment by wbuck** [comment]
@captainsafia Yeah so I tried that in both our actual application and the [Repro](https://github.com/wbuck/Repro) project but I'm still seeing the same behavior.

<h3>Repro</h3>

```C#
var app = builder.Build();
app.UseRouting();
app.UseExceptionHandler(new ExceptionHandlerOptions
{
    AllowStatusCode404Response = true,
    ExceptionHandler = context =>
    {
        // This will always be null.
        var ep = context.GetEndpoint()?.ToString();

        // This will always be empty.
        var values = context.Features.Get<IRouteValuesFeature>()?.RouteValues;
        return Task.CompletedTask;
    }
});
```

![image](https://github.com/dotnet/aspnetcore/assets/13386150/e67a5f34-8633-4e72-b2b0-8f2f2bc35084)

**Comment by wbuck** [comment]
OK problem solved.
I need to use the `IExceptionHandlerPathFeature` to get the `Endpoint` and `RouteValues`:

```C#
var app = builder.Build();
app.UseRouting();
app.UseExceptionHandler(new ExceptionHandlerOptions
{
    AllowStatusCode404Response = true,
    ExceptionHandler = context =>
    {
        var feature = context.Features.Get<IExceptionHandlerPathFeature>();
        // This is now a valid endpoint.
        var ep = feature?.Endpoint?.ToString();

        // The route values is not empty.
        var values = feature?.RouteValues;
        return Task.CompletedTask;
    }
});
```
