### ISSUE TITLE
Kestrel options do not apply.

### ISSUE THREAD

**Issue by Hergeirs** [dotnet/aspnetcore#51763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using [SkiaSharp](https://www.nuget.org/packages/SkiaSharp) for a project. They don't have an asynchronous API, so I need to set ```serverOptions.AllowSynchronousIO = true;``` in kestrel.
For some reason it doesn't seem to have an effect. 
I'm only setting the option because I'm working with legacy code and can't really change the dependency on SkiaSharp at the moment.
As soon as I run ```SKBitmap.Decode(stream);``` I get the exeption: 
```
Unhandled exception. System.NotSupportedException: Synchronous reads are not supported.
```

I have been scouring every resource to try to find a solution. 

### Expected Behavior

Expect Asynchronous reads to work. After the setting is applied.

### Steps To Reproduce

[link for minimal git repo](https://github.com/Hergeirs/blazor-server-issue-repro)

# Minimal steps to reproduce from template

* Create a new blazorserver project
  *  ``` dotnet new blazorserver -o BlazorApp -f net7.0 ```
* Configure Kestrel by adding this line to ```program.cs``` directly beneath ``` var builder = WebApplication.CreateBuilder(); ```
  *  ``` builder.WebHost.UseKestrel().ConfigureKestrel(options => options.AllowSynchronousIO = true); ```
* Install SkiaSharp:
  * ```dotnet add package SkiaSharp.NativeAssets.Linux.NoDependencies```
* Change contents of ``` Pages/Index.razor``` to the following
```
//  Pages/Index.razor
@page "/"
@using SkiaSharp
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components

<InputFile OnChange="@OnChange" multiple />

@code {
    private void OnChange(InputFileChangeEventArgs args)
    {
        foreach (var file in args.GetMultipleFiles())
        {
            try
            {
                var stream = file.OpenReadStream();
                var image = SKBitmap.Decode(stream);
            }
            catch (Exception)
            {
                // Ignore Invalid files
            }
        }
    }
}

```

* Run ``` dotnet run ``` in a terminal.
*  upload a picture.
*  exception is thrown.

### Exceptions (if any)

Unhandled exception. System.NotSupportedException: Synchronous reads are not supported.
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
   at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
   at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)

### .NET Version

7.0.403

### Anything else?

Editor: ```NVIM v0.9.4```

## dotnet --info

```
.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.403/

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  7.0.403 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by BrennanConroy** [comment]
Blazor is throwing that error directly. It has nothing to do with Kestrel.
https://github.com/dotnet/aspnetcore/blob/c15938bb5f23fd3ad2374bde554a6b492a36ecde/src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs#L56

**Comment by SteveSandersonMS** [comment]
The `BrowserFileStream` can't support synchronous reads because it's reading from a file in the browser's memory, which is only reachable over the network.

As a solution in your case, can you asynchronously read the file into memory (as a `byte[]`) before passing that data to `SKBitmap.Decode`?

**Comment by SteveSandersonMS** [comment]
Yes that's correct.
