### ISSUE TITLE
Action route starting with `:` is interpreted as `/:` 

### ISSUE THREAD

**Issue by Mosch0512** [dotnet/aspnetcore#51769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Action route starting with `:` is interpreted as `/:`  when using a controller rout and wanting to exgtend it as example:

```C#
[Route("humans")]
public HumansEndpoint() : ControllerBase {   
    ...
	[HttpPost, Route(":lough")]
	public async Task<IActionResult> Lough([FromBody] LoughDto lough) {
            ...
```

The lough route would now look like that which i think is wrong
```
POST .../humans/:lough
```

Note that when using an abolut route it would work
`Route("/humans:lough")`
would look like that
`POST /humans:lough`

### Expected Behavior

I think if the first character of an action route is an special character it should be used instead of the `/`?

So that it looks like that?
```
POST .../humans:lough
```

### .NET Version

6.0.402

**Comment by javiercn** [comment]
@Mosch0512 thanks for contacting us.

Route attributes combine across separate segments they aren't pure string concatenations. In the case that you mention the expected result is a route that matches the literal segment humans, followed by the literal segment `:lough`.

You can't start a parameter on a preceding attribute/template and add constraints or other data to it that is not a new segment.

**Comment by Mosch0512** [comment]
So to archive this i have to use an Absolute route?  And thats the only way on how to resolf my requirement?
Is there any downside in using an Absolute route than?

Thx a lot :)

**Comment by javiercn** [comment]
Yep, you would simply write `[HttpPost("humans:lough")]` in your action, since it's a single segment
