### ISSUE TITLE
Dockerize ASP.NET Core with Angular template

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#51760]
So the closest I could find was #5417, which was closed with zero actual solutions, hoping someone sees what's wrong with mine.

So I created the .NET 7 [ASP.NET Core with Angular template](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#spa) with individual accounts for identity scaffolding.  
This creates an application containing an angular app in /ClientApp and also builds and runs it when running the asp.net core application.

I then added docker support to the asp.net core application, which of course creates the asp.net core dockerfile without angular support.

So then I changed the build image to dotnetimages/microsoft-dotnet-core-sdk-nodejs:7.0_20.x, an image that contains nodejs in addition to the .NET 7 SDK.

This builds nicely, but for some reason when running the image and calling the URL returns a 500 and nothing more.  
Same when running it via F5 from Visual Studio, and VS' containers tab only displays "The current docker context is not supported".

**Comment by javiercn** [comment]
@Regenhardt thanks for contacting us.

Change your docker file to add an extra step that installs node into the image

```console
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-with-spa
RUN bash -E $(curl -fsSL https://deb.nodesource.com/setup_18.x | bash - ); apt install -y nodejs

From build-with-spa as build
```

@guardrex do you know if we have docs for this?

**Comment by guardrex** [comment]
I don't think so. The guidance we carry is at ...

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-7.0

I'll open an issue for it.

**Comment by Regenhardt** [comment]
> @Regenhardt thanks for contacting us.
> 
> Change your docker file to add an extra step that installs node into the image
> 
> ```
> FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-with-spa
> RUN bash -E $(curl -fsSL https://deb.nodesource.com/setup_18.x | bash - ); apt install -y nodejs
> 
> From build-with-spa as build
> ```
> 
> @guardrex do you know if we have docs for this?

This is similar to what the image I'm currently using does here, although it installd nodejs 20 instead of 18:  
https://hub.docker.com/layers/dotnetimages/microsoft-dotnet-core-sdk-nodejs/7.0_20.x/images/sha256-afa117606aff103d4d22f42120519457bf02942be7a123960cdac967c6aba633?context=explore

**Comment by Regenhardt** [comment]
For future reference: I had no `app.UseDefaultFiles()` in my asp pipeline so the call to root ("/") didn't get routed to the index.html and instead got caught in the identity middleware, which I haven't properly configured yet.

Added `app.UseDefaultFiles();` just before `app.UseStaticFiles();` and now it works as intended.
