### ISSUE TITLE
Web Farm with IIS10 Servers | Content Server: HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process)

### ISSUE THREAD

**Issue by nasheayahu** [dotnet/aspnetcore#51764]
My goal was to put all ASP.NET core content on a Content Server and found "[Build a Web Farm with IIS Servers](https://learn.microsoft.com/en-us/iis/web-hosting/scenario-build-a-web-farm-with-iis-servers/overview-build-a-web-farm-with-iis-servers)" learning document showing how to do this, but I've ran into a problem. I'm running 5 KVM Windows 2019 Essential VMs (ARR, Content, Certificate, Web1, Web2) Servers.

Testing the Blazor App on Web1 I get the,
- Browser: HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process)

and viewing the Windows Logs | Application
- Failed to start application '/LM/W3SVC/1/ROOT', ErrorCode '0x8007023e'.
- Application '\CONTENTSERVER\wwwroot\kohanyim' failed to start. Exception message: Unexpected exception: status: Access is denied.: "\CONTENTSERVER\wwwroot\kohanyim\dotnet.exe"

I thought this would have taking care of that:

cd %windir%\Microsoft.NET\Framework64\v4.0.30319
caspol -m -ag 1. -url file://CONTENTSERVER/wwwroot/kohanyim/* FullTrust

So, how do I correct this?

**Comment by BrennanConroy** [comment]
caspol doesn't seem like it's supported much these days
https://learn.microsoft.com/dotnet/framework/tools/caspol-exe-code-access-security-policy-tool

I usually go to advanced settings and modify the credentials
![image](https://github.com/dotnet/aspnetcore/assets/7574801/858f5132-3332-4f85-bcae-84b92108d0b2)

**Comment by nasheayahu** [comment]
Hi @BrennanConroy,

Thanks for the replay, here is what I did according the Learning Document:

- as you have done
![Screenshot_KohanIIS10Server_2023-10-31_12:05:59](https://github.com/dotnet/aspnetcore/assets/5845052/6a39ca24-771b-44ba-ab8a-519fce9d7bf0)

- accept my folder is Shared on a Windows 2019 Essential Content Server
![Screenshot_KohanIIS10Server_2023-10-31_12:04:52](https://github.com/dotnet/aspnetcore/assets/5845052/6faafa18-1843-425a-92ba-714478481fad)

- as well as the Shared Configuration
![Screenshot_KohanIIS10Server_2023-10-31_12:07:31](https://github.com/dotnet/aspnetcore/assets/5845052/79a1a8df-5767-44ec-b93e-879fb89d1f57)

![Screenshot_KohanIIS10Server_2023-10-31_12:07:54](https://github.com/dotnet/aspnetcore/assets/5845052/c0bd7175-8ffa-41b6-a93c-3820222fe860)

and no success browsing the app from this (Web1) IIS10 Server.

**Comment by BrennanConroy** [comment]
Your physical path is set to `//CONTENTSERVER/wwwroot/kohanyim/wwwroot` instead of `//CONTENTSERVER/wwwroot/kohanyim` and dotnet.exe is complaining about the `//CONTENTSERVER/wwwroot/kohanyim/` path as well.

**Comment by nasheayahu** [comment]
**UPDATE:** it was the wrong image.

In addition, here is my VS net7.0 folder:
![remmina_kohanws_10 30 60 16_20231029-223042](https://github.com/dotnet/aspnetcore/assets/5845052/bee08937-80e8-4d9a-84c1-e4960e6712dd)

and the Published content folder to the Web1 Shared folder:
![remmina_kohanws_10 30 60 16_20231029-223131](https://github.com/dotnet/aspnetcore/assets/5845052/0546d52b-061c-4c0b-ae0d-f84b15ec9282)

**Comment by BrennanConroy** [comment]
I'm wondering why it's trying to use dotnet.exe from your folder, the screenshots you've shared don't show dotnet.exe being there.
Can you specify an absolute path for `processPath="dotnet"`?
