### ISSUE TITLE
We cannot use services registered in Web assembly in components that are Interactive Server rendered.

### ISSUE THREAD

**Issue by Mehdi-Aghaei** [dotnet/aspnetcore#51773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following component in my web assembly app project, and I registered this client in both Server and Web assembly program files.
my goal is to have separation of concern, Define API in the server app, and consume it with HTTP client in the Web assembly app  I like all my components to live in the web assembly app Server and Web assembly render mode,
result: There was an unhandled exception on the current circuit,
```razor
@page "/"

@rendermode InteractiveServer
@inject ApiClient HttpClient

<button @onclick="SayHi">ClickMe</button>

<h1 class="text-yellow-600">From API: @Result</h1>


@code
{
	public string Result { get; set; } = "";

	async Task SayHi()
	{
		var result = await HttpClient.GetContent();

		Result =  result.ToString();
	}


}
```
```csharp
 // in Wasi Program 
builder.Services.AddHttpClient<ApiClient>(,client =>
{
	client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
});
public class ApiClient(HttpClient httpClient)
{
	public async Task<string> GetContent()
	{
		var result = await httpClient.GetStringAsync("api");

		return result;
	}
}
	

// in server program
builder.Services.AddHttpClient();
builder.Services.AddScoped<ApiClient>();
app.MapGet("/api", ( ) => "API is alive.");
```

### Expected Behavior

client be available regardless of render mode. so in all scenarios, you have your registered service available.
```razor
@page "/"

@rendermode InteractiveServer OR InteractiveAuto OR InteractiveWebAssembly
@inject ApiClient HttpClient

<button @onclick="SayHi">ClickMe</button>

<h1 class="text-yellow-600">From API: @Result</h1>


@code
{
	public string Result { get; set; } = "";

	async Task SayHi()
	{
		var result = await HttpClient.GetContent();

		Result =  result.ToString();
	}


}
```

### .NET Version

8.0.100-rc.2.23502.2

**Comment by SteveSandersonMS** [comment]
If your component works across multiple render modes, then the intended design is that you don't put a `@rendermode` directive on it at all. This way, it becomes up to the caller to use it in whatever rendermode it wants:

 * The caller can either not specify a rendermode either (e.g., just use `<MyComponent />`), in which case it inherits the same rendermode as its parent
 * ... or the caller can use the `@rendermode` directive attribute to change that (e.g., `<MyComponent @rendermode=... />`)
