### ISSUE TITLE
Support MAX_CONNECTION_AGE in dotnet server implementation

### ISSUE THREAD

**Issue by careless6666** [dotnet/aspnetcore#51778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Now, for integration with other languages using grpc, we are faced with the problem that there is no support from the dotnet side for the parameter that is in the official GRPC documentation
https://grpc.io/docs/guides/keepalive/
MAX_CONNECTION_AGE
As an example, Java and Golang clients do not have a keep alive client-side setting and are left with hanging connections and do not update DNS information
Can you add such an option on the server side?

The original question was here
https://github.com/grpc/grpc-dotnet/issues/2308

### Describe the solution you'd like

In my first question I was recommended to implement this as middleware for kestrel
It would be possible to implement this as  middleware and connect it if the kestrel option MaxConnectionAge is specified
And it is possible to be able to distinguish between http and grpc connections for this option

**Comment by Tratcher** [comment]
> As an example, Java and Golang clients do not have a keep alive client-side setting and are left with hanging connections and do not update DNS information

Do you mean that this is like a load balancing issue? You want them to gracefully disconnect and create a new connection with current DNS? The two common solutions are to disconnect after a certain number of requests, or after a given time length as mentioned here.

Note there are two types of middleware, Kestrel Connection middleware and AspNetCore Request middleware. The former only sees raw connection traffic it doesn't even get parsed requests. It would be good at limiting connection lifetime but bad at differentiating requests. The later receives a full HttpContext and can differentiate requests, but it can be harder to manage connection lifetime from that level. Note that gRPC can share connections with non-gRPC requests so closing these connections could affect other types of traffic. If freshness of your nodes is an issue then you may want to apply a max age to all request types.

`HttpContext.Connection.RequestClose()` is the API to call from a Request middleware to initiate a graceful close, but it requires an active request. `IConnectionLifetimeNotificationFeature.RequestClose()` can be called from Kestrel Connection middleware and does not require active requests.

What about `MAX_CONNECTION_AGE_GRACE`? I'm guessing that aborts a connection after the max age and an additional buffer time? That would be `IConnectionLifetimeFeature.Abort()`.
