### ISSUE TITLE
PersistentComponentState: overloads for jsontypeinfo

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#51790]
## Background and Motivation

`Microsoft.AspNetCore.Components.PersistentComponentState` currently only allows for reflection based serialization.

## Proposed API

`Microsoft.AspNetCore.Components.PersistentComponentState.PersistAsJson<TValue>(string! key, TValue? instance, JsonTypeInfo<TValue>! jsonTypeInfo) -> void`

`Microsoft.AspNetCore.Components.PersistentComponentState.TryTakeFromJson<TValue>(string! key, JsonTypeInfo<TValue>! jsonTypeInfo, out TValue? instance) -> bool`

## Usage Examples

```csharp
public class PersistentAuthenticationStateProvider(PersistentComponentState persistentState) : AuthenticationStateProvider
{
 public override Task<AuthenticationState> GetAuthenticationStateAsync()
 {
  if (!persistentState.TryTakeFromJson<UserInfo>(nameof(UserInfo), UserInfoSerializer.Default.UserInfo, out var userInfo) || userInfo is null)
...
public class PersistingRevalidatingAuthenticationStateProvider : RevalidatingServerAuthenticationStateProvider
{
...
 private async Task OnPersistingAsync()
 {
...
    _state.PersistAsJson(nameof(UserInfo), new()
    {
     UserId = userId,
     Email = email,
    }, UserInfoSerializer.Default.UserInfo);
```

## Alternative Designs

This is consistent with other JSON serialization APIs.

## Risks

None

## Implementation

https://github.com/dotnet/aspnetcore/pull/51789

**Comment by javiercn** [comment]
JSON serialization is an implementation detail of these APIs. We don't plan to expose this as a first-class citizen. We plan instead to  have explicit overloads that have callbacks you can use to write to a buffer and do whatever you prefer there. Suggest upvoting that issue instead.

https://github.com/dotnet/aspnetcore/issues/45574
