### ISSUE TITLE
.NET 8 changes behavior of IFileProvider initialization for Blazor Server

### ISSUE THREAD

**Issue by normj** [dotnet/aspnetcore#51794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From my understanding with Blazor ServerSide the IFileProvider used for static files is configured with a `CompositeFileProvider` to handle the embedded resources from the Blazor assemblies. I'm updating the [AWS Lambda .NET Test Tool](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool) to support .NET 8 which also has embedded resources in its assemblies. During the services configuration I run the following code to wrap the already configured FileProvider with my embedded file provider with a CompositeFileProvider.

```csharp
services.AddOptions<StaticFileOptions>()
    .PostConfigure(o =>
    {
        var fileProvider = new ManifestEmbeddedFileProvider(typeof(Startup).Assembly, "wwwroot");

        // Make sure we don't remove the existing file providers (blazor needs this)
        o.FileProvider = new CompositeFileProvider(o.FileProvider, fileProvider);
    });
```

From .NET Core 3.1 to .NET 7 the code above has worked without issues. While upgrading to .NET 8 this code no longer works because at this point the `o.FileProvider` is null when in previous versions `o.FileProvider` was not null it would be the IFileProvider to handle Blazor's embedded resources as well as psychical files on disk.

### Expected Behavior

At this point of the `PostConfigure` the `IFileProvider` should be set so I can combine with my `IFileProvider`. If I just set the FileProvider property to my `ManifestEmbeddedFileProvider` then the Blazor embedded assets are not downloaded to the browser and then the application is not functional.

### Steps To Reproduce

In this Blazor .NET 8 application the `Console.WriteLine` during the `PostConfigure` has the `o.FileProvider` as null.
```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddOptions<StaticFileOptions>()
                .PostConfigure(o =>
                {
                    Console.WriteLine($"Has IFileProvider: {o.FileProvider}");
                });

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
```

In this .NET 7 Blazor app the `Console.WriteLine` during the `PostConfigure` has the `o.FileProvider` as **not** null.
```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();

builder.Services.AddOptions<StaticFileOptions>()
                .PostConfigure(o =>
                {
                    Console.WriteLine($"Has IFileProvider: {o.FileProvider}");
                });

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Here is the code in our application that is affected by it https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool.BlazorTester/Startup.cs#L87 

It looks it bit odd I'm sure because this tool is a bit of an odd use case for Blazor ServerSide but the project does multi targeting back to .NET Core 3.1. The examples above on how to repo the issue were starting Blazor applications from the VS project templates and then just adding the `AddOptions<StaticFileOptions>()`.

If this is an expected runtime behavior change then how would I be able to combine my application's `ManifestEmbeddedFileProvider` with the `IFileProvider` that Blazor will setup in a .NET 8 application.

**Comment by javiercn** [comment]
@normj thanks for contacting us.

This change is expected and by design, we were modifying the default settings in the options and that broke when people passed in their own options to the static files middleware. In .NET 8.0 we stopped changing the default options and instead created a separate endpoint to serve just the blazor.server.js file.

You can just assign the Environment.WebRootFileProvider as we did in 7.0 if it's null.

https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Components/Server/src/DependencyInjection/ConfigureStaticFilesOptions.cs#L13-L60

**Comment by normj** [comment]
Thanks @javiercn setting `Environment.WebRootFileProvider` that works for me!
