### ISSUE TITLE
Routing paths with dots

### ISSUE THREAD

**Issue by kuhnboy** [dotnet/aspnetcore#51818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

As described in https://github.com/dotnet/aspnetcore/issues/17334

WASM Blazor apps have an issue with routing paths with 'dots' in them.

This is not a problem with Blazor itself though as it handles 'dots' in routes just fine, but it is a problem with the Kestrel server when running in Visual Studio locally. There is no way to change the rewrite rules with Kestrel that I can see.

If you write a simple web.config with rewrite rules, you can get around this limitation of Kestrel by using IIS Express profile.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<location path="." inheritInChildApplications="false">
		<system.webServer>
			<rewrite>
				<rules>
					<rule name="Redirect to Single Page">
						<match url="^fetchdata/.*" />
						<action type="Rewrite" url="/index.html" />
					</rule>
				</rules>
			</rewrite>
		</system.webServer>
	</location>
</configuration>
```

You can also get around this issue in Azure static apps with a config file.

### Describe the solution you'd like

I would like to be able to configure the WebHost run when debugging a client side Blazor WASM so that I can use 'dots' in URL's.

**Comment by kuhnboy** [comment]
If this needs to be routed to a different project, please let me know.

**Comment by javiercn** [comment]
@kuhnboy thanks for contacting us. There's the `:nonfile` constraint to avoid matching anything that resembles a file.

If as in the issue you pointed out you have a route like `"/counter/{**text}"` blazor will match anything after the /counter/ segment. It's simply doing what you are asking for.

**Comment by kuhnboy** [comment]
> @kuhnboy thanks for contacting us. There's the `:nonfile` constraint to avoid matching anything that resembles a file.

Thank you. The `:nonfile` constraint doesn't seem to be supported in the Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer. Is that correct?
