### ISSUE TITLE
Debugging: Update dictionary debuggers in aspnetcore to follow the new standard

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#51827]
https://github.com/dotnet/runtime/pull/92534 updates dictionaries to display the key in the name instead of an index.

We should update name/value collections in ASP.NET Core to follow the same pattern.

There are a lot of custom dictionaries to update:

- [ ] [ItemsDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http/src/Internal/ItemsDictionary.cs)
- [ ] [FeatureCollection](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Extensions/Features/src/FeatureCollection.cs)
- [ ] [QueryCollection](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http/src/QueryCollection.cs)
- [ ] [HttpHeaders](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.cs)
- [ ] [HttpContext features](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http.Abstractions/src/HttpContext.cs#L111)
- [ ] [ModelStateDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Mvc/Mvc.Abstractions/src/ModelBinding/ModelStateDictionary.cs)
- [ ] [DynamicViewData](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Mvc/Mvc.ViewFeatures/src/DynamicViewData.cs)
- [ ] [RouteValueDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http.Abstractions/src/Routing/RouteValueDictionary.cs)
- [ ] [HeaderDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http/src/HeaderDictionary.cs)
- [ ] [RequestCookieCollection](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http/src/Internal/RequestCookieCollection.cs)
- [ ] [ViewDataDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Mvc/Mvc.ViewFeatures/src/ViewDataDictionary.cs)
- [ ] [TempDataDictionary](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Mvc/Mvc.ViewFeatures/src/TempDataDictionary.cs)
- [ ] [QueryCollectionInternal](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Http/src/QueryCollectionInternal.cs)
- [ ] [HeaderCollection](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Shared/HttpSys/RequestProcessing/HeaderCollection.cs)
- [ ] [RouteData](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Http/Routing.Abstractions/src/RouteData.cs)
- [x] ~[ServerAddressesCollection](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Servers/Kestrel/Core/src/Internal/ServerAddressesCollection.cs)~
- [ ] [RequestHeaders](https://github.com/dotnet/aspnetcore/blob/6870c9b9946a738e4663a2ba6ecd81eb057571c9/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs)

**Comment by danmoseley** [comment]
Cc @artu eek

**Comment by shiladitya-mukerji-22** [comment]
Hey @JamesNK, I would like to work on this update. Can you assign the issue to me.

**Comment by JamesNK** [comment]
@shiladitya-mukerji-22 I suggest you start with one or two collections, establish a pattern that can be reused, and then create a PR.

A small PR lets us review it and suggest changes. Once it is good, you or something else can apply the changes to all of the collections.

**Comment by JamesNK** [comment]
@shiladitya-mukerji-22 Do you still plan to look at this? If not, I wouldn't mind making these changes.

**Comment by JamesNK** [comment]
I'm going to look at this next week.
