### ISSUE TITLE
Can't start debugging with MS Edge

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#51822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

cc: @thaystg 

When starting the app (Run button in VS) for MS Edge, the app builds successfully and starts. The debugger fails and the browser doesn't open to the app, then the app shuts down. The error in a popup and in the console is ...

![image](https://github.com/dotnet/aspnetcore/assets/1622880/2ca74bfd-d9e0-44da-a06f-b18a4cc18eee)

> Failed to launch debug adapter 'pwa-msedge'.
> The system cannot find the file specified

If I switch the browser with the **Browse With** UI to Firefox, the app does launch in the FF browser. It seems like this error is only occurring for MS Edge. I don't have Chrome installed, so I can't test with Chrome.

### Steps To Reproduce

1. Set the broswer to MS Edge.
2. Attempt to debug the app.

### Exceptions (if any)

> Failed to launch debug adapter 'pwa-msedge'.
> The system cannot find the file specified

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.8.0 Preview 6.0

.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.8.34227.203
   Manifest Version:    8.0.0-rc.2.9511/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9511\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34227.203
   Manifest Version:    17.0.8465-net8-rc2.1/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\17.0.8465-net8-rc2.1\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34227.203
   Manifest Version:    17.0.8465-net8-rc2.1/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\17.0.8465-net8-rc2.1\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34227.203
   Manifest Version:    34.0.0-rc.2.479/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.479\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  6.0.319 [C:\Program Files\dotnet\sdk]
  7.0.113 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by thaystg** [comment]
@joj can you help us with this issue?

**Comment by joj** [comment]
@guardrex can you create a new issue in VS by going to Help->Submit Feedback, and then posting the link to the issue here? We get some extra logs and information there when you do it that way. Thanks! J

**Comment by guardrex** [comment]
Sure thing, @joj ... I'll be free very soon ... 20 minutes ... and will take care of it.

**Comment by guardrex** [comment]
Report sent.

**Comment by joj** [comment]
Add a link to the feedback here if you can. It will get to me eventually, but this way it will be faster than going through all the process :)

**Comment by guardrex** [comment]
https://developercommunity.visualstudio.com/t/Cant-start-debugging-with-MS-Edge/10507606?q=can%27t+start+debugger+with+ms+edge

**Comment by guardrex** [comment]
I'm not blocked BTW. If it takes some time to get to it, no worries. I'm using FF right now, which is spawned successfully for debug runs.

**Comment by guardrex** [comment]
Also note that I mentioned that I'm using a custom `Browse With` browser entry for MS Edge that opens it with the MS Edge EXE and in InPrivate mode (`-inprivate`), but that doesn't matter. Even if I select the "Microsoft Edge" entry that VS naturally provides, I get the same error when I set it to be the default `Browse With` browser.

**Comment by mkArtakMSFT** [comment]
I see that the internal ticket has already been assigned for investigation. Closing as there is no further action pending from us here.
