### ISSUE TITLE
net8 blazor interactive modes are so flaky to work with

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#51837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have played around with net8 blazors different interactive render modes, and although it sounds great from the technical perspective,  it is quite impossible to work with in reality, because they break at run-time for the tiniest little bitty things :(

1. Global interactive + any page that requires static mode (httpcontext) -> break at run-time
2. Component that runs in mode X but add a tag for component C that uses mode Y -> break at run-time
3. No global interactive + add some interactive component to any sub component -> break at run-time
4. Any non-trivial Mode Auto or WebAssembly -> break at run-time ('cannot find root')
5. Culture setting on server with Mode Auto or WebAssembly -> break at run-time (reverts to browser language detection)
6. Mode Auto or WebAssembly on project without a dedicated WebAssembly Project -> break at run-time ('dotnet.js 404')
7. Mode Auto or WebAssembly for 3rd party libraries -> break at run-time (because users suck)
8. Fallback policy RequireAuthenticationUser -> break at run-time (cannot access blazor.web.js)
9. Shared JsonSerializerContext between server and webassembly -> break at run-time (because server uses JsonSerializerDefaults.Web, and webassembly use JsonSerializerDefaults.General)
10. Use IJSRuntime explicity or implicitly -> break at run-time (because all modes pre-render)
11. Interactive server with rollover or canary deployment, or any kind of deployment scenario really -> break at run-time 

### Expected Behavior

That blazor was useable beyond toy projects.

### Steps To Reproduce

Get a jr dev to play around with blazor for a few days and see how often they will shoot themselves in the foot.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by davidfowl** [comment]
@davhdavh was your expectation that all of the above would just work or that you would get compile time errors for unsupported combinations? Were the runtime errors helpful?
