### ISSUE TITLE
Unable to communicate with pods in Kubernetes after upgrading to 8.0.100-rc.2

### ISSUE THREAD

**Issue by mschaefer-gresham** [dotnet/aspnetcore#51845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Health checks failing in Kubernetes after upgrading to latest dotnet 8. Health checks failing. Downgrading to latest 7 version solved issue.

### Expected Behavior

Pods to continue communicating as before. 

### Steps To Reproduce

When app is containerized and deployed to Kubernetes, urls can't be reached between pods on port 80.

### .NET Version

8.0.100-rc.2

**Comment by Tratcher** [comment]
Possibly related if you're using `WebHost`: https://github.com/dotnet/aspnetcore/issues/51125

**Comment by mschaefer-gresham** [comment]
@Tratcher yes this is most likely the issue. The app in question uses WebHost. Will reopen if necessary.
