### ISSUE TITLE
Strange message loss when a client sends a message to hub

### ISSUE THREAD

**Issue by mrgopalakrishnan** [dotnet/aspnetcore#51853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an application with SignalR hub and .Net clients. the server will assign tasks to different clients and the clients will communicate the progress and status to the server.

The problem is when a first command is sent to the client and the status is received successfully, the second command status is not sent from client to server. 

i verified the connection and it is in good state.

Used different methods to send messages like SendCoreAsync, SendAsync and InvokeAsync and the behavior is same.

the behavior is strange and occurs on a specific scenario and always reproducible.
even tried to use string messages and the behavior is same.

#### ConfigureServices Method
``` 

            services.AddSignalR(hubOptions =>
            {
                hubOptions.MaximumReceiveMessageSize = 300 * 1024 * 1024;
            }).AddMessagePackProtocol();
```
#### Configure Method
``` 
 app.UseEndpoints(endpoints =>
 {
     endpoints.MapControllers();
     endpoints.MapHub<ClientsHub>("/signalRServer");
     endpoints.MapHub<AgentsHub>("/agentsHub"); //this is the hub suppose to receive the message
 });
```
#### hub method to be invoked
```
    public class AgentsHub : Hub
{
 public void SummaryMessage(SummaryMessage summaryMessage)
 {
     logger.LogDebug($"Summary message received {JsonConvert.SerializeObject(summaryMessage)}");
     OnSummaryReceived?.Invoke(summaryMessage);
 }
}
```

#### Client side connection implementation
```
        private async Task Connect()
        {
            InstantiateConnection();
            while (true)
            {
                try
                {
                    logger.LogInformation("Trying to establish connection with Server");
                    await connection!.StartAsync();
                    logger.LogInformation("Connection established. trying to authenticate");
                    var result = await Authenticate();
                    if (result)
                        logger.LogInformation("Authentication successful.");
                    else
                        logger.LogError($"Authentication with Server {_agentConfiguration.ServerUrl + " / agentsHub"} is not successful. Make sure the Server is targetted righly and the agent version is compatible");
                    break;
                }
                catch
                {
                    logger.LogInformation("Error while connecting to the server. Trying to reconnect");
                    InstantiateConnection();
                    await Task.Delay(new Random().Next(0, 15) * 1000);
                }
            }
        }
```
```
        private void InstantiateConnection()
        {
            connection = new HubConnectionBuilder()
                      .WithUrl(_agentConfiguration.ServerUrl + "/agentsHub", options =>
                      {
                          options.AccessTokenProvider = () => Task.FromResult(token);//check on token
                      })
                      .WithAutomaticReconnect()
                      .Build();
            connection.Closed += async error =>
            {
                token = null;
                logger.LogInformation("Signalr client disconnected");
                await Connect();
            };
            connection.Reconnecting += error =>
            {
                token = null;
                logger.LogInformation("Signalr client reconnecting");
                return Task.CompletedTask;
            };
            connection.Reconnected += err =>
            {
                return Authenticate();
            };

            connection.On<string, string>("Execute", (method, paramJson) =>
            {
                Execute(method, paramJson);
            });
        }
```

#### Packages:
**Server:**
<TargetFramework>net7.0</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.9" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="7.0.9" />

***Client:***
<TargetFramework>net7.0</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="7.0.9" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.9" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="7.0.9" />

**Comment by BrennanConroy** [comment]
> the second command status is not sent from client to server.

Where is the code? It's hard to even begin to diagnose an issue if we can't even see what you're doing.

> the behavior is strange and occurs on a specific scenario and always reproducible.

If it's simple to repro can you provide a small github project that has the problem so we can run it?
