### ISSUE TITLE
How to bypass "Pick an account" popup after Sign out

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#51858]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-to-bypass-Pick-an-account-popup-af/10503095)._

---
[severity:It's more difficult to complete my work]
Hello all,

Is there any possibility to bypass the "Pick user popup", where you have to select user to logout, after Sign out with Endpoint v2.0 at Azure AD?

We need to execute automatic sign out at Blazor app while user is not active, but we got redirect at the popup and the user is still signed in.

---
#### Feedback Bot on 10/30/2023, 07:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@jmprieur looks like this is an AAD related question. Can you or someone from your team help the customer here? Thanks!

**Comment by jmprieur** [comment]
This is the case when you are signed-in in the browser with several accounts.
you could give hints to AzureAd. Microsoft.Identity.Web does that by passing in the login_hint and domain_hint.
