### ISSUE TITLE
ASP0018 does not work with non-literals

### ISSUE THREAD

**Issue by KennethHoff** [dotnet/aspnetcore#51855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With literals:
![Screenshot_20231103_180135](https://github.com/dotnet/aspnetcore/assets/17124533/a91ebc77-1caf-4379-816c-be29e007ab0f)

with constants:
![Screenshot_20231103_180148](https://github.com/dotnet/aspnetcore/assets/17124533/e33c83dd-3b06-4141-91d7-fef67536d09c)

The constant, for reference:
![image](https://github.com/dotnet/aspnetcore/assets/17124533/d130798c-343e-4316-b062-918a110bf5e6)

The handler, for reference:
![image](https://github.com/dotnet/aspnetcore/assets/17124533/5c324ed7-fe86-4d20-97b0-c3b9e058ed85)

(I simply removed the parameter to get the warning)

### Expected Behavior

I'd expect to get the same warning with both approaches.

### Steps To Reproduce

![Screenshot_20231103_181546](https://github.com/dotnet/aspnetcore/assets/17124533/4b64d00f-aab0-495b-8f5f-7b2f77c26014)

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

This is using `JetBrains Rider 2023.3 EAP 5`.

Speaking of, JetBrains has their own analyzer for this that actually works for all these cases, which I had disabled:
![image](https://github.com/dotnet/aspnetcore/assets/17124533/02d3706e-6a05-445f-b391-96346df441c6)

Enabling it, I get this:
![Screenshot_20231103_181800](https://github.com/dotnet/aspnetcore/assets/17124533/db91c471-f187-4abe-97e6-b20d1b573d14)

**Comment by martincostello** [comment]
Any fix for this issue might also be applicable to the issue described in #48307.

**Comment by JamesNK** [comment]
@KennethHoff Does JetBrains work if the string isn't const? e.g. `static readonly RootEndpoint = "/root".ToLower();` I'm curious if they just ignore the RootEndpoint and parses the literal route on its own, or if they combine the two parts at compile time. Combing will only work with const values.

**Comment by KennethHoff** [comment]
![Shot_20240430_182703](https://github.com/dotnet/aspnetcore/assets/17124533/4ec81b7a-a4cc-4811-aa28-353db8b793d2)
![Shot_20240430_182646](https://github.com/dotnet/aspnetcore/assets/17124533/60560ce2-2aea-4c0d-9379-eaa46ccb621a)

**Comment by JamesNK** [comment]
I don't think this will ever be supported. The underlying Roslyn infrastructure doesn't attempt to provide syntax highlighting or analysis to non-literal strings. There are too many edge cases.

**Comment by KennethHoff** [comment]
Fair enough, I guess 🫠
