### ISSUE TITLE
No documentation or support for projects that use @angular/localize

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#51859]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-documentation-or-support-for-projects/10467917)._

---
[severity:It's more difficult to complete my work]
_This is a migration of a github issue (https://github.com/MicrosoftDocs/visualstudio-docs/issues/9498), which references this documentation: https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022. Developers requested a new issue be created in this venue. Description copied as follows:_

The default angular template does not work well with angular projects that use `@angular/localize` and it's not clear if there is a way to make it work without a custom implementation to replace the `StaticFileMiddleware` class and/or `MapFallbackToFile`.

For reference, Angular projects that build multiple languages using `@angular/localize` build one version of the app per culture code listed in the project's `angular.json` file. For example, if culture codes `en` and `fr` are supported, you'd have a version of the app under `wwwroot/en` and `wwwroot/fr`. Out of the box, this partially works with the built-in static file middleware if you add `/en/` or `/fr/` to the path, but the `MapFallbackToFile("index.html")` call will not succeed because it needs to dynamically map to `/en/index.html` or `/fr/index.html` depending on the language they were viewing at the time.

Furthermore, if you want to NOT use `/en/` or `/fr/` subpaths in the browser, and instead map static files to the `wwwroot/{closest matching culture code}` path that most closely matches the `Accept-Language` header in the browser, and/or some other source of language preference (a cookie for instance, or a query param), this does not seem to be possible with the existing static file middleware. You could potentially insert a custom middleware just before the static file middleware that rewrites the request path, but that breaks other middleware after the static file middleware (e.g. swagger, controllers, etc...).

Would appreciate some documentation for how to get asp.net working with localized angular applications in this article, or an example of such.

---
#### Feedback Bot on 9/17/2023, 06:46 PM: 

(private comment, text removed)
#### Feedback Bot on 9/25/2023, 10:11 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contactign us.

A few pointers:
* You can put `UseRouting` and `UseEndpoints` within `app.MapWhen` which will give you the ability to make the mapping you are looking for.
* You could potentially also use `MapFallbackToFile("{language:<<some-optional-constraint>>}/{**path:nonfile}")` to achieve the same results.
