### ISSUE TITLE
Blazor Web App template with global WebAssembly interactivity doesn't compile

### ISSUE THREAD

**Issue by tma-lawo** [dotnet/aspnetcore#51862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you create a new project with the Blazor Web App template with interactivity type set to WebAssembly and interactivity location set to Global, the project won't build.

The error:
<Project>\Pages\Error.razor(28,33,28,44): error CS0246: The type or namespace name 'HttpContext' could not be found (are you missing a using directive or an assembly reference?)

### Expected Behavior

The project builds without having to manually fix the error.

### Steps To Reproduce

Create a new project with the Blazor Web App template with interactivity type set to WebAssembly and interactivity location set to Global, then build.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

IDE: Version 17.8.0 Preview 6.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This has been fixed and the fix will ship in the upcoming 8.0 GA release.
