### ISSUE TITLE
Routing source generation for Native AOT not working well with generic constraints and nullable reference types

### ISSUE THREAD

**Issue by joaofbantunes** [dotnet/aspnetcore#51866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Building an API using .NET 8's Native AOT, I've encountered an issue when using generic constraints and nullable reference types, along with the services being injected. Here's a practical example.

Given the following interfaces:
```csharp
public interface IInputConstraint<TOutput>;

public interface IGenericService<TInput, TOutput> where TInput : IInputConstraint<TOutput>
{
    TOutput Get(TInput input);
}
```

With some concrete implementations:
```csharp
public record SomeInput(int Value) : IInputConstraint<string?>;

public class ConcreteService : IGenericService<SomeInput, string?>
{
    public string? Get(SomeInput input) => input.Value % 2 == 0 ? input.Value.ToString() : null;
}
```

Then registering and using this:
```csharp
builder.Services.AddSingleton<IGenericService<SomeInput, string?>, ConcreteService>();

// ...

app.MapGet("/", (IGenericService<SomeInput, string?> service) 
    => "Maybe? " + service.Get(new SomeInput(Random.Shared.Next())));
```

When building the API, an error occurs, indicating that in the `GeneratedRouteBuilderExtensions.g.cs` file, `SomeInput` cannot be used as a type parameter because nullability doesn't match the generic constraint.

Looking at the `GeneratedRouteBuilderExtensions.g.cs` file, we can see that its missing the question mark to denote the string nullability:
```csharp
var jsonBodyOrServiceTypeTuples = new (bool, Type)[] {
    (false, typeof(global::IGenericService<global::SomeInput, global::System.String>)),
};
```

### Expected Behavior

The generated source code matches the original code, and the application works normally.

### Steps To Reproduce

I created a simple example here: https://github.com/joaofbantunes/NativeAotVsNullableReferenceTypes

### Exceptions (if any)

Not really exception, but compiler error:

```sh
GeneratedRouteBuilderExtensions.g.cs(75,60): Error CS8631 : The type 'SomeInput' cannot be used as type parameter 'TInput' in the generic type or method 'IGenericService<TInput, TOutput>'. Nullability of type argument 'SomeInput' doesn't match constraint type 'IInputConstraint<string>'.
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: arm64
  Commit:       0b25e38ad3

.NET SDKs installed:
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by captainsafia** [comment]
@joaofbantunes Thanks for reporting this issue!

So, currently, we omit the nullability annotations on types that are provided as arguments to the `typeof` operator since it doesn't support NRTs. Our symbol name rendering logic is currently sophisticated enough to determine if the type that is provided is a generic type where the _arguments_ themselves are nullable. I'll have to see if there is some configuration of `SymbolDisplayFormat` that would allow us to support this.

**Comment by eerhardt** [comment]
Just an FYI - dotnet/runtime's source generators actually disable nullable warnings to avoid problems like this. See https://github.com/dotnet/runtime/pull/94267

* https://github.com/dotnet/runtime/blob/e13667af7543e915145e30aee394c60206d85750/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Emitter.cs#L42-L43
* https://github.com/dotnet/runtime/blob/e13667af7543e915145e30aee394c60206d85750/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L139-L140

**Comment by captainsafia** [comment]
> Just an FYI - dotnet/runtime's source generators actually disable nullable warnings to avoid problems like this. See https://github.com/dotnet/runtime/pull/94267

Yeah, the main reason that I avoided this in RDG is because we care about nullability for certain application behaviors. For example, we do nullability checks on the parameter types to determine if we should generate code that throws an exception on a per-request basis if a parameter isn't provided.

Perhaps the middle ground is to disable nullability using pragmas around certain lines of code instead of the entire file...

**Comment by eerhardt** [comment]
I'm not sure why disabling nullable warnings on the whole generated file would prevent us from doing nullability checks on the user's code and generating the necessary exceptions.
