### ISSUE TITLE
Hosted Blazor WebAssembly project only runs with environment set to "Development"

### ISSUE THREAD

**Issue by veertien** [dotnet/aspnetcore#51869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A basic hosted WebAssembly app only works with `ASPNETCORE_ENVIRONMENT`  set to **Development**. Changing the value to anything else causes the webassembly app to fail because it cannot load `/_framework/dotnet.js`

### Expected Behavior

The WebAssembly app starts ok without errors and and the value put in `ASPNETCORE_ENVIRONMENT` on the host is reflected in `IWebAssemblyHostEnvironment.Environment`

### Steps To Reproduce

Create a new project with:

```dotnet new blazor --interactivity WebAssembly```

On the server project, in  `launchSettings.json`, change `ASPNETCORE_ENVIRONMENT` to "Test"

run the project

### Exceptions (if any)

```
GET https://localhost:7036/_framework/dotnet.js net::ERR_ABORTED 404 (Not Found)
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

I am migrating my hosted Blazor WebAssembly project from dotnet 7 to dotnet 8-rc2 and the updated app gives **Production** for the `IWebAssemblyHostEnvironment.HostEnvironment` property while the host has `ASPNETCORE_ENVIRONMENT` set to **Development**.

In the dotnet 7 version the app picks up the `wwwroot/appsettings.Development.json` configuration as expected. I can also run the host project with `ASPNETCORE_ENVIRONMENT` set to `Test` and this leads to `wwwroot/appsettings.Test.json` being applied. I see that the `blazor.webassembly.js` file has the response header `Blazor-Environment` set appropriately. I do not see that header on the `_framework/blazor.web.js` of the dotnet8 version.

To migrate my project to dotnet 8-rc2, I copied  settings from the template generated by `dotnet new blazor --interactivity WebAssembly`. Trying to run that template with `ASPNETCORE_ENVIRONMENT` set to **Test** fails and now I am stuck.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The app has code that configures certain dependencies only for the `Development` environment. If you want to get the app working in a different environment, you should try to publish your application.
If, however, you want to actually do your development using some other environment name, that this is the same issue as https://github.com/dotnet/aspnetcore/issues/51883
