### ISSUE TITLE
Blazor Web App template created app NOT set up for server-side rendering of Razor components by default.

### ISSUE THREAD

**Issue by vnbaaij** [dotnet/aspnetcore#51873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `dotnet new blazor -o BlazorApp1`, you are supposed to get an app which uses SSR by default. However the resulting app uses Blazor Server for rendering. The result also includes the Counter page which should not be created in a SSR app.

This behavior is caused by line https://github.com/dotnet/aspnetcore/blob/a2536e6a4e384182825e89ee064115b5d841e97e/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/.template.config/template.json#L328 which sets the default for interactivity to 'Server' instead of 'None'. Changing the default results in an app with the correct behavior (and without the Counter page)

### Expected Behavior

An app set up for server-side rendering of Razor components by default.

### Steps To Reproduce

Run `dotnet new blazor -o BlazorApp1` and check the created output

### .NET Version

.NET 8 RC2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The default template will use both SSR as well as Server rendering (when the rendermode="InteractiveServer" is specified).
