### ISSUE TITLE
[.NET 8 Blazor] CascadingValue reset when navigating to client pages 

### ISSUE THREAD

**Issue by imranmomin** [dotnet/aspnetcore#51894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a `CascadingValue` at the root with `IsFixed = true`. While I navigate to the server pages the value does not changes and as soon as I navigate to the client pages the value reset to the default.

The value is only reset on the client pages and the server pages still show the correct value.

### Expected Behavior

The `CascadingValue` should not reset when navigating to the client pages

### Steps To Reproduce

Create a project with

```shell
dotnet new blazor --interactivity WebAssembly
```

Under `App.razor` wrap the `<Routes />` with the `<CascadingValue />` component 

```html
<CascadingValue Value="@_randomNumber" Name="RandomNumber" TValue="long" IsFixed="true">
    <Routes />
</CascadingValue>
```
```csharp
private readonly long _randomNumber = DateTime.Today.Ticks;
```

Now go to all the sample pages and accept the `CascadingValue`
```html
<p>Random number: @RandomNumber</p>
```
```csharp
[CascadingParameter(Name = "RandomNumber")]
private long RandomNumber { get; set; }
```
Run the application add navigate to each pages, as you navigate to the `/counter` you will notice the `RandomNumber` will reset in few seconds. If you navigate back to any server pages the value still exits, its only on the client pages the value has been reset.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

https://github.com/dotnet/aspnetcore/assets/6071075/882a7ea6-33fb-4f2f-b7e9-526a18eeeb83

[BlazorClientApp.zip](https://github.com/dotnet/aspnetcore/files/13267762/BlazorClientApp.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What you're experiencing here is the cascading value from the server was simply not transferred to the client, and hence, the client shows the default value, as it never received a value to set.

If you intend to transfer cascading values from server to client, you should persist that state using the PersistenComponentState type: https://learn.microsoft.com/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0#persist-prerendered-state

**Comment by imranmomin** [comment]
@mkArtakMSFT thank you for the clarification. 

But if you notice, on the initial page load the value is shown and then shortly after the value is being reset.

**Comment by imranmomin** [comment]
@mkArtakMSFT after implementing the `PersistenComponentState` below is my observation

- On initial page load the `RandomNumber` passed using `CascadingValueParameter`  is persisted and does not reset to default 
- After navigating to a different page and then coming back the `/counter` page it does not finds the value from `PersistenComponentState`

Am I missing something?
