### ISSUE TITLE
IWebHostEnvironment.Environment.ContentRootPath missing trailing \

### ISSUE THREAD

**Issue by joepperkins** [dotnet/aspnetcore#51897]
### Description

IWebHostEnvironment.Environment.ContentRootPath missing trailing \

### Configuration

Dot net core 7x
Windows

### Regression?

Dot net core 6x includes trailing \ in path from IWebHostEnvironment.Environment.ContentRootPath

### Other information

Workaround use Path.Combine

Path.Combine(this.Environment.ContentRootPath, $"wwwroot\\{somePath}");

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @joepperkins.
Do you observe this behavior in production or in development only?
