### ISSUE TITLE
Improvements to auth and identity in ASP.NET Core 8

### ISSUE THREAD

**Issue by plppp2001** [dotnet/aspnetcore#51906]
/register API endpoint currently only takes Email, PassWord. UserName was removed.  Will UserName be optional for the new Improvements to auth and identity in ASP.NET Core 8 API for SPA apps?

**Comment by bcheung4589** [comment]
No, the email is set as username in register.razor

https://github.com/bcheung4589/BlazorNET8_AutoRenderAuth/blob/4c43ddd7a21247ccfe1decbe09e91fa2c62af837/BlazorNET8_AutoRenderAuth/Components/Pages/Account/Register.razor#L118

**Comment by JeremyLikness** [comment]
There is not a plan to expose username in the identity APIs. It is still possible to expose an API backed by `SignInManager`/`UserManager` to accomplish this and we can consider this example for samples.
