### ISSUE TITLE
ASP.NET Core Web App (Model-View-Controller) targeting .NET 8 with Windows Identity Platform  fails after user login 

### ISSUE THREAD

**Issue by jpremill** [dotnet/aspnetcore#51913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When Creating a New  ASP.NET Core Web App (Model-View-Controller) 8 targeting .NET 8 with Windows Identity Platform and checking the allow graph api checkbox,  the application fails after the user is selected from the authentication user interface;
it throws the following error:

InvalidOperationException: Unable to resolve service for type 'Microsoft.Graph.GraphServiceClient' while attempting to activate '<project>.Controllers.HomeController'.

### Expected Behavior

a starter template should build and run as expected; when the user logs in as their user using the authentication interface, it should succeed and the rest of the application should load without error.

### Steps To Reproduce

1, Create new ASP.NET Core Web App (Model-View-Controller)  project targeting **.NET 8** with  authentication type set to **Windows Identity Platform**
2. following configuration prompts for azure integration to an app registration
3. check the enable Graph API permissions box.
4.  build and run the application.
5. Use  the Microsoft Authentication interface to perform the login action.
6. after the user is selected or the login is processed, the error is thrown.

### Exceptions (if any)

InvalidOperationException: Unable to resolve service for type 'Microsoft.Graph.GraphServiceClient' while attempting to activate '<project>.Controllers.HomeController'.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

The authenticaton guidance is extremely confusing.  Admittedly, the release of .net 8 isnt until next week, but the existing quickstarts for Microsoft Entra seem extremely outdated and do not seem to be applicable at all. Is there is an updated doc page I am just missing ? 

I'd really like to see a template project variation for the react  and asp.net that has a project with the server and a project with the react app in typescript that is setup so that the server does microsoft entra authentication for a react SPA.  Are there special preview templates somewhere ?

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this, @jpremill.
@vijaykrishnadongala do you own the WIP integration code that is being generated by VS? I feel like the issue here is that the service registration isn't being generated.

**Comment by Brettus-ntt** [comment]
I fixed the problem by changing the builder.Services.AddAuthentication in Program.cs.
 _**// Add services to the container.
            builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
                .AddInMemoryTokenCaches();**_

**Comment by mkArtakMSFT** [comment]
Thanks @Brettus-ntt.
@jpremill can you confirm if @Brettus-ntt 's suggestion works for you?
