### ISSUE TITLE
Add a simple TooManyRequestsResult to provided action object results

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet/aspnetcore#51915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

With scaled APIs, I need to consider more throttling scenarios. It will be nice to have an existing TooManyRequestsResult object - and potentially a factory method on ControllerBase class.

### Describe the solution you'd like

```csharp
public ActionResult SomeAction(){
    ...
    return TooManyRequests(message, TimeSpan.FromSeconds(5));   // 5 will be set on Retry-After header.
}
```

### Additional context

The custom implementation is not complex but needs to be done repeatedly for projects. For example:

```csharp
using System;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace Microsoft.ServiceProfiler.WebUtilities;

[DefaultStatusCode(DefaultStatusCode)]
public class TooManyRequestsResult : ObjectResult
{
    private const int DefaultStatusCode = StatusCodes.Status429TooManyRequests;
    private readonly TimeSpan _retryAfter;

    public TooManyRequestsResult([ActionResultObjectValue] object? value, TimeSpan retryAfter = default)
        : base(value)
    {
        _retryAfter = retryAfter;
    }

    public override void OnFormatting(ActionContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        base.OnFormatting(context);

        IHeaderDictionary responseHeaders = context.HttpContext.Response.Headers;
        if (_retryAfter != default && responseHeaders.RetryAfter.Count == 0)
        {
            responseHeaders.RetryAfter = new RetryConditionHeaderValue(_retryAfter).ToString();
        }
    }
}
```

And then an extension method on the ControllerBase.

**Comment by xiaomi7732** [comment]
Hi @captainsafia Thanks for the ask. Rate Limiting is great, but I think there are 2 limitations:

1. it is not there for .net 6 (I believe it was introduced in .NET 7).
2. it doesn't support relay 429 from **dependencies**.

For example, the API could go as fast as possible, but the DB might throttle:

![image](https://github.com/dotnet/aspnetcore/assets/3674549/dfd1dd3b-accc-47e9-9707-3e3690b21430)

In such a case, we would want to create a TooManyRequestResult with the `Retry-After` header forwarded and give it back to the client/browser.

On the side node: we could have forwarded the http-response from the db if we have one. But we might get an exception in our code (through the SDK) than an HttpResponse.

Does that make sense? Or is there anything I missed from how to use the rate limiting you mentioned?

**Comment by captainsafia** [comment]
> it is not there for .net 6 (I believe it was introduced in .NET 7).

Understandable, although admittedly, not the most compelling argument for bringing a new API, especially with .NET 6's support window ending soon.

> it doesn't support relay 429 from dependencies.

Ah, I see. Yes, AFAIK the rate-limiting middleware allows you to define rate-limits at the service layer but doesn't necessarily relay throttling info from the database. cc: @BrennanConroy in case I am wrong here

My inclination here is that this would require you to implement the relying of the throttle yourself which would require the types you are proposing here.

Typically for things like this, you can submit an API proposal for discussion with the wider team available at https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=.

**Comment by BrennanConroy** [comment]
> Ah, I see. Yes, AFAIK the rate-limiting middleware allows you to define rate-limits at the service layer but doesn't necessarily relay throttling info from the database. cc: @BrennanConroy in case I am wrong here

Middleware is typically for client to server requests. A server to backend service (database) does not interact with middleware directly.

There is an issue filed to allow users to consume more tokens/permits from the limiter in their own code, which could for example be used in this database example where the DB is returning a 429, so you could consume more tokens from the limiter after the fact to try throttling future requests.

Forwarding a backends 429 would be up to the user. If they get a 429 they can set 429 on the response (assuming they haven't written to it yet) and set a retry-after header just like your code above.

**Comment by captainsafia** [comment]
OK, that aligns with my understanding of things here.

Rate-limiting doesn't support forwarding 429s and that work is up to the user, which might merit making it a little bit easier by introducing a custom Result type.

@xiaomi7732 Can you update this issue with the API proposal template so we can discuss adding this new API?

**Comment by xiaomi7732** [comment]
Filed proposal: https://github.com/dotnet/aspnetcore/issues/52592.

**Comment by halter73** [comment]
Thank you for filing the proposal. We decided not to take it for now. It seems like a pretty advanced use case, and it doesn't take too much code to implement yourself.
