### ISSUE TITLE
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#51927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Saw the following exceptions in the VSCode debug console when running my asp.net core 7 application which connects to RDS:
```
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
```
What's the reason for this exception? It doesn't stop my application from running.

### Expected Behavior

No exception

### .NET Version

7.0.113

**Comment by martincostello** [comment]
If you configure Visual Studio [as described here](https://learn.microsoft.com/visualstudio/debugger/managing-exceptions-with-the-debugger) to break when that exception type is thrown, you will be able to inspect it in the debugger to get more context on what's happening and possibly why, as well as see a stack trace for where it's coming from.
