### ISSUE TITLE
[Blazor] Clarify the statement: Using an event callback parameter with @bind:after isn't supported.

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#51932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0) contain this statement:

> Using an event callback parameter (`[Parameter] public EventCallback<string> ValueChanged { get; set; }`) with `@bind:after` isn't supported.

How come these two things are related?

`EventCallback` parameter is what a component exposes to support binding/events. But `@bind:after` directive is intended for the usage by the parent component. I do not get how the former contradicts the latter one.

### Expected Behavior

Was the intent of the docs to say that one cannot have `@bind` directive with explicit event handling?

Something like this:
```
<input @bind="InputValue" @onchange="HandleChange"/>
```

### Anything else?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30960

**Comment by MariovanZeist** [comment]
In my understanding ``@bind:after`` was introduced to add the ability to execute code after the property designated by ``@bind`` was updated. People were trying to achieve that by creating special property setters, but ran into problems with for example asynchronous calls.
``@bind:after`` behind the scenes merely adds an additional call into the generated ``ValueChanged`` function to achieve this.  If ``@bind:after`` would have been an EventCallBack, then that would have resulted in calling StateHasChanged twice on the same component.

**Comment by mkArtakMSFT** [comment]
Thanks for answering this, @MariovanZeist!

Closing as there is no further action pending here.

**Comment by voroninp** [comment]
@MariovanZeist ,  thanks. I got it. I had to investigate `event handling` section first.

I didn't know `EventCallBack` field or property of the parent component can be used directly as event handler, so that note just says not to use such callbacks in `bind:after` directive.
