### ISSUE TITLE
Error using RenderModeInteractiveWebAssembly attribute in .NET Core 8 Blazor template project Webassembly

### ISSUE THREAD

**Issue by sukkergris** [dotnet/aspnetcore#51937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When changing the rendermode for eg. Weather.razor to interactive webassembly. This error is shown in the web console:
`
blazor.web.js:1  Error: One or more errors occurred. (Root component type 'LearningBlazor.Components.Pages.Weather' could not be found in the assembly 'LearningBlazor'.)
`

**The same is true when adding a new components to the Webassembly project.**

### Expected Behavior

No errors and an interactive component.

### Steps To Reproduce

Create a new blazor webassembly project

Change the render mode eg.:

@page "/weather"
@* @rendermode RenderMode.InteractiveWebAssembly *@
@attribute [RenderModeInteractiveWebAssembly]
<PageTitle>Weather</PageTitle>

<h1>Weather</h1>
`

### .NET Version

8.0.0-rc.2.23480.2

### Anything else?

Working if the component is placed in the [name].Client project.

Running on Windows 
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22631 Build 22631

Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.8.0 Preview 7.0

**Comment by sukkergris** [comment]
Moved to a project with "Interactivity location: Global"

**Comment by itsMatinDevs** [comment]
Any answers?
