### ISSUE TITLE
Blazor Identity Pages - Inifnite Redirect Loop when adding second external provider

### ISSUE THREAD

**Issue by FaeyUmbrea** [dotnet/aspnetcore#51950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the current (8.0-rc2) scaffold for the new Blazor Identity Pages trying to add another external login to an existing account results in an infinite redirect loop. 
The problem appears to be that the call to "RedirectManager.RedirectToCurrentPageWithStatus" does not purge the action from the redirect, causing "OnGetLinkLoginCallbackAsync" to repeatedly call itself, fail because there is no context, and loop back into itself until the user aborts. 
The backoffice tasks of adding the login actually works fine. 

### Expected Behavior

Being sent back to the page with what ever Status is given in the redirect.

### Steps To Reproduce

1) Create a Blazor Project with the new Blazor Identity Pages.
2) Add two external login providers.
3) Log in with one of them
4) Try to connect the other

### .NET Version

8.0.0-rc2

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up to our attention, @FaeyUmbrea.
@halter73 adding this to your list of issues to investigate - we may need to patch this.

**Comment by FaeyUmbrea** [comment]
For a temporary workaround people who find this issue can replace all instances of `RedirectManager.RedirectToCurrentPageWithStatus([message])` with `RedirectToWithStatus("/Account/Manage/ExternalLogins", [message])` in `Components/Pages/Account/Manage/ExternalLogins.razor`

**Comment by mkArtakMSFT** [comment]
This is fixed in 8.0 GA release.
