### ISSUE TITLE
Add perf benchmarks for Blazor Web scenarios

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#51971]
This issue tracks both defining the scenarios we'll need to onboard as well as actually onboarding all these.

**Comment by SPECIAL35** [comment]
???

**Comment by SteveSandersonMS** [comment]
We do have this one: https://github.com/aspnet/Benchmarks/blob/main/scenarios/blazor.benchmarks.yml

What others are required?

**Comment by MackinnonBuck** [comment]
Closing since we already have Blazor Web SSR tests. Using https://github.com/dotnet/aspnetcore/issues/29303 to track adding additional perf metrics for Blazor Web.
