### ISSUE TITLE
[Linux] After creating the Blazor Web App on Visual Studio Code, running it and clicking "Counters/Weather/Home" in the browser list on the left, cannot navigate to the target page.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspnetcore#51979]
**REGRESSION INFO:**
Not a Regression

**Platform**

- [ ]  Windows
- [ ]  macOS
- [x]  Linux

**INSTALL STEPS**

1. Clean machine: Linux OS Machine
2. Install VS Code from: [https://code.visualstudio.com/download](https://code.visualstudio.com/download)
3. Install the C# Dev Kit from: [C# Dev Kit - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit)
4. Install the .NET SDK 8.0.100
5. Apply NuGet Feeds

**Repro Steps**

1. Open VS Code, click Extension button > Install from VSIX… > select the downloaded "Green" file > Install
2. Type 'Ctrl+Shift+P' to open Command Palette > .NET New Project > click Blazor Web App to create a new project
3. Right-click the project > Build, then click Debug > Start New Instance
4. Click "Counter/Weather/Home"  in the browser list on the left

**ACTUAL**

Click "Counter/Weather/Home"  in the list on the left, it cannot navigate to the target page:
![image](https://github.com/dotnet/aspnetcore/assets/88425944/5a205708-5699-4b81-8766-47ac6d2fa4aa)

**EXPECTED**

It can automatically navigate to the target page

**Note**
1.This issue does not repro on the Blazor WASM Standalone project.
2.This issue does not repro on Linux arm64 machine.
3.After clicking "Counters/Weather/Home" in the list on the left, press refresh in the browser, it can navigate successfully.

**Comment by javiercn** [comment]
* Are there any errors in the browser console?
* Are there any errors on the vs code console log?
* Does it work if you run the app with `dotnet run` from the command line?

**Comment by v-polly** [comment]
> * Are there any errors in the browser console?
> * Are there any errors on the vs code console log?
> * Does it work if you run the app with `dotnet run` from the command line?

@javiercn, In response to your questions above, I did some research on Linux x64 machine with [VS Code](https://code.visualstudio.com/download) + [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit)[1.1.14].
> * When I click Debug > Launch New Instance and then click Counters/Weather in the browser, I cannot navigate to the target page and get some errors in the browser console.
![image](https://github.com/dotnet/aspnetcore/assets/88425944/1f9bfbe8-597a-4ea9-a9a4-b32058f4f210)
> *  If don't do anything or click Counter/Weather after just running, a warning message will appear in DEBUG CONSOLE:
`warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware: Warning: Failed to determine the https port for redirect.`
![image](https://github.com/dotnet/aspnetcore/assets/88425944/e9532ab9-4351-4606-86bb-08e31900ac22)

![image](https://github.com/dotnet/aspnetcore/assets/88425944/1b3e312b-4799-496d-8cb3-488009d8d19e)
     But in the OUTPUT console it appears to be working fine.
![image](https://github.com/dotnet/aspnetcore/assets/88425944/5cd46676-3dd6-477f-93ca-c265cff3be99)
> * Run the app with `dotnet run` from "Open In Integrated Terminal", the results are consistent with the above and cannot navigate to other page.
![image](https://github.com/dotnet/aspnetcore/assets/88425944/016a1c44-008a-4c63-899d-6cf95630bc12)

**Comment by javiercn** [comment]
@v-polly thanks for contacting us.

Can you clarify what version of Firefox are you using? 

The issue seems to be with the Browser/OS. TextDecoder is supported across all major browser versions and it's a requirement. 

Not sure what Browser and what version is in use, but add these two polyfill scripts to the head, to see if it works:
```
<script src="https://unpkg.com/browse/text-encoding-polyfill@0.6.7/lib/encoding.js" />
<script src="https://unpkg.com/browse/text-encoding-polyfill@0.6.7/lib/encoding-indexes.js" />
```

**Comment by v-polly** [comment]
@halter73 Thanks for your reminder.  The Firefox version that comes with our test machine is version 102.0. After we manually upgraded to the latest Firefox (version 120.0.1), this problem disappeared. Do you think this issue needs to be solved or won't fix?

**Comment by mkArtakMSFT** [comment]
Thanks for confirming. We're going to close this issue as there is no further action pending here.
