### ISSUE TITLE
Proposal solution for HostFilteringMiddleware issue connected to IOptionsManager OnChange method

### ISSUE THREAD

**Issue by charytech** [dotnet/aspnetcore#51970]
Proposal solution for #51960 is to reevaluate _allowAnyNonEmptyHost and _allowedHosts instead of resetting them to empty values.
https://github.com/dotnet/aspnetcore/blob/da1d588a9afe7d1ae5591b45265045abf270515e/src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs#L49-L55
The method will be similar to the already existing  "Configure()". 
https://github.com/dotnet/aspnetcore/blob/da1d588a9afe7d1ae5591b45265045abf270515e/src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs#L100-L123
We should also handle reseteting the _allowAnyNonEmptyHost state when it is not top level wildcard and allow _allowedHosts to be adjusted to empty values instead of throwing an exception.

**Comment by Tratcher** [comment]
Can you post this in https://github.com/dotnet/aspnetcore/issues/51960? We don't need a new issue for the proposal.

**Comment by charytech** [comment]
Sure no problem I added it.
I was folowing https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md
