### ISSUE TITLE
Blazor wasm PWA install button (for IOS / Android web app on home screen)

### ISSUE THREAD

**Issue by TDroogers** [dotnet/aspnetcore#51985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have searched, but it seems not possible to add an button to install my blazor wasm app as PWA on the smartphone home screen. Most people don't know where the install button is or how it works.
If this is not technically possible you probably got more connections / influence on Apple/Google to get them to implement this.

### Describe the solution you'd like

Install now button

**Comment by javiercn** [comment]
@TDroogers thanks for contacting us.

I believe you are looking for https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#triggering_the_install_prompt

**Comment by TDroogers** [comment]
Thanks, will like into that. Only 'This is not supported on iOS.' 😅
