### ISSUE TITLE
Program.cs is not called in Blazor Web App Client project (RC2)

### ISSUE THREAD

**Issue by sp00ky** [dotnet/aspnetcore#51986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Visual Studio Version 17.8.0 Preview 5.0 and .NET 8 RC2

1. Create a new Blazor Web App with Interactivity type of Auto (Server and WebAssembly).
2. Place a breakpoint somewhere in Program.cs in the **client** app.
3. Run the project.  
4. Navigate to the client-side counter page.  Not sure if this is necessary or if the project should be initialized when the server project is started.

The breakpoint is never hit.  Perhaps this is a debugger issue and the code is being run.  Or maybe I'm missing something about 
how this works in .NET 8.  

I first noticed this trying to add a HttpClient-based service to the DI container in the client Program.cs.  Using [Inject] in a RenderModeInteractiveAuto or RenderModeInteractiveWebAssembly page failed to provide the service.  I then put a breakpoint in Program.cs where Add[Scoped/Singleton/Transient] was being called and it never hit the breakpoint.  I then tried on a new project with the same results.

I'd add a github repo, but this is happening with File->New Project->Blazor Web App

### Expected Behavior

Placing a breakpoint in Program.cs in the client app should result in that breakpoint being hit.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by sp00ky** [comment]
This appears to be fixed in VS 17.8.0 Preview 7

**Comment by sWozzAres** [comment]
Sure I read somewhere a while back that this is a debugger issue. I don't think it's supposed to work. Program.cs still gets executed though.

**Comment by SvenBobrowski** [comment]
I had the same problem with the 17.8.0 release of VS 2022.
I added an example, where is simply try to inject an service instance in the program.cs of the client, but the code is never hit and the page in the counter.razor component is not rendering. 

An error "InvalidOperationException: Cannot provide a value for property 'appService' on type 'BlazorApp3.Client.Pages.Counter'. There is no registered service of type 'BlazorApp3.Client.Services.AppService'." occured on clicking Counter in the app menu.
[BlazorApp3.zip](https://github.com/dotnet/aspnetcore/files/13401283/BlazorApp3.zip)

Whats wrong?

**Comment by SIBUK** [comment]
I am having this exact same problem with the new final release of .net 8.0.0. My client program.cs just never gets executed and so whenever I click one of my links (which make calls to a server) I get the following error:

'InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.'

The reason being that the program.cs does not run and so this line never gets executed:

builder.Services.AddHttpClient("SiteBuddy.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

**Comment by javiercn** [comment]
@sp00ky thanks for the additional details.

Seems that this was only a bug in the preview.

For anyone else experiencing this problem, please **file a separate issue with a public github repo containing a repro project**.
