### ISSUE TITLE
blazor hybrid wpf, which supports blazor programs in the new wpf window, and routing   

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/aspnetcore#52003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

blazor hybrid wpf, which supports blazor programs in the new wpf window, and routing

 

### Describe the solution you'd like

Let's say I want to run the blazor program on another WPF form

a.wpf
```
 <blazor:BlazorWebView HostPage="wwwroot\index.html" Services="{DynamicResource services}">
     <blazor:BlazorWebView.RootComponents>
         <blazor:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
     </blazor:BlazorWebView.RootComponents>
 </blazor:BlazorWebView>
```
b.wpf

```
 <blazor:BlazorWebView HostPage="wwwroot\index.html" Services="{DynamicResource services}">
     <blazor:BlazorWebView.RootComponents>
         <blazor:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
     </blazor:BlazorWebView.RootComponents>
 </blazor:BlazorWebView>
```

```
 var b= new BWindow();
 b.Show();

```

I need to **b.wpf** open the default Route /admin page

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. This isn't a direction we're going to take the product at this time.

There are ways that this can be achieved without a framework feature - we recommend StackOverflow as a resource for getting help with this.
