### ISSUE TITLE
Duplicate Route Name

### ISSUE THREAD

**Issue by jakobkogler** [dotnet/aspnetcore#52008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AspNetCore already checks to some extend, if all route names are unique.
It's not allowed to have the same route name, but a different template.
E.g. see [ApplicationModelFactory.cs#L218C33-L250](https://github.com/dotnet/aspnetcore/blob/ae33890a62edb2fed5554efab597fb7fc41f8cbe/src/Mvc/Mvc.Core/src/ApplicationModels/ApplicationModelFactory.cs#L218C33-L250)

However, it is currently allowed to have the name for the same route when you use different HTTP Methods.
```csharp
public class HomeController : Controller
{
    [HttpGet("/method", Name = nameof(GetMethod))]
    public string GetMethod()
    {
        return "GET";
    }

    [HttpPost("/method", Name = nameof(GetMethod))]
    public string PostMethod()
    {
        return "POST";
    }
}
```

^ In that example, the application builds without any complains, even though both routes have the same name.

### Expected Behavior

I expect a build error, that complains about duplicate names.

### Steps To Reproduce

Minimal reproducable repo: https://github.com/jakobkogler/aspnetcore-duplicate-route-names/tree/main

### .NET Version

6.0.124

**Comment by javiercn** [comment]
@jakobkogler thanks for contacting us.

This is not something that we plan to do as it would preclude legitimate use cases.
