### ISSUE TITLE
Stuck in Blazor Training "Download the Blazing Pizza assets and starter files"

### ISSUE THREAD

**Issue by robertrackl** [dotnet/aspnetcore#52001]
As I go through the training steps in https://learn.microsoft.com/en-us/training/modules/interact-with-data-blazor-web-apps/3-exercise-create-user-interfaces-with-blazor-components I am stuck not being able to perform the steps under "Download the Blazing Pizza assets and starter files": I deleted the previously created BlazingPizza folder. In Visual Studio Core, terminal, I successfully performed step 2, cloning the BlazingPizza project again. When I do step 3, pressing F5, I am asked to select a debugger. I choose MS Edge. Then nothing more happens. I don't know what to do from here. Might it be an SDK problem again? This is what I have:
 --list-sdks
2.1.526 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.124 [C:\Program Files\dotnet\sdk]
7.0.403 [C:\Program Files\dotnet\sdk]
8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

Robert Rackl
r4

**Comment by javiercn** [comment]
@robertrackl thanks for contacting us.

@danroth27 can you help here?

**Comment by danroth27** [comment]
> When I do step 3, pressing F5, I am asked to select a debugger. I choose MS Edge. 

I think VSCode offers debuggers based on the current file that is open. Can you try opening a C# file and then running the app? You should see C# offered as a debugger.

Also, can you verify the app runs when you run `dotnet run` from the command line?
