### ISSUE TITLE
HttpContext could not be found

### ISSUE THREAD

**Issue by Gushus** [dotnet/aspnetcore#52029]
Steps to reproduce:

Template: Blazor Web App
- Framework: Net 8.0 (Preview)
- Authentication Type: none
- configure for https [x]
- interactivity type: WebAssembly
- Interactivity location: Global
- include sample pages [x]
- Do not use top-level statements []

Try to run --> The Type- or Namespace "HttpContext" could not be found (in Error.razor)

I hope this is somewhat helpful!
Best regards
Lukas

**Comment by javiercn** [comment]
@Gushus thanks for contacting us.

Is the Error page inside the `.Client` project?

**Comment by Gushus** [comment]
@javiercn Thanks for your reply!

Yes, the Error.razor is in the .Client Project. 
I just downloaded .net 8 rc2 and visual studio preview yesterday and noticed that error without doing anything. Where can I find the RTM?

but as you said the error is fixed I assume this issue can be closed too?

Best regards
Lukas

**Comment by javiercn** [comment]
@Gushus you can update Visual Studio to the latest version or download .NET 8.0 RMT from https://dotnet.microsoft.com/en-us/ which was released today.
