### ISSUE TITLE
[Blazor] Recommended actions for upgrading across major Blazor versions

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#52022]
# Dealing with HTTP Caching Issues When Upgrading Blazor Applications Across Major Versions

When Blazor applications are incorrectly upgraded or configured, it can result in non-seamless upgrades for existing users. This article discusses some of the common HTTP caching issues that can occur when upgrading Blazor applications across major versions. It also provides some recommended actions to ensure a smooth transition for your users.

There are several common causes that can negatively impact the upgrade experience for your users. These include:
* Incorrectly handling project and package updates: This can happen if you don't update all projects in your app to use the same major framework version or if you use packages from a previous version when a newer version is available as part of the major upgrade.
* Incorrectly configuring caching headers: These headers control how, where, and for how long your responses are cached. If they’re not configured correctly, users might receive outdated or stale content.
* Incorrectly configuring other layers like CDNs: Content Delivery Networks (CDNs) are another layer that can cause issues if not configured correctly. CDNs are designed to cache and deliver content to improve performance and reduce latency. However, if a CDN is incorrectly serving cached versions of assets, it can lead to stale or outdated content being delivered to the user.

## Detecting and diagnosing upgrade issues

Upgrade issues typically appear as a failure to start the application in the browser. Normally, there is a complaint about a stale asset or an asset that was not found or that it is inconsistent.

* First, check if the application loads succesfully within a clean browser instance (InPrivate window), if it doesn't, it likely points out to an issue with the application itself, where one or more packages/framework have not been correctly updated.
* If the application loads correctly in a clean browser instance, then it's likely that the application is being served from a stale cache. In most cases, a hard browser refresh (CTRL+F5) will cause the cache to be flushed nd for the app to work.
* If that is still not the case, then it's likely that the application is being served from a stale CDN cache. In this case, you can try to flushing the DNS cache via whatever mechanism your specific provider offers.

## Recommended actions before an upgrade

You migth be in a situation where the way your app was served to customers in the past will make the update process harder (for example, if you didn't or used incorrect caching headers). In this case, you can take some actions to mitigate this issue and make the upgrade process easier for your users. The recommended actions are listed below in order of preference:

### 1. Align Framework Packages with the Framework Version

Ensure that all framework packages line up with the framework version. Using packages from a previous version when a newer version is available as part of the major upgrade can lead to compatibility issues. It's also important to ensure that all your projects use the same major framework version. This consistency helps to avoid unexpected behavior or errors.

### 2. Verify the Presence of Correct Caching Headers

The right caching headers should be present on responses to resources. This includes `ETag`, `Cache-Control`, and others. The configuration of these headers is dependent on your hosting/server of choice. They are particularly important for assets like `blazor.webassembly.js` and anything it downloads. 

If you are using a service worker, it might also be impacted by these headers. Service workers rely on HTTP caching headers to manage cached resources effectively. Therefore, incorrect or missing headers can disrupt the service worker's functionality.

### 3. Use Clear-Site-Data to Delete State in the Browser

Consider using `Clear-Site-Data` to delete state in the browser. This might include "cache" and optionally "storage" to free up local storage caches. However, be aware that this might be a destructive action that could remove important information from the client storage if your app is using that. 

Using "cache" should be enough as it should only impact the browser HTTP cache. This action can help to ensure that the browser fetches the latest resources from the server, rather than serving outdated content from the cache.

### 4. Append a Query String to the _framework/blazor.webassembly.js Script Tag

If none of the recommended actions above are possible or apply, consider temporarily appending a query string to the `_framework/blazor.webassembly.js` script tag. This action should be enough in most situations to force the browser to bypass the local HTTP cache and download a new version. 

While future Blazor versions might provide better solutions for dealing with these caching issues, it's ultimately up to the app to correctly configure caching. Proper caching configuration ensures that your users always have the most up-to-date version of your application, improving their experience and reducing the likelihood of encountering errors.

**Comment by javiercn** [comment]
@guardrex

**Comment by guardrex** [comment]
This is live now at ...

https://learn.microsoft.com/aspnet/core/blazor/caching-issues?view=aspnetcore-8.0

@javiercn ... Can you check the last remark and example at ...

https://learn.microsoft.com/aspnet/core/blazor/caching-issues?view=aspnetcore-8.0#append-a-query-string-to-the-blazor-script-tag

... where I wrote that it's ok to make the query string persistent with some dev app versioning scheme, such as versioning the release each time in concert with the .NET release. I gleaned that from something that you wrote to a dev in a PU issue, and I think you have a tracking issue, possibly for .NET 9, to consider a framework feature like that.

If that's incorrect, I'll knock it out 🔪 on a patch PR, leaving just the bit about a temporary QS.

**Comment by guardrex** [comment]
One more ❓ ... your article makes repeated reference to Blazor WASM (i.e., when it mentions the Blazor script tag). I'm a bit concerned that readers will be confused about that. Should the article make it clear at the top that it applies to Blazor Server/Blazor Web app and Blazor WASM ***-OR-*** that it only applies to Blazor WASM apps?

**Comment by owacoder** [comment]
@guardrex - The URL to the ASP.NET Core article is changed, it is now found here instead: [https://learn.microsoft.com/en-us/aspnet/core/blazor/http-caching-issues?view=aspnetcore-8.0](https://learn.microsoft.com/en-us/aspnet/core/blazor/http-caching-issues?view=aspnetcore-8.0)

**Comment by psimsa** [comment]
With the original post in mind, wouldn't the easiest solution be to add a hash to file names (like react does, for instance) on publish? Or at least add a hash to blazor.webassembly.js on build...? In Nuke, the following snippet seems to do the job (though not fully proof-tested):
```csharp
    Target HashBlazorBootstrapFileName => _=> _
    .DependsOn(DotnetPublish)
        .Executes(() =>
        {
            var blazorBootstrapFile = ArtifactsDirectory / "wwwroot" / "_framework" / "blazor.webassembly.js";
            
            var hashBytes = MD5.HashData(blazorBootstrapFile.ReadAllBytes());
            var hash = Convert.ToHexString(hashBytes).ToLower();

            var hashedFile = ArtifactsDirectory / "wwwroot" / "_framework" / $"blazor.webassembly.{hash}.js";
            FileSystemTasks.MoveFile(blazorBootstrapFile, hashedFile, FileExistsPolicy.Overwrite);

            var indexHtmlFile = ArtifactsDirectory / "wwwroot" / "index.html";
            var indexHtml = indexHtmlFile.ReadAllText();
            indexHtml = indexHtml.Replace("blazor.webassembly.js", $"blazor.webassembly.{hash}.js");
            indexHtmlFile.WriteAllText(indexHtml);
        });
```

**Comment by javiercn** [comment]
Closing this issue as this is handled out of the box in 9.0 with the fingerprinting work that we did.
