### ISSUE TITLE
Kestrel HTTP/2 Timeout Behavior in Debugging Sessions is Problematic

### ISSUE THREAD

**Issue by jhigh2000** [dotnet/aspnetcore#52031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Kestrel with HTTP/2 protocol enabled in a debugging session (hitting at a breakpoint in razor pages or MVC project), timeouts are not well-behaved. The problem occurs when additional HTTP requests, such as those triggered by AJAX requests in the layout page, are sent. These requests timeout at around the 2-minute mark, leading to a broken page (standard chromium ERR_TIMED_OUT/page is taking too long page). The browser then retries the requests, introducing additional threads being debugged. This makes debugging more challenging as the execution jumps around unpredictably due multiple threads.

Additional Information:

The issue does not occur when Kestrel is configured to use HTTP/1.1 only.
The issue does not occur when using the IIS Express launch profile.

### Expected Behavior

Requests should not timeout prematurely during debugging sessions, and the debugging experience should remain stable even with additional HTTP requests.

### Steps To Reproduce

* Configure Kestrel to use HTTP/2 protocol (default)
* Start a debugging session.
* Trigger additional HTTP requests, for example, through AJAX requests.

### .NET Version

7.0.x, 8.0.x

### Anything else?

Tested with VS 17.8 previews and 17.7.6 on Windows 11

**Comment by amcasey** [comment]
Are you seeing messages in the kestrel logs when these timeouts occur?  It would be helpful to know which limit is being hit.  A lot of timeouts are essentially ignored when a debugger is attached, but it sounds like at least one is not.  A log message would help identify which timeout needs to be changed and confirm that it's a server-side timeout, rather than a client-side timeout.

**Comment by amcasey** [comment]
Alternatively, providing a sample project that exhibits this behavior would be very helpful.

**Comment by jhigh2000** [comment]
I created a minimal repro that exhibits the behavior described above: [https://github.com/jhigh2000/TimeoutMinimalRepro](https://github.com/jhigh2000/TimeoutMinimalRepro)

This is a File..New Project...razor pages application with the following small modifications.

The `Index.cshtml.cs` has an additional handler that will be called via an ajax request.

```c#
public IActionResult OnGetAjaxRequest() => Content("hello from server");
```

The `_Layout.cshtml` has the following script section in that triggers an ajax request after 60 seconds (the implementation details  aren't important, we just need something to trigger a request when we are in the middle of a debugging session and paused on a breakpoint)

```js
<script>
    $(function () {

        var secondsElapsed = 0;
        var intervalId;

        $(document).ajaxStart(function () {
            console.log('AJAX request starting...');
        });

        // Simulate an ajax request that would update the UI, etc
        setTimeout(function () {
            $.ajax({
                url: '/Index?handler=ajaxRequest',
                type: 'GET',
                cache: false,
                success: function (data) {
                    console.log('AJAX request successful:', data);
                },
                error: function (xhr, status, error) {
                    console.error('AJAX request failed:', status, error);
                }
            });
        }, 60000); // wait 60 seconds, then trigger the AJAX request
    });
</script>
```

The `Private.cshtml.cs` page has a dummy breakpoint

```csharp
 public void OnGet()
 {
     // set a breakpoint here and wait to simulate a long debug session
     var s0 = 0;
 }
```


### To trigger the behavior, set a breakpoint in `Privacy.cshtml.cs`

<img width="522" alt="image" src="https://github.com/dotnet/aspnetcore/assets/138398/37251c06-5e1c-4d23-89a1-370158508e5b">

### Run the project with Kestrel configured to use HTTP/2 (which should be the default).

<img width="822" alt="image" src="https://github.com/dotnet/aspnetcore/assets/138398/01335755-5e08-433d-8b6c-4dc719805236">

### Click Privacy in the header, hit the breakpoint and wait for the timeout and retries

![timeout](https://github.com/dotnet/aspnetcore/assets/138398/6849c83e-94bb-4719-8731-422efc76ad30)


### For the expected/correct behavior, force Kestrel to HTTP/1.1 in `appsettings.json`

```json
 "Kestrel": {
   "EndpointDefaults": {
     "Protocols": "Http1"
   }
 }
```

<img width="242" alt="image" src="https://github.com/dotnet/aspnetcore/assets/138398/b86014cd-5db3-47f4-a31b-99dec4ba0516">

Repeat the steps above to run the application and observe that there are no timeout issues.

**Comment by amcasey** [comment]
I'd like to confirm I'm understanding what I'm seeing correctly.  The timeout is on the client side, right?  It's either the browser or jquery?  I've been looking at wireshark traces and it definitely seems like the client sends the `GOAWAY`.  I also don't see anything in the server logs about timing out or disconnecting after continuing execution (though it does promptly freak out about the connection being closed).

**Comment by jhigh2000** [comment]
It does indeed seem like it's the browser as I have not been able to capture anything useful from the server logs either. The only thing that led me to anything server related is the different behavior when kestrel uses HTTP/1.1 vs HTTP/2, and when you use IIS Express (which also works correctly, no timeouts, even with HTTP/2).

**Comment by amcasey** [comment]
I wonder if IIS can continue to respond to ping frames while paused in the debugger (e.g. because the aspnetcore module is running out-of-proc).

**Comment by jhigh2000** [comment]
> I wonder if IIS can continue to respond to ping frames while paused in the debugger (e.g. because the aspnetcore module is running out-of-proc).
> 
> Edit: from wireshark, looks like IIS is able to keep responding to TCP keep-alives.

Interesting, I didn't know that - the IIS profile runs the ANCM module out of process? I always thought it was in-proc.

**Comment by amcasey** [comment]
I believe it [supports](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-8.0) [both](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/out-of-process-hosting?view=aspnetcore-8.0) though, in my local tests, it's actually in-proc.  I'm told we're probably getting an assist from some kernel support in windows (which isn't paused by the debugger).

**Comment by amcasey** [comment]
And yet kestrel appears to respond to keep-alives with HTTP/1.1...

So I'm missing _something_.

**Comment by jhigh2000** [comment]
> And yet kestrel appears to respond to keep-alives with HTTP/1.1...
> 
> So I'm missing _something_.

Yep, it was driving me crazy too!

**Comment by amcasey** [comment]
Okay, IIS handles HTTP/2 ping in the kernel, whereas Kestrel handles it in-proc (which is frozen).  The browser sends a GOAWAY citing "failed ping" when it doesn't hear back.  HTTP/1.1 doesn't use PINGs and both IIS and Kestrel handle TCP KEEP-ALIVE in the kernel.  That's why one of the four scenarios is different.  Unfortunately, there's nothing we can do about it.

**Comment by jhigh2000** [comment]
Thanks for getting to the bottom of it! So it sounds like the only option left would be to add some guidance to the docs? If someone encounters timeouts during debugging, then either force HTTP/1.1 or use IIS Express (if on Windows)?

For Kestrel, is forcing HTTP/1.1 env/appsettings/user secrets, etc the best way to handle this?

**Comment by Tratcher** [comment]
For now, yes. We'll talk to the tooling folks to see if we can find a way to make this experience better. @samsp-msft

**Comment by samsp-msft** [comment]
We talked to the tooling folks. They don't have the ability to only pause the thread for one worker. The debugger is designed around expecting the entire process to be paused when at a breakpoint. If some parts are running, and some are not, it will cause problems with GC, expression evaluation, and and cross-thread work is likely to hit some nasty deadlocks etc.

**Comment by adityamandaleeka** [comment]
Closing since it sounds like there's not much we can do for this one.
