### ISSUE TITLE
[Announcement] ASP.NET Core in .NET 8 is now available!

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#52046]
Hello all,

Today, we released .NET 8, which includes lots of exciting new features and updates in ASP.NET Core - you can read all about it in our [blog post](https://devblogs.microsoft.com/dotnet/announcing-asp-net-core-in-dotnet-8/)! We'd specifically like to thank all of you for your great & numerous community contributions during the .NET 8 cycle - whether that be PRs, community triage, feature suggestions, or bug reports, our wonderful community is instrumental in helping us deliver a great product.

You can find direct links to download .NET 8 [here](https://dotnet.microsoft.com/en-us/download).

Happy coding!

**Comment by diegosasw** [comment]
There have been breaking changes in `AddJwtBearer` and the `JwtBearerOptions` and I can't find any documentation about it. Is there any relevant link?

More specifically, the `ValidateIssuerSigningKey` set to `false` along with the `TokenValidationParameters.SignatureValidator = (token, _) => new JwtSecurityToken(token); // mock to bypass validation` behaves differently just by upgrading from .NET 7 to .NET8

**Comment by martincostello** [comment]
The specific change referenced doesn't seem to be documented, but the change in the associated issue is related to changes in the [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x) repository for version 7, which ASP.NET Core 8 depends on. I had to make the relevant change to use `JsonWebToken` when updating System.IdentityModel.Tokens.Jwt to `7.0.0-preview` and later.

**Comment by stefannikolei** [comment]
All be aware that using 'JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();;' does probably not work after upgrading to .net8. 'JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear();' should be used.

This change could have been documented better.

**Comment by blogcraft** [comment]
Is there any known issues with error c0000005 in Windows AppService using .NET 8? I can't get my app to run. The same app in Linux App Service runs without problem.

**Comment by zaneclaes** [comment]
Major regressions in the final version; some of us can't even start our app we had built on RC1/RC2: https://github.com/dotnet/aspnetcore/issues/52190
