### ISSUE TITLE
Cannot resolve symbol 'RenderModeInteractiveServer'

### ISSUE THREAD

**Issue by byte-0x74** [dotnet/aspnetcore#52048]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After upgrading to .NET SDK 8.0.100 from 8.0.100-rc.2
`@attribute [RenderModeInteractiveServer]` gives error Cannot resolve symbol 'RenderModeInteractiveServer'

I also tried to create whole new Blazor app project and there `@rendermode InteractiveServer` gives error  Cannot resolve symbol 'rendermode'

### Expected Behavior

Not to give any error

### .NET Version

8.0.100

### Anything else?

ASP.NET Core: 8.0.0
IDE: Jetbrains Rider 2023.3 EAP6

`dotnet --info` otuput:

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

**Comment by Ayymoss** [comment]
Similar problem: https://github.com/dotnet/aspnetcore/issues/52051

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Does your project build without errors when you do so via the command line (`dotnet build`)?

**Comment by LoranKloeze** [comment]
I have this problem as well. But to be clear: dotnet compiles the solution just fine when you use `@rendermode InteractiveServer`. 

**The problem lies with Jetbrains.** They have to release an update for Rider. I reckon they will release it soon.

Check JetBrains issue tracker for some more info on supporting .NET 8: https://youtrack.jetbrains.com/issue/RIDER-89989/Support-for-.NET-8

**Comment by bartvanhoey** [comment]
at **@using static Microsoft.AspNetCore.Components.Web.RenderMode** to _**imports.razor**  file

instead of **@attribute [RenderModeInteractiveServer]**  use **@rendermode InteractiveServer**

**Comment by bdaunt99** [comment]
You also have to add this to your _Imports.razor
@using static Microsoft.AspNetCore.Components.Web.RenderMode

**Comment by byte-0x74** [comment]
> Thanks for reaching out. Does your project build without errors when you do so via the command line (`dotnet build`)?

Yeah it builds normally when using dotnet build. seems to be problem in rider as loran said
