### ISSUE TITLE
Cannot use Razor Pages within .NET Blazor Web App

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#52068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a fresh new .NET 8 Blazor Web App I've added a subfolder `Account` with contains `/Login2.cshtml` within the `Components` folder. And I created a `Pages` folder in the root of the project with contains `Account/Login.cshtml`

Within my `Program.cs` I've added 
```csharp
builder.Services.AddRazorPages();
```

However both `/Account/Login` & `/Account/Login2` cannot be found by the router.

Even configure it as 
```csharp
builder.Services.AddRazorPages().WithRazorPagesRoot("/Components");
```
or
```csharp
builder.Services.AddRazorPages().WithRazorPagesRoot("/Components/Pages");
```

doesn't help me.

### Expected Behavior

Either Login or Login2 should be displayed.

### Steps To Reproduce

I created this small sample project
https://github.com/MarvinKlein1508/RazorPagesTest

### .NET Version

.NET 8

**Comment by MarvinKlein1508** [comment]
Maybe you are wondering why I need to use razor pages in the first place:

Because I use claims based authentification in my other app, I'll need to be able to call `HttpContext.SignInAsync` which is not possible witz razor components as far as I know.

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

Are you able to make it work if you remove Blazor from the app entirely (and add it later?) or in other words, can you get it to work in the way you want without Blazor being in the picture?

**Comment by MarvinKlein1508** [comment]
@javiercn I spent some time with this now. It turns out there is more configuration required in `Program.cs`

This is my `Program.cs` from .NET 7 Blazor Server app.

```csharp
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;

// Add services to the container.

builder.Services.AddRazorPages();

builder.Services.AddServerSideBlazor()
    .AddCircuitOptions(options => { options.DetailedErrors = true; });
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
               .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme);
builder.Services.AddControllers();

var app = builder.Build();


// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();


app.MapControllers();
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
```

In .NET 8 with Blazor Web App Template this needs to be changed to:
```csharp
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddRazorPages().WithRazorPagesRoot("/Components/Pages");

builder.Services.AddServerSideBlazor()
    .AddCircuitOptions(options => { options.DetailedErrors = true; });

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
               .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme);

builder.Services.AddControllers();

// Add services to the container.


var app = builder.Build();


// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseRouting();
app.UseAntiforgery();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapRazorPages();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
```

The two important parts here are:
```csharp
builder.Services.AddRazorPages().WithRazorPagesRoot("/Components/Pages");
```

Because the `Pages` folder has been moved into the `Components` folder you'll either need to specify the root for the new place, or move the `Pages` folder back to root level of the project.

For some reason this isn't enough though. In the Blazor Web App Template you explicity need to call:
```csharp
app.MapRazorPages();
```

otherwise the pages won't be reachable. Not sure though why I haven't to use this line in .NET 7 Blazor Server app.

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for the additional details.

Yes, `MapRazorPages` is required, as "Component Pages" are completely different from traditional pages. I am the first one to acknowledge how confusing this is.

Seems that once you do `app.MapRazorPages()` things work as expected.
