### ISSUE TITLE
Analyzer: ASP0023 Ambiguous route warning when targeting .NET 8 and using [action]

### ISSUE THREAD

**Issue by mahdib619** [dotnet/aspnetcore#52066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

False warning of ambiguous route when using [action] in controller route.

```
    [HttpGet("[action]/{name}")]
    public async Task<ActionResult<IReadOnlyCollection<ProductReadDto>>> GetProductByName(string name)
    {
    }

    [HttpGet("[action]/{category}")]
    public async Task<ActionResult<IReadOnlyCollection<ProductReadDto>>> GetProductByCategory(string category)
    {
    }
```

### Expected Behavior

Should not warn because it evaluates to different routes.

### .NET Version

8.0.100

**Comment by martincostello** [comment]
Duplicate of #49777 which has been fixed for the next servicing release.
