### ISSUE TITLE
Blazor InputRadio is broken by IHandleEvent

### ISSUE THREAD

**Issue by plastovicka** [dotnet/aspnetcore#52069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a Blazor page implements IHandleEvent to optimize rendering speed according to performance best practices, then all input radios are broken. After a radio button is clicked, it is instantly rendered back to its previous state. Then it looks like the value was not changed. The problem started after upgrade to .Net 8.

### Expected Behavior

It worked in .Net 7.

### Steps To Reproduce

```
@page "/"
@implements IHandleEvent

<InputRadioGroup @bind-Value="n">
  <InputRadio Value="0" />
  <InputRadio Value="1" />
</InputRadioGroup>

@code {
  int n;

  Task IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, object? arg) => callback.InvokeAsync(arg);
}
```

### .NET Version

8.0.100

**Comment by javiercn** [comment]
I've tracked down the source of the issue to 4e0c598110f in InputRadio.cs

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/53245
