### ISSUE TITLE
Add an inputRange component like the basic inputNumber components

### ISSUE THREAD

**Issue by jcreach** [dotnet/aspnetcore#52067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm building a form in blazor in which I use simple components like `inputText` and `inputNumber`, but I need an input of type range and I haven't found it in the framework.

### Describe the solution you'd like

I'd like this component to be added. I can propose a first version because I've started to prototype it for the needs of my project based on the `inputNumber` component.

**Summary comment**: https://github.com/dotnet/aspnetcore/issues/52067#issuecomment-1812840071

**Comment by SteveSandersonMS** [comment]
I think `<InputNumber type="range" ... />` works for this purpose. Can you try this and let us know if something seems missing?

**Comment by jcreach** [comment]
Thanks for your reply. I've just tried again and it doesn't work, the range type isn't taken into account...

Here is my code:
```html
<label for="range">Range : </label>
<InputNumber type="range" @bind-Value="data.Range" />
<p>@data.Range</p>
``` 

Here is the result:

![image](https://github.com/dotnet/aspnetcore/assets/57401121/c0f63c88-b593-4e26-ad76-cee0dda1fd01)

**Comment by SteveSandersonMS** [comment]
Ah right yes, I see. I was thinking of `<input type="range" @bind="data.Range" />`, which does work.

So I think this is a valid feature request, but it might be that we'd achieve it by making `<InputNumber type="range">` work. It looks like that would be a one-line change, i.e., swapping the order of these two lines:

https://github.com/dotnet/aspnetcore/blob/5478946653b8c4aaf67842a4cf80bc5e48acee63/src/Components/Web/src/Forms/InputNumber.cs#L56-L57

**Comment by jcreach** [comment]
@MackinnonBuck Yes, of course I want to make the changes

**Comment by divyeshio** [comment]
Hi, I would like to contribute to this. Can someone please assign this issue to me?
Based on [this](https://github.com/dotnet/aspnetcore/pull/52747#issuecomment-1938849747) comment, I managed to write an E2E test for it but for Unit test how do I access "type" attribute after `await InputRenderer.RenderAndGetComponent()` [here](https://github.com/dotnet/aspnetcore/blob/002b186d22a162fce4fc3faea17a8d7f3db74541/src/Components/Web/test/Forms/InputNumberTest.cs#L46).

Do we need something like `InputDateType` and a field like [this](https://github.com/dotnet/aspnetcore/blob/5478946653b8c4aaf67842a4cf80bc5e48acee63/src/Components/Web/src/Forms/InputDate.cs#L35)?
