### ISSUE TITLE
Blazor.web.js broke since official .NET 8

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#52074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting the below error in the browser. I tried to fix the target SDK version to `8.0.100-rc.2.23502.2` to deploy with until Azure supports the newest official one.

Unfortunately, there seem to be breaking changes for Blazor?

### Expected Behavior

Not error.

### Steps To Reproduce

Use GitHub actions to deploy .NET 8 RC2 projects to Azure App Service. Using below `global.json`:

``` json

﻿{
  "sdk": {
    "version": "8.0.100-rc.2.23502.2"
  }
}

```

### Exceptions (if any)

In the browser on https://www.kiss-code.com/

```

Error: AggregateException_ctor_DefaultMessage (DeserializeUnableToConvertValue, Microsoft.AspNetCore.Components.RootComponentOperation[] Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
    at Jn (dotnet.runtime.8.0.0-rc.2.23479.6.xcxvlefo8t.js:3:31627)
    at Ul (dotnet.runtime.8.0.0-rc.2.23479.6.xcxvlefo8t.js:3:181804)
    at 00b1e352:0x1faca
    at 00b1e352:0x1bf8b
    at 00b1e352:0xf172
    at 00b1e352:0x1e7e4
    at 00b1e352:0x1efda
    at 00b1e352:0xcfec
    at 00b1e352:0x440ad
    at e.<computed> (dotnet.runtime.8.0.0-rc.2.23479.6.xcxvlefo8t.js:3:214844)

```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Suggestions are welcome.

**Comment by javiercn** [comment]
@augustevn thanks for contacting us.

Does it reproduce on an inprivate browser window?

**Comment by SteveSandersonMS** [comment]
Also, do you still get this error if you create a new project using the RTM template? If the RTM template works, perhaps there is some additional upgrade step that you need to apply to your older project.

**Comment by augustevn** [comment]
Thanks for replying so quickly. I'm not trying to upgrade anything, I wanted to make sure my GitHub pipelines and Azure App Service would look at the `global.json` file using my current SDK version (8.0.100-rc.2.23502.2) when building or deploying to not risk encountering breaking changes.

Yet, the browser give me that. What is RTM? The official .NET 8 release?

I've got it on tape: [About global.json](https://youtu.be/3o7i33Wc9bk?si=3oPxXFmNzMzp4hZQ)

I hoped to wait with upgrading until next week to make sure Azure supports it. In the meantime I just wanted to continue deploying the RC2 version.

**Comment by augustevn** [comment]
Thank you for the suggestions. I'm going experiment with those "rollForward" options, I tried with "latestPatch" but still not working. I'll experiment some more with "allowPrerelease" etc.

Goodluck with .NET conf! Rocking it!

**Comment by augustevn** [comment]
@rogihee I assumed something similar, I experimented with trying to match the exact Blazor version, unfortunately that wasn't possible.

I've tried "latestFeature" indeed but that rolls me to the RTM while my packages are still at RC2 like you mention.
The point of using the global.json for me was stick with RC2,  to avoid going to RTM pre-maturely but if / when RTM is supported by Azure, I will upgrade.

"latestPatch", "latestMajor", ... nothing is working so far so upgrading it shall be.

**Comment by rogihee** [comment]
@augustevn : the General Settings tab still needs to be updated but you can install the RTM version of 8 via Kudu (Web App -> Advanced Tools -> Site Extensions):
![image](https://github.com/dotnet/aspnetcore/assets/4984486/38bacba7-4086-4025-bb6b-e6675a922904)

**Comment by augustevn** [comment]
@rogihee I've been looking for that when upgrading to RC2, unfortunately I don't think I can access it on a Linux Basic Tier App Service?

![image](https://github.com/dotnet/aspnetcore/assets/77939574/3f7eb0a9-1c99-4710-874d-a955f7270a6d)

**Comment by augustevn** [comment]
I upgraded from RC2 to RTM, Azure seems to support it. The rendering changed a bit tho, I'll explain in someone else's ticket.
I'll close this one, thanks for the help.
