### ISSUE TITLE
In WebAssembly pre-render false, is there a way to display a loading message while downloading the wasm files?

### ISSUE THREAD

**Issue by ricfwolff** [dotnet/aspnetcore#52076]
I'm creating a page that runs only on WebAssembly and I need to have pre-rendering disabled (by using RenderModeInteractiveWebAssembly(prerender: false)).

Is there a way to display the loading spinner (as we had on .net 7) or at least a "loading..." when the user navigates to this page? (while it's downloading the web assemblies)

**Comment by javiercn** [comment]
@ricfwolff thanks for contacting us.

We don't have the equivalent functionality in Blazor web, what you can do in this case is:
* Prerender a wrapper component that displays the placeholder on the page.
  * Inside the wrapper, render your component with prerender: false
* Have the wrapper use `@if(OsPlatform.IsBrowser()` to distinguish between SSR and WebAssembly

**Comment by achmstein** [comment]
When I try to enable prerender, I'm getting A second operation started in this context when using CustomUserClaimsPrincipalFactory? Is there any workaround or I need to disable prerending?

**Comment by SteveSandersonMS** [comment]
@achmstein That sounds unrelated to this issue. Could you file a new issue with full, minimal repro steps?

**Comment by achmstein** [comment]
@SteveSandersonMS  I found why this is happening and it's related to this issue https://github.com/dotnet/aspnetcore/issues/43687

**Comment by MackinnonBuck** [comment]
Dupe of #49056
