### ISSUE TITLE
Blazor Web App Router AdditionalAssemblies routes are forgotten on reload

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#52077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We setup our router to load routes from additional Assemblies like this:

```csharp
<Router AppAssembly="@typeof(Program).Assembly"
        AdditionalAssemblies="new[]
{
    typeof(TestModule.Test).Assembly,
}">
    <Found Context=" routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
</Router>
```

So bascially we are splitting pages into multiple projects and merge them back together into one project. The reason for this is that we can reuse the same object names in a capsulated environment so we don't need to create large object names like `MyModuleAction` instead we can create a class in each module called `Action` which is only available in the module itself.

This used to work fine in .NET 7 Blazor Server. It still works in .NET 8 Blazor Web App, however it is not fully working anymore.

When I navigate to the site contained in my module using links or `NavigationManager` then it works just fine. However I cannot reload the page in anyway. Doing so results in a black screen with error 404 in the console.

Perhaps there is more configuration for this required but I didn't find anything related to this in the breaking changes.

### Expected Behavior

I would expect this to work exactly like it did in .NET 7 on Blazor Server.

### Steps To Reproduce

I created this small sample project 
https://github.com/MarvinKlein1508/BlazorAdditionalAssemblies

### Exceptions (if any)

404 not found

### .NET Version

NET 8.0.0

**Comment by MarvinKlein1508** [comment]
Might be related to #49759

**Comment by MarvinKlein1508** [comment]
Might be related to https://github.com/dotnet/aspnetcore/issues/49759 or https://github.com/dotnet/aspnetcore/issues/48875 or https://github.com/dotnet/aspnetcore/issues/49313

**Comment by MarvinKlein1508** [comment]
Here is a small video showcasing the issue
https://github.com/dotnet/aspnetcore/assets/32510006/a24912d1-c49a-4946-813b-a1b26d01c8ed

**Comment by javiercn** [comment]
@MarvinKlein1508 need to add the assemblies to MapRazorComponents [here](https://github.com/MarvinKlein1508/BlazorAdditionalAssemblies/blob/master/BlazorApp12/Program.cs#L27)

**Comment by MarvinKlein1508** [comment]
@javiercn

When I specify it there it won't work until I also specify it within the Router itself.

**Comment by javiercn** [comment]
@MarvinKlein1508 Thanks for the additional details.

In essence it's because when the code runs on wasm we don't have any built-in knowledge about the assemblies that were declared on the server.

There are things we can do to improve this in the future (for example, we plan to implement automatic discovery at compile time) but it's not something that we have yet.
