### ISSUE TITLE
HealthChecks stoped to work on version 8.0

### ISSUE THREAD

**Issue by zimbres** [dotnet/aspnetcore#52087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrade project to 8.0, also Microsoft.Extensions.Diagnostics.HealthChecks to version 8.0, the HealthCheckPublisher is no longer called.

Using Microsoft.Extensions.Diagnostics.HealthChecks at version 7.0.14, even with project in version 8.0 works as expected.

### Expected Behavior

File "health" is create and HealthCheckPublisher is called on the timespan defined in HealthCheckPublisherOptions.

### Steps To Reproduce

[https://github.com/zimbres/HealthChecksTest](https://github.com/zimbres/HealthChecksTest)

### .NET Version

8.0.100

### Anything else?

https://github.com/dotnet/extensions/issues/4725

**Comment by Defstun** [comment]
We are also experiencing this issue. Health checks failing in kubernetes cluster.

**Comment by PavelRyazanov** [comment]
I have the same issue. I discovered that HealthCheckPublisherHostedService does not create timers until any IHealthCheck is registered. In this case I need to register exactly one dummy IHealthCheck.

**Comment by PavelRyazanov** [comment]
@zimbres You need add at least one health check

**Comment by zimbres** [comment]
@PavelRyazanov Thank you!

I end up adding just with `builder.Services.AddHealthChecks().AddCheck("Sample", () => HealthCheckResult.Healthy());` to get my publisher being called.
