### ISSUE TITLE
Blazor Server does not work after upgrade to .NET 8.0

### ISSUE THREAD

**Issue by Suchiman** [dotnet/aspnetcore#52095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an ASP.NET Core 7 app that mostly uses traditional MVC with razor views that utilizes blazor server on some subpaths.
After upgrading to .NET 8.0, by upgrading the TargetFramework and PackageReferences, not doing any code changes, the blazor pages stopped working correctly.

They pre-render correctly but are not interactive. I include them by having `<component type="typeof(App)" render-mode="ServerPrerendered" />` in a cshtml file at the subpath where blazor starts being used, e.g. https://app.tld/Admin hits an MVC controller that returns a View that includes said markup. If i change it from `ServerPrerendered` to `Server`, all i get is a white page.

I can see that a websocket connection for blazor is established but there's no error message in the browser console nor on the ASP.NET Core console window.
All the Browser console says is
```
[2023-11-15T18:41:50.278Z] Information: Normalizing '/_blazor' to 'https://localhost:44311/_blazor'. blazor.server.js:1
[2023-11-15T18:41:50.327Z] Information: WebSocket connected to wss://localhost:44311/_blazor.
```

If necessary, i can try to create a minimal project but if anyone knows off the top of their head what i'm doing wrong, that would be great.

### Expected Behavior

Blazor Server should just continue to work in .NET 8 as it did in .NET 7 per the upgrade guide https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio#update-a-blazor-server-app

### .NET Version

8.0.100

**Comment by augustevn** [comment]
Hi, I see you're using a lot of the old notations still (before .NET 8). `<component type="typeof(App)" render-mode="ServerPrerendered" />` should look more like `<Routes  @render-mode="InteractiveServer" />`

Also, `blazor.server.js` should look more like `blazor.web.js`. I suggest you start a new .NET 8 InteractiveServer project and look how it's done there, then copy over what's applicable.

Also, clean and rebuilding after major upgrades can do wonders for your project's interactivity.

**Comment by Suchiman** [comment]
@augustevn those are the steps to upgrade from a Blazor Server app to a Blazor Web App as outlined [here](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio#convert-a-blazor-server-app-into-a-blazor-web-app), which i'm trying to avoid for now since i don't see Blazor Web Apps being able to integrate as smoothly into MVC views as blazor server can. That same link however points out that 
![image](https://github.com/dotnet/aspnetcore/assets/7110884/e0683b85-fe3b-41e6-8bca-73d3c0c13055)

**Comment by christallire** [comment]
They forgot Identity migration.

**Comment by appsolab** [comment]
Mine with Identity doesn't work either after migration.

**Comment by javiercn** [comment]
@Suchiman I've you've just updated the libraries and TargetFramework, that should work. There are a few things to try:
* Use an in-private window.
* Turn server logging on to Debug.
* Turn webassembly logging on to Debug.

See if there are more logs. You should also be able to put a breakpoint on your component to see if it's rendering anything at all. You shouldn't change the script on the page (in case you did) It should still be "_framework/blazor.server.js"

**Comment by augustevn** [comment]
Yes, I'm also experiencing odd behavior, not re-rendering as expected. I'm not using the Blazor auth but I am doing similar things. I'm not seeing the correct RenderFragments after (local state) property updates. I'll experiment some more.

I went from .NET 8 RC2 to RTM without changing code, the above issue occurred. After going through the conversion steps, still the above issue.

I've noticed these types of render / behavior changes with most Blazor migrations.
I'll showcase in my next video: [.NET 8 RTM](https://youtu.be/vjKYS4AHF3Y).

**Comment by Suchiman** [comment]
Been sinking a few hours into investigating this closer. Took a look at the logs and saw it connecting and creating a circuit and then nothing for a while until the circuit got disposed because token expired 2 minutes later. Wanted to compare with .NET 7 so i've switched branches and then it suprisingly was broken there too.

Closing VS, cleaning everything the `git clean -xfd` way, etc. did not help. After a while i've figured that the webapp, that was definitively running from a `bin\Debug\net7.0` folder, was delivering the net8.0 version of the blazor.server.js. I've checked everything, browser caching disabled via devtools network tab and the asp.net core console output confirmed that `blazor.server.js` has been sent with 200 OK (not 304 not modified).

So i've manually retrieved the net7.0 version of blazor.server.js and put that in my wwwroot and used that instead of the `_framework` one. That fixed net7.0. Then i switched back to net8.0 and used the net7.0 `blazor.server.js` there as well. That made the non pre rendered version of blazor server also render again, although trying to click on buttons error'd with `No interop methods are registered for renderer 0` but that's to be expected i guess.

Digging around in the net8.0 version of `blazor.server.js`, it seems that the code that uses `const blazorCommentRegularExpression = new RegExp(/^\s*Blazor:[^{]*(?<descriptor>.*)$/);` to match the comments that the components generate never gets hit because it seems like it enumerates the head only, not the body. But that's all i could figure so far and now it's 3:30am so i'll have another look tomorrow

**Comment by augustevn** [comment]
@Suchiman I see what you mean & I'm you're having so much trouble.
I just upgrade a 66+ projects solution with 5 Blazor WASM hosted projects from .NET 6 to .NET 8 without doing the conversion. Everything still renders. Well done Microsoft!

I didn't expect that to go as smoothly since it didn't go smoothly between RC1, RC2 and RTM but that was understandably not the focus and was meant to break.

**Comment by Suchiman** [comment]
Waking up with a fresh head, i had an epiphany. I've moved this piece of code
```html
<script src="/_framework/blazor.server.js" autostart="false"></script>
<script>
    Blazor.start({
        configureSignalR: function (builder) {
            builder.withUrl("/_blazor", {
                skipNegotiation: true,
                transport: 1
            });
        }
    });
</script>
```
from the bottom of the `<head>` to just before the `</body>` and now it works again.

**Comment by javiercn** [comment]
@Suchiman yes, that would do it.

That's why we put it at the end of the file. You could have also done `deferred=true` on the script for the same effect, but essentially what's happening is that the script was loading too early.

**Comment by jonrmorgan99** [comment]
> @Suchiman yes, that would do it.
> 
> That's why we put it at the end of the file. You could have also done deferred=true on the script for the same effect, but essentially what's happening is that the script was loading too early.
> 

@javiercn I'm having similar startup problems with an app I migrated from Net7 Blazor server to Net8. I've been using

`<script src="/_framework/blazor.web.js" autostart="false"></script>`

in my Net8 App.Razor component as that's what's included in the VS2022 Net8 Blazor template. 

As my app runs entirely in interactive server mode should I be using

`<script src="/_framework/blazor.server.js" autostart="false"></script>` 

or is blazor.server.js now obsolete ? The app works fine in Local IIS btw.

**Comment by ryanbuening** [comment]
@jonrmorgan99 - did you ever find the answer to the question of whether to be using `blazor.web.js` or `blazor.server.js` if the app is interactive server only?

**Comment by jonrmorgan99** [comment]
@ryanbuening - No, but I settled on `blazor.web.js` for my Net8 migration which is fine for interactive server mode.

**Comment by ryanbuening** [comment]
So for people coming finding this thread, I have found that `blazor.web.js` in .NET 8 (with Interactive Server) does not work successfully in my environment using IIS with a load balancer. I receive the following SignalR errors:

![image](https://github.com/dotnet/aspnetcore/assets/812974/04332ae0-3055-46a7-bbaf-9dd6798a1aed)

When I switch to using `blazor.server.js`, things work successfully:

![image](https://github.com/dotnet/aspnetcore/assets/812974/4c23e492-a685-402c-a8af-8f22f1b978ec)

I also have the following script logic set in `App.razor`

```js
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
	Blazor.start({
		configureSignalR: function (builder) {
			builder.configureLogging("debug");
			builder.withUrl("/_blazor", {
				skipNegotiation: true,
				transport: 1
			});
		}
	});
</script>
```

We have numerous Blazor Server apps running in production successfully on .NET 7 and below. This was my first experiment with .NET 8.

@javiercn - Please let me know if what I'm doing seems incorrect to you.

**Comment by subhash199** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> I have an ASP.NET Core 7 app that mostly uses traditional MVC with razor views that utilizes blazor server on some subpaths. After upgrading to .NET 8.0, by upgrading the TargetFramework and PackageReferences, not doing any code changes, the blazor pages stopped working correctly.
> 
> They pre-render correctly but are not interactive. I include them by having `<component type="typeof(App)" render-mode="ServerPrerendered" />` in a cshtml file at the subpath where blazor starts being used, e.g. https://app.tld/Admin hits an MVC controller that returns a View that includes said markup. If i change it from `ServerPrerendered` to `Server`, all i get is a white page.
> 
> I can see that a websocket connection for blazor is established but there's no error message in the browser console nor on the ASP.NET Core console window. All the Browser console says is
> 
> ```
> [2023-11-15T18:41:50.278Z] Information: Normalizing '/_blazor' to 'https://localhost:44311/_blazor'. blazor.server.js:1
> [2023-11-15T18:41:50.327Z] Information: WebSocket connected to wss://localhost:44311/_blazor.
> ```
> 
> If necessary, i can try to create a minimal project but if anyone knows off the top of their head what i'm doing wrong, that would be great.
> 
> ### Expected Behavior
> Blazor Server should just continue to work in .NET 8 as it did in .NET 7 per the upgrade guide https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio#update-a-blazor-server-app
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Exceptions (if any)
> _No response_
> 
> ### .NET Version
> 8.0.100
> 
> ### Anything else?
> _No response_

**Comment by subhash199** [comment]
My Program.cs contained "app.MapBlazorHub();" Got rid of this line. It worked
