### ISSUE TITLE
[.NET 8] Page Title not being applied when using WebAssembly PreRender=false

### ISSUE THREAD

**Issue by ricfwolff** [dotnet/aspnetcore#52090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When navigating to a page that is marked with `InteractiveWebAssemblyRenderMode(prerender: false)`, the PageTitle is not applied.

### Expected Behavior

Page Title should be applied according to what's present in the <PageTitle> tag.

### Steps To Reproduce

- Install latest .net 8
- Open a new folder and run: `dotnet new blazor -o BlazorApp -int Auto`
- Open `Counter.razor` and replace line 2 from:
  - `@rendermode InteractiveAuto`
  - To this:
  - `@rendermode @(new InteractiveWebAssemblyRenderMode(false))`
- Run the application and navigate between pages;
- When you go to 'Counter' page, the title is not applied to the browser tab.

### .NET Version

8.0.100

### Anything else?

VSCode

**Comment by ricfwolff** [comment]
Sorry, I could've searched better, as I found a way to do that (or a workaround, if you consider it a bug) on this answer: https://stackoverflow.com/questions/58863542/how-to-set-page-title-in-blazor?rq=3

On the `Program.cs` file **on Client project**, added this using below:
`using Microsoft.AspNetCore.Components.Web;`

And the following line:
`builder.RootComponents.Add<HeadOutlet>("head::after");`

Sorry again, but this might be useful for someone else...

**Comment by augustevn** [comment]
@ricfwolff just out of curiosity did you set the interactivity on the `<HeadOutlet />` that did it for me.

```

﻿<!DOCTYPE html>
<html>
<head>
    ...
    <HeadOutlet @rendermode="@RenderMode.InteractiveWebAssembly" />
</head>
<body>

<App @rendermode="@RenderMode.InteractiveWebAssembly" />
...
```

**Comment by ricfwolff** [comment]
@augustevn Thanks for the tip!
I changed that and now the opposite situation is happening 🤣 
It works correctly for WebAssembly pages, updating the title, but does not work for SSR pages. 🤷

**Comment by augustevn** [comment]
@ricfwolff You're welcome!
Well, SSR is static (without interactivity). I think updating the head tags, page title dynamically requires interactivity.
Maybe there's an "enchanced" thing for that. Feel free to share your piece of code.

**Comment by ricfwolff** [comment]
I'm trying to migrate a WASM Hosted project to become Auto for startup performance increase. So currently my Layout is SSR and my pages are WASM. One of the pages I was able to migrate to Auto and it worked. Just with this small issue regarding the page title. But I know this is new stuff and I'm aware we still don't have all documentation and samples for all the situations people will do. 😄 
It's not a big project, but I have to migrate page by page, find the _difficulties_, solve them, etc. while doing some other stuff at the same time.
As soon as I'm able to generate a small sample code, I'll post it here. :)
Thanks for the help.

**Comment by augustevn** [comment]
@ricfwolff interesting experiment! I'd assume WASM hosted (prerendered) isn't that different in initial load.

**Comment by mandeep-sps** [comment]
Hi team,

I have added the below line of code in the program.cs file but still title is still not showing in Auto mode.
builder.RootComponents.Add<HeadOutlet>("head::after");
I am using this line of code at the page level. Please suggest me any other alternative.
@page "/sfgrid-Grid"
@attribute [StreamRendering]
@* @rendermode @(new InteractiveAutoRenderMode(prerender:false)) *@
@rendermode InteractiveAutoRenderModeNoPreRender

<PageTitle>Employee Listing</PageTitle>

**Comment by mandeep-sps** [comment]
@mkArtakMSFT @augustevn Please check my above message regarding title not showing in dotnet 8 Blazor WEb app.

**Comment by mkArtakMSFT** [comment]
@mandeep-sps you are doing something wrong in your code. We have seen many customers hitting the issue where they have inconsistent render modes set between HeadOutlet and HeadContent components. Those should be the same.
We've seen this as something many other customers hit periodically and we're going to address it as part of https://github.com/dotnet/aspnetcore/issues/50268

**Comment by mandeep-sps** [comment]
@mkArtakMSFT Its is fixed at my end. I have added the Below line in the App.Razor file
`<HeadOutlet @rendermode="InteractiveAuto" />`
Thanks
