### ISSUE TITLE
.NET 8 : dockerfile not working

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/aspnetcore#52092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I upgraded my asp.net core web app from .NET 7 to .NET 8.

I removed dockerfile and added new dockerfile by "add docker support" in Visual Studio 2022 (current version 17.8.0)

**Building the docker image from dockerfile ends with error on COPY commands.**

**I changed nothing else in to project, just dockerfile and target framework and it stopped working.**

When I modified the path to be as in .net 7 docker file it works again (even with net 8 images).

```
------------------
NEW (& WRONG) : .NET 8
------------------

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MyProjectName/MyProjectName.csproj", "MyProjectName/"] <------- ERROR HERE !!!!
RUN dotnet restore "./MyProjectName/./MyProjectName.csproj"
COPY . .
WORKDIR "/src/MyProjectName"
RUN dotnet build "./MyProjectName.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MyProjectName.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyProjectName.dll"]


------------------
ORIGINAL : .NET 7
------------------

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["MyProjectName.csproj", "."] <--------------------- THIS WORKS !!!! 
RUN dotnet restore "./MyProjectName.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MyProjectName.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyProjectName.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyProjectName.dll"]
```

### .NET Version

8.0.0

**Comment by martincostello** [comment]
What is the specific error you get?

**Comment by cropyai** [comment]
@LukasKubicek  looks very very similar to this issue https://github.com/dotnet/aspnetcore/issues/52059

**Comment by amcasey** [comment]
I understand one issue is about building the image and the other is about running it, so it's not immediately obvious to me that they're dups.

**Comment by faruknane** [comment]
> I understand one issue is about building the image and the other is about running it, so it's not immediately obvious to me that they're dups.

I am really sorry about the confusion that I made.

**Comment by amcasey** [comment]
No worries, thanks for checking for related issues. 😄   They may still turn out to be dups.

**Comment by cropyai** [comment]
Yes, I am really sorry about that the confusion happened. was not my intention @amcasey

**Comment by amcasey** [comment]
```diff
+COPY ["MyProjectName/MyProjectName.csproj", "MyProjectName/"] <------- ERROR HERE !!!!
-COPY ["MyProjectName.csproj", "."] <--------------------- THIS WORKS !!!!
```

It looks like the dockerfile expected to be in the solution folder and it's actually one level down in the project folder.

**Comment by amcasey** [comment]
Unfortunately, it's not possible to transfer issues across github orgs, so I've filed a new issue: https://github.com/microsoft/DockerTools/issues/408

I believe you've already discovered this, but the workaround is to use paths relative to the project folder as in 7.0.
