### ISSUE TITLE
Blazor Web App Run Error when project name contain Chinese

### ISSUE THREAD

**Issue by jackywang615** [dotnet/aspnetcore#52109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

if the project name contain any Chinese, the counter Page will raise error.
![Snipaste_2023-11-16_08-44-27](https://github.com/dotnet/aspnetcore/assets/9586655/ab865d88-b289-45e7-aca4-45198b9b8618)

### .NET Version

8.0.100

**Comment by vcsjones** [comment]
This looks to be the same issue reported at https://github.com/dotnet/aspnetcore/issues/50879.
