### ISSUE TITLE
Blazor - .Net 8 - Quick Grid - Sorting and Filtering Broken

### ISSUE THREAD

**Issue by RoryGarner92** [dotnet/aspnetcore#52101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With the standard .Net 8 Blazor template.
Using Quick Grid Sorting and Filtering functionality not available. Including default sort functionality.
OnClick does nothing sorting arrows do not appear in the column headers. 

### Expected Behavior

Arrows to appear in the column headers and the ability to click and sort on field.

### .NET Version

8

**Comment by bcheung4589** [comment]
Do you have some example code where we can reproduce your problem? Maybe even a minimal repo?

**Comment by RoryGarner92** [comment]
Hi thanks for the reply. I was trying to use the sample code from the docs on the Quick Grid page with their test data.

**Comment by RoryGarner92** [comment]
Yep it was using SSR. I am the problem :) like you said need to be rendered client side.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out here, @Aculeo.
@RoryGarner92 looks like there is nothing else pending here, correct?

**Comment by RoryGarner92** [comment]
Correct all working as expected.
