### ISSUE TITLE
protected override void OnInitialized() firing twice

### ISSUE THREAD

**Issue by AlexW68** [dotnet/aspnetcore#52111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to get EditForm to work, but the model keeps on clearing back to null, the issue is the OnInitialized method is running twice, first when it should when the page first loads, then on submit of the page as well, clearing the model and removing any data that has been entered on the page.

I have modified the example from https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/?view=aspnetcore-8.0

looking at other projects the OnInitialized only fires once.

```
@page "/demo"
@inject ILogger<Demo> Logger

<EditForm Model="@Model" FormName="test.form" OnValidSubmit="@Submit">
	<DataAnnotationsValidator />
	<ValidationSummary />
	<InputText @bind-Value="Model!.Id" />
	<button type="submit">Submit</button>
</EditForm>

@code {
        [SupplyParameterFromForm] 
	public Starship? Model { get; set; };

	// this fires twice once when the page loads and once when the form is submitted
	// in my other projects this only fires on initial loading, not on submit
	protected override void OnInitialized() {
		Model ??= new();
	}

	private void Submit() {
		Logger.LogInformation("Id = {Id}", Model?.Id);
	}

	public class Starship {
		public string? Id { get; set; }
	}
}
```

### Expected Behavior

The model should have the value typed into the form on submit

### Steps To Reproduce

put a breakpoint on the OnInitialized method to see it firing twice, once on init and second on submit

### .NET Version

8

### Anything else?

Running the latest VS community edition preview

**Comment by LuohuaRain** [comment]
https://github.com/dotnet/aspnetcore/issues/51978

**Comment by AlexW68** [comment]
@LuohuaRain thanks, it's still broken the key thing is the page looks like it is being completely reloaded as model is going back to null.

As a second issue, I use MudBlazor, using the MudTextField rather than the InputText also clears any properties in the model bound to the control on submit.

**Comment by javiercn** [comment]
@AlexW68 thanks for contacting us.

Seems like you are missing method="POST" on your form.

What's happening here is that Blazor renders the form the first time (on page load) and then when you click submit it renders a new again (a completely new instance, keep in mind that this is SSR, there is no state between requests) and after that it dispatches the event to the form.

Since you are not setting form=POST in your form, it's sending the data in the query string, and we don't bind the form data from the query string.

```
<EditForm Model="@Model" FormName="test.form" OnValidSubmit="@Submit">
	<DataAnnotationsValidator />
	<ValidationSummary />
	<InputText @bind-Value="Model!.Id" />
	<button type="submit">Submit</button>
</EditForm>
```

**Comment by AlexW68** [comment]
Thank you for the reply, I did have the post in on some iterations of the testing, put back in 

the following works

`<InputText @bind-Value="Input.Email" class="form-control" autocomplete="username" aria-required="true" placeholder="name@example.com" />`

but the following still returns null in the model

`<MudTextField T=string Label="User Name" @bind-Value="Input.Email" Variant=MudBlazor.Variant.Outlined></MudTextField>
`
Of course this is a third party library (MudBlazor) so it maybe their responsibility to resolve why that is happening in .net 8

Sorry I have so many demo projects now trying lots of different things.

**Comment by javiercn** [comment]
@AlexW68 thanks for the additional details.

That seems to be a MudBlazor specific issue, hard to tell from the usage what's going wrong.
