### ISSUE TITLE
Milestones - Inconsistencies

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#52113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was wondering about the status of certain milestones.. 
For example, why are some issues still open in closed milestones ?

A) In 8.0-preview6 (Closed), there is still an open issue.
B) In 8.0-rc1 (Closed), there are still two open issues.
C) In 8.0-preview3 (Closed), there are still two open issues.
D) Why is there still a 2.1.x milestone? It is no longer supported.
E) Why is there still a 3.1.x milestone? It is no longer supported.
F) In 8.0-rc2 (Open), there are still seven open issues. Why isn't this milestone closed? It has been released.
G) In 8.0.0 (Open), there are still eight open issues. Why isn't this milestone closed? It has been released.

### Describe the solution you'd like

Do you plan to revise the milestones and change the status of some issues?

**Comment by Tratcher** [comment]
Yes, we do have some cleanup to do.

A), B) @BrennanConroy
C) Fixed
D) AspNetCore 2.1 is still supported on .NET 4.x
E) Fixed
F) @benjaminpetit @captainsafia 
G) @mkArtak @adityamandaleeka

**Comment by captainsafia** [comment]
> F) @benjaminpetit @captainsafia

8.0-rc2 is cleared now.

**Comment by boukenka** [comment]
@captainsafia Thank you
@Tratcher Thanks as well. Do you think other points could be completed ? I have added the H point

A) In 8.0-preview6 (Closed), there is still 1 open issue
B) In 8.0-rc1 (Closed), there is still 1 open issue
F) 8.0-rc2 is still open. Can this milestone be closed?
G) In 8.0.0 (open), there are still 6 open issues. Can this milestone also be closed?
H) In 7.0.0 (Closed), there are still 8 open issues

**Comment by mkArtakMSFT** [comment]
I've triaged the issues under my team areas.
@adityamandaleeka reassigning this to you as the remaining issues are under your team area paths.

**Comment by boukenka** [comment]
Thanks for the update. There have been some changes. Here is the remaining status.

G) In 8.0.0 (open), there are still 2 open issues. Can this milestone also be closed?
H) In version 7.0.0 (closed), there are still 6 open issues.
I) In version 8.0.1 (open), there is still 1 open issue. Can this milestone  also be closed?

Do you plan to set up a procedure, in the future, for dealing with unclosed issues that remain in a closed/released milestone ?

**Comment by boukenka** [comment]
Here is the remaining status.

G) In 8.0.0 (open), there are still 2 open issues. Can this milestone also be closed?

**Comment by mkArtakMSFT** [comment]
This is now done! Thanks for bringing this up, @boukenka !
