### ISSUE TITLE
RenderMode not working with razor class libraries

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#52129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I create a project that has a razor class library and I try to use this code
@rendermode InteractiveAuto
and try to compile that library, it always fails to compile because does not know anything about @rendermode

Works fine when using under blazorwebapp.
However, some cases i need razor class library so I can share with blazor hybrid and use other places as well.

### Expected Behavior

The expected behavior is for the project to compile and run.
When using web, then do as promised on the counter where it first uses blazor server and the next time web assembly (since the components would have been downloaded).

### Steps To Reproduce

1.  Create blank solution
2.  Create blazor web app
3. Create maui blazor hybrid
4. Create shared library
5. Move the Counter from blazor web app client to the shared
6. Make the necessary changes necessary including referencing the proper projects and putting in the additional assemblies
7. Run
8. Will always fail to load (even the blazor web app).

### Exceptions (if any)

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0103	The name 'InteractiveAuto' does not exist in the current context

### .NET Version

8

**Comment by musictopia2** [comment]
Forgot to put in my sample repository.
Here is the link to it.
https://github.com/musictopia2/RenderModeBug 
This shows the problem happening everytime.   Used only the sample that came with the templates.
Only work I did was to move the counter from the client to the shared, delete the counter from the native and did the work required so the routers can work.

**Comment by MariovanZeist** [comment]
Hi @musictopia2 Could you add the following to your ``_imports.razor`` file in your ``BlazorShared`` project. 
That should fix your issue.
```razor
@using static Microsoft.AspNetCore.Components.Web.RenderMode
```

See: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-a-component-instance

**Comment by MariovanZeist** [comment]
Sorry @musictopia2 I spoke to soon.
Updating ``counter.razor`` 
with 
```razor
@rendermode RenderMode.InteractiveAuto
```
did get rid of the compilation error, but the counter still doesn't function.

**Comment by mkalinski93** [comment]
I´m in the exact same situation. I want to have a Client app with several RCL. The RCL cannot be used with the rendermode "InteractiveWebassembly". It works whenever I change the rendermode to server.

<img width="1069" alt="image" src="https://github.com/dotnet/aspnetcore/assets/64005967/70e851e2-2863-4f0e-98b4-4804ddc1d13a">

Wasm lib is a standalone WebAssembly App
Lib B is a RCL

I´ve also added the "@using static Microsoft.AspNetCore.Components.Web.RenderMode" into the RCL´s imports file.

**Comment by chulla** [comment]
i have the same problem. When i compile with F5 no problem... but when i run with Ctrol + F5, i get the error

**Comment by apocalipisis** [comment]
When i add
`@rendermode RenderMode.InteractiveServer`
to the counter component, it works fine on the Blazor web app.

But when I run it on the Windows machine and try to open the counter page, I get the following error:
`Cannot supply a component of type 'BlazorApp1.Client.Pages.Counter' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveAutoRenderMode'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)`

**Comment by apocalipisis** [comment]
When i add
`@rendermode RenderMode.InteractiveServer`
to the counter component, it works fine on the Blazor web app.

But when I run it on the Windows machine and try to open the counter page, I get the following error:

> Cannot supply a component of type 'BlazorApp1.Client.Pages.Counter' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveAutoRenderMode'.
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode) ...

**Comment by bertutron** [comment]
i have the same problem even with an empty blazor web app project. Adding a component with data binding, it only works first time loading. i tried rendermode at router tag, and in razor components, all fail. problem seems to happen only on RenderMode.InteractiveAuto. when i change to InteractiveServer, everything works, even after reload

**Comment by MackinnonBuck** [comment]
@musictopia2, the `Blazor Web App` project template includes a `using static` in `_Imports.razor` to allow you to write `@rendermode InteractiveAuto`:

```razor
@using static Microsoft.AspNetCore.Components.Web.RenderMode
```

However, the Razor Class Library template has no such `using static` directive. So, you'll either have to add that line to your RCL's `_Imports.razor` file, or declare a component's render mode by partially qualifying `InteractiveAuto`:

```razor
@rendermode RenderMode.InteractiveAuto
```

Furthermore, it looks like `BlazorWeb.Client` in your repro project doesn't reference the `BlazorShared` project. This will be required if you want components in the `BlazorShared` RCL to render using WebAssembly interactivity, as they might if they use the `InteractiveAuto` render mode.

I suspect a similar issue might be the cause of @mkalinski93's error, and possibly @bertutron's as well, although it's hard to tell without a repro project.

**Comment by MackinnonBuck** [comment]
@apocalipisis, what might be happening in your case is a component with an interactive render mode is attempting to render a child component with a different interactive render mode. This is not supported. For example, it won't work if you have an app with root-level server interactivity and you try to render a component with an `InteractiveWebAssembly` render mode. For more information, refer to our docs on this topic: https://learn.microsoft.com/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#render-mode-propagation.

**Comment by musictopia2** [comment]
The only issue left is does not work with a maui app though.

**Comment by MackinnonBuck** [comment]
@musictopia2, if a render mode is specified in a component's definition, it's effectively saying, "This component requires 'x' type of interactivity". Blazor Hybrid is a different technology than Blazor Server or Blazor WebAssembly, so a component that requires Server/WebAssembly interactivity won't work in a Blazor Hybrid app.

Unless a component is designed to _only_ work with Server or WebAssembly interactivity, the interactive render mode should be specified at the call site instead. For example, instead of:

_MyComponent.razor:_
```razor
@rendermode InteractiveAuto
...
```

...do this:

_Index.razor_
```razor
<MyComponent @rendermode="InteractiveServer" />
```

For more info, see the note in the docs [here](https://learn.microsoft.com/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-a-component-definition).

cc @apocalipisis, since your comment implied you might also be creating a Blazor Hybrid app.

**Comment by SongPing** [comment]
Found some ugly work around:

In the Razor Class Library write a class with a static variable holding the AppType.
```
    public enum AppType { Unknown, Blazor, Maui }
    public class AppProps {
         public static AppType AppType { get; set; } = AppType.Unknown;
    }
```
Set the AppTyype in Program.cs `AppProps.AppType = AppType.Blazor;` and MauiProgram.cs `AppProps.AppType = AppType.Maui;`  accordingly.

From Counter.razor remove `@page "/counter"` and `<PageTitle>Counter</PageTitle>`.

Create a CounterPage.razor component:
```
@page "/counter"
<PageTitle>Counter</PageTitle>

@if (AppProps.AppType == AppType.Blazor) {
    <Counter @rendermode="InteractiveServer"></Counter>
} else if (AppProps.AppType == AppType.Maui) {
    <Counter></Counter>
}
```

So counter.razor still can be used as 'page' and can be shared across Blazor and Maui app.

I hope I can remove this work-around soon, when there is a solution for .net 8!

Hope it may help somebody meanwhile, coming across the same issue.

**Comment by musictopia2** [comment]
I would have suggested going even further and having more types like Auto or WebAssembly.
So if its a server app that has parts that require webassembly, then WebAssembly would be used.
I would think if the web assembly template was used alone (including PWA), then would be a standard type.
Even Maui would be the standard type.  In this case, then does not matter if its maui.  That can be the same behavior as it would if the entire app was web assembly (the older style).

**Comment by MackinnonBuck** [comment]
@SongPing, if you need to have an interactive page in a Razor Class library, there are a few options:
1. Push interactivity up a layer. This is referred to as "app level" interactivity, and it involves making the `Routes` component interactive. It does, however, mean that interactivity might be enabled for pages that don't necessarily need it.
2. Push component interactivity down a layer. This is similar to what you did in your workaround.
3. Come up with a custom mechanism to select page interactivity. I wrote a gist here to show an example of this [here](https://gist.github.com/MackinnonBuck/441681764d879d9ac4906aaec6410eb9).

**Comment by SongPing** [comment]
@MackinnonBuck Thanks for your answer!
To 1.: I've already tried that before, but got the error:
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot pass RenderFragment<T> parameter 'Found' to component 'Router' with rendermode 'InteractiveServerRenderMode'. Templated content can't be passed across a rendermode boundary, because it is arbitrary code and cannot be serialized.
Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.ValidateParameters(IReadOnlyDictionary<string, object> latestParameters)
Would be nice to get a working working solution for that!
To 3.: This works! But I'm not sure, if this causes any side effects in the future. (Mainly because I myself, does not fully understand the code involved).

**Comment by chulla** [comment]
> MackinnonBuck

This solution works. thank you!!

I notice a little "**lag**" when I first navigate (where the wasm is downloaded for the first time) in the Counter component with InteractiveAuto, do you notice it?

**Comment by mattleibow** [comment]
I was able to get a repro sample here on this commit: https://github.com/mattleibow/.NET-Conf-2023/tree/d48e0b7698b28d3bfbf21c9e05a8f9eeefd2b557/BlazorAllTheThings

I have 3 projects:
* web app
* wasm client
* razor lib

I have a counter component in the razor lib, but the wasm client can't load the component

**Comment by chulla** [comment]
I still have the problem when I compile with CTRL+F5 with Blazor InteractiveAuto

![image](https://github.com/dotnet/aspnetcore/assets/36098387/163b9782-64ce-48fd-8177-30a626cd2d59)

Could you give an example for everyone? (Blazor (InteractiveAuto) + Maui) 



Thank you

**Comment by SteveSandersonMS** [comment]
> when i compile with F5 it works!!

This makes me wonder if it's a caching issue. Can you try clearing your browser cache? Does it work with Ctrl+F5 after that?

**Comment by chulla** [comment]
> > when i compile with F5 it works!!
> 
> This makes me wonder if it's a caching issue. Can you try clearing your browser cache? Does it work with Ctrl+F5 after that?

Yes, I clean all storage cache.  But it not work

Could you check it ?
https://github.com/chulla/Blazor8WithRCL
Thanks

**Comment by javiercn** [comment]
@musictopia2 In your repro, the client project needs to reference the BlazorShared project.

**Comment by musictopia2** [comment]
I did add the reference to the shared in the client.
Still does not fix the issue with the maui app though.

**Comment by chulla** [comment]
Hola @javiercn  could you check my repo?

i use interactiveauto render as @MackinnonBuck has said

https://github.com/chulla/Blazor8WithRCL

Compile & Debug with F5 is OK -->  [video ](https://github.com/musictopia2)](https://icecreamapps.com/v/ehmdkcn)

Compile & without debug ( CTRL + F5 ) --> No ok -->  [Video](https://icecreamapps.com/v/fatybkf)

Gracias, Manuel

**Comment by itaylorm** [comment]
The solution is somewhat complex

You do need to use the reference in your _imports.razor for the razor library
@using static Microsoft.AspNetCore.Components.Web.RenderMode

You need to place this at the top of your page in razor library
@page "/countdown"
@rendermode RenderMode.InteractiveAuto

You then need to add the following to the program.cs file
In my case my component page is Countdown

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(Counter).Assembly)
    .AddAdditionalAssemblies(typeof(Countdown).Assembly);
    
 You can then go to the page specified /countdown
 
 If you don't want to have it be a page, remove both of these from your component
 @page "/countdown"
@rendermode RenderMode.InteractiveAuto

Put the component on the page
<Countdown @rendermode="RenderMode.InteractiveServer"/>

**Comment by musictopia2** [comment]
If you do the proposed solution, then does not work with blazor hybrid though if the page is in the razor class library.

**Comment by saykorz** [comment]
> 3\. Come up with a custom mechanism to select page interactivity. I wrote a gist here to show an example of this [here](https://gist.github.com/MackinnonBuck/441681764d879d9ac4906aaec6410eb9).

Above solution is very good but missing a little step in RazorClassLibrary to activate click button in blazor server:

@page "/counter"
`@using Microsoft.AspNetCore.Components.Web`
@attribute [InteractivePage]

Routes.razor is InteractiveServer of course
`routeData = routeData.WithAllowedInteractivity(InteractiveServer);`

and now all is working in both Blazor Server and MAUI Blazor Hybrid.

**Comment by SongPing** [comment]
Why is this issue closed?
The RenderMode is still not working with razor class libraries using MauiBlazorHybrid.
This is a critical point for many developers wanting to share code between Blazor (Web) and MAUI !
The proposed Hack from @MackinnonBuck does not work stable in all cases.
@SteveSandersonMS are there any plans to make the code sharing possible?

**Comment by javiercn** [comment]
If you are still facing an issue in this area after updating to 8.0.1, please file a separate issue with your specific scenario and include a repro project. See also https://github.com/dotnet/maui/issues/18812 if your scenario involves Maui in case this is what you are running into.

**Comment by smola93** [comment]
Does someone consider fixing this in further releases? I think this is still a big issue and @MackinnonBuck workaround doesn't seem to resolve it in a final way and reusing interactive components/pages between MAUI and Blazor Web is very problematic.

**Comment by Eilon** [comment]
For anyone watching here, we think we found a workaround that will help many common cases and you should be able to easily apply it to your app. Check this post here: https://github.com/dotnet/aspnetcore/issues/51235#issuecomment-1946927922

**Comment by sanepete** [comment]
Would somebody be kind enough to point me to the .Net 9.0 RenderMode.InteractiveWebAssembly version of this bug, please?
I cannot get a component from an RCL to run in my Blazor web app and I feel I've tried practicaly everything.
