### ISSUE TITLE
DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.

### ISSUE THREAD

**Issue by giuseppe-terrasi** [dotnet/aspnetcore#52126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading an existing Blazor Server side on .NET 7 to a Blazor App in .NET 8 I get this javascript error when navigating:

```
Uncaught (in promise) DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.
    at q (https://localhost:7001/_framework/blazor.web.js:1:20110)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167970)
    at wi (https://localhost:7001/_framework/blazor.web.js:1:169913)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167646)
    at wi (https://localhost:7001/_framework/blazor.web.js:1:169913)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167646)
    at vi (https://localhost:7001/_framework/blazor.web.js:1:165963)
    at https://localhost:7001/_framework/blazor.web.js:1:176131
    at Object.write (https://localhost:7001/_framework/blazor.web.js:1:174447)
```

After that, the server streaming part of the page doesn't load. This is totally random. 

The same project works fine with the previous version of the framework,

### Expected Behavior

Navigate from one page to another without any problem

### .NET Version

8.0.100

### Anything else?

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

Carichi di lavoro .NET installati:
 Workload version: 8.0.100-manifests.8d38d0cc
 [android]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    34.0.43/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maui-windows]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    8.0.3/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maccatalyst]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

 [ios]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.320 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by javiercn** [comment]
@giuseppe-terrasi thanks for contacting us.

Could you provide a minimal repro project as a public github repository as well as a detailed set of steps to trigger the issue?

**Comment by giuseppe-terrasi** [comment]
@javiercn thanks for your reply.
I've simplified the app functionalities inside [this](https://github.com/giuseppe-terrasi/TestBlazorApp) test repo. The problem happens when navigating between Counter and Weather pages but, as I said, it is random. Maybe, the docker layer can cause it after some wrong code refresh.

**Comment by giuseppe-terrasi** [comment]
I linked the requested [repo](https://github.com/giuseppe-terrasi/TestBlazorApp)

**Comment by rubenvannieuwpoort** [comment]
For the record, we're seeing the same problem with our Blazor webapp. For some reason, we see this problem consistently on our test environment, but only seldom when we test locally.

```
Uncaught (in promise) DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.
    at q (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:20110)
    at yi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:167970)
    at wi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:169913)
    at yi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:167646)
    at wi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:169913)
    at yi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:167646)
    at vi (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:165963)
    at https://our-app.azurewebsites.net/_framework/blazor.web.js:1:176131
    at Object.write (https://our-app.azurewebsites.net/_framework/blazor.web.js:1:174447)
```

**Comment by capdiem** [comment]
I have the same issue. As long as you put an interactive component in MainLayout, then route to the weather page, refresh, and then visit other pages, this error will occur.

**Comment by sfnmk** [comment]
Same here. Similar error appears randomly while navigating between pages with interactive components. In my case the error is:
```
Uncaught (in promise) TypeError: Failed to execute 'setEndAfter' on 'Range': parameter 1 is not of type 'Node'.
    at q (blazor.web.js:1:20130)
    at yi (blazor.web.js:1:167970)
    at wi (blazor.web.js:1:169913)
    at yi (blazor.web.js:1:167646)
    at wi (blazor.web.js:1:169913)
    at yi (blazor.web.js:1:167646)
    at vi (blazor.web.js:1:165963)
    at blazor.web.js:1:176131
    at Object.write (blazor.web.js:1:174447)
q @ blazor.web.js:1
yi @ blazor.web.js:1
wi @ blazor.web.js:1
yi @ blazor.web.js:1
wi @ blazor.web.js:1
yi @ blazor.web.js:1
vi @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
write @ blazor.web.js:1
await in write (async)
(anonymous) @ blazor.web.js:1
Ne @ blazor.web.js:1
xi @ blazor.web.js:1
```

**Comment by turnercj65** [comment]
Hey @MackinnonBuck I just ran into this issue. I'm able to successfully repro this as you described with an interactive component in the top level of the app's layout, refresh the browser while on a page with streaming enabled that uses the layout, and perform an enhanced navigation to another page, also sharing the same layout.

**Comment by GZidar** [comment]
I too am seeing this problem. We are using v8.0.3 with an interactive component in the app layout.

**Comment by MackinnonBuck** [comment]
@turnercj65, @GZidar, are you using the 8.0.204 SDK? If not, could you please try that and see if it resolves your issue? Please also make sure your package versions are up-to-date. If this resolves the problem, could you please let us know? If not, we would appreciate a minimal repro project that demonstrates the issue, hosted as a public GitHub repository. I tried to create my own repro with an interactive component in the layout, and the issue did not occur. Thanks!

**Comment by CoreyT65** [comment]
Thanks @MackinnonBuck I've updated to the latest SDK and updated all nuget packages and still running into this only when published to azure app service (windows in my case). I'm not able to repro this when running locally, but consistent repro when published to azure.

**Comment by CoreyT65** [comment]
@MackinnonBuck Yep, adding the 8.04 extension to the app service did the trick. Thank you very much!
