### ISSUE TITLE
Incorrect child component content is rendered with static SSR or prerendering on server

### ISSUE THREAD

**Issue by DzmitryMatveyeu** [dotnet/aspnetcore#52131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During static SSR or prerendering parent component loads data in OnInitialiedAsync method. If loaded data is not null then Child component is rendered. In this case only initial state of Child component is rendered on the UI. If Child component itself loads data in OnInitialiedAsync method then the loaded data will not be rendered.

### Expected Behavior

The latest state which is formed after OnInitializedAsync of parent and child components should be returned to browser

### Steps To Reproduce

Create Blazor 8 app from default template and select static rendering with no interactivity.

Add Child.razor component to the project:

```
<div>@childString</div>

@code {
   private string childString = "initial child";

   protected override async Task OnInitializedAsync()
   {
      await base.OnInitializedAsync();
      await Load();
   }

   private async Task Load()
   {
      await Task.Delay(1000);

      childString = "loaded child";
   }
}

```

Update Home.razor to:

```
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@if (someProperty != null)
{
   <div>@someProperty</div>
   <Child />
}

@code {
   private string? someProperty = null;

   protected override async Task OnInitializedAsync()
   {
      await base.OnInitializedAsync();
      someProperty = await Load();
   }

   private async Task<string> Load()
   {
      await Task.Delay(1000);

      return "parent";
   }
}
```

Run the project and check content of home page.

It displays:
Welcome to your new app.
parent
initial child

but should display:
Welcome to your new app.
parent
loaded child

If I remove @if (someProperty != null) condition in parent component then I see expected result on the UI

### .NET Version

8.0.100

**Comment by augustevn** [comment]
I think I'm having similar issues:

Everything seems right but not showing what it should: 
![image](https://github.com/dotnet/aspnetcore/assets/77939574/4aecc812-2604-47c6-9d50-18c96cbec72c)
![image](https://github.com/dotnet/aspnetcore/assets/77939574/634ed253-bf41-41b5-b2f4-5520d33c3a2f)
![image](https://github.com/dotnet/aspnetcore/assets/77939574/2b9dd5c9-0eb6-46fa-b7d4-61b5fd87591d)
