### ISSUE TITLE
Blazor: NavigationManager - NavigateTo bug with parameters

### ISSUE THREAD

**Issue by fabiano-ferreira** [dotnet/aspnetcore#52138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating to .NET 8, my Blazor application is not working properly anymore.

I have one page where a URL string is being built (with parameters) and then the NavigateTo method is called with NO force Load option.

The parameters I am using are this type:
`[Parameter]
[SupplyParameterFromQuery(Name = "c")]
public string CustId { get; set; }
`

Until .NET 7.0.14 the page being called by the NavigateTo method was passed the parameters correctly.
However, after I update to .NET 8, now, the parameters are not being passed by a regular NavigateTo method call. Instead, now it ONLY works if I call the NavigateTo method using the forceLoad option set to true.

I don't want to totally reload the page from the server only because of the parameters. 

Please, see if this can be fixed.

Thank you!

### Expected Behavior

I wanted to call the NavigateTo method with no forceLoad and even though I want the parameters to be passed.

### .NET Version

8.0.0

**Comment by SteveSandersonMS** [comment]
Thanks @fabiano-ferreira. For us to be able to investigate this, could you supply minimal repro code? This could be a public GitHub repo with a minimal example app, or perhaps even better still, create an example using https://blazorrepl.telerik.com/.

**Comment by plastovicka** [comment]
I have a minimal repro code: https://blazorrepl.telerik.com/mHbbFBPi53JL6qNu44
OnParametersSet function is called twice, first with zero parameter, the second time with the correct parameter.

**Comment by fabiano-ferreira** [comment]
> I have a minimal repro code: https://blazorrepl.telerik.com/mHbbFBPi53JL6qNu44 OnParametersSet function is called twice, first with zero parameter, the second time with the correct parameter.

Yes. @plastovicka! You are correct! Actually the parameter is really being passed, but there is a delay that was not happening on .NET 7.0.14.

For instance if I use this workaround, it works for me now:

` while (CustId == null)
 {
     await Task.Delay(10);
 }`

At a certain point the parameter CustId becomes different than null. Of course this workaround is a terrible approach, but at least we know that what is happening is a delay of the page in getting the parameters.

**Comment by paulsuart** [comment]
Thank you @fabiano-ferreira your workaround/hack is a good one.

This is a significant problem for me moving forward with an upgrade .NET 8.  What's the time scale on a fix please?

**Comment by plastovicka** [comment]
> For instance if I use this workaround, it works for me now:
> 
> ` while (CustId == null) { await Task.Delay(10); }`
> 

This workaround works only for pages with mandatory parameters. I have some pages with optional parameters where it causes infinite loop.

**Comment by paulsuart** [comment]
@javiercn - would it be possible to get this one added to the [v8.0.x milestone](https://github.com/dotnet/aspnetcore/milestone/285) please?

**Comment by surayya-MS** [comment]
Putting it in 8.0.x milestone since it is patchable in my opinion. Feel free to put it in another milestone @dotnet/aspnet-blazor-eng

**Comment by paulsuart** [comment]
@surayya-MS - any update on this please?

**Comment by halter73** [comment]
This will be fixed in the next patch (8.0.3) by #53625
