### ISSUE TITLE
"dotnet new grpc" doesn't build on a macbook pro m3

### ISSUE THREAD

**Issue by push-22** [dotnet/aspnetcore#52132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to create a GRPC app, but not getting any further than the initial steps.

from a terminal:
**dotnet new grpc [return]**
_The template "ASP.NET Core gRPC Service" was created successfully.

Processing post-creation actions...
Restoring /Users/barrie/Code/tmp/grpctester/grpctester.csproj:
  Determining projects to restore...
  Restored /Users/barrie/Code/tmp/grpctester/grpctester.csproj (in 105 ms).
Restore succeeded._

Then 
**dotnet build [return]**
_MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: The specified task executable "/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc" could not be run. System.ComponentModel.Win32Exception (86): An error occurred trying to start process '/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc' with working directory '/Users/barrie/Code/tmp/grpctester'. Bad CPU type in executable [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]
/Users/barrie/.nuget/packages/grpc.tools/2.57.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/barrie/Code/tmp/grpctester/grpctester.csproj]

Build FAILED._

### Expected Behavior

I would expect it to work oob or tell me its not supported.

### Steps To Reproduce

from terminal on a macbook pro m3 max
dotnet new grpc
then
dotnet build - this will fail

### .NET Version

8.0.100

### Anything else?

if I go to the proto executable mentioned in the error:
> "/Users/barrie/.nuget/packages/grpc.tools/2.57.0/tools/macosx_x64/protoc"

and try to execute it I get the error:
zsh: bad CPU type in executable: ./protoc

**Comment by Tratcher** [comment]
@JamesNK

**Comment by JamesNK** [comment]
Hi @push-22

Can you recreate this issue at https://github.com/grpc/grpc. That's where the source code and issues for Grpc.Tools (the source of your bug) are located.

Thanks
