### ISSUE TITLE
Publish using Web Deploy has locking issues since .NET 8

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#52149]
Since upgrading to .NET 8 I have been getting the following errors when publishing using IIS Web Deploy in Visual Studio 17.8:

> Web deployment task failed. (Web Deploy cannot modify the file 'MyLibrary.dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.

Please note that in my `publish.pubxml` file I have already set `EnableMSDeployBackup` to `true`.

So far my solution has been to stop the website, restart IIS (to release the lock) and then start it again. This is obviously not ideal.

**Comment by nfplee** [comment]
I've also checked the [announcements repo](https://github.com/dotnet/announcements) to see if something might have broke this but I can't find anything.

**Comment by martincostello** [comment]
If you're using Azure App Service (I don't know if it works elsewhere), I've found that setting `MSDEPLOY_RENAME_LOCKED_FILES=1` helps when this sort of error happens.

**Comment by nfplee** [comment]
Thanks @martincostello, but no I'm publishing to a remote server in a data centre.

**Comment by Jean-Jinj** [comment]
Same problem here.

**Comment by nfplee** [comment]
@Jean-Jinj I have created a Visual Studio issue [here](https://developercommunity.visualstudio.com/t/Publish-using-Web-Deploy-has-locking-iss/10521875).
