### ISSUE TITLE
Blazor Web App does not (always) recompile WebAssembly project when changes were made to RCL project

### ISSUE THREAD

**Issue by amather** [dotnet/aspnetcore#52148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I describe the bug as it appears in a minimal reproducible example. The actual bug is more weird, but I failed to reproduce (will add details below anyways).

Here's the setup:

### Create Blazor Web App solution and add a RCL project (`MyApp.Web` + `MyApp.Web.Shared`)
- `dotnet new sln -n blazor-changes-bug`
- `dotnet new blazor --interactivity Auto  --empty true --auth None --all-interactive true --no-https -n MyApp.Web`
- `dotnet sln blazor-changes-bug.sln add MyApp.Web/MyApp.Web/MyApp.Web.csproj`
- `dotnet sln blazor-changes-bug.sln add MyApp.Web/MyApp.Web.Client/MyApp.Web.Client.csproj`
- `dotnet new razorclasslib -n MyApp.Web.Shared`
- `dotnet sln blazor-changes-bug.sln add MyApp.Web.Shared/MyApp.Web.Shared.csproj`

### Use RCL project 
- configure `MyApp.Web` and `MyApp.Web.Client` to reference `MyApp.Web.Shared`
- move `Home.razor` to `MyApp.Web.Shared`
- configure `MyApp.Web.Client\Routes.razor` with `AdditionalAssemblies` (using `Home` type from the RCL assembly)
- configure `MyApp.Web\Program.cs` with `AddAdditionalAssemblies()` (again, using `Home` type)

Let's look at the `Home.razor`:

```
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.
```

* Hit Ctrl-F5 
* Change the `h1` content
* Hit Ctrl-F5

In the browser, you'll shortly see the changes reflected, but it will then flip to the original content.

This may 'works as designed' as nothing in the Client project actually changed and the flipping represents WebAssembly taking over (that never had the changes compiled in). 

So this may be just unpleasant, but when changing to `@InteractiveWebAssembly` in `App.razor` (in both, HeadOutlet and body) the same flipping occurs! How can that be? I would understand if I wouldn't see the changes reflected, but to see the flipping? Didn't I just removed server rendering so that only WebAssembly should render?

Going further, changing the `Home.razor` not on the HTML part, but adding e.g. another `@page` directive, the Client project always recompiles and I see all changes reflected. I guess this is because some SourceGenerator (Router?) picks up the changes and since `Routes.razor` is in the Client project, it will recompile?!

**So I guess what we really need is some guidance on how to make the `.Client` project to always recompile in this scenario.** 

-----

My actual bug:

Same Blazor setup with 3 projects, but part of a larger solution. RCL project references a library project (`libA`) that itself references another library project (`libB`).

Same issue with not seeing HTML changes reflected in the browser, but there's a workaround for me: If I remove the most dependent project (`libB`) from the solution, any change in the RCL project will have the Blazor WebAssembly project recompile. Always! 

`libA` still references `libB`, it's just removed from the solution file! 🤷‍♂️

Again, I couldn't reproduce this with a standalone example, but super strange behavior. Then again, I guess I'd be fine if I just knew how to make the `.Client` project recompile always, on any changes in the RCL library. 

### Expected Behavior

As a user (and newcomer), reading [the documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#route-to-components-from-multiple-assemblies) on how to add additional assemblies, I expect some warning as to what implications this has on the build process. 

Additionally, I expect guidance on how to keep the same same workflow (change files, run, see the results), regardless of where the components I work on live.

### Steps To Reproduce

see above, or just checkout https://github.com/amather/blazor-rcl-changes

### .NET Version

8.0.100 (with Visual Studio 17.9.0 Preview 1.0)

**Comment by javiercn** [comment]
@amather thanks for contacting us.

In this situation, are you talking about this in the context of hot reload? Or are you stopping the entire app and starting it back again.

**Comment by amather** [comment]
@javiercn no hot reload involved. I always restart the application.

I should mention that it's easy to see upfront what the browser will show:
```
========== Build: 2 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```
The `1 up-to-date` here is the `.Client` project, which will then show the old state.

Change the `@page` directive and all 3 will get compiled:
```
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by javiercn** [comment]
@amather I think the "repro" can be simplified if we think this is a build issue.

If you have a webassembly app, and add a class library, make a change to the class library (whatever change you want) and run build, does the webassembly app get updated or does it say that it's up to date.

**Comment by amather** [comment]
@javiercn most likely so, yes!

But I don't know the internal mechanics to say if that is what's supposed to happen or not. As mentioned, this could be 'works as designed', but then 2 odd things remain:

* why does it work in my larger solution? (related: how can I force it to work?)
* why do I see the flipping when using `@InteractiveWebAssembly`? (that's probably a separate issue)

**Comment by javiercn** [comment]
@amather thanks for the additional details.

Can you provide a minimal repro project that demonstrates the issue?

**Comment by amather** [comment]
@javiercn The repro repo is here: https://github.com/amather/blazor-rcl-changes

There you can run the project and change something in the `Home` component (e.g. `<h1>` content) which lives in the RCL project (`MyApp.Web.Shared`). Rendermode is set to `InteractiveWebAssembly`.

**Comment by javiercn** [comment]
@amather thanks for the additional details

What version of Visual Studio are you using?

**Comment by drewnoakes** [comment]
@amather it's worth only disabling Build Acceleration for your client project, as it can still speed up builds of other projects in your solution and save you time.

**Comment by mkArtakMSFT** [comment]
Discussed this with the team and decided that we will disable Accelerated Build for Blazor by setting the flag in the SDK. The feature is simply not compatible with Blazor apps.
