### ISSUE TITLE
Buttons must have discernible text

### ISSUE THREAD

**Issue by glickerman** [dotnet/aspnetcore#52141]
The buttons of Quick Grid for Net 8 get Accessibility Error.
While the Quick Grid works fine.  This just comes down to meeting Accessibility Requirements. :)
![image](https://github.com/dotnet/aspnetcore/assets/39495884/3a2e9966-b596-4d16-b9af-197c1599d635)

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS if we generate these buttons, let's address this please.
