### ISSUE TITLE
Template for Minimal API outside of startup

### ISSUE THREAD

**Issue by b1tzer0** [dotnet/aspnetcore#52158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to see a dotnet new Minimal API Web Item template that generates a stub of code in a file that is separate from startup.cs.

I don't really like the idea of polluting startup with a bunch of endpoints.

This will help with separating the various endpoints based on context.
Example:
Endpoints for XYZ feature goes in one file.
Endpoints for ZYX feature goes in another file.

### Describe the solution you'd like

I would like to see a custom Web Item Template that generates a file similar to how controllers do today.  

Right Click on Folder
Add New Item
Select Minimal Api
Create file with your basic Get/Post/Patch/Put/Delete api endpoints.
These endpoints could be grouped together.

There are several examples on [stackoverflow](https://stackoverflow.com/a/70139455/10011692), one example does the following:
```
public static class ProductEndpointsExt
{
    public static void MapProductEndpoints(this WebApplication app)
    {
        app.MapGet("/products/{id}", (int id) => { return Results.Ok(); });
    }
}
```
Then in startup.cs
```
app.MapProductEndpoints();
```

Of course, you could also apply the MapGroup to it as well, as seen [here](https://stackoverflow.com/a/77202895/10011692).

### Additional context

This would provide guidance on the proper way to establish endpoints without having to put everything in a single file.  As well as making it faster to get going with your new endpoints.

**Comment by davidfowl** [comment]
Do we really need a template for this?

**Comment by b1tzer0** [comment]
While a template may not be necessary and could be easily accomplished just by the developer adding the files and wiring them up.  I just thought having something similar for Minimal APIs as we do for Controller based APIs would be nice.

**Comment by captainsafia** [comment]
There is scaffolding in Visual Studio that supports this as well.


![](https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2023/05/a-screenshot-of-a-computer-description-automatica-1.png)

See [this blog post](https://devblogs.microsoft.com/visualstudio/web-api-development-in-visual-studio-2022/) for more info.

**Comment by b1tzer0** [comment]
I completely missed that, that resolves my issue.
