### ISSUE TITLE
The default AOT scaffolding project adds a source code generator, and the SG-generated code is referenced in the entry function, compiled with NativeAOT publish throws a CS0103 exception

### ISSUE THREAD

**Issue by vipwan** [dotnet/aspnetcore#52175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In fact, if I don't set `PublishAot `to compile and publish there is no problem, SG works fine, but after set `PublishAot `= true the publish fails

SG code:
```c#

// <auto-generated />
public class Hello
{
    public static void SayHello()
    {
        Console.WriteLine("hello aot!");
    }
}
```
.csproj: 
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>
	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\Gen\Gen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
```
Program.cs
```c#
Hello.SayHello();
```

when publish then throw:
![image](https://github.com/dotnet/aspnetcore/assets/13956765/6396b06c-f337-446a-95e7-419aef1aea19)

### Expected Behavior

If I don't configure `PublishAot`, there's no problem , Is `NativeAOT `not supporting custom SG or `Microsoft.AspNetCore.Http.RequestDelegateGenerator` limitations ?   
Can my needs be met?

### .NET Version

8.0.100

**Comment by gfoidl** [comment]
@vipwan can you please provide a (self contained) reproduction sample. So it's not clear what the source generator `..\Gen\Gen.csproj` is doing, thus it's hard to impossible to tell what's going on.

**Comment by vipwan** [comment]
> @vipwan can you please provide a (self contained) reproduction sample. So it's not clear what the source generator `..\Gen\Gen.csproj` is doing, thus it's hard to impossible to tell what's going on.

I found the problem because I referenced an empty project and this project is marked as `<Project Sdk="Microsoft.NET.Sdk.Razor"> `  if I delete the referenced project , publish succeeds smoothly  :) 

Isn't `NativeAOT `able to reference the Razor library like that ?

**Comment by gfoidl** [comment]
I'm glad you found the problem and could fix it.

> Isn't `NativeAOT `able to reference the Razor library like that ?

At the moment not. Remember that NativeAOT has some limitations, it's under heavy development to enable it on more features. [ASP.NET Core and native AOT compatibility](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0#aspnet-core-and-native-aot-compatibility) gives you on overview of the current state.
