### ISSUE TITLE
Blazor component rendering twice using @rendermode InteractiveServer

### ISSUE THREAD

**Issue by mickeld23** [dotnet/aspnetcore#52185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor component using @rendermode InteractiveServer with a method that calls an external api.
OnInitialized I want to call the external api to provide data to my component.
When doing this noticed OnInitialized is being called twice every time my component is rendered.
This does not happen if my component has no @rendermode InteractiveServer.
In my case I need it because I have a button in my component that can refresh the data by calling the api again.

### Expected Behavior

Call OnInitialized once.

### Steps To Reproduce

- Create a component with @rendermode InteractiveServer.
- Override OnInitialized method and add a log.
- Check the duplicate logs on every render.

### .NET Version

8.0.100

**Comment by Suchiman** [comment]
This is due to [pre rendering](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0). The first time `OnInitialized` is called is when the server is pre rendering the page and the second time when the browser has established the websocket connection to the server and is running interactively.

**Comment by mickeld23** [comment]
This makes sense but the problem I'm having now is that my component is fetching the data and my page is rendering (1st server render). Then again fetching data while my page is rendered so my component is looking empty.
Is their anyway to prevent this? Making my property static is not an option and I prefer that the client has data on the initial request.

**Comment by mickeld23** [comment]
Nevermind did not check the linked docs at first. So looks like I need to use a persistent component state. Will give it a try. Thanks for your help.
