### ISSUE TITLE
blazor ignoring UsePathBase middleware

### ISSUE THREAD

**Issue by quintendc** [dotnet/aspnetcore#52198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Yarp with different blazor projects, it seems like blazor is ignoring the UsePathBase middleware.
Yarp should redirect based on the prefix provided by the UsePathBase e.g. 

**Blazor Web App:**
`app.UsePathBase("/blazorapp2");`

**Blazor yarp config:**
This is a class used in every microservice
```
public static MicroserviceConfig Configuration { get; } = new BlazorApp2Config
{
    Routes =
    {
        new RouteConfig
        {
            RouteId = routeId,
            ClusterId = clusterId,
            Match = new RouteMatch
            {
                Path = "/BlazorApp2/{**catch-all}"
            }
        }
    },
    Clusters =
    {
        new ClusterConfig
        {
            ClusterId = clusterId,
            Destinations = new Dictionary<string, DestinationConfig>
            {
                {
                    "destination1", new DestinationConfig
                    {
                        Address = $"https://localhost:{AppPortNumber}"
                    }
                }
            }
        }
    }
};
```

In the yarp project is build routes from every config instance:
**Yarp project program.cs**
```
var microserviceConfigs = new List<MicroserviceConfig>
{
    BlazorApp1Config.Configuration,
    BlazorApp2Config.Configuration,
};


var allRoutes = microserviceConfigs.SelectMany(config => config.Routes).ToList();
var allClusters = microserviceConfigs.SelectMany(config => config.Clusters).ToList();

builder.Services.AddReverseProxy().LoadFromMemory(allRoutes, allClusters);
```

If i navigate to localhost:7096/BlazorApp2. I'm missing the static files and when navigating inside this project it will redirect to the other application where the route is mapped to localhost:7096/

```
public static MicroserviceConfig Configuration { get; } = new BlazorApp1Config
{
    Routes =
    {
        new RouteConfig
        {
            RouteId = routeId,
            ClusterId = clusterId,
            Match = new RouteMatch
            {
                Path = "{**catch-all}";
            }
        }
    },
        Clusters =
    {
        new ClusterConfig
        {
            ClusterId = clusterId,
            Destinations = new Dictionary<string, DestinationConfig>
            {
                {
                    "destination1", new DestinationConfig
                    {
                        Address = $"https://localhost:{AppPortNumber}"
                    }
                }
            }
        }
    }
};
```

### Expected Behavior

When using **UsePathBase()** every request should use the prefix so yarp can redirect to the corresponding application.

### Steps To Reproduce

https://github.com/quintendc/demo

### .NET Version

8.0.100

### Anything else?

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
 [android]
   Installation Source: VS 17.8.34309.116
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34309.116
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34309.116
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34309.116
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by quintendc** [comment]
You can fix the static files by using this `<base href="@(typeof(Program).Assembly.GetName().Name)/">` inside app.razor, but navigating between pages is still an issue.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
