### ISSUE TITLE
@microsoft/signalr Version 8.0.0 throws error when used with Angular 17

### ISSUE THREAD

**Issue by arambazamba** [dotnet/aspnetcore#52192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Please find details here

Bug was introduced with 8.0.0 - downgrade to 7.0.14 resolves the issue

https://github.com/dotnet/aspnetcore/issues/52082

⠹ Building...X [ERROR] Could not resolve "url"

    (disabled):node_modules/eventsource/lib/eventsource.js:1:20:
      1 │ var parse = require('url').parse;
        ╵                     ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "https"

    (disabled):node_modules/eventsource/lib/eventsource.js:3:20:
      3 │ var https = require('https');
        ╵                     ~~~~~~~

  The package "https" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "http"

    (disabled):node_modules/eventsource/lib/eventsource.js:4:19:
      4 │ var http = require('http');
        ╵                    ~~~~~~

  The package "http" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "util"

    (disabled):node_modules/eventsource/lib/eventsource.js:5:19:
      5 │ var util = require('util');
        ╵                    ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

### Expected Behavior

angular build should be possible

### Steps To Reproduce

add a single signal r 

export class AppComponent {
  private store = inject(OrdersStore);
  private hubConnection: SignalR.HubConnection | null = null;

constructor() {
    this.store.init();
    this.connectSignalR();
  }

  connectSignalR() {
    // Create connection
    this.hubConnection = new SignalR.HubConnectionBuilder()
      .withUrl(environment.WebhookEP + '/api')
      .build();

    // Start connection. This will call negotiate endpoint
    this.hubConnection.start();

    // Handle incoming orders for the specific target
    this.hubConnection.on('foodapp.order', (event: string) => {
      console.log('Received order', event)
      let evt = JSON.parse(event) as CloudEvent<Order>;
      this.store.addOrder(evt);
    });
  }

### Exceptions (if any)

project should build

### .NET Version

@microsoft/signalr

**Comment by BrennanConroy** [comment]
Dupe

**Comment by EricSch** [comment]
Why was this issue closed? 
I have the same problem. Seems there are modules with node libraries used.
