### ISSUE TITLE
In the Blazor Web App Template, a policy works using the attribute Authorize for the page but not for the AuthorizeView inside the page when the page is in the client project

### ISSUE THREAD

**Issue by rsescalante** [dotnet/aspnetcore#52199]
Hello

I'm migrating an application from Blazor Hosted WASM to the new .net 8 Web App template.  I have found that on a InteractiveWebAssembly render mode page, the [Authorize(Policy = "MyPolicy"] works fine but using <AuthorizeView Policy="MyPolicy"] throws the error that the policy cannot be found at runtime.

Authorization should work at the page level and at the html code level.

I have found as a workaround that if I add the Policies and handlers in program.cs as well as the code for the policy handler in the client project it works.

**Comment by javiercn** [comment]
Thanks for contacting us @rsescalante.

You need to define the policy both on the Server and the Client projects, otherwise the Client project has no way to know that the policy exists.

**Comment by rsescalante** [comment]
Thank y ou Javier, that is what I ended up doing, as in the old Hosted WASM way.  Nevertheless the Authorize attribute at the page level does work.  I would expect the AuthorizeView component to behave in the same way.
