### ISSUE TITLE
Blazor web app (dotnet 8): data-enhance-nav="false" is not working when tag <a/> is wrapping some <svg/>

### ISSUE THREAD

**Issue by megafetis** [dotnet/aspnetcore#52205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`<a href="/" data-enhance-nav="false">
    <svg>...Not refresh page...</svg>
</a>` - is not working (not refreshing a page. enhance-nav is still enabled)

`<a href="/" data-enhance-nav="false">
    <img src=""/> 
</a>` - is working (refreshing a page)
This problem is also actual for top level nodes for example <body>... link with svg  ...</body>

### Steps To Reproduce

jsut create new Blazor Web app and add some code 
```
<a href="/" data-enhance-nav="false">
    <svg xmlns="http://www.w3.org/2000/svg"
     width="467" height="462">
  <rect x="80" y="60" width="250" height="250" rx="20"
      style="fill:#ff0000; stroke:#000000;stroke-width:2px;" />
  
  <rect x="140" y="120" width="250" height="250" rx="40"
      style="fill:#0000ff; stroke:#000000; stroke-width:2px;
      fill-opacity:0.7;" />

  <rect x="140" y="120" width="250" height="250" rx="40"
      style="fill:#00ff00; stroke:#0000cc; stroke-width:5px;
      fill-opacity:1.0;" />
</svg>
</a>
```

### .NET Version

8

**Comment by megafetis** [comment]
Update: This bug also happens, when `href` contains anchor or hash:
`<a data-enhance-nav="false" href="/about#licences">About - Licences</a>`

**Comment by MackinnonBuck** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/53541

**Comment by megafetis** [comment]
Cool!
