### ISSUE TITLE
OnInitialized and OnInitializedAsync are called twice with @rendermode InteractiveServer

### ISSUE THREAD

**Issue by giuseppe-terrasi** [dotnet/aspnetcore#52208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With .NET 8 Blazor App the OnInitialized and OnInitializedAsync methods are called twice if the component has render mode InteractiveServer. This happens when the rendermode is defined at component level and when applied with an attribute.
If this is a design pattern it is unclear when a long-running task such as a data recovery. must be executed

### Expected Behavior

OnInitialized and OnInitializedAsync methods are called once

### Steps To Reproduce

The default Blazor App project has this behavior

### .NET Version

8.0.100

### Anything else?

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

Carichi di lavoro .NET installati:
 Workload version: 8.0.100-manifests.8d38d0cc
 [android]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    34.0.43/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maui-windows]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    8.0.3/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maccatalyst]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

 [ios]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.320 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by garrettlondon1** [comment]
You have to turn off pre-rendering. If you have pre-rendering enabled, which is a overload on InteractiveServerRenderMode(prerender: false), it will execute twice. Once when it pre-renders on the server. Another when it renders after initial content.

**Comment by giuseppe-terrasi** [comment]
@garrettlondon1 Thanks for your reply. Why pre-rendering is enabled by default with InteractiveServerRenderMode? In this scenario, it is more intuitive that pre-rendering is disabled by default and enabled only if necessary.

**Comment by giuseppe-terrasi** [comment]
@garrettlondon1 I agree with you, but since now we have more rendering types it can cause more confusion than in the past. I'm refactoring a .NET 7 Blazor Server app, with pre-rendering disabled, to a .NET 8 Blazor App and this double execution occurs when it didn't before. The old default project has the pre-rendering option set on _Host.razor file so it is clearly visible and understandable. The new one doesn't have this option set so I assumed that choosing the rendering mode managed it.

**Comment by garrettlondon1** [comment]
I assumed the same @giuseppe-terrasi, no worries

**Comment by javiercn** [comment]
@giuseppe-terrasi thanks for contacting us.

@garrettlondon1 @giuseppe-terrasi seems that you figured out, but I'll leave the explanation here, just in case. Blazor renders the app twice:
* A first time statically during prerendering.
* A second time interactively once the app starts in the browser.

This behavior is expected and not something we plan to change. As you mentioned, you can disable prerendering in your apps if that behavior doesn't in your app.

However, I would ask what the concrete pain are points you run into with this. Is it just the fact that is running twice, the fact that the code runs in two different contexts (Request vs SignalR).

**Comment by giuseppe-terrasi** [comment]
@garrettlondon1 The problem here is that if we need an interactive page that loads some data it will load them twice and the user must wait until the end to interact with the page. Also, if we add the StreamRendering the user will see blinking data for a while just like this example:

https://github.com/dotnet/aspnetcore/assets/5776240/7ae20e4e-4e8a-498c-b08b-502518558cdd

**Comment by javiercn** [comment]
@giuseppe-terrasi thanks for the additional details.

You should use Persistent Component State in that situation. It'll marshal the data for you so that it doesn't get loaded twice and you avoid the blinking on the UI

**Comment by giuseppe-terrasi** [comment]
@javiercn I think that it is an overload both at development time, because I have to maintain the state with all pros and cons, and on the client side because the data can be very big and the browser has to handle them which can cause a significant loss of performance. In my opinion, the InteractiveServer without pre-rendering still remains the best solution. 

Thanks.

**Comment by javiercn** [comment]
@giuseppe-terrasi thanks for the additional details.

In the end is about trade-offs, but I take your points about the state piece, and we'll likely try to improve the story in the future.

**Comment by mandeep-sps** [comment]
Hi, I have added this line of code for Prevent the Twice call:-
@rendermode @(new InteractiveAutoRenderMode(prerender:false))

**Comment by SenerDemiral** [comment]
@rendermode @(new InteractiveServerRenderMode(prerender:false))

render twice:
```
protected override void OnInitialized()
{
	using IDbConnection conn = dbCon.GetConnection();
	wqp = conn.Query<WQP>("select * from WQP");
}
```
render single:
```
protected override void OnInitialized()
{
	using (IDbConnection conn = dbCon.GetConnection())
	{
		wqp = conn.Query<WQP>("select * from WQP");
	}
}
```

**Comment by Mafyou** [comment]
But, if you do this rendermode, the HttpContext is always null.
Which is very problematic because you cannot Auth a user without it.

**Comment by joesun99** [comment]
> But, if you do this rendermode, the HttpContext is always null. Which is very problematic because you cannot Auth a user without it.

Having sample problem.  If i use @rendermode @(new InteractiveServerRenderMode(prerender: true))
Then HttpContext is null and can't pass cookies to HubConnectionBuilder

**Comment by giuseppe-terrasi** [comment]
@joesun99 It's by design. You cannot bind HttpContext using InteractiveServerRenderMode but, if you need it, you can use the interface `IHttpContextAccessor`. Remember to add 
`builder.Services.AddHttpContextAccessor();`
to add it into DependecyInjection

@Mafyou and @joesun99 To authenticate a user the page must be rendered statically or, eventually, with server streaming because a full request-response circle is required to set the authentication cookie. Using the Interactive mode, both prerendered or not, the framework uses the SignalR connection as same as in .Net 7

**Comment by angularsen** [comment]
I'm still getting `OnInitialized` called twice on initial page load for `AlertInteractionHandler` component in main layout, even when [disabling prerendering](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#prerendering) for the component.

Is there a way to verify pre-rendering is indeed disabled?


- Blazor Web App targeting `net8.0` with .NET SDK 8.0.304
- `InteractiveServer` is set globally on `<Routes>`
- `GlobalHandlers` component in main layout disables pre-rendering
- `AlertInteractionHandler` component inherits disabling of pre-rendering from parent `GlobalHandler`, and I also tried disabling pre-rendering for both components

**App.razor example:**
```razor
<html>
<body>
<Routes @rendermode="InteractiveServer" />
</body>
</html>
```

**MainLayout.razor**
```razor
<GlobalHandlers />
@Body
```

**GlobalHandlers.razor**
```razor
@rendermode @(new InteractiveAutoRenderMode(prerender: false))

<AlertInteractionHandler />
```

**Comment by angularsen** [comment]
After digging more, I created a repro. 
https://github.com/angularsen/aspnetcore-issue-52208

Maybe I'm just misunderstanding how it should work, but
- When app uses interactive server render mode with pre-rendering **enabled**, then components that explicitly disable pre-render still initialize twice (same as app), expected app to initialize twice but components to initialize just once
- When app uses interactive server render mode with pre-rendering **disabled**, then both app and components with pre-rendering disabled initialize just once, as expected.

![image](https://github.com/user-attachments/assets/8dcc11bb-fcd3-46f9-bb7d-8846aa0b5f8f)

**Comment by angularsen** [comment]
So this [pre-render paragraph](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#prerendering) probably explains the behavior.

> Disabling prerendering using the following techniques only takes effect for top-level render modes. If a parent component specifies a render mode, the prerendering settings of its children are ignored. This behavior is under investigation for possible changes with the release of .NET 10 in November, 2025.

Not sure exactly what top-level render modes mean. Globally in app router? Per page?
Assuming globally, [this is how it's set](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-the-entire-app).

> To set the render mode for the entire app, indicate the render mode at the highest-level interactive component in the app's component hierarchy that isn't a root component.
> For apps based on the Blazor Web App project template, a render mode assigned to the entire app is typically specified where the Routes component is used in the App component 

[Prerendering docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#prerendering) state that prerendering _can_ be disabled per component:
> To disable prerendering for a component instance, pass the prerender flag with a value of false to the render mode

Now I'm just confused. 
- Render mode is configured globally in Router.
- Pre-render can be disabled per component
- However, if a parent component sets a render mode (the Router), then render modes of children components are ignored.

So... We can't disable pre-rendering of components?

**Comment by giuseppe-terrasi** [comment]
@angularsen, "If a parent component sets a render mode (the Router), then render modes of children components are ignored." That's correct. I think you should not set a render mode on the Router component and set it to the specific component that requires it. Also, setting a render mode interactive on the Router component is similar to the .NET 7 behavior, which is not comfortable with authentication, especially with cookies. In my application, I create the page and then split it into components with different render modes according to the requirements. 

To better handle the pre-rendering I added this class:

```
    public static class RenderMode
    {
        public static InteractiveServerRenderMode InteractiveServerNotPrerendered { get; } = new(false);

    }
```

and imported in _Imports.razor:

`@using static YourClassNamespace.RenderMode`

Hope it helps!

**Comment by angularsen** [comment]
Interesting, I thought by not setting a render mode it defaulted to static rendering? 

> The default render mode is Static.
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#render-mode-propagation

Will give it a try and report back 🙇
