### ISSUE TITLE
Allow defining Blazor component parameters at runtime

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/aspnetcore#52204]
## Background and Motivation

Imagine you build a component library and want to reduce code redundancy as much as possible. You will eventually build util base classes like `FocusComponentBase` and maybe a `PopoverComponentBase` or whatever base classes fit into the library. The problem is that at the moment you want to mix these up and build scenarios like a focusable popover you will have to introduce an opinionated hirachy into your base classes, which will always limit the further usage of these.

Other frontend frameworks tackled this by allowing "Mixins" or "Composables". This unfortunately will be very hard to cover, given that C# is a strongly typed programming language, but a first step into supporting something similar could be the possibility to define component parameters at runtime. We already can implement default implementations for interfaces, but we cannot define parameters on an interface level (via the `Parameter` attribute). Allowing to define parameters dynamically would mitigate this problem.

## Proposed API

To stay completely downwards compatible and inline with the current API, I suggest the implementation of the `ParametersAttribute`, which one can use to decorate an `IDicitonary<string, object>` to have get & set support for a dynamic collection of key value pairs.

Of course if another parameter is defined with the same key (name) is defined on the same component using the `ParameterAttribute` it should either prioritize the single parameter or throw an exception.

## Usage Examples

```csharp
using Microsoft.AspNetCore.Components;

public class ExampleComponent : ComponentBase
{
    [Parameters]
    public IDictionary<string, object> DynamicParameters { get; } = new Dictionary<string, object>();
}
```

## Alternative Designs

I could also imagine to have a more sophisticated approach by defining an additional interface `IComponentParameters` which could look like this:

```csharp
public interface IComponentParameters
{
    public IEnumerable<string> ParameterNames { get; }
    
    public object? GetParameter(string name);
    
    public void SetParameter(string name, object? value);
}
```

Which would mean that the Microsoft.AspNet.Components framework would only support dynamic parameters if the target component implements this interface.

## Risks

As far as I can see, there should be no risks, since internally the parameters are serialized into a dictionary anyways (at least in WebAssembly).

**Comment by javiercn** [comment]
@DavidVollmers thanks for contacting us.

We already have this feature with `  [Parameter(CaptureUnmatchedValues = true)] public DynamicParameters { get; set; }` are we missing something here?
