### ISSUE TITLE
JavaScript events are not working while `blazor.web.js` is included

### ISSUE THREAD

**Issue by glen-84** [dotnet/aspnetcore#52212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

JavaScript events are not working while `blazor.web.js` is included.

### Expected Behavior

I expected JavaScript events to continue to function, regardless of whether or not the Blazor JavaScript is included.

### Steps To Reproduce

Simply add the following to `Counter.razor`:

```html
<button id="test" class="btn btn-primary">test</button>

<script>
    document.addEventListener("DOMContentLoaded", function(event) {
        document.getElementById("test").addEventListener("click", e => {
            e.target.disabled = true;
        });
    });
</script>
```

Clicking the button does not result in it being disabled. If you comment-out the reference to `blazor.web.js`, then it works.

Why should client-side JavaScript events not work?

### .NET Version

8.0.100

### Anything else?

```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/glen/.dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  7.0.401 [/home/glen/.dotnet/sdk]
  7.0.403 [/home/glen/.dotnet/sdk]
  8.0.100-rc.1.23463.5 [/home/glen/.dotnet/sdk]
  8.0.100-rc.2.23502.2 [/home/glen/.dotnet/sdk]
  8.0.100 [/home/glen/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/glen/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. You're not seeing the `DOMContentLoaded` event fire because it only happens on the initial page load. It doesn't run after an enhanced navigation, which is presumably when this script got added to the page.

We have docs on this here: https://learn.microsoft.com/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0

**Comment by glen-84** [comment]
@MackinnonBuck

That's not the issue. The `DOMContentLoaded` event fires with a direct navigation, but the `click` event is not added (or is removed).

**Comment by glen-84** [comment]
I'm guessing this may be caused by the element being detached from the DOM as part of the (re)rendering process, which results in the event listener being lost.

Removing the `DOMContentLoaded` listener and adding the `click` listener directly seems to work.
