### ISSUE TITLE
Microsoft.AspNetCore.RateLimiting still maintained or deprecated?

### ISSUE THREAD

**Issue by coonmoo** [dotnet/aspnetcore#52228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Microsoft.AspNetCore.RateLimiting nuget package has seen the last release a year ago  (7.0.0-rc.2.22476).
It didn't receive an update with the .NET8 release.

I wonder if this package is still being maintained.
Are there any plans to release an update?

This would be important to know to make a decision if we should depend on the package in the future or roll something custom.

### .NET Version

8.0.0

**Comment by martincostello** [comment]
The package was moved into the shared ASP.NET Core framework and no longer exists as an independently shipped NuGet package.

If you use the web SDK or [a framework reference](https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?tabs=visual-studio#use-the-aspnet-core-shared-framework) you can consume the rate limiting APIs.
