### ISSUE TITLE
Provide updated Blazor Server template for .NET 8

### ISSUE THREAD

**Issue by shoffma1** [dotnet/aspnetcore#52227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently with .NET 8.0.100 SDK, creating an "old" Blazor Server templated project, framework targets are limited to .NET 6 and .NET 7.  Requiring people to either 1) Start a new project on a soon to be unsupported version, or 2) Manually updating all references, and hoping that all the "hidden" references not in the csproj file are also updated.

### Describe the solution you'd like

For scenarios requiring Microsoft Identity, prior to issue #51202 being address, please just update the "old" Blazor Server template to have references to .NET 8 packages.  Rather than requiring people to create new projects and update them to .NET 8, or use a different hosting model.

**Comment by javiercn** [comment]
@shoffma1 thanks for contacting us.

The Blazor Server template has been replaced with the Blazor Web template with the Global Interactivity and Server options enabled. We don't plan to ship an updated Blazor Server template.

**Comment by Viajaz** [comment]
@javiercn Except it doesn't have the same functionality in regards to authentication (Microsoft Identity) and they aren't planning on implementing the missing functionality (See #51202) until .NET 9.

Given the EOL for .NET 6 is 2024-11-14 and EOL for .NET 7 is 2023-05-15, it's conceivable that there could be a period where Microsoft has no supported Blazor Project template that has Microsoft Identity at all or, at the very least, zero overlap between the old and the new.

If they aren't going to do #51202 in .NET 8 then they really should do this issue instead. I really don't understand why so much time was spent on creating ASP.NET Blazor demos and content for .NET Conf when functionality like this is missing from important project templates.

**Comment by mkArtakMSFT** [comment]
The Blazor Web App template is the successor of the Blazor Server project template in .NET 8. We do plan to enable the integration with Microsoft Identity Platform for the new Blazor Web App template and this is tracked as part of the #51202.

As a side note, here is an example showing how to update a project to Blazor 8 and use OpenID Connect https://github.com/dotnet/aspnetcore/issues/51759#issuecomment-1793949698

**Comment by shoffma1** [comment]
I don't think this is a duplicate of 51202, at all. Fwiw, I was able to use the documented (https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#adopt-all-blazor-web-app-conventions)  method to update an existing .NET 7 project ... though Visual Studio is complaining about any component not previously created, such as QuickGrid, as being invalid. I guess that's a VS problem though.
