### ISSUE TITLE
.NET 8 Upgrade Causes Post-Logout Loop in Blazor Server App with Azure AD B2C

### ISSUE THREAD

**Issue by mshiek114** [dotnet/aspnetcore#52245]
**Issue Summary:**
After upgrading a Blazor server application from .NET 7 to .NET 8, which utilizes Azure AD B2C for authentication, a post-logout loop issue is occurring. This looping behavior during logout did not occur with .NET 7. The application handles login and other operations correctly when logged in, but fails to complete the logout process, resulting in a loop. This issue is distinct from previously reported issues #50725 and #51005, which were related to login problems.

**Current Blazor Setup:**
The application is configured for global interactivity, with render modes placed in HeadOutlet and Routes.

**Logout Process:**
The issue arises when using the Sign Out link, which is directed to /MicrosoftIdentity/Account/SignOut.

**Screenshot for Reference:**
<img width="291" alt="Screenshot 2023-11-21 042320" src="https://github.com/dotnet/aspnetcore/assets/117550981/8dba3b62-f2d3-4167-a1fc-4adf8d28ba61">

**Comment by mshiek114** [comment]
[Here ](https://github.com/mshiek114/DotNet8AzureADB2C)is the minimal repo project.

**Comment by VladislavAntonyuk** [comment]
Add `builder.Services.AddRazorPages();` in MauiProgram. `Microsoft.Identity.Web.UI` still uses razor pages

**Comment by mshiek114** [comment]
@VladislavAntonyuk, thank you so much for your assistance. Your suggestion was exactly what I needed, and it has successfully resolved the issue. I appreciate your help!
