### ISSUE TITLE
dotnet user-secrets list --json outputs invalid json

### ISSUE THREAD

**Issue by corbob** [dotnet/aspnetcore#52247]
### Description

The output from `dotnet user-secrets list --id <ProjectId> --json` as stated in the help includes `//BEGIN` and `//END` in the output. The problem with this is that it is not valid JSON syntax, and so Windows PowerShell `ConvertFrom-Json` will fail.

### Reproduction Steps

On Windows PowerShell (version 5.1) run:
```
dotnet user-secrets set hi there --id 'mine'
dotnet user-secrets list --id 'mine' --json | ConvertFrom-Json
```

### Expected behavior

The output JSON should be valid JSON and should be parseable by the strict parser used by Windows PowerShell.

### Actual behavior

The JSON parser in Windows PowerShell is not able to parse the comments: `ConvertFrom-Json : Invalid JSON primitive: .`

### Known Workarounds

Use PowerShell 7.3.9 or newer (suspect should work on earlier, maybe as far back as 6.0). If you need to use Windows PowerShell, a line like this could work around it: `(dotnet user-secrets list --id "myId" --json) -replace '//BEGIN', '' -replace '//END', '' | convertfrom-json`

### Configuration

This happens with `dotnet` versions `6.0.417`, `7.0.403`, and `8.0.100`

**Comment by amcasey** [comment]
As [documented](https://github.com/dotnet/aspnetcore/blob/60b4c429c9a75252ef62f68196f2f79600a7be5a/src/Tools/dotnet-user-secrets/src/Internal/ListCommand.cs#L19), it does [do that](https://github.com/dotnet/aspnetcore/blob/60b4c429c9a75252ef62f68196f2f79600a7be5a/src/Tools/dotnet-user-secrets/src/Internal/ListCommand.cs#L62).  I have to admit it's not immediately obvious to be me why it includes that header and footer - I'll try to find out.

**Comment by amcasey** [comment]
Well, it's [always](https://github.com/aspnet/DotNetTools/pull/199) been that way and changing it now would undoubtedly break consumers.  From some comments on the [issue](https://github.com/aspnet/DotNetTools/issues/168), it sounds like being able to serialize to a file may have been a goal and it seems possible that delimiters help(ed) with deserialization.

**Comment by amcasey** [comment]
As for mitigating the issue, it seems like skipping the first and last lines might be cheaper than text replacement, but I leave that to your discretion.

I don't see other requests for a change in this area (e.g. behind a flag), so I'm going to close this.  Sorry I didn't have better news for you.
