### ISSUE TITLE
Blazor hosted webassembly NavigationManager NavigateTo causing client navigation instead of silent history.pushState

### ISSUE THREAD

**Issue by gilm0079** [dotnet/aspnetcore#52256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was recommended to create a new issue by @SteveSandersonMS after commenting on Issue [https://github.com/dotnet/aspnetcore/issues/51042](https://github.com/dotnet/aspnetcore/issues/51042)

I have a large blazor hosted webassembly app. I'm attempting to use NavigationManager to update querystring parameters silently to help hold state of records opened, tab locations, etc. When I use NavigateTo for same URL except changing a querystring parameter it causes client routing to execute instead of just performing a silent history.pushState(). I see the entire UI refresh, but also I can see all components being disposed and re-initialized. If instead of executing the NavigateTo and call down to Javascript to execute history.pushState() it works correctly, updating the URL and not causing a dispose/initialize cycle.

Again, my application is very large and not able to be shared. I'm trying to create a minimal solution for debugging, but have not replicated the issue yet. I'll continue to add complexities into the solution until it replicates, but any advise as to what I could try to see why NavigationManager is causing a route change to execute would be helpful.  

If you wish to follow along with minimal solution I made the sample solution public here: [https://github.com/gilm0079/DgcSampleNavigationManagerIssue](https://github.com/gilm0079/DgcSampleNavigationManagerIssue)

### Expected Behavior

Change URL silently similar to a history.pushState() in JS. Not cause a route change to execute. Not cause all components to dispose and initialize. history.pushState() works for the same url change.

### Steps To Reproduce

Working on adding complexities until NavigationManager starts causing unwanted route executions.

### .NET Version

7.0.404

### Anything else?

Using VS 2022 Pro x64 17.7.7
NuGet referencing Microsoft.AspNetCore.Components.WebAssembly 7.0.10
Debugging in latest stable version of Chrome
Using IIS Express (via VS) as hosted server

**Comment by mkArtakMSFT** [comment]
Thanks for filing this, @gilm0079.
Your sample is not "minimal". Please strip it out to the minimum code required to demonstrate the problem so that we can investigate this further. Otherwise, we will probably wait for more similar feedback before we investigate.

**Comment by gilm0079** [comment]
Thanks for the update. Sorry, when I said minimal I meant it more as minimal to reproduce the problem. I haven't been able to reproduce it yet so I'll continue to incrementally add complexity until NavigationManager reproduces the issue. At that time I may have a better understanding the specific cause for the issue. In the meantime, if anyone has suggestions of things to try or inspect to see what could be causing NavigationManager to execute the route change it may give me better direction in narrowing down the cause. 

When the problem is reproducible in the referenced repo, I'll trim it down to minimal.
