### ISSUE TITLE
Net8.0 Router NotFound isn't called when an invalid page is entered in the addressbar

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/aspnetcore#52251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Net7.0 You could display a custom 404 page inside the ``NotFound`` Element of a ``Router`` so when you navigate to a nonexisting page the custom 404 page would show.

In Net8.0 when running the default ``Blazor Web App`` templates, when I navigate to a non-existing page, the browser default 404 page is shown, not the one defined in my ``Router``

### Expected Behavior

Display the content of the ``NotFound`` element of a ``Router`` when navigating to a non-existing page

### Steps To Reproduce

Create a default ``Blazor Web App``  Application

Modify the ``Routes.razor`` file to show
```razor
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
    </Found>
    @*Add these lines*@
    <NotFound>
        Show me a 404
    </NotFound>
</Router>
```

And type in ``https://{yourappaddresshere}/nonexistingpage``
It should show ``Show me a 404``  but it will display the default browser 404 page

### .NET Version

8.0

### Anything else?

I assume the problem is because of a missing ``app.MapFallback`` in ``program.cs`` But I am not sure which one to use.

**Comment by MariovanZeist** [comment]
#48983 has more info, closing this as duplicate..

**Comment by MariovanZeist** [comment]
After following #48983 I am unsure what the recommended action is and hope for some guidance.

**Comment by mkArtakMSFT** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/45654, which we plan to use to improve this experience.

As for now, you will have to create a razor page (not a component) to redirect to in response to a non-existent page request.

**Comment by T-Smith45** [comment]
Hello @MariovanZeist and other future devs that find their way to this form, The workaround for this issue is to use app.UseStatusCodePagesWithRedirects("/404") to a blazor page. Example https://github.com/T-Smith45/Blazor-404-redirect

**Comment by mandeep-sps** [comment]
Hi team I got the Solution:-

```
app.UseStatusCodePagesWithRedirects("/404");

app.Run();
Add a _404.razor page to your Pages folder.


@page "/404"
<h3>Show me 404</h3>
@code {
    
}
```
Dotnet 8 Web app Template
