### ISSUE TITLE
[.net 8][Blazor] <Navigating> tag is not working (or improve documentation)

### ISSUE THREAD

**Issue by ricfwolff** [dotnet/aspnetcore#52257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-8.0#complete-example and to https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#user-interaction-with-navigating-content , it should be possible to display some text while the user is transitioning from one page to another by using the `<Navigating>` tag.

But, either the documentation is lacking something, or it stopped working.

Because it is not displaying the `<Navigating>` content for me.

### Expected Behavior

Display "LOADING..." when clicking on different pages.

### Steps To Reproduce

- Install dotnet 8
- open a new folder and run: `dotnet new blazor -o BlazorApp -int auto `
- open Routes.razor and substitute all text with below:

``` diff
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.WebAssembly.Services

<Router AppAssembly="@typeof(Program).Assembly"
        OnNavigateAsync="@OnNavigateAsync" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
+    <Navigating> <!-- <<<<<<<------ This is the tag I'm talking about ----------------->
+        <h1>LOADING...</h1>
+    </Navigating>
</Router>

@code {

    private async Task OnNavigateAsync(NavigationContext args)
    {
        try
        {
            Console.WriteLine($"Navigating to {args.Path}"); // if on VSCode, you can put a debugger here and see that the <Navigating> tag is not being rendered on page transition.
        }
        catch (Exception ex)
        {
        }
    }
}

```

- run `dotnet run`
- Navigate between pages

PS: If you think it's just so fast that one cannot see it, I forced a delay on the Counter page by doing a long-performing for loop bound to the HTML and even with that, nothing was displayed during transition.

Tried with both InteractiveAuto and InteractiveWebAssembly and neither worked.

### .NET Version

8.0.100

### Anything else?

VSCode

dotnet --info

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100-rc.1.23463.5 [/usr/local/share/dotnet/sdk]
  8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `<Navigating>` content will be visible only while lazy-loading an assembly during navigation. That is when seeing that content is realistic. In all other cases the transition is so fast, that the content won't be even shown. @guardrex can you please clarify the documentation in the `Routing` node about the `<Navigating>` element so that we avoid the confusion? Thanks.

**Comment by ricfwolff** [comment]
Thanks!

In slow connections (mobile phones, for instance) there is a perceptive delay sometimes (> 500ms), which could benefit from such feature being available for all navigation types.

But thanks again!
