### ISSUE TITLE
Identity: Blazor: Setting Cookie.SameSite = SameSiteMode.Strict cause unexpected AuthorizationView behavior for external logins

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#52253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure if this is a bug or expected behavior.

We are seeing some, what feels like, unexpected behavior related to External Logins using .NET 8 Identity and a Blazor Web App. When we create a Blazor Web App (.NET 8), and Add Identity to the app, the basic identity works fine but when we add an External Login Provider, for example:
```
.AddMicrosoftAccount(options =>
                {
                    options.ClientId = "<CLIENTID>"; 
                    options.ClientSecret = "<SECRET>";
                }
```

And we set cookie options, for example.:
```
.AddIdentityCookies(cookie =>
{
    cookie.ApplicationCookie?.Configure(config =>
    {
        config.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        config.Cookie.SameSite = SameSiteMode.Strict;
        config.Cookie.HttpOnly = true;
        config.Cookie.IsEssential = true;
        config.Cookie.MaxAge = TimeSpan.FromSeconds(3600);
    });
})

```

The UI AuthorizeViews on the NavMenu do not seem to refresh on the initial Redirect after the External login. The External Login process works fine and the cookie is created but the left NavMenu does not seem to refresh until you select another NavMenu item. Once another NavMenu item is selected the NavMenu shows the NavMenu items that are seen when logged in.

If we set for example:
```
config.Cookie.SameSite = SameSiteMode.Lax;
```

The UI refreshes properly after the External Login process is completed and Redirected to the RedirectUrl.

### Expected Behavior

If by design provide some error to let us know? This was not easy to spot.
If this is allowed the Authorization Views should be refreshed.

### Steps To Reproduce

1. Start with VS 2022 and add a Blazor Web App (.NET 8)
2. Add NuGet <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.0" />
3. See description above to AddMicrosoftAccount. You will need to register an app in Azure AD. 
    1. Set it for Web (not SPA). 
    2. Set redirect url to: https://localhost/signin-microsoft
    3. Turn on Access Tokens
4. Set Cookie options as defined above in the description.

### Exceptions (if any)

None that I can see in the VS 2022 output nor browser console.

### .NET Version

8.0.100

### Anything else?

Windows 11 latest patches

Microsoft Visual Studio Enterprise 2022
Version 17.9.0 Preview 1.0
VisualStudio.17.Preview/17.9.0-pre.1.0+34310.174
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA741
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.101.55877
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.101.55877
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.101.55877
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.9.9
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   1.137.0.0 (v1.137.0.0@2f127d06d)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.137.0

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.9.0 (b3bca6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.1.2355806+8f4bea9f2567429c455f24b09d37645f022bbcbd
Provides languages services for ASP.NET Core Razor.

Solution Colors   1.1.44
Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.

SQL Server Data Tools   17.9.7.1
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.21025.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23523.7+0c5e24d19dc915b00b8755a8532bfb2582aa2b47
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.9.0.27 (main@0338b26)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.1.17 (remotes/origin/main@714487a984)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.9.0 (38e87ba)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.22 (d689a0e0f)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by halter73** [comment]
This is the reason `SameSite=Lax` is the default for `CookieAuthenticationOptions.Cookie.SameSite` and most browsers since 2019 rather than `SameSite=Strict`.

https://github.com/dotnet/aspnetcore/blob/00e3aaafa355bb540b6aae25d01731da6f07df61/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L18-L19

https://learn.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-8.0

>__Strict__
> Means that the browser sends the cookie only for same-site requests, that is, requests originating from the same site that set the cookie. If a request originates from a different domain or scheme (even with the same domain), no cookies with the `SameSite=Strict` attribute are sent.
> __Lax__
> Means that the cookie is not sent on cross-site requests, such as on requests to load images or frames, but is sent when a user is navigating to the origin site from an external site (for example, when following a link). This is the default behavior if the `SameSite` attribute is not specified.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value

> The UI AuthorizeViews on the NavMenu do not seem to refresh on the initial Redirect after the External login. The External Login process works fine and the cookie is created but the left NavMenu does not seem to refresh until you select another NavMenu item. Once another NavMenu item is selected the NavMenu shows the NavMenu items that are seen when logged in.

Strict cookies are not sent for cross-site requests like those when an OIDC provider redirects back to your app. Strict cookies aren't even sent if you follow a link from an external site. As you can see in the steps listed in https://github.com/aspnet/Security/issues/1231#issue-231182471, the internal `302` redirect from `GET https://app/signin-oidc?code=...&state=...` to your final return URL includes a `Set-Cookie` header. But because it's set with `SameSite=Strict` and the last document rendered to the user had an origin of `https://login.microsoftonline.com/...`, the browser does not send the cookie on the very next redirected request to the final return URL. The cookie does get sent with subsequent internal navigations as you observed.

Is there some reason this cookie needs to be `SameSite=Strict`?

> If by design provide some error to let us know? This was not easy to spot.

I'd be okay with logging some sort of warning given this misconfiguration, but it might be hard to detect. `RemoteAuthenticationHandler`s do not really know much about their `SignInScheme` other than that it's an `IAuthenticationSignInHandler`. Going out of our way to try to check if it's a correctly-configured `CookieAuthenticationHandler` might be nice, but it'd introduce a dependency that currently doesn't exist.

I'll unassign myself so we can discuss whether there's more we can do to prevent future developers from running into this issue. Maybe an analyzer would be the way to go.

**Comment by chassq** [comment]
@halter73 thank you for the awesome response. Much appreciated! That really helps to better understand the issue.

> Is there some reason this cookie needs to be SameSite=Strict?

There is no requirement for this for us. We were setting it to strict in hopes to lock down the cookie to the same-site origin but I think we now see what that does when using an external login.

I think our biggest issue was just trying to figure out the root cause of the UX issues we were seeing. It took us a good while to get back to the SameSite setting. For our part, we know now so there is nothing more to be done. Maybe not many others would run into this but if so a warning of some kind might help if feasible.
