### ISSUE TITLE
blazor.web.js missing from publish output

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#52266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have Blazor 8 Web App which runs fine in development. After publishing the app using `dotnet publish`, I've noticed all interactivity is broken because `blazor.web.js` is not included in the publish output. What am I missing?

**Update:** I've checked with a fresh Blazor 8 Web App project created with VS 17.8 RTM and `blazor.web.js` is also absent from publish output.

**Update 2:** Even by manually copying over `blazor.web.js` to the server's deployment folder, I cannot get interactivity to kick in once deployed. In development I can observe `dotnet.js` being loaded when hitting a page containing interactive components and bootstrapping WASM via `blazor.boot.json`. In production `dotnet.js` is not being loaded even though it's been deployed.

![image](https://github.com/dotnet/aspnetcore/assets/51688/9ef2dd95-2aab-41e5-ae48-f15c22e01a03)

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@oliverw thanks for contacting us.

blazor.web.js is never a file on disk, it's embedded at build time in the Endpoints.dll, that's why it doesn't show up on disk.
