### ISSUE TITLE
.NET Core 8 Blazor Web App with interactive location is Global and interactive render mode is WebAssmebly or Auto ,Page in Server Project will appear moment then jump to not found

### ISSUE THREAD

**Issue by unicorn0225** [dotnet/aspnetcore#52276]
.NET Core 8 Blazor Web App with interactive location is Global and interactive render mode is WebAssmebly or Auto ,Page in Server Project will appear moment then jump to not found, include the Error Page in template.
new pages under server project has same behaviors.
![Capture](https://github.com/dotnet/aspnetcore/assets/55499204/80c59612-36ca-4c80-86c2-0ed2cab5f52c)
![Capture2](https://github.com/dotnet/aspnetcore/assets/55499204/f3cd6808-3942-4f6d-99fc-d00555a81cc2)

**Comment by jinzhao1127** [comment]
We tracked this issue in internal bug https://github.com/dotnet/AspNetCore-ManualTests/issues/2421
/cc:  @mkArtak

**Comment by javiercn** [comment]
@unicorn0225 thanks for contacting us.

The page needs to be defined in the client assembly, otherwise it doesn't get transferred to the browser. 

The error page in particular, it's only meant to be used during SSR.

**Comment by unicorn0225** [comment]
> Same as the internal bug https://github.com/dotnet/AspNetCore-ManualTests/issues/2421 /cc: @mkArtak

this link is invalid

**Comment by javiercn** [comment]
@unicorn0225 don't worry about the link, it's not the same issue.
