### ISSUE TITLE
Incorrect swagger.json generation when using FromForm parameters without the WithOpenApi extension method

### ISSUE THREAD

**Issue by marcominerva** [dotnet/aspnetcore#52284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following endpoints:

```
app.MapPost("/api/products", ([FromForm] Product product) =>
{
    return TypedResults.NoContent();
});

app.MapPost("/api/products-with-openapi", ([FromForm] Product product) =>
{
    return TypedResults.NoContent();
})
.WithOpenApi();

public record class Product(string Name, double Price);
```

These endpoints differ only for the `WithOpenApi` extension method, but the `swagger.json` definition is quite different:

```
"/api/products": {
  "post": {
    "tags": [
      "FromFormIssue"
    ],
    "requestBody": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "required": [
              "product"
            ],
            "type": "object",
            "properties": {
              "product": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "encoding": {
            "product": {
              "style": "form"
            }
          }
        },
        "application/x-www-form-urlencoded": {
          "schema": {
            "required": [
              "product"
            ],
            "type": "object",
            "properties": {
              "product": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "encoding": {
            "product": {
              "style": "form"
            }
          }
        }
      }
    },
    "responses": {
      "204": {
        "description": "No Content"
      }
    }
  }
}


"/api/products-with-openapi": {
  "post": {
    "tags": [
      "FromFormIssue"
    ],
    "requestBody": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "$ref": "#/components/schemas/Product"
          }
        },
        "application/x-www-form-urlencoded": {
          "schema": {
            "$ref": "#/components/schemas/Product"
          }
        }
      },
      "required": true
    },
    "responses": {
      "204": {
        "description": "No Content"
      }
    }
  }
}
```

So, in Swagger I get the following result:

WRONG
![image](https://github.com/dotnet/aspnetcore/assets/3522534/154c081a-30ef-4c59-84e2-5a2005878035)

CORRECT
![image](https://github.com/dotnet/aspnetcore/assets/3522534/f57d2137-a5c4-4fb3-8dba-8c7e2ec94fe0)

### Expected Behavior

Both the endpoints should produce the same `swagger.json` definition that defines the parameters from `Form`.

### Steps To Reproduce

Minimal repro here: https://github.com/marcominerva/FromFormIssue

### .NET Version

8.0.100

**Comment by KennethHoff** [comment]
I just stumbled upon this problem as well. Good thing you made this issue or I probably wouldn't have tried your fix - as it involves a package I didn't realize existed.

**Comment by captainsafia** [comment]
The schema generation for each of these components is controlled by `Swashbuckle.AspNetCore` at the moment. To resolve this issue, we'd have to debug further into how the schema is mapped into the built-in `OpenApiOperation` in Swashbuckle to understand how the override is happening.

**Comment by KennethHoff** [comment]
Is there any discussion into creating a first party definition generator for AspNetCore? It doesn't need a full blown swagger UI and all that jazz, but just the json file would be lovely!

Swashbuckle hasn't had an update in almost a year, and NSwag currently doesn't support forms in Minimal APIs at all.

It feels weird how there's so much effort spent making the OpenAPI package and the API explorer and whatnot but seemingly in order to use it for anything useful you need a third party package (or write a lot of code yourself).

... Unless I've missed something and there is a built-in schema generator that I've managed to dodge through my web searches.

**Comment by captainsafia** [comment]
> Is there any discussion into creating a first party definition generator for AspNetCore? It doesn't need a full blown swagger UI and all that jazz, but just the json file would be lovely!

Hopefully more on this front soon. 😅 I've done some prototyping on this in [a sample branch](https://github.com/dotnet/aspnetcore/tree/safia/doc-level-with-open-api) but it needs _considerable work_ before it can formalized.

Feedback that supporting just the OpenAPI document generation into a JSON file  is great to share! I've always been of the opinion that an artifact that you can integrate with other systems (client generation, Postman, API management, etc.) is the most important aspect of this work.

**Comment by captainsafia** [comment]
I've verified that our built-in document generation is doing the right thing here and added some test coverage in https://github.com/dotnet/aspnetcore/pull/55321.

In the future, I plan on replating `WithOpenApi` on top of operation transformers so that there is a consistent experience here.

Closing this as resolved with a fix incoming in preview4.

**Comment by KennethHoff** [comment]
For completeness sake; you went with option 1, right?

**Comment by captainsafia** [comment]
> For completeness sake; you went with option 1, right?

Correct. I added a remark to the API that it's only compatible with Swashbuckle.AspNetCore (https://github.com/dotnet/aspnetcore/blob/0e4ccd1acffa96f4b54a4d40c082e2bd62e2db8c/src/OpenApi/src/Extensions/OpenApiEndpointConventionBuilderExtensions.cs#L27-L30). NSwag hasn't added support for `WithOpenApi` (see https://github.com/RicoSuter/NSwag/issues/4163).
