### ISSUE TITLE
Guidance on hosted WASM applications

### ISSUE THREAD

**Issue by akozhikkot** [dotnet/aspnetcore#52290]
Hello Team,

We have currently in production Blazor web assembly apps, for which we use the Hosted Asp.NET core option. We use App services to host this and currently this works very well as same app service can be used for the hosting of API and Web App.

Our app is protected using Azure AD (via Microsoft Identity Platform)

What is our recommendation to upgrade to .NET 8, are we better of staying on the current version , as we could not see this hosted ASP.NET Core option on Blazor wasm in .NET 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We have published guidance about how to migrate your applications to .NET 8: https://learn.microsoft.com/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#blazor

**Comment by danroth27** [comment]
@akozhikkot To be clear, existing Blazor WebAssembly apps are still supported in .NET 8. You can just retarget your existing app to net8.0, update the package versions, and you should be good to go.

You can then optionally choose to update to the Blazor Web App model, which is also documented in our .NET 7 to .NET 8 migration guidance.

If you're creating a new project and you want a similar set up to an ASP.NET Core hosted Blazor WebAssembly app, you can create a Blazor Web App with the WebAssembly interactive render mode enabled globally. Note that server-based prerendering will be on by default in a Blazor Web App, but you can turn that off if you want.

**Comment by akozhikkot** [comment]
Thank you @danroth27 for the answer. We would greatly love to upgrade and opt the new Blazor Web App with the WebAssembly interactive render mode . Can we continue to use Microsoft AAD authentication work as is in this mode ?
