### ISSUE TITLE
Aftet dotnet 8 upgrade ws-federation with ADFS broken

### ISSUE THREAD

**Issue by hheexx** [dotnet/aspnetcore#52304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating Microsoft.AspNetCore.Authentication.WsFederation from 7 to 8 login with ADFS is broken with error:

IDX14122: JWT is not a well formed JWE, there are more than four dots (.) a JWE can have at most 4 dots.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.

### Exceptions (if any)

Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException

### .NET Version

8

**Comment by martincostello** [comment]
Duplicate of #52099.
