### ISSUE TITLE
Changes to IdentityApiEndpointRouteBuilderExtensions made get api/User/manage/info pointless

### ISSUE THREAD

**Issue by nazare2020** [dotnet/aspnetcore#52311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/pull/51177

This has made /api/User/manage/info return the same info you send in the body of the request

` return TypedResults.Ok(await CreateInfoResponseAsync(user, userManager));`

`
 return new()
 {
     Email = await userManager.GetEmailAsync(user) ?? throw new NotSupportedException("Users must have an email."),
     IsEmailConfirmed = await userManager.IsEmailConfirmedAsync(user),
 };
`
Already a breaking change going from 'account' to 'manage' so might as well have got rid of the call

### Expected Behavior

Ideally it would still return some info on the user i.e. UserId etc

### Steps To Reproduce

call /api/User/manage/info with email and isEmailConfirmed values. Get the same back.

### .NET Version

8.0.100

**Comment by MackinnonBuck** [comment]
Could share an abstraction with #52769 to determine which claims to serialize.

**Comment by mikekistler** [comment]
This should be handled with #58959 -- closing.
