### ISSUE TITLE
IHttpClientFactory.GetClient(string name) to access a mutated HttpClient instance

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#52334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In a Blazor application you can have a dozen `HttpClient` 'callers'. Currently with the named or typed `HttpClient` approaches it is not easy to share or re-use a `HttpClient` instance that has been mutated after configuration, between callers.
Accessing that same instance between callers will only provide the pre-configured property values e.g. `BaseAddress` not e.g. an authorization header that has been set by one caller after successful user authentication.

This mean every caller has to manually update its `HttpClient` instance instead of being able to access the mutated values.
For a dozen callers, this becomes quite cumbersome.

This in a context where multiple distinctly-configured `HttpClient` instances need to work alongside each other. For example, a Blazor app communicating with multiple API's
 I'm not talking about the simple one-on-one scenario since the default `HttpClient` would suffice there.
 
 A named `HttpClient` appears to be the way to go but it returns a new `HttpClient` instance on each caller invoking `IHttpClientFactory.CreateClient("NamedClient1")`. So, within that caller I can mutate this client instance but only for that caller. 
 
#### Problem sample
 
Program.cs

```csharp

builder.Services.AddHttpClient("NamedClient1", client => client.BaseAddress = "https://localhost:3000");

builder.Services.AddScoped<CallingService1>();
builder.Services.AddScoped<CallingService5>();

app.MapGet("/", (CallingService1 s1, CallingService5 s5) => {
    s1.AuthorizeHttpClient("<token>");
    s5.PrintAuthValue(); // Print:     <--- Empty
});
```

CallingService1.cs

```csharp
public class CallingService1 {
    private readonly HttpClient _httpClient;
    public CallingService1(IHttpClientFactory httpClientFac) {
        _httpClient = httpClientFac.CreateClient("NamedClient1"); //    <--- Returns new instance
    }
    
    public void AuthorizeHttpClient(string? token) {
        _httpClient.DefaultHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    }
}
```

CallingService5.cs

```csharp
public class CallingService5 {
    private readonly HttpClient _httpClient;
    public CallingService5(IHttpClientFactory httpClientFac) {
        _httpClient = httpClientFac.CreateClient("NamedClient1"); //    <--- Returns new instance
    }
    
    public void PrintAuthValue() {
        Console.WriteLine("Print: " + _httpClient.DefaultHeaders.Authorization);
    }
}
```

---

### Describe the solution you'd like

A `IHttpClientFactory.GetClient(string? name = "")` to return that exact `HttpClient` instance would solve the above.

This way, 2 callers can work with the same client instance and the mutations of one caller can be leveraged by another caller.

#### Solution sample

Program.cs

```csharp

builder.Services.AddHttpClient("NamedClient1", client => client.BaseAddress = "https://localhost:3000");

builder.Services.AddScoped<CallingService1>();
builder.Services.AddScoped<CallingService5>();

app.MapGet("/", (CallingService1 s1, CallingService5 s5) => {
    s1.AuthorizeHttpClient("<token>");
    s5.PrintAuthValue(); // Print: <token>    <--- EUREKA!
});
```

CallingService1.cs

```csharp
public class CallingService1 {
    private readonly HttpClient _httpClient;
    public CallingService1(IHttpClientFactory httpClientFac) {
        _httpClient = httpClientFac.GetClient("NamedClient1"); //    <--- Returns exisisting instance
    }
    
    public void AuthorizeHttpClient(string? token) {
        _httpClient.DefaultHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    }
}
```

CallingService5.cs

```csharp
public class CallingService5 {
    private readonly HttpClient _httpClient;
    public CallingService5(IHttpClientFactory httpClientFac) {
        _httpClient = httpClientFac.GetClient("NamedClient1"); //    <--- Returns exisisting instance
    }
    
    public void PrintAuthValue() {
        Console.WriteLine("Print: " + _httpClient.DefaultHeaders.Authorization);
    }
}
```

---

### Additional context

I made a [NuGet package](https://www.nuget.org/packages/AugusteVN.HttpClient/#readme-body-tab) to work around it, with wrappers, resolvers and KeyedServices. It registers wrapped, distinctly-configured `HttpClient` instances as keyed, scoped and its resolvers.

But it looks to me that the `IHttpClientFactory` could elegantly solve this perhaps with its `_activeHandlers` which seems to store a (reference to) key-value pair of the registered named clients.

A drawback of having a shared instance is that if one caller mutates the instance with a property that could break another caller's implementation. But for that you can configure another named client or use the `.CreateClient` there.

Is it viable?

A fallback to the default `HttpClient` may be desired when no name passed or non-existing name*. Or make `name` parameter required to prevent people pulling their hair out for forgetting or misspelling the target name.

**Comment by gragra33** [comment]
You can use a [DelegatingHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=net-8.0) to manage this. Here is a YouTube video that shows you how: [Middleware Pattern For HttpClient With Delegating Handlers](https://www.youtube.com/watch?v=_u6v4D6qgDI).

**Comment by davidfowl** [comment]
> In a Blazor application you can have a dozen HttpClient 'callers'. Currently with the named or typed HttpClient approaches it is not easy to share or re-use a HttpClient instance that has been mutated after configuration, between callers.

Don't do this.  Shared mutable state is a bad idea. You don't want other pieces of code to be partying on the HttpClient at the same time. If you want to share the same instance across a single request,  there's ways of doing that. If you need to configure auth properly then there are ways of doing that (like using a delegating handler). There are likely safer ways to accomplish what you need to do.

**Comment by augustevn** [comment]
Ok thanks, I indeed had a feeling that it wasn't a great practice due to the nature of it.
I'll look into it and close this one. Thanks.
