### ISSUE TITLE
[blazor .net8] Will InteractiveAuto Component use Server mode when another Component in InteractiveServer mode?

### ISSUE THREAD

**Issue by ssccinng** [dotnet/aspnetcore#52336]
https://github.com/dotnet/aspnetcore/assets/22047352/7458e0cb-2c2f-4076-b2b5-8ebfb036896f

**Comment by MackinnonBuck** [comment]
The short answer to this question is "yes."

A longer answer can be found in [another comment](https://github.com/dotnet/aspnetcore/issues/52740#issuecomment-1852841365) that explains this in a little more detail 🙂

**Comment by MackinnonBuck** [comment]
Closing this out since the question has been answered.
