### ISSUE TITLE
[Blazor .NET8] In interactive Auto, services created in clients cannot be found if injected in components.

### ISSUE THREAD

**Issue by MetaHex** [dotnet/aspnetcore#52341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This happens to Blazor .net 8.0 in interactiveAuto mode. In program.cs, registered services are validated within program.cs that it has been registered properly. At the component level, during runtime, the injected services does not match/not found with the one registered.

Steps to reproduce.

Scenario 1) in program.cs, if add 
builder.Services.AddScoped(sp => 
    new HttpClient
    {
        BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
    });

in a component, @inject HttpClient httpClient,
in OnInitializedAsync()
httpClient.baseAddress <--- is always empty.

1 b) I've also tried named httpclientfactory service and var client = ClientFactory.CreateClient("webapi"); and baseAddress is also empty.

Scenario 2) create any services in the client side. register it in program.cs. as an example:

builder.Services.AddSingleton<AppService>(); // just an example app service to store rootUrl
var host = builder.Build();
var appService = host.Services.GetRequiredService<AppService>();
Console.WriteLine("appService get rootUrl: " + appService.GetRootUrl()); // validate 

await host.RunAsync();

In a component, @inject AppService appService
in OnInitializedAsync(), calling appService will get InvalidOperationException: Cannot provide a value for property 'appService' on type...

### Expected Behavior

Able to acquire registered service via inject. However, in all the cases I listed above, the injected is either incorrectly returned (httpClient/IHttpClientFactory case) or empty in the appService case.

### Steps To Reproduce

Steps to reproduce.

Scenario 1) in program.cs, if add 
builder.Services.AddScoped(sp => 
    new HttpClient
    {
        BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
    });

in a component, @inject HttpClient httpClient,
in OnInitializedAsync()
httpClient.baseAddress <--- is always empty.

1 b) I've also tried named httpclientfactory service and var client = ClientFactory.CreateClient("webapi"); and baseAddress is also empty.

Scenario 2) create any services in the client side. register it in program.cs. as an example:

builder.Services.AddSingleton<AppService>(); // just an example app service to store rootUrl
var host = builder.Build();
var appService = host.Services.GetRequiredService<AppService>();
Console.WriteLine("appService get rootUrl: " + appService.GetRootUrl()); // validate 

await host.RunAsync();

In a component, @inject AppService appService
in OnInitializedAsync(), calling appService will get InvalidOperationException: Cannot provide a value for property 'appService' on type...

### .NET Version

8.0.100

**Comment by davidfowl** [comment]
Did you add the service in both the client and the server?

**Comment by MetaHex** [comment]
Ah, thank you. That worked. First InteractiveAuto project.

Several suggestions: 
1) on documentation, probably nice to have a section to highlight the differences/todo for migrating from older projects. Come think of it, it's easier to migrate a server side project to interactive auto by just adding the client sides. For ones worked on hosted, it's going to be a bit more confusing.
2) probably some guidance in code separation. Server side needs to have code for server as well as clients, some files (like program.cs) would be flooded with duplicate declarations.
