### ISSUE TITLE
The JSON returned by SignalR does not contain the $type field

### ISSUE THREAD

**Issue by TonEnfer** [dotnet/aspnetcore#52342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When serializing descendant types, for methods that take a single (not a collection) parameter of the base type as an argument, the discriminator field is not added to JSON.
JSON for collection argument:
```json
{
    "type": 1,
    "target": "WeatherForecast",
    "arguments": [
        [
            {
                "$type": "extended",
                "temperatureC": -15,
                "summary": "Freezing",
                "date": "2023-11-24"
            },
            {
                "$type": "summary",
                "summary": "Mild",
                "date": "2022-11-20"
            }
        ]
    ]
}
``` 
JSON for single argument:
```json
{
    "type": 1,
    "target": "SummaryWeatherForecast",
    "arguments": [
        {
            "summary": "Mild",
            "date": "2023-11-24"
        }
    ]
}
``` 
```json
{
    "type": 1,
    "target": "ExtendedWeatherForecast",
    "arguments": [
        {
            "temperatureC": -15,
            "summary": "Freezing",
            "date": "2023-11-24"
        }
    ]
}
``` 

This is similar to the problem described previously in #44852

### Expected Behavior

I expect SignalR JSON to contain a $type field similar to responses from HTTP endpoints:
```json
{
  "$type": "summary",
  "summary": "Mild",
  "date": "2023-11-24"
}
```
```json
{
  "$type": "extended",
  "temperatureC": -15,
  "summary": "Freezing",
  "date": "2023-11-24"
}
```

### Steps To Reproduce

 [Repository with code](https://github.com/TonEnfer/SignalR_Inheritance/tree/main/SignalR_Inheritance) showing the problem.

I used the following classes to show the problem:
```c#
[JsonPolymorphic]
[JsonDerivedType(typeof(SummaryWeatherForecast), "summary")]
[JsonDerivedType(typeof(ExtendedWeatherForecast), "extended")]
public class WeatherForecast
{
    public DateOnly Date { get; set; }
}

public class SummaryWeatherForecast(string summary): WeatherForecast
{
    public string Summary { get; } = summary;
}

public class ExtendedWeatherForecast(string summary, int temperatureC): SummaryWeatherForecast(summary)
{
    public int TemperatureC { get; } = temperatureC;
}
``` 
```c#
public class WeatherForecastHub: Hub<IWeatherForecastHub>;

[SuppressMessage("ReSharper", "AsyncApostle.AsyncMethodNamingHighlighting")]
public interface IWeatherForecastHub
{
    Task SummaryWeatherForecast(WeatherForecast summaryWeatherForecast);

    Task ExtendedWeatherForecast(WeatherForecast extendedWeatherForecast);

    Task WeatherForecast(WeatherForecast[] extendedWeatherForecast);
}
```
```c#
[ApiController]
[Route("[controller]")]
public class WeatherForecastController(IHubContext<WeatherForecastHub, IWeatherForecastHub> hubContext): ControllerBase
{
    [HttpGet]
    public async Task<IEnumerable<WeatherForecast>> Get()
    {
        var forecast1 = new ExtendedWeatherForecast("Freezing", -15)
        {
            Date = DateOnly.FromDateTime(DateTime.UtcNow)
        };

        var forecast2 = new SummaryWeatherForecast("Mild") { Date = DateOnly.Parse("2022-11-20") };

        var result = new WeatherForecast[] { forecast1, forecast2 };

        await hubContext.Clients.All.WeatherForecast(result);

        return result;
    }

    [HttpGet("Summary")]
    public async Task<WeatherForecast> GetSummary()
    {
        var forecast2 = new SummaryWeatherForecast("Mild")
        {
            Date = DateOnly.FromDateTime(DateTime.UtcNow)
        };

        await hubContext.Clients.All.SummaryWeatherForecast(forecast2);

        return forecast2;
    }

    [HttpGet("Extended")]
    public async Task<WeatherForecast> GetExtended()
    {
        var forecast1 = new ExtendedWeatherForecast("Freezing", -15)
        {
            Date = DateOnly.FromDateTime(DateTime.UtcNow)
        };

        await hubContext.Clients.All.ExtendedWeatherForecast(forecast1);

        return forecast1;
    }
}
```

### .NET Version

8.0.100

**Comment by Kahbazi** [comment]
I did a little investigate and I think these line is causing this issue. 

https://github.com/dotnet/aspnetcore/blob/8be9c9e80ebb4dfa7dad7b8f6215fb146b2898c2/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L614
https://github.com/dotnet/aspnetcore/blob/8be9c9e80ebb4dfa7dad7b8f6215fb146b2898c2/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L636
https://github.com/dotnet/aspnetcore/blob/8be9c9e80ebb4dfa7dad7b8f6215fb146b2898c2/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L694

The serializer is using the instance type (which is the derived type) to serialize and I assume it has no information of the base class. Perhaps a fix is to add the argument type along side the argument list.

**Comment by acidbubbles** [comment]
If other people hit this problem, here is an indirect workaround: https://github.com/dotnet/runtime/issues/77532#issuecomment-1300541631

Using such a custom resolver can force the type discriminator, It's not a pretty solution but it's better than the alternatives (pre-serializing, which means every parameter becomes a string; using a custom JSON converter on every implementation; passing an array of the base type; etc.)
