### ISSUE TITLE
.NET 8.0 Blazor Web App EditForm loses values

### ISSUE THREAD

**Issue by ErikScandola** [dotnet/aspnetcore#52347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a simple Blazor Web App in new .NET 8.0. It creates two projects (Server and Client). In server project I created an edit form but, when I submit the form, I lose `Id` value in my `Model` and any other data not in an input in form.
I also tried using simple `<input type="hidden" @bind-value="Model.Id" />` but it doesn't preserve data.

### Expected Behavior

I tried this same code (with little arrangements) in a Blazor project with .NET 6.0 and any field not in form are preserved on submit.
How I need to change in new Blazor with .NET 8.0 code to preserve se same behaviour?

### Steps To Reproduce

    @page "/configurazione"
    @using DartsTraining.Components.Account.Shared
    @attribute [StreamRendering]

    <PageTitle>Settings</PageTitle>

    <h1>Settings</h1>

    <div class="row">
       <div class="col-md-4">
            <StatusMessage Message="@Message" />
       </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <EditForm Model="Model" method="post" OnValidSubmit="Save" FormName="Edit">
                <DataAnnotationsValidator />
                <hr />

                <p>Id: @Model.Id.ToString()</p>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-floating mb-3">
                            <InputText @bind-Value="Model.A" class="form-control" aria-required="true" placeholder="A" />
                            <label for="A">A</label>
                            <ValidationMessage For="() => Model.A" class="text-danger" />
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-lg btn-primary">Save</button>
                </div>
            </EditForm>
        </div>
    </div>

I created a separate file for code:

    public partial class Edit
    {
        [SupplyParameterFromForm]
        private SettingsDTO Model { get; set; }

        [CascadingParameter]
        private HttpContext HttpContext { get; set; } = default!;

        private List<string> Errors { get; set; } = new();

        private string Message => Errors.Count > 0 ? $"Errore: {string.Join("<br /> ", Errors.Select(error => error))}" : string.Empty;

        protected override Task OnInitializedAsync()
        {
            if (HttpMethods.IsGet(HttpContext.Request.Method)) {
                // Retrive data from db and initializing Model
            }

            return base.OnInitializedAsync();
        }

        public async Task Save(EditContext editContext)
        {
            // Update data in db
        }
    }

### .NET Version

.NET 8.0

**Comment by ErikScandola** [comment]
> @ErikScandola thanks for contacting us.
> 
> You need to give your input field a name, same as in MVC or Razor pages. The `Input*` classes do so for you automatically, but the plain input element won't.
> 
> The other bit is that Blazor by default is SSR, which means the state is not maintained across requests unless you do so explicitly (by putting it inside a form). It won't be magically passed around across requests.

I tried to use classic input hidden adding name attribute without success. I tried the same code on client project that should use WebAssembly, but it doesn't work.

**Comment by Manmohabe** [comment]
I Encountered a similar scenario working with Radzen components in SSR, Adding the Name attribute solved my the issue. 
Before <RadzenTextBox @bind-Value="Input.Email" Style="width: 100%;" />
After  <RadzenTextBox Name="Input.Email" @bind-Value="Input.Email" Style="width: 100%;" />

**Comment by ErikScandola** [comment]
> I encountered a similar problem working with Radzen components in SSR, Adding the Name attribute solved my the issue. Before <RadzenTextBox @bind-Value="Input.Email" Style="width: 100%;" /> After <RadzenTextBox Name="Input.Email" @bind-Value="Input.Email" Style="width: 100%;" />

In my case I have a property that shouldn't be editable. I could hide it with css but I think it would be a bad solution.
