### ISSUE TITLE
dotnet 7.0 and dotnet 8.0 are incompatible (host part)

### ISSUE THREAD

**Issue by bcornec** [dotnet/aspnetcore#52352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Context: Ubuntu 22.04 LTS up to date

$ sudo /usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"
install aspnetcore-runtime-6.0 dotnet-runtime-6.0 dotnet-sdk-6.0 aspnetcore-runtime-7.0 dotnet-runtime-7.0 dotnet-sdk-7.0 aspnetcore-runtime-8.0 dotnet-runtime-8.0 dotnet-sdk-8.0 dotnet-host
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-host-7.0 : Conflicts: dotnet-host
E: Unable to correct problems, you have held broken package

Whatever we try it seems it's impossible to have both dotnet-host for v7 and v8.
The other packages can be installed alongside the other version, but not the dotnet-host one.

A new compatible package should be provided for v7, which allows update or simultaneous install with dotnet-host-8.0

At least that should be correctly documented in the installation doc (which doesn't mention dotnet-host BTW).

### Expected Behavior

we would like to install both dotnet-host versions on the same machine without conflicts.

### Steps To Reproduce

See upper

### .NET Version

7.0 with 8.0

**Comment by martincostello** [comment]
This looks like an issue for either [dotnet/runtime](https://github.com/dotnet/runtime) or [dotnet/installer](https://github.com/dotnet/installer).

**Comment by alibildir** [comment]
https://bobbyhadz.com/blog/fatal-error-ocurred-the-folder-usr-share-dotnet-host-fx-does-not-exist refer this. This solved my problem

**Comment by wtgodbe** [comment]
This is likely related to your install setup - the above link should provide a good workaround. Closing this.

**Comment by bcornec** [comment]
There is no relationship with the resolution mentioned in the link and our setup where the conflict is linked to the fact we want to have 2 versions of dotnet (7 & 8) both installed on the same Ubuntu distro. We do not have issue with host xfr, but with conflicting packages.  If you try on your side, and find a way which works, please document it here so we can replicate.  Please reopen this BR or document that having both versions at the same time is unsupported, or patch the existing versions so it works.

**Comment by WhiteSymmetry** [comment]
sudo apt remove dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo apt remove aspnetcore*
sudo apt remove netstandard*
sudo apt remove dotnet-host8*
sudo apt purge dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo rm -f /etc/apt/sources.list.d/mssql-release.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list.save
sudo apt update
Install by App Center: .Net Core SDK, Stable 8.0.101 
there is no need for other installations!
(sudo snap install dotnet-sdk #Installed by App Center
sudo apt install dotnet-sdk-8.0 #Installed by App Center
sudo apt install dotnet-host-8.0 #Installed by dotnet-sdk-8.0)
dotnet workload update
source ~/.bashrc
dotnet sdk check
.NET SDKs:
Version      Status                     
----------------------------------------
8.0.100      Patch 8.0.101 is available.

dotnet --info
.NET SDK:
 Version:           8.0.100

 Workload version:  8.0.100-manifests.6c33ef20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/233/sdk/8.0.100/
 
 Host:
  Version:      8.0.0
  Architecture: x64

dotnet --list-sdks
8.0.100 [/snap/dotnet-sdk/233/sdk]
dotnet --version
8.0.100

**Comment by CannyGent** [comment]
> There is no relationship with the resolution mentioned in the link and our setup where the conflict is linked to the fact we want to have 2 versions of dotnet (7 & 8) both installed on the same Ubuntu distro. 

The solution does work... pinning the microsoft repository avoids the incompatibility which stems from dotnet7 coming from the ubuntu feed and dotnet8 coming from the Microsoft feed.
