### ISSUE TITLE
How to remove ActionId and ActionName from log messages?

### ISSUE THREAD

**Issue by kjpgit** [dotnet/aspnetcore#52361]
asp.net appears to log these whenever a service uses ILogger.  I don't want this, I only want RequestId for correlation to serilog's final request-complete log message.  

(I'm manually logging the ActionName in the serilog final log message, and logging it there once is sufficient, I don't need it logged 10 times for a request.  And I don't see why ActionId is useful at all.)

**Comment by captainsafia** [comment]
The `Actionid` and `ActionName` that you're referencing here are automatically added in the [ActionLogScope](https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/MvcCoreLoggerExtensions.cs,280) associated with the log messages. If you're logger supports including information from these scopes, then it'll do so.

You might be able to set the `IncludeScopes` property in your appsettings to avoid logging these, although that'll end up removing the `RequestId` in the `HttpLogContext`.

Your best bet might be to take advantage of Serilog's enrichers to filter out this information. Have you considered this approach?
