### ISSUE TITLE
HTTP Gone (410) In `Http.Results` APIs

### ISSUE THREAD

**Issue by GDWR** [dotnet/aspnetcore#52376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using Http.Results APIs, specifically [`TypedResults`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.typedresults), I want to beable to use `TypedResult.Gone()` rather than `TypedResults.StatusCode(StatusCodes.Status410Gone)` to simplify and narrow the return type of the function. Additionally enable the status code return to be used via autodocumentation (Swagger).

### Describe the solution you'd like

I would like `TypedResult.Gone()` to be added, which should respond with a 410 status code. Enabling me to specify `Gone` as return type, narrowing the types that a function can return.

### Additional context

Created a PR for this, due to its small nature and similarity to numerous other HTTP response types.

**Comment by martincostello** [comment]
As the associated PR introduces new public APIs, the team will need this to go through API review. You can create an issue for that here: https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=
