### ISSUE TITLE
./restore.cmd error

### ISSUE THREAD

**Issue by jimcbell** [dotnet/aspnetcore#52374]
Hi, I am following the build steps listed here: https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md

I have forked the repo, cloned, installed the latest version of node. When I execute the .\restore.cmd command this is the output I am getting: 

Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Prog in C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot (via PATH)
Build failed with exit code -1073741790. Check errors above.

This is my Execution Policy:
Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted

Is there something wrong with my setup or the command?

**Comment by captainsafia** [comment]
@jimcbell The output that you shared here doesn't look complete based on the code you called. Is there a chance you can share a screenshot?

**Comment by jimcbell** [comment]
@captainsafia The first few times I ran it that was all that was being produced in my console which was confusing because it had no error to look at above. When I run it again today it produces some more content now:
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
Detected JDK in C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot (via PATH)
at Exec-Process, C:\Users\jlc06\coding\source\open-source\aspnetcore\eng\common\tools.ps1: line 89
at MSBuild-Core, C:\Users\jlc06\coding\source\open-source\aspnetcore\eng\common\tools.ps1: line 832
at InitializeToolset, C:\Users\jlc06\coding\source\open-source\aspnetcore\eng\common\tools.ps1: line 707
at <ScriptBlock>, C:\Users\jlc06\coding\source\open-source\aspnetcore\eng\build.ps1: line 419
at <ScriptBlock>, <No file>: line 1
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"

**Comment by captainsafia** [comment]
@jimcbell Have you checked that you have permission to execute scripts on the machine that you're compiling on? If you're not having success on your local machine, you may want to consider following [our Codespaces goal](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#codespaces-on-github).

**Comment by jimcbell** [comment]
@captainsafia Yes I can execute scripts on my machine. I am running powershell in admin and have set the execution policy to unrestricted.

**Comment by captainsafia** [comment]
@jimcbell Bummer! I'll admit I'm a little stuck on what guidance to give based on the info you shared here. As a last ditch effort, can you try cloning the repo into a different directory and seeing if that works?

**Comment by amcasey** [comment]
Some random things to try:
1. I sometimes have better luck building from a Visual Studio Developer Prompt.  If you have multiple msbuilds installed, that will make the invocation unambiguous.
2. What happens if you pass `-nobuildjava`?

**Comment by jimcbell** [comment]
@captainsafia 
I cloned the repo in a new folder and the restore command worked! Thank you!
Originally I had forked the repo and then cloned it, do you have any idea why that might now have worked?

**Comment by amcasey** [comment]
@jimcbell Sometimes things (e.g. package restore) partially succeed and then get stuck so that subsequent attempts fail.  When this happens, I like to try `git clean -xddff`, which tends to be faster than making a new clone.

Sounds like your issue has been resolved?

**Comment by jimcbell** [comment]
@amcasey Yes it is thanks!
