### ISSUE TITLE
Error on Blazor FileInput upload - The format of value '' is invalid

### ISSUE THREAD

**Issue by 0xor1** [dotnet/aspnetcore#52375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Blazor wasm net8.0, I can use the `FileInput` to upload most file types like images, pdfs, text, video, etc. But when I randomly selected a `.nupkg` file, it doesn't attempt the upload at all. It just writes in the console `The format of value '' is invalid. dotnet.native.8.0.0.fdi2l3wiik.js:8`

The debugger says it is this line `out(UTF8ArrayToString(tty.output, 0));` expanded below:
```js
                put_char: function(tty, val) {
                    if (val === null || val === 10) {
                        out(UTF8ArrayToString(tty.output, 0));
                        tty.output = []
                    } else {
                        if (val != 0)
                            tty.output.push(val)
                    }
                },
```
I'm not sure why it would fail to even try to start the upload, I'm not attempting to restrict by any file type. Afaik it should take any file.

### Expected Behavior

it should be able to process any file type for before uploading it

### Steps To Reproduce

select a .nupkg file in the FIleInput control and try to upload it.

It is happening in this repo here https://github.com/0xor1/oak , the live demo link takes you to a running instance that you can register/sign up in if you dont want to run it locally, but I imagine you could replicate it in other apps too.

### Exceptions (if any)

no exceptions it just writes to browsers console `The format of value '' is invalid. dotnet.native.8.0.0.fdi2l3wiik.js:8`

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@0xor1 thanks for contacting us.

Please provide a minimal repro (as a public github repository), it's impossible for us to dig through large projects to attempt to determine if there is an issue in the framework.

**Comment by 0xor1** [comment]
issue was setting ContentType header as empty string for the file upload, I have worked around this by using `application/octet-stream` if the `InputFile` control BrowserFile object has file type value of empty string
