### ISSUE TITLE
Trying to Render HTML for a HTMX integration..

### ISSUE THREAD

**Issue by Scripter1978** [dotnet/aspnetcore#52382]
Sorry PC crashed when I submitted this originally I didn;t know it actually posted...
So here is the issue/concern I have... Here is the scenario.
Use Razor component and render it as HTML, In my specific scenario I am using the Javascript library HTMX. With HTMX one does not use Action attribute on a Form element. I used the information at this link to perform the rendering but it fails if I add a <form> element without an action attribute..
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0

When I track down the specifics of where the code fails it does so initially by checking for form elements then tries to add an action if it is not there... The comments in the attached section of code does not seem to make a clear sense for reason. It seems to limit the developer's ability to do what is needed for the specific situation that they have. 
Additionally why would you try to add an action if there is no action there and since there is no action there how do you expect to get the url for that action. (I am sure there is something I am really just missing in this code. 

https://github.com/dotnet/aspnetcore/blob/57a8a2ac464da4e7e5c1f73d1280e724204cfffb/src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs#L360

Added GitHub Repo

https://github.com/Scripter1978/BlazorFailNoFormAction

**Comment by javiercn** [comment]
@Scripter1978 thanks for contacting us.

Can you provide more details? It's impossible for us to do anything with the info you provided.

**Comment by Scripter1978** [comment]
I didn't comment but rather updated the original post. Please see the post was updated

**Comment by javiercn** [comment]
@Scripter1978 thanks for the additional details.

Unfortunately, we can't exactly tell what you are trying to point out. If you can create a minimal repro project as a public github repository that we can take a look at, it will help us make progress on this issue.

**Comment by Scripter1978** [comment]
Added a new repo on github for this. I removed all code not needed..
https://github.com/Scripter1978/BlazorFailNoFormAction

When the code is ran there are two links, one that is labled "Fail No Action Form"  which will provide you with the error that I encounter

and then a link labeled  "Success Has Action in Form Tag" which will show how things should work even without an Action attribute in the form element.

**Comment by xxnickles** [comment]
I believe I came across with a similar scenario Yesterday. I am also using HTMX and my idea was replacing a rendered from with HtmlRenderer provided by a minimal API endpoint, but I was getting an "HttpNavigationManager has not been initialized" error, even in cases where I explicitly added an action. What this is telling me is that current forms cannot be rendered "outside of ASP.NET Core" (likely for this dependency that OP is pointing), which is something it should be possible. Something I am not sure as well is if AntiforgeryToken token components can be rendered (and be functional) using the HTMLRenderer.

@Scripter1978 the work around I end applying was making the form + the AntiforgeryToken static (kind of a wrapper component) and make the fields + button (which contains the HTMX trigger) the swappable parts. Here an example:

```cs
<form >
        <AntiforgeryToken/>
        @switch (Anime)
        {
            case InterestedAnime interestedAnime:
                <InterestedAnimeControls ControlData="@interestedAnime"></InterestedAnimeControls>
                break;
            case NotAvailableAnime notAvailableAnime:
                <NotAvailableAnimeControls ControlData="@notAvailableAnime"></NotAvailableAnimeControls>
                break;
            case SubscribedAnime subscribedAnime:
                <SubscribedAnimeControls ControlData="@subscribedAnime"></SubscribedAnimeControls>
                break;
            case UnSubscribedAnime unSubscribedAnime:
                <UnsubscribedAnimeControls ControlData="@unSubscribedAnime"></UnsubscribedAnimeControls>
                break;
            default:
                <div class="badge badge-error gap-2">Nothing yet!</div>
                break;
        }
    </form>
```

and here couple of the swapable controls

```cs
  <fieldset class="flex flex-nowrap items-center justify-between">
        <div class="badge badge-info gap-2">Interested</div>
        <div class="gap-2">
            <input type="hidden" name="@nameof(AvailableTvSeriesControlData.Title)" @bind="ControlData.Title"/>
            <input type="hidden" name="@nameof(AvailableTvSeriesControlData.UserId)" @bind="ControlData.UserId"/>
            <button class="btn btn-primary btn-xs" hx-post="tv/remove-interested" hx-target="closest fieldset" hx-swap="outerHTML">Remove from Interested</button>
        </div>
    </fieldset>
```
```cs
  <fieldset class="flex flex-nowrap items-center justify-between">
        <div class="badge badge-warning gap-2">Not Available</div>
        <div class="gap-2">
            <input type="hidden" name="@nameof(AvailableTvSeriesControlData.Title)" @bind="ControlData.Title"/>
            <input type="hidden" name="@nameof(AvailableTvSeriesControlData.UserId)" @bind="ControlData.UserId"/>
            <button class="btn btn-primary btn-xs" hx-post="tv/add-interested" hx-target="closest fieldset" hx-swap="outerHTML">Add to Interested</button>
        </div>
    </fieldset>
```

As you can see, I am swapping the current field set for the one I get from the server. It is not as nice as being able to swap the whole form, but it is a viable alternative

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
