### ISSUE TITLE
HTTP Gone (410) In `Http.Results` APIs

### ISSUE THREAD

**Issue by GDWR** [dotnet/aspnetcore#52381]
## Background and Motivation

When using the C# [ASP.NET Minimal API](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis) format, and specifically the [TypedResults](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses#typedresults-vs-results) I wanted to utilize the [410 Gone HTTP status code](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9) as an API response to semantically let the requester know the resource is **permanently gone**, and hyperlinks to such item should be removed.

At the time [I used](https://github.com/GDWR/Cynnamon/blob/37c0188febe8cea6cb2bb8b6650e60a581b21f61/Cynnamon/Program.cs#L31):
```csharp
TypedResults.StatusCode(StatusCodes.Status410Gone);
```
to correctly return a 410 response to the client, but without narrowing the type and elevating this information for OpenAPI auto-documentation meaning it was unaware it could return 410, without feeding it this information using `.Produces(...)`

This made the return type `Results<..., StatusCodeHttpResult>>`, allowing any arbitrary response code to be presented via `TypedResults.StatusCode` circumventing partially the, to my understanding, [purpose of `TypedResults`](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses#typedresults-vs-results).

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http.HttpResults;

+ public sealed class Gone : IResult, IEndpointMetadataProvider, IStatusCodeHttpResult
+ {
+     public int StatusCode;
+     public Task ExecuteAsync(HttpContext httpContext);
+ }
```

```diff
namespace Microsoft.AspNetCore.Http;

public static class TypedResults
{
+    public static Gone Gone();
}

public static class Results
{
+    public static IResult Gone();
}
```

## Usage Examples

Hello World:
```csharp
app.MapGet("/", () => TypedResult.Gone());
```

Resource permanently deleted:
```csharp
app.MapGet("/product/{productId:int}",
    async Task<Results<Ok<Product>, NotFound, Gone>> (DbContext db, int productId) => 
        await db.Products.FindAsync(productId) switch {
            null => TypedResults.NotFound(),
            {  Deleted: true } => TypedResults.Gone(),
            var product => TypedResults.Ok(product),
        }
}));
```

## Alternative Designs

This API change continues a design [already in place](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.typedresults), as it is adding to already existing set of TypedResult HTTP Codes. Alternatives to this would conflict with this design requiring a lot more consideration, and deviate from the aim of this proposal is to enable 410 Gone within said API.

## Risks

My main concern is, that the HTTP standard the `TypedResults` was developed against does not include 410. To me, 410 is a commonly accepted and widely adopted code, [including in the ASP.NET library](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes.status410gone#microsoft-aspnetcore-http-statuscodes-status410gone). So my concern for this being the case is small.

**Comment by GDWR** [comment]
Created for #52376

**Comment by halter73** [comment]
API Review Notes:

- MVC does not this either even though `410 Gone` has been standardized for a long time.
- It's not a goal for our result types to be exhaustive. For more niche use cases, using a `StatusCodeHttpResult` or a custom result type is fine.
- If usage of this type were to become way more common, we would reconsider.
- Do any common clients actually treat a 410 significantly differently than a 404?

API rejected without prejudice. We could reconsider given more information and feedback.
