### ISSUE TITLE
What Should We Expect the First Load of InteractivityWasm

### ISSUE THREAD

**Issue by mckaragoz** [dotnet/aspnetcore#52406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i start a new web app template with only wasm interactivity, i have a white blank page when run the project. On the second run or after, the app looks properly.

Is it expected? I didn't find something in docs that how InteractiveWasm's first load works. Do we see loading page (wait for load) like previous hosted wasm or some static page?

**Comment by javiercn** [comment]
@mckaragoz thanks for contacting us.

> When i start a new web app template with only wasm interactivity, i have a white blank page when run the project. On the second run or after, the app looks properly.

You should see the prerendered output from the server at a minimum. 

Can you provide a minimal repro project as a public github repository?
