### ISSUE TITLE
FocusOnNavigate does not work (dotnet8 - BlazorWebApp)

### ISSUE THREAD

**Issue by ZANZAAA** [dotnet/aspnetcore#52412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The user's scrolling position will be maintained when navigating to a new page.  
The `<h1>` element does not have the focus.

 Even though
-  `<FocusOnNavigate RouteData="@routeData" Selector="h1" />` is correctly set
-  The pages have a `h1` HTML tag

### Expected Behavior

After navigating from one page to another, sets focus to an element matching a CSS selector.
[Source](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.routing.focusonnavigate?view=aspnetcore-8.0)

### Steps To Reproduce

1. Create a new project using the new **Blazor Web App** template.
2. Add some content to the sample pages (Home, Counter, Weather) so users need to scroll to get to the bottom of it. 
```
<br />
<div style="height:2000px; background-color:bisque"></div>
<br />
```
3.  Once at the bottom bottom of the page, use the menu on the left to navigate to a different page. 
4. The user will remain at their current scrolling position. The focus is not set on the `<h1>` element.

### .NET Version

8

**Comment by ZANZAAA** [comment]
I added this piece of code to my `main.js` and it works.
```
window.Blazor.addEventListener("enhancedload", () => {
    window.scroll({ top: 0, left: 0, behavior: 'instant' });
});
```

Found the solution while reading https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0 (loading scripts for SSR pages)

**Comment by sonnemaf** [comment]
This issue should not be fixed asap. I can't wait 11 months (.NET 9), it is a showstopper.

Have a look at this video. Just create 2 long pages and add them to the NavMenu. It is horrible. I hope there is a workaround.

https://github.com/dotnet/aspnetcore/assets/9335559/ed8a3928-c35f-4173-b3da-f30b3ed6f5bb

**Comment by Andrey-2021** [comment]
I have this problem in 7 (version).
I have many long pages in my Blazor Server project.
We need to solve this problem as soon as possible.
You can't wait for version 9

**Comment by ZANZAAA** [comment]
@Andrey-2021 @sonnemaf  Did you see [my previous comment](https://github.com/dotnet/aspnetcore/issues/52412#issuecomment-1848327945)

I know it's a dirty/quick fix but at least you can use Blazor on prod with a nicer navigation experience.

**Comment by sonnemaf** [comment]
@ZANZAAA Yes your fix it works! Still hope to get the bug fix earlier than `.NET 9`

![App.razor](https://github.com/dotnet/aspnetcore/assets/9335559/9ce44525-6b90-43ed-ac79-afc7ca39f9c7)

**Comment by Andrey-2021** [comment]
Now you can  in `<FocusOnNavigate RouteData="routeData" Selector="h1">` in  Selector="h1" 
Instead of 'h1' write 'h6'-an UNUSED selector in your code.
I do this. It's work.
But this is an "incorrect" decision,
until the developers fix the bug

**Comment by mkArtakMSFT** [comment]
This will be handled as part of #53142

**Comment by thirstyape** [comment]
I experienced this and resolved by using a CSS id tag.

```razor
<FocusOnNavigate RouteData="@routeData" Selector="#main-content-section" />
```

**Comment by acgarzon** [comment]
I've upgraded to .NET 9 and this problem has not been fixed. I've tried the Selector as a class, id, multiple elements, nothing works.
