### ISSUE TITLE
Including Microsoft.AspNetCore.Components.WebAssembly.DevServer 8.0.0 breaks WebAPI debugging

### ISSUE THREAD

**Issue by Coruscate5** [dotnet/aspnetcore#52413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See title - inclusion of the DevServer reference on a .NET 8 GA WebAPI project completely breaks debugging (symbols are not loaded)

### Expected Behavior

Application should either just continue working, or an error should occur before runtime - in existing MSFT samples that I upgraded from 7.0, DevServer and Server references were included in the WebAPI project.

### Steps To Reproduce

1. Create a Blazor WASM .NET core hosted solution in .NET 7 (via CLI, since template is now gone)
2. Upgrade whole project + deps to 8
3. Debugging on WebApi (Server) breaks, symbols don't load

### Exceptions (if any)

None, as PDB isn't found in Modules

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@Coruscate5 thanks for contacting us.

You don't need to reference the DevServer package if you are hosting the app within ASP.NET Core. The DevServer is only for standalone scenarios.
