### ISSUE TITLE
[Blazor] Supplying a `null` parameter value to an interactive root component causes a `NullReferenceException` on enhanced navigation

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#52434]
## Summary

If a `null` value is supplied as a parameter to a render mode boundary component during static SSR, and the SSR'd component is matched up with an existing interactive root component, a `NullReferenceException` gets thrown by the framework.

## Steps to reproduce

1. Create a Blazor Web App with Server interactivity
2. Define a component (`MyComponent.razor`):
    ```razor
    @inject NavigationManager NavigationManager
    
    <button @onclick="@(() => NavigationManager.Refresh())">Refresh</button>
    
    @code {
        [Parameter]
        public string? Value { get; set; }
    }
    ```
4. Render the component from `Home.razor` and supply the value `null` for the `Value` parameter:
    ```razor
    <MyComponent Value="@null" @rendermode="InteractiveServer" />
    ```
5. Run the app
6. Click the button labeled "Refresh"
7. Observe that an exception gets thrown and the circuit gets terminated

## Relevant output

Stack trace:

```text
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.WebRootComponentParameters.DefinitelyEquals(Microsoft.AspNetCore.Components.WebRootComponentParameters other) Line 43
	at Microsoft.AspNetCore.Components\WebRootComponentParameters.cs(43)
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.WebRootComponentManager.WebRootComponent.UpdateAsync(Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer renderer, System.Type newComponentType, Microsoft.AspNetCore.Components.ComponentMarkerKey? newKey, Microsoft.AspNetCore.Components.WebRootComponentParameters newParameters) Line 245
	at Microsoft.AspNetCore.Components.Server.Circuits\RemoteRenderer.cs(245)
.
.
.
```

## Proposed fix

Update [`WebRootComponentParameters`](https://github.com/dotnet/aspnetcore/blob/5b1ad1ee4934be7d587e50670524876763cd45eb/src/Components/Shared/src/WebRootComponentParameters.cs#L48-L49) to account for the possibility that the parameter values are `null` rather than being valid `JsonElement`s.

**Comment by javiercn** [comment]
@MackinnonBuck good catch.

Do you think this has been the case since the beginning or is this a new .NET 8.0 behavior.

**Comment by MackinnonBuck** [comment]
@javiercn  `WebRootComponentParameters` was a type we introduced in .NET 8, so it only affects .NET 8 (specifically Blazor Web apps; pure Server or WebAssembly apps shouldn't be affected)

**Comment by javiercn** [comment]
@MackinnonBuck @mkArtakMSFT parking this in 8.0.x as I think it is patchable, feel free to move it otherwise
