### ISSUE TITLE
`InvalidOperationException` occurs on `onsubmit` event when using `NavigateTo` method with non-ASCII characters on Blazor SSR render mode.

### ISSUE THREAD

**Issue by runceel** [dotnet/aspnetcore#52438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`InvalidOperationException` occurs on `onsubmit` event when using `NavigateTo` method with non-ASCII characters on Blazor SSR render mode. Only ASCII case works fine.

```csharp
// OK
NavigationManager.NavigateTo("navtarget?text=HelloWorld");

// Error
NavigationManager.NavigateTo("navtarget?text=😀");
```

The error page:
![image](https://github.com/dotnet/aspnetcore/assets/79868/84fa1ccc-de91-4f32-8093-eddab5139916)

The stack trace:
```
InvalidOperationException: Invalid non-ASCII or control character in header: 0xD83D
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(char ch)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(string headerCharacters, bool requireAscii)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(string headerName, StringValues headerValues, Func<string, Encoding> encodingSelector)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Location(StringValues value)
Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.HandleNavigationException(HttpContext httpContext, NavigationException navigationException)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__10_0>d.MoveNext()
Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

Navigating works without error.

## Scratch
1. Create a Blazor Web App project.
  - Authentication type: None
  - Interactive render mode: None
  - Interactivity location: Per page/component
  - Uncheck Include sample pages
     ![image](https://github.com/dotnet/aspnetcore/assets/79868/ef4cffcb-a982-488b-bdb8-9d5dc343766d)

2. Edit `Components/Pages/Home.razor` like below:
```razor
@page "/"
@inject NavigationManager NavigationManager

<PageTitle>Home</PageTitle>

<form method="post" @formname="form1" @onsubmit="Navigate">
    <AntiforgeryToken />
    <input type="submit" />
</form>

@code {
    private void Navigate() => 
        NavigationManager.NavigateTo("somepage?text=😀");
}
```

3. Launch the project.
4. Click the submit button.

## Use a repro project

I created a sample project for repro.
https://github.com/runceel/NoAsciiError

1. Clone the repository.
2. Open NoAsciiError.sln
3. Launch the project
4. Click `NavigationManager.NavigateTo("navtarget?text=😀")` button.

### .NET Version

8.0.100

### Anything else?

I faced the error when implement a search page like Bing and Google.
Those pages have a textbox and a submit button. And then search result page has search key words in query parameters.
If search key worlds are non ASCII characters such as Emoji and Japanese and other languages, the error occurs.
I guess it is a serious blocker to use Blazor SSR mode.

**Comment by runceel** [comment]
I tested it on additional platforms.
The result is:

|Server|OK/NG|Comment|
|-----|-----|-----|
|Kestrel|NG| |
|IIS Express|OK| |
|App Service on Windows|NG|No error. But 😀 was replaced to ??.|
|App Service on Linux|NG| |

**Comment by javiercn** [comment]
@runceel thanks for contacting us.

Special characters need to be encoded, as they are not allowed in the Header. Likely related to https://github.com/dotnet/aspnetcore/issues/4919

**Comment by runceel** [comment]
When I noticed this error, I used `NavigationManager.NavigateTo(NavigationManager.GetUriWithQueryParameter("text", "😀"));'. In `GetUriWithQueryParameter`, all parameters were escaped. But the error occured.

**Comment by runceel** [comment]
@javiercn I apologize for the consecutive replies.
I tested it on ASP.NET Core Razor Pages, and same error occured when non-encoded URL, and then encoded URL case works fine.

```razor:Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <input type="submit" />
</form>
```

```csharp:Index.razor.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication29.Pages;
public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }

    public IActionResult OnPost()
    {
        // NG
        // return Redirect("next?text=😀");

        // OK
        return Redirect($"next?text={Uri.EscapeDataString("😀")}");
    }
}
```

However, this issue occurs even if I use encoded URL. There is not workaround. So I guess it is blazor specific issue.
