### ISSUE TITLE
QuickGrid in Blazor Server .Net 8 Not available

### ISSUE THREAD

**Issue by davem7714** [dotnet/aspnetcore#52463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently converted my Blazor Server app from .Net 7 to .Net 8 and have added the NuGet package for Microsoft.AspNetCore.Components.QuickGrid .  When I try to add a QuickGrid component, even if I have a @using for it, it does not see it and I can't figure out why.  I created a temp Blazor Web App and was able to add a QuickGrid component with no issue although I found I also needed to add the NuGet package Microsoft.AspNetCore.Components.Web.
I just need to know what things I need to look at to figure out why it's not available in my converted App.

### Expected Behavior

I expected that after I converted my Blazor Server App from .Net 7 to .Net 8, I would be able to use a QuickGrid component but that isn't happening.

### Steps To Reproduce

Take Blazor Server .Net 7 app and convert project to .Net 8 by opening Project Properties and pointing to .Net 8.
Add NuGet Package Microsoft.AspNetCore.Components.Web
Add NuGet Package Microsoft.AspNetCore.Components.QuickGrid
Add reference to Razor Page
Attempt to add <QuickGrid ...../> component.

### .NET Version

8

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/57457458/f685702d-ace0-47ba-9ef3-c0887c017a6f)

**Comment by javiercn** [comment]
@davem7714 thanks for contacting us.

There should be no issue using quick grid in a Blazor Server app. Can you provide a minimal repro project that demonstrates your issue?
