### ISSUE TITLE
Submit enhanced forms programatically

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#52479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We are heavily (ab)using the enhanced Blazor forms introduced in .NET 8. We do not use any Blazor interactivity all (neither Server nor WASM). Just SSR, Enhanced Forms, Streaming Rendering and some client side interactivity provided by HTMX and AlpineJS. 

Enhanced Forms are used as command handlers which is working fine. Now those forms all have to reside on the page as markup to benefit from enhanced navigation provided by blazor.web.js. 

### Describe the solution you'd like

It would be nice if we could utilize something like the form builder below to submit forms directly levering enhanced navigation for handling the response.

### Additional context

```
export default function createBlazorForm(name: string, fields: {}): FormData {
  const result = new FormData();

  // Set Blazor form handler
  result.append("_handler", name);

  // Set antiforgery token
  const el = document.querySelector("input[name=__RequestVerificationToken]");
  if (!el) {
    throw new Error("Unable to find antiforgery token on page");
  }

  result.append("__RequestVerificationToken", el.value);

  // Set fields
  Object.keys(fields).forEach(x => {
    result.append(x, fields[x]);
  });

  return result;
}
```

**Comment by javiercn** [comment]
@oliverw thanks for contacting us.

If I understood correctly, you want to integrate with the enhanced navigation system to perform an action without an existing form on the page?

Is your ask to be able to "pass" your request to the enhanced navigation system so that it applies whatever diffs came back from the server?
