### ISSUE TITLE
Add Content-Id as a header name

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/aspnetcore#52486]
## Background and Motivation

It would be great if the `Microsoft.Net.Http.Headers.HeaderNames` class could also contain a constant for the "Content-Id" header so developers don't need to rely on custom constants prone to typos.

## Proposed API

```diff
namespace Microsoft.Net.Http.Headers;

public static class HeaderNames
{
+    public static readonly string ContentId = "Content-Id";
}
```

## Usage Examples

```csharp
using System;
using Microsoft.Net.Http.Headers;

Console.WriteLine(HeaderNames.ContentId); // prints "Content-Id"
```

As a reference, [MimeKit has this](http://www.mimekit.net/docs/html/P_MimeKit_MimeEntity_ContentId.htm).

**Comment by martincostello** [comment]
There's a good change this API suggestion will not be accepted. From the code:

https://github.com/dotnet/aspnetcore/blob/15cf8ce0475bb2a8deb382cd43e2a9a112557c53/src/Http/Headers/src/HeaderNames.cs#L9-L10

I imagine adding this would need a highly-motivating case.

**Comment by halter73** [comment]
API Review Notes:

- We don't think this header is common enough for inclusion in `HeaderNames`.
- It appears this was first standardized in 1998, and not many people have requested this.
- Looking at https://grep.app/search?q=%22Content-Id%22&filter[lang][0]=C%23, most existing usage is infrastructure code. More common headers get far more usage.

API rejected.
