### ISSUE TITLE
Set < routes@rendermode= "Interactive Server" / > how to set the component to static rendering mode

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/aspnetcore#52503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Set < routes@rendermode= "Interactive Server" / > how to set the component to static rendering mode

### .NET Version

8.0.100

**Comment by gabephudson** [comment]
There is not currently a direct way to do this. See this issue...
https://github.com/dotnet/aspnetcore/issues/51046
