### ISSUE TITLE
Should not UseAuthentication method check services registration same way as UseAuthorization does?

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#52505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am surprised that `UseAuthorization` method fails immediately, if required services are not registered, but `UseAuthentication` always succeeds and exception is thrown later when calling `app.Run()`

Is it by design?

### Describe the solution you'd like

I'd prefer some consistency in behavior if possible.

**Comment by captainsafia** [comment]
@voroninp Thanks for filing this issue!

I think this is largely historical. For the authorization layer, we register a marker service in DI that we then check for in the middleware to ensure that the DI container is prepped. We don't have a similar marker service for the authentication layer, so it's not clear what service we should check for. We could use a similar check to [what is done in the WebApplicationBuilder](https://source.dot.net/#Microsoft.AspNetCore/WebApplicationBuilder.cs,433).

I think we'd be open to a PR modifying the behavior here if you're interested in opening one!

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. It's not a priority for us to address this, but if you submit a PR, we'll take a look. Closing this out for now.
