### ISSUE TITLE
After updating .NET 7 Blazor server app to .NET 8, deployment to IIS breaks app when in a folder rather than single website

### ISSUE THREAD

**Issue by shoffma1** [dotnet/aspnetcore#52517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When deploying to a virtual application in IIS, via Visual Studio folder deployment, such as myserver/myapp, changing base href="/myapp" and adding app.UsePathBase("/myapp/") aren't being used by calls to load blazor.web.js, or other resources from new App.razor file

### Expected Behavior

Apps deployed to folders should not need to have a base path set, as they work this way in .NET 6 and .NET 7.

### .NET Version

8.0.100

**Comment by shoffma1** [comment]
Actually same behavior with new Blazor Web App template, when choosing Interactivity as "Server" and "Global".  Deploy to a virtual application subfolder on IIS, and no files are found (blazor.web.js, etc.). Both before and after changing base href in App.Razor and adding app.UsePathBase in Program.cs

**Comment by surayya-MS** [comment]
Thanks for filing this issue. Could you please provide a minimal repro so we can investigate?
Also, here it should end with `/` href="/myapp/"

**Comment by shoffma1** [comment]
> Thanks for filing this issue. Could you please provide a minimal repro so we can investigate? Also, here it should end with `/` href="/myapp/"

Adding the trailing slash worked of course.  Could swear I tried that already. Thanks!
