### ISSUE TITLE
Add an option for specifying the port for npm

### ISSUE THREAD

**Issue by stephtr** [dotnet/aspnetcore#5252]
Currently `UseReactDevelopmentServer` and `UseAngularCliServer` randomly select a port for starting the npm script. However in a few cases (for example when caching the webpack configuration) it would be useful to be able to specify the port being used.
Would it therefore make sense to add an optional port parameter to those two functions?

**Comment by hellocontrol-bng** [comment]
+1 - this would solve a big problem for us.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by huysentruitw** [comment]
Isn't this already implemented with https://github.com/dotnet/aspnetcore/pull/16599 ?

**Comment by stephtr** [comment]
Thanks, that's true.
