### ISSUE TITLE
Authentication with WebApplicationFactory/TestServer HttpClient

### ISSUE THREAD

**Issue by JakubJanowski** [dotnet/aspnetcore#52536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a server with Digest authentication enabled and I would like to include that in my integration tests. I was trying to set up my tests using the `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory` but could not find a way to make it work.

With a regular HttpClient it is working out of the box after specifying Credentials for an HttpClientHandler.
```C#
HttpClientHandler handler = new ();
handler.Credentials = new NetworkCredential("test_user", "hunter2");
HttpClient client = new (handler);
HttpResponseMessage response = await client.GetAsync("http://localhost:5001/");
response.EnsureSuccessStatusCode(); 
```

For the WAF client, the only way i see to make it work, would be to add an Authorization header manually. Unfortunately the header's value can't be set up-front as constant because Digest authentication uses nonces. I also can't use the built-in mechanism for authentication used by HttpClient because it is internal. So, unless there is some other workaround I'm missing, I would have to implement my own client authentication logic.

> 

### Describe the solution you'd like

Maybe TestServer could use internal `System.Net.Http.AuthenticationHelper` for authentication and allow configuring credentials and other related properties in a separate parameter to CreateClient, e.g.
```C#
server.CreateClient(options => {
    options.Credentials = new NetworkCredential("test_user", "hunter2");
})
```

**Comment by Tratcher** [comment]
The TestServer does not give you a fully functional client, it's a fake client that directly connects to the server in memory. It does not have many client features like built in authentication.
