### ISSUE TITLE
"Authorize" attribute in razor page in webassembly project requires also authorization on server side

### ISSUE THREAD

**Issue by ihorlazarenko** [dotnet/aspnetcore#52530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you use  "Authorize" attribute on page in hosted client project and you have not authorization on server and you check this page directly navigated by URL you will get error (prerendering is disabled)

### Expected Behavior

Server middleware shouldn't check client's authorization when prerendering is disabled. I believe it should be even for server side rendering.

### Steps To Reproduce

1. use "Blazor web app" and create hosted Blazor webassembly application with global interactivity location without authentication
2. add custom dummy authentication to client project
```
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider,DummyAuthenticationStateProvider>();
public class DummyAuthenticationStateProvider: AuthenticationStateProvider
{
    public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, "test user"),
            new Claim(ClaimTypes.Role, "test role")
        };
        var identity = new ClaimsIdentity(claims, "Custom authentication type");
        var principal = new ClaimsPrincipal(identity);

        return await Task.FromResult(new AuthenticationState(principal));
    }
}
```
3. add `@attribute [Authorize]` to Counter page 
4. remove prerender from components
```
<HeadOutlet @rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)" />

<Routes @rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)" />
```
5. run and open page '/counter' in browser using URL input(not from menu) and you will get exception about authorization is not added. When you open /counter page from navigation menu browser will show page without error.

### Exceptions (if any)

An unhandled exception occurred while processing the request.
InvalidOperationException: Endpoint /counter (/counter) contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAuthorization() must go between them.
Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)

### .NET Version

8.0.100

**Comment by surayya-MS** [comment]
cc @javiercn

**Comment by drapka** [comment]
Same problem here. I am migrating our Blazor WASM static web app to the new (ASP.Net Core) hosting model and I get the error when directly navigating to a specific page which requires authorization.

**Comment by halter73** [comment]
This is the same fundamental issue described in #52063. I'm going to close this as a dupe since that has gotten more activity.
