### ISSUE TITLE
asp.net core 8 部署到iis上出现了问题

### ISSUE THREAD

**Issue by toolgood** [dotnet/aspnetcore#52539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

之前.net 7是没有这个问题的
环境 window 2012R2
一、无法快速替换网站文件，.net 7时，直接将网站暂停，几秒后就可以快速替换文件，现在要等很长时间。
二、应用程序池回收就有问题，关闭后再启动出现错误提示，如以下图片 
![1701528835601](https://github.com/dotnet/aspnetcore/assets/17310407/d4ad32dc-5718-4e65-86e4-f96efec4c6bb)

三、安装.net 8后，Run dotnet --version 显示 2.1.200
![图片](https://github.com/dotnet/aspnetcore/assets/17310407/42cc9cd3-4922-436b-b959-c2f45f8aaeb7)
![1701529575573](https://github.com/dotnet/aspnetcore/assets/17310407/c7763687-17d7-48c5-bcf5-747aeb134e03)

### .NET Version

2.1.200

**Comment by amcasey** [comment]
I had also wondered whether 2012R2 was still supported. 😆 

For the error message, I see
```
Unable to start application pool
An error occurred while performing this operation.
details:
The service cannot accept control information at this time. (Exception comes from HRESULT:0x80070425)
```

[Here](https://learn.microsoft.com/en-us/previous-versions/ms833805(v=msdn.10)?redirectedfrom=MSDN) it says to wait and try again.  It also sounds like restarting the Credential Manager service might help.

**Comment by toolgood** [comment]
The reason is that I want to update the website code and cannot replace the file immediately. I must first close the website, close the application pool, and wait a few minutes before replacing the file.

**Comment by amcasey** [comment]
@toolgood That makes sense.  To confirm, if you revert your application back to 7.0 on the same machine(s), this scenario works as expected?  That would help confirm that the aspnetcore upgrade caused the problem and not some other factor.

Does the problem persist after restarting the Credential Manager service?

**Comment by BrennanConroy** [comment]
If this is on 2012 RC it sounds like a similar issue to https://github.com/dotnet/aspnetcore/issues/52307#issuecomment-1852886535
