### ISSUE TITLE
Blazor Server - HubFilter - Identifying called method

### ISSUE THREAD

**Issue by kurtisane** [dotnet/aspnetcore#52555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Some click on a button is executing some method inside of the code section in a blazor/razor page. 
I have a added HubFilter to for example check the JWT to be valid before method execution. It is not possible to identify the called method.

### Describe the solution you'd like

Provide the called method name in the HubInvocationContext. 

Better would be even to be able to set Attributes on the method which define the method name to be found in the HubInvocationContext. Custom fields to populate some Dictionary in the HubInvocationContext would also be appreciated.

**Comment by kurtisane** [comment]
As a example in my razor/blazor page:
`<button @onclick="LoginUser">Login</button>`

I would like to identify that the LoginUser Method is getting called.
I understand that this happens over the "BeginInvokeDotNetFromJS" Hub Method and that this is the general point where the frontend invokes stuff on the backend.

**Comment by BrennanConroy** [comment]
Oh, that has nothing to do with SignalR, and thus nothing to do with HubFilter then.

**Comment by kurtisane** [comment]
> Oh, that has nothing to do with SignalR, and thus nothing to do with HubFilter then.

Sorry for that. Was not clear enough.

**Comment by surayya-MS** [comment]
Thanks for reaching out.
Would setting JWT authentication and adding a component-level `[Authorize("MyCustomPolicy")]` attribute, where the custom policy verifies that the user has the right claims, work for you? You can follow these docs
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0

**Comment by javiercn** [comment]
@kurtisane thanks for contacting us.

We don't have this type of functionality and we don't recommend you integrate this way; it might break in the future if we change the shape of these APIs. The best way to do this is to inject the authorize service and do the check as the first thing inside the method call.
