### ISSUE TITLE
Slowness on the Clint End | Memory spike in the Chrome browser 

### ISSUE THREAD

**Issue by msrajagovindan** [dotnet/aspnetcore#52557]
Hi Team, we have a case where cx has an a simple client server demo where the server pushes data to the client every 5 seconds.
	• [code]: (https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNivonn%2Fsignal-R-test&data=05%7C01%7Csupportmail2%40microsoft.com%7C87efadadb4404484e20808dbd5344e88%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638338192885845035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XLxk9jvk9JWfpXmfQ%2F5jqzWzDFDVdiX0DH0ozdIikOE%3D&reserved=0) 

When cx takes memory snapshots (chrome->F12->memory->heap snapshot) every couple of minutes, they could see a constant growth of the total memory.
It seems that this issue causes the browser to freeze over a short period of time (high memory footprint)
The demo versions are:
•	Angular cli 16.0.3
•	Node 18.17.1
•	dot net 6.0
•	SignalR 7.0.5
We reviewed their code at this specific link on  [signal-R-test/signal-r-test/src/app/app.component.ts at main · Nivonn/signal-R-test (github.com)](https://github.com/Nivonn/signal-R-test/blob/main/signal-r-test/src/app/app.component.ts) 
	• It appears they only have one client method, which seems to log messages to the console. since it's high memory on the client side, debugging becomes challenging 
Hence I wasn’t sure if we could assist in debugging Angular Client JS apps for high memory.
	• From what we see, the code looks quite straightforward. Doesn’t seem like the SignalR library itself would cause high memory  
	• The only potential cause of high memory that comes to mind is a large number of incoming messages, which we can confirm by checking the SignalR JS logs alongside the Browser Trace.

I was looking for some assistance on this case, please let me know your thoughts and suggestions. thank you.

**Comment by BrennanConroy** [comment]
> When cx takes memory snapshots (chrome->F12->memory->heap snapshot) every couple of minutes, they could see a constant growth of the total memory.

What is increasing? Is it just the console logs? That sounds pretty normal. Not sure what you're expecting here.
