### ISSUE TITLE
Or it should be like this

### ISSUE THREAD

**Issue by Meganwalk** [dotnet/aspnetcore#52578]
Or it should be like this
```C#
public virtual async Task<SignInResult> PasswordSignInAsync(
      Emailstring mutiarajunita0@gmail.com,
      Password0000,

**Comment by gfoidl** [comment]
@Meganwalk I'm going to close this issue, but feel free to respond with more context around your intention. You can also use the [API proposal template](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=) to express your concern.
