### ISSUE TITLE
Blazor Web App in auto mode cannot be used for website development

### ISSUE THREAD

**Issue by GajaLab** [dotnet/aspnetcore#52587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Unfortunately, Blazor's Auto interactive mode presents 2 major problems in website development: the first, which they are already dealing with, concerns the freezing time of the screen from the transition from signalR to Wasm which affects the user experience.

The other concerns SEO with the compromise of pagespeed tests due to the download of the Wasm assemblies.
A low score can affect your ranking on search engines

### Describe the solution you'd like

I suggest the possibility, for problem number 2, of being able to control the downloading of the assemblies so that it is possible to postpone them and therefore exclude them from the pagespeed tests.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

We'll use https://github.com/dotnet/aspnetcore/issues/52154 to track improvements in this area because it brings up similar concerns.
