### ISSUE TITLE
blazorwasm hosted SingleOrg template is missing

### ISSUE THREAD

**Issue by sh-jthorpe** [dotnet/aspnetcore#52584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The templated for hosted webassembly with Microsoft Entra ID auth is missing.

### Expected Behavior

It should create a new project

### Steps To Reproduce

`dotnet new blazorwasm -au SingleOrg --api-client-id "{api-client-id}" --app-id-uri "{app-id-uri}" --client-id "{client-id}" --default-scope "API.Access" --domain "{domain}" -ho -o "Project" --tenant-id "{tenant-id}" --framework net8.0`

### Exceptions (if any)

> No templates found matching ...

### .NET Version

8.0.100

### Anything else?

I upgraded my dotnet 7 project to dotnet 8, and found that it's redirecting me to a HTTP401 page instead of automatically redirecting to login. I thought i'd missed something, so i tried to create a new project from the template to compare against. Lo and behold, it's gone :(

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. The Blazor WebAssembly Hosted template was replaced by the Blazor Web App template, the idea being that you can enable WebAssembly interactivity when configuring the project to get similar functionality.

We've received your [other issue](https://github.com/dotnet/aspnetcore/issues/52586) and we're going to investigate this scenario further to ensure it's a supported use case.

**Comment by sh-jthorpe** [comment]
> Thanks for reaching out. The Blazor WebAssembly Hosted template was replaced by the Blazor Web App template, the idea being that you can enable WebAssembly interactivity when configuring the project to get similar functionality.
> 
> We've received your [other issue](https://github.com/dotnet/aspnetcore/issues/52586) and we're going to investigate this scenario further to ensure it's a supported use case.

Hi @MackinnonBuck thanks for your response. However the Blazor Web App template only supports Individual auth. The Wasm Hosted template supported MS EntraID auth (the -SingleOrg option) as well as some other scenarios like AAD B2C.

So I should have logged this issue as "The Blazor Web App template is missing MS Entra ID options"
