### ISSUE TITLE
Add MapMethods with RoutePattern

### ISSUE THREAD

**Issue by carlreinke** [dotnet/aspnetcore#52581]
## Background and Motivation

[`Map`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutebuilderextensions.map) and [`MapGroup`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutebuilderextensions.mapgroup) have overloads that take the pattern as a `RoutePattern` rather than a `string`.  [`MapMethods`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutebuilderextensions.mapmethods) only has the overloads that take the pattern as a `string`, so there is no straightforward way to do verb-specific mapping for a given `RoutePattern`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

public static class EndpointRouteBuilderExtensions
{
+    public static IEndpointConventionBuilder MapMethods(
+        this IEndpointRouteBuilder endpoints,
+        RoutePattern pattern,
+        IEnumerable<string> httpMethods,
+        RequestDelegate requestDelegate);
+
+    public static RouteHandlerBuilder MapMethods(
+        this IEndpointRouteBuilder endpoints,
+        RoutePattern pattern,
+        IEnumerable<string> httpMethods,
+        Delegate handler);
}
```

## Usage Examples

These methods are meant to be used just like the existing `MapMethods` but when you have a `RoutePattern` rather than a `string`.

## Alternative Designs

```diff
namespace Microsoft.AspNetCore.Builder;

public static class EndpointRouteBuilderExtensions
{
+    public static IEndpointConventionBuilder MapDelete(this IEndpointRouteBuilder endpoints, RoutePattern pattern, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapDelete(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler);
+    public static IEndpointConventionBuilder MapGet(this IEndpointRouteBuilder endpoints, RoutePattern pattern, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapGet(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler);
+    public static IEndpointConventionBuilder MapMethods(this IEndpointRouteBuilder endpoints, RoutePattern pattern, IEnumerable<string> httpMethods, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapMethods(this IEndpointRouteBuilder endpoints, RoutePattern pattern, IEnumerable<string> httpMethods, Delegate handler);
+    public static IEndpointConventionBuilder MapPatch(this IEndpointRouteBuilder endpoints, RoutePattern pattern, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapPatch(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler);
+    public static IEndpointConventionBuilder MapPost(this IEndpointRouteBuilder endpoints, RoutePattern pattern, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapPost(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler);
+    public static IEndpointConventionBuilder MapPut(this IEndpointRouteBuilder endpoints, RoutePattern pattern, RequestDelegate requestDelegate);
+    public static RouteHandlerBuilder MapPut(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler);
}
```

**Comment by halter73** [comment]
@carlreinke Can you explain why you want to be able to pass in the `RoutePattern` directly instead of using a string to define the pattern? Is it just to avoid the perf hit of reparsing it, or is there some other reason?

This API adds a lot of new overloads, particularly if include those mentioned under alternative designs, which can be confusing to new developers who just want to use strings to define routes with strings like normal.

Are you aware the workaround of calling `Map` adding the http method metadata yourself? For example you can do:

```csharp
app.Map(myRoutePattern, () => "Hi!").WithMetadata(new HttpMethodMetadata(new[] { "GET" }));
```

It's not as convenient as the proposed API, but I think it might be good enough considering having a pre-parsed `RoutePattern` is a pretty advanced scenario.

**Comment by carlreinke** [comment]
I have a `RoutePattern` that has custom query parameter constraints added to it.  (I needed to route based on the query parameters as well as the path.)

I was not aware of `HttpMethodMetadata`.  That's what I needed.

I still think the proposed API (not the alternative design) would be nice-to-have in that it's more discoverable than `HttpMethodMetadata`, but I won't be too sad if the proposal is rejected.

**Comment by halter73** [comment]
API Review Notes:

The reason for wanting the `RoutePattern` overload is sensible, since not all constraints can be represented as strings, but
given that the workaround is pretty simple, and this is a pretty niche scenario, we've decided to reject the proposal.

Thanks for submitting it though!
