### ISSUE TITLE
Browser hangs when @layout is specified in _Imports file in child folder (Blazor-WASM)

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#52593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am attempting to create a layout component for files in a folder in my app.  Following the documentation found here:

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-8.0#apply-a-layout-to-a-folder-of-components

Problem occurs when `@layout` is specified in _Imports component.  Page is not rendered and Browser hangs.
When `@layout` is specified in Home.razor the page renders as expected.

Possibly related:

https://github.com/dotnet/aspnetcore/issues/52478

### Expected Behavior

Page is rendered using `@layout` component specified in _Imports.razor in the folder where the page is located.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-8.0#apply-a-layout-to-a-folder-of-components

### Steps To Reproduce

In the attached app there is a folder named AdminPortal which contains APMainLayout.razor.  

Working behavior - `@layout` directive is specified in Home.razor:

Run the attached project.
Click the Admin Portal link
Note page says This is APMainLayout

Non-working behavior:

Comment out `@layout` directive in AdminPortal.Home.razor.
Un-comment content of AdminPortal/_Imports.razor
Run the app
APMainLayout content is not displayed and the browser appears to hang.

### .NET Version

8.0.100

### Anything else?

[BlazorLayoutTest.zip](https://github.com/dotnet/aspnetcore/files/13573672/BlazorLayoutTest.zip)

**Comment by surayya-MS** [comment]
Thanks for reaching out.

It seems likely that your layout is now importing itself as a layout. That would cause an infinite loop and hence a hang. To avoid this, don't put the @layout directive in an _Imports.razor file that's in the same directory as the layout or above.
 
Since this is a usage question, for any more information about this, please consider posting a request on stackoverflow.com.
