### ISSUE TITLE
Make TUser nullable on IPasswordValidator.ValidateAsync

### ISSUE THREAD

**Issue by stefannikolei** [dotnet/aspnetcore#52606]
## Background and Motivation

The user is not used in this method. So It can also be nullable. This case is already handled by the tests.

Usecase for this is, that you want to validate the inserted password (before a user account was created) to show the user the validation results.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Identity;

public interface IPasswordValidator<TUser> where TUser : class
{
-   Task<IdentityResult> ValidateAsync(UserManager<TUser> manager, TUser user, string? password);
+   Task<IdentityResult> ValidateAsync(UserManager<TUser> manager, TUser? user, string? password);
}
```

**Comment by halter73** [comment]
Even though the default `PasswordValidator` does not throw for a null user and our `PasswordValidatorTest` verifies that's the case, that doesn't mean that other `IPasswordValidator` implementations might not require it.

`UserManager.ResetPasswordAsync()` is the only public method that calls into `IPasswordValidator.ValidateAsync`, and it does throw for null users. An implementor of `IPasswordValidator` could reasonably assume that the user will not be null so long as the caller adheres to the nullability rules which our code does. We may not proactively null check the user every method we could, but we don't incorrectly pass through a nullable user either. We shouldn't start raising nullability warnings for valid interface implementations that correctly assume the user will not be null.
