### ISSUE TITLE
Identity pages cannot be reached after migrating Blazor server from 7 to 8

### ISSUE THREAD

**Issue by dajma00** [dotnet/aspnetcore#52610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am following the following guide to migrate a Blazor Server app from .NET7 app to .NET8: [https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#convert-a-blazor-server-app-into-a-blazor-web-app](url)

After completing the migration, everything works fine. But I cannot access Identity pages and I get http 404 error. So the question is what changes are required so my .NET7 identity pages such login.cshtml and register.cshtml keep working and are accessible to the migrated app?

### Expected Behavior

Identity pages should continue to work after migration to .NET8

### Steps To Reproduce

Migrate a Blazor server app that uses scaffolded identity pages from .NET7. After completing the migration, identity pages are not accessible and we get a 404 error.

### .NET Version

.NET8

**Comment by Karny13** [comment]
Facing the same issue myself. 
Another thing I'm facing is with the Routes.razor component. I added the new component but in the App.razor it is not being recognized for some reason.
Nor is the @rendermode working in pages.
I converted from blazor server to .net 8 blazor web using the guidelines
