### ISSUE TITLE
Out of the box .net 8 blazor project fails when navigating directly to a route that load a page with injected dependencies.

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/aspnetcore#52614]
### Description

I'm using the full out of the box visual studio template for a blazor app and select the  GLOBAL web assembly interactive mode.
When injecting a simple HTTPClient in the canonical Counter page and you browse directly to that page you run in :
```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot provide a value for property 'Http' on type 'BlazorAppDIProblem.Client.Pages.Counter'. There is no registered service of type 'System.Net.Http.HttpClient'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
```

### Reproduction Steps

create an out of the box blazor app with interactive web assembly render mode, GLOBAL.
Add in the wasm project in startup:
```
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
var http = new HttpClient()
{
    BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
};
builder.Services.AddScoped(sp => http);
await builder.Build().RunAsync();
```
Use now in Counter.razor the injected service
```
@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    [Inject]
    public HttpClient Http { get; set; }
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
}

```

Start the app with dotnet run and do a refresh of the browser on the Counter route.
You will get:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot provide a value for property 'Http' on type 'BlazorAppDIProblem.Client.Pages.Counter'. There is no registered service of type 'System.Net.Http.HttpClient'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
```

### Expected behavior

The injected service should be simply available.
This was the case in .net 7. No idea what's going wrong here.

### Actual behavior

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot provide a value for property 'Http' on type 'BlazorAppDIProblem.Client.Pages.Counter'. There is no registered service of type 'System.Net.Http.HttpClient'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
```

### Regression?

This worked correctly in .net 7

### Known Workarounds

No.

**Comment by bcheung4589** [comment]
```
@page "/counter"
@inject HttpClient Http
```

Does this work? And do you have to do it in the @code { } area? Since thats how you would do it in a .razor.cs-file. In razor markup I would just use @inject.

**Comment by javiercn** [comment]
@paulvanbladel thanks for contacting us.

By default on .NET 8.0 apps prerender on the server, so you need to also register the HttpClient instance on the server container. Otherwise it will fail to prerender in that case.

**Comment by bestnatureguy** [comment]
I'm still not able to resolve.  Can you please add more detail on how to register the HttpClient instance on the server container?  I've tried a few things and it hasn't worked...  Also - how would you turn off prerendering to prevent this issues.

**Comment by Trapulo** [comment]
I also need to migrate a .net 7 WASM where I inject http client and currently I have "InvalidOperationException: Cannot provide a value for property 'httpClient' on type..." when I run it.

**Comment by bestnatureguy** [comment]
I figured this one out. In.net 8 if you are using http client in the WASM
project, you also need to inject it in the server project. It sounds stupid
but it is due to the fact that.net 8 by default will try to pre-render your
component on the server.  The way to fix this is to mark your components
with the pre-render equals false attribute.  I learned this in a Microsoft
article that was in the documentation way down on a page that I happen to
find. Hth

**Comment by Trapulo** [comment]
I also found it yesterday, thanks. Disabling pre-render on the component has solved.

**Comment by bestnatureguy** [comment]
Glad to hear it!  Too bad this issue was hidden and took us both so long to
find it! Haha

**Comment by GerardFR** [comment]
It also took me a looong time to find the origin of the issue and this post took me to the solution. I am moving a Blazor 7 Hosted Wasm app with authentication (Identity Server) to a Blazor 8 Web app with authentication. So this is what I did to fix that issue.

Change the generated code in [server}/Components/App.razor (I'm using InteractiveWebAssembly render mode):
`private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
    ? null
    : InteractiveWebAssembly;`

to:
`private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
    ? null
    : new InteractiveWebAssemblyRenderMode(prerender: false);`

**Comment by erbatista** [comment]
I wanted to preserve prerender, so I did as suggested in this [page](https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0). For anyone that want to save the time of reading it, you just need to register the HttpClient in the SSR project too, for that just add the line below to its programs.cs file:
`builder.Services.AddHttpClient();
