### ISSUE TITLE
OIDC NonceCookie/CorrelationCookie not accepted in HTTP environment

### ISSUE THREAD

**Issue by noxi515** [dotnet/aspnetcore#52617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

By issue #44853 and PR #45247, OIDC NonceCookie/CorrelationCookie security policy was changed from "SameAsRequest" to "Always", then causes authentication error on pure HTTP webapp. Both `RemoteAuthenticationOptions.CorrelationCookie` and `OpenIdConnectOptions.NonceCookie` are documented as "SecurePolicy defaults to SameAsRequest".

Workaround:
```csharp
builder.AddOpenIdConnect((OpenIdConnectOptions options) =>
{
    // your settings...
    options.NonceCookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;
    options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;
});
```

### Expected Behavior

Both OIDC NonceCookie/CorrelationCookie security policy are set to "SameAsRequest" so no authentication error on pure HTTP webapp by default, or documented "Always".

### .NET Version

8.0.100

**Comment by Tratcher** [comment]
OIDC requires SameSite.None in most cases, which requires Secure cookies / HTTPS. HTTP isn't really an option anymore.

**Comment by noxi515** [comment]
I see why changed, but documents are incorrect. Plaease fix it.


https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L149

https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L317
