### ISSUE TITLE
ASP0018 complains about catch-all parameter without proposing any solutions

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/aspnetcore#52628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```cs
// ASP0018 Unused route parameter 'any'
[HttpOptions, Route("some/api/{*any}")]
public IActionResult CORSPreflight()
{ ... }
```

### Expected Behavior

As route template parameter is [required to have name](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-templates) I expect analyzer to support `catch-all` parameters for rest of template.

### .NET Version

8.0.100

**Comment by JamesNK** [comment]
I don't think this is a bug. This ASP0018 is a hint about what you could do. You can choose to update your app or not.

Also, I double checked the add parameter analyzer works with any parameters:

![catchall](https://github.com/dotnet/aspnetcore/assets/303201/73244adb-5820-48bb-a283-daabb4ea3c03)

I'm closing this. If you have more information, comment here and maybe this can be reopened.

**Comment by Daeymon** [comment]
All your example does is trade the ASP0018 for a "IDE0060 - Remove unused parameter". IT compliance teams within companies tend to take these "hints" very seriously (I know mine does) so its understandable when developers want or need to have these analyser messages resolved.

In terms of a valid scenario requiring a catch-all, one example would be a controller which returns a PDF. At the very least with a Chromium browser, the PDF viewer uses the content in the final part of the request path as the filename of the PDF (which is utilised if a user hits the Download button). But the controller method itself does not have any use for this information. I've thrown together an example below:

```
[ApiController]
[Route("DownloadPdf")]
public class DownloadPdf : ControllerBase
{
    [HttpGet]
    [Route("{*anyFileName}")]
    public IActionResult GetPdfReport([FromQuery(Name = "accessToken")] string accessToken)
    {
        FileDownloader pdfDownloader = this.HttpContext.RequestServices.GetService<FileDownloader>()!;
        return pdfDownloader.GetPendingFile(this.User.Identity, accessToken);
    }
}
```

**Comment by abresee-cc** [comment]
I would like to second that this is an actual issue that needs to be addressed.
