### ISSUE TITLE
Microsoft.AspNetCore.Components.WebView.props does not get imported correctly

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#52637]
We're seeing build failures in https://github.com/dotnet/maui/pull/19236 caused by `src/Components/WebView/WebView/src/build/Microsoft.AspNetCore.Components.WebView.props` not being found in the produced NuGet package for `Microsoft.AspNetCore.Components.WebView`.

**Comment by aherrick** [comment]
i'm seeing this in 8.0.1 is that expected?

**Comment by leecow** [comment]
We missed our note to not publish these packages. Please confirm that we should unpublish the 6.0.26, 7.0.15, and 8.0.1 versions and we'll make it happen. 

cc @rbhanda

**Comment by foximoxi** [comment]
I'm not able to compile WinForms with WebView/Blazor embedded. Same errors.
