### ISSUE TITLE
Investigate metrics endpoint behavior when exception middleware runs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#52648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

OTEL folks noticed that the endpoint is cleared when exception middleware runs. See https://github.com/open-telemetry/opentelemetry-dotnet/issues/5134

Investigate whether this impacts ASP.NET Core's use of the endpoint when building tags for metrics.

### Expected Behavior

Metrics endpoint route tag is present when exception middleware runs.

### .NET Version

net8.0

**Comment by davidroth** [comment]
Thanks, just reported this also in https://github.com/dotnet/aspnetcore/issues/52766  (duplicate) 👍

Question: Will this be published in an 8.0 release update or do we have to wait for 9.0? (Hoping for the former)

**Comment by JamesNK** [comment]
The fix will be back ported to 8.0.2 (available approx Feb or March)

**Comment by JamesNK** [comment]
Your issue here - https://github.com/dotnet/aspnetcore/issues/52766 - says the counter is muted. What do you mean by that? With the bug here, I would still expect a value to be recorded, but without a `http_route` value.

**Comment by davidroth** [comment]
> Your issue here - #52766 - says the counter is muted. What do you mean by that? With the bug here, I would still expect a value to be recorded, but without a `http_route` value.

My fault. I retested it again and the value is indeed recorded, but without the `http_route` value. So basically as described in this issue.

**Comment by JamesNK** [comment]
Reopen to track backport to 8.0

**Comment by JamesNK** [comment]
Added to backport with https://github.com/dotnet/aspnetcore/pull/52790.
