### ISSUE TITLE
JwtBearerPostConfigureOptions registration being override by PostConfigureAuthenticationSchemeOptions<TOptions> when calling AddJwtBearer

### ISSUE THREAD

**Issue by ricardomomm** [dotnet/aspnetcore#52641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AuthenticationBuilder.cs got changed in .Net 8 Preview 5 to replace the ISystemClock and with that it is overriding the previous registration of JwtBearerPostConfigureOptions and breaking existing behavior for dynamically configured JwtOptions (i.e. multi tenant authorization handler)

Link to the change
https://github.com/dotnet/aspnetcore/commit/726f467f4c0d23b40a937edab56430c3861e73b9#diff-c1c20cc495bee5b562aa6e85965adb5890a557b985fe43dc37f7eabbef0225c3

Link to the code that calls it
https://github.com/dotnet/aspnetcore/blob/v8.0.0/src/Security/Authentication/JwtBearer/src/JwtBearerExtensions.cs#L79

### Expected Behavior

The expected behavior is to resolve to JwtBearerPostConfigureOptions when injecting IPostConfigureOptions<JwtBearerOptions> and proceed with its internal logic. 

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.Options;

internal class Program
{
    private static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // Add services to the container.
        builder.Services
            .AddAuthentication()
            .AddJwtBearer();

        var app = builder.Build();

        app.Use((context, next) =>
        {
            var postConfigureOptions = context.RequestServices.GetRequiredService<IPostConfigureOptions<JwtBearerOptions>>();
            if (postConfigureOptions is not JwtBearerPostConfigureOptions)
                throw new InvalidOperationException("Why??");

            postConfigureOptions.PostConfigure("bearer", new JwtBearerOptions());

            return next(context);
        });

        // Configure the HTTP request pipeline.

        var summaries = new[]
        {
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

        app.MapGet("/weatherforecast", () =>
        {
            var forecast = Enumerable.Range(1, 5).Select(index =>
                new WeatherForecast
                (
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
                .ToArray();
            return forecast;
        });

        app.Run();
    }
}

internal record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

### Exceptions (if any)

Because it does not use the JwtBearerPostConfigureOptions all token validations are failing.

### .NET Version

8.0.100

**Comment by Tratcher** [comment]
Your example is confusing, IPostConfigureOptions is something you register for the system to call, not resolve and call yourself. Is this representative of your usage?

**Comment by ricardomomm** [comment]
This is a minimal example of the issue, my use case is more complex, I use PostConfigureOptions to setup JwtBearer dynamically per tenant based in request information. I can try to create a similar usage so you can understand better, but that will not change the fact that it is overriding the JwtBearerPostConfigureOptions in error.

**Comment by halter73** [comment]
We'll need a complete repro to see if there's really a common scenario that was broken, but I'd advise against ever running `IPostConfigureOptions<TOptions>` manually. If you must, at least run all of them like [OptionsFactory<TOptions>](https://github.com/dotnet/runtime/blob/e21bdfe15f4ffbec1f6c56395a2f70433cdf455b/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L69-L72) does, but you'd probably be better off just using `IOptions<TOptions>` or `IOptionsFactory<TOptions>`.

**Comment by ricardomomm** [comment]
@halter73 I added a minimal repro code in the steps to reproduce, it is runnable and reproduces the issue. The main scenario where this is used is to define OpenIdConnectOptions at runtime when handling multi tenant requests. So first request for a given Tenant will setup OpenIdConnectOptions to that tenant and create a specific Schema for it and call post configure manually to setup, all subsequent requests will reuse the prevously defined Schema for the tenant. This is useful to handle wildcard subdomains to an IdP and load OIDC options on demand without the need to restart the application when a new Tenant is added. I wish I could find the repo from Identity Server where they have this sample.

**Comment by mkArtakMSFT** [comment]
Thanks @ricardomomm.
Looks like you will have to follow the suggestion provided by @halter73 above then:

> run all of them like [OptionsFactory](https://github.com/dotnet/runtime/blob/e21bdfe15f4ffbec1f6c56395a2f70433cdf455b/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L69-L72) does, but you'd probably be better off just using IOptions<TOptions> or IOptionsFactory<TOptions>.

There is no other work we plan to do as part of this issue.
