### ISSUE TITLE
Blazor needs to force reload pages with scripts

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#52649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Im trying to make a blazor page that uses a 3rd party javascript.

This itself works just fine, when you add the script tag to the `HeadContent`. (Side question: which issue deals with the problem that `HeadContent` only works when prerender is enabled?)

There are however several issues when enhancedload comes into play:

1. The diff algo will just add the script tag to the head like it is supposed to, but it doesn't wait around until it is actually loaded, and thus if you use an approach like https://learn.microsoft.com/vi-vn/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0 the onload will have the script loaded when non-enchanced load, but race-condition when enhancedload.
2. If you visited the page before, ie user navigated from /pageWithJs -> /pageWithout -> /pageWithJs, the browser will most likely have kept the script somewhere in memory because some reference is still live (e.g. the script declared a func in `window`), but the script tag was removed from the html so it might also have been unloaded. This leads to unpredicable behavior.

I see 2 solutions:
a. Detect scripts in `HeadContent` and issue a `Blazor.navigateTo(true)`.
b. Add support for `@attribute EnchancedLoadDisabled` for page/component.

### Steps To Reproduce

1. Add Script tag to `HeadContent`
2. Script can be something as trivial as `window.MyFunc = function() {}; debugger;`
3. Play around with enhanced load and see it is unpredictable when the debugger tag is triggered.

### .NET Version

8.0.100

**Comment by davhdavh** [comment]
I have a 3rd solution, that would also enabled some advanced caching that I think is missing.

`NavManager.IsEnhancedNavigation` => `NavManager.Refresh(true)`.

That will also support having components that only render on fresh pages, and just wraps themselves in a `<div data-permanent>`. Ie:

`menu.razor`:

```
<div data-permanent>
@if (!NavManager.IsEnhancedNavigation) {
<CreateExpensiveMenu>
}
</div>
```

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

We are working on some guidance on this area and might make some enhancements in the future. See https://github.com/dotnet/aspnetcore/issues/52273

In general, it is better to switch to JS modules (no need to wait for the DOM to be loaded (and will only execute once)) and attach an event handler to trigger whatever logic you need to run on the page.

The main challenge here is that enhanced nav is not entirely transparent, without enhanced nav, you get a clean "context" on every navigation. With enhanced navigation you only get it on first load, but afterwards is a custom mechanism, so you need to do extra work to wire up your logic.

**Comment by davhdavh** [comment]
I do not disagree with that, but 99% of 3rd party js or even just internal js is still stuck in the pre-module world, and it will take a decade or more before that really changes.

> The main challenge here is that enhanced nav is not entirely transparent, without enhanced nav, you get a clean "context" on every navigation. With enhanced navigation you only get it on first load, but afterwards is a custom mechanism, so you need to do extra work to wire up your logic.

Yes, this bug was to provide the necessary hooks and functions to do this extra work.
