### ISSUE TITLE
Seperate SignInManager and UserManager concerns

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnetcore#52650]
I've noticed there's a dependency of UserManager in the SignInManager? Can these two classes be decoupled?

Please see the below screenshot.

![image](https://github.com/dotnet/aspnetcore/assets/14249890/a8e18a97-46fd-4e20-a3f2-9693433a384b)

**Comment by chris-briddock** [comment]
Is there any appetite to do this? I believe the functionality should be exposed by a store interface instead of the UserManager.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
