### ISSUE TITLE
Chinese characters are encoded incorrectly in .Net 8 Blazor Web App despite using HtmlEncoder.Create(UnicodeRanges.All)

### ISSUE THREAD

**Issue by sxbyl** [dotnet/aspnetcore#52683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chinese characters are encoded and displayed incorrectly in .Net 8 Blazor Web App. I tried both
```
builder.Services.Configure<WebEncoderOptions>(options =>
{
    options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All);
});
```
and
`builder.Services.AddSingleton(HtmlEncoder.Create(UnicodeRanges.All));`
but none of them worked.

### Expected Behavior

Chinese characters should be displayed directly without encoding.

### Steps To Reproduce

1. Create a new .Net 8 Blazor Web App (Server render mode).
2. Modify Home.razor as follows:
```
@page "/"

<PageTitle>Home</PageTitle>

<h1>@("测试")</h1>

Welcome to your new app.

```
3. Add the following code in Program.cs:

`builder.Services.Configure<WebEncoderOptions>(options => options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All));`

4. Run the program and view the generated page source code, which contains the following code:
`<h1>&#x6D4B;&#x8BD5;</h1>`

### Exceptions (if any)

The html source of generated page should be `<h1>测试</h1>`

### .NET Version

.net 8.0.100

**Comment by javiercn** [comment]
@sxbyl thanks for contacting us.

Seems that the encoders are hardcoded [here](https://github.com/dotnet/aspnetcore/blob/a9e9cc3e23d06f56b7e6fbd99ecea6b8e4dd8bf4/src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs#L24-L25). 

We should check if there are encoders registered in DI and use those when that's the case [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.cs#L32)

**Comment by javiercn** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/53213
