### ISSUE TITLE
Continuous browser reloading while navigating within AuthorizeView razor page

### ISSUE THREAD

**Issue by Sureshrajan-18** [dotnet/aspnetcore#52686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our Blazor .NET 8 server-mode application, we have integrated an Authorize razor page. However, when navigating within the Authorize razor page, the browser continuously reloads.

We have utilized the AuthorizeRouteView to check the user is authorized or not.

### Expected Behavior

The navigation within the Authorize razor page should render correctly without any browser reloading issues.

### Steps To Reproduce

Please find the issue replicated GitHub sample from the below link.

https://github.com/Sureshrajan-18/Blazor_.NET8-AuthorizeRouteView 

When navigating within the Auth Required, Register, and Login razor pages, you will notice the browser continuously reloading.

### .NET Version

dotnet version 8

**Comment by qwertybba** [comment]
The issue affects a wide community, so I hope Microsoft fixes it as soon as possible

**Comment by halter73** [comment]
I submitted a PR to the repro project to fix the continuous reloading: https://github.com/Sureshrajan-18/Blazor_.NET8-AuthorizeRouteView/pull/1

As I note in the PR's description, the logic in AccountLayout.razor intentionally calls `NavigationManager.Refresh(forceReload: true)` to force a transition from dynamic back to static rendering. If you put a breakpoint there without the changes from the PR, you'll see it repeatedly get hit for reach reload.

The account pages are intended to be used with static rendering where the `HttpContext` is available so the `SignInManager` can use the `IHttpContextAccessor` to do things like sign in and out via server-side authentication schemes which rely on being able to set 302 responses to redirect.

@SteveSandersonMS Just opened #54948 which will add a `@staticroute` directive in .NET 9 (final name to be determined) that we will use on the account pages to make this clearer, and harder to mess up if you refactor your `App.razor`. The `RenderModeForPage` logic will go away.

**Comment by Braanflakes** [comment]
Is there a workaround that can prevent this continuous reloading in the meantime?
