### ISSUE TITLE
Unhandled exception when running new Blazor Web App from following tutorial at https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro

### ISSUE THREAD

**Issue by domtriestocode** [dotnet/aspnetcore#52680]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/try
Operating System: windows 11

When following the .NET published tutorial linked the blazor web app faces an unhandled exception. 
![blazor web app unhandled exception](https://github.com/dotnet/core/assets/137571726/15479ea2-ee96-49eb-8bed-b696cbe3a8fd)

Steps to reproduce: Follow tutorial step by step. Run app in microsoft Edge.

**Comment by domtriestocode** [comment]
> @domtriestocode more information about the exception may be needed.

Sure, can you please tell me how to provide it though? This exception was never actually thrown and I never get any error message in the debugger or output window.

**Comment by javiercn** [comment]
@domtriestocode the exception should be displayed in the Browser Developer Tools console, you can access it, by pressing F12
