### ISSUE TITLE
Ability to add rendermode to blazor layouts

### ISSUE THREAD

**Issue by sukanzubair** [dotnet/aspnetcore#52709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have mutiple layouts which I use in my blazor webapp. I require one layout to be interactive and as a result I need to apply a render mode on the route. This then forces all layouts and page to be webassembly interactive as I cannot apply render modes to individual layouts or pages once I have defined the rendermode at a route level.

If I try to apply the render mode only on the layout I recieve am exception about the renderfragment not being serializable.

It should allow me to specify a render mode of webassemblyinterative with pre render false, which will then allow the rest of the app to be rendered as required. In the current setup, my only option is to apply this at a route level forcing my entire app to be the same.

### Describe the solution you'd like

I would like to be able to specify a render mode of webassemblyinteractive with prerender set to false and this should not cause any errors as this will not need to be serialized as it would only run on the client app.

**Comment by javiercn** [comment]
@sukanzubair thanks for contacting us.

There are fundamental limitations with supporting this today, as the challenge is we can't serialize RenderFragments, which is what Layouts (the `@Body`) use.

I've filed an issue for it https://github.com/dotnet/aspnetcore/issues/52768 which more clearly describes the problem. I suggest you upvote that instead
