### ISSUE TITLE
Blazor: Can `NavigateTo` and `href=` be used without interfering with each other?

### ISSUE THREAD

**Issue by capdiem** [dotnet/aspnetcore#52705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Take eshop webapp as an example, an outside-click event is registered on the page, but clicking anywhere in the document will trigger the `HandleOutsideClickAsync` method, which will close the chat pop-up window. 
When you click the cart link, the shopping cart window pops up, and the chat pop-up window closes automatically.
```razor
@inject NavigationManager Nav

<a href="@Nav.GetUriWithQueryParameter("cart", true)">cart</a>  @* /?cart=true *@

@code {
    private async Task HandleOnOutsideClickAsync() {
        Nav.NavigateTo(Nav.GetUriWithQueryParameter("chat", false)); // /?chat=false
    }
}
```

But when `HandleOutsideClickAsync` triggers earlier than `HandleOutsideClickAsync`, it becomes:
1. initial url: `/?chat=true` 
2. cart link clicked: `/?chat=true&cart=true` 
3. NavigateTo in outside click:`/chat=false`

The third result is not what I want, the correct one should be `/?chat=false&cart=true`

My current solution is:

```cs
private async Task HandleOnOutsideClickAsync() {
    await Task.Delay(100); // <- here
    Nav.NavigateTo(Nav.GetUriWithQueryParameter("chat", false)); // /?chat=false
}
```

### Expected Behavior

1. initial url: `/?chat=true`
2. cart link clicked: `/?chat=true&cart=true`
3. NavigateTo in outside click: `/chat=false&cart=true`

### .NET Version

8.0.100

**Comment by MariovanZeist** [comment]
Hi @capdiem
I assume that the following is happening. 

When you click on the ``<a>`` tag, Blazor intercepts that click and navigates to its ``href``. 
But the ``onclick`` events bubbles up to its parents, and it encounters an element that has an ``onclick`` event set to  ``HandleOnOutsideClickAsync``

What happens in your situation is that you are actually navigating twice, once you navigate to the href, and then you navigate to  the Uri in your function ``HandleOnOutsideClickAsync``

To prevent the click event on the ``<a>``from bubbling up you could handle the ``onclick `` on the ``<a>`` tag yourself and prevent the default action. 
```razor
@inject NavigationManager Nav

<a href="@Nav.GetUriWithQueryParameter("cart", true)" @onclick=HandleHRefClick @onclick:preventDefault>cart</a>  @* /?cart=true *@

@code {
    private async Task HandleOnOutsideClickAsync() {
        Nav.NavigateTo(Nav.GetUriWithQueryParameter("chat", false)); // /?chat=false
    }
    
    private void HandleHRefClick() {
        Nav.GetUriWithQueryParameter("cart", true);  // /?chat=true
    }
}
```

**Comment by capdiem** [comment]
Thank you for your reply. In fact, I just want to navigate twice, the navigation in outsideclick is to close the chat window, the `a` is to pop up the cart window, I don't want to have two windows at the same time.

**Comment by MariovanZeist** [comment]
Hi @capdiem I am trying to run your repro, but I run into the following ``exception``
![image](https://github.com/dotnet/aspnetcore/assets/12493059/3f896eb3-ce09-40d5-87e9-f4135d8facf2)

**Comment by capdiem** [comment]
@MariovanZeist I have fixed this problem.

**Comment by MariovanZeist** [comment]
@capdiem Thank you for the repro. 

It's a bit confusing what is happening in your code, it's a combination of multiple navigation events being fired in short succession and the way you are generating the URL in the ``OutsideClick`` event. (which is different if you are introducing a delay or not)

Is there a reason why you want to use ``QueryParameters`` and navigation events to set the chat and cart state?

**Comment by capdiem** [comment]
@MariovanZeist I think this is a hack approach: in a static SSR application, use `QueryParameters` to open an `InteractiveServer` component that creates a circuit, and when the component disposed or be removed, the circuit would be closed. 

What I want to make clear is that both Href-triggered navigation and NavigateTo-triggered navigation should be handled by enhanced navigation, right? If so, maintain a queue internally and my problem can be solved.

**Comment by MariovanZeist** [comment]
@capdiem  Both the ``HRef`` triggered navigation, and ``NavigateTo`` triggered navigation are initiated, but because of the near-simultaneous time they are executed, depending on subtle timing differences the outcome might vary, and one Navigation might even cancel the previous navigation if it's still being processed. 

I personally prefer this method, as that will make sure the application is as responsive as possible and will abort navigation events when they are superseded by others. 
And even if both of your navigation events were processed you still would have to be content with the fact that you cannot guarantee the order of execution.

**Comment by capdiem** [comment]
@MariovanZeist I think you are right, for example, if I click on several different `href` in succession, only the `QueryPparameter` of the last `href` will be retained.
