### ISSUE TITLE
Catch-all route at the root level doesn't work any more in .NET 8

### ISSUE THREAD

**Issue by gdar91** [dotnet/aspnetcore#52708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an application with very few pages, where one is mainly active and catches all the remaining URLs as a part of its logic. In .NET 7, It was enough to annotate that page with `@page "/{*pageRoute}"` and declare the corresponding parameter `[Parameter] public string? PageRoute { get; set; }`. But it stopped working when I upgraded to .NET 8 (Blazor United) and started showing a white screen and an exception in the browser's console.

### Expected Behavior

It should catch the rest of the URLs that didn't match with other routes .

### Steps To Reproduce

1. Create a net .NET 8 Blazor United app with interactive web assembly with pre-rendering turned OFF.
2. Delete pages but the Index.
3. Annotate the Index page with `@page "/{*pageRoute}"` and declare a parameter for it `[Parameter] public string? PageRoute { get; set; }`
4. Run the app; you should see a white screen with an error in the console.

### Exceptions (if any)

```
blazor.web.js:1  Error: One or more errors occurred. ('<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at 00b1e8b6:0x1faca
    at 00b1e8b6:0x1bf8b
    at 00b1e8b6:0xf172
    at 00b1e8b6:0x1e7e4
    at 00b1e8b6:0x1efda
    at 00b1e8b6:0xcfec
    at 00b1e8b6:0x440ad
    at e.<computed> (cwraps.ts:338:24)
callEntryPoint @ blazor.web.js:1
```

### .NET Version

8.0.100

### Anything else?

It works if the catch-all wildcard is not placed at the root level but after a URI segment.
We need a way to allow routes without explicitly listing them in razor pages.

**Comment by javiercn** [comment]
@gdar91 thanks for contacting us.

In .NET 8.0 routing is integrated with ASP.NET Core routing, what's happening is that your route is "too general" and is intercepting requests for files. You need to add `:nonfile` to the route to avoid capturing paths with an extension.
