### ISSUE TITLE
The blazer auto rendering mode did not work as expected.

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/aspnetcore#52719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Components in auto mode exhibit inconsistent behavior across different page loading methods and do not function as expected in auto mode.

### Expected Behavior

Auto rendering mode always works as expected.

### Steps To Reproduce

Create a blazer project using a project template, choose auto as the rendering mode, and set the rendering mode for each page.
Define the following components in the xxx.Client project:

Test.razor
```
<h3>Test1</h3>
<button @onclick="Btn1Click">click me</button>
@code {
     void Btn1Click()
    {
        Console.WriteLine($"start in browser {this.GetHashCode()} {DateTime.Now.ToLongTimeString()}" );
    }
}
```

Page1.razor
```
@page "/page1"
<h3>Page1</h3>
<BlazorApp3.Client.Components.Test1 @rendermode="InteractiveServer"></BlazorApp3.Client.Components.Test1>
<BlazorApp3.Client.Components.Test1 @rendermode="InteractiveAuto"></BlazorApp3.Client.Components.Test1>
@code {
}
```

Page2.razor
```
@page "/page2"
<h3>Page2</h3>
<BlazorApp3.Client.Components.Test1 @rendermode="InteractiveAuto"></BlazorApp3.Client.Components.Test1>
@code {
}
```

Phenomenon 1:
Enter the Home page, then click on the menu to enter the Page1 page. Components rendered in auto mode will always run in server mode, even after downloading webassembly resources.
Click on the menu again to navigate to the Page2 page, which only contains the test component in auto mode, but it will always run in server mode.

Phenomenon 2:
On the page2, press F5 to refresh the browser. At this point, the Test component runs as expected, starting with server-side rendering. Later, it renders in client-side mode.
At this point, click the button in the menu, navigate to page1, and it will also work as expected. One component will run in server mode, another component will start running in server mode, and later run in client mode.

### .NET Version

net8

### Anything else?

vs2022 17.8.3

**Comment by javiercn** [comment]
@bxjg1987 thanks for contacting us.

There are a few factors that influence when auto components run on server or webassembly, not just whether the dlls have been downloaded.

If the server runtime is already available and the webassembly one is not (for some reason) we'll render the component on the server mode.

@MackinnonBuck thoughts?

**Comment by bxjg1987** [comment]
@javiercn
As I mentioned earlier, Phenomenon 2 works as expected when there are only auto mode components on a page, indicating that the assembly runtime environment can run normally. Why do other auto mode components fail to function as expected when there are server mode components on the page? Is there a specific guideline?

**Comment by MackinnonBuck** [comment]
Hi @bxjg1987, the behavior you're seeing is by design. I left a comment [here](https://github.com/dotnet/aspnetcore/issues/52740#issuecomment-1852841365) that explains why this happens.

> One component will run in server mode, another component will start running in server mode, and later run in client mode.

One thing I'd like to clarify is that the auto render mode never dynamically changes the render mode of a component already on the page. The Auto render mode makes an _initial_ decision about which type of interactivity to use for a component, then the component keeps that type of interactivity for as long as it's on the page. One factor in this initial decision is considering whether there already exist components on the page with WebAssembly/Server interactivity. Auto mode will prefer to pick a render mode that matches the render mode of existing interactive components.

**Comment by bxjg1987** [comment]
@MackinnonBuck 
I understand what you mean. The component initially determines the rendering mode and does not switch rendering modes during its lifecycle. I think this is reasonable.

But in the same page, component A is in server mode and component B is in auto mode. If the assembly is ready, why is component B running in server mode instead of client mode.

**Comment by bxjg1987** [comment]
I am trying progressive development by creating a project for a blazer web app, selecting auto mode, and setting the rendering mode for each page.
Define all pages and components in the Xxx.  Client, inject them into the application service interface, and implement business logic interaction.

At the beginning of the project, all of my pages and components used server rendering mode, and the implementation classes of the application service interfaces referenced in the components or pages directly accessed the business logic layer, so I didn't have to separate the front-end and back-end to achieve rapid development.

In the later stage of the project, due to excessive server pressure caused by server rendering mode, I gradually set some complex components to auto mode.   At this time, the injected application service implementation class interacts with the backend API through HttpClient to save server memory and CPU.   This process is gradually implemented because I do not need to change all pages or components to auto rendering mode at once.   Therefore, at this stage, I need some components or pages to run in server rendering mode, and some components or pages to run in auto mode.

Adding to my comments above, I may need to place a server rendering mode component globally to achieve real-time notifications.

Therefore, in any case, for certain scenarios, we need to support both server rendering mode and auto rendering mode.

The reason why assembly is not only used is because it loads too slowly for the first time, but the auto rendering mode can improve this issue.

At present, the auto rendering mode of blazer relies on the mode of the previous page request.
