### ISSUE TITLE
Calling .NET Method in JavaScript Initializer Causes Error: No call dispatcher has been set

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#52711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a new Blazor web project, calling a .NET Method from `afterWebStarted` results in the following error: 

> Unhandled Promise Rejection: Error: No call dispatcher has been set

Before calling the .NET method via `DotNet.invokeMethodAsync`, I verify that `DotNet` is available.

### Expected Behavior

The invoked method should be reached successfully.

### Steps To Reproduce

Please see sample app [here](https://github.com/mrlife/BlazorApp) and notice the error on this line of BlazorApp.lib.module.js: `DotNet.invokeMethodAsync`

### Exceptions (if any)

> Unhandled Promise Rejection: Error: No call dispatcher has been set

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

`afterWebStarted` is not the hook you are looking for. It gets called inmediately after blazor web starts to allow you to hook into enhanced nav, etc. but at that point there are likely no runtimes started (or won't be reliable). You need to use `afterWebassemblyStarted` or `afterServerStarted`.

**Comment by mrlife** [comment]
@javiercn As an alternative, I also tried removing BlazorApp.lib.module.js and changing 

```javascript
<script src="_framework/blazor.web.js"></script>
```

to 

```javascript
<script src="_framework/blazor.web.js" autostart="false"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        Blazor.start().then(function () {
            console.log(DotNet);
            DotNet.invokeMethodAsync('BlazorApp', 'GetStringVal')
            .then(data => {
                console.log(data);
            });
        });
    }
</script>
```

The same error exists, though. Should everything be ready by then?

**Comment by mrlife** [comment]
Hi, please reopen as it is not resolved.

**Comment by mrlife** [comment]
Hi, please reopen as it is not resolved.

cc @mkArtakMSFT
