### ISSUE TITLE
Blazor optional EmailAddress validation issue

### ISSUE THREAD

**Issue by billreiss** [dotnet/aspnetcore#52743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If an [EmailAddress] attribute is placed on a model string property, if you don't put anything in that TextInput it passes validation as it should, because Required defaults to false, so the property should be optional. However if you type anything into that input and then remove it so the input box is empty again, it fails validation.

### Expected Behavior

I should be able to enter some text into the email textinput, and then delete it, and it should pass validation.

### Steps To Reproduce

I have a sample of this here https://github.com/billreiss/blazor_bugs/tree/main/ValidatingUserInput if you click submit without entering anything you'll see the email field passes validation, then enter anything into the box and then delete it so the TextInput is empty and submit again and you'll see that the validation fails, where it should succeed because it's an optional property.

### .NET Version

latest

**Comment by javiercn** [comment]
@billreiss thanks for contacting us.

@MariovanZeist answer is correct here.

**Comment by billreiss** [comment]
> Hi @billreiss The default EmailAddressValidator seems to behave differently if the email address is `""` instead of `null` it will return true when the string is `null` but false if it doesn't match the requirement (which a `""` string doesn't fulfill)
> 
> The problem you are seeing is that you start with the email address being `null` (so it says the address is "valid") But after typing text, and removing text, the input now will be an empty string `""`. which the default EmailAddress Validator will return as "Invalid"
> 
> Two simple solutions could be 1.) use `@bind:after` to call a function that forces the value to `null` when it's `""` 2.) Create your own EmailValidator. (below is a simple copy of the MS Validator with an additional empty check)
> 
> ```cs
>  [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
>  public sealed class MyEmailAddressAttribute : DataTypeAttribute
>  {
>      public MyEmailAddressAttribute()
>          : base(DataType.EmailAddress)
>      {
>          DefaultErrorMessage = "The {0} field is not a valid e-mail address.";
>      }
> 
>      public override bool IsValid(object? value)
>      {
>          if (value == null)
>          {
>              return true;
>          }
> 
>          if (!(value is string valueAsString))
>          {
>              return false;
>          }
> 
>          if (valueAsString.Length == 0)
>          {
>              return true;
>          }
> 
>          // only return true if there is only 1 '@' character
>          // and it is neither the first nor the last character
>          int index = valueAsString.IndexOf('@');
> 
>          return
>              index > 0 &&
>              index != valueAsString.Length - 1 &&
>              index == valueAsString.LastIndexOf('@');
>      }
>  }
> ```

Thank you, I would recommend updating the built in EmailAddress validator with this change.

**Comment by billreiss** [comment]
Based on the suggestion, I came up with something I think is cleaner. It could be simplified even more if I created a helper for the getter.

`		[EmailAddress]
		public string EmailAddress 
		{ 
			get
			{
				return string.IsNullOrWhiteSpace(emailAddress) ? null : emailAddress;
			}
			set
			{
				emailAddress = value;
			}
		}`

**Comment by billreiss** [comment]
Given the workaround of returning null on the property if the string is empty, I don't see any reason why EmailAddressValidator should return false if the string is empty and the field is optional. Recommend that EmailAddressValidator is updated with this logic.

**Comment by MariovanZeist** [comment]
@billreiss 
This would presumably be a breaking change, and seeing that this code has been virtually untouched for the last 9 years, I suspect changing it would impose a serious risk.

I checked other similar inquiries and saw responses like
https://github.com/dotnet/runtime/issues/83451#issuecomment-1480138877

So I think your best bet for now is the workaround you created.
