### ISSUE TITLE
`dotnet user-secrets` uses windows file path on WSL Linux

### ISSUE THREAD

**Issue by christianfosli** [dotnet/aspnetcore#52746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After adding a user secret with `dotnet user-secrets add <key> <value>` I expected the secret to available at `~/.microsoft/usersecrets/<user_secrets_id>/secrets.json`, as described in [the docs](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-8.0&tabs=linux#how-the-secret-manager-tool-works).

However after running the same command but adding `--verbose` I noticed dotnet is using `/mnt/c/Users/cfosli/AppData/Roaming/Microsoft/UserSecrets/<secretid>/secrets.json` instead.

This creates issues for me when debugging docker containers where I try to bind mount my ~/.microsoft/usersecrets folder into the container.

### Expected Behavior

The `~/.microsoft/usersecrets/<user_secrets_id>/secrets.json` file should be updated

### Steps To Reproduce

On WSL Linux:

```bash
mkdir testproj && cd testproj
dotnet new console
dotnet user-secrets init
dotnet user-secrets set 'secret-key' 'secret-value' --verbose
# Project file path /home/cfosli/Projects/tstproj/tstproj.csproj.
# Secrets file path /mnt/c/Users/cfosli/AppData/Roaming/Microsoft/UserSecrets/32f64663-3311-4e2c-be08-db0f29d8fe8f/secrets.json.
```

### .NET Version

8.0.100

### Anything else?

```bash
$ dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.2d90560f

Runtime Environment:
 OS Name:     fedoraremixforwsl
 OS Version:  39
 OS Platform: Linux
 RID:         fedora.39-x64
 Base Path:   /usr/lib64/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2d90560f
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.124 [/usr/lib64/dotnet/sdk]
  7.0.113 [/usr/lib64/dotnet/sdk]
  8.0.100 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.24 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by amcasey** [comment]
FWIW, I'm seeing
```
Project file path /home/amcasey/tmp/gh52746/gh52746.csproj.
Secrets file path /home/amcasey/.microsoft/usersecrets/81bc0a97-2ab3-45c8-aa2d-92ba57aa7b60/secrets.json.
```

I'm on Ubuntu, rather than Fedora, though.  (Also, 7.0, though that shouldn't matter.)

**Comment by amcasey** [comment]
@christianfosli I believe this is the code that determines the location: https://source.dot.net/#Microsoft.Extensions.Configuration.UserSecrets/PathHelper.cs,42

Looks like `APPDATA` wins - do you have that set?

**Comment by christianfosli** [comment]
> Looks like `APPDATA` wins - do you have that set?

I do, from a long time ago when I was trying a different approach for mounting user secrets into docker containers, I just didn't think it would affect this behavior.

Thanks for checking - I'll just unset this variable to get the behavior I want :smile:
