### ISSUE TITLE
Blazor 8 InteractiveServer : cascading parameter passed from App to MainLayout is null during second pass

### ISSUE THREAD

**Issue by guyvaio** [dotnet/aspnetcore#52758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to pass a cascading parameter (that is json serializable) from the new App.razor to MainLayout.razor. This works fine during prerendering. But during the second pass in MainLayout.razor, this cascading parameter is null.
The render mode is InteractiveServer.

### Expected Behavior

I hope this works like in the previous server side prerendered version. It was possible to pass a cascading parameter from the previous App.razor (containing) the router to the MainLayout. The cascading parameter in MainLayout was never null.

### Steps To Reproduce

- create new Blazor Web App
- in App.razor put  @rendermode="InteractiveServer" for both HeadOutlet and Routes
- in App.razor, inside HTML tag, place the cascadingValue tag
- in MainLayout code behind : add the corresponding [CascadingParameter]
-  in MainLayout, place a break in OnInitializedAsync 

1st time : prerendering : the cascading parameter is not null
2nd time : the cascading parameter is null

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@guyvaio thanks for contacting us.

Cascading parameters are not transferred across render boundaries. You need to pass the state as a regular parameter. We have a tracking issue for supporting a special version of this [here](https://github.com/dotnet/aspnetcore/issues/51969)
