### ISSUE TITLE
Blazor QuickGrid getting selected row

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#52751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-QuickGrid-getting-selected-row/10523558)._

---
Hi,
I'm looking at the Blazor QuickGrid that has just been released.
I'm trying to obtain which row has been clicked by the user, I was hoping the item key property might be of use but I can't work it out.
Simplistically I thought something like this might work, but not so much

Hopefully somebody can help.

Thanks
Justin

```
@page "/category-list"

<h3>Category List</h3>

@if (Categories != null)
{
    <div class="grid">
        <QuickGrid Items="@Categories" Pagination="@pagination" ItemKey="@(c => c.CategoryId)"
                   @onclick="@((ItemKey) => RowClick(ItemKey))">
            <PropertyColumn Property="@(c => c.CategoryId)" Sortable="true" />
            <PropertyColumn Property="@(c => c.CategoryName)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Description)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Picture)" Sortable="true" />
        </QuickGrid>
        <Paginator State="@pagination" />
    </div>
}

@code {

    IQueryable<Category> Categories { get; set; }

    PaginationState pagination = new PaginationState { ItemsPerPage = 15 };

    protected override void OnInitialized()
    {
        using (var dbContext = new NorthwindContext())
        {
            Categories = dbContext.Categories.ToList().AsQueryable();
        }
    }

    private void RowClick(int categoryId)
    {
        
    }

}

```

---
#### Feedback Bot on 11/22/2023, 05:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by fdonnet** [comment]
I could be wrong but your event is on the Grid, not on a row:
You can look at #44899 (it's an actual request to be able to click on a row).

**Comment by SPhilipp** [comment]
You need to use TGridItem.

I show you similar code

`<QuickGrid Items="@Users" Class="qg-body" TGridItem="DoSomeMore.Data.ApplicationUser">
    <PropertyColumn Property="@(p => p.UserName)" Sortable="true" Class="qg-row" />
    <PropertyColumn Property="@(p => p.Email)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Tickets.Count)" Sortable="true" />
    <TemplateColumn>
        <button class="menu-normal" @onclick="()=>EditUser(context)">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#fff" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
            </svg>
        </button>
    </TemplateColumn>
</QuickGrid>

private async Task EditUser(DoSomeMore.Data.ApplicationUser selectedUser)
{
    TargetUser = selectedUser;
}`
