### ISSUE TITLE
Blazor 8 InteractiveServer : newly created cookie not available in second pass of MainLayout.razor

### ISSUE THREAD

**Issue by guyvaio** [dotnet/aspnetcore#52759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A cookie created in App.razor in not present in the httpContextAccessor.HttpContext.Request.Cookies collection during the second pass. This problem occurs only in production server, not in development mode in VS.

### Expected Behavior

Like in version 7 with server side prerendered mode, the cookie collection should be up to date in second pass.

### Steps To Reproduce

1. Create new Blazor Web App
2. In the new App.razor code-behind put this code:

```
private IHttpContextAccessor _httpContextAccessor;
[Inject]
private IHttpContextAccessor httpContextAccessor
{
	get => _httpContextAccessor;
	set
	{
		_httpContextAccessor = value;
		string g = _httpContextAccessor.HttpContext.Request.Cookies["SessionGuid"] ?? "";
		if (!Guid.TryParse(g, out Guid guid))
		{
			Guid sessionGuid = Guid.NewGuid();
			_httpContextAccessor.HttpContext.Response.Cookies.Append("SessionGuid", sessionGuid.ToString(), new CookieOptions { Secure = true, HttpOnly = true, Path = "/", SameSite = SameSiteMode.Lax });
		}
	}
}
```
3. In MainLayout.razor, inject IHttpContextAccessor and test the value of
`httpContextAccessor.HttpContext.Request.Cookies["SessionGuid"]`
During the second pass, it is null on production server (IIS) and not null in development mode.

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@guyvaio thanks for contacting us.

In Blazor web, there is a `[CascadingParameter] HttpContext { get; set; }` that can be used for that.

**Comment by guyvaio** [comment]
Cascading parameters does not pass at this place: https://github.com/dotnet/aspnetcore/issues/52758

**Comment by guyvaio** [comment]
@javiercn please give some more explanations to let us understand the consistency of your answers on different posts.
Definitely is there a real way to pass a single string (or somewhat else) form interactive 8 pre-rendering to interactive 8 second pass. 

This is needed to maintain trust in MS products.

Do such abrupt and curt answers help anyone ?

**Comment by guyvaio** [comment]
The cookie was not created because http used (not https) and the cookie appended with `Secure = true`.
Once this fixed, the newly created cookie is available in the httpContextAccessor.HttpContext.Request.Cookies collection during the second pass.
Sorry for the inconvenience.
