### ISSUE TITLE
Calling external .dll fails after upgrading to .NET 8

### ISSUE THREAD

**Issue by Schoof-T** [dotnet/aspnetcore#52761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a .dll file from a company that I need to call to process some work. The dll is created in powerbuilder.

The .dll required the application to be x86, required Winforms and a bunch of powerbuilder dlls.
I created an API as a wrapper around this .dll, I simply referenced the .dll file
![image](https://github.com/dotnet/aspnetcore/assets/2319986/7d385a0f-7258-4a93-8ae9-8969c2844881)

and called it's methods:
```
 var generators = new Abs_Pdf();

 if (model.PageSize.HasValue && model.Orientation.HasValue)
 {
     generators.set_pdf_size(model.PageSize.Value, model.Orientation.Value);
 }

 _logger.LogInformation("Start Converting Template To Pdf - {table}:{id}", model.TablePrefix, model.PrimaryKey);

 var result = generators.get_template_pdf_file(model.TablePrefix, model.PrimaryKey, ref outputPath);
```

This all worked until I wanted to upgrade my API to .NET 8. Now calling the dll gives an exception (the exception is caught in the dll I assume, because it's simply returning a string saying "Failed!".

Are there any changes to calling a referenced library?

I also contacted the company and asked them, but seeing as it worked in .NET 7, I thought maybe it should/could work in .NET 8 as well.

### Expected Behavior

Calling the .dll library would not result in an error.

### Steps To Reproduce

I cannot share the .dll as it is intellectual property.

- Create new .NET 7 API project
- Add external library (dll)
- Call external library --> Success
- Upgrade to .NET 8
- Call external library --> Fail

### .NET Version

8.0.100

**Comment by martincostello** [comment]
Could you please provide the specifics about the exception that occurs when you try to call the library? You should be able to configure Visual Studio to break when the exception is thrown, even if it's caught in the other library, to see what happened and what the stack trace is.

**Comment by Schoof-T** [comment]
> Could you please provide the specifics about the exception that occurs when you try to call the library? You should be able to configure Visual Studio to break when the exception is thrown, even if it's caught in the other library, to see what happened and what the stack trace is.

Thank you, the excpeption I receive is the following:
`'Could not load type 'System.Drawing.Printing.PrintingPermission' from assembly 'System.Drawing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'`

**Comment by martincostello** [comment]
Looking at the code in dotnet/runtime, the `System.Drawing.Printing.PrintingPermission` type was moved from the `System.Drawing` assembly to the `System.Security.Permissions` assembly ([code](https://github.com/dotnet/runtime/blob/cfa42d32b45780c85a407b5dfde4bb7d30433da8/src/libraries/shims/System.Drawing/src/System.Drawing.cs#L129) around .NET 8 preview 4 (https://github.com/dotnet/runtime/commit/c0cca338479fc5274a2d1325ca64e488b741f895#diff-7b9021540cd5d7eb20f120d664bf21947770715ddbfaf2cf5490501ec7699a70).

Is System.Security.Permissions published/available somewhere to your app?

Seems like the refactoring is breaking something compiled against an older version that now can't find whatever it is it's looking for, which appears to be related to Code Access Security, which [isn't really a thing anymore in .NET (Core)](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/code-access-security-apis-obsolete).

**Comment by Schoof-T** [comment]
> Is System.Security.Permissions published/available somewhere to your app?

I could just manually reference maybe? Is the System.Security.Permissions available somewhere secure?

**Comment by Schoof-T** [comment]
I tried adding the nuget 'System.Security.Permissions' but nothing changed. Any further ideas?

**Comment by Schoof-T** [comment]
Any further ideas on this?

**Comment by martincostello** [comment]
Nope - still seems like your external DLL is broken with respect to .NET 8 and you should consult the original vendor to provide a fix and/or for technical support.

**Comment by captainsafia** [comment]
@martincostello Thanks for the initial triage on this!

@Schoof-T As mentioned, based on the repro details you are able to provide it is not clear that this might be an issue in ASP.NET Core. I'd recommend reaching out to the vendor to see what insights they might have. Off the top of my head, I'm not aware of any obvious changes introduced between 7.0 and 8.0 that would cause this issue.

For now, closing this out as an external bug.
