### ISSUE TITLE
Are there any plans to provide runtime for 'linux-bionic-arm64'?

### ISSUE THREAD

**Issue by xljiulang** [dotnet/aspnetcore#52764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to provide a proposed http/1.1 server based on kestrel on Android, but found that there is no runtime available.

### Describe the solution you'd like

Provide runtime for 'linux-bionic-arm64'.

**Comment by JamesNK** [comment]
There is discussion here: https://github.com/dotnet/aspnetcore/issues/35077

There aren't concrete plans right now, but we're listening to feedback.
