### ISSUE TITLE
Build in AuthenticationStateProviders from Blazor Web templates

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#52769]
In .NET 9, we should automatically register both server and client `AuthenticationStateProvider`'s similar to the ones added by the "Individual Auth" option in the Blazor Web templates.

- [PersistingServerAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/PersistingServerAuthenticationStateProvider.cs)
- [PersistentAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/PersistentAuthenticationStateProvider.cs)

This should make it a lot easier to add auth to a Blazor project that is created without the "Individual Auth" template. As part of this, we will want to figure out which claims are safe to transmit to the clients, and potentially add a callback to configure custom claims.

**Comment by Deineris** [comment]
Is there any guides on how to have a workaround untill this is finished? Wanted to suggest the newly released Blazor United as a base for an upcoming project, but since I can't figure out how the authentication and authorization against B2C with custom user flows would work, that a nonstarter, sadly. I assume in might work OK with server-side rendering, but the whole idea is to have them mixed. And since there is no template for Microsoft Identity (only individual accounts), then I assume that is not guaranteed to work, right?

**Comment by halter73** [comment]
> Is there any guides on how to have a workaround untill this is finished?

You can take a look at https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc. The sample include PersistingServerAuthenticationStateProvider.cs and PersistentAuthenticationStateProvider.cs that are similar to the ones in the individual auth template.

**Comment by halter73** [comment]
## Background and Motivation

In .NET 9, we should automatically register both server and client `AuthenticationStateProvider`'s similar to the ones added by the "Individual Auth" option in the Blazor Web templates.

- [PersistingServerAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/PersistingServerAuthenticationStateProvider.cs)
- [PersistentAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/PersistentAuthenticationStateProvider.cs)

This should make it a lot easier to add auth to a Blazor project that is created without the "Individual Auth" template. As part of this, we will want to figure out which claims are safe to transmit to the clients, and potentially add a callback to configure custom claims.

## Proposed API

```diff
// Microsoft.AspNetCore.Components.Endpoints.dll

namespace Microsoft.AspNetCore.Components.Endpoints;

/// <summary>
/// Provides options for configuring server-side rendering of Razor Components.
/// </summary>
public sealed class RazorComponentsServiceOptions
{
+    public bool SerializeAuthenticationStateToClient { get; set; } = false;
+    public Func<AuthenticationState, Task<IEnumerable<KeyValuePair<string, string>>>> SerializeAuthenticationState { get; set; } = SerializeClaimsDefault;
+
+    private static async Task<IEnumerable<KeyValuePair<string, string>>> SerializeClaimsDefault(AuthenticationState authenticationState)
+    {
+        foreach (var claim in authenticationState.User.Claims)
+        {
+            yield return new KeyValuePair<string, string>(claim.Type, claim.Value);
+        }
+    }
}
```

```diff
// namespace Microsoft.AspNetCore.Components.WebAssembly.dll

namespace Microsoft.AspNetCore.Components.WebAssembly.Hosting;

+ public sealed class AuthenticationStateDeserializationOptions
+ {
+    public Func<IEnumerable<KeyValuePair<string, string>>, Task<AuthenticationState>> DeserializeAuthenticationState { get; set; } = DeserializeAuthenticationState;
+
+    private static Task<AuthenticationState> DeserializeClaimsDefault(IEnumerable<KeyValuePair<string, string>> claims)
+    {
+        return Task.FromResult(
+            new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(claims.Select(c => new(c.Type, c.Value),
+                authenticationType: "DeserializedAuthenticationState"))));
+    }
+ }
+
+  namespace Microsoft.Extensions.DependencyInjection;
+
+ public static class DeserializeAuthentciationStateServiceCollectionExtensions
+ {
+     public static void ConfigureAuthenticationStateDeserialization(Action<AuthenticationStateDeserializationOptions> configureOptions);
+ }
```

## Usage Examples

The simplest way to serialize/deserialize all claims is just to set `SerializeAuthenticationStateToClient` to true.

```csharp
// Program.cs for server project

builder.Services.AddRazorComponents(o => o.SerializeAuthenticationStateToClient = true)
                         .AddInteractiveWebAssemblyComponents()
```

Alternatively, you could include only specific claims:

```csharp
// Program.cs for server project

async Task<IEnumerable<KeyValuePair<string, string>>> MySerializeClaims(AuthenticationState authenticationState)
{
    foreach (var claim in authenticationState.User.Claims)
    {
        if (myAllowedClaims.Contains(claim.Type))
        {
            yield return new KeyValuePair<string, string>(claim.Type, claim.Value);
        }
    }
}

builder.Services.AddRazorComponents(o =>
{
    o.SerializeAuthenticationStateToClient = true;
    o.SerializeAuthenticationState = MySerializeClaims
})
    .AddInteractiveWebAssemblyComponents()
    .AddInteractiveServerComponents();
```

## Alternative Designs

We could change all references to "AuthenticationState" to "ClaimsPrincipal". We could come up with better naming for "serialize" and "deserialize"? Maybe something involving "transmit" or "initialize".

Instead of exposing `KeyValuePair<string, string>` we could create a `ClaimItem` type or something. We don't want to use `Claim` because it includes a lot of detail we're usually uninterested in.

## Risks

We must always register a default `AuthenticationStateProvider` for calls to `AddRazorComponents`, because we enable authentication state serialization using options which can be configured after registered services are finalized. If someone tries to `TryAdd` a custom `AuthenticationStateProvider`, this might break them. I think this is unlikely though.

**Comment by amcasey** [comment]
- Typo: Authentciation
- `Task<IEnumerable>` vs `IAsyncEnumerable`?
- Can we use an extension method instead on `AddRazorComponents` instead of adding a settable boolean?
    - That wouldn't be as clean - this is more consistent with the ownership
- Perf concern: if this happens automatically, it might cost apps that aren't using it
    - It's lazy though

**Comment by halter73** [comment]
The PR has been merged in preview5, but I'm reopening this to finish the API review discussion. We can still make changes in preview6.

**Comment by amcasey** [comment]
[API Review]

- Why `KeyValuePair<string, string>` instead of `Claim`?
    - `Claim` contains a bunch of extra stuff that seems superfluous (e.g. when serializing)
    - What if I already have a `Claim` in hand?
        - Yes, you have to pull out the fields
    - It is sufficiently clear to an auth user what the two strings are and what order they're in
- Claim types are usually URLs and that's why they're typed as strings
- AuthenticationStateData is basically just the object model for the JSON going back and forth
- "All" is in contrast to "only name and role"
- Seal all the things
- Name and Role claims are special and that's why they get dedicated properties in `AuthenticationStateData` (but the values are in the regular list of pairs)
- Let's go with a custom type in place of `KeyValuePair<string, string>` - it can also make conversions from `Claim` easy
    - It will be called `ClaimData`
    - ```csharp
    - public readonly struct ClaimData(string type, string value)
    - {
        - public ClaimData(Claim claim) { }
        - public string Type => type;
        - public string Value => value;
    - }
    - ```
- We like Propagation, but we're worried it might be ambiguous if both ends were called that
- We kind of like Transmission because it conveys something will be leaving your box
- Serialization sort of ambiguously suggests local persistence
- AddAuthenticationStateSender/Receiver conveys the relationship but doesn't accurately convey the action
- We're not big fans of SerializeAllClaims because of the way it introduces interaction between option properties, but it does work nicely with configuration binding, which is why an overload or a void-method isn't a good substitute
    - If we get permission from the security SMEs, we'll remove it entirely

**Comment by amcasey** [comment]
```diff
// Microsoft.AspNetCore.Components.Server.dll
+ [assembly: TypeForwardedTo(typeof(Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider))]

// Microsoft.AspNetCore.Components.Endpoints.dll
+ namespace Microsoft.AspNetCore.Components.Server;

+ public class ServerAuthenticationStateProvider : AuthenticationStateProvider, IHostEnvironmentAuthenticationStateProvider
```

```diff
// Microsoft.AspNetCore.Components.Authorization.dll
namespace Microsoft.AspNetCore.Components.Authorization;

+ public class AuthenticationStateData
+ {
+     public IList<ClaimData> Claims { get; set; } = [];
+     public string NameClaimType { get; set; } = ClaimsIdentity.DefaultNameClaimType;
+     public string RoleClaimType { get; set; } = ClaimsIdentity.DefaultRoleClaimType;
+ }
+ 
+ public readonly struct ClaimData(string type, string value)
+ {
+     public ClaimData(Claim claim) { }
+     public string Type => type;
+     public string Value => value;
+ }
```

```diff
// Microsoft.AspNetCore.Components.WebAssembly.Server.dll
namespace Microsoft.AspNetCore.Components.WebAssembly.Server;

+ public class AuthenticationStateSerializationOptions
+ {
+     public bool SerializeAllClaims { get; set; }
+     public Func<AuthenticationState, ValueTask<AuthenticationStateData?>> SerializationCallback { get; set; } = SerializeAuthenticationStateAsync;
+ }

namespace Microsoft.Extensions.DependencyInjection;

public static class WebAssemblyRazorComponentsBuilderExtensions
{
    public static IRazorComponentsBuilder AddInteractiveWebAssemblyComponents(this IRazorComponentsBuilder builder);

+     public static IRazorComponentsBuilder AddAuthenticationStateSerialization(this IRazorComponentsBuilder builder, Action<AuthenticationStateSerializationOptions>? configure = null)
}
```

```diff
// Microsoft.AspNetCore.Components.WebAssembly.Authentication.dll
namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication;

+ public sealed class AuthenticationStateDeserializationOptions
+ {
+     public Func<AuthenticationStateData?, Task<AuthenticationState>> DeserializationCallback { get; set; } = DeserializeAuthenticationStateAsync;
+ }

namespace Microsoft.Extensions.DependencyInjection;

public static class WebAssemblyAuthenticationServiceCollectionExtensions
{
    // public static IRemoteAuthenticationBuilder<TRemoteAuthenticationState, TAccount> AddRemoteAuthentication<...
+    public static IServiceCollection AddAuthenticationStateDeserialization(this IServiceCollection services, Action<AuthenticationStateDeserializationOptions>? configure = null);
}
```

We would really like to drop `SerializeAllClaims`, security permitting.

API approved

**Comment by amcasey** [comment]
@halter73 What happened with this?
> We would really like to drop SerializeAllClaims, security permitting.

**Comment by halter73** [comment]
The idea was to make `SerializeAllClaims` the default, right? I don't think anything has changed since we decide to [remove InfoResponse.Claims](https://github.com/dotnet/aspnetcore/pull/51177) from `MapIdentityApi`. Both were new APIs that someone would need to opt into calling, but where it might not be clear that all server-side claims would be visible to the client. I didn't really push it though.

If @blowdart thinks someone calling `AddAuthenticationStateSerialization` is a clear enough opt-in to serializing all claims, I'm more than happy to remove the `SerializeAllClaims` option and make that the default behavior.

**Comment by blowdart** [comment]
I think being specific is better here.

And I wish I'd read the design before because I disagree that some of the information in the claims class is superfluous 😕
