### ISSUE TITLE
Blazor's InputSelect does not validate with Required attribute

### ISSUE THREAD

**Issue by jeremysalwen** [dotnet/aspnetcore#52779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using an required enum property with an input select, the validation is mistakenly not performed:

```
    [Required]
    public SomeEnum SomeEnum { get; set; }
 ```
 
 Will not validate the required value, and instead silently sets it to the invalid enum value 0.
 
 This bug was previously reported but mistakenly closed: [Blazor's InputSelect does not validate with Required attribute](https://github.com/dotnet/aspnetcore/issues/27746)  The bug is still present in .NET 8.

### Expected Behavior

I expect the validation to fail since a Required property is not set, i.e. the behavior of any other input element.

### Steps To Reproduce

```public enum SomeEnum
{
    A = 1,
    B = 2
}
```

```
public class SomeModel
{
    [Required]
    public string SomeString { get; set; }

    [Required]
    public SomeEnum SomeEnum { get; set; }

    [Required]
    public SomeEnum? SomeNullableEnum { get; set; }

    [Required]
    public int SomeInt { get; set; }

    [Required]
    public int? SomeNullableInt { get; set; }
}
```
```
@page "/testrequired"
@using TestNET5BlazorServerApp.Data;


<EditForm Model="Model" OnValidSubmit="Submit">

    <DataAnnotationsValidator />
    <ValidationSummary />

    String:
    <br />
    <InputText @bind-Value="Model.SomeString" />
    <br />
    <br />
    Enum:
    <br />
    <InputSelect @bind-Value="Model.SomeEnum">
        <option value="0">Select Enum</option>
        <option value="@SomeEnum.A">@SomeEnum.A</option>
        <option value="@SomeEnum.B">@SomeEnum.B</option>
    </InputSelect>
    <br />
    <br />

    Nullable Enum:
    <br />
    <InputSelect @bind-Value="Model.SomeNullableEnum">
        <option>Select Nullable Enum</option>
        <option value="@SomeEnum.A">@SomeEnum.A</option>
        <option value="@SomeEnum.B">@SomeEnum.B</option>
    </InputSelect>
    <br />
    <br />

    Int:
    <br />
    <InputSelect @bind-Value="Model.SomeInt">
        <option>Select Int</option>
        <option value="1">1</option>
        <option value="2">2</option>
    </InputSelect>
    <br />
    <br />

    Nullable Int:
    <br />
    <InputSelect @bind-Value="Model.SomeNullableInt">
        <option>Select Nullable Int</option>
        <option value="1">1</option>
        <option value="2">2</option>
    </InputSelect>
    <br />
    <br />

    <button type="submit">Save</button>
</EditForm>

@code 
{
    SomeModel Model = new Data.SomeModel();

    void Submit()
    {
        System.Diagnostics.Debug.WriteLine("Enum " + Model.SomeEnum);
        System.Diagnostics.Debug.WriteLine("Nullable Enum " + Model.SomeNullableEnum);
        System.Diagnostics.Debug.WriteLine("Int " + Model.SomeInt);
        System.Diagnostics.Debug.WriteLine("Nullable Int " + Model.SomeNullableInt);
    }
}
```

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@jeremysalwen thanks for contacting us.

Unfortunately, the semantics for the required attribute aren't "this property was set". RequiredAttribute only checks for null values and empty strings if configured to do so.

In your case, you can either use a nullable Enum or create your own validation attribute. In your case, you should use 
`[EnumDataType(typeof(SomeEnum))]` to ensure the value was set.

The logic for the required attribute is [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RequiredAttribute.cs). We don't do any processing nor special casing based on it at the Blazor level.
