### ISSUE TITLE
How To Obfuscation WASM Files

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#52806]
My Last Issue I Asked Last Comment And Microsoft Bot Closed Issue
https://github.com/dotnet/aspnetcore/issues/52712#issuecomment-1850141453

Ok How To Obfuscation For My App Using WASM

I Maked ReportDesigner With Webassembly And I Want To obfuscate The ReportDesigner Cause ReportDesigner
Is Too Hard So I Don't Want Anybody To Decompile The WASM And Read The Code And Copy Code Cause My ReportDesigner

7% JS
10% Razor
83% C#

So C# Code Should Be obfuscated

I Want Way To obfuscate .wasm Files

**Comment by javiercn** [comment]
@wisamidris7 thanks for contacting us.

Anything that gets downloaded to the browser will be disclosed. Obfuscation is not a valid principle for security and is not a recommended practice as it doesn't add any real confidentiality.

If you want to prevent third parties from accessing IP in your app, you should not put that as part of anything that runs on webassembly in the same way you wouldn't put that IP inside a script.

For cases like that, it's better if you make a server component and keep the logic there. That's the only way.

There are third-party "obfuscation" tools in the .NET ecosystem, but I doubt they work with wasm.

**Comment by wisamidris7** [comment]
Thanks
