### ISSUE TITLE
Blazor NavigationManager redirect to NotFound if route parameter contains encoded /

### ISSUE THREAD

**Issue by pmpbpl** [dotnet/aspnetcore#52808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NavigationManager redirects to NotFound if route parameter contains encoded '/' instead of requested page. 

ex:
/cars/parts%20w%2F%20issue/show

It was working in .net 6. Stops after update to .net8.

### Expected Behavior

Navigate to page and bind parameter.

### Steps To Reproduce
[repo](https://github.com/pmpbpl/blazor-issue-52808)

### .NET Version

.net8.0

**Comment by pmpbpl** [comment]
[repo](https://github.com/pmpbpl/blazor-issue-52808)

**Comment by pmpbpl** [comment]
@javiercn hi, could you provide me ETA, when you will be able to look into this issue, we are blocked with .net8 production release.

**Comment by javiercn** [comment]
This is now fixed in main; we'll probably backport it to 8.0 in a future patch release.

**Comment by mkArtakMSFT** [comment]
@pmpbpl did you by any chance try the fix out from the nightly build to see if this indeed has addressed the issue you were facing? It most probably did, but would be nice to get confirmation.

**Comment by pmpbpl** [comment]
Yes, this fix solves navigation issue:)
