### ISSUE TITLE
 Identity endpoint /manage/info not responding after deployment to Azure

### ISSUE THREAD

**Issue by PedrooNL** [dotnet/aspnetcore#52805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

cc: @guardrex 

I've trouble receiving anything from the identity endpoint ../manage/info after deploying the BackEnd (https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend) to Azure. I'm sure all CORS settings on Azure are okay.

Issue after a succesfull login:

System.Net.Http.HttpClient.Auth.LogicalHandler[100]
      Start processing HTTP request POST https://xxxxxxx.azurewebsites.net/login?useCookies=true
invoke-js.ts:176 info: System.Net.Http.HttpClient.Auth.ClientHandler[100]
      Sending HTTP request POST https://xxxxxxx.azurewebsites.net/login?useCookies=true
invoke-js.ts:176 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
invoke-js.ts:176 info: System.Net.Http.HttpClient.Auth.ClientHandler[101]
      Received HTTP response headers after 939.6999ms - **200**
invoke-js.ts:176 info: System.Net.Http.HttpClient.Auth.LogicalHandler[101]
      End processing HTTP request after 940.7999ms - **200**
invoke-js.ts:176 info: System.Net.Http.HttpClient.Auth.LogicalHandler[100]
      Start processing HTTP request GET https://xxxxxxx.azurewebsites.net/manage/info
invoke-js.ts:176 info: System.Net.Http.HttpClient.Auth.ClientHandler[100]
      Sending HTTP request GET https://xxxxxxx.azurewebsites.net/manage/info
polyfills.ts:120 

`GET https://xxxxxxx.azurewebsites.net/manage/info **401** (Unauthorized)`

### Expected Behavior

{
  "email": "name@domain.com",
  "isEmailConfirmed": true
}

### .NET Version

.net 8

**Comment by PedrooNL** [comment]
Adding
builder.Services.AddScoped<IdentityRedirectManager>();
does already change things. But still empty reply.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like you're trying to access your backend APIs from a client hosted on a different domain. What is happening here, is that by default the browser doesn't include credentials with cross-domain requests, so you have to explicitly configure that to happen. Here is the guidance for how to do that: https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#client-side-signalr-cross-origin-negotiation-for-authentication

```csharp
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.WebAssembly.Http;

public class IncludeRequestCredentialsMessageHandler : DelegatingHandler
{
    protected override Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // HERE IS THE IMPORTANT CALL
        request.SetBrowserRequestCredentials(BrowserRequestCredentials.Include);
        return base.SendAsync(request, cancellationToken);
    }
}
```
