### ISSUE TITLE
[Blazor Web Discussion] Clarify Data Access for auto mode

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspnetcore#52818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have the auto render mode now. But for WASM, we can't get access to EFCore DbContext, we still need to do CURD stuff through API call. What I'm doing now, is to create a common interface for data access. And implement it for both modes:
```csharp
public interface IFileService
{
    public File GetFileById(int id);
}

public sealed class ServerFileService : IFileService
{
    public File GetFileById(int id) => //use EFCore
}

public sealed class WasmFileService : IFileService
{
    public File GetFileById(int id) => //api request
}

//I have to implement API too
app.MapGet("files/{id:int}", GetFileById)
```
This brings huge duplication.

### Describe the solution you'd like

Is above the right way?
I know an alt is to use API for both modes. But WASM uses `HttpClient` as fetch through browser which we can let it include cookies to pass authentication. When we use server side `HttpClient` to send request to server itself, how can we identify the user. We have to implement token-based authentication too?
All these things make the auto mode very complex. Are there any other advantages for using auto mode besides avoiding waiting WASM Runtime, saving server circuits connections, and providing SSR?
I hope there can be an official suggestion or add some stuff into official docs.

**Comment by javiercn** [comment]
@Kumima thanks for contacting us.

This is currently the right way to do it, it's an area that we plan to make future improvements, but essentially if you choose auto, you need to implement the data access for both server, and webassembly.

**Comment by Kumima** [comment]
Thanks for the quick reply. Glad to hear there is a plan to improve.

**Comment by AmBplus** [comment]
This is still not clear to me , create two endpoint for each request , to check every time this is a wasm or server , and many other stuff like this , this like you create a half tools for create a web app , in outside you will see a very good presentation, that's tell we have create a auto mode to resolve your problem in server side and wasm , but still not have a clear way to send a simple request , it's a very very basic feature of every web app , but still in blazor auto render mode not have a clear way to do it , I hope soon this problem
