### ISSUE TITLE
Telegram miniapp (TMA) developmet via blazor

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#52825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently we can write TMA using javascript it's just a web app, meanwhile we can develop webapp already using blazor, but there is not a way yet to create a project in visual studio for using blazor for TMA

### Describe the solution you'd like

Let's support developing TMA on visual studio using blazor by letting people create a 'telegram mini app using blazor' project

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This is not a direction we plan to go in. For these types of projects its best to look for a community project or start your own one.
