### ISSUE TITLE
.net 7 and 8 AddFacebook 

### ISSUE THREAD

**Issue by frederic-thibault** [dotnet/aspnetcore#52836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After spending lot of time trying to figured why the facebook login is not working, I just created a very simple app from the code find in ms site and the errro remain the same.

Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: The oauth state was missing or invalid.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) 

The request is never send to Facebook, it stops at the validation in OAuthHandler, it tries to validate the querystrign parameter state, but I have nothing here, I only have the **access_token**, the variable properties is always null.

`protected override async Task<HandleRequestResult> HandleRemoteAuthenticateAsync()
{
	IQueryCollection query = base.Request.Query;
	StringValues stringValues = query["state"];
	AuthenticationProperties properties = base.Options.StateDataFormat.Unprotect(stringValues);
	if (properties == null)
	{
		return HandleRequestResults.InvalidState;
	}`

This is all I have in my project since I try to resolve this issue. I have the same problem when I setup the entire solution from https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-8.0&tabs=visual-studio

`var builder = WebApplication.CreateBuilder(args);

builder.Services
       .AddAuthentication()
       .AddFacebook(facebookOptions =>
       {
           facebookOptions.ClientId = "XXX";
           facebookOptions.ClientSecret = "XXX";
           facebookOptions.AccessDeniedPath = "/accessdeniedpathinfo";
       });

var app = builder.Build();

app.Run();
`

Thanks,

### Expected Behavior

I expect to be able to validate the facebook token without this error.

### .NET Version

7 and 8.0.100

**Comment by frederic-thibault** [comment]
I generate the token from an angular application, get the token and send it to the api using postman. I post t from the bidy, from the querystring but in all cases I dont have any state to provide in the querystring.

**Comment by Tratcher** [comment]
This provider is not meant for use with client SDKs & SPA apps, it communicates directly with the facebook OAuth server via redirects. This flow must be initiated on the server, not the client.

**Comment by frederic-thibault** [comment]
> This provider is not meant for use with client SDKs & SPA apps, it communicates directly with the facebook OAuth server via redirects. This flow must be initiated on the server, not the client.

Knowing how how to generate this state will be helpfull to reuse the same logic.
Thanks very much.
