### ISSUE TITLE
Blazor Server and CkEditor problem

### ISSUE THREAD

**Issue by doanhquang2005** [dotnet/aspnetcore#52855]
When clicking on tag a with href="/home", it redirects to page "/home". How can I edit the link when I click on this a tag?

**Comment by doanhquang2005** [comment]
I have found a solution to address the aforementioned issue by adding the following code during the Editor initialization:
```
editor.ui.view.editable.element.addEventListener('click', (e) => {
    e.preventDefault();
});
```
This snippet effectively prevents the Blazor Server from capturing and redirecting click events on internal links within the editor. Implementing this modification ensures a more seamless and expected user experience, overcoming the challenge posed by the default behavior.

It is my hope that Blazor continues to evolve and improve, providing developers with enhanced tools and capabilities.

**Comment by javiercn** [comment]
@doanhquang2005 thanks for contacting us.

> I have found a solution to address the aforementioned issue by adding the following code during the Editor initialization:
> 
> ```
> editor.ui.view.editable.element.addEventListener('click', (e) => {
>     e.preventDefault();
> });
> ```
> 
> This snippet effectively prevents the Blazor Server from capturing and redirecting click events on internal links within the editor. Implementing this modification ensures a more seamless and expected user experience, overcoming the challenge posed by the default behavior.
> 
> It is my hope that Blazor continues to evolve and improve, providing developers with enhanced tools and capabilities.

The solution you are proposing is the expected approach. I'm assuming you have links within the rendered editor that are part of the contents of the editor. If you don't want Blazor to handle them, you need to register the callback on the root element of the editor and handle the event there.
