### ISSUE TITLE
Blazor Web App with Microsoft Entra External ID Exhibits Inconsistent Unauthorized Access Behavior

### ISSUE THREAD

**Issue by moshali1** [dotnet/aspnetcore#52856]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a Blazor Web App using Microsoft Entra External ID for authentication, there is inconsistent behavior in handling unauthorized access. When navigating to an unauthorized page via the application's navbar, the "Not Authorized" text from Routes.razor is displayed as expected. However, when attempting to access the same route from a new page or an external link, the application instead redirects to an HTTP 404 error page with the URL:

https://localhost:7073/MicrosoftIdentity/Account/AccessDenied?ReturnUrl=%2F.

### Expected Behavior

The application should consistently display the "Not Authorized" message for unauthorized access, irrespective of the method used to navigate to the restricted page.

### Steps To Reproduce

[repro
](https://github.com/moshali1/aspnet_blazor)

Navigate to a restricted page using the application's navbar. Observe the display of "Not Authorized" text.
Attempt to access the same unauthorized page from a new page or an external link.

### .NET Version

net8.0

### Anything else?

I suspect the issue may be related to a routing configuration error in the Blazor Web App. The app is configured for Interactive Server with Global Interactivity.

The issue could also be from the identity configuration (or the Microsofot.Identity.Web.UI) because it was based on ASP.NET (MVC) sample app. 

[Microsoft Entra External ID for ASP.NET Documentation](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-web-app-dotnet-sign-in-prepare-tenant )

**Comment by moshali1** [comment]
Found a related pending issue: #52586.

**Comment by moshali1** [comment]
[This ](https://github.com/dotnet/aspnetcore/issues/52317#issuecomment-1830673284)workaround worked for me.

**Comment by halter73** [comment]
Thanks for filing the issue with a full repro project.

Calling `MapRazorComponents<App>().AllowAnonymous()` might also work if you have the `<AuthorizeRouteView>` set up correctly. The benefit of that over the `IAuthorizationMiddlewareResultHandler` is that non-Blazor routes are unaffected, so there's less of a risk of unintentionally disabling auth for things like API controllers. Take a look at https://github.com/dotnet/aspnetcore/issues/53732#issuecomment-2021878231 for more details. The suggestions in https://github.com/dotnet/AspNetCore.Docs/issues/31931#issuecomment-1970240747 might be helpful to you as well.

We're using #51836 and #52063 to track improving the way Blazor works with auth and endpoint routing so these kinds of workarounds are unnecessary.
