### ISSUE TITLE
EventCallbackFactory has wrong nullability annotations for all callback parameters.

### ISSUE THREAD

**Issue by springy76** [dotnet/aspnetcore#52872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All public Create* methods of `EventCallbackFactory` require the callback argument to be non-null, but in fact both `EventCallback` itself has declared the Callback property being nullable, and also the internal `CreateCore` methods handle the callback as nullable (but don't declare so, too):

```cs
    private static EventCallback CreateCore(object receiver, MulticastDelegate callback)
    {
        return new EventCallback(callback?.Target as IHandleEvent ?? receiver as IHandleEvent, callback);
    }

    private static EventCallback<TValue> CreateCore<TValue>(object receiver, MulticastDelegate callback)
    {
        return new EventCallback<TValue>(callback?.Target as IHandleEvent ?? receiver as IHandleEvent, callback);
    }
```

If I now do the following (which at least works, but with compiler warnings):

```razor
    Action<ChangeEventArgs>? onChange = shouldBeReadonly ? null : args => ProcessData(args, model);

    <select @onchange="@onChange" ... />
```

I get the warning: `warning CS8604: Possible null reference argument for parameter 'callback' in 'EventCallback<ChangeEventArgs> EventCallbackFactory.Create<ChangeEventArgs>(object receiver, Action<ChangeEventArgs> callback)'.`

### Expected Behavior

No warnings for good code - I really would like to enable "tread warnings as errors".

### .NET Version

7.x / 8.0.0

**Comment by javiercn** [comment]
@springy76 thanks for contacting us.

This is by design. You aren't allowed to pass null to event callbacks, even though the underlying code "supports" it. You should pass in an empty delegate instead.

**Comment by springy76** [comment]
@javiercn The **public** ctor of `EventCallback` allows it:

```cs
    internal readonly MulticastDelegate? Delegate;
    internal readonly IHandleEvent? Receiver;

    public EventCallback(IHandleEvent? receiver, MulticastDelegate? @delegate)
    {
        Receiver = receiver;
        Delegate = @delegate;
    }
```

So how should this **not** be by design?

**Comment by springy76** [comment]
@msftbot 💩 **A**rtificial **I**nsanity 🤦‍♂️
