### ISSUE TITLE
HTTP2_PROTOCOL_ERR

### ISSUE THREAD

**Issue by Mukesh-Kaushik** [dotnet/aspnetcore#52891]
### The server is returning response to web browser but not as expected.
The problem is **HTTPRESPONSE**.

Sample Code
`

                    var path = "somefile";
                    Response.ContentType = "application/json; charset=utf-8";                                                            
                    using var body = Response.Body;
                    using var fs = System.IO.File.OpenRead(path);
                    Response.ContentLength = fs.Length + 4;
                    await body.WriteAsync(Encoding.UTF8.GetBytes("["), 0, 1);
                    await fs.CopyToAsync(body);
                    await body.WriteAsync(Encoding.UTF8.GetBytes("{}]"), 0, 3);
                    await body.FlushAsync();
                    return Ok();

`
At backend, data(.net objects) is saved in file on daily basis as JSON string separated by comma. In the above action, I just reading the file and writing directly to outputStream with some delimiter to return as Json Array.

HTTP 2 causing ERROR.
No problem at HTTP 1.1 protocol.

**Comment by BrennanConroy** [comment]
`return Ok();` is attempting to set the status code of the response after you've already written data. If you look at the logs on your server you can see errors like:
```
System.InvalidOperationException: Headers are read-only, response has already started.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.set_ContentLength(Nullable`1 value)
```
Remove `return Ok();` and it'll probably work as expected.

**Comment by amcasey** [comment]
You probably don't want to dispose of `Response.Body`?

**Comment by Mukesh-Kaushik** [comment]
> You probably don't want to dispose of `Response.Body`? (i.e. seems like you want `var body`, rather than `using var body`.)

Disposing of Response Body Stream isn't causing issue here. Same implementation works for HTTP/1.1.


> `return Ok();` is attempting to set the status code of the response after you've already written data. If you look at the logs on your server you can see errors like:
> 
> ```
> System.InvalidOperationException: Headers are read-only, response has already started.
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.set_ContentLength(Nullable`1 value)
> ```
> 
> Remove `return Ok();` and it'll probably work as expected.

Take a look at this picture.
![Untitled](https://github.com/dotnet/aspnetcore/assets/154302654/7db96caa-dd6a-490a-aa79-9cf39b01a9bb)

first request is over http2 (b/w brower and server) and next 2 requests are over http1.1 (fiddler proxy MITM). Browser citing http2_protocol_err rejecting the response, I think it's  not well formatted by underlying server implementation.
you can verify this by regenerating it at your end.

It will yeild the same result when you try to return a txt file contents over http2 as text/plain.

**Comment by BrennanConroy** [comment]
> Take a look at this picture.

Yes, I realized that's the behavior. It could be any number of reasons, maybe the browser has poor behavior here, or Kestrel could be nicer when closing the connection, or the Http/2 spec isn't kind here. But it's not interesting to look into because you have a bug in your code that's causing it.

If you are still getting that after removing the bug then that's more interesting. And a minimal repro app as a github project would be useful.

**Comment by Mukesh-Kaushik** [comment]
hi, @BrennanConroy,  I'm back with something. 
I found error related to stream at http2 protocol level.
I hosted an API at [https://mmp972-001-site1.etempurl.com/weatherforecast/file](url) for you to test.
The provider using Out-of-process hosting with IIS and ASP.NET Core Hosting Model

My test result isbelow. Make me right if I'm wrong.

`

    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;
        private readonly IWebHostEnvironment _env;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IWebHostEnvironment env)
        {
            _logger = logger;
            _env = env;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }

        [HttpGet]
        [Route("file")]
        public async ValueTask GetFile()
        {
            var path = Path.Combine(_env.ContentRootPath, "test", "file.txt");
            Response.StatusCode = 200;
            Response.ContentType = "text/plain; charset=utf-8";

            using var fs = System.IO.File.OpenRead(path);
            Response.ContentLength = fs.Length;
            await fs.CopyToAsync(Response.Body);
            await Response.Body.FlushAsync();
        }
    }

`

Console App file attached here.
[program.cs.txt](https://github.com/dotnet/aspnetcore/files/13749693/program.cs.txt)

![output](https://github.com/dotnet/aspnetcore/assets/154302654/e6ad45a6-981a-4a13-b186-971736f917cd)

**Comment by BrennanConroy** [comment]
What OS are you hosting on? What version of ASP.NET Core are you using? What version is IIS?

Does this repro with IIS InProcess hosting? Does it repro without IIS?

Can you collect server logs?

**Comment by Mukesh-Kaushik** [comment]
Actually, it is Free Trial Asp.net hosting provided by sharkasp.net.

I don't have access to IIS logs.
The trial supports all .net core version and the api deployed there is targeted to .NET8.0

Information from control panel points to _IIS 10_ with _out of process_ deployment.
if it's IIS then it is windows but don't know exact version.

I hope this would help.

**Comment by Mukesh-Kaushik** [comment]
### Resolved

In case of HTTP2, flushing the HttpResponse's stream not working as usual, we have to complete the response to flush the response body.

`await Response.CompleteAsync();`
