### ISSUE TITLE
Rethink Auth in SignalR

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#5289]
Now that we have a handshake, we can consider adding support for sending authentication data over the transport instead of using the query sting (primarily for websockets). The other transports can use headers like normal but we would support sending the access token over the websocket channel.

/cc @blowdart @anurse

**Comment by anurse** [comment]
Broadening this. I don't know if it's feasible to send the token through the transport since the layering is a bit wrong. However, we have some ideas on how to improve some of the problems in the current auth story.

**Comment by Misiu** [comment]
Microsoft is using Chromium in new EDGE, so maybe now adding custom headers support will be easier.
There is an issue in spec repo - https://github.com/whatwg/html/issues/3062.
Please up-vote and comment on that issue.

**Comment by adamhathcock** [comment]
Hoping this can be picked up soon.  Having to explain to "security experts" in audits why there's something called access_token in a SignalR query string is starting to get old for me 😜

**Comment by davidfowl** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/5297
