### ISSUE TITLE
Build Error in Azure Pipeline when Building Blazor Project with MSBuild in Blazor WebAssembly Mode

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [dotnet/aspnetcore#52898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am encountering an error during the build process of a Blazor project in an Azure Pipeline. The project is set up to follow these steps:

1. Build the project in Blazor server mode (to run the source generator in related projects).
2. Change the project mode to Blazor Web Assembly using PowerShell.
3. Build the project.

However, when attempting to build the project in step 3 using MSBuild, the following error is encountered:

```plaintext
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(97,44): Error MSB4057: The target "ResolveWasmOutputs" does not exist in the project.
```

Remarkably, when performing the same step using DotNetCoreCLI instead of MSBuild, the error does not occur.

### Expected Behavior

The project should build successfully using MSBuild in the Blazor Web Assembly mode, just as it does with DotNetCoreCLI.

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@Cyrus-Sushiant thanks for contacting us.

```text
Build the project in Blazor server mode (to run the source generator in related projects).
Change the project mode to Blazor Web Assembly using PowerShell.
Build the project.
```

This is not likely to work without clearing the bin/obj folders and running restore again.
