### ISSUE TITLE
Add Redis benchmark to BenchmarkServer

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#5290]
There should be an option to run the benchmarks against redis. We'll also need to be able to point to an existing redis instance from the application.

**Comment by muratg** [comment]
@sebastienros We now have the code ready for this. Would you be able to help with setting up the infrastructure to get this running automatically? It would be running a Docker image for Redis server and configuring to use it.

**Comment by sebastienros** [comment]
Sure, I will create a Redis instance on the machines, and it will be available like any other database servers are. The host name will still be `TFB-database`, using the default port, and default configuration.

**Comment by muratg** [comment]
Thanks @sebastienros!

**Comment by anurse** [comment]
We think we can just do this by standing up a Redis server and having a single server hooked up to Redis to check the perf of the round-tripping. We'll look at this in 3.1 since it's infra only.
