### ISSUE TITLE
Blazor AOT Publish For Webassembly Hosted Application NET8.0

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#52905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I maked RunAotCompilation to true
It Still Not publish as aot i maked RunAotCompilation in the client project and it still not working

**Comment by javiercn** [comment]
@wisamidris7 thanks for contacting us.

AoT is only supported on the webassembly project, not on Blazor Web. Native AoT in Blazor Web (the server) is not supported in .net 8.0
