### ISSUE TITLE
Support for Blazor Events in Blazor SSR.

### ISSUE THREAD

**Issue by ndensan2029arai** [dotnet/aspnetcore#52919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blazor event handling for Razor components does not work with Blazor SSR.

### Describe the solution you'd like

ASP.NET Similar to WebForms, we want Blazor SSR to post back when a Blazor event occurs. Or call the REST API.

**Comment by javiercn** [comment]
@ndensan2029arai thanks for contacting us.

This is not a direction we are planning to move in the near future. It involves a lot of complexity for little pay off and can't generally be achieved without using JS.

**Comment by ndensan2029arai** [comment]
Can't I include JS in a Razor component?
