### ISSUE TITLE
Blazor WASM deployment to AWS S3 was working now failing with "Failed to find a valid digest in the 'integrity' attribute for resource"

### ISSUE THREAD

**Issue by baynezy** [dotnet/aspnetcore#52942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A new deployment of Blazor WASM to AWS S3 is now failing with "Failed to find a valid digest in the 'integrity' attribute for resource"

### Expected Behavior

The application should be updated and working correctly.

### Steps To Reproduce

* Deploy WASM application in AWS S3 with CloudFront. This works.
* Publish a new version with changes
* Overwrite the existing files in S3  `aws s3 sync ./web-publish/wwwroot s3://bucket-name --delete`

### Exceptions (if any)

All the `.wasm` files are reporting that `Failed to find a valid digest in the 'integrity' attribute for resource`

### .NET Version

8.0.100

### Anything else?

The application works fine for local development.

**Comment by javiercn** [comment]
@baynezy thanks for contacting us.

Check that the files are being downloaded correctly in the network tab (you are not getting 404) and check that you have correctly configured your caching directives.

**Comment by baynezy** [comment]
@javiercn thanks for your input. They were all returning 200 properly it just was failing with the aforementioned error.

Without making any changes it's resolved itself. So I'm pretty sure it's due to CloudFront caching. So I'll close this issue. Sorry to bother you, and thanks again.
